### PR TITLE
Add support for Gradle Kotlin DSL

### LINKED ISSUE #93238: Gradle Kotlin DSL support.
How should Flutter use Gradle Kotlin DSL?
I got many errors while trying to suggest Groovy to Kotlin.
I saw [33726](https://github.com/flutter/flutter/issues/33762) but didn't find a solution.

### PR DESCRIPTION
**Pull request by bartekpacia**
Attempts to fix #93238.

Gradle Kotlin DSL, at least for me, makes the experience of editing build scripts 10x better. Flutter developers should be able to harness this power :)

With this PR I'm aiming to make it possible to use `build.gradle.kts` instead of `build.gradle`, but there's more work to be done:
- update all documentation on the website to mention `build.gradle/build.gradle.kts` instead of only `build.gradle`
- update flutter tool's error messages to mention `build.gradle/build.gradle.kts` instead of only `build.gradle`
- add more tests for KTS buildscripts

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by bartekpacia** [comment]
I don't know why tool integration tests on Linux are failing - any help appreciated.

**Comment by bernaferrari** [comment]
I don't think Flutter supports Kotlin yet.

**Comment by bartekpacia** [comment]
> I don't think Flutter supports (from the verb, they don't want) Kotlin yet, unless it is probably a total migration from Groovy to Kotlin. But I might be wrong.

I'm not sure what you mean. 

This PR aims to let Flutter developers use [Gradle Kotlin DSL](https://docs.gradle.org/current/userguide/kotlin_dsl.html) in their Android buildscripts.

**Comment by bernaferrari** [comment]
Oh, I thought it was converting some scripts to KTS. I don't know then.

Kotlin is not an officially supported language in Flutter. You can attach Kotlin things, but the main.java won't be kotlin because they don't want an additional language, that's what I referred to.

**Comment by christopherfujino** [comment]
Asked in the discord server about adopting a PR from someone who has not signed the CLA

**Comment by bartekpacia** [comment]
@christopherfujino I CTRL+F the whole "flutter" discord but didn't find your question (I searched for `from:christopherfujino` and `cla`). Perhaps you made a typo and you meant to write "ask"? :D

**Comment by christopherfujino** [comment]
> @christopherfujino I CTRL-F-ed the whole "flutter" discord but didn't find your question (I searched for `from:christopherfujino` and `cla`). Perhaps you made a typo and you meant to write "ask"? :D

It was in a hidden chat room :D

**Comment by bartekpacia** [comment]
Closing because of CLA problems.

**Pull request closed without merging**
