### PR TITLE
Revert "Add SliverGrid and ScrollGrid"

### PR DESCRIPTION
**Pull request by Hixie**
Reverts flutter/flutter#7745

I propose temporarily reverting this to see if it was the cause of the flutter_gallery__build aot_snapshot_build_millis regression.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @abarth

**Comment by abarth** [comment]
Ok...  We could also just revert the part that touches the gallery, but feel free to do it this way if you think that's a cleaner experiment.  LGTM

**Comment by Hixie** [comment]
This is just easier 'cos it's one button. :-)

**Comment by abarth** [comment]
Reverting this change had no effect on the benchmark for 5 cycles.

**Pull request merged**
