### PR TITLE
[tool] Fix android tests using outdated regexs to modify templates

### PR DESCRIPTION
**Pull request by Sameri11**
**Description**

While exploring some semi-related stuff, found these 2 tests using outdated regex which does not work because AGP version in modern templates is set in `settings.gradle.kts` and in form of `com.android.application` instead of `com.android.tools.build:gradle`.

Apart from that, in `android_plugin_example_app_build_test.dart` deleted all lines regarding version change (instead of comply with new way of declaring plugin) because for a long time it's didn't work anyway: `replaceAll` haven't find any matches and test ran on latest AGP from template. More than that, attempt to adapt this test to modern AGP setup failed because build is not working with AGP < 8 (I lost logs with actual error for this case, but I believe I can reproduce if anyone wants)

in `native_assets_agp_version_test`: 

- Fixed version to comply with AGP versioning format, which is `major.minor.patch`.
- Updated regex and version changing logic to work with `com.android.application` format and `settings.gradle.kts` file. I believe that version updating is desired behavior here, unlike in `android_plugin_example_app_build_test.dart`. 
- Updated `kts` syntax for declaring flavors in `build.gradle.kts` and updated regex-based updating of this file (didn't work previously because there wasn't actual writing to file)

didn't list any issues because there're not any regarding these tests (or maybe I just failed to find). In any case, I think that this doesn't require issue because fix is kinda trivial and motivation is clear.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by bkonyi** [comment]
@Sameri11 is there an issue filed for this by any chance?

**Review by gmackall — APPROVED** [review]
This LGTM, thanks for updating these tests. Can you change the PR title to be a bit more descriptive before merging? Something like "Fix android tests using outdated regexs to modify templates".

Not in this pr, but: these string modifications that we make on the template outputs are all really fragile. Perhaps it would be good in the future to expose some common `@visibileForTesting` constructor of a fake `AndroidProject` with unified methods for the common actions we do, like changing the AGP version.

**Comment by Sameri11** [comment]
@bkonyi there's not, unfortunately. Or maybe I failed to find one. I decided to not create one, because changes are relatively small and motivation is clear (to fix wrong behavior). But since you asked - maybe I'm wrong and I should create issue on that matter?

**Comment by Sameri11** [comment]
@gmackall thanks for review! I changed title as you suggested.

**Review by bkonyi — APPROVED** [review]

**Pull request merged**
