### PR TITLE
Update Tab semantics in Cupertino to be the same as Material

### PR DESCRIPTION
**Pull request by shihaohong**
## Description

This PR updates the Cupertino tab semantics label to be the same as the Material tab semantics label.

## Tests

I added the following tests:
- n/a, updating the english message translation

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Thanks for the quick fix!
I am surprised CI didn't complain, there is a test that checks the string in bottom_tab_bar_test.dart: https://github.com/flutter/flutter/blob/13501af6e61e7623d5e3663aa16a934aa3a2f138/packages/flutter/test/cupertino/bottom_tab_bar_test.dart#L367
I would expect that test to fail now..

**Review by Piinks — APPROVED** [review]
LGTM!

**Comment by shihaohong** [comment]
I figured out the problem, turns out the string value for DefaultCupertinoLocalizations had not been updated. This would then mean that this change is a breaking one, since if anybody has tests that assume that the label was in the format `tab, {index} of {totalCount}`, those will break and will need to adjust it to be `Tab {index} of {totalCount]`.

I can write a migration guide for this and send out a quick breaking change announcement as well.

**Comment by Piinks** [comment]
My migration guide has not landed yet, we could just add to it

**Comment by shihaohong** [comment]
Migration guide available [here](https://docs.google.com/document/d/1iTkmhJzT4Z2eplRXUgeTwEWJ0rtpCWE0_P88QqFr43c/edit?usp=sharing).

**Comment by shihaohong** [comment]
@Piinks Oops, just saw your comment! That sounds like a good plan, let's just use yours and you can incorporate the content on the very short one I just shared :)

**Pull request merged**
