### PR TITLE
Partially fix Dart 2 issues in animated_icons.test.

### PR DESCRIPTION
**Pull request by mraleph**
It should be using `typed(any)` instead of `any` and
`PaintColorMatcher` should implement `ui.Paint`.

### CODE REVIEW

**Review by amirh — APPROVED** [review]
LGTM

**Comment by amirh** [comment]
Analyzer seems unhappy

**Comment by mraleph** [comment]
@amirh :-/ I will figure it out tomorrow.

**Comment by mraleph** [comment]
@amirh I figured out how to hold mockito - please take another look.

**Review by amirh — APPROVED** [review]
LGTM

**Pull request merged**
