### PR TITLE
fix:#140301  :bug: bottom_navigation_bar_item  nullable label attribute changed to required attribute.

### PR DESCRIPTION
**Pull request by ArunChapagain**
Fixes:#140301 and #113891 
Previously the label attribute of class BottomNavigationBarItem can be null which create the excetion as in bottom_navigation_bar.dart in line  248 the label are checked for not null value. Hence label attribute in BottomNavigationBarItem is made required which solve the error

Before:

Screenshot 2023-12-18 075502

Screenshot 2023-12-18 083853

Screenshot 2023-12-18 083903

After:

Screenshot 2023-12-18 081130

image

Screenshot 2023-12-18 080731

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
Looks like this change is failing a lot of checks can you please take a look at those? Also, as pointed out by the bot above, it is missing a test. Can you please add one? Thanks.

**Comment by goderbauer** [comment]
Also, have you checked other places that take a BottomNavigationBarItem? I believe the [CupertinoTabBar](https://main-api.flutter.dev/flutter/cupertino/CupertinoTabBar-class.html) also takes one and I am not sure if it always requires a label. If it doesn't, then we cannot make this required.

**Comment by ArunChapagain** [comment]
I will make sure that of CupertinoTabBar and update the test.

**Comment by goderbauer** [comment]
> Is it ok to make bottom_navigation_bar_item nullable in bottom_navigation_bar_also

I am not sure what you mean by this, could you elaborate?

**Comment by goderbauer** [comment]
I am going to close this since there hasn't been a follow-up. Feel free to reopen if you plan to work on this again. Thank you.

**Pull request closed without merging**
