### PR TITLE
Warn when using building release app on master channel

### PR DESCRIPTION
**Pull request by GaryQian**
See https://github.com/flutter/flutter/issues/24984

### CODE REVIEW

**Comment by zanderso** [comment]
@GaryQian what's the status of this PR? I'll add the reviewers from the previous attempt at this.

**Comment by GaryQian** [comment]
I haven't had a chance to make the proper adjustments to make sure this is not happening on run also. I'll get back to this later as things with higher priority are currently on my plate.

**Comment by jonahwilliams** [comment]
@GaryQian if you're not working on this could we close it for now?

**Comment by jonahwilliams** [comment]
@GaryQian I'm going to close this PR for now, feel free to get back to it later

**Pull request closed without merging**
