### PR TITLE
[web] Always send the route name even if it's null

### LINKED ISSUE #41375: [Web] Navigation and window href
## Problem

Hi, I am testing a web app with flutter and the url doesn't change as expected when pushing a route from navigation. 

By default the url doesn't change from https://<..>/#/ but sometimes it also appears the name of  a new route like https://<..>/#/dashboard.

Captura de pantalla 2019-09-26 a las 16 17 34

 Using the native chrome navigation for going forward and back doesn't work either as expected. 

### Proposal
I have been testing my self an example of how I would do it.
1. If you are in the route /page1 your url would look like  https://<..>/#/page1
2. If you are in the route /page2 your url would look like  https://<..>/#/page2
3. If you change routes it updates the url

ezgif-4-29054d4381e5

```dart


import 'dart:html' as html;

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
            initialRoute: '/page1',
            onGenerateRoute: (settings)  {
               html.window.history.pushState(null, settings.name, '#' + settings.name);
               print(html.window.location.href);
               switch(settings.name) {
                 case '/page1': return MaterialPageRoute(builder: (_) => Page1());
                 case '/page2': return MaterialPageRoute(builder: (_) => Page2());
               }
               return MaterialPageRoute(builder: (_) => Page1());
            },
            title: 'History test'
    );
  }
}


class Page1 extends StatelessWidget
{
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      backgroundColor: Colors.green,
      appBar: AppBar(title: Text('Page 1'),),
      body: Center(
        child: FlatButton(
          child: Text('Go to page 2'),
          onPressed: () => {
              Navigator.of(context).pushNamed('/page2')
          },
        ),
      ),
    );
  }

}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red,
      appBar: AppBar(title: Text('Page 2'), leading: Container(),),
      body: Center(
        child: FlatButton(
          child: Text('Go back'),
          onPressed: ()  {
            if(Navigator.of(context).canPop()) {
              Navigator.pop(context);
              html.window.history.pushState(null, null, '#' + '/page1');
            } else {Navigator.pushReplacementNamed(context, '/page1');}
          },
        ),
      ),
      
    );
  }

}
```

(the example doesn't work with the navigation native buttons for pushing back and forward.  )

### PR DESCRIPTION
**Pull request by mdebbar**
## Description

When a nameless route is pushed, we should be sending a platform message with route name as `null` in order for the engine to be able clear the browser url.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/41375

## Tests

I added tests in following files:

* `test/widgets/route_notification_messages_test.dart`

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by goderbauer** [comment]
Is clearing really the right choice? If I am on page x and I press a button to bring up some kind of a pop-up route (which I believe is implemented as nameless route) it still feels like I am on page x.

**Comment by goderbauer** [comment]
(Unrelated to this PR:) It also looks like the way these notifications work don't work with nested navigators.

**Comment by mdebbar** [comment]
> If I am on page x and I press a button to bring up some kind of a pop-up route (which I believe is implemented as nameless route) it still feels like I am on page x.

@goderbauer that's a good point. But the problem is how can we distinguish between pop-up routes and real routes that happen to have no name?

> It also looks like the way these notifications work don't work with nested navigators.

If that's the case, I'd love to fix it :) Could you elaborate please?

**Comment by goderbauer** [comment]
If you have a root navigator and a nested navigator B. If you navigate to a different page within B, the URL bar will only show the route within B. It doesn't show the route within the root navigator anymore to get to the page that contained the nested navigator.

**Review by nturgut — APPROVED** [review]
Thanks!

**Pull request merged**
