### PR TITLE
Clamp TabController animation value when calc _DragAnimation.value

### PR DESCRIPTION
**Pull request by smadey**
## Description

see [demo](https://dartpad.dev/cf3e344cfdb5aa08a17c0d36aeaa0681)

## Tests

None

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

No

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hi @smadey, welcome! And thank you for the contribution. 🎉 
Is there an open issue that this change will resolve that we can reference? 
This will also need a test to ensure we do not break it in the future. :)

**Review by Piinks — COMMENTED** [review]
Hey @smadey! Would you like to continue working on this pull request?

**Comment by smadey** [comment]
> Hey @smadey! Would you like to continue working on this pull request?

I am busy at work now, I will follow up when I have time

**Comment by smadey** [comment]
close by #61609

**Pull request closed without merging**
