### PR TITLE
Deprecate these old APIs

### PR DESCRIPTION
**Pull request by Hixie**
Upstream clients have been updated now.

### CODE REVIEW

**Comment by goderbauer** [comment]
go_router has been fixed up here (landed): https://github.com/flutter/packages/pull/3599
fix for pigeon has been suggested here (pending feedback): https://github.com/flutter/packages/pull/3600

I'll close my attempt of doing the same thing at https://github.com/flutter/flutter/pull/123812.

**Comment by Hixie** [comment]
Fixes https://github.com/flutter/flutter/issues/108327

**Comment by goderbauer** [comment]
The pigeon fix rolled in with https://github.com/flutter/flutter/pull/124031. I would expect that rebasing this will turn all checks green now.

**Review by goderbauer — APPROVED** [review]
LGTM

Checks are all green!

**Pull request merged**
