### PR TITLE
Update hello_world_memory_test package name

### PR DESCRIPTION
**Pull request by cbracken**
Broken by 89af5ec8c7c6012746482256b9b7459727526f32.

### CODE REVIEW

**Review by yjbanov — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
LGTM but bonus points for making the logs make this failure mode much more obvious

**Comment by cbracken** [comment]
Looks like there's an `adb pm list packages` command that ostensibly lists all packages. We can filter that for and report 'no such package' on device. I'll put together a follow-up patch.

**Comment by cbracken** [comment]
Filed #9706

**Pull request merged**
