### PR TITLE
add readme pt-br translation

### PR DESCRIPTION
**Pull request by saulojoab**
## Description

just translated the README.md to pt-br. 
im not sure if there are any errors, because for some reason the preview tab isnt working.
this contribution is part of my [hacktoberfest](https://hacktoberfest.digitalocean.com) pull requests!

## Related Issues

there are no especific issues, just trying to make it easier for brazilian folks to know what flutter is all about

## Checklist

- [ X ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ X ] I signed the [CLA].
- [ X ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ X ] I updated/added relevant documentation (doc comments with `///`).
- [ X ] All existing and new tests are passing.
- [ X ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ X ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [ X ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by saulojoab** [comment]
@googlebot I signed it!

**Comment by bernaferrari** [comment]
Why? Is this needed at all?

**Comment by saulojoab** [comment]
@bernaferrari I mean, it's kinda helpful if you're not very good at English. As I said, I made this almost exclusively as a contribution to hacktoberfest, but who knows. Maybe this can help someone.

**Comment by bernaferrari** [comment]
But the documentation is short, all its links are in English and there would be the increased maintenance cost, because every time the Readme changes you would need to re-translate what chanted. I see this causing more issues than helping.

**Comment by saulojoab** [comment]
@bernaferrari well, as I said. it isn't supposed to be a game-changer feature or anything. maybe something that might be useful in the future :p as I said, I mainly did this for hacktoberfest

**Comment by goderbauer** [comment]
Thanks for the contribution. I don't think we want to maintain the readme in different languages in our repository.

**Pull request closed without merging**
