### PR TITLE
[WIP] Toggle buttons directionality

### PR DESCRIPTION
**Pull request by Calamity210**
## Description

Added `Axis direction` to `ToggleButtons` along which the buttons are rendered. While it does not allow `ToggleButtons` to wrap due to wrap not playing nicely with `IntrinsicHeight` and `IntrinsicWidth`, it allows them to be rendered vertically.

## Related Issues

https://github.com/flutter/flutter/issues/63871

## Tests

I have modified:
- toggle_buttons_test.dart

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Comment by LockedThread** [comment]
Thanks for making a PR for this

**Review by shihaohong — COMMENTED** [review]
Hi, thank you for the PR! There seems to be a lot of cosmetic changes unrelated to toggle button directionality. Could you please revert those changes and keep the PR changes relevant?

**Comment by Calamity210** [comment]
@shihaohong hey, thanks for reviewing. Can you please elaborate on which changes exactly you are referring to? Thanks!

**Comment by shihaohong** [comment]
I'm referring to changes like [these](https://github.com/flutter/flutter/pull/63880/files#diff-3f9fe7873cc464fc72ed7438b12bbde8R510) that do not provide any functionality changes to the code. It's a lot easier to do code reviews and track git history for those lines of code if the PR is unrelated.

**Comment by Calamity210** [comment]
ah, my bad, i must've run dartfmt subconsciously. I've corrected them @shihaohong

**Comment by shihaohong** [comment]
Hi @Calamity210, is this still a draft PR, or is it ready for review?

**Comment by Calamity210** [comment]
> Hi @Calamity210, is this still a draft PR, or is it ready for review? 

@shihaohong Im pretty sure I had resolved the comment made by you earlier, but windows-tool-test was failing and I havent gotten around to take a look at it yet.

Not quite sure if the failing test is necessarily related to this pr, but will take a look soon.

**Comment by shihaohong** [comment]
I see -- I had refrained from reviewing the PR since I saw it was marked as draft. I'll look into it once the Windows test is passing. It seems like a flaky test, since your change shouldn't involve any tools tests. Maybe you'll need to rebase with the `master` branch to get things in order.

**Comment by shihaohong** [comment]
I see that a new commit was introduced but the PR is still marked as a draft. There's also merge conflicts likely from the NNBD migration. Could you mark the PR as ready for review once it is? Thanks!

**Comment by Calamity210** [comment]
For sure, its just taking a while as Ive been working on other things and havent gotten to it

**Comment by Calamity210** [comment]
closing as I dont think ill be working on it anytime soon

**Pull request closed without merging**
