### PR TITLE
Added comment for INTERNET permission in Android manifest

### LINKED ISSUE #6834: Add comment to Android manifest file explaining Internet permission
## Steps to Reproduce

Things worked fine yesterday, and today I can't launch my app. I haven't updated my flutter install in case this error goes away magically.

Run `flutter run` or launch debug run configuration from intellij

Note:
- Restarting the phone doesn't solve the issue.
- Restarting intelliJ doesn't solve the issue.
- Restarting the computer doesn't solve the problem.
- (edit) Upgrading flutter doesn't solve the issue

## Logs

With `-v` flag:

```
 ❯ flutter run -v                                                                                                                                                                                                        [11:36:46]
[  +40 ms] /opt/android-sdk/platform-tools/adb devices -l
[   +4 ms] Exit code 0 from: /opt/android-sdk/platform-tools/adb devices -l
[        ] List of devices attached
           84B7N15A10004400       device usb:1-1.5 product:angler model:Nexus_6P device:angler
[   +6 ms] /opt/android-sdk/platform-tools/adb -s 84B7N15A10004400 shell getprop
[ +145 ms] /home/joel/code/flutter/bin/cache/artifacts/engine/linux-x64/sky_snapshot --packages=/home/joel/code/dart/catalogue-mouches/.packages --print-deps /home/joel/code/dart/catalogue-mouches/lib/main.dart
[ +148 ms] Exit code 0 from: /home/joel/code/flutter/bin/cache/artifacts/engine/linux-x64/sky_snapshot --packages=/home/joel/code/dart/catalogue-mouches/.packages --print-deps /home/joel/code/dart/catalogue-mouches/lib/main.dart
[   +8 ms] Running build command.
[   +3 ms] APK up to date; skipping build step.
[        ] Stopping app 'app.apk' on Nexus 6P.
[   +1 ms] /opt/android-sdk/platform-tools/adb -s 84B7N15A10004400 shell am force-stop com.stacktrace.mouches
[ +849 ms] Running install command.
[   +1 ms] /opt/android-sdk/platform-tools/adb version
[   +4 ms] Exit code 0 from: /opt/android-sdk/platform-tools/adb version
[        ] Android Debug Bridge version 1.0.36
           Revision 84e3321d5db3-android
[   +1 ms] /opt/android-sdk/platform-tools/adb start-server
[   +8 ms] Exit code 0 from: /opt/android-sdk/platform-tools/adb start-server
[        ] Installing build/app.apk...
[        ] /opt/android-sdk/platform-tools/adb -s 84B7N15A10004400 install -r build/app.apk
[+2883 ms] Exit code 0 from: /opt/android-sdk/platform-tools/adb -s 84B7N15A10004400 install -r build/app.apk
[   +1 ms] /opt/android-sdk/platform-tools/adb -s 84B7N15A10004400 shell echo -n 7afa556819325c1d83d4aba0bf5927f6289be070 > /data/local/tmp/sky.com.stacktrace.mouches.sha1
[  +20 ms] Exit code 0 from: /opt/android-sdk/platform-tools/adb -s 84B7N15A10004400 shell echo -n 7afa556819325c1d83d4aba0bf5927f6289be070 > /data/local/tmp/sky.com.stacktrace.mouches.sha1
[  +15 ms] /opt/android-sdk/platform-tools/adb -s 84B7N15A10004400 logcat -v time -t 1
[  +68 ms] Exit code 0 from: /opt/android-sdk/platform-tools/adb -s 84B7N15A10004400 logcat -v time -t 1
[        ] --------- beginning of main
           11-13 11:36:49.993 W/System  (12133): ClassLoader referenced unknown path: /system/app/KeyChain/lib/arm64
[  +11 ms] Launching loader on Nexus 6P...
[        ] /opt/android-sdk/platform-tools/adb -s 84B7N15A10004400 logcat -v time
[        ] /opt/android-sdk/platform-tools/adb version
[   +4 ms] Exit code 0 from: /opt/android-sdk/platform-tools/adb version
[        ] Android Debug Bridge version 1.0.36
           Revision 84e3321d5db3-android
[        ] /opt/android-sdk/platform-tools/adb start-server
[   +8 ms] Exit code 0 from: /opt/android-sdk/platform-tools/adb start-server
[   +3 ms] /home/joel/code/flutter/bin/cache/artifacts/engine/linux-x64/sky_snapshot --packages=/home/joel/code/dart/catalogue-mouches/.packages --snapshot=build/snapshot_blob.bin --depfile=build/snapshot_blob.bin.d --build-output=build/snapshot_blob.bin /home/joel/code/flutter/packages/flutter/bin/loader/loader_app.dart
[ +211 ms] Building build/app.flx
[ +101 ms] which zip
[   +4 ms] Encoding zip file to build/app.flx
[  +12 ms] [build/flx/] zip -q /home/joel/code/dart/catalogue-mouches/build/app.flx fonts/MaterialIcons-Regular.ttf AssetManifest.json FontManifest.json LICENSE snapshot_blob.bin
[  +76 ms] Exit code 0 from: zip -q /home/joel/code/dart/catalogue-mouches/build/app.flx fonts/MaterialIcons-Regular.ttf AssetManifest.json FontManifest.json LICENSE snapshot_blob.bin
[        ] [build/flx/] zip -q -0 /home/joel/code/dart/catalogue-mouches/build/app.flx lib/assets/black_woolly_bugger.jpg lib/assets/streamer.jpg lib/assets/caddis.jpg lib/assets/caddis_real.jpg lib/assets/minnows.jpg lib/assets/sangsue_eau.jpg lib/assets/samplehook.jpg lib/assets/green_drake_nymph.jpg lib/assets/mickey_finn.jpg
[   +8 ms] Exit code 0 from: zip -q -0 /home/joel/code/dart/catalogue-mouches/build/app.flx lib/assets/black_woolly_bugger.jpg lib/assets/streamer.jpg lib/assets/caddis.jpg lib/assets/caddis_real.jpg lib/assets/minnows.jpg lib/assets/sangsue_eau.jpg lib/assets/samplehook.jpg lib/assets/green_drake_nymph.jpg lib/assets/mickey_finn.jpg
[        ] Built build/app.flx.
[        ] Starting bundle for Nexus 6P.
[   +1 ms] Nexus 6P startBundle
[        ] /opt/android-sdk/platform-tools/adb -s 84B7N15A10004400 push build/app.flx /data/local/tmp/dev.flx
[  +80 ms] Exit code 0 from: /opt/android-sdk/platform-tools/adb -s 84B7N15A10004400 push build/app.flx /data/local/tmp/dev.flx
[        ] [  4%] /data/local/tmp/dev.flx
           [  8%] /data/local/tmp/dev.flx
           [ 13%] /data/local/tmp/dev.flx
           [ 17%] /data/local/tmp/dev.flx
           [ 21%] /data/local/tmp/dev.flx
           [ 26%] /data/local/tmp/dev.flx
           [ 30%] /data/local/tmp/dev.flx
           [ 34%] /data/local/tmp/dev.flx
           [ 39%] /data/local/tmp/dev.flx
           [ 43%] /data/local/tmp/dev.flx
           [ 47%] /data/local/tmp/dev.flx
           [ 52%] /data/local/tmp/dev.flx
           [ 56%] /data/local/tmp/dev.flx
           [ 60%] /data/local/tmp/dev.flx
           [ 65%] /data/local/tmp/dev.flx
           [ 69%] /data/local/tmp/dev.flx
           [ 74%] /data/local/tmp/dev.flx
           [ 78%] /data/local/tmp/dev.flx
           [ 82%] /data/local/tmp/dev.flx
           [ 87%] /data/local/tmp/dev.flx
           [ 91%] /data/local/tmp/dev.flx
           [ 95%] /data/local/tmp/dev.flx
           [100%] /data/local/tmp/dev.flx
[        ] /opt/android-sdk/platform-tools/adb -s 84B7N15A10004400 shell am start -a android.intent.action.RUN -d /data/local/tmp/dev.flx -f 0x20000000 --ez enable-background-compilation true --ez enable-checked-mode true com.stacktrace.mouches/org.domokit.sky.shell.SkyActivity
[ +529 ms] Exit code 0 from: /opt/android-sdk/platform-tools/adb -s 84B7N15A10004400 shell am start -a android.intent.action.RUN -d /data/local/tmp/dev.flx -f 0x20000000 --ez enable-background-compilation true --ez enable-checked-mode true com.stacktrace.mouches/org.domokit.sky.shell.SkyActivity
[        ] Starting: Intent { act=android.intent.action.RUN dat=/data/local/tmp/dev.flx flg=0x20000000 cmp=com.stacktrace.mouches/org.domokit.sky.shell.SkyActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +468 ms] I/flutter (12297): Could not start Observatory HTTP server:
[        ] I/flutter (12297): SocketException: Failed to create server socket (OS Error: Permission denied, errno = 13), address = 127.0.0.1, port = 0
[        ] I/flutter (12297): #0      _NativeSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:524)
[        ] I/flutter (12297): #1      _RootZone.runUnary (dart:async/zone.dart:1404)
[        ] I/flutter (12297): #2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
[        ] I/flutter (12297): #3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
[        ] I/flutter (12297): #4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
[        ] I/flutter (12297): #5      _Future._completeWithValue (dart:async/future_impl.dart:477)
[        ] I/flutter (12297): #6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
[        ] I/flutter (12297): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
[        ] I/flutter (12297): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[        ] I/flutter (12297): #9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
[        ] I/flutter (12297): #10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
[        ] I/flutter (12297): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/i
[  +38 ms] E/DartVM  (12297): vm-service: Error: Unhandled exception:
[        ] E/DartVM  (12297): SocketException: Failed to create server socket (OS Error: Permission denied, errno = 13), address = 127.0.0.1, port = 0
[        ] E/DartVM  (12297): #0      _NativeSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:524)
[        ] E/DartVM  (12297): #1      _RootZone.runUnary (dart:async/zone.dart:1404)
[        ] E/DartVM  (12297): #2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
[        ] E/DartVM  (12297): #3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
[        ] E/DartVM  (12297): #4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
[        ] E/DartVM  (12297): #5      _Future._completeWithValue (dart:async/future_impl.dart:477)
[        ] E/DartVM  (12297): #6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
[        ] E/DartVM  (12297): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
[        ] E/DartVM  (12297): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[        ] E/DartVM  (12297): #9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[        ] E/DartVM  (12297): #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
[        ] E/DartVM  (12297): 
[        ] E/flutter (12297): [ERROR:../../flutter/runtime/dart_init.cc(137)] Isolate vm-service exited with an error
[        ] E/flutter (12297): [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
[        ] E/flutter (12297): SocketException: Failed to create server socket (OS Error: Permission denied, errno = 13), address = 127.0.0.1, port = 0
[        ] E/flutter (12297): #0      _NativeSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:524)
[        ] E/flutter (12297): #1      _RootZone.runUnary (dart:async/zone.dart:1404)
[        ] E/flutter (12297): #2      _FutureListener.handleValue (dart:async/future_impl.dart:131)
[        ] E/flutter (12297): #3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
[        ] E/flutter (12297): #4      _Future._propagateToListeners (dart:async/future_impl.dart:667)
[        ] E/flutter (12297): #5      _Future._completeWithValue (dart:async/future_impl.dart:477)
[        ] E/flutter (12297): #6      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
[        ] E/flutter (12297): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
[        ] E/flutter (12297): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
[        ] E/flutter (12297): #9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
[        ] E/flutter (12297): #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

## Flutter Doctor
```
 ❯ flutter doctor                                                                                                                                                                                                        [11:38:18]
[✓] Flutter (on Linux, channel master)
    • Flutter at /home/joel/code/flutter
    • Framework revision d0ff41ec35 (3 days ago), 2016-11-10 15:33:02
    • Engine revision 84a060820a
    • Tools Dart version 1.21.0-dev.3.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-25, build-tools 25.0.0
    • ANDROID_HOME = /opt/android-sdk
    • Java(TM) SE Runtime Environment (build 1.8.0_112-b15)

[✓] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • Dart plugin installed
    • Flutter plugin installed

[✓] Connected devices
    • Nexus 6P • 84B7N15A10004400 • android-arm • Android 7.1.1 (API 25)
```

### PR DESCRIPTION
**Pull request by Pacane**
Fixes https://github.com/flutter/flutter/issues/6834

@eseidelGoogle @Hixie

### CODE REVIEW

**Comment by Hixie** [comment]
We should say more, e.g. that the flutter tool uses it to communicate with the running application to provide hot reload, etc.

**Comment by Pacane** [comment]
Sure, want me to put just that, or do we have an official list features requiring this permission?

**Comment by Hixie** [comment]
LGTM

**Comment by chinmaygarde** [comment]
If this patch is good to go. Can we land this?

**Comment by sethladd** [comment]
Really cool, thanks for the patch!

**Pull request merged**
