### PR TITLE
Fix outline button solid path when BorderSize.width is used

### LINKED ISSUE #49287: [web] OutlineButton borders disappear with resolution changes
On web the top and left borders of an `OutlineButton` disappear and reappears as the window is resized. 

Currently experiencing on this on dev 1.14.3. I tried to run it on master, but ran into this problem:  https://github.com/flutter/flutter/issues/49103#issuecomment-577005820

## Steps to Reproduce

[Minimal sample repo](https://github.com/buntagonalprism/outline_button_edge_issue)
main.dart from the sample repo - just add an Outline button to the starter project:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() => _counter++);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Outline Button Edge Issue'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('You have pushed the button this many times:'),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
            OutlineButton(
              child: Text('Increment'),
              onPressed: _incrementCounter,
            ),
          ],
        ),
      ),
    );
  }
}
```

**Expected results:** 
All borders present around outline button
working-resolution

**Actual results:** 
Left edge of border missing at some resolutions
broken-resolution

<details>
  <summary>Logs</summary>

```
flutter run -d chrome --verbose
[  +28 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +125 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] b5a23fdf5bc01e292238627f031a34ed0adb80b0
[        ] executing: [C:\flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +88 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +4 ms] v1.14.3-0-gb5a23fdf5
[  +11 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +58 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +48 ms] Exit code 0 from: git ls-remote --get-url origin
[   +4 ms] https://github.com/flutter/flutter.git
[  +96 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +65 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +59 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +38 ms] executing: C:\Users\t\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +24 ms] Exit code 0 from: C:\Users\t\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +10 ms] List of devices attached
[  +14 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +17 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +200 ms] Generating C:\git\issues\outline_button_edge_issue\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +146 ms] Launching lib\main.dart on Chrome in debug mode...
[   +2 ms] Building application for the web...
[+8762 ms] Starting daemon...
[ +176 ms] Initializing inputs
[  +14 ms] Reading cached asset graph...
[ +246 ms] Reading cached asset graph completed, took 243ms

[ +301 ms] Checking for updates since last build...
[ +645 ms] Checking for updates since last build completed, took 645ms

[  +15 ms] Initializing inputs
[   +8 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 243ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 645ms
[ +952 ms] About to build [web]...
[   +4 ms] Running build...
[ +180 ms] Running build completed, took 104ms

[   +1 ms] Caching finalized dependency graph...
[  +17 ms] Caching finalized dependency graph completed, took 112ms

[   +1 ms] Succeeded after 223ms with 0 outputs (0 actions)

[  +12 ms] Building application for the web... (completed in 11.3s)
[   +7 ms] Attempting to connect to browser instance..
[+8510 ms] Debug service listening on ws://127.0.0.1:56551/osDqWPAApPs=

[ +389 ms]       Failed to load asset at path: packages/build_web_compilers/src/dev_compiler/dart_sdk.js.

                          Status code: 404

                          Headers:
                          {
                      "date": "Wed, 22 Jan 2020 10:12:51 GMT",
                      "content-length": "9",
                      "x-frame-options": "SAMEORIGIN",
                      "content-type": "text/plain; charset=utf-8",
                      "x-xss-protection": "1; mode=block",
                      "x-content-type-options": "nosniff",
                      "server": "dart:io with Shelf",
                      "via": "1.1 shelf_proxy"
                    }

                          Content:
                          Not Found}

[  +50 ms] Attempting to connect to browser instance.. (completed in 8.9s)
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[  +20 ms] �🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[   +8 ms] Debug service listening on ws://127.0.0.1:56551/osDqWPAApPs=
```

```
flutter analyze
Analyzing outline_button_edge_issue...
No issues found! (ran in 9.7s)
```

```
flutter doctor -v
[√] Flutter (Channel dev, v1.14.3, on Microsoft Windows [Version 10.0.18362.592], locale en-AU)
    • Flutter version 1.14.3 at C:\flutter
    • Framework revision b5a23fdf5b (16 hours ago), 2020-01-22 02:11:09 +0800
    • Engine revision c15efb9231
    • Dart version 2.8.0 (build 2.8.0-dev.3.0 f910a7575f)

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\t\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\t\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.130
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by ferhatb**
## Description

_OutlineBorder shape thickness was not correctly adjusting the outerpath bounds to paint at correct thickness. At very low values, this was causing the outline path from being clipped at subpixel causing https://github.com/flutter/flutter/issues/49287.

The problem was not visible on mobile since viewport width is even. Resizing a browser window to odd width and continuous resizing uncovered issue.

* This PR also updates paint matcher to provide path bounds when reporting an error for included/excluded Offsets to aid in debugging test failures.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/49287

## Tests

Added a test case to outline_button_test.dart to make sure we are stroking path at offset+=thickness/2.0.

## Breaking change

OutlineButton(s) were clipping half of stroke width before this change. So visually the border will render 0.5pixels larger in most use cases.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Review by mdebbar — APPROVED** [review]

**Comment by ferhatb** [comment]
Sample diff of 2 outline buttons showing before/diff/after:
Screen Shot 2020-02-28 at 12 18 02 PM

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by Piinks** [comment]
@ferhatb is it ok to merge this PR?

**Comment by ferhatb** [comment]
> @ferhatb is it ok to merge this PR?

@Piinks : It is a breaking change in terms of goldens. Any pointers to prior flow to get this in ?

**Comment by Piinks** [comment]
> > @ferhatb is it ok to merge this PR?
> 
> @Piinks : It is a breaking change in terms of goldens. Any pointers to prior flow to get this in ?

Looks like it did not break any existing golden files, so this LGTM

**Comment by Piinks** [comment]
The tree is green, but the status has not updated here. Merging manually. The status doesn't seem to have been updated for a few days.

**Pull request merged**
