### PR TITLE
Step 2 of 3: Change opt-in default for debugCheckHasMaterialLocalizations assertion on TextField

### PR DESCRIPTION
**Pull request by Piinks**
## Description

Follow-up change to https://github.com/flutter/flutter/pull/56090. This changes the default value of the opt-in flag for asserting MaterialLocalizations on TextField. This is step 2 in a 3 part change to migrate to the new behavior.

### Example migration steps

1. Set all `TextField` instances in app to have `canAssertMaterialLocalizations` be true. 
```dart
TextField(
  canAssertMaterialLocalizations: true, // add this line
  // ...
)
```

2. Examine all screens with TextField to ensure that Material Localizations are present, make sure existing unit tests are not breaking. If something is broken, fix it. An example of a test that might fail is if a unit test was using a TextField without a MaterialApp or Localizations ancestor. If the issue cannot be fixed, it may not be an intended change, so file an issue to `flutter/flutter` on GitHub. 

3. A new PR will be introduced in the future to set `TextField.canAssertMaterialLocalizations` to `true` by default. This will default everybody's TextField to the latest design by default. If developers have properly migrated in step 2, this shouldn't cause any issues to your app. This would be the opportunity to remove the `canAssertMaterialLocalizations` parameter from your application since it is true by default now and it will be removed in a subsequent PR.
```dart
TextField(
  // canAssertMaterialLocalizations: true, // remove this line, since it should be true by default at this point.
  // ...
)
```

4. Finally, a final PR will remove the `canAssertMaterialLocalizations` parameter altogether. If you removed the `canAssertMaterialLocalizations` parameter from your `TextField` instances in step 3, this should not affect your application.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. _Non-breaking phased plan_
   - [x] I got input from the developer relations team
   - [x] I wrote a migration guide: for when we get to step 3

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Piinks** [comment]
This is waiting on step one to have rolled to dev.

**Comment by Piinks** [comment]
Update: the change has rolled to dev, currently identifying/migrating clients to land this next step.

**Comment by Piinks** [comment]
I have checked against the roll, this is ready to land. :)

**Review by justinmc — APPROVED** [review]
LGTM 👍

**Pull request merged**
