### PR TITLE
Fix wrap compute max intrinsic width/height with spacing

### LINKED ISSUE #82289: RenderWrap.computeMaxIntrinsicWidth does not calculate spacing, resulting in improper line feeds.
code: 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    var data = 'test test test test test test test test test test';
    return MaterialApp(
        title: _title,
        home: Scaffold(
          body: IntrinsicWidth(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Container(
                  color: Colors.blue,
                  padding: const EdgeInsets.all(8.0),
                  width: 245,
                ),
                Wrap(
                  alignment: WrapAlignment.spaceBetween,
                  runAlignment: WrapAlignment.end,
                  spacing: 8,
                  children: [
                    Text(data),
                    Text('date time')
                  ],
                ),
              ],
            ),
          ),
        ),
      );
  }
}
```

image

RenderWrap.computeMaxIntrinsicWidth does not calculate spacing, resulting in improper line feeds.

### PR DESCRIPTION
**Pull request by YeungKC**
close #82289

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
LGTM, thanks for fixing this!

**Comment by YeungKC** [comment]
I found an error, please don't merge.

**Comment by YeungKC** [comment]
Please review again, Spacing should be related to main axis.

**Review by chunhtai — COMMENTED** [review]
nice catch, still LGTM

**Comment by tvolkert** [comment]
FYI, this was reverted in https://github.com/flutter/flutter/pull/82872 due to Google tests failing.  @YeungKC please work with @chunhtai (who may need to fix bad tests inside Google first) to re-apply.

**Pull request merged**
