### PR TITLE
Use report_lines flag in flutter coverage

### PR DESCRIPTION
**Pull request by liamappelbe**
The report lines flag returns the line numbers directly in the source report, rather than the token positions. This lets us skip the extra RPC to get the token pos to line number mapping. In my benchmarks, this halved the time it takes to collect coverage.

https://github.com/flutter/flutter/issues/86722

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
lgtm

**Comment by zanderso** [comment]
FYI @christopherfujino

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
@liamappelbe To clarify, this will only affect the performance of collecting coverage on the Flutter SDK itself, and not end users, correct?

**Comment by liamappelbe** [comment]
> @liamappelbe To clarify, this will only affect the performance of collecting coverage on the Flutter SDK itself, and not end users, correct?

It should improve performance for everyone using `flutter test --coverage`

**Comment by christopherfujino** [comment]
> > @liamappelbe To clarify, this will only affect the performance of collecting coverage on the Flutter SDK itself, and not end users, correct?
> 
> It should improve performance for everyone using `flutter test --coverage`

ahh, yes, I read the path wrong, I thought this was in the test directory.

**Pull request merged**
