### PR TITLE
Clear the pointer absorbing flag after temporarily setting it while p…

### LINKED ISSUE #4910: Drawer widget bug!?
I use FlutterView in my app, and it has a drawer widget. I use the method:
 public void onBackPressed() {
        if(flutterView != null) {
            flutterView.popRoute();
        }
   }
When I touch 'back' button, the drawer close, but it cannot  open again.

### PR DESCRIPTION
**Pull request by jason-simmons**
…opping a route

Fixes https://github.com/flutter/flutter/issues/4910

### CODE REVIEW

**Comment by abarth** [comment]
Test?

Should be easy to test tapping an item on the drawer and then seeing that you can tap something on the page below after the drawer finishes closing.

**Comment by eseidelGoogle** [comment]
Is it straightfoward to cover this with our tests?

**Comment by jason-simmons** [comment]
Added a test

**Comment by abarth** [comment]
LGTM

Thanks!

**Pull request merged**
