### PR TITLE
[flutter_tools] Consistently set the working directory for Flutter Test

### LINKED ISSUE #20907: `flutter test` sets current directory differently depending on how test was executed
Moving from https://github.com/Dart-Code/Dart-Code/issues/1156 as this seems to happen from the command line. Depending on whether you pass a filename to `flutter test` or just run all tests (or filter using `--plain-name` or whatever) the value of `Directory.current` will be different.

Since flutter forces you to run `flutter test` from the root (eg. you can't influence the working directory yourself) these should probably be consistent.

```
dantup-macbookpro:flutter_hello_world dantup$ flutter test --plain-name 222
00:04 +0: /Users/dantup/Dev/Dart-Code/test/test_projects/flutter_hello_world/test/widget_test.dart: 222Hello world test                                        
Directory: '/Users/dantup/Dev/Dart-Code/test/test_projects/flutter_hello_world/test'

                                                                                                                                    
dantup-macbookpro:flutter_hello_world dantup$ flutter test test/widget_test.dart 
00:04 +0: 222Hello world test                                                                                                                                  
Directory: '/Users/dantup/Dev/Dart-Code/test/test_projects/flutter_hello_world'
```

### PR DESCRIPTION
**Pull request by jiahaog**
Fixes #20907. This makes `Directory.current` in tests always return the root of the flutter project, irregardless of whether the test command is `flutter test` (run all tests in `$project/test`), or `flutter test test/foo_test.dart` (run a specific test file).

Context: I was trying to initialize an application package as a follow up to #74236 (to run integration tests with `flutter test`). I got it to work for a single test, but running multiple tests did not work, because the [`FlutterProject.current()`](https://github.com/flutter/flutter/blob/2007186d2ed7a9754480cb9b8e2562604b2d17ef/packages/flutter_tools/lib/src/application_package.dart#L88) used in creating an application package works differently depending on the current working directory.

Not sure if this is alright though, it seems a bit breaking for users depending on the incorrect behavior. This is somewhat mitigated because users probably use `flutter test` to run all tests on CI, and the cases where I had to fix in this PR are probably less common (invoking `flutter test` in a subprocess from the test script). I also patched this and ran a global presubmit internally and there are no failures.

### CODE REVIEW

**Comment by jiahaog** [comment]
CI seems to have stalled, but the tool tests pass locally, so marking it as ready for review first.

**Comment by DanTup** [comment]
Not doing anything to handle this in VS Code (the inconsistency occurs there unless there's a workaround in the user code), so fixing this here would be beneficial for VS Code users :-)

**Comment by devoncarew** [comment]
For IntelliJ, when launching `flutter test`, we do set the cwd to the directory containing the pubspec file.

**Comment by devoncarew** [comment]
It should be pretty easy to validate that `flutter test` still works in IntelliJ and VS Code though.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
(but please verify in AS/Intellij too)

**Comment by jiahaog** [comment]
Yup, verified locally with the IntelliJ and VSCode plugins, we still can run individual tests via the UI.

**Pull request merged**
