### PR TITLE
Update /examples/ to new gradle based build flow

### LINKED ISSUE #8061: Convert examples to the new project template
We recently changed the new project template to use gradle on Android.  We should convert all our existing examples in the flutter.git repo to use the new template.

/cc @jakobr-google

### PR DESCRIPTION
**Pull request by mit-mit**
Update `/examples/` to match the new gradle based build enabled in https://github.com/flutter/flutter/issues/4796.

Fixes https://github.com/flutter/flutter/issues/8061

### CODE REVIEW

**Comment by mit-mit** [comment]
@jakobr-google @abarth please review

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
Gold star

**Comment by abarth** [comment]
Thanks so much!

**Review by jakobr-google — APPROVED** [review]

**Pull request merged**
