### PR TITLE
Re-enable docs with new container

### PR DESCRIPTION
**Pull request by dnfield**
I intend to land this once the docs shard on presubmit completes, so we can try to test the docs post submit more quickly.  If it fixes things I'll mark flutter/flutter#34435 as not being TODAY, and leave open until we get a more robust fix upstream.  If it doesn't, I'll retag the docker image and revert this patch.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by tvolkert — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Docs presubmit completed successfully at https://cirrus-ci.com/task/5081873131241472

Landing on red because we want to know if this is fixing docs ASAP, and has no relation to the failures in the devicelab.

**Comment by dnfield** [comment]
https://cirrus-ci.com/task/5118066149556224 is the post submit for this

**Pull request merged**
