### PR TITLE
Bump dart SDK to 1.16.0-dev.5.0.

### PR DESCRIPTION
**Pull request by pq**
Among other things, grabs support for `@optionalTypeArgs`.

This is the last dev push for 1.16.  Here on out we're in cherry-pick season until 1.16 final.

### CODE REVIEW

**Comment by pq** [comment]
cc @Hixie @devoncarew

**Comment by eseidelGoogle** [comment]
lgtm.  I'm not sure what our current dart VM version in the engine is.  These can be out of sync though.

**Comment by Hixie** [comment]
@pq This broke the build.

**Comment by Hixie** [comment]
fix in https://github.com/flutter/flutter/pull/3314

**Comment by eseidelGoogle** [comment]
Sorry, I should have noticed travis was mad.

**Comment by pq** [comment]
My bad.  After @Hixie's build fix landed I was cavalier.  And then went to lunch!

**Pull request merged**
