### PR TITLE
Add FlexibleSpaceBar setting for set title maximum scale value.

### PR DESCRIPTION
**Pull request by mofneko**
## Description

I added this option because I wanted to adjust the magnification effect for widgets with FlexibleSpaceBar set to Title.
This is equally useful for users who want to disable the scale effect.

## Tests

I added test for flexiblebar extensibility.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by mofneko** [comment]
Added test.

**Comment by mofneko** [comment]
@HansMuller please review(｀･ω･´)ゞ

**Comment by mofneko** [comment]
@goderbauer review please(｀･ω･´)ゞ

**Comment by Piinks** [comment]
Hi @mofneko, thanks for the contribution! There have been some changes to the FlexibleSpaceBar class since this was opened and the merge conflict will need to be resolved. Thanks!

**Comment by Piinks** [comment]
This pull request hasn't been updated, so I am going to close it. If you would like to come back and work on this, you are welcome to re-open it. :)

**Pull request closed without merging**
