### PR TITLE
Add .gitignore

### LINKED ISSUE #84349: WinUWP template does not have `.gitignore`
[WinUWP template](https://github.com/flutter/flutter/tree/master/packages/flutter_tools/templates/app/winuwp.tmpl) is missing .gitignore file so after running, the generated folder `flutter/ephemeral/` might get accidentally pushed because it is not ignored like on [Windows](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/windows.tmpl/.gitignore).

### PR DESCRIPTION
**Pull request by asashour**
Fixes #84349

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by clarkezone** [comment]
Thx

**Comment by jonahwilliams** [comment]
You need to update the integration_test/template manifest to include this file.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by cbracken — COMMENTED** [review]
Belated LGTM (was out at the time) and thank you!

**Pull request merged**
