### PR TITLE
Update `ColorScheme.light`, `ColorScheme.dark`, `ColorScheme.highContrastLight`, & `ColorScheme.highContrastDark`  constructors docs for Material 3

### LINKED ISSUE #132584: Clarify ColorScheme fromSwatch/fromSeed usage
From https://github.com/flutter/website/pull/9183#discussion_r1294291872

Currently the API docs does not distinguish which constructor should be used in what context.
The linked comment says:

> We don't recommend using fromSwatch (M1/M2 concept) but rather fromSeed (M3+)

but the docs for `fromSwatch` say

> This constructor is used by [ThemeData](https://api.flutter.dev/flutter/material/ThemeData-class.html) to create its default color scheme.
- https://api.flutter.dev/flutter/material/ColorScheme/ColorScheme.fromSwatch.html

`fromSeed` is a bit clearer, but it isn't clear to me as a Flutter developer which I should use and how they differ in the context of M1/2 versus M3

> Using the seedColor as a starting point, a set of tonal palettes are constructed. These tonal palettes are based on the Material 3 Color system and provide all the needed colors for a [ColorScheme](https://api.flutter.dev/flutter/material/ColorScheme-class.html). These colors are designed to work well together and meet contrast requirements for accessibility.
- https://api.flutter.dev/flutter/material/ColorScheme/ColorScheme.fromSeed.html

While we're at it, the other constructors should be checked for the same clarity for M1/2/3:
- dark
- light
- highContrastDark
- highContrastLight

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes [Clarify ColorScheme fromSwatch/fromSeed usage](https://github.com/flutter/flutter/issues/132584)

"This explains how to use `ColorScheme.fromSeed` as a substitute for each `ColorScheme` constructor."

| `ColorScheme.light` (left) to `ColorScheme.fromSeed` (right) | 
| --------------- | 
| light	|

| `ColorScheme.dark` (left) to `ColorScheme.fromSeed` (right) | 
| --------------- | 
| dark	|

| `ColorScheme.highContrastLight` (left) to `ColorScheme.fromSeed` (right) | 
| --------------- | 
| highContrastLight |

| `ColorScheme.highContrastDark` (left) to `ColorScheme.fromSeed` (right) | 
| --------------- | 
| highContrastDark |

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
LGTM however we should tell developers what to substitute for ColorScheme.dark,light,highContrastLight.  The substitute doesn't have to produce exactly the same color scheme as the old factories, just something moderately close.

**Comment by TahaTesser** [comment]
> LGTM however we should tell developers what to substitute for ColorScheme.dark,light,highContrastLight. The substitute doesn't have to produce exactly the same color scheme as the old factories, just something moderately close.

I love this idea. I've added substitute for each constructor using `ColorScheme.fromSeed` and provided previews in the PR [description](https://github.com/flutter/flutter/pull/137149#issue-1959346306). Please take a look before I can merge this.

**Comment by TahaTesser** [comment]
cc: @HansMuller

**Review by HansMuller — APPROVED** [review]
LGTM

**Pull request merged**
