### PR TITLE
flutter_tools: Remove unused //ignore comments; change flutter-specific ones to "ignore_for_flutter"

### PR DESCRIPTION
**Pull request by srawlins**
## Description

An upcoming change to the Dart analyzer will call out "ignore" comments which do not actively ignore any reported code: https://github.com/dart-lang/sdk/issues/35234. Remove "unused" `// ignore` comments; change flutter-specific ones to `// ignore_for_flutter`.

## Related Issues

https://github.com/dart-lang/sdk/issues/35234

## Tests

I added no tests.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by srawlins** [comment]
@jonahwilliams Would this be a PR for you?

**Comment by jonahwilliams** [comment]
Taking a look

**Review by jonahwilliams — APPROVED** [review]
LGTM

Where did the implementation imports warning go?

**Comment by srawlins** [comment]
> Where did the implementation imports warning go?

Isn't that weird? The lint rule doesn't trigger though... Maybe a bug in the lint rule.

I'd be happy to keep the ignores around and instead add an `// ignore_for_file:` comment at the top for unused "ignore" comments.

**Comment by jonahwilliams** [comment]
ignore_for_file SGTM? We should figured out why/when that stopped working - maybe we turned off a lint?

**Comment by srawlins** [comment]
@jonahwilliams I'm embarrassed to say that those codes looked like they weren't being reported because of course those import statements are in a _String_, they're not actually import statements. But the analyzer sees them as actual ignore comments. https://github.com/dart-lang/sdk/issues/39607. I've re-instated those  ignores.

**Comment by zanderso** [comment]
@srawlins How should we proceed with this PR?

**Comment by srawlins** [comment]
Merge button! 😄

**Comment by tvolkert** [comment]
This broke forbidden_imports_test, which uses a custom ignore comment.  Reverting.

**Comment by tvolkert** [comment]
https://cirrus-ci.com/task/5320647412023296?command=main#L820

**Pull request merged**
