### PR TITLE
web tests: run no more than one `RunnerSuite` at a time

### LINKED ISSUE #47003: Enable web golden tests
The tests fail with "Unknown error loading". For example:

```
02:03 +118 ~33 -1: compiling /tmp/flutter sdk/packages/flutter/test/widgets/list_view_vertical_test.dart [E]                                                                                           
  Failed to load "/tmp/flutter sdk/packages/flutter/test/widgets/list_view_vertical_test.dart": Unknown error loading http://localhost:43947/packages/flutter/material.ddc.js
```

Seen in the following, but I've seen it multiple times lately.

https://cirrus-ci.com/task/5055207964147712?command=main#L759
https://cirrus-ci.com/task/5899632894279680?command=main#L2370

/cc @jonahwilliams and @yjbanov who may know what's going on.

### PR DESCRIPTION
**Pull request by yjbanov**
## Description

- Allow only one `RunnerSuite` to load and test at any given point in time, limiting the number of tests running concurrently. The previous method only serialized the loading part, not loading _and_ running.
- Enable most of the screenshot tests.

## Related Issues

Fixes #47003

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 3.
Please triage them at https://flutter-gold.skia.org/search?issue=52683.

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 5.
Please triage them at https://flutter-gold.skia.org/search?issue=52683.

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 12.
Please triage them at https://flutter-gold.skia.org/search?issue=52683.

**Comment by yjbanov** [comment]
Closing this draft. https://github.com/flutter/flutter/pull/52789 is the final PR.

**Pull request closed without merging**
