### PR TITLE
Fix Textfields in Semantics Debugger

### PR DESCRIPTION
**Pull request by goderbauer**
## Description

Identifies textfields as Textfields in the semantics debugger. (Previously they were labeled as buttons, which is technically correct since they are tap-able, but it's also misleading.)

## Related Issues

None

## Tests

Unclear how to test that a custom paint writes the correct text on the canvas.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by dnfield — APPROVED** [review]

**Review by dnfield — COMMENTED** [review]
Sorry, this needs at est

**Comment by dnfield** [comment]
Could we just have the SemanticsDebugger store the messages it's going to paint somewhere that is debug/test accessible?  E.g. in `_paintMessage`, it could add the `message` it's going to paint to a list or tree or some sort htat could be verified in tests.

**Comment by goderbauer** [comment]
I refactored it and moved the global private methods into the SemanticsDebuggerPainter (they were only used in there anyways). In there, I marked the getMessage as visibleForTesting, which allowed me to write some tests for this change and the existing checkbox rendering.

PTAL.

**Review by dnfield — APPROVED** [review]
LGTM

**Pull request merged**
