### PR TITLE
[flutter_tools] disable flutter build AAR for plugins

### PR DESCRIPTION
**Pull request by christopherfujino**
Per discord discussion, building an AAR out of a plugin project has not worked for years, so let's just disable the functionality. Context: https://github.com/flutter/flutter/issues/137564

### CODE REVIEW

**Review by gmackall — COMMENTED** [review]
Looks like we have a test that tests that you _can_ do this, so that test will probably need to be disabled

```
00:57 +611: test/commands.shard/permeable/build_aar_test.dart: flag parsing parses flags                                                                                                               
Error: AARs can only be built from modules.
```

**Comment by christopherfujino** [comment]
> Looks like we have a test that tests that you _can_ do this, so that test will probably need to be disabled
> 
> ```
> 00:57 +611: test/commands.shard/permeable/build_aar_test.dart: flag parsing parses flags                                                                                                               
> Error: AARs can only be built from modules.
> ```

Thanks, let me investigate further what the test is actually testing :)

**Comment by christopherfujino** [comment]
> > Looks like we have a test that tests that you _can_ do this, so that test will probably need to be disabled
> > ```
> > 00:57 +611: test/commands.shard/permeable/build_aar_test.dart: flag parsing parses flags                                                                                                               
> > Error: AARs can only be built from modules.
> > ```
> 
> Thanks, let me investigate further what the test is actually testing :)

Ahh, it was just verifying that if we build aar from a plugin, we send the right analytics event.

**Review by gmackall — COMMENTED** [review]
Looks like these two tests are also failing
https://github.com/flutter/flutter/blob/034479a7c57f1aadaa0b2522472ef14e625f6c11/packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart#L118

https://github.com/flutter/flutter/blob/034479a7c57f1aadaa0b2522472ef14e625f6c11/packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart#L148

Presumably because they aren't passing in `--template=module` to `createProject` - though its odd that they were passing, because at a first glance they also don't seem to be requesting a plugin template either?

**Comment by christopherfujino** [comment]
> Looks like these two tests are also failing
> 
> https://github.com/flutter/flutter/blob/034479a7c57f1aadaa0b2522472ef14e625f6c11/packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart#L118
> 
> https://github.com/flutter/flutter/blob/034479a7c57f1aadaa0b2522472ef14e625f6c11/packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart#L148
> 
> Presumably because they aren't passing in `--template=module` to `createProject` - though its odd that they were passing, because at a first glance they also don't seem to be requesting a plugin template either?

might be defaulting to an app template?

**Comment by gmackall** [comment]
> > Looks like these two tests are also failing
> > https://github.com/flutter/flutter/blob/034479a7c57f1aadaa0b2522472ef14e625f6c11/packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart#L118
> > 
> > https://github.com/flutter/flutter/blob/034479a7c57f1aadaa0b2522472ef14e625f6c11/packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart#L148
> > 
> > Presumably because they aren't passing in `--template=module` to `createProject` - though its odd that they were passing, because at a first glance they also don't seem to be requesting a plugin template either?
> 
> might be defaulting to an app template?

But if they were defaulting to an app template, wouldn't they be failing before this change anyways?

**Comment by christopherfujino** [comment]
> > > Looks like these two tests are also failing
> > > https://github.com/flutter/flutter/blob/034479a7c57f1aadaa0b2522472ef14e625f6c11/packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart#L118
> > > 
> > > https://github.com/flutter/flutter/blob/034479a7c57f1aadaa0b2522472ef14e625f6c11/packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart#L148
> > > 
> > > Presumably because they aren't passing in `--template=module` to `createProject` - though its odd that they were passing, because at a first glance they also don't seem to be requesting a plugin template either?
> > 
> > 
> > might be defaulting to an app template?
> 
> But if they were defaulting to an app template, wouldn't they be failing before this change anyways?

the tool exit that is failing is a new one I added

**Comment by christopherfujino** [comment]
@gmackall i think this is (finally!) ready for review :)

**Comment by christopherfujino** [comment]
> > > Looks like these two tests are also failing
> > > https://github.com/flutter/flutter/blob/034479a7c57f1aadaa0b2522472ef14e625f6c11/packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart#L118
> > > 
> > > https://github.com/flutter/flutter/blob/034479a7c57f1aadaa0b2522472ef14e625f6c11/packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart#L148
> > > 
> > > Presumably because they aren't passing in `--template=module` to `createProject` - though its odd that they were passing, because at a first glance they also don't seem to be requesting a plugin template either?
> > 
> > 
> > might be defaulting to an app template?
> 
> But if they were defaulting to an app template, wouldn't they be failing before this change anyways?

these tests are using a `FakeAndroidBuilder`, so they're not really running a gradle build.

**Review by gmackall — APPROVED** [review]
LGTM

**Review by reidbaker — APPROVED** [review]

**Comment by gmackall** [comment]
Clicking update branch to hope it gets google testing unstuck

**Pull request merged**
