### PR TITLE
Update analysis options

### LINKED ISSUE #7166: Add a "blacklisted methods" test
The following async file I/O methods should never be called -- they create undue overhead in the async wiring required to accomplish them, and their corresponding sync versions require minimal overhead.

- [ ] `File.lastModified()`
- [ ] `FileSystemEntity.isDirectory()`
- [ ] `FileSystemEntity.isFile()`
- [ ] `FileSystemEntity.isLink()`
- [ ] `FileSystemEntity.type()`
- [ ] `FileSystemEntity.exists()`
- [ ] `FileSystemEntity.stat()`

We should convert all existing uses of these methods (in flutter_tools - we don't use them in the framework) to use the sync versions, and we should add a test that ensures we don't re-introduce them.  Over time, if any other such methods come up, we can just add them to this method blacklist.

@johnmccutchan

### PR DESCRIPTION
**Pull request by tvolkert**
Fixes #7166

Also cleans up from an aborted attempt at #5793

### CODE REVIEW

**Comment by tvolkert** [comment]
@danrubel

**Review by danrubel — APPROVED** [review]

**Comment by Hixie** [comment]
This change was only applied to one of the three `.analysis_options` files. @tvolkert, can you update the others to make sure they're all in sync (or that if they're different, it's intentional)?

**Comment by tvolkert** [comment]
> This change was only applied to one of the three .analysis_options files

All the other `.analysis_options` files (e.g. [this one](https://github.com/flutter/flutter/blob/master/dev/docs/.analysis_options)) are just skeletons...

**Comment by Hixie** [comment]
I meant the three that are mentioned at the top of the root one:
https://github.com/flutter/flutter/blob/master/.analysis_options

**Pull request merged**
