### PR TITLE
Provide default constraints for M3 dialogs

### LINKED ISSUE #118619: Add missing m3 max width/height constraints
These components currently don't correctly limit how wide they can be:
- [x] [Bottom sheets](https://m3.material.io/components/bottom-sheets/specs) should have a max width of 640dp
- [ ] [Dialogs](https://m3.material.io/components/dialogs/specs) should have a max width & height of 560dp

### PR DESCRIPTION
**Pull request by guidezpl**
This PR constrains M3 dialogs to 560dp max width and height.

This is not a breaking change per the breaking change policy.

Part of https://github.com/flutter/flutter/issues/118619

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by esouthren — APPROVED** [review]
LGTM!

**Review by hannah-hyj — APPROVED** [review]
LGTM

**Comment by guidezpl** [comment]
Google testing multiple cases of overflow in extreme circumstances, so I'm now scaling the max height by the text scale factor to help this.

**Comment by guidezpl** [comment]
Adding a g3fix cl/529417686

**Comment by hangyujin** [comment]
This is still causing overflow in some Google testing cases  in extreme circumstances

 Scaling the max height to "_dialogConstraints.maxHeight * textScaleFactor" is not enough because in those extreme cases not just the text height is larger, the number of text in one line is also less, so there will be more lines, I think the scale factor should be " _dialogConstraints.maxHeight * textScaleFactor * textScaleFactor "

**Pull request merged**
