### PR TITLE
Add a Flutter for web issue template

### PR DESCRIPTION
**Pull request by kevmoo**
Add an issue template specific to Flutter's web support

### CODE REVIEW

**Review by yjbanov — APPROVED** [review]

**Comment by Hixie** [comment]
This would prevent web issues from getting front line triage (because the way we drive what gets triage is by a search that excludes already-triaged bugs). Given that there is very little here that is unique to web issues, I'm concerned that this would actually overall be a net negative as it would mean web bugs get fewer labels and less front line processing.

That said, we can certainly add this temporarily while we wait for triage to resume. If you land this, please keep a note of all the places where you link to this template so that we can change them all to the the bug template when we are doing triage normally again.

**Comment by kevmoo** [comment]
@Hixie – so you DON'T want a template?

**Comment by yjbanov** [comment]
Happy to reuse Flutter's existing triage system. It would be very helpful to have issues get the platform-web label asap so it lands on the Web team's plate quicker. Would Flutter's triage process facilitate that?

**Comment by Hixie** [comment]
I could go either way on this, as described above. I don't have a strong opinion. Long term I'd rather rely on front line triage. @kf6gpe tells me that will be going again soon.

**Pull request closed without merging**
