### PR TITLE
Update --local-engine to account for changed host architecture of 32-…

### PR DESCRIPTION
**Pull request by rmacnak-google**
…bit Android debug builds.

Roll engine to 03e642bc8940441bbad5c2fb7d3ca868c1fdad54.

### CODE REVIEW

**Review by jason-simmons — APPROVED** [review]

**Comment by goderbauer** [comment]
LGTM

**Comment by chinmaygarde** [comment]
This breaks the iOS debug simulator local engine workflow.

**Comment by xster** [comment]
I think this breaks x64 builds in general. `build flx` never passes in a platform https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/flx.dart#L44 (though I imagine we probably want to change that)

**Comment by cbracken** [comment]
Output of `flutter run --local-engine ios_debug_unopt -d mydevice`:

```
    Oops; flutter has exited unexpectedly.
    Crash report written to /Users/cbracken/src/text_edit/flutter_01.log;
    please let us know at https://github.com/flutter/flutter/issues.
    Failed to package /Users/cbracken/src/text_edit.
    Command /bin/sh failed with exit code 255

Could not build the precompiled application for the device.
```

Log contents:
```
## command

flutter --suppress-analytics build flx --target=/Users/cbracken/src/text_edit/lib/main.dart --output-file=/Users/cbracken/src/text_edit/ios/Flutter/app.flx --snapshot=build/snapshot_blob.bin --depfile=build/snapshot_blob.bin.d --working-dir=build/flx --local-engine=/Users/cbracken/src/flutter/engine/src/out/ios_debug_unopt

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /Users/cbracken/src/flutter/engine/src/out/ios_debug_unopt/clang_i386/gen_snapshot.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:115)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43)
#2      runCommand (package:flutter_tools/src/base/process.dart:107)
#3      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:125)
<asynchronous suspension>
#4      _createSnapshot (package:flutter_tools/src/flx.dart:82)
<asynchronous suspension>
#5      build (package:flutter_tools/src/flx.dart:124)
<asynchronous suspension>
#6      BuildFlxCommand.runCommand (package:flutter_tools/src/commands/build_flx.dart:44)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:220)
<asynchronous suspension>
#8      BuildSubCommand.verifyThenRunCommand (package:flutter_tools/src/commands/build.dart:50)
<asynchronous suspension>
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:162)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#13     new Future.sync (dart:async/future.dart:222)
#14     CommandRunner.run (package:args/command_runner.dart:109)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
#16     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#18     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1120)
#20     _CustomZone.run (dart:async/zone.dart:1001)
#21     runZoned (dart:async/zone.dart:1467)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
#24     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
#25     main (file:///Users/cbracken/src/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Pull request merged**
