### PR TITLE
Revert "[flutter_tools] Allow providing dart-defines to Android, iOS, macOS builds"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#51714

This broke tests that were supplying extra-gen-snapshot-options in the devicelab

[flutter_gallery_win__compile_ee60eee_2.log](https://github.com/flutter/flutter/files/4295094/flutter_gallery_win__compile_ee60eee_2.log)

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Landing TBR to fix build

**Comment by felix-ht** [comment]
@jonahwilliams does this mean that --dart-define is no longer supported? is there an alternative?

**Comment by jonahwilliams** [comment]
I'm not sure how you found this issue - during the process of landing the feature there were a few hiccups. The feature has been in flutter for months and months.

**Comment by felix-ht** [comment]
It was mentioned in some other issues/blogposts claiming that dart defines do not work for new versions of dart, because it was removed again. Thanks for clarifying.

**Comment by jonahwilliams** [comment]
anything official from flutter?

**Comment by felix-ht** [comment]
no. But i didn't manage to find any official documentation on dart define anywhere. Google lead me to this https://dev.to/ashishrawat2911/pass-arguments-from-command-line-to-main-in-flutter-dart-2dcm the comment mentions this issue, somewhere else (might have been stackoverflow cant remember) does as well.

To me --dart-define doesn't work while runing on a mac with a ios target - `flutter run --dart-define=FOO=test` prints `ENV: {} `with `print("ENV: " + Platform.environment.toString());.`
Thats why i assumed that the comment was right.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale de)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)

• No issues found!
```

**Pull request merged**
