### PR TITLE
move compile/target sdk versions to 29 (#62799)

### PR DESCRIPTION
**Pull request by xster**
Unrevert https://github.com/flutter/flutter/pull/62884

Fixed revert by fixing permissions on devicelab. ~~Also add checks in doctor validation.~~
https://github.com/flutter/flutter/issues/54382

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by xster** [comment]
@fkorotkov do you know what's up with these tests? Do we need to install Java ourselves on these linux dockers?

**Comment by fkorotkov** [comment]
I think @jmagman provided some insights on Discord about the issue. Please let me know if I can help you somehow.

**Comment by jmagman** [comment]
> I think @jmagman provided some insights on Discord about the issue. Please let me know if I can help you somehow.

The test has Android SDK 28.0.3 installed, you bumped the requirement to 29, but there will be a doctor error until there's some automatic download building the Android app.  And the doctor validation fails in setup too.

**Comment by xster** [comment]
🤦🏻‍♂️ yup. 

Moving the doctor check to another PR since updating the min required SDK for all projects (and modifying Cirrus's docker file) vs updating the template which self-upgrades are 2 different semantic steps anyway.

**Comment by bernaferrari** [comment]
Is there a reason you didn't choose API 30 which is the latest?

**Comment by jmagman** [comment]
@bernaferrari see https://github.com/flutter/flutter/issues/56597

**Pull request merged**
