### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by dnfield**
Want this to land before https://github.com/flutter/flutter/pull/26944 so that that PR doesn't include a bunch of unrelated updates.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
You'll need this change as well: https://github.com/flutter/flutter/pull/26978/files#diff-ddc048e02b7f24e9a6a5a7c3ad51e14f

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by gspencergoog — APPROVED** [review]

**Comment by zoechi** [comment]
I assume this would fix #26648 #25916 #24292

**Comment by dnfield** [comment]
Only temporarily.  I think we should remove `flutter upgrade` from those instructions.

**Comment by dnfield** [comment]
Alternatively, we have to make flutter upgrade respect the pinned deps in flutter/flutter

**Pull request merged**
