### PR TITLE
make hotfix use a plus instead of minus

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Currently we use `-` for hotfix versions. This actually places them before the original version in semvar, which can break upgrading.

## Related Issues

https://github.com/flutter/flutter/issues/32044

### CODE REVIEW

**Comment by jonahwilliams** [comment]
If we wanted to hotfix this code into the tool, it would need to be changed to support both hotfix variants. Then the next hotfix could remove that ... I think that is too risky and we should separately evaluate the upgrade process with the new hotfix procedure.

**Review by tvolkert — COMMENTED** [review]
How will this change react to the fact that we already have a `-hotfix` release in the wild?

**Comment by jonahwilliams** [comment]
Because we've already shipped that version of the tool, nothing changes. All future hotfixes need to be created with a `+` and we need to re-test the upgrade procedure

**Comment by Hixie** [comment]
please also update the wiki (release process page and anywhere else you can find)

I'll update the branch protection patterns on GitHub

**Review by tvolkert — APPROVED** [review]

**Pull request merged**
