### PR TITLE
✨ `flutter config list`

### LINKED ISSUE #133732: [flutter_tools] `list` subcommand
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

As previously discussed in https://github.com/flutter/flutter/issues/81831, we might consider a cleaner command design for the `config` tool.

### Proposal

- Use the `list` command to display configured settings.
- Still displays usage when `flutter config` only.

### PR DESCRIPTION
**Pull request by AlexV525**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

Resolves #133732.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by AlexV525** [comment]
Hmm, sub-command cannot live with flags/options? I got `Missing subcommand for "flutter config"` when running the command without any arguments.

**Comment by AlexV525** [comment]
cc @christopherfujino @andrewkolos https://github.com/flutter/flutter/pull/133834#issuecomment-1704351303

**Comment by andrewkolos** [comment]
oooohhh. This might be the case. I wasn't aware of this. I'll discuss with Chris today.

**Comment by christopherfujino** [comment]
Shucks. Sorry about the churn, looks like we'll need to use --list after all.

**Comment by AlexV525** [comment]
Or can we update the Command's behavior?

**Comment by christopherfujino** [comment]
> Or can we update the Command's behavior?

That would be a design decision for the https://github.com/dart-lang/args maintainers.

**Comment by AlexV525** [comment]
Closing based on the above discussion.

**Pull request closed without merging**
