### PR TITLE
[flutter_tools] fix port leak in flutter_driver

### LINKED ISSUE #70983: [flutter_driver] Driver tests won't start when project have a path dependency (1.24)
After upgrading from Flutter 1.23 to 1.24, my driver tests won't even start up. Everything worked fine on the previous version and after downgrading issue disappears.

Starting `flutter drive` on 1.24 results in:
```
The pubspec.lock file has changed since the .dart_tool/package_config.json file was generated, please run "pub get" again.
```

I've narrowed dow the issue to a path dependency in my `pubspec.yaml`. I have two flutter apps linked together. One is my production Android and iOS app. The other have code to generate app screenshots. The _screenshots_ app have a path dependency to _app_ module. Removing this dependency (and commenting out all of the compiler errors) makes driver tests working again.

## Steps to Reproduce

1. Clone `https://github.com/dluksza/flutter_path_depenency`
1. Enter `app` directory
1. Run `flutter drive --target lib/main.dart --driver test_driver/example.dart` - test will fail with the issue reported above
1. Edit `pubspec.yaml`, remove:
```yaml
  base:
    path: ../base/
```
1. Run `flutter drive` again, tests will execute successfully

## Logs

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-GB)
    • Flutter version 1.24.0-10.2.pre at /usr/local/Caskroom/flutter/1.22.4/flutter
    • Framework revision 022b333a08 (3 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/lock/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/lock/Library/Android/sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)
    ! Error: Dariusz’s iPhone is not connected. Xcode will continue when Dariusz’s iPhone is connected. (code -13)

• No issues found!
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

The connect URI method in flutter driver was leaking a port. Fix this so that the tool does not need to run through pub.

Fixes https://github.com/flutter/flutter/issues/70983

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM

I wonder if this was causing some of the hangs we were seeing.

**Comment by jonahwilliams** [comment]
Probably, though I think the other problems were caused by running through pub

**Comment by dluksza** [comment]
Will this be cherry-picked to 1.24?

**Comment by jonahwilliams** [comment]
1.24 is not released

**Pull request merged**
