### PR TITLE
make CupertinoDynamicColor const constructible

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

make `CupertinoDynamicColor`'s constructors const, in order to use a `CupertinoDynamicColor` as the default value of a function argument. This change would allow us to provide a default `CupertinoDynamicColor` in the constructor of the following widget, without breaking its current API:

```dart
class SomeWidget extends StatelessWidget {
  const SomeWidget({ Key key, this.color = defaultColor }) : super(key: key);
}
```

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Tests

No new tests were added: existing tests should be able to cover this.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by justinmc — APPROVED** [review]
LGTM

It's great that you were able to make this const.  Did you find that it needed to be const for some reason or are you just doing it because it's possible?

**Comment by LongCatIsLooong** [comment]
@justinmc default values have to be const values, if a widget's constructor has a color parameter with a default color, it can't take a `CupertinoDynamicColor` as the default value if `CupertinoDynamicColor` doesn't have a const constructor. I was converting cupertino widgets and realized that `CupertinoDynamicColor` being not const constructible is going to break quite a few widgets' current API so I came back and changed it. I had to call the super constructor with a dummy value though:
https://github.com/flutter/flutter/blob/20009df0daa76641f543ad24cdb76cebf5a007e5/packages/flutter/lib/src/cupertino/colors.dart#L227

**Review by darrenaustin — APPROVED** [review]
LGTM. Nice update. Having a const constructor for a class like this is helpful and the changes to the color storage are a lot easier to follow.

**Review by HansMuller — APPROVED** [review]
LGTM

**Pull request merged**
