### PR TITLE
Add myself to AUTHORS

### PR DESCRIPTION
**Pull request by bartekpacia**
I made [a few contributions](https://github.com/flutter/flutter/issues?q=author%3Abartekpacia+).

### CODE REVIEW

**Comment by goderbauer** [comment]
Can you remove the blank line that the analyze check is complaining about?

**Comment by bartekpacia** [comment]
Sorry, done.

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by Piinks — APPROVED** [review]
LGTM! Thank you for contributing!

**Pull request merged**
