### PR TITLE
Revert "Add more tests to slider to avoid future breakages"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#98772

Tree is red https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests_libraries/3751/overview

The tests added in the PR are failing on CI.

### CODE REVIEW

**Comment by zanderso** [comment]
@godofredoc My understanding was that we'd be able to land clean tip-of-tree reverts TBR to get the tree back open.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
Any insights on why this broke anything post-submit? All checks were green on presubmit on the original PR and all gold changes were triaged correctly...

/cc @Piinks

**Comment by Piinks** [comment]
> Any insights on why this broke anything post-submit?

See comments in https://github.com/flutter/flutter/pull/98936

**Pull request merged**
