### PR TITLE
Revert "Fix a multiple pointers bug"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#68587

```
10:14 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:15 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:16 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:17 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:18 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:19 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:20 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:21 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:22 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:23 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:24 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:25 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:26 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:27 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:28 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:29 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:30 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:31 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:32 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:33 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:34 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:35 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:36 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:37 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:38 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:39 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:40 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:41 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:42 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:43 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:44 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:45 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:46 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:47 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:48 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:49 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:50 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:51 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:52 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:53 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:54 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:55 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:56 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:57 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:58 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
10:59 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:00 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:01 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:02 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:03 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:04 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:05 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:06 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:07 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:08 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:09 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:10 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:11 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:12 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:13 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:14 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:15 +3046 ~14: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations                                                     
11:15 +3046 ~14 -1: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: Screenshot composited transforms - with rotations [E]                                              
  TimeoutException after 0:10:00.000000: Test timed out after 10 minutes.
  dart:isolate  _RawReceivePortImpl._handleMessage
  

11:15 +3046 ~14 -1: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: getChildrenDetailsSubtree                                                                          
11:15 +3046 ~15 -1: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: getChildrenDetailsSubtree                                                                          
11:15 +3046 ~15 -1: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: InspectorSerializationDelegate addAdditionalPropertiesCallback                                     
11:16 +3046 ~15 -1: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: InspectorSerializationDelegate addAdditionalPropertiesCallback                                     
11:16 +3046 ~15 -1: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: InspectorSerializationDelegate addAdditionalPropertiesCallback                                     
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test:
Bad state: No element

When the exception was thrown, this was the stack:
#0      Iterable.first (dart:core/iterable.dart:524:7)
#1      _TestWidgetInspectorService.runTests.<anonymous closure> (file:///opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart:2649:59)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Screenshot composited transforms - with rotations
════════════════════════════════════════════════════════════════════════════════════════════════════

11:16 +3046 ~15 -2: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: InspectorSerializationDelegate addAdditionalPropertiesCallback [E]                                 
  Test failed. See exception logs above.
  The test description was: Screenshot composited transforms - with rotations
  

11:16 +3046 ~15 -2: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: debugIsLocalCreationLocation test                                                                  
11:16 +3046 ~16 -2: /opt/s/w/ir/k/flutter/packages/flutter/test/widgets/widget_inspector_test.dart: debugIsLocalCreationLocation test                                                                  
11:16 +3046 ~16 -2: Some tests failed.                                                                                                                                                                 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 1 (expected: zero).
Command: ../../bin/flutter test --no-track-widget-creation --enable-experiment=non-nullable --null-assertions --sound-null-safety test/widgets/
Relative working directory: packages/flutter
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

```

TBR @dkwingsmt

### CODE REVIEW

**Comment by xu-baolin** [comment]
Appears to be a flake. Looking into it.

**Comment by jonahwilliams** [comment]
It failed on each of the windows/mac/linux shards so it seems unlikely to just be flaky.

**Comment by xu-baolin** [comment]
Are the error messages in the log the same? Sorry, I can't view these logs.

**Comment by jonahwilliams** [comment]
i posted the failure on the revert above

**Comment by xu-baolin** [comment]
@dkwingsmt Hi,
I'm sorry to bother you again. Do you have time to look at the failures? From the log at the description, it seems that it has nothing to do with our change, but I don't have permission to see all the logs. What is your opinion?

**Comment by dkwingsmt** [comment]
Sorry, I forgot this. I'll take a look later this evening and tomorrow. Thanks for the reminder!

**Pull request merged**
