### PR TITLE
[flutter] replace 'checked mode' with 'debug mode'

### PR DESCRIPTION
**Pull request by jonahwilliams**
This was renamed many years ago....

### CODE REVIEW

**Review by vishnuaq — APPROVED** [review]

**Comment by Hixie** [comment]
test-exempt: only affects comments

that said, it might be good to add a test that checks for the string "checked mode" in any file in flutter/flutter or flutter/engine and flags said usages.

**Comment by jonahwilliams** [comment]
I think it depends on the context, since for the CLI --checked / checked mode because --enable-asserts but it is still referred to as checked mode in the dart API docs. We could definitely run a test at least for dart:ui and the flutter packages.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
I added an analyze.dart check for the phrase "checked mode" in `flutter/packages`.

**Pull request merged**
