### PR TITLE
Remove fetch.dart

### PR DESCRIPTION
**Pull request by abarth**
These uses cases are now address by http.dart via http.readDataPipe.

### CODE REVIEW

**Comment by abarth** [comment]
@collinjackson @HansMuller

**Comment by sethladd** [comment]
closes https://github.com/flutter/flutter/issues/3163

**Comment by abarth** [comment]
closes #2889 as well.

**Comment by collinjackson** [comment]
lgtm. when we merge it into the core http repo we might want to make sure this extra mojo API plays nicely with conditional compilation on web clients, but we can cross that bridge when we get to it

**Pull request merged**
