### PR TITLE
apply upcoming lint avoid_renaming_method_parameters

### PR DESCRIPTION
**Pull request by a14n**
This will fix dartdoc issues when overrided method changed the parameter names.

See dart-lang/sdk#57680 and dart-lang/linter#907

### CODE REVIEW

**Comment by kevmoo** [comment]
@a14n – you're a machine!

**Review by tvolkert — COMMENTED** [review]
LGTM, though this needs merge conflicts resolved first.

**Comment by a14n** [comment]
Rebased. Waiting for CIs to merge.

**Pull request merged**
