### PR TITLE
Allow scrollable hit test behavior to be passed in via CustomScrollView.

### PR DESCRIPTION
**Pull request by apwilson**
@Hixie

### CODE REVIEW

**Comment by tvolkert** [comment]
What's the use case for having the hot test behavior be something other than opaque?

/cc @HansMuller

**Comment by apwilson** [comment]
Use case is I want to tap something behind the CustonScrollView in a Stack and the taps don't go through the opaqueness of the scroll view.

ie. something like this:

```
Stack(
  children: [
    ThingIWantToTapButCantIfOpaque(),
    CustomScrollView(behavior: HitTestBehavior.translucent),
  ],
)
```

**Comment by HansMuller** [comment]
Scrollables listen for drag gestures so something stacked behind a scrollable could probably listen for taps if behavior was translucent instead of opaque. Listening for drags wouldn't work since the scrollable is on top, and listening for double taps would delay the scrollable's drag recognizer which wouldn't be good.  Listening for tap-cancel, which most button components do, might also delay the scrollable recognizing dragStart.

If we were to add this feature, it would have to be documented in a way that would dissuade most developers from considering it by making the use case - and its limits - pretty clear.

**Comment by Hixie** [comment]
I don't think we should expose this as written. I think it'd be better to expose a way to change the build method of the Scrollable (or probably, just the Scrollable itself, or some such).

**Comment by apwilson** [comment]
ok.  I copied flutter's scrollable classes and have made my own for my purposes so I guess I don't need this anymore.

**Pull request closed without merging**
