### PR TITLE
Add mac_arm64 host only platform support in .ci.yaml

### LINKED ISSUE #104034: Support mac_arm64 host only test configuration
Create `mac_arm64` configuration for host-only tests to be run on arm Macs, similar to:
https://github.com/flutter/flutter/blob/4b1ff134596196d31d5b324ecb997ac0340187db/.ci.yaml#L49-L56

For example, `Mac_arm64_ios macos_chrome_dev_mode` does not need a tethered iOS device to pass.

cc @keyonghan

### PR DESCRIPTION
**Pull request by keyonghan**
fixed: https://github.com/flutter/flutter/issues/104034

### CODE REVIEW

**Comment by jmagman** [comment]
We don't need to address in this PR, but something to think about: `mac` and `mac_arm` could be used for macOS desktop benchmarks, so do we need to peg to a particular Mac model like `Macmini8,1` or `Macmini8,1` so they all run on the same type of machine?

**Review by jmagman — COMMENTED** [review]
To test this, can you add a presubmit `Mac_arm64 tool_host_cross_arch_tests`?  The intention of that shard was to test tool behavior that's different between architectures.

https://github.com/flutter/flutter/blob/129fa7699f3325229917b0a938647000669f892b/.ci.yaml#L2705

**Comment by keyonghan** [comment]
> To test this, can you add a presubmit `Mac_arm64 tool_host_cross_arch_tests`? The intention of that shard was to test tool behavior that's different between architectures.
> 
> https://github.com/flutter/flutter/blob/129fa7699f3325229917b0a938647000669f892b/.ci.yaml#L2705

Added.

**Comment by keyonghan** [comment]
> We don't need to address in this PR, but something to think about: mac and mac_arm could be used for macOS desktop benchmarks, so do we need to peg to a particular Mac model like Macmini8,1 or Macmini8,1 so they all run on the same type of machine?

Seems we deprecated the mac model in: https://github.com/flutter/flutter/pull/101871.
From the bot pool side, `Macmini8,1` is equal to `cpu: x64` whereas `Macmini9,1` is equal to `cpu: arm64`. Do we expect to have more different configs?

**Review by jmagman — COMMENTED** [review]
If `Mac_arm64 tool_host_cross_arch_tests` passes, what's the difference between this and what I did in https://github.com/flutter/flutter/pull/109889, which failed that shard because arm64 Ruby wasn't installed?

https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20tool_host_cross_arch_tests/3779/overview

**Review by jmagman — APPROVED** [review]

**Comment by jmagman** [comment]
> Do we expect to have more different configs?

I'm not sure, will the new arm macs also be `Macmini9,1`?

**Review by a-wallen — APPROVED** [review]
LGTM

**Comment by keyonghan** [comment]
> If Mac_arm64 tool_host_cross_arch_tests passes, what's the difference between this and what I did in https://github.com/flutter/flutter/pull/109889, which failed that shard because arm64 Ruby wasn't installed?

> https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20tool_host_cross_arch_tests/3779/overview

The new target is not picked up by this PR, as it's a new target as `bringup: true`. These targets are not expected to run in pre-submit. Manually ran an led build, and it failed as well.
Closing this as in favor of https://github.com/flutter/flutter/pull/109889.

**Pull request closed without merging**
