### PR TITLE
Add 'fail-fast' argument to flutter test

### LINKED ISSUE #124406: Add a "fast fail" argument to `flutter test` to stop after a failure
## Use case

Tests may take an hour or more to run, especially in a CI environment with limited resources. If there was an argument for `flutter test` (similar to pytest's `--exitfirst`), then a failure that happens within the first 10 minutes, etc. can stop further test execution. This can allow developers to fix tests and re-run them locally, saving a lot of time and money in a CI.

## Proposal

Add an argument such as `flutter test --exit-first` that will stop further text execution when a failure is hit.

### PR DESCRIPTION
**Pull request by Lexycon**
This adds the 'fail-fast' argument to flutter test, since dart test already supports this feature. Tests can now be stopped after first failure. 

Fixes #124406 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by haevensk — COMMENTED** [review]
Still failing mac tests

**Review by andrewkolos — CHANGES_REQUESTED** [review]
Thanks for the PR! It looks like this change doesn't update or add any tests. I think this is something we could put under test without much more maintenance burden. There are some [existing tests](https://github.com/flutter/flutter/blob/054d6191ca8b64294b16eb21fa5c9d95aa86d402/packages/flutter_tools/test/commands.shard/hermetic/test_test.dart#L438-L461) that make sure other flags get piped along to `package:test`. You could draw inspiration from these to write one that makes sure `--fail-fast` is piped along properly. Alternatively, you could merge these tests together into one and then add `--fail-fast` to it. Let me know what you think.

**Comment by Lexycon** [comment]
> Thanks for the PR! It looks like this change doesn't update or add any tests. I think this is something we could put under test without much more maintenance burden. There are some [existing tests](https://github.com/flutter/flutter/blob/054d6191ca8b64294b16eb21fa5c9d95aa86d402/packages/flutter_tools/test/commands.shard/hermetic/test_test.dart#L438-L461) that make sure other flags get piped along to `package:test`. You could draw inspiration from these to write one that makes sure `--fail-fast` is piped along properly. Alternatively, you could merge these tests together into one and then add `--fail-fast` to it. Let me know what you think.

Thank you for your response. I totally missed that there are already tests for flags which gets piped along and wasn't sure if this needs to be tested overall. I will take a look into the existing tests, maybe it really makes sense to merge them. Unfortunately, I am on vacation until mid next week, so this make take a bit. Thank you for your suggestions 😊

**Comment by Lexycon** [comment]
> Thanks for the PR! It looks like this change doesn't update or add any tests. I think this is something we could put under test without much more maintenance burden. There are some [existing tests](https://github.com/flutter/flutter/blob/054d6191ca8b64294b16eb21fa5c9d95aa86d402/packages/flutter_tools/test/commands.shard/hermetic/test_test.dart#L438-L461) that make sure other flags get piped along to `package:test`. You could draw inspiration from these to write one that makes sure `--fail-fast` is piped along properly. Alternatively, you could merge these tests together into one and then add `--fail-fast` to it. Let me know what you think.

I saw this [reporter group test](https://github.com/flutter/flutter/blob/5e448f4ce57723ac0792ae822ebac69df3188ba1/packages/flutter_tools/test/commands.shard/hermetic/test_test.dart#L286-L341) got added a couple of days ago, so I basically did sth. similar and merged the tests (they basically do all the same) for _--start-paused_, _--run-skipped_, _--test-randomize-ordering-seed=random_ and added the _--fail-fast_ test.

There are still some tests which could be merged as well, like the [_--total-shards_ and _--shard-index_ test](https://github.com/flutter/flutter/blob/5e448f4ce57723ac0792ae822ebac69df3188ba1/packages/flutter_tools/test/commands.shard/hermetic/test_test.dart#L240-L284). This one additionally checks that they are not piped by default, but ofc this could be implemented in the merged test group somehow as well.

But, probably we should keep it like it is now, a simple group for only simple passing checks. Let me know what you think.

**Comment by andrewkolos** [comment]
> I saw this [reporter group test](https://github.com/flutter/flutter/blob/5e448f4ce57723ac0792ae822ebac69df3188ba1/packages/flutter_tools/test/commands.shard/hermetic/test_test.dart#L286-L341) got added a couple of days ago, so I basically did sth. similar and merged the tests (they basically do all the same) for `--start-paused`, `--run-skipped`, `--test-randomize-ordering-seed=random` and added the `--fail-fast` test.
> 
> There are still some tests which could be merged as well, like the `--total-shards` and `--shard-index` [test](https://github.com/flutter/flutter/blob/5e448f4ce57723ac0792ae822ebac69df3188ba1/packages/flutter_tools/test/commands.shard/hermetic/test_test.dart#L240-L284). This one additionally checks that they are not piped by default, but ofc this could be implemented in the merged test group somehow as well.
> 
> But, probably we should keep it like it is now, a simple group for only simple passing checks. Let me know what you think.

Ah, I hadn't noticed these tests. Yeah, this is one of the downsides of trying to group these into a single test. I think this is fine as it is; as long as the `fail-fast` flag is under test, I'm happy.

**Review by andrewkolos — APPROVED** [review]
LGTM with nitpick

**Comment by Lexycon** [comment]
Thank you. Can you check your CLA? I think its missing for the PR.

**Comment by andrewkolos** [comment]
> Thank you. Can you check your CLA? I think its missing for the PR.

Yeah, I think this might be an issue with me using the GitHub suggestion feature. I'll investigate 👍

**Comment by andrewkolos** [comment]
Added @jonahwilliams as a second reviewer since @christopherfujino is out-of-action for a couple of days

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by gnprice** [comment]
Looking forward to using this feature — thanks @Lexycon for adding it! Glad the `--reporter` tests were helpful.

**Pull request merged**
