### PR TITLE
api documentation's font importation lacks of font-weight

### PR DESCRIPTION
**Pull request by keidaroo**
## Description

Flutter API documentation has accessibility problems, especially on the font-weight.
I've added 100 to all font-weight parameter, which makes it more visible. 

In my environment, the docs don't seem to be that invisible, but looking at other environments like the issue I mentioned below, in some environment, it seems to be really invisible.

The image below compares how it looks, so please look at it.

This is my first pull request to flutter, so feedbacks are highly welcome.

**Before**
1.
image
2.
image

**After**
1.
image
2.
image

## Related Issues

#47796 

## Tests

I've generated my docs using what is written [here](https://github.com/flutter/flutter/tree/master/dev/snippets), and I found some points differs to the original one, but I think this is unrelated to this commit because I didn't change any code that is related to the context of the docs.

But no tests added because this is a doc change

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. 

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by keidaroo** [comment]
@googlebot I fixed it.

**Comment by raison00** [comment]
hi @keidaroo  - i've looked into this and here's some of my findings to help clarify the issue:

I do not see this as a technical issue, but rather a Design issue.  I can use typical accessibility tools built into the browser to increase/decrease the fonts without issue.  

image

It seems your main concern is with the current font choice - Source Code Pro and Roboto Light - which is intentionally designed to be thin sans-serif fonts.  These fonts, when paired with light colors, can be "invisible" to the eye in smaller sizes.  

I see in your screens above, you changed the font to Arial or Helvetica, which improved the readability.  To me, this is an issue which would be resolved with a different font choice that will be readable with lighter colors. [ Google Fonts](https://fonts.google.com/) has many options other than Arial/Helvetica that will look modern and be readable/accessible.  



image


Note: The thinnest font on the page is actually Roboto Light with a 300 weight.  

image

**Comment by sfshaza2** [comment]
We should have our docs evaluated for accessibility, both on desktop and  in mobile environments. Just changing the font weight across the board is not how we should approach this.

**Comment by dnfield** [comment]
Thanks for the suggestion @keidaroo!  This is definitely an important issue.

Do you think you'll be able to address @sfshaza2 and @raison00's feedback, or should we close this for now?

**Comment by keidaroo** [comment]
Thank you for your feedbacks! (@raison00 @sfshaza2 @dnfield )

I agree with what @sfshaza2 says, this suggestion isn't evaluated enough, and this issue shouldn't be solved as simply changing the font-weight. In the next commit, I'll delete all changes of the weight adding things.

But still, I found another issue about the font-weight, which is related to what @raison00 says. 
In the header file of this page, it is written like
`
@import 'https://fonts.googleapis.com/css?family=Roboto:500,400italic,300,400,100i';
` 
and this means 300i(talic) font isn't imported.

> Note: The thinnest font on the page is actually Roboto Light with a 300 weight.

so this is incorrect, actually, it is using 100 italic font instead of 300 italic font. In the browser debugging console, it is written that the text is using a 300-weight font, but this is just showing the css setting, not the actual font-weight.
You can check this by saving the webpage and changing the heading into 
`
@import 'https://fonts.googleapis.com/css?family=Roboto:500,400italic,300,400,300i';
`
and this is the result.

**Before**
image
**After**
image

It is obvious from the values that 100-weight font is almost "invisible", and I think this needs to be changed.

Can I fix this bug in this pull-request or should I close this and open a new pull-request?

( @raison00 actually, I didn't change any font-family, I just added font-weight into all text)

**Comment by keidaroo** [comment]
Sorry, the last comment was including a mistake.
The thinnest font-weight was actually 100 in the original CSS settings.
Screen Shot 2020-01-05 at 2 52 08

image

Still, Roboto 300-weight font is not imported, so it must be imported.
Screen Shot 2020-01-05 at 2 55 40
image

**Comment by keidaroo** [comment]
Two months past, do you have any suggestions about this PR? 
Also, I think this "Waiting for customer response" label should be taken off.

**Comment by dnfield** [comment]
Removed the label - will wait for response from @sfshaza2 or @raison00

**Comment by awulkan** [comment]
Does anyone have any update regarding this issue? The docs have pretty much been unusable for me since I started learning Flutter this year. I have to edit the css in my browser every time I go to the documentation site.

Chrome, Edge and Firefox, on Windows 10.
1440p VA monitor and 1080p IPS monitors.

**Comment by dnfield** [comment]
Since this PR is out of date, and has had no activity for some time, and there was some meaningful disagreement about whether it's the right way to fix potential a11y issues, I'm going to close it.

I've filed https://github.com/dart-lang/dartdoc/issues/2374 and https://github.com/flutter/website/issues/4824

**Pull request closed without merging**
