### PR TITLE
Revert "Roll engine 74662ab69523..7e3b41dc7ba6 (6 commits)"

### PR DESCRIPTION
**Pull request by dnfield**
Reverts flutter/flutter#22639

Breaks on device lab - 

```
stdout:     Building AOT snapshot in release mode (ios-release)...          
stdout:     Unhandled exception:
stdout:     Unsupported operation: Cannot extract a file path from a org-dartlang-sdk URI
stdout:     #0      _SimpleUri.toFilePath (dart:core/uri.dart:4589:7)
stdout:     #1      _writeDepfile (package:vm/frontend_server.dart:655:32)
```

### CODE REVIEW

**Comment by dnfield** [comment]
Landing TBR @cbracken

**Comment by cbracken** [comment]
lgtm. Thanks for reverting!

**Comment by cbracken** [comment]
@dnfield Have you bisected to an engine commit? If not, we'll get someone on that.

**Comment by dnfield** [comment]
Pretty sure it's https://github.com/flutter/engine/pull/6402

**Pull request merged**
