### PR TITLE
Audit `TODO` syntax

### PR DESCRIPTION
**Pull request by Hixie**
Fixes the pattern for some TODOs to match our style guide.

(Also, a couple of minor code order fixes.)

### CODE REVIEW

**Comment by Hixie** [comment]
i guess cc @dantup for review since the only actual code i changed was yours. :-)

**Comment by Hixie** [comment]
cc @a14n -- would be amazing if we had a lint that caught common mistakes in the TODO syntax

**Review by DanTup — APPROVED** [review]
LGTM!

**Comment by Hixie** [comment]
Thanks for the review!

**Pull request merged**
