### PR TITLE
added allowFloatingBottomNavigation option to Scaffold

### PR DESCRIPTION
**Pull request by BenWildeman**
satisfies #26499

### CODE REVIEW

**Review by dnfield — CHANGES_REQUESTED** [review]
This needs a test.  It's also not clear to me that this change makes sense, as the Scaffold is meant to be following the Material Spec, and this is not.  Perhaps there is some way that the functionality here could be exposed without introducing non-Material changes to this widget?

**Comment by dnfield** [comment]
I'm going to close this as it has had no response in nearly a month, is out of sync with master, and is already tracked by an open issue.

If you're able to address the feedback, sync this up to master, and add some tests, please feel free to reopen.  For this particular case, I'd recommend getting more clarity in the issue first, as this seems like a deviation from the material spec.

**Comment by mposch-Z** [comment]
Where exactly has this landed.  Is there a formal resolution provided by the flutter library or are people still just applying there own workarounds? 

I've found a resolution but would like to pull the correct levers, if they exist...

**Comment by mposch-Z** [comment]
@dnfield - I was able to get the functionality w/o deviating from the material spec...
Refer to #26499 comments.  I've adjusted vHandas keyboard to take a bool which will determine if the keyboard should cover the bottomAppBar (or not).  Used in a stateful widget that contains a bool to determine if we should dock to the top of the keyboard or get covered up..

**Pull request closed without merging**
