### PR TITLE
Delete all temporary files in flutter test.

### PR DESCRIPTION
**Pull request by Hixie**
Turns out we weren't deleting the dill directory or the fonts directory.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @fkorotkov `tool_tests-macos` on this PR seems to have failed in an unexpected fashion unrelated to our own issues.

**Comment by Hixie** [comment]
cc @tvolkert or @gspencergoog for review

**Comment by fkorotkov** [comment]
@Hixie there is Flutter output `Some tests failed.` Maybe something is flaky?

The yellow sing says that Cirrus CI agent **twice** failed to upload logs for `artifacts` script.

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Review by tvolkert — APPROVED** [review]

**Comment by Hixie** [comment]
@fkorotkov I meant specifically the `Fatal exception on the agent! Failed to start uploading logs for command artifacts: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 130.211.170.105:8239: connect: operation timed out"` warning.

**Comment by Hixie** [comment]
(The test failure itself is a real failure for us. A flake, unfortunately. Flakes are my current priority.)

**Comment by Hixie** [comment]
Ok tests passed. Thanks for the reviews, will land on green.

**Comment by Hixie** [comment]
@fkorotkov Not clear what happened on the analyze shard here, but it seems to have just died during setup? Nothing in the logs indicates a failure...

**Comment by fkorotkov** [comment]
@Hixie don't see anything suspicious in the logs. The agent just reported that the script exited with a non-zero exit code. Will try to see if I can gather more information...

**Comment by fkorotkov** [comment]
I didn’t find anything suspicious. Host node was not preempted, container didn't die, the agent just got a non-zero exit code. In case of preeption and enexpected dying a task should be automatically restarted. 

Complete mistery! Will continue looking...

**Comment by Hixie** [comment]
Weird. Could also be something on our end of course.

**Pull request merged**
