### PR TITLE
Add flag to use adjusted value for newIndex in onReorder callback for ReorderableList widgets

### LINKED ISSUE #24786: ReorderableListView#onReorder passes an unexpected new index
The `ReorderableListView` widget seems to passing an incorrect `newIndex` parameter when triggering the `onReorder` handler.

## Steps to Reproduce
Here's a demo of the behavior as described in the below steps:  
https://gist.github.com/chrislambe/b9aa44a5f3d3cc7dc6fdb24fb221982d

1. Create an app with a `ReorderableListView` widget and dummy data.
2. In the `onReorder` handler, print out the new index.
3. Drag the item in the 0 index position down until it swaps positions with the item in 1 index then, without releasing the item, drag it back to its original position and release. Note that the printed new index is `1` instead of `0`, even though the intent was to drop the item in its original position.
4. Drag the item to the bottom of the list and release. Note that the new index is 1 greater than the bounds of the `children` `List`.

### Result of above step 3
```
flutter: oldIndex: 0, newIndex: 1, length: 4
```

### Result of above step 4
```
flutter: oldIndex: 0, newIndex: 4, length: 4
```

### `flutter analyze`

```
$ flutter analyze
Analyzing on_reorder_broken...
No issues found! (ran in 2.3s)
```

### `flutter doctor -v`

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v0.11.9, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 0.11.9 at /Applications/flutter
    • Framework revision d48e6e433c (7 days ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (2 available)
    • moto x4   • ZY224KS2L3                           • android-arm64 • Android 8.1.0 (API 27)
    • iPhone XR • F2133438-AFB5-421D-9CC0-36FD9FE97D28 • ios           • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by markusaksli-nc**
Adds an opt-in flag to use the adjusted value for the `newIndex` in `onReorder` for `ReorderableListView` and the underlying `SliverReorderableList`. Starting off with opt-in since this will be a breaking change (see https://github.com/flutter/flutter/pull/59103)

From gallery `reorderable_list_demo.dart`:
```dart
  void _onReorder(int oldIndex, int newIndex) {
    setState(() {
      // This part becomes unnecessary
      // if (newIndex > oldIndex) {
      //   newIndex -= 1;
      // }
      final _ListItem item = _items.removeAt(oldIndex);
      _items.insert(newIndex, item);
    });
  }
```

Starts off the breaking change to fix https://github.com/flutter/flutter/issues/24786

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by markusaksli-nc** [comment]
I haven't done the guide yet, first just let me know if I'm starting this off right since it's my first breaking change.

**Comment by HansMuller** [comment]
@markusaksli-nc - the 3 1/2 year old issue that this PR would fix is embarrassing for both its age and the triviality of the obvious remedy.  The original widget (https://github.com/flutter/flutter/pull/18374) had a long gestation period and the onReorder callback problem (https://github.com/flutter/flutter/issues/24786) which was reported about 3 months later, was not dealt with promptly.  The approach you've suggested here, allowing developers to opt-in to the fix, does make sense, but we don't have a way to automatically update code (via [FlutterFix](https://docs.flutter.dev/development/tools/flutter-fix)) that works around the problem per the [original documentation](https://api.flutter.dev/flutter/widgets/ReorderCallback.html).  That means that we'd have to continue to support the opt-in flag forever, which - IMHO - complicates everything just a little more than the fix is worth.

There are other ways to handle this, e.g. we could add an additional callback, but having two almost identical callbacks doesn't seem like an overall improvement either.

**Comment by markusaksli-nc** [comment]
I had this concern back when I looked at this issue (although I didn't think it was that hopeless). At this point is there even a viable way to get this fix in? Nothing comes to mind right away other than the flag (which seems pointless without migration) or another callback.

**Comment by HansMuller** [comment]
It's a shame, but I think - at this point in time - it's best to leave this issue as it is.

**Comment by toysonlocation** [comment]
Personally I think this is like saying that because we accidentally reversed 1 and 0, from henceforth the number line shall be 1, 0, 2, 3, 4, 5, 6, 7, 8, 9. It's a VERY common use item, so it should be corrected for the future of Flutter, which will be much longer than its past, right? I hope? Do you not expect BETTER things to come?

How about advancing the language version just for this, since it's so freaking common a function? Bump it to 2.5, BREAKING, like was done to 2.0. Why is that a problem? Fix this for the future, don't hobble it for the past.

**Comment by 1AlexFix1** [comment]
official crutches....

**Pull request closed without merging**
