### PR TITLE
Add full size Cupertino calendar date picker

### PR DESCRIPTION
**Pull request by TahaTesser**
Related https://github.com/flutter/flutter/issues/63693

This introduces a standalone full-size Cupertino Calendar Picker, this will become one of the picker styles in `CupertinoDatePicker`.  This is designed to be as close as possible to the native full-size calendar picker. Initial Implementation matches Material's calendar picker.

This calendar picker has two views grid and wheel (the wheel is customized to show month/year). 

### Light mode
| Month/Day View | Month/Year View |
| --------------- | --------------- |
|  |  |

### Dark mode
| Month/Day View | Month/Year View |
| --------------- | --------------- |
|  |  |

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 10 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/93130

**Comment by skia-gold** [comment]
Gold has detected about 10 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/93130

**Comment by skia-gold** [comment]
Gold has detected about 11 new digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/93130

**Comment by skia-gold** [comment]
Gold has detected about 9 new digest(s) on patchset 5.
View them at https://flutter-gold.skia.org/cl/github/93130

**Comment by skia-gold** [comment]
Gold has detected about 18 new digest(s) on patchset 8.
View them at https://flutter-gold.skia.org/cl/github/93130

**Comment by skia-gold** [comment]
Gold has detected about 10 new digest(s) on patchset 9.
View them at https://flutter-gold.skia.org/cl/github/93130

**Comment by skia-gold** [comment]
Gold has detected about 6 new digest(s) on patchset 9.
View them at https://flutter-gold.skia.org/cl/github/93130

**Comment by TahaTesser** [comment]
Updated `flutter_localizations` and update tests
This is ready to be reviewed :)

**Review by LongCatIsLooong — COMMENTED** [review]
Thank you for the pull request! Left comments on a few minor things. I noticed the implementation of the new date picker is very similar to the material date picker. It will be great if we can take advantage of the existing material date picker implementation and avoid introducing duplicated code.

Discussed this with @HansMuller and @darrenaustin, they suggested moving the implementation to the material library and expose the calendar picker widget via a `CalendarDatePicker .adaptive` or `DatePicker.adaptive` constructor. What do you think?

**Comment by TahaTesser** [comment]
@LongCatIsLooong 
Thanks so much for your valuable feedback.

> Thank you for the pull request! Left comments on a few minor things. I noticed the implementation of the new date picker is very similar to the material date picker. It will be great if we can take advantage of the existing material date picker implementation and avoid introducing duplicated code.
> 
> Discussed this with @HansMuller and @darrenaustin, they suggested moving the implementation to the material library and expose the calendar picker widget via a CalendarDatePicker .adaptive or DatePicker.adaptive constructor. What do you think?

I'm gonna take this approach adaptive approach. I'll take your all suggestions here into count and work on this implementation in the new PR to avoid adding that code to this bubbled PR. Closing this for now.

**Comment by SimonHausdorf** [comment]
@TahaTesser Do you have any timeline for this? Many people love this feature and are waiting for it! Thanks for your contribution.

**Comment by mehcode** [comment]
Any update here? I would really love having the iOS 14+ calendar picker in flutter.

**Comment by GianlucaAntolini** [comment]
Updates?

**Pull request closed without merging**
