### PR TITLE
partial revert of repaint boundary change

### PR DESCRIPTION
**Pull request by jonahwilliams**
Several scuba failures may be due to a bad interaction between this change and the visibility widget which uses Opacity. See https://buganizer.corp.google.com/issues/230559665

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM. Consider adding a test here that would fail in the same way the internal one is.

**Comment by CaseyHillers** [comment]
Are you sure the opacity changes aren't related to b/230173482?

**Comment by jonahwilliams** [comment]
Yes, this wasn't a scuba issue actually it was an assert hit during a scuba test which broke the layout in a few. But nothing surfaces that because scuba is terrible

**Review by CaseyHillers — APPROVED** [review]

**Comment by jonahwilliams** [comment]
> LGTM. Consider adding a test here that would fail in the same way the internal one is.

The internal test isn't even a test, its a scuba and completely worthless. /rant

**Pull request merged**
