### PR TITLE
disable new transition while toPictureSync is fixed

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts default usage of toPictureSync while we work through https://github.com/flutter/flutter/issues/108389

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Waiting to see what tests fail...

**Review by dnfield — APPROVED** [review]
LGTM assuming tests pass.

**Comment by jonahwilliams** [comment]
Test updated

**Comment by gaaclarke** [comment]
This caused an expected regression in `worst_frame_rasterizer_time`: https://flutter-flutter-perf.skia.org/e/?begin=1659024246&end=1659047228&keys=X33785e9f2188721ac4d7c41915b31f19&num_commits=50&request_type=1&xbaroffset=30154

**Comment by dnfield** [comment]
> This caused an expected regression in `worst_frame_rasterizer_time`: https://flutter-flutter-perf.skia.org/e/?begin=1659024246&end=1659047228&keys=X33785e9f2188721ac4d7c41915b31f19&num_commits=50&request_type=1&xbaroffset=30154

Yes - we're losing the benefits we had gained from this change, but for now we need to because the API has a race condition in it that can cause crashes, which I'm working on fixing.

**Pull request merged**
