### PR TITLE
Revert "Update PopupMenuButton to match Material Design spec"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#70160

This change is causing the android_semantics integration test to fail due to potentially unexpected changes in the semantics tree:

With an attached android device: `cd dev/devicelab\ndart bin/run.dart -t android_semantics_integration_test`

```
AccessibilityBridge Popup Controls Popup Menu has correct Android semantics [E]
[android_semantics_integration_test] [STDOUT] stdout: [        ]   Expected: AndroidSemanticsNode with className: android.widget.Button with actions: [AndroidSemanticsAction.accessibilityFocus, AndroidSemanticsAction.click] with flag isChecked: false with flag isEnabled: true with flag isFocusable: true
[android_semantics_integration_test] [STDOUT] stdout: [        ]     Actual: AndroidSemanticsNode:<{rect: {top: 0.0, left: 0.0, bottom: 813.0908813476562, width: 1080, right: 392.7272644042969, height: 2236}, contentDescription: null, flags: {isHeading: false, isEditable: false, isPassword: false, isEnabled: true, isLongClickable: false, isCheckable: false, isChecked: false, isFocused: false, isFocusable: false, isDismissable: false}, className: android.view.View, liveRegion: 0, id: 47, text: null, actions: [64]}>
[android_semantics_integration_test] [STDOUT] stdout: [        ]      Which: Expected className: android.widget.Button
```

```
AccessibilityBridge Popup Controls Dropdown Menu has correct Android semantics [E]
[android_semantics_integration_test] [STDOUT] stdout: [        ]   Expected: AndroidSemanticsNode with className: android.view.View with actions: [AndroidSemanticsAction.accessibilityFocus, AndroidSemanticsAction.click] with flag isChecked: false with flag isEnabled: true with flag isFocusable: true
[android_semantics_integration_test] [STDOUT] stdout: [        ]     Actual: AndroidSemanticsNode:<{rect: {top: 425.81817626953125, left: 125.45454406738281, bottom: 473.81817626953125, width: 302, right: 235.27272033691406, height: 132}, contentDescription: Item 1, flags: {isHeading: false, isEditable: false, isPassword: false, isEnabled: true, isLongClickable: false, isCheckable: false, isChecked: false, isFocused: true, isFocusable: true, isDismissable: false}, className: android.view.View, liveRegion: 0, id: 57, text: null, actions: [16, 128]}>
[android_semantics_integration_test] [STDOUT] stdout: [        ]      Which: Expected actions: [AndroidSemanticsAction.accessibilityFocus, AndroidSemanticsAction.click]
[android_semantics_integration_test] [STDOUT] stdout: [        ]             Actual actions: [AndroidSemanticsAction.clearAccessibilityFocus, AndroidSemanticsAction.click]
[android_semantics_integration_test] [STDOUT] stdout: [        ]             Unexpected: {AndroidSemanticsAction.clearAccessibilityFocus}
[android_semantics_integration_test] [STDOUT] stdout: [        ]             Missing: {AndroidSemanticsAction.accessibilityFocus}
[android_semantics_integration_test] [STDOUT] stdout: [        ]   Dropdown Item 1 doesn't have the right semantics
```

@xu-baolin @goderbauer @Piinks

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
Merging on red to fix tree

**Comment by xu-baolin** [comment]
[Update] The result of the current investigation is that the following change caused the failure, but I still can't understand why warp some widgets will cause semantic changes, and I need to continue working.
image

**Comment by jonahwilliams** [comment]
I wonder if there is a timing issue here? i.e. the first "frame" of information that talkback gets has the IconButton at zero size, so the semantics aren't there. Later updates in the LayoutBuilder fix things, but not necessarily in sync with what talkback exepcts?

**Comment by xu-baolin** [comment]
The information you pointed out gave me inspiration. @jonahwilliams Thank you very much 👍 . 
Now I have posted a PR to fix the test case.  Welcome to review #74620.

**Pull request merged**
