### PR TITLE
Fix that the custom underline color of the TextField is invalid

### PR DESCRIPTION
**Pull request by hezl2021**
Hi,I am  new to Flutter development.When I use the TextFiled, I found that the color of the underline displayed is not the color I set.This PR fix the issue.

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 8 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/85113

**Comment by gspencergoog** [comment]
Hi @hezl2021 can you please modify the description of this PR to include the motivation for it, what it is fixing/adding, refer to any existing issues, and add some tests for your change? It's hard to review the change without all the context for it.

If you're new to Flutter development, it might also be useful to read [the Contributor Guide](https://github.com/flutter/flutter/wiki/Tree-hygiene#overview).

**Comment by gspencergoog** [comment]
@hezl2021 are you still interested in pursuing this PR?

If not, or if you want to come back to it later, I'd encourage you to to close it for now and open a new one when you're ready to continue.

**Comment by hezl2021** [comment]
> Hi @hezl2021 can you please modify the description of this PR to include the motivation for it, what it is fixing/adding, refer to any existing issues, and add some tests for your change? It's hard to review the change without all the context for it.
> 
> If you're new to Flutter development, it might also be useful to read [the Contributor Guide](https://github.com/flutter/flutter/wiki/Tree-hygiene#overview).

I have update the description of this PR,thank you for your reminder.

**Comment by gspencergoog** [comment]
@hezl2021 Thanks for updating the description.

It looks like your change is breaking an existing test. This is usually an indication that the code is doing something that the test isn't expecting. Can you look at that test and see if you can modify your code to not break the test?

Also, as you probably read in the contributor guide, we do require that your change include a test that fails before your code change, and succeeds after your code change.

**Comment by hezl2021** [comment]
@gspencergoog Thank you for your reminder.
I'll try to pass the test.

**Comment by skia-gold** [comment]
Gold has detected about 6 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/85113

**Comment by gspencergoog** [comment]
Great, it looks like you were able to get the test to pass.  Now we just need a test for your change to make sure it doesn't regress when someone else makes a change.

**Comment by gspencergoog** [comment]
Also, it looks like this change modifies how the text borders are painted: it looks like they get darker with this change: perhaps the border is being painted twice?

Here's a GIF of what I mean. It swaps between an image with your change, and an image without your change. It's darker with your change.

diff

**Comment by hezl2021** [comment]
@gspencergoog I want it to display the color I set. Before I change it, it doesn't display the color I set.
image

**Comment by gspencergoog** [comment]
@hezl2021 I'm not sure I understand what the issue is that you're trying to solve. Can you post a small code sample that shows when the color isn't as you expect? The image doesn't really show all the information. And also please post the output of `flutter doctor -v`, so I know what versions of the framework you are running with.

**Comment by Hixie** [comment]
@hezl2021 I'm going to close this PR since it still needs tests and we haven't heard from your in a while, but please don't hesitate to submit a new PR if you have a chance and can answer @gspencergoog's questions. Thanks!

**Pull request closed without merging**
