### PR TITLE
Change suffix of the results in Dart 2.0 microbenchmarks

### PR DESCRIPTION
**Pull request by alexmarkov**
... to match other benchmarks.

### CODE REVIEW

**Review by aam — APPROVED** [review]

**Review by yjbanov — CHANGES_REQUESTED** [review]
I'd rather we kept the names. Changing names wreaks havoc on the dashboard by abandoning old cards and creating new ones.

**Comment by Hixie** [comment]
The benchmarks are very new. The overall cost of having them not use the same style as the others will vastly outweigh the temporary cost of having to archive a few names.

**Comment by yjbanov** [comment]
FWIW, I updated all the UI labels to "_preview_dart_2" prefix, so the search box on the dashboard now locates all of the Dart 2 results.

**Comment by yjbanov** [comment]
Maybe we should use numbers as our benchmark IDs so we don't have to change them.

**Pull request closed without merging**
