### PR TITLE
Switch over to the Travis-built artifacts

### PR DESCRIPTION
**Pull request by abarth**
We've been bulding these binaries using Travis for a while. We can start using
them now.

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
lgtm

**Comment by eseidelGoogle** [comment]
Looks like mac was already using those and this switches the rest.

**Comment by abarth** [comment]
That's correct.  That's how I got started down this path was that we needed to produce some mac binaries as part of the release process.

**Comment by Hixie** [comment]
Should we update the engine release instructions and script as well?

**Comment by abarth** [comment]
> Should we update the engine release instructions and script as well?

Yes, but I wanted to wait a bit in case we need to revert this change.  Having both binaries in the cloud for a while will make reverting much easier.

**Comment by Hixie** [comment]
Roger.

**Pull request merged**
