### PR TITLE
[flutter_tool] Roll the Fuchsia SDK forward

### PR DESCRIPTION
**Pull request by zanderso**
Rolls the Fuchsia SDK pulled by the Flutter tool. Matches the version currently pulled by the engine.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by blasten — APPROVED** [review]
Do we have a ticket on automatizing the roll?

**Comment by zanderso** [comment]
Yeah, there's one here: https://github.com/flutter/flutter/issues/46173

**Pull request merged**
