### PR TITLE
comment some lint exclusions

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
LGTM

**Comment by Hixie** [comment]
I wonder if there's a way we can get the benefits of avoid_catches_without_on_clauses anyway...

**Comment by a14n** [comment]
@Hixie there are a lot of lint to fix and every change needs to really well understand what Exception/Error can occurs. I don't have enough knowledge to put the right type on the `on` clause (I can use `on Object` but it's pointless :) )

- [dev/integration_tests/channels/lib/src/basic_messaging.dart, line 102, col 5](https://github.com/flutter/flutter/blob/master/dev/integration_tests/channels/lib/src/basic_messaging.dart#L102)
- [dev/integration_tests/channels/lib/src/basic_messaging.dart, line 124, col 5](https://github.com/flutter/flutter/blob/master/dev/integration_tests/channels/lib/src/basic_messaging.dart#L124)
- [dev/integration_tests/channels/lib/src/method_calls.dart, line 122, col 5](https://github.com/flutter/flutter/blob/master/dev/integration_tests/channels/lib/src/method_calls.dart#L122)
- [dev/integration_tests/channels/lib/src/method_calls.dart, line 94, col 5](https://github.com/flutter/flutter/blob/master/dev/integration_tests/channels/lib/src/method_calls.dart#L94)
- [dev/integration_tests/channels/lib/src/method_calls.dart, line 64, col 5](https://github.com/flutter/flutter/blob/master/dev/integration_tests/channels/lib/src/method_calls.dart#L64)
- [dev/tools/dartdoc.dart, line 204, col 5](https://github.com/flutter/flutter/blob/master/dev/tools/dartdoc.dart#L204)
- [dev/devicelab/bin/tasks/gradle_plugin_test.dart, line 67, col 7](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/gradle_plugin_test.dart#L67)
- [dev/devicelab/lib/framework/utils.dart, line 464, col 7](https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/utils.dart#L464)
- [dev/devicelab/lib/framework/adb.dart, line 172, col 9](https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/adb.dart#L172)
- [dev/devicelab/lib/framework/runner.dart, line 107, col 7](https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/framework/runner.dart#L107)
- [examples/layers/services/isolate.dart, line 50, col 7](https://github.com/flutter/flutter/blob/master/examples/layers/services/isolate.dart#L50)
- [examples/flutter_gallery/test/live_smoketest.dart, line 43, col 5](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/test/live_smoketest.dart#L43)
- [examples/catalog/bin/sample_page.dart, line 255, col 5](https://github.com/flutter/flutter/blob/master/examples/catalog/bin/sample_page.dart#L255)
- [examples/stocks/lib/stock_data.dart, line 34, col 7](https://github.com/flutter/flutter/blob/master/examples/stocks/lib/stock_data.dart#L34)
- [examples/stocks/lib/stock_home.dart, line 134, col 17](https://github.com/flutter/flutter/blob/master/examples/stocks/lib/stock_home.dart#L134)
- [packages/flutter/test/foundation/error_reporting_test.dart, line 22, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter/test/foundation/error_reporting_test.dart#L22)
- [packages/flutter/test/foundation/error_reporting_test.dart, line 31, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter/test/foundation/error_reporting_test.dart#L31)
- [packages/flutter/test/foundation/error_reporting_test.dart, line 13, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter/test/foundation/error_reporting_test.dart#L13)
- [packages/flutter/test/foundation/synchronous_future_test.dart, line 49, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/test/foundation/synchronous_future_test.dart#L49)
- [packages/flutter/test/services/asset_bundle_test.dart, line 45, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/test/services/asset_bundle_test.dart#L45)
- [packages/flutter/test/services/platform_channel_test.dart, line 73, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/test/services/platform_channel_test.dart#L73)
- [packages/flutter/test/services/platform_channel_test.dart, line 136, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/test/services/platform_channel_test.dart#L136)
- [packages/flutter/test/services/platform_channel_test.dart, line 155, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/test/services/platform_channel_test.dart#L155)
- [packages/flutter/test/services/platform_channel_test.dart, line 88, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/test/services/platform_channel_test.dart#L88)
- [packages/flutter/test/engine/color_test.dart, line 40, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/test/engine/color_test.dart#L40)
- [packages/flutter/test/engine/color_test.dart, line 30, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/test/engine/color_test.dart#L30)
- [packages/flutter/test/rendering/mock_canvas.dart, line 435, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/test/rendering/mock_canvas.dart#L435)
- [packages/flutter/test/rendering/mock_canvas.dart, line 499, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/test/rendering/mock_canvas.dart#L499)
- [packages/flutter/test/widgets/navigator_test.dart, line 56, col 11](https://github.com/flutter/flutter/blob/master/packages/flutter/test/widgets/navigator_test.dart#L56)
- [packages/flutter/test/widgets/parent_data_test.dart, line 42, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter/test/widgets/parent_data_test.dart#L42)
- [packages/flutter/test/widgets/inherited_test.dart, line 46, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/test/widgets/inherited_test.dart#L46)
- [packages/flutter/test/widgets/multichild_test.dart, line 28, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter/test/widgets/multichild_test.dart#L28)
- [packages/flutter/lib/src/scheduler/binding.dart, line 714, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/scheduler/binding.dart#L714)
- [packages/flutter/lib/src/gestures/binding.dart, line 122, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/gestures/binding.dart#L122)
- [packages/flutter/lib/src/gestures/recognizer.dart, line 103, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/gestures/recognizer.dart#L103)
- [packages/flutter/lib/src/gestures/pointer_router.dart, line 74, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/gestures/pointer_router.dart#L74)
- [packages/flutter/lib/src/animation/listener_helpers.dart, line 110, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/animation/listener_helpers.dart#L110)
- [packages/flutter/lib/src/animation/listener_helpers.dart, line 162, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/animation/listener_helpers.dart#L162)
- [packages/flutter/lib/src/foundation/binding.dart, line 369, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/binding.dart#L369)
- [packages/flutter/lib/src/foundation/change_notifier.dart, line 131, col 11](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/change_notifier.dart#L131)
- [packages/flutter/lib/src/foundation/synchronous_future.dart, line 56, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/synchronous_future.dart#L56)
- [packages/flutter/lib/src/foundation/diagnostics.dart, line 1803, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/diagnostics.dart#L1803)
- [packages/flutter/lib/src/services/image_stream.dart, line 193, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/image_stream.dart#L193)
- [packages/flutter/lib/src/services/image_stream.dart, line 214, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/image_stream.dart#L214)
- [packages/flutter/lib/src/services/platform_channel.dart, line 210, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/platform_channel.dart#L210)
- [packages/flutter/lib/src/services/platform_channel.dart, line 301, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/platform_channel.dart#L301)
- [packages/flutter/lib/src/services/platform_channel.dart, line 289, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/platform_channel.dart#L289)
- [packages/flutter/lib/src/services/platform_messages.dart, line 68, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/platform_messages.dart#L68)
- [packages/flutter/lib/src/services/platform_messages.dart, line 43, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/platform_messages.dart#L43)
- [packages/flutter/lib/src/rendering/error.dart, line 117, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/error.dart#L117)
- [packages/flutter/lib/src/rendering/error.dart, line 54, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/error.dart#L54)
- [packages/flutter/lib/src/rendering/object.dart, line 2413, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/object.dart#L2413)
- [packages/flutter/lib/src/rendering/object.dart, line 1949, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/object.dart#L1949)
- [packages/flutter/lib/src/rendering/object.dart, line 2718, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/object.dart#L2718)
- [packages/flutter/lib/src/rendering/object.dart, line 1965, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/object.dart#L1965)
- [packages/flutter/lib/src/rendering/object.dart, line 1839, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/object.dart#L1839)
- [packages/flutter/lib/src/widgets/binding.dart, line 811, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/binding.dart#L811)
- [packages/flutter/lib/src/widgets/framework.dart, line 3588, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/framework.dart#L3588)
- [packages/flutter/lib/src/widgets/framework.dart, line 3506, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/framework.dart#L3506)
- [packages/flutter/lib/src/widgets/framework.dart, line 2428, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/framework.dart#L2428)
- [packages/flutter/lib/src/widgets/framework.dart, line 2263, col 11](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/framework.dart#L2263)
- [packages/flutter/lib/src/widgets/framework.dart, line 3576, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/framework.dart#L3576)
- [packages/flutter/lib/src/widgets/layout_builder.dart, line 113, col 11](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/layout_builder.dart#L113)
- [packages/flutter/lib/src/widgets/layout_builder.dart, line 121, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/layout_builder.dart#L121)
- [packages/flutter/lib/src/widgets/sliver.dart, line 109, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/sliver.dart#L109)
- [packages/flutter_driver/test/flutter_driver_test.dart, line 325, col 11](https://github.com/flutter/flutter/blob/master/packages/flutter_driver/test/flutter_driver_test.dart#L325)
- [packages/flutter_driver/test/flutter_driver_test.dart, line 340, col 11](https://github.com/flutter/flutter/blob/master/packages/flutter_driver/test/flutter_driver_test.dart#L340)
- [packages/flutter_driver/lib/src/retry.dart, line 43, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/retry.dart#L43)
- [packages/flutter_driver/lib/src/driver.dart, line 490, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/driver.dart#L490)
- [packages/flutter_driver/lib/src/driver.dart, line 332, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/driver.dart#L332)
- [packages/flutter_driver/lib/src/driver.dart, line 603, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/driver.dart#L603)
- [packages/flutter_driver/lib/src/driver.dart, line 474, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/driver.dart#L474)
- [packages/flutter_driver/lib/src/extension.dart, line 165, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_driver/lib/src/extension.dart#L165)
- [packages/flutter_test/test/widget_tester_test.dart, line 137, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_test/test/widget_tester_test.dart#L137)
- [packages/flutter_test/test/widget_tester_test.dart, line 47, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_test/test/widget_tester_test.dart#L47)
- [packages/flutter_test/test/widget_tester_test.dart, line 65, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_test/test/widget_tester_test.dart#L65)
- [packages/flutter_test/test/widget_tester_test.dart, line 24, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_test/test/widget_tester_test.dart#L24)
- [packages/flutter_test/test/widget_tester_test.dart, line 191, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_test/test/widget_tester_test.dart#L191)
- [packages/flutter_test/test/widget_tester_test.dart, line 259, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_test/test/widget_tester_test.dart#L259)
- [packages/flutter_test/test/widget_tester_test.dart, line 120, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_test/test/widget_tester_test.dart#L120)
- [packages/flutter_test/test/stack_manipulation_test.dart, line 12, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_test/test/stack_manipulation_test.dart#L12)
- [packages/flutter_test/test/stack_manipulation_test.dart, line 22, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_test/test/stack_manipulation_test.dart#L22)
- [packages/flutter_test/lib/src/binding.dart, line 420, col 11](https://github.com/flutter/flutter/blob/master/packages/flutter_test/lib/src/binding.dart#L420)
- [packages/flutter_tools/bin/fuchsia_builder.dart, line 121, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/fuchsia_builder.dart#L121)
- [packages/flutter_tools/bin/fuchsia_builder.dart, line 133, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/fuchsia_builder.dart#L133)
- [packages/flutter_tools/test/src/context.dart, line 107, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/src/context.dart#L107)
- [packages/flutter_tools/test/ios/cocoapods_test.dart, line 121, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/ios/cocoapods_test.dart#L121)
- [packages/flutter_tools/lib/src/devfs.dart, line 205, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/devfs.dart#L205)
- [packages/flutter_tools/lib/src/devfs.dart, line 294, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/devfs.dart#L294)
- [packages/flutter_tools/lib/src/devfs.dart, line 491, col 11](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/devfs.dart#L491)
- [packages/flutter_tools/lib/src/devfs.dart, line 218, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/devfs.dart#L218)
- [packages/flutter_tools/lib/src/services.dart, line 43, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/services.dart#L43)
- [packages/flutter_tools/lib/src/run_hot.dart, line 593, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L593)
- [packages/flutter_tools/lib/src/run_hot.dart, line 440, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L440)
- [packages/flutter_tools/lib/src/run_hot.dart, line 601, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L601)
- [packages/flutter_tools/lib/src/run_hot.dart, line 132, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L132)
- [packages/flutter_tools/lib/src/run_hot.dart, line 532, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L532)
- [packages/flutter_tools/lib/src/run_hot.dart, line 113, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L113)
- [packages/flutter_tools/lib/src/run_hot.dart, line 419, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L419)
- [packages/flutter_tools/lib/src/device.dart, line 219, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/device.dart#L219)
- [packages/flutter_tools/lib/src/vmservice.dart, line 92, col 11](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/vmservice.dart#L92)
- [packages/flutter_tools/lib/src/vmservice.dart, line 422, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/vmservice.dart#L422)
- [packages/flutter_tools/lib/src/base/port_scanner.dart, line 57, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/port_scanner.dart#L57)
- [packages/flutter_tools/lib/src/base/build.dart, line 237, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/build.dart#L237)
- [packages/flutter_tools/lib/src/base/build.dart, line 250, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/build.dart#L250)
- [packages/flutter_tools/lib/src/base/utils.dart, line 244, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/utils.dart#L244)
- [packages/flutter_tools/lib/src/base/process.dart, line 259, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/process.dart#L259)
- [packages/flutter_tools/lib/src/base/process.dart, line 250, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/process.dart#L250)
- [packages/flutter_tools/lib/src/runner/flutter_command_runner.dart, line 147, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command_runner.dart#L147)
- [packages/flutter_tools/lib/src/version.dart, line 313, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/version.dart#L313)
- [packages/flutter_tools/lib/src/doctor.dart, line 354, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/doctor.dart#L354)
- [packages/flutter_tools/lib/src/doctor.dart, line 230, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/doctor.dart#L230)
- [packages/flutter_tools/lib/src/doctor.dart, line 406, col 15](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/doctor.dart#L406)
- [packages/flutter_tools/lib/src/test/flutter_platform.dart, line 382, col 11](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/flutter_platform.dart#L382)
- [packages/flutter_tools/lib/src/test/flutter_platform.dart, line 369, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/flutter_platform.dart#L369)
- [packages/flutter_tools/lib/src/test/flutter_platform.dart, line 544, col 17](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/test/flutter_platform.dart#L544)
- [packages/flutter_tools/lib/src/crash_reporting.dart, line 110, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/crash_reporting.dart#L110)
- [packages/flutter_tools/lib/src/commands/daemon.dart, line 424, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/daemon.dart#L424)
- [packages/flutter_tools/lib/src/commands/daemon.dart, line 137, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/daemon.dart#L137)
- [packages/flutter_tools/lib/src/commands/analyze_base.dart, line 36, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/analyze_base.dart#L36)
- [packages/flutter_tools/lib/src/commands/trace.dart, line 59, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/trace.dart#L59)
- [packages/flutter_tools/lib/src/commands/upgrade.dart, line 34, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/upgrade.dart#L34)
- [packages/flutter_tools/lib/src/commands/drive.dart, line 134, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/drive.dart#L134)
- [packages/flutter_tools/lib/src/commands/build.dart, line 86, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/build.dart#L86)
- [packages/flutter_tools/lib/src/commands/screenshot.dart, line 88, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/screenshot.dart#L88)
- [packages/flutter_tools/lib/src/commands/run.dart, line 275, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/run.dart#L275)
- [packages/flutter_tools/lib/src/commands/run.dart, line 58, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/run.dart#L58)
- [packages/flutter_tools/lib/src/commands/run.dart, line 69, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/run.dart#L69)
- [packages/flutter_tools/lib/src/commands/build_aot.dart, line 333, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/build_aot.dart#L333)
- [packages/flutter_tools/lib/src/commands/build_aot.dart, line 408, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/build_aot.dart#L408)
- [packages/flutter_tools/lib/src/commands/fuchsia_reload.dart, line 173, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/fuchsia_reload.dart#L173)
- [packages/flutter_tools/lib/src/commands/fuchsia_reload.dart, line 465, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/fuchsia_reload.dart#L465)
- [packages/flutter_tools/lib/src/resident_runner.dart, line 539, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/resident_runner.dart#L539)
- [packages/flutter_tools/lib/src/resident_runner.dart, line 518, col 11](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/resident_runner.dart#L518)
- [packages/flutter_tools/lib/src/resident_runner.dart, line 722, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/resident_runner.dart#L722)
- [packages/flutter_tools/lib/src/resident_runner.dart, line 530, col 13](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/resident_runner.dart#L530)
- [packages/flutter_tools/lib/src/protocol_discovery.dart, line 82, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/protocol_discovery.dart#L82)
- [packages/flutter_tools/lib/src/android/android_workflow.dart, line 62, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_workflow.dart#L62)
- [packages/flutter_tools/lib/src/android/android_workflow.dart, line 84, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_workflow.dart#L84)
- [packages/flutter_tools/lib/src/android/android_studio.dart, line 139, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_studio.dart#L139)
- [packages/flutter_tools/lib/src/android/android_studio.dart, line 72, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_studio.dart#L72)
- [packages/flutter_tools/lib/src/android/android_device.dart, line 250, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L250)
- [packages/flutter_tools/lib/src/android/android_device.dart, line 452, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L452)
- [packages/flutter_tools/lib/src/android/android_device.dart, line 220, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L220)
- [packages/flutter_tools/lib/src/android/android_device.dart, line 188, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L188)
- [packages/flutter_tools/lib/src/android/gradle.dart, line 99, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/gradle.dart#L99)
- [packages/flutter_tools/lib/src/android/android_sdk.dart, line 182, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_sdk.dart#L182)
- [packages/flutter_tools/lib/src/android/android_sdk.dart, line 165, col 13](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_sdk.dart#L165)
- [packages/flutter_tools/lib/src/run_cold.dart, line 92, col 11](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_cold.dart#L92)
- [packages/flutter_tools/lib/src/asset.dart, line 78, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/asset.dart#L78)
- [packages/flutter_tools/lib/src/ios/plist_utils.dart, line 29, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/plist_utils.dart#L29)
- [packages/flutter_tools/lib/src/ios/devices.dart, line 136, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/devices.dart#L136)
- [packages/flutter_tools/lib/src/ios/devices.dart, line 115, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/devices.dart#L115)
- [packages/flutter_tools/lib/src/ios/devices.dart, line 97, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/devices.dart#L97)
- [packages/flutter_tools/lib/src/ios/devices.dart, line 146, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/devices.dart#L146)
- [packages/flutter_tools/lib/src/ios/mac.dart, line 441, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/mac.dart#L441)
- [packages/flutter_tools/lib/src/ios/simulators.dart, line 365, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/simulators.dart#L365)
- [packages/flutter_tools/lib/src/ios/simulators.dart, line 242, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/simulators.dart#L242)
- [packages/flutter_tools/lib/src/ios/simulators.dart, line 252, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/simulators.dart#L252)
- [packages/flutter_tools/lib/src/ios/simulators.dart, line 381, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/ios/simulators.dart#L381)
- [packages/flutter_tools/lib/src/dependency_checker.dart, line 23, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/dependency_checker.dart#L23)
- [packages/flutter_tools/lib/src/cache.dart, line 182, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/cache.dart#L182)
- [packages/flutter_tools/lib/executable.dart, line 145, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/executable.dart#L145)
- [packages/flutter_tools/lib/executable.dart, line 293, col 5](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/executable.dart#L293)
- [packages/flutter_tools/lib/executable.dart, line 226, col 9](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/executable.dart#L226)
- [packages/flutter_tools/lib/executable.dart, line 321, col 7](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/executable.dart#L321)

**Comment by Hixie** [comment]
There's tons of places where we intentionally catch all exceptions, too, where it's not a bug... I guess it's just something we'll have to deal with in code review.

**Pull request merged**
