### PR TITLE
[Actions] Automate Cherry-Pick Comments and Project Tracking

### PR DESCRIPTION
**Pull request by itsjustkevin**
## Overview
This PR introduces enhancements to the existing cherry-pick workflow in the Flutter GitHub Actions. The updates automate additional steps to streamline the release process, improve traceability, and facilitate better project management.

## Changes
1. **Automated Issue Comments:** Once a cherry-pick PR is successfully created, the workflow now automatically comments on the original PR, providing a link to the cherry-pick PR. This link aids in navigation between related PRs, enhancing transparency and ease of access for reviewers and team members.

2. **Project Tracking Integration:** Additionally, the newly created cherry-pick PR is automatically added to the [Flutter cherry-pick queue](https://github.com/orgs/flutter/projects/103).  This helps in tracking the progress and status of cherry-pick PRs.

## Risk
This workflow enhancement is untested in a live environment due to the nature of GitHub Actions, which cannot be fully simulated or tested in isolation from actual use. As such, there is an inherent risk that the modifications may not perform as expected upon deployment. In the event of unforeseen issues or failure to meet the intended goals, I will promptly revert the changes. 

## Next Steps
Upon successful deployment and verification of the new workflow:
- [ ] **Remove the Cherry-Pick Issue Template:** We will decommission the current cherry-pick issue template as it becomes redundant with the new automated processes.
- [ ] **Update the Wiki:** Revise the cherry-pick section of the Flutter Wiki to reflect the new automated workflow, ensuring all documentation is current and accurate.
- [ ] **Announce the Changes:** Communicate the updates to all relevant parties through our usual channels to ensure that everyone is informed about the new process and how it enhances workflow efficiency.

### CODE REVIEW

**Comment by XilaiZhang** [comment]
LGTM overall! 

But would be great if we could test the part when making post requests. Here is how I previously tested it:
1. I have a [personal repository](https://github.com/XilaiZhang/miscellaneous-side-project) with the [actions script](https://github.com/XilaiZhang/miscellaneous-side-project/blob/master/.github/workflows/easy-cp.yml) I want to test.
2. On a merged pull request of this repository, attach the cp:beta labels. [example PR with labels](https://github.com/XilaiZhang/miscellaneous-side-project/pull/18)
3. verify that the original PR and newly created PRs are updated correctly

Let me know if you would like to create your personal repo, or have me test it for you, thank you!

(only recommending a full test since the actions always use a version that is based on base_commit, it's best to not land any breaking change (otherwise there would be a bad commit range for cherry pick that is not easily revertable))

**Comment by XilaiZhang** [comment]
Maybe I did it wrong, I tried
```
gh api --method POST -H "Accept: application/vnd.github.v3+json" /repos/flutter/flutter/issues/146835/projects -f project_id=103
```
and 
```
gh api --method POST -H "Accept: application/vnd.github.v3+json" /repos/flutter/flutter/issues/146696/projects -f project_id=103
```
locally on my terminal, and I got the response
```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest"
}
gh: Not Found (HTTP 404)
```
Would there be something we need to change to make it work, or maybe we could skip the part of adding it to a project?

**Comment by itsjustkevin** [comment]
Thanks @XilaiZhang I will take another look in the morning and verify that this part is working.  

The reason I feel it's important to get it added to the project is that engine cherry-picks may get lost as we tend to only pay attention to things on the Framework side.

**Comment by itsjustkevin** [comment]
I see my mistake @XilaiZhang projectsV2 requires use of the graphQL api.

I tested this out with the following:

```sh
gh api graphql -f query='
  mutation AddItemToProject($projectId: ID!, $contentId: ID!) {
    addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
      item {
        id
      }
    }
  }' -f projectId="PVT_kwDOANctEM4AUayz" -f contentId="PR_kwDOAeUeuM5s062f"
  ```
  
  This makes it a bit more difficult but still doable as we can not use the PR number directly, we need to extract its ID.

**Review by sortie — APPROVED** [review]
Without too deep technical knowledge here of github, what you're trying to do sounds good to me and the code looks right without careful knowledge

**Comment by itsjustkevin** [comment]
@XilaiZhang i tested extracting the PR ID in graphql explorer: https://docs.github.com/en/graphql/overview/explorer

let me look further into this a bit and determine the risk further.

**Comment by itsjustkevin** [comment]
@XilaiZhang round 2.

**Comment by XilaiZhang** [comment]
Thanks for the update Kevin!

> i tested extracting the PR ID in graphql explorer: https://docs.github.com/en/graphql/overview/explorer

This is great! But I would still strongly encourage testing this action end to end on a personal repository. I personally discovered most of my major loopholes / unexpected behaviors of Github while running full workflow simulations. 

For example, I wrote https://github.com/XilaiZhang/miscellaneous-side-project/blob/master/.github/workflows/token.yml tonight to test the logic on commenting on the previous PR. and you can observe the behaviors it has on https://github.com/XilaiZhang/miscellaneous-side-project/pull/9. The test workflow is https://github.com/XilaiZhang/miscellaneous-side-project/actions/runs/8732022766/job/23958348963 and you can see that it commented on the success steps I expected, and failed on the failure steps I expected.

If I have more time I would definitely help with writing a test workflow for the graph ql queris, but I don't have the cycles at the moment. If you are able to test the graph ql queries through a workflow simulation I am happy to approve it. For now, I am happy to approve the logic on commenting on original PR, but would prefer a real test simulation for the graph ql queries part. Thank you!

**Comment by XilaiZhang** [comment]
btw I think we can still land the part where we comment on the original PR (already fully tested), it would definitely help a lot with user experience like Kevin previous pointed out

**Pull request closed without merging**
