### PR TITLE
fix(material): add properties to RaisedButton

### LINKED ISSUE #40696: RaisedButton.icon should have padding argument
## Use case

`RaisedButton` already has a `padding` argument, but the named constructor `RaisedButton.icon()` does not.

As a result, it's not as easy to modify padding on a `RaisedButton.icon()`.

## Proposal

Configuration parity between `RaisedButton` and the named constructor `RaisedButton.icon()`.

### PR DESCRIPTION
**Pull request by cpboyd**
Adds `focusElevation`, `hoverElevation`, and `padding` to `RaisedButton.icon()`

## Description

Brings configuration parity to `RaisedButton.icon()` from the base `RaisedButton`.

## Related Issues

Fixes #40696.

## Tests

This doesn't change behavior, just adds additional configuration options for `RaisedButton.icon()`.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by HansMuller** [comment]
This PR will need tests.

**Comment by cpboyd** [comment]
@HansMuller What might you suggest?

There are not currently any tests for `RaisedButton()` for `padding`, `focusElevation`, or `hoverElevation`:
https://github.com/flutter/flutter/blob/b11c5acaa6200a8d662705a312a2e5fb7714fe2e/packages/flutter/test/material/raised_button_test.dart

These tests are, however, on the generic `MaterialButton()`:
https://github.com/flutter/flutter/blob/b11c5acaa6200a8d662705a312a2e5fb7714fe2e/packages/flutter/test/material/buttons_test.dart

**Comment by HansMuller** [comment]
You can test the padding parameter by verifying that the button's child appears where it's expected when padding is provided. Since RaisedButton et al are simple subclasses of MaterialButton and padding is essentially a pass-through parameter, it would be OK to write another MaterialButton test.

**Comment by shihaohong** [comment]
Hi @cpboyd are you planning on working on adding tests anytime soon? We could close this issue for now and re-open it when you plan on revisiting this PR.

**Comment by cpboyd** [comment]
@shihaohong I'm busy with non-Flutter projects at the moment.  I'll see about revisiting this later

**Pull request closed without merging**
