### PR TITLE
re-work the doctor command

### LINKED ISSUE #2132: Summary message at end of flutter doctor
It would be really cool if `flutter doctor` printed a simple GREEN / YELLOW / RED summary of the state of your project.

The output has a lot of stuff:

```
~/flutter/testme $ flutter doctor
Downloading Dart SDK 1.14.1...
######################################################################## 100.0%
Downloading Flutter engine 6e736e7a76600640c5bd854c2fc9ed0f664ee26e...
######################################################################## 100.0%
######################################################################## 100.0%
######################################################################## 100.0%
######################################################################## 100.0%
Building flutter tool...
Flutter root: /Users/sethladd/Code/flutter.

[✓] iOS toolchain - develop for iOS devices (installed)
  [✓] XCode - enable development for iOS devices (installed)
    [✓] version - Xcode minimum version of 7.2.0 (installed)
    [✓] EULA - XCode end user license agreement (installed)
  [✓] brew - install additional development packages (installed)
    [✓] ideviceinstaller - discover connected iOS devices (installed)
    [✓] ios-deploy - deploy to connected iOS devices (installed)

[✓] Android toolchain - develop for Android devices (installed)
  [✓] Android SDK - enable development for Android devices (installed)

[✓] Atom development environment - a lightweight development environment for Flutter (installed)
  [✓] Atom editor (installed)
  [✓] Flutter plugin - adds Flutter specific functionality to Atom (installed)

Flutter from git@github.com:flutter/flutter.git (on master)
flutter revision: 755a180af2ce521fb2646483e0e9200e8c1264dc (18 minutes ago)
engine revision : 6e736e7a76600640c5bd854c2fc9ed0f664ee26e
```

And to put a bow around it, at the very bottom, we could print:

```
[✓] All systems are a go. You are cleared to Flutter.
```

(bonus points if you make it green)

or

```
[X] Something doesn't check out. If the above diagnostics don't help resolve the issue, please file a bug when the full output of this command: https://github.com/flutter/flutter/issues/new
```

Without this summary output, it's not immediately clear if we're good to go. Also, it makes it easier to document, so we can say: "Look for this message to tell you if you are good to go, or not."

Thanks!

### PR DESCRIPTION
**Pull request by devoncarew**
Re-work the doctor command:
- it's easier to add arbitrary messages to the doctor output (they can show up as either errors or just messages)
- the presentation is flatter, instead of nested
- we can now show version info for installed components better

This should also do a better job of diagnosing why we couldn't run some android launches (missing some android sdk components).

```
[✓] Flutter (a8c03d6 on channel )
    • Flutter root at /Users/devoncarew/projects/flutter/flutter
    • Framework revision a8c03d6 (49 seconds ago)
    • Engine revision b7419de

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/devoncarew/tools/android-sdk-macosx
    • Platform android-23
    • Build-tools 23.0.2

[✓] iOS toolchain - enable development for iOS devices (Xcode 7.2.1)
    • Xcode 7.2.1, Build version 7C1002

[✓] Atom - a lightweight development environment for Flutter
    • Flutter plugin version 0.2.1
```

fix https://github.com/flutter/flutter/issues/2132

### CODE REVIEW

**Comment by abarth** [comment]
`(a8c03d6 on channel )`

Maybe should say "unknown" for the channel name instead of being incomplete?

**Comment by abarth** [comment]
`develop for Android devices` versus `enable development for iOS devices`

Should these be more parallel in grammar?

**Comment by devoncarew** [comment]
Updated to change the text and handle the case where there's no upstream branch:

```
[✓] Flutter (a8c03d6 - channel unknown)
    • Flutter root at /Users/devoncarew/projects/flutter/flutter
    • Framework revision a8c03d6 (2 hours ago)
    • Engine revision b7419de

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/devoncarew/tools/android-sdk-macosx
    • Platform android-23
    • Build-tools 23.0.2

[✓] iOS toolchain - develop for iOS devices (Xcode 7.2.1)
    • Xcode 7.2.1, Build version 7C1002
    • ideviceinstaller, ios-deploy installed

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; flutter plugin version 0.2.1
```

**Comment by abarth** [comment]
LGTM

**Pull request merged**
