### PR TITLE
Remove flutter gallery test family (Mac/ios) from prod pool

### PR DESCRIPTION
**Pull request by keyonghan**
The `flutter_gallery ... transition_perf` family has been flaky (https://github.com/flutter/flutter/issues/88296) and enabled in staging pool: https://flutter-review.googlesource.com/c/infra/+/17400.

Mac/ios ones are running through in staging, and this removes them from the prod pool to avoid affecting build dashboard.

### CODE REVIEW

**Comment by zanderso** [comment]
Can we get the email notification to the sheriff set up on failures in staging before we remove these from prod?

**Comment by keyonghan** [comment]
> Can we get the email notification to the sheriff set up on failures in staging, or a dashboard we can monitor, before we remove these from prod?

https://ci.chromium.org/p/flutter/g/devicelab_staging/console# is where we currently track devicelab_staging tests.

**Comment by zanderso** [comment]
@keyonghan Thanks for the link to the dashboard. Unfortunately, it has a lot of information, and mixes together the benchmarks we care about with other jobs that we are not monitoring, so I don't think I can ask the Engine Sheriff to monitor it.

**Comment by godofredoc** [comment]
> @keyonghan Thanks for the link to the dashboard. Unfortunately, it has a lot of information, and mixes together the benchmarks we care about with other jobs that we are not monitoring, so I don't think I can ask the Engine Sheriff to monitor it.

@keyonghan let's create a plan for treating benchmarks as non blockers but still as production builders. Meanwhile we can create a new console for them.

**Comment by keyonghan** [comment]
New benchmark console is ready: https://ci.chromium.org/p/flutter/g/devicelab_benchmark/console

**Review by godofredoc — APPROVED** [review]

**Pull request merged**
