### PR TITLE
Handle empty sizes in AppBar's toolbar layout

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by HansMuller** [comment]
How does size.width end up being zero? 

A regression test would be useful. If it's possible for size to be 0 x 0 we wouldn't want to introduce a new land mine.

**Comment by jason-simmons** [comment]
See https://github.com/flutter/flutter/issues/5259

**Comment by Hixie** [comment]
I would rather we only fix this if we actively write a test for every single widget to make sure they all work in 0x0 containers. If we just fix this particular manifestation we'll stop feeling the pain and so we'll stop trying to fix it for the rest of the widgets.

**Comment by abarth** [comment]
> write a test for every single widget

It's really only the custom layout widgets that are likely to have this sort of bug.  Maybe that should be something we do as a matter of routine for custom layout widgets...

**Comment by Hixie** [comment]
By "widget" I meant "UI control", not `Widget`, sorry for the ambiguity.

I think we should test things like check boxes, input fields, app bars, scaffold, etc.

**Comment by Hixie** [comment]
@jason-simmons Per our discussion, I'm going to close this PR for now; it's high on my list to do something about this after I'm done with scrolling. (If someone else wants to take it earlier that's fine too.)

**Comment by jason-simmons** [comment]
Added a test - PTAL

**Comment by Hixie** [comment]
I think you have to reopen the PR for it to show the updated diff

**Comment by jason-simmons** [comment]
Recreated this as https://github.com/flutter/flutter/pull/6894

**Pull request closed without merging**
