### PR TITLE
Improve example/hello_world README.md formatting

### LINKED ISSUE #47579: example/hello_world README.md formatting can be improved
The headings and code in the readme are not well organized and are not readable. Using the correct markdown syntax we can solve this issue.

### PR DESCRIPTION
**Pull request by adarshbalu**
Edited the readme and Made it more readable using headings better and making the code highlighted.

Fixes #47579

### CODE REVIEW

**Comment by adarshbalu** [comment]
@googlebot I signed it!

**Review by shihaohong — APPROVED** [review]
LGTM. You might have to rebase your branch against `master` since an analyzer test is failing unrelated to your change.

**Comment by shihaohong** [comment]
Hi! Any word on this?

**Comment by goderbauer** [comment]
I am going to close this since we didn't get any response. Feel free to re-open if you find the time to work on this again.

**Pull request closed without merging**
