### PR TITLE
reduce mac workload

### PR DESCRIPTION
**Pull request by dnfield**
We need to reduce the workload that the macs are doing at least temporarily.

/cc @tvolkert

### CODE REVIEW

**Comment by tvolkert** [comment]
So this:

* Makes the MacOS integration tests only run on master (not pre-commit)
* Skips running the widget tests on MacOS entirely -- presumably because they provide less value when compared to other tests we run on Macs?

What's the story with the removal of the "*_cache" lines?

**Comment by dnfield** [comment]
We run the widget tests on LUCI on post submit.

The caches turned out to be frequently taking longer to create/upload/download than if we just download directly AFAICT, at least on mac.  On Linux and Windows they seem better.

**Review by tvolkert — APPROVED** [review]

**Comment by dnfield** [comment]
Redness is not real - going ot land this to kick the bots.  Should also help us be less red for flakes.

**Comment by Hixie** [comment]
Filed https://github.com/flutter/flutter/issues/41940 to track this.

**Pull request merged**
