### PR TITLE
use RadioListTile in expansion panels demo

### LINKED ISSUE #6048: Expansion panels: Can't tap radio labels in Location
Open Gallery, open Expansion panels, open Location. Tap "Bahamas" or "Barbados".

Expected: the radio button changes selection when a label is tapped.

Actual: nothing happens.

Workaround: tap the radio button itself to change selection.

### PR DESCRIPTION
**Pull request by mockturtl**
Fixes #6048.

### CODE REVIEW

**Comment by Hixie** [comment]
This fix is good. Thanks for your contribution! Might make sense to add a test to make sure the original issue is gone too (i.e. tap the text, check the value changes). Would you mind doing that?

**Comment by mockturtl** [comment]
An [existing](https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/control_list_tile_test.dart#L37) `RadioListTile` test verifies that `onChanged` is called by both a label and a radio tap.  I added a test to  verify the new selection after a rebuild.

My logic for getting `find` to match a `Radio<_T>` feels awkward.  Do you see a less clunky approach?

**Comment by jslavitz** [comment]
@Hixie  Anything else needed to get this one through?

**Comment by mockturtl** [comment]
@jslavitz @Hixie Is there anything I can do to help besides keeping the changes up to date with `master`?

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
