### PR TITLE
Update MergeableMaterial's default color to CardTheme.color

### LINKED ISSUE #63398: MergeableMaterial completely ignores CardTheme.color
## Steps to Reproduce

1. Create a new Flutter application.
2. Replace the code in `main.dart` with the given below

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        cardTheme: CardTheme(
          color: Colors.red
        ),
        cardColor: Colors.green,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Flutter Demo'),
        ),
        body: SingleChildScrollView(
          child: MergeableMaterial(
            children: <MergeableMaterialItem>[
              MaterialSlice(
                key: ValueKey<String>('A'),
                child: SizedBox(
                  width: 100.0,
                  height: 100.0,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
3. Run the application

**Expected results:** 
The color of the `MaterialSlice` should be red but it's green. It completely ignores the `CardTheme.color` and uses `ThemeData.cardColor`, whereas the first priority should have been given to `CardTheme.color`. Have a look here
https://github.com/flutter/flutter/blob/7c6f9dd2396dfe7deb6fd11edc12c10786490083/packages/flutter/lib/src/material/mergeable_material.dart#L542
https://github.com/flutter/flutter/blob/7c6f9dd2396dfe7deb6fd11edc12c10786490083/packages/flutter/lib/src/material/mergeable_material.dart#L614
**Actual results:** 
The color of `MaterialSlice` is green.

actual_result_image

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-8.0.pre.98, on Microsoft Windows [Version 10.0.18363.959], locale en-IN)
    • Flutter version 1.21.0-8.0.pre.98 at C:\flutter
    • Framework revision 77b4505c80 (4 days ago), 2020-08-06 18:51:02 -0700
    • Engine revision cd3ea1e839
    • Dart version 2.10.0 (build 2.10.0-3.0.dev fcafd43f2c)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\SDK
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30330.147
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\Ayush Bherwani\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (5 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.18363.959]
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 84.0.4147.105
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 84.0.522.52

• No issues found!
```
</details>

### PR DESCRIPTION
**Pull request by JuYeong0413**
## Description

Currently the `CardTheme.color` is ignored and `ThemeData.cardColor` is used in `MergeableMaterial`.
This pull request updates `MergeableMaterial`'s default color to `CardTheme.color`.
<details>

  <summary>Reproducible code sample</summary>

  ```dart
  import 'package:flutter/material.dart';

  void main() => runApp(MyApp());

  class MyApp extends StatelessWidget {

    @override
    Widget build(BuildContext context) {
      return MaterialApp(
        theme: ThemeData(
          cardTheme: CardTheme(
            color: Colors.red
          ),
          cardColor: Colors.green,
        ),
        home: Scaffold(
          appBar: AppBar(
            title: Text('Flutter Demo'),
          ),
          body: SingleChildScrollView(
            child: MergeableMaterial(
              children: <MergeableMaterialItem>[
                MaterialSlice(
                  key: ValueKey<String>('A'),
                  child: SizedBox(
                    width: 100.0,
                    height: 100.0,
                  ),
                ),
              ],
            ),
          ),
        ),
      );
    }
  }
  ```

</details>

| Before (`ThemeData.cardColor` is used as default) | After (`CardTheme.color` is used as default) | After (When `CardTheme.color` is not specified |
|---|---|---|
|  |  | 

## Related Issues

Fixes https://github.com/flutter/flutter/issues/63398

## Tests

I added the following tests:

- `mergeable_material_test.dart`
Added a test to verify that the color of `MaterialSlice` is applied by `CardTheme.color`. 

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change.
   - [ ] I wrote a design doc: 

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by AyushBherwani1998** [comment]
Hey, @JuYeong0413 thank you for your contribution. This will be a breaking change and will require a breaking change proposal for the migration. Since the default color of MergableMaterial is changed it creates unexpected color changes in the existing apps. Note: MergableMaterial is also the building block for the ExpansionPanelList, so this change will also affect it.

**Comment by JuYeong0413** [comment]
Thank you @AyushBherwani1998, I'll write a design doc for it ASAP.
I didn't notice that `MergableMaterial` is also the building block for `ExpansionPanelList` - should I add test for `ExpansionPanelList` too?

**Comment by AyushBherwani1998** [comment]
Actually, @shihaohong and I have already made progress for the design doc.

The breaking change will involve 2-3 steps. One will be fixing internal google test failures if any.

If you are willing to contribute, you can hop in the second step which will be to remove the flag and making the `CardTheme.color` default without using a flag.

**Comment by JuYeong0413** [comment]
I see. Then I'll remove the flag and make `CardTheme.color` as default. Thanks a lot!

**Comment by AyushBherwani1998** [comment]
Sorry if it created any confusion, I didn't mean that. 

You can go through the [design doc](https://docs.google.com/document/d/1ZPPADYZuTPfsKiYNenz0ZnEyFHZo7mhE9sFNUGoNP_g/edit?usp=sharing). Once we have completed the first step of migration, you can hop in for the third step and contribute. We still need to work on the design doc and make a PR for the first step.

**Comment by JuYeong0413** [comment]
Ahh, sorry for misunderstanding.

I would happy to contribute, but I'm little bit afraid that involving myself would slow down the progress for this change since I'm not very familiar with breaking changes. There are many ways to contribute to flutter, so maybe it would be better to close this PR and work on another issue :-) Thank you for your comments!

**Pull request closed without merging**
