### PR TITLE
Check for CocoaPods installation if required

### PR DESCRIPTION
**Pull request by cbracken**

### CODE REVIEW

**Comment by cbracken** [comment]
Fixes #8657

**Comment by cbracken** [comment]
@chinmaygarde

**Review by collinjackson — APPROVED** [review]
Are we want to make installing CocoaPods a required step in running the default Flutter template project? If so, this change lgtm. If not, we might want to emit a warning (developer will hit a compile error later on when they try to use the pods they've added) instead of requiring CocoaPods if a Podfile is present.

**Comment by eseidelGoogle** [comment]
This is great.  I think we should do something more general over time.  Make commands declare their dependencies so we can check them up front, or something.  Donno.  We have the capacity to check for all these various dependencies through Flutter Doctor code, seems like we could/should use that before running (and then letting fail) various commands.  Nicer to learn that you don't have pods before we start trying to run anything for example. :)

**Review by collinjackson — APPROVED** [review]

**Comment by cbracken** [comment]
@collinjackson migrated to a warning (which effectively gives us the old behaviour if you don't have CocoaPods installed).

@eseidelGoogle Agreed. Independent of this short-term fix. Right now the doctor validations are pretty monolithic. The right solution feels like breaking out something like a `Tool` class representing a tool we depend on with independent validation, error/warning message, and invocation. Doctor would provide the global overview of the state of everything we depend on, and we could avoid littering the code with these checks.

**Pull request merged**
