### PR TITLE
Extending fillOverscroll Feature for SliverFillRemaining

### LINKED ISSUE #44353: SliverFillRemaining does not fill overscroll even with fillOverscroll option
https://gist.github.com/radroot1/20e9ddb183f638c83258fadf92dfb093
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
[✓] VS Code (version 1.35.1)
[✓] Connected device (2 available)

overscroll1

It was normal in previous version of flutter. I do not remember which, but in the gist I attached code of SliverFillRemaining that worked

### PR DESCRIPTION
**Pull request by Piinks**
## Description

This PR extends the fillOverscroll feature of SliverFillRemaining to enable solely filling the overscroll area, rather than also having a child in the natural un-overscrolled  scroll view. 

This use case applies when SliverFillRemaining's child has no size and the precedingScrollExtent has gone beyond the size of the viewportMainAxisExtent. Prior to this change, this would result in nothing being drawn by SliverFillRemaining. Now it will draw into the overscroll area as it appears. :)

***
~Note:~
~This PR contains changes from #44471, which should land first.~
~I branched from there to prevent a self-inflicted merge conflict. :)~
***

## Related Issues

Fixes #44353 

## Tests

- fillOverscroll works when child has no size and precedingScrollExtent > viewportMainAxisExtent

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Piinks** [comment]
Blocked by #44471

**Comment by Piinks** [comment]
No longer blocked. :)

**Comment by Piinks** [comment]
@goderbauer I would like to land this to close the related issue before the refactoring we have discussed offline. Would you be willing to take a look?

**Review by goderbauer — COMMENTED** [review]
Before we make this widget more complicated, can we split it up into multiple objects? That would make it easier to review this and reason about this.

**Comment by Piinks** [comment]
> Before we make this widget more complicated, can we split it up into multiple objects? That would make it easier to review this and reason about this.

Ok. I will see about addressing the issue when it is re-factored.

**Pull request closed without merging**
