### PR TITLE
[flutter_tools] Federate plugin template, and add web support.

### PR DESCRIPTION
**Pull request by ditman**
## Description

* Migrate the example plugin to be instance-based instead of all static. Update usages.
* Federate the sample plugin so web can be implemented:
  * Separate platform interface from implementations.
  * Core plugin uses *only* platform.
  * Web may override implementation of said platform. 
  * Defaults to MethodChannel version.
* Add web implementation of the plugin (when requested)
* Add test.

## Related Issues

* https://github.com/flutter/flutter/issues/59562

## Tests

I added the following tests:

`flutter_tools/test/commands.shard/permeable/create_test.dart`:
* `plugin project supports web`
* Asserted `lib/src/flutter_project_web.dart` is not created by default. 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by cyanglaz** [comment]
cc @jonahwilliams The web template is currently missing. So we can't really do `flutter add-platform --platform web` yet. This PR is to add the template.

**Review by cyanglaz — COMMENTED** [review]
I'm still thinking it could be a problem if user has a plugin already then trying to add web.
Is there a way to make web template independent ? Maybe we only add the `plugin_web.dart` and add some instruction text in this `plugin_web.dart` on how to structure a web only plugin or a plugin contains web and other platforms. Possibly a link to a flutter.dev page.
This way to don't change the behavior of the command for other platforms. Then we can gradually fix the web in the future? WDYT?

**Comment by jonahwilliams** [comment]
We can add a web template with the existing design, but you can't change the existing template like this since it will need to work with add-platform.

Modifications would have to be in a  plugin_2 - an entirely separate template

**Comment by ditman** [comment]
"it will need to work with add-platform"

What needs to happen for that to be true? How do I test "add-platform"?

**Comment by jonahwilliams** [comment]
It looks like you're modifying the main platform file here: https://github.com/flutter/flutter/pull/59700/files#diff-7e8eece56f751946af82080aaa3d26a9 , right?

**Comment by ditman** [comment]
> It looks like you're modifying the main platform file here: https://github.com/flutter/flutter/pull/59700/files#diff-7e8eece56f751946af82080aaa3d26a9 , right?

@jonahwilliams Yes, I guess this is not backwards compatible with plugins generated *before* this change.

**Comment by ditman** [comment]
I've redone this here, in a way that should be backwards compatible:

https://github.com/flutter/flutter/pull/60116

**Pull request closed without merging**
