### PR TITLE
Mark hot_mode_dev_cycle_linux__benchmark flaky to unblock tree

### PR DESCRIPTION
**Pull request by keyonghan**
https://github.com/flutter/flutter/issues/87512

### CODE REVIEW

**Review by jmagman — COMMENTED** [review]
Will this actually work around https://github.com/flutter/flutter/issues/87512, or does it need to be completely removed?

**Review by jmagman — APPROVED** [review]
LGTM assuming this actually works around the ref missing.

**Comment by keyonghan** [comment]
> Will this actually work around #87512, or does it need to be completely removed?

It will workaround. Current status is based on only unflaky tests results.

**Comment by keyonghan** [comment]
Manually merge to unblock the github PR status.

**Pull request merged**
