### PR TITLE
Remove `ImageProvider.load`, `DecoderCallback` and `PaintingBinding.instantiateImageCodec`

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
~The failing plugin tests should pass once https://github.com/flutter/packages/pull/4725 lands and rolls into flutter/flutter~

google tests are migrated.

Part of https://github.com/flutter/flutter/issues/133171

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Piinks** [comment]
This is pending https://github.com/flutter/packages/pull/4725 and then pending the announcement we're removing these. :+1:

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

This has been announced now in https://github.com/flutter/flutter/issues/133171

**Comment by LongCatIsLooong** [comment]
This PR has a clean TGP run but the google testing CL keeps getting deleted. Manually submitting.

**Comment by flar** [comment]
This PR seems to have caused a large regression in the time to first frame for the complex_layout benchmark:

https://flutter-flutter-perf.skia.org/e/?begin=1691652204&end=1693090952&keys=Xa2f4f2d78d99c6375b9bdf0744384fad&requestType=0&selected=commit%3D36471%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253Dnone%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253DtimeToFirstFrameRasterizedMicros%252Ctest%253Dcomplex_layout_macos__start_up%252C&xbaroffset=36471

**Pull request merged**
