### PR TITLE
Using `initExpensiveAndroidView` for Android Hybrid Composition Mode

### PR DESCRIPTION
**Pull request by 0xZOne**
After https://github.com/flutter/flutter/pull/100990, we should use `initExpensiveAndroidView` for Android Hybrid Composition mode instead of `initSurfaceAndroidView`. 

`initSurfaceAndroidView` attempts to use `TLHC` when possible. In cases where that is not supported, it falls back to using Hybrid Composition.

https://github.com/flutter/engine/pull/49414

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by stuartmorgan-g — APPROVED** [review]
LGTM

**Comment by johnmccutchan** [comment]
In the future please include someone from the Flutter Android team on PRs like this.

**Comment by zanderso** [comment]
SkiaPerf recorded a large regression on this PR in `frame_request_pending_latency`.

https://flutter-flutter-perf.skia.org/e/?begin=1704420532&end=1706757785&keys=X4889c5767836b8864765712c15d613c2&requestType=0&selected=commit%3D39066%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_frame_request_pending_latency%252Ctest%253Dandroid_view_scroll_perf__timeline_summary%252C&xbaroffset=39000

**Comment by johnmccutchan** [comment]
@zanderso Based on the benchmark name this benchmark is *supposed* to be testing the hybrid composition path. It was testing the TLHC path before this PR.

Not sure what we want to do. This change invalidates historical data as it is now measuring something completely different. I do think this change brings the benchmark in line with what it claims to be measuring.

WDYT?

**Comment by johnmccutchan** [comment]
@zanderso I sent a revert PR your way, feel free to submit it.

**Comment by stuartmorgan** [comment]
> Not sure what we want to do. This change invalidates historical data as it is now measuring something completely different. I do think this change brings the benchmark in line with what it claims to be measuring

I don't think we should revert this. I approved the PR because the benchmark had clearly become incorrect when Emmanuel changed what this function did and added a new, different way of getting the old behavior (HC). The benchmark clearly should have been changed at that time, but wasn't, and has therefore been wrong for quite some time.

**Comment by johnmccutchan** [comment]
@zanderso Given we've decided to keep this change, how do we reset the benchmark history?

**Pull request merged**
