### PR TITLE
Revert "Improve tracing"

### PR DESCRIPTION
**Pull request by Hixie**
Reverts flutter/flutter#93086, which broke some CI for some reason even though it passed presubmit.

### CODE REVIEW

**Comment by CaseyHillers** [comment]
I recommend waiting for the latest runs to finish. The ci.yaml takes 1-2 commits to propagate to LUCI.

**Comment by CaseyHillers** [comment]
For example, https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests_misc/3024/overview is from the commit after yours, and it's passing now with your changes

**Comment by Hixie** [comment]
Oh, that's weird. We shouldn't run tests if we know they'll fail. Can the scheduler delay the tests until things are ready? I'll file a bug.

**Comment by CaseyHillers** [comment]
This will get fixed when https://github.com/flutter/flutter/issues/81795 is implemented, and the ci.yaml is scheduled from Cocoon in postsubmit instead of using the luci scheduler.

**Review by CaseyHillers — APPROVED** [review]

**Pull request closed without merging**
