### PR TITLE
Update link branches to `main`

### PR DESCRIPTION
**Pull request by guidezpl**
- Update CS and googlesource.com link branches
- Update GitHub /blob/ and /tree/ links

Tested links manually and fixes a few broken or deprecated links

Added a test that validates that `master` isn't used, except for specified repos.

Part of https://github.com/flutter/flutter/issues/121564

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM. I didn't test every link but I spot checked a random sample.

**Review by Hixie — APPROVED** [review]

**Comment by Hixie** [comment]
Would be nice to have a test that checks that we don't have any files with `/master/` links, otherwise we'll definitely regress this.

**Comment by TahaTesser** [comment]
@guidezpl 
It seems this is breaking the tree.

image

```dart
▌01:31:33▐ Links to GitHub...
╔═╡ERROR #1╞════════════════════════════════════════════════════════════════════
║ /b/s/w/ir/x/w/flutter/dev/bots/analyze.dart contains https://github.com/flutter/flutter/blob/master/dev/tools/gen_defaults, which uses the banned "master" branch.
║ /b/s/w/ir/x/w/flutter/dev/bots/test/analyze_test.dart contains https://github.com/flutter/flutter/blob/master/dev/tools/gen_defaults, which uses the banned "master" branch.
║ Change the URLs above to the expected pattern by using the "main" branch if it exists, otherwise adding the repository to the list of exceptions in analyze.dart.
```

**Comment by guidezpl** [comment]
Oh interesting, let's revert https://github.com/flutter/flutter/pull/146880

**Pull request merged**
