### PR TITLE
[devicelab] remove 32bit test that has not passed recently

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

As far as I can tell, this test has never passed. nevertheless, it is increasing resource usage on a device that we only have one of.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
@liyuqian , @jmagman has brought up that these tests have caught bugs in the past so we should consider not removing them. I cannot tell when the last time they passed was though.

If these are important please fix them, if not LMK and I will remove them

**Comment by liyuqian** [comment]
It was passing on https://github.com/flutter/flutter/commit/6cd847c767f5a49616cd5c6ae04e12d752e906b3 and it passed 8 out of 10 times in the 10 previous commits before it.

**Comment by jonahwilliams** [comment]
That is true, I will update the title of this PR.

Nevertheless, even 8/10 is still incredibly flaky. Are you currently working on de-flaking this test?

**Comment by liyuqian** [comment]
Yes, the flakiness issue is tracked by #67753, and Jenn is working on it #69260.

**Comment by jonahwilliams** [comment]
That is not the source of all of the flakes unfortunately, there are additional failures where it seems like the VM Service URI is never discovered

**Comment by liyuqian** [comment]
@jonahwilliams : can you please share a link or a commit SHA to that failure log? I'll take a look and investigate.

**Comment by jonahwilliams** [comment]
Lets give @jmagman 's change another day or so to bake and see what the status is

**Pull request closed without merging**
