### PR TITLE
Add `minTileHeight` to ListTileTheme

### PR DESCRIPTION
**Pull request by AhmedLSayed9**
`minTileHeight` was added by https://github.com/flutter/flutter/pull/145244 to ListTile widget so its height can be customized to less than the default height.

This PR supports setting `minTileHeight` at the [ListTileTheme](https://api.flutter.dev/flutter/material/ListTileTheme-class.html) too.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by nate-thegrate — COMMENTED** [review]
Just a heads-up: `minTileHeight` has already been added to the ListTile theme data.

https://github.com/flutter/flutter/blob/d8ae99a790d2bcce7c080e1839634bef1422de9d/packages/flutter/lib/src/material/list_tile_theme.dart#L123-L124

<br>

[The previous PR](https://github.com/flutter/flutter/pull/145244) added this property to [`ListTileThemeData`](https://main-api.flutter.dev/flutter/material/ListTileThemeData/minTileHeight.html) without adding an obsolete property to [`ListTileTheme`](https://main-api.flutter.dev/flutter/material/ListTileTheme-class.html).

**Comment by Piinks** [comment]
This might be covered by https://github.com/flutter/flutter/issues/91772 where we are normalizing component themes to use *ThemeData, and I think @nate-thegrate has already pointed out this is included there.

**Comment by QuncCccccc** [comment]
Hello! The `minTileHeight` has been added to ListTileTHemeData. Using 

```
ListTileTheme(
  data: ListTileThemeData(
    minTileHeight: xxx
  )
)
```
would be encouraged since this pattern follows Flutter widget theme convention:)

**Comment by AhmedLSayed9** [comment]
> Hello! The `minTileHeight` has been added to ListTileTHemeData. Using
> 
> ```
> ListTileTheme(
>   data: ListTileThemeData(
>     minTileHeight: xxx
>   )
> )
> ```
> 
> would be encouraged since this pattern follows Flutter widget theme convention:)

I see. This PR just adds an obsolete property to [ListTileTheme](https://main-api.flutter.dev/flutter/material/ListTileTheme-class.html) that can be used directly. I guess this is no longer needed for new properties :)

**Comment by QuncCccccc** [comment]
We should not use these properties in ListTileTheme directly and the existing properties, except `ListTileTheme.data`, would be deprecated in the future. Would you mind if we close this PR for now:)? And you are right, if we have new theme properties to customize `ListTile`, we should add the new ones to `ListTileThemeData` instead of `ListTileTheme`.

**Pull request closed without merging**
