### PR TITLE
Will pop scope on home route

### LINKED ISSUE #151432: WillPopScope.onWillPop not called on home route when using FlutterFragment
### Steps to reproduce

1. Run the code sample, or any app with a WillPopScope that returns `false` on the home route, on Android.
2. Perform a system back (either swipe back or physical back button).

### Expected results

[WillPopScope.onWillPop](https://main-api.flutter.dev/flutter/widgets/WillPopScope/onWillPop.html) is called and the back is unsuccessful because it returns `false`.

### Actual results

WillPopScope.onWillPop is not called and the back succeeds in exiting the app.

This is caused by https://github.com/flutter/engine/pull/52302.

### Workaround
Upgrade to [PopScope](https://main-api.flutter.dev/flutter/widgets/PopScope-class.html). Since WillPopScope is deprecated, fixing this is likely to be low priority.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: WillPopScope(
        onWillPop: () {
          return Future.value(false);
        },
        child: const Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text('Press the system back button. The app should exit, but it dont.'),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

_No response_

### Logs

_No response_

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel master, 3.24.0-1.0.pre.48, on macOS 14.5 23F79 darwin-arm64, locale en)
    ! Upstream repository git@github.com:justinmc/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:justinmc/flutter.git to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] Android Studio (version 2023.2)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for Bella’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

b/344690680

### PR DESCRIPTION
**Pull request by justinmc**
In the transition to PopScope, WillPopScope.onWillPop was broken when used on a root route. This PR fixes it by disabling predictive back whenever a WillPopScope is in the widget tree. It's not possible for WillPopScope to work with predictive back, so I think it's fair to disable it. Better to turn off predictive back than to quietly break WillPopScope.

Anyone that wants predictive back support should migrate to PopScope.

Fixes https://github.com/flutter/flutter/issues/151432

### CODE REVIEW

**Review by reidbaker — APPROVED** [review]
Can you please add to the documentation here https://docs.flutter.dev/release/breaking-changes/android-predictive-back 
To let users know that widgets can impact if predictive back is enabled? This pr feels like an improvement but one that would be confusing to debug if you were getting unexpected behavior.

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by justinmc** [comment]
Website update PR: https://github.com/flutter/website/pull/10928

**Comment by justinmc** [comment]
And we should probably mention this here too: https://github.com/flutter/flutter/pull/152116 @reidbaker

**Pull request merged**
