### PR TITLE
revert some type args added in https://github.com/flutter/flutter/pull/18575

### LINKED ISSUE #18609: Dart roll @optionalTypeArgs regression
This roll https://github.com/flutter/flutter/pull/18575 required that types be specified in more places, despite the `@optionalTypeArgs` annotations. This is a regression that means our documentation is now less clear than before.

### PR DESCRIPTION
**Pull request by devoncarew**
Speculative revert of some type args added in https://github.com/flutter/flutter/pull/18575; fix https://github.com/flutter/flutter/issues/18609.

### CODE REVIEW

**Comment by devoncarew** [comment]
Hmm, the bots seem happy.

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
Huh.  Really don't know what could have caused the problem I saw.  I was confused by it then too, since it only affected the sample code check: the regular code didn't have a problem with the optional types.  In any case, I'm glad we can revert these.

**Comment by devoncarew** [comment]
Yeah, I did a tiny bit of poking around to see what the issue might have been, but didn't see anything obvious (like the sample analysis script possibly having old state on disk).

**Comment by devoncarew** [comment]
The Flutter bots look broken due to:

```
Error: An unexpected error has occurred.
Error: Unable to deploy documentation to firebase. Retrying in five seconds...
⚠  Your CLI authentication needs to be updated to take advantage of new features.
⚠  Please run firebase login --reauth
```

on the docs bot.

**Pull request merged**
