### PR TITLE
Adapt to vm isolate and isolate snapshot pieces being emitted as asse…

### PR DESCRIPTION
**Pull request by rmacnak-google**
…mbly.

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]
lgtm

**Comment by tvolkert** [comment]
So with this change, we pass the following flags to `flutter build aot --release --target-platform=ios`

```
--vm_isolate_snapshot=build/aot/snapshot_aot_vmisolate
--isolate_snapshot=build/aot/snapshot_aot_isolate
```

Yet those snapshot files aren't generated.  Is this intentional?  It seems weird to pass flags that get dropped on the floor.  Does this behavior get triggered because we also pass `--assembly=build/aot/snapshot_assembly.S`?  Or because it's a different gen_snapshot binary that's been built for iOS?  Either way, it seems like we should fail if the flags are passed and we don't support them (then update tools to not pass the flags when they're not supported)...

It's also weird that in debug mode, our app.dylib is being created without actually linking anything anymore...

@rmacnak-google let's chat tomorrow - I guess I need more context on what changed and how stuff works now.

**Comment by tvolkert** [comment]
Funny enough, if you try calling gen_snapshot without the `--vm_isolate_snapshot` flag, it fails with:

```
No vm isolate snapshot output file specified.
```

... even though it's ignored when you do pass it.

**Comment by rmacnak-google** [comment]
They are generated; they're included in the .S now instead of being emitted as separate files.

**Comment by tvolkert** [comment]
Ok, verified that this change causes iOS debug builds to crash, because they're lacking the snapshots required for DBC.

**Pull request merged**
