### PR TITLE
Revert "Roll engine 9a17d8e45197..101e03c1c841 (4 commits)"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#39534

This is breaking the docs shard, see https://cirrus-ci.com/task/4755278756577280

The dart:wasm library was not added to the sky_engine rule, so the local dart sdk sources are in an inconsistent state (see https://github.com/flutter/engine/commit/74a3c73e3c77dc1fcddd98cf216d187ea830faf2)

### CODE REVIEW

**Comment by jonahwilliams** [comment]
TBR @dnfield  @tvolkert

**Comment by dnfield** [comment]
LGTM.

@a-siva has dart added a new core lib for wasm?

**Comment by jonahwilliams** [comment]
The fix is pending here: https://github.com/flutter/engine/pull/11736

It was not added to the sky_engine rule, so dartdocs crashes trying to create docs for it

**Comment by tvolkert** [comment]
LGTM

**Pull request merged**
