### PR TITLE
[flutter tools] Add Logger.dispose()

### PR DESCRIPTION
**Pull request by jamesderlin**
[flutter tools] Add  Logger.dispose()

I would like to override the default `Logger` in google3 with an
implementation that logs all output to a file.  I'd prefer not to use
`File.writeAsStringSync` to avoid opening and closing the log file on
every write.  For correctness, however, if we keep an open file handle
around, we should close it too.

Add a `.dispose()` method to the `Logger` interface and call it in a few
key places before calling `exit()`.

## Tests

None.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jonahwilliams** [comment]
I'm not quite sure how the google3 logger you're implementing will work, but instead of using an IOSink, you could use `writeAsStringSync` with `FileMode.append` (https://api.dart.dev/stable/2.8.3/dart-io/FileMode-class.html)

**Comment by jamesderlin** [comment]
> I'm not quite sure how the google3 logger you're implementing will work, but instead of using an IOSink, you could use `writeAsStringSync` with `FileMode.append` (https://api.dart.dev/stable/2.8.3/dart-io/FileMode-class.html)

I don't quite like `writeAsStringSync` since that would open and close the file for every write.  However, 
I not previously realize that `RandomAccessFile` (obtained from `File.open`/`File.openSync`) provides synchronous I/O functions. I definitely like that much better than using `IOSink`.  I'd still like to have a `Logger.dispose` method to properly close the `RandomAccessFile` though.

**Comment by jamesderlin** [comment]
Alternatively, I could replace this a more generic callback to fire before exiting.

**Review by jonahwilliams — COMMENTED** [review]
Addition of a dispose api LGTM. I'm not sure about the best way to test this, but @zanderso probably has some ideas

**Comment by zanderso** [comment]
Before taking a look, does piping the stdout/stderr of the tool to a file not work?

**Comment by jamesderlin** [comment]
> Before taking a look, does piping the stdout/stderr of the tool to a file not work?

It won't be the same thing.  What will be written to the log file will be much noisier than what will printed to stdout/stderr. (The log file will always include verbose output and will timestamp everything.)

**Comment by zanderso** [comment]
Okay, so the goal is to have an interactive session without verbose output on stdout/stderr during which the verbose logging is also sent to a file. Is something like that correct?

**Comment by zanderso** [comment]
As for the PR, I'd prefer an approach where the cleanup is encapsulated a bit more. See the cleanup for `LocalFileSystem` here:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/file_system.dart#L157

The patter for testing that I think would also be useful:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/base/file_system_test.dart#L131

**Comment by jamesderlin** [comment]
> Okay, so the goal is to have an interactive session without verbose output on stdout/stderr during which the verbose logging is also sent to a file. Is something like that correct?

Right.

> As for the PR, I'd prefer an approach where the cleanup is encapsulated a bit more. See the cleanup for `LocalFileSystem` here:

I'll try that.  Thanks!

**Comment by jamesderlin** [comment]
@zanderso Do you like this better?

I added a `Logger.registerForDisposal` method that needs to be called from `runner.dart`.  That work can't be done automatically by the `Logger` constructor since it depends on `ShutdownHooks`, and `ShutdownHooks` depends on `Logger`.

One aspect I dislike is that I think `Logger` should be special and should be disposed off as late as possible, and there's no way to control callback ordering for `ShutdownHooks` and `Signals`. (`ShutdownHooks` callbacks also arguably should executed in a LIFO order instead of FIFO.)

**Comment by zanderso** [comment]
Thinking about this PR a bit more. I'm wondering if we shouldn't try to make the verbose log file a feature of the core tool rather than a g3-only feature. I think that would be advantageous for @jamesderlin as well since the feature would be tested on pre-submit and we'd be less likely to break rolls. @jonahwilliams wdyt?

**Comment by jamesderlin** [comment]
> Thinking about this PR a bit more. I'm wondering if we shouldn't try to make the verbose log file a feature of the core tool rather than a g3-only feature. I think that would be advantageous for @jamesderlin as well since the feature would be tested on pre-submit and we'd be less likely to break rolls. @jonahwilliams wdyt?

It definitely crossed my mind that logging to a file would be generally useful.  What I had planned was to let it bake in google3 for a while before trying to push it upstream.

**Comment by zanderso** [comment]
> > I'm wondering if we shouldn't try to make the verbose log file a feature of the core tool
> 
> It definitely crossed my mind that logging to a file would be generally useful. What I had planned was to let it bake in google3 for a while before trying to push it upstream.

Ah, okay. Glad to hear you were already thinking about that =) Two things:
* We get more test coverage earlier by working on and landing things in github first. Test coverage on subsequent commits also happens pre-submit on all subsequent PRs. Post-submit, additional test coverage comes from FRoB, and the device lab. The tl;dr is that any baking that needs to happen will happen more effectively in github.
* Since Flutter and Flutter development is open source, we should be preferring to develop new, generally useful features in the open source repo.

**Comment by jamesderlin** [comment]
>     * We get more test coverage earlier by working on and landing things in github first. Test coverage on subsequent commits also happens pre-submit on all subsequent PRs. Post-submit, additional test coverage comes from FRoB, and the device lab. The tl;dr is that any baking that needs to happen will happen more effectively in github.
> 
>     * Since Flutter and Flutter development is open source, we should be preferring to develop new, generally useful features in the open source repo.

In this case I'd still prefer to trial it in google3 first to get a better sense of usage, performance impact, or other deficiencies.  The points you noted definitely would be motivation to get it upstream as quickly as possible, though.

**Comment by jamesderlin** [comment]
This change got significantly more complicated than I initially intended.  Relying on `shutdownHooks` means that I can do this entirely in google3, so I'll just do that.

**Pull request closed without merging**
