### PR TITLE
Fall-back to platform tools in Android SDK detection logic.

### LINKED ISSUE #28741: Licenses check in tools produces cryptic error message
If Android license check fails, users see:

```
Unable to locate the Android SDK; please run 'flutter doctor'.
No application found for TargetPlatform.android_arm64.
Is your project missing an android/AndroidManifest.xml?
Consider running "flutter create ." to create one.
```

None of these directions are applicable. They should be running `<ANDROID_HOME>/tools/bin/sdkmanager --licenses`.

Let's fix this messaging.

### PR DESCRIPTION
**Pull request by dnfield**
## Description

The Android SDK detection logic should still work if a user doesn't have licenses accepted but does have platform tools.  We have too many other codepaths that assume this can work and users end up with confusing messages.

@mehmetf - can you help me verify that this makes things better for our internal customers?  If it does, I'll write some tests, but I haven't been able to fully reproduce the issues I've seen reported.

## Related issues

Fixes https://github.com/flutter/flutter/issues/28741

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
I'm pretty confident at this point that this is the right fix.  I've added a test.  If we still see issues around this from Googlers we can revisit.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Landing on red to kick build

**Pull request merged**
