### PR TITLE
Allow a Nexus 6 and 6P to install Gallery

### LINKED ISSUE #6037: Gallery not installable via play.google.com on a Nexus 6P
Just tested, and received a report, that the Gallery isn't installable via play.google.com on a Nexus 6P.

Looks like our attempt to disallow tablets also accidentally caught phablets: https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/android/AndroidManifest.xml#L12

### PR DESCRIPTION
**Pull request by sethladd**
Closes https://github.com/flutter/flutter/issues/6037

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by sethladd** [comment]
thanks. I'm afraid this is a losing game :( Once we have landscape widgets, we can stop chasing this list :)

**Comment by abarth** [comment]
It might be less work just to implement the missing landscape features.  Folks are going to need them anyway.  Is there a label for the relevant issues in the tracker?

**Comment by eseidelGoogle** [comment]
@abarth https://github.com/flutter/flutter/labels/affects%3A%20landscape is some landscape issues.  It's unlikely to be a very fleshed out list since we haven't stared at it much.

**Pull request merged**
