### PR TITLE
Fix _DatePickerDialog for landscape orientation [small change]

### PR DESCRIPTION
**Pull request by FrantisekGazo**
## Description

This is a small change.

The date picker was stretched vertically when in landscape and on larger screens it didn't look good. Now it wraps it's height to min.

**BEFORE:**
 

**AFTER:**
 

Example code:
```dart

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Date Picker Demo'),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.date_range),
        onPressed: () => _showPicker(context),
      ),
    );
  }

  void _showPicker(BuildContext context) {
    final now = DateTime.now();
    showDatePicker(
      context: context,
      initialDate: now,
      firstDate: now,
      lastDate: now.add(Duration(days: 100)),
    );
  }
}
```

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

### CODE REVIEW

**Comment by FrantisekGazo** [comment]
@Hixie this ^ doesn't need tests, or does it?

**Comment by Piinks** [comment]
HI @FrantisekGazo, welcome! 🎉 
This will definitely need tests, but it also seems like this is causing existing tests to fail. Can you take a look at the failing tests?

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by darrenaustin** [comment]
Indeed welcome @FrantisekGazo! Thanks for your fix. However, we are completely updating the UI for the Date Picker to match the latest Material Design [spec](https://material.io/components/pickers/#mobile-pickers). This will replace the current implementation, so this fix hopefully won't be needed. You can track the progress of the new implementation in #50546. I'll go ahead and close this PR. Thanks.

**Pull request closed without merging**
