### PR TITLE
SizeObserver crusade: Remove EnterExitTransition

### PR DESCRIPTION
**Pull request by Hixie**
...and friends.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @abarth, @apwilson

**Comment by abarth** [comment]
LGTM assuming andrew is ok with it.

**Comment by pylaligand** [comment]
Is there a replacement for that class? We use it in exactly one spot in SysUI.

**Comment by abarth** [comment]
@pylaligand: @Hixie discussed the change with @apwilson .  I'm not sure what resolution they agreed upon.  If it's causing problem before we hear back from them we can revert this patch.

**Pull request merged**
