### PR TITLE
Revert "Add the refresh rate fields to perf_test"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#99710

Failures like https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20animated_placeholder_perf__e2e_summary/2036/overview

### CODE REVIEW

**Comment by bdero** [comment]
There's a bug for this here: https://github.com/flutter/flutter/issues/99796

**Comment by zanderso** [comment]
We should revert to reopen the tree and then investigate after

**Comment by bdero** [comment]
Ah right, I didn't notice it was blocking up the flutter repo

**Review by bdero — APPROVED** [review]

**Review by dnfield — APPROVED** [review]
LGTM

**Pull request merged**
