### PR TITLE
Where appropriate use void instead of Null as type argument

### PR DESCRIPTION
**Pull request by mraleph**
This fixes runtime type check failures in strong mode.

This should not be merged before VM, CFE and analyzer all declare sufficient support for generalized void Dart 2.0 feature.

/cc @a-siva 

fyi @Hixie

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
@mraleph Do you understand the test failures? Was this blocked on the dart roll maybe?

**Comment by mraleph** [comment]
@Hixie yes, as I indicated in the original description, we are waiting for all peaces to fall in place. VM and analyzer should be there now, but we are waiting for CFE to land.

**Comment by Hixie** [comment]
Ah, cool, ok. Thanks.

**Review by leafpetersen — APPROVED** [review]

**Comment by a-siva** [comment]
This PR has landed, @mraleph you can abandon this PR.

**Comment by mraleph** [comment]
\o/ thanks @a-siva

**Comment by Hixie** [comment]
Looking at this in more detail, this only changes generic methods to use `<void>` instead of `<Null>`, it doesn't change any constructor calls or any type declarations. Is that intentional? Ideally, we'd use `Future<void>` everywhere instead of `Future<Null>`, for instance.

**Pull request closed without merging**
