### PR TITLE
Only show the keyboard when the user explicitly focuses an Input.

### LINKED ISSUE #6603: Input reopens keyboard after user interacts with a form element other than Input
1. Create a simple form with a dropdown button and an Input.
2. Tap on input, keyboard appears.
3. Close the keyboard.
4. Open up the dropdown and select something.
5. As the dropdown closes, Input regains focus and opens the keyboard automatically.

I don't mind Input keeping the focus since dropdown isn't a focusable element (typically) but it should not reopen the keyboard. Keyboard should only open when the input element is tapped.

### PR DESCRIPTION
**Pull request by mpcomplete**
Fixes https://github.com/flutter/flutter/issues/6603

### CODE REVIEW

**Comment by Hixie** [comment]
This breaks autofocus, right?

LGTM, ideally with a test, if breaking autofocus is intentional.

Now that we only want to show the keyboard in response to use action, though, maybe we should just literally do it onTap, rather than messing with build and so on.

**Comment by mpcomplete** [comment]
The reason I did it in 2 steps is this comment: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/editable.dart#L301 . This implies that attempting to acquire focus may fail.

I suppose it would break autofocus - or at least, prevent the keyboard from showing for an autofocused widget, until you tap it. I'm not sure what the correct behavior is. I don't know of any examples of autofocused text fields in other material apps.

**Comment by Hixie** [comment]
Yeah maybe we should just rip the autofocus idea out entirely.

You're right about the showing the keyboard after getting focus thing. Not sure what we can really do to make that better...

**Comment by Hixie** [comment]
This shouldn't have landed, since Travis was red for this PR. Please don't land PRs unless Travis is green and the waterfall is showing no problems.

**Pull request merged**
