### PR TITLE
Cleanup no longer used scale and turns getters.

### LINKED ISSUE #130946: Generic version of the ScaleTransition and RotationTransition
In: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/transitions.dart

ScaleTransition and RotationTransition  have duplicate code for the the alignment and filterQuality logic.
A more generic animation to Matrix Transition could both factor the duplicate code, and provide an easy way to make more Matrix based animations.

This is a proposal to make a new generic MatrixTransition class, with the common code, and make ScaleTransition and RotationTransition special cases of it.

### PR DESCRIPTION
**Pull request by gmilou**
Remove RotationTransition.turns and ScaleTransition.scale getters.

fixes #130946

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hey @gmilou thanks for sending another PR. This looks like a breaking change, instead we should probably deprecate these getters in order to allow time for developers to migrate gracefully.

Then again, I could see a case for them staying from a readability/ease-of-use perspective. What do you think?

It looks like several checks are also failing, can you take a look?

**Comment by gmilou** [comment]
Right, that's why I've left this in draft for now.
I'm still waiting on a changes in packages to build
https://github.com/flutter/packages/pull/4747

Last time I checked it needed a roll, or at least that was I think.

Once that PR is merged, this one should be good to go.

**Comment by gmilou** [comment]
Actually needed changes should have rolled for https://github.com/flutter/packages/pull/4747 to pass checks by now. I need to look deeper.

**Comment by goderbauer** [comment]
(triage): @gmilou Do you still have plans to come back to this one and finish the work?

**Comment by gmilou** [comment]
> (triage): @gmilou Do you still have plans to come back to this one and finish the work?

Yeah, I'm sorry I've been distracted by other things, but I do intend to finish this.

**Comment by goderbauer** [comment]
I am going to close this one for now. Please feel free to reopen it if you do find the time to work on this again. Thank you!

**Pull request closed without merging**
