### PR TITLE
fix: cuertino dialog action background blur effect

### PR DESCRIPTION
**Pull request by akindone**
#20784

### CODE REVIEW

**Comment by akindone** [comment]
below images show the difference between before fix and after.
run on iPhone7 plus
```shell
flutter --version
Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (7 days ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

before-1
fixed-1
before-2
fixed-2

**Comment by matthew-carroll** [comment]
Thanks for the PR to fix the issue.

At the moment I'm having trouble remembering why we used Rect.largest, but there was definitely a reason at the time, so I'm going to need a little time to test this PR and to discover that history.

I'm currently busy with some other things, so if you have some free cycles and you'd like to help verify this work even more, you might consider testing the dialog on top of more complex backgrounds.  

One concern that I need to investigate is edge effects.  We may have used Rect.largest to avoid rendering artifacts near the edges of the dialog.  In your screenshots there do not appear to be any edge effects, but then again it's rendering on a very simple and solid background.  The more unusual the content beneath the dialog, the better the chances that we discover edge effects.

**Comment by akindone** [comment]
> Thanks for the PR to fix the issue.
> 
> At the moment I'm having trouble remembering why we used Rect.largest, but there was definitely a reason at the time, so I'm going to need a little time to test this PR and to discover that history.
> 
> I'm currently busy with some other things, so if you have some free cycles and you'd like to help verify this work even more, you might consider testing the dialog on top of more complex backgrounds.
> 
> One concern that I need to investigate is edge effects. We may have used Rect.largest to avoid rendering artifacts near the edges of the dialog. In your screenshots there do not appear to be any edge effects, but then again it's rendering on a very simple and solid background. The more unusual the content beneath the dialog, the better the chances that we discover edge effects.

I have tried some other content beneath the dialog, like a [video](http://cdn.akindone.com/test2-above-video.mov)/[another dialog](http://cdn.akindone.com/test3-above-another-dialog.mov)/[text and image](http://cdn.akindone.com/test1-above-text-image.mov), it looks good.

**Comment by xster** [comment]
Thanks for the extra testing! LGTM

Matt can help you merge in when he's ready.

**Comment by xster** [comment]
@akindone, thanks so much for taking the time to do the extra testing. It looks good to me. @matthew-carroll, I'm going to merge this in and watch out for it in the dev channel. Let us know if you have more concerns.

**Pull request merged**
