### PR TITLE
Pin analyzer package so that we're consistent

### PR DESCRIPTION
**Pull request by Hixie**
See the comment in the patch for details.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @mpcomplete - this is a side-effect of your recent patch

**Comment by mpcomplete** [comment]
lgtm, sorry! (strangely I don't get any errors when running `flutter analyze`)

**Comment by Hixie** [comment]
you should get some warning spew (it's visible e.g. in the travis logs) but it doesn't count as failure.

**Comment by Hixie** [comment]
(maybe it should)

**Pull request merged**
