### PR TITLE
Add emailAddress, url TextInputTypes

### PR DESCRIPTION
**Pull request by cbracken**
Adds support for requesting keyboards optimised for email address and URL entry.

### CODE REVIEW

**Comment by goderbauer** [comment]
LGTM

**Comment by cbracken** [comment]
Related: flutter/engine#3729, flutter/engine#3730

**Comment by Hixie** [comment]
LGTM. In a future commit (or this one) it would be great to add more colour to these docs.

**Comment by cbracken** [comment]
SGTM. Will overhaul the whole lot in a followup patch in a few minutes to avoid touching the others in this one.

**Pull request merged**
