### PR TITLE
ios launcher icons with more padding, optimized

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
cc @HansMuller @Hixie

**Comment by sethladd** [comment]
closes https://github.com/flutter/flutter/issues/5404

**Comment by HansMuller** [comment]
This LGTM but having 3 copies of ~40 files doesn't seem like a good idea

**Comment by Hixie** [comment]
I am starting to get concerned as to the number of binary files in the flutter repo. Every one of these files (even the ones we've deleted) have to be downloaded by everyone who uses flutter.

**Comment by abarth** [comment]
Can we move them into a google storage bucket and pull them down like we do with other binary artifacts?

**Comment by dragostis** [comment]
@Hixie I've added this as a separate [issue](https://github.com/flutter/flutter/issues/5471).

**Comment by sethladd** [comment]
Would it be ok to land this now and then figure out how to deal with binary
assets? I don't think I'm greatly increasing the number of files? Also, I
ran optipng on everything:)

**Comment by abarth** [comment]
> Would it be ok to land this now and then figure out how to deal with binary assets?

Once you land this, the binary files will be in the history forever.  It's probably better to address this issue before digging ourselves deeper into this hole.

**Comment by sethladd** [comment]
OK, just tell me where to put the new icons. Thanks!

**Comment by sethladd** [comment]
Opened https://github.com/flutter/flutter/issues/5472 to track the intention to pull down binary assets from a source external to the repo.

**Comment by sethladd** [comment]
Talked to @abarth and I can land this one. But we do want a long-term solution for assets that can live outside the repo.

**Pull request merged**
