### PR TITLE
Add Support for attaching device with remote url

### PR DESCRIPTION
**Pull request by lext-7**
Use attach command to connect a remote device via http url.

```shell
flutter attach --device ios --url http://x.x.x.x:xxxx --restart
```

This maybe useful for those apps that embed flutter to implement part of the app not the whole app.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
It should already be possible to attach to embedded flutter applications via flutter attach, however the attach process must be started before the flutter view is initialized. There is some work to use mdns to make this process easier, so that attach can be started at any time in https://github.com/flutter/flutter/issues/23164

**Comment by lext-7** [comment]
@jonahwilliams Is there any docs to tell us how to use `attach` command to attach a remote device ? Thanks.

**Comment by kangwang1988** [comment]
```
KyleWongdeMacBook-Pro:flutter_read_file_demo kylewong$ ~/Codes/Flutter/alibaba-flutter/flutter/bin/flutter attach --help
Attach to a running application.

Usage: flutter attach [arguments]
-h, --help                Print this usage information.
    --debug               Build a debug version of your app (default mode).
    --profile             Build a version of your app specialized for performance profiling.
    --release             Build a release version of your app.
-t, --target=<path>       The main entry-point file of the application, as run on the device.
                          If the --target option is omitted, but a file name is provided on the command line, then that is used instead.
                          (defaults to "lib/main.dart")

    --observatory-port    Listen to the given port for an observatory debugger connection.
                          Specifying port 0 (the default) will find a random free port.

    --debug-port          Device port where the observatory is listening.
    --pid-file            Specify a file to write the process id to. You can send SIGUSR1 to trigger a hot reload and SIGUSR2 to trigger a hot restart.

Run "flutter help" to see global options.
KyleWongdeMacBook-Pro:flutter_read_file_demo kylewong$ 
```
Besides, it's also supported in the latest flutter plugin.

**Comment by jonahwilliams** [comment]
@lext-7 What sort of setup do you have for a remote device - attached to a different host machine?

**Comment by lext-7** [comment]
@jonahwilliams Attach to a device which is running flutter without usb connection in the same network with the computer. For example, the ip of my computer is 1.2.3.1 and the ip of my android phone is 1.2.3.2. The observatory port is 12345.  Then I can attach to my flutter app without usb, just as followed:

```shell
flutter attach --device android --url http://1.2.3.2:12345/ --restart
```

Is this function currently supported ? If yes, please provide a demo or doc to teach me how to use it.

**Comment by jonahwilliams** [comment]
This functionality is already supported via the flutter attach command. While we definitely need more documentation here, I would start with the help text of `flutter attach`.

**Comment by T-Shujun** [comment]
@jonahwilliams Is the docs ready？I hope to use the feature of `flutter  attach` @lext-7  mentioned。

**Pull request closed without merging**
