### PR TITLE
PaginatedDataTable fills more than the available size of its card, making it needlessly scroll horizontally

### PR DESCRIPTION
**Pull request by jofas**
Hi, 

a detailed description of my issue can be found in #84978. Basically, if the `PaginatedDataTable` has more horizontal space than it needs for showing its content in full width, it is still needlessly horizontally scrollable. The problem is, that the `LayoutBuilder` used for giving the underlying `DataTable`---which shows the current page of the `PaginatedDataTable`---its minimal width does not know about the `margin` of the `Card` which contains the `DataTable`. By default, the `margin` of a `Card` is 4, so the minimum width of the `DataTable` should be the size of its parent minus 8 (left and right margin) of the card. The minus 8 part is currently omitted, resulting in this tiny horizontal scroll by 8 pixels. I simply put the `LayoutBuilder` inside of the `Card`, so that the margin will be included in the width calculation for the underlying `DataTable`. 

My PR is based on the work done in #48531, which made the `PaginatedDataTable` at least as wide as its parent allows.
I simply added the margin to the test which tests the width of the `PaginatedDataTable`, I hope that counts as a new test.

## Fixed Issues

* #84978 
 
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jofas** [comment]
@googlebot I signed it!

**Comment by craiglabenz** [comment]
Thanks for this PR, @jofas! The changes look perfectly sensible to me, but so far I've failed to create the original scrollbar problem by building a `PaginatedDataTable` with the old implementation and enough space, as you described. Would you mind supplying a minimum repro gist so I can see both ends of this fix?

Thanks so much!

**Comment by jofas** [comment]
Hi @craiglabenz,

I've updated the #84978 issue with example code that shows the unwanted horizontal scrolling. I've tested it on web and android.

**Review by craiglabenz — APPROVED** [review]
Cool, this is looking good. Probably need to rebase it against master and tidy up CI, and then it should be ready :)

**Comment by jofas** [comment]
Awesome! Do you want me to do the rebasing? I don't know much about your CI workflow though, so would be great if you could elaborate a little on the CI stuff.

**Comment by craiglabenz** [comment]
I just rebased this locally and ran all the CI jobs; and everything was good to go. Adding the auto-merge tag for the next time the tree is green.

**Comment by craiglabenz** [comment]
Okay, CI disagreed, so I force pushed my rebase.

**Comment by craiglabenz** [comment]
@jofas, are you able to update this branch against the main branch and resolve any obvious issues? At that point, I'll be able to help tackle not obvious issues :)

**Comment by craiglabenz** [comment]
@jofas I know this fix works, so I would also like to see it land. If rebasing is giving you trouble (it did for me, as well!) then it might be worth starting a brand new branch off `main`, manually plopping in your couple of changes, and tagging me on the PR.

**Comment by jofas** [comment]
Hi @craiglabenz, the new PR is #95390. I couldn't add you as a reviewer, but mentioned you in the comments

**Comment by Piinks** [comment]
Since a new PR has been opened for this, I am going to close it. Thanks!

**Pull request closed without merging**
