### PR TITLE
Modify iOS template to fit Apple's HIG

### LINKED ISSUE #106110: The default icon for iOS does not fit Apple's HIG
## Steps to Reproduce

iOS_icon_1
This is how the application icons are displayed in the settings list, obviously with **black gaps** in the four corners. This is because the mask Apple uses is not the standard rounded corners, but **continuous corner**.

iOS_icon_2

This is a slow motion video of the app when it is opened from the home screen. The black color in the transition animation is **caused by the transparent part** of the icon. 

This animation takes the colors of the left, bottom and right sides of the icon and then spreads the colors in all three directions, but the current icon has rounded corners, so some of the colors are missing.

**Expected results:** 

Expect to change to a style that fits the standard mentioned here: [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons#specifications)

| Platform  | Transparency    | Asset shape   | 
| :-              | :-                        | :-                     |
| iOS, iPadOS  | No           | Square                 |

**Actual results:** 
The default icon for iOS does not fit Apple's HIG.

### PR DESCRIPTION
**Pull request by RockerFlower**
Scale down `Icon-App-1024x1024@1x.png` to different sizes and replace the original icon with rounded corners.

fix #106110 

iOS_icon_1
This is how the application icons are displayed in the settings list, obviously with **black gaps** in the four corners. This is because the mask Apple uses is not the standard rounded corners, but **continuous corner**.

iOS_icon_2

This is a slow motion video of the app when it is opened from the home screen. The black color in the transition animation is **caused by the transparent part** of the icon. 

This animation takes the colors of the left, bottom and right sides of the icon and then spreads the colors in all three directions, but the current icon has rounded corners, so some of the colors are missing.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by timsneath** [comment]
Excited about this PR!

Did you see https://github.com/flutter/flutter/wiki/Managing-template-image-assets?

**Comment by RockerFlower** [comment]
> Excited about this PR!
> 
> Did you see https://github.com/flutter/flutter/wiki/Managing-template-image-assets?

Yes, I've seen it. I thought Android and iOS were different from other platforms. 😂 I'll try to modify.

**Comment by stuartmorgan** [comment]
Currently they are different only because the current icons predate the new out-of-repo system.

**Comment by RockerFlower** [comment]
@timsneath I have created a new PR https://github.com/flutter/packages/pull/2266

**Review by jmagman — COMMENTED** [review]
The test case I was mentioned in https://github.com/flutter/packages/pull/2266#pullrequestreview-1020865671 would be something like:

https://github.com/flutter/flutter/blob/0e0baa40c75fca3d119a821080038b45f1a3cf11/packages/flutter_tools/test/commands.shard/permeable/create_test.dart#L154-L163
```diff
 <String>[ 
   'analysis_options.yaml', 
   'android/app/src/main/java/com/example/flutter_project/MainActivity.java', 
   'android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java', 
   'flutter_project.iml', 
   'ios/Flutter/AppFrameworkInfo.plist', 
   'ios/Runner/AppDelegate.m', 
   'ios/Runner/GeneratedPluginRegistrant.h', 
+  'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png',
   'lib/main.dart', 
 ], 
```
That test creates a flutter app, and validates those files exist in the newly created app.  So validate that at least one of your templated icons gets downloaded and put in the right spot.

**Comment by jmagman** [comment]
And https://github.com/flutter/packages/pull/2266 is now published.  Probably easiest to rebase/merged your branch to top of tree to kick all those tests again.

**Comment by RockerFlower** [comment]
> The test case I was mentioned in [flutter/packages#2266 (review)](https://github.com/flutter/packages/pull/2266#pullrequestreview-1020865671) would be something like:
> 
> https://github.com/flutter/flutter/blob/0e0baa40c75fca3d119a821080038b45f1a3cf11/packages/flutter_tools/test/commands.shard/permeable/create_test.dart#L154-L163
> 
> ```diff
>  <String>[ 
>    'analysis_options.yaml', 
>    'android/app/src/main/java/com/example/flutter_project/MainActivity.java', 
>    'android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java', 
>    'flutter_project.iml', 
>    'ios/Flutter/AppFrameworkInfo.plist', 
>    'ios/Runner/AppDelegate.m', 
>    'ios/Runner/GeneratedPluginRegistrant.h', 
> +  'ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png',
>    'lib/main.dart', 
>  ], 
> ```
> 
> That test creates a flutter app, and validates those files exist in the newly created app. So validate that at least one of your templated icons gets downloaded and put in the right spot.

I apologize for only seeing it now. Do I need to submit a pull request to flutter/packages for this test?

**Comment by stuartmorgan** [comment]
That test is part of this repository, so should be in this PR.

**Comment by franckbleyer1** [comment]
Le lun. 18 juil. 2022 à 18:27, stuartmorgan ***@***.***> a
écrit :

**Comment by jmagman** [comment]
@RockerFlower are you ready to fix this up and merge?  This is blocking any further updates to `flutter_template_images`.

**Comment by RockerFlower** [comment]
> @RockerFlower are you ready to fix this up and merge? This is blocking any further updates to `flutter_template_images`.

I recommitted it, but there are still some failures in the automated checks.

**Comment by jmagman** [comment]
It looks unrelated to your actual changes, you're branched from e1d9adf483 which is pretty old, can you rebase or merge onto master top of tree? I would just do it for you on your fork if I had permission but this PR is on your main branch and I don't want to mess with that.

**Comment by RockerFlower** [comment]
The relevant changes have been merged here: https://github.com/flutter/flutter/pull/107873

**Pull request closed without merging**
