### PR TITLE
Reland "Framework support for font features in text styles"

### PR DESCRIPTION
**Pull request by jason-simmons**
See https://github.com/flutter/flutter/issues/31691

### CODE REVIEW

**Comment by GaryQian** [comment]
Have the web versions of the API been added? I believe that was the reason it had to be rolled back if I remember correctly. If so, do you mind linking the change here?

**Comment by jason-simmons** [comment]
@jonahwilliams committed https://github.com/flutter/engine/commit/fa2e2d9fcbf5b11e90937255c2df428fd6729f01.

Has this rolled to wherever it needs to land?

**Comment by GaryQian** [comment]
That was 7 days ago, it should be rolled in.

**Review by GaryQian — APPROVED** [review]
LGTM!

**Comment by GaryQian** [comment]
It does look like the engine stub_ui text.dart patch is missing docs on the ` List<FontFeature> fontFeatures,` parameter. We should add docs for that.

**Pull request merged**
