### PR TITLE
Add iOS key map generation, make macOS var naming consistent with repo

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This adds iOS key map generation that uses std::maps.  It uses std::maps because on iOS if we use NSDictionaries, then when XCode loads the dylib, the initialization of those status NSDictionaries hasn't yet occurred, and it crashes the app. std::maps have a well-defined static behavior, and are correctly initialized.

I also made the naming of variables, fields, etc. consistent for macOS.  We variously had `macosFoo`, `macOSFoo`, and `macOsFoo`. I eliminated `macOsFoo` and `macosFoo`, since the rest of the repo uses `macOSFoo` for lowerCamelCase names (with only a few exceptions).  I used `iOSFoo` for iOS.

### CODE REVIEW

**Comment by dkwingsmt** [comment]
I'm kind of against `macOSFoo`, because we've been using `HtmlFoo` and `JsonFoo` everywhere. I suggest using `macOs`, but `macos` is also acceptable.

**Comment by gspencergoog** [comment]
The stats in the Flutter repo seem to make a clear choice of "macOS" or "macos" (count of lines containing):

```
  754 macOS
  622 macos
    7 macOs
```

And for being used with other words in an identifier, it's similar:

```shell
flutter > grep --include=*.dart -r "\bmacOS[A-Z]" . | wc -l
137
flutter > grep --include=*.dart -r "\bmacos[A-Z]" . | wc -l
107
flutter > grep --include=*.dart -r "\bmacOs[A-Z]" . | wc -l
4
```

When I have named these things in the past, we've made explicit exceptions for iOS, since `iOs` and `IOs` look silly. From the stats, it appears we've effectively done that for macOS as well.

At the very least, the data file should definitely be "macos", since "macOs" would be the only capitalized identifier (e.g. it's already using 'ios' is not 'iOs').

**Comment by dkwingsmt** [comment]
The one in data file was definitely an oversight and should be `macos`.

I see that we've adopted such a convention. I guess it's `macOS` and `MacOS`, as well as `iOS` and `IOS` then.

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Comment by dkwingsmt** [comment]
Shall we add this convention to https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#capitalize-identifiers-consistent-with-their-spelling ?

**Comment by gspencergoog** [comment]
That would seem to make sense. I'll ask @Hixie.

**Pull request merged**
