### PR TITLE
add missing trailing commas

### PR DESCRIPTION
**Pull request by a14n**
Follow up on #79352 to add missing trailing commas in asserts.

This PR:

* mainly add missing trailing commas (for arguments that are on new lines)
* remove some unnecessary trailing commas
* sometimes reformat the tree with 2 spaces indent

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by a14n** [comment]
> Google testing Pending — Google testing has started...

@goderbauer could you please check why it is still pending ?

**Comment by goderbauer** [comment]
Looks like tests are still running...

**Comment by a14n** [comment]
>Looks like tests are still running...

strange because I pushed 13h ago

**Comment by goderbauer** [comment]
Oh, the google ckeck only starts running after the PR has been approved. So the tests have only ben running for less than 15 minutes.

**Comment by goderbauer** [comment]
Looks like it passed now :)

**Comment by a14n** [comment]
Thanks for the info :)

**Pull request merged**
