### PR TITLE
Fixed missing implementations of toString() in two tests

### PR DESCRIPTION
**Pull request by bkonyi**

### CODE REVIEW

**Review by aam — APPROVED** [review]
cc @yjbanov @matthew-carroll  original authors of _TextStyleProxy and _FakeTicker classes

**Review by yjbanov — APPROVED** [review]

**Comment by Hixie** [comment]
I'm confused by this change. What is the purpose here?

**Comment by Hixie** [comment]
oh, I see. It's because the interface changes the API compared to Object.

**Comment by aam** [comment]
> oh, I see. It's because the interface changes the API compared to Object.

Right, it went unnoticed until recently dart frontend started to flag this kind of errors.

**Pull request merged**
