### PR TITLE
Wrap PopupMenu with SafeArea to respect status bar

### LINKED ISSUE #19954: Tall popup menus go under the system status bar
The popup menu of PopupMenuButton can go all the way into the status bar if the list is too long. It could be even worse if there's a notch on the device.

Also it seems that the menu doesn't have a scroll bar, although I'm not sure if it is intended.

flutter-menu

### PR DESCRIPTION
**Pull request by JuYeong0413**
## Description

Continuous work of https://github.com/flutter/flutter/pull/55489

Currently, `PopupMenu` does not respect the system status bar and bottom notch.

Wrapping `PopupMenu` with `SafeArea` would solve this problem.

## Related Issues

Fixes https://github.com/flutter/flutter/pull/19954

## Tests

I added the following tests:

1. `PopupMenu` in `AppBar` does not overlap with the status bar
2. Vertically long `PopupMenu` does not overlap with the status bar and bottom notch

**However, new tests are failing.**
I have created `MediaQuery.data` for mimicking status bar and bottom notch, but the results are same before&after wrapping `PopupMenu` with `SafeArea`.
Executing the same widgets on the emulator works as expected, so I think there's some problem with `MediaQueryData` or getting y offset of `PopupMenu` in my test code. (BTW, using `MediaQueryData.viewInsets` and `MediaQueryData.viewPadding` both give me the same result when representing the status bar... I think `MediaQueryData.viewInsets` may be correct.)

cc/ @Piinks 

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [x] Yes, this is a breaking change.
   - [x] I wrote a design doc: https://flutter.dev/go/wrap-popupmenu-with-safearea

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Piinks** [comment]
Hey @JuYeong0413 Can you share some sample code that reproduces the behavior in your images above? I have been looking at these tests and I suspect they may be failing because it is not quite working as expected. Thanks!

**Comment by JuYeong0413** [comment]
Ah I've put the reproducible code gist link in the design doc, but found out the link was broken. Sorry.
Here are the sample codes:
- [first behavior](v)
- [second vehavior](https://gist.github.com/JuYeong0413/90b685c4115d87d7369db0f40f5c1daf#file-popup_menu_with_many_items-dart)

**Comment by Piinks** [comment]
Sorry for the delay @JuYeong0413 I've been away. This is on my list to review today. :)

**Comment by JuYeong0413** [comment]
It's okay. :) I know the Flutter team has a lot of works to do. Take your time.

**Comment by Piinks** [comment]
I cannot sort out why the mock media queries in your tests are not working as expected. Let me see if I can recruit a second opinion.

**Comment by Piinks** [comment]
Hey @JuYeong0413 I forgot that the Popup menu is in a different overlay entry, so if you use MaterialApp.builder and place your media query there it should work. I found a test that you can use as an example to update your test:  
https://github.com/flutter/flutter/blob/3e8fb33c08d95debf3a10f8932bd54e4da0932da/packages/flutter/test/material/dialog_test.dart#L1551
Let me know how this works out for you!

**Comment by JuYeong0413** [comment]
Thank you very much for your help @Piinks, using `MaterialApp.builder` worked! 😄 
I've updated the tests. Please take a look when you have time.

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
Thank you for the contribution! And for your patience in figuring out the tests! 🎉

**Pull request merged**
