### PR TITLE
[web] provide serviceWorkerVersion to the getNewServiceWorker function

### LINKED ISSUE #130212: [web] serviceWorkerVersion is not defined at _getNewServiceWorker
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a new web project with `flutter create`.
2. Remove `var serviceWorkerVersion = null;` from the `index.html` 
3.  provide custom service worker version to the `loadEntrypoint` (`index.html`):
```js
_flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: '123',
        },
```
4. Launch web app
5. See `Installing/Activating first service worker.` message in the Chrome console (Verbose level)
6. Refresh the page

### Expected results

Message `Loading from existing service worker.` in the console, service worker is loaded.

### Actual results

Service worker is not loaded with an exception in the console:
```
Exception while loading service worker: ReferenceError: serviceWorkerVersion is not defined
    at _getNewServiceWorker (flutter.js:175:49)
```

### Code sample

<details><summary>Code sample</summary>

```js
window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: '123',
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3.1 22E772610a darwin-arm64,
    locale ru-RU)
    • Flutter version 3.10.5 on channel stable at /Users/mazhnik/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (4 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/mazhnik/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/mazhnik/Library/Android/sdk
    • Java binary at: /Users/mazhnik/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841
      /Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/mazhnik/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841
      /Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/mazhnik/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin version 74.0.4
    • Dart plugin version 231.9161.14

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.3)
    • IntelliJ at /Users/mazhnik/Library/Application
      Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9161.38/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone PM (mobile) • 00008120-000E511C14DB401E • ios            • iOS 16.0
      20A357
    • macOS (desktop)    • macos                     • darwin-arm64   • macOS
      13.3.1 22E772610a darwin-arm64
    • Chrome (web)       • chrome                    • web-javascript • Google
      Chrome 114.0.5735.198
    ! Error: iPhone PM is busy: Loading metadata for the watch via iPhone PM.
      Xcode will continue when iPhone PM is finished. (code -10)
    ! Error: (null) needs to connect to determine its availability. Check the
      connection between the device and its companion iPhone, and the connection
      between the iPhone and Xcode. Both devices may also need to be restarted
      and unlocked. (code 1)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by p-mazhnik**
Fixes https://github.com/flutter/flutter/issues/130212

Fix `Unresolved variable or type 'serviceWorkerVersion'` in the `_getNewServiceWorker` function.  

Supersedes https://github.com/flutter/flutter/pull/130206

### CODE REVIEW

**Comment by ditman** [comment]
https://github.com/flutter/flutter/pull/130206 was reviewed by me and @yjbanov earlier. We dropped it because google tooling was ignoring the branch.

**Review by ditman — APPROVED** [review]
This contains the same changes as #130206. LGTM!

**Comment by ditman** [comment]
Once more, thanks for the contribution @p-mazhnik!!

**Comment by ditman** [comment]
Agh, bummer. PTAL @yjbanov! We need a 2nd approval here :)

**Comment by christopherfujino** [comment]
friendly ping @yjbanov

**Comment by christopherfujino** [comment]
friendly ping @yjbanov

**Comment by christopherfujino** [comment]
friendly ping @yjbanov

**Comment by christopherfujino** [comment]
pinged on discord for a review

**Review by yjbanov — APPROVED** [review]

**Pull request merged**
