### PR TITLE
Revert "Revert "Fix remaining holes in stack trace demangling""

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#60916

Error is unrelated, will be fixed by https://github.com/flutter/flutter/pull/60668

### CODE REVIEW

**Comment by dnfield** [comment]
LGTM.

I assumed it was caused by a bad merge up or something.  Thanks for fixing.

**Comment by jonahwilliams** [comment]
FYI @fkorotkov I cannot get these tasks to rerun :(


https://cirrus-ci.com/build/4837175218929664

**Comment by fkorotkov** [comment]
@jonahwilliams there was a new build though: https://cirrus-ci.com/build/6311036733095936

Let me check why GH didn't update statuses.

**Comment by fkorotkov** [comment]
Oh. It's the issue with different sets of tasks for branch builds vs PR builds. There is no way to delete a check run. I've reported it to GH and will implement a workaround on a Cirrus side.

**Comment by jonahwilliams** [comment]
@PixelToast @dnfield could you try and re-land the PR today? The revert-revert doesn't really seem to work

**Pull request closed without merging**
