### PR TITLE
include all generated part files in animated_icons_private_test

### PR DESCRIPTION
**Pull request by amirh**

### CODE REVIEW

**Comment by Hixie** [comment]
How come this wasn't caught by Travis or the infrabots, only by devicelab?

cc @yjbanov

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
https://github.com/dart-lang/sdk/issues/31998

**Comment by cbracken** [comment]
This appears to have bumped the flutter analyzer watch benchmark into the orange.

**Comment by amirh** [comment]
I'm following up with the VM team to see if this is expected.

**Pull request merged**
