### PR TITLE
[integration_test] Fix official example for Android

### LINKED ISSUE #98161: [integration_test] Fix official example for Android
`integration_test` [example](https://github.com/flutter/flutter/tree/master/packages/integration_test/example) crashes when trying to run the test from Gradle on a physical device, following instructions from [here](https://github.com/flutter/flutter/tree/master/packages/integration_test#android-device-testing) 

<details> 
<summary>logs</summary> 
	
```console
tahatesser@Tahas-MBP android % ./gradlew app:connectedAndroidTest -Ptarget=`pwd`/../integration_test/extended_test.dart
> Task :app:compileFlutterBuildDebug UP-TO-DATE
> Task :app:packLibsflutterBuildDebug UP-TO-DATE
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :integration_test:preBuild UP-TO-DATE
> Task :integration_test:preDebugBuild UP-TO-DATE
> Task :integration_test:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :integration_test:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :integration_test:writeDebugAarMetadata UP-TO-DATE
> Task :app:checkDebugAarMetadata
> Task :app:cleanMergeDebugAssets
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :integration_test:mergeDebugShaders UP-TO-DATE
> Task :integration_test:compileDebugShaders NO-SOURCE
> Task :integration_test:generateDebugAssets UP-TO-DATE
> Task :integration_test:packageDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets
> Task :app:copyFlutterAssetsDebug
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :integration_test:compileDebugRenderscript NO-SOURCE
> Task :integration_test:generateDebugResValues UP-TO-DATE
> Task :integration_test:generateDebugResources UP-TO-DATE
> Task :integration_test:packageDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:extractDeepLinksDebug UP-TO-DATE
> Task :integration_test:extractDeepLinksDebug UP-TO-DATE
> Task :integration_test:processDebugManifest UP-TO-DATE
> Task :app:processDebugMainManifest UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugManifestForPackage UP-TO-DATE
> Task :integration_test:compileDebugLibraryResources UP-TO-DATE
> Task :integration_test:parseDebugLocalResources UP-TO-DATE
> Task :integration_test:generateDebugRFile UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :integration_test:generateDebugBuildConfig UP-TO-DATE
> Task :integration_test:javaPreCompileDebug UP-TO-DATE
> Task :integration_test:compileDebugJavaWithJavac
> Task :integration_test:bundleLibCompileToJarDebug UP-TO-DATE
> Task :app:compileDebugJavaWithJavac
> Task :app:compressDebugAssets UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :integration_test:processDebugJavaRes NO-SOURCE
> Task :integration_test:bundleLibResDebug NO-SOURCE
> Task :integration_test:bundleLibRuntimeToJarDebug UP-TO-DATE
> Task :app:checkDebugDuplicateClasses
> Task :app:mergeDebugJavaResource
> Task :app:dexBuilderDebug
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :integration_test:mergeDebugJniLibFolders UP-TO-DATE
> Task :integration_test:mergeDebugNativeLibs NO-SOURCE
> Task :integration_test:stripDebugDebugSymbols NO-SOURCE
> Task :integration_test:copyDebugJniLibsProjectOnly UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:bundleDebugClasses UP-TO-DATE
> Task :app:preDebugAndroidTestBuild SKIPPED
> Task :app:compileDebugAndroidTestAidl NO-SOURCE
> Task :app:desugarDebugFileDependencies
> Task :app:processDebugAndroidTestManifest UP-TO-DATE
> Task :app:compileDebugAndroidTestRenderscript NO-SOURCE
> Task :app:generateDebugAndroidTestBuildConfig UP-TO-DATE
> Task :app:javaPreCompileDebugAndroidTest UP-TO-DATE
> Task :app:checkDebugAndroidTestAarMetadata UP-TO-DATE
> Task :app:generateDebugAndroidTestResValues UP-TO-DATE
> Task :app:generateDebugAndroidTestResources UP-TO-DATE
> Task :app:mergeDebugAndroidTestResources UP-TO-DATE
> Task :app:processDebugAndroidTestResources UP-TO-DATE

> Task :app:compileDebugAndroidTestJavaWithJavac FAILED
/Users/tahatesser/Code/flutter_tesser/packages/integration_test/example/android/app/src/androidTest/java/com/example/e2e_example/EmbedderV1ActivityTest.java:15: error: cannot find symbol
  public ActivityTestRule<EmbedderV1Activity> rule =
                          ^
  symbol:   class EmbedderV1Activity
  location: class EmbedderV1ActivityTest
/Users/tahatesser/Code/flutter_tesser/packages/integration_test/example/android/app/src/androidTest/java/com/example/e2e_example/EmbedderV1ActivityTest.java:16: error: cannot find symbol
      new ActivityTestRule<>(EmbedderV1Activity.class, true, false);
                             ^
  symbol:   class EmbedderV1Activity
  location: class EmbedderV1ActivityTest
2 errors

> Task :app:mergeDebugNativeLibs
> Task :app:mergeExtDexDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugAndroidTestJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
53 actionable tasks: 13 executed, 40 up-to-date
tahatesser@Tahas-MBP android % 
```
	
</details>

### 1. Issue
Incorrect package
### Expected results
`integration_test/example/android/app/src/androidTest/java/com/example/integration_test_example)`

### Actual results
`integration_test/example/android/app/src/androidTest/java/com/example/e2e_example)`

pacakge name in the test classes throw errors

https://github.com/flutter/flutter/blob/0ce527eb91a37ef31b60ed6d4a9613310f2107d4/packages/integration_test/example/android/app/src/androidTest/java/com/example/e2e_example/FlutterActivityTest.java#L5

### 2. Issue
Since the example using v2 embeddding

https://github.com/flutter/flutter/blob/0ce527eb91a37ef31b60ed6d4a9613310f2107d4/packages/integration_test/example/android/app/src/main/AndroidManifest.xml#L28

`EmbedderV1ActivityTest.java` crashes the test, it should be removed as it is no longer relevant.

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/98161

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by blasten — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
Please rebase onto https://github.com/flutter/flutter/pull/98166 to fix plugin_lint_mac.

**Comment by jmagman** [comment]
> Please rebase onto #98166 to fix plugin_lint_mac.

Actually make that https://github.com/flutter/flutter/pull/98171.

**Pull request merged**
