### PR TITLE
Is executable doesn't mean a+x

### PR DESCRIPTION
**Pull request by chingjun**
Seen this issue:
```Oops; flutter has exited unexpectedly: "ProcessException: Permission denied
  Command: /tmp/flutter_gradle_wrapper.CKEZBO/gradlew -b /usr/local/google/home/chingjun/test/flutter/packages/flutter_tools/gradle/resolve_dependencies.gradle --project-cache-dir
  /tmp/flutter_gradle_wrapper.CKEZBO resolveDependencies".
```

Flutter doctor pointed me to https://github.com/flutter/flutter/issues/6207, which doesn't help.

Turns out the problem was because the permission on gradlew was `rwxr-x---`, which is not `a+x`.

The code before https://github.com/flutter/flutter/commit/354f80b84a9b30ec3b49d8fed81bce772a1bc8e8 was:
```
final String modes = sourceFile.statSync().modeString();
if (modes != null && modes.contains('x')) {
  os.makeExecutable(destinationFile);
}
```

Which is technically the same as my change here.

### CODE REVIEW

**Comment by blasten** [comment]
Would you mind pasting the full log? It checks for a+x because the Flutter command can be run by any user.

**Comment by chingjun** [comment]
The problem is that `gradlew` file might not be a+x

```
$ ll bin/cache/artifacts/gradle_wrapper/
total 24
drwxr-x--- 3 chingjun primarygroup 4096 Dec 18 09:30 ./
drwxr-xr-x 4 chingjun primarygroup 4096 Dec 18 09:30 ../
drwxr-x--- 3 chingjun primarygroup 4096 Nov 30  2017 gradle/
-rwxr-x--- 1 chingjun primarygroup 4971 Nov 30  2017 gradlew*
-rw-r----- 1 chingjun primarygroup 2404 Nov 30  2017 gradlew.bat
```

Here's the full log:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter precache -a --flutter_runner --web --use-unsigned-mac-binaries

## exception

ProcessException: ProcessException: Permission denied
  Command: /tmp/flutter_gradle_wrapper.IFRGHR/gradlew -b /usr/local/google/home/chingjun/test/flutter/packages/flutter_tools/gradle/resolve_dependencies.gradle --project-cache-dir /tmp/flutter_gradle_wrapper.IFRGHR resolveDependencies

```
#0      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:266:37)
<asynchronous suspension>
#1      AndroidMavenArtifacts.update (package:flutter_tools/src/cache.dart:917:58)
#2      Cache.updateAll (package:flutter_tools/src/cache.dart:363:24)
#3      PrecacheCommand.runCommand (package:flutter_tools/src/commands/precache.dart:87:19)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#6      _rootRunUnary (dart:async/zone.dart:1134:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[!] Flutter (Channel master, v1.13.3-pre.61, on Linux, locale en_US.UTF-8)
    • Flutter version 1.13.3-pre.61 at /usr/local/google/home/chingjun/test/flutter
    • Framework revision 54fa1a5a69 (66 minutes ago), 2019-12-18 11:47:32 -0500
    • Engine revision c327cae7ab
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c9d89d55a6)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-gcc-libs


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/google/home/chingjun/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /usr/local/buildtools/java/jdk/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_181-google-v7-272050736-272050736)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio-with-blaze-3.4
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (3 available)
    • Pixel 2    • HT7AK1A00618 • android-arm64  • Android 9 (API 28)
    • Chrome     • chrome       • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server   • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

**Comment by chingjun** [comment]
Also I see the failing test now, this is used twice. Once is to check the permission of the source file, and once again to check the permission of the destination file.

We need to check for a+x for the second case, but has executable flag on for the first case.

**Comment by chingjun** [comment]
Updated the code to check for all executable flag set when deciding whether to set destination file, and any executable flag set on source file when deciding whether to add the permission at all, PTAL. Thanks

**Review by blasten — APPROVED** [review]
LGTM!

**Pull request merged**
