### PR TITLE
fix analyzer warning: use const where possible

### PR DESCRIPTION
**Pull request by yjbanov**
/cc @Hixie

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM but I don't understand why Travis didn't catch all of these? @pq @danrubel

**Comment by pq** [comment]
Hmmmm.  How recently did those warnings get introduced?  Are they warnings or hints?

cc @bwilkerson

**Comment by bwilkerson** [comment]
I'm not aware of any such warning, but would be very interested to know where this came from.

**Comment by pq** [comment]
Ah wait.  I was confused by the error message reported.  Was it actually: 

    [lint] Prefer const with constant constructors.

In that case, the linter is to blame (err, take credit 😉 ).

cc @yjbanov

**Comment by yjbanov** [comment]
@pq We actually like this warning. The surprising part was:

* on my computer I got warnings across 5 files (fixed by this PR)
* when I submitted https://github.com/flutter/flutter/commit/5efbe05f04aaa65e396ba80a972b84c25153f7c5 Travis only showed a warning in 1 file
* the PR https://github.com/flutter/flutter/pull/9271 was green entirely

I'm wondering if we're pulling different versions of the analyzer/linter somehow.

**Comment by yjbanov** [comment]
Also, I just noticed https://github.com/flutter/flutter/commit/4f258357c91d5f9ccf6d5a6f8caeabd2714d4d14 from @xster, which seems to be following-up on https://github.com/flutter/flutter/commit/7ce1cfd48d483e6d44e717e32e70ecefcac3ee53 with fixes for the exact same lint. Something in our build pipeline seems to be leaking these lints into the master branch.

**Comment by pq** [comment]
OK.  I think I see what's happening.  The issue is that we have a skew in linter versions.

As of https://github.com/flutter/flutter/pull/9297, `flutter_tools` is using `0.1.30` but our Dart SDK is a step behind --- I don't believe that the change to `DEPS` to pull in `0.1.30` has been cherry-picked into the `0.1.23` release branch.  I'll check on the timeframe for that...

Sorry for the confusion.

I've got a better process in mind that will reduce the chances of this skew happening.  Small comfort now but I hope to avoid this in the future!

**Comment by yjbanov** [comment]
Cool. Glad to know this is temporary.

**Comment by pq** [comment]
Chatted w/ @keertip and we're at the end of cherry-picks so this will be in the first `0.1.24` Dart SDK dev roll.  Sorry for any continued confusion in the meantime!

**Pull request merged**
