### PR TITLE
Adding ability to create custom Tooltip made of widget.

### PR DESCRIPTION
**Pull request by vaimikpatel2908**
*Added ability to create a custom tooltip to accept custom widget as a parameter to create a custom tooltip like for the info button in the image. It will continue to accept the message parameter for the Tooltip widget and It will not break the current code.*

image

[Targetting proposal](https://github.com/flutter/flutter/issues/85923)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by HansMuller** [comment]
This PR looks like it's attacking the same problem as https://github.com/flutter/flutter/pull/88539

**Comment by chunhtai** [comment]
Hi   @vaimikpatel2908  and @kenzieschmoll, since you have been working on the same issue. It may be good if you can coordinate with each other and decide which of you would like to move forward with the pr.

**Comment by vaimikpatel2908** [comment]
@chunhtai,

Well, It would be better that you guys can decide whatever is best for the user and framework. If another PR is addressing this issue in a better way, I can close this issue.

**Comment by kenzieschmoll** [comment]
As a user myself, I'd prefer a builder approach vs the RichText support I added. The builder allows for using RichText or any arbitrary widget.

**Comment by vaimikpatel2908** [comment]
Hello Guys,

As message property is mandatory in either simple text or custom widget tooltip which can be used for the semantics always. 

Though, if you like the builder approach on the user side and rich text on the back end side why don't we make it as follows:  

1) We can keep the builder approach on the user side 
2) Can we wrap the provided widget inside a Widget Span and then place it within a rich text tooltip on the framework side?

Let me know what do you think guys?

**Comment by chunhtai** [comment]
@vaimikpatel2908 How would user specify the message in this case?

For example they can do this using inlineSpan
```dart
TextSpan(
   semanticsLabel: 'my descriptive tooltip',
   children: <InlineSpan> [WidgetSpan(child: ...)],
)
```
and when the tooltip opens, the talkback will announce `my descriptive tooltip'`

**Comment by vaimikpatel2908** [comment]
If I understood your concern correctly it already does that:

As of now with this PR, the Tooltip should be implemented as follows:

1) Only message is provided
In this scenario, message is only used for the tooltip as well as semantics unless the user set excludeFromSemantics=true.
```dart
Tooltip(
        message: 'my descriptive tooltip', // this will be used as tooltip text as well as semantics 
    )
```
2) message and custom widget is provided in builder
In this scenario, message is only used as semanticLabel unless the user set excludeFromSemantics=true.
```dart
Tooltip(
        message: 'my descriptive tooltip', // this will be used as semantics only if user didn't set excludeFromSemantics=true
        tooltipBuilder: (BuildContext context, String message) {
            return ...;  // any widget
         },
    )
```

So, here the message will be pronounced by talkback when the tooltip opened.

**Comment by chunhtai** [comment]
In your proposal, the message in the second case is not descriptive, and may be confusing to developer that it will be used differently in two cases. It is not a straight forward api

**Comment by vaimikpatel2908** [comment]
That is definitely true.
Anyways, would you like me to do any change here? or would you like me to close this PR if the other PR meets the requirements?

**Pull request closed without merging**
