### PR TITLE
Added spacer.dart to widgets

### PR DESCRIPTION
**Pull request by ScottS2017**
Added a new ui widget, a very simple spacer that allows for an adjustable spacer that can be implemented in ten characters of code. I was encouraged to push this by several people in Gitter.

### CODE REVIEW

**Comment by Hixie** [comment]
looks like #15802?

**Comment by Hixie** [comment]
no worries!

**Comment by Hixie** [comment]
should i close those one?

**Comment by ScottS2017** [comment]
Sure, it'll be a little bit before I can get back to it

**Pull request closed without merging**
