### PR TITLE
Roll pub packages + update DAP tests

### PR DESCRIPTION
**Pull request by DanTup**
This manually rolls pub packages and updates some calls to use updated APIs that use `Uri` instead of file paths (since macro-generated sources don't exist as files on disk).

### CODE REVIEW

**Comment by DanTup** [comment]
@christopherfujino if you're happy with this, feel free to merge / add autosubmit :-)

**Review by eyebrowsoffire — APPROVED** [review]
LGTM!

**Comment by eyebrowsoffire** [comment]
(@christopherfujino is out at a conference right now, so I'll go ahead and merge)

**Comment by DanTup** [comment]
Thanks!

**Pull request merged**
