### PR TITLE
Web: treat modifier key without location

### PR DESCRIPTION
**Pull request by moko256**
On Chromium on Windows, the event of Shift, Control, Alt, and Meta key may have no location (e.g. #97582).
This PR treats their keys and map to synonym.

Will fix the part of #97582.

No changes in `flutter/tests`.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Comment by dkwingsmt** [comment]
Do you mean their `location` field might be 0? In that case I think it's better to give them XxxLeft. The unsided modifiers are synonyms only and will removedi the future.

Also can you add tests?

**Comment by moko256** [comment]
I replaced synonym keys with left keys.
I added the test in flutter/engine#31550, that uses generated `key_map.dart` from this changes.

**Comment by dkwingsmt** [comment]
The change looks great, but can you add a test where a `RawKeyEventDataWeb` for modifier location 0 results in the correct key? Thank you.

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Comment by dkwingsmt** [comment]
@mdebbar Can you make a second review?

**Review by mdebbar — APPROVED** [review]
LGTM!

**Comment by dkwingsmt** [comment]
Can you try rebasing this PR against the latest master?

**Pull request merged**
