### PR TITLE
Add null safety note to flutter create

### LINKED ISSUE #67447: Default app template has errors when used with null safety
## Repro steps:

1. `flutter create foobar`
1. Add a new file `analysis_options.yaml` containing:
   ```
   analyzer:
     enable-experiment:
       - non-nullable
   ```
1. Edit `pubspec.yaml` to change `sdk: ">=2.7.0 <3.0.0"` to `sdk: ">=2.11.0-0.0 <3.0.0"`
1. Run `flutter analyze --enable-experiment=non-nullable`

**Expected result**: no errors

**Actual result**: Three errors

```
  error • The parameter 'key' can't have a value of 'null' because of its type, and no non-null default value is
         provided • lib/main.dart:31:19 • missing_default_value_for_parameter
  error • The parameter 'title' can't have a value of 'null' because of its type, and no non-null default value is
         provided • lib/main.dart:31:29 • missing_default_value_for_parameter
  error • An expression whose value can be 'null' must be null-checked before it can be dereferenced •
         lib/main.dart:101:22 • unchecked_use_of_nullable_value
```

## SDK version

```
mit-macbookpro4:tmp mit$ flutter --version
Flutter 1.23.0-8.0.pre.167 • channel master • https://github.com/flutter/flutter.git
Framework • revision f551178408 (11 hours ago) • 2020-10-06 11:36:50 +0200
Engine • revision 443cd5a1e1
Tools • Dart 2.11.0 (build 2.11.0-186.0.dev)
```

### PR DESCRIPTION
**Pull request by goderbauer**
Note added as per discussion in https://github.com/flutter/flutter/issues/67447#issuecomment-763151291.

Fixes https://github.com/flutter/flutter/issues/67447

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
Should we always suggest --apply-changes, or do we want users to get familiar with the web UI?

**Comment by goderbauer** [comment]
I think the idea here is to always `--apply-changes` since the freshly created template shouldn't have anything in it that requires manual intervention. Showing the UI is probably more confusing at this stage.

**Comment by mit-mit** [comment]
I was debating that with myself. I guess if you have a brand new template, you might as well skip the migration preview UI. And given we're printing it here during create, maybe that is a safe assumption?

**Comment by jonahwilliams** [comment]
Makes sense, LGTM

**Review by mit-mit — APPROVED** [review]

**Pull request merged**
