### PR TITLE
[flutter roll] Revert "[reland] Add Material 3 support for `ListTile` - Part 1"

### PR DESCRIPTION
**Pull request by XilaiZhang**
Reverts flutter/flutter#116963.

context: https://b.corp.google.com/issues/262687159.
Reported by internal customer as breaking scubas

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
RSLGTM, have you tested if this was the root cause of the broken scuba?

**Comment by XilaiZhang** [comment]
Ah i haven't. Good point, will run more thorough tests to verify.

**Comment by XilaiZhang** [comment]
yep reproduced in cl/498305206 and verified that it is the cause of the list tile changes in scubas. updated reproduced test link in https://b.corp.google.com/issues/262687159. merging

**Comment by esouthren** [comment]
FYI - this issue seems to be related to `ListTiles` within` PopupMenu`s - the docs in `popup_menu` advise using list tiles as children, but since M3 list tiles now have a `surface` color, I think we're getting an undesired mismatch between the elevation tint of the menu container and no elevation tinting on the list tile.

**Comment by TahaTesser** [comment]
Thanks for the details. @esouthren

**Comment by TahaTesser** [comment]
https://github.com/flutter/flutter/pull/117965 will land with the fix and other M3 updates for `ListTile`.

**Pull request merged**
