### PR TITLE
test engine roll for 23582159af46fe219bcf4da7ad894865ff7b3f91

### PR DESCRIPTION
**Pull request by flar**
Test engine roll, do not merge.

### CODE REVIEW

**Comment by flar** [comment]
@ditman

**Comment by ditman** [comment]
I suspect the way the flutter_test attempts to interact with some of the tests broke in my branch, looking at this!

**Comment by flar** [comment]
@ditman go ahead and close this when you're done with your investigations...

**Comment by ditman** [comment]
Closing this, we found the issue. Thanks @flar!

**Pull request closed without merging**
