### PR TITLE
Fixing richMessage gesture recognizer in tooltip widget

### PR DESCRIPTION
**Pull request by mhbdev**
Fixing #126206 and #113388 issues

*The IgnorePointer is preventing the richMessage touch events being recognized. Just removing that from*

*Solves #126206 and #113388*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by mhbdev** [comment]
> Looks like this is failing our checks. Can you please take another look at those? Thanks!

I haven't changed anything big and I can't understand what checks are telling and how to pass them.

**Comment by goderbauer** [comment]
If you click through the checks, you will see that one test is failing:

```
02:18 +2024 ~2: /b/s/w/ir/x/w/flutter/packages/flutter/test/material/tooltip_test.dart: Tooltip should not ignore users tap on richMessage                                                             
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
Finder specifies a widget that would not receive pointer events.
A call to tap() with finder "exactly one widget with type "GestureDetector" (ignoring offstage
widgets): GestureDetector(startBehavior: start, dependencies: [MediaQuery])" derived an Offset
(Offset(400.0, 300.0)) that would not hit test on the specified widget.
Maybe the widget is actually off-screen, or another widget is obscuring it, or the widget cannot
receive pointer events.
The finder corresponds to this RenderBox: RenderSemanticsGestureHandler#a6f62(creator: _GestureSemantics ← RawGestureDetector ← GestureDetector ← Semantics ← Builder ← RepaintBoundary-[GlobalKey#b817f] ← IgnorePointer ← AnimatedBuilder ← SnapshotWidget ← _ZoomExitTransition ← SnapshotWidget ← _ZoomEnterTransition ← ⋯, parentData: <none> (can use size), constraints: BoxConstraints(w=800.0, h=600.0), semantics node: SemanticsNode#4, size: Size(800.0, 600.0), behavior: deferToChild, gestures: [tap])
The hit test result at that offset is: HitTestResult(RenderMouseRegion#9b34a@Offset(400.0, 300.0),
RenderSemanticsAnnotations#57df0@Offset(400.0, 300.0), RenderPointerListener#5eb56@Offset(400.0,
300.0), RenderSemanticsGestureHandler#6d0ae@Offset(400.0, 300.0),
RenderExcludeSemantics#403f1@Offset(400.0, 300.0), RenderBlockSemantics#ba5ca@Offset(400.0, 300.0),
RenderIgnorePointer#49206@Offset(400.0, 300.0), _RenderTheater#901e9@Offset(400.0, 300.0),
RenderAbsorbPointer#d4913@Offset(400.0, 300.0), RenderPointerListener#f23fc@Offset(400.0, 300.0),
RenderSemanticsAnnotations#8db40@Offset(400.0, 300.0), RenderCustomPaint#cffb7@Offset(400.0, 300.0),
RenderSemanticsAnnotations#58104@Offset(400.0, 300.0),
RenderSemanticsAnnotations#7f5c8@Offset(400.0, 300.0), RenderTapRegionSurface#b2f34@Offset(400.0,
300.0), RenderSemanticsAnnotations#68ef4@Offset(400.0, 300.0),
RenderSemanticsAnnotations#fc829@Offset(400.0, 300.0),
RenderSemanticsAnnotations#400a9@Offset(400.0, 300.0),
HitTestEntry<HitTestTarget>#db214(RenderView#eb58b),
HitTestEntry<HitTestTarget>#7f279(<AutomatedTestWidgetsFlutterBinding>))
If you expected this target not to be able to receive pointer events, pass "warnIfMissed: false" to
"tap()".
To make this error into a non-fatal warning, set WidgetController.hitTestWarningShouldBeFatal to
false.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1328:11)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1232:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:554:18)
#3      main.<anonymous closure> (file:///b/s/w/ir/x/w/flutter/packages/flutter/test/material/tooltip_test.dart:1929:18)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Tooltip should not ignore users tap on richMessage
════════════════════════════════════════════════════════════════════════════════════════════════════

02:18 +2024 ~2 -1: /b/s/w/ir/x/w/flutter/packages/flutter/test/material/tooltip_test.dart: Tooltip should not ignore users tap on richMessage [E]                                                      
  Test failed. See exception logs above.
  The test description was: Tooltip should not ignore users tap on richMessage
```

There is also a formatting issue:

```
▌07:49:13▐ Trailing spaces...
╔═╡ERROR╞═══════════════════════════════════════════════════════════════════════
║ /b/s/w/ir/x/w/Á flutter sdk/packages/flutter/test/material/tooltip_test.dart:1909: trailing U+0020 space character
╚═══════════════════════════════════════════════════════════════════════════════
```

**Comment by mhbdev** [comment]
> Looks like this is failing our checks. Can you please take another look at those? Thanks!

All checks have passed.

**Comment by mhbdev** [comment]
Good day @goderbauer. Would it be possible for you to spare some time to review my pull request? I would greatly appreciate your valuable feedback. Thank you very much for your kind assistance.

**Comment by goderbauer** [comment]
I did some digging and wasn't able to find a reason why we wrapped the Tooltip with an IgnorePointer in the first place. Also looks like all tests are still passing, so I guess removing it is ok.

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by chunhtai — APPROVED** [review]
LGTM

**Pull request merged**
