### PR TITLE
[ci.yaml] Nest tags under properties

### PR DESCRIPTION
**Pull request by CaseyHillers**
This reduces the bloat of the ci.yaml

https://github.com/flutter/flutter/issues/84998

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by CaseyHillers** [comment]
\cc @chunhtai @christopherfujino @keyonghan here's a demo of moving the tags to be a property. This makes the ci.yaml a bit cleaner, but adds an extra jsonDecode to Cocoon. Would this work for the flaky issue tracking?

**Comment by chunhtai** [comment]
For flaky issue tracking this is fine, but can this be extended to key value pair in the future if we need it?

**Comment by christopherfujino** [comment]
> For flaky issue tracking this is fine, but can this be extended to key value pair in the future if we need it?

The entire `tags` field will be a string that can be parsed as JSON. This has the advantage that you can include whatever types of values you like in this field. The disadvantage is that the `ci.yaml validation` won't validate the schema of the `tags` field.

**Comment by chunhtai** [comment]
I can work with any format since my use case is simple enough, I will leave the decision to @keyonghan

**Comment by CaseyHillers** [comment]
> The entire tags field will be a string that can be parsed as JSON. This has the advantage that you can include whatever types of values you like in this field. The disadvantage is that the ci.yaml validation won't validate the schema of the tags field.

We can add this to the ci_yaml validation (special case properties[tags] and validate it is a json list). However, you're reducing the flexibility of the properties as you need to support release branches.

**Comment by keyonghan** [comment]
This LGTM. We control how to promote the tags to build tags. From flaky side, we only need a way to label a test/builder.

**Review by keyonghan — APPROVED** [review]
LGTM.

**Pull request merged**
