### PR TITLE
Finish integrating HelloServices model on iOS

### PR DESCRIPTION
**Pull request by abarth**
This patch changes the default `flutter create` command to generate a
HelloServices-style app on iOS. As a consequence, the Atom integration now
fully works with HelloServices.

### CODE REVIEW

**Comment by abarth** [comment]
@collinjackson @chinmaygarde @devoncarew

**Comment by chinmaygarde** [comment]
lgtm

**Comment by tvolkert** [comment]
LGTM

**Comment by devoncarew** [comment]
lgtm

> As a consequence, the Atom integration now fully works with HelloServices.

For iOS I assume?

**Comment by abarth** [comment]
Yes, just for iOS.  "fully" is a bit of an overstatement.  :)

**Pull request merged**
