### PR TITLE
Flutter Web Driver Support

### PR DESCRIPTION
**Pull request by angjieli**
This PR adds support for Flutter Web Driver Testing.
In order to execute Flutter Web Driver tests, you need to have Selenium Server and WebDriver binary installed.

Steps to test:

Have Selenium server (https://bit.ly/2TlkRyu) and WebDriver binary (https://chromedriver.chromium.org/downloads) downloaded and placed under the same folder
Launch WebDriver Server: java -jar selenium-server-standalone-3.141.59.jar
Launch Flutter Web application: flutter run -v -d chrome --target=test_driver/scroll_perf_web.dart
Run test script: flutter drive --target=test_driver/scroll_perf.dart -v --use-existing-app=/application address/
There are certain limitations:

getVMFlags(), forceGC() and waitUntilFirstFrameRasterized() are not implemented because they are not applicable to Flutter Web platform. For waitUntilFirstFrameRasterized, there might be a equivalent event that we can leverage.
TimelineSummary.summarize().writeSummaryToFile() does not work.
Tests
I added the following tests:

examples/flutter_gallery/test_driver/scroll_perf_web_test.dart
This will test some basic behavior using Flutter Web Driver.
## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Can you also ensure https://github.com/flutter/flutter/pulls/jonahwilliams is patched in?

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by fkorotkov** [comment]
@angjieli I think this change breaks some testing in plugins. The e2e test uses `serviceClient`: https://github.com/flutter/plugins/blob/master/packages/android_alarm_manager/example/test_driver/android_alarm_manager_e2e_test.dart#L13

Found it while trying to upgrade Xcode version for plugins repository https://github.com/flutter/plugins/pull/2435

**Comment by angjieli** [comment]
@fkorotkov Thanks for letting me know. I will fix this shortly.

**Comment by franciscojma86** [comment]
@angjieli should we revert this in the meantime?

**Comment by franciscojma86** [comment]
Discused offline with @angjieli . I'll revert for now

**Pull request merged**
