### PR TITLE
Add a timeout to the microbenchmarks process.

### PR DESCRIPTION
**Pull request by godofredoc**
This is to ensure the process does not run for the maximum task timeout
making it fail with an infra failure.

Bug:  https://github.com/flutter/flutter/issues/76163

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jmagman — COMMENTED** [review]
60 seconds isn't long enough for this call (it's going to flake for sure), and we've removed individual timeouts like this from other tests

This seems like a larger problem--the entire test suite should fail with a timeout shorter than the recipe limit?

**Comment by godofredoc** [comment]
> 60 seconds isn't long enough for this call (it's going to flake for sure), and we've removed individual timeouts like this from other tests
> 
> This seems like a larger problem--the entire test suite should fail with a timeout shorter than the recipe limit?

I thought we already had a global timeout but I could not find it, can you please point me to an example that I can reuse?

**Comment by jonahwilliams** [comment]
The devicelab tests used to have 15 minute timeouts, but I believe those were removed. I agree that 60 seconds is probably much too quick for this particular test

**Comment by godofredoc** [comment]
Abandoning this in favor of a global test step timeout: https://flutter-review.googlesource.com/c/recipes/+/12020

**Pull request closed without merging**
