### PR TITLE
Add --start-paused doc

### PR DESCRIPTION
**Pull request by xster**
#7844

### CODE REVIEW

**Review by LarkAscending — COMMENTED** [review]
LGTM, but would like @Hixie  to take a look since he added the syntax.

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
It actually prevents the test from even starting, technically. It starts the VM in a paused state and awaits a connection from a debugger (which must then resume the test for it to run). This lets you set breakpoints before the test runs.

**Comment by xster** [comment]
Thanks for the corrections Elaine!

**Pull request merged**
