### PR TITLE
Added should rebuild callback to ValueListenableBuilder

### PR DESCRIPTION
**Pull request by Kavantix**
## Description

Added should rebuild callback to ValueListenableBuilder
Makes it easier to write performant flutter code using the ValueListenableBuilder, similar purpose to the selector of the provider package

## Related Issues

None as far as I know

## Tests

I added the following tests:

Check whether shouldRebuild is called
Checks for whether shouldRebuild is honored

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by goderbauer** [comment]
What is the motivation for this change? This seems a little out because the purpose of the ValueListenableBuilder is to always keep the widget in sync with the value listenable. Now what's shown in the widget would depend on the history of the valuelinstenable?

If you don't want to rebuild, just wrap your valuelistenable in a valuelistenable that only fires for the value changes you want to rebuild on, maybe?

**Comment by Kavantix** [comment]
The motivation is that this allows for more control on the users side of the valuelistenable.
For instance, with your suggestion the code that provides the valuelistenable needs to change if any of its users want to do something special with it.
A good example is having a valuelistenable of a list, some users might care about the list changing to a new list but others might just care about whether the length stays the same.
So this change just gives some extra tools to make it simpler to optimize out rebuilds that are not needed By basically allowing you to override the equality comparison of the values on the using side.

**Comment by goderbauer** [comment]
With this change the code that uses the ValueListanableBuilder still has to change to provide that additional callback. Instead of doing that, it could just wrap the provided ValueListenable in another one that implements that functionality without adding another flag to this widget.

I am currently not seeing the value right now for this to be part of the framework. If you really, really wanted this you could also just copy the implementation of the ValueListanableBuilder into your code and add it there. The implementation is rather simple.

**Comment by Kavantix** [comment]
Hmm I understand your point now.

Do you think it would make sense to add a valuelistenable class that listens to another and implements the behaviour of this PR?
Because my main objective of this is making it easier to optimize the number of rebuilds without everyone needing to make something like this from scratch.

**Comment by goderbauer** [comment]
> Because my main objective of this is making it easier to optimize the number of rebuilds without everyone needing to make something like this from scratch.

I would recommend publishing it as a separate pub package then. People can use it without needing to re-invent the wheel.

**Pull request closed without merging**
