### PR TITLE
Try re-enabling all these tests.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
cc @jonahwilliams

**Comment by jonahwilliams** [comment]
FYI, https://github.com/flutter/flutter/issues/46142

The mitigation landed Thursday/Friday but there are still some skipped create_test.dart. I was planning to take a look at those today, so if you can land these fixes that would be great!

**Comment by Hixie** [comment]
Yeah, I saw that. Haven't had the time to look at the create_test ones, but I was familiar with these so I figured i'd do them.

**Comment by Hixie** [comment]
Looks like the tests pass reliably, so it's ready for review.

**Review by jonahwilliams — APPROVED** [review]
changes to expectation files seem innocuous 

LGTM

**Pull request merged**
