### PR TITLE
migrate host_agent to null safety

### PR DESCRIPTION
**Pull request by Abhishek01039**
Migrate host_agent to null safety

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Abhishek01039** [comment]
Hello @jmagman 
can you please review this PR?
Thanks

**Comment by Abhishek01039** [comment]
Hello @jmagman
can you please review this PR?
Thanks

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by Abhishek01039** [comment]
Hello @jmagman 
Good morning
Thank you for accepting my many PRs.

I need your help.

I have pushed more than 70 PRs in the flutter/flutter repo and I have several PRs in flutter/plugin, flutter/engine, and flutter/packages as well.

so can you please take sponsorship for my contributor access in github?

thank you!

**Comment by Abhishek01039** [comment]
Hello @jmagman
Good morning
Thank you for accepting my many PRs.

I need your help.

I have pushed more than 70 PRs in the flutter/flutter repo and I have several PRs in flutter/plugin, flutter/engine, flutter/website, dart-lang/site-www and flutter/packages as well, I am also willing to make more contributions.

so can you please take sponsorship for my contributor access in GitHub?

thank you!

**Comment by jmagman** [comment]
@Abhishek01039 Thank you for all your contributions!  You've been very helpful, particularly getting the repo migrated to null safety.

As for sponsoring contributor access I'm looking for:
1. A great attitude and respect Flutter's [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md).  You definitely have that! 😃 
2. Self reliance.  At the moment I think you still need a lot of help and code suggestions on your reviews.  We're happy to provide that help, but it's critical that contributors minimize the amount of work for reviewers--it can sometimes take more time and energy to thoroughly review than it does to just fix a bug!
https://github.com/flutter/flutter/pull/82611
https://github.com/flutter/flutter/pull/80624
https://github.com/flutter/flutter/pull/84064
https://github.com/flutter/flutter/pull/83177
https://github.com/flutter/flutter/pull/82084

3. Ability to track down and solve the subtle and inevitable bugs resulting from your changes.  Working on a large codebase with many users and many contributors is complicated with many moving parts.
 https://github.com/flutter/flutter/pull/81629#issuecomment-842594789
https://github.com/flutter/flutter/pull/84029#issuecomment-864163713

I think you still may need to some work on numbers 2 and 3.  That being said, we're happy to provide help, and your enthusiasm and contributions are greatly appreciated! 🙂

**Comment by Abhishek01039** [comment]
Yes @jmagman you are right
but for 3rd concern is that the logs which are given by CI it's very difficult to understand.

**Pull request merged**
