### PR TITLE
Add Checkbox checkIcon color parameter

### PR DESCRIPTION
**Pull request by H3r3zy**
For my work, I had to make a Checkbox where the color of the icon had to be black.

I looked at the code of the current Checkbox and I realized that the color was hard coded.

So I'm doing this PR to correct this.

This image is a preview of what i have done.
pr

### CODE REVIEW

**Comment by H3r3zy** [comment]
I signed it!

**Comment by H3r3zy** [comment]
For the Checkbox:
- Add a "checkColor" argument to allow the change of check Icon color.

For the DropdownButton
- Add a static builder function to generate the DropdownMenuItem list to create the DropdownButton

**Comment by johrpan** [comment]
I was about to raise an issue about the checkbox tick color, so I'm happy to see this. But it should be possible to set this via the theme.

**Review by HansMuller — COMMENTED** [review]
Support for overriding the default checkmark color seems like a reasonable feature to add.

Generally speaking:
- The PR's description should:
-- Describe what's being changed and why.
-- List the existing issues that the PR fixes.
-- If the PR introduces visual changes, before and after screenshots should be included. If possible, it's helpful to crop full-screen screenshots to highlight the changes.
- The changes introduced by the PR should defend against regressions with tests.
- If the changes fix an issue, then a regression test that's specific to the issue should be included.

The handy DropdownButton.builder() method looks useful but we're not accepting changes like that at the moment.

**Comment by H3r3zy** [comment]
Hello @HansMuller, thanks for the review.

I edited my Pr's description and merge my fork with flutter/master ;)

Have a good day

**Comment by HansMuller** [comment]
All that's needed to finish this PR is a test. Something like the last test in checkbox_test.dart: 'CheckBox tristate rendering, programmatic transitions'.

In this case you'd just need to check the colors of the path/line being rendered with expressions like `paints..path(color: const Color(0xFFFFFFFF))` etc.

**Comment by H3r3zy** [comment]
Hi @HansMuller,
It's ok, I just pushed them.

**Comment by HansMuller** [comment]
Nicely done, LGTM. I'll land this now.

**Pull request merged**
