### PR TITLE
Rename platform_services to platform_channel

### PR DESCRIPTION
**Pull request by szakarias**

### CODE REVIEW

**Review by jakobr-google — APPROVED** [review]
LGTM.

We should get rid of android/buildSrc/build.gradle, and change the app ID in android/app/src/main/AndroidManifest.xml to match the iOS app ID (and avoid clashes on com.example.flutter). But that can be another CL.

**Comment by greenflute** [comment]
FYI: The module definition file "platform_services.iml" was not renamed yet, or just forgot to delete it.

**Comment by mit-mit** [comment]
Thanks @greenflute, would you mind opening an issue so we can get that fixed?

**Comment by mit-mit** [comment]
@greenflute that was resolved in https://github.com/flutter/flutter/pull/9101

**Pull request merged**
