### PR TITLE
removed user message class

### LINKED ISSUE #125155: [flutter_tools] Use of `UserMessages` is sporadic
The tool has a [`UserMessages` class](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/user_messages.dart) that houses some user messages displayed to the user by the flutter tool. However, _many_ messages are not stored in this class ([example](https://github.com/flutter/flutter/blob/68ec71f46c0a1210593cbcb34b1a7001d07a43c4/packages/flutter_tools/lib/src/android/android_studio.dart#L503-L504)).

Going back to the PR that introduced it, it's still unclear what the original intent was. See [this comment from @Hixie on the PR](https://github.com/flutter/flutter/pull/23889#issuecomment-448807150).

The class does allow partial reimplementations of the flutter tool to override messages, and it sees very light use in g3. However, it is unclear if this is worth the confusion this class can cause.

Some possible ways to address this:
* Delete the class entirely, either removing the g3 message overrides entirely or finding some other way to enable g3 specific messages.
* Rename and document the class to better describe it's specific purpose. Perhaps the class should only contain messages that need to be overridden in g3.
* Be consistent and have _all_ user messages stored in this class. This would probably result in more trouble than it's worth.

### PR DESCRIPTION
**Pull request by andoriyaprashant**
Removed user message class 
fixes #125155 

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by eliasyishak** [comment]
Same message as https://github.com/flutter/flutter/pull/125098#issuecomment-1516887811

**Review by andrewkolos — CHANGES_REQUESTED** [review]
Thanks for the PR!

Several checks are failing, because many files still reference this class. If we want to remove this class, we'll have to move all the messages out of this class to the place where they are used.

To see the output of a specific check that's failing, go to the Checks tab, select a failing check, click the "View more details on flutter-dashboard" link, and click the "stdout" link under the failed step.

Here's an example of some logs: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8783239552938998977/+/u/prepare_environment/flutter_config_--no-analytics/stdout

**Comment by andoriyaprashant** [comment]
hey @andrewkolos thanks for the review
I make changes in these files -

1.  modified:   packages/flutter_tools/lib/src/android/android_workflow.dart

Screenshot 2023-04-23 002135
Screenshot 2023-04-23 002150

2.  modified:   packages/flutter_tools/lib/src/cache.dart
Screenshot 2023-04-23 002201

3.  modified:   packages/flutter_tools/lib/src/doctor.dart
Screenshot 2023-04-23 002222
Screenshot 2023-04-23 002231
Screenshot 2023-04-23 002244

4. modified:   packages/flutter_tools/lib/src/globals.dart
Screenshot 2023-04-23 002308

can i commit these changes?
or i have to add more changes in the code

**Comment by TzviPM** [comment]
I don't think this is the right way to move forward on #125155. See my comments in the issue.

**Comment by christopherfujino** [comment]
I'm sorry, but I don't think we are yet ready to delete this class. I think we need more discussion on the tracking issue about the right approach (it is still unclear to me about the right way to get rid of this class). Thanks for your contribution, and I'm sorry that we were not able to accept it at this time.

**Pull request closed without merging**
