### PR TITLE
Revert "Keep LLDB connection to iOS device alive while running from CLI."

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#35731

### CODE REVIEW

**Comment by jonahwilliams** [comment]
TBR @sjindel-google @tvolkert

**Comment by sjindel-google** [comment]
What was the reason for revert?

**Comment by jonahwilliams** [comment]
From the devicelab logs:

```
2019-07-11T10:12:49.437804: stdout: [        ] Debugging is enabled, connecting to observatory
2019-07-11T10:12:49.441478: stdout: [   +4 ms] executing: /usr/bin/env ios-deploy --id a39e0f27133602be01f30a2fd1b4385f7952fce0 --bundle build/ios/iphoneos/Runner.app --no-wifi --no-interactive --args --enable-dart-profiling --start-paused --enable-checked-mode --verify-entry-points --trace-startup
2019-07-11T10:12:49.460591: stderr: [  +19 ms] ios-deploy: unrecognized option `--no-interactive'
2019-07-11T10:12:49.460880: stderr: [        ] 2019-07-11 10:12:49.458 ios-deploy[73480:76348849] Usage: ios-deploy [OPTION]...
2019-07-11T10:12:49.461108: stderr: [        ]   -d, --debug                  launch the app in lldb after installation
2019-07-11T10:12:49.461376: stderr: [        ]   -i, --id          the id of the device to connect to
2019-07-11T10:12:49.461601: stderr: [        ]   -c, --detect                 only detect if the device is connected
2019-07-11T10:12:49.461873: stderr: [        ]   -b, --bundle     the path to the app bundle to be installed
2019-07-11T10:12:49.462164: stderr: [        ]   -a, --args             command line arguments to pass to the app when launching it
2019-07-11T10:12:49.462392: stderr: [        ]   -t, --timeout       number of seconds to wait for a device to be connected
2019-07-11T10:12:49.462648: stderr: [        ]   -u, --unbuffered             don't buffer stdout
2019-07-11T10:12:49.462876: stderr: [        ]   -n, --nostart                do not start the app when debugging
2019-07-11T10:12:49.463142: stderr: [        ]   -N, --nolldb                 start debugserver only. do not run lldb
2019-07-11T10:12:49.463365: stderr: [        ]   -I, --noninteractive         start in non interactive mode (quit when app crashes or exits)
2019-07-11T10:12:49.463639: stderr: [        ]   -L, --justlaunch             just launch the app and exit lldb
2019-07-11T10:12:49.463841: stderr: [        ]   -v, --verbose                enable verbose output
2019-07-11T10:12:49.464118: stderr: [        ]   -m, --noinstall              directly start debugging without app install (-d not required)
2019-07-11T10:12:49.464366: stderr: [        ]   -p, --port           port used for device, default: dynamic
2019-07-11T10:12:49.464641: stderr: [        ]   -r, --uninstall              uninstall the app before install (do not use with -m; app cache and data are cleared) 
2019-07-11T10:12:49.464864: stderr: [        ]   -9, --uninstall_only         uninstall the app ONLY. Use only with -1  
2019-07-11T10:12:49.465128: stderr: [        ]   -1, --bundle_id   specify bundle id for list and upload
2019-07-11T10:12:49.465402: stderr: [        ]   -l, --list                   list files
2019-07-11T10:12:49.465666: stderr: [        ]   -o, --upload           upload file
2019-07-11T10:12:49.465865: stderr: [        ]   -w, --download               download app tree
2019-07-11T10:12:49.466139: stderr: [        ]   -2, --to    use together with up/download file/tree. specify target
2019-07-11T10:12:49.466416: stderr: [        ]   -D, --mkdir 
            make directory on device
2019-07-11T10:12:49.466728: stderr: [        ]   -R, --rm               remove file or directory on device (directories must be empty)
2019-07-11T10:12:49.466986: stderr: [        ]   -V, --version                print the executable version 
2019-07-11T10:12:49.467328: stderr: [        ]   -e, --exists                 check if the app with given bundle_id is installed or not 
2019-07-11T10:12:49.467560: stderr: [        ]   -B, --list_bundle_id         list bundle_id 
2019-07-11T10:12:49.467873: stderr: [        ]   -W, --no-wifi                ignore wifi devices
2019-07-11T10:12:49.468258: stderr: [        ]   --detect_deadlocks      start printing backtraces for all threads periodically after specific amount of seconds
2019-07-11T10:12:49.471025: stdout: [   +2 ms] Failed to launch the application on device.
2019-07-11T10:12:49.473434: stdout: [   +2 ms] Installing and launching... (completed in 0.0s)
2019-07-11T10:12:49.473712: stderr: [        ] Could not install build/ios/iphoneos/Runner.app on a39e0f27133602be01f30a2fd1b4385f7952fce0.
2019-07-11T10:12:49.473984: stderr: [        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
2019-07-11T10:12:49.474262: stderr: [        ]   open ios/Runner.xcworkspace
2019-07-11T10:12:49.481756: stdout: [   +7 ms] "flutter drive" took 65,924ms.
2019-07-11T10:12:49.481951: stdout: [        ] "flutter drive" took 65,924ms.
2019-07-11T10:12:49.488811: stderr: Application failed to start. Will not run test. Quitting.
```

It looks like that flag requires a particular version of ios-deploy? If that is the case we'll need to wait until @christopherfujino lands the iOS artifact change

**Comment by christopherfujino** [comment]
@sjindel-google I landed the iOS artifact change [here](https://github.com/flutter/flutter/pull/36093), which locks in the version of ios-deploy the flutter tool will use.

**Comment by sjindel-google** [comment]
Thanks @christopherfujino -- it turned out to just be a typo in the flag name though

**Pull request merged**
