### PR TITLE
Roll Dart to 45f9462398ae7d2e80acd79d3f9c32c7ca6f6f97

### PR DESCRIPTION
**Pull request by aartbik**

### CODE REVIEW

**Comment by aartbik** [comment]
Previous one went through without any presubmit check. The hash had probably not been fully built yet. Retrying.

**Review by liyuqian — APPROVED** [review]
LGTM but it's still not built yet. You can check the build status on https://build.chromium.org/p/client.flutter/console

**Comment by jason-simmons** [comment]
The buildbots skipped the engine commit in this roll.

The next engine commit that has an uploaded build is https://github.com/flutter/engine/commit/739d66eeb3f8777f3e28d3e635a5f691a0f1a16b

**Comment by aartbik** [comment]
rebased to 739d66eeb3f8777f3e28d3e635a5f691a0f1a16b (latter of all)

**Comment by dnfield** [comment]
This one is failing becuase of changes to locale handling that were later reverted.

With that reversion, we're getting other failures: https://github.com/flutter/flutter/pull/23328

**Comment by aartbik** [comment]
Is the locale handling going to be fixed? We have been trying to get the Dart roll in for a long time now.

@jason-simmons @a-siva

**Comment by dnfield** [comment]
@aartbik it's been reverted, but the flutter tool tests now fail with the new Dart VM roll.. See the errors on #23328, which contains this commit plus the locale revert.

**Comment by aam** [comment]
Those failing tests started to fail from https://dart-review.googlesource.com/c/78246 point on where we started to resolve file uri to `package:` uri.

Below fixes the tests:
```
diff --git a/packages/flutter_tools/test/integration/expression_evaluation_test.dart b/packages/flutter_tools/test/integration/expression_evaluation_test.dart
index e594f2ac3..0a81ed05a 100644
--- a/packages/flutter_tools/test/integration/expression_evaluation_test.dart
+++ b/packages/flutter_tools/test/integration/expression_evaluation_test.dart
@@ -33,13 +33,13 @@ void main() {
 
     Future<VMIsolate> breakInBuildMethod(FlutterTestDriver flutter) async {
       return _flutter.breakAt(
-          Uri.file(_project.buildMethodBreakpointFile),
+          Uri.parse("package:test/main.dart"),
           _project.buildMethodBreakpointLine);
     }
 
     Future<VMIsolate> breakInTopLevelFunction(FlutterTestDriver flutter) async {
       return _flutter.breakAt(
-          Uri.file(_project.topLevelFunctionBreakpointFile),
+          Uri.parse("package:test/main.dart"),
           _project.topLevelFunctionBreakpointLine);
     }
 
diff --git a/packages/flutter_tools/test/integration/hot_reload_test.dart b/packages/flutter_tools/test/integration/hot_reload_test.dart
index 3abe5c380..0c059cff6 100644
--- a/packages/flutter_tools/test/integration/hot_reload_test.dart
+++ b/packages/flutter_tools/test/integration/hot_reload_test.dart
@@ -41,7 +41,7 @@ void main() {
     test('reload hits breakpoints after reload', () async {
       await _flutter.run(withDebugger: true);
       final VMIsolate isolate = await _flutter.breakAt(
-          Uri.file(_project.breakpointFile),
+          Uri.parse("package:test/main.dart"),
           _project.breakpointLine);
       expect(isolate.pauseEvent, isInstanceOf<VMPauseBreakpointEvent>());
     });
```

**Comment by aam** [comment]
Those failing tests started to fail from https://dart-review.googlesource.com/c/78246 point on where we started to resolve file uri to `package:` uri.

Below fixes the tests:
```
diff --git a/packages/flutter_tools/test/integration/expression_evaluation_test.dart b/packages/flutter_tools/test/integration/expression_evaluation_test.dart
index e594f2ac3..0a81ed05a 100644
--- a/packages/flutter_tools/test/integration/expression_evaluation_test.dart
+++ b/packages/flutter_tools/test/integration/expression_evaluation_test.dart
@@ -33,13 +33,13 @@ void main() {
 
     Future<VMIsolate> breakInBuildMethod(FlutterTestDriver flutter) async {
       return _flutter.breakAt(
-          Uri.file(_project.buildMethodBreakpointFile),
+          Uri.parse("package:test/main.dart"),
           _project.buildMethodBreakpointLine);
     }
 
     Future<VMIsolate> breakInTopLevelFunction(FlutterTestDriver flutter) async {
       return _flutter.breakAt(
-          Uri.file(_project.topLevelFunctionBreakpointFile),
+          Uri.parse("package:test/main.dart"),
           _project.topLevelFunctionBreakpointLine);
     }
 
diff --git a/packages/flutter_tools/test/integration/hot_reload_test.dart b/packages/flutter_tools/test/integration/hot_reload_test.dart
index 3abe5c380..0c059cff6 100644
--- a/packages/flutter_tools/test/integration/hot_reload_test.dart
+++ b/packages/flutter_tools/test/integration/hot_reload_test.dart
@@ -41,7 +41,7 @@ void main() {
     test('reload hits breakpoints after reload', () async {
       await _flutter.run(withDebugger: true);
       final VMIsolate isolate = await _flutter.breakAt(
-          Uri.file(_project.breakpointFile),
+          Uri.parse("package:test/main.dart"),
           _project.breakpointLine);
       expect(isolate.pauseEvent, isInstanceOf<VMPauseBreakpointEvent>());
     });
```

**Comment by aartbik** [comment]
Why is this all-green so quickly? It does not seem to have run the usual tests.....

**Comment by aartbik** [comment]
@jason-simmons is taking over from Dan trying to get this past the Dart roll.

**Comment by aartbik** [comment]
All taken care of by:

https://github.com/flutter/flutter/commit/a6a1607888d915d8b3d9b41ed985bf71d5ff5c78

**Pull request closed without merging**
