### PR TITLE
added notification that dispatches when user actually ends dragging in scrollable

### LINKED ISSUE #39929: NotificationListener with child as ListView not emittting ScrollEndNotification DragDetails properly
When I add child to a NotificationListener as ListView and when I am scrolling the list view several notifications are captured.one of them being ScrollEndNotification which has DragEndDetails parameter named as (dragDetails)

Now what happens is dragDetails is not null only at the ends of the list view. If I scroll by flinging the list view and the final location is in middle of the list view then dragDetails of scrollEndNotification instance is null. 

What I think is it is happening due to

> If a drag ends with some residual velocity, a typical ScrollPhysics will start a ballistic scroll, which delays the ScrollEndNotification until the ballistic simulation completes, at which time dragDetails will be null.

[https://api.flutter.dev/flutter/widgets/ScrollEndNotification/dragDetails.html](url)

- Now if this dragDetails are None how can I find actual DragEndDetails?

- Is there any method already available, or I have to make it my own and how can I make it?.

### Steps to Reproduce:
```
class MyListView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(itemCount:500,itemBuilder: (context, index) {
      return Text(index.toString());
    });
  }
}

class TemporaryTest extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _TemporaryTestState();
  }
}

class _TemporaryTestState extends State<TemporaryTest> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return NotificationListener(
      child: MyListView(),
      onNotification: (notification) {
        if (notification.runtimeType == ScrollEndNotification) {
          print((notification as ScrollEndNotification).dragDetails); //prints mostly null, only prints instance of DragEndDetails when either we are overscrolling at start or end, not in middle
        }
        return true;
      },
    );
  }
}

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body:TemporaryTest(),
    );
  }
}

```

### PR DESCRIPTION
**Pull request by nimishbansal**
## Description

I added `ScrollDragEndNotification` that will notify that the pointer is no longer in contact with the screen while dragging Scrollable i.e drag has been ended in `Scrollable` widget.
It is different from `ScrollEndNotification` since `ScrollEndNotification` is dispatched when scrolling has been ended whose dragDetails are null when drag residual velocity causes ballistic simulation that further delays `ScrollEndNotification` (scrolling continues even after flinging). With this PR we can detect that scroll drag has been ended with actual dragDetails before ballistic simulation.

Though in the case of over scrolling. `ScrollDragEndNotification` and` ScrollEndNotification `both will be fired immediately in succession with same dragDetails. 

Note : There will be no need for ScrollDragStartNotification, ScrollDragUpdateNotification since `ScrollStartNotification`, (`ScrollUpdateNotification` or `OverscrollNotification`) are actually providing the same functionality respectively.

#### Scrolling in middle
scrolling before `ScrollDragEndNotification`
beforeScrollDrag
scrolling after `ScrollDragEndNotification`
afterScrollDrag

#### Overscrolling
Overscrolling before `ScrollDragEndNotification`
OverscrollbeforeScrollDrag
Overscrolling after `ScrollDragEndNotification`
OverscrollAfterScrollDrag

## Related Issues
Resolves: https://github.com/flutter/flutter/issues/39929

## Tests

Modified the following tests:

- test/widgets/scroll_events_test.dart
- test/widgets/scroll_notification_test.dart
- test/widgets/scroll_view_test.dart

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and updated tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

@Hixie Sir any sugeestions?

### CODE REVIEW

**Review by dnfield — CHANGES_REQUESTED** [review]
Please look into the analysis issues - looks like you may have trailing whitespace to fix.

**Comment by dnfield** [comment]
You still have some whitespace left at the end of some lines in your file.  FWIW, your IDE may have a setting to automatically remove this for you :)

**Comment by nimishbansal** [comment]
Hopefully this time, I won't disappoint you  :-)

**Review by dnfield — APPROVED** [review]
I think this looks good, but would appreciate a sanity check from @goderbauer

**Comment by goderbauer** [comment]
Before we add a new API (here in from of a new ScrollNotification) I would like to know what the actual use case for this is. I've asked that question on the linked issue: https://github.com/flutter/flutter/issues/39929#issuecomment-529694961

**Comment by dnfield** [comment]
Going to close this - the use case known for it currently is resolved by using custom scroll physics instead

**Pull request closed without merging**
