### PR TITLE
Patch Debug/Release.xcconfig files when running devicelab tests

### PR DESCRIPTION
**Pull request by szakarias**
`Flutter create` now creates ios/Flutter/Debug.xcconfig and ios/Flutter/Release.xcconfig and not ios/Flutter/Flutter.xcconfig, so in the new examples these are the files that need patching.

I have not been able to test this locally but it should fix the redness caused by basic_material_app_ios__size and flutter_view_ios__start_up .

We might consider changing the old examples to follow this structure so it matches what we get now when we run `flutter create` .

### CODE REVIEW

**Comment by cbracken** [comment]
Thank you! I think @yjbanov hit this last night as he was headed out the door, but it was already late. This is fantastic. 

LGTM

**Comment by cbracken** [comment]
I've got a patch to migrate all the examples; at some point I applied it but ended up rolling back. Mentioned to Yegor I'd do that today.

**Comment by szakarias** [comment]
Thanks, and that sounds great.

**Comment by yjbanov** [comment]
Ha-ha, nice! I had this exact change in the works but for some reason couldn't make the test pass due to some cocoapods stuckness.

**Comment by cbracken** [comment]
Maybe #8999, which Jakob has a PR out to significantly improve. The good news is this is a one-time setup step. Once it's been done the first time, this step is much speedier.

**Pull request merged**
