### PR TITLE
[new gallery] Reisze gallery images

### LINKED ISSUE #147797: [Impeller] slow frame in new gallery while navigating to travel application
image

Theories:
* Images are too big
* Too many images
* glyph atlas reconstruction is expensive and might be unnecessary (or could be allocation).

### PR DESCRIPTION
**Pull request by jonahwilliams**
Some cause of jank on both Skia and Impeller are these massive images. We should just resize them so that the noise is reduced and we can see other performance issues.

Fixes https://github.com/flutter/flutter/issues/147797

Tested: this is a test!

### CODE REVIEW

**Comment by matanlurey** [comment]
test-exempt: this _is_ a test.

**Review by matanlurey — APPROVED** [review]
Also, LGTM.

**Comment by gaaclarke** [comment]
This surprisingly had a negative effect on the worst raster time 🤷:

https://flutter-flutter-perf.skia.org/e/?keys=X88f7834493ddea4cad661bf2d18ae13d&selected=commit%3D40663%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DPixel_7_Pro%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253Dworst_frame_rasterizer_time_millis%252Ctest%253Dnew_gallery_impeller_old_zoom__transition_perf%252C&xbaroffset=40664

**Comment by jonahwilliams** [comment]
wrong benchmark!

**Pull request merged**
