### PR TITLE
Fix typo in form_row.dart

### PR DESCRIPTION
**Pull request by eltociear**
## Description

`accomodate` -> `accommodate`

## Related Issues

*Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR. There should be at least one issue listed here.*

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behavior with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Abhishek01039** [comment]
Hello @eltociear 
Are you still working on this?
Thanks

**Comment by eltociear** [comment]
@Abhishek01039 Thank you for contacting me!

This PR is comment typo fix. so I think don't needed test.
Should I tell it in chat?

**Comment by Abhishek01039** [comment]
Please rebase with the latest master.
so CI will be passed and you don't need a test as well.
@eltociear

**Comment by eltociear** [comment]
@Abhishek01039 Thank you! I'll try it!

**Comment by eltociear** [comment]
@Abhishek01039 Is this okay?

I tried below.
```
git remote add upstream https://github.com/flutter/flutter.git

git fetch upstream

git rebase master

git push -f
```

**Comment by Abhishek01039** [comment]
@eltociear Please try `git pull upsteam master`

**Comment by eltociear** [comment]
@Abhishek01039 I tried it.
return below.
```
$ git pull upstream master
From https://github.com/flutter/flutter
 * branch                  master     -> FETCH_HEAD
Already up to date.
```

**Comment by Abhishek01039** [comment]
Hello @eltociear 
Please revert your changes.

**Comment by jmagman** [comment]
I'm going to close this.  Try making your change on top of tree on the master branch and recreate your PR.

**Pull request closed without merging**
