### PR TITLE
fix cursor height can not fixed

### PR DESCRIPTION
**Pull request by 1036711153**
##  issues

https://github.com/flutter/flutter/issues/92080

#### On the IOS platform

 it is not entered by default : renderEidtable._caretPrototype = Rect.fromLTRB(0.0, 0.0, 2.0, 21.0)

_caretPrototype calculated value from :  _caretPrototype = Rect.fromLTWH(0.0, 0.0, cursorWidth, cursorHeight + 2)

```
 void _computeCaretPrototype() {
    assert(defaultTargetPlatform != null);
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        _caretPrototype = Rect.fromLTWH(0.0, 0.0, cursorWidth, cursorHeight + 2);
        break;
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
      case TargetPlatform.linux:
      case TargetPlatform.windows:
        _caretPrototype = Rect.fromLTWH(0.0, _kCaretHeightOffset, cursorWidth, cursorHeight - 2.0 * _kCaretHeightOffset);
        break;
    }
  }
```

Execute the code to the following image ： caretRect = Rect.fromLTRB(-1.0, 0.0, 1.0, 21.0)

image-20220106142630048

When input enters some text,  Execute the code to the following image ： caretRect = Rect.fromLTRB(6.4, -1.0, 8.4, 20.0)

image-20220106142822319

When no text is entered ： cursorHeight = 21.0 - 0.0  = 21.0 ；

When entering text ： cursorHeight = 20.0 - （-1.0）  = 21.0 ；

 #### On the Android platform

it is not entered by default :  renderEidtable._caretPrototype = Rect.fromLTRB(0.0, 2.0, 2.0, 17.0)

Execute the code to the following image ： caretRect = Rect.fromLTRB(0.0, 2.0, 2.0, 17.0)

image-20220106143806996

When input enters some text,  Execute the code to the following image ：caretRect = Rect.fromLTRB(9.0, 0.3, 11.0, 19.0)

image-20220106143916413

When no text is entered ：cursorHeight = 17.0 - 2.0  = 15.0 ；

When entering text ： cursorHeight = 19.0 - 0.3  = 18.7 ；

## Solution

Whether the cursor height is fixed by setting a marker bit ： fixedCursorHeight；

Refer to the top / bottom of the default cursor area of iOS platform, reset caretrect to fix cursorHeight;

```
   caretRect = caretRect.shift(renderEditable._paintOffset);

    //If fixed cursorHeight, caretRect top bottom will fixed
    if (renderEditable.fixedCursorHeight != null && renderEditable.fixedCursorHeight) {
      caretRect = Rect.fromLTRB(caretRect.left, 0.0, caretRect.right, renderEditable.cursorHeight + 2.0);
    }

    final Rect integralRect = caretRect.shift(renderEditable._snapToPhysicalPixel(caretRect.topLeft));


```

### CODE REVIEW

**Comment by 1036711153** [comment]
> It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need [an exemption](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests) to this rule, contact Hixie on the #hackers channel in [Chat](https://github.com/flutter/flutter/wiki/Chat).
> 
> If you are not sure if you need tests, consider this rule of thumb: the purpose of a test is to make sure someone doesn't accidentally revert the fix. Ask yourself, is there anything in your PR that you feel it is important we not accidentally revert back to how it was before your fix?
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.

**Comment by 1036711153** [comment]
add a mark flag setting fixed cursor height change;  No one-sided CI execution is required ;

**Comment by 1036711153** [comment]
New flag bit setting, fixed cursor height change; No one-sided CI execution is required;

**Comment by goderbauer** [comment]
@1036711153 Can you please sign the CLA as described here: https://github.com/flutter/flutter/pull/96212/checks?check_run_id=5296873042

Also, this PR is missing tests. Can you please add some?

**Comment by Hixie** [comment]
@1036711153  Thanks for your contribution. Unfortunately, because the CLA has not been signed, I'm afraid we can't look at this proposal. I am therefore going to close this PR. If you would like us to consider this patch in the future, please do not hesitate to open a new PR, after signing the CLA which you can find at: https://cla.developers.google.com/

Thanks!

**Pull request closed without merging**
