### PR TITLE
Do not merge - Testing Gold Infra

### PR DESCRIPTION
**Pull request by Piinks**
I am checking Gold for bad behavior, not sure if the passing state and verbose bot is due to an old PR in https://github.com/flutter/flutter/pull/78744 or if there is a bug. I've intentionally changed some golden files to see if the system is working.

### CODE REVIEW

**Comment by Piinks** [comment]
FYI @kjlubick, following up on some erratic bot behavior.

I suspect some of the behavior we are seeing in #78744 and https://github.com/flutter/flutter/pull/80576 have to do with being older PRs.

#78744 in particular is concerning because it added golden files, but the endpoint we check to see if there are images did not report anything. We use that check to block untriaged images from landing.
Here is the link for that: https://flutter-gold.skia.org/json/v1/changelist/github/78744/058350c668e1534b6715f0aaef0d0965ea595b5b/untriaged
The dashboard did have a digest available for triaging, and those images have been approved.

#80576 had no effect on golden files, so I am not sure what the bot comments are from.

This PR appears to validate that the untriaged endpoint _is_ working fine though, which is why I suspect the age of the other PRs might have had something to do with it. (https://flutter-gold.skia.org/json/v1/changelist/github/84389/42c162ddb2351d7bda84b80712b9fe9d93d9a7da/untriaged)
The gold bot did not comment on this change though, so something is still a bit hinky here.

**Comment by Piinks** [comment]
Also for follow-up:

> Golden file changes have been found for this pull request. Click [here to view and triage](https://flutter-gold.skia.org/search?issue=84389&new_clstore=true) (e.g. because this is an intentional change).

This link (https://flutter-gold.skia.org/search?issue=84389&new_clstore=true) is broken, probably just needs to be updated

**Comment by Piinks** [comment]
It looks like this also landed without the skia gold bot or the flutter-gold check determining a change that was later reported on the dashboard: https://github.com/flutter/flutter/pull/84371

**Comment by kjlubick** [comment]
I would suggest using Gold's "smart link" for CLs, as that will have the latest and greatest search link. For example: https://flutter-gold.skia.org/cl/github/84389

I believe the cause of the erratic behavior for the PRs you mentioned is force pushing.

**Comment by kjlubick** [comment]
However, that does not explain why we have not seen a comment on *this* PR, which clearly has diffs, probably in a similar fashion to how #84371 snuck by.

**Comment by Piinks** [comment]
Touched base with @kjlubick an I think we have this sorted out now. :) Closing.

**Pull request closed without merging**
