### PR TITLE
Pass --local-engine* from dev/bots/test.dart to `pub test` (only web)

### PR DESCRIPTION
**Pull request by sigmundch**
This is bassically reapplying #71721, but only enables it on web tests.

There are known issues that several tests under the `integration.shard`
depend on a specific platform, and as a result they require some
additional flexibility or changes to those tests.

By enabling this on the web-test shard, we hope to reduce or eliminate the false positives in the dart-flutter-HHH-web bot.

Fixing the more general problem is tracked by #72368.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by sigmundch** [comment]
FYI - @annagrin @mkustermann

**Comment by jonahwilliams** [comment]
Linux validate_ci_config appears to be stuck, I'm landing this manually but FYI @CaseyHillers @keyonghan

**Comment by CaseyHillers** [comment]
LGTM, this was expected. We removed this test, so a recent rebase with upstream would have fixed it.

**Pull request merged**
