### PR TITLE
Update typedef syntax to use Function notation and turn on lint for old notation.

### LINKED ISSUE #18028: Enable the prefer_generic_function_type_aliases lint
https://www.dartlang.org/guides/language/effective-dart/design#dont-use-the-legacy-typedef-syntax

### PR DESCRIPTION
**Pull request by gspencergoog**
Fixes https://github.com/flutter/flutter/issues/18028

Just changes typedef declarations, no logic changes.

### CODE REVIEW

**Comment by goderbauer** [comment]
Is this by any chance missing a change to analysis_options.yaml that enables the lint?

**Comment by Hixie** [comment]
We should turn on the lint at the same time.
Also we'll need to do the same to dart:ui code in the engine.

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by tvolkert — APPROVED** [review]

**Comment by gspencergoog** [comment]
Here's the PR that does the same for the engine repo: https://github.com/flutter/engine/pull/5419

**Comment by goderbauer** [comment]
Looks like we are running into https://github.com/dart-lang/sdk/issues/33169 with this change on device lab.

**Comment by gspencergoog** [comment]
Reverting

**Pull request merged**
