### PR TITLE
Fix docked FAB bottom padding when BottomBar size is 0

### PR DESCRIPTION
**Pull request by MarcL01**
https://material.io/design/components/app-bars-bottom.html#behavior
Used to replicate the scrolling behavior of material design
Example
Without this fix the FAB will stick to the bottom, ignoring padding.
```
class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  AnimationController animationDouble;

  @override
  void initState() {
    super.initState();
    animationDouble = new AnimationController(
        vsync: this, value: 1.0, duration: Duration(milliseconds: 250));
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new NotificationListener(
        onNotification: (t) {
          if (t is UserScrollNotification) {
            if (t.direction == ScrollDirection.reverse) {
              animationDouble.reverse();
            } else if (t.direction == ScrollDirection.forward) {
              animationDouble.forward();
            }
          }
        },
        child: new ListView(
          children: <Widget>[
            new ListTile(
              title: Text("Test 1"),
            ),
            new ListTile(
              title: Text("Test 2"),
            ),
            new ListTile(
              title: Text("Test 3"),
            ),
            new ListTile(
              title: Text("Test 4"),
            ),
            new ListTile(
              title: Text("Test 5"),
            ),
            new ListTile(
              title: Text("Test 6"),
            ),
            new ListTile(
              title: Text("Test 7"),
            ),
            new ListTile(
              title: Text("Test 8"),
            ),
            new ListTile(
              title: Text("Test 9"),
            ),
            new ListTile(
              title: Text("Test 1"),
            ),
            new ListTile(
              title: Text("Test 2"),
            ),
            new ListTile(
              title: Text("Test 3"),
            ),
            new ListTile(
              title: Text("Test 4"),
            ),
            new ListTile(
              title: Text("Test 5"),
            ),
            new ListTile(
              title: Text("Test 6"),
            ),
          ],
        ),
      ),
      bottomNavigationBar: new SizeTransition(
        sizeFactor: animationDouble,
        child: new BottomAppBar(
          shape: CircularNotchedRectangle(),
          notchMargin: 8.0,
          color: Colors.blueAccent,
          child: new Row(
            children: <Widget>[
              IconButton(
                icon: Icon(Icons.menu),
                onPressed: () {
                  print("open menu");
                },
                color: Colors.white,
              )
            ],
          ),
        ),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      floatingActionButton: new FloatingActionButton(
        onPressed: () {},
        tooltip: 'Add',
        child: new Icon(Icons.add),
      ),
    );
  }
}
```

### CODE REVIEW

**Comment by Hixie** [comment]
This will need a test.

cc @HansMuller or @goderbauer for more detailed review.

**Comment by tvolkert** [comment]
@littlemarc2011 thanks for the contribution!  I'm going to mark this as "needs love" due to the inactivity over the past 20 days (as @Hixie says, this PR needs a test).  Are you willing to add a test for this code?

**Comment by littlemarc2011** [comment]
I will try my best to add a test, it is on my list of things to do.

**Comment by Hixie** [comment]
@littlemarc2011 any luck?

**Comment by HansMuller** [comment]
I'm going to close this because there hasn't been any activity for a while.

**Pull request closed without merging**
