### PR TITLE
Reland composite physical layers on all platforms

### LINKED ISSUE #27891: Composite physical layers on all platforms
Related: https://github.com/flutter/flutter/issues/25673, https://github.com/flutter/flutter/issues/25226

We should investigate compositing physical layers on all platforms.  Today, we only do it for Fuchsia.

A quick test suggests that turning off the check "just works", but it does throw an assert.  Compositing physical layers on all platforms should make checking elevations and getting thicknesses more consistent and performant.

/cc @jason-simmons @mklim @goderbauer @Hixie

### PR DESCRIPTION
**Pull request by dnfield**
## Description

This relands #28919, which had to be reverted because the engine side was misisng anti-aliasing bits on the paint for physical layer drawing on non-Fuchsia platforms.  That was fixed in https://github.com/flutter/engine/pull/8157 and has since rolled through to the framework.

This PR also undoes some of the golden changes from the original PR, where I mistakenly believed there were subtle acceptable differences - I completely missed that I was turning off anti-aliasing (which was caught later in the google3 roll).

As noted on the original PR, this is expected to improve frame build times, but make "rasterization" time in the engine worse (we're shifting work from the framework to the engine).

/cc @HansMuller @jason-simmons @willlarche @liyuqian @goderbauer @mklim who were involved in the original landing and/or rolling back of this.

## Related Issues

Fixes #27891 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (Please read [Handling breaking changes]). - this was handled in the original PR
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by liyuqian — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
I recommend making a test case where it's harder to mistake the change for a positive change. For example, maybe a test where the test itself verifies that the antialiasing is happening (not a golden file test, but one where the image is actually examined by the code to verify that there's more than two colours on the boundary or some such).

**Comment by dnfield** [comment]
I think our migration to Skia gold should help this - we'll have a better UI for evaluating golden changes and seeing exactly what has changed without manual steps involved in generating a new image.

Are you suggesting that matches golden shoul dhave this logic though?  It should be able to detect anti-aliasing regressions?

**Pull request merged**
