### PR TITLE
Reduce refresh indicator pull-down distance

### PR DESCRIPTION
**Pull request by LasseRosenow**
## Description

Reland of #44054 
Thanks to @altherat

gifs to compare results:
| Old Flutter | New Flutter | Native | 
| ------ | ------ | ------ |
| old_flutter | new_flutter | native

## Related Issues

#14981

## Tests

@altherat added the following tests:

RefreshIndicator - just enough: Ensures a 100 pixel drag causes a refresh, which would fail with the previous pull-down distance.

Also modified an existing test (RefreshIndicator - not enough) to pass for the reduced pull-down distance.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by lazylazyllama** [comment]
Sorry for that, but @altherat I need you to sign this again 😭

**Comment by lazylazyllama** [comment]
@shihaohong Regarding the gif you mentioned in my previous pr: I don't have much knowledge in graphic design tools. Do you know any tool / easy way to create such a gif out of 2 videos?

**Comment by altherat** [comment]
@googlebot I consent.

**Comment by shihaohong** [comment]
I figured out a way to compare it pretty well in a more crude manner and added it to the description. This looks great! Thanks for the fix @altherat and thanks for the effort to reland this @lazylazyllama!

**Review by shihaohong — APPROVED** [review]
LGTM!

**Comment by shihaohong** [comment]
I reran Google testing and it appears to be a flake. I'll merge the change.

**Pull request merged**
