### PR TITLE
Changed DefaultTextStyle to consider the TextTheme defined in the context for Bottom Nav Bar

### PR DESCRIPTION
**Pull request by beckler**
Bottom nav bar was not inheriting the global defined theme in the context.

### CODE REVIEW

**Comment by beckler** [comment]
Should fix #7043

**Comment by HansMuller** [comment]
This looks like a good change. Can you add a regression test?

**Comment by HansMuller** [comment]
Thanks! LGTM

**Comment by beckler** [comment]
@HansMuller done!

**Comment by abarth** [comment]
Thanks for the test.

**Comment by eseidelGoogle** [comment]
What a nice patch.  Thank you! :D

**Pull request merged**
