### PR TITLE
Added scroll snapping to the gallery animation demo

### LINKED ISSUE #9604: Animation demo should snap between states
Feedback from Material Design Review of the Gallery.  Feedback was marked P1 so will block any future releases of the Gallery:

"Animation section should snap to either expanded or collapsed instead of staying in an in between state. It breaks when you start scrolling horizontally after partially scrolling vertically"

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes #9604

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
I presume this is for https://github.com/flutter/flutter/issues/9604?

**Comment by HansMuller** [comment]
It is for #9604 however for the fix to work on iOS I need to refactor the iOS scroll simulation so that it's possible to compute where the simulation will end up.  Once that's sorted this PR will get a 'fixes 9604'.

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
Beautiful.

**Comment by abarth** [comment]
Wow, you're living the scroll physics dream.

**Pull request merged**
