### PR TITLE
Upgrade AGP version in tracing_tests

### PR DESCRIPTION
**Pull request by gmackall**
Related to https://github.com/flutter/flutter/issues/134419

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: rolling dependency

**Comment by aam** [comment]
Are there any updates on this? This has a potential of turning dart sdk flutter buidlbot green - it is currently red https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-linux-framework-tests/

**Review by camsim99 — APPROVED** [review]

**Review by johnmccutchan — APPROVED** [review]

**Comment by aam** [comment]
thanks!

**Comment by gmackall** [comment]
> Are there any updates on this? This has a potential of turning dart sdk flutter buidlbot green - it is currently red https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-linux-framework-tests/

I'm also looking through the test configurations for the ci bots in question at the moment, to see if there are any more that are likely to fail. But please bring any additional failures to my attention!

**Pull request merged**
