### PR TITLE
mark widget == and hashCode as nonVirtual

### PR DESCRIPTION
**Pull request by pq**
## Description

Mark Widget `==` and `hashCode` as `@nonVirtual`, effectively disallowing unwanted overrides.

In conversation, @Hixie raised a question of performance; @mraleph: can you speak to how negligible (or not) the impact of these redirects would be?

I'm also not sure if this constitutes a breaking change.  (I'm thinking not?)

## Related Issues

https://github.com/flutter/flutter/issues/1220
https://github.com/flutter/flutter/pull/41220#discussion_r332737769
https://github.com/dart-lang/sdk/issues/58035

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Hixie** [comment]
> I'm also not sure if this constitutes a breaking change. (I'm thinking not?)

There's no judgement required to establish if something is a breaking change anymore. It's entirely based on whether any tests fail. See https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes for details.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
@pq Is this PR ready to be submitted?

**Comment by pq** [comment]
Sorry, yes.  Thanks!  Let's land when the build is green again.

**Pull request merged**
