### PR TITLE
Fix ShapeDecoration.image and .color

### PR DESCRIPTION
**Pull request by Hixie**
Forgot to pass textDirection on some of these calls.

And add a test that catches these problems.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @amirh

**Comment by amirh** [comment]
What do you think about testing that the textDirection is being used?

**Comment by amirh** [comment]
nit: maybe also mention something about textDirection in the documentation for ShapeDecoration.
To figure out where the direction is coming from I had to trace back from _ShapeDecorationPainter to RenderDecoratedBox to DecoratedBox to image.dart#createLocalImageConfiguration and only there I could see it's coming from the ambient directionality...

**Comment by Hixie** [comment]
Added a test for textDirection.

I added some mention of textDirection to BoxPainter.paint. I couldn't figure out where you would want it in ShapeDecoration; none of its APIs really involve textDirection except for stuff inherited from Decoration and BoxPainter.

**Comment by amirh** [comment]
LGTM

I would expect to have textDirection mentioned on the documentation for ShapeDecoration#shape.
"... the direction for the [ShapeBorder] is the ambient directionality".

Happy to send the patch if you think it makes sense

**Comment by Hixie** [comment]
Hey sorry, I just realised you hadn't actually given me an LGTM when I landed it. My apologies!

I'll update the docs as you propose in a new PR.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/14100

**Pull request merged**
