### PR TITLE
Fix CurvedAnimation._curveDirection status update issue

### PR DESCRIPTION
**Pull request by fingerart**
When `CurvedAnimation` plays animation through `AnimationController#repeat(reverse: true)`, `_curveDirection` is not updated correctly inside `CurvedAnimation`, so `_useForwardCurve` is always true, and the incoming `reverseCurve` cannot be used.

Solved #129776

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
@fingerart Looks like this change is failing some tests. It is also missing a test. Can you please look at the failing checks, fix those, and add a new test? Thanks!

**Comment by Piinks** [comment]
Hi @fingerart do you have plan to return to this PR?

**Comment by fingerart** [comment]
Yes, I will add tests to it as soon as possible.

**Comment by fingerart** [comment]
@goderbauer @Piinks I have added tests. Some of the checks are not successful, so I don't understand it very well. How can I modify it?

**Review by Piinks — COMMENTED** [review]
@fingerart it looks like this change is breaking some tests in

- flutter/packages/flutter/test/cupertino/action_sheet_test.dart
- flutter/packages/flutter/test/cupertino/nav_bar_transition_test.dart

**Comment by Piinks** [comment]
Hi @fingerart, since there has not been an update here for some time, I am going to close this PR for now to remove it from our review queue. If you would like to return to it and address the feedback above, please feel free to reopen it. Thanks for contributing!

**Pull request closed without merging**
