### PR TITLE
Remove multi-arch check in iOS builds

### PR DESCRIPTION
**Pull request by liamappelbe**
## Description

As of https://github.com/flutter/engine/pull/10010, iOS builds targeting armv7 are built using a 64-bit version of gen_snapshot that can produce 32-bit arm code. So this multi-arch special case is no longer necessary (and actually breaks the build).

## Related Issues

https://github.com/flutter/flutter/issues/22598

## Tests

I built the flutter examples in this mode using Xcode 10 and verified that they work on an iPhone 4S.

## Manual roll

git log b41c172bcd86..9fca3c74491a --no-merges --oneline
flutter/engine@9fca3c744 Use simarm_x64 when targeting arm (flutter/engine#10010)
flutter/engine@bf9288597 [fuchsia] Add kernel_compiler target in build_fuchsia script (flutter/engine#10403)

### CODE REVIEW

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

**Comment by cbracken** [comment]
Surprised we didn't have any tests for how we used to call gen_snapshot for iOS. They're no longer necessary in any case :)

**Comment by chinmaygarde** [comment]
This roll was made without waiting for the bots to generate assets. I am reverting it as ToT is broken.

**Comment by tvolkert** [comment]
It looks like when this was merged, the engine binaries weren't done building on LUCI yet, and the pre-commit checks were correspondingly red.  Please don't merge commits until the pre-commit checks are green.

**Comment by chinmaygarde** [comment]
I think think the nuance in submitting breaking changes that was missed was that the red on the engine presubmit has to be ignored (because it checks against ToT framework) but the framework presubmits must always be green.

**Pull request merged**
