### PR TITLE
Remove .pub directories from iml templates

### PR DESCRIPTION
**Pull request by natebosch**
The .pub directory is no longer created by the pub tool, and existing
directories get migrated to .dart_tool.

https://github.com/dart-lang/pub/commit/68a6c12602d564316bc9aa0f115ad625d825effe

### CODE REVIEW

**Comment by natebosch** [comment]
There is nothing to test, and I expect nothing to change in existing tests. This removes lines with no visible behavior.

**Comment by Hixie** [comment]
test-exempt: code removal

**Comment by Jasguerrero** [comment]
cc @christopherfujino

**Review by christopherfujino — APPROVED** [review]
RSLGTM

**Comment by christopherfujino** [comment]
@natebosch I suspect rebasing upstream will fix your failing ci.yaml validation

**Pull request merged**
