### PR TITLE
Add AnimatedPositionedDirectional

### LINKED ISSUE #11998: AnimatedPositioned RTL
Need AnimatedPositionedDirectional to match PositionedDirectional.

### PR DESCRIPTION
**Pull request by abarth**
This widget makes it easier to animated Positioned widgets with
awareness of the ambient Directionality.

Fixes #11998

### CODE REVIEW

**Comment by Hixie** [comment]
lol I literally was just doing this one too. I totally forgot to assign it to myself! :-)

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
Land yours, I'll merge it into mine and see if I had anything else.

**Comment by abarth** [comment]
Oh, sorry.  :(

**Comment by Hixie** [comment]
No not at all, you assigned it to yourself! Entirely my fault.

**Pull request merged**
