### PR TITLE
[flutter_tools] support bundling SkSL shaders into Android applications

### LINKED ISSUE #53115: Add support for --sksl-shader-warmup to package sksl files into flutter_assets
These sksl files should be in a well known directory so that they can be read by the engine.

For https://github.com/flutter/flutter/issues/32170

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Support bundling SkSL shaders into an android APK or appbundle via the `--bundle-sksl-path` command line options. If provided, these are validated for platform engine revision and then placed in `flutter_assets/sksl/io.flutter.shaders.json`

Fixes https://github.com/flutter/flutter/issues/53115

### CODE REVIEW

**Comment by liyuqian** [comment]
@jonahwilliams : for iOS, the tool may need to send an extra arg `--disable-metal` to engine if SkSLs are packaged. The SkSLs warm-up currently don't have much effect on Metal.

**Comment by jonahwilliams** [comment]
@liyuqian that seems counter productive, shouldn't we be encouraging users to move to metal?

**Comment by liyuqian** [comment]
Yes, we encourage Metal.

In the short term, however, we may not be able to bring Metal's performance on par with OpenGL on every aspect. So we could allow developers to choose based on their needs. If shader compilation jank is their blocker, then they probably would choose SkSL with OpenGL. If average rasterization performance is more important, they'd choose the default option with Metal without any SkSL warmup.

Fixing the shader compilation jank on Metal needs our medium term solution "Test-based shader warmup #53609" to be implemented.

**Comment by jonahwilliams** [comment]
@liyuqian I believe we discussed ways to validate this before by looking at the verbose logging, but I don't quite remember

**Comment by liyuqian** [comment]
@jonahwilliams : add `--verbose-system-log` to `flutter run` or `flutter drive` will print out the logs in [PersistentCache::LoadSkSLs](https://github.com/flutter/engine/blob/0273fab7590b5f6c1f217d858fac3719aaf4a169/shell/common/persistent_cache.cc#L160). Is that what you're trying to remember?

**Comment by jonahwilliams** [comment]
Ahh yeah, thats the one!

**Comment by jonahwilliams** [comment]
I hit some issue with rebasing, so continuing here: https://github.com/jonahwilliams/flutter/pull/new/bundle_sksl_3

I'm not able to get the persistent cache to find the shader file. Interestingly looking through the logs from both flutter run and adb, I cannot see a place where setting the persistent cache directory gets logged:

Specifically I'm looking for  https://github.com/flutter/engine/blob/31ecf878aa1f12ee7f3a22c424673751db3100da/shell/common/persistent_cache.cc#L338

Logs:
```
I/flutter (19584): [INFO:persistent_cache.cc(158)] No sksl asset file found.
I/flutter (19584): [INFO:gpu_surface_gl.cc(88)] Found 0 SkSL shaders; precompiled 0
I/flutter (19584): [INFO:persistent_cache.cc(228)] PersistentCache::load failed: CAZACAECBUAAAAIAAAAAAAAAAAJQAAIADQABCAH777776FAAN4AAAAAAAAAAAAAAEAABUAAAAAAAAAAAAAACYABGAAAAAAAABUAACAAAAAAAAPAAA4AAAAAAAAAAAAAABUAACAAAAAAAAUAALQAAAAAAAAAAAAAAAIAAAADAABLQA
I/flutter (19584): [INFO:persistent_cache.cc(228)] PersistentCache::load failed: CAZACAECBUAAAAIACAAAAAAAAAJQAAIADQABCAH777776FAAN4AAAAAAAAAAAAAAEAABUAAAAAAAAAAAAAACYABGAAAAAAAABUAACAAAAAAAAPAAA4AAAAAAAAAAAAAABUAACAAAAAAAAUAALQAAAAAAAAAAAAAAAIAAAADAABLQA
I/flutter (19584): [INFO:persistent_cache.cc(228)] PersistentCache::load failed: CAZAAAECAUAAAAAAAAABGAABAAOAAEIADQAAGAAQABMQAAAAAAAAAAAAAABAAAAAEAAFOAA
I/flutter (19584): [INFO:persistent_cache.cc(228)] PersistentCache::load failed: CAZAAAECAYAAAAYAAAAACAAAAAJQAAIADQABCAAPAAKAAAAAAAABIABLAAAAAAAAAAAAAAACAAAAAKAAK4AA
I/flutter (19584): [INFO:persistent_cache.cc(228)] PersistentCache::load failed: CAZAAAECAYAAAAAAAAAACAAAAAJQAAIADQABCAAPAAKAAAAAAAABIAAZAAAAAAAAAAAAAAACAAAAAKAAK4AA
I/flutter (19584): [INFO:persistent_cache.cc(228)] PersistentCache::load failed: GMZQAAEBA4AAAAAAAAAEOAIAAAJQAAIACIAAAAA4AAIQB7777777777777777777EAAFUAAAAAAAAAAAAAAACAAAAAYAACIA
I/flutter (19584): [INFO:persistent_cache.cc(228)] PersistentCache::load failed: GMZQCAEBBEAAAAAAAAACOAAAAAJQAAIA7777777777776EYAAEAP777777777777EAAFUAAAAAAAABAEAAAAAAAAAAWAATIAAIAAAAAAAAAAAAQAAAAEAACXAA

Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Pixel 4 is available at: http://127.0.0.1:60778/TsLNHw50k4k=/
I/flutter (19584): [INFO:persistent_cache.cc(228)] PersistentCache::load failed: GMZQCAEBBMAAAAAAAAACOAAAAAJQAAIA7777777777776EYAAEAP777777777777EAAFUAAAAAAAABAEAAAAAAAAAAWAATIAAEAAAAAJAAAAABAEAAAEAABRAABAAAAAAAAAAAACAAAAAUAAK4AA
I/flutter (19584): [INFO:persistent_cache.cc(228)] PersistentCache::load failed: GMZQCAEBBMAAAAAAAAACOAAAAAJQAAIA7777777777776EYAAEAP777777777777EAAFUAAAAAAAAAAAAAAAAAAAAAWAATIAAEAAAAAJAAAAAAAAAAAEAABRAABAAAAAAAAAAAACAAAAAUAAK4AA
I/flutter (19584): [INFO:persistent_cache.cc(228)] PersistentCache::load failed: GMZQCAEBBEAAAAAAAAACOAAAAAJQAAIA7777777777776EYAAEAP777777777777EAAFUAAAAAAAAAAAAAAAAAAAAAWAATIAAIAAAAAAAAAAAAQAAAAEAACXAA
I/flutter (19584): [INFO:persistent_cache.cc(228)] PersistentCache::load failed: CAZAAAMCBEAAAAAAAAAGOAAAAAJQAAIA777777Y4AAIQAEYAAEAP777777777777EAAFUAAAAAAAABAEAAAAAAAAAAWAATIAAIAAAAAAAAAAAAQAAAAEAACXAA
I/flutter (19584): [INFO:persistent_cache.cc(228)] PersistentCache::load failed: CAZAAAECA4AAAAAAAAAEOAQAAAJQAAIA777777Y4AAIQB7777777777777777777EAAFUAAAAAAAAAAAAAAAEAAAAAYAAVYA
I/flutter (19584): [INFO:persistent_cache.cc(228)] PersistentCache::load failed: CAZAAAACBAAAAAAAAAAGKAAAAAJQAAIA777777Y4AAIQAEYAAEAP777777777777AAAAAABAABNAAAAAAAAAAAAAAABAAAAAGQAFOAA
```

**Comment by liyuqian** [comment]
@jonahwilliams : thanks for discovering this issue! The root cause of this issue and its fix are described in https://github.com/flutter/engine/pull/17948. Before that PR gets rolled, you can try your tools on iOS.

**Comment by liyuqian** [comment]
FYI @jonahwilliams: I just found one more issue on Android so now I completely moved from reading files from a path to directly calling the AssetManager (https://github.com/flutter/engine/pull/17948#issuecomment-619333051). As a result, you no longer need to put the file in `sksl/io.flutter.shaders.json`. Simply put the file in the root asset directory as `io.flutter.shaders.json` is what the engine needs.

**Comment by jonahwilliams** [comment]
That works, thanks @liyuqian !

**Comment by jonahwilliams** [comment]
Success!
```
Installing build\app\outputs\flutter-apk\app-release.apk...         3.6s
I/flutter (27872): [INFO:persistent_cache.cc(160)] Found sksl asset. Loading SkSLs from it...
I/flutter (27872): [INFO:gpu_surface_gl.cc(88)] Found 27 SkSL shaders; precompiled 27
```

**Comment by jonahwilliams** [comment]
Closing in favor of https://github.com/flutter/flutter/pull/56059

**Pull request closed without merging**
