### PR TITLE
[H] Golden file tests for clip

### PR DESCRIPTION
**Pull request by Hixie**
Also, fixes "flutter run" for golden tests, and some docs.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @goderbauer @liyuqian 

The golden files are showing broken behaviour; I've filed https://github.com/flutter/flutter/issues/18057 to track this.

**Comment by Hixie** [comment]
cc @tvolkert for the golden file logic fixes

**Comment by Hixie** [comment]
Not sure why the golden files failed to match?

**Comment by tvolkert** [comment]
> Not sure why the golden files failed to match?

Yeah, we need https://github.com/flutter/flutter/issues/17260.  Do they pass for you locally?

One thing you need to do is to skip these tests on non-Linux (though they're still failing on Linux too).

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Nope, doesn't match locally...

**Comment by Hixie** [comment]
hm, if i update goldens then retest, it does work. Maybe the engine slightly changed behaviour recently...

**Comment by Hixie** [comment]
New goldens vs old goldens (updated in https://github.com/flutter/goldens/commit/95f60c7e328b53dd65de18a608830a872a92e3cd):

clip clipoval 1 png diff
clip clippath 1 png diff
clip cliprect 1 png diff
clip cliprrect 1 png diff
clip physicalmodel 1 png diff
clip physicalshape 1 png diff

**Comment by Hixie** [comment]
@tvolkert Why should I disable these for non-Linux?

**Comment by tvolkert** [comment]
> Why should I disable these for non-Linux?

If all platforms pass, I suppose you don't 😄

**Review by tvolkert — APPROVED** [review]
LGTM

**Pull request merged**
