### PR TITLE
Roll engine forward with attempt to fix ios perf regression

### PR DESCRIPTION
**Pull request by aam**
This is to pick up https://github.com/flutter/engine/pull/4133, which hopefully addresses https://github.com/dart-lang/sdk/issues/30786

### CODE REVIEW

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm

**Comment by Hixie** [comment]
This may have caused a performance regression. I'm going to apply https://github.com/flutter/flutter/pull/12209 (a revert of the possible more likely cause) to check if it's that one first though.

**Comment by Hixie** [comment]
#12209 wasn't the cause after all, so it seems likely that this was the cause.

**Comment by aam** [comment]
Looking at the performance dashboard for two ios tests, it seems that improving one(like this PR tried) regresses the other:
complex_layout_scroll_perf_ios__timeline_summary average_frame_rasterizer_time_millis turns red when flutter_gallery_ios__transition_perf average_frame_build_time_millis turns green and vice versa.

screen shot 2017-09-22 at 4 31 20 pm

**Pull request merged**
