### PR TITLE
make some widgets const

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

You are amazing.

**Comment by a14n** [comment]
@Hixie I notice _flutter-build_ check failed for this PR but I don't know what it is and I don't know how to fix it. Any advice ?

**Comment by Hixie** [comment]
It's our build status. See the end of the code review section on this page: https://flutter.io/design-principles/#code-review-and-checking-in-code

Unfortunately some of the things that contribute to that status aren't publicly visible because we suck. In any case, the solution is to just wait for us to fix the problem and it'll turn green on its own. (You'll notice all the PRs are red at the moment because of "flutter-build".)

**Comment by a14n** [comment]
Does it mean I can go ahead and merge?

**Comment by Hixie** [comment]
Nope, you have to wait for it to go green. :-) That's why it's there, to make it clear when it's not ok to check in.
Looking at the links that are publicly visible (at the end of that section I linked to above), everything is green. That means the problem is with some internal test (which I can't see right now since I'm not at the office). It'll probably get looked at in the morning (about 10 hours from now). (Unless one of our European colleagues gets to it first, which is possible.)

cc @sethladd / @yjbanov this conversation shows a good reason for why we should make the test dashboard public.

**Comment by a14n** [comment]
Thanks for your answer.

I will wait until all is green.

**Comment by abarth** [comment]
Looks like a flaky run of flutter_gallery__transition_perf.  We might need to start with a whitelist of bots that aren't flaky and expand over time as we stablize.

**Comment by Hixie** [comment]
If you mark a test as flaky in https://github.com/flutter/flutter/blob/master/dev/devicelab/manifest.yaml then it won't turn the build red when it fails.

**Comment by Hixie** [comment]
@abarth https://github.com/flutter/flutter/pull/9489

**Comment by a14n** [comment]
all green => merge

**Comment by yjbanov** [comment]
Public dashboard is code complete. Needs maybe another 2 hours of work to clean up and send a PR.

**Pull request merged**
