### PR TITLE
Add Container.max to set both width and height as infinity by default

### PR DESCRIPTION
**Pull request by AlenDavid**
## Description

Improve Container using a static max method (Container.max) that creates a Container with both height and width set to double.infinity. This setting differs from Expanded on my projects because Expanded goes of screen, while Container(width: double.infinity, height: double.infinity) doesn't do that!

## Related Issues

This is a issue I have found while I was making my personal projects, so I don't found any issues it may get into!

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behaviour with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by AlenDavid** [comment]
@googlebot I fixed it.

**Review by dnfield — CHANGES_REQUESTED** [review]
Thanks for the contribution!

There are a few things that should be done here:

- Any change should have an issue attached to discuss. There's no linked issue here.
- We don't use dartfmt in this repository. All dartfmt related changes should be reverted.
- The new constructor calls itself `max`, but allows width and height to be set to alternative values.
- The problem this is solving is pretty trivial for a downstream consumer to solve, either by explicitly supplying the parameters (only a few more keystrokes than the new constructor here) or creating some other wrapper for it. No changes are needed to the framework to support that.

I'm not clear on why the added maintenance cost of this new constructor is worth the convenience to developers. But perhaps if we can get an issue filed for it, we'll be able to see if this is really a very common request/highly desired feature.

**Comment by AlenDavid** [comment]
So,

Should we close this pull request?

**Comment by dnfield** [comment]
I think so, yes. If you're looking for some things to start tackling, you can take a look through the issues DB, particularly issues labeled easy fix: https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3A%22easy+fix%22

**Pull request closed without merging**
