### PR TITLE
reland driver vm_service migration

### PR DESCRIPTION
**Pull request by dnfield**
Diff from last time is in 6c086e47e5

- Close socket on retries
- Use pub run test to run the host test file.

@jonahwilliams 

See (#68654) (#69074) (#69077) (#69089) for history

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Failure is fixed on master. Going to land this as is.

**Comment by dnfield** [comment]
This one looks like it's going to stick!

**Comment by amirh** [comment]
Following this PR integration tests in flutter/plugins are failing with: `Could not find package "test". Did you forget to add a dependency?`

See: https://cirrus-ci.com/task/4631268350492672?command=build#L255

I'm not sure if it means that the code in flutter/plugins was bad to start with, but we should probably consider this as a breaking change...

**Pull request merged**
