### PR TITLE
android/build.gradle template: merge subprojects {} blocks together

### PR DESCRIPTION
**Pull request by bartekpacia**
Seeing if `subprojects {}` can be merged.

See also:
- #91030
- #77942

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by AbdeMohlbi** [comment]
@bartekpacia 
If u could add this to the template to hit two in a row [here](https://github.com/flutter/flutter/issues/146036#issuecomment-2030058768)

**Comment by bartekpacia** [comment]
@AbdeMohlbi Right now I'm pretty confused, because [this commit](https://github.com/flutter/flutter/pull/147868/commits/67e660dc2f9f446a0b81d25530b84783789dd91d) did not cause [this test](https://github.com/flutter/flutter/blob/9f28b83c19b5743b7a6f8f0395721c9af9c52830/packages/flutter_tools/test/integration.shard/flutter_build_android_app_project_builddir_test.dart) to fail.

**Comment by AbdeMohlbi** [comment]
I see even if i don't quite understand how tests works in this kind things can u try to run the test localy or smth i dunno ?

**Comment by gmackall** [comment]
I have wondered why we have these two different blocks before.

Is this ready for review? Looks like tests are passing?

**Comment by bartekpacia** [comment]
@gmackall, here's some context:
- in the beginning, `subprojects {}` blocks were separate (like they are now)
- some time later, in PR #77942, the `subprojects {}` blocks were merged together
- merging the `subprojects {}` blocks caused issue #91018 to occur
- to fix the issue #91018, the PR #91030 was made to separate the `subprojects {}` block back. In that PR, [a test was also added](https://github.com/flutter/flutter/blame/9f28b83c19b5743b7a6f8f0395721c9af9c52830/packages/flutter_tools/test/integration.shard/flutter_build_android_app_project_builddir_test.dart) that tests that the behavior (the behavior that occurs when `subprojects {}` blocks are merged) doesn't occur anymore.

IIRC, the crux of the problem lies in Gradle. I'll investigate further to provide a minimal, reproducible example of the behavior that is fixed when the `subprojects {}` blocks are merged together.

---

I made this PR to see if the wrongful behavior is still present in Gradle. I'm surprised that CI is green. I expected [the test added in PR #91030 to fail]((https://github.com/flutter/flutter/blame/9f28b83c19b5743b7a6f8f0395721c9af9c52830/packages/flutter_tools/test/integration.shard/flutter_build_android_app_project_builddir_test.dart)), but it is not failing.

**Comment by bartekpacia** [comment]
With changes in this PR, running:

```
cd packages/flutter_tools
flutter test test/integration.shard/flutter_build_android_app_project_builddir_test.dart
```

**fails**.

<details><summary>Logs</summary>

```
$ flutter test test/integration.shard/flutter_build_android_app_project_builddir_test.dart                                                                                 exit 1
Downloading Darwin arm64 Dart SDK from Flutter engine d8ac05c3fb4fca52e1dcc29e32ef757575fcb212...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  206M  100  206M    0     0  8529k      0  0:00:24  0:00:24 --:--:-- 6934k
Building flutter tool...
Resolving dependencies...
Downloading packages...
Got dependencies.
Downloading package sky_engine...                                  429ms
Downloading package flutter_gpu...                                 158ms
Downloading flutter_patched_sdk tools...                         1,217ms
Downloading flutter_patched_sdk_product tools...                   526ms
Downloading darwin-arm64 tools...                                   4.4s
Downloading darwin-arm64/font-subset tools...                      341ms
Resolving dependencies...
Downloading packages...
  devtools_shared 10.0.2 (11.0.0 available)
  flutter_template_images 4.2.0 (4.2.1 available)
  meta 1.15.0 (1.16.0 available)
  native_assets_builder 0.8.2 (0.8.3 available)
  native_assets_cli 0.7.3 (0.8.0 available)
  usage 4.1.1 (discontinued)
Got dependencies!
1 package is discontinued.
5 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
00:54 +0 -1: android/app/build should not exists after flutter build apk [E]
  Expected: not a file system entity that exists
    Actual: LocalDirectory:<LocalDirectory: '/private/var/folders/r6/5z0bypqn4cb8p369zlrfhw3c0000gn/T/flutter_flutter_plugin_test.tv2lhI/aaa/example/android/app/build'>

  package:matcher                                                                   expect
  test/integration.shard/flutter_build_android_app_project_builddir_test.dart 53:5  main.checkBuildDir
  test/integration.shard/flutter_build_android_app_project_builddir_test.dart 66:7  main.<fn>
  test/src/common.dart 183:18                                                       test.<fn>


To run this test again: /Users/bartek/.cache/fvm/versions/master/bin/cache/dart-sdk/bin/dart test /Users/bartek/.cache/fvm/versions/master/packages/flutter_tools/test/integration.shard/flutter_build_android_app_project_builddir_test.dart -p vm --plain-name 'android/app/build should not exists after flutter build apk'
01:15 +0 -2: android/app/build should not exists after flutter build appbundle [E]
  Expected: not a file system entity that exists
    Actual: LocalDirectory:<LocalDirectory: '/private/var/folders/r6/5z0bypqn4cb8p369zlrfhw3c0000gn/T/flutter_flutter_plugin_test.J7142o/aaa/example/android/app/build'>

  package:matcher                                                                   expect
  test/integration.shard/flutter_build_android_app_project_builddir_test.dart 53:5  main.checkBuildDir
  test/integration.shard/flutter_build_android_app_project_builddir_test.dart 80:7  main.<fn>
  test/src/common.dart 183:18                                                       test.<fn>


To run this test again: /Users/bartek/.cache/fvm/versions/master/bin/cache/dart-sdk/bin/dart test /Users/bartek/.cache/fvm/versions/master/packages/flutter_tools/test/integration.shard/flutter_build_android_app_project_builddir_test.dart -p vm --plain-name 'android/app/build should not exists after flutter build appbundle'
```

</details>

**Comment by bartekpacia** [comment]
closing as it's really minor thing and I don't have time to work on it

**Pull request closed without merging**
