### PR TITLE
Remove fuchsia_remote_debug_protocol from API docs

### PR DESCRIPTION
**Pull request by mit-mit**
Mark `fuchsia_remote_debug_protocol` as `nodoc` to remove it from our API docs. Currently this pulls `vm_service` into API docs, and that is not something we should be listing for app developers.

### CODE REVIEW

**Review by Wilczopolski — COMMENTED** [review]
ggsadut

**Comment by mit-mit** [comment]
cc @tvolkert

**Review by tvolkert — COMMENTED** [review]
This change LGTM, but this package is already excluded here: https://github.com/flutter/flutter/blob/184e5871beea4a9b1cbd65dcc57118a7d97285f3/dev/tools/dartdoc.dart#L169

I'm curious: is that not working?

**Comment by mit-mit** [comment]
I don't think it's working, but not fully sure. My goal is to get `fuchsia_remote_debug_protocol` removed from our API docs.

**Review by tvolkert — APPROVED** [review]
I don't see `fuchsia_remote_debug_protocol` on https://api.flutter.dev/ currently.

But nonetheless, the change LGTM.

**Comment by mit-mit** [comment]
Sorry; I must be getting tired. It's VM Service I'm trying to remove from API docs, and that I think it pulled in by this.

I resolved the merge conflict; did I do that correctly? I don't fully understand where that hash is coming from.

**Comment by tvolkert** [comment]
The hash comes from `flutter update-packages --force-upgrade` - it's there to prevent people from manually bumping a single version dependency, since we bump them atomically across the repo.

In your case, you could hack the tool to print out the hash it expects, then update the hash here to match -- to avoid having to update versions in this PR.

**Comment by mit-mit** [comment]
Could I just run that and roll all the package versions at the same time?

**Comment by mit-mit** [comment]
@tvolkert would it be OK if I rolled all package versions with the command?

**Comment by tvolkert** [comment]
Sorry - didn't see your earlier question (was OOO).  Yes, that would be fine.

**Comment by mit-mit** [comment]
Thanks, replaced this with https://github.com/flutter/flutter/pull/87786

**Pull request closed without merging**
