### PR TITLE
Add hero groups to support hero animations with nested navigators

### PR DESCRIPTION
**Pull request by spkersten**
This is an implementation for the solution (1b) mentioned in #28042.

### CODE REVIEW

**Comment by Hixie** [comment]
I think a simpler solution would be to avoid walking into nested Navigators.

**Comment by eseidelGoogle** [comment]
@goderbauer Ian is out for a while.  Can you take a look (and approve or reject as you see fit) for customer: solaris.  Thank you.

**Comment by goderbauer** [comment]
Alternative approach: https://github.com/flutter/flutter/pull/29069

**Comment by spkersten** [comment]
Closing, since @goderbauer's alternative looks better.

**Pull request closed without merging**
