### PR TITLE
The sample code used within the comments in textContaining is wrong

### LINKED ISSUE #100859: The sample code used within the comments in textContaining is wrong
`textContain` is used instead of `textContaining` in the sample code used within the comments of `textContaining`.

### Expected results:
```dart
  /// (Omitted)
  ///
  /// ```dart
  /// expect(find.textContaining('Back'), findsOneWidget);
  /// expect(find.textContaining(RegExp(r'(\w+)')), findsOneWidget);
  /// ```
  ///
  /// (Omitted)
  ///
  /// ```dart
  /// expect(find.textContaining('Close', findRichText: true), findsOneWidget);
  /// expect(find.textContaining(RegExp(r'(\w+)'), findRichText: true), findsOneWidget);
  /// ```
  /// (Omitted)
  /// 
  Finder textContaining(
    Pattern pattern, {
    bool findRichText = false,
    bool skipOffstage = true,
  }) {
```

### Actual results
```dart
  /// (Omitted)
  ///
  /// ```dart
  /// expect(find.textContain('Back'), findsOneWidget);
  /// expect(find.textContain(RegExp(r'(\w+)')), findsOneWidget);
  /// ```
  ///
  /// (Omitted)
  ///
  /// ```dart
  /// expect(find.textContain('Close', findRichText: true), findsOneWidget);
  /// expect(find.textContain(RegExp(r'(\w+)'), findRichText: true), findsOneWidget);
  /// ```
  /// (Omitted)
  /// 
  Finder textContaining(
    Pattern pattern, {
    bool findRichText = false,
    bool skipOffstage = true,
  }) {
```
<details>
<summary>flutter doctor -v</summary>
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.3 21E230 darwin-arm, locale ja)
    • Flutter version 2.8.1 at /opt/homebrew/Caskroom/flutter/2.5.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/yamashita/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • Pixel 3a (mobile) • 93GAY0BAJD • android-arm64  • Android 12 (API 32)
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 99.0.4844.84

• No issues found!
```
</details>

### PR DESCRIPTION
**Pull request by 8rine23**
fixes https://github.com/flutter/flutter/issues/100859

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by HansMuller — COMMENTED** [review]
There's an additional problem here. The [textContaining](https://api.flutter.dev/flutter/flutter_test/CommonFinders/textContaining.html) method doesn't have a findRichText parameter.

**Comment by TowaYamashita** [comment]
@HansMuller 
Thanks for commenting on this pull-request.
I would like to address the problem, but I don't know how to fix the documentation.
Could you please tell me how to fix the [document](https://api.flutter.dev/flutter/flutter_test/CommonFinders/textContaining.html)?

**Comment by goderbauer** [comment]
@HansMuller The `textContaining` matcher does have a `findRichText` property on master: https://master-api.flutter.dev/flutter/flutter_test/CommonFinders/textContaining.html. With that, this change looks fine to me.

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by HansMuller — APPROVED** [review]
LGTM

**Review by jen801 — COMMENTED** [review]
packages/flutter_test/lib/src/finders.dart

**Pull request merged**
