### PR TITLE
Revert "fix a Scaffold.bottomSheet update bug"

### PR DESCRIPTION
**Pull request by angjieli**
This PR breaks several Google tests. 
Reverts flutter/flutter#83689

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
The source of the problem seems to be obscured because the error message is trying to print a deactivated widget's state: "Looking up a deactivated widget's ancestor is unsafe...."

Will investigate.

Internal google bug b/189965268

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by Piinks** [comment]
FYI @xu-baolin who authored the change

**Comment by xu-baolin** [comment]
@HansMuller  Hi, any news about the internal tests?

**Comment by HansMuller** [comment]
Sorry: investigating why the internal tests failed is on my queue; just haven't been able to get to it yet. Sorry about the delay.

**Comment by xu-baolin** [comment]
Got it. Thanks a lot.

**Pull request merged**
