### PR TITLE
Adjust the tests to handle a higher-DPI test harness.

### PR DESCRIPTION
**Pull request by Hixie**
Requires https://github.com/flutter/engine/pull/3688

Moving from `/` to `*` in the gesture binding tests in theory does nothing but in practice avoids floating point errors.

### CODE REVIEW

**Comment by Hixie** [comment]
@chinmaygarde this is the framework side to make up for the engine PR i cc'ed you on

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
This PR now includes the relevant engine roll.
I will land on green unless I hear otherwise.

**Comment by Hixie** [comment]
I have additionally included a fix to an esoteric Stocks test that is dependent on the device pixel ratio.

**Pull request merged**
