### PR TITLE
Rename TextStyle#height to lineHeight

### LINKED ISSUE #2918: API docs: mention that TextStyle's height is the same as ui.TextStyle's lineHeight?
I saw that rendering's TextStyle has a height, and I was curious if that was the same thing as "lineHeight". I also saw that ui's TextStyle has a lineHeight. And then I saw that rendering.TextStyle's getter for textStyle returns a ui.TextStyle and sets the lineHeight to height.

I went through this process because I searched for "line height" on flutter.io to learn how Flutter does line height.

Could we say something like "Also known as _line height_." in rendering.TextStyle's dartdoc comments?

(if that is indeed accurate...)

### PR DESCRIPTION
**Pull request by abarth**
This matches what we use in dart:ui and CSS.

Fixes #2918

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

**Comment by Hixie** [comment]
LGTM.

FWIW, the name "height" had been intentionally different, because "line height" is a misleading name. "height" isn't particularly better but it's vaguer so it's harder to say it's really wrong.

**Comment by abarth** [comment]
lineSpacing ?

**Comment by Hixie** [comment]
It doesn't really do anything with lines. It's the height of the inline box.

**Comment by abarth** [comment]
Do you think we should merge this pull request or should we try for a better name?

**Comment by Hixie** [comment]
I don't really have a good idea for what to do here.

I think I'd be tempted to change the dart:ui names to "height" instead.

I don't think there's much value in having names that match CSS. We're going to diverge over time and eventually that'll just be confusing. It's easy for people to have a name mapping cheat sheet if they need it.

Note that ParagraphStyle's _should_ be called lineHeight, because it's setting the size of the line. (Though there might be a bug about that being broken right now.)

**Comment by apwilson** [comment]
FWIW I never liked TextStyle.height.  I don't really know what it means - especially since I set fontSize which is a 'height' in a way.

**Comment by abarth** [comment]
> I don't really know what it means - especially since I set fontSize which is a 'height' in a way.

What this means is now documented:
http://docs.flutter.io/flutter/widgets/TextStyle/height.html

The value is expressed as a multiple of the font size, which helps a bit with the redundancy.

**Pull request closed without merging**
