### PR TITLE
Deletes files that should be ignored

### PR DESCRIPTION
**Pull request by lsaudon**
Some files are supposed to ignore, but don't.

- **/windows/flutter/generated_plugins.cmake
- **/linux/flutter/generated_plugin_registrant.cc
- **/linux/flutter/generated_plugin_registrant.h
- **/linux/flutter/generated_plugins.cmake
- **/windows/flutter/generated_plugin_registrant.cc
- **/windows/flutter/generated_plugin_registrant.h
- **/ios/Runner/GeneratedPluginRegistrant.h
- **/ios/Runner/GeneratedPluginRegistrant.m

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by loic-sharma** [comment]
For background history on this, see this comment: https://github.com/flutter/flutter/issues/119544#issuecomment-1409597133

**Review by loic-sharma — APPROVED** [review]

**Review by yaakovschectman — APPROVED** [review]
These have been a bit annoying in some of my work before, too. LGTM

**Comment by lsaudon** [comment]
> auto label is removed for flutter/flutter, pr: 127984, due to - The status or check suite [triage](https://github.com/flutter/flutter/actions/runs/5393041972/jobs/9792222743) has failed. Please fix the issues identified (or deflake) before re-applying this label.

I don't understand the error in Pull Request Labeler / triage (pull_request_target)

**Comment by loic-sharma** [comment]
> > auto label is removed for flutter/flutter, pr: 127984, due to - The status or check suite [triage](https://github.com/flutter/flutter/actions/runs/5393041972/jobs/9792222743) has failed. Please fix the issues identified (or deflake) before re-applying this label.
> 
> I don't understand the error in Pull Request Labeler / triage (pull_request_target)

This appears to be an infra bug that's unrelated to your change, see this discussion: https://discord.com/channels/608014603317936148/613398423093116959/1123366240153501817

**Pull request merged**
