### PR TITLE
fix11068 InputDecoration 'errorText' custom builder

### LINKED ISSUE #11068: InputDecorator 'errorText' should have 'textAlign' property
When used with the TextFiled the InputDecorator 'errorText' uses the TextFiled's 'textAlign' property (I suspect).

This is a problem when the TextFiled is used to show numerical values in which case the value should be right-aligned but the error message should be left-aligned.

### PR DESCRIPTION
**Pull request by Michele-x98**
Me, [Daniele Cambi](https://github.com/dancamdev) and [Cosimo Tassone](https://github.com/ctechdev) made this PR that allows to customize the errorText of an InputDecoration with an errorWidgetBuilder function that takes in input the errorText String that cames from InputDecoration, when it is not null, and allows to build a custom Widget for the error.
The default behavior doesn't change if the errorWidgetBuilder is not provided.

Without error widget builder:

<a href="https://ibb.co/jWtQQRR">Simulator-Screen-Shot-i-Phone-13-mini-2022-05-19-at-11-38-16</a>

With custom errorWidgetBuilder:

<a href="https://ibb.co/CJ50Wtj">Simulator-Screen-Shot-i-Phone-13-mini-2022-05-19-at-11-40-30</a>

*List which issues are fixed by this PR. You must list at least one issue.*
Fixes #11068

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by justinmc — COMMENTED** [review]
Thanks for the PR (+@dancamdev and @ctechdev)!  I agree that people probably do want to be able to specify a widget for the error and not just text.  Some points that I'm noticing:

  1. Did you run an autoformatter on the code?  It looks like there are lots of unrelated changes.  We don't use dart format on the Flutter framework code.
  2. We'll need at least one test for this.
  3. I wonder if a parameter of type `Widget` would be better than a builder function?  Similar to [label](https://master-api.flutter.dev/flutter/material/InputDecoration/label.html) and [labelText](https://master-api.flutter.dev/flutter/material/InputDecoration/labelText.html).  Would that still work for you?
  4. Should `helperText` also have this kind of parameter?

**Comment by dancamdev** [comment]
Hi @justinmc, thanks for reviewing the code.

1. Yes, we might have, is there a quick way to roll back?

2. Sure, we'll figure what exactly should be tested, I'm not sure we can have widget tests within flutter itself, right?

3. We'll have a look into it, I remember running into issues when trying to go that route, that's why we settled for a builder in the end.

4. I think it does make sense to have it for helperText as well, we'll have a look into it.

**Comment by dancamdev** [comment]
@justinmc upon further analysis on the current error implementation on both `TextField` and `TextFormField`, which both use `InputDecoration`, we consider the builder approach the better one as it doesn't brake the form validation logic.

We're working on adding tests and `helperWidgetBuilder`

**Comment by HansMuller** [comment]
Specifying an errorWidget  instead of errorText seems sufficient, since the developer needs to specify one or the other for `InputDecoration` and if we allow an errorWidget to be specified, some apps may choose to just show an icon (or whatever) rather than a text message.

This PR reformats InputDecorator.dart; it should not. Please only change as much of the existing code as is necessary to make your change.

Not also: tests for this new feature will be needed.

**Comment by justinmc** [comment]
+1 to the above.  I'm not sure if there's an easy way to rollback the formatter changes or not.  For tests, take a look at [input_decorator_test.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/input_decorator_test.dart) or maybe [text_field_test.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/text_field_test.dart).

**Comment by justinmc** [comment]
@dancamdev @Michele-x98 Are you guys still available to finish this PR?  Let me know if there's anything blocking you.

It looks like there is a merge conflict, but it's probably just due to the formatting changes in input_decorator.dart.

**Comment by Michele-x98** [comment]
@xvrh That's the point, you can't. Now with the simple **errorWidget** you can just add something under the field and it is permanently showed, without the builder you don't have access to the error message string if that is not null. In the previous version that i proposed, the _builder method_ allow to take the message error in input and handle it as you want, but as @justinmc  and @HansMuller said, that logic works only if the widget is "linked" to the errorText, and if the _errorText_ is Null, the widget is never displayed.

**Comment by xvrh** [comment]
@Michele-x98 

> that logic works only if the widget is "linked" to the errorText, and if the errorText is Null, the widget is never displayed.

Unless I'm missing something, this is the behaviour we want.

And if not, then we can also update the builder to be `Widget? Function(String? errorMessage) errorBuilder`. So the user of the API can really decide what to do with and without an error message.

**Comment by Michele-x98** [comment]
@xvrh I follow this logic above: 

> Specifying an errorWidget instead of errorText seems sufficient, since the developer needs to specify one or the other for InputDecoration and if we allow an errorWidget to be specified, some apps may choose to just show an icon (or whatever) rather than a text message.

But i think that it also works as you propose as well, maybe the function could be Nullable and the return type Widget not?

`Widget Function(String? errorMessage)? errorBuilder `

This make more sense to me.
Let me know if it's ok

**Comment by cinder92** [comment]
any update on this?

**Comment by HansMuller** [comment]
I'm closing this due to lack of activity. If you decide to resume working on it, please reopen the PR.

**Pull request closed without merging**
