### PR TITLE
Reland "Refactor ThemeData (#91497)" (part 2) 

### PR DESCRIPTION
**Pull request by guidezpl**
This handles the remaining part of #91497 (reverted in #92820), in the factory constructor. There's a little bit of trickiness around defaults for certain properties (`colorScheme` and `buttonTheme`, namely), but I documented it for `buttonTheme`.

### CODE REVIEW

**Comment by guidezpl** [comment]
@darrenaustin PTAL :)

**Review by darrenaustin — APPROVED** [review]
LGTM. Thx.

**Comment by darrenaustin** [comment]
However, you will need to get a test exemption from @Hixie.

**Comment by Hixie** [comment]
test-exempt: refactor with no semantic change

**Pull request merged**
