### PR TITLE
removed image with 404

### PR DESCRIPTION
**Pull request by mikeroosa**
I removed the image with the 404 and put all the images on the same row to make it look good. This is for issue #23846.

### CODE REVIEW

**Comment by mikeroosa** [comment]
Just looking to make a contribution and learn the process before I dig into something deeper. I took one of the easy-fix issues and submitted the pull request. Please review and let me know if it looks okay or I need to make additional changes.

**Comment by filiph** [comment]
Hike @mikeroosa, thanks for the pull request! And thanks for spotting the 404.

The original `posse_gallery` repo went private but we probably still want to show the picture to be there. The code now lives in a branch here at flutter/flutter (https://github.com/flutter/flutter/tree/gallery) and might get merged into `master`.

Could you please reinstate the picture but without the link-through? When the posse gallery finds its final(-ish) place, we'll add the link.

Also, I don't know what's the deal with the CI fails. I think you were just unlucky to land at a time of breakage.

**Comment by goderbauer** [comment]
I restarted the CI. They should turn green now...

**Comment by mikeroosa** [comment]
I removed the link but it looks like Github automatically links to the source file. Is that okay?

**Comment by filiph** [comment]
Totally ok, thanks! And sorry for the delay. 

I'll merge this once flutter-build gets un-broken. If I don't, please don't hesitate to nudge me again. I'm terrible at this.

**Comment by filiph** [comment]
Sorry for the delay!

**Pull request merged**
