### PR TITLE
make Elevated&Outlined&TextButton support onHover&onFocus callback

### PR DESCRIPTION
**Pull request by yk3372**
Signed-off-by: yukai <yk3372@gmail.com>

My Feature issue is https://github.com/flutter/flutter/issues/90686

**What's the PR do?**
My PR aim to make the ElevatedButton/OutlinedButton/TextButton to support onFocus and onHover callback.

**Why need it?**
Recently, I make an application for macOS and Web. I'm writing a NavMenu view like this: [Element-Menu](https://element.eleme.cn/#/en-US/component/menu).
The Menu need onPress/onFocus/onHover functions. 
I have known the TextButton is Powerful，and it's support the normal/pressed/hover/focus/disable states in MaterialState.

But when I try to use the onHover function, it's has no related param.
Then I read the flutter framework source, and found it use the InkWell widget. It support the onHover and onFocus callback.
And the MaterialStateMixin's updateMaterialState function also support the onChanged param.The TextButton to support onFocus and onHover callback is very easy.

**What‘s the meaning of it?**
The flutter is support all the platforms, such as macOS/Windows/TV. These platforms has keyboard and mouse, all need focus/hover state and callback.

Compare before and after:
**Before:**
image
**After**
image

The Demo Code:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> buttonText = ['Button', 'Button', 'Button', 'Button', 'Button', 'Button'];

  static ButtonStyle getButtonStyle(
      {Color? hoverColor, Color? pressedColor, Color? focusColor, Color? disableColor, Color? normalColor}) {
    return ButtonStyle(
      backgroundColor: MaterialStateProperty.resolveWith((states) {
        if (pressedColor != null && states.contains(MaterialState.pressed)) {
          return pressedColor;
        }
        if (hoverColor != null && states.contains(MaterialState.hovered)) {
          return hoverColor;
        }
        if (focusColor != null && states.contains(MaterialState.focused)) {
          return focusColor;
        }
        if (disableColor != null && states.contains(MaterialState.disabled)) {
          return disableColor;
        }
        //默认不使用背景颜色
        return normalColor;
      }),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            for (int i = 0; i < buttonText.length; i++)
              Padding(
                padding: const EdgeInsets.only(bottom: 5, top: 5),
                child: TextButton(
                  onHover: (bool isHover) {
                    if (isHover) {
                      buttonText[i] = 'hover';
                      setState(() {});
                    } else {
                      buttonText[i] = 'Button';
                    }
                  },
                  onFocusChange: (bool isFocus) {
                    if (isFocus) {
                      buttonText[i] = 'focus';
                      setState(() {});
                    } else {
                      buttonText[i] = 'Button';
                    }
                  },
                  onPressed: () {},
                  style: getButtonStyle(
                      normalColor: Colors.blue,
                      pressedColor: Colors.red,
                      hoverColor: Colors.green,
                      focusColor: Colors.orange),
                  child: SizedBox(
                    width: 200,
                    height: 60,
                    child: Center(
                      child: Text(
                        '${buttonText[i]}:$i',
                        style: const TextStyle(color: Colors.black, fontSize: 14),
                      ),
                    ),
                  ),
                ),
              ),
          ],
        ),
      ),
    );
  }
}

```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by yk3372** [comment]
@googlebot I signed it!

**Comment by yk3372** [comment]
@HansMuller @a14n could you review my pr, thanks.

**Review by HansMuller — COMMENTED** [review]
This looks good however I don't see any tests that verify that the onChange or onHover callbacks are called when expected.  You could probably generalize the existing tests a little (including their titles) to cover that.

**Comment by yk3372** [comment]
> This looks good however I don't see any tests that verify that the onChange or onHover callbacks are called when expected. You could probably generalize the existing tests a little (including their titles) to cover that.

I have added the test for onHover and onFocus. Refer to the test in ink_well_test.dart. Thanks

**Review by HansMuller — APPROVED** [review]
LGTM

**Pull request merged**
