### PR TITLE
Reland fix memory leaks for tab selector [prod-leak-fix]

### PR DESCRIPTION
**Pull request by ValentinVignal**
Part of https://github.com/flutter/flutter/issues/141198

Relands https://github.com/flutter/flutter/pull/147403

We need to make sure the bot 'Google testing' passes.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by ValentinVignal** [comment]
cc @polina-c

**Comment by polina-c** [comment]
@chingjun , can you add your review to enable autosubmit to enable google testing?

**Review by chingjun — APPROVED** [review]
RSLGTM to trigger Google Testing

**Comment by polina-c** [comment]
Here is the error:

```
The following assertion was thrown building ...:
		dependOnInheritedWidgetOfExactType<_TabControllerScope>() or dependOnInheritedElement() was called
		before _TabPageSelectorState.initState() completed.
17:32:14.000	U	When an inherited widget changes, for example if the value of Theme.of() changes, its dependent
		widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor
		or an initState() method, then the rebuilt dependent widget will not reflect the changes in the
		inherited widget.
		Typically references to inherited widgets should occur in widget build() methods. Alternatively,
		initialization based on inherited widgets can be placed in the didChangeDependencies method, which
		is called after initState and whenever the dependencies change thereafter.
		The relevant error-causing widget was:
		...
		When the exception was thrown, this was the stack:
		#0      StatefulElement.dependOnInheritedElement.<anonymous closure> (third_party/dart/flutter/lib/src/widgets/framework.dart:5714:9)
		#1      StatefulElement.dependOnInheritedElement (third_party/dart/flutter/lib/src/widgets/framework.dart:5757:6)
		#2      Element.dependOnInheritedWidgetOfExactType (third_party/dart/flutter/lib/src/widgets/framework.dart:4773:14)
		#3      DefaultTabController.maybeOf (third_party/dart/flutter/lib/src/material/tab_controller.dart:409:20)
		#4      _TabPageSelectorState._tabController (third_party/dart/flutter/lib/src/material/tabs.dart:2266:84)
		#5      _TabPageSelectorState._setAnimation (third_party/dart/flutter/lib/src/material/tabs.dart:2315:15)
		#6      _TabPageSelectorState.initState (third_party/dart/flutter/lib/src/material/tabs.dart:2287:5)
		#7      StatefulElement._firstBuild (third_party/dart/flutter/lib/src/widgets/framework.dart:5612:55)
		#8      ComponentElement.mount (third_party/dart/flutter/lib/src/widgets/framework.dart:5457:5)
```

May be we need to make things resilient to usage after disposal?

**Comment by ValentinVignal** [comment]
@polina-c I think I just need to not set the animation in the `initState` but in the `didChangeDependencies` only. Hopefully [fix: Don't use dependOnInheritedWidgetOfExactType in the initState](https://github.com/flutter/flutter/pull/147689/commits/6bf33fc251f97da6b47cb7638eee19aeb25a679b) fixes it

**Comment by polina-c** [comment]
Great!
Can you add test coverage that would catch the issue that you just fixed, in public testing, before internal testing?

**Comment by ValentinVignal** [comment]
> Great! Can you add test coverage that would catch the issue that you just fixed, in public testing, before internal testing?

Sure, the test I added in [test: Add a test that uses DefaultTabController](https://github.com/flutter/flutter/pull/147689/commits/9006f5fee39c4ff810b934eca21a44d0aa0a1d58) fails without my fix in [fix: Don't use dependOnInheritedWidgetOfExactType in the initState](https://github.com/flutter/flutter/pull/147689/commits/6bf33fc251f97da6b47cb7638eee19aeb25a679b)

**Pull request merged**
