### PR TITLE
Fix local import paths.

### PR DESCRIPTION
**Pull request by aam**
This is in attempt to resolve build failure on Windows.

### CODE REVIEW

**Comment by aam** [comment]
Submitting TBR to unbreak the build.

**Comment by Hixie** [comment]
(when landing TBR, please specify a reviewer so that there is a specific person on the hook to do the review)

LGTM

**Comment by aam** [comment]
@Hixie wrote:

> (when landing TBR, please specify a reviewer

How do you normally do that? I picked @a-siva for 'Reviewers', which I thought would be sufficient.

**Comment by Hixie** [comment]
Oh, I totally missed that. That works. Please disregard me. :-)
(I normally mention it in the comment where I say TBR, but that's not necessarily the only way.)

**Pull request merged**
