### PR TITLE
try some lints

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by Hixie** [comment]
I'm surprised you can enable `avoid_returning_this` without problems. In particular, we have code like this:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/edge_insets.dart#L561

**Comment by a14n** [comment]
I don't know why but `avoid_returning_this` does only apply if the method contains at least 2 statements ( see https://github.com/dart-lang/linter/blob/6690b714b8bef67c474aa91837b0a023022e0067/lib/src/rules/avoid_returning_this.dart#L76 and https://github.com/dart-lang/linter/blob/6690b714b8bef67c474aa91837b0a023022e0067/test/rules/avoid_returning_this.dart#L23-L25)

**Comment by Hixie** [comment]
That seems weird. I would leave that one out I think. I don't see why we'd want the first one below to be ok but not the second:

```dart
Foo resolve(TextDirection textDirection) {
  return this;
}

Foo resolve(TextDirection textDirection) {
  assert(textDirection != null);
  return this;
}
```

**Comment by a14n** [comment]
`avoid_returning_this` rule is out.

PTAL

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
