### PR TITLE
Revert "Re-Land "Refactor StrokeAlign to allow double values." (#109805)"

### PR DESCRIPTION
**Pull request by gspencergoog**
This reverts commit b3aba4d9c868aa5a5f8c3a518960f454eca2ba40 because it breaks Google tests.

Clearly, I didn't find all of the instances.  Also, looks like this time we have some rounding error issues or something. The last time it failed, I didn't see any of that. Reverting until I understand why that is.

b/243217872

cc @bernaferrari

### CODE REVIEW

**Review by CaseyHillers — APPROVED** [review]

**Comment by CaseyHillers** [comment]
Merging as it's a revert.

**Comment by bernaferrari** [comment]
Is there any way I can help?

**Comment by gspencergoog** [comment]
@bernaferrari No, I think it requires access to the failing tests to fix. The problem appears to be something along the lines of some rounding or an off-by-one error. Some thin borders disappear entirely, and others are just off by a bit (less than a pixel).  I'll see if I can make a repro case that we can use as a regression test.

**Comment by bernaferrari** [comment]
If I remember well, one thing we removed was if (width == 0) drawRect (now it draws RRect, no special case). It is the only thing I can think of. Feel free to try adding it again and see how the test behaves.

That's the only thing I can think.

**Comment by bernaferrari** [comment]
Try on RoundedRectangleBorder.paint:
```dart
if (width == 0.0) {
  canvas.drawRRect(borderRadius.resolve(textDirection).toRRect(rect), side.toPaint());
} else {
// ...
}
```
or
```dart
if (width == 0.0) return;
```

**Comment by bernaferrari** [comment]
I went ahead and made this: https://github.com/flutter/flutter/pull/109975
If you could test on Google internal and see if the issue still exists, it would be great. I don't know what happened to the bot that did this before.

**Comment by gspencergoog** [comment]
> I don't know what happened to the bot that did this before.

It doesn't kick in until the PR has been approved.

> I have two theories: drawDRRect has a bug and the person that made width == 0 knew this. Or, drawRRect when width == 0 does something which is better than not drawing anything (or drawing the 'wrong' way).

It doesn't have a bug, but I think that perhaps the anti-aliasing behavior is different between the two. I'll take a look.

**Comment by bernaferrari** [comment]
> It doesn't kick in until the PR has been approved.

That's how it worked, but now it doesn't. You merged your and I merged mine without the Google testing happening. It only happened after.

**Pull request merged**
