### PR TITLE
Fix stack filtering

### PR DESCRIPTION
**Pull request by dnfield**
Bug introduced by #48413 

Before this change, falsely returned matches for stack frame lists that were too short, resulting in out of range errors when trying to set reasons.

### CODE REVIEW

**Comment by Piinks** [comment]
Looks like #49917 affected the test runs. Re-running to see if it resolves again.

**Review by Piinks — APPROVED** [review]
LGTM. The checks are re-running now to de-flake. The status should update soon.

**Comment by dnfield** [comment]
Reruns failed with gsutil error, rerunning again.

**Comment by dnfield** [comment]
It seems like it's consistently failing on this PR for some reason (this PR does not affect goldens).

**Comment by Piinks** [comment]
Can you push a new commit on this?

I have a suspicion that Gold is receiving the results, just returning bad state. https://flutter-gold.skia.org/changelists for this PR shows image results, but we've re-run them a few times with different flakes, so I don't know if they all came from the same test run. I am wondering if all the images are actually accounted for.

**Comment by dnfield** [comment]
Pushed an empty commit (3241507).  Now watch it not flake :)

**Comment by Piinks** [comment]
Flaked worse this time, 26 and 7 tryjob flakes across the two linux shards. I have checked the gold dashboard against the flakes and the images do not appear to be there. :( 

Thanks for letting me check that.

**Comment by dnfield** [comment]
Patching in #50088 has made the gold related failures go away.

**Comment by dnfield** [comment]
Hm.  Different failure on mac now:

https://cirrus-ci.com/task/6635508625309696

```
mp/flutter sdk/packages/flutter/test/cupertino/text_field_test.dart: Cupertino cursor golden (TargetPlatform.macOS)                                                         
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _Exception was thrown while running async test code:
Exception: Unexpected Gold tryjobAdd failure.
Tryjob execution for golden file test cupertino.text_field_cursor_test.cupertino_macos.1.png failed
for
a reason unrelated to pixel comparison.
Debug information for Gold:
stdout:
stderr: ERROR: logging before flag.Parse: I0204 01:11:34.738559   64806 auth.go:364] auth.go:364
Read from file /private/tmp/flutter
sdk/bin/cache/pkg/skia_goldens4761/packages/flutter/test/cupertino/serviceAccount.json
Error running command: ''gold client not ready: Gold results fields invalid: Received nil pointer
for GoldResult. At jsonio.go:197 goldclient.go:468 goldclient.go:301 goldclient.go:291
cmd_imgtest.go:338 command.go:835 command.go:919 main.go:42 proc.go:203 asm_amd64.s:1357''
When the exception was thrown, this was the stack:
#0      SkiaGoldClient.tryjobAdd (package:flutter_goldens_client/skia_client.dart:371:9)
<asynchronous suspension>
#1      _AuthorizedFlutterPreSubmitComparator.compare (package:flutter_goldens/flutter_goldens.dart:374:23)
<asynchronous suspension>
#2      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:82:57)
<asynchronous suspension>
#3      AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:924:22)
#6      AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:922:26)
#7      MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:72:20)
#9      MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:52:28)
#10     _expect (package:test_api/src/frontend/expect.dart:116:26)
#11     expectLater (package:test_api/src/frontend/expect.dart:75:5)
#12     expectLater (package:flutter_test/src/widget_tester.dart:385:10)
#13     main.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter/test/cupertino/text_field_test.dart:523:11)
#26     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1102:17)
#28     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1090:35)
(elided 31 frames from class _FakeAsync, dart:async, dart:async-patch, and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Piinks** [comment]
> Hm. Different failure on mac now:
> 
> https://cirrus-ci.com/task/6635508625309696
> 

Looks like this passed on a re-run? Is there a bug for tracking this yet? I can open one to track it down.

**Comment by dnfield** [comment]
Passed on a rerun - I haven't opened a bug yet, if you don't mind that'd be awesome

**Pull request merged**
