### PR TITLE
roll ios-deploy to HEAD

### PR DESCRIPTION
**Pull request by christopherfujino**
Upstream commit https://github.com/ios-control/ios-deploy/commits/4292f673c582a27393504359de7514b916b2ef84

### CODE REVIEW

**Comment by jmagman** [comment]
On this version I'm seeing `[....] Disconnected <> from WIFI.` logging:

```
$ flutter run -d 00008027-001925360106802E
...
An Observatory debugger and profiler on iPad is available at:
http://127.0.0.1:63652/o1xKe9CMH88=/
Activating Dart DevTools...                                      1,305ms
The Flutter DevTools debugger and profiler on iPad is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:63652/o1xKe9CMH88=/
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
[....] Disconnected d83d5bc53967baa0ee18626ba87b6254b2ab5418 from WIFI.
[....] Disconnected d83d5bc53967baa0ee18626ba87b6254b2ab5418 from WIFI.
```
`d83d5bc53967baa0ee18626ba87b6254b2ab5418` isn't even the device I'm `flutter run`ing to, it's another iPhone I have.

https://github.com/ios-control/ios-deploy/pull/442 (and then https://github.com/ios-control/ios-deploy/pull/490)

When I unlock this other device I see the logging from https://github.com/ios-control/ios-deploy/pull/502
```
Skipping d83d5bc53967baa0ee18626ba87b6254b2ab5418 (N71mAP, iPhone 6s, iphoneos, arm64, 13.7, ) a.k.a. 'iPhone 6s'.
```

I think we'll need to suppress the `[....]` ios-deploy prefixed logging since it's confusing.

**Comment by jmagman** [comment]
`ios-deploy` has a `-output <file>` and `--error_output <file>` option, which I think may only include the lldb output we want and not the `ios-deploy` debugging lines? Would have to check though.  So we could output those to a file, or somehow direct those to stdout and throw the actual process stdout on the ground (except maybe when flutter logging is verbose?)

**Comment by christopherfujino** [comment]
> Note to self: i opened the following upstream PRs to make these log messages verbose-only:
> 
> * [Make "Disconnected..." message verbose-only ios-control/ios-deploy#532](https://github.com/ios-control/ios-deploy/pull/532)
> * [Make "Skipping..." log messages verbose only ios-control/ios-deploy#531](https://github.com/ios-control/ios-deploy/pull/531)

These PRs were merged upstream, and I rolled the commits to our mirror, however, we are blocked on building the newest version by https://github.com/flutter/flutter/issues/90403

**Comment by christopherfujino** [comment]
@jmagman rolled to my changes marking the logs in question verbose, could you take another look?

**Review by jmagman — APPROVED** [review]
LGTM (or I'm not reproducing the disconnection state I was seeing before).

**Pull request merged**
