### PR TITLE
Revert "Check for desktop project files before building"

### PR DESCRIPTION
**Pull request by amirh**
Reverts flutter/flutter#48350

Reverting as the change broke `flutter/plugins`'s CI.

### CODE REVIEW

**Review by mklim — APPROVED** [review]
RSLGTM

**Review by stuartmorgan-g — CHANGES_REQUESTED** [review]
Please do not land this. I indicated yesterday that the problem appears to be with the plugin repository, so it should be fixed there rather than reverting a useful, general tooling change.

**Comment by amirh** [comment]
@stuartmorgan the cheapest and quickest thing I know right now how to do to get the `flutter/plugins` repository unblocked again is to revert this.

We can re-land it cheaply once the required changes to flutter/plugins have landed.
I'm more than happy to not land this if by the time the build is green the flutter/plugins changes have landed.

cc @Hixie

**Comment by stuartmorgan** [comment]
https://github.com/flutter/plugins/pull/2476 should be the actual fix

**Pull request closed without merging**
