### PR TITLE
partial revert of gesture config

### PR DESCRIPTION
**Pull request by jonahwilliams**
Unblocks internal roll

### CODE REVIEW

**Comment by jonahwilliams** [comment]
FYI @renyou @zanderso

**Comment by zanderso** [comment]
I pushed some ';'s

**Comment by zanderso** [comment]
Since this is for unblocking the internal roll, this can land over the tree-closure.

**Review by zanderso — APPROVED** [review]

**Comment by renyou** [comment]
@jonahwilliams Is this PR ready to be merged?

**Comment by jonahwilliams** [comment]
Getting it ready now, sorry - notifications + email were getting DDOS'd by issue closed notifications

**Pull request merged**
