### PR TITLE
Remove temporary LayoutBuilder migration flag, defer `markNeedsLayout`

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Looks like I did not need this flag since flutter_portal pinned flutter version to 3.10 in their presubmits. 

I'll create a g3 fix for this since there're only a handful of scuba failures. Also a g3 test revealed a problem with calling `renderObject.markNeedsLayout` directly. It has to be deferred so the render tree is clean during the idle phase and the postFrameCallback phase.
 
## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by LongCatIsLooong** [comment]
scuba change CL: cl/640025627

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by LongCatIsLooong** [comment]
@goderbauer does it make sense to add an assert that makes sure nobody calls `markNeedsLayout` during `idle` / `postFrameCallbacks`? If `markNeedsLayout` was called during those two phases it's impossible (I think?) to recover before the next frame as the tree is finalized (and `RenderBox.markNeedsLayout` even destroys layout cache), and user actions such as hit-testing generally have asserts that ensure the render tree is clean: `assert(!debugNeedsLayout)`.

I don't think we'll be able to just change the `markNeedsLayout` implementation since there are overrides (`RenderBox`), and adding the assert will probably mess up the case where we manually mark a render object dirty in tests. But it feels like a reasonable assert to add. Is there a way to somehow distinguish `renderObject.markNeedsLayout()` calls we manually write in tests?

**Comment by goderbauer** [comment]
Hm, I am not sure how we would practically achieve that given the existing (test) code. Also, do you think the assert is still correct for somebody who uses the rendering layer directly?

**Comment by LongCatIsLooong** [comment]
I don't know how people use the rendering layer directly, but I think 

- "user inputs are handled during the idle phase" is the contract `SchedulerBinding` establishes 
-  our existing `hitTest` implementation does assume the tree is clean, and `RenderBox.markNeedsLayout` / `RenderParagraph.markNeedsLayout` destroys the current layout. 

Given that `mixin RendererBinding on BindingBase, ServicesBinding, SchedulerBinding, GestureBinding, SemanticsBinding, HitTestable` it seems the best place to enforce that would be `RenererBinding` but doing that in the rendering library doesn't sound terribly wrong (as long as `SchedulerBinding` is being used).

**Pull request merged**
