### PR TITLE
Add a delay to the Gallery navigation memory test to give Dart an opportunity to GC

### PR DESCRIPTION
**Pull request by jason-simmons**
See https://github.com/flutter/flutter/issues/23171

### CODE REVIEW

**Review by liyuqian — APPROVED** [review]
LGTM!

**Comment by Hixie** [comment]
Rather than a delay which we keep having to tweak, we should actually trigger a GC.

**Comment by Hixie** [comment]
@goderbauer was looking at doing this for some other tests iirc.

**Comment by goderbauer** [comment]
Yes, I am in a middle of a PR that triggers a GC before some of the benchmarks that are sensitive to GC.

**Pull request merged**
