### PR TITLE
Update args package

### LINKED ISSUE #46009: Make `flutter analyse` print error suggesting `flutter analyze` (spelling)
For the benefit of our British friends.  Something like "unrecognized command, did you mean 'flutter analyze'"?

### LINKED ISSUE #74521: Commands shouldn't be case sensitive
It seems unnecessarily user-hostile to make commands case-sensitive. We could accept `FLUTTER UPGRADE`, `Flutter Upgrade` and any other accidentally typed casing work, I think?

```
[C:\Windows\System32] flutter Upgrade
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Could not find a command named "Upgrade".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

### PR DESCRIPTION
**Pull request by jakemac53**
This version provides suggestions for alternate commands when an unrecognized command is used.

Fixes https://github.com/flutter/flutter/issues/74521
Fixes https://github.com/flutter/flutter/issues/46009

Example output is as follows:

image

@jonahwilliams I noticed there seems to be a fair bit of whitespace here between the suggestions and the usage footer, let me know if you think that is an issue. I am not sure if this is expected.

This feature is tested in the args package, I don't think we need additional tests here. It may affect integration tests if there are any for this case, in which case I can update them.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
LGTM!! 

(Will keep an eye out for test failures, but should be OK)

**Comment by jakemac53** [comment]
Should I actually mark this as closing https://github.com/flutter/flutter/issues/74521? It does seem like consensus was reached around this solution.

**Comment by jonahwilliams** [comment]
Yes, I think we might have another one about typos, one sec

**Comment by jonahwilliams** [comment]
maybe this one too:  https://github.com/flutter/flutter/issues/46009 ?

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
