### PR TITLE
Bugfix: LinearProgressIndicator is referring to wrong color theme for the background color.

### PR DESCRIPTION
**Pull request by dishankjindal1**
Issue with `LinearProgressIndicator` background color via Theme data:

I found this when i was trying to update the background color of the `LinearProgressIndicator` via theme data. Inside `ProgressIndicatorTheme` object there is an `refreshBackgroundColor`. I believe `refreshBackgroundColor` should update the background color in the case of `LinearProgressIndicator`. But in the current SDK it is not updating. It is using `trackColor` which should be backgroundColor only in case of `LinearProgressIndicator`.

If this makes sense. Please review my PR. 

No breaking changes.

### CODE REVIEW

**Comment by dishankjindal1** [comment]
@victorsanni - Can you review my PR?

**Review by Piinks — COMMENTED** [review]
Hey @dishankjindal1 thanks for contributing! 
It looks like there are some failing checks, can you take a look?

**Comment by victorsanni** [comment]
Hi @dishankjindal1! Could you file an issue with the description, as well as use cases, images, and other descriptive info? This is so that our triage team can go through it and verify that it's a valid issue and to see how move forward with this PR.

**Comment by Piinks** [comment]
Hey @dishankjindal1 do you want to continue working on this PR? We do have another PR open that may resolve this, see https://github.com/flutter/flutter/pull/154817

**Comment by victorsanni** [comment]
Hi @dishankjindal1, thank you for the PR. Since we have not heard back in a while, I am going to close it for now. If you would like to continue working on this, we can reopen it. Thank you!

**Pull request closed without merging**
