### PR TITLE
Fixing type in docs for InputDecoration

### PR DESCRIPTION
**Pull request by killermonk**
s/my be entered/may be entered/

### CODE REVIEW

**Comment by HansMuller** [comment]
My my.

LGTM

**Comment by HansMuller** [comment]
I'm going to land this PR, thanks again for the contribution!

**Comment by HansMuller** [comment]
Sorry about the commotion; this PR needed to land on the master branch. Soon it will: https://github.com/flutter/flutter/pull/15540

**Comment by killermonk** [comment]
@HansMuller ironically I first created this to land on the master branch, then said "Oh, wait, I made this in dev"

**Comment by tvolkert** [comment]
It looks like this was merged to the dev branch and not master.  We have a policy of never merging commits on a release branch.  Can you ensure that this was merged at master as well?

**Comment by tvolkert** [comment]
Ah, I commented too quickly - I see that this was reverted now.  Sorry for the spam.

**Pull request merged**
