### PR TITLE
AutocompleteCore => RawAutocomplete

### PR DESCRIPTION
**Pull request by justinmc**
## Description

Renames AutocompleteCore to RawAutocomplete.

It was brought up in discussions on hackers-framework on Discord that elsewhere in the framework we have prepended "Raw" for this kind of root composed widget.  

## Tests

I just updated the naming in the tests.

## Breaking Change

~~This is a breaking change! But AutocompleteCore was just created a few days ago in https://github.com/flutter/flutter/pull/62927.  Can we sneak it in without the full breaking change process?~~

Not a breaking change, see below.

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by Piinks — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
> This is a breaking change! But AutocompleteCore was just created a few days ago in #62927. Can we sneak it in without the full breaking change process?

We should apply the breaking change process to every PR, including this one. However, per that process this is not a breaking change.

**Comment by justinmc** [comment]
Ah right, I thought that applied to the tests in this repo as well. Sounds good  👌

**Comment by Hixie** [comment]
Ah yeah we changed that a few months ago.

**Pull request merged**
