### PR TITLE
[framework] use backdrop filter for stretch overscroll.

### LINKED ISSUE #138940: Problem with the stretching effect when scrolling with backdrop filter blur on 3.16
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. create a scrollable widget
2. add a BackdropFilter with blur inside that scrollable widget

I believe the cause of this problem is in [this PR](https://github.com/flutter/flutter/commit/a0862f1c3f9885136ff986aa75de1aa9bf8e61e0)

### Expected results

Blur stays the same when stretched

### Actual results

Blur halfway disappears when stretched

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const MyHomePage(title: 'Scrolling 3.16.0'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({
    super.key,
    required this.title,
  });

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBody: true,
      extendBodyBehindAppBar: true,
      body: Stack(
        children: [
          ListView.separated(
            itemCount: 1000,
            itemBuilder: (_, i) {
              if (i == 0) {
                return Stack(
                  children: [
                    Container(
                      width: MediaQuery.sizeOf(context).width,
                      height: 80,
                      margin: const EdgeInsets.only(top: 10),
                      color: Colors.black,
                    ),
                    SizedBox(
                      width: MediaQuery.sizeOf(context).width,
                      height: 100,
                      child: ClipRRect(
                        child: BackdropFilter(
                          filter: ImageFilter.blur(sigmaY: 12, sigmaX: 12),
                          child: AppBar(
                            backgroundColor: Colors.white.withOpacity(0.3),
                            title: Text(title),
                          ),
                        ),
                      ),
                    ),
                  ],
                );
              }
              return Container(
                clipBehavior: Clip.antiAlias,
                margin: const EdgeInsets.symmetric(horizontal: 16),
                decoration: BoxDecoration(
                  color: Colors.amberAccent,
                  borderRadius: BorderRadius.circular(16),
                ),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    SizedBox(
                      height: 200,
                      width: MediaQuery.sizeOf(context).width,
                    ),
                    const SizedBox(height: 4),
                    Text('Some text for $i'),
                    const SizedBox(height: 4),
                  ],
                ),
              );
            },
            separatorBuilder: (_, __) => const SizedBox(height: 8),
          ),
        ],
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Before 3.16:
https://github.com/flutter/flutter/assets/4815246/99c3f104-0589-4e1f-bdde-783b9b87db8a

After 3.16:
https://github.com/flutter/flutter/assets/4815246/c0a30f77-2516-476b-895d-2cea4aa44b4c

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1 23B74 darwin-arm64, locale en-DE)
    • Flutter version 3.16.0 on channel stable at /flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision db7ef5bf9f (8 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Android/sdk
    • Java binary at: Library/Java/JavaVirtualMachines/temurin-17.0.7/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10248

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.1 23B74 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category. 
```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
The stretch overscroll effect uses an ImageFilter to stretch the contents of the list. This places the list items in a different saveLayer than the items in the backdrop. As a result, anything that doesn't blend via BlendMode.src or BlendMode.srcOver will look different if the stretch effect is applied; inserting the image matrix filter changes the order of operations of blending.

To fix this, we can apply the stretch effect with a backdrop filter. This will force both the scroll view and anything rendered into the backdrop to be in the same layer, keeping the order of operations the same.

Fixes https://github.com/flutter/flutter/issues/138940

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Due to the lack of alignment handling this stretches the wrong direction, so WIP still

**Comment by Piinks** [comment]
> apply the stretch and include whatever the list background color is, does that make sense

I am not sure I follow. The background color of a scrollable may be defined outside of the scope of the scrollable. 🤔

**Comment by jonahwilliams** [comment]
I'm thinking of ListView and its background color.

**Comment by Piinks** [comment]
> I'm thinking of ListView and its background color.

It does not have one. 😞 

Unless the children of the ListView are opaque/having some color themselves, the ListView is transparent. And the over scroll indicator wraps the list, not the Scaffold. For example, you can see the red of the Scaffold.backgroundColor behind the list here:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final String title;

  const MyHomePage({
    super.key,
    required this.title,
  }) : super();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red,
      body: ListView(
        children: [
          Text('test'),
          Text('test'),
          Text('test'),
          Text('test'),
          Text('test'),
        ],
      ),
    );
  }
}
```

image

**Comment by jonahwilliams** [comment]
ack. It sounds like the backdrop filter would be the least bad solution then.

**Pull request closed without merging**
