### PR TITLE
[Devicelab] Mark microbenchmarks_ios as flaky.

### PR DESCRIPTION
**Pull request by digiter**
## Description

The microbenchmarks_ios test timeout on iOS 13 devices. Mark it flaky to unblock the tree.

## Related Issues

Mitigates https://github.com/flutter/flutter/issues/49635.

## Tests

N/A

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Please don't mark tests as flaky. Either we care about them, in which case a flaky test is a *failing* test and must be fixed, or the test is not valuable, and we should remove it.

The only times we should mark a test flaky are if it's new (we don't yet know if it works) or if we have someone actively working on fixing it, and we know that it isn't something where we'll have to revert something (e.g. the test itself broke somehow).

**Comment by digiter** [comment]
OK, I'm trying to debug this test. Do we need to revert this change?

**Comment by Hixie** [comment]
Do we know when it became flaky?
* If so, we should revert that.
* If not, have we characterized the problem as one that is likely not a severe issue affecting many users, e.g. because we believe it is a race condition involving our test logic, or some such?
  * If so, it is ok to mark it flaky so long as someone is actively debugging it. There should be a bug assigned to the person working on it, with a target milestone.
  * If not, then the tree should be closed as if this was a test that failed all the time, and the team as a whole should all be working to resolve the issue.

**Comment by digiter** [comment]
Reverted my change in https://github.com/flutter/flutter/pull/49807, as microbenchmarks is broken on iOS 13.

**Pull request merged**
