### PR TITLE
Delete test/data/asset_test/main/.packages

### PR DESCRIPTION
**Pull request by jason-simmons**
(this will be generated by flutter update-packages)

### CODE REVIEW

**Comment by jason-simmons** [comment]
@goderbauer

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm

**Comment by Hixie** [comment]
lgtm

my similar pr also adds this to a .gitignore, iirc

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
