### PR TITLE
install goldctl in docker build

### LINKED ISSUE #44786: download_goldctl.sh should retry if the depot_tools clone fails
## Use case
It looks like sometimes cloning depot_tools fails on Cirrus (network issues?).
```
ulimit -S -n 2048
./dev/bots/download_goldctl.sh
Cloning into './depot_tools'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
./dev/bots/download_goldctl.sh: line 4: cd: depot_tools: No such file or directory
./dev/bots/download_goldctl.sh: line 6: ./cipd: No such file or directory

Exit status: 127
```
https://cirrus-ci.com/task/5949937388355584?command=main#L0

## Proposal

Consider a sleep and retry as is done in a few other tests.  With increased control logic, it may be a good time to migrate to a dart test.

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

This moves the downloading and installing of `goldctl` to `dev/ci/docker_linux/Dockerfile` for the Cirrus linux tests. Previously, 10 Linux shards were running the `install_goldctl.sh` script as part of their "main" step. This speeds up running of tests and avoids occasional failure to download the tool, as seen in #44786.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/44786

## Tests

I did not change any tests as my changes are exercised by the existing framework tests, which depend on `goldctl` being installed on the host to conduct goldens tests.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by goderbauer** [comment]
Is this PR still relevant? Or should we close it?

**Comment by christopherfujino** [comment]
@goderbauer yes, still relevant, I think I can land this soon :)

**Comment by Piinks** [comment]
FYI @kjlubick

**Review by Piinks — APPROVED** [review]
LGTM! This is great! Thanks!
I checked the Gold dashboard for results from this PR and all of the linux ones are accounted for ([see here](https://flutter-gold.skia.org/search?fdiffmax=-1&fref=false&frgbamax=255&frgbamin=0&head=true&include=false&issue=46640&limit=50&master=true&match=name&metric=combined&neg=false&new_clstore=true&offset=0&patchsets=16&pos=true&query=Platform%3Dlinux%26source_type%3Dflutter&sort=desc&unt=false)).

**Comment by Piinks** [comment]
This would pin us at a specific version for Linux shards, but not Mac and Windows. My only concern is if having multiple versions across tests shards will create an issue, I would defer to @kjlubick.

**Comment by kjlubick** [comment]
goldctl doesn't change all that often and if it does, I try to backward compatible. I don't envision an issue, unless the Docker image is rarely re-built/updated.

**Comment by christopherfujino** [comment]
@kjlubick sounds good. For posterity's sake, if in the future there is a breaking change that the Docker image has not picked up, a comment update PR to the `Dockerfile` will trigger a rebuild and pick up the latest `goldctl`.

**Pull request merged**
