### PR TITLE
Fix incorrectly named "debug" prefix

### LINKED ISSUE #111874: (Willing to PR) `_debugReportException` should be `_reportException` indeed, otherwise seems misleading to the readers because it is not debug-only
## Steps to Reproduce

Hi thanks for the wonderful framework! When reading the source code, I see:

https://github.com/flutter/flutter/blob/05c70528752ac4a675ad19447b0483dc695779f5/packages/flutter/lib/src/rendering/object.dart#L1531-L1550

and various places which calls it. The problem is, if I understand correctly, "debugSomething" always means "this thing is only valid when in debug mode and will disappear in release mode", such as debugDoingThisResize, debugDoingThisLayout, etc. For completeness, I briefly glances through other symbols/functions with name ` debug` and `_debug.*(` in `rendering/objects.dart`, and find that they are used inside `assert(...)` or used with `kDebugMode`.

However, this method name indeed reports error unconditionally, i.e. report both in debug and release. That is pretty reasonable, because we surely want error reports in release builds. The problem is the naming - the name seems confusing to the readers IMHO.

Thus, I propose to simply rename _debugReportException to _reportException.

I am willing to make a PR. However, given that this is just a code renaming, I wonder whether I should create a PR?

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

### PR DESCRIPTION
**Pull request by fzyzcjy**
Close #111874

Please read discussions there for why this PR is made :)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by chunhtai — COMMENTED** [review]
Change looks reasonable, there are also some _debugReportException in framework.dart and layout_builder can you update those as well?

**Comment by fzyzcjy** [comment]
@chunhtai sure, done

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by cbracken — APPROVED** [review]
lgtm! Please request a test exemption from @hixie.

**Comment by fzyzcjy** [comment]
@cbracken done https://discord.com/channels/608014603317936148/608018585025118217/1035696084963577957

Btw, is it polite to ask for test exemption directly when creating this PR or I should wait for a few days?

**Comment by Hixie** [comment]
test-exemption: code refactor with no semantic change

**Comment by chunhtai** [comment]
> Btw, is it polite to ask for test exemption directly when creating this PR or I should wait for a few days?

If you think the PR should be exempted, I don't think there is an inappropriate grace period to ask for NTE as far as I know.

**Comment by fzyzcjy** [comment]
@chunhtai I see, thank you

**Pull request merged**
