### PR TITLE
Replace dynamic by Object/Object? in router.dart

### LINKED ISSUE #77357: Replace dynamic by Object or Object? in router.dart file
## Use case
I want to avoid using dynamic in my application in favor for Object and Object? for nullable cases.

## Proposal
Since the introduction of null safe, i think it's better for the flutter repo to decrease it's usage of dynamic in favor of Object? and Object.

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/router.dart

### PR DESCRIPTION
**Pull request by aminedakhlii**
Closes #77357

### CODE REVIEW

**Comment by aminedakhlii** [comment]
@goderbauer I messed things up while re-basing in the previous PR so here is a new cleaner one, could you review it?

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change.

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
@aminedakhlii The test failure looks unrelated, can you try rebase off the latest master branch?

**Comment by aminedakhlii** [comment]
@chunhtai done

**Pull request merged**
