### PR TITLE
Add gradle wrapper to new project template.

### LINKED ISSUE #9842: Android Studio updated gradle version of my project and now flutter run fails
I opened my Flutter project in Android Studio to edit some native Android code. Android Studio told me that I should immediately update the gradle version of my project because of important bug fixes (the messages sounded rather urgent). I foolishly clicked "upgrade gradle" and now my project doesn't build with `flutter run` anymore 😞 

```shell
C:\src\firebase_messaging\example [master]> flutter run
Running 'flutter packages get' in example...          0.7s
Launching lib/main.dart on Nexus 6P in debug mode...
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\src\firebase_messaging\example\android\app\build.gradle' line: 14

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 3.3. Current version is 3.2. If using the gradle wrapper, try editing the distributionUrl in C:\src\firebase_messaging\example\android\gradle\wrapper\gradle-wrapper.properties to gradle-3.3-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error running gradle: Exit code 1 from: C:\Program Files\Android\Android Studio\gradle\gradle-3.2\bin\gradle.bat app:properties
Running 'gradle assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\src\firebase_messaging\example\android\app\build.gradle' line: 14

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 3.3. Current version is 3.2. If using the gradle wrapper, try editing the distributionUrl in C:\src\firebase_messaging\example\android\gradle\wrapper\gradle-wrapper.properties to gradle-3.3-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle build failed: 1
```

Building and Running from Android Studio still works fine, but I miss that hot reload...

/cc @mit-mit @jakobr-google

### PR DESCRIPTION
**Pull request by jakobr-google**
Android Studio is heavily pushing the Gradle wrapper when you open our projects in Studio. It's also pushing an upgrade to the gradle plugin, which requires Gradle 3.3. However, Studio ships with Gradle 3.2, so if you choose to upgrade, the project will not build.

Using the gradle wrapper makes Studio happier, so let's update our new project template to use it.

We could also update our build.gradle to require v2.3.1 of the Android Gradle plugin, so Studio won't prompt to upgrade the dependency for us, but I've left that for another change.

Fixes #9842.

### CODE REVIEW

**Review by abarth — CHANGES_REQUESTED** [review]
Please do not check in binary files, such as `gradle-wrapper.jar`.

I'm also skeptical about the `gradlew` shell script.  For example, what happens when that file changes?

**Comment by mit-mit** [comment]
I'll share some context on this change in a few hours

**Comment by Hixie** [comment]
Before we add more files to the template, I think we should make sure the template contains a README that documents, for each file in the template:

* What the file is for
* Why you would edit that file
* How to verify that the edits are valid
* How to test the file

The template is growing really big and it's not at all clear why some of these files are part of the user code and not just part of the framework.

**Comment by mit-mit** [comment]
Some additional notes are available in go/gradlenotes

**Comment by iNoles** [comment]
You could do gradle wrapper to generate gradle wrapper. It supposed to take gradle version from the wrapper function in a build.gradle.

**Comment by Hixie** [comment]
This is being tracked in https://github.com/flutter/flutter/issues/10236.

Should we close this PR for now, since it seems this is not going to land as-is?

**Comment by mit-mit** [comment]
We can close this PR, yes, but lets track the work in the existing bug https://github.com/flutter/flutter/issues/9842, please

**Pull request closed without merging**
