### PR TITLE
enable lint prefer_for_elements_to_map_fromIterable

### PR DESCRIPTION
**Pull request by a14n**
## Description

enable lint [prefer_for_elements_to_map_fromIterable](https://dart-lang.github.io/linter/lints/prefer_for_elements_to_map_fromIterable.html).

## Related Issues

None

## Tests

None

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by dnfield — COMMENTED** [review]
I find this harder to read than the original.  I'd be open to hearing other feedbak though.

**Comment by jonahwilliams** [comment]
I prefer the if/for elements to Iterable methods, though I could understand the other side as well. I generally dislike Iterable chains because it adds a lot of overhead compared to a for loop. The if/for elements seem like a good compromise.

**Comment by a14n** [comment]
A big advantage of _for-elements_ over `Map.fromIterable` is better type safety. You avoid `dynamic` and explicit casts.

**Comment by dnfield** [comment]
Ahh, I see.

It'd be nice if they had defined `fromIterable` as taking a third generic type for the closures, i.e. 
```
Map<T, K, V>.fromIterable(
  Iterable<T> iterable, {
  K key(
    T element
  ),
  V value(
    T element
  )
})
```

but oh well.

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by a14n** [comment]
>It'd be nice if they had defined fromIterable as taking a third generic type for the closures

Unfortunately it's not possible today. See dart-lang/sdk#26391

**Comment by dnfield** [comment]
Yeah I sometimes wish named constructors just acted more like static methods haha

**Pull request merged**
