### PR TITLE
Only skip license initialization on `flutter test` binding

### PR DESCRIPTION
**Pull request by jiahaog**
Previously, license initialization is skipped for all forms of `TestWidgetsFlutterBinding`. This PR changes it to only do so for `AutomatedTestWidgetsFlutterBinding`.

Rationale: License generation is only skipped by the Flutter tool for `flutter test`. Other forms of testing still have proper license file generation, and it is useful to write tests involving license pages. For example, there was a recent breakage internally (b/187074413), and it would be nice if we could write Integration Tests for this.

I did a internal presubmit of this and there are no breakages caused by this. Since this PR has passing checks, I don't think it is a breaking change.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM, seems like a good change!

**Comment by jiahaog** [comment]
The Google tests included some unrelated changes in my PR, breaking the build. Already ran a global presubmit of this patch, so manually marking the status to passed.

**Comment by jiahaog** [comment]
I hit into this earlier when trying to write an Integration Test internally for a regression, where I found that it is a lot of boilerplate for setting up a driver test to test this, when it's supposedly easy to do so with flutter_test except for this override here.

I don't know, aren't tests today already behaving rather differently when used with `flutter test` and `flutter run` (w.r.t async / frame semantics)? Or do you think it will be better for the Tool to support generating the license artifacts so that `flutter test` can be used to test licenses instead?

**Comment by Hixie** [comment]
Ah, got it. I think a better fix is probably that integration tests need to use a different binding subclass.

The Live test binding is specifically for debugging `flutter test` tests in a `flutter run` scenario. There's a lot of work in there to make sure that the frame semantics are the same (or can be, based on configuration).

**Comment by jiahaog** [comment]
Even if we have a separate `TestWidgetsFlutterBinding` binding for Integration Tests, I think we will need to tweak the signature of `initLicenses` as well. IIUC in a another child class of `TestWidgetsFlutterBinding`, you can't override `initLicenses` to revert the behavior of the method to that of the parent of `TestWidgetsFlutterBinding`. 

Perhaps instead of having a `initLicenses` method, we can change it to be a `shouldInitLicenses` boolean on `TestWidgetsFlutterBinding`? Then different bindings can change the boolean appropriately, without knowing the implementation details of *how* to init licenses.

**Comment by Hixie** [comment]
Sure.

**Pull request merged**
