### PR TITLE
first addition of _embedder.yaml

### PR DESCRIPTION
**Pull request by sethladd**
Configuring our analyzer world through a file.

### CODE REVIEW

**Comment by sethladd** [comment]
cc @pq please take a look

fyi @abarth and @Hixie  for what we are doing. There will be many more options here, including lints. With this file, we can bundle and distribute our configuration of the analyzer.

also FYI @johnmccutchan

**Comment by pq** [comment]
LGTM

**Comment by abarth** [comment]
Neat!  LGTM

**Comment by sethladd** [comment]
Thanks!

**Pull request merged**
