### PR TITLE
removed obsolete timelineArgumentsIndicatingLandmarkEvent

### LINKED ISSUE #101313: Improve the Timeline performance
The poor performance of the Timeline event is causing us to have to hide performance tracking tools behind flags: https://github.com/flutter/flutter/pull/100926

One issue is that `thread_info` calls from the Dart SDK are very slow on iOS ( https://github.com/dart-lang/sdk/issues/47850 ).

This issue is to track all the suggestions and attempts I've made to make things faster over the past few days, hopefully culminating in a change that speeds them up.

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/101313

When this feature was landed in flutter it created a 15% performance regression (https://github.com/flutter/flutter/pull/12058#issuecomment-329841532)

From my local testing with our build_bench.dart microbenchmarks I'm seeing similar results with `debugProfileBuildsEnabled` turned on.  The parameters were added for a feature in the Dart observatory that no longer exists.

test-exempt: no added logic, removed logic for performance reasons

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by dnfield — COMMENTED** [review]
This LGTM if it LGT @kenzieschmoll

**Comment by dnfield** [comment]
I'm assuming this is fine to remove based on my read of devtools - if that's wrong we should definitely add some kind of test that would fail in this repository for it.

**Review by kenzieschmoll — APPROVED** [review]

**Comment by goderbauer** [comment]
From triage: Even though the "Google testing" check didn't seem to update, it looks like this is causing some legit failures in google3 (see "details" link of the check):

```
ERROR: mobile/flutter/testing/integration_test/perf/lib/extension.dart

201: arguments: timelineArgumentsIndicatingLandmarkEvent, Undefined name. #undefined_identifier
```

@gaaclarke Can you take a look and maybe create a g3fix?

**Comment by gaaclarke** [comment]
We could potentially keep that field around but make it nullable and giving it a "deprecated" annotation.  I'd rather just delete it since people should be using it.  It was leaking dart implementation details all the way into the framework API so it was a bad idea to begin with.

**Comment by jiahaog** [comment]
Thanks, the forward fix looks good

**Comment by gaaclarke** [comment]
The forward fix for google has landed.

**Comment by kenzieschmoll** [comment]
There may be merge conflicts from https://github.com/flutter/flutter/pull/101602.

**Comment by CaseyHillers** [comment]
Sorry about Google Testing being blocked! Feel free to submit this as is, or if you want to verify this with google3 presubmit you can push an empty commit.

**Pull request merged**
