### PR TITLE
Fixed Incorrect Translation Generation (l10n) #67217

### PR DESCRIPTION
**Pull request by ArishSultan**
* Added a separate format to generate `decimal` and `percent` based translations.

## Description

As mentioned in the issue, the gen-l10n was not generating the right output if decimalPattern was specified inside the .arb file. this PR fixes the issue.

## Related Issues

This PR is related to issue #67217

## Tests
Its my first contribution, i was not able to figure out how should i write test for this.
but still i tested it by generating the output for both cases using the gen-l10n tool and it was fine.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

### CODE REVIEW

**Comment by ArishSultan** [comment]
Any one to review ?

**Comment by jonahwilliams** [comment]
FYI @shihaohong can you take a look at this?

**Comment by ArishSultan** [comment]
@shihaohong are you there ?

**Review by shihaohong — COMMENTED** [review]
Hi, sorry about the delay. I've taken a look and there are two issues:
1) the generated getter uses an `int`, but that needs to be updated to take a `double` since decimals and percentages can take `double`s.
2) this change will likely need a test to make sure we do not regress. A good place to start is [gen_l10n_test.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/gen_l10n_test.dart). It has a bunch of integration tests and we should add one or two for decimal and percentage patterns here.

**Comment by ArishSultan** [comment]
Ok i am on it, i have also faced same issue while generating currency format, i will fix that too.

**Comment by jonahwilliams** [comment]
@ArishSultan are you still working on this?

**Comment by ArishSultan** [comment]
Yes i am just a little more time

**Comment by ArishSultan** [comment]
are these build fails related to my work ?

**Comment by jmagman** [comment]
@ArishSultan Your PR has 1477 file changes.  Please rebase your branch and force push, or close this PR and create a new one.

**Comment by ArishSultan** [comment]
@jmagman Thanks

**Comment by jonahwilliams** [comment]
@ArishSultan this PR includes way too many changes. It needs to be recreated on a fresh branch. I'm going to close this, please feel free to open a new PR whenever you are ready

**Comment by patmuk** [comment]
@jonahwilliams this PR fixes a really trivial and obvious error.
@ArishSultan put patiently a lot of work in it to make it accepted. I totally understand his frustration when facing one administrative step after another and that he finally gave up. 

So, instead of just closing it, because master overtook it with too many changes, have the curtesy to finish this PR yourself. 
It is a community work and not the lone work of individual community contributors!

**Pull request closed without merging**
