### PR TITLE
Pin Gallery to version with updated settings.gradle

### PR DESCRIPTION
**Pull request by blasten**
Imports https://github.com/flutter/gallery/commit/0e7835661dad4af7d745d4751fd1958a66fc03e1

### CODE REVIEW

**Review by HansMuller — COMMENTED** [review]
LGTM

**Comment by blasten** [comment]
Merging to fix the tree

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by flar** [comment]
@blasten @HansMuller This change caused a "regression" in the amount of memory we use for the layer caches, particularly the "99th percentile layer cache memory". That basically means we are caching more or larger layers than we had previously, but only in a small number of critical frames (slightly more than 1% of them). This is, in itself, not a bug unless it is unexpected. Operations that can cache layers would be Opacity widgets or ImageFiltered widgets or using the filterQuality property on any of the Transform widgets. Since we saw no changes in the frame timings, then this new caching behavior didn't create a performance issue unless the 3mb used for caching the layer is significant. Here is the Skia perf for the benchmark with the regression highlighted`:

https://flutter-flutter-perf.skia.org/e/?begin=1644033618&end=1644288314&keys=X41029fd37de71baf2de789a3414c35f0&num_commits=50&request_type=1&xbaroffset=27478

It's also worth pointing out that the benchmark used to have occasional spikes up to the current value so this could be as subtle as staying just a little bit longer on a frame that was using a layer cache - which would cause the reading to appear in more frames and show up in the 99th percentile whereas before it might have been in the 99.5th percentile. The "worst" reading did not change so it doesn't take much for the reading to start affecting the 99th percentile figures more consistently. The average readings didn't change by much either (they are visible near the horizontal axis if you hunt for them with the mouse), so there were only a few frames affected. If you click on the 99th percentile graph line and click on "hide highlighted" then the other readings will become more visible on the plot.

**Pull request merged**
