### PR TITLE
Fix `RangeSlider` semantics node size

### PR DESCRIPTION
**Pull request by TahaTesser**
part of https://github.com/flutter/flutter/issues/114225 

### Description

This PR fixes semantics node size for `RangeSlider` 

Current behavior simply divides the node size in half.  This doesn't match when testing on Android.

### Android

| Left | Right |
| --------------- | --------------- |
|  |  |

### Flutter

| Before | After |
| --------------- | --------------- |
|  |  |

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by HansMuller** [comment]
Does this all work correctly if the text direction is RTL? I expect that there should be a RTL version of the test.

**Comment by TahaTesser** [comment]
>  Does this all work correctly if the text direction is RTL? I expect that there should be a RTL version of the test.

Sure, we can add a semantics test for RTL

However, it looks like there is a bug in matchSemantics. Even if I match all everything, it fails in RTL in the last node. 
I will look into it further in an isolated test.


Semantics debug tree
```console
SemanticsNode#5
 │ Rect.fromLTRB(0.0, 0.0, 800.0, 600.0)
 │ flags: scopesRoute
 │
 └─SemanticsNode#6
   │ Rect.fromLTRB(0.0, 0.0, 800.0, 600.0)
   │
   ├─SemanticsNode#1
   │   Rect.fromLTRB(526.4, 276.0, 574.4, 324.0)
   │   actions: decrease, increase
   │   flags: hasEnabledState, isEnabled, isSlider
   │   value: "10%"
   │   increasedValue: "15%"
   │   decreasedValue: "5%"
   │   textDirection: rtl
   │
   └─SemanticsNode#2
       Rect.fromLTRB(676.8, 276.0, 724.8, 324.0)
       actions: decrease, increase
       flags: hasEnabledState, isEnabled, isSlider
       value: "30%"
       increasedValue: "35%"
       decreasedValue: "25%"
       textDirection: rtl
```
test:
```dart
              matchesSemantics(
                isEnabled: true,
                isSlider: true,
                hasEnabledState: true,
                hasIncreaseAction: true,
                hasDecreaseAction: true,
                value: '10%',
                increasedValue: '15%',
                decreasedValue: '5%',
                rect: const Rect.fromLTRB(526.4, 276.0, 574.4, 324.0),
              ),
              matchesSemantics(
                isEnabled: true,
                isSlider: true,
                hasEnabledState: true,
                hasIncreaseAction: true,
                hasDecreaseAction: true,
                value: '30%',
                increasedValue: '35%',
                decreasedValue: '25%',
                rect: const Rect.fromLTRB(676.8, 276.0, 724.8, 324.0),
              ),
```

Result:
```dart
 Actual: SemanticsNode:<SemanticsNode#5(Rect.fromLTRB(0.0, 0.0, 800.0, 600.0), flags:
[scopesRoute])>
   Which: rect was: Rect.fromLTRB(676.8, 276.0, 724.8, 324.0)
```

**Comment by Piinks** [comment]
> it looks like there is a bug in `matchSemantics`

Is there a bug filed for this? @chunhtai can you take a look and confirm?

**Comment by TahaTesser** [comment]
> 

I've investigate the problem, filed an issue https://github.com/flutter/flutter/issues/115079

Also fixed the tests here.

**Review by HansMuller — APPROVED** [review]
Nice fix. Please add a TODO comment above the workaround for https://github.com/flutter/flutter/issues/115079 so that we'll remember to fix it.

**Pull request merged**
