### PR TITLE
Use the correct set of options to analyze Flutter packages.

### PR DESCRIPTION
**Pull request by pylaligand**
This will soon start breaking the Fuchsia build.

### CODE REVIEW

**Comment by Hixie** [comment]
Are there warnings we should be fixing? Why disable this?

**Comment by pylaligand** [comment]
This affects only the Fuchsia build. I don't know which standards you want to apply to Flutter code and which means you use to enforce them, and whether it even makes sense to enforce on the Fuchsia side.

**Comment by Hixie** [comment]
The analysis standards we apply are pretty strict:
https://github.com/flutter/flutter/blob/master/.analysis_options

Our build goes red if anything violates those options, so we're very strict about following them. I would leave all the checks on even on the Fuchsia side, just in case it catches something that we aren't expecting. We are eager to fix anything you run into that we don't know about.

**Comment by pylaligand** [comment]
SGTM! Updated the build files to use the set of options you mentioned.

**Comment by Hixie** [comment]
LGTM

**Comment by pylaligand** [comment]
It looks like Flutter build bot is unhappy. How do I re-trigger a build?

**Comment by Hixie** [comment]
We have to fix the problem first.

**Comment by pylaligand** [comment]
Where do I see what the issue is? There's no actionable link on the failed check's line.

**Comment by Hixie** [comment]
We fixed it. It was some Windows thing.

To be clear, flutter-build isn't anything to do with your PR, it's the status of our bots. It goes red when you shouldn't check in because the build is red.

**Pull request merged**
