### PR TITLE
[flutter_tools] split application package factory dependencies

### PR DESCRIPTION
**Pull request by jonahwilliams**
Remove the iOS/Android dependencies from the application package factory. This will make it easier to migrate it and device.dart, which are both super common dependencies. This moves the ios/android application package classes into {ios/android}/application_package.dart

#71511

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
LGTM!

**Comment by jonahwilliams** [comment]
I think the g3 failure is a merge issue - I don't see any actual usage of the interface so I'm going to land once the tree is green.

**Comment by jmagman** [comment]
> I think the g3 failure is a merge issue - I don't see any actual usage of the interface so I'm going to land once the tree is green.

Were you rebased on https://github.com/flutter/flutter/pull/79342/files#diff-e24013dd662b438105ef0c1d965a955e4344a6481bc2e6cbe87a30357314fb69L10 ?

**Comment by jmagman** [comment]
Oh I see, g3 doesn't have https://github.com/flutter/flutter/pull/79342 yet, so it thinks `code_signing` still needs it, but that import was removed.
```
ERROR: third_party/dart/flutter_tools/lib/src/ios/code_signing.dart
10: import '../application_package.dart'; (warning) Unused import: '../application_package.dart'. #unused_import
```

**Comment by jonahwilliams** [comment]
Ehh, cost of doing business :)

**Pull request merged**
