### PR TITLE
Fix VMIsolateRef type declaration

### LINKED ISSUE #7661: devicelab fails when run in checked mode
I ran a devicelab task in checked mode and got:
```
Will retry in 0:00:00.200000.
VM service not ready yet: type 'VMIsolateRef' is not a subtype of type 'VMIsolate' of 'isolate' where
  VMIsolateRef is from package:vm_service_client/src/isolate.dart
  VMIsolate is from package:vm_service_client/src/isolate.dart
```
...a bunch of times then it failed.

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/7661

### CODE REVIEW

**Comment by jason-simmons** [comment]
@yjbanov

**Comment by eseidelGoogle** [comment]
Does this code analyze clean in strong_mode?

**Comment by yjbanov** [comment]
> Does this code analyze clean in strong_mode?

My thoughts exactly. I thought we analyzed everything.

**Review by yjbanov — APPROVED** [review]

**Comment by jason-simmons** [comment]
"flutter analyze --flutter-repo" does analyze the dev/devicelab sources.

But these lines aren't flagged by the analyzer because VMIsolate is a subclass of VMIsolateRef.

**Pull request merged**
