### PR TITLE
[CP] Point kotlin message in `gradle_errors.dart` towards new place

### LINKED ISSUE #149856: [CP] Update Flutter Fix log on How to Update Kotlin Gradle Plugin
### Issue Link

https://github.com/flutter/flutter/issues/144454

### Target

stable

### PR Link

https://github.com/flutter/flutter/pull/145936

### Changelog Description

Update Flutter Fix log on how to update Kotlin Gradle Plugin that was introduced in Flutter 3.19.x

### Impacted Users

All Flutter devs

### Impact Description

Users no longer need to figure out by themselves on how to update their Kotlin Gradle plugin when needed

### Workaround

Reading the breaking change document here https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply. Or ask for a support in Discord or Stackoverflow.

### Risk

low

### Test Coverage

yes

### Validation Steps

_No response_

### PR DESCRIPTION
**Pull request by brainwo**
Cherry pick request of https://github.com/flutter/flutter/pull/145936 to stable

Update Flutter Fix log on how to update Kotlin Gradle Plugin that was introduced in Flutter 3.19.x

Closes #149856

### CODE REVIEW

**Comment by christopherfujino** [comment]
@reidbaker I'm leaning towards rejecting this as not being critical enough to warrant cherrypicking, unless you disagree. WDYT?

**Comment by brainwo** [comment]
I'm sorry for interjecting, but I would argue this is an important fix that needed to be merge. It shows the responsibility and respect to other's people time.

I'm not familiar to Flutter's merging process myself, but I see this wouldn't hurt even though it's not critical.

It just so sad that for this past months, people are misguided when they shouldn't be since we already have this fix that hasn't be merged.

**Comment by reidbaker** [comment]
@christopherfujino I think the pick is safe enough as to critical enough I think migrations have the most value on the following release of the same type like stable to stable. I cant remember what the update patch schedule is but my answer is that if we were shipping a patch then I would lean towards taking this CP but I would not ask that we do a release solely for this CP.

**Comment by christopherfujino** [comment]
> @christopherfujino I think the pick is safe enough, as to critical enough, I think migrations have the most value on the following release of the same type like stable to stable. I cant remember what the update patch schedule is but my answer is that if we were shipping a patch then I would lean towards taking this CP but I would not ask that we do a release solely for this CP.

Thanks for the context

**Review by zanderso — APPROVED** [review]

**Review by itsjustkevin — APPROVED** [review]

**Pull request merged**
