### PR TITLE
Rename Border.uniform() -> Border.fromSide()

### PR DESCRIPTION
**Pull request by tvolkert**

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
When I read `fromSide` I end up wondering which side.  IMO `uniform` is clearer.

**Comment by tvolkert** [comment]
fwiw, I can see both sides of it (truly no pun intended) and don't feel strongly either way.  I like both `fromSide()` and `uniform()`.

**Comment by dnfield** [comment]
Maybe `fromUniformSide`? Although that's getting back closer to where this all started.  What do you think @jonahwilliams ?

**Comment by Hixie** [comment]
`fromBorderSide` maybe?

The problem with `uniform` is that that means the same as `all` and it's not clear why you'd use one or the other from the name.

**Comment by tvolkert** [comment]
`fromBorderSide` is definitely unambiguous.  +1 from me.

**Comment by dnfield** [comment]
My understanding is that `const` is the disambiguator here - you use this one when you want a const version and are willing to explicitly provide a borderside rather than the individual properties that `.all` expects.  But `fromBorderSide` is a bit clearer at least.

**Comment by dnfield** [comment]
LGTM

**Pull request merged**
