### PR TITLE
Remove workaround for compiler dill-initialization.

### PR DESCRIPTION
**Pull request by aam**
Workaround is not needed since real fix has landed in dart sdk: https://dart-review.googlesource.com/c/sdk/+/62729.

### CODE REVIEW

**Comment by aam** [comment]
@a-siva , PTAL

**Review by a-siva — APPROVED** [review]

**Comment by aam** [comment]
The test failure shows up as broken assertion when run against vm with enabled assertions:
```
[   +1 ms] Evicting dirty assets
[   +1 ms] ext.flutter.evict: {value: AssetManifest.json, isolateId: isolates/9702818}
[   +3 ms] Compiling function : 'dart:developer_::__runExtension@4383715' @ token 2134, size 1886
[        ] Compiling Class 'Library:'dart:developer' Class: ServiceExtensionResponse'
[   +1 ms] --> 'dart:developer_::__runExtension@4383715' entry: 0x7fb1d52f2a60 size: 2472 time: 2815 us
[        ] Compiling function : 'package:flutter/src/foundation/binding.dart_BindingBase_registerServiceExtension_<anonymous closure>' @ token 13818, size 2154
[        ] ../../third_party/dart/runtime/vm/kernel_binary.h: 183: error: expected: (size_ >= 4) && (offset >= 0) && (offset <= size_ - 4)
[        ] Dumping native stack trace for thread 309ed
[   +7 ms]   [0x000000000249fe1f] Unknown symbol
[   +5 ms]   [0x000000000249fe1f] Unknown symbol
[        ] -- End of DumpStackTrace
[  +11 ms] Service protocol connection closed.
```

**Comment by aam** [comment]
When initializing from existing kernel file versus when running from scratch, incremental compiler produces different result which seems to be the root cause:

```
$FH/flutter/examples/flutter_gallery$ $FH/engine/src/out/host_debug_unopt/dart-sdk/bin/dart $FH/engine/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot --sdk-root $FH/engine/src/out/host_debug_unopt/flutter_patched_sdk/ --strong --verbose --target=flutter --no-link-platform --incremental --packages .packages --output-dill build/app.dill --depfile build/snapshot_blob.bin.d lib/main.dart
...
$FH/flutter/examples/flutter_gallery$ ll build/app.dill
-rw-r--r-- 1 x x 16093560 Aug 27 11:16 build/app.dill

$FH/flutter/examples/flutter_gallery$ $FH/engine/src/out/host_debug_unopt/dart-sdk/bin/dart $FH/engine/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot --sdk-root $FH/engine/src/out/host_debug_unopt/flutter_patched_sdk/ --strong --verbose --target=flutter --no-link-platform --incremental --packages .packages --output-dill build/app.dill --depfile build/snapshot_blob.bin.d lib/main.dart
...
$FH/flutter/examples/flutter_gallery$ ll build/app.dill
-rw-r--r-- 1 x x 16006861 Aug 27 11:16 build/app.dill
```

cc @jensjoha

**Comment by aam** [comment]
Created https://github.com/dart-lang/sdk/issues/34280 to track incremental compiler issue

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/71700 hopefully with the fix.

**Comment by aam** [comment]
The reason why less than bit-perfect dill files break integration tests(flutter_attached_test, hot_reload_test) is that these tests use FlutterTesterDevice which is built as such that there is no separation(normally closed by DevFS) between kernel file produced by compiler and kernel file loaded by vm. While vm loads a kernel file (from `build/app.dill`) incremental compiler updates exact same `build/app.dill` file.

**Comment by jensjoha** [comment]
Am I right in assuming that there is no longer anything for me to see here?

**Comment by aam** [comment]
@jensjoha wrote:
> Am I right in assuming that there is no longer anything for me to see here?

Right.

**Pull request merged**
