### PR TITLE
Preload canvaskit, potentially saving 25% load time for Web display

### PR DESCRIPTION
**Pull request by Neamar**
When using the default web renderer, every Flutter app has a dependency chain: from `main.dart.js`, we need to load `canvaskit.js` from unpkg.com, and finally load `canvaskit.wasm`.

Each of this download is currently done sequentially: `main.dart.js` has to be fully downloaded, parsed and executed to trigger the next step. Since the file is 2MB even in the smallest possible project, this is already slow, and even slower on an old-ish computer.
Then, the browser needs to DNS resolve unpkg.com, do a SSL handshake, get the file, parse and execute `canvaskit.js`.
Finally, `canvaskit.js` needs to get another 2.5MB (compressed) `canvaskit.wasm` file, unzip and execute (even though modern browsers can parse wasm while streaming, alleviating this issue slightly).

Since those files are always required for any release build (having to rely on an external CDN could be another issue, especially now that per-domain caching removes any direct benefits from using a CDN), it means displaying a Flutter web app is relatively slow.

By preloading ressources (see https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload) we can avoid this and start getting data as soon as possible, making better use of the client available total bandwidth.

Before this change:
image

Big waterfall, with a long time between main.dart.js and canvaskit.js (parsing + compile?), and everything done sequentially: `main.dart.js` then `canvaskit.js` then `canvaskit.wasm`.

After this change:
image

Screenshots are taken from the default application one gets from running `createapp`, but I've also tested the changes in a production application too.
**For the simple default app, all content was loaded in 330ms, rather than 450ms on my fiber connection ("Finish" on screenshots), a roughly 25% improvement.**

Related to #76009, but not a fix, more work is needed.

Especially, in a perfect world:

* this preloading wouldn't happen in debug mode. As of now, I don't see any way to control the html depending on the current mode.
* fonts would also be loaded ahead-of-time
* the URL for canvaskit would be configurable. I think it has been mentioned in #70101 but I wasn't able to get that working (I'm not a Flutter expert :cry:). If configured, the HTML definitely shouldn't preload unpkg, but instead the local file directly.
* the URL for unpkg would be shared with whatever gets used to generate main.dart.js. Right now, I hardcoded v30.0, as I wasn't sure where this came from. It would probably be better to use a new variable, e.g. `$FLUTTER_CANVASKIT_URL` as is done for `$FLUTTER_BASE_HREF`.

It those issues are blockers, then feel free to close as the implementation right now might be considered a bit shaky and could make the dev experience slightly slower on first load. However, I think the overall concept of using preload is worth investigating.

This PR has no tests, as it only includes changes to the default HTML template used for web projects.
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by cedvdb** [comment]
This is great. Shouldn't the wasm version not be hardcoded though ?

**Comment by Neamar** [comment]
It definitely shouldn't. However, it's hardcoded in flutter/engine.

They have a checklist when updating the version: https://github.com/flutter/engine/blob/master/lib/web_ui/README.md#rolling-canvaskit so if this gets traction, we can update the checklist to include a new item asking to update this template.

As mentioned in the description, ideally this should be a variable injected by dart at build time, similar to `$FLUTTER_BASE_HREF`, but I don't have enough familiarity with the engine and build system to get that working :(

**Comment by TimWhiting** [comment]
I agree that this would be great, however, won't this download canvaskit even for mobile which uses the html renderer by default? I'm guessing that these whole script tags would need to be injected after mobile / desktop detection is done. The detection would have to probably be done in the index.html like the current service worker installation in order to avoid the main.dart.js delay problem.

**Comment by Neamar** [comment]
That's a good comment, and I believe we could get the best of both world.

Assuming the mobile detection is "cheap" and can be done in a couple of lines, we can replace the current PR with a <script> *before* the `main.dart.js` inclusion, and have something like this:

```js
var isMobile = /* code to detect mobile */;
if(isMobile) {
  var preloadLink = document.createElement("link");
  preloadLink.href = "https://unpkg.com/canvaskit-wasm@0.30.0/bin/canvaskit.js";
  preloadLink.rel = "preload";
  preloadLink.as = "script";
  document.head.appendChild(preloadLink);
}
```

The same logic could be used to detect "release" vs. "dev" and only trigger the preload when relevant. It does make the HTML template bigger, sadly, but would still bring a nice performance boost.

**Comment by LasseRosenow** [comment]
The issue here is, that it depends on how you build the app, if canvaskit or html us used.

For example I have set it to always be canvas kit, because I rather have a fast page that takes a bit longer to load the first time, then a slow page, that loads fast.

The command is --web-renderer see: https://docs.flutter.dev/development/tools/web-renderers


So maybe those preload lines need to be somewhat injected into the html while coming, but not in the template, that is visible to the developer

**Comment by christopherfujino** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
Yeah, we can't hard-code the version of CanvasKit like that. The intention of the PR makes sense though. I'm not sure how well that plays with service workers and with the upcoming `flutter.js` (cc @ditman). It seems to me that this approach would be useful for a fully online mode where you want to launch a Flutter app asap. We're currently working on the case where the landing page is not Flutter, and you are bootstrapping a Flutter app from within that other page (which could be plain HTML, vanillaJS, React, etc). So the tooling code and this template is going to change soon.

One thing to note is that this change makes the DOMContentLoaded slightly worse, which may push [first contenful paint](https://developer.mozilla.org/en-US/docs/Glossary/First_contentful_paint). This would delay the visuals of a loading indicator or a splash screen by prioritizing HTTP requests for CanvasKit. It might be better to delay CanvasKit a bit but give the user initial feedback earlier. So I'm not sure if this is a clear win.

What this change does highlight is the problem with us loading CanvasKit from within the engine's Dart code. If `main.dart.js` is big, it take the JavaScript VM a while to digest the JS bundle before it fires the CanvasKit HTTP requests. I think we can improve this considerably by having `flutter.js` fetch CanvasKit instead of `main.dart.js`. It would be able to do it much earlier, especially if can be inlined into the `index.html` itself, avoiding the extra fetch.

@ditman WDYT? Can we move the CanvasKit loading logic into `flutter.js`?

**Comment by cedvdb** [comment]
Http 2 push needs to be taken into account when taking a decision. If the resources are hard coded in the js or even the html it might make it harder to implement.

>  we could use flutter.js to have the logic to add the required prefetching.

Adding the fetching to flutter js will also delay the prefetching. The advantage of html is that it does not need to fetch the js in order to start fetching the other resources.

> One thing to note is that this change makes the DOMContentLoaded slightly worse

The fetching happens in the background and you also can delay execution. What exactly do you have in mind as the root cause of that negative impact ?

**Comment by Neamar** [comment]
> testing this earlier on, and then seeing some double-downloads

This was probably caused by setting up the wrong mimetype / crossorigin. Getting those to work correctly is super fiddly :\

Getting the markup added by JS, with additional context on what will be required (canvas or html, debug or release, and library version) would be ideal -- very slightly less performant since JS needs to run first, but insignificant compared to the cost of waiting for a multi-mb js file to be downloaded and parsed :)

> I think we can improve this considerably by having flutter.js fetch CanvasKit instead of main.dart.js. It would be able to do it much earlier, especially if can be inlined into the index.html itself, avoiding the extra fetch.

Yup, that would solve all issues and remove the need for any preloading :+1: 

> One thing to note is that this change makes the DOMContentLoaded slightly worse

7ms would be negligible, but more importantly, it's likely just noise on my (personal) network when running the test. Preload shouldn't have an impact on that metric, I guess taking the measurement ten times would average this out to statistically non-significant.

**Comment by christopherfujino** [comment]
I'm closing this PR as something we won't merge. Feel free to have additional discussion on https://github.com/flutter/flutter/issues/76009

**Pull request closed without merging**
