### PR TITLE
[web] Make `FLUTTER_WEB_AUTO_DETECT` false by default

### PR DESCRIPTION
**Pull request by mdebbar**
Now that "auto" is not supported anymore, it makes more sense to make this dart define false by default. And there's no need to pass `FLUTTER_WEB_AUTO_DETECT=false` anymore.

### CODE REVIEW

**Review by yjbanov — APPROVED** [review]
lgtm

**Comment by jtmcdole** [comment]
Lets make sure to hold off on this till the dart format lands.

**Comment by matanlurey** [comment]
Wowie!

**Comment by jtmcdole** [comment]
I believe this is the first crosscutting change that can be done in a single PR. Excellent!

**Pull request merged**
