### PR TITLE
Port to crypto 0.9.2

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
@abarth

**Comment by Hixie** [comment]
see https://pub.dartlang.org/packages/crypto

**Comment by abarth** [comment]
LGTM

"semantic" versioning

**Comment by Hixie** [comment]
looks like i missed some. trying again.

**Comment by Hixie** [comment]
@abarth updated to fix flutter_tools also. I inlined the deprecated hex-conversion function since it was deprecated in favour of package:convert and I didn't want to add a new dependency for something so trivial.

**Comment by abarth** [comment]
LGTM.  I probably would have kept the name bytesToHex, but hex is fine too.

**Comment by Hixie** [comment]
hex is what it's called in package:convert apparently.

**Comment by abarth** [comment]
sgtm

**Pull request merged**
