### PR TITLE
Docs improvements for minLines/maxLines

### PR DESCRIPTION
**Pull request by justinmc**
There was confusion over whether minLines and maxLines affect the number of lines of text that can be entered vs. the number of lines visible.  This updates the docs to clarify this.

Docs change only, no tests.

Potential fix for https://github.com/flutter/flutter/issues/80133

### CODE REVIEW

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
Pinging @Hixie for test exemption. :)

**Comment by Hixie** [comment]
test-exempt: only affects comments

btw you typically need a newline before a bullet in our markdown variant, so after landing this please check the output and see if it's what you expect

**Comment by justinmc** [comment]
Thanks all!

I'll write myself a note to check the output.  Hopefully it's ok in the way that it combines with the macro...

**Comment by justinmc** [comment]
✅  All docs output looks correct (e.g. https://master-api.flutter.dev/flutter/material/TextField/minLines.html).

**Pull request merged**
