### PR TITLE
Add viewSearchOnChanged to SearchAnchor

### PR DESCRIPTION
**Pull request by burakJs**
I started investigating the #132915 issue. The first thing I noticed was that onChanged was not working when the searchbar view was open, but it was working when it was closed. When I examined the code, I saw that the onChanged argument was not in the arguments given to the opened search view. I added the `viewSearchOnChanged` argument, which will work when the view is open. This solved the #132915 issue and the onChange state was triggered when the search view was open.

- #132915

<details>
<summary> Code Example (The code is the new and working version of the #132915)</summary>

```dart
import 'package:flutter/material.dart';

class SearchBarIssueView extends StatefulWidget {
  const SearchBarIssueView({super.key});

  @override
  State<SearchBarIssueView> createState() => _SearchBarIssueViewState();
}

class _SearchBarIssueViewState extends State<SearchBarIssueView> {
  bool isDark = false;

  @override
  Widget build(BuildContext context) {
    final ThemeData themeData = ThemeData(useMaterial3: true, brightness: isDark ? Brightness.dark : Brightness.light);

    return MaterialApp(
      theme: themeData,
      home: Scaffold(
        appBar: AppBar(title: const Text('Search Bar Sample')),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: SearchAnchor(
            viewSearchOnChanged: (value) {
              print('OnChanged While Open: $value');
            },
            builder: (BuildContext context, SearchController controller) {
              return SearchBar(
                controller: controller,
                padding: const MaterialStatePropertyAll<EdgeInsets>(EdgeInsets.symmetric(horizontal: 16.0)),
                onTap: () {
                  controller.openView();
                },
                onChanged: (value) {
                  print('OnChanged While Close: $value');
                },
                leading: const Icon(Icons.search),
                trailing: <Widget>[
                  Tooltip(
                    message: 'Change brightness mode',
                    child: IconButton(
                      isSelected: isDark,
                      onPressed: () {
                        setState(() {
                          isDark = !isDark;
                        });
                      },
                      icon: const Icon(Icons.wb_sunny_outlined),
                      selectedIcon: const Icon(Icons.brightness_2_outlined),
                    ),
                  )
                ],
              );
            },
            suggestionsBuilder: (BuildContext context, SearchController controller) {
              return List<ListTile>.generate(5, (int index) {
                final String item = 'item $index';
                return ListTile(
                  title: Text(item),
                  onTap: () {
                    setState(() {
                      controller.closeView(item);
                    });
                  },
                );
              });
            },
          ),
        ),
      ),
    );
  }
}
```
</details>
<details>
<summary> Logs </summary>

```
flutter: OnChanged While Open: f
flutter: OnChanged While Open: fl
flutter: OnChanged While Open: flu
flutter: OnChanged While Open: flut
flutter: OnChanged While Open: flutt
flutter: OnChanged While Open: flutte
flutter: OnChanged While Open: flutter
flutter: OnChanged While Close: flutterr
```
</details>

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by TahaTesser** [comment]
Could we somehow make the existing `onChange` also receive `onChange` events from the search view?  I'm not sure about having two onChange callbacks for the user to listen. 

Also this need tests.

**Comment by burakJs** [comment]
> Could we somehow make the existing `onChange` also receive `onChange` events from the search view? I'm not sure about having two onChange callbacks for the user to listen.
> 
> Also this need tests.

- If we think that it will only be received by SearchAnchor, we can give the parameter to the builder and have the man give the new extra onChange parameter. If it is in the SearchBar, we cannot send this parameter to the opened search view, since SearchAnchor cannot access it directly.
- After finalizing the solution process, I can add the solution to the existing sample test widgets

**Comment by TahaTesser** [comment]
That's an interesting problem. 

@HansMuller Any thoughts?

**Comment by HansMuller** [comment]
I agree that the onChanged callback is associated with the search bar's text field, which (from the user's point of view) is visible whether the search view is open or not. Hopefully this could be made to work by just passing the callback along, i.e. without any inherited widget intermediary.

Unrelated: it's a bit of a shame that the onTap and onChanged callbacks are needed by default. I would have thought that overriding them would only be needed if the app didn't just want to have them call controller.openView().

@QuncCccccc - would like to hear your opinion about this.

**Comment by burakJs** [comment]
Maybe we can pass onChanged method as 3rd parameter in builder. By default, the developer can pass it into the onChange inside the SearchBar. Thus, it will not be rewritten, but there will be 2 onChanges again.

```dart
SearchAnchor(
            viewSearchOnChanged: (value) {
              print('OnChanged While Open: $value');
            },
            builder: (BuildContext context, SearchController controller, ValueSetter<String> viewSearchOnChanged) {
            return SearchBar(
                controller: controller,
                padding: const MaterialStatePropertyAll<EdgeInsets>(EdgeInsets.symmetric(horizontal: 16.0)),
                onTap: () {
                  controller.openView();
                },
                onChanged: viewSearchOnChanged,
            ...
```

**Comment by LincolnFerreira** [comment]
I don't know if I can contribute anything, but I would like to leave here the way I tried to somehow deal with all the "problems" with the widget...
If there really is something strange in my code, I apologize and open it for new implementations... Thank you very much!

`class SearchComponent extends StatefulWidget {
  final SearchController searchController;
  final Titles resultData;
  final Function(String text) fetchDataFromBackend;

  const SearchComponent({
    Key? key,
    required this.searchController,
    required this.resultData,
    required this.fetchDataFromBackend,
  }) : super(key: key);

  @override
  State<SearchComponent> createState() => _SearchComponentState();
}

class _SearchComponentState extends State<SearchComponent> {
  @override
  Widget build(BuildContext context) {
    return SearchAnchor(
      isFullScreen: true,
      searchController: widget.searchController,
      builder: (context, controller) {
        return SearchBar(
          controller: controller,
          onTap: () =>
              controller.text.isNotEmpty ? controller.openView() : null,
          onChanged: (_) =>
              controller.text.isNotEmpty ? controller.openView() : null,
        );
      },
      suggestionsBuilder: (context, controller) async {
        List<String> titles =
            await widget.fetchDataFromBackend(controller.value.text);
        widget.resultData.update(titles);

        return List.generate(
          widget.resultData.items.length,
          (index) => ListTile(
            title: Text(
              widget.resultData.items[index],
            ),
          ),
        );
      },
    );
  }
}
`

**Comment by TahaTesser** [comment]
@burakJs 
Are you still working on this? Do you have any response for https://github.com/flutter/flutter/pull/132924#issuecomment-1688695104

**Comment by TahaTesser** [comment]
@QuncCccccc Do you any comment regarding https://github.com/flutter/flutter/pull/132924#issuecomment-1688695104?

**Comment by QuncCccccc** [comment]
> @QuncCccccc Do you any comment regarding [#132924 (comment)](https://github.com/flutter/flutter/pull/132924#issuecomment-1688695104)?

I think a fix(#136840) was already merged last year:) Sorry I didn't notice this PR before. I added a `viewOnChanged` for `SearchAnchor` because the search view can also be opened by clicking any widget which isn't a search bar.

**Comment by TahaTesser** [comment]
@QuncCccccc 
Do we close this PR then?

**Comment by QuncCccccc** [comment]
Thanks so much for the contribution! I'll close this issue because the fix is already in #136840 :)

**Comment by aloh86** [comment]
@QuncCccccc I'm on stable channel 3.16.9. How can I get the new change for SearchAnchor that has `viewOnChanged`?

**Pull request closed without merging**
