### PR TITLE
Add buttons customization to WidgetController and related testing classes

### PR DESCRIPTION
**Pull request by dkwingsmt**
## Description

Add `buttons` customization to the following classes:
  - `TestPointer`'s constructor and property
  - `TestGesture`'s constructor
  - `WidgetController`'s movement methods

It is needed because widgets might want to test their behavior under events with non-primary buttons.

## Related Issues

N/A

## Tests
- New tests: Each of the following methods should respect buttons, i.e. the events yielded from it should have the correct buttons.
  - `WidgetTester.tap`
  - `WidgetTester.press`
  - `WidgetTester.longPress`
  - `WidgetTester.drag`
  - `WidgetTester.fling`

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by dkwingsmt** [comment]
@Hixie Can you help me with https://github.com/flutter/flutter/pull/31095/files#diff-471125bcbe296090fcc1b8b2fa29307aR387 ? Tests go time out because of these lines, and removing them doesn't seem to break any tests. I wonder if it's because of "If the device's screen is currently turned off, this may wait a very long time", but I don't know how to solve it.

**Comment by Hixie** [comment]
@dkwingsmt Happy to help, can you ping me (or drop by my desk) on Thursday?

**Comment by dkwingsmt** [comment]
@Hixie I will, thanks

**Comment by dnfield** [comment]
@dkwingsmt - do we need to keep this open for now, or can we close it to remove it from our review queues?

**Comment by dkwingsmt** [comment]
@dnfield Thanks for reminding. This PR is still relavent, I'll update it asap

**Comment by dkwingsmt** [comment]
It relies on https://github.com/flutter/flutter/pull/31333. Will update after it is merged.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Pull request merged**
