### PR TITLE
Added test for box decoration hit

### PR DESCRIPTION
**Pull request by charafau**
ref: https://github.com/flutter/flutter/issues/7293

I tried to add more tests for BoxDecoration hit - both for square and circle.
I can add more tests if needed.

### CODE REVIEW

**Comment by Hixie** [comment]
This looks great! Thanks!

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
I shall check this in for you! Thanks again!

**Comment by Hixie** [comment]
fyi @HansMuller

**Comment by charafau** [comment]
It was my pleasure :)

**Pull request merged**
