### PR TITLE
text selection affinity can be null on web

### LINKED ISSUE #62724: Text Input on Web does not work with Null Safety
## Steps to Reproduce

0. `flutter run --enable-experiment=non-nullable --no-sound-null-safety -d chrome`.
1. Create a `TextField`.
2. Focus on the `TextField`.
3. Keyboard input is ignored.

This is the case for ***all* text fields** since I upgraded to the latest `master` version.

```
Flutter 1.21.0-6.0.pre.141 • channel master • https://github.com/flutter/flutter.git
Framework • revision c748f1a7aa (10 hours ago) • 2020-07-31 17:45:18 -0700
Engine • revision 280bbfc763
Tools • Dart 2.10.0 (build 2.10.0-2.0.dev bd528bfbd6)
```

It worked fine for `Flutter 1.21.0-6.0.pre.138`. That is *all* text fields worked fine.

### PR DESCRIPTION
**Pull request by a14n**
## Description

In the [nullsafety migration of services](https://github.com/flutter/flutter/pull/62513) we changed the behaviour asserting text affinity was always non null. It doesn't look right on web and is the cause of  #62724.

This PR fixes the issue by accepting null value again.

## Related Issues

* Fixes #62724

## Tests

None

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by a14n** [comment]
NB: I tried to add a test that creates a TextEditingValue from json with null `selectionAffinity` but the test never failed. It's like nullsafety was not checked during test.

**Review by creativecreatorormaybenot — COMMENTED** [review]
🚀

weird indeed

**Review by mdebbar — APPROVED** [review]
@a14n thanks for quickly fixing this! FYI @nturgut.

The test doesn't fail because it's not migrated yet to null safety. See [this line](https://github.com/flutter/flutter/blob/d261f1ef584dc9b233e4e46102e2f83dbe21ad78/packages/flutter/test/services/text_input_test.dart#L5) in the test file.

**Comment by a14n** [comment]
>The test doesn't fail because it's not migrated yet to null safety. See this line in the test file.

I thought null checks would be honored in migrated files. Here `null as String` should have failed in a migrated file. And actually that is what happened in #62724. Debugging in browser I faced :

```
Error: Assertion failed: file:///home/a14n/flutter/packages/flutter/lib/src/services/text_input.dart:597:38
affinity != null
"A null value was passed into a non-nullable parameter: affinity."
    at Object.throw_ [as throw] (http://localhost:46741/dart_sdk.js:4323:11)
    at Object.nullFailed (http://localhost:46741/dart_sdk.js:4277:17)
    at Object._toTextAffinity (http://localhost:46741/packages/flutter/src/services/text_input.dart.lib.js:1335:32)
    at Function.fromJSON (http://localhost:46741/packages/flutter/src/services/text_input.dart.lib.js:893:350)
    at text_input.TextInput.__._handleTextInputInvocation (http://localhost:46741/packages/flutter/src/services/text_input.dart.lib.js:1211:111)
    at _handleTextInputInvocation.next (<anonymous>)
    at runBody (http://localhost:46741/dart_sdk.js:37598:34)
    at Object._async [as async] (http://localhost:46741/dart_sdk.js:37629:7)
    at text_input.TextInput.__.[_handleTextInputInvocation] (http://localhost:46741/packages/flutter/src/services/text_input.dart.lib.js:1180:20)
    at OptionalMethodChannel._handleAsMethodCall (http://localhost:46741/packages/flutter/src/services/system_channels.dart.lib.js:990:57)
    at _handleAsMethodCall.next (<anonymous>)
    at runBody (http://localhost:46741/dart_sdk.js:37598:34)
    at Object._async [as async] (http://localhost:46741/dart_sdk.js:37629:7)
    at OptionalMethodChannel.[_handleAsMethodCall] (http://localhost:46741/packages/flutter/src/services/system_channels.dart.lib.js:987:20)
    at http://localhost:46741/packages/flutter/src/services/system_channels.dart.lib.js:970:126
    at handlePlatformMessage (http://localhost:46741/packages/flutter/src/services/system_channels.dart.lib.js:2188:31)
    at handlePlatformMessage.next (<anonymous>)
    at runBody (http://localhost:46741/dart_sdk.js:37598:34)
    at Object._async [as async] (http://localhost:46741/dart_sdk.js:37629:7)
    at _DefaultBinaryMessenger.handlePlatformMessage (http://localhost:46741/packages/flutter/src/services/system_channels.dart.lib.js:2183:20)
    at Object._invoke3 (http://localhost:46741/dart_sdk.js:174927:7)
    at _engine.EngineWindow.new.invokeOnPlatformMessage (http://localhost:46741/dart_sdk.js:170975:15)
    at _engine.TextEditingChannel.new.updateEditingState (http://localhost:46741/dart_sdk.js:168746:24)
    at http://localhost:46741/dart_sdk.js:168869:24
    at _engine.GloballyPositionedTextEditingStrategy.new.[_handleChange] (http://localhost:46741/dart_sdk.js:148666:40)
    at Object._checkAndCall (http://localhost:46741/dart_sdk.js:4533:16)
    at Object.dcall (http://localhost:46741/dart_sdk.js:4538:17)
    at HTMLInputElement.<anonymous> (http://localhost:46741/dart_sdk.js:105036:21)
```

and this check was the cause of the failure.

So it looks like DDC makes null checks.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by a14n** [comment]
> Google testing — Google testing failed. Please contact a Google developer to investigate.

@goderbauer could you check if I can ignore this failing job?

**Comment by goderbauer** [comment]
> @goderbauer could you check if I can ignore this failing job?

Checking... I'll get back to you.

**Comment by goderbauer** [comment]
You can ignore the "google testing" check on this one.

**Pull request merged**
