### PR TITLE
Annotate RawMaterialButton as a Material > Button category.

### PR DESCRIPTION
**Pull request by jverkoey**
This will enable aggregation of similar Material > Button symbols.

### CODE REVIEW

**Review by Hixie — APPROVED** [review]
test exempt: metadata annotation experiment. If this is successful, we can add tests in a subsequent commit when we add other annotations.

**Comment by jverkoey** [comment]
web_tests-1-linux failure appears to be a flake.

**Comment by rami-a** [comment]
Re-ran the web_tests-1-linux check

**Comment by jverkoey** [comment]
flutter-build appears to be broken.

**Review by rami-a — APPROVED** [review]

**Pull request merged**
