### PR TITLE
Remove EnterExitTransition

### PR DESCRIPTION
**Pull request by abarth**
This widget doesn't work very well. Once we have a good use case, we
should try building it again.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

**Comment by Hixie** [comment]
LGTM. Have you checked with our customers to make sure they're not using it?
cc @apwilson

**Comment by abarth** [comment]
It looks like @apwilson has one in his codebase, but I'm not sure if that's a part of his codebase that he's still using.

**Comment by jimbeveridge** [comment]
Yes, we're still using it. I spent two days last week to get that working again with the new Animation classes :-)

It's working now, but I'm happy to talk to you next week about alternatives.

@apwilson

**Comment by abarth** [comment]
Ok, I'll close this pull request.  We should talk about if there's something better we can do for you to replace this.

**Pull request closed without merging**
