### PR TITLE
Mega gallery

### PR DESCRIPTION
**Pull request by devoncarew**
Work on creating a large benchmark app. This will be used to measure analysis times, and eventually edit/refresh times.
- move some loose scripts from dev/ to dev/tools/
- create a new script, dev/tools/mega_gallery.dart
- it copies `examples/material_gallery` to `dev/benchmarks/mega_gallery`
- `dev/benchmarks/mega_gallery` is .gitignored (but we could also choose to generate it outside the repo directory entirely)
- it duplicates the `lib/` contents enough times to create an app that weighs in at about 60k lines
- create a new main.dart entry-point which references all the samples (so they're analyzed correctly)

Future work will stitch together a UI which uses all n copies, so the code is actually all used at runtime.

Output from running `dev/tools/mega_gallery.dart`:

```
Stats:
  packages/flutter           : 364 files, 58,049 lines
  examples/material_gallery  : 50 files, 5,868 lines

Making 11 copies of material_gallery:
  dev/benchmarks/mega_gallery: 510 files, 63,098 lines
```

and some analysis times (`flutter analyze --watch --benchmark`):

material_gallery: ~12.5 seconds
mega_gallery: ~20.0 seconds

### CODE REVIEW

**Comment by pq** [comment]
Nice!  LGTM.

**Comment by yjbanov** [comment]
My worry is that this is not tested and so it will be breaking on the dashboard box.

**Comment by devoncarew** [comment]
I can add a test that this generates and analyses correctly. We may also want a smoke-test for the dashboard project itself :)

**Comment by yjbanov** [comment]
> We may also want a smoke-test for the dashboard project itself

This would certainly be nice. The issue is that our buildbot doesn't have any Android devices to test against and iOS is not ready for the dashboard yet.

**Comment by devoncarew** [comment]
> The issue is that our buildbot doesn't have any Android devices

Ah, makes sense. You could do something like set a `NO_ANDROID` env variable on the bot and skip the parts that needed a device. The dashboard produced wouldn't be useful, but at least parts of the script would be tested.

**Comment by yjbanov** [comment]
> skip the parts that needed a device

Hmm, in that case we don't need to use the buildbot at all. Plain old Travis should do just fine.

**Comment by yjbanov** [comment]
Oh, and LGTM, especially if you can also add a test that the mega gallery generator works and analysis passes.

**Comment by devoncarew** [comment]
Added code to generate and test the benchmark in `travis/test.sh`.

**Pull request merged**
