### PR TITLE
Revert "Reland "Scribble mixin""

### PR DESCRIPTION
**Pull request by XilaiZhang**
Info: https://b.corp.google.com/issues/258924157

Reverts flutter/flutter#114698

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
@XilaiZhang please include more context with reverts. Is there a FRoB bug filed for these failures that can be linked here?

**Comment by XilaiZhang** [comment]
> @XilaiZhang please include more context with reverts. Is there a FRoB bug filed for these failures that can be linked here?

Yeah sorry I filed these PRs hastily at night. I have put updating descriptions on my to do list and will come back to update the descriptions

**Comment by XilaiZhang** [comment]
Confirmed that this is the cause. Thanks for the early approval!

**Comment by XilaiZhang** [comment]
update: linked a bug with test failures in description.

**Pull request merged**
