### PR TITLE
Roll the engine to 8fea842f027cdc98e2d338f1a04b2c0cb319e204

### PR DESCRIPTION
**Pull request by cbracken**

### CODE REVIEW

**Comment by tvolkert** [comment]
LGTM

**Comment by tvolkert** [comment]
Hmm- https://build.chromium.org/p/client.flutter/waterfall shows broken builds, so can't roll this rev.

**Comment by cbracken** [comment]
Updated to 8fea842f027cdc98e2d338f1a04b2c0cb319e204. Will re-kick-off Travis once it's finished the Linux build on the bots.

**Comment by tvolkert** [comment]
LGTM!

**Pull request merged**
