### PR TITLE
move compile/target sdk versions to 29

### LINKED ISSUE #54382: Update Android SDK from 28 to 29 in new plugins and project templates
Currently `compileSdkVersion` and `targetSdkVersion` are 28. 
Plugins and a new project should use 29.

### PR DESCRIPTION
**Pull request by xster**
Fixes https://github.com/flutter/flutter/issues/54382

(we already moved our engine builds to 29 last year)

### CODE REVIEW

**Review by jmagman — COMMENTED** [review]
@xster This doesn't cause any new warnings in new projects, right?

**Comment by xster** [comment]
oh wow, actually just checked. Android fancy now https://github.com/flutter/flutter/issues/54382#issuecomment-668208415

**Review by jmagman — APPROVED** [review]
LGTM assuming this doesn't cause any new warnings in new projects.
Similar to #26444 and #26790 and #26798

**Comment by xster** [comment]
Ya, that's what I meant to say. It does not. It's a smooth transition as far as I can tell.

**Pull request merged**
