### PR TITLE
Enable avoid_redundant_argument_values lint (#91409)

### PR DESCRIPTION
**Pull request by Hixie**
This is a reland of https://github.com/flutter/flutter/pull/91409 which got reverted in https://github.com/flutter/flutter/pull/91461 because in the 3 hours between the PR being pushed to GitHub and cleared by the bots, and the PR actually landing, https://github.com/flutter/flutter/commit/f753168cb65a391bd352ebd14ad942fda0a63b1a#diff-16ed0ebb4b07365e2bd92f3ba86d3d90385ed7f865dd18b98462e410dee538e3 landed which added another redundant argument.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @christopherfujino the only change between the last version and this one is the second commit, which is a change to code you wrote earlier today.

**Comment by Hixie** [comment]
Google testing is still expected to fail because #91309 hasn't yet rolled into google3.

**Comment by Hixie** [comment]
Please add the "waiting for green" label if you review this PR. Thanks!

**Review by christopherfujino — APPROVED** [review]
LGTM, sorry for breaking you

**Pull request merged**
