### PR TITLE
Roll pub packages

### PR DESCRIPTION
**Pull request by fluttergithubbot**
This PR was generated by `flutter update-packages --force-upgrade`.

### CODE REVIEW

**Comment by goderbauer** [comment]
FYI @natebosch Here's the new PR opened by the bot.

**Comment by natebosch** [comment]
The failures in customer_tests are expected - they are the the `flutter_reactive_ble` package with a dependency that blocks the latest analyzer. Details in https://github.com/flutter/flutter/pull/123350#issuecomment-1490614783

I'm not sure what is happening in the `framework_tests` failure. It may be a flake? It looks like the same test case passes  on flutter test infrastructure, but fails on cirrus.

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20framework_tests_misc/34905/overview
https://cirrus-ci.com/task/5181030374572032


In any case, nothing looks actionable by me. I'm currently waiting the required 72 hours since the email I sent yesterday to the `flutter_reactive_ble` owners. @goderbauer - will you be able to land this on Monday?

**Comment by christopherfujino** [comment]
> I don't see a change in `flutter/tests` and the `flutter_reactive_ble` tests are still running, but Elias triggered an update here (#124015) as part of bringing in a new package, and the customer tests are passing there. Does anyone know what changed over the weekend? In any case, I'll hit the "Update branch" button on this PR to bring it up to head and re-trigger the presubs.

No idea how this got fixed, but we're all green so I guess I won't complain?

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
> No idea how this got fixed, but we're all green so I guess I won't complain?

Looks like a new version of `dart_functional_data` was released over the weekend and picked up by `flutter_reactive_ble`. The new version ([1.1.5](https://pub.dev/packages/functional_data_generator/changelog)) is loosening the version requirements on the analyzer making it compatible with the analyzer version that `test_api` wants: https://github.com/spkersten/dart_functional_data/commit/1d0b10a39bc6bc5ae5f94107c9154f12905774f5

@natebosch Thanks for reaching out to the package maintainers to get this resolved! 🥳

**Comment by christopherfujino** [comment]
Thanks @goderbauer and @natebosch for taking care of this while I was out!

**Comment by natebosch** [comment]
> Does anyone know what changed over the weekend?

https://pub.dev/packages/functional_data_generator/versions/1.1.5

The `functional_data_generator` package published a new version with an expanded analyzer compatibility. It looks like they did this from a local copy and have not updated github yet.

**Pull request merged**
