### PR TITLE
Tiny one space formatting fix

### PR DESCRIPTION
**Pull request by fzyzcjy**
You know, I like to see beautiful code, so really hope we have auto formatter, such that all these (at least such formatting error) can be done automatically!

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by tgucio** [comment]
I've updated the PR title for a clear&concise commit message.

There is no auto formatting in the framework code, instead the [analyser](https://github.com/flutter/flutter/blob/master/dev/bots/analyze.dart) runs a series of checks. I guess one could look at adding one for unnecessary spaces like this with care to avoid false positives (e.g. text in quotes etc.).

**Review by tgucio — APPROVED** [review]
LGTM

**Comment by fzyzcjy** [comment]
@tgucio Thank you! However, I hope to remain at least one "tiny", because then readers will quickly realize this is super small and will not catch their eyes (e.g. when looking at code history).

**Review by HansMuller — APPROVED** [review]
LGTM

**Pull request merged**
