### PR TITLE
Revert "Roll Engine from 7571e7c380fd to b300be3df32b (60 revisions)"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#63892

android_view_scroll_perf_timeline_summary is failing:

```
2020-08-16T03:19:12.369706: stdout: [ +184 ms] E/flutter (32299): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
2020-08-16T03:19:12.370092: stdout: [        ] E/flutter (32299): 	at io.flutter.plugin.platform.PlatformViewsController.finishFrame(PlatformViewsController.java:810)
2020-08-16T03:19:12.371146: stdout: [        ] E/flutter (32299): 	at io.flutter.plugin.platform.PlatformViewsController.onEndFrame(PlatformViewsController.java:771)
stdout: [        ] E/flutter (32299): 	at io.flutter.embedding.engine.FlutterJNI.onEndFrame(FlutterJNI.java:856)
2020-08-16T03:19:12.371823: stdout: [        ] E/flutter (32299): 	at android.os.MessageQueue.nativePollOnce(Native Method)
2020-08-16T03:19:12.372393: stdout: [        ] E/flutter (32299): 	at android.os.MessageQueue.next(MessageQueue.java:323)
2020-08-16T03:19:12.372773: stdout: [        ] E/flutter (32299): 	at android.os.Looper.loop(Looper.java:136)
2020-08-16T03:19:12.373525: stdout: [        ] E/flutter (32299): 	at android.app.ActivityThread.main(ActivityThread.java:6123)
2020-08-16T03:19:12.374160: stdout: [        ] E/flutter (32299): 	at java.lang.reflect.Method.invoke(Native Method)
2020-08-16T03:19:12.374659: stdout: [        ] E/flutter (32299): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
2020-08-16T03:19:12.375206: stdout: [        ] E/flutter (32299): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

### CODE REVIEW

**Comment by jonahwilliams** [comment]
@gaaclarke

**Comment by gaaclarke** [comment]
@jonahwilliams can you link directly to the errors please.  I'm poking around in the dashboard and haven't seen this failure yet.

**Comment by jonahwilliams** [comment]
I can't, its just a log download link - I include the relevant part of the error and the failing test name

**Comment by jonahwilliams** [comment]
Revert analysis errors on ToT: https://github.com/flutter/flutter/pull/63972

Should be safe to land now

**Pull request merged**
