### PR TITLE
Always include PATH environment variable in Posix OS cmds

### PR DESCRIPTION
**Pull request by tvolkert**

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Presumably this covers https://github.com/flutter/flutter/pull/25240 ?

**Comment by tvolkert** [comment]
Yeah.  If you're able to confirm locally, I'll wait for that confirmation to merge.

**Comment by jonahwilliams** [comment]
Does not seem to fix it

**Comment by jonahwilliams** [comment]
@tvolkert I'm going to close this PR for now

**Pull request closed without merging**
