### PR TITLE
[tool][web] Makes flutter.js more G3 friendly.

### LINKED ISSUE #116153: [web] Do not nag users about not configured ServiceWorker.
Currently flutter.js nags users in the console if the [_Service worker not supported (or configured)_](https://github.com/flutter/flutter/blob/4c3b642f27f5b840a94cfba3c8769edab53ac77e/packages/flutter_tools/lib/src/web/file_generators/flutter_js.dart#L115-L120).

We have received several issues, and internal feedback about this:

* https://github.com/flutter/flutter/issues/113145
* https://github.com/flutter/flutter/issues/109771
 
**We should NOT warn users in case that `serviceWorker == null` (the _"(or configured)"_ part), just noop silently.** A blank `serviceWorker` config is a sign that the user does NOT want to use our serviceWorker, not **an issue**.

We also should check: [`isSecureContext`](https://developer.mozilla.org/en-US/docs/Web/API/isSecureContext) to tell users why the ServiceWorker may not be available, and point them to some documentation.

/cc @jacobsimionato

### LINKED ISSUE #120483: [web] Trusted Types validation is too strict in flutter loader.
## Use case

Flutter.js currently accepts only *.dart.js and flutter_service_worker.js in its trusted types policy - see:

https://github.com/flutter/flutter/blob/65fd924d848f611c36de6a1e1bf1059c334ac86f/packages/flutter_tools/lib/src/web/file_generators/flutter_js.dart#L85-L88

Internally, we want to be able to pass names that don't follow the conventions specified above, so we probably should relax the default (at least until it's more easily overridable).

## Proposal

Relax the default so it accepts any `.js` script.

_As reported in b/268285339 by @jacobsimionato_

### PR DESCRIPTION
**Pull request by ditman**
## Description

This PR makes the flutter.js loading process slightly more friendly with google's internal configuration by:

* Relaxing the trusted types validation of the flutter loader, so files with different naming conventions can be used (both for the main.dart.js and flutter_service_worker.js files)
* Nagging users *less* about the serviceWorker configuration being null.
  * Only prints a warning if serviceWorker is not available, and points users to Secure Context documentation if needed.
  * (Null configuration is still output as a low level debug.info message, which is often filtered out by browsers)

_(FYI: @jacobsimionato)_

## Related issues

Fixes https://github.com/flutter/flutter/issues/120483
Fixes https://github.com/flutter/flutter/issues/116153

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by mdebbar — APPROVED** [review]
LGTM!

**Comment by ditman** [comment]
> LGTM!

Thanks for the super fast review @mdebbar, I'll `autosubmit` this on monday though :P

**Comment by ditman** [comment]
It seems that the Google Testing check on this PR is failing because @mdebbar's reland PR hasn't relanded into G3 yet (?)

**Comment by mdebbar** [comment]
@ditman my PR should've landed into g3 today. Please try again and see if it works now.

**Comment by ditman** [comment]
(Rebased with the latest master)

**Comment by ditman** [comment]
The internal CL still has the wrong description, but the affected files now exactly match this PR, so I think the Google Testing step is going to work. Thanks @mdebbar!

**Comment by ditman** [comment]
Please, try again my dear bot.

**Pull request merged**
