### PR TITLE
Use `curly_braces_in_flow_control_structures ` for sample code

### PR DESCRIPTION
**Pull request by guidezpl**
Part of https://github.com/flutter/flutter/issues/104498

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by guidezpl — COMMENTED** [review]
Diff to review is https://github.com/guidezpl/flutter/commit/fffe900b6e7cc4022ac30b26d4bd4d7ddf73253e, the rest is from updating packages.

**Comment by guidezpl** [comment]
The addition to `examples/api/pubspec.yaml` gets wiped when updating packages, what to do?

**Comment by goderbauer** [comment]
> The addition to examples/api/pubspec.yaml gets wiped when updating packages, what to do?

Likely because of this: https://github.com/guidezpl/flutter/commit/fffe900b6e7cc4022ac30b26d4bd4d7ddf73253e#r74497341

**Comment by goderbauer** [comment]
Looks like the only difference is that flutter_lints is enforcing the `curly_braces_in_flow_control_structures` lint. I thought you are adding to the set of lints enforced in the repository as part of https://github.com/flutter/flutter/issues/104498, so that difference would go away soon.

I actually prefer the stricter set of lints we have enabled in the repository over flutter_lints because I think it produces even more readable sample code (e.g. you have to type everything). I believe, every lint that's part of flutter_lints is also already enforced in the repository (with the exception of the curly lint mentioned, but that's hopefully about to change). So, code that's clean under the repository lints should also be clean under flutter_lints (but not necessarily the other way around).

So, overall, I think switching the samples to `flutter_lints` would be a step back.

**Comment by guidezpl** [comment]
Makes sense, I'll repurpose this to just fix the `curly_braces_in_flow_control_structures`.

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
