### PR TITLE
Revert "echo error messages to stderr"

### PR DESCRIPTION
**Pull request by Hixie**
Reverts flutter/flutter#37845

### CODE REVIEW

**Comment by Hixie** [comment]
Filed https://github.com/flutter/flutter/issues/39161 to track the original bug.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by ryenus** [comment]
@tvolkert thank you for the reminder, but I haven't got the chance to setup a local build environment for flutter.

Honestly speaking, if someone can step up and push this forward, I'd be happy to see that happening.

**Pull request merged**
