### PR TITLE
ignore -> flutter_ignore

### PR DESCRIPTION
**Pull request by dnfield**
@goderbauer

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Shouldn't this also require a change in the test that looks for the ignore?

**Comment by dnfield** [comment]
The test just looks for the string. It doesn't parse ignore or flutter_ignore

**Comment by Hixie** [comment]
Oh. Then why bother with the flutter_ignore?

**Comment by dnfield** [comment]
Just to make it clear that it's ignoring something to readers. I could just drop it out, but if someone were reading this sample code they might wonder why the comment is there..?

**Comment by Hixie** [comment]
If the audience is humans, I would say something like "The following code uses sync* or async* despite our style guide's recommendation to avoid those features, because [reason for why it's ok here]".

That said, having done that I would then also make the test search for `The following code uses sync* or async* despite our style guide's recommendation to avoid those features, because` instead of `no_sync_async_star`.

**Comment by dnfield** [comment]
I'll follow @hixie's suggestion in a new PR.

**Pull request closed without merging**
