### PR TITLE
Add example IntelliJ metadata (flutter-intellij#607).

### PR DESCRIPTION
**Pull request by pq**
Ensures example projects open cleanly out-of-the-box w/ the Flutter Plugin.

See: https://github.com/flutter/flutter-intellij/issues/607.

@devoncarew

### CODE REVIEW

**Comment by devoncarew** [comment]
The `.idea/modules.xml` files look good.

Shouldn't the project `foo.iml` files be at the root of each project directory (not in the `.idea` subdirectory)?

**Comment by pq** [comment]
> Shouldn't the project foo.iml files be at the root of each project directory (not in the .idea subdirectory)?

I have no idea to be honest.  This is where they were put when I added the Flutter Module type (via the inspection) and it appears to work.  Removing them did not.

**Comment by devoncarew** [comment]
I think that the foo.iml file is generally at the project root - something like:

```
my_project/.idea/modules.xml
my_project/my_project.iml
```

**Comment by pq** [comment]
> We'll probably want to follow that example for hello_world, layers, and stocks (I think flutter_gallery already is).

Where is that example from?  I just let IntelliJ create the files for me and this where they went...  Nto a lot of the skin in the game.  Just curious!

**Comment by mit-mit** [comment]
If I create a new project, the `.iml` file is a sibling of the `.idea` so would be good to be consistent with that.

**Comment by pq** [comment]
Interestingly the **New Project** flow chooses a different location (the root) than adding a Flutter Module type (the `.idea` dir) as per the inspection.  I'll take a look at the inspection and see what's up there...

In the meantime, this should be more what you're after.

PTAL.

@devoncarew

**Comment by devoncarew** [comment]
lgtm! thanks for the updates

**Pull request merged**
