### PR TITLE
Reland "Do not rebuild Routes when a new opaque Route is pushed on top"

### PR DESCRIPTION
**Pull request by goderbauer**
See https://github.com/flutter/flutter/pull/48900 for full description of this change.

The reason for the revert turned out to be erroneous user code that was missing setState calls. The code was instead relying on the implicit rebuilds caused by pushing/popping routes which this PR removes. The google-internal tests in question have been fixed.

Reverts flutter/flutter#49366

Migration guide: https://github.com/flutter/website/pull/3581

### CODE REVIEW

**Review by bparrishMines — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
@dkwingsmt for review of the changes to the stepper test: https://github.com/flutter/flutter/pull/49376/files#diff-cf08a14b525117a713c3170d35000be3

**Review by dkwingsmt — APPROVED** [review]
LTGM on the fix in `stepper_test.dart`

**Comment by goderbauer** [comment]
This should not be submitted until the upstream fixes have been submitted to the internal google code base.

**Comment by goderbauer** [comment]
Upstream fixes are in, this is ready for submission when Cirrus is done.

**Pull request merged**
