### PR TITLE
Migrate build to null safety

### PR DESCRIPTION
**Pull request by Abhishek01039**
Part of #71511

### CODE REVIEW

**Comment by Abhishek01039** [comment]
image

Do we need this test when we are migrating this to null safety @jmagman ?

**Comment by Abhishek01039** [comment]
**We will migrate this when `packages/flutter_tools/lib/src/artifacts.dart` will be migrated to null safety**

**Comment by jmagman** [comment]
@Abhishek01039 all imported libraries need to be migrated before this can be migrated.  This is stuck behind `artifacts` and https://github.com/flutter/flutter/issues/80875.  I didn't spot any other libraries that could be migrated until that one is done.
Also, you should make sure at a minimum you don't have analyzer warnings before you put these out for review.  🙂 
https://github.com/flutter/flutter/pull/81106/checks?check_run_id=2425037280
```
   info • The library 'package:flutter_tools/src/artifacts.dart' is legacy, and should not be imported into a null safe library • packages/flutter_tools/lib/src/base/build.dart:6:8 • import_of_legacy_library_into_null_safe
```

**Comment by Abhishek01039** [comment]
I am also waiting for `artifacts` will migrate to null safety. @jmagman

**Comment by Abhishek01039** [comment]
Hello @jonahwilliams 
When you will migrate `packages/flutter_tools/lib/src/artifacts.dart` to null safety
then mark this PR as ready
thanks

**Comment by jmagman** [comment]
@Abhishek01039 artifacts has been migrated to null safety, you can rebase on top of tree.

**Comment by jmagman** [comment]
Also please migrate build_test at the same time.

**Comment by jmagman** [comment]
Lots of failing tests
```
02:16 +820 ~3 -1: test/general.shard/build_system/targets/common_test.dart: AotElfProfile Produces correct output directory [E]                                                                        
  NoSuchMethodError: The getter 'isNotEmpty' was called on null.
  Receiver: null
  Tried calling: isNotEmpty
  dart:core                                                          Object.noSuchMethod
  package:flutter_tools/src/base/build.dart 185:54                   AOTSnapshotter.build
```

**Comment by Abhishek01039** [comment]
CI getting an error in `project_test.dart` file which is unrelated to this PR I think.
I am getting this when I am trying to run this test locally
```
Failed to load "test/general.shard/project_test.dart": Directory listing failed, path = '/Users/abhishek/Desktop/open_source/flutter/bin/cache/artifacts/gradle_wrapper/' (OS Error: No such file or directory, errno = 2)
dart:io                                                      _Directory.listSync
2
ForwardingDirectory.listSync
package:file/…/forwarding/forwarding_directory.dart:43
transfer
test/general.shard/project_test.dart:853
_testInMemory
test/general.shard/project_test.dart:790
main.<fn>.<fn>
test/general.shard/project_test.dart:35
package:test_api                                             group
main.<fn>
test/general.shard/project_test.dart:34
package:test_api                                             group
main
test/general.shard/project_test.dart:33
2

✖ loading test/general.shard/project_test.dart
Exited (1)
```

**Comment by jonahwilliams** [comment]
CI is green right now so if the test is failing is because of your changes unfortunately

**Comment by jmagman** [comment]
> CI getting an error in `project_test.dart` file which is unrelated to this PR I think.

Filed https://github.com/flutter/flutter/issues/83275.  Run `flutter build apk` once to get the required cached artifacts downloaded.  In any case you should still be able to see the other failures locally.

**Comment by jmagman** [comment]
This was blocking the next clump of migrations, I have a version in https://github.com/flutter/flutter/pull/83381.

**Pull request closed without merging**
