### PR TITLE
[hotfix] flutter create -t plugin remove no-op iOS folder and set sdk min to 1.20.0

### LINKED ISSUE #60215: `flutter create -t plugin` should not create no-op iOS folders in 1.20.0 stable release
When 1.20 releases, we should make `flutter create -t plugin` command not creating no-op iOS folders anymore.
Also, we will add a lower flutter SDK bound setting to 1.20.0 for all the newly created plugins. 

Ideally, we'd like to land this change to the 1.20.0 release branch as it goes out.

### PR DESCRIPTION
**Pull request by cyanglaz**
This is a cherry-pick of https://github.com/flutter/flutter/commit/004f90f8fd8a8fb93d386d55364707ef1e517948 and https://github.com/flutter/flutter/commit/2459f5c513e26f7bc60d68d8e58972d37bbd6e58

Fixes https://github.com/flutter/flutter/issues/60215

In order to land this while passing CI, I also had to cherry-pick c9cd825fcae2fb7ead6343eb4eb7fa98e27f0d0f

### CODE REVIEW

**Comment by cyanglaz** [comment]
@christopherfujino I experienced some git tag issue with my previous rebased, so I closed the other PR(https://github.com/flutter/flutter/pull/62939) you just reviewed in favor of this one. Could you give another review?

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by cyanglaz** [comment]
@pcsosinski The flutter version is not reported correctly so the tests are failing on versions again. https://github.com/flutter/flutter/issues/62994

**Review by christopherfujino — APPROVED** [review]
LGTM, confirmed it locally (unknown channel is because my git HEAD was detached to check out a PR commit):

```
Flutter 1.20.1-0.0.pre.2 • channel unknown • unknown source
Framework • revision 199983b4ff (16 minutes ago) • 2020-08-05 15:20:27 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0
```

**Comment by cyanglaz** [comment]
@pcsosinski CI has passed.

**Review by pcsosinski — APPROVED** [review]
approved for 1.20, thanks @cyanglaz for getting this done and versioning fixed!

**Pull request merged**
