### PR TITLE
Fix ListView dartdoc where a paragraph doesn't flow with the section heading and the other paragraphs in the section

### PR DESCRIPTION
**Pull request by xster**

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by Hixie** [comment]
BTW, this was checked in when the tree was red. Please avoid checking anything in when the tree is red except for attempts to fix the tree, because it makes it much harder to detect, and later identify, additional failures introduced while the previous failure was ongoing. If you suspect a flaky result, please re-run the test rather than checking in while red. If that isn't possible, at a minimum please note the situation in the PR when landing it. Thanks!

**Comment by xster** [comment]
@Hixie my bad :S I deflaked the issue on the left side but didn't scroll far enough to the right to realize there was another one.

**Comment by Hixie** [comment]
@xster It's easy to tell when the tree is red, just don't commit when flutter-build is red. :-) It'll say "Some checks were not successful" and the box will be orange instead of green.

**Pull request merged**
