### PR TITLE
🐛 Only format Dart files for `gen-l10n`

### LINKED ISSUE #128932: [gen-l10n] Should not parse empty arb files as JSON content
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. `flutter create bug`
2. Integrate l10n as suggested.
3. Add `format: true` to `l10n.yaml`.
4. Create an empty arb file without any content in it (totally empty not even with `{}`).
5. Run `flutter gen-l10n`.

### Expected results

Only the generated dart files should be formatted.

### Actual results

l10n files except the untranslated message file are formatted.

### Code sample

<details><summary>Code sample</summary>

```yaml
synthetic-package: false
arb-dir: lib/src
format: true
output-dir: lib/src/gen
output-localization-file: app_localizations.dart
template-arb-file: l10n_en.arb
untranslated-messages-file: lib/src/gen/localizations_untranslated.json
```

</details>

### Screenshots or Video

_No response_

### Logs

<details><summary>Logs</summary>

```console
Because l10n.yaml exists, the options defined there will be used instead.                                                                                                                                                                                
To use the command line arguments, delete the l10n.yaml file in the Flutter project.


The arb file X:\Coding\Garages\packages\l10n\lib/src\l10n_zh.arb has the following formatting issue: 
FormatException: Unexpected end of input (at character 1)

^
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22621.1848], locale en-US)
    • Flutter version 3.10.5 on channel stable at X:\SDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (33 hours ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

</details>

### PR DESCRIPTION
**Pull request by AlexV525**
Improves #119596. The tests remain valid, so no tests were updated in the request.

This does not resolve issue #128932, it's handled by another part of the code.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by thkim1011** [comment]
Is it possible to write a test that calls `generateLocalizations` twice, but with different `untranslatedMessageFile` names? I think this scenario should cause it to error when using the old behavior. If this doesn't work, we should request a test exemption from Hixie in the #hackers channel of the Flutter Discord.

**Comment by AlexV525** [comment]
> Is it possible to write a test that calls `generateLocalizations` twice, but with different `untranslatedMessageFile` names? I think this scenario should cause it to error when using the old behavior.

The untranslated file has been filtered out before, so I think it should not work as intended? (Throws exception)

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

**Comment by AlexV525** [comment]
@thkim1011 PTAL

**Review by thkim1011 — APPROVED** [review]
LGTM

**Pull request merged**
