### PR TITLE
CupertinoNavigationBar leading is too high

### LINKED ISSUE #18536: CupertinoNavigationBar leading is too high
For some reason the leading in CupertinoNavigationBar is too high. Any ideas?

screen shot 2018-06-16 at 6 10 46 pm

```
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blueGrey,
      ),
      home: CupertinoPageScaffold(
        navigationBar: new CupertinoNavigationBar(
      leading: Text("lead"),
      middle: Text("Title"),
      trailing: Text("Trailing")
    ),
        child: Center(child: Text("Test!")),

      )
    );
  }
}
```

### PR DESCRIPTION
**Pull request by Abhishek01039**
fixes https://github.com/flutter/flutter/issues/18536

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Abhishek01039** [comment]
Hello @xster @goderbauer @a14n @HansMuller
Can you please review this PR?
Thanks

**Comment by xster** [comment]
The principle looks ok to me. You'd have to fix the test in nav_bar_transition_test as well.

**Comment by Abhishek01039** [comment]
sure thanks @xster

**Comment by Abhishek01039** [comment]
Which test do I need to fix? @xster

**Comment by Abhishek01039** [comment]
All test of `nav_bar_transition_test` passing locally here @xster

**Review by Piinks — COMMENTED** [review]
Hi @Abhishek01039 it looks like that test is still failing here across all platforms. What machine are you using locally that is passing?

**Pull request closed without merging**
