### PR TITLE
[flutter_tool] Report to analytics when the tool is killed by a signal

### PR DESCRIPTION
**Pull request by zanderso**
## Description

This PR adds signal handlers such that the tool will report a command result event and command timing when the tool is killed by a signal (SIGINT, SIGTERM).

## Tests

I added the following tests:

Tests in signals_test.dart and flutter_command_test.dart.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by christopherfujino — APPROVED** [review]
lgtm

**Review by christopherfujino — CHANGES_REQUESTED** [review]
looks like CI is failing

**Comment by zanderso** [comment]
Fixed tests.

**Pull request merged**
