### PR TITLE
[WIP] Rework `IconButton` using ButtonStyleButton

### PR DESCRIPTION
**Pull request by TahaTesser**
WIP 

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by TahaTesser** [comment]
@HansMuller 
Here I made a quick draft. 

I created a private `ButtonStyleButton` subclass. Extending `IconButton` directly will require providing the required parameter for super. Here you can see in my quick implementation (still a WIP), the button is basically a matching text button. Instead of splash color, hover color, it now uses overlayColor from ButtonStyle.  

Let me know if this is the right direction, where I could Material Layer for custom splash Radius

I also want to fix other IconButton issues during this rework 
Such as 
https://github.com/flutter/flutter/issues/30658
https://github.com/flutter/flutter/issues/28946
https://github.com/flutter/flutter/issues/64702
https://github.com/flutter/flutter/issues/31541
https://github.com/flutter/flutter/issues/25478
https://github.com/flutter/flutter/issues/21153

**Comment by HansMuller** [comment]
Yes, that's the approach I was suggesting: IconButton would have a ButtonStyle button child with default overrides provided by a new IconButtonTheme. Like TextButton et al. IconButton could be configured with a ButtonStyle. To ensure backwards compatibility, it will be necessary to support all of the current constructor parameters as well. Developers would have to select the style parameter or the the others, but not both. Ensuring that backwards compatibility is essentially perfect will be challenging.

**Comment by TahaTesser** [comment]
@HansMuller 
Friendly ping, as I asked on Discord, I cannot seem to figure out a way to provide a size to Material itself without increasing the overall button size, which breaks lots of tests.

I want the material to behavior like inkwell (non-intrusively) in the buttonstylebutton iconbutton

**Comment by TahaTesser** [comment]
@HansMuller 

I dug deeper into the inner workings of `InkResponse`, `InkWell`, and `Material`. 

`ButtonStylButton` abstract class carries both Material and InkWell. 

Material by defaulting does clipping and regardless of we're using `InkResponse` or `InkWell`, 

https://github.com/flutter/flutter/blob/6ba2f526a46518d35830f790359dd16a9e8e8cf2/packages/flutter/lib/src/material/material.dart#L550



and then InkWell l by sets `containedInkWell` to true, it cannot be overridden, unless replace with InkResponse entirely

https://github.com/flutter/flutter/blob/6ba2f526a46518d35830f790359dd16a9e8e8cf2/packages/flutter/lib/src/material/ink_well.dart#L1243

These strict my splash radius, even if I use custom splash factory

I am thinking to introduce a bool parameter that disables clipping in `Material`  (this could be useful other widgets too where you want to provide but don't want any clipping to occur) and replacing `InkWell` with `InkResponse` in `ButtonStyleButton`
Let me what do you think about this proposal?

**Comment by TahaTesser** [comment]
@HansMuller 
Friendly ping, I wanna make progress with this,  I still cannot get un-clipped Material with a size for Splash to be able to render. If you have suggestions, please let me know

**Comment by Piinks** [comment]
Hey @TahaTesser what is the state of this PR? It looks similar to some of our other button work. Is there anything I can do to help it along?

**Comment by TahaTesser** [comment]
@Piinks 

This turns out to be fairly difficult to implement as material clips ink well and I cannot recreate the same `IconButton` that can have an unclipped splash radius. (current`IconButton` doesn't have self-contained `Material`).

The goal of this rework was to create IconButton with self-contained `Material` using `TextButton` but without breaking `IconButon` itself.

**Comment by TahaTesser** [comment]
I found that the chip increases constraints for the hit test without increasing material size. For IconButton, I need the material itself to increase its size too. 

https://github.com/flutter/flutter/blob/b8734b1700bca240a9ebfe0bb4321eedb7eaeefe/packages/flutter/lib/src/material/chip.dart#L1269-L1274

**Comment by Piinks** [comment]
> the same `IconButton` that can have an unclipped splash radius. 

Is this unclipped behavior part of the material design spec?
Does adding the clipping break existing tests?

**Comment by TahaTesser** [comment]
> Is this unclipped behavior part of the material design spec?

Yes, InkWell is supposed to be overlapping either widget just like the current `IconButton` but applying `InkWell` with `Material` clips the splash area. 

This kinda splash is not possible, where the splash radius exceeds the widget size. As soon as `Material` is dded, splash can only be rendered on that material, which has a size equal to the widget's size.

Screenshot 2022-04-28 at 20 46 03

Adding material to widgets that don't expect their splash area to exceed is no longer
For example, I recently added Material to ListTile and fixed a list of issues as a result, this doesn't break any splash or clipping tests. 
https://github.com/flutter/flutter/pull/102310


> Does add the clipping break existing tests?

Yep, this basically breaks almost all tests.

**Comment by HansMuller** [comment]
The original ink-splash idea was to have the splash highlights from all components rendered on a single shared Material ancestor where the splash would not be clipped by the component that triggered it and where the splash might collide with other in-progress ink splashes from other components.  It's not clear if the Material Design spec ever required this however IconButton and InkWell (when used directly) still behave this way.

Based on https://github.com/flutter/flutter/pull/94599#issuecomment-1112501267 I think it would be best to end this attempt to re-implement IconButton using ButtonStyleButton, since ButtonStyleButton does build it's own Material widget. I wish I'd seen this more clearly at the outset. Thank you @TahaTesser for getting to the bottom of it.

**Comment by Piinks** [comment]
I am going to close this per @HansMuller's last comment but not without first acknowledging the valiant effort! Thanks @TahaTesser!
You work on complicated aspects on the framework, and a lot of them too! Sometimes I mix up which change is which - you have authored so many! 🙏 🎉 🏆

**Comment by TahaTesser** [comment]
@Piinks 
Thank you so much! It is not possible for me to add value without @HansMuller's and your feedback and lot of patience.

**Pull request closed without merging**
