### PR TITLE
make tests in xcodeproj_test.dart and gradle_test.dart hermetic (#18093)

### PR DESCRIPTION
**Pull request by ralph-bergmann**
https://github.com/flutter/flutter/issues/18093

### CODE REVIEW

**Comment by Hixie** [comment]
cc @tvolkert for review

**Comment by Hixie** [comment]
and cc @cbracken for the iOS parts

**Comment by Hixie** [comment]
@the4thfloor Thanks for your contribution! Making our tests more hermetic is definitely a good thing. Any chance you can rebase your PR? It looks like we have a conflict. Thanks.

**Comment by the4thfloor** [comment]
@Hixie yes of course. I will do that this evening

**Review by tvolkert — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
