### PR TITLE
Revert flutter/flutter#19592

### PR DESCRIPTION
**Pull request by tvolkert**
It was causing problems rolling Flutter into Fuchsia

### CODE REVIEW

**Review by a14n — APPROVED** [review]
LGTM but I think this revert will not be enough if you want to get rid of _optional const_.

There've been commits since #19592 and all those commits may have used optional const as well. So I suspect that you will face other issues.

**Comment by a14n** [comment]
I made a quick lint to find where optional const/new are. Here's the result of the run on your branch:

```
dev/devicelab/lib/tasks/gallery.dart 53:43 [lint]
dev/devicelab/lib/tasks/gallery.dart 59:46 [lint]
packages/flutter/test/widgets/list_wheel_scroll_view_test.dart 268:25 [lint]
packages/flutter/test/widgets/list_wheel_scroll_view_test.dart 323:25 [lint]
packages/flutter/lib/src/cupertino/segmented_control.dart 151:46 [lint]
packages/flutter/lib/src/material/chip.dart 1473:14 [lint]
packages/flutter/lib/src/services/platform_views.dart 13:53 [lint]
packages/flutter_goldens/test/flutter_goldens_test.dart 50:67 [lint]
```

**Comment by a14n** [comment]
With a fix on my lint to catch optional const on Map/List:

```
dev/devicelab/lib/tasks/gallery.dart 53:43 [lint]
dev/devicelab/lib/tasks/gallery.dart 59:46 [lint]
packages/flutter/test/widgets/list_wheel_scroll_view_test.dart 268:25 [lint]
packages/flutter/test/widgets/list_wheel_scroll_view_test.dart 323:25 [lint]
packages/flutter/lib/src/cupertino/segmented_control.dart 151:46 [lint]
packages/flutter/lib/src/material/chip.dart 1473:14 [lint]
packages/flutter/lib/src/services/text_input.dart 684:70 [lint]
packages/flutter/lib/src/services/text_input.dart 696:66 [lint]
packages/flutter/lib/src/services/platform_views.dart 13:53 [lint]
packages/flutter_goldens/test/flutter_goldens_test.dart 50:67 [lint]
packages/flutter_driver/test/src/timeline_summary_test.dart 210:41 [lint]
packages/flutter_driver/test/src/timeline_summary_test.dart 211:9 [lint]
packages/flutter_driver/test/src/timeline_summary_test.dart 212:9 [lint]
packages/flutter_driver/test/src/timeline_summary_test.dart 213:9 [lint]
packages/flutter_driver/test/src/timeline_summary_test.dart 216:30 [lint]
packages/flutter_test/test/finders_test.dart 21:41 [lint]
```

**Comment by tvolkert** [comment]
Thanks! I think all of those instances are actually ok in Fuchsia.  I'll send a different PR to revert them if that turns out not to be the case.

**Pull request merged**
