### PR TITLE
re-land "Retry cURL downloads"

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

This is a re-land of #50731, which was reverted because dart infra's version of `curl` didn't support `--retry-connrefused`. This re-lands the retry flags and leaves off the `--retry-connrefused` flag.

## Related Issues

#50730

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

### CODE REVIEW

**Comment by jmagman** [comment]
Did we ever get an answer to https://github.com/flutter/flutter/pull/50731#discussion_r383372136 from @zanderso?

> Any reason not to keep the default exponential backoff behavior?

**Comment by christopherfujino** [comment]
> Did we ever get an answer to [#50731 (comment)](https://github.com/flutter/flutter/pull/50731#discussion_r383372136) from @zanderso?
> 
> > Any reason not to keep the default exponential backoff behavior?

Nope. @fkorotkov?

**Comment by fkorotkov** [comment]
@christopherfujino 🤷‍♂ yeah, let's keep it simple then with just retry count.

**Comment by christopherfujino** [comment]
@jmagman removed explicit 5 second delay, PTAL

**Review by zanderso — APPROVED** [review]

**Pull request merged**
