### PR TITLE
Reapply flutter_assets

### PR DESCRIPTION
**Pull request by szakarias**
This reverts commit ee65db1 except the commit marking `complex_layout_ios__start_up` as flaky.

The problem with the Windows bots should be fixed with  #13564.

### CODE REVIEW

**Comment by szakarias** [comment]
cc @yjbanov .

**Review by jakobr-google — APPROVED** [review]
RSLGTM

**Comment by yjbanov** [comment]
lgtm

**Review by yjbanov — APPROVED** [review]

**Comment by xster** [comment]
Should this add some gitignores in the templates and the example projects?

**Comment by Hixie** [comment]
This dramatically increased the size of the gallery. Is that expected? Are we including assets twice now or some such?

**Comment by mehmetf** [comment]
Could we revert this and give @tvolkert a chance to review? It affects Google build system in a significant way. Rolls are blocked because of it.

**Comment by tvolkert** [comment]
@mehmetf not easily because we'd have to revert several engine commits as well.

s'ok - I'll roll this once I'm back - there shouldn't be that much activity over the holidays anyway.

**Comment by tvolkert** [comment]
@szakarias does was this tested with `--project=assets`?  That flag is used for prebuilt applications (which are used inside Google).

https://github.com/flutter/flutter/blob/12f405578f16baa8afcff7258da844f8462ea33c/packages/flutter_tools/lib/src/commands/run.dart#L115

https://github.com/flutter/flutter/blob/12f405578f16baa8afcff7258da844f8462ea33c/packages/flutter_tools/lib/src/resident_runner.dart#L406

**Comment by szakarias** [comment]
No, I will do that.

**Comment by alanrussian** [comment]
I need to merge #13521 into Google but this is currently blocking me, so I have to manually merge in #13521. Would be nice to have this fixed ASAP. Thanks!

**Comment by tvolkert** [comment]
FTR @szakarias the error we're seeing inside Google patching this in is:

```
I/flutter ( 3392): [INFO:engine.cc(586)] Could not configure asset bundle at path: 
```

You can reproduce by patching in cl/179637015

**Pull request merged**
