### PR TITLE
remove build_runner_core import from flutter_tools

### PR DESCRIPTION
**Pull request by jonahwilliams**
Its not safe to use build_runner packages outside of the build_runner directories

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Review by tvolkert — COMMENTED** [review]
LGTM

**Comment by zanderso** [comment]
Was this the only use? If so, do you also need to remove from pubspec.yaml and BUILD.gn?

**Comment by jonahwilliams** [comment]
No, this is only for the internal build. I've removed the build_runner directories and the entry point file from the sources there so the required parts can still build in the absence of all deps

**Pull request merged**
