### PR TITLE
Fix dep tracking

### PR DESCRIPTION
**Pull request by dcharkes**
Fix dependency tracking in the build.

* https://github.com/flutter/flutter/issues/147643

## Testing

It's not clear to me where to test the caching behavior of specific targets.

* test/general.shard/build_system/targets/common_test.dart
   * This doesn't test the caching behavior of any targets
* test/general.shard/build_system/build_system_test.dart
* test/general.shard/cache_test.dart
   * Both of these don't test specific `Target`s, these have `TestTarget`s.
* test/integration.shard/isolated/native_assets_test.dart
   * This could work, but it's an integration test that already takes long to run.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by dcharkes** [comment]
@christopherfujino Any suggestions on how to test this? I could add unit tests to the `Target` that they report inputs and outputs, but that doesn't actually test if that will be picked up by the build system.

Also, I'm slightly surprised that dependencies is not enough for the caching. I guess it makes sense that inputs and outputs is enough. But then why do we have dependencies.

**Comment by knopp** [comment]
I can confirm this resolves the issue.

**Comment by timmaffett** [comment]
I can confirm that this also fixes https://github.com/flutter/flutter/issues/147752

**Comment by dcharkes** [comment]
Hi @andrewkolos any chance you can get the review done? Multiple users are hit by this on the master branch.

**Comment by andrewkolos** [comment]
Ah sorry, this slipped off my radar. I'll take a look today.

**Review by andrewkolos — APPROVED** [review]
I am willing to LGTM now since this solves a pretty significant issue on master, though I do not have any additional insights on how to better test this onhand (outside of full integration test).

**Comment by dcharkes** [comment]
Thanks @andrewkolos!

If you come up with a good way to test this, let me know.

**Comment by zanderso** [comment]
This change has caused a somewhat large regression in build times https://github.com/flutter/flutter/issues/147982

**Comment by dcharkes** [comment]
Looking at the performance graph, it seems that the performance regression is the inverse of the performance gains by the PR that broke the dependency tracking (and made builds faster but broken).

**Pull request merged**
