### PR TITLE
[TextInput] send `setEditingState` before `show` to the text input plugin when switching input clients

### LINKED ISSUE #68571: The keyboard will disappear when switch focus on two TextField when secure keyboard is enabled
On my login page, I have two TextField, one for username(obscureText: false,), one for password(obscureText: true,).

after finish the username input, I click in the password textfield, the keyboard will disappear even if the password textfield get the focus. It will appear when click again!  Then, click username textfield again, the keyboard not appear also.

I have open the system secure keyboard:
To enable Secure Keyboard, go to [Settings] > [Additional Settings] > [Keyboard & Input Method] and toggle on [Use Secure Keyboard When Entering a Password].

If I close the system secure keyboard, everything is ok!!

this is my flutter doctor -v
```
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18362.1082], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] Connected device (1 available)
```

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
- Fixes https://github.com/flutter/flutter/issues/68571

Some Android keyboards ignore `showSoftInput` if they're immediately told to
restart after the `showSoftInput`.

- Related: https://github.com/flutter/flutter/issues/41990

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by LongCatIsLooong** [comment]
@GaryQian it seems #41990 specifically says "show" should come before "setEditingState", but in a comment from the internal bug it seems the order is actually irrelevant? Also, is there a list of Samsung keyboard versions that had the selection problems that I need to test on?

**Review by mdebbar — APPROVED** [review]
On the web, we had issues with the order of messages a while ago. Since then, we changed our implementation to handle any order. So this should be good to go for web.

**Review by justinmc — APPROVED** [review]
LGTM 👍 

This order seems reasonable to me, but I'm interested if Gary has any input.

**Review by GaryQian — APPROVED** [review]
LGTM.

This ordering change should be safe as later on, I was able to fix the root cause for the samusng issues and it was not related to this ordering.

**Pull request merged**
