### PR TITLE
use nnbd deps

### PR DESCRIPTION
**Pull request by a14n**
## Description

Use nullsafety dependencies.

## Related Issues

* dart-lang/sdk#40146

## Tests

I added the following tests:

None

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by leafpetersen** [comment]
cc @pcsosinski @jakemac53 @jonahwilliams @franklinyow @kevmoo

**Comment by jonahwilliams** [comment]
@fkorotkov what is up with the checks? I see the latest CI is going here: https://cirrus-ci.com/build/6141326519435264

**Review by jonahwilliams — APPROVED** [review]
LGTM if LG to CI

**Comment by a14n** [comment]
I don't know what's happen to job status: the cirrus jos are green :-/  https://cirrus-ci.com/build/5920935591018496

**Comment by jonahwilliams** [comment]
If they're all green there you should be good to submit, once the last host_ test finishes. the build status is also stuck right now, so we could kick with this PR

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by fkorotkov** [comment]
@jonahwilliams you are referring to a build for #59955. Commits in both of them have the same SHA though. This PR's build is this one: https://cirrus-ci.com/build/6141326519435264

**Comment by fkorotkov** [comment]
Apologies, you were right about the build for this PR. Let me try to get my head around how it all happened. Definetly the same SHA for commits is an issue here since GitHub's Check Runs are per SHA and not a pair of SHA and branch.

**Comment by fkorotkov** [comment]
I'm not sure what happened in #59955 but there was a synchronize event by @a14n 20 minutes after a push here. Branch for #59955  looks weird too: 

weirdissue

<details>
 <summary>pull_request.json</summary>

```json
{
  "action": "synchronize",
  "number": 59955,
  "pull_request": {
    "url": "https://api.github.com/repos/flutter/flutter/pulls/59955",
    "id": 437593980,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NDM3NTkzOTgw",
    "html_url": "https://github.com/flutter/flutter/pull/59955",
    "diff_url": "https://github.com/flutter/flutter/pull/59955.diff",
    "patch_url": "https://github.com/flutter/flutter/pull/59955.patch",
    "issue_url": "https://api.github.com/repos/flutter/flutter/issues/59955",
    "number": 59955,
    "state": "open",
    "locked": false,
    "title": "NNBD migrate packages/flutter/lib",
    "user": {
      "login": "a14n",
      "id": 1206632,
      "node_id": "MDQ6VXNlcjEyMDY2MzI=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1206632?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/a14n",
      "html_url": "https://github.com/a14n",
      "followers_url": "https://api.github.com/users/a14n/followers",
      "following_url": "https://api.github.com/users/a14n/following{/other_user}",
      "gists_url": "https://api.github.com/users/a14n/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/a14n/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/a14n/subscriptions",
      "organizations_url": "https://api.github.com/users/a14n/orgs",
      "repos_url": "https://api.github.com/users/a14n/repos",
      "events_url": "https://api.github.com/users/a14n/events{/privacy}",
      "received_events_url": "https://api.github.com/users/a14n/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "## Description\r\n\r\nNNBD migration for:\r\n\r\n* foundation\r\n* scheduler\r\n* physics\r\n* gestures\r\n\r\n## Related Issues\r\n\r\n* dart-lang/sdk#40146\r\n\r\n## Tests\r\n\r\nI added the following tests:\r\n\r\nNone\r\n\r\n## Checklist\r\n\r\nBefore you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.\r\n\r\n- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.\r\n- [x] I signed the [CLA].\r\n- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].\r\n- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.\r\n- [x] I updated/added relevant documentation (doc comments with `///`).\r\n- [x] All existing and new tests are passing.\r\n- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.\r\n- [x] I am willing to follow-up on review comments in a timely manner.\r\n\r\n## Breaking Change\r\n\r\nDid any tests fail when you ran them? Please read [Handling breaking changes].\r\n\r\n- [x] No, no existing tests failed, so this is *not* a breaking change.\r\n- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*\r\n   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*\r\n   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*\r\n   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*\r\n\r\n<!-- Links -->\r\n[issue database]: https://github.com/flutter/flutter/issues\r\n[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview\r\n[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter\r\n[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo\r\n[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement\r\n[CLA]: https://cla.developers.google.com/\r\n[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene\r\n[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes\r\n",
    "created_at": "2020-06-21T20:04:42Z",
    "updated_at": "2020-07-09T20:15:52Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": "28bf0a7274d718fdd00233bc73f99847a85e08fb",
    "assignee": null,
    "assignees": [

    ],
    "requested_reviewers": [

    ],
    "requested_teams": [

    ],
    "labels": [
      {
        "id": 487496476,
        "node_id": "MDU6TGFiZWw0ODc0OTY0NzY=",
        "url": "https://api.github.com/repos/flutter/flutter/labels/cla:%20yes",
        "name": "cla: yes",
        "color": "ffffff",
        "default": false,
        "description": "@googlebot is happy with this PR."
      },
      {
        "id": 284437560,
        "node_id": "MDU6TGFiZWwyODQ0Mzc1NjA=",
        "url": "https://api.github.com/repos/flutter/flutter/labels/framework",
        "name": "framework",
        "color": "207de5",
        "default": false,
        "description": "flutter/packages/flutter repository. See also f: labels."
      },
      {
        "id": 283479307,
        "node_id": "MDU6TGFiZWwyODM0NzkzMDc=",
        "url": "https://api.github.com/repos/flutter/flutter/labels/team",
        "name": "team",
        "color": "d4c5f9",
        "default": false,
        "description": "Infra upgrades, team productivity, code health, technical debt. See also team: labels."
      },
      {
        "id": 912685748,
        "node_id": "MDU6TGFiZWw5MTI2ODU3NDg=",
        "url": "https://api.github.com/repos/flutter/flutter/labels/work%20in%20progress;%20do%20not%20review",
        "name": "work in progress; do not review",
        "color": "000000",
        "default": false,
        "description": "This is a PR that is not going to be checked in in its current state, and does not need review."
      }
    ],
    "milestone": null,
    "draft": true,
    "commits_url": "https://api.github.com/repos/flutter/flutter/pulls/59955/commits",
    "review_comments_url": "https://api.github.com/repos/flutter/flutter/pulls/59955/comments",
    "review_comment_url": "https://api.github.com/repos/flutter/flutter/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/flutter/flutter/issues/59955/comments",
    "statuses_url": "https://api.github.com/repos/flutter/flutter/statuses/4968406c3c91d405b275b908d872471dd267aa09",
    "head": {
      "label": "a14n:nnbd-flutter",
      "ref": "nnbd-flutter",
      "sha": "4968406c3c91d405b275b908d872471dd267aa09",
      "user": {
        "login": "a14n",
        "id": 1206632,
        "node_id": "MDQ6VXNlcjEyMDY2MzI=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/1206632?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/a14n",
        "html_url": "https://github.com/a14n",
        "followers_url": "https://api.github.com/users/a14n/followers",
        "following_url": "https://api.github.com/users/a14n/following{/other_user}",
        "gists_url": "https://api.github.com/users/a14n/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/a14n/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/a14n/subscriptions",
        "organizations_url": "https://api.github.com/users/a14n/orgs",
        "repos_url": "https://api.github.com/users/a14n/repos",
        "events_url": "https://api.github.com/users/a14n/events{/privacy}",
        "received_events_url": "https://api.github.com/users/a14n/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 50984105,
        "node_id": "MDEwOlJlcG9zaXRvcnk1MDk4NDEwNQ==",
        "name": "flutter",
        "full_name": "a14n/flutter",
        "private": false,
        "owner": {
          "login": "a14n",
          "id": 1206632,
          "node_id": "MDQ6VXNlcjEyMDY2MzI=",
          "avatar_url": "https://avatars1.githubusercontent.com/u/1206632?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/a14n",
          "html_url": "https://github.com/a14n",
          "followers_url": "https://api.github.com/users/a14n/followers",
          "following_url": "https://api.github.com/users/a14n/following{/other_user}",
          "gists_url": "https://api.github.com/users/a14n/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/a14n/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/a14n/subscriptions",
          "organizations_url": "https://api.github.com/users/a14n/orgs",
          "repos_url": "https://api.github.com/users/a14n/repos",
          "events_url": "https://api.github.com/users/a14n/events{/privacy}",
          "received_events_url": "https://api.github.com/users/a14n/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/a14n/flutter",
        "description": "Framework for building high-performance, high-fidelity iOS and Android apps",
        "fork": true,
        "url": "https://api.github.com/repos/a14n/flutter",
        "forks_url": "https://api.github.com/repos/a14n/flutter/forks",
        "keys_url": "https://api.github.com/repos/a14n/flutter/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/a14n/flutter/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/a14n/flutter/teams",
        "hooks_url": "https://api.github.com/repos/a14n/flutter/hooks",
        "issue_events_url": "https://api.github.com/repos/a14n/flutter/issues/events{/number}",
        "events_url": "https://api.github.com/repos/a14n/flutter/events",
        "assignees_url": "https://api.github.com/repos/a14n/flutter/assignees{/user}",
        "branches_url": "https://api.github.com/repos/a14n/flutter/branches{/branch}",
        "tags_url": "https://api.github.com/repos/a14n/flutter/tags",
        "blobs_url": "https://api.github.com/repos/a14n/flutter/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/a14n/flutter/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/a14n/flutter/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/a14n/flutter/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/a14n/flutter/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/a14n/flutter/languages",
        "stargazers_url": "https://api.github.com/repos/a14n/flutter/stargazers",
        "contributors_url": "https://api.github.com/repos/a14n/flutter/contributors",
        "subscribers_url": "https://api.github.com/repos/a14n/flutter/subscribers",
        "subscription_url": "https://api.github.com/repos/a14n/flutter/subscription",
        "commits_url": "https://api.github.com/repos/a14n/flutter/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/a14n/flutter/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/a14n/flutter/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/a14n/flutter/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/a14n/flutter/contents/{+path}",
        "compare_url": "https://api.github.com/repos/a14n/flutter/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/a14n/flutter/merges",
        "archive_url": "https://api.github.com/repos/a14n/flutter/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/a14n/flutter/downloads",
        "issues_url": "https://api.github.com/repos/a14n/flutter/issues{/number}",
        "pulls_url": "https://api.github.com/repos/a14n/flutter/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/a14n/flutter/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/a14n/flutter/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/a14n/flutter/labels{/name}",
        "releases_url": "https://api.github.com/repos/a14n/flutter/releases{/id}",
        "deployments_url": "https://api.github.com/repos/a14n/flutter/deployments",
        "created_at": "2016-02-03T08:04:00Z",
        "updated_at": "2018-12-27T20:23:04Z",
        "pushed_at": "2020-07-09T20:15:47Z",
        "git_url": "git://github.com/a14n/flutter.git",
        "ssh_url": "git@github.com:a14n/flutter.git",
        "clone_url": "https://github.com/a14n/flutter.git",
        "svn_url": "https://github.com/a14n/flutter",
        "homepage": "http://flutter.io",
        "size": 107660,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Dart",
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 1,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
          "key": "other",
          "name": "Other",
          "spdx_id": "NOASSERTION",
          "url": null,
          "node_id": "MDc6TGljZW5zZTA="
        },
        "forks": 1,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master",
        "allow_squash_merge": true,
        "allow_merge_commit": true,
        "allow_rebase_merge": true,
        "delete_branch_on_merge": false
      }
    },
    "base": {
      "label": "flutter:master",
      "ref": "master",
      "sha": "61a04b1551a8f63b3081267dc7a0bbc16a1b4bf5",
      "user": {
        "login": "flutter",
        "id": 14101776,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
        "avatar_url": "https://avatars3.githubusercontent.com/u/14101776?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/flutter",
        "html_url": "https://github.com/flutter",
        "followers_url": "https://api.github.com/users/flutter/followers",
        "following_url": "https://api.github.com/users/flutter/following{/other_user}",
        "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
        "organizations_url": "https://api.github.com/users/flutter/orgs",
        "repos_url": "https://api.github.com/users/flutter/repos",
        "events_url": "https://api.github.com/users/flutter/events{/privacy}",
        "received_events_url": "https://api.github.com/users/flutter/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 31792824,
        "node_id": "MDEwOlJlcG9zaXRvcnkzMTc5MjgyNA==",
        "name": "flutter",
        "full_name": "flutter/flutter",
        "private": false,
        "owner": {
          "login": "flutter",
          "id": 14101776,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
          "avatar_url": "https://avatars3.githubusercontent.com/u/14101776?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/flutter",
          "html_url": "https://github.com/flutter",
          "followers_url": "https://api.github.com/users/flutter/followers",
          "following_url": "https://api.github.com/users/flutter/following{/other_user}",
          "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
          "organizations_url": "https://api.github.com/users/flutter/orgs",
          "repos_url": "https://api.github.com/users/flutter/repos",
          "events_url": "https://api.github.com/users/flutter/events{/privacy}",
          "received_events_url": "https://api.github.com/users/flutter/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/flutter/flutter",
        "description": "Flutter makes it easy and fast to build beautiful apps for mobile and beyond.",
        "fork": false,
        "url": "https://api.github.com/repos/flutter/flutter",
        "forks_url": "https://api.github.com/repos/flutter/flutter/forks",
        "keys_url": "https://api.github.com/repos/flutter/flutter/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/flutter/flutter/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/flutter/flutter/teams",
        "hooks_url": "https://api.github.com/repos/flutter/flutter/hooks",
        "issue_events_url": "https://api.github.com/repos/flutter/flutter/issues/events{/number}",
        "events_url": "https://api.github.com/repos/flutter/flutter/events",
        "assignees_url": "https://api.github.com/repos/flutter/flutter/assignees{/user}",
        "branches_url": "https://api.github.com/repos/flutter/flutter/branches{/branch}",
        "tags_url": "https://api.github.com/repos/flutter/flutter/tags",
        "blobs_url": "https://api.github.com/repos/flutter/flutter/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/flutter/flutter/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/flutter/flutter/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/flutter/flutter/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/flutter/flutter/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/flutter/flutter/languages",
        "stargazers_url": "https://api.github.com/repos/flutter/flutter/stargazers",
        "contributors_url": "https://api.github.com/repos/flutter/flutter/contributors",
        "subscribers_url": "https://api.github.com/repos/flutter/flutter/subscribers",
        "subscription_url": "https://api.github.com/repos/flutter/flutter/subscription",
        "commits_url": "https://api.github.com/repos/flutter/flutter/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/flutter/flutter/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/flutter/flutter/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/flutter/flutter/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/flutter/flutter/contents/{+path}",
        "compare_url": "https://api.github.com/repos/flutter/flutter/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/flutter/flutter/merges",
        "archive_url": "https://api.github.com/repos/flutter/flutter/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/flutter/flutter/downloads",
        "issues_url": "https://api.github.com/repos/flutter/flutter/issues{/number}",
        "pulls_url": "https://api.github.com/repos/flutter/flutter/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/flutter/flutter/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/flutter/flutter/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/flutter/flutter/labels{/name}",
        "releases_url": "https://api.github.com/repos/flutter/flutter/releases{/id}",
        "deployments_url": "https://api.github.com/repos/flutter/flutter/deployments",
        "created_at": "2015-03-06T22:54:58Z",
        "updated_at": "2020-07-09T19:46:58Z",
        "pushed_at": "2020-07-09T20:14:59Z",
        "git_url": "git://github.com/flutter/flutter.git",
        "ssh_url": "git@github.com:flutter/flutter.git",
        "clone_url": "https://github.com/flutter/flutter.git",
        "svn_url": "https://github.com/flutter/flutter",
        "homepage": "https://flutter.dev",
        "size": 107654,
        "stargazers_count": 95622,
        "watchers_count": 95622,
        "language": "Dart",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 13222,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 7922,
        "license": {
          "key": "bsd-3-clause",
          "name": "BSD 3-Clause \"New\" or \"Revised\" License",
          "spdx_id": "BSD-3-Clause",
          "url": "https://api.github.com/licenses/bsd-3-clause",
          "node_id": "MDc6TGljZW5zZTU="
        },
        "forks": 13222,
        "open_issues": 7922,
        "watchers": 95622,
        "default_branch": "master",
        "allow_squash_merge": true,
        "allow_merge_commit": false,
        "allow_rebase_merge": false,
        "delete_branch_on_merge": true
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/flutter/flutter/pulls/59955"
      },
      "html": {
        "href": "https://github.com/flutter/flutter/pull/59955"
      },
      "issue": {
        "href": "https://api.github.com/repos/flutter/flutter/issues/59955"
      },
      "comments": {
        "href": "https://api.github.com/repos/flutter/flutter/issues/59955/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/flutter/flutter/pulls/59955/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/flutter/flutter/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/flutter/flutter/pulls/59955/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/flutter/flutter/statuses/4968406c3c91d405b275b908d872471dd267aa09"
      }
    },
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "merged": false,
    "mergeable": null,
    "rebaseable": null,
    "mergeable_state": "draft",
    "merged_by": null,
    "comments": 0,
    "review_comments": 0,
    "maintainer_can_modify": true,
    "commits": 2,
    "additions": 6146,
    "deletions": 6214,
    "changed_files": 258
  },
  "before": "99f99128584d05644f78ab40c775f1fff0672ad2",
  "after": "4968406c3c91d405b275b908d872471dd267aa09",
  "repository": {
    "id": 31792824,
    "node_id": "MDEwOlJlcG9zaXRvcnkzMTc5MjgyNA==",
    "name": "flutter",
    "full_name": "flutter/flutter",
    "private": false,
    "owner": {
      "login": "flutter",
      "id": 14101776,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
      "avatar_url": "https://avatars3.githubusercontent.com/u/14101776?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flutter",
      "html_url": "https://github.com/flutter",
      "followers_url": "https://api.github.com/users/flutter/followers",
      "following_url": "https://api.github.com/users/flutter/following{/other_user}",
      "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
      "organizations_url": "https://api.github.com/users/flutter/orgs",
      "repos_url": "https://api.github.com/users/flutter/repos",
      "events_url": "https://api.github.com/users/flutter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flutter/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/flutter/flutter",
    "description": "Flutter makes it easy and fast to build beautiful apps for mobile and beyond.",
    "fork": false,
    "url": "https://api.github.com/repos/flutter/flutter",
    "forks_url": "https://api.github.com/repos/flutter/flutter/forks",
    "keys_url": "https://api.github.com/repos/flutter/flutter/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/flutter/flutter/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/flutter/flutter/teams",
    "hooks_url": "https://api.github.com/repos/flutter/flutter/hooks",
    "issue_events_url": "https://api.github.com/repos/flutter/flutter/issues/events{/number}",
    "events_url": "https://api.github.com/repos/flutter/flutter/events",
    "assignees_url": "https://api.github.com/repos/flutter/flutter/assignees{/user}",
    "branches_url": "https://api.github.com/repos/flutter/flutter/branches{/branch}",
    "tags_url": "https://api.github.com/repos/flutter/flutter/tags",
    "blobs_url": "https://api.github.com/repos/flutter/flutter/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/flutter/flutter/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/flutter/flutter/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/flutter/flutter/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/flutter/flutter/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/flutter/flutter/languages",
    "stargazers_url": "https://api.github.com/repos/flutter/flutter/stargazers",
    "contributors_url": "https://api.github.com/repos/flutter/flutter/contributors",
    "subscribers_url": "https://api.github.com/repos/flutter/flutter/subscribers",
    "subscription_url": "https://api.github.com/repos/flutter/flutter/subscription",
    "commits_url": "https://api.github.com/repos/flutter/flutter/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/flutter/flutter/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/flutter/flutter/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/flutter/flutter/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/flutter/flutter/contents/{+path}",
    "compare_url": "https://api.github.com/repos/flutter/flutter/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/flutter/flutter/merges",
    "archive_url": "https://api.github.com/repos/flutter/flutter/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/flutter/flutter/downloads",
    "issues_url": "https://api.github.com/repos/flutter/flutter/issues{/number}",
    "pulls_url": "https://api.github.com/repos/flutter/flutter/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/flutter/flutter/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/flutter/flutter/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/flutter/flutter/labels{/name}",
    "releases_url": "https://api.github.com/repos/flutter/flutter/releases{/id}",
    "deployments_url": "https://api.github.com/repos/flutter/flutter/deployments",
    "created_at": "2015-03-06T22:54:58Z",
    "updated_at": "2020-07-09T19:46:58Z",
    "pushed_at": "2020-07-09T20:14:59Z",
    "git_url": "git://github.com/flutter/flutter.git",
    "ssh_url": "git@github.com:flutter/flutter.git",
    "clone_url": "https://github.com/flutter/flutter.git",
    "svn_url": "https://github.com/flutter/flutter",
    "homepage": "https://flutter.dev",
    "size": 107654,
    "stargazers_count": 95622,
    "watchers_count": 95622,
    "language": "Dart",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 13222,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 7922,
    "license": {
      "key": "bsd-3-clause",
      "name": "BSD 3-Clause \"New\" or \"Revised\" License",
      "spdx_id": "BSD-3-Clause",
      "url": "https://api.github.com/licenses/bsd-3-clause",
      "node_id": "MDc6TGljZW5zZTU="
    },
    "forks": 13222,
    "open_issues": 7922,
    "watchers": 95622,
    "default_branch": "master"
  },
  "organization": {
    "login": "flutter",
    "id": 14101776,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
    "url": "https://api.github.com/orgs/flutter",
    "repos_url": "https://api.github.com/orgs/flutter/repos",
    "events_url": "https://api.github.com/orgs/flutter/events",
    "hooks_url": "https://api.github.com/orgs/flutter/hooks",
    "issues_url": "https://api.github.com/orgs/flutter/issues",
    "members_url": "https://api.github.com/orgs/flutter/members{/member}",
    "public_members_url": "https://api.github.com/orgs/flutter/public_members{/member}",
    "avatar_url": "https://avatars3.githubusercontent.com/u/14101776?v=4",
    "description": ""
  },
  "enterprise": {
    "id": 1732,
    "slug": "alphabet",
    "name": "Alphabet",
    "node_id": "MDEwOkVudGVycHJpc2UxNzMy",
    "avatar_url": "https://avatars2.githubusercontent.com/b/1732?v=4",
    "description": "",
    "website_url": "https://abc.xyz/",
    "html_url": "https://github.com/enterprises/alphabet",
    "created_at": "2019-12-19T00:30:52Z",
    "updated_at": "2019-12-19T21:05:17Z"
  },
  "sender": {
    "login": "a14n",
    "id": 1206632,
    "node_id": "MDQ6VXNlcjEyMDY2MzI=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/1206632?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/a14n",
    "html_url": "https://github.com/a14n",
    "followers_url": "https://api.github.com/users/a14n/followers",
    "following_url": "https://api.github.com/users/a14n/following{/other_user}",
    "gists_url": "https://api.github.com/users/a14n/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/a14n/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/a14n/subscriptions",
    "organizations_url": "https://api.github.com/users/a14n/orgs",
    "repos_url": "https://api.github.com/users/a14n/repos",
    "events_url": "https://api.github.com/users/a14n/events{/privacy}",
    "received_events_url": "https://api.github.com/users/a14n/received_events",
    "type": "User",
    "site_admin": false
  }
}
````
</details>

**Comment by a14n** [comment]
sorry, I accidentally pushed to another branch (corresponding to another PR) the same commit. I updated it very quickly but I didn't expect this could make this PR crazy.

**Comment by jonahwilliams** [comment]
All green, Submit! :D

**Comment by fkorotkov** [comment]
No woories, it's a known and very annoying issue on GH side about check on SHA level. 😪

**Pull request merged**
