### PR TITLE
Restore the default surface size in TestWidgetsFlutterBinding.reset

### PR DESCRIPTION
**Pull request by jason-simmons**
See https://github.com/flutter/flutter/issues/87194

### CODE REVIEW

**Review by flar — APPROVED** [review]
I didn't look too closely at the test change as I'm assuming that the change was a simple revert to the previous version without the try/finally.

LGTM.

**Comment by dkwingsmt** [comment]
I'm concerned about the side effect introduced by `setSurfaceSize`. Maybe we just need `_surfaceSize = null`? It might be the cause of the current red checks.

**Comment by jason-simmons** [comment]
Updated this to set `_surfaceSize = null` followed by a synchronous call to `handleMetricsChanged`

**Comment by jason-simmons** [comment]
Just doing `_surfaceSize = null` is insufficient to update binding state that is derived from the surface size.

But calling `handleMetricsChanged` in `reset()` is apparently breaking other tests (e.g. flutter_driver tests that are affected by task scheduling behavior)

Not sure if there is any safe way to restore this state during `reset()`

**Comment by dkwingsmt** [comment]
I made another attempt of this PR at https://github.com/flutter/flutter/pull/87240 and it passes. Apparently the problem is that renderView was updated with the new surface size.

**Pull request closed without merging**
