### PR TITLE
Update to valid build tools variant and update lockfiles

### PR DESCRIPTION
**Pull request by reidbaker**
https://github.com/flutter/flutter/issues/125331

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by camsim99 — APPROVED** [review]
LGTM :) optional suggestion is modifying `ci.yaml` temporarily to verify you get a successful run

**Comment by reidbaker** [comment]
> LGTM :) optional suggestion is modifying `ci.yaml` temporarily to verify you get a successful run

Good idea,  Updated in 1b02013

**Comment by reidbaker** [comment]
Well damn https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8781629673726734545/+/u/test_execution/Build_appbundle/stdout

**Review by gmackall — APPROVED** [review]

**Review by gmackall — APPROVED** [review]
LGTM again (looks like the web test timed out)

**Pull request merged**
