### PR TITLE
Prevent vertical scroll in shrine by ensuring card size fits the screen

### LINKED ISSUE #30449: Shrine App cards do not size to fit in the available vertical space.
I'm running the app on the iPhone XS max simulator and you're able to vertically scroll the cards in each column since they do not size to fit the available space. This does not happen on my pixel 3 however. Some investigation is needed into why this is happening.

### PR DESCRIPTION
**Pull request by rami-a**
## Description

This change will make sure that the Card height in Shrine fits on the screen and prevents vertical scrolling. The image aspect ratio is calculated based on the available height and width, however it was making an assumption that we should use a hard-coded aspect ratio if the available width was less than the available height. This assumption isn't necessary and now the cards will fit on screen and not introduce vertical scrolling

## Related Issues

Fixes #30449 

## Tests

No tests are in place for the Shrine study.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by clocksmith — APPROVED** [review]
LGTM

**Comment by willlarche** [comment]
The actual problem is that `physics: ClampingScrollPhysics(),` for `ListView`s got lost in the move. If you [check the same file in the codelab](https://github.com/material-components/material-components-flutter-codelabs/blob/104-complete/mdc_100_series/lib/supplemental/product_columns.dart), they have that.

**Comment by willlarche** [comment]
But it needs to be consted up good now.

**Comment by willlarche** [comment]
@rami-a explained the circumstances needed to see this are a tall narrow phone like the XR. And another PR got the clamping physics.

Taking a closer look, I've probed my brain for the original intent of this code and I think I remember. It was to ensure the images are all landscape. I'm making an executive order to make sure they are all landscape or square. Here's what needs to be done:

1. Rename `heightOfImages` to something better descriptive like `spaceForImagesHeight` since it doesn't represent the height of the images but how much available space there is for an image in the card.
1. Make sure it's 0 or positive.
1. Get the aspect ratio of the `constraints.biggest.width / spaceForImagesHeight`. Make sure it's between 33 / 49 and 1.0.
1. Make `33 / 49` `33.0 / 49.0`.

**Review by willlarche — CHANGES_REQUESTED** [review]
See comment above.

**Comment by willlarche** [comment]
The 33/49 minimum aspect ratio will make sure they don't totally collapse on animation but is tall enough for the shortest phone we support (the iPhone 5).

**Comment by willlarche** [comment]
And of course port this back to the codelabs branches and docs.

**Comment by willlarche** [comment]
And a comment explaining the ratio decisions.

**Comment by rami-a** [comment]
Spoke with @willlarche offline, the logic will actually be fill the available space even if the aspect ration is portrait, and fallback on a fixed aspect ratio if there is not enough space.

**Review by willlarche — APPROVED** [review]
Thank you!

**Pull request merged**
