### PR TITLE
Add a test for 3D transform with needsCompositing

### PR DESCRIPTION
**Pull request by liyuqian**
The test was first written in
https://github.com/flutter/flutter/issues/41654#issuecomment-558416745

This will ensure that https://github.com/flutter/flutter/issues/41654
won't have regressions.

This test would fail without https://github.com/flutter/engine/pull/18160

### CODE REVIEW

**Review by LongCatIsLooong — APPROVED** [review]
thank you!

**Comment by liyuqian** [comment]
@yjbanov @ferhatb : this golden test fails on the web (https://cirrus-ci.com/task/6684686187495424). It tries to verify that adding a RepaintBoundary or not would not change the rendering of a 3d Transform. Can you please check if there's anything that needs to be fixed?

**Comment by Piinks** [comment]
>  Can you please check if there's anything that needs to be fixed?

That test will need a `skip: isBrowser`. `toImage` is not yet supported: https://github.com/flutter/flutter/issues/42767

**Comment by liyuqian** [comment]
Thank you @Piinks !

**Pull request merged**
