### PR TITLE
Unpin archive package from tool, update to version without security advisories

### LINKED ISSUE #149427: The version of `archive` package the tool uses "are affected by security advisories"
```
Downloading packages...
   _fe_analyzer_shared 69.0.0 (70.0.0 available)
   analyzer 6.5.1 (6.5.2 available)
   archive 3.3.2 (affected by advisories: [^0], [^1], 3.6.0 available)
   web_socket_channel 2.4.5 (3.0.0 available)
 No dependencies changed.
 1 package is discontinued.
 Dependencies are affected by security advisories:
   [^0]: https://github.com/advisories/GHSA-9v85-q87q-g4vg
   [^1]: https://github.com/advisories/GHSA-r285-q736-9v95
```
https://github.com/advisories/GHSA-9v85-q87q-g4vg
> An issue in Archive v3.3.7 allows attackers to execute a path traversal via extracting a crafted zip file.

https://github.com/advisories/GHSA-r285-q736-9v95
> An issue in Archive v3.3.7 allows attackers to spoof zip filenames which can lead to inconsistent filename parsing.

Both issues are patched in `archive` 3.3.8.

In addition to there being security issues, the fact that this logging appears in tool output is embarrassing...

Pinned here
https://github.com/flutter/flutter/blob/5bd34ef541575eddae6aaa82fc76a59ae7e464c3/packages/flutter_tools/lib/src/update_packages_pins.dart#L22
Linked issue is https://github.com/flutter/flutter/issues/115660, appears this is blocked by https://github.com/flutter/flutter/issues/133371?  Can we update without totally changing Windows archiving in the meantime?

### PR DESCRIPTION
**Pull request by jmagman**
Unpin `archive` version and run  `flutter update-packages --force-upgrade` to show there are no additional dependencies pulled in (url_launcher was updated, but unrelated).

Fixes https://github.com/flutter/flutter/issues/149427

### CODE REVIEW

**Comment by jmagman** [comment]
I think this is failing due to https://github.com/brendan-duncan/archive/issues/334 which @brianquinlan fixed, but it's not released yet.

**Comment by jmagman** [comment]
> I think this is failing due to [brendan-duncan/archive#334](https://github.com/brendan-duncan/archive/issues/334) which @brianquinlan fixed, but it's not released yet.

Actually [the fix](https://github.com/brendan-duncan/archive/commit/2606878cd4e50d136b9794e7b8ca1c787fa043e5) is in 3.6.0, which is the version this is failing on...

**Comment by jmagman** [comment]
That other issue is related but not the same.  Filed a more specific issue against `archive` https://github.com/brendan-duncan/archive/issues/339

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
