### PR TITLE
Remove pressure customization from some pointer events

### LINKED ISSUE #30412: Some event kinds shouldn't allow non-zero pressure
## Reasoning

Currently most pointer event classes accepts a parameter `pressure` in their unnamed constructors and pass it to their superclass `PointerEvent`. This allows them to have non-zero pressure, which however doesn't always makes sense. More specifically, a non-zero pressure indicates that the pointer is in contact with the screen with certain force. The following table lists all event types and whether they are supposed to have a non-zero pressure:

| Pointer event kind | Does non-zero pressure make sense? |
| -- | -- |
| `PointerAddedEvents` | **No**. This event indicates the start of the device tracking the pointer, which should contain no movement. |
| `PointerCancelEvents` | **No**. This event indicates the end the pointer being directed towards this device, which should contain no movement. |
| `PointerScrollEvents` | **No**. It's a pointer signal and doesn't change the state of the pointer.  |
| `PointerSignalEvents` | **No**. Pointer signals doesn't change the state of the pointer. |
| `PointerUpEvents` | **No**. The pointer has stopped making contact with the device, hence the pressure must be zero. |
| `PointerMoveEvents` | **Yes**. The pointer is moving while in contact with the device. |
| `PointerDownEvents` | **Yes**. The pointer has made contact with the device. |
| `PointerExitEvents` | **No**. This event only includes situations where the pointer is not in contact with the device. |
| `PointerEnterEvents` | **No**. This event only includes situations where the pointer is not in contact with the device. |
| `PointerHoverEvents` | **No**. The pointer is moving while not in contact with the device. |
| `PointerRemovedEvents` | **No**. This event indicates the end of the device tracking the pointer, which should contain no movement. |

This parameter was brought in by https://github.com/flutter/flutter/pull/24554, which added pressure to every pointer event classes to support force press gesture. According to [discussion](https://github.com/flutter/flutter/pull/24554/files#r241582381), this change was questioned ([here](https://github.com/flutter/flutter/pull/24554#discussion_r236782663) among many others) at first, but eventually made it due to miscommunication. [A later PR](https://github.com/flutter/flutter/pull/24830) which added Enter and Exit likely followed the same pattern for consistency.

## Changes

We propose to remove `pressure` from the unnamed constructors of the following classes:
- `PointerAddedEvent`
- `PointerRemovedEvent`
- `PointerHoverEvent`
- `PointerEnterEvent`
- `PointerExitEvent`
- `PointerUpEvent`
- `PointerCancelEvent`

Instead, each class will pass `pressure = 0.0` to its superclass.

A proposed PR can be found at https://github.com/flutter/flutter/pull/30414.

## Impact

This change will break code that _explicitly creates_ an instance of the aforementioned classes and specifying pressure.

To migrate the affected code,
- If your constructor has pressure = 0.0, simply remove this argument and the behavior will be the same.
- If your constructor has a non-zero pressure, migrate based on why it was needed. For example,
  - A `PointerHoverEvent` in this way is likely a misuse from `PointerMoveEvent`, which is defined as moving while the pointer is _in contact with the device_ (per class documentation), where a non-zero pressure makes sense.
  - A `PointerAddedEvent` in this way should be expanded into an `Added` followed by a `Down` with the requested `pressure` and `down`.
  - A `PointerRemovedEvent` or `PointerCancelEvent` in this way should be expanded into a `Move` with the requested `pressure` and `down` followed by a `Removed` or `Cancel`.

This change will _not_ break code that uses events dispatched by Flutter framework, including all gestures.

### PR DESCRIPTION
**Pull request by dkwingsmt**
## Description

This PR removes parameter `pressure` from the constructors of the following classes:
- `PointerAddedEvent`
- `PointerRemovedEvent`
- `PointerHoverEvent`
- `PointerEnterEvent`
- `PointerExitEvent`
- `PointerUpEvent`
- `PointerCancelEvent`

It also changes `PointerEnterEvent.fromMouseEvent` and `PointerExitEvent.fromMouseEvent` into redirecting to their unnamed constructors, which drops the arguments `down` and `pressure` from the source event.

For reasoning, migration, and discussion, see https://github.com/flutter/flutter/issues/30412.

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/30412

## Tests

It's not related to any tests.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change. It has been proposed at https://groups.google.com/forum/#!topic/flutter-announce/9xk75BKu8bw

### CODE REVIEW

**Comment by dkwingsmt** [comment]
This PR contains the breaking change part that used to be in https://github.com/flutter/flutter/pull/30414.

**Comment by goderbauer** [comment]
Did you follow the breaking change policy from the wiki? Can you link to the announcement? In the PR description? Thanks!

**Comment by dkwingsmt** [comment]
@goderbauer I'm still preparing the announcement, and I found some other issues that I need to reassure before doing so. I will send an announcement, update this PR and make sure to leave enough time.

**Comment by dkwingsmt** [comment]
@goderbauer It seems no objection has been raised in the past 7 days since the proposal (link in PR description). Can you review the PR?

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
This is breaking the embedded_android_views_integration_test

**Pull request merged**
