### PR TITLE
Add icon update tool

### PR DESCRIPTION
**Pull request by cbracken**

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Comment by cbracken** [comment]
IIRC, the updated font had been released only days before this PR. The github repo is apparently only updated periodically. @shyndman from the Material fonts team provided me a link. Probably worth pinging them and see when their Github repo will be updated to get in sync with the current release.

Example that uses the iOS back arrow: http://codepen.io/shyndman/pen/qaPEvx

**Comment by devoncarew** [comment]
Thanks for the info! I opened https://github.com/google/material-design-icons/issues/531 to ask about updating the repo or if there was a better source for the icons.

**Comment by eseidelGoogle** [comment]
Flutter maintains the pub package last I knew:
https://github.com/flutter/flutter/wiki/Updating-Material-Design-Fonts

**Pull request merged**
