### PR TITLE
Revert "Add android license verification to doctor and some refactoring"

### PR DESCRIPTION
**Pull request by tvolkert**
Reverts flutter/flutter#14535

Reports from that commit included:
* Doctor hanging
* Doctor prompting to install JDK
* AnsiStatus.cancel() printing elapsed time and extra newline
* Printing extra spinner character at the end of each line

### CODE REVIEW

**Review by aam — APPROVED** [review]

**Review by cbracken — APPROVED** [review]
RSLGTM - but it'd be useful to add a comment as to why it was reverted, ideally with a link to a bug.

**Comment by tvolkert** [comment]
Updated the description.  No issues were filed yet, but there were four different problem reports.

**Comment by aam** [comment]
I have filed https://github.com/flutter/flutter/issues/14725 for `flutter doctor` hanging

**Comment by jcollins-g** [comment]
Yikes.  It's possible the timeout on the license verification is too large, and I'll look into the other issues.

**Pull request merged**
