### PR TITLE
[WORK IN PROGRESS] [build] add OS X Travis build

### PR DESCRIPTION
**Pull request by yjbanov**
/cc @chinmaygarde

### CODE REVIEW

**Comment by chinmaygarde** [comment]
lgtm

**Comment by yjbanov** [comment]
Depends on #4028

**Comment by Hixie** [comment]
Do you also have a patch for turning the tests on on the infra bots?

**Comment by yjbanov** [comment]
@Hixie Good idea. Logged a separate issue (https://github.com/flutter/flutter/issues/4056) because this has to be done in the Chrome infra repo.

**Comment by Hixie** [comment]
@yjbanov I'm closing this PR since it's been inactive for a couple of weeks and is not ready for checkin, but please don't hesitate to reopen it when it's ready.

**Pull request closed without merging**
