### PR TITLE
Show iOS simulator device logger use a category whitelist

### PR DESCRIPTION
**Pull request by tvolkert**
This should trim down the log spam but allow us hooks into whitelisting
certain log categories so that they show up in the logs

### CODE REVIEW

**Comment by tvolkert** [comment]
@abarth @chinmaygarde

**Comment by abarth** [comment]
As discussed on chat, I think this is going to be too tight a filter and cause us to miss important messages.

**Comment by tvolkert** [comment]
You don't think we can just add to the whitelist as needed?

**Comment by abarth** [comment]
> You don't think we can just add to the whitelist as needed?

I think it's a no-win scenario.

**Comment by Hixie** [comment]
Can someone describe how iOS differs from Android here?

**Comment by chinmaygarde** [comment]
> Can someone describe how iOS differs from Android here?

No difference. Same problem, different spam.

I don't think this approach is scalable. I am sure this patch makes the things a bit more readable but we will definitely have to revisit this in the future.

A cleaner fix would be to add an engine option that redirects all log output from the engine to a socket specified at application launch. The tools can then forward this from the device to the host (like we already do for the observatory) and listen on it for logs that we can be sure are from the application. If no such option is specified, we can dump the logs to either `logcat` or `syslog` like we always do. This way, in case of crashes, we can still inspect the unfiltered system log for deeper analysis. This will make us resilient to changes in device specific log spam across OS versions and platforms.

Philosophical issues aside, this patch lgtm.

**Comment by Hixie** [comment]
If Android and iOS are basically the same here, then we should use the same approach. I don't think it makes sense that we be aggressively filtering on Android but paranoid about not filtering too much on iOS.

Personally I think we should land this. The experience on iOS last I tried it was less pleasant than on Android precisely because the logs were more verbose and less useful on iOS.

**Comment by Hixie** [comment]
I agree that this will need tweaking over time. We've been tweaking the Android filtering a lot over the past few months, and aside from the complete lack of feedback when there's a crash, we're actually at a pretty good place with very little false-positive and few false-negatives. (When there's a crash, we suck, though, because we basically get none of the various crash-related messages.)

**Comment by Hixie** [comment]
See https://github.com/flutter/flutter/issues/6756 and https://github.com/flutter/flutter/issues/6849 for problems filtering too much on Android.

**Comment by tvolkert** [comment]
I don't feel strongly about landing or not - I leave it up to Adam.

**Pull request closed without merging**
