### PR TITLE
Don't use a default test randomize ordering seed

### LINKED ISSUE #51010: stray "shuffling test order" message in `flutter test` output
Any time I run `flutter test` there's a stray line of output in the stdout:

```
Shuffling test order with --test-randomize-ordering-seed=0
```

This violates our style guide which requires no non-actionable output in general.

Looks like this is a regression with a recent package:test rev, and that we had a test that verified that we didn't regress this but it was modified in https://github.com/flutter/flutter/pull/50879 to allow for this output.

### PR DESCRIPTION
**Pull request by natebosch**
Fixes #51010

The test package differentiates between passing and not passing this
argument. A previous version had a bug that treated passing `0`
identically to not passing the argument, and the flutter test runner
relied on this bug by always passing a value and using a default of `0`.

- Remove the argument defaults throughout to make it clear that `null`
  is a valid value and the default.
- Remove the argument defaulting on the argument parser.
- Update the wording of the usage for this argument, this will also be
  updated on the `package:test` side.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
I'm fine with this if this is desired, but I thought that we _wanted_ to randomize the tests by default? Is that not the case?

**Comment by dnfield** [comment]
We do, but we're not ready to yet.  I started doing the work for the tool and have gotten distracted by some more pressing issues.  It will be al arge effort for the framework.

**Comment by natebosch** [comment]
> I thought that we _wanted_ to randomize the tests by default? Is that not the case?

If you go that route you will definitely not want to suppress the extra output. It is actionable by the user because it is how they can repeat a test run.

**Comment by dnfield** [comment]
@natebosch  exactly.

We __should__ suppress the output if the user did not request it.

We __should not__ suppress the output if the user requested to shuffle tests (whether with an exact or random seed).  AFAICT your linked patch does that.

**Comment by natebosch** [comment]
> AFAICT your linked patch does that.

Yes it does.

**Comment by Hixie** [comment]
If we randomize with a fixed seed by default (which seems to me to be the ideal setup) then the message isn't actionable since it's just the default (right?).

**Comment by natebosch** [comment]
> the message isn't actionable since it's just the default (right?).

Yeah I think you're right. It would be different from the Dart test runner, and different from what users are accustomed to, but once it becomes the new normal I think the message loses it's value for the default.

If you decide to go down this route we will should coordinate and either apply the default in the test runner (so that it's consistent for everyone and we can handle the message suppression uniformly) or we'd probably have to give you some new mechanism to suppress that output.

**Comment by natebosch** [comment]
cc @jakemac53 @grouma to consider whether we should randomize by default in the test runner.

**Comment by grouma** [comment]
I don't have a strong opinion here but I did take a look at the internal Go, Karma (JS / TS) and Java test runners. It looks like they don't randomize order by default. For consistency I'd say we'd do the same.

**Comment by jakemac53** [comment]
We would I think have to consider it a breaking change at least. I would not necessarily be opposed, although I would lean towards a random seed and not a fixed seed.

It should really be the default though in terms of enforcing good practices etc.

**Pull request merged**
