### PR TITLE
Re-landing SliverAnimatedList

### LINKED ISSUE #11339: Convert AnimatedList to a sliver
AnimatedList uses a pattern we know is bad: it provides the scroll view. This means, for example, that there's no way to combine the AnimatedList with a SliverGrid.

We should refactor AnimatedList to be a SliverAnimatedList.

cc @HansMuller

### PR DESCRIPTION
**Pull request by Piinks**
## Description

Original PR (#28834) was reverted due to merge conflicts. 

Will follow-up with diagrams and sample snippets.

## Related Issues

Fixes #11339

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Piinks** [comment]
@simolus3 I would like to re-land this change. Would you mind addressing the Google cla bot's comment above? Thank you! :)

**Comment by simolus3** [comment]
@googlebot I consent.

**Comment by Piinks** [comment]
cc/ @goderbauer

**Comment by Piinks** [comment]
Reconciling the merge went badly from this branch to master. I decided to try going to other way (master to branch) and had a much better time. I opened a new pull request with the updated branch.

**Pull request closed without merging**
