### PR TITLE
Remove Deprecated RenderUnconstrainedBox

### PR DESCRIPTION
**Pull request by Piinks**
WIP - tests still need to be migrated

This removes `RenderUnconstrainedBox`

This deprecated class has reached end of life after the release of Flutter 3.3

- The replacement is to use `RenderConstraintsTransformBox instead`.
- Dart fix is TBD since there is a new `replacedBy` feature
- 🕐 This API was deprecated in https://github.com/flutter/flutter/pull/78673, with more context in https://github.com/flutter/flutter/pull/77994, tagged v2.1

Part of https://github.com/flutter/flutter/issues/111708
For the full list of deprecations being removed in this batch, see [flutter.dev/go/deprecations-removed-after-3-3](flutter.dev/go/deprecations-removed-after-3-3)

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Piinks** [comment]
@LongCatIsLooong can you advise what the migration is for this deprecation? There is no guide at https://docs.flutter.dev/release/breaking-changes. I'd like to see if I can add a dart fix for this.

There are a bunch of tests in box_test.dart that need to be migrated or removed, I am not sure which.

**Review by LongCatIsLooong — APPROVED** [review]

**Comment by LongCatIsLooong** [comment]
I think `RenderUnconstrainedBox(constrainedAxis: Axis.vertical)` is equivalent to `RenderConstraintsTransformBox(constraintsTransform: ConstraintsTransformBox.heightConstrained)`, and `RenderUnconstrainedBox(constrainedAxis: Axis.horizontal)` is equivalent to `RenderConstraintsTransformBox(constraintsTransform: ConstraintsTransformBox.widthConstrained)`. Other parameters are pretty much 1:1.

**Comment by Piinks** [comment]
Oh fabulous, thank you! I think I can write an auto-fix for it then.

**Comment by LongCatIsLooong** [comment]
The widget using the deprecated render object at the time (`UnconstrainedBox`) has already been migrated to `RenderConstraintsTransformBox`

**Comment by Piinks** [comment]
Unfortunately the dart fix did not work as expected, filed https://github.com/dart-lang/sdk/issues/50011 to track and follow up. I think this can move ahead, and I will include the expected transforms in the migration guide.

**Pull request merged**
