### PR TITLE
Fix inconsistently suffixed macOS flavored bundle directory

### PR DESCRIPTION
**Pull request by arnemolland**
The current implementation of macOS flavor support (#119564) assumes a bundle directory that differs from both the iOS implementation and the official documentation. The [documentation](https://docs.flutter.dev/deployment/flavors) instructs developers to suffix their Xcode build configurations with `-<flavor>`, but the implementation assumes a space:

https://github.com/flutter/flutter/blob/5fd9ef4240d3fc239f042f49b8eb1ad24260091f/packages/flutter_tools/lib/src/macos/application_package.dart#L174-L178

Whereas the iOS implementation, which is the reference for the docs, assumes a `-<flavor>` suffix:

https://github.com/flutter/flutter/blob/a257efc2841ed7042322fbd043f0983e705d7da2/packages/flutter_tools/lib/src/ios/xcodeproj.dart#L482-L488

This change replaces the empty space with the `-` character which is in line with the documentation and iOS implementation, as well as removing the sentence-casing applied to the flavor name; every bundle built with a flavor keeps the original flavor name in its filename.

*List which issues are fixed by this PR. You must list at least one issue.*
#122684.

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jascodes** [comment]
@goderbauer looks like pretty straight forward, any plans to review merge this?

**Comment by jascodes** [comment]
Any update please?

**Comment by ryanduffyne** [comment]
Has there been any movement on this change.  It seems pretty simple and would be a huge quality of life upgrade for developers.  Currently the only way I can run the macos version of the app is through xcode and that is annoying.  I don't like to have to document this for other developers as an exception to the rule for how to run the app during development.

**Comment by arnemolland** [comment]
> Has there been any movement on this change.  It seems pretty simple and would be a huge quality of life upgrade for developers.  Currently the only way I can run the macos version of the app is through xcode and that is annoying.  I don't like to have to document this for other developers as an exception to the rule for how to run the app during development.

Hoping to get a review on this shortly, but it doesn’t look like a team member has particular ownership looking at the issue yet.

cc @goderbauer, @christopherfujino

**Comment by christopherfujino** [comment]
> > Has there been any movement on this change.  It seems pretty simple and would be a huge quality of life upgrade for developers.  Currently the only way I can run the macos version of the app is through xcode and that is annoying.  I don't like to have to document this for other developers as an exception to the rule for how to run the app during development.
> 
> Hoping to get a review on this shortly, but it doesn’t look like a team member has particular ownership looking at the issue yet.

Whoops, missed this in tool PR review last week. Looking now.

**Review by christopherfujino — COMMENTED** [review]
This looks good to me. However, I wonder if this would be a breaking change. @cbracken WDYT?

**Comment by ryanduffyne** [comment]
Probably to the people who took time to try to hack around it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cbracken** [comment]
Yep this will be a breaking change, but given that we haven't officially announced flavours support (the device lab test was broken and was reverted while still in `bringup` mode), I think that's fine.

Thanks for CCing me. Taking a look. 

I wonder if there's a way to get auto cc'ed on macOS-specific tool changes. There's an email-based patch monitoring tool I use; will see if that allows path-based filters. Will also see if there's a reasonable set of paths we can use for the GitHub bot to auto-tag these with the platform where relevant, if it's not too fragile.

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

**Comment by christopherfujino** [comment]
> Will also see if there's a reasonable set of paths we can use for the GitHub bot to auto-tag these with the platform where relevant, if it's not too fragile.

@cbracken If you decide on the paths you're interested in, adding entries to https://github.com/flutter/flutter/blob/master/.github/labeler.yml will enable auto-labeling.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
