### PR TITLE
Update dartdoc to 0.30.2

### PR DESCRIPTION
**Pull request by jcollins-g**
This fixes some search box problems for Flutter in 0.30.1, and adds the --use-base-href flag as the Flutter post-processing of Dartdoc output requires it (without it, last push broke the docs).  cc @jdkoren

Release notes:  https://github.com/dart-lang/dartdoc/releases/tag/v0.30.2

Screenshots of Flutter docs with this PR:

Screen Shot 2020-03-05 at 9 10 15 AM
Screen Shot 2020-03-05 at 9 10 55 AM
Screen Shot 2020-03-05 at 9 11 30 AM
Screen Shot 2020-03-05 at 9 13 12 AM

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
Looks some of the links on the right side are still broken :(. Was there an issue filed for that?

**Comment by jcollins-g** [comment]
@goderbauer https://github.com/dart-lang/dartdoc/issues/2099 covers the issue of dead links in Flutter, but NNBD has taken too much of my time to pursue it right now.

**Comment by jcollins-g** [comment]
`flutter-build` seems to be "broken" a lot and so I haven't landed this change as when I check it is red.  Should I ignore this and land the change anyway?  @goderbauer / @gspencergoog

**Comment by goderbauer** [comment]
You can label this PR with "waiting for tree to be green" and it will auto-submit when the tree is green the next time.

**Comment by goderbauer** [comment]
(Added the label for you)

**Pull request merged**
