### PR TITLE
Roll Engine from 20caf5496951 to 14a6fd97ca12 (67 revisions)

### PR DESCRIPTION
**Pull request by engine-flutter-autoroll**
Roll Engine from 20caf5496951 to 14a6fd97ca12 (67 revisions)

https://github.com/flutter/engine/compare/20caf5496951...14a6fd97ca12

2020-12-03 chris@bracken.jp Fix NPE when platform plugin delegate is null (flutter/engine#22852)
2020-12-03 skia-flutter-autoroll@skia.org Roll Skia from 38921cafe1bb to abcc1ecdfd0c (8 revisions) (flutter/engine#22851)
2020-12-03 zl398833@alibaba-inc.com More rename from GPU thread to raster thread (flutter/engine#22819)
2020-12-03 gspencergoog@users.noreply.github.com Add delayed event delivery for Linux. (flutter/engine#22577)
2020-12-03 skia-flutter-autoroll@skia.org Roll Dart SDK from 97cfd05b3cb3 to a37a4d42e53d (4 revisions) (flutter/engine#22849)
2020-12-03 skia-flutter-autoroll@skia.org Roll Skia from d39aec0e40ec to 38921cafe1bb (7 revisions) (flutter/engine#22847)
2020-12-03 yjbanov@google.com Make CkPicture resurrectable (flutter/engine#22807)
2020-12-03 nurhan@google.com leaving only html tests (flutter/engine#22846)
2020-12-03 skia-flutter-autoroll@skia.org Roll Skia from c7112edbe0f4 to d39aec0e40ec (17 revisions) (flutter/engine#22844)
2020-12-03 skia-flutter-autoroll@skia.org Roll Fuchsia Mac SDK from Z_-ciOYM9... to DRN4P3zbe... (flutter/engine#22841)
2020-12-03 ferhat@gmail.com [web] Fix event transform between mousedown/up due to mouse move event (flutter/engine#22813)
2020-12-03 skia-flutter-autoroll@skia.org Roll Dart SDK from cfaa7606cbf5 to 97cfd05b3cb3 (2 revisions) (flutter/engine#22840)
2020-12-03 skia-flutter-autoroll@skia.org Roll Skia from 9443d58af292 to c7112edbe0f4 (10 revisions) (flutter/engine#22839)
2020-12-03 RichardJCai@users.noreply.github.com (MacOS) Add FlutterGLCompositor with support for rendering multiple layers (flutter/engine#22782)
2020-12-03 gspencergoog@users.noreply.github.com Reland: "Fix race condition in key event handling on Android (#22658)" (flutter/engine#22834)
2020-12-03 skia-flutter-autoroll@skia.org Roll Fuchsia Linux SDK from W14Qninrb... to M_8svVndh... (flutter/engine#22842)
2020-12-02 garyq@google.com Split AOT Engine Runtime (flutter/engine#22624)
2020-12-02 magder@google.com Generate gen_snapshot_armv7 and gen_snapshot_arm64 (flutter/engine#22818)
2020-12-02 jason-simmons@users.noreply.github.com Generate Maven metadata files for engine artifacts (flutter/engine#22685)
2020-12-02 yjbanov@google.com Better handle image codec instantiation failure (flutter/engine#22809)
2020-12-02 skia-flutter-autoroll@skia.org Roll Skia from c504ecda03b8 to 9443d58af292 (16 revisions) (flutter/engine#22828)
2020-12-02 gspencergoog@users.noreply.github.com Revert "Fix race condition in key event handling on Android (#22658)" (flutter/engine#22823)
2020-12-02 skia-flutter-autoroll@skia.org Roll Dart SDK from 5acaa5f14b03 to cfaa7606cbf5 (2 revisions) (flutter/engine#22827)
2020-12-02 lrn@google.com Stop using the List constructor. (flutter/engine#22793)
2020-12-02 yjbanov@google.com Temporarily reduce e2e test matrix to stop flaky web engine builds (flutter/engine#22824)
2020-12-02 iska.kaushik@gmail.com Reland "Introduce a delegate class for gpu metal rendering (#22611)" (flutter/engine#22777)
2020-12-02 iska.kaushik@gmail.com [embedder] Compositor can specify that no backing stores be cached (flutter/engine#22780)
2020-12-02 jonahwilliams@google.com add trace kernel flag to allowlist (flutter/engine#22812)
2020-12-02 skia-flutter-autoroll@skia.org Roll Fuchsia Mac SDK from 7O11wjLVX... to Z_-ciOYM9... (flutter/engine#22820)
2020-12-02 skia-flutter-autoroll@skia.org Roll Fuchsia Linux SDK from Bnaeivv07... to W14Qninrb... (flutter/engine#22817)
2020-12-02 skia-flutter-autoroll@skia.org Roll Dart SDK from e9a03fd98faa to 5acaa5f14b03 (1 revision) (flutter/engine#22810)
2020-12-02 skia-flutter-autoroll@skia.org Roll Skia from 7b776b514933 to c504ecda03b8 (6 revisions) (flutter/engine#22808)
2020-12-02 47866232+chunhtai@users.noreply.github.com Add static text trait to plain semantics object with label in iOS (flutter/engine#22811)
2020-12-02 xster@google.com Add a golden scenario test for fallback font rendering on iOS take 3 (flutter/engine#22736)
2020-12-02 zanderso@users.noreply.github.com Revert "Roll buildroot and benchmark (#22804)" (flutter/engine#22816)
2020-12-01 skia-flutter-autoroll@skia.org Roll Fuchsia Mac SDK from qpkZl0s5J... to 7O11wjLVX... (flutter/engine#22805)
2020-12-01 dnfield@google.com Roll buildroot and benchmark (flutter/engine#22804)
2020-12-01 skia-flutter-autoroll@skia.org Roll Skia from a927771c9cce to 7b776b514933 (3 revisions) (flutter/engine#22803)
2020-12-01 skia-flutter-autoroll@skia.org Roll Dart SDK from 7a2a3968ef53 to e9a03fd98faa (5 revisions) (flutter/engine#22801)
2020-12-01 skia-flutter-autoroll@skia.org Roll Skia from 4c6f57a23e63 to a927771c9cce (10 revisions) (flutter/engine#22802)
2020-12-01 gspencergoog@users.noreply.github.com Fix PlatformDispatcher.locale to return something meaningful when there are no locales. (flutter/engine#22608)
2020-12-01 gspencergoog@users.noreply.github.com Fix race condition in key event handling on Android (flutter/engine#22658)
2020-12-01 dacoharkes@google.com Add file.dart to DEPS (flutter/engine#22794)
2020-12-01 garyq@google.com Add FlutterPlayStoreSplitApplication for simpler opt in to Split AOT (flutter/engine#22752)
2020-12-01 ferhat@gmail.com [web] Optimize Matrix4.identity (flutter/engine#22622)
2020-11-30 skia-flutter-autoroll@skia.org Roll Skia from 70fe17e12f38 to 4c6f57a23e63 (1 revision) (flutter/engine#22781)
...

### CODE REVIEW

**Comment by cbracken** [comment]
We expect this to fail one of the flutter/tests tests. Fix will land simulatenously in https://github.com/flutter/tests/pull/71

**Comment by cbracken** [comment]
Mac module_test_ios failure is an infra flake during git fetch. Re-run is https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20module_test_ios/1643/overview

**Comment by cbracken** [comment]
Linux web tests timed out. Re-run https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_tests/6816/overview

**Comment by engine-flutter-autoroll** [comment]
Commit queue failed; closing this roll.

**Comment by cbracken** [comment]
Mac module_test_ios failed with:
```
[module_test_ios] [STDOUT] stderr: Failing tests:
[module_test_ios] [STDOUT] stderr: 	FlutterUITests:
[module_test_ios] [STDOUT] stderr: 		-[FlutterUITests testDualCold]
[module_test_ios] [STDOUT] stderr: 		-[FlutterUITests testFullScreenColdPop]
[module_test_ios] [STDOUT] stderr: 		-[FlutterUITests testFullScreenWarm]
[module_test_ios] [STDOUT] stderr: 		-[FlutterUITests testHybridViewWarm]
```

**Comment by cbracken** [comment]
Seems like it's failing looking for text on screen (at least the two I spot-checked).

**Comment by cbracken** [comment]
Mac web test re-run: https://ci.chromium.org/p/flutter/builders/try/Mac%20web_tool_tests/75

**Comment by cbracken** [comment]
Landing at the same time as https://github.com/flutter/tests/pull/71

**Pull request merged**
