### PR TITLE
Roll engine to d786dc910408576712298bcc2c92be3619d961bc

### PR DESCRIPTION
**Pull request by johnmccutchan**
@jason-simmons

### CODE REVIEW

**Comment by jason-simmons** [comment]
LGTM

**Comment by chinmaygarde** [comment]
https://github.com/flutter/flutter/pull/5434/files includes this and a few more fixes.

**Comment by johnmccutchan** [comment]
@chinmaygarde I'll close this.

**Comment by chinmaygarde** [comment]
Thanks

**Pull request closed without merging**
