### PR TITLE
[Fonts] Sort material icons

### PR DESCRIPTION
**Pull request by guidezpl**
Apply logical sorting to make large diffs (e.g. f82986e) easier to read.

Sorted by Flutter id, e.g.

```
ac_unit
ac_unit_sharp
ac_unit_rounded
ac_unit_outlined 
access_alarm
access_alarm_sharp
...
```

part of go/effortless-flutter-font-updates

depends on https://github.com/flutter/flutter/pull/76532

### CODE REVIEW

**Comment by Hixie** [comment]
Looks like this PR ended up including more than just the sorting.

> part of go/effortless-flutter-font-updates

Is there a public version of this by any chance? (See https://github.com/flutter/flutter/wiki/Chat#design-documents)

**Comment by guidezpl** [comment]
I'm not sure what you mean. This PR depends on #76532. I considered it, but the audience really is internal.

**Comment by Hixie** [comment]
Oh I see. I'm going to mark this one "draft" for now since it can't be reviewed until #76532 lands.

**Review by rami-a — APPROVED** [review]
LGTM

**Review by JoseAlba — APPROVED** [review]
```
██╗      ██████╗ ████████╗███╗   ███╗
██║     ██╔════╝ ╚══██╔══╝████╗ ████║
██║     ██║  ███╗   ██║   ██╔████╔██║
██║     ██║   ██║   ██║   ██║╚██╔╝██║
███████╗╚██████╔╝   ██║   ██║ ╚═╝ ██║
╚══════╝ ╚═════╝    ╚═╝   ╚═╝     ╚═╝
```

**Pull request merged**
