### PR TITLE
Disable menu button when bottom sheet open

### LINKED ISSUE #8275: Tap menu dots in sorting list to make bottom sheet dance
Probably not what we expect to happen?

dancing_dots mov

### PR DESCRIPTION
**Pull request by abarth**
Otherwise tapping the menu button causes the bottom sheet to disappear and
reappear.

Fixes #8275

### CODE REVIEW

**Comment by abarth** [comment]
@HansMuller

**Comment by HansMuller** [comment]
LGTM

**Comment by Hixie** [comment]
Isn't this papering over a framework bug?

**Comment by abarth** [comment]
What's the intended behavior when you open a persistent bottom sheet when you already have one?  I'd expect the old one to animate out and the new one to animate in.  That's what eric describes as "dancing"

**Comment by Hixie** [comment]
Oh clicking the button just brings up the bottom sheet, rather than a popup menu? Never mind, I misunderstood.

**Comment by abarth** [comment]
Correct

**Pull request merged**
