### PR TITLE
RenderOpacity pushes layer even when opaque

### LINKED ISSUE #58425: RenderOpacity sometimes omits its layer during animations which breaks caching performance
The RenderOpacity object will not emit a layer when the opacity is 0 or 255. If that is the static opacity then it might make sense, but when it is the value during an animation, this causes the layer tree to drastically change configuration on each frame.

While this could potentially result in a hit if the tree needs to be constantly reconstructed, an even bigger hit happens because the change of identity of its own layer as it moves from a partial value to either 0 or 255 and back again means that the cached information at the engine level needs to be discarded and then re-rendered.

The layer should absolutely be left intact even for opacity values of 0 or 255 during an animation.

### PR DESCRIPTION
**Pull request by goderbauer**
## Description

See https://github.com/flutter/flutter/issues/58425#issuecomment-662125500.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/58425

## Tests

I added the following tests:

* Updated existing test

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 11 untriaged digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/61994

**Review by Piinks — COMMENTED** [review]
There is similar logic in RenderSliverOpacity, should the same change apply there?

**Comment by goderbauer** [comment]
@Piinks good catch. I found some other places in the framework with similar problems as well. Will update those, too.

**Comment by flar** [comment]
Where and how should we document this interaction?  On Opacity and SliverOpacity? On BackdropFilter? On all 3?

Is it worth an article? Even if there is an article, we might want to mention the interaction in the class doc comments.

**Comment by flar** [comment]
I'm basically good with this pending my question about whether we should add a doc comment here about layer interactions.

**Review by Piinks — APPROVED** [review]
This LGTM modulo @flar's documentation recommendation. :)

**Comment by flar** [comment]
I think this is ready to go in. My "recommendations" related to documentation were mostly questions, but I can submit a separate issue about those if and when I can come up with a proper way to educate developers without confusing them.

**Review by flar — APPROVED** [review]
LGTM

**Comment by flar** [comment]
Ugh, I just noticed this issue that had a comment that mentioned that the Opacity widget specifically describes the behavior of 1.0 and 0.0. We should update that paragraph in the Opacity widget to coincide with this change in the implementation:

https://github.com/flutter/flutter/issues/53277#issuecomment-603997173

See: https://github.com/flutter/flutter/blob/48b9c3d39b00a4b8abba79c4ad1e736bfe447581/packages/flutter/lib/src/widgets/basic.dart#L135

**Review by flar — CHANGES_REQUESTED** [review]
Please update this paragraph to match the new behavior...

https://github.com/flutter/flutter/blob/48b9c3d39b00a4b8abba79c4ad1e736bfe447581/packages/flutter/lib/src/widgets/basic.dart#L135

**Comment by goderbauer** [comment]
I've been distracted from this PR by other issues. I'll get back to it shortly and will update the documentation.

**Comment by goderbauer** [comment]
Added a comment for discussion to https://github.com/flutter/flutter/issues/58425#issuecomment-675086179.

Depending on the outcome of that discussion, this PR also needs to be updated to include RenderAnimatedOpacityMixin.

**Comment by Piinks** [comment]
Was there a consensus reached to move forward on this @goderbauer?

**Comment by flar** [comment]
This appears to generate some Scuba failures in rolling to Google3: https://critique-ng.corp.google.com/cl/328370378

The failures were on font rendering in the header of the app. I'm guessing this might be because they have an Opacity on that piece of text and now it is being snapped differently to the pixel grid. My eyes couldn't detect the differences they were claiming. My recommendation is that these are benign and should be accepted...?

**Comment by flar** [comment]
Note that omitting the layer when alpha is 255 creates a rendering inconsistency as mentioned in https://github.com/flutter/flutter/issues/93378#issuecomment-970531336

**Pull request closed without merging**
