### PR TITLE
Switch from .packages to package_config

### PR DESCRIPTION
**Pull request by mit-mit**
Prepare for Dart breaking change https://github.com/dart-lang/sdk/issues/48272

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

**Comment by mit-mit** [comment]
I'm hopping on a flight in 30 mins. If this causes issues, can you please revert on my behalf?

**Comment by christopherfujino** [comment]
> I'm hopping on a flight in 30 mins. If this causes issues, can you please revert on my behalf?

will do!

**Pull request merged**
