### PR TITLE
Added spacer.dart to flutter>lib>src>widgets

### PR DESCRIPTION
**Pull request by ScottS2017**
Added a spacer widget that has been well received in Gitter. It is rediculously simple, fast and intuitive. I was encouraged to push it by several people.

### CODE REVIEW

**Comment by ScottS2017** [comment]
I'm not sure if this is ready to go or not. I made the request and apparently needed to sign the license agreement, which I did. I'm a little confused if there is another problem or not. Please let me know if I need to do anything further.

**Review by ScottS2017 — COMMENTED** [review]
Fixed circular dependency

**Comment by Hixie** [comment]
this seems reasonable! good idea! thanks!

A few suggestions:

 * we will need a test
 * the documentation should be clear that this is only for use inside row/column
 * docs for row/column should point to this
 * use a SizedBox as the child rather than a Container (it's the same thing in the end)
 * constructor first in the class please
 * add documentation to each of the members (e.g. constructor, properties), explaining how they work in the context of this widget

**Comment by Hixie** [comment]
@ScottS2017 Will you have the opportunity to make the suggested changes, or would you rather we took over the patch?

**Comment by gspencergoog** [comment]
This PR is replaced by https://github.com/flutter/flutter/pull/16642

**Comment by ScottS2017** [comment]
After discussing this with Slightfoot and researching a few things, I realized that this widget doesn't exist for a reason. Using it is actually inefficient compared to the proper combination of padding, margin, alignment and expandeds. I'm afraid that promoting it would only lead to bad habits in those who used it.

**Comment by slightfoot** [comment]
hey @ScottS2017 post a gist of the code.

**Comment by slightfoot** [comment]
@Hixie found it.
```
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';


class Spacer extends StatelessWidget {
	final int flex;

	const Spacer({this.flex: 1});

	@override
	Widget build(BuildContext context) {
		return new Flexible(flex: flex, child: new Blank());
	}
}

class Blank extends LeafRenderObjectWidget {
	static final expandConstraints = const BoxConstraints.expand();

	const Blank({ Key key }) : super(key: key);

	@override
	RenderObject createRenderObject(BuildContext context) {
		return new RenderLimitedBox(
			child: new RenderConstrainedBox(additionalConstraints: expandConstraints),
			maxWidth: 0.0,
			maxHeight: 0.0,
		);
	}
}
```

We noted that `SizedBox` didn't work as a nice "Blanker" and `Container` was too heavy. So we came up with `Blank`.

**Comment by ScottS2017** [comment]
okay, so yes it can be used with blank lol

But as I was just telling Slightfoot in gitter, I thought we had decided that there was no spacer because there were already better ways to acheive the same effect... but I certainly wouldn't mind it's being in the SDK for days when I'm feeling lazy!

What do you guys think? Push it with the blank, which is a more efficient way to do it than container?

**Comment by gspencergoog** [comment]
OK, I've updated my PR (https://github.com/flutter/flutter/pull/16642) to reflect the above discussion.

**Pull request closed without merging**
