### PR TITLE
[cupertino_icons] add car, bus, train, paw, controller, and flask icons.

### PR DESCRIPTION
**Pull request by jeffscaturro-aka**
**Issue:** Not all icons displayed in [Cupertino Icon's map.png](https://raw.githubusercontent.com/flutter/cupertino_icons/master/map.png) are available when calling `CupertinoIcons.{x}`.

**What was changed:** While not all missing icons were added in this PR, the following icons were: `bus`, `car`, `car_detailed`, `train_style_one`, `train_style_two`, `paw`, `paw_solid`, `game_controller`, `game_controller_solid`, `lab_flask`, and `lab_flask_solid`.

**Testing:** In order to test these new icons I threw them in a `Column` real quick: 
```
Column(
    mainAxisAlignment: MainAxisAlignment.spaceEvenly,
    children: <Widget>[
        Icon(CupertinoIcons.bus),
        Icon(CupertinoIcons.car),
        Icon(CupertinoIcons.car_detailed),
        Icon(CupertinoIcons.train_style_one),
        Icon(CupertinoIcons.train_style_two),
        Icon(CupertinoIcons.paw),
        Icon(CupertinoIcons.paw_solid),
        Icon(CupertinoIcons.game_controller),
        Icon(CupertinoIcons.game_controller_solid),
        Icon(CupertinoIcons.lab_flask),
        Icon(CupertinoIcons.lab_flask_solid)
    ]),
```

**Testing results:** which resulted in the expected behavior of these icons displaying appropriately:

new icons

### CODE REVIEW

**Comment by JeffScaturro** [comment]
@googlebot I signed it!

**Comment by JeffScaturro** [comment]
Force pushed because I wasn’t sure if Flutter enjoys a lot of master merge commits, just reset to master and applied changes on top. White space after comments has been addressed. Should be ready for final review.

**Comment by jonahwilliams** [comment]
> Force pushed because I wasn’t sure if Flutter enjoys a lot of master merge commits,

FYI, we always squash and merge so that the number of commits in a PR doesn't matter.

**Comment by JeffScaturro** [comment]
Nice. I'll keep that in mind for next time! Thanks for the info.

**Pull request merged**
