### PR TITLE
The dependency script wasn't catching quite all our transitive dependencies

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
cc @aam for review - this should fix the underlying issue that was breaking the build just now

fyi @yjbanov since I think you last touched this particular part of the code

**Review by aam — APPROVED** [review]

**Comment by aam** [comment]
Do you still want me to submit https://github.com/flutter/flutter/pull/13952 ?

**Comment by Hixie** [comment]
If it's ready, you bet. I merged that one into this one just so that I wouldn't have to run it again after that one landed.

**Comment by Hixie** [comment]
Thanks for the review.

**Review by yjbanov — APPROVED** [review]

**Comment by yjbanov** [comment]
lgtm

**Pull request merged**
