### PR TITLE
let ListWheelViewport composite again

### LINKED ISSUE #14224: ListWheelViewport should set needsCompositing
In the example https://github.com/xster/flutter-test/blob/master/t71_text_transform_rendering_2/lib/main.dart

TransformLayers without text works. canvas.transform works. But TransformLayers with text no longer works.

### PR DESCRIPTION
**Pull request by xster**
## Description

Last step in #14224 now that the upstream issue is fixed

## Related Issues

Fixes #14224

## Tests

This is only really testable via golden which already exists for the list wheel viewport. 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by xster** [comment]
@jason-simmons I tried turning compositing back on for this widget re:#14224 but after I did so, all the pixels in the golden kinda shifted a little bit (best visible via onion skin diffing:

https://github.com/flutter/goldens/compare/master...xster:listwheel-composite?expand=1

Is this expected?

**Comment by jason-simmons** [comment]
@liyuqian

**Review by yjbanov — APPROVED** [review]
LGTM if we think that pixel shifting is expected and acceptable.

**Comment by liyuqian** [comment]
The fix here LGTM. In general, `RenderObject`s should always respect its `needsCompositing` bit, which will be true as long as one of its descendants `needsCompositing`.

**Comment by liyuqian** [comment]
@xster the small shift is expected: without `needsCompositing`, the `clipRect` is recorded in `SkPicture`, whose top-left corner will be snapped to integer pixel coordinates. With `needsCompositing`, such snapping doesn't happen.

**Review by liyuqian — APPROVED** [review]

**Comment by xster** [comment]
Cool, thanks for the info

**Comment by gspencergoog** [comment]
Hey @xster, are you still working on this PR?  If not, can you close it to get it off the PR backlog?

**Comment by xster** [comment]
Oh @LongCatIsLooong did it in https://github.com/flutter/flutter/pull/47837. Win!

**Pull request closed without merging**
