### PR TITLE
Reland "perf test for measuring scroll smoothness"

### PR DESCRIPTION
**Pull request by liyuqian**
This relands https://github.com/flutter/flutter/pull/61998

This reverts commit 28de49e358aa87aa7409f7d6f305985fdad7e13d.

No extra change seems to be needed to avoid the test failures in the old reland, probably thanks to https://github.com/flutter/flutter/pull/65124. I tested with iPhone 6s both locally and remotely on flutter-devicelab-mac-1.

### CODE REVIEW

**Comment by liyuqian** [comment]
CC @CareF as somehow I can't put you as the reviewer...

**Comment by CareF** [comment]
@liyuqian Thanks. 
I believe that's because I've been removed from the hacker team :(

**Comment by liyuqian** [comment]
@CareF that must be an accident, and we apologize for that. Ray just added you back (sent you an invitation). Can you please check if it's received?

**Review by CareF — APPROVED** [review]
LGTM
@liyuqian I received the invitation! Thanks.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
