### PR TITLE
When Impeller is enabled for flutter tester choose correct shader target.

### PR DESCRIPTION
**Pull request by jonahwilliams**
When compiling shaders for flutter tester, include Vulkan shaders when targeting Impeller.

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
@christopherfujino I had to make a few more updates to get it fully working.

**Comment by christopherfujino** [comment]
customer_testing & flutter_plugins failures exist at HEAD and are being worked on, pls disregard

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
