### PR TITLE
Update default page transition to Android 10 transition

### LINKED ISSUE #43277: Make Android 10 Activity Animation the default animation
After https://github.com/flutter/flutter/pull/41935 lands, we should default material page transitions to the newer animation.

### PR DESCRIPTION
**Pull request by shihaohong**
## Description

As new OEM behaviors are created, we should be [staying up to date](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#widget-libraries-follow-the-latest-oem-behavior). This PR introduces a breaking change that sets the default MaterialPageRoute transition to the Android 10 transition.

Android 10 activity transition animation

To keep previous behavior, one would need to modify the PageTransitionsTheme in their MaterialApp theme as follows:
```
      theme: ThemeData(
        pageTransitionsTheme: PageTransitionsTheme(
          builders: {
            TargetPlatform.android: FadeUpwardsPageTransitionsBuilder(),
          },
        ),
        // rest of theme
      ),
```

## Related Issues

Fixes https://github.com/flutter/flutter/issues/43277

## Tests

I added the following tests:

- Updated previous tests to check if the default MaterialPageRoute uses the ZoomPageTransitionsBuilder

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by shihaohong** [comment]
The change is breaking some tests, such as: 
1. "Destination hero scrolls mid-flight" in `heroes.dart`, which scrolls mid-flight. since the new transition involves a scaling transition, I assume that this drag ends up scrolling/dragging the hero more or less than expected.
2. "selection handles are rendered and not faded away", which takes into account that a single FadeTransition exists in a MaterialApp, which existed because of the previous transition. 

I will need to spend some time fixing up these issues and making sure we're not breaking more than meets the eye before proceeding with this change.

**Comment by Zazo032** [comment]
Also fixes https://github.com/flutter/flutter/issues/34675

**Review by darielopper — APPROVED** [review]

**Comment by shihaohong** [comment]
I'm closing this for now since I have not had the bandwidth to make this happen. I'll re-open this when I have the opportunity to revisit this change.

**Comment by Zazo032** [comment]
Hi @shihaohong, do you know if the tests this was breaking are still an issue? (the PR is closed so there aren't any Cirrus logs)

**Comment by shihaohong** [comment]
@Zazo032 I made an effort to fix the tests within the framework (https://github.com/flutter/flutter/pull/51150). However, this might still need to go through the standard breaking change process (checking to see if it breaks customer tests, internal tests, and sending an email out to make sure there isn't any issues we're missing out on).

**Comment by shihaohong** [comment]
Closing in favor of https://github.com/flutter/flutter/pull/51538 since the presubmits seem to keep failing. It's likely due to the PR being this old

**Pull request closed without merging**
