### PR TITLE
Do not fade out text for pinned & floating AppBar

### LINKED ISSUE #25000: Title of pinned & floating AppBar disappears on scrolling
The title fades out when the following app bar is scrolled (the app bar itself stays on screen). The title should stay visible as well.

```dart

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: Colors.green,
        child: CustomScrollView(
          slivers: <Widget>[
            SliverAppBar(
              pinned: true,
              floating: true,
              title: Text("hello"),
              leading: new Icon(Icons.add),
                expandedHeight: 120.0,
            ),
            SliverList(
              delegate: SliverChildListDelegate(List.generate(20, (int i) {
                return Container(
                  child: Text('Tile $i'),
                  height: 100.0,
                );
              })),
            )
          ],
        ),
      ),
    );
  }
}

```

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/25000.

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by TheJulianJES** [comment]
Mhm, I guess it's this pr that has kinda "broken" a NestedScrollView with a SliverAppBar and a "bottom".
Now this looks weird when the AppBar is also pinned and floating:

The pictures are bad, the one thing of the title is "censored".
Maybe you can still kinda see whats going on.

I'll create an issue in the next couple of days though if this isn't understandable (or doesn't belog here) ^^

Previously (master, 1.0 stable): (title faded out correctly, then overlapped by bottom)
bildschirmfoto 2019-01-03 um 01 59 19

Now (dev): (title doesn't fade out, get's overlapped by bottom)
image

**Comment by goderbauer** [comment]
Please do file a new issue with some example code that shows the incorrect behavior and with a description of what behavior you expected. Feel free to cc me.

**Comment by TheJulianJES** [comment]
Okay, will do. Thanks for the fast response!

**Pull request merged**
