### PR TITLE
CP: Wait for non-empty layout in platform view placeholder

### PR DESCRIPTION
**Pull request by stuartmorgan-g**
Cherry-picks https://github.com/flutter/flutter/pull/112402 to stable.

### CODE REVIEW

**Review by justinmc — APPROVED** [review]
LGTM :+1: .  Seems low-risk and worthy of cherry picking from my understanding.

@stuartmorgan FYI this needs a merge.  I think the test failure will also be fixed by the merge.

**Comment by godofredoc** [comment]
> tance, the customer test is trying to run



> Looks like the branch is not in a good state in general. For instance, the customer test is trying to run analysis of a package that's using an option that doesn't exist in the analyzer on stable, it looks like.

That is correct, customer_tests have never worked correctly for release branches.

**Comment by stuartmorgan** [comment]
What's the path for landing this if tests are known not to pass?

**Comment by godofredoc** [comment]
> What's the path for landing this if tests are known not to pass?
The release engineer will land it manually.

**Comment by XilaiZhang** [comment]
umm I checked the target history and it looks like linux plugins has always been failing, I went ahead and squash and merged

**Pull request merged**
