### PR TITLE
Removed hardcoded .app extension to add support for frameworks

### PR DESCRIPTION
**Pull request by vitorhugomagalhaes**
## Description

The current `xcode_backend` script assumes that Flutter will be embedded in an app target. This change uses  WRAPPER_EXTENSION setting to allow embedding Flutter into any target like other frameworks too. 

I'm also open to provide more documentation on how to do it. This is specially important for teams that would like to create native SDKs on top of Flutter.

## Related Issues

None that I'm aware of.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by vitorhugomagalhaes** [comment]
@goderbauer I'm not very familiar with the PR approval pipeline. Some tests are failing but they don't seem to be related with my changes. Could you please clarify what would be required on my side ? thanks

**Comment by goderbauer** [comment]
I restarted the bots to see if those failures were flakes.

**Comment by jonahwilliams** [comment]
While this is definitely something we should support, I don't think we can land this as is without tests. Unfortunately that will be very difficult to do as long as much of this logic lives in that shell script (which is why, longer term, we're refactoring this to live in dart).

We do have a suite of integration tests (see dev/devicelab and dev/integration_tests). To test this I would create an app that uses  a different extension and test that it can be built with this change

**Comment by vitorhugomagalhaes** [comment]
Before submitting the PR I took a look at the tests written for the script
and they don’t actually perform a full coverage test. I have tested this
change with app and framework as suggested and they both compile just fine.
If you believe that I should create any additional test could you provide a
bit more information on what integration tests should be written on my side
? Thanks

**Comment by jonahwilliams** [comment]
The current testing situation being far from ideal doesn't justify further regressions in test coverage. While your change may work for now, the difficult part is ensuring that it continues working in the future, which is what the tests will help us do.

A test that would be useful includes successfully building an application that uses a different extension.

**Comment by vitorhugomagalhaes** [comment]
You’re totally right. I didn’t want to justify the lack of tests because my
first goal was to add them just didn’t know where. I’ll add the tests and
then get back to see if they are inline with your expectations. Thanks

**Comment by vitorhugomagalhaes** [comment]
@jonahwilliams Inside the dev/integration_tests there is one folder named ios_add2app which basically is a sample app that tests the app2app integration of Flutter into a native app using different scenarios. If I did understand correctly, your proposal is to create a separated folder named ios_add2other where I'd change the wrapper extension to something different than app and see if it builds successfully ?

I was considering a different scenario where basically I'd create a folder names ios_add2framework where I'd create a sample app and framework targets. I'd then change the podfile to integrate Flutter into the framework target which is then used as a dependency in the app target. I believe this would make sure that a different WRAPPER_EXTENSION value is correctly built and it also helps other people that would want to implement this scenario since the FlutterEngine initialisation requires a custom FlutterDartProject to get the framework NSBundle. 

Can I proceed like this ?

Thanks,

**Comment by jonahwilliams** [comment]
I've looked into this some more and I'm not certain this is the best way we could support it. @vitorhugomagalhaes to unblock yourself, you could replace your script phase with the custom xcode_backend.sh, but I would really appreciate starting with a detailed issue so we can discuss different approaches first.

**Comment by vitor-gyant** [comment]
@jonahwilliams Yeah I do understand. On my side I was able to move forward without changing the xcode_backend.sh script. Bottom line, my scenario is that I want to distribute a native iOS framework that uses Flutter. The xcode_backend.sh script performs the build and embed step on the app target which is correct. We could allow the build step to be added to the framework target but the embed step does not make sense because apple does not support universal frameworks in iOS so in the end of the day we do have to embed Flutter.framework and App.framework at the app level. 

Because my flutter code also depends on several plugins I was also being forced to compile them and send them together with my framework. I was able to workaround this by compiling the plugins as static frameworks by removing `use_frameworks` from the Podfile.

My final configuration was a workspace with one app target that has a target dependency on my framework target. the build and embed commands were added to the app target just like app2app describes. 

I've created a shell script that calls xcodebuild on the app target for the simulator in Debug and again for the devices in Release. In the end it creates a fat framework with all the architectures together. 

The drawback of this approach is that I've to include the JIT assets like kernel_blob, etc inside the flutter_assets of the App.framework. The root cause for this is that Flutter is not compiled for x86_64 and i386 in Release. The other option would be to not support the Simulator arch which would means 3rd party developers would be forced to integrate the SDK using only the devices. I've decided that the assets overhead would make more sense. 

I've started some discussions regarding the most important topics during this process which are:

- Allow Flutter to be compiled in Release for x86_64 and i386.
- Remove the need to disable bitcode.

Moreover, I'd like to have Flutter.framework and App.framework compiled as static frameworks too but that would be the cherry on top :)

Let me know how we should proceed to create a more detailed issue and which blocks would make sense to discuss there.

Thanks for your help!

**Comment by jonahwilliams** [comment]
I think that while we definitely want to support building frameworks, but this isn't the way we're going to go about it. The overall feature request is captured in https://github.com/flutter/flutter/issues/36968 .

**Pull request closed without merging**
