### PR TITLE
[flutter roll] Revert "Add ability for `ModalRoutes` to ignore pointers during trans…

### PR DESCRIPTION
**Pull request by XilaiZhang**
…itions and do so on `Cupertino` routes (#95757)"

This reverts commit 4c0b0be2da5d1ee80c3d713e68ddd88d2cf2e72d.

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
Please briefly add some context why this was reverted for people who want to look at this again in the future and cc the original author for their information that it got reverted.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by willlockwood** [comment]
@XilaiZhang what was the issue here? Anything I can help with?

**Comment by XilaiZhang** [comment]
yes sir i copied the error msg to https://github.com/flutter/flutter/pull/95757#issuecomment-1137492558. I am not sure if there is an open source version of the test you can reference

**Pull request merged**
