### PR TITLE
Fix dart pub cache clean command on pub.dart

### LINKED ISSUE #128663: Flutter Doctor advises invalid `dart pub cache clear` command on first run
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Perform fresh Flutter SDK installation (issue only happens upon first run)
2. Run `flutter doctor`

### Expected results

When pre-existing pub cache is found, `flutter` tool should advise to run `dart pub cache clean`

### Actual results

Running `dart pub cache clear` is advised instead (`clear` instead of `clean`).

### Code sample

<details><summary>Code sample</summary>
Not applicable
</details>

### Screenshots or Video

_No response_

### Logs

<details><summary>Logs</summary>

```console
> flutter --verbose doctor
Found an existing Pub cache at C:\Users\<username>\AppData\Local\Pub\Cache.
It can be repaired by running `dart pub cache repair`.
It can be reset by running `dart pub cache clear`.
[✓] Flutter (Channel stable, 3.10.4, on Microsoft Windows [Version 10.0.19045.2965], locale cs-CZ)
    • Flutter version 3.10.4 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (6 days ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc4)
    • Android SDK at C:\Users\<username>\AppData\Local\Android\sdk
    • Platform android-33, build-tools 34.0.0-rc4
    • Java binary at: C:\Users\<username>\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.10121639\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.23)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.33214.272
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.2)
    • Android Studio at C:\Users\<username>\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\222.4459.24.2221.10121639
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code, 64-bit edition (version 1.79.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2965]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 114.0.5735.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.43

[✓] Network resources
    • All expected network resources are available.

• No issues found!
> dart pub cache clear
Could not find a subcommand named "clear" for "dart pub cache".

Did you mean one of these?
  clean


Usage: dart pub cache [arguments...]
-h, --help    Print this usage information.

Available subcommands:
  add      Install a package.
  clean    Clears the global PUB_CACHE.
  repair   Reinstall cached packages.

Run "dart help" to see global options.
See https://dart.dev/tools/pub/cmd/pub-cache for detailed documentation.
>
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>
See above
</details>

### PR DESCRIPTION
**Pull request by deryrahman**
Command instruction for clearing dart pub cache is somewhat wrong. Instead of `clear`, `clean` is the correct one. Ref: https://dart.dev/tools/pub/cmd/pub-cache

Fixes https://github.com/flutter/flutter/issues/128663

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

(Edited by @andrewkolos. Changed "related to" issue to "fixes" to link this PR to the issue).

### CODE REVIEW

**Comment by Hixie** [comment]
This will need a test; looks like this is similar to https://github.com/flutter/flutter/pull/128037 if you would like to pool resources with other contributors!

**Comment by deryrahman** [comment]
hi @Hixie , I've added the test for that. Feel free to merge and we could mention this PR as part of the other PRs which contribute to fix similar issue

**Review by christopherfujino — APPROVED** [review]
LGTM, and thanks for writing a test :)

**Review by andrewkolos — APPROVED** [review]
LGTM

**Pull request merged**
