### PR TITLE
Update outdated platform directories in examples

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

The first of three or four changes to update the platform directories of the packages in the Flutter repo that have out date platform code.

This batch includes updating the flutter_view example, updating the sanity check numbers in `analyze.dart`, and adding some missing `Podfiles` in the examples. I also eliminated some trailing whitespace in the templates for Android.

## Tests
 - This is just updating the existing embeddings, so no tests needed.

## Related Issues
 - https://github.com/flutter/flutter/issues/91325

### CODE REVIEW

**Review by blasten — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Can we test this by checking for the warning you get when it's out of date, maybe? Would be good to notice when the examples get out of date.

**Comment by gspencergoog** [comment]
How about if I check for the deprecation message any time we `flutter run` something in the repo?  It would have to exempt any tests that were specifically testing for the depreciation (there is one that I know of), but would then apply to all of the embeddings, not just in examples.

**Comment by Hixie** [comment]
test-exempt: we discussed this in Discord. Conclusion was that testing this directly isn't worth it but that in the future we should consider adding a `--fatal-warnings` or equivalent to `flutter` and enable that option widely on our CI.

**Pull request merged**
