### PR TITLE
Transparent icons gallery

### LINKED ISSUE #5376: Update Gallery launcher icons to use transparent backgrounds on Android
Looks like the majority of Android launcher icons use a transparent background. The Gallery launcher icon for Android is a white background.

I have new [transparent-background launcher icons](https://github.com/flutter/identity-assets/tree/master/assets/Flutter-Launcher-Icons/transparent-backgrounds) that we can use for the Gallery on Android.

### PR DESCRIPTION
**Pull request by sethladd**
Now with more transparency!

Closes https://github.com/flutter/flutter/issues/5376

### CODE REVIEW

**Comment by sethladd** [comment]
cc @HansMuller

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
...but shouldn't we replace the defaults, wherever they live? Or are these just for the gallery?

**Comment by sethladd** [comment]
Yeah, I'll replace the default in the next PR :)

**Pull request merged**
