### PR TITLE
More gracefully handle license loading failures

### PR DESCRIPTION
**Pull request by Hixie**
This prevents an exception from being thrown (and ErrorWidget shown) when something goes wrong loading the licenses.

I tried to add a test:

```dart
// Copyright 2014 The Flutter Authors. All rights reserved.                                                                                       
// Use of this source code is governed by a BSD-style license that can be                                                                         
// found in the LICENSE file.                                                                                                                     

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('AboutListTile control test', (WidgetTester tester) async {
    LicenseRegistry.addLicense(() => Stream<LicenseEntry>.error(Exception('Injected failure')));
    await tester.pumpWidget(const MaterialApp(home: Material(child: AboutListTile())));
    await tester.tap(find.byType(ListTile));
    await tester.pump();
    await tester.pump(const Duration(seconds: 2));
    await tester.tap(find.text('VIEW LICENSES'));
    await tester.pump();
    await tester.pump(const Duration(seconds: 2));
    await tester.pumpAndSettle();
    expect(find.text('Injected failure'), findsOneWidget);
  });
}
```

...but it hung (pumpAndSettle spins forever, until a timeout) and I couldn't figure out why before my timebox ran out. It seems to only happen in `flutter test` mode (when running the test in `flutter run`, it passes), and it only seems to happen when the addLicense stream has an error stream (the FutureBuilder never gets the onError call).

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/87841

**Comment by skia-gold** [comment]
Gold has detected about 61 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/87841

**Comment by gspencergoog** [comment]
Thanks, it should definitely do this.  It would be nice to have a test, though.  I wonder what's wrong in the testing framework? I assume we have similar tests elsewhere already, so maybe seeing what's different between this one and those would be illuminating.

**Comment by fzyzcjy** [comment]
👀

**Comment by gspencergoog** [comment]
I took a quick look at the test, and it seems that a `_MaterialState` still has an active ticker once the exception is thrown.  I suspect that throwing the exception from the stream jumps over some code that should deactivate the ticker.

**Comment by Hixie** [comment]
But we don't throw an exception, we just report an error and then return a normal widget...

**Comment by gspencergoog** [comment]
Sorry, this kind of slipped through the cracks.

Doesn't `assert` throw an `AssertionError` exception?

In any case, I'm not opposed to adding this without a test if it's not testable, but it would be nice to figure out why.

**Comment by Hixie** [comment]
> Doesn't `assert` throw an `AssertionError` exception?

In this case, the assert doesn't actually fail, because the closure returns true.

> In any case, I'm not opposed to adding this without a test if it's not testable, but it would be nice to figure out why.

Yeah...

**Comment by gspencergoog** [comment]
> In this case, the assert doesn't actually fail, because the closure returns true.

Oh, duh.

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
LGTM, once the tests pass.

**Comment by Hixie** [comment]
alright i reopened my time box and figured out that the problem was that the stream wasn't completing because it's an asynchronous operation and in `flutter test` of course we run in a FakeAsync zone. So I tweaked the test to pump the stream via `runAsync` first. It's an ugly hack since the classes involved are all private but it works!

**Pull request merged**
