### PR TITLE
Add `IndicatorShape` to `NavigationRailTheme` and fix indicator ripple.

### LINKED ISSUE #115852: M3 `NavigationRail` use wrong ripple
https://github.com/flutter/flutter/issues/114618 fixed ripple for `NavigationBar`

Do the same indicator in M3 `NavigationRail`.

image

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/115852

### Description
1. Added `IndicatorShape` to the `NavigationRailTheme` (similar to `NavigationBarTheme`).
2. Fix the indicator ripple (fix the same issue for `NavigationBar` in https://github.com/flutter/flutter/pull/115499)

### Indicator shape can now be customized from `NavigationRailTheme`.

https://user-images.githubusercontent.com/48603081/204320058-696dc889-fd2b-49b6-82f7-0e41f5821852.mov

### Fixed default indicator ripple.

https://user-images.githubusercontent.com/48603081/204319415-bf908286-d3d4-4eaa-b723-6c5323c0e5ae.mov

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by HansMuller — COMMENTED** [review]
This LGTM however, wouldn't make sense to include a NavigationRail indicatorShape property?

**Comment by TahaTesser** [comment]
> This LGTM however, wouldn't make sense to include a NavigationRail indicatorShape property?

Thanks for taking a look. `NavigationBar` doesn't have ab indicatorShape property, for the same reason I didn't add to `NavigationRail` 

https://github.com/flutter/flutter/blob/224fae50638a4920896b74d55d74d707b8382774/packages/flutter/lib/src/material/navigation_bar.dart#L338

if I were to add it to `NavigationRail`, we should be consistent and add it to `NavigatiomBar` as well. Do you agree?

**Comment by HansMuller** [comment]
> if I were to add it to `NavigationRail`, we should be consistent and add it to `NavigatiomBar` as well. Do you agree?

Yes. I think we can defer that to a separate PR.

**Review by HansMuller — APPROVED** [review]
LGTM

**Pull request merged**
