### PR TITLE
Use `dart pub` instead of `pub` to invoke pub from tools

### LINKED ISSUE #88507: Use `dart pub` instead of `pub` from flutter_tools
The top-level `pub` command will be deprecated.

Part of https://github.com/dart-lang/pub/issues/2736 .

### PR DESCRIPTION
**Pull request by sigurdm**
The top-level `pub` command is being deprecated https://github.com/dart-lang/pub/issues/2736. Start using `dart pub` instead.

Fixes: https://github.com/flutter/flutter/issues/88507

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM (if LG to @christopherfujino )

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by sigurdm** [comment]
I modified the command, so the `dart pub` subcommand will not send its own analytics.

PTAL

**Comment by christopherfujino** [comment]
> I modified the command, so the `dart pub` subcommand will not send its own analytics.
> 
> PTAL

Change LGTM. looks like you'll need to update test expectations again.

**Review by christopherfujino — APPROVED** [review]
lgtm

**Comment by sigurdm** [comment]
Do I have to wait for the google testing to complete? (will it ever complete?)

**Comment by christopherfujino** [comment]
@sigurdm fyi this was reverted in https://github.com/flutter/flutter/pull/88792 for post-submit failures

**Pull request merged**
