### PR TITLE
Fix todo format

### PR DESCRIPTION
**Pull request by pq**
An upcoming fix to the linter will now flag this TODO as being ill-formatted.  We'll need to land this fix before our next linter roll into the Dart SDK.

Roll try: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8803008781015527105/+/u/analyze_flutter_flutter/stdout

See: https://github.com/dart-lang/sdk/issues/58832.

/fyi @AlexV525 

/cc @goderbauer 

(Since this is just a doc change, it should be test exempt.)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by AlexV525** [comment]
Thanks @pq, I didn't see invalid TODOs when I applied the local linter previously, I guess something might be misconfigured. 😢

**Comment by pq** [comment]
No worries @AlexV525!  I appreciate the effort.  And this was an easy fix. 👍

**Review by AlexV525 — APPROVED** [review]
LGTM

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
