### PR TITLE
Requiring data preserves the stackTrace

### LINKED ISSUE #93591: AsyncSnapshot.requireData should preserve the error stacktrace.
The fact that `AsyncSnapshot.requireData` throws with a different stack trace than `AsyncSnapshot.stackTrace` makes debugging tedious, because it is not obvious where the error is coming from.

Now that `Error.throwWithStackTrace` was implemented, it would be helpful to update `requireData` to use it instead of simply doing `throw error`.

### PR DESCRIPTION
**Pull request by rrousselGit**
Now that we have the ability to rethrow an error with a specific stackTrace, this updates `AsyncSnasphot.requireData` to use it.

fixes #93591

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by justinmc — APPROVED** [review]
LGTM 👍

**Comment by goderbauer** [comment]
`throwWithStackTrace` has not rolled into google yet, that's why the check is failing. Let's retry this after it has rolled in.

**Comment by goderbauer** [comment]
I've retriggered "google testing".

**Comment by justinmc** [comment]
Looks like Google testing passed, so I've re-added the "waiting for tree to go green" label.

**Pull request merged**
