### PR TITLE
Move commands into their own shard

### PR DESCRIPTION
**Pull request by Hixie**
Extracted from my cirrus cleanup patch to continue to isolate the weird failure that that introduces.

### CODE REVIEW

**Comment by Hixie** [comment]
The docs analysis failure is fixed by https://github.com/flutter/flutter/pull/39160.

The integration failure... o_O

**Comment by Hixie** [comment]
Code coverage redness is expected (this takes out the command tests from the coverage).

**Comment by jonahwilliams** [comment]
I realize that the code coverage is just a measure and not a goal in itself ... but -7.71% is still a bit disheartening. Having said that, I don't think all of the tests in commands/ are appropriate for a separate shard. The following tests don't use sub-processes or the real filesystem and are fairly quick:

- version_test.dart
- upgrade_test.dart
- shell_completion_test.dart
- run_test.dart
- precache_test.dart
- install_test.dart
- drive_test.dart
- doctor_test.dart
- devices_test.dart
- create_usage_test.dart
- config_test.dart
- clean_test.dart
- build_fuchsia/linux/macos/web/windows_test.dart
- assemble_test.dart

This is probably why the coverage drop is so dramatic. I think these should still be run in the general shard

**Comment by Hixie** [comment]
How would you feel about my splitting the `commands.shard` directory into two subdirectories, `hermetic` and `permeable`, and running coverage only for the hermetic ones?

**Comment by Hixie** [comment]
Ok, I tried that. Let's see what code coverage looks like.

**Review by jonahwilliams — APPROVED** [review]
LGTM

The split looks a lot better. There might be some micro-optimizations we could do by splitting up the upgrade test based on the part that uses system temp ... but we could probably do just as well rewriting all of it.

Also codecov seems to have failed to upload for some reason, though I'm not sure if that is an issue with the PR or codecov. I would give it another kick first

**Comment by Hixie** [comment]
https://cirrus-ci.com/task/5658840365793280?command=test claims to have been successful...

**Comment by Hixie** [comment]
(codegen regression is expected.)

**Pull request merged**
