### PR TITLE
Switch to the new Matrix4.tryInvert method to avoid throwing and catching exceptions while hit-testing

### PR DESCRIPTION
**Pull request by jacob314**
The exceptions occurred for non-invertible matrices which typically occur when a transform has scale 0.
The only package I care about updating the version of is vector_math which switched from 2.0.5 to 2.0.6
I can remove the other auto-generated package updates if desired.
I ran
`flutter update-packages --force-upgrade`
after changing the dependency on vector_math from 2.0.5 to 2.0.6
Let me know if that isn't the right way to do it.

### CODE REVIEW

**Comment by jacob314** [comment]
@devoncarew this should fix all the cases where attempting to invert a matrix would throw and catch an exception.

**Comment by jacob314** [comment]
The pubspec.yaml diff now looks right with just the change to the vector_math package version.

**Comment by devoncarew** [comment]
I think you accidentally picked up `examples/flutter_gallery/lib/main.dart.dill` in this PR.

rslgtm to me...

**Comment by jacob314** [comment]
removed dill file accidentally added to CL.

**Comment by Hixie** [comment]
LGTM
￼￼

**Comment by Hixie** [comment]
You should run `flutter update-packages --force-upgrade`, and it's fine if it updates multiple packages.

**Pull request merged**
