### PR TITLE
Reland: TextSelectionTheme support (step 2 of 3)

### PR DESCRIPTION
**Pull request by darrenaustin**
The original PR: #65044 was reverted due to a problem with the gold image system. Now that it has been resolved, this attempts to land it again.

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 6 untriaged digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/66061

**Review by justinmc — APPROVED** [review]
LGTM

Is this part of the process for fixing the skia gold bot comments like the one on this PR?

**Comment by darrenaustin** [comment]
> Is this part of the process for fixing the skia gold bot comments like the one on this PR?

No Kate already fixed gold. The problem was while it was broken, my original PR had broke the tree due to an image not being approved. Jonah reverted it to get the tree back to green. This is just a relanding now that gold has been fixed.

**Comment by justinmc** [comment]
Got it, thanks!

**Pull request merged**
