### PR TITLE
Repackage manual_tests with the current project template

### PR DESCRIPTION
**Pull request by jason-simmons**
See https://github.com/flutter/flutter/pull/10000

### CODE REVIEW

**Comment by jason-simmons** [comment]
@yjbanov

**Comment by Hixie** [comment]
Lets remove the icons if we can, they're not needed for the manual tests.

cc @cbracken who just did something similar and may remember other things we can trim.

**Comment by jason-simmons** [comment]
done

**Review by yjbanov — APPROVED** [review]
LGTM

**Pull request merged**
