### PR TITLE
Fix for Issue #112983

### LINKED ISSUE #112983: Broken link in `android/app/build.gradle` of a new Flutter project
The `android/app/build.gradle` of a new Flutter project contains:

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.myapp"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.

The link is incorrect. The page still exists, but the anchor changed and is now: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration

### PR DESCRIPTION
**Pull request by domesticmouse**
Fixes: https://github.com/flutter/flutter/issues/112983

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by stuartmorgan-g — CHANGES_REQUESTED** [review]
It looks like you auto-formatted gradle_errors.dart; that will need to be reverted. (I'm not sure what the non-formatting change in that file is so I didn't do a full review.)

**Comment by domesticmouse** [comment]
> It looks like you auto-formatted gradle_errors.dart; that will need to be reverted. (I'm not sure what the non-formatting change in that file is so I didn't do a full review.)

Auto formatting reverted, now it is just the required URL changes.

**Review by stuartmorgan-g — APPROVED** [review]
LTGM, thanks!

(I wish we could specify custom anchors so that minor rewordings of headings didn't break our links all the time.)

**Comment by domesticmouse** [comment]
@stuartmorgan what is the process to land this PR? Tag with a merge on green tag?

**Pull request merged**
