### PR TITLE
Remove FakeProcessResult for Dart 3 compatibility

### LINKED ISSUE #124237: A fuchsia_remote_debug_protocol test implements `ProcessResult`
`ssh_command_runner_test.dart` contains this code:

```dart
class FakeProcessResult extends Fake implements ProcessResult {
  @override
  int exitCode = 0;

  @override
  dynamic stdout;

  @override
  dynamic stderr;
}
```

In Dart 3, `ProcessResult` is `final` and can't be implemented.

So just use the `ProcessResult` constructor instead.

### PR DESCRIPTION
**Pull request by brianquinlan**
Removes code that `implements ProcessResult` since it will be `final` in Dart 3.

Fixes https://github.com/flutter/flutter/issues/124237

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
lgtm on green

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Because I don't believe this will have any effect on g3 (and google testing itself is having problems). I'm going to land this on a green tree

**Comment by brianquinlan** [comment]
@jonahwilliams So you'll apply the `autosubmit` label? I was going to ask for that...

**Pull request merged**
