### PR TITLE
Add benchmark for number of GCs in animated GIF

### PR DESCRIPTION
**Pull request by dnfield**
Benchmark for https://github.com/flutter/flutter/issues/80702

This does not improve the image, but adds some new categories to the timeline summary we send to the perf dashboard and a test that specifically focuses on animating a GIF for a set number of frames.

### CODE REVIEW

**Comment by goderbauer** [comment]
Looks like the checks are unhappy.

**Review by goderbauer — APPROVED** [review]
LGTM once checks are happy

**Review by jonahwilliams — COMMENTED** [review]
Isn't this adding more benchmarking tasks to the existing macrobenchmarks app? Can we keep doing this, or do they need to be split into separate devicelab tasks

**Comment by dnfield** [comment]
@jonahwilliams - yes it is. I don't know the answer to that question though - @keyonghan or @godofredoc might have thoughts.

**Comment by godofredoc** [comment]
> question though - @keyonghan or @godofredoc might have thoughts
Ideally we should prefer more tasks with less execution time over less tasks with longer execution times. This will allow us to make more efficient use of resources when we increase the devicelab capacity.

**Comment by dnfield** [comment]
Actually, this adds a test to the Macrobenchmarks application, but I don't think it adds a definition of where to run it. That's changed since I last did this.

**Comment by dnfield** [comment]
@christopherfujino  do you know why the test failure https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8848843484897376256/+/steps/run_test.dart_for_framework_tests_shard_and_subshard_misc/0/logs/stdout/0#L13293_0 is happening on this patch? IT seems unrelated to me, but rebasing to head doesn't seem to have helped.

**Comment by goderbauer** [comment]
The test is now disabled on HEAD (see tree-status chat), so rebasing on master should now fix it.

**Comment by dnfield** [comment]
I've also added this to its own builder. @jonahwilliams to your question, we run the macrobenchmarks app in a bunch of tasks, each isolated to its own test.

**Comment by keyonghan** [comment]
The builder configuration needs to be added in flutter/infra first before enabling here in prod_builders.json, otherwise test will not be triggered.

**Comment by dnfield** [comment]
I'll open the infra PR shortly.

**Pull request merged**
