### PR TITLE
Use the new service protocol message names

### PR DESCRIPTION
**Pull request by a-siva**
Use the new service protocol message names instead of the old private names
  clearVMTimeline
  setVMTimelineFlags
  getVMTimeline
  getVMTimelineFlags

### CODE REVIEW

**Review by bkonyi — APPROVED** [review]

**Review by tvolkert — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
Can we submit this to get the tree back to green?

**Comment by bkonyi** [comment]
> Can we submit this to get the tree back to green?

I assume we're waiting on the deploy_gallery-macos bots to finish?

**Comment by goderbauer** [comment]
It seems to have a passing run on cirrus, not sure why it got re-run after that?

https://cirrus-ci.com/task/5110686479286272

**Pull request merged**
