### PR TITLE
Prevent building non-android plugins in build aar

### LINKED ISSUE #57795: [flutter module] Flutter_tools/gradle/aar_init_script.gradle' line: 15  - AAR build fail
## Steps to Reproduce

1. Create an add-to-app module: `flutter create -t module --org com.example path_provider_issue`
2. Add dependency `path_provider: ^1.5.1` to pubspec.yaml and run `flutter pub get`
3. Run `flutter build aar`

If opening pubspec.lock I found that:

```
  path_provider_macos:
    dependency: transitive
    description:
      name: path_provider_macos
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "0.0.4+3"
```

and if I force `path_provider_macos` to 0.0.4+2 in pubspec.yaml, the build passes.

path_provider_macos 0.0.4+3 removes the android module, but Flutter tries to evaluate android/build.gradle inside it.

## Logs

```
➜  path_provider_issue $ ls -a
.                               .dart_tool                      .gitignore                      .metadata                       lib                             pubspec.lock
..                              .flutter-plugins                .idea                           .packages                       path_provider_issue.iml         pubspec.yaml
.android                        .flutter-plugins-dependencies   .ios                            README.md                       path_provider_issue_android.iml test
➜  path_provider_issue $ flutter pub get
Running "flutter pub get" in path_provider_issue...                 0.3s
➜  path_provider_issue $ flutter build aar
Running Gradle task 'assembleAarDebug'...
Running Gradle task 'assembleAarDebug'... Done                      3.3s


FAILURE: Build failed with an exception.

* Where:
Initialization script '/Users/perqinxie/App/flutter-latest-stable/packages/flutter_tools/gradle/aar_init_script.gradle' line: 15

* What went wrong:
Android property not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s


Gradle task assembleAarDebug failed with exit code 0.
```

Running `flutter doctor -v`:

```
➜  path_provider_issue $ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale ja-CN)
    • Flutter version 1.17.1 at /Users/perqinxie/App/flutter-latest-stable
    • Framework revision f7a6a7906b (9 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/perqinxie/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/perqinxie/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/perqinxie/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.1 Preview.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6911.31
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is *.oa.com,*.tencent.com,127.0.0.1,localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • BLN AL10 • JJRDU16A26004316 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by blasten**
## Description

Ensures that `build aar` doesn't link against non-android plugins.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/57795

## Tests

I added the following tests: Updated integration test

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM!

**Comment by creativecreatorormaybenot** [comment]
Will this be avaible on `stable`?

**Comment by blasten** [comment]
cc @pcsosinski - is it possible to cherry-pick this commit?

**Comment by pcsosinski** [comment]
https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process

**Pull request merged**
