### PR TITLE
Eliminate Dart 1 benchmarks

### PR DESCRIPTION
**Pull request by cbracken**
Flutter app development has been Dart 2 only for a significant amount of
time, and we're about to remove all support for Dart 1.

### CODE REVIEW

**Comment by sjindel-google** [comment]
Don't we also need to update `dev/devicelab/lib/tasks/microbenchmarks.dart` (lines 78 - 82)?

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
Looks like the analyzer has one tiny complaint.

**Comment by cbracken** [comment]
Fixed.

**Comment by cbracken** [comment]
@sjindel-google FYI the Flutter trees are currently closed pending the resolution of [TODAY issues](https://github.com/flutter/flutter/labels/%E2%9A%A0%20TODAY). I'll land this once the tree is re-opened.

**Pull request merged**
