### PR TITLE
painting: drop deprecated (exported) hashList and hashValues functions

### PR DESCRIPTION
**Pull request by kevmoo**
These have been deprecated for over a year
Will remove from the engine once this PR lands

Towards https://github.com/flutter/flutter/issues/151679

### CODE REVIEW

**Comment by stuartmorgan** [comment]
test-exempt: removing code

**Comment by kevmoo** [comment]
Need to land https://github.com/flutter/engine/pull/53844 first (and roll the engine)

**Comment by kevmoo** [comment]
@goderbauer – this is ready

**Comment by goderbauer** [comment]
Looks like this will require some clean-up in google3, see failing "Google testing" check.

**Review by goderbauer — APPROVED** [review]
LGTM once Google Testing passes

**Comment by kevmoo** [comment]
Blocked on http://cl/651168595

**Pull request merged**
