### PR TITLE
Adding Fuchsia to Material Color

### PR DESCRIPTION
**Pull request by dvdwasibi**
Customer Pink uses this a lot, so might be nice to make this a const.

@apwilson

### CODE REVIEW

**Comment by Hixie** [comment]
This seems dubious. Shouldn't it be in a fuchsia widget library?

**Comment by apwilson** [comment]
@Hixie You have a point.

How about this?

There's a cupertino.dart.
There's a material.dart.

So.....   this should go in fuchsia.dart!

**Comment by dvdwasibi** [comment]
also ```building_1842.dart```

**Comment by Hixie** [comment]
I think that would make total sense, though I don't think the Flutter team has the bandwidth to maintain such a library at this time...

**Comment by Hixie** [comment]
Closing this since I think this was discussed offline. Please reopen if I misunderstood.

**Pull request closed without merging**
