### PR TITLE
Fixed concurrent list modification in vmservice.dart

### PR DESCRIPTION
**Pull request by bkonyi**

### CODE REVIEW

**Comment by zanderso** [comment]
Is there an issue filed for this?

**Comment by bkonyi** [comment]
No, but it came up when testing the background plugins with hot reload enabled.

**Review by zanderso — APPROVED** [review]

**Comment by tvolkert** [comment]
@cbracken landed this a few days ago and had to revert, iirc

**Comment by bkonyi** [comment]
@tvolkert is it [this change](https://github.com/flutter/flutter/pull/18284/commits/aba4a9d9e54efe3da258a911c5387a909da31997)? Looks like it's a different concurrent modification.

**Comment by tvolkert** [comment]
Ah yes, that's the one 😄

**Comment by cbracken** [comment]
Mine is reverted but was only really an issue due to a misplaced curly bracket; and yep definitely a separate issue :)

LGTM

**Review by cbracken — APPROVED** [review]

**Comment by Hixie** [comment]
BTW, this was checked in when the tree was red. Please avoid checking anything in when the tree is red except for attempts to fix the tree, because it makes it much harder to detect, and later identify, additional failures introduced while the previous failure was ongoing. If you suspect a flaky result, please re-run the test rather than checking in while red. If that isn't possible, at a minimum please note the situation in the PR when landing it. Thanks!

**Pull request merged**
