### PR TITLE
Fix error message and other typos

### PR DESCRIPTION
**Pull request by westy92**

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
Thanks!

LGTM

**Comment by ened** [comment]
Hi @westy92 could you please also update other files rgd. that typo:

```
packages/flutter/lib/src/semantics/semantics.dart
2447:/// The information provided in the configuration is used to to generate the

packages/flutter/lib/src/cupertino/bottom_tab_bar.dart
93:  /// This value is used to to configure the [IconTheme] for the navigation

packages/flutter/lib/src/widgets/framework.dart
3927:          'Typically references to to inherited widgets should occur in widget build() methods. Alternatively, '
```

Thank you :-)

**Comment by westy92** [comment]
Yes!

**Comment by westy92** [comment]
@ened done!

**Comment by getex001** [comment]
OkVon meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [flutter/flutter] Fix error message. (#25126)Von: Seth Westphal An: flutter/flutter Cc: Subscribed @ened done!

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/flutter/flutter","title":"flutter/flutter","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/flutter/flutter"}},"updates":{"snippets":[{"icon":"PERSON","message":"@westy92 in #25126: @ened done!"}],"action":{"name":"View Pull Request","url":"https://github.com/flutter/flutter/pull/25126#issuecomment-446043278"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/flutter/flutter/pull/25126#issuecomment-446043278",
"url": "https://github.com/flutter/flutter/pull/25126#issuecomment-446043278",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [flutter/flutter] Fix error message. (#25126)",
"sections": [
{
"text": "",
"activityTitle": "**Seth Westphal**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@westy92",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"flutter/flutter\",\n\"issueId\": 25126,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"flutter/flutter\",\n\"pullRequestId\": 25126\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/flutter/flutter/pull/25126#issuecomment-446043278"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 422026325\n}"
}
],
"themeColor": "26292E"
}
]

**Pull request merged**
