### PR TITLE
Launch DevTools from the 'dart devtools' command instead of pub

### PR DESCRIPTION
**Pull request by kenzieschmoll**
CC @bkonyi

### CODE REVIEW

**Comment by bkonyi** [comment]
FYI @zanderso

**Comment by christopherfujino** [comment]
Looks like you'll have to update `//flutter/dev/bots/test.dart`:

```
Unhandled exception:
FileSystemException: Cannot open file, path = '/b/s/w/ir/x/w/flutter/bin/internal/devtools.version' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#4      _runIntegrationToolTests (file:///b/s/w/ir/x/w/flutter/dev/bots/test.dart:325:75)
#5      _runFromList (file:///b/s/w/ir/x/w/flutter/dev/bots/test.dart:1812:23)
#6      selectShard (file:///b/s/w/ir/x/w/flutter/dev/bots/test.dart:1787:62)
#7      main (file:///b/s/w/ir/x/w/flutter/dev/bots/test.dart:137:11)
<asynchronous suspension>
```

**Review by christopherfujino — APPROVED** [review]
Code LGTM, you'll have to make some updates to fix CI. Also, if "Google Testing" fails you'll have to make a g3fix for this (by approving this, it should schedule the "Google Testing" check)

**Comment by kenzieschmoll** [comment]
FYI @DanTup and @stevemessick for VS code and IntelliJ implications of this. Danny, we'd like to have VS code start launching from `dart devtools` - you should still be able to pass in your existing server URI as you would have before when launching from pub. Steve, once this is landed and pushed through to stable, we'll want to remove the "Launching DevTools" dialog from IntelliJ, as this method eliminates the slowdown caused by activating devtools from pub.

**Comment by DanTup** [comment]
sgtm! It looks like this command doesn't exist in the current stable release, so I presume Dart SDK >= v2.15 would be the right version to check for?

**Comment by kenzieschmoll** [comment]
> so I presume Dart SDK >= v2.15 would be the right version to check for?

That should work. This is the commit that added the command https://github.com/dart-lang/sdk/commit/d7c8e6a9d38df8620fa60a661d2340383e61578c, so it looks like `2.15.0-39.0.dev` is the earliest dart version this commit was included in.

**Review by zanderso — COMMENTED** [review]
Thanks for doing this!

**Pull request merged**
