### PR TITLE
fix(FocusScope): Example fix

### PR DESCRIPTION
**Pull request by albertodev01**
There is a `super.dispose()` call that should go last. This PR just moves it at the bottom of the `dispose()` method.

 - https://github.com/flutter/flutter/issues/98665

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by albertodev01** [comment]
@gspencergoog @cbracken please merge 🙂

**Pull request merged**
