### PR TITLE
Add log to understand flakiness of commands_test

### PR DESCRIPTION
**Pull request by B3rn475**
The flakiness of commands_test is generally visible via:

```
drive:stdout:   Expected: 'log: paint'
drive:stdout:     Actual: ''
drive:stdout:      Which: is different. Both strings start the same, but the actual value is missing the following trailing characters: log: paint ...
```

By returning the name of the test we will be able to understand if
another test is running by reading the `Actual` value

### CODE REVIEW

**Comment by Hixie** [comment]
Might be more effective to instrument _requestData in flutter_driver/lib/src/extension.dart. Something like returning `'${Platform.executable} has not registered a data handler'`.

**Comment by Hixie** [comment]
(assuming that Platform.executable returns something useful, you'd have to check that first)

**Comment by Hixie** [comment]
(LGTM in case you really want to check this in rather than going the more general route)

**Comment by B3rn475** [comment]
I've tried with:
- `Platform.executable`, but it is 'null'
- `Platform.script`, but it is `'..app_flutter/app.flx'`

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
(bonus points for making the default some string other than "", though.)

**Pull request merged**
