### PR TITLE
fix: ZoomPageTransitionsBuilder always has black outlines during transitions

### LINKED ISSUE #115275: ZoomPageTransitionsBuilder black flickering on top
I noticed a black area that shows up for a short amount of time on navigation.

https://user-images.githubusercontent.com/26410357/201684926-58cc5521-c3cc-47e4-8c59-a9bdcadcd4a0.mov

Shouldn't it be the default scaffold color that is visible while the navigation is in progress or something similar?

### PR DESCRIPTION
**Pull request by LowLevelSubmarine**
When using ZoomPageTransitionsBuilder which is the default for ThemeData on Android, we always get black edges around the exiting page that is beeing zoomed out in the background. This is because both pages dont fully fill the enclosing navigators area opaque and the color for filling these pixels is always set to black. This PR aims to change this color to a more pleasent one: The current themes canvasColor.

fixes: https://github.com/flutter/flutter/issues/115275, https://github.com/flutter/flutter/issues/116127

### Before
[unfixed.webm](https://github.com/flutter/flutter/assets/33373745/a5694e43-61cd-4433-945a-ab2e5a460323)

### After
[fixed.webm](https://github.com/flutter/flutter/assets/33373745/d434e462-10a4-4814-908b-7910982222ca)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`). (there were no docs to change)
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by LowLevelSubmarine** [comment]
## Regarding the missing tests
I've never coded any tests in Flutter so i dont really know where to start. I'd like to know first if this approach is acceptable for the flutter team before investing my time into writing tests for this PR.
I'd happily take any advice on how and what to test regarding this PR.

**Comment by LowLevelSubmarine** [comment]
@HansMuller thank you for taking a look at my MR. I've written a comment above regarding the missing tests. Are you in a position where you can tell me if my approach is acceptable, so that i can go on writing the tests?

**Comment by victorsanni** [comment]
Hi @LowLevelSubmarine! Do you plan to keep working on this PR and adding tests?

**Comment by Piinks** [comment]
Hey @LowLevelSubmarine thank you for the PR, since we have not heard back, I am going to close it for now. If you would like to continue working on this, we can reopen it. Thank you!

**Comment by dy0gu** [comment]
Hey @Piinks, the changes here solve #126682 (closed due to waiting on a framework fix) over at `go_router` along with both the issues mentioned at the start of this thread.

If the flutter team is okay with they way this PR fixes it I believe the only thing left is to write a test. I fail to see how such a simple change could even merit a test, seeing as nothing is removed or added, we are simply switching the hard coded `Color.black` with a color from the current theme to fill in the transition.

In any case, if you could give some pointers on how a test for this PR would look like I wouldn't mind taking a crack at it and having it reopened. Considering this is currently related to an issue with a P2 label (#116127), it would be great have it merged.

**Comment by victorsanni** [comment]
Hi @dy0gu, thanks for reaching out. 

The framework requires tests to prevent your changes to be regressed. Someone could come along in the future and revert these changes, unless a test exists to at least alert them of the potential consequences of doing so.

For this PR, a good test would be something like:
- Open `flutter/packages/flutter/test/material/page_transitions_theme_test.dart` to add a new test.
- Pump an app containing this widget, but with a background color that is not black.
- Verify that no black color is painted, but instead the background color (which is not black) is painted.

Feel free to draw inspiration from other tests in `flutter/packages/flutter/test/material/page_transitions_theme_test.dart`.

Thanks for your work so far, and we're looking forward to further changes so that we can reopen and merge this PR!

**Comment by dy0gu** [comment]
Yea I noticed it when I first started working but completely forgot to tell you here that I would need to do that. 

I'll create a new PR as soon as I'm done and give credit for the initial changes I take from here, thanks again!

**Pull request closed without merging**
