### PR TITLE
Downgrade the AndroidX warning

### LINKED ISSUE #37840: [Errors] Tone down the AndroidX errors
## Use case
Every Gradle build fail comes with a huge block saying that this could be due to androidX incompatibility, that makes it a little harder to find the actual error.

https://gist.github.com/prasadsunny1/1024d1c723658b842c12a0bf170c7dde#file-codemagicandroidcrash-L1429

attracts a lot of attention whereas failure is happening at
https://gist.github.com/prasadsunny1/1024d1c723658b842c12a0bf170c7dde#file-codemagicandroidcrash-L1421

This is not a huge issue but makes it a little uncomfortable for people to track the actual source of error in the logs.

## Proposal
Tone down on the AndroidX errors a little, or at least come up with a way to show AndroidX warning only when there is actually an AndroidX error.

### PR DESCRIPTION
**Pull request by mklim**
## Description

Originally we wanted to cast as wide of a net and make the warning as
prominent as possible. Recently we've received feedback that the false
positives are more harmful than not, so downgrading the loud message to
a single line warning.

## Related Issues

Fixes #37840

## Tests

I added no tests, seeing no way to test log output. Happy to correct this if it's feasible to test.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by blasten — APPROVED** [review]
LGTM!

**Comment by Hixie** [comment]
Test?

**Comment by mklim** [comment]
@Hixie looks like there were none:

> ## Tests
>
> I added no tests, seeing no way to test log output. Happy to correct this if it's feasible to test.

I can go back and add a test for this to bring this back up to Flutter style if you'd like? This patch is a couple months old and was written before the emphasis that all PRs must be tested regardless of whether or not our existing infra makes that immediately feasible. I'm still not sure how to test log output here, but I can go figure it out. :)

**Comment by blasten** [comment]
If it helps, I added a couple of tests that exercises this path.

**Comment by Hixie** [comment]
I ran into this because I tried to change the message to remove the trailing period and no tests failed. :-)
I'll add a test as part of my fix.

**Comment by mklim** [comment]
Thank you!

**Pull request merged**
