### PR TITLE
- Fix that the custom underline color of the TextField is invalid

### PR DESCRIPTION
**Pull request by hezl2021**
- Fix that the custom underline color of the TextField is invalid

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 6 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/85110

**Comment by hezl2021** [comment]
#85110

**Comment by hezl2021** [comment]
> @googlebot I signed it!

**Comment by hezl2021** [comment]
> @googlebot I fixed it.

**Comment by hezl2021** [comment]
> @googlebot I fixed it.

**Comment by hezl2021** [comment]
> @googlebot I fixed it.

**Comment by skia-gold** [comment]
Gold has detected about 8 new digest(s) on patchset 5.
View them at https://flutter-gold.skia.org/cl/github/85110

**Comment by skia-gold** [comment]
Gold has detected about 6 new digest(s) on patchset 7.
View them at https://flutter-gold.skia.org/cl/github/85110

**Pull request closed without merging**
