### PR TITLE
Update Xcode to 14.3.1

### PR DESCRIPTION
**Pull request by vashworth**
Framework part of https://github.com/flutter/flutter/issues/129019

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by vashworth** [comment]
@keyonghan Do you happen to know why the `ci.yaml validation` check is stuck?

**Comment by keyonghan** [comment]
> @keyonghan Do you happen to know why the `ci.yaml validation` check is stuck?

There maybe some glitch when scheduling. Do you mind taking a look at the backend log to see if any errors? /cc @sealesj 

@vashworth To unblock, reset the try tasks.

**Comment by vashworth** [comment]
> @vashworth To unblock, reset the try tasks.

@keyonghan How do I reset try tasks?

**Comment by keyonghan** [comment]
> > There maybe some glitch when scheduling. Do you mind taking a look at the backend log to see if any errors? /cc @sealesj
> > @vashworth To unblock, reset the try tasks.
> 
> @keyonghan I'm unsure of what backend log you're referring. Where can I find it? 

Sorry I meant this question for the Infra gardener.

Also, how do I reset try tasks?

go/flutter-luci-playbook#manually-trigger-try-pre-submit-builds

**Comment by sealesj** [comment]
Seeing status 500 errors in the logs which is around the same time as an issue with a dart-internal message issue that could be affecting this change. However that issue should be resolved so resetting the try tasks should fix this

**Review by keyonghan — APPROVED** [review]
LGTM

**Pull request merged**
