### PR TITLE
Adding a CalendarMultiDatePicker to cater discrete multi-date selection 

### PR DESCRIPTION
**Pull request by bananagag**
## Description

The current calendar pickers in Flutter only allows single-date selection or range selection, but in many situations users want to select several separate days / ranges of days. This PR implements a CalendarMultiDatePicker that serves for the above usage.

## Related Issues

[#22621](https://github.com/flutter/flutter/issues/22621)

## Tests

I added the following tests:

I can't find any current test cases for material pickers in Flutter so there's no tests done.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by fish-like-mammal** [comment]
@googlebot I fixed it.

**Comment by cwyu-Ivan** [comment]
@googlebot I consent.

**Comment by fish-like-mammal** [comment]
@googlebot I consent.

**Comment by fish-like-mammal** [comment]
@darrenaustin may I know if there's any problems with my codes?

**Comment by darrenaustin** [comment]
@bananagag thanks for the PR. I realize you are still working on it and it is still a draft, but wanted to chime in here before you spent more time on it.

It looks great from what I have seen, however, we don't have a Material Design for this kind of picker and we would like to keep what is in the material package to just things that support the spec. I will bring up the desire for this kind of feature (as I think it is useful myself) with the design team and see if they have any plans for anything like this. For now though I would strongly encourage you to turn this into a package so that others can use this if they need this kind of functionality.

**Pull request closed without merging**
