### PR TITLE
Add tests for integration tests to devicelab

### PR DESCRIPTION
**Pull request by jiahaog**
Device lab tests for #76200

Tested:

First patch #76200, and `cd dev/devicelab`.

Android:

```sh
 ../../bin/cache/dart-sdk/bin/dart bin/run.dart -t bin/tasks/integration_test_test.dart
```

iOS

Need to modify the runner to create a custom team and bundle ID first, then

```sh
 ../../bin/cache/dart-sdk/bin/dart bin/run.dart -t bin/tasks/integration_test_test_ios.dart
```

Not sure if there's a way to test that the `prod_builders.json` is correct locally, so I think the above should be good enough

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
FYI @CaseyHillers for devicelab changes


LGTM

**Comment by jiahaog** [comment]
https://flutter-dashboard.appspot.com/#/build shows that the entire row for this commit is green, but I would have expect a new column to be added for this change, since new tests are added. Am I doing something wrong here? https://github.com/flutter/flutter/blob/master/dev/devicelab/README.md seems to be a bit out of date with `prod_builders.json`

**Comment by CaseyHillers** [comment]
You'll need to update https://cs.opensource.google/flutter/infra/+/master:config/devicelab_config.star;bpv=1 to dedicate infrastructure to run these tasks. This PR only added UI to show the infrastructure.

Adding the task name to `linux_tasks`, `mac_tasks` will start running these.

**Comment by jiahaog** [comment]
Will do, opened https://github.com/flutter/infra/pull/401 for this!

**Pull request merged**
