### PR TITLE
Cleanup and consolidate .gitignores

### PR DESCRIPTION
**Pull request by rock3r**
This PR consolidates .gitignore rules and removes all the `*.iml` IDEA projects from the repo, so that people can load the projects and change them without risking unwanted changes to the IDEA project files (which are now removed and ignored).

All the common patterns have been moved to the root `.gitignore`, and others have been moved to parent folders as needed.

Please double check that the changes to the `.gitignore`s are not affecting any of your internal stuff as it seems there's some traces of non-public data in there, and I cannot check that.

### CODE REVIEW

**Comment by gspencergoog** [comment]
Thanks for the PR!

Couldn't we just consolidate the `.gitignore`s, and leave the `.iml`s intact?   We're concerned that the new user startup will be more complicated than it already is if we don't have the .iml files in the workspace when they start.

We could keep the .iml files in the .gitignore, so that if we update them we'll need to force add them, but at least that way they won't clutter up all our other checkouts when modified.

**Comment by gspencergoog** [comment]
Also, it would be good to also incorporate all that makes sense from here:
https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

Of course, we would also add the .iml files to the .gitignore (which Jetbrains doesn't recommend), but we don't commit them often enough that we can't `git add -f` them for that case: they are annoying when they change on their own all the time.

**Comment by Hixie** [comment]
I definitely support removing the IML files, but that's because I don't use them. :-)

cc @devoncarew

**Comment by devoncarew** [comment]
They are useful for setting up this repo for development w/ IntelliJ. We've definitely seen some unfortunate churn in the iml files however :(

Generally (if the team is using IntelliJ), I think you want to check in the project structure files (*.iml, and some files from .idea/ like the modules.xml) but not check in the files that are per-user specific (settings or window locations) like workspace.xml.

I'm open to removing them if people don't think they're a net value. It will mean some adjustment for people that are currently using the project w/ IntelliJ (when their metadata files disappear out from under them).

**Comment by Hixie** [comment]
Can we or IntelliJ autogenerate these files in some useful manner?

**Comment by devoncarew** [comment]
IntelliJ wouldn't be able to w/o knowledge of how the repo is laid out. A user could get it to, by opening / importing each separate module, but that would be a good thing to avoid.

We could generate the files easily, w/ a few hours invested in a script. I don't have plans or time really do to so, but it would be straightforward. The simplest solution is to check in the files defining the project structure - the iml files and such - which is what we have now.

**Comment by rock3r** [comment]
The iml files are generally generated by IntelliJ when importing a module — I did it just for testing, and it works, although it is some additional effort, it's a very low effort in my opinion. I understand though that this may cause some issues. I removed them out of habit, since as an Android dev I usually have the Gradle `build.gradle` files that are enough for IDEA to re-generate its project and module settings. In fact, I normally ignore them and remove them from the repo.

I see that this may not be the best idea in this case, though, since there's no parallel mechanism to inform the project structure. It's a semi-manual task (mostly consisting in a couple clicks in IDEA) to have it load the Dart SDK, and it is adding friction for new contributors.

As a reference, this is what I generally have in my Android projects' `.gitignore`s: https://github.com/squanchy-dev/squanchy-android/blob/26ebffb3e2f123d309f831c5237cc40814731401/.gitignore#L11-L46 — noteworthy difference from github's own IDEA `.gitignore` is that it includes the `.idea` folders, excluding some high-churn and low utility files; it is tailored to Android projects, though, so there may be something else we might want to keep in VCS, even though I wouldn't really know what.

I'm happy to revert f1db6db but at that point I'm thinking it may not be worth continuing with this PR at all; if someone changes the project structure and forgets to force add the iml files, we might end up in a tough corner where the project "works on my machine" but won't for others. Your call, team :)

**Comment by gspencergoog** [comment]
FYI, I'm going to make another PR that includes just the .gitignore parts of this (thanks again!), and Devon and I have another plan to fix the whole .iml problem.

**Comment by rock3r** [comment]
Sounds great! Thanks for looking at this folks ❤️

**Pull request closed without merging**
