### PR TITLE
Script to find Flutter earliest Flutter revision that contains an engine revision

### PR DESCRIPTION
**Pull request by dnfield**
TODO: Skia/Dart versions of this for the engine.  Those will be a little harder since the DEPS file is more complicated.

This doesn't handle reverts.

It also is very slow for very old commits.

### CODE REVIEW

**Comment by christopherfujino** [comment]
This isn't working for me locally, but that might be something weird with my setup. Investigating further.

**Review by christopherfujino — APPROVED** [review]
Ok, never mind, this works, my engine repo was outdated. LGTM. nit: should this tool give a suggestion to fetch upstream on both repos if it finds no matches?

**Comment by dnfield** [comment]
I'll just make it fetch upstream on both repos before looking.

**Comment by christopherfujino** [comment]
> I'll just make it fetch upstream on both repos before looking.

Note that the remote may not be named `upstream` for all users. `git fetch --all` may be safer. Also, this may trigger a password prompt for the SSH key.

**Comment by dnfield** [comment]
Ahh ok, I'll do `--all` then - I think the password is ok, I'll add a print message about it.

**Comment by dnfield** [comment]
Timed out on setup.  Going to land this on red to kick the build.  This script has 0 impact on tests.

**Pull request merged**
