### PR TITLE
Roll engine af855e063a9c..46b77937b39f (3 commits)

### PR DESCRIPTION
**Pull request by rmistry**
https://github.com/flutter/engine/compare/af855e063a9c...46b77937b39f

git log af855e063a9c..46b77937b39f --date=short --no-merges --format='%%ad %%ae %%s'
2018-07-30 jason-simmons@users.noreply.github.com Clear the EGL context only if our context is currently active (#5895)
2018-07-30 jason-simmons@users.noreply.github.com Return proper JSON-RPC error responses from service protocol failures (#5889)
2018-07-30 37626415&#43;skia-flutter-autoroll@users.noreply.github.com Roll src/third_party/skia 227424b57d28..c06b8a4e0ca3 (22 commits) (#5904)

The AutoRoll server is located here: http://localhost:8000

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/&#43;/master/autoroll/README.md

If the roll is causing failures, please contact the current sheriff, who should
be CC&#39;d on the roll, and stop the roller if necessary.

### CODE REVIEW

**Comment by rmistry** [comment]
@rmistry : New roll has been created by http://localhost:8000

**Comment by rmistry** [comment]
Trybots failed. These were the failed builds: https://cirrus-ci.com/task/5182199498276864 , https://cirrus-ci.com/task/5745149451698176 , https://cirrus-ci.com/task/4900724521566208

**Comment by rmistry** [comment]
@liyuqian where these checks supposed to fail? or is there a known issue?

**Comment by liyuqian** [comment]
It looks to me that the engine artifacts are not yet compiled in Chrome
bots so all the checks failed.

**Comment by rmistry** [comment]
Oh I see, so it is expected that it failed.

**Comment by rmistry** [comment]
Commit queue failed; closing this roll.

**Pull request closed without merging**
