### PR TITLE
Size of a childless container's implicit DecoratedBox descendants

### LINKED ISSUE #6608: Transformed aligned Container doesn't behave the same as a Transformed Container within an Align
In the following example the inner Container's size ends up being 300x400, not 50x100.
```
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Center(
      child: new Container(
        decoration: new BoxDecoration(backgroundColor: Colors.green[300]),
        width: 300.0,
        height: 400.0,
        child: new Container(
          width: 50.0,
          height: 100.0,
          alignment:FractionalOffset.topLeft,
          decoration: new BoxDecoration(backgroundColor: Colors.purple[300]),
        ),
      ),
    );
  }
}
```

I believe that the previous example should behave the same as this version, in which the inner Container is 50x100 as expected.
```
class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Center(
      child: new Container(
        decoration: new BoxDecoration(backgroundColor: Colors.green[300]),
        width: 300.0,
        height: 400.0,
        child: new Align(
          alignment:FractionalOffset.topLeft,
          child: new Container(
            width: 50.0,
            height: 100.0,
            decoration: new BoxDecoration(backgroundColor: Colors.purple[300]),
          ),
        ),
      ),
    );
  }
}
```

### PR DESCRIPTION
**Pull request by HansMuller**
If a container doesn't specify a child then its alignment should define the size of its implicit DecoratedBox children, if any.

Fixes #6608

### CODE REVIEW

**Comment by Hixie** [comment]
Shouldn't the ConstrainedBox be inside the Align?

**Comment by HansMuller** [comment]
If there's no child, then the ConstrainedBox is within the Align and the DecoratedBoxes are within the ConstrainedBox. That way the decorated boxes are constrained by the width/height args and aligned within the container.

If there is a child, then things are as they were before.

**Comment by Hixie** [comment]
Ok LGTM but I think we're gonna want to change this again to change the case if there is a child.

**Comment by HansMuller** [comment]
OK, I will sort that out in a separate change.

**Pull request merged**
