### PR TITLE
remove gitignored generated files

### PR DESCRIPTION
**Pull request by goderbauer**
These files are re-generated on every flutter run, sometimes there are changes which cause annoying diffs on local machines.

These files are already gitignored in our repo [1] and I think we should just remove the files that were checked in before they were added to `.gitignore`.

[1] https://github.com/flutter/flutter/blob/master/.gitignore

### CODE REVIEW

**Comment by mit-mit** [comment]
@mravn-google can you think of any issues with removing these?

**Comment by mravn-google** [comment]
Following this change, you cannot clone the Flutter repo and then launch these apps from Android Studio. You need to run `flutter run` first to have the `GeneratedPluginRegistrant.java`... well, generated. Similarly for direct Xcode launches on iOS.

It is also slightly controversial to have untracked source files like this in a source folder. In fact, I believe the intention from early Spring was to remove them from `.gitignore` instead, and have people check them in along with `pubspec.yaml`, `pubspec.lock`, and `Podfile.lock`, as these all tend to change together. Can't find the issue right now though.

**Comment by mravn-google** [comment]
Alternatively, we should generate the plugin registrant files as part of `flutter packages get` which I guess people also need to run between cloning the repo and the first launch from an IDE.

**Comment by mit-mit** [comment]
I really like that idea. 'package get' is logically 'get dependencies' and the generated registration code is logically in that category.

**Comment by Hixie** [comment]
We should either remove these files from the repo, or add a test that verifies that the files are up to date. We keep accidentally not updating them.

I don't understand why launching from an IDE can't also generate these files. It compiles the Dart code, right? Why can't it also do `pub get` and generate these files, just like `flutter run`?

**Comment by goderbauer** [comment]
And if they need to be in the repo can we remove their entry from the .gitignore?

**Comment by goderbauer** [comment]
Closing this because https://github.com/flutter/flutter/pull/13541 is submitted as a work-around.

Discussion can continue in https://github.com/flutter/flutter/issues/13554.

**Pull request closed without merging**
