### PR TITLE
[WIP] Allow for Custom Margin in  Vertical Stepper Widget

### LINKED ISSUE #50635: [STEPPER] Need to custom margin on vertical stepper
Hello Flutter Team,

I realy need this mini evolution to make beautifuler app

## Proposal
Widget : Stepper
Proposal : be able to custom the margin for vertical stepper

In `stepper.dart`, the margin is hard set.
channel beta, line 552
```
            margin: const EdgeInsetsDirectional.only(
              start: 60.0,
              end: 24.0,
              bottom: 24.0,
```
 We need to be able to send our custom margin.
It seems  very simple with an additional parameter for the widget

Thank you flutter

### PR DESCRIPTION
**Pull request by maschad**
## Description

Allow users to set custom margins on the vertical stepper as a hard-coded margin is currently set.

## Related Issues

This addresses.
Fixes #50635 

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behaviour with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by QuentinSc** [comment]
Hello,
thank you for this work.
When I created the proposal I wanted to be able to custom the margin when calling the Stepper constructor.

More like this :
- add " ```
this.margin = const EdgeInsetsDirectional.only(
          start: 60.0, end: 24.0, bottom: 24.0)"
``` in constructor
-and so declare the parameter in the class `
  final EdgeInsetsGeometry margin;`

What do you think of my vision ?

**Comment by maschad** [comment]
@QuentinSc right, I was originally trying to initialize it as an optional named parameter but I understand more clearly what you want now. I have added it to the `Stepper` constructor instead

**Comment by proninyaroslav** [comment]
@maschad 
Why is there no further progress?

**Comment by maschad** [comment]
@proninyaroslav I am still unsure which solution is best, my second opinion or @QuentinSc 's. What do you think?

**Comment by proninyaroslav** [comment]
@maschad 
Your option seems more flexible.

**Pull request closed without merging**
