### PR TITLE
Update Material tokens to v0.81.

### PR DESCRIPTION
**Pull request by darrenaustin**
- Updated the Material Design tokens to v0.81.
- Removed some unused token files for Floating Action Button.
- Cleaned up base template class and its utility methods.

### CODE REVIEW

**Review by rami-a — APPROVED** [review]
LGTM

**Review by HansMuller — COMMENTED** [review]
LGTM

**Review by guidezpl — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
Please rebase onto https://github.com/flutter/flutter/pull/98166 to fix plugin_lint_mac.

**Comment by darrenaustin** [comment]
> Please rebase onto #98166 to fix plugin_lint_mac.

Thanks, I thought I had picked it up, but apparently I just missed it. I'll rebase again.

**Comment by jmagman** [comment]
> > Please rebase onto #98166 to fix plugin_lint_mac.
> 
> Thanks, I thought I had picked it up, but apparently I just missed it. I'll rebase again.

Sorry actually it broken again, fix is at https://github.com/flutter/flutter/pull/98171.

**Comment by darrenaustin** [comment]
> Sorry actually it broken again, fix is at #98171.

That would explain why it didn't work for me 😄. I just rebased again and it looks like it is now failing for a new reason. I will pick this up again tomorrow. Thx for following up on this and for the fixes.

**Pull request merged**
