### PR TITLE
Revert "Prevent exception being thrown on hasScrolledBody"

### PR DESCRIPTION
**Pull request by amirh**
Reverts flutter/flutter#31485

Caused a regression that's blocking the roll, see https://github.com/flutter/flutter/issues/34003

### CODE REVIEW

**Comment by amirh** [comment]
@dnfield @Hixie @kpsroka

**Review by dnfield — APPROVED** [review]
LGTM - do you have the failing test?

**Comment by dnfield** [comment]
Nevermind I see it on the issue.

**Comment by kpsroka** [comment]
@amirh Could you please provide a code sample that I could use to reproduce this error? I find it a bit strange that though the PR fixes some of the publicly listed bugs, it gets reverted because of an internal test that is not reproducible in public. Could it be that the reverted PR actually shows a problem in the testing infrastructure, rather than is being a cause of an error?

**Pull request merged**
