### PR TITLE
[testing] Make the FLUTTER_STORAGE_BASE_URL warning non-fatal

### PR DESCRIPTION
**Pull request by whesse**
Presubmit testing and CI testing of Flutter using a custom storage location for engine artifacts must be able to use the --fatal-warnings flag without failing due to the custom artifact location.

This change adds an option that makes this warning non-fatal. The new --no-fatal-storage-url-warning flag makes the --fatal-warnings flag ignore the warning that a custom artifact download URL is being used by setting the environment variable FLUTTER_STORAGE_BASE_URL.

Bug: #127683

## Pre-launch Checklist

- [X ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X ] I signed the [CLA].
- [X ] I listed at least one issue that this PR fixes in the description above.
- [X ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by christopherfujino** [comment]
Could you add a test to https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/runner/flutter_command_test.dart that verifies adding the flag at the top level successfully modifies the `Cache.fatalStorageWarning` field?

**Comment by christopherfujino** [comment]
> Yes, will add the test. Are you saying that we should use this approach, with a flag, and drop the other PR that unconditionally suppresses the failure?

Yes please :)

**Comment by whesse** [comment]
Removed the top-level option, as suggested.  There is no longer a top-level option to test.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
