### PR TITLE
Contributing to 145599 draft-1

### PR DESCRIPTION
**Pull request by Dimilkalathiya**
Contributes toward fixing #145599 

Proposal for fixing  #145599 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by Dimilkalathiya** [comment]
@polina-c Would this approach be viable? it seems be passing with `flutter/test/cupertino/tab_scaffold_test.dart`

of-course there are some improvement that needs to be done like using `unmount` instead of `mount` (which for some reasons throws errors) and implementing proper `dispose` function on ImageProvider instead of using `evict` which causes image to be removed from cache as-well instead of just disposing.

but i was wondering if it is right approach? or should i look for other ways to solve this? some hints would much appreciated :)

i think i might be going bit on lower level apis than needed because running and checking condition each time when widgets get unmounted just for image disposal doesn't sound efficient

but i would like to know what do you thing about this? should i put some effort on it or look for (hopefully) better solution

**Comment by polina-c** [comment]
Thanks for putting it together. 

I am not deep specialist in this area. 

But I know that image cache counts reference somehow to detect if image is ready to be removed from the cache.
If you evict every image immediately after use, image cache will stop functioning as designed. So, it does not seem to be a right way. And I do not know what is right way.

**Comment by Dimilkalathiya** [comment]
Ok thanks for the review

I'll look around on the caching mechanism in depth to see what we can do and maybe ask some advice regarding this on the discord server and my connection.

I may and may not have picked up a bit of a complicated issue for my second PR :)

But I'll see what we can do and probably try again with another draft (might take some time)

**Comment by polina-c** [comment]
nope, it should be dropped

**Pull request closed without merging**
