### PR TITLE
fix reentrant locking in pub upgrade

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
@tvolkert @devoncarew 

Feel free to check this in if it has an LGTM and travis is green, I'm going to lunch. :-)

**Comment by devoncarew** [comment]
lgtm

**Comment by Hixie** [comment]
@tvolkert Apparently this may also be an issue with `flutter build ios`, because xcode re-entrantly calls flutter. I haven't fixed that yet.

**Comment by tvolkert** [comment]
FYI, `flutter upgrade` still hangs on `Waiting to be able to obtain lock of Flutter binary artifacts directory...` on both Mac and Linux

```
> flutter upgrade 
Downloading Dart SDK 1.17.1...
######################################################################## 100.0%
Building flutter tool...
A transformer imported unknown package "drudge" (in "package:drudge/drudge.dart").
Downloading Material fonts...                        0.8s
Downloading package sky_engine...                    2.0s
Downloading package sky_services...                  0.3s
Downloading engine artifacts android-arm...          2.1s
Downloading engine artifacts android-arm-profile...  1.9s
Downloading engine artifacts android-arm-release...  1.6s
Downloading engine artifacts android-x64...          1.8s
Downloading engine artifacts android-x86...          1.4s
Downloading engine artifacts ios...                  1.5s
Downloading engine artifacts ios-profile...          1.3s
Downloading engine artifacts ios-release...          1.4s
Downloading darwin-x64 tools...                      1.5s
Downloading android-arm-profile/darwin-x64 tools...  0.7s
Downloading android-arm-release/darwin-x64 tools...  0.7s
Upgrading Flutter from /Users/tvolkert/project/flutter/flutter...
Already up-to-date.

Upgrading engine...
Waiting to be able to obtain lock of Flutter binary artifacts directory...
```

**Comment by Hixie** [comment]
Yeah, I had a trailing semicolon.

I have a fix for upgrade and build ios.

**Pull request merged**
