### PR TITLE
Update BorderRadius parameter and change it with BorderRadiusGeometry in OutlinedBorder subclasses 

### LINKED ISSUE #70313: RoundedRectangleBorder.copyWith takes a BorderRadius rather than the constructors BorderRadiusGeometry
Is there a reason that the `copyWith` method of `RoundedRectangleBorder` takes a `BorderRadius`, when the class constructor takes a `BorderRadiusGeometry`? I'm trying to implement a variant of the class, so thought I'd check to see that I'm not misunderstanding something.

https://github.com/flutter/flutter/blob/8874f21e79d7ec66d0457c7ab338348e31b17f1d/packages/flutter/lib/src/painting/rounded_rectangle_border.dart#L39-L40

https://github.com/flutter/flutter/blob/8874f21e79d7ec66d0457c7ab338348e31b17f1d/packages/flutter/lib/src/painting/rounded_rectangle_border.dart#L96-L101

### PR DESCRIPTION
**Pull request by payam-zahedi**
## Description
Update the BorderRadius parameter and change it with BorderRadiusGeometry in OutlinedBorder subclasses.

## Related Issues
Fixes https://github.com/flutter/flutter/issues/70313

### CODE REVIEW

**Comment by payam-zahedi** [comment]
> @googlebot I signed it!

**Review by HansMuller — COMMENTED** [review]
Thanks for the contribution.

This PR will need tests for each of the updated border types.

**Comment by payam-zahedi** [comment]
> This PR will need tests for each of the updated border types.
thanks @HansMuller  should I test anything or run tests on my machine?

**Comment by HansMuller** [comment]
Tests (with Directionality widgets) needed to be added to packages/flutter/test/painting - beveled_rectangle_border_test.dart, continuous_rectangle_border_test.dart, rounded_rectangle_border_test.dart -  to check that we're handling the BorderRadiusGeometry parameters correctly.

**Comment by payam-zahedi** [comment]
@HansMuller , thanks for your response. this is my first PR and I'm new to contribute to flutter. Can you please explain more about how to write the tests? and how should I use the Directionality Widget?

**Comment by payam-zahedi** [comment]
@HansMuller Can you please help?

**Review by Piinks — COMMENTED** [review]
Hi @payam-zahedi would you like to continue with this change? There are merge conflicts that will need to be resolved, and there are still tests missing. In order to test this change you should make use of each of these functions you are changing with the new parameter type.

**Comment by payam-zahedi** [comment]
Hi @Piinks, thanks for your response. This PR has not changed for a while. I will check my code and will update this PR.

**Pull request closed without merging**
