### PR TITLE
Re-enable coverage and docs uploading

### LINKED ISSUE #10940: Travis hangs while downloading from dl.google.com
Travis builds are [broken](https://travis-ci.org/flutter/flutter/builds/246067983) due to the setup step failing [when we try to download the Google Cloud SDK](https://github.com/flutter/flutter/blob/be99a04dacc2ac77b445aff54df225c4cf951076/dev/bots/travis_setup.sh#L10).

### PR DESCRIPTION
**Pull request by tvolkert**
Fixes #10940

### CODE REVIEW

**Comment by Hixie** [comment]
So the theory here is that we will _always_ download the Cloud SDK, even if we don't need it, so that we can notice this kind of problem sooner?

**Comment by tvolkert** [comment]
Naah the theory was that I wanted to see if the problem was resolved (since the DL SRE said they couldn't see any issues on their side) in my PR before I merged.  If they were, then I'd update it to only run on non-PRs and merge it.

Though there certainly is an argument to be made for doing this always so we see it earlier...

**Comment by tvolkert** [comment]
Given that the download shouldn't take long, I did remove the PR restriction so we'll catch download errors earlier.

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
That's really weird. It worked fine in the PR, but failed on master.

**Pull request merged**
