### PR TITLE
fix a ListWheelScrollView childDelegate update bug

### LINKED ISSUE #22999: CupertinoPicker refresh data not working
`CupertinoPicker` widget is not refreshed when you change his `childCount`, if you put initial data no problem, but all data added after first build is not visible.
 
To reproduce: 
```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new CupertinoApp(
      title: 'Flutter Demo',
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var _devices = [];
  @override
  Widget build(BuildContext context) {
    print('build! ${_devices.length}');
    return new CupertinoPageScaffold(

      navigationBar: CupertinoNavigationBar(
        middle: Text(widget.title),
      ),
      child: Column(
        children: <Widget>[
          Container(
            height: 300.0,
            child: CupertinoPicker.builder(
                itemExtent: 40.0,
                onSelectedItemChanged: (index) {
                  print(index);
                },
                itemBuilder: (context, index) {
                  print('itemBuilder');
                  return Center(
                    child: Text(
                      'item :'+_devices[index],
                      maxLines: 1,
                      overflow: TextOverflow.fade,
                      textAlign: TextAlign.center,
                    ),
                  );
                },
                childCount: _devices.length),
          ),
          CupertinoButton(child: Text('add'),onPressed: () {
            setState(() {
              _devices.add("test");
            });
          },)
        ],
      ),
    );
  }
}
```

Flutter doctor:
```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.13.6 17G65, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
[✓] Connected devices (1 available)

```

### LINKED ISSUE #58144: ListWheelScrollView.useDelegate   dynamic change childcount not work
```
class Test extends StatefulWidget {
  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> {
  int count = 10;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("test"),
        ),
        body: Column(
          children: <Widget>[
            FlatButton(
              child: Text("测试选择"),
              onPressed: () {
                setState(() {
                  if(count == 10){
                    count = 5;
                  }else{
                    count = 10;
                  }
                });
              },
            ),
            Container(
              height: 450,
              child: ListWheelScrollView.useDelegate(
                itemExtent: 40,
                childDelegate: ListWheelChildBuilderDelegate(
                    childCount: count,
                    builder: (context,index){
                      return Text("$index");
                    }
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}
```
first ，the list  shows 0,1,2,3,4,5,6,7,8,9.
then，i click the button，the list  shows 0,1,2,3,4
but，when i click the button again，i want to see that list shows 0,1,2,3,4,5,6,7,8,9。but it not changed。

the flutter version is 1.14.6

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes #58144
Fixes #22999
 We should mark the render object dirty after changing the child delegate.

### CODE REVIEW

**Review by shihaohong — COMMENTED** [review]
Nice, thanks for the fix and test. Could you add one more test for `CupertinoPicker` as well? This is just to verify that the behavior is really fixed and also prevent future regressions.

**Comment by skia-gold** [comment]
Gold has detected about 1 untriaged digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/81184

**Comment by skia-gold** [comment]
Gold has detected about 1 untriaged digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/81184

**Comment by skia-gold** [comment]
Gold has detected about 1 untriaged digest(s) on patchset 5.
View them at https://flutter-gold.skia.org/cl/github/81184

**Comment by xu-baolin** [comment]
> Golden file changes have been found for this pull request. Click [here to view and triage](https://flutter-gold.skia.org/search?issue=81184&new_clstore=true) (e.g. because this is an intentional change).
> 
> If you are still iterating on this change and are not ready to resolve the images on the Flutter Gold dashboard, consider marking this PR as a draft pull request above. You will still be able to view image results on the dashboard, commenting will be silenced, and the check will not try to resolve itself until marked ready for review.
> 
> For more guidance, visit [Writing a golden file test for `package:flutter`](https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter).
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.
> 
> _Changes reported for pull request #81184 at sha [d2f317e](https://github.com/flutter/flutter/commit/d2f317effdb308f23d697c9f92675f6d5f210167)_

I did not add any golden test 😢

**Comment by goderbauer** [comment]
@Piinks Do you know what gold is complaining about here? The diff looks empty...

**Comment by xu-baolin** [comment]
I guess it was introduced by this [commit](https://github.com/flutter/flutter/blob/12a5fe9db1aa792ee5ce360315ab7dea9b414e43/packages/flutter/test/cupertino/picker_test.dart#L97), @Piinks FYI

**Comment by xu-baolin** [comment]
Continue with #82675

**Pull request closed without merging**
