### PR TITLE
Migrate mac builds to ruby dep.

### PR DESCRIPTION
**Pull request by godofredoc**
The ruby dependency has been automated to include cocoapods.

Bug: https://github.com/flutter/flutter/issues/136377

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by vashworth — APPROVED** [review]
LGTM

I confirmed https://github.com/flutter/flutter/issues/132755 is no longer an issue with new version of cocoapods (There are no `replacing:` logs): https://chromium-swarm.appspot.com/task?id=657738f3d3a4cd10

**Comment by godofredoc** [comment]
@vashworth @christopherfujino @cbracken please let me know if you have concerns about landing this change.

**Comment by godofredoc** [comment]
> LGTM
> 
> I confirmed #132755 is no longer an issue with new version of cocoapods (There are no `replacing:` logs): https://chromium-swarm.appspot.com/task?id=657738f3d3a4cd10

Thank you @vashworth

**Comment by Naimishimaker** [comment]
which ruby version is accept flutter for ios setup?

**Pull request merged**
