### PR TITLE
ignore the ios dir in examples

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
cc @Hixie @abarth

**Comment by abarth** [comment]
LGTM

**Comment by eseidelGoogle** [comment]
Why is there an ios/ dir at the top level of the examples/?  Each individual example will want to check in their ios/ dir.

**Comment by abarth** [comment]
gitignore files inhert.  This says to ignore every ios directory in every subdirectory of this directory.

**Comment by eseidelGoogle** [comment]
That seems wrong then.  You'll want the ios/ dir checked in for all the examples.  That's where the ios icons will go, etc.  Part of solving https://github.com/flutter/flutter/issues/1066 @chinmaygarde

**Comment by abarth** [comment]
We need to cleanly divide the parts of the xcodeproj that are controlled by the author and the parts that are controlled by the flutter tool.  The former should not be git ignored whereas the latter should.

**Comment by chinmaygarde** [comment]
I am in the process of doing this right now since we were having trouble upgrading the project with each engine rev while still keeping around the user edits to the Xcode project (https://github.com/flutter/flutter/issues/1411#issuecomment-175836456)

not-lgtm on this patch since we want the ios directory to stick around. The tool will create the Xcode project as needed outside the project directory

**Pull request merged**
