### PR TITLE
Be more verbose on bots when running 'pub'

### LINKED ISSUE #9237: Add a flag to flutter to run pub get/upgrade w/ --verbose
This new flag can be used on bots to better debug issues accessing pub

CC @Hixie 

See https://github.com/dart-lang/pub-dartlang-dart/issues/94

### PR DESCRIPTION
**Pull request by Hixie**
Fixes https://github.com/flutter/flutter/issues/9237

### CODE REVIEW

**Review by kevmoo — APPROVED** [review]
there are a lot of `final` and unnecessary types everywhere.

...and the lines are long

otherwise, LGTM 😉

**Comment by Hixie** [comment]
The finals are there to catch cases where we accidentally change a variable we didn't meant to change.
The types are there to catch cases where we assign the variable a value that is not the type we meant to give.
The lines, though, they are indeed too long. Will fix...

**Comment by Hixie** [comment]
There's a bigger problem though. The logs are so verbose that Travis killed the job for having too much log output. :-(

Is there an in-between stage where we can have useful output for you but not overload the bots?

**Comment by kevmoo** [comment]
> Is there an in-between stage where we can have useful output for you but not overload the bots?

Nope. Crap. You might have to buffer the output and only print if there is an error...

Maybe?...

**Comment by Hixie** [comment]
I'm going to close this PR since this approach won't work.

**Pull request closed without merging**
