### PR TITLE
Improve tracing and fix packages_autoroller

### PR DESCRIPTION
**Pull request by christopherfujino**
Reverts flutter/flutter#154555
Re-lands of https://github.com/flutter/flutter/pull/154441 and https://github.com/flutter/flutter/pull/154369

New changes in this PR:

1. extend timeout of the `Linux packages_autoroller` shard (see step 14 in this example [LED build](https://ci.chromium.org/ui/p/flutter/builders/prod.shadow/Linux%20packages_autoroller/7/infra))
2. use the managed framework repo as the working directory in the `framework.streamDart()` helper function--we were generating gradle lockfiles in the wrong directory

A LED build with this code generated the following gradle lockfile update: https://github.com/flutter/flutter/pull/154859/commits/d939981cd21afd4151775fab5f5863a2e64f1b5c

### CODE REVIEW

**Comment by christopherfujino** [comment]
A LED test of this PR is this build: https://ci.chromium.org/ui/p/flutter/builders/prod.shadow/Linux%20packages_autoroller/6/infra

(which says `No diff after calling generate_gradle_lockfiles.dart`, which seems impossible)

Which opened this PR: https://github.com/flutter/flutter/pull/154852/files

**Comment by christopherfujino** [comment]
Ok, one  more fix commit, and another LED build: https://ci.chromium.org/ui/p/flutter/builders/prod.shadow/Linux%20packages_autoroller/7/infra

**Comment by christopherfujino** [comment]
> Ok, one more fix commit, and another LED build: https://ci.chromium.org/ui/p/flutter/builders/prod.shadow/Linux%20packages_autoroller/7/infra

This succeeded, and successfully created a roll with gradle lockfiles: https://github.com/flutter/flutter/pull/154859 (it also has all the code changes from this PR, so I will not merge it).

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
