### PR TITLE
Allow multiple FloatingActionButtons to be used on one screen.

### PR DESCRIPTION
**Pull request by Hixie**
* Allow FloatingActionButton to not have a heroTag.
* Allow FloatingActionButton to not have a child.
* Allow Tooltip to not have a child.
* Improve the debug output of the default FloatingActionButton hero tag.
* Improve the error message in the Hero clashing-tag case.
* Improve the debug output of the Hero widget.
* Improve the debug output of gesture-related widgets.
* Minor improvements to documentation.
* Fix some typos in comments.
* Fix some style nits.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @goderbauer

**Comment by goderbauer** [comment]
LGTM

What about some tests (e.g. to make sure that having multiple FloatingActionButtons doesn't break in the future)?

**Comment by Hixie** [comment]
Oh, testing with multiple FABs is a good idea.

**Comment by Hixie** [comment]
Added some tests for the FAB. Will land on green unless I hear otherwise.

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
