### PR TITLE
Update IntelliJ template for new projects and existing samples

### LINKED ISSUE #630: Project view shows many files that first-time users may be confused about
First-time users will likely try to make sense of each and every entry shown in the Project view. Thus it's important this only contains things they actually need to worry about.

I think we should be hiding the following:

1. `.idea` dir: IDE settings that are typically edited using the IJ UI itself
1. `.iml` file: Same as above
1. `.packages` file: Generated pub artefact
1. `pubspec.lock` file: Generated pub artefact

Additionally, the Dart plugin will automatically hide these:
1. `.pub` dir: The local pub cache, not for editing
1. `build` dir: build outputs, not a source artefact

### LINKED ISSUE #632: Migrate IML files to the .idea directory.
... rather than in the project root.  This will allow us to easily hide it in the explorer.  More context in https://github.com/flutter/flutter-intellij/issues/630.

### PR DESCRIPTION
**Pull request by mit-mit**
* Hide folders from Project View users shouldn't worry about: Fixes https://github.com/flutter/flutter-intellij/issues/630

* Move `.iml` into `.idea` as the user shouldn't worry about it: Fixes https://github.com/flutter/flutter-intellij/issues/632

* Add `workspace.xml` to existing examples: Followup to previous PR https://github.com/flutter/flutter/pull/7464

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by devoncarew** [comment]
I don't think we want to commit the workspace.xml file (examples/hello_services/.idea/workspace.xml) for projects other than the create template. I think that file contains settings that are more per-user specific - having it in source control would mean that you would pick up other users local settings changes, and there'd likely be a bunch of scm churn in that file. We do want files like `.idea/modules`, which more define the project. https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems has a bit more info.

Priming `workspace.xml` for the create template however makes sense.

lgtm for the other changes -

**Comment by mit-mit** [comment]
> I don't think we want to commit the workspace.xml file 

OK, that makes sense. Updated the PR to not add those.

**Review by devoncarew — APPROVED** [review]

**Comment by mit-mit** [comment]
Still can't land this as the Travis job is timing out (unrelated to this change, I believe):

```
Shell: Observatory listening on http://127.0.0.1:25446/
19:33 +814 ~2 -1: loading /home/travis/build/flutter/flutter/packages/flutter/test/widgets/unique_widget_test.dart
  TimeoutException after 0:05:00.000000: Test timed out after 5 minutes, 5 seconds.
  dart:isolate  _RawReceivePortImpl._handleMessage
```

**Comment by Hixie** [comment]
I don't understand why Travis did a push test on a PR.

**Comment by Hixie** [comment]
In any case the problem seems to be that this branch is old. You should rebase so Travis tests it against the latest test code, where I believe that race has been fixed.

**Comment by mit-mit** [comment]
> In any case the problem seems to be that this branch is old. 

Ah, of course, will do that right away, thanks!

**Comment by Hixie** [comment]
Minor side note, it looks like what happened is that you checked these changes into a branch on the Flutter repo. The preferred approach is to check them into branches on your own fork of the repo. That way people don't end up pulling down your branch when they're fetching the main repo.

**Comment by mit-mit** [comment]
> The preferred approach is to check them into branches on your own fork of the repo. 

Got it, will do in the future!

**Pull request merged**
