### PR TITLE
add microbenchmark for platform channels

### PR DESCRIPTION
**Pull request by gaaclarke**
## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
Hey @dnfield I can't get these tests working with the microbenchmarks test harness.  The channels to the plugin aren't connecting.  I just get "null" as the result from the `send` call (the same thing that would happen if I talk to some random channel name).  If I run the test in a separate project everything runs fine.  Do you know what is going on?  It doesn't work for android or iOS?

**Comment by dnfield** [comment]
I'm not quite sure, but this PR might be simpler if you just created the channel in the existing iOS/Android code in the app, rather than as a plugin.

**Comment by dnfield** [comment]
The app looks like it's missing a generated plugin registrant, and missing some stock Android code - I'm not quite sure what's going on with that, but maybe it's not loading plugins correctly.

At any rate, I'd still think it's simpler to just create the Android activity code in here and set up your message channel in there without adding a new plugin to the repo.

**Comment by gaaclarke** [comment]
@dnfield Thanks for taking a look.  It does have the generated plugin code, it might be gitignored since it's generated.  Good call on just making the channels directly without a plugin.  I'll give that a shot before I give up and just make my own test harness.

Screen Shot 2021-04-28 at 11 35 38 AM

**Comment by gaaclarke** [comment]
Abandoned, going with the approach in https://github.com/flutter/flutter/pull/81414, it's much easier.  It has its own test harness and does what Dan suggested, eliminating the plugin.

**Pull request closed without merging**
