### PR TITLE
apply upcoming rule use_collection_literals_when_possible

### PR DESCRIPTION
**Pull request by a14n**
[Effective Dart: DO use collection literals when possible](https://www.dartlang.org/guides/language/effective-dart/usage#do-use-collection-literals-when-possible)

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM. this is great.

**Comment by a14n** [comment]
@Hixie I don't have merge permission. Could you process it (and my 2 other open PRs with LGTM) ?

**Comment by a14n** [comment]
@Hixie  thanks :)

**Comment by Hixie** [comment]
You should now have commit access, too. Please use your newfound powers responsibly. :-)
In particular you should make sure you've read these documents:
https://flutter.io/design-principles/ (including the code of conduct)
https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo

**Comment by a14n** [comment]
Thanks. With great powers come great responsibility :)

**Pull request merged**
