### PR TITLE
Revert "Re-land "Migrate some benchmarks to NNBD (75023)" "

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#75265

```
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [  +41 ms]   package:flutter_driver/src/driver/vmservice_driver.dart 331:33  VMServiceFlutterDriver.sendCommand
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1294:19                                    _CustomZone.registerBinaryCallback
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async-patch/async_patch.dart 51:8                          _asyncErrorWrapperHelper
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart                       Invoker.waitForOutstandingCallbacks.<fn>
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                    _rootRun
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                    _CustomZone.run
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1789:10                                    _runZoned
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1711:10                                    runZoned
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 228:5                 Invoker.waitForOutstandingCallbacks
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 383:17                Invoker._onRun.<fn>.<fn>.<fn>
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1286:19                                    _CustomZone.registerUnaryCallback
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async-patch/async_patch.dart 40:23                         _asyncThenWrapperHelper
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart                       Invoker._onRun.<fn>.<fn>.<fn>
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                    _rootRun
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                    _CustomZone.run
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1789:10                                    _runZoned
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1711:10                                    runZoned
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 370:9                 Invoker._onRun.<fn>.<fn>
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 415:15                Invoker._guardIfGuarded
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 369:7                 Invoker._onRun.<fn>
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   package:stack_trace/src/chain.dart 94:24                        Chain.capture.<fn>
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                    _rootRun
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                    _CustomZone.run
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1789:10                                    _runZoned
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1711:10                                    runZoned
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   package:stack_trace/src/chain.dart 92:12                        Chain.capture
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 368:11                Invoker._onRun
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/live_test_controller.dart 153:11   LiveTestController.run
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/future.dart 198:37                                   new Future.microtask.<fn>
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1346:47                                    _rootRun
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                    _CustomZone.run
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1162:7                                     _CustomZone.runGuarded
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1202:23                                    _CustomZone.bindCallbackGuarded.<fn>
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                    _rootRun
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                    _CustomZone.run
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1162:7                                     _CustomZone.runGuarded
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1202:23                                    _CustomZone.bindCallbackGuarded.<fn>
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/schedule_microtask.dart 40:21                        _microtaskLoop
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/schedule_microtask.dart 49:5                         _startMicrotaskLoop
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/isolate_patch.dart 120:13                    _runPendingImmediateCallback
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/timer_impl.dart 402:11                       _Timer._runTimers
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/timer_impl.dart 426:5                        _Timer._handleMessage
[platform_views_scroll_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/isolate_patch.dart 184:12                    _RawReceivePortImpl._handleMessage
```

### CODE REVIEW

**Review by dnfield — APPROVED** [review]

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by shihaohong** [comment]
Merging on red to partially fix the tree. Seems like `framework_tests-misc-linux` is failing for a different reason though (https://github.com/flutter/flutter/pull/75317), but that's because this PR doesn't include that commit

**Comment by goderbauer** [comment]
Here are the fixes in flutter_driver to fix this crash: https://github.com/flutter/flutter/pull/75343. Once it is applied, I will reland this PR.

**Pull request merged**
