### PR TITLE
improvement : removed required  kotlin dependency

### LINKED ISSUE #98212: [Android] Kotlin support library dependency no longer required
At the moment, all Flutter Android Kotlin templates contain a dependency on the Kotlin support library. E.g.:
https://github.com/flutter/flutter/blob/0e2f51dfd04eca2935318389a75e8bc112809342/packages/flutter_tools/templates/app_shared/android-kotlin.tmpl/app/build.gradle.tmpl#L67-L69

Starting from Kotlin 1.4, the Kotlin Gradle plugin adds the dependency on the standard library automatically by default: ([ref](https://kotlinlang.org/docs/whatsnew14.html#dependency-on-the-standard-library-added-by-default))

> You no longer need to declare a dependency on the stdlib library in any Kotlin Gradle project, including a multiplatform one. The dependency is added by default.
> 
> The automatically added standard library will be the same version of the Kotlin Gradle plugin, since they have the same versioning.
> 
> For platform-specific source sets, the corresponding platform-specific variant of the library is used, while a common standard library is added to the rest. The Kotlin Gradle plugin will select the appropriate JVM standard library depending on the kotlinOptions.jvmTarget compiler option of your Gradle build script.

The current Kotlin version in the templates is 1.6.10:
https://github.com/flutter/flutter/blob/1bfb7400c8ce546fd19ffd93b458ded583d9ada5/packages/flutter_tools/lib/src/android/gradle_utils.dart#L32

So the explicit dependency to the Kotlin support library dependency is no longer required.

### PR DESCRIPTION
**Pull request by albertoazinar**
This PR removed the non-necessary required Koltin dependency. This is because the Kotlin Gradle adds the dependency on the standard library automatically. 

Fixes #98212

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy]. *

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by andrewkolos — APPROVED** [review]
LGTM. I will wait for a second review from @christopherfujino before asking for a test exemption.

**Comment by christopherfujino** [comment]
@reidbaker can you give final approval on this one?

**Comment by reidbaker** [comment]
Before we can approve we need the CLA signed for all contributors. 

For context starting at [this commit](https://github.com/flutter/flutter/blame/b3814c7ff04a0a2133a214144a99a0bc38df186e/packages/flutter_tools/lib/src/android/gradle_utils.dart#L33) ~2 years ago we default to a version of kotlin that according to the linked documentation does not need the template version.

**Review by reidbaker — CHANGES_REQUESTED** [review]
Need cla

**Review by reidbaker — APPROVED** [review]

**Comment by albertoazinar** [comment]
Hello @christopherfujino and @reidbaker 
Is there something else I need to do?

**Comment by albertoazinar** [comment]
> > Hello @christopherfujino and @reidbaker
> > Is there something else I need to do?
> 
> I don't think so auto submit should run when the tree is green

Understood.
Thank you @reidbaker

**Comment by reidbaker** [comment]
> > > Hello @christopherfujino and @reidbaker
> > > Is there something else I need to do?
> > 
> > 
> > I don't think so auto submit should run when the tree is green
> 
> Understood. Thank you @reidbaker

Google testing state was stuck. Updated https://github.com/flutter/flutter/issues/125994 where this happened to another teammate and manually set the status.

**Comment by albertoazinar** [comment]
> > > > Hello @christopherfujino and @reidbaker
> > > > Is there something else I need to do?
> > > 
> > > 
> > > I don't think so auto submit should run when the tree is green
> > 
> > 
> > Understood. Thank you @reidbaker
> 
> Google testing state was stuck. Updated #125994 where this happened to another teammate and manually set the status.

Understood. thanks for your collaboration! @christopherfujino and @reidbaker

**Pull request merged**
