### PR TITLE
[cupertino/icons.dart] Replace ligature references with codepoints for dartdoc

### PR DESCRIPTION
**Pull request by victorsanni**
Part of #148075

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by matanlurey** [comment]
The file says "BEGIN GENERATED SF SYMBOLS NAMES", but I don't see any changes to the generator - so how were these changes made?

**Comment by victorsanni** [comment]
> The file says "BEGIN GENERATED SF SYMBOLS NAMES", but I don't see any changes to a generator - so how were these changes made?

Ah yes. I'll link the original issues in the description for more context. But the tldr is: We currently generate this file locally from this repo: https://github.com/xster/framework7-icons. This is the first step of many to fix that.

**Comment by matanlurey** [comment]
I would hope we would fix the repo and move the script to this repo _before_ making the code change - is there a reason we can't do that?

**Comment by LongCatIsLooong** [comment]
> I would hope we would fix the repo and move the script to this repo _before_ making the code change - is there a reason we can't do that?

Yeah currenly the `cupertino_icons` is [an asset package](https://github.com/flutter/packages/blob/main/third_party/packages/cupertino_icons/lib/cupertino_icons.dart), moving the dart file to the `cupertino_icons` package will require some additional imports downstream. We're even referring to `CupertinoIcons` names in `flutter/flutter` tests without depending on that package. So I think moving the `CupertinoIcons` class to a package is going to be a breaking change. 

Also the priority of the ligature table removal has changed. @victorsanni is working on porting the python scripts to dart, based on some initial assessments it will be a non-trivial effort to keep maintaining the ligature table so we'd like to remove things that currently depend on ligatures.

**Review by LongCatIsLooong — APPROVED** [review]

**Comment by matanlurey** [comment]
Ok so if I understand this correctly, doing this "right" is a breaking change, so we're front-loading making this experience better for our users while we fix our process bits in the background?

test-exempt: Thanks for explaining, the trade-off seems reasonable.

**Pull request merged**
