### PR TITLE
[flutter_tools] restore pub caching functionality

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Necessary to work around #70013 (this looks like it will be fixed, but should protect us in the future)

Restores some notion of skipping pub, with differences from the prior implementation:

Off by default, and only used by the flutter command automatic pub get
A single check parameter
Uses the framework version cached per-project instead of a timestamp of the tool, to avoid cases where downloading a prebuilt framework would cause this check to no longer work.
The caveat with master branch rebuilds is noted.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
(I'm fixing the drive test issue separately)

**Comment by jonahwilliams** [comment]
I think https://github.com/flutter/flutter/pull/70136 will fix this, but will double check before landing

**Review by zanderso — APPROVED** [review]
still lgtm

**Comment by jonahwilliams** [comment]
Added pubspec.lock check (the warning forwarded by the SkSL test) to be sure

**Pull request merged**
