### PR TITLE
re-enable ios_add2app tests

### PR DESCRIPTION
**Pull request by dnfield**
This would have caught the regression fixed in https://github.com/flutter/engine/pull/13062

This can't land until that rolls in.

 If  this causes more problems for your upcoming sharding PR I'm happy to close it.

/cc @kangwang1988

### CODE REVIEW

**Comment by dnfield** [comment]
It would probably be good to have this test upstream in the engine as well.

**Review by gaaclarke — APPROVED** [review]

**Comment by jmagman** [comment]
Did we figure out why it was so flaky?

**Comment by dnfield** [comment]
My theory at this point is that your closed issue fixed the flake.  However, while it was disabled, we introduced some regressions (which are being fixed upstream in the engine).

**Comment by jmagman** [comment]
Seems to still have issues.
https://cirrus-ci.com/task/5037645645742080?command=test_all#L70

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
I'm all for unskipping this shard (and don't hesitate to land it, this is by far the least troubling PR I've seen as far as merge conflicts with my .cirrus.yml PR go). However, we need to fix the bug first. :-)

**Comment by dnfield** [comment]
@hixir the bug is in the engine. Once the fix rolls in this can be rebased

**Comment by dnfield** [comment]
@gaaclarke it looks like we still have a leak.  I'm going to close this since I'll be out, but we should fix the leak and reenable.

**Pull request closed without merging**
