### PR TITLE
[flutter_tools] Fix VersionUpstreamValidator to respect FLUTTER_GIT_URL

### LINKED ISSUE #100604: [tool] `VersionUpstreamValidator` ignores `FLUTTER_GIT_URL` if upstream repository is standard
`VersionUpstreamValidator` was introduced in #97202 to prevent the tool to check for freshness from a different remote than the one used to fetch the updates.

It does that by preventing freshness check and update in case the current channel is tracking a "non-standard remote". An explanation of what is considered as a "standard remote" is provided at the below dartdoc:

https://github.com/flutter/flutter/blob/e827f0b3e121d2e1327bc4222b0ec6ae36e6b777/packages/flutter_tools/lib/src/version.dart#L415-L417

However, it appears that the validator completely ignores `FLUTTER_GIT_URL` in the case reproducible through the following steps:

## Steps to Reproduce

1. Make sure that the current branch/channel is tracking a ***standard remote***, by verifying the output of `flutter doctor -v`:
```sh
[✓] Flutter (Channel master, 2.13.0-0.0.pre.219, on Artix Linux 5.16.14-artix1-1, locale en_IN.UTF-8)
    • Flutter version 2.13.0-0.0.pre.219 at /home/rarg/.local/src/flutter_sdk_master
    • Upstream repository https://github.com/flutter/flutter.git
```

2. Run the following command:
```sh
$ FLUTTER_GIT_URL='' flutter upgrade
```

**Expected results:** 

Since `FLUTTER_GIT_URL` is set to a non-standard url, the upgrade _should_ fail.

**Actual results:** 
The upgrade completes successfully.

**flutter doctor -v**
```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.219, on Artix Linux 5.16.14-artix1-1, locale en_IN.UTF-8)
    • Flutter version 2.13.0-0.0.pre.219 at /home/rarg/.local/src/flutter_sdk_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1d8e30c4b (13 minutes ago), 2022-03-23 14:55:11 +0800
    • Engine revision 4fbff7a511
    • Dart version 2.17.0 (build 2.17.0-227.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /opt/android-sdk
    • Platform android-31, build-tools 29.0.2
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /usr/bin/java
    • Java version openjdk version "11.0.15" 2022-04-19
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.22.3
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Artix Linux 5.16.14-artix1-1
    • Chrome (web)    • chrome • web-javascript • Chromium 99.0.4844.74 Artix Linux

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by royarg02**
Fixes `VersionUpstreamValidator` to always respect `FLUTTER_GIT_URL` for checking whether the current channel tracks a standard remote.

Fixes #100604.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by christopherfujino** [comment]
So, to clarify, this behavior of toolExiting if the user sets FLUTTER_GIT_URL and their current branch is not already tracking is what we already had (because you implemented) before https://github.com/flutter/flutter/pull/97202, correct?

**Comment by RoyARG02** [comment]
> So, to clarify, this behavior of toolExiting if the user sets FLUTTER_GIT_URL and their current branch is not already tracking is what we already had (because you implemented) before #97202, correct?

That would be correct, yes.

**Review by christopherfujino — APPROVED** [review]
LGTM!

**Comment by christopherfujino** [comment]
@Jasguerrero could you take a look at this?

**Review by Jasguerrero — APPROVED** [review]
LGTM

**Pull request merged**
