### PR TITLE
Remove unused `SingleTickerProviderStateMixin` from `AnimatedSize ` example

### LINKED ISSUE #83606: AnimatedSize example unused ticker mixin
After vsync was removed from AnimatedSize widget, this ticker provider became obsolete
https://github.com/flutter/flutter/blob/c42ec8592f9c426cfc3d27a5cd4da3f49f42b396/packages/flutter/lib/src/widgets/animated_size.dart#L19

### PR DESCRIPTION
**Pull request by TahaTesser**
Closes https://github.com/flutter/flutter/issues/83606

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by HansMuller** [comment]
This simple example currently does not run (@gspencergoog - here's an example where we'd be better served by a sample's repo _with tests_ then the current setup) and the proposed fix doesn't correct the problem. It looks like the sample was supposed to include `vsync: this` - https://dartpad.dev/d090f2661622d51387ed2986cca4d943?null_safety=true

**Comment by TahaTesser** [comment]
@HansMuller 
Please see https://github.com/flutter/flutter/pull/82733#issuecomment-842635383 and we also discussed it on Discord 
`vsync: this` is removed in the later channels, but example runs on the `stable`

**Comment by HansMuller** [comment]
The current example in https://api.flutter.dev/flutter/widgets/AnimatedSize-class.html doesn't compile (needs`vsync: this`); that doesn't seem like the right state to leave our public API docs in.

**Comment by gspencergoog** [comment]
Yeah, that's a problem. Something that is hard to do right now is to re-publish the docs without doing a new stable release. I agree that this is a good argument for more tests, but I'm surprised that the current analysis didn't fail: it should have died with "line 57 • The named parameter 'vsync' is required, but there's no corresponding argument."

**Comment by gspencergoog** [comment]
The examples are intended only to run on the version they are published with, so examples in `stable` should work on `stable`, but not necessarily on `master`, and vice versa. The examples are published when the `stable` release is published.  The examples on [https://master-api.flutter.dev](https://master-api.flutter.dev) are published whenever a new commit is made.

**Review by Piinks — APPROVED** [review]
LGTM! Thank you for fixing this.

**Pull request merged**
