### PR TITLE
Remove unnecessary null check from switch

### PR DESCRIPTION
**Pull request by divyanshub024**
Removed all the assert null checks in material/switch.dart

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by xu-baolin** [comment]
Thanks for contributing to the Flutter.
Could you remove all the unnecessary null checks of this file?
I see several points such as `set inactiveTrackColor(Color value)` , `set configuration(ImageConfiguration value)` etc.

**Review by xu-baolin — CHANGES_REQUESTED** [review]
Thanks for contributing to the Flutter.
Could you remove all the unnecessary null checks of this file?
I see several points such as `set inactiveTrackColor(Color value)` , `set configuration(ImageConfiguration value)` etc.

**Comment by divyanshub024** [comment]
@xu-baolin Sorry, I missed those. Let me remove them as well.

**Comment by xu-baolin** [comment]
This seems to break the code style [guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#formatting).

**Comment by divyanshub024** [comment]
@xu-baolin @dkwingsmt Please review the PR, I've made the required changes.

**Comment by dkwingsmt** [comment]
Sorry for failing to reply earlier. For now Flutter is intentionally keeping these null checks in all classes despite the types being non-nullable. This is because many projects still have not enabled non-nullable by default and need these explicit checks. In the future when non-nullable has been widely adopted, the null checks will be cleaned up probably using scripts.

**Pull request closed without merging**
