### PR TITLE
Revert "Add clipBehavior to widgets with clipRect"

### PR DESCRIPTION
**Pull request by mehmetf**
Reverts flutter/flutter#55977

Non trivial breakages in g3.

### CODE REVIEW

**Comment by goderbauer** [comment]
LGTM

/cc @liyuqian FYI

**Comment by iskakaushik** [comment]
This change also causes some breakages in the Fuchsia roll. @liyuqian is it possible to structure this as a soft-transition?

cc: @chaselatta

**Comment by liyuqian** [comment]
It should be possible to have a soft-transition. The old PR was supposed to be non-breaking but clearly I missed something. Can you please attach the failed log here so I can make sure that my next try won't fail on the same test?

**Comment by mehmetf** [comment]
I highly recommend that the revert of this revert be staged to g3 and tested before being merged.

@liyuqian please reach out to @renyou in internal chat to figure out how. We have tools for that kind of thing now :-).

**Comment by iskakaushik** [comment]
This is the failure log on the Fuchsia side: http://shortn/_Gy8PvjWzQG

**Comment by chaselatta** [comment]
The failure on our end came from `overflow` being removed from the `Stack` widget and being replaced with `clipBehavior`. We would need `overflow` to remain until we can migrate our usage to `clipBehavior`

**Pull request merged**
