### PR TITLE
Update engine.version

### PR DESCRIPTION
**Pull request by abarth**

### CODE REVIEW

**Comment by chinmaygarde** [comment]
lgtm

**Comment by abarth** [comment]
pub server is down

**Comment by yjbanov** [comment]
This update seems to have broken the build:

`flutter run --profile --trace-startup`

```
Running lib/main.dart on Nexus 5...
--------- beginning of main
E/FlutterMain: Unable to load Sky Engine binary.
E/FlutterMain: org.chromium.base.library_loader.ProcessInitException
E/FlutterMain: 	at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:262)
E/FlutterMain: 	at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:123)
E/FlutterMain: 	at io.flutter.view.FlutterMain.initNative(FlutterMain.java:369)
E/FlutterMain: 	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:147)
E/FlutterMain: 	at org.domokit.sky.shell.SkyApplication.onCreate(SkyApplication.java:19)
E/FlutterMain: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
E/FlutterMain: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
E/FlutterMain: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
E/FlutterMain: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
E/FlutterMain: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/FlutterMain: 	at android.os.Looper.loop(Looper.java:148)
E/FlutterMain: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E/FlutterMain: 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterMain: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/FlutterMain: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/FlutterMain: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memcpy" referenced by "/data/app/io.flutter.examples.gallery-2/lib/arm/libsky_shell.so"...
```

[build history](https://flutter-dashboard.appspot.com/build.html)

**Comment by abarth** [comment]
`cannot locate symbol "__aeabi_memcpy"`

@chinmaygarde Did you find a fix for this on Friday?

**Comment by chinmaygarde** [comment]
@abarth Sort of. I found a workaround. The issue seems to be related to https://android-review.googlesource.com/#/c/195350/. Using an older version of the NDK fixes the issue. But I haven't quite understood the problem yet. According to the comments in that ticket, an issue like this should not have happened (the bit about leaving them unversioned in `libc.so`). This only happens on M devices (older and newer are fine). If I cant understand this fully, will just use a lower NDK version. Duplicate of https://github.com/flutter/flutter/issues/6149.

**Pull request merged**
