### PR TITLE
Teach flutter to build itself

### PR DESCRIPTION
**Pull request by winksaville**
## Description

Instead of having to delete <flutter src root>/bin/cache/flutter_tools.*
to have flutter rebuild itself add support for "flutter build self".

## Related Issues

None

## Tests

I'm not sure how this should be tested. I'll be glad to add some
if someone can point me to some examples.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [x] Yes, but these are the same failures I see without this PR:

 (py38) wink@wink-desktop:~/prgs/flutter/flutter (Teach-flutter-to-build-itself)
 $ cat ../pub.run.test.Teach-flutter-to-build-itself.E.txt
 00:42 +127 -1: test/commands.shard/hermetic/shell_completion_test.dart: shell_completion generates bash initialization script to stdout [E]
 00:42 +128 -2: test/commands.shard/hermetic/shell_completion_test.dart: shell_completion generates bash initialization script to stdout with arg [E]
 00:42 +128 -3: test/commands.shard/hermetic/shell_completion_test.dart: shell_completion generates bash initialization script to output file [E]
 00:42 +129 -4: test/commands.shard/hermetic/shell_completion_test.dart: shell_completion won't overwrite existing output file  [E]
 00:42 +129 -5: test/commands.shard/hermetic/shell_completion_test.dart: shell_completion will overwrite existing output file if given --overwrite [E]
 01:46 +286 -6: test/commands.shard/permeable/packages_test.dart: packages test/pub test without bot [E]
 01:46 +286 -7: test/commands.shard/permeable/packages_test.dart: packages test/pub test with bot [E]
 01:46 +286 -8: test/commands.shard/permeable/packages_test.dart: packages test/pub run [E]
 05:44 +706 -9: test/general.shard/android/gradle_errors_test.dart: flavor undefined handler - with flavor [E]
 05:44 +706 -10: test/general.shard/android/gradle_errors_test.dart: flavor undefined handler - without flavor [E]
 16:46 +2087 ~11 -11: test/commands.shard/permeable/packages_test.dart: packages test/pub pub publish [E]
 31:46 +2087 ~11 -12: test/commands.shard/permeable/packages_test.dart: packages test/pub pub publish input fails [E]
 31:46 +2087 ~11 -13: test/commands.shard/permeable/packages_test.dart: packages test/pub publish [E]
 31:46 +2087 ~11 -14: test/commands.shard/permeable/packages_test.dart: packages test/pub packages publish [E]
 31:46 +2087 ~11 -15: test/commands.shard/permeable/packages_test.dart: packages test/pub deps [E]
 31:46 +2087 ~11 -16: test/commands.shard/permeable/packages_test.dart: packages test/pub cache [E]
 31:46 +2087 ~11 -17: test/commands.shard/permeable/packages_test.dart: packages test/pub version [E]
 31:46 +2087 ~11 -18: test/commands.shard/permeable/packages_test.dart: packages test/pub uploader [E]
 31:46 +2087 ~11 -19: test/commands.shard/permeable/packages_test.dart: packages test/pub global [E]

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by zanderso** [comment]
I myself would appreciate the improvement in ergonomics for this use-case, but distributing the tool command namespace across the Dart program and the shell script wrappers is likely to create confusion. I will try to think of a suggestion for how to avoid that.

**Comment by winksaville** [comment]
@zanderso, I agree having logic in the shell scripts and having to add build_self.dart to add "help" is not great. If a better solution isn't found, I should probably add a comment/REM in the wrapper scripts pointing out that the "help" for BUILD_SELF is located in packages/flutter_tools/lib/src/commands/build_self.dart.

**Review by dnfield — CHANGES_REQUESTED** [review]
I don't think we should do this.

It's nearly impossible to properly test this on all the platforms and configurations we have to support.  It's touching code that is itself untested.  It also presents greater difficulties if/when we decide to ship the tool as an AOT compiled program.

At any rate, we should absolutely not land this without a test.

**Comment by winksaville** [comment]
The change it emits some help text, adds one boolean and 5 boolean expressions of which 3 are evaluted everytime "flutter" is executed. If some one can point me to the current tests of <src_root>/bin/flutter and <src_root>/bin/flutter.bat I'll try to add tests which cover all of the code paths affected.

If there are no tests please give me some guidance on where you'd like them to live and I'll try create some.

**Comment by jonahwilliams** [comment]
Hi @winksaville , having an easy way to rebuild the tool is certainly useful, however most of the functionality of the tool needs to be focused on Flutter developers and not necessarily Flutter contributors. If we added this we would risk it breaking developers' checkouts if they used it accidentally/incorrectly. It might also not work if we change how the tool is built on release branches in the future (using dart2native, for example).

It would be worth opening an issue to track the addition of a separate flutter-dev tool which could contains scripts like this. I'd be happy to do this for you if you'd like, but I'd appreciate your feedback on it ay any rate.

Sorry that we didn't get back to you on this sooner

**Comment by dnfield** [comment]
FWIW, I have a bash-alias called `rm-fluttertool` that just deletes the snapshot, which basically achieves this.

**Comment by winksaville** [comment]
Thanks for considering this PR. But I'd like to try one more time. How about [this WiP](https://github.com/winksaville/flutter/commit/a97a080de7c93226e54d459a0317fe21506ba7ab), it adds "flutter rebuild" with all of the code changes localized in bin/flutter. Of course similar changes to bin/flutter.bat and any desired changes to docs.

Here is the diff:
```
$ git diff HEAD^
diff --git a/bin/flutter b/bin/flutter
index cdf974233..35e94832f 100755
--- a/bin/flutter
+++ b/bin/flutter
@@ -108,7 +108,7 @@ function upgrade_flutter () {
   #  * STAMP_PATH is not a file with nonzero size, or
   #  * Contents of STAMP_PATH is not our local git HEAD revision, or
   #  * pubspec.yaml last modified after pubspec.lock
-  if [[ ! -f "$SNAPSHOT_PATH" || ! -s "$STAMP_PATH" || "$(cat "$STAMP_PATH")" != "$revision" || "$FLUTTER_TOOLS_DIR/pubspec.yaml" -nt "$FLUTTER_TOOLS_DIR/pubspec.lock" ]]; then
+  if [[ "$REBUILD_SELF" == "true" || ! -f "$SNAPSHOT_PATH" || ! -s "$STAMP_PATH" || "$(cat "$STAMP_PATH")" != "$revision" || "$FLUTTER_TOOLS_DIR/pubspec.yaml" -nt "$FLUTTER_TOOLS_DIR/pubspec.lock" ]]; then
     rm -f "$FLUTTER_ROOT/version"
     touch "$FLUTTER_ROOT/bin/cache/.dartignore"
     "$FLUTTER_ROOT/bin/internal/update_dart_sdk.sh"
@@ -137,6 +137,7 @@ function upgrade_flutter () {
   exit $?
 }
 
+if [[ $# == 1 && "$1" == "rebuild" ]]; then REBUILD_SELF=true; else REBUILD_SELF=false; fi
 PROG_NAME="$(path_uri "$(follow_links "$BASH_SOURCE")")"
 BIN_DIR="$(cd "${PROG_NAME%/*}" ; pwd -P)"
 export FLUTTER_ROOT="$(cd "${BIN_DIR}/.." ; pwd -P)"
@@ -187,6 +188,13 @@ fi
 
 (upgrade_flutter) 3< "$PROG_NAME"
 
-# FLUTTER_TOOL_ARGS isn't quoted below, because it is meant to be considered as
-# separate space-separated args.
-"$DART" --packages="$FLUTTER_TOOLS_DIR/.packages" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"
+if [[ "$REBUILD_SELF" != "true" ]]; then
+  # FLUTTER_TOOL_ARGS isn't quoted below, because it is meant to be considered as
+  # separate space-separated args.
+  "$DART" --packages="$FLUTTER_TOOLS_DIR/.packages" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"
+fi
+
+# Add some help on how to rebuild flutter
+if [[ $# == 0 ]] || [[ $# == 1 && "$1" == "help" ]] || [[ $# == 2 && "$1" == "help" && "$2" == "-v" ]]; then
+  echo Run \"flutter rebuild\" to rebuild flutter itself
+fi
```

**Comment by winksaville** [comment]
@jonahwilliams, thoughs on [flutter rebuild](https://github.com/flutter/flutter/pull/52132#issuecomment-608098527)?

**Pull request closed without merging**
