### PR TITLE
Revert "Fix issue where DevTools would not be immediately available when using --start-paused"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#126698

There are a bunch of tool crashes on CI that start with this commit. I'm not sure this PR is the cause because there is no backtrace from the tool on the crashes. The only error message is `Oops; flutter has exited unexpectedly: "Null check operator used on a null value`.

### CODE REVIEW

**Review by dnfield — APPROVED** [review]

**Comment by zanderso** [comment]
Here's an example: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_arm64_android%20run_debug_test_android/2442/overview

**Comment by zanderso** [comment]
The tests that had been failing are now passing regularly, so I think this was the correct culprit.

**Comment by bkonyi** [comment]
Thanks for handling the revert. Is there any reason this wasn't caught by the presubmit checks?

**Comment by zanderso** [comment]
@bkonyi Yeah. Most tests that run on physical devices only run in post submit.

**Pull request merged**
