### PR TITLE
add assert if length of TabController and number of tabs do not match

### LINKED ISSUE #16292: Assert if length of TabController and number of tabs doesn't match
## Steps to Reproduce

I have a scrollable TabBar with 11 elements. The TabBar shows the correct text for all the elements, but only the first 5 tabs are selectable, when I tap the 6th tab or further I get an exception. 

## Logs
```
Launching lib/main.dart on iPhone 6 in debug mode...
Running Xcode clean...                                       3.8s
Starting Xcode build...                                          
 ├─Assembling Flutter resources...                   10.1s
 └─Compiling, linking and signing...                 16.4s
Xcode build done                                            31.9s
Syncing files to device iPhone 6...                          3.7s

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on iPhone 6 is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/material/tab_controller.dart': Failed assertion: line 111 pos 12: 'value >= 0
&& (value < length || length == 0)': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#2      TabController._changeIndex (package:flutter/src/material/tab_controller.dart:111:12)
#3      TabController.animateTo (package:flutter/src/material/tab_controller.dart:163:5)
#4      _TabBarState._handleTap (package:flutter/src/material/tabs.dart:865:17)
#5      _TabBarState.build.<anonymous closure> (package:flutter/src/material/tabs.dart:940:21)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
#7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
#10     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
#11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#12     BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
#13     BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
#14     BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
#15     BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
#16     BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
#17     _invoke1 (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:134)
#18     _dispatchPointerDataPacket (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:91)
(elided 2 frames from class _AssertionError)

Handler: onTap
Recognizer:
TapGestureRecognizer#1dc75(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
Offset(270.0, 149.5), sent tap down)


Analyzing /Users/luisharo/IdeaProjects/sch_test...
No issues found!
Ran in 8.8s
```

## Flutter Doctor
```
[✓] Flutter (Channel beta, v0.2.3, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.2.3 at /Users/luisharo/flutter
    • Framework revision 5a58b36e36 (3 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/luisharo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[✓] Connected devices (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 8.1.0 (API 27) (emulator)
    • iPhone 6                  • B41B74EE-350C-4475-86D2-4306EE7B3ABF • ios         • iOS 11.3 (simulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by shihaohong**
## Description

Initially, an exception would be thrown on certain gestures when there is a mismatch in TabController length and the number of TabBar tabs. This change introduces an assert that throws an exception when:
1) The TabController length and the number of TabBar tabs do not match
2) The TabController length and the number of TabBarView children elements do not match

## Related Issues

Fixes https://github.com/flutter/flutter/issues/16292

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by kika** [comment]
This PR is not marked as "breaking change" but it is. 
https://stackoverflow.com/questions/46180919/pattern-for-updating-tabcontroller-length-from-child-widget/51311740#51311740

**Comment by shihaohong** [comment]
Hi @kika,

The TabController/TabBar/TabBarView APIs were not meant to be used with mismatching lengths, so I would not consider it a breaking change. Not having the asserts in place caused more problems with incorrect usage of the API, as brought up by the [original issue](https://github.com/flutter/flutter/issues/16292) that prompted this PR.

Alternatively, if there is a need or confusion for how to properly create dynamic number of tabs, please file an issue requesting for docs or a new feature.

**Comment by ffeu** [comment]
Hi @shihaohong, 

I can confirm that this check made it apparently impossible (or very difficult) to handle dynamic length TabBars. You can't dispose the old one as it's currently in use, and you cannot create a new one as you end up with multiple Tickers.

As a suggestion, If the check was:
```
 if (newController.length < widget.tabs.length) {
```

The original issue would be fixed (as the cause was that the controller was smaller than the tab count) and there would be no additional harm.

I'm only presenting this option as it's is unlikely that the new issue would be prioritized in the short term, and people who have already relayed on that do not have currently an easy alternative besides refactor the code (forcing rebuilding the whole widget which hosts the tabcontroller).

**Comment by shihaohong** [comment]
Hi @ffeu, 

I believe it is possible to create dynamic tabs with DefaultTabController, since it uses one AnimationController by using a private _copyWith method available to DefaultTabController. What we could do is make copyWith a public method so that developers can make use of it in creating dynamic tabs.

I created an issue to track this update: https://github.com/flutter/flutter/issues/34264

@johnsonmh Would making TabController._copyWith() public cause any problems?

**Comment by johnsonmh** [comment]
> @johnsonmh Would making TabController._copyWith() public cause any problems?

I don't know of any problems that this would cause. @HansMuller What do you think?

**Comment by shihaohong** [comment]
Turns out there was some kind of motivation to making copyWith private.

Leaving this comment here so that it can be referenced: https://github.com/flutter/flutter/pull/30884#issuecomment-485848272

**Pull request merged**
