### PR TITLE
Dropdown shows disabledHint when items is empty

### PR DESCRIPTION
**Pull request by mklim**
See flutter/flutter#18770 for the original PR.

Some changes in this patch:

* Removed the behavior that showed this when `onChanged == null`. Most
of dropdown's unit tests left `onChanged` as null and this broke them.
Can put it back in and update them if that was just brittleness in the
tests and we're not actively trying to preserve the previous behavior
in that case.
* Added the `items != null` assert back in. This functionality works
just as well on an empty list as on null, and generally it's easier to
reason about objects when they're guaranteed to be non-null.
* Fix a bug where `disabledHint` wasn't being given enough padding,
since `items` was empty.
* Minor style changes.

### CODE REVIEW

**Comment by mklim** [comment]
Manually setting the CLA label to "yes" since the original author contributed their commit to this project in the previous PR.

**Comment by Hixie** [comment]
We should also disable if `onChanged` is null, as with other widgets.

**Comment by escamoteur** [comment]
I agree with @Hixie also please allow null again as it was.

**Comment by escamoteur** [comment]
Btw why creating a new PR?

**Comment by mklim** [comment]
OK, I mentioned it in the PR comment but I'll break and fix the existing tests then @Hixie. They were passing in `onChanged = null` and then manipulating the dropdown, I thought it was likely deliberate behavior we wanted to keep backwards compatible instead of just the test missing params.

@escamoteur I made this a new one because of how Github ties PRs to branches. As far as I know the only way for flutter/flutter#18770 to be updated is for [escamoteur/flutter/improved_dropdownbutton](https://github.com/escamoteur/flutter/tree/improved_dropdownbutton) to have additional commits pushed to it. I can push these commits to your fork instead if you'd prefer that to a separate PR?

**Comment by escamoteur** [comment]
I you push them on my PR I see when my PR is merged :-)

**Comment by mklim** [comment]
OK, I'll move these commits into `escamoteur/flutter/improved_dropdownbutton` instead. :)

**Pull request closed without merging**
