### PR TITLE
Fix socket leak by ensuring HttpClientResponse is properly consumed

### PR DESCRIPTION
**Pull request by alexd6631**
This fix a socket leak in NetworkImage IO implementation, that happens when a non Ok http code is returned.
In that case the HttpClientResponse was left unconsumed, and a underlying socket opened.

https://github.com/flutter/flutter/issues/78741

This quick fix ensure the socket is properly closed, by listening to the response and cancelling the stream.
As an alternative we may want to consume (and ignore) the whole response, so that the socket can be reused if kept alive.

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by alexd6631** [comment]
@googlebot I signed it!

**Comment by goderbauer** [comment]
@alexd6631 The email address associated with your github commit doesn't match the email address you used to sign the CLA. That's why the CLA bot is not happy. Can you please fix that?

Also, this will need a test and it looks like it is failing some existing tests.

**Comment by alexd6631** [comment]
Hello @goderbauer.

Unfortunately I don't have the time to invest the test suite in the short term, but I may be able to investigate it later (I am investigating Flutter for personal use on my free time, and will be busy in the upcoming days).
So if an official contributor wants to tackle this issue, feel free to close this MR and create a proper one.

The aim of the PR was to pinpoint the location of the socket leak, and a potential fix for it. A quick local test on my toy app, show that it indeed fixes the leak, preventing too many open files error.

It is likely this issue could affect a production apps (although you need to have a lot of HTTP errors during image loading for it to trigger), so you may want to give it a high priority.

I only reported the issue on iOS, but from the look of it, it could affect other (non web) platform which also use a HttpClientResponse.

**Comment by goderbauer** [comment]
Okay, looks like you filed an issue to track the leak. I am going to close this PR for now until somebody has time to look at it in more detail.

**Pull request closed without merging**
