### PR TITLE
reduce warnings inside flutter.groovy file #2

### PR DESCRIPTION
**Pull request by AbdeMohlbi**
follow up for : [#152073](https://github.com/flutter/flutter/pull/152073)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by reidbaker** [comment]
Test Exemption: Gradle files do not have unit tests and this pr is not worth the maintenance burden of a specific integration test covering just this change. Additionally the code being modified is tested under an integration test for native assets and regular app builds.

**Review by reidbaker — APPROVED** [review]

**Comment by reidbaker** [comment]
Also the new codepath has been available since gradle 4.1 https://docs.gradle.org/4.1/javadoc/org/gradle/api/file/ProjectLayout.html

**Comment by AbdeMohlbi** [comment]
Some stuff are also deprecated inside the groovy file more then 40 warnings if i remember correctly i'll fix some each time because some times debugging could be hard like this one , it worked fine when i used windows but later i found out that it doesn't behave as i supposes with linux and mac (relative paths issue )

**Review by gmackall — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
