### PR TITLE
[CupertinoActionSheet] Match colors to native

### PR DESCRIPTION
**Pull request by dkwingsmt**
This PR matches the various colors of `CupertinoActionSheet` more closely with the native one. 

The following colors are changed.
* Sheet background color
* Pressed button color
* Cancel button color
* Pressed cancel button color
* Divider color
* Content text color

The resulting colors match with native one with deviation of at most 1 (in terms of 0~255 RGB).

The following are comparison (left to right: Native, Flutter after PR, Flutter current)
image
image
_Note: The divider thickness is adjusted to `1/dpr` instead of 0.3 in both Flutter version to make them look more native, as will be proposed in https://github.com/flutter/flutter/pull/149636._

### Derivation 
All the colors are derived through color picker and calculation. The algorithm is as followed:
* Assume all colors are translucent grey colors, i.e. having the same value `x` for R, G, and B, with an alpha `a`.
* Given the barrier color is `x_B1=0` when the background is black, and `x_B2=204` when the background is white.
* Pick the target color `x_t1` when the background is black, and `x_t2` when the background is white
* Solve the following equations for `x` and `a`
```
a * x + (1-a) * x_B1 = x_t1
a * x + (1-a) * x_B2 = x_t2

a = 1 - (x_t1 - x_t2) / (x_B1 - x_B2)
x = (x_t1 - (1-a) * x_B1) / a
```

These equations use a linear model for color composition, which might not be exact, but is close enough for an accuracy of (1/255).

The full table is as follows:

image

* The first two columns are colors picked from XCode.
* The 3~4 columns are the colors picked from the current Flutter. Notice the deviation, which is sometimes drastic.
* The 5~6 columns are the colors picked from Flutter after this PR. The deviation is at most 1.
* The last few columns are calculation.
  * There are two rows whose calculation is based on adjusted numbers, since the original results are not accurate enough, possibly due to the linear composition.

During the calculation, I assumed these colors vary between light and dark modes, but it turns out that both modes use the same set of colors.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by vashworth** [comment]
Reason for revert: Appears to be failing tests in tree
```
01:48 +2991 ~18: /Volumes/Work/s/w/ir/x/w/flutter/packages/flutter/test/cupertino/action_sheet_test.dart: Taps on a button can be slided to other buttons
 ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
 The following SkiaException was thrown while running async test code:
 Skia Gold received an unapproved image in post-submit
 testing. Golden file images in flutter/flutter are triaged
 in pre-submit during code review for the given PR.
 Visit https://flutter-gold.skia.org/ to view and approve
 the image(s), or revert the associated change. For more
 information, visit the wiki:
 https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter
 Debug information for Gold --------------------------------
 stdout: Given image with hash 601f421e3bb643f437cc12395de96152 for test
 cupertino.cupertinoActionSheet.press-drag
 Expectation for test: ce8ef79c146857d162663b1161fd6d5c (positive)
 Expectation for test: 3bb57a8782f67836c6ad3ece7f00729a (positive)
 Expectation for test: 3f8c592774caf3c760fbbd318a7dc5af (positive)
 Expectation for test: 61863f38217aa3349c239eeb49b84930 (positive)
 Expectation for test: 98af16e9b7eb3fb810b44c74bb18ffb9 (positive)
 Untriaged or negative image:
 https://flutter-gold.skia.org//detail?grouping=name%3Dcupertino.cupertinoActionSheet.press-drag%26source_type%3Dflutter&digest=601f421e3bb643f437cc12395de96152
 stderr: Test: cupertino.cupertinoActionSheet.press-drag FAIL
 result-state.json: No result file found.
 ```

**Comment by vashworth** [comment]
PR to manual revert: https://github.com/flutter/flutter/pull/149998

**Comment by b3nni97** [comment]
@dkwingsmt I have problems with the colors in dark mode, I suspect this PR has broken something.

**Comment by dkwingsmt** [comment]
> @dkwingsmt I have problems with the colors in dark mode, I suspect this PR has broken something.
> 
> 
> 
> I see some colors are not resolved by `CupertinoDynamicColor.resolve`, maybe thats the issue.

Can you provide me with screenshots and code to reproduce? I might have used the wrong method to test.

**Comment by b3nni97** [comment]
Hi @dkwingsmt,

I´m using this code to reproduce:

 ``` 
 void main() {
  runApp(TestScaffoldApp(
    theme: const CupertinoThemeData(brightness: Brightness.dark),
    actionSheet: CupertinoActionSheet(
      actions: [
        CupertinoActionSheetAction(
          onPressed: () {},
          child: Text('Button'),
        ),
        CupertinoActionSheetAction(
          onPressed: () {},
          child: Text('Button'),
        ),
      ],
      cancelButton: CupertinoActionSheetAction(
        isDefaultAction: true,
        child: Text("Cancel"),
        onPressed: () {},
      ),
    ),
  ));
}

// Shows an app that has a button with text "Go", and clicking this button
// displays the `actionSheet` and hides the button.
//
// The `theme` will be applied to the app and determines the background.
class TestScaffoldApp extends StatefulWidget {
  const TestScaffoldApp(
      {super.key, required this.theme, required this.actionSheet});
  final CupertinoThemeData theme;
  final Widget actionSheet;

  @override
  TestScaffoldAppState createState() => TestScaffoldAppState();
}

class TestScaffoldAppState extends State<TestScaffoldApp> {
  bool _pressedButton = false;

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      theme: widget.theme,
      home: Builder(
        builder: (BuildContext context) => CupertinoPageScaffold(
          child: Center(
            child: _pressedButton
                ? Container()
                : CupertinoButton(
                    onPressed: () {
                      setState(() {
                        _pressedButton = true;
                      });
                      showCupertinoModalPopup<void>(
                        context: context,
                        builder: (BuildContext context) {
                          return widget.actionSheet;
                        },
                      );
                    },
                    child: const Text('Go'),
                  ),
          ),
        ),
      ),
    );
  }
}
  ``` 
  This is where I use your PR using Dark Mode:
  
IMG_6107

  This is running the latest master (still not correct, so maybe some other PR has broken this behavior):
  
IMG_6108

**Comment by dkwingsmt** [comment]
The first screenshot is exactly what I observed on an Xcode native app when the dark mode toggle on the status bar is on. Did I do it wrong? Can you show me what color it should be?

**Comment by b3nni97** [comment]
Maybe this is a bug in Xcode itself, I can't reproduce it myself in Xcode right now, but this is what a native action sheet looks like in dark mode in the Contacts app.
IMG_6110

If I use `CupertinoDynamicColors.resolve` for all colors in `_ActionSheetButtonBackground` (currently _kPressed, _kActionSheetCancelPressedColor and secondarySystemGroupedBackground Color are not resolved), 
then I get these colors (matching native)
IMG_6111

**Comment by dkwingsmt** [comment]
Thanks you very much! Yeah I couldn't believe it either when I saw that the colors were the same in dark mode. I'll do more research (probably by running the native app on my phone).

**Pull request merged**
