### PR TITLE
Merge flutter_goldens_client into flutter_goldens

### PR DESCRIPTION
**Pull request by Hixie**
This is part 1 of a broken down version of the #140101 refactor.

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

**Comment by Hixie** [comment]
cc @Piinks

**Review by Swiftaxe — APPROVED** [review]
LGTM!

**Comment by Piinks** [comment]
@Swiftaxe please do not merge changes manually. The bot will merge them when checks have completed. The Google test shard only executes after a change is approved.

**Comment by Hixie** [comment]
@Swiftaxe definitely don't merge other people's PRs, ever. Let the person who wrote the PR have final say on whether to land or not.
For example in this particular case I would never have landed this without @Piinks's LGTM since she owns this area of the code, and we have had a bad experience trying to land this refactor in the past so being extra careful is especially warranted.

@Piinks let me know if you would like me to revert for now.

**Comment by Piinks** [comment]
I think we can leave this in @Hixie. Thanks for checking. :)

**Pull request merged**
