### PR TITLE
Include frameworkVersion in JSON version output.

### LINKED ISSUE #23098: flutter --version --machine does not have version string
I've checked out a specific tag:

```
$ git clone -b v0.10.0 --single-branch https://github.com/flutter/flutter.git
Cloning into 'flutter'...
remote: Enumerating objects: 142457, done.
remote: Total 142457 (delta 0), reused 0 (delta 0), pack-reused 142457
Receiving objects: 100% (142457/142457), 47.17 MiB | 2.69 MiB/s, done.
Resolving deltas: 100% (107619/107619), done.
Note: checking out 'd954ae6850a06ea461d5595cef424e278ed9f17f'.
[...]
```

Normal version has the tag information:
```
$ ./flutter/bin/flutter --version
Flutter 0.10.0 • channel unknown • unknown source
Framework • revision d954ae6850 (6 days ago) • 2018-10-09 16:21:06 -0400
Engine • revision bf377896ff
Tools • Dart 2.1.0-dev.6.0.flutter-a50dfd6698
```

But `--machine` does not:
```
$ ./flutter/bin/flutter --version --machine
{
  "channel": "unknown",
  "repositoryUrl": "unknown source",
  "frameworkRevision": "d954ae6850a06ea461d5595cef424e278ed9f17f",
  "frameworkCommitDate": "2018-10-09 16:21:06 -0400",
  "engineRevision": "bf377896ff0fc190301436ff32a592f3bab75e6b",
  "dartSdkVersion": "2.1.0-dev.6.0.flutter-a50dfd6698"
}
```

### PR DESCRIPTION
**Pull request by isoos**
Fixes https://github.com/flutter/flutter/issues/23098

### CODE REVIEW

**Comment by Hixie** [comment]
Can you add a test?

**Comment by isoos** [comment]
Not sure what to test here?

**Comment by tvolkert** [comment]
In [flutter_command_runner_test.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/runner/flutter_command_runner_test.dart), can you add a new `'version'` group with a test for the handling of `flutter --version --machine`?

**Comment by isoos** [comment]
Sorry, I probably won't have time to figure out the details of how that test case should work. Can you take this change without that?

**Comment by tvolkert** [comment]
@isoos no worries!  We'll see if someone else can pick it up and add a test before landing.  Tagging it as "needs love", which means that there's some follow-up work to do on this before it can be landed.

**Pull request closed without merging**
