### PR TITLE
Revert "Refactoring Gold to enable both Luci & Cirrus support"

### PR DESCRIPTION
**Pull request by Piinks**
Reverts flutter/flutter#49815

This is breaking engine tests when they run framework tests on luci.

### CODE REVIEW

**Review by aam — APPROVED** [review]

**Comment by Piinks** [comment]
I have checked Cirrus and it appear that all of the checks have passed, although they are not reflected here: https://cirrus-ci.com/build/6066763053924352 

I am not sure yet what the submit-queue check is, I have not seen it before.

fyi @fkorotkov

**Comment by fkorotkov** [comment]
@Piinks this is the same thing that *branch builds* have a different set of tasks than *PR builds*. But the GH status should've been updated to neutral. Let me check if this change was deployed.

The submit queue check is coming from here https://github.com/cirruslabs/gh-submit-queue. I'll check why GH reports `WIP` as failing for `master` branch.

**Comment by Piinks** [comment]
@fkorotkov Thanks for checking it out! I think this is ok to land then since checking Cirrus directly it looks like all the other checks have passed.

**Comment by fkorotkov** [comment]
@Piinks sounds good. The change was not deployed and I've triggered a deploy now.

**Comment by Piinks** [comment]
fyi @cyanglaz @blasten @kjlubick
This was reverted after breaking dart luci bots. I should be able to re-land after making a recipe change. There are a lot more repos running fluter tests on luci than I thought. 😜

**Comment by fkorotkov** [comment]
Fixed `WIP` reporting in https://github.com/cirruslabs/gh-submit-queue/commit/6f03db6c858c4497eb90e4284c20348d8e5a7dee

**Pull request merged**
