### PR TITLE
Remove back button when using end drawer

### PR DESCRIPTION
**Pull request by gusghrlrl101**
### Before
before

When `end drawer` opens, `close button` is showing on `leading`.

### After
after

When `end drawer` opens, `close button` is not shown.

## Related Issues

#13601

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by darrenaustin** [comment]
@gusghrlrl101 thanks for the contribution. Sorry for the delay in review.

To be honest, I am not sure exactly what you are trying to solve with this. What is wrong with the back button showing when you are using a drawer from the right side? I looked at the [spec](https://material.io/components/navigation-drawer), but I didn't see any guidance on this (other than to not use end drawers for navigation 😄 ). Even if the user sees the back arrow it in the darkened scrim on the left, if they tap on it, it will dismiss the drawer anyway, so I don't see the harm in having it there.

Is there a use case for this that I am missing?

All that said, if we decide to do this, your fix looks good. However, if we do proceed, we will need to have a test added that covers this change (see `test/material/app_bar_test.dart`).

**Comment by gusghrlrl101** [comment]
@darrenaustin, Thanks for your reply 😊.

I added test code for `AppBar`'s `leading` is `null` when `endDrawer` exists.

I think it is unnecessary to show the button and it is awkward for user.
As you said, if we touch darkened scrim on the left, `endDrawer` will disappear. If so, since we can't even press the back button, isn't it more unnecessary?
Opening `endDrawer` is the meaning of showing the menu rather than the meaning of navigating. So it is awkward from the user's point of view when the back button appears after opening the menu.
Seeing that people have tried to get rid of the button in this `issue` as well, I think many users feel it is awkward too.
I would appreciate it if you give me any comments.

Thank you 😊.

**Comment by gusghrlrl101** [comment]
@darrenaustin
I'm sorry to menthion again.
Could you check out my PR again?
Thanks 😊.

**Review by darrenaustin — APPROVED** [review]
Sorry for the lag on this.

I am still not entirely convinced this is that necessary, but it does look like a reasonable implementation and people have been reporting it, so let's go with it.

LGTM. I will push this after they cut a new branch for release (which should be happening soon).

Thanks for the contribution!

**Comment by gusghrlrl101** [comment]
@darrenaustin 
Thank you for your feedback! 😊

**Comment by drdDavi** [comment]
Would have been great if there was a boolean to disable and enable this new feature, this new behavior broke my app... this new change should not be the default.  
Adding the code below to fix several pages...
leading: IconButton(icon: Icon(Icons.close), onPressed: () => Get.back()),

**Comment by darrenaustin** [comment]
@drdDavi so sorry this broke your app. Can you give us more information on how exactly it did that? How were users even tapping the icon with the drawer open?

**Comment by apgapg** [comment]
@darrenaustin Before this back button and end drawer button both appeared. But now with 1.22.x, only end drawer button is shown.
This happens only when one sets endDrawer. In rest pages back button is visible

**Pull request merged**
