### PR TITLE
Add more asserts to try to track down RenderPadding intrinsics bug

### PR DESCRIPTION
**Pull request by Hixie**
See https://github.com/flutter/flutter/issues/19696

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by shihaohong** [comment]
Should https://github.com/flutter/flutter/pull/32817/ be reverted along with this PR? That would increase the instances of this flake occurring and perhaps help with debugging. But, maybe it would happen too frequently that it would hurt the team's overall productivity from having to re-run the flaky tests.

**Comment by Hixie** [comment]
Has anyone been able to reproduce the failures locally on Windows?

**Comment by shihaohong** [comment]
I'm not sure, I've only seen the failures in the context of the Windows Cirrus tests flaking.

**Comment by Hixie** [comment]
It's crazy, but the tests keep timing out on Cirrus on all three platforms. I wonder what is going on...

**Comment by goderbauer** [comment]
(PR triage): @Hixie Do you still have plans to follow-up on this PR?

**Comment by Hixie** [comment]
I need to track down the timeouts. Haven't had much time recently. The timeouts are very suspicious. If someone wants to take it over that's totally fine.

**Comment by Hixie** [comment]
Dealing with timeouts in https://github.com/flutter/flutter/pull/33932

**Comment by Hixie** [comment]
Turns out these asserts are just really really REALLY expensive (one test on my machine ends up taking about 18 hours to run instead of about 5 seconds). I'll have to try a different approach.

**Pull request closed without merging**
