### PR TITLE
Use single quotes for `dartSdkVersionBounds`

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
## Motivation

In all templates, the `dartSdkVersionBounds` are inserted with **double quotes**. This, however, is inconsistent with the rest of the (app) template:

```yml
...
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
...
environment:
  sdk: ">=2.16.1 <3.0.0"
```

After this PR, the environment would be generated as:

```yml
environment:
  sdk: '>=2.16.1 <3.0.0'
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by christopherfujino** [comment]
Hmm, this is interesting. @jonahwilliams is there any kind of special reason we use double quotes for the Dart SDK constraint?

**Comment by jonahwilliams** [comment]
Not that I'm aware of. For YAML I don't think there is a difference, unless it is something to do with SDK versions containing other quotes?

**Comment by christopherfujino** [comment]
Ahh, I bet it's just that the default quote type in dart for our style guide is single quotes, so whoever first wrote this wrote it as `      dartSdkVersionBounds: '">=$dartSdk <3.0.0"',` rather than the other way around.

This change SGTM

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by Jasguerrero — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
@creativecreatorormaybenot could you try re-basing this PR to tip of tree? Only thing blocking merging this PR is getting the pre-submits green.

**Comment by creativecreatorormaybenot** [comment]
@christopherfujino done ✅

**Comment by creativecreatorormaybenot** [comment]
Reopened in #101270.

Could you please re-review? @christopherfujino @Jasguerrero

**Pull request closed without merging**
