### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by mikemimik**
Fixed a small typo in the docs.

### CODE REVIEW

**Comment by mikemimik** [comment]
I signed it!

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
Actually, maybe we should remove the "s" inside the [ ] to make it linkify correctly.

**Comment by Hixie** [comment]
You should also add yourself to https://github.com/flutter/flutter/blob/master/AUTHORS

**Pull request merged**
