### PR TITLE
Support create for macOS (app and plugin)

### LINKED ISSUE #30703: Support 'flutter create' for macOS targets
Once the shell is sufficiently mature, we need to support creation of a macOS runner from a template using `flutter create`.

This should be the most straightforward of the desktop platforms to support, since it should use Xcode, and thus can hopefully share much of the templating code with iOS.

### PR DESCRIPTION
**Pull request by stuartmorgan-g**
## Description

Adds macOS support for `flutter create`:

- Currently it is behind a hidden flag.
- Adds a TargetPlatform workaround to lib/main.dart in the standard app template when enabled.
- Supports `app` and `plugin`; `module` support doesn't yet exist for macOS in general.

This will eliminate the need to use FDE's examples as templates on macOS. The templates are based on the current state of FDE's examples, with templating support added (and with adoption of the new application delegate in the app, which hadn't been done yet in FDE, eliminating some boilerplate from the template).

## Related Issues

Fixes #30703 

## Tests

I added the following tests: Tests that `create` with `--macos` creates an app or plugin with macOS support, and does not otherwise.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by stuartmorgan** [comment]
I just realized that I didn't add macOS support to the plugin's pubspec.yaml, or the plugin example. Hold off on reviewing.

**Review by jonahwilliams — APPROVED** [review]
Wow, we're almost there! 

General approach LGTM. It's probably worth noting that 'flutter create .'  won't add the override to an existing project, so I would expect more bugs to get filled here.

**Comment by jonahwilliams** [comment]
Ahh the plugins, good catch.

**Comment by stuartmorgan** [comment]
Added the new schema conditionally for now, since that's the safer approach; started a discussion in the ecosystem chat about when we want to fully flip the switch on that.

With that the plugin example just works (it just uses the app template to make the example, which is obvious in retrospect).

**Comment by stuartmorgan** [comment]
> Merging #40851 into master will decrease coverage by 2.61%.
> The diff coverage is 100%.

codecov continues to reach... interesting conclusions about absolute coverage.

**Comment by stuartmorgan** [comment]
I'll update flutter.dev/desktop and the FDE readmes soon to point to this so we start getting testing.

**Pull request merged**
