### PR TITLE
Replace hardcoded iOS build dir with config-driven lookup

### PR DESCRIPTION
**Pull request by cbracken**
Related: b5f763b45e454863eb5baa10132e5e2df59d6987

### CODE REVIEW

**Comment by cbracken** [comment]
Addresses #5727

**Comment by eseidelGoogle** [comment]
Thank you for relating to the original commit to help future code-archaeologists. :)

**Comment by chinmaygarde** [comment]
lgtm

**Comment by tvolkert** [comment]
LGTM

Thanks!

**Pull request merged**
