### PR TITLE
Text field height attempt 2

### PR DESCRIPTION
**Pull request by justinmc**
See https://github.com/flutter/flutter/pull/27205

Attempting to get that PR in again after it was [reverted](https://github.com/flutter/flutter/pull/29093) due to breaking internal tests after the roll.

### CODE REVIEW

**Comment by justinmc** [comment]
See https://github.com/flutter/flutter/pull/27205 for confirming CLA.

**Comment by justinmc** [comment]
The bug that was causing the image comparison tests to fail was that my new layout algorithm was adding a subtext gap below the subtext when the old one wasn't.  My fix is to remove that extra subtext gap.

So originally and after my fix, the parent container ends immediately after any subtext with no spacing (see screenshot below).  I think this is best because there is also no spacing when there is no subtext at all. Any desired spacing will be up to the user.

flutter_05

The same thing with spacing after the subtext looked like this.  This is no longer the behavior with my fix.

flutter_06

**Comment by justinmc** [comment]
Another bug for other image comparison tests was related to `errorText` positioning.  My new layout algorithm ignored it if it was an empty string, but for legacy reasons needed to support it.  The bug ended up causing an input that wasn't as tall as it used to be and slightly out of place:

DIFF_display_pin_3

I also didn't lay it out when I should have in a few other cases, which was fixed with the above.

**Comment by justinmc** [comment]
@HansMuller This is ready for review.  You've already reviewed this PR when it went in the first time, but now I've added five new commits, starting with f276609.  The new things that I've done are:

  1. Fixed and tested a subtext bug explained in a comment above, exposed by adwords mobile app tests.
  1. Fixed and tested an errorText bug explained in another comment above, also exposed by adwords mobile app tests.
  1. Added `minlines` and `expands` to TextFormField and CupertinoTextField, just because I noticed that I forgot to do so in the original PR.

**Review by HansMuller — APPROVED** [review]
The new changes LGTM, please take this PR in for a landing!

**Pull request merged**
