### PR TITLE
Add support for running flutter tests on Chromium Infra

### PR DESCRIPTION
**Pull request by eseidelGoogle**
This uses the fancy new x-repository support:
https://github.com/luci/recipes-py/blob/master/doc/cross_repo.md

I'm not at all certain that we're going to use Chromium's
Infra for flutter, but I'm exploring and since this works
I figure I should check it in.

@abarth

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
FYI @luqui

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (424/400 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:2161)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1aKEQf-002oeH-Rs
	for yann.dupuy@zyapps.com; Sat, 16 Jan 2016 01:09:19 +0100
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=pDSnvQz+fbDZ9Nuv58neRI6HEl8=; b=EdJx/fmflPETVDQ9
	AZbVirgwK+LqRPjjhXjdE0rbe1m7LhPJ7OFKU+X3kOty27lSf8WsAsy3RviEvjJc
	14iQsZ61/ZWkvD1ATTzjYUT9GwgsByIBlyILJ2RehiOPT/fmjC0fsv3xq6pMBjK4
	sdyithRWPGcTOxKHQEorPIshvto=
Received: by filter0088p1las1.sendgrid.net with SMTP id filter0088p1las1.28774.569989FAC2
        2016-01-16 00:08:26.832120394 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id i0JFLhUNSQyp4QKNmjrK-g
	for <yann.dupuy@zyapps.com>; Sat, 16 Jan 2016 00:08:27.068 +0000 (UTC)
Date: Fri, 15 Jan 2016 16:08:26 -0800

**Comment by eseidelGoogle** [comment]
FYI @riannucci

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (481/400 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:10523)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1aKERY-002otk-DZ
	for yann.dupuy@zyapps.com; Sat, 16 Jan 2016 01:10:14 +0100
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=4oBP+nEKQjP/ioTZKT3PumkRfbk=; b=HaxgSBhJ0aQJcGtu
	fr/TJnZmRGTut0JD8ckqjskoudCmYtmtCz4YMcrSykBjPIayBZpP0ckxfI9K9liq
	h/BfRY30r/vsUkEmx0t4KaDj/L9odSF4GiUmLp+iTEuD+FQmG2ZouhppCYcPrPOC
	gswPTaStRc8Pdlr6FyWvQ6rgmZ4=
Received: by filter0199p1las1.sendgrid.net with SMTP id filter0199p1las1.4096.56998A353E
        2016-01-16 00:09:25.536539497 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id VVb-EcxLRDm6kRjenMwnvQ
	for <yann.dupuy@zyapps.com>; Sat, 16 Jan 2016 00:09:25.540 +0000 (UTC)
Date: Fri, 15 Jan 2016 16:09:25 -0800

**Comment by riannucci** [comment]
FWIW, that recipe structure on the latest commit lgtm. Some followups:
  * dart will need to be shuttled to the bot somehow by the recipe (our VMs don't supply dart)
  * probably want to run test steps with a mapping of testname -> test function
  * probably want to use `api.step.defer_results` to be able to run all the tests even when one of them fails, but still make the overall recipe fail if one or more tests fails.

**Comment by Hixie** [comment]
merge in https://github.com/flutter/flutter/pull/1043

other than that, lgtm.

**Comment by eseidelGoogle** [comment]
Merging this for now.  Will require further updates in order to run cleanly on infra's bots.

**Pull request merged**
