### PR TITLE
Make `animateTo` use `curve` argument correctly

### LINKED ISSUE #95743: `DraggableScrollableSheetController` ignores the curve argument
## Steps to Reproduce

Call `animateTo()` with a controller attached to a sheet and an arbitrary non-linear curve. Note that the animation is linear even though a non-linear curve was specified.

### PR DESCRIPTION
**Pull request by caseycrogers**
As @jyardin [pointed out](https://github.com/flutter/flutter/pull/92440#discussion_r751125312), the draggable scrollable sheet controller's `animateTo` function doesn't actually use the curve argument.

This PR adds a test to ensure the curve argument is applied to the animation and then fixes the `animateTo` function. Credit to jyardin for the code changes to the `animateTo` function.

Fixes #95743 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by caseycrogers** [comment]
@dnfield Could you look at this guy and #96089?

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
@goderbauer can you provide a second LGTM?

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
@caseycrogers It looks like the google check may have gotten stuck. Can you rebase this to master or push an empty commit to retrigger it? Sorry for the inconvenience.

**Comment by caseycrogers** [comment]
> 

Np, pushed!

**Comment by caseycrogers** [comment]
Ugh I accidentally polluted the commit history and now the CLA check is failing, should I just create a new branch and PR or is there a way to override CLA bot?

**Comment by dnfield** [comment]
Sometimes you can make things work by fetching upstream and doing a soft reset against it, and then force pushing. But if it's easier to create a new PR just do that.

**Comment by caseycrogers** [comment]
Yikes, sorry for the spam people who just got auto-added as reviewers. I'll just kill this PR and make a new one.

**Pull request closed without merging**
