### PR TITLE
prefer const constructor

### PR DESCRIPTION
**Pull request by a14n**
By playing new linter rule of dart-lang/linter#342 on flutter package

### CODE REVIEW

**Comment by sethladd** [comment]
Thanks!

cc @Hixie

**Comment by abarth** [comment]
Awesome

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
Gold star

**Comment by sethladd** [comment]
Thanks @a14n ! Please add your name to AUTHORS file :)

**Pull request merged**
