### PR TITLE
Upgrade to most recent android build tools version

### PR DESCRIPTION
**Pull request by mit-mit**
Upgrade to most recent version of android build tools, version 25.0.3: https://developer.android.com/studio/releases/build-tools.html 

This provides some temporary relief for https://github.com/flutter/flutter/issues/8438

### CODE REVIEW

**Review by jakobr-google — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Is there no way to automatically use the latest version?

**Comment by mit-mit** [comment]
No, the version is pinned to the exact version stated in the file.

**Comment by Hixie** [comment]
@mit-mit would it make sense for us to detect what the latest installed version is and automatically update the build files at build time to use those, or something? Or maybe make "flutter upgrade" upgrade the user to use the latest SDK?

It seems very odd for us to pin people to a specific version when they run "flutter create". They're not going to know that they have to update it. We're going to regularly forget to update it for all out examples. If the version in our examples doesn't match the version their app uses now they have to use two versions. Or maybe they'll download us then download the SDK and get a later version than we expect and now we won't work. In general this seems like a poor experience.

**Pull request merged**
