### PR TITLE
Do not abort at first error when tests fail.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
I don't know if we want this. @christopherfujino suggested it and it seemed like an interesting thing to try implementing while I waited for CI to run on my other PR. :-)

**Comment by christopherfujino** [comment]
> I don't know if we want this. @christopherfujino suggested it and it seemed like an interesting thing to try implementing while I waited for CI to run on my other PR. :-)

Oh, this would also help the situation where I have 4 analysis failures, and I have to push 4 separate commits.

**Review by christopherfujino — APPROVED** [review]
lgtm

**Comment by pedromassango** [comment]
> Oh, this would also help the situation where I have 4 analysis failures, and I have to push 4 separate commits.

If I understood this correctly, it also means that when running tests in CI/CD, it won't fail until it runs all tests, right? If that is true then I would prefer to guard it under a flag as it would cost some $$$ due to the runtime.

I usually run the tests mannually when the first attempt fails to avoid multiple commits.

**Comment by christopherfujino** [comment]
> > Oh, this would also help the situation where I have 4 analysis failures, and I have to push 4 separate commits.
> 
> If I understood this correctly, it also means that when running tests in CI/CD, it won't fail until it runs all tests, right? If that is true then I would prefer to guard it under a flag as it would cost some $$$ due to the runtime.
> 
> I usually run the tests mannually when the first attempt fails to avoid multiple commits.

are you running the framework internal test suite on your own CI/CD?

**Comment by Hixie** [comment]
The vast majority of runs on CI pass all the tests, so the few $$$ you would save from aborting early when it fails early is probably a trivial amount. Also on CI generally much of this is run in parallel anyway, so it's not like it actually reduces it that much on CI even if something fails.

**Comment by Hixie** [comment]
@pedromassango That said, I'll add a flag to my follow-up PR to make it abort on the first error.

I'm going to land this and see what happens.

**Comment by pedromassango** [comment]
> are you running the framework internal test suite on your own CI/CD?

No. I think I misunderstood this PR

**Comment by Hixie** [comment]
FWIW I am adding `--abort-on-error` for `test.dart`, in https://github.com/flutter/flutter/pull/109206

**Pull request merged**
