### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by anoop-b**
Image file size has been reduced by **48%** 🎉

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /examples/flutter_gallery/android/app/src/main/res/mipmap-xxxhdpi/ic_background.png | 122.91kb | 6.64kb | 94.60% |
| /examples/flutter_gallery/android/app/src/main/res/mipmap-xxhdpi/ic_background.png | 70.61kb | 4.85kb | 93.14% |
| /examples/flutter_gallery/android/app/src/main/res/mipmap-xhdpi/ic_background.png | 31.06kb | 3.16kb | 89.84% |
| /examples/flutter_gallery/android/app/src/main/res/mipmap-hdpi/ic_background.png | 17.78kb | 2.52kb | 85.81% |
| /examples/flutter_gallery/android/app/src/main/res/mipmap-xxxhdpi/ic_foreground.png | 16.11kb | 6.01kb | 62.69% |
| /examples/flutter_gallery/android/app/src/main/res/mipmap-xxhdpi/ic_foreground.png | 10.06kb | 4.50kb | 55.23% |
| /examples/flutter_gallery/android/app/src/main/res/mipmap-xhdpi/ic_foreground.png | 5.33kb | 2.66kb | 50.12% |
| /dev/snippets/assets/code_snippet.png | 197.49kb | 110.82kb | 43.89% |
| /examples/flutter_gallery/android/app/src/main/res/mipmap-hdpi/ic_foreground.png | 3.50kb | 2.01kb | 42.39% |
| /dev/devicelab/images/legend.png | 47.70kb | 29.51kb | 38.13% |
| /dev/snippets/assets/code_sample.png | 57.20kb | 38.12kb | 33.35% |
| /examples/flutter_gallery/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png | 13.58kb | 9.67kb | 28.80% |
| /examples/flutter_gallery/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png | 9.42kb | 7.00kb | 25.73% |
| /examples/stocks/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-60@3x.png | 12.52kb | 9.34kb | 25.40% |
| /examples/stocks/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-83.5@2x.png | 11.28kb | 8.42kb | 25.32% |
| /examples/flutter_gallery/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png | 5.20kb | 3.89kb | 25.27% |
| /dev/devicelab/images/agent-statuses.png | 17.97kb | 13.52kb | 24.77% |
| /examples/stocks/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-76@2x.png | 9.85kb | 7.41kb | 24.75% |
| /examples/stocks/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png | 13.31kb | 10.15kb | 23.74% |
| /examples/stocks/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-60@2x.png | 7.04kb | 5.50kb | 21.87% |
| /examples/stocks/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-Small-40@3x.png | 7.04kb | 5.50kb | 21.87% |
| /examples/flutter_gallery/android/app/src/main/res/mipmap-hdpi/ic_launcher.png | 3.86kb | 3.04kb | 21.13% |
| /examples/stocks/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png | 8.67kb | 6.98kb | 19.44% |
| /examples/stocks/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-Small-40@2x.png | 3.96kb | 3.21kb | 19.12% |
| /dev/devicelab/images/broken-test.png | 68.26kb | 55.54kb | 18.63% |
| /examples/stocks/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-76.png | 3.71kb | 3.04kb | 18.11% |
| /examples/stocks/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-Small@3x.png | 4.41kb | 3.64kb | 17.59% |
| /examples/stocks/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-Small@2x.png | 2.46kb | 2.11kb | 14.06% |
| /examples/stocks/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-Notification@3x.png | 2.60kb | 2.24kb | 13.74% |
| /examples/stocks/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png | 4.94kb | 4.27kb | 13.61% |
| /examples/stocks/android/app/src/main/res/mipmap-hdpi/ic_launcher.png | 3.40kb | 2.97kb | 12.64% |
| /examples/stocks/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-Small-40.png | 1.49kb | 1.37kb | 8.18% |
| /examples/stocks/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-Notification@2x.png | 1.49kb | 1.37kb | 8.18% |
| /examples/stocks/android/app/src/main/res/mipmap-mdpi/ic_launcher.png | 2.07kb | 1.91kb | 7.69% |
| /examples/flutter_gallery/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-152.png | 2.11kb | 1.96kb | 7.35% |
| /examples/flutter_gallery/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-120.png | 1.75kb | 1.71kb | 2.07% |
| /dev/benchmarks/macrobenchmarks/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png | 10.85kb | 10.68kb | 1.62% |
| /dev/integration_tests/ios_add2app/ios_add2app/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png | 10.85kb | 10.68kb | 1.62% |
| /packages/flutter_tools/templates/app/ios.tmpl/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png | 10.85kb | 10.68kb | 1.62% |
| /packages/flutter_tools/templates/module/ios/host_app_ephemeral/Runner.tmpl/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png | 10.85kb | 10.68kb | 1.62% |
| /dev/integration_tests/release_smoke_test/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png | 10.85kb | 10.68kb | 1.62% |
| /dev/integration_tests/codegen/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png | 10.85kb | 10.68kb | 1.62% |
| | | | |
| **Total :** | **867.25kb** | **450.62kb** | **48.04%** |
</details>

### CODE REVIEW

**Comment by anoop-b** [comment]
I signed it!

**Comment by dnfield** [comment]
Manually verified that ImgBotApp has signed the CLA.

**Review by dnfield — APPROVED** [review]
LGTM, Thanks!

**Comment by dnfield** [comment]
The release smoke test failure is because of credentials - should pass on post submit.

**Pull request merged**
