### PR TITLE
[flutter_tool] Flip create language defaults to swift and kotlin

### PR DESCRIPTION
**Pull request by zanderso**
## Description

This PR changes the default languages for the `create` command. Previous behavior can be recovered by explicitly passing the `--ios-language` and `--android-language` flags.

## Related Issues

https://github.com/flutter/flutter/issues/21190

## Tests

Adjusted tests in `commands/create_test.dart`.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM


cc @devoncarew , I think the IDEs might also expose some flutter create configuration as well? I did see them in vscode too

**Comment by devoncarew** [comment]
Thanks, we do expose the options graphically. We'll need to flip our defaults as well; cc @stevemessick.

**Comment by Hixie** [comment]
Why did this increase basic_material_app_win__compile?

cc @timsneath

**Comment by AndruByrne** [comment]
So, this change in the defaults did not occasion a change to the AndroidStudio UI; you can check off the kotlin box or not, the same thing happens: Kotlin platform code.

Aside: I was one of the early Kotlin advocates at G, but have not seen opportunities for capitalizing on its features while writing basic API calls; I think the Android team may have different requirements than flutter plugin developers, but all that is besides the point...

I would imagine someone would have had to eat this dogfood and try to set up a Java/ObjC plugin; what was their process and can it be repeated?

I'll go try to throw things at the CLI now...

**Comment by devoncarew** [comment]
> So, this change in the defaults did not occasion a change to the AndroidStudio UI; you can check off the kotlin box or not, the same thing happens: Kotlin platform code.

@AndruByrne, what version of the Flutter IntelliJ plugin are you using? Can you open an issue for this at https://github.com/flutter/flutter-intellij/issues? Thanks!

cc @stevemessick

**Comment by AndruByrne** [comment]
@devoncarew Android Studio 3.5.1; did all the updates, closed the studio, rebooted the computer, made new Flutter Plugin and...

wilco

**Pull request merged**
