### PR TITLE
Improve error messages for iOS workflow

### PR DESCRIPTION
**Pull request by abarth**
We now check that you've got an "ios" directory and that you have the proper
version of Xcode.

### CODE REVIEW

**Comment by abarth** [comment]
@chinmaygarde

**Comment by chinmaygarde** [comment]
lgtm

**Comment by eseidelGoogle** [comment]
lgtm.  I might also suggest that we make `flutter init` just dump out an ios directory and xcodeproj, even if we're on linux.  We already do that for android by dumping out an `apk` dir.

**Comment by abarth** [comment]
@eseidelGoogle Even after doing that, we should still have this error message in case the developer deletes the directory.

**Pull request merged**
