### PR TITLE
remove codesign.dart

### PR DESCRIPTION
**Pull request by Abhishek01039**
https://github.com/flutter/flutter/pull/71244
This lands on stable.
https://github.com/flutter/flutter/blob/stable/dev/bots/codesign.dart

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Abhishek01039** [comment]
Hello @christopherfujino 
can you please review this PR?
Thanks

**Comment by Abhishek01039** [comment]
Hello @Hixie 
can you please review this PR?
Thanks

**Comment by christopherfujino** [comment]
> Hello @christopherfujino
> can you please review this PR?
> Thanks

Thanks for opening this PR. The final blocker to landing this would be updating [this file](https://flutter.googlesource.com/recipes/+/refs/heads/master/recipe_modules/adhoc_validation/resources/verify_binaries_codesigned.sh). I will work on a PR to update that file now.

**Comment by christopherfujino** [comment]
We can land this once https://flutter-review.googlesource.com/c/recipes/+/11620 is merged.

**Comment by Abhishek01039** [comment]
Thanks @christopherfujino

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
