### PR TITLE
Revert "[flutter_tools] File system utilities"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#48738

Reverting for analysis errors that didn't get caught by presubmit checks.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by zanderso** [comment]
TBR, landing on red to help turn the bot green.

**Comment by jonahwilliams** [comment]
> Reverting for analysis errors that didn't get caught by presubmit checks.

That seems odd, was the branch out of sync with master's analysis options?

**Comment by zanderso** [comment]
The errors were 'unused imports' so a non-conflicting addition of an import that got in before this one could have caused it.

**Pull request merged**
