### PR TITLE
Analyze more tests.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
cc @eseidel

**Comment by eseidelGoogle** [comment]
We really need a glob package.  lgtm.

**Comment by eseidelGoogle** [comment]
https://pub.dartlang.org/packages/glob ?

**Comment by Hixie** [comment]
If it works and is now slower, sure. The current code was the result of avoiding some previous patterns that were slow (e.g. the test package does a crawl that follows symbolic links and that's fatally slow, which is why `flutter test` manually lists the tests itself.) File a bug?

**Pull request merged**
