### PR TITLE
add test to verify that nothing changes in the git workspace

### PR DESCRIPTION
**Pull request by Hixie**
## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
cc @godofredoc @CaseyHillers @christopherfujino  how do i enable something like this for the LUCI shards as well?

**Comment by CaseyHillers** [comment]
@Hixie should this be run on all of the Flutter checks? Would it make sense to add this to [bots/test.dart](https://cs.opensource.google/flutter/flutter/+/master:dev/bots/test.dart) and run it at the end of every recipe?

**Comment by Hixie** [comment]
`bots/test.dart` isn't run for every shard, is it? e.g. I don't think it gets run for the customer_testing shard.
For Cirrus I just added it as a line that gets run at the end of every Cirrus shard regardless.

**Comment by CaseyHillers** [comment]
It's not, but we could add it to the missing builds. That test could be run at the end of every `bots/test.dart` invocation.

**Comment by Hixie** [comment]
If we're adding something, easier to just add `git diff --exit-code` :-)
My question is more about _how_ to do that. Presumably long-term the move-of-test-descriptions-to-the-repo-under-test will make this trivial but right now we have to edit a recipe somewhere?

**Comment by CaseyHillers** [comment]
Yes, you'll need to add steps to the recipes. You can run the git command as a shell step in those recipes until we support go/flutter-single-recipe-builds

The recipes repo is hosted on git-on-borg at https://flutter.googlesource.com/recipes/

**Comment by godofredoc** [comment]
We have been calling these use case ad hoc validations and we have been implementing them in the following way:

1. Create a script in this location: https://cs.opensource.google/flutter/recipes/+/master:recipe_modules/adhoc_validation/resources/
1. Then add the script name in this list: https://cs.opensource.google/flutter/recipes/+/master:recipe_modules/adhoc_validation/api.py;l=18

If this is something that won't run as an independent task and instead we want to run it on every task we will need to add it as a step to the relevant recipes:

* [flutter](https://cs.opensource.google/flutter/recipes/+/master:recipes/flutter/flutter_drone.py;l=81)
* [devicelab](https://cs.opensource.google/flutter/recipes/+/master:recipes/devicelab/devicelab_drone.py;l=85)

**Comment by Hixie** [comment]
The idea is to run it at the end of every job that ran anything, to make sure the test didn't affect the git workspace.

In any case it looks like it might be simpler to just wait until the recipes and such aren't written in python in another repo... I'm a little worried that for example if I made the change here it would catch a bug and break everything (unless there's a way to test the recipe changes ahead of landing them?).

**Comment by godofredoc** [comment]
> The idea is to run it at the end of every job that ran anything, to make sure the test didn't affect the git workspace.
> 
> In any case it looks like it might be simpler to just wait until the recipes and such aren't written in python in another repo... I'm a little worried that for example if I made the change here it would catch a bug and break everything (unless there's a way to test the recipe changes ahead of landing them?).

Recipe changes are tested on presubmit using builds from framework, devicelab hostonly and engine. Here is an example: https://ci.chromium.org/p/flutter/builders/try/recipes-with-led/b8853549532636159696?

**Comment by Hixie** [comment]
I've filed https://github.com/flutter/flutter/issues/78265 for now, going to close this. I'm unlikely to get to this in the near future unfortunately.

**Pull request closed without merging**
