### PR TITLE
[roll + cherrypick] Revert "Speed up first asset load by encoding asset manifest in binar…

### PR DESCRIPTION
**Pull request by XilaiZhang**
…y rather than JSON (#113637)" (#116662)

This reverts commit 56cad89b1e8d79b75b88116a5db9cb70f91c4986.

cherrypicks https://github.com/flutter/flutter/pull/116662. cherry pick for now and not updating to head so that we might be able to fix all current failures and get going.

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
Tool revert LGTM

**Comment by CaseyHillers** [comment]
@XilaiZhang do you know why the bot didn't approve this? CPs for rolls should be bot approved

**Comment by XilaiZhang** [comment]
umm my understanding might be wrong, but I remember Godofredo mentioned a while ago that autosubmit bot does not work on release branches, or maybe it now works on release branches as well

**Comment by XilaiZhang** [comment]
Synced with Casey and learnt about auto approve from a cocoon bot. Casey added my name to the bot config so in the future roll cherry picks will be auto approved by the bot

**Pull request merged**
