### PR TITLE
better device discovery through polling

### LINKED ISSUE #1990: Flutter Atom devices popup does not show android device, despite being connected
Both @iposva-google and @gbracha hit this.

@devoncarew

### PR DESCRIPTION
**Pull request by devoncarew**
- use polling to create device add and device remove events (we were already doing this for ios simulators)
- move the adb code over to polling (fix https://github.com/flutter/flutter/issues/1990); implement for ios devices (https://github.com/flutter/flutter/issues/1986)

also,
- refactor `ios/device_ios.dart` into `ios/devices.dart`, `ios/simulators.dart`, and `ios/mac.dart`
- create a class (`ItemListNotifier`) to make it easier to convert from a periodic entirely new list of things, to a series of add and remove events. The polling logic can just get a new, full list of devices; this class will convert that into add and remove events.

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
Curious if dart-atom smart enough to stop polling when Atom is in the background, etc?

**Comment by devoncarew** [comment]
It isn't currently. We could add commands to start and stop polling. I don't see an API on atom to determine whether the window is focues, but we may be able to get at the underlying electron BrowserWindow blur and focus events.

**Comment by devoncarew** [comment]
Updated to add `device.enable` and `device.disable` commands to the device domain. This lets clients start and stop device polling. It defaults to polling not being on.

Clients will need to wire in logic to start and stop device notifications as necessary.

**Comment by eseidelGoogle** [comment]
lgtm.  The moved code makes this difficult to read. :(  I also suspect @yjbanov and @iansf are more precise dart reviewers than I am if you were looking for that.

**Comment by devoncarew** [comment]
I normally try and do refactorings in separate commits to make them easier grok; forgot to this time. The new bits are mostly here:

https://github.com/flutter/flutter/pull/2030/files#diff-4a8e85e670fc26e239c20a777adf4061R10
https://github.com/flutter/flutter/pull/2030/files#diff-098fe4c01d0b201571cc05cf4d9e2f36R73
https://github.com/flutter/flutter/pull/2030/files#diff-c177d0d87b337bd405c8238ffaeeace8R12
https://github.com/flutter/flutter/pull/2030/files#diff-e0a5214ddae4fa817a20f117e17de904R283

**Comment by eseidelGoogle** [comment]
It all looks fine.  Thanks.  I'm also very glad you added the start/stop bits as I will expect that our laptop users will eventually care about our power usage.  I also suspect this is not our biggest culprit. :)

**Comment by devoncarew** [comment]
Closing in favor of https://github.com/flutter/flutter/pull/2030, due to an irreconcilable difference of opinion with git.

**Pull request closed without merging**
