### PR TITLE
Fix benchmark

### PR DESCRIPTION
**Pull request by dnfield**
Follow up on #81240 

A couple issues with that PR meant the new metrics aren't getting published to Skia Perf. This should cover all of that.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by CaseyHillers — APPROVED** [review]

**Comment by goderbauer** [comment]
> Follow up on #52825

Is this the incorrect link by any change? Doesn't seem related...

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
That link was completely wrong, updated it to correct one

**Comment by dnfield** [comment]
Windows tests seem indefinitely queued on this PR...

**Comment by CaseyHillers** [comment]
I followed [go/flutter-luci-playbook](http://go/flutter-luci-playbook) to retrigger the forever stuck checks. Looks like it restarted all the luci checks :/ (tracking in https://github.com/flutter/flutter/issues/81499)

**Comment by dnfield** [comment]
I bet the windows tests are backed up because of https://github.com/flutter/flutter/issues/81486

**Pull request merged**
