### PR TITLE
🛡️ Guard Flutter Android app by disallow task affinity by default

### PR DESCRIPTION
**Pull request by AlexV525**
Partial resolution for #63559

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Review by gmackall — APPROVED** [review]

**Comment by gmackall** [comment]
LGTM but I would not mark it as fixing https://github.com/flutter/flutter/issues/63559, as it only fixes version 1 of the strandhogg attack

**Comment by gmackall** [comment]
Heads up that I've edited the description so that the bot doesn't automatically close the main issue when this lands

**Comment by AlexV525** [comment]
@gmackall I've updated the PR as ready for review.

**Comment by AlexV525** [comment]
Also require @Hixie to see if we can test-exempt this.

**Comment by Hixie** [comment]
Given the sensitivity here, testing this might be a good idea...

**Comment by AlexV525** [comment]
I'm not familiar not don't have time for writing tests regarding the change recently. If we decide to fix the problem we might need a proper solution then.

**Comment by johnmccutchan** [comment]
I'm not sure how we can write a good test for this PR. It's just updating a template value to be set to the empty string. 

I guess we could run `flutter create` and then load the manifest xml and confirm that the value is set to the empty string?

**Comment by wildsylvan** [comment]
this breaks [flutter_web_auth](https://github.com/LinusU/flutter_web_auth) redirects to the app btw

**Comment by AlexV525** [comment]
> this breaks [flutter_web_auth](https://github.com/LinusU/flutter_web_auth) redirects to the app btw

You should be able to resolve that by defining a precise affinity.

**Pull request merged**
