### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by blasten**
`flutter update-packages --force-upgrade`

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
cc @fkorotkov , `skip:` doesn't seem to work when the change is directly below the directory with wildcards, maybe this is a misunderstanding on my part. Seems like `packages/flutter_tools/**` should pick up `packages/flutter_tools/pubspec.yaml`

**Comment by fkorotkov** [comment]
@jonahwilliams looks like a bug. Added some logging to see what GitHub API return as a list of files for a PR to be able to troubleshoot next time.

**Comment by blasten** [comment]
Should I merge this or wait until the bug is fixed?

**Comment by dnfield** [comment]
If you merge it, just make sure to watch the post submits and revert if they fail.

@fkorotkov - would it help to push an empty commit to this to force the tests to run again?

**Comment by fkorotkov** [comment]
@dnfield hm... 🤔 I don't think it will help because GitHub's API response is weird for this PR. It doesn't contain `packages/flutter_tools/pubspec.yaml`. 😳

See https://api.github.com/repos/flutter/flutter/pulls/37971/files

**Comment by fkorotkov** [comment]
It return only 30 files where it should be 40. The API endpoint [claims to return at most 300](https://developer.github.com/v3/pulls/#list-pull-requests-files).

**Comment by dnfield** [comment]
It defaults to 30 - you need to specify the `per_page` to get to 100:  https://api.github.com/repos/flutter/flutter/pulls/37971/files?per_page=100

**Comment by dnfield** [comment]
(And you can page through them by specifying the `page` parameter, e.g. https://api.github.com/repos/flutter/flutter/pulls/37971/files?per_page=100&page=1, https://api.github.com/repos/flutter/flutter/pulls/37971/files?per_page=100&page=2 - but this change is <100 files)

**Comment by jonahwilliams** [comment]
At any rate, the tests ran and this should be safe to merge

**Comment by fkorotkov** [comment]
I found it too. Added pagination already, the change will be deployed before Monday. Will update the issue once deployed.

**Pull request merged**
