### PR TITLE
Gather coverage per isolate

### PR DESCRIPTION
**Pull request by liamappelbe**
Gather coverage per isolate, rather than per source file.

Coverage was being gathered per source file so that the `libraryPredicate` could be applied to the source file URI, to filter out unwanted files. But due to the large RPC overhead, it's much faster to send one `SourceReport` RPC for the whole isolate, and filter out the `SourceReportRange`s afterwards.

I benchmarked the change by running [packages/flutter tests](https://github.com/flutter/flutter/tree/master/packages/flutter):

| Test | Time | Overhead |
|--|--|--|
| Without coverage | 4:08 | - |
| Coverage, no optimizations | 37:41 | 8.12x |
| Coverage, gather per isolate | 22:08 | 4.35x |

#100751

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
This is the exact opposite of the change I had previously made 😄 

When your project is small, the relatively large number of additional dart libraries that have coverage collected will blow up the time. Were there other changes made to coverage collection since then that I may have missed?

**Comment by liamappelbe** [comment]
> This is the exact opposite of the change I had previously made smile
> 
> When your project is small, the relatively large number of additional dart libraries that have coverage collected will blow up the time. Were there other changes made to coverage collection since then that I may have missed?

Hmmm. Not sure. Do you have an example test suite that I can benchmark where this approach is slower?

**Comment by jonahwilliams** [comment]
I would start with hello world, or perhaps a project with a large number of dependencies to the amount of source code given

**Comment by liamappelbe** [comment]
Yeah, flutter/examples/hello_world test with coverage goes from 2 seconds to 15 seconds with this PR. I'll look into moving the libraryPredicate into the service API instead.

**Pull request closed without merging**
