### PR TITLE
Fix driver tests for the examples/stocks app

### PR DESCRIPTION
**Pull request by jamesderlin**
Import `test.dart` instead of `test_api.dart`; using the latter led
to null pointer errors.

Testing Done:
* `flutter drive --target=test_driver/scroll_perf.dart`

### CODE REVIEW

**Comment by jonahwilliams** [comment]
What does this fix?

**Comment by jamesderlin** [comment]
> What does this fix?

As I mentioned in the change description, `flutter drive --target=test_driver/scroll_perf.dart` was giving me null pointer errors.

Specifically:

```
I/flutter (25113): Observatory listening on http://127.0.0.1:51715/
Unhandled exception:
NoSuchMethodError: The method 'group' was called on null.
Receiver: null
Tried calling: group("scrolling performance test", Closure: () => Null, onPlatform: null, retry: null, skip: null, solo: false, tags: null, testOn: null, timeout: null)
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      group (package:test_api/test_api.dart:179:13)
#2      main (file:///home/jamesdlin/git/flutter/flutter/examples/stocks/test_driver/scroll_perf_test.dart:11:3)
#3      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Stopping application instance.
Driver tests failed: 255

```

**Comment by jamesderlin** [comment]
And I don't really know if switching from `test_api.dart` to `test.dart` is the proper fix; I just noticed that `flutter drive --target=test_driver/scroll_perf.dart` works for the flutter_gallery example but not for the stocks example, and flutter_gallery uses `test.dart`.

**Comment by jonahwilliams** [comment]
I believe this will be fixed by the following change here: https://github.com/flutter/flutter/pull/24168.

**Pull request closed without merging**
