### PR TITLE
Add README_CN.md

### PR DESCRIPTION
**Pull request by EyreFree**
Add a README_CN.md(README.md in Chinese) file to make it easy to spread `flutter` in China and let more people have the opportunity to learn to use this amazing SDK.

### CODE REVIEW

**Comment by EyreFree** [comment]
I signed it!

**Comment by Hixie** [comment]
I'm concerned that this will easily get out of date.

**Comment by EyreFree** [comment]
@eseidelGoogle Yes, you're right, people in China will face some problems when using Google resources because of some well-known reasons, but I think more people know and be interested in `Flutter` in China will help to solve those problems. More and more people will be involved in solving the problems they face and sharing with each other, so that the status of using `Flutter` in China will continue to improve.

**Comment by EyreFree** [comment]
@Hixie I will periodically check if this file needs to be updated. I'm an iOS developer and very interested in `Flutter`, recently there are a lot of Information about `Flutter` in Chinese social media, I think this document will be helpful for the popularization of `Flutter` in China.

**Comment by Hixie** [comment]
I think, since the core Flutter team is really not currently set up to maintain documentation in multiple languages, that the best approach would be to host Chinese-specific documentation on a separate site.

**Pull request closed without merging**
