### PR TITLE
Revert "Use runTests in fuchsia tester. (#19178)"

### PR DESCRIPTION
**Pull request by zanderso**
This reverts commit 032f8cdb8b563bdc200acdce068945a834bf2271.

The test runner hangs on exit after all tests pass when trying
to roll this into Fuchsia.

### CODE REVIEW

**Comment by zanderso** [comment]
@garymm

**Comment by aam** [comment]
@cbracken it is possible. Having timestamps on the log entries could have shed the light on that :-)

**Comment by zanderso** [comment]
I'll need to land this before another engine roll attempt to unblock the Fuchsia roll.

**Review by aam — APPROVED** [review]

**Comment by zanderso** [comment]
Landing on red to help unblock the Fuchsia roll.

**Pull request merged**
