### PR TITLE
Fixed DropdownButton behavior, when keyboard is visible

### PR DESCRIPTION
**Pull request by sarbagyastha**
## Description

This PR addresses the issue with **DropdownButton** where tapping on it with an open keyboard would cause an inappropriate behavior as shown below in before(s):

Before *( in stable channel )* | After *( in stable channel )*
--- | ---
before_one | after_one
_Need to tap twice_ | _Fixed Behavior in stable_

Before *( after #40166 )* | After *( after #40166 )*
--- | ---
before_two | after_two
_Current behaviour in master channel_ | _Fixed Behavior in master_

## Related Issues
#22075 
#41881

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
Does your PR require Flutter developers to manually update their apps to accommodate your change?
- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by HansMuller** [comment]
CC @gspencergoog (who as also been working on this problem)

**Comment by dalewking** [comment]
This change didn't work for me, because there is not just one call to didChangeMetrics when this happens. With a breakpoint I see it called 3 times and your fix only takes care of the first time.

Luckily in our app we don't support orientation changes so I was able to just comment out didChangeMetrics and got it to work. That of course, is not a solution when you need to support orientation changes.

**Comment by sarbagyastha** [comment]
#42482

**Comment by yetunnaing18121996** [comment]
I have upgrading my flutter package from the latest stable channel, but the issue of Drop DownButton behavior, when keyboard is visible is not fixed. how can I do to solve this. any suggestion.

**Comment by dalewking** [comment]
Sincerely doubt it has made it to the stable channel yet.  To see the fix at the moment, probably have to be on master

**Comment by gspencergoog** [comment]
Yes, @yetunnaing18121996 , @dalewking is correct.  For right now, the fix is only available on the `master` channel.

**Pull request closed without merging**
