### PR TITLE
Update gradle lockfiles template

### PR DESCRIPTION
**Pull request by bartekpacia**
This PR updates almost* all Gradle buildscripts in the Flutter repo the `example` and `dev` (in particular, in `dev/integration_tests` and in `dev/benchmarks`) directories to apply Flutter's Gradle plugins using the declarative `plugins {}` block.

*almost, because:
- add-to-app (aka hybrid) apps are not migrated (related https://github.com/flutter/flutter/issues/138756)
- apps that purposefully use build files to ensure backward compatibility (e.g. [`gradle_deprecated_settings`](https://github.com/flutter/flutter/tree/3.16.0/dev/integration_tests/gradle_deprecated_settings))

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by bartekpacia** [comment]
[`Linux analyze` is failing with a strange error](https://github.com/flutter/flutter/pull/140115/checks?check_run_id=20046713563). Rebasing multiple times didn't help.

**Comment by bartekpacia** [comment]
Rebasing again, let's see.

**Comment by reidbaker** [comment]
I am for this but I don't think we can just remove dependency locking as a feature in the framework.

**Comment by bartekpacia** [comment]
The dependency lockfiles that are removed by this PR are `buildscript` dependencies. In other words, these lockfiles locked state of the `buildscript.classpath` [configuration](https://docs.gradle.org/current/userguide/declaring_dependencies.html).

And since we're not using `buildscript.classpath` anymore, those lockfiles are not needed. I was searching the web for a way to create lockfiles for dependencies specified in the `plugins {}` block and found these 2 issues:
- https://github.com/gradle/gradle/issues/10437
- https://github.com/gradle/gradle/issues/16593

**Comment by bartekpacia** [comment]
We'll need to generate `settings-gradle.lockfile` instead (e.g. with `./gradlew dependencies --write-locks`?).

Investigating this now.

**Review by gmackall — APPROVED** [review]
Changes to `generate_gradle_lockfiles.dart` lgtm. Just want to double check that all other changes are just generated from that change, correct? Want to make sure I'm not missing anything

**Comment by bartekpacia** [comment]
@gmackall Thank you for reviewing.

> Just want to double check that all other changes are just generated from that change, correct?

Yes, that's right. Although there are some problems with that script. I think we should also have a test that checks that running `find . -type d -name 'android' | dart dev/tools/bin/generate_gradle_lockfiles.dart` does not result in any git changes. See #142475 that I created to track this problem.

**Comment by bartekpacia** [comment]
Reason for revert: broke the tree

- [`Linux firebase_abstract_method_smoke_test`](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20firebase_abstract_method_smoke_test/15844/overview)
- [`Linux_android android_view_scroll_perf__timeline_summary`](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20android_view_scroll_perf__timeline_summary/13453/overview)
- [`Linux_android platform_views_scroll_perf__timeline_summary`](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20platform_views_scroll_perf__timeline_summary/13453/overview)
- [`Linux_pixel_7pro platform_views_scroll_perf__timeline_summary`](Linux_pixel_7pro platform_views_scroll_perf__timeline_summary)
- [`Linux_pixel_7pro platform_views_scroll_perf_impeller__timeline_summary`](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20platform_views_scroll_perf_impeller__timeline_summary/995/overview)

**Pull request merged**
