### PR TITLE
Add focus detector to CupertinoSwitch

### PR DESCRIPTION
**Pull request by MitchellGoodwin**
Addresses #101023

This PR: 

- Adds a border around the switch when focused on by the keyboard
- By default the border will be a more transparent version of the active color, but will be overwritten if provided with a `focusColor`
- Responds to keyboard input to flip the switch

Here is what it looks like in action. The top switch is not provided a focus color, the bottom one is:

https://user-images.githubusercontent.com/58190796/212970052-e4b36226-2a60-49fb-993d-40f316dc838e.mov

In comparison, this is what a native switch in the setting looks like with keyboard enabled:

https://user-images.githubusercontent.com/58190796/211917075-fb9d4d57-1649-49d6-a0c8-689f0b0e871a.mov

Issues that will need more direction on:

- Does not animate in and out like native seems to
- Is always enabled. Does not disable if keyboard navigation is off in macOS settings

I don't know if these issues should be addressed in this PR or a future one.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gspencergoog** [comment]
It looks to me like there's still a small amount of padding, border, or margin around the switch vs the Apple one:

This is the cupertino one:
213023901-ebd6c0c8-97cc-4701-af10-3fcea216f21b

Versus:
213024415-78143021-d431-4c3b-a780-9fe8a58eb5da

Any chance we can make that part look the same?

**Comment by MitchellGoodwin** [comment]
@gspencergoog That gap was deliberate from before I added the `focusColor` and made the default have transparency. I added it to make a visible difference between the focus border and the widget, which isn't needed anymore. It looks like this now:

https://user-images.githubusercontent.com/58190796/213027881-b7293e8a-d388-4c8d-aad8-98f7149c7946.mov

**Comment by gspencergoog** [comment]
Ok, cool. That looks better. The color doesn't look quite right, the Apple version seems a little less saturated, and the border looks like it's a different width by a pixel or so.  Can we sample that color and see if we can get it to match?  Ideally it would be sampled against a pure white background, but that may be hard to do.

**Comment by MitchellGoodwin** [comment]
@gspencergoog I made updates on the color and line thickness. The color seems to be changed with not just opacity, abut also brightness and saturation. From playing around with the values and some math, I've gotten pretty close:
Screenshot 2023-01-18 at 1 09 06 PM
Screenshot 2023-01-18 at 1 10 10 PM
Above is the border generated by Flutter, and the one around the switch in the settings.

Here they are blown up to similar size for comparing the border:
Screenshot 2023-01-18 at 1 15 32 PM

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Looks a lot better!

**Pull request merged**
