### PR TITLE
Dispose the AnimationController when an AnimatedSize is detached

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by goderbauer** [comment]
I believe this will cause us to lose the current animation value and status when the object is temporarily detached from the tree e.g. during a global key re-parent.

**Comment by PixelToast** [comment]
The following test covers the concerns above:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

class AnimatedSizeTest extends StatefulWidget {
  final double size;

  const AnimatedSizeTest({Key key, this.size}) : super(key: key);

  @override
  _AnimatedSizeTestState createState() => _AnimatedSizeTestState();
}

class _AnimatedSizeTestState
  extends State<AnimatedSizeTest>
  with TickerProviderStateMixin {
  @override
  Widget build(BuildContext context) {
    return AnimatedSize(
      duration: Duration(seconds: 1),
      vsync: this,
      child: SizedBox(width: widget.size, height: widget.size),
      curve: Curves.ease,
    );
  }
}

void main() {
  testWidgets('AnimatedSize animates through remount', (tester) async {
    final key = GlobalKey();

    await tester.pumpWidget(
      Column(children: [
        AnimatedSizeTest(key: key, size: 100.0),
      ]),
    );

    await tester.pumpWidget(
      Column(children: [
        AnimatedSizeTest(key: key, size: 200.0),
      ]),
    );

    await tester.pump(Duration(milliseconds: 500));

    expect(key.currentContext.size.width.round(), 180);

    // Remount
    await tester.pumpWidget(
      Column(children: [
        DecoratedBox(
          decoration: BoxDecoration(color: Colors.red),
          child: AnimatedSizeTest(key: key, size: 200.0),
        )
      ]),
    );

    await tester.pump(Duration(milliseconds: 250));

    expect(key.currentContext.size.width.round(), 196);

    await tester.pump(Duration(milliseconds: 250));

    expect(key.currentContext.size.width.round(), 200);
  });
}
```

**Comment by jason-simmons** [comment]
This is intended to fix a memory leak.

The scenario I'm seeing is that each `RenderAnimatedSize` instance creates an `AnimationController`, which then asks the `TickerProvider` to create a Ticker.

But if the `AnimationController` is never disposed, then the `Ticker` is not disposed.  So the widget acting as the `TickerProvider` accumulates an unbounded set of tickers.

@Hixie

**Comment by Hixie** [comment]
I agree with @goderbauer that this PR as written will introduce other issues, but the problem @jason-simmons describes is a real one... if we keep creating new RenderAnimatedSize objects, each one is going to create its own ticker, and they won't go away.

One solution might be to rename AnimatedSize to _AnimatedSize and then create a new AnimatedSize widget that's a StatefulWidget that mixes in SingleTickerProviderStateMixin, and whose build creates an _AnimatedSize with the vsync being itself. (That widget should probably take a `vsync` for historical reasons, but it should be ignored and deprecated.)

I wonder why we didn't do that in the first place... Am I missing something?

**Comment by goderbauer** [comment]
I don't see a good reason for the current behavior either. My suggestion on github also was to move the AnimationController into a stateful widget with a clear lifecycle.

**Comment by jason-simmons** [comment]
An attempt to implement that design: https://github.com/flutter/flutter/pull/80554

**Pull request closed without merging**
