### PR TITLE
Revert integration_test in flutter create template

### PR DESCRIPTION
**Pull request by dnfield**
Reverts #70240

This isn't ready for NNBD. Revert until it is.

Previously attempted in https://github.com/flutter/flutter/pull/74064

@jmagman fyi

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Google failure is a flake.

Windows failure is a flake - filing an issue to track that. See https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8858008542344509392/+/steps/run_test.dart_for_tool_tests_shard_and_subshard_integration/0/stdout#L6706_0

**Comment by jmagman** [comment]
Does this need a migration for people who already have this in their pubpsec from the template?

**Comment by dnfield** [comment]
That is a good question. I think the critical thing is that the template not make it to our next stable. I don't think we need to migrate though. @jonahwilliams WDYT?

**Comment by jonahwilliams** [comment]
I don't think we need to migrate people off of it - there are probably users that have started to use integration test and we can't/shouldn't stop them.

**Pull request merged**
