### PR TITLE
Addresses the proposal to add a PageView.separated widget

### PR DESCRIPTION
**Pull request by maheshj01**
This PR addresses the proposal #79018 to add a Pageview.separated widget which is analogous to [Listview.separated](https://api.flutter.dev/flutter/widgets/ListView/ListView.separated.html).
Let me know your feedback, I am open to incorporate the requested changes.

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hi @maheshmnj! Thanks for the contribution! 

It looks like this treats the separator as just another page in the `PageView`, is this the intended behavior? It does not appear to be different than just adding an index.isEven conditional to `itemBuilder` and building something else in that case.

It looks like the linked issue is not looking for the separator to be its own page, but to fill the space in between pages when `PageController.viewportFraction` is <1.0. In this PR, you have to swipe past each separator.

What do you think?

**Comment by maheshmnj** [comment]
Hi, @Piinks Thanks for taking a look

> It looks like this treats the separator as just another page in the PageView, is this the intended behavior?

Yes, you are right, it's treating each separator as a pageview. 

>It looks like the linked issue is not looking for the separator to be its own page, but to fill the space in between pages when PageController.viewportFraction is <1.0. In this PR, you have to swipe past each separator.

correct user has to swipe past each separator manually, to swipe between pages (skippping the separator)  I believe I will have to either have modify these methods animateToPage, [JumpToPage](https://github.com/flutter/flutter/blob/96f977f4df77f9f8069faa09062f58ba5836a9b5/packages/flutter/lib/src/widgets/page_view.dart#L207) etc to go to appropriate page in case of PageView.separated and also handle the [PageScrollNotification](https://github.com/flutter/flutter/blob/96f977f4df77f9f8069faa09062f58ba5836a9b5/packages/flutter/lib/src/widgets/page_view.dart#L911) to go to appropriate page when user swipes. Is that correct?

**Comment by maheshmnj** [comment]
Hi, @Piinks Thanks for taking a look

> It looks like this treats the separator as just another page in the PageView, is this the intended behavior?

Yes, you are right, it's treating each separator as a pageview. 

>It looks like the linked issue is not looking for the separator to be its own page, but to fill the space in between pages when PageController.viewportFraction is <1.0. In this PR, you have to swipe past each separator.

correct user has to swipe past each separator manually, to swipe between pages (skippping the separator)  I believe I will have to modify these methods animateToPage, [JumpToPage](https://github.com/flutter/flutter/blob/96f977f4df77f9f8069faa09062f58ba5836a9b5/packages/flutter/lib/src/widgets/page_view.dart#L207) etc to handle for PageView.separated and also handle the [PageScrollNotification](https://github.com/flutter/flutter/blob/96f977f4df77f9f8069faa09062f58ba5836a9b5/packages/flutter/lib/src/widgets/page_view.dart#L911) to go to appropriate page when user swipes. Is that correct?

**Comment by goderbauer** [comment]
I am not convinced that adding a separate constructor for this is needed. As @Piinks already points out, the same behavior can easily be achieved by adding a index.isEven conditional to itemBuilder.

**Comment by maheshmnj** [comment]
@goderbauer @Piinks  Thanks for the review, I am okay with closing this PR in that case.

**Comment by Piinks** [comment]
Thanks for the proposal @maheshmnj we appreciate the contribution. :)

**Pull request closed without merging**
