### PR TITLE
Minor PointerExitEvent class docs update :)

### PR DESCRIPTION
**Pull request by imaNNeo**
I updated PointerExitEvent class docs.
I just changed `entered` to `exited`

### CODE REVIEW

**Comment by imaNNeoFighT** [comment]
@googlebot I signed it!

**Review by Piinks — APPROVED** [review]
Oh wow! Nice find. Thank you for improving our docs @imaNNeoFighT. LGTM!

**Comment by imaNNeoFighT** [comment]
Thanks! I think it is the largest PR :))

**Comment by Hixie** [comment]
test-exempt: only affects comments

**Pull request merged**
