### PR TITLE
Remove trailing spaces in repo

### PR DESCRIPTION
**Pull request by guidezpl**
Spring cleaning

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM! Thanks for the clean-up!

**Comment by goderbauer** [comment]
I thought we have a check for this, though, that stops code with trailing spaces from getting submitted?

**Comment by goderbauer** [comment]
Oh, does that check maybe only trigger on changed lines and not existing violations?

**Comment by Hixie** [comment]
Or maybe it only checks .dart files?

Let's fix the test, then we don't need a test exemption here. :-)

**Comment by guidezpl** [comment]
It does [check all files](https://github.com/guidezpl/flutter/blob/045ba2b66171c5c47b9aa349b4221b5984bc5a89/dev/bots/analyze.dart#L527), but only modified lines. My guess is the cases this PR fixes predate the test. So fine to submit without modifying a test?

**Pull request merged**
