### PR TITLE
1.18.0-11.1.pre beta cherrypicks

### PR DESCRIPTION
**Pull request by pcsosinski**
Upgraded to v 1.17.0 today, fails to build with iOS · Issue #56567 · flutter/flutter
  - 0dc7be3bb0c3ba4bb0f9ffe06cb6769075ee4d56

Build --tree-shake-icons option crashes computer · Issue #56473 · flutter/flutter
  - dfc955a87e5e01633e2dd8d8dd179a7a4e3b6812

[Stable v1.17] pushAndRemoveUntil removing initialRoute in navigation stack · Issue #56688 · flutter/flutter
  - 1bb9f3f7180a28f270ecd7799acfa286fc8ac99a

[Suggestion] Migrating Flutter Maven repository to google() · Issue #55134 · flutter/flutter
  - f6b47a5f35c38547f2881ebc5bea1e9f5046d295
  - 793e6a48a1e679074da7f47813c138abb2f0a6f6

### CODE REVIEW

**Comment by tvolkert** [comment]
Is this ready for review?

**Comment by pcsosinski** [comment]
pending https://github.com/flutter/engine/pull/18317

@chenglu can you ack that you're okay with cherrypicking your change here?  thank you!

**Comment by pcsosinski** [comment]
thanks @chenglu I think you need to add a comment that says "@googlebot I consent."

**Comment by chenglu** [comment]
@googlebot I consent.

**Review by tvolkert — APPROVED** [review]

**Pull request merged**
