### PR TITLE
Reenable fade transition for Material page transition

### LINKED ISSUE #12877: Bring back fade transition to Material page transition
Was removed in #9472 for performance reasons. Mitigate performance issue and bring back the transition effect.

### PR DESCRIPTION
**Pull request by passsy**
Fixes #12877 by reverting #9472

### CODE REVIEW

**Comment by Hixie** [comment]
What are the performance implications of this patch?

**Comment by Hixie** [comment]
I guess we'll find out when it lands.

**Comment by Hixie** [comment]
Thanks! Landing.

**Comment by Hixie** [comment]
This massively regressed a number of our benchmarks. I'm going to revert this again for now.

**Comment by Hixie** [comment]
See https://github.com/flutter/flutter/pull/13172 for the revert.

**Comment by xster** [comment]
#13173

**Comment by passsy** [comment]
Great this project has benchmarks!

**Pull request merged**
