### PR TITLE
Implement Specific Fixes for Multi-Touch Scrolling Across Platforms

### LINKED ISSUE #11884: Scrolling with two fingers scrolls twice as fast
When scrolling a Flutter list with two fingers the list scrolls twice as fast.

In native Android or iOS apps, the list continues to scroll in regular speed even with two fingers.

Note: This is NOT specific to accessibility scrolling with two fingers. It's visible even when accessibility is disabled. However, it's also a problem for accessibility scrolling, where using two fingers are commonly used for scrolling.

### PR DESCRIPTION
**Pull request by JacobSyndeo**
Currently, when scrolling in Flutter with multiple fingers, the target platform's conventions are not respected. See #11884 and its discussion for an overview of the situation, as well as #38926 for further details.

This PR implements a solution as discussed [here](https://github.com/flutter/flutter/issues/11884#issuecomment-1813084591) and [here](https://github.com/flutter/flutter/issues/11884#issuecomment-1819814066).

In short, it adds a new enum `MultiTouchDragBehavior` which allows customization of the way multiple finger inputs are treated during scrolling.

It includes `.average`, which implements iOS-style behavior, `.last` for Android-style behavior, `.sum` for legacy behavior, as well as a `.first` in case anyone _really_ wants theirs to behave that way for some reason. It also includes a special `.platformDefault`, which lets Flutter decide which behavior is appropriate for the current platform.

Most of the modifications are in `monodrag.dart`.

Finally, this solution includes @xu-baolin's work on #136708 to support Android-style last-touch scroll behavior, albeit with slight modifications to play nice with more scrolling behaviors, such as the iOS-style `.average`, which is where most of my own effort here went.

Fixes #11884.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by JacobSyndeo** [comment]
I wanted to post this now for review and discussions' sake, but I'm currently having some difficulty writing unit tests for it.

I'm working in `monodrag_test.dart`, but in the test body, each pointer's update handler doesn't seem to provide easy access to the other pointer's activity, which presents a bit of a challenge.

This is my first contribution to Flutter, so if someone more familiar with the codebase could give me some pointers (heh) on how I should implement the unit tests here, then I'll be happy to build them out.

**Comment by xu-baolin** [comment]
@JacobSyndeo Hi, Thank you very much for your contribution to the Flutter community.
Maybe we can wait for #136708 to land before extending the iOS behavior, and the separate features will also facilitate code review.
#106552 is a previous PR that implemented the iOS behavior. There are some comments inside for your reference.

**Comment by JacobSyndeo** [comment]
@xu-baolin Thank you, sounds great. I'm looking forward to us as a community getting this longstanding issue resolved, so I'm happy to contribute!

Let's get yours merged in for now, then we can revisit the iOS side, as you said. That PR you linked is interesting, and may be better logic for the `.average` behavior than what I have here.

I still think there's value in the route you and I went down in our PRs, though, regarding [adding an enum](https://github.com/flutter/flutter/issues/11884#issuecomment-1813084591) that allows different scroll behavior to be used, as well as retaining the legacy behavior (`.sum`) in case some apps depend on that.

Mine also adds `.platformDefault`, which we may end up wanting as well.

**Review by Piinks — COMMENTED** [review]
Hi @JacobSyndeo thanks for contributing! Per the last comment, and the other PR (https://github.com/flutter/flutter/pull/136708) that is addressing the issue, I am going to close this for now.

If there are separate/additional features to follow up on after that PR, we can take a look after that change lands. 

Thanks very much for contributing!

**Pull request closed without merging**
