### PR TITLE
Now that #371 is fixed, we no longer need to check logs for "sky"

### PR DESCRIPTION
**Pull request by collinjackson**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM, but please wait on landing this patch until you've updated the SkyShell binary folks are using in the pre-built workflow.

**Comment by collinjackson** [comment]
Change is landed on engine repo, waiting for next SkyShell binary release to merge this

**Comment by abarth** [comment]
Ok.  I can push a new release

**Comment by abarth** [comment]
Done.

**Pull request merged**
