### PR TITLE
Migrate LogicalKeySet to SingleActivator

### PR DESCRIPTION
**Pull request by dkwingsmt**
This PR follows https://github.com/flutter/flutter/pull/78522, which introduced `SingleActivator` and `ShortcutActivator`, and applies the change to existing code, by replacing all occurrences of `LogicalKeySet` to `SingleActivator` or `ShortcutActivator`. 

This is part of the general keyboard project as in #44918, and resolves the shortcut problems described in https://github.com/flutter/flutter/pull/78522 in existing components.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

You might change the PR title to say "LogicalKeySet" instead of "LogicalActionSet"...

**Comment by tvolkert** [comment]
Even though this didn't break any customer tests, you should probably write a [migration guide](https://github.com/flutter/flutter/wiki/Tree-hygiene#2-evaluate-the-breaking-change-proposal) and list this as a breaking change.

The fact that several tests needed to be updated is an indication that this is likely to affect apps that use shortcuts.  It did mine 🙂

**Comment by tvolkert** [comment]
@dkwingsmt did you write a migration guide for this?

**Comment by dkwingsmt** [comment]
@tvolkert I'll do it next week. Thanks for reminder.

**Comment by dkwingsmt** [comment]
@tvolkert Sorry to have responded so late. I've tried the tests that got changed in this PR, but all of them still compile. What breakage did you encounter? The only thing I can think of is if you wanted to trigger a _system shortcut_ in a deprecated fashion (e.g. trigger `Ctrl-C` by pressing KeyC first then Control, or by holding Control and Shift then Key C). Just want to confirm if there are breakages I missed.

**Comment by tvolkert** [comment]
Here's my code that needed updating:

```dart
final Iterable<LogicalKeyboardKey> activateKeys = WidgetsApp.defaultShortcuts.entries
  .where((MapEntry<LogicalKeySet, Intent> entry) => entry.value is ActivateIntent)
  .map<LogicalKeySet>((MapEntry<LogicalKeySet, Intent> entry) => entry.key)
  .where((LogicalKeySet keySet) => keySet.keys.length == 1)
  .map<LogicalKeyboardKey>((LogicalKeySet keySet) => keySet.keys.single);
```

Again, since no client tests broke, this isn't _technically_ a breaking change according to our policy, but since we had to update so many tests in this PR, it seemed like a good indication that clients may also have to be updated, in which case I think a migration guide may help them.

**Comment by Piinks** [comment]
@dkwingsmt was a migration guide made for this?

**Comment by dkwingsmt** [comment]
No I didn't. Was about to make but was stalled by the flutter/website rework. Will do.

**Pull request merged**
