### PR TITLE
Roll packages to fix #66038

### LINKED ISSUE #66038: hotReloadVMReloadMilliseconds hot_mode_dev_cycle_macos_target__benchmark unit regression
https://flutter-flutter-perf.skia.org/e/?begin=1600280522&end=1600303326&keys=Xba25ef7f44f73f21cf9a689250c8ee38&num_commits=50&request_type=1&xbaroffset=21499.

Increasing, and continuing to go up.

### PR DESCRIPTION
**Pull request by bkonyi**
PR #65873 enabled DDS for non-web Flutter applications. This change surfaced a bug where DDS would not send ServiceRegistered events to VM service clients when they subscribed to the Service stream. This would cause tools and tests that rely on these events (e.g., hot reload in VSCode) to fail.

Fixes #66038.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
This is likely causing a whole host of other CI issues. Consider landing on red after CI has finished if the build is still red

**Comment by bkonyi** [comment]
> This is likely causing a whole host of other CI issues. Consider landing on red after CI has finished if the build is still red

SGTM. I'm actually surprised nothing failed before landing...

**Comment by skia-gold** [comment]
Gold has detected about 3 untriaged digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/66052

**Comment by bkonyi** [comment]
Merge on red to fix CI issues.

**Pull request merged**
