### PR TITLE
Revert "Reland Reland engine display features"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#93117

Really sorry about this, but the Engine roll is 40+ commits behind, and other failures are being masked by this one. I'm going to start getting the trees untangled by rolling this back along with the companion change in the Engine: flutter/engine#29574

### CODE REVIEW

**Comment by andreidiaconu** [comment]
Third time's a charm. Please let me know if I can help in any way.

**Comment by andreidiaconu** [comment]
> /cc @blasten @andreidiaconu The Engine roll is super backed up on #93226 and #93225. Please hold off on re-landing this work until the Engine backlog has cleared. Sorry for the inconvenience!

#93226 is closed and #93225 is no longer a P0. Can we try to reland this?

**Comment by zanderso** [comment]
I should have noted this originally, but the remaining failure on CI that led to the reverts was just this one:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20flutter_engine_group_performance/912/overview

If you know how to keep that one from failing again, then I think you can try to reland.

**Comment by andreidiaconu** [comment]
Ok, I fixed that one in https://github.com/flutter/flutter/pull/93240 and I think we are ready to try and reland.

**Pull request merged**
