### PR TITLE
Roll Dart SDK to 2.0.0-dev.8.0

### PR DESCRIPTION
**Pull request by mit-mit**
Roll Dart SDK to 2.0.0-dev.8.0

Remove all places where `--assert-initializer` is passed, as this feature is always-on, and thus not a supported option, in Dart 2: https://github.com/dart-lang/sdk/commit/fa57f54572bb006b4a7e8f9b946285f5498721df

### CODE REVIEW

**Comment by a14n** [comment]
I tried the same roll some times ago and regarding the issue reported I prefered to wait for the support of type parameters in constructors.

**Comment by mit-mit** [comment]
Yes, looks like there are a bunch of analysis issues to tackle. Do you have a link to the type parameter issue?

**Comment by a14n** [comment]
Several issues : dart-lang/sdk#30355, dart-lang/sdk#26392, dart-lang/sdk#26391 ...

**Comment by mit-mit** [comment]
Here is a direct link to the analysis issues we are seeing: https://travis-ci.org/flutter/flutter/jobs/306314548

**Comment by mit-mit** [comment]
@a14n I'm not sure I understand the relationship between those language feature request and the concrete analysis issues I linked to?

**Comment by a14n** [comment]
for instance [the following code](https://github.com/flutter/flutter/blob/167382480afdfa9eb8f217e084e7abdc6330dd69/dev/benchmarks/microbenchmarks/lib/common.dart#L53-L57) reports 2 issues:

```dart
return JSON.encode(new Map<String, double>.fromIterable(
  _results,
  key: (_BenchmarkResult result) => result.name,
  value: (_BenchmarkResult result) => result.value,
));
```

```
[hint] A function of type '(_BenchmarkResult) → double' can't be assigned to a variable of type '(dynamic) → double'. (dev/benchmarks/microbenchmarks/lib/common.dart, line 56, col 14)
[hint] A function of type '(_BenchmarkResult) → String' can't be assigned to a variable of type '(dynamic) → String'. (dev/benchmarks/microbenchmarks/lib/common.dart, line 55, col 12)
```

If the above language features  was implemented we could fix them with


```diff
-return JSON.encode(new Map<String, double>.fromIterable(
+return JSON.encode(new Map<String, double>.fromIterable<_BenchmarkResult>(
  _results,
  key: (_BenchmarkResult result) => result.name,
  value: (_BenchmarkResult result) => result.value,
));
```

But without that we have to do one of the following alternative:

- use an unsafe property access (no check on property names by analyzer):
  ```diff
  return JSON.encode(new Map<String, double>.fromIterable(
    _results,
  -  key: (_BenchmarkResult result) => result.name,
  -  value: (_BenchmarkResult result) => result.value,
  +  key: (dynamic result) => result.name,
  +  value: (dynamic result) => result.value,
  ));
  ```

- use a cast (but not allowed by `avoid_as` lint):
  ```diff
  return JSON.encode(new Map<String, double>.fromIterable(
    _results,
  -  key: (_BenchmarkResult result) => result.name,
  -  value: (_BenchmarkResult result) => result.value,
  +  key: (dynamic result) => (result as _BenchmarkResult).name,
  +  value: (dynamic result) => (result as _BenchmarkResult).value,
  ));
  ```

- use a downcast (but it's really ugly):
  ```diff
  return JSON.encode(new Map<String, double>.fromIterable(
    _results,
  -  key: (_BenchmarkResult result) => result.name,
  -  value: (_BenchmarkResult result) => result.value,
  +  key: (dynamic result) { _BenchmarkResult r = result; return r.name; },
  +  value: (dynamic result) { _BenchmarkResult r = result; return r.value; },
  ));
  ```

None of the workaround above looks good to me.
There are perhaps other alternatives. @floitschG : any advices ?

**Comment by mit-mit** [comment]
cc @leafpetersen @lrhn

**Comment by floitschG** [comment]
For the `Map.fromIterable` I just proposed a change that would relax the typing so that these functions would work again: https://dart-review.googlesource.com/23440

It's still untested (want to know first, if that's what we want to do).

**Comment by devoncarew** [comment]
@floitschG, I imagine your change to `Map.fromIterable` would take a while to land (as in, not in the timeframe of this PR)?

@Hixie, do any of the above look like reasonable alternatives? Another option is to land with `// ignore:s`.

**Comment by munificent** [comment]
A little more context: these warnings are coming from the ongoing plan to remove support for "fuzzy arrows" in 2.0. The main tracking bug for that is https://github.com/dart-lang/sdk/issues/29630.

**Comment by leafpetersen** [comment]
Two additional ways to work around this:

Via a library of static helper methods, e.g.

```dart
// constructors.dart
import 'dart:core' as core;
class Map {
  static core.Map<K, V> fromIterable<K, V, T>(core.Iterable<T> items, {K Function(T) key, V Function(T) value}) {
    var map = <K, V>{};
    for(var item in items) {
      map[key(item)] = value(item);
    } 
    return map;
  } 
}

// flutter_file.dart
import 'constructors.dart' as constructors;

return JSON.encode(constructors.Map.fromIterable(
  _results,
  key: (_BenchmarkResult result) => result.name,
  value: (_BenchmarkResult result) => result.value,
));
```

Using `Iterable.forEach`

```dart
var map = <String, double>{}'
_results.forEach((result) => map[result.name] = result.value);
return JSON.encode(map);
```

**Comment by mit-mit** [comment]
I'm going to close this PR for now, as we are not ready to land this. We'll make another attempt soon hopefully.

https://github.com/flutter/flutter/issues/13214 was opened to track the only non-language related change (the removal of `--assert-initializer`)

**Pull request closed without merging**
