### PR TITLE
Reland Add UI Benchmarks

### PR DESCRIPTION
**Pull request by bernaferrari**
Reland https://github.com/flutter/flutter/pull/143799 which is part 1 of https://github.com/flutter/flutter/pull/138481 and https://github.com/flutter/flutter/issues/146211.

Could someone run this in device-lab so we are 100% sure it works? I don't know if it was a flake or what last time. Locally it works well.

### CODE REVIEW

**Comment by bernaferrari** [comment]
Is there anything I need to make such as reduce the test to make it lighter, or should I try to reland? In my machine it didn't take so many minutes.

**Comment by jmagman** [comment]
> Is there anything I need to make such as reduce the test to make it lighter, or should I try to reland? In my machine it didn't take so many minutes.

I vote try to reland, if you don't think your test should take much time.

**Comment by bernaferrari** [comment]
I made it twice as fast (if it is still slow, I can reduce further the number of iterations). I think it is ready for review. I'm terrified about it breaking the tree (again).

**Comment by bernaferrari** [comment]
Ok, sorry (didn't see anything on IDE side). Checks working now.

**Comment by jmagman** [comment]
@jtmcdole can you review or find someone to review? This fell between the cracks.

**Comment by jtmcdole** [comment]
I'll take a look tomorrow

**Review by jtmcdole — COMMENTED** [review]
One comment but this is directionally correct.

**Review by jtmcdole — APPROVED** [review]

**Pull request merged**
