### PR TITLE
Revert "Show search app bar theme"

### PR DESCRIPTION
**Pull request by clocksmith**
Reverts flutter/flutter#37962

This PR was reverted because it introduced unintended font and icon color changes. Originally the appBar's default text style was Theme.primaryTextTheme and its icon theme was Theme.primaryIconTheme. PR #37962 mistakenly changed these values to Theme.textTheme and Theme.iconTheme respectively.

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by flar** [comment]
The tree is now green except for 3 tests that only fail because the macs involved have artifacts on them that they can't delete. I'm going to squash and merge so that this can make a new roll candidate once the macs are fixed and brought back online.

**Comment by Hixie** [comment]
When reverting things please remember to say why, to make future archaeology easier. Thanks.

**Comment by HansMuller** [comment]
@Hixie - updated the description to explain the rationale for reverting.

**Pull request merged**
