### PR TITLE
Bump AGP/Gradle/Kotlin warn versions

### PR DESCRIPTION
**Pull request by gmackall**
Bumps the versions up a bit, so we can keep people moving forward.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by bkonyi** [comment]
@gmackall do you want a review on this? :)

**Comment by gmackall** [comment]
> @gmackall do you want a review on this? :)

Sure, thanks for reminding me! I wanted to let the tests finish running before requesting, but I must have closed the tab

**Review by camsim99 — COMMENTED** [review]
This LGTM but I do want to ask if there's a reason behind these specific versions at this time, e.g. we are trying to get to particular versions by X time?

**Comment by gmackall** [comment]
> This LGTM but I do want to ask if there's a reason behind these specific versions at this time, e.g. we are trying to get to particular versions by X time?

No specific driving reason this time, just to keep our window from growing too large (versions are getting released faster than we drop support) and keep users up to date

**Review by camsim99 — APPROVED** [review]

**Pull request merged**
