### PR TITLE
[macOS] codesign native assets during embed

### LINKED ISSUE #148051: [macOS] Code-signing native assets
Currently App.framework and FlutterMacOS.framework are codesigned in `macos_assemble.sh`:

https://github.com/flutter/flutter/blob/607a3dad768d326fb9fb1ac24e6a2fc92303a6ab/packages/flutter_tools/bin/macos_assemble.sh#L180-L183

I think same thing should be done for native assets, otherwise they keep the adhoc signature, which fails to load at runtime with SIP enabled:
```
`.../native_regex_pcre2.framework/Versions/A/native_regex_pcre2` not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)
```

(not sure if this is also relevant for iOS, but if the codesigning is part of assemble it might)

cc @dcharkes

### PR DESCRIPTION
**Pull request by knopp**
Fixes https://github.com/flutter/flutter/issues/148051

Currently only the "embed" phase, which is run during the Runner target build have access to code-signing identity. The flutter assemble target, which does the main build (and also builds native assets) does not have access to the code-signing identity.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by knopp** [comment]
@dcharkes, any idea if this is testable (and how)? Also this PR leaves all the dart codesigning paths unchanged. Those are not really used (the code-signing identity define is never set).

**Comment by dcharkes** [comment]
> @dcharkes, any idea if this is testable (and how)? Also this PR leaves all the dart codesigning paths unchanged. Those are not really used (the code-signing identity define is never set).

We can only test this with an integration test. A test that actually runs `flutter build` and/or `flutter run`. And then we need to look in the app bundle to see if the framework/dylib is signed.

https://github.com/flutter/flutter/blob/cb656c21f082c400a169050f59c30023ae14c5c2/packages/flutter_tools/test/integration.shard/isolated/native_assets_test.dart#L285

We should probably use some kind of commandline tool to inspect what signature the dylib is signed with and check that it's the right one (or the same one as the flutter framework).

**Comment by knopp** [comment]
The problem here is that the dylibs are already codesigned through `codesignDylib` with adhoc certificate. There are two issues with this 

a) the codesigning is performed twice (second time replacing the first signature),
b) unless the test is run with an actual code-signing identity (i don't know if and how we can do this), it will simply resign the binaries with another adhoc signature so we can't really verify this.

Possible option would be to disable codesigning of macOS native assets in code and only do it in the script, in which case we should be able to verify the signature in tests.

**Comment by knopp** [comment]
The annoying part about this is that this diverges the macOS / iOS implementation even further. On iOS codesigning through code should work, since it's part of the Runner target and thus has access to identity. 

@jmagman, do you know why on macOS Flutter assemble is handled as a separate Xcode target? It would be much easier if everything was handled in the Runner target, but pragmatically, even if doable, that'd be a pretty big change and just the migration itself would likely require some significant xcode project surgery.

**Comment by knopp** [comment]
@dcharkes, I disabled adhoc code-signing of macOS dylib in dart code (`_copyNativeAssetsMacOS`) unless actual identity is provided and added test that will fail when `macos_assemble.sh` doesn't codesign native assets.

Note that as far as I can tell there is currently no way to provide code-signing identity in a way that would reach `_copyNativeAssetsMacOS`. There however might be in future, for example if the `BuildFrameworkCommand` is amended to parse `dCodesignIdentity`, which right now it doesn't seem to.

**Comment by jmagman** [comment]
> @jmagman, do you know why on macOS Flutter assemble is handled as a separate Xcode target? It would be much easier if everything was handled in the Runner target, but pragmatically, even if doable, that'd be a pretty big change and just the migration itself would likely require some significant xcode project surgery.

I totally agree, the divergence has been completely annoying and added so much work over the years.
I would _love_ if someone undertook the work to converge the iOS and macOS projects (xcode_backend.dart vs sh, extensive target/build phase Xcode project file surgery, or even combining the iOS/macOS project directories into a single `darwin` Xcode project).  The macOS tooling implementation has lagged so far behind iOS in the last 5 years, for example https://github.com/flutter/flutter/pull/94747, all the macOS spew that gets logged to stderr, etc

**Comment by dcharkes** [comment]
> @dcharkes, I disabled adhoc code-signing of macOS dylib in dart code (`_copyNativeAssetsMacOS`) unless actual identity is provided and added test that will fail when `macos_assemble.sh` doesn't codesign native assets.

👍 

The test is failing on the CI atm.

**Comment by knopp** [comment]
@dcharkes, the tests are passing now.

**Review by dcharkes — APPROVED** [review]
LGTM!

Thanks @knopp! 🙏

**Pull request merged**
