### PR TITLE
Expose showButtonMenu of PopupMenuButtonState

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
Moved (again). Original https://github.com/flutter/flutter/pull/42830; previous https://github.com/flutter/flutter/pull/44170.

## Description

It can be useful to be able to call `showButtonMenu` of a `PopupMenuButton` programmatically instead of it only being called when the user taps the button. There already is a `showMenu` function, however, that would require obtaining the position of the button manually and passing the items again. By exposing `showButtonMenu`, it is very easy to show the menu at the right place with the right items manually.

## Tests

I added the following tests:

 * Ensuring that the exposed method can be called and works correctly.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
cc @chunhtai

**Comment by Hixie** [comment]
LGTM, bonus points if you include some sample code in the documentation.

**Comment by creativecreatorormaybenot** [comment]
@Hixie See previous commit. I had to remove the sample code because it failed the checks when it was on the method documentation. I assumed that it cannot be on a method (I did not understand the CI error message).

@chunhtai said that the documentation belonged to the method instead of the class, which is why I moved it in the first place. See #44170 for context.

**Review by shihaohong — APPROVED** [review]
LGTM (mostly to allow the bot to auto merge when the tree is green)

**Pull request merged**
