### PR TITLE
Use named Image constructors

### PR DESCRIPTION
**Pull request by abarth**
Some folks didn't realize these existed and asked us to add them. By
using them in examples, hopefully folks will discover them more easily.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @HansMuller

**Comment by HansMuller** [comment]
LGTM

**Comment by Hixie** [comment]
We should make the name and src arguments positional also.

The reason I didn't use them for these cases when I added the constructors was that it doesn't really help with these specific cases, because they have so many other arguments.

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/5149 <--- shorten the names

**Pull request merged**
