### PR TITLE
Revert "Driver vm service"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#68654

```
2020-10-26T18:44:06.406463: stdout: [+2167 ms] 00:00 [32m+0[0m: simple_animation_perf[0m
2020-10-26T18:44:06.437330: stderr: [  +30 ms] VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:62612/M1oThs1rXKw=/
2020-10-26T18:44:06.559229: stderr: [ +121 ms] VMServiceFlutterDriver: Isolate found with number: 3190281009807627
2020-10-26T18:44:06.588545: stderr: [  +29 ms] VMServiceFlutterDriver: Isolate is paused at start.
2020-10-26T18:44:06.589077: stderr: [        ] VMServiceFlutterDriver: Attempting to resume isolate
2020-10-26T18:44:06.775808: stderr: [ +186 ms] VMServiceFlutterDriver: Connected to Flutter application.
2020-10-26T18:44:36.426951: stdout: [+29652 ms] 00:30 [32m+0[0m[31m -1[0m: simple_animation_perf [1m[31m[E][0m[0m
2020-10-26T18:44:36.427865: stdout: [   +1 ms]   TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
2020-10-26T18:44:36.445490: stdout: [  +17 ms]   package:test_api/src/backend/invoker.dart 318:28  Invoker._handleError.<fn>
stdout: [        ]   dart:async/zone.dart 1182:47                      _rootRun
stdout: [        ]   dart:async/zone.dart 1093:19                      _CustomZone.run
2020-10-26T18:44:36.445699: stdout: [        ]   package:test_api/src/backend/invoker.dart 316:10  Invoker._handleError
stdout: [        ]   package:test_api/src/backend/invoker.dart 272:9   Invoker.heartbeat.<fn>.<fn>
stdout: [        ]   dart:async/zone.dart 1190:13                      _rootRun
2020-10-26T18:44:36.446182: stdout: [        ]   dart:async/zone.dart 1093:19                      _CustomZone.run
stdout: [        ]   package:test_api/src/backend/invoker.dart 271:38  Invoker.heartbeat.<fn>
stdout: [        ]   dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
2020-10-26T18:44:36.446335: stdout: [        ]   dart:isolate-patch/timer_impl.dart 397:19         _Timer._runTimers
stdout: [        ]   dart:isolate-patch/timer_impl.dart 428:5          _Timer._handleMessage
stdout: [        ]   dart:isolate-patch/isolate_patch.dart 168:12      _RawReceivePortImpl._handleMessage
2020-10-26T18:44:36.455826: stdout: [   +9 ms] 00:30 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m
2020-10-26T18:44:36.457037: stderr: [   +1 ms] Unhandled exception:
stderr: [        ] Dummy exception to set exit code.
2020-10-26T18:44:36.490993: stderr: [  +33 ms] Failed to stop app
2020-10-26T18:44:36.491988: stdout: [   +1 ms] executing: /Users/flutter/.cocoon/flutter/bin/cache/artifacts/ios-deploy/ios-deploy --id 9e4363d6960ef619aad7b987353075b5fdd4ad00 --uninstall_only --bundle_id com.example.macrobenchmarks
2020-10-26T18:44:36.501859: stdout: [   +9 ms] [....] Waiting for iOS device to be connected
2020-10-26T18:44:36.524667: stdout: [  +22 ms] [....] Using 9e4363d6960ef619aad7b987353075b5fdd4ad00 (N61AP, iPhone 6 (GSM), iphoneos, arm64) a.k.a. 'Flutter Devicelab’s iPhone'.
2020-10-26T18:44:36.524798: stdout: [        ] ------ Uninstall phase ------
2020-10-26T18:44:36.866039: stdout: [ +341 ms] [ OK ] Uninstalled package with bundle id com.example.macrobenchmarks
2020-10-26T18:44:36.877101: stdout: [  +11 ms] "flutter drive" took 97,377ms.
2020-10-26T18:44:36.880200: stdout: [   +3 ms] ensureAnalyticsSent: 0ms
2020-10-26T18:44:36.881470: stdout: [   +1 ms] Running shutdown hooks
2020-10-26T18:44:36.881623: stdout: [        ] Shutdown hooks complete
2020-10-26T18:44:36.884381: stdout: [   +2 ms] exiting with code 0
2020-10-26T18:44:36.895457: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
```

See row of red.

@dnfield

### CODE REVIEW

**Comment by dnfield** [comment]
LGTM

**Comment by dnfield** [comment]
I suspect this is not the actual cause - it's not reproducing locally :(

**Comment by dnfield** [comment]
We'll see if revert passes.

**Comment by jonahwilliams** [comment]
Looks like no, I just checked the agent page and it seems like most of the mac/ios agents are down

**Comment by dnfield** [comment]
I'm going to re-revert this until we figure out what's going on

**Pull request merged**
