### PR TITLE
enable lints prefer_spread_collections and prefer_inlined_adds

### PR DESCRIPTION
**Pull request by a14n**
## Description

Enables lints [prefer_spread_collections](https://dart-lang.github.io/linter/lints/prefer_spread_collections.html) and [prefer_inlined_adds](https://dart-lang.github.io/linter/lints/prefer_inlined_adds.html)

## Related Issues

None

## Tests

None

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jonahwilliams** [comment]
The codecov bot is a little flaky right now, I'll update it so it doesn't fail anything

**Comment by a14n** [comment]
Thanks! I didn't understand what was going on with my PR.

**Review by dnfield — APPROVED** [review]
Nice! LGTM

**Comment by dnfield** [comment]
You can ignore the code coverage failure - there's another change coming into make that stop reporting red for now.

**Pull request merged**
