### PR TITLE
Remove redundant "with" from documentation

### PR DESCRIPTION
**Pull request by Timoses**
Just a little "with" in the way.

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
Thanks for the contribution!
Please sign the CLA and then I can land your patch.

**Comment by Hixie** [comment]
@Timoses any luck with signing https://cla.developers.google.com/ ?

**Comment by Hixie** [comment]
@Timoses I'm going to close this PR since you haven't had a chance to sign the CLA. Please don't hesitate to reopen it if you get a chance to do so! Thanks!

**Comment by Timoses** [comment]
Well, I did sign it which is why I responded with a 👍

**Comment by levrik** [comment]
@Timoses
> Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify. Thanks.

**Pull request closed without merging**
