### PR TITLE
Manually update DWDS version to `v.16.0.0`

### PR DESCRIPTION
**Pull request by elliette**
Runs `flutter update-packages --force-upgrade` to upgrade DWDS to `v16.0.0`

This version includes breaking changes to how DWDS is run, which is why I'm doing the update manually. Those changes are in `devfs_web.dart`.

This version of DWDS is null-safe.

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
> Golden file changes have been found for this pull request. Click [here to view and triage](https://flutter-gold.skia.org/cl/github/110822) (e.g. because this is an intentional change).
> 
> If you are still iterating on this change and are not ready to resolve the images on the Flutter Gold dashboard, consider marking this PR as a draft pull request above. You will still be able to view image results on the dashboard, commenting will be silenced, and the check will not try to resolve itself until marked ready for review.
> 
> For more guidance, visit [Writing a golden file test for `package:flutter`](https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter).
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.
> 
> _Changes reported for pull request #110822 at sha [f14ecb8](https://github.com/flutter/flutter/commit/f14ecb84e9040f43f6163d369f6bb0df7cecb25c)_

I'm rebasing upstream, which I expect to fix this

**Comment by christopherfujino** [comment]
`Windows tool_integration_tests_1_6` failure was a known flake, re-running

**Comment by elliette** [comment]
Hot restart is not working on this branch, trying to figure out the cause.

**Review by annagrin — APPROVED** [review]
LGTM!

**Comment by christopherfujino** [comment]
cc @liamappelbe

**Comment by elliette** [comment]
> Hot restart is not working on this branch, trying to figure out the cause.

Merging in recent changes from master fixes the hot restart issue, previously I was synced before https://github.com/flutter/flutter/pull/110805 so the restart regression was expected.

**Pull request merged**
