### PR TITLE
[flutter_tools] remove k toggle for canvaskit from web runner

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

The k toggle allows switching between canvaskit and html backend at runtime. unfortunately this causes hot restart to break, since the dart_sdk modules stores state at runtime.

The recommendation will be to use cavaskit via dart-defines.

### CODE REVIEW

**Review by yjbanov — APPROVED** [review]

**Comment by jonahwilliams** [comment]
@renyou the build error seems like a syncing issue, perhaps dds versions disagree?

**Comment by renyou** [comment]
> @renyou the build error seems like a syncing issue, perhaps dds versions disagree?

It seems that:

This one needs 4 arguments (this is from both GitHub ToT, and Google ToT where we ran the test):
https://github.com/flutter/flutter/blob/2c6f862bf83fff5e1d7b0d71a80304f488da36ad/packages/flutter_tools/lib/src/base/dds.dart#L21 

But only 2 are provided in this PR:
https://github.com/flutter/flutter/blob/fdb99b478a0714c08b1f79c04612edcff419bad4/packages/flutter_tools/lib/src/resident_runner.dart#L221

Am I reading this right?

**Comment by jonahwilliams** [comment]
@renyou this PR doesn't touch that code at all though, so it shouldn't matter right?

**Comment by renyou** [comment]
I think you are right.

**Pull request merged**
