### PR TITLE
Roll js and quiver

### PR DESCRIPTION
**Pull request by mit-mit**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*
Roll packages to pick up a new version of `package:quiver` that no longer depends on a deprecated Dart API.

*List which issues are fixed by this PR. You must list at least one issue.*
Related to https://github.com/dart-lang/sdk/issues/49529

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*
n/a

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by mit-mit** [comment]
Had to update the quiver one due to https://github.com/google/quiver-dart/pull/717

**Comment by mit-mit** [comment]
Autoroller already fixed this, so closing:
https://github.com/flutter/flutter/pull/117357/files

**Comment by mit-mit** [comment]
Hmm, no that roll didn't pick up quiver for some reason (which is the critical one I need rolled)

**Comment by mit-mit** [comment]
Ugh, screwed up this PR. Will open a clean one.

**Pull request closed without merging**
