### PR TITLE
Added `_ErrorDescription.toString()`

### LINKED ISSUE #106504: _ErrorDiagnostic.toString() prints "Instance of"
A helper method in the Crashlytics plugin [`recordFlutterError(FlutterErrorDetails)`](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart#L134) passes the `context` of its argument as `dynamic reason`, where `toString` is called ([#L125](https://github.com/firebase/flutterfire/blob/master/packages/firebase_crashlytics/firebase_crashlytics/lib/src/firebase_crashlytics.dart#L125)).

I believe the bug is in [`assertions.dart`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/foundation/assertions.dart#L470), where the various `_ErrorDiagnostic` subclasses spend some effort at nice formatting.

In the screenshot below (Firebase Crashlytics dashboard), I expect to see the message value, instead of _Instance of 'ErrorDescription'._

Screenshot from 2022-06-13 18-46-36

Flutter version: 3.0.2 stable

### PR DESCRIPTION
**Pull request by Danau5tin**
fixes: [#106504](https://github.com/flutter/flutter/issues/106504)

Minor change where I implemented the override of toString() in order to print a useful message in release mode as well as debug mode for an ErrorDescription. See issue for more info.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by goderbauer** [comment]
(triage) @gspencergoog Do you still have this one on your radar for review? Thanks.

**Comment by gspencergoog** [comment]
I do!  Thanks for the reminder.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by goderbauer** [comment]
(triage) @Danau5tin Looks like one of the checks got stuck and unfortunately I cannot restart it. Could you rebase this PR with master to trigger the check again?

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
