### PR TITLE
Roll engine version to c4141ff8f467dc77b44a5357b61f68f2eb808a34

### PR DESCRIPTION
**Pull request by a-siva**
includes the following CLs since the last roll
- Further improve painting.dart documentation. (https://github.com/flutter/engine/commit/43327730a27344f1d45a1f9e4d53b14260778ce5)
- Add support for --strong option in the engine, create a strong mode
  version of platform file (https://github.com/flutter/engine/commit/0f0b144b0320d00d837fb2af80cd542ab1359491)
- Apply texture transform on Android (https://github.com/flutter/engine/commit/9efcd5371a2a2b6b3be933e0d4461c316966ce01)
- [fuchsia] Removed the flutter_app template. (https://github.com/flutter/engine/commit/194fb81209e1d924cc4fb8667ff7b90cb2b46a0b)
- This adds RPC call to set asset path. (https://github.com/flutter/engine/commit/6bacf4522e36550b017a5fd43c202aa32d6b9273)
- Fix windows build by using lambda capture workaround (https://github.com/flutter/engine/commit/f6ea8f32aa502fe1cf5892b872a96820c02dd16e)
- Add missing include for sk_malloc_throw. (https://github.com/flutter/engine/commit/c4141ff8f467dc77b44a5357b61f68f2eb808a34)

### CODE REVIEW

**Comment by aam** [comment]
Lgtm

**Comment by yjbanov** [comment]
Heads up! This was submitted while the build was broken (you can see that the commits are crossed out), like this:

screen shot 2018-01-04 at 4 44 43 pm

**Comment by a-siva** [comment]
I looked at the buildbot after this was committed and the bot was green.

**Comment by yjbanov** [comment]
It's ok. Just gave you a heads up in case we might need to roll back. Normally, your PR would be marked as broken, the "Merge" button would be red, and you'd get a warning when you click it (unless you push using the command line).

**Pull request merged**
