### PR TITLE
Revert "Add finders for enableFlutterDriverExtension"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#64308

FYI @dnfield 

Broken framework tests:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8870051401946575216/+/steps/run_test.dart_for_framework_tests_shard_and_subshard_misc/0/stdout

```
00:12 +11 -1: C:\b\s\w\ir\k\flutter\packages\flutter_driver\test\src\real_tests\find_test.dart: Ancestor finder deserialize [E]                                                                        
  NoSuchMethodError: The method 'deserializeFinder' was called on null.
  Receiver: null
  Tried calling: deserializeFinder(_LinkedHashMap len:2)
  dart:core                                           Object.noSuchMethod
  package:flutter_driver/src/common/find.dart 416:25  Ancestor.deserialize
  test\src\real_tests\find_test.dart 42:33            main.<fn>
  

00:12 +12 -1: loading C:\b\s\w\ir\k\flutter\packages\flutter_driver\test\src\real_tests\io_extension_test.dart                                                                                         
00:12 +12 -1: C:\b\s\w\ir\k\flutter\packages\flutter_driver\test\src\real_tests\find_test.dart: Descendant finder serialize                                                                            
00:12 +13 -1: C:\b\s\w\ir\k\flutter\packages\flutter_driver\test\src\real_tests\extension_test.dart: ... waiting for NoPendingPlatformMessages returns until a single method channel call returns      
00:12 +14 -2: loading C:\b\s\w\ir\k\flutter\packages\flutter_driver\test\src\real_tests\io_extension_test.dart                                                                                         
00:12 +14 -2: C:\b\s\w\ir\k\flutter\packages\flutter_driver\test\src\real_tests\extension_test.dart: ... waiting for NoPendingPlatformMessages returns until both method channel calls return          
00:12 +14 -2: C:\b\s\w\ir\k\flutter\packages\flutter_driver\test\src\real_tests\find_test.dart: Descendant finder deserialize [E]                                                                      
  NoSuchMethodError: The method 'deserializeFinder' was called on null.
  Receiver: null
  Tried calling: deserializeFinder(_LinkedHashMap len:2)
  dart:core                                           Object.noSuchMethod
  package:flutter_driver/src/common/find.dart 361:25  Descendant.deserialize
  test\src\real_tests\find_test.dart 77:37            main.<fn>
  

00:12 +15 -2: loading C:\b\s\w\ir\k\flutter\packages\flutter_driver\test\src\real_tests\io_extension_test.dart    
```

### CODE REVIEW

**Comment by jonahwilliams** [comment]
landing on red to fix build

**Comment by dnfield** [comment]
LGTM

/Cc @Im-Kevin

**Comment by Im-Kevin** [comment]
already fixed #65276

**Comment by Im-Kevin** [comment]
@dnfield

**Pull request merged**
