### PR TITLE
Reland "Migrate benchmarks to package:web"

### PR DESCRIPTION
**Pull request by eyebrowsoffire**
This attempts to reland https://github.com/flutter/flutter/pull/126848

This was reverted because it made some unexpected changes to our perf measurements. After landing https://github.com/flutter/flutter/pull/127900, we have much less noise in our benchmarks, so I'd like to reland this and see if there is still a significant measurement difference.

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
You have some import errors:

```
warning • Unused import: 'package:web/web.dart' • dev/benchmarks/macrobenchmarks/lib/src/web/bench_platform_view_infinite_scroll.dart:10:8 • unused_import
  error • Undefined class 'Element' • dev/benchmarks/macrobenchmarks/lib/src/web/bench_platform_view_infinite_scroll.dart:18:11 • undefined_class
  error • Undefined name 'html' • dev/benchmarks/macrobenchmarks/lib/src/web/bench_platform_view_infinite_scroll.dart:18:38 • undefined_identifier
```

https://ci.chromium.org/p/flutter/builders/try/Linux%20analyze/57506?

**Comment by eyebrowsoffire** [comment]
> You have some import errors:
> 
> ```
> warning • Unused import: 'package:web/web.dart' • dev/benchmarks/macrobenchmarks/lib/src/web/bench_platform_view_infinite_scroll.dart:10:8 • unused_import
>   error • Undefined class 'Element' • dev/benchmarks/macrobenchmarks/lib/src/web/bench_platform_view_infinite_scroll.dart:18:11 • undefined_class
>   error • Undefined name 'html' • dev/benchmarks/macrobenchmarks/lib/src/web/bench_platform_view_infinite_scroll.dart:18:38 • undefined_identifier
> ```
> 
> https://ci.chromium.org/p/flutter/builders/try/Linux%20analyze/57506?

Thanks! Yeah I had an issue with my rebase, I think I got it resolved.

**Comment by eyebrowsoffire** [comment]
Unfortunately, the benchmark runs from the try bot still show the discrepancy on `totalUiFrame`: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_benchmarks_html/21744/overview

Looking a little closer to see if I can find the culprit.

**Pull request merged**
