### PR TITLE
Changing the flutter doctor and mac message when simulator is missing

### PR DESCRIPTION
**Pull request by gochev**
Changing the flutter doctor and mac message when simulator is missing. The location is now changed to Components and not Platforms

Before:
Screenshot 2024-10-04 at 11 04 08
After:
Screenshot 2024-10-04 at 11 04 29

The Settings in the recent MacOS version looks like this:
Screenshot 2024-10-04 at 11 09 25

No list of issues since it is trivial

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above. (not relevant)
- [X] I updated/added relevant documentation (doc comments with `///`). (not relevant)
- [X] I added new tests to check the change I am making, or this PR is [test-exempt]. (not relevant)
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported. (not relevant)
- [X] All existing and new tests are passing. (not relevant)

### CODE REVIEW

**Comment by saltedpotatos** [comment]
It looks like this was fixed in PR #156432

**Comment by bkonyi** [comment]
Closing as this has already been resolved in https://github.com/flutter/flutter/pull/156432.

**Comment by gochev** [comment]
I see the other one is actually after this one and is also lacking tests and somehow got merged. I guess you need connections :))

**Comment by gochev** [comment]
On worries ;)) thanks for the long answer . Flutter is awesome ! :)

**Pull request closed without merging**
