### PR TITLE
Update rendering smoke tests to assert a frame has been scheduled

### LINKED ISSUE #82954: examples/layout/rendering/custom_coordinate_system is broken
Currently bisecting to where this broke, but it looks like it's been a while.

We need to wire something up to actually test this.

/cc @goderbauer since we were talking about this.

### PR DESCRIPTION
**Pull request by dnfield**
Makes this target run again.

Fixes https://github.com/flutter/flutter/issues/82954

We also need a test for this to make sure it doesn't regress again.

### CODE REVIEW

**Comment by goderbauer** [comment]
Thanks for bisecting and fixing this! Any chance you could also add a regression test?

**Comment by dnfield** [comment]
Yes

**Review by goderbauer — APPROVED** [review]
LGTM

Thanks!

**Comment by dnfield** [comment]
Argh.  This cannot possibly break google testing  

@angjieli or @renyou would it make sense to disable Google testing for changes affecting only /dev?  This one does also have a small doc change though.

**Comment by angjieli** [comment]
I will take a look. We can probably skip or set the status to pass in this situation.

**Comment by dnfield** [comment]
I manually set this to pass.

**Comment by renyou** [comment]
We actually skip the test if the PR doesn't affect Google code. For this PR we picked up doc changes in `packages/flutter/lib/src/rendering/binding.dart` and some flaky tests failed. I am planning to add more deflaking to the Google test to reduce this type of noise.

**Pull request merged**
