### PR TITLE
Reexport meta from foundation.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
This wasn't quite as satisfying as I'd hoped, mostly because at the material layer (where we use `@required` a lot) we still have to import something from another layer in every file just to get the annotations.

**Comment by Hixie** [comment]
The advantage here is that if you already import foundation, which you in theory often will, then you get these for free without having to import meta/meta. The other advantage is that our imports look cleaner just importing flutter packages.

The disadvantage is that now you're getting everything else in foundation where before you only got meta.

I could go either way on this.

**Comment by abarth** [comment]
Seems sort of neutral, but LGTM if you want to land it.  The arc.dart change is good through.  :)

**Comment by Hixie** [comment]
Gonna merge this and see if I can improve it further.

**Pull request merged**
