### PR TITLE
Improve error message when Android SDK not found

### PR DESCRIPTION
**Pull request by abarth**

### CODE REVIEW

**Comment by abarth** [comment]
@devoncarew @collinjackson

**Comment by eseidelGoogle** [comment]
Definitely better.  There are a bunch of default ANDROID_HOME locations we should try at some point.

**Comment by eseidelGoogle** [comment]
lgtm!

**Comment by abarth** [comment]
I'll add that to this patch.

**Comment by abarth** [comment]
Now looks for the android SDK in the default locations.

**Pull request merged**
