### PR TITLE
Try to simplify our bot setup

### PR DESCRIPTION
**Pull request by Hixie**
This moves all the bot-related files to `dev/bots`, hiding it from our
home page in github. Also, simplifies the travis setup, though that
doesn't do any difference to the performance sadly.

### CODE REVIEW

**Comment by Hixie** [comment]
I'm testing to see how Travis handles this.

**Comment by Hixie** [comment]
I don't understand why `flutter test` hangs here. Maybe we're missing a dependency that the engine wants? (I removed dart, ubuntu-toolchain-r-test, and gcc/g++.) Trying something simpler in https://github.com/flutter/flutter/pull/3989.

**Comment by Hixie** [comment]
Well disappointingly this doesn't save any time on Travis at all.

I'll clean it up and post it for real review tomorrow. It'll require a corresponding change to the infra bots.

**Comment by Hixie** [comment]
https://codereview.chromium.org/1993843002 has the corresponding infra patch.

**Comment by Hixie** [comment]
Ok this is ready for review now.

**Comment by abarth** [comment]
LGTM

**Pull request merged**
