### PR TITLE
Fix nullability warnings in routes_test

### PR DESCRIPTION
**Pull request by gspencergoog**
This fixes the build, where some nullability check failures snuck in.

TBR= @goderbauer

### CODE REVIEW

**Comment by goderbauer** [comment]
LGTM

**Comment by aam** [comment]
This seems to have triggered few analyzer warnings on [dart flutter head-head-head buildbot](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8866911260931887856/+/steps/flutter_analyze/0/stdout):
```
▌08:35:17▐ RUNNING: cd .; bin/flutter analyze --dartdocs --flutter-repo --dart-sdk /b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk
Analyzing 3 directories...                                      

   info • Don't cast a nullable value to a non nullable type • packages/flutter/test/widgets/routes_test.dart:60:33 • cast_nullable_to_non_nullable
   info • Don't cast a nullable value to a non nullable type • packages/flutter/test/widgets/routes_test.dart:670:56 • cast_nullable_to_non_nullable
   info • Don't cast a nullable value to a non nullable type • packages/flutter/test/widgets/routes_test.dart:689:56 • cast_nullable_to_non_nullable
   info • Don't cast a nullable value to a non nullable type • packages/flutter/test/widgets/routes_test.dart:728:56 • cast_nullable_to_non_nullable
   info • Don't cast a nullable value to a non nullable type • packages/flutter/test/widgets/routes_test.dart:748:56 • cast_nullable_to_non_nullable
   info • Don't cast a nullable value to a non nullable type • packages/flutter/test/widgets/routes_test.dart:783:56 • cast_nullable_to_non_nullable
   info • Don't cast a nullable value to a non nullable type • packages/flutter/test/widgets/routes_test.dart:816:49 • cast_nullable_to_non_nullable
   info • Don't cast a nullable value to a non nullable type • packages/flutter/test/widgets/routes_test.dart:855:56 • cast_nullable_to_non_nullable
   info • Don't cast a nullable value to a non nullable type • packages/flutter/test/widgets/routes_test.dart:886:49 • cast_nullable_to_non_nullable
   info • Don't cast a nullable value to a non nullable type • packages/flutter/test/widgets/routes_test.dart:893:50 • cast_nullable_to_non_nullable
```

**Comment by gspencergoog** [comment]
@aam those are exactly the errors that this PR fixed in flutter/flutter's build. Are you sure that failure includes this PR?

**Comment by aam** [comment]
Ah, indeed it didn't. Looked at the history of the file incorrectly. Thanks!

**Pull request merged**
