### PR TITLE
Fix ios_add2app Podfile

### PR DESCRIPTION
**Pull request by dcharkes**
Fixes:

* https://github.com/flutter/flutter/issues/131261

### CODE REVIEW

**Comment by dcharkes** [comment]
@vashworth should we land this PR, or you'd rather only land changes if we actually enable this test again?

**Review by vashworth — CHANGES_REQUESTED** [review]
I think we can land this, but can you remove the changes to the `project.pbxproj`? I believe part of the test is that it successfully automates updated it

**Review by vashworth — APPROVED** [review]
LGTM

**Comment by dcharkes** [comment]
Automerge doesn't work if "Google testing" doesn't run the test image.

Manually merging.

**Pull request merged**
