### PR TITLE
Moving pointer event sanitizing to engine.

### PR DESCRIPTION
**Pull request by chunhtai**
## Description

This pr moves the pointer event sanitizing away from framework, as well as test code.

## Related Issues

https://github.com/flutter/flutter/issues/20517

## Tests

I removed a bunch of unused test.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by Piinks — COMMENTED** [review]
Looks like Cirrus is unhappy. :(

**Comment by chunhtai** [comment]
unfortunately this pr requires https://github.com/flutter/engine/pull/13697 to be merged first. After that the analyzer should pass. I should be able to merge the engine pr soon

**Comment by Piinks** [comment]
> unfortunately this pr requires [flutter/engine#13697](https://github.com/flutter/engine/pull/13697) to be merged first. After that the analyzer should pass. I should be able to merge the engine pr soon

Silly me. 😝 
Sounds good!

**Comment by mono0926** [comment]
This seems to caused #45510 and the problem remains still now.

**Pull request merged**
