### PR TITLE
Unpin DDS and roll pub packages

### PR DESCRIPTION
**Pull request by DanTup**
DDS was temporarily pinned to 4.1.0 because 4.2.0 triggered some test failures (see https://github.com/flutter/flutter/pull/147250). Those failures should be fixed by vm_service 14.2.2, so this unpins DDS and rolls both of these packages (along with devtools_shared, which is a DDS dependency).

(If the bot updates vm_service before this is done, I can rebase over that will reduce the size of this PR to just a few files)

### CODE REVIEW

**Comment by DanTup** [comment]
@bkonyi looks like the vm_service changes are failing some tests here:

```
 01:28 +4008 ~5: test/general.shard\vmservice_test.dart: setAssetDirectory forwards arguments correctly
 01:28 +4009 ~5: test/general.shard\vmservice_test.dart: setAssetDirectory forwards arguments correctly
 01:28 +4009 ~5 -1: test/general.shard\version_test.dart: version does not call git if a .version.json file exists
 01:28 +4009 ~5 -1: test/general.shard\vmservice_test.dart: setAssetDirectory forwards arguments correctly [E]
   _flutter.setAssetBundlePath: (-32000) Service connection disposed
   
 01:28 +4010 ~5 -1: test/general.shard\version_test.dart: version does not call git if a .version.json file exists
 01:28 +4010 ~5 -2: test/general.shard\version_test.dart: version does not call git if a .version.json file exists
 01:28 +4010 ~5 -2: test/general.shard\vmservice_test.dart: flushUIThreadTasks forwards arguments correctly [E]
   _flutter.flushUIThreadTasks: (-32000) Service connection disposed
   
 01:28 +4011 ~5 -2: test/general.shard\version_test.dart: version does not call git if a .version.json file exists
 01:28 +4012 ~5 -2: test/general.shard\version_test.dart: version does not call git if a .version.json file exists
 01:28 +4013 ~5 -2: test/general.shard\version_test.dart: version does not call git if a .version.json file exists
 01:28 +4014 ~5 -2: test/general.shard\version_test.dart: version does not call git if a .version.json file exists
 01:28 +4015 ~5 -2: test/general.shard\vmservice_test.dart: getFlutterViews polls until a view is returned
```

Example failing test is this one:

https://github.com/flutter/flutter/blob/7920a52dd5680651118312f9be0600797ff2257e/packages/flutter_tools/test/general.shard/vmservice_test.dart#L168

I can repro locally, but it's not clear to me if what the test is doing is reasonable or not. It provides an empty stream as the input stream, which causes the method being tested to immediately be terminated as the service is disposed. I feel like it shouldn't be providing a stream that is closed before it has done its testing.. possibly it could close the stream after `setAssetDirectory` completes instead.

Thoughts? I can try the above, but want to make sure you don't think vm_service should handle this kind of code.

**Comment by bkonyi** [comment]
> It provides an empty stream as the input stream, which causes the method being tested to immediately be terminated as the service is disposed. I feel like it shouldn't be providing a stream that is closed before it has done its testing.. possibly it could close the stream after `setAssetDirectory` completes instead.

Yeah, this is a bad test. We should be using a `FakeVmService` that extends `VmService` and override the methods that are actually being called to return dummy data (I had to do something similar in google3).

**Comment by DanTup** [comment]
Got it, I'll have a go :)

**Comment by DanTup** [comment]
@christopherfujino @bkonyi I think this is good now (there's one bot outstanding as I type this, but the rest are green). There are some manual changes besides the pubspec changes to tidy up and fix some tests. You can type ".dart" in the file filter when looking at the changes to easily see the non-pubspec changes.

(cc @elliette in case you're interested in when this lands, it includes your permission-to-resume changes)

**Review by bkonyi — APPROVED** [review]

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
