### PR TITLE
fix(flutter tool): fix breakpoint mode crash for BuildableMacOSApp

### PR DESCRIPTION
**Pull request by wanglikun7342**
## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change. If you're changing visual properties, consider including before/after screenshots (and runnable code snippets to reproduce them).*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR. There should be at least one issue listed here.*

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behavior with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by wanglikun7342** [comment]
@kangwang1988

**Comment by wanglikun7342** [comment]
@dnfield

**Comment by dnfield** [comment]
This looks like it's not passing CI - can you also please provide a bug for reference? What's going wrong? What are the stack trace(s)?

**Comment by wanglikun7342** [comment]
image

**Comment by wanglikun7342** [comment]
when i build debug mac app ，build operation is ok
when i build release mac app, codesign wrong like above pic
I found the difference is app.framework, debug mac app's app.framework content more than  release mac app's
when i disable treeshakeicons , release mac app is ok, app.framework went same with debug mac app's
so treeshakeicons is not availabe when build release mac app,
the mac app which I build is flutter/devtools

**Comment by wanglikun7342** [comment]
image
image
image

**Comment by wanglikun7342** [comment]
BuildableMacOSApp extends MacOSApp extends ApplicationPackage
ApplicationPackage constructor assert id != null
  ApplicationPackage({ @required this.id })
    : assert(id != null);  
but BuildableMacOSApp constructor not pass id param to MacOSApp constructor
so when i debug and set breakpoint, flutter tool went crash for assert id != null

**Comment by wanglikun7342** [comment]
@dnfield

**Comment by dnfield** [comment]
@jonahwilliams, @jmagman or @stuartmorgan might know what's going on here.

I think you're identifying two separate problems. Tree shaking icons should not really have anything to do with code signing failures.

Could you please file some bugs with these failures and the steps to reproduce them? Also, please consider copying and pasting text rather than sharing screen shots - screen shots can't be searched as easily or copy/pasted.

**Comment by stuartmorgan** [comment]
+1 to all of that; definitely file issues, and split this into multiple PRs since the two changes being made here are, AFAICT, completely unrelated. (And for those PRs, please actually fill out the PR template; if it's all just the boilerplate its really hard to understand what the PR is about.)

**Pull request closed without merging**
