### PR TITLE
fix DefaultTextStyle not notifying updates for some changes

### PR DESCRIPTION
**Pull request by ds84182**
See #9415.

Works for me locally, so lgtm :+1:

### CODE REVIEW

**Comment by abarth** [comment]
Looks pretty good.  Two issues:

 1. Our style guide says to use `{`/`}` for functions that are more than one textual line.

 2. We need a test to make sure we don't regress.  The test can be pretty simple.  If you look in the packages/flutter/test/widgets directory, you'll see lots of examples of tests.  Basically, I would use `tester.pumpWidget` to build a `DefaultTextStyle` with a pre-built `Text` child (i.e., one that you keep in a local variable outside the `pumpWidget` call) and then use `find.byType(RichText)` to see what values actually get used in the underlying `RichText` widget.  Then, you can use `tester.pumpWidget` to make a new `DefaultTextStyle` with the exact same prebuilt `Text` child, and then again verify that one of the properties on the `RichText` that we failed to update before now gets updated.

**Comment by ds84182** [comment]
Updated, fixed style and added test

**Comment by abarth** [comment]
LGTM

Travis would like you use one more const constructor:

```
[lint] Prefer const with constant constructors. (packages/flutter/test/widgets/default_text_style_test.dart, line 26, col 29)
```

**Comment by abarth** [comment]
Thanks so much!  Once the bots go green, I'll merge your patch.

**Pull request merged**
