### PR TITLE
Less chatty

### PR DESCRIPTION
**Pull request by devoncarew**
Updates to https://github.com/flutter/flutter/pull/6197:
- output generated file count
- mention lib/main.dart
- add a newline after the doctor output

new output:

```
Creating project foo_foo2...
Wrote 52 files.

Running 'pub get' in foo_foo2...                     2.3s

[✓] Flutter is fully installed. (on Mac OS, channel unknown)
[✓] Android toolchain - develop for Android devices is fully installed. (Android SDK 22.0.1)
[✓] iOS toolchain - develop for iOS devices is fully installed. (Xcode 7.3.1)
[✓] Atom - a lightweight development environment for Flutter is fully installed.
[✓] Connected devices is fully installed.

All done! In order to run your application, type:

  $ cd foo_foo2
  $ flutter run lib/main.dart
```

@danrubel

### CODE REVIEW

**Comment by abarth** [comment]
Rather than saying "Running 'pub get' in foo_foo2", can we say "Running 'flutter packages get' in foo_foo2" ?  `flutter packages get` is what end-developers need to run in order to use the Flutter SDK source in their pubspecs.

**Comment by abarth** [comment]
LGTM

**Comment by devoncarew** [comment]
> Rather than saying "Running 'pub get' in foo_foo2", can we say "Running 'flutter packages get' 

makes sense; will update

**Comment by devoncarew** [comment]
Hmm, that needs to be updated in few places (pub.dart, and in the --pub options of a few commands). Perhaps better done as it's own PR -

**Pull request merged**
