### PR TITLE
Optimizes gesture recognizer fixes #35658

### LINKED ISSUE #35658: Optimize gesture recognizers
I skimmed through the [gesture recognizers](https://github.com/flutter/flutter/tree/master/packages/flutter/lib/src/gestures) and noticed the following unoptimized pattern.
``` dart
final LongPressStartDetails details = LongPressStartDetails(
  globalPosition: _longPressOrigin.global,
  localPosition: _longPressOrigin.local,
);
if (onLongPressStart != null)
  invokeCallback<void>('onLongPressStart',
    () => onLongPressStart(details));
```

The `details` object is unnecessarily instantiated if `onLongPressStart == null`. That instantiation should be moved into the `if` block.
``` dart
if (onLongPressStart != null) {
  final details = LongPressStartDetails(
    globalPosition: _longPressOrigin.global,
    localPosition: _longPressOrigin.local,
  );
  invokeCallback<void>(
    'onLongPressStart',
    () => onLongPressStart(details),
  );
}
```

### PR DESCRIPTION
**Pull request by hey24sheep**
## Description
Moved unwanted initialization, fixes issue #35658 

## Related Issues
#35658 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by hey24sheep** [comment]
@goderbauer I don't know who else to ask, can you review my pr. Thank You

**Review by shihaohong — APPROVED** [review]
LGTM

**Comment by hey24sheep** [comment]
@shihaohong Thank you

**Comment by hey24sheep** [comment]
@shihaohong How can l merge this?

**Comment by shihaohong** [comment]
I just merged it for you! Thank you for your contribution!

**Pull request merged**
