### PR TITLE
[CP-beta] Bump `package:unified_analytics` to `5.8.8+1`

### PR DESCRIPTION
**Pull request by eliasyishak**
This pull request is created by [automatic cherry pick workflow](https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process#automatically-creates-a-cherry-pick-request)
Please fill in the form below, and a flutter domain expert will evaluate this cherry pick request.

### Issue Link:
What is the link to the issue this cherry-pick is addressing?

Proactive fix for issue:
- https://github.com/flutter/flutter/issues/146153

More information can be found for the changes in this hotfix in the following [diff](https://github.com/dart-lang/tools/compare/unified_analytics-v5.8.8...unified_analytics-v5.8.8+1?expand=1)

### Changelog Description:
Explain this cherry pick in one line that is accessible to most Flutter developers. See [best practices](https://github.com/flutter/flutter/wiki/Hotfix-Documentation-Best-Practices) for examples

Bump the version for `package:unified_analytics` to 5.8.8+1 to better handle errors internal to the package that can crash the tool

### Impact Description:
What is the impact (ex. visual jank on Samsung phones, app crash, cannot ship an iOS app)? Does it impact development (ex. flutter doctor crashes when Android Studio is installed), or the shipping production app (the app crashes on launch)

This could potentially impact flutter developers as they are using the flutter tool

### Workaround:
Is there a workaround for this issue?

No workaround, they would need to run the flutter tool again.

### Risk:
What is the risk level of this cherry-pick?

  - [ ] Low
  - [x] Medium
  - [ ] High

### Test Coverage:
Are you confident that your fix is well-tested by automated tests?

  - [x] Yes
  - [ ] No

### Validation Steps:
What are the steps to validate that this fix works?

If this works correctly, there would be no errors from `package:unified_analytics` causing errors

### CODE REVIEW

**Comment by christopherfujino** [comment]
checksum failure:

```
Warning: one or more pubspecs have invalid dependencies. Please run "flutter update-packages --force-upgrade" to update them correctly.
```

**Comment by christopherfujino** [comment]
> checksum failure:
> 
> ```
> Warning: one or more pubspecs have invalid dependencies. Please run "flutter update-packages --force-upgrade" to update them correctly.
> ```

I ran update-packages locally and pushed a commit to update the checksum

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by eliasyishak** [comment]
@christopherfujino awesome, thanks for handling that!

**Pull request merged**
