### PR TITLE
Add skp_generator shard to LUCI config

### LINKED ISSUE #80906: Add a test for skp_generator in flutter/tests to flutter/flutter
I need to make sure that on the master branch we are running the skp_generator script in CI.

It should _not_ run in beta or stable branch CI because the skp_generator script is designed to only work with tip of tree.

### PR DESCRIPTION
**Pull request by Hixie**
Fixes flutter/flutter#80906
Depends on https://github.com/flutter/infra/pull/422

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
cc @christopherfujino

**Review by christopherfujino — APPROVED** [review]
LGTM (pending the pre-submit passes ofc)

**Comment by Hixie** [comment]
@christopherfujino clearly i did something wrong, the test isn't completing and i can't see logs...

**Comment by christopherfujino** [comment]
The builder definitely exists: https://ci.chromium.org/p/flutter/builders/try/Linux%20skp_generator. I wonder if maybe you opened this PR before new builder had propagated to LUCI, or if cocoon (which does pre-submit scheduling) had some caching? Re-triggering the build, and I'll come back to check on Monday.

**Comment by christopherfujino** [comment]
Oh annoying, I guess if it's "pending" you can't re-run.

**Comment by Hixie** [comment]
I repushed, that should do it.

**Comment by christopherfujino** [comment]
> I repushed, that should do it.

It ran and passed. This PR looks good to go.

I looked at the timestamps, and this PR was opened 7 minutes before your [infra change](https://github.com/flutter/infra/commit/ba48d3fc95dcc1c718be1ffb8ccd728b7ab2e594) was merged. I'll add a special note on the wiki page that opening this framework PR before the infra change has propagated will lead to bad times.

**Comment by Hixie** [comment]
Awesome, thanks!

**Comment by Hixie** [comment]
Checked the logs for the test and it ran as expected. Landing.

**Comment by Hixie** [comment]
This was further tweaked it https://github.com/flutter/flutter/pull/82239.

**Pull request merged**
