### PR TITLE
Upgrade all packages

### PR DESCRIPTION
**Pull request by DanTup**
This is the result of running `flutter update-packages --force-upgrade`. I can't find a way to run *all* tests locally so I'm opening the PR in the first instance to get a full CI run.

I don't know if timing of updating packages is important or if we're confident enough in the tests that this is generally at any time. I'm trying to get an updated `test` package in that fixes an issue with being able to navigate to tests from a test runner (the test framework previously reported the location of the `test` call inside the `testWidgets` function; now we get both locations).

If we should re-do this at a specific time, let me know and I'll comeback to it.

### CODE REVIEW

**Comment by xster** [comment]
LGTM

**Comment by DanTup** [comment]
@xster Tests all look good - is it safe to just merge this? I'm not sure whether we try to merge at any particular times (for ex. avoiding upgrading right before a release in case it breaks anything a test didn't catch).

**Comment by DanTup** [comment]
I'm told it's fine to land these if all the tests are passing; so I'll land when I see the build green (it's been broken for a little while; though the reason doesn't seem to match the code in the first broken changeset, so I'm not really sure what's happened there..)

**Comment by DanTup** [comment]
@Hixie @devoncarew  After I merged this, flutter_gallery_instrumentation_test has failed twice with this message:

```
stderr: FAILURE: Build failed with an exception.
stderr: 
stderr: * What went wrong:
stderr: Execution failed for task ':app:preDebugAndroidTestBuild'.
stderr: > Conflict with dependency 'com.android.support:support-annotations' in project ':app'. Resolved versions for app (27.0.0) and test app (27.1.1) differ. See https://d.android.com/r/tools/test-apk-dependency-conflicts.html for details.
stderr: 
stderr: * Try:
stderr: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
stderr: 
stderr: * Get more help at https://help.gradle.org
stderr: 
stderr: BUILD FAILED in 16s
stdout: 108 actionable tasks: 98 executed, 10 up-to-date
```

I'm unsure whether this is related - the error seems Android-y and none of these packages are `v27` but my upgrades a Dart packages; yet since that test is otherwise all green (except for one yellow flake - coincidentally on my previous change) it seems like to be the cause?

I'm not sure how best to determine with it's the cause? Should I revert this? (it's getting late here now, so feel free to have someone else revert while we investigate if I'm not responsive).

**Comment by Hixie** [comment]
We should probably revert while we investigate. To try to reproduce, you can run the devicelab test locally.

**Comment by DanTup** [comment]
This change was reverted and the devicelab test has gone back green.

**Comment by mravn-google** [comment]
The error is plugin related. Flutter plugins are pub packages, but bring in Android (and iOS) dependencies which may introduce their own conflicts. Should be solved by #18501 and once that lands, I'll try and re-land the package upgrade.

**Comment by DanTup** [comment]
>  Flutter plugins are pub packages, but bring in Android (and iOS) dependencies

Aha, of course! It seems upgrading packages is riskier than I thought (I actually only really wanted to upgrade `test` but couldn't find any way to only do the one). Thanks for the info 👍; please let me know if you re-land the upgrade :-)

**Comment by DanTup** [comment]
@zoechi This PR was re-done in https://github.com/flutter/flutter/pull/18506 after the plugin dependency was fixed; so all is good on master.

I'm not sure if it's normal for end users should be running `upgrade-packages --force-upgrade` in their beta branches; seems kinda risky. I just checked out the beta branch and ran `flutter update-packages` (**without `--force-upgrade`**) and it runs fine:

```
dantup-macbookpro:flutter dantup$ cd examples/catalog/
dantup-macbookpro:catalog dantup$ flutter run
Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...                                          
 ├─Assembling Flutter resources...                    1.4s
 └─Compiling, linking and signing...                  6.7s
Xcode build done.                                           10.0s
Syncing files to device iPhone X...                          2.8s

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on iPhone X is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".
```

I'll add some notes to that issue.

**Pull request merged**
