### PR TITLE
Use Diagnosticable a bit more.

### PR DESCRIPTION
**Pull request by jacob314**
For discussion before I add more convenience helpers to the property builder. I think adding more helpers for the common cases to the builder makes the correct patterns more discoverable and reduces the amount of boilerplate. If this looks reasonable I'm happing to add a bunch more common property patterns to the builder and refactor existing code to use them instead of creating the properties directly.

### CODE REVIEW

**Comment by Hixie** [comment]
Approach seems fine to me. cc @goderbauer

**Comment by jacob314** [comment]
Are we ok with the breaking change of adding an option to the toString. If users implemented subclasses with a zero arg to string, dart is unhappy for annoying reasons.

**Comment by goderbauer** [comment]
Looks fine to me as well. Can you link me to the breaking change? I didn't see one in the diff...

**Review by jacob314 — COMMENTED** [review]
The stealth break her is if users implement classes subclassing one of these classes and implement their own toString they will get a compile error as they are overriding a method but eliminating an optional parameter. 
The problem is Diagnosticable adds an optional named parameter to toString().

**Comment by goderbauer** [comment]
That's where it's hiding...

I'd be ok with that breaking change (we should announce it though). Is the error message from the compiler somewhat reasonable and points users in the right direction of how to fix this? I just checked, the next person to roll this into google3 will have to fix this in a hand-full of cases...

**Comment by jacob314** [comment]
The error message isn't horrible but could be better. The correct fix is
generally to delete the problem toString() on the subclass but perhaps
users could get confused and add the minLevel named parameter to their
obsolete override.

error: 'ShapeBorder.toString' ('() → String') isn't a valid override of
'Diagnosticable.toString' ('({minLevel: DiagnosticLevel}) → String').
(invalid_override at [flutter] lib/src/painting/borders.dart:292)

**Pull request closed without merging**
