### PR TITLE
Execute rename fixit

### LINKED ISSUE #2536: Execute rename fixit
We should execute the rename fixit.

 - [x] Audit all widgets for LTR basis.
 - [x] Audit the rename fixit label to generate a complete list of renames we're going to execute.
 - [x] Write the email we're going to send to flutter-dev that explains what we did.  (Don't send until later.)
 - [x] Land one pull request per rename.
 - [x] Update all documentation to match the new names.
 - [x] Update all sample code to match the new names.
 - [x] Email flutter-dev explaining what we did.
 - [x] Push the new names to alpha branch
 - [x] Update the codelab to match the new names.

### PR DESCRIPTION
**Pull request by abarth**
This pull request is a series of commits that execute the rename fixit.

Fixes #2536

### CODE REVIEW

**Comment by Hixie** [comment]
lgtm

**Comment by Hixie** [comment]
looks like you missed examples, sprites, markdown

**Comment by Hixie** [comment]
see also https://github.com/flutter/flutter/issues/2554 which lists other things we need to update

**Comment by abarth** [comment]
This is about 2/3 of the renames.  Will do the remaining 1/3 in a separate pull request.

**Pull request merged**
