### PR TITLE
Desktop default window size

### PR DESCRIPTION
**Pull request by kenvandine**
## Description

* Set the default window size for Linux and Windows desktop to 1280x720

## Checklist

- [ x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x ] I signed the [CLA].
- [ x ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ x ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [  ] I updated/added relevant documentation (doc comments with `///`).
- [  ] All existing and new tests are passing.
- [  ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ x ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ x ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jonahwilliams** [comment]
The template is just meant to be a reasonable default value. You could of course change it in your own application.

@stuartmorgan

**Comment by kenvandine** [comment]
> The template is just meant to be a reasonable default value. You could of course change it in your own application.
> 
> @stuartmorgan

Indeed it is just the default.  I don't think anyone will actually want 800x600 and as I've seen recently in a very large flutter project, the default was never changed.  I'd rather start with a more modern default, especially in a desktop app you never want 4:3 aspect.

**Comment by stuartmorgan** [comment]
> > The template is just meant to be a reasonable default value. You could of course change it in your own application.
> > @stuartmorgan
> 
> Indeed it is just the default. I don't think anyone will actually want 800x600 and as I've seen recently in a very large flutter project, the default was never changed. I'd rather start with a more modern default, especially in a desktop app you never want 4:3 aspect.

I picked 800x600 basically because I wanted something that would be pretty much guaranteed to fit on any desktop screen. I agree it's not a great default, but on the other hand I just checked a random stats page on desktop screen resolutions and it looks like somewhere in the vicinity of 5-10% of screens wouldn't necessarily fit 1280x720 once the areas not available for client application use were removed. So I think if we make the default larger, we'd need to add logic to check the available screen area and constrain the starting size to it if it's smaller. (Which I'm fine with, as I think that's generally useful enough to have in the template until a real Dart-based solution for managing window size is available, but it's not quite as simple a change.)

**Comment by kenvandine** [comment]
Actually the window manager takes this as a requested resolution and if the requested size is to large it will make the app full screen.  I tested this by setting it to 3840x2160 on my 1920x1080 desktop.  I confirmed it did in fact just go full screen.

Since it does handle this well, I'd like to go back to my original proposal to default to 1366x768.  @stuartmorgan what do you think?

**Comment by stuartmorgan** [comment]
I'd prefer 1280x720; if the goal is to shape how developers think about their layouts, then skewing slightly smaller has the advantage of reminding developers (who tend to have larger screens) to think about how their layout will look for people with smaller screens.

Have you tested Windows? If not I can do that this afternoon.

**Comment by kenvandine** [comment]
> I'd prefer 1280x720; if the goal is to shape how developers think about their layouts, then skewing slightly smaller has the advantage of reminding developers (who tend to have larger screens) to think about how their layout will look for people with smaller screens.
> 
> Have you tested Windows? If not I can do that this afternoon.

I don't have access to windows, I would appreciate it if you could test that.

**Review by stuartmorgan-g — APPROVED** [review]
The Windows behavior isn't ideal—it constrains to monitor size, without factoring in the taskbar, so the window ends up partially obscured—but it's livable for a default for now. Given that, LGTM.

**Pull request merged**
