### PR TITLE
[WIP] Roll to v0.7.3-hotfix.1 engine

### PR DESCRIPTION
**Pull request by Hixie**
This contains a minor change to the engine. This is a test of the
emergency patch process for releases.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @tvolkert

**Review by tvolkert — APPROVED** [review]
LGTM, but bots aren't happy.

**Comment by Hixie** [comment]
Looks like the engine bots didn't build the artifacts.

**Comment by Hixie** [comment]
Looks like the bots build 3930b7c0d6451994ede745e03fddd6d63400da99.

**Pull request closed without merging**
