### PR TITLE
Bump async, http, and vm_service_client packages

### PR DESCRIPTION
**Pull request by srawlins**
The thrust of this PR is bumping [async](pub.dartlang.org/packages/async) from 1.13.3 to >= 2.0.2.

async 2.0.2 introduces a fix for upcoming Dart 2.0 features, namely a new method on Timer.

However, to make the constraint solver happy, I first had to bump:

* [http](https://pub.dartlang.org/packages/http) from 0.11.3+14 to 0.11.3+16. Support for async 2.0.2 was declared in http 0.11.3+15. http 0.11.3+16 drops the dependency on [stack_trace](https://pub.dartlang.org/packages/stack_trace), which can be seen in `dev/tools/pubspec.yaml`.
* [vm_service_client](https://pub.dartlang.org/packages/vm_service_client) from 0.2.3 to 0.2.4. Support for async 2.0.2 was declared in vm_service_client 0.2.4.

After manually bumping the versions of http and vm_service_client, I ran `./bin/flutter update-packages --force-upgrade`, which successfully bumped async to 2.0.3, and resulted in this PR.

### CODE REVIEW

**Comment by srawlins** [comment]
CC @lrhn @keertip @leafpetersen

**Comment by Hixie** [comment]
> After manually bumping the versions of http and vm_service_client

I'm concerned about the need for this. In theory, the script ignores all the versions you set and just calls `pub upgrade` on a dummy pubspec.yaml that includes all the packages, set to `any`. Can you elaborate on the steps you took to build this?

**Comment by leafpetersen** [comment]
I've definitely seen non-hermetic behavior with --force-upgrade.  My general approach was to do a `git clean -xff` between each upgrade attempt, and even with that I ended up having to start in a clean client once.  

I also don't quite understand what is meant by `manually bumping` though.

@srawlins There's a fairly easy hack to get a global pubspec.yaml that you can use pubviz on if you're having trouble debugging dependencies.

**Comment by srawlins** [comment]
Sorry, I thought my procedure was the standard one. In a clean git branch, if I run `./bin/flutter update-packages --force-upgrade`, I see that `vm_service_client` is bumped from 0.2.3 to 0.2.4 (and device_info and url_launcher also bump). But http (and thus async) do not bump.

My procedure for "bumping" these was to find all of the non-transitive spots where these packages are depended on (`git grep 'http:' |grep -v TRANSITIVE |grep pubspec`), then manually edit each of those files to "bump" the version of http and vm_service_client to the version I wanted. I then ran the `update-packages` script, which updated async (it only comes transitively).

**Comment by srawlins** [comment]
Could that test failure be a flake? Passes for me locally.

**Comment by Hixie** [comment]
> But http (and thus async) do not bump.

That sounds like a bug. The script is supposed to be idempotent; running it should get the same results regardless of the input. I don't understand how it could be affected by the input, in fact, since all it does is read the package names, make a fake pubspec.yaml, run pub get on that, then take those numbers and spam them everywhere.

If you can reproduce that, please do let me know (e.g. if there's a commit where just running the script does a different thing than editing the files then running the script). I am eager to be able to reproduce this.

**Comment by Hixie** [comment]
LGTM
Sorry, I didn't mean to suggest we shouldn't land this in the meantime. LGTM.

**Pull request merged**
