### PR TITLE
Remove BottomNavigationBarItem.title deprecation

### PR DESCRIPTION
**Pull request by Piinks**
This removes the `title` parameter from `BottomNavigationBarItem`.

The replacement for which is to use label instead. This is supported by dart fix.

This deprecations has expired, as laid out in [flutter.dev/go/deprecations-removed-after-2-5](https://docs.google.com/spreadsheets/d/191-PZEOmlT7Xw6MDFFyf5HyneTaiCqI4OITtolbXD6c/edit?usp=sharing)

Part of https://github.com/flutter/flutter/issues/90287

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Piinks** [comment]
@HansMuller can you consult on the new API? I am not sure if `label` should be required now.

**Comment by Piinks** [comment]
Just waiting on an internal change to land, there were some lingering dart doc references.

**Comment by Piinks** [comment]
@goderbauer can you approve this now that everyone is migrated?

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by sentd94** [comment]
> This removes the `title` parameter from `BottomNavigationBarItem`.
> 
> The replacement for which is to use label instead. This is supported by dart fix.

How are we supposed to apply TextStyle to the label then?

**Pull request merged**
