### PR TITLE
Explicitly declare `android:exported` in examples' manifest

### PR DESCRIPTION
**Pull request by wytesk133**
This is a prerequisite for bumping the target SDK.

https://developer.android.com/about/versions/12/behavior-changes-12#exported

*List which issues are fixed by this PR. You must list at least one issue.* I don't think there is an issue filed for this yet. This only takes effect if we set target SDK >= 31.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
cc @blasten for review

**Review by blasten — APPROVED** [review]
This LGTM. There are a few more manifests that need `android:exported="true"` either now, or in the near future once they bump the target SDK version.

**Comment by Hixie** [comment]
What's the status of this PR? Is it still relevant?

**Review by Hixie — APPROVED** [review]
LGTM in case all that's blocking this is needing a second review

**Pull request merged**
