### PR TITLE
Prepare `examples` (minus `examples/api`) for `use_super_parameters`

### PR DESCRIPTION
**Pull request by goderbauer**
https://github.com/flutter/flutter/issues/100575

Excludes `examples/api`, see https://github.com/flutter/flutter/issues/100575#issuecomment-1081037991.

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Nice!  That's some super syntax!

**Comment by aam** [comment]
this seems to have caused red dart-flutter hhh bot https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8818318172012638753/+/u/flutter_test_framework_coverage/stdout
```
27:55 +5519 ~13: loading /b/s/w/ir/cache/builder/flutter/packages/flutter/test/painting/continuous_rectangle_border_test.dart                                                                          
../../examples/layers/rendering/src/sector_layout.dart:623:34: Error: The argument type 'dynamic' can't be assigned to the parameter type 'HitTestResult'.
 - 'HitTestResult' is from 'package:flutter/src/gestures/hit_test.dart' ('lib/src/gestures/hit_test.dart').
  SectorHitTestResult.wrap(super.result) : super.wrap();
                                 ^
../../examples/layers/rendering/src/sector_layout.dart:635:41: Error: The argument type 'dynamic' can't be assigned to the parameter type 'HitTestTarget'.
 - 'HitTestTarget' is from 'package:flutter/src/gestures/hit_test.dart' ('lib/src/gestures/hit_test.dart').
  SectorHitTestEntry(RenderSector super.target, { required this.radius,  required this.theta })
                                        ^
```

**Comment by goderbauer** [comment]
@aam looks like that bot is not running with the super parameter experiment enabled (available starting with SDK 2.17.0-0). I am not familiar with the bot, but somewhere you'll need to bump the lower SDK constrains to be at least 2.17.0-0.

/cc @mit-mit

**Comment by aam** [comment]
current hypothesis is that it was caused by https://dart-review.googlesource.com/c/sdk/+/239081 that landed in dart sdk, has not reached flutter repo yet.

**Pull request merged**
