### PR TITLE
dialog inherits Localizations

### PR DESCRIPTION
**Pull request by yjbanov**
/cc @HansMuller @Hixie

### CODE REVIEW

**Comment by Hixie** [comment]
This doesn't seem like the right solution. Suppose someone else came up with their own localization mechanism -- how would they plug their localization widget into the showDialog function?

**Comment by yjbanov** [comment]
@Hixie perhaps I'm misunderstanding you, but I thought that was exactly what I was fixing. Previously, if you wrapped `showDialog` in your own `Localizations` widget, `showDialog` would ignore you and default to the top-level `Localizations` object. In the test included in this PR, the custom `Localizations.override(locale: const Locale('ru', 'RU'))` would previously have no effect on the contents of the dialog and the test would fail. Note that the fix does not provide any new localization objects, but only assigns the `BuildContext` that the user passed in. We do the same for `Theme` in `showDialog`.

**Comment by Hixie** [comment]
I mean if I used a HixieLocalization widget instead of a Localization widget, how would I get showDialog to use my HixieLocalization logic? Where HixieLocalization has nothing to do with the Localization we ship in the Flutter framework.

**Comment by yjbanov** [comment]
Ah, I see. It seems the more general problem is that `InheritedWidget` operates on parents that _host_ your `BuildContext` rather than those that _created_ your widget. Here's @HansMuller's abandoned attempt to fix it: https://github.com/flutter/flutter/pull/6072.

We could resurrect that effort. However, if we decide to work within the current semantics, I can try to justify why it's reasonable to fix it this way. I think it comes down to _who's job it is to set ambient information when widgets are reparented_. For `showDialog`, which is part of `material.dart`, I think it's reasonable to set material-specific ambient information that's idiomatic to the `material.dart` library. If you are using `material.dart`, you would really be swimming against the current if you tried to use a different localization mechanism. We provide a way to extend `Localizations` with custom delegates, which is compatible with this fix. You shouldn't need to replace the whole thing.

If you have inherited widgets _other than_ `Localizations` that you want to propagate into the dialog, you can still do it by wrapping the `child` that you are passing to `showDialog`, just like this change does with `Localizations`. That would be subject to the semantics of the ambient information your inherited widget publishes, so `showDialog` wouldn't do anything about it automatically. This method would work for `HixieLocalization` too, just without help from `showDialog`.

If that's not convincing, I'm open to ideas.

**Comment by Hixie** [comment]
One could also argue that the dialog isn't "in" the place from which it was launched, it's at the top level of the app, and therefore should follow the app's own locale.

> If you have inherited widgets _other than_ `Localizations` that you want to propagate into the dialog, you can still do it by wrapping the `child` that you are passing to `showDialog`, just like this change does with `Localizations`. That would be subject to the semantics of the ambient information your inherited widget publishes, so `showDialog` wouldn't do anything about it automatically. This method would work for `HixieLocalization` too, just without help from `showDialog`.

Why is `Localizations` special? Our usual approach is not treat anything in the framework as special.

**Comment by yjbanov** [comment]
I cannot say for sure that this is the correct fix, but also not sure the reasons you provided invalidate it either. Some context for this PR: the actual problem that I'm trying to fix is localization in `showTimePicker` and `showDatePicker`. There is no way for a developer to supply `Localizations` because the developer does not instantiate the picker widgets directly. The library functions do it for you. For the date/time use-case the locale set on the dropdown invoking the picker has to be consistent with the locale in the dialog. However, we currently pop you out to the app-level locale.

> One could also argue that the dialog isn't "in" the place from which it was launched, it's at the top level of the app, and therefore should follow the app's own locale.

This is unlikely to be a reasonable default for date/time picker use-case. Also, would this logic not apply to `Theme` too? See https://github.com/flutter/flutter/blob/b5ea59d5f6ee3f3c11525baca48b6e52889b0579/packages/flutter/lib/src/material/dialog.dart#L466

> Why is `Localizations` special? Our usual approach is not treat anything in the framework as special.

`Localizations` is not treated special by anything outside `material.dart`. However, within `material.dart` it is already special because all our widgets depend on it explicitly. Because `showDialog` is part of `material.dart`, for it to be aware of `Localizations` make it no more special than it already is. Maybe I'm missing something, but this seems no different from, say, `PaginatedDataTable` treating `Localizations` as special. Adding a different localization mechanism will have no effect on material widgets. We haven't designed it this way. Instead, a developer who wants to customize `Localizations` would provide different "delegate" implementations. AFAICT this PR is compatible with that design.

**Comment by Hixie** [comment]
This logic definitely also applies to Theme. I'm not a fan of how we solved that either...

Would it make sense to solve this in the same way we solved Theme? At least then we'd have an established pattern and any solution we found for one would apply to the other...

**Comment by yjbanov** [comment]
How about, for now, I add `locale` and `textDirection` parameters to the `showTimePicker` function, like I did in `showDatePicker`? This would solve the immediate problem of not being able to choose the these parameters other than via the `MaterialApp`.

**Comment by Hixie** [comment]
Does the shadowThemeOnly approach not work?

**Comment by yjbanov** [comment]
Closing this, since this particular approach is not what we want to go with. I'll file an issue instead.

**Pull request closed without merging**
