### PR TITLE
feature: add border-radius to dropdown

### PR DESCRIPTION
**Pull request by BRO3886**
## Description

**Feature** : Border-radius for dropdown.

So, I have seen a lot of people wanting a little more customizability from the Dropdown widget..including me, and the ```dropdownColor``` property was a welcome addition. 

Therefore, I tried to make it more customisable by adding a borderRadius property for the scrim that opens when a user taps the Dropdown 

* Note: As per material-design spec, it should be 4dp always, so it takes the default ```BorderRadius.circular(2.0)``` value when the optional borderRadius parameter is not provided.

*a dropdown with borderRadius as ```BorderRadius.circular(10)```*

```dart
 child: DropdownButton<String>(
            borderRadius: BorderRadius.circular(10),
            onChanged: (val) {},
...
),
```

*default behaviour*

```dart
child: DropdownButton<String>(
            onChanged: (val) {},
....
```

## Related Issues

* None, since this is a purely UI update

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by BRO3886** [comment]
Also this is my first PR so please do tell me where I can improve

**Comment by BRO3886** [comment]
* Writing tests for borderRadius now

**Comment by PixelToast** [comment]
Thanks for the PR!

It looks like you ran dartfmt on `packages/flutter/lib/src/material/dropdown.dart`, could you revert those formatting changes?
We currently do hand-formatting for the flutter repo, see: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#formatting

**Comment by BRO3886** [comment]
> Thanks for the PR!
> 
> It looks like you ran dartfmt on `packages/flutter/lib/src/material/dropdown.dart`, could you revert those formatting changes?
> We currently do hand-formatting for the flutter repo, see: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#formatting

yeah sorry about that, I'll fix it 👍

**Comment by lazylazyllama** [comment]
What about adding `shape` instead to get more flexibility?

**Comment by BRO3886** [comment]
> What about adding `shape` instead to get more flexibility?

Adding a shape will be cool, but it might yield unexpected results, border radius is still very limited while still giving some flexibility, don't you think?

**Comment by BRO3886** [comment]
hi, I kind of figured out how to get the exact rect with the exact border radius in a unit test, but I'm not able to figure out how to get it correctly. From the logs I know its LTBR params and I have supplied the border radius param along with it and created an rrect from border-radius using `borderRadius.toRrect(<some rect>)`

Can you give a few days more until I figure this out

**Comment by BRO3886** [comment]
```dart
Rect getExpandedButtonRect() {
    final RenderBox box = tester.renderObject<RenderBox>(find.byType(dropdownButtonType));
    final Rect buttonRect = box.localToGlobal(Offset.zero) & box.size;
    return buttonRect;
  }
```

I tried to use this to get the exact rect to draw the dropdown but somehow it returns a bigger rect, I need ```Rect.fromLTRB(0.0, 8.0, 800.0, 56.0)```

**Comment by Piinks** [comment]
Hi @BRO3886, thanks for the contribution. This has not been updated in a while, and it is not in a state for code review, so I am going to close it for now. Feel free to re-open if you would like to continue working on this. Thank you!

**Pull request closed without merging**
