### PR TITLE
(BLOCKED) Remove redundant 'void' on setters

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
cc @yjbanov Hopefully this makes up a little for the added verbosity elsewhere. :-)

**Comment by Hixie** [comment]
(Note that we can't check this one in until we fix https://github.com/dart-lang/linter/issues/202.)

**Comment by abarth** [comment]
LGTM

**Comment by yjbanov** [comment]
LGTM

**Comment by Hixie** [comment]
I'm closing this for now, since it is conflict-happy.

**Pull request closed without merging**
