### PR TITLE
Avoid divide by zero in scroll thumb rectangle calculations

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by jason-simmons** [comment]
@abarth

**Comment by Hixie** [comment]
test?

**Comment by Hixie** [comment]
The key as far as testing goes here is just to verify that it doesn't crash, really, not so much that it's painting the right thing.

Though if you want to test that it's painting the right thing, the `mock_canvas` framework in the test/rendering directory may be of use. That would certainly be even awesomer.

**Comment by jason-simmons** [comment]
Added a test

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
