### PR TITLE
Fix license page app bar text color on mobile view

### LINKED ISSUE #108991: License page appBar text not visible
## Steps to Reproduce

1. Execute `flutter run` on the code sample on `web` or `desktop` platform
2. Maximize application window
3. The main license page have proper appBar bg and text color
4. The sub-section for license display have appBar bg and text both in `white` color

**Expected results:** 
Inner sub-section for license display appBar should have same color theme as main page appBar.

**Actual results:** 
Inner sub-section for license display appBar have background fixed to the scaffold color for both `light` and `dark` themes.

<details>
<summary>Code sample</summary>

```dart
// Flutter Packages
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.purple,
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.deepPurple,
          foregroundColor: Colors.white,
        ),
        useMaterial3: true,
      ),
      home: const MyLicensePage(),
    );
  }
}

class MyLicensePage extends StatelessWidget {
  const MyLicensePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return LicensePage(
      applicationIcon: Container(
        margin: const EdgeInsets.all(10),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(35),
          boxShadow: [
            BoxShadow(
              color: (Theme.of(context).brightness == Brightness.dark
                      ? Colors.white
                      : Colors.black)
                  .withOpacity(0.69),
              blurRadius: 10,
            ),
          ],
        ),
        width: 150,
        height: 150,
      ),
      applicationName: 'License Page Issue',
      applicationVersion: '-Infinity',
      applicationLegalese: 'Copyright © 2022 OutdatedGuy',
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```bash
https://jpst.it/2VNyh
```

```bash
Analyzing whats_that_anime...                                           
No issues found! (ran in 12.8s)
```

```bash
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22622.450], locale en-IN)
    • Flutter version 3.0.5 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Dell\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32526.322
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.0)
    • VS Code at C:\Users\Dell\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22622.450]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 103.0.1264.77

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<hr />

Before Scrolling the License

image

<hr />

After Scrolling the License

image

### PR DESCRIPTION
**Pull request by rekire**
This PR fixes #108991 and changes the AppBar text color to the default one so that it is readable. This is only visible on mobile devices or when your window is small.

Here is how it looks like on Windows (as example, I found this issue originally on Android):
grafik

When you start scrolling you can see that the text is white:
grafik

With my patch the text become visible again:
grafik

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

I did not write any test since I don't know how I could test this. I hope that won't break any tests.

Might be good to know to get the green app bar I'm creating the Theme like this:

```dart
final platform = Theme.of(context).platform;
const appSeedColor = Colors.green;

return MaterialApp(
  title: _title,
  theme: ThemeData.from(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(seedColor: appSeedColor),
  ),
  darkTheme: ThemeData.from(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(seedColor: appSeedColor, brightness: Brightness.dark),
  ),
  home: MyHomePage(
    title: _title,
    platform: platform,
  ),
);
```

### CODE REVIEW

**Comment by HansMuller** [comment]
The change proposed here doesn't seem unreasonable however it's causing test failures and doesn't include a regression test.

**Comment by rekire** [comment]
I'm aware of that detail, but I had not much time, trouble to understand and fix the test.

**Comment by TahaTesser** [comment]
@rekire 
Unfortunately, your fix doesn't seem to have the license title in lateral UI as reported in https://github.com/flutter/flutter/issues/108991 or in nested UI on mobile

### Your fix
Screenshot 2023-02-27 at 14 22 06


### License Page using lateral UI
Screenshot 2023-02-27 at 14 20 34


### License Page using nested UI when scrolling 
 
Screenshot 2023-02-27 at 14 23 56


Thank you for contributing.
Since the fix doesn't seem to be fixing the reported issue and failing the existing tests. I'm gonna close this.

**Comment by rekire** [comment]
Might be something has changes in the mean time, but when I opened the PR that was working for me as you can see on the screenshots I provided.

**Comment by TahaTesser** [comment]
@rekire 
I found that weird too, I'm still investigating the issue and looking into ways to fix this without failing existing tests.

**Pull request closed without merging**
