### PR TITLE
typedef RestorationId = String;

### PR DESCRIPTION
**Pull request by nmtigor**
It eases the code reading and searching.

### CODE REVIEW

**Comment by ivirtex** [comment]
No.

**Comment by goderbauer** [comment]
I don't think that another layer of indirection makes this any easier to understand.

**Comment by nmtigor** [comment]
It provides useful semantics, e.g.:
````dart
final Map<RestorationId, RestorationBucket> _claimedChildren = <RestorationId, RestorationBucket>{};
typedef RoutePresentationCallback = RestorationId Function(NavigatorState navigator, Object? arguments);
````

**Comment by Hixie** [comment]
I think I agree with @goderbauer above, the indirection doesn't really help (because it doesn't prevent you from assigning a String variable to a RestorationId variable, for example).

Thanks for your contribution, but I'm going to close this one. 😀

**Comment by nmtigor** [comment]
It's a compile time improvement. As I said, it improves code reading.

**Pull request closed without merging**
