### PR TITLE
Roll engine

### PR DESCRIPTION
**Pull request by rmacnak-google**

### CODE REVIEW

**Comment by rmacnak-google** [comment]
@lrhn Please fix your breakage.

**Comment by aam** [comment]
@rmacnak-google to unblock engine roll do you want to tell analyzer to ignore this deprecated warning?
```
    final dynamic exception = new NoSuchMethodError(5, #foo, <dynamic>[2, 4], null); // ignore: deprecated_member_use
```

**Comment by pylaligand** [comment]
This is blocking the rolls of Dart/Flutter into Fuchsia, so yes please let's add an `ignore` and fix later.

**Review by aam — APPROVED** [review]

**Comment by cbracken** [comment]
This appears to have significantly regressed some hot reload benchmarks -- e.g:

hot_mode_dev_cycle_linux__benchmark
hotReloadInitialDevFSSyncMilliseconds

**Comment by aam** [comment]
https://github.com/flutter/flutter/issues/17705

**Pull request merged**
