### PR TITLE
Exit with error message when run as root

### PR DESCRIPTION
**Pull request by cbracken**

### CODE REVIEW

**Comment by cbracken** [comment]
Fixes #8623 for Linux/macOS.

**Comment by Hixie** [comment]
How about

`Woah! You appear to be trying to run flutter as root. We strongly recommend running the flutter tool without superuser privileges.`

**Comment by Hixie** [comment]
LGTM

**Comment by goderbauer** [comment]
There only seem to be hacky approaches to detect if the user has admin rights from batch: http://superuser.com/questions/667607/check-if-current-command-prompt-was-launched-as-the-administrator

**Pull request merged**
