### PR TITLE
Remove hashes for legacy binaries that do not exist anymore

### PR DESCRIPTION
**Pull request by goderbauer**

### CODE REVIEW

**Comment by Hixie** [comment]
What is the benefit of removing these hashes? ("What problem is this solving?")

**Comment by goderbauer** [comment]
> What is the benefit of removing these hashes? ("What problem is this solving?")

* use this as a regression test to make sure that binaries that have been removed once are not accidentally re-introduced later.
* tech debt clean up
* avoid confusion; personal anecdote that got me here: I searched for one of the binaries mentioned here on github because it was mentioned in an issue and got a search hit, but was confused for minutes because I couldn't locate it in my local checkout. Only then I realized that the hit on github was the outdated reference to that binary in this script.

**Comment by Hixie** [comment]
I think it makes sense to mention in the code that the files are gone, but as far as I can tell, there's no extra cost to adding files that match these specific hashes back in. The cost, once paid, is forever.

**Comment by goderbauer** [comment]
Can you elaborate what the advantage of solving this with yet more comments (that one has to read and parse) is over just removing the hashes so nobody has to think about it ever again?

**Comment by Hixie** [comment]
My worry is that by encouraging people to edit this section when they remove binaries, we are normalizing the editing of this logic. I would much rather people never change this logic, because that way they won't ever add a binary. It's very easy for someone to add a binary, add something here, and for a reviewer to not realize what's going on, but it's much harder if this is not an area we ever touch. I'd much rather we be consistent to the point where it _always_ feels wrong to edit a line that has a comment like "Please do not modify this line".

I don't mind us removing the confusing comments if that's what would solve the confusion problem you mentioned above.

**Comment by goderbauer** [comment]
> I don't mind us removing the confusing comments if that's what would solve the confusion problem you mentioned above.

It doesn't, though. This will just bit rot again (other binaries get removed) and in due time the next person will face the same problem.

> My worry is that by encouraging people to edit this section when they remove binaries, we are normalizing the editing of this logic.

I am not buying the "slippery slope" argument here. There's always the danger of people ignoring the comment or not doing what it says regardless of what the editing history is, but I am pretty confident that people working on Flutter generally do the right thing.

I would probably change the "Please do not modify this line" comment to "Only change this if you REMOVED an entry from the list".

**Comment by Hixie** [comment]
What if someone wants to add back one of these images for some legitimate reason?

**Comment by goderbauer** [comment]
> What if someone wants to add back one of these images for some legitimate reason?

We deal with the situation when that hypothetical actually comes up? My guess would be that those binaries should be treated like we treat any other new binary: They shouldn't live in the repository. After all, we don't want to normalize adding any binary to this repository, to use your own words.

**Comment by goderbauer** [comment]
But if this is such a difficult preposition I can also just close this and move on. I didn't expect this clean-up to be this controversial. My only motivation was to to make life better for the next person coming across this so they don't have to face the same confusion I did. 🤷

**Pull request closed without merging**
