### PR TITLE
Check if location permissions are granted before asking for location.

### PR DESCRIPTION
**Pull request by edelvalle**
When compiling with Gradle 2.14.1 I got a linting warning about this; not asking if the app has the access to locations before asking for a location.

### CODE REVIEW

**Comment by edelvalle** [comment]
I signed it!

**Comment by eseidelGoogle** [comment]
@jason-simmons is the right reviewer.

**Comment by eseidelGoogle** [comment]
Thanks for the patch, btw!

**Comment by jason-simmons** [comment]
LGTM

**Pull request merged**
