### PR TITLE
Sample code for dialogs.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
I don't understand the dartdoc failure here, will have to investigate more.

**Comment by branflake2267** [comment]
Nice. Would you like to add some for the alert dialog?

**Comment by Hixie** [comment]
There's one for alert and one for simple.

**Comment by Hixie** [comment]
Ok, resolved the dartdoc issues.

**Comment by HansMuller** [comment]
LGTM

**Comment by branflake2267** [comment]
Nice job. It's going to be so easy for folks to look this up and create these. :)

**Pull request merged**
