### PR TITLE
Fix `FollowerLayer` (`CompositedTransformFollower`) has null pointer error when using with some kinds of `Layer`s

### LINKED ISSUE #100670: `FollowerLayer` (`CompositedTransformFollower`) has null pointer error when using with some kinds of `Layer`s
## Steps to Reproduce

I have found the cause and will PR.

Run the minimal reproducible sample on flutter beta.

**Expected results:** 
no error

**Actual results:** 
has error

<details>
<summary>Code sample</summary>

```dart
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('FollowerLayer has bug', (tester) async {
    final link = LayerLink();
    await tester.pumpWidget(
      CompositedTransformTarget(
        link: link,
        child: CompositedTransformFollower(
          link: link,
          child: MyWidget(),
        ),
      ),
    );
  });
}

class MyWidget extends SingleChildRenderObjectWidget {
  const MyWidget({Key? key, Widget? child}) : super(key: key, child: child);

  @override
  MyRenderObject createRenderObject(BuildContext context) => MyRenderObject();

  @override
  void updateRenderObject(BuildContext context, MyRenderObject renderObject) {}
}

class MyRenderObject extends RenderProxyBox {
  MyRenderObject({RenderBox? child}) : super(child);

  @override
  void paint(PaintingContext context, Offset offset) {
    if (layer == null) {
      layer = MyLayer(
        computeSomething: _computeSomething,
      );
    } else {
      (layer as MyLayer?)?.computeSomething = _computeSomething;
    }

    context.pushLayer(layer!, super.paint, Offset.zero);
  }

  void _computeSomething() {
    // indeed, use `globalToLocal` to compute some useful data
    globalToLocal(Offset.zero);
  }
}

class MyLayer extends ContainerLayer {
  MyLayer({required this.computeSomething});

  VoidCallback computeSomething;

  @override
  void addToScene(ui.SceneBuilder builder) {
    computeSomething(); // indeed, need to use result of this function
    super.addToScene(builder);
  }
}
```

</details>

<details>
  <summary>Logs</summary>

flutter stable

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following _CastError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      FollowerLayer.getLastTransform (package:flutter/src/rendering/layer.dart:2435:66)
#1      RenderFollowerLayer.getCurrentTransform (package:flutter/src/rendering/proxy_box.dart:5286:19)
#2      RenderFollowerLayer.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:5355:24)
#3      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2532:24)
#4      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2580:31)
#5      MyRenderObject._computeSomething (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:50:5)
#6      MyLayer.addToScene (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:61:21)
#7      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:545:5)
#8      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1105:13)
#9      FollowerLayer.addToScene (package:flutter/src/rendering/layer.dart:2567:7)
#10     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:545:5)
#11     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1105:13)
#12     LeaderLayer.addToScene (package:flutter/src/rendering/layer.dart:2270:5)
#13     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:545:5)
#14     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1105:13)
#15     TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1680:5)
#16     ContainerLayer.buildScene (package:flutter/src/rendering/layer.dart:937:5)
#17     RenderView.compositeFrame (package:flutter/src/rendering/view.dart:228:37)
#18     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1138:26)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#22     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:995:9)
#25     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#26     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:982:27)
#27     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:548:22)
#30     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#31     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:545:27)
#32     main.<anonymous closure> (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:10:18)
#33     main.<anonymous closure> (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:8:40)
#34     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +0 -1: FollowerLayer has bug [E]                                                                                                            
  Test failed. See exception logs above.
  The test description was: FollowerLayer has bug
```

flutter beta

```
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following _CastError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      FollowerLayer.getLastTransform (package:flutter/src/rendering/layer.dart:2397:66)
#1      RenderFollowerLayer.getCurrentTransform (package:flutter/src/rendering/proxy_box.dart:5286:19)
#2      RenderFollowerLayer.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:5355:24)
#3      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2534:24)
#4      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2577:31)
#5      MyRenderObject._computeSomething (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:50:5)
#6      MyLayer.addToScene (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:61:21)
#7      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#8      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
#9      FollowerLayer.addToScene (package:flutter/src/rendering/layer.dart:2560:7)
#10     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#11     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
#12     LeaderLayer.addToScene (package:flutter/src/rendering/layer.dart:2252:5)
#13     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:546:5)
#14     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:1106:13)
#15     TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1681:5)
#16     ContainerLayer.buildScene (package:flutter/src/rendering/layer.dart:938:5)
#17     RenderView.compositeFrame (package:flutter/src/rendering/view.dart:228:37)
#18     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1138:26)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#22     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:995:9)
#25     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#26     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:982:27)
#27     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:548:22)
#30     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#31     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:545:27)
#32     main.<anonymous closure> (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:10:18)
#33     main.<anonymous closure> (file:///Users/tom/RefCode/flutter_portal/test/hello_test.dart:8:40)
#34     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
00:11 +0 -1: FollowerLayer has bug [E]                                                                                                                                                                 
  Test failed. See exception logs above.
  The test description was: FollowerLayer has bug
  
00:11 +0 -1: Some tests failed.          
```

```
no errors
```

```
flutter 2.10 and flutter beta both has bug
```

</details>

### PR DESCRIPTION
**Pull request by fzyzcjy**
Please see https://github.com/flutter/flutter/issues/100670

*List which issues are fixed by this PR. You must list at least one issue.*
Close #100670

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Going to add tests, wait for a few minutes

**Comment by fzyzcjy** [comment]
Tests added

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
