### PR TITLE
CupertinoDialogAction is missing super call

### PR DESCRIPTION
**Pull request by Boehrsi**
## Description
I added the missing super call, so the CupertinoDialogAction is now able to use keys.

## Related Issues
https://github.com/flutter/flutter/issues/42729

## Tests

I added the following tests:

None, as no logic changes were applied.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

Due to time constraints i wasn't able to execute the tests / test analyzer, but as the change is pretty minimal I hope this is okay. As I plan to contribute more to the Flutter repository I will soon setup the complete Flutter development chain.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by LongCatIsLooong** [comment]
Hi @Boehrsi thank you for catching this and providing a fix! Could you add a test to verify the key works, to prevent this bug from regressing?

**Comment by Boehrsi** [comment]
I hope I find some time to setup the Flutter repo in a testable way this weekend and will add the test.

**Comment by Boehrsi** [comment]
Added one test to verify the actions are accessible via the key property. I hope the simple approach of just checking if the finder is able to locate the widgets is sufficient.

- [x] All existing and new tests are passing.
Tests passed: 5210, ignored: 32 of 5242 tests

- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
Analyzing 3 directories...
No issues found! (ran in 14.7s)

**Review by LongCatIsLooong — APPROVED** [review]
LGTM. Thank you for contributing!

**Pull request merged**
