### PR TITLE
Add Border customization to CheckboxListTile

### LINKED ISSUE #53420: Add Theme for checkbox: Change color of border in CheckboxListTile
It seems it's currently not possible to change the color of the border in `CheckboxListTile`. That's a pity, especially if you support different Themes (like white- & darkmode).

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
This adds the ability to customize the border of a `Checkbox` in a `CheckboxListTile` by passing the `side` parameter.

Fixes #53420

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by HansMuller** [comment]
This looks like a good change (sorry about the huge delay in getting it reviewed). If you're still interested in landing it, you'll just need to merge the latest checkbox changes.

**Comment by creativecreatorormaybenot** [comment]
@HansMuller the test conflicts were super nasty, so I am not sure if I got them right. if not, let me know and I will redo them. I did not have the time to properly check it right now.

**Comment by skia-gold** [comment]
Gold has detected about 16 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/89023

**Comment by HansMuller** [comment]
> @HansMuller the test conflicts were super nasty, so I am not sure if I got them right. if not, let me know and I will redo them. I did not have the time to properly check it right now.

This was such a simple PR, just created a new one with the merge issues: https://github.com/flutter/flutter/pull/93271

**Pull request closed without merging**
