### PR TITLE
Revert "delete fast reassemble code"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#102842

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
Could you please leave a quick note about WHY something was reverted in the PR description of a revert for people who later look at these and wonder why this failed? Thanks!

**Comment by zanderso** [comment]
There were test failures on CI, for example: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20tool_integration_tests_4_4/4243/overview.

The rest are flagged on https://flutter-dashboard.appspot.com/#/build?taskFilter&authorFilter&messageFilter&hashFilter=ec8693e80bf2c9f31c06d9832ebb4bccc5274440&showMac=true&showWindows=true&showiOS=true&showLinux=true&showAndroid=true&showStaging=false&repo=flutter&branch=master

**Pull request merged**
