### PR TITLE
remove Layer.replaceWith due to no usage and no tests

### LINKED ISSUE #33015: Layer.replaceWith not used, not tested; probably broken?
## Use case

Flutter provides the [Layer.replaceWith](https://api.flutter.dev/flutter/rendering/Layer/replaceWith.html) method. However, this method is neither used by Flutter itself, nor is it covered by any of Flutter's tests. I wouldn't be surprised if it's broken altogether and we just don't know about it.

## Proposal

Some options:

- Remove this method.
- Add tests to make sure this method actually works.

/cc @Hixie

### PR DESCRIPTION
**Pull request by yjbanov**
## Description

Remove Layer.replaceWith.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/33015

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change ([announcement](https://groups.google.com/forum/#!topic/flutter-announce/oY7PbdTNQ3w))
- [ ] No, this is *not* a breaking change.

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Looks ok to me pending feedback from the breaking change announcement.

**Comment by yjbanov** [comment]
It's been 2 days since the breaking change announcement. The feedback is a deafening silence :) What do we do in this case?

**Comment by Hixie** [comment]
Silence is approval. LGTM.

**Comment by Piinks** [comment]
Is this ready to be merged then?

**Review by Piinks — APPROVED** [review]
Good to go then!

**Comment by yjbanov** [comment]
I was waiting for the build to go green. Yep. Submitting. Thanks!

**Pull request merged**
