### PR TITLE
Add webdriver to build gn file for flutter driver

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Fixes flutter/fuchsia roll. is there a way to verify this is sufficient?

### CODE REVIEW

**Comment by iskakaushik** [comment]
@jonahwilliams unfortunately there is no easy way to verify this, go/flutter-cq-post-submits has a plan for verifying this post commit, but in the short term the easiest way would be to wait for the roller to try again.


LGTM

**Review by iskakaushik — APPROVED** [review]

**Comment by chingjun** [comment]
I needed to add `package:matcher` in google3, do you think that would be needed as well in gn?

**Comment by jonahwilliams** [comment]
Might as well be safe...

**Comment by chingjun** [comment]
Hold this PR, revert of web driver is coming: https://github.com/flutter/flutter/pull/47389

**Pull request closed without merging**
