### PR TITLE
[flutter_tools] Fix bad state future already completed in flutter logs

### LINKED ISSUE #138436: Future already completed in LogsCommand.runCommand
on beta/3.16.0-0.5.pre
command `flutter logs`

```
StateError: Bad state: Future already completed
at _AsyncCompleter.complete(future_impl.dart:43)
at LogsCommand.runCommand.<anonymous closure>(logs.dart:87)
at _rootRunUnary(zone.dart:1407)
at _CustomZone.runUnary(zone.dart:1308)
at _CustomZone.runUnaryGuarded(zone.dart:1217)
at _BufferingStreamSubscription._sendData(stream_impl.dart:339)
at _BufferingStreamSubscription._add(stream_impl.dart:271)
at _ForwardingStreamSubscription._add(stream_pipe.dart:123)
at _MapStream._handleData(stream_pipe.dart:218)
at _ForwardingStreamSubscription._handleData(stream_pipe.dart:153)
at _rootRunUnary(zone.dart:1407)
at _CustomZone.runUnary(zone.dart:1308)
at _CustomZone.runUnaryGuarded(zone.dart:1217)
at _BufferingStreamSubscription._sendData(stream_impl.dart:339)
at _DelayedData.perform(stream_impl.dart:515)
at _PendingEvents.handleNext(stream_impl.dart:620)
at _PendingEvents.schedule.<anonymous closure>(stream_impl.dart:591)
at _rootRun(zone.dart:1391)
at _CustomZone.run(zone.dart:1301)
at _CustomZone.runGuarded(zone.dart:1209)
at _CustomZone.bindCallbackGuarded.<anonymous closure>(zone.dart:1249)
at _rootRun(zone.dart:1399)
at _CustomZone.run(zone.dart:1301)
at _CustomZone.runGuarded(zone.dart:1209)
at _CustomZone.bindCallbackGuarded.<anonymous closure>(zone.dart:1249)
at _microtaskLoop(schedule_microtask.dart:40)
at _startMicrotaskLoop(schedule_microtask.dart:49)
at _runPendingImmediateCallback(isolate_patch.dart:118)
at _RawReceivePort._handleMessage(isolate_patch.dart:185)
```

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/138436

### CODE REVIEW

**Comment by christopherfujino** [comment]
Ahh, I probably really broke google testing

**Comment by eliasyishak** [comment]
> Ahh, I probably really broke google testing

Yeah, seems like google3 has its own LogsCommand that needs to have parameters passed to it

**Review by eliasyishak — APPROVED** [review]
Nice, LGTM!

**Comment by christopherfujino** [comment]
created internal fix at cl/583523997

**Pull request merged**
