### PR TITLE
Try dartfmt

### PR DESCRIPTION
**Pull request by blasten**
This is the diff from `dartfmt`. 

There are cases like https://github.com/dart-lang/dart_style/issues/814 in which the Analyzer will fail. I will use this PR to find out all the cases and evaluate turning `dartfmt` on for all the code under `package/flutter_tool`

Please comment if there's something you dislike about `dartfmt`.

### CODE REVIEW

**Comment by a14n** [comment]
See #25251 #30138

**Comment by christopherfujino** [comment]
Adding `    always_put_control_body_on_new_line: false` to the end of `packages/flutter_tools/analysis_options.yaml` will get rid of your control flow conflict with `dartfmt`

**Comment by dnfield** [comment]
Alternatively, always use `{}` on `if` etc. blocks.

**Comment by tvolkert** [comment]
To get less noise, you should probably run this with a column length of 100 if not 120.

**Comment by blasten** [comment]
Much better, __+5,564 −6,593__  _(column length: 120)_ vs  __+12,000 −7,814__ _(column length: 80)_

**Comment by tvolkert** [comment]
This change wreaks havoc with our brace-less if statements (it tries to put them on one line, which is almost never what you want).  As such, we can't make this change unless we require braces for all single-statement `if` (and `while`, etc.) statements.  That's a change I'd be in favor of, but we'd need to make it across the board to be consistent.

FYI: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#formatting

I still see cases where this yields less readable code.  e.g.

### Before

I must admit, this block isn't that readable to begin with, but the "after" is even worse...

```dart
    final Iterable<File> searchFiles = <Directory>[
      fs.directory(fs.path.join(Cache.flutterRoot, 'packages')),
      fs.directory(fs.path.join(Cache.flutterRoot, 'examples')),
    ].expand((Directory directory) => directory.listSync(recursive: true))
      .whereType<File>()
      .where((File file) => file.path.endsWith('.dart') || file.path.endsWith('pubspec.yaml'));
```

### After

```dart
    final Iterable<File> searchFiles = <Directory>[
      fs.directory(fs.path.join(Cache.flutterRoot, 'packages')),
      fs.directory(fs.path.join(Cache.flutterRoot, 'examples')),
    ]
        .expand((Directory directory) => directory.listSync(recursive: true))
        .whereType<File>()
        .where((File file) => file.path.endsWith('.dart') || file.path.endsWith('pubspec.yaml'));
```

### Before

```dart
  _exitFunction = exitFunction ?? (int exitCode) {
    throw ProcessExit(exitCode, immediate: true);
  };
```

### After

```dart
  _exitFunction = exitFunction ??
      (int exitCode) {
        throw ProcessExit(exitCode, immediate: true);
      };
```

### Before

```dart
        final Uri entryUri = fs.path.toUri(projectRootPath != null
          ? fs.path.relative(pathToReload, from: projectRootPath)
          : pathToReload,
        );
```

### After

```dart
        final Uri entryUri = fs.path.toUri(
          projectRootPath != null ? fs.path.relative(pathToReload, from: projectRootPath) : pathToReload,
        );
```

/cc @munificent @Hixie

**Comment by blasten** [comment]
Oh yeah, those are great examples. I wish the tool had more options to tweak the format.  Do we know if `dartfmt` is still in development? – It seems the last commit was a few months ago.

**Comment by a14n** [comment]
@tvolkert formatting is a matter of taste.

I don't like neither of the 2 alternatives of the first code snippet. If I had to manually format the code I'd end up with:
```dart
final Iterable<File> searchFiles =
  <Directory>[
    fs.directory(fs.path.join(Cache.flutterRoot, 'packages')),
    fs.directory(fs.path.join(Cache.flutterRoot, 'examples')),
  ]
  .expand((Directory directory) => directory.listSync(recursive: true))
  .whereType<File>()
  .where((File file) => file.path.endsWith('.dart') || file.path.endsWith('pubspec.yaml'));
```
The second snippet looks better to me after dartfmt.
The current version of the third example is not compliant with the Flutter Style Guide: [If you have a newline after some opening punctuation, match it on the closing punctuation](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#if-you-have-a-newline-after-some-opening-punctuation-match-it-on-the-closing-punctuation).

**Comment by tvolkert** [comment]
Yeah, with the first snippet, I'd probably refactor it to be two statements rather than one long one.

**Comment by Hixie** [comment]
see also https://github.com/flutter/flutter/pull/30138

**Comment by blasten** [comment]
Thanks @hixie for the context. The [readme](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it) is clear that by design, `dartfrm` won't help to achieve this level of customization.  

I had a conversation with @munificent who mentioned that changing the format isn't an option for now  given the existing formatted files in Google3. I'm closing this for now. Thanks everyone!

**Comment by zanderso** [comment]
I'd like to add a perspective that seems to be missing from this discussion. There are two goals to using an auto-formatter:
- Make the code base as a whole more readable by using a consistent style.
- Free code reviewers from being style-rules-lawyers.

With any auto-formatter, even if dartfmt implemented every feature we ask for, we will always be able to find individual examples that sacrifice readability for consistency. The acceptance criteria for an auto-formatter should therefore be "can I live with it in exchange for the benefits", not "are there examples that hurt readability".

**Comment by Hixie** [comment]
Not necessarily. That's true of a canonicalizer like dartfmt, but some formatters allow user formatting to go through unmodified and only change things for which the rules are hard and fast.

Also, even `dartfmt` doesn't free code reviewers from being style-rules-lawyers, there's plenty of style rules it doesn't do anything about (e.g. naming rules).

**Pull request closed without merging**
