### PR TITLE
Revert "Write FLUTTER_BUILD_MODE when using a local engine"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#51687

Reverting for analyzer failures:
```
Analyzing 3 directories...                                      
  error • Missing type arguments for calling generic function type 'PostExpectation<T> Function<T>(T)' • packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart:463:7 • implicit_dynamic_invoke
  error • The getter 'engineOutPath' isn't defined for the type 'MockArtifacts' • packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart:463:26 • undefined_getter
  error • Missing type arguments for calling generic function type 'PostExpectation<T> Function<T>(T)' • packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart:488:7 • implicit_dynamic_invoke
  error • The getter 'engineOutPath' isn't defined for the type 'MockArtifacts' • packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart:488:26 • undefined_getter
4 issues found. (ran in 327.3s)
```

### CODE REVIEW

**Comment by dnfield** [comment]
Weird - how did it pass presubmits?  LGTM

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Landing on red to un-red the tree.

**Review by cbracken — APPROVED** [review]
Thanks!

**Pull request merged**
