### PR TITLE
Reland "Fix Slider semantics node size"

### LINKED ISSUE #114225: `Slider` and `RangeSlider` thumb accessibility issues
### Description
#### 1. The entire `Slider` is focused instead of just the thumb. 

The focus window should only follow the thumb while keeping the ability to tap anywhere on the slider to change value.
(this especially becomes problematic with `RangeSlider`)

| Flutter | Android |
| --------------- | --------------- |
| <img src="https://user-images.githubusercontent.com/48603081/198578617-56b85c4d-4f43-4eed-9c80-0d9b8f7ccbd5.jpg" /> | <img src="https://user-images.githubusercontent.com/48603081/198578513-f64acb71-8c5b-482a-a866-857d68d81084.jpg" /> |




#### 2. `RangeSider` focus window is divided in half despite range thumb locations instead of just the range thumbs.

1. Focus window takes half the size regardless of the thumb location
2. If both range thumbs are located on one side of the slider, the focus window is still shown on the otherwise side, in an empty slider area.
3. Focus windows should be on the range thumbs





| Flutter | Android |
| --------------- | --------------- |
| <img src="https://user-images.githubusercontent.com/48603081/198580896-39585afc-d587-4488-8549-b250d3266522.jpg" /> | <img src="https://user-images.githubusercontent.com/48603081/198580902-fa0442c7-8b00-495e-b4d5-35c1679b6948.jpg" /> |
| <img src="https://user-images.githubusercontent.com/48603081/198580960-c67da866-3fef-42a2-9263-8bb9149d70a2.jpg" /> | <img src="https://user-images.githubusercontent.com/48603081/198580968-b4f1dc50-4a43-44e5-b0a7-55322d81a34e.jpg" /> |

### PR DESCRIPTION
**Pull request by TahaTesser**
reland https://github.com/flutter/flutter/pull/115285
fixes https://github.com/flutter/flutter/issues/114225

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by Piinks — APPROVED** [review]
Approving for additional testing (the bot requires approval first) so we can revisit what was failing for customers originally. Don't merge. 😉

**Comment by pdblasi-google** [comment]
@TahaTesser

Starting to look into this, but the google tests results got stale. Could you rebase? Alternatively, do you mind if I work off of your fork while investigating this?

**Comment by TahaTesser** [comment]
> @TahaTesser
> 
> Starting to look into this, but the google tests results got stale. Could you rebase? Alternatively, do you mind if I work off of your fork while investigating this?

Just rebased. Feel free to make any changes to the fork.

**Comment by pdblasi-google** [comment]
Thanks @TahaTesser, I'm looking forward to seeing the future work!

I wasn't able to get a consistent reproduction, but from what I _was_ able to find, it seemed like the semantics tree differed in such a way that testing tools based off of the semantics tree were unable to interact with the sliders in the way they expected.

My _theory_ was that the available actions (or maybe flags?) may have been in the wrong node compared to native which the previous semantics implementation managed to meet, but like I said, I never got a full reproduction working.

**Pull request closed without merging**
