### PR TITLE
Revert "[flutter_tools] move process manager into tool"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#75350

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by jonahwilliams** [comment]
Enough of the tests have passed that I'm confident in landing this revert only change, since it required no human interaction.

Landing on red to help g3 roll.

**Comment by christopherfujino** [comment]
@jonahwilliams do you anticipate re-landing this soon? asking for a friend who's wondering if they should rebase their PR past the revert.

**Comment by jonahwilliams** [comment]
Define _soon_ :) 

I plan on re-opening, but I'll need to run some global presubmits to make sure I don't miss failing tests.

**Comment by christopherfujino** [comment]
> Define _soon_ :)

¯\_(ツ)_/¯

I guess I'll procrastinate on rebasing until just before I land and see where we're at.

**Pull request merged**
