### PR TITLE
macos support for image_list

### PR DESCRIPTION
**Pull request by Abhishek01039**
part of https://github.com/flutter/flutter/issues/84306

### CODE REVIEW

**Comment by Abhishek01039** [comment]
Hello @Piinks 
can you please review this PR?
Thanks

**Comment by Piinks** [comment]
Hi @Abhishek01039 I do not know that I am the best reviewer for this PR, I recommend inquiring in the #hackers-ios channel for review. :) Thanks for the contribution!

**Comment by Hixie** [comment]
Would it make sense to have a test that verifies that we have the right files for each of the examples? In case we ever add another platform or another example or whatnot.

**Comment by jmagman** [comment]
> Hi @Abhishek01039 I do not know that I am the best reviewer for this PR, I recommend inquiring in the #hackers-ios channel for review. :) Thanks for the contribution!

@Piinks for future reference #hackers-desktop, this is adding support for macOS desktop, not iOS.  😄

**Comment by cbracken** [comment]
Apologies for the delay on this; I expect to have time to review this in the coming week. Thanks for your patience.

**Comment by Abhishek01039** [comment]
Sure, thank you @cbracken

**Review by cbracken — APPROVED** [review]
Apologies for the delay; this LGTM.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Pull request merged**
