### PR TITLE
Wait for Android plugin to load before configuring plugin dependency

### PR DESCRIPTION
**Pull request by blasten**
`implementation` is provided by the Android Gradle plugin. It cannot be called before the Android plugin has loaded, and registered an `implementation` callback. 

`afterEvaluate` ensures that `implementation` is only called after this plugin loaded.

### CODE REVIEW

**Review by xster — COMMENTED** [review]
LGTM. Can we add a test?

**Comment by blasten** [comment]
@xster test added

**Review by jonahwilliams — COMMENTED** [review]
This should not be running in the devicelab since it does not require dedicated hardware.

**Comment by blasten** [comment]
I discussed adding this to LUCI with @godofredoc. Currently, it's a manual process, and cannot be done in a single PR like this one.

This would have to be done after the holidays most likely.

**Comment by jonahwilliams** [comment]
I filled https://github.com/flutter/flutter/issues/70978 to track. Its not so urgent that we need to deal with it right now

**Comment by blasten** [comment]
Thanks @jonahwilliams ! I know @godofredoc is on top of improving this devX.

**Pull request merged**
