### PR TITLE
Revert "Add Crane test to the new Gallery app"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#62162

### CODE REVIEW

**Comment by jonahwilliams** [comment]
All of the new gallery tests are broken.

```
new_gallery_testkDgjua/gallery/test_driver/transitions_perf.dart
stdout:                [+9141 ms] /Users/flutter/.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/fade_scale_transition.dart:148:29: Error: 'decelerateEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
stdout:                [   +1 ms]   ).chain(CurveTween(curve: decelerateEasing));
stdout:                [        ]                             ^^^^^^^^^^^^^^^^
stdout:                [  +24 ms] /Users/flutter/.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:315:12: Error: 'decelerateEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
stdout:                [        ]     curve: decelerateEasing,
stdout:                [        ]            ^^^^^^^^^^^^^^^^
stdout:                [        ] /Users/flutter/.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:321:29: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
stdout:                [        ]   ).chain(CurveTween(curve: standardEasing));
stdout:                [        ]                             ^^^^^^^^^^^^^^
stdout:                [        ] /Users/flutter/.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:326:29: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
stdout:                [        ]   ).chain(CurveTween(curve: standardEasing));
stdout:                [        ]                             ^^^^^^^^^^^^^^
stdout:                [        ] /Users/flutter/.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:335:35: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
stdout:                [        ]         ).chain(CurveTween(curve: standardEasing));
stdout:                [        ]                                   ^^^^^^^^^^^^^^
stdout:                [        ] /Users/flutter/.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:355:35: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
stdout:                [        ]         ).chain(CurveTween(curve: standardEasing));
stdout:                [        ]                                   ^^^^^^^^^^^^^^
stdout:                [   +1 ms] /Users/flutter/.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:402:12: Error: 'accelerateEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
stdout:                [        ]     curve: accelerateEasing,
stdout:                [        ]            ^^^^^^^^^^^^^^^^
stdout:                [        ] /Users/flutter/.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:408:29: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
stdout:                [        ]   ).chain(CurveTween(curve: standardEasing));
stdout:                [        ]                             ^^^^^^^^^^^^^^
stdout:                [        ] /Users/flutter/.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:413:29: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
stdout:                [        ]   ).chain(CurveTween(curve: standardEasing));
stdout:                [        ]                             ^^^^^^^^^^^^^^
stdout:                [        ] /Users/flutter/.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:422:35: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
stdout:                [        ]         ).chain(CurveTween(curve: standardEasing));
stdout:                [        ]                                   ^^^^^^^^^^^^^^
stdout:                [        ] /Users/flutter/.pub-cache/hosted/pub.dartlang.org/animations-1.1.1/lib/src/shared_axis_transition.dart:445:35: Error: 'standardEasing' is imported from both 'package:flutter/src/material/curves.dart' and 'package:animations/src/utils/curves.dart'.
stdout:                [        ]         ).chain(CurveTween(curve: standardEasing));
```

**Comment by christopherfujino** [comment]
LGTM

**Comment by goderbauer** [comment]
/cc @liyuqian 

@jonahwilliams Please cc original author so they know their thing got reverted (or comment on the original PR).

**Comment by goderbauer** [comment]
The real cause for the breakage was/is probably: https://github.com/flutter/flutter/pull/62421

**Comment by goderbauer** [comment]
We'll have to publish a new version of the animations package with the work-around. I'll get on that.

**Comment by jonahwilliams** [comment]
My bad

**Pull request merged**
