### PR TITLE
[CP] Set plugin template min flutter sdk version to 1.20

### PR DESCRIPTION
**Pull request by cyanglaz**
## Description

1.20 cherry pick of https://github.com/flutter/flutter/pull/62605

## Related Issues

https://github.com/flutter/flutter/issues/60215

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by cyanglaz** [comment]
@pcsosinski Tests failed due to branch's sdk version less than 1.20.0.

**Comment by pcsosinski** [comment]
@christopherfujino to make sure we're doing the right thing here wrt versioning and the tests.

**Comment by tvolkert** [comment]
This will yield version solving issues for users on the beta channel before this release is published as `1.20.0`

**Comment by pcsosinski** [comment]
so do we need to release 1.20.0 and then a 1.20.1?

**Comment by pcsosinski** [comment]
what if we just make it > 1.19.1?

**Comment by tvolkert** [comment]
`>1.19.0` should work

**Comment by cyanglaz** [comment]
After offline discussion with @pcsosinski and @csells, we will close this PR. And after 1.20.0's release, we will introduce a hotfix with https://github.com/flutter/flutter/pull/62939

**Comment by pcsosinski** [comment]
stable has versioned to 1.20.0.

**Comment by cyanglaz** [comment]
closing in favor of https://github.com/flutter/flutter/pull/62939

**Pull request closed without merging**
