### PR TITLE
Lazily compute PointerEvent's transformed positions

### PR DESCRIPTION
**Pull request by dkwingsmt**
## Description

This PR refactors the pointer event classes so that if a pointer event is transformed, its `localPosition` and `localDelta` are computed only when first used, and other properties are deferred to the original event instead of stored in the object.

### Why?

The `local*` fields are used less often, but takes quite some computation due to the matrix multiplication. Events are dispatched to every object along the hit test result, and the `local*` fields are calculated unselectively, then discarded without being used most of the time.

Besides, the ~25 fields of `PointerEvent` are also assigned every time without any modification, which we can see some room of improvement.

### How much does it matter?

Currently Move events can be dispatched at a high frequency to all objects along the hit test result, which affects only when the screen is being touched. Hover events can also be dispatched frequently, but they are only dispatched to mouse-related objects, which is a small subset of the entire tree.

But this might change. PR https://github.com/flutter/flutter/pull/63834 proposes to dispatch hover events to all objects, so that they're treated like the other events. This will help fix a few issues as described in the PR, while tightening the performance restriction of event dispatching.

### How much does it improve, or worsen?

A new benchmark, `bench_mouse_region_mixed_grid_hover`, is proposed in https://github.com/flutter/flutter/pull/63808 to measure the performance of dispatching events to non-mouse widgets by making mouse hover over a number of heavily nesting `Container`s and `MouseRegions`. 

Following is the average result of 3 different cases:

- the current master;
- after applying "native hover";
- after applying "native hover" and "lazy local" (this PR)

| | drawFrameDuration | hitTestDuration |
|---|---|---|
| Current master | ~1650 | ~780 |
| Native hover | ~1679 | ~933 |
| Native hover + Lazy local | ~1655 | ~765 |

### Any API change?

Yes, in a minor way.

Currently, each pointer kind has up to 3 constructors (or factories):
- Unnamed constructor
- `.transformed`
- `.fromMouseEvent`

This PR changes the unnamed constructor so that they no longer accepts the following arguments: `localPosition`, `localDelta`, `original`, and `transform`. This is in order to ensure the relationship between the untransformed properties, transformed properties, and `transform`, is correct. To generate a transformed event (e.g. one with a specific `localPosition`), create an untransformed event then use `.transformed`.

```dart
// Currently allowed
PointerDownEvent(position: Offset(100, 100), localPosition(110, 120))

// After PR
PointerDownEvent(position: Offset(100, 100)).transformed(Matrix4.translationValue(10, 10))
```

Also, the transformed events are now of a series of private subclasses. For example, `PointerDownEvent.transformed` actually produces an instance of `_TransformedDownEvent`, which is a subclass of `PointerDownEvent`. This should not break anything unless some code is doing strict type equality check, which should be changed to `isA<T>()`.

```dart
// Before PR
expect(event.runtimeType, PointerDownEvent);

// After PR
expect(event, isA<PointerDownEvent>());
```

## Related Issues

- https://github.com/flutter/flutter/pull/63808, which benchmarks this issue
- https://github.com/flutter/flutter/pull/63834, whose performance issue this issue is trying to solve

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behavior with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
LGTM. It might be friendlier to remove the deprecated methods in a separate PR as a preliminary step.

**Comment by dkwingsmt** [comment]
This PR is ready, but I'll merge this PR right before https://github.com/flutter/flutter/pull/63834, since the latter is the only reason this PR is needed.

**Comment by Piinks** [comment]
Drive-by triage 👋  : It looks like this is causing some web tests to fail.

**Comment by dkwingsmt** [comment]
Update: This PR is blocked by https://github.com/dart-lang/sdk/issues/43528

**Pull request merged**
