### PR TITLE
Update references to Mozart types.

### PR DESCRIPTION
**Pull request by j9brown**
/cc @abarth

### CODE REVIEW

**Comment by abarth** [comment]
It's going to be easier to move these files purely into the Fuchsia world.  We'll probably need to unwrap the token so we can refer to it as an int.  I can take care of this part.

**Comment by j9brown** [comment]
Let's do that separately.  I'm not sure why you want to unwrap the token.  As soon as we have working "cookies" it will become an object handle instead of an int anyhow.

**Comment by abarth** [comment]
> Let's do that separately.

It's hard to do separately.  We need to remove all references to mojoms from standalone Flutter in order to get Flutter properly integrated into the Fuchsia build.

> I'm not sure why you want to unwrap the token.

I want to unwrap it so that we can carry it around in flutter.git without needing to import mojom.dart definitions in flutter.git.

> As soon as we have working "cookies" it will become an object handle instead of an int anyhow.

Object handles are just ints.

/cc @jamesr

**Comment by j9brown** [comment]
Alright, I'll let you take care of that part.

I still don't understand why you feel it's any more difficult to do as a follow on set of patches.  This change doesn't introduce any new dependencies.

**Comment by abarth** [comment]
> I still don't understand why you feel it's any more difficult to do as a follow on set of patches. This change doesn't introduce any new dependencies.

This change introduces dependencies on these modified mojoms.  The current state of mojoms in the standalone Flutter build is busted.  Rather than fix it, we're going to remove all the mojoms from the standalone Flutter build.  Once we do that, everything can smoothly move to the future.

**Comment by j9brown** [comment]
Ok, I'll take care of it then.

**Comment by j9brown** [comment]
Oh right, child_view.dart references a bunch of mozart stuff that can't really be unwrapped.  We should probably move this stuff into //apps/mozart/lib/flutter.  Let's talk tomorrow.

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/6194 is a frist step.

**Comment by abarth** [comment]
I've got it mostly done.  I'll just post a patch.

**Comment by abarth** [comment]
This became https://github.com/flutter/flutter/pull/6195

**Pull request closed without merging**
