### PR TITLE
Remove unnecessary argument names from typedefs

### PR DESCRIPTION
**Pull request by natebosch**
## Description

The function type syntax does not require argument names (contrasted
with the old typedef syntax which required them). Remove all argument
names that don't add new information in order to boost the signal
provided by the names that are meaningful.

- Remove argument names that repeat the type, or a portion of the type.
- Remove argument names that are noise words like "value".
- Refactor to function type syntax where the old typedef syntax was
  still used.

## Related Issues

Minor style cleanup. No related issues.

## Tests

No change in behavior or changed tests.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

Local failing test also fails on master.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

Local failing test also fails on master.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by HansMuller** [comment]
Flutter uses argument names in typedefs per the style guide: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#naming-rules-for-typedefs-and-function-variables

**Comment by natebosch** [comment]
> Flutter uses argument names in typedefs per the style guide:

That does not match my understanding of the linked section. I think the section also covers function literals. The idea of "ignore the arguments" is not sensible from the typedef side, only from the method definition side.

I think what it is discussing is:

instead of:

```dart
someMethod((_) {
  doStuff();
  return foo;
});
```

It should be:

```dart
someMethod((BuildContext context) {
  doStuff();
  return foo;
});
```

Even though `context` is unused, it's given a type and name in the function literal.

This example goes against general Dart style where the former is preferred, and should only be used in the flutter SDK.

**Review by jonahwilliams — COMMENTED** [review]
Tool changes LGTM.

**Comment by zanderso** [comment]
What is the status of this PR?

**Comment by natebosch** [comment]
> What is the status of this PR?

I had been waiting for a review, I'm not sure if I overlooked a step in the contribution guide that would have gotten this more attention. Let me know if there is anything I can do to help move it along.

**Comment by zanderso** [comment]
Ah ok, the next steps are probably to resolve the merge conflicts and ask @HansMuller if his concerns have been addressed.

**Comment by natebosch** [comment]
Merge conflicts resolved.

@HansMuller - do you agree with my interpretation of the style guide, or should we reach out for clarification?

**Comment by natebosch** [comment]
ping @HansMuller - how can we get unblocked?

**Comment by Piinks** [comment]
It looks like this branch is failing some checks due to a flake that has been resolved. Can you update your branch? The checks should pass then.

**Comment by HansMuller** [comment]
@natebosch, per https://github.com/flutter/flutter/pull/46107#issuecomment-562682438, you're right about the style guide. That said, I've occasionally found it useful to copy-paste typedefs for the same reason; not really sure why we need this cleanup.

**Comment by natebosch** [comment]
> I've occasionally found it useful to copy-paste typedefs for the same reason

How often do you copy-paste from a typedef into a named function? It would expect more often a typedef corresponds to a function expression which usually (outside the flutter SDK) should not get argument types.  https://dart.dev/guides/language/effective-dart/design#avoid-annotating-inferred-parameter-types-on-function-expressions 

> not really sure why we need this cleanup

It removes noise from the docs to let the signal stand out. This really only matters in the typedefs that show up in the docs, but I applied the change everywhere for consistency and so we have examples of good style throughout.

**Comment by Hixie** [comment]
I agree with Hans. Having the typedef guide you about what the parameters should be called is valuable guidance, it leads to more consistent code throughout, and helps with the readability.

Also, I agree that in some cases the parameter name isn't critical, but if we don't always give them, we end up in a situation where we have to have a judgement call for every parameter of every typedef and I don't think we'd all make the same calls, which would lead to more inconsistency.

**Comment by natebosch** [comment]
> helps with the readability

Repeating words doesn't make things more readable, it makes them longer.

> a situation where we have to have a judgement call for every parameter of every typedef

Names are things that we _want_ authors to be thinking about. The judgement call today is an implicit "Should I give this a useful name, or repeat the type". I was hoping to change that judgement call to an explicit "Should I give this a useful name or omit it", with the hope that reframing the question leads to the inclusion of more useful names.

**Comment by Hixie** [comment]
> Repeating words doesn't make things more readable, it makes them longer.

Longer and shorter aren't correlated to readability especially (except in the extremes). Consistency and predictability however is a big factor in readability. When you read a typedef you want to be thinking about what its semantics are, not about whether this is one where the names matter or don't matter and what it means that the author of the API decided that they did or did not matter, IMHO.

> Names are things that we want authors to be thinking about.

Agreed, but in this case it's not so much about what the names are (which the API designer still has to think about e.g. in their sample code if nothing else) so much as about whether the names are important or not.

> The judgement call today is an implicit "Should I give this a useful name, or repeat the type".

Interesting. I've never thought of it as "repeat the type". We should definitely always give parameters useful names. It's certainly the case that often the useful name is similar to the type, because the type itself is also usefully named, of course.

**Pull request closed without merging**
