### PR TITLE
Skip formatters if text has not changed

### LINKED ISSUE #12347: WhitelistingTextInputFormatter digitsOnly fail on backspace.
## Steps to Reproduce

Run the flutter_gallery example app. Navigate to the Text Form Field Demo. Begin typing a phone number, then press backspace. The phone validators trigger an infinite loop of trying to delete then replacing the last digit.

Removing either the WhitelistingTextInputFormatter.digitsOnly validator or the _phoneNumberFormatter validator causes the issue not to occur. I played around and it seems that even an empty second formatter triggers the issue. I was unable to debug on my own.

## Flutter Doctor

```
% flutter doctor

[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/frederickcook/flutter
    • Framework revision 89566feeed (2 days ago), 2017-09-29 17:56:25 -0700
    • Engine revision bdfedcc26f
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/frederickcook/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.0, Build version 9A235
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.5)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4155.35

[✓] Connected devices
    • iPhone 7 • 2AE532E3-5B4B-4D8D-8CFB-F54C3BF6F8EE • ios • iOS 11.0 (simulator)
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes #12347

See https://github.com/flutter/flutter/pull/24745#issuecomment-441880888 for more context

### CODE REVIEW

**Comment by xster** [comment]
Cool. Thanks for chasing this down! Please add a test.

**Comment by jonahwilliams** [comment]
Test case (finally) added!

**Comment by xster** [comment]
Cirrus didn't pass but otherwise LGTM. Thanks for fixing this!

**Comment by red42** [comment]
#12347 still happening as of 1.7.8+hotfix.3 , is there somewhere I can check which PRs made into a specific Flutter version?

**Pull request merged**
