### PR TITLE
Add test for Color.lerp to color_testing_demo

### PR DESCRIPTION
**Pull request by mattsarett**
#10655

### CODE REVIEW

**Comment by mattsarett** [comment]
@brianosman

**Comment by mattsarett** [comment]
@Hixie Is this ok to land while we iterate on the other one?  Just trying to clean up some of my issues.

**Comment by Hixie** [comment]
It depends on what we conclude with #3772. Currently, Color.lerp isn't attempting to do a linear lerp, so this would be wrong.

**Comment by Hixie** [comment]
Closing, see https://github.com/flutter/engine/pull/3772.

**Pull request closed without merging**
