### PR TITLE
Use already downloaded dart sdk for frontend_server.

### LINKED ISSUE #14700: flutter tool downloading Dart SDK twice
```
$ flutter precache
$ diff -rq bin/cache/artifacts/engine/<platform>/dart-sdk bin/cache/dart-sdk
```

After #14610, those two SDKs are identical, yet we're still making the user download them both.  That's ~116M of unnecessary download.

/cc @aam

### PR DESCRIPTION
**Pull request by aam**
This is follow-up to https://github.com/flutter/flutter/pull/14610

Fixes #14700

### CODE REVIEW

**Comment by aam** [comment]
cc @tvolkert

**Review by tvolkert — COMMENTED** [review]
Does `flutter precache -a` still download the SDK for all platforms?  We need that to be able to roll Flutter into Google.

**Comment by aam** [comment]
Thanks for the pointer, @tvolkert . It did, cleaned it up.
Note I change `flutter doctor -v` reporting so it reports single Dart version:
```
╰─➤  bin/flutter doctor -v   
...
• Dart version 2.0.0-edge.3c4dccbd46f152be9e1b6ca95c57357e8e48057c
```

**Comment by tvolkert** [comment]
We need to keep the platform-specific locations to support `flutter precache -a`, which downloads artifacts for all platforms (not just the current platform).  So I think we should probably go the other way - get rid of `bin/cache/dart-sdk` in favor of always using the platform-specific location.

**Comment by aam** [comment]
Got you, sorry I misunderstood what `flutter precache -a` does.
One issue with using `bin/cache/artifacts/engine/<linux-x64|darwin-x64|windows-x64>`, which is platform dependent is that `packages/flutter_tools/pubspec.yaml` points to dart sdk to override dependency on analyzer, front_end and kernel libraries https://github.com/flutter/flutter/blob/master/packages/flutter_tools/pubspec.yaml#L90.

**Comment by tvolkert** [comment]
Hmm.  symlinks come to mind, but Windows is tricky...

/cc @goderbauer

**Comment by aam** [comment]
symlinks on Windows seem to require admin elevated privileges, so that leaves copying as the only option.

**Comment by aam** [comment]
Another issue with running flutter from `bin/cache/artifacts/engine/` however is that artifacts-handling code expects to `own` that location, so when updating, for example, it deletes everything first(https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/cache.dart#L253), then downloads. That won't work(as Windows, for example, will tell you that directory is in use) when you have flutter running with dart from that artifacts/engine location.

**Comment by aam** [comment]
a894c9e makes flutter download dart sdk for the host into `bin/cache/dart-sdk`, while only `flutter precache -a` downloads all dart sdks into `bin/cache/artifacts/engine/<platform>/dart-sdk`.

**Review by tvolkert — APPROVED** [review]
LGTM

**Comment by aam** [comment]
This broke use of `--local-engine` with `--preview-dart-2` as frontend_server.dart.snapshot produced by local engine's dart sdk is not compatible with cached dart sdk `bin/cache/dart-sdk`.

cc @alexmarkov

**Pull request merged**
