### PR TITLE
Make parameter optional

### PR DESCRIPTION
**Pull request by dnfield**
/cc @Im-Kevin 

Changing the ctor signature broke some internal Flutter related infra in Google. This fixes that. Updates tests.

@renyou @mehmetf 

See #64308 and #65276

### CODE REVIEW

**Comment by Im-Kevin** [comment]
LGTM

**Comment by dnfield** [comment]
This may not be necessary - internal customer might be migrating to new parameter. @renyou to update.

**Comment by Im-Kevin** [comment]
What is the situation now

**Comment by dnfield** [comment]
This was resolved internally.  It might still be good to make this optional because most callers won't need it.

**Comment by Im-Kevin** [comment]
Yes, I agree very much and hope to merge as soon as possible

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
