### PR TITLE
Solve Chinese Pinyin Composing status problem when textfield has inpu…

### PR DESCRIPTION
**Pull request by Shadow-NewBee**
…tFormatters

## Description
Solve the problem when a textField sets inputFormatters such as FilteringTextInputFormatter.allow(RegExp('[a-zA-Z0-9]')), then user input word with Chinese Pinyin Keyboard, the composing letters will be formate.  The problem show in Rateted Issue, there is a gif.

## Related Issues
edit_textField

## Tests

I added the following tests:
## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ]I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [ ] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Shadow-NewBee** [comment]
@googlebot I fixed it.

**Comment by Shadow-NewBee** [comment]
@googlebot I fixed it.

**Comment by Shadow-NewBee** [comment]
@googlebot I fixed it.

**Comment by cocoaLaiSan** [comment]
@googlebot I fixed it.

**Comment by goderbauer** [comment]
@cocoaLaiSan You need to sign the CLA and provide the same email address you used for your commit (`git config user.email`).

Also, it looks like this change is causing some tests to fail. Can you take a look at those?

Last, but not least, this PR is missing some tests. Can you please add some to ensure that we don't break this again in the future? Thanks!

**Comment by Shadow-NewBee** [comment]
> @cocoaLaiSan You need to sign the CLA and provide the same email address you used for your commit (`git config user.email`).
> 
> Also, it looks like this change is causing some tests to fail. Can you take a look at those?
> 
> Last, but not least, this PR is missing some tests. Can you please add some to ensure that we don't break this again in the future? Thanks!

Thanks for reply. cocoaLaiSan is my another account which sign in google email. I do sure that I sign CLA but @googlebot tell me that I didn't. I confused about it. 

Xnip2020-10-22_10-09-48

Xnip2020-10-22_10-07-37

In adddtion, is there any guide for me that how to test code in my local?  When I clone flutter code to my mac and modify it, I don't know how to run it and test it.

Thanks!

**Comment by goderbauer** [comment]
@cocoaLaiSan The email address you used for your github commit is different than the two listed in your screenshot. You need to update the email address in your commit to one of the addresses you used to sign the CLA (see https://www.git-tower.com/learn/git/faq/change-author-name-email/ for example) or sign the CLA with the email address associated with your git commit. 

You can look at the existing tests here: https://github.com/flutter/flutter/blob/master/packages/flutter/test/widgets/editable_text_test.dart

You run them by executing `flutter test test/widgets/editable_text_test.dart` while inside the `packages/flutter` directory.

**Comment by Shadow-NewBee** [comment]
@googlebot I fixed it.

**Comment by Shadow-NewBee** [comment]
@googlebot I fixed it.

**Comment by Shadow-NewBee** [comment]
@googlebot I fixed it.

**Pull request closed without merging**
