### PR TITLE
Migrate iOS app deployment target from 8.0 to 9.0

### LINKED ISSUE #85173: Migrate existing apps with minimum supported iOS version from 8.0 to 9.0
Migrate existing apps with a minimum version of 8.0 to 9.0.

### PR DESCRIPTION
**Pull request by jmagman**
Migrate the existing app's Xcode project minimum iOS version from 8.0 to 9.0.  Don't change the version if it's anything other than 8.0.  
Compile App.framework for 9.0 (see https://github.com/flutter/flutter/pull/68729 for when I had to revert a previous version of this change since the Xcode projects weren't also being migrated at the same time).

Update `IPHONEOS_DEPLOYMENT_TARGET`, App.framework/Info.plist `MinimumOSVersion` value, `-miphoneos-version-min`, and `-miphonesimulator-version-min`.

Run `flutter build ios` on all the examples, integration tests, etc. to validate the versions were changed.  No longer see `The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99.` warnings everywhere.

Added a few tests to validate App.framework/Info.plist is embedded in the right place in the app.

Note: this does not migrate any plugin project minimum versions, other than the example app.

Template changed in https://github.com/flutter/flutter/pull/62902
See also https://github.com/flutter/flutter/pull/68729
Fixes https://github.com/flutter/flutter/issues/85173

### CODE REVIEW

**Comment by jmagman** [comment]
Hold off on reviewing please, I forgot about migrating the `AppFrameworkInfo.plist` `MinimumOSVersion` value.

**Comment by jmagman** [comment]
> Hold off on reviewing please, I forgot about migrating the `AppFrameworkInfo.plist` `MinimumOSVersion` value.

Updated, ready to review.

**Review by 3zrv — APPROVED** [review]

**Comment by stuartmorgan** [comment]
@0xf10yd Please read https://github.com/flutter/flutter/wiki/Tree-hygiene#getting-a-code-review

In particular:
> approvals in the GitHub UI should be reserved for those with contributor access

**Review by stuartmorgan-g — APPROVED** [review]
LGTM

**Pull request merged**
