### PR TITLE
Provide more const constructors for keys.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by yjbanov** [comment]
FYI, the Mac buildbot wasn't 100% happy with this change: https://uberchromegw.corp.google.com/i/client.flutter/builders/Mac/builds/2570/steps/test.sh/logs/stdio

**Comment by Hixie** [comment]
That was an unrelated breakage. @goderbauer had just turned on the tests on Mac, and they had previously been turned off for a reason. :-)

**Comment by yjbanov** [comment]
Rumor has it that Chrome buildbot now allows storing recipes in project repos. Perhaps we should look into that.

**Pull request merged**
