### PR TITLE
Deprecate 2018 text theme parameters

### LINKED ISSUE #98746: Deprecate Material 2 text style properties
Now that [Material 3 text styles](https://github.com/flutter/flutter/issues/89853) have been added to the `TextTheme`, we can deprecate the Material 2 styles (just like we did for Material 1).

## Proposal

- Deprecate (and eventually remove following the official deprecation policy) M2 text styles from `TextTheme`, for example `display1`, `bodyText2`, etc.

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/98746
Part of #91772

See more details at https://flutter.dev/go/texttheme-m3

M3 Spec at https://m3.material.io/styles/typography/tokens

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ x All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by TahaTesser** [comment]
`dev/integration_tests/flutter_gallery` needs updating

**Comment by Piinks** [comment]
It does indeed!

**Comment by Piinks** [comment]
`dart fix --apply` and done! 😜

**Comment by Piinks** [comment]
> `dart fix --apply` and done! 😜

* mostly. lol

**Pull request merged**
