### PR TITLE
Suggest that people move to "beta" when they upgrade on "stable"

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by timsneath** [comment]
This somehow feels a bit too strong -- do we really want to _encourage_ users to migrate from `stable` to `beta`?

**Review by timsneath — CHANGES_REQUESTED** [review]
I'd like to vet the language a little before we merge... I like the idea though. This somehow feels a bit too strong -- do we really want to _encourage_ users to migrate from `stable` to `beta`?

**Comment by Hixie** [comment]
I thought this text was relatively neutral (just informing them that it exists and that they might want to use it), but I don't feel strongly about exactly what we say. What did you have in mind?

**Comment by timsneath** [comment]
I can see this being _too_ successful and converting 80% of stable users to the beta channel, because it might be perceived as a recommendation. (Or, tongue in cheek: "_Real_ experienced developers use the beta channel"!)

I wonder about instead using a message on the `master`/`main` channel that says something like, "This channel is designed for those contributing code to the Flutter project. Alternatively, you may want to consider the `beta` channel, which is both regularly updated and sufficiently tested for production usage."?

**Comment by Hixie** [comment]
I mean, if it's "too successful" we can always just remove the message! Since we have no particular targets I'm not especially concerned.

In https://github.com/flutter/flutter/pull/126936 I'm adding channel descriptions for `flutter channel` which should push people away from `master`/`main`.

I'm not sure exactly when you're suggesting showing the message you suggest. Can you elaborate?

**Comment by timsneath** [comment]
I'm suggesting a commit very like the one that you're proposing here, but targeting `master` channel users when they run `flutter upgrade`, instead of `stable` users. 

Our recent data showed that `master` channel usage has grown from ~1% to ~4%, whereas `beta` channel usage has remained flat at ~1%. If half of those `master` channel users converted to `beta`, we'd already be in a better place.

**Comment by Hixie** [comment]
Seems reasonable, let me whip up a new PR.

**Comment by Hixie** [comment]
Submitted a version of this for upgrading on "master" as https://github.com/flutter/flutter/pull/127146

**Comment by timsneath** [comment]
I'd suggest we don't merge this one for now, and see how the other PR works out first. If we keep this, I'd probably simplify the text to something like, "For information on other Flutter release channels, visit foo.bar"

**Comment by Hixie** [comment]
Roger.

**Pull request closed without merging**
