### PR TITLE
Refactor l10n generator to handle multiple plurals/selects

### LINKED ISSUE #86906: Add support for multiple/nested plurals and selects in gen_l10n tool
## Use case
Hi!

Internationalization of Flutter apps is getting more and more convenient thanks to the enhancements implemented during the last months. More recently, #86167 allowed to use plural and select in the middle of a string which is super useful.

However while internationalizing this app on top of this recent change, I noted a few cases for which it didn't produce the expected result:

```json
"pluralThenString": "Indeed, {count, plural, =1 {she likes} other {they like}} {framework} a lot!",
"@pluralThenString": {
    "placeholders": {
        "count": {},
        "framework": {
            "type": "String"
        }
    }
},
"multiplePlurals": "There {count, plural, =1{is} other{are}} {count} world{count, plural, =1{} other{s}}.",
"@multiplePlurals": {
    "placeholders": {
        "count": {}
    }
},
"pluralInSelect": "I can see {fruit, select, apple{{count, plural, =0{no apple} =1{one apple} other{some apples}}} banana{{count, plural, =0{no banana} =1{one banana} other{{count} bananas}}}}.",
"@pluralInSelect": {
    "placeholders": {
        "count": {
            "type": "int"
        },
        "fruit": {}
    }
},
```
```dart
@override
String pluralThenString(int count, String framework) {
  final String pluralString = intl.Intl.pluralLogic(
    count,
    locale: localeName,
    one: 'she likes',
    other: 'they like',
  );

  return 'Indeed, $pluralString a lot!';
}

@override
String multiplePlurals(int count) {
  final String pluralString = intl.Intl.pluralLogic(
    count,
    locale: localeName,
    one: 'is',
    other: 'are',
  );

  return 'There ${pluralString}.';
}

@override
String pluralInSelect(int count, Object fruit) {
  final String pluralString = intl.Intl.pluralLogic(
    count,
    locale: localeName,
    zero: 'no apple',
    one: 'one apple',
    other: 'some apples',
  );

  return 'I can see ${pluralString}.';
}
```

## Proposal
I would like to keep developing the l10n support to make it more powerful and reduce the risk of misuse (I personally have been surprised by the first use case).

I understand that Flutter is not intended to implement the ICU format in its entirety. I think it could improve the user experience to support these use cases though. My only references are the following, where we see that multiple plurals are being used:
* [Formatting Messages - ICU Documentation](https://unicode-org.github.io/icu/userguide/format_parse/messages/)
* [The Missing Guide to the ICU Message Format](https://phrase.com/blog/posts/guide-to-the-icu-message-format/)
* [ICU message editor](https://devpal.co/icu-message-editor/)

I had started working on this improvement, but it requires some refactoring. I will open a PR so that it can be discussed.

### PR DESCRIPTION
**Pull request by Delgan**
This is a draft pull request to discuss changes intended to fix #86906.

Currently, the l10n generator is implemented using regexes which makes it hard to handle multiple plurals in the same string. The solution proposed is to use a parser to extract the `{}` components one by one. For simplicity, there are two passes on the string: the first one to extract the fields, the second one to format them in the message. Meanwhile, the variables used in the final string are generated according to the fields extracted by the first pass.

Main change is the following: instead of iterating through the placeholders and replacing their corresponding field in the string, we iterate through the fields and replace them according to the corresponding placeholder.

I understand that the modifications are significant and that one may be reluctant to consider such big refactoring.
I would argue it's really not that complicated once the logical switch is understood, but that's easy for me to say so...
I'm sorry I couldn't find an alternative solution to make this PR less painful to review.

Remains to be done:
* Add documentation
* Add more unit tests
* Add exception in case braces are unbalanced
* Add braces escaping
* Make code more idiomatic
* Respect style guide

Please, let me know: does it worth pursuing the efforts?

I opened this PR so we can possibly discuss the implementation and others implications.
I'm just hoping to improve a little more the Flutter internationalization. ;)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Delgan** [comment]
@googlebot I signed it!

**Comment by christopherfujino** [comment]
Per:

> This is a draft pull request to discuss changes intended to fix #86906.

I've marked this as a draft so that it does not show up in PR triage. Feel free to make this ready for review once it is (although I imagine the proposal at https://github.com/flutter/flutter/issues/86906 would need approval first)

**Comment by HansMuller** [comment]
@Delgan - are you still planning on finishing this PR?

**Comment by Delgan** [comment]
@HansMuller Are you OK with the overall changes of `_generateMethod()` produced by this RP?
Would you like it to be done differently?

If this looks acceptable to you, I can surely finish it this week-end.

**Comment by asashour** [comment]
@Delgan: I am not part of the team, and I have few comments (which you can discard 😉)

Having a PR for a long time not reviewed is not very encouraging for the submitter, but I guess the team is busy, or didn't notice this change.

- Shouldn't we handle escaping `{`, in other words, what happens when the text should include it, please look [here].(https://unicode-org.github.io/icu/userguide/format_parse/messages/#quotingescaping)
- For performance reasons, in `_parseMessage`, instead of adding the character to the string, e .g.  `literalText += char;`, we could just store the index, and then `substring` from the `start` to the `end` in one shot.
- You already have done a great job. In order to cover all cases, how about looking into other library tests cases, e.g. [ICU project](https://github.com/unicode-org/icu), and verify the new implementation against few complex ones?

**Comment by HansMuller** [comment]
@Delgan - I apologize for taking so long in responding to https://github.com/flutter/flutter/pull/86909#issuecomment-920625486

This looks like a nice improvement gen_l10n's features and implementation. If you're willing to tackle all of the things you outlined in the PR's description, I will try and provide a prompt review.  Sorry again for letting this sit for so long.

**Comment by HansMuller** [comment]
@Delgan - I'm going to close this for now. It looks like a good start. If you decide to continue working on it, please reopen the PR and I promise that we'll respond promptly.

**Comment by lslv1243** [comment]
@Delgan just hit the limitation in the current `gen-l10n` implementation and your PR solves it. I hope you get the energy and time to finish it. I will be using your implementation in the meantime. Thanks for contributing!

**Comment by Delgan** [comment]
Hi all!

I was not able to re-open this precise PR, so I created a new one here: https://github.com/flutter/flutter/pull/100427

**Comment by lslv1243** [comment]
Hey, @Delgan. I had hit the limitation and used your PR for a while. But then I hit another limitation, generating code for non Flutter projects. So I ended up making another solution from scratch. It is almost compatible with the current gen-l10n solution. In case you wanna give it a try: https://github.com/lslv1243/land.

**Comment by asashour** [comment]
@lslv1243 I would suggest evaluating #100427 and providing missing functionality there, or you can also raise a PR to benefit everyone.

This PR is closed, thanks.

**Pull request closed without merging**
