### PR TITLE
[platform_view]run platform view ui test to physical device

### PR DESCRIPTION
**Pull request by hellohuanlin**
The failure is because `await devices.workingDevice` requires a physical device, and we were running it using `Mac` name under `.ci.yaml`. 

There are 3 possible fixes: 
1. running on simulator. Use `testWithNewIOSSimulator` to get the device ID, and run the simulator. In this case we don't have to set `deviceOperatingSystem` because it's only for physical device. 
2. actually running it on physical device (This PR)
3. change this test to `flutter_drone` test which runs on simulator too, but it is a lot more involved (moving the test from `devicelab` to `flutter_drone`). 

We pick option 2 because it's relatively easier, and we may actually want to test platform views on device (e.g. measure performance, etc).

*List which issues are fixed by this PR. You must list at least one issue.*

https://github.com/flutter/flutter/issues/106745#issuecomment-1199808744

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by keyonghan — COMMENTED** [review]
https://cs.opensource.google/flutter/flutter/+/master:TESTOWNERS;l=201 should be moved under section: `## Mac iOS DeviceLab tests`

**Comment by keyonghan** [comment]
> https://cs.opensource.google/flutter/flutter/+/master:TESTOWNERS;l=201 should be moved under section: `## Mac iOS DeviceLab tests`

This change request is for TESTOWNERS file.
Though the builder `Linux test_ownership` succeeds here, I am afraid it will fail in other PRs when this lands. This is due to https://github.com/flutter/flutter/issues/108645.

**Comment by hellohuanlin** [comment]
> > https://cs.opensource.google/flutter/flutter/+/master:TESTOWNERS;l=201 should be moved under section: `## Mac iOS DeviceLab tests`
> 
> This change request is for TESTOWNERS file. Though the builder `Linux test_ownership` succeeds here, I am afraid it will fail in other PRs when this lands. This is due to #108645.

Oh sorry i misunderstood. Updated both to be consistent.

**Review by keyonghan — APPROVED** [review]
LGTM

**Review by jmagman — APPROVED** [review]
LGTM

**Pull request merged**
