### PR TITLE
Remove legacy restart support

### PR DESCRIPTION
**Pull request by johnmccutchan**
- [x] Remove restartApp and runFromFile from Device.
- [x] Do not support restarting in the non-hot runner.
- [x] Kill dead code.
- [x] Fix help text for debugDumpRenderTree

### CODE REVIEW

**Comment by johnmccutchan** [comment]
@devoncarew @Hixie

**Comment by Hixie** [comment]
cc @jason-simmons who may have an opinion on this; I believe he uses this codepath daily.

**Comment by devoncarew** [comment]
Can you include the help output for `flutter run --no-hot`? I want to make sure that the text printed after an app starts up doesn't mention 'r to restart'.

lgtm for the code changes

**Comment by jason-simmons** [comment]
fwiw, I find --no-hot helpful during engine development but I generally restart the entire application process on each rebuild versus using non-hot reload of Dart code.

**Comment by johnmccutchan** [comment]
@jason-simmons --no-hot isn't going away just application restart

**Comment by johnmccutchan** [comment]
@devoncarew The removal of the 'restart' help message can be seen here https://github.com/flutter/flutter/pull/6801/files#diff-7926ab5975b7b1656a34c7cd90f4ac7fL248

but just for sanity checking:

```
$ flutter run --no-hot
Running 'flutter packages get' in hello_world...    524ms
Building APK in debug mode (android-arm)...         5265ms
Installing build/app.apk...                         7610ms
Running lib/main.dart on Nexus 7...

The Observatory debugger and profiler is available at: http://127.0.0.1:45528/
For a more detailed help message, press "h" or F1. To quit, press "q", F10, or Ctrl-C.
h
The Observatory debugger and profiler is available at: http://127.0.0.1:45528/
To dump the widget hierarchy of the app (debugDumpApp), press "w".
To dump the rendering tree of the app (debugDumpRenderTree), press "r".
To repeat this help message, press "h" or F1. To quit, press "q", F10, or Ctrl-C.
```

which actually prints out bad help text. dumping the render tree is not "r" but "t".

**Comment by johnmccutchan** [comment]
help text fixed.

**Pull request merged**
