### PR TITLE
[iOS] Copy Flutter.framework.dSYM into app archive

### LINKED ISSUE #116493: Flutter application missing framework dSYMs, validation error "The archive did not include a dSYM for the Flutter.framework with the UUIDs"
I've had a production crash reported by Crashlytics but it's not able to show me any details as there's a required dSYM missing with UUID `1F29F0F6-7F1B-3049-A2C2-B0101BD2AB95`

Checking all the dSYMs in the build output folder does not show any dSYMs with that UUID. Doing a quick google of the UUID shows a couple of posts https://community.flutterflow.io/c/discuss-and-get-help/unable-to-deploy-to-app-store and https://community.flutterflow.io/c/discuss-and-get-help/failed-logs-can-someone-help that have the same UUID - so I'm guessing this dSYM is a framework or other library dSYM and not something specific to my code.

I noticed there's another 5 missing dSYMs in the Crashlytics dSYMs page as well, but those are showing as optional so I'm not sure how important those ones are. For completeness though they are as follows:

* 7626834B-C95E-307C-B8F1-04EB0824D2FE
* 0C071349-588B-309E-924B-6AF69FA560D7
* 71D7C146-9E6E-33A6-BB0D-3CF4763607F3
* 4106CC2E-94B4-3219-8B86-8FEA05CABB7D
* 45A0FAD5-4B81-32BF-A24E-76708AA387DF

I've had a number of crashes in the past (even on that same build) that haven't reported issues with missing dSYMs so I'm guessing most of the dSYMs are getting included in the build output fine without issues.

<details>
flutter doctor -v (version used to build production release that experienced crash)
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.3.1 21E258 darwin-arm, locale en-AU)
    • Flutter version 3.3.1 on channel stable at /Users/nvx/flutter-331/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (3 months ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[!] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[!] Connected device
    ! No devices available

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
</details>

### PR DESCRIPTION
**Pull request by cbracken**
As of Xcode 16, App Store validation now requires that apps uploaded to the App store bundle dSYM debug information bundles for each Framework they embed.

dSYM bundles are packaged in the Flutter.xcframework shipped in the `ios-release` tools archive as of engine patches:
* https://github.com/flutter/engine/pull/54414
* https://github.com/flutter/engine/pull/54458

This copies the Flutter.framework.dSYM bundle from the tools cache to the app archive produced by `flutter build ipa`.

Issue: https://github.com/flutter/flutter/issues/116493

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by cbracken** [comment]
I have an alternate version of this patch that unifies the `App.framework.dSYM` and `Flutter.framework.dSYM` copying code, but took this route, which does an `rsync` copy like we do with `Flutter.framework` because `App.framework`/`App.framework.dSYM` are build products that get bundled, whereas `Flutter.framework`/`Flutter.framework.dSYM` are not build products, but rather pre-builts that get copied over.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by lanistor** [comment]
Does Flutter 3.22 merged this commit?

**Comment by cbracken** [comment]
> Does Flutter 3.22 merged this commit? I still got this problem.

This fix is in Flutter 3.24 (the current `stable` branch). You can pick it up via `flutter upgrade`. There is no plan to back port to older Flutter releases.

**Comment by jmagman** [comment]
https://github.com/flutter/engine/pull/54414#issuecomment-2389372698

There may be a way to do this manually by copying the Flutter dSYMs into your project: https://stackoverflow.com/a/52417617/431116
You can find the dSYMs at <flutter-sdk>/bin/cache/artifacts/engine/ios-release/Flutter.xcframework/ios-arm64/dSYMs/Flutter.framework.dSYM/
Alternatively, it may work if you downgrade to Xcode 15.

**Comment by lanistor** [comment]
> > Does Flutter 3.22 merged this commit? I still got this problem.
> 
> This fix is in Flutter 3.24 (the current `stable` branch). You can pick it up via `flutter upgrade`. There is no plan to back port to older Flutter releases.

Thanks a lot, But Flutter `3.24` has a big problem, it force need all dependencies update android compileSdkVersion to 34, This is unattainable for us, so we have to downgrade to `3.22`.

So will you merge this bugfix to Flutter `3.22`?

**Comment by jmagman** [comment]
> So will you merge this bugfix to Flutter `3.22`?

No, we will not be bug fixing to any previously releases.  However, you should have a relatively easy workaround:


> There may be a way to do this manually by copying the Flutter dSYMs into your project: https://stackoverflow.com/a/52417617/431116
> You can find the dSYMs at /bin/cache/artifacts/engine/ios-release/Flutter.xcframework/ios-arm64/dSYMs/Flutter.framework.dSYM/
> Alternatively, it may work if you downgrade to Xcode 15.

**Comment by lanistor** [comment]
> @cbracken Thanks a lot, But Flutter `3.24` has a big problem: it force need all dependencies update android compileSdkVersion to `34`, this is unattainable for us, so we have to downgrade to `3.22`.

Thanks, but i cannot find `Realm.framework.dSYM`, where to located it?

**Comment by jmagman** [comment]
That StackOverflow link is showing how to embed a random dSYM in your Xcode project, their example is Realm.  Instead of their example, use the Flutter.dSYM (which is what this issue was tracking).  It's located in your Flutter SDK directory at `<flutter-sdk>/bin/cache/artifacts/engine/ios-release` (sorry, my pasting from https://github.com/flutter/engine/pull/54414#issuecomment-2389372698 was bad).

**Comment by lanistor** [comment]
> dSYMs

Thanks, but i cannot find a `dSYMs` folder in `ios-release/Flutter.xcframework/ios-arm64` of flutter folder.

截屏2024-10-03 11 29 04

**Comment by jmagman** [comment]
> > That StackOverflow link is showing how to embed a random dSYM in your Xcode project, their example is Realm. Instead of their example, use the Flutter.dSYM (which is what this issue was tracking). It's located in your Flutter SDK directory at `<flutter-sdk>/bin/cache/artifacts/engine/ios-release` (sorry, my pasting from [flutter/engine#54414 (comment)](https://github.com/flutter/engine/pull/54414#issuecomment-2389372698) was bad).
> 
> Thanks, but i cannot find a `dSYMs` folder in `ios-release/Flutter.xcframework/ios-arm64` of flutter folder.

Okay this is a good point, it doesn't exist on Flutter 3.22, it's only in 3.24 or later, which is the problem!
Follow the instructions at https://github.com/flutter/engine/blob/main/docs/Crashes.md#ios for "For versions prior to Flutter 3.24" and download it directly from Google Cloud Storage.

**Comment by lanistor** [comment]
> > > That StackOverflow link is showing how to embed a random dSYM in your Xcode project, their example is Realm. Instead of their example, use the Flutter.dSYM (which is what this issue was tracking). It's located in your Flutter SDK directory at `<flutter-sdk>/bin/cache/artifacts/engine/ios-release` (sorry, my pasting from [flutter/engine#54414 (comment)](https://github.com/flutter/engine/pull/54414#issuecomment-2389372698) was bad).
> > 
> > 
> > Thanks, but i cannot find a `dSYMs` folder in `ios-release/Flutter.xcframework/ios-arm64` of flutter folder.
> 
> Okay this is a good point, it doesn't exist on Flutter 3.22, it's only in 3.24 or later, which is the problem! Follow the instructions at https://github.com/flutter/engine/blob/main/docs/Crashes.md#ios for "For versions prior to Flutter 3.24" and download it directly from Google Cloud Storage.

I did as your guide, but i still got this problem, it seems that the UUID doesn't match.

截屏2024-10-03 13 39 41
截屏2024-10-03 13 40 54
截屏2024-10-03 13 41 01
截屏2024-10-03 13 43 25

**Comment by jmagman** [comment]
@lanistor can you file a new issue? We would use it as a request to make https://github.com/flutter/engine/blob/main/docs/Crashes.md#ios better.

**Comment by GhassanAlKaraan** [comment]
Having the same issue here. I can't upgrade the flutter version because this is gonna break my project. But willing to refactor later in time. I'm confused by which fix to apply. Should I downgrade my xcode?

Also can I just ignore the warning for now or it will not let me push the build for distribution?

**Comment by jmagman** [comment]
@GhassanAlKaraan I'm not sure why a combo of the instructions at https://github.com/flutter/engine/blob/main/docs/Crashes.md#ios and https://stackoverflow.com/questions/50947279/how-to-include-dsym-file-of-an-embedded-framework-to-an-app-archive/52417617#52417617 aren't working.

> can you file a new issue? We would use it as a request to make https://github.com/flutter/engine/blob/main/docs/Crashes.md#ios better.

**Comment by lanistor** [comment]
> Having the same issue here. I can't upgrade the flutter version because this is gonna break my project. But willing to refactor later in time. I'm confused by which fix to apply. Should I downgrade my xcode?
> 
> Also can I just ignore the warning for now or it will not let me push the build for distribution?

Ignore the warning works fine for our APP, it can publish normally.

**Comment by lanistor** [comment]
> @lanistor can you file a new issue? We would use it as a request to make https://github.com/flutter/engine/blob/main/docs/Crashes.md#ios better.

Well, it seems that just ignoring this issue won't have any impact.

**Comment by dawid-niedzwiecki** [comment]
I encountered an issue while using the add-to-app method. The iOS app doesn't compile due to "Multiple commands produce `MYAPP/DerivedData/app/Build/Products/Debug-iphoneos/Flutter.framework.dSYM`"

**Comment by jmagman** [comment]
@dawid-niedzwiecki Can you file a new issue that describes what you are seeing and how to reproduce it?  Thank you!

**Comment by renefloor** [comment]
@dawid-niedzwiecki and @jmagman We have the same issue. I could reproduce it by taking the multiple-flutters example and changed it from the `cocoapods` setup to the `frameworks` setup following this guide: https://docs.flutter.dev/add-to-app/ios/project-setup#embed-a-flutter-module-in-your-ios-app

I created an issue with more detailed reproduction steps: https://github.com/flutter/flutter/issues/158005

**Comment by jogboms** [comment]
@dawid-niedzwiecki see https://github.com/flutter/flutter/issues/157359

**Pull request merged**
