### PR TITLE
Assert that det != 0 when inverting matrices

### PR DESCRIPTION
**Pull request by Hixie**
Fixes two TODOs that keep bugging me. Hopefully that's what @abarth
meant by them.

### CODE REVIEW

**Comment by abarth** [comment]
Sure.  Can we actually handle exceptions at these points?  If so, LGTM.

**Comment by Hixie** [comment]
Define "handle exceptions".

I mean, it's not going to be good for the user. But usually calls to these functions are called from code in a high-level try/catch (e.g. the pointer router one) which will report it to the console. In practice in release mode this is going to do crazy things (looks like Matrix4 returns the input matrix without inverting it in these cases) and in checked mode it'll get a dart crash.

It wasn't clear to me if the comment was meant to imply that the transforms should never be degenerate (which is what this patch assumes), or whether it was meant to imply that we should do something useful when they occur (e.g. assume that the hit test didn't hit, return 0,0 as the point, or whatever).

Happy to switch it from asserts to the alternative approach if you prefer that.

**Comment by abarth** [comment]
Usually the right behavior is to act as if it isn't hit.  For example, consider a transform with the zero matrix.  There's no way to hit the thing inside the transform.

**Comment by Hixie** [comment]
Ok, that's easy to do for the hit test case.

What should localToGlobal / globalToLocal do?

**Comment by abarth** [comment]
> What should localToGlobal / globalToLocal do?

Probably either return null or throw an exception...

It probably should be legal to have degenerate transforms in the tree.  For example, if you want to animate a scale to zero, on the last frame of the animation, you'll have a degenerate subtree.  That implies that it's not an error to have an non-invertable transform, which makes me think that localToGlobal / globalToLocal should return null and callers will need to handle that case.

**Comment by Hixie** [comment]
Seems reasonable.

**Comment by Hixie** [comment]
I'm going to close this pull request since this approach isn't the one we want to do.

Filed https://github.com/flutter/flutter/issues/1161 to trace further work on this.

**Pull request closed without merging**
