### PR TITLE
Made the logo more sexier

### PR DESCRIPTION
**Pull request by cannibal-kush**
The flutter logo was markably unsexy. This commit makes it cooler, sexier and also more fluttery. Pls accept.

### CODE REVIEW

**Comment by drsatan1** [comment]
I signed it!

**Comment by drsatan1** [comment]
I signed it!

**Comment by MaskyS** [comment]
@drsatan1, not thicc enough :(

**Comment by goderbauer** [comment]
I actually find that pretty hard to read.

**Comment by NathanaelA** [comment]
Agreed (on hard to read), I think if this was accepted the bottom underline needs to be removed so the letters don't flow into each other...

**Comment by drsatan1** [comment]
Guys I can't figure out the CLA. Oh well, take this as my consent to just do the same thing in a different PR and take credit for it without attribution.

**Comment by Hixie** [comment]
@drsatan1 Thanks. I will close this PR for now and we'll consider what to do with the batch file header.

**Pull request closed without merging**
