### PR TITLE
Enable unreachable_from_main lint - it is stable now!!1

### PR DESCRIPTION
**Pull request by goderbauer**
PLUS: clean-up of all the unreachable stuff.

### CODE REVIEW

**Comment by christopherfujino** [comment]
can you link some more references to this black magic? how does it know which `main()` to start from? or does it just evaluate every function named `main()` in a library in the package?

**Comment by goderbauer** [comment]
It only considers files that have a `main` function. And for those files its checks if everything in that file is reachable from that main. Its mostly targeted towards tests, which always have a main function and where people often declare everything as public. Then, when they refactor the test and no longer need the public thing, they forget to delete it.

**Comment by christopherfujino** [comment]
> It only considers files that have a `main` function. And for those files its checks if everything in that file is reachable from that main. Its mostly targeted towards tests, which always have a main function and where people often declare everything as public. Then, when they refactor the test and no longer need the public thing, they forget to delete it.

Ahh, ok, that's much less magical than I thought. Nice cleanup.

**Review by christopherfujino — APPROVED** [review]
Tools LGTM

**Review by srawlins — APPROVED** [review]
Wow, if I'm reading this right, no `ignore`s were required except in samples, that's great news!

**Review by chunhtai — APPROVED** [review]
LGTM

**Pull request merged**
