### PR TITLE
[Improvement] Add prefix `Alignment.` for toString of Alignment

### PR DESCRIPTION
**Pull request by HeavenOSK**
## Description
Added prefix `Alignment.` for toString of `Alignment`.
 
[Alignment#toString](https://github.com/flutter/flutter/blob/eefcff900c3cdf4aff43751c1b32a3aa65c91a4d/packages/flutter/lib/src/painting/alignment.dart#L349) didn't output own class name .

## Related Issues.
[Improvement] Alignment#toString should have prefix `Alignment.` #67859

## Tests
I updated the following tests:
 
-   [AlignmentGeometry toString](https://github.com/flutter/flutter/blob/eefcff900c3cdf4aff43751c1b32a3aa65c91a4d/packages/flutter/test/painting/alignment_test.dart#L213)

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by PixelToast** [comment]
Some more tests are failing:
<details>
  <summary>Click to expand</summary>

```
02:29 +1470 ~2 -2: /tmp/flutter sdk/packages/flutter/test/widgets/overflow_box_test.dart: OverflowBox implements debugFillProperties                                                                   
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: [
            'alignment: center',
            'minWidth: 1.0',
            'maxWidth: 2.0',
            'minHeight: 3.0',
            'maxHeight: 4.0'
          ]
  Actual: [
            'alignment: Alignment.center',
            'minWidth: 1.0',
            'maxWidth: 2.0',
            'minHeight: 3.0',
            'maxHeight: 4.0'
          ]
   Which: at location [0] is 'alignment: Alignment.center' instead of 'alignment: center'
When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///tmp/flutter%20sdk/packages/flutter/test/widgets/overflow_box_test.dart:46:5)
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:794:19)
<asynchronous suspension>
#10     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:774:14)
#11     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1191:24)
#12     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:178:54)
#17     withClock (package:clock/src/default.dart:48:10)
#18     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:178:22)
#23     FakeAsync.run (package:fake_async/fake_async.dart:178:7)
#24     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1188:15)
#25     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:136:24)
#26     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
<asynchronous suspension>
#27     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#32     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
#33     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
#38     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
#39     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
<asynchronous suspension>
#40     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#45     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
#46     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
#47     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
#54     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
#55     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#56     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:256:16)
#61     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:255:5)
#62     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:208:7)
#80     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#81     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#85     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#119    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#127    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#128    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#138    _Socket._onData (dart:io-patch/socket_patch.dart:1969:41)
#147    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1505:33)
#148    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1017:14)
```

</details>

**Review by shihaohong — DISMISSED** [review]
LGTM

**Comment by shihaohong** [comment]
Sorry, I failed to notice that some of the framework tests are failing. Could you make sure that the other tests that use `Alignment.toString` are fixed as well?

**Comment by HeavenOSK** [comment]
Thank you for checking. 
 
> Could you make sure that the other tests that use Alignment.toString are fixed as well?
 
Sure. I'll fix them.

**Comment by shihaohong** [comment]
There's still failing checks. This is the one I could spot on a brief look, but there could be more: 

01:02 +576 ~2: /tmp/flutter sdk/packages/flutter/test/widgets/container_test.dart: Container control test.

**Comment by HeavenOSK** [comment]
@shihaohong 
Thank you for investigating it.

> 01:02 +576 ~2: /tmp/flutter sdk/packages/flutter/test/widgets/container_test.dart: Container control test.
 
According to your comment, I've fixed the test case for `container_test` on https://github.com/flutter/flutter/pull/67860/commits/50c03b1c2bd7e6f759749fee015890cf9ec5c0f0 .
  
Please review when you have time.

**Review by shihaohong — APPROVED** [review]
LGTM

**Comment by shihaohong** [comment]
This change ends up failing some internal Google tests that I have fixes for. I'll merge this PR and fix the internal tests once this change makes it in.

**Pull request merged**
