### PR TITLE
Reland composite physical layers for all platforms

### PR DESCRIPTION
**Pull request by dnfield**
Issue: #27891 

Relands the revert of #29532 

We've gotten sign off from the Fuchsia team to not special case elevation == 0.  With this reland, we will now properly clip in a RenderFlex even if a material widget with elevation 0 overflows it.  This also contains a test to make sure we don't regress that.

/cc @liyuqian @goderbauer @mklim

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
I believe this is the culprit for the flutter_gallery_io32__transition perf flakiness

**Comment by dnfield** [comment]
For the 90th percentile rasterizer benchmark?  Quite possibly - I rebaslined two others, may have to rebaseline that one too.

**Comment by liyuqian** [comment]
flutter_gallery_io32__transition doesn't seem to be so flaky to me. I see that there has been a regression starting from https://github.com/flutter/flutter/pull/29377 , which I think might be caused by https://github.com/flutter/engine/pull/8157

If @dnfield  can confirm that the regression is caused by https://github.com/flutter/engine/pull/8157, then we shall certainly just rebaseline the benchmark since the AA shapes are the correct behavior.

**Comment by dnfield** [comment]
I rebaselined the benchmark.  AA definitely caused some regressions.

**Pull request merged**
