### PR TITLE
remove non-nullability on Navigator methods

### LINKED ISSUE #65938: [NNBD] Conflicting generic type in Navigator's  push methods
In class `Navigator`, there is `Future<T> push<T>(Route<T> route)` and `static Future<T> push<T extends Object>(BuildContext context, Route<T> route)`. The latter restricts `T` to a subclass of `Object` which means that a `Route<void>` doesn't work here. I think, it should be possible to use such a route with both variants. The same if true for other variants of push or replace.

If there is a reason for not allowing `Route<void>` this should be documented, I think. Currently the documentation stats:

```
/// The type argument `T` is the route's return type, as used by
/// [currentResult], [popped], and [didPop]. The type `void` may be used if the
/// route does not return a value.
```

### PR DESCRIPTION
**Pull request by a14n**
## Description

This PR allows to have Route<void> by removing constraints on type parameter on every parameterize methods on Navigator.

## Related Issues

* Fixes flutter/flutter#65938

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 3 untriaged digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/65997

**Comment by a14n** [comment]
I initially replaced `<T extends Object>` with `<T>` but it would cause issue in nullsafety because of the `@optionalTypeArgs` annotation. Basically:

```dart
// with nullsafety
// with <T extends Object>
Navigator.pushNamed<void>(context, '');   // 'void' doesn't extend 'Object'  
// with <T>
Navigator.pushNamed(context, ''); // Missing type arguments for generic method 'pushNamed<T>'
```

With `@optionalTypeArgs` it looks like the way to make it works is to use `<T extends Object?>`

**Comment by skia-gold** [comment]
Gold has detected about 3 untriaged digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/65997

**Comment by goderbauer** [comment]
Looks good, could you maybe add a test for this change to make sure that in the future we never disallow `void` routes again?

**Comment by a14n** [comment]
> Looks good, could you maybe add a test for this change to make sure that in the future we never disallow `void` routes again?

I added a test with explicit `<void>`.

**Comment by skia-gold** [comment]
Gold has detected about 6 untriaged digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/65997

**Review by goderbauer — APPROVED** [review]
LGTM.

Thanks for adding the test!

**Pull request merged**
