### PR TITLE
Recalculate theme values based on brightness with ThemeData.copyWith and add Theme.merge

### LINKED ISSUE #9148: Theme should be easier to use?
"changing the accent color on an input on one screen is complicated" was feedback offered about our theming system.

Ian says on solution here would be to add a copyWith constructor onto theme?

Did I capture that correctly @Hixie?

### PR DESCRIPTION
**Pull request by wilkomanger**
## Description

`ThemeData.copyWith` now recalculates all default values when the brightness changes.

`Theme.merge` uses this to provide a new `Theme` to their descendants.

Unfortunately it's not a `ThemeData` that's passed to `Theme.merge`, but the parameters themselves. If it's desired I can change it to make it pass a `ThemeData`, but I didn't at first to keep things simpler.

## Related Issues

Fixes #9148. And is relevant to #9871.

## Tests

I still need to add tests, but let's first see if the PR is wanted :smile:.

Please let me know if something's missing or should be improved! It's probably not as polished as it could be yet.

### CODE REVIEW

**Comment by HansMuller** [comment]
Thanks for checking in about this before plunging too far ahead. This is good work, although it doesn't quite line up with our plans for the future.

> ThemeData.copyWith now recalculates all default values when the brightness changes.
This is an interesting idea however it's inconsistent with the simple semantics for `copyWith()` methods in Flutter in general. It's also the case that we'd like to move away from having components compute defaults based on the theme's brightness and towards using the theme's colorScheme, which itself depends on the brightness.

> ThemeData.merge()
Eventually, once the ThemeData has been cleanup and the component themes have been normalized per [flutter.dev/go/material-theme-system-updates](https://flutter.dev/go/material-theme-system-updates), I think it would make sense to add a ThemeData.merge() method. I think it would be best to define such a method as `merge(otherThemeData)` since a common usage pattern would be merging with a parent Theme. And to make the semantics of such a thing manageable, the (normalized) component themes would have to provide merge methods as well.

**Comment by wilkomanger** [comment]
Okay, thanks! Agreed. I do think it's still valuable to have some method take a certain `ThemeData` and 'make it dark/light', or does that also not match future plans? If it does, I suppose it would be based on `ColorScheme` only?

**Comment by HansMuller** [comment]
Yes, the idea is that the color scheme will drive the dark/light variations. It's possible that some components may tweak a component-property-specific default based on the theme's brightness, but the overall idea is to defer to the color scheme.

**Comment by wilkomanger** [comment]
So, for the same idea but using a `ColorScheme`, there could still be some function that takes the current `ThemeData` (or even just a `ColorScheme`) and a `Brightness`, and recalculate all default values of that scheme? What could it be called (as we're not going with `copyWith()`)?

**Comment by HansMuller** [comment]
A ColorScheme method that produced a new ColorScheme with darkened or brightened colors - while adhering to the a11y contrast guidelines - would be useful. There are probably other operations that make sense, like increasing the contrast or changing the hue.

**Comment by wilkomanger** [comment]
Alright, seems a bit more complex, but I can try it!

**Comment by HansMuller** [comment]
Here's some inspiration if you decide to go for it: https://material.io/design/color/#tools-for-picking-colors

**Comment by wilkomanger** [comment]
Thanks!

**Comment by HansMuller** [comment]
I'm going to close this PR since https://github.com/flutter/flutter/pull/53526#issuecomment-607988883 is likely to be developed as a new one.

**Pull request closed without merging**
