### PR TITLE
[macOS,iOS] CocoaPods recommended version: 1.13.0

### PR DESCRIPTION
**Pull request by cbracken**
Due to changes in Xcode 15, several variables such as `DT_TOOLCHAIN_DIR` have been eliminateed in favour of others such as `TOOLCHAIN_DIR`. This broke CocoaPods support under Xcode 15, as reported in: https://github.com/CocoaPods/CocoaPods/issues/12012

@vashworth worked around this in Flutter in:
https://github.com/flutter/flutter/pull/132803

The CocoaPods issue was resolved by the following PR to their repo: https://github.com/CocoaPods/CocoaPods/pull/12009
and was released in CocoaPods 1.13.0.

Also switches from an if-else chain to a switch for CocoaPodsStatus handling.

Related: https://github.com/flutter/flutter/issues/133584
Related: https://github.com/flutter/flutter/issues/132755

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by vashworth — COMMENTED** [review]
The code LGTM, but I don't know that we should recommend a new version without running our CI against it first.

**Comment by vashworth** [comment]
There's an outstanding issue for upgrading our CI to 1.12.1 https://github.com/flutter/flutter/issues/133096, which was blocked by https://github.com/flutter/flutter/issues/122057

**Comment by cbracken** [comment]
Yes - we should definitely update CI before landing this.

**Comment by cbracken** [comment]
Actually, what I'll do to minimise this patch is separate out the refactor to using a case statement and adding the upgrade string from the actual version bump. When the next version bump comes along, whoever does it would probably appreciate having the previous patch as minimal as possible.

Will send a separate patch for that work and rebase this one on it.

**Comment by christopherfujino** [comment]
I believe this is blocked on updating the way we get ruby on our mac bots

**Comment by cbracken** [comment]
Yep - that, and then updating our own bots is what this is waiting on.

**Comment by gspencergoog** [comment]
@godofredoc What is the status of updating Cocoapods on the bots? (Desktop Triage)

**Comment by christopherfujino** [comment]
@cbracken I think we're unblocked after https://github.com/flutter/flutter/pull/136929

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
