### PR TITLE
[versions] update to latest web driver

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Unblocks engine roll due to dart:io HttpClient interface change

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
This is a duplicate of https://github.com/flutter/flutter/pull/50926

Let's just land whichever one passes CI first.

**Comment by dnfield** [comment]
Argh. That one ended up with a bunch of merge conflicts.

**Comment by jonahwilliams** [comment]
Oops, yeah the kick tree updated test and was older

**Comment by jonahwilliams** [comment]
Tree is green on build dashboard, merging

**Pull request merged**
