### PR TITLE
Reland 3: Display Features

### PR DESCRIPTION
**Pull request by andreidiaconu**
This reverts commit 2468f315e0a7a3e3fabaec38913a8dc8c0b619db.

List which issues are fixed by this PR
- https://github.com/flutter/flutter/issues/49411
- Needed for landing Engine: https://github.com/flutter/engine/pull/29585
- Initial Framework PR: https://github.com/flutter/flutter/pull/89511

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 22 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/93240

**Comment by andreidiaconu** [comment]
I am not sure why, but [one of the tests fails](https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20framework_tests_misc/9907/overview), unrelated to the changes in this PR.

Test output is 
```Failed assertion: line 150 pos 14: 'diff.inMilliseconds > -1': timeDiffs were: [0:00:00.015618, 0:00:00.026335, 0:00:00.010335, 0:00:00.009855, 0:00:00.009491, 0:00:00.009163, 0:00:00.001837] (offending time was -1ms)```

From what I can gather, one of the Durations in that array is below `-1`, measured in milliseconds - but all the Durations seem positive from the output. This PR is running with an older engine at this point, so perhaps that has something to do with it. Is this by any chance a flaky test? 

@blasten could you please advise?

**Comment by andreidiaconu** [comment]
@Piinks I see you added yourself as a reviewer. I updated the engine version, but the tree is currently broken.

**Review by blasten — APPROVED** [review]
LGTM

**Comment by andreidiaconu** [comment]
Resolved the conflict in `engine.version` but I assume that https://github.com/flutter/flutter/issues/93975 and https://github.com/flutter/engine/pull/29868 need to be closed before this.

**Comment by jason-simmons** [comment]
Merged https://github.com/flutter/engine/pull/29868

@andreidiaconu Can you update `engine.version` in this PR to https://github.com/flutter/engine/commit/30eb4d6974f6abcb5a9f5117da4da6f254ff5799?

**Comment by andreidiaconu** [comment]
It was already very late on my side. Thank you for everything!

**Comment by Piinks** [comment]
> @Piinks I see you added yourself as a reviewer. [flutter/engine#29585](https://github.com/flutter/engine/pull/29585) was merged. I updated the engine version, but the tree is currently broken.

Thanks @andreidiaconu! Glad this has been merged. I've been adding myself to keep track of all the various parts. Thanks for all of your hard work on this! :)

**Pull request merged**
