### PR TITLE
Clean up flutter_test/test/controller_test.dart

### PR DESCRIPTION
**Pull request by Hixie**
Instead of using a custom WidgetController, which is very brittle, we just use the usual infrastructure.

Also, use structured data instead of an array.

This adds offsetMoreOrLessEquals to handle small floating point errors in offsets.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @dkwingsmt

**Comment by Hixie** [comment]
cc @dnfield this may conflict with yours (rectMoreOrLessEquals). Also, I added a @template to avoid duplicating the prose in the docs, which you may wish to use in yours.

**Comment by dnfield** [comment]
I landed #30942 -  do you want me to work on the merge conflicts here?

**Comment by Hixie** [comment]
Merge conflicts are fixed, just needs review.

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
@Hixie Can you resolve the merge conflict?

**Comment by Hixie** [comment]
Feel free to land this if the tree is green.

**Pull request merged**
