### PR TITLE
Add a "flutter debug_adapter" command that runs a DAP server

### PR DESCRIPTION
**Pull request by DanTup**
This PR adds a new (hidden) `"flutter debug_adapter"` command that provides a [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/) implementation for running and debugging Flutter apps (and in a later PR, tests).

This is Flutter's equivalent of the [`"dart debug_adapter"` command](https://github.com/dart-lang/sdk/tree/main/pkg/dds/tool/dap#debug-adapter-protocol) in the Dart SDK, but provides additional Flutter-specific functionality (like running using the `flutter` tool instead of `dart`, and support for things like Hot Restart). Most functionality is implemented by the base Dart DAP classes that are imported from DDS, with only the Flutter-specific parts being added here.

By including this in the SDK, any DAP-compatible editors will be able to run/debug Dart and Flutter apps (without resorting to hacks like extracting Dart-Code's TypeScript implementation and using that). It's essentially the debugging equivalent of LSP.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

@christopherfujino @bkonyi

Sorry for the large PR, this was pretty much the minimum I could do that could correctly launch and run Flutter apps because there's a fair bit of plumbing. Future PRs that add in the rest of the functionality should (in theory) be much smaller!

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by christopherfujino** [comment]
For posterity, I got debugging working in neovim and this PR and journaled it in https://gist.github.com/christopherfujino/80be0f4cd88f75c4991b478e6b071153

**Comment by ericdallo** [comment]
Awesome @DanTup, LMK when this is available so I can make the necessary changes for Emacs :)

c/c @yyoncho

**Comment by DanTup** [comment]
I don't think the latest failure is related to this PR (it's in other integration tests I don't believe this change affects), although I'm not sure how to interpret the message to understand what failed:

```
00:16 +0: loading C:\b\s\w\ir\x\w\flutter\dev\automated_tests\integration_test\trivial_widget_test.dart                                                                                                
00:16 +0: A trivial widget test                                                                                                                                                                        
00:16 +1: A trivial widget test                                                                                                                                                                        
00:16 +1: (tearDownAll)                                                                                                                                                                                
00:16 +1: All tests passed!                                                                                                                                                                            
  
  <<stderr>>
  
  - - - -----8<----- - - -
  
  package:test_api                             expect
  test\integration.shard\test_test.dart 296:5  _testFile
  

01:18 +1 -1: loading test\integration.shard\test_test.dart                                                                                                                                             
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.

01:18 +1 -1: test\integration.shard\test_test.dart: flutter test set the working directory correctly 
```

**Review by christopherfujino — APPROVED** [review]
LGTM!

**Comment by liangxianzhe** [comment]
Hi @DanTup, I tried this and it works great. Thanks for this! One small question, reading the PR, it seems only `hotReload` and `hotRestart` are supported as custom commands. Is there a plan to add others like `debugDumpRenderTree`, etc?

**Comment by DanTup** [comment]
@liangxianzhe I'm not very familiar with `debugDumpRenderTree` but if it's a service extension then it should be callable via the `callService` custom request (see [here](https://github.com/dart-lang/sdk/blob/main/pkg/dds/tool/dap/README.md#callservice) - it's in the Dart DAP doc because it's available in both Dart and Flutter adapters). This is how VS Code does things like toggle debug painting (I don't know if your "etc." meant things like debug painting which are already exposed in VS Code).

If it's not available as a service extension or in the [flutter daemon](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/doc/daemon.md) then it would need exposing via one of those before the debug adapter could expose it.

**Comment by liangxianzhe** [comment]
Thanks @DanTup, (not sure if we should move the discussion somewhere else). Are you able to run `callService` successfully? For me, it seems `hotRestart` works, but `callService` doesn't.

I'm using nvim. Tail the `dap.log` shows that `debugPaint` and `debugDumpRenderTree` are both service extensions (among with many others):
```
[ WARN ] 2022-11-04T09:46:46Z-0700 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:888 ]	"No event handler for "	{
  body = {
    extensionRPC = "ext.flutter.debugPaint",
    isolateId = "isolates/629036477267839"
  },
  event = "dart.serviceExtensionAdded",
  seq = 33,
  type = "event"
}
...
[ WARN ] 2022-11-04T09:46:46Z-0700 ] ...nvim/site/pack/packer/start/nvim-dap/lua/dap/session.lua:888 ]	"No event handler for "	{
  body = {
    extensionRPC = "ext.flutter.debugDumpRenderTree",
    isolateId = "isolates/629036477267839"
  },
  event = "dart.serviceExtensionAdded",
  seq = 40,
  type = "event"
}
```

Trying to `callService` doesn't work:
```
lua require('dap').session():request('callService', {method = 'ext.flutter.debugPaint', params = {enabled = 'true', isolateId = 'isolates/629036477267839'}})
```
while, `hotRestart` works:
```
lua require('dap').session():request('hotRestart')
```

Any pointer on how to further debug this?

**Comment by DanTup** [comment]
@liangxianzhe it seems to work in my testing - I captured this using **Dart: Capture Debug Logs** in VS Code and then toggling the debug paint:

```

# VS Code sending request to DAP (req1)
[11:31:58 AM] [DAP] [Info] <== {"command":"callService","arguments":{"method":"ext.flutter.debugPaint","params":{"enabled":true,"isolateId":"isolates/2324209834572387"}},"type":"request","seq":11}

# DAP sending request to VM Service (req2)
[11:31:58 AM] [General] [Info] [Flutter (iPhone 14 Pro Max)] ==> [VM] {"jsonrpc":"2.0","id":"3917","method":"ext.flutter.debugPaint","params":{"enabled":true,"isolateId":"isolates/2324209834572387"}}

# Event from VM Service to DAP about state change
[11:31:58 AM] [General] [Info] [Flutter (iPhone 14 Pro Max)] <== [VM] {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.ServiceExtensionStateChanged","isolate":{"type":"@Isolate","id":"isolates/2324209834572387","name":"main","number":"2324209834572387","isSystemIsolate":false,"isolateGroupId":"isolateGroups/3891113904111409424"},"timestamp":1667820718530,"extensionData":{"extension":"ext.flutter.debugPaint","value":"true"}}}}

# Event passed back from DAP to VS Code
[11:31:58 AM] [DAP] [Info] ==> {"seq":9333,"type":"event","body":{"extension":"ext.flutter.debugPaint","value":"true"},"event":"flutter.serviceExtensionStateChanged"}

# Response back from VM Service for request (req2)
[11:31:58 AM] [General] [Info] [Flutter (iPhone 14 Pro Max)] <== [VM] {"jsonrpc":"2.0","result":{"enabled":"true","type":"_extensionType","method":"ext.flutter.debugPaint"},"id":"3917"}

# Response from DAP to VS Code to the original request (req1)
[11:31:58 AM] [DAP] [Info] ==> {"seq":9334,"type":"response","body":{"enabled":"true","type":"_extensionType","method":"ext.flutter.debugPaint"},"command":"callService","request_seq":11,"success":true}
```

Are you able to capture the protocol traffic to the DAP server to see exactly what is being sent (and what it is responding with)?

**Comment by DanTup** [comment]
(note: I tested this on latest master, though I wouldn't expect it to make much difference if you're on the most recent stable)

**Comment by DanTup** [comment]
Oh, one thing I noticed is that in your snippet it looks like `enabled` may be sent as a string?

> `enabled = 'true'`

In my VS Code log, it's a literal `boolean`:

> `"enabled":true`

**Comment by liangxianzhe** [comment]
I upgrade flutter version and it works now. Actually both `true` and `'true'` works. Thanks again!

Paste the command here in case anyone sees this thread in the future:
1. Find the isolate id by `tail -f ~/.cache/nvim/dap.log`.

**Comment by DanTup** [comment]
@liangxianzhe ah, glad you got it working. I'm not sure what changed since the current stable version related to this, but there have been a few fixes recently. If you're able to add some code for this, you should be able to capture the `isolateId` from the `dart.serviceExtensionAdded` event so you don't need to fish it out of log files. I don't know how easy that will be in nvim though (it's what we do in the VS Code extension).

**Comment by liangxianzhe** [comment]
Yeah, that should be easy. I will write a plugin for that when I got time.

**Pull request merged**
