### PR TITLE
Merge analaytics from docs site and flutter.io site.

### LINKED ISSUE #24072: Consolidating flutter.io and docs.flutter.io analytics
We'd like to consolidate analytics from both flutter.io and docs.flutter.io by using the same Google Analytics (GA) ID, and it should be doable since they are under the same domain.  

GA was initially added to docs.flutter.io in this PR https://github.com/flutter/flutter/pull/966, which was different from [the one used by flutter.io](https://github.com/flutter/website/blob/18f758d3b3251473d87dbf9b2003740f92283ec0/src/_includes/head.html#L47).

### PR DESCRIPTION
**Pull request by gspencergoog**
Fixes #24072

### CODE REVIEW

**Comment by InMatrix** [comment]
From [this PR](https://github.com/flutter/flutter/pull/966/files), the GA tracking id also exists in doc/index.html, in addition to analytics.html.

**Comment by gspencergoog** [comment]
Yeah, but the "doc" directory no longer exists.  That PR was a loooong time ago.  I searched for the analaytics ID over the entire codebase, and it only appears in the one file.

**Comment by InMatrix** [comment]
Cool, thanks for double checking.

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
