### PR TITLE
Manual roll of engine 45b66b7...ffba2f6

### PR DESCRIPTION
**Pull request by a-siva**
git log 45b66b7...ffba2f6 --oneline

ffba2f68d Roll src/third_party/dart b37aa3b036...0abff7b2bb (flutter/engine#9588)

62514cb77 Roll fuchsia/sdk/core/mac-amd64 from n9fZpXVmsbgKZzS8Q2GXxB453q8AbLpfGztsPsq47pMC to BYCwsJf7r7zfd2THSGinFeIHv552AEVchXdc7VZzP0IC (flutter/engine#9587)

9f2721284 Roll src/third_party/skia e4c88bb1f848..1ddee025229a (7 commits) (flutter/engine#9586)

03a31e0ad Roll fuchsia/sdk/core/linux-amd64 from F9oY0d56X3aONxwv5vw9Gco--AHmC8SHuDXdhdWCnnMC to d2VK3FYSEKQ35UdZw5FdbOZUI_xgT0-1h8DnGDUHPVAC (flutter/engine#9583)

### CODE REVIEW

**Review by bkonyi — APPROVED** [review]

**Comment by liyuqian** [comment]
This seems to break ~10 build bots: https://flutter-dashboard.appspot.com/build.html. Shall we revert?

**Comment by a-siva** [comment]
A fix for the breaks has been submitted on top of this.

**Comment by tvolkert** [comment]
This yielded a significant regression in the following benchmarks:

* hot_mode_dev_cycle__benchmark -- hotReloadMillisecondsToFrameAfterChange
* hot_mode_dev_cycle_linux__benchmark -- hotReloadMillisecondsToFrameAfterChange

@a-siva can you please investigate?

**Comment by tvolkert** [comment]
Looks like a 200-250ms regression in hot reload times on Linux and Mac.

**Comment by bkonyi** [comment]
We're tracking the regression here: https://github.com/flutter/flutter/issues/35551

**Pull request merged**
