### PR TITLE
License update

### PR DESCRIPTION
**Pull request by Hixie**
* Update project.pbxproj files to say Flutter rather than Chromium.
* The templates now have an empty organization so that we don't cause people to give their apps a Flutter copyright.
* Update copyrights on all files to be consistent.
* Remove copyrights from templates.
* Update the copyright notice checker to require a standard notice on all files.

For review purposes you are encouraged to use the separate commits.

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
RSLGTM

(I did not look at every single changed license header)

**Comment by jmagman** [comment]
A few more if you look for "Google LLC" like https://github.com/flutter/flutter/blob/dda74a1993986b2bedfe35efed85f56332032559/packages/flutter_tools/templates/app/macos.tmpl/Runner.xcodeproj/project.pbxproj.tmpl#L198

**Comment by Hixie** [comment]
@jmagman interesting.

**Comment by goderbauer** [comment]
The tree is green, but the tests on this PR are not. :)

**Pull request merged**
