### PR TITLE
remove unnecessary null check

### PR DESCRIPTION
**Pull request by a14n**
This PR fixes upcoming lint reports bring by https://github.com/dart-lang/linter/pull/3258

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM, thanks!

**Comment by a14n** [comment]
> Google testing — Google testing failed. Please contact a Google developer to investigate.

@goderbauer could you have a look please?

**Comment by goderbauer** [comment]
Looks like an unrelated flake. The check should turn green momentarily.

**Comment by christopherfujino** [comment]
test-exempt: semantically equivalent workaround for lint

**Pull request merged**
