### PR TITLE
Increase connection timeout

### PR DESCRIPTION
**Pull request by szakarias**
This should fix the flutter_view_ios__start_up_test  flakiness.

### CODE REVIEW

**Review by jakobr-google — APPROVED** [review]
LGTM

**Comment by szakarias** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
Interesting. When @Hixie and I looked at it last, our impression was that the issue was due to `iproxy` process dying before we connect to observatory. Is this fixing that issue or is it about something else?

**Comment by szakarias** [comment]
Before #13296 the test was failing due to a missing pod dependency. We currently only run `pod install` in the tooling if the app uses plugins, thus I needed to add a `pod install` step for the flutter_view_ios__start_up test. My assumption was that the added time for `pod install` was causing the timeout, but increasing the connection timeout to 30 seconds didn't help. Do you still believe that the problem is with the `iproxy`, and do you have an idea for a fix?

**Comment by yjbanov** [comment]
No, I was just confirming with you if this was something `iproxy`-related. No fix ideas yet for that issue. Need more data.

**Pull request merged**
