### PR TITLE
Update dependencies to bring updated dependency on watcher-0.9.7+6

### PR DESCRIPTION
**Pull request by aam**
This is supposed to fix build and test failures.

### CODE REVIEW

**Comment by Hixie** [comment]
Why does this fix build failures?

**Comment by Hixie** [comment]
The patch LGTM, but I don't understand why this would fix failures. Is there some bug with the previous versions that just started being a problem or something?

**Comment by aam** [comment]
My understanding is that new version of watcher was published(watcher-0.9.7+6). flutter tools still has dependency on  watcher-0.9.7+4. That created conflict that resulted in broken build on my PR which has nothing to do with watcher or updating of any dependencies. This PR essentially bumps flutter tools dependency on watcher up to 0.9.7+6.

**Comment by Hixie** [comment]
But what was the conflict? There shouldn't be any problem with us being on watcher-0.9.7+4, if it worked before why would it not work now?

**Comment by aam** [comment]
All three build failures are `flutter analyze --flutter-repo` failures of same form:

```
Executing: /home/linux2/.cocoon/flutter/dev/devicelab/../../bin/flutter analyze --flutter-repo --benchmark
stderr: Package "watcher" has conflicts:
stderr:   25 sources want "/home/linux2/.pub-cache/hosted/pub.dartlang.org/watcher-0.9.7+6/lib":
...
stderr:   1 source wants "/home/linux2/.pub-cache/hosted/pub.dartlang.org/watcher-0.9.7+4/lib":
stderr:     /home/linux2/.cocoon/flutter/packages/flutter_tools/.packages
```

**Comment by Hixie** [comment]
I don't understand. Where was the 0.9.7+6 version coming from?? The whole point of the pubspec.yaml files hard-coding every package version is that it should be impossible for us to accidentally depend on random versions of packages.

**Comment by Hixie** [comment]
Maybe cocoon itself depends on watcher without a pinned dependency? cc @yjbanov

**Comment by aam** [comment]
> Where was the 0.9.7+6 version coming from??  

Not sure. The only project in flutter repo with watcher dependency is flutter_tools.

**Comment by aam** [comment]
This fixed original problem with `watcher` but broke more tests, seemingly because upgrade to 
```
-  url_launcher: 1.0.3
+  url_launcher: 2.0.0
```
(that is based on failure
```
stderr: Build file '/home/linux2/.pub-cache/hosted/pub.dartlang.org/url_launcher-2.0.0/android/build.gradle' line: 6
stderr: 
stderr: * What went wrong:
stderr: A problem occurred evaluating project ':url_launcher'.
stderr: > Could not find method google() for arguments [] on repository container.
```

I will revert this PR, will create another one that moves up only watcher to 0.9.7+6.

**Comment by Hixie** [comment]
Looks like the script isn't working right. Various of our packages depend on test, which depends on analyzer, which depends on watcher, but for some reason we're not noticing that they depend on watcher.

**Comment by Hixie** [comment]
I have a fix for the script.

**Pull request merged**
