### PR TITLE
Cherry-picks

### PR DESCRIPTION
**Pull request by tvolkert**
roll ios-deploy version to 2fbbee77ea2b3212959b9dddda816f59094cd7cd (#40398)

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by christopherfujino** [comment]
I'm guessing the CocoaPods failures are the issue @digiter mentioned in infra discord about our VMs installing tip of tree cocoapods?

**Comment by christopherfujino** [comment]
@tvolkert do we also hotfix the cirrus change, or do we just leave the tests failing? https://github.com/flutter/flutter/pull/41145

**Comment by tvolkert** [comment]
Yeah, all cherry-picks to this branch have seen these failures - I've been ignoring them.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
