### PR TITLE
Remove unneeded local variables and comments in Editable and RenderParagraph

### PR DESCRIPTION
**Pull request by tgucio**
This PR removes unnecessary local variables and related comments in `Editable` and `RenderParagraph` as both now use another `TextPainter` instance for intrinsics cache.

Test-exempt: minor refactor and comments.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by LongCatIsLooong — APPROVED** [review]
Oops LGTM thanks for the fix!

**Comment by justinmc** [comment]
@tgucio Can you follow the instructions for getting a test exemption if you haven't already?

**Review by justinmc — APPROVED** [review]
LGTM but officially I think this needs a test exemption.

**Comment by tgucio** [comment]
@justinmc sure - I sent the request on Discord yesterday

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

**Pull request merged**
