### PR TITLE
Add objc doc to the dartdoc output

### PR DESCRIPTION
**Pull request by szakarias**

### CODE REVIEW

**Review by jakobr-google — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Note that we're not currently uploading docs so this won't actually have any effect at first. See https://github.com/flutter/flutter/issues/10940.

**Comment by szakarias** [comment]
Fixes #8867

**Comment by Hixie** [comment]
Looks like this didn't actually work, but we didn't notice because we weren't uploading the docs so the code in question never got run.

**Comment by tvolkert** [comment]
As seen in https://travis-ci.org/flutter/flutter/jobs/247597480:

```
Extracing objcdoc to dev/docs/doc/objcdoc
Expected file dev/docs/doc/objcdoc/objc/Classes/FlutterViewController.html not found
```

**Comment by szakarias** [comment]
I believe the path should be dev/docs/doc/objcdoc/Classes/FlutterViewController.html without 'objc' before 'Classes' but I see you fixed that in your commit.

**Pull request merged**
