### PR TITLE
Avoid unnecessary lambdas in SelectionOverlay.showHandles()

### PR DESCRIPTION
**Pull request by tgucio**
This PR removes the unnecessary lambdas in SelectionOverlay method showHandles().

No functional changes.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by LongCatIsLooong** [comment]
Hi @Hixie could you take a look at this pull request? It doesn't seem to be testable. Also I remember we have policies regarding accepting trivial (syntactic-sugar-only) changes, but I could find it in the wiki.

**Review by goderbauer — APPROVED** [review]
LGTM

You will need to get a test exception as described in https://github.com/flutter/flutter/pull/98409#issuecomment-1039187462 before we can merge this.

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

i'm surprised no lint caught this...

**Comment by goderbauer** [comment]
> i'm surprised no lint caught this...

https://github.com/dart-lang/linter/issues/3238

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
@Hixie 

> i'm surprised no lint caught this...

Turns out, the lint exists (`unnecessary_lambdas`), but we are not enforcing it because of: https://github.com/dart-lang/linter/issues/498. Basically, sometimes we explicitly want unnecessary lambdas (e.g. for anything passed to `setState`), but there is no method-side opt-out for the lint.

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

**Comment by tgucio** [comment]
Rebase error... will submit a new PR to fix.

**Pull request closed without merging**
