### PR TITLE
Increase Java heap limit to 8GB for plugin integration tests using deferred components

### LINKED ISSUE #156953: Windows tool_integration_tests_2_9 is 3.00% flaky
The post-submit test builder `Windows tool_integration_tests_2_9` had a flaky ratio 3.00% for the past (up to) 100 commits, which is above our 2.00% threshold.

One recent flaky example for a same commit: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_2_9/99
Commit: https://github.com/flutter/flutter/commit/566f606824c46c8ed1a4e841ce62c8a8298fe0bf

Flaky builds:
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_2_9/99
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_2_9/93
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_integration_tests_2_9/62

Recent test runs:
https://flutter-dashboard.appspot.com/#/build?taskFilter=Windows%20tool_integration_tests_2_9

Please follow https://github.com/flutter/flutter/blob/master/docs/infra/Reducing-Test-Flakiness.md#fixing-flaky-tests to fix the flakiness and enable the test back after validating the fix (internal dashboard to validate: go/flutter_test_flakiness).

### PR DESCRIPTION
**Pull request by bkonyi**
Should help resolve https://github.com/flutter/flutter/issues/156953

### CODE REVIEW

**Review by reidbaker — APPROVED** [review]

**Comment by reidbaker** [comment]
I think this is correct but am leaving a breadcrumb for myself. If it turns out this issue is actually about the number/length of command line args then GRADLE_OPS documented in https://docs.gradle.org/current/userguide/build_environment.html is the right next place to expand.

**Review by christopherfujino — COMMENTED** [review]
When I `grep -rnI 'Xmx4G'`, I get a lot of hits. Should we just mass update them all?

**Comment by christopherfujino** [comment]
Also, per https://github.com/flutter-pub-roller-bot/flutter/commit/225e4aabb50ecd0676ab0871e6022769974e17f2, should we bump the MaxMetaspaceSize and add a flag for ReservedCodeCacheSize?

I'm genuinely asking. I don't understand any of these, and going into swap would be bad too, maybe worse since it's be hard to detect?

**Comment by reidbaker** [comment]
> When I `grep -rnI 'Xmx4G'`, I get a lot of hits. Should we just mass update them all?

I dont think we should update all of the heap sizes. Lets see if this helps. 4 gigs is really big

**Comment by christopherfujino** [comment]
> > When I `grep -rnI 'Xmx4G'`, I get a lot of hits. Should we just mass update them all?
> 
> I dont think we should update all of the heap sizes. Lets see if this helps. 4 gigs is really big

I agree that 4gb is REALLY big. I'm not happy about upping this. I also have no better idea...

**Comment by christopherfujino** [comment]
> > When I `grep -rnI 'Xmx4G'`, I get a lot of hits. Should we just mass update them all?
> 
> I dont think we should update all of the heap sizes. Lets see if this helps. 4 gigs is really big

I'm ok with updating just this one app.

**Comment by bkonyi** [comment]
Yeah, I'm not happy with it either but... *shrugs*

@reidbaker should we also update `MaxMetaspaceSize` and `ReservedCodeCacheSize` as @christopherfujino suggested?

**Comment by reidbaker** [comment]
My gut its that we should only update the ones we think will do something. 
https://stackoverflow.com/questions/31455644/should-i-set-a-maxmetaspacesize indicates that the cost of bumping that value is proably low. 

From https://stackoverflow.com/questions/7513185/what-are-reservedcodecachesize-and-initialcodecachesize we are not seeing the logs that would have me think that value would help. Honestly I wonder if dropping these memory settings to nothing might be a better solution. 

FWIW I dont expect bumping to 8 gb will help but I dont have better solutions for you.

**Pull request merged**
