### PR TITLE
Update macOS version in tests

### PR DESCRIPTION
**Pull request by RDIL**
removed

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

I'll land this when our build goes green.

**Comment by dnfield** [comment]
@RDIL - we need images that have Xcode 9.4.1 for https://github.com/flutter/engine

Can we get a mojave image that has that?  Or can it be added to the existing Mojave images so we can xcode-select it?

**Comment by RDIL** [comment]
I'll take a look

**Comment by RDIL** [comment]
@dnfield would it work if I installed both 9.4.1 and 10.1 onto the image?  Would you be able to select which version to use?

**Comment by dnfield** [comment]
That would be fine as long as we know the path and can sudo, e.g. `sudo xcode-select -s /Path/To/Xcode9.app` will do it

**Comment by fkorotkov** [comment]
Well, High Sierra images will be around. Most likely they won't be updated. Changed wording in the documentation to `Not maintained` rather than `Deprecated` to not be confusing.

**Comment by RDIL** [comment]
👍

**Comment by dnfield** [comment]
That should be fine for us.  It may be good to get an Xcode 9.4.1 on Mojave at some point, but it's not pressing for us.

**Pull request merged**
