### PR TITLE
Fix ios doc url

### PR DESCRIPTION
**Pull request by szakarias**

### CODE REVIEW

**Review by tvolkert — APPROVED** [review]
LGTM!

**Comment by tvolkert** [comment]
https://github.com/flutter/flutter/issues/11119

**Comment by eseidelGoogle** [comment]
Where do I find the docs?  I see Android linked from https://docs.flutter.io/ but not iOS?

**Comment by eseidelGoogle** [comment]
Sorry, they're at https://master-docs-flutter-io.firebaseapp.com/, but it appears to use an absolute URL and thus the link changes domain. :/

**Comment by szakarias** [comment]
Is this still an issue? The link from https://docs.flutter.io/ works fine for me.

**Comment by tvolkert** [comment]
Now that we've released this PR to alpha, the public link works

**Comment by szakarias** [comment]
Great!

**Pull request merged**
