### PR TITLE
Silence an analyzer warning.

### PR DESCRIPTION
**Pull request by Hixie**
I don't understand why Travis hasn't been catching this.

### CODE REVIEW

**Comment by sethladd** [comment]
cc @pq any ideas?

**Comment by Hixie** [comment]
the warning I was getting with 1.13 (Travis is on 1.14) is that the final return in that function, when it was marked async, was returning a `Future<int>` rather than an `int`.

**Comment by Hixie** [comment]
cc @devoncarew

**Comment by pq** [comment]
FWIW: I'm seeing this warning on the `bleeding_edge` SDK (but I'm guessing that's not a surprise).  Not sure what build travis is on...

**Comment by sethladd** [comment]
Looks like 1.14.1 (from https://travis-ci.org/flutter/flutter/builds/107333174)

**Comment by devoncarew** [comment]
So @Hixie, you're seeing this on 1.13 but not 1.14? I'd guess that the strong more may have been improved to have specific knowledge of returning values from async functions. @jmesserly, @leafpetersen

**Comment by devoncarew** [comment]
lgtm, if you want to land this

**Comment by jmesserly** [comment]
Yeah, I can't reproduce this on current bleeding_edge Dart. My guess is it was a bug we fixed, although I don't recall it in particular. Definitely the original code should be fine (same for the new code).

**Comment by Hixie** [comment]
How is the original code fine?

**Comment by devoncarew** [comment]
You can return a non-Future from an async method, and it gets wrapped in a Future. So `return 2` and `return new Future.value(2)` would work the same.

**Comment by Hixie** [comment]
The problematic code is the final return, which returned a Future while the function was marked async.

**Comment by jmesserly** [comment]
That is legal too, for better or worse. The spec defines the result as Future< flatten(T) > where flatten will unwrap a Future (flatten has a slightly more complex definition, but that's the essence).

(In strong mode, we recently extended this typing to all Futures, so Future<T> is now interpreted as Future< flatten(T) >, because that's how all of the methods on Future are implemented. They always flatten, so it's the only way to make the static type system correctly capture the runtime behavior. There's some crazy bugs you can get into otherwise.)

**Comment by Hixie** [comment]
oh, interesting. Ok. In that case this change isn't necessary.

**Pull request closed without merging**
