### PR TITLE
fix: `moreOrLessEquals` does not allow `actual` to be integers

### LINKED ISSUE #125600: `moreOrLessEquals` does not allow `actual` to be integers
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

```
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('when actual is int', () {
    expect(100, moreOrLessEquals(100));
  });

  test('when actual is double', () {
    expect(100.0, moreOrLessEquals(100));
  });
}
```

### Expected results

no err

### Actual results

the "when actual is int" errors:

```
package:test_api                                    expect
package:flutter_test/src/widget_tester.dart 460:16  expect
test/a.dart 5:5                                     main.<fn>

Expected: 100.0 (±1e-10)
  Actual: <100>
   Which: 100 is not in the range of 100.0 (±1e-10).
```

### Code sample

<details><summary>Code sample</summary>

```dart
see above
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
unrelated
```

</details>

### PR DESCRIPTION
**Pull request by fzyzcjy**
Close https://github.com/flutter/flutter/issues/125600

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by werainkhatri — APPROVED** [review]
oh wow. thanks for fixing this. LGTM.

**Comment by fzyzcjy** [comment]
You are welcome!

**Comment by fzyzcjy** [comment]
Btw, tree tip is green + 2 approvals + autosubmit label + google testing passed, but the bot does not merge the PR after half an hour. Shall I file an infra bug?

image
image

**Pull request merged**
