### PR TITLE
[Waiting for Router] findRouteByName method in NavigatorState

### PR DESCRIPTION
**Pull request by long1eu**
I find this kind of method very useful when I want to create complicated nonlinear navigation patterns. I mostly use it in conjunction with removeRoute and replaceRoute.

### CODE REVIEW

**Comment by Hixie** [comment]
I'm actually working on a complete alternative for this API that would just make everything much more usable without having to worry about finding routes and stuff. I suggest we hold off for a while before adding anything else to the API, to see if the new approach means we can just forget about this API.

**Comment by long1eu** [comment]
I think this will do little harm if it will still be added there.

**Comment by long1eu** [comment]
as I said, I don't think this method would do any harm

**Comment by Hixie** [comment]
@long1eu Everything we add does harm in a sense -- it makes the initial download bigger, makes apps bigger, introduces more places where we have to write and maintain documentation, it means more tests, more tests take longer to run, more tests can break, more APIs means people have to learn more when looking at the API, which means the API is harder to maintain, etc etc etc.

That said, maybe it's a good idea. I'm not closing the PR, because I want to see if, with the new Router work, it is still needed. I don't want to land it in the meantime because if it turns out it's not needed, then not having it is strictly better than having it.

**Comment by long1eu** [comment]
Good reasoning! Thanks!

sâm., 24 mar. 2018, 08:56 Ian Hickson <notifications@github.com> a scris:

**Comment by Hixie** [comment]
This is still on my radar. Sorry for the extended delay.

**Pull request closed without merging**
