### PR TITLE
[web] enable CanvasKit tests using a local bundle fetched from CIPD

### LINKED ISSUE #70101: [Web] CanvasKit binary being bundled instead of fetched from the CDN
## Use case

CanvasKit is currently being downloaded from the CDN resource, which can cause problems with very strict content security policies.

Since https://unpkg.com links used by Flutter point to the specific versions of CanvasKit WASM, whitelisting them manually to keep up-to-date is unfeasible (wildcarding is not always possible).

## Proposal

Bundle it with the app - this was already mentioned regarding CanvasKit in similar issues, e.g. https://github.com/flutter/flutter/issues/53639#issuecomment-606725675

### LINKED ISSUE #71604: Most canvaskit framework tests are failing
Now that flutter test --platform=chrome supports dart defines, I've added the ability to run the existing test suite with canvaskit enabled. Unfortunately, the vast majority of these tests are failing:

https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_tests/6679/steps?succeeded=true&debug=false

This has already helped identify one issue in the web engine:  https://github.com/flutter/engine/pull/22809 . Consider triaging the rest to find the common error cases. To run with canvaskit enabled locally:

`flutter test --platform=chrome --dart-define=FLUTTER_WEB_USE_SKIA=true test/file_to_test.dart`

### PR DESCRIPTION
**Pull request by yjbanov**
- Fetch CanvasKit from CIPD to the Flutter SDK cache.
- Copy CanvasKit files to `build/web/canvaskit` during `flutter build web`.
- Use the local CanvasKit copy (instead of unpkg.com) when running unit-tests.
- Add test shards that run currently passing tests in CanvasKit mode (which is the vast majority).
- Golden tests use the ("WebRenderer": "canvaskit") key/value pair to distinguish the goldens from the HTML ones.

Fixes https://github.com/flutter/flutter/issues/71604
Fixes https://github.com/flutter/flutter/issues/70101

### CODE REVIEW

**Review by CaseyHillers — APPROVED** [review]
.ci.yaml lgtm

**Review by christopherfujino — APPROVED** [review]
Some nits about the tests, but otherwise the tools change LGTM

**Review by keyonghan — APPROVED** [review]
LGTM with test ownership.

**Review by Piinks — COMMENTED** [review]
Should the test shards that are being added show up in CI here? They do not appear to be listed as checks, and without running them, Gold is not seeing this new info.

**Review by Piinks — COMMENTED** [review]
According to https://flutter-gold.skia.org/search?crs=github&issue=92134&patchsets=1&positive=true
these are the only builds that are sending info to Gold:

- Windows framework_tests_widgets
- Windows framework_tests_libraries
- Linux web_tests_5
- Linux web_tests_4
- Linux web_tests_3
- Linux web_tests_2
- Mac framework_tests_widgets
- Linux web_tests_1
- Linux web_tests_7_last
- Linux web_tests_6
- Linux framework_tests_widgets
- Linux web_tests_0
- Linux framework_tests_libraries
- Mac framework_tests_libraries

**Comment by yjbanov** [comment]
> Ah I see, ok! In that case it sounds like we would validate later that Gold is receiving the data correctly. Would that testing happen in post submit then? Currently the Gold flow checks images in during presubmit. It may cause some issues temporarily if these are run in post submit first, not sure though since we haven't done that before. upside_down_face

Oh no! Catch-22. @CaseyHillers save us!

**Comment by CaseyHillers** [comment]
> Oh no! Catch-22. @CaseyHillers save us!

@Piinks if we're not running in presubmit, I don't think there would be a way for gold to block PRs. This should be safe to land. If there's a breakage, that's a bug and we'll need to fix the process to adhere with the tree's flaky test policy.

**Review by mdebbar — APPROVED** [review]

**Review by Piinks — APPROVED** [review]
LGTM - Gold changes look fine, but will need to confirm and triage all of the images with the new key set once these shards are actually running.

**Comment by abelokon0711** [comment]
Could you explain me please how exactly does this solve #70101?

**Comment by P-B1101** [comment]
I think this command will use bundled canvaskit from your build folder.
`flutter build web --dart-define=FLUTTER_WEB_CANVASKIT_URL=/canvaskit/`
I test it using IIS from my localhost and it's worked. I think it will work on any other host too.

**Pull request merged**
