### PR TITLE
[a11y] Re-land Make sure RenderFractionalTranslation updates its semantics after the translation field is set

### LINKED ISSUE #20449: Semantic boxes are incorrect inside FractionalTranslation
`showCupertinoModalPopup()` uses a `FractionalTranslation` to slide a popup from offscreen into place. The semantic boxes for the popup are drawn while the popup is offscreen, and not updated once the popup is in its final position. Semantic boxes need to be updated once the animation is complete.

To reproduce, build a `CupertinoActionSheet` and show with `showCupertinoModalPopup()` in accessibility mode. Semantic boxes will not be in place when the action sheet is onscreen.

### PR DESCRIPTION
**Pull request by clocksmith**
## Description

Re-land https://github.com/flutter/flutter/pull/48985

This PR ensures that RenderFractionalTranslation calls markNeedsSemanticsUpdate after its translation is set/changed, so that semantics are properly updated (for instance if a FractionalTranslation is animating).

## Related Issues

closes #20449

## Tests

I added the following tests:

* added test in proxy_box_test.dart to make sure that markNeedsSemanticsUpdate is called when changing the translation value.
* added test in basic_test.dart to make sure that the semantics bounds get updated from a FractionalTranslation translation change

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by flar** [comment]
This change had a dramatic impact on the frame build times as can be seen in the `flutter_gallery__transition_perf_with_semantics/delta_average_frame_build_time_millis` benchmark on the flutter dashboard. The benchmark went from 2.4 to 7.4 milliseconds - or nearly triple the time.

**Comment by flar** [comment]
It looks like this change basically just enables some aspect of the semantics code for the ProxyBox so the performance hit is likely due to the performance of the semantics code.

I don't know enough about the semantics code to make an off-hand suggestion as to how to reduce its impact. Someone more familiar with semantics should look at why the performance hit was so dramatic.

**Comment by jonahwilliams** [comment]
Unfortunately the bug this changed fixed was fairly severe, so the benchmark was likely baselined under incorrect conditions. Similar to a rendering benchmark that didn't do any rendering, the semantics benchmark didn't do any semantics updating :(

**Comment by jonahwilliams** [comment]
That said, it is generally known that our semantics updates are computationally intensive.

**Comment by flar** [comment]
> Unfortunately the bug this change fixed was fairly severe, so the benchmark was baselined under incorrect conditions. Similar to a rendering benchmark that didn't do any rendering, the semantics benchmark didn't do any semantics updating :(

Well that explains the change. The issue should probably be closed then and the benchmark re-baselined?

**Pull request merged**
