### PR TITLE
Remove leftover of GlobalKey removal listeners

### PR DESCRIPTION
**Pull request by spkersten**

### CODE REVIEW

**Comment by goderbauer** [comment]
@spkersten Can you sign the CLA?

The change is LGTM

**Comment by spkersten** [comment]
@goderbauer Unfortunately I'm still waiting for approval by my employer. Will hopeful be soon now the holidays are over.

**Comment by goderbauer** [comment]
@spkersten I am going to close this PR for now because in the current state it is not actionable for us. Please feel free to re-open it if/when you can address the remaining comments. Thanks for your contribution!

**Comment by spkersten** [comment]
CLA should be signed now

**Pull request closed without merging**
