### PR TITLE
Reduce duration of benchmark to avoid timeout

### PR DESCRIPTION
**Pull request by dnfield**
The test is timing out because it's running for too long - it only has 30 seconds t ocomplete, letting the main benchmark portion go for 15 seconds makes it timeout.

Once the test has passed a few times I'll remove the flaky flag.

/cc @jonahwilliams @liyuqian

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
RSLGTM

**Comment by dnfield** [comment]
Ahh this is still timing out locally, spoke too soon.

**Comment by dnfield** [comment]
Ok, 5 is the right magic number to have it not timeout - and I manually verified that it still captures the important part fo when the benchmark is doing work.

**Comment by dnfield** [comment]
Going to land this on red to see if it deflakes the flaky benchmark.

**Pull request merged**
