### PR TITLE
make "flutter channel" work if used multiple times

### PR DESCRIPTION
**Pull request by Hixie**
git is incomprehensible to me (I read the docs on this multiple times and still don't get it) but apparently this is the right way to do this?

@Coder-256 if you agree that this is correct please let me know by leaving a comment here that says LGTM, thanks. (See https://flutter.io/design-principles/#code-review-and-checking-in-code for details on our code review process.)

### CODE REVIEW

**Comment by Coder-256** [comment]
After looking into it a bit more, it actually seems a bit more complicated. I'm thinking something like this would be best, but I would definitely like a second opinion:

```
static Future<Null> _checkout(String branchName) async {
  int result = await runCommandAndStreamOutput(
    <String>['git', 'show-ref', '--verify', '--quiet', 'refs/heads/$branchName'],
    workingDirectory: Cache.flutterRoot,
    prefix: 'git: ',
  );
  if (result == 0) {
    result = await runCommandAndStreamOutput(
      <String>['git', 'checkout', branchName],
      workingDirectory: Cache.flutterRoot,
      prefix: 'git: ',
    );
  } else {
    result = await runCommandAndStreamOutput(
      <String>['git', 'checkout', '--track', "origin/$branchName"],
      workingDirectory: Cache.flutterRoot,
      prefix: 'git: ',
    );
  }
  if (result != 0)
    throwToolExit('Switching channels failed with error code $result.', exitCode: result);
}
```

Also I'm not sure if it is a good idea to hardcode `origin`.

**Comment by Hixie** [comment]
We used to just do `git checkout <branchname>`, but it seems to conflict with directory names (git gets confused as to whether you mean a branch or a directory if there's one of each with the same name).

**Comment by Coder-256** [comment]
@Hixie I can't seem to reproduce that, can you give an example of how to trigger that problem?

**Comment by Hixie** [comment]
there's a `dev` directory in the root of the flutter repo. Go to that directory and type "git checkout dev" without having a local dev branch, and you won't switch to the "dev" branch.

(Neither `git checkout -B dev` nor `git checkout -b dev` seem to do what we want either, which is to actually check out the remote "dev" branch. They both just seem to create a local branch called `dev`.)

**Comment by Hixie** [comment]
This seems to be the right thing if the branch doesn't exist: `git checkout --track -b dev origin/dev`
If it does exist, then `git checkout dev` seems to do the right thing.

**Comment by Coder-256** [comment]
@Hixie That's exactly what the code in my second comment does (the `-b foo` is implied in `--track origin/foo`; you can add it explicitly if you want).

**Comment by Hixie** [comment]
Alright, let's try that.

**Comment by Hixie** [comment]
Alright, new PR in https://github.com/flutter/flutter/pull/14507.

**Pull request closed without merging**
