### PR TITLE
Add retrieve named route and has named route functions

### PR DESCRIPTION
**Pull request by spideythewebhead**
## Description

Add retrieve named route and has named route functions, to the navigator API.

## Tests

I added the following tests:

test/widgets/navigator_test.dart

test name => finds named route and returns it

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by spideythewebhead** [comment]
I forgot to mention that are some test failing, but there are not related with my changes..
Also is there is any help for the failing checks above? Any guide to what i have to do?

**Comment by goderbauer** [comment]
Given that we are moving away from the imperative API of the Navigator I don't think we should be adding more API to it.

/cc @chunhtai

**Comment by chunhtai** [comment]
As @goderbauer said, I suggest we close this PR as this should no longer be a problem if user migrate the router and page api. Does this sounds good to you, @spideythewebhead ?

**Comment by spideythewebhead** [comment]
Sure @goderbauer , thanks for the update!

**Pull request closed without merging**
