### PR TITLE
See if fixing indent fixes our missing caching

### PR DESCRIPTION
**Pull request by eseidelGoogle**
@abarth

### CODE REVIEW

**Comment by Hixie** [comment]
lgtm

**Comment by Hixie** [comment]
did it work?

**Comment by eseidelGoogle** [comment]
I don't think so, no.  The travis docs seem to not care about this indent for whatever reason. Maybe yaml doesn't.

https://docs.travis-ci.com/user/caching/#Arbitrary-directories

**Comment by a14n** [comment]
What make you say that the cache is missed? At line 219 I can see:

>found cache
>adding /home/travis/.pub-cache to cache

**Comment by eseidelGoogle** [comment]
Travis seems to see the cache just fine, but the pub gets are not any faster.  Even in the most recent build:  https://travis-ci.org/flutter/flutter

120s for a first-run ./dev/update_packages.dart is expected, and matches what I get on my mac for example.  But the second run on the same hardware is more like 10s.  We never seem to get that second run behavior, so presumably we're caching the wrong thing.

**Comment by Hixie** [comment]
Maybe the difference is that we don't cache the pubspec.lock files? But we can't cache those, that would prevent us from getting the latest packages each time.

**Comment by a14n** [comment]
@Hixie is right. If you don't check in `pubspec.lock` pub will try to resolve the dependency graph and `.pub-cache` does not help here (though it helps once the good versions are found to avoid downloading the package once again).
On your machine you should have the `pubspec.lock` generated after the first run of `pub get` and that's why it takes less time.
Usually it's not a good practice to check in `pubspec.lock` for packages. It's used mainly for final applications.
Another solution could be to use `pub get --offline` (it will try to resolve the dep graph from your cache) but the drawback is that your code will not be checked against the last matching versions.

**Comment by Hixie** [comment]
I don't really understand why pub is so slow at this. It doesn't seem like fundamentally a difficult problem.

**Pull request merged**
