### PR TITLE
Added `iconTheme` to `RawChip` in `ChoiceChip`

### LINKED ISSUE #110645: [M3] ChoiceChip `iconTheme` being ignored
## Steps to Reproduce

1. Run the dartpad to see bug 
https://dartpad.dev/?id=a2a304296afdb576fecf54c7d6cf0c94

If you look at 
https://github.com/flutter/flutter/blob/069f5042973dc4aafbf76a44ca14af7c0e2c2ca1/packages/flutter/lib/src/material/choice_chip.dart#L153-L181
You will see that `iconTheme` is not being passed into `RawChip`

**Expected results:** 
Icon to be red color

**Actual results:** 
Icon remained the same color, there is no way to supply our own color
<details>
<summary>Code sample</summary>

https://dartpad.dev/?id=a2a304296afdb576fecf54c7d6cf0c94
</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.22000.856], locale en-MY)
    • Flutter version 3.3.0 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (30 hours ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\samue\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components        

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\samue\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64 • Microsoft Windows [Version 10.0.22000.856]    

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

### PR DESCRIPTION
**Pull request by Mayb3Nots**
This issue prevents us from customizing the checkmark color when ChoiceChip is selected.

Fixes #110645

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by darrenaustin — CHANGES_REQUESTED** [review]
@Mayb3Nots thanks for the fix. Just some formatting issues to resolve below and we will be good to go.

**Comment by Mayb3Nots** [comment]
> @Mayb3Nots thanks for the fix. Just some formatting issues to resolve below and we will be good to go.

@darrenaustin Thanks for taking a look into it review request is done

**Review by darrenaustin — APPROVED** [review]
LGTM. Thx.

**Review by darrenaustin — CHANGES_REQUESTED** [review]
Oops, I spoke too soon. Looks like you have an analyzer failure. If you take a look in the checks section, the 'analyze-linux' tests failed. Click on the 'Details' link and it will tell you what the issue is. Something about an extra space at the end of a line.

**Review by justinmc — APPROVED** [review]
LGTM besides the analyzer failure 👍

**Review by darrenaustin — APPROVED** [review]
LGTM. Awesome. Thx.

**Pull request merged**
