### PR TITLE
fix FLUTTER_ANSI_TERMINAL check

### PR DESCRIPTION
**Pull request by goderbauer**
should have been included in the previous PR :(

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
This is unusual, usually we just treat the presence as the indicator. Can you elaborate on this?

**Comment by goderbauer** [comment]
This has to match whatever we do in the PS script (https://github.com/flutter/flutter/blob/master/bin/flutter.ps1#L24). Sure, we can change the logic there, but what`s your reasoning?

I briefly looked at the treatment of other env variables in flutter and found exactly one case were we just seem to rely on the presence.

**Comment by Hixie** [comment]
The reasoning is that the data type is "string", and there's no one true way to know if a particular string is "true" or "false". For example, people might expect any of `1`, `true`, `TRUE`, `YES`, or `y` to be true, though none would be with this patch. People might expect `True`, `tRue`, `trUe`, and `truE` to all do the same thing, but they won't with this patch.

I'm surprised that there are many cases where we have a magic string. I would have expected those cases to be limited to those where we are dealing with environment variables from other systems (like `TERM` here) where we don't decide the API.

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
