### PR TITLE
Re-apply "Send nextId in addition to previousId for traversal order"

### PR DESCRIPTION
**Pull request by tvolkert**
Re-applies flutter/flutter#14676

### CODE REVIEW

**Comment by tvolkert** [comment]
This re-applies the original commit, but with a bumped engine version that is purported to fix the `TimeoutException` issue.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by cbracken** [comment]
Supersedes #14690

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm

**Comment by tvolkert** [comment]
Build redness is a Travis timeout, so merging on red.

**Pull request merged**
