### PR TITLE
Add the missing canvas.save and canvas.restore

### LINKED ISSUE #18708: drawer's elements are not painted after an element with a 'Chip' trailing is painted
## Steps to Reproduce

gist: https://gist.github.com/ebeem/0c2bb55565f93324cf48f53a7bcaeafe

note: some elements other than Chip might cause the same behavior
Texts do not cause this behavior and work normally

caused by the PR #18616 
@liyuqian 

## Logs

```
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.5.6-pre.51, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[✓] Connected devices (1 available)

• No issues found!
flutter upgrade  28.66s user 8.47s system 6% cpu 8:52.48 total

```

### PR DESCRIPTION
**Pull request by liyuqian**
This should fix https://github.com/flutter/flutter/issues/18708 and https://github.com/flutter/flutter/issues/18713

### CODE REVIEW

**Comment by liyuqian** [comment]
CC @ebeem

**Comment by liyuqian** [comment]
CC @andreidiaconu : please let me know if this fixes your issue https://github.com/flutter/flutter/issues/18713

**Review by chinmaygarde — COMMENTED** [review]
Lets use `SkAutoCanvasRestore` instead.

**Review by chinmaygarde — APPROVED** [review]
Nit about the RAII wrapper, but otherwise LGTM.

**Comment by chinmaygarde** [comment]
Oops. That was Dart. Don't mind me :D

**Pull request merged**
