### PR TITLE
#126241 Add ChipSet

### LINKED ISSUE #126241: Add ChipSet
See PR: #126308

See the live sample [here](https://dartpad.dev/?id=cd233afb0bf718d4b8bc71cc3999b776)
image

From the Material Design website:

> Multiple chips should appear together in a group, whereas there should be no more than 3 buttons in a single arrangement.

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

The user needs to select zero or many items in a list.

Problem: no widget allows the user to select multiple items in a list.

Solution: display multiple [`FilterChip`](https://api.flutter.dev/flutter/material/FilterChip-class.html) widgets from left to right, top to bottom, and bind the results to a list.

### Proposal

image

The original sketch code was removed....

See the proposed widget here:
#126308

### PR DESCRIPTION
**Pull request by MelbourneDeveloper**
This pull request introduces a new widget, `ChipSet`, to the Flutter framework, providing an efficient and flexible way to handle multiple chips in a group, as the Material Design specification recommends. The `ChipSet` widget adheres to the guideline that suggests utilizing chips in groups rather than displaying them individually in a single arrangement. By incorporating the `ChipSet` widget, developers can easily create groups of chips, manage their selection state, and customize the appearance and layout of each chip. This enhancement to the framework simplifies the implementation process, enabling developers to build more user-friendly apps that align with the Material Design principles.

> Multiple chips should appear together in a group, whereas there should be no more than 3 buttons in a single arrangement.

https://m3.material.io/components/chips/guidelines

Chips are common components in modern apps.

Original issue and discussion: #126241

See the live sample [here](https://dartpad.dev/?id=cd233afb0bf718d4b8bc71cc3999b776)
image

## Pre-launch Checklist

- [*] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [*] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [*] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [*] I signed the [CLA].
- [*] I listed at least one issue that this PR fixes in the description above.
- [*] I updated/added relevant documentation (doc comments with `///`).
- [*] I added new tests to check the change I am making, or this PR is [test-exempt].
- [*] All existing and new tests are passing.

Thanks to @SEGVeenstra for the name

## Usage

This displays a set of `FilterChip`s for Red, Blue Green, which can be selected.

```dart
import 'package:chip_set/chip_set.dart';
import 'package:flutter/material.dart';

final colors = [
  const Color.fromARGB(255, 255, 0, 0),
  const Color.fromARGB(255, 0, 255, 0),
  const Color.fromARGB(255, 0, 0, 255),
];

var selectedItems = <Color>{};

String colorToText(Color color) {
  if (color.blue == 255) return 'Blue';
  if (color.red == 255) {
    return 'Red';
  } else {
    return 'Green';
  }
}

void main() {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true),
      home: const Scaffold(
        body: ChipSets(),
      ),
    ),
  );
}

class ChipSets extends StatefulWidget {
  const ChipSets({
    super.key,
  });

  @override
  State<ChipSets> createState() => _ChipSetsState();
}

class _ChipSetsState extends State<ChipSets> {
  @override
  Widget build(BuildContext context) => Align(
        alignment: Alignment.topLeft,
        child: _chipSet(),
      );

  ChipSet<Color> _chipSet() => ChipSet(
      constraints: const BoxConstraints(
        maxWidth: 200,
        minWidth: 200,
      ),
      //direction: Axis.vertical,
      spacing: 8,
      runSpacing: 8,
      chipBuilder: _chipBuilder,
      items: colors,
      isSelected: (item) => selectedItems.contains(item),
      onSelected: _onSelected);

  FilterChip _chipBuilder(
    BuildContext context,
    Color color,
    bool selected,
    void Function(bool value) onSelected,
  ) =>
      FilterChip(
        selectedColor: color,
        backgroundColor: color.withOpacity(.5),
        selected: selected,
        label: Text(colorToText(color)),
        onSelected: onSelected,
      );

  void _onSelected(
    Color item,
    bool value,
  ) =>
      setState(
        () {
          if (value) {
            if (!selectedItems.contains(item)) {
              selectedItems.add(item);
            }
          } else {
            if (selectedItems.contains(item)) {
              selectedItems.remove(item);
            }
          }
        },
      );
}
```

Fixes #126241

### CODE REVIEW

**Comment by MelbourneDeveloper** [comment]
Hi @huycozy. This is the PR for the issue #126241

**Comment by MelbourneDeveloper** [comment]
I'm having trouble figuring out the issue with the Linux analyzer. Does anyone know what is going wrong here?

https://github.com/flutter/flutter/pull/126308/checks?check_run_id=13333338346

**Comment by SEGVeenstra** [comment]
I think it's a good start, but I have some more suggestions:
- What if we'd add multiple (named) constructors similar to ListView that allows for specifying either a list of children, OR a builder?
- Add a `layout-mode` or something that you can set to determine how the chips would be shown. I think the guidelines talk about either showing chips in either a horizontal scrollable list, or a Wrap. (https://m3.material.io/components/chips/guidelines#ce5b21e5-27cf-4144-a222-34cfc3415fcf)

Maybe I'm wrong, but I thought your first intention was to have a widget that gave you a way to handle a set of filters.
In that case, wouldn't a `onChange(List<T> selectedItems)` be more helpful because you don't have to manage the set of selected items yourself.

**Comment by bernaferrari** [comment]
This is the discussion: https://discord.com/channels/608014603317936148/608018585025118217/1105226216346230924

**Comment by MelbourneDeveloper** [comment]
Thanks @bernaferrari 

I can't seem to open the discussion. Is it possible that it's in a channel that only the internal team have access to? 

@Hixie 

I hear you. It currently has 100% test coverage and there is documentation for all members, but there's probably work to do to bring it 100% into line with Flutter's style. I will do whatever it takes to make that happen, IF there is a general feeling that this widget might be worthwhile. 

My feeling from building the widget and reading the MD spec is that it slots in, fills a hole and offers a way to achieve sets of chips in a uniform way. I will continue to polish it until it does the rounds. 

Thanks

**Comment by MelbourneDeveloper** [comment]
@bernaferrari how do I get onto this channel? I tried opening the link you sent but I don't have access

**Comment by bernaferrari** [comment]
Are you here? https://github.com/flutter/flutter/wiki/Chat

**Comment by MelbourneDeveloper** [comment]
> Are you here? https://github.com/flutter/flutter/wiki/Chat

@bernaferrari I had no idea about this discord server...

Is there a separate server specifically for the flutter team?

I cannot see the hacker channel. This is all I see

image

**Comment by bernaferrari** [comment]
It is public. You just need to agree to the rules. The discussion went there because someone opened a PR similar to this one and asked for a test exemption there.

**Comment by MelbourneDeveloper** [comment]
@bernaferrari I did agree to the rules, I'm seeing this

image

**Comment by bernaferrari** [comment]
Did you read the welcome channel?

**Comment by MelbourneDeveloper** [comment]
@bernaferrari thanks. I'm finally in. 

I can see what happened here. This conversation has nothing to do with me. Another guy jumped in when I posted the original issue and created a PR with no tests. He then brought the topic up on discord and that's why there has been discussion unrelated to my original issue. 



My PR does have complete test coverage

**Comment by bernaferrari** [comment]
Yeah, you can comment there. But the package idea remains.

**Comment by HansMuller** [comment]
As noted in https://github.com/flutter/flutter/issues/126241#issuecomment-1542579287, this utility would be best shared as either a separate package or an API doc example.

**Comment by TahaTesser** [comment]
> As noted in [#126241 (comment)](https://github.com/flutter/flutter/issues/126241#issuecomment-1542579287), this utility would be best shared as either a separate package or an API doc example.

Given the suggestion above 2 weeks ago. I feel safe to close this PR.

**Pull request closed without merging**
