### PR TITLE
Revert "Update PopupMenuButton widget"

### LINKED ISSUE #80699: PopupMenu trails behind windows resizing
https://github.com/flutter/flutter/pull/80420#pullrequestreview-638545091 fixes an issue where `PopupMenu`s does not correctly reposition itself after the window is resized. However, it would introduce a new problem where the menu "trails" behind the resizing window: 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Home(),
  ));
}

class Home extends StatelessWidget {
  const Home({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: PopupMenuButton(
          itemBuilder: (context) => ["apple", "orange",]
              .map((e) => PopupMenuItem(
                    child: Text(e),
                  ))
              .toList(),
          child: Container(
            height: 200,
            width: 300,
            color: Colors.green,
          ),
        ),
      ),
    );
  }
}
```

https://user-images.githubusercontent.com/27032613/114826354-fce1b500-9df9-11eb-90b4-9186d8167381.mov

I wonder if there is a way to avoid this issue.

### PR DESCRIPTION
**Pull request by shihaohong**
Reverts flutter/flutter#80420. Basically we want to avoid the use of [addPostFrameCallback](https://master-api.flutter.dev/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html) as a solution for this as we want to avoid its use if at all possible.

Closes https://github.com/flutter/flutter/issues/80699

I spoke to @HansMuller and we think it might be best to approach this one of two ways:
1) find a solution that doesn't use [addPostFrameCallback](https://master-api.flutter.dev/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html)
2) (could also be the temporary solution until we find an answer to 1) have the menu close whenever any resizing of the window happens

### CODE REVIEW

**Review by xu-baolin — APPROVED** [review]
LGTM
Thanks 😄

**Comment by xu-baolin** [comment]
I have just tested this behavior on Android native.
https://github.com/flutter/flutter/pull/80420#discussion_r617126995

**Comment by xu-baolin** [comment]
In my opinion, Solution 2 has two problems,
1. The implementation is inconsistent with the web and Android native;
2. As a temporary plan, it may be a breaking change when returning to plan 1;

**Comment by xu-baolin** [comment]
I agree with the first solution. 
The current problem is that if you want to refresh the button and menu in the same frame, the position of the menu depends on the position of the button, but the current Flutter architecture does not allow access to non-parent-child relationships' size during the layout phase. I mentioned this in the previous comment. https://github.com/flutter/flutter/pull/80420#issuecomment-820169178

**Comment by HansMuller** [comment]
Flutter's (mostly) one-pass layout limitation, that a parent widget can't know it's descendant's size at build time, has been cropping up more often lately. There's no easy way around the problem.

**Comment by xu-baolin** [comment]
I just took a look at the behavior definition of the `DropdownButton`, which is very interesting. It was previously dismissed when the size changed, but it was rolled back by this patch. #42482(which is @shihaohong reviewed : ) )
The functions of `PopupMenuButton` and `DropdownButton` are very similar, but they have different behavior definitions. I think it's time for us to unify their behaviors.
CC @HansMuller @shihaohong

**Comment by shihaohong** [comment]
Yeah, that's also pretty tricky because we definitely do not want the keyboard closing to cause the dropdown menu to close when tapped on after having the keyboard dismissed (like with text fields) as well. We would somehow need to differentiate between the keyboard closing and the window resizing. 

Maybe we can query if the Flutter app's target platform is web/desktop and have the window resizing only close the dropdown in those cases, since there's no virtual keyboard? WDYT @HansMuller

**Pull request merged**
