### PR TITLE
Exact port of update_dart_sdk.sh to PowerShell

### PR DESCRIPTION
**Pull request by bbalet**
Exact port of bin/cache/update_dart_sdk.sh to PowerShell
Doesn't rely on any 3rd party tools, it's in pure PowerShell / .net 2.0.

### CODE REVIEW

**Comment by Hixie** [comment]
What ends up calling thing script? This seems like a necessary (and useful) building block, but I'm hesitant to suggest we check it in without more infrastructure (in particular testing) because otherwise it's just going to bitrot.

**Comment by bbalet** [comment]
I've tried to compile the snapshotter - see #138 , but I'm stuck by dependencies to mojom tools which - as far as I understand - doesn't support Windows either. So I guess there's no hurry to merge this script.

**Comment by eseidelGoogle** [comment]
Our BUILD.gn files used to support Windows, but we likely removed that a while back, in part by moving off of base/.  It's also possible that the GN build for Windows required some GYP (the build system before GN) files to function.  It's definitely possible to get that all working again, but will take a concerted effort.  My team intends to do this (and is happy to support you in doing so), we just don't have it on our roadmap for this quarter.

**Comment by Hixie** [comment]
@bbalet Cool, ok. I'm going to close this PR, but please don't take that as disinterest in supporting Windows, it's just that it would bitrot if we don't test it and we want to make sure we don't have bitrotting code since it makes people skeptical about the quality of the rest of the code. If there's anything we can do to help let us know.

**Pull request closed without merging**
