### PR TITLE
Roll engine to 893425d96046e413e643d5de380dfaa2cc5725ed

### PR DESCRIPTION
**Pull request by tonygentilcore**
This picks up a change which causes ChildViews to jank instead of flicker during resize.

### CODE REVIEW

**Comment by abarth** [comment]
Looks like you might have posted your patch while @Hixie 's test failure was in.  Retrying Travis.

**Comment by abarth** [comment]
Actually, Travis would just retry from the exact same git hash you'd need to post a new patch with a new base rev to get a new result from Travis.  I've just merged your patch.  We should just keep an eye on the master branch on Travis to make sure it lands cleanly.

**Comment by abarth** [comment]
Specifically https://travis-ci.org/flutter/flutter/builds/120777974

**Comment by tonygentilcore** [comment]
It passed

**Comment by abarth** [comment]
\o/

**Pull request merged**
