### PR TITLE
Fix line-dependent tests for formatting

### PR DESCRIPTION
**Pull request by goderbauer**
These tests are dependent on line numbers. This formats them and updates the line number to take them off the critical path.

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
The analyzer is le sad, - looks like some test skips in widget_inspector_test.dart

**Comment by goderbauer** [comment]
Yeah, looks like we will have to adjust the script that checks for the skip reason first before this can land :(

**Comment by goderbauer** [comment]
`Linux analyze` is happy now. :)

**Review by Piinks — APPROVED** [review]
LGTM

**Pull request merged**
