### PR TITLE
Reland  "Clipping if only one character text overflows"

### PR DESCRIPTION
**Pull request by xu-baolin**
Do not merge before @justinmc LGTMing.

### CODE REVIEW

**Comment by xu-baolin** [comment]
@justinmc Thanks very much for investigating the G test.

**Comment by goderbauer** [comment]
(triage) @justinmc @xu-baolin Any updates on this one?

**Comment by justinmc** [comment]
Sorry, I've triggered the Google tests on this, but the new approach looks good.  I'll check in on the Google tests tomorrow.

**Comment by justinmc** [comment]
Looks like the Google tests never ran.  I'm trying to figure out how to get that check to show up here...

**Review by justinmc — APPROVED** [review]
I'm under the impression that Google tests won't run until the PR has been approved, so I'm approving this for that reason, but it should not be merged yet!

**Comment by justinmc** [comment]
@xu-baolin I'm still struggling to get the Google tests to run... Can you rebase this onto master so that we get a different commit SHA?

**Comment by xu-baolin** [comment]
> @xu-baolin I'm still struggling to get the Google tests to run... Can you rebase this onto master so that we get a different commit SHA?

Done
Thanks a lot

**Comment by goderbauer** [comment]
Although the status was not reported back to github, it looks like the tests finished running. There are some failures, but they look very minor. @justinmc WDYT?

**Pull request merged**
