### PR TITLE
Expose the history getter for NavigatorState 

### PR DESCRIPTION
**Pull request by kangwang1988**
This commit add history getter for NavigatorState so that developers can have more control of the navigation history. 
For UINavigationController in iOS, push, pop and popToViewcontroller, popToRoot and viewControllers(getter for navigation stack) are enough for developers. 
If the history can be fetched, codes related could be more flexible when processing the navigation stack.

### CODE REVIEW

**Comment by zoechi** [comment]
Is it safe to modify the returned list or should it return a copy or https://api.dartlang.org/stable/2.0.0/dart-collection/UnmodifiableListView-class.html ?

**Comment by kangwang1988** [comment]
@zoechi 
Thanks for your advice. I've made the getter return an immutable copy.

**Comment by rrousselGit** [comment]
I don't think this should be done within NavigatorState.

Instead, it should be on RouteObserver. Something like an `onHistoryChanged` which receives the whole history as parameters.

`Navigator.of(context)` doesn't have internally an InheritedWidget, so if the historic were to change dependents wouldn't be notified.

**Comment by Hixie** [comment]
This also wouldn't handle things like the local history feature correctly.

I think the Router widget in https://github.com/Hixie/flutter/tree/router is probably a better approach to this (unfortunately I'm way behind on working on this).

**Comment by goderbauer** [comment]
Based on @Hixie's comment above and since there hasn't been any activity in a while I am closing this PR.

**Comment by SerggioC** [comment]
Why is this still not a thing??
Why should we keep a stack of the routes if there is already one internally? Just make it public. thanks

**Pull request closed without merging**
