### PR TITLE
Some cleanup in the heroes realm.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by HansMuller** [comment]
Another potentially worthwhile cleanup would be to privatize more of the API.  I think only Hero and HeroController (and CreateRectTween) need to be public.  Perhaps HeroHandle, HeroParty, HeroState, Hero.of() could be private.

**Comment by Hixie** [comment]
@HansMuller I privatised a bunch of the API. PTAL.

**Comment by HansMuller** [comment]
_LGTM

**Comment by HansMuller** [comment]
_LGTM

**Pull request merged**
