### PR TITLE
Fix the transforms for horizontal glows.

### LINKED ISSUE #8053: OverscrollIndiciator runs away from finger in horizontal mode
Overscroll a PageView.  Now move your finger up.  The overscroll indicator moves down.  It's backwards.

/cc @Hixie

### PR DESCRIPTION
**Pull request by Hixie**
Also, make all painters have a toString by default.

Not really sure how to test this.

Fixes https://github.com/flutter/flutter/issues/8053

### CODE REVIEW

**Comment by abarth** [comment]
No test partner?

**Comment by abarth** [comment]
You broke a test, so you have that going for you.  :)

**Comment by Hixie** [comment]
Ok fine it "has a test" now.

**Comment by Hixie** [comment]
(Not really.)

**Comment by Hixie** [comment]
(Happy to add an actual test if you have any idea how to do so. There's no point having an over-fitted display list test, though, as the previous test demonstrates. We really need some sort of reference test to do this.)

**Comment by abarth** [comment]
LGTM

**Pull request merged**
