### PR TITLE
Upgrade packages

### PR DESCRIPTION
**Pull request by GaryQian**
Rolls in upgrades to `path_provider_linux` to fix analyzer.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
It seems like every time one of these plugin libraries gets publish it breaks the build 🙃

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
I would just land it now. Its probably safe

**Comment by GaryQian** [comment]
Alright sounds good!

**Pull request merged**
