### PR TITLE
Use DiagnosticableMixin instead of Diagnosticable for some conditionals.

### LINKED ISSUE #49647: extends Diagnosticable != with DiagnosticableMixin
In many places, Diagnosticable is refered to directly instead of the mixin itself. This has severe implications when it comes to class hierarchies, because classes that use the mixin are incompatible with the Diagnosticable subsystem and will instead cause TypeErrors.

As a suggested fix:

1. Add `implements Diagnosticable` to `DiagnosticableMixin`
2. Change `Diagnosticable` to stop using `DiagnosticableMixin` (and treat it as an interface, copy the signatures from the methods exposed from `DiagnosticableMixin`)
3. Make all subclasses use `with DiagnosticableMixin` instead of `extends Diagnosticable`

This is, unfortunately, a breaking change for anyone using `extends Diagnosticable`.

Right now, the Flutter Inspector stops working when a `ShortcutManager` is specified in a `Shortcuts` widget.

cc @gspencergoog @goderbauer

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description
As the code is right now, if you try and print diagnostics for a `Shortcuts` widget that has a `manager` set (a `ShortcutManager`), it will fail at runtime.  This code:
```dart
import 'package:flutter/widgets.dart';

void main() {
  try {
    print(Shortcuts(shortcuts: {}, manager: ShortcutManager()));
  } catch (ex, stack) {
    print(ex);
    print(stack);
  }
}
```

will fail with this exception:
```
flutter: type 'ShortcutManager' is not a subtype of type 'Diagnosticable' in type cast
flutter: #0      DiagnosticableMixin.toDiagnosticsNode (package:flutter/src/foundation/diagnostics.dart:3113:19)
#1      DiagnosticableMixin.toString.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:3095:20)
#2      DiagnosticableMixin.toString (package:flutter/src/foundation/diagnostics.dart:3097:6)
#3      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2698:61)
#4      DiagnosticsProperty.toDescription (package:flutter/src/foundation/diagnostics.dart:2712:21)
#5      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1169:31)
#6      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1279:39)
#7      DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:1709:7)
#8      DiagnosticsNode.toString (package:flutter/src/foundation/diagnostics.dart:1631:14)
#9      DiagnosticableMixin.toString.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:3095:78)
#10     DiagnosticableMixin.toString (package:flutter/src/foundation/diagnostics.dart:3097:6)
#11     _StringBase._interpolateSingle (dart:core-patch/string_patch.dart:823:17)
#12     print (dart:core/print.dart:11:26)
#13     main (package:focus_samples/focus_traversal_group.dart:5:5)
...
```

The reasons for this are explained in https://github.com/flutter/flutter/issues/49647#issuecomment-579886510

This PR fixes this by changing `DiagnosticableMixin.toDiagnosticsNode` and other things to accept `DiagnosticableMixin` instead of requiring `Diagnosticable`.

Eventually, after making some changes to the linter and some other external repos, we can deprecate and them remove `Diagnosticable` entirely and just have the mixin.

## Related Issues
- Fixes https://github.com/flutter/flutter/issues/49647

## Tests

- Updated `diagnostics_test.dart`, although no functionality changed.

## Breaking Change

- [X] No, this is not a breaking change.

### CODE REVIEW

**Comment by gspencergoog** [comment]
Actually, after doing the "full" fix here, it occurred to me that there is a simpler fix to the original problem, although it still doesn't fix the structural issues with the way `Diagnosticable` is set up.

We can just change `DiagnosticableNode` to be:
```dart
class DiagnosticableNode<T extends DiagnosticableMixin> extends DiagnosticsNode {
```

and change `toDiagnosticsNode` to use `DiagnosticableMixin` instead: 
```dart
  DiagnosticsNode toDiagnosticsNode({ String name, DiagnosticsTreeStyle style }) {
    return DiagnosticableNode<DiagnosticableMixin>(
      name: name,
      value: this,
      style: style,
    );
  }
```

That wouldn't be a breaking change, and nothing gets deprecated. It does leave a pitfall for people that compare things to `Diagnosticable` instead of `DiagnosticableMixin`, so it's not as desirable in that sense.

**Review by ds84182 — APPROVED** [review]
LGTM

Later on, would it be useful to switch the names? With generalized typedefs I think you'd be able to do

```dart
mixin Diagnosticable {...}

@Deprecated(...)
typedef DiagnosticableMixin = Diagnosticable;
```

to move everyone over to the new name.

**Comment by gspencergoog** [comment]
I don't think I'd switch the names back, simply because Flutter has a convention of naming mixins with the suffix "Mixin", and `mixin Diagnosticable` wouldn't follow that convention.

What would you think of doing the simpler change I mentioned in https://github.com/flutter/flutter/pull/49726#issuecomment-579947671?

**Comment by ds84182** [comment]
Gotcha. Having them both around seems like a potential foot-gun, so I think
it's better to have one way of adding DiagnosticableMixin to a class.

**Comment by gspencergoog** [comment]
OK, I think this is the right change eventually, but in order to be able to put in preemptive changes to other repos to make the transition smoother, I think I'll do the simpler fix first, and then convert other repos to use `DiagnosticableMixin` ahead of this change that switches all widgets to not be `Diagnosticable`, because any checks for `is Diagnosticable` would fail.

Things like the dart linter will stop reporting lints for `diagnostic_describe_all_properties` on classes that switch to the mixin, and the dart devtools needs changes too. If I don't make the fix first, then it would break things to switch non-Flutter-repo classes to use the mixin instead of extending `Diagnosticable`. They would fail in the same way as ShortcutManager when they tried to be converted to a `DiagnosticNode`.

Once I commit the simple fix, then I can switch other classes without any breakage, so that when I commit this change that changes the type of the widgets, nothing will stop working.

I've reverted the changes that switch widgets to use the mixin, and added `implements Diagnosticable` to those few classes that were just using the mixin, as well as switching anything that was testing `is Diagnosticable` or template args that assert `<T extends Diagnosticable>` to use the mixin instead, since that only broadens the match.

**Pull request merged**
