### PR TITLE
Move to real generic method syntax

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
With this patch, the `flutter` tool crashes on startup for me:

```
Dumping native stack trace for thread 4f57
  [0x000000000078e7f1] dart::TypeParameter::set_parameterized_class(dart::Class const&) const
  [0x000000000078e7f1] dart::TypeParameter::set_parameterized_class(dart::Class const&) const
  [0x00000000009605c8] dart::TypeParameter::ReadFrom(dart::SnapshotReader*, long, long, dart::Snapshot::Kind, bool)
  [0x00000000008c89a7] dart::SnapshotReader::ReadObjectImpl(long, bool, long, long)
  [0x00000000009609b8] dart::TypeArguments::ReadFrom(dart::SnapshotReader*, long, long, dart::Snapshot::Kind, bool)
  [0x00000000008c84d6] dart::SnapshotReader::ReadObjectImpl(long, bool, long, long)
  [0x0000000000964cac] dart::Function::ReadFrom(dart::SnapshotReader*, long, long, dart::Snapshot::Kind, bool)
  [0x00000000008c851a] dart::SnapshotReader::ReadObjectImpl(long, bool, long, long)
  [0x00000000008cb8bd] dart::SnapshotReader::ArrayReadFrom(long, dart::Array const&, long, long)
  [0x0000000000963438] dart::Array::ReadFrom(dart::SnapshotReader*, long, long, dart::Snapshot::Kind, bool)
  [0x00000000008c8cff] dart::SnapshotReader::ReadObjectImpl(long, bool, long, long)
  [0x00000000008cb4d7] dart::SnapshotReader::ReadObject()
  [0x00000000008cb628] dart::SnapshotReader::ReadScriptSnapshot()
-- End of DumpStackTrace
/home/ianh/dev/flutter/bin/flutter: line 53: 20311 Aborted                 (core dumped) "$DART" "$SNAPSHOT_PATH" "$@"
```

**Comment by abarth** [comment]
I presume you're going to file a bug against the SDK for the crash?  Otherwise, looks amazing.  :)

**Comment by Hixie** [comment]
I was waiting to see if it would reproduce on Travis. :-)

**Comment by eseidelGoogle** [comment]
Did you do this by hand?  Regexp?  some fancy dart upgrade tool?

**Comment by Hixie** [comment]
I used a find/grep/xargs/emacsclient combo to bring up each affected file, then emacs search-and-replace to fix each file in turn. There were few enough that it didn't really justify writing a program to do it automatically.

**Comment by Hixie** [comment]
BTW I filed the SDK issue as https://github.com/dart-lang/sdk/issues/28072

**Comment by Hixie** [comment]
A possible fix for the SDK issue is in, we just need a dart roll then an engine roll now.

**Comment by sethladd** [comment]
Ping. Did we roll Dart enough?

cc @pq

**Comment by Hixie** [comment]
We're currently blocked on engine issues.

**Comment by eseidelGoogle** [comment]
I believe @chinmaygarde may have been trying to roll the engine yesterday?

**Comment by mravn-google** [comment]
Does "blocked on engine issues" explain why my flutter app containing a static generic method works fine, but adding a top-level generic function makes the same app crash on Android (with zero error message from flutter run)?

```
$ flutter doctor
[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/mravn/flutter
    • Framework revision a0666f330e (5 hours ago), 2017-01-10 21:33:04
    • Engine revision f13518d7e7
    • Tools Dart version 1.21.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.1)
    • Android SDK at /usr/local/google/home/mravn/Android/Sdk
    • Platform android-24, build-tools 24.0.1
    • OpenJDK Runtime Environment (build 1.8.0_102-google-v7-137518472-137512069)

[✓] IntelliJ IDEA Community Edition (version 2016.1)
    • Dart plugin version 145.971.7
    • Flutter plugin version 0.1.1

[✓] IntelliJ IDEA Community Edition (version 2016.2)
    • Dart plugin version 162.2485
    • Flutter plugin version 0.1.3

[-] IntelliJ IDEA Ultimate Edition (version 2016.2)
    • Dart plugin version 162.2924
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • For information about managing plugins, see
      https://www.jetbrains.com/help/idea/2016.2/managing-plugins.html

[✓] Connected devices
    • Nexus 5X • 00bff34682e4b2ab • android-arm • Android 7.1.1 (API 25)
```

**Comment by Hixie** [comment]
Yes, that's very likely related. We are working on it.

**Comment by Hixie** [comment]
I plan on getting back to this after I've landed the scrolling stuff, since I used some of the old syntax in the scrolling stuff.

**Comment by abarth** [comment]
LGTM

**Pull request merged**
