### PR TITLE
Make FlexibleSpaceBar title padding configurable

### LINKED ISSUE #9212: Gallery SliverAppBar Text better centered under iOS theme than Android.
Hi,

Seems to be TextAlign issue with SliverAppBar from home.dart in flutter_gallery example. The Android text is missing when the iOS theme is applied.

If i input 'title: new Text('Animate Slowly   ----real slowly'), ' in line 173 of home.dart then it's enough to fill up the page width under the iOS theme but it's clearly not visible when under Android theme. The text is not centered and characters are missing.

I'm not sure if I could adjust this line with something like CenterAlign, whether it's related to FlexibleSpaceBar, or other theme files. I don't have an iphone to check.

Here are some shots with the theme changing the text alignment;

Android theme home page
flutter android home-screenshot from 2017-04-05 11-22-44

iOS theme home page
flutter ios home-screenshot from 2017-04-05 11-23-33

Android drawer theme selected
flutter androiddrawer-screenshot from 2017-04-05 11-29-44

iOS drawer theme selected
flutter ios home-screenshot from 2017-04-05 11-30-23

### LINKED ISSUE #11951: Left aligned title for SlicerAppBar and FlexibleSpace
Hi!

I'm trying to implement a "Collapsing Toolbar", or the "Flexible space with image" scrolling technique from the Material Design spec, but I don't have a back button or navigation drawer. So I would like the title to be near the left edge, without any left padding/space. When I use the SliverAppBar and FlexibleSpace I can only get it to display the title with a considerable left padding, which when collapsed gives space to a back button or navigation drawer (hamburger) icon. This is not the behaviour I want, I would like to do something similar to the Android Contacts app:

example1

Is this possible (without implementing my new SicerAppBar and FlexibleSpace class from scratch), and if so, how to do it?

### LINKED ISSUE #23864: About the value of FlexibleSpaceBar title bottom padding.
I want to make a search bar in FlexibleSpaceBar title, and let it show a large search bar or scroll to a small search bar. but I found that the FlexibleSpaceBar title has a padding bottom for 16.0. 

Is there a way to set the padding bottom to 0.0? Because I need the search bar occupy the all heights.

```dart
class _FlexibleSpaceBarState extends State<FlexibleSpaceBar> {
  bool _getEffectiveCenterTitle(ThemeData theme) {
    if (widget.centerTitle != null)
      return widget.centerTitle;
    assert(theme.platform != null);
    switch (theme.platform) {
      case TargetPlatform.android:
      case TargetPlatform.fuchsia:
        return false;
      case TargetPlatform.iOS:
        return true;
    }
    return null;
  }

  Alignment _getTitleAlignment(bool effectiveCenterTitle) {
    if (effectiveCenterTitle)
      return Alignment.bottomCenter;
    final TextDirection textDirection = Directionality.of(context);
    assert(textDirection != null);
    switch (textDirection) {
      case TextDirection.rtl:
        return Alignment.bottomRight;
      case TextDirection.ltr:
        return Alignment.bottomLeft;
    }
    return null;
  }

  double _getCollapsePadding(double t, _FlexibleSpaceBarSettings settings) {
    switch (widget.collapseMode) {
      case CollapseMode.pin:
        return -(settings.maxExtent - settings.currentExtent);
      case CollapseMode.none:
        return 0.0;
      case CollapseMode.parallax:
        final double deltaExtent = settings.maxExtent - settings.minExtent;
        return -Tween<double>(begin: 0.0, end: deltaExtent / 4.0).transform(t);
    }
    return null;
  }

  @override
  Widget build(BuildContext context) {
    final _FlexibleSpaceBarSettings settings = context.inheritFromWidgetOfExactType(_FlexibleSpaceBarSettings);
    assert(settings != null, 'A FlexibleSpaceBar must be wrapped in the widget returned by FlexibleSpaceBar.createSettings().');

    final List<Widget> children = <Widget>[];

    final double deltaExtent = settings.maxExtent - settings.minExtent;

    // 0.0 -> Expanded
    // 1.0 -> Collapsed to toolbar
    final double t = (1.0 - (settings.currentExtent - settings.minExtent) / deltaExtent).clamp(0.0, 1.0);

    // background image
    if (widget.background != null) {
      final double fadeStart = math.max(0.0, 1.0 - kToolbarHeight / deltaExtent);
      const double fadeEnd = 1.0;
      assert(fadeStart <= fadeEnd);
      final double opacity = 1.0 - Interval(fadeStart, fadeEnd).transform(t);
      if (opacity > 0.0) {
        children.add(Positioned(
          top: _getCollapsePadding(t, settings),
          left: 0.0,
          right: 0.0,
          height: settings.maxExtent,
          child: Opacity(
            opacity: opacity,
            child: widget.background
          )
        ));
      }
    }

    if (widget.title != null) {
      Widget title;
      switch (defaultTargetPlatform) {
        case TargetPlatform.iOS:
          title = widget.title;
          break;
        case TargetPlatform.fuchsia:
        case TargetPlatform.android:
          title = Semantics(
            namesRoute: true,
            child: widget.title,
          );
      }

      final ThemeData theme = Theme.of(context);
      final double opacity = settings.toolbarOpacity;
      if (opacity > 0.0) {
        TextStyle titleStyle = theme.primaryTextTheme.title;
        titleStyle = titleStyle.copyWith(
          color: titleStyle.color.withOpacity(opacity)
        );
        final bool effectiveCenterTitle = _getEffectiveCenterTitle(theme);
        final double scaleValue = Tween<double>(begin: 1.5, end: 1.0).transform(t);
        final Matrix4 scaleTransform = Matrix4.identity()
          ..scale(scaleValue, scaleValue, 1.0);
        final Alignment titleAlignment = _getTitleAlignment(effectiveCenterTitle);
        children.add(Container(
          padding: EdgeInsetsDirectional.only(
            start: effectiveCenterTitle ? 0.0 : 72.0,
            bottom: 16.0                                       // here is the bottom padding,
          ),
          child: Transform(
            alignment: titleAlignment,
            transform: scaleTransform,
            child: Align(
              alignment: titleAlignment,
              child: DefaultTextStyle(
                style: titleStyle,
                child: title,
              )
            )
          )
        ));
      }
    }

    return ClipRect(child: Stack(children: children));
  }
}
```
image

Thank you.

### PR DESCRIPTION
**Pull request by HansMuller**
An earlier version of these changes was contributed by @showang in #22548

Fixes https://github.com/flutter/flutter/issues/23864
Fixes https://github.com/flutter/flutter/issues/11951
Fixes https://github.com/flutter/flutter/issues/9212

### CODE REVIEW

**Comment by zoechi** [comment]
Does this fix #23864?
Others that look related #11951, #11954, #9212

**Comment by HansMuller** [comment]
@zoechi Thanks for looking up the related bugs, this PR does address 3 of them. I've updated the description.

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by jayasio** [comment]
When` titlePadding` is set to something like `EdgeInsetsDirectional.only(start: 16.0, bottom: 16.0)` and if the FlexibleSpaceBar has a leading widget, they just overlap. Is there a way to animate the title to it's place in the default `AppBar` layout?
Screenshot (30)
Screenshot (31)

**Comment by hardypatel30** [comment]
@jayasio  Found any solution? Even I am also facing the same issue.

**Comment by hardypatel30** [comment]
@jayasio   Can find answer  here.  

https://stackoverflow.com/questions/59243525/sliver-appbar-collapsing-toolbar-animate-title-from-left-to-center-in-flutter/59434248#59434248

**Pull request merged**
