### PR TITLE
Rev package:intl version

### PR DESCRIPTION
**Pull request by mosuem**

### CODE REVIEW

**Comment by mosuem** [comment]
See also https://github.com/dart-lang/intl/issues/522.

@thkim1011 @HansMuller

**Comment by goderbauer** [comment]
@mosuem This PR doesn't appear to change the intl version. Is it still relevant?

**Comment by oscarvaldes** [comment]
> @mosuem This PR doesn't appear to change the intl version. Is it still relevant?

I think we need to bump => https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml#L11 (also waiting on some Spanish abbreviation fixes in 0.18)

**Comment by mosuem** [comment]
Apparently running `flutter update-packages --force-upgrade` reverted my change to `packages/flutter_localizations/pubspec.yaml`. My intent was to rev the intl version there. 

Are you waiting for changes in `package:intl` @oscarvaldes ? Which issue are you referring to?

**Comment by mosuem** [comment]
Ah, I just saw #117163. Closing this PR.

**Pull request closed without merging**
