### PR TITLE
Reland 2: Make LiveTestWidgetsFlutterBinding work with setSurfaceSize and live tests

### PR DESCRIPTION
**Pull request by dkwingsmt**
Reland #86449

On top of the original PR, this PR stablized the golden tests with
```
LiveTestWidgetsFlutterBinding().framePolicy = LiveTestWidgetsFlutterBindingFramePolicy.onlyPumps;
```

And instead of `InkWell`s, it uses a simple `GestureRecognizer` to record taps.

The initial frame is also removed.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/86912

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/86912

**Comment by skia-gold** [comment]
Gold has detected about 6 new digest(s) on patchset 5.
View them at https://flutter-gold.skia.org/cl/github/86912

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 6.
View them at https://flutter-gold.skia.org/cl/github/86912

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 7.
View them at https://flutter-gold.skia.org/cl/github/86912

**Comment by dkwingsmt** [comment]
@Piinks I believe this PR's golden results should be stable, but still empty commits trigger untriaged changes. Is it expected?

**Comment by Piinks** [comment]
If you triage the images, and then push an empty commit and it presents more, than yeah, it's still making new images.

Once images are triaged for a PR, if they come up again in a new commit on the PR, Gold won't need you to triage them if they are are the same images as before.

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 8.
View them at https://flutter-gold.skia.org/cl/github/86912

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 10.
View them at https://flutter-gold.skia.org/cl/github/86912

**Comment by dkwingsmt** [comment]
@Piinks Ok this time the empty commit triggers notification but no untriaged digests. I think this means it's stable.

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 11.
View them at https://flutter-gold.skia.org/cl/github/86912

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 12.
View them at https://flutter-gold.skia.org/cl/github/86912

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
