### PR TITLE
Move all Linux Moto G4 tests to mokey in staging

### PR DESCRIPTION
**Pull request by zanderso**
Next step of https://github.com/flutter/flutter/issues/148085

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
RSLGTM

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
FYI, Gray just discovered: https://github.com/flutter/flutter/issues/151615

It will be interesting to see what happens post-submit of this change.

**Comment by zanderso** [comment]
Reason for revert: Overeager cleanup of unused device spec.

**Comment by christopherfujino** [comment]
> Reason for revert: Overeager cleanup of unused device spec.

FYI, this is what broke: https://flutter.googlesource.com/infra/+/refs/heads/main/config/flutter_config.star#73

Which makes me think to actually make this change, we will need to edit that file?

**Comment by zanderso** [comment]
I can reland without the deletion here https://github.com/flutter/flutter/pull/151608/files#diff-9e73abde9fff445f31e5928e80d2d3f88847e02fd8f76d46f66f147fdc82786dL69, then edit the star file, then reland the deletion.

**Comment by christopherfujino** [comment]
> I can reland without the deletion here https://github.com/flutter/flutter/pull/151608/files#diff-9e73abde9fff445f31e5928e80d2d3f88847e02fd8f76d46f66f147fdc82786dL69, then edit the star file, then reland the deletion.

Yeah, that makes sense

**Comment by zanderso** [comment]
Reland is here https://github.com/flutter/flutter/pull/151654

**Pull request merged**
