### PR TITLE
AnimationController should dispatch creation in constructor. [prod-leak-fix]

### LINKED ISSUE #134838: Memory Leak: _MergeableMaterialState does not dispose AnimationController
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

PR which marks this leak: https://github.com/flutter/flutter/pull/134839.

### Steps to reproduce

1. Add `leak-tracker` instrumentation to the `AnimationController`:

Constructor:
```dart
  AnimationController({
    double? value,
    this.duration,
    this.reverseDuration,
    this.debugLabel,
    this.lowerBound = 0.0,
    this.upperBound = 1.0,
    this.animationBehavior = AnimationBehavior.normal,
    required TickerProvider vsync,
  }) : assert(upperBound >= lowerBound),
       _direction = _AnimationDirection.forward {
    if (kFlutterMemoryAllocationsEnabled) {
      MemoryAllocations.instance.dispatchObjectCreated(
        library: 'package:flutter/animation.dart',
        className: '$AnimationController',
        object: this,
      );
    }
    _ticker = vsync.createTicker(_tick);
    _internalSetValue(value ?? lowerBound);
  }
```

`dispose()` method:

```dart
  @override
  void dispose() {
    assert(() {
      if (_ticker == null) {
        throw FlutterError.fromParts(<DiagnosticsNode>[
          ErrorSummary('AnimationController.dispose() called more than once.'),
          ErrorDescription('A given $runtimeType cannot be disposed more than once.\n'),
          DiagnosticsProperty<AnimationController>(
            'The following $runtimeType object was disposed multiple times',
            this,
            style: DiagnosticsTreeStyle.errorProperty,
          ),
        ]);
      }
      return true;
    }());
    if (kFlutterMemoryAllocationsEnabled) {
      MemoryAllocations.instance.dispatchObjectDisposed(object: this);
    }
    _ticker!.dispose();
    _ticker = null;
    clearStatusListeners();
    clearListeners();
    super.dispose();
  }
```

2. Test to reveal the leak:

```dart
testWidgetsWithLeakTracking('_MergeableMaterialState leak', (WidgetTester tester) async {
  await tester.pumpWidget(
    const MaterialApp(
      home: Scaffold(
        body: SingleChildScrollView(
          child: MergeableMaterial(
            children: <MergeableMaterialItem>[
              MaterialSlice(
                key: ValueKey<String>('A'),
                child: SizedBox(
                  width: 100.0,
                  height: 100.0,
                ),
              ),
              MaterialGap(
                key: ValueKey<String>('-'),
              ),
              MaterialSlice(
                key: ValueKey<String>('B'),
                child: SizedBox(
                  width: 100.0,
                  height: 100.0,
                ),
              ),
            ],
          ),
        ),
      ),
    ),
  );

  await tester.pumpWidget(
    const MaterialApp(
      home: Scaffold(
        body: SingleChildScrollView(
          child: MergeableMaterial(
            children: <MergeableMaterialItem>[
              MaterialSlice(
                key: ValueKey<String>('A'),
                child: SizedBox(
                  width: 100.0,
                  height: 100.0,
                ),
              ),
            ],
          ),
        ),
      ),
    ),
  );
}, leakTrackingTestConfig: LeakTrackingTestConfig.debugNotDisposed());
```

<details><summary>Test output</summary>

```console
  Expected: leak free
    Actual: <Instance of 'Leaks'>
     Which: contains leaks:
            # The text is generated by leak_tracker.
            # For leak troubleshooting tips open:
            # https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md
            notDisposed:
              total: 1
              objects:
                AnimationController:
                  test: _MergeableMaterialState leak
                  identityHashCode: 572261535
                  context:
                    start: >
                      #6_______flutterEventToLeakTracker_(package:leak_tracker_flutter_testing/src/test_widgets.dart:24:23)
                      #7______MemoryAllocations.dispatchObjectEvent_(package:flutter/src/foundation/memory_allocations.dart:238:23)
                      #8______MemoryAllocations.dispatchObjectCreated_(package:flutter/src/foundation/memory_allocations.dart:272:5)
                      #9______AnimationController._maybeDispatchObjectCreation_(package:flutter/src/animation/animation_controller.dart:289:34)
                      #10_____new_AnimationController_(package:flutter/src/animation/animation_controller.dart:249:5)
                      #11______MergeableMaterialState._initGap_(package:flutter/src/material/mergeable_material.dart:181:44)
                      #12______MergeableMaterialState.initState_(package:flutter/src/material/mergeable_material.dart:173:9)
                      #13_____StatefulElement._firstBuild_(package:flutter/src/widgets/framework.dart:5605:55)
                      #14_____ComponentElement.mount_(package:flutter/src/widgets/framework.dart:5450:5)
                      #15_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #16_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #17_____SingleChildRenderObjectElement.mount_(package:flutter/src/widgets/framework.dart:6649:14)
                      #18_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #19_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #20_____SingleChildRenderObjectElement.mount_(package:flutter/src/widgets/framework.dart:6649:14)
                      #21_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #22_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #23_____SingleChildRenderObjectElement.mount_(package:flutter/src/widgets/framework.dart:6649:14)
                      #24_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #25_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #26_____SingleChildRenderObjectElement.mount_(package:flutter/src/widgets/framework.dart:6649:14)
                      #27_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #28_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #29_____SingleChildRenderObjectElement.mount_(package:flutter/src/widgets/framework.dart:6649:14)
                      #30_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #31_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #32_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5499:16)
                      #33_____StatefulElement.performRebuild_(package:flutter/src/widgets/framework.dart:5637:11)
                      #34_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5190:7)
                      #35_____ComponentElement._firstBuild_(package:flutter/src/widgets/framework.dart:5456:5)
                      #36_____StatefulElement._firstBuild_(package:flutter/src/widgets/framework.dart:5628:11)
                      #37_____ComponentElement.mount_(package:flutter/src/widgets/framework.dart:5450:5)
                      #38_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #39_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #40_____SingleChildRenderObjectElement.mount_(package:flutter/src/widgets/framework.dart:6649:14)
                      #41_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #42_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #43_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5499:16)
                      #44_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5190:7)
                      #45_____ComponentElement._firstBuild_(package:flutter/src/widgets/framework.dart:5456:5)
                      #46_____ComponentElement.mount_(package:flutter/src/widgets/framework.dart:5450:5)
                      #47_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #48_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #49_____SingleChildRenderObjectElement.mount_(package:flutter/src/widgets/framework.dart:6649:14)
                      #50_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #51_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #52_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5499:16)
                      #53_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5190:7)
                      #54_____ComponentElement._firstBuild_(package:flutter/src/widgets/framework.dart:5456:5)
                      #55_____ComponentElement.mount_(package:flutter/src/widgets/framework.dart:5450:5)
                      #56_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #57_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #58_____SingleChildRenderObjectElement.mount_(package:flutter/src/widgets/framework.dart:6649:14)
                      #59_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #60_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #61_____SingleChildRenderObjectElement.mount_(package:flutter/src/widgets/framework.dart:6649:14)
                      #62_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #63_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #64_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5499:16)
                      #65_____StatefulElement.performRebuild_(package:flutter/src/widgets/framework.dart:5637:11)
                      #66_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5190:7)
                      #67_____ComponentElement._firstBuild_(package:flutter/src/widgets/framework.dart:5456:5)
                      #68_____StatefulElement._firstBuild_(package:flutter/src/widgets/framework.dart:5628:11)
                      #69_____ComponentElement.mount_(package:flutter/src/widgets/framework.dart:5450:5)
                      #70_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #71_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #72_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5499:16)
                      #73_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5190:7)
                      #74_____ComponentElement._firstBuild_(package:flutter/src/widgets/framework.dart:5456:5)
                      #75_____ComponentElement.mount_(package:flutter/src/widgets/framework.dart:5450:5)
                      #76_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #77_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
                      #78_____ComponentElement.performRebuild_(package:flutter/src/widgets/framework.dart:5499:16)
                      #79_____StatefulElement.performRebuild_(package:flutter/src/widgets/framework.dart:5637:11)
                      #80_____Element.rebuild_(package:flutter/src/widgets/framework.dart:5190:7)
                      #81_____ComponentElement._firstBuild_(package:flutter/src/widgets/framework.dart:5456:5)
                      #82_____StatefulElement._firstBuild_(package:flutter/src/widgets/framework.dart:5628:11)
                      #83_____ComponentElement.mount_(package:flutter/src/widgets/framework.dart:5450:5)
                      #84_____Element.inflateWidget_(package:flutter/src/widgets/framework.dart:4329:16)
                      #85_____Element.updateChild_(package:flutter/src/widgets/framework.dart:3840:18)
...
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.14.0-14.0.pre.312, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
    • Flutter version 3.14.0-14.0.pre.312 on channel master at /Users/ksokolovskyi/dev/flutter_master
    • Upstream repository git@github.com:ksokolovskyi/flutter.git
    • FLUTTER_GIT_URL = git@github.com:ksokolovskyi/flutter.git
    • Framework revision 72b69f9449 (4 hours ago), 2023-09-15 08:55:50 -0700
    • Engine revision 45bc4307cd
    • Dart version 3.2.0 (build 3.2.0-162.0.dev)
    • DevTools version 2.28.0-dev.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/ksokolovskyi/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME = /Users/ksokolovskyi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by ksokolovskyi**
### Description
- Adds `AnimationController` creation and disposal dispatching for memory leak tracking as part of https://github.com/flutter/flutter/issues/137311;
- Fixes #134838.

### Tests
- Updates `animation_controller_test.dart` to test `AnimationController` object creation and disposal dispatching;
- Fixes memory leak in `_RenderCupertinoSlider`;
- Fixes memory leak in `_CheckedPopupMenuItemState`;
- Fixes memory leak in `ScaffoldMessengerState`;
- Fixes memory leak in `_MergeableMaterialState`;
- Fixes a couple of leaks in tests.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by ksokolovskyi** [comment]
cc @polina-c

**Comment by polina-c** [comment]
Google testing passed.

**Comment by polina-c** [comment]
@ksokolovskyi ,
While AnimationController is disposable, tracking for it and cleanup is not included in first round of cleanup, because we want to keep scope of first iteration not very big.
I suggest to convert this PR to draft, and return to it after releasing leak_tracker MVP.

See details in the design doc:  https://docs.google.com/document/d/1hlGY6HnsH5EJhpQDFm-_e-Sr9euQf6jE74TxkqDxhGY/edit?resourcekey=0--7J08lEADd6HpaTGC1B-Pw

**Comment by polina-c** [comment]
Also, there are thoughts to introduce mixin Disposable, that will implement the instrumentation, so there will not be need to duplicate the code.

**Comment by ksokolovskyi** [comment]
> @ksokolovskyi , While AnimationController is disposable, tracking for it and cleanup is not included in first round of cleanup, because we want to keep scope of first iteration not very big. I suggest to convert this PR to draft, and return to it after releasing leak_tracker MVP.

Got it, I was not aware of the first-round plans. I have converted this PR to the draft.
Could you please mention it somewhere so we don't forget about it?

**Comment by polina-c** [comment]
> > @ksokolovskyi , While AnimationController is disposable, tracking for it and cleanup is not included in first round of cleanup, because we want to keep scope of first iteration not very big. I suggest to convert this PR to draft, and return to it after releasing leak_tracker MVP.
> 
> Got it, I was not aware of the first-round plans. I have converted this PR to the draft. Could you please mention this PR somewhere so we don't forget about it?

Sure: https://github.com/flutter/flutter/issues/134787

**Comment by ksokolovskyi** [comment]
> > > @ksokolovskyi , While AnimationController is disposable, tracking for it and cleanup is not included in first round of cleanup, because we want to keep scope of first iteration not very big. I suggest to convert this PR to draft, and return to it after releasing leak_tracker MVP.
> > 
> > 
> > Got it, I was not aware of the first-round plans. I have converted this PR to the draft. Could you please mention this PR somewhere so we don't forget about it?
> 
> Sure: #134787

Thanks!

**Comment by ksokolovskyi** [comment]
@polina-c, am I supposed to close this PR considering https://github.com/flutter/flutter/pull/137309?

**Comment by polina-c** [comment]
> @polina-c, am I supposed to close this PR considering #137309, or can I merge your changes later?

Actually, you can adjust it to match new structure. It may be faster that I will get code review for mine PR.

**Comment by ksokolovskyi** [comment]
> > @polina-c, am I supposed to close this PR considering #137309, or can I merge your changes later?
> 
> Actually, you can adjust it to match new structure. It may be faster that I will get code review for my PR. Draft for new process: #137311
> 
> And this PR also contains good fixes. It is up to you if you want to push this PR or copy the fixes to new one.

If you don't mind, I will update this PR as soon as possible. Ok?

**Comment by polina-c** [comment]
> > > @polina-c, am I supposed to close this PR considering #137309, or can I merge your changes later?
> > 
> > 
> > Actually, you can adjust it to match new structure. It may be faster that I will get code review for my PR. Draft for new process: #137311
> > And this PR also contains good fixes. It is up to you if you want to push this PR or copy the fixes to new one.
> 
> If you don't mind, I will update this PR as soon as possible. Ok?

Sure, then I will close mine. Thank you!!!

**Comment by ksokolovskyi** [comment]
@polina-c could you please take a look at the latest commit? It seems like `leak_tracker` has false-positive results. 
Maybe I am doing something wrong?

**Comment by polina-c** [comment]
> @polina-c could you please take a look at the latest commit? It seems like `leak_tracker` has false-positive results. Maybe I am doing something wrong?

Yes, you removed ignore for `allNotGCed: true`, and now all not GCed leaks are visible. Return it.

**Comment by ksokolovskyi** [comment]
> > @polina-c could you please take a look at the latest commit? It seems like `leak_tracker` has false-positive results. Maybe I am doing something wrong?
> 
> Yes, you removed ignore for `allNotGCed: true`, and now all not GCed leaks are visible. Return it.

But previously there were no leaks. In all not marked `testWidgetsWithLeakTracking`.

**Comment by polina-c** [comment]
> > > @polina-c could you please take a look at the latest commit? It seems like `leak_tracker` has false-positive results. Maybe I am doing something wrong?
> > 
> > 
> > Yes, you removed ignore for `allNotGCed: true`, and now all not GCed leaks are visible. Return it.
> 
> But previously there were no leaks in all not marked `testWidgetsWithLeakTracking`.

Sent you IM in twitter.

**Comment by ksokolovskyi** [comment]
@polina-c seems like all tests are fixed now :)

**Review by polina-c — APPROVED** [review]

**Comment by ksokolovskyi** [comment]
@polina-c, thanks a lot for the review!

**Pull request merged**
