### PR TITLE
[Android] Support Android 34

### PR DESCRIPTION
**Pull request by camsim99**
Adds support for Android 34 in the following ways:

- Bumps integration tests compile SDK versions 33 --> 34
- Bumps template compile SDK version 33 --> 34
- Also changes deprecated `compileSdkVersion` to `compileSdk`

Part of https://github.com/flutter/flutter/issues/134220

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by gmackall — APPROVED** [review]
This LGTM! Do you know if we have an issue to do the same thing for `blahVersion` -> `blah` for `min` and `target` sdks?

**Review by reidbaker — APPROVED** [review]

**Comment by camsim99** [comment]
> This LGTM! Do you know if we have an issue to do the same thing for `blahVersion` -> `blah` for `min` and `target` sdks?

I don't see that in the [docs](https://developer.android.com/guide/topics/manifest/uses-sdk-element). I think it's just `compileSdkVersion` that was deprecated!

**Comment by gmackall** [comment]
> > This LGTM! Do you know if we have an issue to do the same thing for `blahVersion` -> `blah` for `min` and `target` sdks?
> 
> I don't see that in the [docs](https://developer.android.com/guide/topics/manifest/uses-sdk-element). I think it's just `compileSdkVersion` that was deprecated!

Those docs also don't indicate that `compileSdkVersion` was deprecated, though. 
https://developer.android.com/reference/tools/gradle-api/7.0/com/android/build/api/dsl/BaseFlavor#minsdkversion indicates it is deprecated, though I can't tell if this documentation is referring to the general case. Do you have a link to documentation indicating that `compileSdkVersion` is deprecated? I would be curious to see if there is a source that indicates the deprecation of _only_ `compileSdkVersion`.

**Comment by gmackall** [comment]
Also, for any of them that we decide are deprecated, we should probably update https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration to reflect

**Comment by camsim99** [comment]
Ah good intuition! I couldn't find the right docs for min but I see it now: https://developer.android.com/reference/tools/gradle-api/7.0/com/android/build/api/dsl/BaseFlavor#minSdkVersion(kotlin.Int)

Here's target: https://developer.android.com/reference/tools/gradle-api/7.1/com/android/build/api/dsl/ApplicationBaseFlavor#targetsdkversion

compileSdkVersion is here: https://developer.android.com/reference/tools/gradle-api/7.0/com/android/build/api/dsl/CommonExtension#compilesdkversion

I can file a bug to update that website + those two (min, target) as well

**Comment by reidbaker** [comment]
I was worried this change might break older clients but it looks like minSdk as a property has been available since 4.1 https://developer.android.com/reference/tools/gradle-api/4.1/com/android/build/api/dsl/BaseFlavor#minsdk and that is as old as the dev site hosts api versions.

**Pull request merged**
