### PR TITLE
Disable testonly_devicelab_tests.

### PR DESCRIPTION
**Pull request by godofredoc**
## Description

Those tests are failing in presubmit and blocking PRs.

## Related Issues

https://github.com/flutter/flutter/issues/64158

## Tests

N/A

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by zanderso** [comment]
From chat, this is an experimental builder. Disabling while fixing sgtm.

**Review by zanderso — APPROVED** [review]

**Comment by zanderso** [comment]
Thought it looks like the change to disable didn't affect the presubmits running for this PR?

**Review by digiter — APPROVED** [review]
LGTM

**Comment by godofredoc** [comment]
> Thought it looks like the change to disable didn't affect the presubmits running for this PR?

yeah, there is still and error when reading the file. It is currently reading from ToT of the branch instead of the current PR. https://github.com/flutter/flutter/issues/64165

**Comment by digiter** [comment]
FYI, https://github.com/flutter/infra/pull/193 should have fixed testonly_devicelab_tests.

**Comment by godofredoc** [comment]
> FYI, [flutter/infra#193](https://github.com/flutter/infra/pull/193) should have fixed testonly_devicelab_tests. The change in the infra configs may take some time to propagate, please revert this CL after that.

**Comment by godofredoc** [comment]
> > FYI, [flutter/infra#193](https://github.com/flutter/infra/pull/193) should have fixed testonly_devicelab_tests. The change in the infra configs may take some time to propagate, please revert this CL after that.

Seems like the changes have propagated, I'll wait for the roller to run the test and ensure it passes before closing this PR

**Comment by godofredoc** [comment]
The builder was fixed, closing this change.

**Pull request closed without merging**
