### PR TITLE
Cupertino TextField WIP

### PR DESCRIPTION
**Pull request by sandrasandeep**
Incomplete CupertinoTextField. This pull request was created to make the code @sandrasandeep wrote on this more easily accessible. It is also available on the sandrasandeep/flutter repo.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @xster to take over this PR

**Comment by xster** [comment]
@gspencergoog you mentioned you were taking this yesterday

**Comment by gspencergoog** [comment]
Yes, I'll finish this off and merge it.

**Comment by Hixie** [comment]
@gspencergoog Should we close this in the meantime?

**Comment by Hixie** [comment]
@gspencergoog I'm going to close this PR for now to get it off the review queue.

**Comment by jslavitz** [comment]
@xster @gspencergoog Either of you guys make any progress on this?

**Comment by xster** [comment]
It's in https://github.com/flutter/flutter/pull/23194. Thanks for checking back!

**Pull request closed without merging**
