### PR TITLE
Set up Kotlin linting step in ci with ktlint

### PR DESCRIPTION
**Pull request by gmackall**
Adds a kotlin linting step to the linux analyze check, using a version of [ktlint](https://github.com/pinterest/ktlint) hosted on [CIPD](https://chrome-infra-packages.appspot.com/p/flutter/ktlint/linux-amd64/+/version_1_1_1).

Configured to disallow trailing commas, because of (and now acting as a test for) https://github.com/flutter/flutter/pull/145718. Because of this configuration the PR also removes some trailing commas in some kotlin files.

Also checks in a baseline file.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gmackall** [comment]
Baseline is also working, as the check passes now with it included

**Comment by gmackall** [comment]
@reidbaker FYI this is the pr in the state we discussed getting it to, where the decision just needs to be made if the linting tool should be on CIPD, or downloaded (current state) like the packages repo https://github.com/flutter/packages/blob/abb04bb89cca97e653764a60bde0ee4e816db322/script/tool/lib/src/format_command.dart#L39

**Comment by gmackall** [comment]
Support for adding a dependency on `ktlint` just landed in https://flutter-review.googlesource.com/c/recipes/+/56760/, so this should be unblocked now. Just need to test to make sure its getting invoked properly, then clean up and get out of draft

**Comment by gmackall** [comment]
cc @keyonghan (sorry for the continued questions on this!)
I'm trying to depend on ktlint in cipd now in this pr
```
dependencies: >-
        [
          {"dependency": "ktlint", "version": "version:version_1_1_1"}
        ]
```
and seeing an error that the version tag doesn't exist
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8752187117714240737/+/u/Install_ktlint/ensure_installed/stdout
but I thought that I had created it correctly here
https://chrome-infra-packages.appspot.com/p/flutter/ktlint/linux-amd64/+/version_1_1_1

Did I perhaps mess something up in [this step](https://github.com/flutter/cocoon/tree/main/cipd_packages#adding-a-reference-to-the-cipd-package)?

**Comment by keyonghan** [comment]
> cc @keyonghan (sorry for the continued questions on this!) I'm trying to depend on ktlint in cipd now in this pr
> 
> ```
> dependencies: >-
>         [
>           {"dependency": "ktlint", "version": "version:version_1_1_1"}
>         ]
> ```
> 
> and seeing an error that the version tag doesn't exist https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8752187117714240737/+/u/Install_ktlint/ensure_installed/stdout but I thought that I had created it correctly here https://chrome-infra-packages.appspot.com/p/flutter/ktlint/linux-amd64/+/version_1_1_1
> 
> Did I perhaps mess something up in [this step](https://github.com/flutter/cocoon/tree/main/cipd_packages#adding-a-reference-to-the-cipd-package)?

You need a full tag name: `version:version_1_1_1`.

**Comment by keyonghan** [comment]
So instead of a reference, a tag may be more suitable for this case. (I need to update the doc again).
```
cipd set-ref flutter/ktlint/linux-amd64 -tag version:version_1_1_1 -version InstanceID
```

**Comment by gmackall** [comment]
> So instead of a reference, a tag may be more suitable for this case. (I need to update the doc again).
> 
> ```
> cipd set-ref flutter/ktlint/linux-amd64 -tag version:version_1_1_1 -version InstanceID
> ```

Hmm so I originally ran 
```
cipd set-ref flutter/ktlint/linux-amd64 -ref version_1_1_1 -version cuHnxtuMe-YkvqnXhXeWPq3i_0TZv4ykCWmDQVxN7f8C
```
Changing `ref` to `tag` gives me an error that the flag doesn't exist
```
mackall-macbookpro:flutter_tools mackall$ cipd set-ref flutter/ktlint/linux-amd64 -tag=version:version_1_1_1 -version cuHnxtuMe-YkvqnXhXeWPq3i_0TZv4ykCWmDQVxN7f8C
flag provided but not defined: -tag
Moves a ref to point to a given version.

usage:  cipd set-ref <package or package prefix> [options]
  -cache-dir string
    	Directory for the shared cache (can also be set by CIPD_CACHE_DIR env var).
  -json-output path
    	A path to write operation results to.
  -log-level value
    	The logging level. Valid options are: debug, info, warning, error. (default info)
  -ref ref
    	A ref to point to the package instance (can be used multiple times).
  -service-account-json string
    	Path to JSON file with service account credentials to use. Or specify ":gce" to use GCE's default service account.
  -service-url string
    	Backend URL. If provided via an "ensure" file, the URL in the file takes precedence. (default https://chrome-infra-packages.appspot.com)
  -verbose
    	Enable more logging (deprecated, use -log-level=debug).
  -version string
    	Package version to point the ref to. (default "<version>")
```

I also assume that I'm not going to have permission currently either way, so I'll open another access request

**Comment by gmackall** [comment]
Oh wait its probably supposed to be also `set-ref` -> `set-tag`, that works (at least up until permissions)

**Comment by gmackall** [comment]
Okay nevermind, I was setting the version wrong 🤦. Sorry about that! Looks like the step is succeeding now https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze/76227/overview

**Review by reidbaker — APPROVED** [review]

**Comment by gmackall** [comment]
I'm pretty certain this does not affect g3 in any way (it only affects ci config, benchmarks, and a test file), so I'm going to override the google testing. I'm sorry if I was wrong 🙏

**Comment by reidbaker** [comment]
> I'm pretty certain this does not affect g3 in any way (it only affects ci config, benchmarks, and a test file), so I'm going to override the google testing. I'm sorry if I was wrong 🙏

Post submit test passed https://critique.corp.google.com/cl/621639365

**Comment by whesse** [comment]
This new test is breaking on the Dart CI, where we run the flutter analysis test with tip-of-tree Dart SDK.
Whatever is added to the Flutter recipes to install klint also needs to be added to the Dart script at https://dart.googlesource.com/sdk/+/refs/heads/main/tools/bots/flutter/analyze_flutter_flutter.sh

Alternatively, if there is a command-line option or environment variable to set to disable the klint checks, or if these could be made a separate test script, rather than adding them into the existing analyze.dart test, which otherwise just requires a normal framework installation.

**Comment by gmackall** [comment]
> This new test is breaking on the Dart CI, where we run the flutter analysis test with tip-of-tree Dart SDK. Whatever is added to the Flutter recipes to install klint also needs to be added to the Dart script at https://dart.googlesource.com/sdk/+/refs/heads/main/tools/bots/flutter/analyze_flutter_flutter.sh
> 
> Alternatively, if there is a command-line option or environment variable to set to disable the klint checks, or if these could be made a separate test script, rather than adding them into the existing analyze.dart test, which otherwise just requires a normal framework installation.

I'm fine reverting this and moving the test to a different check/shard. 

We should also definitely add documentation noting that this check is copied and run in the dart ci as well. Are there other tests that also get copied? Is there a testowner that should be added for this check? I'm not particularly sure how one could know of or anticipate this problem.

**Comment by gmackall** [comment]
Can I ask why you run this test in the dart ci, with the latest dart? It seems like a significant portion of the checks it makes are functionality I wouldn't expect to be run anywhere else, or to be particularly tied to dart versions (things like ['Links for creating GitHub issues'](https://github.com/gmackall/flutter/blob/master/dev/bots/analyze.dart#L1143), ['Unexpected binaries...'](https://github.com/gmackall/flutter/blob/master/dev/bots/analyze.dart#L1640), ['All tool test files end in _test.dart...'](https://github.com/gmackall/flutter/blob/master/dev/bots/analyze.dart#L406), etc).

**Comment by whesse** [comment]
We only want to run any changes in the Dart analyzer and linter against the framework code, and this is the Flutter framework test that does that.  We could extract just the relevant parts into commands run directly in our script, but then it has the danger of getting out-of-sync with what the flutter framework runs.  But it does make sense to skip all of the non-relevant tests run by analyze.sh.

OK, looking at it, I agree that we should extract the analyzer tests out to a separate set, since there are so many non-relevant tests in this suite. Either this suite could be split into two parts, or some option added to only run the analysis tests (but also on gallery and code snippets), or we would have to clone all the analysis test code into our script, with the disadvantages of code clones. So I don't think you should revert.

**Pull request merged**
