### PR TITLE
[flutter_releases] Flutter 1.26.0-17.1.pre Dev - Revert vm_service, other packages from pub roll

### PR DESCRIPTION
**Pull request by christopherfujino**
This reverts https://github.com/flutter/flutter/commit/d1538320d21c67ac5f90ae1b1b4ca6c76307aebe to avoid https://github.com/dart-lang/sdk/issues/44800 in package vm_service.

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Not sure why googlebot is upset, but I've signed a CLA and this reverts my commit and I'm ok with all of that.

**Comment by christopherfujino** [comment]
> Not sure why googlebot is upset, but I've signed a CLA and this reverts my commit and I'm ok with all of that.

Yeah, Googlebot never knows how to handle commits with multiple authors, even if all authors have signed the CLA.

**Review by pcsosinski — APPROVED** [review]

**Comment by pcsosinski** [comment]
title should 17.1.pre?

**Comment by christopherfujino** [comment]
> title should 17.1.pre?

Good catch.

**Comment by christopherfujino** [comment]
Manually overrided clabot as all authors are Googlers.

**Pull request merged**
