### PR TITLE
Roll engine to 431a2511513186b06c4ef32d8abbb3d9b937e5d6.

### PR DESCRIPTION
**Pull request by rmacnak-google**

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by cbracken** [comment]
FYI: this roll regressed the following benchmarks:
* flutter_gallery__back_button_memory start and end total kb
* hot_mode_dev_cycle__benchmark hotRestartMillisecondsToFrame
* stock_layout_iteration microbenchmark
and possibly others.

**Comment by yjbanov** [comment]
It seems this also severely regressed app start-up time. The benchmark is noisy, but the regression seems to be pretty clearly visible in history.

screen shot 2017-07-13 at 6 26 28 pm

**Comment by Hixie** [comment]
We should revert this Dart roll for now.

**Pull request merged**
