### PR TITLE
[flutter_tools] re-enable debug extension

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

I accidentally disabled this when migrating to the latest dwds/compiler updates. 

@DanTup I wasn't able to get the this to work from vs code, though the command line works okay. I get an `net::ERR_CONNECTION_REFUSE` from SSE on the browser side and then the extension goes down. also fyi @grouma

### CODE REVIEW

**Comment by DanTup** [comment]
> @DanTup I wasn't able to get the this to work from vs code, though the command line works okay. I get an `net::ERR_CONNECTION_REFUSE` from SSE on the browser side and then the extension goes down.

Is the error here when using VS Code, or command line? If VS Code, this won't work yet because it's using SSE and in VS Code we don't support using SSE (for the VM service proxy). I have a Flutter branch that passes through a flag through to dwds to tell it not to use SSE but it doesn't rebase cleanly with the recent changes so I need to fix it up before I can open a PR.

Is there a way to test this is being set correctly to ensure it doesn't regress? (a previous test is [here](https://github.com/flutter/flutter/pull/44263/files#diff-fef5cc5637876426f119ad43556952aaR177) but I don't know how easily adaptable it is after the changes).

**Comment by jonahwilliams** [comment]
Yeah from VS Code, command line works okay. Since that is expected I will adapt a test today

**Comment by DanTup** [comment]
FWIW, I applied this fix to my Flutter branch and ran it with my VS Code branch to test. I was able to launch the Gallery using web-server, click the extension button, and have it resume and hit a breakpoint 👍 

I'll do some testing on GitPod, and if it still works there, I'll open a PR with the changes to force WebSockets (instead of SSE) for review/discussion.

Thanks!

**Review by christopherfujino — APPROVED** [review]
lgtm

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Gonna use this to kick the build

**Pull request merged**
