### PR TITLE
[flutter_tools] Enable custom devices on all channels (#109953)

### PR DESCRIPTION
**Pull request by zanderso**
This is a cherry-pick of https://github.com/flutter/flutter/pull/109953 for https://github.com/flutter/flutter/issues/108787

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by zanderso** [comment]
@keyonghan The `autosubmit` label seems not to have worked here.

**Comment by keyonghan** [comment]
> @keyonghan The `autosubmit` label seems not to have worked here.

Auto submit is not supporting release branches as of now. So this WAI. 
Related bug: https://github.com/flutter/flutter/issues/110023

**Comment by christopherfujino** [comment]
> > @keyonghan The `autosubmit` label seems not to have worked here.
> 
> Auto submit is not supporting release branches as of now. So this WAI. Related bug: #110023

Could we catch this and have autosubmit comment?

**Comment by zanderso** [comment]
I think @itsjustkevin meant this to land, so I'm going to go ahead and click the button.

**Pull request merged**
