### PR TITLE
Update IntegrationTestPlugin.m

### PR DESCRIPTION
**Pull request by barringb**
The integration_test native plugin is not being correctly registered on iOS when running tests via `flutter drive`. Adding an 
`IntegrationTestPlugin` instance to `registerWithRegistrar` method in `IntegrationTestPlugin.m`.

This [plugin instance was previously removed](https://github.com/flutter/plugins/pull/2465) before [`integration_test` was migrated from `e2e`](https://pub.dev/documentation/e2e/latest/) to prevent an error where the `e2e` plugin would not exit testing. This does not appear to be an issue with `integration_test` and my tests exit properly regardless of run with `flutter drive` or through XCode.

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/91668

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by pdblasi-google — APPROVED** [review]
LGTM

@barringb Thanks for the PR and the great write-up! The links and history provided some much needed context, so I really appreciate it!

**Review by jmagman — COMMENTED** [review]
> This does not appear to be an issue with `integration_test` and my tests exit properly regardless of run with `flutter drive` or through XCode.

You tested this with static libraries (the default with an Objective-C project)?

> [`integration_test` was migrated from `e2e`](https://pub.dev/documentation/e2e/latest/) to prevent an error where the `e2e` plugin would not exit testing.

I'm not sure how that would have fixed this issue.  I need to check out this change and see if I can reproduce https://github.com/flutter/flutter/issues/48601

**Comment by jmagman** [comment]
I tried to get the hang to reproduce and couldn't, details in https://github.com/flutter/flutter/issues/91668#issuecomment-1454200234

Instead of this one line change, let's actually remove the entire workaround from https://github.com/flutter/plugins/pull/2465.  Meaning remove the exposed `-setupChannels:` method, and change the `+registerWithRegistrar` to its original 
```objc
+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar> *)registrar {
  FlutterMethodChannel *channel = [FlutterMethodChannel methodChannelWithName:kIntegrationTestPluginChannel
                                                              binaryMessenger:registrar.messenger];
  [registrar addMethodCallDelegate:[self instance] channel:channel];
}
```
Let me know if you would prefer I close this and open my own PR instead.

**Review by jmagman — CHANGES_REQUESTED** [review]
Requesting `-setupChannels:` removal.

**Comment by goderbauer** [comment]
(Triage) @barringb Do you still have plans to follow-up on the feedback given above? Thanks!

**Comment by jmagman** [comment]
I wound up reverting https://github.com/flutter/plugins/pull/2465 in https://github.com/flutter/flutter/pull/123729, including removing the now-dead code.

@barringb Thank you for your contribution and kicking off this investigation!

**Pull request closed without merging**
