### PR TITLE
Fix bold not getting cleared on new line

### LINKED ISSUE #52204: Pressing `h` help option in resident runner leaves terminal font as bold
This persists until you exit and flutter run again.

Screen Shot 2020-03-08 at 9 40 44 AM

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/52204

I don't fully understand what's going on here, but on macOS and Linux I can reliably reproduce that the next line comes out bold, even though the characters all look good. Adding a trailing clear bold when there's parenthetical text stops that.

@zanderso @jonahwilliams 

Maybe someone like @christopherfujino or @gspencergoog knows about why this is.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
No idea, if it works ship it

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by zanderso — APPROVED** [review]

**Review by jonahwilliams — CHANGES_REQUESTED** [review]
Please fix the tests

**Comment by dnfield** [comment]
Done

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Redness is a flake on cirrus. Landing.

**Pull request merged**
