### PR TITLE
Updating new plugin's min iOS sdk to 9.0

### PR DESCRIPTION
**Pull request by cyanglaz**
This is to match the app's min iOS sdk version: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/ios-objc.tmpl/Runner.xcodeproj/project.pbxproj.tmpl#L287

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jmagman** [comment]
This means that new plugins created with this template won't work on Flutter apps created before https://github.com/flutter/flutter/pull/62902 in 1.21.0-9.0.pre.

I don't think we should do this, there's nothing wrong with plugins (frameworks) supporting versions older than the app does.  https://github.com/flutter/flutter/issues/63253#issuecomment-670803239

**Review by jmagman — CHANGES_REQUESTED** [review]
I don't think we should do this without a LOT more thought, risk analysis, migration paths (like doing https://github.com/flutter/flutter/issues/62880).

Plus this isn't even a complete fix, you missed https://github.com/flutter/flutter/blob/9397c374a6c5140742a833645c992278622e4b27/packages/flutter_tools/templates/plugin/ios-swift.tmpl/projectName.podspec.tmpl#L18

**Comment by cyanglaz** [comment]
Make sense! Closing.

**Comment by stuartmorgan** [comment]
> there's nothing wrong with plugins (frameworks) supporting versions older than the app does. [#63253 (comment)](https://github.com/flutter/flutter/issues/63253#issuecomment-670803239)

Sure, but there's also nothing wrong with supporting iOS 8 in new apps either. I think the main question is not whether there's something wrong with it, but whether we want the default experience when creating a new, green-field plugin to be an assumption of supporting iOS 8. I would argue that we probably don't.

**Comment by stuartmorgan** [comment]
(And while there's nothing *wrong* with it, the trigger for this was that we are now getting bug reports about deprecation warnings from people running iOS-8-targeted plugins in new iOS-9-targeted apps—warnings that the plugin developer has never seen, and are somewhat annoying to fix since they involve ifdefs that, frankly, even moderately experienced iOS developers screw up not infrequently. How much do we want that to be the default experience for plugin developers?)

**Comment by jmagman** [comment]
> And while there's nothing wrong with it, the trigger for this was that we are now getting bug reports about deprecation warnings from people running iOS-8-targeted plugins in new iOS-9-targeted apps

On what version?  That shouldn't be happening anymore as of https://github.com/flutter/flutter/pull/66590 in 1.23.0-13.0.pre

**Comment by jmagman** [comment]
If we want to make new plugins not work with old Flutter apps without manual intervention by default I'm fine with that, but I think we should document the flows that will break, document the intervention needed, etc.  I'm suggesting this change has larger consequences and we should cover those.  And also, it's going to happen again next year if Xcode does the same thing to 9.0.

**Comment by stuartmorgan** [comment]
> On what version? That shouldn't be happening anymore as of #66590 in 1.23.0-13.0.pre

No, that fix *creates* the warnings I'm talking about. See https://github.com/flutter/flutter/issues/76370 for an example. Suppressing those requires the plugin author to add min-target-sdk ifdefs for minumum SDK versions higher than they have set their min SDK target to.

**Comment by jmagman** [comment]
@stuartmorgan Ahh interesting.  As I said I'm fine with keeping the plugins and apps in sync if that's what we want to do, and increment it as Xcode drops lower versions.  I think that would require:
1. Tooling support of automatic migration of Flutter apps (and plugin examples), and plugin podspecs to the minimum. https://github.com/flutter/flutter/issues/62880
2. Optionally some kind of opt-out if the plugin author really wants to support an older version?  Maybe not needed.
3. Documentation for both app developers and plugin authors for how to manually change their Xcode project and/or Podfile if they get stuck on an older version of Flutter (which happens for various reasons).

And at the absolute barest minimum this PR needs to cover Swift projects and have some tests.

**Pull request closed without merging**
