### PR TITLE
Roll engine to f177f54352785d3bf96ca4d562e8d524e2d84fde

### PR DESCRIPTION
**Pull request by cbracken**

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by chinmaygarde — CHANGES_REQUESTED** [review]
We are investigating a crash that manifests itself in unopt builds. We are not yet sure if the assertion is benign.

**Comment by cbracken** [comment]
Thanks for the heads-up. Holding off on the roll.

**Comment by chinmaygarde** [comment]
A roll back is being performed in https://github.com/flutter/engine/pull/4273.

**Pull request closed without merging**
