### PR TITLE
Reland: Show output from pub get in flutter pub get

### PR DESCRIPTION
**Pull request by sigurdm**
Reland of https://github.com/flutter/flutter/pull/106300 that was reverted here: https://github.com/flutter/flutter/pull/110478

Original description:

Part of https://github.com/dart-lang/pub/issues/2971 .

`dart pub get` has detailed output about outdated dependencies. This is currently not exposed from `flutter pub get`.

We are missing out on at least this information:
 * newer version available
 * package obsolete
 * version retracted
 * known vulnerability (planned)

Before:
```
> flutter pub get
Running "flutter pub get" in sensors_plus...                     1,691ms
Warning: You are using these overridden dependencies:
! sensors_plus_platform_interface 1.1.1 from path ../../sensors_plus_platform_interface
! sensors_plus_web 1.1.1 from path ../../sensors_plus_web
Running "flutter pub get" in example...                          1,019ms
```
Note how the warnings output really belongs to the resolution from the example.

After:
```
> flutter pub get
Running "flutter pub get" in sensors_plus...                     1,803ms
Resolving dependencies...
  matcher 0.12.11 (0.12.12 available)
  test 1.21.1 (1.21.2 available)
  test_api 0.4.9 (0.4.10 available)
  test_core 0.4.13 (0.4.14 available)
  vm_service 8.3.0 (9.0.0 available)
Got dependencies!
Resolving dependencies in ./example...
Got dependencies in ./example.
```
This PR also uses `pub get --example` ([implemented here](https://github.com/dart-lang/pub/pull/2857)) to resolve in './example' if it exists.

Now the output from resolution in ./example is reduced as long as there are no errors.

Because `flutter pub get` will retry `pub get` until successful the output of each run is recorded, and only the output of the last run is shown.

Fix: a small bug where `flutter create` for some templates would invoke pub even if given a `--no-pub` argument.

Cleanup: `pub get` will no longer be invoked with --no-precompile (that is now default).

Output from `pub get` is also show when doing `flutter create` - that might be distracting - maybe we should turn that off:
```
> flutter create test_plugin -tplugin
Creating project test_plugin...
Running "flutter pub get" in test_plugin...                      1,931ms
Resolving dependencies in test_plugin...
+ async 2.9.0
+ boolean_selector 2.1.0
+ characters 1.2.1
+ clock 1.1.1
+ collection 1.16.0
+ fake_async 1.3.1
+ flutter 0.0.0 from sdk flutter
+ flutter_lints 2.0.1
+ flutter_test 0.0.0 from sdk flutter
+ lints 2.0.0
+ matcher 0.12.11 (0.12.12 available)
+ material_color_utilities 0.1.5
+ meta 1.8.0
+ path 1.8.2
+ plugin_platform_interface 2.1.2
+ sky_engine 0.0.99 from sdk flutter
+ source_span 1.9.0
+ stack_trace 1.10.0
+ stream_channel 2.1.0
+ string_scanner 1.1.1
+ term_glyph 1.2.1
+ test_api 0.4.9 (0.4.10 available)
+ vector_math 2.1.2
Changed 23 dependencies in test_plugin!
Resolving dependencies in test_plugin/example...
Got dependencies in test_plugin/example.
Wrote 25 files.

All done!

Your plugin code is in test_plugin/lib/test_plugin.dart.

Your example app code is in test_plugin/example/lib/main.dart.


You've created a plugin project that doesn't yet support any platforms.


To add platforms, run `flutter create -t plugin --platforms <platforms> .` under test_plugin.
For more information, see https://flutter.dev/go/plugin-platforms.
```

Also includes color in the pub terminal output (depending on the flutter terminal color detection):

image

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by sigurdm** [comment]
The first commit is (hopefully) fixing the reason this was reverted.

The process from `startProcess(` would never have its stdout and stderr listened to, this would cause the process to hang on windows when the pipe filled up (speculation). Using `exec` instead should be fine here.

@zanderso  is there away to trigger the test that failed in https://github.com/flutter/flutter/pull/110478 ?

**Review by christopherfujino — APPROVED** [review]
LGTM.

Let me try to validate this test locally.

**Review by christopherfujino — CHANGES_REQUESTED** [review]
Actually, flutter packages get is failing for me when I run this locally (not sure if I'm holding it wrong):

When I execute `dart .\bin\test_runner.dart test -t windows_chrome_dev_mode` on this branch, I get:

```
[windows_chrome_dev_mode] [STDOUT] Executing "D:\git\flutter\bin\flutter packages get" in "C:\Users\chris\AppData\Local\Temp\edited_flutter_gallery" with environment {BOT: true, LANG: en_US.UTF-8}
[windows_chrome_dev_mode] [STDOUT] stdout: Running "flutter pub get" in edited_flutter_gallery...
[windows_chrome_dev_mode] [STDOUT] stdout: pub get failed (server unavailable) -- attempting retry 1 in 1 second...
[windows_chrome_dev_mode] [STDOUT] stdout: pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
[windows_chrome_dev_mode] [STDOUT] stdout: pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...
[windows_chrome_dev_mode] [STDOUT] stdout: pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...
[windows_chrome_dev_mode] [STDOUT] stdout: pub get failed (server unavailable) -- attempting retry 5 in 16 seconds...
[windows_chrome_dev_mode] [STDOUT] stdout: pub get failed (server unavailable) -- attempting retry 6 in 32 seconds...
```

**Comment by christopherfujino** [comment]
> Actually, flutter packages get is failing for me when I run this locally (not sure if I'm holding it wrong):
> 
> When I execute `dart .\bin\test_runner.dart test -t windows_chrome_dev_mode` on this branch, I get:
> 
> ```
> [windows_chrome_dev_mode] [STDOUT] Executing "D:\git\flutter\bin\flutter packages get" in "C:\Users\chris\AppData\Local\Temp\edited_flutter_gallery" with environment {BOT: true, LANG: en_US.UTF-8}
> [windows_chrome_dev_mode] [STDOUT] stdout: Running "flutter pub get" in edited_flutter_gallery...
> [windows_chrome_dev_mode] [STDOUT] stdout: pub get failed (server unavailable) -- attempting retry 1 in 1 second...
> [windows_chrome_dev_mode] [STDOUT] stdout: pub get failed (server unavailable) -- attempting retry 2 in 2 seconds...
> [windows_chrome_dev_mode] [STDOUT] stdout: pub get failed (server unavailable) -- attempting retry 3 in 4 seconds...
> [windows_chrome_dev_mode] [STDOUT] stdout: pub get failed (server unavailable) -- attempting retry 4 in 8 seconds...
> [windows_chrome_dev_mode] [STDOUT] stdout: pub get failed (server unavailable) -- attempting retry 5 in 16 seconds...
> [windows_chrome_dev_mode] [STDOUT] stdout: pub get failed (server unavailable) -- attempting retry 6 in 32 seconds...
> ```

Here's the documentation on running these locally: https://github.com/flutter/flutter/tree/master/dev/devicelab#running-specific-tests

**Comment by sigurdm** [comment]
Hmm, I get through `packages get` on my local windows machine (not able to run the whole test due to missing permissions):
```
$ ../../bin/dart bin/test_runner.dart test -t windows_chrome_dev_mode
[]


Running task "windows_chrome_dev_mode"

Executing "C:\Users\sigurdm\flutter\bin\cache\dart-sdk\bin\dart --disable-dart-dev --enable-vm-service=0 --no-pause-isolates-on-exit bin/tasks/windows_chrome_dev_mode.dart" in "C:\Users\sigurdm\flutter\dev\devicelab" with environment {BOT: true, LANG: en_US.UTF-8}
[windows_chrome_dev_mode] [STDOUT] The Dart VM service is listening on http://127.0.0.1:56167/eftIILWuZ4g=/
[windows_chrome_dev_mode] Connected to VM server.
[windows_chrome_dev_mode] [STDOUT] Running task with a timeout of null.
[windows_chrome_dev_mode] [STDOUT] Enabling configs for macOS and Linux...
[windows_chrome_dev_mode] [STDOUT] Executing "C:\Users\sigurdm\flutter\bin\flutter config -v --enable-macos-desktop --enable-linux-desktop" in "C:\Users\sigurdm\flutter\dev\devicelab" with environment {BOT: true, LANG: en_US.UTF-8}
[windows_chrome_dev_mode] [STDOUT] stdout: [ +160 ms] executing: [C:\Users\sigurdm\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[windows_chrome_dev_mode] [STDOUT] stdout: [+1108 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[windows_chrome_dev_mode] [STDOUT] stdout: [   +1 ms] f68a9f8d1c059e3e59c335dd29f995bf06df06d2
[windows_chrome_dev_mode] [STDOUT] stdout: [   +1 ms] executing: [C:\Users\sigurdm\flutter/] git tag --points-at f68a9f8d1c059e3e59c335dd29f995bf06df06d2
[windows_chrome_dev_mode] [STDOUT] stdout: [ +415 ms] Exit code 0 from: git tag --points-at f68a9f8d1c059e3e59c335dd29f995bf06df06d2
[windows_chrome_dev_mode] [STDOUT] stdout: [   +2 ms] executing: [C:\Users\sigurdm\flutter/] git describe --match *.*.* --long --tags f68a9f8d1c059e3e59c335dd29f995bf06df06d2
[windows_chrome_dev_mode] [STDOUT] stdout: [ +552 ms] Exit code 0 from: git describe --match *.*.* --long --tags f68a9f8d1c059e3e59c335dd29f995bf06df06d2
[windows_chrome_dev_mode] [STDOUT] stdout: [        ] 3.0.0-0.0.pre-2634-gf68a9f8d1c
[windows_chrome_dev_mode] [STDOUT] stdout: [ +855 ms] Unable to locate an Android SDK.
[windows_chrome_dev_mode] [STDOUT] stdout: [   +7 ms] executing: [C:\Users\sigurdm\flutter/] git rev-parse --abbrev-ref HEAD
[windows_chrome_dev_mode] [STDOUT] stdout: [ +303 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[windows_chrome_dev_mode] [STDOUT] stdout: [        ] reland_pub_get_output
[windows_chrome_dev_mode] [STDOUT] stdout: [ +190 ms] Setting "enable-linux-desktop" value to "true".
[windows_chrome_dev_mode] [STDOUT] stdout: [   +8 ms] Setting "enable-macos-desktop" value to "true".
[windows_chrome_dev_mode] [STDOUT] stdout: [        ]
[windows_chrome_dev_mode] [STDOUT] stdout:            You may need to restart any open editors for them to read new settings.
[windows_chrome_dev_mode] [STDOUT] stdout: [  +22 ms] "flutter config" took 144ms.
[windows_chrome_dev_mode] [STDOUT] stdout: [   +5 ms] ensureAnalyticsSent: 2ms
[windows_chrome_dev_mode] [STDOUT] stdout: [   +2 ms] Running shutdown hooks
[windows_chrome_dev_mode] [STDOUT] stdout: [        ] Shutdown hooks complete
[windows_chrome_dev_mode] [STDOUT] stdout: [   +7 ms] exiting with code 0
[windows_chrome_dev_mode] [STDOUT] Executing "C:\Users\sigurdm\flutter\bin\flutter packages get" in "C:\Users\sigurdm\AppData\Local\Temp\edited_flutter_gallery" with environment {BOT: true, LANG: en_US.UTF-8}
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading package sky_engine...                                1,107ms
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading flutter_patched_sdk tools...                         1,034ms
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading flutter_patched_sdk_product tools...                 1,006ms
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading windows-x64 tools...                                    3.8s
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading windows-x64/font-subset tools...                       587ms
[windows_chrome_dev_mode] [STDOUT] stdout: Running "flutter pub get" in edited_flutter_gallery...             26.9s
[windows_chrome_dev_mode] [STDOUT] stdout: Resolving dependencies...
[windows_chrome_dev_mode] [STDOUT] stdout: + _fe_analyzer_shared 46.0.0 (47.0.0 available)
[windows_chrome_dev_mode] [STDOUT] stdout: + analyzer 4.6.0 (4.7.0 available)
[windows_chrome_dev_mode] [STDOUT] stdout: + archive 3.3.1
[windows_chrome_dev_mode] [STDOUT] stdout: + args 2.3.1
[windows_chrome_dev_mode] [STDOUT] stdout: + async 2.9.0
[windows_chrome_dev_mode] [STDOUT] stdout: + boolean_selector 2.1.0
[windows_chrome_dev_mode] [STDOUT] stdout: + characters 1.2.1
[windows_chrome_dev_mode] [STDOUT] stdout: + clock 1.1.1
[windows_chrome_dev_mode] [STDOUT] stdout: + collection 1.16.0
[windows_chrome_dev_mode] [STDOUT] stdout: + connectivity 3.0.6 (discontinued)
[windows_chrome_dev_mode] [STDOUT] stdout: + connectivity_for_web 0.4.0+1 (discontinued)
[windows_chrome_dev_mode] [STDOUT] stdout: + connectivity_macos 0.2.1+2
[windows_chrome_dev_mode] [STDOUT] stdout: + connectivity_platform_interface 2.0.1
[windows_chrome_dev_mode] [STDOUT] stdout: + convert 3.0.2
[windows_chrome_dev_mode] [STDOUT] stdout: + coverage 1.5.0
[windows_chrome_dev_mode] [STDOUT] stdout: + crypto 3.0.2
[windows_chrome_dev_mode] [STDOUT] stdout: + csslib 0.17.2
[windows_chrome_dev_mode] [STDOUT] stdout: + cupertino_icons 1.0.5
[windows_chrome_dev_mode] [STDOUT] stdout: + device_info 2.0.3 (discontinued)
[windows_chrome_dev_mode] [STDOUT] stdout: + device_info_platform_interface 2.0.1
[windows_chrome_dev_mode] [STDOUT] stdout: + fake_async 1.3.1
[windows_chrome_dev_mode] [STDOUT] stdout: + file 6.1.4
[windows_chrome_dev_mode] [STDOUT] stdout: + flutter 0.0.0 from sdk flutter
[windows_chrome_dev_mode] [STDOUT] stdout: + flutter_driver 0.0.0 from sdk flutter
[windows_chrome_dev_mode] [STDOUT] stdout: + flutter_gallery_assets 1.0.2
[windows_chrome_dev_mode] [STDOUT] stdout: + flutter_goldens 0.0.0 from sdk flutter
[windows_chrome_dev_mode] [STDOUT] stdout: + flutter_goldens_client 0.0.0 from path ..\..\..\..\flutter\packages\flutter_goldens_client
[windows_chrome_dev_mode] [STDOUT] stdout: + flutter_test 0.0.0 from sdk flutter
[windows_chrome_dev_mode] [STDOUT] stdout: + flutter_web_plugins 0.0.0 from sdk flutter
[windows_chrome_dev_mode] [STDOUT] stdout: + frontend_server_client 3.0.0
[windows_chrome_dev_mode] [STDOUT] stdout: + fuchsia_remote_debug_protocol 0.0.0 from sdk flutter
[windows_chrome_dev_mode] [STDOUT] stdout: + glob 2.1.0
[windows_chrome_dev_mode] [STDOUT] stdout: + html 0.15.0
[windows_chrome_dev_mode] [STDOUT] stdout: + http_multi_server 3.2.1
[windows_chrome_dev_mode] [STDOUT] stdout: + http_parser 4.0.1
[windows_chrome_dev_mode] [STDOUT] stdout: + integration_test 0.0.0 from sdk flutter
[windows_chrome_dev_mode] [STDOUT] stdout: + intl 0.17.0
[windows_chrome_dev_mode] [STDOUT] stdout: + io 1.0.3
[windows_chrome_dev_mode] [STDOUT] stdout: + js 0.6.4
[windows_chrome_dev_mode] [STDOUT] stdout: + logging 1.0.2
[windows_chrome_dev_mode] [STDOUT] stdout: + matcher 0.12.12
[windows_chrome_dev_mode] [STDOUT] stdout: + material_color_utilities 0.2.0
[windows_chrome_dev_mode] [STDOUT] stdout: + meta 1.8.0
[windows_chrome_dev_mode] [STDOUT] stdout: + mime 1.0.2
[windows_chrome_dev_mode] [STDOUT] stdout: + node_preamble 2.0.1
[windows_chrome_dev_mode] [STDOUT] stdout: + package_config 2.1.0
[windows_chrome_dev_mode] [STDOUT] stdout: + path 1.8.2
[windows_chrome_dev_mode] [STDOUT] stdout: + platform 3.1.0
[windows_chrome_dev_mode] [STDOUT] stdout: + plugin_platform_interface 2.1.2
[windows_chrome_dev_mode] [STDOUT] stdout: + pool 1.5.1
[windows_chrome_dev_mode] [STDOUT] stdout: + process 4.2.4
[windows_chrome_dev_mode] [STDOUT] stdout: + pub_semver 2.1.1
[windows_chrome_dev_mode] [STDOUT] stdout: + scoped_model 2.0.0-nullsafety.0 from git https://github.com/kevmoo/scoped_model.git at cc3944
[windows_chrome_dev_mode] [STDOUT] stdout: + shelf 1.3.2
[windows_chrome_dev_mode] [STDOUT] stdout: + shelf_packages_handler 3.0.1
[windows_chrome_dev_mode] [STDOUT] stdout: + shelf_static 1.1.1
[windows_chrome_dev_mode] [STDOUT] stdout: + shelf_web_socket 1.0.2
[windows_chrome_dev_mode] [STDOUT] stdout: + shrine_images 1.1.2 (2.0.1 available)
[windows_chrome_dev_mode] [STDOUT] stdout: + sky_engine 0.0.99 from sdk flutter
[windows_chrome_dev_mode] [STDOUT] stdout: + source_map_stack_trace 2.1.0
[windows_chrome_dev_mode] [STDOUT] stdout: + source_maps 0.10.10
[windows_chrome_dev_mode] [STDOUT] stdout: + source_span 1.9.1
[windows_chrome_dev_mode] [STDOUT] stdout: + stack_trace 1.10.0
[windows_chrome_dev_mode] [STDOUT] stdout: + stream_channel 2.1.0
[windows_chrome_dev_mode] [STDOUT] stdout: + string_scanner 1.1.1
[windows_chrome_dev_mode] [STDOUT] stdout: + sync_http 0.3.1
[windows_chrome_dev_mode] [STDOUT] stdout: + term_glyph 1.2.1
[windows_chrome_dev_mode] [STDOUT] stdout: + test 1.21.5
[windows_chrome_dev_mode] [STDOUT] stdout: + test_api 0.4.13
[windows_chrome_dev_mode] [STDOUT] stdout: + test_core 0.4.17
[windows_chrome_dev_mode] [STDOUT] stdout: + typed_data 1.3.1
[windows_chrome_dev_mode] [STDOUT] stdout: + url_launcher 6.1.5
[windows_chrome_dev_mode] [STDOUT] stdout: + url_launcher_android 6.0.17
[windows_chrome_dev_mode] [STDOUT] stdout: + url_launcher_ios 6.0.17
[windows_chrome_dev_mode] [STDOUT] stdout: + url_launcher_linux 3.0.1
[windows_chrome_dev_mode] [STDOUT] stdout: + url_launcher_macos 3.0.1
[windows_chrome_dev_mode] [STDOUT] stdout: + url_launcher_platform_interface 2.1.0
[windows_chrome_dev_mode] [STDOUT] stdout: + url_launcher_web 2.0.13
[windows_chrome_dev_mode] [STDOUT] stdout: + url_launcher_windows 3.0.1
[windows_chrome_dev_mode] [STDOUT] stdout: + vector_math 2.1.3
[windows_chrome_dev_mode] [STDOUT] stdout: + video_player 2.2.11 (2.4.7 available)
[windows_chrome_dev_mode] [STDOUT] stdout: + video_player_platform_interface 5.1.4 (6.0.0 available)
[windows_chrome_dev_mode] [STDOUT] stdout: + video_player_web 2.0.12
[windows_chrome_dev_mode] [STDOUT] stdout: + vm_service 9.3.0
[windows_chrome_dev_mode] [STDOUT] stdout: + watcher 1.0.1
[windows_chrome_dev_mode] [STDOUT] stdout: + web_socket_channel 2.2.0
[windows_chrome_dev_mode] [STDOUT] stdout: + webdriver 3.0.0
[windows_chrome_dev_mode] [STDOUT] stdout: + webkit_inspection_protocol 1.1.0 (1.2.0 available)
[windows_chrome_dev_mode] [STDOUT] stdout: + yaml 3.1.1
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading video_player_web 2.0.12...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading video_player_platform_interface 5.1.4...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading vector_math 2.1.3...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading url_launcher_windows 3.0.1...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading url_launcher_web 2.0.13...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading url_launcher_platform_interface 2.1.0...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading url_launcher_macos 3.0.1...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading url_launcher_linux 3.0.1...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading url_launcher_ios 6.0.17...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading url_launcher_android 6.0.17...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading plugin_platform_interface 2.1.2...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading material_color_utilities 0.2.0...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading device_info_platform_interface 2.0.1...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading connectivity_platform_interface 2.0.1...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading connectivity_macos 0.2.1+2...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading connectivity_for_web 0.4.0+1...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading characters 1.2.1...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading flutter_gallery_assets 1.0.2...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading shrine_images 1.1.2...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading video_player 2.2.11...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading cupertino_icons 1.0.5...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading url_launcher 6.1.5...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading connectivity 3.0.6...
[windows_chrome_dev_mode] [STDOUT] stdout: Downloading device_info 2.0.3...
[windows_chrome_dev_mode] [STDOUT] stdout: Changed 89 dependencies!
[windows_chrome_dev_mode] [STDOUT] stderr: Building with plugins requires symlink support.
[windows_chrome_dev_mode] [STDOUT] stderr:
[windows_chrome_dev_mode] [STDOUT] stderr: Please enable Developer Mode in your system settings. Run
[windows_chrome_dev_mode] [STDOUT] stderr:   start ms-settings:developers
[windows_chrome_dev_mode] [STDOUT] stderr: to open settings.
[windows_chrome_dev_mode] [STDERR] Task failed: Executable "C:\Users\sigurdm\flutter\bin\flutter" failed with exit code 1.
[windows_chrome_dev_mode] [STDERR]
[windows_chrome_dev_mode] [STDERR] Stack trace:
[windows_chrome_dev_mode] [STDERR] package:flutter_devicelab/framework/utils.dart 94:3        fail
[windows_chrome_dev_mode] [STDERR] package:flutter_devicelab/framework/utils.dart 363:5       _execute
[windows_chrome_dev_mode] [STDERR] ===== asynchronous gap ===========================
[windows_chrome_dev_mode] [STDERR] dart:async                                                 _CustomZone.registerBinaryCallback
[windows_chrome_dev_mode] [STDERR] package:flutter_devicelab/framework/framework.dart 274:26  _TaskRunner._performTask.<fn>
[windows_chrome_dev_mode] [STDERR] package:stack_trace                                        Chain.capture
[windows_chrome_dev_mode] [STDERR] package:flutter_devicelab/framework/framework.dart 273:11  _TaskRunner._performTask
[windows_chrome_dev_mode] [STDERR] package:flutter_devicelab/framework/framework.dart 166:43  _TaskRunner.run
[windows_chrome_dev_mode] [STDERR]
[windows_chrome_dev_mode] [STDOUT] Checking for reboot
[windows_chrome_dev_mode] Process terminated with exit code 0.
Task result:
{
  "success": false,
  "reason": "Task failed: Executable \"C:\\Users\\sigurdm\\flutter\\bin\\flutter\" failed with exit code 1."
}


Finished task "windows_chrome_dev_mode"
```

**Comment by sigurdm** [comment]
Could you try running it once more?

I don't think the message you saw "pub get failed (server unavailable)" can be related to this PR - it looks more like a network issue of sorts.

**Review by christopherfujino — APPROVED** [review]
If this passes locally for you, I'll take your word for it (don't have my Windows machine today). This definitely seems like it fixed the issue the other PR got reverted for.

**Pull request merged**
