### PR TITLE
move the material_gallery/demos.dart script

### PR DESCRIPTION
**Pull request by devoncarew**
- move `material_gallery/lib/demos.dart` to `material_gallery/lib/demo/all_demos.dart`
- some minor changes to package: imports in material_gallery

I'm experimenting with making n copies of the material_gallery app, and moving demos.dart out of being an immediate child of `lib/` will make that easier.

### CODE REVIEW

**Comment by abarth** [comment]
Maybe just `demos/all.dart` ?

**Comment by abarth** [comment]
LGTM

**Comment by devoncarew** [comment]
> Maybe just demos/all.dart ?

done -

**Comment by Hixie** [comment]
This is a little awkward in that it means that all.dart doesn't include everything in the demos directory (since it doesn't include itself).

Not really sure what you mean by "making n copies" though. :-)

**Comment by devoncarew** [comment]
I'm generating a new app with material_gallery as the input - you can dial in how many copies of material gallery you want, or how many lines of code you want the result to be.

It'll be used to have a large app to measure analysis times for and for measuring the edit-refresh cycle.

**Comment by Hixie** [comment]
Fascinating.

**Pull request merged**
