### PR TITLE
Android visible password input type support

### LINKED ISSUE #31738: [Feature Request] textVisiblePassword (Android)
On Android it is possible to get a Keyboard with letters and numbers visible at the same time through the property `textVisiblePassword`

In Flutter, we use a TextField with the property `obscureText: true` to get the password behavior, so there is no `TextInputType` relative to the password field, so we can not achieve the same effect when using the `textVisiblePassword` property

## Sample

```dart
TextField(controller: textController, keyboardType: TextInputType.textWithNumber)
```

## Expected behavior

keyboard_example

### PR DESCRIPTION
**Pull request by justinmc**
## Description

Simply adds support for the [VisibleText](https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_VARIATION_PASSWORD) input type on Android.

## Related Issues

Depends on engine PR https://github.com/flutter/engine/pull/9999
Closes https://github.com/flutter/flutter/issues/31738

## Tests

None.  Is it possible to test this?

### CODE REVIEW

**Comment by justinmc** [comment]
@GaryQian This is the framework side of the engine PR you reviewed for me the other day (https://github.com/flutter/engine/pull/9999).

**Review by dnfield — CHANGES_REQUESTED** [review]
What behavior is this actually adding?  Where and how would this code be used?

Even if it's not going to be used immediately by the framework, we should have some test that uses it (even in a fake, constructed test only widget) to make sure it works and doesn't regress.

**Comment by dnfield** [comment]
I see now, this is to control the type of keyboard.

Can we have a test where we set this property and make sur ethe right thing goes through up to the dart:ui layer?

Alternatively, could we have an integration test in the devicelab that focuses on a text field with this property set and verify (screenshot? some other inspection method?) that the right keyboard shows up?  This is the kind of thing that is super easy to regress and not know about without that kind of test.

**Comment by justinmc** [comment]
@dnfield Thanks for the ideas, I went with the "dart:ui verification" path.  It turns out there's a built-in way to check the text input messages with [tester.testTextInput](https://api.flutter.dev/flutter/flutter_test/TestTextInput-class.html), so that made it really easy to test.  I think it will be more robust than a device lab test since small differences in device could cause the keyboard to look different and the test to fail.

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
It would still be nice to somewhere have an integration test of this.  This is the kind of thing that regresses and no one knows until months later :(

**Comment by justinmc** [comment]
I checked for existing image comparison tests that have the native keyboard in them and couldn't find any, so I'm going to hold off on the device lab test.  I'll keep an eye out for a better way to test this though.

**Pull request merged**
