### PR TITLE
[Discuss/Proposal/WIP] SliverFlex, SliverGroup, SliverExpanded, SliverSpacer

### PR DESCRIPTION
**Pull request by Piinks**
## Description

WIP - this is a raw prototype of the proposed functionality for discussion. There are still edge cases that need to be addressed, and _extensive_ testing. 🙂 

### Try it out!
Checkout a copy of this branch and run this demo app: https://github.com/Piinks/sliver_demos

## Related Issues

- #33137
- #16854
- #38640
- #38641
- #35753
- #18711 
- #33399 
- #38550 
- #466 
- #28158

## Tests

So many to come. 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Piinks** [comment]
cc/ @spkersten to consent to the google bot as a co-author. :)

**Comment by Piinks** [comment]
FYI @goderbauer

**Comment by spkersten** [comment]
@googlebot I consent.

**Comment by Piinks** [comment]
After some much appreciated feedback, I'm going to close this for now to make some improvements.
This may not require the framework changes proposed herein, so there is still potential for this to live outside of the framework as a package. 
Feel free to comment on this PR or any of the linked issues. I'll post an update once I've made some changes! :)

**Pull request closed without merging**
