### PR TITLE
Revert "Make tests more resilient to Skia gold failures and refactor flutter_goldens for extensive technical debt removal (#140101)"

### LINKED ISSUE #141880: Golden file testing for flutter/flutter is unreliable
https://github.com/flutter/flutter/pull/140101 introduced a regression that causes failures at head to not break the tree.
Because of this, there is no enforcement of approved/unapproved images right now for flutter/flutter.

The revert is currently blocked.

- Revert: https://github.com/flutter/flutter/pull/141814
- Blocked by https://github.com/flutter/flutter/issues/140169
  - https://github.com/flutter/flutter/pull/141427

Until resolved, contributors should consider refraining from introducing image changes. If necessary, i.e. from an engine roll, please check https://flutter-gold.skia.org/ after the change lands to ensure any new images or updated images are properly approved. Otherwise changes may cascade down to other PRs looking for approval.

We do have a safety net of sorts against regressions due to extensive golden file testing inside of Google, which is executed when Flutter rolls into Google.

### PR DESCRIPTION
**Pull request by Hixie**
Reverts https://github.com/flutter/flutter/pull/140101

That PR somehow made non-matching gold tests not fail at HEAD.

Fixes https://github.com/flutter/flutter/issues/141880
- Blocked by https://github.com/flutter/flutter/issues/140169
  - https://github.com/flutter/flutter/pull/141427

### CODE REVIEW

**Review by Piinks — APPROVED** [review]
LGTM - thank you!

**Comment by Piinks** [comment]
Looks like CI is failing in relation to the crypto dependency

**Comment by christopherfujino** [comment]
Failures would be fixed by https://github.com/flutter/flutter/pull/141864, but it's currently blocked due to an infra issue. I will push a workaround to this branch...

**Comment by christopherfujino** [comment]
I just pushed https://github.com/flutter/flutter/pull/141814/commits/df00fe3e4347aa4be5b7fba01663009ad6bd4bfc, which I hope will fix CI

**Comment by christopherfujino** [comment]
Investigating failures...

**Comment by christopherfujino** [comment]
Pushed another commit: https://github.com/flutter/flutter/pull/141814/commits/10076530c003f0baccda1ffbd4751ed7ce01bbfb

**Comment by Hixie** [comment]
We should land https://github.com/flutter/flutter/pull/141888 first to test the current system and see if we can reproduce the issue.

**Comment by Hixie** [comment]
I don't think that section really applies here, because this isn't blocking anyone else's work. The tree is green (indeed that's the problem, it was _too_ green), and we can easily keep an eye on the Skia dashboard to catch unexpected regressions while we know the system isn't fully functional.

**Pull request merged**
