### PR TITLE
Perform Gradle builds using the Gradle wrapper script

### PR DESCRIPTION
**Pull request by jason-simmons**
Run "gradle wrapper" using the installation of Gradle located on the host
in an initial build where no gradlew script is present.  Use gradlew for
subsequent builds.

See https://github.com/flutter/flutter/issues/9842

### CODE REVIEW

**Comment by jason-simmons** [comment]
@jakobr-google @mit-mit

**Comment by Hixie** [comment]
What's the status of this PR?

**Comment by Hixie** [comment]
cc @mravn-google

**Comment by mravn-google** [comment]
It's now owned by me. I'll self-assign once I start working on it.

**Comment by mravn-google** [comment]
There has been some discussion on this, see https://github.com/flutter/flutter/pull/9882.

**Comment by mravn-google** [comment]
@jason-simmons This does not appear to solve our current Gradle versioning problems. If I run `gradle wrapper` in the `android` folder of a newly created Flutter project, Gradle needs to be able to interpret my `build.gradle` file which is written for a particular version of Gradle. In my case, since I have Gradle 4.0 installed, it fails with
```
$ gradle wrapper
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mravn/apps/hej/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 7s
```
What we need, I think, is for the Gradle wrapper to be present in the correct version in our template, as already suggested in #9882.

Adding `gradle-wrapper.jar` to our template would just be following [standard practice](https://docs.gradle.org/3.3/userguide/gradle_wrapper.html#sec:wrapper_generation), even though it is a binary. GitHub itself appears to have embraced this practice, having published a standard [`.gitignore` file](https://github.com/github/gitignore/blob/master/Gradle.gitignore) that un-ignores `gradle-wrapper.jar`.

I'm looking into our reasons for not accepting #9882, such as licensing issues.

**Pull request closed without merging**
