### PR TITLE
[roll] roll to 2.10

### LINKED ISSUE #62044: Update nnbd versions to .2 for update to 2.10 Dart SDK
This will require a manual engine roll. The versions are:

```
characters: 1.1.0-nullsafety.2
collection: 1.15.0-nullsafety.2
meta: 1.3.0-nullsafety.2
typed_data: 1.3.0-nullsafety.2
vector_math: 2.1.0-nullsafety.2
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Update to a good 2.10 engine, update .2 null safety dependencies, update min SDK to 2.10

Fixes https://github.com/flutter/flutter/issues/62044#issuecomment-664680328

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Woops, windows isn't done yet

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by nturgut** [comment]
web_smoke test is passed but web_integration_tests are failing. I'm not very familiar with that test.

**Comment by jonahwilliams** [comment]
Landing on red to fix build

**Pull request merged**
