### PR TITLE
Sets textScaleFactor to 1.0 in the default Close button of Cupertino …

### LINKED ISSUE #35199: Cupertino NavBar default `Close` text shouldn't scale with the font
## Problem
If you look into the native iOS NavBar texts (such as Close, Edit, and so on) those won't scale with the font settings (thus having `textScaleFactor: 1.0`).
Currently, the _Close_ button from the bottom navigation route, is being able to scale and can't have its property overriden unless you explicitly create it yourself the leading widget). This will either add a lot of boilerplate if you want to provide the best native experience possible; or make the `Close` button smaller/bigger than the others across the system UI.

This should also be considered to the AppBar title and action buttons (both text and icon).

## Solution
A simple (and correct) solution would be to set the `CupertinoButton`'s `textScaleFactor` to `1.0` in the default `leadingContent` of the `NavBar`.
```
leadingContent = CupertinoButton(
        child: const Text(
          'Close',
          textScaleFactor: 1.0,
        ),
        padding: EdgeInsets.zero,
        onPressed: () { route.navigator.maybePop(); },
      );
```

Edit: I already PR'd a solution with #35200.

### PR DESCRIPTION
**Pull request by miguelpruivo**
Fixes #35199.

### CODE REVIEW

**Comment by LongCatIsLooong** [comment]
@miguelpruivo thank you for the pull request and the issue! However tests are required for a PR to be able to get merged. 

After testing on an iOS 12 device, it appears to me that the system text scale settings only apply to the "content" area (i.e. what we refer to in flutter as Scaffold.body). Neither tab navigation nor top navigation is affected. 

So instead of explicitly setting `textScaleFactor = 1` for the close button, I'm thinking about wrapping a `MediaQuery` with `textScaleFactor = 1` around the nav bar, or doing it in `CupertinoPageScaffold` so developers can override the `MediaQuery` for the nav bar by wrapping a different `MediaQuery` around their nav bar. Thoughts?

**Comment by miguelpruivo** [comment]
@LongCatlsLooong I was so focused on fixing the `Cancel` button that didn’t thought on preventing the app bar scaling by default, which completely makes sense.

I agree, looks like a reasonable solution. Leaving the possibility to override the text scale for users that want to implement that, but, by default, staying at 1.0 according to iOS HIG. 👍🏻

**Comment by LongCatIsLooong** [comment]
@miguelpruivo would you mind reviewing https://github.com/flutter/flutter/pull/38593?

**Comment by miguelpruivo** [comment]
@LongCatIsLooong done. Thank you for “fixing” it. 🙂

**Pull request closed without merging**
