### PR TITLE
add lang attribute to the a11y_assessments app

### PR DESCRIPTION
**Pull request by yjbanov**
Since the app is used to assess Flutter's overall accessibility, the app should follow at many guidelines as possible, including setting the `lang` attribute.

Fixes b/338044851

### CODE REVIEW

**Comment by chunhtai** [comment]
I wonder what may be the best way to automate this. Can this be added into the flutter create template? or maybe programatically added into the header from the web engine side?

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by hannah-hyj — APPROVED** [review]
LGTM

**Comment by yjbanov** [comment]
I don't think there's a similar concept in mobile Flutter, so whatever API is used for automation it would have to be web-specific. But if it's going to be web-specific, then just using `package:web` to set the value programmatically should work fine, which is already available. I'm hard-coding it into the HTML in this case, since our test app is not internationalized.

**Comment by chunhtai** [comment]
> since our test app is not internationalized.

If the app is not internationalized, wouldn't the default locale be en_US?

**Comment by yjbanov** [comment]
Ignoring the "Google testing" failure. This test app is not even used in Google.

**Pull request merged**
