### PR TITLE
resolved issue #147363

### PR DESCRIPTION
**Pull request by ujjwaltwitx**
resolves issue #147363 ( Refresh indicator not working properly when the height of headSliver is extremely large ).

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hi @ujjwaltwitx welcome! Thanks for contributing. This will need a test to verify that is works as expected, and to prevent us from regressing in the future. Can you add one?

**Review by ghost — COMMENTED** [review]
ok this seems reasonable...

**Review by ghost — COMMENTED** [review]
ok

**Comment by ujjwaltwitx** [comment]
> Hi @ujjwaltwitx welcome! Thanks for contributing. This will need a test to verify that is works as expected, and to prevent us from regressing in the future. Can you add one?

I have not added tests before. Can you guide me?

**Comment by Piinks** [comment]
> I have not added tests before. Can you guide me?

Sure! typically the code that reproduces the issue in https://github.com/flutter/flutter/issues/147363 would be used to create a test that fails as a result of the issue. With this fix, the test should pass.

There are tests you can use as examples in 
- https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/refresh_indicator_test.dart
- https://github.com/flutter/flutter/blob/master/packages/flutter/test/widgets/nested_scroll_view_test.dart

There is also page in the wiki with information on writing tests:
https://github.com/flutter/flutter/wiki/Running-and-writing-tests#for-the-framework

**Comment by Piinks** [comment]
Hey @ujjwaltwitx would you like to continue working on this change?

**Comment by ujjwaltwitx** [comment]
Sorry @Piinks I was a bit occupied with some personal stuffs. I will raise a PR as soon as I add the test.

**Comment by Piinks** [comment]
No worries, thanks for coming back to let us know.

> I will raise a PR as soon as I add the test.

I am going to close this PR for now then until you can add the tests so we can remove it from our review queue. Thank you very much for contributing, let us know when this is ready for another look! :)

**Pull request closed without merging**
