### PR TITLE
 Roll engine to f3ff83a5db71262d240aa5337a2a9a22c73c4749. (dart roll).

### PR DESCRIPTION
**Pull request by aam**

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by aam** [comment]
https://dart-review.googlesource.com/c/sdk/+/70160 (cc @jcollins-g ) caused analyzer warnings reported in https://github.com/flutter/flutter/runs/14496912: 
```
   info • Prefer declare const constructors on `@immutable` classes • packages/flutter/lib/src/widgets/platform_view.dart:53:3 • prefer_const_constructors_in_immutables
   info • Prefer declare const constructors on `@immutable` classes • packages/flutter/lib/src/widgets/scroll_view.dart:53:3 • prefer_const_constructors_in_immutables
   info • Prefer declare const constructors on `@immutable` classes • packages/flutter/lib/src/widgets/single_child_scroll_view.dart:186:3 • prefer_const_constructors_in_immutables
```
Those were incorrect lints which required adding appropriate `//ignore` directives.

**Comment by devoncarew** [comment]
@danrubel, looks like an issue related to the move to Fasta. Also cc'ing @a14n, who authored the lint.

From the docs here: http://dart-lang.github.io/linter/lints/prefer_const_constructors_in_immutables.html, it looks like we need an `@immutable` annotation on the definition of the class in order for this lint to apply. I don't see that annotation on these classes, so I'm not sure why the lint would be firing.

**Comment by devoncarew** [comment]
I filed https://github.com/dart-lang/sdk/issues/34297 to track this.

**Comment by a14n** [comment]
>I don't see that annotation on these classes, so I'm not sure why the lint would be firing.

`@immutable` applies to child classes. `Widget` (which is a parent of `AndroidView`) is annotated with `@immutable`.

**Comment by devoncarew** [comment]
It looks like the lint is correct then, and we should change the constructors over to `const`?

**Comment by aam** [comment]
> It looks like the lint is correct then, and we should change the constructors over to const?

It doesn't work as there are other constraints that prevent those constructors to be const.

**Comment by devoncarew** [comment]
OK, sounds like there are false positives with the lint, or issues where we don't actually want the constructor to be `const` even for immutable classes.

**Comment by a14n** [comment]
>It doesn't work as there are other constraints that prevent those constructors to be const.

Once https://github.com/dart-lang/sdk/issues/33408 has landed all constructors pointed out in the log could be `const`. I think we are in a transition state where CFE and Analyzer differ. /cc @bwilkerson

**Comment by a14n** [comment]
For instance:

```dart
  AndroidView({ // ignore: prefer_const_constructors_in_immutables
    Key key,
    @required this.viewType,
    this.onPlatformViewCreated,
    this.hitTestBehavior = PlatformViewHitTestBehavior.opaque,
    this.layoutDirection,
    this.gestureRecognizers = const <OneSequenceGestureRecognizer> [],
    this.creationParams,
    this.creationParamsCodec
  }) : assert(viewType != null),
       assert(hitTestBehavior != null),
       assert(gestureRecognizers != null),
       assert(creationParams == null || creationParamsCodec != null),
       super(key: key);
```

`creationParams == null` prevent const for now but will be const after the landing of https://github.com/dart-lang/sdk/issues/33408

**Comment by aam** [comment]
Thank you, @a14n . Makes sense.

**Pull request merged**
