### PR TITLE
Remove the pesto gallery demo

### LINKED ISSUE #9257: Hiding the Pesto demo from Gallery
Getting ready to update the Gallery in the public store, we noticed there are a few fidelity and performance issues with Pesto. We don't believe we can address the issues in time for the release, so we'd like to hide the Pesto demo in the meantime.

Fidelity (and some performance) issues affecting Pesto (and thus, people's perception of Flutter)

* https://github.com/flutter/flutter/issues/7709
* https://github.com/flutter/flutter/issues/7541
* https://github.com/flutter/flutter/issues/7221
* https://github.com/flutter/flutter/issues/6920
* https://github.com/flutter/flutter/issues/6742
* https://github.com/flutter/flutter/issues/5906
* https://github.com/flutter/flutter/issues/5350
* https://github.com/flutter/flutter/issues/5203
* https://github.com/flutter/flutter/issues/5045
* https://github.com/flutter/flutter/issues/5042
* https://github.com/flutter/flutter/issues/4436

### PR DESCRIPTION
**Pull request by HansMuller**
The demo's source code is still around for now.

Fixes https://github.com/flutter/flutter/issues/9257

### CODE REVIEW

**Comment by Hixie** [comment]
Is there some way we can include it but only in checked mode, so the test can still run?
These tests catch real bugs regularly.

**Comment by Hixie** [comment]
I'd also like us to bring back the calculator and other demos we've "temporarily" disabled, even if only in debug mode.

**Comment by HansMuller** [comment]
I've restored the gallery/pesto regression tests. The calculator demo is being tested although not as part of the gallery.

The point of this patch was to remove Pesto from release builds. I'd prefer to leave restoring more disabled demos to a separate PR.

**Comment by Hixie** [comment]
LGTM

At some point we may want to consider adding a "Temporarily disabled demos" section at the bottom which has Pesto and Calculator and such. This patch paves the way to do that.

**Pull request merged**
