### PR TITLE
Switch engine.merge_method back to squash

### PR DESCRIPTION
**Pull request by goderbauer**
Unfortunately, device lab does not have the capacity for merge method `rebase`. It's essentially DoSing device lab: The last engine `rebase` has been processing for over 6h now and it is still not done :(

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by gspencergoog — APPROVED** [review]

**Review by tvolkert — APPROVED** [review]

**Review by liyuqian — APPROVED** [review]
LGTM

**Comment by liyuqian** [comment]
I'm Ok to merge this PR on red tree so it will change the merge method before the auto-roller gets a green flutter-build.

**Comment by goderbauer** [comment]
Merging on red to make sure the autoroller doesn't see a green build before this goes in.

**Pull request merged**
