### PR TITLE
Update Data Table Class with Borders Like Table Widgets (#36837)

### LINKED ISSUE #36837: Update Data Table Class with Borders Like Table Widgets
Hello Guys, I would like to recommended to you is that can you please update data table class with border like table widget because when we use this for normal pivot report we face hard to read for large report or please develop new plugin for pivot report view like  for very large amount of data please.. thank you ...

### PR DESCRIPTION
**Pull request by dheerajv09**
Adds boundary and interior divisions to DataTable.

fixes #36837

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

Can you resolve the merge conflicts?

**Comment by dheerajv09** [comment]
@goderbauer  
Resolved the merge conflicts.

**Comment by goderbauer** [comment]
Looks like the analyzer is unhappy now. Can you look at the failures and fix them please? Thanks!

**Comment by goderbauer** [comment]
@dheerajv09 Do you still have plans to come back to this?

**Comment by dheerajv09** [comment]
Hi Michael Goderbauer , I have pushed a new commit to pull request but
analyzer is showing pending checks from very long time. So can you lead me
further.

**Comment by dheerajv09** [comment]
@goderbauer what to do with queued checks in analyzer.

**Comment by goderbauer** [comment]
@dheerajv09 Can you rebase this to the latest master to get the checks to pass?

**Comment by dheerajv09** [comment]
Can you please guide me.

**Review by Piinks — COMMENTED** [review]
Hi @dheerajv09! Thanks for the contribution! It looks like you will need to update your PR so we can land this change. Can you rebase with the latest from master?

**Comment by goderbauer** [comment]
Closing this PR for lack of activity. Feel free to reopen when you have time to get back to it.

**Pull request closed without merging**
