### PR TITLE
Document difference between softWrap and maxLine

### LINKED ISSUE #13631: TextOverflow.fade results in unexpected fade direction
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new FadeDemo());
}

class FadeDemo extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    var themeData = new ThemeData();
    return new MaterialApp(
        theme: themeData,
        home: new Scaffold(
          appBar: new AppBar(title: const Text('Fade Effect')),
          body: new Center(
            child: new Container(
              color: Colors.grey[300],
              width: 250.0,
              child: new Text(
                'This is a short text.',
                style: themeData.textTheme.title.copyWith(fontSize: 48.0),
                maxLines: 1,
                overflow: TextOverflow.fade,
              ),
            ),
          ),
        ));
  }
}
```
results in:

image

I was expecting it to fade out horizontally. If I set overflow to ellipsis, it works as expected and puts the ellipsis at the end.

If I turn off softwrap, fade works as expected. That's counterintuitive given that I would have expected softwrap to have no effect because of maxLines: 1.

### PR DESCRIPTION
**Pull request by paldepind**
This PR fixes #13631 through documentation as suggested in https://github.com/flutter/flutter/issues/13631#issuecomment-354902727.

Since the documentation additions rely on new screenshots this PR will be accompanied by a PR in the assets repository.

### CODE REVIEW

**Comment by paldepind** [comment]
The diagram changes are in https://github.com/flutter/assets-for-api-docs/pull/228. I suppose that PR should be merged prior to this PR.

**Comment by paldepind** [comment]
Thanks for the feedback @gspencergoog. I went back and forth between whether or not to include screenshots or a DartPad. I went with screenshots because a DartPad includes a lot of boilerplate in addition to the relevant code, because I felt the point was simple enough to capture with screenshots, and because it was easier. So I hope it's ok if we proceed with the current approach :)

**Comment by paldepind** [comment]
@gspencergoog Is it fine if we go ahead with the PR as is? :)

**Comment by gspencergoog** [comment]
Yes, we can move forward as-is.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Review by hellohuanlin — APPROVED** [review]

**Comment by paldepind** [comment]
Thanks for the merge! https://github.com/flutter/assets-for-api-docs/pull/228 should be merged as well to ensure that the illustrations used in the documentation are available :)

**Comment by gspencergoog** [comment]
> Thanks for the merge! https://github.com/flutter/assets-for-api-docs/pull/228 should be merged as well to ensure that the illustrations used in the documentation are available :)

Oh, good point.  Can you resolve the conflicts there and we can get it merged?

**Comment by paldepind** [comment]
@gspencergoog I've fixed the conflicts 👍

**Pull request merged**
