### PR TITLE
Macrobenchmark migration to e2e

### PR DESCRIPTION
**Pull request by CareF**
## Description

This is a follow up of #61509 and is to test self-driven test solutions. 

## Related Issues

N/A

## Tests

The PR itself is to test. 

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by liyuqian — COMMENTED** [review]
Adding E2E versions of all macrobenchmark perf tests at once may suddenly increase (almost double?) the workload of our devicelab. I feel it's safer to pick 1-3 macrobenchmark tests and migrate to E2E first to see its benefit over driver tests, and how much workload is added to devicelab. @godofredoc @digiter : is my concern valid, or is devicelab Ok by adding 11 devicelab tasks at once?

**Comment by liyuqian** [comment]
BTW, Ming has already added 1 macrobenchmark E2E test in https://github.com/flutter/flutter/pull/61509. So we could either continue to add E2E tests in a batch of 1-3 tasks per PR, or maybe just add all in one PR as this PR does.

This also reminds me of @flar 's suggestion earlier on why don't we run multiple benchmarks in 1 app run. With E2E and the host-independent `WidgetController` perf tests, it shouldn't be hard as we could just call `watchPerformance` multiple times with different test bodies. The only non-trivial part to figure out might be how to report multiple benchmarks properly: the single-level key-value JSON map would be insufficient. We could have a 2-level nested map instead. Cocoon may need some changes to digest that, or we can directly store metrics into [metrics_center] datastore? CC @digiter on comments about this.

[metrics_center]: https://docs.google.com/document/d/1Lx1TIDIGoWc8HVUbvh0T9NXh_dtVgwpiBDDNDaE-q5Y/edit#

**Comment by CareF** [comment]
I don't like the idea of "multiple benchmarks in 1 app run" because 

- Very often when test performance locally, we only want to run one of these tests;
- If one of these test fail (crash, not regression), running multiple tests in a single app will influence each other;
- Given we already are pushing the device memory limit (#59263), running multiple tests in a single run will increase flakiness.

**Comment by CareF** [comment]
Since I have already implemented the migration, if we decide to only add 1~3 a time, does it make sense to comment out the items in `manifest.yaml` and cancel the comment in following PRs?

**Comment by digiter** [comment]
The devicelab capacity is limited and under big pressure at the moment. I'd recommend migrating 1-3 items at a time to monitor the impact on capacity and flakiness.

Besides, I'm working on uploading benchmark result from LUCI bots to Cocoon backend. Which you might be able to reuse.

**Comment by CareF** [comment]
I commented out most new tests except for: 
- `cull_opacity_perf__e2e_summary` is already added and run from #61509.
- `multi_widget_construction_perf__e2e_summary` is designed for heavily rebuilding the widget tree for tracking the test binding overhead
- `animated_placeholder_perf__e2e_summary`, letter a, the first.

**Comment by CareF** [comment]
Mark as draft for splitting the PR to individual test case.

**Comment by flar** [comment]
> I don't like the idea of "multiple benchmarks in 1 app run" because:
> 
> * Very often when test performance locally, we only want to run one of these tests;
> * If one of these tests fail (crash, not regression), running multiple tests in a single app will influence each other;
> * Given we already are pushing the device memory limit (#59263), running multiple tests in a single run will increase flakiness.

We could offer individual tests as well as the aggregate and only have the aggregate run in the devicelab or we could enhance the drive command to specify a benchmark portion.

For crashing, they could be run on separate invocations, but share the compilation of the benchmark between them. When runnning a test I spend a couple of minutes while the task builds the test and does a large number of setup operations, then finally the bundle is launched on the phone to run a 10 second benchmark. Even with having to launch the app multiple times so that the memory pressure from one benchmark to the next and the crash potential are separated, it would be a huge savings in devicelab time.

Note that this primarily applies to the several benchmarks that are all run from the single "macrobenchmark" executable. It has more than a page of benchmarks to scroll through to trigger.

**Comment by CareF** [comment]
@flar  Thank you for the comments! It should be fairly straightforward t o put all tests into a single app for the new solution. The only blocking factor is how device lab will handle the result and make compatible with the current setup and history data.

**Comment by CareF** [comment]
Close this PR and break it down to multiple ones for each individual tests.

**Pull request closed without merging**
