### PR TITLE
Escalate `missing_required_param` hints to warnings (#8087).

### LINKED ISSUE #8087: Consider upping severity of missing required hints to warnings in analysis options.
Follow-up from: https://github.com/dart-lang/sdk/issues/28693, we should consider escalating the `MISSING_REQUIRED_PARAM` hint code to a warning (at least) in generated `.analysis_options`.

### PR DESCRIPTION
**Pull request by pq**
Fixes: #8087.

@Hixie @danrubel

### CODE REVIEW

**Review by danrubel — APPROVED** [review]
LGTM once same change has been applied to `packages/flutter/lib/analysis_options_user.yaml` (was `.analysis_options_user`)

**Comment by Hixie** [comment]
LGTM but I don't understand what difference this makes.

**Comment by pq** [comment]
> LGTM but I don't understand what difference this makes.

It makes missing required params more obvious to the user by treating them as warnings (rather than hints).

**Comment by Hixie** [comment]
So it's just about changing the colour in IDEs basically?

**Comment by pq** [comment]
Yep.  Warnings also show up in the high level "project view". For example:

screen shot 2017-02-13 at 8 55 22 am

Hints would not get that squiggle on `main.dart`.

**Comment by Hixie** [comment]
Ah. I played with IntelliJ recently and the first thing I did (literally) was to change the configuration so that all hints, warnings, lints, and errors (and other things that IntelliJ itself catches, like spelling errors) would get flagged as yellow-on-red text in the source, and then I closed the thing on the left, so it wouldn't make any difference to me... :-)

**Pull request merged**
