### PR TITLE
Fix call on null when interpolating gradient stops

### PR DESCRIPTION
**Pull request by thekeenant**

### CODE REVIEW

**Comment by Hixie** [comment]
Thanks for your contribution!

Can you add a test to make sure we don't regress this?

**Comment by thekeenant** [comment]
Sure thing! Added stops to the existing gradient lerp tests (radial and linear) since the other attributes are tested there. Does that work?

**Comment by Hixie** [comment]
Looks great, except we should add a test, not replace the existing test. :-) Just copy and paste the existing tests and add the stops in the copy, that way we test that it works without stops and with stops.

**Comment by thekeenant** [comment]
Woops, let me just create a new pull. New to this!

**Pull request closed without merging**
