### PR TITLE
Fixes physics not working when StepperType.horizontal is selected

### PR DESCRIPTION
**Pull request by thecalamiity**
## Description

Stepper's physics property is not set when StepperType.horizontal is selected. This PR adds the physics property. 

## Related Issues

Fixes [#34174]

## Tests

Added a new test to check if physics is working for vertical and horizontal stepper.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[#34714]: https://github.com/flutter/flutter/issues/34174

### CODE REVIEW

**Comment by 2FFPS** [comment]
@googlebot I signed it!

**Comment by 2FFPS** [comment]
Hey @HansMuller ! Sorry for the ping but I saw you self-requested a review. This is my first PR and I haven't got any reply in 13 days. Perhaps something is wrong with the PR? Thank you very much!

**Comment by HansMuller** [comment]
Sorry about the delay. This seems like a reasonable change, however you'll need to add a simple test that verifies that the Stepper's ListView has the expected scroll physics in this case. Should be pretty easy to check the Stepper's ListView descendant in a test. The new test just cover both the vertical and horizontal cases.

**Comment by 2FFPS** [comment]
Hey @HansMuller ! Sorry for the delay (and somehow closing the issue). Hopefully, that test looks good to you.

**Review by HansMuller — APPROVED** [review]
LGTM

I've restarted some of the tests, since the failed for internal reasons. Will land this when the tree is green. Thanks for the contribution!

**Comment by HansMuller** [comment]
I'm afraid that it will be necessary to sync up with the master and push a new commit to get this PR past the failing tests.

I submitted #64208 because sorting that much out isn't as straightforward as it should be.

**Comment by 2FFPS** [comment]
Hey @HansMuller ! Could you please tell me how to do that? Last time I tried syncing stuff, I deleted all my changes. Sorry, this whole git thing still confuses me

**Comment by dkwingsmt** [comment]
You can do this
```
git checkout master
git pull
git checkout stepper-physics-issue
git merge master
git push
```

Or if you know that the flutter/flutter remote is in, say `upstream` can do
```
# You're on stepper-physics-issue
git fetch upstream
git merge upstream/master
git push
```

**Comment by 2FFPS** [comment]
@dkwingsmt Did I do it right 😄 ?

**Pull request merged**
