### PR TITLE
Inputs no longer autofocus after input is submitted.

### PR DESCRIPTION
**Pull request by mpcomplete**
BUG=https://github.com/flutter/flutter/issues/4905

### CODE REVIEW

**Comment by mpcomplete** [comment]
Not sure it makes sense to clear the autofocus, but without it, we would always refocus the Input immediately after submitting.

**Comment by abarth** [comment]
This doesn't seem like the right solution.  @Hixie might have better ideas what to do here.

**Comment by Hixie** [comment]
I don't really understand what this is trying to do (I don't really understand the bug description either).

**Comment by mpcomplete** [comment]
When you dismiss the keyboard while focused on the Input control in the Stocks app, the Input does not appear to lose focus. The underline highlight on the Input remains. That seems like a bug.

This appears to be caused by the combination of 2 things:
1. The Input widget is unfocused when the keyboard is dismissed. However, a rebuild is not usually triggered, so there's no opportunity to update the focus highlight.
2. Even if we trigger a rebuild when dismissing the keyboard, if autofocus is true, we just end up re-focusing the same Input. So we need to rebuild without autofocusing somehow.

I thought it might be reasonable to only autofocus the Input the first time it is displayed.

**Comment by Hixie** [comment]
Adam and I discussed this and came to the following conclusions:

Requiring that the input's owner manage this is too onerous. Instead, we should give the `Focus` widget a constructor argument that decides whether or not autofocus is enabled. When it's enabled, everything works like today. When it's not, autofocus doesn't do anything. The ModalScope widget (which owns the Focus widget) would then set this bit the first time a route is built, and unset it for all subsequent frames (it would register a post-frame callback the first time to ensure it was built the second time. In practice it's already built twice anyway by the heroes code to toggle the offstage bit in the same way).

**Comment by eseidelGoogle** [comment]
Is this PR still active?

**Comment by mpcomplete** [comment]
Nope

**Pull request closed without merging**
