### PR TITLE
[flutter_tool] Use a timeout for xcode showBuildSettings

### PR DESCRIPTION
**Pull request by zanderso**
## Description

Subcommands called by the tool may hang. Subsequent invocations may then succeed. This PR adds optional named parameters to `runAsync()` and `runCheckedAsync()` to provide for the need to retry subcommands that time-out.

In particular, when xcode runs with the `-showBuildSettings` flag it may timeout and then succeed on retry. This PR updates the call site from the issue reported below to time out after one minute, and retry one time. Additionally, this PR caches the result of the `-showBuildSettings` subcommand that could not be made asynchronous since it is called from a constructor.

## Related Issues

https://github.com/flutter/flutter/issues/35988
https://github.com/flutter/flutter/issues/39141

## Tests

I added the following tests:

Added tests of timeout with retry to process_test.dart. Updated other affected tests.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
lgtm

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
This violates our style guide which says to never have timeouts because they are a source of flakes.

Are these processes destructive or idempotent? If they're idempotent, then I suggest that we change this to not kill the first process, but to show a message after a few seconds saying "This seems to be taking longer than usual" and then start a second process in parallel, to see if it returns faster, and if it does, kill the first one. If the second takes more than a minute, kill it then try a third one, etc, leaving still the first one running, in case it's just being super slow.

**Comment by Hixie** [comment]
Filed as https://github.com/flutter/flutter/issues/42265

**Pull request merged**
