### PR TITLE
[material/menu_anchor.dart] Add directional traversal to first and last menu item on web.

### PR DESCRIPTION
**Pull request by davidhicks980**
This draft PR enables the use of vertical directional traversal from a top-level overlay anchor (either a MenuAnchor or the first SubmenuButton in a MenuBar) to the first or last item of that anchor's overlay. This should partially address https://github.com/flutter/flutter/issues/119532.

Additionally, I came across (and fixed) a bug (that I introduced 😿) where aggressively pressing the arrow keys can lead to a loss of focus. I should be able to better address this issue in the coming days, but I wanted to bundle this fix because the directional traversal implementation seemed to exacerbate the problem. Let me know if this should be split out into a separate PR. Note: one negative side effect of the fix is that submenus no longer close when moving in the direction opposite of traversal. As a result, I think this qualifies as a breaking change.

Last, because of the bug fix, I had to enable DismissMenuAction whenever the root menu is open, rather than whenever the current menu is open, because the action was not being enabled even when the menu overlay was visible. I will investigate this tomorrow and add tests if appropriate.

@dkwingsmt 

Directional focus on web: 

https://github.com/user-attachments/assets/26f52867-3829-4caa-b703-f24abbceb2b1

Bug fix side effect (normally, exiting a submenu should close that submenu):

https://github.com/user-attachments/assets/6d23f32b-617d-4116-a5c0-336d57a87027

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [~] I added new tests to check the change I am making, or this PR is [test-exempt].
- [] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by dkwingsmt** [comment]
Thanks for the draft! (I'm still taking a look at the code.)

For the behavior change, unfortunately I believe we should maintain the current behavior. As described in https://www.w3.org/WAI/ARIA/apg/patterns/menubar/, the behavior of a `LeftArrow` press should be:

> When focus is in a submenu of an item in a menu, closes the submenu and returns focus to the parent menuitem.

**Comment by davidhicks980** [comment]
That makes sense. Let me see if I can think of a fix that preserves behavior.

**Comment by goderbauer** [comment]
(triage): @davidhicks980 I was wondering if you still have plans for this PR?

**Comment by davidhicks980** [comment]
@goderbauer We can close it for now depending on how RawMenuAnchor goes. I can always reopen if needed.

**Pull request closed without merging**
