### PR TITLE
[release + cherry-pick] Switching over from iOS-15 to iOS-16 in .ci.yaml. (#118807)

### PR DESCRIPTION
**Pull request by XilaiZhang**
fix post submit failures on beta hotfix release

This will run tests on new iphone11 devicelab devices which are running iOS-16.

Bug:https://github.com/flutter/flutter/issues/117237

### CODE REVIEW

**Review by itsjustkevin — APPROVED** [review]

**Review by CaseyHillers — CHANGES_REQUESTED** [review]
Do not land until we can discuss on Monday.

We should not change the devices that are being tested in release branches. Instead, we should look at reverting the infra changes to make it compatible for the release.

**Comment by XilaiZhang** [comment]
> Do not land until we can discuss on Monday.
> 
> We should change the devices that are being tested in release branches. Instead, we should look at reverting the infra changes to make it compatible for the release.

Thanks for the instructions Casey!

**Comment by CaseyHillers** [comment]
@XilaiZhang can you link to the GitHub issue here with the context why this change is needed?

**Comment by godofredoc** [comment]
> @XilaiZhang can you link to the GitHub issue here with the context why this change is needed?

\cc @yusuf-goog @jmagman

**Review by CaseyHillers — APPROVED** [review]
LGTM. CP request was formerly filed in https://github.com/flutter/flutter/issues/119029, and the necessary approvals have been added there.

**Review by yusuf-goog — APPROVED** [review]

**Pull request merged**
