### PR TITLE
Refactor ThemeData 

### PR DESCRIPTION
**Pull request by guidezpl**
I was trying to make sense of the `ThemeData` class and thought it could be improved with some categorisation of parameters and alphabetical sorting.

- Categorizes properties with comment headers to easily find all the places where they should be kept in order
  - Alphabetization used where helpful
  - Deprecated properties get their own category, and are sorted from oldest to newest
- Adds missing documentation about `platform` defining defaults for `typography` and `materialTapTargetSize`

This should help future additions and deprecations, while making it easier for developers to inspect and understand.

## Related issues
#91772

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by guidezpl** [comment]
@HansMuller I went ahead and did the whole thing. Don't ever make me do that again (kidding)

@rami-a Can you provide color (ha) into which color properties–if any–will be repurposed for material 3? #89852

**Comment by darrenaustin** [comment]
@guidezpl, sorry I didn't catch this sooner. I thought you were just updating the parameters to the default constructor. I was also working in this area with #91774 which will now likely conflict with anything you do in the rest of the file. We should coordinate so we don't step on each others changes.

As for which colors will be repurposed for M3, none of the top level color parameters in the `ThemeData` will be needed, as they are mostly just for backwards compatibility at this point. M3 will be using the colors from the colorScheme exclusively.

**Comment by darrenaustin** [comment]
> Np, please merge your change first, it'll easier for me to merge it into mine afterwards.

Will do. Unfortunately there was a revert on master that is causing a merge issue for my PR. Once I get that sorted out I will land it this morning.

**Review by rami-a — APPROVED** [review]
LGTM

**Review by darrenaustin — COMMENTED** [review]
Generally LGTM, thanks for tackling this. 

Breaking them up by functional section will hopefully make it easier for users reading the docs. However, I think this will be harder to maintain going forward than just a straight up alphabetical order.  We will need to figure out what group new properties belong to.  That said, hopefully any new properties we add at this point will probably be new component themes, or one-off temporary flags, so this may not be a big issue.

**Review by HansMuller — APPROVED** [review]
LGTM

This definitely improves readability.

**Review by darrenaustin — APPROVED** [review]
LGTM as well. This was a tedious task, thanks for taking it on.

**Comment by rydmike** [comment]
Wow, thanks @guidezpl! For us that reads ThemeData a lot this is really useful and nice! 💙

**Pull request merged**
