### PR TITLE
Add `MaterialStateTextStyle` constructor with built-in `MaterialPropertyResolver`

### LINKED ISSUE #143488: Customize floatingLabelStyle for error in InputDecorationTheme
### Use case

I want to customize my TextField entirely through themeData so I don't have to create a specific widget as a wrapper for it.

Right now my form field looks like this: 
image
image
image
image

InputDecorationTheme doesn't expose any parameters to customize textStyle of floatingLabel when validating textField with an error. I can't change the color of the floatingLabel when focused on the textField, and unfocusing it makes the label take the default dark theme error color.

image

### Proposal

Give inputDecorationTheme optional parameters focusedErrorFloatingLabelStyle and errorFloatingLabelStyle.

### PR DESCRIPTION
**Pull request by nate-thegrate**
`InputDecorationTheme` currently gives several convenient options for customizing the border:

```dart
final inputDecorationTheme = InputDecorationTheme(
  errorBorder: border1,
  focusedBorder: border2,
  focusedErrorBorder: border3,
  disabledBorder: border4,
  enabledBorder: border5,
);
```

Conversely, the `labelStyle` documentation recommends writing your own `MaterialStatePropertyResolver` to accomplish the same thing.

<br><br>

This pull request fixes #143488. Originally, I thought about just adding two parameters as requested, but I wanted to cover more use cases:

```dart
const inputDecorationTheme = InputDecorationTheme(
  labelStyle: TextStyle(color: Colors.orange),
  focusedLabelStyle: TextStyle(color: Colors.orangeAccent),
  disabledLabelStyle: TextStyle(color: Colors.grey),
  errorLabelStyle: TextStyle(color: Colors.red),
  errorFocusedLabelStyle: TextStyle(color: Colors.redAccent),
  floatingLabelStyle: TextStyle(color: Colors.orange),
  focusedFloatingLabelStyle: TextStyle(color: Colors.orangeAccent),
  disabledFloatingLabelStyle: TextStyle(color: Colors.grey),
  errorFloatingLabelStyle: TextStyle(color: Colors.red),
  errorFocusedFloatingLabelStyle: TextStyle(color: Colors.redAccent),
);
```

Having all these extra parameters would give easier control over input label appearance, but honestly this is awful to look at.

Instead, this pull request adds a `MaterialStateTextStyle` factory constructor that doesn't require writing out a `MaterialPropertyResolver`.

```dart
const inputDecorationTheme = InputDecorationTheme(
  labelStyle: MaterialStateTextStyle.fromStyles(
    normal: TextStyle(color: Colors.orange),
    focused: TextStyle(color: Colors.orangeAccent),
    disabled: TextStyle(color: Colors.grey),
    error: TextStyle(color: Colors.red),
    focusedError: TextStyle(color: Colors.redAccent),
  ),
  floatingLabelStyle: MaterialStateTextStyle.fromStyles(
    normal: TextStyle(color: Colors.orange),
    focused: TextStyle(color: Colors.orangeAccent),
    disabled: TextStyle(color: Colors.grey),
    error: TextStyle(color: Colors.red),
    focusedError: TextStyle(color: Colors.redAccent),
  ),
);
```

<br>

#### before:
```dart
TextField(
  style: MaterialStateTextStyle.resolveWith((Set<MaterialState> states) {
    if (states.contains(MaterialState.disabled)) {
      return const TextStyle(color: Colors.red);
    }
    return const TextStyle(color: Colors.blue);
  }),
)
```

#### after:
```dart
TextField(
  style: const MaterialStateTextStyle.fromStyles(
    normal: TextStyle(color: Colors.blue),
    disabled: TextStyle(color: Colors.red),
  ),
)
```

<br>

### Demo

MaterialStateTextStyle

<br>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Review by justinmc — COMMENTED** [review]
I worry that this `.fromStyles` constructor is orthogonal to the pattern of MaterialStateProperty. Before MaterialStateProperty existed, Flutter often had long lists of parameters kind of like this (mentioned in [this Decoding Flutter video](https://youtu.be/CylXr3AF3uU?si=hFJur9HYpYXXNyIp&t=43)). This PR feels like we're going back to that, even though it does make some things more convenient.

Maybe instead of bringing this into the framework, we should encourage users to extend MaterialStateTextStyle (and others) in their own codebases if it's convenient?

CC @QuncCccccc, I think we were talking about this subject a week or two ago.

**Comment by nate-thegrate** [comment]
@justinmc thanks for linking that video—really informative and gave a great explanation of the MaterialStateProperty rationale.

I also received some helpful advice from @QuncCccccc in a [previous PR](https://github.com/flutter/flutter/pull/143802#pullrequestreview-1897245149). I thought that it would be appropriate to switch to a factory implementation, but perhaps we should just avoid implementing this constructor altogether.

**Review by MitchellGoodwin — COMMENTED** [review]
Echoing Justin, I do like what this code is doing, but when it comes to code that deals with swapping themes like this, we get feedback that developers feel like they need to either reverse engineer what our code is doing, or take the time to make designs for every possible parameter in order to make sure some weird side effect doesn't happen if they only provide some of the parameters. Which makes it not as smooth to get an app up and running. Letting them extend off of MaterialState themselves when they are ready to scale up in complexity helps avoid that.

**Comment by nate-thegrate** [comment]
It's not a huge deal whether `.fromStyles()` is stored in the Flutter codebase or just in my personal projects, so I'm fine with maintaining status-quo.

I have a few more thoughts I'd like to share. I'll leave this PR open for a few more days to allow further discussion; let's plan on either merging or deleting this branch within the next week.

<br>

<br>

User feedback is super valuable but is also prone to sampling bias: someone who's having problems is much more likely to reach out than someone who's not having problems.

I personally haven't found it difficult to use theme-swapping widgets, whether they're implemented using MaterialStateProperty classes or not.

And unlike `enabledBorder`/`disabledBorder`/`errorBorder`/`focusedErrorBorder`, this proposed change has all the configuration for a given property grouped together.

```dart
floatingLabelStyle: MaterialStateTextStyle.resolveWith((states) {
  if (states.contains(MaterialState.error)) {
    if (states.contains(MaterialState.focused)) {
      return const TextStyle(fontWeight: FontWeight.bold);
    }
    return const TextStyle(color: Colors.red);
  } else if (states.contains(MaterialState.focused)) {
    return const TextStyle(fontWeight: FontWeight.bold);
  }
  return const TextStyle(color: Colors.black87);
}),
```

```dart
floatingLabelStyle: const MaterialStateTextStyle.fromStyles(
  normal: TextStyle(color: Colors.black87),
  focused: TextStyle(fontWeight: FontWeight.bold),
  error: TextStyle(color: Colors.red),
  focusedError: TextStyle(color: Colors.redAccent),
),
```

These two snippets produce the same runtime behavior, and when I look at the `.fromStyles()` constructor, it takes less time for me to understand what's going on.

<br>

Much like the Container widget's `build()` method, this constructor's `resolve()` method aims to combine each parameter in a logical and intuitive way, but it's a suboptimal use of computing resources when most of the properties aren't set.

If half of developers like using `Container` and the other half think it's too confusing/inefficient, it might make sense to include it in the framework—this way it can be used, and everyone still has the option to implement custom widgets tailored to their needs.

In my mind, the same concept applies here.

<br>

<br>

My hope is that long parameter lists such as `enabledBorder`/`disabledBorder`/`errorBorder`/`focusedErrorBorder` will eventually be deprecated in favor of Material state classes.

Currently, I see very little downside to having both `.resolveWith()` and `.fromStyles()` as constructor options.

**Comment by MitchellGoodwin** [comment]
> User feedback is super valuable but is also prone to sampling bias: someone who's having problems is much more likely to reach out than someone who's not having problems.
> I personally haven't found it difficult to use theme-swapping widgets, whether they're implemented using MaterialStateProperty classes or not.

That's very true. We get conflicting feedback on MaterialState: both that it's intimidating to use, and that there should be more of it. [I have a PR](https://github.com/flutter/flutter/pull/142151) sitting that actually moves MaterialState out of Material to make it available to the broader framework, but there's a disagreement on that PR about whether that should happen which we are still talking through.

I think you bring up good points. If we are already asking people to look at using `.resolveWith()` maybe giving them access to `fromStyles` would possibly streamline things. And the ability to umbrella the styles under one property is nice.

I'll look at this more.

**Comment by nate-thegrate** [comment]
Now that a week has passed, I believe it's time to close the PR. I won't delete this branch from my fork, in case we want to pick it back up in the future.

**Comment by justinmc** [comment]
Thanks, it sounds like this is overall issue of MaterialStateProperty is still up for debate, so this may end up being revisited.

**Pull request closed without merging**
