### PR TITLE
Update body1 and body2 in Material Typography 2018

### LINKED ISSUE #38904: TextTheme docs on Material Design 2018 are wrong.
The `TextTheme` docs [here](https://api.flutter.dev/flutter/material/TextTheme-class.html) say that:

- The 2018 spec `body1` has `16.0` font size,  `normal` weight and `0.5` spacing.
- The 2014 spec `body1` has `14.0` font size,  `normal` weight and `0.0` spacing.
- The 2018 spec `body2` has `14.0` font size,  `normal` weight and `0.25` spacing.
- The 2014 spec `body2` has `14.0` font size,  `medium` weight and `0.0` spacing.

So basically (and messy IMHO) accoding to the table, `body1 2018` should be referenced as `body2` and `body2 2018` should be referenced as `body1`.

Then I created my `ThemeData` like this:

```dart
ThemeData(
   ...
  typography: Typography(
    platform: Theme.of(context).platform,
    englishLike: Typography.englishLike2018,
    dense: Typography.dense2018,
    tall: Typography.tall2018,
  ),
),
```

And inspecting the results of `body1`:

image

And `body2`:

image

We can see the framework is getting `body1 2018` as `body1` and `body2 2018` as `body2`, so either the docs are wrong or the implementation is (O I got something wrong here).

### PR DESCRIPTION
**Pull request by harryterkelsen**
## Description

Updates `bodyText1` and `bodyText2` (and `button`) styles in the Material 2018 Typography object to match the Material Typography spec: https://material.io/design/typography/the-type-system.html#

## Related Issues

Fixes https://github.com/flutter/flutter/issues/38904

## Tests

I updated `material/typography_test.dart` to run tests which were commented out.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by willlarche** [comment]
Thank you!

**Review by Piinks — COMMENTED** [review]
It looks like we may have overlapping work here with #47918, @HansMuller was this also a potential breaking change?

**Comment by HansMuller** [comment]
We haven't  pursued this change yet because it will break existing layouts and golden image tests.

**Comment by Piinks** [comment]
It looks like the changes to body1 and body2 landed in #49756, but this adds tests _and_ also updates the button typography. @HansMuller is this ok to land now?

**Comment by HansMuller** [comment]
@Piinks, thanks for the reminder. We'll need to test the impact of landing the button text style's letterSpacing change first. I will run the test.

**Comment by HansMuller** [comment]
This PR updates the `TextTheme.button.letterSpacing` from 0.75 to 1.25 per spec  https://github.com/flutter/flutter/pull/59008

The PR's description also shows how to restore the original `letterSpacing` value.

**Comment by HansMuller** [comment]
I'm going to close this PR per https://github.com/flutter/flutter/pull/51513#issuecomment-640965394.

@hterkelsen - sorry that it's taken so long!

**Pull request closed without merging**
