### PR TITLE
[documentation] Fix `AnimatedSize` example

### LINKED ISSUE #82619: AnimatedSize interactive sample not working
https://api.flutter.dev/flutter/widgets/AnimatedSize-class.html

```
Error compiling to JavaScript:
/tmp/dartpadEUAQEP/lib/bootstrap.dart: Warning: Interpreting this as package URI, 'package:dartpad_sample/bootstrap.dart'.
/tmp/dartpadEUAQEP/lib/main.dart:57:28: Error: Required named parameter 'vsync' must be provided.
        child: AnimatedSize(
                           ^
flutter-sdk/packages/flutter/lib/src/widgets/animated_size.dart:56:9: Context: Found this candidate, but the arguments don't match.
  const AnimatedSize({
        ^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by TahaTesser**
`AnimatedSize` example is missing `vsync`.

Go to https://api.flutter.dev/flutter/widgets/AnimatedSize-class.html

Modify the example to make it work, add `vsync: this,`
```console
        child: AnimatedSize(
          vsync: this,
          curve: Curves.easeIn,
          duration: const Duration(seconds: 1),
          child: FlutterLogo(size: _size),
        ),
```

fixes https://github.com/flutter/flutter/issues/82619

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by Piinks — APPROVED** [review]
LGTM! 🎉

**Comment by TahaTesser** [comment]
Actually, `vsync` is deprecated now https://github.com/flutter/flutter/pull/81067
So the change is not required. looks like flutter api's dartpad hasn't recevied these changes even in master docs
https://master-api.flutter.dev/flutter/widgets/AnimatedSize-class.html

**Comment by Piinks** [comment]
Ooh. Yeah, I think this is because Dartpad only runs off of the stable channel.

**Comment by TahaTesser** [comment]
@Piinks 
When I created PR thinking it is not fixed in master API docs but later realized it. I think master API docs should use the master channel so code sample run when changes are made in the API itself

**Pull request closed without merging**
