### PR TITLE
fix: Removed helper method from Scaffold

### LINKED ISSUE #99712: Remove unnecessary helper method that returns a widget
The `Scaffold` implementation uses a function to return a `Widget` [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/scaffold.dart#L3303-L3312) which is both:

  - Not needed, because the function is used only once (in the `build` method) and nowhere else
  - Using functions to return widgets is a bad practice as stated by the official docs [here](https://api.flutter.dev/flutter/widgets/StatefulWidget-class.html), [here](https://docs.flutter.dev/perf/rendering/best-practices#controlling-build-cost) and [here](https://www.youtube.com/watch?v=IOyq-eTRhvo).

This

```dart
child: _wrapBottomSheet(
  BottomSheet(
    ...
  ),
),
```

should become

```dart
child: Semantics(
  container: true,
  onDismiss: close,
  child:  NotificationListener<DraggableScrollableNotification>(
    onNotification: extentChanged,
    child: BottomSheet(
      ...
    ),
  ),
);

### PR DESCRIPTION
**Pull request by albertodev01**
This PR fixes https://github.com/flutter/flutter/issues/99712 by replacing a helper method with an actual widget inside the `build` method

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by Renzo-Olivares** [comment]
@albertodev01 LGTM could you request a text-exemption from @Hixie on Discord. Thank you!

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

**Review by Piinks — APPROVED** [review]
LGTM - it looks like the Google testing shard is stuck. Can you update your branch with the latest from master and push to refresh? Thank you!

**Comment by Piinks** [comment]
Hey @albertodev01 it looks like this needs to be rebased rather than merged.

**Pull request merged**
