### PR TITLE
FlutterExtension: make fields non-static

### PR DESCRIPTION
**Pull request by bartekpacia**
There's no issue for this PR. I can create one if requested.

## Summary

This PR makes public fields of `FlutterExtension` non-static. The aim is to make migrating from Gradle Groovy DSL to Gradle Kotlin DSL easier for Flutter developers, because...

### Without this PR

**android/app/build.gradle.kts**

```kotlin
plugins {
    id "com.android.application"
    id "dev.flutter.flutter-gradle-plugin"
}

android {
    namespace = "io.flutter.examples.hello_world"
    compileSdk = FlutterExtension.compileSdkVersion

    defaultConfig {
        applicationId = "io.flutter.examples.hello_world"
        minSdk = FlutterExtension.minSdkVersion
        targetSdk = FlutterExtension.targetSdkVersion
        // ...
    }
}
// ...
```

Groovy and Java allow accessing static fields of a class through its instance, but Kotlin is being more "correct" and disallows that.

### With this PR

Thanks to this PR, the user won't have to replace `flutter` with FlutterExtension in some places, thus decreasing possible confusion.

```kotlin
plugins {
    id "com.android.application"
    id "dev.flutter.flutter-gradle-plugin"
}

android {
    namespace = "io.flutter.examples.hello_world"
    compileSdk = flutter.compileSdkVersion

    defaultConfig {
        applicationId = "io.flutter.examples.hello_world"
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        // ...
    }
}
// ...
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Comment by bartekpacia** [comment]
No tests are needed for this, since build of any Flutter app (that has `build.gradle.kts` which uses `flutter.minSdkVersion`) will start failing if this change gets reverted.

**Comment by reidbaker** [comment]
> No tests are needed for this, since build of any Flutter app (that has `build.gradle.kts` which uses `flutter.minSdkVersion`) will start failing if this change gets reverted.

Let me state this differently. No New tests are needed since the existing tests will fail if this is reverted.

**Comment by reidbaker** [comment]
If nothing breaks in customer tests then this works for me.

**Review by reidbaker — APPROVED** [review]

**Comment by bartekpacia** [comment]
> Let me state this differently. No New tests are needed since the existing tests will fail if this is reverted.

That's right. Thanks for clarifying:)

**Comment by bartekpacia** [comment]
This is a tiny bit more complex since the first `build.gradle.kts` will be added to the Flutter repo in https://github.com/flutter/flutter/pull/140115. But I already tested it locally and it works, no breackage. Anyway if something blows up just hit me up and I'll fix stuff.

**Pull request merged**
