### PR TITLE
Mark `Linux flutter_gallery__image_cache_memory` as flaky.

### PR DESCRIPTION
**Pull request by harryterkelsen**
Marks this test as flaky.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by zanderso** [comment]
This seems a little aggressive to me. The benchmark is below the 2% threshold for the last 15 days, and has only flaked twice in the last 60+ days. My understanding of the flaky test policy is that we would only be escalating and marking flaky when tests are above the 2% threshold. @keyonghan

**Comment by keyonghan** [comment]
> This seems a little aggressive to me. The benchmark is below the 2% threshold for the last 15 days, and has only flaked twice in the last 60+ days. My understanding of the flaky test policy is that we would only be escalating and marking flaky when tests are above the 2% threshold. @keyonghan

Thanks for bringing this to my attention.

Yeah, it is true the ratio is below 2%, but this is expected per go/reduce_flutter_flakiness.

In addition to tests above 2% (for which we will file a P1 bug), we also track tests below 2%. For the latter case, we target on the most flaky test (for which we will file a P2 bug). Based on the past two weeks, `Linux flutter_gallery__image_cache_memory` is the top 1 test (<2%) with 1.41%. Though it happens only twice in the past 60 days, these two flaky cases happened in the past two weeks and contributed to the 1.41% ratio. I believe this does catch some flake issue, maybe due to a recent change?

The main reason to file the P2 bug and mark the test as flaky is to make sure we always have flaky issues to work on, and reduce the flakiness hidden in the tree, and keep the tree further more green.

But overall, we are still on the way to improve the process to reduce flakiness. If over a couple of weeks, tests are stably below 2%, it may suggest a time to adjust the SLO 2%.

/cc @Hixie @godofredoc for any comments.

**Comment by Hixie** [comment]
Our eventual goal is to have 0% flakiness. We should expect the threshold at which we care about flakiness to go down over time.

**Comment by zanderso** [comment]
Lowering the threshold over time sgtm. Lowering it while we have still tests marked flaky due to being above a higher threshold seems premature. That is, IIUC, the procedure is saying that we should lower the threshold before we've been successful at a higher threshold, which seems like it could be problematic.

**Comment by keyonghan** [comment]
> Lowering the threshold over time sgtm. Lowering it while we have still tests marked flaky due to being above a higher threshold seems premature. That is, IIUC, the procedure is saying that we should lower the threshold before we've been successful at a higher threshold, which seems like it could be problematic.

That's a good point. The main reason we track the top 1 below SLO is to make sure we have flaky issues to work on. 
I guess we can skip this part but only focus on ones above SLO to make things simple and clear.
When things get stable, such as no new flaky issues (based on existing SLO) for 2~3 weeks, we can adjust SLO to a lower value and refresh the process.
/cc @chunhtai

**Comment by chunhtai** [comment]
It looks like some of the flaky test should be marked as not flaky since their flake ratio has dropped, I am working on making the script to do that.

> When things get stable, such as no new flaky issues (based on existing SLO) for 2~3 weeks

Things will start to get volatile if the flakes all drop below the 2% threshold because the top most flaky test below the threshold is likely to change every week. I think we should use that as the signal. It has been like this for 2 weeks now.

**Comment by hterkelsen** [comment]
As of yesterday it was in the Flutter Gardener playbook (go/flutter-gardener) to make a PR for the flakiest test, but that was removed earlier today.

Should I abandon this PR now?

**Comment by keyonghan** [comment]
> As of yesterday it was in the Flutter Gardener playbook (go/flutter-gardener) to make a PR for the flakiest test, but that was removed earlier today.
> 
> Should I abandon this PR now?

Yes, please. We will give it some time before we mark the test flaky based on some new SLO number.
Sorry for the inconvenience.

**Pull request closed without merging**
