### PR TITLE
Update packages + fix tests for javascript mime change

### PR DESCRIPTION
**Pull request by DanTup**
The first commit is the result of running `flutter update-packages --force-upgrade` and the second commit fixes two failin tests (which prevented the bot from rolling in https://github.com/flutter/flutter/pull/118412) which are caused by changes in `package:mime` to use `text/javascript` instead of `application/javascript`:

See https://github.com/dart-lang/mime/pull/76.
See https://datatracker.ietf.org/doc/html/rfc9239.

> This document defines equivalent processing requirements for the various script media types. The most widely supported media type in use is `text/javascript`; all others are considered historical and obsolete aliases of `text/javascript`.

Note: There are some additional places in the Flutter codebase that use `text/javascript` that I did not update in this PR because I wanted it to be the minimum required to roll the packages. If it makes sense, I can also update them (here, or in another PR).

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by DanTup** [comment]
@christopherfujino there are failures here I can't repro locally. Have you seen these before? (the first is a timeout so maybe it's a flake, I'm not sure):

```
01:23 +2571 ~3 -1: test/general.shard/android/android_device_start_test.dart: AndroidDevice.startApp allows release builds on TargetPlatform.android_arm64 [E]                                         
  TimeoutException after 0:00:02.000000: Test timed out after 2 seconds.
  dart:isolate  _RawReceivePort._handleMessage
01:23 +2571 ~3 -1: test/general.shard/android/android_gradle_builder_test.dart: gradle build build aar uses selected local engine with x86 ABI                                                         
To run this test again: /tmp/flutter sdk/bin/cache/dart-sdk/bin/dart test test/general.shard/android/android_device_start_test.dart -p vm --plain-name 'AndroidDevice.startApp allows release builds on TargetPlatform.android_arm64'
01:23 +2571 ~3 -2: test/general.shard/android/android_device_start_test.dart: AndroidDevice.startApp allows release builds on TargetPlatform.android_arm64 [E]                                         
  Expected: a fake process manager with no remaining expectations
    Actual: <Instance of '_SequenceProcessManager'>
     Which: has remaining expectations:
            [adb, -s, 1234, shell, getprop]
            [adb, -s, 1234, shell, am, force-stop, --user, 10, FlutterApp]
            [adb, -s, 1234, shell, pm, list, packages, --user, 10, FlutterApp]
            [adb, -s, 1234, install, -t, -r, --user, 10, app-debug.apk]
            [adb, -s, 1234, shell, echo, -n, , >, /data/local/tmp/sky.FlutterApp.sha1]
            [adb, -s, 1234, shell, -x, logcat, -v, time]
            [adb, -s, 1234, shell, am, start, -a, android.intent.action.MAIN, -c, android.intent.category.LAUNCHER, -f, 0x20000000, --ez, enable-dart-profiling, true, --ez, enable-software-rendering, true, --ez, skia-deterministic-rendering, true, --ez, trace-skia, true, --es, trace-allowlist, bar,baz, --es, trace-skia-allowlist, skia.a,skia.b, --ez, trace-systrace, true, --ez, endless-trace-buffer, true, --ez, dump-skp-on-shader-compilation, true, --ez, cache-sksl, true, --ez, purge-persistent-cache, true, --ez, enable-impeller, true, --ez, enable-checked-mode, true, --ez, verify-entry-points, true, --ez, start-paused, true, --ez, disable-service-auth-codes, true, --es, dart-flags, foo,--null_assertions, --ez, use-test-fonts, true, --ez, verbose-logging, true, --user, 10, FlutterActivity]
  package:test_api                                                 expect
  test/general.shard/android/android_device_start_test.dart 123:7  main.<fn>
```

Locally:

```
✓ gradle build doesn't indicate how to consume an AAR when printHowToConsumeAar is false
✓ gradle build Verbose mode for AARs includes Gradle stacktrace and sets debug log level
✓ gradle build gradle exit code and stderr is forwarded to tool exit
✓ gradle build build apk uses selected local engine with arm32 ABI
✓ gradle build build apk uses selected local engine with arm64 ABI
✓ gradle build build apk uses selected local engine with x86 ABI
✓ gradle build build apk uses selected local engine with x64 ABI
✓ gradle build honors --no-android-gradle-daemon setting
✓ gradle build build aar uses selected local engine with arm32 ABI
✓ gradle build build aar uses selected local engine with x64 ABI
✓ gradle build build aar uses selected local engine with x86 ABI
✓ gradle build build aar uses selected local engine on x64 ABI
```

**Comment by christopherfujino** [comment]
Not sure, but I'm just re-running this as it is only failing on cirrus, and not LUCI.

**Comment by christopherfujino** [comment]
Re-run [here](https://cirrus-ci.com/task/5935284999684096)

**Comment by DanTup** [comment]
Cool, thanks! Need a review to merge :-)

**Review by bkonyi — APPROVED** [review]

**Pull request merged**
