### PR TITLE
Conditionally apply clipping in StretchingOverscrollIndicator

### PR DESCRIPTION
**Pull request by Piinks**
Internal b/200130013

This updates the stretching overscroll indicator to only apply a clip when stretching, and only then if the viewport dimension is less than the screen size in the main axis. This is because if the viewport fills the whole screen, overflow is not an issue.

Ideally it would be even more performant to just set the clip behavior to Clip.none in that case, but ClipRect does not allow this behavior.

It also removes the indicator from text fields, confirmed the native behavior does not apply either the glow or the stretch in these cases.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/91389

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/91389

**Review by justinmc — APPROVED** [review]
LGTM 👍

**Comment by Hixie** [comment]
What if the overscroll indicator is the size of the screen, but is itself in a transform that shrinks it so that the bottom of the widget does not coincide with the bottom of the screen? or if the widget is in a stack being animated around?

**Pull request merged**
