### PR TITLE
Flutter Migrate

### PR DESCRIPTION
**Pull request by GaryQian**
This PR adds a `flutter migrate <action>` command.

To use the migrate tool:

- Run `flutter migrate start --verbose`
- Fix conflicts found in the `<project>/migrate_working_dir`.
- Run `flutter migrate apply` to apply the changes and clean up the working dir.

Subcommands:
- `flutter migrate start`: Computes the migration and outputs changes into a working directory
- `flutter migrate apply`: Checks the working directory  conflicts are resolved and applies the changes to the project.
- `flutter migrate abandon`: Deletes the current working directory and active migration.
- `flutter migrate status`: Print the files that are slated to be changed as well as any conflicted files that need manual merging.

Notes on testing:

The migration tool requires full apps created with past flutter versions. This can be done two ways: a test fixture copy of pre-generated apps or cloning old versions of flutter and calling create on them after building the tool. The fixture method is much faster than the clone and create way.

### CODE REVIEW

**Comment by GaryQian** [comment]
@blasten You are welcome to take a look/try it out. But heads up, the robustness still needs a lot of work. This works nicely for apps that were generated with a previous stable version as the fallback base commit discovery isn't quite fully fleshed out yet.

**Comment by GaryQian** [comment]
cc @jmagman @hellohuanlin This should be in a working-enough state to try out. Best way to see how it works cleanly is to create a new project with an old version of flutter, then run the migrate tool on it.

I'd be interested in if there are any ios specific issues/files/edge cases that should be handled.

**Comment by GaryQian** [comment]
@jmagman I am seeing that the migration tool is finding merge conflicts when attempting to merge modern versions of ios/Runner.xcodeproj/project.pbxproj with old versions. This file seems to be a machine-handled file that is quite long and unwieldy. Fixing ~6 merge conflicts in this file does not seem like a good user experience.

Do you have any context on how this file changes over time, and the risk of breaking the file either due to a bad merge or it becoming outdated? Is it something we can choose to not handle and xcode will update it for us through context?

**Comment by GaryQian** [comment]
Ok, thanks for the explanation/advice. I think for now, we can just skip that file and have the user own it.

Currently, I definitely cannot guarantee we can fully handle the file, and manually resolving conflicts in it sounds very risky indeed. I will do some testing to see if not migrating that file can cause iOS build issues.

**Review by jmagman — COMMENTED** [review]
Once you're satisfied with this change I recommend breaking this up into smaller reviews to get thorough feedback.

**Comment by christopherfujino** [comment]
> Once you're satisfied with this change I recommend breaking this up into smaller reviews to get thorough feedback.

@GaryQian per this comment, it sounds like you're not really going to land this, but instead smaller incremental changes? Given this, I am going to mark this a draft so it doesn't show up in PR review. Feel free to mark ready for review if I am mistaken.

**Comment by GaryQian** [comment]
Yeah, feel free to mark as draft. Ive already broken this up, and am using this as a master reference

**Comment by GaryQian** [comment]
Superseded by https://github.com/flutter/flutter/pull/100284

**Pull request closed without merging**
