### PR TITLE
Add sample code to RelativePositionedTransition

### PR DESCRIPTION
**Pull request by ny927**
## Description

RelativePositionedTransition didn't have sample code, so I added it.
Reference: https://api.flutter.dev/flutter/widgets/RelativePositionedTransition-class.html

## Related Issues

N/A

## Tests

N/A. Only the doc changed.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Comment by goderbauer** [comment]
Before we review this in-detail: Can you please fix the error reported by the analyzer: https://github.com/flutter/flutter/pull/63940/checks?check_run_id=993030758

Thanks.

**Comment by ny927** [comment]
@goderbauer 
I fixed the error. Thank you for checking.

**Review by Piinks — APPROVED** [review]
Welcome @ny927! This LGTM, thank you for the contribution! 🎉

**Comment by Piinks** [comment]
Hi @ny927 can you update your branch with the latest from master? That should resolve the failing check here.

**Comment by ny927** [comment]
@Piinks I have updated my branch. Thanks!

**Comment by Piinks** [comment]
Thank you so much @ny927, it looks like it will need another update due to https://github.com/flutter/flutter/issues/64723
Sorry about that. We really appreciate your work on this!

**Comment by ny927** [comment]
@Piinks Sorry for late reply. I updated my branch.

**Comment by lanistor** [comment]
The sample code is no longer be useful, because `as Animation<Rect>` will throw error with nullsafe.

**Pull request merged**
