### PR TITLE
Reland "Dsiable CPU/GPU measurement on BackdropFilter test (#41736)"

### PR DESCRIPTION
**Pull request by liyuqian**
Reverts flutter/flutter#41780

The attempted revert doesn't fix the problem, so we'll reland.

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by liyuqian** [comment]
Merge on red to reduce potential flakiness.

**Comment by Hixie** [comment]
Please avoid "revert revert", see https://github.com/flutter/flutter/wiki/Tree-hygiene#avoid-revert-revert-revert-revert-fix-foo-commit-messages

**Comment by liyuqian** [comment]
Oops, I forgot to copy/paste the PR title while merging... Will remember to double check next time. Meanwhile, does Github have an option to automatically use the PR title as the merge commit title, instead of just using the first commit's title?

**Pull request merged**
