### PR TITLE
Drop metrics_center

### PR DESCRIPTION
**Pull request by dnfield**
This package is published to pub. It should be in the `flutter/packages` repo.

Main motivator for this right now is that it depends on googleapis_auth, which transitively depends on other things that are making it difficult to roll NNBD deps.

This has no impact on the repo currently, since the package is vended from pub.

### CODE REVIEW

**Review by liyuqian — APPROVED** [review]
LGTM

**Comment by zanderso** [comment]
It looks like this PR is doing several different things including an engine roll. Can this be split apart into separate changes?

**Comment by zanderso** [comment]
Nevermind. I think github was showing me an old commit.

**Comment by dnfield** [comment]
@zanderso - I think I'm missing something. I only see deleting `dev/benchmarks/metrics_center`.

**Comment by dnfield** [comment]
Not waiting for google testing since this code is not imported into google.

**Pull request merged**
