### PR TITLE
Add parameter for leak tracking to testWidgets.

### PR DESCRIPTION
**Pull request by polina-c**
This PR has G3Fix with cl/580932075, to add dependency on leak tracker to build in G3.

Reincarnation of https://github.com/flutter/flutter/pull/137203
Contributes to https://github.com/flutter/flutter/issues/135856
Prerequisite: leak tracker is up-to-date in G3 (done).

Next steps:
1. Update leaky tests to set leak tracking off (with just added parameter)
2. Start using the parameter for leak tracking (https://github.com/flutter/flutter/pull/138057)
3. Replace `testWidgetsWithLeakTracking` with `testWidgets`.

### CODE REVIEW

**Comment by polina-c** [comment]
Google Testing fails because dependency is not added to G3 build yet. When I try to add it in G3, presubmit fails, because the dependency is not used yet. What is right sequence?
Should I ignore google testing here or add dependency in G3 and ignore unused dependency somehow?

**Comment by goderbauer** [comment]
Why does this PR exist? Why is it not enough to just do https://github.com/flutter/flutter/pull/138057/files?

**Comment by polina-c** [comment]
> Why does this PR exist? Why is it not enough to just do #138057?

Because, before merging #138057 we need to update all leaking tests to have leak tracking off, that requires this parameter.

**Comment by polina-c** [comment]
Google testing succeeded: https://critique.corp.google.com/cl/582106273

**Comment by polina-c** [comment]
@goderbauer , addressed your comments. Can you lgtm?

**Comment by goderbauer** [comment]
Can you please get the PR that removes this hack ready for submission before we submit this so we keep the time this hack exists to a minimum? Presumably, that would be https://github.com/flutter/flutter/pull/138057

Leak tracking has already accumulated a lot of technical debt in our code base, I am wary to add more to that pile.

**Pull request closed without merging**
