### PR TITLE
Update flutter.gradle, shouldShrinkResources

### PR DESCRIPTION
**Pull request by LailaiMaster**
revert 'shouldShrinkResources false'

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*
image

*List which issues are fixed by this PR. You must list at least one issue.*
Fixes:[flutter#101893](https://github.com/flutter/flutter/issues/101893)
*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by LailaiMaster** [comment]
I signed it

**Comment by LailaiMaster** [comment]
@googlebot I signed it！

**Comment by LailaiMaster** [comment]
Can someone tell me what I'm supposed to do next？

**Comment by christopherfujino** [comment]
@LailaiMaster I am not sure that this is the correct change to make. I would recommend having a discussion with the platform: android maintainers on your tracking issue first before opening a PR. I also think you were reading the diff on https://github.com/flutter/flutter/pull/40610 wrong, this function was first introduced in https://github.com/flutter/flutter/commit/ee417827323e68560c7e5cb97276474d5ce3cdf0 and has always defaulted to true.

This change would also need a test before it could be reviewed. I am closing this PR for now, however, feel free to re-open it if there is agreement from the maintainers that the default value should be false. Thanks!

**Comment by LailaiMaster** [comment]
@christopherfujino Thank you for your reply,
so who do I talk to about it? How and when to discuss it.

**Comment by christopherfujino** [comment]
> @christopherfujino Thank you for your reply, so who do I talk to about it? How and when to discuss it.

As I stated, on your tracking issue: https://github.com/flutter/flutter/issues/101893. However, it was already closed with "although I highly doubt we will change the default for this use case" so it doesn't look like this is a change that will be approved.

**Pull request closed without merging**
