### PR TITLE
Trackpad mode crash fix

### PR DESCRIPTION
**Pull request by justinmc**
Fixes a crash reported by the Adwords team.

On iOS, it's possible to use the keyboard in "trackpad mode" by 3D touching the keyboard and dragging your finger around.  3D touching again without picking up your finger will start a selection, and dragging will edit it.

trackpad_mode

Flutter supports trackpad mode, but currently, trying to do selection as well causes a crash.  This PR fixes the crash, but selection in trackpad mode still doesn't work.  Did we ever support this, or is it something that we should build?

This is what happens when the user attempts to select in trackpad mode now after this fix:

trackpad_mode_flutter

### CODE REVIEW

**Comment by HansMuller** [comment]
I believe "trackpad mode" was supposed to work after https://github.com/flutter/flutter/pull/24761. That PR must be missing some tests; this PR should include tests that verify that that selection works in trackpad mode.

**Comment by HansMuller** [comment]
CC @xster

**Comment by xster** [comment]
Good catch. It seems like it was never implemented. Left #30476 for tracking. 

If you'd like to implement it 😉, we should save a second _selectionPointOffsetOrigin or some such on the second force touch down and call renderEditable.selectWordInRange on top of the setFloatingCursor to do the selection.

**Comment by justinmc** [comment]
Thanks for creating that issue.  I've added it to my text selection issue tracker.  I'll write some tests for this one and merge it as-is and come back for selection later.

**Review by HansMuller — APPROVED** [review]
LGTM

**Pull request merged**
