### PR TITLE
Reland "Exit on deprecated v1 embedding when trying to run or build (#92901)"

### PR DESCRIPTION
**Pull request by GaryQian**
This reverts commit 858a32871264543681560ac30c6a939dd17b6974 and relands #92901

### CODE REVIEW

**Review by blasten — APPROVED** [review]

**Comment by blasten** [comment]
The app palette_generator/example in the packages repo seems to still be using v1. https://cirrus-ci.com/task/6165105776787456?logs=main#L171

**Comment by GaryQian** [comment]
https://github.com/flutter/packages/pull/512 Fixes the packages repo v1 embedding vestiges

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by yjbanov** [comment]
I think this broke the build.

**Pull request merged**
