### PR TITLE
Don't print stacktraces from ToolExit errors during flutter run

### LINKED ISSUE #8363: Uncaught exceptions when doing `flutter run` and gradle fails
## Steps to Reproduce

1. `flutter create test`
1. `flutter run`

=> all good

1. Edit `test/android/app/src/main/AndroidManifest.xml`: Put some incorrect value in `android:icon="xxx"`
1. `flutter run`

=> gradle errors as expected, but we also get a dart stack track

Note that if you `flutter build apk` instead, then you as expected only get the gradle error.

### PR DESCRIPTION
**Pull request by jakobr-google**
Fixes #8363.

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
Do these get written out to a file still?  I guess the user can't take action on them anyway, so it doesn't really matter.  We'll need to get them reported via our crashing mechanism or some such instead?

**Comment by jakobr-google** [comment]
It doesn't get written out to a file, but you can see it if you run in verbose mode. This isn't really a crash of flutter tools, more like an error occurred, and we've reported it.

We only have to do extra handling here because the run command does its main work inside a `Chain.capture()`, with the comment "Don't let uncaught errors kill the process."

I'd prefer to remove that, and actually let errors kill the process, since with the current behavior, `flutter run` doesn't exit if there's an error (in this case building the .apk). It just prints an error message, and sits there. Removing the `Chain.capture()` in the run commands enables our normal error reporting (and crash capturing), and for the build error it'll just show the error and exit the tool (like `flutter build apk` does).

But I'm guessing there probably was a reason to wrap `flutter run` in a special zone, so I didn't change it here. Looks like @devoncarew added it in #4105.

**Comment by Hixie** [comment]
> But I'm guessing there probably was a reason to wrap flutter run in a special zone

Please feel empowered to change the code. If there was a reason to do something, then there should be a test to make sure we don't regress it. If the code does something for a subtle reason, it should have a comment saying why. If there's no test and no comment then you should assume that it was done for reasons that no longer apply or that never came to be or just that we made a mistake. (You can also look in the git history in case the checkin comment for the PR that added tho code tries to explain it, if you want to go above and beyond the call of duty.)

You have the authority to make decisions to refactor the code. Nothing is holy. Maybe you'll accidentally step into something that we failed to properly test and document, but then that's what code review is for. :-)

**Comment by Hixie** [comment]
In this specific case, I think we originally had Zones so that we could inject globals into the code. We have been moving away from doing that, because the benefits didn't outweigh the costs (both globals and Zones come with a high cognitive burden, and you can get the same effects by instantiating classes and injecting the relevant objects that way).

**Comment by devoncarew** [comment]
lgtm, though we may also want to hook these exceptions up to crash reporting at some point.

I'm trying to recall the reasoning behind this change, but I don't think we do want to exit the process here on a failure. `flutter run` is a bit different from the other commands in that its long running and I think more represents the app running on the device. If the app is still running on the phone, I think we want the flutter run process to still be alive. Esp. for things like an IDE, the flutter process is our connection to the running app.

**Comment by jakobr-google** [comment]
I figured out I could just rethrow the errors in the Chain.capture() onError() block. These are ToolExit exceptions, so the tool has decided that it doesn't make sense to continue, and we should exit. Other errors (as in, actual crashes) will still be printed, and tools will continue to run.

**Review by mravn-google — APPROVED** [review]
Please update title to match code changes.

Which BTW LGTM.

**Pull request merged**
