### PR TITLE
Fix null operator error when tapping on 'MenuItemButton'

### LINKED ISSUE #142095: MenuItemButton may throw when updated with a null FocusNode
On the MenuItemButton widget, if widget.focusNode is updated to null, didUpdateWidget would throw.

### Steps to reproduce
Change menu item focus node to null 

### Expected outcome
Doesn't throw

### Actual outcome
Throws

<details><summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

/// Flutter code sample for [MenuAnchor].

void main() => runApp(const MenuApp());

class MenuApp extends StatelessWidget {
  const MenuApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const Scaffold(body: SafeArea(child: MyCascadingMenu())),
    );
  }
}

class MyCascadingMenu extends StatefulWidget {
  const MyCascadingMenu({super.key});

  @override
  State<MyCascadingMenu> createState() => _MyCascadingMenuState();
}

class _MyCascadingMenuState extends State<MyCascadingMenu> {
  late FocusNode? _buttonFocusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return MenuAnchor(
      menuChildren: <Widget>[
        MenuItemButton(
            focusNode: _buttonFocusNode,
            closeOnActivate: false,
            child: Text("Set focus to null"),
            onPressed: () => setState(() {
                  _buttonFocusNode = null;
                })),
      ],
      builder:
          (BuildContext context, MenuController controller, Widget? child) {
        return TextButton(
          onPressed: () {
            if (controller.isOpen) {
              controller.close();
            } else {
              controller.open();
            }
          },
          child: const Text('OPEN MENU'),
        );
      },
    );
  }
}
```
</details>

Here is a gist demonstrating the bug in action on the Master branch: https://dartpad.dev/?id=a7da3f81557b11f7080b1f5a8afa0779&channel=master

Here is the code in the master material library: https://github.com/flutter/flutter/blob/b5262f0d80eb6da1b1cd6ceff0943367fbc29331/packages/flutter/lib/src/material/menu_anchor.dart#L1078C8-L1078C53

The code throws on both master and stable branches. 

<details>
<summary>Relevate framework code</summary>

```dart

class _MenuItemButtonState extends State<MenuItemButton> {
  FocusNode? _internalFocusNode;
  FocusNode get _focusNode => widget.focusNode ?? _internalFocusNode!;

  // ...

  @override
  void didUpdateWidget(MenuItemButton oldWidget) {
    if (widget.focusNode != oldWidget.focusNode) {
      // **BUG?** If widget.focusNode changes to null, this appears to throw
      _focusNode.removeListener(_handleFocusChange);
      if (widget.focusNode != null) {
        _internalFocusNode?.dispose();
        _internalFocusNode = null;
      }
      _createInternalFocusNodeIfNeeded();
      _focusNode.addListener(_handleFocusChange);
    }
    super.didUpdateWidget(oldWidget);
  }

  // ...

  void _createInternalFocusNodeIfNeeded() {
    if (widget.focusNode == null) {
      _internalFocusNode = FocusNode();
      assert(() {
        if (_internalFocusNode != null) {
          _internalFocusNode!.debugLabel = '$MenuItemButton(${widget.child})';
        }
        return true;
      }());
    }
  }
}
```
</details>

### PR DESCRIPTION
**Pull request by SelaseKay**
This PR fixes null operator error when you change focus node of a 'MenuItemButton' to null.

fixes: [issue142095](https://github.com/flutter/flutter/issues/142095)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by davidhicks980** [comment]
Correct me if I'm wrong but, because the `_focusNode` getter always references the most recent FocusNode, I think you'll want to reference oldWidget.focusNode regardless of whether widget.focusNode is null or not. Right now, we'd be removing the listener from a new focus node (which should not have a listener attached) rather than the old focus node.

**Comment by SelaseKay** [comment]
I think that makes more sense. I'll try it out and see how it goes.

**Review by gspencergoog — APPROVED** [review]

**Review by LongCatIsLooong — APPROVED** [review]

**Review by Piinks — APPROVED** [review]
Thanks for contributing @SelaseKay, welcome!
I updated the branch to kick the Google testing shard - LGTM :)

**Comment by SelaseKay** [comment]
Thank you @Piinks

**Pull request merged**
