### PR TITLE
Update flexible_space_bar.dart

### PR DESCRIPTION
**Pull request by kutenglaoshu**
missing colon

### CODE REVIEW

**Comment by Piinks** [comment]
Hey @kutenglaoshu welcome! 🎉 
Thank you for finding this typo and fixing it. :) Can you sign the cla as the googlebot has mentioned above?

**Comment by kutenglaoshu** [comment]
@googlebot I signed it!

**Comment by Piinks** [comment]
@kutenglaoshu can you check once more regarding the cla? The bot has not cleared it, but I can override it if it is by mistake.

**Comment by kutenglaoshu** [comment]
@Piinks please help override that, thank you.

**Comment by Piinks** [comment]
Hey @kutenglaoshu I had the bot re-check, then looked it up manually. The cla still needs to be signed.

**Review by Piinks — APPROVED** [review]
LGTM

**Pull request merged**
