### PR TITLE
Assert that runApp is called in the same zone as binding.ensureInitialized

### LINKED ISSUE #94123: Flutter framework does not warn when ensureInitialized is called in a different zone than runApp
## Use case

If a developer wants to call `runApp` within a custom `Zone` with `zoneValues` and the `zoneValues` rely on the underlying platform, they must call `WidgetsFlutterBinding.ensureInitialized()` like:

```dart
final token = Object();
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final value = await _getPlatformValue();
  runZoned(
    () => runApp(MyApp()),
    zoneValues: {token: value},
  );
}
```

This appears to work as expected, however, because `WidgetsFlutterBinding` also initializes other bindings like `GestureBinding` the `zoneValue` is not accessible within `onPressed` callbacks:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print(Zone.current[token]); // OK
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: ElevatedButton(
            onPressed: () {
              print(Zone.current[token]); // NULL
            },
            child: Text('Click Me'),
          ),
        ),
      ),
    );
  }
}
```

## Proposal

It would be great to have a way to initialize the `ServicesBinding` and `SchedulerBinding` independently of the remaining bindings in order to support accessing data from the underlying platform before `runApp` but without initializing the `WidgetsBinding.instance` within the root zone.

```dart
final token = Object();
void main() async {
  FlutterServicesBinding.ensureInitialized();
  final value = await _getPlatformValue();
  runZoned(
    () => runApp(MyApp()),
    zoneValues: {token: value},
  );
}
```

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print(Zone.current[token]); // OK
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: ElevatedButton(
            onPressed: () {
              print(Zone.current[token]); // OK
            },
            child: Text('Click Me'),
          ),
        ),
      ),
    );
  }
}
```

Where `FlutterServicesBinding` could look something like:

<details>
<summary>FlutterServicesBinding Sample</summary>

```dart
import 'dart:ui' as ui show SingletonFlutterWindow, PlatformDispatcher, window;

import 'package:flutter/foundation.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter/services.dart';

class FlutterServicesBinding extends _StandaloneBindingBase
    with SchedulerBinding, ServicesBinding {
  FlutterServicesBinding._();

  static FlutterServicesBinding? _instance;

  static FlutterServicesBinding ensureInitialized() {
    return _instance ??= FlutterServicesBinding._();
  }
}

abstract class _StandaloneBindingBase implements BindingBase {
  _StandaloneBindingBase() {
    initInstances();
    window.onReportTimings = null;
  }

  @override
  ui.SingletonFlutterWindow get window => ui.window;

  @override
  ui.PlatformDispatcher get platformDispatcher {
    return ui.PlatformDispatcher.instance;
  }

  @override
  @protected
  @mustCallSuper
  void initInstances() {}

  @override
  @protected
  @mustCallSuper
  void initServiceExtensions() {}

  @override
  @protected
  bool get locked => false;

  @override
  @protected
  Future<void> lockEvents(Future<void> Function() callback) async {}

  @override
  @protected
  @mustCallSuper
  void unlocked() {}

  @override
  Future<void> reassembleApplication() async {}

  @override
  @mustCallSuper
  @protected
  Future<void> performReassemble() async {}

  @override
  @protected
  void registerSignalServiceExtension({
    required String name,
    required AsyncCallback callback,
  }) {}

  @override
  @protected
  void registerBoolServiceExtension({
    required String name,
    required AsyncValueGetter<bool> getter,
    required AsyncValueSetter<bool> setter,
  }) {}

  @override
  @protected
  void registerNumericServiceExtension({
    required String name,
    required AsyncValueGetter<double> getter,
    required AsyncValueSetter<double> setter,
  }) {}

  @override
  @protected
  void postEvent(String eventKind, Map<String, dynamic> eventData) {}

  @override
  @protected
  void registerStringServiceExtension({
    required String name,
    required AsyncValueGetter<String> getter,
    required AsyncValueSetter<String> setter,
  }) {}

  @override
  @protected
  void registerServiceExtension({
    required String name,
    required ServiceExtensionCallback callback,
  }) {}

  @override
  String toString() => '<${objectRuntimeType(this, 'BindingBase')}>';
}
```

</details>

### DartPad Demos

- [DartPad](https://dartpad.dev/?null_safety=true&id=ecbde139305bd0d9e70aa2c407e072a2) illustrating the limitation when using `WidgetsFlutterBinding.ensureInitialized();`

- [DartPad](https://dartpad.dev/?null_safety=true&id=3edf539bd0fe29c7881baf0f01641209) illustrating an example of how this can be improved via `FlutterServicesBinding.ensureInitialized();`

## Additional Info

Published https://pub.dev/packages/flutter_services_binding as a workaround in the meantime.

### PR DESCRIPTION
**Pull request by Hixie**
Fixes https://github.com/flutter/flutter/issues/94123

### CODE REVIEW

**Comment by Hixie** [comment]
Previously landed as https://github.com/flutter/flutter/pull/117113.
Previously reverted as https://github.com/flutter/flutter/pull/122830.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
For posterity, the failures this was reverted for were actually fixed in https://github.com/flutter/flutter/commit/6711411fc28cb8b802067ee8b04b8fb823f8ab2e

**Comment by mit-mit** [comment]
@Hixie a few folks have requested that should be documented with migration steps as a breaking change.

**Comment by gabrimatic** [comment]
> @Hixie a few folks have requested that should be documented with migration steps as a breaking change.

@mit-mit You're true! I am getting this error after updating to Flutter 3.10:

```
════════ Exception caught by Flutter framework ══════════════════
The following assertion was thrown during runApp:
Zone mismatch.

The Flutter bindings were initialized in a different zone than is now being used. This will likely cause confusion and bugs as any zone-specific configuration will inconsistently use the configuration of the original binding initialization zone or this zone based on hard-to-predict factors such as which zone was active when a particular callback was set.
It is important to use the same zone when calling `ensureInitialized` on the binding as when calling `runApp` later.
To make this warning fatal, set BindingBase.debugZoneErrorsAreFatal to true before the bindings are initialized (i.e. as the first statement in `void main() { }`).
When the exception was thrown, this was the stack
#0      BindingBase.debugCheckZone.<anonymous closure>
binding.dart:497
#1      BindingBase.debugCheckZone
binding.dart:502
#2      runApp
binding.dart:1080
#3      main.<anonymous closure>.<anonymous closure>
main.dart:60
<asynchronous suspension>
```

**Comment by Hixie** [comment]
Sure, I'll see what I can whip up.

**Comment by Hixie** [comment]
proposed migration guide: https://github.com/flutter/website/pull/8683

**Comment by filiph** [comment]
Hi @Hixie, I need guidance on another use of `Zone` than is not mentioned in your migration guide.

Historically, when using Firebase Crashlytics, Zones were used to catch all errors: https://firebase.flutter.dev/docs/crashlytics/usage/#zoned-errors — even those in various callbacks. For something like Crashlytics, this is useful, because you do want to have reports about all your errors.

I used this approach in the [`game_template` sample](https://github.com/flutter/samples/blob/main/game_template/lib/main.dart#L46-L122), among other places. But now I see this is wrong through the warning discussed here (https://github.com/flutter/samples/issues/1818).

I was going to ask if there is any new guidance on cases like this, when you want to run your app in a Zone (i.e. `runApp` is called from a non-root zone), but you also need to send the errors from that zone to a plugin (i.e. `ensureInitialized` needs to be called before the zone is created).

[Newer Crashlytics documentation](https://firebase.google.com/docs/crashlytics/get-started?platform=flutter) does not mention this case at all.

cc @domesticmouse

**Comment by Hixie** [comment]
Create the zone, call initialize binding in the zone, then configure the plugin, then call runApp. You'll need to do something like have the zone error handler call a configurable callback that you can set up from inside the zone.

**Pull request merged**
