### PR TITLE
Performance Improvement for SliverFillRemaining

### PR DESCRIPTION
**Pull request by Piinks**
## Description

This PR changes the layout work done by RenderSliverFillRemaining, that _sometimes_ would do a second layout path. Instead, since SliverFillRemaining has box children, it uses intrinsic size information.

## Tests

Updated tests and added a few that test the horizontal axis.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by liyuqian** [comment]
Thank you @Piinks for improving the performance! It would be nice if you can add some performance test to capture and quantify your improvement. It will also prevent accidental performance regression in the future. See https://docs.google.com/document/d/1UolaKhEWieP2DDOhFuVQOuR5e545mO2obXcHH6p40Y4/edit#bookmark=id.70t9gnas5d1j for more info.

Please let me know if you have any questions about performance testing. I'm happy to answer them, or review the code in general.

**Comment by Piinks** [comment]
I don't know that I have any baseline to measure a performance improvement for this change. This change is not motivated by a reported issue or performance problem. I am not sure how to capture or quantify any improvement then. 🙂

**Comment by liyuqian** [comment]
@Piinks : I see. The easiest way to get a baseline or to quantify the performance change is probably just running our existing tests. Have you noticed any difference in `home_scroll_perf__timeline_summary`, `tiles_scroll_perf__timeline_summary`, or `home_scroll_perf__timeline_summary` test before and after your patch?

(To run the test, `cd flutter/flutter/dev/devicelab && ../../bin/cache/dart-sdk/bin/dart bin/run.dart -t <test_name>`)

**Comment by Piinks** [comment]
Ah! Thanks! I will check that out and report back! 💯

**Comment by Piinks** [comment]
Looks like a minor improvement for `home_scroll_perf__timeline_summary 90th_percentile_frame_rasterizer_time_millis`. 🙂 Cool!

**Comment by liyuqian** [comment]
Good to hear @Piinks ! In that case you probably don't need to write a new performance test. Can you please post your local test result to this PR's description for future reference?

**Comment by Piinks** [comment]
Perf test results after latest merge from master. :)

```
"success": true,
  "data": {
    "average_frame_build_time_millis": 2.928195402298851,
    "90th_percentile_frame_build_time_millis": 6.189,
    "99th_percentile_frame_build_time_millis": 9.166,
    "worst_frame_build_time_millis": 43.872,
    "missed_frame_build_budget_count": 1,
    "average_frame_rasterizer_time_millis": 7.273534482758619,
    "90th_percentile_frame_rasterizer_time_millis": 15.027,
    "99th_percentile_frame_rasterizer_time_millis": 21.857,
    "worst_frame_rasterizer_time_millis": 51.239,
    "missed_frame_rasterizer_budget_count": 14,
    "frame_count": 174,
```

**Comment by liyuqian** [comment]
@Piinks : are you waiting for some framework expert to review this PR? (Just found this lonely PR again in the performance triage.)

**Comment by Piinks** [comment]
Hey @liyuqian, thank you. Yes this is waiting on a review. Would you like to give it a look? It is a fairly trivial change.

**Review by liyuqian — APPROVED** [review]
LGTM

**Pull request merged**
