### PR TITLE
Make dialog background color configurable (#7320)

### PR DESCRIPTION
**Pull request by lequem**
Allow the configuration of dialog's background color

### CODE REVIEW

**Comment by lequem** [comment]
I signed it!

**Comment by lequem** [comment]
I don't understand why travis task failed...

**Comment by abarth** [comment]
I'm re-running the travis build.  The failure seems unrelated to your change.

**Comment by lequem** [comment]
Ok thanks, for the modification, no problem to remove the assert, but how can I do it with git?
I modify the file, do a git commit --amend, a push to origin and a new pull request?

**Comment by abarth** [comment]
> Ok thanks, for the modification, no problem to remove the assert, but how can I do it with git?
> I modify the file, do a git commit --amend, a push to origin and a new pull request?

Yep.

**Comment by abarth** [comment]
Also, you should add yourself to the AUTHORS file.

**Comment by abarth** [comment]
Landed in another PR.

**Pull request closed without merging**
