### PR TITLE
Fix a bug that the cursor jump abnormally when setting text for a TextEditingController.

### PR DESCRIPTION
**Pull request by kangwang1988**
This commit fix a bug that the cursor jump(very beginning and the end) when calling "TextEditingController.setText". A small screenshot video is given below:

https://www.youtube.com/watch?v=vq4_IBVd5Ro

### CODE REVIEW

**Comment by kangwang1988** [comment]
@jonahwilliams 

Though my fix seems working fine, the test cases fails.As I'm not familiar with the test cases in this file,
Can you have a look at the failure in test/widgets/editable_text_test.dart(two errors at line:967 and line:1415) 

screen shot 2018-09-29 at 5 15 44 pm
screen shot 2018-09-29 at 5 16 21 pm

**Comment by jonahwilliams** [comment]
@kangwang1988 Looks like the change updated some of the expected semantics, only because the cursor goes to the end now.

**Comment by jonahwilliams** [comment]
In this case, the first failing test in `editable_text_test.dart` can be fixed by removing ` SemanticsAction.setSelection` from the list of supported actions.
```dart
    expect(
        semantics,
        includesNodeWith(
          value: 'test',
          actions: <SemanticsAction>[
            SemanticsAction.moveCursorBackwardByCharacter,
            SemanticsAction.moveCursorBackwardByWord,
          ],
        ));
```

The second failing case can be fixed by adding the following actions and textSelection:

```dart
                        TestSemantics(
                          flags: <SemanticsFlag>[
                            SemanticsFlag.isTextField,
                            SemanticsFlag.isObscured
                          ],
                          actions: <SemanticsAction>[
                            SemanticsAction.moveCursorBackwardByCharacter,
                            SemanticsAction.moveCursorBackwardByWord,
                          ],
                          value: expectedValue,
                          textDirection: TextDirection.ltr,
                          textSelection: const TextSelection(baseOffset: 24, extentOffset: 24),
                        ),
```

Both seem OK

**Comment by kangwang1988** [comment]
@jonahwilliams 
Thanks for ur help. I will try it.

**Comment by alanrussian** [comment]
Thanks for submitting this pull request! I ran into the same issue.

**Comment by goderbauer** [comment]
Thanks for the contribution! Can you by any chance add a test to this?

**Comment by jslavitz** [comment]
@kangwang1988 You probably want to make a test that just adds a character and immediately checks to see the location of the cursor instead of checking the semantics tree!

**Comment by goderbauer** [comment]
@kangwang1988 Are you still planning to work on this or should we close it for now?

**Comment by kangwang1988** [comment]
@goderbauer  Will work on it using the lastest master branch.

**Pull request closed without merging**
