### PR TITLE
Dart SDK roll for 2018/09/07

### PR DESCRIPTION
**Pull request by bkonyi**

### CODE REVIEW

**Comment by goderbauer** [comment]
LGTM

**Comment by Hixie** [comment]
This did bad things to our performance numbers.

**Comment by Hixie** [comment]
Namely, `complex_layout_scroll_perf__timeline_summary 99th_percentile_frame_rasterizer_time_millis` regressed a lot, and `complex_layout_scroll_perf__memory diff-median` regressed a little. Some of the other benchmarks move a bit too.

**Comment by Hixie** [comment]
proposed fix is in https://github.com/flutter/flutter/pull/21703

**Comment by Hixie** [comment]
Issue is filed in https://github.com/flutter/flutter/issues/21617

**Pull request merged**
