### PR TITLE
[flutter_tools] fix null check in crash reporter

### LINKED ISSUE #80383: Crash reporter may be unable to report crashes in current RC branch
Fixes via https://github.com/flutter/flutter/pull/80382

This will prevent any crash data from making it to analytics. The change above fixes the underlying issue and adds an integration test.

### PR DESCRIPTION
**Pull request by jonahwilliams**
The crash reporter is currently broken, it will crash while trying to report a crash. We need a test for this. Perhaps some way to force the flutter_tool to produce a crash report?

Fixes https://github.com/flutter/flutter/issues/80383

### CODE REVIEW

**Comment by jonahwilliams** [comment]
This broke in  https://github.com/flutter/flutter/commit/8ddc27e6077b0ce66e19d7d489a327f41d974f7d which is unfortunately in the latest RC so we'll need to cherry pick.

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
for testing, can we add a method that always throws with `@visibleForTesting`?

**Comment by jonahwilliams** [comment]
I added a flag to update-packages, since that is really only a command for contributors and is already hidden. This allows us to simulate a crash with as few differences as possible between the test environment and IRL.

**Review by christopherfujino — APPROVED** [review]
lgtm

**Comment by jmagman** [comment]
Actual output is missing the `Oops`
```
  Expected: contains 'Oops; flutter has exited unexpectedly: "Bad state: test crash please ignore.".\n'
              'A crash report has been written to'
    Actual: '\n'
              'Bad state: test crash please ignore.\n'
```

**Comment by jonahwilliams** [comment]
Ahh, the oops is stdout

**Comment by jonahwilliams** [comment]
err, maybe its a terminal versus no terminal thing

**Comment by jonahwilliams** [comment]
g3 failure seems unrelated so I'll land on green.

**Pull request merged**
