### PR TITLE
GestureDetector fills its parent if child-less.

### LINKED ISSUE #5380: A childless GestureDetector should expand to fit its max constraints rather than shrink to minimum constraints.
Use case.  GestureDetector with no child inside a Stack.  GestureDetector should end up being size of Stack.

### PR DESCRIPTION
**Pull request by Hixie**
Fixes https://github.com/flutter/flutter/issues/5380

### CODE REVIEW

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
Maybe RenderPointerListener or GestureDetector and Listener should document their sizing behavior?

**Comment by HansMuller** [comment]
LGTM

**Comment by Hixie** [comment]
Documentation? In our moment of triumph?!

**Comment by Hixie** [comment]
added docs.

**Comment by Hixie** [comment]
will check in once travis is green.

**Pull request merged**
