### PR TITLE
Added DraggableArea which limits movement of the Draggable to container

### PR DESCRIPTION
**Pull request by eligt**
I'm aware that this is most likely not the correct way of achieving this effect, for the following reasons:
1) I'm not sure if `ancestorRenderObjectOfType()` can be used this way, based on the docs
2) Even if 1) is fine, this implementation has a big limit in that it simply ignores the drag if it goes beyond the bounds of the parent DecoratedBox, rather than finding the **closest** valid point based off of the pointer position. The latter would be quite complicated unless there's some built-in classes to do it.
3) Right now it only supports DecoratedBox parents

Example usage to limit the Draggable area:
```dart
Container(
  width: 280.0,
  height: 280.0,
  decoration: new BoxDecoration(
    color: Colors.grey,
    shape: BoxShape.circle,
  ),
  alignment: Alignment.center,
  child: DraggableArea(
    child: LongPressDraggable(
      hapticFeedbackOnStart: true,
      child: Container(
        width: 45.0,
        height: 45.0,
        decoration: new BoxDecoration(
          color: Colors.orange,
          shape: BoxShape.circle,
        ),
      ),
      feedback: Container(
        width: 45.0,
        height: 45.0,
        decoration: new BoxDecoration(
          color: Colors.red,
          shape: BoxShape.circle,
        ),
      ),
    ),
  ),
)
```

### CODE REVIEW

**Comment by goderbauer** [comment]
It's a very interesting idea. We'd have to make it more robust and remove some of the limitations you mentioned in order to land it in the framework. However, maybe this could live in a separate pub package?

**Comment by eligt** [comment]
Personally I think until those limitations are removed, this widget won't really be useful as the drag action feels junky/laggy due to the inability of calculating exact shape bounds and that ruins the user experience. If I get around to remove that limitation I might think of a package or resubmit a PR.

**Comment by goderbauer** [comment]
@eligt Can we close this PR until those limitations are removed?

Also, feel free to file an issue and we can discuss over there how this could be done.

**Comment by eligt** [comment]
Sure, you can close this one.

**Pull request closed without merging**
