### PR TITLE
Removed Pesto's drawer.

### LINKED ISSUE #5713: Gallery, Pesto: "Home" in drawer was confusing to some users
(from user testing)

The "Home" item in Pesto's drawer was confusing. Did it mean "Gallery home" or "Pesto home" ?

One thing I noticed: the Home item isn't highlighted when the user is on the Pesto home. So there's no visual indication that they are at any place in the drawer nav.

One idea: remove the drawer entirely. It only shows up on the home of Pesto. The user could use the back button to get back to the Gallery home.

### PR DESCRIPTION
**Pull request by dragostis**
The drawer was confusing without adding much value. It was
especially confusing when wanting to go back to the Gallery on iOS.
Fixes #5713.

### CODE REVIEW

**Comment by sethladd** [comment]
If the drawer is gone, we might have made it impossible to get to the "favorites". If so, should we remove that code?

**Comment by dragostis** [comment]
@sethladd Might have missed that part. Maybe it's not the best idea to remove the drawer then.

**Comment by sethladd** [comment]
In the drawer, there's a "Favorites" option. If we remove the drawer, we should remove the Favorites view, too.

**Comment by Hixie** [comment]
What does the favorites option do? Can we offer it using a button in the toolbar instead?

**Comment by sethladd** [comment]
> What does the favorites option do?

You can "heart" a recipe that you're looking at. It gets saved into favorites. You can view these favorites. There's no way to delete a favorite.

> Can we offer it using a button in the toolbar instead?

Perhaps. But if we're going to put that effort in, we might as well add Delete/Remove Favorite.

Pesto is better as a visual demo. We could invest more in making it a great "CRUD" (create, read, update, delete) demo, but that's probably a v2 kind of thing.

In an effort to reduce testable surface area, I think it's OK to treat Pesto as a great visual demo and focus efforts on getting the performance and transitions stellar.

**Comment by Hixie** [comment]
I would be happy with seeing either the favourites code go away or relegating its entry point to some other part of the UI, but we shouldn't leave dead code, certainly.

**Comment by dragostis** [comment]
I've removed the favorites functionality. @HansMuller @Hixie @sethladd

**Comment by sethladd** [comment]
Also closes https://github.com/flutter/flutter/issues/5071

**Comment by HansMuller** [comment]
The 'Pesto route management' shouldn't be included in pesto_test.dart. However a generic version of the test should be added to packages/flutter/test/widget/navigator_test, since we want to continue to regression test https://github.com/flutter/flutter/pull/5168

**Comment by HansMuller** [comment]
examples/flutter_gallery/test/smoke_test.dart needs to be updated. The pesto special case stuff isn't needed anymore.

**Comment by HansMuller** [comment]
The gallery performance test, examples/flutter_gallery/test_driver/transitions_perf_test.dart, should be updated. Pesto can be treated like the other gallery demos.

**Comment by HansMuller** [comment]
LGTM

**Pull request merged**
