### PR TITLE
Revert "Fix RefreshIndicator performance issue"

### PR DESCRIPTION
**Pull request by dnfield**
Reverts flutter/flutter#47667

This caused some regressions on internal tests.  I'll try to come up with a good repro.

@LongCatIsLooong 

/cc @renyou

### CODE REVIEW

**Review by LongCatIsLooong — APPROVED** [review]
Thank you!

**Comment by dnfield** [comment]
Current redness is due to a flake, CI has finished on this and it's a revert. LAnding.

**Comment by dnfield** [comment]
The internal test is difficult to reproduce, and it turns out it wasn't using a `RepaintBoundary` explicitly in its golden testing logic - adding a `RepaintBoundary` makes things work.  I'm proposing that change internally, which would allow us to reland this patch.

**Pull request merged**
