### PR TITLE
Persist Chrome Default Directory

### PR DESCRIPTION
**Pull request by grouma**
Cache and restore the entire Chrome `Default` directory across Flutter Tool runs. This ensures that cookies, history and logged in sites are maintained. Related to https://github.com/flutter/flutter/pull/53030.

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
This approach SGTM.

There is an existing test covering the copying logic: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/web/chrome_test.dart#L204

You could update that just a tad with a file outside of the previous copy dirs to make sure this is covered

**Comment by grouma** [comment]
Updated the tests. PTAL.

**Review by jonahwilliams — APPROVED** [review]
LGTM


Thank you!

**Comment by jonahwilliams** [comment]
```
/tmp/flutter sdk/packages/flutter_tools/lib/src/web/chrome.dart:330: trailing U+0009 tab character
/tmp/flutter sdk/packages/flutter_tools/lib/src/web/chrome.dart:331: trailing U+0009 tab character
/tmp/flutter sdk/packages/flutter_tools/lib/src/web/chrome.dart:332: trailing U+0009 tab character
/tmp/flutter sdk/packages/flutter_tools/lib/src/web/chrome.dart:333: trailing U+0009 tab character
/tmp/flutter sdk/packages/flutter_tools/lib/src/web/chrome.dart:334: trailing U+0009 tab character
/tmp/flutter sdk/packages/flutter_tools/lib/src/web/chrome.dart:335: trailing U+0009 tab character
/tmp/flutter sdk/packages/flutter_tools/test/general.shard/web/chrome_test.dart:233: trailing U+0020 space character
```

nit: you need to remove the trailing whitespace

**Review by mdebbar — COMMENTED** [review]
I'm assuming this doesn't have the same issues that made @jonahwilliams change it to a new random profile on every run. But it's not clear to me how. Could someone help me understand?

**Comment by grouma** [comment]
> I'm assuming this doesn't have the same issues that made @jonahwilliams change it to a new random profile on every run. But it's not clear to me how. Could someone help me understand?

Chrome must be provided a custom user-data-dir to enable the remote debug port. If you reuse a data dir, Chrome will potentially "attach" to an existing Chrome instance and the remote debug port may silently fail. I believe that's what @jonahwilliams was trying to resolve. As far as I can tell, since we use a different data dir, Chrome will not "attach" to any existing instance and we won't run into debugging issues.

**Pull request merged**
