### PR TITLE
Roll dds dependency to 2.8.3 for expression evaluation upcoming fixes.

### PR DESCRIPTION
**Pull request by aam**
The fix is coming as part of https://dart-review.git.corp.google.com/c/sdk/+/306908 dart sdk roll as well as https://github.com/flutter/flutter/pull/128084.

BUG=https://github.com/dart-lang/sdk/issues/52522

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
Looks like this is gonna require import updates in the tool:

```
  error • Target of URI doesn't exist: 'package:dds/src/dap/protocol_generated.dart' • packages/flutter_tools/test/integration.shard/debug_adapter/flutter_adapter_test.dart:8:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:dds/src/dap/protocol_generated.dart' • packages/flutter_tools/test/integration.shard/debug_adapter/test_adapter_test.dart:5:8 • uri_does_not_exist
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8779384083340504225/+/u/Analyze/analyze/test_stdout

**Comment by aam** [comment]
Pending `Google testing` seems to due to [fix to AppLifecycleState.hidden](https://github.com/flutter/flutter/pull/127987) not making it all the to g3 yet. Not sure what it the right way of handling that for this PR.

cc @gspencergoog

**Comment by christopherfujino** [comment]
> Pending `Google testing` seems to due to [fix to AppLifecycleState.hidden](https://github.com/flutter/flutter/pull/127987) not making it all the to g3 yet. Not sure what it the right way of handling that for this PR.
> 
> cc @gspencergoog

looks to me like presubmit tests are still running?

```
STILL RUNNING     66% complete
ETA:     Jun 02, 14:32 PDT ±2min
```

**Comment by christopherfujino** [comment]
but you're right, once it finishes there WILL be unrelated failures. once testing finishes if it's just greg's change, i'll update the github status manually in FRoB.

**Comment by christopherfujino** [comment]
Google testing CL finished in https://cl/537415064 and the two failures are due to https://github.com/flutter/flutter/commit/a257efc2841ed7042322fbd043f0983e705d7da2, so I manually set "Google testing" to green in go/flutter-rob.

**Pull request merged**
