### PR TITLE
Always run the flutter tool in checked mode.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
cc @tvolkert

**Review by tvolkert — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
I'm going to revert this since it doubles the analyzer time and (for some reason?) dartdoc generation time.

**Comment by aam** [comment]
Besides, new Dart frontend throws in checked mode. @peter-ahe-google

**Comment by tvolkert** [comment]
SGTM

**Comment by cbracken** [comment]
For the record the numbers were 31 -> 63ms on the analysis benchmark, and it's been remarkably consistent ever since.

**Pull request merged**
