### PR TITLE
Migrate channel to null safety

### PR DESCRIPTION
**Pull request by Abhishek01039**
I have migrated dev/integration_test/channels to null safety

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Abhishek01039** [comment]
Hello @jmagman
can you please review this PR?
Thanks

**Review by jmagman — CHANGES_REQUESTED** [review]
This is still failing in the same way that caused the first revert https://github.com/flutter/flutter/pull/81050.

You can test locally by running:
```
cd dev/devicelab
dart bin/run.dart -t channels_integration_test_ios
```

I get:
```
[channels_integration_test_ios] [STDOUT] stdout: [+3875 ms] 00:04 +0 -1: channel suite step through [E]
[channels_integration_test_ios] [STDOUT] stdout: [        ]   Failed at step 16 with status failed
[channels_integration_test_ios] [STDOUT] stdout: [  +22 ms]   package:test_api/src/frontend/expect.dart 153:31               fail
```
etc

**Comment by Abhishek01039** [comment]
Hello @jmagman 
```
abhishek@abhisheks-mbp devicelab % dart bin/run.dart -t channels_integration_test_ios



════════════╡ ••• Running task "channels_integration_test_ios" ••• ╞════════════


Executing: /Users/abhishek/Desktop/open_source/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --enable-vm-service=0 --no-pause-isolates-on-exit bin/tasks/channels_integration_test_ios.dart in /Users/abhishek/Desktop/open_source/flutter/dev/devicelab with environment {}
Unhandled exception:
ProcessException: Failed to find "/Users/abhishek/Desktop/open_source/flutter/bin/cache/dart-sdk/bin/dart" in the search path.
  Command: /Users/abhishek/Desktop/open_source/flutter/bin/cache/dart-sdk/bin/dart 
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:58:7)
#1      startProcess (package:flutter_devicelab/framework/utils.dart:286:49)
#2      runTask (package:flutter_devicelab/framework/runner.dart:87:32)
#3      runTasks (package:flutter_devicelab/framework/runner.dart:31:37)
#4      main (file:///Users/abhishek/Desktop/open_source/flutter/dev/devicelab/bin/run.dart:106:11)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```
I am getting this error logs...

**Comment by jmagman** [comment]
> ProcessException: Failed to find "/Users/abhishek/Desktop/open_source/flutter/bin/cache/dart-sdk/bin/dart" in the search path.

Try adding it to your PATH then?
```
export PATH=/Users/abhishek/Desktop/open_source/flutter/bin/cache/dart-sdk/bin/:$PATH && dart bin/run.dart -t channels_integration_test_ios
```
Which dart is on your path now (it should be the one specified in the error message)?
```
which dart
```

**Comment by Abhishek01039** [comment]
Hello @jmagman 
I am able to run the app in the simulator.
so what is the problem here?
can you please guide me solve that problem?
Thanks

**Comment by jmagman** [comment]
> Hello @jmagman
> I am able to run the app in the simulator after migrating to null safety.
> so what is the problem here?
> can you please guide me solve that problem?
> Thanks

The `channels_integration_test_ios` test is passing on master, and failing on your PR.  So part of getting this PR merged is debugging that test failure.  😄

**Comment by Abhishek01039** [comment]
Ok let me try to run the test locally
Flutter test will work in this case ?

**Comment by jmagman** [comment]
No, flutter test will not work.

> You can test locally by running:
> 
> ```
> cd dev/devicelab
> dart bin/run.dart -t channels_integration_test_ios
> ```

**Comment by Abhishek01039** [comment]
Hello @jmagman 
I am not able to understand that what is exact here?
can you please guide me?

**Comment by christopherfujino** [comment]
> I am not able to understand that what is exact here
> can you please guide me?

Troubleshooting why tests are failing is the responsibility of a PR author, and out of the scope for reviewers. There's some documentation on running devicelab tests https://github.com/flutter/flutter/blob/master/dev/devicelab/README.md, and if you still need help, I would recommend following up in the discord #hackers-tests channel. Thanks.

**Comment by jmagman** [comment]
@Abhishek01039 If you're not sure how to debug the test failure you should probably just close this PR.  The reviewers (me) aren't likely to prioritize debugging this any time soon.  Feel free to re-open with test edits if you figure out why `channels_integration_test_ios` is failing on this PR.

**Pull request closed without merging**
