### PR TITLE
Fixed middle prop in CupertinoSliverNavigationBar to adhere to the docs and expected iOS behavior.

### LINKED ISSUE #53788: CupertinoSliverNavigationBar  & CupertinoNavigationBar should support differing style||widget for `largeTitle` and `middle`
Once you scroll down on CupertinoSliverNavigationBar the middle widget automatically appears -- this widget cannot be customized while simultaneously having a customized largeTitle. If you try to use a custom middle widget it will appear even while the largeTitle is active in its regular state. There's really no option to customize the middle state of the largeTitle.

Can't customize:
image

Can customize:
image

Right now both have to change together. Ideally you could set a different font weight, or even a different widget when the large title is gone.

### PR DESCRIPTION
**Pull request by SimonVillage**
In reference to #86983

Credit: https://github.com/flutter/flutter/issues/53788#issuecomment-864361170
Closes https://github.com/flutter/flutter/issues/53788 if I understood it correctly. https://github.com/flutter/flutter/issues/78607 is partly closed.

After fix:

https://user-images.githubusercontent.com/1446685/158810187-7d1213ae-ac68-4c6f-a989-86a4aa9febfa.mp4

Before fix:

https://user-images.githubusercontent.com/1446685/158810218-ec1d55ac-27a4-42ca-980e-e76373eb303a.mp4

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/100295

**Comment by CaseyHillers** [comment]
In it's current state, this PR is hard to review as it contains commits outside of this PR. Can you rebase this commit to only contain your changes?

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 38.
View them at https://flutter-gold.skia.org/cl/github/100295

**Comment by SimonHausdorf** [comment]
@CaseyHillers rebased with master

**Pull request closed without merging**
