### PR TITLE
InteractiveViewer scaleFactor

### LINKED ISSUE #76765: Add more granularity when using the InteractiveViewer zoom
Hello, I am using the package graphview. And I have run into a bit of an issue with the InteractiveViewer. Particularity when zooming in and out on web, it is too "fast"?. In the InteractiveViewer file it has the following comment.

```
// In the Flutter engine, the mousewheel scrollDelta is hardcoded to 20 per scroll, while a trackpad scroll can be any amount.
// The calculation for scaleChange here was arbitrarily chosen to feel natural for both trackpads and mousewheels on all platforms.
final double scaleChange = math.exp(-event.scrollDelta.dy / 200);
```

I would suggest the easiest way to fix this would be to make the 200 a variable you can pass to the class so that you can change the rate of scroll.

Thanks,
Harry

### PR DESCRIPTION
**Pull request by justinmc**
Creates a new parameter for InteractiveViewer, `scaleFactor`, which allows control over the amount of scale per scroll when scrolling with a pointer device.

Fixes https://github.com/flutter/flutter/issues/76765

### CODE REVIEW

**Comment by justinmc** [comment]
@longtimedeveloper Would this solve your problem?  Will people be ok with only the ability to adjust `scaleFactor` and not the exponential function that it's used in?

**Comment by longtimedeveloper** [comment]
@justinmc outstanding!! Thank you.  Your fix is better than my original recommendation since you only have to make the property public and you're done!!!!!!

**Comment by longtimedeveloper** [comment]
@justinmc how long does it normally take for the required reviewers to complete the review.  Again, thank you for getting this accomplished!!

**Comment by justinmc** [comment]
Sorry, the holidays are making this take longer than usual.  Will track down a reviewer.

**Comment by longtimedeveloper** [comment]
@justinmc thank you for putting up with me, LOL.  Have a very Happy (and safe too) New Year.  Best regards, Karl

**Review by LongCatIsLooong — APPROVED** [review]

**Comment by longtimedeveloper** [comment]
@justinmc so happy to see progress.  I've not been in the Flutter community long, how long do you think it will take to be in the Stable Branch?  Thank you for implementing this feature!!

**Comment by justinmc** [comment]
No problem!  I'm not sure if this will make it into 2.10 or not.  I think that will be released next month on stable.  Otherwise it would be another month or so after that for the next release.

**Comment by longtimedeveloper** [comment]
@justinmc thank you for a **_super fast reply_**.  So looking forward to this!  So many that use this awesome widget will be very grateful.  Best regards, Karl

**Comment by longtimedeveloper** [comment]
@justinmc I edited my local copy of InteractiveViewer so I could test and implement this in my application.

Here is my ` scaleFactor: 3000.0,`

With 3000.0, the zooming is butter-like, so smooth!!

My Control Panel Mouse Vertical Scrolling is 6.

You can now see why this setting is critical for web and desktop apps using this awesome widget.

image

**Thank you again, this goes down as enhancement of the year!!**

**Comment by justinmc** [comment]
Thanks for following up!  I'm glad to hear that it's working well for you.

**Comment by justinmc** [comment]
Yeah sorry, definitely the next one.

**Comment by longtimedeveloper** [comment]
@justinmc splendid.  I replaced the interactive_viewer.dart file with the one I created earlier.  So I didn't miss a beat.  Will be very cool when part of Flutter so many others can leverage this awesome feature.  Best to you!  Karl

**Pull request merged**
