### PR TITLE
Rev engine, services, and sdk.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by abarth** [comment]
Do we need to rev the SDK?  This will cause pain for our developers because pub has terrible error messages when the SDK rev fails to match.  Instead, we should internalize the dependency on the Dart SDK so we can transparently upgrade it.

**Comment by Hixie** [comment]
Well we know we don't work with 1.12. But yes, once we have a real build system we should just fetch the SDK automatically as part of bootstrapping.

**Comment by abarth** [comment]
If you're going to put an SDK declaration somewhere, it should be in flutter_tools because that's what actually runs in the SDK.

**Comment by Hixie** [comment]
yeah we could move it. or remove it, I don't much mind. I'm just saying
that if we have one it shouldn't be wrong :-)

**Comment by abarth** [comment]
Can we make this change separately from reving the engine?

**Comment by Hixie** [comment]
sure

**Comment by abarth** [comment]
LGTM with the SDK constraints either left alone or removed.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/546

**Pull request merged**
