### PR TITLE
[versions] roll to latest test

### LINKED ISSUE #77856: Flutter SDK's test deps are stuck due to vm_snapshot_analysis, devtools_server
The versions of major tooling dependencies, shelf, test, dwds, vm_service are currently stuck due to the flutter_tools pin of mockito. Mockito was pinned to 4.1.1 to avoid needing to add more dependencies on code generation libraries, and eventually to avoid needing codegen for mockito tests.

The flutter_tool is the last user of mockito, but it will be several more months until we have completed migration off of mockito.

See also:
  *   https://github.com/dart-lang/mockito/issues/352
  *  https://github.com/dart-lang/mockito/pull/353

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/77856

Roll to latest package:test, test_core, test_api

### CODE REVIEW

**Comment by jmagman** [comment]
```
  error • A value of type 'String?' can't be assigned to a variable of type 'String' • packages/flutter_test/test/widget_tester_test.dart:76:30 • invalid_assignment
  error • A value of type 'String?' can't be assigned to a variable of type 'String' • packages/flutter_test/test/widget_tester_test.dart:99:30 • invalid_assignment
  error • A value of type 'String?' can't be assigned to a variable of type 'String' • packages/flutter_test/test/widget_tester_test.dart:117:30 • invalid_assignment
```

**Comment by jonahwilliams** [comment]
So this can't actually land, until we figure out what we want to do about the version change.

**Comment by jonahwilliams** [comment]
all dependencies are updated

**Review by zanderso — APPROVED** [review]

**Comment by jonahwilliams** [comment]
Now blocked by https://github.com/flutter/plugins/pull/3769

**Comment by jonahwilliams** [comment]
Looks like its all going to pass

**Pull request merged**
