### PR TITLE
Reland "Roll engine to fed2ea458ed49088d33eddabc546ba56d600c717 (includes dart roll) again"

### PR DESCRIPTION
**Pull request by aam**
This relands #19277 .

This reverts commit cc122f1672d4b7e0c0734be34a155997463e3b56 as we found culprit for hot mode test failures, which is believed to be fixed with https://github.com/flutter/flutter/commit/b075229d8504e9cbb1f4d86799e5fba6e699c477

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by Hixie** [comment]
IMHO we should revert this. It caused serious regressions to `flutter analyze` and `flutter test` performance, at a time where performance is our top priority.

**Comment by jonahwilliams** [comment]
I believe this also breaks the debugger, see https://github.com/flutter/flutter/issues/19379.

**Comment by aam** [comment]
See #19340

**Comment by jonahwilliams** [comment]
I can still reproduce the crash with those commits patched into master

**Comment by jonahwilliams** [comment]
I made a mistake when rebuilding that patch - confirmed that it does fix the issue.

**Comment by DanTup** [comment]
I'm seeing some new crashes on `flutter-tester`. I can't repro on other devices, though @escamoteur is seeing similar crashes on Android emulator.

Mine is the same steps as #17838 but instead of pausing unexpected on the will-be-caught exception, it terminates and I just get `connection to device lost`. I can't seem to get any useful error/stack even running with `--verbose`.

**Pull request merged**
