### PR TITLE
Fix bar height changes when toggle keyboard

### PR DESCRIPTION
**Pull request by luckysmg**
**The MediaQuery.padding will change during keyboard toggling**, I think we should use `MediaQuery.viewPadding` instead of `padding`.

**And I modifed some old tests because they use the padding property.(It should be viewPadding)**

Here is preview video, **and pay attention to red bottom bar.**

**Before:**

https://user-images.githubusercontent.com/49340347/175492425-f1e4146a-7882-46a9-908f-9fbfc58cd800.mp4

**After**

https://user-images.githubusercontent.com/49340347/175492494-78852056-e8ce-4dee-b8de-eb623b67a4f6.mp4

*List which issues are fixed by this PR. You must list at least one issue.*

<details>

<summary>Demo code</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const TestPage1(),
    );
  }
}

class TestPage1 extends StatefulWidget {
  const TestPage1({Key? key}) : super(key: key);

  @override
  State<TestPage1> createState() => _TestPage1State();
}

class _TestPage1State extends State<TestPage1> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: BottomNavigationBar(
        backgroundColor: Colors.red,
        items: const [
          BottomNavigationBarItem(icon: Text('1'), label: "1"),
          BottomNavigationBarItem(icon: Text('2'), label: "2"),
          BottomNavigationBarItem(icon: Text('3'), label: "3"),
        ],
      ),
      body: const Center(
        child: CupertinoTextField(
          padding: EdgeInsets.all(20),
          placeholder: "Tap me!",
          decoration: BoxDecoration(color: Colors.green),
        ),
      ),
    );
  }
}

class TestPage2 extends StatefulWidget {
  const TestPage2({Key? key}) : super(key: key);

  @override
  State<TestPage2> createState() => _TestPage2State();
}

class _TestPage2State extends State<TestPage2> {
  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      tabBar: CupertinoTabBar(
        items: const [
        BottomNavigationBarItem(icon: Text('1'), label: "1"),
        BottomNavigationBarItem(icon: Text('2'), label: "2"),
        BottomNavigationBarItem(icon: Text('3'), label: "3"),
      ],backgroundColor: Colors.orange,),
      tabBuilder: (BuildContext context, int index) {
        return const Center(
          child: CupertinoTextField(
            padding: EdgeInsets.all(20),
            placeholder: "Tap me!",
            decoration: BoxDecoration(color: Colors.green),
          ),
        );
      },
    );
  }
}


```

</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by luckysmg** [comment]
Emm although the linux customer testing failed...I think the bottom bar height should not change......Is that expected ?

**Comment by luckysmg** [comment]
cc @Piinks is the linux customer test fail is expected? I think the bar height should not change.....

**Comment by Hixie** [comment]
Thanks for your contribution! Could you try rebasing your PR against the tip of tree and force pushing? That will cause us to run the tests with the latest version which may shake out the problem you're seeing.

**Comment by luckysmg** [comment]
Yeah . Tests passed. Would you mind give this PR a review?😄
@Hixie

**Review by MitchellGoodwin — APPROVED** [review]
LGTM

**Review by LongCatIsLooong — APPROVED** [review]

**Comment by MitchellGoodwin** [comment]
Thank you for the fix! Sorry it took so long to review.

**Pull request merged**
