### PR TITLE
Remove DismissDirectionCallback

### PR DESCRIPTION
**Pull request by abarth**
This typedef is just an instance of ValueChanged.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @HansMuller

**Comment by Hixie** [comment]
It's not really a value change though, is it? What's the value that's changing?

**Comment by abarth** [comment]
Maybe we should rename ValueChanged?  It's silly to have all these function typedefs.

I guess the value that's changing is the bit for whether this widget has been dismissed.

**Comment by Hixie** [comment]
that would be a bool, then, not a direction. :-)

I think it's fine to have some typedefs with similar or identical signatures. It's useful to be able to hook different dartdocs to different typedefs, and in general it makes the code self-documenting to some extent ("oh, that's reporting that the value changed and the value is a Foo", vs "oh, this indicates that something happened and the additional information about what happened is a Foo").

**Comment by abarth** [comment]
Ok, abandoning.  Thanks!

**Pull request closed without merging**
