### PR TITLE
Store symlinks in package archive

### LINKED ISSUE #77173: Building for macOS target fails when installed from website, codesigning fails with "bundle format is ambiguous"
I am new to Flutter. I am trying to follow the steps in [Test Drive](https://flutter.dev/docs/get-started/test-drive?tab=terminal) to build a macOS app, but the `macos_assemble.sh` script is failing:

     codesign --force --verbose --sign - -- /Users/peter/flutter/myapp/build/macos/Build/Products/Debug/myapp.app/Contents/Frameworks/FlutterMacOS.framework/FlutterMacOS
     /Users/peter/flutter/myapp/build/macos/Build/Products/Debug/myapp.app/Contents/Frameworks/FlutterMacOS.framework/FlutterMacOS: replacing existing signature
     /Users/peter/flutter/myapp/build/macos/Build/Products/Debug/myapp.app/Contents/Frameworks/FlutterMacOS.framework/FlutterMacOS: bundle format is ambiguous (could be app or framework)

To reproduce:

1. `flutter create myapp`
2. `cd myapp`
3. `flutter run`
4. choose macOS

System is macOS 11.2.1, Xcode 12.4 (12D4e), Intel MBP

<details>
<summary>Logs</summary>

Verbose logs are at [this gist](https://gist.github.com/ridiculousfish/96027fb6e13f31a3a1883b2c4c50e8d1)

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.1 20D74 darwin-x64, locale en-US)
    • Flutter version 2.0.0 at /Users/peter/flutter/flutter
    • Framework revision 60bd88df91 (3 hours ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by jmagman**
Compressed publish package should preserve symlinks, or the `FlutterMacOS.framework` will be malformed and the app won't build.

```
--symlinks
              For UNIX and VMS (V8.3 and later), store symbolic links as such in the zip archive, instead of compressing and storing the file referred to by the link.  This can avoid multiple copies of files being included in the archive as zip recurses the directory trees and accesses files directly and by links.
```

Confirmed locally that `zip -9 -r` removed the `FlutterMacOS.framework` symlinks and `zip -9 -r --symlinks` preserves them.

Fixes https://github.com/flutter/flutter/issues/77173.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
```
$ mkdir prepare
$ dart dev/bots/prepare_package.dart --temp_dir prepare --revision 60bd88df915880d23877bfc1602e8ddcf4c4dd2a --branch stable --no-publish 
...
Running "zip -r -9 --symlinks prepare/flutter_macos_2.0.0-stable.zip flutter" in prepare.
```

Unzip `prepare/flutter_macos_2.0.0-stable.zip`
```
$ ls -la prepare/flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework
total 0
drwxr-xr-x   7 magder  primarygroup  224 Mar  3 16:34 .
drwxr-xr-x  13 magder  primarygroup  416 Mar  3 16:34 ..
lrwxr-xr-x   1 magder  primarygroup   29 Mar  3 16:34 FlutterMacOS -> Versions/Current/FlutterMacOS
lrwxr-xr-x   1 magder  primarygroup   24 Mar  3 16:34 Headers -> Versions/Current/Headers
lrwxr-xr-x   1 magder  primarygroup   24 Mar  3 16:34 Modules -> Versions/Current/Modules
lrwxr-xr-x   1 magder  primarygroup   26 Mar  3 16:34 Resources -> Versions/Current/Resources
drwxr-xr-x   4 magder  primarygroup  128 Feb 25 15:07 Versions
```
Symlinks preserved.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by cbracken — APPROVED** [review]

**Comment by jmagman** [comment]
I'm 100% confident this change didn't break 
```
04:01 +3 ~2 -1: test\integration.shard\migrate_test.dart: dart migrate succeeds on module template [E]                                                                                                 
  TimeoutException after 0:01:00.000000: Test timed out after 1 minutes.
  dart:isolate  _RawReceivePortImpl._handleMessage
 ```
Will file an issue for that.

Merging on test failure and red tree so this can be prepped for a cherry-pick. 🤠

**Comment by jmagman** [comment]
> Will file an issue for that.

https://github.com/flutter/flutter/issues/77191

**Pull request merged**
