### PR TITLE
Use 24-hour validation if 24-hour dials are used (#141610)

### PR DESCRIPTION
**Pull request by jukkaleh-atoz**
Replace `MediaQuery.alwaysUse24HourFormatOf(context)` with `use24HourDials` boolean.
If system clock uses 12-hour and Flutter locale uses 24-hours time picker would show 24-hour dials but use 12-hours clock to parse hours. Valid time eg. 20:00 would not pass input validation.
Testing requires intl support and mocking MediaQuery#alwaysUse24HourFormat result. `time_picker_test.dart` didn't seem to allow this easily. Actual fix was simple but I'm unable to write unit test for it.
Change was manually tested

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

https://github.com/flutter/flutter/issues/141610

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

Non breaking change

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by MitchellGoodwin — COMMENTED** [review]
Hi @jukkaleh-atoz. Thank you for taking the time to fix this! This definitely is going to need a test to protect against possible regressions, so let's see what can be done. If my understanding is correct, would wrapping the widget in the test with a `MediaQuery` that is provided a `MediaQueryData` with `alwaysUse24HourFormat` set to false enable the test to work? `MediaQuery` should look up the tree for the first available one, so we tend to manually wrap the widgets with one in the tests, rather than have it default to the system.

**Comment by jukkaleh-atoz** [comment]
@MitchellGoodwin Unfortunately it is not that simple.

> `MediaQuery` that is provided a `MediaQueryData` with `alwaysUse24HourFormat` set to false enable the test to work? 

alwaysUse24HourFormat is false by default because of default locale. To write test for this you need you first be using 24-hour locale and then wrap `MediaQuery `to return with alwaysUse24HourFormat set to false. So you would need to install intl package and provice Locale to MaterialApp. I could not find precedent about this in unit tests

**Comment by MitchellGoodwin** [comment]
Hello @jukkaleh-atoz. If you need to wrap a specific local around specific media query, would [Localizations.override](https://github.com/flutter/flutter/blob/cb05b4e96d7a62866e3a693216b458290d463725/packages/flutter/lib/src/widgets/localizations.dart#L439) work for this case? I do see that we don't seem to test localizations that often in the tests. Then under that localization override you can include the right media query.

**Comment by Piinks** [comment]
Hey @jukkaleh-atoz  thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to re-open or submit a new PR if you have the time to address the review comments. Thanks!

**Comment by ABausG** [comment]
@Piinks I was able to write some tests for this that indeed fail the validation for inputs right now.

What would you suggest is the best way forward for this?

Should I first create a PR on @jukkaleh-atoz branch and this will then get reopened? Or should I cherrypick this change here and open a new PR?

**Comment by MitchellGoodwin** [comment]
> What would you suggest is the best way forward for this?

Please feel free to open a new PR yourself. People are busy and can't always finish their PRs, so the person picking it up should drive it from there. If you can cherrypick the commits from here and build on top of those, so that @jukkaleh-atoz gets credit for the work they've done, that would be ideal. 😃 But please feel free to do what works best.

**Pull request closed without merging**
