### PR TITLE
Upgrade packages in flutter and flutter_test.

### PR DESCRIPTION
**Pull request by polina-c**

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by polina-c** [comment]
@dnfield 

I got this alert: https://golem.corp.goog/Revision?repository=flutter&revision=158393
I do not know who is Golem, but it seems skipping of google tests resulted in a squeezed issue.
Does this mean I should revert the PR?

**Comment by dnfield** [comment]
The Golem failures are failing on the engine build. This should not have affected those.

**Comment by dnfield** [comment]
I think it's likely that the failure was caused by some other change upstream of you, or it's a flake on the build. @whesse might know what's going on?

**Comment by whesse** [comment]
If you reply to the email giving the Golem warning, that gets sent to people who can answer the question. In this case, it is a flaky failure on the Flutter builds on Golem due to our upgrading the OS of the build machines.

**Pull request merged**
