### PR TITLE
fix 23723 rounding error

### PR DESCRIPTION
**Pull request by chunhtai**
## Description

When table expanding its row to fit the maximum width, it will take the maximum width and calculate how much its children should grow, grow it and do the sanity check if its width is at least as big as maximum width. The precision error occur during the calculation and failed the sanity check.

## Related Issues

https://github.com/flutter/flutter/issues/23723

## Tests

I cannot think of a way to write this test, the error occur in an isolate scope. There is only one input which is constraints, it grow its children based on constraint. I will need at least two input to manually simulate the precision error.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by dnfield** [comment]
For the test, could you pump a widget, then pump it again with new constraints to trigger it?

**Comment by chunhtai** [comment]
> For the test, could you pump a widget, then pump it again with new constraints to trigger it?

It will recalculate the tablewidth with the new constraints.

**Comment by chunhtai** [comment]
Also I have been seen this issue more and more, I wonder if there is a better solution that we can solve once and for all... Maybe overriding double comparison method somewhere?

**Comment by dnfield** [comment]
Where exactly is the precision error occurring?

**Comment by chunhtai** [comment]
> Where exactly is the precision error occurring?

https://github.com/chunhtai/flutter/blob/44500da4201b84c5e995dd2a647bd09d43dc43cc/packages/flutter/lib/src/rendering/table.dart#L866

```
if (tableWidth < targetWidth) {
        final double remainingWidth = targetWidth - unflexedTableWidth;
        assert(remainingWidth.isFinite);
        assert(remainingWidth >= 0.0);
        for (int x = 0; x < columns; x += 1) {
          if (flexes[x] != null) {
            final double flexedWidth = remainingWidth * flexes[x] / totalFlex;
            assert(flexedWidth.isFinite);
            assert(flexedWidth >= 0.0);
            if (widths[x] < flexedWidth) {
              final double delta = flexedWidth - widths[x];
              tableWidth += delta;
              widths[x] = flexedWidth;
            }
          }
        }
        assert(tableWidth + precisionErrorTolerance >= targetWidth);
      }
```
unflexedTableWidth and tableWidth should be the same
targetWidth is from constraints,
it basically try to find out the difference between targetWidth and unflexedTableWidth and padding that difference uniformly across table cell and compare the new tableWidth with targetWidth. The error happened during padding the difference

**Review by dnfield — APPROVED** [review]
Talked some more about this.  I'm not sure if we can regroup the math to not need the epsilon here, but the loop makes me nervous with that.  This LGTM.

**Pull request merged**
