### PR TITLE
add a timeout to dashing

### LINKED ISSUE #60647: Make docs-linux test more verbose
When `docs-linux` times out while building the docset, there is very little logging:

```
Building Flutter docset.
Timed out!
```

### LINKED ISSUE #60719: docs-linux failing: "dartdoc failed: type 'FunctionTypeElementType' is not a subtype of type 'DefinedElementType'"
Here's an example: https://cirrus-ci.com/task/5782559529369600?command=main#L114.

It seems to be flaky; it has failed on the last 2 commits on master, but I'm able to reproduce it locally even earlier. In addition, the commits that failed on master passed on pre-submit.

```
dartdoc:stdout: Documenting Flutter...
dartdoc:stdout: Initialized dartdoc with 126 libraries in 187.9 seconds
dartdoc:stdout: Generating docs for library animation from package:flutter/animation.dart...
dartdoc:stderr:
dartdoc:stderr: dartdoc failed: type 'FunctionTypeElementType' is not a subtype of type 'DefinedElementType'
dartdoc:stderr: package:dartdoc/src/model/method.dart 102:39                                    Method.modelType
dartdoc:stderr: package:dartdoc/src/model/method.dart 99:34                                     Method.linkedReturnType
dartdoc:stderr: dart:mirrors                                                                    _InstanceMirror.getField
dartdoc:stderr: package:mustache/src/renderer.dart 245:29                                       Renderer._getNamedProperty
dartdoc:stderr: package:mustache/src/renderer.dart 212:16                                       Renderer.resolveValue
dartdoc:stderr: package:mustache/src/renderer.dart 90:17                                        Renderer.visitVariable
dartdoc:stderr: package:mustache/src/node.dart 45:43                                            VariableNode.accept
dartdoc:stderr: package:mustache/src/renderer.dart 64:53                                        Renderer.render.<fn>
dartdoc:stderr: dart:_internal                                                                  ListIterable.forEach
dartdoc:stderr: package:mustache/src/renderer.dart 64:36                                        Renderer.render
dartdoc:stderr: package:mustache/src/renderer.dart 195:16                                       Renderer.visitPartial
dartdoc:stderr: package:mustache/src/node.dart 81:43                                            PartialNode.accept
dartdoc:stderr: package:mustache/src/node.dart 66:37                                            SectionNode.visitChildren.<fn>
dartdoc:stderr: dart:core                                                                       List.forEach
dartdoc:stderr: package:mustache/src/node.dart 66:14                                            SectionNode.visitChildren
dartdoc:stderr: package:mustache/src/renderer.dart 184:10                                       Renderer._renderWithValue
dartdoc:stderr: package:mustache/src/renderer.dart 126:28                                       Renderer._renderSection.<fn>
dartdoc:stderr: dart:core                                                                       Iterable.forEach
dartdoc:stderr: package:mustache/src/renderer.dart 126:13                                       Renderer._renderSection
dartdoc:stderr: package:mustache/src/renderer.dart 115:7                                        Renderer.visitSection
dartdoc:stderr: package:mustache/src/node.dart 63:43                                            SectionNode.accept
dartdoc:stderr: package:mustache/src/node.dart 66:37                                            SectionNode.visitChildren.<fn>
dartdoc:stderr: dart:core                                                                       List.forEach
dartdoc:stderr: package:mustache/src/node.dart 66:14                                            SectionNode.visitChildren
dartdoc:stderr: package:mustache/src/renderer.dart 184:10                                       Renderer._renderWithValue
dartdoc:stderr: package:mustache/src/renderer.dart 130:7                                        Renderer._renderSection
dartdoc:stderr: package:mustache/src/renderer.dart 115:7                                        Renderer.visitSection
dartdoc:stderr: package:mustache/src/node.dart 63:43                                            SectionNode.accept
dartdoc:stderr: package:mustache/src/node.dart 66:37                                            SectionNode.visitChildren.<fn>
dartdoc:stderr: dart:core                                                                       List.forEach
dartdoc:stderr: package:mustache/src/node.dart 66:14                                            SectionNode.visitChildren
dartdoc:stderr: package:mustache/src/renderer.dart 184:10                                       Renderer._renderWithValue
dartdoc:stderr: package:mustache/src/renderer.dart 144:7                                        Renderer._renderSection
dartdoc:stderr: package:mustache/src/renderer.dart 115:7                                        Renderer.visitSection
dartdoc:stderr: package:mustache/src/node.dart 63:43                                            SectionNode.accept
dartdoc:stderr: package:mustache/src/renderer.dart 58:30                                        Renderer.render.<fn>
dartdoc:stderr: dart:core                                                                       List.forEach
dartdoc:stderr: package:mustache/src/renderer.dart 58:13                                        Renderer.render
dartdoc:stderr: package:mustache/src/template.dart 40:14                                        Template.render
dartdoc:stderr: package:mustache/src/template.dart 33:5                                         Template.renderString
dartdoc:stderr: package:dartdoc/src/generator/dartdoc_generator_backend.dart 59:31              DartdocGeneratorBackend.render
dartdoc:stderr: package:dartdoc/src/generator/dartdoc_generator_backend.dart 112:5              DartdocGeneratorBackend.generateClass
dartdoc:stderr: package:dartdoc/src/generator/generator_frontend.dart 61:29                     GeneratorFrontEnd._generateDocs
dartdoc:stderr: package:dartdoc/src/generator/generator_frontend.dart 23:5                      GeneratorFrontEnd.generate
dartdoc:stderr: package:dartdoc/dartdoc.dart 167:23                                             Dartdoc.generateDocsBase
dartdoc:stderr: ===== asynchronous gap ===========================
dartdoc:stderr: package:dartdoc/dartdoc.dart 194:43                                             Dartdoc.generateDocs
dartdoc:stderr: dart:async                                                                      runZoned
dartdoc:stderr: /root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.31.0/bin/dartdoc.dart 95:13  main.<fn>
dartdoc:stderr: package:stack_trace                                                             Chain.capture
dartdoc:stderr: /root/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.31.0/bin/dartdoc.dart 94:17  main
dartdoc:stderr:
```

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

1. Upgrade dartdocs to latest on pub to fix https://github.com/flutter/flutter/issues/60719
1. Time out dashing after half an hour to beat Cirrus 1 hour timeout and ensure logs are tailed. Hopefully this allows us to debug https://github.com/flutter/flutter/issues/60646.
1. After testing to confirm it works, disable generation of docset on pre-submit. It will still be generated on post-submit.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/60719 by upgrading dartdocs
Fixes https://github.com/flutter/flutter/issues/60647 by timing out dashing
Hopefully will allow debugging https://github.com/flutter/flutter/issues/60646

## Tests

This PR makes improvements to the existing docs-linux test.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by christopherfujino** [comment]
FYI @gspencergoog i just pushed another commit to skip generating dashing on pre-submit. but it will still generate on post-submit for master. if we can't fix https://github.com/flutter/flutter/issues/60646, we can consider either resuming the test on a dashing failure, or skipping generation of the docset altogether on master.

**Review by gspencergoog — COMMENTED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Still LGTM

**Review by gspencergoog — APPROVED** [review]

**Comment by christopherfujino** [comment]
Landing on red tree to fix the build.

**Pull request merged**
