### PR TITLE
docs cleanup

### PR DESCRIPTION
**Pull request by devoncarew**
- delete unused files, now that the chromium bot script has been updated
- tweak the styles for the generated docs (for more consistent fonts on the pages)

### CODE REVIEW

**Comment by devoncarew** [comment]
@sethladd @qchong

**Comment by sethladd** [comment]
Where did the analytics go?

**Comment by devoncarew** [comment]
Hereabouts: https://github.com/flutter/flutter/tree/master/dev/docs

**Comment by abarth** [comment]
LGTM

**Pull request merged**
