### PR TITLE
Roll engine to d2b69fec751d6d11f62019c863b2cba4ce575bfe

### PR DESCRIPTION
**Pull request by tvolkert**
Includes:
* Require armv7 in create_ios_framework.py (flutter/engine#4944)
* Enable Image encoding by leveraging existing Skia functionality (flutter/engine#4762)

### CODE REVIEW

**Comment by Hixie** [comment]
This had a regressive impact on our release binary size. Was that expected?

**Comment by tvolkert** [comment]
/cc @cbracken 

@Hixie if it's just for iOS, it's likely the inclusion of armv7.

**Comment by Hixie** [comment]
That was a few commits earlier.

**Comment by tvolkert** [comment]
FTR, there were two engine commits contained in this roll:

* https://github.com/flutter/engine/commit/b6f466b344108731e26dbdf44a11a3c98d70f696 -- Enable Image encoding by leveraging existing Skia functionality
* https://github.com/flutter/engine/commit/d2b69fec751d6d11f62019c863b2cba4ce575bfe -- Require armv7 in create_ios_framework.py

**Comment by Hixie** [comment]
The one that really increased the binary size was https://github.com/flutter/flutter/commit/2134adce6deb4dd471b0b6d3baf931b22e80f84d, which includes "Add armv7 support to create_ios_framework script". What's the additional code that this roll adds that wasn't added before? (This roll had a much smaller impact than the other.)

**Comment by cbracken** [comment]
On 2134adce6deb4dd471b0b6d3baf931b22e80f84d: the additional size there is expected and we should either re-baseline or rewrite the benchmark such that we have two (an armv7 one where we lipo away arm64, and an arm64 one where we lipo away armv7).

flutter/engine#4944 (patching the script we use to generate Flutter.framework) should have had no effect on size in this roll since we didn't actually start using the new params on the script here, that leaves flutter/engine#4762 as the most likely candidate.

**Comment by tvolkert** [comment]
Moving discussion to flutter/engine#4762

**Pull request merged**
