### PR TITLE
Fix bug for calling isEmpty on null object.

### PR DESCRIPTION
**Pull request by xuexin**
If Locale's _countryCode is null, calling isEmpth on null object.
And Locale.toString() work fine here.

### CODE REVIEW

**Comment by xuexin** [comment]
I signed it!

**Comment by HansMuller** [comment]
Nice fix, thank you! 

To complete this PR we'll need a small regression test. You can add one to /usr/local/google/home/hansmuller/github/flutter/packages/flutter_localizations/test

**Comment by xuexin** [comment]
I'm sorry, I don't know how to run a test on flutter.
Could you give me some guide for that?

**Comment by xuexin** [comment]
How about this?
Please review it.

**Comment by HansMuller** [comment]
Thanks for providing the test! Your pull request LGTM.

I will land your change as soon as that's possible.

**Pull request merged**
