### PR TITLE
[flutter_tools] update dart cache clear hint

### PR DESCRIPTION
**Pull request by codenoid**
This pull request proposes to update the output message of `flutter doctor` when encountering issues related to the Dart cache. Currently, it suggests using the command `dart pub cache clear` which doesn't exist. Instead, it should recommend using `dart pub cache clean` as it is the correct command to clear Dart's cache.

Steps to reproduce the issue:

1. Run `flutter doctor`.
2. If an existing Pub cache issue is found, the output message includes a suggestion to run `dart pub cache clear`.

### Expected Result:

The output message should suggest running `dart pub cache clean` to clear Dart's cache.

### Actual Result:

The output message suggests running `dart pub cache clear`, which is not a valid Dart command.

image
image

```
flutter --version
Flutter 3.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9cd3d0d9ff (8 days ago) • 2023-05-23 20:57:28 -0700
Engine • revision 90fa3ae28f
Tools • Dart 3.0.2 • DevTools 2.23.1
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by christopherfujino — COMMENTED** [review]
Thanks for this fix. Can you add a test to [this file](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/dart/pub_get_test.dart#L250) that verifies the updated text is in the `logger`?

**Comment by christopherfujino** [comment]
Your test is failing on CI:

```
01:24 +2359 ~2 -1: test/general.shard/dart/pub_get_test.dart: shouldSkipThirdPartyGenerator skips pub get if the package config "generator" is different than "pub" [E]                                
  Expected: contains 'It can be reset by running `dart pub cache clean`'
    Actual: 'Skipping pub get: generated by third-party.\n'
              ''
     Which: does not contain 'It can be reset by running `dart pub cache clean`'
  
  package:matcher                                  expect
  test/general.shard/dart/pub_get_test.dart 249:7  main.<fn>.<fn>
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8778805477762119169/+/u/run_test.dart_for_tool_tests_shard_and_subshard_general/test_stdout

**Comment by christopherfujino** [comment]
Thanks for submitting this, however, it was since fixed in https://github.com/flutter/flutter/pull/128171.

**Comment by codenoid** [comment]
Well that's break my heart

But I understand that because of lack of skills, I'm not able to contribute the correct code as it suppose to be.

Sincerely, codenoid

**Comment by christopherfujino** [comment]
> Well that's break my heart
> 
> But I understand that because of lack of skills, I'm not able to contribute the correct code as it suppose to be.

It's definitely not because of a lack of skills. As this was a high profile bug, we had many PRs submitted to fix it, however only one had tests that were all passing, so I merged that one.

Please don't be discouraged from contributing in the future. To maximize the odds your PR is merged, I would suggest:

1. ensure the change you want to make is being tracked by an issue. ensure that tracking issue is not already assigned to someone.
2. If it is a non-trivial change (this was a trivial change), outline your general approach first in the issue and try to get approval from a maintainer. This is not required, but it may save you from spending time working on a feature and having a reviewer say, "I actually don't agree with this approach, sorry I have to close this PR".
3. Ensure you follow all the steps in the PR template checklist (I believe you checked that the PR had tests before you wrote one)
4. Once you open the PR, ensure all the CI checks are passing. If they're not, investigate the failures and try to fix them.

Good luck!

**Pull request closed without merging**
