### PR TITLE
Unskip the bidi semantics test.

### PR DESCRIPTION
**Pull request by Hixie**
...and make it match what we do, even though it's a bit weird.

cc @jonahwilliams who (if blamed is to be believed) added this test.

### CODE REVIEW

**Comment by Hixie** [comment]
History in https://github.com/flutter/flutter/issues/20891

**Review by jonahwilliams — APPROVED** [review]
RSLGTM

**Comment by Hixie** [comment]
Yeah, RSLGTM is how I feel about this too. :-)

**Comment by Hixie** [comment]
@ferhatb @yjbanov Looks like a11y is broken with bidi on Web, do you want me to file a bug and just skip the test for now?

(When I say broken, I mean it's different on Web than on every other platform.)

**Comment by Hixie** [comment]
@yjbanov says that I should file a bug and skip on Web for now.

**Comment by Hixie** [comment]
Filed https://github.com/flutter/flutter/issues/62945.

**Comment by Hixie** [comment]
PTAL

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
