### PR TITLE
Skip failing input tests

### PR DESCRIPTION
**Pull request by lukechurch**
@Hixie This disables the input tests that are failing on OS X (https://github.com/flutter/flutter/issues/6961).

Disabling other tests in a follow on PR.

### CODE REVIEW

**Comment by abarth** [comment]
Why are these tests failing?  Shouldn't we fix them instead of disabling them?

**Comment by lukechurch** [comment]
@abarth I think @Hixie plans to fix them, he suggested that disable them now so we can get a reliably clean build on OS X. Of course it's entirely possible I've misunderstood something.

**Comment by abarth** [comment]
Maybe we should skip them only `Platform.isMacOS` is true?

**Comment by Hixie** [comment]
Yeah let's skip them only on Mac, so that at least we don't regress them further.

@abarth Turns out our tests are broken on Mac. I'm all for fixing them, but I figured (a) that wasn't luke's problem, and (b) I'd rather we disable the broken tests then turn on the testing on bots, than continue not testing them on mac at all.

**Comment by abarth** [comment]
ok

**Comment by lukechurch** [comment]
@abarth @Hixie: PTAL

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
