### PR TITLE
Updated the M3 textTheme to use `onSurface` color for all styles.

### PR DESCRIPTION
**Pull request by darrenaustin**
Prior to M3 the Material Design spec had different colors for the standard text styles. Some were dark grey, while others where light gray. With M3 they should all use `onSurface` from the `colorScheme`.

| M2  Colors | M3 Colors |
| ------------- | ------------- |
| Screen Shot 2022-11-28 at 10 37 17 AM | Screen Shot 2022-11-28 at 2 58 24 PM |

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by guidezpl** [comment]
Removed autosubmit label, as I'm not sure this is right. It seems to be `onSurface`. See b/238318341 for context.

**Comment by darrenaustin** [comment]
> Removed autosubmit label, as I'm not sure this is right. It seems to be `onSurface`. See b/238318341 for context.

Thanks, I hadn't seen that. `onSurface` might be a bit tricky, as it is dependent on the surrounding colorScheme. When creating a Typography we need both 'black' and 'white' sets of colors. When we create the default typography, it is only for one colorScheme, not both light and dark.

**Comment by darrenaustin** [comment]
Ok, I switched to using `onSurface` (and `surface` for the opposite color in the Typography). Let me know what you think.

**Review by HansMuller — APPROVED** [review]
LGTM

**Review by guidezpl — APPROVED** [review]
Seems reasonable to use `surface` for the opposite color

```
  _    ___ _____ __  __ 
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
                        
```

**Pull request merged**
