### PR TITLE
Added Malay (ms) locale

### PR DESCRIPTION
**Pull request by zulfahmi93**

### CODE REVIEW

**Comment by zulfahmi93** [comment]
@Hixie thanks for the update. I am not rushing but the ms translation is needed for the app that I'm developing for my start-up.

**Comment by HansMuller** [comment]
Thanks for your contribution! I've landed the changes in a separate PR to bring along the latest updates to the message catalog: https://github.com/flutter/flutter/pull/17121

In a week or so "official" Google Malay translations for all of the messages will roll into Flutter.  If any of them don't look right to you, please file an issue.

Thanks again.

**Comment by zulfahmi93** [comment]
Thanks!

**Pull request closed without merging**
