### PR TITLE
Enable hot mode by default. --no-hot disables it

### PR DESCRIPTION
**Pull request by johnmccutchan**
@eseidelGoogle @sethladd

### CODE REVIEW

**Comment by sethladd** [comment]
How does this impact our internal build system? (if at all)

**Comment by yjbanov** [comment]
Could you please test `dev/benchmarks/complex_layout` with the following commands?

```sh
# This command should exit automatically immediately after the app starts and
# it should print startup metrics to the console. If it runs in the resident mode
# then something's wrong
flutter run --profile --trace-startup

# This command just checks that driver tests still function after this change
flutter drive --profile --trace-startup -t test_driver/scroll_perf.dart
```

Thanks.

**Comment by sethladd** [comment]
Closes https://github.com/flutter/flutter/issues/5280

**Comment by eseidelGoogle** [comment]
I don't know how to evaluate this change.  I'm *suuuuuper* excited to see it.  Just no clue how to weigh yes/no.

**Comment by Hixie** [comment]
I support this change but we should make sure we test hot reload so it doesn't break again. (Ahem.)

**Comment by eseidelGoogle** [comment]
Does the Atom plugin need to know about this change? (to remove the checkbox it has now).  @devoncarew

**Comment by devoncarew** [comment]
I'll double check, but I believe the logic is written to go by what the daemon protocol returns to us when we launch an app, not by what we send in as the setting.

**Comment by johnmccutchan** [comment]
@yjbanov --profile mode doesn't support hot mode so those two commands will still use the existing runner.

@Hixie I have a benchmark that can act as an integration test of hot reload and hot restart.

@eseidelGoogle I'll hold off on pulling the switch until you give me the OK. I created this CL to kick start this conversation.

**Comment by eseidelGoogle** [comment]
I suspect we should land this on a Monday AM, instead of a Friday PM.  But
honestly I'm hugely in favor of this idea.  You have my support.  I'd like
us to try and fail and rollout if needed.  So lgtm, just don't let that
override others.

Please communicate this to at least the internal list once you've landed.
Thanks!

**Comment by johnmccutchan** [comment]
PTAL. I'd like to land this today and see what starts to burn.

**Comment by sethladd** [comment]
Yes, let's turn this on.

**Comment by dragostis** [comment]
LGTM.

**Comment by johnmccutchan** [comment]
Just finishing the benchmark / integration test CL before landing this.

**Comment by eseidelGoogle** [comment]
I'm very confused as to why @coveralls is commenting on a 2 year old PR.

**Pull request merged**
