### PR TITLE
Reland change that speeds up multiple devices hot-reload

### PR DESCRIPTION
**Pull request by aam**
This relands change to reload on multiple devices faster( https://github.com/flutter/flutter/pull/22693 ) with the fix to the refreshViews issue that caused the revert (89665ac).

### CODE REVIEW

**Review by jason-simmons — APPROVED** [review]

**Comment by Hixie** [comment]
This dramatically improved the one-device hot reload benchmark, and dramatically regressed the hot restart benchmark. Is that expected?

**Comment by aam** [comment]
I didn't expect it.

**Comment by aam** [comment]
Regarding increased restart benchmark. What is happening is that `_flutter.listViews` RPC message used to be delivered to UI isolate where it was processed right away. Now  `_flutter.listViews` is sent to service isolate, had to be enqueued to get processed on UI isolate thread. And it stays enqueued for quite a while - until dart compiles all dart code and flutter engine is able to produce first frame.

See "before" and "after" json file loadable into `chrome://tracing` - look for ListViewStart, ListViewBeforeWait, ListViewCallback, ListViewAfterWait events.

[dart-timeline.zip](https://github.com/flutter/flutter/files/2531999/dart-timeline.zip)

**Comment by Hixie** [comment]
k, thanks.

**Comment by aam** [comment]
And hot reload performance benchmark improvement should be attributed to the same change in timing as to when `_flutter.listViews` request sent out as part of hot restart finishes processing. Since hot restart and hot reload benchmarks are assessed back to back - time spent in getting restart completed used to be counted as a part of hot reload, rather than host restart benchmark, but now it is properly accounted towards hot restart.

**Pull request merged**
