### PR TITLE
[flutter_tool] Don't crash on a failure to write to std{out,err}

### PR DESCRIPTION
**Pull request by zanderso**
## Description

When stdout and stderr are pipes, writing to them can throw an exception when the other side of the pipes are closed. This can happen e.g. when the tool is spawned as a subprocess of gradle or an IDE.

This PR wraps stdio writes in a `try {} catch {}` with the callsite able to provide a fallback, which defaults to `print()`.

## Related Issues

Frequent crasher on recent dev channel builds.

## Tests

I added the following tests:

Added a test to logger_test.dart.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Comment by zanderso** [comment]
Added fixes for tests that were failing. ptal.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Do you think there is any room for linting/analysis here to keep us from regressing in any additional functionality we add?

**Comment by zanderso** [comment]
> Do you think there is any room for linting/analysis here to keep us from regressing in any additional functionality we add?

Yeah, I'm going to see what I can remove from what is exported by io.dart in a follow-up PR.

**Pull request merged**
