### PR TITLE
preserve detailFiles entry in TaskResult JSON

### PR DESCRIPTION
**Pull request by flar**
We used to have the detailFiles available at the point where we printed out the log and/or tried to upload them to the GCS buckets, but recently the necessary information has been missing from the results. It looks like we now translate the original TaskResult produced by the benchmarks into JSON and back to a TaskResult and the detailFiles got lost in the transition.

Adding the missing code in fromJson to restore the data...

### CODE REVIEW

**Comment by flar** [comment]
In my recent commit that fixes the tests I noticed that the handling of benchmarkScoreKeys and detailFiles and whether they are null or an empty list varied by constructor and by success/failure. I decided to normalize their handling so that all constructors will default them to empty lists for the "success" constructors and to nulls for the "failure" constructors. Note that this isn't enforced strictly with asserts and all, it is just the norm.

**Review by liyuqian — APPROVED** [review]
LGTM. Question for @keyonghan and infra team in general: for this kind of change, is there any unit test that we can follow, or is the convention to just let the device lab run it and see if it fails?

**Comment by keyonghan** [comment]
> LGTM. Question for @keyonghan and infra team in general: for this kind of change, is there any unit test that we can follow, or is the convention to just let the device lab run it and see if it fails?

AFAIK, https://github.com/flutter/flutter/tree/master/dev/devicelab/test are the unit tests available.

**Comment by dnfield** [comment]
I was just disappoitned to find that a test I'm looking for the complete timeline for does not actually have it.

@keyonghan @flar  any reason we can't just turn this on by default for all tests?

**Comment by flar** [comment]
> I was just disappoitned to find that a test I'm looking for the complete timeline for does not actually have it.
> 
> @keyonghan @flar any reason we can't just turn this on by default for all tests?

Which test? They don't exist for e2e bechmarks.

**Comment by dnfield** [comment]
Yeah, I dug into this a bit more and realized we're not preserving the timeline anyway for e2e tests. I think we should fix that but we don't need to trace startup for that either. I'll file a separate issue.

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/issues/108046

**Pull request merged**
