### PR TITLE
Made a few grammatical edits

### PR DESCRIPTION
**Pull request by mikeshatch**
## Description

Proposed edits: 

ObjectiveC ==> Objective-C
uses mainly ==> mainly uses (2)

### CODE REVIEW

**Comment by mikeshatch** [comment]
> I signed it!

**Review by willlarche — APPROVED** [review]
Thank you!

**Comment by willlarche** [comment]
So to merge this I have some annoying requests to satisfy the lawyer cats:

1. Sign the CLA with your email address (if you haven't already.)
1. Rebase this commit on your local machine that's setup with your email address in your git config so it's signed by you.
1. Force push to your branch. 

Right now, the commit is signed by your username at github users.com (I'm guessing because you wrote it in the GitHub tool directly.)

See also the instructions above for Individual Contributors.

**Comment by mikeshatch** [comment]
> So to merge this I have some annoying requests to satisfy the lawyer cats:
> 
> 1. Sign the CLA with your email address (if you haven't already.)
> 2. Rebase this commit on your local machine that's setup with your email address in your git config so it's signed by you.
> 3. Force push to your branch.
> 
> Right now, the commit is signed by your username at github users.com (I'm guessing because you wrote it in the GitHub tool directly.)
> 
> See also the instructions above for Individual Contributors.

Hi Will. You're welcome. I did actually sign the agreement (https://cla.developers.google.com/clas) last night, and then wrote "I signed it!" afterwards in the area requested. For the second two steps, how should I now go about it if I did this via github directly on the website?

**Pull request closed without merging**
