### PR TITLE
Add git config option to automatically convert CRLF to LF

### LINKED ISSUE #8121: Figure out how to prevent Windows line endings from getting checked in
e.g. some kind of a test that fails when it sees windows line endings.

### PR DESCRIPTION
**Pull request by goderbauer**
See "End-of-line conversion" in https://git-scm.com/docs/gitattributes

fixes https://github.com/flutter/flutter/issues/8121

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

I seem to remember that there's some disadvantage to doing this, but let's try it and see how it goes.  I could be I'm mis-remembering some crazy SVN thing.

**Comment by Hixie** [comment]
This is terrifying. How does git know what's a text file?

**Comment by goderbauer** [comment]
Happy to roll this back if it causes any issue. However, that's the setting the internet is pointing to to fix the issue we are having.

Are there any non-text files in the repo that might be affected by this?

**Comment by Hixie** [comment]
We do have some images (e.g. icons).

**Comment by goderbauer** [comment]
OK, if any of those types show issues in the future, they can easily be excluded from the conversion by adding a line to this `.gitattributes` file.

**Comment by abarth** [comment]
Yeah.  I think I'm thinking of SVN's auto line endings, which do something different (and a bit crazy).

**Comment by goderbauer** [comment]
I verified that this setting doesn't want to "convert" any of our non-text files (PNGs, ZIPs, etc). It only wanted to convert `dev/bots/VERSION_WINDOWS_SDK` and `dev/bots/test.dart`, which have been checked in with the wrong CRLF line ending. I added them to this PR with the correct LF line ending.

**Comment by goderbauer** [comment]
I extended the `.gitattributes` file a little bit to list files that should always be normalized to LF and (binary) files that should never be normalized. This list is based on file types we actually have in the repo.

@Hixie What do you think? Does this make it less terrifying for you?

**Comment by Hixie** [comment]
Still terrifying, but LGTM. :-)

**Pull request merged**
