### PR TITLE
Improve test.dart output

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
cc @amirh

**Review by amirh — APPROVED** [review]
LGTM

can you include before and after sample outputs in the PR description?

**Comment by Hixie** [comment]
It adds lines like `SHARD=analyze` to each shard, and a message like `Contents of packages/flutter_localizations/lib/src/l10n/localizations.dart matches output of gen_localizations.dart script.`  to the analysis shard.

**Comment by xster** [comment]
LG

**Pull request merged**
