### PR TITLE
[CP-stable]Reland "Upgrade template Gradle, App AGP, Module AGP, and Kotlin versions, and tests"... but no longer upgrade module AGP version

### PR DESCRIPTION
**Pull request by flutteractionsbot**
This pull request is created by [automatic cherry pick workflow](https://github.com/flutter/flutter/blob/main/docs/releases/Flutter-Cherrypick-Process.md#automatically-creates-a-cherry-pick-request)
Please fill in the form below, and a flutter domain expert will evaluate this cherry pick request.

### Issue Link:
What is the link to the issue this cherry-pick is addressing?

https://github.com/flutter/flutter/issues/153885#issue-2479189666

### Changelog Description:
Explain this cherry pick in one line that is accessible to most Flutter developers. See [best practices](https://github.com/flutter/flutter/blob/main/docs/releases/Hotfix-Documentation-Best-Practices.md) for examples

Upgrades template Gradle, App AGP, and Kotlin versions.

### Impact Description:
What is the impact (ex. visual jank on Samsung phones, app crash, cannot ship an iOS app)? Does it impact development (ex. flutter doctor crashes when Android Studio is installed), or the shipping production app (the app crashes on launch)

Fixes some log spam when building a freshly created template app for Android.

### Workaround:
Is there a workaround for this issue?

Yes, just upgrade the output of the template manually.

### Risk:
What is the risk level of this cherry-pick?

  - [ ] Low
  - [x] Medium
  - [ ] High

### Test Coverage:
Are you confident that your fix is well-tested by automated tests?

  - [x] Yes
  - [ ] No

### Validation Steps:
What are the steps to validate that this fix works?

`flutter create foo`, `cd foo`, `flutter build apk`

### CODE REVIEW

**Comment by reidbaker** [comment]
@gmackall to update pr description. 
@camsim99 as "TL" review for risk and double check that this CP will fix the issue in the description 
@reidbaker (myself) as the release engineer.

**Comment by gmackall** [comment]
Updated. I'll still need to figure out why this one test is failing though - it didn't fail on the original PR.

**Comment by gmackall** [comment]
I updated the AGP version in the test that was failing. This test was refactored on master, which is why this change wasn't made on the master version of the pr

**Review by reidbaker — APPROVED** [review]
Approved % approval from @camsim99.

**Review by gmackall — APPROVED** [review]
LGTMyself

**Pull request merged**
