### PR TITLE
Fix Horizontal Stepper Overflows Title issue

### LINKED ISSUE #40601: Horizontal Stepper Overflows Title (with no way to allow for scrolling)
## Steps to Reproduce

1. Create a stepper with 5+ steps with any title such as "Step Title"
2. Make its direction horizontal
3. The Stepper widget puts step icons into a row until it overflows the screen, with no way to make it scroll

```
Stepper(
            type: StepperType.horizontal,
            currentStep: currentStep,
            steps: <Step>[
              Step(
                  content: Text('content'),
                  title: Text('title'),
                  isActive: currentStep == 0),
              Step(
                  content: Text('content'),
                  title: Text('title'),
                  isActive: currentStep == 1),
              Step(
                  content: Text('content'),
                  title: Text('title'),
                  isActive: currentStep == 2),
              Step(
                  content: Text('content'),
                  title: Text('title'),
                  isActive: currentStep == 3),
              Step(
                  content: Text('content'),
                  title: Text('title'),
                  isActive: currentStep == 4),
              Step(
                  content: Text('content'),
                  title: Text('title'),
                  isActive: currentStep == 5),
              Step(
                  content: Text('content'),
                  title: Text('title'),
                  isActive: currentStep == 6),
            ],
          )
```

Wrapping the stepper with a horizontal `SingleChildScrollView` does not fix the issue.

`Stepper._buildHorizontal`

```
        Material(
          elevation: 2.0,
          child: Container(
            margin: const EdgeInsets.symmetric(horizontal: 24.0),
            child: Row(
              children: children,
            ),
          ),
        ),
```

As you can see from the source code which builds the title row with steps and titles, there is no capability to scroll over overflow gracefully at all. If the `children` of the `row` don't fit on the screen, it will overflow.

### PR DESCRIPTION
**Pull request by thejitenpatel**
This PR fixes the issue of scrolling the Stepper widget horizontally, enabling smooth horizontal scrolling for cases with more than N no. of steps( #40601 ).

Fixes #40601 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by thejitenpatel** [comment]
Hi @Piinks can you please help me out in this PR?

**Comment by thejitenpatel** [comment]
@HansMuller I have updated this branch.

**Comment by thejitenpatel** [comment]
Hi @HansMuller Any update?

**Comment by HansMuller** [comment]
@ihorkozar - what do you think of this PR?

**Review by HansMuller — COMMENTED** [review]
This seems like a breaking change: the previous version would expand to fill the available space with step-connection lines. What defines the length of the connection lines in this version for cases where the entire stepper will fit within the available width?

**Comment by thejitenpatel** [comment]
Hi @Piinks @HansMuller and @ihorkozar any updates? What you think of this PR?

**Comment by ihorkozar** [comment]
@thejitenpatel  In my opinion, this solution is acceptable and I myself use something similar to it to create my own stepper, but @HansMuller correctly noted that such a solution removes the length of the connection lines completely. It is necessary to make sure that when there is enough space, the old behavior is preserved, and when there is not enough, there is a new one. I didn't have time to do this, so I made a separate package and did not do PR, I am satisfied with the new behavior, but it will not suit everyone.

**Comment by thejitenpatel** [comment]
Hi @ihorkozar ,

Thank you for getting back to me. I understand your and @HansMuller 's concerns. Now, the question is, will this issue persist in Flutter?

**Comment by HansMuller** [comment]
@thejitenpatel - the question posed in https://github.com/flutter/flutter/pull/135357#pullrequestreview-1674865234 still needs to be answered before this PR can proceed. Since it's been a couple of months I'm going to close the PR for now. Feel free to reopen it if you'd like to continue working on it.

**Comment by alikhavarii13** [comment]
no solution yet

**Pull request closed without merging**
