### PR TITLE
Specify destination when building for macOS

### LINKED ISSUE #86590: On Xcode 13 "flutter run -d macos" prints warning that there are multiple matching destinations, "arch:x86_64" and "name:Any Mac"
With Xcode 13 installed, red error text warns there are multiple macOS targets:
```
$ flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
2021-07-16 16:25:46.183 xcodebuild[6946:113333223] [MT] DVTPlugInManager: Required plug-in compatibility UUID 42E1F17B-27B3-4DE8-92A8-DC76BA4F5921 for DVTCoreGlyphs.framework (com.apple.dt.DVTCoreGlyphs) not present
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:87BE7059-56E3-5470-B52D-31A0F76402B3 }
{ platform:macOS, name:Any Mac }
Building macOS application...                                           
Syncing files to device macOS...                                    33ms
```
Screen Shot 2021-07-16 at 4 26 29 PM

The app successfully runs.

This does not reproduce on Xcode 12.

```
$ flutter doctor -v
[✓] Flutter (Channel unknown, 2.4.0-5.0.pre.81, on macOS 11.3.1 20E241 darwin-x64, locale
    en-US)
    • Flutter version 2.4.0-5.0.pre.81 at /Users/magder/Projects/flutter
    • Upstream repository unknown
    • Framework revision 7cc853f14f (33 minutes ago), 2021-07-16 15:54:02 -0700
    • Engine revision 26b6520a0c
    • Dart version 2.14.0 (build 2.14.0-321.0.dev)

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Users/magder/Applications/Xcode-13_beta2.app/Contents/Developer
    • Xcode 13.0, Build version 13A5155e
    • CocoaPods version 1.10.1

[✓] Connected device (4 available)
    • iPhone 6s (mobile) • d83d5bc53967baa0ee18626ba87b6254b2ab5418 • ios            • iOS
      13.7 17H35
    • iPhone 11 (mobile) • 81AD29E5-17EB-465A-B62D-1E3DE07E9B75     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                    • darwin-x64     •
      macOS 11.3.1 20E241 darwin-x64
```

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/86590

I do not have access to an arm64 mac to test that this still works. It will probably need to be modified a bit for that use case when we support building arm64 binaries.

### CODE REVIEW

**Comment by dnfield** [comment]
We could probably make this a little more robust by invoking `xcodebuild -scheme Runner -destinations` and parsing the output, but I don't see a good way to make that machine readable...

**Comment by dnfield** [comment]
@christopherfujino I'll try patching that in with this one and seeing what happens, but again I only have an x64 mac to test on right now :)

**Comment by dnfield** [comment]
Based on local testing I don't need the target arch specifier and Xcode still won't complain.

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
Verified manually after landing #100271 and this lgtm (again).

**Comment by rohintoncollins** [comment]
This appears now to be a problem for arm64 (m1) Macs:
```
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-000944861E33001E }
{ platform:macOS, arch:x86_64, id:00008103-000944861E33001E }
```
although it is just a warning and the app does launch, the last 2 lines are in red, which suggests that this is an error, when it really isn't.

**Comment by jmagman** [comment]
> This appears now to be a problem for arm64 (m1) Macs:

Tracking that issue in https://github.com/flutter/flutter/issues/86590

**Pull request merged**
