### PR TITLE
Always reserve space for error text in text fields.

### LINKED ISSUE #6943: Input/InputContainer error should not animate the underline
If you look at the [errors in material design](https://material-design.storage.googleapis.com/publish/material_v_9/0Bzhp5Z4wHba3SjZ2SkgwTERaVkU/components_textfields_single4.png), you can see that the error message is simply appended to the bottom of the container w/o moving the underline.

Please take material team's suggestions on whether the error space should be pre-allocated in the InputContainer. Our team found that pre-allocation causes forms sizes to grow significantly however our UX was not picky on this.

### PR DESCRIPTION
**Pull request by mpcomplete**
Fixes https://github.com/flutter/flutter/issues/6943

### CODE REVIEW

**Comment by Hixie** [comment]
Doesn't this mean we have an animation that used to do something that now doesn't do something? I thought we animated the underline up when you added an error before.

**Comment by abarth** [comment]
It's an AnimatedContainer.  That's still useful for animating the color change for the divider.

**Comment by Hixie** [comment]
LGTM.

If I'm reading the code right, the error text is ignored if isDense is set. Is that right? If so, can you add something to the docs mentioning this? Thanks!

**Comment by HansMuller** [comment]
LGTM too.

**Pull request merged**
