### PR TITLE
Categorize flutter tool commands

### LINKED ISSUE #83706: Group flutter tool help's commands
I think it would be helpful to group commands listed in the flutter tool's help. This is the way many command line tools behave.

At the very least, factoring out the flutter installation commands from the rest would be useful.

For example:
```
...
Available commands

Project:
  analyze           Analyze the project's Dart code.
  assemble          Assemble and build Flutter resources.
  build             Build an executable app or install bundle.
  clean             Delete the build/ and .dart_tool/ directories.
  create            Create a new Flutter project.
  drive             Run integration tests for the project on an attached device or emulator.
  format            Format one or more Dart files.
  gen-l10n          Generate localizations for the current project.
  pub               Commands for managing Flutter packages.
  run               Run your Flutter app on an attached device.
  test              Run Flutter unit tests for the current project.

Devices:
 devices           List all connected devices.
 emulators         List, launch and create emulators.

Tools:
  attach            Attach to a running app.
  install           Install a Flutter app on an attached device.
  screenshot        Take a screenshot from a connected device.
  symbolize         Symbolize a stack trace from an AOT-compiled Flutter app.
  logs              Show log output for running Flutter apps.

Flutter installation:
  bash-completion   Output command line shell completion setup scripts.
  channel           List or switch Flutter channels.
  config            Configure Flutter settings.
  doctor            Show information about the installed tooling.
  downgrade         Downgrade Flutter to the last active version for the current channel.
  precache          Populate the Flutter tool's cache of binary artifacts.
  upgrade           Upgrade your copy of Flutter.
...
```

### PR DESCRIPTION
**Pull request by guidezpl**
Now that `args` [supports command categorisation](https://github.com/dart-lang/args/pull/202), assign a category to all  flutter tool commands. The three categories are:
* Flutter SDK
* Project
* Tools & Devices

Screen Shot 2021-10-05 at 15 16 44

Ready when https://pub.dev/packages/args 2.3.0 is available and packages are updated.

Closes flutter/flutter#83706
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
This looks great!

You'll need tests. :-)

cc @christopherfujino for review.

**Comment by guidezpl** [comment]
@christopherfujino Added a test to validate that all top-level visible commands have a valid category

**Review by christopherfujino — COMMENTED** [review]
Sorry, I made these comments a while ago but forgot to submit

**Review by christopherfujino — APPROVED** [review]
LGTM with a few nits

**Review by christopherfujino — CHANGES_REQUESTED** [review]
Oh wait, is it ok to land this before the args update rolls?

**Comment by christopherfujino** [comment]
Also, rebasing upstream will pick fix `Linux analyze`

**Comment by guidezpl** [comment]
Thanks, args was updated by another package update PR

**Review by christopherfujino — APPROVED** [review]
Nice, LGTM

**Pull request merged**
