### PR TITLE
Flutter 1.22.0-12.3.pre framework cherrypicks

### PR DESCRIPTION
**Pull request by christopherfujino**
## Scheduled Cherrypicks

* Update engine hash
  * https://github.com/flutter/engine/commit/5babba6c4d25fa237bbf755ab85c9a0c50b3c6ec
* iOS 14 release Invalid Binary related to Invalid font when adding a Widget Extension
  * https://github.com/flutter/flutter/issues/65991
  * https://github.com/flutter/flutter/commit/576d6b582be8e343079cb8f71733b60fe19f9f30
  * Original author @willlarche, original approver @HansMuller 
* Page-subclasses to take children instead of builder
  * #66695
  * https://github.com/flutter/flutter/commit/062e469f1b9f6721d144c7ab015e938e1295d0bc
  * Original author @goderbauer, original approver @chunhtai 
* iOS VM services takes 4 min to attach when network dialog shows #65402 
  * https://github.com/flutter/flutter/issues/65402
  * https://github.com/flutter/flutter/commit/76ad864727d341b79e40224652444ee67f96b1cc
  * Original author @gaaclarke, @jmagman 
* On some devices, native keyboard cannot be closed with back button #66036
  * https://github.com/flutter/flutter/issues/66036
  * https://github.com/flutter/flutter/commit/0d945a1a5643ab9d1091e9bc56aed4b281f05463
  * Original author @xu-baolin, original approvers @justinmc & @LongCatIsLooong 
* Update pub dependencies to support dart stable 2.10.0
  * https://github.com/flutter/flutter/commit/9cee75ba6187b9bd917e7a67bb4de46f7921875c
  * Original author @jakemac53, original approver @jonahwilliams

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
#65402 LGTM

**Comment by christopherfujino** [comment]
I manually updated the label to `cla: yes` because the committer in question, @xu-baolin has already signed the CLA.

**Comment by christopherfujino** [comment]
@LongCatIsLooong here's the diff of my manual merge conflict resolution:

```diff
index e4c1b60a43,24b8ff8786..0000000000
--- a/packages/flutter/lib/src/widgets/editable_text.dart
+++ b/packages/flutter/lib/src/widgets/editable_text.dart
@@@ -1815,9 -1823,15 +1823,15 @@@ class EditableTextState extends State<E
      if (!_hasInputConnection)
        return;
      final TextEditingValue localValue = _value;
-     if (localValue == _receivedRemoteTextEditingValue)
+     // We should not update back the value notified by the remote(engine) in reverse, this is redundant.
+     // Unless we modify this value for some reason during processing, such as `TextInputFormatter`.
+     if (_updateEditingValueInProgress && localValue == _receivedRemoteTextEditingValue)
        return;
+     // In other cases, as long as the value of the [widget.controller.value] is modified,
+     // `setEditingState` should be called as we do not want to skip sending real changes
+     // to the engine.
+     // Also see https://github.com/flutter/flutter/issues/65059#issuecomment-690254379
 -    _textInputConnection!.setEditingState(localValue);
 +    _textInputConnection.setEditingState(localValue);
    }

    TextEditingValue get _value => widget.controller.value;
@@@ -2137,15 -2151,11 +2151,11 @@@
      _value = value;
      // Use the last formatted value when an identical repeat pass is detected.
      if (isRepeat && textChanged && _lastFormattedValue != null) {
 -      _value = _lastFormattedValue!;
 +      _value = _lastFormattedValue;
      }

-     // Always attempt to send the value. If the value has changed, then it will send,
-     // otherwise, it will short-circuit.
-     _updateRemoteEditingValueIfNeeded();
-
      if (textChanged && widget.onChanged != null)
 -      widget.onChanged!(value.text);
 +      widget.onChanged(value.text);
      _lastFormattedUnmodifiedTextEditingValue = _receivedRemoteTextEditingValue;
    }
```

**Comment by LongCatIsLooong** [comment]
https://github.com/flutter/flutter/pull/66849/commits/c9d70b6dd0bdea0b821ebc803526347f5a13edec LGTM. Were there any other conflicts in `editable_text.dart` other than this line?

```dart
_textInputConnection.setEditingState(localValue);
```

**Review by jonahwilliams — APPROVED** [review]
Version updates LGTM

**Comment by justinmc** [comment]
Another LGTM for https://github.com/flutter/flutter/commit/0d945a1a5643ab9d1091e9bc56aed4b281f05463.  Thanks!

**Review by pcsosinski — APPROVED** [review]
approve for branch

**Pull request merged**
