### PR TITLE
Use default FlutterActivity in non-plugin examples

### PR DESCRIPTION
**Pull request by cbracken**
Brings hello_world and flutter_gallery Android code in line with the
corresponding iOS code.

### CODE REVIEW

**Comment by xster** [comment]
LGTM

**Review by mravn-google — COMMENTED** [review]
We have WIP that replaces built-in "plugins" with real, external ones, published as pub packages. Notably url_launcher and path_provider. Retrofitting this work into flutter_gallery currently relies on an auto-generated PluginsRegistry being called by MainActivity. Other WIP reduces the boilerplate, but does not completely dispense with a custom Activity provided by the app author.

**Comment by jakobr-google** [comment]
I think we should revert this one. It doesn't really make sense.

We just spent some effort to get the examples to match what you get in a new project, and this is a step backwards. On the iOS side, the template is also being changed, but not in a way that removes the integration with the plugins (when they're added).

If there's a discrepancy between the Android/iOS code for these projects, we should bring both closer to the new project template, not away from it.

**Comment by cbracken** [comment]
> I think we should revert this one. It doesn't really make sense.

This is just a revert of the plugin-specific bits that I added in the last couple days. We ran into enough issues trying to get the examples in usable shape on the iOS side that I decided to do the migration piecewise -- get the worskpace files landed, and general shape of the projects to match but without the plugin/pods integration. This CL reverts simply brings the Android side into consistency with the iOS side. The goal is to eventually have the examples all include plugin support by default, once all the issues with the default template (covered in #9763) are addressed.

Until then, it seems inconsistent to include plugin support in these examples on one platform but not the other.

**Comment by jakobr-google** [comment]
@cbracken that was the context I was missing! Thanks!

**Pull request merged**
