### PR TITLE
[flutter_releases] Flutter Stable 2.2.2 Framework Cherrypicks

### PR DESCRIPTION
**Pull request by christopherfujino**
## Scheduled Cherrypicks

- Roll engine cherrypicks https://github.com/flutter/engine/pull/26669
  - https://github.com/flutter/engine/commit/91c9fc8fe011352879e3bb6660966eafc0847233
- #83799 Tool may crash if pub is missing from the artifact cache
  - 302e992ca7d5a16e1e44910ab98a7526f0d2d829
- #83102 Generated l10n file is missing ‘intl’ import with Flutter 2.2.0
  - 485c409184777c9a5eac0d65c362e00d080ea310
- #82874 PopupMenuButton is broken after upgrade to Flutter 2.2.
  - 43d22ae2d38445e96ec865522da2e228ef392c4d

## Known Presubmit Failures

- Customer testing - clones flutter/tests from HEAD
- Mac module test ios - https://github.com/flutter/flutter/issues/83048

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/84364

**Comment by christopherfujino** [comment]
Analysis failures:

```
  error • A value of type 'dynamic' can't be assigned to a variable of type 'FakeProcessManager' • packages/flutter_tools/test/general.shard/dart/pub_get_test.dart:30:47 • invalid_assignment
  error • The method 'empty' isn't defined for the type 'FakeProcessManager' • packages/flutter_tools/test/general.shard/dart/pub_get_test.dart:30:66 • undefined_method
  error • 1 positional argument(s) expected, but 0 found • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1589:31 • not_enough_positional_arguments
  error • The named parameter 'fileSystem' isn't defined • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1590:11 • undefined_named_parameter
  error • The named parameter 'inputPathString' isn't defined • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1591:11 • undefined_named_parameter
  error • The named parameter 'outputPathString' isn't defined • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1592:11 • undefined_named_parameter
  error • The named parameter 'templateArbFileName' isn't defined • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1593:11 • undefined_named_parameter
  error • The named parameter 'outputFileString' isn't defined • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1594:11 • undefined_named_parameter
  error • The named parameter 'classNameString' isn't defined • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1595:11 • undefined_named_parameter
  error • 1 positional argument(s) expected, but 0 found • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1704:31 • not_enough_positional_arguments
  error • The named parameter 'fileSystem' isn't defined • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1705:11 • undefined_named_parameter
  error • The named parameter 'inputPathString' isn't defined • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1706:11 • undefined_named_parameter
  error • The named parameter 'outputPathString' isn't defined • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1707:11 • undefined_named_parameter
  error • The named parameter 'templateArbFileName' isn't defined • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1708:11 • undefined_named_parameter
  error • The named parameter 'outputFileString' isn't defined • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1709:11 • undefined_named_parameter
  error • The named parameter 'classNameString' isn't defined • packages/flutter_tools/test/general.shard/generate_localizations_test.dart:1710:11 • undefined_named_parameter
```

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/84364

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 5.
View them at https://flutter-gold.skia.org/cl/github/84364

**Comment by skia-gold** [comment]
Gold has detected about 6 new digest(s) on patchset 6.
View them at https://flutter-gold.skia.org/cl/github/84364

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 7.
View them at https://flutter-gold.skia.org/cl/github/84364

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
Overriding CLAbot as all commit authors have signed the CLA, the bot just doesn't know how to handle multiple authors.

**Pull request merged**
