### PR TITLE
Handle Flutter SDK paths with spaces in doctor

### PR DESCRIPTION
**Pull request by cbracken**

### CODE REVIEW

**Comment by cbracken** [comment]
This is a partial fix to #6577. While it gets `doctor` running, there are good changes we have similar issues elsewhere in the SDK.

**Review by danrubel — APPROVED** [review]

**Comment by devoncarew** [comment]
DBC: we may want to change the travis bot to check out the repo into a path with a space - that way it would be harder to regress this issue :)

**Comment by cbracken** [comment]
@devoncarew Agreed. Verified that `flutter run` has similar issues. Once we've got all these fixed I'll make the change.

**Pull request merged**
