### PR TITLE
Quadruple Engine roll (DO NOT SQUASH)

### PR DESCRIPTION
**Pull request by goderbauer**
See individual commits for content of roll.

### CODE REVIEW

**Review by liyuqian — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
There's weird behaviour on tiles_scroll_perf__timeline_summary average_frame_rasterizer_time_millis around the time of this commit. Might be worth verifying locally if the regression is real.

**Comment by goderbauer** [comment]
@Hixie Will take a look tomorrow morning CEST.

**Comment by Hixie** [comment]
Looks like the regression is persisting on the dashboard. Not 100% clear when it started.

**Comment by goderbauer** [comment]
From the benchmark it is pretty clear to me that the regression started with this engine commit: https://github.com/flutter/engine/pull/6237. That buildroot roll changed some build flags to better optimize `libflutter.so` for binary size (`-Oz` instead of `-Os` for build, and `-O2` instead of `-O1` for linking). These new flags are pretty successful in reducing binary size: With these new flags `libflutter.so` is ~500KB smaller (uncompressed), which reduces our minimal APK size by ~265KB (compressed).

I am verifying if I can reproduce the regression in average_frame_rasterizer_time_millis locally now.

**Comment by goderbauer** [comment]
I am not seeing this regression locally :(

Given the nice reduction in size, I'd suggest we rebase the tiles_scroll_perf__timeline_summary/average_frame_rasterizer_time_millis benchmark?

**Pull request merged**
