### PR TITLE
Add onSelectionEvent to text widget

### LINKED ISSUE #131065: Allow onSelectionChangedCallback To Be Aware Of Where Data Came From In a SelectableRegion
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

For selecting `Text` widgets, often one may need to not only know what text was selected, but where that text came from. Example, a text widget may be backed by data that is intended to change on selection, such as selecting "highlight" from a context menu. Adding this functionality will allow selection changes to be mapped to the correct data.

This is functionality that exists in `SelectableText` but not with Text widgets inside a `SelectableRegion` or `SelectionArea.` `SelectableRegion` has a callback, but it only provides the text, not where the text came from.

### Proposal

A few possible solutions:

1. It looks like this functionality could be easily added by modifying `SelectedContent` to also contain a list of widget keys, starts, and end indexes. See `SelectableRegion._updateSelectedContentIfNeeded()` and `_SelectableFrament.getSelectedContent()`
    -  This may not be the desired solution since not all `Selectable`s could be Text
3. A `onSelectionCallback` could be added to the Text widget and called in the `_SelectableFrament.dispatchSelectionEvent()` or `_SelectableFrament.getSelectedContent()`
    - Having this handler would allow the use of a closure with the widget id (or some other identifier) that is associated with the backing data in order to update the backing data as such.
 

I already implemented 2 and it works as expected. Happy to create a PR if this is the desired solution.

### PR DESCRIPTION
**Pull request by mcmah309**
Adds `onSelectionEvent` to the `Text` widget.

Resolves: https://github.com/flutter/flutter/issues/131065

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by justinmc** [comment]
@chunhtai I'm interested in what you think about this approach before I jump in here...

**Review by chunhtai — COMMENTED** [review]
I think having a onSelection callback is fine, but the call back should probably only be called when the selection did change, not when it receive a selection event. Based on the github issue, it seems like the use case is to change text style of selected text, would it make sense to include a text style for selected text in DefaultSelectionStyle?

**Comment by mcmah309** [comment]
@chunhtai, this line here makes sure that `onSelectionEvent` is never called unless there is an actual change to the selection https://github.com/flutter/flutter/pull/131097/files#diff-bc57c6a6c8e97b4cade139f2b1030fffc8707ee8e9713fcab3684e2a213542deR1435 . I improved the test to make this clear/guard against any future changes. 

I believe passing the event to the callback could be useful, for example, I can see a situation where when a `SelectWordSelectionEvent` is received, an application may automatically look up the definition and present it to the user.

I can't think of an immediate benefit to including `DefaultSelectionStyle`, since that could be included in the closure if it was needed. But maybe there is a situation I am not thinking of.

**Comment by chunhtai** [comment]
I don't think exposing the SelectionEvent may make sense. This is mainly used for updating the internal state in Text widget.

I would be more prefer more toward EditableText.onSelectionChange kind of api
```
typedef SelectionChangedCallback = void Function(TextSelection selection, SelectionChangedCause? cause);
```

**Comment by mcmah309** [comment]
Is there a concern with exposing this? I looked at all call chain usages and did not see one, besides the internal state is immutable for all implementations. In regards to `SelectionCause`, from my understanding, `SelectionEvent` and `SelectionCause` are similar, but separate in meaning and functionality. SelectionEvent is what type of selection is to be done (word, move edge, etc,.), while SelecionCause is what caused the selection (tap, long press, etc.). Examining uses of `SelectionEvent`, I see that it is pretty much solely related to the `SelectableRegion` (with the exception of `selectAll` action/handler sending a `SelectAllSelectionEvent` when receiving any `SelectionChangedCause`), while `SelectionCause` is pretty much soley related to `EditableText`. To further integrate the `SelectionCause` system seems like a pretty major refactor. 

If including `SelectionEvent` in the signature is an issue, as this does not effect the original use-case, I will happily remove it, and we can table that as a possible future improvement.

**Comment by chunhtai** [comment]
`SelectionEvent` is used by the SelectionArea to communicate the user-gestures to each `Selectable`s. We can't predict how Selectable will react to these SelectionEvents. If we exposed `SelectionEvent` in the callback, developer will start writing code that asserts how Selectable react to each `SelectionEvent`.

The SelectionChangedCause is used when the selection has been updated, which is a better suited for this use case.

I am going to close this pr as not planned

**Comment by mcmah309** [comment]
@chunhtai So you are saying, the you don't want implementers to make any assumptions on what to do when the `SelectionEvent` is received. Like for example we don't want to enforce the contract that a `SelectionClearEvent` actually clears the selection. We should leave that to the selectable to decide. Okay fair. Nevertheless, does you closing this mean you've now changed your mind about exposing even the `TextSelection` on change in a callback (https://github.com/flutter/flutter/pull/131097#pullrequestreview-1550497325). Or do you want me to create a separate PR for that? If not, how do you propose the solution to https://github.com/flutter/flutter/issues/131065 going forward?

**Comment by chunhtai** [comment]
If you have a good way to expose the API to similar to what TextSelection in EditableText does, yes, please create a new pr.

**Comment by Dall127** [comment]
@chunhtai is there any plans to be able to get TextSelection from SelectionArea/Region?  I'm currently working on a project that requires me to be able to paint a page worth of text, with each segment of text being  positioned based on absolute positions. However, this means that I'm not able to use SelectableText and get the offset (for things like highlighting based off of the text's offsets). I can create a new issue if need be

**Comment by chunhtai** [comment]
@Dall127 does SelectionArea.onSelectionChanged work for your case?

**Comment by Dall127** [comment]
@chunhtai, unfortunately  I can't use the current implementation because it doesn't provide the character offsets directly. I specifically need a TextSelection that starts from an offset of 0 for each SelectionArea. I've looked at the source code and it seems like this data is available, but it's not exposed in the relevant callback.

For my use case, it's crucial to have distinct objects based on character offsets. For instance, the word "can" appearing at offsets 23-26 should be treated as a different object from another "can" at offsets 80-83, because they might have different contextual meanings for my use case.

**Comment by chunhtai** [comment]
@Dall127 can you file a new issue ? This seems like something that would require a new api

**Comment by Dall127** [comment]
@chunhtai More than happy to tomorrow. Would you like me tag you in it when I create it?

**Pull request closed without merging**
