### PR TITLE
Revert "feat: migrate base/dds.dart to null-safety"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#88015

See https://github.com/dart-lang/sdk/issues/46934

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
Can't get the full package to null safety fast enough.  Thanks for tracking it down, @knopp!

**Comment by knopp** [comment]
Thanks! There are multiple call sites where `startDartDevelopmentService` is called with nullable `ddsPort` argument without proper fallback (`?? 0`).

**Pull request merged**
