### PR TITLE
fix cupertino date picker column width calculation

### LINKED ISSUE #110319: CupertinoDatePicker in Arabic showing months in wrong way
CupertinoDatePicker show us months in arabic wrong 

CupertinoDatePicker shows months in arabic not completed for example january showing it janua 
but in arabic. example in arabic "اغسطس"  showing it to "غسط"

snippet of the code:

`showCupertinoModalPopup(
        context: ctx,
        builder: (_) => Container(
          height: 190,
          color: const Color.fromARGB(255, 255, 255, 255),
          child: Column(
            children: [
              SizedBox(
                height: 180,
                child: CupertinoDatePicker(
                  mode: CupertinoDatePickerMode.date,
                  initialDateTime: DateTime.now(),
                    onDateTimeChanged: (value) {
                      debugPrint('value ==> $value');
                      setState(() {
                        _expiredDate = value.toLocal();
                      });
                    },

                ),
              ),
            ],
          ),
        ));`

### PR DESCRIPTION
**Pull request by HosamHasanRamadan**
Fixes: #110319

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by HosamHasanRamadan** [comment]
Hi @Piinks 
I was trying to add tests to this change, but I didn't know where to start.
- `_getColumnWidth` is private 
- the function depends on `flutter_localizations` which is not part of flutter package 

Can you guide me through ?
Or if there is a similar test that I can read because I didn't find any test in `date_picker_test.dart` to old code.

**Comment by MitchellGoodwin** [comment]
Another PR fixing a similar issue with a different implementation was filed here: #151128

**Comment by MitchellGoodwin** [comment]
> Or if there is a similar test that I can read because I didn't find any test in date_picker_test.dart to old code.

This is a tricky thing to test, the person in the other PR is having the same problem. It looks like the test needs to both override the localizations with one that triggers the issue and use a different font then what the tests use by default. The font used by the tests have a standard spacing that may not trigger this issue. See [this comment](https://github.com/flutter/flutter/issues/138305#issuecomment-2207164389) and the one above it.

**Comment by HosamHasanRamadan** [comment]
Thanks @MitchellGoodwin 
Using `Localizations.override` fixes the localization problem and managed to render Arabic months.
Now I have problem with the font , it seems like monospaced font is used during test. 
The problem isn't reproducible in this case.
How can I override the font is this situation?

**Comment by MitchellGoodwin** [comment]
The other PR has the same issue, and looks like they were able to load Roboto. [Link to comment on the section](https://github.com/flutter/flutter/pull/151128/files#r1669227851). I don't know enough about how the fonts load in the tests to know if it's a safe test though.

**Comment by HosamHasanRamadan** [comment]
@MitchellGoodwin 
I managed to add test without exposing any private members in `CupertinoDatePicker` file.
I used `Local('pr')` for locale and months values , I didn't manage to test it with Arabic values.

**Comment by MitchellGoodwin** [comment]
Going to close this in favor of #151128. Feel free to comment on that PR. If that one is closed for any reason, also feel free to reopen this one.

**Pull request closed without merging**
