### PR TITLE
[asset] Include assets in input files

### PR DESCRIPTION
**Pull request by jayzhuang**
So they get propagated to depfiles as well.

### CODE REVIEW

**Comment by jayzhuang** [comment]
@chaselatta @jonahwilliams

**Comment by jonahwilliams** [comment]
I think the failure is unrelated I triggered a re-run.

**Review by jonahwilliams — APPROVED** [review]
LGTM

You'll need to pull in the latest master to get CI running unfortunately

**Comment by jayzhuang** [comment]
Thanks! Rebased onto the latest master.

**Pull request merged**
