### PR TITLE
Wrap lines at 80 characters

### PR DESCRIPTION
**Pull request by mit-mit**
Wrap lines consistently with other files

### CODE REVIEW

**Comment by gspencergoog** [comment]
LGTM, but will this affect the license compression that we use in the engine? It relies on licenses having common segments of text to make the binary size smaller. Check with @goderbauer.

32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Review by gspencergoog — APPROVED** [review]

**Comment by mit-mit** [comment]
Sent a PR to synchronize flutter/engine

**Comment by goderbauer** [comment]
Can you build a flutter apk and check that this change doesn't increase the size of the combined LICENSE file inside?

**Comment by mit-mit** [comment]
Change in flutter/engine landed. I don't see any size difference when `flutter build apk`'ing the gallery

**Pull request merged**
