### PR TITLE
Pin the goldens repo to a specific commit in the android_views test.

### PR DESCRIPTION
**Pull request by amirh**

### CODE REVIEW

**Comment by xster** [comment]
What was the issue we were trying to solve? Was it that tests were slow because await goldensClient.prepare(); should have checked some cache? Otherwise, the next time some maintainer changes a golden, they'd have to change goldens.version and this pubspec too?

Either way LGTM since I don't know much about this test. You can decide.

**Comment by amirh** [comment]
It was actually your idea 😄 (#20959).

It's just simpler this way, e.g in https://github.com/flutter/flutter/issues/23900#issuecomment-435697769 it created confusion when I pointed someone to run the android_views app as a diagnostic step.

**Comment by amirh** [comment]
As for updating the pinned commit, what this test is using off the goldens repository is a recorded touch sequence. It is the only things of goldens used by this test and the only test that uses the touch sequence recording.
So I'm kind of ok with the commit pinned here to get out of sync with the commit in goldens.version as these are used for different parts of the repository.

**Comment by xster** [comment]
Ah I see. The pubspec tries to get that directory directly without being wrapped by anything from flutter_tools that makes sure to clone it first. Makes sense. 

LGTM

**Pull request merged**
