### PR TITLE
reset date in date_picker with one click button

### PR DESCRIPTION
**Pull request by viralkachhadiya**
## Description

=:Reset Date:=
    
         I submit this PR for Reset Date using only one reset button click event. Before this PR , A DatePicker was not provide the reset date functionality with one action. So that, It was difficult to perform reset. When you change the date from initial date to your desired date and if you want to go back to the initial date, this reset action button will help you to do so. 

For example:
        
        If initial date is 10/01/2021 and you want to select and change with new date like 15/03/2021 then when you want to go back to the initial date, you do not need to move back for 2 month to reach the initial date. just use reset button and that will move back to initial date.
  
            
## Related Issues

*Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR. There should be at least one issue listed here.*

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behavior with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [x] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [x] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [x] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [x] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by viralkachhadiya** [comment]
please check my code

**Comment by justinmc** [comment]
Some quick things to fix here.  It seems you have an autoformatting tool running.  Could you disable it and undo its changes in this PR?  Flutter uses a different code style and all of these changes make your PR hard to review.

Also, you will need to add a test for this.  Add it to [material/date_picker_test.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/date_picker_test.dart).

Lastly, could you update the fields in the PR description above?

**Comment by viralkachhadiya** [comment]
> Some quick things to fix here. It seems you have an autoformatting tool running. Could you disable it and undo its changes in this PR? Flutter uses a different code style and all of these changes make your PR hard to review.
> 
> Also, you will need to add a test for this. Add it to [material/date_picker_test.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/date_picker_test.dart).
> 
> Lastly, could you update the fields in the PR description above?

Thank you. I will change it as soon as possible.

**Comment by darrenaustin** [comment]
@viralkachhadiya thanks for the PR. We definitely need the description field above filled out as all we have to go on is the title and code changes themselves. As @justinmc pointed out we use a specific code style for the Flutter framework that doesn't play well with autoformatters (see https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#formatting), so please revert any style only changes so we can see what you are actually changing.

Currently the Material Design for the date pickers does not include support for a "Today" or "Reset" button. We would need to get a design from them before adding such to our implementation. However, if you have need for this right now, you could use the `CalendarDatePicker` and build your own with a button that resets the date.

I look forward to seeing your update to this so we can fully review it. Thanks.

**Comment by viralkachhadiya** [comment]
> @viralkachhadiya thanks for the PR. We definitely need the description field above filled out as all we have to go on is the title and code changes themselves. As @justinmc pointed out we use a specific code style for the Flutter framework that doesn't play well with autoformatters (see https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#formatting), so please revert any style only changes so we can see what you are actually changing.
> 
> Currently the Material Design for the date pickers does not include support for a "Today" or "Reset" button. We would need to get a design from them before adding such to our implementation. However, if you have need for this right now, you could use the `CalendarDatePicker` and build your own with a button that resets the date.
> 
> I look forward to seeing your update to this so we can fully review it. Thanks.

Okay, Thank you for replaying me. I will change some code style.

**Comment by viralkachhadiya** [comment]
@justinmc 
@darrenaustin 

please check my last comment and please give review on it.

**Comment by viralkachhadiya** [comment]
https://github.com/flutter/flutter/pull/73101/commits/f70a7f72eb01ccf1f8c79cb55c3db91e38a3f2d1

**Pull request closed without merging**
