### PR TITLE
Bump Dart SDK to 1.22.0-dev.10.5.

### PR DESCRIPTION
**Pull request by pq**
Latest dev build (~RC1), with all cherry-picks fixing known issues merged.

@tvolkert @goderbauer @Hixie @abarth

### CODE REVIEW

**Comment by goderbauer** [comment]
LGTM

**Comment by pq** [comment]
@tvolkert : can you think of any reason *not* to land this?

**Comment by tvolkert** [comment]
Nope - LGTM.  I was just waiting to see Travis go green :-)

**Comment by whesse** [comment]
-dev.10.6 is now released, with fixes.

**Comment by pq** [comment]
> -dev.10.6 is now released, with fixes.

Yes, thanks!

https://github.com/flutter/flutter/pull/7953

**Pull request merged**
