### PR TITLE
Add compile-expression service.

### PR DESCRIPTION
**Pull request by aam**
This vm service is used during debugging to compile user-provided expressions into kernel format.

### CODE REVIEW

**Review by rmacnak-google — APPROVED** [review]
lgtm

**Comment by Hixie** [comment]
tests?

**Comment by Hixie** [comment]
What is your plan with this PR? (No particular rush, I'm just cleaning out the review queue.)

**Comment by aam** [comment]
This is waiting for the dart sdk changes to land first, then this can be landed.

**Comment by Hixie** [comment]
@aam Is there a bug or PR I can follow to see when the Dart SDK changes will land?

**Comment by aam** [comment]
Large chunk of dart sdk changes landed here: https://dart-review.googlesource.com/c/sdk/+/54407

I'm working on the rest of it, I don't have PR for it yet.

**Comment by aam** [comment]
Here is tracking bug for this: https://github.com/dart-lang/sdk/issues/31981

**Comment by aam** [comment]
Using cirrus successful run results, the change has been sitting in appveyor's queue for 40 minutes already, hasn't started yet.

**Pull request merged**
