### PR TITLE
[devicelab] turn down android X migration gradle tests

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

These androidx migration tests require downloading firebase, which is a large library with a number of dependencies - this causes frequent enough flakes.

AndroidX migration is ~2 years in the past, and while it would be nice to confirm this still works, ideally that would be done in a reduced manner.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
It this the correct way to do it? or do I need to make recipe changes too?

**Comment by keyonghan** [comment]
> It this the correct way to do it? or do I need to make recipe changes too?

For try jobs, these changes are enough. But for prod builders, these change will only avoid status showing up on flutter-dashboard, but these builders will still run and show up in the milo dashboard. So for the prod builders, flutter/infra config changes are needed to stop running them.

@godofredoc made quite some effort to make all these hostonly devicelab tests running, will leave approval to him.

**Review by godofredoc — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
FYI @blasten , these tests have been failing on and off for the past few weeks because the LUCI bots are having problems downloading the firebase dependencies. If we can find a way to run this test with a reduced or local only dependency then it could be re-added

**Pull request merged**
