### PR TITLE
Use site-shared as canonical source for Flutter logo

### PR DESCRIPTION
**Pull request by chalin**
Also, move badges out of the page title/heading.

cc @sfshaza2 @kwalrath @filiph

### CODE REVIEW

**Comment by chalin** [comment]
Btw, I switched to using the standard 64x64 logo (we used to display the image with a smaller width). This is just a README, and not flutter.io, so I figured that we wouldn't be worrying too much about logo size tweaking. But if someone feels strongly about it, I can replace the image markdown with HTML so that we can adjust the size.

**Review by gspencergoog — APPROVED** [review]
Thanks for simplifying that.  I didn't know about using named Markdown link references like that.

**Comment by chalin** [comment]
@gspencergoog - given that you've approved, can I go ahead and merge?

**Comment by gspencergoog** [comment]
Yes, you can merge as soon as the pre-commit tests pass, and as long as the tree is green then.
(Yeah, I know it's only documentation, but we still don't land it without following the protocol).

**Pull request merged**
