### PR TITLE
Default SnackBar duration is below Material Spec's minimum #19003

### PR DESCRIPTION
**Pull request by drkhannah**
PR for this issue https://github.com/flutter/flutter/issues/19003

Changed Material Snackbar default duration to 4 seconds as per Material Design Spec.

### CODE REVIEW

**Comment by drkhannah** [comment]
What command can I run locally to test if the flutter-build pipeline stage is broken or not?

**Comment by Hixie** [comment]
@drkhannah `flutter-build` just tells you if the tree is open or closed, if it's red that means something is broken on the tree. It'll go green on its own if the tree is fixed.

**Comment by Hixie** [comment]
I'm going to close this PR since it looks like Jeremy fixed it in https://github.com/flutter/flutter/pull/19015 already. Thanks for the contribution though! Sorry it took so long to get to it!

**Comment by drkhannah** [comment]
totally cool, thanks for letting me know

**Pull request closed without merging**
