### PR TITLE
Enable no_leading_underscores_for_local_identifiers

### PR DESCRIPTION
**Pull request by goderbauer**
Evaluating what this lint (which may be added to package:lints, https://github.com/dart-lang/core/issues/758) means for the flutter code base.

Before we can submit and enable this we need to wait for the fix of https://github.com/dart-lang/sdk/issues/58603 to roll into our repository. (Analysis will fail before then.)

/cc @pq

### CODE REVIEW

**Comment by pq** [comment]
The fix for field formal params is in the in-flight 1.18.0 (https://github.com/dart-lang/linter/pull/3140).

**Comment by goderbauer** [comment]
@christopherfujino for the tool
@gspencergoog for the API doc samples

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Wow.  I wonder why there were so many of these in non-tests?  I can see doing it accidentally in a test, since it feels like a class scope, but it's really an inner function. But it seems weird to do that with regular locals.

Thanks for turning that on!

**Review by christopherfujino — APPROVED** [review]
tools change LGTM

**Pull request merged**
