### PR TITLE
[Reland] Migration for the `sendTiming` events for `package:unified_analytics`

### PR DESCRIPTION
**Pull request by eliasyishak**
Relanding based on this comment:
- https://github.com/flutter/flutter/pull/139278#issuecomment-1832951108

Related to tracker issue:
- https://github.com/flutter/flutter/issues/128251

image

The image above shows all of the instances where we have `sendTiming`. All of the call sites have been updated to use the new `Event.timing` event from `package:unified_analytics`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by eliasyishak** [comment]
@CaseyHillers, i'll leave this here until your changes have been made, thanks for following up :)

**Comment by CaseyHillers** [comment]
> @CaseyHillers not 100% on the frequency but i think it's about 2 times a week on an automated job. But i can create the update in Gerrit manually to update the dart-sdk DEPS file, will that help?

I'm not sure. It might be best to ask in one of the Dart channels what their dependency update process is.

**Comment by christopherfujino** [comment]
@eliasyishak I think we should wait to merge this PR until we can get Google testing passing. I think we should own ensuring that FRoB runs with the right version of package:unified_analytics, and not the release team.

**Comment by eliasyishak** [comment]
@christopherfujino agreed, i have a CL in Gerrit to update the DEPS file right now to update the package in google3

https://dart-review.googlesource.com/c/sdk/+/339380

**Comment by eliasyishak** [comment]
@CaseyHillers i think this PR is ready for a review, looks like google3 has been updated to have the latest version of package:unified_analytics

**Review by CaseyHillers — APPROVED** [review]

**Pull request merged**
