### PR TITLE
Strip app.so in release mode.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @abarth @tvolkert

**Comment by chinmaygarde** [comment]
screen shot 2016-05-26 at 11 48 20 am

**Comment by tvolkert** [comment]
lgtm

**Comment by abarth** [comment]
LGTM

**Comment by chinmaygarde** [comment]
I closed this because I was seeing errors as Xcode was trying to be smart with the so. Will fix later.

**Comment by abarth** [comment]
Ok...

**Pull request closed without merging**
