### PR TITLE
Fix Dismissible confirmDismiss errors

### LINKED ISSUE #54990: Dismissible Widget confirm dismiss error if animation starts after the child has been scrolled
## Steps to Reproduce

I have a list of widgets inside a CustomScroll, each widget is wrapped in a Dismissible widget and when someone dismiss the widget the confirmDismiss fires and a snackbar with an undo button is showed (like Keep Note app), Now if you scroll away from the widget and then click on undo an error is shown that the ticker animation has been disposed and is null, which makes sense the widget isn't there anymore, and if you don't push the undo button and let the snackbar dissapear it means the widget should start to resize (confirmDismiss returns true) and an error telling you the widget is not mounted. Shouldn't the dismissed widget check if it's mounted or not before starting a resize or _modecontroller.reverse animation? In that way it could fire the onDismissed callback without starting any animation. 

The problem is there is no proper way to fire the onDismiss (so I can delete the object from the list) without starting the animation.

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'dart:async';

void main() => runApp(
    MaterialApp(
        home: Scaffold(
          body: CustomScrollView(
            cacheExtent: 50,
            slivers: <Widget>[
              Drag()
            ],
          ),
        )
    )
);

class Drag extends StatefulWidget {
  @override
  _DragState createState() => _DragState();
}

class _DragState extends State<Drag>{
  List<String> list = List<String>.from(
      'Lorem ipsum dolor sit '
          'amet, consectetur adipiscing elit, s'
          'ed do eiusmod tempor'.split('')
  );

  @override
  Widget build(BuildContext context) {
    return SliverList(
        delegate: SliverChildBuilderDelegate(
              (BuildContext context, int index){
            return Dismissible(
              key: Key('$index${list[index]}'),
              background: Container(color: Colors.red,),
              confirmDismiss: (_) {
                Completer<bool> completer = Completer();
                final scaffold = Scaffold.of(context);
                scaffold.showSnackBar(
                    SnackBar(content: Text('Task dismissed'),
                      behavior: SnackBarBehavior.floating,
                      onVisible: () => Future.delayed(
                          const Duration(milliseconds: 4000), () {
                        if(completer.isCompleted) return;
                        completer.complete(true);
                      }
                      ),
                      action: SnackBarAction(
                          label: 'undo',
                          onPressed: () => completer.complete(false)
                      ),
                    )
                );
                return completer.future;
              },
              onDismissed: (_) => setState(() => list.removeAt(index)),
              child: Container(
                height: 100,
                width: double.infinity,
                color: index % 2 == 0 ? Colors.blue : Colors.green,
                child: Center(
                  child: Text(list[index], style: TextStyle(fontSize: 24),),
                ),
              ),
            );
          },
          childCount: list.isEmpty ? 0 : list.length,
        )
    );
  }
}

```
<details>
  <summary>Logs</summary>

```
 [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 484 pos 7: '_ticker != null': AnimationController.reverse() called
after AnimationController.dispose()
[   +2 ms] E/flutter ( 6276): AnimationController methods should not be used after calling dispose.
[   +1 ms] E/flutter ( 6276): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
[   +1 ms] E/flutter ( 6276): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
[        ] E/flutter ( 6276): #2      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:484:7)
[        ] E/flutter ( 6276): #3      _DismissibleState._handleDismissStatusChanged (package:flutter/src/widgets/dismissible.dart:449:25)
[        ] E/flutter ( 6276): <asynchronous suspension>
[        ] E/flutter ( 6276): #4      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:193:19)
[        ] E/flutter ( 6276): #5      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:773:7)
[        ] E/flutter ( 6276): #6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:789:5)
[        ] E/flutter ( 6276): #7      Ticker._tick (package:flutter/src/scheduler/ticker.dart:237:5)
[        ] E/flutter ( 6276): #8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
[        ] E/flutter ( 6276): #9      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1017:11)
[        ] E/flutter ( 6276): #10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
[        ] E/flutter ( 6276): #11     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1015:17)
[        ] E/flutter ( 6276): #12     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:949:5)
[        ] E/flutter ( 6276): #13     _rootRunUnary (dart:async/zone.dart:1138:13)
[        ] E/flutter ( 6276): #14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
[        ] E/flutter ( 6276): #15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
[        ] E/flutter ( 6276): #16     _invoke1 (dart:ui/hooks.dart:273:10)
[        ] E/flutter ( 6276): #17     _beginFrame (dart:ui/hooks.dart:200:3)
[        ] E/flutter ( 6276): 

```

```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [VersiÃ³n 10.0.18363.720], locale es-MX)
    • Flutter version 1.12.13+hotfix.9 at E:\Programs\flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\dartz\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\dartz\AppData\Local\Android\Sdk
    • Java binary at: E:\Programs\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at E:\Programs\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```

</details>

### LINKED ISSUE #87556: Dismissible when reset the widget is still there
## Reproduction code
In order to reproduce the bug you have to pull the red box all the way to the bottom/top and hold it there for a while. Then release your finger and the box wont reset its position. However, the hitbox is already reset. It works fine when u dont drag all the way to the end.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Dismissible(
            direction: DismissDirection.vertical,
            key: UniqueKey(),
            confirmDismiss: (_) => Future.sync(() => false),
            child: Container(
              color: Colors.red,
              height: 200,
              width: 200,
            ),
          ),
        ),
      ),
    );
  }
}

```
https://user-images.githubusercontent.com/68549184/127986040-8e377398-8792-43b4-8d1f-cc743d081d39.mp4

**Expected results:** When you swipe either up or down and hold it, it should reset to its original position.

**Actual results:** The widget gets stuck, however the hit box itself is back to its original position.

<details>
  <summary>Logs</summary>

Flutter doctor

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.18363.1679], locale en-MY)
    • Flutter version 2.2.3 at C:\scr\flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Samuel\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\Samuel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • SM G885F (mobile) • 192.168.1.104:5555 • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 92.0.902.62



```

</details>

### LINKED ISSUE #88671: Dismissible confirmDismiss should not be called with threshold >= 1.0
## Steps to Reproduce

Specify threshold 1.0 or more and a `confirmDismiss` which returns true. Drag the dismissible all the way to the end and then release.

**Expected results:** logically, by its name, confirmDismiss should not even be called, since dismissal should not be possible with such big threshold

**Actual results:** theshold is ignored and confirmDismiss is called and can take over it

<details>
  <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  Home({Key? key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  bool navigated = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Dismissible(
          key: Key('test_dismissible'),
          resizeDuration: const Duration(milliseconds: 300),
          background: Container(
            color: Colors.red,
          ),
          dismissThresholds: {
            DismissDirection.startToEnd: 1.0,
            DismissDirection.endToStart: 1.0,
          },
          confirmDismiss: (direction) async {
            return true;
          },
          child: ListTile(
            title: Text('Dismiss me'),
            tileColor: Colors.green,
          ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.5.0-7.0.pre.83, on Microsoft Windows [Version 10.0.19041.1110], locale ru-RU)
    • Flutter version 2.5.0-7.0.pre.83 at C:\dev\src\flutter
    • Upstream repository git@github.com:nt4f04und/flutter.git
    • FLUTTER_GIT_URL = git@github.com:nt4f04und/flutter.git
    • Framework revision 06be7e5392 (4 hours ago), 2021-08-15 14:37:02 -0400
    • Engine revision 1af0a20793
    • Dart version 2.15.0 (build 2.15.0-15.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.59.0)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (4 available)
    • Redmi Note 5 (mobile)   • 40c9f14       • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.1110]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 92.0.902.67

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by nt4f04uNd**
Fixes https://github.com/flutter/flutter/issues/54990
Fixes https://github.com/flutter/flutter/issues/87556
Fixes https://github.com/flutter/flutter/issues/88671

Some comments:

1. https://github.com/flutter/flutter/issues/54990 was caused by that some state callbacks ran on disposed state because they were waiting for `confirmDismiss` to end
2. https://github.com/flutter/flutter/issues/87556 had somewhat a similar reason, after the `confirmDismiss` resolved, the `false` result was ignored on this line. Instead, `_moveController!.reverse()` should be called

https://github.com/flutter/flutter/blob/2526cb07cb1f689f857af841570e21f980f44564/packages/flutter/lib/src/widgets/dismissible.dart#L462-L465

3. To prevent unexpected behaviors, disallowed widget dragging when `confirmDismiss` future is pending

4. In the tests the `dismissElement` made the Dismissible to not fully move, because of small offset. To make tests for this PR I fixed it and discovered a few things to tune in the test coverage:
   * `DismissDirection.none does not trigger dismiss` test - needed to make list unscrollable, otherwise the item would be destroyed, because it went out of `cacheExtent`
   * `DismissDirection.none does not prevent scrolling` test - needed just to change a value

5. https://github.com/flutter/flutter/issues/88671 was discovered from the `dismissElement` change, because [the test](https://github.com/flutter/flutter/blob/2ad8e7093f46f44f7bda4ae0c41043bc0688d927/packages/flutter/test/widgets/dismissible_test.dart#L532) that was checking the threshold now failed, so this issue doesn't need any new test

6. Added a new test `Dismissible with null resizeDuration calls onDismissed immediately` - just to increase the test coverage

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by dkwingsmt — APPROVED** [review]
LGTM, very impressive!

**Comment by dkwingsmt** [comment]
I don't know why "Build Parsing Results" keeps pending. Can you try to **rebase** your PR onto master?

**Comment by dkwingsmt** [comment]
There're conflicts with master. Maybe you didn't rebase on the latest master?

**Comment by nt4f04uNd** [comment]
Looks like another patch just landed after I rebased

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Pull request merged**
