### PR TITLE
Prevent entire navigation stack from rebuilding when MediaQuery dependency changes

### PR DESCRIPTION
**Pull request by luckysmg**
Fix: 
https://github.com/flutter/flutter/issues/96044

The `MediaQuery` is a object that its data will change very frequently, especailly when keyboard animating. So I think we can avoid the invisible page from being rebuilt.

### Before

**All pages will rebuild.** 

https://user-images.githubusercontent.com/49340347/204210965-6179faf9-af85-4c1e-b106-a05c74582447.mp4

### After:
**Only visible pages will rebuild.** 

https://user-images.githubusercontent.com/49340347/204211137-77c06a0d-bf36-4690-9bbe-68b9371d38ce.mp4

### Update when page becomes visible

https://user-images.githubusercontent.com/49340347/208226724-9fb4dd17-c9d0-4a31-91fa-7f6be4a87b2d.mp4

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by goderbauer** [comment]
I am not convinced that special casing MediaQuery this way is worth the effort. Widget rebuilds that this is triggering are usually very fast. Do you have a benchmark indicating that there is a performance problem? With https://github.com/flutter/flutter/issues/102060 in place I also suspect that this already cuts down the rebuilds by a lot because widgets can listen to mediaquery changes more targeted.

**Comment by b3nni97** [comment]
I have had the problem of the entire navigation stack being rebuilt for some time now. Of course #102060 helps to avoid some rebuilds, but there are some use-cases to avoid the rebuilds between the pages as well.

For example, Instagram: There is a TabBar with 5 different Pages. With Flutter, if I visit all pages once and then a MediaQuery rebuild is generated, then potentially thousands of widgets will be rebuilt. Especially with more complex apps with a lot of different content, this quickly leads to a performance bottleneck.

Currently I use custom widgets that avoid rebuilding when TickerMode is disabled and this has solved many janks in my app.

**Comment by luckysmg** [comment]
I think this change will not impact the multi tab scenario. Use `CupertinoTabScaffold` as example
I see it use a `Stack` to control the page show or hide instead of a `Navigator` or `Overlay` system. 
See code:
https://github.com/flutter/flutter/blob/dbc9306380d8a72273b478b8fcc934a6014f946d/packages/flutter/lib/src/cupertino/tab_scaffold.dart#L493

**So if one page in tab opens a textField, the other page will still rebuild. I think that's a different problem.**

**The PR https://github.com/flutter/flutter/pull/114459 solve problem is:**
If just use `MediaQuery.viewInsetsOf(context);`, don't rebuild unless `viewInsets` changes. But if I use `MediaQuery.viewInsetsOf(context)` in every pages, it will still be rebuild when textField opens.

**This PR solve is that:**
No matter what, if current page (Or overlayEntry) is not visible, the widget in it should not rebuild until it becomes visible

**Comment by luckysmg** [comment]
Here is demo code to debug.

<details>

<summary>Demo code</summary>

```dart
void main() async {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const TextFieldPage(),
    );
  }
}


class TextFieldPage extends StatefulWidget {
  final int? id;

  const TextFieldPage({Key? key, this.id = 0}) : super(key: key);

  @override
  State<TextFieldPage> createState() => _TextFieldPageState();
}

class _TextFieldPageState extends State<TextFieldPage> {
  @override
  Widget build(BuildContext context) {
    print('${widget.id}page rebuild!');
    MediaQuery.viewInsetsOf(context);
    return GestureDetector(
      onTap: () {
        FocusScope.of(context).unfocus();
      },
      child: Scaffold(
        body: Stack(
          fit: StackFit.expand,
          children: <Widget>[
            Column(
              mainAxisAlignment: MainAxisAlignment.end,
              children: [
                const Spacer(),
                Text('Page ${widget.id}', style: const TextStyle(fontSize: 26)),
                CupertinoButton.filled(
                    child: const Text('push'),
                    onPressed: () {
                      Navigator.of(context).push(CupertinoPageRoute(builder: (ctx) {
                        return TextFieldPage(id: widget.id! + 1);
                      }));
                    }),
                const SizedBox(
                  height: 20,
                ),
                const Spacer(),
              ],
            ),
            Positioned(
              left: 0,
              right: 0,
              bottom: 0,
              height: 100,
              child: Padding(
                padding: const EdgeInsets.only(left: 26, right: 26),
                child: CupertinoTextField(
              decoration:
                  BoxDecoration(color: Colors.red, borderRadius: BorderRadius.circular(8)),
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}

```
</details>

**Comment by b3nni97** [comment]
Oh ok, maybe it's better to create a generic widget that disables the rebuild functionality? Something like TickerMode for rebuilds. If "RebuildMode" is turned off then all widgets in the subtree will not be rebuilt anymore.

**Comment by luckysmg** [comment]
@b3nni97 
Emm I think maybe the `RebuildMode` is a very invasive and aggressive..... 
That will break most current framework theory... Maybe not very feasible. You can have a try for that O(∩_∩)O

**Comment by chunhtai** [comment]
Either we go through the RebuildMode or not at all, It seems like MediaQuery is just one subset of the rebuild issue. I can also see thing may become unexpected when we do that though, if the build or didchangeDepedencies has some side effect, this will be a breaking change.

**Comment by chunhtai** [comment]
If irrc, the non visible Overlay will not be layout or paint, I am not sure how much of this change will help with performance

**Comment by luckysmg** [comment]
After the input from @goderbauer and @chunhtai, maybe this change is not very appropriate. It will have some side effect or other things unexpected, which is a little bit aggressive.

After some investigation, I think we have some options to optimize the rebuild from `MediaQuery` changes when writing code:

- **If we did want to avoid rebuilding when `MediaQuery` changes.** We can use `MediaQueryData.fromWindow(window)` to get value, and using `didChangeMetrics` to update value and call `setState()` **when it is current page**, which will not break current theory and will works fine too.

- **Set `Scaffold`'s `resizeToAvoidBottomInset` to `false` when you don't need adjust viewInsets**, because when `resizeToAvoidBottomInset`  is true, the `Scaffold` will use `MediaQuery.viewInsetsOf` to subscribe the changes and rebuild when it changes. **So set it to `false` when this page doesn't need to adjust `viewInsets`.**

- Using `Builder` to avoid rebuild all things in a page
```dart
class TextFieldPage extends StatefulWidget {
  const TextFieldPage({Key? key}) : super(key: key);
  @override
  State<TextFieldPage> createState() => _TextFieldPageState();
}

class _TextFieldPageState extends State<TextFieldPage> {

  @override
  Widget build(BuildContext context) {
    print("page build");
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          const Spacer(),
          const Text('Keyboard animation', style: TextStyle(fontSize: 26)),
          const Spacer(),
          Builder(builder: (BuildContext builderCtx) {
            /// If you use context, the whole page will be rebuild, you will see log "page build" and "builder build",
            /// but use builderCtx (after change you need to hot restart or recreate this page)
            /// you will only see log "builder build"
            MediaQuery.viewInsetsOf(builderCtx);
            print('builder build');
            return SizedBox(
                height: 60,
                child: const CupertinoTextField(
                  decoration: BoxDecoration(color: Colors.red),
                ));
          }),
        ],
      ),
    );
  }
}
```

**Comment by luckysmg** [comment]
@chunhtai Would you mind sharing your suggestions on this? since https://github.com/flutter/flutter/pull/116090#issuecomment-1356014347 is the suggestions for developers. It needs developer know more things to write code with higher performance.

**Comment by chunhtai** [comment]
I can't think of a systematic way to solve this problem from flutter side. If the developer has to have so many routes on the screen they should set https://api.flutter.dev/flutter/material/MaterialPageRoute/maintainState.html to false.

I am going to close this pr since I don't think this is the direction we want to go

**Pull request closed without merging**
