### PR TITLE
Nicer error message for TLS errors

### PR DESCRIPTION
**Pull request by Hixie**
Also some trivial improvements to style.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @tvolkert

**Comment by tvolkert** [comment]
test?

**Comment by tvolkert** [comment]
Also, LGTM

**Comment by Hixie** [comment]
@tvolkert What do you want me to test? And how? I mean I can test that we show a particular message instead of another message when getUrl throws a HandshakeException, but that seems like a pretty worthless test (if we change the message, we'd have to change the test). I can test that we don't silently catch the HandshakeException, but then I should also test that we don't catch any number of other exceptions, which doesn't really make sense. None of that would test what actually matters, which is that e.g. `curl` in the shell script that downloads Dart actually cares about TLS, or that `git` checks the certificates, etc.

**Comment by tvolkert** [comment]
I figured test that when we call `fetchUrl()` and it throws a `HandshakeException`, we throw a `ToolExit`.  But I agree that it's of questionable value, so I'm fine either way.

**Pull request merged**
