### PR TITLE
Deprecate VelocityTracker default constructor and added VelocityTracker.withKind constructor

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

We've gotten feedback that the VelocityTracker change was disruptive, though it did not break any of the flutter framework or customer tests. In order to make the change non-breaking, PointerDeviceKind parameter can be made optional.

Nevertheless, this parameter should be provided so that the existing touch handlers can use more accurate gestures on mouse/stylus inputs, so we can encourage this by deprecating the default constructor and pointing users towards the VelocityTracker.withKind constructor that takes a non-optional parameter

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 3 untriaged digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/66043

**Comment by skia-gold** [comment]
Gold has detected about 3 untriaged digest(s) on patchset 8.
View them at https://flutter-gold.skia.org/cl/github/66043

**Comment by goderbauer** [comment]
The change looks good.

My current thinking is that we should only submit this if the original change (without this fix) did not and will not make it into any stable releases. Otherwise, this may actually be even more disruptive...

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
This is probably worth cherry-picking?

**Comment by goderbauer** [comment]
> My current thinking is that we should only submit this if the original change (without this fix) did not and will not make it into any stable releases. Otherwise, this may actually be even more disruptive...

Nevermind, its an optional parameter now. So, if you already migrated, everything will continue to work.

**Comment by yunior123** [comment]
My problem still persist since this package https://pub.dev/packages/mp_chart is also depending on another package that uses the Velocity tracker class ->optimized_gesture_detector-0.0.5/lib/scale.dart:229:55: and requires a positional argument

**Pull request merged**
