### PR TITLE
Use test fonts in the test shell and remove custom font installation on Travis.

### LINKED ISSUE #6961: 4 input tests failing on OS X
## Steps to Reproduce

```
./dev/bots/test.sh
```

## Logs

```
00:36 +558 ~2: /Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/input_test.dart: - Can drag handles to change selection in multiline
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
00:36 +559 ~2: /Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/input_test.dart: - Can drag handles to change selection in multiline
The following TestFailure object was thrown running a test:
Expected: <138.0>
  Actual: <0.0>


When the exception was thrown, this was the stack:
#3      main.<anonymous closure>.<<anonymous closure>_async_body> (///Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/input_test.dart:545:5)
#17     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:520:16)
#18     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:366:5)
#19     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:506:24)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:504:16)
#26     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:54:50)
#27     Declarer.test.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (package:test/src/backend/declarer.dart:106:19)
#39     Declarer._runSetUps.<_runSetUps_async_body> (package:test/src/backend/declarer.dart:183:3)
(elided 65 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package
stack_trace)
00:36 +560 ~2: /Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/input_test.dart: - Can drag handles to change selection in multiline

This was caught by the test expectation on the following line:
  ///Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/input_test.dart line 545


════════════════════════════════════════════════════════════════════════════════════════════════════
00:36 +560 ~2 -1: /Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/input_test.dart: - Can drag handles to change selection in multiline
  Test failed. See exception logs above.
  
00:36 +562 ~2 -1: /Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/input_test.dart: - Can scroll multiline input
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
Expected: <225.0>
  Actual: <0.0>


When the exception was thrown, this was the stack:
#3      main.<anonymous closure>.<<anonymous closure>_async_body> (///Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/input_test.dart:636:5)
#17     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:520:16)
#18     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:366:5)
#19     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:506:24)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:504:16)
#26     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:54:50)
#27     Declarer.test.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (package:test/src/backend/declarer.dart:106:19)
#39     Declarer._runSetUps.<_runSetUps_async_body> (package:test/src/backend/declarer.dart:183:3)
(elided 65 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package
stack_trace)

This was caught by the test expectation on the following line:
  ///Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/input_test.dart line 636


════════════════════════════════════════════════════════════════════════════════════════════════════
00:36 +562 ~2 -2: /Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/input_test.dart: - Can scroll multiline input
  Test failed. See exception logs above.
  
00:47 +676 ~2 -2: /Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/scrollable_fling_test.dart: - fling and tap to stop
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
Expected: ['tap 18']
  Actual: ['tap 17']
   Which: was 'tap 17' instead of 'tap 18' at location [0]


When the exception was thrown, this was the stack:
#3      main.<anonymous closure>.<<anonymous closure>_async_body> (///Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/scrollable_fling_test.dart:73:5)
#17     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:520:16)
#18     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:366:5)
#19     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:506:24)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:504:16)
#26     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:54:50)
#27     Declarer.test.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (package:test/src/backend/declarer.dart:106:19)
#39     Declarer._runSetUps.<_runSetUps_async_body> (package:test/src/backend/declarer.dart:183:3)
(elided 65 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package
stack_trace)

This was caught by the test expectation on the following line:
  ///Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/scrollable_fling_test.dart line
  73


════════════════════════════════════════════════════════════════════════════════════════════════════
00:47 +676 ~2 -3: /Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/scrollable_fling_test.dart: - fling and tap to stop
  Test failed. See exception logs above.
  
00:49 +689 ~2 -3: /Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/scrollable_fling_test.dart: - fling and wait and tap
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
Expected: ['tap 18']
  Actual: ['tap 17']
   Which: was 'tap 17' instead of 'tap 18' at location [0]


When the exception was thrown, this was the stack:
#3      main.<anonymous closure>.<<anonymous closure>_async_body> (///Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/scrollable_fling_test.dart:96:5)
#17     AutomatedTestWidgetsFlutterBinding.asyncBarrier (package:flutter_test/src/binding.dart:520:16)
#18     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:366:5)
#19     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:506:24)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:504:16)
#26     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:54:50)
#27     Declarer.test.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (package:test/src/backend/declarer.dart:106:19)
#39     Declarer._runSetUps.<_runSetUps_async_body> (package:test/src/backend/declarer.dart:183:3)
(elided 65 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package
stack_trace)

This was caught by the test expectation on the following line:
  ///Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/scrollable_fling_test.dart line
  96


════════════════════════════════════════════════════════════════════════════════════════════════════
00:49 +689 ~2 -4: /Users/lukechurch/GitRepos/flutter/packages/flutter/test/widgets/scrollable_fling_test.dart: - fling and wait and tap
  Test failed. See exception logs above.
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/lukechurch/GitRepos/flutter
    • Framework revision 39872e7df1 (47 minutes ago), 2016-11-21 11:49:35
    • Engine revision cea5ed2b9b
    • Tools Dart version 1.21.0-dev.6.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/lukechurch/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.1, Build version 8B62

[✓] IntelliJ IDEA Ultimate Edition (version 2016.2.5)
    • Dart plugin installed
    • Flutter plugin installed

[✓] Connected devices
    • None
```

### PR DESCRIPTION
**Pull request by chinmaygarde**
Removes the hack previously added for Travis. Fixes https://github.com/flutter/flutter/issues/6961. Depends on https://github.com/flutter/engine/pull/3301.

### CODE REVIEW

**Comment by jason-simmons** [comment]
LGTM

**Comment by chinmaygarde** [comment]
Updated to include engine roll. Also fixes https://github.com/flutter/flutter/issues/7224.

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
Reverting this because it's causing tests to silently fail (we suspect the engine roll).

**Pull request merged**
