### PR TITLE
[flutter roll] Revert both #117338 and #117547

### PR DESCRIPTION
**Pull request by XilaiZhang**
Reverts flutter/flutter#117338.

tooltip related tests are failing in https://b.corp.google.com/issues/263351045
revert two PRs based on https://github.com/flutter/flutter/pull/117558#issuecomment-1363456415

### CODE REVIEW

**Comment by chunhtai** [comment]
while most tests are expected, this seems to need a g3 fix https://fusion2.corp.google.com/invocations/2756fe61-3b93-4898-a5d4-7badfde614cb/targets/%2F%2Fassistant%2Fgallium%2Fdragonglass%2Fsystem%2Fquick_settings:quick_settings_gallium_tests_test_quick_settings_gallium_tests_test_quick_settings_integration_test_test_entry.host/tests

Can you also revert this as part of this revert? https://github.com/flutter/flutter/commit/bd482ebc54cdbdf1acbaf096e2fd06a0563158ad
otherwise the test will start failing

**Comment by XilaiZhang** [comment]
Ahh right Jenn also mentioned https://github.com/flutter/flutter/commit/bd482ebc54cdbdf1acbaf096e2fd06a0563158ad . Just to confirm our approach, would the plan be to revert both PRs, or keep them and submit a g3fix for the assistant failures? (we would probably need help to create such a g3fix)

**Comment by chunhtai** [comment]
If this is urgent, feel free to revert it. If not I can create a g3fix to fix the issue

**Comment by XilaiZhang** [comment]
sounds good, thank you! it's likely that we will hit it in the next roll, i will put up reverts then.

**Review by chunhtai — APPROVED** [review]
LGTM

**Pull request merged**
