### PR TITLE
Update `hello-world`example to support macOS and Windows

### PR DESCRIPTION
**Pull request by GroovinChip**
This PR updates the `hello-world` example application to support the macOS and Windows build targets

Partly addresses #84306.

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hey @GroovinChip! Good to see you! & thank you for the contribution. :)

It looks like there are some failing checks here, and an unfortunate amount of merge conflicts. 😞 
 Did you need to update packages on this PR? We usually do that for the whole repo at once in an individual change.

cc'ing @gspencergoog who has been looking at some updates to sample code. This may be something for the samples repo.

**Comment by GroovinChip** [comment]
Hi @Piinks ! Nice to see you too! Yes, I did need to update packages here.

**Comment by Piinks** [comment]
Thanks! Do you want to continue with this change? It may be difficult to address all these merge conflicts and failures. If you want to open a fresh PR, let me know! :)

**Comment by GroovinChip** [comment]
I'm

> Thanks! Do you want to continue with this change? It may be difficult to address all these merge conflicts and failures. If you want to open a fresh PR, let me know! :)

I think a fresh PR might be better

**Comment by Piinks** [comment]
I am going to close this per the last comment. Thanks @GroovinChip!

**Pull request closed without merging**
