### PR TITLE
Remove stray PRODUCT_BUNDLE_IDENTIFIER

### PR DESCRIPTION
**Pull request by eseidelGoogle**
This was erroneously added and overrides
the bundle for the gallery causing signing
to fail in my setup.

@chinmaygarde

### CODE REVIEW

**Comment by chinmaygarde** [comment]
lgtm

**Comment by eseidelGoogle** [comment]
Looks like this is actually in the create template and thus everywhere:
https://github.com/flutter/flutter/search?utf8=%E2%9C%93&q=PRODUCT_BUNDLE_IDENTIFIER

I should probably file a bug

**Comment by eseidelGoogle** [comment]
@chinmaygarde updated to remove all of them.  Please verify that you agree these make sense to remove.  I suspect that Flutter.xcodeproj should be setting these always, no?

**Comment by chinmaygarde** [comment]
lgtm

**Pull request merged**
