### PR TITLE
Deleted deprecated profile func and profile.dart

### PR DESCRIPTION
**Pull request by kaparray**
### Description

For more than a year the project contains a function that is not used and deprecated after v1.3.9 in Flutter

### Related Issues
#57840

### CODE REVIEW

**Comment by PixelToast** [comment]
Tests are failing because profile.dart is still exported by the foundation library
```
Compiler message:
../../packages/flutter/lib/foundation.dart:55:1: Error: Error when reading '../../packages/flutter/lib/src/foundation/profile.dart': No such file or directory
export 'src/foundation/profile.dart';
^
```

**Comment by kaparray** [comment]
@PixelToast  Fixed

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by kaparray** [comment]
@goderbauer May be need to update https://api.flutter.dev/flutter/foundation/profile.html?

**Comment by goderbauer** [comment]
That will update once the commit reaches the stable channel.

**Comment by kaparray** [comment]
Flutter team have use dartdoc?

**Pull request merged**
