### PR TITLE
Make the material DropdownButton's icon configurable.

### PR DESCRIPTION
**Pull request by mfiels**
cc: @mehmetf

### CODE REVIEW

**Comment by mehmetf** [comment]
@HansMuller could you review this? I know we would like to adhere to Material specs as much as possible and avoid API bloat. I don't recall Material allowing icon to be configurable.

**Review by HansMuller — COMMENTED** [review]
This looks like a reasonable DropdownButton enhancement and I think making the icon configurable jibes with Material's emphasis on customization.

It would be more flexible if the icon's type was Widget and the IconTheme widget was used to configure the icon's size/color.

If icon is allowed to be null (also seems reasonable), the implementation needs to DTRT.

A test will be needed.

**Review by HansMuller — CHANGES_REQUESTED** [review]
Just a reminder: waiting for changes per the review

**Comment by HansMuller** [comment]
I'm going to close this PR since there hasn't been any activity for a while.

**Pull request closed without merging**
