### PR TITLE
Revert "migrate some material files to nullsafety"

### PR DESCRIPTION
**Pull request by goderbauer**
Reverts flutter/flutter#67078

This is failing tests in google. Will investigate on Monday.

### CODE REVIEW

**Review by nturgut — APPROVED** [review]
LGTM for revert.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
cc @pcsosinski for visibility

**Comment by renyou** [comment]
Google testing failed because of merge conflict. I will merge this one now.

**Pull request merged**
