### PR TITLE
Move mac pixel 7 pro test to presubmit: false

### PR DESCRIPTION
**Pull request by zanderso**
The only bot with this configuration in the try pool just died.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by godofredoc — APPROVED** [review]

**Comment by jonahwilliams** [comment]
Landing on red to fix tree.

**Comment by johnmccutchan** [comment]
@zanderso How do we replace this bot?

**Comment by yusuf-goog** [comment]
We have the following tesbeds in try pool with Pixel devices:

flutter-devicelab-linux-26 |Pixel 7 Pro | Ubuntu 20.04 Focal Fossa (Ubuntu-20.04)
-- | -- | -- 
flutter-devicelab-linux-53 | iPixel 7 Pro | Ubuntu 20.04 Focal Fossa (Ubuntu-20.04)
flutter-devicelab-mac-19 | Pixel 7 Pro | Mac-13.6.1-22G313\

@johnmccutchan we should definitely add more testbeds if we want these builds to be blocking.

**Comment by zanderso** [comment]
> @johnmccutchan we should definitely add more testbeds if we want these builds to be blocking.

To clarify, I think by "to be blocking" here you mean, "to run in presubmit".

**Comment by yusuf-goog** [comment]
> > @johnmccutchan we should definitely add more testbeds if we want these builds to be blocking.
> 
> To clarify, I think by "to be blocking" here you mean, "to run in presubmit".

Something that would turn the tree red, which "run in presubmit" would I beleive.

**Pull request merged**
