### PR TITLE
Bump cocoapods from 1.10.2 to 1.11.2

### PR DESCRIPTION
**Pull request by jmagman**
Bumps [cocoapods](https://github.com/CocoaPods/CocoaPods) from 1.10.2 to 1.11.0.

Testing https://github.com/CocoaPods/CocoaPods/pull/10937 in our CI, see https://github.com/CocoaPods/CocoaPods/issues/10927

### CODE REVIEW

**Comment by christopherfujino** [comment]
Pretty sure we can ignore Cirrus' `Build Parsing Results` check.

**Comment by jmagman** [comment]
> Pretty sure we can ignore Cirrus' `Build Parsing Results` check.

Wonder why that didn't happen in https://github.com/flutter/flutter/pull/89561/checks

**Comment by christopherfujino** [comment]
> https://github.com/flutter/flutter/pull/89561/checks

It didn't run at all--I'm assuming this is something new they just introduced. However, I should look into it, since it looks like we're not even using rubygems on linux anymore?

**Review by christopherfujino — APPROVED** [review]
lgtm

**Comment by jmagman** [comment]
> It didn't run at all--I'm assuming this is something new they just introduced. However, I should look into it (separate from this change), since it looks like we're not even using rubygems on linux anymore?

Filed https://github.com/flutter/flutter/issues/89993.

**Comment by jmagman** [comment]
Woo, `Mac plugin_lint_mac` passed!
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8836185115385117969/+/u/run_plugin_lint_mac/test_stdout

**Comment by jmagman** [comment]
Ignoring `Build Parsing Results` per https://github.com/flutter/flutter/issues/89993, merging.

**Pull request merged**
