### PR TITLE
Remove build phase restriction on Element.didChangeDependencies and InheritedElement.dispatchDidChangeDependencies

### PR DESCRIPTION
**Pull request by kezhuw**
Document of InheritedElement.dispatchDidChangeDependencies states that:

> Subclasses of [InheritedElement] might wish to call this function at other times if their inherited information changes outside of the build phase.

While commit 8c3d5838dd539fec52731bdce3dc73bcc11c4f7c(#12213) applies build phase restriction on Element.didChangeDependencies and InheritedElement.dispatchDidChangeDependencies.

This PR adds test to comply with the documentation and removes that restriction.

### CODE REVIEW

**Comment by Hixie** [comment]
It might be better to go the other way and adjust the documentation, unless you have a good use case for dispatching it asynchronously.

**Comment by kezhuw** [comment]
This is an API design issue, are Element.didChangeDependencies and InheritedElement.dispatchDidChangeDependencies supposed to be called outside build phase ?

My answer to this is YES.

InheritedWidget is some sort of implicit state to its dependents. Just like State.setState can be called asynchronously to change part of its state, subclasses of InheritedWidget should also be able to change their state partially and asynchronously. If we agree on this, there must some apis exist to notify element its dependencies changed, just like markNeedsBuild for State.setState. Element.didChangeDependencies serves this purpose.

Actually, InheritedElement.dispatchDidChangeDependencies (named dispatchDependenciesChanged previously) was introduced in #3580 to solve mutable state change, as its statement from commit message and document:

> Some inherited widgets want to call this function direction, for example to
notify children when a mutable model object changes. Exposing this function to
subclasses of InheritedWidget is clear then forcing them to compute
updateShouldNotify for mutable model objects.

> Subclasses of [InheritedElement] might wish to call this function at other times if their inherited information changes outside of the build phase.

I think it was an accident for #12213 to introduce build phase restriction without noticing semantics change on this api.

@abarth @yjbanov Please, take a look at this PR.

**Comment by abarth** [comment]
> subclasses of InheritedWidget should also be able to change their state partially and asynchronously

InheritedWidget objects are stateless, so I'm not sure I agree that they should be able to change their state (specifically, because they do not have any state).

> Some inherited widgets want to call this function direction, for example to
notify children when a mutable model object changes

Another pattern you might try for solving this problem is for the mutable model object to implement `Listenable` and for widgets that use the model to listen to the model itself.  This approach scales better, for example, if the mutable model has multiple parts that are independently `Listenable`.

**Comment by kezhuw** [comment]
Sorry for confusing word "state" in context, I mean "mutable object" here.

I think there is no easy way to trigger rebuild for StatelessWidgets if `Listenable` notifies.

Current implementation of InheritedElement exports nothing about its dependents. The only API it exports is dispatchDidChangeDependencies which trigger rebuilds for **all dependents**. It can't scale well without knowledge of its dependents. 

I push a new commit b6c78d48ad745a2ec5cccc7cf6b26ec68f579fae which has API break change (marking InheritedElement abstract) to show that it can scales well.

PS: I am not so familiar with flutter's API, if something was wrong, point it out, thanks.

**Comment by abarth** [comment]
> I think there is no easy way to trigger rebuild for `StatelessWidgets` if `Listenable` notifies.

The easiest way is probably to use an `AnimatedBuilder` to listen to the `Listenable`.  It will call its `builder` function again then the `Listenable` notifies:

https://docs.flutter.io/flutter/widgets/AnimatedBuilder-class.html

**Comment by kezhuw** [comment]
`AnimatedBuilder` is an wrapper around `StatefulWidget`.

The `Listenable` approach forces descendant widgets to reshape their structure around `StatefulWidget` in order to trigger rebuild using `State.setState`, usually with empty statements. This sounds somewhat unfriendly to API clients.

On the other side, with knowledge of descendants, API like `MultiplePartsInherited.partOf(BuildContext context, String part)` or `MultiplePartsInherited.firstPartOf(BuildContext context)` should be capable to provide guarantee that widgets only got rebuild triggered by parts they depends on. There is no reshape burden for API clients, if `StatelessWidget` is capable, just use it. If the model object as a whole changed, just rebuild all dependents, there is no need to code boilerplate like removeListener/addListener if dependent is a `StatefulWidget` itself.

**Comment by yjbanov** [comment]
@kezhuw I agree with your observation that `InheritedWidget` is a kind of implicit input for widgets in the subtree. However, I'm not yet clear on the way you draw an analogy between `Element.didChangeDependencies` and `State.setState`.

`setState` gives a signal to the framework that a sub-tree needs to be rebuilt. It does not immediately call the `build()` methods. The `build()` methods are called during the next build phase. Therefore it is safe to call `setState` outside the build phase.

If you treat `didChangeDependencies()` like a `build()` method, similarly you would not call it outside the build phase, but instead use another signal that would cause the framework to call `didChangeDependencies` in the next build phase. That signal is _also_ `setState`. The difference, is that _that_ `setState` can happen _higher_ in the hierarchy of widgets. Usually, as a result of a higher-level `setState` an `InheritedWidget` gets rebuilt, its `updateShouldNotify` is called, and if it was decided that notifications must be sent, the `didChangeDependencies` are called (transitively via `dispatchDidChangeDependencies`). All that propagation happens within the build phase.

**Comment by kezhuw** [comment]
@yjbanov 

>However, I'm not yet clear on the way you draw an analogy between Element.didChangeDependencies and State.setState.
>
> setState gives a signal to the framework that a sub-tree needs to be rebuilt. It does not immediately call the build() methods. The build() methods are called during the next build phase. Therefore it is safe to call setState outside the build phase.

`State.setState` and `Element.didChangeDependencies` both call `Element.markNeedsBuild` finally. `Element.didChangeDependencies` don't call `build()` directly either.

> If you treat didChangeDependencies() like a build() method, similarly you would not call it outside the build phase, but instead use another signal that would cause the framework to call didChangeDependencies in the next build phase. That signal is also setState. The difference, is that that setState can happen higher in the hierarchy of widgets. Usually, as a result of a higher-level setState an InheritedWidget gets rebuilt, its updateShouldNotify is called, and if it was decided that notifications must be sent, the didChangeDependencies are called (transitively via dispatchDidChangeDependencies). All that propagation happens within the build phase.

I make no analogy between `Element.didChangeDependencies` and `build()`, but `Element.didChangeDependencies` does play two roles in current implementation:
* Notification: Notify the framework that dependencies of an element got changed, hence needs to be rebuilt. Same as `State.setState` notify the freamework that state of an element got changed, hence needs to be rebuilt. Image a name `Element.markDependenciesChanged` with no passive meaning.
* Callback: The framework call this to let widgets re-establish their dependencies as a response to `Element.markDependenciesChanged`. Much like `build()` method to `Element.markNeedsBuild`. `State.didChangeDependencies` plays this role in current implementation. Image a name `Element.didDependenciesChanged` with no verbal meaning.

**Comment by Hixie** [comment]
@kezhuw Can you file a bug for this issue so we can make a decision on whether to fix it by changing the docs or changing the code?

**Comment by kezhuw** [comment]
@Hixie See #13176.

**Pull request closed without merging**
