### PR TITLE
[Windows Arm64] Also use Windows 11 for Devicelab tests

### PR DESCRIPTION
**Pull request by loic-sharma**
Currently, the Windows Arm64 tests try to run on Windows 10 devices. However, [all Windows Arm64 devices use Windows 11](https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=os&c=status&d=asc&f=cpu%3Aarm64&f=os%3AWindows-11&f=pool%3Aluci.flutter.staging&s=id) which result in the Windows Arm64 tests not running. This updates the configuration to accept both Windows 10 and 11 (ideally the tests would run on both OSes).

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
SHIP IT

**Review by christopherfujino — CHANGES_REQUESTED** [review]
although actually, can we be less specific and say `Windows`?

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by ricardoamador — APPROVED** [review]
LGTM

**Comment by ricardoamador** [comment]
Are these tests meant to run in staging?
Also I don't think you can use just Windows as that is a generic term for the OS bet it Windows-10 or Windows-11.

**Comment by ricardoamador** [comment]
image
vs Windows-11
image

**Comment by ricardoamador** [comment]
Ah duh. Reading comprehension fail.
Carry on and disregard what I said.

**Comment by loic-sharma** [comment]
> Are these tests meant to run in staging?

Yes that's correct as that's the only pool that has Windows Arm64 machines. Are the properties acceptable for that?

**Comment by ricardoamador** [comment]
Yes. Should be as long as the tests are marked as bring: true

**Pull request merged**
