### PR TITLE
Update expansion_panel.dart and add iconColor

### PR DESCRIPTION
**Pull request by AliHoseinpoor**
Add a color value for the header icon and add a color value for when the icon is disabled (canTapOnHeader = true) and add a color value for when the header is expanded

before :
Screenshot-20211215010206-2466x114

after :
Screenshot-20211215010231-2460x118

issues are fixed by this PR : #80295

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by AliHoseinpoor** [comment]
How can i solve luci-flutter failure?

**Comment by HansMuller** [comment]
The goal of this PR seems reasonable however it would be better to use a `MaterialStateProperty<Color?>` property for colors that depend on the component's state. And a regression test will be needed.

**Comment by Hixie** [comment]
@AliHoseinpoor Thanks for your contribution! Would you be willing to apply the change @HansMuller suggested above?

**Comment by Hixie** [comment]
I'm going to close this since it hasn't been touched for a while, to get it off our review queue. Please don't hesitate to reopen it if you have a chance to get back to it. Thanks!

**Pull request closed without merging**
