### PR TITLE
Start using `@immutable` annotations

### PR DESCRIPTION
**Pull request by abarth**
There are more places we can use this annotation, but this patch just gets us
started.

### CODE REVIEW

**Comment by abarth** [comment]
This annotation doesn't quite seem to work yet, but here's what I've got so far.

**Comment by tvolkert** [comment]
LGTM

**Comment by Hixie** [comment]
LGTM in principle, but if it doesn't work yet then I hesitate to add it. I wouldn't want to force dealing with any errors we made onto whoever next rolls Dart.

**Comment by tvolkert** [comment]
Maybe try to bump to dev.11.0 in this PR and see if there's any other work required?

**Comment by abarth** [comment]
The turning Dart to 11 is https://github.com/flutter/flutter/pull/9151, which is blocked on a VM bug.

**Comment by abarth** [comment]
`@immutable` is too aggressive.  Blocked on https://github.com/dart-lang/sdk/issues/29267

**Pull request merged**
