### PR TITLE
Fix consolidate HTTP response and add test 

### LINKED ISSUE #17034: NetworkAssetBundle failure with GZIP encoding
If I try to use the following code:

```
loadNetworkAsset('https://upload.wikimedia.org/wikipedia/commons/b/b0/Letters_SVG.svg');

Future<String> loadNetworkAsset(String uri) async {
  final NetworkAssetBundle _network =
      new NetworkAssetBundle(Uri.base.resolve(uri));
  return await _network.loadString(uri);
}
```

Fails:
>RangeError (end): Invalid value: Not in range 0..670, inclusive: 818
  dart:typed_data                                                 __Uint8List&_TypedList&_IntListMixin.setRange
  package:flutter/src/foundation/consolidate_response.dart 38:13  consolidateHttpClientResponseBytes.<fn>
  ===== asynchronous gap ===========================
  dart:_http                                                      _HttpClientResponse.listen
  package:flutter/src/foundation/consolidate_response.dart 37:14  consolidateHttpClientResponseBytes
  package:flutter/src/services/asset_bundle.dart 123:35           NetworkAssetBundle.load
  ===== asynchronous gap ===========================

The content-length in  header sent back is for the gzipped size of the content, but by the time `NetworkAssetBundle` gets it `HttpClient` has already decompressed the data for us and our buffer won't be big enough.

While this should be patched here, there is another bug with HttpClient at play - even if we don't trust the content length, in this case it's marking the stream as done __before all of the content has been decoded__.  So the client gets back a response that's missing the last chunk of data.  I'll file another issue about that in the DArt issues.

### PR DESCRIPTION
**Pull request by dnfield**
Fixes #17034 

There still seems to be an underlying issue where the stream is getting marked as done on devices/emulators before it's actually done, but this is to fix the issue where content-length is not accurate (whether because of gzip or some other transformer being applied to the stream before we get it here).

PR #17035 got messed up (CLA bot didn't like it after a rebase) so opening this one instead.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
LGTM, but I've also added @Hixie.

**Comment by dnfield** [comment]
Not really sure why appveyor is failing here.

**Comment by dnfield** [comment]
Whatever might've been going on with the UTF8/GZIP issue is either no longer an issue or was just due to log truncation in print statements.  All that's left for this is the faulty trusting of content-length.

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
