### PR TITLE
Check the type of a hot reload report message

### PR DESCRIPTION
**Pull request by jason-simmons**
See https://github.com/flutter/flutter/issues/7248

### CODE REVIEW

**Comment by jason-simmons** [comment]
@johnmccutchan

**Comment by Hixie** [comment]
Why are we receiving an invalid response?

**Comment by Hixie** [comment]
If we want to be resilient to invalid data, we should probably be more defensive. This code assumes that there's a `type` entry and that if it has the magic value, that the rest of the data will be in the expected format. Is that a safe assumption?

If it is, then, with a test, LGTM.

**Comment by jason-simmons** [comment]
Added a test.

This will check the type of the report message (if it's null/missing, it will return false).  If the type is as expected, it will continue with the preexisting rules.  @johnmccutchan would know if any other rules are needed.

**Comment by johnmccutchan** [comment]
@Hixie The service protocol guarantees responses with certain `type` field will have a certain shape.

LGTM

**Pull request merged**
