### PR TITLE
Use SDK sources to refer to our own packages

### PR DESCRIPTION
**Pull request by abarth**
Switch our pubspec.yamls to using SDK sources so that we can have consistent
source types when we depend on these packages from external packages using SDK
sources.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

**Comment by sethladd** [comment]
fyi @nex3

**Comment by abarth** [comment]
This patch will require all existing clients of flutter that use `pubspec.yaml` to edit their pubspecs.  I'll send emails after it lands explaining what to do.

**Comment by Hixie** [comment]
LGTM, but travis is angry.

**Comment by yjbanov** [comment]
Most of our on-device tests started failing with messages such as:

```
The Flutter SDK is not available.
Depended on by:
- complex_layout 
```

[build history](https://flutter-dashboard.appspot.com/build.html)
[sample log file](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9jMWEyOTY3NDMwMzk2ODE4M2UyZGI4OGRkMGE5ZWMyODEzNTg2NTYxDAsSBFRhc2sYgICAgICAwAgM)

**Comment by abarth** [comment]
Where do I fixenate?  I need to change the dependencies in the pubspec.yaml to use "sdk: flutter" instead of "path: ../../whatever"

**Comment by abarth** [comment]
Alternatively, if these are running `pub get` directly, I need to switch them to use `flutter packages get`.

**Comment by abarth** [comment]
Attempted fix in https://github.com/flutter/cocoon/pull/52

**Comment by yjbanov** [comment]
👍 for the fix. I'll deploy tomorrow (but hopefully soon all this code will move to the main repo)

**Comment by abarth** [comment]
Thanks.  Great!  Sorry for the disruption.

**Pull request merged**
