### PR TITLE
debounce for SearchDelegate

### PR DESCRIPTION
**Pull request by cantaspinar**
## Description

Flutter has a nice way to implement search functionality by using SearchDelegate. However, it is not possible to wait certain amount of time on query(search text) changes. As it is an important factor when making requests to a server, this PR allows passing a debounceDuration to SearchDelegate so that the widget can rebuild itself when the query changed and debounce duration has passed.

## Related Issues

No issue, new feature

## Tests

I added the following tests:

> 'Search with debounce duration' is added to flutter/test/material/search_test.dart

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by HansMuller** [comment]
I think it would make more sense for applications to debounce (and buffer and cache) search queries and their results. Maybe what's needed is an example for the docs?

**Comment by cantaspinar** [comment]
@HansMuller I wasn't able to handle custom logic with in the SearchDelegate. You don't have access to TextController and everytime you write something buildSuggestions is rebuild.

**Comment by HansMuller** [comment]
You could cache the the widget value returned by buildSuggestions and reuse it if your debounce timer hasn't expired. Returning the same widget tree in this case will prevent costly relayout or repainting.

That said, it might be useful to give the developer a way to override the default behavior of _onQueryChanged(). Instead of unconditionally calling setState() the developer might only do so when the query had changed sufficiently or a timer had expired or whatever.

**Comment by cantaspinar** [comment]
Giving a way to override _onQueryChanged() is a good option since it would allow developer to control the logic on query changes. Implementing features like debouncing would require less work.

**Comment by shihaohong** [comment]
Hi @cantaspinar, do you plan on implementing the override for `_onQueryChanged` as discussed above?

**Comment by cantaspinar** [comment]
Hey @shihaohong , I will try to implement it this week. I am still using the current implementation for debouncing search but I believe giving the ability to override _onQueryChanged would be more convenient. Have any suggestions?

**Comment by shihaohong** [comment]
Giving the ability to override `_onQueryChanged` makes sense to me!

**Comment by shihaohong** [comment]
Hi @cantaspinar, any updates or progress on this feature so far?

**Comment by cantaspinar** [comment]
Hey @shihaohong, it was a busier week than I expected. I will hopefully have a look at this in the following days.

**Comment by shihaohong** [comment]
Hi, is this coming along? If you're busy, we can close this PR and re-open it when you get back to it. Let me know! :)

**Comment by cantaspinar** [comment]
Hi, I am sorry for the delay. I am working on it right now. However, I am stuck at some point and need some other thoughts. Right now all _onQueryChanged method  does is calling setState to rebuild the widget. I thought it might be a good idea to create a new method in SearchDelegate and change the body of _onQueryChanged from setState() to widget.delegate.onQueryChanged() in _SearchPage widget. So someone would be able to override the method when extending from SearchDelegate class. However, I am not sure how to call setState method inside a class which extends SearchDelegate since it is not a widget. Any thoughts on that?

**Comment by shihaohong** [comment]
I just did a dive into the different parts involved in creating the search page and it doesn't seem very straightforward. Calling `setState` from the delegate is complicated because the `_SearchPageState` is private, but I also do not think we usually call setState anywhere else but within the State class itself.

One way I can think of doing this is to create a new `setSearchState` method in `SearchDelegate` and setting it as a reference to `_SearchPageState.setState` when `_SearchPageState` is initialized, which would allow you to call `setState` in the search delegate. I haven't tested out if that works as expected and whether or not that's considered an anti-pattern.

**Comment by shihaohong** [comment]
Hi @cantaspinar, any updates on this PR?

**Comment by shihaohong** [comment]
I'm going to close this issue for now since there's been inactivity. Please feel free to reopen the PR when you've had time to pick this up :) Thank you!

**Pull request closed without merging**
