### PR TITLE
[WIP] Page Up / Page Down in text fields

### PR DESCRIPTION
**Pull request by tgucio**
This PR implements the page up/down and shift + page up/down keyboard shortcuts:
- page up/down move caret
- shift page up/down extend the selection by page
- traversing text using page up/down keeps vertical text runs
- no changes in ScrollAction

page-up-down

The corresponding macOS shortcuts which scroll without moving the caret are implemented in PR [#105497](https://github.com/flutter/flutter/pull/105497).

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
@tgucio Looks like the analyzer check found some issues. Can you take a look and fix those up? While you're at it, maybe also fix the merge conflict? Thanks.

**Comment by tgucio** [comment]
@goderbauer sure - resuming to look into this PR now (it also needs adding some tests).

**Comment by goderbauer** [comment]
@tgucio Do you still have plans to add tests soon?

**Comment by tgucio** [comment]
@goderbauer just took a first stab at adding tests.
I pushed two commits with another email (w/o CLA) so since I can't force push to correct that I've opened a new PR: https://github.com/flutter/flutter/pull/107600

**Pull request closed without merging**
