### PR TITLE
Roll Engine from ce9eef7bacf2 to 46c2ccae24e4 (10 revisions)

### PR DESCRIPTION
**Pull request by engine-flutter-autoroll**
https://github.com/flutter/engine/compare/ce9eef7bacf2...46c2ccae24e4

2022-03-16 skia-flutter-autoroll@skia.org Roll Skia from e253cc3e55d3 to 9301fe3779bb (1 revision) (flutter/engine#32064)
2022-03-16 mdebbar@google.com [web] Position spans absolutely within paragraph (flutter/engine#31907)
2022-03-16 skia-flutter-autoroll@skia.org Roll Skia from 0d81bc7bb04e to e253cc3e55d3 (1 revision) (flutter/engine#32063)
2022-03-16 skia-flutter-autoroll@skia.org Roll Fuchsia Mac SDK from jvlI1s78T... to vWlaMIVkM... (flutter/engine#32060)
2022-03-16 skia-flutter-autoroll@skia.org Roll Skia from 8afe53fd76d3 to 0d81bc7bb04e (2 revisions) (flutter/engine#32057)
2022-03-16 skia-flutter-autoroll@skia.org Roll Skia from a9bc6c643791 to 8afe53fd76d3 (1 revision) (flutter/engine#32056)
2022-03-16 skia-flutter-autoroll@skia.org Roll Fuchsia Linux SDK from Ee9OX2o6P... to mVqiTwaVa... (flutter/engine#32055)
2022-03-16 31859944+LongCatIsLooong@users.noreply.github.com [macOS] Forward key events to NSTextInputContext when there's composing text (flutter/engine#32051)
2022-03-16 dnfield@google.com Make tracing safe (flutter/engine#32042)
2022-03-16 lihaohua90@gmail.com [windows] Support win_debug_x86 compilation target in engine (flutter/engine#30417)

Also rolling transitive DEPS:
  fuchsia/sdk/core/linux-amd64 from Ee9OX2o6PFEo to mVqiTwaVayg4
  fuchsia/sdk/core/mac-amd64 from jvlI1s78Ta29 to vWlaMIVkMNGE

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/flutter-engine-flutter-autoroll
Please CC jsimmons@google.com on the revert to ensure that a human
is aware of the problem.

To file a bug in Flutter: https://github.com/flutter/flutter/issues/new/choose

To report a problem with the AutoRoller itself, please file a bug:
https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 10.
View them at https://flutter-gold.skia.org/cl/github/100244

**Comment by zanderso** [comment]
@mdebbar Is this also the same issue?

**Comment by mdebbar** [comment]
@zanderso no, this one is caused by the browser sometimes producing slightly different screenshot for the same test. We do have a threshold in place to allow some margin or variation, but every once in a while there'll be instances that vary beyond our thresholds.

I haven't figured out a solution for this yet. It happens infrequently though.

**Comment by zanderso** [comment]
@mdebbar Thanks. I accepted the diffs.

**Review by zanderso — APPROVED** [review]

**Pull request merged**
