### PR TITLE
Reland fuchsia_remote_debug_protocol allows open port on remote device

### PR DESCRIPTION
**Pull request by satsukiu**
## Description

Relands #63996 and fixes an issue where ipv4 addresses are incorrectly identified as ipv6 addresses and wrapped in brackets.

The original set of changes is the first commit, the second commit contains the fixes.

Original description:
This change extends the functionality of the fuchsia_remote_debug_protocol package. Currently, the package allows forwarding ports from a host device to some other target device running a Flutter instance, which enables the host device to access the debug port exposed by the Flutter instance.
This updates the definition of a port forwarding function to allow for cases where the host device accesses the debug port by calling a port on the target device rather than the local loopback of the host device.

## Related Issues

63968

## Tests

The change is largely tested against internal tests.

I added the following tests:

* End to end test from the original change.
* Unit tests to verify ipv4/ipv6 address detection.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by satsukiu** [comment]
@zanderso Would you be able to take a look again?

/cc @renyou

**Comment by zanderso** [comment]
@satsukiu did you add a unit test here for the case that was failing internally?

**Comment by satsukiu** [comment]
I did add some small unit tests for the ip address detection in network.dart.
I just noticed the end to end unit tests here don't have an ipv4 case, though. I'll add one.

**Comment by satsukiu** [comment]
Added a new case in the latest commit.

**Review by zanderso — APPROVED** [review]

**Pull request merged**
