### PR TITLE
Drop unused docs-linux task on Cirrus

### PR DESCRIPTION
**Pull request by dnfield**
@godofredoc @tvolkert @Hixie

### CODE REVIEW

**Comment by Hixie** [comment]
Running the shard itself would be good, just to get people feedback about docs errors (a _lot_ of contributions we get by people who can't use LUCI before getting review are docs-related). But we can get rid of the credentials part.

**Comment by Hixie** [comment]
test-exempt: this is a test.

**Comment by dnfield** [comment]
Ahh, I was falsely under the impression that we were running this on LUCI presubmit - we only run it on LUCI postsubmit.

**Review by godofredoc — APPROVED** [review]

**Comment by christopherfujino** [comment]
> Ahh, I was falsely under the impression that we were running this on LUCI presubmit - we only run it on LUCI postsubmit.

we do run it on pre-submit: https://ci.chromium.org/p/flutter/builders/try/Linux%20docs

it didn't trigger on this PR because none of hte `run_if` globs matched the file diff: https://github.com/flutter/flutter/blob/master/dev/try_builders.json#L39

**Comment by dnfield** [comment]
So should we just drop the cirrus task after all?

**Comment by Hixie** [comment]
The plan is to not run _any_ LUCI shards for non-team-members until a team-member has reviewed the PR. That's why we want Cirrus shards at all.

**Pull request merged**
