### PR TITLE
Add support for Gradle Kotlin DSL

### LINKED ISSUE #93238: Gradle Kotlin DSL support.
How should Flutter use Gradle Kotlin DSL?
I got many errors while trying to suggest Groovy to Kotlin.
I saw [33726](https://github.com/flutter/flutter/issues/33762) but didn't find a solution.

### PR DESCRIPTION
**Pull request by bartekpacia**
Fixes #93238.

Gradle Kotlin DSL, at least for me, makes the experience of editing build scripts 10x better. Flutter developers should be able to harness this power :)

With this PR I'm aiming to make it possible to use `build.gradle.kts` instead of `build.gradle`, but there's more work to be done:
- update all documentation on the website to mention `build.gradle/build.gradle.kts` instead of only `build.gradle`
- update flutter tool's error messages to mention `build.gradle/build.gradle.kts` instead of only `build.gradle`
- add more tests for KTS buildscripts

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by christopherfujino** [comment]
@GaryQian could you review this one? I believe you landed a change related to Kotlin DSL?

**Comment by christopherfujino** [comment]
@reidbaker

**Comment by reidbaker** [comment]
I will try to give this a look next week. You are correct there is some additional work that needs to happen for use to bring this feature out at a production ready level and I am not sure when my team will be able to do the rest of the work. Also our testing in this area is not such that I can rely on automated tests alone to trust that this will work.


All that said I agree that many would rather work in kotlin gradle rather than learn groovy and I dont want to discourage this sort of contribution. 


In the mean time can you look at https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/features.dart 
Right now I am wavering between waiting to let this feature land when we can commit to have the support it deserves and guarding this behind a flag so that it can get incremental progress and some bake time.

**Comment by bartekpacia** [comment]
The feature flag sounds reasonable, though I think that if somebody has `build.gradle.kts` instead of `build.gradle`, then they've already willingly opted-in :)

**Comment by reidbaker** [comment]
Yes that is one way of looking at it. Another, and the one I am using is an android dev happens to use build.gradle.kts either because of a suggestion they find on the broader internet or because of previous android experience. An explicit opt in with the understanding that kotlin gradle support is experimental/under-development/baking or whatever phrase we decide to use helps align expectations better.

**Comment by reidbaker** [comment]
I am open to coming back to this discussion but for now I think i need to reject this cl. My team does not have the capacity to support adding a new build system. We know that build systems are not where app engineers want to spend their time and do not have the testing setup to ensure that this will keep working. 

Additionally at the current time there is partial support for other IDE's. https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:ide_support

Thank you for the contribution.

**Comment by bartekpacia** [comment]
@reidbaker Sorry for not responding for a prolonged time.

I agree with [your comment](https://github.com/flutter/flutter/pull/118067#issuecomment-1409148012) and am willing to add a feature flag for this.

**Pull request closed without merging**
