### PR TITLE
[integration_test] upgrade androidx test to 1.4.0

### PR DESCRIPTION
**Pull request by micaelcid**
I just finished migrating a project to Android 13 that runs `integration_test` with Firebase Test Lab. In this PR, I am changing the exact dependencies I needed to change to make our application able to run integration tests targeting Android 13. (the project is currently depending on my fork). 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Comment by goderbauer** [comment]
@reidbaker Can somebody from the Android team please check if this dependency bump makes sense? Thanks!

**Comment by reidbaker** [comment]
Version bump is ok with me adding @ricardoamador in case updates cause us to have to add something our CI. 
Not marking "Approved" on the cl until the integration tests pass and the build is up to date with master.

**Review by ricardoamador — APPROVED** [review]
LGTM

**Review by ricardoamador — CHANGES_REQUESTED** [review]
Can you update the branch and make sure all tests are passing?

**Comment by micaelcid** [comment]
Sure, @ricardoamador! I'll do as soon as I can. :) (Possibly today)

**Comment by micaelcid** [comment]
@ricardoamador taking a glimpse at the failed tests, does it look like something you'd know the cause? Otherwise, is there any available documentation I could use to debug the CI problems myself?

**Comment by ricardoamador** [comment]
@micaelcid If you look at the checks tab it will show you more details. Let me know if you are able to see the LUCI build information. 
From taking a look at one of the windows tests it looks like there is a dependency failure:
```
Execution failed for task ':integration_test:generateDebugRFile'.
 [        ] > Could not resolve all files for configuration ':integration_test:debugCompileClasspath'.
 [        ]    > Did not resolve 'net.sf.kxml:kxml2:2.3.0' which is part of the dependency lock state
 [        ]    > Resolved 'androidx.test.services:storage:1.4.0' which is not part of the dependency lock state
 [        ]    > Could not resolve androidx.test:runner:1.4.0.
 [        ]      Required by:
 [        ]          project :integration_test
 [        ]          project :integration_test > androidx.test:rules:1.4.0
 [        ]          project :integration_test > androidx.test.espresso:espresso-core:3.4.0
 [        ]       > Cannot find a version of 'androidx.test:runner' that satisfies the version constraints:
 [        ]            Dependency path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test:runner:1.4.0'
 [        ]            Constraint path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test:runner:{strictly 1.2.0}' because of the following reason: dependency was locked to version '1.2.0'
 [        ]            Dependency path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test:rules:1.4.0' --> 'androidx.test:runner:1.4.0'
 [        ]            Dependency path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test.espresso:espresso-core:3.4.0' --> 'androidx.test:runner:1.4.0'
 [        ]    > Could not resolve androidx.test:rules:1.4.0.
 [        ]      Required by:
 [        ]          project :integration_test
 [        ]       > Cannot find a version of 'androidx.test:rules' that satisfies the version constraints:
 [        ]            Dependency path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test:rules:1.4.0'
 [        ]            Constraint path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test:rules:{strictly 1.2.0}' because of the following reason: dependency was locked to version '1.2.0'
 [        ]    > Could not resolve androidx.test.espresso:espresso-core:3.4.0.
 [        ]      Required by:
 [        ]          project :integration_test
 [        ]       > Cannot find a version of 'androidx.test.espresso:espresso-core' that satisfies the version constraints:
 [        ]            Dependency path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test.espresso:espresso-core:3.4.0'
 [        ]            Constraint path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test.espresso:espresso-core:{strictly 3.2.0}' because of the following reason: dependency was locked to version '3.2.0'
 [        ]    > Could not resolve androidx.test.espresso:espresso-core:{strictly 3.2.0}.
 [        ]      Required by:
 [        ]          project :integration_test
 [        ]       > Cannot find a version of 'androidx.test.espresso:espresso-core' that satisfies the version constraints:
 [        ]            Dependency path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test.espresso:espresso-core:3.4.0'
 [        ]            Constraint path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test.espresso:espresso-core:{strictly 3.2.0}' because of the following reason: dependency was locked to version '3.2.0'
 [        ]    > Could not resolve androidx.test:runner:{strictly 1.2.0}.
 [        ]      Required by:
 [        ]          project :integration_test
 [        ]       > Cannot find a version of 'androidx.test:runner' that satisfies the version constraints:
 [        ]            Dependency path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test:runner:1.4.0'
 [        ]            Constraint path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test:runner:{strictly 1.2.0}' because of the following reason: dependency was locked to version '1.2.0'
 [        ]            Dependency path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test:rules:1.4.0' --> 'androidx.test:runner:1.4.0'
 [        ]            Dependency path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test.espresso:espresso-core:3.4.0' --> 'androidx.test:runner:1.4.0'
 [        ]    > Could not resolve androidx.test:rules:{strictly 1.2.0}.
 [        ]      Required by:
 [        ]          project :integration_test
 [        ]       > Cannot find a version of 'androidx.test:rules' that satisfies the version constraints:
 [        ]            Dependency path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test:rules:1.4.0'
 [        ]            Constraint path 'com.example.integration_test:integration_test:1.0-SNAPSHOT' --> 'androidx.test:rules:{strictly 1.2.0}' because of the following reason: dependency was locked to version '1.2.0'
 [        ] * Try:
 ```

**Comment by micaelcid** [comment]
I can @ricardoamador, except for `Linux firebase_release_smoke_test` step that returns only a one-line message:
image

**Comment by ricardoamador** [comment]
Ah okay. You need to follow the link at the botton of that screen. The one that says 'View more details on flutter-dashboard.' I know it kind of small and can easily be missed. That error is the same though. You can see it here:
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8787738512559017217/+/u/test_execution/Build_appbundle/stdout

**Comment by micaelcid** [comment]
Thanks again, I'm totally newbie to open sourcing, but I'll work my way around :)

**Comment by ricardoamador** [comment]
Sure no problem!

**Comment by micaelcid** [comment]
Hey, @ricardoamador. 

I'm back with good news! I just finished fixing the integration tests 🚀 

Can you please take a look at the changes and review them again?

**Review by ricardoamador — APPROVED** [review]
LGTM! Nice work!

**Comment by ricardoamador** [comment]
You can submit this by adding the 'autosubmit' label to this pull request.

**Comment by micaelcid** [comment]
I don't have contributor permission for adding labels 🤔

**Review by reidbaker — APPROVED** [review]

**Comment by micaelcid** [comment]
Hey, @reidbaker. Thanks for adding the label. It seems the pipeline step failed due to some flakiness. Could you try again, please?

**Pull request merged**
