### PR TITLE
Add tests for scaffold.of.#.dart API examples.

### PR DESCRIPTION
**Pull request by ksokolovskyi**
This PR contributes to https://github.com/flutter/flutter/issues/130459

### Description
- Adds tests for `examples/api/lib/material/scaffold/scaffold.of.0.dart`
- Adds tests for `examples/api/lib/material/scaffold/scaffold.of.1.dart`

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

### CODE REVIEW

**Review by bleroux — COMMENTED** [review]
Thanks again for your valuable additions!

For consistency with other example tests and also with framework ones, please apply the following minor changes:
- remove the group.
- format all `testWidgets` to fit on one line (line 12 is ok), do it even when the test description is longer (for instance line 21). In framework test, this is done for readability. If the test description is very long tes, it can be split into several lines (but finding a shorter description is generally better).

It would be great to do the same for your similar open PRs, thanks!

**Comment by ksokolovskyi** [comment]
@bleroux thanks a lot for the suggestions!
I have applied them to all my open PRs.

**Review by bleroux — APPROVED** [review]
LGTM!

**Comment by ksokolovskyi** [comment]
@TahaTesser could you please look at this PR when you have time?

**Review by TahaTesser — APPROVED** [review]
LGTM

**Comment by ksokolovskyi** [comment]
@bleroux @TahaTesser thanks a lot for the review and merge!

**Pull request merged**
