### PR TITLE
mark windows build tests non-bringup

### PR DESCRIPTION
**Pull request by christopherfujino**
This is a follow-up to https://github.com/flutter/flutter/commit/aa0a1a7ae1467f54e962a5616e5bf4385fbf1daf. I was forced to mark these targets bringup in that PR because the targets were technically new (since each name changed 3 -> 4), so this is marking them non-bringup.

### CODE REVIEW

**Comment by christopherfujino** [comment]
I'm waiting for the ci_yaml roller to generate the configs for these builders, but I don't see even a scheduled build: https://ci.chromium.org/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller

**Comment by christopherfujino** [comment]
And per the [milo page](https://ci.chromium.org/p/flutter/builders/prod/Linux%20ci_yaml%20flutter%20roller) there are 57 bots idle?

Screenshot from 2023-05-17 16-00-13

@ricardoamador do you know if something is wrong here?

**Comment by ricardoamador** [comment]
Taking a look.

**Comment by christopherfujino** [comment]
> Taking a look.

ahh, once you started looking two started.

**Comment by ricardoamador** [comment]
> ahh, once you started looking two started.

Speak of the devil...

**Review by ricardoamador — APPROVED** [review]
LGTM

**Pull request merged**
