### PR TITLE
Add animation curve slowMiddle

### LINKED ISSUE #26743: Add an animation curve that is straight in the middle
It would be nice to have a curve that starts going up fast, then flattens out, is flat at 0.5 for most of the interval, then speeds up and goes to 1.0 near the end in a mirror of what it does at the start. Sort of the same as inOut curves, but with the gradient starting at >1 instead of <1. An inverse S shape on its side.

cc @marcoms in case you're interested in doing that. :-)

### PR DESCRIPTION
**Pull request by dkwingsmt**
## Description

- Added a new animation curve ~~`fastInFastOut`~~`slowMiddle` per requested in https://github.com/flutter/flutter/issues/26743. It starts quickly, flats out when near the center, and ends quickly.
  - ~~It's named so because we also have fastOutSlowIn. Another option is `stallCenter`, which is a new format but maybe clearer.~~ See discussion below
  - Currently it's `Cubic(0.15, 0.85, 0.85, 0.15)`, as shown below.

  - I intentionally chose slower slopes at the start and end because otherwise the start and end animation will be barely visible.
- Fixed a few typos in doc.
- TODO:
  - [x] Add assets-for-api-docs
- Subject to discussion:
  - [x] Name
  - [ ] Tweek numbers

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/26743
- Assets https://github.com/flutter/assets-for-api-docs/pull/57

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by gspencergoog** [comment]
Hmm. I like "stallCenter", "stallMiddle", "slowCenter" or maybe "slowMiddle" better as a name.  "fastInFastOut" sounds like it's just fast all the time.

You'll need to create the assets-for-api-docs content before you commit this, since otherwise the link will be broken in the API docs. You'll want to add your new curve [here](https://github.com/flutter/assets-for-api-docs/blob/686d10a85d65d3c698e6e9f1ac804c61af8f6615/packages/diagrams/lib/src/curve.dart#L429), and then run the asset generator with your this PR to generate the curve animation.

Thank you for fixing the extra "the"s in the docs!

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by dkwingsmt** [comment]
@gspencergoog Thanks! I'll submit a PR for assets after we settled the name and numbers here.

**Comment by gspencergoog** [comment]
Actually, I was thinking about it, and I think it should be `slowMiddle`, since "center" kind of implies something geometric, and although the curve itself it geometric, an animation has a "middle" (like a music composition), more than it has a "center" (like a geometric object).

**Comment by dkwingsmt** [comment]
@gspencergoog Sure. What about the numbers, are they ok?

**Comment by dkwingsmt** [comment]
Also it seems I need to merge this before the asset PR, otherwise the CI for the asset PR would fail.

**Comment by gspencergoog** [comment]
The numbers seem fine.

**Pull request merged**
