### PR TITLE
Remove unused flag `--target-platform` from `flutter run`

### PR DESCRIPTION
**Pull request by blasten**
## Description

The target platform is inferred from the device or simulator, so the `--target-platform` doesn't change anything.

## Tests

I added the following tests:

n/a

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by dnfield** [comment]
Does this mean `flutter run` no longer supports running a 32 bit APK on a 64 bit device?

I guess that's supposed to not work soon anyway, right?  Or at least be strongly discouraged?  And someone could just build the APK and manually install it.

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by blasten** [comment]
Correct. If they need to build an APK that doesn't match the device arch, they can always build it using `build apk`

**Comment by ymback** [comment]
So I have a situation, flutter cannot add libflutter.so to armeabi-v7a automatically when using studio without --target-platform=android-arm because it declared that my Phone is x64, but some libraries don't supply arm64 so files, so without --target-platform=android-arm, arm64 only have libflutter.so, app crash.
So is there a solution to fix my situation.

**Comment by jonahwilliams** [comment]
cc @blasten

**Comment by blasten** [comment]
@ymback Just to confirm, are you using 3P libraries that don’t provide an arm64 equivalent?

**Comment by ymback** [comment]
Yes, 3P libraries only provice armeabi-v7a.
I finally found this commit https://github.com/flutter/flutter/commit/8627ff433b4658195e66b9c0034902116f53d580#diff-e2bd341219c8e758eb91659fe88dbeb5R463, in gradle.dart file line 463, it sets the target-platform to android-arm64 forcely, ignore my argument `--target-platform android-arm` after I readd the option `target-platform` which you removed and recreate flutter_tools.snapshot file.
And I tried to force set `-Ptarget-platform=android-arm` in gradle.dart, after recreate the flutter_tools.snapshot file, everything works normally, no crash.

**Comment by ymback** [comment]
I think the gradle.dart file should check if it's from flutter run, and use different plan to generate target-platform.

**Comment by jason-simmons** [comment]
If you need to build a 32-bit binary and run it on a 64-bit device, then try using the `flutter run --use-application-binary` flag to specify an APK built for a 32-bit target:

```
flutter build apk --debug --target-platform=android-arm
flutter run --use-application-binary=build/app/outputs/apk/debug/app-debug.apk
```

**Comment by ymback** [comment]
> If you need to build a 32-bit binary and run it on a 64-bit device, then try using the `flutter run --use-application-binary` flag to specify an APK built for a 32-bit target:
> 
> ```
> flutter build apk --debug --target-platform=android-arm
> flutter run --use-application-binary=build/app/outputs/apk/debug/app-debug.apk
> ```

Thouth I don't think it's a good solution cause I have to run in command first, but it's useful enough, thank you, I'll do like this.

**Comment by zhihesoft** [comment]
remove --target-platform flag makes debug in vscode very inconvenient while with 32-bit 3P lib.

**Comment by shingohu** [comment]
the same situation

> So I have a situation, flutter cannot add libflutter.so to armeabi-v7a automatically when using studio without --target-platform=android-arm because it declared that my Phone is x64, but some libraries don't supply arm64 so files, so without --target-platform=android-arm, arm64 only have libflutter.so, app crash.
> So is there a solution to fix my situation.

**Comment by buaashuai** [comment]
> Yes, 3P libraries only provice armeabi-v7a.
> I finally found this commit [8627ff4#diff-e2bd341219c8e758eb91659fe88dbeb5R463](https://github.com/flutter/flutter/commit/8627ff433b4658195e66b9c0034902116f53d580#diff-e2bd341219c8e758eb91659fe88dbeb5R463), in gradle.dart file line 463, it sets the target-platform to android-arm64 forcely, ignore my argument `--target-platform android-arm` after I readd the option `target-platform` which you removed and recreate flutter_tools.snapshot file.
> And I tried to force set `-Ptarget-platform=android-arm` in gradle.dart, after recreate the flutter_tools.snapshot file, everything works fine, no crash.

this method really me

**Comment by buaashuai** [comment]
1、edit the flutter/packages/flutter_tools/lib/src/android/gradle.dart file and set -Ptarget-platform=android-arm
2、delete flutter/bin/cache/flutter_tools.snapshot 

Then your Android studio can run armeabi-v7a apk on the 64-bit developing device.

**Comment by CarGuo** [comment]
remove --target-platform flag makes debug very inconvenient while with 32-bit 3P lib.

**Comment by hurshi** [comment]
Here is a solution **for debug mode**: puts the libflutter.so into jniLibs: 
image
and you can happy `flutter run`, or click "Run" in AndroidStudio

**Comment by chenenyu** [comment]
Plz restore this flag.

**Comment by liugangnhm** [comment]
most useless pr

**Pull request merged**
