### PR TITLE
Revert "Fix hot restart flake"

### PR DESCRIPTION
**Pull request by christopherfujino**
Reverts flutter/flutter#122776 because this test is sometimes hanging for example: https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20web_tool_tests_1_2/5036/overview

### CODE REVIEW

**Review by annagrin — APPROVED** [review]
LGTM!

**Comment by christopherfujino** [comment]
Currently blocking tree: https://ci.chromium.org/p/flutter/builders/prod/Windows%20web_tool_tests_1_2/2571

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Review by loic-sharma — APPROVED** [review]

**Comment by annagrin** [comment]
@christopherfujino doe we have a timeout somewhere for one test file not to exceed 30 minutes? I think I added too many tests:) Will split them up and try to reland.

**Comment by christopherfujino** [comment]
> 32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Ahh, you're right, looks like when this passes it's just under the timeout.

**Comment by christopherfujino** [comment]
> @christopherfujino do we have a timeout somewhere for one test file not to exceed 30 minutes? I think I added too many tests:) Will split them up and try to re-land after this revert is in.

Ahh you're right, looks like even when this passes it's just under the timeout.

**Pull request merged**
