### PR TITLE
Improve StrokeAlign on RoundedRectangleBorder

### LINKED ISSUE #106362: [Idea] Make center/outside stroke more consistent.
> **Note**
> This is specific to RoundedRectangleBorder. BoxBorder already does this via isUniform.

A few weeks ago I opened this issue (https://github.com/flutter/flutter/issues/104201) because I thought it felt better. However, today I was playing with Figma and, not that Flutter has to follow it, Figma has the same StrokeAlign.start as Flutter, which is great. My issue then is closed.

... Except...

When I made the PR for StrokeAlign.center and outside, I made the rectangle rounder (check screenshot) because it is impossible to lerp from 0-1 otherwise. Figma doesn't do this. So... should we have the same behavior of StrokeAlign.start for center and outside, which is the same as Figma, but doesn't lerp 0-1 perfectly (check video)? It is a two or three LOC change and it hasn't landed on stable yet, so it is not a breaking change.

Pro: consistency, same behavior as start, same behavior as Figma.
Cons: lerp from 0.0 to 1.0 will jump. 

image

### PR DESCRIPTION
**Pull request by bernaferrari**
> **Note**
> This is specific to RoundedRectangleBorder.
> BoxBorder already does this via `isUniform`.

Fix: https://github.com/flutter/flutter/issues/106362
Related: https://github.com/flutter/flutter/issues/104201

When I added `StrokeAlign.center` and `StrokeAlign.outside`, I 'fixed' lerp from 0 to 1 by kind of accidentally making the behavior different than StrokeAlign.inside and Figma. By sacrificing what happens between BorderRadius.zero and BorderRadius.circular(1), we can get the same behavior (Figma also doesn't solve it, see video).

image

https://user-images.githubusercontent.com/351125/174895032-90a70e90-7e9e-4279-9eaa-23e34560e561.mov
<details>
  <summary>Click to see the sample</summary>

 ```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData.dark(),
      home: const Scaffold(body: MyHomePage()),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

List<Widget> spaceRow(double gap, Iterable<Widget> children) => children
    .expand((item) sync* {
      yield SizedBox(width: gap);
      yield item;
    })
    .skip(1)
    .toList();

List<Widget> spaceColumn(double gap, Iterable<Widget> children) => children
    .expand((item) sync* {
      yield SizedBox(height: gap);
      yield item;
    })
    .skip(1)
    .toList();

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    const double width = 40;
    final Color borderColor = Colors.green.withOpacity(0.3);
    const debugStrokeAlign = StrokeAlign.outside;

    final circleLerp = CircleBorder(
      side: BorderSide(
        color: Colors.red.withOpacity(0.5),
        width: 15,
        strokeAlign: debugStrokeAlign,
      ),
    );

    StadiumBorder stadiumLerp([StrokeAlign strokeAlign = debugStrokeAlign]) =>
        StadiumBorder(
          side: BorderSide(
            color: Colors.red.withOpacity(0.5),
            width: 15,
            strokeAlign: strokeAlign,
          ),
        );

    RoundedRectangleBorder roundedRectangleLerp(
            [StrokeAlign strokeAlign = debugStrokeAlign]) =>
        RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(0),
          side: BorderSide(
            color: Colors.red.withOpacity(0.5),
            width: 15,
            strokeAlign: strokeAlign,
          ),
        );

    ShapeBorder stadiumToCircleLerp(double t) =>
        stadiumLerp().lerpTo(circleLerp, t)!;

    ShapeBorder stadiumToRoundedLerp(double t, StrokeAlign strokeAlign) =>
        stadiumLerp(strokeAlign).lerpTo(roundedRectangleLerp(strokeAlign), t)!;

    ShapeBorder roundedToCircleLerp(double t) =>
        roundedRectangleLerp().lerpTo(circleLerp, t)!;

    return ListView(
      padding: const EdgeInsets.all(50),
      children: [
        const Text(
          "Material Borders",
          textAlign: TextAlign.center,
        ),
        SizedBox(height: 16),
        Row(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: spaceRow(
            width * 2,
            [
              for (StrokeAlign align in StrokeAlign.values)
                Column(
                  children: spaceColumn(
                    16,
                    [
                      Text(align.name),
                      const SizedBox(height: 16),
                      const SizedBox(height: 16),
                      Material(
                        color: Colors.black,
                        child: SizedBox(
                          width: 100,
                          height: 40,
                          child: Center(
                            child: Container(
                              width: 100,
                              height: 2,
                              color: Colors.red,
                            ),
                          ),
                        ),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(10),
                          side: BorderSide(
                            color: borderColor,
                            width: 20,
                            strokeAlign: align,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
            ],
          ),
        ),
        const SizedBox(height: 16),
        const Text(
          "Lerp StadiumBorder -> RoundedRectangleBorder (CENTER)",
          textAlign: TextAlign.center,
        ),
        const SizedBox(height: 16),
        Row(
          children: spaceRow(32, [
            Container(
              width: 100,
              height: 60,
              decoration: ShapeDecoration(
                color: Colors.brown,
                shape: stadiumToRoundedLerp(0.0, StrokeAlign.center),
              ),
              child: Text('lerp 0.0'),
            ),
            Container(
              width: 100,
              height: 60,
              decoration: ShapeDecoration(
                color: Colors.blueAccent,
                shape: stadiumToRoundedLerp(0.99, StrokeAlign.center),
              ),
              child: Text('lerp 0.99'),
            ),
            Container(
              width: 100,
              height: 60,
              decoration: ShapeDecoration(
                color: Colors.orangeAccent,
                shape: stadiumToRoundedLerp(1.0, StrokeAlign.center),
              ),
              child: Text('lerp 1.0'),
            ),
            Container(
              width: 100,
              height: 60,
              decoration: ShapeDecoration(
                color: Colors.black,
                shape: roundedRectangleLerp(StrokeAlign.center),
              ),
              child: Text('final'),
            ),
          ]),
        ),
        const SizedBox(height: 32),
        const Text(
          "Lerp StadiumBorder -> RoundedRectangleBorder (OUTSIDE)",
          textAlign: TextAlign.center,
        ),
        const SizedBox(height: 16),
        Row(
          children: spaceRow(32, [
            Container(
              width: 100,
              height: 60,
              decoration: ShapeDecoration(
                color: Colors.brown,
                shape: stadiumToRoundedLerp(0.0, StrokeAlign.outside),
              ),
              child: Text('lerp 0.0'),
            ),
            Container(
              width: 100,
              height: 60,
              decoration: ShapeDecoration(
                color: Colors.blueAccent,
                shape: stadiumToRoundedLerp(0.99, StrokeAlign.outside),
              ),
              child: Text('lerp 0.99'),
            ),
            Container(
              width: 100,
              height: 60,
              decoration: ShapeDecoration(
                color: Colors.orangeAccent,
                shape: stadiumToRoundedLerp(1.0, StrokeAlign.outside),
              ),
              child: Text('lerp 1.0'),
            ),
            Container(
              width: 100,
              height: 60,
              decoration: ShapeDecoration(
                color: Colors.black,
                shape: roundedRectangleLerp(),
              ),
              child: Text('final'),
            ),
          ]),
        ),
        const SizedBox(height: 16),
        const Text(
          "Lerp RoundedRectangleBorder -> CircleBorder",
          textAlign: TextAlign.center,
        ),
        const SizedBox(height: 16),
        Row(
          children: spaceRow(32, [
            Container(
              width: 100,
              height: 100,
              decoration: ShapeDecoration(
                color: Colors.blue,
                shape: roundedToCircleLerp(0.0),
              ),
              child: Text('lerp 0.0'),
            ),
            Container(
              width: 100,
              height: 100,
              decoration: ShapeDecoration(
                color: Colors.yellow.withOpacity(0.5),
                shape: roundedToCircleLerp(0.01),
              ),
              child: Text('lerp 0.01'),
            ),
            Container(
              width: 100,
              height: 100,
              decoration: ShapeDecoration(
                color: Colors.purple,
                shape: roundedToCircleLerp(1.0),
              ),
              child: Text('lerp 1.0'),
            ),
            Container(
              width: 100,
              height: 100,
              decoration: ShapeDecoration(
                shape: circleLerp,
              ),
              child: Text('final'),
            ),
          ]),
        ),
        const SizedBox(height: 48),
        const Text(
          "Transitions",
          textAlign: TextAlign.center,
        ),
        const SizedBox(height: 20),
        const AnimatedTransitions(),
        const SizedBox(height: 20),
        const Text(
          "Container",
          textAlign: TextAlign.center,
        ),
        const SizedBox(height: 40),
        Row(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: spaceRow(
            width * 2,
            [
              for (StrokeAlign align in StrokeAlign.values)
                Container(
                  width: 100,
                  height: 100,
                  decoration: BoxDecoration(
                    color: Colors.red,
                    borderRadius: BorderRadius.circular(20),
                    border: Border.all(
                      color: Colors.black.withOpacity(0.75),
                      width: width,
                      strokeAlign: align,
                    ),
                  ),
                  child: Center(
                      child: Container(
                          width: 100, height: 100, color: Colors.blue)),
                ),
            ],
          ),
        ),
        const SizedBox(height: width * 2),
        Row(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: spaceRow(
            width * 2,
            [
              for (StrokeAlign align in StrokeAlign.values)
                Container(
                  width: 100,
                  height: 100,
                  decoration: BoxDecoration(
                    color: Colors.green,
                    border: Border.all(
                      color: Colors.black.withOpacity(0.75),
                      width: width,
                      strokeAlign: align,
                    ),
                  ),
                ),
            ],
          ),
        ),
        const SizedBox(height: width * 2),
        Row(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: spaceRow(
            width * 2,
            [
              for (StrokeAlign align in StrokeAlign.values)
                Container(
                  width: 100,
                  height: 100,
                  decoration: BoxDecoration(
                    color: Colors.blue,
                    shape: BoxShape.circle,
                    border: Border.all(
                      color: Colors.black.withOpacity(0.75),
                      width: width,
                      strokeAlign: align,
                    ),
                  ),
                ),
            ],
          ),
        ),
      ],
    );
  }
}

class AnimatedTransitions extends StatefulWidget {
  const AnimatedTransitions({Key? key}) : super(key: key);

  @override
  _AnimatedTransitionsState createState() => _AnimatedTransitionsState();
}

class _AnimatedTransitionsState extends State<AnimatedTransitions>
    with TickerProviderStateMixin {
  late AnimationController _controller;
  late Tween<double> tween;

  @override
  initState() {
    super.initState();
    _controller = AnimationController(
      duration: const Duration(seconds: 4),
      vsync: this,
    )..repeat();
  }

  @override
  dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
        animation:
            CurvedAnimation(parent: _controller, curve: Curves.slowMiddle),
        builder: (context, child) {
          return Center(
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Material(
                  color: Colors.black,
                  child: SizedBox(
                    width: 100,
                    height: 40,
                    child: Center(
                      child: Container(
                        width: 100,
                        height: 2,
                        color: Colors.red,
                      ),
                    ),
                  ),
                  shape: _controller.value > 0.5
                      ? RoundedRectangleBorder(
                          side: BorderSide(
                            color: Colors.red.withOpacity(0.5),
                            width: 15,
                            strokeAlign: StrokeAlign.center,
                          ),
                          borderRadius: BorderRadius.circular(0),
                        )
                      : CircleBorder(
                          side: BorderSide(
                            color: Colors.red.withOpacity(0.5),
                            width: 15,
                            strokeAlign: StrokeAlign.center,
                          ),
                        ),
                ),
                const SizedBox(width: 20),
                Material(
                  color: Colors.black,
                  child: SizedBox(
                    width: 100,
                    height: 40,
                    child: Center(
                      child: Container(
                        width: 100,
                        height: 2,
                        color: Colors.red,
                      ),
                    ),
                  ),
                  shape: _controller.value > 0.5
                      ? RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(10),
                          side: BorderSide(
                            color: Colors.red.withOpacity(0.5),
                            width: 15,
                            strokeAlign: StrokeAlign.center,
                          ),
                        )
                      : RoundedRectangleBorder(
                          side: BorderSide(
                            color: Colors.red.withOpacity(0.5),
                            width: 15,
                            strokeAlign: StrokeAlign.center,
                          ),
                        ),
                ),
                const SizedBox(width: 20),
                Material(
                  color: Colors.black,
                  child: SizedBox(
                    width: 100,
                    height: 40,
                    child: Center(
                      child: Container(
                        width: 100,
                        height: 2,
                        color: Colors.red,
                      ),
                    ),
                  ),
                  shape: _controller.value > 0.5
                      ? StadiumBorder(
                          side: BorderSide(
                            color: Colors.red.withOpacity(0.5),
                            width: 15,
                            strokeAlign: StrokeAlign.outside,
                          ),
                        )
                      : RoundedRectangleBorder(
                          side: BorderSide(
                            color: Colors.red.withOpacity(0.5),
                            width: 15,
                            strokeAlign: StrokeAlign.outside,
                          ),
                        ),
                ),
              ],
            ),
          );
        });
  }
}

class Lerpness extends StatefulWidget {
  const Lerpness({Key? key}) : super(key: key);

  @override
  State<Lerpness> createState() => _LerpnessState();
}

class _LerpnessState extends State<Lerpness> {
  bool direction = true;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        setState(() {
          direction = !direction;
        });
      },
      child: AnimatedContainer(
        width: 100,
        height: 100,
        decoration: BoxDecoration(
          color: Colors.red,
          borderRadius: BorderRadius.circular(20),
          border: Border.all(
            color: Colors.black.withOpacity(0.75),
            width: direction ? 20 : 10,
            strokeAlign: direction ? StrokeAlign.inside : StrokeAlign.outside,
          ),
        ),
        duration: const Duration(seconds: 2),
      ),
    );
  }
}
```

</details>

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hi @bernaferrari! Looking at the associated links, is this the breaking change approach?
Also, I noticed you mentioned BoxBorder already does this with `isUniform`, can this follow the same pattern then?

cc @gspencergoog who had some ideas about this in the associated issues.

**Comment by Piinks** [comment]
> I 'fixed' lerp from 0 to 1

It sounds like there was a previous PR you landed related to this, can you provide a link to it? If it does not actually fix the issue as intended, we should revert it instead of trying to fix further on top of it.

**Comment by bernaferrari** [comment]
@Piinks uh, oh.
> is this the breaking change approach? 

Depends. I want to change the behavior of StrokeAlign that is still not on master. And it don't break any test. It would break a golden made in the past weeks using the new StrokeAlign, yes. But there is none.

> previous PR

The previous PR is the whole StrokeAlign feature. By solving lerp, I accidentally made an undesirable behavior.
https://github.com/flutter/flutter/pull/102112

> isUniform

That works because it doesn't care about lerp (0-1). This PR is doing exactly that.

From the discussion, @gspencergoog likes the old "wrong" way, but @HansMuller  defends what this PR is doing. We could have a middle solution (as I proposed in the discussion), but it seems to me this PR is what we want right now.

**Review by Piinks — COMMENTED** [review]
> Note: there is a single place I believe I could optimize (if cornerRadius == 0 drawRect else drawRRect) for stroke inside, I'm not doing that to avoid breaking two tests that expect drawRRect. I'm trying my best to be safe and not breaking.

Does this mean this has inconsistent behavior? I think it should work the same for all values. Can you clarify?


> > isUniform

> ... This PR is doing exactly that. 

I don't see `isUniform` in this PR. Is there a reason why it does not use the same pattern?

**Comment by bernaferrari** [comment]
> Does this mean this has inconsistent behavior?

No, sorry. Same behavior, no visual change (just like, if box is round, draw a square instead of a box with circleRadius = 0. No visual change, can wait for another day). I shouldn't have mentioned it.

> isUniform
BoxDecoration already does this. Check here: https://github.com/flutter/flutter/blob/2cbcaaddf3a56c528f4d87f2d96eb80db967f768/packages/flutter/lib/src/painting/box_decoration.dart#L434
I'm bringing the same if/else to RoundedRectangleBorder, that's what the PR is about.

**Comment by bernaferrari** [comment]
I'm going to close this. Did I give up? No. I have a new PR that is brutal and includes all of these changes there: https://github.com/flutter/flutter/pull/108339

**Pull request closed without merging**
