### PR TITLE
Add OutlinedBorder class

### PR DESCRIPTION
**Pull request by HansMuller**
Defined a new `OutlinedBorder` abstract class in between ShapeBorder and the existing concrete subclasses like RoundedRectangleBorder. OutlinedBorder adds a BorderSide property and a `copyWith` method with the usual semantics. That makes it possible to combine an OutlinedBorder that defines a component's shape, with a BorderSide that defines how the border outline is to appear.

For example: 
```dart
RoundedRectangleBorder().copyWith(
  side: BorderSide(color: Colors.green, width: 3),
)
```

BeveledRectangleBorder, CircleBorder, ContinuousRectangleBorder, RoundedRectangleBorder, and StadiumBorder are now OutlinedBorders.

This PR does not update the existing InputBorder class to be an OutlinedBorder. InputBorder's BorderSide property and constructor parameter is called "borderSide"; other than that, the two classes are compatible. A future PR could make InputBorder an OutlinedBorder however, that would be a breaking change.

### CODE REVIEW

**Comment by Hixie** [comment]
I don't think we should do this. There's no reason why a border needs to support a BorderSide. It could have many, it could have none. We could have a subclass of ShapeBorder, ShapeBorderWithSide or something, that the others inherit from if we want to do this, but fundamentally the core type shouldn't have to know about sides IMHO.

Having the default not do anything, in particular, seems like a confusing API.

That said, what's the use case?

**Comment by HansMuller** [comment]
Enabling one to specify a button's shape separately from the outline that decorates its border.  An app theme needs to be able to specify the shape of buttons (or other components) without disturbing the outline the buttons decorate their border with. Similarly, a theme should be able to specify a button's border decoration, independently of its shape.

**Comment by Hixie** [comment]
We could have an OutlineableShape class that is between ShapeBorder and those subclasses that have a side, and the button theming could require that it be used, while allowing other widgets to use the regular ShapeBorder. We have precedent for that, e. g. IIRC the text fields require a particular shape subclass.

**Comment by HansMuller** [comment]
Yes, that sounds reasonable although "outlineable" stretches our common language.  It's a shame that we can't have Shape and BorderedShape but those ships have sailed (and "BorderedShapeBorder" is terrible).  Maybe OutlinedShape?

**Review by Hixie — APPROVED** [review]
This is great.
LGTM

**Pull request merged**
