### PR TITLE
Fix Flutter Gallery to use title case

### PR DESCRIPTION
**Pull request by eseidelGoogle**
@HansMuller

### CODE REVIEW

**Comment by chinmaygarde** [comment]
lgtm

**Comment by HansMuller** [comment]
I had used "sentence case" because:

https://www.google.com/design/spec/style/writing.html#writing-capitalization-punctuation
> Use sentence-style caps for all titles, headings, labels, menu items – any place where you might be tempted to use “Title-Style Caps.”

**Comment by eseidelGoogle** [comment]
"Google On" "Google Cast" "Our Groceries" "Arts & Culture" "Weather Timeline" are all on my homescreen and all in Title Case.  I suspect the spec may not be following the defacto convention.

**Comment by HansMuller** [comment]
That's one way of looking at it, yes.

**Pull request merged**
