### PR TITLE
Made insetPadding configurable for Date Picker Dialog

### PR DESCRIPTION
**Pull request by sarbagyastha**
This PR adds following properties to the **DatePickerDialog**:
- `insetPadding`

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by ahyangnb** [comment]
favor

**Comment by sarbagyastha** [comment]
CC @MitchellGoodwin

**Review by MitchellGoodwin — COMMENTED** [review]
Code LGTM. But I'm wondering about the use cases of these. The date values are exposed by the future returned by the dialog being popped off the screen. If another callback exposes the date, then there are conflicting ways to get those values from the widget. I'm worried that exposing these callbacks will create anti-patterns where it's easier to introduce bugs.

**Review by justinmc — COMMENTED** [review]
I would split out the insetPadding change from the onStart/EndDateChanged change. It's totally independent, right? I think the insetPadding change looks like it's probably easy to get landed on its own.

I'm also curious about how the new onStart/EndDateChanged parameters will be used. Is there a case where it's not possible to use the Future to get the selected date range?

**Review by MitchellGoodwin — CHANGES_REQUESTED** [review]
I think before merging we need a clear use case for this. Because this is going to introduce a different way to get the date value along with what we had before, it feels off. It may be possible that the problem this is trying to fix could be solved by something else.

**Comment by sarbagyastha** [comment]
> I think before merging we need a clear use case for this. Because this is going to introduce a different way to get the date value along with what we had before, it feels off. It may be possible that the problem this is trying to fix could be solved by something else.

Yeah, may be instead of adding the callbacks to the dialog, we can expose a new widget that composes of the Calendar and Input date picker, and have the callbacks in it. Then, use the widget to build `DatePickerDialog` without exposing the callbacks.

**Comment by sarbagyastha** [comment]
> I would split out the insetPadding change from the onStart/EndDateChanged change. It's totally independent, right? I think the insetPadding change looks like it's probably easy to get landed on its own.

For now, I removed the callbacks from the PR.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM! Thank you for the PR.

**Review by justinmc — APPROVED** [review]
LGTM :+1: Thanks for the PR!

**Comment by justinmc** [comment]
Ah I missed the Google testing failure. @sarbagyastha can you push a merge commit? I see no failures internally.

**Pull request merged**
