### PR TITLE
Fix `flutter doctor` failure if flutter is installed in a path with exclamation mark

### LINKED ISSUE #26571: Windows failure if install directory has a "!" in it
I set up flutter and running any flutter command, including `flutter doctor` results in 

```
Error: The Flutter directory is not a clone of the GitHub project.
       The flutter tool requires Git in order to operate properly;
       to set up Flutter, run the following command:
       git clone -b beta https://github.com/flutter/flutter.git
```
Git is installed and running `git --version` returns `git version 2.20.1.windows.1`. 

I've tried installing Flutter through the ZIP on [flutter.io](https://flutter.io), as well as cloning it through both 
`git clone -b beta https://github.com/flutter/flutter.git`
and
`git clone -b stable https://github.com/flutter/flutter.git`,

restarted my laptop after each and still get the same error after running `flutter doctor`. 

I've never had this happen to me before, and would greatly appreciate any help. Thank you

### PR DESCRIPTION
**Pull request by kangwang1988**
Fix a problem when running `flutter doctor` if flutter is installed in a path with exclamation mark in it.
This would fix: https://github.com/flutter/flutter/issues/26571

### CODE REVIEW

**Comment by goderbauer** [comment]
Looks like cirrus is not happy with this change.

**Comment by kangwang1988** [comment]
@goderbauer 
I don't understand the intention for this failed test. It seems to be designed to fail, isn't it?
screen shot 2019-02-15 at 12 14 47 am
screen shot 2019-02-15 at 12 14 21 am

**Comment by goderbauer** [comment]
Yes, the dart test is expected to fail and in [1] we have logic to ensure that the flutter tool returns a non-zero exit code for that failure (see also the error message in your screenshot). However, with this change, an exit code of zero is returned indicating that the tests passed even though it should have failed.

[1] https://github.com/flutter/flutter/blob/master/dev/bots/test.dart#L76

**Comment by kangwang1988** [comment]
> Yes, the dart test is expected to fail and in [1] we have logic to ensure that the flutter tool returns a non-zero exit code for that failure (see also the error message in your screenshot). However, with this change, an exit code of zero is returned indicating that the tests passed even though it should have failed.
> 
> [1] https://github.com/flutter/flutter/blob/master/dev/bots/test.dart#L76


Got it, I will check the logic. Thanks.

**Comment by goderbauer** [comment]
Switching from `%` to `!` actually changes the semantics of the statement slightly (see https://ss64.com/nt/delayedexpansion.html). Seems like a strange way to fix this. Is there a way to just escape the problematic character in the string?

**Comment by zanderso** [comment]
Hi @kangwang1988, this PR looks inactive, so I'm going to close it. If you'd like to pick it back up again, please feel free to re-open or start a new one. Thanks!

**Pull request closed without merging**
