### PR TITLE
Modified TextFormField to retain value when scrolled

### PR DESCRIPTION
**Pull request by trauschdavis**
Modified TextFormField to retain value if component is scrolled off the screen

Removed the first assert because it is taken care of when setting the initialValue field

Added if check to pull value from controller into widget if the controller has value

Fixes Issues: #11500, #15484, #14104, #16028

### CODE REVIEW

**Comment by trauschdavis** [comment]
I signed it!

**Comment by HansMuller** [comment]
This change would reset the text field to its initialValue each time it was rebuilt with an empty text controller. I don't think that's what you want.

**Comment by HansMuller** [comment]
This isn't right. If a TextEditingController is provided then its `text` value is the text field's initial value, even if it the controller's text is `""` (empty).

Appreciate your looking into this! In general, changes like this will need regression tests for the bugs the PR fixes.

**Comment by trauschdavis** [comment]
@HansMuller I've made it so that the value gets set from the controller if it exists. Also, I've added some tests around setting the initial value.

This still doesn't fix the issue where the text form field loses its value when scrolled off the screen when a controller isn't present.

**Pull request closed without merging**
