### PR TITLE
Add RichText debugFillProperties TestCase

### PR DESCRIPTION
**Pull request by feHouyushan**
## Description

Add RichText debugFillProperties test case, Enrich test case coverage.

## Tests

I added the following tests:

test/widgets/rich_text_test.dart

### CODE REVIEW

**Comment by feHouyushan** [comment]
@googlebot  I signed it!

**Comment by feHouyushan** [comment]
@googlebot I fixed it.

**Comment by feHouyushan** [comment]
@googlebot I fixed it.

**Comment by xu-baolin** [comment]
Thanks for the PR, Change looks good to me.
Also CC @justinmc

**Review by justinmc — APPROVED** [review]
LGTM 👍 

Thanks for making this improvement!  I've noticed that we sometimes miss things in the debugFillProperties and need better tests like this.

**Pull request merged**
