### PR TITLE
Reland - Introduce tone-based surfaces and accent color add-ons - Part 2

### PR DESCRIPTION
**Pull request by QuncCccccc**
Reverts flutter/flutter#143973

This is a reland for #138521 with an updated g3fix(cl/605555997). Local test: cl/609608958.

### CODE REVIEW

**Comment by BadaySoftware** [comment]
When will flutter support the new Color Scheme tokens? Current color palette is different what material 3 has now on native. For example Google apps now has dimmed, more contrasting surface versus what we have.

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by Piinks** [comment]
This is breaking the tree with some un-approved golden file images. I am going to revert this until we can take a look.

**Comment by Piinks** [comment]
Reason for revert: Failing goldens at the tip of tree

**Comment by QuncCccccc** [comment]
Oh I forget to update golden files! Thanks for helping revert this! Somehow the golden test alert doesn't show up.

**Pull request merged**
