### PR TITLE
Reland 3: Restores surface size and view configuration in the postTest of test binding

### PR DESCRIPTION
**Pull request by dkwingsmt**
Reland #87297.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
fly-by comment: is this just a straight reland or has anything changed?

**Comment by dkwingsmt** [comment]
@goderbauer For now it seems I just need to fix an ill-written internal test case and this PR can be merged unchanged. I'll make a global test to make sure before sending for review and telling what has been changed.

**Comment by dkwingsmt** [comment]
@goderbauer This PR is ready without any changes. All breakages have been fixed or eliminated except for several scuba changes, which will be applied using g3fix (I think).

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by dkwingsmt** [comment]
Progress: A few more internal breakages were discovered and I'm still investigating.

**Comment by goderbauer** [comment]
@dkwingsmt (PR triage): any update on this one?

**Comment by Hixie** [comment]
@dkwingsmt should we close this PR? It sounds like it's not ready for review.

**Pull request closed without merging**
