### PR TITLE
Fix `TabBar` divider and add `TabAlignment` option

### LINKED ISSUE #117722: Material 3 `TabBar` does not take full width when `isScrollable: true`
## Steps to Reproduce

1. Execute `flutter run` on the code sample 

**Expected results:** 

The bottom divider of the `TabBar` taking the full width available

**Actual results:** 

The `TabBar` taking minimum possible width.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> with SingleTickerProviderStateMixin {
  late TabController controller;

  final tabs = ['Tab 1', 'Tab 2', 'Tab 3'];

  @override
  void initState() {
    super.initState();
    controller = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    super.dispose();
    controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
      ),
      home: Scaffold(
        appBar: AppBar(
          bottom: TabBar(
            controller: controller,
            tabs: tabs.map((name) => Tab(text: name)).toList(),
            isScrollable: true,
          ),
        ),
        body: TabBarView(
          controller: controller,
          children: tabs.map((name) => Center(child: Text(name))).toList(),
        ),
      ),
    );
  }
}


```

</details>

<details>
  <summary>Logs</summary>

[logs.txt](https://github.com/flutter/flutter/files/10313296/logs.txt)

```
No issues found! (ran in 5.3s)
```

```
[✓] Flutter (Channel beta, 3.7.0-1.2.pre, on Microsoft Windows [Version 10.0.19043.2075], locale en-US)
    • Flutter version 3.7.0-1.2.pre on channel beta at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c29b09b878 (8 days ago), 2022-12-19 18:30:12 -0600
    • Engine revision 8c99b0feaf
    • Dart version 2.19.0 (build 2.19.0-444.2.beta)
    • DevTools version 2.20.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)  
    • Android SDK at C:\Users\mohamed.haisham\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java        
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866) 
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)     
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community    
    • Visual Studio Community 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866) 

[✓] VS Code (version 1.74.2)
    • VS Code at C:\Users\mohamed.haisham\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.2075]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 108.0.1462.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

### LINKED ISSUE #123112: TabBar height and vertical text alignment don't match spec
## Steps to Reproduce

1. Execute `flutter run` on the code sample. 
2. Observe the TabBar height.
3. Observe the vertical text alignment.

**Expected results:** 
Height and vertical text alignment match the [M3 specs](https://m3.material.io/components/tabs/specs#471acc02-600f-4fe2-8651-70549d4a6679).

**Actual results:** 
Height and vertical text alignment don't match the M3 specs.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = ThemeData.from(
      colorScheme: const ColorScheme.light(),
      textTheme: Typography.englishLike2021,
      useMaterial3: true,
    );

    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(
                'Expected results',
                style: theme.textTheme.titleMedium?.copyWith(
                  color: theme.colorScheme.onInverseSurface,
                ),
                textAlign: TextAlign.center,
              ),
              Text(
                'Height: 48.0\n'
                'Text vertically centered',
                style: theme.textTheme.bodyMedium?.copyWith(
                  color: theme.colorScheme.onInverseSurface,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 16.0),
              DefaultTabController(
                length: 3,
                child: Container(
                  color: theme.colorScheme.surface,
                  child: ConstrainedBox(
                    constraints: const BoxConstraints(maxHeight: 47.5),
                    child: const TabBar(
                      tabs: [
                        Tab(
                          child: Padding(
                            padding: EdgeInsetsDirectional.only(top: 2.5),
                            child: Text('Tab 1'),
                          ),
                        ),
                        Tab(
                          child: Padding(
                            padding: EdgeInsetsDirectional.only(top: 2.5),
                            child: Text('Tab 2'),
                          ),
                        ),
                        Tab(
                          child: Padding(
                            padding: EdgeInsetsDirectional.only(top: 2.5),
                            child: Text('Tab 3'),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 32.0),
              Text(
                'Actual results',
                style: theme.textTheme.titleMedium?.copyWith(
                  color: theme.colorScheme.onInverseSurface,
                ),
                textAlign: TextAlign.center,
              ),
              Text(
                'Height: 48.67\n'
                'Text not vertically centered',
                style: theme.textTheme.bodyMedium?.copyWith(
                  color: theme.colorScheme.onInverseSurface,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 16.0),
              DefaultTabController(
                length: 3,
                child: Container(
                  color: theme.colorScheme.surface,
                  child: const TabBar(
                    tabs: [
                      Tab(text: 'Tab 1'),
                      Tab(text: 'Tab 2'),
                      Tab(text: 'Tab 3'),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
        backgroundColor: theme.colorScheme.inverseSurface,
      ),
      theme: theme,
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.2.1 22D68 darwin-x64, locale en-US)
    • Flutter version 3.7.7 on channel stable at /Users/anthonymoretti/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (13 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
      instructions).

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • ED506CAA-EB76-47D8-BBDC-751CB0EE7EC8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • macOS 13.2.1
      22D68 darwin-x64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome
      111.0.5563.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

Tab issue

### LINKED ISSUE #124195: Introduce `TabGravity` for  scrollable`TabBar`
It's possible to align the scrollable tab bar to the left or center on Android.  There is no such option in Flutter

### Android Demo

https://user-images.githubusercontent.com/48603081/230063359-430c3a38-e8fd-4004-9273-ced4a338146f.mp4

There are some hacks to make this possible.
See https://stackoverflow.com/questions/55549762/how-to-align-tabbar-to-the-left-with-a-custom-starting-position

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/117722
fixes https://github.com/flutter/flutter/issues/124195
fixes https://github.com/flutter/flutter/issues/123112

### 2. Fix the default indicator height.

This PR adds override the `indicatorWeight` for M3 and updates docs.

Native vs Flutter

Screenshot 2023-04-17 at 17 53 51

###  3. Introduce `TabAlignment`

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const TabBarApp());

class TabBarApp extends StatelessWidget {
  const TabBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const TabBarExample(),
    );
  }
}

class TabBarExample extends StatefulWidget {
  const TabBarExample({super.key});

  @override
  State<TabBarExample> createState() => _TabBarExampleState();
}

class _TabBarExampleState extends State<TabBarExample> {
  TabAlignment _tabAlignment = TabAlignment.fill;
  bool isScrollable = false;

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.rtl,
      child: DefaultTabController(
        initialIndex: 1,
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            backgroundColor: Colors.transparent,
            title: const Text('TabBar Sample'),
            bottom: TabBar(
              tabAlignment: _tabAlignment,
              isScrollable: isScrollable,
              tabs: const <Widget>[
                Tab(
                  icon: Icon(Icons.cloud_outlined),
                ),
                Tab(
                  icon: Icon(Icons.beach_access_sharp),
                ),
                Tab(
                  icon: Icon(Icons.brightness_5_sharp),
                ),
              ],
            ),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                Text('TabAlignment: $_tabAlignment'),
                Wrap(
                  alignment: WrapAlignment.center,
                  spacing: 10,
                  runSpacing: 10,
                  children: <Widget>[
                    FilledButton(
                      onPressed: () {
                        setState(() {
                          _tabAlignment = TabAlignment.start;
                        });
                      },
                      child: const Text('TabBarAlignment.start'),
                    ),
                    FilledButton(
                      onPressed: () {
                        setState(() {
                          _tabAlignment = TabAlignment.startOffset;
                        });
                      },
                      child: const Text('TabBarAlignment.startOffset'),
                    ),
                    FilledButton(
                      onPressed: () {
                        setState(() {
                          _tabAlignment = TabAlignment.center;
                        });
                      },
                      child: const Text('TabBarAlignment.center'),
                    ),
                    FilledButton(
                      onPressed: () {
                        setState(() {
                          _tabAlignment = TabAlignment.fill;
                        });
                      },
                      child: const Text('TabBarAlignment.fill'),
                    ),
                  ],
                ),
                FilledButton(
                  onPressed: () {
                    setState(() {
                      isScrollable = !isScrollable;
                    });
                  },
                  child: Text('isScrollable: $isScrollable'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```
	
</details>

### Non-scrollable `TabBar`

| `TabAlignment.fill` | `TabAlignment.center` |
| --------------- | --------------- |
|  |  |

### Scrollable `TabBar`

| `TabAlignment.start` | 
| --------------- | 
|   |

| `TabAlignment.startOffset` | 
| --------------- | 
|    |

|  `TabAlignment.center`  | 
| --------------- | 
|  |

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by TahaTesser** [comment]
@Piinks taking this into the draft to address overall height with divider and indicator for https://github.com/flutter/flutter/issues/123112

**Comment by TahaTesser** [comment]
@Piinks 
This is ready for review.

**Review by Piinks — COMMENTED** [review]
After https://github.com/flutter/flutter/pull/122542, this should be split up into 3 separate PRs.

Especially since one of these is already known to be breaking, we'll need to land the alignment change first so we can opt the affected customers into the alignment so they are not broken by the width change that centered their tab bar. Unless, does this make the current alignment the default?

**Comment by TahaTesser** [comment]
> After #122542, this should be split up into 3 separate PRs.
> 
> Especially since one of these is already known to be breaking, we'll need to land the alignment change first so we can opt the affected customers into the alignment so they are not broken by the width change that centered their tab bar. Unless, does this make the current alignment the default?

Thank you! That makes sense. We discussed the customers affected internally by the change but I wanted to get it here so I can showcase that it is indeed expected that alignment would change. 

I'll split these PRs.

**Pull request closed without merging**
