### PR TITLE
Make `CupertinoDialogAction` not tappable when disabled

### LINKED ISSUE #107371: CupertinoDialogAction is tappable even if onPressed is null
The code to reproduce is:

```dart
    showCupertinoDialog(
      context: context,
      useRootNavigator: true,
      builder: (_) => CupertinoAlertDialog(
        title: const Text('Delete account'),
        content: const Text('Are you sure you want to delete the account?'),
        actions: [
          CupertinoDialogAction(
            isDestructiveAction: true,
            child: const Text('Delete'),
          ),
          CupertinoDialogAction(
            isDefaultAction: true,
            child: const Text('Cancel'),
            onPressed: () => Navigator.of(context, rootNavigator: true).pop(),
          ),
        ],
      ),
    );
```

Note the Delete button gets highlighted when tapping it, though it must be disabled completely.

<details>
  <summary>flutter doctor -v</summary>
```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-x64, locale en-RU)
    • Flutter version 3.0.4 at /Users/andrey/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (10 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/andrey/Library/Android/sdk
    • Platform android-31, build-tools 33.0.0-rc1
    • ANDROID_HOME = /Users/andrey/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 168FC36F-6574-46D2-B438-7737DE540BCB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 103.0.5060.114
    ! Error: Apple TV (3139) is not connected. Xcode will continue when Apple TV (3139) is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by victorsanni**
Currently, when `CupertinoAlertDialog` has an action (typically a `CupertinoDialogAction`, although can be any widget type) that is disabled, tapping on the action button still makes it change opacity, thus looking tappable:

https://github.com/flutter/flutter/assets/77553258/89410b92-f224-45b0-9023-51124de82298

While there is a dedicated class for `CupertinoAlertDialog` actions (`CupertinoDialogAction` button), actions can be any widget type.

Solving this issue is tricky because the actions are decoupled from the dialog box background. For example, if a `CupertinoDialogAction` is disabled, it's text will be shown at a lower opacity, as in the video recording above. However, the box/background behind it (which changes its opacity on tap) currently has no way of knowing that the action contained within is disabled.

There are two ways I see to fix this problem:

### Option A
Do not allow the action button box/background to be pressed if the action is a `CupertinoDialogAction` that is disabled:

```dart
      isPressed: widget.child is CupertinoDialogAction
        ? (widget.child as CupertinoDialogAction).enabled && _isPressed
        : _isPressed,
```

But Flutter is strongly against this pattern of programming, as a solution should not be conditional on the type of the child widget.

### Option B
Do not allow the action button box/background to be pressed if the action has an `onPressed` property set to null:

```dart
   bool canBePressed;
   try {
     canBePressed = (widget.child as dynamic).onChanged != null;
   } catch(_){
     canBePressed = true;
   }
...
isPressed: canBePressed && _isPressed,
```

but not only does the use of `try...catch` and `dynamic` feel problematic, but if the user makes a custom widget that does not mean the action is disabled if `onPressed` is set to null, this behavior will feel erroneous.

Considering `CupertinoDialogAction` is the recommended action to be used in `CupertinoAlertDialog`, and it has a child property itself that can serve as a wrapper for any custom widgets, should Option A be the recommended way to go? Or are there any alternatives/refactoring that give a better solution? Open to any ideas.

Note: 'action' and 'widget' are used interchangeably.

### Desired Result:

https://github.com/flutter/flutter/assets/77553258/c94b5492-f3ff-43e2-a8f2-55a9538b026a

Issue to fix: #107371 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by MitchellGoodwin** [comment]
Just thinking out loud: I wonder if the logic in `_RenderCupertinoDialogActions` should be refactored so that the styling for individual actions is separated out and put in their own class. So the logic around things like the dividers would stay in `_RenderCupertinoDialogActions`. And the styling for each individual action would be in a class that we would make public. The `CupertinoDialogAction` class itself would use that class, and if somebody wanted to they could wrap a custom widget with it to get the same effects. At a glance, it looks like a bit to untangle though.

Also, side note: it doesn't look like `hasCancelButton` does anything? Is it possible to make that true?

**Comment by justinmc** [comment]
[From the styleguide](https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#avoid-interleaving-multiple-concepts-together): 

> Many Widgets take a child. Widgets should be entirely agnostic about the type of that child. Don't use is or similar checks to act differently based on the type of the child.

Reading through that, I think it disqualifies both Option A and Option B above, even though I really wanted to convince myself that Option A was doable. Also if I understand your suggestion correctly @MitchellGoodwin, you would also require using `is` to check if a Widget supports your styling class?

It's possible to solve this problem by working around that limitation. Here are some ideas, though I don't really 100% like any of them yet:

### Take a parallel list

```dart
final List<CupertinoDialogAction> actions = <CupertinoDialogAction>[
  CupertinoDialogAction(enabled: true),
  CupertinoDialogAction(enabled: false),
];

return CupertinoAlertDialog(
  actions: actions,
  actionsEnabledList: actions.map((CupetinoDialogAction action) => action.enabled).toList(),
),
```

Or the parallel list could contain more detailed styling instead of just booleans. Also, we should assert that both lists are the same length.

### Take a function

```dart
return CupertinoAlertDialog(
  actions: <CupertinoDialogAction>[
    CupertinoDialogAction(enabled: true),
    CupertinoDialogAction(enabled: false),
  ],
  isActionEnabled: (Widget action) {
    if (action is CupertinoDialogAction) {
      return (action as CupertinoDialogAction).enabled;
    }
    return true;
  },
),
```

Ok this just seems like putting the burden of violating the styleguide on the user instead of on us now that I write it out :shrug:.

### Generate the `actions` widgets from data
I mentioned this already to @victorsanni, but this reminds me of [ContextMenuButtonItem](https://main-api.flutter.dev/flutter/widgets/ContextMenuButtonItem-class.html). In AdaptiveTextSelectionToolbar, you can pass widgets to the normal constructor, or you can use the [.buttonItems](https://main-api.flutter.dev/flutter/material/AdaptiveTextSelectionToolbar/AdaptiveTextSelectionToolbar.buttonItems.html) constructor and pass in these data classes with special properties. Internally it converts them to widgets and calls through to the default constructor.

Maybe it would be a big awkward change here, but I wanted to throw it out there.

### Wild idea: Incorporate the tap effect into the `actions`?
Currently the code that does the tap effect is separate from the `actions`, even though they visually look like the same thing. Why is that? Would it be possible to make that a publicly available widget?

This feels the most Fluttery to me, if it's possible.

**Comment by victorsanni** [comment]
Just an update on this: I think the wild idea is viable. I've been able to move the logic of painting the buttons out of `_RenderCupertinoDialogActions`, and I'm even exploring using `CupertinoButton` to display the buttons.

@MitchellGoodwin you were right, `hasCancelButton` does nothing.

**Comment by victorsanni** [comment]
On talking about this with @dkwingsmt offline, `_RenderCupertinoDialogActions` has the logic of painting the buttons instead of delegating to the buttons themselves because `_RenderCupertinoDialogActions` needs to know what buttons are being pressed at any given time time so that it does not paint a divider bordering a pressed button.

**Comment by victorsanni** [comment]
With no current solution in mind, I will close this to take it off the PR queue.

**Pull request closed without merging**
