### PR TITLE
Revert "TextField border gap padding improvement"

### PR DESCRIPTION
**Pull request by jmagman**
Reverts flutter/flutter#92940

Post-submission failure https://ci.chromium.org/p/flutter/builders/prod/Linux%20web_canvaskit_tests_3/117
Tree is closed.

```
05:51 +746 ~17 -1: test/material/input_decorator_test.dart: InputDecorator OutlineBorder focused label with icon [E]                                                                                   
  Test failed. See exception logs above.
  The test description was: InputDecorator OutlineBorder focused label with icon
  
[ +855 ms] Preparing to send command: {"imageFile":"/b/s/w/ir/x/t/flutter_tools.MHLKHT/flutter_web_platform.NAAQEC/imageTUJKXZ/image","key":"input_decorator.outline_icon_label.ltr.png","update":false}
[ +234 ms] <<< {"success":true}
[ +164 ms] Preparing to send command: {"imageFile":"/b/s/w/ir/x/t/flutter_tools.MHLKHT/flutter_web_platform.NAAQEC/imageGCIBFW/image","key":"input_decorator.outline_icon_label.rtl.png","update":false}
[ +250 ms] <<< {"success":true}
```

### CODE REVIEW

**Comment by LongCatIsLooong** [comment]
It looks like the failure was caused by a untriaged golden change? @Piinks would it be possible to triage a golden image retroactively in order to fix the build?

**Comment by justinmc** [comment]
Yeah sorry if I missed that.  My PR was known to make a few tiny sub pixel changes, if it's anything like that it should be accepted.

**Comment by jmagman** [comment]
`Linux web_canvaskit_tests_*` didn't run on that PR https://github.com/flutter/flutter/pull/92940/checks
It should have, those changes are in `packages/`
https://github.com/flutter/flutter/blob/e961ea6f41387b2e25cdfcea1b5cb4dbe2a6630e/.ci.yaml#L1266-L1269

**Comment by jmagman** [comment]
> It looks like the failure was caused by a untriaged golden change? @Piinks would it be possible to triage a golden image retroactively in order to fix the build?

Can this be reverted while the goldens issue is investigated to reopen the tree?

**Comment by justinmc** [comment]
Yes feel free to revert in the meantime 👍

**Comment by justinmc** [comment]
Is this really the golden failure? Nothing that big should have changed. https://flutter-gold.skia.org/detail?test=material.input_decorator.outline_label.ltr&digest=11b89b1b5047b52da94dd8b6d8dc817b

I think @Piinks was mentioning some naming collision or something with the goldens right?  Maybe this is caused by that problem.

**Comment by jmagman** [comment]
> Yes feel free to revert in the meantime 👍

@justinmc I'm going to be AFK for the next hour, can you or gardener @hterkelsen handle whatever reverts need to happen in the goldens, then merge ?

**Comment by jmagman** [comment]
@justinmc I think this needs a LGTM for the goldens to run?

**Review by justinmc — APPROVED** [review]
Ah sorry LGTM!  Yes sounds good.

**Comment by Piinks** [comment]
> It looks like the failure was caused by a untriaged golden change? @Piinks would it be possible to triage a golden image retroactively in order to fix the build?

Yes, you can approve the image and re-run the test to open the tree, if the image change was intended. If the image change is not intended, reverting would be appropriate, but you will have to triage the image as negative on the dashboard. Once Gold receives an untriaged image, you have to visit the dashboard to tell Gold what to do with it, it is in the error message. 
From the failure above:

```
Exception: Skia Gold received an unapproved image in post-submit
          testing. Golden file images in flutter/flutter are triaged
          in pre-submit during code review for the given PR.

          Visit https://flutter-gold.skia.org/ to view and approve
          the image(s), or revert the associated change. For more
          information, visit the wiki:
          https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter
```

**Pull request merged**
