### PR TITLE
[bots] Do not invoke `pub global run` concurrently

### LINKED ISSUE #3165: Running `pub global run` concurrently
If the snapshot is missing we do `deleteBinstubs` before recreating them, this opens a window for a race condition.

### PR DESCRIPTION
**Pull request by dcharkes**
`dev/bots/analyze_sample_code.dart` freezes intermittently on the Dart Flutter HHH bot.

Follow up of #90447 #90880, and #91024.

It turns out `pub global run` does not enjoy being invoked concurrently at the moment https://github.com/dart-lang/pub/issues/3165. (Thanks @cskau-g @sigurdm @szakarias for the help!) Invocations of `pub global run` were introduced in #87231 two months ago.

We have multiple options:

1. Wait for `pub global run` to be fixed https://github.com/dart-lang/pub/issues/3165 (but we have recurring failures on the HHH bot right now).
2. Reduce the concurrency to 1 task at the time for now (this PR). And revert it back when pub is patched.
3. Invoke `import 'package:snippets/snippets.dart';` instead of using `pub global run`. However, a bunch of the logic is in `bin/snippets.dart` we would have to duplicate that logic or move it to the `lib` folder.
4. A good solution that didn't come to my mind... 

Background info: [go/flutter-hhh-analyze-freezes]

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[go/flutter-hhh-analyze-freezes]: http://go/flutter-hhh-analyze-freezes

### CODE REVIEW

**Comment by sigurdm** [comment]
I still believe `pub global run` should be thread safe for this task (as long as the snapshot has not been deleted I don't see how a race can occur). But I might be overlooking something...

**Comment by dcharkes** [comment]
> But I might be overlooking something...

@sigurdm The [first](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8838934078135415217/+/u/flutter_analyze/stdout) `flutter analyze` failure is 15th of august, the mentioned PR starting to use `pub global run` was merged 12th of august. Also, we can see that the crashes are from `pub global run`. So, I would be very surprised if this is not due to `pub global run`. We must be overlooking something.

**Comment by gspencergoog** [comment]
First, obviously, we should definitely fix `dart pub global run` if it is broken. It's mainly useful for software tools, and software tools will be run concurrently.

> Invoke import 'package:snippets/snippets.dart'; instead of using pub global run. However, a bunch of the logic is in bin/snippets.dart we would have to duplicate that logic or move it to the lib folder.

I actually think this is the best option. Dartdoc has a built-in ability to snapshot dart tools. I wrote that when I added tools to Dartdoc, because otherwise it's too slow to be practical. If we refactor the snippets tool so that the `main` logic is in the package, and then create a `.dart` file in the flutter repo that just invokes that main by passing in the arguments, Dartdoc will take care of snapshotting it and running it concurrently. This could serve as a temporary solution until global run is fixed.

My goals were to 1) speed up Dartdoc invocation by running tools concurrently, and 2) move the snippets code out of the Flutter repo. I'd rather not backtrack on those by switching back to serial execution or by moving logic back into the Flutter repo.

One other data point, however, is that I have been able to run Dartdoc on a 72-core machine a bunch of times without incident. One would think that if there is a race, it would be far more likely to happen there than on a 4-core bot. We should try creating a pathological case (`dart pub run snippets --help`) and run a bunch of jobs concurrently and see if we can get it to fail.

**Comment by dcharkes** [comment]
> One other data point, however, is that I have been able to run Dartdoc on a 72-core machine a bunch of times without incident. 

Me too. I'm also not able to make it fail locally.

> > Invoke import 'package:snippets/snippets.dart'; instead
>
> I actually think this is the best option.

That's fine with me. Do you want to take a shot at that? Otherwise I can take a look after the weekend.

**Comment by gspencergoog** [comment]
> Do you want to take a shot at that? Otherwise I can take a look after the weekend.

Sure, I can do that.

**Comment by gspencergoog** [comment]
Actually, @dcharkes how about this: Now that we know that it is related to the first-run executable building, we just add a `dart pub global run snippets --help > /dev/null` into the Flutter `docs.sh` script right after activating the tool. That should prevent this issue, and be very low-impact (and also not a lot of work: I'm all for lazy evaluation! :-) ).

**Comment by dcharkes** [comment]
Closing in favor of

* #91110

**Pull request closed without merging**
