### PR TITLE
Reland "Track lastKnownRemoteTextEditingValue separately from received data"

### PR DESCRIPTION
**Pull request by GaryQian**
Reland https://github.com/flutter/flutter/pull/49406

The original patch was causing failures in G3 where they override EditableTextState

Exploring workarounds.

### CODE REVIEW

**Comment by GaryQian** [comment]
Reworked a condition to allow g3 tests to pass.

**Comment by GaryQian** [comment]
Oops need to fix some git issues hang on.

**Comment by GaryQian** [comment]
Ok, ready!

**Review by justinmc — APPROVED** [review]
LGTM 👍

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

**Pull request merged**
