### PR TITLE
Prevent negative scroll offset for a long lists in Dropdown widget

### PR DESCRIPTION
**Pull request by romkor**

### CODE REVIEW

**Comment by romkor** [comment]
@gspencergoog Thank you for reply!
I can describe my use case.
I have dropdown with country phone codes. Dropdown default value is fist code from list. 
But when dropdown is opened it scrolls down to the end (because of negative offset).

I see your point about expected negative offsets, but in this case its kind of broken.

Regarding test case, I hope prepare it before end of the week.

**Comment by Hixie** [comment]
This doesn't seem like the right fix for the problem you describe.

Why are you getting a negative offset? Why would a negative offset scroll to the end?

**Comment by romkor** [comment]
```dart
scrollOffset = selectedItemOffset - (buttonTop - menuTop));
```
Ideal scenario, when dropdown is placed on the absolute top of screen:
selectedItemOffset: 8
buttonTop : 26
menuTop : 26
8 - (26 - 26) // 8
scrollOffset : 8

Broken scenario, when dropdowns top is at least 31:
selectedItemOffset: 8
buttonTop : 57
menuTop : 48
8 - (57 - 48) // -1
scrollOffset : -1

All numbers collected during debugging.

**Comment by Hixie** [comment]
I think what's going on here is that only part of this code is handling the difference between buttonTop and the top of where a _kMenuItemHeight-high menu item will appear when overlapped with the button. The rest of the code that deals in buttonTop doesn't take that into account.

I think if we addressed that, rather than just clamping the scroll offset, the logic would work.

I haven't tested this theory though.

**Comment by Hixie** [comment]
@romkor Did you have a chance to look at my last comment?

**Comment by mklim** [comment]
Sorry @romkor, I hadn't noticed this PR. It looks like I took the same approach to fixing the overflow issue that you did. @Hixie @gspencergoog should 020fd59 be reverted? It also clamps `scrollOffset` at 0 to prevent the negative offset and then scrolling to the bottom of the list.

**Comment by gspencergoog** [comment]
@mklim - Seems prudent to investigate @Hixie's theory, at least.

**Comment by jslavitz** [comment]
Hey, so I think the fix I was working on (which caches menuTop) makes the most sense to fix this issue. https://github.com/flutter/flutter/pull/22594

**Pull request closed without merging**
