### PR TITLE
`ThemeData`: Fix `ColorScheme` is ignored when provided in the `ThemeData.colorScheme`

### LINKED ISSUE #101389: ColorScheme.background is not applied as scaffoldBackgroundColor when ThemeData.colorScheme is set
## Steps to Reproduce

**Expected and Actual results:** see in the code example

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(ExampleApp());
}

// ✅ expected and actual result: Scaffold widget background is orange
class ExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        // is applied as Scaffold widget background
        scaffoldBackgroundColor: Colors.orange,    
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.green),
      ),
      home: Scaffold(body: Container()),
    );
  }
}

// ✅ expected and actual result: Scaffold widget background is dark
class ExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        // when ColorScheme is generated inside ThemeData constructor 
        // with ColorScheme.fromSeed(seedColor: colorSchemeSeed),
        // it's .background field is applied as Scaffold widget background
        colorSchemeSeed: Colors.green,
        brightness: Brightness.dark,    
      ),
      home: Scaffold(body: Container()),
    );
  }
}

// ❌ expected result: Scaffold widget background is orange
// ❌ actual result: Scaffold widget background is light
class ExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.green,
          // is not being applied as Scaffold widget background
          background: Colors.orange,  
        ),
      ),
      home: Scaffold(body: Container()),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] VS Code (version 1.65.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

```
</details>

The issue is reproducible in DartPad `Based on Flutter 2.10.4 Dart SDK 2.16.2`

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/101389

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by darrenaustin — COMMENTED** [review]
Thanks for the patch @TahaTesser. This looks like what I would have wanted originally, but I have a feeling this might break existing apps that depend on color defaults that aren't part of the ColorScheme. I'm a little surprised this didn't break any tests in the repo. Before continuing, we should probably run this against our internal tests and see if anything breaks there. I will take a look at doing that tomorrow.

**Comment by TahaTesser** [comment]
> Thanks for the patch @TahaTesser. This looks like what I would have wanted originally, but I have a feeling this might break existing apps that depend on color defaults that aren't part of the ColorScheme. I'm a little surprised this didn't break any tests in the repo. Before continuing, we should probably run this against our internal tests and see if anything breaks there. I will take a look at doing that tomorrow.

That makes sense, thank you for running the internal tests!

**Comment by darrenaustin** [comment]
As I suspected, this caused several hundred screen test failures in our internal tests. It changes the default value for the scaffold background if a color scheme is specified. While I would love to see all the defaults come from the color scheme instead of hard coded defaults, this would be a breaking change and we would have to follow the breaking change procedure to migrate the change in stages.

**Comment by TahaTesser** [comment]
Thank you for taking a look!

**Pull request closed without merging**
