### PR TITLE
Gallery home page header color should track the material theme

### LINKED ISSUE #5362: Gallery: switching to dark theme, then light, doesn't switch colors of headers on home
Open Gallery, switch to dark theme, then switch to light theme.

Notice how the headers (Demos, Components) are still teal. They should be dark gray (original light theme).

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes #5362

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
Is there something worth testing here?

**Comment by HansMuller** [comment]
A test that verified this would be a bit fragile, since it would depend on strings and colors could change and bit complicated, since it would on orchestrating a series of animated transitions.

I don't think this change is worth testing.

**Comment by HansMuller** [comment]
cc @mpcomplete

**Comment by mpcomplete** [comment]
LGTM

**Comment by abarth** [comment]
IMHO, the proper "test" for this bug is to fix https://github.com/flutter/flutter/issues/5491, which will cause existing tests to blow up with an exception.

**Pull request merged**
