### PR TITLE
Setup leak tracking regression for material.

### PR DESCRIPTION
**Pull request by polina-c**

### CODE REVIEW

**Comment by goderbauer** [comment]
Looks like the tests are failing on this one and there's a merge conflict. Can you take a look?

**Comment by polina-c** [comment]
> Looks like the tests are failing on this one and there's a merge conflict. Can you take a look?

Yes, yesterday everything was green, but then eroded. I will refresh it, but it may erode again as it involves many files. If you are ok with simply replacing `testWidgets` with `testWidgetsWithLeakTracking` for leak-free tests, can you LGTM, and then I will sync everything and add label `autosubmit`. 

I promise this PR will mark only leak-free tests.

**Comment by polina-c** [comment]
I ended up excluding conflicting files, because it is easier to re-cover them, than to resolve conflicts.

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
