### PR TITLE
Revert use of const asserts in flutter_driver

### PR DESCRIPTION
**Pull request by cbracken**
Fixes bot breakage resulting from commit
7d7132636369914402507c7b15d635039193ee46 (#10540).

### CODE REVIEW

**Review by tvolkert — APPROVED** [review]
LGTM

**Comment by cbracken** [comment]
Example failure (for ref):
```
00:00 [32m+0[0m: end-to-end test (setUpAll)[0m
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:8100/
[trace] FlutterDriver: Looking for the isolate
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
00:01 [32m+0[0m[31m -1[0m: end-to-end test (setUpAll)[0m
  'package:flutter_driver/src/health.dart': error: line 33 pos 7: identifier expected
      : assert(status != null);
        ^
  
  package:flutter_driver/src/driver.dart 267:40  FlutterDriver.connect
  test_driver/keyboard_resize_test.dart 12:36    main..
  ===== asynchronous gap ===========================
  dart:async                                     _Completer.completeError
  package:flutter_driver/src/driver.dart 275:3   FlutterDriver.connect
  ===== asynchronous gap ===========================
  dart:async                                     _asyncThenWrapperHelper
  package:flutter_driver/src/driver.dart 141:85  FlutterDriver.connect
  test_driver/keyboard_resize_test.dart 12:36    main..
  ===== asynchronous gap ===========================
  dart:async                                     new Future.microtask
  test_driver/keyboard_resize_test.dart 11:23    main..
```

**Comment by a14n** [comment]
LGTM and sorry for the breakage. I saw the red squares on [Build dashboard](https://flutter-dashboard.appspot.com/build.html) but I hadn't access to see the logs and understand what was wrong.

**Comment by cbracken** [comment]
No problem! If you click one of the red dots, it should take you to the logs. [Example](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9iODNkZGNkMTkyMjEwMGIwMmQ0MGUxZGY5YzZhYjMxMzBmNjVlZWM4DAsSBFRhc2sYgICAgIDkiQoM).

Clicking the chromebot builds (the ones with the Chromium logo at the top of the column) will take you to one of [these pages](https://build.chromium.org/p/client.flutter/builders/Mac) which should allow you to click through.

We should probably document some of this and link it from the dashboard. I've filed #10586 for this.

**Comment by a14n** [comment]
>No problem! If you click one of the red dots, it should take you to the logs. [Example](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9iODNkZGNkMTkyMjEwMGIwMmQ0MGUxZGY5YzZhYjMxMzBmNjVlZWM4DAsSBFRhc2sYgICAgIDkiQoM). BTW, if you find you don't have access to that, can you file a bug? We should definitely ensure those are public.

I haven't access even if I'm logged in. I see the following message:

>Authentication/authorization error: xxxx@gmail.com is not authorized to access the dashboard

**Comment by cbracken** [comment]
Thanks for letting me know! Will discuss with the folks who manage the dashboard infra and see what's up.

**Pull request merged**
