### PR TITLE
[flutter_tools] modify Skeleton template to use ListenableBuilder instead of AnimatedBuilder

### LINKED ISSUE #128801: Modify Skeleton template to use `ListenableBuilder` instead of `AnimatedBuilder`
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

When creating a new project from the skeleton template `flutter create -t skeleton project_name` . It works as intended but it uses `AnimatedBuilder` to listen to the ChangeNotifier, recently `ListenableBuilder` has come to stable, which provides the same functionality that `AnimatedBuilder` but, and I quote "has a more friendly name for the class and for the parameter that it listens to, intended to make it more discoverable and less confusing for new users." as per https://github.com/flutter/flutter/pull/116543 .

### Proposal

Update the template to use ListenableBuilder instad of AnimatedBuilder. Tests should remain the same without the need for new ones as the functionality will be identical after the change.

### PR DESCRIPTION
**Pull request by fabiancrx**
Replaces AnimatedBuilder for ListenableBuilder in the skeleton template

Fixes https://github.com/flutter/flutter/issues/128801

No tests needed

### CODE REVIEW

**Comment by christopherfujino** [comment]
@gspencergoog WDYT about this change?

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Works for me. It is more readable as a `ListenableBuilder`, which is the whole point of adding that Builder widget.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by gspencergoog** [comment]
Because it doesn't have a test, you'll need to ask for test exemption from Hixie on Discord, as the bot's message above says.  It's a refactoring with no semantic change, so it's likely to be approved.

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

**Pull request merged**
