### PR TITLE
Add a missing `const` that triggered analysis warnings

### PR DESCRIPTION
**Pull request by jamesderlin**
## Tests

I manually ran `flutter analyze --flutter-repo`.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by goderbauer** [comment]
I wonder why this didn't turn our build red?

**Comment by jamesderlin** [comment]
> I wonder why this didn't turn our build red?

I don't understand it either, but it's caught when I run `flutter analyze --flutter-repo` locally. =/

Maybe CI is running the wrong analyzer version?  There was a bug (https://github.com/dart-lang/linter/issues/1592) about `prefer_const_constructors` being inconsistently honored; maybe that's related?

**Comment by jamesderlin** [comment]
Adding to the mystery, running `flutter analyze --flutter-repo` locally on my other system doesn't report any problems. =/

At any rate, I think this change is correct (and passes analysis).

**Comment by jamesderlin** [comment]
Rami fixed this in https://github.com/flutter/flutter/pull/38348.

**Pull request closed without merging**
