### PR TITLE
[flutter_tools] Ensure service worker starts caching assets since the very first load

### LINKED ISSUE #115336: [Flutter web] Assets are downloaded again in the 2nd visit despite service worker
Hello, I'm working on a project that is performance-sensitive, I need to squeeze every available resource in the HTML5 world to enhance performance and loading times.

Flutter apps download assets again in the second visit despite service worker, I know this happens because there is no call to 
`self.clients.claim();`

Is there a reason why `self.clients.claim()` is not being called? Imo this is a desirable behavior by default or at least it should be a feature you can enable via `environment.defines`

## Steps to Reproduce

1. create a new project `flutter create example`
2. build it for the web `flutter build web`
3. serve it `python3 -m http.server`
4. load the app for the first time
5. reload the app and **notice how assets added by the app developer are downloaded again**

**Expected results:** service worker should kick in right away
**Actual results:** service worker start caching things after the second session

### PR DESCRIPTION
**Pull request by david-landeros**
As a performance improvement, this PR ensure service worker starts caching assets since the very first load by calling `self.clients.claim()`,

Fixes: https://github.com/flutter/flutter/issues/115336

This is how the service worker behaves now:
- Load page for the first time, and service worker gets installed
- Request asset cat.jpg and service worker caches it right away
- Load the page for the 2nd time and it must be taken from the cache.

https://user-images.githubusercontent.com/79719460/201992435-843172da-3f5e-4904-afd5-e8c53b47853f.mp4

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I updated existing tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by christopherfujino** [comment]
@ditman can you take a look at this one?

**Comment by ditman** [comment]
Ha, the tests that are failing are doing so because this is working better now, for example:

* location ['main.dart.js'] is <1> instead of <2>

That number is "the number of times it was downloaded from the server", which kinda makes sense is 1 now. I'll review the tests to make sure we're not introducing anything nefarious (like an un-updateable service worker or similar :P)

**Comment by davidlanderos-digital** [comment]
Hi, @ditman I updated those integration test to expect fewer requests, now they are passing,

The test that failed in this check didn't failed in the previous commit which makes me think it's flaky, or did I really break something 😅?

**Comment by ditman** [comment]
@davidlanderos-digital thanks! I'm finishing something urgent, but this notification is living in my Notifications forever now, until I review it. I want to also bring this up with the web team so they can take a second look (ETA for a decision: week 48!)

**Comment by christopherfujino** [comment]
friendly ping @ditman

**Review by ditman — APPROVED** [review]
This looks to work amazingly in my machine, let's go!

**Comment by ditman** [comment]
(Finding a second reviewer)

**Review by yjbanov — APPROVED** [review]

**Comment by ditman** [comment]
Let's go!

**Comment by christopherfujino** [comment]
@davidlanderos-digital I'm sorry, but I "Google testing" is stuck because of an infrastructure issue. Could you rebase upstream and push again?

**Comment by davidlanderos-digital** [comment]
@christopherfujino Hi, this PR is messed up because of the rebase, i'm closing it in favor of a this new PR https://github.com/flutter/flutter/pull/116833

**Pull request closed without merging**
