### PR TITLE
Make bottom app bar safe area friendly

### PR DESCRIPTION
**Pull request by xster**
#16821

### CODE REVIEW

**Comment by HansMuller** [comment]
This is tricky. Do we really want to make the bottom app bar _unconditionally_ fit within the safe area?

Wouldn't it be better to have the developer decided by adding a SafeArea themselves?

**Comment by xster** [comment]
We'd want to keep the behaviour consistent with the bottom nav bar. It's by definition at the bottom and should have a bottom friendly layout by default.

**Comment by HansMuller** [comment]
But the BottomAppBar can be set up to accommodate the notched out unsafe areas and if we do this, we'll disable bottom app bars like that.

If we document the fact that you might want to wrap your BottomAppBar in a SafeArea, then we're supporting both use cases.

**Comment by HansMuller** [comment]
LGTM

**Pull request merged**
