### PR TITLE
randomize tool tests

### PR DESCRIPTION
**Pull request by dnfield**
Randomizes the execution order of tool tests.  

I want to run this through CI a bunch of times to try to see if it breaks anything before trying to land.

Addresses tool portion of https://github.com/flutter/flutter/issues/47233

----

This looks like it's finally passing.  I'm re-running the passed jobs a few times just to be sure.

I think we should try to land this soon-ish before new tests have a chance to regress.  Unfortunately, it's possible there's _some_ random seed that we haven't tried that would result in a failure - and this may be confusing for people who find their tests pass locally but fail on CI, or find that their tests passed on presubmit but failed on post.  But it should result in more robust tests that are less flaky and harder to break by introducing new tests in between.

/cc @christopherfujino @jmagman @blasten @stuartmorgan @a14n who are recent-ish committers to this part of the repo

/cc @digiter @keyonghan @godofredoc - this impacts infra/testing.

### CODE REVIEW

**Comment by dnfield** [comment]
I've fixed all the individual files that were bad for this.  It's possible there are some others that will be uncovered through more CI runs of this.  Once the four PRs I have out are merged into this one, I'll try rerunning it a bunch more times.

**Comment by dnfield** [comment]
All currently known failures have fixes merged - I'm setting this up to run on my Linux box in a loop until failure now.

**Comment by goderbauer** [comment]
Any plans to also do this for the framework tests? :)

**Comment by dnfield** [comment]
@goderbauer yes, but that's going to take longer since presumably it will require lots of breaking changes to fix any tests.

**Comment by dnfield** [comment]
I talked with @hixie today - he's going to look at revising the breaking change policy at some point so that changes like this won't be considered breaking (e.g. refactoring a test to make it more repeatable).

**Comment by dnfield** [comment]
Merging this up to master again to see what's still failing.

**Review by jonahwilliams — APPROVED** [review]
LGTM (...if tests pass, naturally)

**Review by zanderso — APPROVED** [review]

**Comment by dnfield** [comment]
This seems like it just needs #52088 and it should be good to go.

**Review by christopherfujino — APPROVED** [review]
LGTM (once tests pass)

**Review by blasten — APPROVED** [review]

**Comment by zanderso** [comment]
Marking 'work in progress', @dnfield please ping again, when we should take another look.

**Comment by jonahwilliams** [comment]
@dnfield we now randomize the unit test shard ourselves, (are you still working on this otherwise)?

**Comment by dnfield** [comment]
I'm fine closing this. Every time I tried to get it back up to date, something new would land and break it.

**Pull request closed without merging**
