### PR TITLE
Remove cross_arch_tests from recipes cq.

### PR DESCRIPTION
**Pull request by godofredoc**
These tests are blocking rolls of the recipe dependencies.

https://ci.chromium.org/p/flutter/builders/try/recipes-with-led/b8800032390708370785?

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jmagman** [comment]
```
An error occurred while installing ffi (1.15.5), and Bundler cannot continue.
```

Hm, why is this needed on master?

https://flutter-review.googlesource.com/c/recipes/+/34400/comments/3de8d3da_334648a4

> recipes-with-led isn't configured to correctly run on release branches. It's testing against main configs, so release team unfortunately has to monitor in prod.

**Comment by godofredoc** [comment]
> ```
> An error occurred while installing ffi (1.15.5), and Bundler cannot continue.
> ```
> 
> Hm, why is this needed on master?
> 
> https://flutter-review.googlesource.com/c/recipes/+/34400/comments/3de8d3da_334648a4
> 
> > recipes-with-led isn't configured to correctly run on release branches. It's testing against main configs, so release team unfortunately has to monitor in prod.

[Mac_arm64 tool_host_cross_arch_tests](https://ci.chromium.org/p/flutter/builders/staging/Mac_arm64%20tool_host_cross_arch_tests) is failing consistently and should not be blocking recipes CLs. Maybe we need a test that fails if we set `bringup: true` with `enable_cq: true`?

If  `Mac_x64 tool_host_cross_arch_tests` should be blocking recipe CLs I can update this change to only remove CQ from the arm64 and try to find the error.

**Comment by jmagman** [comment]
The `arm` recipe crash is https://github.com/flutter/flutter/issues/113231, which is why it has `ignore_flakiness: "true"` https://github.com/flutter/flutter/pull/112999.  

I don't understand why x64 has an ffi error though, that should be passing: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/flutter-try-builder_chops-service-accounts.iam.gserviceaccount.com/aa5c8a8d8a5420b170861e817546b277f995f17b8c8e86d1ca9a44f5181fb7ab/+/build.proto

**Comment by godofredoc** [comment]
> The `arm` recipe crash is #113231, which is why it has `ignore_flakiness: "true"` #112999.
> 
> I don't understand why x64 has an ffi error though, that should be passing: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/flutter-try-builder_chops-service-accounts.iam.gserviceaccount.com/aa5c8a8d8a5420b170861e817546b277f995f17b8c8e86d1ca9a44f5181fb7ab/+/build.proto



> The `arm` recipe crash is #113231, which is why it has `ignore_flakiness: "true"` #112999.
> 
> I don't understand why x64 has an ffi error though, that should be passing: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/flutter-try-builder_chops-service-accounts.iam.gserviceaccount.com/aa5c8a8d8a5420b170861e817546b277f995f17b8c8e86d1ca9a44f5181fb7ab/+/build.proto



> The `arm` recipe crash is #113231, which is why it has `ignore_flakiness: "true"` #112999.
> 
> I don't understand why x64 has an ffi error though, that should be passing: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/flutter-try-builder_chops-service-accounts.iam.gserviceaccount.com/aa5c8a8d8a5420b170861e817546b277f995f17b8c8e86d1ca9a44f5181fb7ab/+/build.proto

There is something very strange with this test, led is not collecting $flutter/osx_sdk property. Can we land this change as it is and bring the tests to recipes cq once the test is fixed?  They are failing in different fronts and they are blocking multiple fixes to recipes.

**Review by ricardoamador — APPROVED** [review]
LGTM

**Comment by godofredoc** [comment]
> > The `arm` recipe crash is #113231, which is why it has `ignore_flakiness: "true"` #112999.
> > I don't understand why x64 has an ffi error though, that should be passing: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/flutter-try-builder_chops-service-accounts.iam.gserviceaccount.com/aa5c8a8d8a5420b170861e817546b277f995f17b8c8e86d1ca9a44f5181fb7ab/+/build.proto
> 
> > The `arm` recipe crash is #113231, which is why it has `ignore_flakiness: "true"` #112999.
> > I don't understand why x64 has an ffi error though, that should be passing: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/flutter-try-builder_chops-service-accounts.iam.gserviceaccount.com/aa5c8a8d8a5420b170861e817546b277f995f17b8c8e86d1ca9a44f5181fb7ab/+/build.proto
> 
> > The `arm` recipe crash is #113231, which is why it has `ignore_flakiness: "true"` #112999.
> > I don't understand why x64 has an ffi error though, that should be passing: https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/flutter-try-builder_chops-service-accounts.iam.gserviceaccount.com/aa5c8a8d8a5420b170861e817546b277f995f17b8c8e86d1ca9a44f5181fb7ab/+/build.proto
> 
> There is something very strange with this test, led is not collecting $flutter/osx_sdk property. Can we land this change as it is and bring the tests to recipes cq once the test is fixed? They are failing in different fronts and they are blocking multiple fixes to recipes.

Tracking issue: https://github.com/flutter/flutter/issues/113611

**Pull request merged**
