### PR TITLE
Add splashOnTap bool field to TextField and TextFormField

### PR DESCRIPTION
**Pull request by xiprox**
This PR adds a `splashOnTap` bool field (that is `true` by default) to the TextField and TextFormField widgets to allow developers to disable the splash effect that is shown on tap.

```dart
new TextField(splashOnTap: false)
```

This would be useful when developers want to implement more customized designs. The splash effect on the TextField itself can be a bit undesirable: 

I've gone over the guidelines and have done my best, but please let me know if I've failed or if you want _anything_ changed.

### CODE REVIEW

**Comment by xiprox** [comment]
I signed it!

**Comment by Hixie** [comment]
There's a splash factory theme value that lets you control exactly what is rendered; is that not sufficient?

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
Right. Replacing or defeating the splash in widgets doesn't come up very often. You can do it by replacing the Theme's splashFactory with one that either paints the splash you want or doesn't paint anything at all:

```
class NoSplashFactory extends InteractiveInkFeatureFactory {
  const NoSplashFactory();

  @override
  InteractiveInkFeature create({
    @required MaterialInkController controller,
    @required RenderBox referenceBox,
    @required Offset position,
    @required Color color,
    bool containedInkWell: false,
    RectCallback rectCallback,
    BorderRadius borderRadius,
    double radius,
    VoidCallback onRemoved,
  }) {
    return new NoSplash(
      controller: controller,
      referenceBox: referenceBox,
      position: position,
      color: color,
      containedInkWell: containedInkWell,
      rectCallback: rectCallback,
      borderRadius: borderRadius,
      radius: radius,
      onRemoved: onRemoved,
    );
  }
}

class NoSplash extends InteractiveInkFeature {
  NoSplash({
    @required MaterialInkController controller,
    @required RenderBox referenceBox,
    Color color,
    VoidCallback onRemoved,
  }) : assert(controller != null),
       assert(referenceBox != null),
       _color = color,
       super(controller: controller, referenceBox: referenceBox, onRemoved: onRemoved);
  @override
  void paintFeature(Canvas canvas, Matrix4 transform) { }
}
```

So to defeat the splash in just one widget, wrap it in a Theme whose ThemeData.splashFactory is `const NoSplash()`

**Comment by trK54Ylmz** [comment]
I've added `NoSplashFactory` in the theme,

```
...
theme: new ThemeData(
    primarySwatch: Colors.blue,
    splashFactory: const NoSplashFactory(),
),
...
```

and according to `NoSplashFactory` I got this error, 

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#f05e1](state:
flutter: OverlayState#259d3(tickers: tracking 24 tickers, entries: [OverlayEntry#f3f1e(opaque: false;
flutter: maintainState: false), OverlayEntry#0ad4e(opaque: false; maintainState: true),
flutter: OverlayEntry#ee661(opaque: true; maintainState: false), OverlayEntry#ad955(opaque: false;
flutter: maintainState: true)])):
flutter: 'package:flutter/src/material/material.dart': Failed assertion: line 432 pos 12: '_inkFeatures !=
flutter: null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _RenderInkFeatures._removeFeature (package:flutter/src/material/material.dart)
flutter: #3      InkFeature.dispose (package:flutter/src/material/material.dart:525:17)
flutter: #4      _TextFieldState.deactivate (package:flutter/src/material/text_field.dart:446:16)
flutter: #5      StatefulElement.deactivate (package:flutter/src/widgets/framework.dart:3806:12)
flutter: #6      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1707:13)
flutter: #7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #8      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #9      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #10     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #12     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #14     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #16     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #17     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #18     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #20     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #21     List.forEach (dart:core/runtime/libgrowable_array.dart:274:8)
flutter: #22     SliverMultiBoxAdaptorElement.visitChildren (package:flutter/src/widgets/sliver.dart:889:36)
flutter: #23     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #24     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #25     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #26     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4734:16)
flutter: #27     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #29     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #30     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #31     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #32     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #33     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #34     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #35     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #36     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #37     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #39     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #41     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #42     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #43     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #45     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #46     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #47     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #48     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #49     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #51     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #53     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #54     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4734:16)
flutter: #55     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #56     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #57     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #59     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #60     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #61     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #62     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4734:16)
flutter: #63     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #65     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #66     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #67     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #69     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #70     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #71     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #72     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #73     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #74     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #75     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #77     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #78     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #79     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #81     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #82     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #83     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #84     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #85     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #87     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #88     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #89     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #90     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #91     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #92     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #93     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #94     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #95     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #96     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4734:16)
flutter: #97     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #98     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #99     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #100    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #101    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #102    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #103    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #104    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #105    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #106    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #107    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #108    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #109    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #111    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #112    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #113    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #114    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #115    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #116    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #117    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #118    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #119    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #120    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #121    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #122    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #123    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #124    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #125    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #126    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4634:14)
flutter: #127    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #128    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #129    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #130    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #131    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #132    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3668:14)
flutter: #133    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1709:13)
flutter: #134    _InactiveElements.add (package:flutter/src/widgets/framework.dart:1718:7)
flutter: #135    Element.deactivateChild (package:flutter/src/widgets/framework.dart:2935:29)
flutter: #136    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4464:11)
flutter: #137    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4761:17)
flutter: #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
flutter: #139    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
flutter: #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
flutter: #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
flutter: #142    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
flutter: #143    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2234:33)
flutter: #144    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
flutter: #145    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #146    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #147    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #148    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #149    _invoke (dart:ui/hooks.dart:120:13)
flutter: #150    _drawFrame (dart:ui/hooks.dart:109:3)
flutter: (elided 2 frames from class _AssertionError)
```

**Comment by HansMuller** [comment]
Sorry, that should happen! Will look into it.

**Comment by HansMuller** [comment]
I haven't been able to reproduce the failure mode your'e seeing. 

This is an example of what I assume you're trying to do: https://gist.github.com/HansMuller/721b827a6c0300e2d57e86a65f599377

Perhaps you could tweak the example to reproduce the bug?

**Comment by trK54Ylmz** [comment]
I deleted the application from my iPhone, upgraded Flutter to newer version (v0.4.3). After than I built the application with newer version, installed again to device and seems problem solved.

Could you please give me more detail about the bug?

Thanks.

**Comment by maxchehab** [comment]
An update,

I have found that this effect I am trying to disable is called a Glow instead of a Splash. To fix this issue I have added a property `final bool showGlow` to the `ThemeData` class. In `Scrollable` I determine to show the glow if the theme's showGlow is true.

I will submit a PR if that's fine with you.

@HansMuller

**Comment by Hixie** [comment]
If you just want to disable the Android glow effect, there are various ways to do it, depending on what you want on iOS (which bounces instead of glowing); you can provide an alternative Physics which doesn't overscroll, or you can provide an alternative viewport chrome. In either case, you do it by providing a custom ScrollBehavior widget.

**Comment by maxchehab** [comment]
@Hixie Thank you. I had no idea that SchrollPhysics or ScrollBehavior influences the glow. I have already submitted my [PR](https://github.com/flutter/flutter/pull/18003). Should I remove it?

**Comment by Hixie** [comment]
If `ScrollBehavior` solves your problem, then yeah, let's not land the `showGlow` patch, since we want to avoid having multiple solutions to one problem (more code = more slow!). Thanks for the contribution though!

**Comment by monting** [comment]
I'm looking to disable the splash effect.

@HansMuller I'm running your gist: https://gist.github.com/HansMuller/721b827a6c0300e2d57e86a65f599377
and getting a similar `'package:flutter/src/material/material.dart': Failed assertion: line 432 pos 12: '_inkFeatures != null': is not true.` exception as @trK54Ylmz 

Steps to reproduce: 
- Load app using `flutter run`
- Click on "Push TextField Page" button
- Click to focus on the first TextField (the one with NoSplashFactory)
- Click the back button

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.24.0)
[✓] Connected devices (1 available)
```

**Comment by eoinfogarty** [comment]
I am also looking to disable splash across the app as a whole.
If we set the `NoSplashFactory` as part of the theme.

``` dart
   void main() {
    runApp(
      MaterialApp(
        theme: ThemeData(
          splashFactory: const NoSplashFactory(),
        ),
        home: HomePage(),
      ),
    );
  }
```

I get the same error : 
`'package:flutter/src/material/material.dart': Failed assertion: line 432 pos 12: '_inkFeatures != null': is not true.`

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.4 17E202, locale en-JP)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] Android Studio (version 3.1)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)
```

I have difficulty reproducing it consistently.
It mostly seems to happen when navigating from on page to another.

In the meantime I am using this workaround of setting the splashColor to transparent
``` dart
 theme: ThemeData(
     splashColor: Colors.transparent,
)
```

**Comment by HansMuller** [comment]
I was able to reproduce the bug just now (per the report from @monting).

**Pull request closed without merging**
