### PR TITLE
[Material 3] Chips showCheckmark from theme being ignored #119163

### LINKED ISSUE #119163: `RawChip` doesn't use `ChipThemeData.showCheckmark` value
## Use case

Hello 👋 
While using the new m3 chips, it looks like the RawChip widget itself ignores the `showCheckmark` from the themes, because its instance value (priority) has a default `= true` on the constructor.

So whenever I wanted to use a `RawChip(...)`, I would have to `RawChip(showCheckmark: null, ...)` instead, so it fallbacks to the theme value.

> My current flutter version (beta channel)
```
Flutter 3.7.0-1.4.pre • channel beta • git@github.com:flutter/flutter.git
Framework • revision 686fe913dc (2 weeks ago) • 2023-01-10 16:14:01 -0800
Engine • revision ac5c83dd5f
Tools • Dart 2.19.0 (build 2.19.0-444.4.beta) • DevTools 2.20.0
```

## Proposal

A simple proposal would be [removing the default constructor value](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/chip.dart#L758) since the property is already nullable.

Also, ChoiceChip particularly will always override the showCheckmark with the [`theme.isMaterial3`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/choice_chip.dart#L159), rather than having it defined on its [internal default variation theme](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/choice_chip.dart#L197).

---

Not sure if this is better to be a separate issue but I would also love to be able to insert a [custom constraint property](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/chip.dart#L1288-L1308), either on the theme or instance.

### LINKED ISSUE #124662: When using Material 3, the ChoiceChip check mark cannot be hidden.
I have looked into the implementation of ChoiceChip, and it appears that it does not implement CheckmarkableChipAttributes like FilterChip does.

## Steps to Reproduce

1. Set the userMaterial3 property of ThemeData to true.
2. To add the ChoiceChip widget to the project
3.  ChoiceChip widget does not have a showCheckmark property, so the check mark in the widget will always be displayed.

**Expected results:** 
screenshot2

**Actual results:** 
screenshot2

<details>
<summary>Code sample</summary>

```dart
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';

/// Flutter code sample for [ActionChoice].

void main() => runApp(const ChipApp());

class ChipApp extends StatelessWidget {
  const ChipApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(colorSchemeSeed: const Color(0xff6750a4), useMaterial3: true),
      home: const ActionChoiceExample(),
    );
  }
}

class ActionChoiceExample extends StatefulWidget {
  const ActionChoiceExample({super.key});

  @override
  State<ActionChoiceExample> createState() => _ActionChoiceExampleState();
}

class _ActionChoiceExampleState extends State<ActionChoiceExample> {
  int? _value = 1;

  @override
  Widget build(BuildContext context) {
    final TextTheme textTheme = Theme.of(context).textTheme;

    return Scaffold(
      appBar: AppBar(
        title: const Text('ActionChoice Sample'),
      ),
      body: Center(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('Choose an item', style: textTheme.labelLarge),
            const SizedBox(height: 10.0),
            Wrap(
              spacing: 5.0,
              children: List<Widget>.generate(
                3,
                (int index) {
                  return ChoiceChip(
                    label: Text('Item $index'),
                    // showCheckmark: false,
                    selected: _value == index,
                    onSelected: (bool selected) {
                      setState(() {
                        _value = selected ? index : null;
                      });
                    },
                  );
                },
              ).toList(),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

### PR DESCRIPTION
**Pull request by GayathrideviGA**
M3 chips, it looks like the RawChip widget itself ignores the showCheckmark from the themes, because its instance value (priority) has a default = true on the constructor.

Previously, the checkmark in the ChoiceChip component was not being hidden when using Material 3. 

To address this issue, we have added two new parameters to the ChoiceChip component. The first parameter, showCheckMark, allows us to hide or show the checkmark based on true/false conditions. The second parameter, checkMarkColor, provides the ability to customize the colour of the checkmark displayed.
With these changes, the ChoiceChip component now works as expected with Material 3, and provides greater flexibility and control over the display of the checkmark.

Fixes #119163 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by GayathrideviGA** [comment]
> It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need [an exemption](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests) to this rule, contact Hixie on the #hackers channel in [Chat](https://github.com/flutter/flutter/wiki/Chat) (don't just cc him here, he won't see it! _He's on Discord!_).
> 
> If you are not sure if you need tests, consider this rule of thumb: the purpose of a test is to make sure someone doesn't accidentally revert the fix. Ask yourself, **is there anything in your PR that you feel it is important we not accidentally revert back to how it was before your fix?**
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.

TestCases Added for the Changes Done.

**Comment by GayathrideviGA** [comment]
@huycozy @guidezpl
How can I resolve the six test failures mentioned above?

**Comment by GayathrideviGA** [comment]
@huycozy @guidezpl Resolved: Need review

**Comment by 9oya** [comment]
@GayathrideviGA I already added this [PR](https://github.com/flutter/flutter/pull/124743) which includes widget tests and related docs.

**Pull request closed without merging**
