### PR TITLE
Fix `TabBar` label color for Material 3

### LINKED ISSUE #103642: `AppBar` with a `TabBar` doesn't use appropriate tab label color
## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. View application in light theme

**Expected results:**

1. TabBar icons should use a contrasting color with the appbar background so they are visible
2. When a child TabBarView is scrolled under the AppBar, the AppBar should raise its elevation and use its tint color. This works when the child is _not_ a TabBarView

**Actual results:**

With Material 3 enabled on a light theme, the AppBar:

1. Defaults to a white icon on a white background
2. Does not change its elevation or tint, so it's difficult to see that something has scrolled under it.

**Code sample**

DartPad example here: https://dartpad.dev/?id=ce15440e9376bd9944e6a53350ff4f70

This is a modification of one of the TabBar examples from the official docs. For some reason, DartPad seems to hang/crash when attempting to scroll the first tab, but it reproduces just fine on an Android emulator.

Light mode:
image

Things are pretty okay in dark mode:
image

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/103642

`TabBar` label colors using `ColorScheme.onSurface` for Material 3.
| Bug | Fix |
| --------------- | --------------- |
|  |  |

Using `bodyMedium` text style for Material 3. 
As when using Material 3, `bodyText1` points to `bodyLarge` which is a bigger font, as explained here in a test 
https://github.com/flutter/flutter/issues/102121#issuecomment-1103036850

Screenshot 2022-05-13 at 14 46 42

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by guidezpl — CHANGES_REQUESTED** [review]
These should use tokens, e.g. and `md.comp.primary-navigation-tab.with-label-text.active.label-text.color` `md.comp.primary-navigation-tab.with-label-text.label-text.font`

**Comment by TahaTesser** [comment]
> These should use tokens, e.g. and md.comp.primary-navigation-tab.with-label-text.active.label-text.color md.comp.primary-navigation-tab.with-label-text.label-text.font

Thanks! Though I don't find these tokens in https://github.com/flutter/flutter/tree/master/dev/tools/gen_defaults/data. 
I'll update this when these tokens are added.

**Comment by wanchana322** [comment]
wanchana

ในวันที่ ศ. 3 มิ.ย. 2022 13:09 น. Pierre-Louis ***@***.***>
เขียนว่า:

**Comment by TahaTesser** [comment]
cc: @darrenaustin @guidezpl @HansMuller 
We need either mentioned tokens to land this PR sooner or land this now and update this code with tokens later since currently simply enabling Material 3 **breaks** `TabBar` colors.

# Steps to reproduce
1. Test code sample from https://api.flutter.dev/flutter/material/TabBar-class.html  with  `theme: ThemeData(useMaterial3: true),`

Result:
Screenshot 2022-06-20 at 15 32 04

**Comment by guidezpl** [comment]
@darrenaustin Could you add the required tokens (they're available)?

**Comment by darrenaustin** [comment]
> @darrenaustin Could you add the required tokens (they're available)?

I am waiting for another token update to land.  Once it has I will add this with some newer component tokens as well.

**Comment by TahaTesser** [comment]
> I am waiting for another token update to land. Once it has I will add this with some newer component tokens as well.

Since we're waiting for tokens and this will be addressed with a wider scope by adding newer components as well by Darren Austin.


I feel safe closing this small PR.

**Comment by darrenaustin** [comment]
FYI, @QuncCccccc just landed the tokens for this today in #111913.

**Comment by TahaTesser** [comment]
> FYI, @QuncCccccc just landed the tokens for this today in https://github.com/flutter/flutter/pull/111913.

Awesome! Taking a look.

**Pull request closed without merging**
