### PR TITLE
Reland "Upgrade Gradle and AGP versions to 7.5/7.2 and migrate benchmarks+examples" #108355

### PR DESCRIPTION
**Pull request by GaryQian**
Relands #108355, previous version missed updating lockfiles for `benchmarks/platform_views_layout` due to v1 embedding warning.

### CODE REVIEW

**Comment by GaryQian** [comment]
One more time, Hopefully it sticks this time. Verified all lockfiles are in place for every project changed.

**Review by zanderso — APPROVED** [review]
rslgtm 🤞🏻

**Review by christopherfujino — APPROVED** [review]
RSLGTM

**Comment by zanderso** [comment]
Looks like this is breaking the tree again.

**Comment by Piinks** [comment]
@zanderso is quicker on the draw again! 😛

**Comment by GaryQian** [comment]
Is there a good way to run all the postsubmit tests in a PR on CI? I'd like to avoid more PR bouncing if possible

**Comment by zanderso** [comment]
> Is there a good way to run all the postsubmit tests in a PR on CI? I'd like to avoid more PR bouncing if possible

I believe this is difficult and requires a bunch of infra changes to understand the branch you want to test, but cc @keyonghan just in case he can suggest an easy way.

**Comment by christopherfujino** [comment]
> Is there a good way to run all the postsubmit tests in a PR on CI? I'd like to avoid more PR bouncing if possible

I remember implementing the flag `--match-host-platform` to try to do this: https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/run.dart#L295, not sure if it has bit rotted though, it doesn't get run on CI.

**Comment by keyonghan** [comment]
> > Is there a good way to run all the postsubmit tests in a PR on CI? I'd like to avoid more PR bouncing if possible
> 
> I believe this is difficult and requires a bunch of infra changes to understand the branch you want to test, but cc @keyonghan just in case he can suggest an easy way.

That is true. I would suggest `LED` runs. A simple shell script to loop through all android targets, for which you need to change the `git_url` and `git_ref` to point to your PR (https://cs.opensource.google/flutter/recipes/+/main:recipes/devicelab/devicelab_drone.py;l=51).
As for the led command in the loop, here is a quick command
```
led get-builder "luci.flutter.prod:<Builder Name>” | led edit-system -p 40 | led edit-recipe-bundle | led launch
```
You may want to run this with a lower priority (40) to avoid affecting PROD queue time.

**Pull request merged**
