### PR TITLE
Add debug logging to deferred components test for deflaking

### PR DESCRIPTION
**Pull request by GaryQian**
https://github.com/flutter/flutter/issues/101609 Tracks flakes in deferred components build tests.

This adds logging to obtain better information on what is happening.

### CODE REVIEW

**Review by keyonghan — APPROVED** [review]
LGTM

**Review by christopherfujino — COMMENTED** [review]
Can you use `printOnFailure` instead? https://pub.dev/documentation/test_api/latest/test_api.scaffolding/printOnFailure.html

**Comment by GaryQian** [comment]
Ahh! I didn't know about `printOnFailure`, thanks!

**Comment by christopherfujino** [comment]
> Ahh! I didn't know about `printOnFailure`, thanks!

Took a while of searching for me to remember the name :)

**Pull request merged**
