### PR TITLE
Roll engine to bb323c145cf9e443636af777888ea8f3d7c1c9eb

### PR DESCRIPTION
**Pull request by amirh**
```bb323c145 Revert "Roll src/third_party/skia 9e0d7e4072e4..297c3c8e85bd (62 commits) (#5802)" (#5803)
0bf69f02d Roll src/third_party/skia 9e0d7e4072e4..297c3c8e85bd (62 commits) (#5802)
5d0e13a45 Fix starting isolate directly from CoreJIT snapshot. (#5798)
09ff9493e Re-land removal of vmservice_io from release builds. (#5784)
b523ee847 Revert "Switch to Fuchsia's ICU (#5774)" (#5801)
69695493b Switch to Fuchsia's ICU (#5774)
55b423f07 Ensure assistiveTechnologyEnabled is initialized when the android view is set up (#5793)
3054f3183 Add touch events to the platform views method channel API. (#5796)
91c16af0c Revert "Roll Dart to 937ee2e8ca4b76499e24cd463f07bfb736bccd74. (#5745)" (#5799)
1a66f895b Roll Dart to 937ee2e8ca4b76499e24cd463f07bfb736bccd74. (#5745)
8d046a727 Revert "Roll src/third_party/skia 9e0d7e4072e4..8f8bf8880d9d (32 commits) (#5794)" (#5797)
e8d172cf3 Revert "Fix Dart 2 reload when running from a snapshot instead of platform.dill. (#5792)" (#5795)
624cf7e25 Fix Dart 2 reload when running from a snapshot instead of platform.dill. (#5792)
16da4710d Roll src/third_party/skia 9e0d7e4072e4..8f8bf8880d9d (32 commits) (#5794)
3fe63fd5d Add presubmit check for engine to flutter roll (#5790)
```

### CODE REVIEW

**Review by liyuqian — APPROVED** [review]
Nit: please change the PR description to something like `git rev-list 5557e3006e8346b2d3cccf3fa68859a00947641f..bb323c145cf9e443636af777888ea8f3d7c1c9eb --oneline` so we know which commits in the engine are rolled.

**Comment by amirh** [comment]
Good idea! done.

**Comment by jonahwilliams** [comment]
TIL about git rev-list

**Review by goderbauer — APPROVED** [review]
Lgtm

**Comment by amirh** [comment]
Closing this as @rmacnak-google is rolling in #19569

**Pull request closed without merging**
