### PR TITLE
Add C++ code generation for key maps.

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This adds generation of some C++ keycode maps for various platforms.

This isn't meant for general use: it's so that the Flutter authors can keep the keycodes up to date with the Chromium and Android (and other) sources. It doesn't run continuously, it's only run occasionally (manually) to update the maps, because they don't change very often, and there is often manual work needed to make it function.

In this PR, I added output of various `.cc` files that write into an engine repo situated next to the flutter repo on disk.  This is a starting point for implementing platform-side handling of key events.

It is related to the work in https://github.com/gspencergoog/platform_keyboard which will form the basis for the framework-side changes to keyboard handling.

## Related Issues

- https://github.com/flutter/flutter/issues/33521
- https://github.com/flutter/flutter/issues/47156

### CODE REVIEW

**Comment by goderbauer** [comment]
(triage fly-by comment): Looks like the analyzer is unhappy.

**Comment by gspencergoog** [comment]
Fixed (I hope).

**Comment by gspencergoog** [comment]
@franciscojma86 the CLA bot really doesn't like when two people have changes in the same PR.  Just send me diffs if need be, and I'll apply them, or if you want, you can take over this change and make your own PR and I'll abandon this one.

**Comment by franciscojma86** [comment]
Ah sorry I just saw your message. That was the last one!

**Comment by gspencergoog** [comment]
Did you just do two just now, or more?  I hope I didn't just force-push over your changes...

**Review by franciscojma86 — APPROVED** [review]

**Comment by franciscojma86** [comment]
Seems like my changes are still in.

**Pull request merged**
