### PR TITLE
Added the machine's architecture to macos doctor results.

### PR DESCRIPTION
**Pull request by gaaclarke**
## Description

Now that apple supports multiple architectures I added the architecture to the flutter doctor output to help us track down bugs related to architecture.

## Related Issues

https://github.com/flutter/flutter/issues/65976

## Tests

none

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
Change seems reasonable, tests pls

**Review by jonahwilliams — COMMENTED** [review]
The tests for this class are in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/base/os_test.dart

You can use the FakePlatform/FakeProcessManager to set things up to be consistent across platforms:

**Review by jmagman — DISMISSED** [review]
I think this needs to be a bigger change, piping through a new `TargetPlatform` everywhere

Really, this shouldn't be hardcoded:
https://github.com/flutter/flutter/blob/9f040865c92a4c1dc37744248436f98c14b85cad/packages/flutter_tools/lib/src/macos/macos_device.dart#L44

**Comment by jmagman** [comment]
Oh I see, this isn't for a target device, it's for this output:
```
[✓] Flutter (Channel unknown, 1.22.0-10.0.pre.212, on Mac OS X 10.15.5 19F101, locale en-US)
```

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
