### PR TITLE
Introduce syntactic sugar for creating custom State subclasses

### PR DESCRIPTION
**Pull request by krisgiesing**

### CODE REVIEW

**Comment by krisgiesing** [comment]
@abarth @Hixie - this is an idea I had to reduce some boilerplate in our examples.  If this looks like a good idea I can convert the others.

Also feel free to bikeshed the name.

**Comment by abarth** [comment]
LGTM but I suspect @Hixie won't like the name.  He's generally against "simple" in names.  ;)

ConfigurationlessStatefulWidget ?

**Comment by krisgiesing** [comment]
I'm not super fond of the current name either.  I am kind of hoping we can come up with something short, since the point is to allow authors to be more terse.

Maybe StateCreatorWidget?

**Comment by Hixie** [comment]
`StatefulWidget.withoutConfiguration()` ?

I'm a little suspicious of having people pass in a closure that returns a State because I think it'll encourage people to do weird things like cache a precreated State to return or something.

I'm surprised that this is all that common. I suspect that this is mostly something we'd see for the root stateful widget of an app or app page, and in demos. It's possible we should restructure existing code that does this to use a different pattern (e.g. having the root widget pass stateless app page widgets configuration, instead of the latter being stateful).

**Comment by krisgiesing** [comment]
I almost called this class "StatefulApp", but it seemed confusing to have it next to MaterialApp and WidgetsApp. In our examples it's used to handle the top level navigator route, which is usually the only route.

I'm open to alternative suggestions, although I don't quite follow your the last part of your comment. Perhaps you mean that MaterialApp/WidgetsApp would take a State constructor of some kind and then pass it down to the navigator routes as context?

I do think we could have a better idiom here. Several people on the discussion lists have mentioned that it seems more complex than necessary to create the state required to run a basic data-driven app.

**Comment by krisgiesing** [comment]
`StatefulWidget.withoutConfiguration` seems like a reasonable approach. I'm thinking that would entail creating a more lengthy-named class instance and returning that, rather than adding the logic in question here to the base class?

**Comment by Hixie** [comment]
Elaborating on my last comment:

This is only necessary for those cases where a Widget has no configuration. But how common is that? When is an application going to always display the same thing without any chance of it displaying something else? Does it only happen in artificial examples? Can we restructure the code so that it doesn't happen in those cases?

One example would be if an app with some basic state has a page with some basic state. Should we restructure the app so that all the state is in one of those widgets, and make the other one stateless, with the relevant bits passed down as configuration?

**Comment by krisgiesing** [comment]
After talking with Ian, there are several possible solutions here, and the right one depends on data we don't really have yet. If this is limited to only the top level state for applications, then developers probably will encounter this rarely and the need for a shorthand is diminished. If on the other hand this happens frequently when defining routes/pages, then there's a broader need, and the shorthand we develop should take this into account.

So I'm going to close this PR for now but we should keep an eye on this as we get more information on actual use.

**Pull request closed without merging**
