### PR TITLE
Add Windows and Linux support to the 'layers' example

### PR DESCRIPTION
**Pull request by loic-sharma**
Enables running the `layers` example on Linux and Windows.

Part of https://github.com/flutter/flutter/issues/126033

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Review by yaakovschectman — APPROVED** [review]

**Comment by Hixie** [comment]
Don't we want to verify that these actually run on Linux?

**Comment by loic-sharma** [comment]
@Hixie AFAIK there are no existing tests that run the `layers` app. However, the `Windows build_tests` and `Linux build_tests` will now verify that the `layers` app builds on their respective platforms ([here](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8781904900248469777/+/u/run_test.dart_for_framework_tests_shard_and_subshard_misc/test_stdout) and [here](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8781993405289547969/+/u/run_test.dart_for_build_tests_shard_and_subshard_2_3/test_stdout)). Also, the `layers` app's unit tests are already ran by `Windows framework_tests_misc` and `Linux framework_tests_misc`.

**Comment by Hixie** [comment]
test-exempt: is tested (as described above)

**Pull request merged**
