### PR TITLE
Update outdated runners in the integration_tests

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This PR updates the platform runners in the integration_tests subdir.

I've attempted to replace the entire group with new code as if the project were recreated with `flutter create` so that they don't become a Frankenstein of minor changes to make it work again, but just plain old generated code that can be replaced and updated in place.

## Tests
 - No tests because we're just updating boilerplate here.

## Related Issues
 - https://github.com/flutter/flutter/issues/91325

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: refactor with no semantic change (applying new boilerplate)

**Comment by gspencergoog** [comment]
@blasten Should I be checking in the lockfiles themselves after running `generate_gradle_lockfiles.dart`? (e.g. `dev/integration_tests/external_ui/android/buildscript-gradle.lockfile`)

**Comment by gspencergoog** [comment]
Closing so @blasten can take over landing this.

**Comment by Hixie** [comment]
Is there a new PR replacing this one? (Asking on behalf of future archeologists following links from `test.dart`...)

**Comment by gspencergoog** [comment]
No, it appears that this was never actually landed.

**Comment by pdblasi-google** [comment]
@gspencergoog 
I am a future archeologist from `test.dart`!

As this PR was closed and a different PR wasn't created/landed, is there an issue that would be better to point to in the `test.dart` file?

**Comment by gspencergoog** [comment]
No, there was never an issue filed for this.  I'll make one.

**Comment by gspencergoog** [comment]
Here's the filed issue.  Haven't updated the comment in test.dart yet.

https://github.com/flutter/flutter/issues/113782

**Comment by pdblasi-google** [comment]
If you'd like, I can update the comment while I'm in the area.

**Comment by gspencergoog** [comment]
Sure, that would be great.

**Comment by pdblasi-google** [comment]
Alright, the comment should be updated when #113784 is merged.

**Pull request closed without merging**
