### PR TITLE
Fix the issue of TextSelection could misbehave inside a Nested Overlay

### LINKED ISSUE #43787: TextSelection could misbehave inside a Nested Overlay
The following code can show a couple of problems with the TextSelection on Android.

```dart
import 'package:flutter/material.dart';

class TextSelectionHomePage extends StatefulWidget {
  _TextSelectionHomePageSate createState() => _TextSelectionHomePageSate();
}

class _TextSelectionHomePageSate extends State<TextSelectionHomePage> {

  TextEditingController _controller;
  @override
  void initState() {
    _controller = TextEditingController(
      text: "This is a test that shows some odd behavior with Text Selection!"
    );

    super.initState();
  }

  @override
  void dispose() {
    _controller.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    Overlay overlay = Overlay(
      initialEntries: [
        OverlayEntry(
          builder: (context) => Center(
              child: TextField(controller: _controller),
          )
        )
      ],
    );

    return Scaffold(
        body: Container(
          color: Colors.grey,
          child: Center(
              child: Container(
                  color: Colors.red,
                  width: 300,
                  height: 600,
                  child: overlay
              )
          ),
        )
    );
  }
}
```

A nested overlay could be desirable for certain reasons, but the TextSelection on Android doesn't do very well with it.
If the overlay's width isn't as wide as what the TextSelection toolbar needs, an overflow can be seen. Also, as you move the cursor around while changing the selection size, the toolbar moves around on the screen as well, which feels weird. Finally, if a ClipRect is placed around the nested overlay, then the Toolbar gets cut off.

Could the TextSelection just use the navigator's overlay instead of the nearest overlay in the tree?

Here is a screenshot of the behavior I'm seeing.

text_selection_overlay

### PR DESCRIPTION
**Pull request by shihchanghsiungsonos**
## Description

Fix the issue by using the root overlay.

## Related Issues
fixes https://github.com/flutter/flutter/issues/43787

## Tests

I added the following tests:

Add a new testWidget 'The selection menu displays in an Overlay without error'

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
text_field_test has trailing whitespace

**Comment by shihchanghsiungsonos** [comment]
> text_field_test has trailing whitespace

Thanks, @dnfield. Will double check.

**Comment by dnfield** [comment]
Analyzer is still unhappy with the tests - need to specify type annotations.

**Comment by shihchanghsiungsonos** [comment]
> Analyzer is still unhappy with the tests - need to specify type annotations.

Thanks, will fix them.

**Review by justinmc — APPROVED** [review]
Just chiming in with **LGTM** since I had in the previous PR https://github.com/flutter/flutter/pull/44018

**Comment by dnfield** [comment]
I think this might have to be manually landed.  I suspect the Skia gold failure is due to you being a first time contributor.  /cc @Piinks 
Filed https://github.com/flutter/flutter/issues/49304

**Comment by shihchanghsiungsonos** [comment]
> I think this might have to be manually landed. I suspect the Skia gold failure is due to you being a first time contributor. /cc @Piinks
> Filed #49304

Ah, thanks!

**Comment by Piinks** [comment]
Hi @shihchanghsiungsonos welcome! :tada:
This shouldn't require any special conditions to land. The contributor access @dnfield mentioned was an old issue. I'm monitoring to see if it flakes again. :)

**Comment by Piinks** [comment]
The check is still running, the status just hasn't updated. 🕐

**Comment by shihchanghsiungsonos** [comment]
> The check is still running, the status just hasn't updated. 🕐

Thanks @Piinks !

**Comment by shihchanghsiungsonos** [comment]
@dnfield thanks a lot for the help to get this one done :)

**Pull request merged**
