### PR TITLE
i127682 android api 33 test support

### PR DESCRIPTION
**Pull request by reidbaker**
- try to set emulator to version 33 to see what happens

#127682

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Comment by reidbaker** [comment]
This is blocked by finding the CIPD entry for android_virtual_device.

**Comment by reidbaker** [comment]
> This is blocked by finding the CIPD entry for android_virtual_device.

Resolved by 
https://flutter-review.googlesource.com/c/recipes/+/45049

**Review by dnfield — APPROVED** [review]

**Comment by reidbaker** [comment]
https://firebase.corp.google.com/project/flutter-infra-staging/testlab/histories/bh.554c4369930daa2b/matrices/5087782873511167545/executions/bs.4d54083875c6b448
```
Failed to finalize session : INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl740390724.tmp/base.apk (at Binary XML file line #27): com.example.release_smoke_test.MainActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present
```

**Comment by dnfield** [comment]
In the AndroidManifest.xml for hello_world you need to add that attribute. Grep the repo and you'll see other examples of it.

**Comment by dnfield** [comment]
e.g. https://github.com/flutter/flutter/blob/main/dev/benchmarks/complex_layout/android/app/src/main/AndroidManifest.xml#L11

**Pull request merged**
