### PR TITLE
Benchmark cannot run in Android12 phone

### PR DESCRIPTION
**Pull request by JsouLiang**
connect issue https://github.com/flutter/flutter/issues/100760

### CODE REVIEW

**Review by dnfield — APPROVED** [review]

**Comment by dnfield** [comment]
The latest templates have this but no one updated this one yet.  Thanks!

**Comment by JsouLiang** [comment]
@

**Comment by JsouLiang** [comment]
cc @blasten

**Review by eggfly — APPROVED** [review]
LGTM

**Pull request merged**
