### PR TITLE
Add review feedback to dartdocs

### PR DESCRIPTION
**Pull request by abarth**

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie as requested.

I didn't apply your comments about the date picker because I didn't know many of the answers.

**Comment by abarth** [comment]
I'm going to land this TBR to avoid more merge conflicts.  Happy to continue iterating on these docs if you have more feedback.

**Comment by Hixie** [comment]
LGTM

**Comment by eseidelGoogle** [comment]
FYI @qchong

**Pull request merged**
