### PR TITLE
Update macOS gallery display name

### PR DESCRIPTION
**Pull request by jmagman**
Update name of app from `flutter_gallery` to `Flutter Gallery`.  Also update copyright.

See window title:
Screen Shot 2022-10-18 at 12 24 01 PM

Screen Shot 2022-10-18 at 12 23 11 PM

Now that it's called "Flutter Gallery", also turn on the `hot_mode_dev_cycle_macos_target__benchmark` check that validates the process with that name is properly killed on `q`, introduced in #113581.  It's passing: https://ci.chromium.org/p/flutter/builders/try/Mac_ios%20hot_mode_dev_cycle_macos_target__benchmark/3628

https://github.com/flutter/flutter/blob/92df0264036df2b2d4a243aac1b147c1ebdab0fb/dev/devicelab/lib/tasks/hot_mode_tests.dart#L277-L280

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by guidezpl** [comment]
small suggestion to rename to "old Flutter Gallery" to help with the confusion between the integration test version and the public version

**Comment by jmagman** [comment]
> small suggestion to rename to "old Flutter Gallery" to help with the confusion between the integration test version and the public version

That doesn't match with the other platforms.  We call the other one "new" Flutter Gallery in most places.  I don't like either name since it doesn't scale for the inevitable third gallery.

**Review by a-wallen — APPROVED** [review]

**Comment by guidezpl** [comment]
Fair, I'm putting my foot down at `new_new_gallery`

**Comment by jmagman** [comment]
> Fair, I'm putting my foot down at `new_new_gallery`

Or lean into the confidence of `newest_gallery` assuming there will never be another 💪

**Pull request merged**
