### PR TITLE
Support some new Dart features in AOT mode

### PR DESCRIPTION
**Pull request by jason-simmons**
See https://github.com/flutter/flutter/issues/7579

### CODE REVIEW

**Comment by jason-simmons** [comment]
@abarth

**Comment by abarth** [comment]
LGTM

**Comment by tvolkert** [comment]
Do these flags work in DBC mode as well?  The PR title says in AOT mode, but they're being added in debug mode on iOS devices.

Also, is the fact that they're first among flags significant?

(I'm asking because I need to port this to Google's internal build system)

**Comment by abarth** [comment]
> Do these flags work in DBC mode as well?

They should.

> Also, is the fact that they're first among flags significant?

Nope.

**Pull request merged**
