### PR TITLE
Making Atom show a lot less errors

### PR DESCRIPTION
**Pull request by domesticmouse**
Dropped from ~120 errors to 2 when editing the flutter_gallery sample app in Atom.io

### CODE REVIEW

**Comment by abarth** [comment]
You're probably using an old version of the Dart SDK.  We recommend configuring Atom to use the version of the Dart SDK in `flutter/bin/cache/dart-sdk`.

In particular, these trailing commas are now allowed in the Dart language (and they make dartfmt produce prettier code in these cases).

**Comment by domesticmouse** [comment]
The `dart` version for the `flutter/bin/cache/dart-sdk` is `Dart VM version: 1.20.0-dev.10.2 (Wed Oct 12 10:35:48 2016) on "macos_x64"`, but my brew installed dart version is `Dart VM version: 1.19.1 (Wed Sep  7 08:59:17 2016) on "macos_x64"`, which is the one I assume Atom is using to run the analysis from?

**Comment by abarth** [comment]
If you look at the plugin settings for the dartlang plugin in Atom, it will tell you which one it is using.

**Comment by domesticmouse** [comment]
Would you believe Atom was using a 1.17 version of dart? Sorry for the noise!

**Comment by abarth** [comment]
Ah!  Yeah, I thought we had waited until trailing commas were in the stable version of the SDK before using them.  Thanks for digging into the issue.

**Comment by domesticmouse** [comment]
I can confirm everything is happy, now that Atom is configured to use the `flutter/bin/cache/dart-sdk` with a fresh checkout of flutter.

**Comment by Hixie** [comment]
Does `flutter doctor` check whether the IDEs are configured to use the right Dart SDK?

**Comment by domesticmouse** [comment]
@Hixie as yet, no. Want me to raise a FR somewhere?

**Comment by Hixie** [comment]
Yes please! That would be a good thing to catch. Thanks!

**Pull request closed without merging**
