### PR TITLE
Update stack_trace.dart

### PR DESCRIPTION
**Pull request by dnfield**
Dart roll containing Object.hash is messing this up.

This seems like a bug in the analyzer - @bwilkerson or @pq might know

### CODE REVIEW

**Comment by dnfield** [comment]
Failures start in https://github.com/flutter/flutter/pull/85354

**Comment by Hixie** [comment]
test-exempt: only affects comments (heh)

**Review by jason-simmons — APPROVED** [review]

**Comment by dnfield** [comment]
Screenshot from VSCode analyzer output:

image

You can see there that the analyzer somehow thinks this is trying to override `Object.hash`. But I can't reproduce this in a smaller project for some reason.

**Comment by dnfield** [comment]
Filed https://github.com/dart-lang/sdk/issues/46477

**Comment by dnfield** [comment]
Merging this to unblock the engine roller.

**Pull request merged**
