### PR TITLE
[flutter_releases] Flutter stable 2.10.3 Framework Cherrypicks

### PR DESCRIPTION
**Pull request by itsjustkevin**
# Flutter stable 2.10.3 Framework

## Scheduled Cherrypicks

- commit: 80660b2d5

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 36 new digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/99337

**Comment by christopherfujino** [comment]
We can safely skip the analysis test on release branches, i'll push a commit

**Comment by christopherfujino** [comment]
I just pushed a commit to skip the consumer deps test, analysis passes for me locally at that commit

**Comment by skia-gold** [comment]
Gold has detected about 25 new digest(s) on patchset 5.
View them at https://flutter-gold.skia.org/cl/github/99337

**Review by godofredoc — APPROVED** [review]

**Comment by fzyzcjy** [comment]
Hi I wonder when will 2.10.3 release? Seems that cp is merged, but I did not see anything from https://docs.flutter.dev/development/tools/sdk/releases?tab=macos yet

**Comment by godofredoc** [comment]
> Hi I wonder when will 2.10.3 release? Seems that cp is merged, but I did not see anything from https://docs.flutter.dev/development/tools/sdk/releases?tab=macos yet

The release has not been completed yet

**Comment by fzyzcjy** [comment]
@godofredoc Oops sorry. May I know when will it be completed?

**Comment by godofredoc** [comment]
It just completed!

**Comment by fzyzcjy** [comment]
🎉 

(btw I have just uninstalled VS 17.1 and start installing 17.0.6... What if I just postpone 20 minutes and then no need for such a reinstall)

**Pull request merged**
