### PR TITLE
[WIP] remove redundant non-null asserts

### LINKED ISSUE #85308: redundant non-null asserts should be removed
After Flutter migrated to Dart Null Safety (>=2.12.0), data types are non-nullable by default, and can be made nullable by adding the `?` operator. This makes non-null asserts for non-nullable variables redundant. There are many such asserts in the flutter package in functions and class constructors that can be removed.

Example:
```dart
void sampleFunction(int value) {
    assert(value != null); // This is redundant as value will never be null
    ...
}
```

### PR DESCRIPTION
**Pull request by werainkhatri**
Non-null asserts for non-nullable variables is redundant and should be removed.

fixes #85308 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by werainkhatri** [comment]
Should I remove doc comments that mention that a non-nullable argument should not be null?

**Review by Piinks — COMMENTED** [review]
Hi @werainkhatri I think these are left there intentionally for now as part of a migration period. I do not think we want to remove these now. Also, it appears several checks are failing in the current state of this PR.

**Comment by werainkhatri** [comment]
> Hi @werainkhatri I think these are left there intentionally for now as part of a migration period. I do not think we want to remove these now.

Oh! Okay. I'll leave the PR asof now.

> Also, it appears several checks are failing in the current state of this PR.

The analyze checks are failing due to a bug I found while removing asserts. I have fixed it in a different PR (#85414) which has been merged and will fix the checks. For the `customer_testing-linux` check, It's due to an improper rebase to the master, which I can fix, but may take time.

If this fix is supposed to be done by the team only, as you said it is a part of the migration, this PR can be closed.

**Comment by Piinks** [comment]
I think the customer check will be resolved when this lands: https://github.com/flutter/flutter/pull/86063
Confirming whether we are waiting on removing asserts, I'll update when I hear back. :)

**Comment by Piinks** [comment]
I confirmed with @gspencergoog that we don't want to do this right now as many packages and customers are still migrating. Thank you very much for the contribution though! At some point we will be making this change. :)

**Pull request closed without merging**
