### PR TITLE
Update dartdoc to 0.24.1

### PR DESCRIPTION
**Pull request by jcollins-g**
Release notes:  https://github.com/dart-lang/dartdoc/releases/tag/v0.24.1

No change to current warnings or doc output.  The most significant change is @gspencergoog 's fix of a bug I accidentally introduced where dartdoc won't hard fail even when errors are detected.

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by gspencergoog** [comment]
@fkorotkov, is the build problem [here](https://cirrus-ci.com/task/5120017395875840) a result of changing the Cirrus git client?  The target repo has a branch with the right name, so I'm not sure why git is failing to clone.

**Comment by gspencergoog** [comment]
Also, it's able to clone just fine on all the other platforms...

**Comment by fkorotkov** [comment]
@gspencergoog I don't see `dartdoc-0.24.1` branch at the moment. Maybe it got removed before macOS started executing?

**Comment by fkorotkov** [comment]
Wait. It's from a fork... Weird.

**Comment by gspencergoog** [comment]
Yeah, it's not a branch on the flutter repo, it's a branch on the fork.

**Comment by fkorotkov** [comment]
Wow. This is some big GitHub glitch. Here is the event that initialized the build (stripped some useless fields to make it more compact): 

```json
{
  "action": "requested",
  "check_suite": {
    "id": 20437609,
    "head_branch": "dartdoc-0.24.1",
    "head_sha": "8a8169be3c6ef96f1f8d19aff37ec98c76cf6824",
    "status": "queued",
    "conclusion": null,
    "url": "https://api.github.com/repos/flutter/flutter/check-suites/20437609",
    "before": "0000000000000000000000000000000000000000",
    "after": "8a8169be3c6ef96f1f8d19aff37ec98c76cf6824",
    "pull_requests": [

    ],
    "app": {
      "id": 3232,
      "node_id": "MDM6QXBwMzIzMg==",
      "owner": {
        "login": "cirruslabs",
        "id": 29414678,
        "type": "Organization",
        "site_admin": false
      },
      "name": "Cirrus CI",
    },
    "check_runs_url": "https://api.github.com/repos/flutter/flutter/check-suites/20437609/check-runs",
    "head_commit": {
      "id": "8a8169be3c6ef96f1f8d19aff37ec98c76cf6824",
      "tree_id": "224b8da7c3eec6c189d7b83f93aa68956983129a",
      "message": "Update dartdoc to 0.24.1",
      "author": {
        "name": "Janice Collins"
      },
      "committer": {
        "name": "Janice Collins"
      }
    }
  },
  "repository": {
    "id": 31792824,
    "name": "flutter",
    "full_name": "flutter/flutter",
    "private": false,
    "owner": {
      "login": "flutter",
      "id": 14101776,
      "type": "Organization",
      "site_admin": false
    },
    "fork": false,
    "clone_url": "https://github.com/flutter/flutter.git",
    "default_branch": "master"
  },
  "organization": {
    "login": "flutter",
    "id": 14101776
  },
  "sender": {
    "login": "jcollins-g",
  },
  "installation": {
    "id": 104037
  }
}
```

It's definitely states `"head_branch": "dartdoc-0.24.1"` and `"full_name": "flutter/flutter"` which makes it appear like this. And seems for a small period of time the ref actually worked since linux builds were able to clone it.

Reporting now to GitHub folks.

**Comment by fkorotkov** [comment]
@gspencergoog it's some crazy weird stuff. 😲

**Comment by jcollins-g** [comment]
@fkorotkov I didn't think about this earlier, but one possible source of the glitch is that I accidentally pushed my branch to the flutter/flutter repo due to a typo.  I then deleted the branch and uploaded it to my fork, which is where it is supposed to go.

It seems possible to me that GitHub might have a bug where if a branch of the same name is (or ever was?) present in the main repo it might give you that rather than the forked repo it is supposed to use...

**Comment by gspencergoog** [comment]
OK, I made a copy of this PR: https://github.com/flutter/flutter/pull/23275

The odd thing THERE is that _none_ of the CI is running on it, just the CLA/google check, WIP and the flutter-build check, no Cirrus checks.

**Comment by jcollins-g** [comment]
I am still unable to make the checks run for MacOS on this PR.   @fkorotkov, if it is helpful for your debugging I can leave this PR open, otherwise I intend to close it in favor of #23275.

**Comment by fkorotkov** [comment]
@jcollins-g I have one question though about you pushing here first and then to your fork. Did you update the PR to point to `jcollins-g:dartdoc-0.24.1` branch manually?

**Comment by jcollins-g** [comment]
@fkorotkov No.  All of the things I mentioned occurred before creating the PR.

**Comment by gspencergoog** [comment]
This was landed in another PR.

**Pull request closed without merging**
