### PR TITLE
Added size to stepper icons

### LINKED ISSUE #16920: Stepper Icons are too big
## Problem

`Stepper` Icons have no space between Icon itself and the circle.
In my opinion, it looks disturbing, especially for edit icon.
Drawing

## Solution

Changing this
```
case StepState.editing:
    return new Icon(
        Icons.edit,
        color: isDarkActive ? _kCircleActiveDark : _kCircleActiveLight,
    );
case StepState.complete:
    return new Icon(
        Icons.check,
        color: isDarkActive ? _kCircleActiveDark : _kCircleActiveLight,
    );
```
Into this:
```
case StepState.editing:
    return new Icon(
        Icons.edit,
        color: isDarkActive ? _kCircleActiveDark : _kCircleActiveLight,
        size: 18.0,
    );
case StepState.complete:
    return new Icon(
        Icons.check,
        color: isDarkActive ? _kCircleActiveDark : _kCircleActiveLight,
        size: 18.0,
    );
```
Would result in this:
Drawing

In [Material specs](https://material.io/guidelines/components/steppers.html#steppers-usage) there is no mention of icon size. Only that the circle should be 24dp.

Can we make this change? I can make a pull request.

### PR DESCRIPTION
**Pull request by MarcinusX**
Resolves #16920

### CODE REVIEW

**Comment by MarcinusX** [comment]
Hey, could someone rerun the pipeline? :) I guess that my PR shouldn't cause the timeouts :D

**Comment by Hixie** [comment]
This patch seems reasonable. It will need a test, though, to make sure we don't accidentally revert your fix!

If you update your PR with a test, it will automatically rerun all the bots which should fix your timeout issues.

**Comment by MarcinusX** [comment]
I've added tests :)  
I also added link to github issue so a person can know why was this test added. Is it ok?

**Comment by Hixie** [comment]
Looks great, thanks for your contribution!

**Pull request merged**
