### PR TITLE
Added support for vscode and vscode-insiders installed via Flatpak

### LINKED ISSUE #137122: VS Code installed via Flatpak is not detected by flutter tool
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Install [VS Code](https://flathub.org/apps/com.visualstudio.code) or [VS Code Insiders](https://github.com/flathub/com.visualstudio.code.insiders) via Flatpak from [Flathub](https://flathub.org/)
1.5. If needed [setup Flatpak and Flathub repo for your distro](https://flathub.org/setup/Ubuntu) first. 
2. execute `flutter doctor -v`.
3. Observe both VS Code or VS Code Insiders installed via Flatpak not showing up.

I'd like to be assigned to this issue and fix it. :)

### Expected results

VS Code and VS Code Insiders installed via Flatpak being picked up by `flutter_tools` and shown in the output of the `flutter doctor` command.

### Actual results

VS Code and VS Code Insiders installed via Flatpak is not being picked up by the `flutter_tools` and is missing from the output of the `flutter doctor` command.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Building flutter tool...
Resolving dependencies... (2.6s)
Got dependencies.
    • Framework revision 27bc1cf61a (87 minutes ago), 2023-10-23 19:25:23 -0400
    • Engine revision 0bd703132c
    • Dart version 3.3.0 (build 3.3.0-53.0.dev)
    • DevTools version 2.28.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/aresminos/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /snap/android-studio/128/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2022.3)
    • Android Studio at /snap/android-studio/128/android-studio
    • Flutter plugin version 75.1.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-35-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.88

[✓] Network resources
    • All expected network resources are available.
```

</details>

### PR DESCRIPTION
**Pull request by KristijanZic**
Closes #137122

<b>Before</b>
VS Code and VS Code Insiders installed via Flatpak aren't detected

<b>After</b>
```sh
[✓] VS Code (version 1.82.2)
    • VS Code at /var/lib/flatpak/app/com.visualstudio.code/x86_64/stable/active/files/extra/vscode
    • Flutter extension version 3.74.0

[✓] VS Code (version 1.84.0-insider)
    • VS Code at /var/lib/flatpak/app/com.visualstudio.code.insiders/x86_64/beta/active/files/extra/vscode-insiders
    • Flutter extension version 3.75.20231002
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by andrewkolos — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
@KristijanZic looks like you will have to resolve the merge conflict before we can merge this PR

**Comment by KristijanZic** [comment]
> @KristijanZic friendly ping

On it! I'm just timing it so that it says flutter on 16 PR GitHub badge on my profile xD

**Comment by christopherfujino** [comment]
> > @KristijanZic friendly ping
> 
> On it! I'm just timing it so that it says "flutter" on 16 PR GitHub badge on my profile xD I just need a few hours, it'll be done today :)

For context I'm not trying to rush you. As long as it's on your radar that's fine. In our weekly PR review we comment on PRs that haven't had activity in a while so we can identify stale ones and close them.

**Comment by christopherfujino** [comment]
Also closed PRs can always be re-opened. So this is all low-stakes, we're just trying to do periodic garbage collection :)

**Comment by KristijanZic** [comment]
@christopherfujino done :)
But Google testing is failing for no obvious reason again :/

**Pull request merged**
