### PR TITLE
Print more layer debug info

### PR DESCRIPTION
**Pull request by liyuqian**
1. Picture identity is added to debug picture raster cache.
2. Engine layer identity is added to debug layer raster cache.
3. Raster cache hints such as isComplex and willChange are also added.

Our clients may need them to debug some performance issues related to the raster cache.

Tests added: PictureLayer prints picture, engine layer, and raster cache hints in debug info

### CODE REVIEW

**Comment by liyuqian** [comment]
CC @ignatz : hopefully this will help debugging the raster cache performance issues.

**Review by yjbanov — APPROVED** [review]

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
Looks like Cirrus is unhappy, though.

**Review by flar — APPROVED** [review]
LGTM

**Pull request merged**
