### PR TITLE
Manually roll the engine and update Gradle dependency locks

### PR DESCRIPTION
**Pull request by blasten**
This is required whenever the embedding dependencies are changed.

To update the dependencies in the future, use:
`find . -type d -name 'android' | dart dev/tools/bin/generate_gradle_lockfiles.dart`

Subsumes this auto-roll: https://github.com/flutter/flutter/pull/92794

### CODE REVIEW

**Comment by zanderso** [comment]
Is this the fix for https://github.com/flutter/flutter/issues/92801?

**Comment by blasten** [comment]
Yup

**Review by dnfield — APPROVED** [review]
Lgtm to unblock the roll 

We should have a way to do this without requiring manual steps.

**Comment by zanderso** [comment]
Was this a breaking change? Are end-users going to have to take any action to compensate for the updated engine deps?

**Comment by jiahaog** [comment]
Apologies, I did not know about this, thanks @blasten!

**Comment by dnfield** [comment]
I think only if they're using lock files in a similar way. @blasten would know better

**Comment by blasten** [comment]
No. This isn’t not a braking change. The lockfiles are used to keep the deterministic Gradle dependencies during CI execution.

**Review by zanderso — APPROVED** [review]

**Comment by zanderso** [comment]
@angjieli is kicking the internal test run, which should hopefully turn the "Google testing" run green.

**Pull request merged**
