### PR TITLE
Remove some more 'dynamic's

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
cc @abarth

**Comment by abarth** [comment]
LGTM

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (408/400 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:48258 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmLl-000aY2-4M
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:37:36 +0100
Date: Mon, 14 Mar 2016 11:12:27 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457979147;
	bh=zd+IvcJZ9cdd3tFpQxAhr//kCAAU0TkXUMn9p+dtDNc=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=nMMO6hDTLiB2ASQFTTxdmx7Z4adss6Lb57ccYUFbEk8oLX5k8Un8e9xjyVYKv4Hyw
	 gVoV8AGYgcx8XlxCC663bV5udzjOTN8/qqCRKAuX1o5UU+A4RAN3Hq9QPQjbRai3V7
	 ySu16VcjcSVS2vGQBBMTOCqKOmpPrL8gM91NTkfs=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (415/400 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:53483 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMb-000ajJ-Kk
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:14 +0100
Date: Mon, 14 Mar 2016 11:12:32 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457979152;
	bh=QZJV6psylMsgJmnXr5RMRN5DH0HDGUnoCOnQ0KA/A+c=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ZTJFpFWDH1Opk3Rz/Ah69vExQ0cn9TVm3R3zpEERSgVXU7vfLd41jEM8yi4lF96Qp
	 9qPElt13ai2xe2gAAfdhtJNK0CBTM7QljsqyWF1GfEAX4BJfUwT5YcBxO4fHdACTnv
	 jIpg/+gowLkebDF4voVUTn2tkYyqlDuYT6BEc1LA=

**Pull request merged**
