### PR TITLE
Disable all Dart fingerprinters

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

There are units tests which cover the behavior of the Fingerprinter given the underlying axiom that the provided values completely describe the build in question. In practice, this assumption is false, as can be seen from the issues linked below.

Until such a time as we can prove them correct, and keep them correct via substantial integration testing, they should stay disabled.

## Related Issues

https://github.com/flutter/flutter/issues/16604
https://github.com/flutter/flutter/issues/27720

### CODE REVIEW

**Review by tvolkert — APPROVED** [review]
Broken behavior is obviously not ok, but it's worth noting that @cbracken added the fingerprinters to fix a highly-upvoted bug at the time about (I think iOS?) incremental build times being painfully slow.

If the fingerprinters introduced a bug and we had caught it right away, the original change would have been reverted anyway, so removing them now LGTM.  But we probably want to put something in the changelog explaining why incremental build times got slower again (at least for now).

**Comment by jonahwilliams** [comment]
There is actually another possibility - that pre-existing bugs in our gradle script are causing some of these issues as well. Forcing the snapshot to always build causes gradle to always build, "fixing" the issue. cc @dnfield  @mklim

**Comment by dnfield** [comment]
Could we disable it only for Android?

**Comment by jonahwilliams** [comment]
Once we prove with integration tests that works for iOS, we can re-enabled it.

**Comment by cbracken** [comment]
Has this been re-enabled? These are painful, but resulted in _massive_ performance increases at the time. If they've been broken since, please fix the root issue rather than regressing performance.

**Comment by jonahwilliams** [comment]
Per my understanding of our priorities for this quarter, this is not currently on my Radar. Lets discuss offline tomorrow.

**Comment by xster** [comment]
No action needed but another angle to consider is that without https://github.com/flutter/flutter/issues/26099, this would also drag in all the non-Flutter devs when they're building xcode/gradle (if they followed our official wiki's setup).

**Comment by xster** [comment]
Is there a tracking bug for re-enabling caching (vs the bugs above which are the incorrect behaviors of caching)?

**Pull request merged**
