### PR TITLE
70341 Correct dateHelpText for en_AU localization

### LINKED ISSUE #70341: Australian MaterialLocalizations has incorrect mm/dd/yyyy dateHelpText
Flutters `en_AU` localizations give the wrong `dateHelpText`. Specifically, they inherit from MaterialLocalizationEn - which uses US style mm/dd/yyyy. [That's not how things are done in Australia.](https://en.wikipedia.org/wiki/Date_and_time_notation_in_Australia)

While the help text is incorrect, the underlying DateFormat locale uses the correct d/m/yyyy formatting. This confuses the user, because when they enter a date as specified by the help desk, the parsed DateTime result is incorrect.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Follow the [Internationalization guide](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#setting-up) to configure localizations
2. Add flutter_localizations to pubspec
2. Set the app's supported locale to en_AU
3. Render the helpText.

**Minimal Example**

`pubspec.yaml`

```yaml
name: dateformat
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
```

`main.dart`

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Date Format Test',
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('en', 'AU'),
        // ... other locales the app supports
      ],
      home: Scaffold(
        appBar: AppBar(title: Text('Date Format Test')),
        body: Builder(builder: (context) {
          final locale = Localizations.localeOf(context);
          final localizations = MaterialLocalizations.of(context);
          final date = DateTime(2020, 11, 12);
          return ListView(
            children: [
              Text('Current Locale: ${locale.toString()}'),
              Text('dateHelpText: ${localizations.dateHelpText}'),
              Text('Compact Date: ${localizations.formatCompactDate(date)}'),
              Text('Short Date: ${localizations.formatShortDate(date)}'),
              Text('Medium Date: ${localizations.formatMediumDate(date)}'),
              Text('Full Date: ${localizations.formatFullDate(date)}'),
            ],
          );
        }),
      ),
    );
  }
}
```

**Expected results:** 

Help text should be dd/mm/yyyy

**Actual results:** 

Help text shows as mm/dd/yyyy

<details>
  <summary>Logs</summary>

no errors when `flutter run --verbose`

```
```
Analyzing dateformat...
No issues found! (ran in 4.2s)
```
```

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-AU)
    • Flutter version 1.23.0-18.1.pre at /Users/michael/.bin/flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/michael/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • F3EA93B5-C2C5-4293-BF6C-B8E48251D7E0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
```

</details>

### PR DESCRIPTION
**Pull request by MichaelMarner**
## Description

This PR closes #70341 by fixing the en_AU localisation for dateHelpText.

Previously, dateHelpText returned `mm/dd/yyyy` which is incorrect for Australian dates, and also did not reflect DateFormat's [compact date for en_AU](https://github.com/dart-lang/intl/blob/master/lib/date_symbol_data_local.dart#L3558).

## Related Issues

* #70341 

## Tests

There doesn't seem to be any tests for changing localizations. I have followed the instructions [here](https://github.com/flutter/flutter/tree/master/packages/flutter_localizations#updating-an-existing-string).

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. 

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by MichaelMarner** [comment]
@googlebot I signed it!

**Comment by shihaohong** [comment]
Hi, thank you for the PR! Unfortunately, we don't take PRs to update any of the `.arb` file changes because we run a script to update these values. We use values generated by Google's internal translation infrastructure to make these changes. However, if there's a value that isn't correct, you can file an issue and we'll make a request for the change to the translation console.

**Comment by MichaelMarner** [comment]
Hey @shihaohong - sorry I was just following the instructions in the [Readme](https://github.com/flutter/flutter/tree/master/packages/flutter_localizations#updating-an-existing-string). Hope this can be resolved soon 👍

**Comment by shihaohong** [comment]
No worries, thanks for attempting the fix :)

**Pull request closed without merging**
