### PR TITLE
Revert "Reland - Update `OutlinedButton` tests for Material 3 (#136809) (#137247)"

### PR DESCRIPTION
**Pull request by TahaTesser**
…9) (#137247)"

This reverts commit 008a10f15898f397a7f0d1ad8e725c01ad61ab3f.

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by bleroux — APPROVED** [review]
LGTM

**Comment by Piinks** [comment]
Do you have a link to the failing build?

**Comment by TahaTesser** [comment]
> Do you have a link to the failing build?

Provided links here https://github.com/flutter/flutter/issues/137177#issuecomment-1783320314

**Comment by TahaTesser** [comment]
> Also, was the test rerun in post submit after failing?

I don't have to access to rerun test in post submit.

**Comment by Piinks** [comment]
> I don't have to access to rerun test in post submit.

Oh! I did not know this. I will follow up on this to see if we can add you.

**Pull request merged**
