### PR TITLE
update device lab manifest stage and required_agent_capabilities

### PR DESCRIPTION
**Pull request by CareF**
## Description

Some of these tests are requiring ios device but is using `stage: devicelab`, or only require mac but uses `required_agent_capabilities: ["mac/ios"]` They seem to work but this PR makes it consistent with device lab readme. 

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by CareF** [comment]
And BTW, is `stage` controlling the icons in the first column in the build try webpage https://flutter-dashboard.appspot.com/#/build ?

**Review by liyuqian — APPROVED** [review]
LGTM

**Comment by liyuqian** [comment]
@CaseyHillers : do you know how icons are determined in the first row of the build webpage https://flutter-dashboard.appspot.com/#/build ? We see some iOS tests with Android icons.

**Comment by digiter** [comment]
You need to search the https://github.com/flutter/cocoon/ code base to see where `stage` is used and make sure not to break Cocoon.

**Comment by CaseyHillers** [comment]
`devicelab` shows an Android logo, `devicelab_ios` shows an Apple logo. This PR looks like it would fix the mislabeling. If there's any changes needed in infra, let's sync up.

[task_icon.dart](https://github.com/flutter/cocoon/blob/master/app_flutter/lib/widgets/task_icon.dart) for reference on the code that loads the icons in Cocoon.

**Review by digiter — APPROVED** [review]
LGTM

**Comment by CareF** [comment]
I noticed that by merging this PR, the build page (https://flutter-dashboard.appspot.com/#/build) now stopped the original rows and start new ones. @digiter

**Comment by CaseyHillers** [comment]
This is intentional. By changing the stage, the dashboard needs to create a new column. Otherwise, the dashboard would not be able to distinguish the same test run on different platforms.

**Pull request merged**
