### PR TITLE
RawKeyboardWindows: Filter out IME events

### LINKED ISSUE #74819: [windows desktop]Korean IME In hanja(한자) key problem
input Chinese characters, conversion is not possible.

my input sequence.
ㄱ ,ㅏ , hanja(한자) key , 1 

expected result
家

actual result
가

image

image

image

<details>
<summary>flutter doctor -v</summary>

```bash
C:\Users\kabyeon\dev\dart\textinput>flutter doctor -v
[√] Flutter (Channel master, 1.26.0-13.0.pre.194, on Microsoft Windows [Version 10.0.19042.746], locale ko-KR)
    • Flutter version 1.26.0-13.0.pre.194 at C:\Users\kabyeon\dev\dart\flutter
    • Framework revision 71aec53acb (11 hours ago), 2021-01-26 21:53:04 -0800
    • Engine revision b11bef83a5
    • Dart version 2.12.0 (build 2.12.0-263.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\kabyeon\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30717.126
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\kabyeon\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.746]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.50

• No issues found!
```
</details>

### PR DESCRIPTION
**Pull request by dkwingsmt**
This PR fixes a problem where IME events cause crash in Win32 apps.

This fix that was once landed in https://github.com/flutter/engine/pull/23853 had a flaw: because on Windows, only down events of IME operations has `VK_PROCESSKEY` as keyCode, while the accompanying up event uses a normal keycode, filtering events in engine using `VK_PROCESSKEY` does not exclude the up events. 

This PR instead filters these events in the framework, since the `RawKeyboard` API keeps states in the framework.

(For the new HardwareKeyboard API, the filtering will be done in the embedding converter.)

Fixes https://github.com/flutter/flutter/issues/74819

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by cbracken — APPROVED** [review]
lgtm. Thank you!

**Comment by wxw-9527** [comment]
On Windows platform, I want to listen to the down event of any key, including when the input method is displayed, but the following code skips the callback function.what should I do? @dkwingsmt Thank You.
```
/// Process a new [RawKeyEvent] by recording the state changes and
  /// dispatching to listeners.
  bool handleRawKeyEvent(RawKeyEvent event) {
    bool shouldDispatch = true;
    if (event is RawKeyDownEvent) {
      if (event.data.shouldDispatchEvent()) {
        _keysPressed[event.physicalKey] = event.logicalKey;
      } else {
        shouldDispatch = false;
        _hiddenKeysPressed.add(event.physicalKey);
      }
    } else if (event is RawKeyUpEvent) {
      if (!_hiddenKeysPressed.contains(event.physicalKey)) {
        // Use the physical key in the key up event to find the physical key from
        // the corresponding key down event and remove it, even if the logical
        // keys don't match.
        _keysPressed.remove(event.physicalKey);
      } else {
        _hiddenKeysPressed.remove(event.physicalKey);
        shouldDispatch = false;
      }
    }
    if (!shouldDispatch) {
      return true;
    }
    // Make sure that the modifiers reflect reality, in case a modifier key was
    // pressed/released while the app didn't have focus.
    _synchronizeModifiers(event);
    assert(
      event is! RawKeyDownEvent || _keysPressed.isNotEmpty,
      'Attempted to send a key down event when no keys are in keysPressed. '
      "This state can occur if the key event being sent doesn't properly "
      'set its modifier flags. This was the event: $event and its data: '
      '${event.data}',
    );
    // Send the event to passive listeners.
    for (final ValueChanged<RawKeyEvent> listener in List<ValueChanged<RawKeyEvent>>.of(_listeners)) {
      try {
        if (_listeners.contains(listener)) {
          listener(event);
        }
      } catch (exception, stack) {
        InformationCollector? collector;
        assert(() {
          collector = () => <DiagnosticsNode>[
            DiagnosticsProperty<RawKeyEvent>('Event', event),
          ];
          return true;
        }());
        FlutterError.reportError(FlutterErrorDetails(
          exception: exception,
          stack: stack,
          library: 'services library',
          context: ErrorDescription('while processing a raw key listener'),
          informationCollector: collector,
        ));
      }
    }

    return false;
  }
```

**Comment by dkwingsmt** [comment]
@wxw-9527 This is a tricky problem, because even if we somehow hack into `RawKeyboardWindows`, our new keyboard system (accessible via `HardwareKeyboard`) also skips these events and does it at in the engine, which you can not hack into. And since other platforms use different ways to ensure keyboard events work well with IMEs, any solution that specifically targets at `VK_PROCESSKEY ` will not be portable.
Can you tell me what you want to achieve with this?

**Comment by wxw-9527** [comment]
Thank you for your reply.
I need to develop a windows program to parse the data provided by the Scanning Gun.But when starting the Chinese input method,```if (!shouldDispatch) { return true; }``` will jump out of this method.
Now I solved my needs in other ways,It was cumbersome, but solved my problem.
```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../util/logger.dart';

final _stringBuffer = StringBuffer();

class ScanMonitor extends StatelessWidget {

  final Widget child;

  final ValueChanged<String>? onScanEnd;

  ScanMonitor({Key? key, required this.child, this.onScanEnd})
      : super(key: key);

  Timer? _timer;

  @override
  Widget build(BuildContext context) {
    return Focus(
      autofocus: true,
      canRequestFocus: true,
      child: child,
      onKey: (node, event) {
        if (event is RawKeyDownEvent) {
          _analysisKeyEvent(event);
        }
        return KeyEventResult.ignored;
      },
    );
  }

  ///
  void _analysisKeyEvent(RawKeyDownEvent event) {
    String? str;
    /* 键盘第一行 */
    // ~ `
    if (PhysicalKeyboardKey.backquote == event.physicalKey) {
      str = event.isShiftPressed ? '~' : '`';
    }
    // 1 !
    if (PhysicalKeyboardKey.digit1 == event.physicalKey) {
      str = event.isShiftPressed ? '!' : '1';
    }
    // 2 @
    else if (PhysicalKeyboardKey.digit2 == event.physicalKey) {
      str = event.isShiftPressed ? '@' : '2';
    }
    // 3 #
    else if (PhysicalKeyboardKey.digit3 == event.physicalKey) {
      str = event.isShiftPressed ? '#' : '3';
    }
    // 4 $
    else if (PhysicalKeyboardKey.digit4 == event.physicalKey) {
      str = event.isShiftPressed ? r'$' : '4';
    }
    // 5 %
    else if (PhysicalKeyboardKey.digit5 == event.physicalKey) {
      str = event.isShiftPressed ? '%' : '5';
    }
    // 6 ^
    else if (PhysicalKeyboardKey.digit6 == event.physicalKey) {
      str = event.isShiftPressed ? '^' : '6';
    }
    // 7 &
    else if (PhysicalKeyboardKey.digit7 == event.physicalKey) {
      str = event.isShiftPressed ? '&' : '7';
    }
    // 8 *
    else if (PhysicalKeyboardKey.digit8 == event.physicalKey) {
      str = event.isShiftPressed ? '*' : '8';
    }
    // 9 (
    else if (PhysicalKeyboardKey.digit9 == event.physicalKey) {
      str = event.isShiftPressed ? '(' : '9';
    }
    // 0 )
    else if (PhysicalKeyboardKey.digit0 == event.physicalKey) {
      str = event.isShiftPressed ? ')' : '0';
    }
    // - _
    else if (PhysicalKeyboardKey.minus == event.physicalKey) {
      str = event.isShiftPressed ? '_' : '-';
    }
    // = +
    else if (PhysicalKeyboardKey.equal == event.physicalKey) {
      str = event.isShiftPressed ? '+' : '=';
    }
    /* 键盘第二行 */
    // Q q
    else if (PhysicalKeyboardKey.keyQ == event.physicalKey) {
      str = event.isShiftPressed ? 'Q' : 'q';
    }
    // W w
    else if (PhysicalKeyboardKey.keyW == event.physicalKey) {
      str = event.isShiftPressed ? 'W' : 'w';
    }
    // E e
    else if (PhysicalKeyboardKey.keyE == event.physicalKey) {
      str = event.isShiftPressed ? 'E' : 'e';
    }
    // R r
    else if (PhysicalKeyboardKey.keyR == event.physicalKey) {
      str = event.isShiftPressed ? 'R' : 'r';
    }
    // T t
    else if (PhysicalKeyboardKey.keyT == event.physicalKey) {
      str = event.isShiftPressed ? 'T' : 't';
    }
    // Y y
    else if (PhysicalKeyboardKey.keyY == event.physicalKey) {
      str = event.isShiftPressed ? 'Y' : 'y';
    }
    // U u
    else if (PhysicalKeyboardKey.keyU == event.physicalKey) {
      str = event.isShiftPressed ? 'U' : 'u';
    }
    // I i
    else if (PhysicalKeyboardKey.keyI == event.physicalKey) {
      str = event.isShiftPressed ? 'I' : 'i';
    }
    // O o
    else if (PhysicalKeyboardKey.keyO == event.physicalKey) {
      str = event.isShiftPressed ? 'O' : 'o';
    }
    // P p
    else if (PhysicalKeyboardKey.keyP == event.physicalKey) {
      str = event.isShiftPressed ? 'P' : 'p';
    }
    // { [
    else if (PhysicalKeyboardKey.bracketLeft == event.physicalKey) {
      str = event.isShiftPressed ? '{' : '[';
    }
    // } ]
    else if (PhysicalKeyboardKey.bracketRight == event.physicalKey) {
      str = event.isShiftPressed ? '}' : ']';
    }
    // | \
    else if (PhysicalKeyboardKey.backslash == event.physicalKey) {
      str = event.isShiftPressed ? '|' : r'\';
    }
    /* 键盘第三行 */
    // A a
    else if (PhysicalKeyboardKey.keyA == event.physicalKey) {
      str = event.isShiftPressed ? 'A' : 'a';
    }
    // S s
    else if (PhysicalKeyboardKey.keyS == event.physicalKey) {
      str = event.isShiftPressed ? 'S' : 's';
    }
    // D d
    else if (PhysicalKeyboardKey.keyD == event.physicalKey) {
      str = event.isShiftPressed ? 'D' : 'd';
    }
    // F f
    else if (PhysicalKeyboardKey.keyF == event.physicalKey) {
      str = event.isShiftPressed ? 'F' : 'f';
    }
    // G g
    else if (PhysicalKeyboardKey.keyG == event.physicalKey) {
      str = event.isShiftPressed ? 'G' : 'g';
    }
    // H h
    else if (PhysicalKeyboardKey.keyH == event.physicalKey) {
      str = event.isShiftPressed ? 'H' : 'h';
    }
    // J j
    else if (PhysicalKeyboardKey.keyJ == event.physicalKey) {
      str = event.isShiftPressed ? 'J' : 'j';
    }
    // K k
    else if (PhysicalKeyboardKey.keyK == event.physicalKey) {
      str = event.isShiftPressed ? 'K' : 'k';
    }
    // L l
    else if (PhysicalKeyboardKey.keyL == event.physicalKey) {
      str = event.isShiftPressed ? 'L' : 'l';
    }
    // : ;
    else if (PhysicalKeyboardKey.semicolon == event.physicalKey) {
      str = event.isShiftPressed ? ':' : ';';
    }
    // " '
    else if (PhysicalKeyboardKey.quote == event.physicalKey) {
      str = event.isShiftPressed ? '"' : '\'';
    }
    /* 键盘第四行 */
    // Z z
    else if (PhysicalKeyboardKey.keyZ == event.physicalKey) {
      str = event.isShiftPressed ? 'Z' : 'z';
    }
    // X x
    else if (PhysicalKeyboardKey.keyX == event.physicalKey) {
      str = event.isShiftPressed ? 'X' : 'x';
    }
    // C c
    else if (PhysicalKeyboardKey.keyC == event.physicalKey) {
      str = event.isShiftPressed ? 'C' : 'c';
    }
    // V v
    else if (PhysicalKeyboardKey.keyV == event.physicalKey) {
      str = event.isShiftPressed ? 'V' : 'v';
    }
    // B b
    else if (PhysicalKeyboardKey.keyB == event.physicalKey) {
      str = event.isShiftPressed ? 'B' : 'b';
    }
    // N n
    else if (PhysicalKeyboardKey.keyN == event.physicalKey) {
      str = event.isShiftPressed ? 'N' : 'n';
    }
    // M m
    else if (PhysicalKeyboardKey.keyM == event.physicalKey) {
      str = event.isShiftPressed ? 'M' : 'm';
    }
    // < ,
    else if (PhysicalKeyboardKey.comma == event.physicalKey) {
      str = event.isShiftPressed ? '<' : ',';
    }
    // > .
    else if (PhysicalKeyboardKey.period == event.physicalKey) {
      str = event.isShiftPressed ? '>' : '.';
    }
    // ? /
    else if (PhysicalKeyboardKey.slash == event.physicalKey) {
      str = event.isShiftPressed ? '?' : '/';
    }
    /* 键盘第五行 */
    // 空格
    else if (PhysicalKeyboardKey.space == event.physicalKey) {
      str = ' ';
    }
    /* 小键盘 */
    // 0
    else if (PhysicalKeyboardKey.numpad0 == event.physicalKey) {
      str = '0';
    }
    // 1
    else if (PhysicalKeyboardKey.numpad1 == event.physicalKey) {
      str = '1';
    }
    // 2
    else if (PhysicalKeyboardKey.numpad2 == event.physicalKey) {
      str = '2';
    }
    // 3
    else if (PhysicalKeyboardKey.numpad3 == event.physicalKey) {
      str = '3';
    }
    // 4
    else if (PhysicalKeyboardKey.numpad4 == event.physicalKey) {
      str = '4';
    }
    // 5
    else if (PhysicalKeyboardKey.numpad5 == event.physicalKey) {
      str = '5';
    }
    // 6
    else if (PhysicalKeyboardKey.numpad6 == event.physicalKey) {
      str = '6';
    }
    // 7
    else if (PhysicalKeyboardKey.numpad7 == event.physicalKey) {
      str = '7';
    }
    // 8
    else if (PhysicalKeyboardKey.numpad8 == event.physicalKey) {
      str = '8';
    }
    // 9
    else if (PhysicalKeyboardKey.numpad9 == event.physicalKey) {
      str = '9';
    }
    // +
    else if (PhysicalKeyboardKey.numpadAdd == event.physicalKey) {
      str = '+';
    }
    // -
    else if (PhysicalKeyboardKey.numpadSubtract == event.physicalKey) {
      str = '-';
    }
    // *
    else if (PhysicalKeyboardKey.numpadMultiply == event.physicalKey) {
      str = '*';
    }
    // /
    else if (PhysicalKeyboardKey.numpadDivide == event.physicalKey) {
      str = '/';
    }
    // .
    else if (PhysicalKeyboardKey.numpadDecimal == event.physicalKey) {
      str = '.';
    }
    // 处理结果
    if (str != null && str.isNotEmpty) {
      _stringBuffer.write(str);
    }
    if (LogicalKeyboardKey.enter == event.logicalKey) {
      _timer = _buildTimber();
    } else {
      _timer = _buildTimber(milliseconds: 500);
    }
  }

  //  生成计时器实例
  Timer _buildTimber({int milliseconds = 500}) {
    // 取消定时器
    _timer?.cancel();
    _timer = null;
    // 创建新的定时器对象
    return Timer(Duration(milliseconds: milliseconds), () {
      // 处理数据
      String result = _stringBuffer.toString();
      _stringBuffer.clear();
      if (result.isNotEmpty) {
        logger.d(result);
        onScanEnd?.call(result);
      }
    });
  }
}
```

**Comment by dkwingsmt** [comment]
I see what you're doing here. (By the way, your current short link is broken.)

If you can hack into the engine you might want to try `ImmDisableIME`, which must be called before the window is created and disables IME for the entire window. Not sure if it's too strong for you.

**Comment by wxw-9527** [comment]
You're great.....（给大哥跪了）
I use `Focus()` do what I want, but I just discovered, you have fixed it..... [#104244](https://github.com/flutter/flutter/pull/104244)
Now I have to think about using `ImmDisableIME`.
Can you help me, how to use `ImmDisableIME` method to disable IME? Thank you very much.

(Google Translate)

**Comment by dkwingsmt** [comment]
总的来说，你需要让flutter引擎在程序的窗口创建之前运行win32的ImmDisableIME函数（不需要参数）。我一时能想到有三种方案：
1. 自己修改引擎，然后找到创建窗口前的位置插这么一行就行。优点是100%理论可行，缺点是需要自己编译引擎并且以后需要自己rebase。
2. 写一个插件（flutter plugin），插件不需要开放任何接口，只需要调用这个函数。我猜测这个函数应该是在创建窗口前调用的，但不确定。优点是漂亮，甚至可以拿到pub.dev上发成库。缺点是我不确定是不是真的可行。
3. 修改应用里的runner，然后在调用flutter的任何函数前调用这个函数。优点是简单（应该可行吧……），缺点是……没有2漂亮（？）。

具体怎么做我现在在手机上看不到。如果你摸索不出来我们可以再讨论。

**Comment by wxw-9527** [comment]
非常感谢您的回复！我试一试。
（题外话，你可真是个让人又爱又恨的男人。。。把路堵的死死的。）

**Comment by wxw-9527** [comment]
我找到了[ImmDisableIME函数](https://learn.microsoft.com/zh-cn/windows/win32/api/immdev/nf-immdev-immdisableime)的文档，但是我没有找到合适的地方调用这个函数，因为它需要的参数我没在windows/runner路径下的任何文件中找到。

**Comment by dkwingsmt** [comment]
A lot of websites mentioned that the parameter should simply be -1.

```
ImmDisableIME(-1);
```

https://github.com/MicrosoftDocs/sdk-api/blob/docs/sdk-api-src/content/immdev/nf-immdev-immdisableime.md

https://cpp.hotexamples.com/examples/-/-/ImmDisableIME/cpp-immdisableime-function-examples.html

https://www.tokovalue.jp/function/ImmDisableIME.htm

**Comment by wxw-9527** [comment]
I'm very sorry to trouble you again.
Because I don't know anything about Windows native development. I tried many times, Including asking questions on [stackoverflow](https://stackoverflow.com/questions/73849077/develop-windows-programs-with-flutter-how-to-disable-ime), But after adding `ImmDisableIME(-1);`, it will report an error when compiling.

**Comment by dkwingsmt** [comment]
What's the compiling error?

**Comment by wxw-9527** [comment]
use `ImmDisableIME(-1);`:
[mian.cpp](https://i.stack.imgur.com/cVvJs.png)
[win32_window.cpp](https://i.stack.imgur.com/5gd9V.png)

Exception when using `DWORD dwParam = (DWORD)(-1); ImmDisableIME(dwParam);`:
`win32_window.obj : error LNK2019: �޷��������ⲿ���� ImmDisableIME������ "public: bool __cdecl Win32Window::CreateAndShow(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,struct Win32Window::Point const &,struct Win32Window::Size const &)" (?CreateAndShow@Win32Window@@QEAA_NAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@AEBUPoint@1@AEBUSize@1@@Z) �������˸÷��� [W:\WorkSpace\RouXinPai\workpad\build\windows\runner\workpad.vcxproj]
W:\WorkSpace\RouXinPai\workpad\build\windows\runner\Debug\workpad.exe : fatal error LNK1120: 1 ���޷��������ⲿ���� [W:\WorkSpace\RouXinPai\workpad\build\windows\runner\workpad.vcxproj]
Exception: Build process failed.`

**Comment by dkwingsmt** [comment]
I think it's because you didn't provide the correct lib file to link `ImmDisableIME`. Maybe try adding 
```
#pragma comment(lib, "imm32.lib")
```

https://blog.csdn.net/sleep_0/article/details/50452483

**Comment by wxw-9527** [comment]
Thanks for your help.
After adding `#pragma comment(lib, "imm32.lib")` to the file header of `win32_window.cpp`, add `ImmDisableIME(GetCurrentThreadId())` in `CreateAndShow` method, can disable the IME.
Thanks again.

**Comment by dkwingsmt** [comment]
Awesome! Glad to know.

**Pull request merged**
