### PR TITLE
Updated Scaffold api docs

### LINKED ISSUE #64136: Scaffold API docs - Should there be a single Scaffold in my entire Flutter app?
Hello,

The documentation at https://api.flutter.dev/flutter/material/Scaffold-class.html says

"The Scaffold was designed to be the single top level container for a MaterialApp and it's typically not necessary to nest scaffolds. For example in a tabbed UI, where the bottomNavigationBar is a TabBar and the body is a TabBarView, you might be tempted to make each tab bar view a scaffold with a differently titled AppBar. It would be better to add a listener to the TabController that updates the AppBar."

Does this mean I should not have a scaffold on any routes in my app?

Here, users say we can have a scaffold per page like here https://stackoverflow.com/questions/60561552/multiple-scaffolds-for-each-page-inside-a-flutter-app

So which one should it be? Please clarify in the docs...

### PR DESCRIPTION
**Pull request by Aman9026**
## Description

Updated Scaffold api docs to add that you can use scaffold for each route

## Related Issues

Fixes #64136

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Review by HansMuller — COMMENTED** [review]
We appreciate this contribution. Unfortunately it's one of two PRs that are trying to address this issue. The other one is https://github.com/flutter/flutter/pull/64645.

It would probably be best for you to close this one and review the other; we do want to get this text right!

**Comment by Aman9026** [comment]
> We appreciate this contribution. Unfortunately it's one of two PRs that are trying to address this issue. The other one is #64645.
> 
> It would probably be best for you to close this one and review the other; we do want to get this text right!

Thanks, would help him fix this.

**Comment by Aman9026** [comment]
@HansMuller The changes made by me are appropriate or I need to update this?

**Comment by HansMuller** [comment]
I'm suggesting that your close this PR and add a review to #64645.

**Comment by Aman9026** [comment]
> I'm suggesting that your close this PR and add a review to #64645.

Okay sure, I'll help him out.

**Pull request closed without merging**
