### PR TITLE
[ci.yaml] Add hot_mode_dev_cycle_win_target__benchmark and Linux gradle_plugin_light_apk_test

### LINKED ISSUE #87373: Windows hot_mode_dev_cycle_win_target__benchmark failing upload metrics due to missing ci.yaml entry
/api/update-task-status is failing consistently with 500 http status code complaining that it can not find any entries for some builder names.

Found 0 entries for builder Windows hot_mode_dev_cycle_win_target__benchmark

image

### PR DESCRIPTION
**Pull request by CaseyHillers**
These are tests that are already running on LUCI, but haven't been connected here. These already appear to have TEST OWNERS assigned to them

https://github.com/flutter/flutter/issues/86802
https://github.com/flutter/flutter/issues/85803
Fixes https://github.com/flutter/flutter/issues/87373

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [X] All existing and new tests are passing.

### CODE REVIEW

**Review by keyonghan — COMMENTED** [review]
I see these builders should stay off: https://github.com/flutter/flutter/issues/86802?

**Review by jmagman — CHANGES_REQUESTED** [review]
With the config refactoring can we instead delete `dev/devicelab/bin/tasks/gradle_non_android_plugin_test.dart`?  The builder was kept around so it wouldn't break stable.

https://github.com/flutter/flutter/blob/a0e5fe84ac1e1364e8b150b7bd16a643a72b62a0/dev/devicelab/bin/tasks/gradle_non_android_plugin_test.dart#L10

See https://github.com/flutter/flutter/issues/85347.
\cc @christopherfujino

**Comment by jmagman** [comment]
`hot_mode_dev_cycle_win_target__benchmark` and `hot_mode_dev_cycle_linux_target__benchmark` were created, but then passed off for further work: https://github.com/flutter/flutter/issues/54295#issuecomment-794192043

**Comment by jmagman** [comment]
> `hot_mode_dev_cycle_win_target__benchmark` and `hot_mode_dev_cycle_linux_target__benchmark` were created, but then passed off for further work: [#54295 (comment)](https://github.com/flutter/flutter/issues/54295#issuecomment-794192043)

@cbracken are these ready to be turned on?

**Comment by CaseyHillers** [comment]
Thanks! When the auto-generation of ci.yaml is rolled out for the framework, it's likely we'll be removing the gradle_non_android_plugin_test anyway

**Comment by jmagman** [comment]
I think @cbracken still needs to weigh in for `hot_mode_dev_cycle_win_target__benchmark`, see https://github.com/flutter/flutter/issues/54295#issuecomment-790907661

**Comment by CaseyHillers** [comment]
Adding @godofredoc, next few days the LUCI configs are going to be generated from this ci.yaml. We either need to add it here or be okay with removing it. Since the test passes some of the time, it should be okay as adding as flaky here, and we can follow up removing it if there's no future plans.

**Comment by jmagman** [comment]
And should `hot_mode_dev_cycle_linux_target__benchmark` also be turned on?

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

**Comment by CaseyHillers** [comment]
@keyonghan is there documentation for adding to TESTOWNERS? I added ownership, but it still says it's missing

**Comment by keyonghan** [comment]
> @keyonghan is there documentation for adding to TESTOWNERS? I added ownership, but it still says it's missing

You are missing `.dart` for the devicelab test file.

**Review by jmagman — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
