### PR TITLE
Define team on wiki

### PR DESCRIPTION
**Pull request by nuritzi**
Are we able to point people to a specific page that has a list of team members, or which describes who the team is comprised of? As a newcomer, I have the following questions after reading this section: 
 * Is the team here the Google Flutter team? A core team? Is it just the people with Developer+ access on GitHub?
 * Is this only meant for code contributors, or for the whole Flutter community? Is this a place where people can collaborate on community-building and outreach? If not, where does one go to do that?

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by nuritzi** [comment]
@itsjustkevin @khyati82 -- adding you both here since you may have more context on this!

**Comment by HLA95** [comment]
Ti

**Comment by Hixie** [comment]
(This is probably best done as an issue?)

> Is the team here the Google Flutter team? A core team? Is it just the people with Developer+ access on GitHub?

I think the intent of this paragraph is to just mean the people working on Flutter, regardless of contributor access or employer.

> Is this only meant for code contributors, or for the whole Flutter community? Is this a place where people can collaborate on community-building and outreach? If not, where does one go to do that?

For "community-building and outreach", do you mean user community or contributor community? We don't really have anything organized around community-building and outreach for the contributor community, other than the Discord. For the user community we don't really do this directly from the open source project, it's mainly done by independent groups like the r/FlutterDev community, the many user groups around the world, and so on. Google's Flutter-focused devrel team works with those groups. The #hackers-devrel channel on Discord is a good place for discussions about that.

**Comment by nuritzi** [comment]
Will close this out since we've already updated the file.

**Pull request closed without merging**
