### PR TITLE
[flutter_releases] Flutter Stable 2.0.4 Framework Cherrypicks

### PR DESCRIPTION
**Pull request by christopherfujino**
## Scheduled Cherrypicks
- [x] Roll engine cherrypicks https://github.com/flutter/engine/pull/25341
- [x] #78589 'ld: bitcode bundle could not be generated' iOS app build error
  - https://github.com/flutter/flutter/commit/6a4dd4cfb417f509befd6eb4bd952f232027e52b
  - Original author @jmagman 

## Pre-submit Known Failures
- All customer_testing shards failing as they clone from head.

## Post-submit Known Failures
- Devicelab failures where tests passed, but parsing benchmark data failed due to a lack of having cherrypicked https://github.com/flutter/flutter/commit/b6a6ea704558662d84537812222ad6f26fd565e8
  - [flutter_gallery__transition_perf_e2e_ios32](https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20stable%20flutter_gallery__transition_perf_e2e_ios32/5?)

### CODE REVIEW

**Comment by christopherfujino** [comment]
Manually overrode cla bot as the one commit author has already signed the CLA.

**Review by kf6gpe — APPROVED** [review]
LGTM!

**Review by jmagman — APPROVED** [review]
LGTM!

**Comment by christopherfujino** [comment]
Outstanding queued pre-submit builds are because upstream these were removed and instead their sub-builds were lifted to the top level. I will attempt to follow up with a fix (cherrypicking will be non-trivial).

**Pull request merged**
