### PR TITLE
Add `-products *` to vswhere calls to find standalone build tools

### PR DESCRIPTION
**Pull request by cactyx**
This allows finding standalone build tools when the VS IDE is not installed.

## Description

The `vswhere` binary [does not find standalone Build Tools](https://github.com/Microsoft/vswhere/issues/103#issuecomment-330567014) when no eligible `products` parameter is specified. This MR adds `-products *` to work around that.

## Related Issues

https://github.com/google/flutter-desktop-embedding/issues/585

## Tests

I added the following tests:

*none*

## Checklist (TODO)

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by stuartmorgan** [comment]
It's not going to be this simple. The current logic is based on using the version of `vswhere` that is installed by the VS installer, so if VS isn't installed it's going to fail well before this point.

So supporting this would at least require either using a tool-managed `vswhere`, or using some other mechanism to validate the toolchain.

**Comment by metaa** [comment]
Thanks for having a look at this @stuartmorgan.

I understand that having something that works right away - possibly even without the current `vswhere` dependency - would be far better, but regarding the current "experimental" state of desktop support, adding the `products` parameter would at least improve the current situation for Windows setups, wouldn't it?

In my case I couldn't get `flutter doctor` and `flutter run` (in `example/`) to yield the desired results at all without either using a custom Flutter build including this change or possibly installing VS (which I am currently unable to do).

> So supporting this would at least require either using a tool-managed `vswhere`, or using some other mechanism to validate the toolchain.

Maybe we could have a look at how [Webkit decided](https://bugs.webkit.org/show_bug.cgi?id=196760) to [bundle `vswhere`](https://github.com/Microsoft/vswhere) then. 

Also what about these checks? Should I trigger a re-run or are they just broken in general? (I see SSL handshake errors and stuff 🤔)

**Comment by stuartmorgan** [comment]
> adding the products parameter would at least improve the current situation for Windows setups, wouldn't it?

I'm unclear on how though. Under what circumstances does someone have the VS installer copy of `vswhere` that this code requires, but not have VS?

**Comment by metaa** [comment]
> Under what circumstances does someone have the VS installer copy of `vswhere` that this code requires, but not have VS?

That installer that you get on [the page linked in `flutter doctor`](https://visualstudio.microsoft.com/downloads/) also places `vswhere` in `C:\Program Files (x86)\Microsoft Visual Studio\Installer`.

image

I just tested that by removing that whole directory and running the installer again.

**Comment by stuartmorgan** [comment]
Right, but that's the Visual Studio installer. I'm still not understanding why someone would have installed the VS installer but not then installed VS.

Can you provide more detail about what your installation flow is here? Does the VS installer have an option to install the tools without the IDE? Or are you getting them separately and just installing the installer to get `vswhere` to satisfy the current `flutter` check?

**Comment by metaa** [comment]
> I'm still not understanding why someone would have installed the VS installer but not then installed VS.

I personally just don't need the VS IDE at all because I'm not gonna use it, so I'm fine with the build tools being offered separately a bit further down on the page (_I actually just realized that I did that instead of picking the thing offered on top of the page so now I get where this confusion is coming from 😮, I'm very sorry_).
image

> Can you provide more detail about what your installation flow is here? Does the VS installer have an option to install the tools without the IDE? Or are you getting them separately and just installing the installer to get vswhere to satisfy the current flutter check?

Apart from choosing the build tools installer, I actually really just do what `flutter doctor` tells me to do.

1. I download the installer.
1. I watch it download and unpack some files on its first run (this also installs `vswhere`).  
image

1. I choose the C++ build tools (`flutter doctor` calls it "Desktop development with C++", maybe it was named that previously)
image

1. And then in my case I unchecked this, because I won't need VS' testing tools
image

1.  
image

**Comment by stuartmorgan** [comment]
Okay, now I understand. I didn't realize that the thing that installs just the build tools is also the Visual Studio Installer.

This seems like a reasonable incremental change to make to support more installation options then. (It'll need tests though, including some tests using canned output that matches what `vswhere` prints for your IDE-less install.)

**Comment by metaa** [comment]
Any updates?
I'd love to get this moving, I just need to know what's up and what needs to be done until I can submit this for review.

**Comment by stuartmorgan** [comment]
Per my last comment (and the fluttergithubbot comment earlier), it needs tests.

**Comment by stuartmorgan** [comment]
@metaa Are you planning on adding tests to this PR so that it can be reviewed and submitted?

**Comment by metaa** [comment]
> @metaa Are you planning on adding tests to this PR so that it can be reviewed and submitted?

I'd love to but I don't quite know how to properly implement them so I was hoping someone could help.

**Comment by stuartmorgan** [comment]
See the existing tests [here](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/windows/visual_studio_test.dart); you'll need a new `setMock...` method that simulates the important parts of your `vswhere` output, and one or more tests validating that it's found correctly following the exiting test structure in that file.

You'll also need to update [this](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/windows/visual_studio_test.dart#L91) to include the new arguments you've added to avoid breaking all the existing tests.

If you have specific questions after looking at that, please let me know.

**Comment by jonahwilliams** [comment]
We haven't heard back from a while here, so I'm going to close the PR in the meantime (to remove it from our review queue). Please feel free to reopen whenever you have time to work on it, or follow up with an issue if you have specific questions about tests/testing

**Comment by metaa** [comment]
I just had another look at this after rebasing to master (locally), wouldn't it make sense to add `-product *` [here](https://github.com/flutter/flutter/blob/2238582301d3a453f28447f6ca86bfc5b5d22426/packages/flutter_tools/test/general.shard/windows/visual_studio_test.dart#L153) instead of adding new mocks since `setMockAnyVisualStudioInstallation` already aims to find *any* installation?

**Comment by stuartmorgan** [comment]
In the rewritten structure you can use existing `setMock*` methods, yes. That is not the only one you'll need to use to do proper testing though, since you are changing the behavior for all lookups, not only for the last-ditch lookup.

You should approach this from the standpoint of writing new tests covering the important new cases, then considering what changes you'll need in the test fixture to properly implement those tests.

**Pull request closed without merging**
