### PR TITLE
[CP] Ignore invalid description in vswhere.exe JSON output

### PR DESCRIPTION
**Pull request by loic-sharma**
The `flutter doctor`, `flutter build`, and `flutter run` commands fail on Windows using certain locales when using the latest version of Visual Studio. This cherrypicks the fix to the latest stable release: https://github.com/flutter/flutter/commit/dcbdff087b7f162dcd9917aad278c7cf2515d8a6 from https://github.com/flutter/flutter/pull/106836.

Cherry pick issue: https://github.com/flutter/flutter/issues/106920

Fixes: https://github.com/flutter/flutter/issues/106601

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
code lgtm

**Comment by itsjustkevin** [comment]
@muditatandon @CaseyHillers Any idea what is going on with these failing tests?

**Comment by CaseyHillers** [comment]
The web tests are timing out (likely due to something crashing)

**Comment by christopherfujino** [comment]
Linux build_tests_1_2 failing because ninja not found:

```
[   +7 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DFLUTTER_TARGET_PLATFORM=linux-x64 /b/s/w/ir/x/w/flutter/dev/integration_tests/flutter_gallery/linux
[  +39 ms] CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
[   +1 ms] CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
[        ] -- Configuring incomplete, errors occurred!
```

I wonder if this dependency changed upstream since the branch?

**Review by itsjustkevin — APPROVED** [review]
LGTM

**Pull request merged**
