### PR TITLE
Propagate TexTheme to Tooltip dark theme

### PR DESCRIPTION
**Pull request by cbracken**

### CODE REVIEW

**Comment by cbracken** [comment]
Another possibility is just re-kill the dark theme, do the `isDark` check inline to set the `TextTheme` and inline the default dark theme colour.

**Comment by Hixie** [comment]
Yeah, I dunno. LGTM I guess.

BTW, another thing we should probably do is make sure anywhere we create a ThemeData, we propagate the platform from the parent theme. Otherwise @eseidel will be sad.

**Comment by cbracken** [comment]
Platform: done. Rebasing the iOS fonts change on top makes me sad without it too.

**Pull request merged**
