### PR TITLE
Remove unused EventRecorder

### PR DESCRIPTION
**Pull request by abarth**

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM.
cc @krisgiesing

**Comment by krisgiesing** [comment]
I used this to generate the velocity tracker test data. I guess the code doesn't have to stay in the framework.

**Comment by abarth** [comment]
Yeah, it was confusing someone who was trying to use it for another purpose.

**Comment by krisgiesing** [comment]
What were they trying to do?

**Comment by abarth** [comment]
The were trying to test some gesture disambiguation cases.

**Pull request merged**
