### PR TITLE
Revert "update packages"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#68569

Broke several tests with compilation errors due to url_launcher. TBR @dnfield

### CODE REVIEW

**Comment by dnfield** [comment]
LGTM or whatever

**Comment by jonahwilliams** [comment]
```
2020-10-20T08:39:04.595944: stderr: [ +960 ms] /Users/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.4+1/lib/url_launcher_web.dart:22:7: Error: The non-abstract class 'UrlLauncherPlugin' is missing implementations for these members:
stderr: [   +3 ms]  - UrlLauncherPlatform.linkDelegate
2020-10-20T08:39:04.597064: stderr: [        ] Try to either
stderr: [        ]  - provide an implementation,
stderr: [        ]  - inherit an implementation from a superclass or mixin,
stderr: [        ]  - mark the class as abstract, or
stderr: [        ]  - provide a 'noSuchMethod' implementation.
2020-10-20T08:39:04.598055: stderr: [        ] class UrlLauncherPlugin extends UrlLauncherPlatform {
stderr: [        ]       ^^^^^^^^^^^^^^^^^
stderr: [        ] /Users/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_platform_interface-1.0.9/lib/url_launcher_platform_interface.dart:43:20: Context: 'UrlLauncherPlatform.linkDelegate' is defined here.
2020-10-20T08:39:04.598385: stderr: [        ]   LinkDelegate get linkDelegate;
stderr: [        ]                    ^^^^^^^^^^^^
2020-10-20T08:39:29.296377: stdout: [+24696 ms] Syncing files to device Web Server... (completed in 27.4s)
2020-10-20T08:39:29.297128: stdout: [   +1 ms] Synced 0.0MB.
2020-10-20T08:39:29.297719: stderr: [        ] Failed to compile application.
2020-10-20T08:39:29.302169: stdout: [   +4 ms] "flutter run" took 30,049ms.
2020-10-20T08:39:29.307892: stderr: [   +5 ms] 
stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
```

Sorry, logs took a while

**Comment by ditman** [comment]
Closing the loop here: Mouad [published](https://github.com/flutter/plugins/pull/3155#issuecomment-713232563) the fix for this one. Apologies for the breakage! /cc @dnfield @jonahwilliams

**Pull request merged**
