### PR TITLE
[CP] Fix visual overflow for SliverMainAxisGroup (#132989)

### PR DESCRIPTION
**Pull request by Piinks**
Cherry picks https://github.com/flutter/flutter/pull/132989 which fixes https://github.com/flutter/flutter/issues/132788

Fixes https://github.com/flutter/flutter/issues/133058

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by XilaiZhang** [comment]
thanks for the cp! merged. As a side note it is recommended to merge early once the cp is approved. Thank you!

**Comment by Piinks** [comment]
> As a side note it is recommended to merge early once the cp is approved. 

Did I miss a step in the documented process? I was wondering why it took so long for this to be merged.

As I understand it, it is up to the release team to merge it.

https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process

**Comment by XilaiZhang** [comment]
oh thanks for providing the doc!
umm @itsjustkevin can we update the doc with a section to merge the cp pull request once its approved? thank you!

**Pull request merged**
