### PR TITLE
Adaptive progress indicator

### PR DESCRIPTION
**Pull request by viveky259259**
## Automatic Progress Indicator depends on Platform

##Description
I am making this PR because I got some problems while specifying Progress indicator for ios and Android. Everytime I need to do if else for making circular progress as activity indicator for ios and circular progress indicator for android.

## Related Issues

One Issue: I get have to check Platform everytime or make a common widget. But a NOOB developer don't know this. So if we get automatic progress indicator like back button in app bar, it will be good for Flutter Framework.

## Tests

Called  AutoProgressIndicator() to get result. And it worked.
## Checklist

Before you create this PR confirms that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by viveky259259** [comment]
@googlebot I signed it!

**Comment by viveky259259** [comment]
@googlebot I signed it!

**Comment by viveky259259** [comment]
@googlebot I fixed it.

**Comment by shihaohong** [comment]
Hi @viveky259259, this seems like a good idea! We tend to make adaptive widgets using an adaptive constructor, just like [Slider does](https://master-api.flutter.dev/flutter/material/Slider/Slider.adaptive.html). There are a couple of other things as well:

1) The `flutter/flutter` repo does not use `dartfmt`. There were a lot of unrelated changes in the files changes, so please revert those.
2) You would need to test your implementation, writing unit tests that make sure that the correct progress indicator is used.
3) You will also need to fix your PR commits to use the email address that you signed the CLA for.

**Comment by shihaohong** [comment]
cc/ @clocksmith, who had worked on the adaptive slider. Do you have any thoughts on implementing an adaptive progress indicator?

**Comment by chunhtai** [comment]
@viveky259259 Thanks for contribution!

There seems to have some formatting changes, would you reverse those? There also are some conflicts with current master.

**Comment by viveky259259** [comment]
Yes it was much older that is why.
I will do a new merge request with some more precautions

**Comment by chunhtai** [comment]
@viveky259259 bump for your attention :)

**Comment by chunhtai** [comment]
@viveky259259 I will close this one for now, feel free to ping me once you create a new pr. Thanks!

**Pull request closed without merging**
