### PR TITLE
increase test timeouts

### PR DESCRIPTION
**Pull request by devoncarew**
- increase test timeouts to account for 3 failing tests (https://build.chromium.org/p/client.flutter/builders/Windows/builds/3297/steps/run%20test.dart%20for%20tests%20shard/logs/stdio)

### CODE REVIEW

**Comment by devoncarew** [comment]
(follow up to https://github.com/flutter/flutter/pull/16979)

**Comment by tvolkert** [comment]
Do we know why they're taking longer now?

**Review by tvolkert — APPROVED** [review]
LGTM.

If there isn't already a bug filed about investigating and improving the cause of the slow cold analysis times, can you file one and link it here?

**Review by cbracken — APPROVED** [review]

**Comment by devoncarew** [comment]
The PRs do have some info about why; @Hixie filed a bug on the sdk repo - https://github.com/dart-lang/sdk/issues/33039 - which is probably the best tracking issue.

We've set up a benchmark on the dart benchmarking system to track this - `flutter analyze --flutter-repo` - using combined commits from the dart and flutter repos, and are working on a longer term plan.

**Comment by devoncarew** [comment]
I still see 2 failures -`TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.` - after this PR. I'm not certain that `timeout: const Timeout.factor(2.0)` doubled anything?

**Comment by devoncarew** [comment]
Hmm, https://build.chromium.org/p/client.flutter/builders/Windows/builds/3299 is passing, so perhaps things are working after all.

**Pull request merged**
