### PR TITLE
Remove various roboto font logic

### PR DESCRIPTION
**Pull request by xster**
#6670

### CODE REVIEW

**Comment by xster** [comment]
Archive:  app.flx
  inflating: fonts/MaterialIcons-Regular.ttf
 extracting: AssetManifest.json
  inflating: FontManifest.json
  inflating: LICENSE

Seems to work ok. How else can I make sure I haven't done anything horrible?

**Comment by abarth** [comment]
LGTM but please make sure the Fuchsia folks have these fonts in their pubspec.yaml files before landing.  Let me know if you need help migrating them.

**Comment by xster** [comment]
That's just to make sure all the other fonts in material_fonts.yaml that Fuchsia doesn't have is bundled too? Should I do it on their github repo or something?

**Comment by abarth** [comment]
> That's just to make sure all the other fonts in material_fonts.yaml that Fuchsia doesn't have is bundled too?

Yep.

> Should I do it on their github repo or something?

They actually all reference back to our repo for a template:

https://github.com/flutter/engine/blob/master/build/flutter_app.gni

It looks like armadillo is the only one with an explicit pubspec.yaml:

https://fuchsia.googlesource.com/sysui/+/master/armadillo/pubspec.yaml

The rest just use the default value for `manifest` in the template.  We can make the default `manifest` be a file in engine.git that includes these fonts.

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm

**Comment by Hixie** [comment]
@xster Are you still planning on merging this?

**Comment by xster** [comment]
@Hixie yes, I just gotta finish up https://github.com/flutter/engine/pull/3444

**Pull request merged**
