### PR TITLE
Updated Hebrew l10n

### PR DESCRIPTION
**Pull request by xvld**
Fixed Hebrew translations to be consistent with the OS.

## Description

Fixed Hebrew translations to be consistent with the OS.
screenshot

## Related Issues

-

## Tests

-

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by vladir95** [comment]
@googlebot I signed it!

**Comment by shihaohong** [comment]
Hi @vladir95, we use an internal translation tool to generate all Flutter translations and refresh the values every time there are significant changes to the translations (see https://github.com/flutter/flutter/pull/42025 for an example of such a PR). 

Which OS/platform would your suggested translations be consistent with? I can certainly suggest these changes to our translators.

**Comment by vladir95** [comment]
Hey @shihaohong, it's inconsistent with both platforms actually.
It's not using the correct tense in Hebrew.

**Comment by shihaohong** [comment]
I just made these suggestions to our internal translations console. Once they review and approve these changes, we should be able to pull down any localizations updates!

**Comment by shihaohong** [comment]
Let's close this PR for now -- I'll create an issue to track that these updates should make it into Flutter and link it to here since it contains the diffs, which will be helpful in verifying that these suggestions made it through.

**Pull request closed without merging**
