### PR TITLE
Added support for MaterialState to InputDecorator

### PR DESCRIPTION
**Pull request by bjartebore**
This is a new pull request for #91182 after it was reverted in #91448, addressing the issues found

---

- Adds support for MaterialState properties to all relevant Color, TextStyle and Border properties of InputDecoration and InputDecorationTheme
- Adds support for iconColor, prefixIconColor and suffixIconColor properties to InputDecoration and InputDecorationTheme

#91180 
#91181 

All changes are backward compatible

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by bjartebore** [comment]
Since _getInlineStyle originally did not include labelStyle and the new code merged labelStyle with hintStyle, I am pretty confident that the split should resolve the latest regression issue.

I agree that there should be a regression test for this, but I would believe that have to be golden tests, and I am unsure about how to go forward with those.

**Comment by HansMuller** [comment]
Although I didn't include the changes from "[clean up a redundant TextStyle.merge](https://github.com/flutter/flutter/pull/91762/commits/eb78a5a04fa3f4007e08f3a46cdbf8c962b2f1ce)" the internal tests appear to succeeded with your latest changes. I will try and land this PR when the tree goes green. Fingers crossed.

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by bjartebore** [comment]
I think this unintentionally fixed an unknown bug (that the golden tests rely upon). If we look at the original code, the `height: 1` is applied before `floatingLabelStyle ?? labelStyle` is merged in this meaning that if the height is set in either one of those the fixTextFieldOutlineLabel does nothing. In all other places the fixTextFieldOutlineLabel is applied last.

I can change _getFloatingLabelStyle to work as before, but I would like you to consider if this is not really an error

```dart
  // OLD CODE
  TextStyle _getFloatingLabelStyle(ThemeData themeData) {
    final Color color = decoration!.errorText != null
      ? decoration!.errorStyle?.color ?? themeData.errorColor
      : _getActiveColor(themeData);
    final TextStyle style = themeData.textTheme.subtitle1!.merge(widget.baseStyle);
    // Temporary opt-in fix for https://github.com/flutter/flutter/issues/54028
    // Setting TextStyle.height to 1 ensures that the label's height will equal
    // its font size.
    return themeData.fixTextFieldOutlineLabel
      ? style
        .copyWith(height: 1, color: decoration!.enabled ? color : themeData.disabledColor)
        .merge(decoration!.floatingLabelStyle ?? decoration!.labelStyle)
      : style
        .copyWith(color: decoration!.enabled ? color : themeData.disabledColor)
        .merge(decoration!.floatingLabelStyle ?? decoration!.labelStyle);

  }
```  

```dart
  // NEW CODE
  TextStyle _getFloatingLabelStyle(ThemeData themeData) {
    TextStyle getFallbackTextStyle() {
      final Color color = decoration!.errorText != null
        ? decoration!.errorStyle?.color ?? themeData.errorColor
        : _getActiveColor(themeData);

      return TextStyle(color: decoration!.enabled ? color : themeData.disabledColor)
        .merge(decoration!.floatingLabelStyle ?? decoration!.labelStyle);
    }

    final TextStyle? style = MaterialStateProperty.resolveAs(decoration!.floatingLabelStyle, materialState)
      ?? MaterialStateProperty.resolveAs(themeData.inputDecorationTheme.floatingLabelStyle, materialState);

    return themeData.textTheme.subtitle1!
      .merge(widget.baseStyle)
      .merge(getFallbackTextStyle())
      .merge(style)
      // Temporary opt-in fix for https://github.com/flutter/flutter/issues/54028
      // Setting TextStyle.height to 1 ensures that the label's height will equal
      // its font size.
      .copyWith(height: themeData.fixTextFieldOutlineLabel ? 1 : null);
  }
```

**Comment by bjartebore** [comment]
I agree

Changing the merge order should be sufficient

```dart
  TextStyle _getFloatingLabelStyle(ThemeData themeData) {
    TextStyle getFallbackTextStyle() {
      final Color color = decoration!.errorText != null
        ? decoration!.errorStyle?.color ?? themeData.errorColor
        : _getActiveColor(themeData);

      return TextStyle(color: decoration!.enabled ? color : themeData.disabledColor)
        .merge(decoration!.floatingLabelStyle ?? decoration!.labelStyle);
    }

    final TextStyle? style = MaterialStateProperty.resolveAs(decoration!.floatingLabelStyle, materialState)
      ?? MaterialStateProperty.resolveAs(themeData.inputDecorationTheme.floatingLabelStyle, materialState);

    return themeData.textTheme.subtitle1!
      .merge(widget.baseStyle)
      // Temporary opt-in fix for https://github.com/flutter/flutter/issues/54028
      // Setting TextStyle.height to 1 ensures that the label's height will equal
      // its font size.
      .copyWith(height: themeData.fixTextFieldOutlineLabel ? 1 : null)
      .merge(getFallbackTextStyle())
      .merge(style);
  }
```

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by moxiaov587** [comment]
Hi, thank you very much for the MaterialStateColor support for iconColor, but the current code seems to have a priority problem, the properties in the separately configured decoration are not used, please see the code.
```dart
Color _getIconColor(ThemeData themeData) {
    Color _resolveIconColor(Set<MaterialState> states) {
      if (states.contains(MaterialState.disabled) && !states.contains(MaterialState.focused))
        return themeData.disabledColor;

      if (states.contains(MaterialState.focused))
        return themeData.colorScheme.primary;

      switch (themeData.brightness) {
        case Brightness.dark:
          return Colors.white70;
        case Brightness.light:
          return Colors.black45;
      }
    }

   /// should it be
   /// return MaterialStateProperty.resolveAs(decoration!.iconColor, materialState) ?? 
   /// MaterialStateProperty.resolveAs(themeData.inputDecorationTheme.iconColor, materialState)
   /// ?? MaterialStateProperty.resolveWith(_resolveIconColor).resolve(materialState);
    return MaterialStateProperty.resolveAs(themeData.inputDecorationTheme.iconColor, materialState)
      ?? MaterialStateProperty.resolveWith(_resolveIconColor).resolve(materialState);
  }

  Color _getPrefixIconColor(ThemeData themeData) {
   /// should it be
   /// return MaterialStateProperty.resolveAs(decoration!.prefixIconColor, materialState) ?? 
   /// MaterialStateProperty.resolveAs(themeData.inputDecorationTheme.prefixIconColor, materialState)
   /// ?? _getIconColor(themeData);
    return MaterialStateProperty.resolveAs(themeData.inputDecorationTheme.prefixIconColor, materialState)
      ?? _getIconColor(themeData);
  }

  Color _getSuffixIconColor(ThemeData themeData) {
   /// should it be
   /// return MaterialStateProperty.resolveAs(decoration!.suffixIconColor, materialState) ?? 
   /// MaterialStateProperty.resolveAs(themeData.inputDecorationTheme.suffixIconColor, materialState)
   /// ?? _getIconColor(themeData);
    return MaterialStateProperty.resolveAs(themeData.inputDecorationTheme.suffixIconColor, materialState)
      ?? _getIconColor(themeData);
  }
```

**Pull request merged**
