### PR TITLE
enabled unnecessary_raw_strings lint

### LINKED ISSUE #77437: Enable unnecessary_raw_strings lint
1. Comment in this line: https://github.com/flutter/flutter/blob/c9d68ba75f73155ca3882e3a17657022f0ac1a89/analysis_options.yaml#L209
2. Run `flutter analyze --flutter-repo --watch`
3. Fix all warnings printed by previous command
4. Create PR

### PR DESCRIPTION
**Pull request by Swayam221**
This PR uncomments line 209 in the analysis_options.yaml file to enable the unnecessary raw strings lint.

Fixes #77437 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
This is test-exempt.

That said, I don't know if it's a good idea. There's a number of cases here where it would be safer to leave the `r''`, in case we ever edit the code. For example, consider something like this:

```dart
  final RegExp separators = RegExp('[/-]');
```
If one day you decide to add backslashes to the list:
```dart
  final RegExp separators = RegExp('[/\-]');
```
...the RegExp will suddenly be invalid.
On the other hand if we use `r''`:
```dart
  final RegExp separators = RegExp('[/-]');
```
...then adding the `\` is safe:
```dart
  final RegExp separators = RegExp(r'[/\-]');
```
There's a number of cases like this in the diff.

**Comment by Swayam221** [comment]
> This is test-exempt because it's essentially adding a test.
> 
> That said, I don't know if it's a good idea. There's a number of cases here where it would be safer to leave the `r''`, in case we ever edit the code. For example, consider something like this:
> 
> ```dart
>   final RegExp separators = RegExp('[/-n]');
> ```
> 
> If one day you decide to add backslashes to the list:
> 
> ```dart
>   final RegExp separators = RegExp('[/-\n]');
> ```
> 
> ...the RegExp will suddenly be doing something very different than we think it is (notably, it will not be allowing backslashes, instead it will be allowing newlines).
> 
> On the other hand if we use `r''`:
> 
> ```dart
>   final RegExp separators = RegExp('[/-n]');
> ```
> 
> ...then adding the `\` is safe:
> 
> ```dart
>   final RegExp separators = RegExp(r'[/-\n]');
> ```
> 
> There's a number of cases like this in the diff.

So, should i find cases like these and convert them to the form of r' ', and edit the PR?

**Comment by Swayam221** [comment]
> This is test-exempt because it's essentially adding a test.
> 
> That said, I don't know if it's a good idea. There's a number of cases here where it would be safer to leave the `r''`, in case we ever edit the code. For example, consider something like this:
> 
> ```dart
>   final RegExp separators = RegExp('[/-n]');
> ```
> 
> If one day you decide to add backslashes to the list:
> 
> ```dart
>   final RegExp separators = RegExp('[/-\n]');
> ```
> 
> ...the RegExp will suddenly be doing something very different than we think it is (notably, it will not be allowing backslashes, instead it will be allowing newlines).
> 
> On the other hand if we use `r''`:
> 
> ```dart
>   final RegExp separators = RegExp('[/-n]');
> ```
> 
> ...then adding the `\` is safe:
> 
> ```dart
>   final RegExp separators = RegExp(r'[/-\n]');
> ```
> 
> There's a number of cases like this in the diff.

@Hixie I get your point completely. But similarly it can be said that if someday we want to want to allow newlines by 
`final RegExp separators = RegExp('[/-\n]');`
and having this regexp in the form of a raw string like 
`final RegExp separators = RegExp(r'[/-\n]');`
,would then completely change the meaning to allow backslashes instead, right?
I think that what has to be in that RegExp() argument has to be thought by and is completely dependent on the developer/user's logic and the lint only tells if there is no backslash, making it a raw string is unnecessary. and on the other hand if there is a backslash in the string, it depends on the user that if he want the string to be raw or not. 
Am I thinking this correctly? 😅

**Comment by Swayam221** [comment]
@goderbauer Please review this PR.

**Comment by goderbauer** [comment]
I am with Hixie, now that I look at it, this lint doesn't seem that useful. Sorry about it.

**Comment by Swayam221** [comment]
> I am with Hixie, now that I look at it, this lint doesn't seem that useful. Sorry about it.

No worries sir, Thank You!

**Comment by a14n** [comment]
Enabling locally `unnecessary_string_escapes` I found this PR just before sending mine.

> If one day you decide to add backslashes to the list [...] the RegExp will suddenly be doing something very different than we think it is

@Hixie @goderbauer this risk is quite limited. Thanks to the [unnecessary_string_escapes](https://dart-lang.github.io/linter/lints/unnecessary_string_escapes.html) lint this issue with backslash could happen only if it is before a [limited number of chars](https://github.com/dart-lang/linter/blob/ce5c72d5e72454e92b27a397d5a15a1cc5d2db2e/lib/src/rules/unnecessary_string_escapes.dart#L129-L142). And even in those cases the IDE (at least VSCode) will use a different color from the surrounding string to enlight the escaped character. So I would be in favour of enabling it.

**Comment by Hixie** [comment]
We did enable `unnecessary_string_escapes` IIRC but I have to say I'm not a big fan of that one either. It leads to weird things like:
```dart
  foo(
    'Hello '
    'World '
    "How're "
    'you '
    'doing?'
  );
```
...which I find quite displeasing personally. It just makes for so much faffing around when you're editing strings. I would have much preferred if we just used `'` everywhere and were find with `\'` where appropriate.

**Comment by a14n** [comment]
We could tweak the lint to ignore adjacent strings.

**Comment by Hixie** [comment]
I mean, the same thing happens with:
```dart
 print('Hello!');
 print("Aren't you...");
 print('My old friend bob?');
```

**Pull request closed without merging**
