### PR TITLE
Remove json_schema and cli_util deps from flutter_tool

### LINKED ISSUE #28019: Remove dependency on json_schema from flutter_tools
The transitive closure is too large

### LINKED ISSUE #28021: Get rid of dependency on json_schema from tool
json_schema 2.0.0+ added a bunch of transitive dependencies.  We don't want to bring these into the tool.

We only use this package to validate pubspec.yaml.  We should avoid the depdendency altogether and validate pubspec.yaml in some other way.

/cc @jonahwilliams

### PR DESCRIPTION
**Pull request by dnfield**
Fixes #28019 
Fixes https://github.com/flutter/flutter/issues/28021

Eliminates dependencies on json_schema and dart2_constant from flutter_tool

cli_util usage was removed in https://github.com/flutter/flutter/pull/16979 but just never updated pubspec.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
If we already have some test coverage on the validation? If not it should be straightforward to add some valid/invalid tests

**Comment by dnfield** [comment]
There are some tests that hit this but can add more.

**Comment by jonahwilliams** [comment]
If we cover basic validation then I am ok with it as is. If the tests use the filesystem though this might be a good chance to replace it with a faster unit test

**Comment by dnfield** [comment]
Nah these all pass in strings and test the strings.  Some of them test memoryFS to make sure it works with this too.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
