### PR TITLE
Clean up the bindings APIs.

### PR DESCRIPTION
**Pull request by Hixie**
* Add more documentation.
* Make accesses to `instance` not required `!`.
* Rationalize our "ensureInitialized" etc logic.

### CODE REVIEW

**Comment by Hixie** [comment]
Fixes https://github.com/flutter/flutter/issues/64830

**Comment by Hixie** [comment]
Still need to go through the tests to make sure the ones that are making dubious use of the binding API are cleaned up.

**Comment by goderbauer** [comment]
(PR triage) @Hixie says this needs some more thorough work on the engine first.

**Comment by Hixie** [comment]
I'll submit a new PR when this is ready.

**Pull request closed without merging**
