### PR TITLE
Adds support for floating cursor

### LINKED ISSUE #17030: Support keyboard cursor move on iOS
On iOS, 3d force pressing and moving around on the keyboard moves the cursor in text fields. Recreate that effect for Flutter text fields.

### PR DESCRIPTION
**Pull request by jslavitz**
Adds framework support for the floating cursor for text editing on iOS. It can be triggered by either a force press on the keyboard or (on iOS 12) by long pressing the spacebar. Fixes #17030 (#5445, #24761).

### CODE REVIEW

**Comment by xster** [comment]
LGTM. Check devicelab tests before merging.

**Comment by eseidelGoogle** [comment]
I'm so happy to see this landing!

**Comment by AppleEducate** [comment]
Is this working on the master branch? I have still not got this to work in any of my flutter apps?

**Comment by anderscheow** [comment]
I need this badly as it does not provide full iOS experience!

**Comment by xster** [comment]
This is on the dev branch since 1.1.3. It should be out on beta in the next few days.

**Pull request merged**
