### PR TITLE
re-enable lint unnecessary_const

### PR DESCRIPTION
**Pull request by a14n**
Original PR #19342 reverted by #19423

### CODE REVIEW

**Comment by a14n** [comment]
@Hixie

**Comment by Hixie** [comment]
RSLGTM

If the performance regresses again, we will have to revert.

**Comment by a14n** [comment]
Feel free to revert on performance issue (I don't think I have access to the performance dashboard to see if this PR make performances regress)

**Comment by tvolkert** [comment]
Sorry, but I'm gonna revert this because Fuchsia has not yet fully migrated to Dart 2 (something I'm working on fixing).  I'll re-apply once it's ready.

**Comment by a14n** [comment]
@tvolkert is it good now to reland this? (re. https://github.com/flutter/plugins/pull/682#issuecomment-409449988)

**Comment by tvolkert** [comment]
Yep, this can re-land now.  Thanks!

**Pull request merged**
