### PR TITLE
WIP TextField Vertical Alignment

### LINKED ISSUE #29927: Textfield text is centered vertically when expands = true and using an OutlineInputBorder
The new changes from @justinmc (#27205 and then #29250) are great but still leave me with a problem. When I set my textfield to expanded, the text is then centered vertically, whereas I want it to be at the top. I can't figure out a way to do this.

I would expect the behaviour of expands to be the same as setting maxlines; that is, the text would stay at the top.

If the default cannot be changed (and now would be the time since it was only introduced recently) then an option to align the text vertically when expanded = true would be great.

### PR DESCRIPTION
**Pull request by justinmc**
Closes https://github.com/flutter/flutter/issues/29927

TextFields currently vertically center their text when they have an outline border.  The difference between this and top alignment is almost nothing in most cases except when the input is very tall (see issue).  We need to decide if we need that vertically centering functionality at all, and if so, when exactly.

Currently, this PR is just an exploration of how we could force top alignment, since according to https://github.com/flutter/flutter/issues/29927#issuecomment-476446043, we may not need this vertical centering at all.

### CODE REVIEW

**Comment by justinmc** [comment]
@HansMuller I need your advice on this.

Someone opened an issue (https://github.com/flutter/flutter/issues/29927) because tall text fields with an outline vertically center the text:



But without an outline it's aligned to the top:



I think this was on purpose originally, but the material spec may have since changed, because Will is saying that all multiline inputs should be aligned to the top: https://github.com/flutter/flutter/issues/29927#issuecomment-476446043

There are several things we could do here, from providing param(s) to allow the user to set the vertical alignment, to getting rid of vertical centering altogether. What do you think?

**Comment by HansMuller** [comment]
@justinmc I don't think it would be a good idea to change the default layout of (multiline) outlined textfields however I agree that the aligning the text to the top makes more visual sense.  The safest path would be to introduce a parameter that does the job. It might be useful to define this new parameter in a way that allows for bottom-alignment, or arbitrary vertical alignment.

**Comment by justinmc** [comment]
After discussing this, I am going to investigate providing a new parameter that specifies the vertical alignment as a range, with top, center, and bottom constructors.

**Comment by justinmc** [comment]
Note to self: make sure that the solution here considers the `alignLabelWithHint` param.  See https://github.com/flutter/flutter/issues/18081#issuecomment-487926914.

**Comment by justinmc** [comment]
I just messed this PR up badly somehow...  It is not merged into master.  I will try to recover my code and open a new PR.

**Pull request closed without merging**
