### PR TITLE
Make the pub roller bot re-generate gradle lockfiles

### LINKED ISSUE #142475: generate_gradle_lockfiles is not run on CI
I think we should run [generate_gradle_lockfiles](https://github.com/flutter/flutter/blob/1d5c2c51187e5c608f36e81d6f89c1782918ab85/dev/tools/bin/generate_gradle_lockfiles.dart) on (pre/post – idk)submit tests. 

### Problems

Sometimes, regenerating gradle lockfiles results in git changes. I don't think that it should be happening, i.e. the running:

```
find . -type d -name 'android' | dart dev/tools/bin/generate_gradle_lockfiles.dart
```

should result in no git changes.

Sometimes, it fails altogether (often on different project - look at the logs carefully):

[crash_logs_1.txt](https://github.com/flutter/flutter/files/14089272/crash_logs_1.txt)

[crash_logs_2.txt](https://github.com/flutter/flutter/files/14089273/crash_logs_2.txt)

I didn't debug thse crashes further but usually re-reunning results in a different failure.

### PR DESCRIPTION
**Pull request by gmackall**
Fixes https://github.com/flutter/flutter/issues/142475

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by goderbauer** [comment]
(triage): I spoke to @gmackall last week and he says this is still on his radar.

**Comment by christopherfujino** [comment]
@gmackall FYI, I updated this branch. Turned into somewhat of a yak shave, but I updated generate_gradle_lockfiles.dart to no longer require the android directories via stdin (since that would have been awkward to pipe from the packages_autoroller.dart script) and just taught it to discover these all itself.

**Comment by gmackall** [comment]
> @gmackall FYI, I updated this branch. Turned into somewhat of a yak shave, but I updated generate_gradle_lockfiles.dart to no longer require the android directories via stdin (since that would have been awkward to pipe from the packages_autoroller.dart script) and just taught it to discover these all itself.

Wow, thanks for taking the time to do that! This looks great to me, but I can't technically approve because it is my PR

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
