### PR TITLE
Change async stubbing to use thenAnswer.

### PR DESCRIPTION
**Pull request by alanrussian**
Mockito now prohibits calling thenReturn with Futures and Streams. dart-lang/build#4833

### CODE REVIEW

**Comment by alanrussian** [comment]
We have to do a pub release for mockito. It's going to be a 3.0 alpha release. I'll update the pull request with that shortly.

**Comment by Hixie** [comment]
Please make sure you did the pubspec.yaml fixes by running `flutter update-packages --force-upgrade`, not by hand. Thanks.

**Comment by alanrussian** [comment]
Hey @Hixie. Ted did a [new release of Mockito](https://pub.dartlang.org/packages/mockito/versions/3.0.0-alpha). It's an alpha release. When I run that command, it updates it to the latest stable release, not alpha release.

Is there anything I can do to update the deps to the alpha release? I just don't want anyone to cause an accidental breakage in the future.

**Comment by Hixie** [comment]
It probably means some other package we depend on depends on a range that doesn't include the new version.

**Comment by alanrussian** [comment]
Ok, I'll just revert the dep change then. Thanks.

**Comment by Hixie** [comment]
Rather than `_`, can you give the type and name of the argument for these callbacks? That will make it easier to understand the code later (when someone looks at the code and wonders what the argument is...).

Other than that, LGTM.

**Comment by alanrussian** [comment]
Done. Thank you.

**Comment by alanrussian** [comment]
The lint checks seem to require specifying a type for function expressions. I'm not sure why since this is against Effective Dart (https://www.dartlang.org/guides/language/effective-dart/design#avoid-annotating-types-on-function-expressions). I guess the Flutter style guide is different?

@Hixie How strongly do you feel about "_"? I think reading "Invocation invocation" on each of these is overkill. It looks like there were several calls to thenAnswer with "_" already.

**Comment by Hixie** [comment]
Flutter's codebase is intended to be fully typed, so that we don't rely on inference or dynamic. It has frequently helped us catch bugs.

I prefer to have the argument be explicit (in type and in name, so that I can see what it is, and what it means), because otherwise whenever I read this code I'm going to think, "ooh, an argument, I wonder what that is" and have to go look it up instead of just being able to see it.

If you only provide the type (`.thenAnswer(Invocation _)`) then I'll wonder what the argument is supposed to mean ("is it the "before" invocation? Is it the "answer" of "thenAnswer"? etc). If you only provide the name (`.thenAnswer(invocation)`) then I'll wonder what the type of the argument is. Is it a string? Is it an Invocation? Is it some custom object that is special for "thenAnswer"?

**Comment by alanrussian** [comment]
Got it, thanks for the explanation. I'll update the pull request soon.

Alan

**Comment by alanrussian** [comment]
@Hixie friendly ping. Would love to get this merged and pulled into g3 ASAP.

**Review by yjbanov — APPROVED** [review]

**Comment by alanrussian** [comment]
Thanks!

**Pull request merged**
