### PR TITLE
[flutter_releases] Flutter 2.0.2 Stable Framework Cherrypicks

### PR DESCRIPTION
**Pull request by christopherfujino**
## Scheduled Cherrypicks

- [x] Engine cherrypicks
  * https://github.com/flutter/engine/pull/24928
- [x]  '_initialButtons == kPrimaryButton': is not true. #75061
  * https://github.com/flutter/flutter/pull/75943
  * Original author: @goderbauer 
- [x] Issue with ScaffoldManager and double scaffold #77251
  * https://github.com/flutter/flutter/issues/77251
  * https://github.com/flutter/flutter/pull/77410
  * Original author: @Piinks 
- [x] ProcessException: cannot delete old bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/Resources #77234
  * https://github.com/flutter/flutter/issues/77234
  * https://github.com/flutter/flutter/pull/77316
  * Original author: @jmagman 

## Known Failures
* Devicelab:
  - [x] https://github.com/flutter/flutter/issues/77973
  - [x] `Linux stable android_stack_size_test` - not in prod_builders.json
  - [x] `Linux stable flutter_engine_group_performance` - not in prod_builders.json
  - [x] `Mac_ios stable native_ui_tests_ios32` - not in prod_builders.json
  - [ ] `Mac_ios stable complex_layout_ios__start_up` repeatedly timed out, [builder log](https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20stable%20complex_layout_ios__start_up)
  - [x] `Mac_ios stable platform_views_scroll_perf_ios__timeline_summary` - timed out, [re-run](https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20stable%20platform_views_scroll_perf_ios__timeline_summary/4)
  - [ ] `Mac_ios stable platform_channel_sample_test_swift` - tracking issue https://github.com/flutter/flutter/issues/77981#issuecomment-797192493
  - [x] `Mac_ios stable complex_layout_scroll_perf_ios__timeline_summary` - `fopen failed for data file: errno = 2 (No such file or directory)` passed on re-run.
  - [ ] `Mac_ios stable flutter_gallery__transition_perf_e2e_ios` - bad state no element, https://github.com/flutter/flutter/issues/78047
  - [ ] `Mac_ios stable flutter_gallery_ios__start_up` - repeatedly timed out https://github.com/flutter/flutter/issues/78048
  - [x] `Mac stable dart_plugin_registry_test` - not in prod_builders.json
  - [x] `Mac_ios stable smoke_catalina_hot_mode_dev_cycle_ios__benchmark` - not in prod_builders.json
  - [x] `Mac_ios stable platform_view_ios__start_up` - not in prod_builders.json
  - [x] `Mac_ios stable microbenchmarks_ios` - not in prod_builders.json

### CODE REVIEW

**Comment by christopherfujino** [comment]
I manually overrode the CLAbot because all authors have signed the CLA.

**Review by kf6gpe — APPROVED** [review]

**Review by jmagman — APPROVED** [review]
#77316 LGTM.  https://github.com/flutter/flutter/issues/77173 will also go away once the engine version gets revved.

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by Piinks — APPROVED** [review]
LGTM! Thanks! 🌸

**Comment by jmagman** [comment]
The failing tests passed for me locally:
```
Task result:
{
  "success": true,
  "data": {
    "engineEnterTimestampMicros": 258498883041,
    "timeToFrameworkInitMicros": 175697,
    "timeToFirstFrameRasterizedMicros": 1220647,
    "timeToFirstFrameMicros": 251485,
    "timeAfterFrameworkInitMicros": 75788
  },
  "detailFiles": [],
  "benchmarkScoreKeys": [
    "timeToFirstFrameMicros",
    "timeToFirstFrameRasterizedMicros"
  ]
}


════════════╡ ••• Finished task "complex_layout_ios__start_up" ••• ╞════════════
```
```
Task result:
{
  "success": true,
  "data": null,
  "detailFiles": [],
  "benchmarkScoreKeys": []
}


═════════╡ ••• Finished task "platform_channel_sample_test_swift" ••• ╞═════════
```
```
Task result:
{
  "success": true,
  "data": {
    "average_frame_build_time_millis": 1.226,
    "90th_percentile_frame_build_time_millis": 1.907,
    "99th_percentile_frame_build_time_millis": 11.696,
    "worst_frame_build_time_millis": 31.042,
    "missed_frame_build_budget_count": 6,
    "average_frame_rasterizer_time_millis": 5.026,
    "90th_percentile_frame_rasterizer_time_millis": 16.352,
    "99th_percentile_frame_rasterizer_time_millis": 57.886,
    "worst_frame_rasterizer_time_millis": 181.151,
    "missed_frame_rasterizer_budget_count": 125,
    "frame_count": 952,
    "frame_build_times": [
...
    ]
  },
  "detailFiles": [],
  "benchmarkScoreKeys": [
    "average_frame_build_time_millis",
    "worst_frame_build_time_millis",
    "90th_percentile_frame_build_time_millis",
    "99th_percentile_frame_build_time_millis",
    "average_frame_rasterizer_time_millis",
    "worst_frame_rasterizer_time_millis",
    "90th_percentile_frame_rasterizer_time_millis",
    "99th_percentile_frame_rasterizer_time_millis"
  ]
}


══════╡ ••• Finished task "flutter_gallery__transition_perf_e2e_ios" ••• ╞══════
```
```
Task result:
{
  "success": true,
  "data": {
    "engineEnterTimestampMicros": 259571406885,
    "timeToFrameworkInitMicros": 191307,
    "timeToFirstFrameRasterizedMicros": 1456516,
    "timeToFirstFrameMicros": 302828,
    "timeAfterFrameworkInitMicros": 111521
  },
  "detailFiles": [],
  "benchmarkScoreKeys": [
    "timeToFirstFrameMicros",
    "timeToFirstFrameRasterizedMicros"
  ]
}


═══════════╡ ••• Finished task "flutter_gallery_ios__start_up" ••• ╞════════════
```

**Pull request merged**
