### PR TITLE
Consider crossAxisSpacing and mainAxisSpacing for Edges

### LINKED ISSUE #27151: GridView has unexpected overflow in RTL
`GridView` `crossAxisSpacing` Overflow RTL

When I'm using RTL layout, `GridView` and `crossAxisSpacing`, the children on right overflow the edge of the emulator.

### LTR

screenshot_1549008583

### RTL

screenshot_1549008589

```dart
new GridView.count(
            crossAxisCount: 2,
            padding: const EdgeInsets.all(12.0),
            mainAxisSpacing: 12.0,
            crossAxisSpacing: 12.0,
            children: new List<Widget>.generate(16, (index) {
              return new Container(color: Colors.red,child: new Text(""),);
            }),
          ),
```

### PR DESCRIPTION
**Pull request by p30arena**
Fixes https://github.com/flutter/flutter/issues/27151

### CODE REVIEW

**Comment by p30arena** [comment]
This is the expected result

screenshot_1549016222


```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Directionality(
        textDirection: TextDirection.rtl,
        child: GridView.count(
          crossAxisCount: 4,
          mainAxisSpacing: 10,
          crossAxisSpacing: 10,
          children: List.generate(
            10,
            (index) => Container(
                  alignment: Alignment.center,
                  color: Colors.lightGreen,
                  child: Text("Hello World 2"),
                ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by p30arena** [comment]
```
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during paint():
The getter 'visible' was called on null.
Receiver: null
Tried calling: visible

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:527:26)
#2      RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:521:7)
#3      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
#4      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
#5      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
#6      PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
#7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
#8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/pr
oxy_box.dart:123:15)
#9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
#10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
#11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/pr
oxy_box.dart:123:15)
#12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
#13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
#14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/pr
oxy_box.dart:123:15)
#15     RenderPointerListener.paint (package:flutter/src/rendering/proxy_box.dart:2629:11)
#16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
#17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
#18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/pr
oxy_box.dart:123:15)
#19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
#20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
#21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/pr
oxy_box.dart:123:15)
#22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
#23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
#24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/pr
oxy_box.dart:123:15)
#25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
#26     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
#27     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
#28     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
#29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
#30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/pr
oxy_box.dart:123:15)
#31     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:562:11)
#32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
#33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
#34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/pr
oxy_box.dart:123:15)
#35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
#36     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
#37     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
#38     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
#39     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
#40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/pr
oxy_box.dart:123:15)
#41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
#42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
#43     RenderView.paint (package:flutter/src/rendering/view.dart:178:15)
#44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
#45     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
#46     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
#47     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:853:29)
#48     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:807:27)
#49     _TestWidgetsFlutterBinding&BindingBase&ServicesBinding&SchedulerBinding&GestureBinding&SemanticsBinding&Renderer
Binding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:237:5)
#50     _TestWidgetsFlutterBinding&BindingBase&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/sr
c/scheduler/binding.dart:990:15)
#51     _TestWidgetsFlutterBinding&BindingBase&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/sch
eduler/binding.dart:930:9)
#52     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:714:9)
#55     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#56     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:701:27)
#57     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:250:22)
#60     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#61     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:247:27)
#62     main.<anonymous closure> (file:///M:/flutter/packages/flutter/test/widgets/scrollable_semantics_traversal_order_
test.dart:338:18)
<asynchronous suspension>
#63     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:82:23)
#64     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:566:19)
<asynchronous suspension>
#67     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:550:14)
#68     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:893:24)
#74     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:890:15)
#75     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:81:22)
#76     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer
.dart:168:27)
<asynchronous suspension>
#77     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
<asynchronous suspension>
#82     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
#83     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#88     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#89     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api
/src/backend/invoker.dart:400:25)
<asynchronous suspension>
#103    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#104    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#105    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
(elided 32 frames from class _FakeAsync, package dart:async, and package stack_trace)

The following RenderObject was being processed when the exception was fired:
  RenderViewport#7bbf5
  creator: Viewport ← IgnorePointer-[GlobalKey#d85f3] ← Semantics ← Listener ← _GestureSemantics ←
  RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#da00a] ← _ScrollableScope ←
  _ScrollSemantics-[GlobalKey#e81ec] ← RepaintBoundary ← CustomPaint ← RepaintBoundary ←
  NotificationListener<ScrollNotification> ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=800.0, h=600.0)
  layer: OffsetLayer#89286 DETACHED
  size: Size(800.0, 600.0)
  axisDirection: down
  crossAxisDirection: right
  offset: ScrollPositionWithSingleContext#e4ac9(offset: 1600.0, range: null..null, viewport: 600.0,
  ScrollableState, ClampingScrollPhysics, IdleScrollActivity#1c5c9, ScrollDirection.idle)
  anchor: 0.0
This RenderObject had the following child:
  RenderSliverGrid#ba429 relayoutBoundary=up1 NEEDS-PAINT
```

**Comment by goderbauer** [comment]
Thanks for your contribution!

I am not sure I understand exactly what the goal of this PR is. Its title seems to be unrelated to the linked bug?

The PR seems to be applying the specified `crossAxisSpacing` and `mainAxisSpacing` around the entire grid. That's not what those properties are for. As documented in [1] and [2] they are meant to specify the spacing **between** the tiles of the grid. If you want to change the padding around the grid, use the `padding` [3] property. Changing how `crossAxisSpacing` and `mainAxisSpacing` works would be a breaking change and we try to avoid those. In this case, the change seems unnecessary since we already have the padding property that archives the same thing.

[1] https://master-docs.flutter.io/flutter/rendering/SliverGridDelegateWithFixedCrossAxisCount/crossAxisSpacing.html
[2] https://master-docs.flutter.io/flutter/rendering/SliverGridDelegateWithFixedCrossAxisCount/mainAxisSpacing.html
[3] https://master-docs.flutter.io/flutter/widgets/GridView-class.html

Now for #27151, that is a bug we should fix. Since this PR also includes other changes (as explained above) I cannot tell if this PR is fixing this properly. I'd suggest you revert the unrelated changes. In general, it's usually a good idea to just make one logical change in a PR. This also makes it easier to roll back specific changes if they turn out to break anything after submission.

If you revert those changes, some (hopefully all) of those failing tests should probably be passing again.

Last, but not least, in order for us to accept this PR into our tree as a fix for #27151, you'll also have to add a test for that case to ensure that in the future we never, ever undo your work and break this functionality again.

**Comment by p30arena** [comment]
@goderbauer 
Hi there!

So I was wrong thinking that crossAxisSpacing and mainAxisSpacing should also do the job of padding for both directions.
maybe this was a better name for them:

[cross|main]AxisBetweenChildrenSpacing

**Pull request closed without merging**
