### PR TITLE
Bump Dartdoc version to 6.1.5

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This bumps the Dartdoc version to 6.1.5

## Related Issues
 - https://github.com/dart-lang/dartdoc/issues/3265
 - https://github.com/dart-lang/dartdoc/issues/3204

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
What do you think about filing a cherry-pick request for this change? This version includes some nice usability improvements that would be nice to have on stable as well.

**Comment by gspencergoog** [comment]
Seems reasonable to me.  It's low risk, since it doesn't affect the framework code, just the doc generation.

**Comment by gspencergoog** [comment]
I'll make a CP request.

**Pull request merged**
