### PR TITLE
[flutter_tools] Ensure that global variables are easily identifiable

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

In order to track the effectiveness of https://github.com/flutter/flutter/issues/47161 , we should track where most global variables are used throughout the tool. This PR introduces and enforces the practice of importing globals.dart as globals and accessing these members through a prefix.

### CODE REVIEW

**Comment by zanderso** [comment]
Could you highlight and/or link to the files containing non-mechanical changes?

**Comment by jonahwilliams** [comment]
The benchmark is https://github.com/jonahwilliams/flutter/blob/2a9f0142d639c8483269ac479536b7c7f6f201bd/dev/devicelab/bin/tasks/technical_debt__cost.dart

platform.dart and process manager dart were deleted and moved into globals.

Forbidden imports test now has a clause ensuring globals is imported with a prefix.

globals has fs, terminal, platform, and processManager

**Review by zanderso — COMMENTED** [review]
Overall lgtm. Others should also take a look.

`globals.print{Error,Status,Trace}()` is a bit verbose, but IIUC after the refactoring these will be `logger.printError()` or maybe `log.printError()`, right? I guess the tech debt calculator would get some false positives if globals were imported with a shorter prefix like 'g' ?

**Comment by jonahwilliams** [comment]
>  I guess the tech debt calculator would get some false positives if globals were imported with a shorter prefix like 'g'

`g.` would probably not trigger than many false positives. Though I also think you should feel a _little_ bad when using a global variable

**Review by jmagman — COMMENTED** [review]
Can we add a `verifyGlobalImports` check to `dev/bots/analyze.dart` to check for globals.dart imports missing `as globals`?  I feel like it may not take us long to forget to do this in new files.

**Review by jmagman — APPROVED** [review]
Actually you can do my verifyGlobalImports suggestion in another commit, you better land this ASAP or you're gonna have a bad merge time.

**Comment by jonahwilliams** [comment]
I have a test added in forbidden_imports.dart that ensures that globals are imported 'as globals'

**Comment by jmagman** [comment]
> I have a test added in forbidden_imports.dart that ensures that globals are imported 'as globals'

source

I see your comment to @zanderso now. Merge quick!

**Review by blasten — APPROVED** [review]
This is a great step forward, thanks!  Would the chart automatically appear on https://flutter-dashboard.appspot.com/benchmarks.html after merging this PR?

**Comment by jonahwilliams** [comment]
Updated, lets see if I can land it today :)

**Comment by jonahwilliams** [comment]
> This is a great step forward, thanks! Would the chart automatically appear on https://flutter-dashboard.appspot.com/benchmarks.html after merging this PR?

Yup!I'll need to set the baseline correctly, but as long as we regularly re-baseline this should prevent us from introducing more globals.

**Comment by christopherfujino** [comment]
I know this is after the fact, but this is great! Makes the code look a lot less magical.

**Pull request merged**
