### PR TITLE
added DrawerListener for drawer open and close events to the scaffold

### PR DESCRIPTION
**Pull request by StorminGorman**
I needed a way to know when the Drawer was opening or closing.  Since there was no hook for that yet through the Scaffold I put one in.

### CODE REVIEW

**Comment by StorminGorman** [comment]
I signed it!

**Comment by Hixie** [comment]
Why do you need to know if the drawer is open?

**Comment by StorminGorman** [comment]
Well, I am working on implementing a design that calls for an element to be spanning both the AppBar and Body of the Material scaffold.  
screenshot_20180515-075846

The only way to get this to work that I could think of was to use a Stack.

` return new Stack(
        children: <Widget>[
          new Scaffold(
            drawerListener: this,
            appBar: new AppBar(),
            drawer: new GardenDrawer(context, user),
            body: new _LandingBody(),
          ),
          !hideLogo ? new Row(
            children: <Widget>[
              new Container(
                child: new Image.asset(
                  'images/logo_shadow.png',
                  width: 100.0,
                  height: 100.0,
                  fit: BoxFit.scaleDown),
                  margin: new EdgeInsets.fromLTRB(0.0, 40.0, 0.0, 0.0)
              )
            ],
            crossAxisAlignment: CrossAxisAlignment.end,
            mainAxisAlignment: MainAxisAlignment.center,
          ) : new Container(),
        ]
    );`

The problem is that Since the Drawer is part of the Scaffold the Image appears _on top_ of the drawer when the drawer opens.  I needed a hook into the events of the drawer in order to hide/show that image.  I know that is hacky and maybe I should implement my own scaffold but this seemed to me to be the quickest way to get this prototype up and running.  I decided to submit the pull request because I thought there might be other unforeseen reasons why a developer might want to execute arbitrary code when the drawer opens/closes.

**Comment by Hixie** [comment]
Easiest way to do what you describe is to put the AppBar in a Column with crossAxisAlignment set to stretch, then put the body in an Expanded in that column below it. Then, put that Column in a Stack, and use the Stack to position the image on top of the AppBar. Or, use a CustomMultiChildLayout to lay out the appbar, body, and flower image, using the "body" slot of the Scaffold to do this. Then you don't need to remove the image when the drawer opens.

**Comment by Hixie** [comment]
I'm going to close this PR based on my last comment, but please don't hesitate to file a bug or contact me if that wasn't sufficient. I'm not against the idea in this PR, just avoiding adding code that isn't strictly necessary. If it turns out it's necessary after all, we should definitely consider adding it.

**Pull request closed without merging**
