### PR TITLE
Warn when Gradle plugins are applied using the legacy "apply script method" way

### PR DESCRIPTION
**Pull request by bartekpacia**
This PR adds a deprecation message when Android build is using the legacy "apply script method" way of applying Flutter's Gradle plugins (that is: [`flutter.gradle`](https://github.com/flutter/flutter/blob/3.16.0/packages/flutter_tools/gradle/flutter.gradle) and [`app_plugin_loader.gradle`](https://github.com/flutter/flutter/blob/3.16.0/packages/flutter_tools/gradle/app_plugin_loader.gradle)).

See also:
- #121541
  - in particular https://github.com/flutter/flutter/issues/121541#issuecomment-1836947311
- #135392
  - and PR that add the migration guide: [#9857](https://github.com/flutter/website/pull/9857)

- I think either `logger.error` or `logger.quiet` must be used, because all other error levels are not shown during `flutter build apk` (and that's what most people use).

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by bartekpacia** [comment]
- The URL currently linked to is temporary. It'll likely be some `go/xyz` link once the migration gudie (https://github.com/flutter/website/pull/9857) is merged.

**Comment by bartekpacia** [comment]
This change should very likely be included in Flutter's "at least 1 year or 4 releases, whichever longer" deprecation policy.

**Comment by reidbaker** [comment]
@christopherfujino what level of error/warning do you want to see here. I can see us using error because we want folks to know but also I can see someone being annoyed at an error (I am thinking of our own testing infra) that is actually a warning. 

These messages pass both the warning and error guidance in our styleguide. https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#only-log-actionable-messages-to-the-console

**Comment by reidbaker** [comment]
FWIW if you wanted to add a test I believe there are a few integration tests that check for log messages. 
I think dev/integration_tests would be a good starting point.

**Comment by bartekpacia** [comment]
> if you wanted to add a test I believe there are a few integration tests that check for log messages.

@reidbaker I don't think a test is necessary here.

**Comment by bartekpacia** [comment]
> I can see us using error because we want folks to know but also I can see someone being annoyed at an error (I am thinking of our own testing infra) that is actually a warning.

Yeah, I understand, but I haven't found a way for a tool to display a warning (say, yellow text) _always_, not only when run with `--verbose`.

Also, I'm happy to volunteer to fixing (_as much as necessary_ amount) of migrating to declarative plugin apply.

**Comment by reidbaker** [comment]
> > if you wanted to add a test I believe there are a few integration tests that check for log messages.
> 
> @reidbaker As much as I'm a fan of testing, I don't think a test is necessary (or even would bring any value) here.

The value would come from making sure we dont accidentally stop logging this message. That said I am ok with this landing since the consequence is the same as the current behavior.

**Review by reidbaker — APPROVED** [review]

**Comment by bartekpacia** [comment]
Should I get test exemption from Hixie or Stuart Morgan?

**Comment by reidbaker** [comment]
Yep that is the process.

**Comment by matanlurey** [comment]
test-exempt: no changes to the app, just a logging message as part of a deprecation.

**Comment by bartekpacia** [comment]
Thanks @matanlurey :D

**Pull request merged**
