### PR TITLE
Fix timepicker size change when input incorrect time

### LINKED ISSUE #103353: Web - Invalid value in Timepicker (input mode) changes input field size.
## Steps to Reproduce

1. Execute `flutter run` on the code sample or open [Dartpad example](https://dartpad.dev/?id913731a95aca676eef367372e822b769)
2. When I change the timepicker to manual input mode and then give invalid values like hours > 24 or Minutes > 60 then the size of the invalid box changes and shrinks. (see images)

**Expected results:** 
The expected result would be that the box does not get smaller, when the value is invalid.
flutter_bug_expected
**Actual results:** 
The Box gets smaller when an invalid value is used.
flutter_bug

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter TimePicker',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() {
    return _MyHomePageState();
  }
}

class _MyHomePageState extends State<MyHomePage> {
  TimeOfDay selectedTime = TimeOfDay.now();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Flutter TimePicker"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: () {
                _selectTime(context);
              },
              child: Text("Choose Time"),
            ),
            Text("${selectedTime.hour}:${selectedTime.minute}"),
          ],
        ),
      ),
    );
  }

  _selectTime(BuildContext context) async {
    final TimeOfDay? timeOfDay = await showTimePicker(
      context: context,
      initialTime: selectedTime,
      initialEntryMode: TimePickerEntryMode.dial,
    );
  }
}

```

</details>

**Tested on**
- stable 2.10.5
- beta 2.13.0 - 0.3.pre

### PR DESCRIPTION
**Pull request by tomcheung**
Fix #103353

time picker screenshot

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
@tomcheung Can you please add a test for this?

**Comment by tomcheung** [comment]
@goderbauer I am trying to add a test case in `time_picker_test.dart` to check EditableText size is change when the error message is appear using following code:

```dart
  testWidgets('DatePickerDialog size should not change in web', (WidgetTester tester) async {
    await mediaQueryBoilerplate(tester, true, entryMode: TimePickerEntryMode.input);
    await tester.enterText(find.byType(TextField).at(1), '99');
    final Size inputSize = tester.getSize(find.byType(EditableText).at(1));

    await tester.tap(find.text('OK'));
    await tester.pumpAndSettle();

    final Size inputSizeWhenError = tester.getSize(find.byType(EditableText).at(1));
    expect(inputSize, equals(inputSizeWhenError));
  });
```

However It look like `flutter_test` is not using Chrome (CanvasKit) for testing, so the size is same **before** the fix (also time_picker_test is skip web platform test by annotate `@TestOn('!chrome')`), can you give some suggestion how to test on this issue

**Comment by Hixie** [comment]
@tomcheung thanks for your contribution! Do you know why this patch fixes the bug? (That would help me help you write a test.)

**Comment by tomcheung** [comment]
@Hixie, Thanks for your comment, you can reference to this [related comment](https://github.com/flutter/flutter/issues/75837#issuecomment-1129086795), the problem is come from Skin library didn't hide the error label we are using `errorStyle: const TextStyle(fontSize: 0.0, height: 0.0)` in web (it look like have minimum font size, and but app don't have), so in this PR is use private modified version of `_TimePickerTextFormField ` base on `TextFormField`

In `_TimePickerTextFormField`, it will only pass `InputDecoration` to `TextField` without `.copyWith(errorText: field.errorText)`, because InputDecoration have not `errorText` inside, the error message won't be shown while it can keep using `FormField` validation function

Another less hacky way is implement the own validation logic without using `TextFormField` validation feature, however it require lot change and may break existing functionality

**Comment by hterkelsen** [comment]
I have an upstream fix for this in CanvasKit, so this PR should be unnecessary: https://skia-review.googlesource.com/c/skia/+/593616

**Comment by tomcheung** [comment]
@hterkelsen thanks, let me close the PR

**Pull request closed without merging**
