### PR TITLE
Add shouldRebuild argument to ValueListenableBuilder to control rebuilds

### PR DESCRIPTION
**Pull request by MohiuddinM**
Right now the ValueListenableBuilder widget rebuilds every time the value of the ValueListenable changes. This PR keeps this default behavior but adds an optional argument called shouldRebuild that can be used to control widget rebuilds. This enhances performance by avoiding useless rebuilds,

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by cedvdb** [comment]
In what scenario would you not want to rebuild and wouldn't it be niche enough to just not use ValueListenableBuilder ?

**Comment by MohiuddinM** [comment]
> In what scenario would you not want to rebuild and wouldn't it be niche enough to just not use ValueListenableBuilder ?

There are many cases but the reason I added this is because of performance improvements in cases where value listenable contains a lot of properties but you wanna only rebuild when a particular property changes:

```
final ValueListenable<Cart> cartNotifier = ValueNotifier<Cart>(
  Cart(
   ...
    items: [],
  ),
);

ValueListenableBuilder<Cart>(
  valueListenable: cartNotifier,
  builder: (BuildContext context, Cart cart, Widget? child) {
    return Bubble(
      text: Text(cart.items.length.toString()),
      child: child,
    );
  },
  shouldRebuild: (Cart? last, Cart current) => last?.items.length != current.items.length;
);
```

In the above example, I only want to rebuild the icon when something is added or removed from the cart and want to prevent useless rebuilds when other properties keep changing.

**Comment by MohiuddinM** [comment]
Can someone look into it? @jacob314 @polina-c  I don't think the smoke test is failing because of any problem with the code.

**Comment by goderbauer** [comment]
You can already do this today by wrapping your Listenable in another listenable that only notifies their listeners when the condition is met. I don't think we should add specific API to this to ValueListenableBuilder because I believe this could be an easy foot gun where your UI goes out if sync with your data because the UI is not rebuilt on every notification.

**Comment by MohiuddinM** [comment]
> You can already do this today by wrapping your Listenable in another listenable that only notifies their listeners when the condition is met. I don't think we should add specific API to this to ValueListenableBuilder because I believe this could be an easy foot gun where your UI goes out if sync with your data because the UI is not rebuilt on every notification.

Thanks for the feedback @goderbauer:
1. For our internal use we are using the exact same thing just with a different name 😄(also why I want to contribute this feature). We also experimented with warping and then using an extension method but found that less intuitive and performant. 
2. I understand your concern regarding a difference that can arise between the Listenable value, and what is shown on the UI. I would think that the effects are limited only to the assumptions a developer has about rebuild behavior and not any carry-on side effects in the app. Since it is an optional opt-in feature just like the child argument, will it be possible to address the concern you raised by adding an explicit doc comment for this argument, that would explain to the developer that using this argument can result in a difference?

**Comment by goderbauer** [comment]
I still don't think we should add this to the framework as a doc comment is easy to miss and it is an API that can have surprising side effects. Also, not having this in the framework will not block any functionality as this can easily be implemented on top of the framework if desired.

**Pull request closed without merging**
