### PR TITLE
[flutter_tools] add snapshot analysis dependency

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Add snapshot analysis dependency for APK size analysis tool

### CODE REVIEW

**Comment by jonahwilliams** [comment]
@kenzieschmoll has this been rolled into google3?

**Review by peterdjlee — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
(Looks like it has)

**Comment by kenzieschmoll** [comment]
Sorry for the late reply - yes `version: 0.5.1-dev.1` is in google3

**Pull request merged**
