### PR TITLE
Revert isolate platform channels because of google integration tooling

### PR DESCRIPTION
**Pull request by gaaclarke**
This has to be reverted because of integration problems with google's internal tooling.

see also:
1) https://github.com/flutter/flutter/issues/111701
1) b/246785281

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gaaclarke** [comment]
Looks like the revert bot can't handle PR's that revert multiple commits, fyi @godofredoc.

**Review by godofredoc — APPROVED** [review]

**Comment by godofredoc** [comment]
> Looks like the revert bot can't handle PR's that revert multiple commits, fyi @godofredoc.

@ricardoamador FYI

**Comment by godofredoc** [comment]
> as to be reverted because of integration problems with google's internal tooling.

Actually @gaaclarke was this created from the UI or manually created?

**Review by chingjun — APPROVED** [review]

**Comment by dnfield** [comment]
This seemed off to me but I assumed a test would catch it if we were really doing it wrong.

**Comment by ricardoamador** [comment]
It would not handle this. This is a manual revert and not a revert initiated through the UI.

**Comment by gaaclarke** [comment]
@godofredoc @ricardoamador The revert was made by hand since the UI can't revert multiple PRs (that I know of).  Is there any real requirement that the UI made it beyond a PR description that matches a format the bot can parse?

**Comment by ricardoamador** [comment]
The UI can revert multiple PRs. You just need to revert them individually which is probably preferable for tracking purposes rather than wrapping multiple commits from different PRs. 
https://github.com/flutter/flutter/wiki/Tree-hygiene#avoid-revert-revert-revert-revert-fix-foo-commit-messages

**Comment by ricardoamador** [comment]
There is doing to be some validation to the original PR you are reverting which is why it is looking for a link. If this was reverted through the UI everything would have been done automatically for you.

**Comment by ricardoamador** [comment]
But as I hinted at, you will be able to do what you just did shortly. Once I have our pipeline setup for this I will update it again to allow this type of revert.

**Pull request merged**
