### PR TITLE
Rename Image.fromNetwork and Image.fromAssetBundle

### PR DESCRIPTION
**Pull request by abarth**
These now have sorter names to make the callers less verbose.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

**Comment by Hixie** [comment]
code semantics LGTM. the formatting, I dunno. It's kinda weird. Especially for those cases with a single named argument. Not sure how to improve it though. Maybe just put them on the same line? And put a newline before the positional when there's more than one arg? as in:

```dart
              child: new Image.asset(
                  icon,
                  width: _kWeatherIconSize,
                  height: _kWeatherIconSize
                )
```

```dart
        child: new Image.asset(destination.assetName, fit: ImageFit.cover)
```

Either way LGTM.

**Comment by dragostis** [comment]
@Hixie Seems like a reasonable way to format it. LGTM

**Comment by abarth** [comment]
I put it all on one line if it roughly fit in 80 cols, otherwise I added a newline before the position argument.

**Pull request merged**
