### PR TITLE
upgrade to linter-0.1.30

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by Hixie** [comment]
I'm surprised to see the const cases.


Is the list of lints in the options files here comprehensive, or are there any lints that exist but aren't listed? If there are any that aren't listed, please add them, but commented out, with an extra comment briefly mentioning why.

**Comment by Hixie** [comment]
LGTM

**Comment by a14n** [comment]
The list is comprehensive regarding the changes here. All the const added were detected by the `prefer_const_constructors` lint.

**Comment by Hixie** [comment]
What I meant was are there lint names defined by the analyzer with this package that aren't listed in our .analysis_options file?

**Pull request merged**
