### PR TITLE
Run `flutter update-packages --force-upgrade`.

### PR DESCRIPTION
**Pull request by pennzht**
## Description

I ran `flutter update-packages --force-upgrade`, in order to bump up the version of `flutter_gallery_assets` to `0.2.1`, to reconcile with the version used in flutter/gallery.
This PR contains the changes made to all `.yaml` files after running the command.

This change is required for the following PRs:
* [Add Web Benchmarks for Flutter Gallery (Flutter Side)](https://github.com/flutter/flutter/pull/57576)
* [Add Web Benchmarks for Flutter Gallery (Gallery Side)](https://github.com/flutter/gallery/pull/163)

I decided to submit this as a separate PR, so that the version changes won't clutter the changes I make for the 2 PRs above.

## Related Issues

https://github.com/flutter/gallery/issues/103

## Tests

This is a version update. It does not require tests.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] ~I updated/added relevant documentation (doc comments with `///`).~
    * This is a version update. It does not require documentation.
- [ ] ~All existing and new tests are passing.~
    * This is a version update.
    * I only ran tests in `packages/flutter/test/`. They all passed.
    * **tool_tests-commands-{linux,macos,windows} are failing.**
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
    * This is a version update.
    * I only ran tests in `packages/flutter/test/`. They all passed.
    * **tool_tests-commands-{linux,macos,windows} are failing.**

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by yjbanov — APPROVED** [review]

**Comment by yjbanov** [comment]
@jonahwilliams could you please assist @pennzht with this PR? The tools tests are failing to run `pub get` for some reason.

**Comment by jmagman** [comment]
The error is
```
Because test >=1.13.0 <1.14.5 depends on test_api 0.2.15 and every version of flutter_driver from sdk depends on test_api 0.2.16, test >=1.13.0 <1.14.5 is incompatible with flutter_driver from sdk.
So, because flutter_project depends on both flutter_driver any from sdk and test 1.13.0, version solving failed.
```

**Comment by yjbanov** [comment]
@jonahwilliams said:

> you need to update https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/pubspec.yaml.tmpl#L49
> possibly other lines in the pubspec.yaml

**Comment by yjbanov** [comment]
> @jonahwilliams said:
> 
> > you need to update https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/app/pubspec.yaml.tmpl#L49
> > possibly other lines in the pubspec.yaml

@Hixie Shouldn't `flutter update-packages --force-upgrade` do this automatically?

**Comment by jonahwilliams** [comment]
no, thats why we have the test

**Comment by pennzht** [comment]
@jonahwilliams 
> no, thats why we have the test

Thank you very much for your message!
How should we resolve this issue (without breaking more tests)?

**Review by clocksmith — APPROVED** [review]

**Review by HansMuller — APPROVED** [review]
LGTM

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
If we pin the `test` package in the Flutter SDK, should we just be depending on the `test` package as `any` instead of with a fixed version? It seems like having a fixed version here means that we'll be making life harder on developers to upgrade Flutter later.

**Comment by jonahwilliams** [comment]
We could also give it a caret `^`. I think `any` dependencies should probably be avoided unless a user is specifically experimenting, so I'd be worried that adding it to the template would precipitate a bad practice

**Pull request merged**
