### PR TITLE
Translate Flutter to Norwegian

### LINKED ISSUE #15439: showDialog throws an exception when localizing an app to a language not found in `MaterialLocalizationsDelegate`
## Steps to Reproduce

I'm using Flutter to write an app that must be localized in norwegian and english. I declared support for both languages using  `supportedLocales` in my main app widget.
At some point I want to display a dialog using `showDialog(Context, Widget)`, but I noticed that in the implementation of `showDialog` there is a call to `MaterialLocalizations.of(context).modalBarrierDismissLabel` that is causing an exception (see below) and prevents the dialog from showing at all. By removing `Locale('nb', 'NO');` from the list of supported locales, the app behaves as expected (the dialog appears)

## Logs

I/flutter (22056): The getter 'modalBarrierDismissLabel' was called on null.
I/flutter (22056): Receiver: null
I/flutter (22056): Tried calling: modalBarrierDismissLabel

### PR DESCRIPTION
**Pull request by m9rc1n**
Partially resolves #15439

### CODE REVIEW

**Comment by HansMuller** [comment]
I've started the process for adding Norwegian (language codes 'nb' and 'nn') to Flutter's supported translations. It usually takes two weeks or so for the updates to roll in.

I'm hoping that you can get by with local changes (this PR) until then.

**Comment by maszin** [comment]
That's great. Thanks so much. I hope I will find some more areas to contribute.

**Comment by tvolkert** [comment]
@HansMuller can this be closed now that #15708 has landed?

**Comment by HansMuller** [comment]
Closing this PR; Norwegian support has landed in #15708

**Comment by HansMuller** [comment]
It looks like this PR used the wrong language code for Norwegian, 'no' instead of 'nb'. The problem was reported here:  https://github.com/flutter/flutter/issues/17770 and should be fixed by https://github.com/flutter/flutter/pull/17788

**Pull request closed without merging**
