### PR TITLE
Allow null fields in InputValue, to represent 'unchanged'.

### LINKED ISSUE #6018: Input should either assert or document that InputValue needs to be persistent.
It's currently not obvious that `InputValue`s need to be preserved in a state.

### PR DESCRIPTION
**Pull request by mpcomplete**
This allows users to pass in a `new InputValue(text: foo)` to an Input,
without clobbering the selected or composing ranges. This is a common
mistake.

Fixes https://github.com/flutter/flutter/issues/6018

### CODE REVIEW

**Comment by abarth** [comment]
IMHO, we should aim for a more wholistic solution.

**Comment by mpcomplete** [comment]
OK, I haven't given up on this yet. Here's attempt number 2: https://github.com/flutter/flutter/pull/6533

**Comment by Hixie** [comment]
@mpcomplete With #6533, is this PR obsolete?

**Comment by mpcomplete** [comment]
I think this is orthogonal to #6569 . Though I'm still not sure if this is the right approach. I have a feeling people will still be confused by the Input widget, e.g. https://github.com/flutter/flutter/issues/6589

**Comment by Hixie** [comment]
Ok. I think this is a reasonable thing to do in addition to #6569.

**Comment by mpcomplete** [comment]
Playing with this some more, I'm not so sure this PR is a good idea. With #6569, Input is stateless, and you use an InputFormField to preserve state. With this patch, Input is half stateful. It remembers some fields of InputValue, but you still need to handle onChanged to update the text, and you still need to rebuild the Input with every character the user types. That might even be more confusing. Input should be either fully stateful or fully stateless.

**Comment by Hixie** [comment]
Yeah, good point.

**Comment by johnmccutchan** [comment]
Is this PR still current?

**Comment by mpcomplete** [comment]
No, giving up on this patch.

**Pull request closed without merging**
