### PR TITLE
doc: Update Overlay example.

### PR DESCRIPTION
**Pull request by SzunTibor**
Changed the Builder + Switch statement combo to Switch expression for overlayEntry.

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by TahaTesser — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

However, I'm not sure this is a desireable change? Can you elaborate on why we would make this change?

**Comment by Producer86** [comment]
@Hixie  Example uses a Builder just to use a switch statement and make the code shorter. This sets a bad example.

**Comment by Hixie** [comment]
There's basically no difference between the old code and the new code in terms of which is good practice and which is better practice (a Builder is cheap, and the old code is clearer; the new code uses a lot more punctuation and is correspondingly harder to read, but skips one widget). I think if we wanted to show really good practice here we'd refactor the example so that only the inner bit (the bit that used to be a Builder) actually rebuilt when the state changed.

**Comment by Hixie** [comment]
Actually looking more closely, the current code (and proposed code in this PR) is just wrong. As far as I can tell the intent is for the overlay to be static with a particular page, but instead it is being built from a closure that captures the state of the widget around it. That means, for example, that if you rotate the screen after the state has changed you might see the widgets change when they should not.

**Comment by Producer86** [comment]
Huh, I always thought Builder is heavy, alas never benchmarked it. But that was the primary motivation. Highly agree with the refactor, but I understand we want to keep things as simple as can be in examples.
PR doesn't have a closure anymore, it's just an expression.

**Comment by Hixie** [comment]
The expression is in the closure starting line 44.

**Comment by Hixie** [comment]
I think it would be fine to refactor this to be more correct, we do want our examples to be correct. :-)
The fix would actually make the code simpler, just remove the local variable and the setStates and just pass the variable to the function that creates the overlay entries directly.

**Comment by goderbauer** [comment]
(triage) @Producer86 do you still have plans to follow up on the feedback given above?

**Pull request closed without merging**
