### PR TITLE
[R] Improve documentation regarding padding for dialogs.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
This should in theory have no semantic change, though the code is tweaked a bit to put the defaults in the constructors where possible and to use the cheaper `EdgeInsets` class where possible (rather than `EdgeInsetsDirectional`).

**Comment by Hixie** [comment]
cc @goderbauer

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Thanks, will land on green.

**Pull request merged**
