### PR TITLE
Revert "Add capability to flutter test --platform=chrome"

### PR DESCRIPTION
**Pull request by tvolkert**
This reverts https://github.com/flutter/flutter/pull/33525

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Why?

**Comment by jonahwilliams** [comment]
NVM, see comment now. Unfortunate, but I can reland using the chrome launcher logic I have pending

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by tvolkert** [comment]
I'm going to land this speculatively and watch the bots post-commit since our dev release is blocking Fuchsia work.

**Pull request merged**
