### PR TITLE
Revert "Revert "obscureText and enableInteractiveSelection defaults""

### PR DESCRIPTION
**Pull request by justinmc**
Reverts flutter/flutter#25335

Revert of a reverted PR. It was reverted due to a device lab test failure.  I've fixed the failure and am resubmitting.

### CODE REVIEW

**Comment by justinmc** [comment]
@HansMuller Check out the 4 lines I removed in main_test.dart to get the test to work.

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
I encourage you to read https://github.com/flutter/flutter/wiki/Tree-hygiene (notably, please see the section on revert commits -- for clarity, we'd like to avoid having more than one "revert" per commit message).

**Comment by justinmc** [comment]
Whoops missed that one, thanks for the reminder :blush:

**Pull request merged**
