### PR TITLE
Pin url_launcher to federated version in plugin_lint_mac

### LINKED ISSUE #98165: Mac plugin_lint_mac failing consistently on unrelated PR
On https://github.com/flutter/flutter/commit/0ce527eb91a37ef31b60ed6d4a9613310f2107d4, which doesn't look like it should have affected a plugin test. /cc @cyanglaz 

https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20plugin_lint_mac/5483/overview

```
[plugin_lint_mac] [STDOUT] stdout:         /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-macos10.11 -isysroot /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -L/Users/chrome-bot/Library/Developer/Xcode/DerivedData/App-fnuhlnrabrbryscrhrnessyodoze/Build/Products/Release -L/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -L/Users/chrome-bot/Library/Developer/Xcode/DerivedData/App-fnuhlnrabrbryscrhrnessyodoze/Build/Products/Release/test_plugin_swift -L/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/lib/swift -F/Users/chrome-bot/Library/Developer/Xcode/DerivedData/App-fnuhlnrabrbryscrhrnessyodoze/Build/Products/Release -F/opt/s/w/ir/x/t/CocoaPods-Lint-20220209-14900-7a9pgu-test_plugin_swift/Pods/FlutterMacOS -filelist /Users/chrome-bot/Library/Developer/Xcode/DerivedData/App-fnuhlnrabrbryscrhrnessyodoze/Build/Intermediates.noindex/App.build/Release/App.build/Objects-normal/arm64/App.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker /opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -object_path_lto -Xlinker /Users/chrome-bot/Library/Developer/Xcode/DerivedData/App-fnuhlnrabrbryscrhrnessyodoze/Build/Intermediates.noindex/App.build/Release/App.build/Objects-normal/arm64/App_lto.o -fobjc-link-runtime -L/opt/s/w/ir/cache/osx_sdk/XCode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/chrome-bot/Library/Developer/Xcode/DerivedData/App-fnuhlnrabrbryscrhrnessyodoze/Build/Intermediates.noindex/App.build/Release/App.build/Objects-normal/arm64/App.swiftmodule -ObjC -ltest_plugin_swift -framework FlutterMacOS -framework Cocoa -lPods-App -Xlinker -dependency_info -Xlinker /Users/chrome-bot/Library/Developer/Xcode/DerivedData/App-fnuhlnrabrbryscrhrnessyodoze/Build/Intermediates.noindex/App.build/Release/App.build/Objects-normal/arm64/App_dependency_info.dat -o /Users/chrome-bot/Library/Developer/Xcode/DerivedData/App-fnuhlnrabrbryscrhrnessyodoze/Build/Intermediates.noindex/App.build/Release/App.build/Objects-normal/arm64/Binary/App
[plugin_lint_mac] [STDOUT] stdout:     ld: warning: ignoring file /opt/s/w/ir/x/t/CocoaPods-Lint-20220209-14900-7a9pgu-test_plugin_swift/Pods/FlutterMacOS/FlutterMacOS.framework/FlutterMacOS, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
[plugin_lint_mac] [STDOUT] stdout:     Undefined symbols for architecture arm64:
[plugin_lint_mac] [STDOUT] stdout:       "_FlutterMethodNotImplemented", referenced from:
[plugin_lint_mac] [STDOUT] stdout:           test_plugin_swift.TestPluginSwiftPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in libtest_plugin_swift.a(TestPluginSwiftPlugin.o)
[plugin_lint_mac] [STDOUT] stdout:           function signature specialization <Arg[1] = Dead, Arg[2] = Owned To Guaranteed> of function signature specialization <Arg[1] = [Closure Propagated : reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned Swift.Optional<Swift.AnyObject>) -> () to @escaping @callee_guaranteed (@in_guaranteed Swift.Optional<Any>) -> (), Argument Types : [@escaping @callee_unowned @convention(block) (@unowned Swift.AnyObject?) -> ()]> of test_plugin_swift.TestPluginSwiftPlugin.handle(_: __C.FlutterMethodCall, result: (Any?) -> ()) -> () in libtest_plugin_swift.a(TestPluginSwiftPlugin.o)
[plugin_lint_mac] [STDOUT] stdout:       "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
[plugin_lint_mac] [STDOUT] stdout:           objc-class-ref in libtest_plugin_swift.a(TestPluginSwiftPlugin.o)
[plugin_lint_mac] [STDOUT] stdout:     ld: symbol(s) not found for architecture arm64
[plugin_lint_mac] [STDOUT] stdout:     clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

/cc @godofredoc @yusuf-goog @jmagman @stuartmorgan

### PR DESCRIPTION
**Pull request by jmagman**
Fixes https://github.com/flutter/flutter/issues/98165

Pins to `url_launcher` to first federated version https://github.com/flutter/plugins/pull/4536. See explanation at https://github.com/flutter/flutter/issues/98165#issuecomment-1034480221

Reverts https://github.com/flutter/flutter/pull/98166

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jmagman** [comment]
Tests are failing on infra issue https://github.com/flutter/flutter/issues/97303.

**Review by cyanglaz — APPROVED** [review]
LGTM if the infra issue is fixed and tests pass

**Comment by jmagman** [comment]
Rebased onto https://github.com/flutter/flutter/pull/98210.

**Comment by jmagman** [comment]
Test failed because it still ran on `Mac-10.15` even on https://github.com/flutter/flutter/pull/98210, and https://github.com/flutter/cocoon/pull/1597 probably hadn't rolled in cocoon.

**Comment by jmagman** [comment]
Ugh, led test still failed.  https://github.com/flutter/flutter/pull/98166 passed let's merge that one instead of this one to reopen the tree, I'll keep investigating this.

**Comment by stuartmorgan** [comment]
Except the new version of url_launcher was published about an hour ago :(

**Comment by keyonghan** [comment]
The `os` dimension is being retrieved on [platform property level](https://cs.opensource.google/flutter/infra/+/main:config/flutter_config.star;l=110 ), so unfortunately https://github.com/flutter/flutter/commit/c1c96ef677e1766803a78f6ebb070bd4269e4c4d did not promote the dimension.

So we need to wait for https://github.com/flutter/flutter/pull/98144 to land, so that the new os versions will be picked up.

**Comment by jmagman** [comment]
> The `os` dimension is being retrieved on [platform property level](https://cs.opensource.google/flutter/infra/+/main:config/flutter_config.star;l=110), so unfortunately [c1c96ef](https://github.com/flutter/flutter/commit/c1c96ef677e1766803a78f6ebb070bd4269e4c4d) did not promote the dimension.
> 
> So we need to wait for #98144 to land, so that the new os versions will be picked up.

It looks like it worked this time?
https://ci.chromium.org/p/flutter/builders/try/Mac%20plugin_lint_mac/11051?

```
os | "Mac-12"
...
xcode | "13a233"
```
It ran on a Mac-12.2 (build835-m9) machine.

**Comment by keyonghan** [comment]
> It looks like it worked this time? https://ci.chromium.org/p/flutter/builders/try/Mac%20plugin_lint_mac/11051?
> 
> ```
> os | "Mac-12"
> ...
> xcode | "13a233"
> ```
> 
> It ran on a Mac-12.2 (build835-m9) machine.

Ah, right. The pre-submit should be okay as scheduling is triggered via cocoon which started supporting dimension injection yesterday. The post-submit needs to wait for that PR to land as it [doesn't support target level override](https://flutter.googlesource.com/infra/+/refs/heads/main/config/lib/ci_yaml/ci_yaml.star#315).

Created https://github.com/flutter/flutter/issues/98274 to track.

**Pull request merged**
