### PR TITLE
Retry remove package:test from flutter

### PR DESCRIPTION
**Pull request by jonahwilliams**
Retry of https://github.com/flutter/flutter/pull/23755, adds back test dep to driver scripts until we add support for https://github.com/flutter/flutter/issues/24005

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Adds back test dep to our driver scripts so that the devicelab can run

**Review by tvolkert — APPROVED** [review]

**Comment by byteasc** [comment]
This appears to have removed a large chunk of dart imports from various flutter pubspec.yaml files. Is the intended process that we'll have to add what we want to import per project

**Comment by jonahwilliams** [comment]
@byteasc yes that is correct. The alternative is, everyone has to be on exactly the correct version of these packages to use Flutter. For very common dependencies such as analyzer and http, this caused problems for users at every upgrade.

**Comment by byteasc** [comment]
@jonahwilliams Simple enough and understandable! Just wanted to clarify

**Comment by jonahwilliams** [comment]
No problem! If you have any follow up questions or comments, feel free to respond to the thread on [flutter-dev](https://groups.google.com/forum/#!topic/flutter-dev/EppJpBk9eqQ) and I'll happily follow up.

**Pull request merged**
