### PR TITLE
Handle compilation failures from web application

### LINKED ISSUE #38642: Flutter for Web crash after framework exception
## Steps to Reproduce

0. Setup flutter for web on Channel master, v1.8.5-pre.156, on Mac OS X 10.14.6 18G84, locale en-US
1. Cause a red-screen-of-death by navigating to a widget with an empty build method
2. add a build method
3. Type "R" in console to hot-restart
4. observe Chrome crashes and Flutter sends a bug report

## Logs

```
════════════════════════════════════════════════════════════════════════════════════════════════════

Dependencies graph change for module 'packages/fede/src/pages/detail' detected. Dependencies was
[dart_sdk,packages/flutter/src/widgets/actions,packages/webfeed/domain/atom_item,packages/flutter/material,packages/http/htt
p,packages/webfeed/domain/atom_feed], now
[dart_sdk,packages/flutter/material,packages/flutter/src/widgets/actions,packages/flutter/src/rendering/animated_size,packag
es/webfeed/domain/atom_person,packages/webfeed/domain/atom_category,packages/webfeed/domain/atom_item,packages/http/http,pac
kages/webfeed/domain/atom_feed]. Page can't be hot-reloaded, firing full page reload.
Unexpected Server Error WipError 46: {code: -32000, message: Execution context was destroyed.}
#0      DwdsVmClient.create.<anonymous closure> (package:dwds/src/dwds_vm_client.dart:43:22)
<asynchronous suspension>
#1      VmService._routeRequest (package:vm_service/vm_service.dart:1730:39)
<asynchronous suspension>
#2      VmService._processRequest (package:vm_service/vm_service.dart:1707:25)
<asynchronous suspension>
#3      VmService._processMessageStr (package:vm_service/vm_service.dart:1675:9)
#4      VmService._processMessage (package:vm_service/vm_service.dart:1632:7)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#11     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#12     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#17     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#18     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#19     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#20     _rootRun (dart:async/zone.dart:1120:38)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
 (-32000) from hotRestart()
#0      ResidentWebRunner.restart (package:flutter_tools/src/build_runner/resident_web_runner.dart:238:49)
<asynchronous suspension>
#1      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1065:61)
<asynchronous suspension>
#2      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1117:13)
<asynchronous suspension>
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:375:20)
#9      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#10     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#16     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#17     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#18     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#19     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#20     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#21     _ErrorHandlingAsciiDecoderSink.addSlice (dart:convert/ascii.dart:252:17)
#22     _ErrorHandlingAsciiDecoderSink.add (dart:convert/ascii.dart:238:5)
#23     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#24     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#30     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#31     _StreamController._add (dart:async/stream_controller.dart:640:7)
#32     _StreamController.add (dart:async/stream_controller.dart:586:5)
#33     _Socket._onData (dart:io-patch/socket_patch.dart:1791:41)
#34     _rootRunUnary (dart:async/zone.dart:1136:13)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#39     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#40     _StreamController._add (dart:async/stream_controller.dart:640:7)
#41     _StreamController.add (dart:async/stream_controller.dart:586:5)
#42     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1339:33)
#43     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:860:14)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#46     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


Performing hot restart...                                               
(This is taking an unexpectedly long time.)       ⣷
Sending crash report to Google.                                 
Crash report sent (report ID: 107d909073f4dc23)                                                                    
Performing hot restart...                                       (This is taking an unexpectedly long time.)       ⣻Oops; flutter has exited unexpectedly.
(This is taking an unexpectedly long time.)        
Crash report written to /Users/ryjohn/code/github/johnpryan/fede/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

```
flutter analyze
Analyzing fede...                                                       

   info • 'child' is deprecated and shouldn't be used • lib/src/pages/feed.dart:22:11 • deprecated_member_use

1 issue found. (ran in 1.7s)

```

```bash
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.8.5-pre.156, on Mac OS X 10.14.6 18G84, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] VS Code (version 1.35.1)
[✓] Connected device (2 available)

• No issues found!

```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

The VMService may throw an RPCError if it is unable to reload. Catch this and instead do a hard page refresh. Additionally, reduce the verbosity of compilation errors by hiding verbose build_daemon logs.

Still does not fix build errors not showing up in the terminal.

Fixes https://github.com/flutter/flutter/issues/38642

### CODE REVIEW

**Comment by yjbanov** [comment]
There seems to be something wrong in the commits, as if a rebase went awry. For example, you have @tvolkert's commit listed, which is already submitted.

**Comment by jonahwilliams** [comment]
Hmmm

**Comment by jonahwilliams** [comment]
Doesn't include that code though...  🤷‍♂

**Review by yjbanov — APPROVED** [review]

**Comment by jonahwilliams** [comment]
I'm ignore the add2app failures because they are unrelated.

**Pull request merged**
