### PR TITLE
Add ThemeData.shadowColor

### PR DESCRIPTION
**Pull request by lucasreiners**
## Description

This pull request adds shadowColor to the ThemeData to be able to override the default color of the elevation shadows. The property is used by the Material widget as a fallback, when no shadowColor is supplied to the Material widget. When the user did not override the shadowColor in the Theme, it defaults to black. This way we preserve the backward compatibility all the way to the Material widget.

The priority is the following, going to the next, when null:
1. shadowColor property of Material Widget
2. shadowColor property of ThemeData
3. black (for backward compatibility)

## Related Issues

#27461

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jamesblasco** [comment]
Well done!!! It would be very useful

**Comment by athornz** [comment]
Would be great to see this merged. Any change of fixing those tests?

**Comment by gspencergoog** [comment]
@LucasR93, are you still interested in pursuing this PR?  If so, you would need to resolve the test failures, and the conflicting files.

Also, you will need to add a test for your change that fails without your change, and succeeds with it.

**Comment by Hixie** [comment]
I suspect that @HansMuller may want the shadow color to go into the ColorScheme rather than the ThemeData?

**Comment by v7lin** [comment]
Any news update?

**Comment by HansMuller** [comment]
The [material color scheme](https://material.io/design/color/the-color-system.html#color-theme-creation) doesn't dictate the appearance of shadows. The approach taken here, adding a property to ThemeData, seems reasonable.

@LucasR93 - are you interested in returning to this PR?

**Comment by frmatthew** [comment]
@LucasR93 Do you have any intention to revise this PR and get it merged?

**Comment by goderbauer** [comment]
I am going to close this PR since there hasn't been any activity since the beginning of the year. Feel free to re-open if you find the time to work on this in the future.

**Pull request closed without merging**
