### PR TITLE
Update Android plugin templates to new Gradle constructs

### LINKED ISSUE #142685: Gradle Plugin DSL for Android plugins
### Use case

Flutter 3.16 introduced a new way to apply Gradle plugins using new Plugin DSL (as described [here](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply)). New apps generated using `flutter create` use this approach.

I expected this change to affect Android plugins created using `flutter create --template=plugin --platforms=android`, but it seems like it's not the case. I am missing explanation as to why. Is it intentional or just an oversight?

Tested on latest master.

### Proposal

Either include a description as to why Plugin DSL is not (yet?) available for plugins or add implementation to `flutter create --template=plugin --platforms=android` and a migration guide.

### PR DESCRIPTION
**Pull request by bartekpacia**
This PR resolves #142685

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by bartekpacia** [comment]
Plugins that use declarative `plugins {}` block are not able to specify the plugins version they wish to use if the app project already uses them.

This:

```gradle
plugins {
    id("com.android.library") version "8.2.2"
    id("kotlin-android") version "1.9.22"
}
```

results in:

<details><summary>Crash logs</summary>

```
$ flutter build apk --debug                                                                                                             exit 1


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/bartek/projects/example2/android/build.gradle' line: 2

* What went wrong:
Error resolving plugin [id: 'com.android.library', version: '7.3.0']
> The request for this plugin could not be satisfied because the plugin is already on the classpath with an unknown version, so compatibility cannot be checked.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 447ms
Running Gradle task 'assembleDebug'...                             922ms
Gradle task assembleDebug failed with exit code 1
```

</details>

**Comment by yaakovschectman** [comment]
Can we test this? Do the existing tests ensure these template files build?

**Comment by johnmccutchan** [comment]
What is the status of this PR? Should it be closed?

**Comment by bartekpacia** [comment]
I just finished the semester; will try to get back to this soon

**Comment by reidbaker** [comment]
bartekpacia wants to share why he doesn’t think this change makes sense and is possible.
https://discord.com/channels/608014603317936148/846507907876257822/1278496175728889926

**Comment by bartekpacia** [comment]
Yeah.

I don't believe the Gradle's new (recommended by them) `plugins {}` block works with how Flutter's plugin ecosystem works on Android.

The problem is this: individual Flutter plugins often specify varios versions of buildscript classpath dependencies, e.g. different Kotlin versions in the `buildscript {}` block. This means that different versions of e.g. Kotlin are simultaneusly present in the Gradle buildscript classpath, but only for a specific Flutter Android plugin project.

However, as far as I understand, Gradle forbids using different versions of the same Gradle plugin in the `plugins {}` block.

So let's consider an Android Flutter app with 2 Android Flutter plugins:
- `app` -> `plugins { id("kotlin-android") version 2.0.0 }`
- `plugin_tangos` -> `plugins { id("kotlin-android") version 1.9.24 }`
- `plugin_zulu` -> `plugins { id("kotlin-android") version 1.8.22 }`

This will not work, and Gradle will be angry that "the plugin is already on the classpath". Basically, [this StackOverflow problem](https://stackoverflow.com/questions/60070739/plugin-request-for-plugin-already-on-the-classpath-must-not-include-a-version).

I hope I am wrong, or that there is a way around this. But as of now I don't see a way forward.

**Comment by bartekpacia** [comment]
This is somewhat related: https://discuss.gradle.org/t/why-duplicate-plugins-in-top-level-build-scripts/49087

**Comment by emakar** [comment]
what if plugins just specify `id("kotlin-android")`, making it effectively a requirement for apps to specify `kotlin-android` version in `settings.gradle(.kts)` or root `bulid.gradle(.kts)`?

at least as a migration path

**Comment by bartekpacia** [comment]
@emakar – that'd be _a solution_, but then we'd hit another problem – the plugin author wouldn't have control over what Kotlin version their plugin uses. So let's say that an app specifies the latest Kotlin version, which had some breaking change, but plugin author didn't update their plugin in a while and the plugin isn't compatible with that latest Kotlin version. The result would be a compilation (or perhaps a runtime?) failure.

But I'm very curious to hear all the other ideas. Maybe there's a way we could make it work.

**Pull request closed without merging**
