### PR TITLE
Make the template plugin example depend on the plugin as a real dependency

### PR DESCRIPTION
**Pull request by amirh**
## Description

The template for the example plugin app was adding the path dependency to the parent plugin as a dev_dependency.
When the plugin template was introduced in https://github.com/flutter/flutter/pull/9076 this was the case depending whether the example app was created with a driver test, https://github.com/flutter/flutter/pull/11304 made this the case unconditionally.

The example app builds with the plugin as either a real dependency or dev_dependency as the semantic difference between the two only applies to transitive dependencies ([Pub Dev Dependencies](https://dart.dev/tools/pub/dependencies#dev-dependencies)). Though it still violates the convention where stuff that's imported from `lib/` is a real dependency.

## Tests

- Verify that the pubspec for the example app that's generated as part of the plugin template has a real dependency on the parent plugin.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jmagman** [comment]
Is there an issue tracking first-party plugin example projects getting this change?  Would be nice to prove everything is working there as well.

**Comment by amirh** [comment]
@jmagman most first party plugins are including the example app as a real dependency already, e.g: https://github.com/flutter/plugins/blob/9859a383c7d15966eb9165f2616afeb4ee53129a/packages/image_picker/example/pubspec.yaml#L9

**Comment by amirh** [comment]
cc @Hixie to evaluate test exemption

**Review by harryterkelsen — APPROVED** [review]
LGTM

**Pull request merged**
