### PR TITLE
[flutter_releases] Flutter 1.22.1 Framework Cherrypicks

### PR DESCRIPTION
**Pull request by christopherfujino**
## Scheduled Cherrypicks
* [x] Engine cherrypicks
  * https://github.com/flutter/engine/commit/75bef9f6c8ac2ed4e1e04cdfcd88b177d9f1850d
* [x] [Docs] [Icons] Icons API page doesn't respect new icons #66407
  * https://github.com/flutter/flutter/issues/66407
  * ee6d4c65902b81855f71ea3053fafa60ae944bbb 
  * Author @willlarche, approvers @HansMuller, @rami-a, @JoseAlba 
* [x] Restore the autovalidate property and deprecate it #66940
  * https://github.com/flutter/flutter/issues/66940
  * 10f6284426bc653da3640088c0a769fab7986cc9 
  * Author @pedromassango, approver @justinmc 
* [x] Using --analyze-size with --split-debug-info crashes the snapshot analysis package #66962
  * https://github.com/flutter/flutter/issues/66962
  * fe22d196fc004d01d5e8ae618ac34744ad03a6ac
  * Author @jonahwilliams, approver @zanderso

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Missing #66962

**Comment by christopherfujino** [comment]
> Missing #66962

Yeah, I shouldn't have added reviewers yet, this is still WIP

**Comment by christopherfujino** [comment]
I manually updated the cla-bot label because the contributor in question has already signed the CLA.

**Review by willlarche — APPROVED** [review]

**Review by pcsosinski — APPROVED** [review]
approved for branch

**Review by jonahwilliams — APPROVED** [review]
LGTM for tools change

**Pull request merged**
