### PR TITLE
Load assets during test from file system instead of manifest.

### PR DESCRIPTION
**Pull request by chingjun**
This is done to match the app's behavior of not expecting all assets to have an entry in AssetManifest.json.

The assumption is not true for internal customers, and issue #36552 is blocking us from fixing AssetManifest.json internally.

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
LGTM, it is not ideal that we can't have test for the use case of internal test, and i can't think of a way to test the internal behavior unless we duplicated the internal assets build in the test. I guess we have to live with it.

**Comment by chingjun** [comment]
Thanks for the review. I was thinking about the tests too when I was submitting this PR.

I'll add tests internally for this, and hopefully after the AssetManifest loading issue is resolved we don't need to depend on this to accommodate the differences between the two versions.

**Comment by chunhtai** [comment]
> Thanks for the review. I was thinking about the tests too when I was submitting this PR.
> 
> I'll add tests internally for this, and hopefully after the AssetManifest loading issue is resolved we don't need to depend on this to accommodate the differences between the two versions.

If you plan to change it back, please add a todo in the code

**Comment by chingjun** [comment]
Oh I meant by the time there will be no difference between internal and external versions and the difference does not matter anymore.

I don't think we have to change it back if the functionality it provides is equivalent.

**Pull request merged**
