### PR TITLE
Minor code cleanup: remove redundant return

### PR DESCRIPTION
**Pull request by fzyzcjy**
Find this when reading source code. Maybe next time it can be caught by a linter :)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
test-exemption: code refactor with no semantic change

That said, it would be great to file an issue on the linter to ask for a lint to catch this kind of thing.

**Review by Hixie — APPROVED** [review]
LGTM

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by fzyzcjy** [comment]
> That said, it would be great to file an issue on the linter to ask for a lint to catch this kind of thing.

Totally agree, here it is: https://github.com/dart-lang/linter/issues/3804

**Comment by jiahaog** [comment]
> auto label is removed for flutter/flutter, pr: 114290, due to - The status or check suite [Google testing](http://flutter-rob/#/flutter/premerge_prs?pr=114290) has failed. Please fix the issues identified (or deflake) before re-applying this label.

This seems to be some sort of infrastructure issue. I've overridden the "Google testing" status check and this PR should be ok to land. Googlers, please see b/256753114 for more details.

**Pull request merged**
