### PR TITLE
Auto-format Framework

### PR DESCRIPTION
**Pull request by goderbauer**
This auto-formats all *.dart files in the repository outside of the `engine` subdirectory and enforces that these files stay formatted with a presubmit check.

**Reviewers:** Please carefully review all the commits except for the one titled "formatted". The "formatted" commit was auto-generated by running `dev/tools/format.sh -a -f`. The other commits were hand-crafted to prepare the repo for the formatting change. I recommend reviewing the commits one-by-one via the "Commits" tab and avoiding Github's "Files changed" tab as it will likely slow down your browser because of the size of this PR.

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by goderbauer** [comment]
Superseded by https://github.com/flutter/flutter/pull/160545.

**Comment by liheng168** [comment]
packages/flutter/lib/src/widgets/icon_data.dart

**Comment by liheng168** [comment]
packages/flutter/lib/src/widgets/icon_data.dart

**Pull request closed without merging**
