### PR TITLE
Move FlutterLogo from material to widget

### LINKED ISSUE #154448: Move FlutterLogo out of the Material library
### Use case

FlutterLogo is in the Material library, but has no Material dependencies/opinions. So it makes sense to move it out of the Material library.

Also, [CupertinoContextMenu's examples](https://api.flutter.dev/flutter/cupertino/CupertinoContextMenu-class.html?_gl=1*11gn7bu*_ga*ODkwNDg2NzQxLjE3MTM5OTkwNDQ.*_ga_04YGWK0175*MTcyNTA0NTMzOS4xMzkuMS4xNzI1MDUwMTA3LjAuMC4w) imports the Material library because of FlutterLogo. This move can help remove that import.

### Proposal

Move FlutterLogo out of the Material library.

### PR DESCRIPTION
**Pull request by g0rdan**
The PR is moving FlutterLogo from `lib/src/material` to `lib/src/widgets` because it has no dependency on Material.

Fixes https://github.com/flutter/flutter/issues/154448

PS: There is [older PR](https://github.com/flutter/flutter/pull/154711) for this issue and I don't know the policy on conflicting PRs. Let me know if I need to drop mine.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by victorsanni — APPROVED** [review]
LGTM! Thanks for the contribution.

**Review by nate-thegrate — APPROVED** [review]
LGTM!

**Comment by nate-thegrate** [comment]
@victorsanni apparently non-Googlers can't triage the [flutter-gold changes](https://flutter-gold.skia.org/cl/github/155864).

**Comment by g0rdan** [comment]
@nate-thegrate Maybe I can as a creator of PR...? I'm just hesitant...

@victorsanni @nate-thegrate Quick question, the goldens triage happens because it is a new directory for the widget/tests, right? I can safely mark them as positive (if I technically can, of course)?

**Comment by nate-thegrate** [comment]
> the goldens triage happens because it is a new directory for the widget/tests, right? I can safely mark them as positive (if I technically can, of course)?

Correct! Feel free to go ahead and try :)

**Comment by g0rdan** [comment]
> Correct! Feel free to go ahead and try :)

Nope, I cannot. 401.

**Pull request merged**
