### PR TITLE
Set modal bottom sheet barrier color

### PR DESCRIPTION
**Pull request by katallaxie**
## Description

When presenting a Modal Bottom Sheet this PR allows to pass down a value for the color of the modal barrier. This is a non-breaking change, because the default behavior is being kept.

## Tests

I added the following tests:

* A test which confirms that the presented modal barrier color reflects the passed in value for the color.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by katallaxie** [comment]
@darrenaustin any thoughts here. Has been laying around for a bit.

**Review by darrenaustin — APPROVED** [review]
Thanks for your contribution. This is a reasonable feature with a good implementation and test. LGTM.

**Comment by darrenaustin** [comment]
> @darrenaustin any thoughts here. Has been laying around for a bit.

Sorry about that. Looks good. I will push this when the build goes green. Thanks for submitting this.

**Comment by droidery** [comment]
@katallaxie Shouldn't this also be exposed in the `BottomSheetThemeData`. This would allow the same modal sheet barrier color to be used across the entire app.

It would also be more consistent with the other properties available in the `BottomSheetThemeData` like `backgroundColor` and `shape`.

**Comment by katallaxie** [comment]
@droidery I thought of this. But because there is default behavior that actually reflects the standard design guidelines I thought it would be better to have this more as a special customization.

**Pull request merged**
