### PR TITLE
Roll Engine from 5140e30cec13 to 8f272d98c92f (57 revisions)

### PR DESCRIPTION
**Pull request by engine-flutter-autoroll**
Roll Engine from 5140e30cec13 to 8f272d98c92f (57 revisions)

https://github.com/flutter/engine/compare/5140e30cec13...8f272d98c92f

2021-11-07 skia-flutter-autoroll@skia.org Roll Fuchsia Linux SDK from aD3d4Kqmy... to ZniYyCw7U... (flutter/engine#29579)
2021-11-07 skia-flutter-autoroll@skia.org Roll Fuchsia Mac SDK from rIpW1050J... to TOmxgL3av... (flutter/engine#29578)
2021-11-07 skia-flutter-autoroll@skia.org Roll Skia from 2417872a9993 to cd7220e7686c (2 revisions) (flutter/engine#29577)
2021-11-07 zanderso@users.noreply.github.com Revert dart to 38e7078fa2b7 (flutter/engine#29575)
2021-11-07 zanderso@users.noreply.github.com Revert "Reland Display Features support (Foldable and Cutout) (#29447)" (flutter/engine#29574)
2021-11-06 skia-flutter-autoroll@skia.org Roll Fuchsia Mac SDK from W9UXc2Fwx... to rIpW1050J... (flutter/engine#29573)
2021-11-06 skia-flutter-autoroll@skia.org Roll Fuchsia Linux SDK from uP2kJIngK... to aD3d4Kqmy... (flutter/engine#29572)
2021-11-06 dnfield@google.com Hide a11y elements when resigning active (flutter/engine#29566)
2021-11-06 skia-flutter-autoroll@skia.org Roll Dart SDK from 5ccf755b37a4 to f6a43e5eb71d (1 revision) (flutter/engine#29571)
2021-11-06 skia-flutter-autoroll@skia.org Roll Fuchsia Mac SDK from 6BYh8qaYo... to W9UXc2Fwx... (flutter/engine#29570)
2021-11-06 skia-flutter-autoroll@skia.org Roll Fuchsia Linux SDK from kHXT3xnTG... to uP2kJIngK... (flutter/engine#29569)
2021-11-06 skia-flutter-autoroll@skia.org Roll Dart SDK from 996ef242a2c9 to 5ccf755b37a4 (1 revision) (flutter/engine#29568)
2021-11-06 skia-flutter-autoroll@skia.org Roll Skia from 37bef2d300e4 to 2417872a9993 (1 revision) (flutter/engine#29567)
2021-11-06 dworsham@google.com fuchsia: Enable integration tests (flutter/engine#29565)
2021-11-05 skia-flutter-autoroll@skia.org Roll Dart SDK from d464cd3f2dc8 to 996ef242a2c9 (1 revision) (flutter/engine#29564)
2021-11-05 egarciad@google.com Fix race condition introduced by background platform channels (flutter/engine#29377)
2021-11-05 skia-flutter-autoroll@skia.org Roll Skia from deb9386be146 to 37bef2d300e4 (6 revisions) (flutter/engine#29563)
2021-11-05 ychris@google.com ios test script checks for `ios_test_flutter` artifacts (flutter/engine#29554)
2021-11-05 dnfield@google.com Trace calls to Canvas::saveLayer (flutter/engine#29444)
2021-11-05 skia-flutter-autoroll@skia.org Roll Dart SDK from 38e7078fa2b7 to d464cd3f2dc8 (5 revisions) (flutter/engine#29561)
2021-11-05 dkwingsmt@users.noreply.github.com [Linux keyboard] Fix logical keys of up events are not regularized (flutter/engine#29550)
2021-11-05 skia-flutter-autoroll@skia.org Roll Skia from 725705f6630b to deb9386be146 (3 revisions) (flutter/engine#29559)
2021-11-05 skia-flutter-autoroll@skia.org Roll Fuchsia Mac SDK from emi7COLIo... to 6BYh8qaYo... (flutter/engine#29558)
2021-11-05 skia-flutter-autoroll@skia.org Roll Fuchsia Linux SDK from Ci-Vji1rx... to kHXT3xnTG... (flutter/engine#29557)
2021-11-05 skia-flutter-autoroll@skia.org Roll Dart SDK from 05febe0a7860 to 38e7078fa2b7 (5 revisions) (flutter/engine#29556)
2021-11-05 skia-flutter-autoroll@skia.org Roll Skia from 1800d410df16 to 725705f6630b (1 revision) (flutter/engine#29555)
2021-11-05 skia-flutter-autoroll@skia.org Roll Skia from 4322c7fec7e4 to 1800d410df16 (1 revision) (flutter/engine#29553)
2021-11-05 skia-flutter-autoroll@skia.org Roll Dart SDK from f38618d5d0c0 to 05febe0a7860 (5 revisions) (flutter/engine#29539)
2021-11-05 hanneswinkler2000@web.de don't build flutter SDK artifacts for armv7 (flutter/engine#28016)
2021-11-05 skia-flutter-autoroll@skia.org Roll Skia from 17616469ddf8 to 4322c7fec7e4 (3 revisions) (flutter/engine#29552)
2021-11-05 skia-flutter-autoroll@skia.org Roll Skia from ae67f07a58a2 to 17616469ddf8 (1 revision) (flutter/engine#29551)
2021-11-05 skia-flutter-autoroll@skia.org Roll Skia from cf8daf79e710 to ae67f07a58a2 (1 revision) (flutter/engine#29549)
2021-11-05 zhongwuzw@qq.com [iOS] Fixes press key message leaks (flutter/engine#29354)
2021-11-05 skia-flutter-autoroll@skia.org Roll Skia from 37da672b14b7 to cf8daf79e710 (9 revisions) (flutter/engine#29548)
2021-11-05 skia-flutter-autoroll@skia.org Roll Fuchsia Mac SDK from nkHhPcy3q... to emi7COLIo... (flutter/engine#29547)
2021-11-05 skia-flutter-autoroll@skia.org Roll Fuchsia Linux SDK from m90mMA37b... to Ci-Vji1rx... (flutter/engine#29546)
2021-11-05 chriscraws@gmail.com FragmentProgram constructed asynchronously (flutter/engine#29513)
2021-11-04 skia-flutter-autoroll@skia.org Roll Dart SDK from 3b11f88c96a5 to f38618d5d0c0 (7 revisions) (flutter/engine#29537)
2021-11-04 skia-flutter-autoroll@skia.org Roll Clang Linux from 5N9a1nYj5... to UtjvZhwws... (flutter/engine#29535)
2021-11-04 flar@google.com use SkMatrix.invert() instead of MatrixDecomposition to validate cache matrices (flutter/engine#29530)
2021-11-04 skia-flutter-autoroll@skia.org Roll Skia from a05d3029ac65 to 37da672b14b7 (1 revision) (flutter/engine#29534)
2021-11-04 dnfield@google.com Re-enable A11yTreeIsConsistent with higher timeout (flutter/engine#29367)
2021-11-04 iska.kaushik@gmail.com [raster_cache] Increment access_count on Touch (flutter/engine#29529)
2021-11-04 gw280@google.com Remove D3D9 fallback path (flutter/engine#29533)
2021-11-04 akbiggs@users.noreply.github.com [fuchsia] Add more logging for error cases. (flutter/engine#29397)
2021-11-04 andreidiaconu@users.noreply.github.com Reland Display Features support (Foldable and Cutout) (flutter/engine#29447)
...

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 57.
View them at https://flutter-gold.skia.org/cl/github/93216

**Comment by zanderso** [comment]
Is https://github.com/flutter/engine/pull/29448 causing the skia diffs? @dkwingsmt @dnfield

**Comment by dkwingsmt** [comment]
Likely. I'll revert it.

**Comment by dkwingsmt** [comment]
https://github.com/flutter/engine/pull/29580 @zanderso

**Comment by innos123** [comment]
> Roll Engine from 5140e30cec13 to 8f272d98c92f (57 revisions)
> 
> [flutter/engine@5140e30...8f272d9](https://github.com/flutter/engine/compare/5140e30cec13...8f272d98c92f)
> 
> 2021-11-07 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Fuchsia Linux SDK from aD3d4Kqmy... to ZniYyCw7U... ([flutter/engine#29579](https://github.com/flutter/engine/pull/29579)) 2021-11-07 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Fuchsia Mac SDK from rIpW1050J... to TOmxgL3av... ([flutter/engine#29578](https://github.com/flutter/engine/pull/29578)) 2021-11-07 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Skia from 2417872a9993 to cd7220e7686c (2 revisions) ([flutter/engine#29577](https://github.com/flutter/engine/pull/29577)) 2021-11-07 [zanderso@users.noreply.github.com](mailto:zanderso@users.noreply.github.com) Revert dart to 38e7078fa2b7 ([flutter/engine#29575](https://github.com/flutter/engine/pull/29575)) 2021-11-07 [zanderso@users.noreply.github.com](mailto:zanderso@users.noreply.github.com) Revert "Reland Display Features support (Foldable and Cutout) (#29447)" ([flutter/engine#29574](https://github.com/flutter/engine/pull/29574)) 2021-11-06 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Fuchsia Mac SDK from W9UXc2Fwx... to rIpW1050J... ([flutter/engine#29573](https://github.com/flutter/engine/pull/29573)) 2021-11-06 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Fuchsia Linux SDK from uP2kJIngK... to aD3d4Kqmy... ([flutter/engine#29572](https://github.com/flutter/engine/pull/29572)) 2021-11-06 [dnfield@google.com](mailto:dnfield@google.com) Hide a11y elements when resigning active ([flutter/engine#29566](https://github.com/flutter/engine/pull/29566)) 2021-11-06 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Dart SDK from 5ccf755b37a4 to f6a43e5eb71d (1 revision) ([flutter/engine#29571](https://github.com/flutter/engine/pull/29571)) 2021-11-06 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Fuchsia Mac SDK from 6BYh8qaYo... to W9UXc2Fwx... ([flutter/engine#29570](https://github.com/flutter/engine/pull/29570)) 2021-11-06 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Fuchsia Linux SDK from kHXT3xnTG... to uP2kJIngK... ([flutter/engine#29569](https://github.com/flutter/engine/pull/29569)) 2021-11-06 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Dart SDK from 996ef242a2c9 to 5ccf755b37a4 (1 revision) ([flutter/engine#29568](https://github.com/flutter/engine/pull/29568)) 2021-11-06 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Skia from 37bef2d300e4 to 2417872a9993 (1 revision) ([flutter/engine#29567](https://github.com/flutter/engine/pull/29567)) 2021-11-06 [dworsham@google.com](mailto:dworsham@google.com) fuchsia: Enable integration tests ([flutter/engine#29565](https://github.com/flutter/engine/pull/29565)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Dart SDK from d464cd3f2dc8 to 996ef242a2c9 (1 revision) ([flutter/engine#29564](https://github.com/flutter/engine/pull/29564)) 2021-11-05 [egarciad@google.com](mailto:egarciad@google.com) Fix race condition introduced by background platform channels ([flutter/engine#29377](https://github.com/flutter/engine/pull/29377)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Skia from deb9386be146 to 37bef2d300e4 (6 revisions) ([flutter/engine#29563](https://github.com/flutter/engine/pull/29563)) 2021-11-05 [ychris@google.com](mailto:ychris@google.com) ios test script checks for `ios_test_flutter` artifacts ([flutter/engine#29554](https://github.com/flutter/engine/pull/29554)) 2021-11-05 [dnfield@google.com](mailto:dnfield@google.com) Trace calls to Canvas::saveLayer ([flutter/engine#29444](https://github.com/flutter/engine/pull/29444)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Dart SDK from 38e7078fa2b7 to d464cd3f2dc8 (5 revisions) ([flutter/engine#29561](https://github.com/flutter/engine/pull/29561)) 2021-11-05 [dkwingsmt@users.noreply.github.com](mailto:dkwingsmt@users.noreply.github.com) [Linux keyboard] Fix logical keys of up events are not regularized ([flutter/engine#29550](https://github.com/flutter/engine/pull/29550)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Skia from 725705f6630b to deb9386be146 (3 revisions) ([flutter/engine#29559](https://github.com/flutter/engine/pull/29559)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Fuchsia Mac SDK from emi7COLIo... to 6BYh8qaYo... ([flutter/engine#29558](https://github.com/flutter/engine/pull/29558)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Fuchsia Linux SDK from Ci-Vji1rx... to kHXT3xnTG... ([flutter/engine#29557](https://github.com/flutter/engine/pull/29557)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Dart SDK from 05febe0a7860 to 38e7078fa2b7 (5 revisions) ([flutter/engine#29556](https://github.com/flutter/engine/pull/29556)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Skia from 1800d410df16 to 725705f6630b (1 revision) ([flutter/engine#29555](https://github.com/flutter/engine/pull/29555)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Skia from 4322c7fec7e4 to 1800d410df16 (1 revision) ([flutter/engine#29553](https://github.com/flutter/engine/pull/29553)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Dart SDK from f38618d5d0c0 to 05febe0a7860 (5 revisions) ([flutter/engine#29539](https://github.com/flutter/engine/pull/29539)) 2021-11-05 [hanneswinkler2000@web.de](mailto:hanneswinkler2000@web.de) don't build flutter SDK artifacts for armv7 ([flutter/engine#28016](https://github.com/flutter/engine/pull/28016)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Skia from 17616469ddf8 to 4322c7fec7e4 (3 revisions) ([flutter/engine#29552](https://github.com/flutter/engine/pull/29552)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Skia from ae67f07a58a2 to 17616469ddf8 (1 revision) ([flutter/engine#29551](https://github.com/flutter/engine/pull/29551)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Skia from cf8daf79e710 to ae67f07a58a2 (1 revision) ([flutter/engine#29549](https://github.com/flutter/engine/pull/29549)) 2021-11-05 [zhongwuzw@qq.com](mailto:zhongwuzw@qq.com) [iOS] Fixes press key message leaks ([flutter/engine#29354](https://github.com/flutter/engine/pull/29354)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Skia from 37da672b14b7 to cf8daf79e710 (9 revisions) ([flutter/engine#29548](https://github.com/flutter/engine/pull/29548)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Fuchsia Mac SDK from nkHhPcy3q... to emi7COLIo... ([flutter/engine#29547](https://github.com/flutter/engine/pull/29547)) 2021-11-05 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Fuchsia Linux SDK from m90mMA37b... to Ci-Vji1rx... ([flutter/engine#29546](https://github.com/flutter/engine/pull/29546)) 2021-11-05 [chriscraws@gmail.com](mailto:chriscraws@gmail.com) FragmentProgram constructed asynchronously ([flutter/engine#29513](https://github.com/flutter/engine/pull/29513)) 2021-11-04 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Dart SDK from 3b11f88c96a5 to f38618d5d0c0 (7 revisions) ([flutter/engine#29537](https://github.com/flutter/engine/pull/29537)) 2021-11-04 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Clang Linux from 5N9a1nYj5... to UtjvZhwws... ([flutter/engine#29535](https://github.com/flutter/engine/pull/29535)) 2021-11-04 [flar@google.com](mailto:flar@google.com) use SkMatrix.invert() instead of MatrixDecomposition to validate cache matrices ([flutter/engine#29530](https://github.com/flutter/engine/pull/29530)) 2021-11-04 [skia-flutter-autoroll@skia.org](mailto:skia-flutter-autoroll@skia.org) Roll Skia from a05d3029ac65 to 37da672b14b7 (1 revision) ([flutter/engine#29534](https://github.com/flutter/engine/pull/29534)) 2021-11-04 [dnfield@google.com](mailto:dnfield@google.com) Re-enable A11yTreeIsConsistent with higher timeout ([flutter/engine#29367](https://github.com/flutter/engine/pull/29367)) 2021-11-04 [iska.kaushik@gmail.com](mailto:iska.kaushik@gmail.com) [raster_cache] Increment access_count on Touch ([flutter/engine#29529](https://github.com/flutter/engine/pull/29529)) 2021-11-04 [gw280@google.com](mailto:gw280@google.com) Remove D3D9 fallback path ([flutter/engine#29533](https://github.com/flutter/engine/pull/29533)) 2021-11-04 [akbiggs@users.noreply.github.com](mailto:akbiggs@users.noreply.github.com) [fuchsia] Add more logging for error cases. ([flutter/engine#29397](https://github.com/flutter/engine/pull/29397)) 2021-11-04 [andreidiaconu@users.noreply.github.com](mailto:andreidiaconu@users.noreply.github.com) Reland Display Features support (Foldable and Cutout) ([flutter/engine#29447](https://github.com/flutter/engine/pull/29447)) ...

**Pull request closed without merging**
