### PR TITLE
Mark module_test_ios tests unflaky

### PR DESCRIPTION
**Pull request by jmagman**
[Dart workaround](https://dart-review.googlesource.com/c/sdk/+/297821 ) to prevent the flake has rolled into the framework.  Mark the tests unflaky so we can detect if it happens again when a fix for the underlying issue lands.

https://github.com/flutter/flutter/issues/125425#issuecomment-1522142360

Reverts https://github.com/flutter/flutter/pull/125426

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by keyonghan — COMMENTED** [review]
Could we wait for the bot to auto deflake after 50 runs validation, just in case?

**Comment by jmagman** [comment]
> Could we wait for the bot to auto deflake after 50 runs validation, just in case?

I'd like to know if it starts flaking again if the dart team submits a fix for the underlying issue, but it doesn't work or is incomplete for some reason.

**Review by vashworth — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
This [failed](https://ci.chromium.org/ui/p/flutter/builders/staging/Mac%20module_test_ios/685/overview) not too long ago due to https://github.com/flutter/engine/pull/41533 and may have caught it in the presubmit of the engine roll.

Let's turn this back on.

**Pull request merged**
