### PR TITLE
Closes #37593 Add flutter_export_environment.sh to gitignore

### LINKED ISSUE #37593: Git ignore flutter_export_environment.sh
## Description

The `ios/Flutter/flutter_export_environment.sh` file created using `flutter create` explicitly states: 

>  \# This is a generated file; do not edit or check into version control.

Yet it is not part of the top level project `.gitignore`. 

## Proposal

Add `ios/Flutter/flutter_export_environment.sh` to `.gitignore.tml` files located at:

```
packages/flutter_tools/templates/app/.gitignore.tmpl
packages/flutter_tools/templates/package/.gitignore.tmpl
```

### PR DESCRIPTION
**Pull request by walsha2**
## Description

Closes #37593 - Please see that issue description.

## Tests

Manually tested to confirm that `.gitignore` templates with changes are implemented when using `flutter create`

## Checklist

All tasks completed: 

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Review by jmagman — CHANGES_REQUESTED** [review]
This also needs to be changed in:
dev/integration_tests/android_splash_screens/splash_screen_kitchen_sink/.gitignore
dev/integration_tests/android_splash_screens/splash_screen_load_rotate/.gitignore
dev/integration_tests/android_splash_screens/splash_screen_trans_rotate/.gitignore
dev/integration_tests/android_views/ios/.gitignore
dev/integration_tests/release_smoke_test/.gitignore
packages/flutter_tools/templates/plugin/ios.tmpl/.gitignore

**Comment by walsha2** [comment]
@jmagman copy. Will make that change later and push back up.

**Comment by walsha2** [comment]
@jmagman complete.

**Review by jmagman — APPROVED** [review]
Thank you! LGTM!

**Comment by jmagman** [comment]
This is ready to merge!

**Comment by walsha2** [comment]
> The general process for submitting code to a Flutter repository is as follows:
> ....
> 8. Once everything is green and you have an LGTM, land your patch.

@jmagman I'm not sure who or how step 8 above (from contribute section of Wiki) is performed. 

Or is that because the testing pipeline is showing "Flutter build is currently broken"? Im not sure why that is... Tests should all be passing.

**Comment by jmagman** [comment]
> > The general process for submitting code to a Flutter repository is as follows:
> > ....
> > 8. Once everything is green and you have an LGTM, land your patch.
> 
> @jmagman I'm not sure who or how step 8 above (from contribute section of Wiki) is performed.
> 
> Or is that because the testing pipeline is showing "Flutter build is currently broken"? Im not sure why that is... Tests should all be passing.

When I made that comment "flutter-build" was green.   Looks like the CI system is red though (not due to your change).  When it goes green again, please squash and merge!

**Comment by jmagman** [comment]
I merged it.  Thanks @walsha2!

**Pull request merged**
