### PR TITLE
Text selection handle color should default to accent color

### PR DESCRIPTION
**Pull request by lanmonster**
## Description

This PR changes the default textSelectionHandleColor to be accentColor. Previously, it switched on whether the theme was dark and chose between a teal color and the primary swatch color. moving forward, it will just pull from the accentColor, which itself does that check if not provided.

## Related Issues

[#17635](https://github.com/flutter/flutter/issues/17635)

## Tests

I added the following tests:

packages/flutter/lib/src/material/theme_data.dart:
- 'Text selection handle color defaults to accent color'

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [x] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [x] I wrote a design doc: https://flutter.dev/go/change-default-textselectionhandlecolor-to-accentcolor
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by dnfield — DISMISSED** [review]
This changes goldens and is almost certainly a breaking change - if it is the right change to make it will have to follow our breaking change policy.

**Comment by lanmonster** [comment]
I have written a design doc and made a request to update the firebase.json on the website project. waiting on the PR to land for the website so the design doc can be viewable.

**Comment by HansMuller** [comment]
This is a reasonable change however I'd like to defer the PR. We're planning a significant update to ThemeData that will remove Flutter's dependencies on the accent properties.

The Material Design spec no longer includes a color called ‘accent’ (the ‘secondary’ ColorScheme color is roughly equivalent). We considering defining a TextSelectionTheme and adding a TextSelectionThemeData valued property to ThemeData. The selection handles color, and other visuals related to text selection, would be part of the TextSelectionTheme.

A concrete proposal for the ThemeData update will be available early next year.

**Comment by Piinks** [comment]
Here is the previously mentioned proposal for updates to theming: [Material Theme System Updates](https://docs.google.com/document/d/1kzIOQN4QYfVsc5lMZgy_A-FWGXBAJBMySGqZqsJytcE/edit?usp=sharing).

In light of this scheduled work, I am going to close this pull request. Thank you for the contribution, and if you feel you would like to discuss this patch further, feel free to come back and let us know. Thanks! :)

**Pull request closed without merging**
