### PR TITLE
added example and renamed bad data class

### PR DESCRIPTION
**Pull request by antholeole**
- I've added two examples for magnifier. One uses the magnifier as just a widget, and the other uses it in text selection. I think they're both useful because a magnifier widget could be useful for general use cases and having an example of it would be nice, and the text selection magnifier example is useful because the API for consuming the `MagnifierInfoBearer` is a little involved so hopefully the example could smooth out some kinks should someone decide they want to modify the default loupes. 
- I also renamed `MagnifierOverlayInfoBearer` to no longer have `Overlay` in it. The old name implies that we're doing something with the overlay, which I don't really like: technically, if you want, you don't have to use the overlay. It just is helpful to so you can globally position. It's also shorter, which is useful for readability - the previous name was overly verbose. I'm also considering removing "Bearer" to just `MagnifierInfo` - thoughts?

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by antholeole** [comment]
@Renzo-Olivares @justinmc 

I wanted to write some examples for people if they ever want to use magnifier. The magnifier without the text field example works well, but I couldn't get the example with the text field to work. The golden would render empty and the CustomMagnifier would never show, although it works fine when you run it on device (flutter run -t). 

I currently have it passing CI without any tests for the magnifier version with the text field. Off the top of you heads, is there any reason why this https://github.com/flutter/flutter/pull/109050/commits/6d20af2978042aa83b149608ebae9e24c58ee483#diff-8896e72b4d23abd601288ddab8ded4319ef4b807679215f50314392baf96107dR1 test would pass in text_field_tests but not in the example repo? perhaps there's some setup that I'm missing....

**Comment by justinmc** [comment]
@antholeole The problem is just the platform!  When you run with `flutter test`, it's running it on desktop, and there are no text selection handles.  When you run with `flutter run -t`, you're probably running on an iOS emulator, and so the handles show and it passes.

I've modified your test to get it to work below.  I think all I changed was specifying the platform and adding a bit more offset to the handle Offset so that it reaches the handle on Android as well as iOS.

I know you're probably busy now, no worries about returning to this PR if so.  If you don't respond I'll just reopen this PR myself.

<details>

<summary>Working test</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_api_samples/widgets/text_magnifier/text_magnifier.0.dart'
    as example;
import 'package:flutter_test/flutter_test.dart';

List<TextSelectionPoint> _globalize(
    Iterable<TextSelectionPoint> points, RenderBox box) {
  return points.map<TextSelectionPoint>((TextSelectionPoint point) {
    return TextSelectionPoint(
      box.localToGlobal(point.point),
      point.direction,
    );
  }).toList();
}

RenderEditable _findRenderEditable<T extends State<StatefulWidget>>(
    GlobalKey<T> key) {
  final T state = key.currentState!;
  assert(state is TextSelectionGestureDetectorBuilderDelegate,
      'State of textFieldKey must conform to TextSelectionGestureDetectorBuilderDelegate');
  final EditableTextState editableTextState =
      (state as TextSelectionGestureDetectorBuilderDelegate)
          .editableTextKey
          .currentState!;
  return editableTextState.renderEditable;
}

Offset _textOffsetToPosition<T extends State<StatefulWidget>>(
  // the global key's state must refer to a TextSelectionGestureDetectorBuilderDelegate.
  GlobalKey<T> textFieldKey,
  int offset,
) {
  final RenderEditable renderEditable = _findRenderEditable(textFieldKey);

  final List<TextSelectionPoint> endpoints = renderEditable
      .getEndpointsForSelection(
        TextSelection.collapsed(offset: offset),
      )
      .map<TextSelectionPoint>((TextSelectionPoint point) => TextSelectionPoint(
            renderEditable.localToGlobal(point.point),
            point.direction,
          ))
      .toList();

  return endpoints[0].point + const Offset(0.0, -2.0);
}

void main() {
  testWidgets('should show custom magnifier on drag',
      (WidgetTester tester) async {
    const Duration durationBetweenActons = Duration(milliseconds: 20);

    await tester.pumpWidget(const example.MyApp());

    final TextField textField = tester.firstWidget(find.byType(TextField));
    final GlobalKey<State<StatefulWidget>> textFieldKey =
        textField.key! as GlobalKey<State<StatefulWidget>>;

    final Offset tapOffset = _textOffsetToPosition(
      textFieldKey,
      example.MyApp.textFieldText.indexOf('e'),
    );

    // Double tap 'Magnifier' word to show the selection handles.
    final TestGesture testGesture = await tester.startGesture(tapOffset);
    await tester.pump(durationBetweenActons);
    await testGesture.up();
    await tester.pump(durationBetweenActons);
    await testGesture.down(tapOffset);
    await tester.pump(durationBetweenActons);
    await testGesture.up();
    await tester.pumpAndSettle();

    final TextSelection selection = textField.controller!.selection;

    final RenderEditable renderEditable = _findRenderEditable(textFieldKey);
    final List<TextSelectionPoint> endpoints = _globalize(
      renderEditable.getEndpointsForSelection(selection),
      renderEditable,
    );

    final Offset handlePos = endpoints.last.point + const Offset(10.0, 10.0);

    final TestGesture gesture = await tester.startGesture(handlePos);

    await gesture.moveTo(_textOffsetToPosition(
      textFieldKey,
      example.MyApp.textFieldText.length - 2,
    ));
    await tester.pump();

    expect(find.byType(example.CustomMagnifier), findsOneWidget);

    await expectLater(
      find.byType(example.MyApp),
      matchesGoldenFile('text_magnifier.0_test.png'),
    );
  }, variant: const TargetPlatformVariant(<TargetPlatform>{ TargetPlatform.iOS,  TargetPlatform.android }));
}
```

</details>

**Comment by antholeole** [comment]
Ohhhhh that makes sense! Ill try to finish this out when I have some free time. I’ll tag you again when it’s ready for review :) marking as draft for the time being

**Comment by antholeole** [comment]
Closing in favor of https://github.com/flutter/flutter/pull/110218 - had to juke the CLA out. My @google got deleted and as a consequence it's CLA - but since I committed under my @google, it wanted oleina@google to sign the CLA, which no longer exists. Attempted a rebase but the merge from master made it a ton of work.

**Pull request closed without merging**
