### PR TITLE
Roll engine 12315736f9ca..c0e6f6a6e665 (6 commits)

### PR DESCRIPTION
**Pull request by engine-flutter-autoroll**
https://github.com/flutter/engine/compare/12315736f9ca...c0e6f6a6e665

git log 12315736f9ca..c0e6f6a6e665 --no-merges --oneline
c0e6f6a6e Roll src/third_party/skia 76bba35cbaa4..46a5f6c28a34 (1 commits) (flutter/engine#6244)
49ef4adad Fix a crash when UILaunchStoryboardName is not specified in Info.plist (flutter/engine#6234)
2a433bc68 Roll src/third_party/skia 34e5e1b387f5..76bba35cbaa4 (2 commits) (flutter/engine#6243)
0c28a093a Roll src/third_party/skia 858f648bdae3..34e5e1b387f5 (8 commits) (flutter/engine#6241)
513f8fbae Roll src/third_party/skia 16322637c477..858f648bdae3 (7 commits) (flutter/engine#6240)
9a7d7215a Roll src/third_party/skia 44215505623b..16322637c477 (10 commits) (flutter/engine#6238)

The AutoRoll server is located here: https://autoroll.skia.org/r/flutter-engine-flutter-autoroll

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/&#43;/master/autoroll/README.md

If the roll is causing failures, please contact the current sheriff, who should
be CC&#39;d on the roll, and stop the roller if necessary.

### CODE REVIEW

**Comment by engine-flutter-autoroll** [comment]
@rmistry @liyuqian : New roll has been created by https://autoroll.skia.org/r/flutter-engine-flutter-autoroll

**Comment by goderbauer** [comment]
Closing because it is stuck: cirrus has completed all checks successfully, but github's new checks feature still shows one check as pending.

**Comment by goderbauer** [comment]
@fkorotkov This PR is also having trouble with github's new Checks thing: Cirrus has completed the task `codelabs-build-test` successfully, but github believes it's still pending.

**Comment by goderbauer** [comment]
Actually, since this seems to be a bug with github and/or cirrus I am going to submit this one manually.

**Comment by engine-flutter-autoroll** [comment]
Commit queue failed; closing this roll.

**Comment by rmistry** [comment]
> @goderbauer, sorry about that. I've been working with GitHub engineers on fixing these issues. Provided all the logs to them so hopefully they'll fix "seems like a race condition" issues.

@fkorotkov 
I have been seeing this happening more frequently on the other github roller. Was there a bug filed to Github where they were investigating this?

Thanks!

**Comment by fkorotkov** [comment]
@rmistry let me check with them. Haven't heard anything so far. Do you have a link to a recent build?

**Comment by rmistry** [comment]
@fkorotkov  Here is a recent roll that is stuck: https://github.com/flutter/engine/pull/7104

**Pull request merged**
