### PR TITLE
Make ios_deploy_test.dart more robust

### PR DESCRIPTION
**Pull request by mkustermann**
The test should not assume that a stream of bytes delivers them in a certain chunked order (e.g. all bytes of a line are delivered in one chunk and the newline comes in another chunk).

Instead it should use a line splitter to obtain individual lines and can match those against expectations.

This fragile test is broken after [0] which combines writing a string together with the newline instead of seperately.

[0] https://dart-review.googlesource.com/c/sdk/+/378024

### CODE REVIEW

**Review by osa1 — APPROVED** [review]

**Comment by mkustermann** [comment]
Thanks, @osa1

**Comment by jtmcdole** [comment]
Fixes  #153163

**Comment by a-siva** [comment]
> /cc @a-siva

Thanks for fixing the test @mkustermann

**Pull request merged**
