### PR TITLE
[flutter_tools] forward all args to pub

### LINKED ISSUE #69915: null safety mode for `pub outdated` doesn't work in the flutter tool
Repro:
```
$ flutter pub outdated --mode=null-safety
Could not find an option named "mode".
```

Seems to be related to args parsing, as this works:
```
$ flutter pub outdated -- --mode=null-safety
Running in 'null safety' mode.
Showing packages where the current version doesn't fully support null safety.```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Change forwarding command to pass through all args, even -h - this allows flutter to support all of the pub flags without needing to declare them.

Fixes https://github.com/flutter/flutter/issues/69915

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
Might also fix:
https://github.com/flutter/flutter/issues/33324
https://github.com/flutter/flutter/issues/42832
https://github.com/flutter/flutter/issues/61186

**Comment by jonahwilliams** [comment]
I don't think it will fix any of those unfortunately 😆

**Comment by jmagman** [comment]
> I don't think it will fix any of those unfortunately 😆

You're right.

> #33324

`packages pub global` resolves to `PackagesPassthroughCommand` not `PackagesForwardCommand`, which does require a pubspec.

> #42832

`pub upgrade` uses `PackagesGetCommand` not `PackagesForwardCommand`.

> #61186

Not a subcommand.

**Comment by jmagman** [comment]
`PackagesPassthroughCommand` and `PackagesForwardCommand` might be combinable now.

**Pull request merged**
