### PR TITLE
[framework] SliverDecoration

### PR DESCRIPTION
**Pull request by jonahwilliams**
Avoid situations where users place scrollable content in a Column just so they can wrap it in a Container to add some kind of BoxDecoration. For example, I've seen stuff like:

```
CustomScrollView(
  slivers: [
    SliverToBoxAdaptor(
      child: Container(
         color: Colors.red,
         child: Column( ...),
      ),
    ),
  ]
)

```

Which totally defeats the purpose of scroll views

### CODE REVIEW

**Comment by jonahwilliams** [comment]
I don't think the golden tests I added are super useful, I'll update them a bit so they actually have some content

**Comment by jonahwilliams** [comment]
Renamed to SliverDecoration to matching existing sliver widgets

**Review by Piinks — COMMENTED** [review]
Love this! 😻 

Can you add a reference in the docs for DecoratedBox and/or BoxDecoration to make this more discoverable?

**Comment by jonahwilliams** [comment]
I added some breadcrumbs to the "see also" section of the BoxDecoration and DecoratedBox docs

**Review by Piinks — APPROVED** [review]
lgtm-very

**Comment by Kavantix** [comment]
> Well the only one I can immediately disagree with is `4`, which is that I chose the name to be consistent with the other sliver widgets like `SliverPadding` and `SliverList`. 🐈

Well this name suggests it’s a counterpart to [BoxDecoration](https://api.flutter.dev/flutter/painting/BoxDecoration-class.html)

**Comment by Kavantix** [comment]
And probably there should actually be a `SliverDecoration` that has specific properties related to decorating slivers rather than boxes

**Comment by jonahwilliams** [comment]
Yes, but then it would be named differently from all of the other Sliver* widgets

**Comment by Kavantix** [comment]
You could technically name it `SliverDecorated` or `SliverWithDecoration` but `DecoratedSliver` is both nicer and more discoverable for someone that knows about `DecoratedBox`
This is also how I ended up with the name `MultiSliver` in sliver_tools, there just want a good name that started with Sliver, covered the load and wasnt unwieldy

**Comment by jonahwilliams** [comment]
I like SliverDecorated

**Comment by jonahwilliams** [comment]
but its a bit odd still IMO, we don't do past tense for the most part. I.e. its SliverPadding and not SliverPadded

**Comment by Kavantix** [comment]
I agree and wouldnt have even mentioned the name if it werent for BoxDecoration not being the widget but the configuration. And we’ll run into this same thing when inevitably adding a Sliver counterpart to ColoredBox.

Perhaps in light of this and the widget not being finished it would make more sense to not put it in the framework itself just yet?

**Pull request merged**
