### PR TITLE
iOS: update provisioning profile for 2024-2025 cert

### PR DESCRIPTION
**Pull request by cbracken**
Tells our iOS bots to use the provisioning profile stored in the flutter_internal/mac/mobileprovision CIPD packages tagged `version:to_2025`.

This CIPD package contains an updated provisioning profile which supports both the current development signing certificate expiring in October 2024, and the updated signing cert expiring in August 2025.

Also removes the CIPD dependency for devicelab tasks. On devicelab bots, the cert and provisioning profile are deployed via Salt, not via CIPD. We only need this dependency on the Chromium bots.

CIPD packages can be seen at:
https://chrome-infra-packages.appspot.com/p/flutter_internal/mac/mobileprovision

Required for: https://g-issues.chromium.org/issues/366034566

Issue: https://github.com/flutter/flutter/issues/152888

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by bdero — APPROVED** [review]
LGTM

**Review by christopherfujino — APPROVED** [review]
LGTM, although bonus points if you remove the apple_signing dep from "mac_arm64_ios"

**Comment by christopherfujino** [comment]
LED builds for the affected devicelab targets:

https://ci.chromium.org/b/8737050001693267361
https://ci.chromium.org/b/8737050000155673009
https://ci.chromium.org/b/8737049998522993985
https://ci.chromium.org/b/8737049996755234689
https://ci.chromium.org/b/8737049995334845409
https://ci.chromium.org/b/8737049993918974145
https://ci.chromium.org/b/8737049992459741985
https://ci.chromium.org/b/8737049990829461057
https://ci.chromium.org/b/8737049989339340449
https://ci.chromium.org/b/8737049987930091633
https://ci.chromium.org/b/8737049986443173729
https://ci.chromium.org/b/8737049984990281233
https://ci.chromium.org/b/8737049983400510897
https://ci.chromium.org/b/8737049981862627937
https://ci.chromium.org/b/8737049979960894225
https://ci.chromium.org/b/8737049978181515713
https://ci.chromium.org/b/8737049976829787297
https://ci.chromium.org/b/8737049975282219873
https://ci.chromium.org/b/8737049973432993873
https://ci.chromium.org/b/8737049971989360529
https://ci.chromium.org/b/8737049970402188209
https://ci.chromium.org/b/8737049964637731441
https://ci.chromium.org/b/8737049963287442593
https://ci.chromium.org/b/8737049961809794801
https://ci.chromium.org/b/8737049960084973665
https://ci.chromium.org/b/8737049958706246849
https://ci.chromium.org/b/8737049957247965745
https://ci.chromium.org/b/8737049955740975041
https://ci.chromium.org/b/8737049954126617057
https://ci.chromium.org/b/8737049952507941937
https://ci.chromium.org/b/8737049951006804017
https://ci.chromium.org/b/8737049949403292769
https://ci.chromium.org/b/8737049947682499697
https://ci.chromium.org/b/8737049945992645425
https://ci.chromium.org/b/8737049944391903409
https://ci.chromium.org/b/8737049943110513841
https://ci.chromium.org/b/8737049941458107761
https://ci.chromium.org/b/8737049938975567393
https://ci.chromium.org/b/8737049937545416449
https://ci.chromium.org/b/8737049936229504321
https://ci.chromium.org/b/8737049934728244529
https://ci.chromium.org/b/8737049933381137553
https://ci.chromium.org/b/8737049931809080001
https://ci.chromium.org/b/8737049930298073025
https://ci.chromium.org/b/8737049928959513233
https://ci.chromium.org/b/8737049927643929985
https://ci.chromium.org/b/8737049926183578033
https://ci.chromium.org/b/8737049924574599745
https://ci.chromium.org/b/8737049923038819697
https://ci.chromium.org/b/8737049921535206737
https://ci.chromium.org/b/8737049920050742561
https://ci.chromium.org/b/8737049918542265633
https://ci.chromium.org/b/8737049917222046689
https://ci.chromium.org/b/8737049915750627601
https://ci.chromium.org/b/8737049914258627633
https://ci.chromium.org/b/8737049912627898737

**Comment by zanderso** [comment]
Reason for revert: The tree is red on this change: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8737044980814837569/+/u/run_flutter_gallery_ios__compile/stdout.

**Comment by christopherfujino** [comment]
> Reason for revert: The tree is red on this change: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8737044980814837569/+/u/run_flutter_gallery_ios__compile/stdout.

The breakage was my fault, even though I scheduled a billion LED builds, I forgot to point them at this PR, so they just tested tip of tree.

**Comment by cbracken** [comment]
Summary of breakage: we got a bit too enthusiastic trying to bundle the removal of the CIPD dependency alongside the version upgrade.

The devicelab bots get their certs/provisioning profile via the devicelab Salt configuration server (Googlers, see: go/flutter-salt) but they're relying on apple_signing dependency to trigger the apple_signing recipe step, which unlocks the keychain. The CIPD package isn't actually being downloaded by the recipe on device lab bots (it is on chromium bots), but we rely on this being in CIPD.yaml to trigger the unlock.

**Pull request merged**
