### PR TITLE
Turn timer_picker_test goldens back on

### PR DESCRIPTION
**Pull request by xster**
We were facing some infra issues in https://github.com/flutter/flutter/pull/65501. Splitting it off to diagnose here.

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 30 untriaged digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/67555

**Comment by xster** [comment]
The golden outputs look correct now

**Review by Piinks — APPROVED** [review]
Flutter_LGTM
Thanks for working through the infra issues with me! :)

**Comment by Piinks** [comment]
It looks like the Google testing shard is stuck, and I can't seem to kick it manually, can you push a new commit? :)

**Comment by xster** [comment]
pinged the google chat. Not in a rush. Let's see if they find any useful infra debugging data from this. I couldn't restart a test on rob either.

**Pull request merged**
