### PR TITLE
Add benchmark to property

### PR DESCRIPTION
**Pull request by KristinBi**
Add the benchmark to property. Let benchmark to be true to show that this build is a benchmark test.

Referred to https://github.com/flutter/flutter/issues/98004 for all benchmark tests.

### CODE REVIEW

**Review by CaseyHillers — CHANGES_REQUESTED** [review]
Let's hold off on changing the .ci.yaml for now. Let's land the changes to Cocoon first, and test them before changing the prod configs

**Comment by keyonghan** [comment]
> Let's hold off on changing the .ci.yaml for now. Let's land the changes to Cocoon first, and test them before changing the prod configs

These are target properties and should be no-op changes?

**Comment by keyonghan** [comment]
Instead of `benchmark: true`, we should use `benchmark: "true"`

**Review by CaseyHillers — COMMENTED** [review]
+1 to Keyong's comment, this LGTM otherwise

**Review by CaseyHillers — APPROVED** [review]
Approving to remove the request changes. Please wait on Keyong's approval before landing.

**Review by keyonghan — APPROVED** [review]
Benchmark property is populating to the build:
https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20web_benchmarks_html/9744/overview (see `Input Properties`)

Let's land this. LGTM.

**Comment by keyonghan** [comment]
@KristinBi We need to wait for all tests pass, and then add label `Waiting for Tree to go green` and let bot auto submit.

**Comment by KristinBi** [comment]
Thanks Keyong and Casey, I will add the label later to let it auto submit.

**Comment by CaseyHillers** [comment]
Re Mac plugin_lint_mac, you'll need to rebase this branch on tip of tree to get the fix for that breakage.

**Comment by jmagman** [comment]
> Re Mac plugin_lint_mac, you'll need to rebase this branch on tip of tree to get the fix for that breakage.

Sorry, make that https://github.com/flutter/flutter/pull/98171.

**Pull request merged**
