### PR TITLE
Fix globs in runIf configurations.

### PR DESCRIPTION
**Pull request by godofredoc**
Several tests have not been running on presubmit after the glob behavior was fixed in the cocoon backend. This change updates runIf configs to make consistent use of globs.

Bug: https://github.com/flutter/flutter/issues/122157

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by christopherfujino** [comment]
cc @keyonghan, I thought https://github.com/flutter/flutter/issues/122157 was fixed by https://github.com/flutter/cocoon/pull/2516. Were ALL of these runIf conditions really wrong?

**Comment by jmagman** [comment]
Cocoon backend glob fix was https://github.com/flutter/cocoon/pull/2506

**Comment by christopherfujino** [comment]
> Cocoon backend glob fix was [flutter/cocoon#2506](https://github.com/flutter/cocoon/pull/2506)

So all of these runIf conditions were wrong for 2 weeks because they didn't actually glob and we added a `$` to the end of the regex?

**Comment by godofredoc** [comment]
> ll of these runIf conditions were wrong for 2 weeks because they didn't actually glob and we added a `$` to the end of the regex

That's correct, we created that fix because the builds using the glob were not being run correctly but didn't check the configs in .ci.yaml apart from the ones referenced in the bug.

**Review by keyonghan — APPROVED** [review]
LGTM

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
> > ll of these runIf conditions were wrong for 2 weeks because they didn't actually glob and we added a `$` to the end of the regex
> 
> That's correct, we created that fix because the builds using the glob were not being run correctly but didn't check the configs in .ci.yaml apart from the ones referenced in the bug.

Oh interesting. I'm surprised this wasn't more disruptive.

**Pull request merged**
