### PR TITLE
Reland "Hide text selection toolbar when dragging handles on mobile"

### LINKED ISSUE #62193: Hide selection toolbar on iOS and Android when moving paddles/caret
The selection toolbar in Flutter does not behave as the native one on iOS. The native behaviour is to hide the selection toolbar while the user is moving the caret and then show it once he release the caret. Flutter is actually showing the toolbar all the time. See the GIF bellow.

aa11

<details>
<summary> Complete sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(TextDemo());

class TextDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Text Wrap Demo',
        home: Scaffold(
          body: Center(
            child: TextField(),
          ),
        ),
    );
  }
}
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-AO)
    • Flutter version 1.21.0-1.0.pre at /Users/pedro/dev/SDKs/flutter_dev
    • Framework revision f25bd9c55c (9 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/pedro/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe)
    ! /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe is not
      executable.

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/pedro/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9
      (API 28) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server (web)             • web-server    • web-javascript • Flutter
      Tools

! Doctor found issues in 1 category.
```
</details>

Cc @LongCatIsLooong because you worked in the selection toolbar before.

### PR DESCRIPTION
**Pull request by markusaksli-nc**
Relands https://github.com/flutter/flutter/pull/104274

Fixes https://github.com/flutter/flutter/issues/62193

### CODE REVIEW

**Review by justinmc — APPROVED** [review]
LGTM 👍 

So sorry I missed this notification!

**Comment by justinmc** [comment]
@TahaTesser It seems like there is a legit test failure after that push.  I almost just pressed the merge button last night but maybe it's good that I didn't.  Thanks for updating it.

**Comment by markusaksli-nc** [comment]
Thanks @TahaTesser for the rebase. @justinmc I'll be back from vacation Monday, and I'll take a look at the test failure.

**Comment by justinmc** [comment]
Sounds good, enjoy your vacation!

**Comment by markusaksli-nc** [comment]
It looks like this was already implemented with the magnifier

**Comment by justinmc** [comment]
Ah sorry I should have realized that and closed the issue.  Anyway, glad it's fixed!

**Pull request closed without merging**
