### PR TITLE
[flutter_test] handle breaking change to test main

### LINKED ISSUE #67382: Erroneous main methods in flutter_goldens and flutter_test
These files have erroneous main methods wrt nnbd:

packages/flutter_goldens/lib/flutter_goldens.dart
packages/flutter_test/test/custom_exception_reporter/flutter_test_config.dart

The first parameter needs to be a supertype of List<String>.

https://github.com/dart-lang/sdk/commit/4c29f26fc69d4ced6f58bc5ed854eb3d20283225

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Use a name other than `main` for the test config entrypoint

Fixes https://github.com/flutter/flutter/issues/67382

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
lgtm on green presubmits

**Comment by jonahwilliams** [comment]
Apparently this change is quite breaking for g3

**Comment by jonahwilliams** [comment]
This change passed according to the google testing UI, landing

**Comment by tsimbalar** [comment]
Sorry to intervene on a closed PR but ... I think after those changes, the documentation at 

https://github.com/flutter/flutter/blob/f9df1935fedee5f65e761659d24b4768aa4a1766/packages/flutter_test/lib/flutter_test.dart#L18-L35

is now incorrect, right ?

**Pull request merged**
