### PR TITLE
CupertinoDatePicker with month and year (#93508)

### PR DESCRIPTION
**Pull request by hunterwilhelm**
Continuing with the pattern between the modes `date` and `time` having two different states.
Made a `monthYear` state that renders and stores values for month and year Is compatible with the localization of the `date` mode.
Changed asserts to match the same expectations.

Fixes issue/feature requests: [#93508]

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by hunterwilhelm** [comment]
I am stuck on making the tests. I am not understanding the `matchesGoldenFile` function. I am getting guidance in discord under the #hackers-framework-🔩 channel

**Comment by MitchellGoodwin** [comment]
Hi @hunterwilhelm. Hope all is well. Are you still working on this?

**Comment by MitchellGoodwin** [comment]
Hi @hunterwilhelm. I hope all is going well. As this has not been updated in some time I am going to close this PR to clear up our queue. Please feel free to reopen if you ever are able to work on this change again. :)

**Comment by hunterwilhelm** [comment]
For anyone wondering, this feature was added by the flutter team in 3.13! https://medium.com/flutter/whats-new-in-flutter-3-13-479d9b11df4d

**Pull request closed without merging**
