### PR TITLE
Add child for placeholder widget

### PR DESCRIPTION
**Pull request by M97Chahboun**
Adds a `child` property to `Placeholder` widget & test it,

Fixes  #100204

<details>
  <summary>Demo</summary>
  
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Column(
      children: [
        Placeholder(
            child: Center(
          child: Text("Image", style: Theme.of(context).textTheme.headline3),
        )),
        Expanded(
          child: Placeholder(
              child: Center(
            child: Text("Description",
                style: Theme.of(context).textTheme.headline3),
          )),
        )
      ],
    ));
  }
}
```
</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.
**I can't pass all existing tests because my Mac slow, but I passed placeholder test.**

### CODE REVIEW

**Comment by HansMuller** [comment]
The "trailing spaces" problem should be easy to fix

**Review by HansMuller — COMMENTED** [review]
Sadly, it looks like flutter/packages/flutter/test/widgets/keep_alive_test.dart and flutter/dev/tracing_tests/test/timeline_test.dart depend on Placeholder haveing a CustomPainter with a foregroundPainter called `_PlaceholderPainter`. You'll need to fix those tests.

**Comment by M97Chahboun** [comment]
@HansMuller 
Thank you for your help,
I solved issue from `keep_alive_test.dart` & I passed test for it,
& I test `flutter/dev/tracing_tests/test/timeline_test.dart` with `flutter test timeline_test.dart --enable-vmservice` successful.

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by HansMuller** [comment]
I'm afraid that this PR's bots are stuck. The simplest thing to do is to push an empty commit to force the tests to restart. To create an empty commit:

git commit --allow-empty -m 'Empty commit to force all tests to rerun'

**Comment by M97Chahboun** [comment]
Thank you for your help.

**Comment by HansMuller** [comment]
Sadly, now it looks like an unrelated problem is holding this up.  You'll need to rebase and push another commit. Sorry about the hassle.

**Comment by ZakatKnowledge** [comment]
@HansMuller 
Are you means push another empty commit or create another branch & do new PR ? 
Thank you.

**Comment by M97Chahboun** [comment]
@HansMuller 
Not problem, Are you means push new commit or create another branch and do new PR!
Thank you.

**Comment by HansMuller** [comment]
@M97Chahboun - rebasing with master and force-pushing a new commit will work. Or just creating a new PR will work too.

**Comment by M97Chahboun** [comment]
OK, Thank you

**Review by HansMuller — APPROVED** [review]
LGTM

**Pull request merged**
