### PR TITLE
Remove fancy lines demo from Gallery

### PR DESCRIPTION
**Pull request by abarth**
This demo burns battery continuously even when there's no change to the visual
appearance. This patch removes this demo to avoid giving the impression that
Flutter burns battery.

Related to #4120

### CODE REVIEW

**Comment by abarth** [comment]
@HansMuller

**Comment by Hixie** [comment]
See https://github.com/flutter/flutter/issues/4120
We should first split the gallery in two so that we still have these parts to debug known issues with them.

**Comment by Hixie** [comment]
Oh actually never mind. This particular demo isn't affected by that.

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
