### PR TITLE
Fix flex floating point error causing unnecessary striped warnings

### PR DESCRIPTION
**Pull request by Hixie**
Also:

 * Provide a better message when you lerp from infinity to finity
   constraints.

 * Make the striped marker support RTL.

 * By popular demand, dump a warning to the console the first time
   a particular Flex overflows. (Resets on hot reload.)

### CODE REVIEW

**Comment by Hixie** [comment]
Fixes https://github.com/flutter/flutter/issues/12423

**Comment by Hixie** [comment]
cc @apwilson

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
We'll need to update the revision of package:flutter that Fuchsia uses after this change lands:

https://fuchsia.googlesource.com/manifest/+/master/flutter#7

**Comment by Hixie** [comment]
Apparently I broke some of our more obscure sanity checks, I'll have to fix those before I land.

**Comment by Hixie** [comment]
Fixes https://github.com/flutter/flutter/issues/12119

**Comment by JosephDunivan** [comment]
Was this ever fixed? It's driving me insane.

**Comment by Hixie** [comment]
the patch here was landed; if you're still seeing this please file a new bug with some code that shows the problem

**Comment by SnehaInGitHub** [comment]
I am getting the same issue. Don't know how to solve it.
Screenshot_1554357391

**Pull request merged**
