### PR TITLE
Add optional border to CupertinoSwitch

### PR DESCRIPTION
**Pull request by matekdev**
## Description

Adds the ability to show a border around a `CupertinoSwitch`. The border width and color can be adjusted.

preview

## Related Issues

Addresses the issue posted: https://github.com/flutter/flutter/issues/63407

## Tests

I added the following tests:
`switch_test.dart`
- Checks if `borderColor` gets property set
- Checks if `borderWidth` gets property set
- Checks if negative `borderWidth` doesn't cause exceptions
- Pre-existing tests handle the cases of `borderColor` and `borderWidth` potentially being null

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by mzegar** [comment]
There is nothing to update, this PR is ready to go and addresses https://github.com/flutter/flutter/issues/63407

**Comment by mzegar** [comment]
@Hixie Hey, apologies for poking you, could I get this reviewed by the appropriate parties? PR has been sitting around for a while waiting.

**Comment by mzegar** [comment]
@googlebot I fixed it.

**Comment by mzegar** [comment]
@googlebot I fixed it.

**Comment by mzegar** [comment]
@googlebot I fixed it.

**Comment by Hixie** [comment]
Any idea what the test failures are? Fixing those will be needed regardless if we're to land this. :-)

cc @xster and @HansMuller for review

**Comment by mzegar** [comment]
@Hixie Hello! yeah I see those failing tests. This PR was sitting for a while without any merge conflicts up until a few days ago. I've only had the chance recently to fix the conflicts and I'll look into the failing tests.

**Comment by xster** [comment]
Closing this as discussed in https://github.com/flutter/flutter/issues/63407 since there is no corresponding effect or customization available in iOS 14 / Xcode. Please feel free to reopen the PR or the issue if there's some feasibly functionality in iOS that's absent in Flutter.

**Pull request closed without merging**
