### PR TITLE
Explain why devtools in pinned

### PR DESCRIPTION
**Pull request by zanderso**
See discussion on https://github.com/flutter/flutter/pull/77637

Are there any other instances where this is pinned? @jonahwilliams @kenzieschmoll

### CODE REVIEW

**Comment by jonahwilliams** [comment]
I dunno, I didn't add this pin :) 

The tool is unpinned right now. FWIW, we're meeting later this week to discuss shipping devtools in the SDK, that might reduce the complexity here.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by kenzieschmoll — APPROVED** [review]
+1 to what Jonah said.

**Pull request merged**
