### PR TITLE
Remove use of BundleUtilities in Linux build

### LINKED ISSUE #58883: Remove use of BundleUtilities in Linux build
When switching to CMake for the Linux desktop build I used `BundleUtilities` to create the relocatable folder, as it seemed like a straightforward and relatively error-proof way of getting all the dependent libraries. However, it has some undesirable properties:
- AFAICT there is no way to control where the libraries it copies end up, so they are all just next to the executable, instead of in a `libs` subfolder as the previous Make build structure used. While not a big deal, it makes for a messy folder.
- How it decides what to copy is something of a black box. In theory it doesn't copy system libraries, but how it decides what a system library is doesn't seem to be something we can control. If someone wanted to use any kind of sysroot, for instance, it would copy basically everything.

Since in general having a fully declarative build system works out better than having magical steps, I think using it was the wrong choice. We should instead explicitly declare the libraries we need, and copy them ourselves.

The necessary changes I'm aware of:
- Set the rpath, which `BundleUtilities` currently does for us. IIRC `CMAKE_INSTALL_RPATH` worked when I was first experimenting with different approaches, but if not we can do it directly in the build as we used to in the Makefile. (The unbundled version isn't launchable anyway, so the rpath of the unbundled copy of the binary doesn't matter.)
- Copy the Flutter library. Prior my adopting `BundleUtilities` I just had the path to the library as another variable exported to parent scope by `flutter/CMakeLists.txt` (it already exports a couple of things).
- Copy the plugin libraries, and do so in a way that allows plugins to add other libraries to that list and have them copied. (While I think in general things will work out better in the ecosystem if plugins statically link their non-system dependencies, that won't always be viable; e.g., a plugin wrapping a binary-only SDK library.) My preference for how to do that is to establish an "API" convention that each plugin exports something like `<plugin_name>_bundled_libraries` to parent scope, which is a list of absolute paths of libraries to copy (including the build product of the plugin itself), and then have the generated_plugins.cmake assemble that into a mega-list that it then exports in turn to its parent scope (the top-level CMake file), which uses it for copying.

A couple of notes on approaches that would be simpler, but that I don't want to use:
- Have plugin builds manipulate the mega-list directly, which would be trivial. This increases the chances that plugin authors will break things in hard-to-find ways. As a simple example, if plugin A accidentally *sets*, rather than appends to, the list, then it'll work fine in isolated testing, but when someone tries to build with plugin A and plugin B, the error will be that plugin *B*'s library is missing on launch, which will cause a lot of extra headache for users and other plugin authors. Having a policy that plugin build files should only make local changes, and export things up, will be much safer for the ecosystem. (Yes, people can still break things at the top level other ways, but I don't want to normalize things that can do that, like changing outside variables.)
- Having the copying done by an install directive in each plugin's build file (e.g., by providing a variable from the top level for a directory to copy into). My concern with this is that it puts more control about the actual behavior into the plugin build files, and once plugins are published we lose the ability to easily make any changes. The more we can have plugins export information about themselves rather than embed logic, the more flexibility we will have to make changes even after the ecosystem is established.

/cc @MarcusTomlinson

### PR DESCRIPTION
**Pull request by MarcusTomlinson**
## Description

This PR removes the use of CMake's `BundleUtilities` in Linux builds.

This implementation explicitly bundles the Flutter library, automatically bundles plugin libraries via the `$<TARGET_FILE:${plugin}_plugin>` generator expression, and allows plugins to specify further dependancies via an optional `<plugin_name>_bundled_libraries` list.

All libraries are also now copied into a "lib" directory within the bundle instead of just next to the executable.

## Related Issues

Resolves: https://github.com/flutter/flutter/issues/58883

## Tests

Updated 'Injecting creates generated Linux plugin Cmake file'.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by stuartmorgan-g — CHANGES_REQUESTED** [review]
A few small things, but overall looks good. Thanks for doing this!

**Review by stuartmorgan-g — APPROVED** [review]
LGTM!

**Comment by zanderso** [comment]
@stuartmorgan is this ready to land? Would you like to mark it 'waiting for tree to go green'?

**Comment by stuartmorgan** [comment]
@zanderso For committers, I generally leave it up to them how they want to land PRs.

**Comment by MarcusTomlinson** [comment]
Sorry, I didn’t know this was waiting on me to merge.

**Pull request merged**
