### PR TITLE
Treat missing --local-engine-host as fatal on CI-like systems.

### PR DESCRIPTION
**Pull request by matanlurey**
Partial work towards https://github.com/flutter/flutter/issues/132245.

The goal here is to "sniff" out any missing pieces that would block engine builds, rolls, benchmarks and so on before requiring humans to provide the parameter. The implementation is based on a [short discussion with @christopherfujino](https://discord.com/channels/608014603317936148/608022056616853515/1141503921546875110):

@matanlurey:

> Not sure whether to post here or ⁠hackers-infra-🌡 , but is there a way to (and is it advisable to) detect whether the tool is running in a CI environment? I'd like to "soft enforce" --local-engine-host being provided strictly on CI, make sure that lands well, and then "upgrade" it to being non-CI invocations as well (re: https://github.com/flutter/flutter/issues/132245).
>
> Also happy to get talked out of this idea 🙂

@christopherfujino:

> we have a check, lemme find it
> whether or not it is advisable, idk
> https://github.com/flutter/flutter/blob/flutter-3.14-candidate.0/packages/flutter_tools/lib/src/base/bot_detector.dart#L30
>
> (...)
>
> is your desire to get early signal before enforcing t his for humans to prevent functionality churn of landing and reverting and re-landing? 
>
> (yes)
>
> uhh, sure, that's advisable 🙂

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by whesse** [comment]
No errors have shown up in the Dart CI after this change landed.

**Comment by whesse** [comment]
Errors have shown up on Flutter engine CI: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8772529585020554513/+/u/Framework_analyze/Update_packages/stdout

**Comment by whesse** [comment]
A fix for the flutter engine CI errors is at https://flutter-review.googlesource.com/c/recipes/+/49620

Please log in to this review host, which creates an account, so you can be added as CC on reviews on this site.

A further use of --local-engine with a matching --local-engine-host is in the devicelab drone runners, which get their local engine value from an environment variable LOCAL_ENGINE, with no matching environment variable LOCAL_ENGINE_HOST.  They pass the --local-engine flag to the devicelab test runner, which has had the corresponding flag local-engine-host added in https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/command/test.dart#L40.

I don't know why these have not started failing since this CL landed.  It may be that no CI builders pass the LOCAL_ENGINE flag to these drones any more, since engine testing has migrated to engine_v2 which does not use local-engine.  If this is the case, then the support for LOCAL_ENGINE should be removed from the recipe, instead of adding support for LOCAL_ENGINE_HOST and providing it.

**Pull request merged**
