### PR TITLE
Use kDebugMode in error_widget.0.dart example

### LINKED ISSUE #97479: update ` examples/api/lib/widgets/framework/error_widget.0.dart`  example
flutter has a `bool` cost  `kDebugMode` 
and this example 
https://github.com/flutter/flutter/blob/6e49cce18f26c24027f92dabf903ef51baa43250/examples/api/lib/widgets/framework/error_widget.0.dart

uses `assertion` to run a specific code in debug only 
this works fine but new comers might does not know that `assert`  works only on debug 
using the const (`kDebugMode`) will make it more clear 
since the example is about the error handling not about `assert` use cases

### PR DESCRIPTION
**Pull request by maxzod**
Fixes #97479

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by ZED-Magdy — COMMENTED** [review]
Yeah I see it's a better approach

**Comment by Hixie** [comment]
@maxzod This looks great, would you mind fixing the import order to be alphabetical? Then we can land it!

**Comment by maxzod** [comment]
> @maxzod This looks great, would you mind fixing the import order to be alphabetical? Then we can land it!

done .👍

**Review by Hixie — APPROVED** [review]
LGTM

**Comment by ditman** [comment]
I think I understand what this review does, but I think this should have a better description of the change; in particular:

> I listed at least one issue that this PR fixes in the description above.

Is checked in the pre-launch checklist, but there's no issue linked (or information about what this does, really).

@maxzod can you provide more context, and maybe an issue? If the fix is maybe too trivial to open an issue in flutter/flutter, can the description be updated to provide said context?

Thanks!

**Comment by Hixie** [comment]
@maxzod also if you wouldn't mind rebasing the change to tip of tree, that should unblock the tests (unfortunately your PR is branched from before a point where we had to change our tokens, so the tests are failing on old tokens).

**Comment by maxzod** [comment]
@Hixie , the branch has the latest changes in the master until this comment 
@ditman , i have opened a issue and listen it in the PR  (#97479)

**Comment by ditman** [comment]
Thanks @maxzod! Note that if you list the PR as "Fixes #ISSUE_NUMBER_OR_LINK", Github will automatically link the issue and this PR, so the issue will get closed when this PR lands! (see [this Github docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), very handy!).

I've done it for this PR (check the description above).

**Comment by ditman** [comment]
> ERROR: One or more tests from rainbowmonkey failed.
> Deleting temporary directory...
> Contact: @Hixie

@Hixie, are the customer_testing-linux tests safe to restart? Maybe this PR needs a merge from master for CI to pass again?

**Comment by maxzod** [comment]
when will this be merged 🤔

**Review by ditman — APPROVED** [review]

**Comment by ditman** [comment]
Apologies @maxzod, I have been busy with other stuff and didn't see this notification. I've approved your change, and merged this with the latest `master`.

I've also applied the 'waiting for tree to go green' tag, so it lands as soon as all tests pass (and flutter/flutter is ready to accept new changes!)

Thanks for your contribution, keep them coming!

**Comment by ditman** [comment]
Hey guys, this very innocent-looking PR is breaking several customer tests: `rfw`, `flutter_svg` and `rainbowmonkey`... How come?

(Pinging owners: @goderbauer, @Hixie, @dnfield (?))

**Comment by goderbauer** [comment]
This PR probably just needs to be rebased to the current master to make those errors go away.

**Comment by ditman** [comment]
> This PR probably just needs to be rebased to the current master to make those errors go away.

@goderbauer tried that already, this branch is at the tip of `master`, if git is to be believed.

**Comment by ditman** [comment]
@dnfield might have a point here: "Make sure to explicitly use `git rebase`, **not `git merge`**, since rebase is the only way to get the script to find the right branch point to pick for updates to customer testing"

**Comment by ditman** [comment]
(Rebasing and push-forcing the branch)

**Pull request merged**
