### PR TITLE
Rename "slow mode" to be "debug mode"

### PR DESCRIPTION
**Pull request by tvolkert**
This moves toward more consistency in our messaging. Apps are
launched using --debug, so the banner will reflect the build
mode.

### CODE REVIEW

**Comment by wmleler** [comment]
Is there documentation that needs to be updated too?

**Comment by tvolkert** [comment]
> Is there documentation that needs to be updated too?

I think I caught all the instances in `flutter/flutter` - it's likely there are places on the website (including screenshots) that need to be updated in a separate PR.

**Comment by Hixie** [comment]
Can you include a screenshot here of what it looks like? I recall, now that I'm looking at this patch, that the reason I'd used "SLOW MODE" was that "DEBUG MODE" didn't fit on the device I was testing on.

**Comment by tvolkert** [comment]
__iPhone 8__
debug-mode-iphone-8

__iPhone X__
debug-mode-iphone-x

__Pixel 2 XL__
debug-mode-pixel-2-xl

**Comment by wmleler** [comment]
I think that -- especially once we allow users to click on it and see a
menu with further explanation and options -- that it would be fine -- in
fact preferable -- to just say "DEBUG" and leave off the "MODE".

**Comment by Hixie** [comment]
Sure, we can try just "DEBUG".

**Comment by tvolkert** [comment]
Updated:

__iPhone 8__
debug-mode-iphone-8

__iPhone X__
debug-mode-iphone-x

__Pixel 2 XL__
debug-mode-pixel-2-xl

**Pull request merged**
