### PR TITLE
Keep `dirty` manipulations private to `Element` base class

### PR DESCRIPTION
**Pull request by goderbauer**
I tried to create a custom Element that was a direct subclass of `Element` outside of the framework and it was impossible to implement this right because I couldn't properly set/unset the `dirty` flag when necessary. Element subclasses in the framework directly manipulate the private `Element._dirty` field, but subclasses outside of `framework.dart` don't have this option. This change keeps setting `Element._dirty` private to the `Element` class to give subclasses outside of the framework a fair chance. This is archived by:

* Resetting `_dirty` in the default implementation of `Element.performRebuild`. Subclasses are now expected to call this super implementation to reset the flag.
* Adding a `force` parameter to the `Element.rebuild` method to force rebuilding even if the `Element` isn't dirty. This is convenient to call from implementations of `update` in subclasses.

I don't expect this to be a breaking change. Elements implemented outside the framework, who are not calling `super.performRebuild` already, are essentially broken because they can't reset the `dirty` flag properly. Therefore, I am not expecting any implementations out there that override `performRebuild` without already calling super. Furthermore, the addition of a new parameter to `rebuild` shouldn't break any subclasses since subclasses should be overriding `performRebuild` instead and that signature is unchanged. (However, I did find one class in google3 that overrides `rebuild` directly and that override needs to be updated to include the newly added `force` parameter.)

Alternatives considered:
* Instead of adding `force` as a parameter to `rebuild`, add a new `forceRebuild` method. While this would be non-breaking in google3, it would deepen the call stack if we want to call into `forceRebuild` from `rebuild` to re-use code.
* Instead of introducing a new force rebuild functionality, have the base implementation of `Element.update` set the dirty flag to true so subclasses can call the regular `rebuild` method in their `update` method (since the element is now dirty, rebuild will actually do the rebuilding work). While this would work for all Element subclasses implemented in the framework, this would force every Element to always rebuild in `update` to clear the dirty flag. Conceptually, this seems incorrect as there could in theory be updates that don't require a rebuild because the update is essentially a no-op.
* Instead of having `Element.performRebuild` reset the dirty flag, provide a specific API to mark an Element as clean again (i.e. `Element.markAsClean()`). I am a little hesitant to give Element more API surface and adding that extra API feels easier to miss-use then having `performRebuild` clear the flag.

### CODE REVIEW

**Comment by goderbauer** [comment]
Looks like a GlobalKey test in `test/widgets/framework_test.dart` is failing unexpectedly. Need to investigate...

**Comment by goderbauer** [comment]
@Hixie Curious to hear what you think about this or whether you have another suggestion for addressing this.

**Comment by goderbauer** [comment]
Global presubmit in google (with that one fix mentioned in the PR description) came back green, g3fix for that fix is posted in cl/467248749.

**Review by Hixie — APPROVED** [review]
LGTM

**Comment by gspencergoog** [comment]
I *think* this broke the build by causing an integration test to time out.

The test that hangs is here:
https://github.com/flutter/flutter/blob/dce82f7e2179b785327ae6da342ec66c7b1fdd11/packages/flutter_tools/test/integration.shard/break_on_framework_exceptions_test.dart#L674

I'm assuming that this is causing the hang because of some change in the rebuild code that the integration test is testing.

I'm going to revert this to green the build. (I'm gardener this week)

**Pull request merged**
