### PR TITLE
Upgrade quiver to 0.28.1 in flutter_test to fix usage of Maps

### PR DESCRIPTION
**Pull request by pulyaevskiy**
Running tests when on current master channel produces following error:

```shell
⋊> flutter test
00:04 +0: loading /Users/anatoly/Projects/memspace/test/happy_path_test.dart                                                              compiler message: file:///Users/anatoly/.pub-cache/hosted/pub.dartlang.org/quiver-0.28.0/lib/src/collection/lru_map.dart:264:24: Error: Getter not found: 'Maps'.
compiler message:   String toString() => Maps.mapToString(this);
compiler message:                        ^^^^
compiler message: file:///Users/anatoly/.pub-cache/hosted/pub.dartlang.org/quiver-0.28.0/lib/src/collection/lru_map.dart:264:24: Error: The getter 'Maps' isn't defined for the class 'quiver.collection::LinkedLruHashMap<quiver.collection::LinkedLruHashMap::K, quiver.collection::LinkedLruHashMap::V>'.
compiler message: Try correcting the name to the name of an existing getter, or defining a getter or field named 'Maps'.
compiler message:   String toString() => Maps.mapToString(this);
compiler message:                        ^
```

Though the process still exits with `0`.

### CODE REVIEW

**Comment by Hixie** [comment]
to update our dependencies we have to run `flutter update-packages --force-upgrade`.

It's weird that this would just break though. If `flutter test` didn't work, surely the tree would be red?

**Comment by pulyaevskiy** [comment]
> It's weird that this would just break though. If flutter test didn't work, surely the tree would be red?

Looks like this compile error is not treated as "fatal" by Dart VM and it keeps running, so tests are actually executed successfully.

> to update our dependencies we have to run flutter update-packages --force-upgrade.

I just ran it and got a fairly big diff for everything with mostly updates in:

```
pub_semver: 1.3.3
quiver: 0.29.0+1
test: 0.12.33
```

Should I push those changes?

**Comment by Hixie** [comment]
Yup.

**Comment by pulyaevskiy** [comment]
CI looks happy now!

**Review by tvolkert — APPROVED** [review]
Thanks!

**Pull request merged**
