### PR TITLE
[flutter_releases] Upgrade dwds to 12.1.1

### PR DESCRIPTION
**Pull request by christopherfujino**
Cherrypick of the fix for #101224 on the 2.13 release branch.

Fixes https://github.com/flutter/flutter/issues/101547

### CODE REVIEW

**Review by itsjustkevin — APPROVED** [review]

**Review by annagrin — APPROVED** [review]
LGTM!

**Comment by CaseyHillers** [comment]
@christopherfujino can we land this?

**Comment by christopherfujino** [comment]
> @christopherfujino can we land this?

Nothing blocking on my end, I'm good if @itsjustkevin is.

**Comment by CaseyHillers** [comment]
Merging with pending checks as this already went green.

**Pull request merged**
