### PR TITLE
Fix SliverGridRegularTileLayout.computeMaxScrollOffset for 0 children

### LINKED ISSUE #59663: `SliverGrid` with zero childCount throws `The "scrollExtent" is negative.`
## Code to Reproduce

```
GridView.builder(
        shrinkWrap: true,
        physics: NeverScrollableScrollPhysics(),
        padding: EdgeInsets.only(top: 15),
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 1,
          mainAxisSpacing: 10,
          childAspectRatio: 2.1,
        ),
        itemCount: 0,
        itemBuilder: (context, index) {
          return getWidget(index);
        })
```

The itemCount parameter is, of course, dynamic, and in the rare situation that its set to 0, and the mainAxisSpacing is also defined, it throws an exception.

The exception doesn't occur if I remove the mainAxisSpacing value, OR if I increase the itemCount to something greater than 0.

**Exception:** 
```
flutter: The following assertion was thrown during performLayout():
flutter: SliverGeometry is not valid: The "scrollExtent" is negative.
flutter: The RenderSliver that returned the offending geometry was: RenderSliverGrid#fe95d relayoutBoundary=up14 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   creator: SliverGrid ← SliverPadding ← ShrinkWrappingViewport ← IgnorePointer-[GlobalKey#fd570] ←
flutter:     Semantics ← _PointerListener ← Listener ← _GestureSemantics ←
flutter:     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#af9cf] ← _PointerListener ← Listener
flutter:     ← _ScrollableScope ← ⋯
flutter:   parentData: paintOffset=Offset(0.0, 15.0) (can use size)
flutter:   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
flutter:     scrollOffset: 0.0, remainingPaintExtent: Infinity, crossAxisExtent: 384.0, crossAxisDirection:
flutter:     AxisDirection.right, viewportMainAxisExtent: Infinity, remainingCacheExtent: Infinity,
flutter:     cacheOrigin: 0.0)
flutter:   geometry: SliverGeometry(scrollExtent: -10.0, hidden, maxPaintExtent: -10.0)
flutter:   no children current live
flutter:
flutter: The relevant error-causing widget was:
flutter:   GridView
```

Side note: The widget tree looks like this: CustomScrollView -> SliverList -> Column -> GridView.builder

Flutter (Channel master, 1.18.0-10.0.pre)
Dart version 2.9.0 (build 2.9.0-3.0.dev a69cb6d700)

### PR DESCRIPTION
**Pull request by Piinks**
Fixes https://github.com/flutter/flutter/issues/59663

SliverGridRegularTileLayout.computeMaxScrollOffset did not account for a child count of 0.
This would either produce a crash or report the wrong value.

---

```dart
SliverGrid.builder(
  itemCount: 0,
  itemBuilder: (_, __) => Container(),
  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
    crossAxisCount: 1,
    mainAxisSpacing: 10,
    childAspectRatio: 2.1,
  ),
),
```

This case would  cause a crash from a negative scroll extent. 💀 

```dart
SliverGrid.builder(
  itemCount: 0,
  itemBuilder: (_, __) => Container(),
  gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(
    maxCrossAxisExtent: 30,
  ),
),
```

This would just report the wrong value > 0. 🙃 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by nehaaaa6** [comment]
SliverGrid.builder(
  itemCount: 0,
  itemBuilder: (_, ) => Container(),
  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
    crossAxisCount: 1,
    mainAxisSpacing: 10,
    childAspectRatio: 2.1,
  ),
  // Add a shrinkWrap property to avoid the negative scroll extent issue
  shrinkWrap: true,
  // Add an empty child to prevent the child count from being 0
  children: [ ],
),

**Comment by nehaaaa6** [comment]
To fix this issue, you can add a check to ensure that the child count is greater than 0 before calling 'computeMaxScrollOffset'.
By adding an empty child and setting 'shrinkWrap' to true, you can prevent the child count from being 0 and avoid the negative scroll extent issue. This should resolve the error and allow the merge to proceed

**Comment by Piinks** [comment]
Hi @nehaaaa6 thanks for the feedback. I feel that SliverGridRegularTileLayout should handle this since anyone can instantiate and use this to create tile layouts. It should definitely handle the case for 0. :)

**Review by thkim1011 — APPROVED** [review]
LGTM!

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
