### PR TITLE
Add Flutter Console for Windows

### PR DESCRIPTION
**Pull request by goderbauer**
Just download a Flutter ZIP bundle, unzip, and double-click on `flutter_console.bat` to get started. No PATH modifications required.

flutter_console

/cc @mit-mit @gspencergoog

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by Hixie** [comment]
Nice!

**Comment by mit-mit** [comment]
Very cool indeed!

**Comment by zanderso** [comment]
FYI @jonahwilliams

**Pull request merged**
