### PR TITLE
Avoid calling `cancel` on `AnsiSpinner` more than once when building for iOS

### LINKED ISSUE #26812: Cannot build app ios in release
Hi Guys, 

I cannot build after last upgrade flutter. The my locale situation is

 
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.1.10-pre.135, on Mac OS X 10.14.2 18C54, locale en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (5 available)

• No issues found!
```

and after the command and the response for release command build on ios

```
flutter build ios                     
Building com.pjonny84.babyLearnWithGame for device (ios-rele                                                                                             ├─Building Dart code...                                     6.8s                                                                                       Unhandled exception:                                                                                                
NoSuchMethodError: The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      AnsiSpinner.finish (package:flutter_tools/src/base/logger.dart:652:11)
#2      Status.cancel (package:flutter_tools/src/base/logger.dart:492:5)
#3      AnsiStatus.cancel (package:flutter_tools/src/base/logger.dart:731:11)
#4      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:470:30)
<asynchronous suspension>
#5      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:478:37)
<asynchronous suspension>
#6      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:478:37)
<asynchronous suspension>
#7      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:482:29)
<asynchronous suspension>
#8      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:78:43)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:551:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#16     Future._complete (dart:async/future_impl.dart:473:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)


```

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/26812

I'm not sure how to write a test for this, since there are asserts sprinkled througout that make a test fail.  I was trying

```dart

      testUsingContext('AnsiSpinner can be canceled without starting', () {
        final AnsiSpinner ansiSpinner = AnsiSpinner(timeout: const Duration(milliseconds: 10));
        ansiSpinner.cancel();
      });
```

### CODE REVIEW

**Review by Hixie — COMMENTED** [review]
How does the timer end up being null at the end? That sounds like a contact violation.

**Comment by dnfield** [comment]
We have several devicelab tests that __should__ have caught this.  Not really sure why they didn't fail.

**Comment by jbg** [comment]
This patch doesn't prevent the crash for me, but results in a slightly different exception.

```
Unhandled exception:
NoSuchMethodError: The method 'cancel' was called on null.
Receiver: null
Tried calling: cancel()
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      AnsiSpinner.finish (package:flutter_tools/src/base/logger.dart:652:11)
#2      Status.stop (package:flutter_tools/src/base/logger.dart:487:5)
#3      AnsiStatus.stop (package:flutter_tools/src/base/logger.dart:724:11)
#4      buildXcodeProject.listenToScriptOutputLine (package:flutter_tools/src/ios/mac.dart:462:27)
<asynchronous suspension>
[snip]
```

(note it's called from `Status.stop` rather than `Status.cancel` as before)

I patched it like this to get back to work, but I don't know if it's the most desirable way to do it:

```patch
diff --git a/packages/flutter_tools/lib/src/base/logger.dart b/packages/flutter_tools/lib/src/base/logger.dart
index 06b78075b..022ce669b 100644
--- a/packages/flutter_tools/lib/src/base/logger.dart
+++ b/packages/flutter_tools/lib/src/base/logger.dart
@@ -649,7 +649,7 @@ class AnsiSpinner extends Status {
   void finish() {
     assert(timer != null);
     assert(timer.isActive);
-    timer.cancel();
+    timer?.cancel();
     timer = null;
     _clearSpinner();
     super.finish();
```

**Comment by dnfield** [comment]
@jbg  can you try this again with this patch?

/cc @DanTup

**Comment by a396901990** [comment]
waiting this fix for 2 days. does anyone can merge it. thanks~

**Comment by Hixie** [comment]
LGTM, but boy, that whole function needs some serious refactoring.

**Comment by Hixie** [comment]
any luck finding out why the device lab tests didn't catch this?

**Comment by dnfield** [comment]
I'm not sure, I'm guessing it's some environmental issue where the output isn't being tracked properly or it's coming through differently for some reason.  I'll try to look into that some more.

**Comment by dnfield** [comment]
Opened #26877 to track follow up on this

**Pull request merged**
