### PR TITLE
add a target for android-x64

### PR DESCRIPTION
**Pull request by devoncarew**
@jason-simmons, add an enum for `android-x64`. It sounds like you're working on android emulator x86 / x64 support. This plumbs an android emulator constant through the tools.

### CODE REVIEW

**Comment by devoncarew** [comment]
This location might need to be updated as well: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/build_apk.dart#L286

**Comment by jason-simmons** [comment]
LGTM

That line in build_apk.dart will need to select "x86_64" instead of "armeabi-v7a" for an android-x64 build.  The libsky_shell.so path in _findApkComponents will similarly need to be updated.

**Comment by eseidelGoogle** [comment]
This is relevant to #490 and #284

**Comment by devoncarew** [comment]
OK, updated refs from `armeabi-v7a` to `x86_64`. I do see:

```
E/AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.example.flutter_sunflower-2/lib/x86/libsky_shell.so" is 64-bit instead of 32-bit
E/AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
E/AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
E/AndroidRuntime: 	at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:250)
```

when running, but at least we're trying to send x86 libs through, instead of arm ones.

**Comment by jason-simmons** [comment]
LGTM

For testing, make sure that your emulator is running a 64-bit system image.

Eventually we'll need flags for 32-bit versus 64-bit x86

**Comment by eseidelGoogle** [comment]
Huzzah!  Yet another step closer!  Thank you both!

**Comment by devoncarew** [comment]
> For testing, make sure that your emulator is running a 64-bit system image.

Ah yeah, looks like I was running w/ a 32 bit image. I get a segfault with the 64 bit image, but it does get further along.

**Pull request merged**
