### PR TITLE
Guard against usage after async callbacks in RenderAndroidView, unregister listener

### PR DESCRIPTION
**Pull request by dnfield**
xref b/186978412

When this code was written, render object disposal wasn't a thing. When I implemented that, I didn't realize there were async methods being used in this render object.

The test in this patch is basically a clone of an existing test, but it disposes the RO before completing some of the async operations. Without the changes in the implementation the test fails.

### CODE REVIEW

**Review by stuartmorgan-g — COMMENTED** [review]
Looks like a mock in another test needs updating, but otherwise LGTM. Thanks for investigating this!

We should definitely cherry-pick this to `beta` (and maybe even `stable`?).

**Review by stuartmorgan-g — APPROVED** [review]

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Is the flutter_plugins failure a known issue? Looks like mockito deprecated something that plugins is using?

**Comment by goderbauer** [comment]
> 
Is the flutter_plugins failure a known issue? Looks like mockito deprecated something that plugins is using?

/cc @Piinks Is this the same issue that turned the tree red?

**Comment by Piinks** [comment]
Yeah it is the same failure that has the tree red

**Pull request merged**
