### PR TITLE
Skip "newly added code executes during hot restart - canvaskit"

### PR DESCRIPTION
**Pull request by zanderso**
https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20web_tool_tests/2880/overview

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by zanderso** [comment]
@jonahwilliams is there a better issue to link to for the canvaskit download issue?

**Comment by zanderso** [comment]
Maybe @yjbanov would also know

**Comment by zanderso** [comment]
Landing on red to green the tree.

**Pull request merged**
