### PR TITLE
Fix for floating pinned persistent header

### PR DESCRIPTION
**Pull request by nonameden**
SliverGeometry in updateGeometry() method does not respect minExtent from Sliver Delegate. Fix for #11222

### CODE REVIEW

**Comment by nonameden** [comment]
I signed it!

**Comment by nonameden** [comment]
I signed it!

**Comment by nonameden** [comment]
again

**Comment by eseidelGoogle** [comment]
I believe to un-grump the CLA bot you'll need to force-push a new commit with the email address in the commit author field matching one that you've signed the CLA with. :(

Something like this:
https://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit

**Comment by Hixie** [comment]
This needs detailed comprehensive tests.

**Comment by nonameden** [comment]
@Hixie ok, will have a look into testing. @eseidelGoogle I changed author in commit (my second commit in PR) but looks like I need to do PR again to pass CLA bot =(

**Comment by HansMuller** [comment]
This change should be applied to both floating/pinned and just pinned headers.

**Comment by Hixie** [comment]
To clarify by testing I meant automated unit tests.

**Comment by Hixie** [comment]
@nonameden Are you planning on doing the tests or should we take this PR over? (either way is fine, just trying to decide if we should leave the PR open in the meantime)

**Comment by nonameden** [comment]
@Hixie sorry, it was busy week at my job, I was planning to do it next week.

**Comment by Hixie** [comment]
Sounds good! No rush!

**Comment by Hixie** [comment]
@nonameden I'm going to take over this patch and write a test for it. Thanks for your contribution!

**Comment by nonameden** [comment]
Thank you @Hixie 
I've played with test, but almost gave up with position detection for my slivers

Here the gist with test: https://gist.github.com/nonameden/5ac7b8c129e8ab9ede17fef2f8f0106b

**Comment by Hixie** [comment]
Thanks, you can see what I came up with here: https://github.com/flutter/flutter/pull/11996
I found that I didn't need to change the `scrollExtent` line, can you elaborate (e.g. comment on that PR) about what doesn't work if that line isn't changed?
Also if there's anything else you think I should test don't hesitate to let me know on that PR.

**Pull request closed without merging**
