### PR TITLE
Revert "Fix computeMinIntrinsicHeight in _RenderDecoration"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#87404

Reverting for b/198862719

### CODE REVIEW

**Review by xster — APPROVED** [review]

**Review by justinmc — APPROVED** [review]
LGTM 👍

**Comment by zanderso** [comment]
Landing revert on red to unblock the roll

**Comment by zanderso** [comment]
@smitsk

**Comment by justinmc** [comment]
@smitsk We should try to reland https://github.com/flutter/flutter/pull/87404 by unreverting this PR.  I'm going to try to reproduce a wrapping obscured field that caused one of the Google test failures.  Not sure if it's a problem with the PR or just something that we need to change internally.

**Comment by justinmc** [comment]
@smitsk I was able to reproduce the problem.  Is this change intended?

| Before #87404 | With #87404 |
| -- | -- |
| Screen Shot 2021-09-08 at 3 38 52 PM | Screen Shot 2021-09-08 at 3 38 41 PM |

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Flutter Demo'),
        ),
        body: Center(
          child: Container(
            width: 640.0,
            child: TextField(
              textAlign: TextAlign.left,
              style: DefaultTextStyle.of(context).style.copyWith(fontSize: 120.0),
              autofocus: true,
              maxLines: 1,
              decoration: InputDecoration(
                border: OutlineInputBorder(),
                fillColor: Colors.transparent,
                floatingLabelBehavior: FloatingLabelBehavior.never,
                contentPadding: EdgeInsets.all(20.0),
                prefixText: '•••• •••• ••',
              ),
              keyboardType: TextInputType.number,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by smitsk** [comment]
@justinmc 
I think this is expected. We discussed that when `prefix` and `postfix` are laid out with full width (before #87404) then they are outside the container. If we try to change left content padding to greater value, we will see something like this:

After #87404 we will see (prefix is inside the container horizontally):

In your example (with #87404) `prefix` doesn't ignore contentPadding and text after second space is on second line.

I'm not sure about bottom overflow, but if in your example we will change contentPadding to
`contentPadding: EdgeInsets.symmetric(horizontal: 20.0)` 
and add few symbols then we can have the same (it's before #87404):


I think this is another problem. Perhaps I could look into this and fix in a new PR in the future.

**Pull request merged**
