### PR TITLE
Fix some indentation

### PR DESCRIPTION
**Pull request by asashour**
Fix some code indentation.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by shihaohong — APPROVED** [review]
LGTM

**Comment by shihaohong** [comment]
The Google testing failure doesn't seem related to your change. However, you'll need to rebase or merge your branch with master to get the Cirrus presubmit checks to pass

**Comment by asashour** [comment]
Thanks for advice, I didn't know that.

**Comment by zanderso** [comment]
@asashour I'm wondering if you used any sort of automated tooling to discover the need for these fixes.

**Comment by asashour** [comment]
Indeed, I wrote a small program that checks the indentation of consecutive lines.

I believe there is a long term plan to automatically handle this, but it is a small start.

**Pull request merged**
