### PR TITLE
Add find.descendant API to support find descendants of an element by passing the current element finder and the finder of descendant.

### PR DESCRIPTION
**Pull request by zhenqiu1101**
A fix related to #7643.

Thanks for reviewing.

### CODE REVIEW

**Comment by Hixie** [comment]
Yay, CLA bot is happy.

LGTM. Please feel free to push the "squash and merge" button once Travis goes green, or let me know if you don't see that button and I can do it for you.

**Comment by zhenqiu1101** [comment]
I can't see the button, I guess because I don't have "write access".

**Comment by Hixie** [comment]
Ok, I landed it for you! Thanks!

**Comment by zhenqiu1101** [comment]
Thank you!

**Pull request merged**
