### PR TITLE
Added default TextStyle() to TextSpan constructor

### LINKED ISSUE #66196: RichText textScaleFactor is ignored if the child TextSpan doesn't contain a TextStyle
## Steps to Reproduce
1. Run this dartpad [code sample](https://dartpad.dartlang.org/b65e7edd460d38507ff39162021030be)

**Expected results:** 
[RichText](https://api.flutter.dev/flutter/widgets/RichText-class.html) [textScaleFactor property](https://api.flutter.dev/flutter/widgets/RichText/textScaleFactor.html) should apply to his child [TextSpan](https://api.flutter.dev/flutter/painting/TextSpan-class.html)

**Actual results:** 
[RichText](https://api.flutter.dev/flutter/widgets/RichText-class.html) [textScaleFactor property](https://api.flutter.dev/flutter/widgets/RichText/textScaleFactor.html) doesn't apply to his child [TextSpan](https://api.flutter.dev/flutter/painting/TextSpan-class.html) unless [TextStyle](https://api.flutter.dev/flutter/painting/TextStyle-class.html) is declared
(try un-commenting the code as described in the sample)

I have no relevant logs to provide

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.22.0-10.0.pre.269, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-10.0.pre.269 at
      /home/francesco/development/flutter_master
    • Framework revision 51fa704642 (71 minutes ago), 2020-09-19 11:27:04 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/lib/Android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/lib/Android
    • ANDROID_SDK_ROOT = /usr/lib/Android
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.102

! Doctor found issues in 1 category.
```

</details>

please consider this [PR](https://github.com/flutter/flutter/pull/66197) to fix the issue

### PR DESCRIPTION
**Pull request by iapicca**
## Description

Added default TextStyle() to TextSpan constructor ([here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/text_span.dart#L72)) 
<details>
<summary>before</summary>

```dart
  const TextSpan({
    this.text,
    this.children,
    TextStyle? style,
    this.recognizer,
    this.semanticsLabel,
  }) : super(style: style);
```

</details>
<details>
<summary>after</summary>

```dart
  const TextSpan({
    this.text,
    this.children,
    TextStyle? style = const TextStyle(),
    this.recognizer,
    this.semanticsLabel,
  }) : super(style: style);
```

</details>

## Related Issues

Fixes https://github.com/flutter/flutter/issues/66196

## Tests

[edit] please see this [comment](https://github.com/flutter/flutter/pull/66197#issuecomment-695840761)

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

### CODE REVIEW

**Comment by PixelToast** [comment]
Good catch, thanks for making a PR!

This definitely needs tests, could you add one?

**Comment by iapicca** [comment]
I've added 2 tests [here](https://github.com/flutter/flutter/blob/master/packages/flutter/test/painting/text_span_test.dart#L247)
#
1. verifies that a `TextSpan()` 's `style` by default is `TextStyle()`

```dart
  test('TextSpan should have non-null default TextStyle()', () {
    const TextSpan textSpan = TextSpan();
    expect(textSpan.style, const TextStyle());
  });
```
#
2. verifies that `textScaleFactor` affect `TextSpan()` when painted

```dart
test('TextSpan in TextPainter should scale according to textScaleFactor', () {
    const TextSpan textSpan = TextSpan(text: ' ');
    final TextPainter painterScaleOne = TextPainter(
      text: textSpan,
      textScaleFactor: 1,
      textDirection: TextDirection.ltr,
      maxLines: 1,
    );
    final TextPainter painterScaleDouble = TextPainter(
      text: textSpan,
      textScaleFactor: 2,
      textDirection: TextDirection.ltr,
      maxLines: 1,
    );
    painterScaleOne.layout();
    painterScaleDouble.layout();
    expect(painterScaleOne.size.width < painterScaleDouble.size.width, true);
  });
```

with the latest master
<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.22.0-10.0.pre.269, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (4 available)

! Doctor found issues in 1 category.
```
</details>

 this [code](https://dartpad.dartlang.org/7079332b9acaae78a5335969586877a6) returns this output
```console
withTextStyle: true
withoutTextStyle: false
```

**Comment by goderbauer** [comment]
Looks like this is making some existing tests fail. Can you take a look at those.

It's also not clear to me that just providing a default value is the right fix here. Did you investigate why the TestPainter is ignoring the scale factor when no style is provided?

/cc @GaryQian

**Comment by GaryQian** [comment]
Text widgets including TextSpan should inherit TextStyle from the parent TextSpan, if available, and then inherit from the theme. Setting a default here breaks this inheritance.

Ignoring of scale should be resolved in a different way.

**Comment by GaryQian** [comment]
I believe the problem lies at text_painter.dart:411 where we check for _text.style being null, and then fail to pass textScaleFactor.

**Comment by GaryQian** [comment]
https://github.com/flutter/flutter/pull/66375 Fixes the defaulting problem without setting a default TextStyle for all TextSpans. Thanks for your PR and narrowing down the problem area!

**Comment by Piinks** [comment]
@GaryQian do you mean this change should be closed to defer to #66375?

**Comment by GaryQian** [comment]
Yes, I'll go ahead and close this now.

**Pull request closed without merging**
