### PR TITLE
Add secondary tap capabilities to TableRowInkWell

### LINKED ISSUE #116643: DataTable: missing secondary tap callback
## Use case

Showing context menus on desktop platforms.

Currently, `DataCell` has `onTap`, `onTapDown`, `onTapCancel`, `onLongPress`, and `onDoubleTap` whereas `DataRow` only has a `onLongPress` gesture callback.

## Proposal

Add `onSecondaryTap(Down)` to both `DataRow` and `DataCell` for showing row- and cell-specific context menus.

### PR DESCRIPTION
**Pull request by justinmc**
Recently, https://github.com/flutter/flutter/pull/119058 added secondary tap support to InkWell.  This PR adds it to TableRowInkWell, too.

CC @chinmoy12c 

This was noticed in: https://github.com/maxim-saplin/data_table_2/pull/176#discussion_r1140956138

Closes https://github.com/flutter/flutter/issues/116643

### CODE REVIEW

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

**Review by Piinks — APPROVED** [review]
LGTM, but lookin at the super class the docs are a bit confusing. I'll file a separate issue on that. :)

**Comment by Piinks** [comment]
Filed https://github.com/flutter/flutter/issues/123049. I feel silly having approved the PR that added this, but in retrospect, the secondary button can be confusing if you do not already know about it. :)

**Comment by justinmc** [comment]
Yes, thanks!

**Pull request merged**
