### PR TITLE
Always run the flutter tool in checked mode.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by abarth** [comment]
Maybe we should do this on Travis?  It seems wrong to run in checked mode in production.

**Comment by Hixie** [comment]
I don't think we should keep this on forever, but we are regularly failing to catch problems because of not using checked mode around the team. Case in point, Travis failed this. Looking into it now...

**Comment by Hixie** [comment]
Fixes https://github.com/flutter/flutter/issues/4807

**Comment by Hixie** [comment]
Blocked on https://github.com/dart-lang/sdk/issues/28519

**Comment by Hixie** [comment]
Closing until https://github.com/dart-lang/sdk/issues/28519 is fixed.

**Pull request closed without merging**
