### PR TITLE
Roll engine f2f8c342be32..e5091a8ca264 (36 commits)

### PR DESCRIPTION
**Pull request by engine-flutter-autoroll**
https://github.com/flutter/engine/compare/f2f8c342be32...e5091a8ca264

git log f2f8c342be32..e5091a8ca264 --first-parent --oneline
2020-02-21 gw280@google.com Enable Vulkan-related shell unittests on Fuchsia (flutter/engine#16718)
2020-02-21 nurhan@google.com [web] Running safari tests on LUCI (flutter/engine#16715)
2020-02-21 skia-flutter-autoroll@skia.org Roll src/third_party/skia 392846665c40..bf5cb0f539e7 (1 commits) (flutter/engine#16730)
2020-02-21 skia-flutter-autoroll@skia.org Roll src/third_party/skia 77521d9e06e8..392846665c40 (1 commits) (flutter/engine#16729)
2020-02-21 skia-flutter-autoroll@skia.org Roll src/third_party/dart 6ef9131d82c4..5829fc7829d5 (3 commits) (flutter/engine#16728)
2020-02-21 skia-flutter-autoroll@skia.org Roll fuchsia/sdk/core/linux-amd64 from CZTpy... to -u-iU... (flutter/engine#16727)
2020-02-21 skia-flutter-autoroll@skia.org Roll fuchsia/sdk/core/mac-amd64 from 78ZcV... to iYYAH... (flutter/engine#16726)
2020-02-21 skia-flutter-autoroll@skia.org Roll src/third_party/skia 3ffa7af75301..77521d9e06e8 (2 commits) (flutter/engine#16725)
2020-02-21 skia-flutter-autoroll@skia.org Roll src/third_party/dart fd20c7b92bb8..6ef9131d82c4 (7 commits) (flutter/engine#16723)
2020-02-21 skia-flutter-autoroll@skia.org Roll src/third_party/skia df283d01cabb..3ffa7af75301 (1 commits) (flutter/engine#16722)
2020-02-21 dnfield@google.com Refactor of ClaimDartHandle -> AssociateWithDartWrapper (flutter/engine#16720)
2020-02-21 skia-flutter-autoroll@skia.org Roll src/third_party/skia 706851dc99d9..df283d01cabb (3 commits) (flutter/engine#16719)
2020-02-21 skia-flutter-autoroll@skia.org Roll src/third_party/dart 81d4cc6bc99a..fd20c7b92bb8 (31 commits) (flutter/engine#16716)
2020-02-21 dnfield@google.com Reland "Remove usage of Dart_AllocateWithNativeFields" (flutter/engine#16713)
2020-02-20 skia-flutter-autoroll@skia.org Roll src/third_party/skia 1d589a578ca4..706851dc99d9 (2 commits) (flutter/engine#16714)
2020-02-20 gw280@google.com Flush the SkCanvas when submitting a frame in ShellTestPlatformViewVulkan::OffscreenSurface (flutter/engine#16717)
2020-02-20 skia-flutter-autoroll@skia.org Roll src/third_party/skia 62076977a0b7..1d589a578ca4 (6 commits) (flutter/engine#16712)
2020-02-20 skia-flutter-autoroll@skia.org Roll src/third_party/skia 9d4e31d6cda5..62076977a0b7 (11 commits) (flutter/engine#16710)
2020-02-20 freiling@google.com [shell tests] Integrate Vulkan with Shell Tests (flutter/engine#16621)
2020-02-20 vsm@google.com opt out dart:ui from nnbd (flutter/engine#16473)
2020-02-20 skia-flutter-autoroll@skia.org Roll fuchsia/sdk/core/linux-amd64 from YPr0t... to CZTpy... (flutter/engine#16708)
2020-02-20 skia-flutter-autoroll@skia.org Roll src/third_party/skia 2c2db2762809..9d4e31d6cda5 (1 commits) (flutter/engine#16707)
2020-02-20 skia-flutter-autoroll@skia.org Roll fuchsia/sdk/core/mac-amd64 from WZgbp... to 78ZcV... (flutter/engine#16706)
2020-02-20 skia-flutter-autoroll@skia.org Roll src/third_party/dart e187e42593e8..81d4cc6bc99a (3 commits) (flutter/engine#16705)
2020-02-20 jmccandless@google.com Fix the newline on some keyboards (flutter/engine#16560)
2020-02-20 kustermann@google.com Enable lazy-async-stacks by-default in all modes (flutter/engine#16556)
2020-02-20 skia-flutter-autoroll@skia.org Roll src/third_party/skia a5097354217b..2c2db2762809 (1 commits) (flutter/engine#16704)
2020-02-20 skia-flutter-autoroll@skia.org Roll src/third_party/skia ed1ff23c2768..a5097354217b (1 commits) (flutter/engine#16703)
2020-02-20 skia-flutter-autoroll@skia.org Roll src/third_party/dart 7469b87b042a..e187e42593e8 (11 commits) (flutter/engine#16702)
2020-02-20 skia-flutter-autoroll@skia.org Roll fuchsia/sdk/core/linux-amd64 from VHyDa... to YPr0t... (flutter/engine#16701)
2020-02-20 skia-flutter-autoroll@skia.org Roll src/third_party/skia 9baef3593c3c..ed1ff23c2768 (5 commits) (flutter/engine#16699)
2020-02-20 skia-flutter-autoroll@skia.org Roll src/third_party/skia 7dfb46e7f397..9baef3593c3c (3 commits) (flutter/engine#16696)
2020-02-19 xster@google.com fix param (flutter/engine#16694)
2020-02-19 skia-flutter-autoroll@skia.org Roll src/third_party/dart 0f141be8bd52..7469b87b042a (9 commits) (flutter/engine#16693)
2020-02-19 skia-flutter-autoroll@skia.org Roll src/third_party/skia c5ff41f2976e..7dfb46e7f397 (20 commits) (flutter/engine#16691)
2020-02-19 skia-flutter-autoroll@skia.org Roll fuchsia/sdk/core/mac-amd64 from _jvYk... to WZgbp... (flutter/engine#16692)

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/flutter-engine-flutter-autoroll
Please CC jsimmons@google.com on the revert to ensure that a human
is aware of the problem.

To report a problem with the AutoRoller itself, please file a bug:
...

### CODE REVIEW

**Comment by dnfield** [comment]
@rmistry - why did the roller pick this commit? One of the builders for it failed, so the artifacts aren't available.

I'm retriggering that engine builfder (failure was a goma flake on windows)

**Comment by rmistry** [comment]
> @rmistry - why did the roller pick this commit? One of the builders for it failed, so the artifacts aren't available.

What was not available?
The roller looks for all of this: https://skia.googlesource.com/buildbot/+/master/autoroll/config/flutter-engine-flutter.json#37

> 
> I'm retriggering that engine builfder (failure was a goma flake on windows)

**Comment by rmistry** [comment]
> > @rmistry - why did the roller pick this commit? One of the builders for it failed, so the artifacts aren't available.
> 
> What was not available?
> The roller looks for all of this: https://skia.googlesource.com/buildbot/+/master/autoroll/config/flutter-engine-flutter.json#37
> 
> > I'm retriggering that engine builfder (failure was a goma flake on windows)

I0221 21:32:54.667764       1 github_repo_manager.go:239] github_repo_manager.go:239 [gcsFileFilter] Found flutter/e5091a8ca2622d44cc2529304590fe724d3e855/android-javadoc.zip
I0221 21:32:54.693416       1 github_repo_manager.go:239] github_repo_manager.go:239 [gcsFileFilter] Found flutter/e5091a8ca2622d44cc2529304590fe724d3e855/dart-sdk-linux-x64.zip
I0221 21:32:54.719389       1 github_repo_manager.go:239] github_repo_manager.go:239 [gcsFileFilter] Found flutter/e5091a8ca2622d44cc2529304590fe724d3e855/dart-sdk-darwin-x64.zip
I0221 21:32:54.738796       1 github_repo_manager.go:239] github_repo_manager.go:239 [gcsFileFilter] Found flutter/e5091a8ca2622d44cc2529304590fe724d3e855/dart-sdk-windows-x64.zip
I0221 21:32:54.758461       1 github_repo_manager.go:239] github_repo_manager.go:239 [gcsFileFilter] Found flutter/e5091a8ca2622d44cc2529304590fe724d3e855/ios-objcdoc.zip
I0221 21:32:54.777116       1 github_repo_manager.go:239] github_repo_manager.go:239 [gcsFileFilter] Found flutter/e5091a8ca2622d44cc2529304590fe724d3e855/ios/artifacts.zip
I0221 21:32:54.795684       1 github_repo_manager.go:239] github_repo_manager.go:239 [gcsFileFilter] Found flutter/e5091a8ca2622d44cc2529304590fe724d3e855/fuchsia/fuchsia.stamp
I0221 21:32:54.795729       1 github_repo_manager.go:248] github_repo_manager.go:248 [gcsFileFilter] Found all [flutter/%s/android-javadoc.zip flutter/%s/dart-sdk-linux-x64.zip flutter/%s/dart-sdk-darwin-x64.zip flutter/%s/dart-sdk-windows-x64.zip flutter/%s/ios-objcdoc.zip flutter/%s/ios/artifacts.zip flutter/%s/fuchsia/fuchsia.stamp] paths for e5091a8ca26422d44cc2529304590fe724d3e855
I0221 21:32:59.860176       1 autoroller.go:564] autoroller.go:564 nextRollRev is: e5091a8ca26422d44cc2529304590fe724d3e855

**Comment by engine-flutter-autoroll** [comment]
Commit queue failed; closing this roll.

**Comment by dnfield** [comment]
Ahhh -we need to add some more files to that list. android-arm-profile/windows-x64.zip was missing, as was the release variant of that and the arm64 variants.

**Comment by rmistry** [comment]
> Ahhh -we need to add some more files to that list. android-arm-profile/windows-x64.zip was missing, as was the release variant of that and the arm64 variants.

Could you explicitly list everything that needs to be added? (I could not tell what the release/arm64 variants mean)

**Comment by dnfield** [comment]
It looks like the artifacts in there are the _last_ artifact to be uploaded by most of the builders - but some are missing.  

If we update the artifacts here, it seems likely that we'll get messed up again at some point when someone adds new artifacts or re-arranges the order.

Can we instead just have the roller check that all of the LUCI builds for the desired revision have completed successfully?

**Comment by dnfield** [comment]
For example, for the commit that was selected, run this RPC:

https://cr-buildbucket.appspot.com/rpcexplorer/services/buildbucket.v2.Builds/SearchBuilds?request={%20%20%20%20%22predicate%22:%20{%20%20%20%20%20%20%20%20%22builder%22:%20{%20%20%20%20%20%20%20%20%20%20%20%20%22project%22:%20%22flutter%22,%20%20%20%20%20%20%20%20%20%20%20%20%22bucket%22:%20%22prod%22%20%20%20%20%20%20%20%20},%20%20%20%20%20%20%20%20%22tags%22:%20[%20%20%20%20%20%20%20%20%20%20%20%20{%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22key%22:%20%22buildset%22,%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22value%22:%20%22commit/git/e5091a8ca26422d44cc2529304590fe724d3e855%22%20%20%20%20%20%20%20%20%20%20%20%20}%20%20%20%20%20%20%20%20]%20%20%20%20}}

And check that all the statuses are `SUCCESS`.

**Comment by dnfield** [comment]
(Alternatively, come up with a predicate that just returns the last buildset where all builds are successful or something)

**Comment by rmistry** [comment]
> It looks like the artifacts in there are the _last_ artifact to be uploaded by most of the builders - but some are missing.

I don't fully follow this.

> 
> If we update the artifacts here, it seems likely that we'll get messed up again at some point when someone adds new artifacts or re-arranges the order.

Yes, adding new artifacts will get messed up again. I do not understand the order part, the roller looks at all locations not the order of them.

> 
> Can we instead just have the roller check that all of the LUCI builds for the desired revision have completed successfully?
> (Alternatively, come up with a predicate that just returns the last buildset where all builds are successful or something)

Yes, a better solution is for the roller to check all the LUCI builds. However this will need a new repo_manager in the generic autoroller code, it is doable but will take some time to get to with the other things on my plate.

If we have a way to write to a single Google storage location *only* when all builds are done then the existing code can easily check for that. Otherwise, in the interim, we will have to keep adding new locations to the config till a way to check luci builds is ready.

**Comment by dnfield** [comment]
No, we fan builds out, and each builder builds whatever artifacts it needs based on the recipe, and it uploads them.

The current list looks to me like someone said "for our current shards, what's the last artifact the builder uploads on a successful run" and added them.  But we now have more shards, and new artifacts.  The ones in that list are not up to date, and it sounds like we'll have to comb through a bunch of places to verify all the artifacts we need - and it will just get out of date again.

**Pull request closed without merging**
