### PR TITLE
Update IML files

### PR DESCRIPTION
**Pull request by abarth**
IntelliJ seems to really want these files to have these changes.

### CODE REVIEW

**Comment by abarth** [comment]
@devoncarew

**Comment by abarth** [comment]
Sorry, this is actually about IML files.  :)

**Comment by devoncarew** [comment]
lgtm!

@alexander-doroshko, I know you've done some work here to minimize diffs. I wonder if there's something we can do make these files more terse and even less prone to scm churn? flutter_tools.iml in particular seems pretty long: https://github.com/flutter/flutter/pull/7835/files#diff-c74c1a5227cd375f425fb06c4fb9ed48

**Comment by alexander-doroshko** [comment]
@devoncarew @abarth As long as we want to support old `packages` symlinks we have to auto-exclude all paths where they may appear. Otherwise, IDE has to index the Universe multiple times.

I think we are 100% safe to make IMLs small and stable as soon as:
- option to generate symlinks is removed from the SDK
- minimal SDK version supported by the IDE is officially increased to be the one from the previous item

We may consider making IMLs smaller without 100% safety if we are ok that for the minority of users who still use symlinks will have to wait for ages on initial indexing.

**Comment by devoncarew** [comment]
I suspect it's not worth introducing some (small) risk , or dramatically slowing down indexing for some users. I'll file an issue on the jetbrains tracker to look at simplification once the min sdk is one that no longer uses symlinks.

**Pull request merged**
