### PR TITLE
Devicelab memory usage test that navigates repeatedly to a screen within Gallery

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by jason-simmons** [comment]
@yjbanov

**Comment by yjbanov** [comment]
What will this benchmark measure in addition to the existing `complex_layout_scroll_perf__memory`? I strongly support more test coverage, but at the same time I'm wary of over-testing because too many tests can weaken the signal. If this test gives us a better signal than `complex_layout_scroll_perf__memory`, perhaps we should remove the other one?

**Comment by yjbanov** [comment]
Also, I may have to scale up the lab to support running more tests.

@sethladd @eseidelGoogle

**Comment by yjbanov** [comment]
I'm guessing this could partially fix #7084?

**Comment by jason-simmons** [comment]
The goal of this scenario is detecting potential leaks in Gallery. (https://github.com/flutter/flutter/issues/7084).

This script starts Gallery and repeats a cycle of navigating to the text fields demo and returning to the home screen.  Ideally the memory stats after the final return to the home screen should be similar to the levels at initial startup.

**Comment by eseidelGoogle** [comment]
We have more devices (and happy to expense more) if you need them @yjbanov.

**Review by yjbanov — APPROVED** [review]
Sounds good. Let's add it to `manifest.yaml` so that the lab picks it up.

**Pull request merged**
