### PR TITLE
Do not cache itemBuilder calls in a GridView

### LINKED ISSUE #61006: SliverMultiboxAdaptorElement (e.g. GridView) retains widgets it shouldn't
Specifically, the `_childWidget`s cache might not ever get cleared if the widget doesn't rebuild, and indefinitely hold on to child widgets even if they exceed the cache extent. This is a serious issue if the widget has any field on it that is expensive to hold, such as a large Uint8List for image or file data. Here's a simple case that is problematic:

```dart
import 'package:flutter/material.dart';

void main() {
  return runApp(
    MaterialApp(
      home: GridView.builder(
        addAutomaticKeepAlives: false,
        cacheExtent: 0,
        itemCount: 300,
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 3,
          mainAxisSpacing: 3,
          crossAxisSpacing: 3,
        ),
        itemBuilder: (BuildContext context, int index) {
          return ExpensiveWidget(child: Text(index.toString()));
        },
      ),
    ),
  );
}

class ExpensiveWidget extends StatelessWidget {
  ExpensiveWidget({
    Key key,
    int size = 1000000,
    @required this.child,
  }) : _expensive = List<int>(size);

  final List<int> _expensive;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return SizedBox(height: 200, width: 200, child: child);
  }
}
```

/cc @chunhtai who is in the blame for this code and might have a quick idea for a fix. I suspect we need to take into acount the cacheExtent to make sure that we don't indefinitely grow the _childWidgets hashmap here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/sliver.dart#L1062

We clear it on performRebuild, but that rebuild might not happen when we want it to. We should probably trim it here: https://github.com/flutter/flutter/blob/2ab509943660c62281e7b48648c06b057e028c65/packages/flutter/lib/src/widgets/sliver.dart#L1136

### PR DESCRIPTION
**Pull request by dnfield**
## Description

Avoid caching the result of the itemBuilder for GridView. This causes problems particularly when the widget being built is expensive to hold in memory, such as when it's a memory image.

Ideally, this shouldn't land until after https://github.com/flutter/flutter/pull/61025 has run through the devicelab to show the improvement in memory usage expected.

This might potentially regress frame performance, but I can't find a benchmark ti should negatively impact. Either way, it's causing OOMs for a customer so it needs to be fixed. If we can determine a memory safe way of doing an LRU cache for this we could try that. However, we generally say that things that build widgets should be fast - I doubt we're really saving much time with this optimization.

/cc @chunhtai @Hixie 

## Related Issues

Fixes https://github.com/flutter/flutter/issues/61006

## Tests

I added the following tests:

Unit test that we call the itemBuilder when scrolling.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by mehmetf** [comment]
>  I doubt we're really saving much time with this optimization.

I would be more comfortable if we validated this claim; either via benchmarks or if that's too hard, by manual testing. Is the performance acceptable with the repro case that the client gave us (200 6M images)? I admit it is highly synthetic but it could give us an idea of what we are losing.

**Comment by dnfield** [comment]
The use case this should help is when you have a GridView and rapidly scroll back and forth, it's caching the result of the itemBuilder function and so doesn't have to keep invoking it.

Anecdotally, I don't notice any significant performance difference with the customer's simplified demo, which I think is fairly close to their real use case. But I'm also testing on relatively recent hardware (iPhone 11, Pixel 4). Is there any chance the customer has any benchmarks for this?

I didn't think transitions perf would be much impacted by this, but it looks like the numbers are better overall:

```
on master: 
    "missed_transition_count": 0,
    "average_frame_build_time_millis": 2.2558806306306307,
    "90th_percentile_frame_build_time_millis": 3.367,
    "99th_percentile_frame_build_time_millis": 22.765,
    "worst_frame_build_time_millis": 63.287,
    "missed_frame_build_budget_count": 15,
    "average_frame_rasterizer_time_millis": 5.261718785151857,
    "90th_percentile_frame_rasterizer_time_millis": 6.276,
    "99th_percentile_frame_rasterizer_time_millis": 21.771,
    "worst_frame_rasterizer_time_millis": 80.495,
    "missed_frame_rasterizer_budget_count": 15,
    "frame_count": 888,
    "frame_rasterizer_count": 889,
    "average_vsync_transitions_missed": 1.1791044776119404,
    "90th_percentile_vsync_transitions_missed": 2.0,
    "99th_percentile_vsync_transitions_missed": 2.0

-========


on grid_memory_widget with master:
    "missed_transition_count": 0,
    "average_frame_build_time_millis": 2.2474882943143832,
    "90th_percentile_frame_build_time_millis": 3.33,
    "99th_percentile_frame_build_time_millis": 22.208,
    "worst_frame_build_time_millis": 41.701,
    "missed_frame_build_budget_count": 12,
    "average_frame_rasterizer_time_millis": 5.14609933035714,
    "90th_percentile_frame_rasterizer_time_millis": 6.636,
    "99th_percentile_frame_rasterizer_time_millis": 19.603,
    "worst_frame_rasterizer_time_millis": 50.042,
    "missed_frame_rasterizer_budget_count": 12,
    "frame_count": 897,
    "frame_rasterizer_count": 896,
    "average_vsync_transitions_missed": 1.1388888888888888,
    "90th_percentile_vsync_transitions_missed": 1.0,
    "99th_percentile_vsync_transitions_missed": 5.0
```

**Review by mehmetf — APPROVED** [review]

**Comment by dnfield** [comment]
Hmm.  Looking at https://github.com/flutter/flutter/commit/59524c697b7904e915b6e7936bf4a6ea3b4b9426, I'm wondering if this change is quite right. @Hixie wdyt?

At any rate, this patch should remove the remaining comment if we're not using it.

It's not clear to me what the failure mode would be here.

**Comment by dnfield** [comment]
I'm going to go ahead with this. I can't come up with a case where this would cause problems, and if we find one we can fix it.

**Pull request merged**
