### PR TITLE
Unpin test

### LINKED ISSUE #140169: Unpin test, test_api and test_core in flutter.
These packages are pinned various test dependencies need to update their mockito constraint to 5.4.4, which accepts test_api v0.7.0.

See discussion: https://discord.com/channels/608014603317936148/1184909649703600248

### PR DESCRIPTION
**Pull request by christopherfujino**
Fixes https://github.com/flutter/flutter/issues/140169

### CODE REVIEW

**Comment by christopherfujino** [comment]
@DanTup @bkonyi @derekxu16 I *think* this is unblocked now, right?

**Comment by derekxu16** [comment]
> @DanTup @bkonyi @derekxu16 I _think_ this is unblocked now, right?

Yes, it is safe to update `package:vm_service`.

**Comment by christopherfujino** [comment]
> Maybe we'll need to roll devtools in flutter/tests?
> 
> ```
> | Because every version of integration_test from sdk depends on vm_service 14.0.0 and devtools_app depends on vm_service ^13.0.0, integration_test from sdk is forbidden.
> | So, because devtools_app depends on integration_test from sdk, version solving failed.
> ERROR: Could not run "flutter pub get" in packages/devtools_app, which was specified as an update directory.
> ```
> 
> https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20customer_testing/68365/overview
> 
> I'll look to update flutter/tests....

Oh actually, devtools hasn't been updated yet. @derekxu16 would you be able to update vm_service in devtools_app, since I think you are also blocked on this?

**Comment by DanTup** [comment]
>  package:devtools_app cannot be updated to accept package:vm_service 14.0.0 until package:integration_test accepts it.

Could DevTools be updated to support 13 + 14? (I don't know how breaking the changes are, so I don't know if that'll work). Otherwise, could DevTools be excluded from customer tests to land this, then updated, then re-added?

**Comment by derekxu16** [comment]
> Could DevTools be updated to support 13 + 14? (I don't know how breaking the changes are, so I don't know if that'll work). Otherwise, could DevTools be excluded from customer tests to land this, then updated, then re-added?

Following the second suggestion would be ideal. A lot of special checks would have to be added to convert between `int`s and `DateTime`s to make DevTools support both `package:vm_service` v13 and v14. Would it be possible to follow the second suggestion, @christopherfujino?

**Comment by christopherfujino** [comment]
> > Could DevTools be updated to support 13 + 14? (I don't know how breaking the changes are, so I don't know if that'll work). Otherwise, could DevTools be excluded from customer tests to land this, then updated, then re-added?
> 
> Following the second suggestion would be ideal. A lot of special checks would have to be added to convert between `int`s and `DateTime`s to make DevTools support both `package:vm_service` v13 and v14. Would it be possible to follow the second suggestion, @christopherfujino?

This is fine with me, as long as it's good with @kenzieschmoll. I just want to make sure we don't end up trying to roll an incompatible version of devtools into flutter/flutter.

**Comment by kenzieschmoll** [comment]
@derekxu16 has a draft PR to update DevTools to vm_service 14: https://github.com/flutter/devtools/pull/6953. Derek can you give an update on this? If we disable the customer tests, then the DevTools CI will start failing shortly after this PR lands. So we will need to migrate DevTools to 14 either way.

**Comment by derekxu16** [comment]
> @derekxu16 has a draft PR to update DevTools to vm_service 14: [flutter/devtools#6953](https://github.com/flutter/devtools/pull/6953). Derek can you give an update on this?

That PR is ready for review.

**Comment by kenzieschmoll** [comment]
I reviewed @derekxu16's DevTools PR to bump to vm_service 14. Let's follow the plan suggested above:
1) disable the DevTools flutter customer tests for now
2) land this PR
3) once the DevTools CI picks up this version of Flutter and the build goes red, Derek can land his DevTools PR to bump to vm_service 14 and fix the build
4) re-enable the DevTools flutter customer tests with the hash of Derek's DevTools PR

**Comment by derekxu16** [comment]
Just wondering, what is the status of this?

**Comment by christopherfujino** [comment]
> Just wondering, what is the status of this?

I'm gonna pick this up again next week--I'm pretty swamped right now.

**Review by derekxu16 — APPROVED** [review]

**Comment by DanTup** [comment]
@christopherfujino @bkonyi what's the current status of VM service 13/14? I was just trying to use DDS as a path dependency in Flutter and noticed that Flutter's vm_service dependency has been bumped to v14 here, but DDS in the SDK repo was put back to down to 13.

Was it an error that Flutter went up to 14? If not, when will DDS also use 14?

**Comment by derekxu16** [comment]
The `vm_service` constraint of DDS in the SDK was accidentally set back to `^13.0.0`. I'm working on publishing a new version of DDS that accepts `vm_service: ^14.0.0`.

**Comment by derekxu16** [comment]
Published.

https://pub.dev/packages/dds/versions/3.2.0

**Pull request merged**
