### PR TITLE
Revert "[flutter_tools] add --android-gradle-daemon option, use in devicelab"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#68409

### CODE REVIEW

**Comment by jonahwilliams** [comment]
TBR @zanderso

**Comment by jonahwilliams** [comment]
build commands are weird, this needs to go after the subcommand because of how we handle the args
```
2020-10-19T09:31:37.643905: 
Executing: /home/flutter/.cocoon/flutter/bin/flutter build --no-android-gradle-daemon apk --profile -t test_driver/transitions_perf.dart --target-platform android-arm,android-arm64 in /home/flutter/.cocoon/flutter/dev/integration_tests/flutter_gallery with environment {}
2020-10-19T09:31:37.959425: stderr: Could not find an option named "android-gradle-daemon".
stderr: 
2020-10-19T09:31:37.959536: stderr: Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
2020-10-19T09:31:37.978411: "/home/flutter/.cocoon/flutter/bin/flutter" exit code: 64
2020-10-19T09:31:37.984431: Task failed: Executable "/home/flutter/.cocoon/flutter/bin/flutter" failed with exit code 64.2020-10-19T09:31:37.984590: 
```

**Review by zanderso — COMMENTED** [review]
lgtm

**Comment by whesse** [comment]
This revert was relanded in https://github.com/flutter/flutter/pull/68491

**Pull request merged**
