### PR TITLE
Merge semantics in reorderable list draggables

### LINKED ISSUE #20589: ReorderableListView needs to merge semantics on draggables
We have a `ReorderableListView` that contains a list of SwitchListTiles. Right now, the accessibility actions for reordering that the ReorderableListView defines are not read aloud because the SwitchListTile defines its own set of semantics. We need the draggable widget to be wrapped in a `MergeSemantics`. Since the `ReorderableListView` is creating the draggables itself, wrapping our passed in widget, I believe this has to be fixed by the reorderable list view widget.

### PR DESCRIPTION
**Pull request by alanrussian**
Fixes #20589 

cc @DaveShuckerow

### CODE REVIEW

**Comment by Hixie** [comment]
cc @goderbauer @jonahwilliams

**Review by goderbauer — COMMENTED** [review]
Can you add a test for this?

**Comment by alanrussian** [comment]
I don't know if I have the bandwidth to write a test right now :( Are you able to contribute a test to this pull request or create a new one?

**Comment by Hixie** [comment]
Writing tests is an integral part of writing code. If there's no test, we can't check this in, because it means the patch is incomplete.

**Comment by alanrussian** [comment]
I agree but don't have the time to write one right now. We're in a time crunch right now for our launch. I only opened this pull request because I wrote it as I was trying to figure out what needed to be done to fix the accessibility issue in our app.

**Pull request closed without merging**
