### PR TITLE
Revert "ListTile Material Ripple and Shape Patch (#74373)"

### PR DESCRIPTION
**Pull request by gspencergoog**
This reverts commit 422916d201b21bf9c7e65225d520029e30ab278d because it causes unexpected changes in the rendering of the background of a `ListTile`.

The left side is before the change, and the right side is after (and the pink part is the diff).

Screenshot from 2021-02-16 10-44-20

Notice that the light grey background disappears.

/cc @NWalker1208

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by NWalker1208** [comment]
> This reverts commit 422916d201b21bf9c7e65225d520029e30ab278d because it causes unexpected changes in the rendering of the background of a `ListTile`.
> 
> The left side is before the change, and the right side is after (and the pink part is the diff).
> 
> Screenshot from 2021-02-16 10-44-20
> 
> Notice that the light grey background disappears.
> 
> /cc @NWalker1208 

Can you post the snippet of code that created the ListTiles with that background?

**Comment by gspencergoog** [comment]
@NWalker1208 Unfortunately, I can't share the code, partly because it's hugely complicated, but also because the customer's code is proprietary (Google's). I'm trying to build a test case, but so far I am failing to get it to reproduce.

**Comment by NWalker1208** [comment]
@gspencergoog I assume that the grey background on the first image is intentional. Otherwise, I feel like the second image actually looks better. Could you explain how their code tries to give the ListTile a grey background? For example, do they set the color property of the tile, or does a descendant of the ListTile paint the color?

Also, thanks for your patience. I didn’t think this contribution would be so troublesome, but maybe that's why nobody has fixed this issue before. Hopefully we can figure this out.

**Comment by gspencergoog** [comment]
Yes, the grey background is set on the `tileColor` attribute as `Colors.grey[50]`, and is intentional.

In looking at the widget tree, it looks like this may have to do with interactions with scrollable areas. If I replace the `ListView` with a `Column` in my example (linked below), the problem goes away. That might just be because it introduces different widgets in the tree, however.

In a diff of the two widget trees, this line (all from `debugDumpApp()`) in the "before your change" diff:
```
└ColoredBox(color: Color(0xfffafafa), renderObject: _RenderColoredBox#00000 relayoutBoundary=up35)
```

When run with your change, changes to:
```
└Ink(bg: ShapeDecoration(color: Color(0xfffafafa), shape: Border.all(BorderSide(Color(0xff000000), 0.0, BorderStyle.none))), state: _InkState#00000)
 └Padding-[GlobalKey#00000](padding: EdgeInsets.zero, dependencies: [Directionality], renderObject: RenderPadding#00000 relayoutBoundary=up35)
  └Builder(dependencies: [_LocalizationsScope-[GlobalKey#00000], Directionality, MediaQuery])
```

Which I think is mostly expected.

I think the problem has to do with how golden tests capture things, and in order to find the golden image, it needs a widget to start with, and if that widget contains a repaint boundary, it uses that repaint boundary, and if it doesn't, it uses an ancestor with a repaint boundary. Since you added in an `Ink`, it mutates which repaint boundary the test uses to capture the image. This might be a simple case of changing the test to match new expectations (making it search for a different widget to snapshot, for instance), but it also might point to some other issue.

Here's a [ZIP file](https://drive.google.com/file/d/1I1X_S9_OJjHE-y7AUW5GAMdyP2Rdr-k5/view?usp=sharing) with a sample app that shows the problem (you'll need to run "`flutter create .`" in there before it'll build).  Visually, the app when I run it is fine, but the `flutter test` fails with your code (doesn't draw the background into the golden), and succeeds without it. I included the golden image, the failed image (in `test/failures`) and some widget trees you can diff.

**Comment by NWalker1208** [comment]
@gspencergoog So I believe this issue with the test is being caused because the background created by the Ink widget isn't actually painted by the Ink widget, but by it's nearest Material widget ancestor. The golden test only captures what's rendered on the nearest RepaintBoundary. When the tile is in a ListView, the Material widget has a few RepaintBoundaries between it and the ListTile. Before my change, the ListTile painted its own background, so it was captured by the test. Since my change causes the Material widget to render the background, the golden test fails because it doesn't see past the nearest RepaintBoundary.

One way to fix this would be to replace the Ink widget with a Material widget, so that it renders all InkFeatures by itself. This would satisfy the test, but it would be less efficient, especially in situations where there are many ListTiles. The alternative, like you mentioned, is to try to change the test. I haven't looked at the source code for it yet, so I might need some pointers on where to look, but I could give it a shot. What would you recommend?

```
└Material(type: canvas, color: Color(0xfffafafa), dependencies: [_InheritedTheme, _EffectiveTickerMode, _LocalizationsScope-[GlobalKey#00000]], state: _MaterialState#00000)
 └AnimatedPhysicalModel(duration: 200ms, shape: rectangle, borderRadius: BorderRadius.zero, elevation: 0.0, color: Color(0xfffafafa), animateColor: false, shadowColor: Color(0xff000000), animateShadowColor: true, dependencies: [_EffectiveTickerMode], state: _AnimatedPhysicalModelState#00000(ticker inactive))
  └PhysicalModel(shape: rectangle, borderRadius: BorderRadius.zero, elevation: 0.0, color: Color(0xfffafafa), shadowColor: Color(0xff000000), renderObject: RenderPhysicalModel#00000)
   └NotificationListener<LayoutChangedNotification>
    └_InkFeatures-[GlobalKey#00000 ink renderer](renderObject: _RenderInkFeatures#00000)
     └AnimatedDefaultTextStyle(duration: 200ms, debugLabel: (englishLike body1 2014).merge(blackMountainView bodyText2), inherit: false, color: Color(0xdd000000), family: Roboto, size: 14.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip, dependencies: [_EffectiveTickerMode], state: _AnimatedDefaultTextStyleState#00000(ticker inactive))
      └DefaultTextStyle(debugLabel: (englishLike body1 2014).merge(blackMountainView bodyText2), inherit: false, color: Color(0xdd000000), family: Roboto, size: 14.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip)
       └AnimatedBuilder(animation: AnimationController#00000(⏭ 1.000; paused), state: _AnimatedState#00000)
        └CustomMultiChildLayout(renderObject: RenderCustomMultiChildLayoutBox#00000)
         ├LayoutId-[<_ScaffoldSlot.body>](id: _ScaffoldSlot.body)
         │└MediaQuery(MediaQueryData(size: Size(800.0, 600.0), devicePixelRatio: 3.0, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding: EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, highContrast: false, disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional))
         │ └_BodyBuilder
         │  └ListView(scrollDirection: vertical, primary: using primary controller, AlwaysScrollableScrollPhysics, dependencies: [MediaQuery, PrimaryScrollController])
         │   └PrimaryScrollController(no controller)
         │    └Scrollable(axisDirection: down, physics: AlwaysScrollableScrollPhysics, restorationId: null, dependencies: [UnmanagedRestorationScope, ScrollConfiguration, _EffectiveTickerMode, _InheritedTheme, _LocalizationsScope-[GlobalKey#00000]], state: ScrollableState#00000(position: ScrollPositionWithSingleContext#00000(offset: 0.0, range: 0.0..0.0, viewport: 544.0, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#00000, ScrollDirection.idle), effective physics: AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics))
         │     └GlowingOverscrollIndicator(axisDirection: down, show: both sides, Color(0xff2196f3), dependencies: [_EffectiveTickerMode], state: _GlowingOverscrollIndicatorState#00000(tickers: tracking 4 tickers))
         │      └NotificationListener<ScrollNotification>
         │       └RepaintBoundary(renderObject: RenderRepaintBoundary#00000 relayoutBoundary=up1)  # REPAINT BOUNDARY
         │        └CustomPaint(renderObject: RenderCustomPaint#00000 relayoutBoundary=up2)
         │         └RepaintBoundary(renderObject: RenderRepaintBoundary#00000 relayoutBoundary=up3)  # REPAINT BOUNDARY
         │          └_ScrollSemantics-[GlobalKey#00000](renderObject: _RenderScrollSemantics#00000 relayoutBoundary=up4)
         │           └_ScrollableScope
         │            └Listener(listeners: [signal], behavior: deferToChild, renderObject: RenderPointerListener#00000 relayoutBoundary=up5)
         │             └RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#00000](state: RawGestureDetectorState#00000(gestures: [vertical drag], behavior: opaque))
         │              └_GestureSemantics(renderObject: RenderSemanticsGestureHandler#00000 relayoutBoundary=up6)
         │               └Listener(listeners: [down], behavior: opaque, renderObject: RenderPointerListener#00000 relayoutBoundary=up7)
         │                └Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null, hintOverrides: null, renderObject: RenderSemanticsAnnotations#00000 relayoutBoundary=up8)
         │                 └IgnorePointer-[GlobalKey#00000](ignoring: false, ignoringSemantics: false, renderObject: RenderIgnorePointer#00000 relayoutBoundary=up9)
         │                  └Viewport(axisDirection: down, anchor: 0.0, offset: ScrollPositionWithSingleContext#00000(offset: 0.0, range: 0.0..0.0, viewport: 544.0, ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#00000, ScrollDirection.idle), cacheExtent: null, cacheExtentStyle: CacheExtentStyle.pixel, dependencies: [Directionality], renderObject: RenderViewport#00000)
         │                   └SliverPadding(padding: EdgeInsets.zero, dependencies: [Directionality], renderObject: RenderSliverPadding#00000 relayoutBoundary=up1)
         │                    └MediaQuery(MediaQueryData(size: Size(800.0, 600.0), devicePixelRatio: 3.0, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding: EdgeInsets.zero, viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, highContrast: false, disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional))
         │                     └SliverList(delegate: SliverChildListDelegate#00000(estimated child count: 4), renderObject: RenderSliverList#00000 relayoutBoundary=up2)
         │                      ├KeyedSubtree
         │                      │└AutomaticKeepAlive(state: _AutomaticKeepAliveState#00000(handles: no notifications ever received))
         │                      │ └KeepAlive(keepAlive: false)
         │                      │  └NotificationListener<KeepAliveNotification>
         │                      │   └IndexedSemantics(index: 0, renderObject: RenderIndexedSemantics#00000 relayoutBoundary=up3)
         │                      │    └RepaintBoundary(renderObject: RenderRepaintBoundary#00000 relayoutBoundary=up4)  # REPAINT BOUNDARY
         │                      │     └MyTile(dependencies: [_InheritedTheme, _LocalizationsScope-[GlobalKey#00000]])
         │                      │      └Padding(padding: EdgeInsets.all(8.0), dependencies: [Directionality], renderObject: RenderPadding#00000 relayoutBoundary=up5)
         │                      │       └MergeSemantics(renderObject: RenderMergeSemantics#00000 relayoutBoundary=up6)
         │                      │        └Builder
         │                      │         └ListTileTheme
         │                      │          └ListTile(dependencies: [Directionality, ListTileTheme, _InheritedTheme, _LocalizationsScope-[GlobalKey#00000]])
         │                      │           └InkWell
```

**Comment by gspencergoog** [comment]
@NWalker1208 I think you have it figured out.  I don't think replacing the `Ink` with a `Material` is the right way to go: it's just going to be inefficient.

I think I'll try and change the test, since it's likely that the actual app is rendering properly, it's just being captured differently now. Obviously, I'd have to verify that first.

I'll see if can create a new PR (with your changes) and try to land it simultaneously with changes to the internal test (we have a mechanism for that). (It may be a few days, I've been busy...)

**Comment by NWalker1208** [comment]
@gspencergoog Sounds like a plan. Let me know if you run into any new issues.

**Pull request merged**
