### PR TITLE
Reland #61998 and update complex_layout ios files

### PR DESCRIPTION
**Pull request by CareF**
This is by revert #64883, run following  to update `ios/` :

```bash
cp -r ~/flutter/dev/benchmarks/complex_layout ~/tmp/
# flutter create cannot run in Flutter SDK path. 
cd ~/tmp/complex_layout
flutter create ./
cd ~/flutter/dev/benchmarks/complex_layout
rm -rf ios
cp -r ~/tmp/complex_layout/ios ./
```
and add license header to 
- `dev/benchmarks/complex_layout/ios/Runner/Runner-Bridging-Header.h`
- `dev/benchmarks/complex_layout/ios/Runner/AppDelegate.swift`

### CODE REVIEW

**Comment by CareF** [comment]
@googlebot I signed it!

**Comment by shihaohong** [comment]
@CareF There's an analyzer issue --
```
The following 1 file does not have the right license header:
/tmp/flutter sdk/dev/benchmarks/complex_layout/ios/Runner/Runner-Bridging-Header.h
The expected license header is:
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
...followed by a blank line.
```

**Comment by CareF** [comment]
> @CareF There's an analyzer issue --
> 
> ```
> The following 1 file does not have the right license header:
> /tmp/flutter sdk/dev/benchmarks/complex_layout/ios/Runner/Runner-Bridging-Header.h
> The expected license header is:
> // Copyright 2014 The Flutter Authors. All rights reserved.
> // Use of this source code is governed by a BSD-style license that can be
> // found in the LICENSE file.
> ...followed by a blank line.
> ```

Done

**Comment by CareF** [comment]
Before merge this I will need to add revert #64883 to this PR make it meaningful.

**Review by liyuqian — APPROVED** [review]
LGTM

**Comment by CareF** [comment]
@liyuqian I no longer have the permission to merge or to add `wait until green` label.

**Comment by CareF** [comment]
@liyuqian This is still causing the tests to fail. Without logs I don't have  more clues about how to fix it. I created a revert in #64990

**Comment by jonahwilliams** [comment]
Here is one of the failure logs:

```


------------ TASK ------------
Task(id: 5796757902065664, parentKey: flutter/flutter/master/df83398687b63762c742e35fbb608d16fee50a7a, key: 5796757902065664, commitKey: flutter/flutter/master/df83398687b63762c742e35fbb608d16fee50a7a, createTimestamp: 1598919841395, startTimestamp: 1598923194569, endTimestamp: 1598923226576, name: complex_layout_ios__compile, attempts: 2, isFlaky: false, timeoutInMinutes: 0, reason: Task failed on agent, requiredCapabilities: [mac/ios], reservedForAgentId: flutter-devicelab-mac-2, stageName: devicelab_ios, status: Failed, buildNumber: null, buildNumberList: null, builderName: null, luciBucket: null)

------------ LOG ------------
Deleting build/ directories, if any.
Deleting /Users/flutter/.cocoon/flutter/dev/benchmarks/macrobenchmarks/build
2020-08-31T18:14:36.122096: Agent ID: flutter-devicelab-mac-62020-08-31T18:14:36.530425: Observatory listening on http://127.0.0.1:20000/
2020-08-31T18:14:37.180553: Running task with a timeout of null.
2020-08-31T18:14:37.181127: 

══════════════════╡ ••• Checking running Dart processes ••• ╞═══════════════════

2020-08-31T18:14:37.270291: RunningProcesses{pid: 1731, commandLine: dart bin/agent.dart ci -c config.yaml, creationDate: 2020-08-20 08:54:04.000}
RunningProcesses{pid: 30896, commandLine: /Users/flutter/.cocoon/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --enable-vm-service=20000 --no-pause-isolates-on-exit --disable-service-auth-codes bin/tasks/complex_layout_ios__compile.dart --cloud-auth-token=ya29.c.Ko8B2gdOkiPrHv_2Y7APiqf1pxrbs6IwZyFnHatofZwpKH2ok60qLbljG0Z8DRhewGqVCIH2MlkwfxUnHiI0HBZKUK4zyodwsBqdVRxEeiQ3uNP8osg7d5M8PHYxQXDNZlCSfuwTg3epaywOCWmoxQjD3Vhf-ugaG_LB2Z_-2SVQ08MqETMarV2SfsON9ZJGzo8, creationDate: 2020-08-31 18:14:36.000}
RunningProcesses{pid: 58986, commandLine: /Users/flutter/.cocoon/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/flutter/.cocoon/flutter/packages/flutter_tools/.packages /Users/flutter/.cocoon/flutter/bin/cache/flutter_tools.snapshot run --hot -d macos --benchmark --verbose --resident --output-dill build/app.dill, creationDate: 2020-08-21 17:12:11.000}
RunningProcesses{pid: 59040, commandLine: /Users/flutter/.cocoon/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/flutter/.cocoon/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/flutter/.cocoon/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill build/app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill, creationDate: 2020-08-21 17:12:17.000}
enabling configs for macOS, Linux, Windows, and Web...
2020-08-31T18:14:37.272575: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter config --enable-macos-desktop --enable-windows-desktop --enable-linux-desktop --enable-web in /Users/flutter/.cocoon/flutter/dev/devicelab
2020-08-31T18:14:37.754978: stdout: Setting "enable-web" value to "true".
2020-08-31T18:14:37.755078: stdout: Setting "enable-linux-desktop" value to "true".
stdout: Setting "enable-macos-desktop" value to "true".
stdout: Setting "enable-windows-desktop" value to "true".
2020-08-31T18:14:37.755406: stdout: 
stdout: You may need to restart any open editors for them to read new settings.
2020-08-31T18:14:37.781279: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-08-31T18:14:37.798586: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter devices --machine --suppress-analytics in /Users/flutter/.cocoon/flutter/dev/benchmarks/complex_layout
2020-08-31T18:14:41.018979: stdout: [
2020-08-31T18:14:41.019146: stdout:   {
stdout:     "name": "iPhone",
stdout:     "id": "b4873f14ffb248dfcb00c8cb7fdd4cdcff87f1f0",
stdout:     "isSupported": true,
stdout:     "targetPlatform": "ios",
stdout:     "emulator": false,
stdout:     "sdk": "iOS 12.4",
stdout:     "capabilities": {
stdout:       "hotReload": true,
stdout:       "hotRestart": true,
stdout:       "screenshot": true,
stdout:       "fastStart": false,
stdout:       "flutterExit": true,
stdout:       "hardwareRendering": false,
stdout:       "startPaused": false
stdout:     }
stdout:   },
stdout:   {
stdout:     "name": "macOS",
stdout:     "id": "macos",
stdout:     "isSupported": true,
stdout:     "targetPlatform": "darwin-x64",
stdout:     "emulator": false,
stdout:     "sdk": "Mac OS X 10.14.6 18G103",
stdout:     "capabilities": {
stdout:       "hotReload": true,
stdout:       "hotRestart": true,
stdout:       "screenshot": false,
stdout:       "fastStart": false,
stdout:       "flutterExit": true,
stdout:       "hardwareRendering": false,
stdout:       "startPaused": true
stdout:     }
stdout:   },
stdout:   {
stdout:     "name": "Web Server",
stdout:     "id": "web-server",
stdout:     "isSupported": true,
stdout:     "targetPlatform": "web-javascript",
stdout:     "emulator": false,
2020-08-31T18:14:41.019209: stdout:     "sdk": "Flutter Tools",
stdout:     "capabilities": {
stdout:       "hotReload": true,
stdout:       "hotRestart": true,
stdout:       "screenshot": false,
stdout:       "fastStart": false,
stdout:       "flutterExit": false,
stdout:       "hardwareRendering": false,
stdout:       "startPaused": true
stdout:     }
stdout:   },
2020-08-31T18:14:41.019268: stdout:   {
stdout:     "name": "Chrome",
stdout:     "id": "chrome",
stdout:     "isSupported": true,
stdout:     "targetPlatform": "web-javascript",
stdout:     "emulator": false,
stdout:     "sdk": "Google Chrome 77.0.3865.90",
2020-08-31T18:14:41.019314: stdout:     "capabilities": {
stdout:       "hotReload": true,
stdout:       "hotRestart": true,
stdout:       "screenshot": false,
stdout:       "fastStart": false,
2020-08-31T18:14:41.019538: stdout:       "flutterExit": false,
stdout:       "hardwareRendering": false,
2020-08-31T18:14:41.019581: stdout:       "startPaused": true
stdout:     }
stdout:   }
stdout: ]
2020-08-31T18:14:41.042065: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-08-31T18:14:41.047039: Device chosen: device: b4873f14ffb248dfcb00c8cb7fdd4cdcff87f1f0
2020-08-31T18:14:41.048044: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter packages get in /Users/flutter/.cocoon/flutter/dev/benchmarks/complex_layout
2020-08-31T18:14:42.147985: stdout: Running "flutter pub get" in complex_layout...                      0.5s
2020-08-31T18:14:42.269132: stdout: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
stdout: Warning
stdout: ──────────────────────────────────────────────────────────────────────────────
stdout: Your Flutter application is created using an older version of the Android
stdout: embedding. It's being deprecated in favor of Android embedding v2. Follow the
stdout: steps at
stdout: 
stdout: https://flutter.dev/go/android-project-migration
stdout: 
stdout: to migrate your project.
stdout: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
stdout: 
2020-08-31T18:14:42.445760: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-08-31T18:14:42.447201: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter clean in /Users/flutter/.cocoon/flutter/dev/benchmarks/complex_layout
2020-08-31T18:14:44.940628: stdout: Cleaning Xcode workspace...                                         1.9s
2020-08-31T18:14:44.943582: stdout: Deleting .dart_tool...                                               0ms
2020-08-31T18:14:44.945097: stdout: Deleting Generated.xcconfig...                                       0ms
2020-08-31T18:14:44.945690: stdout: Deleting flutter_export_environment.sh...                            0ms
2020-08-31T18:14:44.947940: stdout: Deleting .flutter-plugins-dependencies...                            0ms
2020-08-31T18:14:44.948420: stdout: Deleting .flutter-plugins...                                         0ms
2020-08-31T18:14:44.962087: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-08-31T18:14:44.962699: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter build ios --release --tree-shake-icons --split-debug-info=infos/ in /Users/flutter/.cocoon/flutter/dev/benchmarks/complex_layout
2020-08-31T18:14:46.002692: stdout: Running "flutter pub get" in complex_layout...                      0.5s
2020-08-31T18:14:46.159783: stdout: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
stdout: Warning
stdout: ──────────────────────────────────────────────────────────────────────────────
stdout: Your Flutter application is created using an older version of the Android
stdout: embedding. It's being deprecated in favor of Android embedding v2. Follow the
stdout: steps at
stdout: 
stdout: https://flutter.dev/go/android-project-migration
stdout: 
stdout: to migrate your project.
stdout: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
stdout: 
2020-08-31T18:14:48.236560: stdout: Building com.yourcompany.complexLayout for device (ios-release)...
2020-08-31T18:14:48.367858: stdout: Warning: Missing build name (CFBundleShortVersionString).
stdout: Warning: Missing build number (CFBundleVersion).
2020-08-31T18:14:48.369783: stderr: Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
2020-08-31T18:14:48.371456: stdout: Automatically signing iOS for device deployment using specified development team in Xcode project: S8QB4VV633
2020-08-31T18:14:49.981392: stdout: Running pod install...                                              1.0s
2020-08-31T18:14:53.684194: stdout: Running Xcode build...                                          
2020-08-31T18:14:53.684352: stdout: Xcode build done.                                            3.7s
2020-08-31T18:14:54.736758: stdout: Failed to build iOS app
2020-08-31T18:14:54.736880: stdout: Error output from Xcode build:
stdout: ↳
2020-08-31T18:14:54.736946: stdout:     ** BUILD FAILED **
stdout: 
stdout: 
2020-08-31T18:14:54.737048: stdout: Xcode's output:
stdout: ↳
2020-08-31T18:14:54.737127: stdout:     diff: /Podfile.lock: No such file or directory
stdout:     diff: /Manifest.lock: No such file or directory
stdout:     error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
2020-08-31T18:14:54.737174: stdout:     note: Using new build systemnote: Planning buildnote: Constructing build description
stdout: 
2020-08-31T18:14:54.745505: stderr: Encountered error while building for device.
2020-08-31T18:14:54.757055: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 1
2020-08-31T18:14:54.765806: Task failed: Executable "/Users/flutter/.cocoon/flutter/bin/flutter" failed with exit code 1.2020-08-31T18:14:54.766081: 

Stack trace:
2020-08-31T18:14:54.783080: package:flutter_devicelab/framework/utils.dart 98:3        fail
package:flutter_devicelab/framework/utils.dart 363:5       _execute
===== asynchronous gap ===========================
dart:async                                                 _asyncErrorWrapperHelper
package:flutter_devicelab/framework/framework.dart         _TaskRunner._performTask.<fn>
package:stack_trace                                        Chain.capture
package:flutter_devicelab/framework/framework.dart 169:11  _TaskRunner._performTask
package:flutter_devicelab/framework/framework.dart 101:41  _TaskRunner.run

2020-08-31T18:14:54.783362: 

═══════════╡ ••• Checking running Dart processes after task... ••• ╞════════════

2020-08-31T18:14:54.811239: Cleaning up after task...
2020-08-31T18:14:54.840614: Task execution finished

Task failed with the following reason:
Task failed: Executable "/Users/flutter/.cocoon/flutter/bin/flutter" failed with exit code 1.
Deleting build/ directories, if any.
Deleting /Users/flutter/.cocoon/flutter/dev/integration_tests/ui/build
2020-08-31T18:19:55.580993: Agent ID: flutter-devicelab-mac-22020-08-31T18:20:14.365856: 

═══════════╡ ••• Checking running Dart processes after task... ••• ╞════════════

2020-08-31T18:20:14.395190: Cleaning up after task...
2020-08-31T18:20:14.423563: Task execution finished2020-08-31T18:19:56.133464: Observatory listening on http://127.0.0.1:20000/
2020-08-31T18:19:56.628020: Running task with a timeout of null.
2020-08-31T18:19:56.628574: 

══════════════════╡ ••• Checking running Dart processes ••• ╞═══════════════════

2020-08-31T18:19:56.718646: RunningProcesses{pid: 2437, commandLine: dart bin/agent.dart ci -c config.yaml, creationDate: 2020-08-18 16:04:38.000}
RunningProcesses{pid: 74885, commandLine: /Users/flutter/.cocoon/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --enable-vm-service=20000 --no-pause-isolates-on-exit --disable-service-auth-codes bin/tasks/complex_layout_ios__compile.dart --cloud-auth-token=ya29.c.Ko8B2gdXEljlVJcFfCIHzj6Tqv2u40oM1j0YeSOIFyZ_0KPyd0pVhvjLvhOPFkTUHOLLWvARQuIZBzVIRDhsUXgisgjWqW7nVpI57TDfz4xRtNMJxVAx13EkG3BH0IBAzXlVddsFxBGhY71pjcFOAT9zzEEFX4HN5gr_t_o5K-StbKFIxGKHItcRFRFZJLblaHk, creationDate: 2020-08-31 18:19:55.000}
RunningProcesses{pid: 93859, commandLine: /Users/flutter/.cocoon/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/flutter/.cocoon/flutter/packages/flutter_tools/.packages /Users/flutter/.cocoon/flutter/bin/cache/flutter_tools.snapshot run --hot -d macos --benchmark --verbose --resident --output-dill build/app.dill, creationDate: 2020-08-21 17:20:34.000}
RunningProcesses{pid: 93916, commandLine: /Users/flutter/.cocoon/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /Users/flutter/.cocoon/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/flutter/.cocoon/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill build/app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill, creationDate: 2020-08-21 17:20:41.000}
enabling configs for macOS, Linux, Windows, and Web...
2020-08-31T18:19:56.720919: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter config --enable-macos-desktop --enable-windows-desktop --enable-linux-desktop --enable-web in /Users/flutter/.cocoon/flutter/dev/devicelab
2020-08-31T18:19:57.197857: stdout: Setting "enable-web" value to "true".
2020-08-31T18:19:57.197940: stdout: Setting "enable-linux-desktop" value to "true".
stdout: Setting "enable-macos-desktop" value to "true".
stdout: Setting "enable-windows-desktop" value to "true".
2020-08-31T18:19:57.198252: stdout: 
stdout: You may need to restart any open editors for them to read new settings.
2020-08-31T18:19:57.224715: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-08-31T18:19:57.242086: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter devices --machine --suppress-analytics in /Users/flutter/.cocoon/flutter/dev/benchmarks/complex_layout
2020-08-31T18:20:00.427013: stdout: [
2020-08-31T18:20:00.427193: stdout:   {
stdout:     "name": "iPhone",
stdout:     "id": "b579ee2d16e30f86651249dc51e4ebef46d36ac0",
stdout:     "isSupported": true,
stdout:     "targetPlatform": "ios",
stdout:     "emulator": false,
stdout:     "sdk": "iOS 11.3",
stdout:     "capabilities": {
stdout:       "hotReload": true,
stdout:       "hotRestart": true,
stdout:       "screenshot": true,
stdout:       "fastStart": false,
stdout:       "flutterExit": true,
stdout:       "hardwareRendering": false,
stdout:       "startPaused": false
stdout:     }
stdout:   },
stdout:   {
stdout:     "name": "macOS",
stdout:     "id": "macos",
stdout:     "isSupported": true,
stdout:     "targetPlatform": "darwin-x64",
stdout:     "emulator": false,
stdout:     "sdk": "Mac OS X 10.14.6 18G103",
stdout:     "capabilities": {
stdout:       "hotReload": true,
stdout:       "hotRestart": true,
stdout:       "screenshot": false,
stdout:       "fastStart": false,
stdout:       "flutterExit": true,
stdout:       "hardwareRendering": false,
stdout:       "startPaused": true
stdout:     }
stdout:   },
stdout:   {
stdout:     "name": "Web Server",
stdout:     "id": "web-server",
stdout:     "isSupported": true,
stdout:     "targetPlatform": "web-javascript",
stdout:     "emulator": false,
stdout:     "sdk": "Flutter Tools",
stdout:     "capabilities": {
stdout:       "hotReload": true,
stdout:       "hotRestart": true,
stdout:       "screenshot": false,
stdout:       "fastStart": false,
stdout:       "flutterExit": false,
2020-08-31T18:20:00.427272: stdout:       "hardwareRendering": false,
stdout:       "startPaused": true
stdout:     }
stdout:   }
stdout: ]
2020-08-31T18:20:00.450124: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-08-31T18:20:00.455027: Device chosen: device: b579ee2d16e30f86651249dc51e4ebef46d36ac0
2020-08-31T18:20:00.456028: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter packages get in /Users/flutter/.cocoon/flutter/dev/benchmarks/complex_layout
2020-08-31T18:20:01.530539: stdout: Running "flutter pub get" in complex_layout...                      0.5s
2020-08-31T18:20:01.661585: stdout: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
stdout: Warning
stdout: ──────────────────────────────────────────────────────────────────────────────
stdout: Your Flutter application is created using an older version of the Android
stdout: embedding. It's being deprecated in favor of Android embedding v2. Follow the
stdout: steps at
stdout: 
stdout: https://flutter.dev/go/android-project-migration
stdout: 
stdout: to migrate your project.
stdout: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
stdout: 
2020-08-31T18:20:01.847660: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-08-31T18:20:01.849046: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter clean in /Users/flutter/.cocoon/flutter/dev/benchmarks/complex_layout
2020-08-31T18:20:04.337603: stdout: Cleaning Xcode workspace...                                         1.9s
2020-08-31T18:20:04.340670: stdout: Deleting .dart_tool...                                               0ms
2020-08-31T18:20:04.342431: stdout: Deleting Generated.xcconfig...                                       0ms
2020-08-31T18:20:04.343048: stdout: Deleting flutter_export_environment.sh...                            0ms
2020-08-31T18:20:04.345316: stdout: Deleting .flutter-plugins-dependencies...                            0ms
2020-08-31T18:20:04.345817: stdout: Deleting .flutter-plugins...                                         0ms
2020-08-31T18:20:04.360023: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-08-31T18:20:04.360539: 
Executing: /Users/flutter/.cocoon/flutter/bin/flutter build ios --release --tree-shake-icons --split-debug-info=infos/ in /Users/flutter/.cocoon/flutter/dev/benchmarks/complex_layout
2020-08-31T18:20:05.417670: stdout: Running "flutter pub get" in complex_layout...                      0.5s
2020-08-31T18:20:05.577200: stdout: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
stdout: Warning
stdout: ──────────────────────────────────────────────────────────────────────────────
stdout: Your Flutter application is created using an older version of the Android
stdout: embedding. It's being deprecated in favor of Android embedding v2. Follow the
stdout: steps at
stdout: 
stdout: https://flutter.dev/go/android-project-migration
stdout: 
2020-08-31T18:20:05.577301: stdout: to migrate your project.
stdout: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
stdout: 
2020-08-31T18:20:07.675028: stdout: Building com.yourcompany.complexLayout for device (ios-release)...
2020-08-31T18:20:07.846158: stdout: Warning: Missing build name (CFBundleShortVersionString).
stdout: Warning: Missing build number (CFBundleVersion).
2020-08-31T18:20:07.848086: stderr: Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
2020-08-31T18:20:07.849792: stdout: Automatically signing iOS for device deployment using specified development team in Xcode project: S8QB4VV633
2020-08-31T18:20:09.574765: stdout: Running pod install...                                              1.1s
2020-08-31T18:20:13.265417: stdout: Running Xcode build...                                          
2020-08-31T18:20:13.265663: stdout: Xcode build done.                                            3.7s
2020-08-31T18:20:14.319585: stdout: Failed to build iOS app
2020-08-31T18:20:14.319698: stdout: Error output from Xcode build:
2020-08-31T18:20:14.319753: stdout: ↳
stdout:     ** BUILD FAILED **
2020-08-31T18:20:14.319796: stdout: 
stdout: 
2020-08-31T18:20:14.319902: stdout: Xcode's output:
stdout: ↳
2020-08-31T18:20:14.319980: stdout:     diff: /Podfile.lock: No such file or directory
stdout:     diff: /Manifest.lock: No such file or directory
stdout:     error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
stdout:     note: Using new build systemnote: Planning buildnote: Constructing build description
stdout: 
2020-08-31T18:20:14.328239: stderr: Encountered error while building for device.
2020-08-31T18:20:14.339615: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 1
2020-08-31T18:20:14.348404: Task failed: Executable "/Users/flutter/.cocoon/flutter/bin/flutter" failed with exit code 1.2020-08-31T18:20:14.348672: 

Stack trace:
2020-08-31T18:20:14.365419: package:flutter_devicelab/framework/utils.dart 98:3        fail
package:flutter_devicelab/framework/utils.dart 363:5       _execute
===== asynchronous gap ===========================
dart:async                                                 _asyncErrorWrapperHelper
package:flutter_devicelab/framework/framework.dart         _TaskRunner._performTask.<fn>
package:stack_trace                                        Chain.capture
package:flutter_devicelab/framework/framework.dart 169:11  _TaskRunner._performTask
package:flutter_devicelab/framework/framework.dart 101:41  _TaskRunner.run



Task failed with the following reason:
Task failed: Executable "/Users/flutter/.cocoon/flutter/bin/flutter" failed with exit code 1.
```

**Comment by jonahwilliams** [comment]
The issue is probably:

```
2020-08-31T18:14:54.737127: stdout:     diff: /Podfile.lock: No such file or directory
stdout:     diff: /Manifest.lock: No such file or directory
stdout:     error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
2020-08-31T18:14:54.737174: stdout:     note: Using new build systemnote: Planning buildnote: Constructing build description
```

**Comment by CareF** [comment]
It still looks like we need to adjust what's in `ios/`, but I don't have any idea about how to do it. This PR can run `flutter test` or `flutter drive` on my local machine, with manual interference with signing using personal account, but that may depend on the xcode version. I think I have to stop here and ask the infra team for help. @liyuqian @dnfield

**Comment by liyuqian** [comment]
Ok, I created https://github.com/flutter/flutter/issues/65047 and added it to my TODO list. I should be able to find sometime to test it locally on iPhones before the end of September.

**Comment by gspencergoog** [comment]
I have no concrete evidence other than the number of retries on the build page, but the "flakiness" of `complex_layout_ios__start_up` seems to have increased after this PR.

**Comment by liyuqian** [comment]
@gspencergoog : the first yellow commit on https://flutter-dashboard.appspot.com/#/build seems to be https://github.com/flutter/flutter/commit/b3d1ebf117589c90a0fc09e76920dc80d92d4dc8 ?

Anyway, I checked several failed run and saw some error messages as below
```
2020-09-14T09:39:01.012522: stdout: [  +53 ms] HttpException: Connection closed before full header was received, uri = http://localhost:62410/ws
2020-09-14T09:39:03.030427: stdout: [+2017 ms] HttpException: , uri = http://localhost:62410/ws
2020-09-14T09:39:05.040692: stdout: [+2010 ms] HttpException: , uri = http://localhost:62410/ws
2020-09-14T09:39:07.045852: stdout: [+2005 ms] HttpException: , uri = http://localhost:62410/ws
2020-09-14T09:39:09.060897: stdout: [+2015 ms] HttpException: , uri = http://localhost:62410/ws
2020-09-14T09:39:11.072518: stdout: [+2011 ms] Failed to connect directly, falling back to mDNS
2020-09-14T09:39:11.076292: stdout: [   +4 ms] Checking for advertised Dart observatories...
2020-09-14T09:39:16.090269: stdout: [+5014 ms] No pointer records found.
2020-09-14T09:39:16.091501: stdout: [   +1 ms] mDNS query failed. Checking for an interface with a ipv4 link local address.
2020-09-14T09:39:16.093360: stdout: [   +1 ms] Found interface "en0":
2020-09-14T09:39:16.093668: stdout: [        ] 	Bound address: "192.168.1.231" 
stdout: [        ] Found interface "en1":
2020-09-14T09:39:16.093792: stdout: [        ] 	Bound address: "169.254.98.90" link local
2020-09-14T09:39:16.093857: stdout: [        ] Found interface "en8":
2020-09-14T09:39:16.093899: stdout: [        ] 	Bound address: "169.254.92.48" link local
2020-09-14T09:39:16.094260: stdout: [        ] An interface with an ipv4 link local address was found.
2020-09-14T09:39:16.094342: stdout: [        ] Failed to connect with mDNS, falling back to log scanning
```

I've seen many of these errors locally since a few weeks (can't remember exactly when) with my local iPhone 6s using vanilla tip-of-tree Flutter. I can use Xcode to run a Flutter app, but using `flutter run` or `flutter drive` would fail with this maybe 90% of the time. Meanwhile, @CareF didn't have any issue with his iPhone 6s so I think it's hardware or host environment specific.

BTW, I think this "failed to connect with mDNS" failure is not just limited to `complex_layout_ios__start_up`. I can see it in almost all flaky iOS devicelab tests.

@jonahwilliams @zanderso @godofredoc : any idea how to debug and fix this?

**Comment by jonahwilliams** [comment]
No idea

**Comment by jonahwilliams** [comment]
We really just need a way to get the device logs and drop the mDNS discovery

**Comment by jonahwilliams** [comment]
i.e. the app could have crashed or have other sorts of startup exceptions and I'm pretty sure we're missing them right now

**Comment by liyuqian** [comment]
Yes, I can see the app immediately disappear after launch (presumably crashed) in my failed local run/drive, and there's no crash or error logs even with `--verbose`.

**Comment by jonahwilliams** [comment]
If you run the app through xcode you should be able to see why it is crashing

**Comment by CareF** [comment]
> I've seen many of these errors locally since a few weeks (can't remember exactly when) with my local iPhone 6s using vanilla tip-of-tree Flutter. I can use Xcode to run a Flutter app, but using `flutter run` or `flutter drive` would fail with this maybe 90% of the time. Meanwhile, @CareF didn't have any issue with his iPhone 6s so I think it's hardware or host environment specific.

I do have issue with my iPhone 6s. It's very like what you described above: if fails very often (but not always) with `flutter run/drive` but fine with Xcode.

**Comment by liyuqian** [comment]
@jonahwilliams : unfortunately if doesn't crash with Xcode. It only crashes with `flutter run` and `flutter drive`...

@CareF : oh I didn't notice that. Then I wonder why the device lab didn't have that until very recently. @digiter : is there any recent Xcode or iOS upgrade in the device lab?

**Comment by jonahwilliams** [comment]
Then the problem is that mDNS is not working.

**Pull request merged**
