### PR TITLE
Roll engine to 2812ea3ed304eac01d89fe456cd5d45f658ce11c

### PR DESCRIPTION
**Pull request by tvolkert**
This contains the following commits:

flutter/engine@2812ea3 Define Uri.base as CWD to match the standalone Dart VM.
flutter/engine@6f15a91 Roll src/third_party/skia/ 4912d903b..dc3192b30 (7 commits)
flutter/engine@f9165be Roll src/third_party/skia/ c353ee211..4912d903b (1 commit)
flutter/engine@fb51bf2 Roll src/third_party/skia/ d5750b6b3..c353ee211 (1 commit)
flutter/engine@a859432 Roll buildroot to a69ebc4e1.
flutter/engine@89a8dff Roll src/third_party/skia/ 0ce19fa0b..d5750b6b3 (3 commits; 1 trivial rolls)

### CODE REVIEW

**Review by yjbanov — APPROVED** [review]

**Comment by yjbanov** [comment]
lgtm

**Comment by tvolkert** [comment]
@fkorotkov do you know how to restart a failed Cirrus task, to deflake?

**Comment by fkorotkov** [comment]
@tvolkert you should see a `Re-Run` button on task's page: https://cirrus-ci.com/task/4897204238024704

**Comment by tvolkert** [comment]
@fkorotkov the [task page](https://cirrus-ci.com/task/4897204238024704) actually goes completely blank for me after it starts to render.

MacOS
Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by tvolkert** [comment]
@fkorotkov other comments:

1. It appears maybe I'm just not authenticated.  If I load the page in an incognito window, I can get it to render, but I don't see a way to sign in.

2. When it does render, it looks like maybe Cirrus is swallowing stderr?  e.g. if you search for `-1:` in the task page, you'll see the first test failure, but no associated error message.

**Comment by tvolkert** [comment]
> ...goes completely blank for me after it starts to render.

@fkorotkov removing the "local storage" cookies fixed this

**Comment by fkorotkov** [comment]
@tvolkert first of all, sorry for the inconvenience.

1. I've checked the logs and seems you've never authorized with Cirrus CI and it means that Incognito mode shouldn't change anything. I wonder what was in your cookies and **how** it got there.

2. Cirrus CI's agent combines stderr and stdout together. We have integration tests with Gradle output for that. We'll investigate Flutter's case and add tests.

Now you can sign-in via GitHub in the top right corner. I would Re-Run it but I don't have permissions. Only PR's author and people with write permissions to the repo can re-run tasks.

Once again, sorry for the troubles, and thanks for the feedback! I will investigate the issues.

**Comment by tvolkert** [comment]
@fkorotkov re <span>#</span>1, @Hixie reported the same behavior after he tried to expand the shelf on the left of the page.  I can reliably reproduce the failure by expanding the shelf as well.

If I look in the top right of the page, here's what I see:

cirrus

Yet if I hover over the area to the right of "Documentation", indeed it's a hidden link to authorize! 😄

**Comment by fkorotkov** [comment]
OMG. 😔Need to add some tests using Puppeteer.

**Comment by tvolkert** [comment]
btw @fkorotkov now that I'm authorized, the left shelf works fine, so it seems to be that there are problems when unauthenticated users try to expand the shelf.

**Comment by fkorotkov** [comment]
@tvolkert @Hixie found out why it was breaking for unauthorized users once they open the side panel with user's top repositories. Fix will be automatically deployed in ~5 minutes. Sorry for the inconvenience.

**Pull request merged**
