### PR TITLE
Fix: MaterialButton's shape

### PR DESCRIPTION
**Pull request by HeavenOSK**
## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change. If you're changing visual properties, consider including before/after screenshots (and runnable code snippets to reproduce them).*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by dnfield** [comment]
@fkorotkov - I'm not really sure why I'm seeing the error here - it's happening on all platforms though.

https://cirrus-ci.com/task/4696491242291200

**Comment by dnfield** [comment]
@HeavenOSK -

Thanks for the contribution.  Unfortunately, in its current state we can't really review this PR.  Please address the following before reopening:

- Either create a new issue or link to an existing one that this change addresses.
- Add a description of what this change does.
- Add a test that fails without this change and succeeds with it.
- Sign the CLA - see the instructions posted by @googlebot for more information.  We cannot accept contributions without a signed CLA.

I'm going to close this for now - please feel free to reopen once you've addressed those issues!

**Comment by dnfield** [comment]
@fkorotkov nevermind, I figured it out.  I need to guard accessing that env variable.

**Comment by HeavenOSK** [comment]
@dnfield Thanks you to reply. I’ll fix and reopen this PR. Your advice is very helpful for me because it’s my first commit in OSS.

**Comment by masashi-sutou** [comment]
@dnfield I have created an issue #29146 related to this fix. Please check the issue.

**Comment by HansMuller** [comment]
I created a new PR for this change - #29198. The fix is pretty much exactly what you had here; I just added a simple test. Thanks again for making this contribution to Flutter!

**Pull request closed without merging**
