### PR TITLE
[flutter_tools] Add flutter create-local-engine-repo

### PR DESCRIPTION
**Pull request by MeandNi**
According to [this PR](https://github.com/flutter/flutter/pull/44243), we can specify the repo path of the local engine artifact through `local-engine-repo`, but there is currently no way to create this repo path.

[This PR](https://github.com/flutter/engine/pull/14150) tries to do this at the time when the artifacts was builded, but it doesn't seem to work.

So I'm going to add a command like this: 

```shell
flutter create-local-engine-repo --local-repo-path=xxx --local-engine-src-path xxx/src --local-engine=android_debug_unopt
```

It will create a repo path in `local-repo-path`, which is especially useful in add-to-app scenarios.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by christopherfujino** [comment]
This looks related to your change (https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8775908197004019617/+/u/Analyze/analyze/test_stdout):

```
Analyzing Á flutter sdk...                                      

   info • Sort directive sections alphabetically • packages/flutter_tools/lib/executable.dart:20:1 • directives_ordering
   info • Local variables should be final • packages/flutter_tools/lib/src/commands/create_local_engine_repo.dart:39:5 • prefer_final_locals
   info • Local variables should be final • packages/flutter_tools/test/commands.shard/hermetic/create_local_engine_repo_test.dart:32:7 • prefer_final_locals
   info • Missing type annotation • packages/flutter_tools/test/commands.shard/hermetic/create_local_engine_repo_test.dart:62:7 • always_specify_types
```

**Comment by MeandNi** [comment]
> This looks related to your change (https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8775908197004019617/+/u/Analyze/analyze/test_stdout):↳
> 
> ```
> Analyzing Á flutter sdk...                                      
> 
>    info • Sort directive sections alphabetically • packages/flutter_tools/lib/executable.dart:20:1 • directives_ordering
>    info • Local variables should be final • packages/flutter_tools/lib/src/commands/create_local_engine_repo.dart:39:5 • prefer_final_locals
>    info • Local variables should be final • packages/flutter_tools/test/commands.shard/hermetic/create_local_engine_repo_test.dart:32:7 • prefer_final_locals
>    info • Missing type annotation • packages/flutter_tools/test/commands.shard/hermetic/create_local_engine_repo_test.dart:62:7 • always_specify_types
> ```

yes, Looks like I need to be careful.

**Comment by MeandNi** [comment]
why i still failed ci. @christopherfujino

**Comment by christopherfujino** [comment]
> why i still failed ci. @christopherfujino

Thanks for contributing this PR. Unfortunately, offering technical guidance to contributors is outside the scope of our code review process (and simply would not scale to the number of PRs that we receive).

**Comment by christopherfujino** [comment]
Thank you for contributing! As you have not responded within 3 weeks, I will be closing this PR as stale. If you are still interested in landing this, feel free to rebase this PR upstream, address code review feedback, and re-open this PR.

**Pull request closed without merging**
