### PR TITLE
update packages and unpin build

### PR DESCRIPTION
**Pull request by jonahwilliams**
Roll forward of https://github.com/flutter/flutter/pull/31795 now that the required version bump landed in fuchsia

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by tvolkert** [comment]
Marking `flutter update-packages` as experimental is preventing our packaging scripts from creating archives on stable branches.  Is there a reason it was made experimental?

**Comment by jonahwilliams** [comment]
It was done to prevent occurrences such as https://stackoverflow.com/questions/55525370/building-flutter-tool-because-flutter-tools-depends-on-sockjs-client-0-3-5-wh

It sounds like that isn't the right approach though...

**Comment by zanderso** [comment]
Was the issue with stable branches resolved?

**Comment by tvolkert** [comment]
I sent https://github.com/flutter/flutter/pull/35467 to make `update-packages` non-experimental.

**Comment by jonahwilliams** [comment]
Yes, this specific change was reverted

**Pull request merged**
