### PR TITLE
[O] Remove this README, which seems stray.

### PR DESCRIPTION
**Pull request by Hixie**
It's not clear why this directory has a README. It does weird things
on GitHub (e.g. it appears in the docs for parent directories).

### CODE REVIEW

**Comment by Hixie** [comment]
cc @goderbauer 
fyi @jcollins-g

**Comment by xster** [comment]
LGTM

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Apparently this is actually being used in theory by dartdoc though we later blow it away. I'll update the contents of the file instead of deleting it.

**Pull request closed without merging**
