### PR TITLE
Roll dart to 1.25.0-dev.4.0

### PR DESCRIPTION
**Pull request by goderbauer**
Picks up some fixes for how `pub` behaves with no internet connection (https://github.com/flutter/flutter/issues/10138).

### CODE REVIEW

**Review by tvolkert — APPROVED** [review]
LGTM, though we have to be careful not to depend on any new 1.25 API until Google's internal version has caught up with this.

**Comment by cbracken** [comment]
@tvolkert @pq, what was the reason we cut short the previous roll to 1.24 final?

**Comment by pq** [comment]
Hmmmm.  I'll defer to @tvolkert.  I can't remember what the exact issue was.  Sorry!

**Comment by tvolkert** [comment]
We did roll to `1.24.0` stable in #10931, and then it was rolled to `1.24.2` in #10985 to pick up analyzer fixes in the SDK.

**Pull request merged**
