### PR TITLE
driver: do not build APK twice

### LINKED ISSUE #8102: flutter drive appears to build the app twice
```
flutter/dev/benchmarks/complex_layout$ flutter drive --profile test_driver/scroll_perf.dart 
Using device Nexus 5.
Starting application: lib/main.dart
Building APK in profile mode (android-arm-profile)... 20.9s
Installing build/app.apk...                           4.4s
Building APK in profile mode (android-arm-profile)... 18.6s
Installing build/app.apk...                           4.7s
I/flutter (24075): Observatory listening on http://127.0.0.1:39658/
00:00 +0: scrolling performance test (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:8100/
[trace] FlutterDriver: Looking for the isolate
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
00:00 +0: scrolling performance test measure
00:09 +1: scrolling performance test (tearDownAll)
00:09 +1: All tests passed!
Stopping application instance.
```

/cc @yjbanov

### PR DESCRIPTION
**Pull request by yjbanov**
`command.device.startApp` already builds it.

Fixes #8102

@abarth

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
Thanks :)

**Comment by abarth** [comment]
Can we test this?  /cc @tvolkert

**Comment by tvolkert** [comment]
Yep, we should be able to using record/replay

**Comment by yjbanov** [comment]
Re testing - we run this regularly in the device lab, so it should be covered.

**Pull request merged**
