### PR TITLE
prefer_const_constructor in packages/flutter/test

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by Hixie** [comment]
This is fantastic. LGTM.

**Comment by chinmaygarde** [comment]
@Hixie can you merge this please.

**Comment by Hixie** [comment]
@a14n Is there a lint we should be turning on that catches these?

**Comment by a14n** [comment]
@Hixie there's a rule `prefer_const_constructor` but its PR (dart-lang/linter#342) not yet merged into master branch.

**Pull request merged**
