### PR TITLE
Fix import statements in flutter_tools

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

I thought we had a check for that? Or does the check only operate on package/flutter?

**Comment by Hixie** [comment]
Yeah it only operates on the flutter package.

**Comment by Hixie** [comment]
I'll add a test for this.

**Comment by Hixie** [comment]
Added test, PTAL.

**Review by goderbauer — APPROVED** [review]
Nice!

**Comment by Hixie** [comment]
Will land on green.

**Comment by Hixie** [comment]
This patch makes AppVeyor do more. I need to either make AppVeyor not run the analysis step or I need to fix why it doesn't work on Windows.

**Pull request merged**
