### PR TITLE
Use full textspan tree instead of top level textspan

### PR DESCRIPTION
**Pull request by GaryQian**
The TextSpan holds text as a tree of strings. It was incorrect usage of API to check only `_text.text`. This fixes it to use the full tree traversal through `TextSpan.toPlainText()`

### CODE REVIEW

**Comment by GaryQian** [comment]
cc @jslavitz This fixes the iOS caret bug you found yesterday.

**Review by goderbauer — COMMENTED** [review]
This will need a test :)

**Comment by justinmc** [comment]
+1 for a test.  Would that just be a double wide character before or after the cursor?  Otherwise it looks good to me and shouldn't interfere with my text painter work.

**Comment by jslavitz** [comment]
+2 for a test!

**Review by jslavitz — APPROVED** [review]
LGTM! Lets land this.

**Review by justinmc — APPROVED** [review]

**Pull request merged**
