### PR TITLE
Use the new path to the linter package

### PR DESCRIPTION
**Pull request by yyoon**
@abarth @ianloic @pylaligand

### CODE REVIEW

**Comment by sethladd** [comment]
Hi @Hixie and @danrubel can you either of you take a look? Thanks!

**Comment by yyoon** [comment]
FYI, there was a similar PR in dart sdk:
dart-lang/sdk#28062

**Comment by Hixie** [comment]
cc @jason-simmons

**Comment by Hixie** [comment]
I'm going to land this to unblock you since it seems fine but I'm not really the right reviewer.

RSLGTM
TBR @abarth

**Pull request merged**
