### PR TITLE
commit intellij project metadata

### LINKED ISSUE #38: make sure the plugin works well with the flutter repo
This one: https://github.com/flutter/flutter

From looking at it:

- we analyze things in `bin/cache/` (like the copy of the dart sdk), which we shouldn't
- we don't analyze the packages in `packages/` - the analysis server thinks those projects are within a symlink

### PR DESCRIPTION
**Pull request by devoncarew**
- commit intellij project metadata
- fix https://github.com/flutter/flutter-intellij/issues/38

@pq, would you mind patching this in locally? I've tried to make a good guess at which metadata files in `.idea/` to include and exclude, but would love to know if this project can open cleanly on another machine. Thanks!

### CODE REVIEW

**Comment by pq** [comment]
Define "cleanly" 😉 

I tried to "Create Project from Existing Sources..." for `flutter` and it opened but no Flutter or Dart natures...

Man, I love this direction though!

**Comment by devoncarew** [comment]
You should just need to open it - `File` > `Open`; the project already exists in `dev/intellij`.

**Comment by devoncarew** [comment]
Alternatively we could move the `.idea` folder up from `//dev/intellij/` to the repo root -

**Comment by pq** [comment]
Oh!  Much more promising...

screen shot 2016-10-06 at 8 40 44 am


Bonus points the gallery launch config even works!

Not sure what's up with the project structure which looks a bit odd but this is a BIG step in the right direction!  🎉

**Comment by pq** [comment]
FWIW if you want to land and iterate I'm good with that.  LGTM.

**Comment by devoncarew** [comment]
Perhaps the meta-data should be moved up to the top level; in any case, won't get a chance to land until later today.

**Pull request merged**
