### PR TITLE
Make the iOS syslog parser stateful to support multi-line log messages

### PR DESCRIPTION
**Pull request by TimNN**
Without this patch, only the first line of iOS log messages is printed, which is very annoying.

This patches changes the iOS log reader to be stateful: After successfully matching a log line from the runner app, all the following lines will also be captured until the start of a new log message is detected.

I would especially appreciate your thoughts on the new regex. It could, for example, be made more strict by also matching the timestamp at the beginning of log lines (e.g. `May  5 13:56:18`). In general, I don't know which parts of the log message can be considered stable between iOS versions (and maybe languages?). However the proposed regex seems to work well so far, for the short time I've been using the patched code.

### CODE REVIEW

**Comment by TimNN** [comment]
@cbracken / @xster: Is there anything I can / need to do to move this PR forward?

**Comment by chinmaygarde** [comment]
I'll ping them again.

**Comment by cbracken** [comment]
Have you tested against older versions of iOS (8, 9, 10?). I'll test this locally with iOS 8, 9, 10+ devices tonight. The log format changed in either 10.0 or 10.3 -- I can't remember which, but there should be some hints in `simulators.dart`. 

Once I dig it up, we can add a test for both formats. Thanks for the PR and apologies for the delay in reviewing.

**Comment by TimNN** [comment]
> Have you tested against older versions of iOS (8, 9, 10)?

No (I've only been experimenting a bit with Flutter on the latests iOS). I could set up a test app and additional simulators to try things. Let me know if you need that (although if you're testing on real devices, I imagine that is enough?).

> The log format changed in either 10.0 or 10.3 -- I can't remember which, but there should be some hints in `simulators.dart`.

There is a comment close to my diff about log format changes between 9.0 and 10.0. Are you referring to that change?

> Thanks for the PR and apologies for the delay in reviewing.

No problem, thanks for taking the time to review this now. 

---

Some analysis on ways this patch could cause "bad" log messages:

1) `anyLineRegex` fails to match an output line from the Flutter Runner: The line would still be printed, just with some additional "Junk" at the beginning.
2) `anyLineRegex` fails to match an output line from another App: One or more "uninteresting" lines from other apps are printed.
3) `anyLineRegex` matches legitimate log content e.g. `foo[0] <head>: 42` instead of the standard prefix: A multiline message is cut-off early.

Note that (1) can only happen if the Flutter Runner app name does not match `\w+$`.

Also, while not ideal, (3) is still an improvement over the current situation IMO.

**Comment by cbracken** [comment]
Manually tested on:
[x] iPhone 5 (iOS 8.3)
[x] iPhone 4S (iOS 9.3.5)
[x] iPhone 5 (iOS 10.3.3)
[x] iPod touch G6 (iOS 11.3.1)

Looks good!

There are some cosmetic differences for the second line, but I'll land a fix for those in a followup. 

Specifically, the following code:
```dart
print('This is a single-line comment');
print('This is a\nmulti-line comment');
```

Results in the following output on iOS 10.3.3 and iOS 11:
```
flutter: This is a single-line comment
flutter: This is a
multi-line comment
```

But the following on iOS 8.3 and iOS 9.3.5:
```
flutter: This is a single-line comment
flutter: This is a
	multi-line comment
```

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm

**Pull request merged**
