### PR TITLE
ModalBarrier and Drawer barrier prevents mouse events

### LINKED ISSUE #32915: Hover effects are incorrectly shown for all widgets under cursor.
## Screenshot:
vvvvv

## Steps to Reproduce
1. create a button in a scaffold
2. show a modal bottom sheet / open a side drawer / put two widgets on each other
3. hover the button even if it's not visible at all ( behind the drawer for example )
so the button get the hover effect too ,, but it shouldn't
and if you click , only the first one will receive the click (which is right ofc) 

```
```

[ظê?] Flutter (Channel master, v1.6.1-pre.36, on Microsoft Windows [Version 6.3.9600], locale en-US)

    ظت Flutter version 1.6.1-pre.36 at E:\Setups\FLUTTER\flutter
    ظت Framework revision 1f2972c7b6 (2 hours ago), 2019-05-17 10:44:08 -0700
    ظت Engine revision 065fe5b210
    ظت Dart version 2.3.1 (build 2.3.1-dev.0.0 5ffff98440)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ظت Android SDK at E:\Setups\Android
    ظت Android NDK location not configured (optional; useful for native profiling support)
    ظت Platform android-28, build-tools 28.0.3
    ظت ANDROID_HOME = E:\Setups\Android
    X Android SDK file not found: adb.
    ظت Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Android Studio (not installed)
    ظت Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[ظê?] IntelliJ IDEA Community Edition (version 2019.1)
    ظت IntelliJ at E:\Setups\JetBrains\IntelliJ IDEA Community Edition 2019.1.1
    ظت Flutter plugin version 35.3.3
    ظت Dart plugin version 191.7141.49

[ظê?] Connected device (2 available)
    ظت Windows ظت Windows ظت windows-x64 ظت Microsoft Windows [Version 6.3.9600]
    ظت web     ظت web     ظت web         ظت web

! Doctor found issues in 2 categories.

```
```

btw fixing this strange characters in the flutter doctor -v would be helpful too :)

### LINKED ISSUE #33679: Route should be opaque to MouseEnter/Exit events
## Description

As shown in the GIF below, when a pop up menu is shown, widgets on the lower route still reacts to MouseEnter/Exit events and shows hover effect, despite ignoring mouse click events.

## Expected
Maybe MouseEnter/Exit events should also obey the "opaque" flag?

## Environment
Framework: 56940b544

### PR DESCRIPTION
**Pull request by dkwingsmt**
## Description

This PR adds a full-container opaque `MouseRegion` to the following widgets in order to prevent widgets behind it reacting to mouse events:
- `ModalBarrier`
- The barrier of `Drawer`

Check out related issues to see reason of this change.

**How do I make sure they are all cases that need changing?** I searched `BlockSemantics` and they are the only usages.

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/32915
- Fixes https://github.com/flutter/flutter/issues/33679
  - The behavior is fixed for `ModalRoute` (which applies to most common cases), but not its superclasses.

## Tests

I added the following tests:

- Drawer hover test
- ModalBarrier prevents hover interactions with widgets behind it
- ModalBarrier does not prevent hover interactions with widgets in front of it
- an empty opaque MouseRegion is effective

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by shyndman** [comment]
Nice!

Have you considered adding this to `IgnorePointer` as well? (https://github.com/flutter/flutter/issues/35213)

**Comment by dkwingsmt** [comment]
@shyndman That needs a different approach. I'll do it in another PR. Thanks for reminding though.

**Comment by shyndman** [comment]
You're welcome. Happy to see these updates land. :)

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Pull request merged**
