### PR TITLE
Roll engine a76054f4b6fd..3f46cd267518 (4 commits)

### PR DESCRIPTION
**Pull request by engine-flutter-autoroll**
https://github.com/flutter/engine/compare/a76054f4b6fd...3f46cd267518

git log a76054f4b6fd..3f46cd267518 --date=short --no-merges --format='%%ad %%ae %%s'
2018-08-02 regis@google.com Roll Dart to b04def964c428ada007cca7ef6b4936001db965d (#5928)
2018-08-02 jamesderlin@users.noreply.github.com Add an explicit `-[FlutterViewController init]` implementation (#5924)
2018-08-02 37626415&#43;skia-flutter-autoroll@users.noreply.github.com Roll src/third_party/skia e43024a5bab7..64cc576b1fa7 (1 commits) (#5926)
2018-08-01 37626415&#43;skia-flutter-autoroll@users.noreply.github.com Roll src/third_party/skia ed8bc196bd56..e43024a5bab7 (1 commits) (#5925)

The AutoRoll server is located here: https://flutter-engine-flutter-roll.skia.org

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/&#43;/master/autoroll/README.md

If the roll is causing failures, please contact the current sheriff, who should
be CC&#39;d on the roll, and stop the roller if necessary.

### CODE REVIEW

**Comment by engine-flutter-autoroll** [comment]
@rmistry @liyuqian : New roll has been created by https://flutter-engine-flutter-roll.skia.org

**Comment by engine-flutter-autoroll** [comment]
I signed it!

**Comment by goderbauer** [comment]
@liyuqian I find the log of whats included in the roll hard to read. Maybe this can be changed to something more readable as seen in https://github.com/flutter/flutter/pull/20160?

**Comment by engine-flutter-autoroll** [comment]
Commit queue failed; closing this roll.

**Comment by rmistry** [comment]
The log follows the same format as our other autorollers eg: https://chromium-review.googlesource.com/c/chromium/src/+/1160788

It is automatically generated by "git log a76054f4b6fd..3f46cd267518 --date=short --no-merges --format='%%ad %%ae %%s'"

I personally think it is useful to include the date/author/commit-msg.

But, it is configurable here: https://skia.googlesource.com/buildbot/+/master/autoroll/go/repo_manager/github_repo_manager.go#256
if everybody feels the same way.

**Comment by liyuqian** [comment]
Be careful about the (#<pull-number>) link. It links to flutter/flutter
pull request but it's actually meant for flutter/engine pull request. You
can replace it with (flutter/engine#<pull-number>) to solve the problem.

**Comment by rmistry** [comment]
Ah that's unfortunate, I just noticed it.

**Comment by rmistry** [comment]
Filed https://bugs.chromium.org/p/skia/issues/detail?id=8222 for the autolink problem.

**Pull request closed without merging**
