### PR TITLE
[flutter_tools] separate concept of null safe language version from current language version

### PR DESCRIPTION
**Pull request by jonahwilliams**
The tool currently treats a missing language version as 2.12, the null safe version. This needs to be bumped to 2.13 for the next dart release. In general, we should find a way to automate this, without doing any runtime reading of the Dart SDK.

### CODE REVIEW

**Comment by jmagman** [comment]
We're not going to remember to bump this.  There's no way we can get this programmatically?

**Comment by jonahwilliams** [comment]
I agree -

We can get the language version from the dart version, I just need a bit more time to put it together

**Comment by jmagman** [comment]
> I agree -
> 
> We can get the language version from the dart version, I just need a bit more time to put it together

Got a tracking issue for that work, maybe add a TODO?  I can already see this getting dropped on the ground.

**Comment by jonahwilliams** [comment]
Totally, updated the PR to just do the work :)

**Review by jmagman — APPROVED** [review]
Dang that was fast.  Thanks!

**Pull request merged**
