### PR TITLE
Roll engine dependency forward

### PR DESCRIPTION
**Pull request by aam**
Pick up engine dart roll as well as few other changes that were done since last engine roll yesterday.

### CODE REVIEW

**Comment by goderbauer** [comment]
LGTM

**Comment by aam** [comment]
This is blocked on https://github.com/flutter/flutter/issues/12089.

**Comment by yjbanov** [comment]
Do we know why the aot_snapshot_size_isolate dropped by a half in Dart 2? Smaller code size is good, just want to make sure the drop was expected, that there's no regression lurking somewhere.

screen shot 2017-09-16 at 11 33 37 am

**Comment by aam** [comment]
This is as expected: https://github.com/dart-lang/sdk/issues/30616

**Comment by Hixie** [comment]
Looks like it also regressed flutter_gallery_ios__transition_perf missed_frame_build_budget_count.

**Pull request merged**
