### PR TITLE
iOS hasStrings and the clipboard notification

### LINKED ISSUE #60145: Unsolicited iOS14 clipboard permission prompt
At WWDC2020, Apple announced that it was cracking down on clipboard sniffing by showing a prompt when an app attempts to access the clipboard.  This likely means that Flutter apps that feature text input will trigger this at strange times.

As of https://github.com/flutter/flutter/pull/54902, Flutter began checking the clipboard contents to decide whether or not to show the paste button in the text selection menu.  Previously, it would always show the button, even when nothing pasteable existed in the clipboard.

When exactly are Flutter apps seeing this clipboard permission dialog?  What should we do about it?

Some options:

  1. Revert to the old behavior (show the paste button regardless of clipboard contents).
  1. Revert only for iOS, or only or iOS 14.  Provide the developer an option to enable the feature on iOS 14 anyway?

### PR DESCRIPTION
**Pull request by justinmc**
## Description

Uses the iOS [hasStrings](https://developer.apple.com/documentation/uikit/uipasteboard/1829416-hasstrings?language=objc) method that's being added in the engine in https://github.com/flutter/engine/pull/19859 to avoid iOS's clipboard notification.

## Related Issues

Closes https://github.com/flutter/flutter/issues/60145
Depends on https://github.com/flutter/engine/pull/19859
Depends on https://github.com/flutter/engine/pull/20393
Depends on https://github.com/flutter/engine/pull/20531 
Depends on https://github.com/flutter/engine/pull/21388 and more to come for other platforms

## Tests

I added the following tests:

TODO

## Breaking Change

None

### CODE REVIEW

**Comment by goderbauer** [comment]
PR triage: Looks like the engine side was submitted. Is this ready?

**Comment by justinmc** [comment]
No, I need to add hasStrings to all the other platforms in addition to iOS.  I have an Android PR at https://github.com/flutter/engine/pull/20393 and will follow up with the others.  I've added this to the description.

**Comment by Piinks** [comment]
Bad bot. :)

**Comment by justinmc** [comment]
This PR is hanging around for awhile while I finish all the engine dependencies, I'm probably confusing the bot.

**Comment by goderbauer** [comment]
PR triage update from @justinmc: "I need to do a PR for Windows and a PR for Fuchsia."

**Comment by justinmc** [comment]
Closing this for now until I have time to work on Windows and Fuchsia engine methods, at which point I'll reopen.

**Pull request closed without merging**
