### PR TITLE
Add tests to image_decoder_test.dart

### PR DESCRIPTION
**Pull request by lequem**
The last test fail. See comments for more informations.

### CODE REVIEW

**Comment by Hixie** [comment]
Thanks for submitting this.

**Comment by lequem** [comment]
I hope it will help. Do not hesitate if you have any question

**Comment by abarth** [comment]
Looks like one of tests timed out on Travis:

```
00:23 +632 ~2 -1: /home/travis/build/flutter/flutter/packages/flutter/test/services/image_decoder_test.dart: - Same test but with flutter_test framework
  TimeoutException after 0:00:05.000000: Test timed out after 5 seconds.
  dart:async                _StreamController.add
  websocket_impl.dart 1111  _WebSocketImpl._WebSocketImpl._fromSocket.<fn>
  dart:async                _EventSinkWrapper.add
  websocket_impl.dart 333   _WebSocketProtocolTransformer._messageFrameEnd
  websocket_impl.dart 228   _WebSocketProtocolTransformer.add
  
00:29 +780 ~2 -1: Some tests failed.                                                               
```

**Comment by lequem** [comment]
Yes, this test point out a problem with the flutter_test fwk. The dart main process is blocked and the test ends with a timeout.
You can read the test comment to have more details

**Comment by abarth** [comment]
Ah, makes sense.  Thanks!

**Comment by Hixie** [comment]
So I finally got around to checking out your branch and having a look. Sorry about the delay.

What's going on is that when you use testWidgets, which introduces a FakeAsync zone. You then await a Timer, but because you never call pump(), the clock doesn't move, so you're just stuck waiting on the timer with nothing happening.

We try to avoid anything in tests that actually takes time (like timers) because that slows down the tests. Having a FakeAsync zone allows us to advance time in a predictable way to test animations, without actually having to take real time.

HTH.

**Comment by lequem** [comment]
Thank you for your answer.
I have coded these tests with timers to point out this behavior because I have the same behavior when I want to test the evolution I have done about listeners on ImageNetwork (#5741)
I am going to explore the pump() solution.

Vincent.

**Comment by Hixie** [comment]
Great!

While you explore that, do you mind if we close your two PRs just to get them off the list of PRs awaiting review? You can of course reopen them whenever you are ready, it's just so that we can keep our list clear in the meantime.

**Comment by Hixie** [comment]
I am closing this PR since it is old and no progress is being made, to take it off our list of PRs that need review. Please reopen the PR when it is ready for review and checkin.

**Pull request closed without merging**
