### PR TITLE
Make subcommands return success instead of null

### PR DESCRIPTION
**Pull request by blasten**
## Description

These commands currently return `null`, which show as "unspecified" in the analytics.

## Tests

I added the following tests: unit test for the code that can be mocked.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by dnfield — COMMENTED** [review]
In `flutter_command.dart`, should we just add an assert that `commandResult != null` to the `run` method?

**Comment by blasten** [comment]
@dnfield Possibly. `null` is still a handled case, although I'm not sure if there's any valid use case for it.

**Comment by dnfield** [comment]
It seems like only the `FastFlutterCommand` which is documented as not using analytics would want it, right?

It also seems like whenever we go to NNBD, it'd just be better to avoid null here.

**Comment by zanderso** [comment]
Where is the null return handled? What does it mean?

**Comment by blasten** [comment]
@zanderso https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/reporting/events.dart#L174

**Comment by zanderso** [comment]
Huh, okay. I think I agree with Dan that we can assert that the command result is non-null. Looking at `FastFlutterCommand`, I'm doubtful that it really saves any time. It seems to be only used by `TestCommand` so I wonder if we can just remove it.

**Comment by blasten** [comment]
PTAL @zanderso

**Review by zanderso — APPROVED** [review]

**Pull request merged**
