### PR TITLE
Fixed bug where we could accidently call a callback twice.

### PR DESCRIPTION
**Pull request by gaaclarke**
## Description

In the case where we would overflow a buffer channel we would end up calling the callback twice.

## Related Issues

Related Issue: https://github.com/flutter/flutter/issues/42880

## Tests

I added the following tests:

WIP

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by gaaclarke** [comment]
WIP Let me see if I can come up with a unit test tomorrow.

**Comment by hterkelsen** [comment]
Also update the `BinaryMessenger` in `packages/flutter_web_plugins`

**Comment by gaaclarke** [comment]
I've added a test.  I'm not sure the best way to notify you that it's open for review.

**Comment by gaaclarke** [comment]
@yjbanov @hterkelsen friendly ping for review

**Comment by hterkelsen** [comment]
I'm worried that not calling the callback immediately on unrecognized channels could cause apps to hang. Currently, if there is no plugin that handles a message call, it will call the callback with `null` immediately, signalling that there was no handler. Now, the callback will not be called until the `ChannelBuffers` cache is drained (i.e., not until you receive another call to the same channel).

I can't find an example in the widgets where waiting forever on a platform call might cause the app to hang, however, so this may be an unwarranted fear.

**Review by harryterkelsen — APPROVED** [review]

**Review by yjbanov — APPROVED** [review]
LGTM if LGT @hterkelsen

**Pull request merged**
