### PR TITLE
DecorationImagePainter not paint when app switch background and foreg…

### PR DESCRIPTION
**Pull request by JsouLiang**
I found this issue is because of : when the iOS app entry background, the `CachingAssetBundle` is called `clear`, and this image is assert image in this case, if the the assert image is loaded, then the `AssetImage.obtainKey` call `chosenBundle.loadStructuredData` will return a `SynchronousFuture` in the `CachingAssetBundle` and then in the `ImageStreamCompleter` has `_currentImage` and `addListener` will set imager immediately, the whole flow is a synchronous flow. And if the `CachingAssetBundle` call `clear` the whole flow is a asynchronous flow, when the `DecorationImagePainter` handImage this object need mark need repaint.

## Pre-launch Checklist

- [x]  I read the [Contributor Guide] and followed the process outlined there for submitting PRs.

- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

Fix the issue: [flutter 2.8.0 BoxConstraints doesn't render image when app comes to foreground (ie when app life cycle goes from paused to resumed)](https://github.com/flutter/flutter/issues/95372)

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by WasserEsser** [comment]
This does not fix the issue at hand.

`DecorationImagePainter._handleImage` is being called with the `synchronousCall` parameter set to true, even when called asynchronously. That's the underlying issue that needs to be fixed. Your solution just fixes this one scenario, but the issue that the function gets called with wrong parameters still remains.

**Comment by JsouLiang** [comment]
> 

I this this problem is in the `DecorationImagePainter.paint` , if the `_image` is synchronous this method paint directly, but if the `_image` is async, we should `markNeedRepaint` when `_handleImage`
My solution is when `_handleImage` if the painter is not in painting, then we can paint `markNeedRepaint` and paint the image

**Comment by WasserEsser** [comment]
> > 
> 
> I this this problem is in the `DecorationImagePainter.paint` , if the `_image` is synchronous this method paint directly, but if the `_image` is async, we should `markNeedRepaint` when `_handleImage` My solution is when `_handleImage` if the painter is not in painting, then we can paint `markNeedRepaint` and paint the image

That is exactly what _handleImage is already doing. The logic of `paint` and `_handleImage` is correct and _does_ call the `markNeedPaint` if called asynchronously. The underlying issue is that the listener gets called with the `synchronousCall` parameter set to true even when it was called asynchronously. That's the issue that needs to be fixed.

Your PR ignores this issue and just paints when the image listener is being called later. It has the same effect as if the image listener was called with correct parameters, but doesn't fix the underlying issue. It's a band-aid fix.

**Comment by chunhtai** [comment]
as the @WasserEsser mentioned, this is not a complete fix. I am going to close this PR

**Pull request closed without merging**
