### PR TITLE
[roll] Revert "Fix `ExpansionTile` double tap to collapse/expanded and expanded/collapsed states semantics announcements"

### PR DESCRIPTION
**Pull request by XilaiZhang**
Reverts flutter/flutter#120881

This PR merges nodes in some tests where the change wasn't expected.
There might be a better way to do this. Will revert for now.

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
@TahaTesser This pr causes the entire expanded content and tile to merge. I think you can reproduce it when using something like a column with multiple text widget in the expanded content, and observe that the entire column will be merged after the pr

**Comment by TahaTesser** [comment]
> @TahaTesser This pr causes the entire expanded content and tile to merge. I think you can reproduce it when using something like a column with multiple text widget in the expanded content, and observe that the entire column will be merged after the pr

Thank you, I'll investigate it.

**Pull request merged**
