### PR TITLE
Revert "Roll engine 5b4b1f33c6d6..916f014d1cfb (24 commits)"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#54373

Bug fixes to the prefer_const_constructors lint has broken the customer testing shard. Temporarily reverting until we can fix all of the customer projects.

See:

https://api.cirrus-ci.com/v1/task/6328701516251136/logs/main.log

### CODE REVIEW

**Comment by jonahwilliams** [comment]
TBR @Hixie

**Comment by Hixie** [comment]
RSLGTM

**Comment by GaryQian** [comment]
What needs to be done to get the customer tests passing again? Engine roll will start to fall behind soon.

**Comment by GaryQian** [comment]
cc @cbracken who is roll sheriff this week

**Comment by Hixie** [comment]
@jonahwilliams is on it

**Comment by jonahwilliams** [comment]
I'm waiting on CI for https://github.com/flutter/tests/pull/34 then we should be good

**Comment by jonahwilliams** [comment]
The CI has landed, engine rolls should be able to land now

**Pull request merged**
