### PR TITLE
Fix interference in fling-scrolling from cross-axis motion

### LINKED ISSUE #120345: Fling-scrolling is slow unless you swipe precisely vertically
When trying to scroll rapidly through a list, the fastest you can go is much slower if you swipe at an angle and not straight up or down: about 15%-30% less initial speed, and 20%-50% less total distance on a single fling, for a range of likely angles.

Swiping at an angle is the most natural motion for many ways of using a phone, especially when using the thumb to scroll. And Android native scrolling (*) does not share this behavior: swiping at an angle can reach the same top speeds as swiping precisely vertically. As a result, many users are accustomed to scrolling this way, and the way an app responds when they do is their primary experience of trying to scroll in the app.

((*) I mention Android because that's where I've tested. It's possible that iOS or other platforms share Flutter's behavior here, or Android's, or do something else.)

This is one of several issues that combine to produce user feedback that scrolling feels sluggish and unresponsive in the default scrolling behavior used on Android. The symptoms naturally blend together until you investigate closely, so here's the others I know of for cross-reference:
* Another 15% reduction in total fling distance, affecting many scrolling lists: #120338
* Another 7% reduction, affecting all kinds of scrollables: #119875
* A thread for the overall symptom of all three issues (and possibly others) combined: #16371

## Steps to Reproduce

1. Run the [`platform_tests/scroll_overlay`](https://github.com/flutter/platform_tests/tree/1d797b8699546f1178e3cf58de9c6cc64f825281/scroll_overlay) app on an Android device. (This may be the same on iOS and other platforms too, but I haven't yet tested that.)
2. In `lib/main.dart`, delete the line `itemCount: 1000,`, in order to avoid #120338. Reload.
3. Scroll with a fling gesture: swipe rapidly upward and release. Wait a couple of seconds for the scroll to come to a stop.
   * Swipe just once, and swipe as precisely straight upward as possible, just like with #119875.
4. Observe how far the scroll went, as shown by the numbered items in the Android- and Flutter-driven scrolling lists.

5. Scroll back to the top.
6. Repeat step 2, but this time swipe up at an angle. For example, swipe rapidly from about the lower-left corner of the screen to the upper-right corner.
   * You may find this a much more natural gesture than swiping straight upward, especially if you use your thumb. (At least it is for me, and others I've observed with this repro.)
7. Repeat step 3.

**Expected results:** 

Swiping at top speed should cause the list to scroll equally far whether you do it straight vertically up (which can be natural when using the index finger) or up at an angle (which is natural when using the thumb, and in many postures with the index finger.)

**Actual results:** 

The Flutter list scrolls much less far when swiping at an angle than it does when swiping straight up.

The Android list, on the other hand, scrolls the same distance in both cases, or nearly so. (If it doesn't, try again but swiping faster. There's a certain maximum fling distance no matter how hard you swipe, and it's the same whether straight up or at an angle. The total numbers may get slightly smaller at an angle, because they include the initial portion when your finger was still on the screen performing a drag, and that part is shorter when at an angle.)

Specifically:
* Swiping straight up, I see "Android 94" and "Flutter 90" at the top of the screen. (The remaining discrepancy in this case is #119875.)
* Swiping diagonally up at roughly a 30-degree angle from vertical (from about one corner to the opposite corner, on my phone in portrait mode), I see "Android 93" next to "Flutter 78".
* Swiping diagonally up at roughly a 45-degree angle, I see "Android 90" next to "Flutter 51".

This represents about a 19% reduction in the 30-degree case and a 56% reduction in the 45-degree case, compared to straight up. (By my calculations, using the fact that item N is 40+N logical pixels high.)

<details>
  <summary>Logs</summary>

```
$ flutter analyze
Analyzing scroll_overlay...                                             
No issues found! (ran in 0.8s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel main, 3.8.0-8.0.pre.13, on Debian GNU/Linux 10 (buster) 4.19.0-23-amd64, locale en_US.UTF-8)
    • Flutter version 3.8.0-8.0.pre.13 on channel main at /home/greg/n/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2303f42250 (3 hours ago), 2023-02-08 14:24:12 -0500
    • Engine revision cc4ca6a06a
    • Dart version 3.0.0 (build 3.0.0-215.0.dev)
    • DevTools version 2.21.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/greg/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/greg/lib/android-studio-2020.3.1.24/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
    • cmake version 3.13.4
    • ninja version 1.8.2
    • pkg-config version 0.29

[✓] Android Studio (version 2022.1)
    • Android Studio at /home/greg/lib/android-studio-2020.3.1.24
    • Flutter plugin version 71.2.4
    • Dart plugin version 221.6096
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2021.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 71.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.0)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 08171FDD40025F • android-arm64  • Android 13 (API 33)
    • Linux (desktop)  • linux          • linux-x64      • Debian GNU/Linux 10 (buster) 4.19.0-23-amd64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by gnprice**
Fixes #120345.

The main change here is that when a single-axis DragGestureRecognizer (say, a VerticalDragGestureRecognizer) sees the end of a drag, it now projects the drag's velocity onto its own single axis, and then clamps that.  Previously it would clamp the velocity's magnitude as a 2D vector, and then consumers would project *that*, which resulted in clamping too hard when the motion wasn't precisely on-axis.

For PanGestureRecognizer, the behavior is unchanged: we continue clamping the velocity as a 2D vector, which is the geometrically nice behavior when we're not trying to focus on a single axis.

When I'd first looked at this code, I was concerned that fixing this issue might require a breaking change.  But happily I believe it doesn't, for two reasons:

 * This base class DragGestureRecognizer is effectively sealed (even though Dart doesn't quite yet have that feature), because it has private abstract methods.

   Dart won't actually stop you extending it, but that seems like a bug in Dart (*); when the class's own method implementations go try to call those methods, they'll produce runtime errors.  So it's not possible to subclass it in any useful way from outside the library, which means there are likely no such subclasses anywhere.  That means we can freely alter the API between the base class and its subclasses.

   (*) In fact, it's in the Dart tracker: https://github.com/dart-lang/sdk/issues/25462

 * We're also changing the behavior of the `onEnd` callback: previously it would return a DragEndDetails with a two-dimensional velocity, even for a single-axis recognizer, and now it returns a velocity that's always zero in the cross axis.  In principle that could be a breaking change; it's a bit odd for a VerticalDragGestureRecognizer to be telling you there was horizontal as well as vertical motion, but someone could nevertheless be depending on that.

   Fortunately, it turns out that the `onUpdate` callback's behavior already agrees with the view that that is an odd thing that shouldn't happen: it already returns an axis-locked velocity from single-axis recognizers.  So the existing `onEnd` behavior is inconsistent with that; and whatever someone might try to do with cross-axis velocity from `onEnd`, it seems like it'd be hard for them to be doing it successfully already when `onUpdate` isn't going along.  That makes me hopeful that nobody is depending on that behavior and we can freely clean it up.

Also add tests, not only for the changes but for the existing behavior: it turns out that the fancy 2-D clamping, which we keep for PanGestureRecognizer because it's helpful there, wasn't tested at all.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gnprice** [comment]
After this change, if you fling rapidly on Android, the distance the fling travels is a pixel-perfect match for the distance it would travel with a native Android list.

Previously #120420 made that true if you managed to swipe your finger precisely along the scroll axis with negligible cross-axis motion. With that PR now merged, this change makes it true even if you move your finger at an angle, which is the most natural motion for many ways of using a phone.

Here are before/after screen recordings, taken with the [`platform_tests/scroll_overlay`](https://github.com/flutter/platform_tests/tree/1d797b8699546f1178e3cf58de9c6cc64f825281/scroll_overlay) app on a Pixel 5 running Android 13:

| Before | After |
| --- | --- |
| <video src="https://user-images.githubusercontent.com/28173/224184187-e1f1e25e-71be-42d5-a409-bcf17391bb6c.mp4" /> | <video src="https://user-images.githubusercontent.com/28173/224184295-f3aeaabd-f110-4e12-aa32-7f9cac9568a2.mp4" /> |

**Comment by gnprice** [comment]
I say the match is pixel-perfect "if you fling rapidly" because if you make a less rapid fling, you can still get small differences.

I suspect this means that we're estimating a different velocity for the drag than Android is. Flinging rapidly means the velocity is large enough that it gets clamped, masking any such difference, so that this PR fixing the clamping behavior plus #120420 previously fixing the ensuing fling curve is enough to make the behavior match exactly.

Those remaining differences for slower flings are small, and I haven't debugged to work out the pattern of them. I'm also not yet sure they're enough to matter from a user perspective: they're easily noticed when using the `scroll_overlay` app, which is all about highlighting such differences, but I think they might be awfully subtle when simply using a scrollable in an app and the existing behavior (after this PR) may feel just fine.

**Comment by gnprice** [comment]
Windows tests failed with the flake #103230:
```
[   +1 ms] Evaluating project ':app' using build file 'C:\b\s\w\ir\x\w\flutter\examples\platform_view\android\app\build.gradle'.
[   +1 ms] Caching disabled for Kotlin DSL script compilation (Project/ScriptPlugin/stage1) because:
[        ]   Build cache is disabled
[        ] Skipping Kotlin DSL script compilation (Project/ScriptPlugin/stage1) as it is up-to-date.
[   +1 ms] FAILURE: Build failed with an exception.
[   +3 ms] * Where:
[        ] Script 'C:\b\s\w\ir\x\w\flutter\packages\flutter_tools\gradle\flutter.gradle.kts' line: 34
[        ] * What went wrong:
[        ] Failed to apply plugin class 'Flutter_gradle$FlutterPluginKts'.
[        ] > Comparison method violates its general contract!
[        ] * Try:
[        ] > Run with --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[        ] * Exception is:
[        ] org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin class 'Flutter_gradle$FlutterPluginKts'.
```

Re-running.

**Review by Piinks — APPROVED** [review]
This is excellent, thank you! LGTM!

**Pull request merged**
