### PR TITLE
[flutter_tools] switch flutter sdk to dart format

### PR DESCRIPTION
**Pull request by jonahwilliams**
Work towards https://github.com/flutter/flutter/issues/83822

Also makes flutter format forward everything to dart format without interpretation. 

--dry-run has been replaced with --output=show, work around this by translating the arg on the fly.

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by RedBrogdon** [comment]
@jonahwilliams, I believe this change just broke a dev channel CI routine of mine in which I was using `-n`. What's the correct setting for `--output` if I'd like stdout to get the names of files that would have been changed, but not a stream of the contents themselves?

**Comment by jmagman** [comment]
> @jonahwilliams, I believe this change just broke a dev channel CI routine of mine in which I was using `flutter format -n --set-exit-if-changed`. What's the correct setting for `--output` if I'd like stdout to get the names of files that would have been changed, but not a stream of the contents themselves (identical behavior to my old setup, in other words)?

Does this work?
```
$ flutter format  --show changed --set-exit-if-changed --output none .
```
Not very intuitive, I had to figure that out from reading https://github.com/dart-lang/sdk/issues/44023#issuecomment-724408397 and the `dart format -h -v` help.

**Comment by RedBrogdon** [comment]
Whoa. Why does `dart format --help` show a different number of flags and options than `dart format --help -v`?

**Comment by jmagman** [comment]
> Whoa. Why does `dart format --help` show a different number of flags and options than `dart format --help -v`?

Can't speak for `dart format` but `flutter` does that too, the `-v` verbose help shows the local engine flags, for example.

**Pull request merged**
