### PR TITLE
Reland Reland engine display features

### PR DESCRIPTION
**Pull request by andreidiaconu**
Previous reland was failing because the `gallery` repo also needed to be updated with compileSdkVersion 31 and new gradle lockfiles. There is a separate PR for this: https://github.com/flutter/gallery/pull/557

This reverts https://github.com/flutter/flutter/pull/93098 (commit 7779ad3c60a58caa96e571a979a20a37f50e2806).

List which issues are fixed by this PR:
- https://github.com/flutter/flutter/issues/49411
- Relands https://github.com/flutter/flutter/pull/89511

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by andreidiaconu** [comment]
The `gallery` compiles on my machine without adding multidex support. This was needed in the `flutter_gallery` copy that this repo contains, but the `gallery` repo seems to be a lot different at this point. The tests that failed on previous reland (referenced in https://github.com/flutter/flutter/pull/93098) should pass once https://github.com/flutter/gallery/pull/557 is merged.

@zanderso @blasten Please have a look. Thank you.

**Comment by andreidiaconu** [comment]
https://github.com/flutter/gallery/pull/557 was merged. The only failing check is `luci-flutter` and this PR should help make the tree green again.

**Comment by zanderso** [comment]
The tests that are now broken on the tree following the revert of the previous attempt to land this change should be made green before attempting to reland.

**Comment by andreidiaconu** [comment]
The tree was red before that merge and revert but I agree with making the tree green a priority. Opening a separate PR with just that fix.

**Comment by andreidiaconu** [comment]
Separate PR with just the failing test fix: https://github.com/flutter/flutter/pull/93136

**Comment by andreidiaconu** [comment]
Reverted one of the commits https://github.com/flutter/flutter/pull/93117/commits/6b17477b41f947980c042fcf0ba96ceed8b5f048, as it is no longer needed, due to https://github.com/flutter/flutter/pull/93148

**Review by blasten — APPROVED** [review]
LGTM

**Pull request merged**
