### PR TITLE
[Fonts] Update icons

### LINKED ISSUE #88852: [Proposal] Add Missing Material icons
## UseCase: 

This issue is a consolidated proposal to add missing material icons 

## Proposal

Please add the missing Material icons

- [ ] Icons.free_cancellations https://github.com/flutter/flutter/issues/88852
- [ ] Icons.wechat icon https://github.com/flutter/flutter/issues/89619
- [ ] Icons.route_outlined https://github.com/flutter/flutter/issues/89684
- [ ] Icons.medication_liquid https://github.com/flutter/flutter/issues/91577
- [ ] Icons.edit_calendar https://github.com/flutter/flutter/issues/88852#issuecomment-954501168
- [ ] Icons.arrow_circle_left_outlined https://github.com/flutter/flutter/issues/93383
- [ ] Icons.heart_broken https://github.com/flutter/flutter/issues/93920
## Icons

<details>
<summary>images</summary>

### Icons.edit_calendar

</details>

### LINKED ISSUE #91553: Stop icons from Icons class don't show "stop" icon inside
I have tried different stop icons from Icons class but none of them shows the square inside.
- stop_circle
- stop_circle_rounded
- stop_circle_sharp

### LINKED ISSUE #95238: Material "Balance" Icon is not implemented by Flutter
`Icons.balance` is not present in the Flutter API, proof: https://api.flutter.dev/flutter/material/Icons-class.html.
Icon: https://fonts.google.com/icons?selected=Material%20Icons%3Abalance%3A

### PR DESCRIPTION
**Pull request by guidezpl**
This PR adds 1028 new icons. 

Starting with this update and going forward, existing codepoints will be stable between updates. This has the nice side effect of making diffs readable. There is one exception for this particular update for `wifi_tethering_error_rounded_sharp` and `wifi_tethering_error_rounded_outlined`.

Closes #88852
Closes #91553
Screen Shot 2021-12-10 at 13 47 44
Closes #95238

### CODE REVIEW

**Review by rami-a — APPROVED** [review]
LGTM

**Comment by guidezpl** [comment]
As per previous icon updates, `Google testing` check is expected to fail and can be safely ignored.

**Comment by bernaferrari** [comment]
I'm curious about Adobe that was added but isn't on the official website and Facebook that got removed from Google Fonts.

**Comment by TerryJoo** [comment]
Please tell me how to use it.

**Pull request merged**
