### PR TITLE
Better debugPaintSize logic for clip renderers

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
Fixes https://github.com/flutter/flutter/issues/8884

**Review by goderbauer — APPROVED** [review]
Test? :)

**Comment by Hixie** [comment]
What do you want me to test? :-)

I considered adding one, but I wasn't sure what to test exactly. I could vaguely check that something gets painted, but it's not clear what that gets us.

**Comment by Hixie** [comment]
Landing on red because redness appears to be flaky.

**Pull request merged**
