### PR TITLE
Revert "Override MediaQuery for WidgetsApp"

### PR DESCRIPTION
**Pull request by renyou**
Reverts flutter/flutter#81295

This breaks internal tests. test/OCL:380874320:BASE:381245548:1624543113950:7fda35d8

### CODE REVIEW

**Comment by Piinks** [comment]
FYI to author @atoka93

**Review by Piinks — APPROVED** [review]
LGTM to revert

**Comment by atoka93** [comment]
@renyou @Piinks is there any way to re-land it later on? Can I fix the test/s?

**Comment by Piinks** [comment]
> @renyou @Piinks is there any way to re-land it later on? Can I fix the test/s?

Hey @atoka93 if you can re-open this change as a new PR, we can look at the failing tests and discuss changes to make it not breaking. Feel free to ping me on the new PR. :)

**Comment by zs-dima** [comment]
Why so important commit had been reverted back ?
And still not in stable for so long time ?

**Pull request merged**
