### PR TITLE
Add 3-letter language codes that don't have 2-letter alternative

### LINKED ISSUE #92818: ARB files with 3-letter language codes
`gen-l10n` does not accept `.arb` files with 3-letter (alpha3-b and alpha3-t) language codes.

In [ubuntu-desktop-installer](https://github.com/canonical/ubuntu-desktop-installer), we would like to include languages such as "ast" and "szl". For reference, here's the full list of languages supported by the old Ubiquity installer: https://git.launchpad.net/ubiquity/tree/d-i/source/localechooser/languagelist.

In https://github.com/flutter/flutter/pull/60185, a check was added that `.arb` language codes must on the list of ISO 639-1 alpha2 language codes. Since then, the list was already hand-edited to include a couple of ISO 639-2 alpha3-b codes (fil=filipino, gsw=swiss german) which happen to be used by the Flutter gallery: flutter/flutter#60632. However, there are plenty of other languages on the alpha3-b and alpha3-t code lists that don't have an alpha2 code.

See ["language-codes-full"](https://datahub.io/core/language-codes#resource-language-codes-full) at datahub.io, where Flutter's alpha2 code list was originally taken from.

## Steps to Reproduce

1) Clone [gen_l10n_example](https://github.com/flutter/website/tree/main/examples/internationalization/gen_l10n_example)
2) Create `lib/l10n/ast_ES.arb` (e.g. copy one of the existing ARB files to `app_ast_ES.arb`)
3) Run `flutter gen-l10n`:
  ```
  Multiple arb files with the same 'es' locale detected. 
  Ensure that there is exactly one arb file for each locale.
  ```
4) Try being more explicit and add `"@@locale": "ast_ES"` to `ast_ES.arb`:
  ```
  The locale specified in @@locale and the arb filename do not match. 
  Please make sure that they match, since this prevents any confusion 
  with which locale to use. Otherwise, specify the locale in either the 
  filename of the @@locale key only.
  Current @@locale value: ast_ES
  Current filename extension: es
  ```

<details>
<summary>Code sample</summary>

gen_l10n_example/lib/l10n/app_ast_ES.arb:
```json
{
    "@@locale": "ast_ES",
    "helloWorld": "¡Hola Mundo!"
}
```
</details>

<details>
  <summary>Logs</summary>

Without `@@locale`:
```bash
$ cat lib/l10n/app_ast_ES.arb 
{
    "helloWorld": "¡Hola Mundo!"
}

$ flutter gen-l10n 
Because l10n.yaml exists, the options defined there will be used instead.
To use the command line arguments, delete the l10n.yaml file in the Flutter project.


Multiple arb files with the same 'es' locale detected. 
Ensure that there is exactly one arb file for each locale.
```

With `"@@locale": "ast_ES"`:
```bash
$ cat lib/l10n/app_ast_ES.arb 
{
    "@@locale": "ast_ES",
    "helloWorld": "¡Hola Mundo!"
}

$ flutter gen-l10n 
Because l10n.yaml exists, the options defined there will be used instead.
To use the command line arguments, delete the l10n.yaml file in the Flutter project.


The locale specified in @@locale and the arb filename do not match. 
Please make sure that they match, since this prevents any confusion 
with which locale to use. Otherwise, specify the locale in either the 
filename of the @@locale key only.
Current @@locale value: ast_ES
Current filename extension: es
```

The issue is reproducible with both the stable and the master channel.

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 21.10 5.13.0-20-generic, locale en_US.UTF-8)
    • Flutter version 2.5.3 at /home/jpnurmi/.fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/jpnurmi/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /home/jpnurmi/Android/Sdk
    • Java binary at: /home/jpnurmi/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 13.0.0-2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/jpnurmi/Android/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.27.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 21.10 5.13.0-20-generic

• No issues found!
```

```
$ flutter doctor -v
[✓] Flutter (Channel master, 2.6.0-12.0.pre.535, on Ubuntu 21.10 5.13.0-20-generic, locale en_US.UTF-8)
    • Flutter version 2.6.0-12.0.pre.535 at /home/jpnurmi/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 04156b6636 (2 days ago), 2021-10-29 18:29:31 -0700
    • Engine revision 3a0a63c2d2
    • Dart version 2.15.0 (build 2.15.0-262.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/jpnurmi/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_SDK_ROOT = /home/jpnurmi/Android/Sdk
    • Java binary at: /home/jpnurmi/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 13.0.0-2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/jpnurmi/Android/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.27.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 21.10 5.13.0-20-generic

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/92818

Some tests might fail as this needs to be merged after https://github.com/flutter/flutter/pull/93401, it has a fix for where @@locale needs to match file name and fallback class.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by HansMuller** [comment]
Will review once this PR has been sync'd up with #93401

**Comment by jpnurmi** [comment]
The `_iso639Languages` set, which is now a mixture of ISO-639-1 alpha2 and ISO-639-2 alpha3-b codes, is getting quite long even if alpha3-t codes were left out? I'm not sure if this approach is sustainable because according to [iso.org](https://www.iso.org/iso-639-language-codes.html), ISO-639 is composed of five different parts. Where do you draw the line? For example, Ubiquity's [language list](https://git.launchpad.net/ubiquity/tree/d-i/source/localechooser/languagelist) contains two ISO-639-3 codes (ckb, szl) that are not included in this PR.

Would it be possible to use the basename of the template .arb file to determine the locale part of other .arb files? As for the locale part, would it be good enough if `intl` is able to parse it?

**Comment by christopherfujino** [comment]
@TahaTesser is this PR unblocked now?

**Comment by TahaTesser** [comment]
@christopherfujino 
Yes, I am trying to land https://github.com/flutter/flutter/pull/93855 first so i can proceed with this

**Comment by christopherfujino** [comment]
this is still blocked by https://github.com/flutter/flutter/pull/93855

**Pull request closed without merging**
