### PR TITLE
Update engine revision.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by chinmaygarde** [comment]
But I am still throwing stuff against the bot to see what sticks.

**Comment by chinmaygarde** [comment]
Done. Rebased.

**Comment by yjbanov** [comment]
FYI, beginning with this change the flutter_gallery_ios__transition_perf test started failing consistently and with a new error message (usually it's flaky due to corrupted timeline data; now it fails to connect to observatory altogether). The most suspicious thing I see in the log is this:

```
[INFO:../../flutter/shell/gpu/gpu_surface_gl.cc(86)] Failed to setup GL context. Aborting.
[INFO:../../flutter/shell/gpu/gpu_surface_gl.cc(87)] 
         Vendor: Apple Inc.
       Renderer: Apple A8 GPU
        Version: 2.0 Apple ES
```

More: https://flutter-dashboard.appspot.com/build.html

**Comment by chinmaygarde** [comment]
@yjbanov The shell needs to be passed the `--non-interactive` flag.

**Comment by eseidelGoogle** [comment]
Out of curiosity @chinmaygarde: What would cause a physical device to fail to set up a GL context like that?  Screen being off?  Surely we support that GPU? :)

**Comment by chinmaygarde** [comment]
@yjbanov is running the device on the desktop shell. It could be that the shell was being torn down too early but the setup of the GL context not aborted. This might be the cause of the intermittent errors earlier.

**Comment by eseidelGoogle** [comment]
I'm not sure what "running the device on the desktop shell" means. (My understanding is "Apple A8 GPU" is an iPhone.)  But also trust that you two know what's going on. :)

**Comment by chinmaygarde** [comment]
> But also trust that you two know what's going on

No. I am wrong :(

Don't know why context setup would fail. Would need more logs or a repro case.

**Comment by tvolkert** [comment]
Yeah this looks related to #6997

**Pull request merged**
