### PR TITLE
Update keyboard view when keyboardType has changed.

### PR DESCRIPTION
**Pull request by Yodesoft**
This commit fixes the keyboard view is not following keyboardType dynamically.

All done in function of didUpdateWidget , when the keyboardType has changed, close current input connect then open a new input connection to update keyboard view.

Videos for the case.

Incorrect behavior before fixes
https://user-images.githubusercontent.com/2268115/236105957-03854a41-746b-44fe-aa91-5a56f2d1273c.mp4

Correct behavior after fixes.
https://user-images.githubusercontent.com/2268115/236105975-d68ca108-410e-47b3-a4cc-f3b7ca9e17f2.mp4

### CODE REVIEW

**Comment by justinmc** [comment]
@cbracken I think the correct solution here is again to sync TextInputConfiguration with the engine, would you agree?

I remember a very similar thing came up with obscureText.  We said that we'd like to sync everything in TextInputConfiguration with the engine when it changes, but I think in the meantime we just did only obscureText.  See https://github.com/flutter/flutter/issues/122300#issuecomment-1467169720.

And here's the obscureText PR, which solves the similar problem by syncing the TextInputConfig instead of restarting the connection: https://github.com/flutter/flutter/pull/122383

**Comment by Yodesoft** [comment]
> @cbracken I think the correct solution here is again to sync TextInputConfiguration with the engine, would you agree?
> 
> I remember a very similar thing came up with obscureText. We said that we'd like to sync everything in TextInputConfiguration with the engine when it changes, but I think in the meantime we just did only obscureText. See [#122300 (comment)](https://github.com/flutter/flutter/issues/122300#issuecomment-1467169720).
> 
> And here's the obscureText PR, which solves the similar problem by syncing the TextInputConfig instead of restarting the connection: #122383

The solution what i found is restarting the connection, but i not sure what's the correct solution.
Follow you comments, i tested updateConfig in didUpdateWidget with below code snippet.

`   
 if (_hasInputConnection && oldWidget.keyboardType != widget.keyboardType) {
      _textInputConnection!.updateConfig(textInputConfiguration);
    }
`
Unfortunately, it's not effect to update keyboard view, maybe i missed some details and need to do more works.

**Comment by justinmc** [comment]
That's probably because the engine isn't set up to update keyboardType when updateConfig is called.  The PR I mentioned above also needed an engine PR (https://github.com/flutter/engine/pull/40216) to allow it to update obscureText on iOS.

**Comment by goderbauer** [comment]
(triage) Looks like the engine PR mentioned above got merged. Are there still plans to continue working on this PR?

**Comment by goderbauer** [comment]
(Triage): Closing this since there has not been any follow-up. Feel free to reopen if you find the time to work on this again. Thanks.

**Pull request closed without merging**
