### PR TITLE
Added implementation for a Finder that can find Types by searching for some IconData

### PR DESCRIPTION
**Pull request by bramvbilsen**
This makes it easy to test `IconButton`s but of course also makes it easier to just find a widget with an `Icon` in.

### CODE REVIEW

**Comment by bramvbilsen** [comment]
I signed it!

**Comment by Hixie** [comment]
can you use find.ancestor combined with a find.byIcon?

**Comment by bramvbilsen** [comment]
@Hixie I'm pretty sure you can but I followed the design choices of the `_WidgetWithTextFinder` class.

**Comment by bramvbilsen** [comment]
I do not see why these checks fail though. I do not see any duplicate method name?

**Comment by Hixie** [comment]
Well what I meant was do we really need these new features? If it can be done as a one-liner, you could put that in your unit test file directly, or in a utility library.

**Comment by bramvbilsen** [comment]
@Hixie I found it useful. And I guess it makes sense because it is implemented for `Text` widgets.

**Comment by Hixie** [comment]
I'm not sure we should have added "widgetWithText" either.

**Comment by Hixie** [comment]
Maybe we can have both `find.widgetWithText` and `find.widgetWithIcon`, but implement them as one liners, which at least would keep the implementation simpler?

**Comment by Hixie** [comment]
@bramvbilsen What do you think of the most recent suggestion?

**Comment by bramvbilsen** [comment]
@Hixie you are correct for sure! I stopped following this because I saw someone else had made a pull request on the same day as me with the same implementation. That's why the pull request were failing. Not sure if anything about that changed?

**Comment by Hixie** [comment]
Huh, go figure. I somehow hadn't noticed and I even commented on the other PR.

Well if you're interested in simplifying the implementation I would certainly support that, but if you're not interested in that (and I wouldn't blame you) then feel free to close the PR! Thanks!

**Comment by Hixie** [comment]
I'm going to close this PR per my last comment, but please feel free to file a new one if you did want to do the simplification mentioned above! Thanks again for your contribution!

**Pull request closed without merging**
