### PR TITLE
Use Integer instead of int in map in flutter.groovy 

### LINKED ISSUE #141897: [packages][ci] Flutter-Packages roller stuck with groovy error.
### Type of Request

infra task

### Infrastructure Environment

Flutter-Packages autoroller.

### What is happening?

The `master` auto-roller is failing consistently with:

```
FAILURE: Build failed with an exception.

* Where:
Script '/b/s/w/ir/x/w/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 168

* What went wrong:
Could not compile script '/b/s/w/ir/x/w/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy'.
> startup failed:
  script '/b/s/w/ir/x/w/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy': 168: primitive type parameters not allowed here;
     solution: use the corresponding wrapper type, such as Integer for int @ line 168, column 41.
     e static final Map<String, int> ABI_VERS
                                   ^

  1 error
```

### Steps to reproduce

Attempt a `master` merge into packages, like here:

https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_build_all_packages%20master/5504/overview

### Expected results

n/a

### PR DESCRIPTION
**Pull request by reidbaker**
packages Roller breakage 
https://ci.chromium.org/ui/p/flutter/builders/try/Linux_android%20android_build_all_packages%20master/5504/overview
Fixes flutter/flutter/issues/141897
```
FAILURE: Build failed with an exception.

* Where:
Script '/b/s/w/ir/x/w/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 168

* What went wrong:
Could not compile script '/b/s/w/ir/x/w/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy'.
> startup failed:
  script '/b/s/w/ir/x/w/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy': 168: primitive type parameters not allowed here;
     solution: use the corresponding wrapper type, such as Integer for int @ line 168, column 41.
     e static final Map<String, int> ABI_VERS
```

Covered by tests in packages. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by gmackall — APPROVED** [review]

**Comment by matanlurey** [comment]
test-exempt: tested by the fact the packages roller will now work (it is broken at HEAD).

... though as @reidbaker pointed out on Discord, it could be tested by:

> writing a test in framework that uses the abi version rolling code

He'll file a bug for that.

**Review by ditman — APPROVED** [review]
RSLGTM!

**Comment by reidbaker** [comment]
> test-exempt: tested by the fact the packages roller will now work (it is broken at HEAD).
> 
> ... though as @reidbaker pointed out on Discord, it could be tested by:
> 
> > writing a test in framework that uses the abi version rolling code
> 
> He'll file a bug for that.

https://github.com/flutter/flutter/issues/141899

**Comment by reidbaker** [comment]
https://github.com/flutter/packages/pull/5948/checks?check_run_id=20673122973 
Proof the roller issue behind the issue is passing. https://github.com/flutter/packages/pull/5948/checks?check_run_id=20673122973

**Pull request merged**
