### PR TITLE
Move Brightness to dart:ui in the engine (#27479).

### PR DESCRIPTION
**Pull request by matthew-carroll**
Moves Brightness to the engine. This PR simply re-exports Brightness from system_chrome.dart to stay backwards compatible.

Engine PR is here:
https://github.com/flutter/engine/pull/7678

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Comment by rostopira** [comment]
Now using master `Brightness` can't be resolved

**Comment by matthew-carroll** [comment]
@rostopira I'm not sure what you mean by master Brightness.  Can you provide sample code that shows the issue?

**Comment by rostopira** [comment]
@matthew-carroll thanks for quick response
I meant master branch, missed word
Code is pretty simple
```
theme: new ThemeData(
        brightness: Brightness.dark,
```
Intellij IDEA says "Undefined name 'Brightness'"

**Comment by matthew-carroll** [comment]
Ok, for now can you deal with that by importing Brightness

`import 'dart:ui' show Brightness;'

I'll look at putting up a PR tomorrow that gets Brightness back in Material or wherever it was coming from previously.

**Comment by matthew-carroll** [comment]
You mentioned that you're importing "dart:ui", that should include Brightness.  Again, I'll look in tomorrow, but I thought "dart:ui" was correctly exporting it.

**Comment by rostopira** [comment]
@matthew-carroll yeah, `IsolateNameServer` import is broken as well.
Confirmed working:
```dart
import 'dart:ui' show Brightness, IsolateNameServer;
```

**Comment by matthew-carroll** [comment]
@rostopira so is everything working for you now, or are you still experiencing issues?

**Pull request merged**
