### PR TITLE
Move tools tests into a general.shard directory in preparation to changing how we shard tools tests

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
cc @dnfield @tvolkert @jonahwilliams @zanderso

**Review by tvolkert — APPROVED** [review]

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
I don't really understand why codecov thinks this reduced coverage. All it did is move tests around.

**Comment by jonahwilliams** [comment]
The "impacted files" diff is bogus, but the top level coverage diff is generally accurate.

**Comment by Hixie** [comment]
full report looks pretty bogus to me. e. g. first supposed change is to a const declaration.

**Pull request merged**
