### PR TITLE
use isEmpty and isNotEmpty

### PR DESCRIPTION
**Pull request by a14n**
Follow [_Don't use length to see if a collection is empty_](https://www.dartlang.org/guides/language/effective-dart/usage#dont-use-length-to-see-if-a-collection-is-empty) rule of [Effective Dart](https://www.dartlang.org/guides/language/effective-dart/usage)

### CODE REVIEW

**Comment by Hixie** [comment]
I thought we had a lint that would catch these. Is it broken or something? How did we miss them?

**Comment by Hixie** [comment]
LGTM but I'm concerned that the lint isn't working.

**Comment by Hixie** [comment]
@pq, any idea why the lint didn't catch these?

**Comment by pq** [comment]
> @pq, any idea why the lint didn't catch these?

At first no and then I looked closer and it turns out the lint is only checking for: `!foo.isEmpty` and *not* the more obvious `foo.length != 0`.  (The name is actually a tip-off: `prefer_is_not_empty`.  Looks like we should have a `prefer_is_empty` too or have an uber-lint that handles both checks.)  Net-net: this *is* confusing.  We should fix it!

**Comment by pq** [comment]
Linter tracking issue opened: https://github.com/dart-lang/linter/issues/363.

**Pull request merged**
