### PR TITLE
Simplify mark needs build

### PR DESCRIPTION
**Pull request by goderbauer**
This simplifies some methods in `framework.dart` a bit.

From what I can tell, the `_debugAllowIgnoredCallsToMarkNeedsBuild` check wasn't actually used for anything. It was checked in the code snippet below in line 4532. However, in all cases were it was true, `debugIsInScope` just before it would also return true. In other words, the `debugIsInScope` check is more comprehensive and already considers the condition covered by `_debugAllowIgnoredCallsToMarkNeedsBuild`. Therefore `_debugAllowIgnoredCallsToMarkNeedsBuild` isn't really needed. Ripping it out removes one extra special case (and thus mental overhead) when trying to understand under what conditions `markNeedsBuild` may be called.

https://github.com/flutter/flutter/blob/e05ae3cac799b26c36405f8bfdda2a15c2298b68/packages/flutter/lib/src/widgets/framework.dart#L4529-L4534

To prove that everything `_debugAllowIgnoredCallsToMarkNeedsBuild` was supposed to enable (see snippet below) still works without it, I added some extra tests for these scenarios.

https://github.com/flutter/flutter/blob/e05ae3cac799b26c36405f8bfdda2a15c2298b68/packages/flutter/lib/src/widgets/framework.dart#L4500-L4504

From some historic digging, the more comprehensive `debugInScope` check was added after `_debugAllowIgnoredCallsToMarkNeedsBuild` was already in place in https://github.com/flutter/flutter/commit/fbf8174c87eb4cab85d0ebf43f672cb8493c63da.

### CODE REVIEW

**Comment by goderbauer** [comment]
If my analysis above is wrong, this change will cause more exceptions because the "setState() or markNeedsBuild() called during build." is no longer guarded by the `_debugAllowIgnoredCallsToMarkNeedsBuild` flag. I will run this through google3 to see if it surfaces any new and unexpected exceptions.

**Comment by goderbauer** [comment]
A global presubmit in google3 with this change is passing (tap/463417112).

(Ignore the Google testing check below, frob pulled in an unrelated PR that caused the failures there.)

**Comment by goderbauer** [comment]
@Hixie Since this is touching some vintage code, could you review this one?

**Review by Hixie — APPROVED** [review]
LGTM

**Pull request merged**
