### PR TITLE
Ensure that ios-deploy meets minimum version constraint

### PR DESCRIPTION
**Pull request by cbracken**
Also emits the version information in flutter doctor output.

ios-deploy > 1.9.0 is required to deploy to iOS devices.

### CODE REVIEW

**Comment by cbracken** [comment]
@xster

**Comment by tvolkert** [comment]
Tests?  You could call `IOSWorkflow.validate()` in a context that has a ReplayProcessManager set on it.

**Comment by cbracken** [comment]
@tvolkert I suspect I can actually add tests without faking out processes since almost all the process launches are behind getters that return stdout, but it'll take some refactoring due to e.g. use of global vars like Xcode.instance right now.

Will follow up with that work immediately after this CL so as to keep the refactoring separate from this change.

**Comment by xster** [comment]
LGTM

**Comment by tvolkert** [comment]
LGTM

**Comment by sethladd** [comment]
Thanks @cbracken !

**Pull request merged**
