### PR TITLE
Fix analyzer issues for onReportTiming to frameTiming

### PR DESCRIPTION
**Pull request by iskakaushik**
Filed: https://github.com/flutter/flutter/issues/38838
to track these usages.

This was introduced by: https://github.com/flutter/engine/pull/11041

### CODE REVIEW

**Comment by jonahwilliams** [comment]
cc @mehmetf 

Won't this also trip analyzer warnings in fuchsia-source and google?

**Comment by iskakaushik** [comment]
@jonahwilliams true. I'll leave it to @liyuqian to decide on the best next steps here.

**Review by liyuqian — APPROVED** [review]
LGTM!

**Comment by liyuqian** [comment]
Considering that the commit is already in the framework, I think this PR is the fastest way to fix the tree.

@jonahwilliams @mehmetf @cbracken @stuartmorgan : For the next Google3 and Fuchsia roll, we need to apply the `ignore: deprecated_member_use` to whereever `onReportTimings` is used.

**Comment by liyuqian** [comment]
Because that requires a more detailed PR (https://github.com/flutter/flutter/pull/38861), and this PR aims at making the tree green as soon as possible.

But thank you for the ping! I just realized that the tree is green so I'm going to merge https://github.com/flutter/flutter/pull/38861 . That's going to use the new API.

**Pull request merged**
