### PR TITLE
add autofocus to fix a11y issue with dialog

### PR DESCRIPTION
**Pull request by DBowen33**
Add autofocus=true to first TextButton in dialog so that focus automatically goes to an interactive element when dialog is opened.

Before: https://screencast.googleplex.com/cast/NTYxNTczMTk2MDk3MTI2NHxlMjAyOTMzZi1lNw
After: https://screencast.googleplex.com/cast/NTk1NzMxNjYxNTYwMjE3NnxlYWNlM2Q1MC1jYw

fixes b/338656477

NOTE: This would be a good candidate to update the documentation for Dialogs and TextButtons to encourage the user to add autofocus=true on at least one button so that focus automatically goes to an interactive element instead of the actual Dialog element.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by chunhtai — COMMENTED** [review]
The correct behavior is to focus on the first item in screen order when a new page or dialog is pushed, which is the "This is a typical dialog".

I am not sure if this is possible for web though.

**Comment by chunhtai** [comment]
cc @yjbanov  I think this should be the default behavior, but I remembered you mention web engine have trouble detecting a new page is pushed

**Comment by DBowen33** [comment]
> The correct behavior is to focus on the first item in screen order when a new page or dialog is pushed, which is the "This is a typical dialog".
> 
> I am not sure if this is possible for web though.

**Comment by DBowen33** [comment]
> The correct behavior is to focus on the first item in screen order when a new page or dialog is pushed, which is the "This is a typical dialog".
> 
> I am not sure if this is possible for web though.

In most cases, yes this is the correct behavior. According to APG, the initial focus can be variable depending on the circumstance of the dialog and what makes most sense for the user. Since this is a simple dialog that conveys information to a user, focus should be set on the first focusable element of "Ok"

An example can be seen at this link:
https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/

Once at the page click on the "Add Delivery Address" button and once the dialog is open, click "Add" at the bottom. Notice that initial focus is set on the OK button, which is the last focusable element. This is for efficiency since most users will simply dismiss the dialog as soon as they have read the message.

Due to the variability in interactive elements that can be in a dialog, initial focus is variable and it sounds like it's really up to the developer to know which initial focus use case is best. 

However, I believe in this case in particular for the dialog testing, initial focus should be put on the "Ok" button.

**Comment by chunhtai** [comment]
thanks for explanation, I am ok with using auto focus to get around the current behavior.

However, the current behavior is not ideal, looks like it doesn't focus anything. Looking at the semantics tree from the browser devtool, it seems like it is not generating a dialog div. This is something we should look into cc @yjbanov, but not necessary in this pr.

**Comment by chunhtai** [comment]
filed https://github.com/flutter/flutter/issues/153791

**Review by chunhtai — APPROVED** [review]
LGTM

**Pull request merged**
