### PR TITLE
When doing flutter test use batch compiler and link platform in.

### LINKED ISSUE #14931: flutter test loads test forever in --preview-dart-2
## Steps to Reproduce

* Checkout `flutter/plugins`
* `cd flutter/plugins/packages/path_provider`
* `flutter test --preview-dart-2`

There is just one test file with four short tests, but it doesn't seem to finish loading them.
Runs fine without `--preview-dart-2`.

## Logs

```
$ flutter test -v --preview-dart-2
[  +26 ms] [/Users/mravn/github/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] upstream/master
[        ] [/Users/mravn/github/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] [/Users/mravn/github/flutter/] git ls-remote --get-url upstream
[   +6 ms] Exit code 0 from: git ls-remote --get-url upstream
[        ] git@github.com:flutter/flutter.git
[        ] [/Users/mravn/github/flutter/] git log -n 1 --pretty=format:%H
[   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 29d59e3cb7dcd74a8e6ecb57c5c2b11fa106cba0
[        ] [/Users/mravn/github/flutter/] git log -n 1 --pretty=format:%ar
[   +7 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 59 minutes ago
[        ] [/Users/mravn/github/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +18 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.1.7-2-g29d59e3cb
[ +140 ms] switching to directory LocalDirectory: 'test' to run tests
[   +1 ms] running test package with arguments: [--, /Users/mravn/github/plugins/packages/path_provider/test/path_provider_test.dart]
00:00 +0: loading /Users/mravn/github/plugins/packages/path_provider/test/path_provider_test.dart                                                   [ +160 ms] test 0: starting test /Users/mravn/github/plugins/packages/path_provider/test/path_provider_test.dart
[  +14 ms] test 0: starting shell process in preview-dart-2 mode
[   +2 ms] /Users/mravn/github/flutter/bin/cache/dart-sdk/bin/dart /Users/mravn/github/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/mravn/github/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --strong --no-link-platform --incremental --packages /Users/mravn/github/plugins/packages/path_provider/.packages /var/folders/d7/wjkm2mlx10j1389dljf91sg400cjvd/T/dart_test_listenerN7qzTN/listener.dart
00:03 +0: loading /Users/mravn/github/plugins/packages/path_provider/test/path_provider_test.dart                                                   [+3513 ms] /Users/mravn/github/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --disable-observatory --flutter-assets-dir=/var/folders/d7/wjkm2mlx10j1389dljf91sg400cjvd/T/flutter_bundle_directoryFKjvPb --enable-checked-mode --enable-dart-profiling --non-interactive --use-test-fonts --packages=/Users/mravn/github/plugins/packages/path_provider/.packages /var/folders/d7/wjkm2mlx10j1389dljf91sg400cjvd/T/dart_test_listenerN7qzTN/listener.dart.dill
[  +10 ms] test 0: awaiting initial result for pid 14958
00:04 +0: loading /Users/mravn/github/plugins/packages/path_provider/test/path_provider_test.dart                                                   [ +656 ms] test 0: process with pid 14958 connected to test harness
[        ] test 0: awaiting test result for pid 14958
02:09 +0: loading /Users/mravn/github/plugins/packages/path_provider/test/path_provider_test.dart 
```

## Flutter Doctor

```
[✓] Flutter (Channel master, v0.1.8-pre.2, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.1.8-pre.2 at /Users/mravn/github/flutter
    • Framework revision 29d59e3cb7 (61 minutes ago), 2018-02-27 13:15:32 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/mravn/Library/Android/sdk
    • Android NDK at /Users/mravn/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.2.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[✓] Connected devices (1 available)
    • Nexus 5X • 00bff34682e4b2ab • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

### PR DESCRIPTION
**Pull request by aam**
This is to fix #14931.

### CODE REVIEW

**Review by mraleph — APPROVED** [review]

**Comment by mraleph** [comment]
is linking platform in required? In my tests just removing `--incremental` was enough.

**Comment by aam** [comment]
@mraleph wrote

> is linking platform in required? In my tests just removing --incremental was enough.

Yes, per what I see just removing `incrementalCompilerByteStorePath: ''` option still produces kernel file with empty methods in `_Object&ListMixin^^#T0` class.

**Comment by mraleph** [comment]
I am now really concerned that we might have this problem in hot-reload scenario. We need to test this. Also lets try to work with FE team to ensure that we have a way to produce partial Kernel files during testing to avoid overhead.

**Comment by aam** [comment]
This PR is certainly just a workaround to unblock current implementation of `flutter test --preview-dart-2`. Besides concerns about hot reload, we will need working incremental compiler to have `flutter test --preview-dart-2` reuse frontend compiler for multiple tests (#14728).

**Comment by aam** [comment]
> Also lets try to work with FE team to ensure that we have a way to produce partial Kernel files during testing to avoid overhead.

I'm in the middle of moving frontend_server to the dart sdk(main stumbling block is the fact that flutter frontend_server has flutter-specific widget inspector kernel transformation hardcoded, which I don't want to copy over to dart sdk), that should help with that a little.

**Pull request merged**
