### PR TITLE
Fix the OutlineInputBorder padding (#67707)

### PR DESCRIPTION
**Pull request by feinstein**
## Description

This PR is meant to fix the padding on a `InputDecoration` with `OutlineInputBorder`, which didn't conform to the material specs, as explained in the issue linked below.

The issue also asks for further functionality, but I have taken a look at the code and it seems rather complicated to change it. I don't have the time to add it right now, so I decided to just submit this quick fix as at least I can help with this much.

I am not adding any tests, as this change will break lots of golden image tests and I prefer to leave that part to people more experienced with those than me. I didn't run the tests, since I know they will break, so I am marking this as a braking change.

I am posting this PR more as a help to speed things up as I don't think it's finished.

## Related Issues

#67707

## Tests

I added the following tests:

No tests

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [x] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 2 untriaged digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/68523

**Comment by justinmc** [comment]
Thanks for the PR!  Your idea about an adjustable label position might be nice too, but I agree that this PR is fine on its own for now.

Could you merge master into this branch?  I think you picked up a weird commit that's causing weird test failures.

After that, I'll take a look at the tests and see if anything else needs to change besides the goldens.

We'll also need to follow the [breaking changes policy](https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes) for this, including writing a design doc and migration guide.  Are you up for that?

**Comment by skia-gold** [comment]
Gold has detected about 2 untriaged digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/68523

**Comment by feinstein** [comment]
@justinmc I don't know if I have the spare time to write an entire document on this. I could jump start one and you could review/complete it?

I looked at the template, should I create a go link with my go link account or do you create one with Google's?

**Comment by justinmc** [comment]
Yeah sure I can take over the design doc after you get started with it.

The go link is step 6 in the [design doc instructions](https://docs.google.com/document/d/1SFRO8U2toOlAaZ38dsuEU7Wm5fn41wvBCWKiwADqfmw/edit).  You just open a PR in flutter/website.

Thanks for merging master, the tests seem to be running now, but indeed they are failing due to the padding change.  Try running material/text_field_test.dart locally and you'll see the failures.  Probably just some numbers that need to be updated.

**Comment by feinstein** [comment]
I try to run them locally.

I just didn't understand the step 6. I have to edit the JSON, ok, but what go link do I put there? Will someone else put it for me on my PR?

**Comment by justinmc** [comment]
The destination link is just the link to your design document.  So make a copy of that template, make it publicly visible, and then put the public URL into that JSON file.

**Comment by feinstein** [comment]
Yes, but that json has 2 fields, one for the doc link and one for the go link. Will the go link name be generated automatically by whatever I write there?

**Comment by justinmc** [comment]
Oh sorry, the go link you can just make up yourself.  Like "outline-input-border-padding" or whatever looks nice to you.

**Comment by feinstein** [comment]
@justinmc I added you as an editor to the breaking changes doc I am writing, it's almost done, I just left the testing section empty.

I would appreciate any inputs on how to improve it.

**Comment by justinmc** [comment]
@feinstein I left you some comments, thanks for writing that!  You also have some tests here that are failing because they're testing the position of various things in TextField.  You should run the tests in material/text_field_test.dart locally to see what's failing.

**Comment by feinstein** [comment]
@justinmc I tried to run the tests in text_field_test.dart but I get TONS of errors, most I believe not related with this issue. Also the code doesn't compile, so I believe more has to be changed in order for us to change the tests? Is this related to the non-nullable changes?

**Comment by justinmc** [comment]
Maybe, could you try merging in master again?  I would expect lots of failures due to sizing and positioning numbers being wrong, but not unrelated errors.

**Comment by feinstein** [comment]
I tried to merge master again, but I got lots of errors as well. All of them appeared to be unrelated with this. Also a compilation error. I suspect this test file wasn't fully updated to match the non-nullable update.

**Comment by justinmc** [comment]
I just checked out your branch and ran `flutter test packages/flutter/test/material/text_field_test.dart` in the root of the flutter repo and I get one failure and no strange errors.  Is that the command you're running?  Maybe something is messed up in your checkout of Flutter?

**Comment by feinstein** [comment]
Thinking about it, I invoked the IntellijJ shortcut for running all tests, as I always do. But my system is not using the flutter tool version from the flutter repo, it uses the stable branch, that could be the problem. Thanks for pointing it out, I will try to run the test in the repo's flutter tool.

**Comment by feinstein** [comment]
@justinmc I found the error, but I am not sure on how to fix it.

The test failing is related to the MD specs on leading icons on text inputs. The most recent version of the website doesn't include specs for a leading icon, just for a trailing icon.

Could you inform the MD team and ask for specs so I could fix the test and a create a new one accordingly?

**Comment by justinmc** [comment]
What is the clarification you need, exactly?  The distance from the outline to the leading icon?

**Comment by feinstein** [comment]
Yes.

**Comment by justinmc** [comment]
Got it, I will find out and respond here.

**Comment by justinmc** [comment]
@feinstein I confirmed that it's the same for the leading and trailing icons (they are mirror images of each other).

**Comment by feinstein** [comment]
OK so I am assuming this:

With icon:

<border><12dp><icon><16dp><label><16dp><icon><12dp><border>

Without icon:

<border><16dp><label><16dp><border>

And will ajust the code accordingly.

**Comment by feinstein** [comment]
@justinmc I will need some further specs from the MD team.

The tests mention some specs relative to the outer icon, but the link and text make no sense on the current version of MD.

These are all the icons (I don't know why they are rendering as X, maybe a bad master?):

image

From left to right: `icon`, `prefixIcon` and `suffixIcon`.

I have the specs for `prefixIcon` and `suffixIcon`, but not for `icon`.

Is `icon` out of the MD and should we remove it's tests?

**Comment by justinmc** [comment]
We should probably have some tests for the icon and wherever Flutter decides to put it, even if we have to spec definition for it.

Yeah I'm also unable to find it in the spec.  Maybe it's more of a form thing and less of a text field thing.  I'll check with the Material team again tomorrow.

**Comment by justinmc** [comment]
I haven't been able to get any solid numbers from the Material team.  These kinds of icons are in the [spec](https://material.io/components/text-fields#usage) but they don't have measurements.

Screen Shot 2020-11-09 at 8 39 28 AM

**Comment by feinstein** [comment]
Ok, so do we proceed? Do they want to make a spec and we should wait?... Or do I just leave them as they are?

**Comment by feinstein** [comment]
Hi @justinmc, I have been very busy lately so it has been hard to take a look at this, anyway, today I got some spare time to update the tests and I got another question to the MD team.

The `prefixIcon` and `suffixIcon` have a minimum size of 48x48. The MD specs say they should have 12dp distance from the border....do I add 12 to those 48 or do I remove the 48dp from the width and add 12dp padding?

**Comment by justinmc** [comment]
Sorry for the silence, I've been on leave for awhile.  I actually noticed today that the bug I opened on the Material spec had just been assigned, so maybe we will get an answer soon.  If not, I think we should just take our best guess at the location of those far left icons, but then write a test that checks the icons' exact positions (if one doesn't already exist).

About your second question, I say 12 + 48.  Is there any invisible padding in that 48x48 though?  The reason the icon's hitbox is 48x48 is so that it's never too small to tap.

**Comment by justinmc** [comment]
@feinstein Here are the measurements we need.  Are you still available to get this PR over the finish line?

b_172570269_TextField-IcSpacing

**Comment by feinstein** [comment]
@justinmc I became a Flutter Tech Lead @ BTG Pactual a couple of months ago, so I am currently swamped with new projects. 

Do you guys have any time-line on this? I can try to attack it on my spare time, if it takes too long I will let you know and ask for help, is this OK?

**Comment by Piinks** [comment]
Hey @feinstein congrats on your tech lead role! 🎉  
Should we close this PR or would you like to have this change move forward?

**Comment by feinstein** [comment]
Thanks @Piinks!

I would like to see this implemented, I am just not finding the spare time to look into it.

**Comment by Piinks** [comment]
> I would like to see this implemented, I am just not finding the spare time to look into it.

I understand. Thank you very much for your work on this! Someone may pick it up, but in the meantime, I am going to close this since it is not currently active.

**Pull request closed without merging**
