### PR TITLE
Pare down our Travis dependencies. (NOT FOR REVIEW)

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
I'm testing to see how Travis handles this since it couldn't handle the more complex https://github.com/flutter/flutter/pull/3986.

**Comment by abarth** [comment]
Yeah, I don't think these are needed now that we don't build C++ code on this bot.

**Comment by Hixie** [comment]
_Something_ here is needed. `flutter test` is hanging if I remove the three addons. I'm trying to narrow down to which one it actually needs.

**Comment by Hixie** [comment]
follow up will be in #3986

**Pull request closed without merging**
