### PR TITLE
[flutter_tools] output release artifacts to build/winuwp

### PR DESCRIPTION
**Pull request by jonahwilliams**
Add a `uwp`  parameter to `WindowsAotBundle` to conditionally output the app.so into the winuwp build folder

https://github.com/flutter/flutter/issues/70211

### CODE REVIEW

**Comment by jonahwilliams** [comment]
This will require an update to the patcher scripts/template to look in build/winuwp instead of build/windows

**Comment by jonahwilliams** [comment]
friendly ping @cbracken

**Comment by jonahwilliams** [comment]
Sorry, didn't realize you were OOO when I messaged you 😄

**Review by clarkezone — APPROVED** [review]
lgtm

**Comment by clarkezone** [comment]
This is blocking progress @cbracken please can you take a look?

**Pull request merged**
