### PR TITLE
Added Kazakh material translations

### PR DESCRIPTION
**Pull request by yerzhant**
## Description

*Added material translations for kazakh language

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [X] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by yerzhant** [comment]
I signed it.

**Comment by HansMuller** [comment]
Thanks for the contribution! I've added your translations to a new PR: #31578.  With any luck it will land in the Flutter repo in the next couple of days.

**Comment by HansMuller** [comment]
I'm closing this PR because the new translations will land in #31578

**Comment by yerzhant** [comment]
And thank you, Hans.

**Pull request closed without merging**
