### PR TITLE
Update goldens and roll engine to ecbb2b28d48a3854aba846da38053cf381cced25

### PR DESCRIPTION
**Pull request by liyuqian**
ecbb2b28d Call drawPaint instead of drawPath if there's clip (flutter/engine#5937)
597a50849 Roll src/third_party/skia cdfa16d086b8..4c3b63e289c5 (9 commits) (flutter/engine#5936)
715b64ee3 Roll src/third_party/skia 1400d38e0863..cdfa16d086b8 (10 commits) (flutter/engine#5934)
ffbafc852 Flush all embedded Android views on hot restart. (flutter/engine#5929)
9fe6a573e Roll src/third_party/skia 578ef2847b72..1400d38e0863 (7 commits) (flutter/engine#5933)
3b66f20d9 Don't drop MotionEvents with unknown tool type. (flutter/engine#5931)
391ac2f95 Roll src/third_party/skia 64cc576b1fa7..578ef2847b72 (20 commits) (flutter/engine#5930)

Goldens:
64b7a3a Add updated golden files
cb1fa8a Update golden files of PhysicalModel and PhysicalShape
3baed8d Add a goldens package for the embedded Android views integration test.

### CODE REVIEW

**Comment by amirh** [comment]
nit: I missed that this is a goldens roll as well, maybe include in the PR title roll engine and goldens?
nit2: add a `git rev-list` for the goldens roll as well to the description

**Review by amirh — APPROVED** [review]
LGTM

**Comment by liyuqian** [comment]
@amirh Done, thanks!

**Comment by Hixie** [comment]
This roll caused major performance regressions.

**Comment by liyuqian** [comment]
@Hixie yes, it should be fixed by https://github.com/flutter/engine/pull/5952 . I'll discuss the tests with you tomorrow.

**Pull request merged**
