### PR TITLE
[flutter_tools] check if requireloader is defined

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Otherwise we get a nasty (though harmless) console stacktrace when running with -d web-server

### CODE REVIEW

**Comment by jonahwilliams** [comment]
This is tested by the existing web integration tests, which failed when i misspelled requireLoader

**Comment by christopherfujino** [comment]
why would requireLoader not be present?

**Comment by jonahwilliams** [comment]
the requireLoader is put on the window by the injected dwds bootstrap script, which isn't run on the web-server mode

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by ph55** [comment]
Could it be merged to beta cannel please ?

**Comment by rafaelcmm** [comment]
> Could it be merged to beta cannel please ?

looking forward to that

**Comment by christopherfujino** [comment]
> Could it be merged to beta cannel please ?

This should be present in the next beta release.

**Pull request merged**
