### PR TITLE
Drop an unnecessary factory constructor

### PR DESCRIPTION
**Pull request by natebosch**
This usage is more idiomatically modeled with an initializer list.

### CODE REVIEW

**Comment by natebosch** [comment]
Existing tests (should) cover this. No visible change.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by natebosch** [comment]
One thing I overlooked, before the class was defined in a way that prevented `extends TimelineEvent`, and now that will be allowed.

I don't _think_ that was the purpose for this pattern, but I could be wrong.

This class is exposed in the public API of `flutter_driver` so this does have user facing consequences

@yjbanov - was disallowing subclasses an intended goal? If so I can switch this PR to adding a comment stating such.

**Review by yjbanov — APPROVED** [review]
Thanks for the clean-up

**Comment by yjbanov** [comment]
> @yjbanov - was disallowing subclasses an intended goal? If so I can switch this PR to adding a comment stating such.

No, but now that you mention it, I wouldn't mind putting `@sealed` on it :)

**Pull request merged**
