### PR TITLE
[CupertinoDatePicker] Fixed curving for wide screen 

### LINKED ISSUE #54241: CupertinoDatePicker is curving the wrong way when screen is wide
On head v1.18.1-pre.2

Use a basic CupertinoDatePicker
https://github.com/xster/flutter-test/tree/master/t156_picker

The horizontal curvature seems to be width dependent. 

Screen Shot 2020-04-07 at 4 16 22 PM

When it's too wide, it starts to curve backwards

Screen Shot 2020-04-07 at 4 16 52 PM

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/54241

This is easily reproducible in https://gallery.flutter.dev/#/demo/cupertino-pickero on desktop or tablet

### Narrow
Screenshot 2021-11-03 at 11 59 48 AM

## Before
Screenshot 2021-11-03 at 12 00 57 PM

## After
Screenshot 2021-11-03 at 12 00 03 PM

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 12 new digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/92972

**Comment by skia-gold** [comment]
Gold has detected about 8 new digest(s) on patchset 5.
View them at https://flutter-gold.skia.org/cl/github/92972

**Comment by skia-gold** [comment]
Gold has detected about 12 new digest(s) on patchset 5.
View them at https://flutter-gold.skia.org/cl/github/92972

**Comment by TahaTesser** [comment]
This seems to be breaking tons of tests, I will close it for now

**Pull request closed without merging**
