### PR TITLE
Update cupertino and material translations

### LINKED ISSUE #65448: Japanese localization of CupertinoDatePicker has uncommon date format.
I tried to show the Cupertino-type date picker in Japanese, and it showed the date in the format "month : day : year". However, the date in Japanese is expressed in the "year : month : day" format in most cases and this localization doesn't seem to be appropriate.
This is due to the datePickerDateOrderString property of  CupertinoLocalizationJa class having the value 'mdy' instead of 'ymd'.

image

### PR DESCRIPTION
**Pull request by xster**
Our arbs have some new translation. Look reasonable to me. I don't have too much context on the Material updates. 

Also fixes https://github.com/flutter/flutter/issues/65448

### CODE REVIEW

**Review by DanielEdrisian — APPROVED** [review]
LGTM

**Comment by DanielEdrisian** [comment]
From analyze-linux:

> The contents of packages/flutter_localizations/lib/src/l10n/generated_material_localizations.dart are different from that produced by gen_localizations.
> Did you forget to run gen_localizations.dart after updating a .arb file?

**Comment by xster** [comment]
Indeed. Thanks for pointing out. 

Also fixes https://github.com/flutter/flutter/issues/65448

**Comment by HansMuller** [comment]
@shihaohong - please take a look at this

We definitely don't want a resource called `searchTextFieldPlaceholerLabel`

**Comment by xster** [comment]
@HansMuller can you elaborate a bit? Are you objecting to the name string or the concept of it?

**Comment by xster** [comment]
The seemingly approximate equivalent on the Material side is a field called `searchFieldLabel`

**Comment by HansMuller** [comment]
> @HansMuller can you elaborate a bit? Are you objecting to the name string or the concept of it?

There's a typo: searchTextFieldPlaceholerLabel should be searchTextFieldPlaceholderLabel

**Comment by DanielEdrisian** [comment]
@HansMuller That is completely my fault. Thank you for catching it.

**Comment by HansMuller** [comment]
@DanielEdrisian - NP, the typo made me smile.

**Comment by xster** [comment]
ha, thanks for catching it Hans. Replacing it here. I think that should correct the translation console string as long as we don't push translations again before the next google3 roll.

**Review by shihaohong — APPROVED** [review]
Changes LGTM

**Comment by xster** [comment]
Linux web_e2e_test passed on luci but isn't updating on github for some reason. Merging

**Pull request merged**
