### PR TITLE
fix fialing lint `Consider using 'register' to avoid unnecessary configuration`

### PR DESCRIPTION
**Pull request by AbdeMohlbi**
fix failing lint `Consider using 'register' to avoid unnecessary configuration` in Android studio :
Capture d’écran 2024-11-19 132110

Capture d’écran 2024-11-19 133050
see #147122
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by reidbaker** [comment]
Test-exemption: This is a change in behavior lets identify at least one test that covers this path so we can claim that this codepath is tested. 
I am comfortable saying that the compile and copy assets tasks are covered but we need to find a test that covers the jni libs task.

**Review by reidbaker — COMMENTED** [review]
approved % jnilibs test identification. 

As an aside I really appreciate the new format you are using with screenshots of the lints you are correcting!

**Review by bartekpacia — APPROVED** [review]
this LGTM, a welcome change:) thank you

**Comment by AbdeMohlbi** [comment]
> approved % jnilibs test identification. 
> 
Should i write a test ?
Any examples that i can use them as a blueprint ?

**Comment by reidbaker** [comment]
> > approved % jnilibs test identification.
> 
> Should i write a test ? Any examples that i can use them as a blueprint ?

I dont think you need to write a test just identify an existing test that uses the jni task. I am about to go on vacation for a bit more than a week (time off + thanksgiving) and i am trying to get some different work landed before I leave or I would find this for you.

**Comment by AbdeMohlbi** [comment]
> > > approved % jnilibs test identification.
> > 
> > 
> > Should i write a test ? Any examples that i can use them as a blueprint ?
> 
> I dont think you need to write a test just identify an existing test that uses the jni task. I am about to go on vacation for a bit more than a week (time off + thanksgiving) and i am trying to get some different work landed before I leave or I would find this for you.
if understand the errors right , this is a test that failed when to excute without the jni task (there is others , but this one seamed more accurate)
[Linux gradle_plugin_fat_apk_test](https://github.com/flutter/flutter/pull/159294/checks?check_run_id=33349820930)

**Comment by reidbaker** [comment]
> > > > approved % jnilibs test identification.
> > > 
> > > 
> > > Should i write a test ? Any examples that i can use them as a blueprint ?
> > 
> > 
> > I dont think you need to write a test just identify an existing test that uses the jni task. I am about to go on vacation for a bit more than a week (time off + thanksgiving) and i am trying to get some different work landed before I leave or I would find this for you.
> 
> if i understand the errors right , this is a test that failed to execute without the jni task (there is others , but this one seamed more accurate) [Linux gradle_plugin_fat_apk_test](https://github.com/flutter/flutter/pull/159294/checks?check_run_id=33349820930)

Confirmed 
`[2024-11-19 04:04:15.120178] [STDOUT] stdout: [  +99 ms] > Task :aaa:mergeDebugJniLibFolders`
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8730841621379757489/+/u/run_gradle_plugin_fat_apk_test/stdout
From this pr.

**Review by reidbaker — APPROVED** [review]

**Pull request merged**
