### PR TITLE
Changed ThemeData DiagnosticProperties to DiagnosticLevel.hidden

### PR DESCRIPTION
**Pull request by amrfarid140**
## Description

Changes ThemeData DiagnosticProperties to DiagnosticLevel.hidden to reduce the verbosity of `ThemeData.toString` call

## Related Issues

https://github.com/flutter/flutter/issues/27478

## Tests

I added the following tests:

in `theme_data_test.dart: 

- `ThemeData.toString has less than 200 characters output for dark color scheme`
- `ThemeData.toString has less than 200 characters output for light color scheme`

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by gspencergoog** [comment]
Out of curiosity, why did you switch back to `DiagnosticLevel.hidden` from `DiagnosticLevel.debug`, as Jacob had suggested in the bug? (Which is not necessarily wrong, I'm just curious what the motivation was).

**Comment by amrfarid140** [comment]
It still didn't pass the tests and gave a very long output

**Comment by gspencergoog** [comment]
I restarted the failed tasks: they looked like flakiness in our continuous integration, not a problem with your change.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by gspencergoog** [comment]
Sorry, this fell off my radar.  I'll submit as soon as the tests pass.

**Comment by gspencergoog** [comment]
@amrfarid140 I'm wondering why the tests are still failing: can you sync to the upstream HEAD and push it?  I'm wondering if you're just synced to a broken build.

**Comment by amrfarid140** [comment]
@gspencergoog I will pull that latest on `master` and let's see

**Comment by gspencergoog** [comment]
It looks like the merge you did removed all the changes except the tests.

Can you take a look at your git repo and see if you can recover the changes?

**Comment by amrfarid140** [comment]
Closed in favour of https://github.com/flutter/flutter/pull/50589

**Pull request closed without merging**
