### PR TITLE
update adaptive slider docs

### PR DESCRIPTION
**Pull request by maheshj01**
Minor change in the slider doc mentioning the platforms when CupertinoSlider is created.

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 7 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/96599

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by HansMuller** [comment]
@maheshmnj - please push an empty update to force the tests to rerun

**Comment by skia-gold** [comment]
Gold has detected about 3 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/96599

**Comment by HansMuller** [comment]
@maheshmnj - no one seems to know why this is failing. Best to try syncing up with master and pushing again.

**Comment by werainkhatri** [comment]
Looks like the issue has been fixed. Adding the label.

**Pull request merged**
