### PR TITLE
Revert "update packages"

### PR DESCRIPTION
**Pull request by CareF**
Reverts flutter/flutter#61647
because luci reports error downloading dependencies.

### CODE REVIEW

**Comment by CareF** [comment]
https://ci.chromium.org/p/flutter/builders/prod/Windows/10129?
https://ci.chromium.org/p/flutter/builders/prod/Mac/12731?

**Review by liyuqian — APPROVED** [review]
LGTM

**Comment by jason-simmons** [comment]
Rerunning `flutter update-packages --force-upgrade` will update the `hybrid_android_views` package that was missed during the last run of force-upgrade.

**Comment by GaryQian** [comment]
Heads up, Looks like this revert brought the tree into a worse state than before. https://github.com/flutter/flutter/commit/1c55445b25fb0a6fce19e458213b56d6a001900e seemed to bring it to a mostly-green state

**Pull request merged**
