### PR TITLE
Roll engine to 05c5f817eb731569ddaad6397ee9ce000d37f2f1

### PR DESCRIPTION
**Pull request by bkonyi**

### CODE REVIEW

**Comment by cbracken** [comment]
I've kicked Travis/Appveyor to pick up the engine build.

**Comment by cbracken** [comment]
LGTM but looks like there's a merge conflict.

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
Safe to ignore CLA bot - both of us are Googlers.

**Comment by tvolkert** [comment]
FYI, this engine rev needs to be applied together with the semantics changes that go with it.  So this is superseded by https://github.com/flutter/flutter/pull/14694

**Pull request closed without merging**
