### PR TITLE
avoid // ignore: prefer_const_constructors

### PR DESCRIPTION
**Pull request by a14n**
This is to reduce technical debt as mentioned in https://github.com/flutter/flutter/pull/8024#issuecomment-279105998

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
I would maybe make the comment be more explicit, something like "we want these instances to be separate instances so that we're not just checking with a single object" or whatever.

**Comment by a14n** [comment]
comment changed

**Comment by abarth** [comment]
Thanks!

**Pull request merged**
