### PR TITLE
Don't display empty tooltips (Tooltips with empty `message` property)

### PR DESCRIPTION
**Pull request by bambinoua**
If tooltip message is empty than no need to display empty dark rectangle.

### CODE REVIEW

**Comment by dkwingsmt** [comment]
The change looks ok. Can you add a unit test so that someone doesn't accidentally undo it?

**Comment by bambinoua** [comment]
> 
> 
> The change looks ok. Can you add a unit test so that someone doesn't accidentally undo it?

@dkwingsmt  I've added tests but I did not do them ever before. Please check I  created acceptable ones.

**Comment by bambinoua** [comment]
I do not know why some checks were not successful

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Comment by dkwingsmt** [comment]
> If this is merged, we could do away with [`Chip.useDeleteButtonTooltip`](https://master-api.flutter.dev/flutter/material/Chip/useDeleteButtonTooltip.html) added in #68237 (I happen to know this one since I authored it).

That's a very reasonable idea. Be aware that the change might be breaking or at least need a migration guide.

**Pull request merged**
