### PR TITLE
Some debugger stepping integration tests

### PR DESCRIPTION
**Pull request by DanTup**
Some debugger tests; work in progress.

~~Requires [this PR](https://github.com/dart-lang/vm_service_client/pull/33) to be merged to work.~~

~~Though the tests then fail because they don't pause as expected - I believe that's down to https://github.com/flutter/flutter/issues/18877.~~

Blocked on https://github.com/dart-lang/vm_service_client/issues/41

### CODE REVIEW

**Comment by Hixie** [comment]
@DanTup What's the plan here? Is this ready for review?

**Comment by DanTup** [comment]
I fixed the original issues blocking these tests in vm_service_client but hit another:

https://github.com/dart-lang/vm_service_client/issues/41

It's not clear to me how it should be fixed so I hoped for some input - I'll see if I can find someone to ping about it.

**Comment by Hixie** [comment]
@DanTup Should we close this in the meantime?

**Comment by DanTup** [comment]
Apologies - I made a little progress (update the VM spec with the missing info), but still need to update the `vm_service_client` package to reflect the spec changes.

I'll close this until it's in a better position to progress (I can easily re-open it).

**Pull request closed without merging**
