### PR TITLE
Add web safe indirection to Platform.isPlatform getters

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

flutter tests compiled to JavaScript will not be able to safely invoke `Platform.isWindows/isLinux/isMacOS` in skip fields since this `dart:io` method has no implementation currently in the web SDK. Even if we added an implementation, it would likely not capture the spirit of these particular skips - we don't want to conflate skipping something on flutter tester on Windows with skipping something running in a browser on Windows.

To avoid the lint "don't define a class with only static members" I made these top level getters, though I am open to other approaches.

## Related Issues
https://github.com/flutter/flutter/pull/33349

### CODE REVIEW

**Comment by gspencergoog** [comment]
It would be nice if these were const values instead of accessors, a la https://github.com/dart-lang/sdk/issues/35705.  Then the code could be more completely optimized by the compiler.

But at least these are accessors and not functions so that they can be swapped out for const values in the future.

**Comment by jonahwilliams** [comment]
We could definitely do this ourselves once a) the const evaluation update lands, allowing us to provide defines to non-AOT builds b) we produce different bundles/snapshots per architecture

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

Looks like you'll need to merge with master.

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
