### PR TITLE
flutter tool: log dart2wasm vs dart2js as appropriate during build

### LINKED ISSUE #124164: flutter tool, web: should we report dart2wasm time vs dart2js time...when doing wasm things?
https://github.com/flutter/flutter/blob/9e4b5fb7d986fe1a92f92d970f8021e2c1e1603d/packages/flutter_tools/lib/src/web/compile.dart#L108

### PR DESCRIPTION
**Pull request by kevmoo**
Fixes https://github.com/flutter/flutter/issues/124164

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
> It looks like this pull request may not have tests.

PR at https://github.com/flutter/flutter/pull/124179 shows how something like this could be tested.

**Comment by kevmoo** [comment]
Now with tests! Thanks @jmagman !

**Comment by jmagman** [comment]
> Now with tests! Thanks @jmagman !

This could use a test where `isWasm: false` to cover the other branch 🙂

**Pull request merged**
