### PR TITLE
Revert "Roll Engine from 965fbbed1776 to 801559ac4ed3 (50 revisions)"

### PR DESCRIPTION
**Pull request by dnfield**
Reverts flutter/flutter#59384

This made the devicelab _very_ red.

TBR @iskakaushik

### CODE REVIEW

**Comment by gw280** [comment]
Reference: https://flutter-dashboard.appspot.com/#/build

Not looking good. Investigating

**Comment by dnfield** [comment]
Most likely culprit seems to be Dart roll, since it seems like all mac specific VM Service connection failures.

**Comment by iskakaushik** [comment]
LGTM

**Pull request merged**
