### PR TITLE
Manual roll of engine to 16d7694e760a..5c428d924790 (10 commits)

### PR DESCRIPTION
**Pull request by jiahaog**
$ git log 16d7694e760a48fddc6a29f77db016c14156bb94..5c428d9247905ff2ffd0f53186ccf5f6898c617c --no-merges --oneline

5c428d924 Check for a null input method subtype (flutter/engine#12706)
42dd58940 Roll src/third_party/skia 1ffc2e453b00..a7914a872657 (1 commits) (flutter/engine#12721)
1aea2f55c Roll src/third_party/dart 63b5fa1709..fb1c5a6404 (6 commits)
a8353e179 Roll src/third_party/skia cb6de9f661f3..1ffc2e453b00 (4 commits) (flutter/engine#12719)
2122412a4 Roll fuchsia/sdk/core/linux-amd64 from _0Sq8... to 3Axx8... (flutter/engine#12718)
9fcec1955 Roll src/third_party/dart 67ae444f29..63b5fa1709 (2 commits)
079e418c2 Set transparent background in textarea elements (flutter/engine#12710)
6d1117979 Roll fuchsia/sdk/core/mac-amd64 from KH7Tv... to Jr7x0... (flutter/engine#12716)
545926df9 Roll src/third_party/skia 2533afa3f8c6..cb6de9f661f3 (1 commits) (flutter/engine#12714)

### CODE REVIEW

**Comment by jiahaog** [comment]
There seems to be a pending autoroll at #41660, will this automatically cancel it?

**Review by mklim — APPROVED** [review]
LGTM

**Comment by mklim** [comment]
> There seems to be a pending autoroll at #41660, will this automatically cancel it?

I think so. There will be merge conflicts in `engine.version`.

**Comment by jiahaog** [comment]
The autoroll happened before this – I resolved the conflicts and updated the description.

**Pull request merged**
