### PR TITLE
Remove deprecated drag anchor

### PR DESCRIPTION
**Pull request by Piinks**
This removes 
- `Draggable.dragAnchor`
- `LongPressDraggable.dragAnchor`
- `DragAnchor` enum

This deprecated class has reached end of life after the release of Flutter 3.3

- The replacement is to use `dragAnchorStrategy` instead.
-  ✅  Migration via dart fix is supported
- 🕐 This API was deprecated in
  - https://github.com/flutter/flutter/pull/79160, tagged v2.1

Part of https://github.com/flutter/flutter/issues/111708
For the full list of deprecations being removed in this batch, see [flutter.dev/go/deprecations-removed-after-3-3](https://github.com/flutter/flutter/pull/flutter.dev/go/deprecations-removed-after-3-3)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Piinks** [comment]
Customers are migrated, this is safe to land.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by bernaferrari** [comment]
Noob question: is it possible to remove this too? 

2.3.0 seems to be more than one year ago. I'm not sure you have a calendar and periodically removes the deprecated things, or you are seeing some code and see it is deprecated, let's remove it.

image


image

**Comment by Piinks** [comment]
That one is not slated for removal after v3.3. The cut-off was v2.2 this time around. The deprecation policy specifies number of releases, as well as time, with the longest duration as taking precedence, for removing deprecated code. That one should be removed in the next batch.

**Comment by bernaferrari** [comment]
Oh, ok, thanks!!

**Comment by Piinks** [comment]
Also, you do not seem to be referring to stable releases. Those are the releases we base the cut off on. 2.2 was followed by 2.5 on the stable channel. :)

**Comment by bernaferrari** [comment]
You are right, but 2.5 was also more than 1 year ago (barely..) 😛

**Comment by Piinks** [comment]
> but 2.5 was also more than 1 year ago

| -- | -- |
| v2.5  | 9/8/2021 |
| v3.3 |  8/30/2022 |

Again, this is based on release dates. Not today's date. 
Do you feel we should change our policy? Feedback is always welcome.

**Comment by bernaferrari** [comment]
No, it is fine the way it is, but I never understood it (I still don't understand it, lol). I guess it is 12month + 1 stable version, something like this.

**Pull request merged**
