### PR TITLE
Disable back gesture behind a flag until it's ready.

### PR DESCRIPTION
**Pull request by mpcomplete**

### CODE REVIEW

**Comment by Hixie** [comment]
Is there a bug list somewhere of what needs to be fixed for this to be permanently enabled?

**Comment by Hixie** [comment]
Yeah, you can create a label for it. "affects: back gesture" or some such.

**Comment by Hixie** [comment]
I'm concerned that settings this to false didn't make any tests fail.

I think that if we're going to have a flag, it makes it even more important that we have tests for this code. Code that isn't run _will_ bit rot and introduce bugs.

**Comment by mpcomplete** [comment]
I'm actively working on this feature. It won't bit rot. I'm only disabling it so we don't ship a Gallery release with an incomplete version of this.

**Comment by mpcomplete** [comment]
I've added a test that checks the back gesture on iOS and android. I first verifies it works as expected when the gesture is enabled, then I disabled the gesture and inverted the test condition.

**Comment by Hixie** [comment]
LGTM for now. Please make sure this doesn't stay in this state for more than a couple of weeks or so.

**Comment by eseidelGoogle** [comment]
This only seems to disable the gesture itself.  iOS still slides things in from the right (instead of below like Android), which is actually where more of the bugs are. :)

In this case I think we're just gonna fix the back gesture and not worry hugely about disabling or not.  But we'll eventually need to tech up more in this area.

**Pull request merged**
