### PR TITLE
Update plugin test template.

### PR DESCRIPTION
**Pull request by pq**
Currently we generate an example test that makes no sense for plugin projects since they use a different `main` (see [main.tmpl](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/lib/main.dart.tmpl#L129)).  This fixes that.  

**EDIT:** also adds steps to ensure generated widget tests pass for vanilla, package and plugin projects 👍 

To be sure, the test itself could be improved; input on that (or anything), welcome!

@Hixie @cbracken @yjbanov

### CODE REVIEW

**Comment by Hixie** [comment]
Can you add a test to make sure that when we do `flutter create` for a plugin, the test passes?

**Comment by pq** [comment]
@Hixie : validation added for for vanilla, package and plugin project tests 👍 .

**Comment by Hixie** [comment]
LGTM

**Comment by pq** [comment]
Bummer.  I'm not surprised that the tests are a bit slower since we're now verifying that all the template widget tests run (and pass).  But 10s+, ouch!

**Comment by mravn-google** [comment]
@pq Based on one measurement only. But still.

**Pull request merged**
