### PR TITLE
Add locales for fil(filipino) and gsw(swiss german) to locale list, Fixes #60631

### LINKED ISSUE #60631: Missing locales for fil and gsw in 'gen_l10n_types'
When trying to generate localizations with grinder on the flutter gallery the generate-localizations script outputs the following errors

`  fatal: The following .arb file's locale could not be determined: 
  lib/l10n/intl_fil.arb 
  Make sure that the locale is specified in the file's '@@locale' property or as part of the filename (e.g. file_en.arb)
`

and 

`  fatal: The following .arb file's locale could not be determined: 
  lib/l10n/intl_gsw.arb 
  Make sure that the locale is specified in the file's '@@locale' property or as part of the filename (e.g. file_en.arb)
`

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
## Description

This fixes a bug that broke localization generation for the flutter gallery which uses fil and gsw locales.

## Related Issues

This fixes #60631 

## Tests

This script has no tests.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by rami-a — APPROVED** [review]
LGTM

**Review by clocksmith — APPROVED** [review]

**Review by HansMuller — APPROVED** [review]
LGTM

**Review by shihaohong — APPROVED** [review]
LGTM. This is sort of a hack, but the main underlying issue is actually with the filename parsing algorithm that was recently introduced in https://github.com/flutter/flutter/pull/60185. 

I'll spend some time thinking about what we can do to have a smart filename parsing algo. @Renzo-Olivares Do you happen to know if `fil` and `gsw` are language identifiers that are particular to Google?

**Comment by Renzo-Olivares** [comment]
> LGTM. This is sort of a hack, but the main underlying issue is actually with the filename parsing algorithm that was recently introduced in #60185.
> 
> I'll spend some time thinking about what we can do to have a smart filename parsing algo. @Renzo-Olivares Do you happen to know if `fil` and `gsw` are language identifiers that are particular to Google?

I don't believe they're particular to Google. I did a quick search to see how Android handles locales and came it came up with this https://developer.android.com/reference/java/util/Locale#getISO3Language() . 

> Three-letter language/country(region) codes
The Locale constructors have always specified that the language and the country param be two characters in length, although in practice they have accepted any length. The specification has now been relaxed to allow language codes of two to eight characters and country (region) codes of two to three characters, and in particular, three-letter language codes and three-digit region codes as specified in the IANA Language Subtag Registry. For compatibility, the implementation still does not impose a length constraint.

link to registry [https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)

**Comment by shihaohong** [comment]
Seems like an unrelated tools test is failing on windows. Since `flutter-build` is also failing, maybe wait until the tree is green, then rebase/merge from master to see if that fixes the issue

**Pull request merged**
