### PR TITLE
Tiny fix Flutter seems not to agree what is the estimated size of `ui.Image` (reland)

### LINKED ISSUE #128163: Flutter seems not to agree what is the estimated size of `ui.Image`
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

-

### Expected results

-

### Actual results

-

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by fzyzcjy**
Reland https://github.com/flutter/flutter/pull/128164

Close https://github.com/flutter/flutter/issues/128163

I did an experiment, and the result is quite close to `4/3`, and far away from the one without 4/3. See https://github.com/flutter/flutter/issues/128163#issuecomment-1579602572 for details. (Indeed it agrees with my intuition ;) )

Copy of that comment:

0. Create a test image at `assets/green.png`

For example, I use imagemagick:

```
convert -size 8000x8000 canvas:green green.png
```

2. Hack the Flutter source code:

Go to `image.dart`, add a line in `_ImageState._replaceImage`:

```dart
    print('hi $runtimeType._replaceImage info=$info sizeBytes=${info.sizeBytes}');
```

3. Run the code, and tap the button

```dart
import 'package:flutter/material.dart';

void main() {
  debugOnPaintImage = (info) => print('debugOnPaintImage see $info decodedSizeInBytes=${info.decodedSizeInBytes}');
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var _loadAssetImage = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Column(
          children: [
            TextButton(
              onPressed: () => setState(() => _loadAssetImage = true),
              child: Text('Load AssetImage'),
            ),
            if (_loadAssetImage) Image.asset('assets/green.png'),
          ],
        ),
      ),
    );
  }
}
```

Result:

```
I/flutter (18623): hi _ImageState._replaceImage info=null sizeBytes=null
I/flutter (18623): hi _ImageState._replaceImage info=assets/green.png [8000×8000] @ 1.0x sizeBytes=256000000
I/flutter (18623): debugOnPaintImage see ImageSizeInfo(assets/green.png, imageSize: Size(8000.0, 8000.0), displaySize: Size(1080.0, 1080.0)) decodedSizeInBytes=341333333
```

In other words, the same image is reported to be both 256000000 bytes and 341333333 bytes, which does not look right.

In addition, look at Memory tab in DevTools before and after the button tap. I reproduce on Android with Profile mode. Results:

before:

image

immediately after:

image

wait a while (maybe it does some kind of GC?)

image

In other words, the memory increases 352MB (519-167M), which looks near 341333333, and unlike 256000000.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
(triage): Looks like lots of checks are failing - can you take a look?

**Comment by fzyzcjy** [comment]
Sure!

**Comment by goderbauer** [comment]
@dnfield Do you know if this is correct?

**Review by dnfield — CHANGES_REQUESTED** [review]
The right place to expose this is in `dart:ui` on `Image`. We should have some kind of getter that exposes the size in bytes, similar to what we have on `ui.Picture.approximateBytesUsed` (but we should not call it approximate since with images we'll know).

The basic problem here is whether there is overhead for mipmapping or not, as well as whether the image is actually being stored in a 4-byte format (in Flutter it generally is but we don't have to -but again, the engine knows this and that's the right place to fix things).

**Comment by dnfield** [comment]
IOW - instead of giving a slightly closer but still wrong answer, we should just give the right answer :)

**Comment by fzyzcjy** [comment]
Thanks for the suggestion, then I will make an engine PR first!

**Pull request closed without merging**
