### PR TITLE
Refactored ListTileTheme: ListTileThemeData, ThemeData.listThemeData

### LINKED ISSUE #31247: ListTileTheme should be a part of ThemeData
## Steps to Reproduce

1. Create a new flutter app
2. Add a list tile widget with a secondary icon
3. Add all icon themes to the ThemeData, Notice secondary icon attributes do not change
3. Wrap Widget with ListTileTheme and add icon attributes, Notice secondary icon attributes changed.

https://gist.github.com/ibrahim-mubarak/f6f777396372ac400e0a7f129e5b1186

## Logs

Output of `flutter run --verbose`

https://gist.github.com/ibrahim-mubarak/573222b2988f0149df74bd9a8bca0bd5

Output of `flutter analyze`

```
Analyzing list_tile_theme...
No issues found! (ran in 1.4s)
```

Output of `flutter doctor -v`

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-IN)
    • Flutter version 1.2.1 at /Users/ibrahim/development/flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ibrahim/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/ibrahim/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.87
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • iPhone Xʀ • CB9F9632-F724-40C0-8C12-8FB04A58DD26 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

If we are using The Navigators onGenerateRoute Function we have to wrap all our page widgets with ListTileTheme or the MaterialApp itself with ListTileTheme, both in my opinion, feels hacky

### PR DESCRIPTION
**Pull request by HansMuller**
Refactored ListTileTheme to make it conform to Flutter's conventions for component themes.

- Added a `ListTileThemeData` class which defines overrides for the defaults for visual ListTile properties.
- Added a ListTileTheme constructor parameter and getter: `ListTileThemeData data`. This is now the preferred way to configure a ListTileTheme.
- Added a `listTileThemeData listTileTheme` property to ThemeData. This is now the preferred way to configure ListTiles in a MaterialApp.
- Added `selectedColor`, `textColor`, `iconColor` and (ListTileStyle) `style` parameters to ListTile, so that all of the properties that can be overridden via the theme can also be set on the widget itself.

For example to configure the icon and text colors for all of the ListTiles in an app:

```dart
import 'package:flutter/material.dart';

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            ListTile(
              selected: true,
              title: Text('selected'),
              leading: Icon(Icons.android),
              trailing: Text('trailing')
            ),
            SizedBox(height: 32),
            ListTile(
              selected: false,
              title: Text('unselected'),
              leading: Icon(Icons.android),
              trailing: Icon(Icons.android),
            ),
          ],
        ),
      ),
    );
  }
}

void main() {
  runApp(
    MaterialApp(
      theme: ThemeData.light().copyWith(
        listTileTheme: ListTileThemeData(
          selectedColor: Colors.orange,
          iconColor: Colors.green,
          textColor: Colors.blue,
        ),
      ),
      home: Scaffold(body: Home())
    ),
  );
}
```

This is a non-breaking change.  In an upcoming PR all of the ListTileTheme properties, except for `data` will be deprecated and a Dart Fix script will be provided to automatically migrate code.

Fixes https://github.com/flutter/flutter/issues/31247

### CODE REVIEW

**Review by darrenaustin — APPROVED** [review]
LGTM. Nicely done. Just a few suggestions below.

**Comment by anaurelian** [comment]
When is this going to be in the stable branch?

**Comment by HansMuller** [comment]
@anaurelian - it's not likely until mid to late December 2021

**Comment by fredgrott** [comment]
Thanks for the info @HansMuller glad to know that the drop for it appearing is soon.

**Pull request merged**
