### PR TITLE
fix visual density prefer_const_constructors lint

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Engine roll with fixed lint did not run against this before submission. TBR @gspencergoog

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Landing on red to fix build

**Review by gspencergoog — COMMENTED** [review]
LGTM.  I'm very confused as to how that passed analysis before, but I guess it was because it ran before the lint was turned on?

**Comment by jonahwilliams** [comment]
The version of the linter in the tree had a bug. This PR was analyzed against the version of the linter with the bug, when it was branched. The engine roll that contained the fix ran tests against the framework without your change in. Both pass on presubmit and immediately fail

**Comment by cbracken** [comment]
Was discussing with @Hixie yesterday. Improvements/fixes to linters are a constant source of legitimate roll pain. Our solution there was that we built tooling that allowed us to whitelist files for a given lint in the roll then shard the fixes out over as many commits as needed to fix (one for the framework, however many for the customer-submitted tests) and whittle down the whitelist to nothing again.

That avoids blocking the roll for what isn't a regression, and also doesn't unfairly put the burden of fixing everyone else's code on the roller. I'll file a bug for this.

**Comment by cbracken** [comment]
Filed https://github.com/flutter/flutter/issues/54482.

**Pull request merged**
