### PR TITLE
[flutter_tools] [dap] Ensure DAP sends app.stop/app.detach during terminate

### PR DESCRIPTION
**Pull request by DanTup**
Fixes an issue where the flutter_tester device may not be cleaned up correctly if we just terminate the Flutter process in the DAP when the client calls terminateRequest. This calls the [app.stop/app.detach commands](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/doc/daemon.md#appstop) first and waits for them to complete (or the process to terminate).

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
Looks like you'll need to update expectations for the integration test too:

```
10:14 +28 -2: test/integration.shard/debug_adapter/flutter_adapter_test.dart: launch can run and terminate a Flutter app in debug mode [E]                                                             
  Expected: [
              'Launching lib/main.dart on Flutter test device in debug mode...',
              <a string starting with 'Connecting to VM Service at'>,
              'topLevelFunction',
              '',
              <a string starting with 'Exited'>
            ]
    Actual: [
              'Launching lib/main.dart on Flutter test device in debug mode...',
              'Connecting to VM Service at ws://127.0.0.1:42277/c2gksXLXhog=/ws',
              'topLevelFunction',
              'Application finished.',
              '',
              'Exited.'
            ]
     Which: at location [3] is 'Application finished.' instead of ''
  
  package:test_api                                                     expect
  test/integration.shard/debug_adapter/test_support.dart 49:5          expectLines
  test/integration.shard/debug_adapter/flutter_adapter_test.dart 63:7  main.<fn>.<fn>
```

**Comment by DanTup** [comment]
Oops, I think I didn't rebuild flutter_tools when I ran those (they spawn `flutter debug_adapter`) 🙈

Should be good now, thanks!

**Comment by christopherfujino** [comment]
> Oops, I think I didn't rebuild flutter_tools when I ran those (they spawn `flutter debug_adapter`) 🙈
> 
> Should be good now, thanks!

Ahh yeah, I've hit that tricky gotcha.

**Comment by DanTup** [comment]
> Ahh yeah, I've hit that tricky gotcha.

Embarrassingly, I'd set up a way to run the tests in-process specifically because of this, and I had to rebuild when doing the manual testing with Dart-Code's integration tests to verify it solved the original issue 🙃

(although perhaps committing temporary code to disable verbose logging is more embarrassing... also fixed now)

**Pull request merged**
