### PR TITLE
Updated package template .gitignore file

### PR DESCRIPTION
**Pull request by shali3**
Updated package template .gitignore file to match the .gitignore file in the app template.

### CODE REVIEW

**Comment by shali3** [comment]
I signed it!

**Comment by shali3** [comment]
Any updates?

**Review by zanderso — APPROVED** [review]
lgtm

**Comment by DanTup** [comment]
The `.vscode` folder was removed from gitignore previously (see https://github.com/flutter/flutter/issues/15555 and https://github.com/flutter/flutter/pull/15382). It's not a good idea to have here, as it can contain important launch information for your project.

I understand that some projects don't want IDE-specific files in their repo, but they should make that call and ignore them if they want - losing these files by default for end users seems a bad idea.

Any objections to removing `.vscode` here and wherever it was copied from? @zanderso @jonahwilliams

**Comment by jonahwilliams** [comment]
No objections from me. Perhaps we could have the IDE specific files commented out in the template with a "uncomment to hide files for ___" ?

**Comment by shali3** [comment]
+1 for @jonahwilliams idea.

**Comment by DanTup** [comment]
Without context, I think for VS Code users it could be confusing/misleading. If you're a VS Code user it generally doesn't make sense to ignore that folder (and if you're not, you won't see them).

I think the decision to ignore this folder should be a very deliberate and specific one, rather than just "it looked like I should uncomment it because I use VS Code". It's hard to capture that in a comment because it's hard to describe the situations where it makes sense to ignore (the only reasons I can come up with is a project where the main devs don't use VS Code, some contributors do use VS Code *and explicitly create these files*, but don't review the files they're committing).

FWIW, I came across this change because a user was having trouble launching projects - it turned out to be that he had a launch file on disk created for another branch, but because it wasn't committed/versioned, switching branch didn't remove it, and it resulted in vague errors when launching (the errors make sense when you understand the cause, but it wasn't obvious because he hadn't realised his VS Code launch configs were gitignored).

**Comment by DanTup** [comment]
I commented it out with a note and opened a PR here: https://github.com/flutter/flutter/pull/32404

**Pull request merged**
