### PR TITLE
ModalBottomSheetRoute: Allow content to consume top notch with SafeArea

### LINKED ISSUE #121752: ModalBottomSheetRoute: Content can't consume top notch with `SafeArea`
## Steps to Reproduce

1. Execute `flutter run` on the code sample, choosing a recent iPhone with a camera notch (such as an iPhone 14 Pro)
3. Tap the "Show sheet" button
4. Bug: The contents of the sheet aren't padded against the notch at the top, even though I've wrapped them in a `SafeArea` with `top: true`.

**Expected results:** I expected my `SafeArea` to pad the notch at the top, so my sheet's content isn't hidden.

**Actual results:** My `SafeArea` did not pad the notch at the top.

Screen recording:

Code sample: https://github.com/chrisbobbe/modal-bottom-sheet-top-inset-not-paddable

Or paste into a blank project's main.dart:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Bottom sheet issue'),
        ),
        body: Center(child: Builder(builder: (context) {
          return ElevatedButton(
            onPressed: () => showModalBottomSheet(
              context: context,
              constraints: const BoxConstraints(minHeight: 800),
              useSafeArea: false,
              isScrollControlled: true,
              builder: (BuildContext context) {
                return SafeArea(
                  child: Column(
                    children: List.generate(4, (index) {
                      return MenuItemButton(
                          onPressed: () {},
                          child: Text('MenuItemButton $index'));
                    })));
              }),
            child: const Text('Show sheet'));
        })),
      ),
    );
  }
}
```

<details>
  <summary>Logs</summary>

```
No errors expected or observed in the logs.
```

```
$ flutter analyze
Analyzing scratch...                                                    
No issues found! (ran in 1.9s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel main, 3.8.0-17.0.pre.27, on macOS 13.0 22A380 darwin-x64, locale
    en-US)
    • Flutter version 3.8.0-17.0.pre.27 on channel main at
      /Users/chrisbobbe/.local/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a6f7cd0650 (2 days ago), 2023-02-27 16:30:46 -0800
    • Engine revision 8857c39c96
    • Dart version 3.0.0 (build 3.0.0-277.0.dev)
    • DevTools version 2.22.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/chrisbobbe/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/chrisbobbe/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] Network resources
    • All expected network resources are available.

• No issues found!
chrisbobbe:~/dev/scratch (main) 
```
</details>

### PR DESCRIPTION
**Pull request by chrisbobbe**
Fixes #121752.

With `useSafeArea: false`, there is no longer a `MediaQuery.removePadding` with `removeTop: true`. That `MediaQuery` was preventing the sheet's content from accurately padding the system intrusion at the top, when desired.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by gnprice — APPROVED** [review]
Thanks! LGTM. (And I see it's essentially the same as the remaining part of #121588 after #122118 was merged.)

We found on #121588 that these changes caused failures in Google testing. I believe this is nevertheless the right change, for the reasons at https://github.com/flutter/flutter/issues/121752#issuecomment-1451088562 and in the thread up to https://github.com/flutter/flutter/pull/121588#issuecomment-1450616535 . But I'd like to have @hangyujin's input on what's going on in those tests — whether the code in question is just working around broken behavior and can be updated to work with the fixed behavior, or whether perhaps there's something we've missed that makes the existing behavior the right way after all.

**Comment by gnprice** [comment]
@hangyujin Do you think you might be able to take a look at the Google tests affected by this fix? I see your major bottom-sheet PR #122445 has now been merged :-)

**Comment by hangyujin** [comment]
@chrisbobbe  Hi Can you rebase this PR to re-trigger google testing? I can't see the failure details for it.

**Comment by chrisbobbe** [comment]
Ah it looks like @gnprice has just done so; thanks, Greg!

**Comment by gnprice** [comment]
@hangyujin Are you able to see failure details for the PR now?

The reporting of status back to GitHub seems to be getting stuck, but I'm told [in #hackers-infra](https://discord.com/channels/608014603317936148/608021351567065092/1087875326828363837) that it ran and there are some failures visible from inside Google.

**Review by hannah-hyj — APPROVED** [review]

**Comment by hangyujin** [comment]
Talked to a release team member, and he suggested me to try give this an approval to see if it can trigger google testing to start.

**Comment by gnprice** [comment]
Looks like it's still in status pending.

I think the release team member's suggestion may have been about [this point](https://github.com/flutter/flutter/wiki/Understanding-google-testing):
> Google Testing does not start until a Flutter hacker has approved the PR.

But the PR already satisfied that condition, since I'd approved it earlier. So if it's about that condition, then a second approval wouldn't change things.

I'll try updating the branch again. Perhaps on a third roll of the dice, things will work. (Also, perhaps the underlying issue is about the infra running into GitHub rate limits, in which case this might be a less congested time of day.)

**Comment by gnprice** [comment]
:tada: Google testing reported results! Failures, as expected.

@hangyujin when you get a chance, it would be great if you can take a look at what's going on in those tests — whether the code in question is just working around broken behavior and can be updated to work with the fixed behavior, or whether perhaps there's something we've missed that makes the existing behavior the right way after all.

(There are also failures in customer_testing, but those are unrelated to the PR: #123385.)

**Comment by chrisbobbe** [comment]
Just updated with a merge commit.

**Comment by chrisbobbe** [comment]
Just updated again.

**Comment by chrisbobbe** [comment]
Updated.

**Comment by chrisbobbe** [comment]
Hmm, an automated check failed: "Pull Request Labeler / triage (pull_request_target)".

Clicking through to see details, there are some error lines in the output:

```console
[…]
Error: Error: found unexpected type for label 'a: accessibility' (should be array of config options)
Error: found unexpected type for label 'a: accessibility' (should be array of config options)
[…]
```

Neither this PR nor its linked issue (#121752) are labeled with 'a: accessibility'…hmm.

Ah! Those errors are mentioned in https://github.com/flutter/flutter/issues/129666, which has been closed as fixed. I'll make another merge commit to update this, and see if that fixes it.

**Comment by Hixie** [comment]
@chrisbobbe thanks for the contribution! Sorry for the delay in reviewing the test results.

I just triggered an update so that the bots would run again. Can you ping us on [Discord](https://github.com/flutter/flutter/wiki/Chat) when the tests give a result so that someone can help you find out what is going on? Thanks!

**Comment by Hixie** [comment]
Google testing failures: looks like it's caused a bunch of apps to have some additional padding at the top of bottom sheets.

**Comment by chrisbobbe** [comment]
Makes sense; I would expect that to happen in most cases where the bottom-sheet content has a `SafeArea` with `top: true`. Each case should be described by one of these three scenarios:

1. The bottom-sheet content doesn't want to pad the top inset. It makes the mistake of building a `SafeArea` with `top: true` and should stop doing that.
2. The bottom-sheet content wants to pad the top inset, and it wasn't doing so before. The `SafeArea` with `top: true` has started to work as intended. (Nothing to change.)
3. The bottom-sheet content wants to pad the top inset, and it _was_ doing so before: whether to a wrong, hardcoded value, or to the right value because of hacking around the `removeTop`. There's a `SafeArea` with `top: true` in there somewhere, which used to be a no-op but now adds padding on top of the hack. The app should remove the hack and leave behind a normal use of `SafeArea` with `top: true`.

If that's wrong, perhaps there's something we've missed that makes the existing behavior the right way after all. 🙂

**Comment by Hixie** [comment]
The problem is that this would essentially introduce a silent regression which we could not detect or automation migration for. So we'd essentially be breaking shipping apps without any way for the developer to notice unless they tested every screen on a lot of devices (with different notches), which is more effort than many people can afford.

**Comment by chrisbobbe** [comment]
I see. I think one way forward would be:

- Close as WONTFIX #121752.
- Document the current behavior: with `useSafeArea: false`, if you put a `SafeArea` in the content, it won't have top padding. That's actually also true of `useSafeArea: true`, but that's not surprising, because in that case the top edge of the sheet can't actually enter the device's top inset.

Thinking more about this, I don't really understand the use case for `useSafeArea: false`, which is where #121752 is active. The default is `false`.

<details>
<summary>(why I don't understand that use case)</summary>

https://github.com/flutter/flutter/issues/39205#issuecomment-726257303 mentions one bottom sheet that builds a whole `Scaffold` with an app bar that "docks" at the top of the screen, and so it mustn't be prevented from entering the top inset, as `true` would do. I don't know which app that is, or [whether it still does it that way](https://github.com/flutter/flutter/pull/121588#issuecomment-1450616535). In that case, it's not clear whether you'd want top padding or not:

- With padding, won't it look wrong when the sheet is open halfway?
- Without padding, won't it look wrong when the sheet is open fully ("docked" at the top)?
- With dynamic padding computed from the top edge's position, won't that break the Material metaphor?

</details>

Possibly, `useSafeArea: true` should have been the default, but changing that default also sounds disruptive and breaking. But as I said at the top of this comment, some more documentation could be helpful.

**Comment by Hixie** [comment]
Documentation is always welcome, certainly. And I agree that it's not clear that we made the right choices when initially developing this, unfortunately.

**Comment by chrisbobbe** [comment]
Makes sense. I just sent https://github.com/flutter/flutter/pull/134793 for that documentation, and so now I'll close this PR, and close https://github.com/flutter/flutter/issues/121752 as WONTFIX (after commenting there to refer to #134793).

**Pull request closed without merging**
