### PR TITLE
Null safe migration for fuchsia remote debug protocol

### PR DESCRIPTION
**Pull request by dnfield**
Mostly just from `dart migrate`, plus deleting some now unreachable code and a few tweaks/hints that seemed right to me.

@chaselatta  - any chance you can verify this doesn't break `fx attach`?

Required for https://github.com/flutter/flutter/issues/71379

### CODE REVIEW

**Comment by dnfield** [comment]
Going to see if I can run this through some internal testing that might exercise that.

**Comment by dnfield** [comment]
Per @chaselatta this is working internally, with one exception being that an `// ignore: await_only_futures` might not actually be doing what we want it to.

If that's the case, we might need to roll vm_service internally as part of the flutter roll :(

**Comment by dnfield** [comment]
Also, this needs an internal buildrule update, which I'll file a g3 fix for - but I think it needs to be approved before I can do that.

**Comment by chaselatta** [comment]
We will also need to update the build rule in the fuchsia repo but I can add that for you.

**Comment by chaselatta** [comment]
Regarding the vm_service, when we roll this into fuchsia we will roll the version of vm_service that you are using locally. I didn't realize you had updated the version so I was still using version 5.5.0 locally so this will resolve itself when we roll.

**Review by chaselatta — APPROVED** [review]

**Comment by dnfield** [comment]
I'll open a g3 fix for this.

**Pull request merged**
