### PR TITLE
[performance] Process dirty nodes from top to bottom during paint to avoid unnecessary layer tree walks

### PR DESCRIPTION
**Pull request by goderbauer**
Prior to this change, the `flushPaint` method was the odd one out of all the flush methods on PipelineOwner as it would process dirty nodes from bottom to top instead of top to bottom. Some historic digging shows that the flushPaint processing order was changed to that in https://github.com/flutter/flutter/commit/654fc7346eb79780aadeb9c2883ea9938d5f0bd3#diff-d06e00032e4d722205a2189ffbab26c1d8f5e13652efebc849583d0a1359fec9R612. Unfortunately, the exact reason is lost to history. Presumably it was for performance, but no scenario where this order would be beneficial has been identified. Instead, this order of processing causes additional walks of the layer tree during paint that would be avoided with top to bottom processing. Therefore, this PR is changing the order back to top to bottom.

**Regressions?** If this change causes any performance regression it should be rolled back immediately and the scenario where bottom to top processing is beneficial should be documented in flushPaint (or even better: encoded in a test).

### CODE REVIEW

**Comment by goderbauer** [comment]
FYI @chunhtai since you recently also run into trouble with the upside down processing order in paint.

**Review by chunhtai — APPROVED** [review]
LGTM, the only thing that prevented me from doing this was that I am not sure if some mechanism may depend on the paint order. If this change was introduced as a result of performance improvement, I think it is probably obsolete.

**Review by jonahwilliams — APPROVED** [review]
Let the great experiment begin!

**Comment by goderbauer** [comment]
Figured out why this was breaking a test in Google3. A widget there is making brittle assumptions about the paint order. The Render tree looks basically like this:

```
Overlay
  OverlayEntryA
     UninterestingRenderObject
        RenderObjectA
  OverlayEntryB
    RenderObjectB
```

RenderObjectA and RenderObjectB share some data via a shared object. When RenderObjectA paints it sets some data on that sharedObject, that RenderObjectB is supposed to use during its paint. This is assuming that A paints before B (if B paints first it will use outdated data as A didn't have a chance to update the sharedObject yet). Prior to this PR, we would paint the deepest RenderObject first and since A is deeper in the tree it was guaranteed to paint first. This PR is switching this order around and now B is painting first missing the updated data that A is producing during its paint.

Seems a little brittle to rely on paint order like that. It only works because A happens to be deeper in the tree.

**Comment by Hixie** [comment]
That is definitely an invalid assumption. It's perfectly acceptable for siblings to be painted in any arbitrary order.

**Comment by goderbauer** [comment]
Actually, what I describe above is not some custom internal widget. Turns out, it's our Material Slider widget that has this problematic reliance on node processing order during paint. Filed https://github.com/flutter/flutter/issues/98770 for that with more details. We should also add a test for the slider to the framework that would have caught the breakage this caused in google3 earlier on this PR.

**Pull request merged**
