### PR TITLE
Fix autofill eligibility check

### LINKED ISSUE #94043: Autofill not working on latest master
## Steps to Reproduce

1. Execute `flutter run` on the code sample.
2. Tap the `TextField`.

**Expected results:** Autofill option pops up.

**Actual results:** Autofill option does not pop up.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Reproduction',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key? key}) : super(key: key);
  final focusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: [
          IconButton(
            icon: const Icon(Icons.restore),
            onPressed: () => focusNode.unfocus(),
          )
        ],
      ),
      body: Center(
        child: TextField(
          autofillHints: const [AutofillHints.email],
          keyboardType: TextInputType.emailAddress,
          focusNode: focusNode,
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[  +67 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +432 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 6644d548e9762ea0d3d4fc9e836f8102a7476039
[        ] executing: [C:\src\flutter/] git tag --points-at 6644d548e9762ea0d3d4fc9e836f8102a7476039
[  +48 ms] Exit code 0 from: git tag --points-at 6644d548e9762ea0d3d4fc9e836f8102a7476039
[   +1 ms] executing: [C:\src\flutter/] git describe --match *.*.* --long --tags 6644d548e9762ea0d3d4fc9e836f8102a7476039
[  +70 ms] Exit code 0 from: git describe --match *.*.* --long --tags 6644d548e9762ea0d3d4fc9e836f8102a7476039
[        ] 2.3.0-16.0.pre-388-g6644d548e9
[   +5 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +25 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +102 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +30 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +92 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +63 ms] executing: C:\Users\gergo\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +52 ms] List of devices attached
           4fcf519f               device product:beryllium model:POCO_F1 device:beryllium transport_id:25
[   +5 ms] C:\Users\gergo\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 4fcf519f shell getprop
[ +119 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +114 ms] Skipping pub get: version match.
[ +109 ms] Generating C:\Git\aaa\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +70 ms] ro.hardware = qcom
[  +40 ms] Initializing file store
[  +11 ms] Skipping target: gen_localizations
[   +9 ms] Skipping target: gen_dart_plugin_registrant
[   +1 ms] Skipping target: _composite
[   +3 ms] complete
[   +7 ms] Launching lib\main.dart on POCO F1 in debug mode...
[   +7 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dillC:\Users\gergo\AppData\Local\Temp\flutter_tools.3283f6df\flutter_tool.1793523c\app.dill --packages C:\Git\aaa\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\f245b0b7cc30f460f818fcec6bcf01fb.cache.dill.track.dill --flutter-widget-cache
--enable-experiment=alternative-invalidation-strategy
[  +13 ms] executing: C:\Users\gergo\AppData\Local\Android\Sdk\build-tools\32.0.0-rc1\aapt dump xmltree C:\Git\aaa\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +13 ms] Exit code 0 from: C:\Users\gergo\AppData\Local\Android\Sdk\build-tools\32.0.0-rc1\aapt dump xmltree C:\Git\aaa\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.aaa" (Raw: "com.example.aaa")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="aaa" (Raw: "aaa")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.aaa.MainActivity" (Raw: "com.example.aaa.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=39)
                     E: action (line=40)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=42)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=49)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +12 ms] executing: C:\Users\gergo\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 4fcf519f shell -x logcat -v time -t 1
[  +21 ms] <- compile package:aaa/main.dart
[ +133 ms] --------- beginning of kernel
                    12-01 03:26:10.513 I/[cds_ol][12141362991284][17:13:17.460737] wlan(    0): [2098:I:QDF] qdf_dp_display_proto_pkt_always: 2093:  DPT: 1645:255 DHCP: [0] [DISC] SA: c4:ad:34:bb:21:bc   
                    <--  DA: ff:ff:ff:ff:ff:ff
[  +12 ms] executing: C:\Users\gergo\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[  +37 ms] Android Debug Bridge version 1.0.41
           Version 31.0.3-7562133
           Installed as C:\Users\gergo\AppData\Local\Android\Sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\gergo\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[  +24 ms] Building APK
[  +24 ms] Running Gradle task 'assembleDebug'...
[   +9 ms] Using gradle from C:\Git\aaa\android\gradlew.bat.
[  +15 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +144 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[   +2 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +155 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "11.0.10" 2021-01-19
           OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
           OpenJDK 64-Bit Server VM (build 11.0.10+0-b96-7249189, mixed mode)
[   +3 ms] executing: [C:\Git\aaa\android/] C:\Git\aaa\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=C:\Git\aaa\lib\main.dart
-Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1585 ms] > Task :app:compileFlutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +2 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[  +66 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[   +1 ms] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugAssets
[ +401 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[  +84 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[   +1 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[        ] > Task :app:compressDebugAssets UP-TO-DATE
[   +1 ms] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[  +96 ms] > Task :app:packageDebug UP-TO-DATE
[ +133 ms] > Task :app:assembleDebug
[   +1 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[   +1 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 2s
[        ] 32 actionable tasks: 4 executed, 28 up-to-date
[ +530 ms] Running Gradle task 'assembleDebug'... (completed in 3.3s)
[  +74 ms] calculateSha: LocalDirectory: 'C:\Git\aaa\build\app\outputs\flutter-apk'/app.apk
[ +685 ms] √  Built build\app\outputs\flutter-apk\app-debug.apk.
[   +5 ms] executing: C:\Users\gergo\AppData\Local\Android\Sdk\build-tools\32.0.0-rc1\aapt dump xmltree C:\Git\aaa\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +18 ms] Exit code 0 from: C:\Users\gergo\AppData\Local\Android\Sdk\build-tools\32.0.0-rc1\aapt dump xmltree C:\Git\aaa\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.example.aaa" (Raw: "com.example.aaa")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="aaa" (Raw: "aaa")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.aaa.MainActivity" (Raw: "com.example.aaa.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=39)
                     E: action (line=40)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=42)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=49)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +6 ms] Stopping app 'app.apk' on POCO F1.
[        ] executing: C:\Users\gergo\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 4fcf519f shell am force-stop com.example.aaa
[ +106 ms] executing: C:\Users\gergo\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 4fcf519f shell pm list packages com.example.aaa
[ +133 ms] package:com.example.aaa
[   +3 ms] executing: C:\Users\gergo\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 4fcf519f shell cat /data/local/tmp/sky.com.example.aaa.sha1
[  +74 ms] 99609fa27fc3fc53c08c1f4fb93b2abcf024d037
[   +1 ms] Latest build already installed.
[        ] executing: C:\Users\gergo\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 4fcf519f shell -x logcat -v time -t 1
[  +90 ms] --------- beginning of kernel
           12-01 03:26:15.735 I/[cds_ol][12141463248881][17:13:22.682487] wlan(    0): [2098:I:QDF] qdf_dp_display_proto_pkt_always: 2093:  DPT: 1695:255 DHCP: [0] [DISC] SA: c4:ad:34:bb:21:bc  <--  DA:  
           ff:ff:ff:ff:ff:ff
[   +8 ms] executing: C:\Users\gergo\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 4fcf519f shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez
enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.aaa/com.example.aaa.MainActivity
[ +110 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.aaa/.MainActivity (has extras) }
[   +1 ms] Waiting for observatory port to be available...
[ +320 ms] Observatory URL on device: http://127.0.0.1:38645/Tqt5EE_es3Q=/
[   +1 ms] executing: C:\Users\gergo\AppData\Local\Android\Sdk\platform-tools\adb.exe -s 4fcf519f forward tcp:0 tcp:38645
[  +26 ms] 60767
[   +1 ms] Forwarded host port 60767 to device port 38645 for Observatory
[+3275 ms] Caching compiled dill
[  +45 ms] Connecting to service protocol: http://127.0.0.1:60767/Tqt5EE_es3Q=/
[ +223 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:60767/Tqt5EE_es3Q=/.
[ +198 ms] DDS is listening at http://127.0.0.1:60772/MpQTDp7hoq4=/.
[  +62 ms] Successfully connected to service protocol: http://127.0.0.1:60767/Tqt5EE_es3Q=/
[ +119 ms] DevFS: Creating new filesystem on the device (null)
[  +55 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.aaa/code_cache/aaaHFIZFF/aaa/)
[   +2 ms] Updating assets
[  +78 ms] Syncing files to device POCO F1...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:aaa/main.dart b0ea2867-9200-4c7d-b62f-cf5f73bd91b5
[        ] <- b0ea2867-9200-4c7d-b62f-cf5f73bd91b5
[ +107 ms] Updating files.
[        ] DevFS: Sync finished
[   +2 ms] Syncing files to device POCO F1... (completed in 115ms)
[   +1 ms] Synced 0.0MB.
[   +2 ms] <- accept
[  +22 ms] Connected to _flutterView/0x7d301d85d0.
[   +3 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ]  Running with sound null safety 
[   +1 ms] An Observatory debugger and profiler on POCO F1 is available at: http://127.0.0.1:60772/MpQTDp7hoq4=/
[ +126 ms] DevTools activation throttled until 2021-11-23 05:10:26.700051.
[ +565 ms] The Flutter DevTools debugger and profiler on POCO F1 is available at: http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A60772%2FMpQTDp7hoq4%3D%2F
```

```
Analyzing aaa...                                                        
No issues found! (ran in 2.5s)
```

```
[√] Flutter (Channel master, 2.3.0-17.0.pre.388, on Microsoft Windows [Version 10.0.19042.1348], locale en-GB)
    • Flutter version 2.3.0-17.0.pre.388 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6644d548e9 (5 months ago), 2021-06-17 08:19:02 -0400
    • Engine revision ced58ef9c1
    • Dart version 2.14.0 (build 2.14.0-217.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at C:\Users\gergo\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 32.0.0-rc1
    • ANDROID_SDK_ROOT = C:\Users\gergo\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.0-insider)
    • VS Code at C:\Users\gergo\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.28.0

[√] Connected device (3 available)
    • POCO F1 (mobile) • 4fcf519f • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)       • edge     • web-javascript • Microsoft Edge 96.0.1054.29

• No issues found!
```

</details>

## Solution
Changing [`_needsAutofill`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/editable_text.dart#L2190) to use the `_effectiveAutofillClient` seems to solve the issue.
```dart
bool get _needsAutofill => _effectiveAutofillClient.textInputConfiguration.autofillConfiguration.enabled;
```
Is there a reason it uses `widget.autofillHints`, or is this just an oversight?

This change was made in commit [33755f](https://github.com/flutter/flutter/commit/33755f203dfeae491f586a73abdf4e400749f32a). Prior to this commit, autofill worked.

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Fixes #94043.

Thanks to @morvagergely for filing the issue and providing a solution.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by justinmc — APPROVED** [review]
LGTM 👍 

I think the failures may be irrelevant.

**Comment by LongCatIsLooong** [comment]
Verified on my phone that autofill works after applying this patch.

**Comment by Lafannn** [comment]
@LongCatIsLooong I see PR already has approved. What are we waiting?

**Comment by AlirezaDaryani** [comment]
So?

**Pull request merged**
