### PR TITLE
Fix Scrollbar painting

### PR DESCRIPTION
**Pull request by TrGiLong**
The description of this bug and steps to reproduce it locates at issue #57920. The master branch also contains this bug. You can see the following screen records:

https://user-images.githubusercontent.com/11016237/112908115-3672aa80-90ef-11eb-9dcf-f56211e256ca.MP4

https://user-images.githubusercontent.com/11016237/112908119-396d9b00-90ef-11eb-9bd3-69830a38329d.MP4

This PR removes unnecessary padding in the calculation of the offset. After the padding was removed, the bug disappeared. I have tested `Scrollbar` with different device orientations, with and without `SafeArea` in root.

Some tests weren't passed because they were written to test padding (Line 321 to 390 in `scrollbar_test.dart`. Should I delete the tests? Here is my first PR so I would appreciate every valuable feedback from the flutter community.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hi @TrGiLong welcome! 🎉 
Thank you for the contribution! It looks like this is causing several existing tests to fail. Can you please fix so that the tests are no longer broken?
This will also require new tests to verify the issue no longer exists. I would recommend one of those tests to consider the behavior when notches are present on the device, as that is a common edge case here.

**Comment by TrGiLong** [comment]
Hi @Piinks 

Currently `widget/scrollbar.dart` applies padding to position, where scroll indicator will be painted. That means if list view is fit to the screen, it will be ok, but if list view is inside the screen, the padding will also be applied and thus move scroll indicator more inside. You can look at the screen below:

IMG_1280

My solution is to remove all those paddings. Developers should apply `SafeArea` to `Scrollbar` to avoid screen notches.

```
// in `widget/scrollbar.dart` at line 324
switch (direction) {
      case AxisDirection.down:
        thumbSize = Size(thickness, thumbExtent);
        trackSize = Size(thickness + 2 * crossAxisMargin, _trackExtent);
        x = textDirection == TextDirection.rtl
          ? crossAxisMargin + padding.left <---- Remove padding
          : size.width - thickness - crossAxisMargin - padding.right; <---- Remove padding
        y = _thumbOffset;
        trackOffset = Offset(x - crossAxisMargin, 0.0);
        break;
      case AxisDirection.up:
        thumbSize = Size(thickness, thumbExtent);
        trackSize = Size(thickness + 2 * crossAxisMargin, _trackExtent);
        x = textDirection == TextDirection.rtl
          ? crossAxisMargin + padding.left <---- Remove padding
          : size.width - thickness - crossAxisMargin - padding.right; <---- Remove padding
        y = _thumbOffset;
        trackOffset = Offset(x - crossAxisMargin, 0.0);
        break;
      case AxisDirection.left:
        thumbSize = Size(thumbExtent, thickness);
        x = _thumbOffset;
        y = size.height - thickness - crossAxisMargin - padding.bottom; <---- Remove padding
        trackSize = Size(_trackExtent, thickness + 2 * crossAxisMargin);
        trackOffset = Offset(0.0, y - crossAxisMargin);
        break;
      case AxisDirection.right:
        thumbSize = Size(thumbExtent, thickness);
        trackSize = Size(_trackExtent, thickness + 2 * crossAxisMargin);
        x = _thumbOffset;
        y = size.height - thickness - crossAxisMargin - padding.bottom; <---- Remove padding
        trackOffset = Offset(0.0, y - crossAxisMargin);
        break;
    }
```

There is another bug but I don't know whether it is related to this bug or not. However, the behaviour is the same. If we apply right padding to `ListView`, the right empty space will not be removed. My solution is also to remove the applying of padding. Developers should use `SafeArea` if it's necessary. You can see this bug in the following attachment:

IMG_1281 2

```
class MyHomePage extends StatelessWidget {
  final List<Widget> items = List<Widget>.generate(30, (_) {
    return Container(
      width: 50,
      height: 50,
      child: Placeholder(),
    );
  });

  @override
  Widget build(BuildContext context) {
    print(MediaQuery.of(context).padding);
    return Scaffold(
      appBar: AppBar(
        title: Text('Scrollbar in horizontal ListView'),
      ),
      body: Scrollbar(
        child: Container(
          padding: EdgeInsets.only(right: 30),
          child: ListView(
            scrollDirection: Axis.horizontal,
            children: items,
          ),
        ),
      ),
    );
  }
}

```

**Review by Piinks — COMMENTED** [review]
Hey @TrGiLong thanks for the update!

I don't know that it is a good idea to change the behavior and require developers to use SafeArea widgets. Right now they do not have to apply SafeAreas, and I think this will cause issues for users that expect the Scrollbar to work without extra widgets. We actually just landed a feature that creates Scrollbars automatically in ScrollBehavior on desktop platforms, so users would not be able to access these Scrollbars and modify them to account for SafeAreas.

I think the second issue you mentioned is caused by the fact that the Scaffold modifies the MediaQuery data of its children. Maybe the issue lies there instead: https://github.com/flutter/flutter/blob/eb7351673937c883e4084844fea92fc5dc1fe834/packages/flutter/lib/src/material/scaffold.dart#L3006

**Comment by TrGiLong** [comment]
Thanks for your reply, @Piinks 

I work on a project which uses `Scrollbar` inside another widget, so it would be great if we can fix this bug early. Do you think we can sort this out soon?😅

On top of that, the feature that you have mentioned is very interesting to me. Can I help with something here? I am a Computer Science student and it would be my pleasure to contribute to the Flutter community.

Last but not least, about the second issue, that we discussed. Should I create a new issue for that?

**Comment by Piinks** [comment]
> I work on a project which uses `Scrollbar` inside another widget, so it would be great if we can fix this bug early. Do you think we can sort this out soon?😅

You could put the scrollbar above that widget, no? It listens to scroll notifications, so as long as it is above your scrollable, putting it higher in your widget tree may be a good workaround while you are working on this. :) 


> On top of that, the feature that you have mentioned is very interesting to me. Can I help with something here? I am a Computer Science student and it would be my pleasure to contribute to the Flutter community.

I am not sure which feature you are referring to, can you elaborate?

> Last but not least, about the second issue, that we discussed. Should I create a new issue for that?

I am not sure if it is an issue, but please feel free to file one with a minimal code sample that reproduces the behavior and I would be happy to take a look with you. :)

**Comment by goderbauer** [comment]
(PR triage): @TrGiLong Do you still have plans to come back to this PR?

**Comment by chunhtai** [comment]
(PR triage): @TrGiLong  I am going to close this PR, feel free to reopen it when you have time to come back to this PR

**Pull request closed without merging**
