### PR TITLE
flutter build ios-framework Some plugin debug framework creation failing

### PR DESCRIPTION
**Pull request by 1amageek**
## Description

Resolved a problem with Cocoapods when running the `flutter build ios-framework `.
Thanks to @robrichardson13 for already suggesting a solution to the problem.

#63508

## Related Issues

https://github.com/flutter/flutter/issues/63508

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behavior with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jmagman — CHANGES_REQUESTED** [review]
Thanks for the contribution!
This needs tests, though unfortunately this file is not well unit tested.  Can you update the integration test?
https://github.com/flutter/flutter/blob/19078b1a026b197cbecbb7482c39b27c226222c8/dev/devicelab/bin/tasks/build_ios_framework_module_test.dart#L34
Try adding `native_mixpanel: 0.1.2` (exact version please so changes in this plugin don't break the test)

Near https://github.com/flutter/flutter/blob/19078b1a026b197cbecbb7482c39b27c226222c8/dev/devicelab/bin/tasks/build_ios_framework_module_test.dart#L386-L390 do something like:
```dart
checkDirectoryExists(path.join(
  cocoapodsOutputPath,
  mode,
  'Mixpanel.framework',
));
```
and near https://github.com/flutter/flutter/blob/19078b1a026b197cbecbb7482c39b27c226222c8/dev/devicelab/bin/tasks/build_ios_framework_module_test.dart#L241 add the `Mixpanel.framework` checks (would duplicate less code to add a second loop over `['device_info', 'Mixpanel']`).

You can run the test locally:
```
$ cd dev/devicelab 
$ dart bin/run.dart -t build_ios_framework_module_test
```

**Comment by 1amageek** [comment]
@jmagman Thank you for providing the details of the test. I've tested it locally and it didn't run well.

```
stdout: ! Doctor found issues in 1 category.
"/Users/1amageek/Developer/flutter/bin/flutter" exit code: 0
Could not determine JAVA_HOME; not shutting down Gradle.
Unhandled exception:
JSON-RPC error -32000: Server error
package:json_rpc_2/src/client.dart 123:62              Client.sendRequest
package:json_rpc_2/src/peer.dart 98:15                 Peer.sendRequest
package:vm_service_client/src/scope.dart 64:23         Scope.sendRequestRaw
package:vm_service_client/src/isolate.dart 361:19      VMIsolateRef.invokeExtension
package:flutter_devicelab/framework/runner.dart 82:59  runTask
===== asynchronous gap ===========================
bin/run.dart 92:47                                     _runTasks
bin/run.dart 85:11                                     main
dart:isolate-patch/isolate_patch.dart 299:32           _startIsolate.<fn>
dart:isolate-patch/isolate_patch.dart 168:12           _RawReceivePortImpl._handleMessage
```

**Comment by jmagman** [comment]
> @jmagman Thank you for providing the details of the test. I've tested it locally and it didn't run well.
> 
> ```
> stdout: ! Doctor found issues in 1 category.
> "/Users/1amageek/Developer/flutter/bin/flutter" exit code: 0
> Could not determine JAVA_HOME; not shutting down Gradle.
> Unhandled exception:
> JSON-RPC error -32000: Server error
> package:json_rpc_2/src/client.dart 123:62              Client.sendRequest
> package:json_rpc_2/src/peer.dart 98:15                 Peer.sendRequest
> package:vm_service_client/src/scope.dart 64:23         Scope.sendRequestRaw
> package:vm_service_client/src/isolate.dart 361:19      VMIsolateRef.invokeExtension
> package:flutter_devicelab/framework/runner.dart 82:59  runTask
> ===== asynchronous gap ===========================
> bin/run.dart 92:47                                     _runTasks
> bin/run.dart 85:11                                     main
> dart:isolate-patch/isolate_patch.dart 299:32           _startIsolate.<fn>
> dart:isolate-patch/isolate_patch.dart 168:12           _RawReceivePortImpl._handleMessage
> ```

I think I just [fixed that yesterday](https://github.com/flutter/flutter/pull/66487)!  Try rebasing on master ToT and try again, or temporarily comment everything in that `cleanupSystem` method to get it to run locally (don't check in the commented code!).

**Comment by jmagman** [comment]
@1amageek I took a crack at this in https://github.com/flutter/flutter/pull/69736#discussion_r517068579.  Would you be able to test it for me?  It's available on the master channel.

**Pull request closed without merging**
