### PR TITLE
Add tooltip for the clear button on `SearchAnchor`'s search view

### LINKED ISSUE #141347: `SearchAnchor` search view close and clear buttons don't have hover tooltips
### Steps to reproduce

1. Add a `SearchAnchor` to your app
2. Run the app. (I tried macOS, CanvasKit, and skwasm)
3. Open the full search view
4. Hover over the close/back or clear buttons
5. Notice no tooltips show up like other built-in Material widgets

### Expected results

Like other Material widgets, I'd expect these icon buttons to have helpful default tooltips.

- When I hover over the close/back button, I'd expect it to say "Close" or "Back" depending on the context.
- When I hover over the clear button, I'd expect it to say "Clear search".

This is especially important in this case as the clear button could easily be mistaken as close.

### Actual results

When hovering over these icon buttons, no tooltips appear.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: SearchAnchor.bar(
            barHintText: 'Search',
            suggestionsBuilder: (context, controller) {
              return [];
            },
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots

<details open>
<summary>Screenshots</summary>

Search view close button:
Search view close button

Search view clear button:
Search view clear button

</details>

### Flutter version info

<details><summary>Version</summary>

```console
Flutter 3.19.0-3.0.pre.43 • channel main • https://github.com/flutter/flutter
Framework • revision f961fdf2ba (4 hours ago) • 2024-01-10 17:37:07 -0500
Engine • revision a045134c91
Tools • Dart 3.4.0 (build 3.4.0-14.0.dev) • DevTools 2.31.0
```

</details>

### PR DESCRIPTION
**Pull request by QuncCccccc**
Fixes #141347
This PR is to add a "clear text" tooltip for the clear button on `SearchAnchor`'s search view and also add a `clearButtonTooltip` entry for `material_localizations`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by AlexV525** [comment]
@QuncCccccc Is there any plan to fill in precise sentences for other languages with this field?

**Comment by gloinho** [comment]
Sorry for asking, but there is any way to remove defaultTrailing (close button) (or edit it)?

**Comment by QuncCccccc** [comment]
> @QuncCccccc Is there any plan to fill in precise sentences for other languages with this field?

Hi! https://github.com/flutter/flutter/pull/154959 just landed:)!

**Pull request merged**
