### PR TITLE
Tell user how to enable available but disabled features

### LINKED ISSUE #79964: When features are disabled, tell user how to enable them
When desktop development is not enabled, you get:
```
$ flutter build macos
"build macos" is not currently supported.
```

Would be nice if this message instructed the user to run `flutter config --enable-macos-desktop` to enable.

### PR DESCRIPTION
**Pull request by jmagman**
Now that desktop and web are available but disabled by default, let the user know how to enable the feature when they try to build for the platform.
Fixes https://github.com/flutter/flutter/issues/79964

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
I don't think we want to show this message unconditionally - desktop isn't available on stable and uwp is only on master. Maybe we need a new feature method like `canBeEnabled(feature)` that would tell you if you're on a supported channel?

**Comment by jonahwilliams** [comment]
I guess desktop can be enabled, its just UWP we need to leave off

**Comment by jmagman** [comment]
> I don't think we want to show this message unconditionally - desktop isn't available on stable and uwp is only on master. Maybe we need a new feature method like `canBeEnabled(feature)` that would tell you if you're on a supported channel?

I was going to say, I thought it was all enabled... but I missed `windowsUwpEmbedding`.

**Comment by jonahwilliams** [comment]
actually I'm not sure if you need my PR for that. If you remove the message for the UWP path I think this PR is great as is

**Comment by jmagman** [comment]
> actually I'm not sure if you need my PR for that. If you remove the message for the UWP path I think this PR is great as is

Done.

**Comment by jonahwilliams** [comment]
We could test this with the command output integration test - run with the environment variable that disables the feature and then check the output

**Comment by jmagman** [comment]
> We could test this with the command output integration test - run with the environment variable that disables the feature and then check the output

Done.

**Comment by jonahwilliams** [comment]
@jmagman I think you missed a commit

**Comment by jmagman** [comment]
> @jmagman I think you missed a commit

Yup.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
