### PR TITLE
bump the dart sdk version

### PR DESCRIPTION
**Pull request by devoncarew**
- bump the dart sdk version to `2.0.0-dev.17.0` to is it addresses the `"Minimum version ("2.0.0-dev.20.0") must be less than maximum ("2.0.0-dev.16.0")"` issue

### CODE REVIEW

**Comment by devoncarew** [comment]
And now try `2.0.0-dev.20.0`.

**Comment by devoncarew** [comment]
And, down to `2.0.0-dev.19.0` to avoid `Package flutter_tools requires SDK version >=1.19.0 <=2.0.0-dev.19.0 but the current SDK is 2.0.0-dev.20.0.`.

**Comment by xster** [comment]
LGTM

**Comment by Coder-256** [comment]
@devoncarew @xster If the issue was a local problem, shouldn't this be updated back to `2.0.0-dev.20.0`? The newer version contains [a significant amount of fixes (143 commits)](https://github.com/dart-lang/sdk/compare/2.0.0-dev.19.0...2.0.0-dev.20.0).

**Comment by devoncarew** [comment]
We needed a version newer than dev.16; dev.20 is ahead of what our internal system is using (which we don't like to be ahead of).

**Pull request merged**
