### PR TITLE
serve the generated main.dart file so source_maps work for it

### PR DESCRIPTION
**Pull request by jakemac53**
## Description

Writes the generated `main.dart` file for flutter web apps to the web asset server so it can be served.

This fixes source maps for the root entrypoint.

## Related Issues

https://github.com/flutter/flutter/issues/50753

## Tests

I couldn't find any existing integration tests where I could ensure this file is served, if one does exist please point me at it and I would be happy to update it :). 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jakemac53** [comment]
Actually I found the right test, although it is currently skipped.

Note that if I remove the `IOOverrides` zone the test does pass though.

**Comment by jonahwilliams** [comment]
I had some issues with it failing locally - though if you comment out the skip/remove the IOOverrides and it passes that is good enough for me

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jakemac53** [comment]
I haven't unskipped the test for now - mostly just noting that the new expect does in fact pass when ran locally.

**Pull request merged**
