### PR TITLE
added default springDescription parameter to AnimationController

### LINKED ISSUE #76016: ability to change default fling springDescription of AnimationController
i'm proposing to allow changing the default springDescription for the AnimationController. changing it for a single `fling` call is already possbile via parameter on the same name. to not change it every time we use the fling, we could just allow changing the default one for a whole controller

### PR DESCRIPTION
**Pull request by nt4f04uNd**
fixes https://github.com/flutter/flutter/issues/76016

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Comment by goderbauer** [comment]
It looks like you can already change the spring by providing one to the fling method: https://master-api.flutter.dev/flutter/animation/AnimationController/fling.html

It is not clear to me what advantage this change has. It does seem to make the API more complicated, though, by adding another property that's only used for one specific function.

**Comment by nt4f04uNd** [comment]
this would make it more convenient if you often use fling per some controller instance. i don't agree this would make api any more complicated, i could remove this from constructors though
a controller design mistake that we have only one controller both for simulations and ordinary transitions - this what can make people be more confused than this i believe

**Comment by goderbauer** [comment]
My comment from above still stands, I don't see the value of this change.

**Comment by nt4f04uNd** [comment]
@goderbauer is this not convincing to you https://github.com/flutter/flutter/issues/76016#issuecomment-780913163 ?

**Comment by goderbauer** [comment]
Not really. It seems pretty easy to just pass in the springDescription you want.

**Pull request closed without merging**
