### PR TITLE
Merge branch 'stable' of https://github.com/flutter/flutter into stable

### PR DESCRIPTION
**Pull request by gavin-fromm**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jmagman** [comment]
@gavin-fromm Out of curiosity why did you try this?  Trying to figure out why we keep seeing PRs from folks trying to merge the stable branch, yours isn't the first.

**Comment by gavin-fromm** [comment]
@jmagman Hello, my apologies. I am a college student and am new to flutter. I was having an issue merging a branch, and VS code suggested a bunch of commits for the flutter/flutter branch. I was not sure as to what exactly would happen, so I just assumed it was helping me update my local project.  Sorry again.

**Comment by jmagman** [comment]
It's no problem, I'm just curious how this keeps happening.  So VS Code prompted you to open a pull request?  Do you remember the exact steps that reproduced that prompt?

**Comment by gavin-fromm** [comment]
image
I am pretty sure I clicked "Sync Changes" and this window popped up
image
If you click "Ok" this windows pops up
image

**Comment by jmagman** [comment]
Thanks for the info! Once you chose Create Fork, I would have thought that would have created a fork and pushed to a branch there. Did you take additional steps to actually create the pull request?

**Comment by gavin-fromm** [comment]
Yes, that is what occurred.

**Pull request closed without merging**
