### PR TITLE
Roll Plugins from f4ca73237db8 to 99aa799ea07a (11 revisions)

### LINKED ISSUE #104453: google_maps_flutter_web has prefer_const_literals_to_create_immutables info warnings
On engine roll https://github.com/flutter/flutter/pull/104431 new plugin warnings, `Linux flutter_plugins` is failing, tree is closed 
```
Analyzing google_maps_flutter_web...

   info - example/integration_test/google_maps_controller_test.dart:148:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:149:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:162:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:163:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:176:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:177:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:190:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:191:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:236:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:237:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:246:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:247:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:256:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:257:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:266:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:267:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8813346359515629377/+/u/run_test.dart_for_flutter_plugins_shard_and_subshard_analyze/test_stdout

### PR DESCRIPTION
**Pull request by engine-flutter-autoroll**
Fixes https://github.com/flutter/flutter/issues/104453

https://github.com/flutter/plugins/compare/f4ca73237db8...58478a525

2022-05-23 magder@google.com [google_maps_flutter] Fix prefer_const_literals_to_create_immutables (flutter/plugins#5811)
2022-05-23 stuartmorgan@google.com [google_maps_flutter] Updates platform interface to new analysis options (flutter/plugins#5793)
2022-05-23 martin.georgiu@gmail.com [Camera] Return all possible cameras on iOS (flutter/plugins#5636)
2022-05-23 tttkhs@naver.com [google_sign_in, in_app_purchase_android] Add availability to mock models (flutter/plugins#5642)
2022-05-21 engine-flutter-autoroll@skia.org Roll Flutter from de7c23e7e963 to ec20ea80ad98 (1 revision) (flutter/plugins#5805)
2022-05-21 engine-flutter-autoroll@skia.org Roll Flutter from b8b0c807bbe5 to de7c23e7e963 (1 revision) (flutter/plugins#5804)
2022-05-21 engine-flutter-autoroll@skia.org Roll Flutter from 4654fd011d13 to b8b0c807bbe5 (1 revision) (flutter/plugins#5803)
2022-05-21 engine-flutter-autoroll@skia.org Roll Flutter from 6aaabf6d5695 to 4654fd011d13 (2 revisions) (flutter/plugins#5802)
2022-05-21 engine-flutter-autoroll@skia.org Roll Flutter from 1e10ceceb036 to 6aaabf6d5695 (1 revision) (flutter/plugins#5800)
2022-05-21 engine-flutter-autoroll@skia.org Roll Flutter from 1e1f4bcfb561 to 1e10ceceb036 (6 revisions) (flutter/plugins#5799)
2022-05-21 engine-flutter-autoroll@skia.org Roll Flutter from a4a8e73bce15 to 1e1f4bcfb561 (65 revisions) (flutter/plugins#5795)
2022-05-20 asashour@yahoo.com [google_sign_in] Suppress `deprecation` warnings (flutter/plugins#5049)

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/flutter-plugins-flutter-autoroll
Please CC flutter-ecosystem@google.com on the revert to ensure that a human
is aware of the problem.

To file a bug in Flutter: https://github.com/flutter/flutter/issues/new/choose

To report a problem with the AutoRoller itself, please file a bug:
https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

### CODE REVIEW

**Comment by engine-flutter-autoroll** [comment]
Commit queue failed; closing this roll.

**Comment by jmagman** [comment]
Reopening and rebasing on main, will hopefully close https://github.com/flutter/plugins/pull/5793 by picking up https://github.com/flutter/plugins/pull/5793

**Comment by jmagman** [comment]
Adding reviewers so I can merge manually when https://ci.chromium.org/p/flutter/builders/try/Linux%20flutter_plugins/26159 passes.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by bparrishMines — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
https://ci.chromium.org/p/flutter/builders/try/Linux%20flutter_plugins/26159 still failed:
```
   info - example/integration_test/google_maps_controller_test.dart:148:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:149:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:162:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:163:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:176:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:177:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:190:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_controller_test.dart:191:17 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:236:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:237:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:246:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:247:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:256:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:257:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:266:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
   info - example/integration_test/google_maps_plugin_test.dart:267:11 - Prefer const literals as parameters of constructors on @immutable classes. - prefer_const_literals_to_create_immutables
```

**Comment by bparrishMines** [comment]
Yea, it looks like `google_maps_flutter_web` was missed in the PR: https://github.com/flutter/plugins/pull/5793

**Comment by bparrishMines** [comment]
I can create a PR, but I'm not sure why our CI didn't catch this

**Comment by jmagman** [comment]
> I can create a PR, but I'm not sure why our CI didn't catch this

Actually I already got it in https://github.com/flutter/plugins/pull/5811.
Updated this roll to that SHA.

**Comment by jmagman** [comment]
Woot analysis passed https://ci.chromium.org/p/flutter/builders/try/Linux%20plugin_test/16601.
Merging.

**Pull request merged**
