### PR TITLE
Update ListTile to match M3 spec

### LINKED ISSUE #127075: Update ListTile to match M3 specs
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

_I am currently finalising a PR that addresses these issues._

### Steps to reproduce

See code sample.

### Expected results

- IconButtons are not correctly aligned in a ListTile
    - padding causes `IconButton`s to not align with `Icon`s
    - This also impacts CheckboxListTile, RadioListTile and SwitchListTile. It does not impact ExpansionTile.

- ListTile text uses M2 baseline alignment rather than box-stacking
    - M3  spec is to stack the text boxes and centre or top align depending on size

- ListTile missing overline text element
    - Both M2 & M3 have an overline label available above the headline that is not present

- ListTile cannot create 64x114 video leader for M3 (*)
    - height is restricted to 56dp

- ListTile incorrect trailing icon and text colour M3
    - uses `onSurface`, should be `onSurfaceVariant`

- ListTile 8dp padding not applied for 56dp high leading image in one-line tile M3

- ListTile 12dp padding not applied for three-line M3
    - uses default 8dp padding
    - it would also not be applied if 64dp high video was available as per (*)

- ListTile having video leader flush with start requires manually setting all padding
    - Use case: Ergonomic issue - requires the developer to know not to see the vertical padding.
    - Proposal: Declarative properties on ListTIle to tell it the type of the leading or trailing element.
    Eg:
        - https://github.com/jamesgorman2/flutter/blob/1a1b07772db26a76004526a9d74118382160ed1d/packages/flutter/lib/src/material/list_tile.dart#L335
        - https://github.com/jamesgorman2/flutter/blob/1a1b07772db26a76004526a9d74118382160ed1d/packages/flutter/lib/src/material/list_tile.dart#L1208

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        visualDensity: VisualDensity.standard,
      ),
      home: Scaffold(
        body: SingleChildScrollView(
          child: Column(
            children: [
              const SizedBox(height: 8),
              ListTile(
                tileColor: Colors.black26,
                leading: const SizedBox(
                  height: 56,
                  width: 56,
                  child: Placeholder(),
                ),
                title: const Text('56x56 image'),
                onTap: () {},
              ),
              ListTile(
                tileColor: Colors.black12,
                
                leading: const SizedBox(
                  height: 64,
                  width: 114,
                  child: Placeholder(),
                ),
                title: const Text('64x114 video'),
                onTap: () {},
              ),
              ListTile(
                tileColor: Colors.black26,
                isThreeLine: true,
                leading: const SizedBox(
                  height: 64,
                  width: 114,
                  child: Placeholder(),
                ),
                title: const Text('Three line video'),
                subtitle: const Text('Should have 12 dp padding top and bottom'),
                onTap: () {},
              ),
              ListTile(
                tileColor: Colors.black12,
                title: const Text('One line icon'),
                trailing: const Icon(Icons.more),
                onTap: () {},
              ),
              ListTile(
                tileColor: Colors.black26,
                title: const Text('One line iconButton'),
                trailing: IconButton(
                  onPressed: () {},
                  icon: const Icon(Icons.more),
                ),
                onTap: () {},
              ),
              ListTile(
                tileColor: Colors.black12,
                isThreeLine: true,
                title: const Text('Three line icon'),
                subtitle: const Text('Top right aligned'),
                trailing: const Icon(Icons.more),
                onTap: () {},
              ),
              ListTile(
                tileColor: Colors.black26,
                isThreeLine: true,
                title: const Text('Three line iconButton'),
                subtitle: const Text('8 dp down and left from the plain icon'),
                trailing: IconButton(
                  onPressed: () {},
                  icon: const Icon(Icons.more),
                ),
                onTap: () {},
              ),
              const ExpansionTile(
                backgroundColor: Colors.black12,
                title: Text('Exansion tile'),
                subtitle: Text('You can see the 1px gap above when hovering or holding'),
                children: [
                  ListTile(
                    title: Text('Expansion child'),
                  ),
                ],
              ),
              const ExpansionTile(
                backgroundColor: Colors.black26,
                title: Text('Exansion tile'),
                subtitle: Text('Expand both of us to see the double line'),
                children: [
                  ListTile(
                    title: Text('Expansion child'),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel m3_list_tile, 3.11.0-6.0.pre.132, on macOS 12.6.5 21G531 darwin-arm64, locale en-AU)
    ! Upstream repository git@github.com:jamesgorman2/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:jamesgorman2/flutter.git to dismiss this error.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] VS Code (version 1.76.1)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by jamesgorman2**
Fixes #127075

This PR is larger than I'd like but it needed to cover a lot of ground. This code _should_ only impact M3 ListTiles by default.

`ListTile`
* add `overline` with color and style 
    * for both M2 and M3 
    * update assertions
* add `leadingAndTrailingTextColor` 
     * for both M2 and M3
* add M3 text layout * vertically align text elements by box 
     * top align box if `isThreeLine` or tile height > 88; otherwise 
     * center align box
* add `material3` leading/trailing 
     * same as `threeLine` but will top align if tile height > 88
* increase vertical padding to 12dp when `isThreeLine`
* add `ListTileConstraint` and `ListTilePaddingCorrection` to: 
     * constrain the max size of the leading/trailing widget 
     * force a minimum tile height 
     * specify a leading/trailing title gap 
     * ignore the start/end padding (for large widgets like video) 
     * apply a padding correction to align leading/trailing widgets
* add sensible defaults for `ListTileConstraint`
* refactor layout logic * the addition of `overline` and `ListTileConstraint` significantly increases branching
* documentation 
     * fix links to M2/M3 specs 
     * additional `See also`s

[NEW] `examples/../list_tile.5.dart`
* render the M3 spec list examples
* allow switching to M2, platform density, rtl, dark mode, dividers

`examples/../list_tile.[2, 4].dart`
* update with new defaults
* update tests as needed

`EdgeInsetsGeometry`
* add a method to convert `EditInsetsGeometry` to `EdgeInsetsDirectional`. Inverse of `resolve()`

`CheckBoxListTile`, `RadioListTile`, SwitchListTile`
* apply padding correction
* add `overline`, `secondaryConstraint` and `titleAlignment`
* update constructor assertions
* update tests as needed

`ExpansionTile`
* allow optional dividers when expanded
* use `Divider.createBorderSide()` to create `BorderSide`
* dividers are drawn over the `ExpansionTile`, not as padding
* add `overline`, `titleAlignment`, `isThreeLine`, `leadingConstraint` and `trailingConstraint`
* `trailing` moved to widgets section
* M3 icon color updated
* update tests as needed

`Switch`
* remove no-op maths

`gen_defaults.dart`
* fix typo

Not addressed:
 * difference between flutter Material and the M2 spec 
      * except leading video widget layout and how vertical text overlap is handled

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by HansMuller** [comment]
This is definitely an ambitious PR and we welcome changes that bring the Material library closer to the Material Design spec. And we're always glad to see new examples! That said, there are some things to worry about:

- It breaks lots of tests (many of which have been patched up here). This will cause problems for apps with tight layouts and golden image tests.
- It bundles many related changes together. Breaking it up into small more narrowly scoped PRs will help. This PR could probably be factored into a dozen.

**Comment by jamesgorman2** [comment]
> It breaks lots of tests (many of which have been patched up here). This will cause problems for apps with tight layouts and golden image tests.

I can only see one failure left (Linux customer_testing / goldens/material_test.drawer.png). I assume flutter-gold has more tests? Is there a way to run either of these locally?

**Comment by jamesgorman2** [comment]
> It bundles many related changes together. Breaking it up into small more narrowly scoped PRs will help. This PR could probably be factored into a dozen.

To save my sanity my recommended approach would then be (and given @huycozy has asked for the same thing in #127075):
* I break out #127075 into component issues, use #127075 to track all of them for future reference
* Flutter reviewers new issue (with this PR as a reference, but not actually reviewing the PR)
     * fix as is in this PR (as separate PR)
     * fix with new architecture or specific default behaviour requirements (only if it can be determined quickly)
     * won't fix
     * on hold
* I do the thing and put in PRs as needed.

Does this approach work for you?

Breaking out some of the PR is trivial but a large chunk of it would be a massive merge conflict. I'd rather have confidence that any breaking out is going to be used before doing it.

**Comment by TahaTesser** [comment]
Hi @jamesgorman2 

First of all, kudos for the effort you put into this PR.

While this PR gives an overview of the issues you're attempting to fix, it's not ideal for several reasons.

1. A Pull Request should be focused, usually fixing one widget or a narrow problem across different widgets in the framework.

Sometimes when working on bugs and new features for a single widget you might also require splitting the changes into multiple focused PRs. For instance, One PR  or more PR fixes multiple bugs, another for a new feature, and one for updating examples. Such PRs are more clear on what changes are being made and for what reason.

2. You've modified a bunch of existing tests, probably because they were failing due after introducing the changes. These tests are difficult to verify and test against in a PR like this.

Because of these reasons, this PR cannot be landed. 

This might require multiple PRs based on the type of fixes and features.

Before you split and file new PRs, I recommend discussing the changes in the issues since the changes aren't straightforward.  After the discussion, you can start with a smaller and more focused PR.  Which will be easier to test, review and approve.

I'm closing this PR for the reasons explained above, you can keep the branch for reference for any potential new PRs.

**Pull request closed without merging**
