### PR TITLE
Revert "[Material] Update TabController to support dynamic Tabs"

### PR DESCRIPTION
**Pull request by johnsonmh**
Reverts flutter/flutter#30884

This is a temporary revert while some of our customers deal with the breaking changes involved.

### CODE REVIEW

**Comment by HansMuller** [comment]
This PR should fix the problems we ran into: https://github.com/flutter/flutter/pull/32434

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
@johnsonmh can we delete the branch for this?

**Comment by johnsonmh** [comment]
Done!

**Pull request closed without merging**
