### PR TITLE
Remove duplicate error parts

### PR DESCRIPTION
**Pull request by miDeb**
This also caused an additional error 

> FlutterError contained multiple error summaries

## Description

No other changes were made.

## Related Issues

I have not found any related issues

## Tests

I added the following tests:

None

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by miDeb** [comment]
Sorry if I was not clear; The only thing I did was that I removed duplicate code. You can see that exactly the same error parts were already added to `errorParts` because they are already in the List `information` which is then added to `errorParts`. The reason why I noticed it was that flutter threw an additional error because of two `ErrorSummary`s in the list which looks like it is not allowed.
The reason why the original error was thrown was that there was a bug in my code. 🤷

**Comment by Piinks** [comment]
Thank you for clarifying.
It looks like there is a failing test here. You may need to update your branch with changes from master to resolve that failure.

**Comment by miDeb** [comment]
Is there anything I can do?

**Comment by Piinks** [comment]
Hi @miDeb, I've had something similar happen before, there is a way to fix it. 
Is there any chance you used `git rebase` when updating your branch? This can happen when updating a branch using rebase.
I've fixed it in the past by using `git reflog` and then resetting to a point before I rebased. Pushing your updates to remote then will probably need a force.
As for updating the branch, pulling instead of rebasing should avoid this. :)

**Comment by Piinks** [comment]
Thanks for updating your branch! I'm not sure why these `release_smoke_tests` are failing, cc @dnfield, do you recognize the issue here?

**Comment by dnfield** [comment]
That's safe to ignore.  I'll fix this today

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

Thanks for sticking with this! We can land this on the failing test after chatting offline with @dnfield.

**Comment by dnfield** [comment]
https://github.com/flutter/flutter/pull/35130 is the fix

**Pull request merged**
