### PR TITLE
[CP] `beta` 138434 flutter tools pathnotfoundexception

### PR DESCRIPTION
**Pull request by eliasyishak**
Fixes:
- https://github.com/flutter/flutter/issues/138434

Cherry pick into Beta issue:
- https://github.com/flutter/flutter/issues/140006

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
@godofredoc do we need to branch recipes for beta?

> Uncaught Exception: AssertionError('analyze is not listed in available_validations.')

https://github.com/flutter/flutter/pull/140005/checks?check_run_id=19576191609

**Comment by CaseyHillers** [comment]
> @godofredoc do we need to branch recipes for beta?

This should have been fixed in https://github.com/flutter/cocoon/pull/3305. Let me try rerunning, maybe there was a Cocoon issue where it was rolled back to an older version.

I've gone ahead and manually rerun the two failing targets to see if that gets them passing.

**Comment by eliasyishak** [comment]
@CaseyHillers those two checks seem to be stuck, I'm going to push an empty commit to see if that restarts them

**Comment by CaseyHillers** [comment]
@eliasyishak I think there's an issue with your checkout. I'm going to land on red to bypass the presubmit check, but your branch should've included https://github.com/flutter/flutter/pull/139161 which I'm not seeing.

**Pull request merged**
