### PR TITLE
Revert "Reland "Update PopupMenuButton to match Material Design spec""

### PR DESCRIPTION
**Pull request by Piinks**
Reverts flutter/flutter#74620

This is breaking a lot of internal tests that were not part of the batch of Google tests executed on the PR.

cc @xu-baolin @renyou

### CODE REVIEW

**Review by xu-baolin — APPROVED** [review]
LGTM, thanks for revert

**Comment by Piinks** [comment]
> LGTM, thanks for revert

Thanks @xu-baolin, still confirming :)

**Comment by xu-baolin** [comment]
The last commit(update to master channel) introduces a change and causes the compile error.

**Comment by xu-baolin** [comment]
@Piinks Hi,
Please let me know if there is any progress of what internal tests being broken, thanks. : )

**Comment by Piinks** [comment]
Hey @xu-baolin can you open another PR to reland this? I can verify the status easier by referencing a PR. :)

**Pull request merged**
