### PR TITLE
Fix text_style_text.dart to be Dart 2 compliant.

### PR DESCRIPTION
**Pull request by mraleph**
In Dart 2 mode we throw different exception: compiler generates
throw of a compilation error instead of runtime throwing
noSuchMethod.

### CODE REVIEW

**Comment by tvolkert** [comment]
Does the compilation error type exist in 2.0.0-dev19?  If so, we could match against either type instead of a generic matcher.

/cc @Hixie

**Comment by mraleph** [comment]
It's a private class `_CompileTimeError` and not a part of public Dart core libraries interface, so you can't match against it.

**Comment by tvolkert** [comment]
Hmm - is there no use case where someone would want to catch that error?

**Comment by mraleph** [comment]
You can still catch an error, you just can't necessarily identify it. 

If you want to write test against compiler you can do it using compiler APIs.

I mean you don't write C++ unit tests like this:

```
class C {
  C(intptr_t foo) : foo(foo) { }
  const intptr_t foo;
}

TEST(CanNotAssignToFoo) {
  C c(10);
  try {
    c.foo = 20;
  } catch (...) {
  }
}
```

you trust the compiler to handle this correctly.

**Comment by tvolkert** [comment]
Fair enough 😄 

FYI, looks like analysis is failing:

```
[hint] 'throws' is deprecated and shouldn't be used. (packages/flutter/test/painting/text_style_test.dart, line 26, col 44)
```

Maybe use `throwsA(const isInstanceOf<Error>())`

**Comment by mraleph** [comment]
@tvolkert done.

**Review by tvolkert — APPROVED** [review]
LGTM

**Pull request merged**
