### PR TITLE
Move FLUTTER_HOME to FLUTTER_ROOT in gradle plugin

### PR DESCRIPTION
**Pull request by charafau**
I Moved FLUTTER_HOME to FLUTTER_ROOT in gradle plugin specified in issue:

https://github.com/flutter/flutter/issues/10065

### CODE REVIEW

**Comment by charafau** [comment]
I signed it!

**Comment by Hixie** [comment]
cc @tvolkert

**Review by jakobr-google — APPROVED** [review]
LGTM

**Review by tvolkert — APPROVED** [review]
LGTM

**Pull request merged**
