### PR TITLE
Palette generator

### PR DESCRIPTION
**Pull request by gspencergoog**
This adds a palette generator that will take an image and generate a set of distinct, dominant colors from it.  This is more or less a port of the [Android Palette](https://android.googlesource.com/platform/frameworks/support/+/android-8.1.0_r33/v7/palette/src/main/java/android/support/v7/graphics/Palette.java) class, except that it doesn't automatically resize the image if it is too large.

For instance, given this image:
landscape

It will generate this palette of colors from it:
palette

Where the leftmost color is the more prominent distinct color, and the rightmost is the least. (Just to be clear, it generates the metadata for the colors, not an image like the one above.... :-)).

[Note that this PR also includes the HSLColor class and changes that are currently up for review in #18294, so you can ignore those and review that PR instead for those changes.  I'll merge that one first.]

### CODE REVIEW

**Comment by Hixie** [comment]
Given how self-contained this code is, would it make sense to publish it as a package instead? It's not clear that it needs to be part of the core framework.

**Comment by gspencergoog** [comment]
Good point.  Where do Flutter-maintained packages live? [flutter/packages](https://github.com/flutter/packages)? (which seems to be entirely empty!)

**Comment by gspencergoog** [comment]
Moving this to the [flutter/packages](https://github.com/flutter/packages) repo.
See flutter/packages#2

**Comment by lukepighetti** [comment]
@gspencergoog any chance you can post it on https://pub.dartlang.org/flutter so we can use this before it gets pulled into flutter/packages ? 

(Or is there another way I can use it?)

**Comment by zoechi** [comment]
@lukepighetti should just work with https://www.dartlang.org/tools/pub/dependencies#git-packages

**Comment by lukepighetti** [comment]
@zoechi Thank you

**Pull request closed without merging**
