### PR TITLE
Roll Engine from 83cfdcc8f101 to b5162c93f513 (1 revision)

### PR DESCRIPTION
**Pull request by jason-simmons**
b5162c93f Use the SkParagraph text renderer by default (flutter/engine#28912)

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/97180

**Review by zanderso — APPROVED** [review]

**Review by gaaclarke — APPROVED** [review]

**Comment by Hixie** [comment]
this was landed in a way that included disabling flutter/tests tests (https://github.com/flutter/tests/pull/123) and that broke the packages repo.

In general if we need to land something in a way that violates our usual processes, we should make everyone extremely aware of this, at a minimum notifying the #announcements and #tree-status channels and making sure people are ready for any upstream breakage.

**Comment by zanderso** [comment]
@jason-simmons SkiaPerf has detected regressions for this change: https://flutter-flutter-perf.skia.org/e/?begin=1642805039&end=1643168414&keys=Xf98240cb6f1160c361037486d85f96fa&requestType=0&xbaroffset=27306

Are these expected? The flutter gallery transition perf worst frame increasing by 4x seems fairly severe.

**Comment by jason-simmons** [comment]
I tried running various Gallery iOS benchmarks on an iPhone 7.  But so far I've been unable to reproduce the large change in `worst_frame_build_time_millis`.

Also not sure why this would only affect iOS benchmarks.  I have not seen anything like that in the Android benchmarks.

**Comment by jason-simmons** [comment]
I did some profiling of Gallery startup on iOS with SkParagraph.  One aspect of SkParagraph that may be contributing to increased startup time is SkShaper's font loader.

SkShaper's `create_hb_face` is calling `SkTypeface::openStream` to load font assets into memory.  The implementation used on iOS (`SkTypeface_Mac::onOpenStream`) calls various CoreText APIs to read font metadata and extract the font's tables.  This appears to be more expensive than the approach used by Libtxt/Minikin.

Gallery needs to load several fonts during startup.  This is a one-time cost - after the font is loaded SkShaper stores it in a cache.

**Comment by zanderso** [comment]
> SkShaper's create_hb_face is calling SkTypeface::openStream to load font assets into memory. The implementation used on iOS (SkTypeface_Mac::onOpenStream) calls various CoreText APIs to read font metadata and extract the font's tables. This appears to be more expensive than the approach used by Libtxt/Minikin.

Can any of this work be done asynchronously or ahead-of-time? Can SkParagraph adopt the faster approach of libtxt? @jason-simmons can you follow up on this with the Skia folks?

**Comment by zanderso** [comment]
Assuming this is related, but I also just noticed a regression in memory footprint on iOS on this change: https://flutter-flutter-perf.skia.org/e/?begin=1643075719&end=1643149114&keys=X6f655a2116d0334351964dd6b09e79e7&num_commits=50&request_type=1&xbaroffset=27306

**Pull request merged**
