### PR TITLE
Change from plural to singular

### LINKED ISSUE #5702: Gallery, Contacts: it's labeled as "contacts" plural, but we display a single contact
Noticed in a user test. They wondered why it was called "Contacts" if there was only one person/contact. They were looking for the rest of the contacts.

Strawman suggestion: rename to "Contact profile" in the homescreen.

### PR DESCRIPTION
**Pull request by sethladd**
Closes #5702

### CODE REVIEW

**Comment by HansMuller** [comment]
You'll also need to update examples/flutter_gallery/test_driver/transitions_perf_test.dart and /builds/dev/flutter/examples/flutter_gallery/test/simple_smoke_test.dart

You just got lucky with the second one.

**Comment by dragostis** [comment]
You also need to rename the smoke test in [transitions_perf_test.dart](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/test_driver/transitions_perf_test.dart#L28).

**Comment by HansMuller** [comment]
LGTM

**Comment by sethladd** [comment]
thanks! updated the two other places in the tests.

**Comment by sethladd** [comment]
Blocked by https://github.com/flutter/flutter/issues/5716

**Pull request merged**
