### PR TITLE
Reland "Refactor ThemeData  (#91497)" (part 1)

### PR DESCRIPTION
**Pull request by guidezpl**
Reland most of #91497, which was reverted in #92820.

The re-ordering of business logic in the factory constructor seems to have caused a change in some buttons' background color. This PR includes all of #91497, minus the re-ordering of that logic.

### CODE REVIEW

**Review by darrenaustin — APPROVED** [review]
Yeah, the ThemeData initialization code is a bit brittle and subtle. Easy to break.

LGTM.

**Comment by Piinks** [comment]
(Breaking change audit) Hey @guidezpl I noticed this was reverted for breaking internal tests, did these updates (part 1 & 2) make it non breaking? Or was the internal code migrated? If the later, this should have a migration guide under breaking changes on the website.

**Comment by darrenaustin** [comment]
I am pretty sure this was an ordering issue with some initialization code. The fix was reordering it in such a way that it maintained the previous behaviour. This shouldn't be a breaking change.

**Comment by Piinks** [comment]
Thanks @darrenaustin! :)

**Pull request merged**
