### PR TITLE
[WIP] :bug: (VelocityTracker) Handle case where velocity is infinite

### PR DESCRIPTION
**Pull request by guitoof**
This Pull Request aims to fix this issue: [#101579](https://github.com/flutter/flutter/issues/101579)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Piinks** [comment]
Hi @guitoof welcome, thanks for the contribution!

Before we can review this, it will need a test to verify the change works as expected, and to ensure we do not undo this change in the future. It also looks like there are several currently failing tests, and the cla will need to be signed as well by following the instructions from the google bot above.

**Comment by guitoof** [comment]
Hi @Piinks, thank you very much for your reply. I signed the CLA and I am currently working on adding tests to the Pull Request to comply.
Can I add somehow a WIP tag to specify that it is not yet ready for review?

**Comment by Piinks** [comment]
You can put WIP in the title, or mark this as a draft PR in the github UI. Thanks for the update!

**Comment by goderbauer** [comment]
@guitoof (triage): Looks like this PR is failing a bunch of checks. Could you please take a look?

**Comment by guitoof** [comment]
HI @goderbauer, I am taking a look but I am having trouble understanding how to fix them because the test failing do not seem to be related to my changes. I am setting this PR back to WIP to let you know that it's not ready for review. Sorry for the inconvenience

**Comment by goderbauer** [comment]
@guitoof If the test failures are unrelated you can try rebasing in the latest master and see if that makes the tests pass.

**Comment by goderbauer** [comment]
(triage): I am going to close this one for now since there hasn't been any follow-up. Looks like we have an issue on file for this and please feel free to reopen the PR if you have time to work on this again.

**Pull request closed without merging**
