### PR TITLE
Reland Scribble mixin

### PR DESCRIPTION
**Pull request by justinmc**
Scribble mixin (https://github.com/flutter/flutter/pull/104128) has been reverted several times due to breaking Google tests, most recently in flutter/flutter#115146.  This PR is an attempt to reland it.

Also, it seems to have caused a performance regression: https://github.com/flutter/flutter/issues/114898

Before merging this reland, we should be sure that the test failure and the performance problem are fixed.

Google bug for last failure: https://buganizer.corp.google.com/issues/258924157

### CODE REVIEW

**Comment by justinmc** [comment]
Removing draft status in order to run Google tests.

**Comment by justinmc** [comment]
I looked over the code again and didn't see anything suspicious for the performance regression...  I have not rerun the benchmark though.

**Review by CaseyHillers — APPROVED** [review]
RSLGTM for triggering Google Testing

**Comment by goderbauer** [comment]
(Triage): @justinmc Do you still have plans for this one?

**Comment by justinmc** [comment]
Yes, I'll take a closer look at the Google test failures this week.

**Comment by jmagman** [comment]
If this is still in progress, can we change the names back ASAP in a smaller PR to resolve https://github.com/flutter/flutter/issues/119180?

@moffatman in https://github.com/flutter/flutter/issues/119180#issuecomment-1404245331
> Maybe the best way to fix is to first change the names back, then land the rest of the changes? That would be easiest to cherry-pick. @justinmc

**Comment by justinmc** [comment]
Ah it didn't cross my mind that the engine PR would start breaking things since this was reverted.  I'm trying to get this back up to speed.

**Comment by goderbauer** [comment]
(triage) Can this one be closed in favor of https://github.com/flutter/flutter/pull/119739?

**Comment by justinmc** [comment]
Let me see if the tests pass on https://github.com/flutter/flutter/pull/119739 (I accidentally committed the diff file so I just pushed again).  If it looks like this one has a problem then I'll close it.

**Comment by justinmc** [comment]
Both PRs seem to have identical Google test failures.  I will close one of the two PRs.

**Comment by goderbauer** [comment]
(triage) @justinmc Do you still have plans for this one?

**Comment by justinmc** [comment]
I'm going to update this and make another attempt at seeing why it fails Google tests.

**Comment by justinmc** [comment]
Closing this as I won't have time to fix it for awhile.  Hoping to come back and fix the Google failures at some point.

**Pull request closed without merging**
