### PR TITLE
integration_test: migrate to build.gradle.kts

### PR DESCRIPTION
**Pull request by bartekpacia**
This PR is yet another attempt (after #154125) to reland #142008.

Benefit: this will be the first plugin in Flutter repo that uses Gradle KTS for Android buildscripts. Once it works fine, we can follow up with migration of more plugins later.

[The previous error message](https://github.com/flutter/flutter/pull/142008#issuecomment-1939558432) was:

```
e: /b/s/w/ir/cache/gradle/caches/jars-8/42139b5be0c79e133a7b5c5c5d5bf731/gradle-7.3.1.jar!/com/android/build/gradle/LibraryExtension.class: Class 'com/android/build/gradle/LibraryExtension' was compiled with an incompatible version of Kotlin. The binary version of its bytecode is unknown, expected version is 1.0.3
e: /b/s/w/ir/cache/gradle/caches/jars-8/043c0d54e2c1bb39208ec4477607cdf5/gradle-api-7.3.1.jar!/com/android/build/api/dsl/LibraryVariantDimension.class: Class 'com/android/build/api/dsl/LibraryVariantDimension' was compiled with an incompatible version of Kotlin. The binary version of its bytecode is unknown, expected version is 1.0.3

FAILURE: Build failed with an exception.

* Where:
Build file '/b/s/w/ir/x/w/flutter/packages/integration_test/android/build.gradle.kts' line: 36

* What went wrong:
com.android.build.gradle.LibraryExtension.setNamespace(Ljava/lang/String;)V
```

The `integration_test` plugin now puts `com.android.tools.build:gradle:8.1.0` on its classpath since https://github.com/flutter/flutter/issues/153795.

This makes me take an optimistic bet that it won't kill the autoroller now 🤞

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by bartekpacia** [comment]
@reidbaker 

I made a mistake with the previous PR #154125 - I reverted it before letting all CI to finish running. So now I know this causes tree to break, but I know not much more.

I'm thinking of merging it, letting it run to the finish (likely marking the tree red), _then_ reverting and knowing what exactly fails, submit the final version.

**Comment by reidbaker** [comment]
I am about to head to vacation. @gmackall will need to make this decision.

**Comment by gmackall** [comment]
The tests should still run after the revert. The postsubmits will generally all run, regardless of future commits (unlike presubmits which cancel when you push a new commit)

**Comment by bartekpacia** [comment]
Thanks for explaining @gmackall.

In that case, all of the [the failing postsubmit tests](https://flutter-dashboard.appspot.com/#/build?hashFilter=e819a38292406ca770719656760c06a2a59b2b04&repo=flutter&branch=master) for the previous version of this PR (https://github.com/flutter/flutter/pull/154125) appear to be flakes.

I'm curious wdyt @gmackall and what course of action would you take

**Comment by gmackall** [comment]
> Thanks for explaining @gmackall.
> 
> In that case, all of the [the failing postsubmit tests](https://flutter-dashboard.appspot.com/#/build?hashFilter=e819a38292406ca770719656760c06a2a59b2b04&repo=flutter&branch=master) for the previous version of this PR (#154125) appear to be flakes.
> 
> I'm curious wdyt and what course of action would you suggest me to take

Sorry for the late reply - if all the post submit failures were flakes (which they do look like at first glance to me) then I would just reland the original pr with no changes

**Comment by bartekpacia** [comment]
thanks @gmackall

let's do this then

**Review by gmackall — APPROVED** [review]

**Pull request merged**
