### PR TITLE
Update Devicelab README with new dashboard information

### PR DESCRIPTION
**Pull request by CaseyHillers**
## Description

Add links to the different pages on the build dashboard. Update the color coding scheme for tasks.

Add the current list of capabilities the devicelab supports.

Remove old dashboard images

## Related Issues

https://github.com/flutter/flutter/issues/43095 updated the build dashboard to the version written in Flutter.

## Tests

No tests added since this just updates the documentation.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM!

**Comment by CaseyHillers** [comment]
@Hixie this removes the legacy devicelab images, and removes them from the grandfathered binary check. Is this okay? If so, how do I update the value for https://github.com/flutter/flutter/blob/master/dev/bots/analyze.dart#L1059?

I am not able to convert its value of `-3983063706891029293` to the correct hexadecimal value.

**Review by digiter — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Its 0xC8B950A9690274D3

**Comment by CaseyHillers** [comment]
Thanks Jonah!

**Comment by CaseyHillers** [comment]
I forgot this was opened. I am going to submit this since this only removes binaries, and does not add any.

**Pull request merged**
