### PR TITLE
[flutter_tools] configure dwds to not serve devtools

### LINKED ISSUE #52269: WebAssetServer.start > serveDevTools crash: NoSuchMethodError: The method 'toFilePath' was called on null.
```
--no-color run --machine --track-widget-creation --device-id=chrome lib\main.dart
```

```
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      defaultHandler (package:devtools_server/src/handlers.dart:28:60)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:144:21)
#3      DevTools.start (package:dwds/src/servers/devtools.dart:27:15)
#4      Dwds.start (package:dwds/dwds.dart:111:33)
#5      WebAssetServer.start (package:flutter_tools/src/build_runner/devfs_web.dart:85:36)
<asynchronous suspension>
#6      WebDevFS.create (package:flutter_tools/src/build_runner/devfs_web.dart:460:43)
#7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:421:44)
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1502:12)
#13     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#14     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:411:20)
<asynchronous suspension>
#15     AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:532:23)
#16     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:594:26)
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#23     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:1037:20)
#24     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:592:15)
#25     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:526:12)
#26     _rootRunUnary (dart:async/zone.dart:1134:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#31     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#32     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

This isn't necessary for any current functionality. Fixes https://github.com/flutter/flutter/issues/52269

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
RSLGTM

**Comment by NicTanghe** [comment]
Hello i must say i'm using the latest beta channel build and i'm still getting.
```

Oops; flutter has exited unexpectedly: "NoSuchMethodError: The method 'toFilePath' was called  
on null.
Receiver: null
Tried calling: toFilePath()".
```

**Comment by jonahwilliams** [comment]
> Hello i must say i'm using the latest beta channel build

The latest beta channel is older than this PR

**Comment by NicTanghe** [comment]
he latest release is from 17 march that is newer or is it older in another way ?

**Comment by jmagman** [comment]
This change is available in 1.15.19.  So at the moment it's on master and dev.  See https://flutter.dev/docs/development/tools/sdk/releases.

**Comment by nttd-jieyangxu** [comment]
Im sorry, but  i try two dev versions, that still happen. anything wrong?
dev version: 1.5.22 and 1.16.1

`Downloading Web SDK...                                              8.2s
Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...                                       [
flutter_doctor
](url)
13,882ms (!)
ERROR - 2020-03-20 11:06:30.426168
GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
dart:core                                              Object.noSuchMethod
package:dwds/src/handlers/injected_handler.dart 35:39  createInjectedHandler.<fn>.<fn>`
flutter_doctor

**Comment by jonahwilliams** [comment]
You're right, that is actually a different issue. Opening a new PR

**Comment by nttd-jieyangxu** [comment]
> You're right, that is actually a different issue. Opening a new PR

thank you!  the new PR foe web #1752

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/issues/52914

**Comment by AttSee** [comment]
Launching lib/main.dart on Chrome in debug mode...
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
Exited (sigterm)

1.15.17 beta

**Pull request merged**
