### PR TITLE
Update open_jdk version `version:11`

### PR DESCRIPTION
**Pull request by keyonghan**
For cipd package `open_jdk`, there are two ways to identify:
1) Tags: `version:11`
2) Refs: `11`

Existing targets are referencing the Refs:
```
{"dependency": "open_jdk", "version": "11"},
```

However, the Refs are not consistence across different platforms. This PR updates to use Tags to make all consistent.
```
{"dependency": "open_jdk", "version": "version:11"},
```

Context: https://github.com/flutter/flutter/pull/109889#issuecomment-1221165867

### CODE REVIEW

**Comment by jmagman** [comment]
Hitting https://github.com/flutter/flutter/issues/110112

**Review by jmagman — APPROVED** [review]
LGTM
Though this wound up not being necessary for the Mac arm case, it passed without this change when I added the `arm` tag. https://github.com/flutter/flutter/pull/109889

**Comment by keyonghan** [comment]
> LGTM Though this wound up not being necessary for the Mac arm case, it passed without this change when I added the `arm` tag. #109889

Yeah, those green builds didn't seem to pick up correct platforms. I believe this is needed. Adding the autosubmit label.

**Comment by jmagman** [comment]
This worked! https://ci.chromium.org/p/flutter/builders/try/Mac%20framework_tests_misc/25849 (still failed, but got past the open jdk installation).

**Pull request merged**
