### PR TITLE
Reland "Clean up some flutter_tools tests and roll dependencies"

### PR DESCRIPTION
**Pull request by jason-simmons**
This relands flutter/flutter#33163 with a fix to the integration_ui test.

### CODE REVIEW

**Review by tvolkert — APPROVED** [review]

**Comment by tvolkert** [comment]
LGTM assuming a green test run (it's not green now)

**Comment by tvolkert** [comment]
What's the status of this?

**Comment by jason-simmons** [comment]
I intended to land this yesterday but was running into build/CI infrastructure issues.  Will try again today.

**Comment by jonahwilliams** [comment]
I broke this again with my PR. I will rollback so this can be landed

**Comment by jonahwilliams** [comment]
cc @jason-simmons can you update and land this PR?

**Pull request merged**
