### PR TITLE
Fix error when choose noon on time picker

### PR DESCRIPTION
**Pull request by Arkangel12**
When using the TimePicker and set `alwaysUse24HourFormat` as `false` after choosing noon it shows `00:00 PM` which is wrong, you can see more details in my previous [PR](https://github.com/flutter/flutter/pull/72480) that was closed.

The time selected is fixed, now the user can choose noon and devs don't have to add extra code to show 12:00 PM when they are not using 24 hours format.

Testing was added to `time_test.dart` nothing else was changed.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by darrenaustin — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by dkwingsmt** [comment]
This PR seems to be causing a breakage in the tree. cc @darrenaustin

**Comment by darrenaustin** [comment]
@Arkangel12 thanks again for this PR. As you can see above, there was a hiccup in the automated tests that made it look like this broke the build. It didn't, as the test was unrelated to this commit. However, I had reverted it until I could figure out what was going on.

That said, as I was prepping to re-land this, I realized that I am not sure what this is fixing exactly. The test that was added will pass _without_ the changes to `hourOfPeriod`. `TimeOfDay.format` handles the noon case for both 24hr and 12hr time. 

What exactly was the issue you were trying to solve here? Can you open a new issue with a reproducible case of what you are trying to fix?

**Comment by Arkangel12** [comment]
Hello, @darrenaustin  you can find more details in [here](https://github.com/flutter/flutter/pull/72480).

This is an easy enhancement, basically, when you choose noon instead of showing you 12:00 pm it sent you 00:00 pm which is not right, that's it. 

i actually fix this in my code using and extension method because this makes no sense for the user, and I send the PR with the fix. that's it.

Please let me know if you find if this is wrong or if it can be improved, happy to help.

**Comment by darrenaustin** [comment]
So sorry I haven't been able to get back to this. I understand where my confusion came from. The issue has nothing to due with TImePicker, as it appears to be working fine. The issue was only with TimeOfDay. I have just landed a fix for that with PR #83947. Thanks again for your effort here and sorry for the confusion.

**Pull request merged**
