### PR TITLE
More beautiful linear_gradient sample

### PR DESCRIPTION
**Pull request by timsneath**
Tweak example so that it's more attractive to a design-oriented audience.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

### CODE REVIEW

**Comment by goderbauer** [comment]
Nice! I think we also need to adjust the description accompanying this example. It's not really "vertical window shades" we are showing now: https://github.com/flutter/flutter/blob/ebb48e16509fb7b375b4c239b7b5596239d9a5d2/packages/flutter/lib/src/painting/gradient.dart#L353.

**Comment by gspencergoog** [comment]
We are trying to add tests as a requirement for all changes, including examples, so adding a test here would be good.  We have examples of tests for examples in the `examples/api/test` dir.

**Comment by goderbauer** [comment]
@gspencergoog @Piinks Do we support golden tests in API samples? This seems to be the first one added to the API samples and its failing...

**Review by Piinks — COMMENTED** [review]
We don't currently, but I think it would work if you include

https://github.com/flutter/flutter/blob/ff3333d53624782d9085aacebab3b8cfbb56273c/packages/flutter/test/flutter_test_config.dart#L23

in a `flutter_test_config.dart` file in `examples/api/test`, like in the flutter package.

https://github.com/flutter/flutter/blob/master/packages/flutter/test/flutter_test_config.dart

**Comment by gspencergoog** [comment]
@goderbauer API Samples are just normal code now, so yes, they should support golden tests.

**Comment by gspencergoog** [comment]
Oh, I didn't know packages needed configuring to make goldens work, but I guess that makes sense.

**Comment by Piinks** [comment]
> Oh, I didn't know packages needed configuring to make goldens work, but I guess that makes sense.

Just for if they want to use https://flutter-gold.skia.org/, this repo doesn't use the default golden file configuration

**Comment by goderbauer** [comment]
I created https://github.com/flutter/flutter/pull/99298, which incorporates this PR and enables running golden tests for our API samples to make the newly added test pass. If that PR gets submitted, we can close this one.

**Comment by Piinks** [comment]
Closing per https://github.com/flutter/flutter/pull/99298#issuecomment-1057248356

**Pull request closed without merging**
