### PR TITLE
Detect VS Code IDE on Arch Linux

### PR DESCRIPTION
**Pull request by vially**
Add support for detecting the Visual Studio Code IDE when installed from the following packages on Arch Linux:
- [code](https://archlinux.org/packages/extra/x86_64/code/)
- [visual-studio-code-bin](https://aur.archlinux.org/packages/visual-studio-code-bin)
- [visual-studio-code-insiders-bin](https://aur.archlinux.org/packages/visual-studio-code-insiders-bin)

It looks like `flutter doctor` is unable to detect the version for `code`, due to the way it's packaged (e.g.: `package.json` is stored at `/usr/lib/code/package.json` while the [current logic](https://github.com/flutter/flutter/blob/3df4e735d5d0bd2db7930098eba1b3e620d77aa0/packages/flutter_tools/lib/src/vscode/vscode.dart#L67) is looking for it at `/usr/lib/code/resources/app/package.json`).

However, this only affects the official `code` package, so the `visual-studio-code-bin` and `visual-studio-code-insiders-bin` packages are unaffected:

```sh
$ flutter doctor -v
...
[✓] VS Code (version unknown)
    • VS Code at /usr/lib/code
    • Flutter extension version 3.78.0
    ✗ Unable to determine VS Code version.

[✓] VS Code (version 1.86.0-insider)
    • VS Code at /opt/visual-studio-code-insiders
    • Flutter extension version 3.78.0
...
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by bartekpacia — APPROVED** [review]
LGTM. Thanks for contributing!

**Review by christopherfujino — CHANGES_REQUESTED** [review]
Thank you for contributing!

I'm sorry, but I don't think we want to get into the business of supporting every possible way of installing the Flutter SDK on every possible linux distribution. Also, the Flutter AUR package is *not* officially supported, and we recommend just cloning the repo and adding the path to your PATH.

**Comment by vially** [comment]
> I'm sorry, but I don't think we want to get into the business of supporting every possible way of installing the Flutter SDK on every possible linux distribution. Also, the Flutter AUR package is *not* officially supported, and we recommend just cloning the repo and adding the path to your PATH.

I think there may be a misunderstanding about what this pull-request is supposed to fix.

This is **not** related to supporting alternative ways of installing the Flutter SDK. For what it's worth, that's exactly how the Flutter SDK was installed on my machine (e.g.: repo cloned and the binary added to PATH). This is about *detecting* the installation of the Visual Studio Code IDE by the `flutter doctor` command.

More precisely, without this change the Visual Studio Code IDE is not detected on Arch Linux by the `flutter doctor` command:

```sh
$ flutter doctor -v
...
[!] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/
```

After this change, the Visual Studio Code IDE is properly detected on Arch Linux by the `flutter doctor` command:

```sh
$ flutter doctor -v
...
[✓] VS Code (version unknown)
    • VS Code at /usr/lib/code
    • Flutter extension version 3.78.0
    ✗ Unable to determine VS Code version.

[✓] VS Code (version 1.86.0-insider)
    • VS Code at /opt/visual-studio-code-insiders
    • Flutter extension version 3.78.0
```

**Comment by christopherfujino** [comment]
> > I'm sorry, but I don't think we want to get into the business of supporting every possible way of installing the Flutter SDK on every possible linux distribution. Also, the Flutter AUR package is _not_ officially supported, and we recommend just cloning the repo and adding the path to your PATH.
> 
> I think there may be a misunderstanding about what this pull-request is supposed to fix.
> 
> This is **not** related to supporting alternative ways of installing the Flutter SDK. For what it's worth, that's exactly how the Flutter SDK was installed on my machine (e.g.: repo cloned and the binary added to PATH). This is about _detecting_ the installation of the Visual Studio Code IDE by the `flutter doctor` command.

Ahh, ok, you're right. I still do not want to support every possible installation path for vscode. However, I can see that we already (unfortunately) hard code other paths. Can you open a tracking issue for this and then ping me on it? I think this is something that will need greater discussion.

**Pull request closed without merging**
