### PR TITLE
[fuchsia] Runs stocks driver test on Fuchsia NUCs in devicelab

### PR DESCRIPTION
**Pull request by iskakaushik**
Also pushes `tiles` which is needed to host the flutter application on Fuchsia.

### CODE REVIEW

**Review by blasten — APPROVED** [review]

**Comment by iskakaushik** [comment]
This needs https://github.com/flutter/infra/pull/87 and https://chromium-review.googlesource.com/c/chromium/tools/build/+/2029567 to merge before we can land this.

**Comment by dnfield** [comment]
This may have failed...  Trying to rerun the job on luci, but for some reason the nuc timed out.

**Comment by dnfield** [comment]
https://ci.chromium.org/p/flutter/builders/prod/Linux/11005 is original run, https://ci.chromium.org/p/flutter/builders/prod/Linux/11006 is rerun

**Comment by iskakaushik** [comment]
@dnfield it succeeded in the attempt before: https://ci.chromium.org/p/flutter/builders/try/Linux/38

**Comment by dnfield** [comment]
It's had a few permission denied errors on reruns...

**Comment by dnfield** [comment]
https://chromium-swarm.appspot.com/task?id=4a274efcde9be610

**Comment by dnfield** [comment]
https://chromium-swarm.appspot.com/task?id=4a29ea686d2cec10

**Comment by dnfield** [comment]
I think we should revert this until we can figure out why it's having issues.

**Comment by iskakaushik** [comment]
@blasten fixed this forward https://github.com/flutter/flutter/pull/50122

**Comment by dnfield** [comment]
Ahh ok.  We're also having issues with capacity - this is making the nucs take a long time to schedule.  @godofredoc

**Pull request merged**
