### PR TITLE
Added an option to allow default fonts to not be packed in an flx file.

### PR DESCRIPTION
**Pull request by pylaligand**
Default fonts should never be bundled on Fuchsia.

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
How will you do custom fonts on Fuchsia then?

**Comment by pylaligand** [comment]
This really applies only to default fonts that Flutter normally caches and adds. From the look of it adding a font in the manifest should still work.

**Comment by Hixie** [comment]
How is this different from "includeRobotoFonts" then?

**Comment by abarth** [comment]
Previously we included roboto on iOS but not on Android.  We included the material design icons everywhere.  Perhaps we should have a flag that controls the material design icons specifically.

**Comment by pylaligand** [comment]
I changed the flag to be specifically about fonts that Flutter would normally cache itself - new patch coming up soon.

**Comment by Hixie** [comment]
Presumably we do want to pack the Material Design Icons file. That file gets revved, and it's critical that the app run with the version it expects.

In fact honestly I'd say the same about Roboto. Why would the app want to rely on the system fonts?

**Comment by abarth** [comment]
> Why would the app want to rely on the system fonts?

Because the system fonts have been arranged to correspond exactly with the app's needs because the app builds together with the system.

**Comment by Hixie** [comment]
Ah, well, ok, in that one _specific_ case... :-P

**Pull request merged**
