### PR TITLE
Bump Dart SDK to `1.21.0 dev.6.0`.

### PR DESCRIPTION
**Pull request by pq**
* updates to latest Dart SDK `1.21.0 dev.6.0`
* bumps `json_schema` dependency to remedy issue with duplicate map entries (#6840)

Note that this (re)introduces the "spam" about package `drudge`.  I hope this is only temporary (maintainer of `json_schema` pinged).

Also note the raft of analysis errors that need addressing.

/cc @Hixie @abarth and @leafpetersen FYI for new analysis results.

### CODE REVIEW

**Comment by leafpetersen** [comment]
I'm a little confused about this error:

```
[error] The function expression type '() → void' isn't of type '() → Null'. This means its parameter or return type does not match what is expected. Consider changing parameter type(s) or the returned type(s). (packages/flutter/lib/src/gestures/drag.dart, line 185, col 44)
```

Did you already check in fixes for this?  In my checkout of flutter (after doing flutter update), if I look at the code at that line I see this:

```dart
        invokeCallback/*<Null>*/('onDown', () => onDown(new DragDownDetails(globalPosition: _initialPosition)));
```

I tried to reproduce the error reported above with this code:

```dart
typedef T RecognizerCallback<T>();

/*=T*/ invoke/*<T>*/(RecognizerCallback/*<T>*/ c) => c();

void foo(int x) {}

void main() {
  invoke/*Null*/(() => foo(3));
}
```

But I see no errors with 1.21.0-dev.6.0, nor with bleeding edge.

Am I looking at the wrong code (post-fixes, or somehow not up to date)?

**Comment by leafpetersen** [comment]
Never mind, the comment syntax strikes again.  The correct reproduction code should be this:

```dart
typedef T RecognizerCallback<T>();

/*=T*/ invoke/*<T>*/(RecognizerCallback/*<T>*/ c) {
  return c();
}

typedef void Foo(int x);

void test() {
  Foo foo;
  invoke/*<Null>*/(() => foo(3));
}
```

And with this I do see the error.  

I think that the main issue here is this one:

https://github.com/dart-lang/sdk/issues/27504

Using `dynamic` instead of `Null` as the type parameter seems to me to be the right short term fix.

Note that `Null` isn't really the right type here anyway.  Functions which claim to return `void` can in fact return any value (even in strong mode), whereas functions that return `Null` can only return `null`.  So claiming that `() => functionReturningVoid()` has type `() -> Null` isn't really right.  

cc @floitschG @munificent @lrhn @eernstg

**Comment by leafpetersen** [comment]
```
[error] The function expression type '(List<String>) → Iterable<String>' isn't of type '(Iterable<String>) → Iterable<String>'. This means its parameter or return type does not match what is expected. Consider changing parameter type(s) or the returned type(s). (packages/flutter_test/lib/src/binding.dart, line 345, col 24)
```
This just seems like a bug - the contract doesn't promise a `List`?

**Comment by leafpetersen** [comment]
These errors I'm not sure about:

```dart
[error] The function expression type '(Element) → Widget' isn't of type '(Element) → T'. This means its parameter or return type does not match what is expected. Consider changing parameter type(s) or the returned type(s). (packages/flutter_test/lib/src/controller.dart, line 77, col 41)
[error] The function expression type '(Element) → RenderObject' isn't of type '(Element) → T'. This means its parameter or return type does not match what is expected. Consider changing parameter type(s) or the returned type(s). (packages/flutter_test/lib/src/controller.dart, line 222, col 41)
```

In this code:
```dart
 Iterable<RenderObject/*=T*/> renderObjectList/*<T extends RenderObject>*/(Finder finder) {
    TestAsyncUtils.guardSync();
    return finder.evaluate().map/*<T>*/((Element element) => element.renderObject);
  }
```
Is there an invariant that `finder.evaluate()` will always return an `Iterable` of `Element`s whose `renderObject`s are some subtype of `RenderObject` which matches whatever `T` was instantiated with?

**Comment by leafpetersen** [comment]
This error:
```
[error] The function expression type '(StatefulElement) → State<StatefulWidget>' isn't of type '(Element) → State<StatefulWidget>'. This means its parameter or return type does not match what is expected. Consider changing parameter type(s) or the returned type(s). (packages/flutter_test/lib/src/controller.dart, line 133, col 17)
```
from this code:
```
Iterable<State> get allStates {
    TestAsyncUtils.guardSync();
    return allElements
           .where((Element element) => element is StatefulElement)
           .map((StatefulElement element) => element.state);
  }
```

is the same issue of lacking `Iterable.filter` that we've discussed before, and that is on our list of things to fix.

cc @floitschG @lrhn @eernstg @munificent

**Comment by leafpetersen** [comment]
I'm not sure what's up with this one:

```
[error] The method tear-off '_sort' has type '(BuildableElement, BuildableElement) → int' that isn't of expected type '(Element, Element) → int'. This means its parameter or return type does not match what is expected. (packages/flutter/lib/src/widgets/framework.dart, line 1282, col 61)
```

Is the contract on `_sort` stronger than what is required, or is the type of `_elements` too weak?

**Comment by leafpetersen** [comment]
For these errors:

```
[error] The function expression type '(Request, ByteStream) → Future<StreamedResponse>' isn't of type '(BaseRequest, ByteStream) → Future<StreamedResponse>'. This means its parameter or return type does not match what is expected. Consider changing parameter type(s) or the returned type(s). (packages/flutter/lib/src/http/mock_client.dart, line 59, col 14)
[error] The function expression type '(Request, ByteStream) → Future<StreamedResponse>' isn't of type '(BaseRequest, ByteStream) → Future<StreamedResponse>'. This means its parameter or return type does not match what is expected. Consider changing parameter type(s) or the returned type(s). (packages/flutter/lib/src/http/mock_client.dart, line 30, col 14)
```

Just making the parameter annotation `BaseRequest` instead of `Request` fixes the error - is this just a bad type annotation, or is there something else going on?

**Comment by Hixie** [comment]
Looking at warnings now. Will submit a patch to fix those I understand.

**Comment by Hixie** [comment]
https://github.com/dart-lang/sdk/issues/27827

**Comment by Hixie** [comment]
I don't understand why this first one is ok but the second isn't:
```dart
  Widget/*=T*/ widget/*<T extends Widget>*/(Finder finder) {
    TestAsyncUtils.guardSync();
    return finder.evaluate().single.widget; // this is ok?!
  }

  Iterable<Widget/*=T*/> widgetList/*<T extends Widget>*/(Finder finder) {
    TestAsyncUtils.guardSync();
    return finder.evaluate().map/*<T>*/((Element element) => element.widget); // this is not?
  }
```

**Comment by Hixie** [comment]
Ok, I've submitted a PR to silence all but two of the warnings: https://github.com/flutter/flutter/pull/6866

**Comment by Hixie** [comment]
The two remaining warnings are these:
```dart
[error] The function expression type '(Element) → Widget' isn't of type '(Element) → T'. This means its parameter or return type does not match what is expected. Consider changing parameter type(s) or the returned type(s). (packages/flutter_test/lib/src/controller.dart, line 77, col 41)
[error] The function expression type '(Element) → RenderObject' isn't of type '(Element) → T'. This means its parameter or return type does not match what is expected. Consider changing parameter type(s) or the returned type(s). (packages/flutter_test/lib/src/controller.dart, line 222, col 41)
```

The code here is not sound, in that it's quite possible to call this code with predicates that return true for widgets of the wrong type. However, the same is true for the other functions in that section and yet those don't get warnings? I don't understand why they are different. Either assigning to a narrower type should be ok or it shouldn't, I don't see why it matters if it's in a closure or not.

Not really sure what the right fix here is, but presumably it involves asserts and implicit casts...

**Comment by pq** [comment]
This is awesome.  Cheers @Hixie !

Not sure what the right fix is for the remaining issues.

Is @leafpetersen right when he asks?

> Is there an invariant that finder.evaluate() will always return an Iterable of Elements whose renderObjects are some subtype of RenderObject which matches whatever T was instantiated with?

**Comment by Hixie** [comment]
There's only such an invariant in the sense that that's the intended use of the API. Nothing (especially nothing in the static analysis) prevents someone from writing code that doesn't fulfill these conditions.

But that is true of the other ones I mentioned too. Which is why I'm confused that only two of the 6 or more cases are being caught here.

**Comment by Hixie** [comment]
#6866 has landed; you may wish to restart Travis to see if it catches new errors. (I haven't done it in case you didn't want the old log discarded yet.)

**Comment by leafpetersen** [comment]
> I don't understand why this first one is ok but the second isn't:

The reason is that for the first one there is always a place for strong mode to ask the runtime to insert an implicit cast to check that that the thing which is statically unsafe is in fact ok at runtime, whereas in the second one there (in general) isn't.

For this code:

```dart
Widget/*=T*/ widget/*<T extends Widget>*/(Finder finder) {
    TestAsyncUtils.guardSync();
    return finder.evaluate().single.widget; // this is ok?!
  }
```

Strong mode will require a runtime check on the return to make sure that the thing that you are implicitly downcasting from `Widget` to `T`, is in fact a `T` at runtime, as the contract promises.  (As we've discussed, the VM does not implement these checks yet - nonetheless, the strong mode type system is designed around the assumption of their presence or absence).

In this code:

```dart
 Iterable<Widget/*=T*/> widgetList/*<T extends Widget>*/(Finder finder) {
    TestAsyncUtils.guardSync();
    return finder.evaluate().map/*<T>*/((Element element) => element.widget); // this is not?
  }
```

We have a place that expects an `Element -> T`, but is being passed an `Element -> Widget`.  If we were to just insert a cast at that exact spot, casting the closure literal to `Element -> T`, that cast is guaranteed to fail, since the reified type of that closure is, in fact, `Element -> Widget` and not `Element -> T`.

In general, we are stuck at this point.  However, in this particular narrow case, in which we have a closure literal with no annotated return type, I believe we could do better.  We could choose to use the type from the context of occurrence to infer a more precise type for the return type than what is inferred from the return expression, thereby moving the runtime check inside of the closure literal.  This would of course still not work if the argument to `.map` was a tearoff instead of a closure literal, but for this case it would handle it.

@jmesserly has an outstanding patch that we have not yet committed to landing that I believe implements this behavior.

**Comment by Hixie** [comment]
Ah because the closure has an implicit `dynamic` return type, so the compiler doesn't know what to cast it to? I guess that makes sense... With a tearoff it wouldn't be an issue because the tearoff _would_ have a return type so we could add the cast.

I can add an assignment to that block if you like. Or `//ignore` it and point to the bug where you plan to improve the inference.

**Comment by pq** [comment]
> #6866 has landed; you may wish to restart Travis to see if it catches new errors. 

Done.

Progress!  But still a few to address...

**Comment by Hixie** [comment]
Most of those seem to be me having failed to properly //ignore the warnings.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/6874

**Comment by pq** [comment]
> Most of those seem to be me having failed to properly //ignore the warnings.

I think I see what's up.  It looks like those are `StrongModeCode`s and that those have "STRONG_MODE" as a prefix in their code names.  In other words,

`INVALID_CAST_FUNCTION` => `STRONG_MODE_INVALID_CAST_FUNCTION`

**Comment by Hixie** [comment]
Ah, fascinating. Want me to submit a new PR?

**Comment by pq** [comment]
If it's not a huge distraction, that'd be great. Otherwise, let me know and I can take a crack later this afternoon.

**Comment by Hixie** [comment]
For you sir, I would be honoured to do it.

**Comment by pq** [comment]
Thanks a million for all the help!

**Pull request merged**
