### PR TITLE
Fix running dev/bots/test.dart in Dart 2 mode

### PR DESCRIPTION
**Pull request by mraleph**

### CODE REVIEW

**Comment by yjbanov** [comment]
@Hixie does the windows failure make sense to you? It seems to be of a kind that should either fail everywhere or succeed everywhere :confused:

**Comment by Hixie** [comment]
I don't know what 's causing it, but it is a flake that I've heard of. Log it and we'll address it when we look at flakes.

**Comment by yjbanov** [comment]
Logged and restarted the bot.

**Comment by mraleph** [comment]
ping?

**Pull request merged**
