### PR TITLE
Mention that the widget tree is not disposed on exit

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by morgwai** [comment]
related issue: #40940
as many ppl stated in the above issue, we think that Flutter platform should put its best effort to call dispose() as reliably as feasible.

**Review by Piinks — APPROVED** [review]
This LGTM - although it looks like conversation is ongoing in the issue?

**Comment by Hixie** [comment]
yeah this is just a stopgap while we continue to figure out how to resolve it. (Even if we can resolve the issue, it's still useful information for most ways that an app can shut down.)

**Comment by Piinks** [comment]
Failure appears to be another instance of https://g-issues.skia.org/issues/40045532, following up with the Gold team. I kicked the task off again.

**Pull request merged**
