### PR TITLE
Revert "implicit-casts: false"

### PR DESCRIPTION
**Pull request by chingjun**
Reverts flutter/flutter#47199

It failed analyzer and is blocking engine roll.

### CODE REVIEW

**Comment by chingjun** [comment]
Landing the revert TBR since it's blocking engine roll, and this is the last commit before the revert.

**Comment by a14n** [comment]
The breakage should be fixed by  #47426 (just waiting pre-submit check to land)

**Comment by a14n** [comment]
:'(

**Comment by chingjun** [comment]
Oops, I clicked the button a bit too early, sorry.

**Pull request merged**
