### PR TITLE
Add support for Material 3 Chip

### PR DESCRIPTION
**Pull request by TahaTesser**
part of https://github.com/flutter/flutter/issues/91605 and https://github.com/flutter/flutter/issues/99024

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key, this.dark = false, this.useMaterial3 = true});

  final bool dark;
  final bool useMaterial3;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      themeMode: dark ? ThemeMode.dark : ThemeMode.light,
      theme: ThemeData(
        useMaterial3: useMaterial3,
        brightness: Brightness.light,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      darkTheme: ThemeData(
        useMaterial3: useMaterial3,
        brightness: Brightness.dark,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      home: const Example(),
    );
  }
}

class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('M3 Chip Sample'),
      ),
      body: Center(
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                RawChip(
                  label: const Text('RawChip'),
                  onDeleted: () {},
                  onPressed: () {},
                ),
                const Chip(
                  label: Text('Chip'),
                ),
                InputChip(
                  label: const Text('InputChip'),
                  selected: true,
                  onPressed: () {},
                ),
                FilterChip(
                  label: const Text('FilterChip'),
                  onSelected: (bool value) {},
                ),
                ChoiceChip(
                  label: const Text('ChoiceChip'),
                  selected: true,
                  onSelected: (bool value) {},
                ),
                ActionChip(
                  label: const Text('ActionChip'),
                  onPressed: () {},
                ),
              ],
            ),
            Column(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: <Widget>[
                RawChip(
                  label: const Text('RawChip'),
                  elevation: 1.0,
                  onDeleted: () {},
                  onPressed: () {},
                ),
                const Chip(
                  elevation: 1.0,
                  label: Text('Chip'),
                ),
                InputChip(
                  elevation: 1.0,
                  label: const Text('InputChip'),
                  selected: true,
                  onPressed: () {},
                ),
                FilterChip(
                  label: const Text('FilterChip'),
                  onSelected: (bool value) {},
                ),
                ChoiceChip(
                  elevation: 1.0,
                  label: const Text('ChoiceChip'),
                  selected: true,
                  onSelected: (bool value) {},
                ),
                ActionChip(
                  elevation: 1.0,
                  label: const Text('ActionChip'),
                  onPressed: () {},
                ),
              ],
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {},
        child: const Icon(Icons.add),
      ),
    );
  }
}

``` 
	
</details>

Screenshot 2022-05-26 at 17 53 27

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by TahaTesser** [comment]
Updated this PR to check if there is any conflict from https://github.com/flutter/flutter/pull/106384

**Review by darrenaustin — COMMENTED** [review]
@TahaTesser thanks so much for this contribution. Sorry I hadn't had a chance to review it earlier. This looks like a great start! 

However, there are some issues that it is missing. The layouts don't look like they match the margins and padding of the spec (they aren't part of the tokens yet, but we should probably add them to the theme and set them in the templates). The icon sizes should be smaller. The delete button should have an outline rect instead of a circle. The ChoiceButton should be using checkboxes for the selected item.

As it turns out I had already started working on this feature as well (I didn't realize you had submitted this for review, sorry). I have PR in progress that is dealing with all of these issues and would prefer to keep going on it. So if it is ok with you we can close this and I can take it from here.

**Comment by TahaTesser** [comment]
@darrenaustin 
Thanks for taking a look. Sounds good to me!

**Comment by darrenaustin** [comment]
Thanks for understanding, and sorry I didn't coordinate better with you on this.

**Pull request closed without merging**
