### PR TITLE
fix the reload and restart service extension methods

### LINKED ISSUE #1896: Hot reload from app causes error
Steps:
1. Run devtools using `pub global run devtools`. 
2. Run a flutter app (I used [gallery](https://github.com/flutter/gallery)) - `flutter run`
3. Press hot reload in the devtools top right bar

Screen Shot 2020-04-30 at 4 07 12 PM
In this screenshot I first tried hot reloading with the devtools button (failed), then tried hot reload on the command line by pressing 'r' (succeeded), then tried the devtools button again (failed)

### PR DESCRIPTION
**Pull request by devoncarew**
## Description

This fixes the `reloadSources` and `hotRestart` service extension methods, which likely regressed as part of  flutter/flutter@4851888.

In addition, the PR:
- more uniformly validates parameters into the flutter tools service extensions methods
- fixes an issue in the existing integration tests where we were not awaiting `flutter?.stop()`, and were possibly leaking a flutter_tester process instance
- removes explicit exception handing and conversion to RPCErrors; this is handled by package:vm_service

## Related Issues

- fix https://github.com/flutter/devtools/issues/1896

## Tests

- added integration tests for the `reloadSources` and `hotRestart` service extension methods, as well as tests for bad params

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by devoncarew** [comment]
Also, this fixes some of the return results to be formed like:

```
<String, dynamic>{
  'result': <String, Object>{
   ...
}
```

We should likely add a utility method to package:vm_service to make the return results less hand-written and error-prone.

**Review by jonahwilliams — APPROVED** [review]
LGTM

What actually uses these service methods? I assumed IDEs did but it seems like they probably go through the daemon protocol instead.

**Comment by devoncarew** [comment]
> What actually uses these service methods? I assumed IDEs did but it seems like they probably go through the daemon protocol instead.

Yup - clients which actually launch the app use the daemon protocol (IDEs and such). Clients that connect to an already running app - like DevTools - use these services for hot reload and restart. It's more rare, which is likely why these were able to regress w/o us knowing right away.

**Comment by devoncarew** [comment]
Looks like these tests time out on windows: https://cirrus-ci.com/task/6016410658799616

**Comment by jonahwilliams** [comment]
I restarted the windows shard

**Comment by jonahwilliams** [comment]
I'll try another round of restarts. If not, lets disable on windows and land the fix sooner rather than later. We might need to bump the resources for these windows shards

**Comment by devoncarew** [comment]
I think there must be some issue on windows (or with the CI?). But I agree that getting this fixed and having an end-to-end test - on any platform - would be an improvement.

**Comment by devoncarew** [comment]
> We should likely add a utility method to package:vm_service to make the return results less hand-written and error-prone.

Re: my comment here, it's still probably worth improving package:vm_service here or service extensions in general, but in lieu of that, one slightly less error prone technique I've seen is:

```dart
return {'result': Success().toJson()};
```

https://github.com/dart-lang/webdev/blob/564ec5be934d76d49d6fb383800e0e4d1f7ea635/dwds/lib/src/dwds_vm_client.dart#L84

**Comment by jonahwilliams** [comment]
IT PASSED!

**Pull request merged**
