### PR TITLE
Roll engine to version cf0855e69fa8dcd39cd092c9aa9fdce1b216a96b

### PR DESCRIPTION
**Pull request by a-siva**
This roll contains the following changes :

2fa1ab9de Roll src/third_party/skia d95303e10cbc..4302eb9a6e14 (12 commits) (#6443)
45c5fe561 Remove touch mapper and respect the UITouch phase when calculating the pointer data change type. (#6430)
234736801 Roll src/third_party/skia 66a973493468..d95303e10cbc (13 commits) (#6440)

### CODE REVIEW

**Comment by liyuqian** [comment]
This may need to wait the Engine build bots to compile the artifacts: https://build.chromium.org/p/client.flutter/console

**Comment by a-siva** [comment]
Yes, I am waiting for it. Somehow the Linux-Engine builds seem to take much longer these days.

**Comment by yjbanov** [comment]
Heads up. There's another engine roll by auto-roller in progress: https://github.com/flutter/flutter/pull/22700

**Comment by yjbanov** [comment]
The description is missing cf0855e69fa8dcd39cd092c9aa9fdce1b216a96b

**Comment by a-siva** [comment]
Auto roller has picked up this change. Closing PR

**Pull request closed without merging**
