### PR TITLE
 add a params checkColor for Checkbox.

### PR DESCRIPTION
**Pull request by CaiJingLong**
The color of CheckBox is mutable, but the middle check color is immutable (white).

I think it should be allowed to change, otherwise when a background color is dark and a CheckBox is white, the checkbox is not visible when selected

### CODE REVIEW

**Comment by Hixie** [comment]
I agree that we should allow the color to be changed, but I think the way to do that is to implement what I wrote in the comment in https://github.com/flutter/flutter/issues/14674: make it so you can provide arbitrary decorations for each state of the checkbox. Otherwise we'll keep adding features here and eventually the list of parameters will be out of control. :-)

**Comment by tvolkert** [comment]
@CaiJingLong do you plan on updating this PR per @Hixie's review comment?

**Comment by CaiJingLong** [comment]
I don't know what attributes this decorator should contain. Normally, it shouldn't cover the old attributes to prevent API incompatibility. But in fact, if you need to use the decorator to wrap color-related attributes, some of the old attributes should be included, so I don't know how to update this PR.

**Comment by CaiJingLong** [comment]
@Hixie  you can close the pr, If you have any good suggestions, I can also modify the code .

**Comment by Hixie** [comment]
one way to do it is to have the decorations be mutually exclusive with the color properties; if color is specified, then it implies a set of decorations with that color, otherwise the color has to be null m

**Pull request closed without merging**
