### PR TITLE
Change type in `ImplicitlyAnimatedWidget` to remove type cast to improve performance and style

### PR DESCRIPTION
**Pull request by fzyzcjy**
Hi, hope to have a quick view whether this PR is acceptable or not? If yes I will add an issue and maybe ask for test-exempt.

---

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
@fzyzcjy I believe this just needs a test (or probably just a test exemption) to land.

**Comment by fzyzcjy** [comment]
@goderbauer I agree. Not sure how it can be tested though, so I will ask a test-exempt.

I will do it maybe a few days later since I am working on https://github.com/flutter/flutter/issues/101227 (and on discord), and do not want to have too many things on discord in one day :)

Thanks for your reply!

**Comment by goderbauer** [comment]
@fzyzcjy Did you have a chance to look into testing this or applying for the test exception?

**Comment by fzyzcjy** [comment]
@goderbauer Ah I forgot it completely. Here is the exemption request: https://discordapp.com/channels/608014603317936148/608018585025118217/1029170238190784704

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

**Review by Piinks — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
