### PR TITLE
Fix a type casting error in text_input.dart

### LINKED ISSUE #109632: `_toTextPoint` throws `type '_Smi' is not a subtype of type 'double' in type cast`
internal: b/240501546
Stacktrace:
```
at _toTextPoint 
at TextInput._handleTextInputInvocation
at TextInput._loudlyHandleTextInputInvocation
at TextInput._loudlyHandleTextInputInvocation
```

Potentially because the number could be an `int` instead of `double`.

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
The numbers can be integers.

Fixes https://github.com/flutter/flutter/issues/109632

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Comment by dkwingsmt** [comment]
As a side note: I've searched `as double` throughout the flutter/flutter repo and it doesn't seem like we have other cases like this. [PlatformView](https://github.com/flutter/flutter/blob/bacab7ee96e80b726a151cfbc87633c709edc32a/packages/flutter/lib/src/services/platform_views.dart#L1095) converts a method channel result from `dynamic` to `double` but it uses the standard codec.

**Comment by nohli** [comment]
@dkwingsmt @LongCatIsLooong 

Is this not part of Flutter `3.3.0`? I first see this error after upgrading Flutter stable.
(commenting here, since https://github.com/flutter/flutter/issues/109632 is closed and locked)

Error:
```
type '_Smi' is not a subtype of type 'double' in type cast
```

Stacktrace:
```
#0      _toTextPoint (package:flutter/src/services/text_input.dart:1513)
#1      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1827)
#2      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1701)
#3      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:536)
#4      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:529)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387)
#6      _invoke2.<anonymous closure> (dart:ui/hooks.dart:189)
#7      _rootRun (dart:async/zone.dart:1391)
#8      _CustomZone.run (dart:async/zone.dart:1293)
#9      _CustomZone.runGuarded (dart:async/zone.dart:1201)
#10     _invoke2 (dart:ui/hooks.dart:188)
#11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42)
#12     _Channel.push (dart:ui/channel_buffers.dart:132)
#13     ChannelBuffers.push (dart:ui/channel_buffers.dart:329)
#14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599)
#15     _dispatchPlatformMessage (dart:ui/hooks.dart:89)

```

**Comment by LongCatIsLooong** [comment]
No but it will likely be included in the next stable release. See https://github.com/flutter/flutter/wiki/Where's-my-Commit%3F

**Comment by limenote135** [comment]
@dkwingsmt @LongCatIsLooong Is there a plan to hotfix this into the stable branch?

**Comment by dmitry-fbm** [comment]
Can this please be included in next release?

**Comment by dtq** [comment]
@dkwingsmt Would it be possible to have this hotfixed into 3.3 stable? We're seeing hundreds of these reports per day in our crash logs for a production app since moving to 3.3. 

The fix [appears to be scheduled](https://github.com/flutter/flutter/issues/111892#issuecomment-1252734673) for 3.4, but it's unclear when that release will happen.

**Comment by AlexV525** [comment]
I've submitted a CP request for this.

**Comment by DimitarMilushev** [comment]
> As a side note: I've searched `as double` throughout the flutter/flutter repo and it doesn't seem like we have other cases like this. [PlatformView](https://github.com/flutter/flutter/blob/bacab7ee96e80b726a151cfbc87633c709edc32a/packages/flutter/lib/src/services/platform_views.dart#L1095) converts a method channel result from `dynamic` to `double` but it uses the standard codec.

It's part of [TextureAndroidViewController], since the error has been observed on iOS it's unlikely that to be the cause.

**Comment by vishalpatel1327** [comment]
The thing is error log cant be represented by the last mile file name, so no one can trace it that where the actual issue is.

**Pull request merged**
