### PR TITLE
Revert "Roll engine to 4c79e423dc6f89f98d8ceb263a5ca78e2f2da996 and update tests"

### PR DESCRIPTION
**Pull request by dnfield**
Reverts flutter/flutter#23357

Cirrus didn't run the merge job for this.

### CODE REVIEW

**Comment by dnfield** [comment]
TBR @aam @aartbik

**Comment by dnfield** [comment]
I will try to reland this when Cirrus/GitHub can check it.

**Comment by aam** [comment]
Well, with https://github.com/flutter/flutter/pull/23357 landed(even with this revert) we will know check results.

**Review by aam — COMMENTED** [review]
lgtm

**Pull request merged**
