### PR TITLE
Reland "Export Material curves in the Material lib"

### PR DESCRIPTION
**Pull request by goderbauer**
Reverts flutter/flutter#62431

A new version 1.1.2 of the animations package has been published and this should be save to land now.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
This is not safe to land without rolling in a new version of the new gallery, right?

**Comment by goderbauer** [comment]
Do you know where we pin the gallery version?

**Comment by jonahwilliams** [comment]
https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/new_gallery.dart

**Comment by jonahwilliams** [comment]
that is pulling in a gallery hash which has a lockfile checked in, so it might require an update to that

**Comment by goderbauer** [comment]
> [...] which has a lockfile checked in, so it might require an update to that

https://github.com/flutter/gallery/pull/231

**Comment by goderbauer** [comment]
New gallery version bump: https://github.com/flutter/flutter/pull/62439

**Comment by goderbauer** [comment]
Waiting on https://github.com/flutter/flutter/pull/62439 to successfully pass device lab before submitting this.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by tvolkert — APPROVED** [review]

**Pull request merged**
