### PR TITLE
[WIP] When --start-paused is passed on flutter for web applications, don't eagerly call main

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

As in the description. Also removes work around for error messages that isn't needed anymore. I'm not quite sure if this is sufficient for breakpoints

### CODE REVIEW

**Comment by jonahwilliams** [comment]
This isn' quite enough

**Comment by jonahwilliams** [comment]
@DanTup could you take a look at the one sometime this week? 

I've got some of start paused working just by skipping the invocation of main. I think I can listen to resume events to figure out when to invoke it again, but that hasn't been enough to get vscode to work.

**Comment by DanTup** [comment]
Had a quick test of this, but it didn't work. When we connect and call `getIsolate()` to get the state of the isolates, the isolates `pauseEvent` is a `Resume` event rather than some sort of `Pause` event (we expect it to be paused at the start, then we'll send breakpoints, then resume it):

```
[5:56:55 PM] [Observatory] [Info] ==> {"id":"7","method":"getIsolate","params":{"isolateId":"1"}}
[5:56:55 PM] [Observatory] [Info] <== {"jsonrpc":"2.0","result":{"type":"Isolate","id":"1","number":"1","name":"http://localhost:60854/:main()","startTime":null,"runnable":true,"livePorts":null,"pauseOnExit":null,"pauseEvent":{"type":"Event","kind":"Resume","timestamp":null,"isolate":{"type":"@Isolate","id":"1","number":"1","name":"http://localhost:60854/:main()"}},"libraries":[{"type":"@Library","id":"dart:_runtime","name":"dart:_runtime","uri":"dart:_runtime"},{"type":"@Library","id":"dart:_debugger","name":"dart:_debugger","uri":"dart:_debugger"},{"type":"@Library","id":"dart:_foreign_helper","name":"dart:_foreign_helper","uri":"dart:_foreign_helper"} // ...
```

Full log is here in case it's useful:

[Dart-Code-Log-2019-08-02 17-56-04.txt](https://github.com/flutter/flutter/files/3570607/Dart-Code-Log-2019-08-02.17-56-04.txt)

**Comment by DanTup** [comment]
There's an issue here with `PauseStart` unticked - I don't know if this means dwds doesn't support this yet? (cc @grouma)

https://github.com/dart-lang/webdev/issues/166

**Comment by grouma** [comment]
Is this a specific event we need to handle?

We have the infrastructure to support this. See:
https://github.com/dart-lang/webdev/blob/a8451a935db8f3821dd1cd279f5510850dfdb065/dwds/lib/src/connections/app_connection.dart#L23

**Comment by DanTup** [comment]
> Is this a specific event we need to handle?

I think it's the isolate state that's wrong. If I run with `--start-paused` and then call `getIsolate()` through the VM service, the `pauseEvent` of the isolate should be in one of the paused states (`IsolateStart`?), but it's currently in the `Resume` state (suggesting it's running and not paused).

**Comment by DanTup** [comment]
(FWIW my understanding of how it works is mostly based on just debugging and trying to make things work against the VM, it may be better to try and find a more official source for the lifecycle of these things in the VM, if one exists!)

**Comment by grouma** [comment]
Please open a tracking issue on package:dwds.

**Comment by DanTup** [comment]
Done! -> https://github.com/dart-lang/webdev/issues/629

**Comment by DanTup** [comment]
@jonahwilliams dwds has been updated to set the initial state to `PauseStart` - I'm not familiar with how that gets to here - do we need to wait for a release of dwds and then update pubspec references?

**Comment by jonahwilliams** [comment]
It should be up to date, I can give this a poke this week

**Comment by jonahwilliams** [comment]
With the updates here I'm getting to another vmservice method, but we don't seem to be hitting the resume as expected:

```
[6:23:11 PM] [Observatory] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceRegistered","timestamp":null,"service":"hotRestart","method":"hotRestart"}}}
[6:23:11 PM] [Observatory] [Info] <== {"jsonrpc":"2.0","result":{"type":"Isolate","id":"1","number":"1","name":"http://localhost:62127/:main()","startTime":1568078589403,"runnable":true,"livePorts":0,"pauseOnExit":false,"pauseEvent":{"type":"Event","kind":"PauseStart","timestamp":1568078589403},"libraries":[{"type":"@Library","id":"dart:_runtime","name":"dart:_runtime","uri":"dart:_runtime"},{"type":"@Library","id":"dart:_debugger","name":"dart:_debugger","uri":"dart:_debugger"},{"type":"@Library","id":"dart:_foreign_helper","name":"dart:_foreign_helper","uri":"dart:_foreign_helper"},{"type":"@Library","id":"dart:_interceptors","name":"dart:_interceptors","uri":"dart:_interceptors"},{"type":"@Library","id":"dart:_internal","name":"dart:_internal","uri":"dart:_internal"},{"type":"@Library","id":"dart:_isolate_helper","name":"dart:_isolate_helper","uri":"dart:_isolate_helper"},{"type":"@Library","id":"dart:_js_helper","name":"dart:_js_helper","uri":"dart:_js_helper"},{"type":"@Library","id":"dart:_js_mirrors","name":"dart:_js_mirrors","uri":"dart:_js_mirrors"},{"type":"@Library","id":"dart:_js_primitives","name":"dart:_js_primitives","uri":"dart:_js_primitives"},{"type":"@Library","id":"dart:_metadata","name":"dart:_metadata","uri":"dart:_metadata"},{"type":"@Library","id":"dart:_native_typed_data","name":"dart:_native_typed_data","uri":"dart:_native_typed_data"},{"type":"@Library","id":"dart:async","name":"dart:async","uri":"dart:async"},{"type":"@Library","id":"dart:collection","name":"dart:collection","uri":"dart:collection"},{"type":"@Library","id":"dart:convert","name":"dart:convert","uri":"dart:convert"},{"type":"@Library","id":"dart:developer","name":"dart:developer","uri":"dart:developer"},{"type":"@Library","id":"dart:io","name":"dart:io","uri":"dart:io"},{"type":"@Library","id":"dart:isolate","name":"dart:isolate","uri":"dart:isolate"},{"type":"@Library","id":"dart:js","name":"dart:js","uri":"dart:js"},{"type":"@Library","id":"dart:js_util","name":"dart:js_util","uri":"dart:js_util"},{"type"…
[6:23:11 PM] [Observatory] [Info] ==> {"id":"8","method":"setExceptionPauseMode","params":{"isolateId":"1","mode":"None"}}
[6:23:11 PM] [Observatory] [Warn] No thread for pause event
[6:23:11 PM] [Observatory] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceRegistered","timestamp":null,"service":"fullReload","method":"fullReload"}}}
[6:23:11 PM] [Observatory] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceRegistered","timestamp":null,"service":"ext.dwds.screenshot","method":"ext.dwds.screenshot"}}}
[6:23:11 PM] [Observatory] [Info] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Service","event":{"type":"Event","kind":"ServiceRegistered","timestamp":null,"service":"reloadSources","method":"reloadSources"}}}
[6:23:11 PM] [Observatory] [Info] <== {"jsonrpc":"2.0","result":{"type":"Success"},"id":"8"}
[6:23:11 PM] [Observatory] [Info] ==> {"id":"9","method":"setExceptionPauseMode","params":{"isolateId":"1","mode":"None"}}
[6:23:11 PM] [Observatory] [Info] <== {"jsonrpc":"2.0","result":{"type":"Success"},"id":"9"}
Mon Sep 09 2019 [18:23:21 GMT-0700 (Pacific Daylight Time)] Log file ended
```

**Comment by DanTup** [comment]
> No thread for pause event

I'm improved this error a little now. It happens because the `isolate` field is missing on the `PauseEvent` object in the response to `getIsolate`:

```
==> {"id":"7","method":"getIsolate","params":{"isolateId":"1"}}
<== {
	"jsonrpc": "2.0",
	"result": {
		"type": "Isolate",
		"id": "1",
		"number": "1",
		"name": "http://localhost:60506/:main()",
		"startTime": 1568117207585,
		"runnable": true,
		"livePorts": 0,
		"pauseOnExit": false,
		"pauseEvent": { // <------ No isolate ref on here
			"type": "Event",
			"kind": "PauseStart",
			"timestamp": 1568117207585
		},
		"libraries": [/*SNIP*/],
		"breakpoints": [],
		"exceptionPauseMode": "none",
		"rootLib": {
			"type": "@Library",
			"id": "package:flutter_gallery/main_web_entrypoint.dart",
			"name": "package:flutter_gallery/main_web_entrypoint.dart",
			"uri": "package:flutter_gallery/main_web_entrypoint.dart"
		},
		"extensionRPCs": []
	},
	"id": "7"
}
```

In the VM, the isolate ref is included:

```
"pauseEvent": {
	"type": "Event",
	"kind": "PauseStart",
	"isolate": {
		"type": "@Isolate",
		"id": "isolates\/1241700780580311",
		"name": "main",
		"number": "1241700780580311"
	},
	"timestamp": 1568117494694
},
```

In this instance (where we called `getIsolate`) we could code around this, but since there are multiple debugger implementations I think it would be better to have the behaviour aligned? (cc @grouma).

**Comment by DanTup** [comment]
If I work around that locally, I then hit this error when it starts sending breakpoints:

```
[1:46:18 PM] [Observatory] [Error] NoSuchMethodError: The getter 'id' was called on null.
Receiver: null
Tried calling: id
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ChromeProxyService.addBreakpointWithScriptUri (package:dwds/src/services/chrome_proxy_service.dart:182:51)
<asynchronous suspension>
#2      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:911:51)
<asynchronous suspension>
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
```

The requests look like this:

```
[1:46:10 PM] [Observatory] [Info] ==> {"id":"608","method":"addBreakpointWithScriptUri","params":{"isolateId":"1","scriptUri":"file:///Users/dantup/Dev/Google/flutter/examples/flutter_gallery/lib/gallery/app.dart","line":64}}
[1:46:10 PM] [Observatory] [Info] ==> {"id":"609","method":"addBreakpointWithScriptUri","params":{"isolateId":"1","scriptUri":"file:///Users/dantup/Dev/Google/flutter/examples/flutter_gallery/lib/demo/animation/home.dart","line":495}}
[1:46:10 PM] [Observatory] [Info] ==> {"id":"610","method":"addBreakpointWithScriptUri","params":{"isolateId":"1","scriptUri":"file:///Users/dantup/Dev/Google/flutter/examples/flutter_gallery/lib/demo/animation/home.dart","line":496}}
```

**Comment by grouma** [comment]
Open up some tracking issues on `package:dwds` and I'll work on them.

**Comment by DanTup** [comment]
Thanks - I opened:

- https://github.com/dart-lang/webdev/issues/656 - pause events should include isolate references
- https://github.com/dart-lang/webdev/issues/657 - "getter 'id' was called on null" when calling addBreakpointWithScriptUri

**Comment by DanTup** [comment]
@grouma 

> Also can you share a version of VS Code so I can test this behavior locally?

Sorry, missed this. You shouldn't need a special build, if you enable the web stuff in Flutter (be on master, and run `flutter config --enable-web`) then Chrome will show up as a device. If you hit `F5` to run, it'll try and run and debug as usual (you may wish to enable the [Observatory logfile](https://dartcode.org/docs/logging/#observatory) or run **Dart: Capture Logs** and tick Observatory to get a log of all the communication over the VM service).

**Comment by grouma** [comment]
@DanTup is there a way to configure VS Code to run Flutter from source?

Something like this:
` dart /usr/local/google/home/grouma/flutter/packages/flutter_tools/bin/flutter_tools.dart run -d chrome -v`

**Comment by DanTup** [comment]
You can't fun a "flutter project" like that because it wants to invoke `flutter`, though if you open the `flutter_tools` repo you could run it that way (because you're just running a Dart script). I have a `launch.json` I use when hacking on flutter_tools so I can easily step through and debug flutter_tools:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Dart",
			"program": "bin/flutter_tools.dart",
			"request": "launch",
			"type": "dart",
			"args": [
				"doctor"
			]
		}
	]
}
```

I change the `args` here to match what I want to run. Then when pressing `F5` it'll run with the debugger attached. Does that help?

**Comment by DanTup** [comment]
(you can set `cwd` for the current directory as well as the args btw)

**Comment by grouma** [comment]
Hmmm. I don't think that's what I want. I want to run a Flutter web application through VS code but using Flutter Tools from source. This way I can make changes to the Flutter Tools and validate that breakpoints / other IDE features work.

**Comment by DanTup** [comment]
> Hmmm. I don't think that's what I want. I want to run a Flutter web application through VS code but using Flutter Tools from source. This way I can make changes to the Flutter Tools and validate that breakpoints / other IDE features work.

Ah, got it. There's no built-in way to do that now. I usually just delete the `flutter_tools.snapshot` file and it rebuilds. It's not as fast as running from source but it's not something that I've done enough to add support for (I don't think it'd be difficult to have as a setting if it happens a lot though).

Potentially you could also just hack the [flutter script](https://github.com/flutter/flutter/blob/a7cfdbd3f309d930b5f3236faf7ec74618f5878b/bin/flutter#L106) to not generate/use a snapshot and invoke it from there, though I haven't tried it!

**Comment by DanTup** [comment]
@jonahwilliams looks like the breakpoint issue is resolved with https://github.com/flutter/flutter/pull/41805. I tried to test with this one too (without it there's a race with setting breakpoints) but wasn't sure how to resolve all the conflicts - if you can rebase this, I can re-test them together.

**Comment by jonahwilliams** [comment]
@DanTup I'll push  a new PR, this one got pretty stale

**Comment by jonahwilliams** [comment]
Closing in favor of the PR linked above

**Pull request closed without merging**
