### PR TITLE
Android context menu theming and visual update

### LINKED ISSUE #89939: Material Text Selection Toolbar color conflicts with brightness theme
In Flutter 2.5, with the new ColorScheme theming, you need to set `brightness: Brightness.dark` in order to get the status bar info (e.g., battery, wifi, time) to show as dark on light.  However, in Material's `text_selection_toolbar_text_button.dart` line 112 the ternary logic uses that brightness setting, which results in a white on white toolbar for the text selection options.

With Cupertino's `text_selection_toolbar_button.dart` it's not a problem because the toolbar color is hard coded with _kToolbarBackgroundColor.

Screenshot_1631451505

### PR DESCRIPTION
**Pull request by justinmc**
Fixes https://github.com/flutter/flutter/issues/89939 and updates the look of the Android context menu to match API 34.

## The problem
Before this PR, setting `surface` in the color scheme caused the background color of the Android context menu to change, but it wasn't possible to change the text color.

```dart
MaterialApp(
  theme: ThemeData(
    // Using a dark theme made the context menu text color be white.
    colorScheme: ThemeData.dark().colorScheme.copyWith(
      // Setting the surface here worked.
      surface: Colors.white,
      // But there was no way to set the text color. This didn't work.
      onSurface: Colors.black,
    ),
  ),
),
```

| Expected (after PR) | Actual (before PR) |
| --- | --- |
| Screenshot 2023-08-07 at 11 45 37 AM | Screenshot 2023-08-07 at 11 51 10 AM |

## Other examples

<table>
<tr>
<th>Scenario</th>
<th>Result</th>
</tr>
<tr>
<td>

```dart
MaterialApp(
  theme: ThemeData(
    colorScheme: ThemeData.light(),
  ),
  ...
),
```

</td>
<td>
Screenshot 2023-08-07 at 11 42 05 AM
</td>
</tr>
<tr>
<td>

```dart
MaterialApp(
  theme: ThemeData(
    colorScheme: ThemeData.dark(),
  ),
  ...
),
```

</td>
<td>
Screenshot 2023-08-07 at 11 42 23 AM
</td>
</tr>
<tr>
<td>

```dart
MaterialApp(
  theme: ThemeData(
    colorScheme: ThemeData.light().colorScheme.copyWith(
      surface: Colors.blue,
      onSurface: Colors.red,
    ),
  ),
  ...
),
```

</td>
<td>
Screenshot 2023-08-07 at 11 43 06 AM
</td>
</tr>
<tr>
<td>

```dart
MaterialApp(
  theme: ThemeData(
    colorScheme: ThemeData.light().colorScheme.copyWith(
      surface: Colors.blue,
      onSurface: Colors.red,
    ),
  ),
  ...
),
```

</td>
<td>
Screenshot 2023-08-07 at 11 42 47 AM
</td>
</tr>
</table>

### CODE REVIEW

**Comment by justinmc** [comment]
@QuncCccccc This is based on your suggestion in https://github.com/flutter/flutter/issues/89939#issuecomment-1659095246 (thank you!).

One question though: What if we want to deviate from the default surface colors by default?

I noticed that we're getting the default background color wrong in dark mode right now.  What if I want to fix that while still allowing users to customize the colors using ColorScheme's `surface` and `onSurface`?

| Native Android | Flutter Android |
| --- | --- |
|  | Screenshot from 2023-08-02 15-03-23 |

**Comment by QuncCccccc** [comment]
> One question though: What if we want to deviate from the default surface colors by default?
> 
> I noticed that we're getting the default background color wrong in dark mode right now. What if I want to fix that while still allowing users to customize the colors using ColorScheme's `surface` and `onSurface`?

Ah this would be a little bit tricky. Ideally, we can use a `propertyColor ?? themeColor ?? defaultColor` pattern to assign a color for the backgroundColor. If we do a similar thing here, it would be `backgroundColor: theme.colorScheme.surface ?? defaultAndroidColor`, but the problem is `theme.colorScheme.surface` will never return null, so the default color for native android can never be reached.🥲

I once added a similar fix for IconButton. We can check if the color is a default color scheme color, if it is, then we should use our own default color(native android). If it's not, we should use the customized surface color. So for this problem, I think we can firstly determine if there is a customized surface color in ColorScheme. We can compare the color `Theme.of(context).colorScheme.surface` with `ThemeData().colorScheme.surface`/`ThemeData.dark().colorScheme.surface`. If they are the same object, it means no custom surface exists, then we can use the native android background color; otherwise, we should use the custom surface.

The code change should look like this(I assumed a pink color for the native color😛):
Screenshot 2023-08-02 at 4 33 11 PM

Please let me know if there's any confusion or problems!

**Review by QuncCccccc — APPROVED** [review]
LGTM:)

**Comment by justinmc** [comment]
@QuncCccccc Would you mind reviewing this again?  I changed the PR to fully match the colors as well as font weight and border radius.  I noticed that there were goldens breakages, so I thought it would be better to update all of this at once rather than break the goldens multiple times in multiple PRs.  I update the description and title of the PR to match the increased scope.

Also, I took your advice from above about allowing the override of default values, so it will now be possible to change the background and foreground colors with `surface` and `onSurface` in the color scheme.

In these screenshots, the top is native and the bottom is Flutter.

| | Light | Dark|
| --- | --- | --- |
| With this PR | Screenshot 2023-08-07 at 10 49 14 AM | Screenshot 2023-08-07 at 10 49 38 AM |
| Before this PR | Screenshot 2023-08-07 at 10 55 54 AM | Screenshot 2023-08-07 at 10 55 35 AM |

**Comment by justinmc** [comment]
Golden changes all looked expected so I accepted them 👍

**Comment by QuncCccccc** [comment]
> @QuncCccccc Would you mind reviewing this again? I changed the PR to fully match the colors as well as font weight and border radius. I noticed that there were goldens breakages, so I thought it would be better to update all of this at once rather than break the goldens multiple times in multiple PRs. I update the description and title of the PR to match the increased scope.

I see! Reviewing now!

**Review by QuncCccccc — APPROVED** [review]
LGTM!

**Pull request merged**
