### PR TITLE
Roll pub packages

### PR DESCRIPTION
**Pull request by fluttergithubbot**
This PR was generated by `flutter update-packages --force-upgrade`.

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
cc @eliasyishak to fix analysis on the new version of package:xml: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8782890335841347217/+/u/Analyze/analyze/test_stdout

**Comment by christopherfujino** [comment]
FYI https://pub.dev/documentation/xml/latest/xml/XmlNode/text.html

**Comment by eliasyishak** [comment]
Note: seems like swapping out the deprecated getter `.text` on an xml node with `.innerText` fixes the issue.

**Comment by christopherfujino** [comment]
> Note: seems like swapping out the deprecated getter `.text` on an xml node with `.innerText` fixes the issue.

Awesome, thanks @eliasyishak!

**Pull request merged**
