### PR TITLE
Remove devicelab mac android tasks from manifest.yaml

### PR DESCRIPTION
**Pull request by godofredoc**
All these tests are already running in luci and were added to
prod_builders.json file.

Bug: https://github.com/flutter/flutter/issues/71960
Bug: https://github.com/flutter/flutter/issues/74059

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by xster** [comment]
Can you update dev/devicelab/README.md on how to run these locally now?

**Comment by jmagman** [comment]
It's the same as before.  `dart bin/run.dart -t <test>`

**Comment by xster** [comment]
none of the tests from prod_builders.json seem to run when I `dart bin/run.dart -a`

**Comment by godofredoc** [comment]
> lders.json seem to run when I `dart bin/run.dart -a`

This change should not affect the way the runner is executing tests unless you try to use stages flag. Can you please share the full command you are using and the the current working directory?

**Comment by xster** [comment]
I'm just on master head on a mac.

`cd dev/devicelab`
(connect an android and ios phone)
`dart bin/run.dart -a`

**Comment by godofredoc** [comment]
-a is trying to use stages, individual tests should still run. If we want to keep that functionality we need to update the runner to read prod_config.json instead of manifest.yaml

**Comment by xster** [comment]
ah I see. Will try. Thanks!

**Comment by xster** [comment]
Works, thanks!

**Comment by jmagman** [comment]
> > lders.json seem to run when I `dart bin/run.dart -a`
> 
> This change should not affect the way the runner is executing tests unless you try to use stages flag. Can you please share the full command you are using and the the current working directory?

Filed https://github.com/flutter/flutter/issues/74660 to get this working, or update the README.

**Pull request merged**
