### PR TITLE
Adding vscode path installed though snap

### PR DESCRIPTION
**Pull request by jeanluc243**
## Description

*Adding path to VScode directory installed through snap on Linux*

## Related Issues

VS Code installed via Snap does not appear in flutter doctor [#54358](https://github.com/flutter/flutter/issues/54358)

### CODE REVIEW

**Comment by zanderso** [comment]
@jeanluc243 If you'd like to continue with this PR, please sign the CLA, and see our CONTRIBUTING.md. Thanks!

**Comment by jeanluc243** [comment]
> @googlebot I signed it!

**Comment by jonahwilliams** [comment]
@jeanluc243 the change seems reasonable, but it looks like git is a bit confused. I would recommend following the contributing guide in CONTRIBUTING.md, specifically setting up a separate flutter checkout for contributing and branching off of upstream/aster

**Comment by christopherfujino** [comment]
@jeanluc243 unfortunately because of a change I made and landed upstream, CI won't pass for this PR. The easiest way to fix this would be to fetch the latest upstream master locally, create a new branch off of the tip of master, and then re-create your changes (as it's only a few lines that shouldn't be difficult). This change will also require tests. Feel free to ping me on your new PR if you need help writing tests.

**Comment by zanderso** [comment]
@jeanluc243 Since the PR has to be recreated following @christopherfujino's, I'm going to close this one. Thanks!

**Pull request closed without merging**
