### PR TITLE
Add use of generated plugin registry

### PR DESCRIPTION
**Pull request by mravn-google**
Making the platform channel samples use the new project template.

### CODE REVIEW

**Comment by mravn-google** [comment]
Partially fixes https://github.com/flutter/flutter/issues/10297

**Review by szakarias — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
flutter_gallery_ios__transition_perf has been flaky ever since this checkin.

**Comment by mravn-google** [comment]
Yes, I have been monitoring it too. Not entirely clear how these changes could affect response times on `flutter_driver` tapping. I'll revert if flakes continue.

**Comment by mravn-google** [comment]
Wait, this PR is all about `examples/platform_channel` and `examples/platform_channel_swift`. No code changes outside. I doubt this is the culprit.

**Comment by Hixie** [comment]
Yeah, I don't understand that either. cc @yjbanov

**Comment by yjbanov** [comment]
I don't think the flakiness is due to this change. Looking at adjacent commits, they don't look suspicious either. For now, I'll see if refreshing the test environment helps. If not, I'll investigate more.

https://github.com/flutter/flutter/pull/10420
https://github.com/flutter/flutter/issues/10419

**Pull request merged**
