### PR TITLE
Fix ios module test typo

### LINKED ISSUE #89175: Mac module_test_ios is 2.76% flaky
The post-submit test builder `Mac module_test_ios` had a flaky ratio 2.76% for the past 15 days, which is above our 2.00% threshold.

One recent flaky example for a same commit: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_test_ios/3945
Commit: https://github.com/flutter/flutter/commit/c5861cfb56725f492e4a58d3dfdfca868c64dade
Flaky builds:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_test_ios/3945
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_test_ios/3930
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_test_ios/3913
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_test_ios/3903
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_test_ios/3898

Succeeded builds (3 most recent):
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_test_ios/4007
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_test_ios/4006
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20module_test_ios/4005

Please follow https://github.com/flutter/flutter/wiki/Reducing-Test-Flakiness#fixing-flaky-tests to fix the flakiness and enable the test back after validating the fix (internal dashboard to validate: go/flutter_test_flakiness).

### PR DESCRIPTION
**Pull request by cyanglaz**
Fix typo in ios module test that caused flakes

Fixes https://github.com/flutter/flutter/issues/89175

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
🤦‍♀️ good eye. LGTM

**Comment by cyanglaz** [comment]
@jmagman Do you know what's the benchmark failure here? Doesn't seem to relate to the PR but my other framework PR didn't hit this. (This is synced with master) 

cc @godofredoc

**Comment by jmagman** [comment]
Lots of infra failures on that benchmark in try jobs: https://ci.chromium.org/p/flutter/builders/try/Mac_ios%20hot_mode_dev_cycle_macos_target__benchmark

File an infra ticket and infra on-call can diagnose.

**Comment by cyanglaz** [comment]
Filed https://github.com/flutter/flutter/issues/94946

**Comment by cyanglaz** [comment]
ci.yaml validation failed, created infra ticket: https://github.com/flutter/flutter/issues/95027

**Pull request merged**
