### PR TITLE
Implement ImageRepeat

### LINKED ISSUE #158: Implement (or remove) all the ImageRepeat logic.
<a href="https://github.com/Hixie"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Wednesday Sep 09, 2015 at 17:34 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1097_

----

### PR DESCRIPTION
**Pull request by abarth**
Fixes #158

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

**Comment by Hixie** [comment]
LGTM.
I love the approach, it's very self-contained and readable.

**Comment by abarth** [comment]
> I love the approach, it's very self-contained and readable.

\o/

**Comment by Hixie** [comment]
does this clip to the output rect? seems like it might overflow if the slices don't exactly line up with the destination.

**Comment by abarth** [comment]
That's a good point.  I was testing with a full-screen widget, so I didn't notice.  Please file a bug against me.  Will fix.

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/issues/766

**Pull request merged**
