### PR TITLE
Expose API that allows for resizing of images

### PR DESCRIPTION
**Pull request by iskakaushik**
## Description

This allows us for a way to resize images. We add a new parameter to network, asset, file and memory images: `resizeToFit`, setting this means that the image will be resized and take up less memory.

## Related Issues

#26194

## Tests

I added the following tests in `image_resize_test.dart`

1. Added tests for resizing `MemoryImage`
2. Added tests for resizing `FileImage`
3. Added tests for resizing `AssetImage`

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by iskakaushik** [comment]
@jonahwilliams , @Hixie : Re-opening this with more tests and addressing the comments on https://github.com/flutter/flutter/pull/31164, I had to close it earlier and now have cycles to iterate in this.

I've also added benchmarks in https://github.com/flutter/flutter/pull/33814 that should let us know the impact of this change.

**Comment by Hixie** [comment]
Should this be done using the Size in ImageConfiguration rather than arguments to load?

if we stick with the approach in this PR, we should definitely include detailed descriptions of how these relate to each other and what they both mean.

**Comment by iskakaushik** [comment]
@Hixie , `ImageConfiguration` is indeed used to provide the `targetWidth` and `targetHeight` in the `ResizedImage` image provider.

If we are looking at `ImageConfiguration` that the `NetworkImage.obtainKey` (same for others as well) is called with, we do not use the size as part of the ImageKey key as we would potentially not want to cache images at a specified side, think- gifs, animated images etc.

For that reason, I've tried to keep any size specific configuration contained only in the `ResizedImage` and it's Image key. That way when users use `resizeToFit` parameter, they are making the choice to cache at a specific target dimension understanding the implications on animations.

But you are right, it will be confusing for users who are using `NetworkImage` directly, but we do mention on `ImageConfiguration` that the parameters are advisory and best effort. I will add additional documentation on the `load` method documenting this behavior.

**Comment by iskakaushik** [comment]
After offline conversation with Ian, we decided that the `ImageProvider` implementations not respecting `targetWidth` and `targetHeight` is not ideal. We came up with a way to use `ResizedImage` as the only thing that overrides the target dimensions when instantiating the codec.

**Pull request closed without merging**
