### PR TITLE
[flutter roll] Revert "Use AnimatedSwitcher's _childNumber as Key in layoutBuilder's Stack"

### PR DESCRIPTION
**Pull request by XilaiZhang**
Reverts flutter/flutter#121408

I created a tracking bug with scuba links in b/271479418

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by JimGerth** [comment]
Hi, I was wondering why #121408 got reverted? I‘m not sure I understand the problem.
Is there anything I can do to get this relanded?

**Comment by goderbauer** [comment]
@JimGerth This is gonna be a little frustrating and I apologize in advance for that: The change was breaking a number of google-internal apps. Unfortunately, I can't give you access to the failing tests. I still believe that your change is the correct one to make. However, until someone with access to google-internal systems can take a look and figure out why these tests are failing we can't make the change. I'll see if I can find someone who can take a look at this.

**Comment by JimGerth** [comment]
@goderbauer Alright, thanks for the response. If I can't do anything about it, I can remove it from the back of my mind at least :D

**Comment by JimGerth** [comment]
@goderbauer Are there updates on this by any chance?

**Comment by JimGerth** [comment]
@goderbauer Has anyone looked at this in the past month?

**Comment by gnprice** [comment]
@JimGerth Another place you might try is in Discord:
https://github.com/flutter/flutter/wiki/Chat
I think the `#hackers-framework` channel would be appropriate.

You can ask there if someone can help you land a bugfix that needs help resolving some Google internal tests.

**Pull request merged**
