### PR TITLE
Roll engine to 58a1894a1cd798de2f9a206f157a90d45944028b

### PR DESCRIPTION
**Pull request by goderbauer**
Switches to new clang toolchain

### CODE REVIEW

**Comment by dnfield** [comment]
LGTM

**Review by chinmaygarde — APPROVED** [review]

**Comment by liyuqian** [comment]
I'm curious why the auto-roller can't roll this? This seems to be a simple roll that only changes the engine version.

**Comment by goderbauer** [comment]
I wanted to ensure that the benchmarks run on this specific engine commit. The engine auto-roller would have lumped multiple engine commits into one.

**Comment by liyuqian** [comment]
I see. Thanks for the explanation.

**Pull request merged**
