### PR TITLE
PageView.builder with viewport fraction not working properly 🚧

### PR DESCRIPTION
**Pull request by Suraj-Tiwari**
When using `PageView.builder` with single item containing Inkwell with viewport fraction, Inkwell wont trigger. 

You can run this gist for better understanding what is the issue
https://gist.github.com/Suraj-Tiwari/2320e3ff973bab0cbbe3ec3b9498b3ef 

### Here is a detailed reason why this is happening: 

image

as you can see the SilverFillViewport width is 40% of screen width because view port fraction is 0.4
so it did it's job. and that area is clickable

Width of card is equal to view port but it's in center instead of left side of the screen where is SilverFillViewport 

so i investigated and found this line which gives padding to that card 

https://github.com/flutter/flutter/blob/e99c881f8d0e63042af6e2a3f6182c3ca6967442/packages/flutter/lib/src/rendering/sliver_fill.dart#L60

if i replace that code with following line 
`double get _padding => (1.0 - 1.0) * constraints.viewportMainAxisExtent * 0.5;`
which is equal to:
`double get _padding => 0`

This is how it looks after that, and this (card with inkwell) works perfectly. 

image

### CODE REVIEW

**Comment by Suraj-Tiwari** [comment]
I signed it!

**Comment by goderbauer** [comment]
Looks like this is making a couple of existing tests fail. This change is either breaking them or those tests will need to be updated.

Additionally, in order to accept this PR you'll also have to write a test to ensure that we don't break this again.

**Comment by Suraj-Tiwari** [comment]
@goderbauer something weird is going on with tests-* 
can you please have a look at it?

**Comment by goderbauer** [comment]
What do you mean by "weird"?

Looks like there are some pretty clear test failures which seem related to what this PR is changing, e.g. from the logs:

```
04:33 +2981 ~15: /tmp/flutter sdk/packages/flutter/test/widgets/page_view_test.dart: PageView viewportFraction                                                                                         
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: Offset:<Offset(50.0, 0.0)>
  Actual: Offset:<Offset(0.0, 0.0)>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///tmp/flutter%20sdk/packages/flutter/test/widgets/page_view_test.dart:409:5)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:82:23)
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:571:19)
<asynchronous suspension>
#9      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:555:14)
#10     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:898:24)
#16     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:895:15)
#17     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:81:22)
#18     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#19     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
<asynchronous suspension>
#24     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
#25     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#30     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#31     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
<asynchronous suspension>
#45     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#46     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#47     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
(elided 28 frames from class _FakeAsync, package dart:async, and package stack_trace)

This was caught by the test expectation on the following line:
  file:///tmp/flutter%20sdk/packages/flutter/test/widgets/page_view_test.dart line 409

The test description was:
PageView viewportFraction
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Suraj-Tiwari** [comment]
sorry i just looked at it, i was looking an old test. found it I'll update you soon with a fix

**Comment by goderbauer** [comment]
You can also run the tests locally by running `flutter test` in `packages/flutter`. That should show you the tests failures as well.

**Comment by Suraj-Tiwari** [comment]
Thanks for you help.

**Comment by Suraj-Tiwari** [comment]
@goderbauer I went through tests issue is due to wrong offset


this image is without fix
image

this image is with fix
image

As you can see to keep it clickable padding has to be removed from page view child . so offset is updated, 
so i have to update offset in tests or i it's a bad idea?

**Comment by goderbauer** [comment]
If the tests are actually incorrect they'll have to be updated (I haven't looked at the failing tests to answer that, though).

**Comment by goderbauer** [comment]
@Suraj-Tiwari did you have a chance to look at the failing tests?

**Comment by Suraj-Tiwari** [comment]
Yeah I'll As I'm busy for some days that's why it'll take some time, maybe
I'll try this weekend

**Comment by goderbauer** [comment]
@Suraj-Tiwari I am going to close this for now since there has been no activity. Feel free to open it again if you find the time.

**Pull request closed without merging**
