### PR TITLE
Remove FadeTransition from _MountainViewFadeTransition.

### PR DESCRIPTION
**Pull request by chinmaygarde**
Fixes perf issues [observed](https://github.com/flutter/flutter/issues/9219#issuecomment-292308315) on opening all demos in the gallery.

flutter_02

### CODE REVIEW

**Review by sethladd — APPROVED** [review]
screenshot lgtm

**Review by xster — APPROVED** [review]
Are we adding it back after we ship the gallery?

**Comment by sethladd** [comment]
I think we should add it back (or, at least, turn it on by default) once we're happy with the performance. People will evaluate Flutter by building the Gallery and using our stock components, so we want them to have a good first impression.

**Comment by xster** [comment]
Can we add this back now?

**Comment by Hixie** [comment]
Have we resolved the performance issue?

**Pull request merged**
