### PR TITLE
add text_input_action deserialization factory

### PR DESCRIPTION
**Pull request by sw-tester**
adding deserialisation factory for SendTextInputAction. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by pdblasi-google** [comment]
Hi @5v1988,

Thanks for the contribution! It looks like this PR is missing a couple of things though:

* It's best to file an issue in case there are any problems downstream and this PR needs to be reverted and relanded. That way references to this change can be made without being dependent on this specific PR introducing it. It also helps others find issues when they have the same problem you have.
* We'll also need a test to make sure this isn't accidentally undone in the future. This area of the codebase is a bit strange to test, but you should be able to test this (indirectly at least) through `extension_test.dart`. There are other tests there that validate specific commands are being deserialized and acted upon that you can use as a reference.

**Comment by Piinks** [comment]
Hi @5v1988, since there has not been an update here for some time, I am going to close this PR for now to remove it from our review queue. If you would like to return to it and address the feedback above, please feel free to reopen it. Thanks for contributing!

**Comment by nonvachara-paloit** [comment]
I ran into an issue relates to this PR today and I'm will to fix. Should I create a new PR or reopen (don't know how) this one?

**Comment by Piinks** [comment]
> I ran into an issue relates to this PR today and I'm will to fix. Should I create a new PR or reopen (don't know how) this one?

@nonvachara-paloit thanks for contributing! I would recommend opening a new PR since this was authored by someone else.

**Pull request closed without merging**
