### PR TITLE
Constants! Constants everywhere!

### PR DESCRIPTION
**Pull request by Hixie**
Aggressively apply the const lint.

### CODE REVIEW

**Comment by Hixie** [comment]
Apparently I haven't been risking enough merge conflicts with my other two multi-thousand line outstanding PRs, so I thought I should up the ante.

**Comment by sethladd** [comment]
I can't wait to see how this affects our benchmarks, if at all.

**Comment by Hixie** [comment]
Yeah, me too!

**Comment by abarth** [comment]
LGTM

**Comment by a14n** [comment]
lgtm ( I had the same patch locally - I was just waiting a review of my last PR to submit it ;) )

**Pull request merged**
