### PR TITLE
Turn on win_build_tests_2_3 shard, skip 'build windows' tests

### PR DESCRIPTION
**Pull request by jmagman**
Re-enable the shard disabled in https://github.com/flutter/flutter/pull/81955.  Continue to skip the `flutter build windows` tests until the right version of Visual Studio can be made available https://github.com/flutter/flutter/issues/81956.

This will allow the non-Windows Android and web tests to run on this shard.

Enable only in the try builder.  If this starts passing in prod I'll mark it unflaky in another PR.

### CODE REVIEW

**Comment by jmagman** [comment]
It worked https://ci.chromium.org/p/flutter/builders/try/Windows%20build_tests_2_3/3165?

**Review by godofredoc — APPROVED** [review]
LGTM, fix to make VS available in bots in on review https://flutter-review.googlesource.com/c/recipes/+/13400

**Comment by jmagman** [comment]
> LGTM, fix to make VS available in bots in on review https://flutter-review.googlesource.com/c/recipes/+/13400

Oh nice, that's eminent.  That one might even merge first. 😄

**Comment by jmagman** [comment]
build tests passed. `web_integration_tests` and  `tool_integration_tests_4_4` are fixed on ToT.  Merging.

**Pull request merged**
