### PR TITLE
Add missing awaits

### PR DESCRIPTION
**Pull request by mravn-google**
`Future.wait` doesn't actually wait unless you do.

### CODE REVIEW

**Review by xster — APPROVED** [review]
Seems like there are a bit more from a global search on Future.wait

**Comment by mravn-google** [comment]
Yes, that does seem like an easy mistake to make. I only looked at `flutter_tools`. Will do a global sweep.

**Comment by xster** [comment]
We did a bunch of sweeps in the past but haven't turned the linter on #10754

**Comment by Hixie** [comment]
What's the status of this PR?

**Comment by mravn-google** [comment]
It's ready to land. Thought I had already done that.

**Pull request merged**
