### PR TITLE
Use downgraded analyze for flutter/packages

### LINKED ISSUE #129633: Find a way to avoid flutter/flutter tree closures due to stale flutter/packages checkout
We have a lot of complexity in flutter/packages tests around reliance on published dependencies, which can bleed into flutter/flutter due to the analysis step that's run in flutter/flutter.

We had a [recent case](https://github.com/flutter/packages/pull/4261#issuecomment-1609628254) where we ran into a new variant, which could definitely happen again. The chain of events:
1. We deprecated a method in a platform interface package of a federated plugin
2. As expected, the flutter/packages CI flagged that this would break analysis in the higher-level packages that make up that plugin.
3. We updated the PR to include `// ignore` directives for those cases (which would then be cleaned up in the next PR).
4. We landed the PR, and the change was published
5. flutter/flutter started failing, because it's using a pinned version of flutter/packages, so instead of getting the `ignore`s immediately and the published dependency later, it got the published dependency *before* it picked up the `ignore`s via the flutter/packages->flutter/flutter roller.

I'm not sure yet how to best avoid this.
- We don't want do exact pinning in the package itself, because it's a published package's non-dev dependency.
- We could break things apart (like we used to) such that we update all the packages first, *then* deprecate the old method, but that's more overhead, and there's still no guarantee the ordering of that won't be wrong in flutter/flutter (although it would certainly be much less likely). And that doesn't work well for other similar cases that can cause analysis warnings, like adding an enum value.
- We could convert ranges to exact pins in `flutter/flutter` before running analysis. That does mean it would sometimes be analyzing with older versions of dependencies, but that might be fine since by definition the lowest version should work. It might cause conflicts though, by preventing the resolver from working normally.
- Maybe we could do something like the version-at-time script that some other combination tests use (customer tests, IIRC?), but for pub? So in flutter/flutter, for each direct dependency, we set the constraint to have a max of the newest version that had been published at the time of the pin?

### PR DESCRIPTION
**Pull request by stuartmorgan-g**
Add the `--downgrade` flag to the flutter/packages analyze test, so that it won't get the latest version of dependencies, avoiding out-of-band failures in flutter/flutter due to package publishing events.

Fixes https://github.com/flutter/flutter/issues/129633

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@devoncarew We should make this change to the Dart repo version of the test as well, to reduce random breakage.

**Review by bparrishMines — APPROVED** [review]
LGTM

**Review by tarrinneal — APPROVED** [review]
Is using newest and oldest not possible, or not worth?

**Comment by stuartmorgan** [comment]
> Is using newest and oldest not possible, or not worth?

The purpose of this change is explicitly to avoid using the newest, because doing so exposes flutter/flutter to out-of-band breakage. All we care about when we are running these tests in the context of the flutter/flutter repo is catching cases where flutter/flutter changes would break flutter/packages, and the dependency versions are irrelevant for that.

In flutter/packages, we run this test both ways, because the goal of the testing there has a very different scope.

**Comment by devoncarew** [comment]
> @devoncarew We should make this change to the Dart repo version of the test as well, to reduce random breakage.

👍 - makes sense. Probably good to track w/ an issue in the dart-lang/sdk repo? cc @srawlins

**Comment by stuartmorgan** [comment]
> > @devoncarew We should make this change to the Dart repo version of the test as well, to reduce random breakage.
> 
> 👍 - makes sense. Probably good to track w/ an issue in the dart-lang/sdk repo? cc @srawlins

I tracked down my breadcrumbs to the script and posted https://github.com/dart-lang/sdk/pull/52989

**Pull request merged**
