### PR TITLE
Revert engine roll that caused microbenchmarks failures

### PR DESCRIPTION
**Pull request by aam**
Reverting engine roll https://github.com/flutter/flutter/pull/19008 that caused https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/microbenchmarks.dart to fail https://flutter-dashboard.appspot.com/build.html

### CODE REVIEW

**Comment by matthew-carroll** [comment]
LGTM.  Do we have anyone investigating the regressions?

**Comment by aam** [comment]
I believe @DanTup spent some time last few days investigating it: https://github.com/flutter/flutter/issues/19096

**Comment by DanTup** [comment]
Yeah, I think the failures are a combination of two issues - one of them I think I can look at (the test not correctly terminating processes - it's been a bug forever but it was only exposed by the other...); the other may be in the engine/SDK (when an app is stopped because another app is being installed on the device, the old `flutter run` process doesn't get terminated anymore). Fixing either will likely fix the tests, but really both need to be understood/fixed (since the second one might mean something isn't being cleaned up that used to be).

I'll dig more into the second one on Monday - it's possible it's reproducible by running `flutter run` in two different terminals, but I didn't get chance to test yet.

**Comment by aam** [comment]
Not waiting for cirrus windows build to complete - it failed to started first time around, while AppVeyor completed successfully.

**Comment by DanTup** [comment]
FYI; I split the issue above into two more specific issues for fixing:

- https://github.com/flutter/flutter/issues/19208
- https://github.com/flutter/flutter/issues/19210

I can do some investigating into the first, but the second one is likely something changing in the engine. I wasn't able to repro outside of the test, but I've added a note on how to run a smaller set of the tests to repro more quickly (probably it can be repro'd outside of the tests if you use the right args to `flutter run`?).

**Pull request merged**
