### PR TITLE
Revert "[framework] inline AbstractNode into RenderObject"

### PR DESCRIPTION
**Pull request by CaseyHillers**
Reverts flutter/flutter#103832

Breaking google tests

### CODE REVIEW

**Comment by CaseyHillers** [comment]
Putting this up in case we don't have time to update the internal fix today

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by CaseyHillers** [comment]
I'm seeing a few instances of:

```
Change to a supertype of 'RenderObject', or, for a covariant parameter, a subtype.
  void adoptChild(RenderBox child) {
```

**Comment by jonahwilliams** [comment]
Lets revert for now, if you could send me the failure log I can take a look at it later and figure out what tests were missed. FWIW the frob run got stuck so I manually patched it in and ran tests in g3, so I hit skip on google tests for the original PR.

**Comment by dnfield** [comment]
That particular failure can probably be fixed by making `adoptChild(covariant RenderObject child)`, right?

**Pull request merged**
