### PR TITLE
Consider the FLUTTER_TOOL_ARGS as part of the compilation stamp

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
(still need to update test.dart, but that's blocked on https://github.com/flutter/flutter/pull/94879 landing)

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
I suspect the test failures will be fixed (or clarified) by https://github.com/flutter/flutter/pull/96320

**Comment by skia-gold** [comment]
Gold has detected about 10 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/94951

**Comment by Hixie** [comment]
Yup, test failures got resolved by that other PR. Marking as ready to land.

**Pull request merged**
