### PR TITLE
Set slider semantics flag for sliders

### LINKED ISSUE #226: Ensure sliders have useful a11y labels
It would be nice if these sliders had accessibility labels, just as an example for developers to follow. Currently, screen readers only read the value

### LINKED ISSUE #67396: Set slider semantics flag for sliders
Now that #65766 has landed, we should set this flag for all sliders (`Slider`, `RangeSlider`, and `CupertinoSlider`)

### PR DESCRIPTION
**Pull request by apomalyn**
## Description

Add the semantics flag for the sliders (`Slider`, `RangeSlider` and `CupertinoSlider`).

## Related Issues

*Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR. There should be at least one issue listed here.*
Linked to:
- Should close: #67396 
- Also closes https://github.com/flutter/gallery/issues/226

## Tests

I didn't add any tests but changed the following tests:
- cupertino/slider_test.dart: `Slider Semantics` and `Slider Semantics can be updated`
- material/range_slider_test.dart: `Range Slider Semantics`
- material/slider_test.dart: `Slider Semantics` (l.1314 and l.1474) and `Slider semantics with custom formatter`

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`). **I don't know what to add or update**
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

## Other information

After reviewing this PR if this is possible to add the label: hacktoberfest-accepted that would be wonderful. This is for the [hacktoberfest challenge](https://hacktoberfest.digitalocean.com/)

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by guidezpl — APPROVED** [review]
Thanks for contributing!
```
  _    ___ _____ __  __ 
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
                        
```

**Comment by apomalyn** [comment]
> Thanks for contributing!
> ```
>   _    ___ _____ __  __ 
>  | |  / __|_   _|  \/  |
>  | |_| (_ | | | | |\/| |
>  |____\___| |_| |_|  |_|
>                         
> ``` 

Thanks!! Just quick question 😅 is it possible to add the label **hacktoberfest-accepted** so it count for the challenge? 😅

**Comment by guidezpl** [comment]
I don't think we're a participating repo, but let me ask. cc @kf6gpe

**Comment by kf6gpe** [comment]
Yeah, unfortunately we're not participating!! It's a good idea, though --- and thanks for your contribution!

**Comment by apomalyn** [comment]
Alright, maybe next year! Thanks for letting us contribute to this repo!

**Pull request merged**
