### PR TITLE
Revert "Use the new pushImageFilter offset parameter to fix the transform of the children"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#113673

Failing framework tests due to golden diffs that were not accepted

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
(un-)ship it

**Comment by flar** [comment]
Is there a pointer to the broken goldens?

**Comment by jonahwilliams** [comment]
The test run was https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8796772275144668881/+/u/run_test.dart_for_framework_tests_shard_and_subshard_widgets/test_stdout

The failure is:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following SkiaException was thrown while running async test code:
Skia Gold received an unapproved image in post-submit
testing. Golden file images in flutter/flutter are triaged
in pre-submit during code review for the given PR.

Visit https://flutter-gold.skia.org// to view and approve
the image(s), or revert the associated change. For more
information, visit the wiki:
https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter

Debug information for Gold --------------------------------
stdout: Given image with hash 316a1ce1bcf477aa5f2d28107669fb29 for test
widgets.image_filter_matrix_offset
Untriaged or negative image:
https://flutter-gold.skia.org/detail?test=widgets.image_filter_matrix_offset&digest=316a1ce1bcf477aa5f2d28107669fb29


stderr: Test: widgets.image_filter_matrix_offset FAIL


result-state.json: No result file found.

When the exception was thrown, this was the stack:
#0      SkiaGoldClient.imgtestAdd (package:flutter_goldens_client/skia_client.dart:243:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```

**Comment by flar** [comment]
That was when the test failed post submit because of the lack of goldens.

According to the docs on goldens, there will be golden test failure that you can follow to update the goldens. No such link was generated during pre-submit. In other words, there was no indication that goldens needed to be updated, nor a link to where to approve them.

**Comment by jonahwilliams** [comment]
I'm not sure. Sometimes the gold notification is substantialled delayed though. Maybe after setting the PR status to approved in frob there wasn't enough time for gold to trigger before it was merged? Or possibly whatever notification was used to trigger gold was dropped.

**Comment by flar** [comment]
But the new tests were run as a pre-submit and they passed with no errors. Why would they then fail post-submit?

**Comment by flar** [comment]
The flutter gold check is supposed to wait for all tests to complete to go green. It was green before that PR was submitted. Further, the logs show that the failing golden tests were, in fact, run during pre-submit and did not cause an error...?

**Pull request merged**
