### PR TITLE
New properties added in RawAutocomplete and Autocomplete widgets

### PR DESCRIPTION
**Pull request by asadbaidar**
New properties added for simple features in `RawAutocomplete` and `Autocomplete` widgets:

- `clearOnUnfocus`
- `clearOnSelection`
- `alwaysShowOptionsWhenFocused`
- `selectHighlightedOptionOnSubmit`
- `allowSubmissionWhenEmpty`
- `optionsOffset`
- `onFieldChanged`

*No breaking changes*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by justinmc — COMMENTED** [review]
Thanks for improving Autocomplete and for all of the documentation you added here.

Would you be able to break this PR up into one PR per parameter?  Or maybe one PR per set of related parameters.  It will be easier to review that way, especially after you add tests.

Speaking of tests, you'll need to add at least one test per parameter, either in widgets/autocomplete_test.dart or material/autocomplete_test.dart.

Lastly, we try to avoid bloat of the parameter lists of Flutter's widgets, so I want to look closely at whether or not each of these parameters is worth the added complexity.  I want to know things like 1. Is it possibly to achieve the functionality of the new parameter without these code changes?  and 2. Is there high demand? Are users confused or burdened by not having this parameter?

Let me know if you're able to break this up and I'd be happy to help review each one!

**Comment by asad-baidar** [comment]
@justinmc Thank you for reviewing. I will break the PR and let you know.

**Comment by Hixie** [comment]
@asad-baidar Thanks for your contribution! Was this broken up as discussed above? Should we close this PR?

**Comment by goderbauer** [comment]
(triage): I am closing this since there hasn't been any follow-up.

**Pull request closed without merging**
