### PR TITLE
Make a couple methods generic so that types flow through properly.

### PR DESCRIPTION
**Pull request by jacob314**
This ended up being ugly due to the Flutter rule that generic arguments 
have to be explicitly set. Maybe there is a way to use annotations to
indicate that omitting the generic for this method is fine? Adding <Null>
for calls to the method where the return type is ignored adds no value.  
Note that there are also a few cases where inference does work correctly
and types now flow through as desired fixing strong mode errors.
For example see: dev/devicelab/lib/framework/utils.dart

@munificent do you have any ideas how we can make the strong mode experience better for this case?

### CODE REVIEW

**Comment by abarth** [comment]
There's an `@optionalTypeArgs` annotation.  Maybe that could be useful here?

/cc @Hixie

**Comment by jacob314** [comment]
Adding @optionalTypeArgs to the Future class would make sense to me.
That seems reasonable to me as I believe there are a lot of ways to end up with Future<dynamic> in the core library in Dart 1.0 so checks on Future<T> types are likely misleading in Flutter even without adding @optionalTypeArgs.

There is only one check of ```(foo is Future<SomeType>)``` in the flutter code and perhaps that check should be changed to ```(foo is Future)```.

I am assuming @optionalTypeArgs can only apply to a class and not a method. It would also be entirely reasonable to apply it at the method level for these two methods if that was possible as omitting generic does not trigger the creation of a Foo<dynamic>.

**Comment by munificent** [comment]
> @munificent do you have any ideas how we can make the strong mode experience better for this case?

The strong mode experience *is* better for this case. The Flutter team is choosing to opt out and not use it. The inference is already there, they just don't take advantage of it.

**Comment by Hixie** [comment]
What we want for Future wouldn't be `@optionalTypeArgs` but some sort of "default type args".

The reason we want types everywhere is to verify that the programmer inferred the same types as the VM. It improves the quality of the code because the VM is proving that the programmer's intent is what the programmer implemented, rather than the VM figuring out if there's a possible interpretation that is consistent, even if the programmer didn't intend it.

However, there are some times where we don't care about the type, as with `GlobalKey` when used with non-stateful widgets (so `key.currentState` isn't going to be used), or where we want a type to be "none", as with `Future<Null>` (or, ideally, on the long term, `Future<void>`).

It would be amazing if there was a way to declare `Future` such that if you don't declare the type, it's assumed to be `Null` (or `void`).

The reason we don't want it to default to `dynamic` is that that would allow people to write bogus code where they're returning values into futures that we don't expect to ever have values, or for them to read values out of futures where we don't expect them to ever have values, etc.

The solution other languages use for this kind of problem is `typedef`, type aliases.

**Comment by Hixie** [comment]
LGTM

**Comment by munificent** [comment]
> The reason we want types everywhere is to verify that the programmer inferred the same types as the VM.

I hope this becomes less necessary once the VM fully implements strong mode.

I totally agree users need to have good confidence about what static types and reified types their code has, but I think it's a real usability problem if the only way for them to get that confidence is by explicitly annotating every type everywhere.

Users of C#, Java, Swift, TypeScript, Scala, Kotlin, SML, Haskell, and others all rely type inference to fill in unannotated types for them, without sacrificing the safety and readability of their code. Dart should be able to do the same.

> It would be amazing if there was a way to declare Future such that if you don't declare the type, it's assumed to be Null (or void).

That would be wrong in lots of places where inference would otherwise fill in a different, correct type. But it would be nice if it did that when inferring the type from a closure that doesn't return anything:

```dart
await inDirectory(flutterDirectory, () async {
  await exec('git', <String>['checkout', revision]);
});
```

We should be able to infer `void` (or Null) for `inDirectory`'s T since the closure doesn't return anything.

**Comment by Hixie** [comment]
> ```dart
> await inDirectory(flutterDirectory, () async {
>   await exec('git', <String>['checkout', revision]);
> });
> ```
>
> We should be able to infer `void` (or Null) for `inDirectory`'s T since the closure doesn't return anything.

This is a great example of why we require explicit types. Suppose the code was instead:

```dart
await inDirectory(flutterDirectory, () async {
  await exec('git', <String>['checkout', revision]);
  return 1;
});
```

The VM would infer that the return value was `int`, which is not what the programmer intended. They intended it to be `void`, but made a mistake, and the compiler isn't catching it. If instead you write:

```dart
await inDirectory<void>(flutterDirectory, () async {
  await exec('git', <String>['checkout', revision]);
  return 1;
});
```

...or:

```dart
await inDirectory<int>(flutterDirectory, () async {
  await exec('git', <String>['checkout', revision]);
});
```

...then the analyzer will notice that what you wrote is incoherent and will flag it.

The more types you are explicit about, the more likely you are to catch a mistake like this.

In any case, that's a choice for the programming team. Flutter does not require that developers using Flutter put types everywhere (and indeed, the fact that we _do_ put types everywhere helps with this, since it increases the odds that the VM will be able to infer types usefully).

> > It would be amazing if there was a way to declare Future such that if you don't declare the type, it's assumed to be Null (or void).
>
> That would be wrong in lots of places where inference would otherwise fill in a different, correct type.

Yes, this would have to be something a package opts into (so package:flutter would say "when you use `Future` without an annotation, it means `Future<void>`", but other packages wouldn't have this assumption). An alternative that would avoid having to have different semantics in different packages would be type aliases, as mentioned earlier.

**Comment by Hixie** [comment]
@jacob314 Let me know if you need someone to land this for you; otherwise, it's good to go.

**Comment by Hixie** [comment]
@jacob314 This branch has conflicts, could you fix them and re-upload? Then either you can land it or if you can't let me know and I'll land it for you.

**Comment by Hixie** [comment]
ping?

**Comment by Hixie** [comment]
I'm going to close this PR since it hasn't been touched in a month. However, please don't hesitate to reopen it if you want to work on it again.

**Pull request closed without merging**
