### PR TITLE
[flutter_tools] add a dart command in flutter cli

### PR DESCRIPTION
**Pull request by faustobdls**
## Description

As a member of the flutterando, Brazilian community, we created a dart cli called slidy, for some advances in it we would like to have easy access to the flutter dart, so I request the PR so that we can run it through the command `flutter dart <dart-file or snapshot-file> `

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jmagman** [comment]
From the hackers-tool Discord chat:


> Fausto Today at 1:48 PM
> Jonah Williams we want to use to run our cli, slidy, auto-upgrade commands (slidy upgrade) and slidy script run <script-name or file> with better performance than the current one, and this way we reduce the amount of written code and we opened it for several others to have access to it to create something different with this functionality
>  
> Jonah Williams Today at 1:49 PM
> It sounds like it should be a feature of your CLI then, not the flutter tool
>  
> Fausto Today at 1:50 PM
> now i'm implementing an extension for vscode to use the cli inside it, the intention is also that we can use it without defining the pub-cache folder of the flutter in the environment variables in the path
> but it is just to run our cli without having to configure something in the variable path, that way we would do  flutter dart slidy.dart.snapshot command 
>  
> Jonah Williams Today at 1:58 PM
> I don't think we're going to add this functionality
>  
> Fausto Today at 1:59 PM
> Jonah Williams I already implemented it, I'm reading the guide to make a good PR, I just wanted to know if it would be approved, doing this
>  
> christopherfujino Today at 2:00 PM
> It likely wouldn't be approved Fausto , as it seems like this is a very specific use case.
> and your use case isn't of benefit to general flutter developers.
>  
> Fausto Today at 2:03 PM
> in Brazil and in some other places it is, several flutter developers that use slidy, will benefit from these features that will be possible with the dart command to run their scripts and etc.
>  
> jmagman Today at 2:09 PM
> I don't quite understand what you're buying for your users trading a dependency on dart for a much larger dependency on Flutter.  But in any case, I agree with christopherfujino here, that's a narrow group of Flutter users.


@zanderso What do you think?

**Comment by zanderso** [comment]
@faustobdls Thanks for the PR.  I understand where you're coming from with this. There are ongoing conversations with the Dart team about the right way to access the Dart SDK from Flutter. I don't want us to jump the gun, so I don't think we'll be able to consider the PR at this time. I'll cc some folks who might be interested in hearing about this use case, though.

/cc @mit-mit @timsneath

**Comment by faustobdls** [comment]
@zanderso Thanks for the warning, this I believe will help other people too, not only the people from Fluttterando, I will finish commenting and documenting the PR yet, but good to know that I am thinking just like them

**Comment by timsneath** [comment]
This is an awesome idea, Fausto -- please don't take our 'no' as meaning
other than great enthusiasm for it. We are looking at how we can modernize
the Dart CLI in particular, since it's a product of its original time. As
zra says, it's probably better to wait until we've rationalized some stuff
before we further institutionalize the existing CLI behavior.

**Comment by faustobdls** [comment]
Thank you @timsneath , when I know it's a good one and that many will benefit, I insist, I thank you very much for your comment and for the Zanderso, if I can help, I'm here, hugs

**Comment by jonahwilliams** [comment]
It sounds like this should be closed until the right design is decided.

**Pull request closed without merging**
