### PR TITLE
Reland "ConstraintsTransformBox (#77994)" reverted in (#78661)

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
This reverts commit c0bcb4fc16381ea0d9e2ff8b22843ab961167308. Diff https://github.com/flutter/flutter/pull/78673/commits/69fe39e4c5caf02a941abfa28ee9892009a42aba

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Kavantix** [comment]
Shouldn't the `constraintsTransform` also be used when computing the intrinsic sizes?

**Comment by LongCatIsLooong** [comment]
@Kavantix the new render object is merely a container and doesn't have opinions about the intrinsic size. It's possible for a particular transform to always return a tight `BoxConstraints` and potentially change the intrinsic size but I can't come up with a practical use case (usually there're better render objects for the job). Do you have an example where the new render object wants to modify its child's intrinsic dimensions?

**Comment by Kavantix** [comment]
@LongCatIsLooong 
Well I mention it because with the current version this widget would cause similar issues as constrainedbox currently (see [this](https://github.com/flutter/flutter/issues/27293#issuecomment-737755744) issue)

So yeah indeed it should still let the child determine the intrinsic size but when asking the child it should apply the constraints, just like [Padding](https://github.com/flutter/flutter/blob/4d7946a68d26794349189cf21b3f68cc6fe61dcb/packages/flutter/lib/src/rendering/shifted_box.dart#L171) does and like ConstrainedBox should do but [still doesn’t ](https://github.com/flutter/flutter/issues/27293#issuecomment-790800506)

**Comment by LongCatIsLooong** [comment]
@Kavantix Ah I see. You're right the transform matters for flow layout. Let me run this against internal tests and see if anything fails.

**Review by mdebbar — APPROVED** [review]
Thanks for fixing the analyzer errors!

**Pull request merged**
