### PR TITLE
Reland `AutomatedTestWidgetsFlutterBinding.pump` provides wrong pump time stamp, probably because of forgetting the precision, via optional flag

### LINKED ISSUE #112610: `AutomatedTestWidgetsFlutterBinding.pump` should match engine frame precision
Companion issue fixed by #112609. Please see PR for description :)

_Copied from PR_

The fix is just one line:

image

I have `git blame` and find the bug exist since the first version 7yr ago, and no special comments about why this is introduced so I guess it is but not feature.

IMHO the bug may be written like, the programmer wants to convert DateTime (the `clock.now()`) into a Duration. But then it is forgotten that both are microseconds precision instead of milliseconds precision, and the milliseconds approach is used.

### PR DESCRIPTION
**Pull request by fzyzcjy**
This relands https://github.com/flutter/flutter/pull/112609, but with a flag that is off by default. The reason why it is designed like this can be found in discussions around https://github.com/flutter/flutter/pull/112609#issuecomment-1278889389.

Close #112610

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by pdblasi-google** [comment]
@fzyzcjy @CaseyHillers @goderbauer

I still think that this change should be made without the boolean flag. The underlying issue with the goldens is that `pumpFrames` defines `interval` with microsecond precision, but the `AutomatedTestWidgetsFlutterBinding` didn't support microsecond precision. @Piinks and I went over a couple of golden changes in the flutter repos test as well and accepted the changes to those goldens as they were a change to a correct state (which is why the goldens are current hanging for this PR).

The secondary issue that makes this difficult to break cleanly is that `LiveWidgetsFlutterBinding` _does_ support microsecond precision, so we can't just update `pumpFrames`' `interval` parameter to be a clean 16 milliseconds by default, as that would break _other tests_.

To start with, the first paragraph in the [breaking changes process](https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes) says:

> Sometimes, however, doing this is necessary for the greater good. We want our APIs to be intuitive; if being backwards-compatible requires making an API into something that we would never have designed that way unless forced to by circumstances, then we should instead break the API and make it good.

Adding a boolean to make the _correct_ behavior happen is not an API that we would have designed on purpose. It's also not a change that we can easily guide people to using, as there's no "new API" we can drive them towards with deprecations or data driven fixes. It'd be something we introduce for a period of time, hope people read the blog, then end up running into the same "breaking change" issues when we eventually remove the boolean or default it to true.

From there, digging into the process, the preferred process is the three step process:

1. Add new API and opt in to the new API
2. Remove the old API
3. Remove the opt in

I think the only way we can get that to happen is to introduce a new version of `pumpFrames` that would support the correct behavior, deprecate the current `pumpFrames`, then eventually remove `pumpFrames`. Here's what I'd propose:

* Fix `AutomatedTestWidgetsFlutterBinding` _without_ the flag
* Introduce a new method with the exact contents that `pumpFrames` currently has:

```
pumpFramesFor(
  Widget target,
  Duration duration, [
    Duration interval = const Duration(milliseconds: 16, microseconds: 683),
  ])
```
* Update `pumpFrames` to pass through to the new `pumpFramesFor` method:
    * Check `if (binding is AutomatedTestWidgetsFlutterBinding)`
    * If it is, then truncate the microseconds off of `interval` before passing through to maintain the current incorrect behavior

My biggest concern with this approach is that `pumpFramesFor` isn't as clean a name as just `pumpFrames`, but it's the best I can come up with. Names aside, introducing a new method and deprecating the old is the only way I can think of to keep the existing behavior and actually be able to drive users to the new api before landing the correct behavior.

**Comment by fzyzcjy** [comment]
@pdblasi-google @CaseyHillers @goderbauer I agree with both sides of the opinion, both looks very reasonable to me. So just ping me when googlers reach a conclusion that what I should do!

**Comment by fzyzcjy** [comment]
So... what should I do?

**Comment by pdblasi-google** [comment]
@fzyzcjy

If you're alright with it, I'd like to grab the issue from you to wrap it up. We'll need to make some changes internally and do some extra documentation to release this due to the internal test failures. If you'd like, I'll guide you through the extra docs and just handle the internal stuff myself, but I think it'll be easier with just one person working to get this landed.

**Comment by fzyzcjy** [comment]
@pdblasi-google Sure :) so shall I close this issue now?

**Comment by pdblasi-google** [comment]
This PR yes. I'll still work off of the original issue so we can keep the wonderful history of this surprisingly complex issue! 😛

**Comment by fzyzcjy** [comment]
@pdblasi-google Looking forward to see it landed!

**Pull request closed without merging**
