### PR TITLE
Always push layer for RenderAnimatedOpacityMixin

### LINKED ISSUE #58425: RenderOpacity sometimes omits its layer during animations which breaks caching performance
The RenderOpacity object will not emit a layer when the opacity is 0 or 255. If that is the static opacity then it might make sense, but when it is the value during an animation, this causes the layer tree to drastically change configuration on each frame.

While this could potentially result in a hit if the tree needs to be constantly reconstructed, an even bigger hit happens because the change of identity of its own layer as it moves from a partial value to either 0 or 255 and back again means that the cached information at the engine level needs to be discarded and then re-rendered.

The layer should absolutely be left intact even for opacity values of 0 or 255 during an animation.

### LINKED ISSUE #71008: RenderAnimatedOpacityMixin causes child pixel snapping when fully opaque
`RenderAnimatedOpacityMixin` has the following paint method, which avoids painting both the child widget and the opacity later when fully transparent. When fully opaque, the opacity layer is elided while the child is painted. Unfortunately this last optimization causes obvious pixel snapping on low DPR screens. 

`RenderAnimatedOpacityMixin.paint`
```dart
 @override
  void paint(PaintingContext context, Offset offset) {
    if (child != null) {
      if (_alpha == 0) {
        // No need to keep the layer. We'll create a new one if necessary.
        layer = null;
        return;
      }
      if (_alpha == 255) {
        // No need to keep the layer. We'll create a new one if necessary.
        layer = null;
        context.paintChild(child!, offset);
        return;
      }
      assert(needsCompositing);
      layer = context.pushOpacity(offset, _alpha!, super.paint, oldLayer: layer as OpacityLayer?);
    }
  }
```

This can be seen fairly easily when a mouse hover first reveals a tooltip, such as in the "example app" section of the flutter gallery. The last frame visible shifts - fairly dramatically compared to the previous animation. Though the video below uses 10x time dilation to make it more obvious, it is still hard to see in the low res/low framerate GIF. 

ezgif-6-2fad4fb28e3e (1)

Keeping the opacity layer even when at fully opaque removes this jump.

### LINKED ISSUE #83050: AnimatedOpacity moves the child widget while playing the animation
h6qYbCHHSj

Maybe the problem happens because of the padding widget on top of the container. But if i remove Padding widget and add the padding attribute to a container, the issue disappears. However, sometimes, this issue occurs even without a padding widget(for example you can wrap the DropdownButtonFormField's icon inside of such AnimatedOpacity widget and also repeat the issue). alwaysIncludeSemantics attribute of the AnimatedOpacity widget does not make any difference. 

As for adding padding inside of the container widget instead of wrapping it with a Padding widget: the issue does not disappear if you remove width: 150.0 and leave container with limitless width. But in my other project, it works the other way around(if i add the boundaries, the issue appears, but if remove them, it disappears), so i have no idea why it happens. 

Code to reproduce the issue:

<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _showSomething = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      home: Scaffold(
        backgroundColor: Colors.green,
        body: Center(
          child:
            Column(
              children: [
                GestureDetector(
                  onTap: () => setState(() => _showSomething = !_showSomething),
                  child: Container(
                    alignment: Alignment.center,
                    height: 40.0,
                    width: 150.0,
                    color: Colors.redAccent,
                    child: Text(
                      'I am a cool button!',
                      style: TextStyle(color: Colors.white),
                    ),
                  ),
                ),
                AnimatedOpacity(
                  opacity: _showSomething ? 1.0 : 0.0,
                  duration: Duration(milliseconds: 425),
                  curve: Curves.easeInOutCubic,
                  alwaysIncludeSemantics: true,
                  child: Padding(
                    padding: EdgeInsets.only(top: 5.0, left: 5.0),
                    child: Container(
                      width: 150.0,
                      child: Text(
                        'Just a text for some reason with an unknown text to test the animation for exactly this text ',
                        style: TextStyle(color: Colors.white),
                      ),
                    ),
                  ),
                ),
              ],
            ),
        ),
      ),
    );
  }
}
``` 

</details>

Flutter version: The latest from the stable channel;

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/71008
Fixes https://github.com/flutter/flutter/issues/83050
Fixes https://github.com/flutter/flutter/issues/58425

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 14 untriaged digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/83145

**Review by jonahwilliams — APPROVED** [review]
LGTM!

Fixing bugs _and_ deleting code, what a PR

**Review by flar — APPROVED** [review]
It looks like a golden threshold is failing, but other than that LGTM.

**Comment by skia-gold** [comment]
Gold has detected about 21 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/83145

**Comment by jonahwilliams** [comment]
I wonder if this is raster cache related. Maybe we could work around it by pushing some other layer in place of the existing opacity layer - but at least we have benchmarks to check on!

**Comment by flar** [comment]
> I wonder if this is raster cache related. Maybe we could work around it by pushing some other layer in place of the existing opacity layer - but at least we have benchmarks to check on!

The layer coming and going basically causes a side effect that the composition of the pictures around the child are disrupted. When the layer is pushed then any Picture currently being built is ended, the children are rendered into their own picture and when they return that Picture is ended and a new one will be created for any content that follows.

When the layer is not pushed, then the preceding children will share a Picture with the children of the animated widget which will also share a Picture with the following children.

I think what we need to ensure is that the previous, descendant, and following content remain isolated regardless of the alpha. Pushing the opacity layer will always ensure this, but it can be managed simply by ensuring that the pictures are broken before and after the children are painted.

It would be even better if this whole sub-tree were treated as a RepaintBoundary - that would make sure that there is no sharing of Picture objects across this widget and also would prevent the changing opacity from causing adjacent children to repaint on either side.

**Pull request merged**
