### PR TITLE
Add new pub command 'Token'

### LINKED ISSUE #91013: Add support for `flutter pub token`
Command was added to pub here https://github.com/dart-lang/pub/commit/bbdac802eb27ab8aa2af6732f739e0b51561d718

### PR DESCRIPTION
**Pull request by sigurdm**
Adds support for `flutter pub token [add|list|remove]`

Fixes: https://github.com/flutter/flutter/issues/91013

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by christopherfujino — COMMENTED** [review]
this looks good, but will need a test. For example: https://github.com/flutter/flutter/pull/53251

**Comment by sigurdm** [comment]
Seems those tests where removed/simplified here: https://github.com/flutter/flutter/pull/76806

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
oh wait, actually, we already fixed it upstream, you just need to rebase upstream to pick up the fix.

**Pull request merged**
