### PR TITLE
Roll meta/pedantic

### PR DESCRIPTION
**Pull request by dnfield**
Unpin meta, fix up callsites.

Last time I tried this, it broke some customer tests. Will have to see if that's still the case.

https://github.com/jocosocial/rainbowmonkey/pull/328

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
Tool changes LGTM

**Comment by jakemac53** [comment]
Note that we are currently considering rolling back this release. There are a lot of trade-offs and no decision as of yet what will happen, but I would hold of on depending on `1.2.1` until a decision has been reached.

**Comment by jakemac53** [comment]
It looks like we will in fact be rolling this back (hopefully today?)

**Comment by dnfield** [comment]
Thanks Jake.  Is there a bug to follow for it?

**Comment by jakemac53** [comment]
https://github.com/dart-lang/sdk/issues/42635

**Comment by dnfield** [comment]
I'll open a new PR that unpins and rolls to the newer meta.

**Pull request closed without merging**
