### PR TITLE
Use CloseButton on AppBar in PopupRoute

### LINKED ISSUE #61255: request: AppBars in PopupRoutes should display CloseButton
## Use case

In a `PopupRoute` like used by `showModalBottomSheet`, the `AppBar` currently shows a `BackButton` rather than `CloseButton`.

This is a result of https://github.com/flutter/flutter/blob/5a00d54eece05852e9f2166713cdfb587ce03a18/packages/flutter/lib/src/material/app_bar.dart#L506

## Proposal

An `AppBar` within a `PopupRoute` should likely display a `CloseButton` because it's displayed over top of another page and `BackButton` doesn't make much sense.

Current:
Screen Shot 2020-07-10 at 4 37 33 PM

Proposed:
Screen Shot 2020-07-10 at 4 37 05 PM

### PR DESCRIPTION
**Pull request by cpboyd**
## Description

From #61255:
In a `PopupRoute` like used by `showModalBottomSheet`, the `AppBar` currently shows a `BackButton` rather than `CloseButton`.

An `AppBar` within a `PopupRoute` should likely display a `CloseButton` because it's displayed over top of another page and `BackButton` doesn't make much sense.

Current:
Screen Shot 2020-07-10 at 4 37 33 PM

Proposed:
Screen Shot 2020-07-10 at 4 37 05 PM

## Related Issues

Fixes #61255.

## Tests

I added the following tests:
`Close button shows correctly with custom PopupRoute` to `scaffold_test.dart` since it contained the related checks for `PageRoute`.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [X] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

The existing test failed because it checked for the `'Back'` tooltip on a `showDialog`.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by chunhtai** [comment]
what is the native behavior? do they also use close button?

**Comment by cpboyd** [comment]
@chunhtai See the "Control" section of [Material Design's Modal Bottom Sheet](https://material.io/components/sheets-bottom#modal-bottom-sheet)

**Comment by shihaohong** [comment]
Hi @cpboyd sorry for taking so long to get to this. I think it's probably better to expose an API that renders a `CloseButton` and keep the default the `BackButton` because of two reasons:

1) This would be a breaking change since it would affect any existing route provided by our libraries, but also affect any user who has a custom extension of `PopupRoute`. If we do decide on providing this by default, we would need to provide some form of backwards compatibility and a migration guide to allow the user to display a `BackButton` for all existing routes (the following routes extend `PopupRoute`: `ContextMenuRoute`, `CupertinoModalPopupRoute`, `DropdownRoute`, `PopupMenuRoute` and `DialogRoute`). More on breaking changes [here](https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes).

2) Other routes that extend `PopupRoute`, as I've mentioned above. Though they may benefit from this improvement, may actually not want this behavior by default. At a glance, it seems like most of these would prefer a `CloseButton`, but we'd need to make sure.

**Comment by shihaohong** [comment]
I added a comment on the linked issue (#61255) and will close this PR as well for the same reason.

**Pull request closed without merging**
