### PR TITLE
Stop the animation controller if a CircularProgressIndicator is determinate

### LINKED ISSUE #21445: CircularProgressIndicator causes 100% CPU on IOS simulator
## Steps to Reproduce

1) Create `main.dart` containing:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CircularProgressIndicator(
          value: .8,
        ),
      ),
    );
  }
}
```
2) Run it on the IOS simulator
3) Run `top -o cpu`
> PID    COMMAND      %CPU
> 47633  Runner       58.6
> 46728  backboardd   43.4

4) Replace `CircularProgressIndicator(value: .8),` with `Column(),`
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(),
      ),
    );
  }
}
```
5) Note Simulator CPU usage drops to zero.

## Flutter Doctor
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.6.0 at /Users/jeff/Dev/2_flutter_tool/flutter
    • Framework revision 9299c02cf7 (3 weeks ago), 2018-08-16 00:35:12 +0200
    • Engine revision e3687f70c7
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✗] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • iPhone 7 • D840D735-FEF3-4486-940C-923FC8044EB5 • ios • iOS 11.4 (simulator)

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/21445

### CODE REVIEW

**Comment by jason-simmons** [comment]
@HansMuller

**Comment by HansMuller** [comment]
LGTM, but this needs a regression test.

Also: could you change `const Duration(milliseconds: 6666)` to `const Duration(seconds: 5)` (and line 225 in progress_indicator_test.dart) ? The current version looks like a joke.

**Comment by jason-simmons** [comment]
Done

**Comment by HansMuller** [comment]
Looks good however you'll also want to update the test that contains (used to be line 225):
```
await tester.pump(const Duration(milliseconds: 6666));
```

**Pull request merged**
