### PR TITLE
Add `onSubmitted` property to `SearchBar`

### LINKED ISSUE #126551: Add onSubmitted to SearchBar
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

There might be a (possibly different) action to be initiated when the user finishes the text entry and presses the Done button on the keyboard. In some use cases, interim suggestions are not required, a search anchor is not used but the existing Material look & feel of a standalone `SearchBar` would be welcome.

### Proposal

Add an optional `onSubmitted` handler to allow the developer to decide which even to act upon.

### PR DESCRIPTION
**Pull request by QuncCccccc**
Fixes #126551

This PR is to add `onSubmitted` property to `SearchBar`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by PsyOhm23** [comment]
Hi, I don't know if I can report a potential associated issue here but the `SearchAnchor.bar ` don't have the `onChanged` or the recently added `onSubmitted`  property ?
Thanks

**Comment by PsyOhm23** [comment]
@QuncCccccc any advice ?

**Comment by QuncCccccc** [comment]
> @QuncCccccc any advice ?

Creating an issue sounds good to me! Will add this to SearchAnchor.bar soon. Thanks:)

**Comment by PsyOhm23** [comment]
Thanks for your reply :) I've created this issue #130687 ;)

**Pull request merged**
