### PR TITLE
Introduce kernel mode in Flutter tools

### PR DESCRIPTION
**Pull request by aam**
This introduces ```--is-kernel-mode``` boolean option to 'build flx' and 'run' flutter tools commands as in
```flutter run -v --is-kernel-mode --local-engine=android_release --release```.

When specified, flutter tools produce and send to the device platform.dill and main.dart.dill instead of snapshots and source files.

Proper operation of this option on device currently depends on https://codereview.chromium.org/2970543003, https://github.com/flutter/engine/compare/master...aam:flutter-kernel and ```hash/501688de4cb6ba62a5bfe655361edf122cc1d7fc```  in flutter/bin/internal/dart-sdk.version, but this can be landed without affecting existing flows to let more people be look at kernel flutter flows.

### CODE REVIEW

**Comment by mit-mit** [comment]
@aam we would like to have a single, uniform flag for previewing the Dart 2.0 tool chain across all Dart and Flutter tools. And we should not expose internal component names to developers.

Can we use the option `--preview-dart-2` rather than `--is-kernel-mode` ?

**Comment by mit-mit** [comment]
@aam did you get the flag changed to `--preview-dart-2`?

**Comment by aam** [comment]
@mit-mit I haven't, that should be easy once the rest of things fall in place. Unfortunately there are other things in this PR that are not functional yet(which I didn't realize when I put it together).

**Comment by mit-mit** [comment]
OK, thanks

**Comment by aam** [comment]
Will be closing in favor of https://github.com/flutter/flutter/compare/master...aam:flutter-tools-kernel-mode-simple

**Comment by Hixie** [comment]
@aam should we close this PR then?

**Pull request closed without merging**
