### PR TITLE
Remove await for syntax from fuchsia log scanner

### LINKED ISSUE #24261: Fuchsia attach can hang due to await for
This lists attached isolates I believe, something is going wrong here.

### PR DESCRIPTION
**Pull request by jonahwilliams**
The await for syntax seems to trick the command runner into thinking the task hasn't finished yet

Fixes https://github.com/flutter/flutter/issues/24261

### CODE REVIEW

**Comment by tvolkert** [comment]
Is there an underlying issue with `async*` and `await for` that we should be filing as an issue in the Dart SDK?  Can you create a reduced test case that shows the failure?

**Comment by jonahwilliams** [comment]
My suspicion is that since the `await for` pauses the stream at times that might be triggering something else down the line in how we detect whether a command is still running.   I will investigate further, but we should land this when I fix the tests since it is fairly severe.

**Review by tvolkert — APPROVED** [review]
LGTM, but please do follow-up to see if there's a deeper problem here, because `await for` should be semantically equivalent.

Then again, I may be missing something 😄 

/cc @lrhn

**Comment by lrhn** [comment]
The `yield` inside the `await for` can (and likely does) trigger a pause of the input stream. If that is not handled properly somewhere else, then this can just be a symptom of the actual error.
(I obviously have no idea what's really going on, I hope someone does :smile:).

**Pull request merged**
