### PR TITLE
Roll engine to 0c119932c0d6cb30dafd75ec717d1eda76fd7651

### PR DESCRIPTION
**Pull request by gspencergoog**
Also, update packages, which forced a number of changes:

- Renaming isInstanceOf to TypeMatcher (from matcher package)
- Hiding of Flutter's `TypeMatcher` in places where we were using isInstanceOf from the matcher package, since they deprecated that in favor of their class (also called TypeMatcher, of course).
- Fixing several pieces of example code that now fail checks (seems that the example code checker doesn't honor the `@optionalTypeArgs` annotation).
- Renaming some uppercase constants to lowercase (HttpResult.OK -> ok, etc.).

This replaces Florians [roll](https://github.com/flutter/flutter/pull/18569), since I already had a bunch of these things in a branch from this weekend.

### CODE REVIEW

**Comment by gspencergoog** [comment]
OK, I changed my tack here: I decided to keep our implementation of TypeMatcher, and just hide it for the tests that use the one from matcher (that used to be called isInstanceOf).  This preserves the existing API, doesn't require re-exporting, and isn't too onorous.  I still think we need to consolidate on the matcher TypeMatcher someday (since they do the same thing), but I don't want to hold up the roll for that.

**Review by floitschG — APPROVED** [review]

**Comment by Hixie** [comment]
This patch has a number of things that are concerning. Specifically, changing the tests to use TypeMatcher is a problem because it is less idiomatic and it conflicts with our TypeMatcher class; these are non-backwards-compatible breaking changes which are going to hurt our users for little benefit, as far as I can tell. Secondly, it appears the analyzer has stopped supporting `@optionalTypeArgs` in certain cases, which is a regression.

Can we revert this for now?

**Comment by DaveShuckerow** [comment]
Heads up: Resolving this appropriately is a blocker for #18573, which blocks the g3 roll.

Please prioritize resolving any issues that need to be resolved on this merge.

**Comment by Hixie** [comment]
I'm looking at reverting the matcher change for now; https://github.com/flutter/flutter/issues/18609 still needs investigation.

**Comment by cbracken** [comment]
This appears to have regressed the flutter_gallery_ios32__transition_perf  missed_transition_count benchmark.

**Comment by Hixie** [comment]
Should we revert?

**Pull request merged**
