### PR TITLE
Don't give the correct checksum, it's misleading.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Review by mdebbar — APPROVED** [review]

**Comment by Hixie** [comment]
test-exempt: removing code

**Comment by Hixie** [comment]
fyi @christopherfujino

**Review by christopherfujino — CHANGES_REQUESTED** [review]
Why is it misleading? Having the checksum in the error message is helpful.

**Comment by christopherfujino** [comment]
> Why is it misleading? Having the checksum in the error message is helpful.

In particular, it's helpful when there are cherrypicks to pub dependencies, and we can't use `flutter update-packages --force-upgrade` lest we roll everything.

**Comment by Hixie** [comment]
Spoke with @christopherfujino, the checksum is currently used during cherry-pick scenarios.

To address both needs, I implemented cherry-picking of packages, see https://github.com/flutter/flutter/pull/128917.

That PR supersedes this one.

**Pull request closed without merging**
