### PR TITLE
Remove ideviceinfo, idevice_id artifacts

### PR DESCRIPTION
**Pull request by jmagman**
## Description

Remove ideviceinfo and idevice_id code. Made dead by https://github.com/flutter/flutter/pull/49854.

## Tests

Updated cache_test, and mac_test. 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

**Comment by jmagman** [comment]
This needs a corresponding CL to remove `g3assets.ideviceinfo` and `g3assets.idevice_id`.

**Review by zanderso — APPROVED** [review]

**Comment by zanderso** [comment]
@christopherfujino Can the infra recipe be updated to avoid building these?

**Comment by christopherfujino** [comment]
> @christopherfujino Can the infra recipe be updated to avoid building these?

yup, I'll open an issue to track.

**Review by christopherfujino — APPROVED** [review]
looks GREAT to me!

**Pull request merged**
