### PR TITLE
[Api docs] Dartpad demo for alert dialog.

### PR DESCRIPTION
**Pull request by Alabhya268**
image
image

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

This PR has same changes as #75148

### CODE REVIEW

**Comment by Alabhya268** [comment]
@shihaohong

**Review by shihaohong — APPROVED** [review]

**Comment by Alabhya268** [comment]
> @Piinks , Please approve this PR as this as same changes as #75148 ,
> 
> Also in last PR #75148 ,while updating branch I used git merge and it caused problem and git rebase was not working as expected.
> Normally "Update branch" button on Github does the trick, but its not visible .
> So could you please tell me what cmd should I run to update branch manually ?
> 
> Thank in advance

@shihaohong can you tell me how to get around this as I've now made this mistake twice?

**Comment by shihaohong** [comment]
You'll need to rebase/merge from the `master` branch: https://www.atlassian.com/git/tutorials/merging-vs-rebasing#conceptual-overview.

Personally, I use `git pull upstream master`, which is basically a git fetch and a git merge.

**Comment by Alabhya268** [comment]
> You'll need to rebase/merge from the `master` branch: https://www.atlassian.com/git/tutorials/merging-vs-rebasing#conceptual-overview.
> 
> Personally, I use `git pull upstream master`, which is basically a git fetch and a git merge.

does this update all branches?

**Comment by Alabhya268** [comment]
> You'll need to rebase/merge from the `master` branch: https://www.atlassian.com/git/tutorials/merging-vs-rebasing#conceptual-overview.
> 
> Personally, I use `git pull upstream master`, which is basically a git fetch and a git merge.

Does Github "Update branch" button does the same ?

**Comment by shihaohong** [comment]
Looks like you merged with upstream master correctly! Although, the test that's failing isn't related to your test. I'll take a look.

**Pull request merged**
