### PR TITLE
Upgrade package:vm_service to 14.2.1

### PR DESCRIPTION
**Pull request by derekxu16**
CP request: https://github.com/flutter/flutter/issues/146897
Upstream bug: https://github.com/dart-lang/sdk/issues/55475

### CODE REVIEW

**Review by christopherfujino — COMMENTED** [review]
Is your bugfix the only diff between 14.2.0 and 14.2.1? Otherwise we should put out a patch hotfix 14.2.0+1.

**Comment by derekxu16** [comment]
> Is your bugfix the only diff between 14.2.0 and 14.2.1?

Yes.

**Comment by christopherfujino** [comment]
> > Is your bugfix the only diff between 14.2.0 and 14.2.1?
> 
> Yes.

Ahh, nice! :)

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
Can you add a reference to the bug in the PR description (since github will generate the squash commit message from that)?

**Comment by derekxu16** [comment]
> Can you add a reference to the bug in the PR description (since github will generate the squash commit message from that)?

Done.

**Pull request merged**
