### PR TITLE
Fix URL of the template to report a corrupted dart SDK

### PR DESCRIPTION
**Pull request by reez12g**
Fixed the URL of the template for reporting a corrupted dart SDK.

- https://github.com/flutter/flutter/issues/92683

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by reez12g** [comment]
`Linux tool_integration_tests_4_4` is failing, is it related to https://github.com/flutter/flutter/issues/91270 🤔 ?

**Review by reez12g — COMMENTED** [review]
`Linux tool_integration_tests_4_4` is failing, is it related to https://github.com/flutter/flutter/issues/91270 🤔 ?

**Review by goderbauer — APPROVED** [review]
LGTM

@christopherfujino Can you give this a secondary review? Thanks.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
test-exempt: not really clear how we would test this in practice.

**Comment by christopherfujino** [comment]
> `Linux tool_integration_tests_4_4` is failing, is it related to #91270 thinking ?

I'm re-running the test, if it fails again I will re-open the issue.

**Comment by christopherfujino** [comment]
I'm sorry we never got back to merging this, but it was fixed upstream in a different PR: https://github.com/flutter/flutter/commit/bde9f11831f60ef35ab15d69bc37fb47e04b0ee1. Thanks again for the PR.

**Pull request closed without merging**
