### PR TITLE
Move ios screenshot test to flutter gold.

### PR DESCRIPTION
**Pull request by cyanglaz**
## Description

This PR moves the driver screenshot test to use flutter gold. It removes all the old local gold files.
It also removes the `dart:ui` deps in `_goldens_io_.dart` as it is not needed anymore \cc @blasten 
The PR combines the fuchsia gold test and ios gold tests as they have the same logic now.
The PR also updates the `README` to reflect the new tests setup.

Waiting for https://github.com/flutter/flutter/pull/49815 to land before landing this.

## Tests

I added the following tests:

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by blasten — APPROVED** [review]
LGTM

**Comment by Piinks** [comment]
The support for luci should re-land once the tree is green. https://github.com/flutter/flutter/pull/52760

**Comment by cyanglaz** [comment]
@Piinks Nice, thanks

**Comment by Piinks** [comment]
#52760 has landed 🎉

**Comment by cyanglaz** [comment]
@Piinks Thanks for the heads up. @blasten I'm going to land this when flutter tree is green. This test is marked as flaky so it won't block the flutter tree, if the flow doesn't work out for us we can just revert or introduce fixes if needed.

**Comment by Piinks** [comment]
@cyanglaz have you confirmed this is WAI after landing? I didn't see an image on the [gold dashboard](https://flutter-gold.skia.org/list?fdiffmax=-1&fref=false&frgbamax=255&frgbamin=0&head=true&include=false&limit=50&master=false&match=name&metric=combined&neg=false&new_clstore=true&offset=0&pos=true&query=source_type%3Dflutter&sort=desc&unt=true) for this.

**Comment by cyanglaz** [comment]
> @cyanglaz have you confirmed this is WAI after landing? I didn't see an image on the [gold dashboard](https://flutter-gold.skia.org/list?fdiffmax=-1&fref=false&frgbamax=255&frgbamin=0&head=true&include=false&limit=50&master=false&match=name&metric=combined&neg=false&new_clstore=true&offset=0&pos=true&query=source_type%3Dflutter&sort=desc&unt=true) for this.

The device lab tests didn't work, it performed similar to my local test, which says something like 'Golden file comparison requested for "red_square_driver_screenshot__iPhone7,2.png"; skipping...`

And it is not enabled on LUCI yet as LUCI doesn't work with real iOS devices. 

I was pulled away for something else, ill eventually circle back on this tho.

**Comment by Piinks** [comment]
SGTM, Let me know when and if I can help when you do. :)

**Pull request merged**
