### PR TITLE
Revert "roll engine to 9af920ef22f311588b649ba876127993f5c1362c"

### PR DESCRIPTION
**Pull request by amirh**
Reverts flutter/flutter#19365

### CODE REVIEW

**Comment by amirh** [comment]
Landing TBR and on red to fix test breakage.

**Comment by jonahwilliams** [comment]
I'm not able to reproduce the appveyor failure locally

**Comment by amirh** [comment]
I guess it might have been a flake. Though it only failed on the Windows machine. Did you run it on Windows?

**Comment by jonahwilliams** [comment]
I'll try rebuilding the commit that failed

**Comment by jonahwilliams** [comment]
Rebuilt and ran both commits and they stayed green.  Since I can't reproduce it locally either I'm going to call it a flake

**Pull request merged**
