### PR TITLE
EdgeInsets => EdgeInsetsGeometry

### PR DESCRIPTION
**Pull request by xclud**
Use the more generic EdgeInsetsGeometry instead of EdgeInsets. This enables to use EdgeInsetsDirectional as well and should be useful for Right-To-Left scenarios.

### CODE REVIEW

**Comment by xclud** [comment]
I signed CLA.

**Comment by Hixie** [comment]
Where does it get resolved? Or is it passed through to something that already accepts EdgeInsetsGeometry?

**Comment by Hixie** [comment]
(this will need tests)

**Comment by xclud** [comment]
For almost every padding enabled widget in Flutter we are able to set a padding either from a left-top-right-bottom or start-top-end-bottom because the padding property itself is a EdgeInsetsGeometry and we can assign values of type EdgeInsets or EdgeInsetsDirectional to it (child classes).

For InputDecorator this was not the case and i believe it is an implementation mistake. Currently we are unable to do the following:

```
new InputDecorator(
contentPadding: new EdgeInsetsDirectional...()
);
```

Above code will cause a compile-time error.

**Comment by HansMuller** [comment]
I think this is a good improvement to make however I don't think this is the right way to make it.

InputDecoration.contentPadding and InputDecorationTheme.contentPadding should be EdgeInsetsDirectional and _InputDecoratorState should resolve contentPadding based on Directionality.of().

**Comment by Hixie** [comment]
Where are the `EdgeInsets` values actually used? Are they just passed on to Paddings or such, or are they directly used somewhere?

**Comment by HansMuller** [comment]
They're directly used (in a way where start/end resolution matters) by the InputDecorator's renderer at `performLayout()` time

**Comment by Hixie** [comment]
Ah yeah in that case this patch will indeed not work, and we'll have to resolve them before use. I'm surprised the code above compiles without analyzer warnings, actually.

**Comment by Hixie** [comment]
@xclud Will you be able to continue working on this (to address the comments above)? It's totally fine if not; we can take it over (though it might take longer). I'm just asking because I'm trying to clean out our review queue.

**Comment by xclud** [comment]
@Hixie I want to bring your attention to the field type of `contentPadding` which is `EdgeInsets` in the `InputDecoration` class.

On the other hand, for the rest of the Widgets `padding` field is of type `EdgeInsetsGeometry`. Take `SingleChildScrollView` as an example, here is the padding field:

`  final EdgeInsetsGeometry padding;`

I believe the `InputDecoration` case is a mistake. Being `EdgeInsetsGeometry` allows us to use a value of type either `EdgeInsets` or `EdgeInsetsDirectional`.

**Comment by Hixie** [comment]
Yes, it's definitely a mistake. The fix is not just to change the type though. We have to change the type, and resolve them (using `EdgeInsertsGeometry.resolve`) before using them.

**Comment by HansMuller** [comment]
I'm making an InputDecoration change now, will fix this as well.

**Comment by Hixie** [comment]
@HansMuller Is this resolved now?

**Comment by HansMuller** [comment]
This was fixed in https://github.com/flutter/flutter/pull/17292

**Pull request closed without merging**
