### PR TITLE
[Android] Fix Linux Android flavors_test

### LINKED ISSUE #115121: Android flavors_test is failing, `"app-paid-release.apk" does not exist`
Started on https://github.com/flutter/flutter/pull/114048
```
[flavors_test] [STDOUT] stderr: "build\app\outputs\flutter-apk\app-paid-release.apk" does not exist
```
https://ci.chromium.org/p/flutter/builders/staging/Windows_android%20flavors_test_win/1677
https://ci.chromium.org/p/flutter/builders/staging/Linux_android%20flavors_test/1

cc @a-wallen

### PR DESCRIPTION
**Pull request by camsim99**
Fixes https://github.com/flutter/flutter/issues/115121 with the solution @jmagman noted [here](https://github.com/flutter/flutter/issues/115121#issuecomment-1311013134).

Changes test to install debug version of the test app versus the release version (which is installed by default via `flutter install` but is not built by the call made to `flutter drive`).

cc @a-wallen 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jmagman** [comment]
If you want to test this in presubmit you can temporarily remove `bringup: true` and `presubmit: false`, check that it's passing, add a link to the passing test, then revert that change.
https://github.com/flutter/flutter/blob/d58855c49986d46588b0e2b1bf2f8b2bb97e3932/.ci.yaml#L1706-L1708

Or brave `led`...

**Comment by jmagman** [comment]
I think you hit https://github.com/flutter/flutter/issues/102402 in https://github.com/flutter/flutter/pull/116129/checks?check_run_id=9778613166.  Push an empty commit to retrigger?

**Comment by jmagman** [comment]
Passed! https://ci.chromium.org/p/flutter/builders/try/Linux_android%20flavors_test/2

**Review by jmagman — APPROVED** [review]
Thank you!

**Review by a-wallen — APPROVED** [review]
@camsim99 thank you!

**Comment by camsim99** [comment]
@jmagman Is there a reason PRs get stuck on Google testing like this?

**Comment by jmagman** [comment]
You're hitting b/234758732, I pinged the roller team about this since this PR isn't listed in the pre-merge FRoB tab.

**Comment by CaseyHillers** [comment]
@camsim99 can you rebase your PR with tip of tree? It's 150 commits behind, and Google testing can't correctly patch it in if it's that old.

**Pull request merged**
