### PR TITLE
Update .gitignore.tmpl to ignore coverage

### PR DESCRIPTION
**Pull request by maxzod**
*List which issues are fixed by this PR. You must list at least one issue.*
#101349

 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by christopherfujino** [comment]
@maxzod thank you for contributing! However, I am not sure this is the right change to make. I will close this for now, and pose a question on the issue to discuss.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by SPiercer** [comment]
LFTM

**Comment by christopherfujino** [comment]
> LFTM

What's LFTM mean?

**Comment by SPiercer** [comment]
Looks fine to me :""

**Comment by SPiercer** [comment]
> > LFTM
> 
> What's LFTM mean?

Looks fine to me :""

**Comment by christopherfujino** [comment]
@maxzod this will need a test. Can you add one here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands.shard/permeable/create_test.dart

**Comment by maxzod** [comment]
> @maxzod this will need a test. Can you add one here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands.shard/permeable/create_test.dart

ok

**Comment by maxzod** [comment]
@christopherfujino its my first time to contribute directly to the framework i use Windows 10 and there is no docs alliable about how to setup the env ,, only linux an mac os ! 
https://github.com/flutter/flutter/wiki/Setting-up-the-Framework-development-environment

**Comment by christopherfujino** [comment]
> @christopherfujino its my first time to contribute directly to the framework i use Windows 10 and there is no docs alliable about how to setup the env ,, only linux an mac os ! https://github.com/flutter/flutter/wiki/Setting-up-the-Framework-development-environment

Those should work. I'm not sure which step you're stuck on, but all you should need to test this feature is git. You shouldn't need to debug an android device.

**Review by christopherfujino — CHANGES_REQUESTED** [review]
This needs a test

**Comment by christopherfujino** [comment]
Thank you for contributing! As you have not responded within 3 weeks, I will be closing this PR as stale. If you are still interested in landing this, feel free to rebase this PR upstream, address code review feedback, and re-open this PR.

**Pull request closed without merging**
