### PR TITLE
Roll back to dd32b3fbc21439df90c872eee88de9cb35633697

### PR DESCRIPTION
**Pull request by jonahwilliams**
This breaks the devicelab test flutter_test_performance with error messages:

```
test stdout (TestStep.testLoading): Shell: ---- failed to open  as a font
test stdout (TestStep.testLoading): Shell: ---- failed to open  as a font
2018-11-05T18:02:43.192831: test stdout (TestStep.testLoading): Shell: ---- failed to open  as a font
2018-11-05T18:02:43.193324: test stdout (TestStep.testLoading): Shell: ---- failed to open  as a font
test stdout (TestStep.testLoading): Shell: ---- failed to open  as a font
test stdout (TestStep.testLoading): Shell: ---- failed to open  as a font
```

### CODE REVIEW

**Comment by jonahwilliams** [comment]
cc @goderbauer

**Review by goderbauer — APPROVED** [review]
LGTM

Sorry... engine side has also been reverted until I figure out why the tester loads all these fonts...

**Comment by dnfield** [comment]
I'm going to turn off the autoroller for now.  Next engine roll will require a goldens update anyway.

**Comment by goderbauer** [comment]
Can you switch the auto roller to dry run instead of turning it off? Thanks!

**Comment by dnfield** [comment]
Done

**Comment by goderbauer** [comment]
Let’s go with https://github.com/flutter/flutter/pull/23986 instead. It rolls the upstream revert from the engine repo into the flutter repo.

**Pull request closed without merging**
