### PR TITLE
Update test expectations after using --lazy-async-stacks in JIT mode

### PR DESCRIPTION
**Pull request by mkustermann**
This is the accompanying change for [0]: We should include this change together with the roll.

[0] https://github.com/flutter/engine/pull/16556

### CODE REVIEW

**Comment by dnfield** [comment]
How about we just temporarily disabled the test until the engine rolls to avoid the need for another manual roll?

**Comment by mkustermann** [comment]
Friendly ping :)

I don't want to land the engine change (see https://github.com/flutter/engine/pull/16556) without having approval for this one first, because it makes sense to land them together.

**Comment by mkustermann** [comment]
> How about we just temporarily disabled the test until the engine rolls to avoid the
> need for another manual roll?

Great idea: https://github.com/flutter/flutter/pull/51047

**Comment by mkustermann** [comment]
I've just submitted the engine CL, once that gets rolled into flutter/flutter this PR's presubmit checks should succeed and we can land it.

**Comment by chunhtai** [comment]
Can this one be rebased and try to see if it pass?

**Comment by chunhtai** [comment]
a friendly bump

**Comment by goderbauer** [comment]
@mkustermann Is this one still on your radar?

**Comment by goderbauer** [comment]
@mkustermann I am going to close this one for now as it is getting pretty old. Please feel free to re-open when you find the time to look at it again. Thanks!

**Pull request closed without merging**
