### PR TITLE
[deps] Update package:web dependency.

### LINKED ISSUE #135075: Bump pkg:web across repo to 0.2.1-beta
This is the latest release which includes helpers and updated APIs!

### PR DESCRIPTION
**Pull request by ditman**
This PR is the result of running:

```console
$ flutter update-packages --force-upgrade
```

Fixes #135075

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by christopherfujino** [comment]
@ditman let's try https://github.com/flutter/flutter/pull/134958, which is a superset of this one.

**Comment by ditman** [comment]
Closing in favor of https://github.com/flutter/flutter/pull/134958

**Comment by christopherfujino** [comment]
This will need either a rebase, or to be regenerated from scratch to avoid a merge conflict with https://github.com/flutter/flutter/pull/134958 (which unfortunately did not bump package:web)

**Comment by christopherfujino** [comment]
Unfortunately, I can't re-open the PR as the branch has been deleted (I believe you have this power, though, @ditman )

**Comment by ditman** [comment]
I'll recreate this one, no worries!

**Review by christopherfujino — APPROVED** [review]
LGTM. i'll leave it as an exercise for the reader to resolve the git conflict.

**Comment by ditman** [comment]
This one is much cleaner now @christopherfujino! I'll add the autosubmit label. Thanks for the quick review!

**Comment by ditman** [comment]
"No results matched your search criteria." take another look flutter-dashboard!

**Comment by ditman** [comment]
I should have pushed an empty commit, rather than rebasing the branch 🤦

**Comment by ditman** [comment]
Let's try and recreate this from scratch, and see what FRoB thinks :)

**Pull request closed without merging**
