### PR TITLE
[flutter_tool] Don't download CanvasKit if it's already in flutter_web_sdk

### PR DESCRIPTION
**Pull request by harryterkelsen**
Don't download CanvasKit from CIPD if it's already included in the `flutter_web_sdk` engine artifacts.

We are building CanvasKit locally in the Flutter engine now, and soon will be bundling it with `flutter_web_sdk`. This change causes flutter_tool to use the built version rather than the one from CIPD when the built version is available.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Going forward, will we still need to support downloading from the canvaskit URL, or is the idea to only use the prebuilt?

**Review by eyebrowsoffire — APPROVED** [review]
LGTM!

**Comment by hterkelsen** [comment]
The plan is to only use the prebuilt version

**Comment by jonahwilliams** [comment]
It sounds like this is for a soft transition we need to make then? Could you link a bug in the code here with a note that it can all be deleted once the work is completed?

**Comment by hterkelsen** [comment]
Done. PTAL

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by mdebbar — APPROVED** [review]

**Pull request merged**
