### PR TITLE
Refactor: Split and adjust all tests in `button_tests.dart' into its respective files #42798

### LINKED ISSUE #42798: All tests in `button_tests.dart` should be split into its respective widget's test files
A `buttons_tests.dart` file exists that contains tests for different buttons like `FlatButton`, `RaisedButton` and `MaterialButton` exist, even though `flat_button_test.dart`, `raised_button_test.dart`, and `material_button_test.dart` exist. 

We should really split up these tests into their respective files.

Edit: An attempt was made to conduct the entire refactor in one PR. It turned out to be difficult to review and we should really break down this refactor into multiple PRs to ensure that none of the tests are accidentally changed or that unnecessary set up steps or imports were added while porting over. 

- [x] FlatButton - https://github.com/flutter/flutter/pull/43742
- [x] RaisedButton - https://github.com/flutter/flutter/pull/44169
- [x] OutlineButton - https://github.com/flutter/flutter/pull/44328
- [x] MaterialButton - https://github.com/flutter/flutter/pull/43528

### PR DESCRIPTION
**Pull request by Inconnu08**
## Description

The existing monolithic `buttons_tests.dart` file contains tests for different buttons like `FlatButton`, `RaisedButton`, `OutlineButton` and `MaterialButton`, even though `flat_button_test.dart`, `raised_button_test.dart`, `outline_button_test.dart`, and `material_button_test.dart` exists.

This PR splits up and adjusts these tests properly into their respective files.

## Related Issues

Resolves #42798

## Tests

I added the following tests:

- Refactored existing

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Inconnu08** [comment]
@shihaohong should I delete `button_tests.dart' since it has no tests of its own or is this good enough?

**Comment by shihaohong** [comment]
It should be okay to just completely delete the `button_tests.dart` file. Just make sure that if there were any files that point to it, they no longer do so.

**Comment by Inconnu08** [comment]
@shihaohong alright nothing does, I'll delete it

**Comment by Inconnu08** [comment]
@shihaohong is everything good now?

**Comment by shihaohong** [comment]
Hi, sorry about the delay, I've been waiting until I had a good chunk of time to review this PR since the diffs are tough to parse when moving entire sections of code for a refactor like this. I just want to make sure that nothing has changed out of the ordinary by mistake.

**Comment by Inconnu08** [comment]
Oh it's fine, please do take your time and thank you!

**Comment by shihaohong** [comment]
I just started reviewing it and was thinking this could probably be better done with smaller incremental PRs... for example:

PR 1: Migrate MaterialButton tests
PR 2: Migrate FlatButton tests
... etc

Is that within your bandwidth? It would make this process easier on my end and reduce the chance for errors uncaught by both you and I.

**Comment by shihaohong** [comment]
@Inconnu08 After some more thought, I don't feel comfortable reviewing a single PR refactor of this scale. I feel like there's a lot of room for mistakes to occur. To move this forward, I'd prefer if we broke this down into multiple consecutive PRs. 

I'll close this PR for now and add a note to the original issue to make sure we don't run into this situation in the future.

**Comment by Inconnu08** [comment]
@shihaohong alright, that's fine with me. I too initially thought about it. Anyway I will split them into separate PRs

**Comment by shihaohong** [comment]
Thanks for understanding! :)

**Pull request closed without merging**
