### PR TITLE
[CP] Space character should be optional when tree shaking fonts

### PR DESCRIPTION
**Pull request by eyebrowsoffire**
This is the cherry-pick for https://github.com/flutter/flutter/pull/132880

### CODE REVIEW

**Comment by zanderso** [comment]
NB: This CP depends on the engine CP here: https://github.com/flutter/engine/pull/44869

**Review by zanderso — APPROVED** [review]

**Comment by itsjustkevin** [comment]
@eyebrowsoffire could you try rebasing this commit to head?

**Comment by zanderso** [comment]
@itsjustkevin I clicked the rebase button again. I think it might work this time?

**Comment by zanderso** [comment]
Yup, this appears to be in good shape now.

**Pull request merged**
