### PR TITLE
allow application to know if the user is still engaged with the slider

### PR DESCRIPTION
**Pull request by jdeltoft**
## Description

I needed a way to know when the user was done interacting with my sliders so I could send the REST command resulting from the value change just once.  This exposes knowledge to the application creating the slider widget if the user is still touching the slider, or if they did a quick tap to move the slider.  In both cases, I want to then trigger my action.

## Tests

I added the following tests:

I need some help with adding tests for this.  I did just run with the slider and confirm with the logging that touch active status I added is true until I release and also quick taps of the slider work to trigger a touch active.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x] I signed the [CLA].
- [x ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x ] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by jdeltoft** [comment]
I did sign the CLA, not sure how to fix that.  I don't know of any other authors.  This was a small change off master.

**Comment by HansMuller** [comment]
CC @clocksmith

**Comment by clocksmith** [comment]
onChangeEnd fires once when the user is done interacting with the slider. onChange fires every time the slider value updates (including within an interaction). Can you use onChangeEnd to accomplish sending the rest command only once?

**Comment by jdeltoft** [comment]
> onChangeEnd fires once when the user is done interacting with the slider. onChange fires every time the slider value updates (including within an interaction). Can you use onChangeEnd to accomplish sending the rest command only once?

From my original testing, onChangeEnd fires twice.  It was firing when I started changing the slider and it fired when I lifted my finger.  I will test again and see if that's still causing me the same issues.

**Comment by jdeltoft** [comment]
I've tested the latest flutter today, and this is now working fine. Closing this out as unnecessary. 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.14.7-pre.19, on Mac OS X 10.14.6 18G2022, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (3 available)

• No issues found!

**Comment by jdeltoft** [comment]
Ahhhhhh, so I just found a new clue.  Here was the cause of my "on change end" getting called twice.  Once when I started touching the slider and once when I released (that was my original complaint here.  This code fails:

          Container(
              padding: EdgeInsets.symmetric(horizontal: 5),
              child: Slider(
                min: 0,
                max: 100,
                value: _dimValue,
                onChanged: _setDimValue,
                onChangeEnd: _sendDimValue,
                divisions: 10,
              )),

And this code works as I expect (only call my _sendDimValue function when I release the slider):

          Container(
              padding: EdgeInsets.symmetric(horizontal: 5),
              child: Slider(
                min: 0.0,
                max: 100.0,
                value: _dimValue,
                onChanged: _setDimValue,
                onChangeEnd: _sendDimValue,
                divisions: 10,
              )),

So you see the difference is that the min/max are doubles in the working case.  The issue seems to be that the initial touch maybe triggers a conversion of int to double and that triggers a send somehow.

**Comment by jdeltoft** [comment]
@clocksmith Just FYI see my discovery.  Is that an "issue"?  Let me know.

**Comment by jdeltoft** [comment]
entered a bug: https://github.com/flutter/flutter/issues/49794

**Pull request closed without merging**
