### PR TITLE
[framework] switch to default Map from HashMap

### PR DESCRIPTION
**Pull request by jonahwilliams**
We've seen several instances where the default hash map (LinkedHashMap) has better performance than HashMap.

* LinkedHashMap.of has a fast path for copying objects that HashMap.of does not. because of the different internal representations it would be difficult to port this to HashMap. https://github.com/dart-lang/sdk/issues/47856
* On the web, LinkedHashMap can use a JS object if the keys are primitive types. This can be signifiicantly faster in some cases.

Beyond those reasons, the LinkedHashMap is the default, and generally we should try and stick with defautls unless we have a good reason too. While we don't need the ordering property of the linked map, the documented reason of using hashmap for better performance is also not proven or observable. Therefore, I believe it is a reasonable choice to revert back to the default.

### CODE REVIEW

**Review by dnfield — COMMENTED** [review]
This seems fine to me - have you run any benchmarks on this though?

**Comment by jonahwilliams** [comment]
nope :)

**Comment by gaaclarke** [comment]
At least in the instance of InheritedWidgets I tried switching to `Map` from `HashMap` and it regressed the `build_bench.dart` benchmark.  I don't recall the numbers off the top of my head but around -3%.  Stephen from the Dart team actually suggested it after I had tried it in the past and this confirmed to me that it was slower despite the thought that they'd be faster.

**Comment by jonahwilliams** [comment]
that is surprsing for sure, perhaps we shouldn't land this.

**Pull request closed without merging**
