### PR TITLE
Shard Travis job into three pieces

### PR DESCRIPTION
**Pull request by abarth**

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @yjbanov

**Comment by sethladd** [comment]
Nice!

**Comment by Hixie** [comment]
LGTM

**Comment by abarth** [comment]
Before: `Ran for 9 min 38 sec`
After: `Ran for 5 min 58 sec`

**Comment by abarth** [comment]
The long pole is generating the dartdocs.

**Pull request merged**
