### PR TITLE
Fix buggy formula for critically-damped springs

### LINKED ISSUE #109675: The calculation method for _CriticalSolution seems wrong
## Steps to Reproduce

1. I was reading the source code of Flutter and found a little mistake in spring_simulation.dart.
2. It is in line 185. When calculating the critical damping solution, I got a different result. 
3. My calculation steps are as follows: y = (c1 + c2 * t) * e ^(r * t) get: v = c2 * e^(r * t) + (c1 + c2 * t) * r * e ^ (r * t) .
4. When t = 0, get: y = c1, v = c2 + c1 * r, then c2 = v - c1 * r .
5. So I think this code should be: "final double c2 = velocity - (r * distance);" , but not "final double c2 = velocity / (r * distance );".
6. I calculated many times and tried to make sure every step of my calculation was right, always got this result.
7. Was this a mistake or am I wrong?
8. Thank you. 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

### PR DESCRIPTION
**Pull request by gnprice**
Fixes #109675.

This formula would produce an initial velocity quite different from the one specified as an argument.

To update the test, I computed the expected results separately by using the physical formula.

Happily, the framework by default never ends up actually exercising this code.  Of the four SpringDescription call sites within the framework, two are explicitly overdamped; the other two are by design critically damped, but due to rounding they end up being treated as (very slightly) overdamped too.  Details here:
  https://github.com/flutter/flutter/issues/109675#issuecomment-1423674855

So the only way an app could be affected by this bug is if it called a SpringDescription constructor itself, and managed to create a spring description where the distinguishing formula in _SpringSolution comes out exactly equal to zero.  It's likely nobody has ever shipped such an app, because the behavior this produces would be so wildly wrong that it'd be hard to miss when exercised.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Piinks** [comment]
I agree with your (very detailed) assessment of this and the potential impact! I am running this through some extra testing up front as well.

**Review by Piinks — APPROVED** [review]
Thanks for your patience while I ran this through additional testing! LGTM!

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by gnprice** [comment]
Thanks for the testing and reviews!

I see the "Google testing" check is pending. I'll rebase in hopes of unwedging that.

**Pull request merged**
