### PR TITLE
Reland "Add DataTableTheme to allow for themable DataTables (#64316)"

### LINKED ISSUE #56079: DataTable should incorporate Theming
Following up on these two To-Dos:

https://github.com/flutter/flutter/blob/368da5bb5962db7be40439f416bd12176e2b3abf/packages/flutter/lib/src/material/data_table.dart#L546

https://github.com/flutter/flutter/blob/368da5bb5962db7be40439f416bd12176e2b3abf/packages/flutter/lib/src/material/data_table.dart#L599

By default the table's colors and text styles should be configured in terms of the Theme's colorScheme and textTheme. There shouldn't be brightness-specific code here or hardwired colors, etc. Additionally, there should be a DataTableTheme, so that one can configure the appearance of tables in general.

### PR DESCRIPTION
**Pull request by perclasson**
## Relanding #64316

Reland "Add DataTableTheme to allow for themable DataTables (#64316)"

Reverted in #65382 due to the DataTable not being rendered inside of an AlertDialog. This was due to the added Ink widget thats wrapping the Table. I removed this Ink widget for the DataTable and removed the decoration parameter for the DataTableTheme.

## Description

This PR adds a new DataTableTheme class to allow for themable DataTables across an application.

It also aligns the data table with Material specs by:
- To allow for a border around the table, without having a double border at the bottom, we do not set the border at the bottom of the `DataTable` by default (use `DataTable.showBottomDivider` to still have it).
- Change heading text to be `subtitle2` by default.
- Change cell text to be `bodyText2` by default.
- Let sort icon color be defined by any theme set instead of hard coding it to a black and white color.

## Screenshots
| PaginatedDataTable before | PaginatedDataTable after |
| :---: | :---: |
|  |  |
|  |  |

## Related Issues

Closes https://github.com/flutter/flutter/issues/56079

Follow up issues:

- Make sure the selected color follows Material spec guidelines, and that tristate icon is correct: https://github.com/flutter/flutter/issues/64314
- Add theming class for `PaginatedDataTable` (will create new issue when more information has been gathered on what is needed)

## Tests

I added the following tests:

- DataTable set show bottom divider
- DataTableThemeData copyWith, ==, hashCode basics
- DataTableThemeData defaults
- Default DataTableThemeData debugFillProperties
- DataTableThemeData implements debugFillProperties
- DataTable is themeable
- DataTable properties are taken over the theme values

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by rami-a — APPROVED** [review]
LGTM

**Review by clocksmith — APPROVED** [review]

**Review by JoseAlba — APPROVED** [review]
```
██╗      ██████╗ ████████╗███╗   ███╗
██║     ██╔════╝ ╚══██╔══╝████╗ ████║
██║     ██║  ███╗   ██║   ██╔████╔██║
██║     ██║   ██║   ██║   ██║╚██╔╝██║
███████╗╚██████╔╝   ██║   ██║ ╚═╝ ██║
╚══════╝ ╚═════╝    ╚═╝   ╚═╝     ╚═╝
```

**Review by HansMuller — APPROVED** [review]
RSLGTM

Please open an issue about the missing decoration feature. We should try and restore that in the not-distant future.

**Comment by perclasson** [comment]
> RSLGTM
> 
> Please open an issue about the missing decoration feature. We should try and restore that in the not-distant future.

https://github.com/flutter/flutter/issues/65532 Done!

**Pull request merged**
