### PR TITLE
Make dartdoc warnings fatal (& cleanup of warnings)

### PR DESCRIPTION
**Pull request by goderbauer**
**Reviewers**: Please ignore the first commit, it is a copy of https://github.com/flutter/flutter/pull/62317 to make cirrus happy.

## Description

* Make all warnings (except for `unresolved doc reference`) fatal
* Fix all warnings except for `unresolved doc reference`
* Fix `unresolved doc references` in:
  * painting library
  * scheduler library
  * services library
  * flutter_test
  * flutter_localizations
  * flutter_driver
  * semantics

The following packages still have `unresolved doc references` that need cleaning up:

- [ ] material
- [ ] widgets
- [x] rendering (https://github.com/flutter/flutter/pull/62443)

## Related Issues

#31931

## Tests

I added the following tests:

* doc only change, no tests

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by justinmc — APPROVED** [review]
LGTM, thanks for doing all this clean up 👍

**Comment by tvolkert** [comment]
https://github.com/flutter/flutter/issues/31931

**Comment by goderbauer** [comment]
> #31931

Thanks! Added to PR description.

**Comment by tvolkert** [comment]
FYI, #62317 has landed, so you can rebase this now.

**Comment by goderbauer** [comment]
> FYI, #62317 has landed, so you can rebase this now.

Thanks. Already done :)

**Pull request merged**
