### PR TITLE
Create flutter_tools.dart to represent public tools API

### PR DESCRIPTION
**Pull request by tvolkert**

### CODE REVIEW

**Comment by tvolkert** [comment]
@mpcomplete @devoncarew

**Comment by mpcomplete** [comment]
LGTM

**Comment by Hixie** [comment]
The idea here is that people can either use the 'flutter' tool directly, or they can import flutter_tools are write to its API, this file being its API? (so right now, just the one function?)

**Comment by tvolkert** [comment]
@Hixie yeah, that's the idea.  I'm calling into this in Google's internal build toolchain

**Pull request merged**
