### PR TITLE
Draggable can be accepted when the data is null

### LINKED ISSUE #84816: DragTarget crash  if Draggable data field is not set, but data is not required.
### DragTarget crashes if Draggable data field is not set, but data is not required. 

image

Specifically the issue is in `didDrop` in `drag_target.dart` which asserts `data` is not null:
image

### Suggestion
Make `data` field required.

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes https://github.com/flutter/flutter/issues/84816

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Nice find! Thanks for the fix. I am running this through G testing, I think it will be fine, but just in case I want to be sure this won't break and get reverted.

**Comment by Piinks** [comment]
@xu-baolin can you update this PR with the latest from master? The Google testing shard had some issues, and I cannot see if the failures are legit here. Thanks!

**Comment by skia-gold** [comment]
Gold has detected about 38 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/97355

**Review by Piinks — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
