### PR TITLE
Generate a depfile for assets of a flutter_app.

### PR DESCRIPTION
**Pull request by pylaligand**

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by chinmaygarde** [comment]
Travis is mad though.

**Comment by pylaligand** [comment]
Yeah, should be fixed with my latest push.

**Comment by yjbanov** [comment]
This PR may have broken our Windows build: https://flutter-dashboard.appspot.com/build.html

**Comment by yjbanov** [comment]
@goderbauer - for Windows support.

**Comment by pylaligand** [comment]
Could be a flake, it does not look related to any of the files I modified: https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9kMzU2YjJkNzdhODYwMTM1ZWE1MzlhZjViZGExMjVlMmFiMGFmMzkxDAsSBFRhc2sYgICAgICA8AsM

```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:29)
#1      buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:222)

#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:170)

#3      buildApk (package:flutter_tools/src/commands/build_apk.dart:99)

#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:305)

#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:200)

#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:281)

#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:151)

#8      RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:196)

#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:121)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)

#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:261)

#12     CommandRunner.run. (package:args/command_runner.dart:109)
#13     Future.Future.sync (dart:async/future.dart:208)
#14     CommandRunner.run (package:args/command_runner.dart:109)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#16     run. (package:flutter_tools/executable.dart:140)

#17     AppContext._run (package:flutter_tools/src/base/context.dart:76)

#18     AppContext.runInZone. (package:flutter_tools/src/base/context.dart:66)
#19     _rootRun (dart:async/zone.dart:1150)
#20     _CustomZone.run (dart:async/zone.dart:1026)
#21     runZoned (dart:async/zone.dart:1503)
#22     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#23     run (package:flutter_tools/executable.dart:113)

#24     main (package:flutter_tools/executable.dart:66)

#25     main (file:///C:/Users/win2/.cocoon/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#26     _startIsolate. (dart:isolate-patch/isolate_patch.dart:259)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by goderbauer** [comment]
If I manually execute the task it all passes. I just updated the bot to the latest version and restarted it. Let's see if it's green on the next run.

**Comment by yjbanov** [comment]
It is green! Case closed.

**Pull request merged**
