### PR TITLE
Increase template Swift version from 4 to 5

### LINKED ISSUE #40400: Swift template is using Swift 4
A significant part of the argument for switching the default iOS template to Swift was that with Swift 5, newer iOS devices wouldn't have the size overhead of having all the Swift libraries bundled in an app.

However, our Swift template is currently using Swift version 4, which means that's actually not the case unless developers go in and manually change their project settings. Lots of people are going to have unnecessarily large new apps under the current settings.

We should make the language default for the app and plugin templates 5, not 4. This will require:
- Actually changing the value in the Xcode project templates
- Updating the Swift code in the templates to use Swift 5
- Making Xcode 10.3 the minimum supported version in flutter_tool (currently its 9)

### PR DESCRIPTION
**Pull request by jmagman**
## Description

Template SWIFT_VERSION from 4.0 to 5.0.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/40400.

## Tests

Updated xcode_test.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by jmagman** [comment]
Blocked by https://github.com/flutter/flutter/issues/39921.

**Comment by jmagman** [comment]
This needs to be split into two PRs - one to up the Xcode version (blocked on https://github.com/flutter/flutter/issues/39921) and another to increase the Swift version.

**Comment by jmagman** [comment]
I split this out from https://github.com/flutter/flutter/pull/42254.  That will need to be merged first.

**Review by dnfield — APPROVED** [review]
LGTM provided devicelab is ready - and if it is maybe I can reland some patches to enable bitcode?

/cc @digiter

**Comment by jmagman** [comment]
> LGTM provided devicelab is ready - and if it is maybe I can reland some patches to enable bitcode?
> 
> /cc @digiter

No, it's not ready, still blocked on https://github.com/flutter/flutter/issues/39921.  @digiter was estimating it would be done this week.  I wanted something to merge ready when the lab is go.

**Comment by digiter** [comment]
Mac machines in devicelab are using Xcode 11.0 now.

**Pull request merged**
