### PR TITLE
Grammatical mistake on pull request template

### PR DESCRIPTION
**Pull request by Abhishek01039**
I have added `-` in `Pull request template`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by Abhishek01039** [comment]
Hello @goderbauer 
can you please discuss this with hixie?
Thanks

**Comment by Abhishek01039** [comment]
@goderbauer 
Google testing is failing.

**Comment by goderbauer** [comment]
@Abhishek01039 Can you push an empty commit to the branch to re-trigger it? For some reasons, I can't restart it internally.

**Comment by Abhishek01039** [comment]
Now, all checks passed!
@goderbauer

**Comment by Abhishek01039** [comment]
Have you discussed this with Hixie?
RIght? @goderbauer

**Pull request merged**
