### PR TITLE
[Add2App Android] Fix the issue of Hotreload broken on latest Dev release with Android device

### PR DESCRIPTION
**Pull request by shihchanghsiungsonos**
## Description

In an Android Add2App scenario, doing a Hot reload causes exception fired and nothing can be done anymore.

fix the issue by initialized `trackWidgetCreationValue` to null.

## Related Issues

https://github.com/flutter/flutter/issues/56957

## Tests

I added the following tests:

Ran `../../bin/flutter analyze` and no issue found.

Tested with Huawei P30 and verified Hot Reload works.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jonahwilliams** [comment]
It would be better to default to `true` to match the tool behavior

**Comment by dannyvalentesonos** [comment]
> It would be better to default to `true` to match the tool behavior

Yeah I was wondering about that. But then what happens for a release build? Shouldn't that be off for Release?

**Comment by jonahwilliams** [comment]
The value of the flag is ignored for release/profile builds, its safe to always pass true unless you want to disable the feature for some reason

**Comment by dannyvalentesonos** [comment]
Perfect, good to know. We'll update.

**Review by jonahwilliams — APPROVED** [review]
LGTM

Thanks for fixing this and sorry for the trouble

**Pull request merged**
