### PR TITLE
Replace FLUTTER_MODULE_TYPE with WEB_MODULE in flutter_tools/

### PR DESCRIPTION
**Pull request by jwren**
This change is being staged to be in coordination with flutter/flutter-intellij#1213

@devoncarew @pq

### CODE REVIEW

**Comment by pq** [comment]
When the time is right, LGTM!

**Comment by devoncarew** [comment]
lgtm; let's wait to land this until M16 of the Flutter plugin has been out for a little bit.

**Comment by cbracken** [comment]
Unnecessary post- #11536

**Comment by devoncarew** [comment]
We may still need to land this one; this is for the template files, and the other was for the repo's iml files.

**Pull request closed without merging**
