### PR TITLE
Implement switch in build info

### PR DESCRIPTION
**Pull request by AbdeMohlbi**
replaced the remaining switch expression with switch statement in `packages\flutter_tools\lib\src\build_info.dart`

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by nate-thegrate — COMMENTED** [review]
A fellow fan of switch expressions 🥹

I ran into these while working on #136139, but ultimately decided against refactoring them, since I think they're quite a bit easier to read as switch statements.

But feel free to head over to [flutter.dev/go/dart-patterns](https://flutter.dev/go/dart-patterns) and share your opinion about switch expression readability!

**Comment by AbdeMohlbi** [comment]
> A fellow fan of switch expressions 🥹
> 
> I ran into these while working on #136139, but ultimately decided against refactoring them, since I think they're quite a bit easier to read as switch statements.
> 
> But feel free to head over to [flutter.dev/go/dart-patterns](https://flutter.dev/go/dart-patterns) and share your opinion about switch expression readability!

okay man i have been trying to make the tests work locally the entire the day , i don't see a reason why this test is failing , when i didn't touch the getSupportedProtocols inside the vmService wich is wierd ,so is it better to hold up on this one ?

**Comment by nate-thegrate** [comment]
Yeah, I made a response in [Discord](https://discord.com/channels/608014603317936148/1267771223941845074/1267869995946348616) and I'll go ahead and copy/paste here…

<br>

I believe the [Mac tool_integration_tests_3_5](https://github.com/flutter/flutter/pull/152548/checks?check_run_id=28096608083) failure is just a flake, it'd probably pass the next time any changes are pushed to the PR.

That being said, we might not want to land that pull request, for readability reasons.

**Comment by AbdeMohlbi** [comment]
> Yeah, I made a response in [Discord](https://discord.com/channels/608014603317936148/1267771223941845074/1267869995946348616) and I'll go ahead and copy/paste here…
> 
> 
> I believe the [Mac tool_integration_tests_3_5](https://github.com/flutter/flutter/pull/152548/checks?check_run_id=28096608083) failure is just a flake, it'd probably pass the next time any changes are pushed to the branch.
> 
> That being said, we might not want to land this PR, for readability reasons.

okay no problem then

**Pull request closed without merging**
