### PR TITLE
[versions] update to the latest sdk versions

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Update to more null-safety versions

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
rslgtm

**Review by christopherfujino — APPROVED** [review]
LGTM what could go wrong?

**Comment by christopherfujino** [comment]
> LGTM what could go wrong?

other than all the tool_tests failing...

**Comment by christopherfujino** [comment]
https://cirrus-ci.com/task/5116457497395200?command=main#L2139

```
ERR : Because test >=1.15.3 <1.16.0-nullsafety depends on test_api 0.2.18 and every version of flutter_driver from sdk depends on test_api 0.2.19-nullsafety, test >=1.15.3 <1.16.0-nullsafety is incompatible with flutter_driver from sdk.
    | So, because flutter_project depends on both flutter_driver any from sdk and test 1.15.3, version solving failed.
FINE: Exception type: SolveFailure
FINE: package:pub/src/solver/version_solver.dart 312:5   VersionSolver._resolveConflict
    | package:pub/src/solver/version_solver.dart 133:27  VersionSolver._propagate
    | package:pub/src/solver/version_solver.dart 97:11   VersionSolver.solve.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                         Future.catchError
    | package:pub/src/utils.dart 113:52                  captureErrors.wrappedCallback
    | package:stack_trace                                Chain.capture
    | package:pub/src/utils.dart 126:11                  captureErrors
    | package:pub/src/command_runner.dart 193:13         PubCommandRunner.runCommand
```

**Comment by christopherfujino** [comment]
Possibly https://github.com/flutter/flutter/issues/61687

**Pull request merged**
