### PR TITLE
Use sliver-based scrolling in more places

### PR DESCRIPTION
**Pull request by abarth**
In particular, we now use ListView in the about dialog.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

**Comment by Hixie** [comment]
This dramatically regressed complex_layout_scrol-related benchmarks.

**Comment by Hixie** [comment]
It also dramatically improved some other benchmarks.

**Comment by Hixie** [comment]
More complete report in https://github.com/flutter/flutter/issues/7937.

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
