### PR TITLE
modified gitignore resolving issue 39742

### LINKED ISSUE #39742: local.properties not in .gitignore
Create new flutter app.
There are two local.properties files:
```android/local.properties```
```.android/local.properties```

Both of these files contain references to local directories, but .gitignore lists only
**/android/local.properties
So file .android/local.properties is still put in source control.
It should also be in .gitignore, possibly with some other files from .android folder

```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.950], locale pl-PL)
    • Flutter version 1.7.8+hotfix.4 at C:\flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Grzegorz\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\Grzegorz\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[!] VS Code, 64-bit edition (version 1.34.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • SM J510FN • ae08ec9e • android-arm • Android 7.1.1 (API 25)
```

### PR DESCRIPTION
**Pull request by PushkaraSharma**
## Description

*Fixed the beginner issue with 39742 (bug number)*

Fixes #39742

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ X] I signed the [CLA].
- [ X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ X] I updated/added relevant documentation (doc comments with `///`).
- [ X] All existing and new tests are passing.
- [ X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by goderbauer** [comment]
My understanding of #39742 is that we need to change this in the `.gitignore` we generate during `flutter create`. Tagging "tool" because of that.

/cc @xster Do you know whether this android file should be ignored or not?

**Comment by jmagman** [comment]
@PushkaraSharma Thank you for this contribution!

The `.gitignore` you edited is for the Flutter SDK itself, which should never have any `.android` directories checked in.  The one that's plopped down into a new `flutter create -t module` app already has `.android` ignored:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/module/common/.gitignore.tmpl#L39-L40

Additionally, I don't think a `flutter create` app would ever create a `.android` directory, and likewise a `flutter create -t module` would not create an `android` directory. 

I would be surprised if https://github.com/flutter/flutter/issues/39742 is still happening on master.  It might be worth trying to reproduce instead with the purpose of closing the issue as already resolved.

**Comment by jmagman** [comment]
Additionally, you need to sign the CLA https://github.com/flutter/flutter/pull/57134#issuecomment-628127305.

**Comment by zanderso** [comment]
@PushkaraSharma Since this PR looks inactive, I'm going to close it, but feel free to re-open if you'd like to continue working on it.

**Pull request closed without merging**
