### PR TITLE
move INTERNET permission to debug/AndroidManifest.xml

### PR DESCRIPTION
**Pull request by lesnitsky**
This PR is related to #8421
This is not an "injection" at build time, but rather a separate manifest for debug builds

Let me know what you think

### CODE REVIEW

**Comment by lesnitsky** [comment]
I signed it!

**Comment by Hixie** [comment]
cc @matthew-carroll this seems relevant to your current work. Can you take a look and see if we should land this and/or adapt it to your current plans? Thanks!

**Comment by matthew-carroll** [comment]
I will land this change as soon as the updated project structure has been finalized.

**Comment by lesnitsky** [comment]
@matthew-carroll should I resolve conflict now or should I wait for mentioned project structure finalization?

**Comment by matthew-carroll** [comment]
You can wait.  I'll probably just make this change directly in the project structure change, but we'll see.

**Comment by tvolkert** [comment]
@matthew-carroll is this still relevant?

**Comment by matthew-carroll** [comment]
@tvolkert given the slowdown of add2app work, this is probably fine to merge in.

**Comment by tvolkert** [comment]
sgtm.  @lesnitsky, are you game to rebase and resolve conflicts?

**Comment by lesnitsky** [comment]
@tvolkert Sure thing! will do this tomorrow

**Review by tvolkert — APPROVED** [review]
Thanks!

**Comment by matthew-carroll** [comment]
@Hixie who is "you" - a framework developer or app developer?  An app developer should continue to edit only a single AndroidManifest.xml...unless I've missed something.

**Comment by Hixie** [comment]
An App developer. Say I want to add a camera permissions to my app for use with the image picker plugin. Do I need to update just one file, or three files, if I want it to work in debug, profile, and release modes?

**Comment by dnfield** [comment]
If you add it to the main `AndroidManifest.xml`, you should be all set for all build types.

The debug one gets merged in to the main one for debug builds.

**Comment by lesnitsky** [comment]
@dnfield why this was reverted?

**Comment by dnfield** [comment]
That's a github bug - I didn't acutally revert it.  I reverted a different commit through the web UI workflow, and this one mistakenly got referenced .  If you check the source tree your changes are still in there.

**Comment by lesnitsky** [comment]
Oh, got it, thanks

**Pull request merged**
