### PR TITLE
Roll Dart to 45f9462398ae7d2e80acd79d3f9c32c7ca6f6f97

### LINKED ISSUE #34596: [Material] Update the slider gallery demo with range slider examples

### PR DESCRIPTION
**Pull request by aartbik**
Included in this long roll:

45f9462398 Revert "[build] Debug means debug!"
9f7ad8d082 Fix recovery when parsing complex type variables
dcb665fa6d [hhh] Apply patch to flutter engine to fix hhh buildbot build step.
781ea1be70 [vm/interpreter] Fix interpreter frame recognition in stack walking, v2
c70666a3a3 Additional tests in the analyzer_plugin optype_test.dart file, follow up from https://dart-review.googlesource.com/c/sdk/+/80362.
7a3762d4a9 Fixes for convert tests
3f9c3e6ebc Update unterminated string error message length
a502061c11 Add test and implementation for package: uris
70d5cf8578 [VM] Rehash constant tables after cid-renumbering during app-jit training
cfbb70aa1c [gardening] Mark various RawDatagramSocket/ tests as flaky
2b23fa0607 Improve the way we call inferExpression
e18aeac38c Remove NamedExpressionJudgment
b429939377 Remove CheckLibraryIsLoadedJudgment
f13537064e Remove ThrowJudgment
1bc9bbcdb6 Remove StaticInvocationJudgment
1610356382 Remove StaticGetJudgment
5aa705776b Remove desugaredError
a474f49ada Revert "[vm/interpreter] Fix interpreter frame recognition in stack walking"
e9b8e24891 [vm] Adds mutator thread asserts around bytecode reading
f0a116d339 [dart2js] Some tear-off cleanup
a0cc3e2684 [vm/interpreter] Fix interpreter frame recognition in stack walking
ef870b25e6 Dont complain about TypeImpl in switch cases
531d8235eb Initial documentation for the public API
bff11184fe dart2js co19_2 status bingo
fdca304de5 Safari status bingo
ac2036d76b Firefox status bingo
c0c3fc4c5f [dartdevc] fix #34596, hot restart can now clear field & cache state
54690c0d38 Update dartdoc to 0.24.1.
5f4511a30e Stop adding tokens to unit API signature at EOF.
2a63500865 [infra] Add flutter-analyze builder to the test matrix (#34739)
f51ccbc010 bump to linter 0.1.70
91b5862c1e [vm] Add core-jit-all snapshot kind to gen_snapshot
0f32be21bf Document single root flag
a4a3f95748 Avoid using future closure in http connect.
8f4e379665 update kernel worker to enable sync-async
bb93696c96 Simplify canParse on LSP types to only check for required fields
36551624e1 Implement fromJson() constructors for LSP types
4585b8eb44 [gardening] Mark RawDatagramSocket/any_A01_t02 co19 test flaky
d04a36b4ab [infra] Fix third_party/pkg_tested step having slash in name.
1061c83779 Optionally report scanner errors via errors list rather than in the token stream
fed5bc62b6 [co19] DEPS and .status files updated
b27e4febaf Eliminate an unnecessary boolean variable
a29c04953e Automatically run analysis server from source if launched with the SDK source tree
d07f3edd5e [vm] Disable symbolization of Dart frames in Dart_DumpNativeStackTrace.
3039fb0031 Sort LSP files
0aa2dc6ead Batch 'inherit'
2bb4284c63 Add a few more tests and comments for GnWorkspace
5dfe3c8f94 bump to linter 0.1.69
1ca91cb6db Ensure unterminated string error is reported on visible characters
ce1eac3800 Adapt analyzer/FE comparison logic to handle mixins with >2 superclass constraints.
cc750ecec1 Revert "Don't clone constant ASTs when running with Analysis Driver."
c7bc970ba7 [vm/simdbc] Clean up slot for result in InlineCacheMiss
d5e5842971 [vm/interpreter] Fix stack frame recording in native calls
5d4ce27bea [vm] Fix race between Dart::Cleanup and VerifyBootstrapClasses.
4506e1d179 add linter changes (#34817)
a53172cd47 [vm] Print isolate sticky_error during shutdown to let user know of unhandled exceptions.
22b4ec0e78 [vm/interpreter] Clean up slot for result in InlineCacheMiss
b10a36b8df [vm] Set WasCompiled at safepoint
27b3f0ba6b [vm/frontend] Allow 'package:'-scheme uris as sources for frontend_server compilation.
a3db8a904e Support running analyzer_cli in worker mode in an isolate.
3fc1f36e28 [vm] Update status files for issue 34760.
f337b254ce Support running dartdevc in worker mode in an isolate.
18f56e59cf [infra] Add configuration name to results.json
843b4c9c23 Refactoring to prepare for serialization
531bce152d Tune invariants for inferredTypesMap
822fd6a1ed Remove StringLiteralJudgment
cf84ce88d6 Remove StringConcatenationJudgment
f0ebf05092 Remove RethrowJudgment
83c6963ce2 Remove PropertyGetJudgment
2a9ba09b93 Allow abstract operator == methods in switch case constants
5d1832b20a Disallow factory constructors in mixin declarations.
055ce6f101 fix syntax error on android
130f57f7f3 missing include for android
ee975c89e2 [dart2js] Force --fast-startup holders to be fast objects
8fb17e0b6a Missing import for some linux builds
5c1a40837e Update analyzer fix sorting by priority
6e23c3b3cb Support SO_REUSEPORT and IP_MULTICAST_TTL for datagram sockets.
9a69a5c1ee Remove more unnecessary awaits (from analyzer)
5b574415f8 Fix GnWorkspace root
7f9049991b [ VM / Dart API ] Updated Dart_Invoke Dart_SetField tests to check error messages
2d397d1da6 Fix for dartbug.com/34821, variable_name_contributor.dart to complete "var SomeType |", to "someType" and "_someType", for declarations that can be denoted private.
0eb5dbffac [vm] Revert service isolate setup in main.cc
445a43b58d [ VM / Testing ] Add build flags to enable code coverage
6066ac83e3 Improve dartfix console output
da67d58110 Remove some unnecessary await expressions
f99d89b513 Update dartdoc to 0.24.0
93b1955ed0 Dartfix ui tweaks.
009eabf892 [Test tool] Add VM options to compiler arguments in VMKernelCompilerConfiguration
984c407bb3 [build] Debug means debug!
3a69805f6b Switch enums that don't have type aliases to stronger-typed values
56306b90ee Fix html changes markdown syntax:
f921f203f4 [vm/bytecode] Fix constant evaluation of factory constructors in bytecode
20f4349951 Fix for reporting INVALID_USE_OF_PROTECTED_MEMBER in documentation comments.
fade5f33f0 Regenerate code based on the server spec after updates to the generator
1996e78049 Update dart2js_info in DEPS to 0.5.13
df621a1fff Fix cast exception in TypeNameResolver (issue-34809)
f4ffb426c4 [Gardening] Mark flaky co19 tests and filed issue
4d5c5ecdbf Update synced version of pkg:test
8300248edb [VM] Ensure inferred types are set on parameters
5d78509e25 Make FieldElementImpl.isCovariant a public member on FieldElement
9ba152b69e Mark deprecated fields as such
de6f24367a Fix build from two incompatible changes landing
cfa92dc090 Remove NullJudgment
9fadaec5f8 Remove NotJudgment
e65ed1d143 Remove LogicalJudgment
0bcd98eb76 Remove FunctionExpressionJudgment
4df63225a8 Remove IsJudgment and IsNotJudgment
035aad457e Remove ConstructorInvocationJudgment
840afb4f9d Remove ConditionalJudgment
7fa8bc3fee Remove BoolJudgment
2495e2e951 [vm] Silence output from kernel::Program::ReadFromFile.
c0ec6299ad Extract enums from the spec
ea72ba3b1d Move sorting from reading to codegen
ab253a8a4e Review comments for "[vm/aot] Fix regressions from dynamic invocation forwarders in AOT."
801f28666a Remove ThisJudgment
af00f7c05d [vm/aot] Fix regressions from dynamic invocation forwarders in AOT.
349adc5b1f Reland "[VM] Use c++/kernel2kernel constant evaluator for const StaticInvocation in the kernel IR"
ed73cc379d Increase file descriptor limit when running test.py on MacOS
5ce132a912 [infra] Copy core dumps to ISOLATED_OUTDIR on shards (#34746)
a2aa6c8414 Consolidate DDC dependencies on front_end
9137fe26ac Remove deprecated_problems.dart
ed7be67cab Remove CompilerOptions.onProblem
18cb217840 Remove CompilerOptions.onError and CompilationMessage
2084c5b2a9 Add toJson() methods
d4fac1684c Remove CompilerOptions.reportMessages
c6b43d9cb6 Use ansi color in the dartfix cli output.
c8cf355c54 Bump package dart_internal's SDK constraint upper-bound to <2.2.0
2ed614819d [vm] Fix MakeUnusedSpaceTraversable in the 'Instance' filler case
c362e4862f [vm] Invalidate KernelProgramInfo caches on a reload
ac6d4f7e65 [vm] Disable conversion of large typed data to external when sending through a message port
dea6c97a08 [vm] A couple more benchmark for kernel loading
f3c51a4be0 Organize imports.
ae22eaa48b Remove unused import
abcb84ac78 Re-order the dartdoc param.
311a184cb8 Remove type merging and the only instance that used it
dd59921896 Support "{@link xxx}" in LSP spec
1f344e4ee0 Add support for "class" instead of interface
0a6d960d66 Update bazel_worker to onDiagnostic
e502edf28b Add DiagnosticMessage support API
88bde88112 Add constructors and mark all fields final
bf270577cc [fasta] Report errors on generic function types in type arguments
06f9a9e354 [VM] Introduce function and osr entrypoints to the VM's IR
22b11717ac [fasta] Fix bounds checking: non-generic types are always well-bounded
0a986f3f80 Remove a few shadow nodes.
490421d166 Fixed Service Workers and any Promise/Future API with a Dictionary parameter.
77c5677abe Don't clone constant ASTs when running with Analysis Driver.
1cabefdf5b Fix analyzer/FE comparison tool handling of mixins.
45092fd0aa Improve output of analyzer/FE comparison tool.
a4f3df6534 [vm] Fix symlinks in test cases.
180b3dd301 Remove extra spaces in copyright notices in analyzer_plugin
d127ab9a27 Get rid of places that allocate lots of _Closure instances.
5cff16bc75 Use single InheritanceManager2 instance for Linker.
d8e52e5e82 Remove last references to InheritanceManager in analyzer/server.
9f00eec55b [ VM / Mirrors ] Added type checking to enforce strong mode semantics when using dart:mirrors
2ec7c9cdb1 Skip the tests that require super mixin support
469e1e2e64 Remove unnecessary library directives
1d0d9f1d3f [vm] Fix heap corruption while reading "kernel list" file
80cddf0d53 Rename writeOverrideOfInheritedMember() to writeOverride() in DartEditBuilder.
2c352111a4 Use just TypeSystem in InheritanceManager2.
977f5c2c21 Switch KytheDartVisitor to InheritanceManager2.
bc2ea566f1 Auto generate more analyzer error codes
a2a3c36b77 Switch CREATE_MISSING_OVERRIDES to writeOverrideOfInheritedMember() and using FunctionType signatures.
aabc26bafe Revert "[VM] Use c++/kernel2kernel constant evaluator for const StaticInvocation in the kernel IR"
dac3e0d9df [dart2js] Don't create instance call-through stubs for statics
e34472db10 Remove unused import
22190e4d79 [vm] In IsolateMirror.loadUri, note that a kernel file at a URI may not contain any library with that URI.
dc9d6785de Report compile-time errors on invalid switch cases
af8d026337 Address dartfix comments and improve output
841a75698d [vm] Fix typo in previous commit
5b6220d44d [vm/compiler] Start of loop framework
0b1b09116a Simplify handling of non-shadow nodes in type inference
aa9f0f911f Update stream.dart
0e001641a9 Re-write invalid ASTs and update fix to reflect new AST structure for invalid type arguments on named constructors
48544cd77d Use InheritanceManager2 in InstanceMemberInferrer.
29ff9e4a6a [VM] Use c++/kernel2kernel constant evaluator for const StaticInvocation in the kernel IR
3199875231 Remove TypeSystemImpl.
0b78ac7f38 [VM] Add regression test for buildbot flakiness due to smi-widening optimization in VM
af7cead848 Clone default values of mixin application constructors
47c55605b8 Reland: [vm] Add a library and class cache to KernelProgramInfo
87a10d9811 Provide context for NotAType
69cf0ec97c Signal an error if a class extends a mixin
99815c8d6d Do not print --output_directory in reproduction commands
9b41728b2d Remove FileParseExceptionHandler from FileSystemState.
eee8787a8d Generate noSuchMethod forwarders for private members inherited from a class in a foreign library.
5b1fcb09df Remove d2fe ikg minimal benchmark from commit queue.
54ef78b7c5 Remove non-strong vm dill files from SDK
6177615d71 [kernel] Fix subtype relationship for generic function types
1f4dfce179 [gardening] Mark co19 LibTest/io/HttpServer/close_A05_t01 flaky
5cbb640f7c Error for type arguments after named constructor with implicit new
2fa1143600 Check classes at mixin applications
ade528c4e6 Fixed the type alias omission in the def. of simple bounds
ddf67772bb Remove warning about inferring packages URI from dart2js
18110717fe Move infer methods to visitor
bd223d0ec4 Add consistent_type_error_test
d95f63d752 Update dartfix to use new invalid type argument fix
0cdd5b9ff3 Raise warning to error: duplicate key in a const map is now an error in Dart.
f6ca2c1d8f Remove the Dart 1 tests.
9f98f5f44c Remove instantiateToBounds parameter from FunctionTypeImpl.relate.
82f31cd250 Add types to method args to avoid analysis warnings.
63c9a241e3 Upgrade WRONG_NUMBER_OF_TYPE_ARGUMENTS_CONSTRUCTOR from a warning to an error
5658d406b7 Add changelog entry for integer literals in double contexts.
6b67cd784b [vm] Make UBSAN happy for the code in Range::BitwiseOp
e4c3fa0a9c Improve recovery when parsing named constructor invocation with invalid type arguments
3e7ce992cf [vm/tfa] Implementation of type arguments tracking in TFA.
001343ce06 [vm, gc] Disable reads and writes to from-space after a scavenge.
97ffcd9a3d [vm] Disable incorrect widening of smis to int32
1a4933715e [gardening] Mark co19 LibTest/io/RawDatagramSocket/any_A03_t01 flaky
e4842a293b Remove extra spaces in headers
58c90dc488 [vm] Fix bytecode in core-jit for simarm64
fab5d0a50d In InheritanceManager remove unused, and deprecate used (in lints) methods.
2989116219 Add some special cases for types we can't/don't need to parse
49b121f20d Remove TypeParameterSerializationContext.location.
244e6c7ffc Infer package URIs
cc884b3449 Remove optional argument from FunctionTypeImpl.forTypedef.
931202df27 Improve wrapping of lists and *notes* in LSP spec comments
3e897ac3b1 [vm] Extend previous status file updates.
23e7f9d1eb Handle references to other classes in comments
472c898c87 [dartdevc] fix for-in loop variable shadowing a var used in initialzer
3fe3106489 [gardening] Fix leaks in run_vm_tests binary detected by ASAN.
a6c8b62056 Remove dummy .packages files
2f7e7a4b52 [vm] Update status files for vm-kernel-mac-product-x64 for issue 34760.
e12538fff0 Move package bundle functionality into SummaryBaseTestStrategy.
96737787e2 Add LSP spec code-gen output
5e7ea5b672 [infra] Add .vpython spec to fix gsutil on the bots (#31065)
3cf0008b13 [vm/bytecode] Remove dependencies on ASTs when running with bytecode
fc0decc262 Improvements to the Dart code generated from the LSP spec.
efcca1132b Switch ErrorVerifier and OverrideVerifier to InheritanceManager2.
c347850976 [gardening] Mark co19 LibTest/io/RawDatagramSocket/timeout_A06_t01 as flaky
5e1bf1d135 Create LibraryScope once per library analyzer.
7c7df7bfa4 Add initial version of feature specification on interface conflicts.
f2bffc6872 Revert "[infra] Upgrade gsutil to a new version (#31065)"
1809bae318 Revert "Ignore JSON exceptions when reading (empty) test results file"
787194e738 [infra] Upgrade gsutil to a new version (#31065)
265d0d9ec1 Update status files after 8648d782
23c36ed029 Elaborate that -0 means -0.0 in double context or when compiled to JS.
8648d782ae Reland "[fasta] Report errors for bounds violations"
5c9a8d8cb5 [VM] Add $target_gen_dir/gen_kernel_bytecode.dill.d to outputs of GN action, to ensure directory is created before action is run
49d7fb39ac Temporarily ignore --strong option in flutter builds
f0a30bc8d1 Revert "[vm] Add a library and class cache to KernelProgramInfo"
1c2ed4ac11 [infra] Include gsutil in vm-kernel fileset to enable coredumps on shards (#31065)
5b32ab3be6 Remove the word "strongMode" from some package:kernel libraries.
dfb8e97b86 Report errors on members hiding prefixes
235a918233 [vm] Remove Dart_LoadScript, Dart_LoadLibrary, Dart_LoadSource, etc.
90e362f63c Deprecate the last non-deprecated EMPTY_LIST
0ab8e42fea Use a special context for serializing generic function types.
c47879d354 Remove one-phase summary logic.
b9dd229e35 Convert element.dart to triple-slash comment style.
e70a7aab8a [VM] Dead code removal - Remove dead code around creation of service isolate in gen_snapshot.cc - Create service isolate from the core snapshot - exclude sources from platform dill file (saves about 2.5MB in size)
662ff7f112 [vm] Remove TokenStream, TokenValue, CompilerStats.
a933f42b9e [VM] Use Symbols::Empty() when there is no source for a script instead of creating new empty string objects. Change-Id: I8ec6702557b07c4c4ede2aece5a3f25b4cde1a5b Reviewed-on: https://dart-review.googlesource.com/c/79060 Reviewed-by: Ryan Macnak <rmacnak@google.com> Commit-Queue: Siva Annamalai <asiva@google.com>
72b31316e4 [observatory] Fail gracefully when a Script lacks source code.

### CODE REVIEW

**Review by aam — APPROVED** [review]
I don't think folks normally include description of flutter/engine commits on dart/engine into flutter rolls. Just a list of flutter engine commits(including dart roll one) would be sufficient.

**Comment by yjbanov** [comment]
Looks like Cirrus didn't run any pre-submit tests. Our post-submit tests are showing some major breakages: https://flutter-dashboard.appspot.com/build.html

**Comment by aartbik** [comment]
I noticed it too. Reverting.

**Comment by liyuqian** [comment]
The failure seems to be caused by missing engine artifacts. They should be resolved once engine build bots finished running for the corresponding engine commit.

Note: the engine auto-roller will wait for those artifacts to be compiled and then automatically roll the engine with the Dart roll. Therefore you don't have to do anything to have Dart or engine roll into the framework.

**Pull request merged**
