### PR TITLE
[iOS] Update template icons

### PR DESCRIPTION
**Pull request by RockerFlower**
Updates the AppIcon and LaunchImage assets in the iOS app template to meet Apple's icon guidelines as of iOS. Assets were moved to the [flutter_template_images][1] package, which includes them as of version 4.2.0.

Ref: https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons#specifications

Update the test on creating iOS templated icons

Validate that at least one of the iOS templated icons gets downloaded and put in the right spot.

Issue: #106110

[1]: https://github.com/flutter/packages/tree/main/packages/flutter_template_images

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by RockerFlower** [comment]
@jmagman Sorry to bother you again. 😅

This commit should be based on the latest repository, but the automated check still has errors.

```
Warning: one or more pubspecs have invalid dependencies. Please run "flutter update-packages --force-upgrade" to update them correctly.
```

I ran this command, and no files were changed.

```
$ flutter update-packages --force-upgrade

Upgrading packages...
WARNING: the following packages use hard-coded version constraints:
  - archive: 3.1.11
  - flutter_gallery_assets: 1.0.2
  - flutter_template_images: 4.0.0
  - shelf: 1.1.4
  - video_player: 2.2.11
Running "flutter pub upgrade" in flutter_update_packages.Nz9N8F...         4.9s
Ran pub get in dev/integration_tests/web in 0.5s...
Ran pub get in dev/tools/vitool in 0.8s...
Ran pub get in dev/integration_tests/web_compile_tests in 0.4s...
Ran pub get in dev/tools/gen_keycodes in 1.1s...
Ran pub get in dev/tools/gen_defaults in 1.1s...
Ran pub get in dev/tools in 1.2s...
Ran pub get in dev/integration_tests/ios_platform_view_tests in 1.2s...
Ran pub get in dev/integration_tests/deferred_components_test in 1.3s...
Ran pub get in dev/bots in 1.3s...
Ran pub get in dev/integration_tests/ui in 1.3s...
Ran pub get in dev/integration_tests/release_smoke_test in 0.7s...
Ran pub get in dev/integration_tests/android_views in 1.6s...
Ran pub get in dev/integration_tests/ios_app_with_extensions in 0.6s...
Ran pub get in dev/integration_tests/ios_add2app_life_cycle/flutterapp in 0.6s...
Ran pub get in dev/integration_tests/android_embedding_v2_smoke_test in 0.8s...
Ran pub get in dev/integration_tests/gradle_deprecated_settings in 0.6s...
Ran pub get in dev/integration_tests/non_nullable in 0.6s...
Ran pub get in dev/integration_tests/flavors in 1.1s...
Ran pub get in dev/integration_tests/abstract_method_smoke_test in 0.4s...
Ran pub get in dev/integration_tests/external_ui in 1.2s...
Ran pub get in dev/integration_tests/android_semantics_testing in 1.2s...
Ran pub get in dev/integration_tests/web_e2e_tests in 1.3s...
Ran pub get in dev/manual_tests in 0.6s...
Ran pub get in dev/integration_tests/platform_interaction in 1.1s...
Ran pub get in dev/integration_tests/hybrid_android_views in 1.3s...
Ran pub get in dev/forbidden_from_release_tests in 0.4s...
Ran pub get in dev/tracing_tests in 0.6s...
Ran pub get in dev/integration_tests/channels in 1.1s...
Ran pub get in dev/integration_tests/flutter_gallery in 1.7s...
Ran pub get in dev/customer_testing in 1.2s...
Ran pub get in dev/benchmarks/multiple_flutters/module in 1.0s...
Ran pub get in dev/devicelab in 1.5s...
Ran pub get in dev/benchmarks/complex_layout in 1.4s...
Ran pub get in dev/benchmarks/test_apps/stocks in 1.6s...
Ran pub get in examples/splash in 0.7s...
Ran pub get in dev/benchmarks/platform_views_layout_hybrid_composition in 1.6s...
Ran pub get in dev/benchmarks/platform_views_layout in 1.6s...
Ran pub get in dev/benchmarks/macrobenchmarks in 1.8s...
Ran pub get in dev/benchmarks/microbenchmarks in 1.7s...
Ran pub get in dev/benchmarks/platform_channels_benchmarks in 1.7s...
Ran pub get in examples/platform_view in 0.4s...
Ran pub get in dev/conductor/core in 1.4s...
Ran pub get in examples/flutter_view in 0.4s...
Ran pub get in dev/automated_tests in 1.5s...
Ran pub get in examples/layers in 0.7s...
Ran pub get in examples/image_list in 0.7s...
Ran pub get in packages/integration_test/integration_test_macos in 0.4s...
Ran pub get in examples/hello_world in 1.4s...
Ran pub get in packages/flutter_web_plugins in 0.7s...
Ran pub get in packages/integration_test in 0.7s...
Ran pub get in examples/platform_channel_swift in 1.3s...
Ran pub get in packages/flutter_goldens_client in 0.4s...
Ran pub get in examples/platform_channel in 1.2s...
Ran pub get in packages/flutter_goldens in 0.8s...
Ran pub get in packages/flutter_tools/test/data/asset_test/main in 0.2s...
Ran pub get in packages/flutter/test_private in 0.5s...
Ran pub get in packages/flutter_test/test/test_config/project_root in 0.1s...
Ran pub get in packages/flutter/test_private/test in 0.8s...
Ran pub get in examples/api in 1.3s...
Ran pub get in packages/integration_test/example in 1.3s...
Ran pub get in packages/flutter in 0.7s...
Ran pub get in packages/flutter_localizations in 0.5s...
Ran pub get in packages/flutter_test in 0.4s...
Ran pub get in packages/fuchsia_remote_debug_protocol in 0.7s...
Ran pub get in packages/flutter_driver in 0.7s...
Downloaded lcov data for package:flutter in 0.0s...
Ran pub get in packages/flutter_tools in 1.9s...
Running "flutter pub get" in affected packages...                   7.7s

Ran 'pub get' 66 times and fetched coverage data in 7.7s.
```

**Comment by jmagman** [comment]
A ha! This is caused by https://github.com/flutter/packages/pull/1951.  

This logic is checking if `package.packageUriRoot` directory exists, which in this case is the `flutter_template_images-4.2.0/lib` directory, which no longer exists.
https://github.com/flutter/flutter/blob/ed3c32c9d2c27b6259b7226063317d07b85f2134/packages/flutter_tools/lib/src/flutter_cache.dart#L101

Because it doesn't exist, on every run it thinks the pub dependencies are out of date, and `pub` needs to be run.

@stuartmorgan I see from that PR it says
> Removes the empty Dart file, which used to be required by pub.dev checks but no longer is.

I'm not sure what feature this is referencing, is the tool logic correct?

**Comment by jmagman** [comment]
Filed https://github.com/flutter/flutter/issues/107957 to track this.  Thanks for your patience, please hold 🙂

**Comment by stuartmorgan** [comment]
> > Removes the empty Dart file, which used to be required by pub.dev checks but no longer is.
> 
> I'm not sure what feature this is referencing

It used to be that if you tried to `pub publish` a package that didn't contain any Dart code, it would error out, so we had packages/plugins (like this one, which exists only to hold images) that had a dummy Dart file in lib/. That restriction was lifted at some point, so I've been cleaning up those dummy files as I find them.

> is the tool logic correct?

I'm not sure what that tool logic does exactly, but it shouldn't be assuming that *all* packages have `lib` directories.

**Comment by jmagman** [comment]
> I'm not sure what that tool logic does exactly, but it shouldn't be assuming that _all_ packages have `lib` directories.

This is the logic:
https://github.com/flutter/flutter/blob/ed3c32c9d2c27b6259b7226063317d07b85f2134/packages/flutter_tools/lib/src/flutter_cache.dart#L100-L104

`package.packageUriRoot` is `lib` in this case.
Screen Shot 2022-07-19 at 1 21 03 PM

Need some better way to check this then, I don't see anything else interesting in that package object.

**Comment by stuartmorgan** [comment]
Sorry, I meant I don't know what that logic is *for*. I.e., I don't know what "lib/ exists" is intended to be a proxy for, and thus what to replace it with. Is there a reason it's checking for something *in* the package, not the folder itself? Is there a reason it's not checking for `pubspec.yaml` instead, or was `lib/` arbitrary content?

**Comment by stuartmorgan** [comment]
> Sorry, I meant I don't know what that logic is _for_. I.e., I don't know what "lib/ exists" is intended to be a proxy for, and thus what to replace it with. Is there a reason it's checking for something _in_ the package, not the folder itself? Is there a reason it's not checking for `pubspec.yaml` instead, or was `lib/` arbitrary content? Someone who knows the answers to those questions should decide how to fix it :)

**Comment by jmagman** [comment]
> Someone who knows the answers to those questions should decide how to fix it :)

Yup, wasn't saying you should fix it, the tool team is already on it. Was just asking for more context since you knew more than I did about how these packages should be formatted. 🙂

**Comment by jmagman** [comment]
Thank you for your patience! Can you try rebasing/merging this on https://github.com/flutter/flutter/pull/107968? 
And did you want to track this work in https://github.com/flutter/flutter/pull/106111 or this PR?

**Comment by RockerFlower** [comment]
> Thank you for your patience! Can you try rebasing/merging this on #107968? And did you want to track this work in #106111 or this PR?

I seem to have made a mistake, so many commits..

**Comment by jmagman** [comment]
> I seem to have made a mistake, so many commits..

Looks correct now, you figured it out. 🙂

**Comment by RockerFlower** [comment]
> > I seem to have made a mistake, so many commits..
> 
> Looks correct now, you figured it out. 🙂

Oops, there are still errors.

**Comment by jmagman** [comment]
So `flutter update-packages --force-upgrade` will need to be run on your PR.  That command hasn't been run in a bit, and there are some updates it generates unrelated to your change.  I created https://github.com/flutter/flutter/pull/108178 which will run it on master, then you can rebase again when that lands.  Then you can run `flutter update-packages --force-upgrade` on your change, and the _only_ diff should be the `CHECKSUM` in `packages/flutter_tools/pubspec.yaml`:
```diff
-# PUBSPEC CHECKSUM: b869
+# PUBSPEC CHECKSUM: 5d6a
```
Apologies that you've hit so many rough edges helping us with this change.  Thanks again, we're almost there!

**Comment by RockerFlower** [comment]
> So `flutter update-packages --force-upgrade` will need to be run on your PR. That command hasn't been run in a bit, and there are some updates it generates unrelated to your change. I created #108178 which will run it on master, then you can rebase again when that lands. Then you can run `flutter update-packages --force-upgrade` on your change, and the _only_ diff should be the `CHECKSUM` in `packages/flutter_tools/pubspec.yaml`:
> 
> ```diff
> -# PUBSPEC CHECKSUM: b869
> +# PUBSPEC CHECKSUM: 5d6a
> ```
> 
> Apologies that you've hit so many rough edges helping us with this change. Thanks again, we're almost there!

I'm delighted to contribute to Flutter!

Do I need to wait for https://github.com/flutter/flutter/pull/108198 to be merged?

**Comment by jmagman** [comment]
> Do I need to wait for https://github.com/flutter/flutter/pull/108198 to be merged?

Yes, once it's in master then merge or rebase to get that change.

**Comment by jmagman** [comment]
> Do I need to wait for https://github.com/flutter/flutter/pull/108198 to be merged?

It's merged.

**Comment by RockerFlower** [comment]
The strange thing is that after I run `flutter update-packages --force-upgrade`, nothing changes.

**Comment by jmagman** [comment]
Looks like it's passing now, marking ready for review.

**Comment by RockerFlower** [comment]
> Looks like it's passing now, marking ready for review.

CHECKSUM was changed manually by me because I ran the command without effect.

**Review by jmagman — APPROVED** [review]
LGTM, thanks again for the contribution!
Adding @christopherfujino for the second review.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by RockerFlower** [comment]
> CHECKSUM was changed manually by me because I ran the command without effect.

@jmagman When I updated my own copy of flutter, I became aware of this: by running `flutter update-packages —force-upgrade`, I was updating the flutter code that I set the path to, so the copy I cloned did not change. 🤦‍♂️

**Comment by jmagman** [comment]
> > CHECKSUM was changed manually by me because I ran the command without effect.
> 
> @jmagman When I updated my own copy of flutter, I became aware of this: by running `flutter update-packages —force-upgrade`, I was updating the flutter code that I set the path to, so the copy I cloned did not change. 🤦‍♂️

That would do it!

**Pull request merged**
