### PR TITLE
Add `heightIsNull` param for `TextStyle.copyWith`

### PR DESCRIPTION
**Pull request by daohoangson**
## Description

Currently `TextStyle.copyWith` cannot reset the height value back to null. The `height=null` behavior is quite different since https://github.com/flutter/engine/pull/9041/ and cannot be reproduced with any other value (`height=null` will render differently from `height=1.0`). This PR add a new param to reset the height value if needed.

## Related Issues

#58765

## Tests

I updated the following tests:

- packages/flutter/test/painting/text_style_test.dart

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by goderbauer** [comment]
`heightIsNull` feels a little ugly.

/cc @GaryQian 
/cc @HansMuller, who has recently thought a lot about null values and Themes.

**Comment by HansMuller** [comment]
@daohoangson - None of Flutter's copyWith() methods support resetting a property to null. Although it's a reasonable thing to want to do, it doesn't come up that often and so we haven't created a standard way to do it. Adding a `fooIsNull` flag for each property in every copyWith() method doesn't really make sense without a big demand for it, and adding a one-off flag like `heightIsNull` to the TextStyle copyWith method establishes a precedent for a pattern we don't plan to follow.

Appreciate the idea, but I don't think we're going to land this one.

**Comment by GaryQian** [comment]
Going off of what Hans said, for edge cases like this, you should be able to roll an implentation specific solution that does this for your app. In the case for height, the inability to reset to null is a bit more serious than other properties, but not serious enough to warrant a new standard API that may cause additional confusion for the majority of users who won't use the feature. Theoretically, we could provide explicit API to accomplish every single small thing that could possibly be done, but realistically, we must choose the most important subset that are the most useful to keep the API parsable, learnable, and understandable. A local custom solution should be straightforwards in this case.

**Comment by daohoangson** [comment]
Thank you @HansMuller and @GaryQian for the reasonable feedback, adding a new weirdly-named param doesn't seem to be a great idea. I'm closing this MR now.

**Pull request closed without merging**
