### PR TITLE
Introduce `Split` curve

### LINKED ISSUE #51627: Look into making _BottomSheetSuspendedCurve public
This curve is used with bottom sheets to allow linear finger dragging and non-linear enter/exit animations.

- Look into making this public
- Adding useful examples
- Find instances where it would be useful, not just for bottom sheets, and retrofit existing code

The PR that adds this curve: #51122

### PR DESCRIPTION
**Pull request by guidezpl**
`Split` is a curve that progresses according to `beginCurve` until `split`, then according to `endCurve`.

This curve is used with bottom sheets to allow linear finger dragging and non-linear enter/exit animations. This PR cleans up a previously private class I introduced and replaces it with the more customisable `Split`.

Fixes https://github.com/flutter/flutter/issues/51627

Diagram to be added with https://github.com/flutter/assets-for-api-docs/pull/239

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by guidezpl** [comment]
In google3, there are only 2 instances of an existing `Split` class, both in third_party:
1. In the DevTools app
2. In a codelab example

So I'm leaning towards keeping this simple name, which matches the naming convention of all other curves.

**Comment by guidezpl** [comment]
In google3, there are only 2 instances of an existing `Split` class, both in third_party:
1. In the DevTools app
2. In a codelab example

So I'm leaning towards keeping this simple name, which matches the naming convention of all other curves.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Thanks, looks useful.

**Comment by gspencergoog** [comment]
Sorry, reviewed prematurely: I didn't realize this was still in Draft mode.  Did you have more to add here?

**Comment by guidezpl** [comment]
> Sorry, reviewed prematurely: I didn't realize this was still in Draft mode. Did you have more to add here?

Thanks! No, I will just have it drafted until I update conflicting class names elsewhere.

**Pull request merged**
