### PR TITLE
Revert "Revert "Reland: Migrate examples to the Android embedding v2""

### PR DESCRIPTION
**Pull request by blasten**
Reverts flutter/flutter#43885

### CODE REVIEW

**Review by godofredoc — APPROVED** [review]

**Comment by blasten** [comment]
Merging on red to debug the test while it's running.

**Comment by xster** [comment]
Seems like flutter_gallery__back_button_memory diff-median is up to 4747kb from 4390kb previously. But that's mostly consistent with @matthew-carroll testing locally and expected since both the embedding and plugin code (which the gallery exercises) are new.

Edit: oh, the benchmarks are back in range again. Looks like we're ok.

**Comment by matthew-carroll** [comment]
@blasten were you able to debug the future completion issue?

**Comment by xster** [comment]
it just passed on the device lab this time for some reason

**Comment by matthew-carroll** [comment]
Interesting. Do we take that as a green light? Or should someone force another round or two of device lab runs?

**Comment by xster** [comment]
Actually, it looks like the tests have gotten flaky since this PR.

**Comment by godofredoc** [comment]
I got a repro on mac-20 output but can not find any error from logcat. The test is blocked after the following lines:
```
2019-10-31T21:40:08.131770: INFO [task runner] [platform_view__start_up] stdout: [        ] Notification from VM: {streamId: Extension, event: {type: Event, kind: Extension, extensionKind: Flutter.Navigation, isolate: {type: @Isolate, id: isolates/1560588269629051, name: main, number: 1560588269629051}, timestamp: 1572583208088, extensionData: {route: {description: MaterialPageRoute<dynamic>(/), settings: {name: /, isInitialRoute: true}}}}}

2019-10-31T21:40:08.525553: INFO [task runner] [platform_view__start_up] stdout: [ +393 ms] I/Choreographer( 7914): Skipped 34 frames!  The application may be doing too much work on its main thread.

2019-10-31T21:40:08.527251: INFO [task runner] [platform_view__start_up] stdout: [   +1 ms] W/FlutterView( 7914): Tried to send viewport metrics from Android to Flutter but this FlutterView was not attached to a FlutterEngine.
```

**Comment by xster** [comment]
Do we adb screenshot at the moment of the failure in the devicelab?

**Comment by xster** [comment]
@matthew-carroll is there an elevated logcat mode we can turn on for the devicelab tests?

**Comment by matthew-carroll** [comment]
In any test apps desired, we can statically elevate the level of logs that are shown from the io.flutter.Log:
https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/Log.java#L24

**Comment by xster** [comment]
Does it read from env var or any source that doesn't need rebuilding a local engine?

**Comment by matthew-carroll** [comment]
No support for an env variable, but you don't need to rebuild the engine, you just need to rebuild the app that uses the embedding. You can call that static method from MainActivity in your app, or from the Application class.

**Comment by xster** [comment]
ah right. Could we try that locally on one of the device lab hosts tomorrow @godofredoc @blasten?

**Pull request merged**
