### PR TITLE
Extract kernel compile from buildAotSnapshot

### PR DESCRIPTION
**Pull request by cbracken**
Moves the kernel compile step to the beginning of the AOT build in a
separate method. This is pre-factoring for iOS universal builds where
the kernel build happens once, but we then snapshot twice: once for
armv7 and once for arm64.

This also writes dependencies to build/kernel_compile.d rather than
build/aot/snapshot.d, since that is immediately overwritten by
gen_snapshot.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @aam @tvolkert

**Comment by cbracken** [comment]
Related #2089

**Review by tvolkert — APPROVED** [review]
LGTM

**Comment by tvolkert** [comment]
```
The class '_FakeKernelCompiler' isn't used. (packages/flutter_tools/test/base/build_test.dart, line 73, col 7)
```

**Comment by cbracken** [comment]
Done.

**Pull request merged**
