### PR TITLE
Revert "Fix jumping when doing long press for selecting text"

### PR DESCRIPTION
**Pull request by CaseyHillers**
Reverts flutter/flutter#102270

This broke internal google tests

Googlers, see b/230165332

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
Is there a minimal reproduction of the failing test that we can include in flutter/flutter CI?

**Comment by zanderso** [comment]
The internal issue is closed, noting that the changes are acceptable, so I don't understand why a revert is needed.

**Comment by CaseyHillers** [comment]
I've added more context to the internal bug. I defer to @LongCatIsLooong and @chunhtai but I suspect we could send a g3fix since this was a single test failing.

**Comment by rgevrek** [comment]
Hi @CaseyHillers 
Why we have to revert the fix. With the bug, we are not able to use a selectable RichText which has a size taller than the screen size?

**Comment by CaseyHillers** [comment]
@rgevrek please coordinate the reland with @LongCatIsLooong and @chunhtai. The internal test failed as it has a hard coded assumption that inactive cursors allow jumping to. This is a test issue that should be fixed, and I don't see anything wrong with this PR.

**Pull request merged**
