### PR TITLE
Make BoxDecoration lerp gradients

### PR DESCRIPTION
**Pull request by Hixie**
This still is very limited in what it can lerp, but it sets the stage for arbitrary lerps later.

cc @abarth

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
I made the following changes to fix the tests:

```diff
diff --git a/packages/flutter/lib/src/painting/box_decoration.dart b/packages/flutter/lib/src/painting/box_decoration.dart
index 916d838..5087bbf 100644
--- a/packages/flutter/lib/src/painting/box_decoration.dart
+++ b/packages/flutter/lib/src/painting/box_decoration.dart
@@ -154,7 +154,7 @@ class BoxDecoration extends Decoration {
       border: BoxBorder.lerp(null, border, factor),
       borderRadius: BorderRadius.lerp(null, borderRadius, factor),
       boxShadow: BoxShadow.lerpList(null, boxShadow, factor),
-      gradient: gradient.scale(factor),
+      gradient: gradient?.scale(factor),
       shape: shape,
     );
   }
@@ -183,6 +183,11 @@ class BoxDecoration extends Decoration {
   /// The [shape] is not interpolated. To interpolate the shape, consider using
   /// a [ShapeDecoration] with different border shapes.
   ///
+  /// At `t=0.0`, this returns `a` unmodified, and at `t=1.0`, this returns `b`
+  /// unmodified; in both cases, this may result in null being returned. If both
+  /// are null, then null is returned for all `t`. In all other cases, the
+  /// result is non-null.
+  ///
   /// See also:
   ///
   ///  * [Decoration.lerp], which can interpolate between any two types of
@@ -191,6 +196,10 @@ class BoxDecoration extends Decoration {
   ///     and which use [BoxDecoration.lerp] when interpolating two
   ///    [BoxDecoration]s or a [BoxDecoration] to or from null.
   static BoxDecoration lerp(BoxDecoration a, BoxDecoration b, double t) {
+    if (t == 0.0)
+      return a;
+    if (t == 1.0)
+      return b;
     if (a == null && b == null)
       return null;
     if (a == null)
diff --git a/packages/flutter/lib/src/painting/decoration.dart b/packages/flutter/lib/src/painting/decoration.dart
index 3595f0c..120d2ef 100644
--- a/packages/flutter/lib/src/painting/decoration.dart
+++ b/packages/flutter/lib/src/painting/decoration.dart
@@ -99,7 +99,16 @@ abstract class Decoration extends Diagnosticable {
   /// null or if its [lerpTo] returns null, it uses `begin`'s [lerpFrom]
   /// function instead. If both return null, it attempts to lerp from `begin` to
   /// null if `t<0.5`, or null to `end` if `t≥0.5`.
+  ///
+  /// At `t=0.0`, this returns `begin` unmodified, and at `t=1.0`, this returns
+  /// `end` unmodified; in both cases, this may result in null being returned.
+  /// If both are null, then null is returned for all `t`. In all other cases,
+  /// the result is non-null.
   static Decoration lerp(Decoration begin, Decoration end, double t) {
+    if (t == 0.0)
+      return begin;
+    if (t == 1.0)
+      return end;
     Decoration result;
     if (end != null)
       result = end.lerpFrom(begin, t);
diff --git a/packages/flutter/lib/src/painting/flutter_logo.dart b/packages/flutter/lib/src/painting/flutter_logo.dart
index a058d62..3e77de7 100644
--- a/packages/flutter/lib/src/painting/flutter_logo.dart
+++ b/packages/flutter/lib/src/painting/flutter_logo.dart
@@ -123,10 +123,19 @@ class FlutterLogoDecoration extends Decoration {
   ///
   /// Interpolates both the color and the style in a continuous fashion.
   ///
+  /// At `t=0.0`, this returns `a` unmodified, and at `t=1.0`, this returns `b`
+  /// unmodified; in both cases, this may result in null being returned. If both
+  /// are null, then null is returned for all `t`. In all other cases, the
+  /// result is non-null.
+  ///
   /// See also [Decoration.lerp].
   static FlutterLogoDecoration lerp(FlutterLogoDecoration a, FlutterLogoDecoration b, double t) {
     assert(a == null || a.debugAssertIsValid());
     assert(b == null || b.debugAssertIsValid());
+    if (t == 0.0)
+      return a;
+    if (t == 1.0)
+      return b;
     if (a == null && b == null)
       return null;
     if (a == null) {
diff --git a/packages/flutter/test/painting/decoration_test.dart b/packages/flutter/test/painting/decoration_test.dart
index 96c8af5..9d39ead 100644
--- a/packages/flutter/test/painting/decoration_test.dart
+++ b/packages/flutter/test/painting/decoration_test.dart
@@ -282,15 +282,14 @@ void main() {
   });

   test('BoxDecoration.lerp - gradients', () {
-    // We don't lerp the gradients, we just switch from one to the other at t=0.5.
-    final Gradient gradient = new LinearGradient(colors: <Color>[ const Color(0x00000000), const Color(0xFFFFFFFF) ]);
+    final Gradient gradient = new LinearGradient(colors: const <Color>[ const Color(0x00000000), const Color(0xFFFFFFFF) ]);
     expect(
       BoxDecoration.lerp(
         const BoxDecoration(),
         new BoxDecoration(gradient: gradient),
         -1.0,
       ),
-      const BoxDecoration()
+      const BoxDecoration(gradient: const LinearGradient(colors: const <Color>[ const Color(0x00000000), const Color(0x00FFFFFF) ]))
     );
     expect(
       BoxDecoration.lerp(
@@ -306,7 +305,7 @@ void main() {
         new BoxDecoration(gradient: gradient),
         0.25,
       ),
-      const BoxDecoration()
+      const BoxDecoration(gradient: const LinearGradient(colors: const <Color>[ const Color(0x00000000), const Color(0x40FFFFFF) ]))
     );
     expect(
       BoxDecoration.lerp(
@@ -314,7 +313,7 @@ void main() {
         new BoxDecoration(gradient: gradient),
         0.75,
       ),
-      new BoxDecoration(gradient: gradient)
+      const BoxDecoration(gradient: const LinearGradient(colors: const <Color>[ const Color(0x00000000), const Color(0xBFFFFFFF) ]))
     );
     expect(
       BoxDecoration.lerp(
```

Specifically, my reasoning for the Decoration.lerp, BoxDecoration.lerp, and FlutterLogoDecoration.lerp changes was that these objects are really heavy to lerp, so in the common cases of 0.0 and 1.0 we should have a fast path.

Also, see https://github.com/flutter/flutter/issues/12377 regarding `a`/`b` vs `begin`/`end`.

**Comment by Hixie** [comment]
Assuming this fixes the tests, will land on green.

**Comment by abarth** [comment]
For null a and 0.0, don't we normally return whatever "zero" we inflate null to (assuming b is non-null)?  It seems odd for these lerp to be different in that regard.

**Comment by abarth** [comment]
Put it this way, I think what you've got here has a discontinuity at 0.0 (and, symmetrically, at 1.0) in the part-null case, which isn't ideal for a linear interpolation.

**Comment by Hixie** [comment]
How do you feel about the non-null case? The case that brought this up for me is this:

```dart
    final Gradient gradient = new LinearGradient(colors: const <Color>[ const Color(0x00000000), const Color(0xFFFFFFFF) ]);
    expect(
      BoxDecoration.lerp(
        const BoxDecoration(),
        new BoxDecoration(gradient: gradient),
        -1.0,
      ),
      const BoxDecoration(gradient: const LinearGradient(colors: const <Color>[ const Color(0x00000000), const Color(0x00FFFFFF) ]))
    );
    expect(
      BoxDecoration.lerp(
        const BoxDecoration(),
        new BoxDecoration(gradient: gradient),
        0.0,
      ),
      const BoxDecoration()
    );
```

If I actually interpolate, then the second case will return the same as the first, where `lerp(a,b,0.0)` is not `a` (technically it doesn't even `== a`, though it will render the same thing). It seems bad to be doing all the work of computing the interpolation to return something that will eventually be identical to something we have already.

**Comment by abarth** [comment]
That seems fine given that the visual output is the same.  I guess you're saying that null has the same visual output as well?

**Comment by Hixie** [comment]
`gradient.scale(0.0)` is defined to render the same thing as null (per the comments added in this PR).

If you're ok with the non-null case, I don't feel strongly about the null case. I'd be fine with saying that the output of lerp should never be null unless the input is null/null.

**Comment by abarth** [comment]
> If you're ok with the non-null case

Yeah, that part seems fine.

> I'd be fine with saying that the output of lerp should never be null unless the input is null/null.

My guess is that will be less surprising for clients.

**Comment by Hixie** [comment]
Ok, changed the Decoration, BoxDecoration, and FlutterLogoDecoration lerp functions.

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
landing on "red" because redness is not real (cc @yjbanov, looks like we don't notice when appveyor has a subsequent updated run).

**Pull request merged**
