### PR TITLE
Add integration_test to integration tests build shard

### LINKED ISSUE #71758: integration_test_macos plugin does not build
## Steps to Reproduce
```
$ cd ./packages/integration_test/example/
$ flutter build macos
```
Fails
```
[!] The name of the given podspec `IntegrationTestMacOS` doesn't match the expected one `integration_test_macos`
```

`integration_test_macos.podspec` name should be `integration_test_macos` instead of `IntegrationTestMacOS`.

https://github.com/flutter/plugins/blob/89794a635a5efad6705e3d7ccc29e8139318d947/packages/integration_test/integration_test_macos/macos/integration_test_macos.podspec#L5

### PR DESCRIPTION
**Pull request by jmagman**
## Description

- Add integration_test example to integration tests build shard.
- Remove packages/integration_test/example/macos/ since `packages/integration_test` doesn't declare a macos implementation, and so doesn't build.
- Run the test and check in the iOS project file changes from various migrators.
- Fix iOS `VALID_ARCHS` -> `EXCLUDED_ARCHS`, see https://github.com/flutter/flutter/pull/64504
- Fix integration_test_macos.podspec name so it actually can build.
- Update styles.xml to make `flutter build apk` build 
- Remove `pod install` and let `build` handle it.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/71758

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
@dnfield The android integration_test example doesn't build.  Do you have an open issue for that? 
```
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:mergeDebugResources'.
[        ] > /b/s/w/ir/k/flutter/packages/integration_test/example/android/app/src/main/res/values/styles.xml:5:6: Error: The processing instruction target matching "[xX][mM][lL]" is not allowed.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1m 12s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 15 actionable tasks: 14 executed, 1 up-to-date
[ +399 ms] Running Gradle task 'assembleDebug'... (completed in 73.2s)
[   +4 ms] "flutter apk" took 75,173ms.
[   +3 ms] Gradle task assembleDebug failed with exit code 1
```

**Comment by dnfield** [comment]
That seems strange - we should file a bug, if you want to just skip it for this PR we can leave it as a TODO

**Comment by jmagman** [comment]
> That seems strange - we should file a bug, if you want to just skip it for this PR we can leave it as a TODO

I think I figured it out.

**Review by stuartmorgan-g — APPROVED** [review]
Removal of macOS LGTM. At some point we can add a real implementation (which we probably won't federate), and the placeholder version isn't actually necessary (even if building)

**Pull request merged**
