### PR TITLE
Remove measureIosCpuGpu

### PR DESCRIPTION
**Pull request by liyuqian**
This function is no longer used.

### CODE REVIEW

**Comment by TheBiirb** [comment]
Look like you forgot to delete the _execAndCheck method. This one:
```
Future<void> _execAndCheck(String executable, List<String> args) async {
  _checkExitCode(await exec(executable, args));
}
```

**Comment by liyuqian** [comment]
> Looks like you forgot to delete _execAndCheck and _checkExitCode methods since they are not used anymore 😄 .

Oh yes, thank you!

**Comment by liyuqian** [comment]
Ping @iskakaushik @gaaclarke @flar ...

**Review by iskakaushik — APPROVED** [review]
LGTM

**Review by flar — APPROVED** [review]
LGTM

**Pull request merged**
