### PR TITLE
Upgrade packages to pull a Dart 2 compliant mockito.

### LINKED ISSUE #14532: Flutter should be upgraded to Dart 2 compliant mockito
Current issue of mockito is 2.2.1 (latest stable release), however it is not fully Dart 2 compliant:

```console
compiler message: file:///usr/local/google/home/vegorov/.pub-cache/hosted/pub.dartlang.org/mockito-2.2.1/lib/src/mock.dart:680:32: Error: A value of type '(#lib1::_VerifyCall) → #lib1::Mock' can't be assigned to a variable of type '(dynamic) → dynamic'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to '(dynamic) → dynamic'.
compiler message:             tmpVerifyCalls.map((_VerifyCall vc) => vc.mock).toSet();
compiler message:
```

This makes tests using mockito fail when running in Dart 2 mode. 

This issue is to track an upgrade when it becomes available. Currently only unstable 3.0.0-alpha is available. 

Currently the only test in Flutter repository, I know about, that is using package mockito is `packages/flutter/test/material/animated_icons_test.dart`

/fyi @a-siva @srawlins

### PR DESCRIPTION
**Pull request by mraleph**
Fixes #14532

### CODE REVIEW

**Comment by xster** [comment]
LGTM

**Comment by mraleph** [comment]
PTAL @cbracken

**Comment by mraleph** [comment]
@xster wow, you are fast :)

**Comment by xster** [comment]
org dashboard view :)

**Pull request merged**
