### PR TITLE
Roll goldctl to f808dcff91b221ae313e540c09d79696cd08b8de

### PR DESCRIPTION
**Pull request by zanderso**
goldctl hasn't been updated in about a year, and an update may be needed to reland https://github.com/flutter/flutter/pull/127110.

### CODE REVIEW

**Comment by zanderso** [comment]
@keyonghan Does this have to be updated anywhere outside of the `ci.yaml`?

**Comment by Piinks** [comment]
Oh wow, it was updated recently I thought in the luci recipes? I was unaware of it here. Looking for the cl we recently updated it in...

**Comment by zanderso** [comment]
See the comment from @godofredoc in that CL: https://flutter-review.git.corp.google.com/c/recipes/+/38126/comment/53a94ea2_d3e1ba9d/

> The preferred way of updating dependency versions is through .ci.yaml which will test the change in presubmit https://github.com/flutter/engine/blob/main/.ci.yaml#L440

**Review by mdebbar — APPROVED** [review]

**Comment by Piinks** [comment]
Good to know! Thanks @zanderso!

**Review by Piinks — APPROVED** [review]
LGTM

**Comment by keyonghan** [comment]
> @keyonghan Does this have to be updated anywhere outside of the ci.yaml?

This should be enough.

**Review by keyonghan — APPROVED** [review]
LGTM

**Review by kjlubick — APPROVED** [review]
For reference, here is the CIPD link: https://chrome-infra-packages.appspot.com/p/skia/tools/goldctl/linux-amd64/+/git_revision:f808dcff91b221ae313e540c09d79696cd08b8de

**Pull request merged**
