### PR TITLE
Reduce refresh indicator pull-down distance

### PR DESCRIPTION
**Pull request by LasseRosenow**
## Description

Reland of #44054 
Thanks to @altherat

## Related Issues

#14981

## Tests

@altherat added the following tests:

RefreshIndicator - just enough: Ensures a 100 pixel drag causes a refresh, which would fail with the previous pull-down distance.

Also modified an existing test (RefreshIndicator - not enough) to pass for the reduced pull-down distance.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by altherat** [comment]
@googlebot I consent.

**Comment by shihaohong** [comment]
Apparently one way to fix the `*customer-testing` issue is by doing a rebase like this:
```
git pull --rebase upstream master followed by git push --force origin <branch>
```

Alternatives are creating a new branch off of the latest upstream master and just re-adding my changes as a commit on top of that. I think https://github.com/flutter/flutter/pull/69726 has the context for what's causing this problem.

Also, would you be willing to put a side-by-side comparison gif of the native and Flutter behaviors in the PR description? That would help in the future if there's ever any question about the correct native behavior, especially changes occur for Android in the future.

**Comment by lazylazyllama** [comment]
Ooops I think I made things worse

**Comment by lazylazyllama** [comment]
I will open a new pr very soon

**Comment by lazylazyllama** [comment]
See #69783

**Pull request closed without merging**
