### PR TITLE
Roll engine to 0cc0784dd515c0b6831f7bfe36a701a7682f83d1

### PR DESCRIPTION
**Pull request by alhaad**
@abarth @zanderso

### CODE REVIEW

**Comment by xster** [comment]
LGTM

**Review by chinmaygarde — APPROVED** [review]
We are performing a roll to the exact commit that flips the switch on libTXT as a checkpoint for Google3. This commit will land right after.

**Comment by chinmaygarde** [comment]
Still blocked on the linked roll due to failures on the Mac bot.

**Comment by Hixie** [comment]
Closing since I assume we've rolled the engine now.

**Pull request closed without merging**
