### PR TITLE
Add a timeout to bot tests

### PR DESCRIPTION
**Pull request by tvolkert**
This will catch the case where tests hang -- and it will
force them to fail so that we see the output from the test.

### CODE REVIEW

**Comment by Hixie** [comment]
Can we just suppress the output unless it fails?

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by jakobr-google — APPROVED** [review]
LGTM

**Comment by tvolkert** [comment]
@Hixie it never failed - it hung (with a bunch of informative output)

**Comment by Hixie** [comment]
The reason we suppress the output is because it is massively confusing to have the logs contain messages that say things like "test failed" when they didn't. We've wasted way more than 8 SWEh on the confusion that this hides.

Ideally, IMHO, the entire bot output would be one line saying "All tests passed" unless anything failed.

**Comment by Hixie** [comment]
If it hung it should have hit a timeout and that should have made it fail.

**Comment by tvolkert** [comment]
> If it hung it should have hit a timeout and that should have made it fail.

Good point.  Update coming.

**Comment by tvolkert** [comment]
Ok, ready for another review - PTAL

**Comment by Hixie** [comment]
Now this I can get behind. :-)

LGTM

**Pull request merged**
