### PR TITLE
Revert "Nnbd widgets"

### PR DESCRIPTION
**Pull request by goderbauer**
Reverts flutter/flutter#64672

/cc @a14n @Hixie 

See flutter/flutter#64672 for failures caused by this.

### CODE REVIEW

**Review by a14n — APPROVED** [review]
LGTM :cry:

**Comment by zanderso** [comment]
See also failures in `flutter_gallery_sksl_warmup__transition_perf_e2e` in the device lab.

**Review by zanderso — APPROVED** [review]

**Comment by zanderso** [comment]
Landing revert on red.

**Comment by a14n** [comment]
> See also failures in `flutter_gallery_sksl_warmup__transition_perf_e2e` in the device lab.

Unfortunately I cannot sign in into https://flutter-dashboard.appspot.com/#/build to see what happened.

Moreover I really don't know who is the best person to help to fix it (it looks related to AOT compiler and nullsafety). Do you have someone in mind?

**Pull request merged**
