### PR TITLE
Add background color animation to MaterialInteriorState

### LINKED ISSUE #154255: ElevatedButton's background color isn't being animated between enabled/disabled states
### Steps to reproduce

1. Run sample code
2. Tap on the button "Press here"

### Expected results

The background color of the button should be animated

### Actual results

The background color is instantly swapped.

### Code sample

<details open><summary>Code sample</summary>

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool enabled = false;
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light().copyWith(
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.black,
            foregroundColor: Colors.white,
            disabledBackgroundColor: Colors.grey[300],
            disabledForegroundColor: Colors.grey[500],
          ),
        ),
      ),
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ElevatedButton(
                onPressed: enabled ? () {} : null,
                child: Text(enabled ? "Enabled" : "Disabled"),
              ),
              CupertinoButton(
                onPressed: () {
                  setState(() {
                    enabled = !enabled;
                  });
                },
                child: const Text("Press here"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/02679c52-1e07-47fc-9334-4cea79e0bc6c

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.25.0-1.0.pre.160, on macOS 14.6.1 23G93 darwin-arm64, locale en-SI)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.92.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by eliseyOzerov**
This PR adds an animation for the background of the ElevatedButton by adding a ColorTween for the backgroundColor to _MaterialInteriorState class and evaluating it against the animation as well as assigning the result to the PhysicalShape constructor.

Fixes #154255 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
(there was no docs on this code beforehand)
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
(not sure which tests I should add here)
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.
(42 existing tests weren't passing)

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hey @eliseyOzerov welcome! Thank you for contributing!
This will need a test to verify it works as expected, although, I am not sure this is a change we want to make. Is it documented as expected that this should not animate?

**Comment by eliseyOzerov** [comment]
Hi @Piinks!

I'm not sure about the docs, but background color was the only obvious property that wasn't animated, which then looks weird among all the others.

The code is completely equal to that of the shadowColor animation, so I think it should be fine, no? I'm not sure how to test this, I'd be very grateful if you can give me some suggestions, given this is animation code.

**Comment by eliseyOzerov** [comment]
Hi @nate-thegrate!

So, regarding inheritance, I've noticed that it inherits the color from AnimatedTheme, which is great! But what do we do with the enabled/disabled state then?

I don't think adding a ValueListenableBuilder to each button with a disabled state is a good solution, given that there's already support for different states of the button. Shouldn't these states be implicitly animated without additional mechanisms?

I don't know enough about the framework to hit the nail on the head with a solution, as this is just what I tried to solve my issue. Maybe there's a different place where this could be tackled? We could wrap the ElevatedButton into a custom widget, but this only adds more boilerplate to the codebase instead of solving the issue.

Also, seems like the foreground color is animated because it's wrapped in an AnimatedDefaultTextStyle

```dart
class _MaterialState extends State<Material> with TickerProviderStateMixin {
  final GlobalKey _inkFeatureRenderer = GlobalKey(debugLabel: 'ink renderer');

  @override
  Widget build(BuildContext context) {
    final ThemeData theme = Theme.of(context);
    final Color? backgroundColor = widget.color ?? switch (widget.type) {
      MaterialType.canvas => theme.canvasColor,
      MaterialType.card => theme.cardColor,
      MaterialType.button || MaterialType.circle || MaterialType.transparency => null,
    };
    final Color modelShadowColor = widget.shadowColor
        ?? (theme.useMaterial3 ? theme.colorScheme.shadow : theme.shadowColor);
    assert(
      backgroundColor != null || widget.type == MaterialType.transparency,
      'If Material type is not MaterialType.transparency, a color must '
      'either be passed in through the `color` property, or be defined '
      'in the theme (ex. canvasColor != null if type is set to '
      'MaterialType.canvas)',
    );

    Widget? contents = widget.child;
    if (contents != null) {
      contents = AnimatedDefaultTextStyle(
        style: widget.textStyle ?? Theme.of(context).textTheme.bodyMedium!,
        duration: widget.animationDuration,
        child: contents,
      );
    }
```
so the background color is the only one without its own animation.

I suppose if other properties could be affected by the button state it would be similar to the background color issue. I've also tested changing the color in the theme and this implementation doesn't seem to be interfering with the changing of the background color in the theme.

> Material doesn't need its color animated because it inherits an implicit animation from the AnimatedTheme that's built into the MaterialApp widget.

That's true, for only for the theme-level changes. And we could make the same argument for the border, yet it's still got its own ShapeBorderTween in the _MaterialInteriorState.

**Comment by eliseyOzerov** [comment]
Hi @Piinks, I don't really have time to focus on this anymore, so I'll close this PR. Thanks!

**Pull request closed without merging**
