### PR TITLE
Fixed  Action code sample in the documentation had a bug  issue #77591

### PR DESCRIPTION
**Pull request by 2002Bishwajeet**
According to the  Issue #77591

On the documentation website about Actions is a code Sample:
https://api.flutter.dev/flutter/widgets/Actions-class.html
You can increase a number by clicking +1 and decrease a number by clicking -1.
You start with 0. Let's increase the number to 4 by clicking +1. That works.
Now click -1. You should go to 3, but you go to 5. Click -1 again and now the number starts decreasing.
But the number should decrease directly with the first click on the -1 button after increasing the number.

Increasing after decreasing has the same bug. And the first click on -1 or +1 after reset is not changing the number in general.

This has been fixed by using pre increment operator.

The old one had (count++)
New one (++count) and it is working fine .

### CODE REVIEW

**Comment by 2002Bishwajeet** [comment]
@googlebot I signed it!

**Comment by chunhtai** [comment]
@2002Bishwajeet it looks like your branch is outdated, can you rebase off master again to see if that fixes the build

**Review by chunhtai — APPROVED** [review]
LGTM, just need to make sure the presubmit passes

**Comment by 2002Bishwajeet** [comment]
> @2002Bishwajeet it looks like your branch is outdated, can you rebase off master again to see if that fixes the build

hey @chunhtai  can you guide me on how to do that.

**Comment by yash1200** [comment]
```
git remote add upstream git@github.com:flutter/flutter.git
git fetch upstream
git merge upstream master
git push
```
Run this in your cloned repo

**Comment by 2002Bishwajeet** [comment]
> ```
> git remote add upstream git@github.com:flutter/flutter.git
> git fetch upstream
> git merge upstream master
> git push
> ```
> 
> Run this in your cloned repo

I Did as you said in the above - It's Already Updated

**Comment by 2002Bishwajeet** [comment]
> > ```
> > git remote add upstream git@github.com:flutter/flutter.git
> > git fetch upstream
> > git merge upstream master
> > git push
> > ```
> > 
> > 
> > Run this in your cloned repo
> 
> I Did as you said in the above - It's Already Updated

@yash1200

**Comment by yash1200** [comment]
You sure? Check it again because clearly your branch is 261 commits behind master.

**Comment by 2002Bishwajeet** [comment]
hey @yash1200 
image

This is what I Could see and tells that my branch is upto date

**Comment by 2002Bishwajeet** [comment]
hey @yash1200  do I have to create a new pull request for the same or it would be done in the same PR???

**Comment by 2002Bishwajeet** [comment]
hey @yash1200  Thanks a lot , the commands worked but flutter build still failed!! Any Help?

**Comment by yash1200** [comment]
Don't worry, that's not of your concern.

**Pull request merged**
