### PR TITLE
Fix ci.yaml and testowners format

### PR DESCRIPTION
**Pull request by chunhtai**
Updates the format to make it easier to parse by the automation script

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by chunhtai** [comment]
Hi @keyonghan I am trying to find where the ci.yaml validation test is, but couldn't find it

**Comment by chunhtai** [comment]
oh nvm it is in cocoon/app_dart/lib/src/model/proto/internal/scheduler.proto

**Review by keyonghan — COMMENTED** [review]
How about these categories? 
devicelab
devicelab_hostonly
framework_hostonly
framework_hostonly_shard
firebaselab

Instead of `type`, can we use `tags` with a list of strings? This way, we can add more tags as needed in the future, for example ios, driver, etc.

**Comment by chunhtai** [comment]
I added `devicelab`, `hostonly`, `framework`, `shard` tag
I still don't know animated_image_gc_perf and linux_skp_generator so i left them empty

**Comment by chunhtai** [comment]
@keyonghan , I merged the cocoon ci validation code, is there any additional step i need to do to pass the check?

**Comment by keyonghan** [comment]
> @keyonghan , I merged the cocoon ci validation code, is there any additional step i need to do to pass the check?

We need to wait for the cocoon deployment to pick up the changes. It gets deployed daily morning.

**Comment by keyonghan** [comment]
> I added `devicelab`, `hostonly`, `framework`, `shard` tag
> I still don't know animated_image_gc_perf and linux_skp_generator so i left them empty

https://github.com/flutter/flutter/pull/85667 to add missing ownership.

**Comment by chunhtai** [comment]
Win/Mac/Linux gradle_non_android_plugin_test existing in testowner and luci but not in ci.yaml

hot_mode_dev_cycle_win_target__benchmark exist in luci but not in testowner and ci.yaml (There is a similar test in testowner hot_mode_dev_cycle_win__benchmark, not sure if they are the same test)

cc @CaseyHillers

**Comment by CaseyHillers** [comment]
Thanks, I filed https://github.com/flutter/flutter/issues/85803. I would say let's add them as non-blocking first, and they can eventually be promoted to blocking.

**Comment by chunhtai** [comment]
Linux docs_publish exists in ci.yaml and luci but not in testowner

**Comment by CaseyHillers** [comment]
> Linux docs_publish exists in ci.yaml and luci but not in testowner

Would it make sense to port the testowner file into `.ci.yaml`? Once every target is given an owner, we can make it a requirement when adding new targets.

**Comment by chunhtai** [comment]
can you elaborate on that? I am not sure what does the `port` mean

**Comment by CaseyHillers** [comment]
You could add a new field to the target proto, `owner`, and targets in .ci.yaml can list who owns them. Then wherever can parse the yaml also gets this field.

```yaml
- name: Linux docs_publish
   # ...
   owner: team here
```

**Comment by chunhtai** [comment]
> You could add a new field to the target proto, `owner`, and targets in .ci.yaml can list who owns them. Then wherever can parse the yaml also gets this field.
> 
> ```yaml
> - name: Linux docs_publish
>    # ...
>    owner: team here
> ```

@keyonghan  and I had a brief discussion about this. The team wants to keep a github style owner file in the directory. If we also include the owner here it may be hard to keep them in sync.

**Comment by keyonghan** [comment]
> > You could add a new field to the target proto, `owner`, and targets in .ci.yaml can list who owns them. Then wherever can parse the yaml also gets this field.
> > ```yaml
> > - name: Linux docs_publish
> >    # ...
> >    owner: team here
> > ```
> 
> @keyonghan and I had a brief discussion about this. The team wants to keep a github style owner file in the directory. If we also include the owner here it may be hard to keep them in sync.

Yeah, see details in go/reduce_flutter_flakiness. The big concern is tests with shards, and it is not recommended to have ownership on shard level.

**Comment by keyonghan** [comment]
> > > You could add a new field to the target proto, `owner`, and targets in .ci.yaml can list who owns them. Then wherever can parse the yaml also gets this field.
> > > ```yaml
> > > - name: Linux docs_publish
> > >    # ...
> > >    owner: team here
> > > ```
> > 
> > 
> > @keyonghan and I had a brief discussion about this. The team wants to keep a github style owner file in the directory. If we also include the owner here it may be hard to keep them in sync.
> 
> Yeah, see details in go/reduce_flutter_flakiness. The big concern is tests with shards, and it is not recommended to have ownership on shard level.

After a revisit of our earlier discussions, the ownership makes sense on test level rather than on shard level from test file/directory perspective. Here we are using TL as the owner of builders for bug assignee and PR reviewer purpose, I guess it is okay to add TL in each builder config. This way will ease the ownership fetching process a lot, no matter if we use that info for bug assignee or to add a pre-submit test to enforce ownership.

On the other hand, we can continue to maintain TESTOWNERS file to track test file/directory ownership, and in the future merge it with CODEOWNERS file.
/cc @Hixie

**Comment by chunhtai** [comment]
I am ok either way, it will probably be easier for me to do that too. How are we going to make sure the TESTOWNERS and the ci.yaml from going out of sync?

**Comment by Hixie** [comment]
If test ownership is done at the test level (i.e. ownership of files in the repo), then there's nothing in ci.yaml that needs to be kept up to date, right? It doesn't matter how the tests are sharded, all that matters is which test flaked. So a shard can have two tests by two different owners, and a test can be used in two shards, and in either case there's unambiguous ownership.

**Review by keyonghan — APPROVED** [review]
Nit: https://github.com/flutter/cocoon/blob/master/CI_YAML.md may need an update.

**Comment by keyonghan** [comment]
Let's deploy/promote a dev version to gcloud, and split some traffic to validate the changes not breaking anything before we submit.

**Comment by chunhtai** [comment]
update is in this pr https://github.com/flutter/cocoon/pull/1269

**Pull request merged**
