### PR TITLE
Make CircularProgressIndicator's stroke width configurable

### LINKED ISSUE #9062: CircularProgressIndicator should have a strokeWidth parameter.

### PR DESCRIPTION
**Pull request by abarth**
Fixes #9062

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
wait wait

where's the test!

**Comment by Hixie** [comment]
https://github.com/flutter/flutter/pull/10121 should make writing a test here easier

**Comment by abarth** [comment]
Now with test.  Thanks!

**Comment by Hixie** [comment]
Landing to avoid bit rot.

**Comment by abarth** [comment]
Thanks.  I thought I had landed it.

**Pull request merged**
