### PR TITLE
Reset the global variable before running a test.

### PR DESCRIPTION
**Pull request by chingjun**
The variable debugDisableShadows wasn't reset before each test, so the
output of the test is different depending on whether the previous test
has passed.

Discovered in #45530

### CODE REVIEW

**Comment by jonahwilliams** [comment]
The test framework should be asserting that these values are unset after each test case, for example: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/gestures/debug.dart#L59

It looks like the check for debugDisableShadows is missing

**Comment by chingjun** [comment]
There is indeed a check for `debugDisableShadows` here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/debug.dart#L45

But the check doesn't help in this case. When the previous test failed, the verification doesn't get to run.

Everything works correctly when all the tests succeed. The only problem is when one test failed, it might cause another unrelated test to fail as well with weird symptom (in this case, shadow enabled when it should be disabled), causing confusion and wasting some debugging time :)

**Comment by goderbauer** [comment]
Instead of resetting it of the beginning of every test, could you add one tearDown that resets it at the end of the test even if the tests fails?

**Comment by chingjun** [comment]
That's a great idea, done it in "teardown" instead of resetting the variable at the beginning of each test.

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
