### PR TITLE
[do not merge] google testing verify skipping files and report on neutral state 

### PR DESCRIPTION
**Pull request by XilaiZhang**
similar to https://github.com/flutter/flutter/pull/130046 and https://github.com/flutter/flutter/pull/127895
this PR is used as an integration test to verify the logics we landed in cl/550076135

When the PR only includs file changes that do not need to be rolled into google 3, Google testing should report a neutral state and return the state early.

### CODE REVIEW

**Comment by XilaiZhang** [comment]
Looks like this pulled in an unrelated file third_party/dart/flutter/test/painting/decoration_image_lerp_test.dart (a new file that doesn't exist in github or google3). Synced with Casey and Casey pointed out this is a known bug: where when someone opens a new pull request that adds a new file in testing, github includes untracked files even after a `git reset hard`.

The action item here is to do a `git clean -f -d` after `git reset hard` in our github checkout of the flutter repo, so that when we are copying from the github checkout into google3, we do not include these new files. Another note is that the git cache gets reset every time we redeploy roll worker.

**Comment by XilaiZhang** [comment]
Ah cool Google testing returned with a neutral state as expected! cc @CaseyHillers

**Comment by goderbauer** [comment]
Is this PR still needed or can we close it?

**Comment by XilaiZhang** [comment]
yes sir closed

**Pull request closed without merging**
