### PR TITLE
Fatten up multiple_flutters memory footprint

### LINKED ISSUE #93292: Move multiple_flutters benchmark to using the flutter gallery
When sharing GrContext's was reverted the signal on the benchmark wasn't noticeable (https://github.com/flutter/engine/pull/28694).  We should switch the benchmark to use the flutter gallery to stress out the memory more.

(benchmark here: https://github.com/flutter/flutter/tree/master/dev/benchmarks/multiple_flutters)

### PR DESCRIPTION
**Pull request by gaaclarke**
**NOTICE: This intentionally increases the memory readings for flutter_engine_group_performance devicelab task.  This is not a regression.**

fixes https://github.com/flutter/flutter/issues/93292

I looked into using the flutter gallery but it would be quite involved to use that for the the performance tests.  There is some massaging that has to happen to convert an app to a module that we'd have to automate.

Alternatively, I just tried to fatten it up by adding:
1) Icons
2) A large image
3) Custom painter
4) A custom font
5) Increased the number of instances from 2 to 5

In local testing this sent the memory footprint from 56549KB to 111498KB (~55MB increase).

This should help a bit but the problem is that the probe is so gross it's hard to pinpoint the regressions.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by zanderso — COMMENTED** [review]
This seems like a good idea independent of the specific issue we would have hoped to catch by doing this, but it sounds like you're saying that even with this change we wouldn't have caught it? Do you have before/after numbers with your engine PR?

**Comment by gaaclarke** [comment]
@zanderso I ran the tests before and after the change and it resulted in a 1355KB reduction (1.15%).  I'm not sure if that is noticeable enough.  I'm not sure of the pathological case that would explode the size of the GrContext.  I could try increasing the number of instances to 10, that should in theory at least double the reduction.  I'm not sure how sensitive our regression detection is.

```
Before change:

Task result:
{
  "success": true,
  "data": {
    "totalMemory-min": 109066,
    "totalMemory-max": 125974,
    "totalMemory-median": 117166
  },
  "detailFiles": [],
  "benchmarkScoreKeys": [
    "totalMemory-min",
    "totalMemory-max",
    "totalMemory-median"
  ],
  "reason": "success"
}

After change:

Task result:
{
  "success": true,
  "data": {
    "totalMemory-min": 106083,
    "totalMemory-max": 121368,
    "totalMemory-median": 115811
  },
  "detailFiles": [],
  "benchmarkScoreKeys": [
    "totalMemory-min",
    "totalMemory-max",
    "totalMemory-median"
  ],
  "reason": "success"
}
```

**Comment by zanderso** [comment]
If the run-to-run variance is small, the regression detection will create alerts for small regressions, but if the run-to-run variance is large, then they'll be missed.

**Comment by gaaclarke** [comment]
@zanderso https://flutter-flutter-perf.skia.org/e/?queries=test%3DLinux_flutter_engine_group_performance  here is the output now.  Looks like 1.5MB might not go noticed, I'm eyeballing about 2MB of variance.  I'll try tweaking the number of engines since I'm unsure about increasing the GrContext size.

**Comment by gaaclarke** [comment]
I'm running in to a problem where the app is deadlocking when increasing the number of engines.  I can't get a stacktrace because the engine's symbols are stripped.  I can see that not all of the engine's plugins are getting registered though since path_provider prints out if it is using TaskQueues or not.  I do know that there is a pthread_cond_wait at the top of the stack.  This worked at some point for xiao, either there was a regression or potentially the adding of a plugin caused it.  I tried out Flutter before background task queues and it demonstrated the problem still.

**Comment by gaaclarke** [comment]
I removed the plugins from the module and there is no more deadlock.

**Comment by gaaclarke** [comment]
Specifically, just removing flutter_gallery_assets and the image from it removed the deadlock:
```diff
diff --git a/dev/benchmarks/multiple_flutters/android/app/src/main/java/dev/flutter/multipleflutters/MainActivity.kt b/dev/benchmarks/multiple_flutters/android/app/src/main/java/dev/flutter/multipleflutters/MainActivity.kt
index 86203e06e9..d2c507944e 100644
--- a/dev/benchmarks/multiple_flutters/android/app/src/main/java/dev/flutter/multipleflutters/MainActivity.kt
+++ b/dev/benchmarks/multiple_flutters/android/app/src/main/java/dev/flutter/multipleflutters/MainActivity.kt
@@ -19,7 +19,7 @@ import io.flutter.embedding.engine.FlutterEngineCache
 import io.flutter.embedding.engine.dart.DartExecutor
 
 class MainActivity : FragmentActivity() {
-    private val numberOfFlutters = 5
+    private val numberOfFlutters = 10
 
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
diff --git a/dev/benchmarks/multiple_flutters/module/lib/main.dart b/dev/benchmarks/multiple_flutters/module/lib/main.dart
index 99a56fe010..073b1828bf 100644
--- a/dev/benchmarks/multiple_flutters/module/lib/main.dart
+++ b/dev/benchmarks/multiple_flutters/module/lib/main.dart
@@ -118,42 +118,38 @@ class _MyHomePageState extends State<MyHomePage> {
               ),
               Row(
                 mainAxisAlignment: MainAxisAlignment.spaceAround,
-                children: <Widget>[
-                  const Icon(
+                children: const <Widget>[
+                  Icon(
                     Icons.favorite,
                     color: Colors.pink,
                     size: 24.0,
                     semanticLabel: 'Text to announce in accessibility modes',
                   ),
-                  const Icon(
+                  Icon(
                     Icons.audiotrack,
                     color: Colors.green,
                     size: 30.0,
                   ),
-                  const Icon(
+                  Icon(
                     Icons.beach_access,
                     color: Colors.blue,
                     size: 36.0,
                   ),
-                  const Icon(
+                  Icon(
                     Icons.zoom_out,
                     color: Colors.amber,
                     size: 36.0,
                   ),
-                  const Icon(
+                  Icon(
                     Icons.money,
                     color: Colors.lightGreen,
                     size: 36.0,
                   ),
-                  const Icon(
+                  Icon(
                     Icons.bug_report,
                     color: Colors.teal,
                     size: 36.0,
-                  ),
-                  Image.asset('food/fruits.png',
-                      package: 'flutter_gallery_assets',
-                      width: 36.0,
-                      height: 36.0),
+                  ),                  
                 ],
               ),
               CustomPaint(
diff --git a/dev/benchmarks/multiple_flutters/module/pubspec.yaml b/dev/benchmarks/multiple_flutters/module/pubspec.yaml
index 83bc99c715..e94f2932c0 100644
--- a/dev/benchmarks/multiple_flutters/module/pubspec.yaml
+++ b/dev/benchmarks/multiple_flutters/module/pubspec.yaml
@@ -11,7 +11,6 @@ dependencies:
     sdk: flutter
 
   cupertino_icons: 1.0.4
-  flutter_gallery_assets: 1.0.2
   google_fonts: 2.1.0
 
   async: 2.8.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
@@ -48,11 +47,5 @@ flutter:
     androidX: true
     androidPackage: com.example.multiple_flutters_module
     iosBundleIdentifier: com.example.multipleFluttersModule
-  assets:
-    - packages/flutter_gallery_assets/food/fruits.png
-  fonts:
-    - family: GalleryIcons
-      fonts:
-        - asset: packages/flutter_gallery_assets/fonts/GalleryIcons.ttf
 
 # PUBSPEC CHECKSUM: f80b
```

I'll file another issue after this.

**Comment by gaaclarke** [comment]
Removing the flutter_gallery_assets to remove the deadlock and increasing the number of instances to 10 gives us ~4MB (5%) swing when sharing the GrContext.  I think we can do a little bit better.  I'll add a bit more drawing and a bit more instances:
```
Before change:

Task result:
{
  "success": true,
  "data": {
    "totalMemory-min": 80959,
    "totalMemory-max": 84641,
    "totalMemory-median": 81437
  },
  "detailFiles": [],
  "benchmarkScoreKeys": [
    "totalMemory-min",
    "totalMemory-max",
    "totalMemory-median"
  ],
  "reason": "success"
}

After change:

Task result:
{
  "success": true,
  "data": {
    "totalMemory-min": 75615,
    "totalMemory-max": 88725,
    "totalMemory-median": 77456
  },
  "detailFiles": [],
  "benchmarkScoreKeys": [
    "totalMemory-min",
    "totalMemory-max",
    "totalMemory-median"
  ],
  "reason": "success"
}
```

**Comment by gaaclarke** [comment]
Okay, I think that's the best I'm going to get.  I've increased the instances to 20.  It looks like there is a difference between a engine that is offscreen versus onscreen.  Here are the results 7.2MB (7%):
```
Task result:
{
  "success": true,
  "data": {
    "totalMemory-min": 101584,
    "totalMemory-max": 105728,
    "totalMemory-median": 102514
  },
  "detailFiles": [],
  "benchmarkScoreKeys": [
    "totalMemory-min",
    "totalMemory-max",
    "totalMemory-median"
  ],
  "reason": "success"
}


after

Task result:
{
  "success": true,
  "data": {
    "totalMemory-min": 92211,
    "totalMemory-max": 98257,
    "totalMemory-median": 95305
  },
  "detailFiles": [],
  "benchmarkScoreKeys": [
    "totalMemory-min",
    "totalMemory-max",
    "totalMemory-median"
  ],
  "reason": "success"
}
```

**Review by zanderso — APPROVED** [review]
lgtm, the deadlock was concerning, though. We should probably have an issue filed describing how to trigger that.

**Comment by gaaclarke** [comment]
Filed deadlock issue: https://github.com/flutter/flutter/issues/93564

**Comment by Kvnbbg** [comment]
**Thank You**

**Pull request merged**
