### PR TITLE
[versions] roll many versions

### PR DESCRIPTION
**Pull request by jonahwilliams**
Most of our versions are unstuck now, still not test

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
```
00:03 +4 ~1 -1: test/prepare_package_test.dart: Throws on missing executable [E]                                                                                                                       
  Expected: contains 'Invalid argument(s): Failed to resolve this_executable_better_not_exist_2857632534321 to an executable.'
    Actual: 'Running "this_executable_better_not_exist_2857632534321" in /opt/s/w/ir/k/flutter/dev/bots failed with:\n'
              'ProcessException: Failed to find "this_executable_better_not_exist_2857632534321" in the search path.\n'
              '  Command: this_executable_better_not_exist_2857632534321 '
  
  package:test_api                     expect
  test/prepare_package_test.dart 30:7  main.<fn>
```

**Comment by jonahwilliams** [comment]
Fixed!

**Comment by jonahwilliams** [comment]
version rolls will not affect g3, landing

**Comment by pinkasey** [comment]
Hope it's OK to ask here -
when will this reach `stable` channel?

I want to migrate to null-safety, and the `flutter_driver` in channel `stable` is not compatible.
I believe that this change will allow me to proceed (right now I'm stuck because of `args: 1.6.0`)

**Comment by jonahwilliams** [comment]
I do not know exactly when the next stable release will be ready, but we generally do one release a quarter and the next one is soon-ish

**Pull request merged**
