### PR TITLE
[flutter_tools] cache for UWP artifacts

### PR DESCRIPTION
**Pull request by jonahwilliams**
Add the ability to download the cached artifacts for the windows UWP build. Also fixes some inconsistencies with the gen_snapshot lookup which broke aot compilation.

https://github.com/flutter/flutter/issues/70211

### CODE REVIEW

**Comment by jonahwilliams** [comment]
This will _probably_ fix the build release issue too

**Review by clarkezone — APPROVED** [review]
LGTK

**Review by cbracken — APPROVED** [review]
lgtm -- thanks!

**Comment by clarkezone** [comment]
Tested and works great for debug but release still broken:

```
c:\src\f3\flutter-uwp-template\src>flutter run --release --verbose
[  +64 ms] executing: [C:\src\f3\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +76 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 02efffc134ab4ce4ff50a9ddd86c832efdb80462
[        ] executing: [C:\src\f3\flutter/] git tag --points-at 02efffc134ab4ce4ff50a9ddd86c832efdb80462
[  +70 ms] Exit code 0 from: git tag --points-at 02efffc134ab4ce4ff50a9ddd86c832efdb80462
[   +1 ms] executing: [C:\src\f3\flutter/] git describe --match *.*.* --long --tags
02efffc134ab4ce4ff50a9ddd86c832efdb80462
[ +114 ms] Exit code 0 from: git describe --match *.*.* --long --tags
02efffc134ab4ce4ff50a9ddd86c832efdb80462
[   +1 ms] 2.1.0-12.0.pre-574-g02efffc134
[   +4 ms] executing: [C:\src\f3\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\src\f3\flutter/] git ls-remote --get-url origin
[  +40 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +320 ms] Unable to locate an Android SDK.
[   +6 ms] executing: [C:\src\f3\flutter/] git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +51 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +93 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] Multiple devices found:
[  +31 ms] Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version
10.0.19042.870]
[   +1 ms] Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 • Microsoft Windows [Version
10.0.19042.870]
[        ] Chrome (web)            • chrome  • web-javascript  • Google Chrome 89.0.4389.90
[        ] Edge (web)              • edge    • web-javascript  • Microsoft Edge 89.0.774.68
[   +1 ms] [1]: Windows (windows)
[        ] [2]: Windows (UWP) (winuwp)
[        ] [3]: Chrome (chrome)
[        ] [4]: Edge (edge)
[   +1 ms] Please choose one (To quit, press "q/Q")
[        ] :
[+2620 ms] 2
[   +9 ms] Skipping pub get: version match.
[  +82 ms] Generating
c:\src\f3\flutter-uwp-template\src\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.
java
[  +82 ms] Launching lib\main.dart on Windows (UWP) in release mode...
[  +11 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json
-products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[ +394 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format
json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[   +1 ms] [
             {
               "instanceId": "20d429d3",
               "installDate": "2020-06-05T04:47:56Z",
               "installationName": "VisualStudio/16.9.1+31105.61",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.9.31105.61",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Powerful IDE, free for students, open-source contributors, and
               individuals",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Servi
               ce",
               "releaseNotes":
               "https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.9#16.9.1",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2021-03-15T22:17:34.196119Z",
               "catalog": {
                 "buildBranch": "d16.9",
                 "buildVersion": "16.9.31105.61",
                 "id": "VisualStudio/16.9.1+31105.61",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.9.1",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "1",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.9.1+31105.61",
                 "requiredEngineVersion": "2.9.3352.28579"
               },
               "properties": {
                 "campaignId": "1363741881.1591332351",
                 "channelManifestId": "VisualStudio.16.Release/16.9.1+31105.61",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual
                 Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[   +4 ms] Building Windows application...
[   +8 ms] executing: C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -S
c:\src\f3\flutter-uwp-template\src\winuwp -B build\winuwp -G Visual Studio 16 2019
[  +60 ms] -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.
[  +35 ms] -- Configuring done
[ +266 ms] -- Generating done
[  +19 ms] -- Build files have been written to: C:/src/f3/flutter-uwp-template/src/build/winuwp
[   +8 ms] executing: C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe --build
build\winuwp --config Release --verbose
[ +106 ms] Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET Framework
[        ] Copyright (C) Microsoft Corporation. All rights reserved.
[  +45 ms] Build started 4/10/2021 10:07:47 AM.
[ +221 ms] Project "C:\src\f3\flutter-uwp-template\src\build\winuwp\ALL_BUILD.vcxproj" on node 1 (default
targets).
[        ] Project "C:\src\f3\flutter-uwp-template\src\build\winuwp\ALL_BUILD.vcxproj" (1) is building
"C:\src\f3\flutter-uwp-template\src\build\winuwp\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
[        ] InitializeBuildStatus:
[        ]   Creating "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate"
was specified.
[  +21 ms] CustomBuild:
[        ]   All outputs are up-to-date.
[  +15 ms] FinalizeBuildStatus:
[        ]   Deleting file "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
[        ]   Touching "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
[        ] Done Building Project "C:\src\f3\flutter-uwp-template\src\build\winuwp\ZERO_CHECK.vcxproj"
(default targets).
[ +119 ms] Project "C:\src\f3\flutter-uwp-template\src\build\winuwp\ALL_BUILD.vcxproj" (1) is building
"C:\src\f3\flutter-uwp-template\src\build\winuwp\flutter\flutter_wrapper_app.vcxproj" (3) on node 1
(default targets).
[        ] Project "C:\src\f3\flutter-uwp-template\src\build\winuwp\flutter\flutter_wrapper_app.vcxproj"
(3) is building "C:\src\f3\flutter-uwp-template\src\build\winuwp\flutter\flutter_assemble.vcxproj" (4) on
node 1 (default targets).
[        ] InitializeBuildStatus:
[        ]   Touching "x64\Release\flutter_assemble\flutter_assemble.tlog\unsuccessfulbuild".
[   +2 ms] CustomBuild:
[        ]   "The build of
'C:\src\f3\flutter-uwp-template\src\build\winuwp\CMakeFiles\f1a87c17f1a0528aaa6e1d6d61811962\flutter_assem
ble.rule' depends on
'C:\SRC\F3\FLUTTER-UWP-TEMPLATE\SRC\WINUWP\FLUTTER\EPHEMERAL\FLUTTER_WINDOWS_WINUWP.DLL' which is produced
by the build of
'C:\src\f3\flutter-uwp-template\src\build\winuwp\CMakeFiles\8f94b3390d9d9024edd89c1d75fe7c55\flutter_windo
ws_winuwp.dll.rule'. The items cannot be built in parallel."
[  +55 ms]   Generating
C:/src/f3/flutter-uwp-template/src/winuwp/flutter/ephemeral/flutter_windows_winuwp.dll,
C:/src/f3/flutter-uwp-template/src/winuwp/flutter/ephemeral/flutter_export.h,
C:/src/f3/flutter-uwp-template/src/winuwp/flutter/ephemeral/flutter_windows.h,
C:/src/f3/flutter-uwp-template/src/winuwp/flutter/ephemeral/flutter_messenger.h,
C:/src/f3/flutter-uwp-template/src/winuwp/flutter/ephemeral/flutter_plugin_registrar.h,
C:/src/f3/flutter-uwp-template/src/winuwp/flutter/ephemeral/flutter_texture_registrar.h,
C:/src/f3/flutter-uwp-template/src/winuwp/flutter/ephemeral/cpp_client_wrapper/core_implementations.cc,
C:/src/f3/flutter-uwp-template/src/winuwp/flutter/ephemeral/cpp_client_wrapper/standard_codec.cc,
C:/src/f3/flutter-uwp-template/src/winuwp/flutter/ephemeral/cpp_client_wrapper/plugin_registrar.cc,
C:/src/f3/flutter-uwp-template/src/winuwp/flutter/ephemeral/cpp_client_wrapper/flutter_engine.cc,
C:/src/f3/flutter-uwp-template/src/winuwp/flutter/ephemeral/cpp_client_wrapper/flutter_view_controller.cc,
_phony_
[ +955 ms]   [  +61 ms] executing: [C:\src\f3\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +61 ms]   [  +80 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ]   [        ] 02efffc134ab4ce4ff50a9ddd86c832efdb80462
[        ]   [        ] executing: [C:\src\f3\flutter/] git tag --points-at
02efffc134ab4ce4ff50a9ddd86c832efdb80462
[  +81 ms]   [  +81 ms] Exit code 0 from: git tag --points-at 02efffc134ab4ce4ff50a9ddd86c832efdb80462
[        ]   [   +1 ms] executing: [C:\src\f3\flutter/] git describe --match *.*.* --long --tags
02efffc134ab4ce4ff50a9ddd86c832efdb80462
[ +122 ms]   [ +121 ms] Exit code 0 from: git describe --match *.*.* --long --tags
02efffc134ab4ce4ff50a9ddd86c832efdb80462
[        ]   [        ] 2.1.0-12.0.pre-574-g02efffc134
[   +4 ms]   [   +5 ms] executing: [C:\src\f3\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +50 ms]   [  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ]   [        ] origin/master
[        ]   [        ] executing: [C:\src\f3\flutter/] git ls-remote --get-url origin
[  +46 ms]   [  +47 ms] Exit code 0 from: git ls-remote --get-url origin
[        ]   [        ] https://github.com/flutter/flutter.git
[ +392 ms]   [ +392 ms] Unable to locate an Android SDK.
[   +7 ms]   [   +7 ms] executing: [C:\src\f3\flutter/] git rev-parse --abbrev-ref HEAD
[  +48 ms]   [  +48 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ]   [        ] master
[  +51 ms]   [  +52 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ]   [   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +78 ms]   [  +80 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ]   [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ]   [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ]   [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +23 ms]   [  +28 ms] Initializing file store
[  +13 ms]   [  +13 ms] Done initializing file store
[  +45 ms]   [  +45 ms] Skipping target: gen_localizations
[+1598 ms]   [+1598 ms] Skipping target: unpack_windows_uwp
[ +277 ms]   [ +277 ms] Skipping target: kernel_snapshot
[ +110 ms]   [ +110 ms] aot_elf_release: Starting due to {}
[   +5 ms]   [   +5 ms] Persisting file store
[   +8 ms]   [   +8 ms] Done persisting file store
[   +7 ms]   [   +7 ms] "flutter assemble" took 2,192ms.
[   +7 ms]   [   +8 ms] Sending crash report to Google.
[ +338 ms]   [ +338 ms] Crash report sent (report ID: 8979a0639ce202bd)
[   +1 ms]   [        ] Oops; flutter has exited unexpectedly: "ReachabilityError: `null` encountered as
case in a switch expression with a non-nullable enum type.".
[  +24 ms]   [  +24 ms] executing: [C:\src\f3\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%ar
[  +51 ms]   [  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ]   [        ] 9 hours ago
[  +62 ms]   [  +62 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
-format json -products * -utf8 -latest -version 16 -requires Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.CMake.Project
[ +390 ms]   [ +390 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual
Studio\Installer\vswhere.exe -format json -products * -utf8 -latest -version 16 -requires
Microsoft.VisualStudio.Workload.NativeDesktop Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.VC.CMake.Project
[        ]   [        ] [
[        ]                {
[        ]                  "instanceId": "20d429d3",
[        ]                  "installDate": "2020-06-05T04:47:56Z",
[        ]                  "installationName": "VisualStudio/16.9.1+31105.61",
[        ]                  "installationPath": "C:\\Program Files (x86)\\Microsoft Visual
Studio\\2019\\Community",
[        ]                  "installationVersion": "16.9.31105.61",
[        ]                  "productId": "Microsoft.VisualStudio.Product.Community",
[        ]                  "productPath": "C:\\Program Files (x86)\\Microsoft Visual
Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
[        ]                  "state": 4294967295,
[        ]                  "isComplete": true,
[        ]                  "isLaunchable": true,
[        ]                  "isPrerelease": false,
[        ]                  "isRebootRequired": false,
[        ]                  "displayName": "Visual Studio Community 2019",
[        ]                  "description": "Powerful IDE, free for students, open-source contributors, and
individuals",
[        ]                  "channelId": "VisualStudio.16.Release",
[        ]                  "channelUri": "https://aka.ms/vs/16/release/channel",
[        ]                  "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
[        ]                  "releaseNotes":
"https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.9#16.9.1",
[        ]                  "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
[        ]                  "updateDate": "2021-03-15T22:17:34.196119Z",
[        ]                  "catalog": {
[        ]                    "buildBranch": "d16.9",
[        ]                    "buildVersion": "16.9.31105.61",
[        ]                    "id": "VisualStudio/16.9.1+31105.61",
[        ]                    "localBuild": "build-lab",
[        ]                    "manifestName": "VisualStudio",
[        ]                    "manifestType": "installer",
[        ]                    "productDisplayVersion": "16.9.1",
[        ]                    "productLine": "Dev16",
[        ]                    "productLineVersion": "2019",
[        ]                    "productMilestone": "RTW",
[        ]                    "productMilestoneIsPreRelease": "False",
[        ]                    "productName": "Visual Studio",
[        ]                    "productPatchVersion": "1",
[        ]                    "productPreReleaseMilestoneSuffix": "1.0",
[        ]                    "productSemanticVersion": "16.9.1+31105.61",
[        ]                    "requiredEngineVersion": "2.9.3352.28579"
[        ]                  },
[        ]                  "properties": {
[        ]                    "campaignId": "1363741881.1591332351",
[        ]                    "channelManifestId": "VisualStudio.16.Release/16.9.1+31105.61",
[        ]                    "nickname": "",
[        ]                    "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual
Studio\\Installer\\vs_installershell.exe"
[        ]                  }
[        ]                }
[        ]              ]
[        ]   [   +1 ms] executing: reg query HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft
SDKs\Windows\v10.0 /v InstallationFolder
[  +10 ms]   [  +19 ms] Exit code 0 from: reg query
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0 /v InstallationFolder
[        ]   [        ] HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0
[        ]                  InstallationFolder    REG_SZ    C:\Program Files (x86)\Windows Kits\10\
[ +112 ms] CUSTOMBUILD : Unable to generate crash report due to secondary error : Null check operator used
on a null value [C:\src\f3\flutter-uwp-template\src\build\winuwp\flutter\flutter_assemble.vcxproj]
[        ]   Please report a bug at https://github.com/flutter/flutter/issues.
[        ]   [ +109 ms] Sending crash report to Google.
[ +445 ms]   [ +449 ms] Crash report sent (report ID: a78b3e697c81d248)
[        ]   [        ] Oops; flutter has exited unexpectedly: "ReachabilityError: `null` encountered as
case in a switch expression with a non-nullable enum type.".
[  +49 ms]   [  +50 ms] executing: reg query HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft
SDKs\Windows\v10.0 /v InstallationFolder
[  +19 ms]   [  +19 ms] Exit code 0 from: reg query
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0 /v InstallationFolder
[        ]   [        ] HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0
[        ]                  InstallationFolder    REG_SZ    C:\Program Files (x86)\Windows Kits\10\
[   +6 ms] CUSTOMBUILD : Unable to generate crash report due to secondary error : Null check operator used
on a null value [C:\src\f3\flutter-uwp-template\src\build\winuwp\flutter\flutter_assemble.vcxproj]
[        ]   Please report a bug at https://github.com/flutter/flutter/issues.
[        ]   Unhandled exception:
[        ]   ProcessExit: 1
[        ]   #0      _handleToolError (package:flutter_tools/runner.dart:172:7)
[        ]   <asynchronous suspension>
[        ]   #1      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:86:7)
[        ]   <asynchronous suspension>
[  +64 ms] C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: Custom
build for
'C:\src\f3\flutter-uwp-template\src\build\winuwp\CMakeFiles\8f94b3390d9d9024edd89c1d75fe7c55\flutter_windo
ws_winuwp.dll.rule;C:\src\f3\flutter-uwp-template\src\build\winuwp\CMakeFiles\f1a87c17f1a0528aaa6e1d6d6181
1962\flutter_assemble.rule' exited with code 1.
[C:\src\f3\flutter-uwp-template\src\build\winuwp\flutter\flutter_assemble.vcxproj]
[   +3 ms] Done Building Project
"C:\src\f3\flutter-uwp-template\src\build\winuwp\flutter\flutter_assemble.vcxproj" (default targets) --
FAILED.
[        ] Done Building Project
"C:\src\f3\flutter-uwp-template\src\build\winuwp\flutter\flutter_wrapper_app.vcxproj" (default targets) --
FAILED.
[  +53 ms] Done Building Project "C:\src\f3\flutter-uwp-template\src\build\winuwp\ALL_BUILD.vcxproj"
(default targets) -- FAILED.
[   +1 ms] Build FAILED.
[   +2 ms] "C:\src\f3\flutter-uwp-template\src\build\winuwp\ALL_BUILD.vcxproj" (default target) (1) ->
[        ] "C:\src\f3\flutter-uwp-template\src\build\winuwp\flutter\flutter_wrapper_app.vcxproj" (default
target) (3) ->
[        ] "C:\src\f3\flutter-uwp-template\src\build\winuwp\flutter\flutter_assemble.vcxproj" (default
target) (4) ->
[        ] (CustomBuild target) ->
[        ]   CUSTOMBUILD : Unable to generate crash report due to secondary error : Null check operator
used on a null value [C:\src\f3\flutter-uwp-template\src\build\winuwp\flutter\flutter_assemble.vcxproj]
[        ]   CUSTOMBUILD : Unable to generate crash report due to secondary error : Null check operator
used on a null value [C:\src\f3\flutter-uwp-template\src\build\winuwp\flutter\flutter_assemble.vcxproj]
[        ]   C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: Custom
build for
'C:\src\f3\flutter-uwp-template\src\build\winuwp\CMakeFiles\8f94b3390d9d9024edd89c1d75fe7c55\flutter_windo
ws_winuwp.dll.rule;C:\src\f3\flutter-uwp-template\src\build\winuwp\CMakeFiles\f1a87c17f1a0528aaa6e1d6d6181
1962\flutter_assemble.rule' exited with code 1.
[C:\src\f3\flutter-uwp-template\src\build\winuwp\flutter\flutter_assemble.vcxproj]
[        ]     0 Warning(s)
[        ]     3 Error(s)
[        ] Time Elapsed 00:00:06.10
[  +23 ms] Building Windows application... (completed in 6.7s)
[        ] Exception: Build process failed.
[   +1 ms] "flutter run" took 10,121ms.
[   +3 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1047:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[  +28 ms] ensureAnalyticsSent: 26ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Pull request merged**
