### PR TITLE
De-flake adapter integration test

### PR DESCRIPTION
**Pull request by bdero**
Expected to resolve this high rate flake: https://github.com/flutter/flutter/issues/120015.

I'm not sure if this will water down the test too much.

### CODE REVIEW

**Review by DanTup — APPROVED** [review]
LGTM, and I don't think they change what's being tested in a negative way.

Although I'm curious whether something changed recently that caused this? And why it would be flaky (are we sometimes fetching dependencies and sometimes not?)

Some other thoughts - we could change the test setup to ensure dependencies have been fetched before the test, and/or have the this output just filtered out by helper classes.

**Comment by bdero** [comment]
> Although I'm curious whether something changed recently that caused this? And why it would be flaky (are we sometimes fetching dependencies and sometimes not?)

Not sure, I didn't manage to find a clear smoking gun around the commits or builder recipes.
The high rate beings at this seemingly unrelated commit: https://github.com/flutter/flutter/commit/3f02d4b4c35965a4aaa60bb1cbab7c9cba9e205a

> Some other thoughts - we could change the test setup to ensure dependencies have been fetched before the test, and/or have the this output just filtered out by helper classes.

That sounds reasonable to me. Would you mind adding an issue about this?

**Comment by bdero** [comment]
This fix is getting blocked by another high rate flake: https://github.com/flutter/flutter/issues/120014

I'm going to land this fix with broken tests if it breaks a 3rd time.

**Comment by DanTup** [comment]
> Not sure, I didn't manage to find a clear smoking gun around the commits or builder recipes.
> The high rate beings at this seemingly unrelated commit: https://github.com/flutter/flutter/commit/3f02d4b4c35965a4aaa60bb1cbab7c9cba9e205a

We have this code that seems like it was intended to skip this kind of output at the start, but seems like maybe it's changed? 🤔:

https://github.com/flutter/flutter/blob/bbca7ff693e27ac58119b8cc2a6d73099854b219/packages/flutter_tools/test/integration.shard/debug_adapter/test_client.dart#L357-L363

The referenced PR did land, but maybe timestamps on the files are still not reliable enough. As a slight improvement, I've extended that code to handle the output shown in #120015 and removed these `allowExtras` to keep the tests a little more strict - see https://github.com/flutter/flutter/pull/120077.

**Comment by DanTup** [comment]
@bdero I landed some slight changes in https://github.com/flutter/flutter/pull/120077. I don't know if it's possible for me to see these flake numbers you have, but if it seems like that's made things worse (since it reverts the chance made here), please let me know!

**Pull request merged**
