### PR TITLE
Switch docs to docs.flutter.io

### PR DESCRIPTION
**Pull request by abarth**
That site is now live.

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
hotdamn.  lgtm

**Comment by Hixie** [comment]
nice!

Can we get an index page on that site? :-)

**Comment by Hixie** [comment]
(as in, the root URL isn't serving anything useful right now)

**Comment by abarth** [comment]
Sure, design me one and I can push it to prod for you.

**Comment by Hixie** [comment]
http://damowmow.com/temp/flutter-root.html

**Comment by abarth** [comment]
Live.

**Comment by abarth** [comment]
I had to take away the search box because it didn't seem to work.

**Pull request merged**
