### PR TITLE
[fuchsia] Change format of ffx call to debug spam.

### PR DESCRIPTION
**Pull request by akbiggs**
Fuchsia is seeing a large amount of
ffx analytics spam with the command
`ffx -T 30 target list --format s`. We
suspect it is coming from this file but are
not 100% sure. We are changing the format of this
call to verify that the spammed command also
changes in our analytics.

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
Pushed a merge from upstream to to fix the JWT error on cirrus

**Comment by akbiggs** [comment]
Thanks!

**Comment by christopherfujino** [comment]
Let me push a unit test fix, too

**Review by christopherfujino — COMMENTED** [review]
for consistency, should we also update line 88?

**Comment by akbiggs** [comment]
Updated that line now, thanks.

**Comment by christopherfujino** [comment]
Working to fix unit tests...

**Pull request merged**
