### PR TITLE
Run flutter tester with arch -x86_64 on arm64 Mac

### LINKED ISSUE #88106: flutter test --coverage is sporadically failing on M1 "hell: rosetta error: unexpectedly got a signal in sigtramp"
Our tests on M1 are often failing.

It only happens when using `--coverage`.

Unfortunately, the code is not open source, so I can't paste samples.

## Steps to Reproduce

1. Run `flutter test --coverage`.
2. Try a few times, it doesn't fail every time (about 30%, and we have a lot of tests).

**Expected results:** 

Tests complete fine.

**Actual results:** 
```
hell: rosetta error: unexpectedly got a signal in sigtramp
unhandled error during test:
(removed path)
Shell subprocess crashed with unexpected exit code -5.
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:224:73)
<asynchronous suspension>
#1      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
<asynchronous suspension>

unhandled error during finalization of test:
(removed path)
TestDeviceException(Shell subprocess crashed with unexpected exit code -5.)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:224:5)
<asynchronous suspension>
#1      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
<asynchronous suspension>
```

### PR DESCRIPTION
**Pull request by jmagman**
On ARM Macs, run the flutter_tester process with `arch -x86_64`.  It's already running in Rosetta, but we've had reports that this process fails with `rosetta error: unexpectedly got a signal in sigtramp` unless it's run with `arch -x86_64`. I don't really understand why, except that it's some Rosetta bug.

Fixes https://github.com/flutter/flutter/issues/88106

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by doc-rj-ebay** [comment]
Just a note -- it only fails when running with --coverage

**Comment by jmagman** [comment]
@doc-rj-ebay can you try on master?   The arm version available there.

**Comment by doc-rj-ebay** [comment]
> @doc-rj-ebay can you try on master? The arm version available there.

Thanks @jmagman and sorry, it was this other --coverage issue that I was experiencing: https://github.com/flutter/flutter/issues/103656

@jmagman Do you know if that issue is fixed in stable?

**Comment by jmagman** [comment]
> @jmagman Do you know if that issue is fixed in stable?

If you were hitting https://dart.googlesource.com/sdk/+/539cccd8234ee10fddca244d9855ce0e0e5d8c45 is in https://github.com/flutter/flutter/issues/103656 is in https://github.com/flutter/engine/pull/33528 is in https://github.com/flutter/flutter/pull/104316 which is in Flutter 3.3, released yesterday.  If you are still seeing issues, please file them!

**Pull request merged**
