### PR TITLE
Fix internationalization issues with cupertinoTextSelectionControls

### PR DESCRIPTION
**Pull request by songfei**
Fix internationalization issues with cupertinoTextSelectionControls, 
cupertino and material are on the same layer, I think they can call each other.

### CODE REVIEW

**Comment by xster** [comment]
Cupertino shouldn't depend on the Material package. We'll need a separate translation mechanism for Cupertino (https://github.com/flutter/flutter/issues/13452). For now, you can make changes to `CupertinoLocalization` and supply your own translation. Official translations will be coming in the next quarter.

**Comment by Hixie** [comment]
@songfei Are you interested in implementing the fix using `CupertinoLocalization`? (It's fine if you don't want to or don't have time, we'll get to it in due course!)

**Comment by jslavitz** [comment]
Merged in the fix in a different PR so I'm closing this!

**Comment by xster** [comment]
Thanks @jslavitz

**Pull request closed without merging**
