### PR TITLE
Remove superfluous words from comments

### PR DESCRIPTION
**Pull request by asashour**
This PR removes duplicate words on consecutive lines.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

**Review by yaakovschectman — APPROVED** [review]

**Review by QuncCccccc — APPROVED** [review]
LGTM

**Review by justinmc — APPROVED** [review]
LGTM 👍 

@asashour  Clever PR, did you write a regex for this?

**Review by loic-sharma — APPROVED** [review]

**Comment by asashour** [comment]
> LGTM 👍
> 
> did you write a regex for this?

Thsnks. Yes, for different types of comment separators.

**Comment by justinmc** [comment]
Good call, thanks for helping us keep our docs clean!

**Pull request merged**
