### PR TITLE
bugfix: Text overflow does not work correctly in Sized widgets

### LINKED ISSUE #25025: TextOverFlow bug
## Steps to Reproduce

```dart
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: SizedBox(
          width: 50.0,
          height: 50.0,
          child: Text(
            "a long long long long text, should be clip",
            overflow: TextOverflow.clip,
          ),
        ),
      ),
    );
  }
```

the text will be not clip correctly.

### PR DESCRIPTION
**Pull request by limengyun2008**
fixes #25025

### CODE REVIEW

**Comment by limengyun2008** [comment]
#25025

**Comment by limengyun2008** [comment]
I signed it!

**Comment by jason-simmons** [comment]
@Hixie any thoughts on the effects of this change?

**Comment by Hixie** [comment]
Seems reasonable.

**Comment by Hixie** [comment]
In addition to a test, we should also update the documentation to mention that ellipsis only applies to the space the paragraph thinks it has (i.e. based on max lines), but the shading is based on the actual space taken vs actual space available (i.e. based on constraints).

**Comment by goderbauer** [comment]
@limengyun2008 Are you able to add some tests for this and address the doc comment from above in the near future?

**Comment by goderbauer** [comment]
Superseded by https://github.com/flutter/flutter/pull/27892.

**Pull request closed without merging**
