### PR TITLE
Revert Ballistic & Clamping simulation updates

### LINKED ISSUE #110340: ListView Sliding abnormal flashing
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Slide up from the bottom

**Expected results:** normal upward

**Actual results:**  slide up from 19 and flash (bounce back) to 18

<details>
<summary>Code sample</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyWidget());
}

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<StatefulWidget> createState() => MyWidgetState();
}

class MyWidgetState extends State<StatefulWidget> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView.builder(
          itemBuilder: (context, index) {
            return Container(
              height: index * 30,
              color: Colors.primaries[index % Colors.primaries.length],
              child: Center(
                child: Text(
                  index.toString(),
                  style: const TextStyle(fontSize: 40),
                ),
              ),
            );
          },
          itemCount: 20,
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

Null

</details>

<details>
  <summary> flutter doctor -v logs</summary>

```

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel master, 3.1.0-0.0.pre.2486, on Microsoft Windows [版本 10.0.22000.856], locale zh-CN)
    • Flutter version 3.1.0-0.0.pre.2486 on channel master at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f477c8b184 (20 hours ago), 2022-08-25 10:28:08 -0700
    • Engine revision bd7a1e0b2b
    • Dart version 2.19.0 (build 2.19.0-138.0.dev)
    • DevTools version 2.16.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at D:\AndroidSDK
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at D:\VSSDK\IDE
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.70.2)
    • VS Code at C:\Users\autop\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] VS Code (version 1.71.0-insider)
    • VS Code at C:\Users\autop\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (5 available)
    • DBY W09 (mobile)  • DXQBB21C02222514   • android-arm64  • Android 10 (API 29)
    • DBY W09 (mobile)  • 192.168.8.208:5555 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [版本 10.0.22000.856]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 104.0.1293.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

https://user-images.githubusercontent.com/44134842/186911542-2167a4bc-881e-4c1d-9482-b019343e1acf.mp4

### PR DESCRIPTION
**Pull request by Piinks**
Fixes b/245621581
Fixes https://github.com/flutter/flutter/issues/110340

Original PR: #107735

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ x I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
RSLGTM :(

**Comment by fzyzcjy** [comment]
Hi, is there any possibility this is landed again? ClampingScrollSimulation indeed has weird behavior as mentioned here -> https://github.com/flutter/flutter/issues/113424

**Comment by godofredoc** [comment]
@Piinks fyi

**Comment by Piinks** [comment]
@fzyzcjy we aren't currently working on relanding this. There were a number of issues found with it, primarily those listed here:

Originating issues this PR tried to fix
- #11599
- https://github.com/flutter/flutter/issues/16371

Issues that caused the revert
- https://github.com/flutter/flutter/issues/110340
- As well as the fixed metrics mentioned here: https://github.com/flutter/flutter/issues/11599#issuecomment-1241019949
- and correctBy being broken, mentioned here: https://github.com/flutter/flutter/issues/11599#issuecomment-1250107127

If anyone wants to take a looks at these issues and try to reland this I would be happy to take a look. We do not have anyone actively working on this right now.

**Comment by fzyzcjy** [comment]
@Piinks Thanks I see

**Pull request merged**
