### PR TITLE
Mark flutter_gallery_instrumentation_test as flaky

### PR DESCRIPTION
**Pull request by DanTup**
See #18879.

Please merge for me if you're happy with this; it's getting late here so I'll be off v. soon.

### CODE REVIEW

**Comment by DanTup** [comment]
Windows Cirrus failure is "Agent is not responding!", so I've restarted it.

**Review by yjbanov — APPROVED** [review]

**Comment by yjbanov** [comment]
lgtm

**Comment by Hixie** [comment]
This test doesn't seem flaky. I think we can unmark it.

**Comment by DanTup** [comment]
You jinxed it :( Yellow 3 times in the last 6 runs.

screen shot 2018-07-31 at 8 37 12 am

- https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9lZTM5NjI3MmQzMjYzZWVjNDZjOTRiYjFmYTAwY2QyY2E3MmRkMWU3DAsSBFRhc2sYgICAgICA1AgM
- https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9hY2Y0YjZjMWFhNjMxZTVmYTYyOTliYTdlZjZkZmRmZTFmYTdkNmFiDAsSBFRhc2sYgICAgICAiAoM
- https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci81YjMwYjM5M2E4Y2Y3ZjAwOTJmMTcyNmM1YThmNzk4MzJiMGFkMGY4DAsSBFRhc2sYgICAgICAuAkM

**Pull request merged**
