### PR TITLE
Roll engine to 7f083e54fe75

### PR DESCRIPTION
**Pull request by liyuqian**
7f083e54f Don't implicitly fall through in switch statement (flutter/engine#5964)
c7ce6dd69 Apply translation to accessibility tree when in landscape (flutter/engine#5950)
aef94b73d Reland "Updated background execution implementation for Android" (flutter/engine#5954)
3421bca7a Roll src/third_party/skia 36216fb0acbc..177742435e52 (15 commits) (flutter/engine#5963)
9d1e67399 Temporarily add travis/analyze.sh back for Chrome bot (flutter/engine#5961)
4386afdaa Roll src/third_party/skia e6d0618f677c..36216fb0acbc (11 commits) (flutter/engine#5960)
7cef3da03 Roll src/third_party/skia 01d9a344b575..e6d0618f677c (1 commits) (flutter/engine#5958)
ad82cb154 Roll src/third_party/skia fdf05f4ff4e9..01d9a344b575 (1 commits) (flutter/engine#5957)
6ea410cfe Revert "Roll Dart to 17b54c76ce9b945c6f013ad08c19268409c0694a (flutter/engine#5955)" (#5956)
f20c58f65 Roll Dart to 17b54c76ce9b945c6f013ad08c19268409c0694a (flutter/engine#5955)
ed1938e99 Roll src/third_party/skia 641ac7daa81c..fdf05f4ff4e9 (3 commits) (flutter/engine#5953)
5f04e00d7 Remove travis directory (flutter/engine#5935)
5442c0a7d Revert "Updated background execution implementation for Android" (flutter/engine#5949)
a5215ce50 Add hasImplicitScrolling SemanticFlag and support in Android bridge (flutter/engine#5941)
4681351af Roll src/third_party/skia 6e487e67a3f3..641ac7daa81c (16 commits) (flutter/engine#5948)
bc885f319 Updated background execution implementation for Android
5770cbd2a Roll src/third_party/skia 12fb9cfeee07..6e487e67a3f3 (8 commits) (flutter/engine#5946)
f4464a8d9 Roll src/third_party/skia 2e77f54f46e8..12fb9cfeee07 (1 commits) (flutter/engine#5945)
c6baaaf75 Replace acquire+release thread annotation with excludes (flutter/engine#5944)
63ede2e35 Roll src/third_party/skia 59aabbcf3b0d..2e77f54f46e8 (1 commits) (flutter/engine#5943)
97aea093e Roll src/third_party/skia 71fe8baccc01..59aabbcf3b0d (1 commits) (flutter/engine#5942)
aaf4a9a24 Roll src/third_party/skia 4c3b63e289c5..71fe8baccc01 (3 commits) (flutter/engine#5940)

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Either I can land https://github.com/flutter/flutter/pull/20274 first, or you'll need to sync the framework changes

**Comment by liyuqian** [comment]
@jonahwilliams framework changes synced. I'm afraid that #20274 will never pass the windows_tests because the particular engine revision has no Windows artifacts.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
This roll seems to have made the `flutter_gallery__back_button_memory` markedly more flaky.

**Comment by liyuqian** [comment]
@Hixie Is it related with https://github.com/flutter/flutter/issues/19438 and maybe something in the Dart roll triggers it again? Anyway, I created https://github.com/flutter/flutter/pull/20393 to mark it as flaky to make our tree green.

**Comment by alexmarkov** [comment]
@liyuqian this particular engine roll doesn't have a Dart roll. Dart was rolled in https://github.com/flutter/engine/commit/f20c58f658a88e24f062cf7de921a44b9c8d4eaf and then reverted in the next commit https://github.com/flutter/engine/commit/6ea410cfea184632446a6bd784b3de38ed0ba757.

**Pull request merged**
