### PR TITLE
Revert "Roll Plugins from a9f34a1d528c to 1e2ffdb006e6 (1 revision)"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#94313

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20flutter_plugins/4133/overview
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20plugin_lint_mac/4793/overview

### CODE REVIEW

**Review by blasten — APPROVED** [review]

**Comment by jmagman** [comment]
I doubt this will re-open the tree, the failing test doesn't use the plugin roll SHA.

**Comment by jmagman** [comment]
Oh, actually it will help `Linux flutter_plugins` but not `Mac plugin_lint_mac`.
```
info - example/lib/web_view.dart:550:37 - Prefer const with constant constructors. - prefer_const_constructors
```
@bparrishMines plugins sheriff

**Comment by jmagman** [comment]
@mvanbeusekom re: lint error https://github.com/flutter/plugins/pull/4553

**Comment by jmagman** [comment]
The `Mac plugin_lint_mac` failure is due to url_plugin being federated.  I'll get a fix out.
https://github.com/flutter/plugins/commit/a456f6343840eba0d0b4de27e215f210bf4dbcc4

**Review by jmagman — APPROVED** [review]
LGTM to work around the linter issue.  This plugin roller should be turned off until it is resolved.

**Comment by jmagman** [comment]
> The `Mac plugin_lint_mac` failure is due to url_plugin being federated. I'll get a fix out. [flutter/plugins@a456f63](https://github.com/flutter/plugins/commit/a456f6343840eba0d0b4de27e215f210bf4dbcc4)

https://github.com/flutter/flutter/issues/94372

**Comment by jmagman** [comment]
Hm, this roll revert didn't fix `Linux flutter_plugins`
```
   info - example/lib/web_view.dart:550:37 - Prefer const with constant constructors. - prefer_const_constructors
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8829201417244925441/+/u/run_test.dart_for_flutter_plugins_shard_and_subshard_analyze/test_stdout

**Comment by jmagman** [comment]
I think it needs to be rolled to https://github.com/flutter/plugins/commit/6bc9a2bd62e5ac9ff36b0fddf77ece6fdddaeef6. We should instead merge https://github.com/flutter/flutter/pull/94352/.

**Comment by zanderso** [comment]
@jmagman To clarify, are you saying that we should abandon this PR, and instead merge https://github.com/flutter/flutter/pull/94352?

**Comment by jmagman** [comment]
> @jmagman To clarify, are you saying that we should abandon this PR, and instead merge #94352?

Yes, this isn't the right SHA to roll to, it didn't fix `Linux flutter_plugins `.  Actually #94352 had a failing ci.yaml roll test and all the tests were queued, and I don't know how to kick the tests.  I created an identical manual roll at https://github.com/flutter/flutter/pull/94375

**Pull request closed without merging**
