### PR TITLE
Fix TabBar jag when user interrupts ballistic scroll

### PR DESCRIPTION
**Pull request by giantsol**
## Description

TabBar sometimes jags when user interrupts ballistic scroll:

Almost at the end of the video, you can see a slight jagging. This happens because when user interrupts the ballistic scroll, `ScrollEndNotification` is called, but we don't update `_controller.offset` value as we do in `ScrollUpdateNotification`. This bug was found during another PR that I'd been working on: https://github.com/flutter/flutter/pull/60080#issuecomment-668004706

cc. @chunhtai 

<details>
  <summary>Reproducible code</summary>

```dart
void main() {
  runApp(Main());
}

class Main extends StatefulWidget {
  Main({Key key}) : super(key: key);

  @override
  _MainState createState() => _MainState();
}

class _MainState extends State<Main> with SingleTickerProviderStateMixin {
  final List<Tab> _tabs = <Tab>[
    Tab(text: 'Tab 1'),
    Tab(text: 'Tab 2'),
    Tab(text: 'Tab 3'),
  ];

  TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(vsync: this, length: _tabs.length);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          bottom: TabBar(
            controller: _tabController,
            tabs: _tabs,
            isScrollable: true,
            labelPadding: const EdgeInsets.symmetric(horizontal: 56),
          ),
        ),
        body: TabBarView(
          controller: _tabController,
          children: _tabs.map((Tab tab) {
            return Center(
              child: Text(tab.text),
            );
          }).toList(),
        ),
      ),
    );
  }
}
```

</details>

## Related Issues

None

## Tests

Added a test: `TabController's animation value should be in sync with TabBarView's scroll value when user interrupts ballistic scroll`

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by chunhtai** [comment]
the device lab test keep failing, can you see if you can rebase off latest master to resolve it?

**Comment by giantsol** [comment]
@chunhtai Oops, may I ask why this is closed?

**Comment by chunhtai** [comment]
@giantsol sorry i clicked the wrong button

**Comment by giantsol** [comment]
@chunhtai Hi! Is this waiting for the tree to go green? :)

**Comment by chunhtai** [comment]
> @chunhtai Hi! Is this waiting for the tree to go green? :)

yes! thanks for reminding

**Pull request merged**
