### PR TITLE
Add expandColumnIndex parameter to DataTable

### PR DESCRIPTION
**Pull request by jibbers42**
Add `expandColumnIndex` parameter to `DataTable`. This allows the user to specify a column to expand. If `expandColumnIndex` is `null`, then the default behavior of expanding the single, non-numeric column is retained (if one exists).

The PR is helpful when your `DataTable` is wider than the data it contains and you find the spacing awkward. This PR allows me to go from this:
image
to this:
image

While something along the lines of #77841 may be a better long term solution, I believe this PR handles a very common use case and will help in the meantime.

I was hoping to use tests of the existing functionality as guide for adding my tests, but I don't see that it's tested... I'm not sure where to start.

*List which issues are fixed by this PR. You must list at least one issue.*
This PR is inspired by #51799.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by HansMuller** [comment]
This seems like a reasonable tweak to the default behavior however a more general solution, where one could specify the flexibility of each column, seems like a better solution (and as noted earlier, see https://github.com/flutter/flutter/issues/77841). On the face of it the more general solution doesn't seem like it would be that difficult to implement?

**Comment by jibbers42** [comment]
> On the face of it the more general solution doesn't seem like it would be that difficult to implement?

Probably not for someone else 😅. I guess I'd start by looking into how `columnWidths` on `Table` works, but I don't really have time to dig into that right now and try to figure it out.

Would it make any difference if I said I didn't care if this feature was removed when someone implemented the more general solution? (Or at the least, if a `columnWidths` (or similar) were provided, then that could override this `expandColumnIndex`.)

**Comment by HansMuller** [comment]
> Would it make any difference if I said I didn't care if this feature was removed when someone implemented the more general solution? (Or at the least, if a columnWidths (or similar) were provided, then that could override this expandColumnIndex.)

That's what we'd prefer to avoid, creating a temporary feature that will become obsolete when a more general version of the same feature lands.  Of course if we could get ALL flutter developers to agree that they wouldn't care ... 😅.

**Comment by Hixie** [comment]
The right fix is probably to expose `columnWidths` from the underlying `Table` widget on the `DataTable` widget. I think the reason I didn't do that was that the spec for the material widget itself didn't suggest that that was ever a thing one would do? I forget.

I'm going to close this PR for now. I recommend opening an issue to track this topic so that we can discuss whether and how to fix it before submitting a PR. Thanks for the contribution!

**Comment by Patrick386** [comment]
Any news on improvements?

**Comment by Hixie** [comment]
@Patrick386 This is an abandoned PR, so there are unlikely to be updates here. As the note above says, the right fix is _probably_ to expose `columnWidths` from the underlying `Table` widget on the `DataTable` widget. If you are interested in submitting a fix, I recommend opening an issue to track this topic, maybe discussing it on our Discord (see the [contributing guide](https://github.com/flutter/flutter/blob/main/CONTRIBUTING.md) for the invite link), and then submitting a PR. (Filing an issue is an important step that was not used for this PR, which means we have not been tracking interest in this topic, nor had a place for people to discuss how to solve the issue.)

**Comment by jibbers42** [comment]
> @Patrick386 This is an abandoned PR, so there are unlikely to be updates here. As the note above says, the right fix is _probably_ to expose `columnWidths` from the underlying `Table` widget on the `DataTable` widget. If you are interested in submitting a fix, I recommend opening an issue to track this topic, maybe discussing it on our Discord (see the [contributing guide](https://github.com/flutter/flutter/blob/main/CONTRIBUTING.md) for the invite link), and then submitting a PR. (Filing an issue is an important step that was not used for this PR, which means we have not been tracking interest in this topic, nor had a place for people to discuss how to solve the issue.)

To be fair, I explained my proposal to issue https://github.com/flutter/flutter/issues/51799 (linked in the description) on Discord. This solution was approved (I think by you, but I don't recall without looking, maybe someone else on the team), then denied once implemented.

**Comment by Hixie** [comment]
I wouldn't say it was _approved_, I just [said](https://discord.com/channels/608014603317936148/608018585025118217/1025564468169678908) it looked good but would probably also need to be looked at by someone else (this was after a first version of the PR was posted, though). I also wouldn't say it was _denied_; further review uncovered additional issues and suggestions were made for where to go next with the PR. Software engineering is a collaborative endeavour and a back and forth like this is normal. You should see some of my PRs!

**Comment by jibbers42** [comment]
I guess I did explore the work for a simple version first, sorry, didn't remember that.

I probably misunderstood or was being overly optimistic regarding the "approval", my apologies.

**Comment by Hixie** [comment]
No apology necessary, I totally understand that it can be a bit daunting to work with a project of this size. For what it's worth if you do want to continue this work I'd be more than happy to support you through that!

**Pull request closed without merging**
