### PR TITLE
Add a way to get the furthest Navigator

### PR DESCRIPTION
**Pull request by xster**
#12107

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
Either this patch or the patch before it (https://github.com/flutter/flutter/commit/f6135107bcba92f02df6572d1a8be5e93863e6f6) regressed flutter_gallery_ios__transition_perf average_frame_build_time_millis significantly. Please revert this patch then determine the cause before relanding it. Thanks!

**Comment by Hixie** [comment]
It may also have caused a regression of complex_layout_scroll_perf_ios__timeline_summary ms average_frame_rasterizer_time_millis.

**Comment by xster** [comment]
I think this PR wasn't it based on the benchmarks' metrics after the revert

**Comment by Hixie** [comment]
Maybe it's https://github.com/flutter/flutter/pull/12578 then?

**Comment by Hixie** [comment]
I've got a revert for that one in https://github.com/flutter/flutter/pull/12661.

**Pull request merged**
