### PR TITLE
Fixed some analysis errors.

### PR DESCRIPTION
**Pull request by pylaligand**

### CODE REVIEW

**Comment by pylaligand** [comment]
Getting:
```
  error • Missing type arguments for generic method 'then<E>' at package:flutter/src/material/refresh_indicator.dart:311:8 • strong_mode_implicit_dynamic_method
  error • Missing type arguments for generic method 'then<E>' at package:flutter/src/widgets/animated_list.dart:294:26 • strong_mode_implicit_dynamic_method
  error • Missing type arguments for generic method 'then<E>' at package:flutter/src/widgets/animated_list.dart:329:26 • strong_mode_implicit_dynamic_method
3 errors found.
```

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
Why don't we catch this on Travis?

**Comment by pylaligand** [comment]
Might be because we are using different versions of Dart. Ours is very recent, and I know some lint changes were made in the past week.

**Comment by pylaligand** [comment]
Also, in Fuchsia lints/hints/warnings are all considered as errors.

**Comment by Hixie** [comment]
They're all considered errors for us, too, but we are on a month-old Dart. We plan to rev around the 20th.

**Pull request merged**
