### PR TITLE
newly created apps / plugins should use latest gradle dependencies

### PR DESCRIPTION
**Pull request by ened**
Currently, new plugin / app projects will cause Android Studio 3.2 to prompt the user for Gradle & Gradle Plugin updates, which causes:

1. Project warnings if the project uses kotlin due to a) old kotlin plugin version, b) inclusion of the deprecated kotlin "jre" package instead of the jdk package
2. Project build failures because AS will upgrade the gradle wrapper to 4.6 (which causes #22614 and perhaps #22297)

This PR updates the default project templates which fixes both.
Perhaps best to sweep once through all flutter components and upgrade all dependency versions?

### CODE REVIEW

**Comment by ened** [comment]
@sbaranov done & please see below:

Fixes #22945
Related to #22953 (@mit-mit could you kindly confirm?)
Fixes #22614
Closes #22470
Fixes #21816
Closes #19719
Fixes #19337

**Review by tvolkert — COMMENTED** [review]
Thanks the contribution @ened!

LGTM.  I'll wait for @sbaranov to review and approve, then we can merge on green.

**Comment by yjbanov** [comment]
Unfortunately I'll have to roll it back because our build bots are not yet upgraded to the Android SDK version needed by this change: https://github.com/flutter/flutter/pull/23263

**Comment by yjbanov** [comment]
Reverted. Let's try this again but have someone on the Flutter team upgrade the build machines prior to submitting.

**Comment by ened** [comment]
@yjbanov Oh no! Alrighty then, hope we can get the build bots upgraded soon. Once done I would prepare a similar PR for the flutter/plugins project (and update all dependencies).

**Comment by sbaranov** [comment]
Buildlab machines upgraded. Re-landed this as https://github.com/flutter/flutter/pull/23314.

**Pull request merged**
