### PR TITLE
Add Windows support to hello_world

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
Continuation of #84751 (cc @GroovinChip). That PR was closed due to being outdated. In the meantime, macOS support _has been added_. This PR adds Windows support.

The command I used to generate is:

```
flutter create --platforms=windows --template=app --project-name "hello_world" --org "io.flutter.examples" .
```

The running result on Windows looks like this:

image

Related: #84306

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
macOS support was added in https://github.com/flutter/flutter/pull/86534 afaic.

**Comment by Hixie** [comment]
see also https://github.com/flutter/flutter/pull/84899

**Comment by Hixie** [comment]
cc @cbracken for review

**Comment by christopherfujino** [comment]
I'm sorry we never got around to reviewing this. However I am unsure if this is actually worth doing, so I would recommend discussing whether or not we should do this on the issue.

**Pull request closed without merging**
