### PR TITLE
Unpin mysteriously pinned packages

### PR DESCRIPTION
**Pull request by Hixie**
Unpin mysteriously pinned packages.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM as long as tests are passing

**Comment by dnfield** [comment]
Looks like failure is related to camera - 0.7.0 is either broken or we need to update whatever is consuming it.

**Comment by dnfield** [comment]
My thought is we should either fix the app consuming camera, or fix camera and publish a working version :)

**Comment by bparrishMines** [comment]
I published a new version of `camera` that contained a fix to a critical bug this morning. I might be missing something, but which tests are failing because of `camera`?

**Comment by dnfield** [comment]
It's `test/integration.shard/deprecated_gradle_settings_test.dart` that's failing in `packages/flutter_tools`.  Something's going wrong when it tries to build the https://github.com/flutter/flutter/blob/master/dev/integration_tests/gradle_deprecated_settings/pubspec.yaml using camera 0.7.0.

**Comment by Hixie** [comment]
If you just launched a new version let me rerun the script and try again.

**Comment by Hixie** [comment]
This time it used camera 0.7.0+1.

**Comment by Hixie** [comment]
@bparrishMines this is what I'm seeing:
```
[   +1 ms] /b/s/w/ir/k/.pub-cache/hosted/pub.dartlang.org/camera-0.7.0+1/android/src/main/java/io/flutter/plugins/camera/DeviceOrientationManager.java:194: error: cannot find symbol
[   +2 ms]     if (VERSION.SDK_INT >= VERSION_CODES.R) {
[        ]                                         ^
[        ]   symbol:   variable R
[        ]   location: class VERSION_CODES
[        ] /b/s/w/ir/k/.pub-cache/hosted/pub.dartlang.org/camera-0.7.0+1/android/src/main/java/io/flutter/plugins/camera/DeviceOrientationManager.java:195: error: cannot find symbol
[        ]       return activity.getDisplay();
[        ]                      ^
[        ]   symbol:   method getDisplay()
[        ]   location: variable activity of type Activity
[        ] 2 errors
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':camera:compileDebugJavaWithJavac'.
[        ] > Compilation failed; see the compiler error output for details.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 33s
[   +5 ms] Gradle task assembleDebug failed with exit code 1
```

**Comment by Hixie** [comment]
Looks like with @blasten 's suggestions the tests pass again. I'll land once I've re-upgraded everything if it goes green again.

**Pull request merged**
