### PR TITLE
let the embedding maven engine dependency reference the storage proxy

### LINKED ISSUE #55134: Flutter maven repository (https://storage.googleapis.com/download.flutter.io) could be inaccessible in China
Hi Team:

The existing Flutter Maven repository: http://download.flutter.io or https://storage.googleapis.com/download.flutter.io couldn't be easily accessed in China now. I was wondering if there's any chance to migrate this Flutter Maven repository to google() since the maven.google.com is working for China, or using the `FLUTTER_STORAGE_BASE_URL` for instead? 

Thanks to @liudonghua123 for giving this feedback.
Cc/ @xster @InMatrix @zoeyfan.

Thanks!

### PR DESCRIPTION
**Pull request by xster**
Fixes https://github.com/flutter/flutter/issues/55134

### CODE REVIEW

**Comment by xster** [comment]
didn't look like there were any tests that mocked groovy scripts however... any tips?

**Review by blasten — APPROVED** [review]
LGTM

**Comment by blasten** [comment]
In an integration test, you could probably add an assert in a `build.gradle` script that checks that `project.repositories[..].maven.url` equals the one you passed from `FLUTTER_STORAGE_BASE_URL`.

**Comment by xster** [comment]
added test

**Pull request merged**
