### PR TITLE
Changed CupertinoSlidingSegmentedControl width to fill the encompassing widget

### PR DESCRIPTION
**Pull request by ManuLpz4**
## Description

* Added default and customizable outer padding feature to `CupertinoSlidingSegmentedControl` following the line of `CupertinoSegmentedControl`
* Removed inner padding feature from `CupertinoSlidingSegmentedControl` following the line of `CupertinoSegmentedControl` and the [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/controls/segmented-controls/)
* Added shrinkWrap parameter to `CupertinoSlidingSegmentedControl` allowing it to fit the inner content but expanded by default following the [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/controls/segmented-controls/)
* Added the necessary documentation and corrected some lines of the previous one
* Updated the `CupertinoSlidingSegmentedControl` test to match the new one

Before and after

<details>
  <summary>Code to reproduce the resizing issue</summary>

  ```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
    runApp(
      MaterialApp(
        theme: ThemeData.dark(), // Just to take care of your eyes
        home: HomePage(),
      ),
    );
}

class HomePage extends StatefulWidget {
    @override
    _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
    int groupValue = 0;

    @override
    Widget build(BuildContext context) {
      return Scaffold(
        body: Center(
          child: CupertinoSlidingSegmentedControl(
            groupValue: groupValue,
            onValueChanged: onValueChanged,
            children: {
              0: const Text('1'),
              1: const Text('2, thanks'),
              2: const Text('All of them!'),
            },
          ),
        ),
      );
    }

    void onValueChanged(int newValue) {
      setState(() {
        groupValue = newValue;
      });
    }
}
  ```
</details>

## Related Issues
The following issue is resolved by this PR:
* #62063

## Tests
Sorry for not editing the CupertinoSlidingSegmentedControl test in the first commit, it is my first PR and I didn't realize.

* Updated CupertinoSlidingSegmentedControl test to match the new one

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by LongCatIsLooong — COMMENTED** [review]
Thank you for this PR! Left a few comments regarding the new parameters.

It feels to me that this PR is a workaround for https://github.com/flutter/flutter/pull/62093.  If the developer sets `shrinkWrap` to true then they are still going to see the same issue I think?

**Comment by LongCatIsLooong** [comment]
IMO we need to do a measurement run during layout to determine the correct intrinsic width of each child to account for the potential width change when the child is highlighted, but I'm not sure how exactly. Any ideas? I'm thinking maybe we can make a separate widget for the intrinsic size calculation, so developers can wrap each segment in that widget when appropriate. The downside is the setup becomes more complicated, and it's going to be a breaking change.

**Comment by ManuLpz4** [comment]
@LongCatIsLooong First of all, thank you very much for taking the time to review the the PR and bring me the corresponding feedback. It helps me a lot to learn and improve for contributing in a more efficient way.

I'll be working hard on everything you told me, it will take me a while but I didn't want to leave it unanswered. 💙

**Comment by LongCatIsLooong** [comment]
@ManuLpz4 sorry my previous comment is confusing. 

I think one possible way to fix the varying width issue would be to layout each child with increased font weight (i.e. highlighted) first, get their widths, and calculate the overall width of the segmented control based on those widths. My initial concern was since we allow arbitrary widgets in each segment, some widgets' layout processes may change their internal states, so the measurement run previously described may not get us the correct width of each child. But I've been told that `RenderFlex` does something similar so this should be a valid approach.

Instead of adding the measurement run logic to `CupertinoSlidingSegmentedControl` directly, we might be able to create a new widget to wrap each child and does the measurement run, so we only make minimal changes to the existing segmented control code. Do you think this could work?

**Pull request closed without merging**
