### PR TITLE
We were looking for HapticFeedback in the wrong service bundle

### LINKED ISSUE #3795: No vibration
In my own app and in the MaterialGallery date and time pickers I get no vibration, despite calls to HapticFeedback.vibrate().

Device: LG LS980

All the vibration-related settings on the device seem to be enabled.  

## Flutter Doctor

[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/vinteresting/dev/github/flutter
    • Framework revision 5460e94488 (6 days ago), engine revision 76d5cf230a

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /home/vinteresting/dev/android-sdk-linux
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2

### PR DESCRIPTION
**Pull request by abarth**
Fixes #3795

### CODE REVIEW

**Comment by abarth** [comment]
@chinmaygarde Same problem we had with path provider.

**Comment by eseidelGoogle** [comment]
Does this make a log on connect failure which we should have been catching on our buildbot?  (in our flutter drive test).

**Comment by abarth** [comment]
> Does this make a log on connect failure which we should have been catching on our buildbot?

The behavior was correct according to the design intent of mojo, similar to Objective-C silently swallows messages sent to nil.

**Comment by abarth** [comment]
@jason-simmons

**Comment by jason-simmons** [comment]
LGTM

**Pull request merged**
