### PR TITLE
Turn back on macOS shard Cirrus caching

### PR DESCRIPTION
**Pull request by jmagman**
## Description

This was previously attempted in https://github.com/flutter/flutter/pull/50496 and reverted in https://github.com/flutter/flutter/pull/50661 due to ongoing Cirrus macOS networking flakes causing constant recaching.

[Networking is much improved](https://github.com/flutter/flutter/issues/50730), try again.

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change
- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
In this commit all_flutter_cache took 1:36, pub cache took 1:40, and setup took 1:22: https://cirrus-ci.com/task/6571153200250880
For comparison, this master task without a cache setup took 3:16 https://cirrus-ci.com/task/5005830894387200

Based on this random example, that means we'll save ~2 minutes on a cache hit and lose ~1:30 on a cache miss.

**Comment by jmagman** [comment]
Looks like still a no-go on this since unarchiving the cache is failing, retrying, failing again, and re-populating.
Here's `all_flutter_cache` taking 9 minutes:
[all_flutter_cache.log.txt](https://github.com/flutter/flutter/files/4258840/all_flutter_cache.log.txt)

**Comment by christopherfujino** [comment]
> Looks like still a no-go on this since unarchiving the cache is failing, retrying, failing again, and re-populating.
> Here's `all_flutter_cache` taking 9 minutes:
> [all_flutter_cache.log.txt](https://github.com/flutter/flutter/files/4258840/all_flutter_cache.log.txt)

:(

**Pull request closed without merging**
