### PR TITLE
[WIP] Support virtual layer to reduce the cost of annotations

### PR DESCRIPTION
**Pull request by dkwingsmt**
## Description

This PR introduces a new concept called _virtual layer_. It's a kind of layer that, although taking a spot in the layer tree, performs rendering on its parent. This change improves the performance of mouse detection on Web. 

### Problem
Currently some layers in the layer tree do not participate in rendering, most notably `AnnotatedRegionLayer`, instead they provide utilities such as metadata. However, these layers are inserted with `pushLayer`, which interrupts the recording and creates an unnecessary `PictureLayer` despite providing nothing new in terms of rendering.
```
// When there are only rendering layers A and B
————  A (creates a picture layer)
————  B (drawn on A's picture layer)

// When annotated region layer X is inserted
————  A (creates a picture layer)
----  X (calls pushLayer, which stops rendering)
————  B (creates a picture layer)
```

This extra `PictureLayer` does not affect mobile or desktop much, but severely hurts web's performance (https://github.com/flutter/flutter/issues/41194). The extra `PictureLayer`s can be demonstrated by the following log (details omitted):

```
TransformLayer#81d1f
│
├─child 1: OffsetLayer#3c42a
│ │
│ └─child 1: OffsetLayer#a9df3
│   │
│   └─child 1: PhysicalModelLayer#0dfdd
│     │
│     ├─child 1: OffsetLayer#ed976
│     │ │
│     │ ├─child 1: OffsetLayer#7c638
│     │ │ │
│     │ │ └─child 1: OffsetLayer#ed5a9
│     │ │   │
│     │ │   └─child 1: ClipRectLayer#a17ae
│     │ │     │
│     │ │     ├─child 1: OffsetLayer#654f5
│     │ │     │ │
│     │ │     │ ├─child 1: AnnotatedRegionLayer<MouseTrackerAnnotation>#00f36
│     │ │     │ │ │ value: MouseTrackerAnnotation#346f2(callbacks: enter hover exit)
│     │ │     │ │ │ size: Size(40.0, 40.0)
│     │ │     │ │ │ offset: Offset(0.0, 0.0)
│     │ │     │ │ │
│     │ │     │ │ └─child 1: PictureLayer#17a3f
│     │ │     │ │     paint bounds: Rect.fromLTRB(0.0, 0.0, 1257.0, 40.0)
│     │ │     │ │
│     │ │     │ ├─child 2: AnnotatedRegionLayer<MouseTrackerAnnotation>#990b7
│     │ │     │ │ │ value: MouseTrackerAnnotation#a2bd9(callbacks: enter hover exit)
│     │ │     │ │ │ size: Size(40.0, 40.0)
│     │ │     │ │ │ offset: Offset(40.0, 0.0)
│     │ │     │ │ │
│     │ │     │ │ └─child 1: PictureLayer#05c4f
│     │ │     │ │     paint bounds: Rect.fromLTRB(0.0, 0.0, 1257.0, 40.0)
│     │ │     │ │
│     │ │     │ ├─child 3: AnnotatedRegionLayer<MouseTrackerAnnotation>#7b8aa
│     │ │     │ │ │ value: MouseTrackerAnnotation#e08c8(callbacks: enter hover exit)
│     │ │     │ │ │ size: Size(40.0, 40.0)
│     │ │     │ │ │ offset: Offset(80.0, 0.0)
│     │ │     │ │ │
│     │ │     │ │ └─child 1: PictureLayer#9eb2e
│     │ │     │ │     paint bounds: Rect.fromLTRB(0.0, 0.0, 1257.0, 40.0)
[...]
```

### Analysis
`PaintingContext`'s `pushLayer` method always stops the current recording and creates a new painting context for its child, which creates a new `PictureLayer` if later required to paint on. The process makes sense since a new layer used to always mean a new canvas. But now that a new layer might not render at all, we should allow it to skip the process of stopping recording and creating context.

To fix this, we will add a new class `VirtualLayer` that extends from `ContainerLayer`, which are classes that promise not to render at all. It'll be the new superclass of `AnnotatedRegionLayer`.

`PaintingContext` will allow pushing `VirtualLayer` to the layer tree _without_ switching context, i.e. the virtual layer will use the same painting context as its parent. In this way, rendering objects on the virtual layer will actually render on the parent layer, while the tree structure is still kept so that annotation finder works as before.

```
// By making X a virtual layer
————  A (creates a picture layer)
----  X (calls pushVirtualLayer, which doesn't stop recording)
————  B (renders on A's picture layer)
```

### Details
`VirtualLayer` must not be used as root, must not own an engine layer, and is kept in the layer tree only for structural purpose.

`PaintingContext`'s `_containerLayer` is no longer a fixed layer, but the top of a stack of layers. The stack bottom is the non-virtual layer that the context  was created with, while all other layers must be virtual layers.

`PaintingContext` will have a new public method, `pushVirtualLayer`, which is similar to `pushLayer` but only accepts a `VirtualLayer`. This method pushes the virtual layer to the `_containerLayerStack`, and, without stopping the current recording and creating a context, calls the painter with the current context.

### Results
Through testing, this PR successfully fixes the performance regression of `MouseRegion` on Web. The layer tree goes (properties omitted):
```
TransformLayer#f4fef
│
├─child 1: OffsetLayer#9c876
│ │
│ └─child 1: OffsetLayer#c3e1e
│   │
│   └─child 1: PhysicalModelLayer#86741
│     │
│     ├─child 1: OffsetLayer#85029
│     │ │
│     │ ├─child 1: OffsetLayer#aead1
│     │ │ │
│     │ │ └─child 1: OffsetLayer#1ad22
│     │ │   │
│     │ │   └─child 1: ClipRectLayer#43994
│     │ │     │
│     │ │     ├─child 1: OffsetLayer#8fefd
│     │ │     │ │
│     │ │     │ ├─child 1: AnnotatedRegionLayer<MouseTrackerAnnotation>#93b67
│     │ │     │ │   value: MouseTrackerAnnotation#4a1db(callbacks: enter hover exit)
│     │ │     │ │   size: Size(40.0, 40.0)
│     │ │     │ │   offset: Offset(0.0, 0.0)
│     │ │     │ │
│     │ │     │ ├─child 2: PictureLayer#7dce7
│     │ │     │ │   paint bounds: Rect.fromLTRB(0.0, 0.0, 1257.0, 40.0)
│     │ │     │ │
│     │ │     │ ├─child 3: AnnotatedRegionLayer<MouseTrackerAnnotation>#9e514
│     │ │     │ │   value: MouseTrackerAnnotation#03ab7(callbacks: enter hover exit)
│     │ │     │ │   size: Size(40.0, 40.0)
│     │ │     │ │   offset: Offset(40.0, 0.0)
│     │ │     │ │
│     │ │     │ ├─child 4: AnnotatedRegionLayer<MouseTrackerAnnotation>#6c21e
 [...]

```

### Alternatives
Alternative names:
- `pushMetadata` and `MetadataLayers`

Alternative level of encapsulation:
- Instead of pushing a virtual layer, push an annotation and let `PainterContext` construct a virtual layer privately. It prevents virtual layer classes being extended and added rendering utilities, at the price of requiring new methods if we want a new kind of metadata.

## Related Issues

*Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR.*

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behaviour with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by yjbanov** [comment]
Wouldn't it be simpler to allow leaf layers to have virtual sub-trees of layers? This way we do not restructure the layers at all, and we do not introduce a concept of "root container layer".

Example:

```
OffsetLayer
  AnnotatedRegionLayer #1
    OpacityLayer
      PictureLayer
        AnnotatedRegionLayer #2
          SomeOtherVirtualLayer
       AnnotatedRegionLayer #3
```

`OffsetLayer` is a normal `ContainerLayer` that can have arbitrary children. `AnnotatedRegionLayer` is a virtual layer. It may contain arbitrary children when composited. However, when it is a descendant of a leaf layer, such as `PictureLayer` in the example, it may only contain virtual children. In the example, `AnnotatedRegionLayer #2`, `AnnotatedRegionLayer #3`, and `SomeOtherVirtualLayer`, are all virtual layers that happily exist as children of `PictureLayer`, which is fine since they are virtual.

**Comment by yjbanov** [comment]
Here's an example of an illegal layer tree, which we can enforce using asserts:

```
OffsetLayer
  PictureLayer
    OpacityLayer
```

This is illegal, because `OpacityLayer` is not virtual.

**Comment by yjbanov** [comment]
BTW, whether a layer is virtual or not could be a boolean field on the `ContainerLayer` instead of a special type. This way, an `OffsetLayer` could be used as a virtual layer. All it does is offset its children, and if all its children are virtual it does not need to create an engine layer.

**Comment by dkwingsmt** [comment]
The reason I make `VirtualLayer` a special class is to enforce at compile time that only virtual layers can be called with `pushVirtualLayer`, since it bypasses the `stopRecording` and should only be used on layers that do not render.
That being said, your way might also be feasible, since I can change `Layer` so that `addToScene` is only called when the layer is not virtual, although I'm a little concerned that it might be confusing (why doesn't this picture layer paint... wait, it's virtual!), and also I don't know why we would like so many different kinds of virtual layers.

The reason I only allow container layers to do it is because `ContainerLayer` has complete support of `append`. How can arbitrary layers being pushed onto without copying the entire `append` system? The idea is that virtual layers are still valid members of the layer tree, it's just they're treated specially by `PaintingContext` in that they reuse the canvas of their parents.

**Review by goderbauer — COMMENTED** [review]
It seems complex/confusing to have layers that don't behave like actual layers.

As an idea (i haven't thought this fully through): Could we leave the Layer tree alone and instead introduce an annotation concept that's separate from (but connected to) the layer tree? An annotation could be added to a Layer, but it does not change the shape of the tree. When finding an annotation, you'd walk the layer tree as usual and for each layer check its list of annotations to see if there's anything in there that matches your search.

To take Yegor's example from https://github.com/flutter/flutter/pull/43646#issuecomment-547661080 the tree would look something like this:

```
OffsetLayer ------- [Annotation #1]
    OpacityLayer
      PictureLayer ---- [Annotation #2, Annotation #3]
```

**Comment by dkwingsmt** [comment]
@goderbauer It was my initial thought too. I turned to the virtual layer design for the following reasons:

Annotations are not just simple children that belong to a layer in a flat way; they are structured in a tree. See the following example:
```
A    (Parent layer)
| \
m  n (Two annotation layers; m is in front of n)
|
B    (A subtree that contains annotations)
```
Since they are structured in a tree, 
- If `B` is opaque, then `A.findAllAnnotations` will result in `[B, m]`
- If `B` is not opaque, then `A.findAllAnnotations` will result in `[B, m, n]`

If annotations are list-like properties of the parent layer, then this behavior can't be achieved.

An alternative design is for the parent layer to own an annotation tree. But it comes at two compexities:
1. Building a tree requires a lot of extra code, since `AbstractNode` provides limited support for a tree.
2. The annotation tree must also remember the "exits", i.e. layers that each leaf annotation might contain, in order to achieve the aforementioned behavior. This can be illustrated as below:

```
A, whose `annotation` is .
|                        | \
|                        m  n
|                        |
|                        B
| 
B
```

I made limited attempt before realizing it'd be very complicated.

**Comment by dkwingsmt** [comment]
On the other hand, the virtual layer design is fully compatible with the current annotation and layer system, no breaking at all. The render object only needs to change `pushLayer` to `pushVirtualLayer`, which is optional for performance.

**Comment by goderbauer** [comment]
Hm, right. I forgot about the concept of opaqueness.

Could we solve that by remembering the child after which an annotation should be visited? In your example from https://github.com/flutter/flutter/pull/43646#issuecomment-548114259, we'd get something like this:

A ---- {null: [m], B: [n]} (let's call this map annotations)
|
|
B

Annotations are stored as a map from "child layer" to "annotations to process before visiting that child layer" (and null or any other special marker indicates: process these annotations before visiting any children).

So, when you search for annotations and arrive at A, you'd process them in the following order annotations[null], child[0], annotations[child[0]], child[1], annotations[child[1], etc.

**Comment by dkwingsmt** [comment]
Sorry if I misunderstand your proposal, but it seems to me that it doesn't properly handle more complicated situations, such as when layer A has:
```
<root>
|——————
| | | |
m n o p
|   |
B   C
```

**Comment by goderbauer** [comment]
In your example, lower case letters are annotations and upper case is for actual Layers? Woudn't that just turn into:

Layer Tree:
```
  A
/ | \
B C D
```

Map annotation = {null: [m], B: [n, o], C: [], D: [p]}

**Comment by dkwingsmt** [comment]
I get what you mean. 
(Yes, lower cases are annotations, upper cases are layers.)

So your idea is basically a pre-processed sequence of depth first search. But it can't tell the difference between following scenarios:
```
<root>
 / |
B  m
```
- If `B` is opaque, result is `[B]`
- If `B` is not opaque, result is `[B, m]`

```
<root>
 |
 m
 | 
 B
```
- If `B` is opaque, result is `[B, m]`
- If `B` is not opaque, result is `[B, m]`

Both scenarios have layer tree
```
A
|
B
```
and `mapAnnotation = {null: [], B: [m]}`

**Comment by goderbauer** [comment]
The second one would be `mapAnnotation = {null: [m], B: []}`, so you'd visit m before B.

**Comment by dkwingsmt** [comment]
Nope, the algorithm visits children before the node itself.

**Comment by yjbanov** [comment]
@goderbauer 

> It seems complex/confusing to have layers that don't behave like actual layers.

This ship might have sailed already. We already have several layers that do not create engine layers. But, of course, it does not mean that we should make the situation worse. Therefore I'm still in favor of maintaining annotations in a separate tree. After all, annotations are mere optimizations, so any design that conflates it with the compositor layer tree feels wrong.

@dkwingsmt 

> I'm a little concerned that it might be confusing (why doesn't this picture layer paint... wait, it's virtual!), and also I don't know why we would like so many different kinds of virtual layers.

I'm not sure how this situation can happen. A picture layer can never be virtual. In fact a layer must choose whether it is virtual or not at construction time, so the field would be `final`. In addition, a `PictureLayer` would not even allow you to specify it. It will hard-code the value to `false`. Pseudo-code:

```dart
class Layer {
  Layer(this.isVirtual);
  final bool isVirtual;
}

class PictureLayer extends Layer {
  PictureLayer() : super(false);
}
```

**Comment by dkwingsmt** [comment]
Close this PR in favor of an alternative design.

**Pull request closed without merging**
