### PR TITLE
Revert "Fix version command for certain git workflows"

### LINKED ISSUE #52121: analyzer benchmark mega_gallery_watch_maximum regression
Screenshot 2020-03-06 at 08 56 05

Started at https://github.com/flutter/flutter/pull/52062. If that's really the culprit, I'd say it's the test and we should re-baselne.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#52062

This regressed the performance of all flutter commands, including https://github.com/flutter/flutter/issues/52121 and flutter_test_performance

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM.

I think we're going to have to take some kind of performance hit for this, but we can probably optimize this. For now we can revert and try to figure out a more optimal way to make this correct.

**Comment by jonahwilliams** [comment]
I don't think we should take a performance hit for _everyone_ for a non-standard workflow

**Comment by dnfield** [comment]
Yeah, it might be enough to just run this for `flutter doctor` rather than every call to `--version`, or maybe there's some way we can check some cache information more rapidly before actually fetching the upstream.

**Comment by jonahwilliams** [comment]
The tests passed in https://cirrus-ci.com/build/5163935233998848, but the checks didn't update. Landing

**Pull request merged**
