### PR TITLE
Support ANDROID_SDK_ROOT in addition to ANDROID_HOME

### PR DESCRIPTION
**Pull request by DanTup**
I don't know if we need changes outside of this repo, but this should address #15114 which relates to our use of ANDROID_HOME which is now deprecated.

The change currently still prefers ANDROID_HOME since that's what the SDK appears to do:

https://developer.android.com/studio/command-line/variables

> If *ANDROID_HOME* is defined and contains a valid SDK installation, its value is used instead of the value in *ANDROID_SDK_ROOT*.

The `flutter doctor` output will list both variables, so aid troubleshooting if something seems wrong.

Note: This changes the Cirrus script to set *ANDROID_SDK_ROOT* since that's now our "preferred" option (even if we check the other first) - everything seems to pass on my fork, but I don't know if there are any other implications of no longer having ANDROID_HOME set (for ex. in anything that only runs on certain branches).

(cc @dnfield since your name is on a comment about ANDROID_HOME in here!)

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by DanTup** [comment]
@gspencergoog there's a mention of using `ANDROID_HOME` for Fastlane (https://flutter.io/docs/deployment/fastlane-cd). Is this just because it calls SDK commands, or might there be some requirement to have `ANDROID_HOME` set for it to work (is it possible to test this before landing?)

**Comment by DanTup** [comment]
(no idea why accepting your text change resulted in these failed builds... I'll rebase in the hope it's something already fixed elsewhere)

**Comment by gspencergoog** [comment]
I don't know about the Fastlane question.  I think it probably executes some Android SDK commands, but I'm not sure.  @xster, do you know?

**Comment by DanTup** [comment]
I found in some fastlane code it checks both variables:

https://github.com/fastlane/fastlane/blob/c2fa5335777921dc14ab751f28a8a6c07dc4d5ef/fastlane/lib/fastlane/helper/adb_helper.rb#L19

So I think they're probably handling both. @gspencergoog @xster do you think it's safe to land this, or should we try and find some way of testing fastlane locally? (I don't know what's involved).

**Comment by gspencergoog** [comment]
I think it's probably safe to land: the code falls back, so it should work whether ANDROID_SDK_ROOT or ANDROID_HOME are set, and we can just revert or add ANDROID_HOME back into .cirrus.yml if there's something we're missing.

**Pull request merged**
