### PR TITLE
Try to make this test less flaky.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by mravn-google** [comment]
Flutter frame rate calibration can obviously be made more accurate. I'm not sure it matters that much to this test though. The recent test failures seem to have been caused by frame production on the Java side being too fast due to rounding in the integer expression `1000 / fps`. When the desired frame rate exceeds 112 we get 1000/fps=8ms between frames, and the Java side then produces frames at 125fps rather than the 112 requested...

**Comment by Hixie** [comment]
If you think the test as-is will be stable enough then I'm happy to close this without landing. :-)

**Comment by mravn-google** [comment]
I appreciate the debug output and the formatting fixes, so I think you should land at least those changes. My only (minor) concern is that the improved calibration accuracy comes at the cost of slower test execution and doesn't seem to be needed. I may be wrong here (we'll see in a few days), but the iOS counterpart has been doing fine for quite some time.

**Review by mravn-google — APPROVED** [review]

**Comment by Hixie** [comment]
At most this adds 30 seconds (the old test timeout was 30 seconds, the new timeout is 60 seconds), which is a small amount relative to the overhead of running a test at all, so I'm not too worried about the extra time. We can always tone it back a bit if we find it's slowness is an issue.

I'll land it as-is for now.

**Pull request merged**
