### PR TITLE
Always write full timeline before summary

### PR DESCRIPTION
**Pull request by dnfield**
The timeline API for the devicelab currently expects tests to separately call writing the full timeline and the summary. The order of these is important, since summarizing can fail if no frames were produced.  However, it's always beneficial to write the full timeline first in that case so that we can still try to figure out what, if anything, showed up in the timeline.

Expected to help with https://github.com/flutter/flutter/issues/79097 and some related issues, particularly with large_image_changer which had this in the wrong order.

I will be filing a separate CL to update the recipe to set an env var so these get picked up by luci.

@zanderso @jmagman @godofredoc

### CODE REVIEW

**Comment by dnfield** [comment]
I would like to land this even if the tree is red, but I would like to land it after the CL that starts uploading timelines to luci.

**Comment by dnfield** [comment]
We apparently have customer(s) using this API, so I'm deprecating it instead of removing it.

**Review by zanderso — APPROVED** [review]

**Comment by dnfield** [comment]
(I will land this as long as flutter-build is the only thing that's red)

**Comment by dnfield** [comment]
Blocked by https://github.com/flutter/gallery/pull/469

**Comment by dnfield** [comment]
Blocked by https://github.com/flutter/flutter/pull/79310

**Pull request merged**
