### PR TITLE
Make the StockHome TabBar selection persistent

### LINKED ISSUE #671: Tabs forget which tab there were showing
They should use PageStorage to store the current tab much like scrollables do with scroll position.

1. Launch stock app.
2. Switch tabs to PORTFOLIO.
3. Tab a row.
4. Wait for the transition to complete.
5. Hit back. The MARKET tab is selected.

cc @HansMuller

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes https://github.com/flutter/flutter/issues/671

### CODE REVIEW

**Comment by abarth** [comment]
This isn't the right fix.  We should teach TabBar how to persist this data in PageStorage.  Check out how Scrollable saves its scroll offset.

**Comment by HansMuller** [comment]
TabBar doesn't own its TabBarSelection the app or page does. In this case I think StockHome would be the logical owner, so I can have it use PageStorage to save the TabBarSelection.

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
Can the TabBarSelection actually be an Inherited widget in the tree itself? Then the tab bar and tab view could crawl up a bit instead of being given a TabBarSelection; and the TabBarSelection could crawl up and find the page storage.

**Comment by HansMuller** [comment]
Making the TabBarSelection an InheritedWidget sounds like the right thing to do. If it's OK with you, I'll commit this change, just to fix the bug, and then do the inherited widget.

**Comment by Hixie** [comment]
Oh sure there's no reason to do that in this PR. Feel free to just file a bug for it too.

**Comment by HansMuller** [comment]
TabBarSelection should be an InheritedWidget
https://github.com/flutter/flutter/issues/835

**Pull request merged**
