### PR TITLE
Revert "Update typedef syntax to use Function notation and turn on lint for old notation. (#18035)"

### PR DESCRIPTION
**Pull request by gspencergoog**
This reverts part of commit 3258602073c6a05b1b051fddf644cba92116694b because we're running into https://github.com/dart-lang/sdk/issues/33169

### CODE REVIEW

**Comment by gspencergoog** [comment]
Actually, I'm tempted instead to just revert the changes to the six typedef instances that use @required (and turn of the lint) until Dart 1 support is removed.  Sound OK?

**Comment by Hixie** [comment]
I'd rather we be consistent throughout. I don't want to have half the code on one and half on the other, and I'd rather we not have some code on one and some on the other without a lint to force us one way or the other.

Waiting a week to do this will be fine. :-)

**Comment by gspencergoog** [comment]
There are only two instances of this...

**Comment by gspencergoog** [comment]
OK, I'm just going to revert and we'll re-land it next week when Dart1 is turned off.

**Comment by gspencergoog** [comment]
TBR @goderbauer

**Review by goderbauer — COMMENTED** [review]
LGTM

**Pull request merged**
