### PR TITLE
Extract Sample code into examples/api

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This extracts the sample code out from the API doc comments, and places them in separate files on disk, allowing running of the examples locally, testing them, and building of slightly larger examples.

## Design Doc

- This is to address the velocity project "Sample code testing"
- Based on [this design doc](https://flutter.dev/go/testing-code-samples).

## Tests

- This is just moving existing sample code around, no logic has changed.

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

**Review by HansMuller — APPROVED** [review]
LGTM

I understand that calling the examples `slider.0.dart` serves the process which automatically extracts the code from the API docs.  If there was a way to choose to give examples more meaningful names, like slider.custom_thumb.dart, then developers digging around in the example directories might have an easier time finding the sample they were looking for. 

We could do much more of course. Examples could include a section that provided a title, a one-line description, and a longer description, then we could generate README.md files that helped with navigation. We'll have to see how developers end up using the example code. It's possible that they will not need navigation help; that the API docs will be enough.

One other related issue: if someone wants to create a link from a (say) StackOverflow question to an example, what sort of stable URL would they create? Or would we prefer that people just point to the API doc pages and let readers find the sample that's being referred to from there?

**Comment by gspencergoog** [comment]
> I understand that calling the examples slider.0.dart serves the process which automatically extracts the code from the API docs. If there was a way to choose to give examples more meaningful names, like slider.custom_thumb.dart, then developers digging around in the example directories might have an easier time finding the sample they were looking for.

They already are named after the symbol they are attached to.  For instance, the first example on `DeletableChipAttributes.onDeleted` in `chip.dart` resides in: `examples/api/lib/chip/deletable_chip_attributes.on_deleted.0.dart`

Are you just saying that you'd rather they weren't indexed and had readable names instead? That's easy enough to do, we would just need to add a "--name" argument to the snippets tool. It would require changes in how samples are detected by the IDE code (the code that puts up a banner right now telling you that there are examples to be browsed), since that would change the name of the output file. And we currently have a situation (a bug) where the stable docs are pointing to master examples, so until the next stable release, we'll break all the stable examples.

> We could do much more of course. Examples could include a section that provided a title, a one-line description, and a longer description, then we could generate README.md files that helped with navigation. We'll have to see how developers end up using the example code.

This would be pretty easy to add, except for the part where we have to come up with 300+ summaries of the existing samples. :-) I'd rather not generate a separate README.md for each example, though: it would double the number of files in the examples directory, and it would be redundant with the description information that is in the API doc comment. I could maybe see adding it to a comment at the top of the example file, but it would still be redundant in that case.

> One other related issue: if someone wants to create a link from a (say) StackOverflow question to an example, what sort of stable URL would they create? Or would we prefer that people just point to the API doc pages and let readers find the sample that's being referred to from there?

I think the API doc page would be the right URL.  They could point to the file in our repo on GitHub if they want, but that might not be stable if the examples are reordered (unless we implement naming of samples).

**Comment by HansMuller** [comment]
> They already are named after the symbol they are attached to. For instance, the first example on DeletableChipAttributes.onDeleted in chip.dart resides in: examples/api/lib/chip/deletable_chip_attributes.on_deleted.0.dart
> 
> Are you just saying that you'd rather they weren't indexed and had readable names instead? That's easy enough to do, we would just need to add a "--name" argument to the snippets tool. It would require changes in how samples are detected by the IDE code (the code that puts up a banner right now telling you that there are examples to be browsed), since that would change the name of the output file. And we currently have a situation (a bug) where the stable docs are pointing to master examples, so until the next stable release, we'll break all the stable examples.

The case I was concerned about was examples included with the class API doc for widgets/components like Scaffold. If developers do end up digging around in the  examples/api/lib/scaffold directory, giving the examples evocative names (suffixes) might make the digging a little easier.

**Comment by HansMuller** [comment]
> This would be pretty easy to add, except for the part where we have to come up with 100+ summaries of the existing samples. :-) I'd rather not generate a separate README.md for each example, though: it would double the number of files in the examples directory, and it would be redundant with the description information that is in the API doc comment. I could maybe see adding it to a comment at the top of the example file, but it would still be redundant in that case.

I agree that generating README files probably (at whatever level) probably would help tremendously. Developers are most likely to find examples via our API doc or via search (via things like StackOverflow).

**Comment by HansMuller** [comment]
> The examples on the API docs site already have stable links you can use (the "link" icon). Like this one: https://api.flutter.dev/flutter/widgets/Shortcuts-class.html#widgets.Shortcuts.2

That's perfect

**Pull request merged**
