### PR TITLE
Update to Dart SDK `1.19.0-dev.7.0`.

### PR DESCRIPTION
**Pull request by pq**
- bumps Dart SDK to `1.19.0-dev.7.0`
- removes now defunct `package-symlinks` pub arg (now renamed and defaulting to true)

/cc @devoncarew @Hixie

### CODE REVIEW

**Comment by pq** [comment]
Note that this introduces a bit of version skew with our `analyzer` dependency which we can only bump once `test` is updated (https://github.com/flutter/flutter/issues/5481).

**Comment by devoncarew** [comment]
lgtm, modulo a strange analysis failure w/ mega_gallery (strange because flutter_gallery analyzes cleanly)

**Comment by pq** [comment]
Ah...  This looks like a strong mode issue.  Investigating.

**Comment by pq** [comment]
For the curious, lots of action in strong-mode land (see [changes](https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#strong-mode)).

**Comment by pq** [comment]
FWIW these errors reproduce in `flutter_gallery`...  Not sure why that's not failing the tests.

**Comment by Hixie** [comment]
@pq Are you still looking at this one?

**Comment by pq** [comment]
Sorry, yeah.  I'd hoped to be able to simply update this one and land it once I sorted out some issues with `test` and `analyzer` but it's turned out to be a little trickier.  I'll close this and open a fresh PR when things are better squared away.

**Pull request closed without merging**
