### PR TITLE
chore: Add default variant to the iOS `archs`

### LINKED ISSUE #136951: [tech-debt] Environment.defines default value behavior
The environment defines could benefit from wrapping for dealing with default/required values.

https://github.com/flutter/flutter/blob/8b2c643c96782db810d05f252353849e8475e478/packages/flutter_tools/lib/src/build_system/build_system.dart#L490-L494

For example the defines contain

https://github.com/flutter/flutter/blob/8b2c643c96782db810d05f252353849e8475e478/packages/flutter_tools/lib/src/build_info.dart#L914-L926

There is a doc-comment on these what the default values are if they are missing. But doc-comments are not followed in the code:

This code follows the doc-comment:

https://github.com/flutter/flutter/blob/8b2c643c96782db810d05f252353849e8475e478/packages/flutter_tools/lib/src/build_system/targets/ios.dart#L65-L69

This code doesn't:

https://github.com/flutter/flutter/blob/8b2c643c96782db810d05f252353849e8475e478/packages/flutter_tools/lib/src/build_system/targets/ios.dart#L286-L289

Discovered in:

* https://github.com/flutter/flutter/pull/136948

Regarding the DarwinArchs and IosArchs, they should be maybe required everywhere instead of defaulting to a default value.

### PR DESCRIPTION
**Pull request by Rohithgilla12**
This fixes https://github.com/flutter/flutter/issues/136951

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Rohithgilla12** [comment]
@Hixie or @stuartmorgan I think this qualifies for a `test-exempt:`

**Comment by eliasyishak** [comment]
@Rohithgilla12 thank you for the contribution! You are missing tests for this change though, per the bots comment

**Comment by Rohithgilla12** [comment]
@eliasyishak This actually doesn't require tests.
I have pinged for a test exempt, waiting on it 😄

**Comment by eliasyishak** [comment]
> This actually doesn't require tests

Could we not test that the `MissingDefineException` exception is not being thrown when missing the `kIosArchs` key from the environment variables?

**Comment by Rohithgilla12** [comment]
@eliasyishak Sorry missed the message

Will check that

**Comment by eliasyishak** [comment]
Your test is failing, here is the snippet of the error
```
01:00 +1601 ~1 -1: test/general.shard/build_system/targets/ios_test.dart: Default kIosArchs value [E]                                                                                                  
  Expected: 'arm64'
    Actual: <null>
     Which: not an <Instance of 'String'>
  
  package:matcher                                             expect
  test/general.shard/build_system/targets/ios_test.dart 76:5  main.<fn>
  dart:async                                                  runZoned
  test/src/common.dart 214:14                                 testWithoutContext.<fn>
  test/src/common.dart 183:18                                 test.<fn>
```

I think a better test will be to override the `enviornment.defines` map and running the workflow you are editing

**Comment by Rohithgilla12** [comment]
@eliasyishak Thanks for the help, all tests are now passing.

**Comment by christopherfujino** [comment]
@vashworth if this is the right change to make, this LGTM, but can you confirm we want this to fallback to arm64?

**Comment by vashworth** [comment]
> @vashworth if this is the right change to make, this LGTM, but can you confirm we want this to fallback to arm64?

So I don't know that having a fallback is actually the correct thing here. If the ARCHs is empty/blank, that's for a reason and generally means that the project's settings do not support any arch (see https://github.com/flutter/flutter/issues/136931#issuecomment-1817190065 for an example of when this can happen).

Hypothetically, if we do default it to arm64, and arm64 is a not a valid arch, it'll most likely fail somewhere else in the build.

I think a better solution would probably be to give better error messaging, we could even parse the plugins and configs to try and determine the conflict that would cause ARCHs to be empty.

**Comment by christopherfujino** [comment]
> I think a better solution would probably be to give better error messaging, we could even parse the plugins and configs to try and determine the conflict that would cause ARCHs to be empty.

thanks for the context, and yeah, this approach sounds the most prudent.

**Comment by Rohithgilla12** [comment]
@christopherfujino @vashworth 
 Can you please help me on how to do this, any high level overview helps!

**Comment by christopherfujino** [comment]
> @christopherfujino @vashworth Can you please help me on how to do this, any high level overview helps!

Thanks for contributing this PR. Unfortunately, offering technical guidance to contributors is outside the scope of our code review process (and simply would not scale to the number of PRs that we receive).

**Comment by andrewkolos** [comment]
From tools PR triage, we are closing this as stale. Feel free to reopen if you wish to address the feedback and get this landed.

**Pull request closed without merging**
