### PR TITLE
Update BUILD.gn

### PR DESCRIPTION
**Pull request by danrubel**
Re: https://github.com/flutter/flutter/pull/6273 - Update the Fuchsia build to reference `package:mustache`.

@pylaligand Please let me know if this change works for you.

### CODE REVIEW

**Comment by kevmoo** [comment]
Uh – doesn't this point to packages that come in as part of GN for the SDK?

The SDK repo has mustache4dart – needed for dartdoc.

Not sure how this relates here...

**Comment by abarth** [comment]
I think we need to run a script to get this package into the Fuchsia build

/cc @pylaligand

**Comment by abarth** [comment]
https://fuchsia.googlesource.com/third_party/dart-pkg/+/master/pub/

Notice that mustache4dart exists there but mustache does not.

**Comment by danrubel** [comment]
Merged as https://github.com/flutter/flutter/commit/2c41a4000483137b83b3f05fc485bda351c942c2

**Pull request closed without merging**
