### PR TITLE
Depend on the goldens repo through git.

### PR DESCRIPTION
**Pull request by amirh**
It's easier to run the android_views integration test this way, without
needing to worry if we have a local clone of the goldens repo or not.

### CODE REVIEW

**Comment by dnfield** [comment]
This is only for a specific integration test, not for all flutter goldens - correct?

**Comment by xster** [comment]
Same question (since this seems to be the only non frozen dependency). How do we keep it hermetic (on the same devicelab test on the same commit, run once, submit something to goldens, run a second time, there might be a different result)

**Comment by amirh** [comment]
Good point, I'll fix it to a specific commit.

**Comment by amirh** [comment]
Followed up in #25678

**Pull request merged**
