### PR TITLE
Fix a legacy TODO

### PR DESCRIPTION
**Pull request by Hixie**
The referenced issue (https://github.com/flutter/flutter/issues/51885) is now closed.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
cc @dnfield

**Review by ghost — APPROVED** [review]

**Review by dnfield — APPROVED** [review]
lgtm assuming tests pass

**Comment by Hixie** [comment]
@yjbanov Can you give me any advice here?

**Comment by Hixie** [comment]
I can't repro the integration_test failure:
```
ianh@burmese:~/dev/flutter/packages/integration_test$ ../../bin/flutter test
00:02 +7: /home/ianh/dev/flutter/packages/integration_test/test/binding_test.dart: Test Integration binding (tearDownAll)
Warning: integration_test test plugin was not detected.
00:09 +10: All tests passed!
ianh@burmese:~/dev/flutter/packages/integration_test$ 
```

**Comment by Hixie** [comment]
Ok well I figured out why what we'd changed didn't fix it.

Turns out, before each test, we call `tester.resetTestTextInput` regardless of whether `binding.registerTestTextInput` is set to true or not, and _that_ reregisters the `TestTextInput` class regardless.

Also it turns out tests (including public documentation) depends on `tester.enterText` working even when `registerTestTextInput` is false.

**Comment by Hixie** [comment]
Ok I did some refactoring and cleaned this stuff up so now it passes. Hopefully this passes google3 too...

**Comment by Hixie** [comment]
cc @goderbauer for flutter_test changes

**Comment by Hixie** [comment]
cc @yjbanov since it affects web_e2e_tests

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
