### PR TITLE
Reland: Migrate examples to the Android embedding v2

### PR DESCRIPTION
**Pull request by blasten**
Once https://github.com/flutter/cocoon/pull/509 is merged and rolled out, then this change can be relanded.

### CODE REVIEW

**Comment by xster** [comment]
LGTM! Fingers crossed

**Comment by blasten** [comment]
@godofredoc Let me know when it's safe to merge.

**Review by godofredoc — APPROVED** [review]
Updated all the agent with the phone wakeup fix.

**Comment by xster** [comment]
Thanks @godofredoc!

**Comment by xster** [comment]
\o/

**Comment by xster** [comment]
Seems like we're safe here. Thanks for all the debugging @godofredoc and @blasten

**Comment by aam** [comment]
This broke building of flutter_gallery with local engine:

```
$FH/flutter/bin/flutter run -v --local-engine android_debug_unopt
...
[  +99 ms] > Task :app:compileDebugJavaWithJavac FAILED
[        ] $FH/flutter/examples/flutter_gallery/android/app/src/main/java/io/flutter/demo/gallery/MainActivity.java:7: error: cannot find symbol
[        ] import androidx.annotation.NonNull;
[        ]                           ^
[        ]   symbol:   class NonNull
...
[   +1 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
[   +4 ms] ✏️  Creating `android/settings_aar.gradle`...
...
                     FAILURE: Build failed with an exception.

                     * Where:
                     Initialization script '$FH/flutter/packages/flutter_tools/gradle/aar_init_script.gradle' line: 50

                     * What went wrong:
                     Local engine isn't supported when building the plugins as AAR. See: https://github.com/flutter/flutter/issues/40866

...
```

**Comment by aam** [comment]
Is it safe to revert while the failures being investigated?

**Comment by xster** [comment]
@blasten adding gradle dependencies temporarily to the gallery and pointing to it as manual instructions for other projects while we wire this up with POMs seems reasonable.

**Pull request merged**
