### PR TITLE
Fix local testing, gradle XML errors, and enable on CI.

### PR DESCRIPTION
**Pull request by matanlurey**
TIL you cannot have XML comments before the initial `<?xml` declaration.

Follow-up to https://github.com/flutter/flutter/pull/152326.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by matanlurey** [comment]
Unfortunately due to our CI setup I've spent all day trying to debug why this passes on CI (it shouldn't - a Skia Gold image should have been prompted for review). Hopefully this runs again today, if not I'll take it up again next week.

**Comment by matanlurey** [comment]
I need to tweak the ADB settings in order to hide this confirmation dialog:

image

**Comment by matanlurey** [comment]
Looks like that wasn't sufficient, guess I'll try again tomorrow.

**Comment by jonahwilliams** [comment]
Is it possible to use Flutter's SystemChrome API to have the test app enable full screen and/or hide the status bar?

**Comment by matanlurey** [comment]
> Is it possible to use Flutter's SystemChrome API to have the test app enable full screen and/or hide the status bar?

Hiding the bar is done, the problem is telling ADB "it's cool, I know it's hidden" for the screenshot

**Pull request merged**
