### PR TITLE
add preserveHeaderCase argument to subclasses of HttpHeaders

### PR DESCRIPTION
**Pull request by zichangg**
Preparation for landing https://github.com/dart-lang/sdk/issues/39657 in Dart SDK.

The cl: https://dart-review.googlesource.com/c/sdk/+/119100

An upcoming SDK release will add a named argument which must be included for any class which `implements` the interface.

[Flutter analyze bot](https://ci.chromium.org/p/dart/builders/try/flutter-analyze-try/6139) will break without this pr.

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by ZichangG** [comment]
I'm not quite sure how to land this without breaking the build too much. Does this break the flutter build?

Is this supposed to land when my change has been rolled into flutter engine? Or I'll land this anyway and flutter analyze bot will not complain.

What do you think?

**Comment by zanderso** [comment]
The analyzer pre-submit check appears to be fine with this change as-is even without the Dart SDK roll. It looks like we can land this now, and then monitor the Dart SDK roll. I will mark this PR so the bot will land it when the tree next turns green.

**Comment by ZichangG** [comment]
> The analyzer pre-submit check appears to be fine with this change as-is even without the Dart SDK roll. It looks like we can land this now, and then monitor the Dart SDK roll.

Great!

But once this goes in, does flutter-analyze-bot see the change immediately? Otherwise it will stay red. The bot uses "flutter pub get" to get flutter_tools.

**Comment by zanderso** [comment]
I don't know how the `flutter-analyze-bot` works. Does it pull the Flutter repo from head? @a-siva

**Pull request merged**
