### PR TITLE
Change iOS device discovery from polling to long-running observation

### PR DESCRIPTION
**Pull request by jmagman**
## Description

https://github.com/flutter/flutter/pull/58137 cherry-pick on 1.17-candidate.3

### CODE REVIEW

**Comment by jmagman** [comment]
@jonahwilliams Can I get a LGTM on the merge?  There were a few trivial conflicts around the `_items`->`deviceNotifier` rename, and less trivial ones in the tests, which I'm not worried about.

**Comment by jmagman** [comment]
@googlebot I fixed it.

**Comment by jmagman** [comment]
@googlebot come on bro

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by pcsosinski** [comment]
LGTM for submitting to the branch, docs-linux looks like it is gonna time out

**Comment by jmagman** [comment]
@tvolkert just added [change requests](https://github.com/flutter/flutter/pull/58137/files#r441810623) on the original PR. Following up on master at https://github.com/flutter/flutter/pull/59709.

However I don't think that change is critical for this cherry pick.  The dispose/shutdown path is called when the daemon process is about to get killed, and the [daemon docs](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/doc/daemon.md#daemonshutdown) say "It is not necessary to call this before shutting down the daemon; it is perfectly acceptable to just kill the daemon process."

**Review by tvolkert — APPROVED** [review]

**Pull request merged**
