### PR TITLE
Fix docs.sh to be more idomatic Bash, runnable from any dir

### PR DESCRIPTION
**Pull request by gspencergoog**

### CODE REVIEW

**Review by tvolkert — COMMENTED** [review]
Worth changing to use `[[ ... ]]` bash tests instead of `[ ... ]`?

**Comment by gspencergoog** [comment]
Oh, definitely.  I actually thought I already did that (but maybe that was in the other PR)...

**Comment by gspencergoog** [comment]
@tvolkert Ping?

**Review by tvolkert — APPROVED** [review]
LGTM

**Pull request merged**
