### PR TITLE
[versions] upgrade the world

### LINKED ISSUE #81294: flutter_test does not use the latest version of test_api
### to reproduce
- create a package that depends on the latest version of [test](https://pub.dev/packages/test) (at the time of writing `test: ^1.17.2`)
- create an app based on the latest master (see `doctor` below)
- add the package to the `dev_dependencies`
- run `flutter pub get`
### expected result

- `flutter_test` should be `up-to-date` with the latest version of `test`
- a possible error message should be "understandable"

### actual result

- flutter_test is **_not_** `up-to-date` with `test` more specifically [test_api](https://pub.dev/packages/test_api) (`^0.4.0` at the time of writing) 
- the error message is **_not informative_** and **_misleading_** 
    -  `Minimum version ("0.4.0") ` minimum version of what?
    -  immediately direct the user to filing an `issue`

<details>
<summary>flutter pub get</summary>

```console
$ flutter pub get
Invalid argument(s): Minimum version ("0.4.0") must be less than maximum ("0.4.0-0").
package:pub_semver/src/version_range.dart 67:7      new VersionRange    
package:pub/src/solver/reformat_ranges.dart 56:27   _reformatTerm       
package:pub/src/solver/reformat_ranges.dart 34:26   reformatRanges.<fn> 
dart:_internal                                      ListIterable.toList 
package:pub/src/solver/reformat_ranges.dart 35:12   reformatRanges      
package:pub/src/solver/reformat_ranges.dart 133:25  _reformatCause      
package:pub/src/solver/reformat_ranges.dart 36:7    reformatRanges      
package:pub/src/solver/reformat_ranges.dart 133:25  _reformatCause      
package:pub/src/solver/reformat_ranges.dart 36:7    reformatRanges      
package:pub/src/solver/reformat_ranges.dart 133:25  _reformatCause      
package:pub/src/solver/reformat_ranges.dart 36:7    reformatRanges      
package:pub/src/solver/reformat_ranges.dart 133:25  _reformatCause      
package:pub/src/solver/reformat_ranges.dart 36:7    reformatRanges      
package:pub/src/solver/reformat_ranges.dart 133:25  _reformatCause      
package:pub/src/solver/reformat_ranges.dart 36:7    reformatRanges      
package:pub/src/solver/version_solver.dart 308:24   VersionSolver._resolveConflict
package:pub/src/solver/version_solver.dart 129:27   VersionSolver._propagate
package:pub/src/solver/version_solver.dart 93:11    VersionSolver.solve.<fn>
===== asynchronous gap ===========================                      
package:pub/src/source/hosted.dart 635:14           BoundHostedSource.withPrefetching.<fn>
===== asynchronous gap ===========================                      
package:pub/src/rate_limited_scheduler.dart 110:14  RateLimitedScheduler.withPrescheduling
===== asynchronous gap ===========================                      
package:pub/src/source/hosted.dart 634:12           BoundHostedSource.withPrefetching
===== asynchronous gap ===========================                      
package:pub/src/solver/version_solver.dart 90:14    VersionSolver.solve 
===== asynchronous gap ===========================                      
package:pub/src/entrypoint.dart 233:18              Entrypoint.acquireDependencies
This is an unexpected error. Please run                                 
                                                                        
    dart pub --trace get --no-precompile                                
                                                                        
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in <****some_app****> ...                              
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
```

</details>

only `flutter pub get -v` refer the actual package/packages causing the issue
<details>
<summary>flutter pub get -v (partial)</summary>

```console
[   +1 ms] SLVR:   fact: no versions of <****some_package****> match >=0.4.0 <0.4.0+0
[        ] SLVR:   conflict: no versions of <****some_package****> match >=0.4.0 <0.4.0+0
[        ] SLVR:   ! <****some_package****> >=0.4.0 <0.4.0+0 is partially satisfied by not <****some_package****> >=0.4.0+0
[        ] SLVR:   ! which is caused by "<****some_package****> >=0.4.0+0 depends on test ^1.17.1"
[        ] SLVR:   ! thus: <****some_package****> >=0.4.0 requires test ^1.17.1
[        ] SLVR:   ! not test ^1.17.1 is satisfied by not test >=1.17.0
[        ] SLVR:   ! which is caused by "test >=1.17.0 depends on test_api 0.4.0"
[        ] SLVR:   ! thus: <****some_package****> >=0.4.0 requires test_api 0.4.0
[        ] SLVR:   ! not test_api 0.4.0 is satisfied by test_api 0.3.0
[        ] SLVR:   ! which is caused by "every version of flutter_test from sdk depends on test_api 0.3.0"
[        ] SLVR:   ! thus: <****some_package****> >=0.4.0 is incompatible with flutter_test from sdk
[        ] SLVR:   ! flutter_test any from sdk is satisfied by flutter_test any from sdk
[        ] SLVR:   ! which is caused by "<****some_app****> depends on flutter_test any from sdk"
[        ] SLVR:   ! thus: <****some_package****> >=0.4.0 is forbidden
[        ] SLVR:   ! <****some_package****> >=0.4.0 is satisfied by <****some_package****> ^0.4.0
[        ] SLVR:   ! which is caused by "<****some_app****> depends on <****some_package****> ^0.4.0"
[        ] SLVR:   ! thus: version solving failed
[   +2 ms] SLVR: Version solving took 0:00:02.930735 seconds.
```

</details>
<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 2.3.0-1.0.pre.105, on Linux, locale en_US.UTF-8)
    • Flutter version 2.3.0-1.0.pre.105 at /home/yakforward/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3eb5736134 (2 hours ago), 2021-04-27 07:49:08 -0400
    • Engine revision 9e4b4e23a3
    • Dart version 2.14.0 (build 2.14.0-47.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/yakforward/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /snap/android-studio/101/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-1ubuntu1
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.1)
    • Android Studio at /snap/android-studio/101/android-studio
    • Flutter plugin version 55.1.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.85

• No issues found!

```

</details>

### proposal

- would be nice to have some automation that updates `flutter_test` when a new release of `test_api` is released 
- the error message could be more clear

### LINKED ISSUE #81516: Errors in debug console window when using widget explorer
Repro steps:

- Debug hello_world example for web platform using latest flutter version on master channel
- Open widget inspector
- (May need to stop and start the debugger again)
- Observe several errors in the debug console mentioning (-32601) Unknown method "_flutter.listViews".

I added some printing and found that the calls to failing extension services are coming from dart-code VSCode extension  and the errors happen at https://github.com/flutter/flutter/blob/1b4f4482b75b92a95807ee4337798227c439dc61/packages/flutter_tools/lib/src/commands/daemon.dart#L692. I stopped at that ...

image

**Flutter doctor -v**
[✓] Flutter (Channel master, 2.3.0-1.0.pre.170, on Mac OS X 10.15.7 19H524
    darwin-x64, locale en-US)
    • Flutter version 2.3.0-1.0.pre.170 at /Users/annagrin/source/flutter/flutter
    • Upstream repository git@github.com:annagrin/flutter.git
    • Framework revision 027d4ecaba (5 hours ago), 2021-04-29 10:56:57 -0700
    • Engine revision e7939e091e
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/annagrin/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H524
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!

### LINKED ISSUE #81834: Unknown method "_flutter.listViews" errors on boot (web)
## Steps to Reproduce

1. Create a new flutter project.
2. Launch the code

**Expected results:**
A normal counter app with no errors

**Actual results:**
App launches, but console shows errors:

> Error handling 'checkPlatformOverride' custom request: _flutter.listViews: (-32601) Unknown method "_flutter.listViews".
Error handling 'checkBrightnessOverride' custom request: _flutter.listViews: (-32601) Unknown method "_flutter.listViews".
Error handling 'serviceExtension' custom request: _flutter.listViews: (-32601) Unknown method "_flutter.listViews".
Error handling 'checkIsWidgetCreationTracked' custom request: _flutter.listViews: (-32601) Unknown method "_flutter.listViews".

<details>
  <summary>Logs</summary>

```
```

```
No issues found! (ran in 8.4s)
```

```
[√] Flutter (Channel master, 2.3.0-1.0.pre.209, on Microsoft Windows [version 10.0.18363.1500], locale fr-CA)
    • Flutter version 2.3.0-1.0.pre.209 at C:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 336ae2de79 (21 hours ago), 2021-05-03 19:06:53 +0200
    • Engine revision 3e578c6e0d
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\matpa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.66

! Doctor found issues in 2 categories.
```

</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
Unblock the latest test version by revving mockito. Though this introduces more dev deps, we're close to eliminating it anyway.

Fixes #81516
Fixes #81834
Fixes #81294

### CODE REVIEW

**Comment by jonahwilliams** [comment]
it looks like we cant update our version of test because we have customer tests that dont version solve. I'm not sure what to do here

**Comment by zanderso** [comment]
> it looks like we cant update our version of test because we have customer tests that dont version solve. I'm not sure what to do here

In general, we have to update the customer repos before landing changes that would break them. So, I guess in this case that would bean loosening the constraints in the customer pubspecs?

**Comment by jonahwilliams** [comment]
This one was definitely not gonna roll in automatically 😓

**Comment by Hixie** [comment]
Yeah, but an automated roller would let us know as soon as that kind of problem came around, instead of us finding out at inconvenient times.

**Comment by jonahwilliams** [comment]
Trying again in https://github.com/flutter/flutter/pull/82275

**Pull request closed without merging**
