### PR TITLE
Made a few grammatical changes

### PR DESCRIPTION
**Pull request by mikeshatch**
## Description

I made a few grammatical changes. I changed ObjectiveC to Objective-C. I also reversed "uses mainly" to "mainly uses" which is more grammatically correct. Otherwise it appears to the eye that it's called "mainly Dart."

## Related Issues

This is my second commit for the same change. The first one was accepted but it wouldn't merge because I hadn't signed the CLA beforehand.

## Checklist

- [x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ x] I signed the [CLA].
- [x ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x ] No, this is *not* a breaking change.

### CODE REVIEW

**Review by kf6gpe — APPROVED** [review]
Looks great! Thanks for your contribution!

**Comment by kf6gpe** [comment]
Can you sign the CLA when you get a minute so we can take your change and merge this? Thanks so much!

**Comment by mikeshatch** [comment]
> Can you sign the CLA when you get a minute so we can take your change and merge this? Thanks so much!

I signed it a couple of months ago. I've run into the same issue with Google contributions before. The robot asks you to sign even if you've already signed. There's no way around it.

**Comment by jmagman** [comment]
@mikeshatch Are you waiting for anything to merge this (other than flutter-build going green)?

**Comment by tvolkert** [comment]
The build is green, but the status hasn't updated because GitHub is blocking status updates on this commit.  Merging.

**Pull request merged**
