### PR TITLE
check for pubspec instead of lib/

### LINKED ISSUE #107957: tool thinks pub packages without a lib directory are always out of date
This logic is checking if `package.packageUriRoot` directory exists, so the `lib` directory.  

https://github.com/flutter/flutter/blob/ed3c32c9d2c27b6259b7226063317d07b85f2134/packages/flutter_tools/lib/src/flutter_cache.dart#L101

https://github.com/flutter/packages/pull/1951 removed this directory `flutter_template_images`

> Removes the empty Dart file, which used to be required by pub.dev checks but no longer is.

But because the `lib` doesn't exist, on every run it thinks the pub dependencies are out of date, and `pub get` needs to be run.

Either that directory is needed, or the tool needs to be updated.

See https://github.com/flutter/flutter/issues/107873#issuecomment-1189507243

### PR DESCRIPTION
**Pull request by Jasguerrero**
Fixes: #107957

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by christopherfujino** [comment]
From the analyze-linux failure:

```
Unhandled exception:
FormatException: Unexpected character (at character 1)
Running "flutter pub get" in flutter_tools...                    2,609ms
^
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:612:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      _checkConsumerDependencies (file:///tmp/flutter%20sdk/dev/bots/analyze.dart:1676:47)
<asynchronous suspension>
#7      run (file:///tmp/flutter%20sdk/dev/bots/analyze.dart:153:3)
<asynchronous suspension>
#8      main (file:///tmp/flutter%20sdk/dev/bots/analyze.dart:50:5)
<asynchronous suspension>
```

https://github.com/flutter/flutter/blob/master/dev/bots/analyze.dart#L1664

So with this change, it must be failing the cache check even when the package is already present (note we already run `flutter update-packages` before running tests.

**Comment by Jasguerrero** [comment]
> So with this change, it must be failing the cache check even when the package is already present (note we already run `flutter update-packages` before running tests.

After a couple of logs I found that https://github.com/flutter/flutter/blob/master/dev/bots/analyze.dart#L1676 `result.stdout` starts with a `Running "flutter pub get" in flutter_tools...` which makes the json.decode to fail; apparently just making sure the `pubspec.yaml` is present is not enough (at least with our current setup in the flutter package) a work around could be to check if at least one option between lib/ and pubspec.yaml is present. Let me know what you think

**Comment by christopherfujino** [comment]
> > So with this change, it must be failing the cache check even when the package is already present (note we already run `flutter update-packages` before running tests.
> 
> After a couple of logs I found that https://github.com/flutter/flutter/blob/master/dev/bots/analyze.dart#L1676 `result.stdout` starts with a `Running "flutter pub get" in flutter_tools...` which makes the json.decode to fail; apparently just making sure the `pubspec.yaml` is present is not enough (at least with our current setup in the flutter package) a work around could be to check if at least one option between `lib/` and `pubspec.yaml` is present. Let me know what you think

Which package is it that's causing this to fail?

**Comment by christopherfujino** [comment]
> > Which package is it that's causing this to fail?
> 
> `flutter`

Hmm, are you sure? flutter_tools doesn't depend on package:flutter.

**Comment by Jasguerrero** [comment]
> Hmm, are you sure? flutter_tools doesn't depend on package:flutter.

Yes. here is an output of `bots/analyze.dart` In which I added a print with `Package name: $package` and the the stdout of `pub deps --json`

**Comment by Jasguerrero** [comment]
> Hmm, are you sure? flutter_tools doesn't depend on package:flutter.

Or do you mean what package inside the tool does not have the pubspec on the bot and that is why the `Running "flutter pub get"...` log is spawned?

**Comment by christopherfujino** [comment]
> > Hmm, are you sure? flutter_tools doesn't depend on package:flutter.
> 
> Or do you mean what package inside the tool does not have the pubspec on the bot and that is why the `Running "flutter pub get"...` log is spawned?

Yes

**Comment by Jasguerrero** [comment]
> Yes
It is `flutter_tools` so apparently https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/flutter_cache.dart#L100 `packageConfig.packages` contains `flutter_tools` and that does not have a pubspec.yaml. I added some logs in a different PR to verify it, here are some logs from a different PR to test this https://cirrus-ci.com/task/4762793864855552?logs=main#L26

**Comment by christopherfujino** [comment]
> > Yes
> 
> It is `flutter_tools` so apparently https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/flutter_cache.dart#L100 `packageConfig.packages` contains `flutter_tools` and that does not have a pubspec.yaml. I added some logs in a different PR to verify it, here are some logs to test this https://cirrus-ci.com/task/4762793864855552?logs=main#L26

I mean, we know `flutter_tools` has a pubspec.yaml https://github.com/flutter/flutter/blob/master/packages/flutter_tools/pubspec.yaml, so i think this is a bug in your code.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
