### PR TITLE
Roll engine to bc2acf7bddd855898ceb245a8a2ecf83c634ec8d

### PR DESCRIPTION
**Pull request by cbracken**
Includes Topaz and Garnet changes (and some Fuchsia-specific rasteriser changes).

### CODE REVIEW

**Comment by cbracken** [comment]
Includes Topaz and Garnet changes (and some Fuchsia-specific rasteriser changes).

**Comment by xster** [comment]
LGTM

**Comment by aam** [comment]
Somehow this introduced regression in few hot_mode_dev_cycle_win__benchmark and microbenchmarks

**Comment by cbracken** [comment]
@aam thanks. I'll see if I can bisect where this hit.

**Comment by Hixie** [comment]
@cbracken Any luck? (The hot reload benchmark got better for unrelated reasons but the original regression is likely still present. The microbenchmarks are not better.)

**Comment by cbracken** [comment]
@Hixie at this point it looks suspiciously like the tonic/topaz roll (d615678) as opposed to the garnet roll (a8237ec). The change we care about in there is https://fuchsia-review.googlesource.com/c/topaz/+/83861 which fixes #9998, and which we'd expect to impact performance (in favour of correctness).

**Comment by cbracken** [comment]
Note: I haven't yet tried reverting the one change in question in topaz to rule out any other Topaz change(s) causing the regression. I'll try that tomorrow.

**Comment by aam** [comment]
Nice find! 
+ @jason-simmons  regarding regression in hot_mode_dev_cycle[_win/_linux]__benchmark introduced in that exact PR.

**Comment by cbracken** [comment]
I've confirmed at head and manually reverting the topaz change that it appears to account for the difference on the `stock_build_iteration` benchmark.

Three runs at head:
```
I/flutter (18358): Stock build: 6545.0 µs per iteration
I/flutter (17967): Stock build: 6411.0 µs per iteration
I/flutter (18918): Stock build: 6444.6 µs per iteration
```

Three runs at head with the revert:
```
I/flutter (17666): Stock build: 4732.6 µs per iteration
I/flutter (18408): Stock build: 4980.9 µs per iteration
I/flutter (18649): Stock build: 4822.3 µs per iteration
```

**Comment by cbracken** [comment]
I've added a test in #13073 that I've verified used to fail but now passes and will re-baseline the affected benchmarks unless anyone has any objections.

**Comment by aam** [comment]
One thing that is worrisome is that this same change caused regression in hot_mode reassemble benchmarks. It's not clear whether impact of completing microtasks sooner and checking the queue sooner on those benchmarks is as expected.

**Comment by cbracken** [comment]
@aam Agreed - I've only looked into the microbenchmarks.

**Pull request merged**
