### PR TITLE
use --no-precompile

### PR DESCRIPTION
**Pull request by devoncarew**
W/ the rev to the latest sdk, we can use the pub flag `--no-precompile`. This makes a _very_ slight performance improvement in update-packages.

```
Running 'pub upgrade' in cassowary...         5.8s
Running 'pub upgrade' in flutter...           4.5s
Running 'pub upgrade' in flutter_driver...    4.8s
Running 'pub upgrade' in flutter_markdown...  6.0s
Running 'pub upgrade' in flutter_sprites...   5.8s
Running 'pub upgrade' in flutter_test...      4.5s
Running 'pub upgrade' in flutter_tools...     5.3s
Running 'pub upgrade' in flx...               5.4s
Running 'pub upgrade' in newton...            5.3s
Running 'pub upgrade' in playfair...          5.9s
Running 'pub upgrade' in hello_world...       3.1s
Running 'pub upgrade' in layers...            3.1s
Running 'pub upgrade' in material_gallery...  3.3s
Running 'pub upgrade' in stocks...            5.1s
Running 'pub upgrade' in docs...              5.2s
Running 'pub upgrade' in manual_tests...      3.4s

Ran 'pub' 16 times in 76.3s.
```

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
I'm not sure what precompile did in the first place. :)  lgtm.

**Comment by devoncarew** [comment]
It creates cached snapshots of apps local to each package. So `test`, and some of the `i18n` tools. Things like `pub run test` would still work w/ this flag, it's just that `pub get` won't pre-compile the snapshot.

**Comment by abarth** [comment]
LGTM but travis is mad

**Comment by devoncarew** [comment]
Looks like `pub get` was using whatever pub was on the path, and the version on travis doesn't support the `--no-precompile` flag. I changed our pub get to use the sdk from bin/cache.

**Pull request merged**
