### PR TITLE
Revert "Check for watch companion in build settings"

### PR DESCRIPTION
**Pull request by jmagman**
Reverts flutter/flutter#113956

`ios_app_with_extensions_test` is failing in post-submit.

https://ci.chromium.org/p/flutter/builders/prod/Mac_arm64_ios%20ios_app_with_extensions_test/3318

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by vashworth — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
Landing before presubmits finish as it is a straight revert of the tip of the tree

**Comment by jmagman** [comment]
The bot doesn't have the watchOS simulator installed (see https://github.com/flutter/flutter/pull/94190), so `destination generic/platform=watchOS -showBuildSettings ` is failing:
```
           xcodebuild: error: Unable to find a destination matching the provided destination specifier:
           		{ generic:1, platform:watchOS }
```

**Pull request merged**
