### PR TITLE
fix the textalign of placeholder is always on the left

### PR DESCRIPTION
**Pull request by AlexTeamX**
## Description

`CupertinoTextField(
     textAlign: TextAlign.right,
     placeholder: "Input something",
),`

## Related Issues

[#27946](https://github.com/flutter/flutter/issues/27946)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jslavitz** [comment]
Hey! Thanks so much for your contribution! This looks really good, tho we'll need a test before it can be submitted! Will you be able to do that?

**Comment by YaoShuwei** [comment]
> Hey! Thanks so much for your contribution! This looks really good, tho we'll need a test before it can be submitted! Will you be able to do that?

Yes,I'm able to do everything.

**Comment by xster** [comment]
Thanks for your contribution. There are a number of tests already in https://github.com/flutter/flutter/blob/master/packages/flutter/test/cupertino/text_field_test.dart which you can use as a template for adding additional tests. 

We'd want to make assert that the positioning is as intended with this new implementation. Also, on iOS, it seems like if you have a multi-line height text field, the placeholder is vertically aligned. Please also assert that that is the case in the test.

**Comment by xster** [comment]
We haven't heard back from you for a while. We're going to close this PR for now but definitely feel free to re-open it when you're ready to add some tests. We can help you implement it as well.

**Pull request closed without merging**
