### PR TITLE
Revert "Improve the ScrollBar behavior when nested"

### PR DESCRIPTION
**Pull request by jmagman**
Reverts flutter/flutter#71843

Dartdoc error:
```
dartdoc:stderr:   error: unresolved doc reference [notificationPredicate], from material.Scrollbar: (file:///b/s/w/ir/k/flutter%20sdk/packages/flutter/lib/src/material/scrollbar.dart:48:7)
```
```
dartdoc:stderr: found 1 warning and 1 error
dartdoc:stdout: Documented 163 public libraries in 263.2 seconds
dartdoc:stderr:
dartdoc:stderr: dartdoc failed: dartdoc encountered 1 errors while processing..
dartdoc:stderr: #0      Dartdoc.generateDocs (package:dartdoc/dartdoc.dart:231:9)
dartdoc:stderr: <asynchronous suspension>
dartdoc:stderr: #1      Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/dartdoc.dart:500:9)
dartdoc:stderr: <asynchronous suspension>
```
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8857995126157483168/+/steps/prepare_environment/0/steps/Docs/0/steps/docs/0/stdout

### CODE REVIEW

**Comment by jmagman** [comment]
Merging to see if this was the cause of that failure.

**Comment by jonahwilliams** [comment]
The specific error is:

```
dartdoc:stderr:   error: unresolved doc reference [notificationPredicate], from material.Scrollbar: (file:///b/s/w/ir/k/flutter%20sdk/packages/flutter/lib/src/material/scrollbar.dart:48:7)
```

**Comment by jonahwilliams** [comment]
LGTM

**Comment by jmagman** [comment]
> if this was the cause of that failure.
> scrollbar.dart:48:7

Sure seems it :-)

**Comment by jmagman** [comment]
> The specific error is:
> 
> ```
> dartdoc:stderr:   error: unresolved doc reference [notificationPredicate], from material.Scrollbar: (file:///b/s/w/ir/k/flutter%20sdk/packages/flutter/lib/src/material/scrollbar.dart:48:7)
> ```


Thanks, I missed it in the middle.

**Comment by Piinks** [comment]
How strange, this should have failed in presubmit. Thanks!

**Comment by xu-baolin** [comment]
> How strange, this should have failed in presubmit. Thanks!

This is most likely because I did not synchronize this change #73899

**Pull request merged**
