### PR TITLE
Fix `prefer_mixin` in Dart files.

### LINKED ISSUE #123172: Dart 3 cleanup: Update our usage of package:file
Once https://github.com/dart-lang/linter/issues/3018 is resolved, we should remove the ignores put in place in this PR: https://github.com/flutter/flutter/pull/123159

### PR DESCRIPTION
**Pull request by bernaferrari**
Fix https://github.com/flutter/flutter/pull/123159
Fix https://github.com/flutter/flutter/issues/123172
when this https://github.com/google/file.dart/pull/210 lands.

### CODE REVIEW

**Comment by bernaferrari** [comment]
Waiting for files 7.0.1 to land on pub.

**Comment by bernaferrari** [comment]
cc @jakemac53

**Comment by goderbauer** [comment]
Looks like the analyzer check is unhappy.

**Comment by bernaferrari** [comment]
Yeah, we need to wait for files 7.0.1 because it has a circular dependency :(

**Comment by jakemac53** [comment]
We shouldn't need files `7.0.1` afaik, that just removes the overrides? You instead need the latest glob, version `2.1.2`.

If things still aren't working can you show me a failed pub solve?

**Comment by bernaferrari** [comment]
Yeah, I'll wait a few more days. They have been having some dependency issues I thought they solved already.

**Comment by bernaferrari** [comment]
Blocked by https://github.com/google/process.dart/pull/75

**Comment by bernaferrari** [comment]
Now blocked by dws using `dart_code_metrics` which got discontinued and became closed source/paid.

**Comment by jakemac53** [comment]
I would file an issue to remove the dependency if it is discontinued, we can't have dependencies that won't be updated in our repos.

**Comment by bernaferrari** [comment]
Done, now we wait dwsd to be updated to version 20, maybe a few weeks, lol

**Comment by elliette** [comment]
> Done, now we wait dwsd to be updated to version 20, maybe a few weeks, lol

DWDS 20.0.0 has been published! I think we need this to land in order to pull in the new version of DWDS in flutter_tools:

```
Because flutter_tools depends on dwds 20.0.0 which depends on file ^7.0.0, file ^7.0.0 is
  required.
So, because flutter_tools depends on file 6.1.4, version solving failed.
```

**Comment by bernaferrari** [comment]
Let's goooo.. I don't even know where flutter_tools is. Finding..

**Comment by elliette** [comment]
Looks like `process_runner` will also need to be updated to use `file` 7.0.0: https://github.com/google/process_runner/blob/master/pubspec.yaml

**Comment by bernaferrari** [comment]
Thanks for the finding, opened the PR already: Here we go again. <@259558104251760642> 
https://github.com/google/process_runner/pull/31

**Comment by elliette** [comment]
It looks like more versions are going to need to be updated after that unfortunately. I'm going to roll in a new version of `dwds` into Flutter without the `package:file` update (because it's blocking us from updating DWDS in flutter). However, once the other dependencies using `package:file` have been identified, happy to update to the latest version of `package:file` in DWDS and roll into Flutter.

**Comment by bernaferrari** [comment]
You can do file > 6 < 8, then when it is update, it automatically works.

**Comment by christopherfujino** [comment]
> You can do file > 6 < 8, then when it is updated, it automatically works.

that will resolve the pub solve issues, but is it safe to allow version solving that wide? that means that the breaking changes in 6->7 and 7->8 are not going to affect DWDS usage. Is this true?

**Comment by christopherfujino** [comment]
> The only change is the "do not extend me" mixin thing, which was never ever extended anyway.

Ahh, I see.

**Comment by Hixie** [comment]
@goderbauer fixed this.

**Pull request closed without merging**
