### PR TITLE
ShortcutManager should dispatch creation in constructor.

### LINKED ISSUE #133515: _ShortcutRegistrarState initializes but not dispose the field `manager`
See PR: https://github.com/flutter/flutter/pull/133487

### PR DESCRIPTION
**Pull request by polina-c**
First attempt was reverted: https://github.com/flutter/flutter/pull/133356

Fixes: https://github.com/flutter/flutter/issues/133515

### CODE REVIEW

**Comment by vashworth** [comment]
@polina-c Looks like this PR is still a draft? Is it ready to review? Also, since you've changed the logic a bit and it's not a straight revert, can you request @chunhtai review once it's ready?

**Review by chunhtai — COMMENTED** [review]
If not fixing the leak in this pr, may be good to add a todo at the line that supposed to dispose the manager to remind us that the migration has not completed

**Comment by polina-c** [comment]
It is draft, because I want to know which tests will fail in order to disable them and add TODO.

**Comment by polina-c** [comment]
Now ready for review.

**Comment by polina-c** [comment]
There are too many failures. Will try to submit fix. Maybe this time it will stay.
I little worry that it is for public field.

**Review by chunhtai — APPROVED** [review]
LGTM

**Pull request merged**
