### PR TITLE
[flutter_tools] Fix breakage when test main is tagged with @doNotStore

### PR DESCRIPTION
**Pull request by jiahaog**
When a test `main` is tagged with `@doNotStore`, and the `return_of_do_not_store` lint is enabled, #76200 will be a breaking change.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
What is doNotStore?

**Comment by jiahaog** [comment]
I just found out today as well... Apparently there's a [lint](https://pub.dev/documentation/meta/latest/meta/doNotStore-constant.html) where doing the following will be an error. 

```
import 'package:meta/meta.dart'

@doNotStore
String thing() {
  return 'abc'
}

void main() {
  final a = thing(); // LINT
}
```

**Comment by jiahaog** [comment]
Not really sure why the tests are failing on CI but passing locally though, will investigate a bit further

**Comment by jonahwilliams** [comment]
TIL!

**Comment by jonahwilliams** [comment]
the problem here is that you can't await a Function that returns void either. TBH, this seems like a hole in doNotStore. You'd need excessive `is` checks for all of the different kinds of main functions, so that you can strategically await. I don't see a better way through this besides an ignore

**Comment by jiahaog** [comment]
Yeah, agreed about how `doNotStore` should probably handle returning `void`. Then again users could still cast the void value to something else so I'm also not sure how that should be handled best.

I don't understand why the test was passing for me locally just now, rerunning it again causes it to fail now 😅 . Re: avoiding breaking users who do annotate `main` with `@doNotStore`, what about wrapping the whole thing in a `Future`? Then we can await it unconditionally.

I'm not sure how to add a test for this though, as there doesn't appear to be a way to turn *on* the lint. Whatever I do causes the doNotStore test case that fails in Google3 to pass even without this PR.

**Comment by jonahwilliams** [comment]
Seems reasonable, though I would think that would trigger the lint too - at any rate - as long as the existing tests are passing it should be OK

**Comment by jiahaog** [comment]
I think the lint is only triggered if the annotated expression is propagated by a function through the returned value. Since we `await` it here instead of returning it in `_testMain`, it's fine. (Also tested this internally with the failing case)

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
