### PR TITLE
Use flutter from in same repo (not path) in `generate_gradle_lockfiles.dart` (again)

### PR DESCRIPTION
**Pull request by gmackall**
Fixes another invocation of `flutter`. Follow up to https://github.com/flutter/flutter/pull/155790/.

Checked that this is the only other one (and also the only use of `exec()` left that is relying on the path and shouldn't be (one other use uses git from the path, which is fine, and the other one uses an absolute path).

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by matanlurey** [comment]
test-exempt: Tested by running on CI.

**Comment by gmackall** [comment]
This particular test seems to be running into an infra failure frequently:
https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20build_tests_2_4/15092/overview
```
fatal: unable to access 'https://github.com/flutter/flutter/': SSL: certificate verification failed (result: 5)
```

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by reidbaker — APPROVED** [review]

**Comment by reidbaker** [comment]
@gmackall consider filing a bug against our team to write a longer for this class of mistake.

**Pull request merged**
