### PR TITLE
Implement documented behavior of WidgetsApp.builder

### PR DESCRIPTION
**Pull request by goderbauer**
## Description

_Story Time..._

This all began with me wondering, "Why is the `child` parameter of [`MaterialApp.builder`](https://master-api.flutter.dev/flutter/material/MaterialApp/builder.html) nullable?" Luckily, the documentation had the answer:

> If no routes are provided using home, routes, onGenerateRoute, or onUnknownRoute, the child will be null, and it is the responsibility of the builder to provide the application's routing machinery.

Cool, I thought. Except when I wrote a test for it, it wouldn't pass:

```dart
  testWidgets('MaterialApp.build can build without Navigator', (WidgetTester tester) async {
    Widget builderChild;
    await tester.pumpWidget(MaterialApp(
        builder: (BuildContext context, Widget child) {
          builderChild = child;
          return Container();
        }
    ));
    expect(builderChild, isNull);
  });
```

Looking at the code of WidgetsApp, it turns out that we are always instantiating a Navigator and passing it to the builder. Unfortunately, since none of the arguments for the Navigator are provided to the MaterialApp, this Navigator is actually not buildable and would crash the app if inserted into the widget tree.

Some historic digging showed that https://github.com/flutter/flutter/pull/22161 from 2 years ago accidentally changed the logic to always instantiate a Navigator even when it shouldn't (e.g. because the Navigator is not build-able with the provided information).

This PR restores the old behavior as documented: If not enough information are presented to build a Navigator, none is instantiated.

## Related Issues

n/a

## Tests

I added the following tests:

 * added test mentioned above.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by dnfield — COMMENTED** [review]
This LGTM but I think @chunhtai is more up to date on all of this and would defer to his review.

**Review by chunhtai — COMMENTED** [review]
Change looks good but i think the documentation of WidgetsApp.builder is outdated, it should mention router, and the child could be a router instead of navigator

**Comment by goderbauer** [comment]
@chunhtai docs updated. PTAL.

**Review by chunhtai — APPROVED** [review]
LGTM

**Pull request merged**
