### PR TITLE
Convenience test task for VS Code

### PR DESCRIPTION
**Pull request by xster**
Just a thought. WDYT @abarth?

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
I am excite.

**Comment by eseidelGoogle** [comment]
FYI @dantup (you appear to have more fans on the Flutter team).

**Comment by xster** [comment]
filepicker-3vfcwpm3qvupgq0fgtri_borat
Indeed

**Comment by DanTup** [comment]
I'm curios - what does this action do? I raised an issue about support for tests in VS Code (https://github.com/Microsoft/vscode/issues/10742) and it sounded like it needed development before I could do anything useful there?

**Comment by xster** [comment]
Ummm I had the issue you described in the other bug. I didn't dig into their source but it was finicky about wanting the exact combination of the parent command and arguments with the child task name and parameters. 

Now it runs the open file's tests via Tasks: Run Test Tasks / workbench.action.tasks.test.

**Pull request merged**
