### PR TITLE
Wrap input widgets in a repaint boundary

### PR DESCRIPTION
**Pull request by jason-simmons**
Performance improvement for https://github.com/flutter/flutter/issues/6008

### CODE REVIEW

**Comment by Hixie** [comment]
Can you use the app with this for a while and then dump the render tree and see what diagnostics it gives for that repaint boundary?

**Comment by Hixie** [comment]
(If you're going to put in a repaint boundary, put it in at the inner-most point, so that for example we don't bother repainting the padding each time.)

**Comment by jason-simmons** [comment]
According to debugDumpRenderTree "this is an outstandingly useful repaint boundary and should definitely be kept" :)

**Comment by Hixie** [comment]
LGTM

Ship it! :-)

**Pull request merged**
