### PR TITLE
Allow Duration.Zero for animateTo without assertion failure

### LINKED ISSUE #11445: AnimationController.animateTo fails with obscure assertion on zero duration
## Steps to Reproduce

The following test demonstrates the issue:

```dart
  test('can deal with duration == Duration.ZERO', () {
    final AnimationController controller = new AnimationController(
      duration: const Duration(milliseconds: 100),
      vsync: const TestVSync(),
    );

    controller.forward(from: 0.2);
    expect(controller.value, 0.2);
    controller.animateTo(1.0, duration: Duration.ZERO);
  });
```

I haven't looked in detail, but either the assertion is wrong, or it should produce a much better error message. The docs on `animateTo` do not contain anything on this either.

/cc @Hixie @bramvbilsen

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/11445

@Hixie @yjbanov @bramvbilsen

### CODE REVIEW

**Comment by Hixie** [comment]
This makes animateTo() with a zero duration exactly equivalent to setting `value` directly, right?

**Comment by Hixie** [comment]
LGTM

**Comment by goderbauer** [comment]
> This makes animateTo() with a zero duration exactly equivalent to setting value directly, right?

No, not exactly. Let's say you have an AnimationController with [0.0, 1.0] as bounds. Setting value directly to 0.5 will leave you with AnimationStatus.forward or AnimationStatus.reverse (depending on what `direction` was) because you haven't reached the lower/upper bound yet. Calling animateTo with a target of 0.5 will leave you with AnimationStatus.dismissed or AnimationStatus.completed (depending on what `direction` was) because, well, the animation to 0.5 is done.

Looking at the code, this is true wether or not the duration was zero and this logic hasn't changed with this PR. However, it looks like these subtile differences between setting value directly and calling animateTo are currently not covered by any tests. If we agree that the currently implemented logic is correct and not a bug, I'd volunteer to add some test coverage to that.

**Comment by goderbauer** [comment]
Actually, the current implementation is kinda odd: Let's assume you'd create an AnimationController with bounds [0.0, 1.0] and initialize it with value 1.0. If you now call animateTo(0.5) it will claim that it is actually animating *forward* from 1.0 to 0.5. Intuitively, I'd call that the reverse direction.

Looks like maybe animateTo needs to update the direction value depending on what the current value and the target is?

**Comment by goderbauer** [comment]
I am going to submit this on green. I started https://github.com/flutter/flutter/pull/11520 for adding extra tests.

**Pull request merged**
