### PR TITLE
Add iOS benchmarks for sksl warmup

### PR DESCRIPTION
**Pull request by zanderso**
Related https://github.com/flutter/flutter/issues/86457.

Am I doing this right? Is there anything else I have to do, @CaseyHillers?

@chinmaygarde

### CODE REVIEW

**Review by CaseyHillers — APPROVED** [review]
LGTM - This still requires a flutter/infra change to add the builders in devicelab_config.star

**Comment by zanderso** [comment]
@CaseyHillers https://flutter-review.googlesource.com/c/infra/+/15600

**Comment by zanderso** [comment]
@CaseyHillers Which do I land first? This one or the flutter/infra change?

**Comment by CaseyHillers** [comment]
> @CaseyHillers Which do I land first? This one or the flutter/infra change?

Preferably flutter/infra, and wait 15 minutes. However, the order doesn't matter for a non-blocking postsubmit target.

**Comment by keyonghan** [comment]
Can we add the test ownership in https://github.com/flutter/flutter/blob/master/TESTOWNERS?

**Pull request merged**
