### PR TITLE
Make NavigationRail scrollable

### PR DESCRIPTION
**Pull request by maheshj01**
This PR addressed the issue https://github.com/flutter/flutter/issues/89167 to make the navigationRail Scrollable when the number NavigationDestinations exceeds the viewport

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by maheshmnj** [comment]
I am kind of not sure what tests would we write for this PR, some sort of feedback or pointers would be much helpful.

Thanks

**Comment by gspencergoog** [comment]
So, a possible test would be to create a NavigationRail, and then synthesize a drag over the control and verify that it scrolls.

You'll also have to address the semantics failures in the existing tests. Ideally, the semantics tree wouldn't change, but since you are introducing scrolling, the semantics will change somewhat, and you'll have to verify that your changes are sensible. I also think perhaps that the semantics shouldn't change on a control that is too small to scroll, but perhaps there is overscroll even then, so maybe not (I'm not too sure about that point).

**Comment by maheshmnj** [comment]
Thanks for taking a look @gspencergoog, I am sorry for the delayed response, I have added the scrollable test. But I have no idea at this point how to address the semantics test failure 
The semantic tree fails with 

```console
Actual: SemanticsTester:<SemanticsTester for SemanticsNode#0(Rect.fromLTRB(0.0, 0.0, 2400.0, 1800.0))>
   Which: expected node id null to have textDirection "TextDirection.ltr" but found "null".
          Current SemanticsNode tree:
```

**Comment by Hixie** [comment]
@maheshmnj If you are still interested in working on this PR but looking for advice on writing the tests, I recommend reaching out for help on Discord in our #hackers-new channel. See the contributing guide for a link to the Discord server. Thanks!

**Comment by maheshmnj** [comment]
Closing this for now will send a PR When I can fully contribute

**Comment by davedega** [comment]
any update on this issue?

**Pull request closed without merging**
