### PR TITLE
Get rid of _NullElement.

### LINKED ISSUE #145602: _NullElement is leaking
To repro follow the steps: https://github.com/flutter/flutter/issues/141198#issuecomment-1987383965

### PR DESCRIPTION
**Pull request by polina-c**
Fixes https://github.com/flutter/flutter/issues/145602

### CODE REVIEW

**Comment by polina-c** [comment]
> It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need [an exemption](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests) to this rule, contact "@test-exemption-reviewer" in the #hackers channel in [Chat](https://github.com/flutter/flutter/wiki/Chat) (don't just cc them here, they won't see it! Use Discord!).
> 
> If you are not sure if you need tests, consider this rule of thumb: the purpose of a test is to make sure someone doesn't accidentally revert the fix. Ask yourself, **is there anything in your PR that you feel it is important we not accidentally revert back to how it was before your fix?**
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.

Test covered in [flutter_test_config.dart](https://github.com/flutter/flutter/pull/146741/files#diff-6480fd5d23df7fded24dfe31246ea83975761007443b1be230db2201c3c9c01d)

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
You'll need to do what the [bot](https://github.com/flutter/flutter/pull/146741#issuecomment-2058072352) says to get a test exception, though.

**Comment by Hixie** [comment]
Have we checked the performance implications of this change? The original code was intended to avoid overhead in list generation and the new code has a lot more function calls.

**Comment by polina-c** [comment]
> Have we checked the performance implications of this change? The original code was intended to avoid overhead in list generation and the new code has a lot more function calls.

From my perspective the new code has better performance.
The old code did: (1) list generation and (2) updating each value in the list with full scan, so looping two times.
New code is looping through items just one time without doing more for each item.

And I expect flutter performance banchmarks to catch the issue.

If it is not convincing enough, what will be convincing for you?

**Comment by Hixie** [comment]
The only way to tell is to benchmark it.

**Comment by polina-c** [comment]
Measured timing. On mac performance is improved 4 times if number of tabs is 30.

Code:
```
class Element {}

final stub = Element();
const numberOfTabs = 30;
const repeat = 1000000;

Element generateItem() => Element();

List<Element> oldCode() {
  final result = List<Element>.filled(numberOfTabs, stub);

  for (int i = 0; i < result.length; i += 1) {
    final Element newChild = generateItem();
    result[i] = newChild;
  }
  return result;
}

List<Element> newCode() {
  return List<Element>.generate(numberOfTabs, (int i) => generateItem(),
      growable: false);
}

void main() {
  late List<Element> list;
  
  Stopwatch oldTime = Stopwatch()..start();
  for (int i = 0; i < repeat; i ++) {
    list = oldCode();
  }
  oldTime.stop();
  print('old: ${oldTime.elapsedMilliseconds} ms');
  
  Stopwatch newTime = Stopwatch()..start();
  for (int i = 0; i < repeat; i ++) {
    list = newCode();
  }
  newTime.stop();
  print('new: ${newTime.elapsedMilliseconds} ms');
  
  
  print('length: ${list.length}');
}
```

Output:
```
old: 471 ms
new: 127 ms
length: 30
```

**Comment by Hixie** [comment]
nice!

**Review by Hixie — APPROVED** [review]
LGTM

**Pull request merged**
