### PR TITLE
Add Material 3 support to the existing Drawer

### LINKED ISSUE #103551: Update `Drawer` to support Material 3
As part of the [Material 3 specification](https://m3.material.io/components/icon-buttons/overview) there are updates to the Navigation drawer visuals:

Screen Shot 2022-05-11 at 5 15 20 PM

Currently Flutter only has the `Drawer` widget, but it is pretty bare-bones. We should look into possibly creating a new NavigationDrawer. It would be good if that could be integrated with the `NavigationDestination` used by the `NavigationBar` as well.

### PR DESCRIPTION
**Pull request by elbeicktalat**
This PR. introduce the material 3 support for the already existing `Drawer` widget.

Fix #103551 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Comment by hangyujin** [comment]
Hi @elbeicktalat! Thank you very much for your contribution! 
I see this is a draft and will also need some new tests, so I just wanted to confirm if this is still in your plans?

**Comment by elbeicktalat** [comment]
Hi there,
Yes for sure, I'll probably support M3 then integrate Drawer with NavigationDestination.

**Comment by mavyfaby** [comment]
Any updates?

**Comment by hangyujin** [comment]
Hi @elbeicktalat ! 
I just wanted to inform you that the Flutter team is looking into this. You can drop this PR draft so we don't duplicate work :)

**Comment by elbeicktalat** [comment]
Drop PR. since flutter team working on.

**Pull request closed without merging**
