### PR TITLE
Reland flaky golden file tests

### PR DESCRIPTION
**Pull request by Piinks**
Reland #114450 
Reverted in https://github.com/flutter/flutter/pull/114902

WIP - Still trying to diagnose why https://flutter-gold.skia.org/detail?test=cupertino.date_picker_test.date.initial&digest=6cce8fe0712d4b12c137063cae36eccf closed the tree

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Piinks** [comment]
@yjbanov I this was reverted after the tree closed on https://flutter-gold.skia.org/detail?test=cupertino.date_picker_test.date.initial&digest=6cce8fe0712d4b12c137063cae36eccf

According to our assumptions, the fuzzy settings should have passed the image.. I've reach out to @kjlubick to see if we're wrong here to think so.

**Comment by Piinks** [comment]
Filed https://bugs.chromium.org/p/skia/issues/detail?id=13906&q=katelovett&can=2 for follow up on the Gold team. The fuzzy auto-triage should have occurred.

One thing we could do, @yjbanov WDYT of when flaky, removing the `--passfail` flag? That would prevent the tree from breaking, but it would not auto-triage the image in this case where fuzzy matching is not approving the image.

That means untriaged images could accrue on the dashboard, and left unattended, could alert other unrelated PRs... not sure how you would like to proceed 🤔

**Comment by Piinks** [comment]
I heard back from the gold team, this is blocked on https://github.com/flutter/flutter/issues/93263.
The fizzy matching won't auto-triage when the image sizes vary

**Comment by christopherfujino** [comment]
> I heard back from the gold team, this is blocked on https://github.com/flutter/flutter/issues/93263.

@Piinks should we leave this open optimistically or just leave a TODO?

**Comment by Piinks** [comment]
I am going to close it. @yjbanov mentioned that https://github.com/flutter/flutter/issues/93263 may be the root cause of the flaky tests to begin with, so we can reassess after that is resolved.

**Pull request closed without merging**
