### PR TITLE
Added Widget of the Week Links to API Docs

### PR DESCRIPTION
**Pull request by Piinks**
## Description

This PR provides links to the Widget of the Week videos in the API documentation for each widget.

## Related Issues

Ref: #28360 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [ ] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by goderbauer** [comment]
/cc @RedBrogdon 

It would be even cooler if the video was directly imbedded in the page so you'd only have to press play to watch it. Maybe we can implement something like the `{@tool sample}`, but for embedding YouTube? My plan is to add the work for this to next quarter's OKR...

**Comment by Piinks** [comment]
I was wondering if that might be better too. Could it potentially clutter up the page?

**Comment by goderbauer** [comment]
I'd think that it would nicely break up the wall of text we have on some of those widgets and make the docs more approachable: If I just discovered a new widget, the "widget of the week" video is the perfect intro to that widget and I'd want that one to stand out from the wall of text that describes all the edge cases of the widget, which may be irrelevant to my use case.

**Comment by Piinks** [comment]
I'm going to close this in favor of a better implementation later. The related issue remains open: #28360

**Comment by RedBrogdon** [comment]
@goderbauer I've actually got that exact thing on my Q1 OKRs; I just haven't gotten to it yet. I'm always trying to find new ways to drive traffic to our videos. 😄

**Pull request closed without merging**
