### PR TITLE
Foldable support & TwoPane Widget

### PR DESCRIPTION
**Pull request by andreidiaconu**
- Adds support for foldable devices and display cutouts, in the form of Display Features exposed by MediaQuery.
- Adds TwoPane, a widget which helps with layouts on dual-screen devices and scaling a two pane design on larger screens.
- Adds HingeAvoidingModalWrapper, a widget can be used at the root of a Popup route in order to make the contents avoid the hinge area. It determines the safe areas of the display and uses one of them to render its child.
- Makes dialogs aware of the hinge, so they don't overlap.

This is based on the Engine support for Display Features: https://github.com/flutter/engine/pull/24756

A display feature is an area of the display that is obstructed by a hardware feature. For now, this works only on Android. There are three types of display features:

- Hinge - a physical separator between the two displays of the device.
display-feature-hinge
- Fold - You can view the fold like a hinge that has zero width. It tells us where the flexible display has a crease.
display-feature-fold
- Cutout - A cutout sits at the edge of the display and usually houses camera systems.
display-feature-cutout

Here is a preview of what this PR enables, on a dual-screen emulator:

hinge-aware-dialog-right

Issues that will be closed by this PR: 

- https://github.com/flutter/flutter/issues/49411

## Work in progress:

- Tests are still in progress
- The engine PR needs to be closed first: https://github.com/flutter/engine/pull/24756

### CODE REVIEW

**Comment by goderbauer** [comment]
Thanks for the PR. Unfortunately, this PR is in many aspects not following our style guide (see also https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo). Most of the issues are also pointed out by the analyzer (`flutter analyze --flutter-repo`). There's also commented out code in the PR making it unclear whether this is just a draft or if it's actually ready for review. Can you please clean this up to make it easier to actually review this? Thanks!

**Comment by andreidiaconu** [comment]
@goderbauer Yes. Will ping you when this is higher quality and also has tests.

**Comment by goderbauer** [comment]
OK, marking this as draft for now.

**Comment by goderbauer** [comment]
Some overall feedback from scanning through the code: It would be good to keep this a little more generic. The Dialogs and Pop-ups for example need to avoid all kinds of display obstructions and the API shouldn't assume that these obstructions divide the rendering space into two "screens" (not all obstructions will do). So, having a `screen` argument doesn't seem ideal. As an idea, maybe we could have an anchorPoint argument instead that specifies if the dialog cannot be rendered at its natural point (e.g. due to obstructions) it is pulled towards that point to stay clear of those obstructions. The point the user touched on screen to trigger the dialog could be used as a natural anchor point for most use cases, presumably. If no anchor point is provided, we'd use a heuristic to avoid obstructions (e.g. prefer higher over lower, prefer the leading edge over the trailing edge, etc).

Also, the TwoPane seems pretty specific to certain phone hardware and its also pretty independent of the framework. That widget may be best distributed as part of an external package.

**Comment by andreidiaconu** [comment]
I see your point on dialogs and will give the anchorPoint a try. I think it
is a good idea, but wonder if it complicates the api more than needed.
Renaming screen to safeArea would be less specific to dual screen form
factors.

TwoPane indeed helps with dual screen devices a lot, but is meant to easily
scale up the same layout to tablets, desktop and web. This is why I don’t
see it as a dual screen specific layout, but rather as a basic building
block that happens to work well on that form factor.

**Comment by andreidiaconu** [comment]
@goderbauer The code is now in line with the style guide and gives no messages during `analyze`. Made the dialogs use `anchorPoint` and fallback on `Directionality`. I'm turning my attention to tests. Since we want all checks to pass before we consider this Ready for review, this means that https://github.com/flutter/engine/pull/24756 needs to be merged first - I will update you when we make progress on that. 

For now I just wanted to let you know that your concerns were addressed, in case you want to give this another look and provide any other feedback.

**Comment by andreidiaconu** [comment]
@goderbauer I would like to offer an update on this PR:

- The [Engine PR](https://github.com/flutter/engine/pull/24756#issuecomment-902945863) that this depends on is now out of WIP status. It was marked as WIP while we waited for its main dependency, `androidx.window`, to be promoted to beta. 
- This PR now has tests for all the components it touches and the documentation is better.

The current status for this PR is that we are waiting for the Engine PR to be merged, but the code is ready for review, in case we want to speed things along in the meantime. I will gladly address any feedback I get, as I already did up to this point.

**Comment by goderbauer** [comment]
I believe this PR would be easier to review, land, and (if necessary) revert if it were split up into multiple PRs, one per feature listed in the bullet list in the PR's description.

**Comment by andreidiaconu** [comment]
Ok, I will split this into multiple PRs.

**Comment by 12people** [comment]
@andreidiaconu Any updates on this?

**Comment by andreidiaconu** [comment]
> @andreidiaconu Any updates on this?

Yes, the Engine changes are now able to make progress https://github.com/flutter/flutter/pull/89511 and once those are merged, focus moves to this. Also, I am breaking ths PR into smaller, more focused ones this week.

**Comment by andreidiaconu** [comment]
Here are the PRs that were split from this:
- https://github.com/flutter/flutter/pull/92906
- https://github.com/flutter/flutter/pull/92907
- https://github.com/flutter/flutter/pull/92909
- https://github.com/flutter/flutter/pull/92910

Everything still depends on getting the Engine support merged:
- Engine support: https://github.com/flutter/engine/pull/29447
- Framework integration of the engine support: https://github.com/flutter/flutter/pull/89511

@blasten @goderbauer I am closing this PR as it is now replaced by 4 other smaller PRs.

**Pull request closed without merging**
