### PR TITLE
Create a flag to change default behaviour of TextField maxLines

### LINKED ISSUE #15388: TextField starts with maxLines if it is set to anything other than null.
Setting `maxLines` allows as many lines up to that number, but it also initially starts with that many lines. So, setting `maxLines` to `5` starts with `5` lines, instead of `1`. Is this intended and how can I work around this?

Setting `maxLines` to null starts it at 1 line, but expands infinitely.

### PR DESCRIPTION
**Pull request by tuliomagalhaes**
fixes: #15388 and #18825.

When maxLines is set, the default behaviour of the TextField is to calculate the height based on number of lines. In some cases it's necessary to limit the number of lines of TextField, but the height need to grow as the lines is breaking, not as fixed size. Looking for alternatives in the issues, I found these 2, and nothing else helped me achieve this, the only alternative was to change the default behaviour of TextField.

### CODE REVIEW

**Comment by justinmc** [comment]
This looks like a solid PR for fixing this problem, but this is a delicate situation because any API change here needs to fit into the greater scope of all outstanding improvements for TextField layout.  Flutter maintains backwards compatibility, so any API change here can't be changed in the future.  The idea of `maxLinesIncrementalHeight` will likely need to be rethought to accommodate fixes to related issues.

I'm going to do some research on all of those related issues.  I'll post back in a bit with all the requirements that I can find and we can figure out a way forward.

**Comment by Tulioh** [comment]
One of my concerns is to not break the existing code of TextField, and with that in mind, the default value of `maxLinesIncrementalHeight` is `false`, and if you use the TextField without putting this attribute, the default behaviour will be the same as the current one.

**Comment by justinmc** [comment]
Alright I've opened an empty PR to start a conversation around these interconnected TextField height issues and proposed a potential solution: https://github.com/flutter/flutter/pull/27205

Please take a look and let me know what you think!  If there are any holes in the solution or anything that this PR would allow that the proposal wouldn't, I'm all ears.  If there is any work from this PR that can be recycled in the final solution then I totally support that as well.

**Comment by justinmc** [comment]
The work from this PR was moved to https://github.com/flutter/flutter/pull/27205, which has a larger scope.  See that PR for full details.

**Pull request closed without merging**
