### PR TITLE
Roll engine to 549c855e89341b97436b3417542fc8f997492df7

### PR DESCRIPTION
**Pull request by aam**
Changes since last engine roll:

```
549c855e8 Roll dart sdk to 4c9689c1d2da97d0aa25cf16cc90c2e463ad157f (#5559)
b19e2d4e7 Roll src/third_party/skia 63b3bfb711d7..5045e501d2ae (1 commits) (#5562)
01bc207da Roll src/third_party/skia dfbfc738a9ed..63b3bfb711d7 (5 commits) (#5561)
6070a657c Roll src/third_party/skia 3567c14a41cd..dfbfc738a9ed (12 commits) (#5557)
```

### CODE REVIEW

**Comment by jacob314** [comment]
This version of eval doesn't crash but doesn't work correctly either. Calls to evaluate an expression on a library throw exceptions when they shouldn't with the exceptions triggered within the frontend.
```
compiler message: Unhandled exception:
compiler message: NoSuchMethodError: The getter 'loader' was called on null.
compiler message: Receiver: null
compiler message: Tried calling: loader
compiler message: #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
compiler message: #1      IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:429)
compiler message: <asynchronous suspension>
compiler message: #2      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118)
compiler message: #3      new Future.sync (dart:async/future.dart:222)
compiler message: #4      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118)
compiler message: #5      _rootRun (dart:async/zone.dart:1126)
compiler message: #6      _CustomZone.run (dart:async/zone.dart:1023)
compiler message: #7      _runZoned (dart:async/zone.dart:1518)
compiler message: #8      runZoned (dart:async/zone.dart:1465)
compiler message: #9      CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117)
compiler message: #10     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:428)
compiler message: <asynchronous suspension>
compiler message: #11     IncrementalCompiler.compileExpression (package:vm/incremental_compiler.dart:103)
compiler message: #12     FrontendCompiler.compileExpression (package:vm/frontend_server.dart:448)
compiler message: <asynchronous suspension>
compiler message: #13     _FlutterFrontendCompiler.compileExpression (package:frontend_server/server.dart:55)
compiler message: #14     listenAndCompile.<anonymous closure> (package:vm/frontend_server.dart:650)
compiler message: <asynchronous suspension>
compiler message: #15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
```

**Comment by a-siva** [comment]
Do you still want to merge this or fix the issue that @jacob314 reports above and then merge?

**Comment by aam** [comment]
cc @DaveShuckerow

**Comment by aam** [comment]
I believe this roll is an incremental improvement over previous state of things, so would still merge this.

**Review by a-siva — APPROVED** [review]

**Comment by aam** [comment]
Root cause for https://github.com/flutter/flutter/pull/18591#issuecomment-398795191 seems to be https://github.com/dart-lang/sdk/issues/33087#issuecomment-398886925

**Pull request merged**
