### PR TITLE
Update SDK constraints to reflect the fact that set literals are being used

### PR DESCRIPTION
**Pull request by bwilkerson**
## Description

I am attempting to add a hint to the analyzer that is triggered if code is using a set literal but specifies an SDK constraint that allows it to be used with an SDK that does not support set literals. Unfortunately, the flutter repo contains several places where this hint would be triggered.

This PR updates the necessary SDK constraints to allow my change to land without breaking flutter.

## Related Issues

none

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
cc @devoncarew - This regressed analyzer performance.

**Comment by bwilkerson** [comment]
@Hixie I don't have much experience contributing to Flutter. I assume you mentioned the performance regression because some action needs to be taken, but I'm not sure what I need to be doing. Please advise.

I'm also at a loss to explain why changing the SDK constraints would impact the performance of the analyzer. The analyzer only uses the SDK constraints to check that no language features are being used where they might not be supported. The checks haven't changed; the only change is the version number that is now being read.

**Comment by Hixie** [comment]
@bwilkerson I have added some documentation here explaining what to do in the case of a performance regression: https://github.com/flutter/flutter/wiki/Tree-hygiene#regressions-in-performance

**Comment by bwilkerson** [comment]
Thanks!

**Pull request merged**
