### PR TITLE
Initialize _lastTextPosition with default value

### LINKED ISSUE #27772: text_painter: NoSuchMethodError: The getter 'offset' was called on null.
Flutter doctor

```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14 18A391, locale en-BY)
    • Flutter version 1.1.8 at /Users/r1zzu/flutter
    • Framework revision 985ccb6d14 (5 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/r1zzu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/r1zzu/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/r1zzu/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] IntelliJ IDEA Community Edition (version 2017.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.31.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • iPhone 6 • D5B9AE18-0DA0-4F13-8CAA-10CB70DAD228 • ios • iOS 12.1 (simulator)
```

Error

```
text_painter.dart in TextPainter.getOffsetForCaret at line 545
editable.dart in RenderEditable.getLocalRectForCaret at line 1050
editable_text.dart in EditableTextState._onFloatingCursorResetTick at line 683
listener_helpers.dart in _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners at line 124
animation_controller.dart in AnimationController._tick at line 697
ticker.dart in Ticker._tick at line 228
binding.dart in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback at line 990
binding.dart in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<fn> at line 906
Called from: libcompact_hash.dart in __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach
binding.dart in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame at line 904
binding.dart in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame at line 834
```

Got this error in sentry, however can't reproduce it locally

I'm calling `setState` when user submits content of `TextField` with consecutive `textInputController.clear();`

### PR DESCRIPTION
**Pull request by lesnitsky**
Closes #27772

### CODE REVIEW

**Comment by HansMuller** [comment]
I'm not sure if this is a good fix or not (haven't looked into #27772 yet). A regression test would be needed. That's essentially what @zoechi is asking for in https://github.com/flutter/flutter/issues/27772#issuecomment-462375224 is asking for.

**Comment by lesnitsky** [comment]
I've tested my own apps (chat app + several forms) and it worked well. I'll
do my best to reproduce this issue in a sandbox app though

**Comment by goderbauer** [comment]
This also seems to be causing a lot of test failures (see Cirrus checks).

**Comment by lesnitsky** [comment]
I'll be back with some details on how to reproduce this issue and probably a better fix :)

**Comment by HansMuller** [comment]
OK, sounds good.

**Pull request closed without merging**
