### PR TITLE
Updated skipped tests for widgets directory.

### PR DESCRIPTION
**Pull request by darrenaustin**
Part of #86396.

Updated the skip tests in the 'widgets' directory. Turned some tests back on, marked some as intentional in a comment or added issues where missing.

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/87879

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/87879

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/87879

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by Piinks** [comment]
Gold changes should be ignored here. Gold sometimes gets confused when the git history is overwritten. I have triaged the images as negative. I do not know if the check will clear (this has only happened once before). I'll wait and see (~5 minutes is when it updates the check).

**Comment by Piinks** [comment]
Checks cleared! @darrenaustin is this ready to land then?

**Pull request merged**
