### PR TITLE
CocoaPods flow step 2 - don't pod install unless project has plugins

### PR DESCRIPTION
**Pull request by xster**
For #9580

Reverts #9719 

Only run pod install if the user uses pulls in pods via pub and plugins. 

Also removes all references of the channel integration test's dependencies on cocoapods since the artifacts checked in were partial and wouldn't build without a first pod install even though it doesn't actually use cocoapods. (some context/assumptions in #9621)

### CODE REVIEW

**Comment by xster** [comment]
cc @cbracken we talked about some related stuff

**Review by collinjackson — APPROVED** [review]

**Comment by mravn-google** [comment]
cc @jakobr-google

**Review by mravn-google — APPROVED** [review]
LGTM on changes to the integration test.
RSLGTM on changes to flutter tooling.

**Comment by cbracken** [comment]
lgtm

**Pull request merged**
