### PR TITLE
Fix: "ProcessException: %1 is not a valid Win32 application."

### PR DESCRIPTION
**Pull request by blasten**
## Description

Add quoted strings to indicate where the file name ends and the arguments begin otherwise, the file name is ambiguous. https://github.com/dart-lang/sdk/issues/37751

## Related Issues
https://github.com/flutter/flutter/issues/19359
https://github.com/flutter/flutter/issues/33972
https://github.com/flutter/flutter/issues/36607
https://github.com/flutter/flutter/issues/36171
https://github.com/flutter/flutter/issues/36152
https://github.com/flutter/flutter/issues/35695
https://github.com/flutter/flutter/issues/33023
https://github.com/flutter/flutter/issues/31550
https://github.com/flutter/flutter/issues/19304
https://github.com/flutter/flutter/issues/15014

## Tests

Unit tests in `process_test.dart`

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Saifallak** [comment]
is this fix for #33972 too? or related?

**Comment by jonahwilliams** [comment]
Should this also handle wrap the injected implementation of process manager?

**Comment by blasten** [comment]
:/ this needs to be fixed in https://github.com/google/process.dart instead.

**Comment by zanderso** [comment]
So that we have a trail of breadcrumbs that folks can follow, could you explain a bit why this has to be fixed there? Thanks!

**Comment by blasten** [comment]
I found that the process manager also checks if the [executable exists](https://github.com/google/process.dart/blob/master/lib/src/interface/local_process_manager.dart#L112). Therefore, the check fails if the quotes are added in `flutter_tools/lib/src/base/process.dart`.

The process manager is what calls `Process.runSync` and `Process.run`.

**Pull request closed without merging**
