### PR TITLE
[flutter_tools] Support IntelliJ 2020.1 and later on Linux and Windows

### PR DESCRIPTION
**Pull request by jparound30**
## Description

Even after PR #57963 merged, Flutter tools do not recognize IntelliJ IDEA/Community 2020.1 on Linux and Windows.

This PR will update IntelliJ IDEA/Community validation logic for 2020.1 and later on Linux and Windows.

## Related Issues

Ref: #57963
Ref: #57684
Ref: #54867
Ref: #58384

## Tests

I added the following tests:
`packages/flutter_tools/test/general.shard/intellij/intellij_validator_test.dart`

- 'legacy intellij(<2020) plugins check on linux'
- 'intellij(2020.1) plugins check on linux (installed via JetBrains ToolBox app)'
- 'intellij(>=2020.2) plugins check on linux (installed via JetBrains ToolBox app)'
- 'intellij(2020.1~) plugins check on linux (installed via tar.gz)'
- 'legacy intellij(<2020) plugins check on windows'
- 'intellij(2020.1 ~ 2020.2) plugins check on windows (installed via JetBrains ToolBox app)'
- 'intellij(>=2020.3) plugins check on windows (installed via JetBrains ToolBox app and plugins)'
- 'intellij(2020.1~) plugins check on windows (installed via installer)'

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Hi @jparound30 ,

This is a really well written PR, and with good test coverage too. I'm sorry it took so long to get to reviewing it, but we were a bit stuck on what our plans for the IDE validators are.

After discussing it for a while, it sounds like we're going to drop the IDE validation all together. It was proving to be a lot of work to maintain, and was often giving users the impression that they needed to use Android Studio/Intellij/VsCode - which isn't the case today.

Since we're going to turn down the feature, we can't merge this PR. I'm sorry that we didn't get to this one sooner, but I really appreciate the effort you put into it and I would love to see more contributions from you in the future.

**Comment by jonahwilliams** [comment]
Hi @jparound30 

We've backtracked a bit and we're still going to support IDE validators. If you are willing to rebase and update I'm happy to review and help you land this

**Comment by jparound30** [comment]
Hi @jonahwilliams 

Thank you for giving me the opportunity!
I've updated this pull request so please review it.

**Comment by jonahwilliams** [comment]
That is great to hear! I will take a look first thing in the morning 😄

**Review by jonahwilliams — COMMENTED** [review]
Just some minor style nits, otherwise this looks great.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Landed! Thank you so much @jparound30

**Pull request merged**
