### PR TITLE
Plug TextDirection into box_decoration background gradient

### PR DESCRIPTION
**Pull request by sroddy**
Without this, applying an AlignmentDirectional to a LinearGradient inside a BoxDecoration background was causing an assert.

### CODE REVIEW

**Comment by gspencergoog** [comment]
Thanks for the help!  Could you please add a test for this condition to this PR?

**Comment by sroddy** [comment]
I added a test that was triggering the assertion, thus failing, before applying the fix.
However I didn't find a way to check that the shader is really applied by the Paint.

Suggestions are welcome, otherwise you are welcome to merge :)

**Comment by Hixie** [comment]
Thanks!

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
