### PR TITLE
Use unselected styles for the tabs adjacent to the selected tab

### LINKED ISSUE #16169: Widget: TabBar labelStyling buggy
## Steps to Reproduce

Using a `TabBar` for the bottom of a `AppBar` and trying to set the style for the "selected" tab to be bold text, and the "unselected" tabs to be normal text doesn't seem to work.

Here's what it looks like when I set labelStyle to bold and unselectedLabelStyle to normal:
screen shot 2018-04-02 at 10 23 27 pm

As you can see from the shot, "Recommended" and "Articles" is also bold, even though they are not selected.

This is the code I've used:

```
TextStyle activeTabLabelStyle = new TextStyle(fontSize: 15.0, fontWeight: FontWeight.bold);
TextStyle tabLabelStyle = new TextStyle(fontSize: 15.0, fontWeight: FontWeight.normal);


new TabBar(
            controller: _controller,
            indicatorColor: CoreTheme.MainColor,
            indicatorWeight: 1.0,
            labelColor: CoreTheme.MainColor,
            labelStyle: activeTabLabelStyle,
            unselectedLabelStyle: tabLabelStyle,
            unselectedLabelColor: Colors.black,
            isScrollable: true,
            tabs: [
              new Tab(text: "Latest"),
              new Tab(text: "Recommended"),
              new Tab(text: "News"),
              new Tab(text: "Articles"),
              new Tab(text: "Blogs")
            ],
          )
```

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/16169

### CODE REVIEW

**Comment by jason-simmons** [comment]
@HansMuller

**Comment by HansMuller** [comment]
This looks correct but the existing tests should pass

**Comment by jason-simmons** [comment]
Reversed the animation of the tabs adjacent to the selected tab, and added tweening of the tabs' text styles

PTAL

**Review by HansMuller — APPROVED** [review]
LGTM

**Pull request merged**
