### PR TITLE
Make Image sizes to double instead of int

### LINKED ISSUE #136509: ResizeImage width should be of type double, not type int because you usually resize based on constraints in double
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

ResizeImage width should be of type double, not type int because you usually resize based on constraints in double
```
      return LayoutBuilder(builder: (context, constraints) {
        return Image(
            image: ResizeImage(
          FileImage(File(pathRefImage)),
          width:
              (constraints.maxWidth * MediaQuery.of(context).devicePixelRatio)
                  .toInt(),
        ));
```

### Proposal

ResizeImage width should be of type double, not type int because you usually resize based on constraints in double

### PR DESCRIPTION
**Pull request by prasadsunny1**
Fixes https://github.com/flutter/flutter/issues/136509

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

There is probably not a breaking change because integer value is automatically cast to float.
So, for existing codebases, devs will start seeing a warning that they do not need to convert an expression's float result to int.

For eg:
```
Image(
...
   height: (2/3).toInt() // The analyzer will show a warning to users about unnecessary cast
...
)
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by prasadsunny1** [comment]
Hi @suyashmadhesia and @piedcipher , I have tried to fix this and I have raised a Draft PR.
But I am not able to figure out how can I fix the failing build.
```

| ../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/painting/binding.dart:116:20: Error: The argument type 'double?' can't be assigned to the parameter type 'int?'.
|       targetWidth: cacheWidth,
|                    ^
| ../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/painting/binding.dart:117:21: Error: The argument type 'double?' can't be assigned to the parameter type 'int?'.
|       targetHeight: cacheHeight,
|                     ^
| ../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/painting/image_provider.dart:1297:46: Error: The argument type 'double?' can't be assigned to the parameter type 'int?'.
|             return ui.TargetImageSize(width: targetWidth, height: targetHeight);
|                                              ^
| ../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/painting/image_provider.dart:1297:67: Error: The argument type 'double?' can't be assigned to the parameter type 'int?'.
|             return ui.TargetImageSize(width: targetWidth, height: targetHeight);
|                                                                   ^
| ../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/painting/image_provider.dart:1331:46: Error: The argument type 'double' can't be assigned to the parameter type 'int?'.
|             return ui.TargetImageSize(width: targetWidth, height: targetHeight);
|                                              ^
| ../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/painting/image_provider.dart:1331:67: Error: The argument type 'double' can't be assigned to the parameter type 'int?'.
|             return ui.TargetImageSize(width: targetWidth, height: targetHeight);
|                                                                   ^
| ../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/painting/image_provider.dart:1282:44: Error: The argument type 'TargetImageSize Function(double, double)' can't be assigned to the parameter type 'TargetImageSize Function(int, int)?'.
|  - 'TargetImageSize' is from 'dart:ui'.
|       return decode(buffer, getTargetSize: (double intrinsicWidth, double intrinsicHeight) {
```

**Comment by suyashmadhesia** [comment]
`TargetImageSize` class belongs to dart sky_engine here its definition

class TargetImageSize {

  const TargetImageSize({this.width, this.height})
      : assert(width == null || width > 0),
        assert(height == null || height > 0);


  final int? width;

  final int? height;

  `@override`
  String toString() => 'TargetImageSize($width x $height)';
}

that's why it is failing the build.

**Comment by prasadsunny1** [comment]
> class TargetImageSize {


I checked this class in engine and I found out that it surly needs an integer, On the dart side, I am not able to figure out if it we should take double input and then round it or not. I feel we should not do that. 
@suyashmadhesia , would you like to take this issue and PR forward?

**Comment by suyashmadhesia** [comment]
@prasadsunny1 It doesn’t make any sense to take double as input and round it off. Maybe we can ask in the community forum about the use case of the TargetImageSize class. I tried this a week ago and got the same issue. Maybe we need to change the dart engine's first. I still don't know the correct resolution for this issue.

**Comment by prasadsunny1** [comment]
Currently my understanding is that the `TargetImageSize` stores actual pixel height and width. Pixels can not be a fractional number. But yes, please check with community

**Pull request closed without merging**
