### PR TITLE
[tool][web] Fix flutter.js in Safari 13

### LINKED ISSUE #104646: Flutter web not working on iOS web having OS version less than 14.1
When testing the Flutter web app on iOS safari with OS 13.4 and 13.7, it is not working.
We tested it on OS 15.2 and 15.4, it is working fine.

Sample: https://github.com/deepak786/ios_web_issue
web build: https://deepak786.github.io/ios_web_issue_build

It also works fine on the Desktop browsers and Android web browsers.

I inspected the console using the Safari web inspector, it showed the following error:

```
[Error] SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.
	(anonymous function) (flutter.js:23)
[Error] ReferenceError: Can't find variable: _flutter
	(anonymous function) (ios_web_issue_build:80)
```

The same issue happens with [Flutter Gallery website](https://gallery.flutter.dev/#/).

When I searched about the above error, it seems that flutter.js is declaring the variables in a way that is not supported by iOS 13.
This feature is added in iOS 14.1.
Ref: https://stackoverflow.com/questions/60026651/safari-unexpected-token-expected-an-opening-before-a-methods-paramet

Video showing the error:
https://drive.google.com/file/d/1nFupkQ2ZqHZnXDaBRuP9CO8GMXdkVCPb/view?usp=sharing

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-x64, locale
    en-US)
    • Flutter version 3.0.0 at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/appleapple/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/appleapple/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Deepak’s iPhone (mobile) • 00008101-00117D690A80801E            • ios
      • iOS 15.4.1 19E258
    • iPhone 11 Pro (mobile)   • 56817DBD-D6E9-4308-84F2-65A261C2095C • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)          • macos                                •
      darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)             • chrome                               •
      web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

### PR DESCRIPTION
**Pull request by ditman**
The current version of `flutter.js` is using 'public class fields' ([docs](https://caniuse.com/mdn-javascript_classes_public_class_fields)) that weren't supported in Safari until v14.1.

This PR removes the public class field syntax, and uses instead a 'constructor' method to initialize public fields in the FlutterLoader class, which is more broadly supported ([docs](https://caniuse.com/mdn-javascript_classes_constructor)), importantly by Safari 13.

Fixes https://github.com/flutter/flutter/issues/104646

## Testing

Testing needs to be manual, because it's almost impossible to get Safari 13 on any updated device. An iOS simulator (or an old device) are required to use the affected browser.

This PR is now deployed here:

* https://dit-bootstrap-tests.web.app

Point Safari on an iOS Simulator on iOS 13 there to see that it loads. Compare with gallery.flutter.dev.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by mdebbar — APPROVED** [review]
LGTM

**Review by yjbanov — APPROVED** [review]
lgtm

**Comment by yjbanov** [comment]
A test exemption is reasonable because we don't have infra to test on ancient versions of iOS Safari.

**Comment by Hixie** [comment]
can we test this by scanning the code for patterns known to not work in old Safaris we want to support?

if not:
test-exempt: intractable

**Comment by ditman** [comment]
> can we test this by scanning the code for patterns known to not work in old Safaris we want to support?

@Hixie I tried to use eslint + eslint-plugin-compat specifying the browsers we want to support, and it wasn't very trust-worthy. If eslint was adjusted to recognize the syntax (es2022) for the browsers that would support it to pass, the `compat` plugin wouldn't complain about it for Safari 13. This would have also required to bring node as a build dependency (or to somehow shrink-wrap the `eslint` tool, which I'm not sure is possible).

I also looked at `esbuild`, which seems more promising, because you can feed it JS written in any syntax level, and it'll  automatically transform it to something that complies with a specific target (targets can be `es6` but also `safari 13`, or a combo of them), even minify it, so this might stop being a problem altogether. I've created an issue to dive deeper into that option here: https://github.com/flutter/flutter/issues/104777 (which could be a great package for post-processing of the web assets).

For now, I'm going to land this, but it is true that there's more changes coming here that are hard to test (if at all possible)

_(PS: Another way of handling this is converting flutter.js in a node package, maintained separately from flutter/flutter_tools, but that might be overkill)_

**Pull request merged**
