### PR TITLE
[flutter_tools] remove unused JSON schema

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

This code is not used, except for test coverage of itself.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
@DanTup @devoncarew do any of the IDEs use this file? As far as I can tell it is not used at all by the flutter tool, and isn't actually the source of truth for what is/isn't allowed.

**Comment by devoncarew** [comment]
> @DanTup @devoncarew do any of the IDEs use this file? As far as I can tell it is not used at all by the flutter tool, and isn't actually the source of truth for what is/isn't allowed.

No, not to my knowledge. We do separate pubspec validation - some IntelliJ native, and some from the analysis server.

**Comment by DanTup** [comment]
Also not used by VS Code - there's no pubspec validation in there except what comes from the analysis server.

**Comment by jonahwilliams** [comment]
Thanks all!

**Review by jmagman — APPROVED** [review]
LGTM let's see if anything breaks!

**Pull request merged**
