### PR TITLE
Update gitignore template for flutter create

### PR DESCRIPTION
**Pull request by timsneath**
The default .gitignore from `flutter create` is very minimal, resulting in lots of runtime binaries being checked in with new projects. This PR brings across the [.gitignore](https://github.com/flutter/flutter/blob/master/.gitignore) from the root of flutter/flutter, with the exception of the items that are specific to the Flutter repo itself.

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Review by cbracken — APPROVED** [review]
lgtm

**Comment by timsneath** [comment]
Yes, I think that would be my preference also. Looking in these two files, the iOS one looks much more comprehensive than the Android one (although there are some entries in the `ios/.gitignore` that I don't recognize, like `*.moved-aside`). 

I wonder if we can simply delete the child directory files? To test, I ran `flutter create` and `flutter build ios` with two separate projects, one with just my new `.gitignore` and one with both this and the `android/` and `ios/` `.gitignore` files. Aside from the extra two .gitignore files, the list of files to commit were identical.

**Review by originme — APPROVED** [review]

**Comment by timsneath** [comment]
Per my proposal last week and my conversation with @cbracken yesterday, I've removed the subfolder gitignores. I'll merge this as soon as I get an updated LGTM from him.

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm

**Pull request merged**
