### PR TITLE
Add multiple selection feature to DropdownButton

### PR DESCRIPTION
**Pull request by jimshepherd**
Add feature to DropdownButton that allows multiple selections to be made in a similar fashion as Angular Material.

This implementation uses an additional argument, "values", which contains the list of selected values. The Angular and other implementations just use the "value" argument to hold the list along with a Boolean argument "multiple".  This feature can be changed to the "value" / "multiple" with some help with Dart typing.

Note that this implementation only allows a single value to be toggled before the dropdown is closed. A "Close" button could be added to the bottom of the selection list to allow multiple changes to be made but I'm not sure if that work flow is actually better on mobile.

I will add tests and address other requirements if this implementation is acceptable.

Addresses issue #22927

### CODE REVIEW

**Comment by jimshepherd** [comment]
> Once you've signed (or fixed any issues), please reply here (e.g. `I signed it!`) and we'll verify it.

I signed it

**Comment by HansMuller** [comment]
Sorry to have taken so long to get to this. It looks like you've put a non-trivial amount of effort into this contribution!

We'd prefer to support creating multiple selection menus like this by making sure that it's moderately straightforward to do with the existing dropdown button classes. It looks like it's already possible to do something like what was done here by creating a menu with checkbox items whose values toggle when selected: https://gist.github.com/HansMuller/a46c847cd38c9394405975a2b95ace81

dropdown1

dropdown2

**Comment by HansMuller** [comment]
I'm going to close this because https://github.com/flutter/flutter/pull/25955#issuecomment-466215221

Sorry about that.

**Comment by jgoyvaerts** [comment]
@HansMuller The code gist you suggested doesn't work correctly, it closes the dropdown everytime you select an item. Can you reevaluate merging this PR because right now there is no proper dropdown multiple selection support in Flutter

**Pull request closed without merging**
