### PR TITLE
Remove use of "implements Function" in tests.

### PR DESCRIPTION
**Pull request by ferhatb**
## Description

implements/extends Function is being deprecated. This PR prepares flutter code base.

## Related Issues

Example Dart roll failure: https://cirrus-ci.com/task/4670267658076160

## Tests

Already covered by icon_button_test and implicit_animations_test.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

### CODE REVIEW

**Review by ditman — APPROVED** [review]
LGTM

**Review by yjbanov — APPROVED** [review]

**Comment by ditman** [comment]
This looks like something that could be achieved with some Mockito mocks, instead of rolling our own function-like handler?

**Comment by yjbanov** [comment]
@vsmenon @sigmundch  Surprisingly this only failed on the Web, not on mobile. Is there a discrepancy between Web and VM we should be aware of?

**Comment by vsmenon** [comment]
@yjbanov - web and mobile should behave the same here.  Are these files exercised in both places?  Do both have consistent settings wrt failing on warnings?

fyi - @johnniwinther

**Comment by yjbanov** [comment]
> Are these files exercised in both places?

Yes.

> Do both have consistent settings wrt failing on warnings?

/cc @jonahwilliams do you know?

**Pull request merged**
