### PR TITLE
Allow Image as Icon

### PR DESCRIPTION
**Pull request by ghost**
With this change you can put an Image as Icon in a PopupMenuButton.

### CODE REVIEW

**Comment by xascis** [comment]
I signed it!

**Comment by xascis** [comment]
I signed it!

**Comment by HansMuller** [comment]
This looks like a sensible change. The PopupMenuButton's icon is just passed along to IconButton and IconButton's icon property is a Widget.

This PR should really include a test (a smoke test really) that builds a popup menu button with a Widget icon. You can just add one to packages/flutter/test/material/popup_menu_test.dart.

Given that I'll be happy to land this PR.

**Comment by xascis** [comment]
I've found that popup_menu has a child property. So, you can add an Image as Icon

Therefore, I'm closing this pull request because it's not necessary. 

Thanks.

**Pull request closed without merging**
