### PR TITLE
Reland: Skip painting hidden children of a sliver list

### PR DESCRIPTION
**Pull request by liyuqian**
https://github.com/flutter/flutter/pull/18465 Handled nonzero offset incorrectly (see https://github.com/flutter/flutter/issues/18527) and this should fix it.

### CODE REVIEW

**Comment by liyuqian** [comment]
@Hixie @jonahwilliams  : 
I tried to add a unit test but it seems that [mock_canvas.dart:506](https://github.com/flutter/flutter/blob/master/packages/flutter/test/rendering/mock_canvas.dart#L506) always gives a zero offset by `renderObject.paint(context, Offset.zero);`. Therefore the unit test added (copied from https://github.com/flutter/flutter/issues/18527) in this PR can't catch our mistake in https://github.com/flutter/flutter/pull/18465. Please let me know if there's a way to test a nonzero offset in paint.

**Comment by Hixie** [comment]
Feel free to adapt mock_canvas.dart as needed.

**Comment by liyuqian** [comment]
Please take a look. BTW, the flutter-build failure seems to be a flake. How can I retry it?

**Comment by liyuqian** [comment]
Ping... @jonahwilliams @goderbauer @Hixie

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by andreidiaconu** [comment]
Is it possible that this is related https://github.com/flutter/flutter/issues/18713 ? I am asking because this used to work a week ago and looking through the latest commits, this seems the most related to me. Thanks for having a look!

**Pull request merged**
