### PR TITLE
Update `flutter build apk -h` to indicate that target arch is not supported in debug mode. 

### PR DESCRIPTION
**Pull request by reidbaker**
Part of #153359

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by andrewkolos — COMMENTED** [review]
In hindsight, I am afraid that users don't read help text very often (or that they might forget details like these by the time it's relevant to them).

Genuine question: should we go further by printing a warning when the user uses `--target-platform` together with `--debug`?

**Comment by reidbaker** [comment]
> In hindsight, I am afraid that users don't read help text very often (or that they might forget details like these by the time it's relevant to them).
> 
> Genuine question: should we go further by printing a warning when the user uses `--target-platform` together with `--debug`?

I don't think so if I was going to modify the implementation then I would make the flags work together. I know you have a bunch on your plate and it is fair to expect help to indicate if flags don't work together. The updated documentation is better than ignoring the bug and faster than modifying the behavior. 

I found in https://github.com/flutter/flutter/issues/153359#issuecomment-2310496925 if you add split-per-abi then the bug author can get the behavior they want.

**Comment by reidbaker** [comment]
I should add that the consequences of getting this dual flag behavior are constrained. The primary issue is build speed and app size. That said most users are uploading to google play which uses an AAB and needs all the architectures. 

This is a dev workflow that we can make better when it is a priority.

**Review by andrewkolos — APPROVED** [review]
> The updated documentation is better than ignoring the bug and faster than modifying the behavior.

Agreed.

LGTM

**Pull request merged**
