### PR TITLE
hasStrings support for eliminating clipboard notifications

### LINKED ISSUE #60145: Unsolicited iOS14 clipboard permission prompt
At WWDC2020, Apple announced that it was cracking down on clipboard sniffing by showing a prompt when an app attempts to access the clipboard.  This likely means that Flutter apps that feature text input will trigger this at strange times.

As of https://github.com/flutter/flutter/pull/54902, Flutter began checking the clipboard contents to decide whether or not to show the paste button in the text selection menu.  Previously, it would always show the button, even when nothing pasteable existed in the clipboard.

When exactly are Flutter apps seeing this clipboard permission dialog?  What should we do about it?

Some options:

  1. Revert to the old behavior (show the paste button regardless of clipboard contents).
  1. Revert only for iOS, or only or iOS 14.  Provide the developer an option to enable the feature on iOS 14 anyway?

### PR DESCRIPTION
**Pull request by justinmc**
Previously, the framework was looking at the actual contents of the clipboard in order to decide if it could paste or not.  This caused apps to show a notification ("app pasted from app") on certain platforms (currently iOS 13+ and Android 12+).

Screen Shot 2021-08-04 at 12 13 55 PM

After a bunch of engine work linked below, we now have engine methods that can check the clipboard status without accessing the contents of the clipboard on supported platforms ([Android](https://developer.android.com/reference/android/content/ClipboardManager#getPrimaryClipDescription()) and [iOS](https://developer.apple.com/documentation/uikit/uipasteboard/1829416-hasstrings?language=objc)).

This PR wires these engine methods up in the framework.  On platforms that don't have support for methods like these, hasStrings still accesses the clipboard contents in the engine.

### Related issues and PRs

Currently waiting for https://github.com/flutter/engine/pull/27749.

Closes https://github.com/flutter/flutter/issues/60145
Partial fix for https://github.com/flutter/flutter/issues/74139 (Android 12+)
Depends on iOS engine support: https://github.com/flutter/engine/pull/19859
Depends on Android engine support: https://github.com/flutter/engine/pull/20393
Depends on Android 12 engine support: https://github.com/flutter/engine/pull/27215
Depends on Mac engine support: https://github.com/flutter/engine/pull/20531 
Depends on Linux engine support: https://github.com/flutter/engine/pull/21388
Depends on Windows engine support: https://github.com/flutter/engine/pull/27749
Reopened from https://github.com/flutter/flutter/pull/61774

Makes work arounds like https://github.com/flutter/flutter/pull/86791 obsolete.

### Fuchsia
Flutter on Fuchsia currently has no clipboard support.  When it gets clipboard support we should also include support for hasStrings, even if it just uses getData.

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 3 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/87678

**Comment by skia-gold** [comment]
Gold has detected about 7 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/87678

**Review by LongCatIsLooong — APPROVED** [review]
LGTM

**Review by wytesk133 — APPROVED** [review]

**Comment by vysotsky** [comment]
Hello. Since this PR is not in Stable yet, is there any workaround to avoid having this notification? Idk, maybe somehow disable Handoff programatically for specific project? Or something else?
Because now it seems that as a developer I'm forced to either stick on using outdated flutter version or start using unstable Master. None of these options is good enough for me.
Thanks.

**Pull request merged**
