### PR TITLE
Bump collection dependency to 1.14.5

### PR DESCRIPTION
**Pull request by srawlins**
collection 1.14.5 includes method stubs for new methods being added to core libraries in Dart 2.

### CODE REVIEW

**Comment by srawlins** [comment]
CC @tvolkert

**Comment by srawlins** [comment]
Woohoo green Travis!

**Comment by tvolkert** [comment]
LGTM

**Comment by Hixie** [comment]
Did you just run the `flutter update-packages --force-update` script to do this?

**Pull request merged**
