### PR TITLE
Improve doctor output on incomplete Visual Studio installation

### PR DESCRIPTION
**Pull request by loic-sharma**
Flutter doctor warns if the user is updating Visual Studio or has paused a Visual Studio update. The current output recommends reinstalling Visual Studio. This is unnecessary as the user should be able to use the Visual Studio Installer app to complete the installation:

image

This message is covered by this existing test:

https://github.com/flutter/flutter/blob/229b74d987720a0437039b6e44e13f20fb94ad51/packages/flutter_tools/test/general.shard/windows/visual_studio_validator_test.dart#L68-L81

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by andrewkolos — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
Ahh, I see now the context of your question. In this case, I would say copy pasting the relevant error message to your test, and either renaming the existing test or creating a new one with a name that makes it clear this is an expectation will help document this behavior and prevent regression from clueless tool maintainers :)

**Comment by loic-sharma** [comment]
I updated the tests, please take another look @andrewkolos @christopherfujino. Thanks!

**Review by andrewkolos — APPROVED** [review]
LGTM

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
The customer_testing failure is actively being worked on upstream. See discord #tree-status for more context.

**Comment by christopherfujino** [comment]
Filed b/298053054 and manually overrode Google testing

**Comment by loic-sharma** [comment]
@christopherfujino Thanks! Looks like Google testing is now hitting a second issue, filed b/298076936

**Comment by christopherfujino** [comment]
Screenshot from 2023-08-30 09-39-17
:'(

**Pull request merged**
