### PR TITLE
[BREAKING CHANGE] Introduce ImageStyle and DefaultImageStyle

### PR DESCRIPTION
**Pull request by ds84182**
**THIS IS A BREAKING CHANGE, STUFF _WILL_ BREAK!!**

This moves all parameters from Image, except for the ImageProvider, into a new class: ImageStyle. ImageStyle, like TextStyle, can be merged with another ImageStyle and can be copied with new values. 

This PR also implements DefaultImageStyle, which, like DefaultTextStyle, allows you to give a subtree a base ImageStyle. The fallback style also contains the default values that RawImage expects (repeat, currently) and a default value for gaplessPlayback (which is false). Also, the difference between `new DefaultImageStyle` and `DefaultImageStyle.merge` is highlighted, and also advises users of `new DefaultImageStyle` to make sure they inherit the values from the default ImageStyle.

I've also provided a unit test for DefaultImageStyle. This also allowed me to find a bug in RenderImage, where the colorBlendMode setter didn't actually update the value. There should probably be a lint for that >_<;

Also, all existing code using Image has been updated (Gallery, Complex Layout, Flutter Markdown).

### CODE REVIEW

**Comment by Hixie** [comment]
Can you elaborate on the motivation here? What problem does this solve?

**Comment by ds84182** [comment]
Say I had an album widget that displays album art in multiple places (in the AppBar when expanded and in ListTiles).

For the AppBar, you could use BoxFit.fitWidth to keep contents from being scaled (just clipped), and in the ListTiles you could use BoxFit.contain to ensure that the entire area gets filled. Without this, you'd have to pass around ImageProviders, but then it limits you from setting a color filter, changing alignment, etc. Also, passing around ImageProviders would limit your code to only showing images instead of taking any widget.

In an application I'm working on, I grab a widget from the model that would usually be an Image, but I would also like to pass Placeholders (from a dummy data model which has no actual Images) or do an animation on load later down the road.

**Comment by sethladd** [comment]
@ds84182 I'm a PM on Flutter, and I'd love to learn more. If you're up for it, please send me an email: sethladd @ google. Thanks!

**Comment by Hixie** [comment]
This sounds very similar to IconTheme, which we use to solve this problem for icons. Maybe we should extend what IconTheme does? IconTheme is used by IconImage to apply this to Images, as well as by Icon to apply it to text-based Icons. It does size, opacity, and colour, right now.

**Comment by Hixie** [comment]
@ds84182 any opinions on the IconTheme thing?

@abarth any opinions?

**Comment by ds84182** [comment]
I'm quite confused at how extending IconTheme would be an alternative to this, could you clarify?

**Comment by Hixie** [comment]
Well IconTheme is basically your DefaultImageStyle, just for ImageIcon instead of Image.

**Comment by ds84182** [comment]
I don't see a reason to extend what IconTheme does because images have more style properties than text does. IconTheme is currently limited to what both Image and Text have in common (size, opacity, color), while ImageStyle controls these (size, opacity, color) and more (fit, blending, repeat modes)... Perhaps I'm misinterpreting extend here...

**Comment by Hixie** [comment]
Yeah, if you want to be able to control the repeating then that wouldn't fit IconTheme.

I don't feel doing this for Image widgets as a whole would be a great idea. Imagine if someone enables repeating at the root of their app for whatever reason. Now all their image icons and avatars would look weird. I think it's non-intuitive for images to have this kind of shared behaviour.

I think it would make more sense to have a new AlbumTheme widget and an Album widget, and have the Album widget pass the relevant properties on to the Image from the AlbumTheme.

**Comment by Hixie** [comment]
(That approach would also let you have separate inheritance for icons, avatars, albums, and other categories of images, rather than having all of them share a single group of properties.)

**Comment by Hixie** [comment]
I think we shouldn't do this, for the reasons given above. I'm going to close this PR. I apologise that your experience with Flutter is that we reject your input, and I hope you understand that that makes me sad too. :-( Your code quality was very high and I would love to see more contributions. I encourage you to discuss major changes first, to get people to buy in to the solutions before writing code.

Thanks for your contribution.

**Pull request closed without merging**
