### PR TITLE
Implement Double Tap Handling in TextField and Editable

### LINKED ISSUE #9288: Double-tap to select word in CupertinoTextField
## Steps to Reproduce

1. Tap in a text field in a Flutter app.
1. Enter some text with spaces; e.g., `foo bar baz`.
1. Double-tap on a word.

~On iOS, the double-tapped word should be selected. This behaviour is iOS-specific and does not apply on Android.~
The double-tapped word should be selected.

## Flutter Doctor

[✓] Flutter (on Mac OS X 10.12.4 16E195, channel master)
    • Flutter at /Users/cbracken/src/flutter/flutter
    • Framework revision 1b948cbb85 (2 days ago), 2017-04-05 12:27:59 -0700
    • Engine revision 5d9a642257
    • Tools Dart version 1.23.0-dev.11.5

### PR DESCRIPTION
**Pull request by NikoYuwono**
Fix [#9288](https://github.com/flutter/flutter/issues/9288)

### CODE REVIEW

**Comment by xster** [comment]
Seems sensible. @cbracken might have some ideas for how to add test to these.

**Comment by xster** [comment]
Thanks for adding tests! Please make sure the existing Cirrus tests pass. You can see their details by clicking into the 'Details' link of each row that has an X

**Comment by NikoYuwono** [comment]
@xster Anytime! I planned to fix all affected test, but want to test my solution on the main one first. Now all checks have passed.

I still have one concern though, currently to prevent the tap event being held by DoubleTapRecognizer until the timeout, I added 300 milliseconds delay to pump(), to make sure the up event is properly passed after tap event has been released by DoubleTapRecognizer.

In real world practice I don't notice any problem (confirmed in iPhone 7 Plus and Huawei P20 Pro),
but I wonder if this is the correct way or there is a better approach to this or not.

Maybe @cbracken have some ideas?

**Comment by GaryQian** [comment]
The logic looks good to me, but I don't think I understand the testing setup well enough to address your concern, I have requested some people who might be able to.

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
Thanks for sending this PR @NikoYuwono! This has been a pet peeve of mine for a while now!

lgtm

**Comment by Hixie** [comment]
@GaryQian Looks like this broke some devicelab tests. Can you revert while you investigate further? Thanks!

**Comment by jonahwilliams** [comment]
I think this change adds the double-tap action to both Android and iOS - the bug says it should only be for iOS.

**Comment by jonahwilliams** [comment]
Ahh it looks like this behavior should also be on later apps too - I can update the semantics test then

**Comment by jonahwilliams** [comment]
err, it is breaking other targets too - we should rollback

**Comment by cbracken** [comment]
The original bug was for iOS only, but Android has since adopted this behaviour. Ideally this should be enabled from Android M onwards and disabled for versions prior to that.

**Comment by NikoYuwono** [comment]
@HansMuller I should have documented it better like on the other test, but yes 300ms is the doubleTapTimeout ([reference](https://github.com/flutter/flutter/blob/eda03e2586b186ffcf8ea2d4424232710dbb7c81/packages/flutter/lib/src/gestures/constants.dart#L31), [usage](https://github.com/flutter/flutter/blob/a07d3719a1fe58c0c43ffde7079be291640fa98b/packages/flutter/lib/src/gestures/multitap.dart#L211)).

The reason why I added doubleTapTimeout is to make sure the up event is properly passed after tap event has been released by DoubleTapRecognizer. 
If you have other idea please let me know.

**Comment by HansMuller** [comment]
@NikoYuwono Although it would have been nice to have started with double tap support enabled by default, adding it now means that existing tests like the ones you've updated in the Flutter repo, will fail.  That's the sort of breaking backwards incompatible-change that should probably be avoided.

We could avoid the backwards incompatibility by making this feature "opt in" with a TextField flag. It's not ideal - it would be better to enable the feature by default - but much less disruptive.

**Comment by xster** [comment]
I'll pick this up again

**Pull request merged**
