### PR TITLE
Handle empty sizes in AppBar's toolbar layout

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by jason-simmons** [comment]
New version of https://github.com/flutter/flutter/pull/6535

**Comment by jason-simmons** [comment]
@Hixie

**Comment by Hixie** [comment]
We're going to have to do this for every widget (https://github.com/flutter/flutter/issues/6537), but for now, since this keeps coming up, LGTM.

**Comment by HansMuller** [comment]
I assume this fixes https://github.com/flutter/flutter/issues/6879

**Comment by HansMuller** [comment]
LGTM also.

**Pull request merged**
