### PR TITLE
Use Gradle KTS in new Android app projects by default (2nd try)

### LINKED ISSUE #151166: Change language of Gradle scripts in templates from Groovy to Kotlin
### Use case

Since 3.22, Flutter supports writing Gradle buildscripts in Kotlin, in addition to Groovy.

Using Kotlin instead of Groovy in Gradle buildscripts has many advantages and has been recommended by Gradle since April 2023 ([link](https://blog.gradle.org/kotlin-dsl-is-now-the-default-for-new-gradle-builds)).

I think it makes sense to make Kotlin the default language, to bring those advantages to every Flutter developer, many of whom are understandably not experts in Gradle, Groovy, and their quirks.

### Proposal

Scope:
1. Change the language of files in Gradle templates from Groovy to Kotlin
2. Revise existing documentation on [flutter/website](https://github.com/flutter/website) to make sure it works equally well for both Groovy and Kotlin templates.

As for bullet point (2), it's worth noting that in many cases, Kotlin syntax in Gradle is a subset of Groovy syntax, so we in many cases we can just show Kotlin syntax and it'll work the same in Groovy, e.g.:

**Example 1**

This works only in Groovy:

```groovy
dependencies {
    implementation "com.example:my-artifact:1.2.3"
}
```

but the following works both in Groovy and in Kotlin:

```groovy
dependencies {
    implementation("com.example:my-artifact:1.2.3")
}
```

**Example 2**

This works only in Groovy:

```groovy
android {
    namespace "pl.baftek.discoverrudy"
    compileSdk 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget "11"
    }

    defaultConfig {
        applicationId "pl.baftek.discoverrudy"
        minSdk 23
        targetSdk 34
        versionCode flutter.versionCode()
        versionName flutter.versionName()
    }
}
```

but this works in both:

```kotlin
android {
    namespace = "pl.baftek.discoverrudy"
    compileSdk = 34

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
    }

    defaultConfig {
        applicationId = "pl.baftek.discoverrudy"
        minSdk = 23
        targetSdk = 34
        versionCode = flutter.versionCode()
        versionName = flutter.versionName()
    }
}
```

---

**Alternatively**, we might decide to provide users with a switch when calling `flutter create`, e.g. `flutter create --android-build-language kotlin` and `flutter create --android-build-language groovy`.

### See also

https://github.com/flutter/flutter/issues/148586

### PR DESCRIPTION
**Pull request by bartekpacia**
This PR resolves #151166

This PR relands #154061

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by bartekpacia** [comment]
probably good idea to rebase with master after #157196 lands

i.e. this PR depends on #157196 being on master

**Review by reidbaker — APPROVED** [review]

**Comment by gmackall** [comment]
Updated branch to include https://github.com/flutter/flutter/pull/157196, LGTM if tests pass.

I checked post submits for the last merge, and it was just `android_java11_dependency_smoke_tests/android_java17_dependency_smoke_tests` and some tool integration tests failing. The tool integration tests are also getting run in presubmit and seem to be passing.

**Review by gmackall — APPROVED** [review]

**Comment by bartekpacia** [comment]
thanks @gmackall :)

I'll take a look at the failing tests in a minute.

**Review by reidbaker — COMMENTED** [review]
Failures appear related to this pr. 
```
To keep the default AGP version AGP version 8.1.0, download a compatible Java version
[2024-10-21 12:01:05.009001] [STDOUT] stderr: (Java 17 <= (Java 17 <= compatible Java version < Java 21) Java version < Java 21). Configure this Java version
```

@gmackall we dont have a java 21 version of these suite of tests yet, it looks like we will need to make one.

**Comment by gmackall** [comment]
Yes, the latest android studio version vends Java 21 I believe, so it would be good to use that in CI

**Comment by bartekpacia** [comment]
@gmackall Should I create a new PR that adds CI for java 21?

**Comment by gmackall** [comment]
Ah, I see - that is just the warning from `flutter create`. Ignore the previous comment, I think that can be safely ignored because we are planning on overwriting the Gradle files anyways.

So in summary, I think you just need to fix the failures in the following log section, namely the part starting
```
[2024-10-21 12:00:49.029432] [STDOUT] stderr: FAILURE: Build failed with an exception.
[2024-10-21 12:00:49.029461] [STDOUT] stderr: 
[2024-10-21 12:00:49.029507] [STDOUT] stderr: * Where:
[2024-10-21 12:00:49.029544] [STDOUT] stderr: Settings file '/b/s/w/ir/x/t/flutter_android_dependency_version_testsZOXTQI/7.0.2GANUFY/dependency_checker_app/android/settings.gradle.kts' line: 2
[2024-10-21 12:00:49.029585] [STDOUT] stderr: 
[2024-10-21 12:00:49.029623] [STDOUT] stderr: * What went wrong:
[2024-10-21 12:00:49.029652] [STDOUT] stderr: Script compilation errors:
[2024-10-21 12:00:49.029684] [STDOUT] stderr: 
[2024-10-21 12:00:49.029712] [STDOUT] stderr:   Line 02:     def flutterSdkPath = {
[2024-10-21 12:00:49.029742] [STDOUT] stderr:                                   ^ Expecting an element
[2024-10-21 12:00:49.029775] [STDOUT] stderr: 
[2024-10-21 12:00:49.029803] [STDOUT] stderr:   Line 03:         def properties = new Properties()
[2024-10-21 12:00:49.029833] [STDOUT] stderr:                                   ^ Expecting an element
[2024-10-21 12:00:49.029864] [STDOUT] stderr: 
[2024-10-21 12:00:49.029892] [STDOUT] stderr:   Line 05:         def flutterSdkPath = properties.getProperty("flutter.sdk")
[2024-10-21 12:00:49.029920] [STDOUT] stderr:                                       ^ Expecting an element
[2024-10-21 12:00:49.029953] [STDOUT] stderr: 
[2024-10-21 12:00:49.029982] [STDOUT] stderr:   Line 05:         def flutterSdkPath = properties.getProperty("flutter.sdk")
[2024-10-21 12:00:49.037188] [STDOUT] stderr:                                                   ^ Expecting an element
[2024-10-21 12:00:49.037724] [STDOUT] stderr: 
[2024-10-21 12:00:49.039026] [STDOUT] stderr:   Line 06:         assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
[2024-10-21 12:00:49.039920] [STDOUT] stderr:                                          ^ Expecting an element
[2024-10-21 12:00:49.040246] [STDOUT] stderr: 
[2024-10-21 12:00:49.041363] [STDOUT] stderr:   Line 06:         assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
[2024-10-21 12:00:49.041575] [STDOUT] stderr:                                            ^ Unexpected tokens (use ';' to separate expressions on the same line)
[2024-10-21 12:00:49.042884] [STDOUT] stderr: 
[2024-10-21 12:00:49.042944] [STDOUT] stderr:   Line 06:         assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
[2024-10-21 12:00:49.043209] [STDOUT] stderr:                                                 ^ Unexpected tokens (use ';' to separate expressions on the same line)
[2024-10-21 12:00:49.043424] [STDOUT] stderr: 
[2024-10-21 12:00:49.044644] [STDOUT] stderr:   Line 20:     id "dev.flutter.flutter-plugin-loader" version "1.0.0"
[2024-10-21 12:00:49.045201] [STDOUT] stderr:                   ^ Unexpected tokens (use ';' to separate expressions on the same line)
[2024-10-21 12:00:49.045265] [STDOUT] stderr: 
[2024-10-21 12:00:49.046550] [STDOUT] stderr:   Line 21:     id "com.android.application" version "7.0.1" apply false
[2024-10-21 12:00:49.047067] [STDOUT] stderr:                   ^ Unexpected tokens (use ';' to separate expressions on the same line)
[2024-10-21 12:00:49.047336] [STDOUT] stderr: 
[2024-10-21 12:00:49.047971] [STDOUT] stderr:   Line 22:     id "org.jetbrains.kotlin.android" version "1.7.10" apply false
[2024-10-21 12:00:49.049283] [STDOUT] stderr:                   ^ Unexpected tokens (use ';' to separate expressions on the same line)
```

FYI you should be able to run these tests locally with
```
../../bin/cache/dart-sdk/bin/dart bin/test_runner.dart test -t android_java11_dependency_smoke_tests
```
run from 
```
<flutter_root>/dev/devicelab
```

**Comment by bartekpacia** [comment]
we are so back

**Pull request merged**
