### PR TITLE
Wrong PT localization texts

### PR DESCRIPTION
**Pull request by leobispo**
* Back should be Voltar
* CORTA should be RECORTAR

### CODE REVIEW

**Comment by Hixie** [comment]
Thanks for your contribution! I believe @HansMuller is working on these translations so I'm going to defer to him rather than land these immediately, but hopefully this should land within a few days.

**Comment by HansMuller** [comment]
Thanks again for reviewing our translations. They were produced by a separate team within Google; I am going to forward your feedback to them.

**Comment by leobispo** [comment]
Tnx. Portuguese can be sometimes a tricky language.

**Comment by HansMuller** [comment]
These corrections have made it through the internal translation process and they landed as part of https://github.com/flutter/flutter/pull/13621.

Thanks for your patience!

**Pull request closed without merging**
