### PR TITLE
Handle KEYCODE_DPAD_CENTER and KEYCODE_ENTER

### PR DESCRIPTION
**Pull request by mossmana**
Addresses https://github.com/flutter/flutter/issues/1670

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by mossmana** [comment]
@gspencergoog I'm just now familiarizing myself with this area of the code, so before I continue along this path and add the associated tests, etc. Do you think this is a valid approach? Or would you recommend I start somewhere else?

**Comment by gspencergoog** [comment]
That should be a good start.  You might even be able to add it to the default shortcuts, since the select key would only be mapped on a system that produces it.  Then if, say, we started mapping that key on iOS, then it would just work.  We currently seem to map it already on Windows, so it would be nice if it worked there.

**Comment by goderbauer** [comment]
(triage): @mossmana said she would get back to this.

**Comment by mossmana** [comment]
In my first pass I made a change that would have only taken effect for Android. However, now the defaults for Fuchsia, Windows and Linux have been updated as well.

**Comment by mossmana** [comment]
I'm not sure what is going on, but every time I try to merge in the latest changes from master, there's a completely different unrelated to my changes test failure. I think I'm going to try opening up a fresh PR starting from the most recent base branch.

**Pull request closed without merging**
