### PR TITLE
Cupertino portuguese translations

### PR DESCRIPTION
**Pull request by lgfranco**
## Description

Cupertino translations to Portuguese

## Related Issues
####13452
- Need Cupertino Translations
- https://github.com/flutter/flutter/issues/13452

### CODE REVIEW

**Comment by lgfranco** [comment]
I signed it!

**Comment by lgfranco** [comment]
I signed it! Again...

**Comment by lgfranco** [comment]
googlebot check it again.

**Comment by lgfranco** [comment]
@xster, What should I do to correct this Pull Request?

**Comment by dnfield** [comment]
Make sure the commits you added were with the same email as what you registered with.  The first couple commits look like your author email were not the same as the email you CLA'd with.  Your best bet may be to close this PR and open a new one with the correct commit history.

**Comment by lgfranco** [comment]
Ok, i will do it again.

**Pull request closed without merging**
