### PR TITLE
Fix path-to-uri conversion that broke hot reload on Windows.

### LINKED ISSUE #14945: Android crash on hot-reload using dart 2 preview using Android Studio or VS Code
## Steps to Reproduce
1. `flutter create fl_test`
2. open project in Android Studio or VsCode with the Dart-Code extension
3. setup the IDE to run in --preview-dart-2 mode
4. open a android simulator
5. debug the project
6. press hot-reload (or make a change and save)
7. app crashes and all you get for an output is `Lost connection to device.`

This issue only happens with the flutter plugin, using the flutter command line works perfectly (pressing 'r' doesn't crash), so it seems to be something with however the plugins interact with the flutter run time that is different from the command line

## Logs
```
Analyzing C:\git\flut_test...
No issues found!
Ran in 6.1s
```
## Flutter Doctor
```
[√] Flutter (Channel dev, v0.1.7, on Microsoft Windows [Version 10.0.17025.1000], locale en-US)
    • Flutter version 0.1.7 at C:\git\flutter
    • Framework revision 3b84503403 (24 hours ago), 2018-02-26 20:11:11 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 27.0.1)
    • Android SDK at C:\Users\Rory\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code (version 1.20.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.9.0

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by aam**
This fixes #14945

### CODE REVIEW

**Comment by aam** [comment]
Kudos to #grindvoll for root cause analysis and the fix!

**Review by a-siva — APPROVED** [review]
lgtm.

Can you add a link to https://github.com/flutter/flutter/issues/14945#issuecomment-369353321
in the comment section

**Review by jacob314 — APPROVED** [review]

**Comment by aam** [comment]
@a-siva wrote:
> Can you add a link to #14945 (comment) in the comment section

What comment section are you talking about? Adding link to the bug on line 508 doesn't sound right.

**Comment by a-siva** [comment]
I meant the comment section of this pull request, now it is there so ignore it

**Comment by zarub2k** [comment]
Is the fix available in beta? I am struggling and tired of restarting everytime...

**Comment by zarub2k** [comment]
Can someone move this fix to beta? The core selling of Flutter is broken now in my beta build and I am not able to work without any restarting the app. Urgent...

**Comment by Hixie** [comment]
The next beta will be cut in a few weeks. Feel free to switch to the dev channel in the meantime.

**Pull request merged**
