### PR TITLE
Be more consistent about how we mark classes that can't be extended.

### LINKED ISSUE #26095: We should be more consistent about Foo._(); vs factory Foo._() => null;
In the engine and framework we are inconsistent about how we handle classes that are all static methods.

Sometimes they're abstract, sometimes they're not; sometimes they have `X._()` constructors, sometimes they have `factory X._() => null` constructors.

I think we should standardize on non-abstract with `factory X._() => null` constructors, with the same comment as we currently have for `PluginUtilities`.

### PR DESCRIPTION
**Pull request by Hixie**
Fixes #26095

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Are these ones different?
- TickerFuture
- PlatformViewsService
- RawKeyboard
- TextInput
- DoNothingIntent - this one looks like a special case

**Review by a14n — APPROVED** [review]
nit: update comment of modified constructors to have the same comment everywhere.

**Comment by Hixie** [comment]
@Piinks Yeah, those are meant to be instantiated but only by code in their own file. I could have a separate comment for those if you like.

@a14n There's three different cases: interfaces, classes that just contain statics, and classes instantiated locally. They have different comments. Did you find another kind of comment?

**Comment by a14n** [comment]
> There's three different cases: interfaces, classes that just contain statics, and classes instantiated locally. They have different comments. Did you find another kind of comment?

Not really. I didn't really pay attention that they were 3 different cases. So it looks good.

**Pull request merged**
