### PR TITLE
Update text_form_field.dart

### PR DESCRIPTION
**Pull request by robertoscaramuzzi**
Add autovalidate parameter to TextFormField constructor so standalone TextFormFields can autovalidate too.

### CODE REVIEW

**Comment by Hixie** [comment]
test?

**Comment by robertoscaramuzzi** [comment]
PTAL

**Comment by ezrasandzerbell** [comment]
The current textFormFieldDemo breaks my build with these errors: parameter Builder and MaxLength aren't defined.

**Comment by robertoscaramuzzi** [comment]
That's unrelated to this PR. Can you please open an issue for it on the flutter main branch?

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
Thanks!

**Pull request merged**
