### PR TITLE
Fixed a lot of typos

### PR DESCRIPTION
**Pull request by anisalibegic**
Fair amount of typos spotted and fixed. Some of them are in comments, some of them are in code and some of them are in nondart files.

There is no need for issues since it's a typo fix.

I have doubts about [packages/flutter_tools/lib/src/ios/core_devices.dart](https://github.com/flutter/flutter/compare/master...anisalibegic:flutter:master#diff-fdbc1496b4bbe7e2b445a567fd385677af861c0093774e3d8cc460fdd5b794fa), I have a feeling it might broke some things on the other end, even though it's a typo.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by bartekpacia** [comment]
How'd you find all these?

**Review by bartekpacia — APPROVED** [review]

**Comment by anisalibegic** [comment]
> How'd you find all these?

I really would love to say that I use something sophisticated but it's just a Typo Analyzer in IntelliJ IDEA and 2 hours of going through each file and checking if it's really a typo or not... :)

**Comment by bartekpacia** [comment]
Haha, nice!
Thanks you for your contribution

**Comment by anisalibegic** [comment]
@bartekpacia What can we do about this _auto-submit_ comment?

**Comment by bartekpacia** [comment]
We need to wait for someone else from the team to approve this PR. I don't often review PRs so I forgot about this rule.

**Review by goderbauer — APPROVED** [review]
Wow. Thank you!

LGTM

**Pull request merged**
