### PR TITLE
Reland: Always use new plugin schema for plugin template

### PR DESCRIPTION
**Pull request by stuartmorgan-g**
## Description

Now that the new schema is supported on the stable channel, and the old
schema is considered legacy, the template should always create plugins
using the new schema.

## Related Issues

None

## Tests

I added the following tests: None. Existing tests cover both formats.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Checking to see if the failure shows up in presubmits this time; it may be that the previous presubmit runs were just too old.

**Comment by stuartmorgan** [comment]
@amirh Ping? This is identical to the previously landed version, but with the test fix.

**Review by amirh — APPROVED** [review]
Thanks!

We need to also introduce a constraint to enforce minimal Flutter SDK version that supports the new schema.

Also needs some test.

**Comment by stuartmorgan** [comment]
> We need to also introduce a constraint to enforce minimal Flutter SDK version that supports the new schema.

Should I use `flutter: ">=1.10.0 <2.0.0"` like the mass-migration PR in flutter/plugins?

> Also needs some test.

There are already a bunch of tests of the new schema. Do you mean you want a test asserting that the template-created pubspec.yaml has the specific format of the new schema?

**Comment by amirh** [comment]
> Should I use `flutter: ">=1.10.0 <2.0.0"` like the mass-migration PR in flutter/plugins?

yes.

> There are already a bunch of tests of the new schema. Do you mean you want a test asserting that the template-created pubspec.yaml has the specific format of the new schema?

Yes. The policy in https://github.com/flutter/flutter/wiki/Tree-hygiene#overview (`#5`) requires a test or a test update for a change like this one.

I'm actually feeling like we should just have a generated plugin checked in, and just compare all output files to a newly created plugin as part of a test, this should prevent unintended changes from going unnoticed, and would ease reviewing template / tool changes as you'd see what the end result looks like. (I just sent out a test in https://github.com/flutter/flutter/pull/50485 which is probably better replaced by something like what's described above). WDYT?

Anyway I'm happy to go with whatever is the fastest path to land this P, be it any kind of new test, or a test exemption saying that we're planning to land something like the test mentioned above.

**Comment by amirh** [comment]
> > Should I use `flutter: ">=1.10.0 <2.0.0"` like the mass-migration PR in flutter/plugins?
> 
> yes.

 Correction `flutter: ">=1.10.0"` per feedback from Ian

**Comment by stuartmorgan** [comment]
> I'm actually feeling like we should just have a generated plugin checked in, and just compare all output files to a newly created plugin as part of a test, this should prevent unintended changes from going unnoticed, and would ease reviewing template / tool changes as you'd see what the end result looks like. (I just sent out a test in #50485 which is probably better replaced by something like what's described above). WDYT?

I'm not sure it would actually prevent unintended changes as well as targeted tests, because standard practice would become to simply update the golden output on any template change, and it's easier to miss that you've broken something that was intentional. An "is this the new platform schema", for instance, is a clear signal that if you weren't trying to change that, your change is probably wrong, while "golden output changed" would be normal for every change.

> Anyway I'm happy to go with whatever is the fastest path to land this P, be it any kind of new test, or a test exemption saying that we're planning to land something like the test mentioned above.

There's no rush that prevents adding a test now, I just didn't know that we wanted a test enforcing that the template had the new schema. I'll update shortly.

**Comment by amirh** [comment]
> I'm not sure it would actually prevent unintended changes as well as targeted tests, because standard practice would become to simply update the golden output on any template change, and it's easier to miss that you've broken something that was intentional. An "is this the new platform schema" test failure, for instance, is a clear signal that if you weren't trying to change that, your change is probably wrong, while "golden output changed" would be normal for every change.

https://github.com/flutter/flutter/pull/11304 for example snuck in a regression (moved the the plugin dependency to become a dev_depenency), I would imagine seeing that change in the checked in generated plugin would have increase the chances of that regression getting caught in review

**Comment by stuartmorgan** [comment]
> Correction `flutter: ">=1.10.0"` per feedback from Ian

Capturing from offline discussion: I'll do a canary PR that removes the upper constraint from a flutter/plugins plugin, so we can try publishing to see if there are any issues with plugins that have no upper constraint before changing the template, since the current plugins have an upper bound (and there are cases, like the Dart constraint, where no upper bound is flagged).

**Comment by jmagman** [comment]
@stuartmorgan Is this ready to merge?

**Comment by stuartmorgan** [comment]
No, it still needs a test, and the update to remove the upper constraints on the Flutter SDK. I'll update it this week.

**Pull request merged**
