### PR TITLE
Upgrade node on travis

### PR DESCRIPTION
**Pull request by DanTup**
This upgrades Node (and with it, NPM) to the latest LTS version. Hopefully it may resolve some of the hangs we see when installing firebase-tools in the Travis script (used for deploying docs). I've already put a `retry` script around that, but it only helps in the cases where we get errors (eg. npm network wobbles) and not the case where it just hangs and Travis eventually kills it.

As far as I can tell, nodejs/npm are only used in two places:

1. A line in travis/install that installs firebase-tools
2. A call to `firebase deploy` in the docs script which only runs for certain branches and not in PRs

To test `1`, I removed the condition around it and let it run on my own Travis branch. Unsurprisingly it didn't fail, but all it does it installs the package!

Testing `2` isn't really possible without me deploying docs (and couldn't be done from a PR branch since it won't have access to the secret env variables); however I think the risk is low since if it's broken it's likely a `firebase-tools` bug and lots of people are probably using this version of nodejs in the wild.

(cc @mit-mit - you last upgraded the NodeJS version, so you may have a better opinion on the risk of this)

### CODE REVIEW

**Comment by mit-mit** [comment]
We should probably consider also upgrading flutter/website?

**Comment by DanTup** [comment]
Looks like you already did! :) https://github.com/flutter/website/pull/752

**Comment by DanTup** [comment]
Looking at the top comment in that PR, seems like this might also fix a bunch of errors we have spewed out in the logs in `master` too (same things as in that PR) :-)

**Comment by DanTup** [comment]
Sure - or would it be better to move website up to 8.11 (that's the current newest LTS version, as provided on [the homepage](https://nodejs.org/en/))? It probably does make sense to have them pegged to a minor version though, to reduce how often they update (to keep builds more consistent, in case we still have issues).

**Comment by mit-mit** [comment]
I don't know js wellenough to make that call. I just think it makes sense to pin them both to the same version.

**Comment by DanTup** [comment]
Ok, I'll make this 8.1 for now. I'm not sure about website, but here it seems like it's only used to run the `firebase deploy` command line tool so the version likely doesn't make any difference outside of bugs in npm, but I don't know if that's the same for website.

**Comment by DanTup** [comment]
@mit-mit Happy for me to land this as 8.1? or is there someone else who may have a stronger opinion on it?

**Review by devoncarew — APPROVED** [review]
rslgtm to me

**Pull request merged**
