### PR TITLE
Overlay contains entry

### PR DESCRIPTION
**Pull request by Timoteohss**
## Description

Added a method to verify the existence of given OverlayEntry on the Overlay.

## Related Issues

#47532

## Tests

Added `Can verify if OverlayEntry is already on the Overlay` on `overlay_test`

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Comment by Timoteohss** [comment]
@googlebot I signed it!

**Comment by Timoteohss** [comment]
@googlebot I fixed it.

**Comment by Timoteohss** [comment]
@googlebot I fixed it.

**Comment by chunhtai** [comment]
@Timoteohss I don't think this is something we should expose. We purposely make it so widget should aware what overlay entry it has inserted into the overlay. There should not be a case where a widget need to know whether an overlay entry has been inserted.

**Comment by chunhtai** [comment]
I will close this pr for now and we can continue our discussion in the issue.

**Pull request closed without merging**
