### PR TITLE
Remove clip for background of Dismissible. fix for issue 56812

### PR DESCRIPTION
**Pull request by qwertylolman**
Before
Screenshot 2024-07-27 at 00 56 27

After
Screenshot 2024-07-27 at 00 54 25

This PR fixes the issue 'Background Clipping in Dismissible #56812'

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [+] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by qwertylolman** [comment]
I don't understand why there was a ClipRect, but it's definitely breaks the appearance of the Dissmissible background

**Comment by goderbauer** [comment]
You can discuss this on our discord channel, see https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md.

Also, can you please add tests to this PR as instructed by the bot message above? Thank you.

**Comment by chriscarman-mp** [comment]
Thanks for this, think I will create my own custom widget until this is merged

**Comment by goderbauer** [comment]
(triage) @qwertylolman Do you still have plans to get back to this PR?

**Comment by qwertylolman** [comment]
> (triage) @qwertylolman Do you still have plans to get back to this PR?

I am closing this PR. New PR with better solution will be created when I will have more time :/

**Pull request closed without merging**
