### PR TITLE
Update devicelab test for rename of materialize -> make-host-app-editable

### PR DESCRIPTION
**Pull request by DanTup**
This fixes the devicelab failure after #22006 renamed this command.

(fyi @matthew-carroll)

### CODE REVIEW

**Review by tvolkert — APPROVED** [review]

**Comment by DanTup** [comment]
I'll land once Cirrus finishes, though with a red Flutter build since this is the fix for the redness.

**Comment by matthew-carroll** [comment]
@DanTup thanks for taking care of this.  Do we not run device lab tests in presubmit?

**Comment by jonahwilliams** [comment]
We don't run devicelab tests on presubmit (I've been bitten by this too). We don't have the resources in the devicelab to handle this for the large number of PR commits we get. You can run them locally, but that requires the correct host setup

**Comment by DanTup** [comment]
Yeah :( Though we do have the ability to write integration tests using `flutter-tester` that can run on Cirrus, so it's possible that some of the devicelab tests could be ported/copied there if they don't specifically require running on real devices (this one seems like it may be a good fir for that).

**Pull request merged**
