### PR TITLE
Add modifier functions to RawKeyEventAndroid.

### PR DESCRIPTION
**Pull request by JediBurrell**
This adds `isCtrlPressed`, `isAltPressed`, and `isShiftPressed` to `RawKeyEventAndroid`. This closes issue #26155.

### CODE REVIEW

**Comment by goderbauer** [comment]
@JediBurrell Thank for the contribution. In order for us to accept this PR into the repository you'll have to add a test case to ensure that this feature continues to work as expected. Can you add one? Thanks.

@gspencergoog Can you review since you're working on keyboard stuff?

**Comment by JediBurrell** [comment]
I added tests, but I'm not able to replicate the failed checks. Looking at the logs doesn't really indicate a point of fatal failure.

**Comment by gspencergoog** [comment]
Looks like you need to rebase onto master again: you've got some code from another commit in yours.

**Comment by JediBurrell** [comment]
Christ, I just made it worse.

I'm going to close this PR and open it with a new branch.

**Pull request closed without merging**
