### PR TITLE
Add await to make timing match sync async modes

### LINKED ISSUE #20318: sync async issues in RefreshIndicator
https://github.com/flutter/flutter/blob/b32c77a01246e84b74ba42ea13554331aa0d8c0a/packages/flutter/lib/src/material/refresh_indicator.dart#L300-L307

With sync async disabled, the body of `_dismiss()` ran in the next microtask loop.  But with sync async enabled, it runs synchronously.  This can cause the following assertion error to be thrown:

```
I/flutter ( 9919): ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
I/flutter ( 9919): The following assertion was thrown:
I/flutter ( 9919): Build scheduled during frame.
I/flutter ( 9919): While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild
I/flutter ( 9919): the widget tree. This might be because setState() was called from a layout or paint callback. If a
I/flutter ( 9919): change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a
I/flutter ( 9919): change for the subsequent frame instead results in an interface that lags behind by one frame. If
I/flutter ( 9919): this was done to make your build dependent on a size measured at layout time, consider using a
I/flutter ( 9919): LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one
I/flutter ( 9919): frame delay is the desired effect, for example because this is an animation, consider scheduling the
I/flutter ( 9919): frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an
I/flutter ( 9919): AnimationController to trigger the animation.
I/flutter ( 9919): 
I/flutter ( 9919): When the exception was thrown, this was the stack:
I/flutter ( 9919): #0      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:521:9)
I/flutter ( 9919): #1      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding._handleBuildScheduled (package:flutter/src/widgets/binding.dart:540:6)
I/flutter ( 9919): #2      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2139:7)
I/flutter ( 9919): #3      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3479:11)
I/flutter ( 9919): #4      State.setState (package:flutter/src/widgets/framework.dart:1141:14)
I/flutter ( 9919): #5      RefreshIndicatorState._dismiss (package:flutter/src/material/refresh_indicator.dart:305:5)
I/flutter ( 9919): <asynchronous suspension>
I/flutter ( 9919): #6      RefreshIndicatorState._handleScrollNotification (package:flutter/src/material/refresh_indicator.dart:246:11)
I/flutter ( 9919): #7      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:125:27)
I/flutter ( 9919): #8      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:45:20)
I/flutter ( 9919): #9      _ScrollNotification&LayoutChangedNotification&ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:35:18)
I/flutter ( 9919): #10     Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3308:39)
I/flutter ( 9919): #11     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:59:12)
I/flutter ( 9919): #12     ScrollActivity.dispatchScrollEndNotification (package:flutter/src/widgets/scroll_activity.dart:106:67)
I/flutter ( 9919): #13     ScrollPosition.didEndScroll (package:flutter/src/widgets/scroll_position.dart:636:14)
I/flutter ( 9919): #14     ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:605:9)
I/flutter ( 9919): #15     _NestedInnerBallisticScrollActivity.applyNewDimensions (package:flutter/src/widgets/nested_scroll_view.dart:1149:14)
I/flutter ( 9919): #16     ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:485:14)
I/flutter ( 9919): #17     _NestedScrollPosition.applyNewDimensions (package:flutter/src/widgets/nested_scroll_view.dart:1102:11)
I/flutter ( 9919): #18     ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:456:7)
I/flutter ( 9919): #19     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1233:20)
I/flutter ( 9919): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9919): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 9919): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9919): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 9919): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9919): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 9919): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9919): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 9919): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9919): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 9919): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9919): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 9919): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9919): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 9919): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9919): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter ( 9919): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9919): #37     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter ( 9919): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9919): #39     RenderSliverFillRemaining.performLayout (package:flutter/src/rendering/sliver_fill.dart:121:13)
I/flutter ( 9919): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter ( 9919): #41     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter ( 9919): #42     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1311:12)
I/flutter ( 9919): #43     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1229:20)
I/flutter ( 9919): #44     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter ( 9919): #45     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:704:18)
I/flutter ( 9919): #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter ( 9919): #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter ( 9919): #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter ( 9919): #49     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 9919): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 9919): #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 9919): #52     CoreActivityZoneImpl._run.<anonymous closure> (package:ads.acx2.tracking.activity.core.zone/zone.dart:200:18)
I/flutter ( 9919): #55     CoreActivityZoneImpl._run (package:ads.acx2.tracking.activity.core.zone/zone.dart:197:19)
I/flutter ( 9919): #58     _invoke (dart:ui/hooks.dart:127:10)
I/flutter ( 9919): #59     _drawFrame (dart:ui/hooks.dart:114:3)
I/flutter ( 9919): (elided 4 frames from package dart:async)
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/20318

### CODE REVIEW

**Review by tvolkert — APPROVED** [review]
LGTM

**Comment by tvolkert** [comment]
Is there any test we could add that would deterministically fail before this fix was made?

**Comment by tvolkert** [comment]
Thanks.  I'm trying to keep some well-meaning future developer from removing that "superfluous" line and not having any test feedback as to its purpose.

**Comment by jonahwilliams** [comment]
// DO NOT REMOVE - load bearing `await`.

**Pull request merged**
