### PR TITLE
Create CustomRoundedRectangleBorder

### PR DESCRIPTION
**Pull request by bramvbilsen**
This class is similar to the RoundedRectangleBorder, but differs in the sense that the appearance of each border and corner are specified on its own. This allows the user to have non-uniform borders with different colors and different widths while keeping the possibility to not show a side or corner border.
The following image shows the capabilities of this class
screenshot_1525893115

### CODE REVIEW

**Comment by bramvbilsen** [comment]
AppVeyor is timing out:
```
Build execution time has reached the maximum allowed time for your plan (60 minutes).
```
Not sure how to fix this.

**Comment by bramvbilsen** [comment]
The bug introduced in the previous commit is fixed!

**Comment by Hixie** [comment]
@bramvbilsen I like the look here! I think this would be a great standalone package. If we want to include it in the Flutter framework itself, we probably want to make sure we can lerp between these borders and the regular `Border` class, `CircleBorder`, and various such things. What do you think, would it make more sense as a standalone package or do you want to do the more detailed work that'll be needed for including this in the framework?

**Comment by bramvbilsen** [comment]
@Hixie Sounds good, I'll wrap it in a package! I just noticed that the lerping doesn't work correctly all the time so I'm gonna have to fix that first.

**Comment by Hixie** [comment]
@bramvbilsen If we're moving to putting this in a package, I'm going to close this PR. Please let me know if you want me to review any code you end up publishing, I'd be happy to do so.

**Comment by bramvbilsen** [comment]
@Hixie I'm definitely going to take you up on that offer when I find the time to finish the package!

**Comment by irundaia** [comment]
Did this end up in a package somewhere? I couldn't find it on pub.dartlang.org

**Comment by bramvbilsen** [comment]
@irundaia It still isn't not, I still want to make it into a plugin but just haven't found the time in these last few months.

**Comment by Riz-waan** [comment]
@bramvbilsen What about now, is the package out?

**Comment by AntiqPeace** [comment]
@bramvbilsen Any update on this? I want this thing...

**Comment by AntiqPeace** [comment]
Can anybody tell me how to use the given class? I tried to provide it inside container decoration. But, that accepts `BoxBorder` and this is a `ShapeBorder`...

**Comment by lekanbar** [comment]
Thanks for this @bramvbilsen! I just published it as a package here for anyone interested [like me :)]: https://pub.dev/packages/custom_rounded_rectangle_border

**Pull request closed without merging**
