### PR TITLE
[flutter_tools] Handle special characters during conversion of asset manifest paths into URIs

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Adding @dnfield since he landed the previous fix

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Is there a bug this is fixing for context?

**Comment by jason-simmons** [comment]
While looking into https://github.com/flutter/flutter/issues/46163 I found that some characters that are meaningful in URIs were not being handled correctly in asset manifests (e.g. `#` and `?`)

#46163 described a slightly different bug though.

**Comment by AlexVincent525** [comment]
Would you like to add some chinese character in the test? Just to make sure everything is gonna be okay. :smily:

**Pull request merged**
