### PR TITLE
Add new class, to adapt text styles based on Material states

### LINKED ISSUE #143488: Customize floatingLabelStyle for error in InputDecorationTheme
### Use case

I want to customize my TextField entirely through themeData so I don't have to create a specific widget as a wrapper for it.

Right now my form field looks like this: 
image
image
image
image

InputDecorationTheme doesn't expose any parameters to customize textStyle of floatingLabel when validating textField with an error. I can't change the color of the floatingLabel when focused on the textField, and unfocusing it makes the label take the default dark theme error color.

image

### Proposal

Give inputDecorationTheme optional parameters focusedErrorFloatingLabelStyle and errorFloatingLabelStyle.

### PR DESCRIPTION
**Pull request by nate-thegrate**
Flutter currently gives several convenient options for customizing the input decoration border:

```dart
final inputDecorationTheme = InputDecorationTheme(
  errorBorder: border1,
  focusedBorder: border2,
  focusedErrorBorder: border3,
  disabledBorder: border4,
  enabledBorder: border5,
);
```

Conversely, the `labelStyle` documentation recommends writing your own `MaterialStatePropertyResolver` to accomplish the same thing:

```dart
  /// If [labelStyle] is a [MaterialStateTextStyle], then the effective
  /// text style can depend on the [MaterialState.focused] state, i.e.
  /// if the [TextField] is focused or not.
  ///
  /// It's possible to override the label style for just the error state, or
  /// just the default state, or both.
  ///
  /// ** See code in examples/api/lib/material/input_decorator/input_decoration.floating_label_style_error.0.dart **
```

<br><br>

This pull request fixes #143488. Originally, I thought about just adding two parameters as requested, but I wanted to cover more use cases:

```dart
const inputDecorationTheme = InputDecorationTheme(
  labelStyle: TextStyle(color: Colors.orange),
  focusedLabelStyle: TextStyle(color: Colors.orangeAccent),
  disabledLabelStyle: TextStyle(color: Colors.grey),
  errorLabelStyle: TextStyle(color: Colors.red),
  errorFocusedLabelStyle: TextStyle(color: Colors.redAccent),
  errorDisabledLabelStyle: TextStyle(color: Color(0xFF804040)),
  floatingLabelStyle: TextStyle(color: Colors.orange),
  focusedFloatingLabelStyle: TextStyle(color: Colors.orangeAccent),
  disabledFloatingLabelStyle: TextStyle(color: Colors.grey),
  errorFloatingLabelStyle: TextStyle(color: Colors.red),
  errorFocusedFloatingLabelStyle: TextStyle(color: Colors.redAccent),
  errorDisabledFloatingLabelStyle: TextStyle(color: Color(0xFF804040)),
);
```

Having all these extra parameters would give easier control over input label appearance, but honestly this is awful to look at.

Instead, this pull request adds the `InputDecorationStyle` class. It extends the `MaterialStateTextStyle` class (allowing it to be used in place of a `TextStyle`) and has a built-in `MaterialPropertyResolver`.

It's a bit more visually appealing:

```dart
const inputDecorationTheme = InputDecorationTheme(
  labelStyle: InputDecorationStyle(
    normal: TextStyle(color: Colors.orange),
    focused: TextStyle(color: Colors.orangeAccent),
    disabled: TextStyle(color: Colors.grey),
    error: TextStyle(color: Colors.red),
    focusedError: TextStyle(color: Colors.redAccent),
    disabledError: TextStyle(color: Color(0xFF804040)),
  ),
  floatingLabelStyle: InputDecorationStyle(
    normal: TextStyle(color: Colors.orange),
    focused: TextStyle(color: Colors.orangeAccent),
    disabled: TextStyle(color: Colors.grey),
    error: TextStyle(color: Colors.red),
    focusedError: TextStyle(color: Colors.redAccent),
    disabledError: TextStyle(color: Color(0xFF804040)),
  ),
);
```

<br>

#### before:
```dart
TextField(
  style: MaterialStateTextStyle.resolveWith((Set<MaterialState> states) {
    if (states.contains(MaterialState.disabled)) {
      return const TextStyle(color: Colors.red);
    }
    return const TextStyle(color: Colors.blue);
  }),
)
```

#### after:
```dart
TextField(
  style: const InputDecorationStyle(
    normal: TextStyle(color: Colors.blue),
    disabled: TextStyle(color: Colors.red),
  ),
)
```

<br>

`Container()` has class members to represent alignment/padding/color, and its `build()` method combines them in a logical and intuitive way.

The goal of `InputDecorationStyle()` and its `resolve()` method is to do the same for text styles.

InputDecorationStyle

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by QuncCccccc — COMMENTED** [review]
Thanks a lot for your contribution! Seems like this class is doing the same thing as providing a MaterialStateResolver? I probably would prefer the original way for maintenance and consistency with other MaterialStateXproperty :)

Maybe @HansMuller would have more advice about this:)

**Comment by nate-thegrate** [comment]
@QuncCccccc you're absolutely right, this class doesn't add anything that you can't already do by providing a `MaterialPropertyResolver`.

I noticed that when setting the `InputDecorationTheme`, you can configure the border's appearance for multiple different Material states without needing to write out a function. I thought it'd be nice to have the same options available for the label/floating label text styles, and I figured that a class like this one would be the most straightforward way to do it.

I agree that getting multiple opinions would be very beneficial!

**Comment by nate-thegrate** [comment]
Maybe instead of a public class, it could be implemented the same way as `MaterialStateTextStyle.resolveWith`:

```dart
MaterialStateTextStyle.fromStyles(
  normal: style1,
  focused: style2,
  disabled: style3,
  error: style4,
  focusedError: style5,
)
```

The downside is that `fromStyles` would need to be a factory or static method, so unlike a class constructor, it can't be `const`.

**Comment by nate-thegrate** [comment]
I'm going to try this again, using a `MaterialStateTextStyle` factory instead of a new public class.

**Pull request closed without merging**
