### PR TITLE
Do not handle external requests by service worker (Flutter web)

### LINKED ISSUE #155451: Inconsistent behavior of external requests on Flutter for web due to issue in service worker
### Steps to reproduce

I have created a GitHub repo to showcase the issue: https://github.com/Frank3K/flutter_service_worker_bug

## Prerequisites

Ensure you have a tool installed that can run an HTTP server to serve the contents of a directory. Here, Python 3 is used as an example. Other examples can be found at https://gist.github.com/willurd/5720255.

## Reproduction steps

1. Clone the repository on https://github.com/Frank3K/flutter_service_worker_bug.
2. Install dependencies: `flutter pub get`.
3. Compile for web: `flutter build web`
    - Note that `flutter run -d chrome` is not sufficient, since service workers are empty in `run` mode.
4. Serve the output, e.g., using `python3 -m http.server 8080 -d build/web`.
5. Open the following URLs in Chrome:
    - http://this-is-a-very-long-url-thats-sooooooooooooooooooooooooooo-long.localhost:8080/
    - http://short.localhost:8080/
6. Open the network tools.
7. In each tab, press the download (FAB) button.
8. Observe that for the long URL, the request is processed by the service worker (a ⚙ is present), and for the short URL, it is not.

## Expected results

The expected result is that the service worker does not handle external requests.

## Cause of this discrepancy

Looking into the service worker code, we find the following code: [link](https://github.com/flutter/flutter/blob/2528fa95eb3f8e107b7e28651a61305d960eef85/packages/flutter_tools/lib/src/web/file_generators/js/flutter_service_worker.js#L87-L95):

```js
  var origin = self.location.origin;
  var key = event.request.url.substring(origin.length + 1);
  // Redirect URLs to the index.html
  if (key.indexOf('?v=') != -1) {
    key = key.split('?v=')[0];
  }
  if (event.request.url == origin || event.request.url.startsWith(origin + '/#') || key == '') {
    key = '/';
  }
```

Depending on the length of the URLs, the `substring` returns the empty string, which later on becomes `/`.

### Suggested fix

Bail out when the request is to an external URL. For example, using:

```js
  var requestURL = new URL(event.request.url);
  if (requestURL.origin !== origin) {
    return;
  }
```

### Actual results

Some external requests are processed by the service worker in Flutter for web and other requests are not, depending on the length of the application URL in combination with the request URL.

For example, given an application URL: https://www.some-website-example.com that makes the following requests:

- A GET request to https://www.some-api.com/status
- A GET request to https://www.another-api.com/items/12345

The first request will be processed (and cached) by the service worker, while the second one will not.

### Code sample

The source for an application showcasing the issue can be found over at:

https://github.com/Frank3K/flutter_service_worker_bug

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Long URL: service worker handling the request:

image

Short URL: service worker not handling the request:

image

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.6.1 23G93 darwin-x64, locale en-NL)
    • Flutter version 3.24.3 on channel stable at /Users/<redacted>/.asdf/installs/flutter/3.24.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (9 days ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/<redacted>/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/<redacted>/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    ! iOS 18.0 Simulator not installed; this may be necessary for iOS and macOS development.
      To download and install the platform, open Xcode, select Xcode > Settings > Platforms,
      and click the GET button for the required platform.

      For more information, please visit:
        https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes
    ! CocoaPods 1.12.1 out of date (1.13.0 is recommended).
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      To update CocoaPods, see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.6.1 23G93 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 128.0.6613.138

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by Frank3K**
Fixes #155451.

## Problem description

Some external requests are processed by the service worker in Flutter for web and other requests are not, depending on the length of the application URL in combination with the request URL.

For example, given an application URL: https://www.some-website-example.com that makes the following requests:

- A GET request to https://www.some-api.com/status
- A GET request to https://www.another-api.com/items/12345

The first request will be processed (and cached) by the service worker, while the second one will not.

## Expected behavior and fix

The expected behavior of the service worker is that it should only handle application resources and must never interfere with external requests. This PR makes sure that external requests are not handled by the service worker.

## Testing

I would need help writing tests for this change. I have found this test: [service_worker_test.dart](https://github.com/flutter/flutter/blob/2528fa95eb3f8e107b7e28651a61305d960eef85/dev/bots/service_worker_test.dart), but I'm unsure how to test the fix there.

## TODO

- [ ] Tests

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by yjbanov** [comment]
It feels strange that the length of the URL would affect this. Could this be a CORS issue or something?

**Comment by Frank3K** [comment]
> Could this be a CORS issue or something?

No. In https://github.com/flutter/flutter/issues/155451 the issue is demonstrated with the same external request URL.

> It feels strange that the length of the URL would affect this. 

The issue originates from substring logic which does not take different origins into account: 

https://github.com/flutter/flutter/blob/2528fa95eb3f8e107b7e28651a61305d960eef85/packages/flutter_tools/lib/src/web/file_generators/js/flutter_service_worker.js#L87-L95

**Comment by yjbanov** [comment]
I see. I guess we can take this fix. @ditman WDYT?

That said, we are planning to remove the service worker from the Flutter SDK and instead let the community fill this gap. More details here: https://docs.google.com/document/d/1czOm3Hmy_oIq3NJStezb9AjwkKyta3NospkCy_DDv9E/edit?usp=sharing

**Comment by bkonyi** [comment]
@ditman friendly ping. Can you take a look or close this when you have a chance?

**Comment by ditman** [comment]
I think we should close this, we're planning on removing the default Service Worker in this quarter, here's some documentation:

* https://groups.google.com/g/flutter-announce/c/0Vv-j_TyrdI
* https://flutter.dev/go/web-cleanup-service-worker

WDYT @bkonyi @yjbanov?

**Comment by bkonyi** [comment]
I'm fine with closing this if we're planning on removing the default service worker sooner than later.

**Pull request closed without merging**
