### PR TITLE
Make DropdownMenuItem's value param required

### LINKED ISSUE #56725: [proposal] Make "value" required for "DropdownMenuItem"
`DropdownButtonFormField` is not showing the value provided into `value` param.

Facing this on the latest Flutter version (`1.17.0`)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Run the code bellow 
3. Try to select a item in the dropdown field...

**Expected results:** The selected value should be visible to the user

**Actual results:** The first value is displayed instead

## Code

```
class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _i;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Página Inicial')),
      body: Column(
        children: <Widget>[
          DropdownButtonFormField<String>(
            value: _i,
            onChanged: (i) {
              setState(() {
                _i = i;
              });
            },
            items: List.generate(
              10,
              (index) => DropdownMenuItem(
                child: Text('$index'),
              ),
            ),
          )
        ],
      ),
    );
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by pedromassango**
## Description

I proposed that `value` param of `DropdownMenuItem` should be required since it is easy to forget without being required and once it is a required value to this widget to function properly.

This fixes: https://github.com/flutter/flutter/issues/56725#issuecomment-626149509

## Related Issues

https://github.com/flutter/flutter/issues/56725#issuecomment-626149509

## Tests

I added the following tests:

I added a test that assert that `value` param is provided or throws AssertionError otherwise

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Comment by pedromassango** [comment]
@shihaohong can you please add yourself as reviewer on this?

**Comment by shihaohong** [comment]
Could you add a test to make sure that the required parameter needs to be specified? We generally don't take PRs without tests. Thanks!

**Comment by pedromassango** [comment]
> Could you add a test to make sure that the required parameter needs to be specified? We generally don't take PRs without tests. Thanks!

Can you help me to find a way to test this use case?

**Comment by shihaohong** [comment]
We need to somehow test that `DropdownMenuItem` requires a value now. If that's not possible, then explain what the blockers for writing the test are. I'm not exactly sure what needs to be done here, but you could try to initialize a `DropdownMenuItem` without the `value` parameter and write a test to ensure that isn't allowed.

This PR would still be a breaking change (although a smaller one than the one we went through) and would require following Flutter's breaking change policy, since anybody who did not have `value` defined will have a broken application, so please go ahead and follow that procedure before we move forward with this change.

**Comment by pedromassango** [comment]
> We need to somehow test that `DropdownMenuItem` requires a value now. If that's not possible, then explain what the blockers for writing the test are. I'm not exactly sure what needs to be done here, but you could try to initialize a `DropdownMenuItem` without the `value` parameter and write a test to ensure that isn't allowed.
> 
> This PR would still be a breaking change (although a smaller one than the one we discussed) and would require following Flutter's breaking change policy, since anybody who did not have `value` defined will have a broken application. Please go ahead and follow that procedure before we move forward with this change.

The `value` param currently is not required but wigets like `DropdownButtonFormField` can't work properly if it is not specified (they use it to return in `onChanged ` method that is called when a item is pressed). This is what causes this issue: https://github.com/flutter/flutter/issues/56725. So if someone is not using this param maybe their code is  not working as expected. So I don't think this will be a breaking change!

I will find a way to add some tests.

**Comment by christopherfujino** [comment]
>So if someone is not using this param maybe their code is not working as expected. So I don't think this will be a breaking change!

@pedromassango please see https://github.com/flutter/flutter/wiki/Tree-hygiene#1-determine-if-your-change-is-a-breaking-change to see the definition of a breaking change.

**Comment by pedromassango** [comment]
> > So if someone is not using this param maybe their code is not working as expected. So I don't think this will be a breaking change!
> 
> @pedromassango please see https://github.com/flutter/flutter/wiki/Tree-hygiene#1-determine-if-your-change-is-a-breaking-change for the formal determination of a breaking change.

After reading this I must agree that this is a breaking change.

**Comment by shihaohong** [comment]
Hi @pedromassango, any progress with the breaking change steps?

**Comment by pedromassango** [comment]
> Hi @pedromassango, any progress with the breaking change steps?

Nothing yet. Maybe we can just add the required annotation without the assertion to prevent breaking changes. This will not prevent the user to not specify it but the analyzer will show a warning.

**Comment by shihaohong** [comment]
I think that even if your suggestion isn't technically preventing users from using a `null` value, they might still feel frustration seeing a new warning/error message when they did not before. I would still recommend writing at least a breaking change announcement since it'd be ideal to not catch them off guard.

**Comment by christopherfujino** [comment]
> I think that even if your suggestion isn't technically preventing users from using a `null` value, they might still feel frustration seeing a new warning/error message when they did not before.

Agreed. And if they run analysis in CI and use this widget this change will break their build.

**Comment by pedromassango** [comment]
> I think that even if your suggestion isn't technically preventing users from using a `null` value, they might still feel frustration seeing a new warning/error message when they did not before. I would still recommend writing at least a breaking change announcement since it'd be ideal to not catch them off guard.

Right. Could you help me with the breaking change announcement?!

**Comment by shihaohong** [comment]
There are steps in [the breaking change policy](https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes) for how to handle a breaking change in Flutter.

**Comment by shihaohong** [comment]
Hi, I'm going to close out this PR because it's been inactive for almost a month now. Feel free to reopen the PR when you can come back to it :)

**Comment by pedromassango** [comment]
@shihaohong  I have some time to work on this now!

**Pull request closed without merging**
