### PR TITLE
Feature: `ExpandIcon` should use the `size` parameter

### PR DESCRIPTION
**Pull request by Inconnu08**
## Related Issues
#45692

## Tests

I added the following tests:
- `ExpandIcon default size is 24`
- `ExpandIcon has the correct given size`

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by shihaohong** [comment]
Hi @Inconnu08! Could you add tests to verify for a default behavior ("default size"), as well as passing in a few size values to the ExpandIcon to make sure that changes are expected?

**Comment by Inconnu08** [comment]
@shihaohong sorry was a bit busy but here it is

**Review by shihaohong — APPROVED** [review]
LGTM

**Comment by shihaohong** [comment]
I restarted the `docs-linux` test since it seems to be failing for reasons unrelated to your PR. If it fails again, you might have to rebase with master

**Comment by shihaohong** [comment]
Strangely, rerunning the failing `docs-linux` check caused one checkmark to pass, while the other "failing" checkmark is stuck on the previous run. I'm merging on red and will monitor its progress since it seems like it's the CI having issues rather than an actual failing check.

**Comment by Inconnu08** [comment]
closes #45692

**Pull request merged**
