### PR TITLE
Remove elevation/thickness from semantics

### PR DESCRIPTION
**Pull request by goderbauer**
🫡

These were never used for anything.

In spirit, this is a revert of https://github.com/flutter/flutter/pull/25670.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
RIP IN PIECE

LGTM

**Comment by goderbauer** [comment]
Sadly, it is failing tests because it is changing the shape of the semantics tree in some places. For unknown reasons, this change turns child-parent semantics nodes into siblings in some cases. I'll have to investigate a bit more and see what impact it has on g3.

**Comment by jonahwilliams** [comment]
Hmm, did our merging rules take the elevation into account perhaps?

**Comment by goderbauer** [comment]
I am losing this one for now as I don't have time to figure out why/how this is breaking things.

**Pull request closed without merging**
