### PR TITLE
Do not animate `TabBarView` if controller is invalid

### PR DESCRIPTION
**Pull request by gilnobrega**
An exception is raised by TabBar when its TabController gets replaced with another controller while it is animating between two tabs.

This happens because the method `_handleScrollNotification` in `_TabBarViewState` tries to set `_controller.offset` value, which setter depends on a non-nullable `_controller.animation`. 
However, this Animation is null if `_controller.dispose()` is called, e.g.: when the controller is replaced with another controller.

This merge request prevents calling `_controller.offset` if a pre-existing boolean `_controllerIsValid` condition is not met in the `_handleScrollNotification` method.

Fixes issue #34744 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by nehaaaa6** [comment]
class _TabBarViewState extends State<TabBar> with TickerProviderStateMixin {
  late TabController _controller;
  late bool _controllerIsValid; // new boolean variable

  @override
  void initState() {
    super.initState();
    _controller = widget.controller ?? DefaultTabController.of(context);
    _controllerIsValid = true; // initialize to true
  }

  @override
  void dispose() {
    _controllerIsValid = false; // set to false before calling dispose()
    _controller.dispose();
    super.dispose();
  }

  ...

  void _handleScrollNotification(ScrollNotification notification) {
    if (notification is ScrollUpdateNotification && notification.depth == 0) {
      _controllerIsValid = _controller.animation != null; // check if animation is not null
      if (_controllerIsValid) {
        _controller.offset -= notification.scrollDelta;
      }
    }
  }

  ...
}

**Comment by nehaaaa6** [comment]
In this modified method, we added a check for _controllerIsValid before accessing _controller.animation and _controller.offset. _controllerIsValid is a boolean flag that you can set to true when the _controller is created, and set to false when _controller.dispose() is called.

By adding this check, we prevent accessing _controller.animation when it is null, which should fix the issue you described.

**Comment by gilnobrega** [comment]
@nehaaaa6 `_controllerIsValid` is already defined in `_TabBarViewState`, see line 1620 of tabs.dart file.

This page is not an issue, it's a pull request, you can see the fix I proposed in the `Files changed` tab.

**Comment by HansMuller** [comment]
BTW: you can check for analyzer errors locally 
with `flutter analyze --flutter-repo`

**Comment by gilnobrega** [comment]
> BTW: you can check for analyzer errors locally with `flutter analyze --flutter-repo`

Thanks, I was trying to make sense of what those logs in analyze-linux meant, then I noticed Cirrus CI shows the full log

**Review by HansMuller — APPROVED** [review]
LGTM

**Pull request merged**
