### PR TITLE
[SingleChildScrollView] Correct the offset pixels if it is out of range during layout

### LINKED ISSUE #105733: Scroll with unnecessary animation and updates when maximizing window.
Hi!

I recorded this GIF doing the horizontal resizing (to have a smaller image) but it generates the same effect when maximize the window.

scroll

You can see that the scroll keeps changing its size and the content keeps moving.

This happens when the scroll offset is at the end.

In horizontal resizing, it is understandable because it must generate multiple events. But it gets really weird when maximizing the window (should be only one event) and seeing the entire content slowly move to the side.

I've also noticed that the scroll offset is updated numerous times when maximizing the window as if trying to adjust until it succeeds. Updates before the last one are also with offset values greater than the maximum allowed. This also happens when resizing horizontally.

## Steps to Reproduce

1. move scroll to the end
2. maximize the window

## Code

```dart
class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final ScrollController _scrollController = ScrollController();

  @override
  void initState() {
    _scrollController.addListener(_scrollListener);
    super.initState();
  }

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  void _scrollListener() {
    // offset bigger than maxScrollExtent?
    print(
        'offset: ${_scrollController.offset} / maxScrollExtent: ${_scrollController.position.maxScrollExtent}');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Theme(
            data: ThemeData(
                scrollbarTheme: ScrollbarThemeData(
                    thumbVisibility: MaterialStateProperty.all(true),
                    thumbColor: MaterialStateProperty.all(Colors.red))),
            child: Scrollbar(
                controller: _scrollController,
                child: SingleChildScrollView(
                    controller: _scrollController,
                    scrollDirection: Axis.horizontal,
                    child:
                        const SizedBox(width: 2000, child: Placeholder())))));
  }
}
```

## Prints from the listener

```
...
offset: 82.05680889386778 / maxScrollExtent: 80
offset: 81.76819620001922 / maxScrollExtent: 80
offset: 81.51992893399559 / maxScrollExtent: 80
offset: 81.30657864605345 / maxScrollExtent: 80
offset: 81.12319587706092 / maxScrollExtent: 80
offset: 80 / maxScrollExtent: 80
```

## flutter doctor -v

```
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.13.0-48-generic, locale en_US.UTF-8)
    • Flutter version 3.0.1 at /cadu/desenv/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /home/cadu/Android/Sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_SDK_ROOT = /home/cadu/Android/Sdk
    • Java binary at: /cadu/desenv/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /cadu/desenv/android-studio
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at /cadu/desenv/idea-IC-211.7628.21
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • moto g 9 plus (mobile) • 0069365263 • android-arm64  • Android 11 (API 30)
    • Linux (desktop)        • linux      • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-48-generic
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### LINKED ISSUE #135865: DropdownMenu throws an assert error if keyboard is closed while menu is open
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the code on simulator
2. Select the textfield
3. Select the dropdown menu
4. Press done to close the keyboard

### Expected results

No crash

### Actual results

Crash

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: const SingleChildScrollView(
        child: Column(
          children: [
            Padding(
              padding: EdgeInsets.symmetric(vertical: 20, horizontal: 16),
              child: Column(
                children: [
                  SizedBox(height: 500),
                  TextField(
                    decoration: InputDecoration(label: Text('Textfield')),
                  ),
                  SizedBox(height: 24),
                  DropdownMenu<int>(
                    label: Text('Dropdown'),
                    dropdownMenuEntries: [
                      DropdownMenuEntry(value: 1, label: 'Dropdown Item 1'),
                      DropdownMenuEntry(value: 2, label: 'Dropdown Item 2'),
                      DropdownMenuEntry(value: 3, label: 'Dropdown Item 3'),
                      DropdownMenuEntry(value: 4, label: 'Dropdown Item 4')
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/33460888/8d5f27f6-243d-4ee3-a28d-81ef09265fd8

</details>

### Logs

<details><summary>Logs</summary>

```console
[+10554 ms] ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
                     The following assertion was thrown while dispatching notifications for ValueNotifier<bool>:
                     Build scheduled during frame.
                     While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild
                     the widget tree.
                     This might be because setState() was called from a layout or paint callback. If a change is needed
                     to the widget tree, it should be applied as the tree is being built. Scheduling a change for the
                     subsequent frame instead results in an interface that lags behind by one frame. If this was done to
                     make your build dependent on a size measured at layout time, consider using a LayoutBuilder,
                     CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is
                     the desired effect, for example because this is an animation, consider scheduling the frame in a
                     post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to
                     trigger the animation.
                     
                     When the exception was thrown, this was the stack:
                     #0      WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:849:9)
                     #1      WidgetsBinding._handleBuildScheduled (package:flutter/src/widgets/binding.dart:872:6)
                     #2      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2721:24)
                     #3      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:5050:12)
                     #4      State.setState (package:flutter/src/widgets/framework.dart:1223:15)
                     #5      _MenuAnchorState._close (package:flutter/src/material/menu_anchor.dart:563:7)
                     #6      _MenuAnchorState._handleScroll (package:flutter/src/material/menu_anchor.dart:472:13)
                     #7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24)
                     #8      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:555:5)
                     #9      ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:1003:25)
                     #10     ScrollPositionWithSingleContext.beginActivity
(package:flutter/src/widgets/scroll_position_with_single_context.dart:113:11)
                     #11     ScrollPositionWithSingleContext.goBallistic
(package:flutter/src/widgets/scroll_position_with_single_context.dart:146:7)
                     #12     IdleScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:159:14)
                     #13     ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:706:15)
                     #14     ScrollPositionWithSingleContext.applyNewDimensions
(package:flutter/src/widgets/scroll_position_with_single_context.dart:102:11)
                     #15     ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:635:7)
                     #16     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:499:12)
                     #17     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
                     #18     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
                     #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
                     #20     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
                     #21     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
                     #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
                     #23     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
                     #24     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
                     #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
                     #26     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
                     #27     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
                     #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
                     #29     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
                     #30     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
                     #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
                     #32     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
                     #33     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
                     #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
                     #35     RenderObject.layout (package:flutter/src/rendering/object.dart:2546:7)
                     #36     RenderBox.layout (package:flutter/src/rendering/box.dart:2389:11)
                     #37     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
                     #38     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1062:7)
                     #39     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
                     #40     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
                     #41     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385:7)
                     #42     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025:18)
                     #43     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038:15)
                     #44     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
                     #45     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
                     #46     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
                     #47     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
                     #48     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
                     #49     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
                     #50     _invoke (dart:ui/hooks.dart:312:13)
                     #51     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
                     #52     _drawFrame (dart:ui/hooks.dart:283:31)
                     
                     The ValueNotifier<bool> sending notification was:
                       ValueNotifier<bool>#01070(true)
                     ════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.16.0-2.0.pre.6, on macOS 13.5.2 22G91 darwin-arm64, locale en-VN)
    • Flutter version 3.16.0-2.0.pre.6 on channel master at /Users/howl/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bfd4cf6a2b (77 minutes ago), 2023-10-02 12:12:14 -0400
    • Engine revision c0cf135b11
    • Dart version 3.2.0 (build 3.2.0-221.0.dev)
    • DevTools version 2.28.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/howl/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/howl/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • iPorn 14 (mobile)          • 00008120-001A593811E0C01E            • ios            • iOS 17.0 21A329
    • iPhone 15 Pro Max (mobile) • E1D76201-773A-4AF6-9CBC-19AF1A033835 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0
      (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes https://github.com/flutter/flutter/issues/105733
FIxes https://github.com/flutter/flutter/issues/135865

The above two issues will not occur on the `ListView` widget, so after analyzing their differences, it was found that the `SingleChildScrollView` pixels were not corrected according to the content dimensions during layout.

### ListView correct the pixels codes
https://github.com/flutter/flutter/blob/5dfd78c2e30483a9a8668ba6b754d089b1e132c8/packages/flutter/lib/src/rendering/viewport.dart#L1462-L1465

We should correct the pixels to prevent the physics ballistic simulations.

This change makes them have the same behavior.

### CODE REVIEW

**Review by Piinks — APPROVED** [review]
This is an excellent find! Thank you for tracking it down and fixing it.
LGTM

**Comment by Piinks** [comment]
This broke a customer test, I am going to revert this and will see about getting a repro of the customer issue.

**Comment by martinale14** [comment]
This pr causes an error when you work with offsets and some custom animations, this forces when you set state on that animations to keep always on top and can not perform outofscroll behavior

**Comment by xu-baolin** [comment]
> This pr causes an error when you work with offsets and some custom animations, this forces when you set state on that animations to keep always on top and can not perform outofscroll behavior

Hi, could you file a new issue and supply a minimal example to reproduce the problem?

**Pull request merged**
