### PR TITLE
Tiny fix about outdated message

### PR DESCRIPTION
**Pull request by fzyzcjy**
The message is in `_ensureOutputIsNotJsonRpcError`, and that method is called both in runSkia and runRasterizer. Thus, it is not reasonable to say "... skia output ..." because it can also be a rasterizer output.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by christopherfujino — COMMENTED** [review]
This looks like a good change. Can you add a test?

**Comment by fzyzcjy** [comment]
@christopherfujino Sure, will do this soon

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by Jasguerrero — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
@fzyzcjy sorry, I think Google testing is failing due to an infrastructure problem. Can you rebase this upstream and push again?

**Comment by christopherfujino** [comment]
Landing on red Google testing as this is an infrastructure error

**Pull request merged**
