### PR TITLE
fix spelling typo

### PR DESCRIPTION
**Pull request by suragch**
"empty" was spelled wrong.

- emtpy -> empty

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by LongCatIsLooong — APPROVED** [review]
LGTM. But the `_index` field is not nullable. /cc @justinmc

**Comment by justinmc** [comment]
I guess I made several mistakes here 😊.  I think this would be best actually:

```dart
// The index of the current value, or -1 if the list is empty.
int _index = -1;
```

Notice that in the `clear` method, _index gets set to -1.  So this would make the state of the class consistent before the first push and after a clear.

**Comment by HansMuller** [comment]
@suragch - can you address https://github.com/flutter/flutter/pull/120062#issuecomment-1421424676?

**Comment by suragch** [comment]
I've updated the PR to address the comments by @LongCatIsLooong and @justinmc

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

**Comment by Renzo-Olivares** [comment]
@suragch looks like some tests are failing, though they seem unrelated to the changes in this PR. Do you mind syncing up to the latest commit and seeing if that helps?

**Comment by suragch** [comment]
@Renzo-Olivares Tests are passing after syncing.

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
