### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by Hixie**
Improve some terminology to make it clearer what is going on, especially for people not familiar with English idioms.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @Piinks

**Comment by Piinks** [comment]
Related to #59484. That one found more idioms, ok to defer to that one?

**Comment by goderbauer** [comment]
Looks like we had the same idea over the weekend: https://github.com/flutter/flutter/pull/59484

**Comment by Hixie** [comment]
Happy to defer.

**Pull request closed without merging**
