### PR TITLE
[doc] Update `suffixIcon`/`prefixIcon` for alignment with code snippet

### PR DESCRIPTION
**Pull request by TahaTesser**
Related 
https://github.com/flutter/flutter/issues/67426
https://github.com/flutter/flutter/issues/91804
https://github.com/flutter/flutter/issues/22471

Using `Align` with custom padding also fixes this issue but need to provide `heightFactor: 10.0,` has to match `maxLines: 10`
https://github.com/flutter/flutter/issues/42651
```dart
      body: const Center(
        child: TextField(
          maxLines: 10,
          textAlignVertical: TextAlignVertical.top,
          decoration: InputDecoration(
            border: OutlineInputBorder(),
            labelText: 'Enter your text here',
            prefixIcon: Padding(
              padding: EdgeInsets.only(top: 20),
              child: Align(
                alignment: Alignment.topCenter,
                widthFactor: 1.0,
                heightFactor: 10.0,
                child: Icon(
                  Icons.lock,
                ),
              ),
            ),
          ),
        ),
      ),
```

This wasn't documented when this was closed
https://github.com/flutter/flutter/pull/67496

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by justinmc — APPROVED** [review]
LGTM 👍   I'll ask for a no-test exception on discord.

Thanks for adding this.  You're right that it deserves an example like this after the discussion in the closed PR https://github.com/flutter/flutter/pull/67496.

@cedvdb Can we continue this discussion on an issue, maybe one of the ones linked in the description at the top?  You're right that it's hard to align the prefix/suffix to the baseline in many cases.  All of the code for the prefix/suffix positioning is [here](https://github.com/flutter/flutter/blob/5cf7eaf511340cbfb427bcca237b59fad542d535/packages/flutter/lib/src/material/input_decorator.dart#L984).  It's not immediately obvious how we can solve this in a way that makes it easy to align to baseline while still allowing the alignment to be customized with Align, but we can probably think of something.

**Review by gspencergoog — COMMENTED** [review]
> Updated the code snippet with {@tool snippet} and fixed nits.

This is better, but I think it would be better to use a complete dartpad example. This seems like exactly the sort of thing that would benefit from having a visual example that can be played with.

You can also write a test for it then, to make sure the example continues to work in the future.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Looks great! Thanks so much for adding examples!

**Comment by francip** [comment]
This solution does not work for `TextField` with `maxLines: null`.

**Pull request merged**
