### PR TITLE
Fix `TimePicker` defaults for `hourMinuteTextStyle` and `dayPeriodTextColor` for Material 3

### LINKED ISSUE #127035: `TimePicker` color and visual issues
#91605

I think we should make small visual changes to the TimePicker:

1. Change the "Period selector label text" to "On surface variant" for a non-selected color.

`from specification`
unnamed

`from flutter`
Screenshot_2023_05_17_15_13_09_717_com_example_material_3_demo

2. In the "Time picker input" change the width of the period selection container, making it the same as in the time picker with the (12 hour) selector.

1 | 2
--- | ---
Screenshot_2023_05_17_15_45_35_739_com_example_material_3_demo | Screenshot_2023_05_17_15_45_15_624_com_example_material_3_demo

3. In the "Time picker dial" reduce the width of the period selector container, making it a width (114 dp), which is slightly larger than with the selector (12 hour).

`example Flutter / Compose`
Screenshot_2023_05_17_15_21_10_535_androidx_compose_material_catalog

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes [`TimePicker` color and visual issues](https://github.com/flutter/flutter/issues/127035)

## Description

- fixes default text style for `TimePicker`s  `hourMinuteTextStyle` and added a todo for https://github.com/flutter/flutter/issues/131247
- fixes correct default color not being accessed for  `dayPeriodTextColor`
-  Updates tests

### Code sample

<details> 
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(useMaterial3: true),
      home: const Example(),
    );
  }
}

class Example extends StatelessWidget {
  const Example({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sample'),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            showTimePicker(
              context: context,
              orientation: Orientation.portrait,
              initialEntryMode: TimePickerEntryMode.input,
              initialTime: TimeOfDay.now(),
              builder: (BuildContext context, Widget? child) {
                return MediaQuery(
                  data: MediaQuery.of(context)
                      .copyWith(alwaysUse24HourFormat: true),
                  child: child!,
                );
              },
            );
          },
          child: const Text('Open Time Picker'),
        ),
      ),
    );
  }
}

``` 
	
</details>

### Before

  
ezgif com-video-to-gif

### After

ezgif com-video-to-gif (1)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Thanks! This may require some changes to the Google test golden files, but I'll look out for that.

**Comment by TahaTesser** [comment]
Ping @gspencergoog

**Comment by gspencergoog** [comment]
Sorry, @TahaTesser  what did you need from me here?  It seems like the Google test is still pending.

**Comment by TahaTesser** [comment]
> Sorry, @TahaTesser what did you need from me here? It seems like the Google test is still pending.

In case you need to check golden images, I didn't rebase.  Let me try that.

**Pull request merged**
