### PR TITLE
Fix slider preferred height

### PR DESCRIPTION
**Pull request by brettmeemo**
## Description

This PR fixes the preferred height of the slider.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by brettfingo** [comment]
I have signed it!

**Review by jaleelmeemo — APPROVED** [review]

**Comment by dnfield** [comment]
Thanks for the contribution!

Can you add a test for this?

**Comment by HansMuller** [comment]
CC @clocksmith

**Comment by clocksmith** [comment]
LGTM, but please add a test

**Comment by brettfingo** [comment]
I'm sorry but I don't have time to write a test, if someone would like to do this fix and write a test I'd be happy to close this PR and let that one merge.

**Comment by dnfield** [comment]
Unfortunately we can't merge a change like this without a test. I did a little digging to see what a test for this would look like, and it looks like this code passes today because all the implementations that touch these properties use sizes where height == width.  So a test should create a property where the height > width, pass it into the theme, and make sure the widget is laid out correctly.

```dart

  testWidgets('Slider respects width and height from theme', (WidgetTester tester) async {
    final Key sliderKey = UniqueKey();
    double value = 0.0;
    await tester.pumpWidget(
      Directionality(
        textDirection: TextDirection.ltr,
        child: StatefulBuilder(
          builder: (BuildContext context, StateSetter setState) {
            final SliderThemeData sliderTheme = SliderTheme.of(context).copyWith(tickMarkShape: TallSliderTickMarkShape());
            return MediaQuery(
              data: MediaQueryData.fromWindow(window),
              child: Material(
                child: Center(
                  child: IntrinsicHeight(
                    child: SliderTheme(
                      data: sliderTheme,
                      child: Slider(
                        key: sliderKey,
                        value: value,
                        divisions: 4,
                        onChanged: (double newValue) {
                          setState(() {
                            value = newValue;
                          });
                        },
                      ),
                    ),
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );

    final RenderBox renderObject = tester.renderObject<RenderBox>(find.byType(Slider));
    expect(renderObject.size.height, 200);
  });
```

Where TallSliderTickMarkShape is something like:

```dart
class TallSliderTickMarkShape extends SliderTickMarkShape {
  @override
  Size getPreferredSize({SliderThemeData sliderTheme, bool isEnabled}) {
    return const Size(10.0, 200.0);
  }

  @override
  void paint(
      PaintingContext context,
      Offset offset, {
      Offset thumbCenter,
      RenderBox parentBox,
      SliderThemeData sliderTheme,
      Animation<double> enableAnimation,
      bool isEnabled,
      TextDirection textDirection,
    }) {
    final Paint paint = Paint()..color = Colors.red;
    context.canvas.drawRect(Rect.fromLTWH(offset.dx, offset.dy, 10.0, 20.0), paint);
  }
}
```

**Comment by clocksmith** [comment]
@dnfield Shouldn't this height > width case be for the whole Slider component (the inner RenderBox), not just the TickMarkShape?

**Comment by dnfield** [comment]
@clocksmith - any one of those will cause the height to be higher

**Review by dnfield — APPROVED** [review]
LGTM

**Pull request merged**
