### PR TITLE
make FlexibleSpaceBarSettings public

### PR DESCRIPTION
**Pull request by procedurallygenerated**
When we create a custom FlexibleSpaceBar widget for use with the SliverAppBar we are not able to access the FlexibleSpaceBarSettings since it's private.

This will be useful when you want to provide a flexible space bar with custom behaviour, but you want to reuse the code written in the SliverAppBar and _SliverAppBarDelegate.

### CODE REVIEW

**Comment by procedurallygenerated** [comment]
I signed it!

**Comment by xster** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
API docs and tests?

**Comment by procedurallygenerated** [comment]
@HansMuller Do I need to write tests for this?

**Comment by HansMuller** [comment]
Yes, tests and docs.

**Comment by procedurallygenerated** [comment]
@HansMuller Sure I can do that. I am new to this for go easy on me if this is obvious.

The change makes one private settings class public. How do I test this? Where do I document it?

**Comment by HansMuller** [comment]
Sorry, I'd thought this change came from @xster. Your userid @procedurallygenerated threw me :-).

By "docs" I meant dart API docs. The code doesn't have any because we often don't write them for private classes. 

A small example that showed how the class would be used could be included as well (see for example https://docs.flutter.io/flutter/material/AppBar-class.html)

There's useful information about writing dart API docs in Flutter's style guide: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo

As far as tests go, the objective is to verify that the class works correctly (per the docs!) and that it doesn't regress in the future.  See https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md#adding-a-test

**Comment by Hixie** [comment]
@procedurallygenerated I'm going to close this PR just to get it off our review queue; if you have the chance to add the suggested changes, please don't hesitate to open a new PR; otherwise don't worry, we'll eventually look at it and probably land it ourselves.

**Pull request closed without merging**
