### PR TITLE
fix scrollable widget scrollDirection update bug

### LINKED ISSUE #81952: ListView throws '_drag == null': is not true exception
I had a problem with my demo of ListView sliders. I think it's a bug in the  flutter framework. Hopefully the Flutter team will fix it！

<details>
  <summary>Demo1</summary>

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'dart:math';
import 'dart:math' as math;

void main() => runApp(ListViewPortDemo());

class ListViewPortDemo extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _ListViewPortDemoState();
}

class _ListViewPortDemoState extends State<ListViewPortDemo> {

  List<double>? _initHeights;

  late ScrollController _scrollController;
  double _listSize = 450;

  Axis _axis = Axis.vertical;
  bool _reverse = true;

  final Random rd = Random();

  void updateHeights() {
    final int count = _initHeights?.length ?? rd.nextInt(20) + 10000;
    _initHeights = List.generate(count, (index) => rd.nextDouble() * 100 + 40);
  }

  void _resetListSize() {
    _listSize = rd.nextDouble() * 350 + 100;
  }

  @override
  void initState() {
    super.initState();
    updateHeights();
    _scrollController = ScrollController();
  }

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  Widget _buildText(int index) {
    final Widget child = Text("$index",
      style: TextStyle(
        fontSize: 16,
      ),
    );
    return RotatedBox(
      quarterTurns: _axis == Axis.horizontal ? 1 : 0,
      child: child,
    );
  }

  Widget _buildListView(context) {
    return Container(
      height: _axis == Axis.horizontal
          ? MediaQuery.of(context).size.height - 220
          : _listSize,
      width: _axis == Axis.horizontal ? _listSize : double.infinity,
      color: Colors.black12,
      child: ListView.builder(
        scrollDirection: _axis,
        physics: BouncingScrollPhysics(),
        controller: _scrollController,
        reverse: _reverse,
        itemBuilder: (context, index) {
          return Container(
            height: _axis == Axis.horizontal
                ? double.infinity
                : _initHeights![index],
            width: _axis == Axis.horizontal
                ? _initHeights![index]
                : double.infinity,
            color: Colors
                .primaries[index % Colors.primaries.length],
            alignment: Alignment.center,
            child: _buildText(index),
          );
        },
        itemCount: _initHeights!.length,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Center(
          child: SingleChildScrollView(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: [
                Stack(
                  children: [
                    Builder(builder: (context) {
                      return _buildListView(context);
                    }),
                    Positioned(
                      child: Center(
                        child: Transform.rotate(
                          angle: _axis == Axis.horizontal ? math.pi / 2 : 0,
                          child: Text(
                            "center",
                            style: TextStyle(
                              color: Colors.redAccent,
                              fontStyle: FontStyle.italic,
                              fontWeight: FontWeight.bold,
                              fontSize: 10.5,
                              backgroundColor: Colors.white,
                            ),
                          ),
                        ),
                      ),
                      top: 0,
                      bottom: 0,
                      left: 0,
                      right: 0,
                    ),
                    Positioned(
                      child: Offstage(
                        offstage: _axis != Axis.horizontal,
                        child: VerticalDivider(
                          color: Colors.black,
                          width: 2.0,
                        ),
                      ),
                      top: 0,
                      bottom: 0,
                      left: 0,
                      right: 0,
                    ),
                    Positioned(
                      child: Offstage(
                        offstage: _axis != Axis.vertical,
                        child: Divider(
                          height: 2.0,
                          color: Colors.black,
                        ),
                      ),
                      top: 0,
                      bottom: 0,
                      left: 0,
                      right: 0,
                    ),
                  ],
                ),
                Wrap(
                  spacing: 24,
                  children: [
                    TextButton(
                      onPressed: () {
                        setState(() {
                          _resetListSize();
                        });
                      },
                      child: Text("Resize"),//the first step
                    ),
                    TextButton(
                      onPressed: () {
                        setState(() {
                          _axis = _axis == Axis.horizontal
                              ? Axis.vertical
                              : Axis.horizontal;
                        });
                      },
                      child: Text("Change Direction"),//the second step
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
  <summary>Demo2</summary>

```
import 'dart:math';
import 'package:flutter/material.dart';

void main() => runApp(SimpleScrollViewDemo());

class SimpleScrollViewDemo extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _SimpleScrollViewDemoState();
}

class _SimpleScrollViewDemoState extends State<SimpleScrollViewDemo> {
  double _height = 360;
  Axis _axis = Axis.vertical;
  Random _random = Random();

  ScrollController _controller = ScrollController();
  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: Column(
          children: [
            _buildListView(),
            _buildBtn(),
          ],
        ),
      ),
    );
  }

  Widget _buildBtn() {
    return Row(
      children: [
        TextButton(
          onPressed: () {
            setState(() {
              _height = _random.nextInt(100) + 120;
            });
          },
          child: Text("Resize"),
        ),
        TextButton(
          onPressed: () {
            setState(() {
              _axis =
                  _axis == Axis.horizontal ? Axis.vertical : Axis.horizontal;
            });
          },
          child: Text("Change Direction"),
        ),
      ],
    );
  }

  Widget _buildListView() {
    return Container(
      color: Colors.black12,
      height: _height,
      width: double.infinity,
      child: ListView.builder(
        scrollDirection: _axis,
        controller: _controller,
        itemBuilder: (_, index) {
          return Container(
            color: Colors.primaries[index % Colors.primaries.length],
            height: _axis == Axis.vertical ? (_random.nextDouble() * 80 + 20) : null,
            width: _axis == Axis.horizontal ? (_random.nextDouble() * 80 + 20) : null,
            alignment: Alignment.center,
            child: Text("$index"),
          );
        },
      ),
    );
  }
}

```
</details>

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. Steps to reproduce the problem: 
_Step 1: Click the **`Resize`** button.
Step 2: Click the **`Change Direction`** button.
Step 3: Swipe the screen freely._

**Expected results:** 
The `ListView` scrolls normally, and the program does not throw an exception.

**Actual results:** 
_Demo1:_
The `ListView` scrolls exception, and the program always throws an exception:
_**'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 582 pos 12: '_drag == null': is not true.**_

_Demo2:_
The `ListView` simply scrolls exception, but the program doesn't throw an error.

<details>
  <summary>Logs</summary>

```
Launching lib\main.dart on M6 Note in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:61159/scpcD28kbaI=/ws
Syncing files to device M6 Note...
I/art     (22028): IsDexFileNeededDisableVerify for /system/framework/QPerformance.jar
I/art     (22028): GetPkgNameFromDexFile return /system/framework/QPerformance.jar

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 582 pos 12: '_drag == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:582:12)
#3      DragGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:403:51)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#5      DragGestureRecognizer._checkDown (package:flutter/src/gestures/monodrag.dart:403:7)
#6      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:267:7)
...
Handler: "onDown"
Recognizer: HorizontalDragGestureRecognizer#cef67
  start behavior: start
====================================================================================================

======== Exception caught by gesture ===============================================================
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 591 pos 12: '_drag == null': is not true.
====================================================================================================
```

```
Analyzing flutter_new_test...
No issues found! (ran in 3.0s)
```

```
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.17763.1817], locale zh-CN)
    • Flutter version 2.0.2 at C:\wuchaochao\flutter\tools\flutter
    • Framework revision 8962f6dc68 (8 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\wuchaochao\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\wuchaochao\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Users\wuchaochao\AppData\Local\Chromium\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\wuchaochao\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • M6 Note (mobile) • 721QADRR45FUF • android-arm64  • Android 7.1.2 (API 25)
    • Chrome (web)     • chrome        • web-javascript • unknown

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes #81952 

### Repro Steps
1, Run the code below
2, Tap the floating button to change the `scrollDireaction` to horizontal
3, Bug appeared. Vertical drag can cause scrolling instead of horizontal drag.

### Root Cause
The `scrollDireaction` change can not trigger `ScrollableState.setCanDrag`
Here is the `setCanDrag` call stack when `applyContentDimensions`(re-layout)
```dart
I/flutter (19596): #0      debugPrintStack (package:flutter/src/foundation/assertions.dart:1150:29)
I/flutter (19596): #1      ScrollableState.setCanDrag (package:flutter/src/widgets/scrollable.dart:543:5)
I/flutter (19596): #2      ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:105:13)
I/flutter (19596): #3      ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:536:7)
I/flutter (19596): #4      _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:586:12)
I/flutter (19596): #5      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (19596): #6      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:881:18)
I/flutter (19596): #7      RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:462:19)
I/flutter (19596): #8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:879:13)
I/flutter (19596): #9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
I/flutter (19596): #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1147:15)
I/flutter (19596): #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1084:9)
I/flutter (19596): #12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1000:5)
I/flutter (19596): #16     _invoke (dart:ui/hooks.dart:163:10)
I/flutter (19596): #17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
I/flutter (19596): #18     _drawFrame (dart:ui/hooks.dart:126:31)
I/flutter (19596): (elided 3 frames from dart:async)
```

### Code
```dart
import 'package:flutter/material.dart';

void main() => runApp(BugReport());

class BugReport extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => BugReportState();
}

class BugReportState extends State<BugReport> {
  bool flag = true;
  final ScrollController controller = ScrollController();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              flag = !flag;
            });
          },
        ),
        body: Center(
          child: SizedBox(
            height: 100,
            width: 100,
            child: SingleChildScrollView(
              controller: controller,
              scrollDirection: flag ? Axis.vertical : Axis.horizontal,
              child: SizedBox(
                width: 200,
                height: 200,
                child: FlutterLogo(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

### CODE REVIEW

**Comment by chunhtai** [comment]
Hi @xu-baolin I couldn't reproduce this in macOS, can you still reproduce the bug?

**Comment by xu-baolin** [comment]
I reproduce this on a android phone, did you try the unit test on the macOS? I will try the test app on the macOS and will let you know the results.

**Comment by xu-baolin** [comment]
@chunhtai Hi, Update status, can repro on the iPhone simulator.
On macOS app, repro with(drag whit mouse or single pointer down, do not use the track with two pointers):
```dart
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';

void main() => runApp(BugReport());

class BugReport extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => BugReportState();
}

class BugReportState extends State<BugReport> {
  bool flag = true;
  final ScrollController controller = ScrollController();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      scrollBehavior: MyCustomScrollBehavior(),
      home: Scaffold(
        appBar: AppBar(),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              flag = !flag;
            });
          },
        ),
        body: Center(
          child: SizedBox(
            height: 100,
            width: 100,
            child: SingleChildScrollView(
              controller: controller,
              scrollDirection: flag ? Axis.vertical : Axis.horizontal,
              child: SizedBox(
                width: 200,
                height: 200,
                child: FlutterLogo(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

class MyCustomScrollBehavior extends MaterialScrollBehavior {
  // Override behavior methods and getters like dragDevices
  @override
  Set<PointerDeviceKind> get dragDevices => {
    PointerDeviceKind.touch,
    PointerDeviceKind.mouse,
    // etc.
  };
}
```

**Comment by chunhtai** [comment]
I can't reproduce the crashing, but i can reproduce the scroll direction and drag direction out of sync

**Review by chunhtai — APPROVED** [review]
LGTM, nice fix!

**Comment by xu-baolin** [comment]
> I can't reproduce the crashing, but i can reproduce the scroll direction and drag direction out of sync

You are right.
The original crashing is a follow-up issue, and I can repro it use the original sample code.
After this change, the crashing can not reproduce.

**Pull request merged**
