### PR TITLE
Fix errors in grapheme cluster boundary detection

### LINKED ISSUE #76850: Family emojis (👨‍👩‍👧‍👦) misbehave on deletion with Samsung keyboard
I notice that only the family emojis will produce this issue. Also, sometime (randomly) the cursor is positioned at the middle of the emoji.  

|Samsung One UI2.1 Keyboard|Emulator (Google Pixel 3A) Keyboard|
|-|-|
|samsung one ui keyboard|google keyboard|

**Expected results:** 
The cursor should be positioned at the end of the emoji.
The emoji itself should be deleted entirely while deleting.

**Actual results:** 
The cursor positioned at the start of the emoji.
The emoji deleted three persons and remains a person while deleting 

### Versions
Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (4 months ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4

### PR DESCRIPTION
**Pull request by justinmc**
The cursor was being misplaced after adding certain extended grapheme clusters, and this PR fixes it.

The problem seems to have been errors in the boundary detection of extended grapheme clusters in TextPainter, which does not use the Characters package due to potential performance issues.

*The behavior before this PR.*

### Issues

Closes https://github.com/flutter/flutter/issues/76850

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 7 untriaged digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/77085

**Comment by skia-gold** [comment]
Gold has detected about 2 untriaged digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/77085

**Comment by justinmc** [comment]
I hoped that I could fix this quickly, but I don't understand why tests are failing due to my change... I'll come back to this.

**Comment by skia-gold** [comment]
Gold has detected about 2 untriaged digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/77085

**Comment by skia-gold** [comment]
Gold has detected about 5 untriaged digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/77085

**Pull request closed without merging**
