### PR TITLE
Add RawKeyboardListener

### LINKED ISSUE #787: Route hardware keyboard key events (when there's no software keyboard) to whichever widget has focus
Key events should be on par with pointer events imo.

### PR DESCRIPTION
**Pull request by abarth**
RawKeyboardListener makes it easier to listen for raw keyboard events.

Fixes #787

### CODE REVIEW

**Comment by abarth** [comment]
@collinjackson @jason-simmons

**Comment by Hixie** [comment]
lgtm, but presumably medium term we want to hook this into the `Focus` world.

**Comment by collinjackson** [comment]
lgtm

**Comment by abarth** [comment]
> lgtm, but presumably medium term we want to hook this into the Focus world.

Yeah, I should make the example use focus.  The intent is that you pass `Focus.at(context)` as the `focused` argument.

**Comment by Hixie** [comment]
Why not just have that be built-in?

**Comment by abarth** [comment]
> Why not just have that be built-in?

The problem is you have to pick an exact widget to be focused.  For example, in the IME part of the system, `Input` is the widget that's focused rather than `RawEditableLine`.  Similar to `RawKeyboardListener`, `RawEditableLine` takes a `focused` parameter that tells it whether to blink the cursor.

Suppose you were to build a gamepad widget out of `RawKeyboardListener`, you'd want the gamepad widget itself to be the one that's focused (perhaps drawing a focus ring or a lighting up in some color) rather than the underlying `RawKeyboardListener`.

This all points a composability problem with focus that we might need to solve somehow.

**Comment by Hixie** [comment]
Ah yeah that makes sense.

**Pull request merged**
