### PR TITLE
[flutter_tools] use win32 file API to read file attributes

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

(WIP because I haven't added automated tests yet).

The dart:io File types do not expose whether a windows File has the hidden attribute set, and Directory.listSync() returns all files whether or not they are hidden.

on Linux/macOS we can simply check for a leading `.`. But on windows, we need to use ffi to call a win32 API.

This is needed to solve http://github.com/flutter/flutter/issues/47366

### CODE REVIEW

**Comment by zanderso** [comment]
I'm reluctant to introduce a use of `dart:ffi` since we don't have one yet, and I'm not sure we understand all of the implications, yet. Can you use the `attrib` command instead? It looks like it can fetch attributes for a whole directory at once: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/attrib

**Comment by jonahwilliams** [comment]
`attrib` doesn't list files that are hidden. We could take advantage of that by diffing the listing from attrib and then from Directory.listSync(), but that seems like it would have its own issues too

**Comment by jonahwilliams** [comment]
There is also https://github.com/flutter/flutter/issues/46696, though I don't fully understand whether this would make that worse/better

**Comment by zanderso** [comment]
At least on my build of Windows 10 (1909), `attrib` does list hidden files:
```
PS C:\Workspace\hidden_file_test> attrib C:\Workspace\hidden_file_test\*
A   H                C:\Workspace\hidden_file_test\hidden_file.txt
```

(I made a file, opened its properties in explorer, and ticked the 'Hidden' ticky-box.)

**Comment by jonahwilliams** [comment]
Hmm, I've got a setup with a hidden directory that isn't listing it. Maybe that doesn't matter in this case

**Comment by zanderso** [comment]
The `/S` switch seems to help:
```
PS C:\Workspace\hidden_file_test> attrib C:\Workspace\hidden_file_test\* /S
A   H                C:\Workspace\hidden_file_test\hidden_directory\hidden_file.txt
A   H                C:\Workspace\hidden_file_test\hidden_file.txt
```
Though I guess it doesn't tell you that the directory is hidden, just whether files in it are hidden.

**Comment by jonahwilliams** [comment]
Not working on this right now

**Pull request closed without merging**
