### PR TITLE
AnimatedPositioned

### PR DESCRIPTION
**Pull request by Hixie**
See the three individual commits for specifics.

### CODE REVIEW

**Comment by Hixie** [comment]
Reviewing this will be easiest by looking at the three commits, because I move some files around and do a bunch of refactoring here.

**Comment by Hixie** [comment]
FIxes https://github.com/flutter/flutter/issues/957

**Comment by Hixie** [comment]
Ok I think I fixed the mess with the commits. Sorry about that. Dealing with the other comments now.

**Comment by Hixie** [comment]
@abarth I added a test, but I think the code already did what you want it to do, because when you set a variable targetValue to null the variable itself gets set to null immediately, we don't transition to null.

I also replaced the constructor tear-offs with lambdas wrapping constructors for now.

PTAL, thanks!

**Comment by abarth** [comment]
Great!  LGTM

**Pull request merged**
