### PR TITLE
Cleanup DevFS support and add unit test

### PR DESCRIPTION
**Pull request by johnmccutchan**
- [x] Move devfs support into separate file
- [x] Adapt to new interface
- [x] Add unit test

### CODE REVIEW

**Comment by johnmccutchan** [comment]
@devoncarew @sethladd

**Comment by johnmccutchan** [comment]
Mostly done but still some WIP as I need to add more tests and fix a performance problem.

**Comment by devoncarew** [comment]
@johnmccutchan, can you merge to master - I committed changes in this area this morning - and reformat. It looks like you have some odd indents going on in this files. I'll review once you're ready.

**Comment by johnmccutchan** [comment]
I'm going to close this pull request. I ended up getting hot reloading working on Android devices. Will send a more complete pull request tomorrow.

**Pull request closed without merging**
