### PR TITLE
fix(cupertinoDatePicker): do not display previous day when minimumDat…

### LINKED ISSUE #72932: [CupertinoDatePicker] date picker displays out of range date edge case
## Steps to Reproduce

1. Add a `CupertinoDatePicker` with `minimumDate` set for **some date at midnight**.
1. Run the app as usual: `flutter run`

**Expected results:**
The `date` column first available date is the `minimumDate` specified date.

**Actual results:** 
The `date` column first available date is the day before `minimumDate` specified date. However, when selecting that date, all time pickers are disabled (hour, minute and meridiem).

### Additional resources
Minimal code to reproduce the  bug and a sample available at
https://github.com/davidlj95/bug-cupertino-date-picker-date-column

<details>
  <summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-GB)
    • Flutter version 1.22.4 at /Users/yc00143/app/flutter/git
    • Framework revision 1aafb3a8b9 (6 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/yc00143/Library/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/yc00143/Library/Android/Sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 12 (mobile) • 651FB4DA-53B3-4315-888D-504F1E0D081A • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 2 categories.

```

</details>

### PR DESCRIPTION
**Pull request by davidlj95**
## Description

Fixes the edge case for a `CupertinoDatePicker` when the `minimumDate` is a date set at midnight. The item on the column date for the previous date should not be displayed though it is now as of the current range comparison.

## Related Issues

Fixes #72932 

## Tests

I added the following tests:

https://github.com/flutter/flutter/pull/72933/files#diff-9b38c44527149e714db603d6eb23dea06ed25db5716f0b304d53de0ef3b60070R936

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by LongCatIsLooong** [comment]
Thanks for the fix! Could you add a test to make sure it does not regress in the future? The instructions can be found [here](https://github.com/flutter/flutter/wiki/Running-and-writing-tests). See also here: https://github.com/flutter/flutter/blob/5f46931a8f94a4228c16edd5beae96a82bf15bdf/packages/flutter/test/cupertino/date_picker_test.dart#L937

**Comment by davidlj95** [comment]
> Thanks for the fix! Could you add a test to make sure it does not regress in the future? The instructions can be found [here](https://github.com/flutter/flutter/wiki/Running-and-writing-tests). See also here:
> 
> https://github.com/flutter/flutter/blob/5f46931a8f94a4228c16edd5beae96a82bf15bdf/packages/flutter/test/cupertino/date_picker_test.dart#L937

Sure @LongCatIsLooong ! Just added a regression test 👍  Sorry for the delay, was on Christmas holidays 🎄 🎅 

Thanks 👍

**Comment by LongCatIsLooong** [comment]
Could you sync this branch to the latest master and see if that fixes the CI failures?

**Comment by davidlj95** [comment]
> Could you sync this branch to the latest master and see if that fixes the CI failures?

Sure, done 👍

**Review by LongCatIsLooong — APPROVED** [review]
LGTM. Thanks for fixing this!

**Pull request merged**
