### PR TITLE
[flutter_tools] remove UWP tooling

### PR DESCRIPTION
**Pull request by jonahwilliams**
Work towards https://github.com/flutter/flutter/issues/102172

### CODE REVIEW

**Review by cbracken — APPROVED** [review]
This LGTM but please hold off landing till we've checked in with @zanderso.

**Comment by cbracken** [comment]
@jonahwilliams

You're all clear kid, now let's blow this thing and go home!

**Comment by jonahwilliams** [comment]
https://user-images.githubusercontent.com/8975114/165365776-84eea9dc-31f4-4072-a16b-57e49ed6eca6.mp4

**Comment by jonahwilliams** [comment]
image

**Pull request merged**
