### PR TITLE
_SearchBarState should dispose FocusNode, if it created it.

### PR DESCRIPTION
**Pull request by polina-c**

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by mateusfccp** [comment]
I think this may not be well solved.

We don't have `didUpdateWidget` implemented for the state. This means that if the widget starts with a null `FocusNode` and then is updated to have a non-null `FocusNode` and disposed, the `dispose` method will check if `widget.focusNode == null`, which will return false and `_focusNode` will not be disposed.

In this same case, when the widget is updated, `_focusNode` will still be the `FocusNode` that has been created in the `initState`.

I think a more appropriate implementation would be something like this:

```dart
  @override
  void initState() {
    super.initState();
    // ...
    _focusNode = widget.focusNode ?? FocusNode();
  }

  @override
  void didUpdateWidget(TradingChart oldWidget) {
    super.didUpdateWidget(oldWidget);

    if (widget.focusNode != oldWidget.focusNode) {
      if (oldWidget.focusNode == null) _focusNode.dispose();
      _focusNode = widget.focusNode ?? FocusNode();
    }
  }

  @override
  void dispose() {
    // ...
    if (widget.focusNode == null) {
      _focusNode.dispose();
    }
    super.dispose();
  }
```

WDYT?

**Comment by chunhtai** [comment]
@mateusfccp 
You are right, this doesn't take into account that if the widget.focusNode changes. Since you already have the fix, can you file a pr with a test? you can pin me for review

**Comment by mateusfccp** [comment]
@chunhtai Sure, as soon as I have some time!

**Comment by mateusfccp** [comment]
@chunhtai It seems that this issue has already been fixed in a later PR.

**Pull request merged**
