### PR TITLE
[flutter roll] Revert "Added ButtonStyle.foregroundBuilder and ButtonStyle.backgroundBuilder"

### PR DESCRIPTION
**Pull request by XilaiZhang**
temporarily creating a revert of flutter/flutter#141818

context: b/323399158

Seems like button backgrounds are missing in a number of scubas

### CODE REVIEW

**Comment by HansMuller** [comment]
https://github.com/flutter/flutter/pull/141818 introduced an incompatibliity - before, if TextButton.styleFrom only specified backgrondColor, then _all_ states would get that background color. Now, disabled buttons get their default (transparent) background instead. Applies to the other button classes too.

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by XilaiZhang** [comment]
Looks like tree is red now. Will try using the 'revert' label instead of 'autosubmit' label to see if we can surpass the tree status check

**Comment by XilaiZhang** [comment]
Cool, the 'revert' label merged https://github.com/flutter/flutter/pull/142748 and surpassed the checks.

Thanks a lot for inspecting!

**Pull request closed without merging**
