### PR TITLE
fix typo?

### PR DESCRIPTION
**Pull request by aoisensi**
## Description

fixed comment issue

### CODE REVIEW

**Comment by chunhtai** [comment]
Hi @aoisensi, thanks for contribution! It looks like you haven't signed the CLA, it is required to merge this pr. Thank you!

**Comment by goderbauer** [comment]
@aoisensi Can you sign the CLA as described in https://github.com/flutter/flutter/pull/52921#issuecomment-601494277? Once you do that, we can merge this PR.

**Comment by aoisensi** [comment]
@googlebot I signed it!

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
