### PR TITLE
New dwds

### PR DESCRIPTION
**Pull request by alan-knight**
## Description

This updates flutter_tool to use dwds 0.7.0, which has a breaking change in its creation API. It passes an asset handler which replaces several other parameters.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [not required for googlers] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by alan-knight** [comment]
This fails because I manually updated the pubspec, but shows the changes necessary to use a 0.7.x dwds. We also expect to have a 0.7.1 with a few more fixes for Flutter issues very shortly.

**Comment by jonahwilliams** [comment]
Sounds good - you can update the pubspecs for this PR with `flutter update-packages --force-upgrade` FWIW

**Comment by alan-knight** [comment]
OK. I had been reluctant to do that for fear of coupling it to other things, but did it now.

**Comment by jonahwilliams** [comment]
Ahh I see you ended up with the build_runner roll too. Could you update these lines:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_runner/build_script.dart#L219

To remove the skipPlatformCheckPackages and replace it with `skipPlatformCheck: true`?

If not, I can take over this PR to finish it

**Comment by alan-knight** [comment]
Added the build_runner fix.

**Comment by jonahwilliams** [comment]
Sorry, looks like there is one more at packages/flutter_tools/lib/src/build_runner/build_script.dart:245

**Comment by DanTup** [comment]
🎉

Screenshot 2019-10-07 at 10 20 54 am

**Comment by jonahwilliams** [comment]
Looks like we managed to roll this in with https://github.com/flutter/flutter/pull/41936

**Comment by alan-knight** [comment]
OK.

**Pull request closed without merging**
