### PR TITLE
Enable lint unnecessary_statements. Codebase is compliant.

### PR DESCRIPTION
**Pull request by MichaelRFairhurst**
see https://github.com/dart-lang/sdk/issues/57760 and customer tweet https://twitter.com/pavel_ismailov/status/1004641813548892161

### CODE REVIEW

**Comment by pq** [comment]
FWIW: I think you want to enable this here too

https://github.com/flutter/plugins/blob/master/analysis_options.yaml

as per the advice here:

https://github.com/flutter/flutter/blob/1393c730773e8764f2cbfc1cd569d4ab354e86dd/analysis_options.yaml#L19-L20

**Comment by MichaelRFairhurst** [comment]
thanks @pq!

**Comment by Hixie** [comment]
is this turning it on for us or for our users? or both?

**Comment by devoncarew** [comment]
This will do it for the flutter repo itself, which seems useful. You'll also want to enable it in `packages/flutter/lib/analysis_options_user.yaml`, which will turn it on for users.

**Comment by MichaelRFairhurst** [comment]
Rebasing to fix the build?

**Review by devoncarew — APPROVED** [review]
From a CI perspective your PR is good. The Flutter device lab also runs post-commit checks and writes the status back into open PRs. Those device lab tests are currently failing (and, you shouldn't land a PR when they're red except to fix the build).

I would periodically refresh this PR until the build is green again.

**Comment by devoncarew** [comment]
It's green - merging.

**Pull request merged**
