### PR TITLE
[O] Fix a race condition in vmservice_test.dart

### LINKED ISSUE #19273: flutter_tester hangs on linux workstation
On my Linux workstation, running flutter tester just hangs and doesn't find a flutter view to run on.

Repro:

1. `flutter create mytest`
1. `cd mytest`
1. `flutter run -d flutter-tester --verbose`
1. fails with a stack trace and `Error connecting to the service protocol: Exception: No Flutter view is available`

The same thing works fine on my mac, and flutter tester tests seem to run fine on the bots.

I have tried:
1. killing all flutter_tester processes (there were 10 running! I think it's not dying properly either).
1. rebooting my machine
1. nuking my cache directory and git pulling from master again.
1. running flutter_tester manually directly.  It runs and just sits there not reporting any errors.

I'm using master branch HEAD at 36e16e754433a1357e7f49af8c1221d70b67bc79.

Here's the entire output:
```
(home/gspencer:master) -- test_reload > flutter run -d flutter-tester --verbose
[  +42 ms] [/usr/local/google/home/gspencer/code/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +40 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: no upstream configured for branch 'master'
[        ] [/usr/local/google/home/gspencer/code/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] [/usr/local/google/home/gspencer/code/flutter/] git log -n 1 --pretty=format:%H
[   +7 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 36e16e754433a1357e7f49af8c1221d70b67bc79
[        ] [/usr/local/google/home/gspencer/code/flutter/] git log -n 1 --pretty=format:%ar
[   +6 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 68 minutes ago
[   +1 ms] [/usr/local/google/home/gspencer/code/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +25 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v0.5.6-97-g36e16e754
[ +102 ms] /usr/local/google/home/gspencer/Android/Sdk/platform-tools/adb devices -l
[  +11 ms] Exit code 0 from: /usr/local/google/home/gspencer/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           84B7N15A07007628       device usb:2-2.3 product:angler model:Nexus_6P device:angler transport_id:1
[ +210 ms] Found plugin shared_preferences at /usr/local/google/home/gspencer/code/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.2/
[ +792 ms] Launching lib/main.dart on Flutter test device in debug mode...
[ +389 ms] DependencyChecker: nothing is modified after 2018-07-11 10:44:23.408.
[ +208 ms] Skipping kernel compilation. Fingerprint match.
[ +285 ms] Building bundle
[        ] Writing asset files to build/flutter_assets
[  +66 ms] Wrote build/flutter_assets
[        ] /usr/local/google/home/gspencer/code/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester --run-forever --non-interactive --enable-dart-profiling --packages=.packages --flutter-assets-dir=build/flutter_assets build/app.dill
[ +243 ms] Observatory URL on device: http://127.0.0.1:34079/
[   +6 ms] Connecting to service protocol: http://127.0.0.1:34079/
[ +195 ms] Successfully connected to service protocol: http://127.0.0.1:34079/
[   +3 ms] getVM: {}
[  +11 ms] Waiting for Flutter view
[ +187 ms] Do not know weight for: TeXGyreSchola (BoldItalic) 
[ +813 ms] Waiting for Flutter view
[+1004 ms] Waiting for Flutter view
[+1000 ms] Waiting for Flutter view
[+1000 ms] Waiting for Flutter view
[+1002 ms] No Flutter views available on Flutter test device
[   +6 ms] Error connecting to the service protocol: Exception: No Flutter view is available
[  +21 ms] "flutter run" took 7,512ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:406)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:347)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:77)
#4      _rootRunUnary (dart:async/zone.dart:1134)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638)
#8      Future._propagateToListeners (dart:async/future_impl.dart:667)
#9      Future._complete (dart:async/future_impl.dart:472)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/dart:async/async_patch.dart:28)
#12     _completeOnAsyncReturn (dart:async-patch/dart:async/async_patch.dart:292)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart:211)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:77)
#15     _rootRunUnary (dart:async/zone.dart:1134)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:638)
#19     Future._propagateToListeners (dart:async/future_impl.dart:667)
#20     Future._complete (dart:async/future_impl.dart:472)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:33)
#23     _rootRun (dart:async/zone.dart:1126)
#24     _CustomZone.run (dart:async/zone.dart:1023)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#28     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

### PR DESCRIPTION
**Pull request by Hixie**
Fixes https://github.com/flutter/flutter/issues/19273

### CODE REVIEW

**Comment by Hixie** [comment]
cc @tvolkert @aam this is the reland of the patch from before.

**Review by aam — APPROVED** [review]

**Comment by tvolkert** [comment]
Tests are failing

**Comment by Hixie** [comment]
Oops, merge error.

Thanks. Will land on green.

**Comment by dnfield** [comment]
Can we land this to try to fix the build?  Tool test linux is failing and this is one possible reason why.

**Comment by aam** [comment]
> Can we land this to try to fix the build? Tool test linux is failing and this is one possible reason why.

I don't think @Hixie will object if you land this for him.

**Comment by tvolkert** [comment]
If you think it'll fix the build, then it makes sense to merge on red.

**Pull request merged**
