### PR TITLE
[flutter_test] accessibility inspector handles merged nodes

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

In order to better guess the font style/size/position, the contrast checker will attempt to look for an element matching the semantics it found. Previously, if this was not found in the element tree it was skipped. Unfortunately, this behavior did not play nicely with merge semantics since there would not be an element corresponding to the merged label.

Instead now fail if there are zero matches, allow more than one match, and search for substrings instead of exact matches.

This isn't perfect, and could probably be refined a bit by taking average font size across matching within some bounding box.

### CODE REVIEW

**Review by pennzht — COMMENTED** [review]
Hi Jonah,

Thank you very much for your help on this issue!

I added a new test, which places some **black texts on white background**. It should pass, but it also failed.
The code can be found here — https://github.com/pennzht/flutter/commit/f8cc0f608d43b0e6eca133f588829041f6be211b — and the output is posted below (some irrelevant paths are hidden).
Could you please take a look?

Also, is there a way to `find` all text widgets that **contribute to** a semantics node? I think that would make the test logic more straightforward, and avoid some uncommon edge cases (such as, maybe, a text widget outside the semantics node with the same label?).

Looking forward to hearing from you!

Regards,
Tianguang



```
00:02 +1: text contrast guideline black text on white background with merge semantics                                
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: Text contrast should follow WCAG guidelines
  Actual: <Instance of 'WidgetTester'>
   Which: Unable to find element matching semantic node: SemanticsData(Rect.fromLTRB(0.0, 0.0,
238.0, 600.0), [1.0,0.0,0.0,281.0; 0.0,1.0,0.0,0.0; 0.0,0.0,1.0,0.0; 0.0,0.0,0.0,1.0], label: "I am
text one\nAnd I am text two", textDirection: ltr)

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/frontend/expect.dart:153:30)
#1      _expect.<anonymous closure> (package:test_api/src/frontend/expect.dart:127:9)
#13     _MatchesAccessibilityGuideline.matchAsync (package:flutter_test/src/matchers.dart)
<asynchronous suspension>
#14     _expect (package:test_api/src/frontend/expect.dart:116:26)
#15     expectLater (package:test_api/src/frontend/expect.dart:75:5)
#16     expectLater (package:flutter_test/src/widget_tester.dart:385:10)
#17     main.<anonymous closure>.<anonymous closure> ({{{path to flutter repository, hidden}}}/packages/flutter_test/test/accessibility_test.dart:64:13)
<asynchronous suspension>
#18     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:140:29)
<asynchronous suspension>
#19     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:699:19)
<asynchronous suspension>
#22     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:679:14)
#23     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1079:24)
#29     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1076:15)
#30     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:133:24)
#31     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:27)
<asynchronous suspension>
#32     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:242:15)
#37     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:239:5)
#38     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:33)
#43     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:13)
#44     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:392:25)
#58     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#59     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
(elided 39 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)

The test description was:
  black text on white background with merge semantics
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +1 -1: text contrast guideline black text on white background with merge semantics [E]                         
  Test failed. See exception logs above.
  The test description was: black text on white background with merge semantics
  
00:03 +22 -1: Some tests failed.                                                                                     
```

**Comment by goderbauer** [comment]
Looks like Cirrus is unhappy on this change, can you take a look?

**Comment by jonahwilliams** [comment]
Updated with changes to currently failing gallery contrast tests

**Comment by pennzht** [comment]
Hi Jonah,

Thank you very much for your help!

I tested this PR with a few more tests: see https://github.com/pennzht/flutter/blob/verify-contrast-checker-3/packages/flutter_test/test/accessibility_test.dart (branch `pennzht:verify-contrast-checker-3`), but results are quite unexpected:

- white text on white
  * Correct: Does not meet guideline
- white and black text on white
  * Correct: Does not meet guideline
- black and white text on white
  * **Incorrect:** Should not meet guideline, but meets
- irrelevant text
  * **Incorrect:** Should meet guideline, but does not meet
- irrelevant text - passing
  * Correct: Meets guideline
- irrelevant button
  * **Incorrect:** Should meet guideline, but does not meet
- irrelevant button - passing
  * Correct: Meets guideline
- black and white text, without MergeSemantics
  * **Incorrect:** Should not meet guideline, but meets

These tests are found near the end of [this file](https://github.com/pennzht/flutter/blob/verify-contrast-checker-3/packages/flutter_test/test/accessibility_test.dart).

Especially, in the tests "irrelevant text" vs. "irrelevant text - passing" and "irrelevant button" vs. "irrelevant button - passing", **changing the string of a text from 'One' to 'Two' passes the test,** while not changing any colors.

I think this is because…
1. …we are using `elements.first` to see which element to test, instead of checking the **actual** text widget that contributed to semantics; and
2. …we are globally searching for widgets with a text that matches the label data, instead of only looking for children of the semantics node widget(?).

Again, I suggest that we find out which widgets **actually** contributed to semantics, and run color contrast tests only for these widgets.

What do you think?

Regards,
Tianguang

**Comment by jonahwilliams** [comment]
The new behavior ends up breaking some tests accidentally. I'm looking at making it an opt-in for easier landing

**Comment by pennzht** [comment]
@jonahwilliams 

I think this issue is really hard to fix.

I submitted an issue #50376 and assigned to myself — if you want to, you can add yourself too.
I'll continue analyzing it next week, and try to give a solution.

Thank you very much for your help — and have a great weekend!

Regards,
Tianguang

**Comment by goderbauer** [comment]
(PR triage): Is there value in keeping this PR open until we have figured out a solution? Or should we close it for the time beeing?

**Comment by jonahwilliams** [comment]
No, closing for now

**Pull request closed without merging**
