### PR TITLE
flutter tools hook support

### PR DESCRIPTION
**Pull request by kangwang1988**
This pr enable developers to add some customized hooks point into flutter tools. So that they can do some things before/after a flutter command, by specify a hooks.yaml under the root directory of their flutter project without modifying the flutter_tools.

A typical hooks.yaml is given below:
```
# Use the analysis options settings from the top level of the repo (not
# the ones from above, which include the `public_member_api_docs` rule).

commands:
  doctor:
    hook:
      before: 
        executable: "perl"
        argument: "flutter_tools_hook.pl"
      after: 
        executable: "/bin/sh"
        argument: "flutter_tools_hook.sh"
  build:
    bundle:
      hook:
        after: 
          executable: "python"
          argument: "flutter_tools_hook_bundle.py"
    ios:
      hook:
        before: 
          executable: "python"
          argument: "flutter_tools_hook.py"
        after: 
          executable: "ruby"
          argument: "flutter_tools_hook.rb"
```

For example, 'python flutter_tools_hook_bundle.py "build bundle --target-platform=ios --target=lib/main.dart --release --depfile=build/snapshot_blob.bin.d --asset-dir=/Users/kylewong/Codes/Flutter/alibaba-flutter/flutter/examples/hello_world/ios/Flutter/App.framework/flutter_assets --precompiled" will be executed when flutter build bundle command is executed.

## Tests

I added the following tests:
packages/flutter_tools/test/hooks_test.dart
It includes test logic for hooks.yaml parser, hooks execution logic.

## Breaking Change
- [ ] No, this is *not* a breaking change.

### CODE REVIEW

**Review by jonahwilliams — CHANGES_REQUESTED** [review]
Why does this need to implemented within the flutter tool? It seems like a lot of complexity to support something that could ultimately be accomplished with a bash/batch script that wrapped the commands.

**Comment by kangwang1988** [comment]
@jonahwilliams 
This pr originally comes from a case that we want to do some dill transformation after it's generated by "flutter build bundle" command. 
flutter build bundle command is often wrapped in flutter build apk, flutter build ios,etc, if we want to wrap it using a shell or some scripts, we need to modify the xcode_backend.sh or flutter.gradle, this kind of injection would make things more complex.
Besides, now, different from gradle/cocoapods, flutter_tools don't offer hooks so that developers can do this kind of stuff before or after a flutter command. A natively supported hook mechanism would give developers freedom to do their own job without injecting the flutter_tools.

**Comment by kangwang1988** [comment]
I developed a aop framework aspectd available at https://github.com/alibaba-flutter/aspectd
Its core logic is to do dill transformation after a dill file is generated.
However, I want the dill transformation is called automatically if aop annotation is enabled, for a developer who want to use the aop, they can still use `flutter build ios` `flutter build apk`, `flutter run --debug` `flutter run --release`, without changing their way to use the flutter command.
So aspectd has to modify the flutter_tools, so that the dill transformation logic is executed after a dill file is generated, which would request more inner knowledge about the flutter_tools and made the injection logic vulnerable to changes.
Aspectd tries to solve the aop problem without invasion, however, the logic of flutter_tools still made it necessary to do invasion to flutter build process.

In this pr, i not only want to solve the aspectd invasion problem, but also provides a more general way to give developers chance to do some job they want.

**Comment by kangwang1988** [comment]
image

We also have hook logic as above.
Which brings some differences from the github flutter repo and makes it hard to maintain.

**Comment by kangwang1988** [comment]
@gspencergoog 
What do you think is the best way to do provide hook support when using flutter command?

**Comment by kangwang1988** [comment]
@jason-simmons 
Different from gradle, flutter_tools provides no ways to do the hook related job when needed, that's what I'm trying to solve.

**Comment by jonahwilliams** [comment]
@kangwang1988 It looks a bit like you're using the aspectd package to plugin into the CFE. It would be great to start with a detailed issue describing a bit more how this works and what sort of transformations you are making. I _think_ the CFE might have some APIs to do this sort of thing. We could cc the dart team and get a discussion going

**Comment by kangwang1988** [comment]
Close this issue as I think we are on the right way to have a better solution to resolve my problem, see:https://github.com/flutter/flutter/issues/36738 for more.

**Pull request closed without merging**
