### PR TITLE
Flutter Web Loading Indicator

### LINKED ISSUE #80987: [Flutter Tools] Should display a loading indicator / splash screen for web applications
While a Flutter Web application is loading the window will remain blank. This is especially problematic in slow environments as the user has no indication that something is happening for an extended period of time. We should display a loading / splash screen similar to what `package:test` provides.

cc @jonahwilliams @DanTup

### PR DESCRIPTION
**Pull request by grouma**
Decided to throw a quick PR together to close https://github.com/flutter/flutter/issues/80987

We may want a better graphic or animation but this should suffice for now. I chose the Flutter colors and a material-esque spinner:

capture

Note converting the video to a gif has slowed down the animation. It's generally smooth and rolls faster.

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
So we don't have a good way to do a real integration test of this, maybe just add to the bootstrap unit tests with a contains('flutter-loader') and a description of what this is doing? At least then if someone copy pastes this around wrong that could fail

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by DanTup** [comment]
Neat! Does `dart-app-ready` always fire, or only if you have the extension? (If the latter, is there any concern with the stylesheet not being removed?).

It's not clear from the screenshot - does the spinner vanish once the app is loaded, then you click the debug button, or does the spinner remain until you click the debug button?

**Comment by grouma** [comment]
> Neat! Does `dart-app-ready` always fire, or only if you have the extension? (If the latter, is there any concern with the stylesheet not being removed?).

It always fires as a part of `package:dwds`. The extension listens for this as well.

> It's not clear from the screenshot - does the spinner vanish once the app is loaded, then you click the debug button, or does the spinner remain until you click the debug button?

I'm not clicking the debug icon at all. It removes itself when the injected client is ready and the initial connection is established: https://github.com/dart-lang/webdev/blob/49dc708342f7570a790341cf896cff05590d0a94/dwds/web/client.dart#L132

**Comment by Leffe108** [comment]
It is great that Flutter now has a default loader on web. 👍🎉 And looking at the source, one can add a style `.flutter-loader { display: none; }` to disable it if you already have your own custom loader that you want to keep.

**Comment by Sammius** [comment]
My God, how to turn it off ???


This is of course great, maybe someone needs it. But my opinion is that you need to add such things by some key who will need it.
In the end, for whom it was important already added a couple of lines of code to  `web/index.html`.

**Comment by Sammius** [comment]
@Leffe108 add where: `.flutter-loader {display: none; }`? Adding to `web/index.html` doesn't work.

**Comment by jmarkham** [comment]
The default for this highly questionable PR needs to be 'off'.

**Comment by jmarkham** [comment]
> @Leffe108 add where: `.flutter-loader {display: none; }`? Adding to `web/index.html` doesn't work.

In index.html:

`<style>
    ....
    .flutter-loader {
      display: none !important;
    }
   ....
 </style>`

**Comment by jmarkham** [comment]
> @Leffe108 add where: `.flutter-loader {display: none; }`? Adding to `web/index.html` doesn't work.

In index.html:

      <style>
           ...
          .flutter-loader {
            display: none !important;
          }
          ...
      </style>

**Comment by jonahwilliams** [comment]
This is debug mode only functionality. it will not show up on a release website unless you add it yourself.

**Comment by wilpar** [comment]
Can this be disabled? I've already integrated a spinner into my index.html and while I know it doesn't show up on release builds, it's still distracting.

If not, IMO it would make sense to hook it into debugShowCheckedModeBanner

**Comment by grouma** [comment]
> Can this be disabled? I've already integrated a spinner into my index.html and while I know it doesn't show up on release builds, it's still distracting.
> 
> If not, IMO it would make sense to hook it into debugShowCheckedModeBanner

See the comment above by @Leffe108. Not sure why it was marked as off topic. 

> It is great that Flutter now has a default loader on web. 👍🎉 And looking at the source, one can add a style `.flutter-loader { display: none; }` to disable it if you already have your own custom loader that you want to keep. And this PR also document how you in JS land can listen for when the app has loaded to remove your custom loader. 😀

**Comment by vistaco** [comment]
> > Neat! Does `dart-app-ready` always fire, or only if you have the extension? (If the latter, is there any concern with the stylesheet not being removed?).
> 
> It always fires as a part of `package:dwds`. The extension listens for this as well.
> 
> > It's not clear from the screenshot - does the spinner vanish once the app is loaded, then you click the debug button, or does the spinner remain until you click the debug button?
> 
> I'm not clicking the debug icon at all. It removes itself when the injected client is ready and the initial connection is established: https://github.com/dart-lang/webdev/blob/49dc708342f7570a790341cf896cff05590d0a94/dwds/web/client.dart#L132

just use `flutter-first-frame` instead `dart-app-ready`. it's work for me in flutter 2.5.3.

`window.addEventListener("flutter-first-frame",function(){ 
      console.log('flutter app loaded.');
});`

**Pull request merged**
