### PR TITLE
Update tokens to 4.0.0

### PR DESCRIPTION
**Pull request by QuncCccccc**
This PR is to 
* Update the Material Design tokens to 4.0.0

Since the last token update(#145356), only `Slider` tokens have been updated. The M3 `Slider` has significant visual changes, compared to the original M3 Slider, so a separate PR would be needed. I commented out `SliderTemplate` and added a TODO when we are ready to add new widgets again.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by Piinks** [comment]
FYI @TahaTesser regarding the slider changes

**Review by Piinks — APPROVED** [review]
LGTM

**Review by guidezpl — APPROVED** [review]

**Comment by TahaTesser** [comment]
> FYI @TahaTesser regarding the slider changes

Ohhh... I was using hard coded values with TODOs to use tokens later in https://github.com/flutter/flutter/pull/147783.

**Comment by TahaTesser** [comment]
> > > FYI @TahaTesser regarding the slider changes
> > 
> > 
> > Ohhh... I was using hard coded values with TODOs to use tokens later in #147783.
> 
> I don't know we have #147783🤩 Then looks like we can just remove this todo once your PR is ready! Thanks!

This PR removes th tokens for current M3 detaults so I will update https://github.com/flutter/flutter/pull/147783 to use new the tokens and restore delete values as we plan to keep the current M3 shapes under the new flag.

**Pull request merged**
