### PR TITLE
Revert "Upgrade the Gradle script to Android plugin version 3.3.0 (#26913)"

### PR DESCRIPTION
**Pull request by jason-simmons**
This reverts commit 30f33d6c7d7581e61269da8778fae59882f081d8.

### CODE REVIEW

**Comment by jason-simmons** [comment]
The change of the main script to 3.3.0 needs to be staged along with updates to other users like the Flutter plugins

**Review by mklim — APPROVED** [review]
LGTM. Thanks!

**Review by cbracken — APPROVED** [review]

**Comment by dnfield** [comment]
Can this be relanded?  I don't fully recall the problem it caused.

**Comment by bradyt** [comment]
This issue is noisy in logs, for example,

```
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: Called from: ~/opt/flutter/packages/flutter_tools/gradle/flutter.gradle:422
WARNING: Debugging obsolete API calls can take time during configuration. It's recommended to not keep it on at all times.
Affected Modules: app
```

 Can someone fix this?

**Pull request merged**
