### PR TITLE
Support Float32Lists in StandardMessageCodec (#72613)

### PR DESCRIPTION
**Pull request by fuzzybinary**
This adds Float32List support to StandardMessageCodec, and should probably land after flutter/engine#26386 adds support for the engine. 

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Note to reviewers: please see my comments at https://github.com/flutter/engine/pull/26386 before landing this, since I don't think this is actually ready to go forward.

**Comment by fuzzybinary** [comment]
With flutter/engine#26537 and flutter/engine#26472 in this is probably ready for review now yes @stuartmorgan ?

**Comment by stuartmorgan** [comment]
@chinmaygarde should probably review this since he reviewed the other side of the codec.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by fuzzybinary** [comment]
@goderbauer I've rebased on master to fix the tests and get flutter-gold to re-run. Can I get a re-review?

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
