### PR TITLE
Bugfix: Add platformBrightness to TestWindow.

### PR DESCRIPTION
**Pull request by matthew-carroll**
Bugfix: Add platformBrightness to TestWindow.

Cause of bug: I merged the following

1. TestWindow implementation in framework that implements Window

2. Added platformBrightness to Window definition in engine, but forgot to add corresponding implementations to TestWindow

This broke the framework because TestWindow no longer fully implemented Window.

This PR adds the necessary Window implementations to TestWindow.

This PR also rolls the engine with the following commits:
git log 93aa035dd46999353d8f7fe4be61e6599c794b4b..cc27cafb840f6fd57b86a36a3e7ed5461575f10a --no-merges --oneline
cc27cafb8 Implemented Dark Mode for Android (#25525) (flutter/engine#7488)
9c05cbcfb Roll src/third_party/dart b53dceadaa..5823be65af (5 commits) 5823be65af [vm/compiler] Continued graph checker development (reland) 8231cdb7a3 [gardening] Update status for issue 35854 db7f848632 [vm] Remove dead BigInt code. 35ab1755f4 Support more type propagation for code-as-ui features 569ee07f91 [vm] Cleanup class finalization checks
ec5e6f6ef Ensure dart2js and kernel worker snapshots are copied out of gen dir (flutter/engine#7692)
8b5fa65c4 Roll src/third_party/skia 50ea3c06b80f..2d35a1c87553 (6 commits) (flutter/engine#7693)

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by matthew-carroll** [comment]
Related question for @Hixie and @goderbauer - how do we generally handle interfaces and dependencies that cross the framework/engine barrier?  I don't think our automation even has a way to verify such changes, does it? For example, in this case I think what happened is that I merged in engine changes that broke the framework, but the framework breakage was not caught by CI...

**Comment by goderbauer** [comment]
@matthew-carroll CI did catch it on the failing engine roll (https://cirrus-ci.com/task/5997428453933056), which showed that the framework was not ready to have the engine-side changes rolled in. The current way to handle this is a manual engine roll.

**Review by liyuqian — APPROVED** [review]
Nit: just added engine commits to the PR description. Please remember to include them when this is merged.

**Pull request merged**
