### PR TITLE
Bump mockito to 3.0.0-alpha+3

### PR DESCRIPTION
**Pull request by srawlins**
I ran `update-packages --force-upgrade`.

This PR bumps mockito to 3.0.0-alpha+3, which puts additional restrictions on mocks. Those additional restrictions will make for smoother rolls into Google internal, where mockito is about to enforce these restrictions.

### CODE REVIEW

**Comment by srawlins** [comment]
@aam would you be able to take a look? Travis is happy. This is ready.

**Review by aam — APPROVED** [review]

**Comment by aam** [comment]
@srawlins wrote
> @aam would you be able to take a look? Travis is happy. This is ready.

LGTM. Will you be able to land it?

**Comment by srawlins** [comment]
:grin: I also don't have write access.

**Comment by srawlins** [comment]
Thanks @aam!

**Pull request merged**
