### PR TITLE
Avoid labeling all PRs as 'text-input'

### PR DESCRIPTION
**Pull request by jmagman**
After https://github.com/flutter/flutter/pull/157650 all PRs are being labeled as text-input by the PR labeler. I think the config is missing an `all` based on the [negation example](https://github.com/actions/labeler/blob/main/README.md#basic-examples) 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by jmagman** [comment]
Closing, I give up, I'll revert https://github.com/flutter/flutter/pull/157650 instead.

**Comment by jmagman** [comment]
Oh wait, the labeler was using the one on main, not this PR https://github.com/flutter/flutter/actions/runs/11579120557/job/32234576590#step:2:91

Maybe this did work...

**Comment by jmagman** [comment]
Oh wait, the labeler was using the one on main, not this PR https://github.com/flutter/flutter/actions/runs/11579120557/job/32234576590#step:2:91

Maybe this did work...

**Review by TahaTesser — APPROVED** [review]
LGTM! (Without understanding how it works tho)

**Comment by jmagman** [comment]
> LGTM! (Without understanding how it works tho)

I promise to revert this for good if it goes haywire again.

**Pull request merged**
