### PR TITLE
Add more debug output to snippet git failures

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This adds more verbose failure output when the `git status` command fails inside of the snippet tool, because we were getting some odd return codes, with not enough information about why it died.

## Related Issues

- https://github.com/flutter/flutter/issues/83762

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: debugging diagnostics

**Review by jmagman — APPROVED** [review]
This error was mysterious...
LGTM

**Comment by gspencergoog** [comment]
Well, if it happens after this, at least we'll have more information.

**Comment by jmagman** [comment]
Merging to diagnose future flakes (current reason the build is closed).

**Pull request merged**
