### PR TITLE
re-enable system_debug_ios

### LINKED ISSUE #43029: Re-enable `system_debug_ios`, output logging during driver tests for devices running iOS 13+
We should re-enable the `system_debug_ios` devicelab test once https://github.com/flutter/flutter/issues/41133 is resolved. I commented the test out in https://github.com/flutter/flutter/pull/43026.

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

Re-enable `system_debug_ios`.

## Related Issues

Fixes #43029.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by christopherfujino** [comment]
@jmagman I opened this so we won't forget. Let's wait till Monday to land it though :)

**Comment by jmagman** [comment]
This will still fail.  I'm working on fixing the test driver now, which doesn't go through the same resident_runner code path.

**Comment by christopherfujino** [comment]
Oops, I knew that...

**Review by jmagman — CHANGES_REQUESTED** [review]
This will still fail.  I'm working on a PR to output logging during the driver tests.
I assigned https://github.com/flutter/flutter/issues/43029 to myself.

**Comment by goderbauer** [comment]
Is this PR still relevant? Or should we close it?

**Comment by jmagman** [comment]
Let's close it for now.

**Pull request closed without merging**
