### PR TITLE
Update default android page transition in the skeleton app

### LINKED ISSUE #92439: Skeleton template app uses legacy screen transitions
The skeleton template app uses the default screen transitions, which are out of date. We should consider how we can make the default be the newest style, and/or at least opt-in to the latest style in the template app.

(I'm referring to the animation you get when tapping the list items or the cog.)

### PR DESCRIPTION
**Pull request by willlockwood**
This PR updates the skeleton app template to define custom page transitions to better match the native transitions most commonly seen on Android 10 and above.

This should be reverted once https://github.com/flutter/flutter/pull/88482 has been relanded (or, more specifically, whenever someone makes an update that updates the default `PageTransitionsTheme._builders` to use the `ZoomPageTransitionBuilder` on Android).

This PR fixes https://github.com/flutter/flutter/issues/92439.

https://user-images.githubusercontent.com/7915388/147396920-0d8a92c9-a963-4182-9b85-f11a80690d8d.mov

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by Hixie** [comment]
If we want this to be the default, that seems like a better fix?

This should be tested, so that we don't accidentally break this.

cc @HansMuller @goderbauer for review

**Comment by superproprodev** [comment]
Superproprodev

**Comment by willlockwood** [comment]
Writing tests for the implementation now. Also totally happy to close this in favor of the ongoing work to update the default on `PageTransitionsTheme` 👍🏻

**Comment by goderbauer** [comment]
Instead of hard-coding this into the template we should work on making this the default across the board.

**Comment by willlockwood** [comment]
> Instead of hard-coding this into the template we should work on making this the default across the board.

Gotcha sounds good. I can close this then—should we also close the linked issue, in favor of the other ones that are tracking the updating of the default transition?

Also, are you familiar with any way that I can help move that along? I could imagine that maybe the performance issues/coordinating on the layer stuff is best left to internal folks, but if y'all could benefit from outside help I'd be glad to pitch in

**Pull request closed without merging**
