### PR TITLE
Revert "Roll Engine from fab19829949d to f121c1fe6843 (10 revisions)"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#96631

### CODE REVIEW

**Comment by zanderso** [comment]
Failed post-submit: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android%20integration_ui_keyboard_resize/218/overview

**Review by iskakaushik — APPROVED** [review]
LGTM

**Comment by zanderso** [comment]
Landing revert eagerly to green the tree.

**Comment by blasten** [comment]
cc @camsim99 - this test was also failing probably due to the same issue

**Pull request merged**
