### PR TITLE
Correct handling of InputDecoration.hintMaxLines=null (fixed issue #32830)

### PR DESCRIPTION
**Pull request by Shahzainali**
## Description

As per [hintMaxLine](https://api.flutter.dev/flutter/material/InputDecoration/hintMaxLines.html) Docs "This value is passed along to the Text.maxLines attribute of the Text widget used to display the hint text. TextOverflow.ellipsis is used to handle the overflow when it is limited to single line."

According to issue "So I expect that when both maxLines and hintMaxLines are null, the hint should keep growing and wrap to 2nd, 3rd, etc line. Instead, I see that it gets truncated with ellipsis"

Now the behaviour is when hintMaxlines is set to 1, it will get truncated with ellipsis, if hintMaxLines set to null the hint will not truncated, but it will go to 2nd line and so on..

## Related Issues

issue #32830 is fixed

## Tests

I added the following tests:

I have tested and it works perfectly.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Shahzainali** [comment]
Any way to check where flutter build is broken? 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.6.1-pre.43, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!

**Comment by Shahzainali** [comment]
Any way to check where flutter build is broken?

[✓] Flutter (Channel master, v1.6.1-pre.43, on Linux, locale en_US.UTF-8)
    • Flutter version 1.6.1-pre.43 at /media/zain/shahzain-personal/github/flutter
    • Framework revision dad8fb4f53 (80 minutes ago), 2019-05-23 03:04:56 +0500
    • Engine revision beb8e75121
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 9e30fbaea4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /media/zain/shahzain-personal/softwares/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • ANDROID_HOME = /media/zain/shahzain-personal/softwares/Android/Sdk
    • Java binary at: /media/zain/shahzain-personal/softwares/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /media/zain/shahzain-personal/softwares/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Redmi 4X • 945dc3127d04 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!

**Comment by Shahzainali** [comment]
@justinmc when it will be merged?

**Comment by justinmc** [comment]
I was worried about this simple one-liner being a solid solution for this, but after looking into it I'm on board.

As pointed out in https://github.com/flutter/flutter/issues/32830, the docs for hintMaxLines actually seem to incorrectly describe the current behavior as the behavior that will be created by this PR: "TextOverflow.ellipsis is used to handle the overflow when it is limited to single line.".  That's not currently true, but with this PR it will be.

The only other real fix I can think of for this problem is to give `Text` support for ellipsizing `maxLines: null` on the final line.  However, I'm not sure if this is possible or if we even want to do it (it would likely be a breaking change).  It seems like there's no need for now and this simple fix will work instead.

@Shahzainali Would you be able to add a test for this?  Maybe test the height of the hint text when `hintMaxLines` is 1 vs. something else.  You can test the height of the hint similar to how this test does it: https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/input_decorator_test.dart#L365

Also, we should probably update that last sentence in the docs to make it a bit more clear.  Maybe "[TextOverflow.ellipsis] is used to handle the overflow when hintMaxLines is 1, otherwise [TextOverflow.clip] is used.".  Here it is in the code: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/input_decorator.dart#L2349.

**Comment by justinmc** [comment]
@Shahzainali Are you still available to get this PR across the finish line?

**Comment by Shahzainali** [comment]
@justinmc yes I am available, but a little bit busy so can't add test.

**Comment by justinmc** [comment]
If anyone else has an interest in seeing this sort of change happen, please speak up.

**Comment by dnfield** [comment]
Without tests, we will not be able to land this. If you decide to add tests we'd be happy to reopen this and land it, or if anyone else needs it they can certainly open a new PR with this change and some tests.

**Pull request closed without merging**
