### PR TITLE
ExpansionTile: Add colors transition options

### PR DESCRIPTION
**Pull request by guissalustiano**
Add colors transitions options in used Title and Icon,
named 'headerColorTweenBegin', 'headerColorTweenEnd', 'iconColorTweenBegin' and 'iconColorTweenEnd'

## Description

I started adding properties that make it possible to define the colors used in the header animations, leaving what is used today by default
I didn't know which is the best default to indicate default values, since they need to be set by theme, so at runtime

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [XI updated/added relevant documentation (doc comments with `///`). (But I need help/confirmation)
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR. (nothing i changed)
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by shihaohong** [comment]
Hi, could you please provide a sample (gif or image) of what you're trying to achieve with this pull request? It seems unclear to me and involves almost completely modifying an existing the existing ExpansionPanel widget into completely separate one.

**Comment by christopherfujino** [comment]
Looking at the diff, I think you may have saved your changes as the wrong file. Also, your PR is not passing the CI checks (under "Some checks were not successful"). To see the failures locally, run `flutter analyze --flutter-repo`.

**Comment by JojoSalustiano** [comment]
Oops
I lost the file ...
And I can't access [fork](https://github.com/flutter/flutter/tree/patch-1) to reverse commit because I committed straight to github
Can I close this PR and open another?

**Comment by shihaohong** [comment]
> Oops
> I lost the file ...
> And I can't access [fork](https://github.com/flutter/flutter/tree/patch-1) to reverse commit because I committed straight to github
> Can I close this PR and open another?

I'm not sure what you mean here when you say you committed straight to GitHub, but it's totally fine to close this PR and open another one!

**Comment by JojoSalustiano** [comment]
I create new PR: #37153
Thanks and see you soon

**Pull request closed without merging**
