### PR TITLE
With flutter tests timing out on travis, this increases timeout from 30 to 60s.

### PR DESCRIPTION
**Pull request by aam**

### CODE REVIEW

**Comment by goderbauer** [comment]
/cc @Hixie, who recently played with the timeout logic. 

@aam what kind of timeouts are you seeing? Not sure if this is the right timeout to increase.

**Comment by aam** [comment]
I have seen errors like these:
```
 ╰─➤  ../../bin/cache/dart-sdk/bin/pub run test -j1 -rcompact test/commands/test_test.dart
00:23 +0 ~1 -1: flutter test should report nice errors for exceptions thrown within testWidgets() [E]                                      
  TimeoutException after 0:00:15.000000: Test timed out after 30 seconds.
  package:test  Invoker._onRun.<fn>.<fn>.<fn>
 ```
I landed this change as part of https://github.com/flutter/flutter/pull/19044 so the tests pass on Travis.

**Comment by Hixie** [comment]
My recent changes don't affect flutter_tools.

cc @tvolkert and @gspencergoog who are more familiar with the tool.

**Comment by gspencergoog** [comment]
I'm not sure which timeout that is either.

Also, that message is confusing anyhow:
```
TimeoutException after 0:00:15.000000: Test timed out after 30 seconds.
```
Huh?  Which is it? 15s or 30s?

**Pull request closed without merging**
