### PR TITLE
Increase image cache to 100MB

### LINKED ISSUE #18952: Image cache too small? Cache evicting too aggressive?
Based on discussion at https://github.com/flutter/flutter/pull/18135, cc @jonahwilliams 

I have two big (2000x1200) images (A and B) on in the tree of widgets. Both in the different paths of the tree, different BuildContexts, nested in different parents. At some point I throw away image A, replace it with B (which becomes new A) and load a third one, which becomes the new B.

At this point the B image shortly blinks (also the listener at ImageProvider.resolve(...).addListener(...) is called asynchronously).

This behavior appeared after the last upgrade to:
Flutter 0.5.6-pre.105 • channel master • https://github.com/flutter/flutter.git
Framework • revision 35e8cd83d0 (21 hours ago) • 2018-06-28 11:27:22 -0700
Engine • revision 6fe748490d
Tools • Dart 2.0.0-dev.63.0.flutter-4c9689c1d2

Increasing the cache helped:
PaintingBinding.instance.imageCache.maximumSizeBytes = 100 * 1000 * 1000;

Question is:
- is 10MB default cache size enough?
- is cache evicting too aggressive?

### PR DESCRIPTION
**Pull request by liyuqian**
This should fix https://github.com/flutter/flutter/issues/18952 and https://github.com/flutter/flutter/issues/813

### CODE REVIEW

**Comment by liyuqian** [comment]
@HansMuller @cbracken : the janky animation (https://drive.google.com/open?id=1Y9tETl-Elr8_VAlapTTPqoqGHMJYmo75) is caused by the image caching and this should fix it.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
We should probably connect some sort of diagnostic logging to the cache so that it notifies on eviction

**Comment by cbracken** [comment]
lgtm

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
Agreed maybe add `TRACE_EVENT_INSTANT0()` on evict?

**Comment by liyuqian** [comment]
@cbracken : is `TRACE_EVENT_INSTANT0` available in Dart? I get nothing from `git grep` inside `flutter/flutter`.

**Comment by jonahwilliams** [comment]
We evict from the dart side of things, but the engine still has to release the shared handle.

**Comment by Hixie** [comment]
If we ever log anything due to eviction, please make sure it's only when you enable a flag. There generally shouldn't be anything logged unless there's an error, otherwise people start ignoring errors because "oh that's just always logged, I don't know why".

**Pull request merged**
