### PR TITLE
Revert "Ensure time picker input mode lays out correctly in RTL"

### PR DESCRIPTION
**Pull request by mehmetf**
Reverts flutter/flutter#63599

This was reverted because flutter/flutter#63599, the ":" separator became vertically offset from the hours and minutes because of the addition of a nested Row widget that didn't specify the crossAxisAlignment appropriately. This ended up being caught by internal screenshot tests and so was reverted.

### CODE REVIEW

**Review by rami-a — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
Can you please include some information regarding why a PR was reverted in a revert?

**Comment by rami-a** [comment]
Added a comment why it was reverted in the description

**Comment by goderbauer** [comment]
Thanks!

**Pull request merged**
