### PR TITLE
Revert "Reland "fixes TextInputFormatter gets wrong old value of a se…

### PR DESCRIPTION
**Pull request by lukepighetti**
Revert "Reland "fixes TextInputFormatter gets wrong old value of a selection" (#76653)"
    
Related issue (#77855)
    
This reverts commit b0d4d4485310bf87bd67c8f1b99f348403ecdd99.

### Description

After b0d4d4485310bf87bd67c8f1b99f348403ecdd99 an issue appeared on macOS where if the user smashed their keys it would create an infinite loop where the text selection and contents would jitter.

At the same time, a bug manifested when used in concert with `flutter_masked_text` where any masked input would cause the cursor to not operate as expected, staying put when the mask inserted a character (?). This manifested itself on multiple platforms.

I am requesting this commit be merged into `dev` as a hotfix until a suitable replacement for b0d4d4485310bf87bd67c8f1b99f348403ecdd99 can be found.

I am also requesting clarification on my responsibilities for tests in this particular PR.

### MCVE

https://github.com/flutter/flutter/issues/77855#issuecomment-801251285

### Resolves

https://github.com/flutter/flutter/issues/77855

### The issue
77855-bad

### The fix

77855-good

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by chunhtai** [comment]
We can't merge this to the dev directly, we will have to merge this to the master and ask for cherry picking. This will be a hard revert because some other commit has landed on top of that.

**Comment by lukepighetti** [comment]
> We can't merge this to the dev directly, we will have to merge this to the master and ask for cherry picking. This will be a hard revert because some other commit has landed on top of that.

Switched base to `master`. Any guidance on the viability of this PR and anything I can do to improve it?

**Comment by chunhtai** [comment]
Let me see if I can come up with a fix without reverting the commit.

**Comment by lukepighetti** [comment]
Closed due to https://github.com/flutter/flutter/issues/77855#issuecomment-801335050, thanks!

**Pull request closed without merging**
