### PR TITLE
Make Flutter repo Dart SDK 2.1-dev3.1 compatible

### PR DESCRIPTION
**Pull request by mehmetf**

### CODE REVIEW

**Comment by mehmetf** [comment]
Not sure how these were not caught via the analyzer upstream but they are breaking Google.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Wasn't Future added/going to be added dart:core? If upstream linters/analyzer are using an older dart it might not work...still odd

**Comment by mehmetf** [comment]
Gah... I think it is the analyzer version problem... For this PR, I am getting

info • Unnecessary new keyword • packages/flutter_tools/lib/src/commands/daemon.dart:187:5 • unnecessary_new

Internally (and on Dartpad), this idiom does not work:

`new Future.sync()` vs `Future.sync()`.

I assume the latter is just assumed to be a static fn call, which I admit, is probably the right way to interpret it. Removing new keyword from named ctrs is probably not the right move.

@keertip

**Comment by keertip** [comment]
@leafpetersen

**Comment by keertip** [comment]
@mehmetf, you don't need the import. `dart:async` is now exported by `dart:core`

**Comment by mehmetf** [comment]
Yep Flutter is now at 2.1.0-dev.4 whereas internally we are at dev.3.1

One way to mitigate this would be to allow a grace period of backward compat. I think the import is one example where both importing and not importing works.

The new vs not-new Future.sync() is not backward compatible. I will seek permission to disable this analyzer check and unblock Google rolls. The dev.4 is not landing to google until next week.

**Pull request merged**
