### PR TITLE
Improve performance of Pesto hero animation

### PR DESCRIPTION
**Pull request by abarth**
Previously we were resizing a paragraph of text during the animation. Now we
animate the text and the image separately. Also, add a default hero tag for
FloatingActionButton so that it animates as part of the hero transition as
well.

### CODE REVIEW

**Comment by abarth** [comment]
@HansMuller @mpcomplete

**Comment by HansMuller** [comment]
LGTM

**Comment by mpcomplete** [comment]
This makes the image detach from the card while animating, moving us further from this design: https://github.com/flutter/flutter/issues/4436

**Comment by abarth** [comment]
There are two competing factors: (1) performance and (2) fidelity.  Ideally we'll end up with perfect performance and fidelity.  IMHO, we should get there along a path that has high performance at each step.

Prior to this patch, the performance of the transition wasn't very good.  For example, we were resizing the text in the recipe on every frame of the animation.  That's not something that's in the final design either, so it doesn't make sense to bang our heads against making that fast.

**Comment by Hixie** [comment]
The bottom paragraph shouldn't resize, but the caption and name should.

**Pull request merged**
