### PR TITLE
[flutter_conductor] Support initial stable release version

### LINKED ISSUE #89776: [flutter_conductor] conductor should support initial stable release versions
There is currently no way for the conductor to produce a stable release version *x*.*y*.0. If a conductor session was started where the increment level was set to z, but the previous version was a dev-style version (e.g. `1.2.0-3.4.pre`), the tool will throw an exception. This is correct for all subsequent stable hotfix releases, but will not support the initial stable release (such as the recent 2.5.0 release).

### PR DESCRIPTION
**Pull request by christopherfujino**
fixes: https://github.com/flutter/flutter/issues/89776

Previously, there was no way for the conductor to produce a stable release version x.y.0. If a conductor session was started where the increment level was set to `z`, but the previous version was a dev-style version (e.g. `1.2.0-3.4.pre`), the tool would throw an exception. This change modifies the tool to specifically detect this situation, and hard-code the `z` value to 0.

### CODE REVIEW

**Comment by christopherfujino** [comment]
cc @Yugue

**Review by CaseyHillers — APPROVED** [review]
flutter-lgtm

**Comment by christopherfujino** [comment]
tool_test failure is an unrelated test issue, that was just fixed in https://github.com/flutter/flutter/pull/89779:

```
16:44 +370 -1: test\commands.shard\permeable\create_test.dart: invokes pub offline when requested [E]                                                                                                  
  TimeoutException after 0:15:00.000000: Test timed out after 15 minutes.
  dart:isolate  _RawReceivePortImpl._handleMessage
```

I will rebase

**Comment by CaseyHillers** [comment]
@Yugue for reference, @christopherfujino was able to identify the failure as not his via following the Discord chat, but you can also check https://flutter-dashboard.appspot.com/#/build to see if any of your tests are failing there. In this instance, we randomize the tests daily, and today showed a failure that needed to be fixed. So doing `git fetch upstream && git rebase upstream/master` fixed his PR.

**Comment by christopherfujino** [comment]
lol, I was too slow, now another upstream failure has been introduced :P

https://github.com/flutter/flutter/issues/89792

**Pull request merged**
