### PR TITLE
enable avoid_web_libraries_in_flutter

### PR DESCRIPTION
**Pull request by pq**
## Description

Enable `avoid_web_libraries_in_flutter` to flag web library uses outside of Flutter web plugins w/ `flutter analyze`.

/fyi @devoncarew 

## Related Issues

https://github.com/dart-lang/sdk/issues/38691

Bump linter in SDK: https://dart-review.googlesource.com/c/sdk/+/123466 (limits web lib access to Flutter web plugin packages).

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by yjbanov** [comment]
Will this be a breaking change for our users? I don't believe we have anything in this repo to detect this as a breaking change.

**Comment by jonahwilliams** [comment]
> Will this be a breaking change for our users? I don't believe we have anything in this repo to detect this as a breaking change.

I do not thing we should be considering web specific breaking changes until we hit some level of stability

**Comment by pq** [comment]
Good question.  In general I didn't think improved analysis would be considered a "breaking change" but I'd be curious of your perspective. @jonahwilliams makes a good point too.  At this point Flutter web is moving pretty fast and is probably technically _nearly always_ breaking...

**Comment by yjbanov** [comment]
I'm not worried about breaking web code. I'm more worried about breaking code that targets both mobile and web. In this case, this change could potentially be breaking production mobile code that, for example, uses conditional imports and uses web libraries in the web implementation. But perhaps I'm being paranoid. I guess let's try and see. Worst case we can revert and try rolling this differently. LGTM.

**Review by yjbanov — APPROVED** [review]

**Pull request merged**
