### PR TITLE
Manual dependency bump

### PR DESCRIPTION
**Pull request by kevmoo**
`package:collection` is 50+ days behind at this point which is blocking updates to a number of other packages `http_parser`, `shelf`, etc...

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
Looks like legit build failure:

```
[        ] Caused by: org.gradle.internal.locking.LockOutOfDateException: Resolved 'androidx.media3:media3-exoplayer-rtsp:1.4.0' which is not part of the dependency lock state
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8740412652728516577/+/u/run_test.dart_for_build_tests_shard_and_subshard_1_3/stdout

**Comment by christopherfujino** [comment]
cc @gmackall

**Comment by gmackall** [comment]
This should be fixed by updating the Gradle lockfiles, from the root of your Flutter repo
```
find . -type d -name 'android' | dart dev/tools/bin/generate_gradle_lockfiles.dart --no-exclusion --no-gradle-generation
```
If it complains that you need Java 17 you can set you `JAVA_HOME` to the java in the engine checkout (at `engine/src/flutter/third_party/java/openjdk/Contents/Home/`)

Or just apply this diff if that works? [lockfile_diff.txt](https://github.com/user-attachments/files/16503108/lockfile_diff.txt)

**Comment by kevmoo** [comment]
lock file applied. Let's see!

**Pull request merged**
