### PR TITLE
Capitalize german OkButtonLabel

### PR DESCRIPTION
**Pull request by MCOfficer**
## Description

In the german localization (and all others i looked at), labels are full uppercase, while tooltips are the way german text normally works. The only exception to this is the german "OK"-Button label, which is PascalCase. This makes for rather awkward dialogs:
grafik

For reference, this is the OkButtonLabel in other localizations:
https://github.com/flutter/flutter/blob/e026bd3d33c79c8e68ea0065815dcae9981464f5/packages/flutter_localizations/lib/src/l10n/material_fr.arb#L27
https://github.com/flutter/flutter/blob/e026bd3d33c79c8e68ea0065815dcae9981464f5/packages/flutter_localizations/lib/src/l10n/material_en.arb#L126
https://github.com/flutter/flutter/blob/e026bd3d33c79c8e68ea0065815dcae9981464f5/packages/flutter_localizations/lib/src/l10n/material_ru.arb#L31

This PR turns the PascalCase `Ok` into a full uppercase `OK`.

*yes, this may the most trivial PR ever.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by MCOfficer** [comment]
@googlebot I signed it!

**Comment by MCOfficer** [comment]
bump .-.

@HansMuller @Hixie since you're possible review candidates :)

**Comment by HansMuller** [comment]
I will route this suggested change through our internal system for managing translations.  Assuming that it's accepted (I don't see why it wouldn't), it will take a couple of weeks for it to appear in the sources.  When it does, I will close this PR. Thanks for the contribution!

**Comment by shihaohong** [comment]
I just put in the suggested change through our translation management system. I'll keep this updated as I get more information!

**Pull request closed without merging**
