### PR TITLE
Use Isolate.run as implementation for compute

### LINKED ISSUE #48566: Usibility issue with Isolate.run wrt to over-capturing
`Isolate.run` is difficult to use because of https://github.com/dart-lang/sdk/issues/36983. When the closure provided to `Isolate.run` captures unnecessary stuff (because of that bug) that can't be send to an isolate, the user only sees this cryptic message:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: (object extends NativeWrapper - Library:'dart:ui' Class: Path)
#0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:399:25)
#1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:379:7)
#2      Isolate.run (dart:isolate:232:15)
#3      _MyHomePageState._applySepiaFilterInIsolate (package:isoimg/main.dart:100:45)
```

It is not at all obvious that this is because the closure provided was over-capturing.

IMO, this is a major usability problem for `Isolate.run` because it is easy to use in a way that triggers the problem and the solution is not clear from the error message.

Example where I ran into this: https://github.com/goderbauer/scratchpad/blob/8d82e738a4307c65651dc854ec6437002f69d6ed/isoimg/lib/main.dart#L90-L92

To make it work, one has to define a static method to avoid over-capturing: https://github.com/goderbauer/scratchpad/commit/e36c3117b7d30733a726b4dd4769dd58c045accf

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/dart-lang/sdk/issues/48566

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Doesn't that lose the Timeline logic?

**Comment by Hixie** [comment]
If not, might be worth adding a test that the Timeline logic still works, actually. I should probably have done that when I created this API in the first place.

**Comment by dnfield** [comment]
> Doesn't that lose the Timeline logic?

It loses the timeline logic we had, but still will have timeline logic from the Dart VM.

I was looking at what to preserve, but it looks like at some point the timeline logic got refactored to only use flow IDs around port creation and disposal, and I'm not really sure how useful that was anyway.

**Comment by mit-mit** [comment]
@MaryaBelanger fyi

**Comment by Hixie** [comment]
That's sad. Ideally what you'd want to see is the flow going from one thread to the other in the timeline so you could easily follow the logic of your code. IIRC that's what it looked like when I originally did it, but my bad for not writing tests for that.

**Comment by Hixie** [comment]
test-exempt: deletes code

**Comment by mit-mit** [comment]
@Hixie can we go ahead and merge this on Dan's behalf? I'd like for this to go out in this week stable so that it's aligned with the corresponding Dart change.

**Comment by goderbauer** [comment]
Talked to @Hixie, he is fine with this. Adding the merge label to get it submitted.

**Pull request merged**
