### PR TITLE
Specify what image formats are supported in the API docs.

### PR DESCRIPTION
**Pull request by Hixie**
Depends on https://github.com/flutter/engine/pull/4483

### CODE REVIEW

**Comment by xster** [comment]
LG

**Comment by Hixie** [comment]
will land after next engine roll

**Comment by Hixie** [comment]
Blocked on https://github.com/dart-lang/dartdoc/issues/1582

**Comment by Hixie** [comment]
Pending dartdoc roll.

**Comment by Hixie** [comment]
Will land after https://github.com/flutter/flutter/pull/14123 lands.

**Pull request merged**
