### PR TITLE
add flutter_gallery__transition_perf_e2e to ios tests

### PR DESCRIPTION
**Pull request by CareF**
## Description

As a follow up of #62064, to add the test to iOS

## Related Issues

#60559

## Tests

The PR itself is to add tests 

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by liyuqian — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
This test (flutter_gallery__transition_perf_e2e_ios32) has failed five times since being added to the manifest (2 days ago).
This is excessively flaky. I suggest removing it until we can figure out the cause of the flakiness.

**Comment by Hixie** [comment]
Filed as https://github.com/flutter/flutter/issues/64748

**Comment by liyuqian** [comment]
Also filed https://github.com/flutter/flutter/issues/64753 to track the root cause of the flakiness. More discussions are available in https://github.com/flutter/flutter/issues/64748#issuecomment-682153820

**Pull request merged**
