### PR TITLE
[flutter_tools] iOS VM Service logs should include stderr

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

This is an educated guess fix for https://github.com/flutter/flutter/issues/58078 , but I don't have an iOS device to test.

### CODE REVIEW

**Comment by jmagman** [comment]
@jonahwilliams Is there any way to force an error message?  I can try testing.

**Comment by jmagman** [comment]
This looks like an obviously good change, but I'm not getting any compilation error logs, even if flutter is handling it:
```dart
int x;
void main() {
   x + 0;
}
```
In Console on the device I see the log:
```
	default	12:40:30.361433-0700	Runner	[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method '+' was called on null.
Receiver: null
Tried calling: +(0)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      main (package:test_error/main.dart:5:10)
#2      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:247:25)
#3      _rootRun (dart:async/zone.dart:1190:13)
#4      _CustomZone.run (dart:async/zone.dart:1093:19)
#5      _runZoned (dart:async/zone.dart:1630:10)
#6      runZonedGuarded (dart:async/zone.dart:1618:12)
#7      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:239:5)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```
Nothing from the tool observatory output.  

Even when flutter does handle it:
```dart
  void _incrementCounter() {
    setState(() {
       x + 0;
    });
  }
```
Device logs:
```
	default	12:37:31.600388-0700	Runner	flutter: Another exception was thrown: NoSuchMethodError: The method '+' was called on null.
```
but again, nothing from the tool observatory output.

Ditto on master.

**Comment by jonahwilliams** [comment]
Interesting! I'd say this a bug in the engine then, we should be directing these to stderr at least

**Comment by jmagman** [comment]
Still seems smart to land this change even if it doesn't fix #58078.

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
See also https://github.com/flutter/engine/pull/13487 which was reverted.

**Comment by jonahwilliams** [comment]
It looks like we hit the verbose warning if there is no unhandled_exception_callback:

https://github.com/flutter/engine/blob/master/lib/ui/ui_dart_state.cc#L159

This is passed from a settings handle in dart_isolate:

https://github.com/flutter/engine/blob/1c8ee9856bffbc637670d372ac4a88bd11368f46/runtime/dart_isolate.cc#L138

For example, usage in fuchsia:

https://github.com/flutter/engine/blob/c9f98914548bbdb93b9c011afe2a60404464c958/shell/platform/fuchsia/flutter/component.cc#L393

**Pull request merged**
