### PR TITLE
Cover focus tests with leak tracking

### PR DESCRIPTION
**Pull request by ksokolovskyi**
### Description
This PR changes `testWidgets` by `testWidgetsWithLeakTracking` in number of `flutter/test/widgets` tests according to the https://github.com/dart-lang/leak_tracker/issues/134.

### Tests
- Updates `focus_manager_test.dart` to use `testWidgetsWithLeakTracking`;
- Updates `focus_scope_test.dart` to use `testWidgetsWithLeakTracking`;
- Updates `focus_traversal_test.dart` to use `testWidgetsWithLeakTracking`.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by ksokolovskyi** [comment]
cc @polina-c

**Comment by XilaiZhang** [comment]
side note: I was testing out a few things and Google Testing wasn't triggered on this PR, it should be triggered on future commits pushed to this pr.

**Review by polina-c — APPROVED** [review]

**Comment by polina-c** [comment]
@XilaiZhang , i merged master, but I do not see google testing in the list. Is it ok to merge if everything is green or I need to trigger google testing somehow?

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by XilaiZhang** [comment]
Umm looks like Google Testing was [pending due to merge conflict](https://github.com/flutter/flutter/wiki/Understanding-Google-Testing#my-cl-reached-max-number-of-retry-why-and-how-do-i-resolve-this), very likely due to flutter rolls being 2 weeks behind current head.

I sent cl/564524744 to better manifest the information on propagating merge conflict information

**Comment by ksokolovskyi** [comment]
@polina-c @chunhtai @XilaiZhang thanks for the review!

**Pull request merged**
