### PR TITLE
Only complete the web socket future once

### PR DESCRIPTION
**Pull request by tvolkert**

### CODE REVIEW

**Comment by tvolkert** [comment]
@Hixie 

Internally, I witnessed a "Bad state: Future already completed" flaky test run for `rendering_box_constraints_test.dart`

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
BTW, this was checked in when the tree was red. Please avoid checking anything in when the tree is red except for attempts to fix the tree. Thanks!

**Comment by Hixie** [comment]
I'm so confused as to how this could possible end up getting called twice. Is the server returning two results or something?!

**Comment by tvolkert** [comment]
It must be.  I've seen it happen twice, and both times, it was during a coverage run.  I can locally add some instrumentation and run it internally 1000 times to see what the server responses are.

**Comment by tvolkert** [comment]
Following up on this... the plot thickens.  I ran 50K iterations of a test that saw this failure, and none of them saw this getting called twice - even if I sync to the version that saw the failure!

It could have been triggered by some transient external conditions at the time...?

**Pull request merged**
