### PR TITLE
Fix Scrollable.of()

### LINKED ISSUE #1087: Scrollable.of returns null for a child of a ScrollableViewport

### PR DESCRIPTION
**Pull request by Hixie**
Make ancestorStateOfType() and ancestorRenderObjectOfType() support
subclassing.

Fixes https://github.com/flutter/flutter/issues/1087

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by HansMuller** [comment]
I think TabBarSelectionState.of() (material/tabs.dart) could be rewritten too:

```
static TabBarSelectionState of(BuildContext context) => context.ancestorStateOfType(const TypeMatcher<TabBarSelectionState>());
```

**Comment by Hixie** [comment]
Yeah, good call. Will fix TabBarSelectionState.of() in separate patch.

**Comment by Hixie** [comment]
filed https://github.com/flutter/flutter/issues/1117 for that case

**Pull request merged**
