### PR TITLE
Adding `@docImport`s to the `animation` library

### PR DESCRIPTION
**Pull request by goderbauer**
Part of https://github.com/flutter/flutter/issues/150800.

I turned on the `comment_references` lint and looked at what needed fixing inside of the `animation` library.

There are a couple of places where for some reason adding a docImport didn't fix the `comment_references` warning:

- [ ] All the references in the doc on the `library` statement of the animations library (no doc import helps), example: https://github.com/flutter/flutter/blob/65e6bde4b13a680cbc0e9032c39e299aab882280/packages/flutter/lib/animation.dart#L12
- [ ] The docImport of `package:flutter/material.dart` is for some reason unable to resolve `[Easing.legacy]`: https://github.com/flutter/flutter/blob/65e6bde4b13a680cbc0e9032c39e299aab882280/packages/flutter/lib/src/animation/curves.dart#L1831
- [ ] The docImport of `package:flutter/widgets.dart` is for some reason unable to resolve `[State]` and `[AnimationController]` in https://github.com/flutter/flutter/blob/65e6bde4b13a680cbc0e9032c39e299aab882280/packages/flutter/lib/src/animation/animations.dart#L50 https://github.com/flutter/flutter/blob/65e6bde4b13a680cbc0e9032c39e299aab882280/packages/flutter/lib/src/animation/animations.dart#L410

### CODE REVIEW

**Comment by goderbauer** [comment]
cc @srawlins

**Review by srawlins — APPROVED** [review]
❤️  I want to look into the problem children but it could take me a while to get there.

**Comment by goderbauer** [comment]
Uh, lots of google testing targets are failing, claiming that they are unable to resolve the URIs in the doc imports:

```
Target of URI doesn't exist. #uri_does_not_exist

/// @docImport 'package:flutter_test/flutter_test.dart';
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by srawlins** [comment]
You should be able to `// ignore: uri_does_not_exist` above those.

Since `package:flutter` does not have any dependency on `package:flutter_test`, there is no way for the analyzer to resolve those `@docImport`s. As for dartdoc... I need to think about whether those will cause problems...

**Comment by goderbauer** [comment]
It does specify a dev dependency on flutter_test:

https://github.com/flutter/flutter/blob/9afd397cd4b996b896cc49fa21d57b60aff6bf70/packages/flutter/pubspec.yaml#L21-L23

**Comment by matanlurey** [comment]
text-exempt: Awesome.

**Comment by srawlins** [comment]
Ah, interesting! Is there a `flutter_test` entry then, in `packages/flutter/.dart_tool/package_config.json`? Can you paste it here, please.

**Comment by goderbauer** [comment]
It's in there (see below, from my local machine). One thought though: The issue is reported in google3, I don't know how things are set up there and whether the `package_config.json` equivalent there would include it?

```
{
  "configVersion": 2,
  "packages": [
    {
      "name": "async",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/async-2.11.0",
      "packageUri": "lib/",
      "languageVersion": "2.18"
    },
    {
      "name": "boolean_selector",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/boolean_selector-2.1.1",
      "packageUri": "lib/",
      "languageVersion": "2.17"
    },
    {
      "name": "characters",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/characters-1.3.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "clock",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/clock-1.1.1",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "collection",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/collection-1.18.0",
      "packageUri": "lib/",
      "languageVersion": "2.18"
    },
    {
      "name": "crypto",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/crypto-3.0.3",
      "packageUri": "lib/",
      "languageVersion": "2.19"
    },
    {
      "name": "fake_async",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/fake_async-1.3.1",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "file",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/file-7.0.0",
      "packageUri": "lib/",
      "languageVersion": "3.0"
    },
    {
      "name": "flutter_goldens",
      "rootUri": "file:///Users/goderbauer/dev/flutter/packages/flutter_goldens",
      "packageUri": "lib/",
      "languageVersion": "3.2"
    },
    {
      "name": "flutter_test",
      "rootUri": "file:///Users/goderbauer/dev/flutter/packages/flutter_test",
      "packageUri": "lib/",
      "languageVersion": "3.3"
    },
    {
      "name": "leak_tracker",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/leak_tracker-10.0.5",
      "packageUri": "lib/",
      "languageVersion": "3.2"
    },
    {
      "name": "leak_tracker_flutter_testing",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/leak_tracker_flutter_testing-3.0.5",
      "packageUri": "lib/",
      "languageVersion": "3.2"
    },
    {
      "name": "leak_tracker_testing",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/leak_tracker_testing-3.0.1",
      "packageUri": "lib/",
      "languageVersion": "3.2"
    },
    {
      "name": "matcher",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/matcher-0.12.16+1",
      "packageUri": "lib/",
      "languageVersion": "3.0"
    },
    {
      "name": "material_color_utilities",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/material_color_utilities-0.11.1",
      "packageUri": "lib/",
      "languageVersion": "2.17"
    },
    {
      "name": "meta",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/meta-1.15.0",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "path",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/path-1.9.0",
      "packageUri": "lib/",
      "languageVersion": "3.0"
    },
    {
      "name": "platform",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/platform-3.1.5",
      "packageUri": "lib/",
      "languageVersion": "3.2"
    },
    {
      "name": "process",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/process-5.0.2",
      "packageUri": "lib/",
      "languageVersion": "3.0"
    },
    {
      "name": "sky_engine",
      "rootUri": "file:///Users/goderbauer/dev/flutter/bin/cache/pkg/sky_engine",
      "packageUri": "lib/",
      "languageVersion": "3.2"
    },
    {
      "name": "source_span",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/source_span-1.10.0",
      "packageUri": "lib/",
      "languageVersion": "2.18"
    },
    {
      "name": "stack_trace",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/stack_trace-1.11.1",
      "packageUri": "lib/",
      "languageVersion": "2.18"
    },
    {
      "name": "stream_channel",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/stream_channel-2.1.2",
      "packageUri": "lib/",
      "languageVersion": "2.19"
    },
    {
      "name": "string_scanner",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/string_scanner-1.2.0",
      "packageUri": "lib/",
      "languageVersion": "2.18"
    },
    {
      "name": "term_glyph",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/term_glyph-1.2.1",
      "packageUri": "lib/",
      "languageVersion": "2.12"
    },
    {
      "name": "test_api",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/test_api-0.7.2",
      "packageUri": "lib/",
      "languageVersion": "3.2"
    },
    {
      "name": "typed_data",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/typed_data-1.3.2",
      "packageUri": "lib/",
      "languageVersion": "2.17"
    },
    {
      "name": "vector_math",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/vector_math-2.1.4",
      "packageUri": "lib/",
      "languageVersion": "2.14"
    },
    {
      "name": "vm_service",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/vm_service-14.2.4",
      "packageUri": "lib/",
      "languageVersion": "3.3"
    },
    {
      "name": "web",
      "rootUri": "file:///Users/goderbauer/.pub-cache/hosted/pub.dev/web-0.5.1",
      "packageUri": "lib/",
      "languageVersion": "3.3"
    },
    {
      "name": "flutter",
      "rootUri": "../",
      "packageUri": "lib/",
      "languageVersion": "3.3"
    }
  ],
  "generated": "2024-06-25T21:23:51.682231Z",
  "generator": "pub",
  "generatorVersion": "3.5.0-297.0.dev",
  "flutterRoot": "file:///Users/goderbauer/dev/flutter",
  "flutterVersion": "3.23.0-13.0.pre.328",
  "pubCache": "file:///Users/goderbauer/.pub-cache"
}
```

**Comment by srawlins** [comment]
I'm going to work on enabling `unnecessary_import`, `unused_import`, `duplicate_import`, `unused_shown_name`, `duplicate_shown_name`, `duplicate_hidden_name`, `unknown_hidden_name`, and ensuring `ambiguous_import` is reported for `@docImport`s. That should remove some pain when trying a CL like this.

**Comment by srawlins** [comment]
Ah ok, if it is _only_ google3, then I am much less surprised, and the issue is clear. `flutter_test` is not a "Bazel dependency" of `flutter` over there, so there is no such thing as `package:flutter_test`. I'm not sure I can think of any better path forward (even long-term) other than ignoring `uri_does_not_exist` for those lines. This would be the same solution for `dart:ui` libraries attempting to `@docImport 'package:flutter/...`.

**Comment by matanlurey** [comment]
I coincidentally saw this and talked to @srawlins this morning.

I'd like to propose a (simpler) alternative that doesn't leave @goderbauer (or others) having to ignore things externally that have no value internally - let's just turn this whole class of warning code _off_ in google3. G3 doesn't support dartdoc, and there is no timetable where it would.

I'd suggest:

- [ ] @srawlins renames the warning code (i.e. `unused_doc_import` instead of reusing `unused_import`)
- [ ] @srawlins hardcodes google3 to _always ignore_ these class of diagnostics
- [ ] @goderbauer can move forward with these PRs without a weird workflow

**Comment by goderbauer** [comment]
What Matan suggests above would be also my preferred way forward. Solving the internal problems with ignores in the open-source code feels ... iky. In open source land we do want to see warnings if we accidentally docimport something that doesn't exist.

> This would be the same solution for `dart:ui` libraries attempting to `@docImport 'package:flutter/....`

Sounds like that wouldn't solve this case, though? This worries for the same reasons: We do want to know if we accidentally import something that doesn't exist and not ignore that...

**Comment by matanlurey** [comment]
Sam was supportive when I spoke to him - Sam if I can help in anyway (code reviews, google3 hacking) LMK

**Comment by srawlins** [comment]
Is there any problem in this PR with `unused_import`? That is a "warning" for real imports and for doc imports, so I was not planning on splitting that.

However, `uri_does_not_exist` is a COMPILE_TIME_ERROR, so I do intend to split that, and report something similar for doc imports that is a "warning" (and has a different name so that we can universally ignore it in google3).

**Comment by goderbauer** [comment]
> Is there any problem in this PR with unused_import?

So far, I have not encountered any problems with that lint in this PR.

**Comment by goderbauer** [comment]
I removed the problematic flutter_test docimport for now to see if there are any other issues. If there aren't I am planning on submitting this without that import for now.

**Pull request merged**
