### PR TITLE
Reland Button padding M3

### PR DESCRIPTION
**Pull request by CaseyHillers**
Reverts flutter/flutter#119597

I'll land this when the LSC tooling is ready, and the Flutter roll is up to date.

### CODE REVIEW

**Review by esouthren — APPROVED** [review]
LGTM!

**Review by guidezpl — APPROVED** [review]
```
  _    ___ _____ __  __ 
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
                        
```

**Comment by CaseyHillers** [comment]
@XilaiZhang this is the first LSSC. Can you merge it in when you're ready?

**Comment by XilaiZhang** [comment]
Casey built a LSSC tool yesterday, we will merge in this PR today

**Comment by XilaiZhang** [comment]
will squash and merge

**Pull request merged**
