### PR TITLE
Revert "[flutter_tools] remove alternative build aot code path"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#49577

android_compile_ devicelab failures, these tests are still using AOT

### CODE REVIEW

**Comment by jonahwilliams** [comment]
tbr @zanderso

**Comment by zanderso** [comment]
lgtm

**Comment by zanderso** [comment]
Looks like this change also broke some benchmarks in Dart's infrastructure, so we'll have to be sure to coordinate there too. @sortie

**Comment by sortie** [comment]
You can coordinate with the Dart VM team about these changes as they own the benchmarks.

**Comment by jonahwilliams** [comment]
I might be easier to start with a warning before removing any functionality then, something like:

"If you were going to run 'flutter build aot --..' instead run 'flutter assemble ... "

**Pull request merged**
