### PR TITLE
Lazily download artifacts (III): The Revenge of the Sith

### LINKED ISSUE #6491: Would be nice if `flutter run` only downloaded the necessary artifacts
I was on a train with bad wifi.  It was painful.

I was trying to run the gallery on an iOS Simulator.

```
%flutter run
Building flutter tool...
Downloading package sky_engine...                    8101ms
Running 'pub get' in sky_engine...                   450ms
Downloading package sky_services...                  596ms
Running 'pub get' in sky_services...                 3139ms
Downloading package flutter_services...              1929ms
Running 'pub get' in flutter_services...             2294ms
Building Dart SDK summary...                         1753ms
Downloading engine artifacts android-arm...          177027ms
Downloading engine artifacts android-arm-profile...  164117ms
Downloading engine artifacts android-arm-release...  115925ms
Downloading engine artifacts android-x64...          78964ms
Downloading engine artifacts android-x86...          78600ms
Downloading engine artifacts ios...                  178979ms
Downloading engine artifacts ios-profile...          189778ms
Downloading engine artifacts ios-release...          152586ms
Downloading darwin-x64 tools...                      232022ms
Downloading android-arm-profile/darwin-x64 tools...  34656ms
Downloading android-arm-release/darwin-x64 tools...  139862ms
Running 'pub get' in flutter_gallery...              870ms
```

FYI @danrubel

### PR DESCRIPTION
**Pull request by jonahwilliams**
To make this landable I have removed all of the lazily downloading logic. The gradle scripts seem to either be losing information about what their build_mode/target is or they are requesting artifacts that aren't needed.

-------------------

Work towards #6491

Allows configuring which artifacts are required by a command, by default all artifacts are still downloaded.

* buildMode & targetPlatform for filtering by artifacts, can be null. If null, retrieve all artifacts matching one of the other parameters. For example, targetPlatform.ios and null buildMode downloads debug, profile, and release for iOS.
  -skipUnknown, which allows downloading artifacts when targetPlatform and hostPlatform are unknown.
* clobber, whether to force re-downloading of artifacts

`flutter precache` will still download the full set of artifacts for a given host platform.
`flutter precache -f/--force` will re download all artifacts.

Re-organizes engine artifacts into a class from lists of lists of strings.

Flutter commands can now check the artifacts for the given or default build mode, and any connected devices. (note: android-arm-profile is downloaded unconditionally because we currently need it for a Flutter doctor check).

This is accomplished via a new method on FlutterCommand called `updateCache`. This is only called if `shouldUpdateCache` is true. The default implementation is:

```
  Future<void> updateCache() async {
    // Only download the minimum set of binaries.
    await cache.updateAll(
      clobber: false,
      skipUnknown: true,
    );
  }
```

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
Third time's the charm!
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by gspencergoog** [comment]
### :crossed_fingers:

**Comment by jonahwilliams** [comment]
Nope

**Comment by gspencergoog** [comment]
#### :cry:

**Pull request merged**
