### PR TITLE
Attempt skipping coverage shard if tools did not change

### PR DESCRIPTION
**Pull request by jonahwilliams**
In order to stop codecov bot from commenting on everyone's PR. I had previously attempted this and it didn't quite work, but I might have made a stupid

### CODE REVIEW

**Comment by jonahwilliams** [comment]
If this PR https://github.com/flutter/flutter/pull/35234 runs the coverage shard, we're OK to skip

**Comment by jonahwilliams** [comment]
cc @dnfield

**Comment by jonahwilliams** [comment]
The linked PR has started running the tools check, so this does work well enough for now

**Review by dnfield — APPROVED** [review]
Lgtm

**Comment by jonahwilliams** [comment]
mac luci passed on rerun, landing

**Pull request merged**
