### PR TITLE
Revert "[flutter_test] Adds method to mock EventChannels"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#123726

Analysis failures on CI https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20analyze/12890/overview

### CODE REVIEW

**Comment by zanderso** [comment]
cc @Rexios80

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
@Rexios80 Looks like your branch may have been outdated and didn't have these deprecations yet.

**Comment by Rexios80** [comment]
I thought I avoided the deprecated methods. How do we continue? Do I need to make a new PR?

**Comment by pdblasi-google** [comment]
@Rexios80

It was likely an indirect conflict with a different recent merge that only became apparent after merging. You'll have to make a new PR that avoids the method mentioned in the analyzer.

Relands typically move a lot faster though as the main code usually doesn't need to change much to resolve the issue.

**Pull request merged**
