### PR TITLE
Reland "Add BuildContext parameter to TextEditingController.buildTextSpan"

### LINKED ISSUE #72343: Pass BuildContext to TextEditingController.buildTextSpan
## Use case

I'm building a rich text editor by overriding `TextEditingController.buildTextSpan` in a `SpannedTextEditingController`. Users can apply `TextAttribute` to parts of the text managed by the controller (the controller maintains the active attributes as well).

*The following explanation is slightly simplified*

These attributes currently have a `TextStyle` that is applied to the `TextSpans` created in `TextEditingController.buildTextSpan`:

```
class TextAttribute {
  TextStyle get style;
}
```

However, I would like for the attributes to be themeable. E.g. a 'Header' attribute should not have a fixed size. They'd have a `resolve` method that takes a `BuildContext` - so they can use `InheritedWidgets` - and returns the actual `TextStyle`:

```
class TextAttribute {
  TextStyle resolve(BuildContext context);
}
```

Of course now I need access to the wrapping `BuildContext` in `buildTextSpan`.

### Alternatives

The `SpannedTextEditingController` could hold theming data itself (for example with an `AttributeTheme` field). I do not think this is a great solution because:

1. The responsibility of retrieving the theme is placed outside the `SpannedTextEditingController`.
1. It does not match with the way themes are used in flutter. Themes are not stored for later use, instead they are depended on and used immediately.
1. The theme would need to be depended upon (`AttributeTheme.of`) where the controller is created, which is not necessarily close to the widget that displays the text. This would most likely be a source of confusion and error as theming beneath the context that the controller was created in is not applied.

## Proposal

Add a `BuildContext` parameter to `TextEditingController.buildTextSpan` and pass the build context in [`EditableTextState.build`](https://github.com/flutter/flutter/blob/58081821ab8f0f56a1e4c21da61203fcd0ef2f13/packages/flutter/lib/src/widgets/editable_text.dart#L2602).

This would be a breaking change for inheritors and users of the API (because the parameter would be `required`).

Design doc: https://docs.google.com/document/d/1nr-g45gXcWTYoW9UmChZV7Ije3lKP4pEvDQCdz6NFdI/edit?usp=sharing

### PR DESCRIPTION
**Pull request by Jjagg**
Redo of #72344 after revert in #73503.

The original PR did not follow the breaking changes policy.

Fixes #72343, which should be reopened.

Sorry about that @justinmc, and thanks for picking this up. Should I set up a design document? I'm new to this 😬

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

Design doc: https://docs.google.com/document/d/1nr-g45gXcWTYoW9UmChZV7Ije3lKP4pEvDQCdz6NFdI/edit?usp=sharing

### CODE REVIEW

**Comment by justinmc** [comment]
No worries, I should have realized that this would be a breaking change when I reviewed it!  Thanks for following up and reopening.

Yes, could you write up a design doc and follow the steps in the [breaking change policy](https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes)?  Then we can make sure anyone that might be broken by this is aware of how to migrate.  I think the code in this PR should be fine as-is.

**Comment by Jjagg** [comment]
Added the design doc [link](https://docs.google.com/document/d/1nr-g45gXcWTYoW9UmChZV7Ije3lKP4pEvDQCdz6NFdI/edit?usp=sharing)!

**Review by justinmc — APPROVED** [review]
LGTM, thanks for following up with this 👍 

Have you done the migration guide steps in the breaking change policy ([step 3 here](https://github.com/flutter/flutter/wiki/Tree-hygiene#3-prepare-your-change))?  You can take most of it from your design doc, then ping Hixie about it on Discord, and then send it out as an email.  Then we can merge this.

**Comment by Jjagg** [comment]
Not yet, some things came up. I've also not pointed RedBrogdon to the design doc.

I'll put some time into this today to ask for feedback and create the migration guide :)

**Comment by Hixie** [comment]
usually the build context is the first (positional) argument, would it make sense to do that here too?

**Comment by Jjagg** [comment]
> usually the build context is the first (positional) argument, would it make sense to do that here too?

That's a good point. Yes, I think that'd be more consistent with other API's. I'll make the change.

**Review by justinmc — APPROVED** [review]
Still LGTM with the reordered arguments 👍 

Are you ready to merge with the breaking change stuff?

**Comment by Jjagg** [comment]
Yes, I think this is good to go. I haven't had any more feedback on the design doc or migration guide.

After merging I'll handle [step 5](https://github.com/flutter/flutter/wiki/Tree-hygiene#5-document-the-change-including-clear-documentation-for-migrating-code-with-samples-and-clear-rationales-for-each-change) of the breaking change guide.

**Comment by justinmc** [comment]
Sounds good, thanks!  I'll be ready to migrate any customers that break when this merges.

**Review by MATTYGILO — COMMENTED** [review]
Looks fine

**Pull request merged**
