### PR TITLE
Add module template for Android

### PR DESCRIPTION
**Pull request by mravn-google**
Add a module project template to support adding Flutter to existing Android apps.

Usage is not yet documented as we want to iterate a bit on the design before going public.
```
flutter create -t module my_module
```
Cf #14821

### CODE REVIEW

**Review by szakarias — APPROVED** [review]
LGTM

**Comment by hasonguo** [comment]
I had Switched to the Project directory，when I Run command “flutter create -t module my_module”，it tells me "module" is not an allowed value for option "template". how to do deal with it

**Comment by hasonguo** [comment]
at your android_host_app  project,had error:include_flutter.groovy not found.
and I newed a project,switched to my project path,created flutter module,alse had this problem.
It tells me “include_flutter.groovy not found.”  how to config to deal with it

**Comment by mravn-google** [comment]
The `settings.gradle` file of your host app needs to point out the `include_flutter.groovy` script in the Flutter module. Our example code on the wiki assumes the two are siblings:
```
some/path/the_flutter_module/
some/path/the_host_app/
```
If they are not, you need to modify how to locate the `include_flutter.groovy` script accordingly in your `settings.gradle` script.

**Comment by jonasbark** [comment]
I'm getting the following error when building:

> Cannot open a library at 'FileMapping(from=/Users/[redacted]/Documents/Programmieren/Android/[redacted]/[redacted]_module_flutter_base/.android/Flutter/build/intermediates/flutter/flutter-x86.jar, to=/Users/[redacted]/.gradle/caches/transforms-1/files-1.1/flutter-x86.jar/77ccf32321279b8c89c3dea709a9e700/jetified-flutter-x86.jar)'

If I make the following changes to the .android/build.gradle file...
```
rootProject.buildDir = 'Flutter'
subprojects {
    project.buildDir = "${rootProject.buildDir}/build"
}
```
it will build again but execution fails with "couldn't find "libflutter.so"" crash. 
This might only happen with:

```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by mravn-google** [comment]
@jonasbark Comments on merged PRs are unlikely to receive proper attention, so please file issues if you encounter problems using Flutter.

FWIW, the `.android` folder is for auto-generated scripts/code, and you should not expect it to work after manual editing. If `android.enableJetifier=true` makes the Android Studio Gradle plugin insist on a particular placement of `build/` folders, then we might have to change how the folder is generated by `flutter_tools`.

**Comment by jonasbark** [comment]
Alright - I wasn't sure wether to create new issues or not as it was marked as experimental.

I filed two issues:
https://github.com/flutter/flutter/issues/18940
https://github.com/flutter/flutter/issues/18939

**Comment by justxuemin** [comment]
When i run this command line  'flutter create -t module my_module' that  i get this issue : "module" is not an allowed value for option "template"

**Comment by jonasbark** [comment]
@justxuemin are you using the master channel? is it up to date?

**Pull request merged**
