### PR TITLE
[gen_l10n] to handle arbitrary DateFormat patterns

### LINKED ISSUE #77646: Use DateFormats default constructor for AppLocalizations generator
## Use case

Say we have a text with a date. So far the [i18n generator](https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc/edit#heading=h.9mkycc6qsbea) allows using the `intl` `DateFormat` constructors only. There is no way to use a custom pattern like `DateFormat.yMMMMd().add_jm()` gives you.

## Proposal

Pass the argument given in the arb-files properties to the `DateFormat()`-constructor.

### PR DESCRIPTION
**Pull request by asashour**
Fixes #77646

Use `DateFormat` constructor with any arbitrary pattern. However, I am not sure if it should throw an exception  in some particular case.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by HansMuller — COMMENTED** [review]
The reason we used the DateFormat factory constructors, instead of just allowing the developer to specifying an arbitrary format string, was because it eliminated the possibility of a runtime error due to a bad format string. I agree that it's reasonable to allow developers to specify an arbitrary format string - as an alternative - however I don't think we should stop recognizing the ones that correspond to DateFormat factory constructors.  I assume that most apps, most of the time, will be able to use the formats for which there is a factory constructor.

We want to avoid breaking anything and to encourage developers to continue to use the standard formats when possible. For example you could introduce a placeholder attribute like isCustomFormat, (`"isCustomDateFormat": true`) which would have to be present if format's value was an arbitrary DateFormat string. There are certainly more convenient ways to express this, but we'd prefer that developers only use custom formats when that's necessary. And when they do, they should do so explicitly.

Sorry about all of the direction; hope this makes sense.

**Comment by asashour** [comment]
Thanks a lot for your feedback and detailed guidance.

This would be better, to try help developers to use standard format whenever possible.

**Comment by christopherfujino** [comment]
@asashour what is the current state of this PR?

**Review by HansMuller — APPROVED** [review]
LGTM

**Pull request merged**
