### PR TITLE
Reorder show and setEditingState calls to the IMM

### PR DESCRIPTION
**Pull request by GaryQian**
This ensures `_textInputConnection.show()` is called before `_textInputConnection.setEditingState()`.

This makes it consistent with the order of other platforms, and is aimed at possibly resolving https://github.com/flutter/flutter/issues/41990 (pending confirmation from Samsung).

b/141639086 reports that a possible cause of the Samsung keyboard bugs we are seeing is a reversed call order of onShowInputRequested() and onUpdateSelection(). This change should flip it to the expected order.

In practice, this reorder does not seem to have any impact on Flutter.

### CODE REVIEW

**Review by mklim — COMMENTED** [review]
Code itself LG, but this needs some kind of test.

Edit: Or maybe no, since it's not an impact? Could ask Hixie.

**Comment by GaryQian** [comment]
I think in this case, Flutter itself doesn't really care what order this is called in; both should be valid. This is relevant only when specific implementations of keyboards decide to depend on this behavior.

**Comment by goderbauer** [comment]
Changes to textInputConnection always make me kinda uncomfortable because this part is not very well tested.

If it is important (even for only some platforms) that these calls happen in a certain order we should definitely add a test to ensure that nobody changes this back (by accident or to fix another bug, maybe).

Also, please double check that this doesn't break anything else - especially with textfields that switch the keyboard.

**Comment by GaryQian** [comment]
Added a test verifying TextInput channel call order.

**Review by mklim — APPROVED** [review]
LGTM

**Pull request merged**
