### PR TITLE
(WIP) Proposal to simplify FocusTrap

### LINKED ISSUE #86972: Consider simplifying FocusTrap?
From: https://github.com/flutter/flutter/pull/82575

> If we want this behaviour, why not just put a Focus widget around the route?

> ...but I'm not convinced we want this behaviour. It's not what happens on Windows and macOS as far as I can tell.

> ￼I think this is just something we want on Web, and on Web the behaviour is just that the root of the tree is itself focusable, no need to check whether a tap would have focused a node and all that.

cc @jonahwilliams

### PR DESCRIPTION
**Pull request by justinmc**
This is a proposal to replace FocusTrap with a root Focus instead, in order to:
 * More closely match native behavior.  Only web should lose focus when clicking the background, not desktop.
 * Allow overriding this behavior, like buttons that don't remove focus from text fields (as discussed in https://github.com/flutter/flutter/pull/76072#issuecomment-902187533).

### TODO
 * Read through https://github.com/flutter/flutter/issues/86972 and make sure nothing was missed here.
 * Tap support or just clicks?

| Flutter (this PR) | Native web |
| --- | --- |
| flutter_focus | web_focus |

### Related issues
Fixes https://github.com/flutter/flutter/issues/86972
Unblocks https://github.com/flutter/flutter/pull/76072
Original FocusTrap PR: https://github.com/flutter/flutter/pull/82575
Follow up that fixed clicks on prefix/suffix: https://github.com/flutter/flutter/pull/86041

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 10 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/90240

**Comment by skia-gold** [comment]
Gold has detected about 7 new digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/90240

**Comment by skia-gold** [comment]
Gold has detected about 10 new digest(s) on patchset 6.
View them at https://flutter-gold.skia.org/cl/github/90240

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 7.
View them at https://flutter-gold.skia.org/cl/github/90240

**Comment by skia-gold** [comment]
Gold has detected about 4 new digest(s) on patchset 7.
View them at https://flutter-gold.skia.org/cl/github/90240

**Comment by justinmc** [comment]
Closing this until I have time to return to it.

**Comment by Hixie** [comment]
@justinmc do you remember if this was looking promising or if it ran into some problems?

FWIW, I would definitely support efforts to remove FocusTrap entirely.

**Comment by justinmc** [comment]
I'm going to update this PR and see if tests pass, etc.  I remember really doubting myself that I could make this work with such a simple change, but I can't remember if I specifically ran into any major blockers.

**Comment by justinmc** [comment]
@Hixie Here's the major blocker: the tests don't pass on web because the [onTapDown](https://github.com/flutter/flutter/pull/99434/files#diff-748ff41c8eac8d1b2daddbdc16ae69880172e1790662d957824518e1c1c4e47aR887) is swallowing gestures.  For example, for iOS's swipe back gesture, the [onHorizontalDragUpdate](https://github.com/flutter/flutter/blob/10805ca3fe6bf22bba2454a8c2d26e1bbe2cd2c3/packages/flutter/lib/src/cupertino/route.dart#L643) is never called when the onTapDown is in the tree above it.

I imagine this can be solved with a custom tap gesture detector or something like that?  If I get more time maybe I can figure out something that works.

**Pull request closed without merging**
