### PR TITLE
Remove opt out for CurvedAnimation.

### LINKED ISSUE #145600: CurvedAnimation is leaking.
To repro follow the steps: https://github.com/flutter/flutter/issues/141198#issuecomment-1987383965

### PR DESCRIPTION
**Pull request by polina-c**
Fixes https://github.com/flutter/flutter/issues/145600 

Prerequisite: 

- [x] clean up ~400 leaking tests of CurvedAnimation.

@ValentinVignal , @Dimilkalathiya and @ksokolovskyi 

I highly appreciate your help resolving leaks.
I noticed couple overlaps during last week. I appreciate the effort and do not want it to be less efficient than it could be. How about splitting work? 

Suggested parts:

1. Failures of Windows framework_tests_**libraries**_leak_tracking, from **top** of stdout
2. Failures of Windows framework_tests_**libraries**_leak_tracking, from **bottom** of stdout
3. Failures of Windows framework_tests_**widgets**_leak_tracking, from **top** of stdout
3. Failures of Windows framework_tests_**widgets**_leak_tracking, from **bottom** of stdout

Overlaps still can happen, but with less probability. Feel free to pick a part.

### CODE REVIEW

**Comment by ValentinVignal** [comment]
Great idea, maybe we can split the work once https://github.com/flutter/flutter/pull/146999. For now, most of the leaks are from `CupertinoPageTransition` and `CupertinoFullscreenDialogTransition` and hopefully https://github.com/flutter/flutter/pull/146999 will fix them

**Comment by polina-c** [comment]
> Great idea, maybe we can split the work once #146999 is merged. For now, most of the leaks are from `CupertinoPageTransition` and `CupertinoFullscreenDialogTransition` and hopefully #146999 will fix them

Cool!
I did not realize this PR still fixes some leaks. If it does, should it be reflected in name in addition to janks?
I see this PR is waiting for review. In general, feel free to ping me on GitHub or twitter (PolinaCC) if a PR is waiting for somebody from Google more than one business day.

**Comment by polina-c** [comment]
Number of leaking test libraries:
- Windows framework_tests_**libraries**_leak_tracking: 24
- Windows framework_tests_**widgets**_leak_tracking: 3

Thank you for fixes!

**Comment by Dimilkalathiya** [comment]
It seems we can we only have one issue to fix to close CurvedAnimation chapter 👀

as of now only 3 test files are leaking:-
- `material/dialog_test.dart`
- `cupertino/dialog_test.dart`
- `cupertino/route_test.dart`

Screenshot 2024-05-20 at 10 40 40 PM


Origin of leak for all of them is `CupertinoDialogRoute` in which  `_buildCupertinoDialogTransitions` is using `CurvedAnimation` without any means of disposal

**Comment by polina-c** [comment]
> It seems we can we only have one issue to fix to close CurvedAnimation chapter (after #147823 is merged) 👀
> 
> as of now only 3 test files are leaking:-
> 
> * `material/dialog_test.dart`
> * `cupertino/dialog_test.dart`
> * `cupertino/route_test.dart`

Cool!

**Comment by polina-c** [comment]
Time to celebrate - no remaining leaks of Curved Animation!!!

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
