### PR TITLE
Manual engine roll

### LINKED ISSUE #35291: WebView is sized (0,0) for some pages on Android
This regressed at https://github.com/flutter/engine/pull/9343

Revert PR: https://github.com/flutter/engine/pull/9581

### PR DESCRIPTION
**Pull request by amirh**
The engine haven't rolled for a while, creating a manual roll to include the minimal set of changes needed to revert the https://github.com/flutter/flutter/issues/35291 regression.

```
45b66b722e1275c47dccbe6b002c8e4cb13ea983 Revert " Roll src/third_party/dart b37aa3b036...1eb113ba27 (#9559)" (#9584)
fc1d86b7580bc65a3b816b38d3b4c114079ccdf9 Revert "Avoid a full screen overlay within virtual displays (#9343)" (#9581)
140b2aef5ed381aecc13e262d1e2bb3b70960b3b  Roll src/third_party/dart b37aa3b036...1eb113ba27 (#9559)
94bb7a7ff2a52e9e69b9b4228b5a3ec9fb1e5127 Adds API for retaining intermediate engine layers (#9461)
7d1508d989e682b7fbc1e43db8053e7ded369154 Roll fuchsia/sdk/core/mac-amd64 from cFEtOUFvy2XYSKuSmCMDaMQV8_Y7GOif521L3x86J_4C to n9fZpXVmsbgKZzS8Q2GXxB453q8AbLpfGztsPsq47pMC (#9579)
7a0bbf935599b223352312a20ceabbe2dd2eb3ac Fixed memory leak by way of accidental retain on implicit self (#9329)
```

Fixes: #35291

### CODE REVIEW

**Comment by tvolkert** [comment]
This is running into the same problem that @a-siva is hitting in his Dart roll.

**Comment by tvolkert** [comment]
(and likely the same problem that's blocking the auto-roller)

**Comment by amirh** [comment]
Oops, added one more commit (Siva's revert of the dart roll)

**Review by dnfield — APPROVED** [review]
LGTM

**Pull request merged**
