### PR TITLE
Default child lists to empty lists

### LINKED ISSUE #6591: ScrollableGrid: Omitting optional 'children' parameter returns broken widget
When creating a ScrollableGrid widget, not setting the 'children' parameter gives you the red error widget with the text `NoSuchMethodError: The getter 'length' was called on null. Tried calling: length`

Passing `[]` to this parameter gives you an error-free empty ScrollableGrid widget as expected.

Pretty minor but I'd expect either the children parameter to be required or to be assigned the empty list by default.

### PR DESCRIPTION
**Pull request by abarth**
Fixes #6591

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

**Comment by Hixie** [comment]
Search for `_emptyWidgetList` in basic.dart. We should presumably replace it with inline `const <Widget>[]` everywhere it's used too.

LGTM.

Test maybe?

**Comment by abarth** [comment]
> We should presumably replace it with inline const <Widget>[] everywhere it's used too.

Ok.  I'll do that in a separate patch.

> Test maybe?

I guess I could test it...  I'm not sure it would be such a valuable test though.

**Comment by abarth** [comment]
> > We should presumably replace it with inline const <Widget>[] everywhere it's used too.
> 
> Ok.  I'll do that in a separate patch.

Turns out I did it in this patch because I'm such a great guy.

> > Test maybe?
>
> I guess I could test it...  I'm not sure it would be such a valuable test though.

Alright, I tested that all these classes can be constructed with only required arguments.  Turned up a bug (and a doc opportunity), so I guess it was worthwhile.  :)

**Comment by Hixie** [comment]
:-)

**Pull request merged**
