### PR TITLE
replaced url_stratagy export for non web

### LINKED ISSUE #152490: usePathUrlStrategy() breaks app on non-web platforms
### Steps to reproduce

```
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

void main() async {
  usePathUrlStrategy();
  runApp(const MyApp());
}
```

launch app on any platform that isn't web (macOS was used to produce this issue)

### Actual results

App won't launch

### Expected results

App launches, and this function is a no-op

### Logs

<details open>
<summary>Logs</summary>

```console

import 'dart:ui_web' as ui_web;
       ^
Context: The unavailable library 'dart:ui_web' is imported through these packages:

    package:ffa_app => package:flutter_web_plugins => dart:ui_web

Detailed import paths for (some of) the these imports:

    package:ffa_app/main.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/url_strategy.dart => dart:ui_web
    package:ffa_app/main.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/plugin_event_channel.dart => package:flutter_web_plugins/src/plugin_registry.dart => dart:ui_web
    package:ffa_app/main.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/plugin_registry.dart => dart:ui_web

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.4.1 23E224 darwin-arm64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.91.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 2 categories.


```

</details>

### PR DESCRIPTION
**Pull request by kishan-dhankecha**
This will be useful when importing the `url_stratagy.dart` file from `flutter_web_plugins`, as the current export statement causes non-web platforms to break.

The plugin has a file in the `lib` folder that handles this issue using the conditional export statement. So by adding this patch, the default plugin src file will export the file which has a conditional export statement.

Fixes #152490

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by kishan-dhankecha** [comment]
Hi @darshankawar, @DanTup can you guys review this?

I tried to fix all the checks that were not working but I couldn't figure out this "Linux build_test_1_3" check.

**Comment by DanTup** [comment]
The changes seem reasonable to me, but I think this should be reviewed by someone more familiar with this package than I am. I also wonder if there are any tests for this functionality that could now be enabled to run on non-web (to ensure this library remains compatible for non-web in future)?

As for the bot failure, on https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20build_tests_1_3/32967/overview it says "Step failed (timeout) (retcode: -15)" and the last line of the log is at 29m 56s so I think it hit a 30min timeout. From the timestamps in the log, it doesn't seem stuck and I can't see any obvious single operation taking a long time, so I wonder if this bot has been close to the timeout for a while and it just flaked here, or whether this change really made things much slower. Perhaps someone who has had better visibility of these bots lately will have a better idea (and if so, could re-run it).

**Comment by kishan-dhankecha** [comment]
@DanTup Can you add someone who can have a look into this? I would love to get feedback on how I can make it more future-compatible or if it's even a feasible solution or not.

**Comment by DanTup** [comment]
I'm afraid I don't know who is best to review this, though I saw @yjbanov added a comment about making this kind of change at https://github.com/flutter/flutter/issues/152490#issuecomment-2305368272 so it may warrant some discussion about the change first.

**Comment by mdebbar** [comment]
Thanks for taking the time to create this PR!

The `flutter_web_plugins` package (as the name suggests) is intended to be web-only. People who want to use it can do so with conditional imports.

That said, we made an exception for `package:flutter_web_plugins/url_strategy.dart`. We made that part of the package cross-platform for convenience. But it's a special case that we prefer not to spread to the entire `flutter_web_plugins` package.

In the future, we may want to move `url_strategy.dart` into its own package, potentially in [`flutter/packages`](https://github.com/flutter/packages).

**Pull request closed without merging**
