### PR TITLE
Use unified android sdk+ndk package in ci.yaml

### PR DESCRIPTION
**Pull request by GaryQian**
https://flutter-review.googlesource.com/c/recipes/+/23920 Changes the recipe to use a new CIPD package. This updates the version being passed.

### CODE REVIEW

**Comment by CaseyHillers** [comment]
`version:31v8` doesn't exist on CIPD

**Comment by GaryQian** [comment]
It does, this requires the recipes change to land first, which changes the package being installed to https://chrome-infra-packages.appspot.com/p/flutter/android/sdk/all instead of the flutter_internal version of the package. I'll likely attempt the landing process later at night to prevent breaking the tree for too long.

**Comment by CaseyHillers** [comment]
This shouldn't need a breaking change, but \cc @godofredoc since he seems to have more context

**Comment by godofredoc** [comment]
> This shouldn't need a breaking change, but \cc @godofredoc since he seems to have more context

This is correct, you'll need to land the recipes change first and then this one, none of them are breaking changes.

**Review by godofredoc — APPROVED** [review]
This is now ready to land!

**Review by CaseyHillers — APPROVED** [review]
Thanks for versioning this Gary!

**Pull request merged**
