### PR TITLE
Remove skip clause on tools coverage

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

This does not appear to be picking up changes to the tool

### CODE REVIEW

**Review by dnfield — COMMENTED** [review]
LGTM.

/cc @fkorotkov - is something missing here?

**Comment by fkorotkov** [comment]
What do you mean by "changes to the tool"?

**Comment by dnfield** [comment]
@jonahwilliams may have examples

It seems like `"!changesInclude('./packages/flutter_tools/**/*', '.cirrus.yml', './dev/bots/test.dart')"` was skipping PRs where there were changes uner `packages/flutter_tools/**/*`.

**Comment by fkorotkov** [comment]
Oh! Do you have a link to the build? Would love to investigate why it happened.

**Comment by jonahwilliams** [comment]
See https://github.com/flutter/flutter/pull/34896

**Comment by fkorotkov** [comment]
The issue there was that `changesInclude` function did not support glob with `./` prefixes and wasn't actually returning the correct result. I've added support for such syntax so it should be working as expected. Thanks for reporting!

**Pull request merged**
