### PR TITLE
Add `SeparatedSliverChildBuilderDelegate` and `SliverList.separated()` constructor

### PR DESCRIPTION
**Pull request by navaronbracke**
This PR moves the builder delegate from `ListView.separated()` into its own class and adds a new constructor to `SliverList`, `SliverList.separated()`, which enables using similar functionality in a `CustomScrollView`.

*List which issues are fixed by this PR.*
https://github.com/flutter/flutter/issues/101418

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hi @navaronbracke thanks for contributing! Is there a reason why this is needed? adding more API surface may be unnecessary here. SliverList is intended to be a lower level widget, in contrast to ListView, which is why it has several helper constructors like separated.

**Comment by navaronbracke** [comment]
@Piinks Good point, the main reasoning behind this PR was making the logic of the `SliverChildBuilderDelegate` reusable for both `ListView` and `SliverList`. Now that I think of it, the `SliverList.separated()` constructor adds no additional value. I'll remove that one.

Do you have any other suggestions?

**Review by Piinks — COMMENTED** [review]
Is the `SeparatedSliverChildBuilderDelegate` itself necessary? The logic that the `separated` constructor applies is pretty simple. It seems like a lot of code to add in comparison to the current implementation that is only used by one widget.

**Comment by Reprevise** [comment]
> Is the `SeparatedSliverChildBuilderDelegate` itself necessary? The logic that the `separated` constructor applies is pretty simple. It seems like a lot of code to add in comparison to the current implementation that is only used by one widget.

I'd say it's pretty useful. Sure, the logic might be simple but when you're doing it over and over in several widget files (personally in my project) then it's a handy class to have.

**Comment by navaronbracke** [comment]
You're right, there's really no good way of having the logic for the separated behavior included _without_ adding boilerplate to the framework itself. At the very minimum, you'll end up with a dupe of SliverChildBuilderDelegate. And it's too little of a change to turn it into a package either IMO. 

Guess this is a case where copy-pasta in user code is the only viable option.

**Pull request closed without merging**
