### PR TITLE
Don't use example folder as a project type signal

### LINKED ISSUE #87007: Empty example folder in the root of the app prevents from generating plugin registration
## Steps to Reproduce

1. Run `flutter create bug`.
2. Create an empty folder called example in the new flutter project
3. Run `flutter pub add  shared_preferences` (or any plugin that creates an Android Module)
4. Run `flutter pub get` 

**Expected results:** 
Flutter generates all needed files, including GeneratedPluginRegistrant.java and the application can start/compile run. 

**Actual results:** 
Flutter doesn't generate the file or warn you, the verbose output of flutter pub get shows no error and skips the Found plugin section completely.  The application fails, the Android plugins are not loaded. 

This happens on Linux and Windows (had no time to check Mac), it took me 1.5 Day to find this (and a complete reinstallation of my OS as I first thought I broke something). From my point of view this can (and did for me) lead to a long-running search for the actual cause, if possible one of the tools should at least print an error that it failed/stopped. 

<details>
  <summary>Logs</summary>

End of flutter pub get -v with the empty example folder:
```
[  +14 ms] Running "flutter pub get" in a... (completed in 832ms)
[  +11 ms] "flutter get" took 1,115ms.
[ +103 ms] ensureAnalyticsSent: 100ms
[   +4 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 0
```
Without the folder:
```
[  +14 ms] Running "flutter pub get" in a... (completed in 747ms)
[  +29 ms] Found plugin path_provider_linux at /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +2 ms] Found plugin path_provider_windows at /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.1/
[   +3 ms] Found plugin shared_preferences at /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.6/
[   +1 ms] Found plugin shared_preferences_linux at /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
[   +1 ms] Found plugin shared_preferences_macos at /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
[   +1 ms] Found plugin shared_preferences_web at /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
[   +1 ms] Found plugin shared_preferences_windows at /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
[  +50 ms] Found plugin path_provider_linux at /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
[   +2 ms] Found plugin path_provider_windows at /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.1/
[   +2 ms] Found plugin shared_preferences at /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.6/
[        ] Found plugin shared_preferences_linux at /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
[   +1 ms] Found plugin shared_preferences_macos at /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
[   +1 ms] Found plugin shared_preferences_web at /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
[        ] Found plugin shared_preferences_windows at /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
[  +17 ms] Generating /home/christian/Downloads/a/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +21 ms] "flutter get" took 1,167ms.
[  +97 ms] ensureAnalyticsSent: 93ms
[   +5 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 0
```

```
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.58.2)
[✓] Connected device (2 available)

• No issues found!

```

</details>

### LINKED ISSUE #95540: Presence of a directory named `example` on project top level causes the `flutter drive ..` integration test to fail.
# Issue description (tl;dr): 
Presence of a directory named `example` on project top level causes the `flutter drive ..` integration test to fail.
The integration test which fails 
```shell
  flutter drive --driver=test_driver/integration_test.dart --target=integration_test/screenshot_test.dart
```
is the screenshot test created exactly by following instructions in 
  https://github.com/flutter/flutter/tree/master/packages/integration_test#integration_test. 
The full description of how the project was created and how the test was run is below.
The failure is very specific to the directory name `example`. The contents of the directory does not matter - just 
the presence of such named directory. Directories with other names do not cause this issue.
**This failure prevents library projects to contain a example app, which by convention should be in a directory 
named `example`.**
 
I created a project on Github  https://github.com/mzimmerm/screenshot 
which can be used to fully duplicate the issue.
The project is a rudimentary Flutter example app created from command line,
with added files `test_driver/integration_test.dart` and `integration_test/screenshot_test.dart`
described in https://github.com/flutter/flutter/tree/master/packages/integration_test#integration_test. 
 
# To duplicate the issue

Install the duplication project from Github as follows:

On your local system, from the command line, run the following commands:
    
```shell
   cd ~/tmp # create if not exist
   git clone https://github.com/mzimmerm/screenshot.git
   cd screenshot
   # Note that the project top level does NOT contain a directory named `example`.
   
   # Clean and run the test (which creates a screenshot) from command line
   flutter clean
   flutter emulator --launch "Nexus_6_API_29_2" # Change the emulator name to one on your system 
   sleep 25 # make sure the emulator starts fully
   
   # Run the added Flutter integration (drive) test which creates a screenshot of the app
   flutter drive --driver=test_driver/integration_test.dart --target=integration_test/screenshot_test.dart
   # Expected: screenshot-1.png is created in the project top level
   # Actual:   screenshot-1.png is created in the project top level
   
   # Remove the screenshot to ensure we continue from the same initial state
   rm screenshot-1.png
   # Exit the emulator to ensure we continue from the same initial state.
   
   # Now create an empty directory `example` which will cause the same test to fail
   
   mkdir example
  
   # Run the same test as above again
   # Clean and run the test (which creates a screenshot) from command line
   flutter clean
   flutter emulator --launch "Nexus_6_API_29_2" # Change the emulator name to one on your system 
   sleep 25
   flutter drive --driver=test_driver/integration_test.dart --target=integration_test/screenshot_test.dart
   # Expected: screenshot-1.png is created in the project top level
   # Actual:   Build exception: 
   
   #    ~/tmp/screenshot/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:19: error: package dev.flutter.plugins.integration_test does not exist
   #    flutterEngine.getPlugins().add(new dev.flutter.plugins.integration_test.IntegrationTestPlugin()); ^
   #    1 error
   #    FAILURE: Build failed with an exception. 
  
   # Note: renaming `example` to `example1` or any other name makes the test to work again.
```

## Supplemental information: The project https://github.com/mzimmerm/screenshot on Github was created as follows:

```shell
   cd ~/tmp
   flutter create --template=app screenshot
   # - Edited pubspec.yaml and added test, integration_test and flutter_test
   # - Added directory and file `integration_test/screenshot_test.dart`
   #   as described in https://github.com/flutter/flutter/tree/master/packages/integration_test#integration_test.
   #   (alternative in https://dev.to/mjablecnik/take-screenshot-during-flutter-integration-tests-435k is almost the same 
   #   and also does not work)
   # - Added directory and file `test_driver/integration_test.dart`
   #   as described in https://github.com/flutter/flutter/tree/master/packages/integration_test#integration_test.
   #   (alternative in https://dev.to/mjablecnik/take-screenshot-during-flutter-integration-tests-435k is almost the same 
   #   and also does not work)
   # - Added directory named `example1` for now
   # - Added project `screenshot` on Github
   #     `https://github.com/mzimmerm/screenshot` 
   # 
```
 
## Supplemental information: The result of the first successful test
 
```
     Running "flutter pub get" in screenshot...                         819ms
     Running Gradle task 'assembleDebug'...                             24.1s
     ✓  Built build/app/outputs/flutter-apk/app-debug.apk.
     Installing build/app/outputs/flutter-apk/app.apk...                618ms
     D/EGL_emulation( 4947): eglMakeCurrent: 0xe2a38b00: ver 3 0 (tinfo 0xda90fc90)
     VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:34567/i7VCyPBOS58=/
     VMServiceFlutterDriver: Isolate found with number: 4413108995828315
     VMServiceFlutterDriver: Isolate is paused at start.
     VMServiceFlutterDriver: Attempting to resume isolate
     I/flutter ( 4947): 00:00 +0: screenshot
     VMServiceFlutterDriver: Connected to Flutter application.
     W/Gralloc3( 4947): allocator 3.x is not supported
     D/EGL_emulation( 4947): eglMakeCurrent: 0xda91a120: ver 3 0 (tinfo 0xda90fc10)
     D/EGL_emulation( 4947): eglMakeCurrent: 0xe2a38b00: ver 3 0 (tinfo 0xda90fc90)
     D/EGL_emulation( 4947): eglMakeCurrent: 0xe2a38b00: ver 3 0 (tinfo 0xda90fc90)
     D/EGL_emulation( 4947): eglCreateContext: 0xda91a7e0: maj 3 min 0 rcv 3
     D/EGL_emulation( 4947): eglMakeCurrent: 0xda91a7e0: ver 3 0 (tinfo 0xda90fc90)
     D/EGL_emulation( 4947): eglMakeCurrent: 0xe2a38b00: ver 3 0 (tinfo 0xda90fc90)
     D/EGL_emulation( 4947): eglMakeCurrent: 0xe2a38b00: ver 3 0 (tinfo 0xda90fc90)
     I/flutter ( 4947): 00:01 +1: (tearDownAll)
     W/mple.screensho( 4947): Accessing hidden method
     Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z
     (greylist, linking, allowed)
     I/flutter ( 4947): 00:01 +2: All tests passed!
     All tests passed.
```    
## Supplemental information: The result of the failed test when directory `example` exists:
 
```
    Running "flutter pub get" in screenshot...                       1,864ms
     ~/tmp/screenshot/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:19: error: package dev.flutter.plugins.integration_test does not exist
           flutterEngine.getPlugins().add(new dev.flutter.plugins.integration_test.IntegrationTestPlugin());
                                                                                  ^
     1 error
     
     FAILURE: Build failed with an exception.
     
     * What went wrong:
     Execution failed for task ':app:compileDebugJavaWithJavac'.
     > Compilation failed; see the compiler error output for details.
     
     * Try:
     Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     
     * Get more help at https://help.gradle.org
     
     BUILD FAILED in 10s
     Running Gradle task 'assembleDebug'...                             10.5s
     Gradle task assembleDebug failed with exit code 1
```

### PR DESCRIPTION
**Pull request by stuartmorgan-g**
The code to generate platform files used to use the presence of an
'example' folder to determine whether or not a project was a plugin (in
which case that generation is bypassed). Later, robust detection was
added based on the pubspec.yaml `plugin` key, but the old check was left
in place. This creates false positives where people who add an example
folder to their app project start getting mysterious failures.

Since the pubspec check is definitive, there's no reason to continue to
use the presence of `example` as an indicator at all.

Fixes https://github.com/flutter/flutter/issues/87007
Fixes https://github.com/flutter/flutter/issues/95540

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by stuartmorgan** [comment]
> The code to generate platform files used to use the presence of an
> 'example' folder to determine whether or not a project was a plugin

See https://github.com/flutter/flutter/issues/87007#issuecomment-892689404 for why I'm confident that this was the intent of that check.

**Review by jmagman — APPROVED** [review]
Also fixes https://github.com/flutter/flutter/issues/95540.  I swear I had just commented about this very issue in another bug and now I can't find it.

**Comment by MrBirb** [comment]
@jmagman Were you thinking of #78785?

**Comment by jmagman** [comment]
> @jmagman Were you thinking of #78785?

No, wasn't that one.  Must have been a boring dream...

**Comment by TekExplorer** [comment]
What branch is this in currently?

**Comment by jmagman** [comment]
Available in 2.11.0-0.1.pre.
https://github.com/flutter/flutter/wiki/Where's-my-Commit%3F#finding-the-versions-that-contain-framework-commit-x

**Pull request merged**
