### PR TITLE
More documentation about warm-up frames

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
Fixes https://github.com/flutter/flutter/issues/125326

**Comment by dkwingsmt** [comment]
cc @loic-sharma for having this question.

**Review by loic-sharma — APPROVED** [review]
Thanks for documenting this!

**Comment by loic-sharma** [comment]
FYI, this does not address the problem described by https://github.com/flutter/flutter/issues/125326. As documented on [`FlutterView.render`](https://github.com/flutter/engine/blob/6ec35667c431d424c49c588cb8f0348acefb66ef/lib/ui/window.dart#L330-L332), the Dart app can only call `FlutterView.render` within the scope of `PlatformDispatcher.onBeginFrame` or `PlatformDispatcher.onDrawFrame`.

However, hot reload's warm up frame _does_ call `FlutterView.render` because [`sendFramesToEngine`](https://github.com/flutter/flutter/blob/ad0dbc8de5f98c6b8a374ae1b7e18b32a660d21a/packages/flutter/lib/src/rendering/binding.dart#L481-L490) isn't set to `false`.

For more details from the engine side, see the issue above:

> This eventually calls into `Animator::Render`, which [attempts to reuse the pending producer continuation](https://github.com/flutter/engine/blob/609e71543cb4bc996348ae316ff00a0ed252518c/shell/common/animator.cc#L153-L159). Normally the [producer continuation is created by the vsync](https://github.com/flutter/engine/blob/609e71543cb4bc996348ae316ff00a0ed252518c/shell/common/animator.cc#L81-L95) in `Animator::BeginFrame`. However, in the hot reload scenario we skipped waiting for a vsync, never called `Animator::BeginFrame`, and never created a producer continuation. As a resrult, the pending producer continuation is likely already committed and the scene will be dropped.
>
> You can confirm this behavior by setting a breakpoint here and hot reloading: https://github.com/flutter/engine/blob/609e71543cb4bc996348ae316ff00a0ed252518c/shell/common/animator.cc#L157

**Comment by Hixie** [comment]
@loic-sharma I'm not sure I understand, can you elaborate? This documentation mentions that the warm-up frame will not be rendered, are you saying it should explain why it does not do so in the hot reload case (because the scene will be dropped, etc, as described above) vs other cases? Or are you saying we should change the logic itself?

**Comment by loic-sharma** [comment]
@Hixie We should change the logic itself such that hot reload's warm up frame does not result in calls to `FlutterView.render`, similar to how the first warm up frame does not result in calls to `FlutterView.render`. Rendering a scene outside of a vsync is unsafe and can cause problems in theory.

**Pull request merged**
