### PR TITLE
Material 3 TextField vertical padding

### PR DESCRIPTION
**Pull request by justinmc**
A hardcoded 4.0 value for vertical padding should use 8.0 for Material 3.

| | Material 2 | Material 3 |
| --- | --- | --- |
| Flutter after this PR | Screenshot 2023-03-01 at 4 12 00 PM (same) | Screenshot 2023-03-01 at 4 13 58 PM ✅  |
| Flutter before this PR | Screenshot 2023-03-01 at 4 12 00 PM (same) | Screenshot 2023-03-01 at 4 15 02 PM ❌ |
| Spec | Screenshot 2023-03-01 at 4 19 27 PM Screenshot 2023-03-01 at 4 20 35 PM | [Screenshot 2023-03-01 at 4 18 13 PM](https://m3.material.io/components/text-fields/specs) |

Partial fix for https://github.com/flutter/flutter/issues/114950.

### CODE REVIEW

**Comment by yaymalaga** [comment]
Why is cursor looking way taller in Material 3 than Material 2? Also, the cursor in the spec is much shorter.

**Comment by justinmc** [comment]
True.  We should probably do a more thorough evaluation of all of the dimensions of the field and make sure they match the spec as part of https://github.com/flutter/flutter/issues/114950.

**Comment by Hixie** [comment]
Checked with @justinmc, this is still on his radar.

**Comment by justinmc** [comment]
I'm not feeling confident in my ability to get this working perfectly without major breaking changes after facing similar problems in https://github.com/flutter/flutter/pull/121753.  We might need to build something new and migrate to it.

**Pull request closed without merging**
