### PR TITLE
Make naming consistent across channel APIs

### PR DESCRIPTION
**Pull request by mravn-google**
Addresses https://github.com/flutter/flutter/issues/9173 and https://github.com/flutter/flutter/issues/9250.

Corresponding engine PR: https://github.com/flutter/engine/pull/3574.
Breaking change.

### CODE REVIEW

**Comment by Hixie** [comment]
Please make sure you e-mail flutter-dev about the changes including instructions on how to migrate.

**Comment by mravn-google** [comment]
Sure. I'll update our wiki page: https://github.com/flutter/flutter/wiki/Upgrading-Flutter-projects-from-using-PlatformMessages-to-using-channels

**Comment by Hixie** [comment]
Thanks!

(FYI i added a section to https://flutter.io/design-principles/#handling-breaking-changes that talks about what should be in such e-mails.)

**Comment by Hixie** [comment]
Looks like this broke platform_channel_test_ios, see #9447.

**Pull request merged**
