### PR TITLE
Updated packages to use the nnbd version of the intl package.

### PR DESCRIPTION
**Pull request by darrenaustin**
## Description

Update of all the package to use the nnbd version of the `intl` package.

Removed a dependency in the stocks app on intl_translation that is no longer needed.

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by jonahwilliams** [comment]
@darrenaustin are you going to keep working on this PR?

**Comment by darrenaustin** [comment]
> @darrenaustin are you going to keep working on this PR?

Yeah, I just got stuck pulling the chain of deps with the community gallery test. They need to update their intl dep, which in turn means another package they depend on flutter_localized_locales needs to be updated as well. Still working this through with them, but if this is hold you up or something let me know.

**Comment by darrenaustin** [comment]
Looks like someone already updated the packages to the nnbd intl package so this is no longer needed.

**Pull request closed without merging**
