### PR TITLE
rename Sky to Flutter and add clarifying comment to template

### LINKED ISSUE #7162: Explain SkyApplication in AndroidManifest.xml template and possibly rename it
## Steps to Reproduce

It's got a strange package name for legacy reasons and developers might not know whether they are supposed to customize it.

We can update the package name and deprecate but keep the old one around for legacy purposes.

### PR DESCRIPTION
**Pull request by collinjackson**
Fixes flutter/flutter#7162

Requires merging flutter/engine#3293

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]
lgtm

**Comment by eseidelGoogle** [comment]
Do existing customers need to take any action?  Or are all the old classes still around?

**Comment by eseidelGoogle** [comment]
FYI @tvolkert this will likely require changes to internal apps during the next release.

**Comment by collinjackson** [comment]
It should be backwards compatible.

**Pull request merged**
