### PR TITLE
Updates `AutomatedTestWidgetsFlutterBinding.pump` to support microsecond precision

### LINKED ISSUE #112610: `AutomatedTestWidgetsFlutterBinding.pump` should match engine frame precision
Companion issue fixed by #112609. Please see PR for description :)

_Copied from PR_

The fix is just one line:

image

I have `git blame` and find the bug exist since the first version 7yr ago, and no special comments about why this is introduced so I guess it is but not feature.

IMHO the bug may be written like, the programmer wants to convert DateTime (the `clock.now()`) into a Duration. But then it is forgotten that both are microseconds precision instead of milliseconds precision, and the milliseconds approach is used.

### PR DESCRIPTION
**Pull request by pdblasi-google**
* Updated `AutomatedTestWidgetsFlutterBinding.pump` to use microseconds instead of milliseconds
* Added a test to prevent regression of the microsecond precision
* Fixed a test that incorrectly assumed millisecond precision

Closes #112610

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
In the linked issue, it looks like this was reverted before due to breakages. What was the impact?

The issue also mentioned documentation, should some be added here?

**Comment by pdblasi-google** [comment]
> In the linked issue, it looks like this was reverted before due to breakages. What was the impact?

In the first pass for this issue, the change in precision caused issues with G3 scubas. Those issues seemed to be worse than they were due to many tests having multiple scubas instead of using something like `AnimationSheetBuilder` with a single scuba. At that time, I didn't know how to push through those expected changes, so it got reverted and I put together a breaking change plan for this update.

That plan would be significantly more complicated, and at the end of the day still require updating each problematic scuba/golden, so it can't be easily automated either. This time I'm working with @CaseyHillers internally to give more heads up and have a better chance of getting the scuba changes pushed through.

> The issue also mentioned documentation, should some be added here?

I suspect the documentation mentioned is the breaking change plan? There was a design doc and I think a migration guide that would be outdated at this point.

**Comment by Piinks** [comment]
Ah ok! Thanks for clarifying!

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

**Pull request merged**
