### PR TITLE
Remove flaky non-e2e test

### LINKED ISSUE #73873: multi_widget_construction_perf__timeline_summary timed out
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8858199145548236432/+/steps/run_multi_widget_construction_perf__timeline_summary/0/stdout
```
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [  +23 ms] VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:38693/HWRG-yMgbZA=/
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [ +101 ms] VMServiceFlutterDriver: Isolate found with number: 433950321518587
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [  +79 ms] VMServiceFlutterDriver: Isolate is paused at start.
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [   +1 ms] VMServiceFlutterDriver: Attempting to resume isolate
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [ +401 ms] VMServiceFlutterDriver: Connected to Flutter application.
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [+6629 ms] VMServiceFlutterDriver: waitFor message is taking a long time to complete...
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [+38728 ms] 00:45 [32m+0[0m[31m -1[0m: multi_widget_construction_perf [1m[31m[E][0m[0m
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [   +1 ms]   TimeoutException after 0:00:45.000000: Test timed out after 45 seconds.
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [  +14 ms]   package:test_api/src/backend/invoker.dart 318:28  Invoker._handleError.<fn>
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1178:47                      _rootRun
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1090:19                      _CustomZone.run
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 316:10  Invoker._handleError
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 272:9   Invoker.heartbeat.<fn>.<fn>
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1186:13                      _rootRun
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1090:19                      _CustomZone.run
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 271:38  Invoker.heartbeat.<fn>
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/timer_impl.dart 395:19         _Timer._runTimers
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/timer_impl.dart 426:5          _Timer._handleMessage
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/isolate_patch.dart 184:12      _RawReceivePortImpl._handleMessage
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [  +22 ms] 00:46 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [   +2 ms] Unhandled exception:
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [        ] Dummy exception to set exit code.
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [  +69 ms] executing: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY22465W9K shell am force-stop com.example.macrobenchmarks
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [+1032 ms] executing: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY22465W9K uninstall com.example.macrobenchmarks
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [ +409 ms] Success
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [   +5 ms] executing: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY22465W9K forward --list
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [  +10 ms] Exit code 0 from: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY22465W9K forward --list
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [        ] ZY22465W9K tcp:46197 tcp:41863
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [   +4 ms] executing: /opt/s/w/ir/cache/android/platform-tools/adb -s ZY22465W9K forward --remove tcp:46197
[multi_widget_construction_perf__timeline_summary] [STDOUT] stdout: [  +11 ms] "flutter drive" took 186,346ms.
[multi_widget_construction_perf__timeline_summary] [STDOUT] stderr: [  +10 ms] 
```

### PR DESCRIPTION
**Pull request by liyuqian**
Fixes https://github.com/flutter/flutter/issues/73873

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
Removing this sounds good to me, once the merge conflict and `Could not find an option named "results-file".` error is fixed(?).

**Comment by christopherfujino** [comment]
I suspect rebasing off of upstream will fix the `Could not find an option named "results-file".` error. This is a new flag that was added to the devicelab runner.

**Comment by jmagman** [comment]
> I suspect rebasing off of upstream will fix the `Could not find an option named "results-file".` error. This is a new flag that was added to the devicelab runner.

He's right, rebase past https://github.com/flutter/flutter/pull/72765 your parent is even older.

**Comment by liyuqian** [comment]
Wow, things changed a lot. Rebased :)

**Comment by christopherfujino** [comment]
> Wow, things changed a lot. Rebased :)

Welcome back :)

**Comment by jmagman** [comment]
TAP failure not related, marking as good.

**Comment by jmagman** [comment]
Actually FRoB seems mad and `setGitHubCheckToPass` isn't working, just merging this fella.

**Pull request merged**
