### PR TITLE
Use package:vm_service instead of json_rpc_2

### PR DESCRIPTION
**Pull request by dnfield**
And generally simplify the deps of fuchsia_remote_debug_protocol. This also allows dropping web_socket_channel.

Additionally:

- Drop the flutter_driver dep since it was only used for an example. If we really want to keep examples here, we should make a proper example package so that these dependencies don't leak to consumers (and to avoid having cyclic dependencies between the packages).
- Drop the flutter_test package, which not only was incorrectly listed as a direct dep, it just wasn't necessary - the test(s) were fine as package:test tests.

AFAICT, the real use of this is covered by our Fuchsia driver tests. @gw280, @blasten, or @iskakaushik can hopefully confirm that.

### CODE REVIEW

**Comment by dnfield** [comment]
I'm really not quite sure why this is even separate from flutter_driver itself. I can't find any usage of it in the Fuchsia tree or internally.

**Review by jonahwilliams — COMMENTED** [review]
In terms of changes, this is great! LGTM

Do we know what tests would fail if they were relying on the particulars of this package API? This is my only concern

**Comment by dnfield** [comment]
I'm working with some Fuchsia folks to verify this change doesn't break attach on Fuchsia.

**Comment by dnfield** [comment]
@chaselatta has confirmed that this still works for Fuchsia attach/tunnel use cases. Going to land this.

**Pull request merged**
