### PR TITLE
Handle breaking changes in leak_tracker.

### PR DESCRIPTION
**Pull request by polina-c**
New version of leak_tracker finds new leaks. 
This PR fixes some of them and replaces testWidgetsWithLeakTracking with testWidgets for others.

@christopherfujino , can you add autosubmit after signing off?

### CODE REVIEW

**Comment by christopherfujino** [comment]
@polina-c looks like you have CI failures

**Comment by polina-c** [comment]
@christopherfujino 

It seems I fixed all of them. At least they pass locally. If they fail on bots, it sill stop autosubmit.

**Comment by polina-c** [comment]
We need this PR to be merged: https://github.com/dart-lang/leak_tracker/pull/117

**Comment by polina-c** [comment]
It seems everything is resolved.

**Comment by polina-c** [comment]
Handling merge conflicts.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
