### PR TITLE
Add a splash screen to flutter gallery

### PR DESCRIPTION
**Pull request by xster**
Can be submitted after the next engine roll

### CODE REVIEW

**Comment by Hixie** [comment]
The assets should be in the asset repo, not this repo.

**Comment by xster** [comment]
Is it https://flutter.googlesource.com/gallery-assets? Is it possible for native code to refer to assets in dart depedencies?

**Comment by Hixie** [comment]
Yes, that's the one.

I presume we can set the paths to point to the right place. If we can't we certainly should make it possible, I doubt that we have the only example of an app whose assets are in a separate package.

**Comment by xster** [comment]
Just to be sure, this is for native assets like the launch icon and splash screen, not general assets used by flutter inside the app.

**Comment by Hixie** [comment]
Right.

**Comment by xster** [comment]
Hard to do the symlinking we talked about and find out the location of the assets in .pub-cache without adding some custom logic into the flutter tools for creating the symlinks. Dropping this for now.

**Pull request closed without merging**
