### PR TITLE
Move Point to Offset

### PR DESCRIPTION
**Pull request by Hixie**
I recommend reviewing the commits one at a time. Some need more study than others.

I'll send an e-mail before landing this.

Right now this is blocked on fixing the regression caused by https://github.com/flutter/engine/pull/3571.

### CODE REVIEW

**Comment by Hixie** [comment]
(Note, this depends on https://github.com/flutter/engine/pull/3567.)

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
Fixes https://github.com/flutter/flutter/issues/6794

**Comment by Hixie** [comment]
I plan to land this Monday once I've gotten Fuchsia ready as well.

**Comment by Hixie** [comment]
This will land when Travis goes green.

**Pull request merged**
