### PR TITLE
Always use the testbed in web_test.dart so `environment` is populated.

### PR DESCRIPTION
**Pull request by eyebrowsoffire**

### CODE REVIEW

**Review by loic-sharma — APPROVED** [review]

**Comment by christopherfujino** [comment]
@eyebrowsoffire can you link to a failing build if you have one handy?

**Comment by eyebrowsoffire** [comment]
Here is one of the recent postsubmit failures: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_tests_general/9580/overview

**Comment by CaseyHillers** [comment]
> @eyebrowsoffire can you link to a failing build if you have one handy?

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20tool_tests_general/9668/overview is an example failing build.

Merging manually on red to unblock the tree.

**Comment by christopherfujino** [comment]
> Here is one of the recent postsubmit failures: https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_tests_general/9580/overview

Thanks.

**Pull request merged**
