### PR TITLE
[flutter_test] Adds method to mock EventChannels

### PR DESCRIPTION
**Pull request by Rexios80**
Reland of https://github.com/flutter/flutter/pull/123726 fixing the issues mentioned here https://github.com/flutter/flutter/pull/124401

### CODE REVIEW

**Comment by Rexios80** [comment]
@goderbauer @pdblasi-google

**Review by pdblasi-google — APPROVED** [review]
LGTM

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by Rexios80** [comment]
@goderbauer Do you need to add the autosubmit label again?

**Comment by Rexios80** [comment]
In case anyone wants to use this code before it's released to stable, I copied this code into the [mock_event_channel](https://pub.dev/packages/mock_event_channel) package. When this PR is released to stable, just remove that package.

**Pull request merged**
