### PR TITLE
Remove //examples/widgets

### PR DESCRIPTION
**Pull request by abarth**
Most of the remaining widget examples are actually manual tests. This patch
moves them into //packages/flutter/test/manual. A couple are examples of using
services, which I've moved to //examples/layers/services. The remainder are
out-dated and are removed by this patch.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

**Comment by Hixie** [comment]
lgtm.

paging @krisgiesing, @HansMuller, @collinjackson whose examples are affected.

**Comment by collinjackson** [comment]
thanks for the heads-up

**Comment by HansMuller** [comment]
AFAIK there's no test for IndexedStack yet. Can we move that to the manual tests directory instead of deleting it?

**Comment by HansMuller** [comment]
Likewise for scrollbar.dart. Since it demos that scrollbars don't work anymore...

**Comment by krisgiesing** [comment]
resolution_awareness.dart is also a manual test, can we move rather than deleting?

**Comment by abarth** [comment]
Is there some reason we can't make scrollbar.dart and resolution_awareness.dart into test that are run automatically?  Manual tests don't provide much value unless they are used frequently.

**Comment by Hixie** [comment]
Yeah, I don't think anything should count as a manual test unless someone really is regularly running them. (So, for example, I regularly run and tweak stocks and card_collection.)

**Comment by krisgiesing** [comment]
I can convert it, but can you leave the manual test in place until I do?

**Comment by abarth** [comment]
I'm not in a rush to land this pull request.  It's just trying to clean things up.  I'll leave it open here.

**Comment by krisgiesing** [comment]
OK, thanks.

**Comment by Hixie** [comment]
We discussed this further and concluded that stocks, card_collection, and the other manual tests should go to dev/manual_tests.

When you do this, don't forget to update "flutter upgrade-packages" to also include "dev/manual_tests/*/".

**Comment by krisgiesing** [comment]
LGTM for removal of resolution_awareness.dart.

**Comment by abarth** [comment]
Thanks!  /me need to rebase this patch.

**Pull request merged**
