### PR TITLE
Fixing patch for coming breaking change in HttpClientRequest

### PR DESCRIPTION
**Pull request by zichangg**
[The breaking change](https://dart-review.googlesource.com/c/sdk/+/147339) will be landed in dart-sdk. This patch will update the test accordingly and stop the breakage.

### CODE REVIEW

**Comment by zanderso** [comment]
See also: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/src/testbed.dart#L311

**Comment by zichangg** [comment]
@zanderso Can you take a look? Because flutter-roll and dart-roll are separate and probably won't be able to go to g3 at the same time. I pushed another commit which added an noSuchMethod() in the class. We can land this pr first to prevent breakage in g3.

**Comment by zanderso** [comment]
If this is strictly an analyzer lint, and doesn't trigger a compilation failure, then I would prefer disabling the lint for the affected lines rather than adding `noSuchMethod`s. @jonahwilliams wdyt?

**Comment by jonahwilliams** [comment]
Yeah, I think you can add the method with the override warning ignored. Then clean up after the roll.

**Comment by zichangg** [comment]
What is the correct syntax? I didn't find a proper item in linter's rules. `ignore: annotate_overrides`?
g3 complained:
ERROR: third_party/dart/flutter_test/lib/src/_binding_io.dart:208
Missing concrete implementation of 'HttpClientRequest.abort'. #non_abstract_class_inherits_abstract_member

**Comment by jonahwilliams** [comment]
`ignore: override_on_non_overriding_member` for flutter,

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
