### PR TITLE
[devicelab] remove globals and dependency tracking from technical debt

### PR DESCRIPTION
**Pull request by jonahwilliams**
Dependencies are now tracked more indirectly be the allowlist.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
(this will also fix the build)

**Comment by jonahwilliams** [comment]
We also not been using the global tracking

**Review by zanderso — APPROVED** [review]
How far did we get?

**Comment by jonahwilliams** [comment]
Thousands, but still working on it :)

**Comment by jonahwilliams** [comment]
Landing to fix tree

**Comment by zanderso** [comment]
> Landing to fix tree

How did these break the tree?

**Comment by jonahwilliams** [comment]
```
[technical_debt__cost] [STDOUT] stdout: Downloading video_player_web 2.0.0...
[technical_debt__cost] [STDOUT] stdout: Downloading video_player_platform_interface 4.1.0...
[technical_debt__cost] [STDOUT] stdout: Downloading url_launcher_windows 2.0.0...
[technical_debt__cost] [STDOUT] stdout: Downloading url_launcher_web 2.0.0...
[technical_debt__cost] [STDOUT] stdout: Downloading url_launcher_platform_interface 2.0.2...
[technical_debt__cost] [STDOUT] stdout: Downloading url_launcher_macos 2.0.0...
[technical_debt__cost] [STDOUT] stdout: Downloading url_launcher_linux 2.0.0...
[technical_debt__cost] [STDOUT] stdout: Downloading connectivity_platform_interface 2.0.1...
[technical_debt__cost] [STDOUT] stdout: Downloading connectivity_macos 0.2.0...
[technical_debt__cost] [STDOUT] stdout: Downloading connectivity_for_web 0.4.0...
[technical_debt__cost] [STDOUT] stdout: Downloading flutter_gallery_assets 1.0.2...
[technical_debt__cost] [STDOUT] stdout: Downloading shrine_images 1.1.2...
[technical_debt__cost] [STDOUT] stdout: Downloading video_player 2.1.1...
[technical_debt__cost] [STDOUT] stdout: Downloading url_launcher 6.0.3...
[technical_debt__cost] [STDOUT] stdout: Downloading connectivity 3.0.3...
[technical_debt__cost] [STDOUT] stdout: Changed 86 dependencies!
[technical_debt__cost] [STDOUT] stderr: pub failed (65; The pubspec.lock file has changed since the .dart_tool/package_config.json file was generated, please run "pub get" again.)
[technical_debt__cost] [STDOUT] "/b/s/w/ir/k/recipe_cleanup/tmp8rHtS8/flutter sdk/bin/flutter" exit code: 65
[technical_debt__cost] [STDERR] Task failed: Executable "/b/s/w/ir/k/recipe_cleanup/tmp8rHtS8/flutter sdk/bin/flutter" failed with exit code 65.
```

Something I changed in update-packages broke an assumption of transitive-closure, but only in this test. Since we don't use it..

**Pull request merged**
