### PR TITLE
Roll Engine from dc1dba505c33 to a5718ab3c33b (9 revisions)

### PR DESCRIPTION
**Pull request by engine-flutter-autoroll**
https://github.com/flutter/engine/compare/dc1dba505c33...a5718ab3c33b

2022-03-01 skia-flutter-autoroll@skia.org Roll Dart SDK from c3e3126a598b to 34a5563af80d (6 revisions) (flutter/engine#31734)
2022-03-01 skia-flutter-autoroll@skia.org Roll Skia from 5deac304821b to c3e7a2a00b0a (3 revisions) (flutter/engine#31732)
2022-03-01 skia-flutter-autoroll@skia.org Roll Fuchsia Linux SDK from _mwyhkd9H... to 7rB0Yrprs... (flutter/engine#31731)
2022-03-01 skia-flutter-autoroll@skia.org Roll Fuchsia Mac SDK from qGsRXn7-D... to RIOZP5nXz... (flutter/engine#31730)
2022-03-01 godofredoc@google.com Standardize embedder archive name. (flutter/engine#31693)
2022-03-01 30870216+gaaclarke@users.noreply.github.com added dart plugin registrant test executables to run_tests.py (flutter/engine#31726)
2022-03-01 skia-flutter-autoroll@skia.org Roll Skia from 1fc0c1c0f8af to 5deac304821b (2 revisions) (flutter/engine#31725)
2022-03-01 godofredoc@google.com Standardize the embedder file name. (flutter/engine#31723)
2022-02-28 30870216+gaaclarke@users.noreply.github.com Started looking for the dart plugin registrant at runtime  (flutter/engine#31418)

Also rolling transitive DEPS:
  fuchsia/sdk/core/linux-amd64 from _mwyhkd9Hjv0 to 7rB0YrprsDcI
  fuchsia/sdk/core/mac-amd64 from qGsRXn7-DuBr to RIOZP5nXz9S8

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/flutter-engine-flutter-autoroll
Please CC zra@google.com on the revert to ensure that a human
is aware of the problem.

To file a bug in Flutter: https://github.com/flutter/flutter/issues/new/choose

To report a problem with the AutoRoller itself, please file a bug:
https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 9.
View them at https://flutter-gold.skia.org/cl/github/99346

**Comment by Piinks** [comment]
It looks like this is blocked on a known caching issue: https://bugs.chromium.org/p/skia/issues/detail?id=12645&q=component%3AGold&can=2

The dashboard shows no image changes, but the endpoint we hit to check says there are images that are untriaged: https://flutter-gold.skia.org/json/v1/changelist_summary/github/99346

This can either be landed manually, or a new PR can be opened.

**Comment by Piinks** [comment]
cc @kjlubick above ^

**Review by zanderso — APPROVED** [review]

**Comment by kjlubick** [comment]
I manually triggered a cache clear (basically a rolling reboot of the flutter frontend)

**Pull request merged**
