### PR TITLE
Pass --no-version-check to tool app-jit snapshot training.

### PR DESCRIPTION
**Pull request by zanderso**

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
Argh

**Comment by christopherfujino** [comment]
Btw, I was debugging something similar to this with goderbauer this morning, I think he's gonna file a bug.

**Comment by christopherfujino** [comment]
(that is, if the issue you're trying to fix here is that during app-jit training we're crashing calculating the version because of missing tags)

**Comment by zanderso** [comment]
No I was looking at https://github.com/flutter/flutter/issues/145158, but actually the cause of that issue is different. I was going to abandon this PR, but if it's useful for a different issue, I can add the flag to the `.bat` script, and land it.

**Comment by christopherfujino** [comment]
> No I was looking at #145158, but actually the cause of that issue is different. I was going to abandon this PR, but if it's useful for a different issue, I can add the flag to the `.bat` script, and land it.

actually, let's abandon this. this looks like it's calling the tool without args, which IIRC will not hit the version check code.

**Comment by kevmoo** [comment]
Can delete branch @zanderso ?

**Comment by christopherfujino** [comment]
deleted (Zach can undelete if he really needs it)

**Pull request closed without merging**
