### PR TITLE
Bump dart SDK to 1.17.0-dev.6.

### PR DESCRIPTION
**Pull request by pq**
New dev build with more fixes and (fingers-crossed) speed-ups.

@Hixie @abarth

### CODE REVIEW

**Comment by abarth** [comment]
Travis is mad.  I retried it.

**Comment by pq** [comment]
> Travis is mad. I retried it.

Still mad (timed out downloading)...  Kicking again.

**Comment by pq** [comment]
Hmmmm.  I keep bumping and it keeps breaking even though I can grab it fine locally.  I wonder if travis is failing with a timeout?

@sethladd, @devoncarew, @whesse : any ideas?

**Comment by pq** [comment]
Adding @Hixie since I see he did some work on setup.sh and that's the bit that's getting killed.

**Comment by devoncarew** [comment]
Are you sure this version is available? I only see `1.17.0-dev.4.1` available for the mac. Perhaps 1.17.0-dev.5.0 isn't fully rolled out - can you hit the d/l url manually?

**Comment by pq** [comment]
> Are you sure this version is available? I only see 1.17.0-dev.4.1 available for the mac. Perhaps 1.17.0-dev.5.0 isn't fully rolled out - can you hit the d/l url manually?

Yeah, it's there and I can download it locally.  Not sure why it's not on the [download site](https://www.dartlang.org/downloads/archive/) yet but I do know sometimes there's a bit of a lag...  Don't expect that's related but maybe!

**Comment by whesse** [comment]
It is built (though not completely - some dartium builds failed), but not
released (promoted to the release channels, like the download site,
homebrew, linux package repo, etc.).  I'll release it once I get the other
dartium builds done.

If you are relying on the arm build, note that the new build on arm is
using glibc 2.16.  We are looking into reverting that to an earlier glibc.

On Thu, May 26, 2016 at 9:32 AM, Phil Quitslund <notifications@github.com>
wrote:

> Are you sure this version is available? I only see 1.17.0-dev.4.1
> available for the mac. Perhaps 1.17.0-dev.5.0 isn't fully rolled out - can
> you hit the d/l url manually?
>
> Yeah, it's there and I can download it locally. Not sure why it's not on
> the download site <https://www.dartlang.org/downloads/archive/> yet but I
> do know sometimes there's a bit of a lag... Don't expect that's related but
> maybe!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/flutter/flutter/pull/4203#issuecomment-221924244>
>



-- 
William Hesse

**Comment by pq** [comment]
Thanks @whesse!

It's worth adding that when I say locally I do mean on my mac whereas travis is fetching for linux-64.  if the build is incomplete, and the linux 64 build isn't ready that would explain it!

The SDK update script is [here](https://github.com/flutter/flutter/blob/master/bin/cache/update_dart_sdk.sh).

**Comment by pq** [comment]
Kicked again after the latest re-roll and it looks like we're green.

https://travis-ci.org/flutter/flutter/builds/133227461

Cheers @whesse!

**Comment by abarth** [comment]
LGTM

**Pull request merged**
