### PR TITLE
Keep indeterminate RefreshProgressIndicator spinning until end of time

### LINKED ISSUE #17923: RefreshProgressIndicator stops spinning after ~5-6 seconds
After a certain amount of time, `RefreshProgressIndicator`s stop spinning and reset to their initial state. This is inconsistent with the behavior of `CircularProgressIndicator`. Our UX designer wants us to use `RefreshProgressIndicator` in many places in our app, so we need this to be fixed for launch.

This is broken if you're using a `RefreshIndicator` too.

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
      home: new Scaffold(
          appBar: new AppBar(
            title: new Text('Test app'),
          ),
          body: _body)));
}

Widget get _body {
  return new RefreshIndicator(
    onRefresh: () => new Future.delayed(const Duration(seconds: 10)),
    child: new ListView(
      physics: const AlwaysScrollableScrollPhysics(),
      children: <Widget>[
        new Container(height: 16.0),
        new Center(child: new CircularProgressIndicator()),
        new Container(height: 16.0),
        new Center(child: new RefreshProgressIndicator()),
      ],
    ),
  );
}
```

See low FPS gif below. I've also attached the original video.

ezgif-3-dd64680a47

[demo.mp4.zip](https://github.com/flutter/flutter/files/2040926/demo.mp4.zip)

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/17923.

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM
lol

**Review by cbracken — APPROVED** [review]

**Comment by HansMuller** [comment]
`await tester.pump(const Duration(days: 9999))`

NICE

**Comment by tvolkert** [comment]
This is causing failures when trying to roll it into Google:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
pumpAndSettle timed out

When the exception was thrown, this was the stack:
#0      WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:291:11)
<asynchronous suspension>
#3      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:44)
#4      WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:287:27)
...
```

Is this the fault of the test, or should this be rolled back?

**Comment by Hixie** [comment]
Paste more of the stack?

**Comment by Hixie** [comment]
At a guess, it's the fault of the test. It probably starts a refresh and doesn't end it.

**Comment by tvolkert** [comment]
It's customer:mulligan code - ping me for the link to the next stack frame (it's in the test)

**Comment by goderbauer** [comment]
I'll take a look at this tomorrow.

**Pull request merged**
