### PR TITLE
Reduce potential collisions from Gold RNG

### LINKED ISSUE #50121: Gold flake: gold client not ready
Originating from #49956 
This passed on a re-run.

https://cirrus-ci.com/task/6635508625309696

```
mp/flutter sdk/packages/flutter/test/cupertino/text_field_test.dart: Cupertino cursor golden (TargetPlatform.macOS)                                                         
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _Exception was thrown while running async test code:
Exception: Unexpected Gold tryjobAdd failure.
Tryjob execution for golden file test cupertino.text_field_cursor_test.cupertino_macos.1.png failed
for
a reason unrelated to pixel comparison.
Debug information for Gold:
stdout:
stderr: ERROR: logging before flag.Parse: I0204 01:11:34.738559   64806 auth.go:364] auth.go:364
Read from file /private/tmp/flutter
sdk/bin/cache/pkg/skia_goldens4761/packages/flutter/test/cupertino/serviceAccount.json
Error running command: ''gold client not ready: Gold results fields invalid: Received nil pointer
for GoldResult. At jsonio.go:197 goldclient.go:468 goldclient.go:301 goldclient.go:291
cmd_imgtest.go:338 command.go:835 command.go:919 main.go:42 proc.go:203 asm_amd64.s:1357''
When the exception was thrown, this was the stack:
#0      SkiaGoldClient.tryjobAdd (package:flutter_goldens_client/skia_client.dart:371:9)
<asynchronous suspension>
#1      _AuthorizedFlutterPreSubmitComparator.compare (package:flutter_goldens/flutter_goldens.dart:374:23)
<asynchronous suspension>
#2      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:82:57)
<asynchronous suspension>
#3      AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:924:22)
#6      AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:922:26)
#7      MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:72:20)
#9      MatchesGoldenFile.matchAsync (package:flutter_test/src/_matchers_io.dart:52:28)
#10     _expect (package:test_api/src/frontend/expect.dart:116:26)
#11     expectLater (package:test_api/src/frontend/expect.dart:75:5)
#12     expectLater (package:flutter_test/src/widget_tester.dart:385:10)
#13     main.<anonymous closure> (file:///private/tmp/flutter%20sdk/packages/flutter/test/cupertino/text_field_test.dart:523:11)
#26     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1102:17)
#28     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1090:35)
(elided 31 frames from class _FakeAsync, dart:async, dart:async-patch, and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

### PR DESCRIPTION
**Pull request by Piinks**
Maybe fixes https://github.com/flutter/flutter/issues/50121

Gold does not support threading, so we have a rng to randomize the directories Gold is being run out of in pre and post submit golden file testing in the framework. This currently may not be random enough. The flake reported in #50121 may be collisions caused by this.

This change tweaks the seed to not only use the clock, but also the swarming task id. Will continue monitor to see if flake persists.

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: part of a test

I guess you could test that the format is correct.

If what you're trying to do is create a unique directory on the local machine, though, why not use the createTempSync API?

**Comment by skia-gold** [comment]
Gold has detected about 403 untriaged digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/81792

**Comment by Piinks** [comment]
Whoops. Ok I changed something that I shouldn't have, and will most likely need to tweak further. Marking WIP in the meantime.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
Looks like the checks are unhappy, though.

**Comment by Piinks** [comment]
The G testing failure is a flake. Setting to green.

**Pull request merged**
