### PR TITLE
Add loading indicator web template

### LINKED ISSUE #85405: Enhancing the web index.html template
## Use case

The web template currently has no loader.

## Proposal

I suggest adding a default loader in the `index.html` that can be then changed by the user if needed.

If that is interesting, I can do it.

### PR DESCRIPTION
**Pull request by YazeedAlKhalaf**
This adds a loading indicator to the web template. It showed when there is no flutter app loaded. Once the Flutter app is loaded, the loading indicator is not visible to the user.

GIF showing the design of the loading indicator:
123546889-31151280-d767-11eb-9e5d-a79427f3862d

closes #85405 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by bernaferrari** [comment]
The way you did it, wouldn't the loader be alive after Flutter app has loaded? Is there any benchmark to see if it doesn't affect anything?

**Comment by christopherfujino** [comment]
Note: that this PR (https://github.com/flutter/flutter/pull/83530) created a merge conflict with this PR.

**Comment by YazeedAlKhalaf** [comment]
@bernaferrari Yup you're right, it would stay spinning all the time even after the app loads.

So now the loader is there with its styling. We need to make it appear only when the flutter app is loading and remove it once the app paints the first frame. I am not sure how, to be honest, but will try to dig in to find a way.

**Comment by jonahwilliams** [comment]
I'm not sure whether this makes sense from a product perspective, adding @yjbanov for thoughts

**Comment by YazeedAlKhalaf** [comment]
I suggest using the loading indicator that flutter photobooth used.
It looks cool and is material design compliant too.

Or do you think keeping it simple is better?

https://github.com/flutter/photobooth/blob/main/web/index.html#L56

**Comment by zanderso** [comment]
@yjbanov any thoughts?

**Comment by yjbanov** [comment]
I think we should provide API for implementing custom loading indicators and/or splash screens, and provide an example that developers could learn from. The gallery should probably use one too. It would also be great if one of the `flutter create` templates added one. Whether it should be in the _default_ template, I'm not sure. This is more of a product question, cc @mariamhas. It's also not clear to me what style the default loading indicator should use, or whether it matters at all. If it's intended to be a starting point for developers to hack from and customize, then maybe the style doesn't matter.

Aside from that, I think we lack API for implementing a proper loading indicator. For example, this implementation, as pointed out by @bernaferrari, will stay in the DOM tree forever. We could have the engine emit a "first frame rendered event" JavaScript event that the app could listen to and implement a transition from the loading screen to the app screen. We should also provide a JS API for controlling the visibility of the Flutter app, so one could implement different transitions, such as cross-fade.

This probably has enough devils in the detail to warrant a design doc before we jump into coding.

**Comment by yjbanov** [comment]
I think we should not do this before we add JS API and before we make decision on styling, defaults, etc. So I'm closing this PR. However, this is a good example, and could be a useful blog post. I would add loading indicator removal after the app renders its first frame (which can be done by using [addPostFrameCallback](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html)).

**Comment by YazeedAlKhalaf** [comment]
> I think we should not do this before we add JS API and before we make decision on styling, defaults, etc. So I'm closing this PR. However, this is a good example, and could be a useful blog post. I would add loading indicator removal after the app renders its first frame (which can be done by using [addPostFrameCallback](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html)).

Oh thanks for the suggestion @yjbanov. It makes so much sense.

Will make a blog post. 🚀

**Pull request closed without merging**
