### PR TITLE
Fix frameworks added to bundle multiple times instead of lipo

### PR DESCRIPTION
**Pull request by knopp**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by knopp** [comment]
@dcharkes, I updated test to actually check lipoing multiple architectures. I did have to introduce `_FatNativeAssetsBuildRunner`, which doesn't look very nice. Maybe `FakeNativeAssetsBuildRunner` could be modified to accept `(target) => result` getter as `buildResult` instead of plain result?

**Comment by dcharkes** [comment]
I believe the iOS implementation might have the same issue.

**Comment by dcharkes** [comment]
> @dcharkes, I updated test to actually check lipoing multiple architectures.

❤️  (Thanks for doing what I should have done before! 🤓 )

> I did have to introduce `_FatNativeAssetsBuildRunner`, which doesn't look very nice. Maybe `FakeNativeAssetsBuildRunner` could be modified to accept `(target) => result` getter as `buildResult` instead of plain result?

Both of these are fakes, I wouldn't worry about the setup.
If it doesn't complicate the other places we can fold it into the existing fake. (e.g. if the function is passed run it, and otherwise return the predefined list).
But it's also fine to have two fakes instead of one fake.  In that case, maybe name the new one `_FakeNativeAssetsBuildRunner` and the other one `ConstFakeXX` (e.g. the constness is that the responses are hardcoded).

**Comment by knopp** [comment]
@dcharkes, I did that [here](https://github.com/flutter/flutter/pull/144688/commits/046bfdb28e993898197cf3f45de96f86ba3b9107), but I'm quite sure about it. Maybe the old one should have remained `FakeNativeAssetsBuilder` and the new one have different name? Not sure. Your call.

**Comment by dcharkes** [comment]
How does the code look like if you merge the functionality into one fake?

e.g. `return (onBuild!=null) ? onBuild(...) : buildResult;`

**Comment by knopp** [comment]
> How does the code look like if you merge the functionality into one fake?
> 
> e.g. `return (onBuild!=null) ? onBuild(...) : buildResult;`

[Quite a lot better](https://github.com/flutter/flutter/pull/144688/commits/2616bd3ceb382cc5864a8dda315d2a00b634be5b) I'd say.

**Comment by knopp** [comment]
@dcharkes, is anything else needed for the PR? should be ready for review.

**Review by dcharkes — APPROVED** [review]
Looks I left off halfway through the review.

LGTM!

**Comment by dcharkes** [comment]
Thanks @knopp!

**Pull request merged**
