### PR TITLE
Remove obsolete work around for shadow drawing

### LINKED ISSUE #130737: Potentially obsolete use of transparent rectangles to fix bounds issues
At one point there was an issue with Skia bounds of shadow operations and so the code was sprinkled with calls to draw a transparent rect of the proper bounds to work around the issue.

Now that we are using DisplayList internally instead of SkPictureRecorder, the bounds are correct without the workarounds (also, it is likely that Skia fixed that bug a long time ago and so it was already obsolete even before DisplayList). These code snippets should be removed.

One example: https://github.com/flutter/flutter/blob/0df4496cdb50c4b7d6c42d461c46b3f4c2029d95/packages/flutter/lib/src/rendering/proxy_box.dart#L2137

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/130737.

### CODE REVIEW

**Review by flar — APPROVED** [review]
Looks very similar to another that we removed before. There may be scuba diffs with this...

**Comment by flar** [comment]
You can see the history on the prior fix here: https://github.com/flutter/flutter/pull/127052

It had to be reverted and relanded due to golden failures. I think in that case we realized that the web needed the workaround and so we had to land a fix to the web before we relanded the fix that removed the workaround from the framework. You might want to check out the tests that failed and make sure the same thing doesn't happen here.

@jason-simmons landed the web workaround here: https://github.com/flutter/engine/pull/42304

**Comment by goderbauer** [comment]
Kicked off a TGP to see if this breaks anything in g3 (OCL:550046596:BASE:550044778:1689973967576:ba883be0). All open source tests are still passing.

**Comment by goderbauer** [comment]
TGP didn't surface any issues.

**Pull request merged**
