### PR TITLE
[flutter_tools] alternate the name of the dill file used for hot restart

### LINKED ISSUE #60910: Windows Hot Restart reverts to older version of app (from the first Hot Restart)
I haven't reproduced myself yet as I've not got VS set up for Windows Desktop work (I can't repro using the Android emulator on Windows) but I've seen @BootBlock reproduce it reliably on multiple video calls. He's using:

- Windows 10
- Latest Flutter master branch (`1.20.0-3.0.pre.130`)
- Windows Desktop device
- The default counter app created by `flutter create`

The problem looks like this:

- Run the app
- Make a change to the text (eg. replace with "one") and save (which triggers a hot reload)
- Manually click the Hot Restart action (this restarts the app, and correctly shows "one")
- Change the text again (eg. replace with "two") and save (which triggers a hot reload)
- Manually click the Hot Restart action (this restarts the app, but incorrectly reverts to showing "one")

This happens consistently. Any time you click Hot Restart from this point, it will revert to showing "one". Hot Reload works fine, reflecting the changes being made.

Here is both a full verbose log (including Flutter daemon output, and all VM service traffic) and also a version I've trimmed down to remove some of the stuff I think isn't relevant to this (setLibraryDebuggable spam, ServiceExtensionAdded, etc.).

- [hotRestartLog.txt](https://github.com/flutter/flutter/files/4879886/hotRestartLog.txt)
- [hotRestartLog.trimmed.txt](https://github.com/flutter/flutter/files/4879885/hotRestartLog.trimmed.txt)

This is from the hot restart the fails - I'm not sure if the 0 here is the cause (however this file was known to have been modified and was hot reloaded in successfully between the initial - working - hot restart, and this one):

```
[15:55:45] [FlutterRun] [Error] [        ] Scanning asset files
[15:55:45] [FlutterRun] [Error] [        ] <- reset
[15:55:45] [FlutterRun] [Error] [        ] Compiling dart to kernel with 0 updated files
[15:55:45] [FlutterRun] [Error] [        ] <- recompile package:bugtest/main.dart 26f89a78-d949-494f-845c-86bcaa413fa9
[15:55:45] [FlutterRun] [Error] [        ] <- 26f89a78-d949-494f-845c-86bcaa413fa9
```

(@jonahwilliams if there's anywhere we can add extra logging to temporarily to track this down, let me know - we can easily modify the source locally on @BootBlock's machine and redo)

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

The engine memory maps the dill file used to run the Dart isolate. Replacing this file before hot restart is not technically safe, though is unlikely to crash.  Nevertheless, the protection applied by the windows mapping prevents replacing the file.

Update hot restart so that the uploaded file name alternates -> main.dart.dill -> main.dart.swap.dill > main.dart.dill to prevent replacing the mapped dill and to avoid filling up the devFS.

Context:

https://github.com/flutter/engine/blob/master/fml/platform/win/mapping_win.cc#L73

Fixes https://github.com/flutter/flutter/issues/60910

### CODE REVIEW

**Comment by jonahwilliams** [comment]
FYI @aam

**Review by aam — APPROVED** [review]

**Comment by jonahwilliams** [comment]
@zanderso do you have any concerns about this? from my understanding what we're doing today is technically not safe, though unlikely to crash.

**Review by zanderso — APPROVED** [review]
bikeshed: instead of 'left' how about just '1' and '0'? Or maybe 'swap' or 'secondary'?

Is the real fix a lot more involved? I would think that Restart should be doing something like:
1. stop execution
2. unmap the old dill
3. map the new dill
4. restart

Do we know how/why that goes wrong?

**Comment by jonahwilliams** [comment]
swap sounds good.

For a real fix, yes I think we'd have to stop the main isolate before uploading the new dill and restarting. I can foresee some issues though because the main isolate lifecycle is tied to the service isolate and application lifecycle, so simply using the existing vm_service API is not sufficient.

We'd need a new set of vm_service APIs provided by the engine that essentially split the hot restart process in half, one to take down the main isolate (while keeping everything else alive) and one to resurrect it with the newly uploaded dill. I'm not sure how difficult that would be to do. Fyi @chinmaygarde @jason-simmons

**Pull request merged**
