### PR TITLE
Add conditional centerLeading

### PR DESCRIPTION
**Pull request by ghost**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Review by justinmc — COMMENTED** [review]
A few things to look at before this is ready: 

 * Is it possible to work around this by wrapping your `leading` in a `Center`?
 * Is there an existing issue for this?
 * Needs tests.
 * Failing checks, see below.
 * PR description needs to be filled out.

**Comment by Piinks** [comment]
@mu7ammadkamel would you like to continue working on this change?

**Comment by muhammadkamel** [comment]
@Piinks 


> @mu7ammadkamel would you like to continue working on this change?

Sure thing!
What is the next step?

**Comment by muhammadkamel** [comment]
> @mu7ammadkamel would you like to continue working on this change?

Sure thing!
What is the next step?

**Comment by muhammadkamel** [comment]
> A few things to look at before this is ready:
> 
> * Is it possible to work around this by wrapping your `leading` in a `Center`?
> * Is there an existing issue for this?
> * Needs tests.
> * Failing checks, see below.
> * PR description needs to be filled out.

I need to make this behavior on the Theming as (Global).
Maybe developers needs to change the style of the leading (Arrow back).
In some cases I need to make the leading like a rounded container with an arrow.

**Comment by mu7ammadkamel** [comment]
> A few things to look at before this is ready:
> 
> * Is it possible to work around this by wrapping your `leading` in a `Center`?
> * Is there an existing issue for this?
> * Needs tests.
> * Failing checks, see below.
> * PR description needs to be filled out.

I need to make this behavior on the Theming as (Global).
Maybe developers need to change the style of the leading (Arrow back).
In some cases I need to make the leading like a rounded container with an arrow.

**Comment by mu7ammadkamel** [comment]
> @mu7ammadkamel would you like to continue working on this change?

Sure thing! What is the next step?

**Comment by justinmc** [comment]
1. Fill out the PR description above.
2. Test the new code.
3. Fix the failing CI checks.

Also, can you show me what you're trying to achieve with this PR with a screenshot?

**Comment by Piinks** [comment]
Hey @mu7ammadkamel would you like to continue working on this change?

**Pull request closed without merging**
