### PR TITLE
[dap] Remove some code that's not longer required

### PR DESCRIPTION
**Pull request by DanTup**
This just removes some leftover code that's no longer required in the DAP. The latest DDS roll made this code redundant and @bkonyi already removed the places that called it in #98513 (thanks!).

There are no new tests as this is just removing unused code. All existing tests continue to pass.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM, I'll request a test exemption on discord

**Comment by DanTup** [comment]
Thanks!

> LGTM, I'll request a test exemption on discord

I already did :-)

**Comment by christopherfujino** [comment]
> Thanks!
> 
> > LGTM, I'll request a test exemption on discord
> 
> I already did :-)

oh nice

**Comment by DanTup** [comment]
> Google testing — Google testing failed. Please contact a Google developer to investigate.

Do you know what this is? 🤔

**Comment by bkonyi** [comment]
This is the error:

```
google3:///[third_party/dart/flutter_tools/lib/src/debug_adapters/flutter_test_adapter.dart:131](https://cs.corp.google.com/piper///depot/google3/third_party/dart/flutter_tools/lib/src/debug_adapters/flutter_test_adapter.dart?l=131&ws=tap-prod-presubmit/173052774&snapshot=4):35: Error: The method 'findPackageConfigFile' isn't defined for the class 'FlutterTestDebugAdapter'.
 - 'FlutterTestDebugAdapter' is from 'package:flutter_tools/src/debug_adapters/flutter_test_adapter.dart' ('google3:///third_party/dart/flutter_tools/lib/src/debug_adapters/flutter_test_adapter.dart').
Try correcting the name to the name of an existing method, or defining a method named 'findPackageConfigFile'.
      final File? packageConfig = findPackageConfigFile(possibleRoot);
                                  ^^^^^^^^^^^^^^^^^^^^^
(09:28:50) ERROR: [third_party/dart/flutter_tools/BUILD:17](https://cs.corp.google.com/piper///depot/google3/third_party/dart/flutter_tools/BUILD?l=17&ws=tap-prod-presubmit/173052774&snapshot=4):13: Dart, summarizing //third_party/dart/flutter_tools:api [for tool] failed: (Exit 1) analyzer_bin failed: error executing command (from target //third_party/dart/flutter_tools:api) blaze-out/host/bin/dart/build_defs/action/analyzer/analyzer_bin @blaze-out/host/bin/third_party/dart/flutter_tools/api.api.ds-0.params.  [forge_remote_host=volu14]

ERROR: third_party/dart/flutter_tools/lib/src/debug_adapters/flutter_adapter.dart

268: final File? packageConfig = findPackageConfigFile(possibleRoot); Undefined method. #undefined_method

ERROR: third_party/dart/flutter_tools/lib/src/debug_adapters/flutter_test_adapter.dart

131: final File? packageConfig = findPackageConfigFile(possibleRoot); Undefined method. #undefined_method
```

So I think we're just waiting on a roll into google3 which includes my related changes.

**Comment by DanTup** [comment]
@bkonyi ah, so the google3 bot is trying to apply this patch without #98513? Will the status here automatically update, or do I need to do something to re-run it once that's happened (which I don't think I have visibility of, so someone will have to tell me if so :-) )

Thanks!

**Comment by Hixie** [comment]
test-exempt: code removal

**Comment by bkonyi** [comment]
> @bkonyi ah, so the google3 bot is trying to apply this patch without #98513? Will the status here automatically update, or do I need to do something to re-run it once that's happened (which I don't think I have visibility of, so someone will have to tell me if so :-) )
> 
> Thanks!

Yeah, we just need to wait for that change to roll in and then we'll have to kick this check to run again. Not sure when that will happen, unfortunately :-(

**Comment by DanTup** [comment]
@bkonyi has your change landed internally? (there's no rush to land this, just noticed it was still open)

**Comment by bkonyi** [comment]
> @bkonyi has your change landed internally? (there's no rush to land this, just noticed it was still open)

I think so... I'll kick the Google testing bot and see what happens.

**Comment by bkonyi** [comment]
Still failing. I'm not sure that change has rolled in yet.

**Comment by christopherfujino** [comment]
cc @CaseyHillers regarding what I was saying about new "Google Testing" runs not patching in an existing g3fix.

**Comment by CaseyHillers** [comment]
\cc @renyou @angjieli do you know if there's a way to link a g3fix to a PR?

**Comment by renyou** [comment]
> \cc @renyou @angjieli do you know if there's a way to link a g3fix to a PR?

Yes but it's designed to be a full internal process. You can do so in frob.

**Comment by christopherfujino** [comment]
So the underlying breaking change has rolled internally, so just doing a sync and test should fix this. However, in the FRoB UI, I cannot find this PR, and when I try to "test a PR", I get the error that it already exists. @renyou @angjieli any tips on how to force a retry?

**Comment by DanTup** [comment]
I've rebased on latest master. I don't know if it'll help, but the bots have started again.

**Comment by christopherfujino** [comment]
> I've rebased on latest master. I don't know if it'll help, but the bots have started again.

Looks like that re-scheduled Google testing :+1:

**Comment by DanTup** [comment]
@christopherfujino do you know what the bot failure is above? I can't find any output in the logs that looks like an error.

**Comment by christopherfujino** [comment]
> @christopherfujino do you know what the bot failure is above? I can't find any output in the logs that looks like an error.

It's a timeout. Re-triggering...

**Comment by DanTup** [comment]
Seems to have happened again 😞

**Comment by christopherfujino** [comment]
This flake is being tracked in https://github.com/flutter/flutter/issues/99940. Gonna retry one more time for good luck.

**Comment by godofredoc** [comment]
This PR needs to be rebased dart_plugin_registry_test  is not running because .ci.yaml is outdated

**Comment by DanTup** [comment]
> This PR needs to be rebased dart_plugin_registry_test is not running because .ci.yaml is outdated

Thanks, done!

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/98928

**Comment by DanTup** [comment]
crying toddler

Maybe we should just keep this code? 😄

**Comment by christopherfujino** [comment]
Unrelated, marked this green in FRoB dashboard.

**Comment by DanTup** [comment]
Thanks!

**Pull request merged**
