### PR TITLE
Fixed large amount of spelling errors

### PR DESCRIPTION
**Pull request by anisalibegic**
## Description

Large amount of typos spotted and fixed! Some of them are in comments, some of them are in code and some of them are in nondart files.

## Tests

No tests for typos correction.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I am willing to follow-up on review comments in a timely manner.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by anisalibegic** [comment]
CC @jonahwilliams

**Review by jonahwilliams — APPROVED** [review]
LGTM!

**Comment by jonahwilliams** [comment]
You do have one lint failure:

info • Only use double quotes for strings containing single quotes • packages/flutter_driver/test/src/real_tests/extension_test.dart:261:9 • prefer_single_quotes

**Comment by anisalibegic** [comment]
@jonahwilliams  Can you check that last commit? I pushed some other fixes.

**Comment by jonahwilliams** [comment]
It looks like you've got some legitimate test failures now

**Comment by anisalibegic** [comment]
> It looks like you've got some legitimate test failures now

I fixed it! It was failing because of https://github.com/flutter/flutter/pull/83744/commits/66312bd5b41556f7a6dd995d5a61a13704b2cdf2. I believe we should use something else for map key instead of `chidlren` if the idea was to test if `childJson` is returning null for nonexisting element. Also, that's the only place in the whole repo where `chidlren` is used.

**Review by jonahwilliams — APPROVED** [review]
LGTM!

**Comment by rafaelsetragni** [comment]
Hi everyone!

Right now im developing a notification plugin for Flutter called `awesome_notifications` and im struggling to add Flutter into targets extension, such as `NotificationServiceExtension` and `NotificationContentExtension`. That way ill be able to provide all the rich resources that i can do with local notifications.

Im trying to add Flutter into the targets using the command `flutter_install_ios_engine_pod`, but im getting this error:

```
ld: warning: Could not find or use auto-linked framework 'Flutter'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FlutterStandardTypedData", referenced from:
      objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)
  "_OBJC_CLASS_$_FlutterError", referenced from:
      objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)
      objc-class-ref in awesome_notifications_fcm(SwiftAwesomeNotificationsFcmPlugin.o)
  "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
      objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)
      objc-class-ref in awesome_notifications_fcm(SwiftAwesomeNotificationsFcmPlugin.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

Im trying by many different ways to codding my podspec to achieve this, but in major tries i did:

```
target 'AwesomeServiceExtension' do
  use_frameworks!
  use_modular_headers!

  flutter_install_ios_engine_pod File.dirname(File.realpath(__FILE__))
  pod 'awesome_notifications_fcm', :path => '.symlinks/plugins/awesome_notifications_fcm/ios'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      if target.name.start_with? 'Awesome'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end
end
```

And i need Flutter because i add dynamicaly assets and other flutter resources into notifications.
Any idea of how to include Flutter to run inside target extensions?

**Comment by anisalibegic** [comment]
> Hi everyone!
> 
> Right now im developing a notification plugin for Flutter called `awesome_notifications` and im struggling to add Flutter into targets extension, such as `NotificationServiceExtension` and `NotificationContentExtension`. That way ill be able to provide all the rich resources that i can do with local notifications.
> 
> Im trying to add Flutter into the targets using the command `flutter_install_ios_engine_pod`, but im getting this error:
> 
> ```
> ld: warning: Could not find or use auto-linked framework 'Flutter'
> Undefined symbols for architecture arm64:
>   "_OBJC_CLASS_$_FlutterStandardTypedData", referenced from:
>       objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)
>   "_OBJC_CLASS_$_FlutterError", referenced from:
>       objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)
>       objc-class-ref in awesome_notifications_fcm(SwiftAwesomeNotificationsFcmPlugin.o)
>   "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
>       objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)
>       objc-class-ref in awesome_notifications_fcm(SwiftAwesomeNotificationsFcmPlugin.o)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> Im trying by many different ways to codding my podspec to achieve this, but in major tries i did:
> 
> ```
> target 'AwesomeServiceExtension' do
>   use_frameworks!
>   use_modular_headers!
> 
>   flutter_install_ios_engine_pod File.dirname(File.realpath(__FILE__))
>   pod 'awesome_notifications_fcm', :path => '.symlinks/plugins/awesome_notifications_fcm/ios'
> end
> 
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>       if target.name.start_with? 'Awesome'
>         config.build_settings['ENABLE_BITCODE'] = 'NO'
>         config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
>       end
>     end
>   end
> end
> ```
> 
> And i need Flutter because i add dynamicaly assets and other flutter resources into notifications.
> Any idea of how to include Flutter to run inside target extensions?

Sorry but I'm really not sure how that issue is connected with this PR (that just fixed few non-breaking typos).

**Comment by rafaelsetragni** [comment]
I believe is related to this PR because the Flutter path is not correct when `flutter_install_ios_engine_pod` runs inside other target extensions and, if i got a solution someday, i will recomend others to use it by mine README files.

It is possible to debug the pod script to check what values are passing by the methods? I wanna help to improve this file, but im basicly coding with "notepad".

**Pull request merged**
