### PR TITLE
'fix' build

### PR DESCRIPTION
**Pull request by jonahwilliams**

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
Ewww.  LGTM.

**Comment by jonahwilliams** [comment]
Landing on red to fix the build

**Comment by mravn-google** [comment]
Thanks for fixing my breakage! I'm puzzled by the fix though. Doesn't Dart string interpolation delegate to `toString` on its own??

**Comment by jonahwilliams** [comment]
It does, in this case through some overrides or something toString is returning null, which causes string interpolation to fail.

**Comment by mravn-google** [comment]
Ah, ok. That's something I should be able to fix. Looking...

**Pull request merged**
