### PR TITLE
flutter_tools/version: git log.showSignature=false

### LINKED ISSUE #38572: `git config --global log.showsignature true` breaks Flutter
In case the site Git installation is configured with `log.showsignature=true`, `git log` will output the GPG signature even with `--pretty=format`. Flutter will then fail to get its own version and crash at the first invocation (from `packages/flutter_tools/src/version.dart`).

Possibly related issue: #26751 (closed).

## Steps to Reproduce

1. `git config --global log.showsignature true`
2. Download, unpack and cd into [the Linux flutter archive](https://flutter.dev/docs/get-started/install/linux)
3. `export PATH=$(pwd)/flutter/bin:$PATH ; flutter doctor`

## Logs

[flutter_02.log](https://github.com/flutter/flutter/files/3503344/flutter_02.log)

```
FormatException: FormatException: Invalid date format
gpg: Signature made Fri 19 Jul 2019 03:04:33 AM UTC
gpg:                usi...
```

Output of `flutter doctor -v` is irrelevant (will crash).

## Fixes

1) Ignore this issue. `showsignature=true` breaks a lot of things, and not a lot of people enable it. I've had it on purely on inertia.
2) Force `log.showsignature=false`. PR coming up, merge at discretion.

### PR DESCRIPTION
**Pull request by ghost**
If the site Git configuration has log.showSignature=true, which is not the default, it will break versioning functions with

>  FormatException: FormatException: Invalid date format

This fix forces log.showSignature=false for git log calls in package:flutter_tools/src/version.dart.

Fixes #38572.

## Tests

No new tests have been added. Some existing tests have been patched.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by interruptinuse** [comment]
Actually, yeah, some tests still call `git log`, gonna have to patch those as well.
```
dev/bots/test.dart
667:    'git$exe', <String>['log', _getGitHash(), '--pretty="%an <%ae>"'],

packages/flutter_tools/lib/src/version.dart
23:    _frameworkRevision = _runGit("git $_gitlog_conf log -n 1 --pretty=format:%H");
89:    return _frameworkAge ??= _runGit("git $_gitlog_conf log -n 1 --pretty=format:%ar");
145:      '--pretty=format:%ad',

packages/flutter_tools/test/general.shard/commands/version_test.dart
119:    if (commandStr == 'git log -n 1 --pretty=format:%H') {

packages/flutter_tools/test/general.shard/version_test.dart
475:    if (argsAre('git', 'log', '-n', '1', '--pretty=format:%ad', '--date=iso')) {
486:    } else if (remoteCommitDate != null && argsAre('git', 'log', '__flutter_version_check__/$channel', '-n', '1', '--pretty=format:%ad', '--date=iso')) {
509:    <String>['git', 'log', '-n', '1', '--pretty=format:%H'],
514:    <String>['git', 'log', '-n', '1', '--pretty=format:%ar'],

packages/flutter_tools/test/general.shard/runner/flutter_command_runner_test.dart
135:        when(processManager.runSync('git log -n 1 --pretty=format:%H'.split(' '),
143:        when(processManager.runSync('git log -n 1 --pretty=format:%ar'.split(' '),
147:        when(processManager.runSync('git log -n 1 --pretty=format:%ad --date=iso'.split(' '),
```

**Comment by jmagman** [comment]
Can you also take a look at the analyzer warnings?
```
   info • Prefer single quotes where they won't require escape sequences • packages/flutter_tools/lib/src/version.dart:23:34 • prefer_single_quotes
   info • Prefer single quotes where they won't require escape sequences • packages/flutter_tools/lib/src/version.dart:89:38 • prefer_single_quotes
```

**Comment by interruptinuse** [comment]
Updated the code for `analyze` hints.
I have modified existing tests to use the new `FlutterVersion.gitLog` interface. I \***haven't**\* added any tests: the test will need to call `git config --local log.gitstatus=true` on the actual repository, then test, then cleanup, and all git calls in `packages/flutter_tools/test/general.shard/version_test.dart` and `packages/flutter_tools/test/general.shard/commands/version_test.dart` seem to use mocks; so I'm not sure if a test is appropriate. Confirm? Going to open for review in the meantime.

**Comment by interruptinuse** [comment]
One more force push, sorry. Adding an explanation comment and removing some formatting I accidentally added.

**Comment by interruptinuse** [comment]
Should I maybe squash these commits into one to retrigger the CI?

**Comment by jmagman** [comment]
> Should I maybe squash these commits into one to retrigger the CI?

add2app failed on a clone timeout, annoying that reported as a failure instead of restarting.  I reran them.

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
Feel free to merge whenever the check mark is green!

**Comment by interruptinuse** [comment]
Sure! May I have access pwease?

**Comment by jmagman** [comment]
> Feel free to merge whenever the check mark is green!

Apologies, I forgot you needed access for that.  Merged!

Thanks for your fix!

**Pull request merged**
