### PR TITLE
roll engine

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by jason-simmons** [comment]
@chinmaygarde

**Review by chinmaygarde — APPROVED** [review]

**Comment by Hixie** [comment]
This engine roll regressed several performance metrics.

**Comment by Hixie** [comment]
Specifically this regressed missed_frame and average_frame rasterizer benchmarks on Android.

**Comment by jason-simmons** [comment]
This roll includes rendering to an offscreen texture for sRGB color space conversion (https://github.com/flutter/engine/commit/ddaa125ca7845ee177ceca6078d0aae3a675c4a6)

@chinmaygarde

**Comment by Hixie** [comment]
This roll also regressed two of the aot_snapshot_build_millis benchmarks.

**Comment by Hixie** [comment]
The relevant commits for this roll were https://github.com/flutter/engine/pull/3931 https://github.com/flutter/engine/pull/3929 https://github.com/flutter/engine/pull/3921 https://github.com/flutter/engine/pull/3930 https://github.com/flutter/engine/pull/3932 and https://github.com/flutter/engine/pull/3933.

The first of these included a Dart roll, which seems like the obvious candidate for the regression to aot_snapshot_build_millis. cc @a-siva.

**Pull request merged**
