### PR TITLE
[web] roll Chromium dep to 96.2

### PR DESCRIPTION
**Pull request by yjbanov**
Roll test Chromium from 84 to 96 for non-mac builders (macs are on 98 already).

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 29 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/99725

**Review by keyonghan — APPROVED** [review]
LGTM

**Comment by skia-gold** [comment]
Gold has detected about 24 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/99725

**Comment by skia-gold** [comment]
Gold has detected about 27 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/99725

**Pull request merged**
