### PR TITLE
[fix issue #24048] Fixed a problem, the vertical drag was not recogni…

### LINKED ISSUE #24048: Use GestureDetector and CustomScrollView together
Hello,
I try use customScrollView for  pull-to-refresh，see code
   ```
CustomScrollView(
        shrinkWrap: widget.shrinkWrap,
        physics:  RefreshScrollPhysics(),
        slivers: <Widget>[
          CupertinoSliverRefreshControl(
              builder: _buildSimpleRefreshIndicator,
              onRefresh: () => Future(() => widget.loadNew())),
          SliverSafeArea(sliver: SliverList(
                  delegate: SliverChildBuilderDelegate((context, index) {
                            return _buildProgressIndicator();
                        },
                          childCount: widget.itemCount)
                      ))
        ],
        controller: _scrollController,
      )
```
But it drop down to a certain distance will refresh，What I want is to loosen my fingers and refresh。 And the refreshIndicatorMode has only five states，There is no one state indicating that the finger is off the screen。So finally，I use gestureDetector and customScrollView together to get the state of the finger。
```
GestureDetector(
      child: CustomScrollView(...),
      onVerticalDragDown: (_) {
        print("show onVerticalDragDown");
      },
      onVerticalDragStart: (_) {
        print("show onVerticalDragStart");
      },
      onVerticalDragUpdate: (_) {
        print("show onVerticalDragUpdate");
      },
      onVerticalDragEnd: (_) {
        print("show onVerticalDragEnd");
      },
      onVerticalDragCancel: () {
        print("show onVerticalDragCancel");
      },
    )
```
But there seems to be a sliding conflict，it‘s only print 'show onVerticalDragDown' and then print 'show onVerticalDragCancel'。So how to solve these problems when can't use it to set physics is NeverScrollableScrollPhysics。

### PR DESCRIPTION
**Pull request by haeseoklee**
…zed when the child of GestureDetector is ScrollView

## Description

Due to the conflict between GestureDetector and ScrollView, some functions of GestureDetector were not called. 
So I fixed it. :)

demo

**Before**
```
Performing hot restart...
Syncing files to device iPhone SE (2nd generation)...
Restarted application in 5,353ms.
flutter: Gesture arena 516  ❙ ★ Opening new gesture arena.
flutter: Gesture arena 516  ❙ Adding: VerticalDragGestureRecognizer#4b16e(start behavior: start)
flutter: Gesture arena 516  ❙ Adding: VerticalDragGestureRecognizer#3b37d(debugOwner: GestureDetector, start behavior: start)
flutter: show onVerticalDragDown
flutter: Gesture arena 516  ❙ Closing with 2 members.
flutter: Gesture arena 516  ❙ Accepting: VerticalDragGestureRecognizer#4b16e(start behavior: start)
flutter: Gesture arena 516  ❙ Self-declared winner: VerticalDragGestureRecognizer#4b16e(start behavior: start)
flutter: show onVerticalDragCancel
```

**After**
```
Performing hot restart...
Syncing files to device iPhone SE (2nd generation)...
Restarted application in 5,473ms.
flutter: Gesture arena 515  ❙ ★ Opening new gesture arena.
flutter: Gesture arena 515  ❙ Adding: VerticalDragGestureRecognizer#891e3(start behavior: start)
flutter: Gesture arena 515  ❙ Adding: VerticalDragGestureRecognizer#56a13(debugOwner: GestureDetector, start behavior: start)
flutter: show onVerticalDragDown
flutter: Gesture arena 515  ❙ Closing with 2 members.
flutter: Gesture arena 515  ❙ Accepting: VerticalDragGestureRecognizer#891e3(start behavior: start)
flutter: Gesture arena 515  ❙ Self-declared winner: VerticalDragGestureRecognizer#891e3(start behavior: start)
flutter: show onVerticalDragStart
flutter: show onVerticalDragUpdate
flutter: show onVerticalDragUpdate
flutter: show onVerticalDragUpdate
flutter: show onVerticalDragUpdate
flutter: show onVerticalDragUpdate
flutter: show onVerticalDragUpdate
flutter: show onVerticalDragUpdate
flutter: show onVerticalDragUpdate
flutter: show onVerticalDragUpdate
flutter: show onVerticalDragUpdate
flutter: show onVerticalDragUpdate
flutter: show onVerticalDragUpdate
flutter: show onVerticalDragEnd
```

**<details><summary>Test code</summary>**

```Dart
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';

void main() {
  debugPrintGestureArenaDiagnostics = true;
  runApp(MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
          body: GestureDetector(
            onVerticalDragDown: (_) {
              print("show onVerticalDragDown");
            },
            onVerticalDragStart: (_) {
              print("show onVerticalDragStart");
            },
            onVerticalDragUpdate: (_) {
              print("show onVerticalDragUpdate");
            },
            onVerticalDragEnd: (_) {
              print("show onVerticalDragEnd");
            },
            onVerticalDragCancel: () {
              print("show onVerticalDragCancel");
            },
            child: CustomScrollView(
              slivers: <Widget>[
                const SliverAppBar(
                  pinned: true,
                  expandedHeight: 250.0,
                  flexibleSpace: FlexibleSpaceBar(
                    title: Text('Demo'),
                  ),
                ),
                SliverGrid(
                  gridDelegate: SliverGridDelegateWithMaxCrossAxisExtent(
                    maxCrossAxisExtent: 200.0,
                    mainAxisSpacing: 10.0,
                    crossAxisSpacing: 10.0,
                    childAspectRatio: 4.0,
                  ),
                  delegate: SliverChildBuilderDelegate(
                        (BuildContext context, int index) {
                      return Container(
                        alignment: Alignment.center,
                        color: Colors.teal[100 * (index % 9)],
                        child: Text('Grid Item $index'),
                      );
                    },
                    childCount: 30,
                  ),
                ),
              ],
            ),
          )
      ),
    );
  }
}
```
</details>

## Related Issues

Use GestureDetector and CustomScrollView together 
Fixes #24048

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by goderbauer** [comment]
This PR is causing many test failures and it is missing tests.

**Comment by haeseoklee** [comment]
@goderbauer 
I added test code!! Also the rewritten code passed many test failures. Please review :)

**Comment by dkwingsmt** [comment]
Thanks for the PR. Although I'm not a fan of this solution for the following reasons:

- The name `addManually` is confusing. For a user who is only aware of gesture detectors, this name does not make much sense. Even if you explain what it does, it's hard for users to understand when to use it.
- When it's enabled, the outer detector detects the drag even when the inner drag is not at its end, which violates the rule of only one gesture should be accepted (see below for more thoughts).
- It adds an option to solve a problem that feels should not exist at all, which means it's better we think about what we did wrong (I'm sure we did) when designing the mechanism.

Correct me if I'm wrong, but I think the demand here is that the inner drag recognizer should "surrender" when it has reached the end of the intended direction. For example, say there are 2 vertical dragging gestures, one nested in the other,
- If the inner is being dragged downwards, and it's not at the top yet, the outer should not be notified.
- If the inner is being dragged downwards, and it's at the top at the start or middle of the drag, the outer should start to take over the drag.

This mechanism has been implemented by `PointerSignalResolver` for mouse scrolling, and by `NestedScrollView` for nested scroll views, but in the case you're trying to solve, the outer widget is a detector instead of a scroll view, which means it can take advantage of neither.

We should probably either 1) try to build the demanded feature using `NestedScrollView`, or in case it's not possible, 2) build a mechanism that can resolve dragging the same way as `PointerSignalResolver`.

@Piinks Are you familiar with `NestedScrollView`? Do you think 1) is possible? Or if not, doing 2) will simplify/unify the implementation of `NestedScrollView`?

**Comment by Piinks** [comment]
Hey @dkwingsmt thanks for considering the Nested Scroll View. It appears in the issue that this can be accomplished using a NotificationListener: https://github.com/flutter/flutter/issues/24048#issuecomment-644340821 The issue was looking for a way to trigger a refresh after lifting their finger instead of dragging to a certain scroll offset.

**Comment by goderbauer** [comment]
I am going to close this with some of the reasons given in https://github.com/flutter/flutter/pull/63179#issuecomment-673145768.

**Pull request closed without merging**
