### PR TITLE
Reland "Fix text field label animation duration and curve (#105966)"

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
Reverts flutter/flutter#114646

### CODE REVIEW

**Comment by CaseyHillers** [comment]
@LongCatIsLooong can you link to the internal fix?

**Comment by LongCatIsLooong** [comment]
@CaseyHillers sorry for the delay: cl/494922517

**Review by CaseyHillers — APPROVED** [review]
flutter-lgtm

**Comment by LongCatIsLooong** [comment]
TGP: OCL:495709437:BASE:495710669:1671157852850:ff6f8e4b

Merging manually.

**Pull request merged**
