### PR TITLE
Update package:stack_trace dependency to 1.10.0-nullsafety.4

### PR DESCRIPTION
**Pull request by mkustermann**
This is a pre-requisite to re-landing the flutter engine change in https://github.com/flutter/engine/pull/21043#issuecomment-704880681

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by mkustermann** [comment]
On my GCP windows VM the expression evaluation test successfully passes with this CL.

**Comment by cskau-g** [comment]
Tree looks green. Good to go?

(LGTM)

**Review by ghost — APPROVED** [review]

**Comment by mkustermann** [comment]
Flutter tree has turned green, landing it now

**Pull request merged**
