### PR TITLE
More dart 2 fixes to fuchsia_tester.dart

### PR DESCRIPTION
**Pull request by tvolkert**

### CODE REVIEW

**Review by matanlurey — COMMENTED** [review]
Just curious: how is this related to Dart 2?

Is someone else expecting this to be a List? Your code is totally valid before.

**Comment by tvolkert** [comment]
It wasn't valid because that iterable was being passed to a function that requires a `List<String>`

**Comment by filiph** [comment]
@matanlurey I think it's because `runTests` expects a list, not an iterable:
https://github.com/tvolkert/flutter/blob/fd9d24d835d9e2078f20b8d8e5d452f15d576a30/packages/flutter_tools/lib/src/test/runner.dart#L24

**Comment by matanlurey** [comment]
Got it thanks!

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
LGTM

test?

**Pull request merged**
