### PR TITLE
ignore PausePostRequest when reloading

### LINKED ISSUE #11336: Hot reload button didn't perform hot reload
_From @InMatrix on July 21, 2017 0:26_

## Steps to Reproduce

- Create a new Flutter project
- Run the app in an iPhone SE simulator 
- Change the theme color of the app
- Hit the Hot Reload button in IntelliJ

The console said "Reloaded 1 of 439 libraries in 305ms." But the color wasn't updated in the Simulator. 

This problem seems to only exist in IntelliJ. Hot Reload via command line worked. 

## Version info

[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/taodong/Code/flutter_repos/flutter
    • Framework revision 48427cb77a (3 hours ago), 2017-07-20 17:06:57 -0700
    • Engine revision 5fcfb995bb
    • Tools Dart version 1.25.0-dev.4.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/taodong/Library/Android/sdk
    • Platform android-24, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.0

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.5)
    • Flutter plugin version 15.1
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • iPhone SE • 464ACEFB-D361-4889-90B9-4084691BDF19 • ios • iOS 10.3 (simulator)

_Copied from original issue: flutter/flutter-intellij#1228_

### PR DESCRIPTION
**Pull request by devoncarew**
- ignore `PausePostRequest ` events when reloading (fix https://github.com/flutter/flutter/issues/11336)

This happens when a flutter_tools client - typically an IDE - requests a reload with the pause-after-reload flag set. This gives IDEs a chance to re-set breakpoints for the new scripts before the isolate starts executing again. In this case, we still want to request a reassemble of the app; the IDE client will resume the isolate, and without the reassemble, the hot reload is performed, but the app UI doesn't update.

### CODE REVIEW

**Comment by devoncarew** [comment]
@a-siva, could you or @B3rn475 review? I think this is a result of fixing the PausePostRequest event handling.

**Review by B3rn475 — APPROVED** [review]
I do confirm the missed reassemble and that the change fixes it.

LGTM

**Comment by johnmccutchan** [comment]
This will make it difficult to set breakpoints in build methods. It will also expose the developer to an indeterminate state of which breakpoints are still active.

**Comment by B3rn475** [comment]
Due to https://github.com/dart-lang/sdk/commit/ba5fe22984ee46192f3a08a557f916794f7f2d99 when editors request `sourceReload` with `pause: true`.

- If the application was idle, it reloads the source code and pauses, the `reassemble` request gets queued in the VM, the editor has time to reset all the requested breakpoints and send the `resume` command when they are all in place. The  `reassemble` is executed.
- If the application was at a breakpoint, it reloads the source code and still pauses, the `reassemble` request gets queued in the VM, the editor has time to reset all the requested breakpoints and will not send the `resume` command when they are all in place, remaining at the same breakpoint. The  `reassemble` will remain in the queue till the stack empties.

Before https://github.com/dart-lang/sdk/commit/ba5fe22984ee46192f3a08a557f916794f7f2d99 the isolate was resuming in both `pause: true` and `pause: false` situations https://github.com/flutter/flutter/issues/10934

IntelliJ due to good timing was still able to reset breakpoints.

**Pull request merged**
