### PR TITLE
Drop mockito for flutter_goldens

### PR DESCRIPTION
**Pull request by dnfield**
Part of a minor quest to get rid of mockito to make NNBD migrations easier.

During this, I noticed that tests were creating files on me and found that the goldens client was not using its process manager but instead using io.Process.run, so I fixed that up too.

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
This is awesome, thank you for doing this. 🎉 
It looks like a lot of tests are broken though?

**Comment by dnfield** [comment]
Yeah, I'm having trouble reproducing it locally cause I think it goes down a different code path on CI

**Comment by dnfield** [comment]
Ok, I had one method where I forgot to add `_goldctl` to the list of arguments. It should hopefully pass now.

**Comment by dnfield** [comment]
Tests appear to be happy now

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

**Pull request merged**
