### PR TITLE
V1.9.1 hotfixes

### PR DESCRIPTION
**Pull request by tvolkert**
Bump version of just package:multicast_dns (#41207)
Implement mdns for `flutter run` (#40447)

### CODE REVIEW

**Comment by christopherfujino** [comment]
I'll test this locally....

**Review by zanderso — APPROVED** [review]

**Review by christopherfujino — APPROVED** [review]
LGTM, runs for me locally both on iOS13 and iOS12

**Comment by tvolkert** [comment]
@christopherfujino can you take a look at the test failures?  They're more than the known failures on the tip of this branch.

**Comment by christopherfujino** [comment]
@tvolkert tool_tests are failing because the version file (`flutter/version`) doesn't match the regex pattern--because this commit hasn't been tagged yet, the version file contains `1.9.1+hotfix.3-pre.3`. I think the regex for this test needs to be changed, opened https://github.com/flutter/flutter/issues/41310.

**Review by zanderso — APPROVED** [review]
still lgtm

**Comment by christopherfujino** [comment]
lgtm, looks like the tools tests have passed.

**Pull request merged**
