### PR TITLE
Minor fixes to precache help text

### PR DESCRIPTION
**Pull request by timsneath**
## Description

Noticed a spelling error on the `flutter precache` command help text, and took the opportunity to tidy up the capitalization and trailing periods to be consistent with `flutter help`. Finally, clarified the difference between `--all-platforms` and `--universal`

## Related Issues

None

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

Thanks for the fixes!

**Comment by jonahwilliams** [comment]
I'm not quite sure what went wrong with CI, I'll restart the bots...

**Comment by timsneath** [comment]
Thanks!

**Comment by timsneath** [comment]
Replacing this PR with https://github.com/flutter/flutter/pull/36331, which does the same thing but hopefully without the odd CI failures.

**Pull request closed without merging**
