### PR TITLE
Down-sample animated icons frames.

### PR DESCRIPTION
**Pull request by amirh**
To reduce the code footprint of the generated files I down sampled
frames. For each icon I picked the lowest sample rate (1/2, 1/3, or 1/4)
that did not introduce artifacts.

### CODE REVIEW

**Comment by amirh** [comment]
@Hixie this brings the animated icons data from 1.8MB down to 728K.

Not sure if this is worth submitting (as it increases our git footprint, and we are still left with somewhat big files), let me know what you think...

**Comment by Hixie** [comment]
Is there some variable sampling rate solution that might make sense?

**Comment by amirh** [comment]
Yes, ideally we should be able to define some error margin, and skip frames where the interpolation does not introduce an error bigger than the margin.
This fixed rate sampling is just a  quick thing I could do to squeeze some improvement in file sizes.

While I believe we can get a major improvement with a few days of work doing smarter sampling (we will need to change the player as well), I'm not sure we're prioritizing that work right now. (Especially as we are probably going to end up with a completely different vector format in the long run).

Looks like VM folks might be able improve the performance regression as well - https://github.com/dart-lang/sdk/issues/32024.

My main doubt here is - should we be doing incremental improvements of the file sizes (where each improvement effectively increases our git history footprint), or just leave it as-is for now until we have time for a major overhaul of vector animations.

**Comment by Hixie** [comment]
I think probably it's best if we leave it for now, and then do a big improvement all at once later. File a bug with the performance label to track this? milestone 4 or 5.

**Pull request closed without merging**
