### PR TITLE
Roll engine to 45464c0a31e143055d6109c89b2f818d3fc819e5

### PR DESCRIPTION
**Pull request by alexmarkov**
Roll Flutter engine to the version before Dart 2.0 fixed-size integers.

### CODE REVIEW

**Review by cbracken — APPROVED** [review]

**Comment by aam** [comment]
Didn't realize it, but it would have been nice to had separate commit(roll) at dart roll commit e92933611af7762a0632a10c1e409a77b88cb4e4 to be able to see performance impact of just dart roll itself.

**Comment by xster** [comment]
Seems like this is causing some snapshot issues. Snapshots built after this PR can no longer run on the engine. 

`flutter run` gets `VM initialization failed: Wrong full snapshot version, expected '03753e0c17108b17c9447945f20f628d' found '3768d9fa87021f5c698c9ff34f739d5d'` starting from this commit.

**Comment by cbracken** [comment]
Quick summary of what we gathered:
* The issue occurs during debug builds, during `flutter build flx`, specifically during the `gen_snapshot` step. 
* Regardless of target platform, we always use `android-arm-profile` for script snapshot builds, the assumption being that script snapshots (as opposed to AOT snapshots) should be platform-portable.
* The `SNAPSHOT_HASH` embedded in the `gen_snapshot`s and engine builds under `bin/cache/artifacts/engine` is consistently `03753e0c17108b17c9447945f20f628d`, but for `bin/cache/artifacts/engine/darwin-x64/isolate_snapshot.bin` (and `vm_isolate_snapshot.bin`), it's `3768d9fa87021f5c698c9ff34f739d5d`.

To repro for the hello world example (tweak directories as necessary):
```
/Users/cbracken/src/flutter/flutter/bin/cache/artifacts/engine/android-arm-profile/darwin-x64/gen_snapshot --await_is_keyword --causal_async_stacks --vm_snapshot_data=/Users/cbracken/src/flutter/flutter/bin/cache/artifacts/engine/darwin-x64/vm_isolate_snapshot.bin --isolate_snapshot_data=/Users/cbracken/src/flutter/flutter/bin/cache/artifacts/engine/darwin-x64/isolate_snapshot.bin --packages=/Users/cbracken/src/flutter/flutter/examples/hello_world/.packages --dependencies=build/snapshot_blob.bin.d --print_snapshot_sizes --snapshot_kind=script --script_snapshot=build/snapshot_blob.bin --enable-mirrors=false /Users/cbracken/src/flutter/flutter/examples/hello_world/lib/main.dart
```

@aam @alexmarkov

**Comment by aam** [comment]
Build script update https://chromium-review.googlesource.com/c/chromium/tools/build/+/762358 should fix the problem where out-of-date mac gen_snapshot was packaged and uploaded to the cloud.

**Pull request merged**
