### PR TITLE
[flutter_test] perf: find.ancestor

### LINKED ISSUE #108920: [flutter_test] find.ancestor() is slow
I noticed that `find.ancestor()` is quite slow. It seems like `evaluate()` is called too often.

https://github.com/flutter/flutter/blob/04f7ea8459a965a7484af19ae551a86192bad86e/packages/flutter_test/lib/src/finders.dart#L957-L960

Possible fix:
Call `ancestor.evaluate()` only once at the beginning of the method instead of every time for every child.

### PR DESCRIPTION
**Pull request by passsy**
I noticed that `find.ancestor()` is quite slow. Mostly due to unnecessary `evaluate()` calls of the `ancestor` Finder. 

The `_AncestorFinder` called `ancestor.evaluate()` for every candidate. Now it is called beforehand. 

The new test now runs 4x faster.

```
Before: 538ms
After: 127ms
```

In my own tests I could see 10x and more improvements. 

Fixes #108920

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by pdblasi-google** [comment]
Hi @passsy!

Code wise, this looks good to me, but we need a related issue on the books in case we need to revert this for any reason, or if we need followup/context on the changes (see [#2 in the Tree Hygiene overview](https://github.com/flutter/flutter/wiki/Tree-hygiene)).

Once you've found or created an issue and linked it in this PR, I'll be happy to formally approve it. Great find and fix!

**Comment by passsy** [comment]
@pdblasi-google created the issue https://github.com/flutter/flutter/issues/108920

**Review by pdblasi-google — APPROVED** [review]

**Comment by pdblasi-google** [comment]
Great! Thanks @passsy, I'll add the `autosubmit` label and this should be merged shortly!

**Comment by pdblasi-google** [comment]
Apologies, looks like this needs a second contributor approval. I've reached out to get another review, and they'll handle it from here.

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
