### PR TITLE
Convert PointerInputEvent to Duration for timestamp

### PR DESCRIPTION
**Pull request by abarth**
To make the units clear.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @krisgiesing

**Comment by Hixie** [comment]
good call

LGTM

**Comment by krisgiesing** [comment]
I think you're truncating some data here (since Duration.inMilliseconds returns an int), but I suppose it doesn't matter, as long as the velocity tracker tests pass.

**Comment by abarth** [comment]
@krisgiesing The original data from Android only has millisecond granularity anyway...

**Comment by krisgiesing** [comment]
Fair enough.

**Pull request merged**
