### PR TITLE
Revert "Add visual density for menu default style"

### PR DESCRIPTION
**Pull request by QuncCccccc**
Reverts #114878

The reverted PR causes a Scuba failure on b/271378386. Will try a re-land later!

### CODE REVIEW

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

**Review by goderbauer — APPROVED** [review]
LGTM

For future archeologists: Can you add the reason for the revert to the PR description please.

**Review by chunhtai — APPROVED** [review]
LGTM

**Review by esouthren — APPROVED** [review]
LGTM

**Comment by QuncCccccc** [comment]
> LGTM
> 
> For future archeologists: Can you add the reason for the revert to the PR description please.

Just updated! Thanks:)

**Pull request merged**
