### PR TITLE
[Material] Remove "down position" from toggleable ripple calculation

### LINKED ISSUE #112278: Checkbox splash "jumps" when clicking with mouse
The jump is quick and a bit jarring. I would expect the splash to happen in the center of the checkbox, even when I click the corner of the checkbox. This effect happens on Switches and Radio buttons too.

See the expected behavior from the Material Design web library: https://material-components.github.io/material-components-web-catalog/#/component/checkbox

## Steps to Reproduce

Run the following app with a checkbox on desktop or web. Click on the corner of the checkbox, noticed the circle "jumps".

**Expected results:** 
giphy-1

**Actual results:** 
giphy-2

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const Scaffold(body: Body()),
    );
  }
}

class Body extends StatefulWidget {
  const Body({super.key});

  @override
  State<Body> createState() => _BodyState();
}

class _BodyState extends State<Body> {
  var _value = false;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Checkbox(
        value: _value,
        onChanged: (newValue) {
          setState(() {
            _value = newValue ?? false;
          });
        },
      ),
    );
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by johnsonmh**
|Before|After|
|-|-|
|giphy-2|giphy-1|

Closes https://github.com/flutter/flutter/issues/112278

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by HansMuller** [comment]
CC @guidezpl @QuncCccccc - I realize that this issue came up just recently. Can you-all check this PR's proposal, it still seems sensible to me to change this part of the checkbox's highlight, at least when responding to pointer (not touch) events.

**Review by guidezpl — APPROVED** [review]
Looks great, thanks MH! Can you just add an issue to the description?

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by whiskeyPeak** [comment]
Hmm, looking at the GIFs more carefully, the circle outline seems to get darker for one frame and then return back to being its normal shade of grey. This happens in both GIFs, but is more consistent in the first one.

**Comment by HansMuller** [comment]
@whiskeyPeak - I can see that as well and it's possible it's related to https://github.com/flutter/flutter/pull/111112. Appreciate it if you'd verify the problem on the master branch and file an issue if needed.

**Pull request merged**
