### PR TITLE
Add arena resolution when all entry types are the same

### PR DESCRIPTION
**Pull request by tlarsendataguy**
While working on an update to my app I noticed a delay was occurring between the time when I started physically dragging a picker widget and when the picker widget would actually start scrolling.  The picker was inside a scaffold, which builds its contents inside a ListView.  After some digging, I realized there was a competition going on between the scaffold's vertical drag gesture and the picker's vertical drag gesture.  After a certain amount of slop the gesture arena would award the winner to the picker and the picker would then jump to catch up to my finger.

I did not see an easy way to deal with this in the existing framework, so I added a resolution process to the gesture arena manager.  If all of the gesture arena entries have the same runtime type, it will make the first entry the winner.  In my case, this allows the picker to immediately win and respond to the drag gesture, which results in a much more fluid experience.  I think this logic makes sense in general, hence this PR.  I have not been able to arrive at a case where this behavior is undesirable.

Be advised that I had to update one of the tests in tap_test.dart.  The end result of that test is still the same, but the events now happen in a different order.  I do not know if this is a breaking change.

### CODE REVIEW

**Comment by tlarsen7572** [comment]
Thanks @amirh.  Is your concern primarily directed toward multi-pointer gestures, or does it encompass single-pointer gestures as well?  I can certainly see where this change might cause complications with multi-pointer gestures.  If this resolution only targeted descendants of OneSequenceGestureRecognizer, would that ease your concerns?  Or are there aspects of the state of single-pointer gestures I am missing?

**Comment by amirh** [comment]
Hi,

My concern is that we have no guarantee that 2 gesture recognizers with the same type are going to behave the same. Even if today we can look at the gesture recognizers in the framework and say that this is this case (I'm not sure it is, e.g you can set some fling parameters on DragGestureRecognizers) I can easily see these classes getting new configuration parameters, and we also have to consider gesture recognizers that are not part of the framework.

I do think we should look for a solution for the issue you mentioned. What do you think about filing an issue with a short code snippet that demonstrates the problem (a gesturedetector with vertical drag gesture inside a scrollable?) and we could discuss potential solutions there?

Thanks again for your contributions! would be great to improve the speed of gesture resolution.

**Comment by Hixie** [comment]
I don't think this is the right solution, because as amir says, it's possible for different instances of the same type of gesture recognizer to be looking for different gestures.

However, I do agree that the problem you describe is a real one. Would you mind filing a bug so that we can discuss possible solutions?

I'm going to close this PR in the meantime since we don't think it's the right approach. Thanks for your contribution though!

**Comment by tlarsen7572** [comment]
Sorry guys, real life took a bite out of my free time.  I will file the bug now.  Thanks for entertaining the PR, even if it wasn't the right direction to go in.

**Pull request closed without merging**
