### PR TITLE
Refine the directional traversal algorithm for out of band widgets

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This updates the directional traversal algorithm so that if you traverse down (or any other direction), and there isn't a widget below in the band created by the infinite height box the width of the currently focused widget, then we prefer the widget with one side closest to the band, and if there are two the same distance from the band, then we prefer the closest one vertically.

This layout used to do the wrong thing when you went down, preferring the one whose center was closest to the band, rather than the closest side:
<video src='https://user-images.githubusercontent.com/8867023/224839316-7d5f0975-5477-4de6-8af0-4759e5021710.mp4'></video>

And here is the new code:
<video src='https://user-images.githubusercontent.com/8867023/224839849-1f054f99-1dce-4d65-ad75-5f3346de89d1.mp4'></video>

## Tests
 - Added tests for both horizontal and vertical versions of the issue.

### CODE REVIEW

**Review by cbracken — APPROVED** [review]
Nice!

**Review by cbracken — COMMENTED** [review]
Is there any user-facing documentation that discusses the navigation key traversal behaviour? If so, does it already document this behaviour as now implemented?

**Review by yjbanov — COMMENTED** [review]
Does the accessibility traversal algorithm need to be updated too?

**Comment by gspencergoog** [comment]
> Does the accessibility traversal algorithm need to be updated too?
Accessibility traversal order in a direction is handled by the screen reader, we don't control that.

**Review by loic-sharma — APPROVED** [review]
LGTM but I'm not very familiar with this area :)

**Comment by gspencergoog** [comment]
There is some discussion [here](https://cs.opensource.google/flutter/flutter/+/master:packages/flutter/lib/src/widgets/focus_traversal.dart;l=492;drc=b1d8a4e4c7568f475e18ab13194904e284b27ba9), but it doesn't go into that much detail. I'll try and add some detail, but I worry a little that it might just be too much detail and their eyes will glaze over. :-)

**Pull request merged**
