### PR TITLE
Add Linux implementation of the platform view example

### PR DESCRIPTION
**Pull request by robert-ancell**

### CODE REVIEW

**Comment by robert-ancell** [comment]
Screenshot from 2023-03-30 12-37-21

**Comment by robert-ancell** [comment]
(The screenshot shows the wrong window title - fixed in the branch).

**Comment by Hixie** [comment]
@robert-ancell Is this still on your radar?

**Comment by robert-ancell** [comment]
Yes, @cbracken please review!

**Review by cbracken — APPROVED** [review]
lgtm!

**Comment by robert-ancell** [comment]
Build is failing due to:
```
/b/s/w/ir/cache/clang/bin/clang++ -g  CMakeFiles/platform_view.dir/main.cc.o CMakeFiles/platform_view.dir/my_application.cc.o CMakeFiles/platform_view.dir/flutter/generated_plugin_registrant.cc.o -o intermediates_do_not_run/platform_view -L/b/s/w/ir/x/w/flutter/examples/platform_view/linux/flutter/ephemeral -Wl,-rpath,/b/s/w/ir/x/w/flutter/examples/platform_view/linux/flutter/ephemeral:  -lflutter_linux_gtk  /usr/lib/x86_64-linux-gnu/libgtk-3.so  /usr/lib/x86_64-linux-gnu/libgdk-3.so  /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so  /usr/lib/x86_64-linux-gnu/libpango-1.0.so  /usr/lib/x86_64-linux-gnu/libharfbuzz.so  /usr/lib/x86_64-linux-gnu/libatk-1.0.so  /usr/lib/x86_64-linux-gnu/libcairo-gobject.so  /usr/lib/x86_64-linux-gnu/libcairo.so  /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so  /usr/lib/x86_64-linux-gnu/libgio-2.0.so  /usr/lib/x86_64-linux-gnu/libgobject-2.0.so  /usr/lib/x86_64-linux-gnu/libglib-2.0.so && :
ld.lld: error: undefined symbol: fl_method_call_get_type
>>> referenced by fl_method_call.h:19 (/b/s/w/ir/x/w/flutter/examples/platform_view/linux/flutter/ephemeral/flutter_linux/fl_method_call.h:19)
>>>               CMakeFiles/platform_view.dir/my_application.cc.o:(FL_METHOD_CALL(void*))
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```

For some reason the compiler must be optimizing this away, so I've made https://github.com/flutter/engine/pull/43394 to ensure this symbol is exported. Other get_type() functions already have this change.

**Comment by robert-ancell** [comment]
The build fix has landed in the engine, will rebuild this PR once that engine is being used by Flutter.

**Comment by robert-ancell** [comment]
@gspencergoog is the Google testing failure an issue?

**Comment by gspencergoog** [comment]
It is broken, but I think it's an error from a previous PR in the queue: it doesn't look related to this PR at all.  I'd try rebasing to HEAD and see if you can move to a state that builds.

[I'm not sure why you're the one that has bad luck here: this doesn't happen that often, I promise!]

**Pull request merged**
