### PR TITLE
Add onTertiaryTap* to TapGestureRecognizer and GestureDetector

### LINKED ISSUE #62488: Gesture detect Middle Mouse Button
## Use case

There seems to be a [`PointerEvent` for the middle mouse button](https://api.flutter.dev/flutter/gestures/kMiddleMouseButton-constant.html), however, I see no way to access it from widgets.

## Proposal

It would be very useful if you could have an `onMiddleMouseButtonPressed` callback on the widget level.

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
## Description

This PR aims to support the middle mouse button in Flutter (which is currently the only tertiary button).  
The naming decision **and** the decision to *omit the **tap** event* were derived from https://github.com/flutter/flutter/issues/62488#issuecomment-666488378.

cc @gspencergoog

## Related Issues

* Resolves #62488.

## Tests

I added the following tests:

* Tap gesture tests for the tertiary handlers.
* `GestureDetector` tests in all relevant files.
* Regression test for the bug fixed.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by gspencergoog** [comment]
@dkwingsmt Can you review this, since I'm out this week?

**Comment by goderbauer** [comment]
Fly-by comment: It looks like one of the new tests is failing on cirrus.

**Comment by creativecreatorormaybenot** [comment]
@goderbauer Thank you! Sorry that I was not thorough enough.

However, I do not understand why the `Tap down occurs after kPressTimeout (tertiary)` test is failing.  
Can someone help me with that?

**Comment by creativecreatorormaybenot** [comment]
(I am aware that tests-widgets are failing, however, I do not understand why that one test is failing)

**Review by dkwingsmt — CHANGES_REQUESTED** [review]
1. Since mouse is not the only device that can use a tertiary button, but also stylus, using `kMiddleMouseButton` is not accurate. Can you create a new `kTertiaryButton`, and replace all uses of `kMiddleMouseButton` in your new code to that?
2. We probably want to also add a `onTertiaryTap` callback just like the primary and secondary button.
3. The reason why the test fails is because the tertiary tap has no competition, which means the tertiary tap is accepted immediately on the down event. A primary or secondary tap, however, is competed by long press (thus the 2 long press callbacks) and must wait `kPressTimeout` before being accepted, which is interrupted by the drag. The solution is probably adding a tertiary long press callback. Also since you're confused by it, it'd be best if you can add a comment to explain this at the 2 long press callbacks.

Everything else looks good.

**Comment by creativecreatorormaybenot** [comment]
@dkwingsmt Thank you so much for the review!

About 2. and 3.: I think that @gspencergoog pointed out that we might not want to have the other callbacks for tertiary pointers, https://github.com/flutter/flutter/issues/62488#issuecomment-666488378.

What you said is logical to me - I just want to make sure that we are clear on that 👍🏼

**Comment by dkwingsmt** [comment]
Sounds good :)

**Comment by creativecreatorormaybenot** [comment]
@dkwingsmt So I think it is just fixing `1.` now and adjusting the tests to address that there are no long presses?

**Comment by dkwingsmt** [comment]
I think he didn't say we shouldn't add the tertiary version of long press. But I don't think we NEED to add that either, at least before real demands come; but then to use the same logic of variants you might still need to create a private one just for this test. I can't think of other ways if we want too reuse the variant logic.

**Comment by creativecreatorormaybenot** [comment]
@dkwingsmt that sounds good 👍🏽

**Comment by creativecreatorormaybenot** [comment]
@dkwingsmt I think I addressed everything.

I only added the tertiary long press callbacks to the `LongPressGestureRecognizer` but not to `GestureDetector` because they are not needed there.  
Consequently, I used `RawGestureDetector` instead in the tests that used long presses with variants.

Additionally, I fixed a bug that would not allow primary and secondary callbacks to be used together on `GestureDetector`s *and* I included a **regression test** for this fix (last commit).

**Comment by creativecreatorormaybenot** [comment]
Fixes #62895.

I hope it is fine to include the fix in this PR. I do not see why not, though.

**Comment by creativecreatorormaybenot** [comment]
(I decided to move a fix I did to another PR, see #62897)

**Comment by creativecreatorormaybenot** [comment]
@dkwingsmt Seems like the tests are all fine now.

If I got the implementation right, this should be done 🙂

**Review by dkwingsmt — APPROVED** [review]
LGTM, great job!

**Comment by dkwingsmt** [comment]
Seems a conflict is blocking the merge.

**Comment by creativecreatorormaybenot** [comment]
@dkwingsmt resolved.

**Pull request merged**
