### PR TITLE
[flutter_tools] stop using `dart pub __deprecated_pub`

### PR DESCRIPTION
**Pull request by christopherfujino**
Related to https://github.com/dart-lang/pub/issues/3458#issuecomment-1172291741

### CODE REVIEW

**Comment by christopherfujino** [comment]
It looks like the reason we initially couldn't use `dart pub get` was: https://github.com/flutter/flutter/pull/88792#issuecomment-906513700

**Comment by sigurdm** [comment]
I think this should be unproblematic if we land: https://github.com/flutter/flutter/pull/106300 that no longer relies on `--verbosity=warning`

**Comment by christopherfujino** [comment]
closing as stale

**Comment by sigurdm** [comment]
I don't think this is stale - still should happen, just will be much easier now.

**Comment by sigurdm** [comment]
Ah - sorry - thought this was the issue :)

**Pull request closed without merging**
