### PR TITLE
Wrap the ReorderableList's children with a MergeSemantics

### LINKED ISSUE #20589: ReorderableListView needs to merge semantics on draggables
We have a `ReorderableListView` that contains a list of SwitchListTiles. Right now, the accessibility actions for reordering that the ReorderableListView defines are not read aloud because the SwitchListTile defines its own set of semantics. We need the draggable widget to be wrapped in a `MergeSemantics`. Since the `ReorderableListView` is creating the draggables itself, wrapping our passed in widget, I believe this has to be fixed by the reorderable list view widget.

### PR DESCRIPTION
**Pull request by DaveShuckerow**
This prevents the list's semantics from getting hidden by children that have semantics in them.

Fixes #20589 

cc @alanrussian

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
This doesn't have any implications for the Gallery example does it?

LGTM.

**Comment by DaveShuckerow** [comment]
No, all custom actions remain accessible in the gallery.

**Comment by Hixie** [comment]
@fkorotkov when this landed on master, the Windows bot just spun not doing anything for over an hour: https://cirrus-ci.com/task/6614532319346688

Not at all clear why.

**Comment by fkorotkov** [comment]
Seems like the same Azure issue. I've reported these performance issues you've seen to Azure support and they are looking into it.  I doubt they'll find anything so I'm concidering switching back to GCP in that case.

**Pull request merged**
