### PR TITLE
Clean up the bindings APIs.

### LINKED ISSUE #64830: Clean up Binding.instance
With nnbd, we're making all the FooBinding.instance singletons nullable, and sprinkling `!`s everywhere. We should instead make them non-nullable and have a good error message when you read them as null, and if anyone needs to know if the instance is set up, have a separate flag.

### LINKED ISSUE #78028: Restore error message explaining the need to call WidgetsFlutterBinding.ensureInitialized()
When using `shared_preferences: ^2.0.4`, when calling `SharedPreferences.getInstance()` I get a null check exception.

Fails on 

- macOS
- iOS
- Android

Succeeds on

- Web

### Flutter version & devices
```
Flutter 2.1.0-10.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision cc9b78fc5c (2 weeks ago) • 2021-02-25 13:26:03 -0800
Engine • revision a252ec09b7
Tools • Dart 2.13.0 (build 2.13.0-77.0.dev)

SM S102DL (mobile)     • RF8N737S2CR                              • android-arm    • Android 10 (API 29)
Luke's iPhone (mobile) • 0bc0c4864d8e08aac4456893cded68bf0b6767d5 • ios            • iOS 14.4
macOS (desktop)        • macos                                    • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
Chrome (web)           • chrome                                   • web-javascript • Google Chrome 89.0.4389.82
```

## MCVE

```yaml
name: shared_preferences_macos_issue
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```

```dart
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() async {
  final prefs = await SharedPreferences.getInstance();

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: Text('shared_preferences error'),
        ),
      ),
    );
  }
}

```

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
#0      MethodChannel.binaryMessenger
package:flutter/…/services/platform_channel.dart:142
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:148
#2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:331
#3      MethodChannel.invokeMapMethod
package:flutter/…/services/platform_channel.dart:358
#4      MethodChannelSharedPreferencesStore.getAll
package:shared_preferences_platform_interface/method_channel_shared_preferences.dart:44
#5      SharedPreferences._getSharedPreferencesMap
package:shared_preferences/shared_preferences.dart:181
#6      SharedPreferences.getInstance
package:shared_preferences/shared_preferences.dart:57
#7      main
package:shared_preferences_macos_issue/main.dart:5
#8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:146:25)
#9      _rootRun (dart:async/zone.dart:1354:13)
#10     _CustomZone.run (dart:async/zone.dart:1258:19)
#11     _runZoned (dart:async/zone.dart:1789:10)
#12     runZonedGuarded (dart:async/zone.dart:1777:12)
#13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:139:5)
#14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

### PR DESCRIPTION
**Pull request by Hixie**
* Add more documentation.
* Make premature binding accesses have better runtime errors.
* Make accesses to `instance` not required `!`.
* Rationalize our "ensureInitialized" etc logic.

Fixes flutter#64830
Fixes flutter#78028

Most of these changes were done using `dart fix --apply`, but they have been squashed into one commit for easier merging.
To see previous reviews of this PR, see
flutter#83843,
flutter#86388,
flutter#86438, and
flutter#89451.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
This is blocked on finding a way to migrate Google's code.

**Comment by skia-gold** [comment]
Gold has detected about 3 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/89451

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/89451

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/89451

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/89451

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/89451

**Comment by skia-gold** [comment]
Gold has detected about 5 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/89451

**Comment by skia-gold** [comment]
Gold has detected about 2 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/89451

**Comment by nt4f04uNd** [comment]
Also linked flutter#78028 as being fixed by this

**Comment by Hixie** [comment]
@goderbauer google3 is getting close to ready to receive this, would you mind stamping it one more time so that I can land it when it's ready?

**Review by goderbauer — APPROVED** [review]
RSLGTM

I did not review this closely again assuming that it is largely unchanged from the last time I looked at it. If there are major changes anywhere that I should take a closer look please let me know.

**Comment by Hixie** [comment]
There's no new major changes, it's all just the same mechanical changes being applied to new code.

**Comment by Hixie** [comment]
This will need to wait for @dnfield's PR #92509 to roll into Google before it can be tested, if I understand correctly.

**Pull request merged**
