### PR TITLE
Implement 'reversed' parameter for Flex

### PR DESCRIPTION
**Pull request by robiot**
This pull request implements the "reversed" parameter for the Flex widget and can be enabled for other widgets extending `MultiChildRenderObjectWidget`.  This makes it possible to easily replicate css's features `flex-direction: row-reverse` and `flex-direction: column-reverse`.

### Here is an example scenario where this feature can be useful.
This is how you would do it **without** this feature. It is not ergonomic if you want a clean code structure. And if you are going to have multiple lists of children that should be reversed, it would be a mess.

```dart
import "package:flutter/material.dart";

// Without this feature
class TestPage extends StatelessWidget {
  const TestPage({
    super.key,
    this.dividerFirst = false,
  });

  /// If the divider should be on top instead of bottom (default)
  final bool dividerFirst;

  @override
  Widget build(context) {
    const List<Widget> children = [
      Divider(
        color: Color(0xFFFF0000),
        thickness: 1.5,
      ),
      SizedBox(height: 50),
      Text("Hello world")
    ];

    return Center(
      child: Flex(
        direction: Axis.vertical,
        children: dividerFirst ? children : children.reversed.toList(),
      ),
    );
  }
}

```
With this feature however. It would look something along the lines of this:
```dart
import "package:flutter/material.dart";

// With feature
class TestPage extends StatelessWidget {
  const TestPage({
    super.key,
    this.dividerFirst = false,
  });

  /// If the divider should be on top instead of bottom (default)
  final bool dividerFirst;

  @override
  Widget build(context) {
   return Center(
      child: Flex(
        direction: Axis.vertical,
        reversed: !dividerFirst,
        children: const [
          Divider(
            color: Color(0xFFFF0000),
            thickness: 1.5,
          ),
          SizedBox(height: 50),
          Text("Hello world")
        ],
      ),
    );
  }
}
```

### Resolves
- #54821

### CODE REVIEW

**Comment by robiot** [comment]
There is a more convenient way of implementing it which involves making the children non final, which I will commit soon. If the current way of doing it is preferred, a revert can be done.

**Comment by robiot** [comment]
Now to make a Widget extending `MultiChildRenderObjectWidget` to support the "reversed" feature, it will only need to include super.reversed in the constructor.

Before:
```dart
Flex({
  super.key,
  ...
  super.children,
  super.reversed,
});

@override
List<Widget> get children => reversed ? super.children.reversed.toList() : super.children;
```
Now:
```dart
Flex({
  super.key,
  ...
  super.children,
  super.reversed,
});
```

There is just a slight issue with `@immutable` (which makes CI angry (Linux analyze/analyze-linux)).
image
Every subclass to `MultiChildRenderObjectWidget` needs `// ignore: must_be_immutable` for CI to be happy, which isn't convenient at all. If there is any way to drop the `@immutable` inherited from the superclass of `MultiChildRenderObjectWidget`, the warnings would disappear.

If that's not possible, I can revert to the old logic/solution.

**Review by lucemans — COMMENTED** [review]
Documentation present,
Includes tests,
Seems clear,
Would love to see these changes in the next flutter release!

**Comment by robiot** [comment]
One fix would be to remove the immutable from the `Widget` class. Tho I don't know what this means for all the other Widgets that are subclasses (unsafe, allowing mutable stuff or whatever) except that it resolves warnings.

https://github.com/flutter/flutter/blob/937165019d024c39f77e67b43409bda2db3bc92a/packages/flutter/lib/src/widgets/framework.dart#L299

**Comment by navaronbracke** [comment]
@robiot Can't you use an initializer expression that sets children? Then the `children` property can stay final.
Also, there is an open TODO for making `MultiChildRenderObjectWidget` const in the future, so keeping children final is preferred.

```
  MultiChildRenderObjectWidget({ super.key, List<Widget> children = const <Widget>[], this.reversed = false })
    : this.children = reversed ? children.reversed.toList() : children, assert(children != null) {
    assert(() {
      for (int index = 0; index < children.length; index++) {
        // TODO(a14n): remove this check to have a lot more const widget
        if (children[index] == null) {
          throw FlutterError(
            "$runtimeType's children must not contain any null values, "
            'but a null value was found at index $index',
          );
        }
      }
      return true;
    }()); // https://github.com/dart-lang/sdk/issues/29276
  }
```

I did get one `unnecessary_this` warning but that is only to avoid shadowing (as the lint suggests) so if needed an ignore can be added just above `: this.children = ...`

**Comment by robiot** [comment]
@navaronbracke Thank you. That is perfect! :+1: 
I tested without using `this` to access children and it worked perfectly fine. So I suppose it isn't needed.

**Comment by robiot** [comment]
Now all checks should hopefully pass, and there is no need to mess with the mutability on the Widget class.

**Review by svemat01 — COMMENTED** [review]
LGTM! Great work including tests :)

**Comment by robiot** [comment]
Hey @goderbauer. Mentioning you because you recently were active. Could you, or anyone else in the team review this pr, or just leave some thoughts or whatever :)

**Comment by robiot** [comment]
I get your point @goderbauer. But there would still be boilerplate code if I for example wanted to have that wrapper widget in multiple projects. Yes, I could create a package out of it. But having a package, only containing a single widget that only reverses children would be a total waste.

I don't personally think it will be confusing having the children reversed since you are explicitly setting that variable, which has a descriptive name. CSS has this feature, and I have not seen a single individual being confused over why the children are reversed when setting "flex-direction: row-reverse".

If there is absolutely no chance of implementing the reversed parameter to the flex widget, we could make a Reversed() widget instead. One problem with this is that the `direction` most likely wouldn't work.

```dart
 import "package:flutter/material.dart";

// With feature
class TestPage extends StatelessWidget {
  const TestPage({
    super.key,
    this.dividerFirst = false,
  });

  /// If the divider should be on top instead of bottom (default)
  final bool dividerFirst;

  @override
  Widget build(context) {
    return Center(
      child: Flex(
        direction: Axis.vertical,
        children: [
          Reversed(
            reversed: !dividerFirst
            children: const [
              Divider(
                color: Color(0xFFFF0000),
                thickness: 1.5,
              ),
              SizedBox(height: 50),
              Text("Hello world")
            ],
          ),
        ],
      ),
    );
  }
}
```

So what I'm saying is that this feature would simplify the workflow for lots of people (20 thumbs up in #54821), and think it should be implemented. 

Br

**Comment by gspencergoog** [comment]
It is fairly easy to make your own `ReversableFlex` widget for your own project (it's only a few lines), so there's not a big advantage to putting it into the framework, and as @goderbauer mentioned, it has some drawbacks with people misinterpreting the order when the `children` list is explicit, and not just a variable.

That said, thank you for your contribution, we do appreciate the effort. At this time this is not really the direction in which we would like to take the project. If you are interested in pursuing this further I would encourage you to discuss it in the Discord chat. A design doc may be a good way to socialize this idea with the rest of the team too.

**Comment by robiot** [comment]
Thanks for the feedback @gspencergoog! I suppose r/FlutterDev is the Discord guild you directed to.

**Comment by gspencergoog** [comment]
@robiot No, I was referring to the official Flutter discord channel described in the Wiki [here](https://github.com/flutter/flutter/wiki/Chat). Sorry, I should have linked that.

**Pull request closed without merging**
