### PR TITLE
Align doubles to 8 bytes in the StandardMessageCodec

### PR DESCRIPTION
**Pull request by jason-simmons**
See https://github.com/flutter/flutter/issues/10701

### CODE REVIEW

**Comment by jason-simmons** [comment]
@mravn-google

**Review by mravn-google — APPROVED** [review]
We need to add a unit test for this.

Otherwise, LGTM

**Comment by jason-simmons** [comment]
Added a test of the new encoding to message_codecs_test

**Comment by mravn-google** [comment]
Thanks!

**Review by tvolkert — APPROVED** [review]
The Chromium bots are done with the engine builds, so you can rev the engine to `784e9756720f7f6daa15c95ba3df6215bb54783f` in this now.

Then LGTM!

**Pull request merged**
