### PR TITLE
Parse .flutter-plugins-dependencies for add-to-app iOS modules, remove no-op plugin iOS folder

### LINKED ISSUE #60215: `flutter create -t plugin` should not create no-op iOS folders in 1.20.0 stable release
When 1.20 releases, we should make `flutter create -t plugin` command not creating no-op iOS folders anymore.
Also, we will add a lower flutter SDK bound setting to 1.20.0 for all the newly created plugins. 

Ideally, we'd like to land this change to the 1.20.0 release branch as it goes out.

### PR DESCRIPTION
**Pull request by jmagman**
## Description

1.20 cherry-pick of https://github.com/flutter/flutter/pull/61269 and #61561.

There was a merge conflict related to the integration test so I removed the rename cleanup, but it's testing the same thing.  The podhelper Ruby code is identical to that PR

Fixes https://github.com/flutter/flutter/issues/60215.

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
The merge base of this PR should be `flutter-1.20-candidate.7`, however.

**Review by christopherfujino — CHANGES_REQUESTED** [review]
please change the merge target to branch `flutter-1.20-candidate.7`

**Comment by jmagman** [comment]
> please change the merge target to branch `flutter-1.20-candidate.7`

Done.

**Review by christopherfujino — APPROVED** [review]
LGTM again

**Review by xster — APPROVED** [review]

**Comment by cyanglaz** [comment]
We still need to bump the low SDK constraint to 1.20.0, should we do it in this PR?

**Review by pcsosinski — APPROVED** [review]
customer_testing-* failures are expected for the 1.20 branch (https://github.com/flutter/flutter/issues/57062)

**Comment by cyanglaz** [comment]
we need to include https://github.com/flutter/flutter/pull/62605 in this CP otherwise the newly created plugin will fail when publishing.

**Comment by pcsosinski** [comment]
does it need to go into master?  or just added to this PR?

**Pull request merged**
