### PR TITLE
Add `textCapitalization` property for `SearchBar` and `SearchAnchor`

### LINKED ISSUE #131260: textCapitalization option for SearchBar
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Using the new material 3 [SearchBar](https://api.flutter.dev/flutter/material/SearchBar-class.html), it would be nice to be able to pass in the [TextCapitalization](https://api.flutter.dev/flutter/services/TextCapitalization.html) to use in the TextField.

For example, if I have a SearchBar where the user can search a list of things, **or create one if it doesn't exist in the list**, sometimes I want those new things to begin with a capital letter as default without the user having to manually use shift to capitalize the first letter. Currently this is not possible.

### Proposal

Currently this is what happens by default when you type into SearchBar without manually using shift to capitalize the first letter:

image

To allow this to default to "New thing", it's a really easy addition: allow passing in a [TextCapitalization](https://api.flutter.dev/flutter/services/TextCapitalization.html) property:
```
SearchBar(
   hintText: "Search or create",
   onChanged: widget.onChanged,
   textCapitalization: TextCapitalization.sentences,
)
```
And apply this to [the TextField in SearchBar](https://github.com/flutter/flutter/blob/c8b9b15e4cd14de5ba46fafb476ac198da63fea5/packages/flutter/lib/src/material/search_anchor.dart#L1255):

```
                      TextField(
                        ...
                        // ADD THIS:
                        textCapitalization: widget.textCapitalization,
                      )
```

### PR DESCRIPTION
**Pull request by QuncCccccc**
This is to add `textCapitalization` property for `SearchBar` and `SearchAnchor`.
Fixes: #131260

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by HansMuller** [comment]
Shouldn't this property also be exposed in  the SearchBarTheme?

**Comment by HansMuller** [comment]
It looks like the tests, e.g. 'SearchBar respects textCapitalization property' need to be extended a little to also verify that the theme parameter does the right thing.

**Comment by QuncCccccc** [comment]
> It looks like the tests, e.g. 'SearchBar respects textCapitalization property' need to be extended a little to also verify that the theme parameter does the right thing.

Ah I added this check in `search_bar_theme_test.dart`. The tests in this file are checking `textCapitalization` can be overridden by searchBar's `textCapitalization`, then `SearchBarThemeData.textCapitalization`, and then overall theme's searchBarTheme.textCapitalization.

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by lukaszciastko** [comment]
Hi, shouldn't the services.dart be an absolute reference? This is the pattern across the whole of Material. I just spotted this, because I have a script that relies on these dependencies while copying Material classes into a custom folder.

**Comment by QuncCccccc** [comment]
> Hi, shouldn't the services.dart be an absolute reference? This is the pattern across the whole of Material. I just spotted this, because I have a script that relies on these dependencies while copying Material classes into a custom folder.

Thanks for catching this! Created a fix PR(#140425)!

**Pull request merged**
