### PR TITLE
Revert "Always evaluate the finder in `driver.waitFor*()`"

### PR DESCRIPTION
**Pull request by Hixie**
Reverts flutter/flutter#11434

This patch landed around the same time as we changed devices, and it had an odd impact on the numbers, mostly making them much less noisy. I think this makes sense given the fix, but I'm curious to see if removing this patch also reverts the change, or if it's actually all about the hardware change. I suspect it may be all hardware since little changed on iOS over the same time period.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
LGTM. Wondering why GitHub is showing that you are reverting 9 commits.

**Comment by Hixie** [comment]
Weirdly they're all empty...

**Comment by Hixie** [comment]
I'll land this on green after I've rolled internally.

**Pull request merged**
