### PR TITLE
Unnecessary new

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by a14n** [comment]
@Hixie

I've push the 3 commits to split changes:
- the first commit is the result of a script to remove `new ` pointed out by the `unnecessary_new` lint
- the second commit to fix analysis
- the last one to fix tests

**Comment by Hixie** [comment]
It looks like the `## Sample code` sections didn't get updated by this. I don't understand how this passed the analysis step... are we using the wrong set of lints for the sample code analysis?

**Comment by a14n** [comment]
>It looks like the `## Sample code` sections didn't get updated by this. I don't understand how this passed the analysis step... are we using the wrong set of lints for the sample code analysis?

Looking at `dev/bots/analyze-sample-code.dart` it seems that no lints are used to analyze sample code.

We could update `dev/bots/analyze-sample-code.dart` in an other PR.

**Comment by Hixie** [comment]
Ah, bummer. Yeah, we should definitely run lints in that script!

**Comment by Hixie** [comment]
Maybe we should make that change first, actually, so that we are consistent throughout about `new`.

**Comment by a14n** [comment]
Actually there are already places where `new` or `const` have been omitted. Moreover `unnecessary_const` is already activated in code but not in sample. So I don't think the order of changes are important.

**Comment by Hixie** [comment]
The omission of `new` in various places (so that we're inconsistent) is a problem.

**Comment by a14n** [comment]
First step for lint on sample codes done in #21155 ( review welcome ;) )

**Comment by a14n** [comment]
CI ok, PTAL

**Comment by a14n** [comment]
@Hixie : Oops! I'm really sorry! I confused your RSLGTM on flutter/plugins#701 with this PR and I've merged it :-(
Should I revert the merge for this current PR?

**Comment by a14n** [comment]
BTW: what's the workflow to follow in the case of such a mistake?

**Comment by a14n** [comment]
@goderbauer any advice as you seem online?

**Comment by goderbauer** [comment]
I don't think we have a process for this. You could just revert this. However, as I understand it, the only remaining problem is that we are still showing `new` in various sample codes? If you can fix that quickly you can send it to me for review and we should be good as it is? Otherwise, I'd probably revert this PR for now.

**Comment by a14n** [comment]
Acutally `new` in samples have already been remove by #21539 . I was wondering if the flutter team had something in mind blocking this PR that I was not aware of.
What bother me is that this merge is so huge that any revert and/or all current PR will have conflict for merging.

**Comment by goderbauer** [comment]
I am not aware of anything that would be blocking this. Let's leave this PR in. Here is my post-submit LGTM :)

LGTM

**Comment by a14n** [comment]
Thanks

**Pull request merged**
