### PR TITLE
PathProvider.getTemporaryDirectory() never resolves

### LINKED ISSUE #3683: PathProvider.getTemporaryDirectory() never resolves on android
## Steps to Reproduce

Call "await PathProvider.getTemporaryDirectory()" on an android simulator or android hardware (S5)
I have not tested on iOS.

## Flutter Doctor

```
app (dev *)$ flutter doctor
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /usr/local/google/home/drewwarren/flutter
    • Framework revision 5460e94488 (3 hours ago), engine revision 76d5cf230a

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/users/drewwarren/aswb-sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-119990345-117822431)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
app (dev *)$ flutter devices
2 connected devices:

Android SDK built for x86 64 • emulator-5554 • android-x64
SM G900V                     • 5c1103af      • android-arm
app (dev *)$ 
```

## Logs and Crash Reports

```
    print("getting dir");
    Directory dir = await PathProvider.getTemporaryDirectory();
    print("got dir");
```
output:
```
I/flutter : getting dir
```

### PR DESCRIPTION
**Pull request by abarth**
We were looking for this service in the wrong service provider.

Fixes #3683

### CODE REVIEW

**Comment by abarth** [comment]
@chinmaygarde

**Comment by abarth** [comment]
@jason-simmons

**Comment by Hixie** [comment]
LGTM

**Comment by eseidelGoogle** [comment]
Presumably we have no way to do platform-specific testing like this yet?

(FYI @yjbanov)

**Comment by abarth** [comment]
We can write a shallow test against a mock, but this is really an integration issue and we don't have a great integration testing story yet.

**Comment by yjbanov** [comment]
@eseidelGoogle 

> Presumably we have no way to do platform-specific testing like this yet?

Widget tests, no. Driver tests running on a real device, I can't see why not.

**Pull request merged**
