### PR TITLE
Random color

### PR DESCRIPTION
**Pull request by dsrenesanse**
getter which returns random color from primaries

### CODE REVIEW

**Comment by Renesanse** [comment]
I signed it!

**Comment by dnfield** [comment]
Is there an issue open related to this?

Normally I'd be asking you to fill out the template that seems to be missing from this PR - in particular the parts about adding a test, making sure analysis passes, and linking to an issue where this has been discussed and requested.  If this change is to be merged, then those things really should be done.  But I'm not entirely sure this really belongs in the framework - is it really something that most or even many Flutter apps would need, and is its complexity high enough to say that even those apps that want it shouldn't have to re-implement it or consume it as a separate package?

**Comment by dnfield** [comment]
(I'm going to try again - on rereading my initial post I don't know that I expressed myself the way I really wanted to).

Thanks for the contribution, and taking care of the CLA!

This should really have a linked issue discussing why we want this change and what it's going to solve.  It also needs a test and its analysis issues cleaned up.

I'm entirely open to hearing more about why this change belongs in the framework, but I suspect it's something that only a few apps would use and could be implemented fairly simply as either a package or a snippet for the apps that need it.  Could you explain more about why this should go into the framework?

**Comment by Renesanse** [comment]
I guess the case is : When you using map method of some collection to return collection with widgets, it will be very useful to show different colors of each item. For example : to show boundaries, or design where user needs a random color (avatar background).

**Comment by dnfield** [comment]
In that case wouldn't it be preferable to use a gradient or to use something like the way [D3](https://github.com/d3/d3-scale-chromatic/blob/master/README.md) does this kind of logic?  Randomized colors in a list could end up looking very unpleasant.

**Comment by dnfield** [comment]
(I really do like the idea of a package that would help with this kind of thing though - creating nice looking gradients and color schemes for lists, charts, etc!)

**Pull request closed without merging**
