### PR TITLE
Roll dependencies

### PR DESCRIPTION
**Pull request by Hixie**
test-exempt: rolling dependencies

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM. out of curiosity do you need something from this roll?

**Comment by christopherfujino** [comment]
Ahh, the autoroll PR had failing tests: https://github.com/flutter/flutter/pull/139589. If presubmits pass here i'll manually close that one.

**Comment by christopherfujino** [comment]
I'm guessing customer_testing failures are legit then?

**Comment by Hixie** [comment]
I wanted to submit a PR that updated a pubspec.yaml, so I needed the dependencies to be up to date. I forgot we have a bot that does this these days.

**Pull request merged**
