### PR TITLE
Added multiple Cupertino icons

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
I do not understand why the checks fail. I believe that everything should be fine.

**Comment by goderbauer** [comment]
Looks like a flake. I have restarted the check for you.

**Comment by creativecreatorormaybenot** [comment]
For some commits `tool_tests-macos` were failing. This seems odd since it appears to not be related to the actual commits.

**Comment by xster** [comment]
LGTM. Thanks for your contributions

**Comment by xster** [comment]
The `tests-linux` status getter on GitHub seems stuck since Cirrus actually finished running. Merging.

**Comment by zoechi** [comment]
Related to #16102

**Pull request merged**
