### PR TITLE
Use arrow function in README example

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
sky_sdk isn't a real repository... Right now it's generated from a scirpt in mojo.

You probably mean:
https://github.com/domokit/mojo/tree/master/sky/sdk

**Comment by eseidelGoogle** [comment]
I'll make this change in mojo for you. :)

**Comment by eseidelGoogle** [comment]
https://codereview.chromium.org/1091613002

**Comment by sethladd** [comment]
For anyone following along... we decided not to use the arrow function. 99% of the time, a developer will want to build a more complicated set of nodes.

**Pull request closed without merging**
