### PR TITLE
Rename BannerLocation enum values

### PR DESCRIPTION
**Pull request by abarth**
* topLeft -> topStart
 * topRight -> topEnd
 * bottomLeft -> bottomStart
 * bottomRight -> bottomEnd

These names will make it easier for us to adjust the location of the
banner in right-to-left mode.

See the discussion on flutter-dev.

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
I suspect I've fixed all the test failures in my TextPainter patch. You may wish to wait for me to land that first.

**Comment by abarth** [comment]
Ok.  /me waits

**Comment by Hixie** [comment]
Ok, TextPainter patch landed.

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
