### PR TITLE
Owesome validator

### PR DESCRIPTION
**Pull request by osamaasifoak**
A very helpful flutter package for form validation.

## Description

A package for flutter for validation based on pure dart code will provide the most common validation like name, email, password, contact, etc.

## Related Issues
 [FOR ISSUES](https://github.com/osamaasifoak/owesome_validator/issues)

## PUB DEV LINK
 [pubdev.com](https://pub.dev/packages/owesome_validator)

### CODE REVIEW

**Comment by sidrao2006** [comment]
Hey @osamaasifoak could you please explain your changes. Why are you trying to add your package to the flutter repo?

Thanks

**Comment by goderbauer** [comment]
Looks like this package is already available in pub and can be obtained from there: https://pub.dev/packages/owesome_validator.

**Comment by osamaasifoak** [comment]
Hi @sidrao2006, Sorry for the late reply. I created this package for helping the community and I believe by adding this package into the flutter repository give more exposure to package and more people can reach it easily.

**Comment by osamaasifoak** [comment]
Hi @goderbauer, yeah the package is also available on pub dev and I am maintaining it continuously.

**Pull request closed without merging**
