### PR TITLE
Make CircularProgressIndicator's animation match native

### PR DESCRIPTION
**Pull request by coin3x**
## Description

This PR adjusts the animation of CircularProgressIndicator using values from AOSP repo. 
[Screen recording demonstrating the change](https://i.imgur.com/FACfZ4S.mp4)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Comment by shihaohong** [comment]
Hi @coin3x, could you provide a link to the specs you used for these changes? I believe the goal is here to achieve the look and feel in the [Material spec](https://material.io/components/progress-indicators/#circular-progress-indicators) as closely as possible, but the spec doesn't seem to go into enough detail on the changes that you're intending to make in this PR. 

@HansMuller might be able to chime in with what the intended values are supposed to be and if we are aligned with the spec or not.

**Comment by coin3x** [comment]
Sure, the 1333ms and 2222ms (4444/2) are  extracted from the following two files
[progress_indeterminate_material.xml](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/res/res/anim/progress_indeterminate_material.xml)
[progress_indeterminate_rotation_material.xml](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/res/res/anim/progress_indeterminate_rotation_material.xml)
which are referenced in [progress_indeterminate_anim_medium_material.xml](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/res/res/drawable/progress_indeterminate_anim_medium_material.xml)

**Comment by shihaohong** [comment]
Thanks! Just eyeballing the animations, it does look like your progress indicator animation looks closer to the one observed in the Material spec. Let's see what Hans says and we can move forward from there. 

We might have to also consider adding a test for the animation and a breaking change announcement, since anybody who has golden tests with a progress indicator in it will likely have them fail.

**Comment by shihaohong** [comment]
A quick update -- We are going to have some designers look at the video and the diffs to verify that this is closer to the spec. Let's wait for their feedback first before proceeding with this PR :) 

cc/ @willlarche

**Comment by dkwingsmt** [comment]
Will is OOO for a while. In the mean time, @coin3x can you add in the comparison of the new circular progress indicator with the OEM (system native) one? It's not the difference of the old and the new that we care about, but the similarity of the new and the OEM one :)

**Comment by coin3x** [comment]
Uploaded here 🎞️
[Comparison with native progress indicator](https://i.imgur.com/PxNW4if.mp4)

**Comment by dkwingsmt** [comment]
@coin3x That animation looks perfect! Did you make it using a single app? If so, can you send over the apk?

**Comment by coin3x** [comment]
@dkwingsmt The video above is two screen recordings combined because it's easier to adjust timing in video editor. Nevertheless, I made a crappy demo consisted

**Comment by coin3x** [comment]
@dkwingsmt The video above is two screen recording combined because Flutter engine needs a bit time to start and it's easier to adjust timing in video editor, however I made an app containing progress indicator in both native and Flutter, and it allows you to restart the animation of native one.
[Link to APK](https://coin3x.github.io/pi-arm64.apk)

**Comment by dkwingsmt** [comment]
Thank you so much. I’ll seek someone to verify it soon.

**Comment by willlarche** [comment]
Approved by motion design with enthusiastic thanks!!

**Comment by dkwingsmt** [comment]
Update: While trying to write a test for this change, we came up with an idea of composing the animation of the widget into a sprite grid and test with golden. We think it's a good opportunity to write a universal utility matcher, since this demand has been around for a while. We're trying to finish that before applying it to test this change.

**Comment by dkwingsmt** [comment]
Hello @coin3x! The Animation Sheet Builder is finally in with https://github.com/flutter/flutter/pull/55527. It's been a long time but I'm sure it's worth it, because it can test animations with an animation sheet that look like this:
material circular_progress_indicator indeterminate

Can you add a test such as the following snippet to the PR? We'll have this PR merged as soon as it's done.

```dart
  testWidgets('Indeterminate CircularProgressIndicator uses expected animation', (WidgetTester tester) async {
    final AnimationSheetBuilder animationSheet = AnimationSheetBuilder(frameSize: const Size(40, 40));

    await tester.pumpFrames(animationSheet.record(
      const Directionality(
        textDirection: TextDirection.ltr,
        child: Padding(
          padding: EdgeInsets.all(4),
          child: CircularProgressIndicator(),
        ),
      ),
    ), const Duration(seconds: 2));

    tester.binding.setSurfaceSize(animationSheet.sheetSize());

    final Widget display = await animationSheet.display();
    await tester.pumpWidget(display);

    expect(
      find.byWidget(display),
      matchesGoldenFile('material.circular_progress_indicator.indeterminate.png'),
    );
  });
```

Also the CLA check seems to be off, can you also take a look?

**Comment by coin3x** [comment]
@googlebot rescan

**Comment by coin3x** [comment]
@dkwingsmt Merged upstream and added the test. Not sure what I should do with the CLA check.

**Comment by dkwingsmt** [comment]
CLA looks fine now. Alright here's a problem: recently Flutter changed the versioning convention, and branches created earlier than that will no longer work. As a result, `flutter --version` will show a "0.0.0-unknown" version.

Here's how to fix it.

```bash
# Optionally, create a backup branch, just in case something's messed up
git branch progress-backup 
# Do a pull, because I changed a line to add a skip to the test
git pull
# Do a soft reset to upstream master
git reset --soft upstream/master
# Commit all the files
git commit -a
```

You should be able to run `flutter version -v` and see the correct version. Now do a force push:

```
git push -f
```

**Comment by skia-gold** [comment]
Gold has detected about 1 untriaged digest(s) on patchset 2.
Please triage them at https://flutter-gold.skia.org/search?issue=50412.

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Pull request merged**
