### PR TITLE
sort directives

### PR DESCRIPTION
**Pull request by pq**
Follow-up from: https://github.com/flutter/flutter/issues/81219

Note that these changes are required to unblock the failing `flutter analyze` try-bot:

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8848446021182711936/+/u/analyze_flutter_flutter/stdout?format=raw

/fyi @goderbauer @bwilkerson @devoncarew 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Comment by dkwingsmt** [comment]
Why weren't these errors found during the presubmit?

**Comment by pq** [comment]
> Why weren't these errors found during the presubmit?

It's a good question.  I thought they should and was careful to wait to land to https://github.com/flutter/flutter/issues/81219 re-enabling `directives_ordering` until I saw that the current engine roll had included the Dart SDK with the updated lint.  Either I was mistaken?  It was reverted?  Or some other cause of Dart SDK skew?

Sorry for the noise.  Really, I was trying to avoid this!

/fyi @athomas

**Comment by zanderso** [comment]
There are more coming in on the current engine roll that have been caught by the presubmit check: https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze/15040/overview

**Comment by zanderso** [comment]
I also filed https://github.com/dart-lang/sdk/issues/45892

**Pull request merged**
