### PR TITLE
ensure lastBuildTimestamp is set before early return

### PR DESCRIPTION
**Pull request by jonahwilliams**
If the last build time isn't set before this early return, empty pubspecs will hang on hot reload, as the incremental dill files will never be copied to the device.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
cc @keertip

**Comment by keertip** [comment]
👍  Awesome!

**Comment by cbracken** [comment]
Test?

**Review by cbracken — APPROVED** [review]

**Comment by jonahwilliams** [comment]
Test added

**Pull request merged**
