### PR TITLE
[flutter_tools] improve error surfacing from Linux builds

### PR DESCRIPTION
**Pull request by jpnurmi**
## Description

For example, with a missing asset in pubspec.yaml:

### Before
```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...
Exception: Build process failed
```

### After
```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...
ERROR: No file or variants found for asset: images/a_dot_burr.jpeg.
Exception: Build process failed
```

## Related Issues

#33584

## Tests

I updated the following tests:

- `test/general.shard/base/logger_test.dart`
- `test/commands.shard/hermetic/build_linux_test.dart`

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by zanderso** [comment]
Sorry if I'm misreading the PR, but it seems to be conflating a couple of different issues. It adds the `--verbose-error` flag, but as far as I can tell, that flag doesn't make error messages more verbose, rather it just prints `ERROR` in front of them.

Secondly, it also modifies the regular expression for passing through errors from clang. I think it would make sense to separate these changes into two PRs so we can discuss them separately.

**Comment by jpnurmi** [comment]
You are absolutely right. I got greedy and smacked the two changes together since both were touching the same regexp. I have split off the first and simpler change to a separate PR: #72559. We can get back to this PR later. :)

**Comment by jonahwilliams** [comment]
@stuartmorgan is there a better way for us to get stderr from the flutter tool through cmake?

**Comment by stuartmorgan** [comment]
> @stuartmorgan is there a better way for us to get stderr from the flutter tool through cmake?

This call is directly to `ninja`, not CMake. But unfortunately per the issues referenced here:
https://github.com/flutter/flutter/pull/71003#issuecomment-731739909
it looks like the answer is currently no. That's unfortunate; I didn't realize ninja collapsed output. That certainly explain why Linux build output regressed after you fixed it originally.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
I re-ran the failing web test, I'll see if that passes it.

**Pull request merged**
