### PR TITLE
Make AssetImage constructor const

### PR DESCRIPTION
**Pull request by tvolkert**

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
lgtm

**Comment by abarth** [comment]
What's the motivation for this change?  It's hard to tell without more information in the description.

**Comment by abarth** [comment]
Also, it might be worth adding a comment explaining why its const constructable.  We don't do that for most widgets because we want to preserve the option to add asserts to the constructor body.

**Comment by tvolkert** [comment]
I was going through my sample app and trying to use const constructors for widgets as much as possible, and this one being non-const prevented me from doing so in a few cases that could have otherwise been const.  This was all on guidance from @Hixie that in an ideal world, all widgets would be compile-time constants.

**Comment by abarth** [comment]
Yeah, in an ideal world they'd all be const constructible.  The trade-off today is that making the constructor const prevents us from adding asserts to the body of the constructor.  In this case, we don't have any asserts, and I think it is reasonable to give up that option.  Thanks!

**Comment by tvolkert** [comment]
I authored these changes

**Pull request merged**
