### PR TITLE
Allow selecting specific minute in a single tap

### LINKED ISSUE #62424: ShowTimePicker should allow selecting specific minutes in a single tap
Please clone this repository created just for this issue to see the problem yourself: https://github.com/Albert221/flutter_time_picker_issues

You cannot select a minute that's not dividable by 5 easily in `showTimePicker`!

### Steps to reproduce

1. Call `showTimePicker`.
2. Select random hour (to get to the minutes ring).

Now let's say I want to select 43rd minute. I click somewhere between `40` and `45`. `45` is selected, not as I wanted. I cannot easily tap on the minute I want, I have to firstly drag my finger on the printed minute AND ONLY THEN drag it to the minute in-between that I wanted.

[Link to a GIF showing that.](https://imgur.com/08UN60b)

```
[√] Flutter (Channel dev, 1.21.0-1.0.pre, on Microsoft Windows [Version 10.0.19041.388],
    locale pl-PL)
    • Flutter version 1.21.0-1.0.pre at D:\flutter
    • Framework revision f25bd9c55c (2 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
```

### PR DESCRIPTION
**Pull request by maheshj01**
Disabled rounding off minutes

Fixes: https://github.com/flutter/flutter/issues/62424

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by HansMuller** [comment]
Sorry to have let this PR go without a review for so long.  Providing a way to specify how taps on the time picker are quantized seems reasonable, although just replacing the current nearest-5-minute behavior with nearest-minute would be a breaking change (and see https://github.com/flutter/flutter/issues/62424#issuecomment-1518281486).  If you're still interested in developing this PR, I'd suggest introducing a parameter in the component, the theme, and showTimePicker that allows one to specify how taps on a minute value will be quantized - where the default is still nearest-5-minute.

**Comment by maheshmnj** [comment]
Thanks for the feedback will take a look at it.

**Comment by maheshmnj** [comment]
Will Comeback to this PR probably on aa weekend

**Comment by maheshmnj** [comment]
Closing this for now, Will come back when I can contribute.

**Pull request closed without merging**
