### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by GaryQian**
Remove extra 'the'

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by kf6gpe — APPROVED** [review]
LGTM.

**Comment by goderbauer** [comment]
@fkorotkov Any idea why Cirrus is not triggering on new PRs? (maybe related to the other thing I pinged you about)

**Comment by fkorotkov** [comment]
@goderbauer there was an incident that affected task processing and some API endpoints. It should be resolved by now and queued tasks are processing.

**Pull request merged**
