### PR TITLE
Always evaluate the finder in `driver.waitFor*()`

### LINKED ISSUE #11327: FlutterDriver.waitForAbsent() never completing
#### Problem

Tried to use this inside Google today, and getting incorrect behavior:

```dart
await driver.waitForAbsent(find.text('foo'), timeout: const Duration(seconds: 20));
```

* If I call that, the future never completes, and the test fails with a timeout exception after 20 seconds.
* If I *first* await a delayed future of 5 seconds to let the Snackbar that holds the text go away, *then* run the `await` above, then the future completes just fine, and the test succeeds.

#### Analysis

The future is never completing because of an error during this call in `extension.dart`:
```dart
await _waitUntilFrame(() => !finder.precache());
```

The error is:
```
'package:flutter_test/src/finders.dart': Failed assertion: line 269: '_cachedResult == null': is not true.
```

It seems weird that it's causing the future to never complete rather than completing with an error...

### PR DESCRIPTION
**Pull request by tvolkert**
Fixes #11327

### CODE REVIEW

**Comment by Hixie** [comment]
cc @yjbanov

**Comment by Hixie** [comment]
test?

**Comment by tvolkert** [comment]
No time in this PR - I'm half way out the door on vacation.  I can wait until I get back if you like.

**Comment by yjbanov** [comment]
I can take it over and add a test.

**Comment by tvolkert** [comment]
> I can take it over and add a test.

sg - thanks!

**Comment by Hixie** [comment]
Should we close this PR in the meantime?

**Comment by yjbanov** [comment]
> Should we close this PR in the meantime?

I'll pick it up right after I'm done cleaning up my other PRs.

**Comment by yjbanov** [comment]
But yeah, I'll have to rebase on top of @tvolkert's branch and open a new PR, so I'll have to close it anyway.

**Comment by Hixie** [comment]
Closing this PR to get it off our review list, per comments above.

**Pull request closed without merging**
