### PR TITLE
Add support for locale-specific text styles

### PR DESCRIPTION
**Pull request by jason-simmons**
See https://github.com/flutter/flutter/issues/12630 and
https://github.com/flutter/flutter/issues/16408

### CODE REVIEW

**Comment by jason-simmons** [comment]
@Hixie

**Comment by Hixie** [comment]
we should reexport Locale from the painting layer so that we don't have to keep saying ui.Locale.

Also, we should figure out how to get the Locale out of the inherited widgets the same way we do directionally, in the same places (text, rich text, render paragraph, editable text, etc)

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by Hixie** [comment]
also we may need to update the Locale-specific text styles on the material layer. @HansMuller may know more. or @yjbanov, iirc he wrote that code.

**Comment by HansMuller** [comment]
I'm not sure how this is supposed to work with our existing support for specifying Locales with the inherited [Localizations ](https://docs.flutter.io/flutter/widgets/Localizations-class.html) widget.

Do we need to change every TextStyle occurrence in a build method to `textStyle.copyWith(locale: Localizations.localeOf(context))`?

**Comment by Hixie** [comment]
This patch is incomplete. It should automatically propagate the `localOf(context)`, among other things.

**Comment by jason-simmons** [comment]
This PR is only intended to make the engine's TextStyle/ParagraphStyle locale field available to the framework's wrappers of TextStyle and ParagraphStyle.

It doesn't add locale support to layers of the framework above painting.

**Pull request merged**
