### PR TITLE
Added Indonesian (id) and Norwegian (no) locales

### LINKED ISSUE #15192: Could we add Indonesia language into Localization.dart in the Beta channel?
Hi ,now our app need to support Indonesian bahasa , but I found there is no material_id.arb file in the flutter_localizations folder ,

By the way , could you add Thai and Indonesia Bahasa in the  flutter/packages/flutter_localizations/lib/src/material_localizations.dart ?

I want to commit my code, but no access right .
Thank you so much .

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes https://github.com/flutter/flutter/issues/15192

Support for Norwegian was originally a contribution from Marcin Urbański - https://github.com/flutter/flutter/pull/15452

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by yjbanov** [comment]
Belated LGTM

**Comment by Fideas** [comment]
There is a typo in packages/flutter_localizations/test/translations_test.dart
it says:
`'nl', // Norwegian`

it should say:
`'no', // Norwegian`

**Comment by HansMuller** [comment]
Thanks for the report! Will fix.

**Pull request merged**
