### PR TITLE
Revert "MouseRegion enter/exit event can be triggered with button pressed"

### PR DESCRIPTION
**Pull request by dkwingsmt**
Reverts flutter/flutter#8114.

This PR has caused an internal breakage (internal issue b/186846732).

### CODE REVIEW

**Comment by dkwingsmt** [comment]
cc @xu-baolin

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by dkwingsmt** [comment]
Merging revert without flutter-build.

**Comment by xu-baolin** [comment]
@dkwingsmt hi, any details about the internal test?

**Comment by dkwingsmt** [comment]
@xu-baolin Not yet, I'm fully occupied on some other issues. Will get back on this asap.

**Pull request merged**
