### PR TITLE
Add benchmark for clipper layers raster cache

### PR DESCRIPTION
**Pull request by wangying3426**
Benchmark for https://github.com/flutter/engine/pull/32899.

The test result shows that it reduced the rasterizer time by using raster cache to replace saveLayer.

- If child DisplayListLayers are simple ( isComplex is false ) and not be cached, the result is that 90th percentile rasterizer time reduced. layer cache increased but saveLayer reduced.  See:
```
═════════════════════════╡ ••• Final A/B results ••• ╞══════════════════════════

Score	Average A (noise)	Average B (noise)	Speed-up
average_frame_build_time_millis	1.80 (0.00%)	1.95 (0.00%)	0.92x	
worst_frame_build_time_millis	3.28 (0.00%)	3.58 (0.00%)	0.92x	
90th_percentile_frame_build_time_millis	2.42 (0.00%)	3.03 (0.00%)	0.80x	
99th_percentile_frame_build_time_millis	3.03 (0.00%)	3.51 (0.00%)	0.86x	
average_frame_rasterizer_time_millis	11.77 (0.00%)	3.65 (0.00%)	3.22x	
worst_frame_rasterizer_time_millis	59.87 (0.00%)	6.23 (0.00%)	9.61x	
90th_percentile_frame_rasterizer_time_millis	13.32 (0.00%)	4.50 (0.00%)	2.96x	
99th_percentile_frame_rasterizer_time_millis	15.88 (0.00%)	4.96 (0.00%)	3.20x	
average_layer_cache_count	0.00 (0.00%)	4.00 (0.00%)	0.00x	
90th_percentile_layer_cache_count	0.00 (0.00%)	4.00 (0.00%)	0.00x	
99th_percentile_layer_cache_count	0.00 (0.00%)	4.00 (0.00%)	0.00x	
worst_layer_cache_count	0.00 (0.00%)	4.00 (0.00%)	0.00x	
average_layer_cache_memory	0.00 (0.00%)	5.68 (0.00%)	0.00x	
90th_percentile_layer_cache_memory	0.00 (0.00%)	5.68 (0.00%)	0.00x	
99th_percentile_layer_cache_memory	0.00 (0.00%)	5.68 (0.00%)	0.00x	
worst_layer_cache_memory	0.00 (0.00%)	5.68 (0.00%)	0.00x	
average_picture_cache_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
90th_percentile_picture_cache_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
99th_percentile_picture_cache_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
worst_picture_cache_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
average_picture_cache_memory	0.00 (0.00%)	0.00 (0.00%)	NaNx	
90th_percentile_picture_cache_memory	0.00 (0.00%)	0.00 (0.00%)	NaNx	
99th_percentile_picture_cache_memory	0.00 (0.00%)	0.00 (0.00%)	NaNx	
worst_picture_cache_memory	0.00 (0.00%)	0.00 (0.00%)	NaNx	
new_gen_gc_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
old_gen_gc_count	0.00 (0.00%)	0.00 (0.00%)	NaNx
```

- If child DisplayListLayers are complex and also cached, the result is that 90th percentile rasterizer time reduced. layer cache increased, but both picture cache and saveLayer reduced. See: 
```
═════════════════════════╡ ••• Final A/B results ••• ╞══════════════════════════

Score	Average A (noise)	Average B (noise)	Speed-up
average_frame_build_time_millis	1.74 (0.00%)	1.70 (0.00%)	1.03x	
worst_frame_build_time_millis	5.17 (0.00%)	3.65 (0.00%)	1.42x	
90th_percentile_frame_build_time_millis	2.10 (0.00%)	2.73 (0.00%)	0.77x	
99th_percentile_frame_build_time_millis	3.90 (0.00%)	3.19 (0.00%)	1.22x	
average_frame_rasterizer_time_millis	9.60 (0.00%)	4.25 (0.00%)	2.26x	
worst_frame_rasterizer_time_millis	20.38 (0.00%)	12.19 (0.00%)	1.67x	
90th_percentile_frame_rasterizer_time_millis	11.02 (0.00%)	7.06 (0.00%)	1.56x	
99th_percentile_frame_rasterizer_time_millis	12.85 (0.00%)	7.63 (0.00%)	1.68x	
average_layer_cache_count	0.00 (0.00%)	4.00 (0.00%)	0.00x	
90th_percentile_layer_cache_count	0.00 (0.00%)	4.00 (0.00%)	0.00x	
99th_percentile_layer_cache_count	0.00 (0.00%)	4.00 (0.00%)	0.00x	
worst_layer_cache_count	0.00 (0.00%)	4.00 (0.00%)	0.00x	
average_layer_cache_memory	0.00 (0.00%)	6.72 (0.00%)	0.00x	
90th_percentile_layer_cache_memory	0.00 (0.00%)	6.72 (0.00%)	0.00x	
99th_percentile_layer_cache_memory	0.00 (0.00%)	6.72 (0.00%)	0.00x	
worst_layer_cache_memory	0.00 (0.00%)	6.72 (0.00%)	0.00x	
average_picture_cache_count	4.00 (0.00%)	0.00 (0.00%)	Infinityx	
90th_percentile_picture_cache_count	4.00 (0.00%)	0.00 (0.00%)	Infinityx	
99th_percentile_picture_cache_count	4.00 (0.00%)	0.00 (0.00%)	Infinityx	
worst_picture_cache_count	4.00 (0.00%)	0.00 (0.00%)	Infinityx	
average_picture_cache_memory	8.72 (0.00%)	0.00 (0.00%)	Infinityx	
90th_percentile_picture_cache_memory	8.72 (0.00%)	0.00 (0.00%)	Infinityx	
99th_percentile_picture_cache_memory	8.72 (0.00%)	0.00 (0.00%)	Infinityx	
worst_picture_cache_memory	8.72 (0.00%)	0.00 (0.00%)	Infinityx	
new_gen_gc_count	0.00 (0.00%)	0.00 (0.00%)	NaNx	
old_gen_gc_count	0.00 (0.00%)	0.00 (0.00%)	NaNx
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by wangying3426** [comment]
@flar Could you have time to have a look at this? Thanks.

**Comment by flar** [comment]
First, this appears to be modifying an existing benchmark. Once a benchmark is added, it should remain stable as its performance history is tracked. If you have new things to benchmark, a new benchmark should be created so that it doesn't interfere with existing metrics.

Second, please run A/B tests with more than 1 iteration so that benchmark jank is averaged out. I typically run AB=4.

**Comment by wangying3426** [comment]
> First, this appears to be modifying an existing benchmark. Once a benchmark is added, it should remain stable as its performance history is tracked. If you have new things to benchmark, a new benchmark should be created so that it doesn't interfere with existing metrics.
> 
> Second, please run A/B tests with more than 1 iteration so that benchmark jank is averaged out. I typically run AB=4.


Thank you for reply.

For the this point, this seems to be a new benchmark so that it doesn't interfere with existing metrics. 
But, do you mean that we should modify the existed [shader_mask_cache](https://github.com/flutter/flutter/blob/master/dev/benchmarks/macrobenchmarks/lib/src/shader_mask_cache.dart) to implement the benchmark test?

For the second point, the result of AB=4 is also that 90th percentile rasterizer time reduced, see:
```dart
═════════════════════════╡ ••• Final A/B results ••• ╞══════════════════════════

Score	Average A (noise)	Average B (noise)	Speed-up
average_frame_build_time_millis	1.10 (7.36%)	1.05 (7.80%)	1.04x	
worst_frame_build_time_millis	3.12 (34.06%)	4.23 (35.41%)	0.74x	
90th_percentile_frame_build_time_millis	1.54 (13.24%)	1.55 (11.08%)	0.99x	
99th_percentile_frame_build_time_millis	2.69 (32.77%)	2.76 (20.81%)	0.97x	
average_frame_rasterizer_time_millis	3.13 (5.42%)	2.21 (2.51%)	1.42x	
worst_frame_rasterizer_time_millis	4.95 (7.84%)	3.85 (35.28%)	1.29x	
90th_percentile_frame_rasterizer_time_millis	3.69 (6.13%)	2.62 (1.68%)	1.41x	
99th_percentile_frame_rasterizer_time_millis	4.26 (0.35%)	2.88 (1.31%)	1.48x	
average_layer_cache_count	0.00 (0.00%)	3.00 (0.00%)	0.00x	
90th_percentile_layer_cache_count	0.00 (0.00%)	3.00 (0.00%)	0.00x	
99th_percentile_layer_cache_count	0.00 (0.00%)	3.00 (0.00%)	0.00x	
worst_layer_cache_count	0.00 (0.00%)	3.00 (0.00%)	0.00x	
average_layer_cache_memory	0.00 (0.00%)	4.63 (0.00%)	0.00x	
90th_percentile_layer_cache_memory	0.00 (0.00%)	4.63 (0.00%)	0.00x	
99th_percentile_layer_cache_memory	0.00 (0.00%)	4.63 (0.00%)	0.00x	
worst_layer_cache_memory	0.00 (0.00%)	4.63 (0.00%)	0.00x	
average_picture_cache_count	3.00 (0.00%)	0.00 (0.00%)	Infinityx	
90th_percentile_picture_cache_count	3.00 (0.00%)	0.00 (0.00%)	Infinityx	
99th_percentile_picture_cache_count	3.00 (0.00%)	0.00 (0.00%)	Infinityx	
worst_picture_cache_count	3.00 (0.00%)	0.00 (0.00%)	Infinityx	
average_picture_cache_memory	4.99 (0.00%)	0.00 (0.00%)	Infinityx	
90th_percentile_picture_cache_memory	4.99 (0.00%)	0.00 (0.00%)	Infinityx	
99th_percentile_picture_cache_memory	4.99 (0.00%)	0.00 (0.00%)	Infinityx	
worst_picture_cache_memory	4.99 (0.00%)	0.00 (0.00%)	Infinityx	
new_gen_gc_count	0.00 (0.00%)	2.00 (0.00%)	0.00x	
old_gen_gc_count	0.00 (0.00%)	0.00 (0.00%)	NaNx
```

**Comment by flar** [comment]
> > First, this appears to be modifying an existing benchmark. Once a benchmark is added, it should remain stable as its performance history is tracked. If you have new things to benchmark, a new benchmark should be created so that it doesn't interfere with existing metrics.

> Thank you for reply.
> 
> For the this point, clipper_cache_perf__e2e_summary seems to be a new benchmark so that it doesn't interfere with existing metrics.

Please ignore that part of my comment. When I looked at it the other day all I saw was a few changes that updated a file in the macrobenchmarks area - which looked exactly like it was just modifying an existing benchmark.

But, I now see that this PR is about adding a new benchmark.

I think I was confused by the link in one of the emails taking me to just a single commit in the chain rather than showing me the entire set of code changes.

**Review by flar — APPROVED** [review]
LGTM

**Comment by flar** [comment]
@keyonghan did you look over the CI files?

**Comment by wangying3426** [comment]
https://github.com/flutter/engine/pull/32899 depends on it, so merge it first. we can revert it later if there is any problem.

**Comment by flar** [comment]
Tracking history for the benchmark: https://flutter-flutter-perf.skia.org/e/?queries=test%3Dclipper_cache_perf__e2e_summary

**Pull request merged**
