### PR TITLE
use transparent android launcher icons

### LINKED ISSUE #5440: Update default Android launcher icons
With the shiny new transparent background icons.

https://github.com/flutter/identity-assets/tree/master/assets/Flutter-Launcher-Icons/android/transparent-backgrounds

### PR DESCRIPTION
**Pull request by sethladd**
Closes https://github.com/flutter/flutter/issues/5440

### CODE REVIEW

**Comment by sethladd** [comment]
cc @Hixie

**Comment by sethladd** [comment]
oops, looks like Stocks was an arrow. Let me know if you want me to revert that, or use the Flutter logo.

**Comment by Hixie** [comment]
@sethladd Yeah we shouldn't change the stocks icon.

**Comment by eseidelGoogle** [comment]
We don't demo stocks anymore, so I'm happy to have us not worry about it's arrow icon.  Do what's easy here imo.

**Comment by HansMuller** [comment]
LGTM

**Pull request merged**
