### PR TITLE
Revert "Fix wrap compute max intrinsic width/height with spacing (#82…

### PR DESCRIPTION
**Pull request by chunhtai**
…t609)"

This reverts commit 468471bfc1ce61e9ab0120e1dfc6bc7b384b7448.

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

https://github.com/flutter/flutter/issues/82289

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by chunhtai** [comment]
cc @YeungKC

**Review by renyou — APPROVED** [review]

**Comment by christopherfujino** [comment]
firebase tests are failing due to https://github.com/flutter/flutter/issues/82863

**Comment by chunhtai** [comment]
@christopherfujino  Am I allowed to merge this revert pr?

**Comment by christopherfujino** [comment]
> @christopherfujino Am I allowed to merge this revert pr?

I'm unsure of the policy wrt unblocking the internal roll.

**Comment by tvolkert** [comment]
Approval to land, given that #82863 is now fixed.

**Comment by tvolkert** [comment]
Revert of https://github.com/flutter/flutter/pull/82609

**Pull request merged**
