### PR TITLE
Migrate the flutter/flutter wiki to docs/unsorted_wiki

### PR DESCRIPTION
**Pull request by Piinks**
Part of https://github.com/flutter/flutter/issues/145009
This is part one of the wiki migration.
This moves all wiki pages wholesale into the new docs directory with no changes.
Follow up PRs will sort them, updating breadcrumbs and links.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Review by matanlurey — APPROVED** [review]
LGTM!

**Comment by Piinks** [comment]
I'm going to need to change some file names to make CI happy. Will do that after lunch.

**Comment by Piinks** [comment]
Context: see reserved characters https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

**Comment by Hixie** [comment]
test-exempt: documentation

**Comment by Piinks** [comment]
Ok next, I will need to make some edits. There are some links I need to fix to pass analysis, along with some trailing white space. I will not edit anything else, pinky promise. :)

**Comment by Piinks** [comment]
Actually, I may have a better idea, I am going to edit analyze.dart to make only `docs/unsorted` immune. The primary issues (of which there are a ton) are
- links that reference the `master` branch and
- links to file issues that do not fit expected templates

Since this initial move is meant to change as little as possible, I think exempting only the `unsorted` directory is pretty straightforward. As we moved pages out of unsorted, we can fix all of these links then.

**Comment by Piinks** [comment]
Last commit is just copying over a coincidentally timed update to the Setting up the Framework Development Environment from @goderbauer 😉 

Should be able to merge after CI passes before any other changes are introduced.

When sorting pages into subdirs in follow up PRs, I'll circle back to the original wiki page, check that there weren't additional changes, and update the page to point to the new location.

**Pull request merged**
