### PR TITLE
Remove our extra timeout logic.

### LINKED ISSUE #88838: flutter_test timeout logic - addTime - positive is flaky
This has been failing on and off since at least https://github.com/flutter/engine/pull/27787 on 2021-07-29.

```
#44     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:0:0)
#49     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:386:9)
#50     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:429:15)
#51     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:385:7)
#58     Invoker._onRun (package:test_api/src/backend/invoker.dart:384:11)
#59     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#60     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/backend/remote_listener.dart:257:16)
#65     RemoteListener._runLiveTest (package:test_api/src/backend/remote_listener.dart:256:5)
#66     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/backend/remote_listener.dart:209:7)
#84     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#85     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#89     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#123    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1150:21)
#131    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#132    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#142    _Socket._onData (dart:io-patch/socket_patch.dart:2166:41)
#151    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1702:33)
#152    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1213:14)
(elided 125 frames from class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package:stack_trace)

The test description was:
  flutter_test timeout logic - addTime - positive
════════════════════════════════════════════════════════════════════════════════════════════════════

00:06 +0 -1: flutter_test timeout logic - addTime - positive [E]                                                                                                                                       
  Test failed. See exception logs above.
  The test description was: flutter_test timeout logic - addTime - positive
  

00:06 +0 -1: Some tests failed.  
```

Looking at commits since 2021-06-21, I see:
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/4736/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/4735/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/4722/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/4698/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/4650/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/4373/overview
* https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Web%20Framework%20tests/4371/overview

Previous issue: https://github.com/flutter/flutter/issues/18507

### PR DESCRIPTION
**Pull request by Hixie**
It's just causing flakes and we're not really using it anyway.

Fixes https://github.com/flutter/flutter/issues/88838

### CODE REVIEW

**Review by zuhaibkhan629 — COMMENTED** [review]
Alright somehow.!

**Review by goderbauer — APPROVED** [review]
LGTM once LUCI is happy

**Comment by Hixie** [comment]
(i got a flake on the `pending_timer_fail_test.dart` test on the windows web shard; i'm just going to try running it again with extra logging to see if there's something i can learn before chalking it up to a random bit flip...)

**Comment by Hixie** [comment]
Definitely not a random bit flip...

**Comment by Hixie** [comment]
Maybe caused by https://github.com/flutter/flutter/issues/90026...

**Comment by Hixie** [comment]
@goderbauer you should probably rereview the test.dart changes.

**Comment by chinmaygarde** [comment]
@goderbauer Could you please re-review this as soon as convenient?  The linked issue is the only cause of flakes on the engine LUCI in the past ~5 days.

engine luci flakes

**Review by goderbauer — APPROVED** [review]
Still LGTM

**Comment by Hixie** [comment]
thanks!

**Pull request merged**
