### PR TITLE
fix transform assert

### PR DESCRIPTION
**Pull request by pq**
## Description

Fixes an assert that was bogus.

Flagged by the newly updated `unrelated_type_equality_checks` lint in this failing try:

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8915275287386529616/+/steps/analyze_flutter/0/stdout

Cheers @srawlins for the fix!
## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by pq** [comment]
@dnfield, @jonahwilliams: any thoughts on the failures here?

**Comment by jonahwilliams** [comment]
Part of the reason this ends up being breaking is that we have inadvertently created scenarios where our matrices are non-invertible. It's also not clear whether turning this on will effect users as well, as it might end up being a large breaking change.

We would need to:
- Figure out what widgets/behaviors are causing these matrices to be created and why they don't break elsewhere.  Perhaps they go unused or is test only behavior?
- From there, figure out what the likely impact on users is for re-enabling this assert. We could try running google3 with the required framework changes and see if it affects applications.

I don't think it will be obvious to most users what the problem is if this assert starts firing in their application, so we should be careful.

cc @Hixie @goderbauer

**Comment by pq** [comment]
@Hixie, @goderbauer: assuming this is not an easy call to make and in the interest of not blocking an analyzer roll could we consider adding a comment and:

1. removing the assert, or
2. adding an ignore

?

**Comment by jonahwilliams** [comment]
Since the assert is functionally diasbled we can comment it out here to unblock analyzer

**Comment by pq** [comment]
Awesome.  Thanks @jonahwilliams !

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Was a bug filed to fix this? We should fix this soon; adding commented-out code is strictly against our style guide.

**Pull request merged**
