### PR TITLE
Roll engine 162b2e98c036..6c2a0b3a6d93 (5 commits)

### PR DESCRIPTION
**Pull request by engine-flutter-autoroll**
https://github.com/flutter/engine/compare/162b2e98c036...6c2a0b3a6d93

git log 162b2e98c036..6c2a0b3a6d93 --no-merges --oneline
6c2a0b3a6 Undefine ERROR in platform_view_layer.cc (flutter/engine#6675)
55e12993a Update FlutterPlugin.h docs, suppress warning for older API (flutter/engine#6672)
f7970048d Attach and position embedded UIVIews (flutter/engine#6614)
df85722fa Plumb the iOS PlatformViewsController into flow. (flutter/engine#6603)
2bfb893cf iOS Embedding Refactor (flutter/engine#6447)

The AutoRoll server is located here: https://autoroll.skia.org/r/flutter-engine-flutter-autoroll

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/&#43;/master/autoroll/README.md

If the roll is causing failures, please contact the current sheriff, who should
be CC&#39;d on the roll, and stop the roller if necessary.

### CODE REVIEW

**Comment by engine-flutter-autoroll** [comment]
@liyuqian : New roll has been created by https://autoroll.skia.org/r/flutter-engine-flutter-autoroll

**Comment by engine-flutter-autoroll** [comment]
Auto-roller completed checks. About to merge.

**Comment by Hixie** [comment]
Looks like this broke the build. cc @liyuqian

**Comment by liyuqian** [comment]
I'm not surprised as this roll include some quite significant changes to the engine from @dnfield and @amirh . I'll revert the roll and try to manually roll "2bfb893cf iOS Embedding Refactor" to see if it's causing the issue.

**Pull request merged**
