### PR TITLE
Update engine

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by chinmaygarde** [comment]
lgtm

**Comment by abarth** [comment]
I've got one of these too :)

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/5006 :)

**Comment by abarth** [comment]
it's a race!

**Comment by jason-simmons** [comment]
Didn't realize that you had one in flight.  Closing this.

**Comment by abarth** [comment]
I've merged mine.

**Pull request closed without merging**
