### PR TITLE
Revert 10395 modal ignore

### PR DESCRIPTION
**Pull request by Hixie**
See https://github.com/flutter/flutter/pull/10395#issuecomment-305267503

cc @goderbauer

### CODE REVIEW

**Comment by Hixie** [comment]
I don't understand why github is showing this as 6 reverts.

**Comment by Hixie** [comment]
The "files changed" section seems right though, so...

**Comment by goderbauer** [comment]
Sad LGTM.

**Comment by goderbauer** [comment]
Looks like the benchmark is back to normal. I take my LGTM back! :)

**Pull request closed without merging**
