### PR TITLE
Add Flutter post-initialization callback into runApp

### LINKED ISSUE #64288: Consider adding initialization callback to runApp
Developers often need to run some set of behaviors near app initialization that require various Flutter services. The typical remedy is to invoke some kind of direct initialization of an internal Flutter binding before calling `runApp()`, for example:

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();

  // Run some Flutter-relevant code, like early plugin communication

  runApp(MyApp());
}
```

Consider offering an optional callback in `runApp()` that is invoked after all binding initializations so that Flutter developers do not need to understand the implementation details of `runApp()` such that those developers manually orchestrate the internal initialization:

```dart
void main() {
  runApp(
    MyApp,
    onFlutterInitialized: () {
      // Run some Flutter-relevant code, like early plugin communication
    },
  );
}
```

### PR DESCRIPTION
**Pull request by pedromassango**
## Description

This PR provide the ability to register a callback that is called after Flutter binding initialization with the host operating system.

Cc @Hixie for review since you touched the code that I'm changing.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/64288

## Tests

- `runApp.onFlutterInitialized` callback is executed if it is not null

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Comment by pedromassango** [comment]
> Thanks for the contribution!
> 
> Can you talk about why this would be preferred over just having the developer set up a post-frame callback themselves after the runApp call? How common is it that a postframe callback should run vs a callback to run after the warmup frame, or before the first frame, or as a microtask, or as a regular task, or as a scheduler prioritized task?

I think this something that nedd to provided by the framework because only the framework knows when flutter is "fully" ready. The post frame callback are called only once and I think this is good for code initialisation.

> How common is it that a postframe callback should run vs a callback to run after the warmup frame, or before the first frame, or as a microtask, or as a regular task, or as a scheduler prioritized task?

I'm not really sure what would be the best solution to call this callback, at first it seems to me that run it in post frame callback would be the best solution. I'm pretty sure you have a better approach to handle this and I would like to know.

**Comment by Hixie** [comment]
> I think this something that nedd to provided by the framework because only the framework knows when flutter is "fully" ready. The post frame callback are called only once and I think this is good for code initialisation.

I don't really know what you mean by "when flutter is fully ready". Unlike the Web, where things have to load before they can be run and so you have to wait for onload and similar events, with Flutter the whole app is loaded before any code starts running, so there's nothing to wait for except the app model itself, which isn't under Flutter's control.

> I'm not really sure what would be the best solution to call this callback, at first it seems to me that run it in post frame callback would be the best solution. I'm pretty sure you have a better approach to handle this and I would like to know.

I don't know what the problem is so it's hard for me to give an answer to this. Generally when it comes to setting up application logic, I do it before `runApp`.

**Comment by goderbauer** [comment]
@pedromassango Do you still have plans for this PR?

**Comment by Hixie** [comment]
I'm preparing a PR that improves the diagnostics around using "binding.instance" before the bindings are ready which should make this less of an issue, FWIW.

**Comment by pedromassango** [comment]
> @pedromassango Do you still have plans for this PR?

Not really.

**Pull request closed without merging**
