### PR TITLE
Roll engine to 8757bf2a19ef8c6dc14f7595272bcd92d28dfdda

### PR DESCRIPTION
**Pull request by mraleph**
This is a pre-roll for Dart roll. 

Includes two Skia rolls and a corresponding goldens update.

8757bf2a1 Roll src/third_party/skia 05caa69a3f5a..1b62fad4b188 (2 commits) (flutter/engine#6513)
c2fd10ad1 Roll src/third_party/skia 2a138544646d..05caa69a3f5a (1 commits) (flutter/engine#6512)

### CODE REVIEW

**Review by aam — APPROVED** [review]

**Comment by alexmarkov** [comment]
@liyuqian could you please take a look at gold file changes (coming from Skia rolls), and check if they are correct?

**Review by liyuqian — APPROVED** [review]
LGTM. I've added the engine commit description to the commit message. Please make sure that it's preserved during merging so we can easily see what are rolled in.

Meanwhile, @GaryQian may want the engine to roll as far as possible to e44c10c9620db493de3faa6879f117a2165c40cc just before his text shadow commit.

**Comment by liyuqian** [comment]
Someone broke a golden test by setting it to run only on MacOS: https://github.com/flutter/flutter/pull/20202 We'll need to fix that to fix the macos tests.

**Comment by tvolkert** [comment]
Is this still relevant?  It looks like the engine has rolled since this was created.

**Pull request closed without merging**
