### PR TITLE
Re-land Fix FlexibleSpaceBar Opacity when AppBar.toolbarHeight > ktoolbarHeight

### LINKED ISSUE #80451: FlexibleSpaceBar incompatible when AppBar.toolbarHeight is larger than ktoolbarHeight
The `AppBar` supports `flexibleSpace` - even though it doe not actually collapse unless animated or otherwise manually.
However, the `Opacity` calculation for the `FlexibleSpaceBar.background` dow not account for the AppBar using a different `toolbarHeight`. 
For example, this computes an opacity of 0 for the background, resulting in nothing being painted:

```dart
MaterialApp(
        home: Scaffold(
          appBar: AppBar(
            toolbarHeight: 300,
            flexibleSpace: const FlexibleSpaceBar(
              title: Text('Title'),
              // Invisible and how! :)
              background:  Text('Background'),
              collapseMode: CollapseMode.pin,
            ),
          ),
          body: CustomScrollView(
            primary: true,
            slivers: <Widget>[
              SliverToBoxAdapter(
                child: Container(
                  height: 1200.0,
                  color: Colors.orange[400],
                ),
              ),
            ],
          ),
        ),
      ),
```

### PR DESCRIPTION
**Pull request by Piinks**
Reverts flutter/flutter#80545
Original PR: https://github.com/flutter/flutter/pull/80453
Fixes: https://github.com/flutter/flutter/issues/80451

### CODE REVIEW

**Comment by Piinks** [comment]
This requires customer migration as it was reverted for internal test failure. Currently working on migration now.

**Comment by Piinks** [comment]
Customer has been migrated, this should be ok to re-land. :)

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by Piinks** [comment]
The G testing shard appears stuck. I ran a global test on this to make sure there weren't other customers broken by this, so I have manually set the check to green.

**Pull request merged**
