### PR TITLE
[Draft] Test animation in sprite sheet in golden: pumpAnimation and AnimationSheetRecorder

### PR DESCRIPTION
**Pull request by dkwingsmt**
## Description

This is a **demonstration** of a change that supports golden-testing animating widgets in an animation sheet.

This PR includes both the desired change and a demonstrating test for `CircularProgressionIndicator`, which will yield a result as follows:

circular_progress_indicator grid

The demonstration part will be removed in the final PR.

The proposed change introduces 2 new APIs:
* `WidgetTester.pumpFrames`, which is like `pump` but pumps a number of frames with the specified interval of `frameDuration` 
* `SheetDisplay`, which places clones of the target widget in a grid, and assign them with keys from the tail to the front

In this way, clones of the widget will be added to the front of the sheet one every frame, so that after a number of frames, the sheet is filled with clones that show each frame of the widget.

## Related Issues

- Affected by https://github.com/flutter/flutter/issues/54511, golden tests yield incorrect result on chrome

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behaviour with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 3.
Please triage them at https://flutter-gold.skia.org/search?issue=54335.

**Comment by dkwingsmt** [comment]
@Piinks Can you take a look at the changes?

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 4.
Please triage them at https://flutter-gold.skia.org/search?issue=54335.

**Review by Piinks — COMMENTED** [review]
Can you check the Flutter Gold dashboard and see if the chrome result is what you expected?

Also, it may be better to break this out into two separate PRs. One that adds the new testing features first, and then one that applies the changes to the circular progress indicator.

**Comment by dkwingsmt** [comment]
Yeah the Chrome one was what I mentioned yesterday that needs investigation.

The PR will definitely be split before being ready.

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 5.
Please triage them at https://flutter-gold.skia.org/search?issue=54335.

**Comment by dkwingsmt** [comment]
The incorrect result generated by chrome is because of a general bug as described in https://github.com/flutter/flutter/issues/54511, unrelated to this change.

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 6.
Please triage them at https://flutter-gold.skia.org/search?issue=54335.

**Comment by dkwingsmt** [comment]
Close in favor of https://github.com/flutter/flutter/pull/54699

**Pull request closed without merging**
