### PR TITLE
run pub with --no-package-symlinks

### LINKED ISSUE #2941: Flutter tool should use pub with --no-package-symlinks
We're not quite ready for this, but once we add support for `.packages` files, we should run pub with `--no-package-symlinks` to avoid creating all the symlinks.

### PR DESCRIPTION
**Pull request by devoncarew**
- run pub with `--no-package-symlinks` (fix https://github.com/flutter/flutter/issues/2941)
- resolve `packages/foo` references in futter.yaml files using info from the .packages file

I'm not 100% sure that this has caught all the places using symlinks; we can back out the use of the flag if there are issues.

### CODE REVIEW

**Comment by devoncarew** [comment]
Hmm, looks like `pub run test` still needs symlinks.

**Comment by sethladd** [comment]
Can we run tests by just calling into `dart` ?  (we do that in dartdoc, it's faster than going through `pub run`)

**Comment by devoncarew** [comment]
That would work; we'll want a `all.dart` file for the test dir.

Not sure how `flutter test` will handle no symlinks.

**Comment by abarth** [comment]
LGTM once Travis is happy.

> That would work; we'll want a all.dart file for the test dir.

We could also crawl it to find all the `_test.dart` files.  That's what we do for `flutter test`.

**Comment by devoncarew** [comment]
Iterating a bit to try and get Travis green; remove `pub run test` in favor of using `test/all.dart` files (will ping for a re-review once this stabilizes).

**Comment by devoncarew** [comment]
It's green!

@abarth, I did create some `test/all.dart` files in the repos. We can no longer use `pub run test` - `test` doesn't work w/o package symlinks. When you said crawl the _test.dart files, did you mean that we'd adapt `flutter test` to work with projects that didn't need the flutter headless runtime, and have it scan for test files?

**Comment by abarth** [comment]
LGTM

> have it scan for test files?

Yeah, that's what I was thinking, but reading it in print makes me think that it's out-of-scope for the flutter tool.  Really we just need to wait for package:test to work with `.packages` files.  Maybe add a comment to the add.dart files that references the package:test bug?

**Comment by devoncarew** [comment]
> Maybe add a comment to the all.dart files that references the package:test bug?

sgtm

**Comment by abarth** [comment]
After landing this patch, you might want to send an email to flutter-dev recommending that folks `git clean -x -f -d` after updating to clear away the packages symlinks.  Otherwise the stale symlinks might be confusing.

**Comment by sethladd** [comment]
This is great, thanks for working on this! symlinks be gone!!

**Comment by devoncarew** [comment]
Sounds good; running `flutter update-packages` will do the same thing (pub get/upgrade --no-package-symlinks will nuke symlinks as well).

**Comment by eseidelGoogle** [comment]
https://github.com/dart-lang/test/issues/327 is the package:test bug about .packages support.

**Pull request merged**
