### PR TITLE
[WIP] Opt-in for smooth pointer scrolling

### LINKED ISSUE #32120: Scroll wheel scrolling is not smooth
## Steps to Reproduce

1. Use a desktop embedder, or another platform that allows you to scroll with a mouse's scroll wheel.
2. Scroll any scrollable content (e.g. list demo in Flutter Gallery)
3. Observe how the scroll offset abruptly jumps between scroll notches instead of smoothly transitioning (like Chrome, Firefox, UWP apps, etc.)

Gif example:

### PR DESCRIPTION
**Pull request by Piinks**
WIP
Loosely based on the chromium smooth scroller for animating stepped mouse wheel scrolling.

Fixes https://github.com/flutter/flutter/issues/32120

The original PR (https://github.com/flutter/flutter/pull/115314) could not move forward until we could reliably distinguish trackpad input from mouse wheels on web. This was needed because trackpads already curve input deltas for smooth scrolling. If this curve is applied to already curved input, the user's scrolling input would go no where. A heuristic was added a while ago to identify trackpads on web, and it seems to be working well so let's see if we can get this in. :)

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by loic-sharma** [comment]
Here's `Windows - mouse wheel`, scrolling works but appears to not respect my system's scroll speed settings:

pr_139392_windows_desktop_physical_scroll_wheel

**Comment by loic-sharma** [comment]
Here's `Windows web - trackpad`, scrolling works but it is slow and appears to ignore scroll events sporadically if `animatePointerScroll` is `true`. Here's me attempting to scroll to the ends of the list as quickly as possible:

Windows web - trackpad

**Comment by Piinks** [comment]
Ah ok, thank you @loic-sharma this is very helpful. Trackpads on web should not be going through the animated pointer path. This is why we were unable to land this change previously because it caused sporadic results with trackpad on web. It looks like we need to better identify trackpads on web so that they do not go through this code path.

**Comment by Piinks** [comment]
Thanks again to @loic-sharma. I filed https://github.com/flutter/flutter/issues/139990 to follow up on the issue with identifying trackpads on web. I also updated https://github.com/flutter/flutter/issues/32120 to reflect the latest info on the bug, along with some work arounds and packages I found that achieve the desired effect. Until we resolve the web issue, I do not think we can land this as it causes erratic scrolling with trackpads on web, which is definitely not an improvement. 🙃

**Pull request closed without merging**
