### PR TITLE
[Refactor] Fix style in example

### PR DESCRIPTION
**Pull request by natsuk4ze**
I just fixed "IMAGES" to "images" in examples/image_list.
Currently, "PREFER uses the lower case of the constant name ".

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by negotoyolo** [comment]
@goderbauer It seems to keep getting stuck at "Google testing has started". What should I do?

**Comment by negotoyolo** [comment]
I rebased a branch to fix the Google test stack, but the commit history was not compiled...

**Comment by negotoyolo** [comment]
I've tried empty commits and rebasing, but it doesn't seem to fix it. #65646

**Comment by negotoyolo** [comment]
@goderbauer I fixed it.

**Comment by negotoyolo** [comment]
Since the commit history has become complicated, I will close this one and create a new PR.

**Pull request closed without merging**
