### PR TITLE
Setting icon color to first ListTile in ExpansionTile. Fixes #23053

### LINKED ISSUE #23053: ExpansionTile - can't change trailing default Icon color even though it looks like one should be able to
## Steps to Reproduce

Create any Flutter App that uses an ExpansionTile 

Try to change the default Icon color ... 

Although the code looks like one should be to set the following:
theme.unSelectedWidget    and 
theme.accentColor

it actually doesn't do anything ..the Icon color stays the same.. 

I finally had to copy the code and change the Icon logic to the following (see the color: attribute)  

`              trailing: widget.trailing ??
                  RotationTransition(
                    turns: _iconTurns,
                    child: Icon(Icons.expand_more, color: _iconColor.value),
                  ),`

```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en)
    • Flutter version 0.9.4 at /Users/sjm/Development/tools/flutter
    • Framework revision f37c235c32 (3 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/sjm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected devices (2 available)
    • iPhone 8 • 0CF10D1F-D5FD-4887-BCA1-6BE9818C5AB7 • ios • iOS 12.0 (simulator)
    • iPhone X • 78590509-1E81-4378-8BDE-92EBAFDB00A0 • ios • iOS 12.0 (simulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by jmolins**
In issue [#23053](https://github.com/flutter/flutter/issues/23053), developer reports being unable to set the trailing icon color in the first ListTile of the ExpansionTile.

This behaviour can be seen in the Gallery app. Go to Material > Expand/collapse list control. The trailing arrow does not get the same blue color the title gets.

The problem is the following:

The `ExpansionTile` sets an `IconThemeData` before creating the `ListTile` and sets the color to be used forward. This is the original code:

```
        children: <Widget>[
          IconTheme.merge(
            data: IconThemeData(color: _iconColor.value),
            child: ListTile(
              onTap: _handleTap,
              leading: widget.leading,
              title: DefaultTextStyle(
                style: Theme.of(context).textTheme.subhead.copyWith(color: titleColor),
                child: widget.title,
              ),
              trailing: widget.trailing ?? RotationTransition(
                turns: _iconTurns,
                child: const Icon(Icons.expand_more),
              ),
            ),
          ),
          ClipRect(
            child: Align(
              heightFactor: _heightFactor.value,
              child: child,
            ),
          ),
        ],
```
 The problem with this code is that the `ListTile` itself creates another `IconThemeData` in its `build()`  method. And this new `IconThemeData` does not take into account the one created outside in the `ExpansionTile`.

This PR substitutes the `IconThemeData` by a `ListTileTheme` that is used natively by the code inside the `ListTile` to set its style.

Since the `ListTileTheme` can also provide a text style, it is used to provide the style for the title so it is no longer necessary to create a `DefaultTextStyle`, that is also removed from the code.

### CODE REVIEW

**Comment by Hixie** [comment]
This looks pretty reasonable.

Can you add a test to make sure we don't accidentally revert this?

**Comment by jmolins** [comment]
@Hixie, I have added the test as requested.

The test is based on the tests done for ListTile in https://github.com/flutter/flutter/blob/db9fe3f827836a0b29657d24bb87be90c5fca2c3/packages/flutter/test/material/list_tile_test.dart#L251.

In this case, though, since the ListTileTheme is just above the first ListTile, the tests apply only to this one. The test ensure that the theme in scope is correctly applied to the tile through the ListTileTheme.

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
Thanks for your contribution! I'll land it when the bots go green.

**Comment by HansMuller** [comment]
Landing this now (finally!).

**Pull request merged**
