### PR TITLE
Reland Refactored ListTileTheme: ListTileThemeData, ThemeData.listThemeData

### PR DESCRIPTION
**Pull request by HansMuller**
Reland https://github.com/flutter/flutter/pull/91449

Fixed a typo in the  `ListTileTheme.data` getter that caused an internal test to fail. Added a regression test.

### CODE REVIEW

**Review by darrenaustin — APPROVED** [review]
LGTM

**Comment by guidezpl** [comment]
@HansMuller @Piinks I'm curious if Dart fix supports this kind of change?

**Comment by HansMuller** [comment]
@guidezpl - I'm assuming that class renames are supported, so in this case ListTileTheme => ListTileThemeData.

**Comment by guidezpl** [comment]
It's a bit more than that, right, with adding a constructor
Screen Shot 2021-11-17 at 17 40 46

**Comment by HansMuller** [comment]
Yes, that's right. The old constructor still works however a complete upgrade would require the transformation you've shown. I don't know if Dart Fix can do that. 

@bwilkerson - is this possible?
```dart
Foo(a: b, c: d) => Bar(data: BarData(a: b, c: d))
```

**Comment by Piinks** [comment]
Hey all, thanks for thinking of this! I do not believe this is supported right now. Dart fixes work within a class right now, not across them. There is a feature request for this though in https://github.com/dart-lang/sdk/issues/45393

The `TextSelectionThemeData` ones seem similar, they were added in #78897, so it may be worth double checking.

Overall, this does seem like something that really should have a migration guide, are you going to make one @HansMuller?

**Pull request merged**
