### PR TITLE
[flutter_tools] add command to help users get flutter on PATH

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Add a new command that adds flutter to a users PATH configuration on macOS and Linux. Searches any of the shell config files and adds an export to each one.

For windows there are more choices.
* setx
* edit the registry manually (requires restart)
* https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?redirectedfrom=MSDN&view=netframework-4.8#overloads

Absolutely no idea what the best approach is

### CODE REVIEW

**Comment by christopherfujino** [comment]
Note this is complicated by Catalina defaulting to zsh.

**Comment by jonahwilliams** [comment]
Oh my zsh. Lets chat about this when I'm back in the office on Wednesday

**Comment by christopherfujino** [comment]
> Oh my zsh. Lets chat about this when I'm back in the office on Wednesday

sgtm

**Comment by Piinks** [comment]
The `flutter-gold` check can be disregarded here. I just made a change in `flutter/cocoon` for it to ignore changes that don't run golden file tests, so it won't be coming back around to update this one.

**Comment by jonahwilliams** [comment]
CLosing this for now

**Pull request closed without merging**
