### PR TITLE
feat: enable flavor option on test command

### LINKED ISSUE #82898: integration_test: support --flavor in flutter test
## Steps to Reproduce

1. Create a project that use several flavors (https://flutter.dev/docs/deployment/flavors)
2. Run an integration test: `flutter test integration_test/my_test.dart`
3. Get the error message 
```
The Xcode project defines schemes: dev, prod
Exception: You must specify a --flavor option to select one of the available schemes.
```

4. Try to specify the `--flavor` option: `flutter test --flavor dev integration_test/my_test.dart`

==>
**`Could not find an option named "flavor".`**

<details>
  <summary>Logs</summary>

[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-BE)
    • Flutter version 2.2.0 at /Users/xavier/projects/flutter_stable
    • Framework revision b22742018b (4 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/xavier/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/xavier/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/xavier/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
    • IntelliJ at /Users/xavier/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 56.0.3
    • Dart plugin version 203.8173

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (6 available)
    • SM A300FU (mobile)       • 46f057fd                             • android-arm    • Android 6.0.1 (API 23)
    • Moto G 5 Plus (mobile)   • ZY224FKBCL                           • android-arm    • Android 8.1.0 (API 27)
    • Xavier’s iPhone (mobile) • 00008030-00012D9C0212802E            • ios            • iOS 14.4.2
    • iPhone 11 Pro (mobile)   • EDF6FADF-F5D7-4A4D-8C3A-B9A3231F49E6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)          • macos                                • darwin-x64     • Mac OS X 10.15.7 19H15 darwin-x64
    • Chrome (web)             • chrome                               • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.

</details>

### PR DESCRIPTION
**Pull request by HelloCore**
`flutter test` command doesn't support flavor option, but some projects need flavor in order to build the app for  integration_test.

```bash
$ flutter test --flavor develop -d iPhone integration_test/bla_bla.dart
```

Fixed
#82898

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jaumard** [comment]
That's a must have :)

**Comment by burhanrashid52** [comment]
Are there any updates on this ?

**Review by jmagman — CHANGES_REQUESTED** [review]
I think this needs an integration test.

For example, in here:
https://github.com/flutter/flutter/blob/99c8dd56b45a5e794eb0ca64ae7adc6d07515e04/dev/devicelab/bin/tasks/flavors_test.dart#L11

Adding something like 
```dart
await task(createIntegrationTestFlavorsTest()); 
```
Then in here
https://github.com/flutter/flutter/blob/f673c5c58f7c9332e7ac31d77790d14cdb3b65d9/dev/devicelab/lib/tasks/integration_tests.dart#L24
something like:
```dart
TaskFunction createIntegrationTestFlavorsTest() {
  return IntegrationTest(
    '${flutterDirectory.path}/dev/integration_tests/flavors',
    'lib/main.dart',
    extraOptions: <String>['--flavor', 'paid'],
  );
}
```
`IntegrationTest` would then need to be updated to handle `extraOptions` similar to `DriverTest`.
https://github.com/flutter/flutter/blob/f673c5c58f7c9332e7ac31d77790d14cdb3b65d9/dev/devicelab/lib/tasks/integration_tests.dart#L168

Also add to:
https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/flavors_test_ios.dart
https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/flavors_test_win.dart

**Comment by jiahaog** [comment]
Hi @HelloCore, are you still working on this PR?

**Review by jmagman — CHANGES_REQUESTED** [review]
```
[flavors_test_ios] [STDOUT] stdout: No tests ran.
[flavors_test_ios] [STDOUT] stderr: No tests were found.
```
This needs to actually run tests:
```
$ cd dev/integration_tests/flavors
$ flutter test lib/main.dart --flavor paid
```

**Review by jmagman — CHANGES_REQUESTED** [review]
The flavors iOS app no longer builds.  I filed https://github.com/flutter/flutter/pull/92520 to just add integration_test to this test project, but not change the `flutter test` command.  Once that merges, you can rebase on that PR.

For future reference, can you make sure that both of these commands pass before putting out another review?
```
$ dart bin/run.dart -t flavors_test
$ dart bin/run.dart -t flavors_test_ios
```

**Comment by felangel** [comment]
@HelloCore if you need any help let me know. I'm happy to rebase and help address the remaining feedback to get this merged 😄

**Review by jmagman — APPROVED** [review]
Thanks for the tests.  LGTM!

**Comment by StuartGrantLetherenCameron** [comment]
will this be in the next stable release?

**Comment by jmagman** [comment]
> will this be in the next stable release?

No, it's not yet available in a beta.

**Comment by oligazar** [comment]
@jmagman When can we expect this feature in stable or at least in beta, please?

**Comment by jmagman** [comment]
It's available in 2.9.0-0.0.pre.

**Pull request merged**
