### PR TITLE
Let RenderObjectWidgets use inherited properties

### PR DESCRIPTION
**Pull request by abarth**
This prepares us for depending on the LTR/RTL inherited property in
RenderObjectWidgets.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

**Comment by Hixie** [comment]
lgtm. Can you file a bug on the issue we uncovered where you can mark your earlier sibling dirty if you're a render object widget or a proxy widget?

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (435/400 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:33046 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmNa-000axf-MW
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:39:16 +0100
Date: Mon, 14 Mar 2016 16:58:07 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457999887;
	bh=TpoBwFIdYt0It4sJZU9A2EqbA9qiPwrw0MHaj7LMZV4=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=x5UpjmS/QY50MnAWkYIj3RS2RiMUp3aOiGNPgP85A28lrducqvPZqc62gHFJ8RlBi
	 H+V3ctNldtryva0XnsPk0+vFcsh7e3IjVAdTgh/qRx71GfekTc8Y2+WBe6KypipO0+
	 iwDvcwiKKqigk5U0UU5ZAdaOCr4WvEKc7BOnuTns=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (437/400 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:33300 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmNd-000ayT-GP
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:39:21 +0100
Date: Mon, 14 Mar 2016 16:57:53 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457999873;
	bh=hpEmTgu2cLAHha5nd9iKAEAJ/Q8CT8S7+PynJNQHpnI=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=dE/tXl7QpaUPQOk5tIMB/8wuuWhkpJUgdG1TZrbpB6oyy/6IEC6OhbKukbPDhe+75
	 zrFzVDT5XjfjwrQC0ZD6UYXpwgTQ02TvduC3nB5ZL5JnzsuUs9/yNj2nrCsokj8r4F
	 NVRvuvq/q6wAwdgVmosMI4BmzECTdqaoVKwOjDiY=

**Comment by abarth** [comment]
Done. https://github.com/flutter/flutter/issues/2704

**Pull request merged**
