### PR TITLE
Re-land "Support Scribble Handwriting" (#96615)

### LINKED ISSUE #61278: TextField should support apple pencil input by default.
related: https://github.com/flutter/flutter/issues/38135

not the complex implementation for pressure, tilt, etc.
but textfield should support apple pencil input by default.

figure 1 - text recignition on default text inputs.

[more info about this feature](https://www.theverge.com/2020/6/22/21294662/apple-ipados-14-scribble-pencil-handwriting-typed-text-wwdc-2020)

apple pencil text input works on web html inputs by default, i think it just needs to be recognized as input from ios.

Great thanks to the flutter team.

### PR DESCRIPTION
**Pull request by fbcouch**
Reverts #96615

@LongCatIsLooong 

Fixes #61278

Original PR #75472

Migration Guide: https://github.com/flutter/website/blob/main/src/release/breaking-changes/scribble-text-input-client.md

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by LongCatIsLooong — APPROVED** [review]
LGTM. Sorry I triggered the internal test on the wrong pull request. Testing this one now.

**Comment by LongCatIsLooong** [comment]
I need to get one more fix in to land this.

**Comment by LongCatIsLooong** [comment]
the fix is in @fbcouch  could you resolve the merge conflict? I'll try relanding this.

**Comment by fbcouch** [comment]
@justinmc Friendly ping to see if you can take a look at this, thanks!

**Review by justinmc — APPROVED** [review]
Code and migration guide LGTM 👍 

I'm tempted to merge this now, but @LongCatIsLooong is out for the rest of the week.  We should probably wait for him to be around in case something goes wrong.

**Comment by justinmc** [comment]
I had to revert this due to a failure, but it wasn't in the internal Google tests, it was a test added in this PR.  It failed on all of the CI platforms (Windows, Mac, Linux).  Any idea why?

Here's on of the failed runs: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests_widgets/3425/overview

```
01:31 +1913 ~3 -1: /b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/editable_text_test.dart: multiline Scribble fields can show a vertical placeholder (variant: TargetPlatform.iOS)                
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following StateError was thrown during a scheduler callback:
Bad state: No element

When the exception was thrown, this was the stack:
#0      List.first (dart:core-patch/growable_array.dart:360:5)
#1      EditableTextState._updateSelectionRects.<anonymous closure> (package:flutter/src/widgets/editable_text.dart:2756:168)
#2      new _GrowableList.generate (dart:core-patch/growable_array.dart:136:28)
#3      EditableTextState._updateSelectionRects (package:flutter/src/widgets/editable_text.dart:2748:41)
#4      EditableTextState._updateSizeAndTransform (package:flutter/src/widgets/editable_text.dart:2783:7)
#5      EditableTextState._updateSizeAndTransform.<anonymous closure> (package:flutter/src/widgets/editable_text.dart:2785:49)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1089:9)
#8      AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:995:9)
#11     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#12     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:982:27)
#13     WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:668:23)
#14     WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:662:38)
#17     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#18     WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:662:27)
#19     main.<anonymous closure> (file:///b/s/w/ir/x/w/flutter/packages/flutter/test/widgets/editable_text_test.dart:2050:18)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
```

**Comment by fbcouch** [comment]
😩  I'll take a look...wonder if something that was merged to master between when I last merged to fix that PR and now broke it...at least that's a starting point

**Comment by fbcouch** [comment]
So, a bisect pointed to 55e8a2cd5bc319f9aa9f28f7e3e68ec7672d4a04, which was an engine roll (thankfully of only 1 revision) for this flutter/engine#28912 ... my guess is something about the text layout change is messing with the selection rects. I will try to look more closely at it tomorrow.

**Pull request merged**
