### PR TITLE
Roll engine 091492601479..a52724fcf859 (2 commits)

### PR DESCRIPTION
**Pull request by engine-flutter-autoroll**
https://github.com/flutter/engine/compare/091492601479...a52724fcf859

git log 091492601479..a52724fcf859 --no-merges --oneline
a52724fcf Roll src/third_party/skia ee2a3f36dcf7..92bc476c8c49 (6 commits) (flutter/engine#6083)
f4df18f66 Roll src/third_party/skia 1118cfdbdcc2..ee2a3f36dcf7 (8 commits) (flutter/engine#6082)

The AutoRoll server is located here: https://autoroll.skia.org/r/flutter-engine-flutter-autoroll

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/&#43;/master/autoroll/README.md

If the roll is causing failures, please contact the current sheriff, who should
be CC&#39;d on the roll, and stop the roller if necessary.

### CODE REVIEW

**Comment by engine-flutter-autoroll** [comment]
@rmistry @liyuqian : New roll has been created by https://autoroll.skia.org/r/flutter-engine-flutter-autoroll

**Comment by liyuqian** [comment]
@rmistry I wonder why this is not merged?

**Comment by rmistry** [comment]
Did the number of checks reduce? It says "10 successful checks" and it used to be 11 before: https://skia.googlesource.com/buildbot/+/master/autoroll/config/flutter-engine-flutter.json#4

**Comment by rmistry** [comment]
Changed with https://skia-review.googlesource.com/c/buildbot/+/149360 and pushed to production

**Comment by liyuqian** [comment]
@rmistry it should still be 11. I've no idea why "wip" (work in progress) test isn't triggered here. All other pull requests, including the most recent autorolls, have 11 tests... @gspencergoog do you know why "wip" test is missing here?

**Comment by gspencergoog** [comment]
No, I have no idea why it's missing. Maybe it removes itself now when the WIP is removed? I still see the WIP check working on my PRs.

**Comment by rmistry** [comment]
Should I revert https://skia-review.googlesource.com/c/buildbot/+/149360  then?
I also see WIP running on the newest roll - https://github.com/flutter/flutter/pull/21064

**Comment by liyuqian** [comment]
Yes, I think that we should revert  https://skia-review.googlesource.com/c/buildbot/+/149360 so we still check for 11 successful tests.

**Pull request merged**
