### PR TITLE
Upgrade packages

### PR DESCRIPTION
**Pull request by zanderso**

### CODE REVIEW

**Comment by zanderso** [comment]
Unfortunately, it doesn't look like 'args' was upgraded.

**Comment by Hixie** [comment]
You can use some of the other arguments to the script to see why something is picked. We pin "test", it might be that args is being held back by our version of test.

**Comment by zanderso** [comment]
Thanks, I'll play around with those. It looks like the pinned version of test asks for a recent version of args: https://github.com/dart-lang/test/blob/0.12.26/pubspec.yaml#L10

**Comment by zanderso** [comment]
Okay, my problem is not the flutter pubspec.yamls, but rather pubspec.yaml files in the Dart SDK repo that still say "args: '>=0.13.1 < 0.14.0'". Instead of "args: '>=0.13.1 <2.0.0'"

**Comment by yjbanov** [comment]
tip: you can also use `flutter update-packages --paths --from=packageA --to=packageB` to get a list of possible pub/flutter packages that might be constraining the versions.

**Comment by zanderso** [comment]
Yeah. The problem I was having over in Fuchsia-land had nothing to do with Flutter. This PR is probably still useful though, as it updates some other packages.

**Comment by Hixie** [comment]
This is probably out of date now. I'm going to close it and we can land a new version separately. Sorry we didn't handle this one promptly.

**Pull request closed without merging**
