### PR TITLE
Adds onFocus and onBlur to text fields

### PR DESCRIPTION
**Pull request by Mairramer**
Implementation of onFocus and onBlur based on #45841, #40675 and #140538.
The intention is to add the onFocus and onBlur events, in order to avoid dealing with the events manually and also adds new possibilities.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by LongCatIsLooong** [comment]
`FocusNode` already allows a callback to be registered for those events I think.

**Comment by Mairramer** [comment]
@LongCatIsLooong Are you referring to `FocusOnKeyCallback` and `FocusOnKeyEventCallback`? 
The idea of ​​the proposed implementation would be to use it for general purposes, as we use on the web, but it could be expanded to other platforms.

**Comment by LongCatIsLooong** [comment]
`FocusNode` itself is listenable, and it notifies the listeners when it gains/loses focus.

**Comment by Mairramer** [comment]
We currently use something like `focusNode.addListener(_onFocusChange) ;`  , but the idea would be to make this automatic.
I consider it a good approach, but I don't know if it will contradict the idea of what `FocusNode` currently is.

**Comment by LongCatIsLooong** [comment]
Could you elaborate a bit on what problem this is solving? The new API does not seem to provide new functionalities over the existing focus node API and IMO it doesn't make listening to focus change too much easier either (as compared to `focusNode.addListener`).

**Comment by Mairramer** [comment]
What I want is a less cumbersome way of managing all the listeners on the screen. For example, if I have 10 listeners on the screen, each with its own characteristics, I need to add each one manually. For problem #40675 I simply solve it with Focus. I really still need something, maybe I can simplify the change to just the `TextFormField`.

**Comment by Mairramer** [comment]
I will close this PR. Analyzing it further, it really doesn't make much sense in how my implementation was done and the result I want (to be more flexible like on the web). For now I think the best way is to create abstractions based on what we have.

**Pull request closed without merging**
