### PR TITLE
fix SwitchListTile test

### PR DESCRIPTION
**Pull request by mockturtl**
See #18771.

@escamoteur See [`pumpAndSettle`](https://docs.flutter.io/flutter/flutter_test/WidgetTester/pumpAndSettle.html).

### CODE REVIEW

**Comment by escamoteur** [comment]
How can I confirm the changes?

**Comment by mockturtl** [comment]
For the CLA, I think it will suffice if you :+1: in this thread.  (I just rebased your PR to fix a merge conflict.)

**Comment by escamoteur** [comment]
Just tried, nothing happened

**Comment by escamoteur** [comment]
@Hixie what can we do about that CLA error?

**Comment by dnfield** [comment]
@Hixie I think this looks good, did you have any other comments on this before landing?

I've manually updated the CLA labels because both contributors assent.

**Comment by Hixie** [comment]
Some minor style issues but the code LGTM.

**Comment by mockturtl** [comment]
Landed as #22823, thanks!

**Pull request closed without merging**
