### PR TITLE
Added MultipleFilterChipPicker widget

### LINKED ISSUE #126241: Add ChipSet
See PR: #126308

See the live sample [here](https://dartpad.dev/?id=cd233afb0bf718d4b8bc71cc3999b776)
image

From the Material Design website:

> Multiple chips should appear together in a group, whereas there should be no more than 3 buttons in a single arrangement.

### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

The user needs to select zero or many items in a list.

Problem: no widget allows the user to select multiple items in a list.

Solution: display multiple [`FilterChip`](https://api.flutter.dev/flutter/material/FilterChip-class.html) widgets from left to right, top to bottom, and bind the results to a list.

### Proposal

image

The original sketch code was removed....

See the proposed widget here:
#126308

### PR DESCRIPTION
**Pull request by dhanush17-tech**
MultipleFilterChipPicker Widget 

This PR adds a new widget called MultipleFilterChipPicker to the Flutter codebase. The MultipleFilterChipPicker widget provides a convenient way to display and select multiple filter chips. It allows the user to choose multiple options from a list of filter chips.

Screenshots: multipleFilterChipList

Fixes: #126241

# MultipleFilterChipPicker

A Flutter widget that allows selecting multiple filter chips.

## Features

- Select and deselect filter chips.
- Callback when the selection of filter chips changes.
- Customizable appearance and behavior of filter chips.

## Usage

1. Add the `MultipleFilterChipPicker` widget to your Flutter app.
2. Provide a list of `FilterChipData` objects to the `filterChips` parameter. Each `FilterChipData` object represents a filter chip with a label and an initial selection state.
3. Specify the `onChanged` callback to receive the updated list of selected filter chips whenever the selection changes.
4. Customize the appearance and behavior of the filter chips using the available parameters.

## Features

- Select and deselect filter chips.
- Callback when the selection of filter chips changes.
- Customizable appearance and behavior of filter chips.

## Usage

1. Add the `MultipleFilterChipPicker` widget to your Flutter app.
2. Provide a list of `FilterChipData` objects to the `filterChips` parameter. Each `FilterChipData` object represents a filter chip with a label and an initial selection state.
3. Specify the `onChanged` callback to receive the updated list of selected filter chips whenever the selection changes.
4. Customize the appearance and behavior of the filter chips using the available parameters.

```dart
MultipleFilterChipPicker(
  filterChips: [
    FilterChipData('Filter 1', false),
    FilterChipData('Filter 2', true),
    FilterChipData('Filter 3', false),
  ],
  onChanged: (selectedFilterChips) {
    // Handle the updated list of selected filter chips
  },
  // Customize other parameters as needed
)
```
Customization

The MultipleFilterChipPicker widget provides several parameters to customize the appearance and behavior of the filter chips:

    avatar: Avatar widget for the filter chips.
    labelStyle: Style for the filter chip labels.
    pressElevation: Elevation when a filter chip is pressed.
    disabledColor: Color for disabled filter chips.
    selectedColor: Color for selected filter chips.
    tooltip: Tooltip for filter chips.
    avatarBorder: Border shape for filter chip avatars.
    side: Border side for filter chips.
    clipBehavior: Clip behavior for filter chips.
    focusNode: Focus node for filter chips.
    autofocus: Whether the filter chips should autofocus.
    backgroundColor: Background color for filter chips.
    labelPadding: Padding for filter chip labels.
    visualDensity: Visual density for filter chips.
    surfaceTintColor: Surface tint color for filter chips.
    iconTheme: Icon theme for filter chips.
    selectedShadowColor: Shadow color for selected filter chips.
    showCheckmark: Whether to show a checkmark for selected filter chips.
    checkmarkColor: Color for the checkmark on selected filter chips.
    padding: Padding for filter chips.
    shape: Shape for filter chips.
    isSelectedShadowColor: Whether to use shadow color for selected filter chips.
    filterChipSpacing: Spacing between each filter chip.

Feel free to adjust these parameters according to your specific requirements.

Pre-launch Checklist:

- [x] I read the Contributor Guide and followed the process outlined there for submitting PRs.
- [ ] I read the Tree Hygiene wiki page, which explains my responsibilities.
- [ ] I read and followed the Flutter Style Guide, including Features we expect every widget to implement.
- [x] I signed the CLA.
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with ///).
- [ ] I added new tests to check the change I am making, or if this PR is test-exempt.
- [ ] All existing and new tests are passing.

Please review this PR and provide any feedback or suggestions.
If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
(Just repeating the discussion from Discord here for completeness:)

I think this is probably best done as a package, rather than in the core framework.

**Comment by MelbourneDeveloper** [comment]
@dhanush17-tech, the screenshot you used above is actually my screenshot. It's not your widget at all.

**Comment by dhanush17-tech** [comment]
@MelbourneDeveloper You can customize the widget to that look by playing with the parameters!

**Comment by dhanush17-tech** [comment]
Oh well yeah, I did that. I mean I'm new to open source contribution and I didn't know it was something I shouldn't do. Just wanted to give an example of what the widget could do and the picture seemed to just do that!

I could remove it, if you'd want to

**Pull request closed without merging**
