### PR TITLE
Update AUTHORS

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
Added my name in the AUTHORS file, Hope it will get merged :)
My contribution - #90060 
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by guidezpl — APPROVED** [review]
Thanks for contributing!

**Comment by Pradumnasaraf** [comment]
@Hixie @guidezpl Looks like you have to manually merge this PR because 'this ci.yaml validation' problem is coming in merging every PR.

**Comment by guidezpl** [comment]
Can you try  `git commit --allow-empty -m "trigger checks"` to get the checks going again?

**Comment by Pradumnasaraf** [comment]
> Can you try `git commit --allow-empty -m "trigger checks"` to get the checks going again?

Don't we get an extra commit?

**Comment by Pradumnasaraf** [comment]
> Can you try `git commit --allow-empty -m "trigger checks"` to get the checks going again?

@guidezpl Don't we get an extra commit?

**Comment by Pradumnasaraf** [comment]
> Can you try `git commit --allow-empty -m "trigger checks"` to get the checks going again?

@guidezpl Don't we get an extra commit?. If possible merge from your side or Instruct me, please.

**Comment by guidezpl** [comment]
That's fine, all the commits in a PR get squashed into one when merged to master.

**Comment by Pradumnasaraf** [comment]
@guidezpl Done

**Comment by guidezpl** [comment]
All good ty!

**Comment by Pradumnasaraf** [comment]
Thank You for the merge 🍁

**Pull request merged**
