### PR TITLE
Removed safe area from date range picker

### PR DESCRIPTION
**Pull request by viralkachhadiya**
Related to #85316

### CODE REVIEW

**Comment by KSLiquid** [comment]
It looks really good and seems to solve issue #85316

**Comment by viralkachhadiya** [comment]
@HansMuller 

can you please review this pr?

**Comment by viralkachhadiya** [comment]
@Piinks @PixelToast can you  please review this pr?

**Review by HansMuller — COMMENTED** [review]
Removing the safe area means that the date range picker will not avoid display notches, which isn't desirable as a default. You could defeat the SafeArea with [MediaQuery.removePadding](https://api.flutter.dev/flutter/widgets/MediaQuery/MediaQuery.removePadding.html). 

I don't think we should develop the change proposed by this PR.

**Comment by HansMuller** [comment]
I'm closing this PR per https://github.com/flutter/flutter/pull/85511#pullrequestreview-706571693

**Pull request closed without merging**
