### PR TITLE
Do not silently fail `pub get` even if output-mode is "none"

### LINKED ISSUE #148569: `flutter update-packages` can fail silently
There are probably other instances where this happens, but this is how I am able to consistently reproduce it:

1) Clone flutter from a fork (it's important that it's cloned from a fork because those are missing tags): `git clone git@github.com:goderbauer/flutter.git`
2) Run `./bin/flutter update-packages` inside the cloned repository:
```
$./bin/flutter update-packages
Downloading Darwin arm64 Dart SDK from Flutter engine bf1c6da0dd31273405ae4107ba7225238686140b...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  201M  100  201M    0     0  16.3M      0  0:00:12  0:00:12 --:--:-- 26.2M
Building flutter tool...
Resolving dependencies... 
Downloading packages... 
Got dependencies.
Downloading Material fonts...                                      804ms
Downloading Gradle Wrapper...                                      117ms
Downloading package sky_engine...                                  245ms
Downloading flutter_patched_sdk tools...                           321ms
Downloading flutter_patched_sdk_product tools...                   360ms
Downloading darwin-arm64 tools...                                1,253ms
Downloading libimobiledevice...                                    125ms
Downloading usbmuxd...                                             107ms
Downloading libplist...                                            111ms
Downloading openssl...                                             182ms
Downloading ios-deploy...                                          144ms
Downloading darwin-arm64/font-subset tools...                      341ms
```
3) There's no indication in the output that something has failed, one has to inspect the error code to learn that the command in fact failed silently.

**Expectation:** It prints a clear error describing the failure so it is impossible to miss that something has gone wrong.

Currently, to learn about the real failure, one has to run the command with `-v`:

```
                    ERR : The current Flutter SDK version is 0.0.0-unknown.
                        | 
                        | Because flutter_update_packages depends on webview_flutter_wkwebview >=2.0.14 which requires Flutter SDK version >=2.5.0, version solving failed.
```

Speculatively, the problem of failing silently could be related to this TODO:

https://github.com/flutter/flutter/blob/3695802295777e67af8c5f29c97b68877df29492/packages/flutter_tools/lib/src/commands/update_packages.dart#L527

cc @christopherfujino

### PR DESCRIPTION
**Pull request by matanlurey**
I am making an assumption `OutputMode.none` should _really_ mean `OutputMode.failuresOnly`, that is, if we ever get a non-zero exit code, we still want to know why. If I've somehow misunderstood that, LMK and I'm happy to revert this PR or make adjustments.

This fixes the bug where if you were to do:

```sh
git clone https://github.com/myuser/fork-of-flutter
cd fork-of-flutter
./bin/flutter update-packages
```

You now get:

1. An actual error message, versus no output at all.
2. A warning that a common reason is not tracking a remote, with instructions to fix it.

Closes https://github.com/flutter/flutter/issues/148569.

### CODE REVIEW

**Comment by matanlurey** [comment]
One failure is essentially a lint - I can fix that.

The other is a test that expected no failure (`pub get 66`) but does produce a non-zero exit code.

I suspect updating the test is the right call, but I'm also not 100% sure.

**Review by andrewkolos — APPROVED** [review]
Thanks!

**Comment by andrewkolos** [comment]
I spoke a bit soon! Looks like this is failing `test/general.shard/dart/pub_get_test.dart: pub get 66 shows message from pub`

**Comment by andrewkolos** [comment]
This is failing customer_testing due to seemingly unrelated compilation errors 🤷. I wonder what's going on and whether a rebase/merge would fix this PR.

**Pull request merged**
