### PR TITLE
manual roll of engine to b48566470c5e8758e5ea472044b09b6364e166eb

### PR DESCRIPTION
**Pull request by whesse**
## Description

This patch is necessary to change the version of Dart
used by the flutter tool from 2.9 to 2.10.

It changes the pinned packages in
flutter_tools/.../update_packages.dart
to -nullsafety.2 versions allowing sdk 2.10

It also includes the result of running
flutter update_packages --force-upgrade,
because it needs to be bootstrapped to even run that command.

This needs to be landed with a commit that changes the
checked-out SDK in bin/cache/dart-sdk to a 2.10 version.

## Tests

- [ ] All existing and new tests are passing.
Flutter test fails because it tries to run some product that still is Dart 2.9. Even with --local-engine=host_debug_unopt.
- [ ] The analyzer (`flutter analyze --flutter-repo`)
  reports many problems, don't know if it was also reporting them before.

I think this patch is still needed, as a prerequisite to get to the point where we can run the flutter test and flutter analyze commands.

### CODE REVIEW

**Comment by whesse** [comment]
@zanderso @christopherfujino @jason-simmons

**Comment by whesse** [comment]
Updated original comment to say that flutter test and flutter analyze are failing, but this patch gets flutter to the point where it can even run those commands.

**Comment by zanderso** [comment]
> This needs to be landed with a commit that changes the checked-out SDK in bin/cache/dart-sdk to a 2.10 version.

In that case, this patch sounds like it will have to be included in a manual engine roll.

**Comment by whesse** [comment]
Yes, my intention was that this could be used by the person creating the manual engine roll in the framework, as a starting point that will get the flutter tool working when the roll puts a 2.10 dart sdk in the framework checkout.

**Comment by whesse** [comment]
Adding a manual roll of engine to b48566470c5e8758e5ea472044b09b6364e166eb
which is the current head of engine/master and which includes Dart 2.10.0,
works, after flutter update-packages, the analyzer tests and dev/bots/test.dart
all pass.

Changing the name of this PR to manual roll of engine to b48566470c5e8758e5ea472044b09b6364e166eb

**Comment by whesse** [comment]
All changes here were landed in #62368

**Pull request closed without merging**
