### PR TITLE
v1.12.13+hotfix.7 cherry-picks

### PR DESCRIPTION
**Pull request by tvolkert**
* flutter/engine@a677925 Cherry pick infra testing updates into hotfixes
* flutter/engine@b1bb773 Raise API level for reportFullyDrawn
* flutter/engine@a433ed9 v1.12.13+hotfix.7 cherry-picks
  * google/skia@a640745 Disable QCOM_tiled_rendering while we wait for test devices
  * flutter/engine@bcb8267 Revert "Do not default to downstream affinity on iOS insertText"
* d345a3b Revert "Track and use fallback TextAffinity for null affinity platform TextSelections. (#44622)"
* bd25f70 Upgrade dartdoc to 0.29.3
* 7915e58 Change firebase Pixel3 version from Q-beta3 to 29

### CODE REVIEW

**Review by dnfield — COMMENTED** [review]
LGTM

**Comment by tvolkert** [comment]
flutter/flutter#47804
flutter/flutter#47164

**Comment by GaryQian** [comment]
Changes regarding Revert "Track and use fallback TextAffinity for null affinity platform TextSelections. (#44622)" LGTM

**Comment by dnfield** [comment]
I don't quite understand why, but it's failing when it tries to global activate dartdoc 0.29.1

Bumping it to 0.29.3 (the current version on master) is not failing at the same step.  bd25f70c66ccd832d53644bd33a1368e96a7aa75 is the commit to cherrypick.

**Comment by dnfield** [comment]
@tvolkert this is actually green on citrus.  Should be safe to land now

**Pull request merged**
