### PR TITLE
Support failures-only and silent reporters in `flutter test`

### LINKED ISSUE #148738: Failures-only reporter for `flutter test`
As discussed at #27845, it would be very helpful to be able to have `flutter test` report details about failures, without printing a line for every success.

This is already what it mostly does by default for interactive use (the exceptions to "mostly" include skips and tests with noisy output of their own), by overwriting the same line repeatedly using terminal escape sequences. But that's not available in a CI context.

Recent versions of `package:test` support this, with `--reporter failures-only`. So we just need to accept that argument ourselves, and pass it through.

### PR DESCRIPTION
**Pull request by gnprice**
Fixes #148738.

Also add some tests for this part of the `flutter test` CLI.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by gnprice** [comment]
Test flake in CI; rebased to pick up #148737.

**Comment by andrewkolos** [comment]
Note for self: when this lands, we should consider using `failures-only` for flutter tool CI tests that use package:test

**Review by andrewkolos — APPROVED** [review]
LGTM!

**Comment by andrewkolos** [comment]
> Note for self: when this lands, we should consider using `failures-only` for flutter tool CI tests that use package:test

Filed https://github.com/flutter/flutter/issues/149611 to track this.

**Pull request merged**
