### PR TITLE
image filled is now nullable

### PR DESCRIPTION
**Pull request by hasanm08**
in null safety projects, it is better for the Decoration image, image  field to be nullable
please change if needed

### CODE REVIEW

**Comment by devj3ns** [comment]
Hey @hasanm08, I don't understand why the `image` property of `DecorationImage` should be nullable. To me, it seems really unreasonable.

Maybe you have a use case where it is nice, but for the most use cases it's a really good thing that `image` is required (e.g. see 56 failing tests).

So, I really don't think this gets merged.

**Comment by hasanm08** [comment]
> 

Hi @devj3ns due to servers dynamic data, the nullable image will make the code cleaner and more null-safety

**Review by Piinks — COMMENTED** [review]
Hi @hasanm08, thanks for the PR. I think that if there is no image, then the DecorationImage widget should not be used, allowing a null image does not sound right here. Also, this PR does not have any tests, and it appears to be breaking many of them.

Is there an open issue that you are trying to address here?

**Comment by hasanm08** [comment]
I had this issue and tried to fix it
because when I saw this field
I don have any sense about being null-safety

_Note that we have refresh capability in the web platform that may null our data so plus caching we should make our widgets complete null-safe too_

about many broken tests Please check my PR, maybe something missed
I hope this PR helps the usability and stability of flutter multi-platform projects

have a good day :)

**Comment by Piinks** [comment]
Hi @hasanm08 unfortunately I cannot debug your PR for you, and this is not a change we would want to make to this widget. For these reasons I am going to close this PR, thank you for contributing!

**Pull request closed without merging**
