### PR TITLE
Revert "Fix the second TextFormField to trigger onTapOutside"

### PR DESCRIPTION
**Pull request by Renzo-Olivares**
Reverts flutter/flutter#148206

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
What's the reason for the revert?

**Comment by Renzo-Olivares** [comment]
@gspencergoog This looks like the culprit for the tree being red.

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8747210306750076193/+/u/run_test.dart_for_web_canvaskit_tests_shard_and_subshard_1/stdout

```
05:36 +663 ~89: test/widgets/editable_text_test.dart: keyboard is requested after setEditingState after switching to a new text field
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: [
            'TextInput.clearClient',
            'TextInput.setClient',
            'TextInput.setEditableSizeAndTransform',
            'TextInput.setMarkedTextRect',
            'TextInput.setStyle',
            'TextInput.setEditingState',
            'TextInput.show',
            'TextInput.requestAutofill',
            'TextInput.setCaretRect'
          ]
  Actual: MappedListIterable<MethodCall, String>:[
            'TextInput.clearClient',
            'TextInput.hide',
            'TextInput.setClient',
            'TextInput.setEditableSizeAndTransform',
            'TextInput.setMarkedTextRect',
            'TextInput.setStyle',
            'TextInput.setEditingState',
            'TextInput.show',
            'TextInput.requestAutofill',
            'TextInput.setCaretRect'
          ]
   Which: at location [1] is 'TextInput.hide' instead of 'TextInput.setClient'
```

**Comment by Renzo-Olivares** [comment]
cc @wyqlxf

**Comment by wyqlxf** [comment]
@Renzo-Olivares Thank you for your feedback. It will indeed fail on the web platform. I will check again.

**Pull request merged**
