### PR TITLE
Revert engine back to afb9d510c3bb0f1b97980434b41200a2d3491697

### PR DESCRIPTION
**Pull request by zanderso**
This reverts two engine rolls:

https://github.com/flutter/flutter/commit/c84767cae8c8874b192e35e9777a7046c4aff60c
https://github.com/flutter/flutter/commit/881cdfdeb073bdd489533fc4f049fbe16e39f36c

For consistent bot failures in the android_views integration test.

Looks related: https://github.com/flutter/engine/commit/5ea125eaf9e15a3e4eefe89b13cb86b0ba820d8f @matthew-carroll @amirh

### CODE REVIEW

**Comment by zanderso** [comment]
@bparrishMines

**Review by tvolkert — APPROVED** [review]

**Comment by zanderso** [comment]
Also reverting https://github.com/flutter/flutter/commit/61b83d320e9149828ffb5e39e1da6d14d281c0c2 @goderbauer

**Comment by goderbauer** [comment]
Why is 61b83d3 getting reverted?

**Comment by zanderso** [comment]
@goderbauer There were failures related to that change in the presubmit checks for the engine revert by itself.

**Comment by goderbauer** [comment]
Can you link to the failure so I can debug that for re-landing?

**Comment by zanderso** [comment]
https://api.cirrus-ci.com/v1/task/6642212578787328/logs/test.log

**Comment by matthew-carroll** [comment]
@zanderso do you know what I can do to repro whatever the problems were with flutter/engine@5ea125e ? I ran an app locally before putting up the PR, and the PR checks were green...

**Comment by amirh** [comment]
@matthew-carroll run the android_views driver test

**Comment by zanderso** [comment]
It looks like the test might have only been failing on Mac, so that might be where to start: https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9jODQ3NjdjYWU4Yzg4NzRiMTkyZTM1ZTk3NzdhNzA0NmM0YWZmNjBjDAsSBFRhc2sYgIDA8L2HlwkM

**Pull request merged**
