### PR TITLE
Fix a type error in Scrollable.ensureVisible

### LINKED ISSUE #14492: Stepper throws exception caused by type tap
When adding the `Stepper` Widget nested I get the error below and the `onStepTapped` not get called. I was looking into the `Stepper` implementation but could not find the source of this issue.

## Code to Reproduce

```
class HomeScreen extends StatelessWidget  {
  @override
  Widget build(BuildContext context) {
    var body = new Column(children: <Widget>[
      new Expanded(child: new HomeTabBar()),
    ]);

    return new Scaffold(
        appBar: new AppBar(
            title: new Text('Dein Fortschritt', style: new TextStyle(fontSize: 12.0, letterSpacing: 1.5)),
        ),
        body: new SafeArea(child: body, bottom: true),
    );
  }
}

class HomeTabBar extends StatefulWidget {
  @override
  _HomeTabBarState createState() => new _HomeTabBarState();
}

class _HomeTabBarState extends State<HomeTabBar> with SingleTickerProviderStateMixin {
  double _tabBarHeight = 51.0;
  TabController _controller;

  @override
  void initState() {
    super.initState();
    _controller = new TabController(length: 2, vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    return new TabBarView(
        controller: _controller,
        children: <Widget>[
          new _LevelView(),
          new _LevelView(),
        ],
    );

  }
}

class _LevelView extends StatefulWidget {
  @override
  _LevelViewState createState() => new _LevelViewState();
}

class _LevelViewState extends State<_LevelView> {
  int current_step = 0;
  List<Step> my_steps = [
    new Step(
      // Title of the Step
        title: new Text("Step 1"),
        // Content, it can be any widget here. Using basic Text for this example
        content: new Text("Hello!"),
        isActive: true),
    new Step(
        title: new Text("Step 2"),
        content: new Text("World!"),
        // You can change the style of the step icon i.e number, editing, etc.
        state: StepState.editing,
        isActive: true),
    new Step(
        title: new Text("Step 3"),
        content: new Text("Hello World!"),
        isActive: true),
  ];

  @override
  Widget build(BuildContext context) {

    var stepper = new Stepper(
      currentStep: this.current_step,
      steps: my_steps,
      type: StepperType.vertical,
      onStepTapped: (step) {
        setState(() {
          current_step = step;
        });
        print("onStepTapped : " + step.toString());
      },
      onStepCancel: () {
        setState(() {
          if (current_step > 0) {
            current_step = current_step - 1;
          } else {
            current_step = 0;
          }
        });
        print("onStepCancel : " + current_step.toString());
      },
      onStepContinue: () {
        setState(() {
          if (current_step < my_steps.length - 1) {
            current_step = current_step + 1;
          } else {
            current_step = 0;
          }
        });
        print("onStepContinue : " + current_step.toString());
      },
    );

    return new Container(color: Colors.red, child: stepper) ;
  }
}
```

## Logs

```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
type '_Future<List>' is not a subtype of type 'Future<Null>' of 'function result' where
_Future is from dart:async
List is from dart:core
Future is from dart:async
Null is from dart:core

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#0      Scrollable.ensureVisible (package:flutter/src/widgets/scrollable.dart:217:19)
#1      _StepperState._buildVertical.<anonymous closure> (package:flutter/src/material/stepper.dart:526:28)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:468:14)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:520:30)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
#6      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
#7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#8      BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
#9      BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
#10     BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
#11     BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
#12     BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
#13     _invoke1 (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:134)
#14     _dispatchPointerDataPacket (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:91)

Handler: onTap
Recognizer:
TapGestureRecognizer#e977f(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
Offset(126.0, 314.3), sent tap down)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.13.3 17D47, locale en-DE, channel alpha)
    • Flutter version 0.0.21 at /Users/eikebartels/Applications/flutter
    • Framework revision 2e449f06f0 (8 days ago), 2018-01-29 14:26:51 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/eikebartels/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[-] IntelliJ IDEA Community Edition (version 2017.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 173.4548.30
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
```

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/14492

### CODE REVIEW

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm

**Comment by Hixie** [comment]
How is the analyzer not catching this??? cc @leafpetersen @pq

**Comment by pq** [comment]
cc @bwilkerson

**Comment by mraleph** [comment]
@Hixie It's an implicit downcast: `Future<Null>` is a subtype of `Future<List<Null>>` so an instance of type `Future<Null>` might be hiding within a variable of type `Future<List<Null>>`. So when analyzer (or any Dart 2 runtime) sees 

```dart
static Future<Null> ensureVisible(...) {
  // ...
  return Future.wait<Null>(futures);
}
```

they treat it as essentially: 

```dart
static Future<Null> ensureVisible(...) {
  // ...
  return Future.wait<Null>(futures) /* implicit down cast => */ as Future<Null>;
}
```

So from type system perspective there is nothing wrong.

Of course analyzer could have known that the downcast would always fail based on either hard-coded semantics for `Future.wait<T>` or something else - but I don't think there are any rules like that available.

Sidenote: this is a place where `void` should really be used instead of `Null`.

**Comment by keertip** [comment]
fyi, you will be able to use `void` once flutter moves to dart `2.0.0-dev.20.0`.

**Comment by Hixie** [comment]
Oh man, implicit downcasts are such a source of bugs.

**Comment by mraleph** [comment]
@Hixie yeah, they often are, they are also very helpful when you just want to write code quickly (which is why they were there essentially since the early days of Dart). there is large discussion going about removing them later, see dart-lang/sdk#31410 - if you have not checked it out already.

**Comment by Hixie** [comment]
Yeah, we plan to turn on the relevant lints once dart2 has landed enough that we can use `as` again.

**Pull request merged**
