### PR TITLE
Fix bugs of Gradle script support Flutter-as-lib

### PR DESCRIPTION
**Pull request by SupSaiYaJin**
1. Change dependencies of plugins from 'implementation' to 'api' to support flutter-as-lib.
2. Fix packaging problem when root module name is not app.

### CODE REVIEW

**Comment by SupSaiYaJin** [comment]
Why nobody review this？T_T

**Comment by SupSaiYaJin** [comment]
Finally, checks have passed!
fuck --track-widget-creation

**Comment by SupSaiYaJin** [comment]
The reason for using api instead of implementation is that some plugins may need some configurations or initialization and flutter mudule can't get the configuration or decide when to initialize. So plugin's classes should be accessible to app module.

**Comment by zoechi** [comment]
Thanks for your contribution and sorry for the delay. 
People were quite busy preparing Flutter 1.0 and Flutter live.

**Comment by SupSaiYaJin** [comment]
any update for this?

**Pull request closed without merging**
