### PR TITLE
Animate size of label text over text fields.

### LINKED ISSUE #7217: Text label doesn't scale up when focus is applied
From a review with an eng on the material team.

In the gallery, go into the Text Input demo. When you tap into a field, notice how the tooltip in the field (e.g. "Name") immediately switches to blue and smaller, and then animates up.

Instead, the text "Name" should smoothly animate up, and smoothly change to blue, and smoothly shrink in size.

The final resting place of "Name" is correct.

### PR DESCRIPTION
**Pull request by mpcomplete**
Fixes https://github.com/flutter/flutter/issues/7217

### CODE REVIEW

**Comment by HansMuller** [comment]
LGTM

**Comment by Hixie** [comment]
This needs a test.
@HansMuller Please do not LGTM without a test. :-)

@mpcomplete Did you check how this looks? Often animating font-size looks terrible because of snapping in the font hinting, and we end up wanting to animate the transform instead.

**Comment by mpcomplete** [comment]
@Hixie yes, there's snapping (though I didn't notice it until I slowed down animations). That seems like a deficiency of AnimatedDefaultTextStyle. Can we fix that instead of introducing a transform here?

**Comment by Hixie** [comment]
What's going on is that fonts are not pure vectors, they're programs that snap to pixel boundaries based on their font size (this is known as hinting). So as you change the font size, the underlying vectors change in a non-linear fashion. Basically, animating the font size is not the same as animating the text growing.

**Comment by mpcomplete** [comment]
Right - but AnimatedDefaultTextStyle exists, and will happily animate between font sizes. We should figure out how to make that look good (or don't try, and explicitly note that it shouldn't be used for font size changes)

**Comment by Hixie** [comment]
Documenting it is certainly a good idea.

**Comment by mpcomplete** [comment]
Here's another version that smoothly interpolates between the 2 font sizes using a Transform. Working on a test, but I wanted to get your feedback @Hixie to see if you liked this approach. I'm adding a `scale` param to DefaultTextStyle that Text uses to decide whether to add a Transform.

I also added a fade-in to the hintText, so it doesn't pop in immediately on top of the label while that animates out of the way.

**Comment by Hixie** [comment]
I'm a little skeptical about adding a transform to RichText for this, because it will have really weird effects on multiline text.

@abarth may have another opinion, I'd be curious to hear what he thinks.

**Comment by abarth** [comment]
I don't think we should add a Transform to RichText.  Instead, we should do something more specific to input field animations.

**Comment by mpcomplete** [comment]
OK, the label animation is now local to input.dart.

As for a test: this patch makes the animation "look better". That's not really something I can test via automation. I can test that there is now an animation, but that seems oddly specific and not really in the spirit of an automated test. WDYT?

**Comment by Hixie** [comment]
What are you worried I'll accidentally regress when I walk into this code like a bull in a china shop?

Test that. :-)

**Comment by mpcomplete** [comment]
Added a test.

**Comment by HansMuller** [comment]
LGTM

**Pull request merged**
