### PR TITLE
Clean up MenuAnchor

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR cleans up some typos and formatting issues in the `material/menu_anchor.dart` file and associated tests.

### CODE REVIEW

**Review by gspencergoog — COMMENTED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Thank you!

**Comment by Piinks** [comment]
Hey @bleroux looks like there are some merge conflicts, can you take a look?

**Comment by bleroux** [comment]
Ohoh, https://github.com/flutter/flutter/pull/150914 was merged in between the moment I submitted this PR and the approval.
Let me push an update.

**Comment by bleroux** [comment]
@gspencergoog Not sure if you clicked the approve button the first time  :smile:  . I updated the PR to resolve the merge conflict.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

(Again!)

**Comment by gspencergoog** [comment]
> @gspencergoog Not sure if you clicked the approve button the first time 😄 . I updated the PR to resolve the merge conflict.

What?!? The bot can't read my LGTM on its own? Soo 2023. :-)

**Comment by anishthakur-krofile** [comment]
In stable version 3.27.0 getting offset issue for menuAnchor as it was not earlier as per current issue in git: https://github.com/flutter/flutter/pull/159665 please have a look

**Pull request merged**
