### PR TITLE
[flutter_tool] Suggest fix for transform input

### LINKED ISSUE #82262: Flutter build apk not working with flavors
Cannot release apk for production!!!

After upgrading to null safety i needed to upgrade to gradle 4.0.

Same as https://github.com/flutter/flutter/issues/58247 which was opened over a year ago!!

Gradle expects a ../libs.jar for every combination of flavor - buildType (in new project needs 3 - release - debug - profile, in my project needs 48 so the 'solutions' (offered on the above issue) of running each one once is out of the question especially with dev-op).

This prevents us from any future action with our app. Can this be fixed maybe in a hotfix?

## Steps to Reproduce

- Run flutter create counter
- Add this to build.gradle:

`` 

	flavorDimensions "app"
	
	productFlavors {
		flavor1{
			dimension "app"
		}
		flavor2{
			dimension "app"
		}
	}

- Run flutter build apk --flavor flavor1

Output:

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:lintVitalFlavor1Release'.
> Could not resolve all artifacts for configuration ':app:flavor2ReleaseRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\nikts\Projects\counter\build\app\intermediates\flutter\flavor2Release\libs.jar.
         > Transform's input file does not exist: C:\Users\nikts\Projects\counter\build\app\intermediates\flutter\flavor2Release\libs.jar. (See https://issuetracker.google.com/issues/158753935)

flutter doctor:

C:\Users\nikts\Projects\counter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.0)
[√] Connected device (2 available)

• No issues found!

### PR DESCRIPTION
**Pull request by blasten**
Suggests a fix to the user instead of ending with the Gradle error message. 

`checkReleaseBuilds` is useful, and should ideally be enabled. 
There are still corner cases like [using flavors](https://github.com/flutter/flutter/issues/82262), which trigger this issue.

Fixes: https://github.com/flutter/flutter/issues/82262 (This isn't the real fix to the root problem, but addresses the comment.)
Related issue: https://github.com/flutter/flutter/issues/58247

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
According to the android bug, this is fixed in AGP 7.0. Do we know if this is usable for Flutter? If so, could we suggest that people try upgrading first?

**Comment by blasten** [comment]
I wonder if they meant Gradle 7.0. The latest released AGP version is 4.2.0 (from March 2021).

I did tried with the latest version, and it's not fixed yet. Also, this is a different bug https://issuetracker.google.com/issues/158753935

**Comment by jonahwilliams** [comment]
oof. Thanks for checking,.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
