### PR TITLE
Popup menu custom padding

### LINKED ISSUE #57110: Custom Padding in PopupMenuButton
Not able to configure padding in PopupMenuButton.  It is seems like it using the default values for vertical and horizontal paddings,
```
const double _kMenuCloseIntervalEnd = 2.0 / 3.0;
const double _kMenuHorizontalPadding = 16.0;
const double _kMenuDividerHeight = 16.0;
const double _kMenuMaxWidth = 5.0 * _kMenuWidthStep;
const double _kMenuMinWidth = 2.0 * _kMenuWidthStep;
const double _kMenuVerticalPadding = 8.0;
const double _kMenuWidthStep = 56.0;
const double _kMenuScreenPadding = 8.0;
```
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (11 days ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1

### PR DESCRIPTION
**Pull request by Moluram**
Provides ability to change PopupMenuButton popup menu padding.

Fixes #57110.

_This is my first PR! It's really great to participate in such a big project :)_

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Piinks** [comment]
Hi @Moluram it looks like there are some merge conflicts here, would you like to take a look and update this PR?

**Comment by MahMoos** [comment]
Any update on this?

**Comment by arafaysaleem** [comment]
What's the status of this PR?

**Comment by arafaysaleem** [comment]
@darrenaustin I opened a new PR with the same changes applied on the latest master branch. The PR is hopefully updated now

- #96657

**Comment by arafaysaleem** [comment]
@darrenaustin we can close this

**Comment by ronytesler** [comment]
How can I set the _kMenuScreenPadding?

**Comment by fa-fifi** [comment]
SInce this issue is not solved yet, I open a new one https://github.com/flutter/flutter/issues/143512.

**Comment by ivictoruan** [comment]
Hello??? It's not solved? I've see many issues to  solve this problem and nothing! What's happing?

**Pull request closed without merging**
