### PR TITLE
Use the same flags as Android on iOS while starting on the simulator

### PR DESCRIPTION
**Pull request by chinmaygarde**
- The initialization of the SkySettings goes through a common path in the engine. So I am using the same flags as iOS.

### CODE REVIEW

**Comment by krisgiesing** [comment]
LGTM

**Comment by chinmaygarde** [comment]
Fixes https://github.com/flutter/flutter/pull/1699

**Comment by chinmaygarde** [comment]
Fixes https://github.com/flutter/flutter/issues/1458

**Comment by chinmaygarde** [comment]
Fixes https://github.com/flutter/flutter/issues/1511 for checked mode

**Comment by chinmaygarde** [comment]
Fixes https://github.com/flutter/flutter/issues/1652 for `start --checked`

**Pull request merged**
