### PR TITLE
Fix the issue of Android add2app build fails on Android when assets are read-only

### PR DESCRIPTION
**Pull request by shihchanghsiungsonos**
## Description

With the latest dev build (Flutter 1.10.14-dev), the flutter:copyFlutterAssets task fails when the assets being copied are read-only. This can happen when a source control tool makes files read-only.

## Related Issues

https://github.com/flutter/flutter/issues/43686

## Tests

I added the following tests:

The change fixes the build issue.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by blasten** [comment]
@shihchanghsiungsonos This LGTM. Would you be able to modify https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/module_test.dart to make some assets read only?

**Comment by shihchanghsiungsonos** [comment]
> @shihchanghsiungsonos This LGTM. Would you be able to modify https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/module_test.dart to make some assets read only?



> @shihchanghsiungsonos This LGTM. Would you be able to modify https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/module_test.dart to make some assets read only?

Do you mean to make, for example, "isolate_snapshot_data" as read only in module_test.dart and run the test "../../bin/cache/dart-sdk/bin/dart bin/run.dart -t module_test"?

**Comment by blasten** [comment]
Yes -- After [this line](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/module_test.dart#L176), change the file permission to read only, then build again and verify that it currently fails and then with your fix, it passes.

**Comment by xster** [comment]
@shihchanghsiungsonos let us know if you need any additional help with the tests for this PR

**Comment by shihchanghsiungsonos** [comment]
> @shihchanghsiungsonos let us know if you need any additional help with the tests for this PR

Thanks for the follow up @xster !

Sorry for the delay. I haven't ran this before.

When I tried this comment:

`../../bin/cache/dart-sdk/bin/dart bin/run.dart -t module_test`

I am getting these errors:

```
Error: Could not resolve the package 'args' in 'package:args/args.dart'.
Error: Could not resolve the package 'path' in 'package:path/path.dart'.
Error: Could not resolve the package 'flutter_devicelab' in 'package:flutter_devicelab/framework/manifest.dart'.
Error: Could not resolve the package 'flutter_devicelab' in 'package:flutter_devicelab/framework/runner.dart'.
Error: Could not resolve the package 'flutter_devicelab' in 'package:flutter_devicelab/framework/utils.dart'.
bin/run.dart:9:8: Error: Not found: 'package:args/args.dart'
import 'package:args/args.dart';
       ^
bin/run.dart:10:8: Error: Not found: 'package:path/path.dart'
import 'package:path/path.dart' as path;
       ^
bin/run.dart:12:8: Error: Not found: 'package:flutter_devicelab/framework/manifest.dart'
import 'package:flutter_devicelab/framework/manifest.dart';
       ^
bin/run.dart:13:8: Error: Not found: 'package:flutter_devicelab/framework/runner.dart'
import 'package:flutter_devicelab/framework/runner.dart';
       ^
bin/run.dart:14:8: Error: Not found: 'package:flutter_devicelab/framework/utils.dart'
import 'package:flutter_devicelab/framework/utils.dart';
       ^
```
Is there anything I need to make sure before running this test? Thanks for the help!

**Comment by xster** [comment]
I don't think I've seen these issues so I'm not 100% sure but `flutter update-packages` could likely solve it if you run it at the Flutter repo's root.

**Comment by shihchanghsiungsonos** [comment]
> I don't think I've seen these issues so I'm not 100% sure but `flutter update-packages` could likely solve it if you run it at the Flutter repo's root.

Thank you! It fixes the errors. Will update once I verify the fix.

**Comment by xster** [comment]
cool, good to hear. Thanks for your contribution.

**Comment by shihchanghsiungsonos** [comment]
> cool, good to hear. Thanks for your contribution.

I don't have much luck.

After these:
```
        await exec(gradlewExecutable,
          <String>['app:assembleDebug'],
          environment: <String, String>{
            'JAVA_HOME': javaHome,
            'FLUTTER_ANALYTICS_LOG_FILE': analyticsOutputFile.path,
          },
        );
```

I add line to exec 'chmod +r' to make `flutter_assets/isolate_snapshot_data` read only. But, always get file not found. what's the correct file path for `flutter_assets/isolate_snapshot_data`?

Thanks for the help!

**Comment by shihchanghsiungsonos** [comment]
> > cool, good to hear. Thanks for your contribution.
> 
> I don't have much luck.
> 
> After these:
> 
> ```
>         await exec(gradlewExecutable,
>           <String>['app:assembleDebug'],
>           environment: <String, String>{
>             'JAVA_HOME': javaHome,
>             'FLUTTER_ANALYTICS_LOG_FILE': analyticsOutputFile.path,
>           },
>         );
> ```
> 
> I add line to exec 'chmod +r' to make `flutter_assets/isolate_snapshot_data` read only. But, always get file not found. what's the correct file path for `flutter_assets/isolate_snapshot_data`?
> 
> Thanks for the help!

I found the path. But, change the file permission after `await exec(gradlewExecutable` is probably too late, since the apk has been created.

I think @blasten 's suggestion to change the asset to read only within `await exec(gradlewExecutable`. what's the right line I should add to change asset's file permission before the apk is created. Thanks!

**Comment by blasten** [comment]
@shihchanghsiungsonos what about adding a user read only .txt file to `flutter_assets` and then verify that the file copied into `packageAssets.outputDir` is user-readable and writable?  The output dir should be `build/app/intermediates/merged_assets/<build-variant>/out/flutter_assets/`.

**Comment by shihchanghsiungsonos** [comment]
> @shihchanghsiungsonos what about adding a user read only .txt file to `flutter_assets` and then verify that the file copied into `packageAssets.outputDir` is user-readable and writable? The output dir should be `build/app/intermediates/merged_assets/<build-variant>/out/flutter_assets/`.

Will give it a try. Thanks!

**Comment by zanderso** [comment]
@shihchanghsiungsonos Are you interested in continuing with this PR?

**Comment by shihchanghsiungsonos** [comment]
> @shihchanghsiungsonos Are you interested in continuing with this PR?

Yes. But, having problem to verify the way @blasten is asking.

**Comment by shihchanghsiungsonos** [comment]
With the latest, I am seeing these errors when running the module_test:

`[module_test] [STDOUT] stderr: /private/var/folders/dz/89m7jll94sl27tqp1612sht1qx16hy/T/flutter_module_test.jKSft7/hello_host_app/app/src/main/java/io/flutter/add2app/MainActivity.java:9: error: package io.flutter.facade does not exist
[module_test] [STDOUT] stderr: import io.flutter.facade.Flutter;
[module_test] [STDOUT] stderr:                         ^
[module_test] [STDOUT] stderr: /private/var/folders/dz/89m7jll94sl27tqp1612sht1qx16hy/T/flutter_module_test.jKSft7/hello_host_app/app/src/main/java/io/flutter/add2app/MainActivity.java:16: error: cannot find symbol
[module_test] [STDOUT] stderr:     setContentView(Flutter.createView(this, getLifecycle(), "route1"));
[module_test] [STDOUT] stderr:                    ^`

**Comment by blasten** [comment]
@shihchanghsiungsonos how did you run the test?

To run the test, run `cd <flutter-sdk>/dev/devicelab`.  Then `../../bin/cache/dart-sdk/bin/dart bin/run.dart -t module_test`

**Comment by shihchanghsiungsonos** [comment]
> @shihchanghsiungsonos This LGTM. Would you be able to modify https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/module_test.dart to make some assets read only?

Tes, that's what i did. thanks!

**Comment by blasten** [comment]
What version of the Flutter SDK are you using? Are you on master?

**Comment by shihchanghsiungsonos** [comment]
> What version of the Flutter SDK are you using? Are you on master?

Dev branch v1.14.3

[✓] Flutter (Channel dev, v1.14.3, on Mac OS X 10.14.6 18G2022, locale en-US)
    • Flutter version 1.14.3 at /Users/shihchang.hsiung/development/git/flutter-dev-new
    • Framework revision b5a23fdf5b (3 days ago), 2020-01-22 02:11:09 +0800
    • Engine revision c15efb9231
    • Dart version 2.8.0 (build 2.8.0-dev.3.0 f910a7575f)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/shihchang.hsiung/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/shihchang.hsiung/Library/Android/sdk/
    • ANDROID_SDK_ROOT = /Users/shihchang.hsiung/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Shih-Chang’s iPhone • 83c3a17190068bb7d7ff580eb58f916ab8e7db37 • ios • iOS 13.3

**Comment by blasten** [comment]
what about if you run `export ENABLE_ANDROID_EMBEDDING_V2='true'` and then `../../bin/cache/dart-sdk/bin/dart bin/run.dart -t module_test`.

**Comment by shihchanghsiungsonos** [comment]
> what about if you run `export ENABLE_ANDROID_EMBEDDING_V2='true'` and then `../../bin/cache/dart-sdk/bin/dart bin/run.dart -t module_test`.

Yea, that fixes the issue. Thanks!

**Comment by shihchanghsiungsonos** [comment]
Okay, I have verified before the fix, the asset is user-readable only. After the fix, the asset is user-readable and writable. Thanks!

**Comment by blasten** [comment]
@shihchanghsiungsonos Are you still working on this PR or a new one?

**Comment by shihchanghsiungsonos** [comment]
> @shihchanghsiungsonos Are you still working on this PR or a new one?



> @shihchanghsiungsonos Are you still working on this PR or a new one?

Still on this one. I just verified the fix as you requested. Is there anything else i need to do? Thanks!

**Comment by blasten** [comment]
@shihchanghsiungsonos I thought you were going to add the test to this PR. Is that still case?

**Comment by shihchanghsiungsonos** [comment]
@blasten, sorry i didn't know that the test case needs to be updated. I will work on that.

**Comment by christopherfujino** [comment]
@shihchanghsiungsonos somehow this PR gained a huge diff (looks to be the result of a non-standard git merge).

**Comment by shihchanghsiungsonos** [comment]
Just commit the change to update module_test test case, not sure why there are so many files changed?

**Comment by shihchanghsiungsonos** [comment]
> @shihchanghsiungsonos somehow this PR gained a huge diff (looks to be the result of a non-standard git merge).

Just did:
git fetch updtream
git pull
git commit -a -m
git push origin dev-local

**Comment by shihchanghsiungsonos** [comment]
@christopherfujino should I start another new PR and close this one?

**Comment by christopherfujino** [comment]
@shihchanghsiungsonos that might be easiest. When you start a new branch, make sure you create your branch by starting from master. If you branch off of stable, it won't cleanly merge to master.

**Comment by shihchanghsiungsonos** [comment]
> @shihchanghsiungsonos that might be easiest. When you start a new branch, make sure you create your branch by starting from master. If you branch off of stable, it won't cleanly merge to master.

Cool. Thanks!

**Comment by jmagman** [comment]
> > @shihchanghsiungsonos that might be easiest. When you start a new branch, make sure you create your branch by starting from master. If you branch off of stable, it won't cleanly merge to master.
> 
> Cool. Thanks!

Closing in favor of your new PR, thank you!

**Comment by shihchanghsiungsonos** [comment]
I have created a new PR: https://github.com/flutter/flutter/pull/50047

Close this one.

**Pull request closed without merging**
