### PR TITLE
Fix _DragAvatar to display in the proper position for Overlays whose Point.origin is not the global Point.origin.

### PR DESCRIPTION
**Pull request by apwilson**

### CODE REVIEW

**Comment by Hixie** [comment]
Can I trouble you for a unit test?

**Comment by apwilson** [comment]
Yeah

**Comment by johnmccutchan** [comment]
Is this PR still current?

**Comment by apwilson** [comment]
I'll take a look today and add tests or close.

**Comment by apwilson** [comment]
This PR has been replaced by https://github.com/flutter/flutter/pull/7223 with added tests.

**Pull request closed without merging**
