### PR TITLE
Wrap launching devtools in DevtoolsLauncher

### PR DESCRIPTION
**Pull request by chingjun**
This allows launching Devtools to be overridden.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Sorry I didn't get to this sooner. What I would do is write a test that injects a fake devtools launcher and assert that it is used somehow.

**Comment by jonahwilliams** [comment]
For example: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/resident_runner_test.dart#L1245

Write a test like this that invokes the launch devtools method with an injected fake, assert that fake is called correctly and not real devtools

**Comment by chingjun** [comment]
Thanks for the suggestions, added test, PTAL, thanks.

**Review by jonahwilliams — APPROVED** [review]
LGTM!

**Pull request merged**
