### PR TITLE
Update re-thrown error for incompatible Java/Gradle versions to include migration guide

### PR DESCRIPTION
**Pull request by camsim99**
Updates error message concerning incompatible Java/Gradle versions to reference migration guide that will be created in https://github.com/flutter/website/pull/8501.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by mariamhas — APPROVED** [review]

**Comment by gmackall** [comment]
This LGTM if we are of the opinion that the info should only be on the migration guide. 

I do somewhat think that there is value to leaving the existing steps, and then providing the link as a "for more info, see:" type of link. It can be a nicer experience to just see the answer, instead of having to copy a link and open it in a browser. But also understand if we want all the info in one place, instead of multiple.

**Review by gmackall — APPROVED** [review]

**Comment by camsim99** [comment]
> This LGTM if we are of the opinion that the info should only be on the migration guide.
> 
> I do somewhat think that there is value to leaving the existing steps, and then providing the link as a "for more info, see:" type of link. It can be a nicer experience to just see the answer, instead of having to copy a link and open it in a browser. But also understand if we want all the info in one place, instead of multiple.

I thought the same thing, but didn't want to be redundant. The current steps are definitely more vague than the guide, and the guide should include the information I had before. Deferring to @mariamhas and @reidbaker

**Comment by mariamhas** [comment]
> 

Gray you make a valid point on making it easier for developers, but if the steps are robust enough or complete they might confuse the developer and end up making things more difficult. I think its better to keep the instructions in one place as source of truth for when we eventually have to update them again, itll be easier to do it in one place than several.

**Comment by gmackall** [comment]
> > 
> 
> Gray you make a valid point on making it easier for developers, but if the steps are not robust enough or complete they might confuse the developer and end up making things more difficult. I think its better to keep the instructions in one place as source of truth for when we eventually have to update them again, itll be easier to do it in one place than several.

Sure, that makes sense! This LGTM then

**Review by reidbaker — APPROVED** [review]

**Pull request merged**
