### PR TITLE
[gen-l10n] Fixes named and positional parameter issue with NumberFormat when type is specified

### LINKED ISSUE #67217: Incorrect Translation Generation when type is specified (l10n)
In flutter v1.22,  a new way of using localization was introduced, i have been using it since tomorrow, was working fine but when i tried to use the conversion / placeholders as described inside the i18n guide (link is given in the blog post related to new update).

here is my pubspc.yaml file.
```
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl:

flutter:
  generate: true
```

the latest version of intl package is 0.16.1

I was trying to use the locale based currency / number formatting but the code generation seems to have a bug.

here's a piece of code from one of the `.arb` files

```
{
  "price": "${price} SAR",
  "@price": {
    "placeholders": {
      "price": {
        "type": "int",
        "format": "decimalPattern"
      }
    }
  }
}
```

Now have a look at the output files generated from the above `.arb` code

```
@override
String price(int price) {
  final intl.NumberFormat priceNumberFormat = intl.NumberFormat.decimalPattern(
    locale: localeName,
      
  );
  final String priceString = priceNumberFormat.format(price);

  return '\$${priceString} SAR';
}
```
This is the place where the problem begins.

I just looked at the declaration of `NumberFormat.decimalPattern` inside `intl` package,
```
NumberFormat.decimalPattern([String locale])
      : this._forPattern(locale, (x) => x.DECIMAL_PATTERN);
```
`locale` is declared as an optional parameter but the generator is considering it as a named parameter.

You can follow same steps to regenerate this error.

### PR DESCRIPTION
**Pull request by shihaohong**
## Description

cc/ @ArishSultan, this is a change originally written by him, and I'm just helping push it forward due to unforeseen rebasing/merging issues. Thank you!! :) 

.arb file:
```json
{
  "price": "${price} SAR",
  "@price": {
    "placeholders": {
      "price": {
        "type": "int",
        "format": "decimalPattern"
      }
    }
  }
}
```

Used to incorrectly generate:
```dart
@override
String price(int price) {
  final intl.NumberFormat priceNumberFormat = intl.NumberFormat.decimalPattern(
    locale: localeName, // named parameter generated incorrectly
  );
  final String priceString = priceNumberFormat.format(price);

  return '\$${priceString} SAR';
}
```

This PR fixes the problem by instead generating:
```dart
@override
String price(int price) {
  final intl.NumberFormat priceNumberFormat = intl.NumberFormat.decimalPattern(
    localeName, // positional parameter
  );
  final String priceString = priceNumberFormat.format(price);

  return '\$${priceString} SAR';
}
```

## Issues

Continues https://github.com/flutter/flutter/pull/75056, which ran into merge/rebase issues.

Fixes #67217

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by shihaohong** [comment]
@ArishSultan you'll need to consent to the CLA to be able to merge this PR by leaving a comment saying `@googlebot I consent.` Thanks!

**Comment by ArishSultan** [comment]
@googlebot I consent.

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by shihaohong** [comment]
Thanks again for the change @ArishSultan

**Pull request merged**
