### PR TITLE
Fix flutter web app not respecting assets path when in non-root folder

### LINKED ISSUE #68449: [flutter_tools][web] PWA ServiceWorker breaks on GitHub Pages (rootPath rewrite issue with url-params?)
## Steps to Reproduce

1. Run `flutter create flutter-pwa-bug`
2. Create a GitHub repo and push the project to it
3. Create a `gh-pages` empty branch and push to GitHub repo
4. Configure the GitHub repo to use the `gh-pages` branch as the GitHub Pages root for the repo
5. Update the BASE tag's `href` attribute in `{project-root}/web/index.html` to be `/{gh-repo-name}/`
6. In the flutter-pwa-bug project, run `flutter build --release`
7. Push the contents of `{project-root}/build/web/` to the `gh-pages` branch
8. Open the GitHub Pages URL in Chrome browser

I've made a repository to demonstrate this issue here: https://github.com/JELaVallee/hello-flutter-pwa
With the deployment of such here: https://jelavallee.github.io/hello-flutter-pwa

**Expected results:** 

1. In the Chrome browser, the web site loads and the application is functional
2. In the Chrome browser's location field the "+" icon is displayed
3. Clicking the "+" icon opens the "Install app?" popup dialog and allows you to install the PWA to your computer

**Actual results:** 

1. The page loads and the application functions as expected
2. The "+" icon is _not_ displayed in the browser's location field
3. In the Chrome Developer Tools, Console pane, there is the error: "Uncaught (in promise) TypeError: Request failed ... flutter_service_worker.js?v={cache-buster}"
4. In the Chrome Developer Tools, Network pane, there is a 404 error for the request: "https://<user>.github.io/?revision={app-cache-buster}" which is thrown by the `flutter_service_worker.js` when it's loading the app-cache.

**Triage Notes**

While working to narrow down this issue, I've made the following observations:

1. Hard-coding of "/" as one of the app-cache keys here: [web.dart:Line 438](https://github.com/flutter/flutter/blob/345188d40e576ffb6c97fee60446af58b8c9965a/packages/flutter_tools/lib/src/build_system/targets/web.dart#L438)
    1. In a site deployment like GitHub Pages (w/o a CNAME binding, of course) this absolute root path isn't what we want
    1. This cannot be easily over-ridden and isn't respecting the BASE:href attribute in the `index.html`
    1. I've been able to hack this to work in the generated `flutter_service_worker.js` as seen in [this commit](https://github.com/JELaVallee/hello-flutter-pwa/commit/5f8695bdd0982b7877100098dda1bf916f3715f3) which is not currently deployed...
1. The "fetch" call in `flutter_service_worker.js` (generated in [web.dart:Line 633](https://github.com/flutter/flutter/blob/345188d40e576ffb6c97fee60446af58b8c9965a/packages/flutter_tools/lib/src/build_system/targets/web.dart#L633) is throwing errors which yields the "Uncaught (in promise) TypeError" documented above on the 404.
1. ~GitHub Pages does not rewrite the rootPath URL to "index.html" when the URL has params applied to it.~
    1. ~When tested on a GitHub Pages site with a bound CNAME record, the request to "https://{domain}/?revision={app-cache-buster}" the server still returns a 404 error response.~ (EDIT: This was a bad test on my part, GitHub Pages handles these rewrites properly...)

Suggesting that we either make "/" key in observation-1 be parsed from the BASE:href in the coded `{project-root}/web/index.html` _or_ making the cache loading/checking code in the generated `flutter_service_worker.js` a bit more defensive when handling response errors vs. just throwing them up-stack.

Having one heck of a time properly testing this in the web_test harness.  Going to look at a `flutter_service_worker.js` error handling fix first since it seems less "intrusive", but thinking that a fix for observation-1 would be ideal.

Possibly related to #50580 or #52901

<details>
  <summary>Logs</summary>

```
$ flutter build web --release --verbose
[ +125 ms] executing: [/home/jelavallee/workspace/sandbox/flutter/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +62 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 4fa4f91d5cc65a5a98c7ccd91bb7d47814048a57
[        ] executing: [/home/jelavallee/workspace/sandbox/flutter/flutter/] git tag --points-at HEAD
[  +30 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.23.0-13.0.pre
[  +17 ms] executing: [/home/jelavallee/workspace/sandbox/flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/home/jelavallee/workspace/sandbox/flutter/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +160 ms] executing: [/home/jelavallee/workspace/sandbox/flutter/flutter/] git rev-parse --abbrev-ref HEAD
[  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[ +174 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +113 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +233 ms] Generating
/home/jelavallee/workspace/sandbox/hello-flutter-pwa/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +129 ms] Generating
/home/jelavallee/workspace/sandbox/hello-flutter-pwa/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[   +5 ms] Compiling lib/main.dart for the Web...
[   +4 ms] Initializing file store
[   +7 ms] Done initializing file store
[ +106 ms] Skipping target: gen_localizations
[  +66 ms] Skipping target: web_entrypoint
[ +569 ms] Skipping target: dart2js
[  +48 ms] web_release_bundle: Starting due to {InvalidatedReason.outputMissing}
[ +168 ms] web_release_bundle: Complete
[ +100 ms] web_service_worker: Starting due to {InvalidatedReason.inputChanged, InvalidatedReason.outputMissing}
[  +80 ms] web_service_worker: Complete
[  +10 ms] Persisting file store
[  +15 ms] Done persisting file store
[  +57 ms] Compiling lib/main.dart for the Web... (completed in 1.2s)
[   +2 ms] "flutter web" took 1,757ms.
[ +112 ms] ensureAnalyticsSent: 108ms
[  +62 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0
```

```
 $ flutter analyze
Analyzing hello-flutter-pwa...                                          
No issues found! (ran in 2.4s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel dev, 1.23.0-13.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.23.0-13.0.pre at /home/jelavallee/workspace/sandbox/flutter/flutter
    • Framework revision 4fa4f91d5c (12 days ago), 2020-10-06 12:31:25 -0700
    • Engine revision 443cd5a1e1
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/jelavallee/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/jelavallee/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.50.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • nami (mobile)    • emulator-5554 • android-x64    • Android 9 (API 28)
    • Web Server (web) • web-server    • web-javascript • Flutter Tools
    • Chrome (web)     • chrome        • web-javascript • Chromium 83.0.4103.116 built on Debian 10.4, running on Debian 10.6
```

</details>

### PR DESCRIPTION
**Pull request by nicolasvac**
This pull request aims to fix #68449.
This bug is blocking the incremental integration of every flutter web-app in subdirectories for existing systems.
And also, because this bug makes every flutter web-app search in the root domain path for assets, it only allows for one flutter web-app to co-exists even if in different projects / directories.

*List which issues are fixed by this PR. You must list at least one issue.*
- Fixes #68449 

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by nicolasvac** [comment]
I'm not sure where to look for writing a test or even how to, so if the PR reviewer could guide me that would help a lot.

**Review by mdebbar — COMMENTED** [review]
Thanks for tackling this issue!

This looks good to me but I would like to have @yjbanov take a look too.

**Comment by yjbanov** [comment]
The change itself LGTM. Is there a way to write a test that would make sure we don't break it in the future?

**Comment by yjbanov** [comment]
Maybe something like this? https://github.com/flutter/flutter/blob/master/dev/bots/service_worker_test.dart

**Comment by nicolasvac** [comment]
@yjbanov i think a test that checks if the '/' is present at the beginning of the file names is sufficient ?

**Review by yjbanov — APPROVED** [review]
Nah, let's just remove this line. For the deployment scenarios that we formally support and already have tests for this line is unnecessary. However, it's worth fixing for other environments, even if we don't have a proper setup for replicating them in our tests. So I think a no-test exception is reasonable in this case.

lgtm

**Comment by yjbanov** [comment]
Of course, since we don't have a test environment that replicates Github pages or similar, there's no guarantee that we won't break this again in the future. We won't break it on purpose though.

**Review by ditman — APPROVED** [review]
Hm, webworkers should be scoped to the directory from where they're served, so this "/" should mean: "/baseDir/" and not the root directory of the domain itself.

See Parameters > options > scope: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register#parameters

Let's try this, but I think that if we remove this, we're breaking the offline mode for the "root" of the webapp.

Also, the restriction above can be removed by the server via a header, so maybe this is a matter of the serviceworker being misconfigured?: 

> _"Servers can remove this restriction by setting a `Service-Worker-Allowed` header on the service worker script, and then you can specify a max scope for that service worker above the service worker's location."_

**Comment by ditman** [comment]
(Just checked in the original issue, and the headers are *not* overriding service worker scopes, odd)

**Comment by yjbanov** [comment]
For some reason I thought `index.html` was not served from the service worker in offline mode (or any mode), but maybe I'm wrong.

**Comment by yjbanov** [comment]
Well, _our_ service worker [does fetch it](https://github.com/flutter/flutter/blob/fdf8627c951186a0637e1057f3678d4deb0fc603/dev/bots/service_worker_test.dart#L139), but maybe that's unnecessary? We [don't really support offline mode very easily right now](https://github.com/flutter/flutter/issues/60069), so all this may be a little moot.

**Comment by ditman** [comment]
(I think this can be merged, but it'll need revisiting when solving the issue you linked for sure @yjbanov)

**Comment by christopherfujino** [comment]
@nicolasvac looks like there's a type error that the `Linux web_long_running_tests_1_5` CI step is catching:

```
Unhandled exception:
type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<Object, Object>' of 'other'
#0      MapMixin.addAll (dart:collection/maps.dart)
#1      addStateInfo (package:matcher/src/util.dart:29:14)
#2      _DeepMatcher.matches (package:matcher/src/equals_matcher.dart:261:5)
#3      expect (file:///b/s/w/ir/x/w/flutter/dev/bots/service_worker_test.dart:61:15)
#4      runWebServiceWorkerTest.expectRequestCounts (file:///b/s/w/ir/x/w/flutter/dev/bots/service_worker_test.dart:76:5)
#5      runWebServiceWorkerTest (file:///b/s/w/ir/x/w/flutter/dev/bots/service_worker_test.dart:137:5)
<asynchronous suspension>
#6      _runShardRunnerIndexOfTotalSubshard (file:///b/s/w/ir/x/w/flutter/dev/bots/test.dart:1931:5)
<asynchronous suspension>
#7      _runWebLongRunningTests (file:///b/s/w/ir/x/w/flutter/dev/bots/test.dart:1115:3)
<asynchronous suspension>
#8      _runFromList (file:///b/s/w/ir/x/w/flutter/dev/bots/test.dart:1973:5)
<asynchronous suspension>
#9      main (file:///b/s/w/ir/x/w/flutter/dev/bots/test.dart:200:5)
<asynchronous suspension>
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8824686530296893649/+/u/run_test.dart_for_web_long_running_tests_shard_and_subshard_1_5/test_stderr

**Comment by christopherfujino** [comment]
> @christopherfujino how is this affected by removing the first element of the list, considering it's still a list ?

I didn't actually look at your PR before. Now that I did...I have no idea

**Comment by christopherfujino** [comment]
I scheduled a re-run of `Linux web_long_running_tests_1_5`. If that also fails, I would suggest rebasing upstream, in case this was something that has already been fixed in master.

**Comment by nicolasvac** [comment]
@christopherfujino merged commits

**Comment by christopherfujino** [comment]
I'm stumped on this failure, gonna ask about it on the tests channel of our discord server.

**Comment by christopherfujino** [comment]
Ok, narrowed it down to an bug in the test file: https://github.com/flutter/flutter/issues/99522. I will submit a patch to fix.

**Comment by christopherfujino** [comment]
Fix is in https://github.com/flutter/flutter/pull/99524

**Comment by christopherfujino** [comment]
> Fix is in #99524

Fix has been merged, @nicolasvac please rebase upstream. The test will still fail because you need to update an expectation, but the failure should tell you how to fix it.

**Comment by nicolasvac** [comment]
@christopherfujino i've remerged everything and waited for the tests to run,
`
[CHROME STDERR]:Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[CHROME STDERR]:
`

Still this is not related to this merge request. I hope this can be merged now as it has been over two months for "outside" problems

**Comment by christopherfujino** [comment]
> @christopherfujino i've remerged everything and waited for the tests to run, `[CHROME STDERR]:Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank" [CHROME STDERR]:`
> 
> Still this is not related to this merge request. I hope this can be merged now as it has been over two months for "outside" problems

Per the Flutter team's [Tree Hygiene](https://github.com/flutter/flutter/wiki/Tree-hygiene#tldr) policy this change cannot be merged with failing tests.

The customer_testing-linux test will be fixed by rebasing (not merging) upstream. As for the web test infrastructure failure, I am not familiar with that. I would recommend joining the discord #hackers-infra channel and following up there (alternatively you can file an issue for it).

**Comment by nicolasvac** [comment]
@mdebbar do you have a list of commands i can run ?

I'm not familiar with rebasing from another repository

**Comment by mdebbar** [comment]
@nicolasvac can you show me what you are naming your remotes? (output of `git remote -v`)

**Comment by nicolasvac** [comment]
```
origin  git@github.com:nicolasvac/flutter.git (fetch)
origin  git@github.com:nicolasvac/flutter.git (push)
```

**Comment by mdebbar** [comment]
Ok, first thing you need to add the flutter upstream remote:
```
git remote add upstream git@github.flutter/flutter.git
```

Then, you need to fetch the `master` branch from `upstream`:
```
git fetch upstream master
```

Next, move your local `master` branch to point to your latest commit (excluding the merge commits). That would be the `Update web.dart` commit (sha: `419783e`). The first step here is to make sure to point your HEAD somewhere else:
```
git checkout upstream/master
git branch -f master 419783e
```

Now, let's rebase your local `master` on top of `upstream:master`. The number 3 is the number of commits in your branch that will be rebased:
```
git rebase --onto upstream/master master~3 master
```

**Comment by nicolasvac** [comment]
@mdebbar git gave me some errors and i think it got messed up.

If you want i can just open another PR and re-create the branch

**Comment by nicolasvac** [comment]
@mdebbar i think i've managed to solve it.

Is it ok now ?

**Review by mdebbar — APPROVED** [review]
Looks good now! Thanks for cleaning it up.

Let's wait for the tests to pass and then merge the PR.

**Comment by nicolasvac** [comment]
@mdebbar @christopherfujino All right, thank you both for your patience and assistance.

**Comment by christopherfujino** [comment]
> @mdebbar @christopherfujino All right, thank you both for your patience and assistance.

You never fixed the test: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8820046930680517745/+/u/run_test.dart_for_web_long_running_tests_shard_and_subshard_1_5/test_stderr

```
Unhandled exception:
has different length and is missing map key ''
#0      expect (file:///b/s/w/ir/x/w/flutter/dev/bots/service_worker_test.dart:67:3)
#1      runWebServiceWorkerTest.expectRequestCounts (file:///b/s/w/ir/x/w/flutter/dev/bots/service_worker_test.dart:77:5)
#2      runWebServiceWorkerTest (file:///b/s/w/ir/x/w/flutter/dev/bots/service_worker_test.dart:138:5)
<asynchronous suspension>
#3      _runShardRunnerIndexOfTotalSubshard (file:///b/s/w/ir/x/w/flutter/dev/bots/test.dart:1931:5)
<asynchronous suspension>
#4      _runWebLongRunningTests (file:///b/s/w/ir/x/w/flutter/dev/bots/test.dart:1115:3)
<asynchronous suspension>
#5      _runFromList (file:///b/s/w/ir/x/w/flutter/dev/bots/test.dart:1973:5)
<asynchronous suspension>
#6      main (file:///b/s/w/ir/x/w/flutter/dev/bots/test.dart:199:5)
<asynchronous suspension>
```

**Comment by nicolasvac** [comment]
@christopherfujino seems ok now

**Pull request merged**
