### PR TITLE
PointerDownEvent and PointerMoveEvent default `buttons` to 1

### PR DESCRIPTION
**Pull request by dkwingsmt**
## Description
- The unnamed constructors of `PointerDownEvent` and `PointerMoveEvent` now default `buttons` to `kPrimaryButton` (`1`), instead of `0`.
- Documentation improvement.

## Reasoning
- It is technically wrong for `PointerDownEvent` and `PointerMoveEvent` to have `buttons = 0`, which means their instances that are created out of the box are illegal.
- `kPrimaryButton` is a good default value because it's valid in most cases for all devices.
- Flutter has hundreds of instances of these 2 classes created in test files. If we don't change this, we'll have to change all of them (see https://github.com/flutter/flutter/pull/30408 as an alternative solution). In future PRs gesture recognizers will reject events with `buttons = 0`.

## Related Issues

- Tracking https://github.com/flutter/flutter/issues/30734
- Alternative solution: https://github.com/flutter/flutter/pull/30408

## Tests

No tests are related.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?
- [x] Yes, this is a breaking change, it was proposed at https://groups.google.com/forum/#!topic/flutter-announce/M6J8oX1A17g and tracked at https://github.com/flutter/flutter/issues/30734

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by dkwingsmt** [comment]
No objections have been raised by Apr 12th. Will try to commit.

**Comment by Hixie** [comment]
Maybe add one test that checks the default value, so that people think twice before changing the default back.

**Comment by dkwingsmt** [comment]
@Hixie I've added the said tests

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
