### PR TITLE
Breaking script when inside a folder with spaces

### PR DESCRIPTION
**Pull request by Panthro**

### CODE REVIEW

**Comment by Panthro** [comment]
PR following resolution for #14884

**Comment by tvolkert** [comment]
Thanks for the contribution!  Please sign the contribute license agreement so we can accept it 🙂

**Comment by Panthro** [comment]
@tvolkert already signed it some hours ago, is it normal to take that much?

**Comment by tvolkert** [comment]
Nope - must have just needed to be kicked 😄 

I'll let @cbracken or @goderbauer review and merge

**Comment by goderbauer** [comment]
This doesn't look correct to me. In fact, when I do this and run `flutter doctor` after removing all previous artifacts with `git clean -xfd` I am getting the following error:
```
Exists failed, path = '"C:\src\flutter\.pub-cache"\hosted\pub.dartlang.org\archive-1.0.33' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds...
```

As you can see, there are quotes in that path that do not belong there.

**Comment by goderbauer** [comment]
I am also curious: This code path only becomes active when you have a `.pub-cache` directory inside your `flutter` folder. How did you end up with such a directory in there?

**Comment by Panthro** [comment]
@goderbauer It might have been the case that I was with an already broken install after several attempts.

I honestly don't remember if I did cleanup or not the git repo before rerunning, but as you can see in the #14884 I was down the rabbit hole trying to fix the scripts to make it work in my environment (corporate machine with lots of blocked things).

I'm sure at home it would have worked in the first trial :sweat_smile:

**Comment by Panthro** [comment]
btw, i realized I made a PR to `master` when I was trying the `beta` branch actually.

**Comment by tvolkert** [comment]
> btw, i realized I made a PR to master when I was trying the beta branch actually.

You did it right - we merge all changes into master, and rather than patching changes into branches, we just cut new branches off master.  See https://github.com/flutter/flutter/wiki/Release-process for more details.

**Comment by Hixie** [comment]
Based on @goderbauer's comment above I'm going to close this PR; please don't hesitate to reopen or file a new one if I am wrong in doing so.

**Comment by Panthro** [comment]
That's ok, I guess I had another issue here that somehow this fixed but I
can't reproduce.

**Pull request closed without merging**
