### PR TITLE
SegmentedButton should not create new MaterialStatesController in every build.

### PR DESCRIPTION
**Pull request by polina-c**

### CODE REVIEW

**Review by chunhtai — APPROVED** [review]
LGTM, fyi @HansMuller

**Comment by polina-c** [comment]
> Shouldn't we be trying to dispose controllers for segments that no longer exist?

Yes, this may great next improvement for the code. I am not familiar with code enough to implement it. Can you create it?

**Comment by HansMuller** [comment]
Unfortunately this PR prevents a source of unnecessary allocations but creates a leak (https://github.com/flutter/flutter/pull/133949#issuecomment-1706951935). I suppose what needs to be done is to diff the old and new lists of segments in a https://api.flutter.dev/flutter/widgets/State/didUpdateWidget.html override and dispose the discarded segments.

**Comment by polina-c** [comment]
> Unfortunately this PR prevents a source of unnecessary allocations but creates a leak ([#133949 (comment)](https://github.com/flutter/flutter/pull/133949#issuecomment-1706951935)). I suppose what needs to be done is to diff the old and new lists of segments in a https://api.flutter.dev/flutter/widgets/State/didUpdateWidget.html override and dispose the discarded segments.

Thanks. I will prepare update: https://github.com/flutter/flutter/issues/134061

**Comment by polina-c** [comment]
Fix: https://github.com/flutter/flutter/pull/134064

**Pull request merged**
