### PR TITLE
[feat] Implement `iconType` property for `NavigationRail`

### LINKED ISSUE #134944: NavigationRail should have a iconType attribute so that only the selected or none of the icons are displayed
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

NavigationRail doesn't have `iconType` only `labelType`

### Expected results

add iconType to NavigationRail

### Actual results

no iconType to NavigationRail

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

### PR DESCRIPTION
**Pull request by opxdelwin**
Include new property `iconType` for `NavigationRail` where you could only  show icons when selected, never or always. 

Since few combinations aren't feasible along with `labeltype`, assertions has been put to place to ensure nothing breaks while runtime. 
As assertions are implemented, it'd be best not to change both these parameters while runtime to ensure stability, or put appropriate restrictions on user facing screen.
Here are the following combinations:
```
All Icon + All Label,
All Icon + Selected Label,
All Icon + No Label,
Selected Icon + All Label,
Selected Icon + Selected Label (restricted),
Selected Icon + No Label (restricted),
No Icon + All Label,
No Icon + Selected Label (restricted),
No Icon + No Label (restricted),
```

Fix #134944 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All new tests are passing.
- [x] All existing tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by opxdelwin** [comment]
@Piinks Please do review, I'll take care of the checks and tests in a few days.

**Review by Piinks — COMMENTED** [review]
Hi @opxdelwin thanks for contributing!

I am not sure this is a change we should make. Typically this would be something implemented as a MaterialStateProperty so it could respond to different states such as whether or not it is selected.  

I see it follows a similar pattern to `NavigationRailLabelType`, which also would probably benefit from using MaterialStateProperties instead of enums - @HansMuller what do you think?

This is also missing tests and is failing CI currently. Can you take a look?

**Comment by Piinks** [comment]
Hey @opxdelwin we haven't heard back from you, would you like to continue with this change?

**Comment by opxdelwin** [comment]
@Piinks Sorry for the delay, should've informed you earlier, I'm engaged till 19 Dec. Will it be fine if I work on this once I'm back?

Sorry for leaving this hanging.

**Comment by Piinks** [comment]
No worries at all. You are always welcome to come back to it! I'll follow up after the 19th

**Comment by opxdelwin** [comment]
@Piinks Tests are in! 👍 

Let's stick with this setup for now and consider transitioning to `MaterialStateProperties` in future updates. Thoughts?

**Review by Piinks — COMMENTED** [review]
Thanks for the update!

> Let's stick with this setup for now and consider transitioning to MaterialStateProperties in future updates.

That would mean we would have to make a breaking change here later. Breaking changes are hard on developers, and we try to avoid them as much as possible. Why not use MaterialStateProperty now?

**Comment by Piinks** [comment]
@opxdelwin would you like to continue working on this change?

**Comment by Piinks** [comment]
No worries @opxdelwin, thanks for letting us know. I'll close this PR for now, and we will leave the issue open so someone else could work on it. Thanks for contributing!

**Pull request closed without merging**
