### PR TITLE
Navigator change

### PR DESCRIPTION
**Pull request by nturgut**
Sending route changes via popRoute and pushRoute methods in SystemChannels.navigation. These messages will be used in flutter_web to detect the route

## Description

In order to upstream WebOnlyNavigatorObserver in flutter web we would like to it's functionality with SystemChannel messages. There will also be another change which will alter: https://github.com/flutter/flutter_web/blob/master/packages/flutter_web_ui/lib/src/engine/window.dart#L101 to parse the new route and also deletes:
https://github.com/flutter/flutter_web/blob/master/packages/flutter_web/lib/src/widgets/web_navigator.dart altogether.

## Related Issues

https://github.com/flutter/flutter/issues/34272

## Tests

I added the following tests:

- unit tests for navigator.dart

*Replace this with a list of the tests that you added as part of this PR. A change in behaviour with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by nturgut** [comment]
@yjbanov I accidentally closed the other PR (https://github.com/flutter/flutter/pull/35543) which has approvals. 

Can you please have a look at this one?

Thanks!

**Review by yjbanov — APPROVED** [review]
Please make sure all tests pass. Otherwise, LGTM.

**Comment by Piinks** [comment]
It looks like there are some failing tests here, I've re-triggered them to check for flakes.

**Comment by goderbauer** [comment]
(PR triage): @nturgut  can you take a look while the tests are still failing?

**Comment by nturgut** [comment]
@goderbauer  @Piinks the tests are failing due to an issue on the code. The system channel message being sent is not being consumed in Android/IOS. I'll change the code and I'll make it web only.

Thanks for rerunning the tests!

**Pull request closed without merging**
