### PR TITLE
Reland "Re-enable the Dart Development Service (DDS) (#64671)"

### PR DESCRIPTION
**Pull request by bkonyi**
iOS device lab bots were failing since the MDNS code was relying on `hostVmServicePort` being null to actually forward the device port, causing DDS to attempt to connect to `http://localhost:0`. When DDS is enabled, `hostVmServicePort` is set to 0 to represent that the VM service should be forwarded to any port.

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
could you add some unit test coverage for the mdns change, or something that would have otherwise caught that error on presubmit?

**Comment by bkonyi** [comment]
> could you add some unit test coverage for the mdns change, or something that would have otherwise caught that error on presubmit?

Sure, let me take a look. Shouldn't be an issue.

**Comment by bkonyi** [comment]
> could you add some unit test coverage for the mdns change, or something that would have otherwise caught that error on presubmit?

Done.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
