### PR TITLE
Run flutter test on appveyor (Windows)

### PR DESCRIPTION
**Pull request by goderbauer**
Should be possible now that https://github.com/flutter/flutter/issues/8516 is closed.

/cc @bkonyi

### CODE REVIEW

**Comment by goderbauer** [comment]
Closing in favor of @bkonyi's PR.

**Comment by tvolkert** [comment]
Isn't this still relevant?  `dev/bots/test.dart` still disables running unit tests on Windows...

**Comment by tvolkert** [comment]
Scratch that - just saw the Right PR 😄

**Comment by goderbauer** [comment]
I talked to @bkonyi offline and he wanted to enable all the tests in his PR, so I am dropping this one for now.

**Pull request closed without merging**
