### PR TITLE
Do not delete output directory during flutter build ios-framework

### PR DESCRIPTION
**Pull request by jmagman**
## Description

Don't delete the output directory since they might pass in something they don't want to delete... like their existing app directory or their Desktop or something else.

Delete the build mode directory to clean removed plugins.

### CODE REVIEW

**Comment by xster** [comment]
This changes the 'API' of the command though. I suspect we can just not delete the directory since we only pass this path to xcrun etc

**Comment by jmagman** [comment]
> This changes the 'API' of the command though. I suspect we can just not delete the directory since we only pass this path to xcrun etc

Don't we want to start over though?  if you run just --debug, change something, and then --profile do you want both directories?  or some stale --profile you accidentally ran once awhile ago?

**Comment by jmagman** [comment]
> > This changes the 'API' of the command though. I suspect we can just not delete the directory since we only pass this path to xcrun etc
> 
> Don't we want to start over though? if you run just --debug, change something, and then --profile do you want both directories? or some stale --profile you accidentally ran once awhile ago?

Eh you're right I'm overthinking it.  Let's at least delete the build mode directory so there aren't any leftover plugin frameworks if they get removed.

**Comment by xster** [comment]
> Don't we want to start over though? if you run just --debug, change something, and then --profile do you want both directories? or some stale --profile you accidentally ran once awhile ago?

Isn't that what Xcode does too (with or without a specified output directory)? I don't think Xcode deletes anything unless you run clean.

**Comment by xster** [comment]
LGTM

**Pull request merged**
