### PR TITLE
Revert file naming convention of .aar files to support fuzzy matching in build.gradle

### LINKED ISSUE #108000: [tool][add-2-app]  Debug and Profile modules are generated when passing `--no-debug` and `--no-profile` flags
On the master channel `flutter build aar --no-debug --no-profile` will result in also creating modules for debug and profile.

## Steps to Reproduce

1. flutter checkout master
2. flutter create -t module module_test
3. flutter build aar --no-debug --no-profile

**Expected results:** 
On stable the following files are created:
```
build/host/outputs/repo/com/example/
└── module_test
    └── flutter_release
        ├── 1.0
        │   ├── flutter_release-1.0.aar
        │   ├── flutter_release-1.0.aar.md5
        │   ├── flutter_release-1.0.aar.sha1
        │   ├── flutter_release-1.0.pom
        │   ├── flutter_release-1.0.pom.md5
        │   └── flutter_release-1.0.pom.sha1
        ├── maven-metadata.xml
        ├── maven-metadata.xml.md5
        └── maven-metadata.xml.sha1
```

**Actual results:** 
On master these files are created:
```
build/host/outputs/repo/com/example/
└── module_test
    ├── flutter
    │   ├── 1.0
    │   │   ├── flutter-1.0-debug.aar
    │   │   ├── flutter-1.0-debug.aar.md5
    │   │   ├── flutter-1.0-debug.aar.sha1
    │   │   ├── flutter-1.0-debug.aar.sha256
    │   │   ├── flutter-1.0-debug.aar.sha512
    │   │   ├── flutter-1.0-profile.aar
    │   │   ├── flutter-1.0-profile.aar.md5
    │   │   ├── flutter-1.0-profile.aar.sha1
    │   │   ├── flutter-1.0-profile.aar.sha256
    │   │   ├── flutter-1.0-profile.aar.sha512
    │   │   ├── flutter-1.0-release.aar
    │   │   ├── flutter-1.0-release.aar.md5
    │   │   ├── flutter-1.0-release.aar.sha1
    │   │   ├── flutter-1.0-release.aar.sha256
    │   │   ├── flutter-1.0-release.aar.sha512
    │   │   ├── flutter-1.0.module
    │   │   ├── flutter-1.0.module.md5
    │   │   ├── flutter-1.0.module.sha1
    │   │   ├── flutter-1.0.module.sha256
    │   │   ├── flutter-1.0.module.sha512
    │   │   ├── flutter-1.0.pom
    │   │   ├── flutter-1.0.pom.md5
    │   │   ├── flutter-1.0.pom.sha1
    │   │   ├── flutter-1.0.pom.sha256
    │   │   └── flutter-1.0.pom.sha512
    │   ├── maven-metadata.xml
    │   ├── maven-metadata.xml.md5
    │   ├── maven-metadata.xml.sha1
    │   ├── maven-metadata.xml.sha256
    │   └── maven-metadata.xml.sha512
    ├── flutter_debug
    │   ├── 1.0
    │   │   ├── flutter_debug-1.0.aar
    │   │   ├── flutter_debug-1.0.aar.md5
    │   │   ├── flutter_debug-1.0.aar.sha1
    │   │   ├── flutter_debug-1.0.aar.sha256
    │   │   ├── flutter_debug-1.0.aar.sha512
    │   │   ├── flutter_debug-1.0.module
    │   │   ├── flutter_debug-1.0.module.md5
    │   │   ├── flutter_debug-1.0.module.sha1
    │   │   ├── flutter_debug-1.0.module.sha256
    │   │   ├── flutter_debug-1.0.module.sha512
    │   │   ├── flutter_debug-1.0.pom
    │   │   ├── flutter_debug-1.0.pom.md5
    │   │   ├── flutter_debug-1.0.pom.sha1
    │   │   ├── flutter_debug-1.0.pom.sha256
    │   │   └── flutter_debug-1.0.pom.sha512
    │   ├── maven-metadata.xml
    │   ├── maven-metadata.xml.md5
    │   ├── maven-metadata.xml.sha1
    │   ├── maven-metadata.xml.sha256
    │   └── maven-metadata.xml.sha512
    ├── flutter_profile
    │   ├── 1.0
    │   │   ├── flutter_profile-1.0.aar
    │   │   ├── flutter_profile-1.0.aar.md5
    │   │   ├── flutter_profile-1.0.aar.sha1
    │   │   ├── flutter_profile-1.0.aar.sha256
    │   │   ├── flutter_profile-1.0.aar.sha512
    │   │   ├── flutter_profile-1.0.module
    │   │   ├── flutter_profile-1.0.module.md5
    │   │   ├── flutter_profile-1.0.module.sha1
    │   │   ├── flutter_profile-1.0.module.sha256
    │   │   ├── flutter_profile-1.0.module.sha512
    │   │   ├── flutter_profile-1.0.pom
    │   │   ├── flutter_profile-1.0.pom.md5
    │   │   ├── flutter_profile-1.0.pom.sha1
    │   │   ├── flutter_profile-1.0.pom.sha256
    │   │   └── flutter_profile-1.0.pom.sha512
    │   ├── maven-metadata.xml
    │   ├── maven-metadata.xml.md5
    │   ├── maven-metadata.xml.sha1
    │   ├── maven-metadata.xml.sha256
    │   └── maven-metadata.xml.sha512
    └── flutter_release
        ├── 1.0
        │   ├── flutter_release-1.0.aar
        │   ├── flutter_release-1.0.aar.md5
        │   ├── flutter_release-1.0.aar.sha1
        │   ├── flutter_release-1.0.aar.sha256
        │   ├── flutter_release-1.0.aar.sha512
        │   ├── flutter_release-1.0.module
        │   ├── flutter_release-1.0.module.md5
        │   ├── flutter_release-1.0.module.sha1
        │   ├── flutter_release-1.0.module.sha256
        │   ├── flutter_release-1.0.module.sha512
        │   ├── flutter_release-1.0.pom
        │   ├── flutter_release-1.0.pom.md5
        │   ├── flutter_release-1.0.pom.sha1
        │   ├── flutter_release-1.0.pom.sha256
        │   └── flutter_release-1.0.pom.sha512
        ├── maven-metadata.xml
        ├── maven-metadata.xml.md5
        ├── maven-metadata.xml.sha1
        ├── maven-metadata.xml.sha256
        └── maven-metadata.xml.sha512
```

### LINKED ISSUE #111643: Revert file naming convention of `.aar` files to support fuzzy matching in `build.gradle`
Q1:On the master channel flutter build aar --no-debug --no-profile will result in also creating modules for debug and profile.
see: https://github.com/flutter/flutter/issues/108000

Q2:the dependencies version format does not work on 3.1.0~3.3.2

### Steps to Reproduce:
1.flutter checkout master
2.flutter create -t module module_test
3.flutter build aar --no-debug --no-profile --build-number 1.0.0

### Expected results:
On stable the following files are created: on 3.0.5

<details>
<summary>Logs</summary>

```
build/host/outputs/repo/com/example/
└── module_test
    └── flutter_release
        ├── 1.0
        │   ├── flutter_release-1.0.aar
        │   ├── flutter_release-1.0.aar.md5
        │   ├── flutter_release-1.0.aar.sha1
        │   ├── flutter_release-1.0.pom
        │   ├── flutter_release-1.0.pom.md5
        │   └── flutter_release-1.0.pom.sha1
        ├── maven-metadata.xml
        ├── maven-metadata.xml.md5
        └── maven-metadata.xml.sha1


implementation 'com.example.module_test:flutter_release:1.0.0'
```

</details>

### Actual results:

On master these files are created:  on 3.1.0~3.3.2

<details>
<summary>Logs</summary>

```
build/host/outputs/repo/com/example/
└── module_test
    ├── flutter
    │   ├── 1.0
    │   │   ├── flutter-1.0-debug.aar
    │   │   ├── flutter-1.0-debug.aar.md5
    │   │   ├── flutter-1.0-debug.aar.sha1
    │   │   ├── flutter-1.0-debug.aar.sha256
    │   │   ├── flutter-1.0-debug.aar.sha512
    │   │   ├── flutter-1.0-profile.aar
    │   │   ├── flutter-1.0-profile.aar.md5
    │   │   ├── flutter-1.0-profile.aar.sha1
    │   │   ├── flutter-1.0-profile.aar.sha256
    │   │   ├── flutter-1.0-profile.aar.sha512
    │   │   ├── flutter-1.0-release.aar
    │   │   ├── flutter-1.0-release.aar.md5
    │   │   ├── flutter-1.0-release.aar.sha1
    │   │   ├── flutter-1.0-release.aar.sha256
    │   │   ├── flutter-1.0-release.aar.sha512
    │   │   ├── flutter-1.0.module
    │   │   ├── flutter-1.0.module.md5
    │   │   ├── flutter-1.0.module.sha1
    │   │   ├── flutter-1.0.module.sha256
    │   │   ├── flutter-1.0.module.sha512
    │   │   ├── flutter-1.0.pom
    │   │   ├── flutter-1.0.pom.md5
    │   │   ├── flutter-1.0.pom.sha1
    │   │   ├── flutter-1.0.pom.sha256
    │   │   └── flutter-1.0.pom.sha512
    │   ├── maven-metadata.xml
    │   ├── maven-metadata.xml.md5
    │   ├── maven-metadata.xml.sha1
    │   ├── maven-metadata.xml.sha256
    │   └── maven-metadata.xml.sha512
    ├── flutter_debug
    │   ├── 1.0
    │   │   ├── flutter_debug-1.0.aar
    │   │   ├── flutter_debug-1.0.aar.md5
    │   │   ├── flutter_debug-1.0.aar.sha1
    │   │   ├── flutter_debug-1.0.aar.sha256
    │   │   ├── flutter_debug-1.0.aar.sha512
    │   │   ├── flutter_debug-1.0.module
    │   │   ├── flutter_debug-1.0.module.md5
    │   │   ├── flutter_debug-1.0.module.sha1
    │   │   ├── flutter_debug-1.0.module.sha256
    │   │   ├── flutter_debug-1.0.module.sha512
    │   │   ├── flutter_debug-1.0.pom
    │   │   ├── flutter_debug-1.0.pom.md5
    │   │   ├── flutter_debug-1.0.pom.sha1
    │   │   ├── flutter_debug-1.0.pom.sha256
    │   │   └── flutter_debug-1.0.pom.sha512
    │   ├── maven-metadata.xml
    │   ├── maven-metadata.xml.md5
    │   ├── maven-metadata.xml.sha1
    │   ├── maven-metadata.xml.sha256
    │   └── maven-metadata.xml.sha512
    ├── flutter_profile
    │   ├── 1.0
    │   │   ├── flutter_profile-1.0.aar
    │   │   ├── flutter_profile-1.0.aar.md5
    │   │   ├── flutter_profile-1.0.aar.sha1
    │   │   ├── flutter_profile-1.0.aar.sha256
    │   │   ├── flutter_profile-1.0.aar.sha512
    │   │   ├── flutter_profile-1.0.module
    │   │   ├── flutter_profile-1.0.module.md5
    │   │   ├── flutter_profile-1.0.module.sha1
    │   │   ├── flutter_profile-1.0.module.sha256
    │   │   ├── flutter_profile-1.0.module.sha512
    │   │   ├── flutter_profile-1.0.pom
    │   │   ├── flutter_profile-1.0.pom.md5
    │   │   ├── flutter_profile-1.0.pom.sha1
    │   │   ├── flutter_profile-1.0.pom.sha256
    │   │   └── flutter_profile-1.0.pom.sha512
    │   ├── maven-metadata.xml
    │   ├── maven-metadata.xml.md5
    │   ├── maven-metadata.xml.sha1
    │   ├── maven-metadata.xml.sha256
    │   └── maven-metadata.xml.sha512
    └── flutter_release
        ├── 1.0
        │   ├── flutter_release-1.0.aar
        │   ├── flutter_release-1.0.aar.md5
        │   ├── flutter_release-1.0.aar.sha1
        │   ├── flutter_release-1.0.aar.sha256
        │   ├── flutter_release-1.0.aar.sha512
        │   ├── flutter_release-1.0.module
        │   ├── flutter_release-1.0.module.md5
        │   ├── flutter_release-1.0.module.sha1
        │   ├── flutter_release-1.0.module.sha256
        │   ├── flutter_release-1.0.module.sha512
        │   ├── flutter_release-1.0.pom
        │   ├── flutter_release-1.0.pom.md5
        │   ├── flutter_release-1.0.pom.sha1
        │   ├── flutter_release-1.0.pom.sha256
        │   └── flutter_release-1.0.pom.sha512
        ├── maven-metadata.xml
        ├── maven-metadata.xml.md5
        ├── maven-metadata.xml.sha1
        ├── maven-metadata.xml.sha256
        └── maven-metadata.xml.sha512


implementation 'com.example.module_test:flutter:1.0.0:release'
```

</details>

The following methods will not work
```
implementation 'com.example.module_test:flutter:1.0.+:release'
implementation 'com.example.module_test:flutter:1.+:release'
implementation 'com.example.module_test:flutter:1.0.0-SNAPSHOT:release'
```

I want the implementation to support fuzzy matching. for example:
```
implementation 'com.example.module_test:flutter_release:1.0.+'
implementation 'com.example.module_test:flutter_release:1.+'
implementation 'com.example.module_test:flutter_release:1.0.0-SNAPSHOT'
```

### PR DESCRIPTION
**Pull request by JunhuaLin**
Revert file naming convention of .aar files to support fuzzy matching in build.gradle on using maven-publish

Fix https://github.com/flutter/flutter/issues/111643 
Fix https://github.com/flutter/flutter/issues/108000

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by JunhuaLin** [comment]
build result:
image

image

**Comment by JunhuaLin** [comment]
image

**Comment by Jasguerrero** [comment]
Could you take a look? @GaryQian

**Comment by JunhuaLin** [comment]
Could you take a look? @GaryQian

**Review by GaryQian — COMMENTED** [review]
This PR seems to be missing some of the testing code removed in the original PR. Can you make sure this PR fully reverts the original PR? Tests that have comments "mimic the AGP plugin" seem to be missing. Things like the JDK bump can stay unless it causes incompatibility issues. This way we have more guarantees we are not introducing new bugs.

**Comment by JunhuaLin** [comment]
> This PR seems to be missing some of the testing code removed in the original PR. Can you make sure this PR fully reverts the original PR? Tests that have comments "mimic the AGP plugin" seem to be missing. Things like the JDK bump can stay unless it causes incompatibility issues. This way we have more guarantees we are not introducing new bugs.

This PR modifies the use of Maven-Publish to produce the correct AAR based on https://github.com/flutter/flutter/pull/101276

The Maven-Publish introduction has been tested in https://github.com/flutter/flutter/pull/101276

This PR ensures that the code is correct without having to adjust the Maven-Publish-related test code

**Comment by JunhuaLin** [comment]
> This PR seems to be missing some of the testing code removed in the original PR. Can you make sure this PR fully reverts the original PR? Tests that have comments "mimic the AGP plugin" seem to be missing. Things like the JDK bump can stay unless it causes incompatibility issues. This way we have more guarantees we are not introducing new bugs.

The JDK version configuration in the CI file is not concerned, the latest flutter:master branch has been adjusted

**Review by GaryQian — APPROVED** [review]

**Comment by JunhuaLin** [comment]
@GaryQian 
When can this PR be merged to the master branch？

**Comment by GaryQian** [comment]
This still needs one more review to be landable! I've tagged a few others.

**Comment by JunhuaLin** [comment]
> auto label is removed for flutter/flutter, pr: 112149, due to Validations Fail.



> 



> This still needs one more review to be landable! I've tagged a few others.

There seems to be a need for approving comments LGTM

**Comment by JunhuaLin** [comment]
Could you take a look? @christopherfujino

**Comment by JunhuaLin** [comment]
Hope to deal with as soon as possible, affect the upgrade to the latest version！
We don't want to stay at 3.0.5 for too long！
This problem is holding up the build flutter.

**Review by christopherfujino — APPROVED** [review]
RSLGTM

**Comment by christopherfujino** [comment]
@JunhuaLin it looks like you have a test failure, however:

```
02:08 +13 -1: test\integration.shard\gradle_non_android_plugin_test.dart: Flutter app that depends on a non-Android plugin can still build for Android [E]
  Expected: a file system entity that exists
    Actual: LocalFile:<LocalFile: 'C:\b\s\w\ir\x\t\flutter_flutter_plugin_test.5951ddc1\ios_only\example\build\app\outputs\apk\release\app-release.apk'>
     Which: does not exist
  
  package:test_api                                                 expect
  test\integration.shard\gradle_non_android_plugin_test.dart 90:5  main.<fn>
  dart:async                                                       runZoned
  test\src\common.dart 197:14                                      testWithoutContext.<fn>
  test\src\common.dart 166:18                                      test.<fn>
```

**Comment by JunhuaLin** [comment]
> @JunhuaLin it looks like you have a test failure, however:
> 
> ```
> 02:08 +13 -1: test\integration.shard\gradle_non_android_plugin_test.dart: Flutter app that depends on a non-Android plugin can still build for Android [E]
>   Expected: a file system entity that exists
>     Actual: LocalFile:<LocalFile: 'C:\b\s\w\ir\x\t\flutter_flutter_plugin_test.5951ddc1\ios_only\example\build\app\outputs\apk\release\app-release.apk'>
>      Which: does not exist
>   
>   package:test_api                                                 expect
>   test\integration.shard\gradle_non_android_plugin_test.dart 90:5  main.<fn>
>   dart:async                                                       runZoned
>   test\src\common.dart 197:14                                      testWithoutContext.<fn>
>   test\src\common.dart 166:18                                      test.<fn>
> ```

This test failure has nothing to do with my PR
Let me merge ther flutter:master code again

**Comment by JunhuaLin** [comment]
image

Should I not merge the master code？
Should I just keep my commit？

**Comment by JunhuaLin** [comment]
Now，it‘s fine~
@christopherfujino @GaryQian

**Comment by AesSedai101** [comment]
this change is going to cause add to app modules with multiple native dependencies to fail because of how gradle 7 does dependency resolution. Please test that case as well

**Comment by JunhuaLin** [comment]
> this change is going to cause add to app modules with multiple native dependencies to fail because of how gradle 7 does dependency resolution. Please test that case as well

### Can you give a detailed description demo？

## OR

### Does this mean that there are multiple flutter plugin dependencies?
this case：it's ok

### module dependency
```
app --> module_test --> flutterboost
                 |
                  --> shared_preferences_android
```
### file tree:
```
└── host
    └── outputs
        └── repo
            ├── com
            │   ├── example
            │   │   └── module_test
            │   │       └── flutter_release
            │   │           ├── 1.0.0
            │   │           │   ├── flutter_release-1.0.0.aar
            │   │           │   ├── flutter_release-1.0.0.aar.md5
            │   │           │   ├── flutter_release-1.0.0.aar.sha1
            │   │           │   ├── flutter_release-1.0.0.aar.sha256
            │   │           │   ├── flutter_release-1.0.0.aar.sha512
            │   │           │   ├── flutter_release-1.0.0.module
            │   │           │   ├── flutter_release-1.0.0.module.md5
            │   │           │   ├── flutter_release-1.0.0.module.sha1
            │   │           │   ├── flutter_release-1.0.0.module.sha256
            │   │           │   ├── flutter_release-1.0.0.module.sha512
            │   │           │   ├── flutter_release-1.0.0.pom
            │   │           │   ├── flutter_release-1.0.0.pom.md5
            │   │           │   ├── flutter_release-1.0.0.pom.sha1
            │   │           │   ├── flutter_release-1.0.0.pom.sha256
            │   │           │   └── flutter_release-1.0.0.pom.sha512
            │   │           ├── maven-metadata.xml
            │   │           ├── maven-metadata.xml.md5
            │   │           ├── maven-metadata.xml.sha1
            │   │           ├── maven-metadata.xml.sha256
            │   │           └── maven-metadata.xml.sha512
            │   └── idlefish
            │       └── flutterboost
            │           └── flutter_boost_release
            │               ├── 1.0.0
            │               │   ├── flutter_boost_release-1.0.0.aar
            │               │   ├── flutter_boost_release-1.0.0.aar.md5
            │               │   ├── flutter_boost_release-1.0.0.aar.sha1
            │               │   ├── flutter_boost_release-1.0.0.aar.sha256
            │               │   ├── flutter_boost_release-1.0.0.aar.sha512
            │               │   ├── flutter_boost_release-1.0.0.module
            │               │   ├── flutter_boost_release-1.0.0.module.md5
            │               │   ├── flutter_boost_release-1.0.0.module.sha1
            │               │   ├── flutter_boost_release-1.0.0.module.sha256
            │               │   ├── flutter_boost_release-1.0.0.module.sha512
            │               │   ├── flutter_boost_release-1.0.0.pom
            │               │   ├── flutter_boost_release-1.0.0.pom.md5
            │               │   ├── flutter_boost_release-1.0.0.pom.sha1
            │               │   ├── flutter_boost_release-1.0.0.pom.sha256
            │               │   └── flutter_boost_release-1.0.0.pom.sha512
            │               ├── maven-metadata.xml
            │               ├── maven-metadata.xml.md5
            │               ├── maven-metadata.xml.sha1
            │               ├── maven-metadata.xml.sha256
            │               └── maven-metadata.xml.sha512
            └── io
                └── flutter
                    └── plugins
                        └── sharedpreferences
                            └── shared_preferences_android_release
                                ├── 1.0.0
                                │   ├── shared_preferences_android_release-1.0.0.aar
                                │   ├── shared_preferences_android_release-1.0.0.aar.md5
                                │   ├── shared_preferences_android_release-1.0.0.aar.sha1
                                │   ├── shared_preferences_android_release-1.0.0.aar.sha256
                                │   ├── shared_preferences_android_release-1.0.0.aar.sha512
                                │   ├── shared_preferences_android_release-1.0.0.module
                                │   ├── shared_preferences_android_release-1.0.0.module.md5
                                │   ├── shared_preferences_android_release-1.0.0.module.sha1
                                │   ├── shared_preferences_android_release-1.0.0.module.sha256
                                │   ├── shared_preferences_android_release-1.0.0.module.sha512
                                │   ├── shared_preferences_android_release-1.0.0.pom
                                │   ├── shared_preferences_android_release-1.0.0.pom.md5
                                │   ├── shared_preferences_android_release-1.0.0.pom.sha1
                                │   ├── shared_preferences_android_release-1.0.0.pom.sha256
                                │   └── shared_preferences_android_release-1.0.0.pom.sha512
                                ├── maven-metadata.xml
                                ├── maven-metadata.xml.md5
                                ├── maven-metadata.xml.sha1
                                ├── maven-metadata.xml.sha256
                                └── maven-metadata.xml.sha512

```
### pom dependencies:

module_test pom file:
```
<project ...>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example.module_test</groupId>
  <artifactId>flutter_release</artifactId>
  <version>1.0.0</version>
  <packaging>aar</packaging>

  <dependencies>
    <dependency>
      <groupId>io.flutter</groupId>
      <artifactId>flutter_embedding_release</artifactId>
      <version>1.0.0-4b591e17d288447f118300754073c9f1d9a4393a</version>
      <scope>compile</scope>
    </dependency>
  
 ......

    <dependency>
      <groupId>io.flutter.plugins.sharedpreferences</groupId>
      <artifactId>shared_preferences_android_release</artifactId>
      <version>1.0.0</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>com.idlefish.flutterboost</groupId>
      <artifactId>flutter_boost_release</artifactId>
      <version>1.0.0</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

flutterboost pom file:
```
<project ...>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.idlefish.flutterboost</groupId>
  <artifactId>flutter_boost_release</artifactId>
  <version>1.0.0</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>io.flutter</groupId>
      <artifactId>flutter_embedding_release</artifactId>
      <version>1.0.0-4b591e17d288447f118300754073c9f1d9a4393a</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

shared_preferences_android pom file:

```
<project ...>
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.flutter.plugins.sharedpreferences</groupId>
  <artifactId>shared_preferences_android_release</artifactId>
  <version>1.0.0</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>io.flutter</groupId>
      <artifactId>flutter_embedding_release</artifactId>
      <version>1.0.0-4b591e17d288447f118300754073c9f1d9a4393a</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>

```

**Comment by AesSedai101** [comment]
If you have your add to app project depending on another plugin with a native dependency (in your case, flutterboost depending on shared_preferences) via the pubspec, the dependencies in the POM uses the new classifier mechanism. 

For example., in my main add to app module, I use [logging_to_logcat](https://pub.dev/packages/logging_to_logcat), which gets included like this:

```
<dependency>
      <groupId>com.logger.logging_to_logcat</groupId>
      <artifactId>logging_to_logcat</artifactId>
      <version>1.0.0</version>
      <scope>compile</scope>
    </dependency>
``` 

with the `-debug` and `-release` classifiers mapping to the flavours

**Comment by JunhuaLin** [comment]
> If you have your add to app project depending on another plugin with a native dependency (in your case, flutterboost depending on shared_preferences) via the pubspec, the dependencies in the POM uses the new classifier mechanism.
> 
> For example., in my main add to app module, I use [logging_to_logcat](https://pub.dev/packages/logging_to_logcat), which gets included like this:
> 
> ```
>    <dependency>
>       <groupId>com.logger.logging_to_logcat</groupId>
>       <artifactId>logging_to_logcat</artifactId>
>       <version>1.0.0</version>
>       <scope>compile</scope>
>     </dependency>
> ```
> 
> with the `-debug` and `-release` classifiers mapping to the flavours.
> 
> so, if you don't publish the artifacts in the new way with the classifiers, you will need to declare all Flutter dependencies with a native component manually in the gradle file of your native project.


### I created the following dependency structure：

```
app --> module_test --> flutterboost
                             |
                              --> shared_preferences_android
```

### flutterboost depending on logging_to_logcat
image

.flutter-plugins-dependencies file:Plugin dependent plugins also compile normally，look this:
image

### build aar file tree:
```
└── host
    └── outputs
        └── repo
            └── com
                ├── example
                │   └── module_test
                │       └── flutter_release
                │           ├── 1.0
                │           │   ├── flutter_release-1.0.aar
                │           │   ├── flutter_release-1.0.aar.md5
                │           │   ├── flutter_release-1.0.aar.sha1
                │           │   ├── flutter_release-1.0.pom
                │           │   ├── flutter_release-1.0.pom.md5
                │           │   └── flutter_release-1.0.pom.sha1
                │           ├── maven-metadata.xml
                │           ├── maven-metadata.xml.md5
                │           └── maven-metadata.xml.sha1
                ├── idlefish
                │   └── flutterboost
                │       └── flutter_boost_release
                │           ├── 1.0
                │           │   ├── flutter_boost_release-1.0.aar
                │           │   ├── flutter_boost_release-1.0.aar.md5
                │           │   ├── flutter_boost_release-1.0.aar.sha1
                │           │   ├── flutter_boost_release-1.0.pom
                │           │   ├── flutter_boost_release-1.0.pom.md5
                │           │   └── flutter_boost_release-1.0.pom.sha1
                │           ├── maven-metadata.xml
                │           ├── maven-metadata.xml.md5
                │           └── maven-metadata.xml.sha1
                └── logger
                    └── logging_to_logcat
                        └── logging_to_logcat_release
                            ├── 1.0
                            │   ├── logging_to_logcat_release-1.0.aar
                            │   ├── logging_to_logcat_release-1.0.aar.md5
                            │   ├── logging_to_logcat_release-1.0.aar.sha1
                            │   ├── logging_to_logcat_release-1.0.pom
                            │   ├── logging_to_logcat_release-1.0.pom.md5
                            │   └── logging_to_logcat_release-1.0.pom.sha1
                            ├── maven-metadata.xml
                            ├── maven-metadata.xml.md5
                            └── maven-metadata.xml.sha1

```
### flutterboost pom file:
```
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.idlefish.flutterboost</groupId>
  <artifactId>flutter_boost_release</artifactId>
  <version>1.0</version>
  <packaging>aar</packaging>
  <dependencies>

    <dependency>
      <groupId>com.logger.logging_to_logcat</groupId>
      <artifactId>logging_to_logcat_release</artifactId>
      <version>1.0</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>io.flutter</groupId>
      <artifactId>flutter_embedding_release</artifactId>
      <version>1.0.0-d3ea636dc5d16b56819f3266241e1f708979c233</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

**Comment by GaryQian** [comment]
@AesSedai101 Can you confirm that @JunhuaLin 's explanation here resolves your concern?

**Comment by JunhuaLin** [comment]
image


Why did the test fail？

**Comment by GaryQian** [comment]
Yes, you should use rebase, but don't worry about the tree being broken, it is not your fault, it should become green again soon (it is green now). That check simply reflects the build status of tip-of-tree.

**Comment by JunhuaLin** [comment]
> Yes, you should use rebase, but don't worry about the tree being broken, it is not your fault, it should become green again soon (it is green now). That check simply reflects the build status of tip-of-tree.

Ok, I see~
When can this PR be merged to the master branch？
We want to use the latest version as soon as possible

**Comment by AesSedai101** [comment]
> Can you confirm that @JunhuaLin 's explanation here resolves your concern?

That is not the behaviour I saw on my side, but it's possible that my environment is in a broken state

**Comment by JunhuaLin** [comment]
> > Can you confirm that @JunhuaLin 's explanation here resolves your concern?
> 
> That is not the behaviour I saw on my side, but it's possible that my environment is in a broken state

I'm not sure I understand your situation. 
My changes are consistent with 3.0.5 and earlier features for build aar，so there should be no negative effect！

You can use [my branch master](https://github.com/JunhuaLin/flutter) version to verify your problem
or：
Can you provide a complete minimum reproducible code example ？

**Comment by JunhuaLin** [comment]
Submitting a PR is too hard！-_-||

**Comment by GaryQian** [comment]
@AesSedai101 Ping on @JunhuaLin 's questions

**Comment by JunhuaLin** [comment]
Can my PR be released with 3.4.0 @GaryQian

**Pull request merged**
