### PR TITLE
Improve checkbox animation

### LINKED ISSUE #1614: Selection controls feedback
- [x] I believe the animation for checkboxes generally transitions to the checked color (yellow, in this case) before filling the square/check mark. Feels a bit strange to have it fill with grey and then turn yellow at the very end.
- [x] The touch targets, at least on the checkboxes, feel a bit small (could just be mind playing tricks, though)

### PR DESCRIPTION
**Pull request by abarth**
This patch improves the checkbox animation as suggested by the design
team. The color transition now occurs earlier in the animation and there
are fewer components to the animation.

Fixes #1614

### CODE REVIEW

**Comment by abarth** [comment]
@HansMuller @Hixie

**Comment by Hixie** [comment]
The code looks fine, but i can't visualise what the animation is from it. I'll take your word for it that it's improved. :-)

Can you think of a way we could test this? Maybe with a mock PaintingContext and manually driving the paint function?

LGTM.

**Comment by abarth** [comment]
> Can you think of a way we could test this? Maybe with a mock PaintingContext and manually driving the paint function?

That's one option.  The issue is more trying to zero in on what the designers want the animation to look like.  The previous animation was fine for what it was, they just asked for it to look a bit different.

**Comment by abarth** [comment]
> The code looks fine, but i can't visualise what the animation is from it.

Basically, you've got a DRRect that shrinks slightly in size until the halfway mark and then regrows to the original size.  During the first half of the animation, the center of the DDRect collapses to nothing, leaving a solid RRect.  The color fades from grey to the active color (e.g., yellow) over the first 25% of the animation.  At the halfway mark, we're at minimum size with a solid RRect and the white checkmark begins to form as the RRect returns to its original size.

**Pull request merged**
