### PR TITLE
Formally deprecate VirtualViewport

### PR DESCRIPTION
**Pull request by abarth**
This mechanism has been replaced by slivers.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @HansMuller

**Comment by abarth** [comment]
@Hixie @HansMuller

**Comment by HansMuller** [comment]
LGTM. This change may warrant an explanatory note to the flutter mailing list.

**Comment by abarth** [comment]
Yes, I have it half-written in my drafts folder.  I'll finish it up and send it off.

**Pull request merged**
