### PR TITLE
DO NOT COMMIT

### PR DESCRIPTION
**Pull request by Hixie**
test to see if this test is actually used

### CODE REVIEW

**Comment by Hixie** [comment]
Maybe it's used by devicelab? cc @dnfield

**Comment by dnfield** [comment]
I can't find anywhere obvious that it's used. It might just be used in devicelab, but I'm having trouble finding where if it actually is.

In my roll PR I've moved this to a dev_dependency, since it's only used in a test file. I also removed the other instance, since it's not used at all there anymore.

**Comment by Hixie** [comment]
If the test just isn't running, let's delete it. The cost of this test is probably greater than it's value.

**Comment by Hixie** [comment]
->https://github.com/flutter/flutter/pull/74763

**Pull request closed without merging**
