### PR TITLE
Unskip a widget inspector test that doesn't seem flaky anymore.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
See https://github.com/flutter/flutter/issues/29108 for history.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
I want to run these tests a few more times before landing.

**Comment by Hixie** [comment]
For the record, "Google testing" failed, but it was unrelated to this test. Still running the tests more times to see if it flakes.

**Comment by Hixie** [comment]
Ok well I haven't been able to get this to fail, so I guess it's no longer flaky.

**Pull request merged**
