### PR TITLE
Report total_ui_gc_time to SkiaPerf

### PR DESCRIPTION
**Pull request by zanderso**
Not sure why this wasn't already being reported.

### CODE REVIEW

**Review by flar — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
IIRC anything running integration_test instead of flutter_driver wont report this

**Comment by zanderso** [comment]
> IIRC anything running integration_test instead of flutter_driver wont report this

Changed to exclude for 'e2e' tests.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
