### PR TITLE
Reland "Switch flutter_tools to run frontend server from AOT snapshot"

### PR DESCRIPTION
**Pull request by derekxu16**
This reverts commit a1639be.

### CODE REVIEW

**Comment by christopherfujino** [comment]
@derekxu16 for posterity, was there an internal CL that landed that resolves the issue that lead to the previous GitHub being reverted?

**Comment by derekxu16** [comment]
Yeah, cl/569577574 and cl/569558141.

**Comment by christopherfujino** [comment]
> Yeah, cl/569577574 and cl/569558141.

Ahh cool, so the former has merged already and the latter is a g3fix. LGTM

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
FYI @Jasguerrero who I believe is rolling this week.

**Comment by Jasguerrero** [comment]
> FYI @Jasguerrero who I believe is rolling this week.

cc @XilaiZhang

**Pull request merged**
