### PR TITLE
Move global analysis options file to the repo root

### PR DESCRIPTION
**Pull request by krisgiesing**
Also restore the analysis options file for stocks example, since
the global options trigger warnings on generated intl files.

### CODE REVIEW

**Comment by krisgiesing** [comment]
@Hixie @devoncarew

**Comment by devoncarew** [comment]
It looks like having a local `.analysys_options` file ignores this global one - the settings are replaced, not merged - @pq.

Can you delete the settings file in `examples/material_gallery/`? I don't believe that's used anymore, and removing it will let the options flow into that example.

**Comment by pq** [comment]
> It looks like having a local .analysys_options file ignores this global one - the settings are replaced, not merged - @pq.

That's accurate.  No merge.  Straight override.

**Comment by krisgiesing** [comment]
Removed the options file for Material Gallery example.

**Comment by devoncarew** [comment]
lgtm

**Pull request merged**
