### PR TITLE
Removed required kotlin dependency

### PR DESCRIPTION
**Pull request by andoriyaprashant**

### CODE REVIEW

**Comment by eliasyishak** [comment]
@andoriyaprashant thank you for contributions! However, as the bot is saying above, you need the sign the CLA before we can start considering these contributions. You can refer to https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md for details

**Comment by andoriyaprashant** [comment]
thank you @eliasyishak for the information

**Comment by christopherfujino** [comment]
@andoriyaprashant what is the motivation for this change? Is there a tracking issue?

**Comment by christopherfujino** [comment]
> @andoriyaprashant what is the motivation for this change? Is there a tracking issue?

Not sure what is going on here, however I am going to close this PR for now. If you still think this is a legitimate change we should make, please start by filing an issue. Thanks!

**Pull request closed without merging**
