### PR TITLE
Teach FlutterPlugin.groovy about AOT builds

### PR DESCRIPTION
**Pull request by abarth**
The `flutter.buildMode` property not controls whether to build in debug,
profiling, or release.

### CODE REVIEW

**Comment by abarth** [comment]
@jason-simmons @chinmaygarde

**Comment by jason-simmons** [comment]
s/not/now/ in the commit message

LGTM

**Comment by tain335** [comment]
Is there a way to debug with FlutterView?

**Comment by abarth** [comment]
Yes, but it's not fully wired up yet.  See https://github.com/flutter/flutter/commit/00c7734c8ba983564be97b5ad8fc2abcc8de65f5 for some progress.

**Comment by tain335** [comment]
Good Jobs!

**Pull request merged**
