### PR TITLE
Reland dispose images when done (#67100)

### LINKED ISSUE #56482: removing Image widgets does not reduce Graphics memory allocation
Internal: b/157467549

If the app was put to background and then resumed, the GPU memory went back down.

not sure what the right approach for this. Changing the widget tree and not seeing an expected memory behavior is hard to explain. Is this a bug? Is it something that should be in documentation?

/cc @cbracken @mehmetf

### PR DESCRIPTION
**Pull request by dnfield**
Fixes https://github.com/flutter/flutter/issues/56482 (again)

Changes since last time:

- Test for CanvasKit image rendering
  (https://github.com/flutter/flutter/pull/67176)
- Fix CanvasKit dispose impl
  (https://github.com/flutter/engine/pull/21555)
- Update internal google3 customer with a problematic ImageStream
  Listener impl (cl/335091311)

This reverts commit 473358d93dd9522970afa82512a4d05685345b3b.

### CODE REVIEW

**Comment by dnfield** [comment]
This will be in draft mode until the relevant CanvasKit change rolls into the framework - I'll rebase this and then it'll be ready for review.

**Comment by goderbauer** [comment]
Is this a 1:1 revert of 473358d or are there any additional changes in here?

**Comment by goderbauer** [comment]
Never mind, I didn't read the PR description carefully.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Engine roll merged in, af ew updates for NNBD in the test, and the internal CL is submitting right now.

**Comment by dnfield** [comment]
Hm. There appears to be a new failure internally I have to check out. Moving this back to draft.

**Comment by dnfield** [comment]
This now needs cl/335459002

**Comment by dnfield** [comment]
(google testing hasn't caught up yet to the CL I just landed, the test will pass now)

**Pull request merged**
