### PR TITLE
Remove unused offset from Layer.addToScene/addChildrenToScene

### PR DESCRIPTION
**Pull request by goderbauer**
I was recently reading this code and tried to figure out when the `childOffset` param to `addChildrenToScene` is ever non-zero to understand what code paths trigger non-retained rendering [1]. Turns out, the offset is always zero. To avoid that confusion in the future and to simplify the code, let's remove the parameter (pending checks passing to verify that it's not breaking anything).

[1] https://github.com/flutter/flutter/blob/528f77dc99e43f3eb20698cb683c25705725ced0/packages/flutter/lib/src/rendering/layer.dart#L1109-L1113

_Update:_ Some historical digging shows that three years ago it was also proposed to eliminate this param, but it was kept **unused** to preserve backwards-compatibility, see https://github.com/flutter/flutter/pull/21619#discussion_r220380344. Since our breaking change policy has evolved since then I think we should remove it if this doesn't turn out to be a breaking change per our latest breaking change policy.

### CODE REVIEW

**Comment by dnfield** [comment]
It is highly unlikely that this will break anyone.

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
SGTM.

**Pull request merged**
