### PR TITLE
Improve flutter tools integration tests

### PR DESCRIPTION
**Pull request by DanTup**
This is the start of tidying up from #18560. See the list of commits for the changes made.

I made a class for a "test project" to better group together the strings for the files we were writing to disk. It can be subclassed so additional data can be provided (for ex. the single existing sample project provides locations to put breakpoints for a build method and top level function, which some of tests using it use). Hopefully this'll make it easier to extend with additional projects as the tests grow (for ex.; I think the hot reload test needs to have a `print` or something we can modify to make it easy to verify we actually did run new code). We may wish to move the strings into real files in a folder at some point (and copy them into the temp dir in setup) to make it easier to modify them in the IDE (eg. code completion, highlighting, etc; editing Dart in a string sucks).

Outstanding:

> Or, have integration tests defining in a class, with setup, test, and teardown methods subclasses can override?

Is there any existing way (or convention) for doing this? I couldn't see anything in the existing tests. Not sure if there's a better way than maintaining a big block of code creating instances of these test classes manually?

> For some (many?) of these skips, we should instead invert the test to expect failure. That means we'll be notifies by the CI when the issue is fixed.

Some of these currently fail with things like timeouts, so this might not work. I'm also slightly nervous about making it so that when someone commits a fix for something, we break the build (which probably would come as part of an engine roll). I don't want to add obstacles to people getting the fix in (though I appreciate we mustn't let these get forgotten about and be forever skipped - but I am happy to re-review each when any of the related issues are resolved - I do get notifications on them).

### CODE REVIEW

**Comment by devoncarew** [comment]
> Some of these currently fail with things like timeouts, so this might not work. I'm also slightly nervous about making it so that when someone commits a fix for something, we break the build

Timeouts seem like a real issue (we'd need to check for them specifically). Breaking the build when a test is fixed seems reasonable - the person will get notified in the PR during review and can fix the test expectation (no now expect to pass). The alternative is for the disabled tests to get stale.

Thanks for the PR! I'll review now.

**Review by devoncarew — APPROVED** [review]
> Or, have integration tests defining in a class, with setup, test, and teardown methods subclasses can override?

> Is there any existing way (or convention) for doing this?

The analyzer and analysis server have this style of test. It's not critical to use this style - just a suggestion for one option. Composition (as with the `BasicProject` class) works too.

**Comment by devoncarew** [comment]
It sounds like you've started on some stepping tests as well. As an example of one test style, the VM's debugger tests use line comments in source to define test expectations: https://github.com/dart-lang/sdk/blob/master/runtime/observatory/tests/service/step_through_function_test.dart.

**Comment by DanTup** [comment]
> It sounds like you've started on some stepping tests as well. As an example of one test style, the VM's debugger tests use line comments in source to define test expectations

That's ver similar to what I did :)

https://github.com/DanTup/flutter/blob/31dfc40d598c0d71ebd787b4b4d09892061865ff/packages/flutter_tools/test/integration/test_data/stepping_project.dart#L37-L41

The source code is annotated with comments about where it expects each step to end up (currently it only checks lines, though I may tweak this to be /* inline */ comments when they're working a bit better (they're slightly annoying to work on while the stepping is broken as they fail on the first assertions).

**Comment by DanTup** [comment]
Looks like all the expression evaluation tests are now passing (!) so I've removed the `skip`s :)

I've updated the Hot Reload tests to have new expectations based on the bugs and added comments about how to address them as bugs are fixed (and included my name so I can be pinged if there are any issues, such as failures for different reasons). I couldn't figure out how to get async tests to test exception text so they're currently checking `throwsA(anything)` - if there's a way to improve this I'll update.

The CIs are currently running on all platforms - if there are any remaining failures once they finish I'll work through them (but hopefully by the time you read this the builds are all green and there are no skips).

**Comment by DanTup** [comment]
I've had to mark the expression evaluation tests as skip on Windows. I tried to refactor them a little so they'll pass because of the issue (https://github.com/flutter/flutter/issues/17833) but they ended up being a huge mess. I tried changing them to not user hot reload, but it turned out I'd mis-remembered that issue, and it's not only hot reload - they fail to even start up.

I'm happy to open an issue and assign it to myself or set a weekly reminder to check on the issue - I don't really want to leave a big blob of messy coed in each test that requires careful editing when the fix lands, as it will just complicate an engine roll and if it's outside of my hours, I don't want to be a hold-up for them.

They'll still run on Linux/Mac and I'll be notified for updates on the related issue. @devoncarew WDYT?

**Comment by DanTup** [comment]
@devoncarew I pushed some changes since you reviewed this (and added a comment about skips), lmk if you're happy for me to land as it is now.

**Comment by DanTup** [comment]
@devoncarew I've rebased this on master again - I landed a change in master that updated the test_driver to the latest version (from across several branches) so this PR is now only the test changes.

(There are still skips on Windows because I'm struggling to make them expect failure without making them really complicated for whoever lands the fix to fix up).

**Review by devoncarew — APPROVED** [review]
lgtm!

**Pull request merged**
