### PR TITLE
[luci] Decommision the coverage shard

### LINKED ISSUE #31615: [LUCI] Decommision the coverage shard for Flutter Framework
Thanks to some great work by @jonahwilliams, test coverage is now only marginally slower than testing without coverage.

We should decomission https://ci.chromium.org/p/flutter/builders/luci.flutter.prod/Linux%20Coverage and just make the `Linux` framework tests run coverage as part of their normal run.  This will free up a bot per commit and get rid of a bot that has poor visibility right now anyway.

/cc @digiter

### PR DESCRIPTION
**Pull request by digiter**
## Description

Per https://github.com/flutter/flutter/issues/31615, we'd like to run coverage along framework tests. 

I will remove the coverage shard from LUCI first to avoid breaking LUCI.

## Related Issues

Fix https://github.com/flutter/flutter/issues/31615

## Tests

N/A

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

How do we upload or merge the coverage data?

**Comment by dnfield** [comment]
Has this already been removed from flutter/infra?

**Comment by digiter** [comment]
This is blocked on https://github.com/flutter/infra/pull/71 that removes the shard from LUCI.

**Comment by digiter** [comment]
> How do we upload or merge the coverage data?
@jonahwilliams The upload is broken at the moment: https://github.com/flutter/flutter/issues/45271

**Comment by Hixie** [comment]
I don't understand the goal of this PR.

We need to run a bunch of tests with and without coverage, to make sure both work.
As far as I can tell we wouldn't want to run most tests with coverage, because that makes them much slower and uses much more RAM.
We need to upload the coverage data from the framework tests, because the longer we run without updates the more out of date anyone using the lcov files will be.

**Comment by digiter** [comment]
Hi Dan, I'm not sure what should be done to this PR. Could you take a look at Ian's comment above and give some suggestions? @dnfield

**Comment by dnfield** [comment]
We still need to run coverage somewhere.

Coverage is fast enough that we could run it anywhere now.  We don't necessarily need a separate shard on Luci for it

**Comment by goderbauer** [comment]
Is this PR still relevant? Should we close it?

**Comment by digiter** [comment]
I have to increase cpu and memory for below tasks in order to make the presubmit run within time limit. Here're run time changes before and after this PR:
- framework_tests-widgets-linux: 21 mins (before) vs 32 mins (after)
- framework_tests-libraries-linux: 17 mins (before) vs 45 mins (after)
- framework_tests-widgets-windows: 25 mins (before) vs 51 mins (after)
- framework_tests-libraries-windows: 20 mins (before) vs 53 mins (after)
- framework_tests-widgets-macos:  22 mins (before) vs 48 mins (after)
- framework_tests-libraries-macos: 22 mins (before) vs 46 mins (after)

Run time increased about 2 times worries me.

**Comment by digiter** [comment]
The increased time doesn't prevent this PR from merging though, because tests on latest commits take about 50 mins on Cirrus.

**Comment by dnfield** [comment]
We should avoid creating presubmits that take longer than 15 minutes on average.

**Comment by digiter** [comment]
Closing this PR as I can't find a good way to make presubmits run within 15 minutes.

**Comment by dnfield** [comment]
Not sure if it's an option, but we could try to just make this a post submit for now that doesn't affect tree status?

**Comment by digiter** [comment]
Do you mean, for example, adding a flag to only enable this in post submit?

**Comment by dnfield** [comment]
Correct, and somehow not have it block the tree - which is basically what the LUCI shard did.

**Pull request closed without merging**
