### PR TITLE
Shell instances launched by the tools from the desktop are always non-interactive.

### LINKED ISSUE #5769: 'flutter test --coverage' hangs on Mac
## Steps to Reproduce

Exact same setup as #5761, but on a Mac machine, rather than Linux.
* Add any test code under `test` directory.
* Run `flutter test --coverage` **on Mac**.

The command hangs with the following console message (added `--verbose` to get more info):
```
youngseokyoon foo (code-coverage)$ flutter test --coverage --verbose
   0 ms • switching to directory Directory: 'test' to run tests
00:00 +0: loading /Users/youngseokyoon/Programming/baku/foo/test/main_test.dart
 113 ms • running test package with arguments: [--concurrency=1, --, /Users/youngseokyoon/Programming/baku/foo/test/main_test.dart]
Shell: 2016-09-07 21:53:32.776 sky_shell[31384:6154423] No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, exiting
```

The same test runs fine without the `--coverage` option.

## Flutter Doctor

```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/youngseokyoon/Programming/flutter
    • Framework revision 6070cd949f (7 weeks ago), engine revision 3291edef41

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.1)
    • Android SDK at /Users/youngseokyoon/Library/Android/sdk
    • Platform android-23, build-tools 23.0.1
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.35
```

### PR DESCRIPTION
**Pull request by chinmaygarde**
(In that they never create a window with an OpenGL context and the works.)

This requires https://github.com/flutter/engine/pull/3011 to land with a roll. Fixes https://github.com/flutter/flutter/issues/5769 after.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @jason-simmons

**Comment by jason-simmons** [comment]
LGTM

**Comment by chinmaygarde** [comment]
The engine patch has landed. Just amended this PR to roll the engine too. Will wait till bots are green.

**Comment by chinmaygarde** [comment]
Bots are green. Landing.

**Pull request merged**
