### PR TITLE
Remove flutter_gallery_mac__start_up as target in .ci.yaml

### LINKED ISSUE #111115: Remove `flutter_gallery_mac__start_up` devicelab test.
`macOS` is missing many device lab tests that are running on `iOS`, `Android`, and `Windows`. Having `flutter_gallery_mac__start_up` and `flutter_gallery_macos__start_up` device lab tests is confusing.

Since we have other tests/benchmarks that can launch an Android app from a mac host, we can just delete `flutter_gallery_mac__start_up`. This will eliminate the confusion once `flutter_gallery_macos__start_up` is landed as a perf test for `macOS`.

### PR DESCRIPTION
**Pull request by a-wallen**
This PR removes `flutter_gallery_mac__start_up` and all references to it. Since we have other tests/benchmarks that can launch an Android app from a mac host, we can just delete flutter_gallery_mac__start_up. This will eliminate the confusion once flutter_gallery_macos__start_up is landed as a perf test for macOS.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
See discussion in https://github.com/flutter/flutter/pull/110379#discussion_r958802680

cc @zanderso 

LGTM

**Review by jmagman — COMMENTED** [review]
Actually, @keyonghan is there still the issue we need to remove the test from the .ci.yaml, let it roll, and then it's safe to delete the test file?

**Comment by keyonghan** [comment]
> Actually, @keyonghan is there still the issue we need to remove the test from the .ci.yaml, let it roll, and then it's safe to delete the test file?

Yeah, we are still having that issue as the ci roller is still in use. As said, we need to remove the target first, and then the files. Otherwise it will cause a short time of tree red if the target is scheduled before the roller lands.

**Comment by a-wallen** [comment]
@keyonghan alright, I dropped the commit that removed the file. I'll follow up in another PR to delete that file.

**Review by jmagman — APPROVED** [review]

**Review by keyonghan — APPROVED** [review]
LGTM

**Comment by a-wallen** [comment]
Opening an issue to track the deletion of the file and mark this as fully completed.

https://github.com/flutter/flutter/issues/111115

**Pull request merged**
