### PR TITLE
Revert "Always activate DevTools if it's not installed"

### PR DESCRIPTION
**Pull request by goderbauer**
Reverts flutter/flutter#81242

The test unskipped by that PR is failing reliably on Windows, see https://github.com/flutter/flutter/issues/81486.

### CODE REVIEW

**Comment by Hixie** [comment]
We can skip that test on windows, but I don't think reverting this PR is the right thing to do. The PR itself isn't introducing anything incorrect as far as we know.

**Comment by goderbauer** [comment]
The PR was adding (or unskipping) a test that's not reliably passing on devicelab. I thought the policy is to do revert first.

But sure, I will prepare a PR that just skips the test on windows.

**Comment by goderbauer** [comment]
Superseded by https://github.com/flutter/flutter/pull/81509.

**Pull request closed without merging**
