### PR TITLE
InputDecorator vertical centering fix

### LINKED ISSUE #86093: Input decoration vertical alignment is broken with `isDense: true`
## Bug

Using a very simple `TextField` setup, the visuals are broken on web, i.e. the text is too high vertically / **not center aligned**.

This means there is a very easily provable **discrepancy** between Flutter web and Flutter for mobile.

### Screenshots

| Mobile (correct) | Web (broken) |
| :----------------: | :--------------: |
| image | image |
| image | image |

### Reproducible sample

This is the exact code I ran on **web** and on **mobile**:

<details><summary>Click to expand snippet</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const Bug());
}

class Bug extends StatelessWidget {
  const Bug({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(32),
            child: DecoratedBox(
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.onSurface.withAlpha(0x1a),
                borderRadius: BorderRadius.circular(8),
              ),
              child: SizedBox(
                height: 44,
                child: TextField(
                  cursorColor: Theme.of(context).accentColor,
                  textAlign: TextAlign.left,
                  textAlignVertical: TextAlignVertical.center,
                  style: Theme.of(context).textTheme.bodyText2,
                  decoration: InputDecoration(
                    border: InputBorder.none,
                    hintText: 'Hint :)',
                    isDense: true,
                    hintStyle: Theme.of(context).textTheme.subtitle2,
                    prefixIcon: const Icon(Icons.search),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

#### Versions

```dart
[✓] Flutter (Channel origin/stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1052], locale en-150)
    • Flutter version 2.2.3
    • Framework revision f4abaa0735 (7 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 91.0.4472.124
```

### PR DESCRIPTION
**Pull request by justinmc**
Fixes https://github.com/flutter/flutter/issues/86093

The text baseline was not considering the fact that the prefix/suffix icons could be bigger than the text content and make the field even bigger.  In those cases, the text baseline should be centered next to the icon.

| Version | Screenshot |
| --- | --- |
| Before | Screenshot from 2023-03-31 16-25-08 |
| After | Screenshot from 2023-03-31 16-24-11 |

### CODE REVIEW

**Comment by bernaferrari** [comment]
Maybe it will also fix this? https://github.com/flutter/flutter/issues/40477

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

**Comment by justinmc** [comment]
There is a legitimate failure from the Google tests.  The case of zero contentPadding and vertically aligning center is broken by the PR.

Screenshot 2023-04-12 at 10 27 08 AM


<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              // TODO(justinmc): This textAlignVertical and the contentPadding
              // below are necessary to reproduce the bug.
              textAlignVertical: TextAlignVertical.center,
              decoration: InputDecoration(
                prefixIcon: Icon(Icons.search),
                contentPadding: EdgeInsets.zero,
                filled: true,
                fillColor: Colors.lime.withOpacity(0.6),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

**Comment by justinmc** [comment]
Unfortunately I don't think I'm going to be able to resolve the inconsistencies here without a major rewrite.  I'm unable to hack something together that passes all the tests while still fixing the bug, and a deeper investigation into the issues yields inconsistencies.  For example, the [docs for textAlignVertical](https://master-api.flutter.dev/flutter/material/InputDecorator/textAlignVertical.html) seem to say that the prefix/suffix should be at the same baseline as the input, but in the code it seems positioned independently.

I think need to strictly define how all of these parameters should behave and make a major breaking change with a rewrite.

**Pull request closed without merging**
