### PR TITLE
fix two null-aware-operator issues

### PR DESCRIPTION
**Pull request by devoncarew**
Two issues, both `The expression uses '?.', so can be 'null'`.

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
These do look like good fixes, but where did you see that message?

**Comment by devoncarew** [comment]
In Atom :), running against the dev sdk.

**Comment by Hixie** [comment]
I don't understand how the message relates to that fix.

**Comment by Hixie** [comment]
I mean, the only reason the original code was wrong is that we don't guarantee that fontWeight is non-null, but we easily could and this function wouldn't change.

**Comment by devoncarew** [comment]
I think that `begin?.fontWeight` will evaluate to null if `begin` is null, so `begin?.fontWeight?.index` would potentially have an npe, even if we guarantee that fontWeight is never null. At least, that's how I read the error message.

**Comment by Hixie** [comment]
Oh interesting. I assumed `foo?.bar.baz` was equivalent to `foo == null ? null : foo.bar.baz`, not `(foo == null ? null : foo.bar).baz`. I wonder if we have this bug anywhere else.

**Pull request merged**
