### PR TITLE
Simplify colorizing icons

### PR DESCRIPTION
**Pull request by abarth**
Now you can colorize an Icon simply by proving a Color for the Icon.

### CODE REVIEW

**Comment by abarth** [comment]
@HansMuller

**Comment by Hixie** [comment]
It would be interesting for theme transitions if IconButton supported this. The difficulty is working out which underlying image to colorize (we have white and black variants).

**Comment by abarth** [comment]
IMHO, we should just get rid of the white variants.  We can just use Colors.white to colorize the black images.

**Comment by HansMuller** [comment]
LGTM

**Pull request merged**
