### PR TITLE
floating action button y-offset respect inset bottom

### PR DESCRIPTION
**Pull request by iskakaushik**
Floating action button should be visible when `Scaffolding.resizeToAvoidBottomInset` is set.

### Current behavior / Repro steps:

1. Center or End docked FAB.
2. Open Keyboard.
3. FAB is only partially visible.

### The configuration this PR specifically addresses:

1. Docked FAB implementations.
2. When`Scaffolding.resizeToAvoidBottomInset` is `true`.
3. When insets exist AND `contentBottom` does not have enough space for the FAB to fully reside below it. E.g. Keyboard is open.

New behavior: 

FAB is completely visible.

### CODE REVIEW

**Comment by HansMuller** [comment]
This has been a bit trying to look into today because of https://github.com/flutter/flutter/issues/26563. Sorry about that.

It would really help if this issue clarified exactly what's required for each of the existing FloatingActionButtonLocations, for Scaffold.resizeToAvoidBottomInset true or false, when the keyboard is up and down, likewise for the snackbar and bottomsheet, and if MediaQueryData.padding implies that there are display notches. These requirements could be expressed as deltas vs the current implementation.

A test case that can be used to demo the various scenarios would help as well. This is the one I was using just now: https://gist.github.com/HansMuller/6218fd11caf2775271abdff2042d5c74

**Comment by iskakaushik** [comment]
@HansMuller per you suggestion, i've created a demo app, and this helped uncover a couple more issues with **FloatingActionButtonLocation** where we were not using the top insets correctly.

I will address these along with the CI failures in the follow up commits. Still thinking about the right way to capture the constraints, we could pass in the deltas but i think we can infer a tighter bounding box using **ScaffoldPrelayoutGeometry** that is more general and can be used by all implementations of **FloatingActionButtonLocation** and we could use that to make things cleaner.

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/pull/22039

**Comment by iskakaushik** [comment]
Hi @HansMuller , any update from the Material Design team on this?

**Comment by iskakaushik** [comment]
@Hixie This should address that case as well.

@HansMuller any update from the material design team on this?

**Comment by dnfield** [comment]
@iskakaushik  - this is out of sync with HEAD now. Do you plan to continue with it?  If so, can you sync it up to HEAD?

**Comment by iskakaushik** [comment]
@dnfield i don't think i can work on this now. will revive it once i have some cycles.

**Pull request closed without merging**
