### PR TITLE
increase touch target area of material text selection handle

### LINKED ISSUE #17618: Selection handle touch target is too small in TextFields.
The Flutter editable text widget (`TextField`) displays a selection handle; however, the touch target is too small. 

This is an accessibility issue, so I'm marking it as blocking for mulligan.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes #17618

### CODE REVIEW

**Comment by jonahwilliams** [comment]
This currently breaks in some odd ways

**Comment by tvolkert** [comment]
@jonahwilliams can we increase the touch target without affecting the visual indicator?

**Comment by jonahwilliams** [comment]
@tvolkert possibly just by adding padding, but I'm also unsure if this change is currently necessary.  TalkBack/VoiceOver don't use the handle - closing for now

**Comment by tvolkert** [comment]
Making the touch target bigger is an accessibility requirement even for users who don't use TalkBack/VoiceOver, no?

**Pull request closed without merging**
