### PR TITLE
bump versions and tools

### PR DESCRIPTION
**Pull request by jonahwilliams**

### CODE REVIEW

**Comment by Hixie** [comment]
lgtm

wow, i don't think i even knew these python scripts still existed

**Comment by jonahwilliams** [comment]
@Hixie do I need to rerun the scrips on each different host platform in order to get the correct versions in the VERSION_X_YDK files?

**Comment by jonahwilliams** [comment]
Closing for now due to buildroot difficulties

**Comment by Hixie** [comment]
I've no idea how these scripts work, off-hand. I can look into it if you want.

**Comment by jonahwilliams** [comment]
script update is fine, It's just that the new android sdks don't work with our buildroot.  I could work on updating our storage location regardless, but I have a lot of other stuff on my plate right now :3

**Pull request closed without merging**
