### PR TITLE
[flutter_tools] Make test asset directory visible on web platform testing

### PR DESCRIPTION
**Pull request by bleroux**
## Description

This PR makes the test assets directory content available to web tests.
The goal of this PR is to unblock https://github.com/flutter/flutter/pull/144314 which activates ink sparkle animation on CanvasKit. The ink sparkle animation relies on a shader.

https://github.com/flutter/flutter/pull/144314 works when launching a flutter app but fails when launching a web test with a 404 error for the `ink_sparkle.frag` file.

## Related Issue

Needed for https://github.com/flutter/flutter/pull/144314.

## Tests

Adds 1 test.

### CODE REVIEW

**Review by jonahwilliams — CHANGES_REQUESTED** [review]
ink_sparkle should be loaded via asset bundles. if the asset bundle is broken, then a fix should be made there, not by adjusting the test harness loading behavior.

**Comment by bleroux** [comment]
@jonahwilliams 
Ink sparkle is correctly loaded when launching an app using 'flutter run -d chrome' (once activated on canvas kit, see the PR linked on the description). That's why I assumed, it was a test only issue.
Can you point me to someone who can work on this? Or give my guidance on where to fix this?

**Comment by jonahwilliams** [comment]
The test assets are built here:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/test.dart#L656-L680

maybe those arguments need to be adjusted for web tests?

**Comment by bleroux** [comment]
> The test assets are built here:
> 
> https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/test.dart#L656-L680
> 
> maybe those arguments need to be adjusted for web tests?

Thanks for pointing out this code.
I figured out that tests assets are correctly generated for web tests (this code is called before launching the internal web server). But the asset directory was not sent to FlutterWebPlatform.
I have updated the PR to make the test assets directory visible on the internal web server (and I added a test).
Let me know it this is the right way or if there was a reason for not exposing this directory?

**Comment by bleroux** [comment]
@christopherfujino
Can you point me to someone who can review this PR?
Based on Jonah feedback I updated this PR some weeks ago.
Thanks!

**Comment by christopherfujino** [comment]
I'm gonna defer to @andrewkolos to make the final review on this one, he's currently out of office but will be back ~1 week.

**Comment by andrewkolos** [comment]
Hello, I'm back and trying to catch up on this. I'm starting out from the same place @jonahwilliams did:

> ink_sparkle should be loaded via [the] asset bundle. if the asset bundle is broken, then a fix should be made there, not by adjusting the test harness loading behavior.

I need to figure out where this shader is being loaded, how it's being loaded, and why it's not working for web tests.

**Comment by bleroux** [comment]
@andrewkolos 
Hey! For context, before Johan review, my first implementation was to add a specifc rule to the Shelf server in order to serve ink_sparkle file.
That's why Johan commented:
> ink_sparkle should be loaded via [the] asset bundle. if the asset bundle is broken, then a fix should be made there, not by adjusting the test harness loading behavior.

Since then I updated the PR to serve the test asset directory which was already correctly built for web tests but whose path was not known by the `FlutterWebPlatform`.

**Comment by bleroux** [comment]
@andrewkolos Did you get a chance to look at this PR?

**Comment by andrewkolos** [comment]
Hello, I got preoccupied with other things, but I have no excuse for not communicating this. My apologies.

> Since then I updated the PR to serve the test asset directory which was already correctly built for web tests but whose path was not known by the FlutterWebPlatform.

If the path was not known by `FlutterWebPlatform`, wouldn't any test that depends on an [asset](https://docs.flutter.dev/ui/assets/assets-and-images) fail when running on a browser? To my knowledge, this is not the case, and I've verified this locally[^1] (assuming I did so correctly). I'm missing something here.

[^1]: I created a simple Flutter app that displays text loaded from an asset file. I wrote an [integration test](https://docs.flutter.dev/testing/integration-tests) that verifies that the text is displayed and I [ran this test on chrome](https://docs.flutter.dev/testing/integration-tests#running-in-a-browser). The test passed.

**Comment by andrewkolos** [comment]
To extend the previous comment: I believe the code that actually loads `ink_sparkle.frag` is unique compared to the more general asset-loading code, but I have to imagine that the file would still be visible on the web server hosted by `flutter test` since it's bundled in the same directory as any other asset file.

**Comment by bleroux** [comment]
@andrewkolos Thanks for your insight. I’m far from having a full understanding of asset loading, shaders and flutter tools inner workings. That makes it hard to draw conclusions on this area.
I will close this PR for the moment and I will try to come up with a narrowed investigation.

For context, here is what led me to this PR:
- In order to fix https://github.com/flutter/flutter/issues/138487, I filled https://github.com/flutter/flutter/pull/144314 which activates the ink sparkle shader animation on CanvasKit. With that PR, the shader works correctly when launching an app using `flutter run` but several tests are failing.
- When I filed it the main cause for test failure was a 404 response while retrieving the `ink_sparkle.frag` shader file, see https://github.com/flutter/flutter/pull/138545#issuecomment-1814639943. That’s why I worked on this flutter tools PR.
- As of today, this work is not enough to get https://github.com/flutter/flutter/pull/144314 passing all tests locally (I think it was when I first filed it). Especially, the problem is not specific to integration test, some widget tests fail because the shader is not loaded. For reference, the loading logic on framework side is:

https://github.com/flutter/flutter/blob/13a05def8305c93b6ac0ddb4486c01d83821218c/packages/flutter/lib/src/material/ink_sparkle.dart#L443-L452


I will try to get a better understanding of how the shader is supposed to be loaded on web tests and I will try to narrow it down to make progress.

**Comment by bleroux** [comment]
Just found https://github.com/flutter/flutter/pull/31207 which is a great starting point to understand how assets are loaded in non-web tests (it mocks flutter/assets channel to bypass the engine).

**Comment by andrewkolos** [comment]
Thanks for the recap!

> I’m far from having a full understanding of asset loading, shaders and flutter tools inner workings. That makes it hard to draw conclusions on this area.

I work on the tool full-time, and I could still say the same 😆. I would have loved to have a deep dive here and figure all of this out, but I unfortunately do not have the time. If you do figure this out or this turns out to be a higher priority than I thought, I'd be glad to look at this again.

**Comment by dvaruas** [comment]
Hello @bleroux I am also facing the same issue where shaders asset is not found in unit tests for flutter app. 
Were you able to find anything more during your investigation? 

@andrewkolos  this really blocks users from using updated Flutter version (since 3.16, and the latest SDK is 3.22). Could the flutter team also take a look into this with priority?

**Comment by bleroux** [comment]
Hello @dvaruas!
I have not work on this issue since my last comment. It would help if you can file an issue with a minimal repro. My work was based on https://github.com/flutter/flutter/issues/138487 which is a specific case (a shader provided by the framework). Having a proper issue with a simple repro based on a Flutter app that loads a shader would be interesting because it extends the scope of this issue.

> this really blocks users from using updated Flutter version (since 3.16, and the latest SDK is 3.22). 

Do you mean that it worked before 3.16? (I'm not sure when shaders support was added to Flutter Web)
For Flutter 3.16 and 3.19, there was another issue related to shaders (https://github.com/flutter/flutter/issues/141296), it was fixed in https://github.com/flutter/engine/pull/49754 which is included in Flutter 3.22.

**Comment by dvaruas** [comment]
Hey @bleroux , thank you for your response. I'll try to create a issue with a minimal example once I isolate it. 

> Do you mean that it worked before 3.16? (I'm not sure when shaders support was added to Flutter Web)
yes, I was using 3.13.9 previously and everything works fine. 
Encountered this issue when I tried to update to 3.16

For now I am removing the --no-test-assets flag to bypass this issue.

**Pull request closed without merging**
