### PR TITLE
Adjust floating label height when font size is larrrrgeee

### LINKED ISSUE #14583: Regression in text field scalable text support
The `TextField` used to work for scaled text sizes, and now the label starts to overlap the text field at about 2.0, and continues to get worse.

screenshot_20180208-182213

The developer should be able to put in pretty much any scale up to about 10.0 and get something expected (if not reasonable!).

### PR DESCRIPTION
**Pull request by jonahwilliams**
~~Based on a breakpoint in the label height.~~
Updated to scale the floatingLabelHeight by the textScaleFactor.

 Fixes https://github.com/flutter/flutter/issues/14583

flutter_01
flutter_02

### CODE REVIEW

**Comment by jonahwilliams** [comment]
cc @HansMuller

**Comment by jonahwilliams** [comment]
Friendly ping  :) @HansMuller

**Comment by HansMuller** [comment]
This looks great but it needs a test.

**Comment by jonahwilliams** [comment]
cc @HansMuller I've added the test case, works out _perfectly_ with the existing calculation scaled.

**Review by HansMuller — APPROVED** [review]
Still LGTM.

**Pull request merged**
