### PR TITLE
Change dialog font family

### LINKED ISSUE #139434: Letterspacing is too tight on Cupertino Dialog title
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When using standard framework dialog boxes, the title has letter spacing that has now become too tight after the recent update to iOS fonts in `master` branch

This can be overcome by widening it in the `Text` widget, but its not correct at default when no letter spacing is applied.  The problem is glaring when you compare the title text to the message text

@MitchellGoodwin 
I know you are now working on the fontWeight issue mentioned https://github.com/flutter/flutter/pull/137275.  So as to not confuse the situation, I figured I would make a new issue here for letter spacing issue that has cropped up after the iOS font changes were rolled into `master` branch last week.

Code sample and screen shot are below
Screen Shot 2023-12-02 at 5 08 35 PM

### Expected results

Correct letter spacing

### Actual results

Too tight letter spacing

### Code sample

<details><summary>Code sample</summary>

```
                              result = await showAdaptiveDialog<bool>(
                                context: context,
                                builder: (context) {
                                  return AlertDialog.adaptive(
                                    title: const Text('Are you sure?'),
                                    content: const Text('Ready to submit?'),
                                    actions: [
                                      TextButton(
                                        onPressed: () => Navigator.of(context).pop(true),
                                        child: const Text('No'),
                                      ),
                                      TextButton(
                                        onPressed: () => Navigator.of(context).pop(true),
                                        child: const Text('Yes'),
                                      ),
                                    ],
                                  );
                                },
                              );
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

Screen Shot 2023-12-02 at 5 08 35 PM

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Framework • revision d861ce496c (12 hours ago) • 2023-12-02 08:02:27 -0500
Engine • revision cfabe42bc0
Tools • Dart 3.3.0 (build 3.3.0-182.0.dev) • DevTools 2.30.0

```

</details>

### PR DESCRIPTION
**Pull request by MitchellGoodwin**
Fixes #139434.

Changes the font from "Text" to "Display". We should only be using the "Display" font for fonts of size 20 and above. Previously "Display" was not showing correctly so this font being wrong was flying under the radar.

Before:
Screenshot 2024-01-10 at 10 49 26 AM

After:
Screenshot 2024-01-10 at 10 52 11 AM

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by MitchellGoodwin** [comment]
This code is covered by a golden test. The golden test isn't failing because it's fuzzy matching to the image from before https://github.com/flutter/flutter/pull/137275.

**Comment by Hixie** [comment]
Shouldn't we be marking old tests as wrong once we decide we're changing the behaviour? cc @Piinks

**Comment by MitchellGoodwin** [comment]
> Shouldn't we be marking old tests as wrong once we decide we're changing the behaviour? cc @Piinks

I asked @Piinks that question and the answer was that the incorrect image will expire naturally.

**Comment by Piinks** [comment]
Asked and answered on Discord as well: https://discord.com/channels/608014603317936148/608018585025118217/1197283919796633600

> Piinks — Yesterday at 2:58 PM
IIRC, It'll still detect regressions. Gold has a short memory. Once the image changes, and it stops seeing the prior image, it forgets about it. Otherwise, you could explicitly go in and mark the prior image negative. But, I think this is similar to when we used flutter/goldens, where branches out of sync could still pass if they were generating an older image, so going in and marking it negative would break alternate branches people are working on

**Review by Piinks — APPROVED** [review]
That test'll do! Thanks @MitchellGoodwin, LGTM

**Pull request merged**
