### PR TITLE
[devicelab] remove vulkan validation devicelab test.

### LINKED ISSUE #151528: Linux_pixel_7pro hello_world_impeller is 5.26% flaky
The post-submit test builder `Linux_pixel_7pro hello_world_impeller` had a flaky ratio 5.26% for the past (up to) 100 commits, which is above our 2.00% threshold.

One recent flaky example for a same commit: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20hello_world_impeller/4553
Commit: https://github.com/flutter/flutter/commit/b713445298598c949e0ea6a3ce6baea3f022750a

Flaky builds:
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20hello_world_impeller/4553
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20hello_world_impeller/4533
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20hello_world_impeller/4523
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20hello_world_impeller/4518
https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_pixel_7pro%20hello_world_impeller/4499

Recent test runs:
https://flutter-dashboard.appspot.com/#/build?taskFilter=Linux_pixel_7pro%20hello_world_impeller

Please follow https://github.com/flutter/flutter/blob/master/docs/infra/Reducing-Test-Flakiness.md#fixing-flaky-tests to fix the flakiness and enable the test back after validating the fix (internal dashboard to validate: go/flutter_test_flakiness).

### PR DESCRIPTION
**Pull request by jonahwilliams**
Fixes https://github.com/flutter/flutter/issues/151528

We're no longer turning on vulkan validation by default so this being a blocking integration test is not as valuable.

### CODE REVIEW

**Review by zanderso — APPROVED** [review]
lgtm w/ question:

Do we run engine unit tests with validation layers?

**Comment by jonahwilliams** [comment]
yes

**Comment by jonahwilliams** [comment]
Wait what, what was it asserting?

**Comment by gaaclarke** [comment]
> Wait what, what was it asserting?

Well it's a high level test so it's asserting a lot of things implicitly.  Explicitly it was testing that we had validation layers turned on (which is no longer the case) and also asserting that we got a log message to the console that mentioned what backend we are using.  We are going to want to keep that, especially for Android when we have Vulkand and OpenGLES backends so users can communicate that.

This is generally a good canary since it's the smallest program we could have and catches any crash that might happen in startup before printing that log message and is running in the realest setup.

**Comment by gaaclarke** [comment]
When we remove skia completely this can potentially be merged with whatever other canary we have.  Looking at the other tests it looks like there may already be one.  As long as skia is in the binary this is important too.

**Comment by jonahwilliams** [comment]
We can't do the backend selection test via log matching though. We *WILL* need to remove the logs at some point in the near future like we did for iOS. Lets keep this test for now and talk about a better approach at the weekly.

**Pull request closed without merging**
