### PR TITLE
Fix leaky test.

### PR DESCRIPTION
**Pull request by polina-c**
Introduced by https://github.com/flutter/flutter/pull/148094

### CODE REVIEW

**Review by QuncCccccc — APPROVED** [review]
LGTM! Thanks for fixing this! Just a question, is there a way to notice whether leaky will happen?

**Comment by polina-c** [comment]
> LGTM! Thanks for fixing this! Just a question, is there a way to notice whether leaky will happen?

Yes!
Pass `--dart-define LEAK_TRACKING=true` to the test :)

**Comment by QuncCccccc** [comment]
> Pass --dart-define LEAK_TRACKING=true to the test :)

Got it! Thanks! I just took a look, the Google testing is failed because there is some name conflicts. I've included a [g3fix](https://critique.corp.google.com/cl/638377846) in the merged [PR](https://github.com/flutter/flutter/pull/148094) but I think that PR and the g3fix are not rolled into G3 yet, so Google testing keeps complaining the same error.

**Comment by polina-c** [comment]
> > Pass --dart-define LEAK_TRACKING=true to the test :)
> 
> Got it! Thanks! I just took a look, the Google testing is failed because there is some name conflicts. I've included a [g3fix](https://critique.corp.google.com/cl/638377846) in the merged [PR](https://github.com/flutter/flutter/pull/148094) but I think that PR and the g3fix are not rolled into G3 yet, so Google testing keeps complaining the same error.

Normally test only PRs do not affect G3. So, I would consider it flackiness.

**Comment by QuncCccccc** [comment]
> Normally test only PRs do not affect G3. So, I would consider it flackiness.

Seems like the auto-generated CL also includes the newly-created `carousel.dart`, so Google testing just broke. Is that possible that the tests depend on this file, so the CL must include the file for the tests.

**Comment by polina-c** [comment]
> > Normally test only PRs do not affect G3. So, I would consider it flackiness.
> 
> Seems like the auto-generated CL also includes the newly-created `carousel.dart`, so Google testing just broke. Is that possible that the tests depend on this file, so the CL must include the file for the tests?

We can just wait when everything lands. No rash here :)

**Comment by QuncCccccc** [comment]
Sounds good! Thanks again for the fix:)

**Pull request merged**
