### PR TITLE
Pass --trace to pub when in verbose mode

### PR DESCRIPTION
**Pull request by tvolkert**
https://github.com/dart-lang/pub/issues/1812

### CODE REVIEW

**Review by jason-simmons — APPROVED** [review]

**Comment by nex3** [comment]
Why `--trace` and not `--verbose`?

**Comment by tvolkert** [comment]
> Why `--trace` and not `--verbose`?

Because in dart-lang/pub#1812, the user was presented with this message from pub:

```
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error --no-packages-dir
```

Is `--verbose` preferred?

**Comment by nex3** [comment]
It just seems like `--verbose` would match the flag the user passes to `flutter`. The difference is that `--trace` only prints verbose information if `pub` encounters a faillure, whereas `--verbose` prints it all the time.

**Pull request merged**
