### PR TITLE
Use recommended plugin DSL when creating a new flutter plugin

### PR DESCRIPTION
**Pull request by alestiago**
After creating a plugin using the flutter dev tool with:

```sh
flutter create my_plugin -t plugin --platforms android
```

The generated `android/build.gradle` file is not using the [recommended plugin DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block), but instead using the [Legacy Plugin Application](https://docs.gradle.org/current/userguide/plugins.html#sec:old_plugin_application) (see [example difference](https://stackoverflow.com/a/73982049/14335923)). Moreover, from the [Gradle documentation](https://docs.gradle.org/current/userguide/plugins.html#sec:old_plugin_application):

> With the introduction of the [plugins DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block), users should have little reason to use the legacy method of applying plugins. It is documented here in case a build author cannot use the plugin DSL due to restrictions in how it currently works.

I've included the versions within the `android/setting.gradle` instead of inlining in `android/build.gradle` to be consistent with the approach defined in the Flutter documentation regarding [Deprecated imperative apply of Flutter's Gradle plugins](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-appl). 

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by andrewkolos** [comment]
Converting this to draft since this has many failing tests. Feel free to mark as ready for review when it is.

**Comment by alestiago** [comment]
@andrewkolos can you provide some insights to what tests need to get update for this template change?

**Comment by Piinks** [comment]
(PR Triage): @alestiago do you plan on returning to this change to resolve the failures?

**Comment by alestiago** [comment]
@Piinks I don't have a lot of bandwidth right now, but I might be able to make some space for it, I think I was unsure what test needed template updates to get this working, if you know right off the bat let me know and I might be able to land the test changes in.

**Comment by bartekpacia** [comment]
Hey, I just found this PR. I think what @alestiago is trying to do here is the same thing I tried to do in #144114, and failed. I wrote down my findings there, I hope it may be of use to you.

**Comment by alestiago** [comment]
Thanks @bartekpacia I do not have time to prioritise this right now, will close in favour of yours.

**Pull request closed without merging**
