### PR TITLE
Add missing parameters in `TextFormField`

### PR DESCRIPTION
**Pull request by lsaudon**
`TextFormField` does not have all the parameters of `TextField`.

Added:
```dart
    UndoHistoryController? undoController,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? cursorOpacityAnimates,
    ui.BoxHeightStyle selectionHeightStyle = ui.BoxHeightStyle.tight,
    ui.BoxWidthStyle selectionWidthStyle = ui.BoxWidthStyle.tight,
    DragStartBehavior dragStartBehavior = DragStartBehavior.start,
    ContentInsertionConfiguration? contentInsertionConfiguration,
    Clip clipBehavior = Clip.hardEdge,
    bool scribbleEnabled = true,
    bool canRequestFocus = true,
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by lsaudon** [comment]
> It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need [an exemption](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests) to this rule, contact Hixie on the #hackers channel in [Chat](https://github.com/flutter/flutter/wiki/Chat) (don't just cc him here, he won't see it! _He's on Discord!_).
> 
> If you are not sure if you need tests, consider this rule of thumb: the purpose of a test is to make sure someone doesn't accidentally revert the fix. Ask yourself, **is there anything in your PR that you feel it is important we not accidentally revert back to how it was before your fix?**
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.

For me, there is no need for a new test because it should already be tested by TextField.

**Comment by justinmc** [comment]
@lsaudon Thanks for cleaning this up!  Would you be able to just write a simple test that confirms that the new parameters on TextFormField are passed through to TextField?

**Review by Piinks — COMMENTED** [review]
Hi @lsaudon thanks for contributing!
It looks like this is not ready for review yet. Can you fill out the PR description, including what issue this is resolving? This also currently does not have tests.
Thanks!

**Comment by lsaudon** [comment]
@Piinks @justinmc
Thanks for your feedback.
It's ok, I added the descriptions and tests.

**Review by Piinks — COMMENTED** [review]
Thanks for the update @lsaudon! In general, we typically do not make changes that just rearranges parameters. This makes it difficult to track down previous changes in the git history, and it affect dart fixes, which specify constructor indices for auto migrating broken code. Can you remove the changes that rearranged the already existing parameters, and place the new ones at the end?

**Comment by lsaudon** [comment]
I made the changes I requested. @Piinks

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

Thanks for contributing!

**Review by justinmc — APPROVED** [review]
LGTM :+1:

**Pull request merged**
