### PR TITLE
[flutter_tools] allow passing properties directly to Gradle

### LINKED ISSUE #48707: How to pass custom arguments from command line in Flutter?
## Use case

i want to use gradle plugins and cli to publish aab to google play，but flutter cli don't accept custom argument.

```shell
flutter build appbundle -t lib/main_${flavorName}.dart --flavor ${flavorName} --target-platform android-arm,android-arm64 --publish-to-play 
```

```groovy
                variant.assemble.doLast {
                    if (!target.hasProperty('publish-to-play')) {
                        return
                    }
                    publishToPlay(target, variant, mergePlay, false)
                }

                target.tasks.findByPath("bundle${variant.name.capitalize()}").doLast {
                    if (!target.hasProperty('publish-to-play')) {
                        return
                    }
                    publishToPlay(target, variant, mergePlay, true)
                }
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
Allow passing key value pairs directly to the gradle project.

Fixes https://github.com/flutter/flutter/issues/48707

### CODE REVIEW

**Comment by irvine5k** [comment]
Hey, @jonahwilliams. The issue mentioned in this PR is related to iOS too. So I think that we need to choose another name for the flag, something like `mobilePlatformArgs`.

How it works on iOS:

```shell
# Type a script or drag a script file from your workspace to insert its path.

function entry_decode() { echo "${*}" | base64 --decode; }

IFS=',' read -r -a define_items <<< "$DART_DEFINES"


for index in "${!define_items[@]}"
do
    define_items[$index]=$(entry_decode "${define_items[$index]}");
done

printf "%s\n" "${define_items[@]}"|grep '^DEFINEEXAMPLE_' > ${SRCROOT}/Flutter/Defineexample.xcconfig
```

You can see all the configurations in this article: https://itnext.io/flutter-1-17-no-more-flavors-no-more-ios-schemas-command-argument-that-solves-everything-8b145ed4285d

**Comment by jonahwilliams** [comment]
passing a property to gradle is different then embedding another key/value pair in the xcconfig. The latter is sticky, and may have other semantic differences, so a different flag name may be required.

**Comment by irvine5k** [comment]
I did not know about it, thanks for the info. But the intention of the comment was to make you aware that there's the need for an iOS flag.

**Comment by jonahwilliams** [comment]
but you could also just use your own xcconfig files, there is no need to use flutter's right?

**Comment by irvine5k** [comment]
You're right. I was with my mind in this use-case(#82865) 😅

**Review by jmagman — APPROVED** [review]
LGTM

**Pull request merged**
