### PR TITLE
Bump json_rpc_2 dependency

### PR DESCRIPTION
**Pull request by srawlins**
json_rpc_2 2.0.6 contains fixes for fuzzy arrows (https://github.com/dart-lang/sdk/issues/29630) and asserts-only-accept-bool (https://github.com/dart-lang/sdk/issues/30326) needed for Dart 2.0.

### CODE REVIEW

**Comment by srawlins** [comment]
CC @tvolkert

**Comment by srawlins** [comment]
Yay travis!

**Comment by Hixie** [comment]
Is this just the output of `flutter update-packages --force-upgrade`?

**Comment by srawlins** [comment]
Yeah, after I bumped json-rpc-2 in a few places.

**Comment by Hixie** [comment]
> Yeah, after I bumped json-rpc-2 in a few places.

How do you mean?

**Comment by Hixie** [comment]
LGTM

**Comment by tvolkert** [comment]
LGTM

**Pull request merged**
