### PR TITLE
Bump to Dart SDK 1.23.0-dev.10

### LINKED ISSUE #9042: Upgrade dart to 1.23.0-dev.10
Now that this release is out, it will allow us to understand flutter usage via telemetry 

CC @sethladd @pq @eseidel

### PR DESCRIPTION
**Pull request by pq**
* allows us to understand flutter usage via telemetry
* brings in `@immutable`

Fixes: #9042 

@abarth @tvolkert @Hixie 

FYI: @sethladd @kevmoo

### CODE REVIEW

**Comment by pq** [comment]
Looks like appveyor is unhappy.

Anyone know how to get at `flutter_01.log` on an appveyor build?

@sethladd @tvolkert ?

**Comment by tvolkert** [comment]
> Anyone know how to get at flutter_01.log on an appveyor build?

@goderbauer 

> brings in `@immutable`

How dire is our need to use this?  I ask because I'd like to minimize the time difference between when we start using new SDK features externally and when they're available internally within Google.  The longer that lag time, the more backed up we get when trying to bump Flutter within Google.  @keertip may also know the likelyhood of `dev.10` landing internally soonish.

**Comment by kevmoo** [comment]
@tvolkert - @dgrove says dev.10 should be this week in Google3

**Comment by keertip** [comment]
This week is an extremely optimistic view! We are fixing google3 code in preparation, so should have a better idea of when dev.10 will be in by mid week.

**Comment by abarth** [comment]
> I ask because I'd like to minimize the time difference between when we start using new SDK features externally and when they're available internally within Google.

Is this true for analyzer lints as well?  We could start using the `@immutable` annotations and old versions of the analyzer would just ignore it.

**Comment by tvolkert** [comment]
> We could start using the @immutable annotations and old versions of the
> analyzer would just ignore it.

Good point - in this case there's no harm in using this immediately.

**Comment by goderbauer** [comment]
> Anyone know how to get at flutter_01.log on an appveyor build?

Not that I am aware of. However, it's probably crashing because the `ansiSupported` getter we use in [1] moved from `platform` to `stdin` in 1.23-dev.10. The new API is https://api.dartlang.org/dev/1.23.0-dev.10.0/dart-io/Stdin/supportsAnsiEscapes.html. My understanding is that the new API can replace the entire `colorSupported` logic in Flutter as it now supports detecting ANSI support on POSIX and Windows platforms.

If it is sill crashing after that change, I am happy to run it locally on my Windows machine and get you the log from there.

[1] https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/base/logger.dart#L253

**Comment by pq** [comment]
Thanks all!

@danrubel (or anyone), I'm curious why the test script has two analysis passes.

    bin/flutter analyze --flutter-repo

followed by:

    bin/flutter analyze --flutter-repo --watch --benchmark

I notice that the first doesn't catch everything but shouldn't it?

**Comment by abarth** [comment]
> I'm curious why the test script has two analysis passes.

We kept breaking the `--watch` version when we were only running the first one.  I would have thought they'd report the same issues.  /cc @Hixie

**Comment by pq** [comment]
Thanks @abarth .

**Comment by danrubel** [comment]
I just [updated flutter analyze to call dartanalyzer](https://github.com/flutter/flutter/commit/52245e5082d70e089d6b9460a681849000de2340), and at this point:
* `flutter analyze` calls `dartanalyzer`
* `flutter analyze --flutter-repo` uses the embedded analyzer library in a custom way
* `flutter analyze --watch` (all forms) calls AnalysisServer

The first and third should always produce the same results. Now I need to enhance `dartanalyzer` before I can bring the second into line with the other two.

**Comment by pq** [comment]
Thanks @goderbauer!  Am I right that really we need to update the `platform` [package](https://pub.dartlang.org/packages/platform)?  It looks like you started that a ways back (https://travis-ci.org/google/platform.dart/builds/211981851) actually.  Is that something we should pick up again?

**Comment by goderbauer** [comment]
@pq Yes, package:platform will have to be updated for this as well.

**Comment by tvolkert** [comment]
LGTM

**Comment by abarth** [comment]
@pq Where do I find the declaration for `@immutable`?  Maybe we need to publish a new copy of `package:meta` ?

**Comment by sethladd** [comment]
Apparently, this didn't give us `@immutable`. For next time, to better understand how to tell if a feature is available, why didn't `dev.10` give us this feature?

cc @pq

**Comment by kevmoo** [comment]
@sethladd give me the commit where this landed in the SDK and I can show you "one cool trick"

**Comment by tvolkert** [comment]
`@immutable` exists in `package:meta`, not the SDK.  Presumably, the SDK version is bundled with an analyzer version that respects `@immutable`...

**Comment by kevmoo** [comment]
https://github.com/dart-lang/sdk/commit/4f28d97ac23605a280b6ad26d78d83655018af0f

Look at SDK commits. 

screen shot 2017-04-03 at 11 17 32 am

So this *should* be working. Assuming you mean in the analyzer...

**Comment by sethladd** [comment]
Ah, I see the `-dev.11` in that screenshot. OK, probably just some wires crossed. Thanks!

**Pull request merged**
