### PR TITLE
Retry tasks when adb reports that a device has gone offline unexpectedly

### PR DESCRIPTION
**Pull request by zanderso**

### CODE REVIEW

**Comment by matanlurey** [comment]
Two questions:

1. Will this run on every test, i.e. [the test I wrote here](https://github.com/flutter/flutter/blob/master/dev/bots/suite_runners/run_flutter_driver_android_tests.dart)?
2. If the emulator is _crashing_, will this restart the emulator? I.e. does task mean "everything including EMU setup"?

**Comment by matanlurey** [comment]
Also something I can't explain, take a look at this:

Screenshot 2024-08-09 at 6 22 14 PM

The [red block](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android_emu%20flutter_driver_android_test/78/overview) was an instant fail, but the [black !](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android_emu%20flutter_driver_android_test/66/overview) appeared to re-run?

**Comment by zanderso** [comment]
> Also something I can't explain, take a look at this:
> 
> The [red block](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android_emu%20flutter_driver_android_test/78/overview) was an instant fail, but the [black !](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux_android_emu%20flutter_driver_android_test/66/overview) appeared to re-run?

I believe cocoon won't schedule a re-run if the test is running or already passed on a newer commit.

**Comment by zanderso** [comment]
> Two questions:
> 
> 1. Will this run on every test, i.e. [the test I wrote here](https://github.com/flutter/flutter/blob/master/dev/bots/suite_runners/run_flutter_driver_android_tests.dart)?

No =( We have too many test harnesses.

> 2. If the emulator is _crashing_, will this restart the emulator? I.e. does task mean "everything including EMU setup"?

If the emulator is straight up crashing, then these retries won't restart it. Looking at the tree, the failures ~all look like this one:

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8740073209622739633/+/u/run_external_textures_integration_test/stdout

where the emulated device disappears mid-test, and then reappears and is responsive again when the task is retried, but the emulator process itself is still running the whole time.

Now that I type this out, I'm wondering if the issue is that the emulated devices is not ready yet for some reason when we first try to run things on it?

**Review by matanlurey — APPROVED** [review]
LGTM mostly if you want this running over the weekend to review (otherwise I can do a more thorough review on Monday).

**Comment by zanderso** [comment]
Hesitating on landing this since it's a bit of a last resort. Would like to exclude the possibility that the tests are getting OOM-killed as discussed on https://github.com/flutter/flutter/issues/152769.

**Comment by zanderso** [comment]
Obsolete

**Pull request closed without merging**
