### PR TITLE
apply prefer_asserts_in_initializer_list lint

### PR DESCRIPTION
**Pull request by a14n**
Same as #10502 without `flutter_tools`

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
Turns out this broke flutter_driver because of the same issue that affected flutter_tools, assert initializers aren't enabled over there yet. I'll revert.

**Comment by Hixie** [comment]
@cbracken is working on a localized fix instead.

**Comment by cbracken** [comment]
Landed - we're green again :)

**Comment by a14n** [comment]
Thanks for the fix and sorry for the breakage.

**Pull request merged**
