### PR TITLE
Deprecated text from tabs widget

### LINKED ISSUE #78788: [Tab Widget] Rename `Tab.text` to `Tab.label`
## Use case
The `Tab` widget currently looks like this:

out

A very similar looking widget is `BottomNavigationBarItem`:

out1

The arguments for the composition of these widgets are also similar, an `Icon` and a `String`.

The material spec also describes the text used in [tabs](https://material.io/components/tabs#anatomy) and [bottom navigation bar items](https://material.io/components/bottom-navigation#anatomy) as **"text label"**.

Considering these, it would seem that the labeling of the `Tab` widget is done through the `label:` parameter. This is not the case.

## Proposal

Rename `Tab.text` to `Tab.label`, to better match its intended purpose and the material spec.

### PR DESCRIPTION
**Pull request by Abhishek01039**
Fixes https://github.com/flutter/flutter/issues/78788

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 12 untriaged digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/78830

**Comment by skia-gold** [comment]
Gold has detected about 12 untriaged digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/78830

**Comment by skia-gold** [comment]
Gold has detected about 12 untriaged digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/78830

**Comment by skia-gold** [comment]
Gold has detected about 12 untriaged digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/78830

**Comment by skia-gold** [comment]
Gold has detected about 4 untriaged digest(s) on patchset 5.
View them at https://flutter-gold.skia.org/cl/github/78830

**Comment by skia-gold** [comment]
Gold has detected about 4 untriaged digest(s) on patchset 6.
View them at https://flutter-gold.skia.org/cl/github/78830

**Comment by goderbauer** [comment]
Thanks for the contribution. While label probably would have been a better name for it, this seems like an unnecessary breaking change for many existing apps. I don't think the breakage is worth it. I am going to close this.

**Pull request closed without merging**
