### PR TITLE
Simplify the AutoLayout API

### PR DESCRIPTION
**Pull request by abarth**
This patch makes it easier to use the auto layout API:
- We no longer use operator== because that requires an ugly cast by the
  API user.
- Also, "leftEdge" is now just "left" for less verbosity.
- AutoLayoutChild not implies its key from the AutoLayoutParam object.
- We now correctly layout every child of a RenderAutoLayout object even
  if the solver doesn't flush any updates to that child.

### CODE REVIEW

**Comment by abarth** [comment]
@chinmaygarde

**Comment by chinmaygarde** [comment]
lgtm. I wouldn't mind getting rid of the `<=` and `>=` overrides. Not sure if that is idiomatic Dart either.

Travis mad because of the tests in the Cassowary package BTW.

**Comment by abarth** [comment]
Tests!  In our moment of triumph!

**Comment by abarth** [comment]
> I wouldn't mind getting rid of the <= and >= overrides.

Yeah, >= and <= seem out of place now.  I'll save that for a future patch though.

**Comment by chinmaygarde** [comment]
lgtm

**Pull request merged**
