### PR TITLE
Upgrade template Gradle, App AGP, Module AGP, and Kotlin versions, and tests

### PR DESCRIPTION
**Pull request by gmackall**
After the land of https://github.com/flutter/engine/pull/53592, there is some log spam:
```
e: /Users/mackall/.gradle/caches/transforms-3/c1e137371ec1afe9bc9bd7b05823752d/transformed/fragment-1.7.1/jars/classes.jar!/META-INF/fragment_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
e: /Users/mackall/.gradle/caches/transforms-3/d86c7cb1c556fe1655fa56db671c649c/transformed/jetified-activity-1.8.1/jars/classes.jar!/META-INF/activity_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
...
```

I think this is harmless, but still annoying. Upgrading the AGP version fixes it. To be honest, I don't know why (I expected the Kotlin version would do it). But after https://github.com/flutter/flutter/pull/146307, our tests have been running on AGP/Gradle 8.1/8.3 for a while, so it makes sense to upgrade anyways.

In a follow up PR:
1. Also upgrade the tests that were left behind in https://github.com/flutter/flutter/pull/146307, as I think removal of discontinued plugins paved the way here.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by gmackall** [comment]
TODO: The tests in `test/android_preview_integration.shard/flutter_build_preview_sdk_test.dart` will fail because that shard uses Java 11. 

They were living on the same shard as the Gradle tests because they conveniently worked with Java 11, and this was a good shard to isolate to that Java version. But now this convenience is gone (the lower bounds that we are testing for Gradle are `7.0.x` version which don't support Java 17, so they can't live a Java 17 shard and the preview tests can't live on a Java 11 shard because they use the updated templates).

**Review by reidbaker — APPROVED** [review]

**Review by reidbaker — APPROVED** [review]

**Comment by gmackall** [comment]
Requesting review from you as well @christopherfujino because this further fragments a subset of the tools tests into yet another shard, and I want to hear if you are opposed or otherwise make you aware.

The justification why another shard is needed is that the dependency checking tests need Java 11, and not the preview sdk. And the preview tests now need Java 17 (unless we hardcode old Gradle versions, right now they use `create`).

And this set is also different from the main shard, which uses Java 17 and the stable (not preview) android sdk.

**Comment by christopherfujino** [comment]
> Requesting review from you as well @christopherfujino because this further fragments a subset of the tools tests into yet another shard, and I want to hear if you are opposed or otherwise make you aware.
> 
> The justification why another shard is needed is that the dependency checking tests need Java 11, and not the preview sdk. And the preview tests now need Java 17 (unless we hardcode old Gradle versions, right now they use `create`).
> 
> And this set is also different from the main shard, which uses Java 17 and the stable (not preview) android sdk.

Yeah, this is ugly, and not efficient with CI resources, but I can't think of a better short-term solution, so I think this is fine. FYI @andrewkolos 

Long-term, it might be worth having the tool_integration_tests install multiple JDKs and such in the same build, and then allowing individual tests to select the one they want to test. This would require additional design, however.

**Review by christopherfujino — APPROVED** [review]
This is fine

**Comment by gmackall** [comment]
Agreed on the wish to have multiple JDKs, and then configure per test

**Comment by goderbauer** [comment]
Reason for revert: Failing test in https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8743574743030691569/+/u/run_android_obfuscate_test/stdout

**Comment by gmackall** [comment]
Hmm, looks like this breaks building modules as AARs. 

TODO: 
1. Figure out why
2. The test that we can build a module as an AAR should probably run in presubmit if we change the templates for modules, so add that to the reland.

**Comment by reidbaker** [comment]
https://docs.gradle.org/7.3/javadoc/org/gradle/api/Project.html#getComponents--
https://docs.gradle.org/8.8/javadoc/org/gradle/api/Project.html#components(org.gradle.api.Action)

looks like they added a parameter at some point.

**Comment by gmackall** [comment]
I think it is because of 
https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes
> AGP 8.0 creates no SoftwareComponent by default. Instead AGP creates SoftwareComponents only for variants that are configured to be published using the publishing DSL.

And we need to follow https://developer.android.com/build/publish-library/configure-pub-variants, or otherwise change how we are initializing the `Aar` task.

**Pull request merged**
