### PR TITLE
[flutter_tools] support new SDK structure for sdkmanager

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Teach the android SDK class about the cmdline tools, which accept licenses instead of the obsolete platform tools.

We're not currently able to accept android licenses in the latest SDK. We also need to update our documentation to explain which component to download.

 https://github.com/flutter/flutter/issues/51712

### CODE REVIEW

**Comment by jonahwilliams** [comment]
The documentation to update is here: https://flutter.dev/docs/get-started/install/macos#install-android-studio

**Review by jmagman — APPROVED** [review]
LGTM. You could add a comment about how this was in `tools/bin` prior to 3.6, though I'm happy with the git archeology of just looking at this PR and the issue.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by sandy9808** [comment]
Sir is the error resolved or not?

**Comment by jmagman** [comment]
This change is in [v1.15.12](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos), so currently [master and dev channels](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels).

**Pull request merged**
