### PR TITLE
Add ThemeData.shadowColor

### PR DESCRIPTION
**Pull request by reminjp**
## Description

I am working on following up #33257 because its author seems to be inactive.

## Related Issues

#27461

## Tests

- Simply add `shadowColor` to tests in `theme_data_test.dart`, `material_test.dart`.
- Modify some tests because the default value of `Material.shadowColor` is `null` now.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [`ThemeData.raw`](https://api.flutter.dev/flutter/material/ThemeData/ThemeData.raw.html) requires `shadowColor`.

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [x] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by rdrgn** [comment]
So should I add @LucasR93's code as my commit...?

**Comment by rdrgn** [comment]
@googlebot I consent.

**Comment by rdrgn** [comment]
```
SLVR:                                                                                                     fact: process >=3.0.4 depends on platform >=1.0.1

SLVR:                                                                                                       selecting process 3.0.13

SLVR:                                                                                                       fact: every version of plugin_platform_interface depends on meta ^1.0.0

SLVR:                                                                                                         selecting plugin_platform_interface 1.0.2

SLVR:                                                                                                           selecting platform 2.2.1

SLVR:                                                                                                           fact: path_provider_platform_interface >=1.0.1 requires Flutter SDK version >=1.10.0 <2.0.0

SLVR:                                                                                                           conflict: path_provider_platform_interface >=1.0.1 requires Flutter SDK version >=1.10.0 <2.0.0

SLVR:                                                                                                           ! path_provider_platform_interface >=1.0.1 is satisfied by path_provider_platform_interface 1.0.2

SLVR:                                                                                                           ! which is caused by "platform_views depends on path_provider_platform_interface 1.0.2"

SLVR:                                                                                                           ! thus: version solving failed

SLVR: Version solving took 0:00:01.323970 seconds.

    | Tried 1 solutions.

FINE: Resolving dependencies finished (1.3s).

ERR : The current Flutter SDK version is 0.0.0-unknown.

    | 

    | Because platform_views depends on path_provider_platform_interface >=1.0.1 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.

FINE: Exception type: SolveFailure

FINE: package:pub/src/solver/version_solver.dart 312:5   VersionSolver._resolveConflict

    | package:pub/src/solver/version_solver.dart 133:27  VersionSolver._propagate

    | package:pub/src/solver/version_solver.dart 97:11   VersionSolver.solve.<fn>

    | ===== asynchronous gap ===========================

    | dart:async                                         Future.catchError

    | package:pub/src/utils.dart 113:52                  captureErrors.wrappedCallback

    | package:stack_trace                                Chain.capture

    | package:pub/src/utils.dart 126:11                  captureErrors

    | package:pub/src/command_runner.dart 193:13         PubCommandRunner.runCommand

---- End log transcript ----
pub get failed (1; ---- End log transcript ----)
������������������������������������
```

**Review by Piinks — COMMENTED** [review]
Hi @rdrgn welcome! 🎉  Thanks for the contribution!

> **Cirrus CI / analyze-linux**
> 
> ✅ 00:30 clone
> ✅ 03:42 pub
> ✅ 00:01 flutter_pkg
> ✅ 00:24 artifacts
> ❌ 01:18 setup
> 

I recommend updating your branch with changes from master first to see if that will resolve these versioning errors. This tends to happen with old branches that have fallen far out of date with master. 
Also, cc/ @darrenaustin and @HansMuller who have been working hard on Theming, they may have some thoughts here. :)

**Review by HansMuller — COMMENTED** [review]
This is a reasonable change. Although we'd prefer to avoid introducing new top-level ThemeData properties, it doesn't seem terribly useful to add a MaterialTheme et al. and to have Material's shadowColor default to a ColorScheme color.

Just need some simple tweaks.

**Comment by rdrgn** [comment]
@Piinks 
Thanks for your attention to my PR. I am puzzled because merging the master branch did not fix the checks by Cirrus CI. 😟

@HansMuller 
Thanks for reviewing! I updated the docs about the default values.

I am not so sure about `ThemeData.applyElevationOverlay`, so I have not added any description about it yet. 😖 Could you tell me more about it? (Can you give me a link to the "the TBD one for Material.shadowColor"? I couldn't find it.) Shouldn't this be fixed in another PR?

**Comment by HansMuller** [comment]
@rdrgn - https://api.flutter.dev/flutter/material/ThemeData/applyElevationOverlayColor.html
It's important to help developers who are reading about shadowColor to find applyElevationOverlayColor since shadowColor isn't terribly effective in dark mode.

The existing Material shadowColor property is https://api.flutter.dev/flutter/material/Material/shadowColor.html.

**Comment by Piinks** [comment]
> @Piinks
> Thanks for your attention to my PR. I am puzzled because merging the master branch did not fix the checks by Cirrus CI. 😟

Thanks for giving it a go!
This may require a more forceful update, or you can re-open this as a new PR on a fresh branch.
This has worked to resolve the versioning errors that are causing Cirrus to fail on other PRs:
```
git fetch upstream
git reset --soft upstream/master
git commit .... // This will re-commit all of your changes
git push -f ... // Force push to update PR
```

**Comment by rdrgn** [comment]
> It's important to help developers who are reading about shadowColor to find applyElevationOverlayColor since shadowColor isn't terribly effective in dark mode.

That makes sense! I will write a brief explanation.

**Review by HansMuller — APPROVED** [review]
LGTM, nicely done.

**Pull request merged**
