### PR TITLE
update dev/integration_tests/flutter_gallery/android/settings.gradle

### LINKED ISSUE #63199: plugin not found in `dev/integration_tests/flutter_gallery`
While building, there's error message: 
```
Plugin project :video_player_web not found. Please update settings.gradle.
Plugin project :connectivity_macos not found. Please update settings.gradle.
```

### PR DESCRIPTION
**Pull request by CareF**
## Description

The current version of `dev/integration_tests/flutter_gallery` is using a old settings.gradle that's not compatible with the plugins it's using, causing warning message: 

```
Plugin project :video_player_web not found. Please update settings.gradle.
Plugin project :connectivity_macos not found. Please update settings.gradle.
```

## Related Issues

Fixes #63199

## Tests

N/A

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by liyuqian** [comment]
@blasten last updated this gradle to its current content. This PR seems to be restoring the old gradle. Is this intended?

**Comment by blasten** [comment]
It sounds like the  resolved versions of `video_player_web` and `connectivity_macos` contain a `android/build.gradle` file. I would try to ensure that they are resolved to a version that doesn't include those files.

**Comment by CareF** [comment]
@cyanglaz Should we make the change here or to somewhere in the plugins repo?

**Comment by CareF** [comment]
@blasten @liyuqian These packages are pin-ed since #50365 due to the plugins' breaking change. Updating files in the plugins won't help because we can't update the depended version in the framework repo.

**Comment by liyuqian** [comment]
Regarding https://github.com/flutter/flutter/pull/63200#issuecomment-675072701, shall we fix the flutter gallery smoke test so we no longer needs to pin `video_player`? CC @jonahwilliams @zanderso @goderbauer

**Pull request closed without merging**
