### PR TITLE
optimize flutter update-packages

### LINKED ISSUE #1313: Optimize "flutter update-packages"
Our builds take 8-10 mins now. 2 minutes of that is running pub via `./dev/update_packages.dart`:

```
Ran "pub get" 19 times in 125880 ms
```

We could optimize this by reading all the pubspecs for the examples and packages projects, unifying the info, writing out a synthetic pubspec in a temp dir, running pub on that, and then creating `pubspec.lock` and `.packages` files for each project. It would probably drop the time from ~125s to 10-15s. We might also need to create a `packages/` symlink dir in each project as some of our tooling depends on looking into `packages/ske_engine` and possibly other package dirs.

### LINKED ISSUE #2104: update-packages failures should end travis
Right now if update-packages fails, we ignore the failure, and instead fail with a side-effect of taht failure. e.g. just now a transient error on the pub server meant that we didn't properly update fitness and the result was an analyzer error that playfair wasn't available.

### PR DESCRIPTION
**Pull request by devoncarew**
- optimize flutter update-packages (fix https://github.com/flutter/flutter/issues/1313, fix https://github.com/flutter/flutter/issues/2104)
- for `flutter update-packages`, scan all the pubspecs, create a new synthetic pubspec, store it in the `bin/cache/artifacts/repo_packages` dir, run pub get/upgrade on that, and then copy the resulting .packages and lock file to the ~15 repo dart projects. flutter update-packages time drops from ~130 seconds to 13. We keep the temp dir in the cache so that subsequent runs are faster (~1-2 seconds).

When we switch to `1.16.0-dev.3.0` we can start using --no-precompile which should halve the initial time.

The output is pretty verbose, but this should only be run by repo developers, and it's nice to have a clear picture of all the packages that we're using.

```
Running 'pub get' in /Users/devoncarew/projects/flutter/flutter/bin/cache/artifacts/repo_packages/...

Repo packages (15):
  packages/cassowary
  packages/flutter
  packages/flutter_driver
  packages/flutter_markdown
  packages/flutter_sprites
  packages/flutter_test
  packages/flutter_tools
  packages/flx
  packages/newton
  packages/playfair
  examples/hello_world
  examples/layers
  examples/material_gallery
  examples/stocks
  dev/manual_tests

Direct depencencies (31):
  analyzer: 0.27.2
  archive: 1.0.20
  args: 0.13.4
  asn1lib: 0.4.1
  bignum: 0.1.0
  box2d: 0.2.0
  collection: 1.5.1
  crypto: 0.9.2
  file: 0.1.0
  flutter_gallery_assets: 0.0.12
  intl: 0.12.7
  json_rpc_2: 1.2.0
  json_schema: 1.0.3
  markdown: 0.9.0
  matcher: 0.12.0+2
  mockito: 0.11.0
  mustache4dart: 1.0.10
  package_config: 0.1.3
  path: 1.3.9
  pointycastle: 0.10.0
  pub_semver: 1.2.3
  quiver: 0.21.4
  sky_engine: 0.0.99
  sky_services: 0.0.99
  stack_trace: 1.6.4
  string_scanner: 0.1.4+1
  test: 0.12.13
  vector_math: 1.4.7
  vm_service_client: 0.1.2+1
  xml: 2.4.2
  yaml: 2.1.8

Transitive depencencies (39):
  async: 1.9.0
  barback: 0.15.2+7
  boolean_selector: 1.0.0
  charcode: 1.1.0
  cli_util: 0.0.1+2
  code_transformers: 0.4.2+1
  convert: 1.0.1
  csslib: 0.12.2
  dart_style: 0.2.4
  fixnum: 0.10.2
  glob: 1.1.1
  html: 0.12.2+1
  http_multi_server: 2.0.0
  http_parser: 2.2.1
  logging: 0.11.2
  mime: 0.9.3
  mojo: 0.4.17
  mojo_sdk: 0.2.20
  mojo_services: 0.4.23
  petitparser: 1.5.1
  plugin: 0.1.0
  pool: 1.2.1
  quiver_collection: 1.0.0
  quiver_iterables: 1.0.0
  quiver_pattern: 1.0.0
  reflectable: 0.5.3
  shelf: 0.6.5
  shelf_static: 0.2.3+3
  shelf_web_socket: 0.2.0
  source_map_stack_trace: 1.0.4
  source_maps: 0.10.1+1
  source_span: 1.2.2
  stream_channel: 1.3.1
  typed_data: 1.1.2
  utf: 0.9.0+3
  watcher: 0.9.7
  web_socket_channel: 1.0.2
  when: 0.2.0
  which: 0.1.3

Elapsed time 11.735 seconds.
```

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
I suspect this has a side-effect of making it no longer required for packages inside flutter to express exact dependencies?  Since now any single mention of a package will cause that package to exist for all packages inside the flutter repo?

**Comment by devoncarew** [comment]
Yeah, some caveats:

- this means that all (~15) packages inside the repo will be using the same packages versions; we have to be OK with that (at least as this patch is now)
- when specifying versions, pubspec need to request the exact same version, or use `any`. `any`'s are ignored; explicit versions are compared. If any are not equal, be print who used what versions and fail

**Comment by abarth** [comment]
I'm concerned that this change will cause us to have overly permissive `.packages` files.  As I understand what you've proposed, if any package in flutter.git depends on a package, then that package will be visible to every other package in the repository.  That seems overly permissive.

**Comment by devoncarew** [comment]
Well, the .packages file will likely be a superset of the packages that a particular project has requested (via direct and transitive dependencies). But this isn't much different then things are today. The `stock` example references flutter_test in it's `dev_dependencies`; that references `test`, which references `analyzer`, which references the world. So many packages today have a great many more available packages in `.packages` then they've explicitly requested in the `dependencies` section.

Any packages refs in code in `lib/` should be reflected in the `dependencies` section, but there's no analyzer support for enforcing this currently.

**Comment by sethladd** [comment]
This might be something we need to fix at the platform level (cc @munificent). We've seen multiple cases where an "application package" would like multiple ".packages" -- some for running tests, some for running a bin entry point, some for running a flutter app, some for running a dev-time-only script, etc.

Perhaps moving the Dart platform from "one .packages per package" to "one .packages per entry point".

**Comment by abarth** [comment]
> The stock example references flutter_test in it's dev_dependencies; that references test, which references analyzer, which references the world.

At some point we want to prune down the production dependencies for package:flutter to something reasonable (i.e., not including analyzer).

**Comment by devoncarew** [comment]
Thinking about this, it's possible to re-work the PR to write out custom .packages for each project. We'd traverse the normal and dev deps for the target project, and the normal deps for things it references. All projects would still be pinned to the same versions, they'd just have different views on the full set of available packages.

I could look at that, or we could discuss it more or VC.

**Comment by Hixie** [comment]
We already require that all flutter packages depend on the same version. If they ever don't, `flutter analyze` falls over and our tree goes red. So that part is fine.

**Comment by abarth** [comment]
Let's talk about it over VC.  The end-state that I'd like to get to is that we have many fewer production dependencies for package:flutter and that we have pinned those dependencies to exact version, potentially even hosting the bits for those packages on servers that we control.

**Comment by apwilson** [comment]
FWIW we are planning to do something similar for our repo: https://github.com/domokit/sysui/pull/623

I think this is a common problem that having dart platform level support for as Seth suggested would be very useful.

**Comment by apwilson** [comment]
Having a 'here are all the dependencies for the project' in one place massively speeds up get pub get/upgrade, dart analyzing, and dart doc generation.

**Comment by apwilson** [comment]
Also @devoncarew in order for this to work you don't need to manually get the transitive dependencies yourself.  Just by having all the projects in the repo as your dependencies you pull in all the transitive dependencies.

**Comment by devoncarew** [comment]
Yeah, the traversing bit was more if we wanted to generate separate `.packages` files, one specific to each repo package.

**Comment by munificent** [comment]
> This might be something we need to fix at the platform level (cc @munificent). We've seen multiple cases where an "application package" would like multiple ".packages" -- some for running tests, some for running a bin entry point, some for running a flutter app, some for running a dev-time-only script, etc.

cc @nex3

This is a good idea, though there may be a dragon or two hiding in it.

I'm guessing you wouldn't want these different .packages files to end up with different versions of the same dependency. It wouldn't be super helpful if your app used foo 1.2.3 while your app's own tests used foo 2.3.4!

So what this sounds to me like is:

1. Run a monolithic version solve to get all possible transitive dependencies.
2. Generate separate .packages files from a subset of those to filter out certain dependencies.

I think that's feasible, though it's probably not something we'll have time to work on any time soon.

**Comment by devoncarew** [comment]
I'll drop this PR - we can circle back to it in the context of package:flutter deps.

**Pull request closed without merging**
