### PR TITLE
Remove `new` usage from comments

### PR DESCRIPTION
**Pull request by jamesderlin**
We don't need to use `new` in dartdoc comments to
disambiguate references to classes from references to
constructors.  We can replace `[new T]` with `[T()]` and
`[new T.constructor]` with just `[T.constructor]`.

In some cases, I used `[T.constructor()]` when used
alongside `[T()]`.

See: https://www.dartlang.org/guides/language/effective-dart/documentation#do-use-square-brackets-in-doc-comments-to-refer-to-in-scope-identifiers

### CODE REVIEW

**Comment by Hixie** [comment]
Are we sure this works in dartdocs?

**Comment by Hixie** [comment]
(Using `new` was the recommended way previously, as I understand it. Not sure when this changed.)

**Comment by Hixie** [comment]
LGTM assuming this actually works

**Comment by HansMuller** [comment]
@jamesderlin not sure what to do about this PR. Dartdoc issue #1850 is still open although https://github.com/dart-lang/dartdoc/issues/1850#issuecomment-442561040 suggests a "not very darty" way to refer to constructors instead of classes.

Do you want to forge ahead, resolve the conflicts and update the constructor references, or should we close this PR?

**Comment by jamesderlin** [comment]
I was hoping that dart-lang/dartdoc#1850 would get fixed sometime soon, but I guess I shouldn't hold my breath.  I'll close this for now and repost this when dartdoc is fixed.

**Pull request closed without merging**
