### PR TITLE
Fix `flutter build aar` for modules that use a plugin

### LINKED ISSUE #154371: Problem when running "flutter build aar" using AGP 8.1 + JDK 17
### Steps to reproduce

1. Set up a flutter module with Flutter 22.2 + AGP 8.1 + JDK 17
2. Try to generate the AAR running `flutter build aar`

Note: this project has dependency on other flutter plugins, published in dispub, as well as other 3rd party and Android AAR dependencies.

### Actual results

gives this error:
```
FAILURE: Build failed with an exception.

Where:
Initialization script '/Users/user/flutter_envs/flutter_macos_3.22.2-stable/flutter/packages/flutter_tools/gradle/aar_init_script.gradle' line: 148

What went wrong:
Cannot invoke method dependsOn() on null object. 

```

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

### PR DESCRIPTION
**Pull request by gmackall**
https://github.com/flutter/flutter/pull/151675 bumped module templates to AGP 8.1.

In doing so, I tried to work around a behavior change [that was new in AGP 8.0](https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes):
> AGP 8.0 creates no SoftwareComponent by default. Instead AGP creates SoftwareComponents only for variants that are configured to be published using the publishing DSL.

by using AGP's publishing DSL to define which variants to publish in the module's ephemeral gradle files:
```
android.buildTypes.all {buildType ->
    if (!android.productFlavors.isEmpty()) {
        android.productFlavors.all{productFlavor ->
            android.publishing.singleVariant(productFlavor.name + buildType.name.capitalize()) {
                withSourcesJar()
                withJavadocJar()
            }
        }
    } else {
        android.publishing.singleVariant(buildType.name) {
            withSourcesJar()
            withJavadocJar()
        }
    }
}
```

The problem is that this doesn't get applied to the plugin projects used by the module, so if a module uses any plugin it breaks. This PR fixes that by applying similar logic, but to each project (not just the module's project).

Tested manually with https://github.com/gmackall/GrayAddToApp, and also re-enabled an old test that tested this use case as a part of the PR.

Fixes: https://github.com/flutter/flutter/issues/154371

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by gmackall** [comment]
cc @reidbaker , wip here (ignore if you're already out for the day!)

**Comment by reidbaker** [comment]
Given this area is of high consequence to customers and cleary difficult for us to understand the full impact lets add a test. 

I think a more unit style tests where we run gradle tasks and verify the output contains the tasks we expect could be good enough but would be a new style of test. Or you could add an integration test of a module that had a plugin and confirmed we could build an aar without error. Or both.

**Comment by gmackall** [comment]
Did some manual testing, because I wanted to be sure this was really working.

Followed the docs at https://docs.flutter.dev/add-to-app/android/add-flutter-screen to get a super rough add to app setup going at https://github.com/gmackall/GrayAddToApp, and made sure that the built aar actually works when added as a screen to a host app.

Going to work on adding the test now

**Comment by gmackall** [comment]
Turns out we already had a test that tested this, it was just disabled 🙂 

The reason for disabling seems to be either a flake getting the kotlin gradle plugin, or otherwise a larger problem with the third party `webcrypto` plugin that the test was using. I just removed that plugin - it isn't important for our case (the test already uses a different plugin, the `webcrypto` one is just to additionally test a plugin that uses the ndk).

I the test passed for me locally, so I've re-enabled it (as bringup).

**Review by reidbaker — APPROVED** [review]

**Comment by reidbaker** [comment]
> Turns out we already had a test that tested this, it was just disabled 🙂
> 
> The reason for disabling seems to be either a flake getting the kotlin gradle plugin, or otherwise a larger problem with the third party `webcrypto` plugin that the test was using. I just removed that plugin - it isn't important for our case (the test already uses a different plugin, the `webcrypto` one is just to additionally test a plugin that uses the ndk).
> 
> I the test passed for me locally, so I've re-enabled it (as bringup).

@gmackall can you post a link to the pr that disabled this test?

**Comment by gmackall** [comment]
https://github.com/flutter/flutter/pull/102329

**Pull request merged**
