### PR TITLE
Support querying display refresh rate

### PR DESCRIPTION
**Pull request by liyuqian**

### CODE REVIEW

**Comment by liyuqian** [comment]
CC @devoncarew @kenzieschmoll : here's the updated flutter tool change. According to Chinmay's suggestion, we have to provide a viewId since a single observatory port can have many FlutterViews and they may have different display refresh rate.

**Comment by devoncarew** [comment]
And, IDEs don't currently have knowledge of the viewIds, or that multiple flutter views are running in an isolate. Reload and other actions act per app and per isolate. I think that as is requiring a viewId as a param to the engine call will present an issue for tooling actually using the call -

**Comment by liyuqian** [comment]
@chinmaygarde told me that different views may have different refresh rates. Chinmay also told me that if IDE can do hot-reload, it must have some knowledge about viewId because that's required for triggering hot-reload from service protocols.

BTW, according to what Chinmay told me, an isolate only has a single view and it belongs a a single app. So they're equivalent. What I did wrong before was that I thought that a single observatory port also corresponds to a single app/isolate/view. That's not the case as a single observatory port corresponds to a single vm which may have multiple views/apps/isolates.

**Comment by devoncarew** [comment]
> if IDE can do hot-reload, it must have some knowledge about viewId because that's required for triggering hot-reload from service protocols.

It doesn't have knowledge of the viewids - flutter tools internal implementation code lists all views for an isolate when it gets a hot reload request in (from the IDE), and reloads them all.

The service extension will be running in an isolate - the IDE will know to invoke the extension in that isolate. 

> an isolate only has a single view

I'd suggest that we make the view implement in the request then - that we don't need to pass in the param explicitly, but that it can be determined by the isolate that the extension is running in. How does that sound?

**Comment by devoncarew** [comment]
> but the isolate is a service isolate which is entirely unrelated to any other isolate in a Flutter application

Ah, I'm familiar with service protocol extensions (https://api.dartlang.org/stable/2.1.0/dart-developer/registerExtension.html) that are registered in a specific isolate, and invoked in that isolate. Are the extensions in the engine registered in the service isolate? If so, perhaps the args for the call should include the isolateId containing the view we'd like the target fps for. Or, it could take two optional args - one a viewId, and one an isolateId?

> I don't understand this. Is this in the tooling?

Sorry, that should have read 'implicit': that the viewId is implicit based on the isolate that receives the request.

> Not necessarily, each Flutter application gets its own vsync waiter and the refresh rates may differ.

OK, good to know about the having different refresh rates, even for views on the same device. The case of dynamically changing rates wouldn't be well handled - we'd likely just query once and assume that the target was good for the life of the app. If we end up caring about dynamically changing rates, we should have something like an event for rate changes.

**Comment by liyuqian** [comment]
> I'd suggest that we make the view implicit in the request then - that we don't need to pass in the param explicitly, but that it can be determined by the isolate that the extension is running in. How does that sound?

@devoncarew : Sure, I can do that. Please check the last commit where I added viewId field to the isolate.

**Comment by devoncarew** [comment]
Hi @liyuqian, we may want to VC about this - we'd need more plumbing to get that viewId to tools. I was suggesting allowing the isolateId to be a param into the C++ call, and for that to imply a viewId. I'm traveling now, but I think a short VC would be useful.

**Comment by jonahwilliams** [comment]
Hey @liyuqian, what are your plans with this PR? Happy to chat about any tooling concerns

**Comment by liyuqian** [comment]
@jonahwilliams Thanks for the remind! The plan is to get an LGTM and merge it eventually :smile: But I'm currently not sure who needs this tool (Devon seems to be satisfied with the [engine change](https://github.com/flutter/engine/pull/7002) alone) so I'm a little hesitant to merge it now due to our "laze programming" philosophy.

So I guess that my current plan is to close it and reopen it when we need it.

**Comment by kenzieschmoll** [comment]
It would be great to get this change landed so we can start querying fps from our tools (DevTools and the flutter-intelliJ plugin). @liyuqian, can we revisit this PR?

cc @jacob314

**Comment by liyuqian** [comment]
@kenzieschmoll : sure if you have a use case for it. Jacob previously said that the service protocol alone is enough for DevTools and plugin so I closed this PR.

**Comment by devoncarew** [comment]
Yes, I think tools will just need the service protocol based APIs.

**Comment by kenzieschmoll** [comment]
It sounds like we'd still have the issue where we don't have a view id to pass in the args?

**Comment by kenzieschmoll** [comment]
Was able to get the view id through another RPC! PR here: https://github.com/flutter/devtools/pull/1010 🎉

**Pull request closed without merging**
