### PR TITLE
Revert "Iterate through potential grapheme cluster lengths in text painter"

### PR DESCRIPTION
**Pull request by GaryQian**
…inter (#24797)"

This reverts commit f8964ae250354e655ac81e1be3201ffadd8ce3b2.

### CODE REVIEW

**Comment by GaryQian** [comment]
@jslavitz

**Review by jslavitz — COMMENTED** [review]
LGTM!

**Comment by GaryQian** [comment]
For reference, this is being reverted because of a significant regression of ltr text input on iOS only. It appears to work properly on android.

**Comment by xster** [comment]
Can you create a tracking bug?

**Pull request closed without merging**
