### PR TITLE
Update quiver dependency to 0.26.2

### PR DESCRIPTION
**Pull request by cbracken**
Updates quiver from 0.26.0 to 0.26.2 to pick up strong-mode fixes.

Update was manually applied to get strong-mode fixes required for Dart
SDK 2.0.0, after using flutter update-packages --paths queries to verify
our dependency paths on quiver.

### CODE REVIEW

**Comment by cbracken** [comment]
I believe the long-term plan is to eliminate our dependency on quiver altogether, but in the meantime, this gets us the strong-mode fixes we need for 2.0.0-dev SDKs.

**Review by aam — APPROVED** [review]
Sounds reasonable to me!

**Comment by yjbanov** [comment]
Let's note in the description that this was done manually rather than using the `flutter update-package --force-upgrade` in order to unblock dart 2 efforts. Otherwise, LGTM.

**Comment by yjbanov** [comment]
lgtm

**Review by yjbanov — APPROVED** [review]

**Comment by cbracken** [comment]
Done.

**Comment by Hixie** [comment]
Why did we have to do this manually?

**Comment by cbracken** [comment]
@Hixie `update-packages` doesn't support selective updating, and doing a full run hits dart-lang/sdk#31442

**Comment by Hixie** [comment]
We can pin specific versions by updating the script:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/update_packages.dart#L19

**Pull request merged**
