### PR TITLE
Continue the clipBehavior breaking change

### PR DESCRIPTION
**Pull request by liyuqian**
This follows https://github.com/flutter/flutter/pull/59364 and cl/319911104

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by liyuqian** [comment]
There are some failed tests in the test run of cl/321021912. Investigating...

**Comment by liyuqian** [comment]
This is currently blocked by https://github.com/dnfield/flutter_svg/issues/384. The "customer: dream" needs it to update the code so we can continue this breaking change. CC @dnfield

**Comment by liyuqian** [comment]
Several CLs that "Add clipBehavior to FittedBox, Wrap, and Stack" have landed internally and I'm starting a new test at cl/331657143. I'm only expecting minor AA mismatches in this test. If it's as expected, I'll merge this PR. CC @renyou

**Pull request merged**
