### PR TITLE
Cache the hosted directory under .pub-cache instead of all of .pub-cache.

### PR DESCRIPTION
**Pull request by jacob314**
…

### CODE REVIEW

**Comment by jacob314** [comment]
This might resolve the strange caching issues for the coverage tests.
Bob thinks only caching this subdirectory is safer than caching all of .pub-cache.

**Comment by goderbauer** [comment]
Should we do the same for the Windows build on appveyor (controlled by `appveyor.yml`)?

**Comment by jacob314** [comment]
If this fixes the issue with travis then yes.

**Comment by goderbauer** [comment]
OK.

LGTM.

**Pull request merged**
