### PR TITLE
Simplify ImageStream(Completer).removeListener

### PR DESCRIPTION
**Pull request by xster**

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM, (sorry I missed this!)

**Comment by Hixie** [comment]
That doesn't "simplify" so much as "radically change the behaviour"... this should definitely involve some tests.

**Comment by xster** [comment]
This is the original API intent (https://github.com/flutter/flutter/pull/18424#discussion_r207063494). Unfortunately the original test passed due to the bug Amir pointed out (https://github.com/flutter/flutter/pull/25865#discussion_r244851565) 😭 so the [test](https://github.com/flutter/flutter/pull/20125/files#diff-1f9334e95055c237f00b72bb642684d4R580) is still passing. 

Will add some more tests.

**Comment by Hixie** [comment]
thanks!

**Comment by xster** [comment]
Added a test in #26693

**Pull request merged**
