### PR TITLE
borderRadius param updated in copyWith functions

### LINKED ISSUE #70313: RoundedRectangleBorder.copyWith takes a BorderRadius rather than the constructors BorderRadiusGeometry
Is there a reason that the `copyWith` method of `RoundedRectangleBorder` takes a `BorderRadius`, when the class constructor takes a `BorderRadiusGeometry`? I'm trying to implement a variant of the class, so thought I'd check to see that I'm not misunderstanding something.

https://github.com/flutter/flutter/blob/8874f21e79d7ec66d0457c7ab338348e31b17f1d/packages/flutter/lib/src/painting/rounded_rectangle_border.dart#L39-L40

https://github.com/flutter/flutter/blob/8874f21e79d7ec66d0457c7ab338348e31b17f1d/packages/flutter/lib/src/painting/rounded_rectangle_border.dart#L96-L101

### PR DESCRIPTION
**Pull request by payam-zahedi**
*Update the BorderRadius parameter and change it with BorderRadiusGeometry in copyWith method of OutlinedBorder subclasses.*

Fixes https://github.com/flutter/flutter/issues/70313

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Comment by payam-zahedi** [comment]
Hi @Piinks, I hope you're doing well.
I re-created my last PR, you can find the last one here https://github.com/flutter/flutter/pull/70585
in this PR, I updated the copyWith function of the OutlinedBorder subclasses, and added some test for each of them.

**Review by Piinks — APPROVED** [review]
This LGTM! Thank you for returning and finishing this contribution! 🎉

**Comment by Piinks** [comment]
Can you update your branch with the latest from master? I think that should resolve the failing check here due to an infra issue.

**Comment by payam-zahedi** [comment]
@Piinks thanks for reviewing my 'P'. All the checks have been passed.

**Pull request merged**
