### PR TITLE
[flutter_tools] detect deadlocks from ios-deploy

### PR DESCRIPTION
**Pull request by christopherfujino**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by christopherfujino** [comment]
I tried manually running the ios-deploy command from the terminal (e.g. `/Users/fujino/git/flutter/bin/cache/artifacts/ios-deploy/ios-deploy --id 00008020-00017DA80CC1002E --bundle build/ios/iphoneos/Runner.app --app_deltas build/ios/app-delta --debug --detect_deadlocks 10 --no-wifi --args '--enable-dart-profiling --disable-service-auth-codes --enable-checked-mode --verify-entry-points'`), and I did not see any backtraces. I am not sure if this is the right change to make.

WDYT @jmagman ?

**Comment by jmagman** [comment]
Let me try.

**Comment by jmagman** [comment]
It didn't do anything for me either, even when I sleep the main thread...

**Comment by christopherfujino** [comment]
closing this, as I don't think it will work.

**Pull request closed without merging**
