### PR TITLE
Revert "Implements browser context menu in selectable region"

### PR DESCRIPTION
**Pull request by a-siva**
Reverts flutter/flutter#108909

Reason for revert, it is breaking the Dart builds see [https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8806196862948593777/+/u/test_results/new_test_failures__logs_](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8806196862948593777/+/u/test_results/new_test_failures__logs_)

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by yjbanov — APPROVED** [review]
I'm OK with temporarily reverting this to unblock the roll, but I think the Dart SDK test should be updated to accept this kind of code.

**Review by chunhtai — APPROVED** [review]
LGTM

**Comment by a-siva** [comment]
Closing it as the Dart Analyzer team has temporarily approved the failing test.

**Pull request closed without merging**
