### PR TITLE
Add my name to authors

### PR DESCRIPTION
**Pull request by caseycrogers**
Adds my name to authors.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by caseycrogers** [comment]
@dnfield Could you check this one too?

**Review by dnfield — APPROVED** [review]

**Comment by dnfield** [comment]
This needs a merge to head

**Comment by Piinks** [comment]
I think this may require another update from the master branch to resolve the analyzer.

**Comment by caseycrogers** [comment]
Merged, hopefully CI is happy this time. This has been my most challenging Flutter PR yet XD.

**Comment by fzyzcjy** [comment]
Hi friends, does the `AUTHORS` still accept addition? I have surely contributed a few PRs to flutter, so not sure whether I can open a PR like this one and add the name?

**Comment by dnfield** [comment]
> Hi friends, does the `AUTHORS` still accept addition? I have surely contributed a few PRs to flutter, so not sure whether I can open a PR like this one and add the name?

Feel free to open a PR

**Comment by fzyzcjy** [comment]
@dnfield Thanks!

**Comment by fzyzcjy** [comment]
https://github.com/flutter/flutter/pull/111522 is created

**Pull request merged**
