### PR TITLE
Force plugin transitive dependencies to an ARC compatible version (#1…

### PR DESCRIPTION
**Pull request by stuartmorgan-g**
Cherry-pick https://github.com/flutter/flutter/pull/124349 onto stable (3.10).

CP request at https://github.com/flutter/flutter/issues/126549

### CODE REVIEW

**Comment by XilaiZhang** [comment]
Looks like some of the tests aren't successful. @stuartmorgan could you take a look if a fix is needed? thank you!

**Comment by stuartmorgan** [comment]
Those aren't related to the PR; most look like https://github.com/flutter/flutter/issues/126557

**Comment by XilaiZhang** [comment]
Thanks for the info! I will ask for a LGTM and land this

**Review by ricardoamador — APPROVED** [review]
LGTM

**Pull request merged**
