### PR TITLE
[flutter_tools] hide web server by default

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

The web-server device will only appear if run with -d web-server or with --show-web-server-device

### CODE REVIEW

**Review by nturgut — APPROVED** [review]
LGTM.

Thanks, since long running tests are passing, I assume the integration tests on the engine side will also be fine.

**Comment by yeysus** [comment]
Hi. I think somebody should update the Documentation / Getting Started. https://flutter.dev/docs/get-started/codelab, 2020.01.03, says a Web server should be listed in flutter devices. Now accoding to above it is shown only with flutter devices --show-web-server-device.

**Comment by matthew-carroll** [comment]
+1 for appropriate documentation updates. The getting start guide is currently wrong. It took me a while to find this thread to see that the option I was looking for was hidden.

@jonahwilliams what was the rationale behind hiding this option?

**Comment by DenisDashkevich** [comment]
just curious, why?

**Comment by omatt** [comment]
@matthew-carroll @DenisDashkevich 
Tim explained the rationale behind this feature here https://github.com/flutter/flutter/issues/75088#issuecomment-789253047

**Pull request merged**
