### PR TITLE
Fix for 64-bit MSYS2/mingw-w64 shells

### PR DESCRIPTION
**Pull request by mingwandroid**
.. where uname -s returns e.g.
MINGW64_NT-10.0-19041 t7910-win10 3.1.4-340.x86_64 2020-05-22 08:28 UTC x86_64 Msys

## Description

We are making sure that flutter can be run from within MSYS2 and Git-for-Windows 64-bit shells and not just the 32-bit versions.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM, thanks for submitting this!

**Comment by zanderso** [comment]
@christopherfujino the presubmit checks look unhappy. They're on windows--is this PR the cause?

**Comment by christopherfujino** [comment]
> @christopherfujino the presubmit checks look unhappy. They're on windows--is this PR the cause?

I will investigate

**Comment by jonahwilliams** [comment]
It looks like this PR was branched when we had a bug with downloaded dependencies, rebasing should fix it

**Comment by christopherfujino** [comment]
> It looks like this PR was branched when we had a bug with downloaded dependencies, rebasing should fix it

@mingwandroid can you try rebasing off of the latest master again, which should fix the CI tests.

**Comment by christopherfujino** [comment]
@mingwandroid friendly ping, are you still interested in landing this? If so, it needs to rebased off of the latest upstream master. If not I'll land it in another PR.

**Comment by christopherfujino** [comment]
Actually, gspencergoog implemented this fix in https://github.com/flutter/flutter/pull/59789, which just landed. Still, thanks for opening this PR!

**Pull request closed without merging**
