### PR TITLE
Repaint child view on attach / detach.

### PR DESCRIPTION
**Pull request by alhaad**
@j9brown

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM.

Is it possible to write a test for this?

**Comment by Hixie** [comment]
LGTM

**Comment by alhaad** [comment]
Not sure if there is supporting code to test such a change.
https://github.com/flutter/flutter/blob/master/dev/manual_tests/mozart.dart just runs examples manually.

**Comment by abarth** [comment]
We don't have the ability to run tests in MojoShell.  We could test against mocks of Mozart though.

**Pull request merged**
