### PR TITLE
[integration_test] Support collecting of SkSL

### PR DESCRIPTION
**Pull request by jiahaog**
Passing `--write-sksl-on-exit=sksl.json` to `flutter test` when running in Integration Test mode will collect shaders to the specified file.

- Slightly pushes back when `IntegrationTestDevice.observatoryUrl` completes, so that we avoid duplication of state and keep one instance variable that tracks both the observatory and the vm service
- Modified `FakeVmService` to copy the `requests` list since it will be mutated and is unexpected when reusing the `requests` list over multiple fakes

TODO:
- Verify that the collected shaders actually work
- Multiple tests will generate multiple shader files, probably want to only run this when one test file is specified

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jiahaog** [comment]
@dnfield I managed to wire it up with Integration Tests here. But when I tried reusing the collected SkSL, (following the repro from https://github.com/flutter/flutter/issues/76180), it didn't seem to help eliminate jank, while the manually collected ones through `flutter run --cache-sksl` did for me locally. Do you know if it's possible that with the `IntegrationTestWidgetsFlutterBinding` bindings, the collected SkSL is somehow different from the ones expected in a normal app?

**Comment by dnfield** [comment]
If you compare the JSON output are they different?

**Comment by jiahaog** [comment]
Yes, they are different ([uploaded here](https://gist.github.com/jiahaog/389bdebcb5b23470feeea7ed26929b5d)). I've checked the usual things - running in profile mode on the same iOS physical device, software rendering is disabled, not sure if you have any ideas.

**Comment by dnfield** [comment]
Could it be the extra repaint boundary we added?

**Comment by hazzo** [comment]
I found this draft PR looking for something similar. Sorry to to bother here, but I indeed stumbled with disappointment that compiled shaders extracted from integration test don't reduce jank at all. Why is this?

**Comment by jiahaog** [comment]
Sorry, I haven't had time to follow up and investigate further. As Dan mentioned, it could be due to the [extra repaint boundary](https://github.com/flutter/flutter/pull/70368) that we use to wrap all widgets, or some subtle difference in how the `IntegrationTestWidgetsFlutterBinding` differs from the default `WidgetsFlutterBinding`.

**Comment by hazzo** [comment]
This is a huge bummer. In the documentation [https://flutter.dev/docs/perf/rendering/shader](https://flutter.dev/docs/perf/rendering/shader) it talks how integration tests could make the task of compiling shader cache easier and it does not specifies that the new `integration_test` will run useless the exported shaders. I have a bunch of tests written the new way that you are telling me that I can't use to compile shaders? 

The jank issues have been (since I started with flutter) the worst part of all the delightful experience flutter is. I accepted and realised that compiling shaders is a temporary solution that solves a problem with good results. But been not able to make this automatically brings us way back again to not solving the jank issues at all. Manual shader compilation by playing with the app is not acceptable for large scale applications.

Sorry to repeat this but is a **huge** disappointment.

**Comment by dnfield** [comment]
I strongly suspect it's this code here that's causing trouble: 

https://github.com/flutter/flutter/blob/7d023f0de0896814375b0e9dab2511838b56296c/packages/flutter_test/lib/src/binding.dart#L1833-L1862

@jiahaog - are you set up to easily verify if deleting that code produces the expected shaders or not?

**Comment by jiahaog** [comment]
Thanks Dan for the pointer, I'll try that out and update here

**Comment by hazzo** [comment]
I made a test my self commenting the code you @dnfield you suggested and it does not seem to fixed the issue of janks on first run. I commented the lines in the file in the dart package and then run the integration test. I don't know if that is enough or I have to do an extra step.

**Comment by hazzo** [comment]
Oh I have to say that the compiled shaders JSON file size was reduced on this run with the commented lines. So it seems that something is doing but not enough.

**Comment by dnfield** [comment]
I'm suspicious of that code because it changes what gets drawn and thus might change shaders. We have to see if there are other places too.

**Comment by hazzo** [comment]
It definitively change shaders because size was reduced. My question is, do you consider that this issue will get fixed and integration_test package will be a valid way to generate shaders? Or is safer if I re write them the "old way"? I want to know your opinion on this because now I have some feature tests but if in a couple of months the app grows it would be kind of annoying to re write them the old way.

Thanks!

**Comment by dnfield** [comment]
This is a prolem we want to fix, but I don't have an estimate on when it will be fixed right now.

What do you mean the size is reduced? I thought integration_test was using the native device resolution.

**Comment by hazzo** [comment]
Okey so I will continue doing tests this way and making cache shaders through playing around with the app. 

By reduced size I mean that the json file first was around 217kb and after commenting the code you suggested the json was 191kb.

**Comment by dnfield** [comment]
Ah! yes, a change in size would be expected since you're not compiling the same shaders anymore.

It would be helpful to compare the files against a regular `flutter run --profile`, or a `flutter_driver` based test.

**Comment by dnfield** [comment]
Also, I'm assuming you're running in profile mode on a real device.

**Comment by hazzo** [comment]
Yes, real device and profile.
```
flutter drive --profile --cache-sksl --write-sksl-on-exit flutter_01.sksl.json --driver=test/integration_test_driver.dart --target=test/${TARGET}
```
I'll try to get some time to compare the `.json` files.

**Comment by hazzo** [comment]
I have one doubt that got me thinking. Running multiple `group` tests in a single file, initialising apps `main` method in each group could lead to wrong shaders?

For example: 

```dart
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('smoke test', () {
    testWidgets('test 1', (WidgetTester tester) async {
        app.main();
        await tester.pumpAndSettle();
        await testOne(tester);
    });

    testWidgets('test 2', (WidgetTester tester) async {
        app.main();
        await tester.pumpAndSettle();
        await testTwo(tester);
    });
  });

  group('smoke test logged', () {
    testWidgets('test 3', (WidgetTester tester) async {
        app.main();
        await tester.pumpAndSettle();
        await testThree(tester);
    });
  });
}
```

**Comment by dnfield** [comment]
I don't think so, but it would be worth isolating

**Comment by jiahaog** [comment]
The changes mentioned in https://github.com/flutter/flutter/pull/85118#issuecomment-902972906 did not help. I was able to get the collected shaders with this to work with a few modifications to the integration test:

### Approach 1 - setting the frame policy, using timeouts

https://github.com/jiahaog/hello_flutter_integration_test/blob/2a423a4ea157cec90d395ab27ef7e0663977d283/integration_test/collect_sksl_test.dart#L9-L34

### Approach 2 - Large time dilation value

https://github.com/jiahaog/hello_flutter_integration_test/blob/20d77e8842aa055345ef3a3151b8dda9ecb64469/integration_test/collect_sksl_test.dart#L8-L26

The value of `timeDilation` required for `pumpAndSettle` is fairly large. I suspect that using `pumpAndSettle` is potentially expensive, which relates to https://github.com/flutter/flutter/issues/84994 where frames are missed, preventing the shaders from being cached properly, so we need to set the time dilation to a large value.

---

I'm less favourable to the first approach since that requires the use of timeouts, and changing the frame policy may not be compatible with existing tests, which does not make them portable for both regular testing and collecting of SkSL.

@dnfield any thoughts about the above? For approach 2 we could potentially send a signal from the tool to the app under test to increase the time dilation, though it may not be easy to choose a good value. Then existing tests can be reused without code changes.

Workspace for reference: https://github.com/jiahaog/hello_flutter_integration_test/tree/cache-sksl

**Comment by hazzo** [comment]
> The changes mentioned in https://github.com/flutter/flutter/pull/85118#issuecomment-902972906 did not help. I was able to get the collected shaders with this to work with a few modifications to the integration test:
> 
> 
> 
> ### Approach 1 - setting the frame policy, using timeouts
> 
> 
> 
> https://github.com/jiahaog/hello_flutter_integration_test/blob/2a423a4ea157cec90d395ab27ef7e0663977d283/integration_test/collect_sksl_test.dart#L9-L34
> 
> 
> 
> ### Approach 2 - Large time dilation value
> 
> 
> 
> https://github.com/jiahaog/hello_flutter_integration_test/blob/20d77e8842aa055345ef3a3151b8dda9ecb64469/integration_test/collect_sksl_test.dart#L8-L26
> 
> 
> 
> The value of `timeDilation` required for `pumpAndSettle` is fairly large. I suspect that using `pumpAndSettle` is potentially expensive, which relates to https://github.com/flutter/flutter/issues/84994 where frames are missed, preventing the shaders from being cached properly, so we need to set the time dilation to a large value.
> 
> 
> 
> ---
> 
> 
> 
> I'm less favourable to the first approach since that requires the use of timeouts, and changing the frame policy may not be compatible with existing tests, which does not make them portable for both regular testing and collecting of SkSL.
> 
> 
> 
> @dnfield any thoughts about the above? For approach 2 we could potentially send a signal from the Tool to the test to increase the time dilation, though it may not be easy to choose a good value. Then existing tests can be reused without code changes.
> 
> 
> 
> Workspace for reference: https://github.com/jiahaog/hello_flutter_integration_test/tree/cache-sksl

This means that tests will be longer with a time dilation so big? In my test I had to use several `pumpAndSettle` consecutively as it was the only way to advance some frames. My whole test skips frames abruptly but I did not think that this would affect the generated shaders.

The time delation for some complex animations may be needed to be longer?

**Comment by jiahaog** [comment]
Yes, you may be able to find some success by playing around with the time dilation value.

**Comment by dnfield** [comment]
I think this makes sense - if your test skips frames (perhaps because of shader compilation), it will likely not have shaders.

I agree that time dilation is probably the way to go. I think as long as it's set low enough it should just work right? It sounds like what we basically want is something where the framework gets to render every possible frame of every animation. Time dilation is more or less a timeout in this sense, since we're saying we'll slow things down and that should be enough for the rasterizer to finish its work on every frame. That should work in most cases, but it would be even better if we just had some kind of new frame policy like `neverSkip` or something.

**Comment by jiahaog** [comment]
I'm not sure if frame skipping happens within the framework or engine, would you have a pointer to the code that controls that?

**Comment by dnfield** [comment]
You'd have to do some tracing through the scheduler binding - I think if you look at the way the time dilation logic is handled, it may be possible to instead just adjust it so that it appears that we've always passed a single frame's worth of time (e.g. 16ms).

**Comment by jiahaog** [comment]
Thanks, I'll try that out 🙂

**Comment by Hixie** [comment]
`flutter test` runs the tests in an 800x600 window with dpr=3x, which is extremely different from most phones. Could that be an issue?

(Should we close this PR? It hasn't been touched in a while.)

**Comment by dnfield** [comment]
integration_test overrides those settings to match the size/dpr of the host device.

I think we should close this. The guidance around using SkSL is about to change anyway.

**Pull request closed without merging**
