### PR TITLE
Revert "Fixes in flutter framework code to address the mixin issue raised in Dart issue 31984"

### PR DESCRIPTION
**Pull request by a-siva**
Reverts flutter/flutter#14392

We see a number of runtime strong mode errors with this change, maybe we should land this after we have a FE fix to address the mixin issue.

TBR=mraleph

### CODE REVIEW

**Review by mraleph — APPROVED** [review]

**Comment by jcollins-g** [comment]
How are the flutter tools changes related to the issue?

**Comment by mraleph** [comment]
@jcollins-g I think something is borked in the history. When you looks the cumulative diff then you see that only #14392 was reverted.

**Comment by jcollins-g** [comment]
@mraleph It's unfortunate that github has picked that up and marked all the PRs with "revert" commits.

**Comment by Hixie** [comment]
That's just GitHub being GitHub. The net result is what you want, just ignore the empty commits it creates for some reason when you hit "revert".

**Comment by Hixie** [comment]
Are we expecting the branch/push tests to fail with "Invalid argument(s): Minimum version ("2.0.0-dev.20.0") must be less than maximum ("2.0.0-dev.16.0")."?

**Comment by jcollins-g** [comment]
@Hixie #14426 fixes that, tests just need to be rerun

**Comment by Hixie** [comment]
Ah, excellent.

I don't think rerunning the tests will actually help because the /push and /branch tests, if I understand correctly, run against the actual commit that was uploaded, they don't merge with tip of tree like the /pr ones do. (I'm not sure why they run at all.)

Anyway, to get them green, we should repush the branch after merging with tip of tree.

**Comment by Hixie** [comment]
Or just check it in as-is. The /pr tests are green and that's what matters.

**Comment by a-siva** [comment]
Closing this pull request as the comments in this PR seems to have caused lots of confusion, will commit the revert in a fresh PR.

**Pull request closed without merging**
