### PR TITLE
change BorderRadius to BorderRadiusGeometry

### LINKED ISSUE #27223: Material - BorderRadiusDirectional can't be assigned to parameter type BorderRadius
Might be Similar to https://github.com/flutter/flutter/issues/24257

```
new Material(
    borderRadius: new BorderRadiusDirectional.circular(2.0),
),
```

```
[√] Flutter (Channel master, v1.1.10-pre.205, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 1.1.10-pre.205 at F:\flutter
    • Framework revision e38efc890b (4 hours ago), 2019-01-28 19:55:01 -0800
    • Engine revision 9b6d5031a3
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 a5030ed92f)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at F:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = F:\Android\sdk
    • ANDROID_SDK_ROOT = F:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin version 12.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 162.2924
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 6.0 (API 23) (emulator)

! Doctor found issues in 2 categories.
```

### PR DESCRIPTION
**Pull request by p30arena**
BorderRadiusDirectional can't be assigned to parameter type BorderRadius

Fixes https://github.com/flutter/flutter/issues/27223

### CODE REVIEW

**Comment by p30arena** [comment]
I signed it!

**Review by HansMuller — CHANGES_REQUESTED** [review]
Thanks for the quick fix!

The debugFillProperties method needs to be updated and a regression test is needed (it can be a trivial one). Include a comment at the top of the test's body:

    // Regression test for https://github.com/flutter/flutter/issues/27223

Please also add tests which verify that debugFillProperties works (the current version seems to think that the borderRadius property is an enum?). There are examples in text_field_test.dart.

**Comment by p30arena** [comment]
@HansMuller 

Updated debugFillProperties Conforming to https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/box_decoration.dart#L301

I found no tests for debugFillProperties in https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/material_test.dart Should I add one?

**Comment by HansMuller** [comment]
@p30arena - there are good examples in text_field_test.dart

**Comment by p30arena** [comment]
@HansMuller 
https://github.com/flutter/flutter/commit/5f609c488a05c594fa80921b7da8fe9efe38db7c

**Comment by p30arena** [comment]
@HansMuller 
https://github.com/flutter/flutter/pull/27255

**Pull request closed without merging**
