### PR TITLE
Stocks input field for company name doesn't work

### LINKED ISSUE #1850: Stocks input field for company name doesn't work
I noticed this when implementing https://github.com/flutter/flutter/pull/1847

It seems to be an issue even before my change, so I think the regression happened earlier.

### PR DESCRIPTION
**Pull request by abarth**
We weren't listening to the onChange handler.

Fixes #1850

### CODE REVIEW

**Comment by abarth** [comment]
@collinjackson @Hixie

**Comment by eseidelGoogle** [comment]
I wonder if we can test this with yegors new fancy?

**Comment by abarth** [comment]
@eseidelGoogle We could just test this with a normal unit test.  However, I don't think it's worthwhile.

**Comment by eseidelGoogle** [comment]
Ok

**Comment by Hixie** [comment]
lgtm. the value of testing this would be to set the tone for our examples, fwiw.

**Pull request merged**
