### PR TITLE
Removing minor version from device_os value.

### PR DESCRIPTION
**Pull request by yusuf-goog**
Bug:103733

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jmagman** [comment]
@yusuf-goog `Mac_ios hot_mode_dev_cycle_macos_target__benchmark` failed with no bots, reopened https://github.com/flutter/flutter/issues/104027

**Review by jmagman — APPROVED** [review]
LGTM, let's see if we ever hit issues with inconsistencies between minor versions.

**Comment by jmagman** [comment]
> @yusuf-goog `Mac_ios hot_mode_dev_cycle_macos_target__benchmark` failed with no bots, reopened #104027

Actually this seems related to your PR?  I see 3 results for `iOS-15.1` but none for `iOS-15`.  Can luci understand dropping a minor version for that property?
https://chromium-swarm.appspot.com/botlist?c=id&c=task&c=device_os&c=os&c=status&d=asc&f=os%3AMac-12&f=cpu%3Ax86&f=pool%3Aluci.flutter.try&f=device_os%3AiOS-15.1&k=device_os&s=id

**Comment by keyonghan** [comment]
This will block the tree as `device_os: iOS-15` is not available in luci swarming dimensions.

**Comment by jmagman** [comment]
@yusuf-goog what happened, how did https://ci.chromium.org/p/flutter/builders/try/Mac_ios%20hot_mode_dev_cycle_macos_target__benchmark/1571? pass?

**Comment by jmagman** [comment]
I would have marked requested changes but I thought the failing test would have blocked, but then it passed?  https://ci.chromium.org/p/flutter/builders/try/Mac_ios%20hot_mode_dev_cycle_macos_target__benchmark/1571 claims `device_os | "iOS-15"` but the swarming task says the dimension was `device_os:iOS-15.1` https://chromium-swarm.appspot.com/task?id=5b1ac5b257651710&o=true&w=true

**Comment by keyonghan** [comment]
Sounds the rerun ignores the dimension change. https://github.com/flutter/flutter/issues/104758 to track.

**Comment by yusuf-goog** [comment]
@jmagman can you please look at at the failure, so we can remove the minor version dependency. We have a number of iphones at different versions, and its going to keep capacity low.

**Comment by jmagman** [comment]
To support this PR, we need to extend the bot dimension to cover `iOS-15`.

Filed https://github.com/flutter/flutter/issues/104770

**Pull request merged**
