### PR TITLE
Add a simple golden-file test to `package:integration_test`.

### LINKED ISSUE #72045: Add Skia Gold support to tests for package:integration_test
As mentioned in https://github.com/flutter/flutter/pull/70368#discussion_r522272359, it would be better if we could have Skia Gold integration for the internal package tests.

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/flutter/flutter/issues/72045.

Let's see if I wired this correctly and if `Flutter Gold` knows to check based on the files changed.

### CODE REVIEW

**Comment by cbracken** [comment]
```
╔═╡ERROR #1╞════════════════════════════════════════════════════════════════════
║ /b/s/w/ir/x/w/flutter/packages/integration_test/test/golden_screenshot_test.dart: Files containing golden tests must be tagged using @Tags(<String>['reduced-test-set']) at the top of the file before import statements.
║ See: https://github.com/flutter/flutter/blob/main/docs/contributing/testing/Writing-a-golden-file-test-for-package-flutter.md
╚═══════════════════════════════════════════════════════════════════════════════
```

**Comment by matanlurey** [comment]
Mean.

**Review by cbracken — APPROVED** [review]
May the force be with you.

**Comment by Piinks** [comment]
> if Flutter Gold knows to check based on the files changed.

The flutter-gold check from flutter/cocoon does not consider what files changed, it looks at what test shards are running. It may need to be informed of what test shards package:integration_test runs on for it to guard against PRs landing with images changes.

https://github.com/flutter/cocoon/blob/f12111463c23852d0f83049af985dc43f0f422a4/app_dart/lib/src/request_handlers/push_gold_status_to_github.dart#L126

**Pull request merged**
