### PR TITLE
Change isFlaky to isNew

### PR DESCRIPTION
**Pull request by liyuqian**
To reduce confusions on when to set this flag.

### CODE REVIEW

**Comment by liyuqian** [comment]
@flar : do you think that this would reduce the confusions?

**Review by dnfield — DISMISSED** [review]
Maybe I'm missing some context, but this is actually used for both new and flaky tests.

We assume new tests are flaky until proven otherwise, i.e. by running cleanly for a day or so.

**Comment by dnfield** [comment]
An "old" test can become flaky. A new test might take a very long time to deflake

**Comment by liyuqian** [comment]
@dnfield : that's exactly the confusion that I try to resolve. When an old test becomes flaky, setting this flag to true is not the right thing to do. Instead we should fix it right away. Rerun a flaky test until it passes seems to be better than ignoring it as flaky until someone really breaks it without anyone noticing it.

For example, our framework Cirrus tests are famously known to be flaky. But marking it as flaky and ignoring its result doesn't seem to be the correct thing to do. I'd rather rerun the Cirrus tests, or just fix its flakiness.

**Comment by dnfield** [comment]
My understanding is that some tests should not be marked flaky even if they are.  But some tests may be worth marking flaky while we figure out how to fix them.  The age of the test isn't necessarily correlated with that.

We should probably make some citrus tests flaky, but right now we would have to mark all of citrus flaky to do that, which doesn't seem wise.

**Review by tvolkert — CHANGES_REQUESTED** [review]
This info is also used in the Cocoon backend, so it can't be changed here without a phased rollout.  It's probably not worth the churn since we'll be re-doing a lot of this when we re-architect the Cocoon backend anyway.

**Comment by flar** [comment]
> My understanding is that some tests should not be marked flaky even if they are. But some tests may be worth marking flaky while we figure out how to fix them. The age of the test isn't necessarily correlated with that.

This is my take on the matter. If a test is failing because we broke it then it should be marked fixed. If a test is failing because it was not set up to be reliable then the problem is on the test, not on the new fixes that are trying to land while it is poorly written. Finally, if a test is flaky because the hardware or infra environment is not set up well for it - a similar evaluation to the test being wrong, but a different person responsible to fix it.

Also, if a test is flaky then the onus should be on the person who wants the test evaluated to fix it. Leaving it as blocking lets them be lax about getting around to diagnosing and fixing the test. Marking it as flaky means it is on them to fix it and get it back into a state where it is reasonable to expect other people to halt their work if it fails.

I don't think a poorly written test, for example and I count a test that doesn't work well in the test environment as some form of "poorly written", should block work from developers who are trying to move the product forward. That's all on the test writer or owner to deal with.

**Comment by Hixie** [comment]
Once a test is working, then it shouldn't become flaky again. If it does, we should fix it. It's not the test writer's job, it's all of our job. If it's so poorly written that it's not giving us a useful signal then the solution is to delete the test, not mark it flaky.

Having disabled tests that still run has _numerous_ problems:

* It uses very expensive resources to run uselessly. We don't have enough capacity as it is. We can't waste it on bad tests.
* It makes the dashboard look red when it's green. This is a morale issue as well as just generally confusing.
* It reduces confidence in tests in general.
* Worst of all, it creates a culture of ignoring tests that fail because "just mark it flaky".

We have had numerous tests recently fail legitimately that we just ignore because the failure is not reported 100% of the time, it's 90% failing, or 50% failing. These are not passing tests that erroneously fail, they are failing tests that erroneously pass. THEY SHOULD CLOSE THE TREE UNTIL WE FIX THEM. They should not be causing us to mark them flaky.

**Comment by liyuqian** [comment]
@tvolkert : is https://github.com/flutter/cocoon/pull/406 enough on the cocoon side? We don't have to change all "flaky" in the cocoon. Just changing the yaml parsing seems to be enough.

**Comment by tvolkert** [comment]
Following on @Hixie's comment in https://github.com/flutter/flutter/pull/39856#issuecomment-528641594, tbh, I'd rather we get rid of the flaky marker altogether and just fix the tests, or evict them if they're not ready yet.

**Comment by liyuqian** [comment]
@tvolkert : right, that's our strategy. But there still needs to be a flag for new tests though.

**Comment by tvolkert** [comment]
> there still needs to be a flag for new tests though

Why?

**Comment by flar** [comment]
> > there still needs to be a flag for new tests though
> 
> Why?

Until a test runs in the devicelab for a few runs and establishes a profile we don't have any data to establish a baseline for it.

But, those tests should have (I think) 0's for baseline so perhaps we should consider them "new" if their baseline and goal are both 0. Then baselining it would establish its "not newness" without a flag?

**Comment by liyuqian** [comment]
@tvolkert : when we write a new test, we don't want the tree to be red because of it. We only want the tree to be red when a test is proven to be working properly. One might argue to delete the new test immediately if it doesn't pass, and reland after a fix. But that seems to be too costly as a new test would usually require N tries to make it work. Requiring deletion/reverting after each failure means 2N-1 commits (and their pre-submit tests, and post-submit tests). I guess that's due to the fact that we don't have good presubmit tests to cover a device lab test. Of course, removing the flag and just let each new test immediately revert after a failure is an option. @Hixie : how do you think about the alternative?

@flar : the `new` flag here is not used for baselines. The tree won't be red due to the lack of baselines. Also, not all device lab tests generate a metric that needs a baseline.

**Comment by flar** [comment]
> @tvolkert : when we write a new test, we don't want the tree to be red because of it. We only want the tree to be red when a test is proven to be working properly.

Why isn't the test vetted before it is pushed?

**Comment by liyuqian** [comment]
Because we currently don't have a way to exercise all the scripts of the device lab locally without merging the change. It would be nice if one can change that so the test can be vetted beforehand. (Note that we do have a way to run a device lab test locally, but that doesn't involve all the scripts of reading and scheduling that test to the correct host/device via manifest.)

**Comment by tvolkert** [comment]
> Because we currently don't have a way to exercise all the scripts
> of the device lab locally without merging the change.

We don't have a way to locally say "run all the devicelab tests against my change", but we do have a way to run an individual test, which presumably would cover the case of adding a new test -- https://github.com/flutter/flutter/tree/master/dev/devicelab#running-tests-locally

**Comment by flar** [comment]
So @tvolkert is pointing out a mechanism to vet a test ahead of time, but even if we didn't have that mechanism I still don't see why it would be so common for a new test to have to go through "N tries to make it work". Tests that don't necessarily work on all platforms should be relatively rare and it shouldn't take multiple attempts to deal with them on the off chance that one comes up.

**Comment by liyuqian** [comment]
As I mentioned before:
> (Note that we do have a way to run a device lab test locally, but that doesn't involve all the scripts of reading and scheduling that test to the correct host/device via manifest.)

And I've mentioned
> Of course, removing the flag and just let each new test immediately revert after a failure is an option. @Hixie : how do you think about the alternative?

At least, I think we all agree that changing isFlaky to isNew is an improvement. The only question is whether it's worth to further remove the flag altogether? While we're discussing the question, maybe we can first change isFlaky to isNew. And if the answer to that question is yes, we can easily just forbid that flag in our manifest parser.

**Comment by tvolkert** [comment]
I don't think changing isFlaky to isNew is worth the churn.  It's still not clear to me what problem it solves.

**Comment by liyuqian** [comment]
@tvolkert : how do you think about the alternative option to remove the flag altogether, and also delete the currently "flaky" tests `run_without_leak_linux`, `run_without_leak_mac`, and `macos_chrome_dev_mode`? (CC the creator of those tests: @dnfield @jonahwilliams )

**Comment by tvolkert** [comment]
Those tests were already removed in https://github.com/flutter/flutter/pull/40155.  I'm supportive of removing isFlaky altogether.

**Comment by dnfield** [comment]
I'm fine with removing the run_without_leaks tests.  I think we've thoroughly demonstrated that we leak processes at this point and AFAIK no one is actively working on it.

**Comment by Hixie** [comment]
How do you add a new test without turning the tree red if we don't have this flag?

**Comment by liyuqian** [comment]
I think @tvolkert and @flar 's suggestion is to immediately delete/revert the new test if the tree turns red because of it.

**Comment by tvolkert** [comment]
> I think @tvolkert and @flar 's suggestion is to immediately delete/revert the new test if the tree turns red because of it.

Combined with running it locally before checking in.

**Comment by Hixie** [comment]
Historically neither of those have been sufficient to avoid pain.

**Comment by tvolkert** [comment]
Are there instances of tests that we expected to pass but failed upon initial check-in, that we then fixed and removed the flaky marker from?  I've seen tests that pass upon first check-in, and tests that fail upon first check-in that continue to fail after checkin.

**Comment by Hixie** [comment]
Almost every test I've been involved with (either writing or working with someone who was writing it) failed on initial checkin but got fixed a few commits later, usually to fix things that a local run could not catch, such as the PATH being different, or the OS version being different, or some binary not being available on the devicelab, or the version of Xcode being different, or Xcode configuration being wrong or different, or any number of other similar issues.

**Comment by tvolkert** [comment]
Then what about having a server-side `isNew` flag that can be flipped only 1-way (to not new)?  All new tests would be set to `isNew` automatically by Cocoon, and the UI would support the 1-way flip to not new...

**Comment by Hixie** [comment]
We could do that. Seems a bit over-engineered though.

**Comment by liyuqian** [comment]
Close this for now as it seems that our default action is to
1. not use "flaky" field, 
2. revert the new test if it's not passing.

It is a little annoying (see, e.g., the 5 commits revert/reland chain https://github.com/flutter/flutter/pull/41578), but acceptable.

**Comment by Hixie** [comment]
I do not believe that should be our behaviour and it doesn't seem to be what is described in our docs last I checked.

**Comment by tvolkert** [comment]
We can absolutely still use the flaky field for newly added tests.

See my last comment above (https://github.com/flutter/flutter/pull/39856#issuecomment-530868273) -- as long as this is rolled out in a non-breaking way, I'm ok with making the change.

**Pull request closed without merging**
