### PR TITLE
Update android templates to use target sdk 34

### PR DESCRIPTION
**Pull request by gmackall**
We should always target the newest, and 34 is the newest. This isn't a requirement yet (like it is for 33+) but presumably it will be made required in the nearish future.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by gmackall** [comment]
I also want to bump the min in our templates to 28, in light of https://github.com/flutter/flutter/issues/63559, but that seems to be a bit more complicated because:
1. I wouldn't want to do it for the ephemeral `.android` directory that gets used for add to app, because that directory gets regenerated constantly and so (unlike our other templates) it isn't a "suggestion", 
2. having the template for regular apps and modules be different is causing test failures that would require some larger changes to fix.

So I would do that in a follow up PR

**Review by johnmccutchan — APPROVED** [review]
Please update the title to not include the "and min sdk 28" as that isn't in this CL.

**Comment by gmackall** [comment]
> Please update the title to not include the "and min sdk 28" as that isn't in this CL.

Whoops, changed. Thanks for the catch!

**Comment by matanlurey** [comment]
test-exempt: changes tests/covered by existing tests.

**Comment by gmackall** [comment]
Google testing had infra failure, and this is all gradle stuff, so overriding the check

**Pull request merged**
