### PR TITLE
Update gallery assets version with optipng

### PR DESCRIPTION
**Pull request by xster**

### CODE REVIEW

**Comment by willlarche** [comment]
0.1.4? I don't see that version. Did you publish it? https://pub.dartlang.org/packages/flutter_gallery_assets#-versions-tab-

**Review by willlarche — APPROVED** [review]

**Comment by willlarche** [comment]
I went ahead and published the package. Doing some Android testing right now. Looks great on iOS.

**Comment by willlarche** [comment]
Looks good on Android.

**Comment by xster** [comment]
I'll rerun the tests

**Pull request merged**
