### PR TITLE
CupertinoAlertDialog title and content fix

### PR DESCRIPTION
**Pull request by Adem68**
## Description

CupertinoAlertDialog font weight and padding fixed. Now looks like SwiftUI.

## Related Issues

#49715  
https://github.com/flutter/flutter/issues/49492

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behaviour with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hi @Adem68 welcome! 🎉  Thank you for the contribution. 
In order to merge this, we'll need to have a test that checks the expected behavior.

**Comment by Adem68** [comment]
Hi Kate (@Piinks),

Thanks for message 😊. I was tested on stable channel when i was openened pr. It was worked. Today i tested on master channel. I found the bug; `.SF UI Display` doesn't take fontWeight parameter if you try fontWeight with `.SF UI` it will work

**Review by Piinks — CHANGES_REQUESTED** [review]
Thanks for the confirmation! We will need a test though here in your PR. Tests confirm everything is working the way it should and make sure we don't un-do the fix you have made at a later date. There is some helpful guidance in [write test fix bug](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#write-test-find-bug) and [running and writing tests](https://github.com/flutter/flutter/wiki/Running-and-writing-tests).

**Comment by Adem68** [comment]
I closed pr. Because it couldn't solve problem. Thanks for helping to me.

**Pull request closed without merging**
