### PR TITLE
[WIP] place ResidentRunner artifacts in isolated directory

### LINKED ISSUE #18566: Crash when Hot Restarting on two devices at the same time: Invalid kernel binary: Indicated size is invalid.
I'd like to support running a Flutter app on multiple devices concurrently (from an editor). @devoncarew has seen issues running multiple instances simultaneously that may be related to a shared build folder so I've been trying this out to see if I can repro some issues.

The first thing I found was that if I Hot Restart on both devices (one iOS Simulator, one Android Emulator) at the same time, I get a crash on the Android one (`Invalid kernel binary: Indicated size is invalid.`).

A possible fix may be having a subfolder in `build` per-device. I'm not sure whether all the places that assume ` build` folder are in this repo, or may go into the `engine` repo; but I'll do some digging to see what I can find.

```
E/DartVM  ( 7774): ../../third_party/dart/runtime/vm/kernel_binary.cc: 55: error: Invalid kernel binary: Indicated size is invalid.
E/DartVM  ( 7774): Dumping native stack trace for thread 1e79
E/DartVM  ( 7774):   [0xd2b3745e] Unknown symbol
E/DartVM  ( 7774):   [0xd2b3745e] Unknown symbol
E/DartVM  ( 7774):   [0xd2d2b1a1] Unknown symbol
E/DartVM  ( 7774):   [0xd2d96d17] Unknown symbol
E/DartVM  ( 7774):   [0xd2a2f6da] Unknown symbol
E/DartVM  ( 7774):   [0xd2a2f9ef] Unknown symbol
E/DartVM  ( 7774):   [0xd2d2916d] Unknown symbol
E/DartVM  ( 7774):   [0xd2488313] Unknown symbol
E/DartVM  ( 7774):   [0xd2497a70] Unknown symbol
E/DartVM  ( 7774):   [0xd24977a7] Unknown symbol
E/DartVM  ( 7774):   [0xd2495fb5] Unknown symbol
E/DartVM  ( 7774):   [0xd2495ca4] Unknown symbol
E/DartVM  ( 7774):   [0xd2495c30] Unknown symbol
E/DartVM  ( 7774):   [0xd249bc12] Unknown symbol
E/DartVM  ( 7774):   [0xd249e63e] Unknown symbol
E/DartVM  ( 7774):   [0xd249df65] Unknown symbol
E/DartVM  ( 7774):   [0xd249df9f] Unknown symbol
E/DartVM  ( 7774):   [0xd2490d66] Unknown symbol
E/DartVM  ( 7774):   [0xd2463721] Unknown symbol
E/DartVM  ( 7774):   [0xd24632df] Unknown symbol
E/DartVM  ( 7774):   [0xd2467e7f] Unknown symbol
E/DartVM  ( 7774):   [0xebedaaf8] android::SimpleLooperCallback::handleEvent(int, int, void*)
E/DartVM  ( 7774):   [0xebedb937] android::Looper::pollInner(int)
E/DartVM  ( 7774):   [0xebedb4d7] android::Looper::pollOnce(int, int*, int*, void**)
E/DartVM  ( 7774):   [0xe5654f11] ALooper_pollOnce
E/DartVM  ( 7774):   [0xd2467db9] Unknown symbol
E/DartVM  ( 7774):   [0xd246395a] Unknown symbol
E/DartVM  ( 7774):   [0xd2462bbd] Unknown symbol
E/DartVM  ( 7774):   [0xd2465f68] Unknown symbol
E/DartVM  ( 7774):   [0xeb176446] Unknown symbol
E/DartVM  ( 7774):   [0xeb1255dc] Unknown symbol
E/DartVM  ( 7774): -- End of DumpStackTrace
F/libc    ( 7774): Fatal signal 6 (SIGABRT), code -6 in tid 7801 (Thread-2), pid 7774 (les.hello_world)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:8.1.0/OSM1.180201.018/4662058:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
pid: 7774, tid: 7801, name: Thread-2  >>> io.flutter.examples.hello_world <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    eax 00000000  ebx 00001e5e  ecx 00001e79  edx 00000006
    esi d23ceaac  edi 00001e5e
    xcs 00000023  xds 0000002b  xes 0000002b  xfs 0000006b  xss 0000002b
    eip ef2f0af0  ebp d23cecd8  esp d23ce5d8  flags 00000296
backtrace:
    #00 pc 00000af0  [vdso:ef2f0000] (__kernel_vsyscall+16)
    #01 pc 0001edf8  /system/lib/libc.so (syscall+40)
    #02 pc 0001f073  /system/lib/libc.so (abort+115)
    #03 pc 0070ab3a  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #04 pc 009c6d1e  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #05 pc 0065f6d9  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #06 pc 0065f9ee  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #07 pc 0095916c  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #08 pc 000b8312  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #09 pc 000c7a6f  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #10 pc 000c77a6  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #11 pc 000c5fb4  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #12 pc 000c5ca3  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #13 pc 000c5c2f  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #14 pc 000cbc11  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #15 pc 000ce63d  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #16 pc 000cdf64  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #17 pc 000cdf9e  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #18 pc 000c0d65  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #19 pc 00093720  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #20 pc 000932de  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #21 pc 00097e7e  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #22 pc 00014af7  /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+39)
    #23 pc 00015936  /system/lib/libutils.so (android::Looper::pollInner(int)+982)
    #24 pc 000154d6  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+118)
    #25 pc 0000ff10  /system/lib/libandroid.so (ALooper_pollOnce+96)
    #26 pc 00097db8  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #27 pc 00093959  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #28 pc 00092bbc  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #29 pc 00095f67  /data/app/io.flutter.examples.hello_world-EcHStWouG_XfGa7bPLFpNA==/lib/x86/libflutter.so
    #30 pc 00071445  /system/lib/libc.so (__pthread_start(void*)+53)
    #31 pc 000205db  /system/lib/libc.so (__start_thread+75)
    #32 pc 0001ec16  /system/lib/libc.so (__bionic_clone+70)
Lost connection to device.
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

By default, the ResidentRunner will output incremental dill files at the same location regardless of how the build was run or the connected devices. This works when there is a single tool process, but multiple tool process sharing the same directory will all attempt to read and write to the same file. The build system Environment is used to create a unique-ish subdirector where this process would be the only user. The inputs to the name are the identifiers of the connected devices, the mode, and the target file.

This approach is preferable to something like a lockfile, because that doesn't prevent different applications (say, target files) from clobbering each other.

Fixes https://github.com/flutter/flutter/issues/18566

### CODE REVIEW

**Comment by jonahwilliams** [comment]
cc @DanTup give this a try and let me know  if it fixes the issues in vscode

**Comment by DanTup** [comment]
@jonahwilliams Android emulator + iOS simulator seem to work great now! 👍 🎉

There is still an issue when running two iOS simulators, though I'm not sure if it's our limitation or something like Xcode?

> error: unable to attach DB: error: accessing build database "/Users/dantup/Library/Developer/Xcode/DerivedData/Runner-cqvvjujagpbkjpcfmgxfzeqtjdep/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.
> 
> note: Using new build systemnote: Planning buildnote: Constructing build description
> 
> Could not build the application for the simulator.
> Error launching application on iPad Pro (10.5-inch)

**Comment by jonahwilliams** [comment]
Thats a limitation if we use the device identifier as a key, since i think it will be the same for multiple emulators. We could fold the pid in as well somehow...

**Comment by jonahwilliams** [comment]
Oh I should read the error more closely. Might be an issue with multiple sims, I'll look into it

**Comment by jonahwilliams** [comment]
Closing for now, see https://github.com/flutter/flutter/issues/18566#issuecomment-523268902

**Pull request closed without merging**
