### PR TITLE
Update AUTHORS with couple contributors.

### PR DESCRIPTION
**Pull request by AlexV525**
## Description

Recently I just found out that the contributor can update the `AUTHORS` file if they were contributed to flutter's repo, so I reached out my friends who has their contributions with flutter to update the file together (makes it not awkward if there's only one person).

## Related Contributions (Most recent)

@chenglu #56685
@Vadaski #45750
@zmtzawqlp #58746 
@CaiJingLong #21142
And me #58686 

I'm wondering if we can use Chinese name for the file, if not the current changes would be okay. :)

And I'll bring them to here and thumb up the post to ensure they are acknowledged and support this request.

### CODE REVIEW

**Comment by shihaohong** [comment]
I don't see a problem with using your Chinese names in the `AUTHOR.md` file. @Hixie do you have any thoughts?

**Review by shihaohong — APPROVED** [review]
LGTM

**Comment by flutter-github-sync** [comment]
Started Google testing for this PR

**Comment by AlexVincent525** [comment]
Waiting for feedback from others...

**Comment by flutter-github-sync** [comment]
Google testing passed!

**Comment by Hixie** [comment]
@AlexVincent525 Please use whatever name you identify as in the AUTHORS file so long as it doesn't include a newline character. :-) The files are encoded as UTF-8. You should definitely feel free to use Chinese names.

**Comment by AlexVincent525** [comment]
Thanks, and now it's ready for merge. 😆

**Comment by flutter-github-sync** [comment]
Started Google testing for this PR

**Comment by flutter-github-sync** [comment]
Google testing passed!

**Comment by flutter-github-sync** [comment]
Started Google testing for this PR

**Comment by flutter-github-sync** [comment]
Google testing passed!

**Pull request merged**
