### PR TITLE
Reland "Add support for Dart Development Service (DDS) in Flutter Tools (#61276)"

### PR DESCRIPTION
**Pull request by bkonyi**
This reverts commit 38fe887342f6c6bf40dd2c25442b892644e11a39.

Fourth time's the charm, right?

Same change as the last PR, rebased. A new test or package was added between the time of my last rebase and my last landing attempt so the dependency updates broke the new package.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM Good Luck

**Comment by bkonyi** [comment]
> LGTM Good Luck

Thanks. One day this will stick, I promise...

**Comment by jonahwilliams** [comment]
You've cursed this feature by mentioning when it would be done in the all hands

**Comment by bkonyi** [comment]
> You've cursed this feature by mentioning when it would be done in the all hands

Apparently... GitHub needs built-in support for '😭' reactions.

**Pull request merged**
