### PR TITLE
[flutter_tools] remove dwarf stripping now that linked issue is fixed

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description
--strip should now correctly work for assembly snapshots.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
cc @dnfield , besides the additional flags, I don't see any tests to remove for the dwarf stripping. Am I missing them somewhere?

**Comment by dnfield** [comment]
I think if this breaks anything it will be in the devicelab.

**Comment by jonahwilliams** [comment]
Building with bitcode would fail right? Otherwise I can always verify with some grepping

**Comment by dnfield** [comment]
Yeah, try building a bitcode enabled project and archiving it for distribution.

**Comment by jonahwilliams** [comment]
Locally I can see a DWARF section, but it appears to be in the engine binary:

```
jonahwilliams-macbookpro2:iphoneos jonahwilliams$ grep -r "DWARF" .
Binary file ./Runner.app/Frameworks/Flutter.framework/Flutter matches
jonahwilliams-macbookpro2:iphoneos jonahwilliams$ 
```

Is this expected?

**Comment by dnfield** [comment]
The code you're changing did not modify the engine binary so it should be fine.

**Review by dnfield — APPROVED** [review]
LGTM

**Pull request merged**
