### PR TITLE
Add dart fix for DragAnchor deprecation

### PR DESCRIPTION
**Pull request by Piinks**
Deprecated in https://github.com/flutter/flutter/pull/79160

Related: 
- https://github.com/flutter/flutter/issues/80552
- https://github.com/flutter/flutter/issues/74908

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Piinks** [comment]
> It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need an exemption to this rule, contact Hixie on the #hackers channel in [Chat](https://github.com/flutter/flutter/wiki/Chat).
> 
> If you are not sure if you need tests, consider this rule of thumb: the purpose of a test is to make sure someone doesn't accidentally revert the fix. Ask yourself, is there anything in your PR that you feel it is important we not accidentally revert back to how it was before your fix?
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.

The tests for dart fix are included, although not detected by the bot. :)

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by domesticmouse** [comment]
Trailing LGTM. Any predictions on when this should show up in dev or beta channel?

**Comment by Piinks** [comment]
> Trailing LGTM. Any predictions on when this should show up in dev or beta channel?

This I do not know. Lately I think the master->dev roll has been landing about every other day - whether it is published to dev depends on if there are any issues found during the roll. I think beta usually tries to roll monthly. 
https://github.com/flutter/flutter/wiki/Flutter-build-release-channels has more info :)

**Pull request merged**
