### PR TITLE
Add NavigatorState.(add|remove)Observer

### LINKED ISSUE #64442: Add NavigatorState.addObserver and NavigatorState.removeObserver
Use case: in an event handler in a descendant of the navigator (deep in my app), I want to register a navigator observer and monitor navigator activity.

NavigatorState already maintains a stateful list of "effective observers" (a possible augmentation of the widget's observers).  This makes it fairly easy to add the ability to dynamically register navigator observers from lower down in the tree -- enabling callers to do the following:

```dart
NavigatorObserver observer = MyNavigatorObserver();
Navigator.of(context).addObserver(observer);
...
Navigator.of(context).removeObserver(observer);
```

### PR DESCRIPTION
**Pull request by tvolkert**
## Description

This adds `NavigatorState.addObserver` and `NavigatorState.removeObserver`, to allow
callers to dynamically add and remove observers to the navigator.  This should prove useful
to stateful widgets deeper in the app's widget hierarchy that want a hook into the navigator's
observers list.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/64442

## Tests

I added the following tests:

* A test of adding an observer from a descendant widget (and the observer getting properly notified)

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

**Review by HansMuller — COMMENTED** [review]
I think the reason for leaving this API out was to discourage the use of the NavigatorObserver API, which  was originally added to enable Hero transitions. @goderbauer or @Hixie can probably shed more light on this.

**Comment by tvolkert** [comment]
I discussed it with @goderbauer - I don't see another way to handle my use case.

In the future, when we support multi-window, we're likely going to need a similar `Window.addWindowListener()` (or `Window.addWindowObserver()` - not sure when we use "listener" vs "observer") API to be notified when child windows are opened/closed, but until we support multi-window, this API satisfies that need.

**Comment by Hixie** [comment]
NavigatorObserver has caused us nothing but trouble. I'm very reluctant to add more ways to observe the navigator. What's the use case?

**Comment by tvolkert** [comment]
Discussed the use-case with @Hixie.  tldr: while the use case is valid, it can be accomplished by hooking into the observer list at the navigator level, so we'll close this PR so as to not introduce more ways to use NavigatorObserver (something we're trying to get away from).

**Pull request closed without merging**
