### PR TITLE
[flutter_releases] Flutter Stable 2.0.3 Framework Cherrypicks

### PR DESCRIPTION
**Pull request by christopherfujino**
## Scheduled Cherrypicks
* [x] Engine roll
  * https://github.com/flutter/engine/pull/25055
* [x] Fix Autovalidate enum references in fix data
  * https://github.com/flutter/flutter/commit/08bc8e69ce43ff9e5103945ad019a6c9486be7ee
  * Original author: @pq 
* [x] NoSuchMethodError: The method ‘cancel’ was called o null at AnsiSpinner:finish
  * https://github.com/flutter/flutter/commit/8f3a6245f014f4983e48a5be46732808c9d525e2
  * Original author: @jmagman 

## Test-Only Cherrypicks
* [x] #75648 ios_platform_view_tests fail when device is rotated in landscape and #75467 flutter_gallery__transition_perf_e2e_ios fails when device is rotated in landscape
  * https://github.com/flutter/flutter/commit/ac13cd35a55b16920b4ef90224e178dd2ea2dea2
* [x] complex_layout_ios__start_up brings up a system dialog that makes next tests fail #75048
  * https://github.com/flutter/flutter/commit/91aad2bb061ce14f14e8a3d6f67f747f9738246f
* [x] Mac/iOS tests are timing out when rebooting devices
  * https://github.com/flutter/flutter/commit/4597b51cbc2121ad8bcfd38cb925a497867e80cc

### CODE REVIEW

**Review by kf6gpe — APPROVED** [review]
LGTM. Thanks!

**Review by jmagman — APPROVED** [review]
https://github.com/flutter/flutter/pull/75679 and the test-only changes LGTM!

**Comment by christopherfujino** [comment]
try jobs queued and not running because I need to cp https://github.com/flutter/flutter/pull/78078

**Review by linhzz999 — COMMENTED** [review]
Ok

**Pull request merged**
