### PR TITLE
Add debugIsInsideBuild

### LINKED ISSUE #49505: Add a way to know if a `ComponentElement` is executing its build method or not
## Use case

`provider`'s upcoming feature, `select`, is a way to consume InheritedWidgets that works only inside the `build` method.

Trying to call `select` inside other life-cycles (including `didChangeDependencies`) is not supported.

To make sure that people do not mistakenly still use it in a place where it shouldn't be used, `provider` would like to add an "assert" that fails if the `BuildContext` is not in the progress of building.

## Proposal

This would be implemented through a debug-only flag on `ComponentElement`.
Basically, within `build` that flag would be true, and outside of `build` it wouldn't.

Then, `select` could do:

```dart
extension Select on BuildContext {
  R select<T, R>(R cb(T value)) {
    assert(this is ComponentElement && this.debugIsInsideBuild);
    ...
  }
}
```

### PR DESCRIPTION
**Pull request by rrousselGit**
## Description

Expose a debug-only flag on `ComponentElement` that tells whether the method `build` is currently running or not.

## Related Issues

closes #49505

## Tests

- ComponentElement.debugIsInsideBuild is true inside build and false outside
- ComponentElement.debugIsInsideBuild is false inside ErrorWidget.builder

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by dnfield — DISMISSED** [review]
How is this different from `debugBuilding`?

**Comment by rrousselGit** [comment]
As stated in the issue:

debugBuilding is global for the entire tree

This flag is specific to a given element and represent StatelessWidget.build/StatefulWidget.build, which means it is false during initState/didChangeDependencies/...

**Comment by goderbauer** [comment]
@dnfield @rrousselGit After the discussion in the associated bug: Can we close this in favor of #49527?

**Comment by rrousselGit** [comment]
Hum, no

#49527 doesn't solve the issue. I'll think on how to update the flag to work with these changes

**Comment by dnfield** [comment]
Can you explain why the distinction between build and didChangeDependencies matters still?

Can you explain why something would ever need this information?  Wouldn't a user know if they were in their own build or an error widget build?

**Comment by rrousselGit** [comment]
It's for libraries, to use inside assertions.

That's the same story as to how we can't call `dependOnInheritedWidgetOfExactType` inside `initState` – it works based on a flag similar to this one.

But as an external package, we currently have no mean to implement an exception similar to the one in `dependOnInheritedWidgetOfExactType`.

A more open solution that is not specific to `build` might be to have an enum instead:

```dart
enum StateLifecycle {
  none,
  initState,
  didChangeDependencies,
  build,
  ...
}

class StateElement extends ComponentElement {
  ...
  StateLifecycle get debugCurrentLifecycle => ...
}
```

**Review by dnfield — CHANGES_REQUESTED** [review]
Unfortunately, I don't think we should add this API.

It is likely to be confusing for consumers, and increase the likelyhood that some optimization we wish to do that is today not a breaking change will become a breaking change down the line.

It would help if there was some clearer, concrete reason to describe why exposing this is important.  It seems likely to me that there would be some useful way of resolving the use case behind this without exposing as much of the internals of the framework.

**Comment by rrousselGit** [comment]
> It is likely to be confusing for consumers

Consumers won't see this. They see the BuildContext interface, which doesn't expose the flag. 

> Increase the likelyhood that some optimization we wish to do that is today not a breaking change will become a breaking change down the line.

Any example? 
Because as long as StatefulElement calls State.build, this flag should be able to be implemented.

> It would help if there was some clearer, concrete reason to describe why exposing this is important

There are already quite a few of such flag inside the existing implementation. Like _StateLifecycle or BuildOwner.debugIsBuilding.
It sounds unfair to ask for something different when the framework already does the exact same thing in many places.

**Comment by rrousselGit** [comment]
Also, the breaking change argument feels off to me. 

This is a debug-only flag. Removing it would have no impact on the behavior of an app. If there's ever a need to remove this flag (which is almost impossible to happen considering the implementation), then it is same to remove.

**Comment by dnfield** [comment]
The breaking change argument is because of our breaking change policy. Every API surface we introduce is a new surface that we have to support, and a surface we should expect that some customer will use. If we remove or change the behavior of that surface, and a customer has contributed a test, it becomes a breaking change.  Suddenly an optimization we'd like to do goes from being a simple fix that is transparent to end users to a longer process that requires a deprecation plan and mitigations for customers who have come to depend on the behavior.

I would be happy to look at a design doc around the ideas behind this work - I think that would be more helpful than continuing the discussion here at this point, and could help get some more voices to weigh in on this issue and what approaches make the most sense for the intended use cases.  I'm going to close this to get it off of the review queue for now.

**Comment by rrousselGit** [comment]
I still need this
What else am I supposed to do to get this merged?

**Comment by rrousselGit** [comment]
Also, if a design doc is needed for new features, why not close the PR immediately then?

This would avoid wasting time on both time. 
cc @Hixie

**Comment by dnfield** [comment]
As you know from other pull requests that you have had merged, a design doc is not always necessary. I am suggesting a design doc in this case because you want to add functionality that may have unintended consequences on the framework. We also have two team members disagreeing about the necessity and the use cases for this API. I am proposing a design doc as a way to try to move forward and resolve those differences.

If you have an alternative idea to try to continue to move this forward I'd be happy to work with you.

**Comment by rrousselGit** [comment]
I still do not understand what is a design doc / what should I do next

**Comment by dnfield** [comment]
Try the template at https://flutter.dev/go/template

**Comment by rrousselGit** [comment]
Done https://github.com/flutter/flutter/pull/49506

**Comment by rrousselGit** [comment]
The design doc is slightly different from this PR (it talks about the changes proposed in https://github.com/flutter/flutter/pull/49506#issuecomment-580289993 instead). 

It's worth noting that https://github.com/rrousselGit/provider/pull/319 is currently delayed until this discussion comes to a conclusion – as introducing these flags at a later stage would mean `provider` would have to make a breaking change.

**Comment by Hixie** [comment]
(the design doc is at http://flutter.dev/go/lifecycle-debug-flag)

**Pull request closed without merging**
