### PR TITLE
Update iOS build signing error message

### PR DESCRIPTION
**Pull request by amrfarid140**
## Description

Updated `fixWithDevelopmentTeamInstruction` to match the most recent version of Xcode which moved the singing configurations from General tab to Signing & Capabilities tab.

## Related Issues

[Issue #45821](https://github.com/flutter/flutter/issues/45821)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by amrfarid140** [comment]
@Hixie Is it possible to get an exemption from the test rule for this change. I don't think it's needed in this instance.

**Review by jmagman — APPROVED** [review]
Matches https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices, LGTM

**Comment by jmagman** [comment]
> Matches https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices, LGTM

Well... kind of matches.  I leave this up to @christopherfujino 
> For Xcode 9 & 10, look under General > Signing > Team.
> For Xcode 11 and newer, look under Signing & Capabilities > Team.

**Review by christopherfujino — CHANGES_REQUESTED** [review]
Thanks for making this PR @amrfarid140!

To be safe, can we be consistent with the website, and offer both instructions, since we support XCode 10.2 and later. Can you make it something to the effect of:

```
  3- Make sure a 'Development Team' is selected in either the 'Signing & Capabilities' tab (for Xcode 11 and newer) or the 'General' tab (for Xcode 10).
```

**Comment by amrfarid140** [comment]
Not a problem at all. I will make this change ny tomorrow :)

**Comment by christopherfujino** [comment]
@amrfarid140 thank you! Note, I just opened [this PR](https://github.com/flutter/website/pull/3352) to remove the reference to Xcode 9 on the website, so you don't need to reference version 9.

**Comment by amrfarid140** [comment]
@christopherfujino @jmagman I've updated the message to match https://flutter.dev/docs/get-started/install/macos#deploy-to-ios-devices

**Review by christopherfujino — APPROVED** [review]
LGTM! Thanks so much!

**Comment by Hixie** [comment]
This should be tested — there should be a test that verifies that the output is what we expect when this condition is met.

**Pull request merged**
