### PR TITLE
Revert "Migrate Flutter gallery test to null safety"

### PR DESCRIPTION
**Pull request by mit-mit**
Reverts flutter/flutter#69048

This is causing failures in apps, for example in flutter/gallery:

```
git clone https://github.com/flutter/gallery.git
cd gallery
flutter pub get
```

=>

```
"af": 41 untranslated message(s).
"am": 41 untranslated message(s).
...
"zh_TW": 41 untranslated message(s).
"zu": 41 untranslated message(s).
To see a detailed report, use the --untranslated-messages-file
option in the tool to generate a JSON format file containing
all messages that need to be translated.
Because gallery depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, intl 0.17.0-nullsafety.2 is required.
So, because gallery depends on intl ^0.16.1, version solving failed.
Running "flutter pub get" in gallery...
pub get failed (1; So, because gallery depends on intl ^0.16.1, version solving failed.)
```

I tried to resolve this in flutter/gallery by upgrading intl (`intl: ^0.17.0-nullsafety`), but that causes another failure:

```
gallery] flutter pub get
Running "flutter pub get" in gallery...                         

Because every version of flutter_localized_locales depends on intl ^0.16.0 and gallery depends on intl ^0.17.0-nullsafety, flutter_localized_locales is forbidden.
So, because gallery depends on flutter_localized_locales ^1.1.1, version solving failed.
pub get failed (1; So, because gallery depends on flutter_localized_locales ^1.1.1, version solving failed.)
exit code 1
```

So looks like a fix is needed in `flutter_localized_locales` to roll that to `intl` 0.17

### CODE REVIEW

**Comment by mit-mit** [comment]
TBR @blasten,  this is now passing CI, so I'm going to merge this to unblock the engine roll, which we need by monday

**Comment by tvolkert** [comment]
Looks like there were some dependencies in the migration that were still on non-null-safe versions.  e.g. I notice http http_parser were still on 0.12.2 and 3.1.4 respectively.  In those cases, the null-safe versions haven't been published, so you have to do something like the following:

```
dependency_overrides:
  http:
    git:
      url: https://github.com/dart-lang/http.git
      ref: 7bc620de8b416d8186f0bed75837c09293f597d4
  http_parser:
    git:
      url: https://github.com/dart-lang/http_parser.git
      ref: 763512ce970c336b3392a1a75d2ccd9508a33896
```

**Comment by tvolkert** [comment]
@mit-mit we should probably publish null safe versions of those packages (and any others in the Dart SDK that the gallery depends on).

**Comment by mit-mit** [comment]
@tvolkert https://pub.dev/packages/http_parser/versions/4.0.0-nullsafety is already there, and @kevmoo says http should be there later today

**Comment by blasten** [comment]
cc @guidezpl @rami-a for `flutter/gallery` dependencies.  

1) `flutter_localized_locales` was just published
2) `intl_translation` also conflicts as it depends on `intl`, but I heard it could be dropped from the Gallery's dev dependencies.

Are you guys driving the changes to the Gallery's pubspec.yaml?

**Comment by kevmoo** [comment]
Also blocked on https://dart-review.googlesource.com/c/sdk/+/171021 – and would need to roll this into google3

**Pull request merged**
