### PR TITLE
[WIP] Move observatory discovery into device class

### PR DESCRIPTION
**Pull request by jonahwilliams**
Keep attach implementation lean, make it easier to gradually add mdns support.

TODO: verify that logging call can be safely removed for fuchsia.

### CODE REVIEW

**Comment by dnfield** [comment]
Should we just make the Android devices use a log scanner like they do today for this?  I think overall this approach makes sense though.

**Comment by jonahwilliams** [comment]
Not sure what you mean - they do unless a port is provided?

**Comment by dnfield** [comment]
I'm thinking in terms of getting away from using log scanners for this, although maybe that's not the best idea as I think about it some more.

**Comment by jonahwilliams** [comment]
Oh right - long term yes we should - however fuchsia and Android/iOS will always have different implementations, and there will probably be a wide gap on the web and desktop too

**Comment by jonahwilliams** [comment]
Closing until I have a change to work on this.

**Pull request closed without merging**
