### PR TITLE
[await sync-async flag] Add test of sync async execution

### PR DESCRIPTION
**Pull request by mravn-google**
Add a test of sync-async Dart semantics to the async widgets test suite. This may not be the ideal place for it, and I'd appreciate suggestions for a better place to put it.

### CODE REVIEW

**Comment by tvolkert** [comment]
Test passes, but there are linter failures that the bots are complaining about

**Comment by mravn-google** [comment]
@tvolkert Lints gone.

**Comment by Hixie** [comment]
That file is for the Async widgets.

This seems more like a test for the Dart test suite or the engine test suite, but I've no problem having it in the Flutter test suite as well... maybe //packages/flutter/test/engine is the right place though.

**Review by tvolkert — COMMENTED** [review]
The actual test LGTM, pending decision on where to place it (//packages/flutter/test/engine sounds like the right place).

**Comment by Hixie** [comment]
SGTM

**Review by tvolkert — APPROVED** [review]

**Comment by Hixie** [comment]
Should we land this?

**Comment by mravn-google** [comment]
It would fail until we land the sync-async change.

**Pull request merged**
