### PR TITLE
Default clipBehavior of ClipRect to hardEdge.

### PR DESCRIPTION
**Pull request by GaryQian**
Using antiAlias in ClipRect, which is no longer the default, is now slow since flutter/engine#6199 enables AA.

**Background:**
Previously, the engine did not properly pass the AA flag on ClipRect.clipBehavior. flutter/engine#6199 fixes this and enables AA. However, default AA on clipRects has caused severe regressions in benchmark performance.

To maintain expected performance, we should now default the clipBehavior to hardEdge to disable default AA. This is consistent with any flutter projects that did not previously explicitly set the clipBehavior and should not change app appearance.

**Migration:**
- If you left clipBehavior as default: Nothing!
- If you explicitly set clipBehavior as hardEdge: Nothing!
- If you explicitly set clipBehavior as antiAlias or antiAliasWithSaveLayer: Your application will now actually perform the specified AA. It is up to you to decide if the performance is worth the visual improvement.
- If you left clipBehavior as default and expected AA: explicitly set clipBehavior to Clip.antiAlias and verify that the performance is acceptable to your application.

For the most part, there should be minimal if any need to migrate code, but I will be glad to assist anyone to achieve the expected clipping behavior.

**Summary:**
clipBehavior is now properly respected instead of always hardEdge. Any expectation of anti-aliasing should be re-evaluated in regards to performance.

https://github.com/flutter/flutter/issues/21702

### CODE REVIEW

**Comment by GaryQian** [comment]
Fixes: https://github.com/flutter/flutter/issues/21617

**Review by tvolkert — APPROVED** [review]

**Review by liyuqian — APPROVED** [review]
LGTM. Thanks for the quick fix!

**Comment by Hixie** [comment]
LGTM, but please make sure to add more documentation soon. Thanks!

**Comment by goderbauer** [comment]
FYI: My golden files update for an engine roll overwrite your golden update for this PR, see https://github.com/flutter/goldens/pull/17.

**Comment by liyuqian** [comment]
FYI: you can also `git rebase master` and `git push -f` to avoid the Merge branch master commit.

**Comment by Hixie** [comment]
This seems to have had no effect on the regression.

**Pull request merged**
