### PR TITLE
Reland "Fix text field selection toolbar under Opacity (#31097)"

### PR DESCRIPTION
**Pull request by liyuqian**
Updated the golden file

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
do we understand how this failed before?

**Comment by Hixie** [comment]
(was it just a new test that was added between when the PR was written and tested, and when it landed?)

**Comment by jonahwilliams** [comment]
We forgot to roll the golden files

**Comment by liyuqian** [comment]
@Hixie : the PR was created about 3 days ago and the the golden file was generated at that time based on flutter master 3 days ago; in the last 2 days, someone landed changes that affects the golden file, but I didn't rebase the PR to the newest master before merging. Our presubmit only checks against my old base, not the master, while the post-submit always checks against the newest master, so the post-submit failed while the pre-submit passed. This race condition seems to be possible in any CI system that I've worked with.

**Pull request merged**
