### PR TITLE
Update packages --force-upgrade

### PR DESCRIPTION
**Pull request by tvolkert**

### CODE REVIEW

**Comment by gspencergoog** [comment]
Uhm, how is this different from https://github.com/flutter/flutter/pull/24120

**Comment by tvolkert** [comment]
It bumps `process` too.

**Comment by gspencergoog** [comment]
I'm just waiting for green to commit it.

**Comment by gspencergoog** [comment]
Ahh, OK.  I'll close mine, and give this an LGTM.

**Review by gspencergoog — APPROVED** [review]

**Comment by tvolkert** [comment]
@fkorotkov any idea why the Cirrus task is failing?  It seems to crash in the middle of the task and fail without providing context.

**Comment by tvolkert** [comment]
Nope.  That test didn't actually fail, and even if it did, tests should continue to run after it.

@dnfield said he was seeing the same behavior on a separate pr

**Comment by dnfield** [comment]
Seeing this error:

> Exception on the agent! Failed to start uploading logs for command artifacts: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 130.211.170.105:8239: connect: connection refused"

On https://cirrus-ci.com/task/5759012647731200

The last two attempts of this have just cut out after a few minutes in the middle of testing the way @tvolkert is describing.

**Comment by fkorotkov** [comment]
@dnfield this is a warning. I'm trying to repro but my fork fails with:

```
FINE: Resolving dependencies finished (1.5s).
ERR : The current Flutter SDK version is 0.2.8-pre.1959.
    | 
    | Because flutter_gallery depends on url_launcher >=4.0.0 which requires Flutter SDK version >=0.5.6 <2.0.0, version solving failed.
FINE: Exception type: SolveFailure
FINE: package:pub/src/solver/version_solver.dart 308:5   VersionSolver._resolveConflict
    | package:pub/src/solver/version_solver.dart 131:27  VersionSolver._propagate
    | package:pub/src/solver/version_solver.dart 96:9    VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                         _AsyncAwaitCompleter.completeError
    | package:pub/src/solver/version_solver.dart         VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                         _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart         VersionSolver.solve
    | package:pub/src/solver.dart 35:10                  resolveVersions.<fn>
    | package:pub/src/log.dart 378:18                    progress
    | package:pub/src/solver.dart 32:10                  resolveVersions
    | package:pub/src/entrypoint.dart 200:24             Entrypoint.acquireDependencies
---- End log transcript ----
pub get failed (1)
```

**Comment by dnfield** [comment]
Unfortunately we're having flakes happen in some of these that look like legitimate failures (and Cirrus can't control that).  But mixed in there I'm also seeing the agent stop responding.

**Comment by fkorotkov** [comment]
Oh. My error was because of missing tags on my fork. 👍

**Comment by dnfield** [comment]
I'm becoming suspicious of https://github.com/flutter/flutter/commit/2d5ed986e194cb2e264028fa2aea3ddcdb8b7da3 - it seems like the linux tool tests might be flaky since then, and sometimes with a segfault, which might explain Cirrus not reporting all the errors or might not.

I'm getting failures on Linux when I run the tool tests with it, and reverting it makes them go away.

**Comment by dnfield** [comment]
That commit is fine - getting errors without it too...

**Comment by tvolkert** [comment]
@fkorotkov we're still seeing this happen on basically every PR and at `master`.  `tool_tests` jobs are failing without any logs of what happened or any actual Dart test failures.  It's blocking our ability to submit or cut a good release.

It's _possible_ that the Dart VM is crashing while running tools tests, though if that were the case, Cirrus should log something to the effect of "process exited abnormally".

Can you please have a look?

**Comment by goderbauer** [comment]
Another example where the test is failing with a variety of infra failures: https://cirrus-ci.com/build/5652850182979584

**Comment by goderbauer** [comment]
FWIW: The tests in question run fine on my local linux machine...

**Comment by fkorotkov** [comment]
@tvolkert resumed looking into it. I still have [problems reproducing it](https://cirrus-ci.com/build/6436563133136896).

Cirrus CI Agent should report exit code explicitly if it's not `0` or `1`. Not sure how the agent can see if a process launched within a bash script had internal issues. Is there a way to have some extra Dart VM logs stored in a file for example?

**Comment by fkorotkov** [comment]
@tvolkert I found an issues that might be related to this behaviour. Just deployed a fix. Let's see if it will continue to appear.

**Comment by fkorotkov** [comment]
@tvolkert I have a suspicion there was a race condition when a tree of processes got killed upon a node preemption. The child Dart VM process gets killed first since it is a child and the agent manages to observe it and report back.

**Pull request merged**
