### PR TITLE
AppBar Height Fix

### LINKED ISSUE #26163: The height of the AppBar is incorrect on IphoneX?
I want to use appbar anywhere, so I put the appbar in the body of the `Scaffold` instead of using the appbar property directly, but I find that the height of the appbar on IphoneX is not correct?

```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          children: [
            AppBar(
              backgroundColor: Colors.amber,
              title: Text("Second AppBar"),
            )
          ],
        ),
      ),
    );
  }
}
```

### PR DESCRIPTION
**Pull request by justinmc**
## Description

On iOS, when an AppBar is placed in the body of an app, it is too tall.  This PR fixes the height by removing the bottom padding.

## Related Issues

Closes https://github.com/flutter/flutter/issues/26163

## Tests

Tested the padding received by an AppBar in the Scaffold's body. Fails before this PR.

### CODE REVIEW

**Comment by goderbauer** [comment]
@justinmc Is this PR still being worked on? It probably needs at least a test :)

**Comment by justinmc** [comment]
Ah I meant to check if this is viable.  I will make a go/no-go decision tomorrow.

**Comment by justinmc** [comment]
Alright I'm going to move forward with this unless anyone comes up with a good reason not to.  I tested this side by side with master on Android and iOS, and it seems to fix the bug on iOS and affect nothing else.  Existing tests pass.  I'll add a new test and put this in review.

**Review by HansMuller — APPROVED** [review]
LGTM

**Pull request merged**
