### PR TITLE
Marks Windows_android channels_integration_test_win to be flaky

### PR DESCRIPTION
**Pull request by fluttergithubbot**
Issue link: https://github.com/flutter/flutter/issues/134636

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Review by keyonghan — APPROVED** [review]
LGTM

**Comment by zanderso** [comment]
Why is Google testing failing?

**Comment by keyonghan** [comment]
Created https://github.com/flutter/flutter/issues/134668 to investigate.

**Comment by XilaiZhang** [comment]
There seems to be two separate issues:
1. .ci.yaml should be excluded in the roller script. when I looked at the [filters for framework in roller script](https://source.corp.google.com/piper///depot/google3/mobile/flutter/tools/frob/roll_job/lib/src/roller.dart;l=20;bpv=1;bpt=1?q=frob%2Froll_job%2Flib%2Fsrc%2Froller.dart), it does not seem to exlude .ci.yaml. However, on [flutter repo in google3](https://source.corp.google.com/piper///depot/google3/third_party/dart/flutter/) it seems like .ci.yaml files are excluded. Maybe @chingjun or @CaseyHillers would know more on how .ci.yaml files are excluded from roller script? thank you!

2. Instructions on how to resolve merge conflict isn't clear. sent cl/565087659 for review

**Pull request merged**
