### PR TITLE
Upgrade vm_service and others.

### PR DESCRIPTION
**Pull request by polina-c**
Unblocks https://github.com/flutter/devtools/pull/7331

### CODE REVIEW

**Review by bkonyi — APPROVED** [review]

**Comment by christopherfujino** [comment]
Analysis failure:

```
  error â�¢ The argument type 'JSArray<JSAny?>' can't be assigned to the parameter type 'JSArray<JSNumber>'.  â�¢ dev/benchmarks/macrobenchmarks/lib/web_benchmarks.dart:309:22 â�¢ argument_type_not_assignable
```

I'm guessing from the package:js bump from 0.6.7 -> 0.7.1

**Comment by polina-c** [comment]
> I'm guessing from the package:js bump from 0.6.7 -> 0.7.1

Adding js to packages/flutter_tools/lib/src/update_packages_pins.dart dies not help. 
The command is stating:

```
WARNING: the following packages use hard-coded version constraints:
  - flutter_gallery_assets: 1.0.2
  - flutter_template_images: 4.2.0
  - material_color_utilities: 0.8.0
  - archive: 3.3.2
  - leak_tracker: 10.0.4
  - leak_tracker_testing: 3.0.1
  - leak_tracker_flutter_testing: 3.0.3
  - path_provider_android: 2.2.1
  - js: 0.6.7 (skipped because it was not a transitive dependency)
 ```

And upgrades js under `dev/...`

**Comment by polina-c** [comment]
Failure of `Linux_android hot_mode_dev_cycle_linux__benchmark`: PathNotFoundException: Cannot open file, path = '/opt/s/w/ir/x/t/edited_flutter_gallery/hot_benchmark.json' (OS Error: No such file or directory, errno = 2)

**Comment by polina-c** [comment]
Closing in favor of isolated upgrade: https://github.com/flutter/flutter/pull/144845

**Pull request closed without merging**
