### PR TITLE
Added option to disable [NavigationRailDestination]s

### PR DESCRIPTION
**Pull request by matheus-kirchesch**
It adds the optional property [disabled] to the public class [NavigationRailDestinations], this is the only public change visible in the flutter API.

As for internal changes the [_RailDestination] widget now takes this new property into consideration for rendering the widget. (It applies an opacity and removes the function from the button's InkWell when disabled)

* https://github.com/flutter/flutter/issues/127108

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by HansMuller** [comment]
This is a reasonable idea for a feature however changing the opacity of the inkwell's child isn't consistent with the way the disabled state is handled in other widgets, it can't be overridden and there's no theme entry. It shouldn't be possible to tab into a disabled destination or to control it with the keyboard.  And PRs need tests.

**Comment by matheus-kirchesch-btor** [comment]
Hello @HansMuller.

> This is a reasonable idea for a feature however changing the opacity of the inkwell's child isn't consistent with the way the disabled state is handled in other widgets

Agreed, I stated that in the issue I opened, I just wanted to present the problem, I will see if I can read about it and implement it tonight.

> it can't be overridden and there's no theme entry

What do you mean by that?

> It shouldn't be possible to tab into a disabled destination or to control it with the keyboard

That is handled by the pull request since the ink well is the only thing that makes it targetable.

> And PRs need tests

Sure, I will write one, now just to be sure, it has to just check if the disabled flag is making the InkWell non clickable?

**Comment by matheus-kirchesch-btor** [comment]
@HansMuller I added the tests and changed the custom opacity code to do the same thing the ButtonStyle does, which is use the onSurface color with 0.38 opacity

**Review by HansMuller — APPROVED** [review]
LGTM

**Pull request merged**
