### PR TITLE
Fix: Date picker interactive sample not loading 

### LINKED ISSUE #99338: showDateRangePicker sample is broken on docs
image

[showDateRangePicker function
](https://api.flutter.dev/flutter/material/showDateRangePicker.html)

### PR DESCRIPTION
**Pull request by maheshj01**
Fixes interactive sample not loading

Fixes: https://github.com/flutter/flutter/issues/99338

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
LGTM

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by HansMuller** [comment]
The Google Testing failure doesn't appear to have anything to with this PR:
```
google3:///[mobile/flutter/tools/icon_font/bin/icon_map_generator.dart:24](https://cs.corp.google.com/piper///depot/google3/mobile/flutter/tools/icon_font/bin/icon_map_generator.dart?l=24&ws=tap-presubmit-rerun-server/458933&snapshot=2):24: Error: Method not found: 'stringToTokenPairMap'.
  final tokenPairMap = stringToTokenPairMap(codepointsString);
```

I'll rerun the test however this PR will probably need to be sync'd with master (rebased).

**Comment by maheshmnj** [comment]
Unfortunately, rebase does not fix the Google testing failure

**Review by TahaTesser — APPROVED** [review]

**Pull request merged**
