### PR TITLE
Rename TargetPlatform.ios to ios_arm64

### PR DESCRIPTION
**Pull request by cbracken**
Pre-factoring for the addition of ios_armv7.

### CODE REVIEW

**Review by tvolkert — APPROVED** [review]

**Comment by cbracken** [comment]
Related to: #2089

**Comment by eseidelGoogle** [comment]
This reminds me, our usage reporting for "ios" also just comes in as "ios", unlike Android where we get android-x86, android-arm, android-arm64, which is kinda nice.  I can file a bug.

**Comment by eseidelGoogle** [comment]
(Don't take this as a review, since I'm sure I don't know what I'm talking about) . Doesn't "ios" already contain binaries for both simulator (x64) and arm?  Will those need to be split further?

**Comment by cbracken** [comment]
@eseidel this allows for multiple `TargetPlatform`s within iOS, but we still pull from the same old `ios`, `ios-profile`, and `ios-release` URLs/archives. 

Specifically the value side of [this map](https://github.com/flutter/flutter/pull/16258/files#diff-b90d32e8d03d0fce960fe8fd71ab81f9R394) doesn't change.

The plan is to continue to generate multi-arch framework binaries, but it's useful to differentiate between 64- and 32-bit gen_snapshot steps for the AOT build (though we'll use lipo to ship a universal binary in the end).

**Comment by Hixie** [comment]
@cbracken can this land?

**Comment by cbracken** [comment]
Dropping this for now as I expect I can avoid it.

**Pull request closed without merging**
