### PR TITLE
Roll engine to fed2ea458ed49088d33eddabc546ba56d600c717 (includes dart roll)

### PR DESCRIPTION
**Pull request by aam**
Changes since last roll:
```
fed2ea458 Revert "Remove vmservice_io.main from entry points. (#5625)" (#5711)
958d2cfc5 Remove trailing white spaces (#5708)
6db0cc9da Roll src/third_party/skia 1d784ceafa9e..c69c4410be7d (13 commits) (#5709)
494562442 Roll src/third_party/skia 418e658a6922..1d784ceafa9e (10 commits) (#5707)
cb27dab2b Roll src/third_party/skia 6d98257725b5..418e658a6922 (1 commits) (#5706)
2981cc7a3 Roll src/third_party/skia e0a9962b12ad..6d98257725b5 (1 commits) (#5704)
ad4197280 Roll src/third_party/skia 8fe31406e980..e0a9962b12ad (3 commits) (#5703)
3b6dedb86 Add anti-alias switch to canvas clip calls (#5670)
d9a831c55 Roll dart to 84ca27a09ebd6a65cd23ee52d835d89cbe06c574. (#5700)
d5fce84be revert change to app delegate that wont build on earlier xcodes (#5702)
45db8f7c5 Roll src/third_party/skia d48897b576e9..8fe31406e980 (4 commits) (#5701)
d217a9512 Remove cullRect calculation on TransformLayers with a perspective transform. (#5693)
13d801ac2 Roll src/third_party/skia 1354048c8fa8..d48897b576e9 (8 commits) (#5699)
1644f3589 Roll src/third_party/skia 373224c9ab3a..1354048c8fa8 (1 commits) (#5698)
4da7d44f3 Roll src/third_party/skia a391c72a2057..373224c9ab3a (1 commits) (#5697)
a36207f35 Roll src/third_party/skia 0dd98a59df63..a391c72a2057 (1 commits) (#5696)
cf14ca0f7 Roll src/third_party/skia a717ca970b25..0dd98a59df63 (1 commits) (#5695)
89cd29fb1 Roll src/third_party/skia dd962a95c5f2..a717ca970b25 (1 commits) (#5694)
f52955c25 Roll src/third_party/skia bcc3aec00422..dd962a95c5f2 (1 commits) (#5692)
6e6512287 Roll src/third_party/skia 4f6ea65f66c9..bcc3aec00422 (2 commits) (#5691)
e3347680c Roll src/third_party/skia a50205fca5f7..4f6ea65f66c9 (2 commits) (#5690)
8aa9a8158 Roll src/third_party/skia 6667fb123911..a50205fca5f7 (3 commits) (#5689)
3c4bf8de3 Roll src/third_party/skia 3d3d8841ff86..6667fb123911 (1 commits) (#5688)
f5f15b78b Roll src/third_party/skia b95bbba308b9..3d3d8841ff86 (1 commits) (#5687)
31bd1e29a Roll src/third_party/skia 20b824d9fe49..b95bbba308b9 (1 commits) (#5686)
37e96b9e6 Roll src/third_party/skia 53f5db5e9833..20b824d9fe49 (1 commits) (#5685)
b04fc96c2 Roll src/third_party/skia 3f2d909d7029..53f5db5e9833 (1 commits) (#5683)
686ee99d8 Roll src/third_party/skia 9eb1c7d80fb3..3f2d909d7029 (1 commits) (#5682)
936a38dda Roll src/third_party/skia 44bad2e86a01..9eb1c7d80fb3 (1 commits) (#5681)
6f8788625 Roll src/third_party/skia e72c144af687..44bad2e86a01 (1 commits) (#5680)
23ae68dfd Roll src/third_party/skia a93486b095ea..e72c144af687 (1 commits) (#5679)
c6ab9b941 Roll src/third_party/skia 5788bb9af9ad..a93486b095ea (1 commits) (#5678)
aa4afc14b Roll src/third_party/skia 9b80bd5f16e6..5788bb9af9ad (1 commits) (#5677)
9f9c06234 Roll src/third_party/skia cdefa23a23cf..9b80bd5f16e6 (1 commits) (#5676)
4128a799c Roll src/third_party/skia 233c65202e69..cdefa23a23cf (1 commits) (#5675)
74dc963ab Roll src/third_party/skia 6784ffa78e70..233c65202e69 (1 commits) (#5674)
5724faf86 ensure that bridge is not destroyed when semantics is still enabled (#5672)
24af9ca6c [fuchsia] Update gn label for fuchsia.ui.scenic (#5673)
d085f1df2 Do not make an extra submit callback during SurfaceFrame destruction if the frame was already submitted (#5669)
b66301055 Roll src/third_party/skia 58a1605d2b9b..6784ffa78e70 (8 commits) (#5671)
2b890c804 Roll src/third_party/skia 34aa059c1502..58a1605d2b9b (6 commits) (#5667)
2a88ecf17 Roll src/third_party/skia 94d57c477fe1..34aa059c1502 (8 commits) (#5666)
51785d244 Remove unused Java imports (#5663)
b157d4f56 Roll dart sdk to 64641d014b77bd410e9aa10558522ae26e4210ee (#5610)
d05225ed9 Roll src/third_party/skia d7425b58df89..94d57c477fe1 (1 commits) (#5665)
32736d52c Roll src/third_party/skia a22d924763ab..d7425b58df89 (4 commits) (#5664)
0fca44477 Roll src/third_party/skia ef21d7e47963..a22d924763ab (3 commits) (#5662)
a7d0f29c7 Roll src/third_party/skia 9aa30c6ee0e5..ef21d7e47963 (5 commits) (#5661)
21c7d6a5d Revert "Add antiAlias and saveCount to clipPath and restore (#5638)" (#5660)
70dcbb591 Roll src/third_party/skia d818ebf4a317..9aa30c6ee0e5 (11 commits) (#5658)
ad42324a6 Roll src/third_party/skia a219419c9d76..d818ebf4a317 (2 commits) (#5657)
f2eb83ae2 Roll src/third_party/skia 00d2e8ebcb13..a219419c9d76 (1 commits) (#5655)
0ec766946 Roll src/third_party/skia 8451daabb23d..00d2e8ebcb13 (1 commits) (#5654)
061e899b5 Support all keyboard actions. (#11344) (#5620)
bc6b2501c Roll src/third_party/skia 34024a7c478c..8451daabb23d (1 commits) (#5653)
df4dffb10 Roll src/third_party/skia 75e69028956d..34024a7c478c (1 commits) (#5652)
d8770d440 Roll src/third_party/skia cf863fb9b446..75e69028956d (1 commits) (#5651)
b88a8b3d5 Roll src/third_party/skia b7b9d02ac020..cf863fb9b446 (1 commits) (#5650)
2261ccf87 [fuchsia] Update scenic lib path. (#5649)
4c4ef987a [fuchsia] Rename scenic_lib => scenic (#5648)
f0c21f327 Roll src/third_party/skia 184d408b646b..b7b9d02ac020 (7 commits) (#5646)
a2bf80590 Add antiAlias and saveCount to clipPath and restore (#5638)
9e450d116 Roll src/third_party/skia c91fe3ab1c5d..184d408b646b (10 commits) (#5645)
e6639963f Roll src/third_party/skia eb8f8106f38c..c91fe3ab1c5d (5 commits) (#5644)
fecd66f34 Roll src/third_party/skia 723b1f6ef941..eb8f8106f38c (1 commits) (#5643)
4466d61a9 Remove vmservice_io.main from entry points. (#5625)
f279dfe30 Roll src/third_party/skia 7e2327b133db..723b1f6ef941 (1 commits) (#5642)
a885bd4f9 Roll src/third_party/skia 24d18ced1ad7..7e2327b133db (6 commits) (#5641)
ad1bd4743 Roll src/third_party/skia a1e5630183c1..24d18ced1ad7 (7 commits) (#5639)
```

### CODE REVIEW

**Comment by goderbauer** [comment]
https://github.com/flutter/flutter/pull/19008 contains a competing engine roll.

**Comment by aam** [comment]
Non-fatal error is generated when flutter is being built:
```
╰─➤  $FH/flutter/bin/flutter test
Downloading Dart SDK from Flutter engine b157d4f5683023836cdf15d42bf56fd201a7084b...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 76.9M  100 76.9M    0     0  39.1M      0  0:00:01  0:00:01 --:--:-- 39.1M
Building flutter tool...
Failed to precompile kernel:util:
Dart_LoadScriptFromKernel: The binary program does not contain 'main'.
```

cc @a-siva in case you have some thoughts on this

**Comment by aam** [comment]
@devoncarew have you had much progress with running flutter tools in dart2 mode? @a-siva mentioned you were looking at that recently. The issues we are seeing here seem to be related to that.

**Comment by devoncarew** [comment]
I have a PR that address some issues: https://github.com/flutter/flutter/pull/19007

If this is blocking the roll I can look at addressing the review comments and seeing about landing it.

**Comment by aam** [comment]
Okay, good to know. We could run flutter tools explictly in dart1 mode until your PR lands

**Comment by devoncarew** [comment]
> We could run flutter tools explictly in dart1 mode until your PR lands

Sounds like a good workaround; we would want to back out that flag and see what the impact is.

**Comment by aam** [comment]
| | We could run flutter tools explictly in dart1 mode until your PR lands
| Sounds like a good workaround; we would want to back out that flag and see what the impact is.

I gave it a try (add `--no-preview-dart-2` flag to flutter shell script), but could not get tests(`flutter test`) to pass. Instead I'm trying to patch https://github.com/flutter/flutter/pull/19007 in and see how that holds up. At least locally tests seem to pass.

**Comment by devoncarew** [comment]
Will land my PR once the bots are device bots are green. 

> I'm trying to patch

Note that I had once small update - changes that hadn't made it into the main PR the first time around.

**Comment by aam** [comment]
> > I'm trying to patch

> Note that I had once small update - changes that hadn't made it into the main PR the first time around.

Yep, github pinged when you added another change.

**Comment by aam** [comment]
flutter_tools tests are failing with mysterious error:
```
⏩ RUNNING: cd packages/flutter_tools; ../../bin/cache/dart-sdk/bin/pub run test -j1 -rcompact
Unable to spawn isolate: .dart_tool/pub/bin/test/test.dart.snapshot.dart2:1:1: Error: Unable to decode bytes as UTF-8.
����
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 1 (expected: zero).
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
cc @a-siva

**Comment by aam** [comment]
Error https://github.com/flutter/flutter/pull/19044#issuecomment-402320496 is caused by a bug in uri handling in File::OpenUri where percent-encoded characters(space is encoded as %20) are not decoded.

**Review by zanderso — APPROVED** [review]
lgtm

**Comment by cbracken** [comment]
FYI I have an engine roll almost about to land...

**Comment by aam** [comment]
@cbracken 
> FYI I have an engine roll almost about to land...
Not sure how we ended up with competing rolls, but I see yours still have errors, which I believe mine have fixes for.

**Comment by cbracken** [comment]
sgtm!

**Pull request merged**
