### PR TITLE
Correct the unit of file size from "kb" (maybe "kilo bits") to "KB"

### LINKED ISSUE #76032: The unit of file size is "kb" but actually it means "kilo bytes" not "kilo bits"
## Steps to Reproduce

1. Run `flutter create bug`.
2. create an oversized image.
3. look at errors.

The error message when enabling "invert oversized images" tells us how many extra space the image uses. That is quite helpful! However, when I read `...an additional 1234kb...`I thought that means kilo *bits* (since in network programming `kb` and `kB` are definitely different and should be taken with care). However, after reading the source code, I suddenly realized that it is kilo *bytes*. Thus, this PR is here to ensure that people do not misunderstand the unit. 

**Expected results:** 
The error reports `kb` but it actually means `kB`.

**Actual results:** 
correct the naming

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

### PR DESCRIPTION
**Pull request by fzyzcjy**
The error message when enabling "invert oversized images" tells us how many extra space the image uses. That is quite helpful! However, when I read `...an additional 1234kb...`I thought that means kilo *bits* (since in network programming `kb` and `kB` are definitely different and should be taken with care). However, after reading the source code, I suddenly realized that it is kilo *bytes*. Thus, this PR is here to ensure that people do not misunderstand the unit. 

*List which issues are fixed by this PR. You must list at least one issue.*
Fixes https://github.com/flutter/flutter/issues/76032

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*
N/A

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

Looks like this is failing some tests, though. Can you please fix those?

**Comment by fzyzcjy** [comment]
@goderbauer Thanks! I only change 2 characters in a literal String, so I am a bit confused why it the tests are failed... I have looked at the CI logs, but seems no clues (since I am not very familiar with all the infrastructures of Flutter). Could you please give some hints?

**Comment by goderbauer** [comment]
There appear to be tests that verify the error message you're modifying. You can probably reproduce this locally by going into the `packages/flutter` directory and running `flutter test` there.

**Comment by fzyzcjy** [comment]
@goderbauer Thanks! I will have a look

**Comment by fzyzcjy** [comment]
@goderbauer Hi all checks have passed!

**Comment by fzyzcjy** [comment]
Wait a bit... The flutter-build fails? Hours ago it was all green...

**Pull request merged**
