### PR TITLE
Started caching results from iana.

### PR DESCRIPTION
**Pull request by gaaclarke**
## Description

Started caching information from iana locally as code to avoid flakes in tests and CI.

## Related Issues

https://github.com/flutter/flutter/issues/53281

## Tests

I added the following tests:

Uses existing tests.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by gaaclarke** [comment]
@HansMuller @jmagman What do you think of this approach?  Should we automate the generation of the code somehow?

**Comment by HansMuller** [comment]
This looks like a good approach to me. Ideally the download/codegen code would be run automatically and regularly. Not because that's vital but because it seems like an easy to way to ensure that we're current.

**Comment by gaaclarke** [comment]
> Ideally the download/codegen code would be run automatically and regularly

Got any pointers on a good place I could do that?  I could try refreshing it when the tests are run so it would try to piggy back on another PR when someone is running tests locally.

**Comment by jmagman** [comment]
You can try a separate Cirrus cache of just this data for just this test.

**Comment by HansMuller** [comment]
I don't have a good suggestion about where to insert gen_subtag_registry.dart, it's probably OK to just run it by hand for now; create an issue about how to ensure that it runs on regular basis in the future.

**Comment by gaaclarke** [comment]
> You can try a separate Cirrus cache of just this data for just this test.

That would have a lot of different issues (stale data, still waiting around for a remote server just to throw the result away, etc).  The added benefit to doing things this way is that it protects us from breakages in iana and we can keep the data and the parser atomically revisioned together.

**Comment by HansMuller** [comment]
Since we're no longer precomputing the data we could restructure this in a more substantial way. The language_subtag_registry command could generate a class with a describeLocale() method, and we could bury the _languages, _regions, _scripts, etc inside the class.

**Comment by gaaclarke** [comment]
> Since we're no longer precomputing the data we could restructure this in a more substantial way. The language_subtag_registry command could generate a class with a describeLocale() method, and we could bury the _languages, _regions, _scripts, etc inside the class.

You are talking about doing more processing in the `gen_subtag_registry.dart` script?  We could do that.  I did the minimal amount of work to get this cached without having to understand the system.  It was just a simple "oh there's a remote string, let's make it local.

One benefit of having the code look exactly like the remote text is that it makes it easier to review and find any potential breaking changes from the source.

I think we should just keep it simple now until we have a bigger signal that we should do more.

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Can you set up an autoroller as well to regularly update the file?

**Pull request merged**
