### PR TITLE
Add enableDrag configuration for showModalBottomSheet

### LINKED ISSUE #39744: Add enableDrag property in showModalBottomSheet method
## Proposal
Be able to disable dragging when creating a Bottom Sheet using showModalBottomSheet method.

### PR DESCRIPTION
**Pull request by yuwen-yan**
## Description

Be able to disable dragging when creating a Bottom Sheet using showModalBottomSheet method.

## Related Issues

Fixes #39744 #39297 #27023

## Tests

I added the following tests:

Updated the existing test by adding details about default behaviour.
Created test for enableDrag is true/false/default.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by rami-a** [comment]
Hey @ybbaigo thanks a lot for the pull request, this seems like a very reasonable request. Out of curiosity, we were wondering what sort of use-case would require the modal bottom sheet to not be draggable? Thanks!

**Comment by ybbaigo** [comment]
@rami-a thanks for your quick reply. sometimes, we want to show a consent bottom sheet with `deny` / `allow` button on it. in this case, we don't want the user can dismiss it without tap `deny` or `allow` due to GDPR issue.

**Review by creativepsyco — APPROVED** [review]
LGTM

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by dev-juyoung** [comment]
The enableDrag property was found to have been merged 12 hours ago.
When will the version containing the feature be released?
I am currently using the 1.12.13+hotfix.5 version, but I need that property right now.

**Comment by tugayac** [comment]
@dev-juyoung Seems like [`BottomSheet` has `enableDrag` as a property in the current stable release](https://api.flutter.dev/flutter/material/BottomSheet-class.html) (`BottomSheet` is the widget class used by `showModalBottomSheet`), but `showModalBottomSheet` only passes that property down to `BottomSheet` as of 1.15.20, which is on the dev channel.

**Pull request merged**
