### PR TITLE
Remove new keyword from default template app

### PR DESCRIPTION
**Pull request by NPKompleet**
The `new` keyword is now redundant in Dart 2 but the template app generated by `flutter create` still reflects the old convention. This PR will help make the template app consistent with Dart 2 coding style.

### CODE REVIEW

**Comment by NPKompleet** [comment]
Hi @Hixie, you can also look at this one I just added. Thanks.

**Comment by dnfield** [comment]
Looks like you have some conflicts that need to be fixed

**Comment by NPKompleet** [comment]
@dnfield So you guys have changed the folder structure. One updated fix coming up shortly.

**Comment by NPKompleet** [comment]
@dnfield It has just been updated.

**Comment by dnfield** [comment]
Thanks for your contribution!

**Pull request merged**
