### PR TITLE
[versions] update EVERYTHING

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Update all the versions!

### CODE REVIEW

**Comment by mit-mit** [comment]
Looks like a couple were not moved to the latest version (these are major upgrades):

```
Package           Current   Upgradable  Resolvable  Latest
petitparser       *2.4.0    *2.4.0      *2.4.0      3.0.1
xml               *3.5.0    *3.5.0      *3.5.0      3.7.0
```

**Comment by jonahwilliams** [comment]
@mit-mit  the culprit here appears to be the `intl_translation` package:

https://github.com/dart-lang/intl_translation/blob/master/pubspec.yaml

This is constraining `petitparser` to `< 3.0.0` which is also keeping `xml` from upgrading.

**Comment by miksen** [comment]
Got it. I logged an issue for intl_translation. But this PR is already a massive improvement, so how about we merge this; the we can update again when intl_translation might be ready?

**Comment by mit-mit** [comment]
Got it. I logged an issue for intl_translation. But this PR is already a massive improvement, so how about we merge this; the we can update again when intl_translation might be ready?

**Comment by jonahwilliams** [comment]
SGTM

**Review by tvolkert — APPROVED** [review]

**Pull request merged**
