### PR TITLE
[Gallery] Reland Add Material Study app Rally as an example app

### PR DESCRIPTION
**Pull request by perclasson**
Reland "Add Material Study app Rally as an example app." #42236 which was reverted in #44194

## Description

Adds a Flutter sample app based on the Material study Rally (a hypothetical, personal finance app). It showcases custom tabs, custom painted widgets, and custom animations.

Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-14 at 12 30 47
Simulator Screen Shot - iPhone Xʀ - 2019-10-08 at 09 57 33
Simulator Screen Shot - iPhone Xʀ - 2019-10-08 at 09 57 36

## Related Issues

N/A

## Tests

N/A

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by rami-a — APPROVED** [review]
```
 __    ___  ____  __  __ 
(  )  / __)(_  _)(  \/  )
 )(__( (_-.  )(   )    ( 
(____)\___/ (__) (_/\/\_)
```

**Review by willlarche — APPROVED** [review]

**Comment by tvolkert** [comment]
This change contains Apache 2.0 licensed files, which aren't allowed in flutter/flutter.

Reviewers (@rami-a @willlarche) FYI to check newly added files for proper license headers.

I'm going to revert this change.  Feel free to re-send with the license headers fixed.

FYI @Hixie

**Comment by tvolkert** [comment]
This change was also missing tests.  Please include tests for all changes.

**Comment by perclasson** [comment]
Thanks @tvolkert for reverting it, was not aware that Apache 2.0 license was not allowed. It was needed for the Roboto font.

(Also all of the gallery example studies have smoke tests by default.)

**Comment by tvolkert** [comment]
re: tests -- imagine we have a bot that randomly changes or removes code from the codebase and checks it in if the tests pass.  If you don't want that bot to break you, then you should have tests to ensure that doesn't happen.

Another way to think about it is that you should have tests ensuring the behavior of anything that you care about.  The fact that this was able to be reverted without changing any tests implies that the behavior in question wasn't worth keeping.

**Comment by iskakaushik** [comment]
If/When you re-land it please include the changes in https://github.com/flutter/flutter/commit/68d1fe58da759c22a8c3ce6f2735c914f7844316. I am reverting it for now.

**Pull request merged**
