### PR TITLE
track debug build times; switch from --profile to --release

### LINKED ISSUE #10270: Add a benchmark to track build times for debug builds
We're tracking AOT build times, but it would be nice to also track debug build bench times since those will be quite different code paths and are actually more important to our users.

cc @yjbanov

### PR DESCRIPTION
**Pull request by yjbanov**
Fixes https://github.com/flutter/flutter/issues/10270

@Hixie

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM.

For bonus points:
nit: constructors should be first in a class
nit: some of these constructors can probably be const

**Comment by yjbanov** [comment]
> nit: constructors should be first in a class

Done.

> nit: some of these constructors can probably be const

Done.

**Comment by Hixie** [comment]
Is this ready to land?

**Comment by yjbanov** [comment]
Yep.

**Comment by yjbanov** [comment]
Done.

**Pull request merged**
