### PR TITLE
remove flutter_test quiver dep, use fake_async and clock instead

### PR DESCRIPTION
**Pull request by jakemac53**
## Description

Removes the `flutter_test` dependency on `quiver`, instead using the more targeted `clock` and `fake_async` packages.

## Related Issues

https://github.com/flutter/flutter/issues/53908

## Tests

No changes to tests

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [x] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [x] I wrote a design doc: https://docs.google.com/document/d/1EkkLbECNBwHgddBQAZqEy7iQLTIxR1rgChKzxcLwhio/edit
   - [x] I got input from the developer relations team, specifically from: @RedBrogdon
   - [x] I wrote a migration guide:  https://github.com/flutter/website/pull/3932

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

Note for future readers. This will increase the number of packages that flutter_test depends on by 1. Each package is significantly smaller than quiver however, so it should be considered a net positive.

**Comment by jakemac53** [comment]
Correct it does increase the number of packages - I have filed an issue on quiver to also just export these packages instead of duplicating the code, so ultimately it maybe a reduction in dependencies of 1 if they did choose to do that.

**Comment by jakemac53** [comment]
Note that this is currently blocked on rolling the new fake_async internally which I am doing now

**Comment by jakemac53** [comment]
Updated with design doc/migration plan as this did turn out to be breaking.

Will rebase and fix conflicts once its ready to land.

**Comment by goderbauer** [comment]
fly-by comment: I saw you wrote a migration guide linked in the PR description. We typically publish those on our website here to make them available to our users: https://github.com/flutter/website/tree/master/src/docs/release/breaking-changes

**Comment by jakemac53** [comment]
Oh ok - I will go ahead and send a pr for it there, that gives a better opportunity for commenting on the wording of it etc as well :+1:

**Comment by jakemac53** [comment]
https://github.com/flutter/website/pull/3932

**Comment by RedBrogdon** [comment]
This is the type of breaking change for which the affected audience is likely to be quite sophisticated and able to roll with the new API. The migration guide is great, and should be all the community needs.

**Pull request merged**
