### PR TITLE
Unblock PowerShell Script before execution

### PR DESCRIPTION
**Pull request by goderbauer**
Possible fix for https://github.com/flutter/flutter/issues/17646.

@mit-mit Can you verify that this fixes your problem?

### CODE REVIEW

**Comment by mit-mit** [comment]
This produces a similar, but slightly different, error:

```
C:\Users\mit>flutter --version
Checking Dart SDK version...
File C:\Users\mit\dev\flutter\bin\internal\update_dart_sdk.ps1 cannot be loaded. The file
C:\Users\mit\dev\flutter\bin\internal\update_dart_sdk.ps1 is not digitally signed. You cannot
run this script on the current system. For more information about running scripts and setting
execution policy, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
Error: Unable to update Dart SDK. Retrying...
```

**Comment by mit-mit** [comment]
Simply removing the flag seems to work; the upgrade completed as expected
```
    CALL PowerShell.exe -File "%update_dart_bin%"
```

**Comment by goderbauer** [comment]
That's very odd. Can you open PowerShell and tell me what the output of "Get-ExecutionPolicy" is on your system?

**Comment by goderbauer** [comment]
Also: how did you obtain this copy of flutter? Is it a git checkout or one of those download bundles?

**Comment by mit-mit** [comment]
> That's very odd. Can you open PowerShell and tell me what the output of "Get-ExecutionPolicy" is on your system?

```
PS C:\Users\mit> Get-ExecutionPolicy
RemoteSigned
```

**Comment by mit-mit** [comment]
I just grabbed fresh SDKs into a temp folder from both git and a bundle. It indeed only repros in the bundle case. I simple extracted the bundle, and then ran `flutter channel master` and got:

```
C:\Users\mit\tmp\bundle\flutter>.\bin\flutter channel master
Checking Dart SDK version...
& : File C:\Users\mit\tmp\bundle\flutter\bin\internal\update_dart_sdk.ps1 cannot be loaded. The
file C:\Users\mit\tmp\bundle\flutter\bin\internal\update_dart_sdk.ps1 is not digitally signed.
You cannot run this script on the current system. For more information about running scripts
and setting execution policy, see about_Execution_Policies at
http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ & 'C:\Users\mit\tmp\bundle\flutter/bin/internal/update_dart_sdk.ps1'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
Error: Unable to update Dart SDK. Retrying...
```

**Comment by gspencergoog** [comment]
I wonder if it has to do with how zip creates the files when it unpacks them: e.g. some kind of metadata marking it as "downloaded" when zip extracted, but not when git cloned? I know that Macs have a "downloaded from the internet" bit on executable metadata, so Windows might have something similar.

**Comment by goderbauer** [comment]
Yeah, windows has one too. I'll look into it today. In theory and according to Microsoft's docs, "executionpolicy bypass" should disable the check...

**Comment by goderbauer** [comment]
> Simply removing the flag seems to work; the upgrade completed as expected

On my system I get the error message when I REMOVE"-ExecutionPolicy Bypass". With the parameter in place everything works.

**Comment by goderbauer** [comment]
@mit-mit I was actually able to reproduce your problem on @bkonyi's Windows machine. The only difference I could find is that he was running an older version of Windows. 

Fortunately, I was also able to confirm on his machine that this PR in its latest version fixes the problem.

Background: Windows marks executables downloaded from the web with a special bit and PowerShell by default doesn't allow executing these. In theory and as documented by Microsoft, `-ExecutionPolicy Bypass` is supposed to make PowerShell not care about that bit, but apparently on older Windows versions PowerShell still does... Luckily, we can easily remove that bit from the PowerShell script, which is what this PR is doing.

**Review by gspencergoog — APPROVED** [review]

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by mit-mit** [comment]
I can confirm that the latest fix resolves the issue!

**Pull request merged**
