### PR TITLE
[flutter_tools] handle unsafe build outputs

### LINKED ISSUE #53546: `flutter build --release` includes JIT-related files on macOS (off a dirty build folder)
I am not sure if this is the case on other desktop platforms, but if you build a release version of a Flutter app for macOS without cleaning the build directory first, a couple of JIT-specific files (`kernel_blob.bin` and `isolate_snapshot_data`) are included in the release `.app` (bloating it by about ~30MB in a minimal app)

## Steps to Reproduce

```bash
$ flutter create bug && cd bug
$ flutter run -d macos # you can quit after the application launches
$ flutter build macos --release
```
Inspect the .app file at `bug/build/macos/Build/Products/Release/bug`

**Expected results:** `bug` should be ~35MB (the size you get from a clean build)

**Actual results:** `bug` is ~65MB, and further inspection reveals `Contents/Frameworks/App.framework/.../flutter_assets/isolate_snapshot_data` and `Contents/Frameworks/App.framework/.../flutter_assets/kernel_blob.bin` within `bug`

<details>
  <summary>Logs</summary>

```bash
$ flutter doctor -v

[✓] Flutter (Channel dev, v1.16.3, on Mac OS X 10.14.6 18G103, locale en-GB)
    • Flutter version 1.16.3 at /Users/filleduchaos/flutter
    • Framework revision be3a4b37b3 (3 days ago), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)
...
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.1
...

• No issues found!
```
</details>

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Fixes https://github.com/flutter/flutter/issues/53546

When multiple build configurations output to the same build directory, the normal output cleaning process does not work. Work around this by always deleting the directory.

Explanation:

Consider two build configurations: A & B with a shared output folder `outputs/`. `A` outputs `a.dart`, `B` outputs `b.dart`.

Run `A`. `outputs/` contains `a.dart`.
Run `B`. `outputs/` contains `a.dart` and `b.dart`. 

`B` does not have any information that `a` was output by a prior build, so it cannot be removed accidentally.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
This is not a long term solution, but it does ameliorate the immediate problems.

**Review by zanderso — COMMENTED** [review]
Does this affect build times?

**Comment by jonahwilliams** [comment]
It does a little bit. I thought of a different approach - we could write a hash of the build configuration into the root of each build output. Then if the configuration file is different from the current target, we blow away the directory. (NB: the output directory (build/web, build/macos) not the build directory (.dart_tool/flutter_build/abasdasasd8saha/)

The long-long term solution is to use the unique build directories as outputs and not copy to shared locations, but that is a bigger change. I could probably start doing that for the web builds easily enough. Gradle is okay, because it is a real build system we can describe which files are inputs/outputs and which are detritus

**Review by zanderso — APPROVED** [review]
A has per config sgtm, but if this change only affects build times a little bit, landing this in the meantime lgtm.

**Comment by jonahwilliams** [comment]
Filled https://github.com/flutter/flutter/issues/53668 and https://github.com/flutter/flutter/issues/53667

**Pull request merged**
