### PR TITLE
Update cupertino_icons dependency version in pubspec.yaml template

### PR DESCRIPTION
**Pull request by prasadsunny1**
## Description

Upon creation of a new flutter project from the android studio or visual studio code :

Existing behaviour:
pubspec.yaml contains the `cupertino_icons: ^0.1.2` dependency which is old

Desired behaviour:
pubspec.yaml should contain the `cupertino_icons: ^0.1.3` dependency which is current

Changes in this PR:
I have updated version for `cupertino_icons` in the template file that generates  `pubspec.yaml` for `module` and `app`

## Related Issues

none

## Tests

none

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by prasadsunny1** [comment]
@googlebot I signed it!

**Comment by jmagman** [comment]
This seems like a good idea.  

@RedBrogdon  Do you think we should try bumping `cupertino_icons` in the samples to make sure it looks good, first?

@zanderso Likewise for examples and any other tests?

@Piinks If we updated examples would there be any golden impact?

**Comment by slightfoot** [comment]
I think this has been needed for some time. But I think the bigger issue is that [CupertinoIcons](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/cupertino/icons.dart) class is not in the package but in the main repository. Both should live together do they are kept up to date with each other. So either the CupertinoIcons class should move to this package or the font file should be moved from the external library into the framework and treat it like the MaterialIcons one.

**Comment by zanderso** [comment]
Yeah, if we're updating the templates, we should make the same changes to the examples and tests as well.

**Comment by prasadsunny1** [comment]
Shall I go ahead and update Cupertino dependency to flutter/samples repo?

**Comment by jmagman** [comment]
> Shall I go ahead and update Cupertino dependency to flutter/samples repo?

If you grep for `cupertino_icons: ^0.1.2` in the repo you'll find the example and integration tests we're referring to.

**Comment by Piinks** [comment]
> @Piinks If we updated examples would there be any golden impact?

I don't think so, and it appears all of the checks are green. Icons are usually swapped out for placeholders in golden file tests.

**Comment by Piinks** [comment]
>  it appears all of the checks are green. 

 Although I just noticed the framework tests were not triggered for this PR, let me check it out locally and test it. :)

**Comment by prasadsunny1** [comment]
> > Shall I go ahead and update Cupertino dependency to flutter/samples repo?
> 
> If you grep for `cupertino_icons: ^0.1.2` in the repo you'll find the example and integration tests we're referring to.

none found (other than ones in PR)

**Comment by jmagman** [comment]
You're right, the lock files are all up to date.  I was on stable and didn't notice.

**Review by jmagman — APPROVED** [review]
LGTM
@zanderso Any thoughts?

**Review by Piinks — APPROVED** [review]
LGTM

**Comment by zanderso** [comment]
It looks like the gallery and tests were already updated to 0.1.3, so lgtm

**Pull request merged**
