### PR TITLE
Enable landscape mode in Flutter Gallery (iOS)

### PR DESCRIPTION
**Pull request by cbracken**
Already enabled on Android.

### CODE REVIEW

**Comment by cbracken** [comment]
@chinmaygarde

**Review by chinmaygarde — APPROVED** [review]
Cool. I didn't know the gallery supported landscape.

**Comment by cbracken** [comment]
According to @Hixie this is relatively recent (for particular definitions of 'relatively' and 'recent'). I didn't take a look at the commit history to see where it happened.

**Comment by cbracken** [comment]
Looks like this broke the iOS buildbot. Build:
https://build.chromium.org/p/client.flutter/builders/Mac/builds/2898

**Comment by Hixie** [comment]
The gallery has always "supported" landscape. It's just that many things are buggy in landscape mode. But the time has come where we can't really hide behind turning it off any more and we just need to deal with it.

**Pull request merged**
