### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by owenkealey**
## Description
Hello,

* I have added the darkTheme property featured in the MaterialApp widget to the CupertinoApp widget to take advantage of automatic detection of system-wide dark mode. This is especially useful for iOS developers who use the CupertinoApp widget if they want their app to automatically change themes depending on the system's theme. Note that I am not an experienced flutter developer nor am I especially familiar with the internal workings of the engine.
## Related Issues
* darkTheme property lacking from CupertinoApp widget

## Tests
I added the following tests:

* hello_world test succeeded

## Checklist
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes ([x]). This will ensure a smooth and quick review process.

 I read the Contributor Guide and followed the process outlined there for submitting PRs.
 I signed the CLA.
 I read and followed the Flutter Style Guide, including Features we expect every widget to implement.
 I read the Tree Hygiene wiki page, which explains my responsibilities.
 I updated/added relevant documentation (doc comments with ///).
 All existing and new tests are passing.
 The analyzer (flutter analyze --flutter-repo) does not report any problems on my PR.
 I am willing to follow-up on review comments in a timely manner.
Breaking Change
Did any tests fail when you ran them? Please read Handling breaking changes.

 No, no existing tests failed, so this is not a breaking change.
 Yes, this is a breaking change. If not, delete the remainder of this section.
 I wrote a design doc: https://flutter.dev/go/template Replace this with a link to your design doc's short link
 I got input from the developer relations team, specifically from: Replace with the names of who gave advice
 I wrote a migration guide: Replace with a link to your migration guide*

### CODE REVIEW

**Comment by christopherfujino** [comment]
@owenkealey did you create your feature branch by branching off of dev? It looks like there are some regressions in the diff here.

**Comment by owenkealey** [comment]
@christopherfujino I might have forgot to update my fork before submitting the PR. Should I close and submit a new one with up to date branch?

**Comment by christopherfujino** [comment]
> @christopherfujino I might have forgot to update my fork before submitting the PR. Should I close and submit a new one with up to date branch?

Yes. The most important thing is that when creating a new branch, branch from `master`, and not a release branch.

**Comment by owenkealey** [comment]
Closing to reopen later.

**Pull request closed without merging**
