### PR TITLE
Separate theme logic

### PR DESCRIPTION
**Pull request by MahanRahmati**
When I was working on [Arna](https://github.com/MahanRahmati/Arna), I saw an opportunity to improve readability of MaterialApp. This PR separates the logic of themebuilder from materialBuilder. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by bernaferrari** [comment]
Why?

**Comment by cedvdb** [comment]
imo it makes it more readable, as someone who had never read it before seeing this PR.

**Comment by MahanRahmati** [comment]
I have no idea why Windows build_tests_3_3  failed 😞

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

**Review by HansMuller — COMMENTED** [review]
Sorry that it has taken so long to get this PR reviewed! This is a small change and I think the title may have scared off the original reviewer. 

The changes you're proposing seem reasonable. If you'd be willing to sync your PR up, I think we could land this.

**Comment by MahanRahmati** [comment]
@HansMuller Thanks for the review! I will sync it later.

**Comment by MahanRahmati** [comment]
@HansMuller It's done! 🚀

**Comment by cedvdb** [comment]
> the title may have scared off the original reviewer

🐔

**Review by HansMuller — APPROVED** [review]
LGTM

**Review by reidbaker — APPROVED** [review]

**Pull request merged**
