### PR TITLE
Always codesign when running native Xcode tests in CI

### PR DESCRIPTION
**Pull request by jmagman**
macOS 14 added new requirements that sandbox apps should be codesigned to avoid this popup:
Screenshot 2024-05-30 at 2 41 33 PM

Waiting for this UI caused macOS tests to fail on macOS 14 because the test runner forced codesigning off.  The chromium bots have the codesigning certs on them b/326078082#comment4, so always run `xcodebuild test` with codesigning.

On this PR:
[Passing `plugin_test_macos`](https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20plugin_test_macos/17320/overview)
[Passing `native_ui_tests_macos`](https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20native_ui_tests_macos/3832/overview)

Fixes framework part of https://github.com/flutter/flutter/issues/149264. I still need to investigate a fix for packages `macos_platform_tests` test.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

**Comment by vashworth** [comment]
Unfortunately, looks like this doesn't fix https://github.com/flutter/flutter/issues/149264

I ran the tests against your PR and tests still timeout with `Test runner never began executing tests after launching`

Tried it twice:
https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac%20plugin_test_macos/4/infra
https://ci.chromium.org/ui/p/flutter/builders/staging.shadow/Mac%20plugin_test_macos/5/infra

**Comment by jmagman** [comment]
Trying again with Automatic style codesigning.

**Comment by jmagman** [comment]
Closing.

**Pull request closed without merging**
