### PR TITLE
Fixes ‍‍`RenderTransform‍`'s `paint` method when `filterQuality` is not null.

### LINKED ISSUE #95091: `Transform` widget is rendered incorrectly if a `FilterQuality` is set
This simple code is a `Transform` widget that transforms a box.
If we don't set a `filterQuality` parameter, it is ok.

```
main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: Transform(
        // filterQuality: FilterQuality.medium,
        alignment: Alignment.center,
        transformHitTests: true,
        transform: Matrix4.diagonal3Values(2, 2, 0)..rotateZ(pi / 4),
        child: ConstrainedBox(
          constraints: BoxConstraints.tight(
            const Size(50, 75),
          ),
          child: const ColoredBox(
            color: Colors.orange,
          ),
        ),
      ),
    ));
  }
}
```

Screenshot from 2021-12-11 17-44-46

But if we set a `filterQuality` to it.

The result will be incorrect :

Screenshot from 2021-12-11 17-46-38

### PR DESCRIPTION
**Pull request by MohammadTaherri**
This **PR** fixes #95091.

<details><summary>Description: </summary>

This **PR** changes the behaviour of  the `paint` method of the `RenderTransform`when `RenderTransform` has a non-null `filterQuality`.

The following code is the `paint` method of `RenderTransform` :

```dart
@override
  void paint(PaintingContext context, Offset offset) {
    if (child != null) {
      final Matrix4 transform = _effectiveTransform!;
      if (filterQuality == null) {
        final Offset? childOffset = MatrixUtils.getAsTranslation(transform);
        if (childOffset == null) {
          layer = context.pushTransform(
            needsCompositing,
            offset,
            transform,
            super.paint,
            oldLayer: layer is TransformLayer ? layer as TransformLayer? : null,
          );
        } else {
          super.paint(context, offset + childOffset);
          layer = null;
        }
      } else {
        final ui.ImageFilter filter = ui.ImageFilter.matrix(
          transform.storage,
          filterQuality: filterQuality!,
        );
        if (layer is ImageFilterLayer) {
          final ImageFilterLayer filterLayer = layer! as ImageFilterLayer;
          filterLayer.imageFilter = filter;
        } else {
          layer = ImageFilterLayer(imageFilter: filter);
        }
        context.pushLayer(layer!, super.paint, offset);
      }
    }
  }
```

If `filterQuality` is not set, `paint` method uses the `pushTransform` and passes the `offset` that is passed to it to `pushTransform`.
`pushTransform` creates an `effectiveTransform` and it applies `offset` parameter.then `effectiveTransform` that is included the `offset` is passed to the `pushLayer` or canvas.

The following code is the `pushTransform` method of `PaintingContext` : 

```dart
  TransformLayer? pushTransform(bool needsCompositing, Offset offset,
      Matrix4 transform, PaintingContextCallback painter,
      {TransformLayer? oldLayer}) {
    final Matrix4 effectiveTransform =
        Matrix4.translationValues(offset.dx, offset.dy, 0.0)
          ..multiply(transform)
          ..translate(-offset.dx, -offset.dy);
    if (needsCompositing) {
      final TransformLayer layer = oldLayer ?? TransformLayer();
      layer.transform = effectiveTransform;
      pushLayer(
        layer,
        painter,
        offset,
        childPaintBounds: MatrixUtils.inverseTransformRect(
            effectiveTransform, estimatedBounds),
      );
      return layer;
    } else {
      canvas
        ..save()
        ..transform(effectiveTransform.storage);
      painter(this, offset);
      canvas.restore();
      return null;
    }
  }
```

But if `filterQuality` is set, `paint` method uses the `ImageFilterLayer`, but in this case `offset` is not applied.

Therefore I changed the behaviour of `paint` method when `filterQuality` is set.
I defined a new `effectiveFilterTransform` variable and I applied `offset` to it like `pushTransform` method.

```dart
final Matrix4 effectiveFilterTransform =
            Matrix4.translationValues(offset.dx, offset.dy, 0.0)
              ..multiply(transform)
              ..translate(-offset.dx, -offset.dy);
```

```dart
@override
  void paint(PaintingContext context, Offset offset) {
    if (child != null) {
      final Matrix4 transform = _effectiveTransform!;
      if (filterQuality == null) {
        final Offset? childOffset = MatrixUtils.getAsTranslation(transform);
        if (childOffset == null) {
          layer = context.pushTransform(
            needsCompositing,
            offset,
            transform,
            super.paint,
            oldLayer: layer is TransformLayer ? layer as TransformLayer? : null,
          );
        } else {
          super.paint(context, offset + childOffset);
          layer = null;
        }
      } else {
        final Matrix4 effectiveFilterTransform =
            Matrix4.translationValues(offset.dx, offset.dy, 0.0)
              ..multiply(transform)
              ..translate(-offset.dx, -offset.dy);

        final ui.ImageFilter filter = ui.ImageFilter.matrix(
          effectiveFilterTransform.storage,
          filterQuality: filterQuality!,
        );
        if (layer is ImageFilterLayer) {
          final ImageFilterLayer filterLayer = layer! as ImageFilterLayer;
          filterLayer.imageFilter = filter;
        } else {
          layer = ImageFilterLayer(imageFilter: filter);
        }
        context.pushLayer(layer!, super.paint, offset);
      }
    }
  }
```

</details>

<details><summary>Example:</summary>

```dart
main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: Transform(
        // filterQuality: FilterQuality.medium,
        alignment: Alignment.center,
        transformHitTests: true,
        transform: Matrix4.diagonal3Values(2, 2, 0)..rotateZ(pi / 4),
        child: ConstrainedBox(
          constraints: BoxConstraints.tight(
            const Size(50, 75),
          ),
          child: const ColoredBox(
            color: Colors.orange,
          ),
        ),
      ),
    ));
  }
}
```

| before bug fixing - without filterQuality  | Before bug fixing - with filterQuality | after bug fixing - with filterQuality | 
| ------------- | ------------- | ------------- |
| Screenshot from 2021-12-11 17-44-46  | Screenshot from 2021-12-11 17-46-38  | Screenshot from 2021-12-11 17-49-56  |
|  OK  | Not OK  | OK  |
</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by mohammadtaherri** [comment]
@goderbauer 
May I ask you to tell me how do I add a test?

**Comment by goderbauer** [comment]
You can look at some existing tests for RenderTransform and see if you could model a test case for this PR after those: https://github.com/flutter/flutter/blob/59fc92168a4596b4f523ba5774a8c5cfece6cc31/packages/flutter/test/rendering/transform_test.dart

**Comment by mohammadtaherri** [comment]
@goderbauer 
Thanks you.
I added some tests to `transform_test.dart`.
Please review this PR again.

**Comment by nt4f04uNd** [comment]
I see that @flar created a similar patch for this https://github.com/flutter/flutter/pull/95432, which has landed, so I'm closing this one.

@mohammadtaherri thanks for the contribution!

**Comment by flar** [comment]
Oh, sorry, I didn't see this other PR. I already had the fix coded when I looked through the Issues database for an issue so I didn't look if there was existing work being done on it. Another thanks to @mohammadtaherri

**Pull request closed without merging**
