### PR TITLE
Prevent ModalBottomSheet from rebuilding its child

### PR DESCRIPTION
**Pull request by enolcasielles**
## Description

This PR uses the `child` property of the `AnimatedBuilder` (as documentation explains) in order to prevent `ModalBottomSheet`'s child widget of being rebuilt needlessly.
## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change.

### CODE REVIEW

**Comment by goderbauer** [comment]
The change looks reasonable. In order to accept this PR you will have to sign the CLA (see message above) and add a test to ensure that we never regress this again. Can you please do those two things? Thanks!

**Comment by enolcasielles** [comment]
@googlebot I fixed it

**Comment by enolcasielles** [comment]
@googlebot I fixed it.

**Comment by goderbauer** [comment]
Looks like there is still a problem with the CLA. From what I can tell at my end it looks like the email address associated with the git commit doesn't match the email address you used when signing the CLA. Maybe update the email address of the commit to match? See here for instructions: https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

**Comment by enolcasielles** [comment]
@googlebot I fixed it.

**Comment by goderbauer** [comment]
Some commits in this PR still use an incorrect email address. Can you fix those as well? (Or alternatively, squash everything into one commit with the correct address.)

**Comment by enolcasielles** [comment]
@goderbauer mmmm I have updated the author of all commits but it seems that new commits were generated instead of overwriting the previous ones. I'm trying to squash all them into one single. Thanks ;)

**Comment by enolcasielles** [comment]
@goderbauer I was not able to edit email's author of existing commits or stash all into single one. So I have finally created a new pull request with a single commit  with a valid email and I'm closing this one. Here is the new PR https://github.com/flutter/flutter/pull/55832 Sorry for the mess.

**Pull request closed without merging**
