### PR TITLE
Update ios-deploy to version 1.11.0

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

Updates ios-deploy to https://github.com/ios-control/ios-deploy/commit/fcbba00cd6561deed70d235caa58ee00c1f9bbff.

## Related Issues

Will help with https://github.com/flutter/flutter/issues/60072

### CODE REVIEW

**Comment by christopherfujino** [comment]
Oops, I committed too much here, have to cleanup

**Comment by jmagman** [comment]
Xcode 12:
Screen Shot 2020-07-21 at 4 02 21 PM
🥳

**Review by jmagman — APPROVED** [review]
LGTM!

**Comment by jmagman** [comment]
`flutter install` and `flutter install --uninstall-only` also work.

**Comment by christopherfujino** [comment]
> `flutter install` and `flutter install --uninstall-only` also work.

forgot about `--uninstall-only`

**Comment by jmagman** [comment]
> > `flutter install` and `flutter install --uninstall-only` also work.
> 
> forgot about `--uninstall-only`

It's pretty new https://github.com/flutter/flutter/pull/53385.

**Pull request merged**
