### PR TITLE
[flutter_tools] pub roll

### LINKED ISSUE #85035: Breakpoints are ignored when using custom base url
I'm having a trouble with breakpoints when using flutter for web in debug mode. Everything worked fine until I had to change **base** url attribute because our application is not sitting root. 

Of course that this could be fixed by changing base during development but it is really cumbersome.  For my use case I have written a custom CI stage that changes base url before build without committing so its not a blocker.

I haven't found similar issue so I even tho it is not a blocker I decided to post an issue to possibly save some time for others when they encounter this issue. 

## Steps to Reproduce

1. Create new flutter application using `flutter create bug`.
2. Change base from `<base href="/">` to `<base href="/bug/">` inside of `<app root>/web/index.html`
3. Place a breakpoints somewhere in your application using your favourite IDE (im using **intellij** but it also happens in **vs code**)
4. Run your application in debug
5. Watch how your breakpoint is ignored

**Expected results:** My breakpoint wouldn't be ignored

**Actual results:** My breakpoints are sadly ignored

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.2 at /Users/_/Development/flutter
    • Framework revision d79295af24 (11 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/_/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

### LINKED ISSUE #102159: Flutter tools debugging with web server device is not working with chrome 100.x
See comment in https://github.com/flutter/flutter/issues/101224#issuecomment-1097565580

The issues are caused by https://github.com/dart-lang/webdev/issues/1581

Related: https://github.com/flutter/flutter/issues/101224

/cc @fhuonder

### LINKED ISSUE #102868: Package integration_test - update crypto dependency
Hello

could you please upgrade the dependencies in 'integration_test' package
https://github.com/flutter/flutter/tree/master/packages/integration_test

crypto 3.0.1 -> 3.0.2

thx

### PR DESCRIPTION
**Pull request by christopherfujino**
Pub roll that works around https://github.com/flutter/flutter/issues/102781

Fixes https://github.com/flutter/flutter/issues/102868.
Fixes https://github.com/flutter/flutter/issues/102159
Fixes https://github.com/flutter/flutter/issues/85035

This roll is needed to pick up critical upgrades to `crypto` and `dwds`

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

Thank you!!

**Comment by christopherfujino** [comment]
Looks like I need fix analysis

**Comment by christopherfujino** [comment]
@goderbauer actually, can you help me with fixing analysis on the old flutter_gallery? `package:url_launcher` deprecated an API, and I'm not sure what to do about our use of `forceSafariVC: false` in the legacy API.

```
~/git/flutter/dev/integration_tests/flutter_gallery$ flutter analyze .
Analyzing flutter_gallery...

   info • 'launch' is deprecated and shouldn't be used. Use launchUrl instead •
          lib/gallery/about.dart:28:7 • deprecated_member_use
   info • 'launch' is deprecated and shouldn't be used. Use launchUrl instead •
          lib/gallery/app.dart:125:11 • deprecated_member_use
   info • 'canLaunch' is deprecated and shouldn't be used. Use canLaunchUrl instead •
          lib/gallery/demo.dart:73:15 • deprecated_member_use
   info • 'launch' is deprecated and shouldn't be used. Use launchUrl instead •
          lib/gallery/demo.dart:74:13 • deprecated_member_use
   info • 'launch' is deprecated and shouldn't be used. Use launchUrl instead •
          lib/gallery/demo.dart:233:24 • deprecated_member_use
   info • 'launch' is deprecated and shouldn't be used. Use launchUrl instead •
          lib/gallery/demo.dart:256:24 • deprecated_member_use
   info • 'launch' is deprecated and shouldn't be used. Use launchUrl instead •
          lib/gallery/updater.dart:40:7 • deprecated_member_use
```

**Comment by christopherfujino** [comment]
This test failure is a little puzzling:

```
00:36 +634 -1: /b/s/w/ir/x/w/flutter/packages/flutter/test/material/theme_data_test.dart: ThemeData can generate a dark colorScheme from colorSchemeSeed [E]                                           
  Expected: Color:<Color(0xff9ccaff)>
    Actual: Color:<Color(0xff9ecaff)>
  
  package:test_api                                    expect
  package:flutter_test/src/widget_tester.dart 455:16  expect
  test/material/theme_data_test.dart 249:5            main.<fn>
```

**Comment by christopherfujino** [comment]
So it looks like bumping `package:material_color_utilities` caused breaking changes to our `Linux framework_tests_libraries`. @HansMuller what should I do about this?

**Comment by goderbauer** [comment]
> actually, can you help me with fixing analysis on the old flutter_gallery? package:url_launcher deprecated an API, and I'm not sure what to do about our use of forceSafariVC: false in the legacy API.

Can you cherry-pick this commit into your PR here: https://github.com/goderbauer/flutter/commit/36bfa7c0aac366e6f8ad87c89b4299ffdc074a55

**Comment by goderbauer** [comment]
> So it looks like bumping package:material_color_utilities caused breaking changes to our Linux framework_tests_libraries. @HansMuller should I just accept these changes?
>
> https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8814886108995385025/+/u/run_test.dart_for_framework_tests_shard_and_subshard_libraries/test_stdout

@darrenaustin may also be able to help here.

**Comment by darrenaustin** [comment]
> > So it looks like bumping package:material_color_utilities caused breaking changes to our Linux framework_tests_libraries. @HansMuller should I just accept these changes?

I thought we had pinned the version of this library to avoid changes like this. It would appear that the palette generation algorithm may have changed, yielding slightly different colors. @guidezpl might know more, but for now can we not update this package version?

**Comment by christopherfujino** [comment]
> > > So it looks like bumping package:material_color_utilities caused breaking changes to our Linux framework_tests_libraries. @HansMuller should I just accept these changes?
> 
> I thought we had pinned the version of this library to avoid changes like this. It would appear that the palette generation algorithm may have changed, yielding slightly different colors. @guidezpl might know more, but for now can we not update this package version?

Cool, will do.

**Comment by guidezpl** [comment]
Looping in @pennzht, is the slight change between 0.1.4. and 0.1.5 mentioned in https://github.com/flutter/flutter/pull/103220#issuecomment-1120052158 expected?

**Comment by annagrin** [comment]
@christopherfujino I need to update dwds - could you please look at https://github.com/flutter/flutter/pull/103243, we probably need to merge some changes...

**Comment by christopherfujino** [comment]
> ```
> 00:36 +634 -1: /b/s/w/ir/x/w/flutter/packages/flutter/test/material/theme_data_test.dart: ThemeData can generate a dark colorScheme from colorSchemeSeed [E]                                           
>   Expected: Color:<Color(0xff9ccaff)>
>     Actual: Color:<Color(0xff9ecaff)>
>   
>   package:test_api                                    expect
>   package:flutter_test/src/widget_tester.dart 455:16  expect
>   test/material/theme_data_test.dart 249:5            main.<fn>
> ```

Never mind, looks like I'll have to patch in your changes to this PR :)

**Comment by christopherfujino** [comment]
Re-ran windows build_tests_1_3 because of https://github.com/flutter/flutter/issues/97160

**Comment by annagrin** [comment]
thank you @christopherfujino!

**Comment by jmagman** [comment]
Ran `Mac_ios hot_mode_dev_cycle_macos_target__benchmark` locally on `pub-roll` branch and it passed:
```
Task result:
{
  "success": true,
  "data": {
    "hotReloadInitialDevFSSyncMilliseconds": 256,
    "hotRestartMillisecondsToFrame": 415,
    "hotReloadMillisecondsToFrame": 148,
    "hotReloadDevFSSyncMilliseconds": 19,
    "hotReloadFlutterReassembleMilliseconds": 127,
    "hotReloadVMReloadMilliseconds": 0,
    "hotReloadMillisecondsToFrameAfterChange": 299,
    "hotReloadDevFSSyncMillisecondsAfterChange": 70,
    "hotReloadFlutterReassembleMillisecondsAfterChange": 113,
    "hotReloadVMReloadMillisecondsAfterChange": 114,
    "hotReloadInitialDevFSSyncAfterRelaunchMilliseconds": 256,
    "hotReloadMillisecondsToFrameAfterMediumChange": 322,
    "hotReloadDevFSSyncMillisecondsAfterMediumChange": 42,
    "hotReloadFlutterReassembleMillisecondsAfterMediumChange": 167,
    "hotReloadVMReloadMillisecondsAfterMediumChange": 110,
    "hotReloadMillisecondsToFrameAfterLargeChange": 6680,
    "hotReloadDevFSSyncMillisecondsAfterLargeChange": 5498,
    "hotReloadFlutterReassembleMillisecondsAfterLargeChange": 426,
    "hotReloadVMReloadMillisecondsAfterLargeChange": 754
  },
  "detailFiles": [],
  "benchmarkScoreKeys": [
    "hotReloadInitialDevFSSyncMilliseconds",
    "hotRestartMillisecondsToFrame",
    "hotReloadMillisecondsToFrame",
    "hotReloadDevFSSyncMilliseconds",
    "hotReloadFlutterReassembleMilliseconds",
    "hotReloadVMReloadMilliseconds",
    "hotReloadMillisecondsToFrameAfterChange",
    "hotReloadDevFSSyncMillisecondsAfterChange",
    "hotReloadFlutterReassembleMillisecondsAfterChange",
    "hotReloadVMReloadMillisecondsAfterChange",
    "hotReloadInitialDevFSSyncAfterRelaunchMilliseconds",
    "hotReloadMillisecondsToFrameAfterMediumChange",
    "hotReloadDevFSSyncMillisecondsAfterMediumChange",
    "hotReloadFlutterReassembleMillisecondsAfterMediumChange",
    "hotReloadVMReloadMillisecondsAfterMediumChange",
    "hotReloadMillisecondsToFrameAfterLargeChange",
    "hotReloadDevFSSyncMillisecondsAfterLargeChange",
    "hotReloadFlutterReassembleMillisecondsAfterLargeChange",
    "hotReloadVMReloadMillisecondsAfterLargeChange"
  ],
  "reason": "success"
}
```

**Comment by Hixie** [comment]
text-exempt: rolling dependencies

**Pull request merged**
