### PR TITLE
Fix CMake invocation for 3.10 compat

### LINKED ISSUE #57409: 'Source directory does not exist' building Linux with CMake 3.10
使用 flutter run -d linux 出现了下面的问题

Launching lib/main.dart on Linux in debug mode...
CMake Error: The source directory "/home/mi/hello/build/linux/debug" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Exception: Unable to generate build files

过程：
1, mkdir hello && cd hello
2, flutter create . && flutter pub get 
3, flutter  run -d linux 

flutter version:
[✓] Flutter (Channel master, 1.19.0-2.0.pre.83, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.19.0-2.0.pre.83 at /home/mi/flutter
    • Framework revision 8abf0a6d8c (5 小时前), 2020-05-16 15:07:34 -0700
    • Engine revision aaf9e79f1d
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 2676764792)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/mi/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/mi/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2

[✓] Android Studio (version 3.6)
    • Android Studio at /home/mi/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.10.1

[✓] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.0/8,::1,127.0.0.1
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

• No issues found!

### PR DESCRIPTION
**Pull request by stuartmorgan-g**
## Description

The -S/-B format of specifying source and build directories wasn't added
until 3.13. For 3.10 compatibility, use the older form of having the
working directory as the build directory, and the last argument as the
source directory.

## Related Issues

Fixes #57409

## Tests

I added the following tests: None; updated existing tests to expect the older command line format.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by stuartmorgan** [comment]
I really need to do an end-to-end test with 3.10 to make sure there aren't other compat issues lurking that I missed in writing it, but this fixes the immediate problem. (We also need end-to-end automated testing with an Ubuntu 18.04 image, but that's already on the TODO list.)

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by MrGreenTea** [comment]
Maybe adding a version check of `cmake` in `doctor` could also be helpful?

**Comment by stuartmorgan** [comment]
> Maybe adding a version check of `cmake` in `doctor` could also be helpful?

There is already a version check.

**Pull request merged**
