### PR TITLE
Update Scrollbar widget to use CupertinoScrollbar on macOS

### LINKED ISSUE #138447: Update CupertinoScrollbar for macOS
Follow up to https://github.com/flutter/flutter/pull/138189

We auto-adapt on iOS, but not macOS. See `material/scrollbar.dart`.

---

After looking into doing this right quick, I realized it would not be so straight forward.
The CupertinoScrollbar implements the iOS spec, not the native macOS behaviors. They are different!
The Material Scrollbar that is currently shown on macOS is more like the native one (which is great! 👍 ), it supports hovering and does not change size when dragged.
If we want to auto-adapt a macOS scrollbar like we do on iOS, the CupertinoScrollbar will need to be updated to support the native behaviors from macOS.

### PR DESCRIPTION
**Pull request by EchoEllet**
*Update Scrollbar widget to use CupertinoScrollbar on macOS*

* Fix #138447

If we are using the CupertinoScrollbar by default on **iOS** then it's a good idea to use it also on **macOS** since both use the Cupertino theme system designed by Apple

[Previous PR](https://github.com/flutter/flutter/pull/138189)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by ellet0** [comment]
I will update the [scrollbar_test.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/scrollbar_test.dart) soon

I just need more info

**Comment by ellet0** [comment]
Hi @Piinks

We have four falling tests

It's all because the tests expect the `Scrollbar` widget on macOS but after this change, it's now `CupertinoScrollbar`

Example:

```dart

  testWidgets('Scrollbar showTrackOnHover', (WidgetTester tester) async {
    expect(
      find.byType(Scrollbar),
      paints..rrect(
        rrect: RRect.fromRectAndRadius(
          getStartingThumbRect(isAndroid: false),
          _kDefaultThumbRadius,
        ),
        color: _kDefaultIdleThumbColor,
      ),
    );

  },
    variant: const TargetPlatformVariant(<TargetPlatform>{
      TargetPlatform.linux,
      TargetPlatform.macOS,
      TargetPlatform.windows,
    }),
  );

```

**Review by Piinks — COMMENTED** [review]
Hi @ellet0, thanks for opening another PR.

Referring to the issue:

> The CupertinoScrollbar implements the iOS spec, not the native macOS behaviors. They are different!
The Material Scrollbar that is currently shown on macOS is more like the native one (which is great! 👍 ), it supports hovering and does not change size when dragged.
If we want to auto-adapt a macOS scrollbar like we do on iOS, the CupertinoScrollbar will need to be updated to support the native behaviors from macOS.

Do you plan to update the CupertinoScrollbar for macOS behaviors? I do not think we can adapt the scrollbar on mac until that is completed first.

**Comment by ellet0** [comment]
Sure, I noticed that, too. I will wait until the CupertinoScrollbar is updated for macOS, too, or we can close this PR

It's up to you

**Comment by Piinks** [comment]
> I will wait until the CupertinoScrollbar is updated for macOS,

I don't know that anyone is working on that right now, so I do not know when that will be updated. If you would like to work on that you are more than welcome to! Thank you!

**Comment by Piinks** [comment]
I am going to close this for now since there have not been any updates. If you would like to continue working on this, you are welcome to return to it anytime. Thank you!

**Pull request closed without merging**
