### PR TITLE
[tool] Allow downgrade when install APKs

### LINKED ISSUE #96588: Flutter tool should ask before uninstalling old version
## Use case

My application has some data synced from server in local database. Initial synchronization can take some time. If I try to run flutter in debug mode and installation fails for some reason (e.g. downgrading version, or using incorrect certificate for debug/release - easilly fixable mistakes) flutter automatically uninstalls old version and tries to install again.

```
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Performing Streamed Install
Error: ADB exited with exit code 1
adb: failed to install build/app/outputs/flutter-apk/app.apk:
Uninstalling old version...
Installing build/app/outputs/flutter-apk/app.apk...
```

This of course wipes all data and settings. Ability to abort installation could prevent this.

## Proposal

I think there 2 possible approaches for this.

1. Adding new run parameter (e.g. --force-installation), that will implement current behavior. IDE plugins could have checkbox for it
2. Installation should pause with yes/no question whether user wants to uninstall old version (no should be default IMHO as it is more safe)

Yes example:
```
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Performing Streamed Install
Error: ADB exited with exit code 1
adb: failed to install build/app/outputs/flutter-apk/app.apk:

Do you want to uninstall old version and install again? (y/N): y

Uninstalling old version...
Installing build/app/outputs/flutter-apk/app.apk...
```

No example:
```
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Performing Streamed Install
Error: ADB exited with exit code 1
adb: failed to install build/app/outputs/flutter-apk/app.apk:

Do you want to uninstall old version and install again? (y/N): n
Failed to install APK

```

### PR DESCRIPTION
**Pull request by AlexV525**
Fix #96588. Adding `-d` with `adb install` to allow version code downgrade for debuggable packages.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by AlexV525** [comment]
I'd suggest leaving the new argument as a non-opt-in behavior since it will cover more cases and provide a better installation experience.

**Comment by Hixie** [comment]
@AlexV525 You've marked this as not ready for review; is it something you'd like to land, or should we close the PR?

**Comment by AlexV525** [comment]
> @AlexV525 You've marked this as not ready for review; is it something you'd like to land, or should we close the PR?

Sorry but there is something that is hard to figure out how to test at present. I can reopen this once I have more thoughts.

**Comment by derrickgw** [comment]
This is something I would really like to see.  Testing locally is relatively easy, but  I can see how this would be hard to test automatically, depending on the test framework.  

Perhaps a more testable (and flexible) solution would be making the arguments to adb configurable.  Then the test would be "Do the configuration flags show up when I run adb?" rather than "Does adb behave as intended?".

**Pull request closed without merging**
