### PR TITLE
Avoid relative paths in .dart_tool/package_config.json when generate:true

### PR DESCRIPTION
**Pull request by sigurdm**
Instead of using package:package_config to write the .dart_tool/package_config the original json is modified and rewritten.

The .dart_tool/package_config.json file is read twice to simplify control flow.

This works around https://github.com/dart-lang/tools/issues/1538 and https://github.com/dart-lang/tools/issues/1539 and will make it easier for pub to work around: https://github.com/flutter/flutter/issues/73870 / https://github.com/dart-lang/pub/issues/2806

This also avoids the issue of package:package_config writing directly to local filesystem.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I listed at least one issue that this PR fixes in the description above.
  **This PR doesn't on its own solve any current issues, but is a step towards solving: https://github.com/flutter/flutter/issues/73870**
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
This should be fixed in package:package_config/package_config.dart and not worked around in the tool

**Comment by sigurdm** [comment]
Ok - let's wait for that.

**Comment by jonahwilliams** [comment]
Discussed with @jonasfj today, it sounds like the fix in package_config is not so clear - so lets land the workaround.

**Review by jonahwilliams — APPROVED** [review]
LGTM (if tests pass...)

**Pull request merged**
