### PR TITLE
Change elevation to double of MergeableMaterial

### LINKED ISSUE #11468: MergeableMaterial should express elevation as a double not as an int
Expressing elevation as an int is inconsistent with other uses of elevation.
It also appears that MergeableMaterial is using an obsolete system where only specific elevations are allowed.
```dart
  /// The following elevations have defined shadows: 1, 2, 3, 4, 6, 8, 9, 12, 16, 24
```

### PR DESCRIPTION
**Pull request by Abhishek01039**
Update elevation from `int` to `double`
Fixes https://github.com/flutter/flutter/issues/11468

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Abhishek01039** [comment]
Hello @Hixie 
can you please review this PR?
Thansk

**Comment by Hixie** [comment]
test-exempt: code refactor

Please don't forget to update the commit message above.

There's a bunch of places in this file that use "toDouble" that should now be redundant. We should remove those as well. (@a14n: might be worth a lint -- flagging cases where one has used toDouble() on a type we know statically to be a double, and similar, e.g. .round() on an int, or .toString() on a String)

If this lands successfully, we should also consider doing the next one up the chain, ExpansionPanel.

**Comment by Abhishek01039** [comment]
Thanks @Hixie 
I have removed those and updated the commit message

**Review by Hixie — APPROVED** [review]
LGTM, assuming the tests pass! (The Google Testing ones are the ones I'm mostly concerned about...)

**Comment by Abhishek01039** [comment]
Hey @Hixie 
I have seen you in one of the boring flutter show
you are good tutor as well as Engineer
thanks

**Comment by Abhishek01039** [comment]
> LGTM, assuming the tests pass! (The Google Testing ones are the ones I'm mostly concerned about...)

All tests passed

**Comment by MrBirb** [comment]
Why the .toDouble() for the expansion file?

**Comment by MrBirb** [comment]
Also this is probably fixes #11468

**Comment by Abhishek01039** [comment]
hello @MrBirb 
because expansion tile has `final int elevation;`

**Comment by Hixie** [comment]
we should file a bug about ExpansionPanelList using `int` for elevation now too

**Comment by Abhishek01039** [comment]
Sure @Hixie 
And please assign to me!
Thanks

**Comment by Hixie** [comment]
By "we" I meant "you", really. :-)

**Comment by Abhishek01039** [comment]
Great

**Pull request merged**
