### PR TITLE
add some exports of public API in foundation/serialization.dart

### PR DESCRIPTION
**Pull request by a14n**
Related to https://github.com/dart-lang/sdk/issues/58731 this PR exports several types from `dart:typed_data` used in the public API of `foundation/serialization.dart` library.

### CODE REVIEW

**Comment by Hixie** [comment]
This is exactly the kind of thing I was hoping we'd find.

**Comment by a14n** [comment]
If this PR is approved. How am I supposed to land it given the failure of the _Linux flutter_plugins_ check?

**Comment by Hixie** [comment]
> If this PR is approved. How am I supposed to land it given the failure of the _Linux flutter_plugins_ check?

We'll have to add a `//ignore` to that repo first.

**Review by Hixie — APPROVED** [review]
LGTM

fyi @goderbauer

**Review by goderbauer — APPROVED** [review]
LGTM

Nice!

**Comment by a14n** [comment]
> We'll have to add a //ignore to that repo first.

Could you help me to do that? I don't know which file need to be touch.
Moreover should I make this ignore change in the current Pr or another one?

**Comment by goderbauer** [comment]
You have to ignore the ignores to the files/lines mentioned in the failing check in this repository in a separate PR: https://github.com/flutter/plugins.

**Comment by jmagman** [comment]
https://github.com/flutter/plugins/pull/5922 was picked up by the roll in https://github.com/flutter/flutter/pull/105523, once that merges you can rebase on/merge that.

**Pull request merged**
