### PR TITLE
Fix animate to curve argument

### LINKED ISSUE #95743: `DraggableScrollableSheetController` ignores the curve argument
## Steps to Reproduce

Call `animateTo()` with a controller attached to a sheet and an arbitrary non-linear curve. Note that the animation is linear even though a non-linear curve was specified.

### PR DESCRIPTION
**Pull request by caseycrogers**
This PR adds a test to ensure the curve argument is applied to the animation and then fixes the animateTo function. Credit to jyardin for the code changes to the animateTo function.

Fixes #95743

This is a replica of #95744 because I accidentally polluted it with a bunch of commits.

cc @dnfield 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by caseycrogers** [comment]
@dnfield do you mind merging this?

**Comment by dnfield** [comment]
Merging on the basis that a prior version of this patch was LGTM'd already by goderbauer, and this version was only created to fix GitHub related issues with the previous one.

**Review by jambestwick — COMMENTED** [review]
vi

**Pull request merged**
