### PR TITLE
Add capability to run build_runner tests for tool

### LINKED ISSUE #27964: Support build_runner test for flutter_tools tests
This will possibly speed up execution in CI and allow us to shard more easily.

cc @dnfield

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Allows compiling tests to kernel and running them via `flutter packages pub run build_runner test`

## Related Issues

Fixes https://github.com/flutter/flutter/issues/27964

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
RSLGTM

Pretty excited about this. Is this all that's needed to now do the build runner version of the command?  Do we have plans to follow it up so that becomes the default way of running the command?

**Comment by jonahwilliams** [comment]
I'm not sure what you mean by the default - we can't really replace pub run test, but we should update cirrus config and instructions so that we can pbr test

**Comment by dnfield** [comment]
Sorry I was thinking of Flutter test.  That makes sense.

**Comment by jonahwilliams** [comment]
flutter_test is a different can of worms. We can chat about it tomorrow, but essentially there are some constraints based on the method used to generate kernel.

Its theoretically possible, but not today.

**Pull request merged**
