### PR TITLE
CP: Manually update DWDS to 21.0.0+1 to fix null-cast error when debugging from VS Code 

### LINKED ISSUE #2297: Getting DWDS error when deubg on web
Getting DWDS error when deubg on web on every object which i what to see properties

Screenshot 2023-12-06 at 8 38 34 AM

```console
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.2 23C5055b darwin-arm64, locale en-US)
    • Flutter version 3.16.2 on channel stable at /Users/burhankhanzada/Development/Google/Flutter/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (5 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/burhankhanzada/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 15A5160n
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.2 23C5055b darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

### PR DESCRIPTION
**Pull request by elliette**
Update DWDS version on Flutter stable to a hotfix release to resolve https://github.com/dart-lang/webdev/issues/2297

See https://github.com/dart-lang/webdev/pull/2319

### CODE REVIEW

**Comment by itsjustkevin** [comment]
Shouldn't the pubspec checksum be updated when changing versions?  We might want to hold off on these until next week.

**Comment by christopherfujino** [comment]
the merge target should be a release-candidate branch, also, not `stable`. I'm guessing the branch should be: `flutter-3.16-candidate.0`? Per https://github.com/flutter/flutter/blob/stable/bin/internal/release-candidate-branch.version

**Comment by elliette** [comment]
> Shouldn't the pubspec checksum be updated when changing versions? We might want to hold off on these until next week.

How do I update the pubspec checksum?

**Comment by christopherfujino** [comment]
> > Shouldn't the pubspec checksum be updated when changing versions? We might want to hold off on these until next week.
> 
> How do I update the pubspec checksum?

Probably the best way to do so for release cherry picks would be to use:

`flutter update-packages --cherry-pick-package=dwds --cherry-pick-version='21.0.0+1'`

This will ensure ONLY dwds is changed, and that the checksum is written.

**Comment by elliette** [comment]
Thanks! Updated the checksum

**Review by christopherfujino — APPROVED** [review]
LGTM thanks!

**Pull request merged**
