### PR TITLE
Move mockito to 3.0.0-alpha.

### PR DESCRIPTION
**Pull request by aam**
This is needed so it matches mockito version used internally.

### CODE REVIEW

**Comment by aam** [comment]
@srawlins , what do you think?

**Comment by aam** [comment]
@cbracken this will be needed for flutter roll into google3

**Comment by jonahwilliams** [comment]
@aam make sure to run `flutter update-packages --force-upgrade`...it appears I did not correctly implement my analysis check to fail the build when they are out of date

**Comment by srawlins** [comment]
Looks good!

**Comment by aam** [comment]
@jonahwilliams I didn't run `--force-upgrade` to minimize amount of changes. But I just tried running it now and it seems that `update-packages --force-upgrade` doesn't like `mockito: 3.0.0-alpha+2`, reverts it back to `2.2.3`. Not sure what the deals is with that.

**Comment by jonahwilliams** [comment]
@aam Looks like the issue there is that analysis_server and front_end both use ^2.0.2 and we pin to the same version.  I'll take this up as a separate issue, since we should be able to depend on different versions of a dev_dependency.

**Comment by cbracken** [comment]
LGTM'ed by IM, but for the record:
lgtm

**Comment by Hixie** [comment]
If you want to pin a particular package to a particular version, there's a map you edit in `update_packages.dart`.

**Comment by aam** [comment]
@Hixie wrote
> If you want to pin a particular package to a particular version, there's a map you edit in update_packages.dart.

Not sure what to make out of response on https://github.com/dart-lang/mockito/issues/110, except perhaps it's clear that existing process of adding an override with cleanup TODO is not universally accepted.

**Pull request merged**
