### PR TITLE
Make NavigationRail.selectedIndex nullable

### LINKED ISSUE #95330: NavigationRail support no active destination
## Use case

`NavigationRail` currently requires a `selectedIndex`, so there is no way to not have an active destination. For my application, on large screens, I'd like the navigation rail to be visible for non-top-level pages or pages otherwise not in the navigation rail.

The material spec does not mention there having to be an active destination ([M2](https://material.io/components/navigation-rail), [M3](https://m3.material.io/components/navigation-rail/guidelines)).

An example from Google Contacts:

image

After clicking the Create contact FAB:

image

Note that there is no active destination in the rail.

## Proposal

Make `NavigationRail.selectedIndex` nullable to support having no active destination for `NavigationRail`.

This seems like a simple change that only requires some `null` checks:

https://github.com/flutter/flutter/blob/935d1478aac8329016846131c4d0091ed011be87/packages/flutter/lib/src/material/navigation_rail.dart#L478

https://github.com/flutter/flutter/blob/935d1478aac8329016846131c4d0091ed011be87/packages/flutter/lib/src/material/navigation_rail.dart#L359-L363

I can set up a PR for this.

### PR DESCRIPTION
**Pull request by Jjagg**
This PR makes `NavigationRail.selectedIndex` nullable so `NavigationRail` supports not having an active destination.
The test uses the `Semantics` to check for `selected` because the `_RailDestination` widget is private, I hope that's okay.

Fixes #95330.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by HansMuller — COMMENTED** [review]
This looks OK to me however some additional unit tests should cover rebuilding a rail where the selectedIndex changes from non-null to null and null to non-null, in the simple case where we wait for the animations to finish, and in the case where the change happens in the middle of the transition animation.

**Comment by HansMuller** [comment]
Looking at this again, the use case is a little odd - since the rail is intended to show the user which view they're looking at (they've navigated to), and they're typically looking at something. It's also inconsistent with [BottomNavigationBar.currentIndex](https://api.flutter.dev/flutter/material/BottomNavigationBar/currentIndex.html), which is non-nullable.

**Comment by Jjagg** [comment]
Thanks for taking a look @HansMuller :)

> Looking at this again, the use case is a little odd

My situation is the following: I have some top-level navigation items that I want to always be visible on big screens, also on pages that are not top-level navigation items. How do I handle this? The Material spec on the navigation rail doesn't mention having no selected destination, but I've found a few examples of applications using this design (all on a big screen):

- Google Contacts example in the issue (#95330)
- [Google News](https://news.google.com/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRFZxYUdjU0FtVnVHZ0pWVXlnQVAB?hl=en-US&gl=US&ceid=US%3Aen) (by clicking more headlines on the home page)
- [Google Photos](https://photos.google.com/settings) (settings page)
- [Google Finance](https://www.google.com/finance/quote/QCOM:NASDAQ)
- twitter.com (e.g. open a tweet)
- Windows Spotify client app

The Google examples all use a navigation drawer instead of a navigation rail, but the pattern is the same.
The latter two don't use Material design, but I think they show how the pattern can be useful for Flutter devs.

`BottomNavigationBar` is only for mobile or small tablets according to [Material 3](https://m3.material.io/components/navigation-bar/guidelines). You'd typically push pages that are not in the nav over the page with the navigation bar, hiding its state. So I think this issue is less relevant there.

**Comment by HansMuller** [comment]
@Jjagg - sorry it's taken so long to get to this.   I agree that the example in #95330 does imply the need for `selectedIndex == null`. If you're still interested in this PR, it still needs the tests requested in https://github.com/flutter/flutter/pull/95336#issuecomment-995066529

**Comment by skia-gold** [comment]
Gold has detected about 24 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/95336

**Comment by Jjagg** [comment]
No worries @HansMuller, and sorry for the delay on my end. I added a test for animating from/to selectedIndex null (based on label opacity). 

> in the case where the change happens in the middle of the transition animation

I'm not 100% sure I understood this correctly. Do you mean for a case like I covered in d8e93b28405cc38c6d70546345ca655e18591f49? I can add some other tests like that one if required.

**Review by HansMuller — APPROVED** [review]
@Jjagg - thanks for adding the additional tests, this change LGTM

**Pull request merged**
