### PR TITLE
Fix document of the switch

### PR DESCRIPTION
**Pull request by AAkira**
The description of track color in Switch was incorrect.

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/switch.dart#L581-L597

### CODE REVIEW

**Comment by AAkira** [comment]
@googlebot I signed it!

**Review by YazeedAlKhalaf — APPROVED** [review]
# Thanks for the contribution! 🚀

lgtm_transparent

**Review by darrenaustin — APPROVED** [review]
@AAkira thanks for the doc fix. 

We are trying to migrate all of these colors to be based off `ColorScheme` colors, but for now it is better to document the existing defaults correctly.

**Comment by Hixie** [comment]
test-exempt: only affects comments

**Comment by soffieprincess07** [comment]
> It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need an exemption to this rule, contact Hixie on the #hackers channel in [Chat](https://github.com/flutter/flutter/wiki/Chat).
> 
> If you are not sure if you need tests, consider this rule of thumb: the purpose of a test is to make sure someone doesn't accidentally revert the fix. Ask yourself, is there anything in your PR that you feel it is important we not accidentally revert back to how it was before your fix?
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.

**Pull request merged**
