### PR TITLE
Roll engine ecabc1037652..060a7733a654 (2 commits)

### PR DESCRIPTION
**Pull request by engine-flutter-autoroll**
https://github.com/flutter/engine/compare/ecabc1037652...060a7733a654

git log ecabc1037652..060a7733a654 --first-parent --oneline
2020-02-26 iska.kaushik@gmail.com Roll fuchsia/sdk/core/linux-amd64 from QU3ft... to 94el1... (flutter/engine#16821)
2020-02-26 skia-flutter-autoroll@skia.org Roll src/third_party/skia f0a13d04c233..7f5e3c7e43c7 (6 commits) (flutter/engine#16810)

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/flutter-engine-flutter-autoroll
Please CC chinmaygarde@google.com on the revert to ensure that a human
is aware of the problem.

To report a problem with the AutoRoller itself, please file a bug:
https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+/master/autoroll/README.md

### CODE REVIEW

**Comment by rmistry** [comment]
@dnfield Looks like this is stuck waiting for the mergebot to land it? maybe it got confused because of the "skipped" test?

**Comment by jonahwilliams** [comment]
I'll land it in the meantime...

**Comment by dnfield** [comment]
@keyonghan recently switched this to check the Cirrus API instead of GitHub.  Maybe that's not working in this case.

**Comment by keyonghan** [comment]
Yes. The culprit is the SKIPPED status for cirrus tasks. 
From https://github.com/cirruslabs/cirrus-ci-web/blob/master/schema.graphql#L120, there is no SKIPPED status listed, so I din't include that in our logic.
Filed issue https://github.com/cirruslabs/cirrus-ci-web/issues/157 to track.

I will create a PR to fix.

**Comment by keyonghan** [comment]
@dnfield @rmistry  Following https://github.com/cirruslabs/cirrus-ci-web/blob/master/schema.graphql#L569-L579

Is the following category correct:
failure: 'ABORTED', 'FAILED'
in progress: 'CREATED',  'TRIGGERED', 'SCHEDULED', 'EXECUTING'
success: 'COMPLETED', 'SKIPPED', 'PAUSED'

**Comment by dnfield** [comment]
That all seems straightforward to me _except for_ `PAUSED`.  Is that really success?

Another possibility here is that GitHub has been having service issues in the last couple days...

**Comment by keyonghan** [comment]
'PAUSED' is the one that confuses me too. Not sure which category shall we put it.

**Comment by keyonghan** [comment]
@fkorotkov could you help share your input?

**Comment by fkorotkov** [comment]
@keyonghan it's used for [manual tasks](https://cirrus-ci.org/guide/writing-tasks/#manual-tasks). IMO it should be in the same category as `CREATED `.

**Pull request merged**
