### PR TITLE
Bump Dart SDK to `1.23.0-dev.11.11`.

### PR DESCRIPTION
**Pull request by pq**
Keeping up with the latest internal roll.

@tvolkert @abarth @Hixie

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by tvolkert** [comment]
LGTM!

**Comment by pq** [comment]
Awesome.  Regarding the `flutter-build` [mac failure](https://build.chromium.org/p/client.flutter/waterfall?show=Mac), is that safe to ignore and land?

**Comment by Hixie** [comment]
Well we shouldn't ignore it. But let's pick a harmless PR and land it and see if the failure was just a flake. I'll find one to land.

**Comment by pq** [comment]
We're still failing on changes unrelated to this one...  Thoughts on landing?

@Hixie @abarth @tvolkert

**Comment by Hixie** [comment]
@pq https://flutter.io/design-principles/#code-review-and-checking-in-code talks about the rules around landing things when red... basically the rule is, figure out why it's red, then fix it, and don't land anything else in the meantime :-)

**Comment by pq** [comment]
@Hixie wrote: "EVERYONE LAND EVERYTHING" (and so I did 👍 )

**Pull request merged**
