### PR TITLE
Support double tap and long press to select ChoiceChip, FilterChip, InputChip (#157752)

### PR DESCRIPTION
**Pull request by benji-farquhar**
This is a proposed solution to https://github.com/flutter/flutter/issues/157752, just for the ChoiceChip for now. I will add to the other selection chips, `SelectableChipAttributes`, documentation and tests once someone has confirmed this is an acceptable approach. 

It can be tested by pasting this into a new project:

```
import 'package:flutter/material.dart';

/// Flutter code sample for [ActionChoice].

void main() => runApp(const ChipApp());

class ChipApp extends StatelessWidget {
  const ChipApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
          colorSchemeSeed: const Color(0xff6750a4), useMaterial3: true),
      home: const ActionChoiceExample(),
    );
  }
}

class ActionChoiceExample extends StatefulWidget {
  const ActionChoiceExample({super.key});

  @override
  State<ActionChoiceExample> createState() => _ActionChoiceExampleState();
}

class _ActionChoiceExampleState extends State<ActionChoiceExample> {
  int? _singleTapValue = 1;
  int? _doubleTapValue = 1;
  int? _longPressValue = 1;
  int? _doubleTapAndLongPress = 1;
  int? _allThreeValue = 1;

  @override
  Widget build(BuildContext context) {
    final TextTheme textTheme = Theme.of(context).textTheme;

    return Scaffold(
      appBar: AppBar(
        title: const Text('ActionChoice Sample'),
      ),
      body: Center(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('Single tap', style: textTheme.labelLarge),
            const SizedBox(height: 10.0),
            Wrap(
              spacing: 5.0,
              children: List<Widget>.generate(
                3,
                (int index) {
                  return ChoiceChip(
                    label: Text('Item $index'),
                    selected: _singleTapValue == index,
                    onSelected: (bool selected) {
                      setState(() {
                        _singleTapValue = selected ? index : null;
                      });
                    },
                  );
                },
              ).toList(),
            ),
            Text('Double tap', style: textTheme.labelLarge),
            const SizedBox(height: 10.0),
            Wrap(
              spacing: 5.0,
              children: List<Widget>.generate(
                3,
                (int index) {
                  return ChoiceChip(
                    label: Text('Item $index'),
                    selected: _doubleTapValue == index,
                    selectGestures: const {SelectGesture.doubleTap},
                    onSelected: (bool selected) {
                      setState(() {
                        _doubleTapValue = selected ? index : null;
                      });
                    },
                  );
                },
              ).toList(),
            ),
            Text('Long press', style: textTheme.labelLarge),
            const SizedBox(height: 10.0),
            Wrap(
              spacing: 5.0,
              children: List<Widget>.generate(
                3,
                (int index) {
                  return ChoiceChip(
                    label: Text('Item $index'),
                    selected: _longPressValue == index,
                    selectGestures: const {SelectGesture.longPress},
                    onSelected: (bool selected) {
                      setState(() {
                        _longPressValue = selected ? index : null;
                      });
                    },
                  );
                },
              ).toList(),
            ),
            Text('double tap & long press', style: textTheme.labelLarge),
            const SizedBox(height: 10.0),
            Wrap(
              spacing: 5.0,
              children: List<Widget>.generate(
                3,
                (int index) {
                  return ChoiceChip(
                    label: Text('Item $index'),
                    selected: _doubleTapAndLongPress == index,
                    selectGestures: const {SelectGesture.doubleTap, SelectGesture.longPress},
                    onSelected: (bool selected) {
                      setState(() {
                        _doubleTapAndLongPress = selected ? index : null;
                      });
                    },
                  );
                },
              ).toList(),
            ),
            Text('All three', style: textTheme.labelLarge),
            const SizedBox(height: 10.0),
            Wrap(
              spacing: 5.0,
              children: List<Widget>.generate(
                3,
                (int index) {
                  return ChoiceChip(
                    label: Text('Item $index'),
                    selected: _allThreeValue == index,
                    selectGestures: const {SelectGesture.doubleTap, SelectGesture.longPress, SelectGesture.tap},
                    onSelected: (bool selected) {
                      setState(() {
                        _allThreeValue = selected ? index : null;
                      });
                    },
                  );
                },
              ).toList(),
            ),
          ],
        ),
      ),
    );
  }
}

```

### CODE REVIEW

**Comment by BenjiFarquhar** [comment]
We could also use booleans rather than the new enum: `selectOnTap`, `selectOnDoubleTap`, `selectOnLongPress`

**Comment by TahaTesser** [comment]
Hi @BenjiFarquhar 
Thanks for your contribution. I'm afraid this would create a fairly verbose API for a niche use case. This would be done through composition. You would be achieve similar results yourself by wrapping chips with your own gesture callbacks.

**Comment by justinmc** [comment]
Good point @TahaTesser, I'm interested in your thoughts @BenjiFarquhar.

**Comment by nate-thegrate** [comment]
The Material 3 site has a page going over double tap/long press: https://m3.material.io/foundations/interaction/gestures
Unfortunately, it just describes the gestures and doesn't specify which components they apply to.

I agree that this might be a bit too niche to be included in the `Chip` API (though I'm sort of biased in favor of making custom widgets most of the time). IMO this would be pretty easy to pull off by wrapping an `InkWell` with a `Material`, and using chip theme data if desired.

**Comment by BenjiFarquhar** [comment]
@TahaTesser, @justinmc, @nate-thegrate 

Fair enough guys, thanks for looking into it. As suggested, I've implemented it by wrapping a `RawChip` with an `InkWell`.

**Pull request closed without merging**
