### PR TITLE
Add more exceptinal condition for ProgressIndicator

### PR DESCRIPTION
**Pull request by gtgalone**
Seen in #140754

### CODE REVIEW

**Comment by bernaferrari** [comment]
Would be good if you added a test

**Comment by gtgalone** [comment]
@bernaferrari Thanks but how to add test?

**Comment by bernaferrari** [comment]
Pass double to infinity and expect the assert. Check what I did on border test (search for uniform border)

**Comment by bernaferrari** [comment]
Could as well just clamp(0, 100)

**Comment by gtgalone** [comment]
Thanks!

I am just trying to run test but this logs error cannot install packages because of version conflict. Is there any way for this?

```
[packages/flutter] flutter pub get --no-example
Resolving dependencies...
Note: web is pinned to version 0.3.0 by flutter_goldens from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because flutter depends on flutter_goldens from sdk which depends on web 0.3.0, web 0.3.0 is required.
So, because flutter depends on web 0.4.0, version solving failed.
exit code 1

--

[packages/flutter] flutter pub get --no-example
Resolving dependencies...
Note: process is pinned to version 4.2.4 by flutter_goldens from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because flutter depends on flutter_goldens from sdk which depends on process 4.2.4, process 4.2.4 is required.
So, because flutter depends on process 5.0.1, version solving failed.
exit code 1

--

[packages/flutter] flutter pub get --no-example
Resolving dependencies...
Because process ^4.0.0 depends on file ^6.0.0 and flutter depends on file 7.0.0, process ^4.0.0 is forbidden.
So, because flutter depends on process 4.2.4, version solving failed.
exit code 1

--

[packages/flutter] flutter pub get --no-example
Resolving dependencies...
Note: web is pinned to version 0.3.0 by flutter_goldens from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because flutter depends on flutter_goldens from sdk which depends on web 0.3.0, web 0.3.0 is required.
So, because flutter depends on web 0.4.0, version solving failed.
exit code 1
```

**Comment by bernaferrari** [comment]
You must run the new flutter, not your old flutter. It is like bin/flutter ../../packages/flutter/tests but there are other ways too

**Comment by gtgalone** [comment]
Thanks! I just push test code.

```
➜  flutter git:(progress-indicator-exception) ✗ flutter test test/material/progress_indicator_test.dart         
00:06 +46: All tests passed! 
```

**Comment by bernaferrari** [comment]
What if you clamped the values? Possibly makes more sense

**Comment by gtgalone** [comment]
Where should I add clamp function to value?

**Comment by bernaferrari** [comment]
Yes, because then -1 becomes 0 instead of a weird value. Probably easy to predict.

**Comment by bernaferrari** [comment]
I prefer clamp. But if the other reviewer prefers the assert, this is what you could do:
https://github.com/flutter/flutter/blob/3df4e735d5d0bd2db7930098eba1b3e620d77aa0/packages/flutter/lib/src/painting/circle_border.dart#L34

**Comment by gtgalone** [comment]
I got it. I can add assert. if other reviewers want to use assert like this below. Just let me know.

```dart
String? expandedSemanticsValue = semanticsValue;
if (value != null) {
  assert(value! >= 0.0, 'The value argument $value is not greater than or equal to zero.');
  assert(value! <= 1.0, 'The value argument $value is not less than or equal to one.');
  expandedSemanticsValue ??= '${(value! * 100).round()}%';
}
```

**Comment by bernaferrari** [comment]
You would add the assert in the constructor, if you go that path.. But probably just wait for the next reviewer lol but I bet they will prefer the assert

**Comment by gtgalone** [comment]
Is it possible to add value assert in constructor? value is nullable.

**Comment by bernaferrari** [comment]
Good question. You could do "value == null ||..."

**Comment by gtgalone** [comment]
Thanks! I will use like that if I need to use assert!

**Comment by bernaferrari** [comment]
?

**Comment by gtgalone** [comment]
@bernaferrari Check this #140754

**Pull request closed without merging**
