### PR TITLE
[flutter_releases] Flutter 1.25.0-8.3.pre framework cherrypicks

### PR DESCRIPTION
**Pull request by pcsosinski**
## Scheduled Cherrypicks

* update engine
  * https://github.com/flutter/engine/commit/7a8f8ca02c276dce02f8dd42a44e776ac03fa9bc

* [CupertinoDatePicker] Selection background is broken for mode "time" and "dateAndTime" · Issue #73203
  * 35af0d7b1b015b9b0341f6ae6b3ef7732b78a86f
* Cupertino Icons draws the wrong icon that you selected in the code · Issue #72237
  * 795b23ef44b60bdb9b4764b00d4f3a16a87b65bb 
* Add minimum recommended version of Xcode to doctor · Issue #73801 
  * 7c75c01fc3e2affb22b35ee6e35e73700c6715e1 

## Known Presubmit Failures

* LUCI `customer_testing` depends on a script in the recipes repo that clones customer_testing from HEAD

## Known Postsubmit Failures

* `ios_app_with_extensions_test` failed with an infra failure that was fixed upstream with: https://github.com/flutter/flutter/pull/73442/files

### CODE REVIEW

**Comment by jmagman** [comment]
```
 'Xcode' is from 'package:flutter_tools/src/macos/xcode.dart' ('packages/flutter_tools/lib/src/macos/xcode.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'majorVersion'.
    if (boolArg('xcframework') && globals.xcode.majorVersion < 11) {
```
Patch:
[xcode-11.diff.txt](https://github.com/flutter/flutter/files/5817382/xcode-11.diff.txt)

**Comment by christopherfujino** [comment]
manually set label `cla: yes` because all commit authors have already signed the CLA.

**Comment by skia-gold** [comment]
Gold has detected about 14 untriaged digest(s) on patchset 5.
View them at https://flutter-gold.skia.org/cl/github/73985

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by pcsosinski** [comment]
customer testing failing as expected / 33 failures related to pre-submit recipe changes at master that we expect to pass on post-submit (branched recipes)

**Comment by christopherfujino** [comment]
`ios_app_with_extensions_test` failed post-submit with an infra failure that was fixed upstream with: https://github.com/flutter/flutter/pull/73442/files

**Pull request merged**
