### PR TITLE
[cherry pick] Use PorterDuff blend mode when below Android 29

### PR DESCRIPTION
**Pull request by bparrishMines**
Part of: https://github.com/flutter/flutter/issues/108136

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by XilaiZhang** [comment]
umm looks like some tests are failing

**Comment by bparrishMines** [comment]
The failures looks like they are unrelated to the engine change in my specific PR. I'm assuming this could be caused by the other engine changes that are included in using this specific commit. Would the solution to this be to find the earliest engine commit that passes tests and includes the cherry-picked PR?

**Comment by XilaiZhang** [comment]
> The failures looks like they are unrelated to the engine change in my specific PR. I'm assuming this could be caused by the other engine changes that are included in using this specific commit. Would the solution to this be to find the earliest engine commit that passes tests and includes the cherry-picked PR?

umm this doesn't sound correct to me, maybe @itsjustkevin and @CaseyHillers would have better idea?

**Comment by CaseyHillers** [comment]
@bparrishMines you'll need to open the engine PR, and then manually roll the branched engine change into this branch.

In its current state, you're fast forwarding the engine to the commit on ToT.

**Pull request closed without merging**
