### PR TITLE
Handle lifecycle and navigation platform messages

### PR DESCRIPTION
**Pull request by abarth**
Soon the engine will send this information through platform messages.

### CODE REVIEW

**Comment by abarth** [comment]
@chinmaygarde @jason-simmons @Hixie

**Review by chinmaygarde — APPROVED** [review]

**Comment by Hixie** [comment]
LGTM but I'm really not a fan of all these strings. We're losing static type checking and we're doing string comparisons, both of which are bad juju.

**Comment by abarth** [comment]
> I'm really not a fan of all these strings. We're losing static type checking and we're doing string comparisons, both of which are bad juju.

Maybe we should make our own mojo called juju.  :)

I'm open to suggestions about how to approach this problem.

**Comment by Hixie** [comment]
Yeah I don't have a better suggestion. Mojo solved this problem my code-generating parsers that enforced type correctness. That seems like overkill here.

**Comment by chinmaygarde** [comment]
_Don't know why an email reply to the comment didn't show up in this thread. Pasting the reply again._

> Maybe we should make our own mojo.

Yes! JSON for platform/language interoperability was making me super uncomfortable as well. I didn’t think that decision was open for debate. I do agree Mojo was overkill for our needs. And it was trying to solve for a different and/or broader use-case. The JSON approach is easier in its implementation but hardly less error prone or verbose.

How about a dead simple IDL that can deal with basic types and collections (we don’t even need to deal with object graphs)? It can generate stubs for various languages that we fill in. Isn’t that all we need? We will have to manage threading and serialization/deserialization of arguments and return types. But it should make for a safer and less verbose scheme.

I would love to take a stab at such a scheme. Though I do understand if we want to stick with what we have got. Its ugly but there is no doubt it works.

**Comment by chinmaygarde** [comment]
Yes! JSON for platform/language interoperability was making me super uncomfortable as well. I didn’t think that decision was open for debate. I do agree Mojo was overkill for our needs. And it was trying to solve for a different and/or broader use-case. The JSON approach is easier in its implementation but hardly less error prone or verbose.

How about a dead simple IDL that can deal with basic types and collections (we don’t even need to deal with object graphs)? It can generate stubs for various languages that we fill in. Isn’t that all we need? We will have to manage threading and serialization/deserialization of arguments and return types. But it should make for a safer and less verbose scheme.

I would love to take a stab at such a scheme. Though I do understand if we want to stick with what we have got. Its ugly but there is no doubt it works.

Chinmay

**Comment by Hixie** [comment]
All decisions are open for debate.

**Pull request merged**
