### PR TITLE
Pass bottomsheet child into AnimatedBuilder.

### PR DESCRIPTION
**Pull request by KlausJokisuo**
## Description

*This will fix performance issue when closing / opening / moving bottomsheet.  Moved BottomSheet child into AnimatedBuilder child so no useless builds are done with the child. This PR should give a major performance boost to bottomsheet*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by dnfield** [comment]
@rami-a might be better for this as it impacts the new shape stuff

**Review by rami-a — APPROVED** [review]
LGTM from the theming and shape perspective. @dnfield could you also take a look and determine if this affects the scrollable bottom sheet behavior?

**Comment by HansMuller** [comment]
@KlausJokinen - do you have a benchmark that demonstrates how much of a performance improvement this change yields? On the face of it it appears that the BottomSheet would be built more often than before, since we were not building each time the Route's animation ticked before.

**Comment by KlausJokinen** [comment]
> @KlausJokinen - do you have a benchmark that demonstrates how much of a performance improvement this change yields? On the face of it it appears that the BottomSheet would be built more often than before, since we were not building each time the Route's animation ticked before.

Sorry I don't have any benchmarks at the moment. Mostly how I tested was to add a lot of widgets into BottomSheet and drag it up and down and check performance profiler what it's rebuilding. Before assigning sheet content into animatedbuilder child it was rebuilding all widgets causing lag if there was a lot of them.

**Comment by dnfield** [comment]
Could you look at adding a performance benchmark for this?  Starting from https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/complex_layout_scroll_perf__timeline_summary.dart and https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/perf_tests.dart might help.

It'd be especially nice if you could add the benchmark in a separate PR so we could measure the performance impact of this PR.  It would also mean we won't risk regressing this case in the future.

**Comment by dnfield** [comment]
This now has some merge conflicts, and could still really do with a benchmark so we make sure not to regress it.  Do you plan to continue with that?

**Comment by HansMuller** [comment]
@KlausJokinen I'm going to close this for now. If you have time to create a benchmark that demos the advantages of this change, please reopen the PR. Thanks for contribution!

**Pull request closed without merging**
