### PR TITLE
[flutter_tools] use -f when fetching tags

### LINKED ISSUE #57396: [flutter_tools] "would clobber existing tag" when trying to fetch tags
Split off from https://github.com/flutter/flutter/issues/56853#issuecomment-629625117.

From @larssn:

```
ProcessException: Process exited abnormally:
From https://github.com/flutter/flutter
 ! [rejected]            v1.7.8+hotfix.1 -> v1.7.8+hotfix.1  (would clobber existing tag)
  Command: git fetch --tags
```

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Fixes https://github.com/flutter/flutter/issues/57396

use `-f` to overwrite local tags

### CODE REVIEW

**Comment by christopherfujino** [comment]
Do you think this could happen for any reason other than a user arbitrarily tagging a random commit `1.2.3`?

**Comment by jonahwilliams** [comment]
Perhaps if we deleted/recreated a tag or something? It happened to me locally when checking out flutter though, so it could happen to anyone

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
> Perhaps if we deleted/recreated a tag or something? It happened to me locally when checking out flutter though, so it could happen to anyone

Actually yeah, I think we fixed a tag on the wrong revision. LGTM

**Pull request merged**
