### PR TITLE
Provide an observatory extension to evict resources

### PR DESCRIPTION
**Pull request by Hixie**
...so that you can use hot reload mode to update assets.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @johnmccutchan

**Comment by johnmccutchan** [comment]
ACK. I'll ping this once I've tested it and have it working for hot mode.

**Comment by johnmccutchan** [comment]
This appears to work and I have my side of the work in https://github.com/flutter/flutter/pull/5303

Some comments:
1. I sent an asset eviction notice for anything that has changed in the asset bundle, this means we might clear the image cache when no images were changed.

2. I don't know if a reassemble is enough to get the new assets to display. I had to dismiss the about window and then bring it back up to see the change.

**Comment by johnmccutchan** [comment]
LGTM

**Comment by Hixie** [comment]
I've updated it to make sure the images reload.

I wish there was a good way to only evict the changed images, but I'm not really seeing a clean way to do that. The cache doesn't use the same keys as the asset bundle, so the asset bundle key (which is what we get over the observatory message) doesn't really help you clear out the image cache. I considered a callback on the asset bundle cache that the image provider could use to then signal the cache but that way lies madness (you have to know when to unregister the callback, for example).

**Comment by johnmccutchan** [comment]
Performance in shrine and pesto is very nice even without a more selective image cache eviction.

**Pull request merged**
