### PR TITLE
Fix the calculation of image heights in ImageFit.scaleDown mode

### LINKED ISSUE #4407: Pesto: Scrolling the app bar should smoothly scale the logo
On iOS and Android, as I scroll the list of recipes in pesto, I see the app bar's logo image move and then pop from logo+title to just logo.

We should look for a way to smoothly scale the logo+title as the user scrolls. A good example of smoothly scaling would be the "Flutter gallery" title on the home screen of the gallery.

To see the scaling in action, see https://polymerelements.github.io/app-layout/templates/pesto/#/home and narrow your browser window. Then, scroll up and down. You'll see the pesto logo scaling in and out as the list of recipes is scrolled up and down.

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/4407

### CODE REVIEW

**Comment by chinmaygarde** [comment]
lgtm

**Comment by Hixie** [comment]
this should have a test. we've gotten this code wrong several times already :-)

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
I made this function testable in https://github.com/flutter/flutter/pull/5158.

**Pull request merged**
