### PR TITLE
Roll engine to 0b7582e6a130fc99270dafec5113a7ec46ed522a

### PR DESCRIPTION
**Pull request by alexmarkov**
This roll enables Dart 2.0 fixed-size integers.

### CODE REVIEW

**Comment by mravn-google** [comment]
So now Flutter will operate with fixed-sized ints? That is bound to break some users.

What will happen, once this lands, if you send a Java `BigInteger` across a `MethodChannel` with the standard codec? Should we remove support for that on the engine side? Similarly for iOS.

**Comment by alexmarkov** [comment]
The plan is to switch to fixed-size integers in Dart 2.0 (see https://github.com/dart-lang/sdk/blob/master/docs/language/informal/int64.md). By rolling this Dart 2.0 feature to Flutter early, I'd like to figure out if it is causing any problems and discover cases like this.

Eventually Dart team will provide [Bigint class](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/int64.md#bigints--migration) which can be used to represent arbitrary integers, but it is not ready yet.

@mravn-google, could you please clarify what these codecs do with large integers? Is it a blocker for switching to fixed-size integers?

**Comment by mravn-google** [comment]
@alexmarkov The codec merely supports the existing `int` type in Dart, in the sense of faithfully conveying large values to Java (as `BigInteger`s) and iOS (as values of a home-grown type, `FlutterBigInteger`). It also supports sending those platform-specific values back to Dart, as `int`s, for full round-trip. This special handling would not have been there, if Dart had fixed-size `int`s to begin with, and I think it makes sense to remove it at some point during the transition to Dart 2.0.

**Comment by alexmarkov** [comment]
Created issue to track related changes in message codecs: https://github.com/flutter/flutter/issues/12976
Closing this PR, as we're not going to enable fixed-size integers in Flutter right now.

**Pull request closed without merging**
