### PR TITLE
Add --cache-sksl flag to drive and run

### PR DESCRIPTION
**Pull request by liyuqian**
So we can test SkSL precompile using the command line tools.
See https://github.com/flutter/engine/pull/12412.

### CODE REVIEW

**Review by jonahwilliams — COMMENTED** [review]
This needs tests:

There should be some existing test coverage that asserts that command line arguments are turned into the correct adb/process command. I think that would be all that is needed in this case

**Comment by liyuqian** [comment]
Thank you @jonahwilliams for the quick comment! Can you please give me a link to the existing test that I can reference?

**Comment by jonahwilliams** [comment]
Hmm, I was sure what existing test cases that cover these. At any rate, what you'll likely want are two tests.

One for iOS in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/ios/devices_test.dart which calls startApp and ensures that the command line args are correctly set. Specifically, something like https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/ios/devices_test.dart#L172 but with assertions on the command line arguments.

Another one for Android in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/android/android_device_test.dart . Unfortunately we don't have an existing one, but it would look much like the iOS tests.

To run a single test in the tools repo, you can run `bin/cache/dart-sdk/bin/pub run test path/to/test`

**Comment by liyuqian** [comment]
@jonahwilliams : tests added.

**Comment by liyuqian** [comment]
@jonahwilliams : friendly ping...

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
