### PR TITLE
Replaces the InkSparkle shader SPIR-V program from in-memory (List<int> as bytes) to a binary asset (ink_sparkle.spv)

### LINKED ISSUE #99783: [Material] [InkSparkle] Change SPIR-V byte code from static const to a file to prepare for Impeller
Binary is currently here: https://github.com/material-components/material-components-flutter-experimental/tree/fragment-shader-manager/fragment_shader_manager/shaders

### PR DESCRIPTION
**Pull request by clocksmith**
Replaces the InkSparkle shader SPIR-V program from in-memory (`List<int>` as bytes) to a binary asset (`ink_sparkle.spv`)

With this change, the asset is added to runtime assets and loaded asynchronously, right before the compile step, which is already asynchronous.

TODO(reviewers): For WIP, copied asset to cache subdirectory, where material_fonts are read, but where should it be stored instead?

closes: https://github.com/flutter/flutter/issues/99783

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x]I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by zanderso** [comment]
It looks like the parts of the change to use the shader asset in the framework were removed? Maybe github is just not loading the change properly for me for some reason, though.

**Comment by zanderso** [comment]
Ah, I misread the PR. The presubmits are failing because of the binary artifact. It looks like we'll need to get the shader compiler pulled in first. I will look into that ASAP.

**Comment by dnfield** [comment]
I think Zach got blocked on https://github.com/flutter/flutter/issues/102165, and now will be OOO for a bit. That bug is probably resolved by a PR I'm about to land, but getting impellerc pulled in will probably have to wait for a bit now.

**Comment by clocksmith** [comment]
@dnfield Does that mean this can't land until impeller lands?

**Comment by zanderso** [comment]
@clocksmith Yeah, this is blocked waiting for impellerc to be available, but as of yesterday, impellerc is already being vended by the engine build. The next step is to consume it in the tool. Using the in-memory SPIR-V is a blocker for Impeller to support InkSparkle.

**Comment by clocksmith** [comment]
Thanks

> The next step is to consume it in the tool. 

To consume this shader? Is there a tracking bug to know when that is unblocked, so this one can be pushed forward?

**Comment by zanderso** [comment]
This is obsolete.

**Pull request closed without merging**
