### PR TITLE
Updated to Latest Stable Gradle Version 4.7

### PR DESCRIPTION
**Pull request by handstandsam**
Latest Distributions: http://services.gradle.org/distributions/

### CODE REVIEW

**Comment by handstandsam** [comment]
I signed it!

**Comment by Hixie** [comment]
How will existing apps get upgraded?

**Comment by Hixie** [comment]
cc @mravn-google

**Comment by mravn-google** [comment]
I think we should stay on the Gradle version used by latest stable version of Android Studio, which is Gradle 4.4. There is another PR to make that bump. Awaiting upgrade of device lab bots. User projects do not have to be changed; this affects newly created ones only --- and the template instantiations in our repo to ensure we test everything with the most recent template.

**Comment by Hixie** [comment]
if we are not updating existing applications, shouldn't we test with every version we've ever used?

**Comment by mravn-google** [comment]
Yes and no. (Btw, this also applies to developers using older versions of iOS project files, such as Podfiles.) Yes, because our tooling created those files and depend on their existence. No, because we also relinquish control over them to the app author, who may edit them manually, and is in that way responsible for keeping them up-to-date with tooling, including Android Studio, Xcode, Cocoapods, ... and Flutter.

As you know, I want us to move away from this shared ownership situation, and the add2app efforts seem to be taking us to a much saner place.

**Comment by Hixie** [comment]
I don't think we can assume that most Flutter authors are going to understand what's going on in all these files we create in `flutter create`. Most of them are boilerplate for random build systems that have nothing really to do with Flutter. Heck, I barely understand what some of them do. What I want to avoid is the situation where someone does `flutter create` in January, writes their app, comes back 6 months later, runs `flutter upgrade`, and now their app doesn't work because they didn't keep their boilerplate code up to date.

**Comment by Hixie** [comment]
SGTM.

LGTM

**Comment by mravn-google** [comment]
Gradle update to the version used by Android Studio has landed as https://github.com/flutter/flutter/pull/18080

**Pull request closed without merging**
