### PR TITLE
Fixed incorrect offsetting when applying ShaderMasks

### PR DESCRIPTION
**Pull request by mjohnsullivan**
ShaderMasks are applying incorrect offsets when masking over their children. For example, the following mask should be centered in the container, but is incorrectly offset.

Screen Shot 2019-11-26 at 4 41 02 PM

The PR correctly offsets the mask, and updates the unit test to properly test for this behavior:

Screen Shot 2019-11-26 at 4 42 41 PM

### CODE REVIEW

**Comment by goderbauer** [comment]
This seems to be partly undoing a fix that was applied in https://github.com/flutter/flutter/pull/10458.

/cc @jason-simmons Can you take a look at it since you authored the other change?

**Comment by Hixie** [comment]
We should make sure we add a golden test this time, because it's going to be a lot harder to get confused when updating a golden test than a number in a unit test, especially since what we really care about is the pixel output here.

**Comment by goderbauer** [comment]
@mjohnsullivan Would you be up for adding a golden test to this like Hixie suggested in his previous comment?

**Comment by Piinks** [comment]
Here is the guide for goldens in the wiki: https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter

We'll chat about this more offline today. :)

**Comment by mjohnsullivan** [comment]
Added two golden file tests; the images should show that the concentric circles are centered in the Container:

widgets shader_mask bounds matches_bottom_right
widgets shader_mask bounds matches_top_left

**Review by dnfield — COMMENTED** [review]
This looks right, but would be really nice to see the golden - can you sync this to head so we get the Skia gold tryjobs?

**Comment by mjohnsullivan** [comment]
Synced to head!

**Review by dnfield — APPROVED** [review]
LGTM once CI is green.  I triaged the changes in gold, they look good.

**Comment by Piinks** [comment]
Disregard the bot. I have to update that message. :)

**Pull request merged**
