### PR TITLE
Fix the type of `RenderTable.get rowDecorations`.

### PR DESCRIPTION
**Pull request by lrhn**
This changes the return type from `List<Decoration>` to `List<Decoration?>`, matching the corresponding setter.
As such it is a breaking change.
I believe the current type is a *bug*, and this is the correct fix.

The underlying value has a nullable element type, and the setter accepts a list which can contain `null`, but the getter tries to create a list with non-nullable elements from the stored value.
Calling this getter while the list contains `null` will throw.

(If this fix is too simplistic, I'll file a bug for the issue instead.)

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by lrhn** [comment]
(Feel free to land, I don't have commit autority.)

**Comment by goderbauer** [comment]
OK, this needs a secondary LGTM then.

**Review by chunhtai — APPROVED** [review]
LGTM

**Pull request merged**
