### PR TITLE
Dart SDK roll for 8/1/2018

### LINKED ISSUE #34035: Problems resolving uris with the latest dev_compiler and build_web_compilers
Original issue https://github.com/dart-lang/build/issues/1694. See also the travis failure https://travis-ci.org/dart-lang/build/jobs/410045783.

You can reproduce by checking out the [build repo](https://github.com/dart-lang/build) and running `pub run build_runner serve` under the `_test` directory with the latest edge sdk.

Possibly the semantics around the module root or library root changed?

This does not occur on 2.0.0-dev.69.5, so it likely is not blocking 2.0 stable.

I can continue to update as I investigate some more.

cc @vsmenon @jmesserly

### PR DESCRIPTION
**Pull request by aartbik**
Dart SDK roll and disabling of return warnings as errors.

List of commits included in this roll:

8bad5c7b29 [vm/compiler] Non-speculative X64 long division/remainder.
918cda18c5 Add docs about sourcemap extensions
329e029bd6 Fixes dart-lang/sdk#34035
12326c10e1 Store constructor field initializera when the target is not a field.
50da4b8d92 Skip ShadowInvalidFieldInitializer while resynthesizing constructor initializers.
8810b6ecc7 Translate kernel.Instantiation in constant expressions.
cb7341fceb Initial support for inlining-data in source-maps.
4206131030 Fix tracking of onStep position of arguments to new expression
384b0a9a73 Issue 34038. Fix resynthesizing imports when mixed with exports.
ba7dbcf412 Update the test output processor to produce more useful analysis
4b2ee8e9a5 Improve catch clause recovery
66500de4dc More fixes to the CFE integration tests
3f2251986d CC sra also in changes to compiler files and tests
4734c55882 Report error on unsupported operators
00e3109368 [VM] Adjust flags for creating depfiles
07c462b471 [vm] Refactoring: extract BaseFlowGraphBuilder to a separate file
ff9167ff7b Fix parseDirectives to recognize metadata
079bebb78b [ VM ] Added missing token position for assert statements
174649b9be [gardening] Update status of dissasemble_test on Windows
8c5aca7d4d Remove the Factory interface
3dc201e168 Update ChangeBuilder to not include empty edits (Take 2)
18047b2757 Refactor test.dart by changing class Configuration to TestConfiguration
7373d38a31 Update status for Dart2js minified CSP on Chrome with fast startup
61148eade8 Update mixin-declaration feature specification.
a98feb0f01 [VM interpreter] Fix exception handling. Convert bytecode indices to pc offsets ....
da2ed2fd59 Don't ignore runtime cast failures on Map<K,V>.
3d8ca8e566 [gardening] Increase debug app-jitk timeout
0313f7bd66 [gardening] Update status file for failing test
6c39bc38f3 Clear ShadowX references that are not required after compilation.
05b9bbd2b5 Remove the dart1 version of the analysis server snapshot.
9107399190 Add back in the analysis server training.
9fb6c09015 Store reference/type for invalid types.
21db860271 Remove non-strong dart2js builders from test_matrix.json
2e7b0a13f1 Add support for accessing all of the created contexts
73663ae7c6 Allow void on the RHS of null coalescing expressions
17cb6d95d1 Don't remember TypeEnvironment in resolution results.
72960de5f9 [VM] Fix one more place where bound error allocation happened on BG thread in new space
6ad79ff4bd Update status file for tests passing under CFE
23ba527735 [VM] Ensure to alloate bound errors in old space on BG compiler
fe8052428b Remove CONTENT_MODIFIED from spec/test for getSignature
c4c847a45c Revert "[CQ] Remove pkg-linux-release from the CQ trybots until it is fixed"
beaf05efa3 [vm] When generating JITDUMP also dump IR and attach it as source to code.
24158b773d [vm/compiler] Do not LICM LoadStaticField for uninitialized fields.
68bfaf3ac3 [vm/compiler] Avoid crashes when canonicalizing unreachable AssertAssignable.
5a45b2a62b [infra] Upgrade homebrew dependencies to work on Dart 2
8e287dc037 [VM] Only add direct implementor when reading script snapshots if ....
6e81d74fcc [VM] Optimize generation of type testing stubs in JIT mode.
058510eeab fix #28233, add hint for missing returns to function expressions
4482d13ff7 [vm/compiler] Bug fix in 64-bit MOD (%) operator.

### CODE REVIEW

**Review by a-siva — APPROVED** [review]

**Comment by goderbauer** [comment]
@fkorotkov This PR has been waiting for a Mac host for ~3h now. Do you have a status page to see the load of the mac cluster (similarly to https://www.traviscistatus.com/)?

**Comment by fkorotkov** [comment]
@goderbauer we don't have such a page yet but we've ordered more macs for the community cluster. We should get more capacity within the next ~22 hours.

**Comment by aartbik** [comment]
I am ready to roll (pun intended!) but I still have 2 pending tests and the broken flutter build as blockers....

**Comment by aartbik** [comment]
Hmmm. Going on 5 hours now. Do these last test make any progress? The details are rather sparse.

**Comment by aartbik** [comment]
Yeah \O/ all done!

**Pull request merged**
