### PR TITLE
Update tester to latest version

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Works around future changes to meta by pinning exact version

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM. just curious, why is the dev version always odd?

**Comment by jonahwilliams** [comment]
coincidence, I don't roll every version I publish  :)

**Comment by jonahwilliams** [comment]
I should only publish major version revisions to the next prime number

**Comment by jonahwilliams** [comment]
Tester tests passed, landing to unblock meta rollback

**Comment by christopherfujino** [comment]
> I should only publish major version revisions to the next prime number

I thought maybe it was a number puzzle, and if I solved it I would be admitted to some secret society.

**Pull request merged**
