### PR TITLE
Update bottom_sheet.dart

### PR DESCRIPTION
**Pull request by While1true**
Add support of backgroundColor、barrierDismissible、enabledrag、evalution  for showModalBottomSheet and BottomSheet.
Now you can easily use it.

### CODE REVIEW

**Comment by Hixie** [comment]
@While1true Any chance you can sign the CLA as described above? We would love to consider your contribution but can't do so before the CLA is signed. Thanks!

**Comment by dnfield** [comment]
I think this is probably an improvement over what we have right now, but it would still leave some problems.  In particular, a user would not be able to scroll the content up to the top and continue scrolling with a single gesture, and if you put scrolling content (e.g. a `ListView` or `SingleChildScrollView`) in the BottomSheet the drag behavior won't work.

@While1true - do you have any thoughts on that?  It would be helpful to see some sample code for how you want to use this.  It would also be good to see tests for this, but I think a lot of that work would end up being undone by a planned BottomSheet refactor anyway.

**Comment by Hixie** [comment]
Since the CLA wasn't signed, we can't take this patch. @While1true Please don't hesitate to submit a new PR if you have the opportunity to sign the CLA. Thanks!

**Pull request closed without merging**
