### PR TITLE
Use double quotes over single quotes in gradle build files

### PR DESCRIPTION
**Pull request by reidbaker**
Following https://developer.android.com/build/migrate-to-kotlin-dsl
2/n Use double quotes instead of single quotes. 

Should be a no-op change. If you see a behavioral change please flag it. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by johnmccutchan** [comment]
test-exempt: cleanups

**Review by bartekpacia — APPROVED** [review]

**Review by gmackall — APPROVED** [review]
LGTM, though I think there are still some single quotes not yet replaced (lines 67, 426 for ex)

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by reidbaker** [comment]
> LGTM, though I think there are still some single quotes not yet replaced (lines 67, 426 for ex)

Yes I missed those in the merge conflict resolution. Fixed now.

**Pull request merged**
