### PR TITLE
roll source_span 1.8.0-nullsafety.2

### LINKED ISSUE #66287: Engine PRs are blocked by failing Flutter Web tests
e.g. https://github.com/flutter/engine/pull/21300/checks?check_run_id=1145826862

The error message is the same as https://github.com/flutter/flutter/issues/66132 but it sounds like Cirrus may be failing to update to the latest Dart SDK, causing this issue.

cc @yjbanov @jonahwilliams @jakemac53 @nturgut

### PR DESCRIPTION
**Pull request by yjbanov**
## Description

Roll to `source_span` version `1.8.0-nullsafety.2`, which works in both versions of the Dart SDK we're currently using (the one we build, and the one pinned in [DEPS](https://github.com/flutter/engine/blob/87eff25909559e86f1e9f87de1516cbdc2ca82ab/DEPS#L352)).

## Related Issues

Fixes https://github.com/flutter/flutter/issues/66287

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by nturgut — APPROVED** [review]

**Comment by nturgut** [comment]
After this PR merges, we need to change the engine PR commit time, so that it's younger than this commit.

**Comment by yjbanov** [comment]
The "Linux web_tests` status is incorrect. Here's the latest status https://ci.chromium.org/p/flutter/builders/try/Linux%20web_tests/2282 (spoiler: it's green).

**Comment by yjbanov** [comment]
Landing on unfinished "Google testing" and "flutter-gold" to unblock the P0:

- "Google testing" is a noop anyway because google3 doesn't use pubspecs.
- "flutter-gold" will never finish because it's confused about the status of "Linux web_tests" (see https://github.com/flutter/flutter/pull/66290#issuecomment-696389653)

**Pull request merged**
