### PR TITLE
Increase our build budget to 16ms

### PR DESCRIPTION
**Pull request by liyuqian**
Because we now have 2 separate GPU and UI threads.

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]

**Comment by Hixie** [comment]
I'm confused by this change. What does it mean to have two UI threads?

If our target is 120Hz with no pipeline latency, and assuming equal share between build and rasterize, how can the budget be more than 4ms?

**Comment by liyuqian** [comment]
We meant two threads, one UI thread and one GPU thread.

We didn't always target 0 pipeline latency. Instead, our goal is to track smoothness and latency separately. In the case of 120Hz, each thread has a budget of 8ms to be completely smooth. In order to be 0 latency, the sum should be less than 8ms.

**Comment by Hixie** [comment]
Have we not always had two separate threads?

I agree that the sum should be 8ms if we're targetting 120Hz. That seems like the opposite direction than this PR went in, though.

**Comment by liyuqian** [comment]
Yes, just chatted with Chinmay and confirmed that we always had 2 threads. Chinmay also said that 8ms for each thread under 60fps assumption was either a mistake or an over-simplification? (CC @chinmaygarde for confirmations)

For 120Hz, it's sum of 8ms for 0 latency, and 8ms each thread for 100% smooth. This PR focuses on the latter. So far, I haven't seen any complaints about the latency, and all performance issues are regarding the smoothness. That's why this PR focuses on the latter.

**Comment by Hixie** [comment]
We should care about latency and smoothness and we should care about 120Hz. We should care about this stuff before we hear complaints, that way we will never hear complaints. The idea is to be ahead of where our developers are, not behind. :-)

**Comment by liyuqian** [comment]
Agree! Filed https://github.com/flutter/flutter/issues/32447

**Pull request merged**
