### PR TITLE
Roll engine 2ab019412dce..2f706bea076d (1 commits)

### PR DESCRIPTION
**Pull request by engine-flutter-autoroll**
https://github.com/flutter/engine/compare/2ab019412dce...2f706bea076d

git log 2ab019412dce..2f706bea076d --no-merges --oneline
2f706bea0 Fix EXIF orentation problem (flutter/engine#6974)

The AutoRoll server is located here: https://autoroll.skia.org/r/flutter-engine-flutter-autoroll

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/&#43;/master/autoroll/README.md

If the roll is causing failures, please contact the current sheriff, who should
be CC&#39;d on the roll, and stop the roller if necessary.

### CODE REVIEW

**Comment by engine-flutter-autoroll** [comment]
@liyuqian : New roll has been created by https://autoroll.skia.org/r/flutter-engine-flutter-autoroll

**Comment by goderbauer** [comment]
@efortuna Once this PR lands can you update your flutter checkout back to HEAD master and confirm that images in your app are oriented the correct way? Thanks!

**Comment by engine-flutter-autoroll** [comment]
Trybots failed. These were the failed builds: https://cirrus-ci.com/task/4763266666463232

**Comment by efortuna** [comment]
yes, I'll let you know once it lands!

**Comment by engine-flutter-autoroll** [comment]
Commit queue failed; closing this roll.

**Pull request closed without merging**
