### PR TITLE
Add markdown link checking CI task

### PR DESCRIPTION
**Pull request by RDIL**
Removed

### CODE REVIEW

**Comment by dnfield** [comment]
Thanks for this!

I like the idea of doing the check, but have a few concerns.

1. It looks like this doesn't fail the task if a link isn't working.  I'm a bit worried that no one would ever actually check this if it doesn't fail.  However, if it does fail and a site is just temporarily down, it could block a PR or a post submit on something that has nothing to do with the changes :(  Is there a way for Cirrus to mark a task as something other than red or green in this case?  E.g. green if everything is 200, but ... orange if anything isn't?
2. This introduces an NPM/JavaScript dependency.  We already deal with a lot of languages in maintaining Flutter, and I'm a little concerned about adding another dependency (even if it's only for CI). We're actively trying to reduce external dependencies, as they're frequently the source of trouble for us.

**Comment by dnfield** [comment]
Looking at https://developer.github.com/v3/checks/runs/ - something like a "warning" annotation on broken links would be really nice.

**Comment by RDIL** [comment]
Hey @dnfield ,
The task not failing is an issue on Cirrus's end.  It is being worked on.  
I'm willing to check the links every now-and-then, and fix any that are broken.  
I've tried to isolate the tool so it won't affect anything else, in and out of the CI.

**Comment by dnfield** [comment]
My concern is that this will end up being a flaky test.  If we have links to sites that have anything less than 100% uptime, we could end up failing a CI check on someone because an unrelated website is down - or even worse, failing a post-submit (and marking the tree red) for the same.

**Comment by RDIL** [comment]
My idea for this is more of static analysis, meaning the logs aren’t checked too actively.  I think that this check should never fail, and just have “fix dead links with these logs” as more of a starter issue thing.  Please tell me what you think of this approach.

**Comment by dnfield** [comment]
How would the check notify someone that a link needed to be fixed?

**Comment by RDIL** [comment]
I have to close this for reasons I can't disclose.

**Pull request closed without merging**
