### PR TITLE
mojo_client: Dont try to iterate over response headers if there aren't any.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
This seems reasonable, but is this a quirk in iOS's emulator bindings that it doesn't send an empty array?  It appears Android's does.

Also, do we have a way to test this?  (FYI @yjbanov)

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
> This seems reasonable, but is this a quirk in iOS's emulator bindings that it doesn't send an empty array?

The headers field is allowed to be null.  Notice the `?` in the declaration here:

https://github.com/domokit/mojo/blob/master/mojo/public/interfaces/network/url_request.mojom#L34

**Comment by chinmaygarde** [comment]
> This seems reasonable, but is this a quirk in iOS's emulator bindings that it doesn't send an empty array? 

@eseidel: This commit stands on its own as the array is nullable. If ns_net does not wire up the response headers, it is an engine issue with a separate fix. I am verifying that next. This fixes https://github.com/flutter/flutter/issues/3802

**Comment by yjbanov** [comment]
> do we have a way to test this?

If this can be reproduced in the simulator, then yes, a simple driver test should do it. Otherwise, we'd need a real iDevice on the buildbot.

**Pull request merged**
