### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by Hixie**
The "about" text was apparently too long.

### CODE REVIEW

**Comment by Hixie** [comment]
See https://github.com/flutter/flutter/pull/17250/files?w=1 for a version of the diff with GitHub's whitespace mangling hidden (I used the UI to edit this, but had written the original files in a different UI).

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by tvolkert — APPROVED** [review]

**Comment by Hixie** [comment]
Landing on red by popular demand.

**Review by mdale00o — COMMENTED** [review]
⭐

**Pull request merged**
