### PR TITLE
Make platform_channels_swift use more idiomatic Swift

### PR DESCRIPTION
**Pull request by jamesderlin**
* Remove semicolons.
* `if (condition)` => `if condition`.
* `Class.init(...)` => `Class(...)`.
* Remove `break` statements from `switch` cases.

### CODE REVIEW

**Review by willlarche — COMMENTED** [review]
So great to have someone doing this!

**Comment by jamesderlin** [comment]
@willlarche Thanks for looking at this!  If it's okay with you, I'd prefer to keep this pull request focused on mechanical/trivial changes and to implement your suggestions separately. (Doing so also should make the changes you requested easier to review.)

**Comment by willlarche** [comment]
Sure thing. I'd add removing `self` to your list. It's almost never needed except in the one place with `self.eventSink`.

**Comment by jamesderlin** [comment]
> Sure thing. I'd add removing `self` to your list. It's almost never needed except in the one place with `self.eventSink`.

Good point. (It's also needed on the `self.receiveBatteryLevel(result: result)` line because that's in a closure, and it's needed to explicitly capture `self`.)

**Comment by willlarche** [comment]
LGTM

**Comment by willlarche** [comment]
Actually, one more thing, the self in the block is a retain cycle that causes a memory leak. Make it weak and you're good:

```
batteryChannel.setMethodCallHandler({
      [weak self] (call: FlutterMethodCall, result: FlutterResult) -> Void in
      if ("getBatteryLevel" == call.method) {
        self?.receiveBatteryLevel(result: result);
      } else {
        result(FlutterMethodNotImplemented);
      }
    });
```

Doesn't have to be in this PR but needs to be noted somewhere.

**Comment by jamesderlin** [comment]
> Actually, one more thing, the self in the block is a retain cycle that causes a memory leak.

Good catch.  I'll fix that along with the other changes you requested.

**Pull request merged**
