### PR TITLE
Improve error message for when you're not running chromedriver

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
Hmm, somehow this broke the script that parses test files checking that skips have comments. From your diff I'm guessing this is a bug in the skip checker?

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8833369513074622337/+/u/Analyze/analyze/test_stderr
```
Unhandled exception:
Invalid argument(s): Content produced diagnostics when parsed:
  EXPECTED_TOKEN: Expected to find ')'. - 238:5

#0      parseString (package:analyzer/dart/analysis/utilities.dart:102:5)
#1      parseFile (package:analyzer/dart/analysis/utilities.dart:46:10)
#2      _getTestSkips (file:///b/s/w/ir/x/w/flutter%20sdk/dev/bots/analyze.dart:369:41)
#3      verifySkipTestComments (file:///b/s/w/ir/x/w/flutter%20sdk/dev/bots/analyze.dart:414:34)
<asynchronous suspension>
#4      run (file:///b/s/w/ir/x/w/flutter%20sdk/dev/bots/analyze.dart:73:3)
<asynchronous suspension>
#5      main (file:///b/s/w/ir/x/w/flutter%20sdk/dev/bots/analyze.dart:40:5)
<asynchronous suspension>
```

**Comment by Hixie** [comment]
lol i'll debug it

**Comment by Hixie** [comment]
oh it's just a typo in the test.

**Pull request merged**
