### PR TITLE
[ExpansionPanel] adds parameter to customize expansion indicator icon

### PR DESCRIPTION
**Pull request by AyushBherwani1998**
## Description

Adds new parameter `expandIconBuilder` to customize the expansion indicator icon for `ExpansionPanel`. The PR continues the work of @shihaohong from #35416. 

WIP: Add interactive samples to document and explain the usage of `expandIconBuilder`.

## Related Issues

#32802

## Tests

I added the following tests:

- added test to check `ExpansionPanel` and `ExpansionPanelRadio` respects `expandIconBuilder`.
- added test to check the semantics when a user provides a custom indicator icon.
- added test to check hit-testing for custom indicator icon is ignored for `ExpansionPanel` and `ExpansionPanelRadio` when `canTapOnHeader` is true.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by shihaohong** [comment]
It seems like the migration to NNBD has created a ton of merge conflicts for this PR.

**Comment by AyushBherwani1998** [comment]
> 
> 
> It seems like the migration to NNBD has created a ton of merge conflicts for this PR.

Sure, I'll solve it tomorrow morning :)

**Comment by AyushBherwani1998** [comment]
@shihaohong I have updated the PR, PTLA when you have time :)

**Comment by Piinks** [comment]
Hi @AyushBherwani1998, this PR has not been updated in a while, and it is not in a state for code review, so I am going to close it for now. Please feel free to re-open this to continue working on it if you'd like. Thank you!

**Comment by Macacoazul01** [comment]
@Piinks, @AyushBherwani1998  any chances of this being implemented

**Pull request closed without merging**
