### PR TITLE
Introduce `Suspended` curve

### LINKED ISSUE #51627: Look into making _BottomSheetSuspendedCurve public
This curve is used with bottom sheets to allow linear finger dragging and non-linear enter/exit animations.

- Look into making this public
- Adding useful examples
- Find instances where it would be useful, not just for bottom sheets, and retrofit existing code

The PR that adds this curve: #51122

### PR DESCRIPTION
**Pull request by guidezpl**
This curve is used with bottom sheets to allow linear finger dragging and non-linear enter/exit animations.

I had previously introduced this curve privately, pending discovering other possible usages. I rewrote the documentation and refactored to be in line with other `Curve` subclasses.

Fixes https://github.com/flutter/flutter/issues/51627

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gspencergoog** [comment]
It seems to me like this curve would be more useful if you could specify the starting curve and ending curve, not just the ending curve.  The starting curve could default to `Curves.linear`, but you could specify any curve.  Basically all it would be doing would be scaling the first curve both in the parametric direction and in amplitude by the `begin` value, and the second curve by `1.0 - begin`, like in the (very) rough sketch below.  (In that case, you might consider renaming the `begin` to `split` or something)

Untitled drawing

**Comment by guidezpl** [comment]
I think a split curve might be worth adding as a separate subclass if there is a need for it. 

> It may be a refactor, but the refactor creates new public API that should be tested. 

True. I added proper tests.

**Comment by gspencergoog** [comment]
Thanks for adding tests.

> I think a split curve might be worth adding as a separate subclass if there is a need for it.

Having one, more general purpose, curve is better if we're going to have to maintain a public API for it. Having one of the curves hard coded as a linear curve is too restrictive, and doesn't need to be a public class because of its limited usefulness: as you probably know, linear ramps aren't common in UI animation. A more general purpose class also eliminates the need for an additional subclass that would also need to be maintained.

If you don't have time or interest in making this more general purpose right now, that's fine, but I don't  think it warrants a new public API if it is restricted to just a linear ramp.

**Comment by gspencergoog** [comment]
@guidezpl Are you planning to continue pursuing this PR?  If not, could you please close it to get it out of our backlog?  You can always reopen it later.

**Comment by guidezpl** [comment]
No bandwidth, closing for now.

**Pull request closed without merging**
