### PR TITLE
Revert "Revert "[flutter_tools] always initialize the resident runner from di…"

### LINKED ISSUE #58250: linux_chrome_dev_mode SecondStartupTime regression
Looks like it may be this revert: https://github.com/flutter/flutter/pull/58193
Screen Shot 2020-05-29 at 8 31 20 AM

cc @jonahwilliams, who committed the revert.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#58193

Fixes https://github.com/flutter/flutter/issues/58250

### CODE REVIEW

**Comment by zanderso** [comment]
Do you want to land this, or just fix the merge conflicts in https://github.com/flutter/flutter/pull/58188?

**Comment by jonahwilliams** [comment]
Probably this one first.

**Comment by jonahwilliams** [comment]
Friendly ping @zanderso

**Review by jmagman — APPROVED** [review]
LGTM

**Review by zanderso — APPROVED** [review]

**Pull request merged**
