### PR TITLE
Attach standard streams of the child sky_shell process so that logs from the shell show up.

### PR DESCRIPTION
**Pull request by chinmaygarde**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
You should check whether this makes `print` show up twice.

**Comment by chinmaygarde** [comment]
screen shot 2016-05-18 at 4 16 58 pm

Seems fine.

**Comment by eseidelGoogle** [comment]
I think Adam meant dart print. The LOG messages you site would have been
sent to stderr only.

**Pull request merged**
