### PR TITLE
Expose `ignoringPointer` property for `Draggable` and `LongPressDraggable`

### LINKED ISSUE #92083: MouseRegion's cursor in a Draggable's feedback does not work
## Steps to Reproduce

Consider this minimal example ([dartpad](http://dartpad.dev/498f3e532296ab72a9cce857484b762f)):

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: Draggable(
            child: const MouseRegion(
              cursor: SystemMouseCursors.grab,
              child: Square(color: Colors.red),
            ),
            childWhenDragging: Square(color: Colors.red.shade100),
            feedback: const MouseRegion(
              cursor: SystemMouseCursors.grabbing,
              child: Square(color: Colors.red),
            ),
          ),
        ),
      ),
    );
  }
}

class Square extends StatelessWidget {
  const Square({
    required this.color,
    Key? key,
  }) : super(key: key);

  final Color color;

  @override
  Widget build(BuildContext context) {
    return ColoredBox(
      color: color,
      child: const SizedBox.square(dimension: 64.0),
    );
  }
}
```

**Expected results:**

While hovering the square area, the cursor should be `grab`. While dragging, the cursor should be `grabbing`.

**Actual results:**

While hovering the square area, the cursor is `grab`, as expected. When we click to start dragging, the cursor reverts to the "normal" cursor instead of going to `grabbing`.

<details>
  <summary>flutter doctor -v</summary>

```
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale
    en-BR)
    • Flutter version 2.5.3 at /Users/pintome/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/pintome/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (3 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API
      30) (emulator)
    • macOS (desktop)         • macos         • darwin-x64     • macOS 11.6
      20G165 darwin-x64
    • Chrome (web)            • chrome        • web-javascript • Google Chrome
      94.0.4606.81

! Doctor found issues in 1 category.
```
</details>

https://user-images.githubusercontent.com/4605213/137899370-9bcc623f-d324-4f54-a696-0b754554e469.mov

### PR DESCRIPTION
**Pull request by xu-baolin**
Fixes https://github.com/flutter/flutter/issues/92083

MU5735 R.I.P 🙏

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/100475

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/100475

**Comment by xu-baolin** [comment]
@Piinks hey, I see that you have reviewed #93733, which also to fix this issue, could you take a look at this? :)

**Comment by xu-baolin** [comment]
@Piinks hey, I see that you have reviewed #93733, which also to fix this issue, could you take a look at this? :)

**Comment by Piinks** [comment]
Absolutely! Taking a look now, thanks for your patience. https://github.com/flutter/flutter/issues/98537 has been taking up my time lately.

**Review by Piinks — COMMENTED** [review]
This looks good, thank you! Is it possible to add a test that uses MouseRegion like in the repro from the issue?

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

Thank you @xu-baolin! 🎉

**Comment by goderbauer** [comment]
@xu-baolin I restarted the google test to see if it passes now.

**Comment by xu-baolin** [comment]
> @xu-baolin I restarted the google test to see if it passes now.

Thanks, But the test still looks unhappy 😢

**Comment by goderbauer** [comment]
It's green now, but looks like there's a merge conflict. Can you resolve that?

**Comment by xu-baolin** [comment]
Can someone help check why the G test time out? Thanks :)

**Comment by Piinks** [comment]
@keyonghan is this another case where the Google testing should be ignored? For 2 weeks now it has not been successful for this PR, including after multiple rebases.
Related issue: #101719

**Comment by Piinks** [comment]
@xu-baolin thanks for your patience, I can manually merge this once @CaseyHillers confirms. I can't manually set the check to green either due to the issues it is experiencing.

**Comment by CaseyHillers** [comment]
Ack. Feel free to merge.

**Pull request merged**
