### PR TITLE
prefer_const_declarations on local variables

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by a14n** [comment]
@Hixie @bwilkerson

And the list of places where the lint has to be worked around:
- [packages/flutter/test/material/tabs_test.dart, line 1506, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/material/tabs_test.dart#L1506)
- [packages/flutter/test/painting/border_side_test.dart, line 19, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/painting/border_side_test.dart#L19)
- [packages/flutter/test/painting/alignment_test.dart, line 95, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/painting/alignment_test.dart#L95)
- [packages/flutter/test/painting/image_provider_test.dart, line 11, col 7](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/painting/image_provider_test.dart#L11)
- [packages/flutter/test/painting/colors_test.dart, line 43, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/painting/colors_test.dart#L43)
- [packages/flutter/test/painting/border_rtl_test.dart, line 625, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/painting/border_rtl_test.dart#L625)
- [packages/flutter/test/painting/border_rtl_test.dart, line 320, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/painting/border_rtl_test.dart#L320)
- [packages/flutter/test/painting/text_span_test.dart, line 16, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/painting/text_span_test.dart#L16)
- [packages/flutter/test/painting/text_span_test.dart, line 11, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/painting/text_span_test.dart#L11)
- [packages/flutter/test/painting/border_test.dart, line 10, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/painting/border_test.dart#L10)
- [packages/flutter/test/painting/edge_insets_test.dart, line 76, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/painting/edge_insets_test.dart#L76)
- [packages/flutter/test/widgets/render_object_widget_test.dart, line 9, col 1](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/widgets/render_object_widget_test.dart#L9)
- [packages/flutter/test/widgets/key_test.dart, line 22, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/widgets/key_test.dart#L22)
- [packages/flutter/test/widgets/key_test.dart, line 25, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/widgets/key_test.dart#L25)
- [packages/flutter/test/widgets/key_test.dart, line 51, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/widgets/key_test.dart#L51)
- [packages/flutter/test/widgets/key_test.dart, line 47, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/widgets/key_test.dart#L47)
- [packages/flutter/test/widgets/key_test.dart, line 29, col 5](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/widgets/key_test.dart#L29)
- [packages/flutter/test/widgets/directionality_test.dart, line 68, col 7](https://github.com/a14n/flutter/blob/d44edc2239257c5f950f2d9d8ce5eb010d7216ad/packages/flutter/test/widgets/directionality_test.dart#L68)

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
What's the plan for the ones that will need workarounds?

**Comment by a14n** [comment]
I think we can add an identity function in `flutter_test` like:

```dart
T unConst<T>(T t) => t;
```

and use it to avoid `prefer_const_declarations` and `prefer_const_constructors`:


```dart
class A {
  const A(this.i);
  int i;
}

main () {
  new A(unConst(null)); // OK for prefer_const_constructors
  final int $null = unConst(null); // OK for prefer_const_declarations
  final A a = unConst(const A(null)); // OK for prefer_const_declarations
}
```

WDYT ? Any better name for `unConst` ?

**Comment by Hixie** [comment]
Ah, yeah, clever. `unconst` seems fine. Or `nonconst` maybe.

That pushes the problem back as far as when the Dart team fulfills my wish for compile time execution. :-)

**Pull request merged**
