### PR TITLE
Cherry-pick changes to support the use_emulator flag that made it into candidate branch

### PR DESCRIPTION
**Pull request by ricardoamador**
The Linux_Android android_defines_test is consistently failing on release branches. 

For the linux_android defines test the use_emulator flag made it into the release branch however none of the supporting changes did. This cherry-picks two commits that are needed to support the testing with the emulator.

Commits are:
https://github.com/flutter/flutter/commit/f989d551ce4267f00da668f35d1bae975f061992
https://github.com/flutter/flutter/commit/22bbdf03e02ee685d985279aad04fd6e16c9e7be

*List which issues are fixed by this PR. You must list at least one issue.*
Fixes https://github.com/flutter/flutter/issues/120287

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by CaseyHillers** [comment]
@ricardoamador this requires a CP request issue to be attached. Please file one at https://github.com/flutter/flutter/issues/new?assignees=&labels=cp%3A+review&template=7_cherry_pick.yml&title=%5BCP%5D+%3Ctitle%3E

In the description, include why this is needed, and links to example breakages.

**Comment by ricardoamador** [comment]
Added a Cherry-pick request.

**Comment by godofredoc** [comment]
Landing with failures on codesigning tests as they are not supposed to run/pass on presubmit.

**Review by godofredoc — APPROVED** [review]

**Review by godofredoc — APPROVED** [review]

**Comment by ricardoamador** [comment]
Thanks @godofredoc!

**Pull request merged**
