### PR TITLE
Fix broken asset uris

### PR DESCRIPTION
**Pull request by mehmetf**
Asset URIs are not supposed to begin with a slash. Perhaps we should relax that requirement but for now let's fix gallery.

### CODE REVIEW

**Comment by mehmetf** [comment]
I discovered this during a Google roll. The scuba test failed showing the missing logo.

**Comment by mehmetf** [comment]
@HansMuller Should we be more forgiving on the URL format?

**Review by willlarche — APPROVED** [review]
Thank you!

**Comment by HansMuller** [comment]
Did all of the images named with  /foo URLs not actually show up? That would have put the gallery in rather worse shape then I would have expected.

I'm not sure if we ascribe any specific meaning to a leading slash; if not perhaps we should be more forgiving.

**Comment by willlarche** [comment]
This is not necessary for iOS but _is_ necessary for Android. So removing the `/` is correct.

**Comment by HansMuller** [comment]
In other words, if we'd manually checked the gallery on Android, we would have noticed that there was something amiss.

In the future, we're going to need to create a golden image test for the gallery. I'll file an issue

On Monday.

**Comment by willlarche** [comment]
Yes. I definitely made a mistake by only testing on iOS.

**Comment by HansMuller** [comment]
If this is confession, I've been only testing on Android for years. Tell no one 😳

**Pull request merged**
