### PR TITLE
Revert "Expose height and width factor in AnimatedAlign "

### PR DESCRIPTION
**Pull request by mehmetf**
Reverts flutter/flutter#60836

This is a breaking change but I am not sure 100% why. There can be two cases that I can think of:

- `Align` widget accepts null values for width and height factors. Perhaps `null` vs 1.0 mean different things?
- Apps might rely on `AnimatedAlign`'s current behavior (i.e. *not* animating the width and height factors).

This PR needs to follow the breaking changes policy.

### CODE REVIEW

**Comment by Piinks** [comment]
@Nash0x7E2 This was reverted due to some test failures that run after a PR is merged. I'm going to review them and see what we need to do to in order to successfully re-land this. 👍

**Comment by Nash0x7E2** [comment]
Noted @Piinks, let me know how I can help 👍

**Comment by Piinks** [comment]
@Nash0x7E2, when you have a chance, can you open a new PR with your original change so we can discuss a few adjustments to it? I think we can do this is a non-breaking way. :)

**Comment by Nash0x7E2** [comment]
Sure! I’ll do so momentarily :)

**Comment by Nash0x7E2** [comment]
Created a new PR #61136 @Piinks

**Pull request merged**
