### PR TITLE
Configure Cirrus CI

### PR DESCRIPTION
**Pull request by fkorotkov**
This change configures Cirrus CI to run Flutter's tests both in Linux and Windows containers. Cirrus CI provides a consistent experience for both platforms, fast virtual CPUs and start-up time thanks to [Container Optimized OS](https://cloud.google.com/container-optimized-os/), etc.

Here is a link to the corresponding build: https://cirrus-ci.com/build/5764001350811648

image

Also Cirrus CI creates separate GitHub status checks for each task for better visibility of what exactly is passing/failing in CI:

image

Cirrus CI is already successfully used on [`flutter/plugins`](https://github.com/flutter/plugins) repository.

### CODE REVIEW

**Comment by fkorotkov** [comment]
BTW I faced some race conditions with streams and sinks:

```
Bad state: StreamSink is already bound to a stream
#0      _StreamSinkImpl.addStream (dart:io/io_sink.dart:181)
#1      _StdSink.addStream (dart:io/stdio.dart:353)
#2      _runCommand (file:///C:/Windows/Temp/flutter%20sdk/dev/bots/test.dart:326:12)
<asynchronous suspension>
#3      _runFlutterTest (file:///C:/Windows/Temp/flutter%20sdk/dev/bots/test.dart:360:10)
#4      _runTests (file:///C:/Windows/Temp/flutter%20sdk/dev/bots/test.dart:184:9)
<asynchronous suspension>
#5      main (file:///C:/Windows/Temp/flutter%20sdk/dev/bots/test.dart:57:35)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

That's why I added be80e0f3a6fc26ae9486ed0cfce1059762222bd2

**Comment by Hixie** [comment]
Why does Cirrus show the entire PR description inline in the landing page for a shard? That seems like not really useful information there. I'd much rather see the logs and timing information prominently shown.

I'm a little concerned that Cirrus seems to have had a flake on this PR? It's hard for me to understand how exactly it failed, but it reports having failed once?

Also, it looks like some of the shards took a long time to run, e.g. the analyzer shard took around 5 minutes just to start, which is longer than it took to run.

**Comment by fkorotkov** [comment]
@Hixie thanks for the UX feedback. I've made a change to only show a change title instead of the full change message.

Regarding the flake that you mentioned. Failure message of the [task](https://cirrus-ci.com/task/6297141815279616) contains a [link to documentation](https://cirrus-ci.org/faq/#ci-agent-stopped-responding). **TLDR**: Cirrus CI uses [Preemptible VMs](https://cloud.google.com/preemptible-vms/) for running OSS projects that might be preempted by Google Cloud. This is what happened in this case. 

Such VMs are 80% cheeper which makes them a huge **$$$** saver for a small startup like Cirrus CI since we pay for the [Community Cluster](https://cirrus-ci.org/guide/supported-computing-services/#community-cluster). But anyone can [configure their own Kubernetes cluster](https://cirrus-ci.org/guide/supported-computing-services/#kubernetes-engine) with non-preemptible VMs to use with Cirrus CI. That's why there are automatic re-runs for such cases of an internal infrastructure failure and this is why you see [a re-run task](https://cirrus-ci.com/task/5633647818309632) that was automatically created. We are considering to use a mix of regular and Preemptible VMs and have a prioritization for big OSS projects like Flutter and master branches of all repositories to run on non-preemptible VMs.

I don't see where `analyze` took 5 minutes to start. [In this case](https://cirrus-ci.com/task/5171241908436992) it took 3 minutes to start from the moment a corresponding commit was pushed. I've checked the logs again and the situation here was that there were not enough resources in the cluster and it tool 3 minutes to bring up a new VM and cache `cirrusci/flutter:latest` image. 

We have a pretty aggressive auto-scaling policy for Community Cluster which allows us save $$$ and minimize preemption events since nodes in the cluster don't live for long. But according to metrics, p95 for scheduling though out the day varies from 2.7 seconds to 8.3 seconds (scheduling time includes time to pull a Docker image if it's not cached and start a container).

**Comment by fkorotkov** [comment]
BTW when I rebased I saw a real flake of `sdk\examples\layers\test\smoketests\rendering\flex_layout_test.dart` test on Windows:

```
00:05 +10 -1: C:\Windows\Temp\flutter sdk\examples\layers\test\smoketests\rendering\flex_layout_test.dart: layers smoketest for rendering/flex_layout.dart [E]
  'package:flutter/src/rendering/flex.dart': Failed assertion: line 439 pos 18: 'textDirection != null': Horizontal RenderFlex with multiple children has a null textDirection, so the layout order is undefined.
  smoketests\rendering\flex_layout_test.dart 12:60       main.<fn>.<fn>
  package:flutter/src/foundation/assertions.dart 408:14  FlutterError.reportError
  package:flutter/src/scheduler/binding.dart 992:20      _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
  package:flutter/src/scheduler/binding.dart 930:9       _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
  package:flutter/src/scheduler/binding.dart 842:5       _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame
  This test failed after it had already completed. Make sure to use [expectAsync]
  or the [completes] matcher when testing async code.
  smoketests\rendering\flex_layout_test.dart 12:60       main.<fn>.<fn>
  package:flutter/src/foundation/assertions.dart 408:14  FlutterError.reportError
  package:flutter/src/scheduler/binding.dart 992:20      _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
  package:flutter/src/scheduler/binding.dart 930:9       _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
  package:flutter/src/scheduler/binding.dart 842:5       _RenderingFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame
```

Here is a [link to the build where it failed](https://cirrus-ci.com/task/5881751368892416) and [here is a link to a re-run that succeeded](https://cirrus-ci.com/task/5715614517690368).

**Comment by fkorotkov** [comment]
I've rebased and `flex_layout_test.dart` flaked again. After some digging it appeared to look like an actual problem since `RenderFlex#_debugHasNecessaryDirections` requires `textDirection` when `direction` is horizontal and there are multiple children. Here is this logic in the code: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/flex.dart#L439

Fixed it by 7e21e33d3e4d1d07fd0015d17d1f7abf6a7c79cd

**Comment by Hixie** [comment]
Weird, I wonder why that wasn't failing reliably.

**Comment by Hixie** [comment]
This looks pretty good. There's definitely some things we can improve (e.g. it's hard to tell on the Cirrus page what shard one is looking at, or even what repo, unless you know that the chips at the top are showing that information), and it'd be nice if the logs were open by default since that the only reason you're likely to look at these pages, but these are minor details.

I'm going to land this once the tree is green and we'll see how it feels.

**Comment by fkorotkov** [comment]
@Hixie great news! 🎉 I'll rebase it in the meantime.

Do you have an idea how visibility of the shard name or repo can be improved? I'll think about it. At some point of time I was thinking about making these chips bigger than normal ones for visibility.

About logs. If some step is failing, logs for that step will be pre-opened. If everything is working, no additional fetching of logs until a user will expand them. It's just an optimization 😅

**Comment by Hixie** [comment]
Bigger chips might work. Or just a header, I don't know if it has to be a chip. :-)

**Comment by Hixie** [comment]
@fkorotkov Is there a way we can rename the tasks so that the "tests" shard is named "tests-linux" and the "windows" shard is named "tests-windows"?

**Comment by fkorotkov** [comment]
@Hixie sure thing! Here is a PR: https://github.com/flutter/flutter/pull/17216

**Comment by fkorotkov** [comment]
@Hixie BTW you were right about more traffic in this repo. It also spikes 😅Had to bump GCP quotas for OSS builds twice today. It mostly affects Windows which should be fixed next week once we move Windows builds to Kubernetes as well.

**Pull request merged**
