### PR TITLE
setState() will call scheduleFrame() in post-frame callback now.

### PR DESCRIPTION
**Pull request by snyiuan**
setState() will call scheduleFrame() in post-frame callback now.

### CODE REVIEW

**Comment by goderbauer** [comment]
For context: Looks like this was changed in https://github.com/flutter/flutter/pull/14133.

So yeah, we should be able to remove this now. Thanks for the contribution! However, in order to accept it, we require tests. Can you add one that shows that everything still works as expected without this call.

**Review by goderbauer — COMMENTED** [review]
For context: Looks like this was changed in #14133.

So yeah, we should be able to remove this now. Thanks for the contribution! However, in order to accept it, we require tests. Can you add one that shows that everything still works as expected without this call.

**Comment by snyiuan** [comment]
@goderbauer I added a test case.

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
