### PR TITLE
Allow select cases to be numbers (#116625)

### PR DESCRIPTION
**Pull request by AlexV525**
(cherry picked from commit 583a8122bc895208da53d2a5728255450537a5ae)

As a pre-cp of #120678 suggested at https://github.com/flutter/flutter/pull/120678#issuecomment-1432016460.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by thkim1011 — APPROVED** [review]
LGTM but just to make sure, cherry-picking the other commit on top of this one works without merge conflicts?

**Comment by AlexV525** [comment]
> LGTM but just to make sure, cherry-picking the other commit on top of this one works without merge conflicts?

I'm not sure I can fully understand your purpose, but after this has landed, we can rebase another request so it won't have conflicts then.

**Comment by AlexV525** [comment]
@thkim1011 You'll need to approve the request issue too. :)

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
