### PR TITLE
Roll engine to 94cdd81031a287babbf70144ea93d18d88abae4a

### PR DESCRIPTION
**Pull request by cbracken**
Includes:
* Add hint to use ninja with goma (flutter/engine#4894)
* Support `Path.addCircle` (flutter/engine#4783)
* Roll dart (flutter/engine#4902)

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by yjbanov — APPROVED** [review]

**Comment by yjbanov** [comment]
lgtm

**Comment by aam** [comment]
See https://github.com/flutter/flutter/pull/16087

**Review by tvolkert — APPROVED** [review]

**Comment by cbracken** [comment]
@aam thanks for the heads-up. Looks like an analyzer error on both our PRs (I haven't yet looked into it).

**Comment by cbracken** [comment]
Closing this PR.

**Pull request closed without merging**
