### PR TITLE
Enable fading animation during page transitions.

### PR DESCRIPTION
**Pull request by liyuqian**
The average frame time of page transitions on Moto G4 is now very close to 16ms (the last 10 measurements on our dashboard are between 15.5ms to 16.7ms and half of them are below 16ms).

It is now much faster than when we disabled it (which was at about 35ms). So I think that we should be able to enable it by default.

See https://github.com/flutter/flutter/issues/13736 and the comparison between what it was and what it is:
gdd material savelayer_youtube

### CODE REVIEW

**Comment by Hixie** [comment]
@liyuqian If it's good enough to enable, then feel free to remove the flag entirely.

**Comment by Hixie** [comment]
(and send a breaking change warning, since this is technically a breaking change)

**Comment by liyuqian** [comment]
I'm worried that we might need to revert this change is something unexpected happened (as the frame time is not that comfortably below 16ms). By removing the whole flag, we had more chance of having roll back conflicts. But I'm happy to remove the flag completely if you think that a roll back is unlikely or if the conflicts are easy to resolve.

**Comment by liyuqian** [comment]
@HansMuller @Hixie : this flag is now removed.

**Comment by liyuqian** [comment]
Breaking change warning sent: https://groups.google.com/forum/#!topic/flutter-dev/oox6o92PFqE

**Review by HansMuller — APPROVED** [review]
LGTM

**Pull request merged**
