### PR TITLE
Make it easier to catch multiple errors during a test

### LINKED ISSUE #8338: Hard to test exceptions during layout
Exceptions during layout tend to cause a cascade of other exceptions, which makes it hard to test.  See https://github.com/flutter/flutter/pull/8321 for an example of a layout exception we'd like to test.

### PR DESCRIPTION
**Pull request by pingbird**
## Background

Tests that expect multiple exceptions to occur (such as during layout) are difficult to implement, the current approach is to override `FlutterError.onError`, for example: https://github.com/flutter/flutter/blob/fe55dc2b135b5b71ae3c19062b34dc6e8d02e9d5/packages/flutter/test/rendering/viewport_test.dart#L1615-L1631

However, this is much less elegant than the `takeException` method provided by the test binding, and prone to error as some tests forget to restore `FlutterError.onError` to its original state.

This PR fixes this small issue by adding a new `wrapExceptions` method to the test binding, allowing tests to catch multiple exceptions easily without manually touching `FlutterError.onError`.

## Related Issues

Fixes #8338

## Tests

I added the following tests:

* A test to make sure `wrapExceptions` catches framework errors and restores default behavior when finished

## Breaking Change

No breaking changes

### CODE REVIEW

**Review by chunhtai — COMMENTED** [review]
This API is still quite verbose and I think it does not help much with making the test more readable. I wonder whether we can come up with an API that are similar to takeException, but it takes all the pending exceptions as a list. This may need to change our test binding quite a bit though.

cc @jonahwilliams , can you foresee any issue if we keep a list of pending exceptions in the test binding?

**Comment by PixelToast** [comment]
I've simplified the API to have wrapExceptions return a list, however this is probably as simple as it can get without making breaking changes

**Comment by chunhtai** [comment]
I think we should avoid callback wrapper if we can provide a more straight forward API. It may require more work but it won't be a breaking change.

**Comment by chunhtai** [comment]
I will close this pr as I don't think this is the approach we want to take.

**Pull request closed without merging**
