### PR TITLE
drop/restore focus when app becomes invisible/visible

### LINKED ISSUE #21193: TextField does not lose input focus when window loses focus.
To reproduce (Android):
  - place a flutter app in split screen mode with another app.
  - Begin editing a text field. 
  - Tap into the other app, this will dismiss the keyboard
  - Observe that the text field still appears to have focus, the cursor is blinking et cetera.

What should happen:

Upon focusing the other android app, the Flutter input focus should be reset.

### PR DESCRIPTION
**Pull request by jonahwilliams**
Documented explanation for behavior:
```
// When the application moves to the background, any focus nodes
// need to lose focus. When the application is restored to the
// foreground state, any focused node should regain focus (including)
// restoring the keyboard. This is only important in cases where
// applications in the background are partially visible. For example,
// split-screen on Android or a backgrounded app on a desktop environment.
```

Fixes flutter#21193

### CODE REVIEW

**Comment by goderbauer** [comment]
I just opened on Android in split screen Gmail and Website with a text field. Both can have a blinking cursor at the same time. This would change that behavior if one of them were a Flutter app. Any reason we want to diverge from native behavior (I agree that Android behavior is kinda odd to keep the cursor blinking)?

On Desktop (Mac) I am observing the behavior as you describe: If a window loses focus, it's cursor also stops blinking.

**Comment by jonahwilliams** [comment]
@goderbauer which android version? I haven't been able to find a way to keep two cursor blinking on Pie

**Comment by jonahwilliams** [comment]
And I say that and I got it, had to come back from lock screen

**Comment by jonahwilliams** [comment]
I'll follow up with an experiment on an Android tablet. If need be we can exclude Android for now

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Adding @gspencergoog  for focus related changes

**Comment by gspencergoog** [comment]
I think you need to determine if that was an intentional thing (both cursors blinking), or just a bug on Android.  I'm inclined to think it is the latter. And then we need to decide if we're prioritizing replicating bugs to match the platform or correct behavior.

**Comment by jonahwilliams** [comment]
I've confirmed that the cursor blinking on Android is a bug

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
