### PR TITLE
Roll pub packages

### PR DESCRIPTION
**Pull request by fluttergithubbot**
This PR was generated by `flutter update-packages --force-upgrade`.

### CODE REVIEW

**Comment by christopherfujino** [comment]
Build tests failure is https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20build_tests_2_3/1012/overview:

```
[ +997 ms] > Task :app:mergeDebugAssets FAILED
[        ] Task :app:mergeDebugAssets in app Starting
[        ] Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/io/flutter/arm64_v8a_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/arm64_v8a_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom]
[        ] Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/io/flutter/x86_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/x86_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom]
[        ] Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/io/flutter/armeabi_v7a_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/armeabi_v7a_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom]
[        ] Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/io/flutter/arm64_v8a_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/arm64_v8a_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom]
[        ] Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/io/flutter/x86_64_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/x86_64_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom]
[        ] Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/io/flutter/x86_64_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/x86_64_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom]
[        ] Downloading https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/arm64_v8a_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom to /tmp/gradle_download15312503271329264788bin
[        ] Downloading https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/x86_64_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom to /tmp/gradle_download1096395717218753309bin
[        ] Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/io/flutter/x86_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/x86_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom]
[        ] Downloading https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/x86_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom to /tmp/gradle_download13390330898619356488bin
[        ] Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/io/flutter/armeabi_v7a_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/armeabi_v7a_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom]
[        ] Downloading https://storage.googleapis.com/download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/armeabi_v7a_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom to /tmp/gradle_download6077833758564215312bin
[        ] Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/io/flutter/flutter_embedding_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/flutter_embedding_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom]
[        ] Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/io/flutter/flutter_embedding_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/flutter_embedding_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom]
[        ] Downloading https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b/flutter_embedding_debug-1.0.0-37e2aaa901e812c5538b7bd1b7648b2141ee169b.pom to /tmp/gradle_download3590890895327266982bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/annotation/annotation/1.2.0/annotation-1.2.0.pom to /tmp/gradle_download5105099650457545368bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/annotation/annotation/1.2.0/annotation-1.2.0.module to /tmp/gradle_download9708187287534973410bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/fragment/fragment/1.1.0/fragment-1.1.0.pom to /tmp/gradle_download10869566438640471495bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/window/window-java/1.0.0-beta03/window-java-1.0.0-beta03.pom to /tmp/gradle_download13052256387015851874bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-common/2.2.0/lifecycle-common-2.2.0.pom to /tmp/gradle_download5233289809094244575bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/core/core/1.6.0/core-1.6.0.pom to /tmp/gradle_download12152505451455542597bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-runtime/2.2.0/lifecycle-runtime-2.2.0.pom to /tmp/gradle_download2193081361324673287bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/tracing/tracing/1.0.0/tracing-1.0.0.pom to /tmp/gradle_download5105168713498034837bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-common-java8/2.2.0/lifecycle-common-java8-2.2.0.pom to /tmp/gradle_download262196944515748692bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/core/core/1.6.0/core-1.6.0.module to /tmp/gradle_download9676005857116364601bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/window/window-java/1.0.0-beta03/window-java-1.0.0-beta03.module to /tmp/gradle_download7918448922781233933bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/tracing/tracing/1.0.0/tracing-1.0.0.module to /tmp/gradle_download12372459376989709746bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/arch/core/core-common/2.1.0/core-common-2.1.0.pom to /tmp/gradle_download12601481370457837361bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/viewpager/viewpager/1.0.0/viewpager-1.0.0.pom to /tmp/gradle_download7666810680974813552bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/loader/loader/1.0.0/loader-1.0.0.pom to /tmp/gradle_download6960485863523413981bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-viewmodel/2.1.0/lifecycle-viewmodel-2.1.0.pom to /tmp/gradle_download14319835533823888186bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/activity/activity/1.0.0/activity-1.0.0.pom to /tmp/gradle_download1873054134764888953bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/collection/collection/1.1.0/collection-1.1.0.pom to /tmp/gradle_download6358339360041991978bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/versionedparcelable/versionedparcelable/1.1.1/versionedparcelable-1.1.1.pom to /tmp/gradle_download11122388208851017539bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/annotation/annotation-experimental/1.1.0/annotation-experimental-1.1.0.pom to /tmp/gradle_download8883167115847504143bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/annotation/annotation-experimental/1.1.0/annotation-experimental-1.1.0.module to /tmp/gradle_download195364698488746314bin
[        ] Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.5.2/kotlinx-coroutines-core-1.5.2.pom]
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/window/window/1.0.0-beta03/window-1.0.0-beta03.pom to /tmp/gradle_download18384686699247020732bin
[        ] Downloading https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.5.2/kotlinx-coroutines-core-1.5.2.pom to /tmp/gradle_download10260681998903312643bin
[        ] Downloading https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.5.2/kotlinx-coroutines-core-1.5.2.module to /tmp/gradle_download11891635705991534910bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/window/window/1.0.0-beta03/window-1.0.0-beta03.module to /tmp/gradle_download11187247978682971291bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/customview/customview/1.0.0/customview-1.0.0.pom to /tmp/gradle_download12985330331982463810bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-livedata/2.0.0/lifecycle-livedata-2.0.0.pom to /tmp/gradle_download6593246366152662406bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/savedstate/savedstate/1.0.0/savedstate-1.0.0.pom to /tmp/gradle_download9392415701405982867bin
[        ] Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.5.2/kotlinx-coroutines-core-jvm-1.5.2.pom]
[        ] Downloading https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.5.2/kotlinx-coroutines-core-jvm-1.5.2.pom to /tmp/gradle_download14997597196384915449bin
[        ] Downloading https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.5.2/kotlinx-coroutines-core-jvm-1.5.2.module to /tmp/gradle_download2060802915837044277bin
[        ] Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-android/1.5.2/kotlinx-coroutines-android-1.5.2.pom]
[        ] Downloading https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-android/1.5.2/kotlinx-coroutines-android-1.5.2.pom to /tmp/gradle_download7314119291941177910bin
[        ] Downloading https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-android/1.5.2/kotlinx-coroutines-android-1.5.2.module to /tmp/gradle_download3901900855531447522bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-livedata-core/2.0.0/lifecycle-livedata-core-2.0.0.pom to /tmp/gradle_download499409523067167918bin
[        ] Downloading https://dl.google.com/dl/android/maven2/androidx/arch/core/core-runtime/2.0.0/core-runtime-2.0.0.pom to /tmp/gradle_download8069807164141184154bin
[        ] Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.5.30/kotlin-stdlib-jdk8-1.5.30.pom]
[        ] Downloading https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.5.30/kotlin-stdlib-jdk8-1.5.30.pom to /tmp/gradle_download11896476411455089097bin
[        ] Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.5.30/kotlin-stdlib-jdk7-1.5.30.pom]
[        ] Downloading https://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.5.30/kotlin-stdlib-jdk7-1.5.30.pom to /tmp/gradle_download6548244470425653294bin
[        ] Task :app:mergeDebugAssets in app Finished
[        ] :app:mergeDebugAssets (Thread[Execution worker for ':' Thread 5,5,main]) completed. Took 1.006 secs.
[        ] :path_provider_android:writeDebugAarMetadata (Thread[Execution worker for ':' Thread 7,5,main]) completed. Took 1.077 secs.
[   +1 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:mergeDebugAssets'.
[        ] > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
[        ]    > Did not resolve 'com.google.errorprone:error_prone_annotations:2.3.2' which is part of the dependency lock state
[        ]    > Did not resolve 'com.google.guava:guava:28.1-android' which is part of the dependency lock state
[        ]    > Did not resolve 'com.google.code.findbugs:jsr305:3.0.2' which is part of the dependency lock state
[        ]    > Did not resolve 'org.codehaus.mojo:animal-sniffer-annotations:1.18' which is part of the dependency lock state
[        ]    > Did not resolve 'org.checkerframework:checker-compat-qual:2.5.5' which is part of the dependency lock state
[        ]    > Did not resolve 'com.google.guava:failureaccess:1.0.1' which is part of the dependency lock state
[        ]    > Did not resolve 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava' which is part of the dependency lock state
[        ]    > Did not resolve 'com.google.j2objc:j2objc-annotations:1.3' which is part of the dependency lock state
[        ] * Try:
[        ] Run with --debug option to get more log output. Run with --scan to get full insights.
[        ] * Exception is:
[        ] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mergeDebugAssets'.
```

**Comment by christopherfujino** [comment]
@stuartmorgan do you have any idea why your change in https://github.com/flutter/plugins/pull/6744 is causing gradle version solving to fail?

**Comment by stuartmorgan** [comment]
> > Did not resolve 'com.google.guava:guava:28.1-android' which is part of the dependency lock state

No idea, but this is the dependency that I removed. It's mentioning the "lock state", and I see that there are [gradle lock files referencing it](https://github.com/flutter/flutter/search?q=com.google.guava%3Aguava%3A28). I don't know anything about Gradle lock files, but it seems like they are probably the issue here.

**Comment by christopherfujino** [comment]
> > > Did not resolve 'com.google.guava:guava:28.1-android' which is part of the dependency lock state
> 
> No idea, but this is the dependency that I removed. It's mentioning the "lock state", and I see that there are [gradle lock files referencing it](https://github.com/flutter/flutter/search?q=com.google.guava%3Aguava%3A28). I don't know anything about Gradle lock files, but it seems like they are probably the issue here.

cc @reidbaker is the fix here to just one time re-generate https://github.com/flutter/flutter/blob/master/dev/integration_tests/hybrid_android_views/android/project-path_provider.lockfile ? I was thinking maybe we could just not check it in to version control, but the comment at the top says its intended to be version controlled.

**Comment by christopherfujino** [comment]
I'm going to file an issue as it looks like the number of lockfiles we have in the repo is non-trivial

**Comment by christopherfujino** [comment]
> I'm going to file an issue as it looks like the number of lockfiles we have in the repo is non-trivial

nvm, turns out there's already a script in the repo for this: https://github.com/flutter/flutter/pull/92800

**Comment by christopherfujino** [comment]
Obsolete, manually pinned and rolled in https://github.com/flutter/flutter/pull/116377

**Pull request closed without merging**
