### PR TITLE
use TextField.border.borderSide by default

### PR DESCRIPTION
**Pull request by altynbek132**
#98368

### CODE REVIEW

**Comment by HansMuller** [comment]
The issue this PR is supposed to resolve, https://github.com/flutter/flutter/issues/98368,  is already closed as invalid.

**Comment by altynbek132** [comment]
@HansMuller 
suggested solution stated that we should use "enabledBorder", but in case when I want default border in **all** states leads to case when we write:
```
TextField(
  decoration: InputDecoration(
    enabledBorder: defaultBorder,
    disabledBorder: defaultBorder,
    errorBorder: defaultBorder,
    focusedBorder: defaultBorder,
    focusedErrorBorder: defaultBorder,
  ),
),
```
Suggested pr fixes that issue

[here is demo](https://dartpad.dev/?id=163743f986d94712712e0f4b5b36d31e) of issue with comments

**Comment by Hixie** [comment]
@altynbek132 Before we can land this PR, we need to jump through a few hoops:
* First, we will need to file an issue that describes the problem being resolved and why it is a problem (the issue listed above is marked as invalid, so it's insufficient in its current state).
* Second, we will need to add a test to the PR to verify that the behaviour is working, so that we don't accidentally revert the fix later.
* Third, we will need to make sure the existing tests all pass (currently a number of them fail).

Would you be willing to take point on these steps?

**Comment by Hixie** [comment]
@altynbek132 Thanks for your contribution. We're going to close this PR for now. If you're interested in following up please don't hesitate to reach out, the #hackers-new channel on our Discord is a good place to start. Thanks again!

**Pull request closed without merging**
