### PR TITLE
Remove the typo error in shouldReclip method.

### PR DESCRIPTION
**Pull request by ChHannan**
## Description

When the shouldReclip method is overridden by extending the CustomClipper class, the android studio or another IDE give typo error in method name, so i have updated the method name to shouldReClip in abstract class.

### CODE REVIEW

**Comment by ChHannan** [comment]
@googlebot I signed it!

**Comment by goderbauer** [comment]
Thanks for the PR. This would be a breaking change for everybody implementing a CustomClipper without any benefit for them. It also seems that "reclip" is a somewhat commonly used word in the english language: https://www.google.com/search?q=define%3Areclip. I don't think we should submit this.

**Comment by ChHannan** [comment]
Noted with thanks.

**Comment by goderbauer** [comment]
I am going to close this with the reason stated above.

**Pull request closed without merging**
