### PR TITLE
change expand icon to use default icon colors

### LINKED ISSUE #18992: ExpandIcon is always black
I tried to use the `ExpansionPanelList` and found that the `ExpandIcon` always has `Colors.black38` color:
https://github.com/flutter/flutter/blob/2a65505e8af78aba79ccbae4f0b2bb83bf3c65d4/packages/flutter/lib/src/material/expand_icon.dart#L109
```
    return new IconButton(
      padding: widget.padding,
      color: Colors.black38,
      onPressed: widget.onPressed == null ? null : _handlePressed,
      icon: new RotationTransition(
        turns: _iconTurns,
        child: const Icon(Icons.expand_more)
      )
    );
```
image
That can be a problem if you use a dark theme. I think it's better to use the icon color from the current theme or create different constants for the dark and light themes (like the material buttons):
https://github.com/flutter/flutter/blob/cc1cf9e12a226ec67875a857c2fcc097541781b1/packages/flutter/lib/src/material/flat_button.dart#L242

I'm new to the Flutter, so I can be wrong :)

### PR DESCRIPTION
**Pull request by jonahwilliams**
Previously expand icon unconditionally used black38, which is problematic for dark themes. Instead we should just use the theme defaults.

~~Since the default is significantly darker than the old icon, we should discuss whether we want to add a workaround to restore the previous color black38 when using light themes.~~

Fixed to use black54/white54

Fixes https://github.com/flutter/flutter/issues/18992

### CODE REVIEW

**Comment by jonahwilliams** [comment]
cc @HansMuller , this should use the same icon themes as the rest of flutter right?

**Comment by HansMuller** [comment]
I believe the icon color is (now) supposed to be 54% black or white for the light or dark themes respectively.

**Comment by HansMuller** [comment]
It looks like https://flutter.github.io/assets-for-api-docs/assets/material/Colors.whites.png and likewise for black need to updated.

**Comment by HansMuller** [comment]
LGTM

**Comment by pavelsust** [comment]
> Previously expand icon unconditionally used black38, which is problematic for dark themes. Instead we should just use the theme defaults.
> 
> ~Since the default is significantly darker than the old icon, we should discuss whether we want to add a workaround to restore the previous color black38 when using light themes.~
> 
> Fixed to use black54/white54
> 
> Fixes #18992
> 
> 

How you change the icon color can you share with me?

**Pull request merged**
