### PR TITLE
Add ability to mock VMService's WebSocket connection

### PR DESCRIPTION
**Pull request by tvolkert**

### CODE REVIEW

**Comment by tvolkert** [comment]
@johnmccutchan

**Review by johnmccutchan — COMMENTED** [review]
Lgtm

**Comment by tvolkert** [comment]
@cbracken

**Comment by tvolkert** [comment]
@johnmccutchan FYI, I had to make some substantive updates to deal with a test failure in the first rev.  Would you mind taking another look?

**Comment by johnmccutchan** [comment]
Still LGTM

**Pull request merged**
