### PR TITLE
Make animation_demo a manual test

### LINKED ISSUE #5710: Gallery: Animations demo difficult to use
(from user testing)

Out of four user tests, no one knew how to use the animation demo. They didn't see or understand the FAB. Tapping on the little circles doesn't do anything (that might be a very recent bug). Pinch-zoom doesn't seem to do anything. 

Low priority, but if there's an easy way to improve the UI (maybe, tap anywhere triggers the animation) such that the user can make the demo do a thing, that would reduce confusion. Thanks!

### PR DESCRIPTION
**Pull request by abarth**
This demo doesn't work properly in landscape and is confusing. It's
really more of a test of the material arc code.

Fixes #5710

### CODE REVIEW

**Comment by abarth** [comment]
@HansMuller

**Comment by mpcomplete** [comment]
FWIW, for me, the refresh button is the confusing part of this demo. If it were a Play arrow, it would be more obvious what to do.

**Comment by HansMuller** [comment]
You'll need to remove 'Animation' from examples/flutter_gallery/test_driver/transitions_perf_test.dart
 LGTM

**Comment by HansMuller** [comment]
This demo was really about showing how animated points and vertices traveled along arcs (per Material Designs). Most users didn't realize that the animated elements could be moved, despite the directions at the top .

I agree that we need an animation demo that can just be played. Something with some more visual interest.

**Comment by eseidelGoogle** [comment]
The Flutter logo animates nicely. :)  Maybe that could be a demo?

**Pull request merged**
