### PR TITLE
Implemented Stepper horizontal back and forth navigation buttons

### PR DESCRIPTION
**Pull request by andryfailli**

### CODE REVIEW

**Comment by andryfailli** [comment]
I signed it!

**Comment by andryfailli** [comment]
inspired by #11133

**Comment by Hixie** [comment]
This needs tests.

**Comment by Hixie** [comment]
@andryfailli Are you planning on doing the tests or should we take this PR over? (either way is fine, just trying to decide if we should leave the PR open in the meantime)

**Comment by Hixie** [comment]
I've filed a bug to track this so that we don't lose your contribution: https://github.com/flutter/flutter/issues/11361.
I'm going to close this PR in the meantime so that it's not on our review queue, but please do not hesitate to reopen it or open a new one if you have the chance to work on some tests!

**Comment by andryfailli** [comment]
Ok, perfect, I'll update this PR when I will have some tests

**Review by akilinomendez — COMMENTED** [review]
Fantastic

**Pull request closed without merging**
