### PR TITLE
Desktop composing region navigation

### LINKED ISSUE #85328: Can't navigate composing candidates list with arrow keys on Mac
When using composing keyboards on native Mac, the arrow keys can be used to navigate the composing tooltip.  In Flutter, the arrow keys continue to be intercepted by Flutter when the composing tooltip is visible, so it doesn't receive the keys.  We should not intercept the keys when composing is happening.

| Native Mac | Flutter Mac |
| --- | --- |
| text_edit_composing | text_edit_composing_flutter |

## Steps to reproduce

  1. Run any app with a text input, like the one given below, on a Mac.
  2. Set your keyboard to a composing keyboard, such as Chinese Pinyin.
  3. Type some text so that the composing tooltip appears, such as "ni".
  4. Attempt to navigate in the tooltip using the arrow keys.

Result: The cursor moves, not the selection in the composing tooltip.
Expected result: The selection in the composing tooltip moves.

<details>

<summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: TextField(),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by justinmc**
Previously, Flutter was unable to navigate the native composing tooltip when using the arrow keys on desktop:

| Native Mac | Flutter Mac |
| --- | --- |
| text_edit_composing | text_edit_composing_flutter |

This PR gets it to work by passing the arrow keys through to the platform when composing.

Fixes https://github.com/flutter/flutter/issues/85328

### CODE REVIEW

**Review by LongCatIsLooong — COMMENTED** [review]
Would it be possible to fix this in the macOS text input plugin? If there's a way on macOS to tell that there's an active candidate view (for multistage input or emojis/accents) then we probably don't want the framework to handle the keyevent first?

**Comment by justinmc** [comment]
Yeah this is probably better there in the engine, the key shouldn't come to the framework at all.  I'll look into doing it in the engine and will likely close this PR.

**Comment by goderbauer** [comment]
(PR triage): @justinmc Do you still have plans for this PR?

**Comment by cbracken** [comment]
See the note I added to #85328 for a test case you may want to verify this with.

**Pull request closed without merging**
