### PR TITLE
engine roll cp

### PR DESCRIPTION
**Pull request by Jasguerrero**
engine cp roll

### CODE REVIEW

**Comment by itsjustkevin** [comment]
Nothing is missing, we should be picking to candidate 0 for the beta.

**Comment by XilaiZhang** [comment]
Oh i see, this is for Jesús' 1p cherry pick request, the context was [b/287578759](https://b.corp.google.com/287578759)

**Review by XilaiZhang — APPROVED** [review]
lgtm. (just make sure all the tests pass before merging in)

**Comment by afandi-09** [comment]
emmmmm

**Pull request merged**
