### PR TITLE
Create template splash screens for Android and iOS

### LINKED ISSUE #8147: flutter create should make an app with a non-white splash screen
(based on @xster's proposal in #8127)

When running flutter create, the default launch storyboard is white. Devs will likely want to show a custom screen while the app is loading. Consider putting a placeholder splash screen in the template app, so devs can just drop in new assets and be done with it.

Here are some resources that discuss configuring splash screens.

iOS: https://docs.nativescript.org/publishing/creating-launch-screens-ios

Android: https://www.bignerdranch.com/blog/splash-screens-the-right-way/

### PR DESCRIPTION
**Pull request by xster**
Fixes #8147

This add ~~81kB~~ to a newly `flutter create`d project.

### CODE REVIEW

**Comment by Hixie** [comment]
iirc @abarth had opinions about doing this

**Comment by xster** [comment]
I'll add some splash screen instructions (probably to https://flutter.io/assets-and-images) in a separate website PR

**Comment by Hixie** [comment]
I would rather we didn't show the Flutter logo by default. Our developers' apps' users don't care that our developers use Flutter. (Also if we do decide to show the logo, we should show the right one -- these PNGs have the SVG rendering error.)

Can we make these default splash screens just black, maybe?

**Comment by xster** [comment]
You're right, the svgs do look broken. Seems like the illustrator vectors in the same directory are ok. Swapped out assets for those one. 

It's not so much about showing the flutter logo as having a template for developers to drop in assets for splash screens without having to do all the work that's in this PR. 

We can document on the website how to remove image assets to just have static colors but I think for developers, removing will be a lot easier than adding. But I think we can use a different image placeholder if there's another one you prefer.

**Comment by Hixie** [comment]
I don't mind having a placeholder image, I just think it should be all-black or something like that.

Many developers are just writing little apps for their own personal use. They don't want to have to go and remove our big logo to have a professional-looking app. They just want an out-of-the-box polished experience. It's bad enough that we use our logo for the icon. ;-)

**Comment by xster** [comment]
Did you mean a black box in a white background?

**Comment by xster** [comment]
Made the changes we talked about, removed the actual assets. Left the hookups.

**Comment by Hixie** [comment]
RSLGTM

The approach LGTM. I'm totally ignorant about the actual files you're modifying. :-)

**Comment by xster** [comment]
I tweaked it again. The iOS side was giving warnings in Xcode and sometimes while running. Felt unclean. Added back a 1px transparent png for placeholder.

**Pull request merged**
