### PR TITLE
Reland elide long tree walks

### PR DESCRIPTION
**Pull request by dnfield**
Relands #48413 

Removes bad assertion from test (it isn't relevant to the test, forgot to remove it.

### CODE REVIEW

**Comment by shihaohong** [comment]
It seems to still be failing the test for a different reason (doesn't seem to be eliding the tree walk?)

**Comment by shihaohong** [comment]
This seems to be failing now on `packages/flutter/test/material/radio_test.dart: Radio ink ripple is displayed correctly` for a [framework test](https://cirrus-ci.com/task/6530858593026048)

**Comment by dnfield** [comment]
Both flakes - rerunning, and filed https://github.com/flutter/flutter/issues/49917

The other flake was a timeout during setup.  Not sure if we have a bug tracking that, it's been happening more recently.

**Comment by Piinks** [comment]
Could Cirrus be providing the wrong service account? IT looks like it is trying to authenticate with an account I haven't seen before.

**Comment by dnfield** [comment]
CI all green now

**Review by shihaohong — APPROVED** [review]
LGTM

**Pull request merged**
