### PR TITLE
Bump Dart SDK to `1.24.0-dev.3.0`.

### PR DESCRIPTION
**Pull request by pq**
For landing post-I/O.

Staging now to see if any build issues shake out.

@Hixie 

@keertip: could you ping if we do a new internal push in the meantime?

### CODE REVIEW

**Comment by pq** [comment]
Glad I put this out.  Looks like we've got some test failures.

cc @tvolkert for ideas (@Hixe threw you under the bus 😉 )

**Comment by Hixie** [comment]
I've no idea what's up with the failure on Windows.
The analysis failure seems like a legit bug with the autogenerated code of mega_gallery that we should just fix.

**Comment by Hixie** [comment]
cc @goderbauer who may have a better idea for the Windows problem.

**Comment by goderbauer** [comment]
I can't reproduce the Windows failure locally. I restarted the appveyor build in case it's just a flake.

**Comment by goderbauer** [comment]
Windows failure was a flake, it's green now.

And the Travis failure can (probably) be fixed by replacing the `new` with a `const` in this line: https://github.com/flutter/flutter/blob/master/dev/tools/mega_gallery.dart#L111.

**Comment by pq** [comment]
Thanks @goderbauer!  Fixing up mega_gallery now.

**Comment by Hixie** [comment]
LGTM

Feel free to land this whenever.

**Comment by pq** [comment]
Thanks.  I'll land it this AM when I'm in the office. 👍

**Comment by Hixie** [comment]
@pq I am separately rolling Dart in the engine so don't worry about that. (I'm rolling to today's latest trunk revision.)

**Comment by pq** [comment]
Good deal.  Thanks @Hixie!

**Pull request merged**
