### PR TITLE
Factor out some common code in PaintingContext

### PR DESCRIPTION
**Pull request by Hixie**
...and remove some highly specialised methods now that they can just
be implemented directly by the previous callers.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @abarth, who may care about this change.

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
Test failure was caused by the code invoking saveLayer() on the mock canvas (previously it was dropped on the floor because we didn't see inside the pushPhysicalModel call). Turns out we didn't track saveLayer() so the save count was off when we got to restore(). We now track saveLayer(). At some point we should make mock canvas much more aware of everything else going on here.

**Comment by Hixie** [comment]
will land on green unless @apwilson leaves the office first

**Pull request merged**
