### PR TITLE
- add FadeInImage.placeholderFit

### PR DESCRIPTION
**Pull request by tuyen-vuduc**
At the moment, `FadeInImage` doesn't allow us to specify a BoxFit for the placeholder image. It's annoying because placeholder image usually local image, and its size is totally different from the actual Image's, so is the BoxFit.

Issue #20231 was raised a long time ago without a PR.

The PR aims to solve that issue and allows developers to specify a dedicated BoxFit for the placeholder image.

I don't add any new tests or modify any existing ones because I don't find any relevant tests regarding `FadeInImage.fit`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by goderbauer** [comment]
This seems fine, but it will still need a test to make sure that this doesn't get broken in the future.

**Comment by tuyen-vuduc** [comment]
@goderbauer Any suggestions how to write the tests for this one?

**Review by dnfield — COMMENTED** [review]
Change seems fine, needs a test. You can probably model this on some of the other tests in fade_in_image_test.dart

**Review by dnfield — APPROVED** [review]
LGTM.

Needs to be approved of by another team member before landing.

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
