### PR TITLE
Migrate to .ci.yaml

### PR DESCRIPTION
**Pull request by CaseyHillers**
## Issues

https://github.com/flutter/flutter/issues/82303

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by christopherfujino** [comment]
analysis failling:

```
/tmp/flutter sdk/.ci.yaml:1503: trailing blank line
/tmp/flutter sdk/dev/README.md:8: trailing blank line
```

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
@CaseyHillers Can you update https://github.com/flutter/flutter/wiki/Adding-a-new-Test-Shard accordingly?

**Comment by CaseyHillers** [comment]
Good catch @Hixie, I updated the documentation with the `.ci.yaml` workflow

**Comment by Hixie** [comment]
Thanks!

**Pull request merged**
