### PR TITLE
Don't include toString method bodies in release mode

### PR DESCRIPTION
**Pull request by mdebbar**
Guarding all the bodies of `toString` methods by `assertionsEnabled` helps reduce the binary size. Here are the results I got by running `flutter build apk` on the following projects under `examples/`:

* **catalog**: _-4168_
* **flutter_gallery**: _-37956_
* **flutter_view**: _-22684_
* **hello_world**: _-4204_
* **layers**: _-4204_
* **platform_channel**: _-17924_
* **platform_view**: _-19864_
* **stocks**: _-27104_

The numbers represent the reduction in apk sizes in bytes.

### CODE REVIEW

**Comment by dnfield** [comment]
Could we achieve similar savings if we hid this behind a flag other than `assertionsEnabled`?  

I can imagine a situation in which someone has a depdency on a release-mode `toString` and doesn't want to enable assertions to get it back.  I suppose they could just refactor their code, but guarding with a different flag doesn't seem expensive either.

**Comment by Hixie** [comment]
Getting rid of the toStrings in release builds seems like a huge win. I'm not sure this is the right approach though. It makes the code much less readable and it's going to be really easy for people to forget to add these checks in the future.

Is there some way we can get this win with a kernel transform maybe?

**Comment by goderbauer** [comment]
+1 to doing this in a kernel transformer. I believe that one should be fairly straightforward to write.

**Comment by goderbauer** [comment]
Do we maybe also have to add an analyzer lint that triggers when people explicitly or implicitly call toString in their app to remind them that this will have different behavior in release mode?

**Comment by mdebbar** [comment]
I agree that this approach isn't the best and it doesn't scale. It helped provide real data though about the possible code size win.

That said, I'm not convinced that it's a good idea to blindly strip out any method named `toString`. Regardless of the approach we take, it should allow the developer to decide which ones are okay to strip out. And I would argue that whatever approach we implement, should be generalizable and not limited to `toString`.

Something like a `@devOnly` annotation maybe?
```dart
class Foo {
  @devOnly
  void foo() => 'foo'; // Will be removed in release builds.
}
```
To make it scale better, we could make it so that it automatically propagates to subclasses.

Thoughts?

**Comment by dnfield** [comment]
We could probably make an analyzer lint warn people if they were using something so annotated outside of a similarly annotated method

**Comment by Hixie** [comment]
Having a `@debugOnly` (or `@debug` and `@profile`, or any number of other such variants) seems like a great idea. In particular it would be really useful to be able to turn these back on temporarily while debugging a release build, since `print` debugging is all you have left in release builds.

**Comment by yjbanov** [comment]
I like the `@debug`/`@profile` idea! I'd use it a lot. However, I don't think kernel transform is sufficient. The analyzer and the CFE need to check that when the `@debug`-annotated member is tree-shaken out code still compiles correctly.

For example, this should be flagged quite early in the process:

```dart
abstract class Foo {
  bar();
}

class Baz implements Foo {
  @debug @override
  bar() {};
}
```

There is no proper way to compile this code in release mode as `Baz` leaves the abstract `bar` method unimplemented.

I think this PR should go in to reduce the chance of developers relying to debug behavior in release builds. I would technically be a breaking change (albeit a minor one) to change the behavior or debug methods in production builds.

**Comment by mdebbar** [comment]
@Hixie @dnfield @goderbauer FYI: I filed an issue in Dart sdk for adding the support for `@debug` annotation: https://github.com/dart-lang/sdk/issues/35303

**Comment by xster** [comment]
I'm gonna remove the various other f: tags to help subteams triage. I took a look and it doesn't look like there are much 'sub-layer' specific logic that needs reviewing if there's a framework-wide convention

**Comment by goderbauer** [comment]
(cleaning up the PR backlog) Looks like there has been agreement that we'd need language support or a kernel transformer to actually do this. Can we close this PR in the meantime?

**Pull request closed without merging**
