### PR TITLE
Transport `e2e` based perforamnce test to `integration_test` and remove duplicate `watchPerformance`

### LINKED ISSUE #63537: [e2e] Move `watchPerformance` to e2e after `FrameTimingSummarizer` goes into stable release
This issue is to monitor the duplicate of `watchPerformance` in various host-independent performance tests, which will be moved to `e2e` in flutter/plugins after `FrameTimingSummarizer` goes into stable version. 

We can't do it now because `e2e` is tested against Flutter stable SDK.

### PR DESCRIPTION
**Pull request by CareF**
## Description

This is **NOT** a complete upgrade from the `e2e` dependence in the framework to `integration_test` but just those that reference `watchPerformance`.  

## Related Issues

Fixes #63537

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by CareF** [comment]
The CI will fail until flutter/plugins#3116 is merged and published to pub.dev

**Comment by liyuqian** [comment]
@CareF : integration_test 0.9.2 has been published. Can you please rerun the presubmit tests?

**Comment by CareF** [comment]
> @CareF : integration_test 0.9.2 has been published. Can you please rerun the presubmit tests?

@liyuqian Test completed.

**Review by liyuqian — APPROVED** [review]
LGTM

**Pull request merged**
