### PR TITLE
update tests for TextStyle changes in engine

### PR DESCRIPTION
**Pull request by dnfield**
This pull is related to flutter/engine#5395

While I intend to do a bit more around TextStyle to surface this work in the SDK, this at least just gets the unit tests to pass with those changes in the engine.  This should not be merged until the engine PR has been merged.

### CODE REVIEW

**Comment by Hixie** [comment]
Man, we really should change this to not mention the unspecified values. It's getting tediously long.

LGTM, though, so you can land this (with the engine roll in the same PR) when you're ready.

**Comment by dnfield** [comment]
e.g. is it really just a matter of updating the internal/engine file with the Git commit hash for the engine?

**Comment by Hixie** [comment]
https://github.com/flutter/engine/wiki/Release-process

**Comment by dnfield** [comment]
This will have to be updated again once either flutter/engine#5499 lands or the related analyzer issue is resolved.

**Pull request merged**
