### PR TITLE
Fix tooltips don't dismiss when using TooltipTriggerMode.tap

### LINKED ISSUE #98854: `Tooltip` doesn't dismiss when using `TooltipTriggerMode.tap`
Tooltip showDuration doesn't work with TooltipTriggerMode.tap 
When enable TooltipTriggerMode.tap , showDuration doesn't work and tooltip stay alive until another tab action!

### PR DESCRIPTION
**Pull request by bleroux**
## Description

Tooltips lifecycle is managed using three sources of pointer events :
- a `MouseRegion` to manage hover events.
- a listener registered to `GestureBinding.instance.pointerRouter`.
- a `GestureDetector` to react to long press or tap gestures (depending on the tooltip trigger mode).

The GestureDetector handlers (onLongPress and onTap) call _handlePress method to display the Tooltip.
The tooltip is dismissed either by :
- the MouseRegion onHoverExit handler when the mouse is moved outside the targeted widget.
- the listener to PointerRouter after a PointerUpEvent or a pointerCancelEvent.

For TooltipTriggerMode.onTap, the tooltip might not be disposed (see #98854). It happens when there is one or more competing GestureDetectors. In this case (see #98854), the GestureArena disambiguation process takes more time and the PointerRouter events are received before the tooltip is shown.

This PR updates the Tooltip GestureDetector onTap callback to show the Tooltip and dismisses it after `showDuration` expired.

## Related Issue

Fixes https://github.com/flutter/flutter/issues/98854

## Tests

Add 3 test in `material/tooltip_test.dart`

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by chunhtai — COMMENTED** [review]
Based on the pr description, the issue is that the global pointer arrive faster than the ontap call back which makes the _handleMouseExit called before the _handleTap is called?

If so it seems like we should not use the globalpointer route in the first place, why don't we just use the onLongPressUp/onLongPressCancel and onTapUp/onTapCancel to call the _handleMouseExit?

**Comment by chunhtai** [comment]
Thanks for clarifying, based on the original issue it seems like only this is required

https://github.com/flutter/flutter/blob/10087a3b5e831bbb3f9ccd0804586e84e20ebaa5/packages/flutter/lib/src/material/tooltip.dart#L631

the PointerUpEvent, PointerCancelEvent should be handled by the gesture detector instead?

**Comment by chunhtai** [comment]
The reason I brought this up is this pr create two different ways to dismiss the tooltip for longpress and tap, one from the global route for long press and one from the ontap handler for single tap, It will be easier to maintain if they are more unified.

**Comment by bleroux** [comment]
Unification would be great. Unfortunately, I don’t think we can get rid of PointerRouter reacting to PointerUpEvent/PointerCancelEvent.

I tried and quickly found one issue on Desktop : hold down the mouse button outside the widget, move above the widget, the tooltip is shown (onMouseOver), release the button the tooltip should be dismissed, it is not when removing this line : 
https://github.com/flutter/flutter/blob/10087a3b5e831bbb3f9ccd0804586e84e20ebaa5/packages/flutter/lib/src/material/tooltip.dart#L629 
and we can't rely on GestureDetector for this scenario because the gesture started elsewhere.

As TooltipTriggerMode.tap was introduced recently (in 2021) and is not covered by Material spec, I tried to find a fix that doesn’t interfere with the main use cases (longPress and Hover) to avoid subtle breaking changes.

**Comment by chunhtai** [comment]
>  I tried and quickly found one issue on Desktop : hold down the mouse button outside the widget, move above the widget, the tooltip is shown (onMouseOver), release the button the tooltip should be dismissed.

Is this a expected behavior? I tried on web https://www.w3schools.com/css/tryit.asp?filename=trycss_tooltip
and the tooltip is not dismissed when lifted the mouse click even if the tooltip started outside. I thought the tooltip only relies on the mouse hover when mouse is connected.

**Comment by bleroux** [comment]
> Is this a expected behavior? 

As per [material spec](https://material.io/components/tooltips#behavior), I would say yes 
"Display the tooltip for 1.5 seconds. If the user takes another action before that time ends, the tooltip will disappear.". 
But it depends on how 'action' is interpreted :smile: 

> I thought the tooltip only relies on the mouse hover when mouse is connected.

By default no. I too expected that it will, for instance on desktop. That's why I filed #103703. 
I closed #103073, because I recently figured out that with `TooltipTriggerMode.manual` we can show Tooltip only when hovered.

What you are suggesting is smarter : using mouse hover when a mouse is connected and relying on gestures when there are no mouse. That seems very interesting for computer with a touch screen or tablets with a mouse. If it makes sense, filing a new issue will be more actionnable than updating this PR.

I would like to keep this PR simple, as `TooltipTriggerMode.tap` is a edge case and updating Tooltip lifecycle code might be risky.

**Review by chunhtai — APPROVED** [review]
LGTM, make sense. seem like the best thing to do at the moment

**Pull request merged**
