### PR TITLE
fix `mustCallSuper` contract for `DiagnosticableTreeMixin`

### PR DESCRIPTION
**Pull request by pq**
https://dart-review.googlesource.com/c/sdk/+/240880 adds a new diagnostic to flag cases where mixins break `@mustCallSuper` semantics as discussed in https://github.com/dart-lang/sdk/issues/48352.  As written, `DiagnosticableTreeMixin` (correctly) gets flagged by this new diagnostic as it does not call super.  This change fixes that and should be behavior preserving and non-breaking for current users of `DiagnosticableTreeMixin` 🤞 .

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by pq** [comment]
Ah, not quite right.

```
../../packages/flutter/lib/src/rendering/object.dart:1235:16: Error: 'AbstractNode' doesn't implement 'Diagnosticable' so it can't be used with 'DiagnosticableTreeMixin'.
 - 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('../../packages/flutter/lib/src/foundation/node.dart').
 - 'Diagnosticable' is from 'package:flutter/src/foundation/diagnostics.dart' ('../../packages/flutter/lib/src/foundation/diagnostics.dart').
 - 'DiagnosticableTreeMixin' is from 'package:flutter/src/foundation/diagnostics.dart' ('../../packages/flutter/lib/src/foundation/diagnostics.dart').
abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin implements HitTestTarget {
```

**Comment by pq** [comment]
I'm not seeing an easy fix here.

The rub is that to ensure mustCallSuper semantics, `DiagnosticableTreeMixin` has to be **on** `Diagnosticable` but if we do that, `DiagnosticableTreeMixin` can only be mixed into classes that implement `Diagnosticable`. I think this is actually correct but since we weren't detecting this earlier we've got ourselves into a funny spot where fixing it would be breaking for downstream users of `DiagnosticableTreeMixin`.

/cc @jacob314

**Review by jacob314 — APPROVED** [review]
lgtm

**Comment by jacob314** [comment]
> Ah, not quite right.
> 
> ```
> ../../packages/flutter/lib/src/rendering/object.dart:1235:16: Error: 'AbstractNode' doesn't implement 'Diagnosticable' so it can't be used with 'DiagnosticableTreeMixin'.
>  - 'AbstractNode' is from 'package:flutter/src/foundation/node.dart' ('../../packages/flutter/lib/src/foundation/node.dart').
>  - 'Diagnosticable' is from 'package:flutter/src/foundation/diagnostics.dart' ('../../packages/flutter/lib/src/foundation/diagnostics.dart').
>  - 'DiagnosticableTreeMixin' is from 'package:flutter/src/foundation/diagnostics.dart' ('../../packages/flutter/lib/src/foundation/diagnostics.dart').
> abstract class RenderObject extends AbstractNode with DiagnosticableTreeMixin implements HitTestTarget {
> ```

We either need a data driven fix to fix all the usages of DiagnosticableTreeMixin or find a different way to resolve the lint that doesn't require a data driven fix.
Core problem is right now there isn't really any super.debugFillProperties to call but its also hard to statically tell that the mixin can only be used in a case where there isn't really a super.debugFillProperties to call.

**Comment by jacob314** [comment]
Discussed at length with @munificent. TLDR is we should tweak the mustCallSuper behavior for `mustCallSuper` annotated on a mixin class. `mustCallSuper` really means `mustNotHide`. That means that the existing behavior in Flutter is right for this but we need to enforce errors any time you:
1. Have a mixin that has a method that has `@mustCallSuper`.
2. The class being mixed into has a base class that implements the method
Because in that case the base class method is hidden which is counter to the goal of `@mustCallSuper` to prevent you from accidentally hiding a version of the method. One example we discussed are weird cases where you happen to accidentally use the same mixin twice in your class hierarchy.

**Comment by pq** [comment]
Closing this out in favor of updating semantics of the diagnostic.  Thanks for the feedback @jacob314 and @munificent!

**Pull request closed without merging**
