### PR TITLE
Resolved contradictory documentation of showGeneralDialog and default value of 'barrierLabel' argument

### LINKED ISSUE #78868: Documentation of showGeneralDialog is contradictory
The documentation of `showGeneralDialog` states:

https://github.com/flutter/flutter/blob/5d37734ea1032f25dfc022f6130916e28b98e7f3/packages/flutter/lib/src/widgets/routes.dart#L1871-L1874

https://github.com/flutter/flutter/blob/5d37734ea1032f25dfc022f6130916e28b98e7f3/packages/flutter/lib/src/widgets/routes.dart#L1876-L1877

but `barrierDismissible` actually defaults to **false** (introduced with https://github.com/flutter/flutter/pull/61503) and `barrierLabel` doesn't default to anything and must not be null if `barrierDismissible` is set to true.

### PR DESCRIPTION
**Pull request by Tapaswi846580**
where default value of 'barrierDismissible' is 'false' and default 'barrierLabel' is 'Dismiss'

This PR will change the default value of `barrierDismissible` argument of `showGeneralDialog()` to `false` in the documentation as per the code and it will also assign the default value of `barrierLabel` argument as `'Dismiss'`

`barrierDismissible` documentation Before:

before_true

`barrierDismissible` documentation After:

after_false

`barrierLabel` argument before:

before

`barrierLabel` argument after:

after

Issue [#7868](https://github.com/flutter/flutter/issues/78868) gets fixed by this PR

Fixes https://github.com/flutter/flutter/issues/78868

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by shihaohong — COMMENTED** [review]
Thanks for the PR! I see two ways forward:

1) Add a test to ensure that the barrierLabel of 'Dismiss' is applied and keep it the way you've written it
2) Update the documentation to say that the barrierLabel defaults to `null`. In the Material and Cupertino libraries, we have localized values for Dismiss (The string updates based on your device's locale or the locale specified in your Flutter app). We do not have localizations at the `widget` layer, so it might be better off to leave the value off as `null` by default and keep it agnostic to the user's language.

I think 2 makes more sense, let me know what you think!

**Comment by Tapaswi846580** [comment]
Hey, Thanks for the reply !
I will add a test to ensure that the barrierLabel of 'Dismiss' is applied by default. If  this is incorrect do let me know and then I'll update the documentation.

**Comment by shihaohong** [comment]
Actually, after thinking about it some more, I think that we should just update the documentation and not have the default value be `Dismiss`. It would not only force the barrier label to be in English, but also could be a breaking change (from not having a label to having a label). Could you update the docs accordingly instead? Sorry about the confusion

**Comment by Tapaswi846580** [comment]
Yes, you are absolutely correct! I'll just update the doc accordingly. Thank you so much for addressing the issue.

**Review by shihaohong — APPROVED** [review]
LGTM

**Comment by Tapaswi846580** [comment]
Thank you so much for your kind and humble response. Looking forward to make more contributions. 😊

**Pull request merged**
