### PR TITLE
Remove `RenderObject.rotate`

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
It's not implemented/overridden.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by Hixie — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
(when submitting a PR like this please either update the PR description, or just delete the template, i'd rather we didn't commit code whose commit description was the template verbatim)

**Comment by LongCatIsLooong** [comment]
Manual TGP run passed but frob won't let me set the status

**Comment by keyonghan** [comment]
@CaseyHillers Is this good enough to manually submit the PR ignoring the Google Testing check?

**Comment by CaseyHillers** [comment]
In future cases, feel free to link the TGP run and submit.

**Pull request merged**
