### PR TITLE
Fixed flutter create "package" template error in pubspec.yaml

### PR DESCRIPTION
**Pull request by argumentofperiapsis**
Attempted to resolve issue #14975 
I've edited "package" template's pubspec.yaml similar to "create"'s one.

### CODE REVIEW

**Comment by Hixie** [comment]
This is a better fix than @tvolkert's fix in https://github.com/flutter/flutter/pull/14976. :-)

LGTM

**Comment by Hixie** [comment]
Will land on green.

**Review by tvolkert — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
cla/google was confused. Both committers are OK.
flutter-build seems confused. Build is green.

I'm landing.

**Pull request merged**
