### PR TITLE
Testing GN artifacts (used to test engine_v2 recipes, will be closed once migration is complete)

### PR DESCRIPTION
**Pull request by godofredoc**
Do not review.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by christopherfujino** [comment]
Pushed a new commit that should completely suppress the tool warning. Let's say how the tool integration tests do after this

**Comment by christopherfujino** [comment]
One outstanding failure in Linux tool_integration_tests 2_4:

```
18:42 +46 ~7 -1: test/integration.shard/migrate_utils_test.dart: legacy app creation clone and create [E]                                                                                              
  Exception: Command failed with exit code 1
  package:flutter_tools/src/base/common.dart 10:3             throwToolExit
  package:flutter_tools/src/migrate/migrate_utils.dart 260:7  MigrateUtils.checkForErrors
  package:flutter_tools/src/migrate/migrate_utils.dart 151:5  MigrateUtils.createFromTemplates
  ===== asynchronous gap ===========================
  test/integration.shard/migrate_utils_test.dart 208:7        main.<fn>.<fn>
```

I'm investigating

**Comment by christopherfujino** [comment]
LOL, also it looks like we actually test the storage bucket override message:

```
00:30 +843 ~1 -1: test/general.shard/cache_test.dart: Cache overridden storage base url prints warning to STDERR [E]                                                                                   
  Expected: contains 'Flutter assets will be downloaded from https://storage.com'
    Actual: ''
  package:test_api                          expect
  test/general.shard/cache_test.dart 333:7  main.<fn>.<fn>
  dart:async                                runZoned
  test/src/common.dart 197:14               testWithoutContext.<fn>
  test/src/common.dart 166:18               test.<fn>
```

I'll comment out this test.

**Comment by christopherfujino** [comment]
Finally got the stderr from migrate_utils_test:

```
18:26 +46 ~7 -1: test/integration.shard/migrate_utils_test.dart: legacy app creation clone and create [E]                                                                                              
  Creating a new app from template failed:
  Command encountered an error with exit code 1.
  Command:
    /b/s/w/ir/x/t/flutter_tools.AVSYDO/flutter_sdk_testMTJMSD/bin/flutter create --project-name=testapp --android-language=java --ios-language=objc --no-pub /b/s/w/ir/x/t/flutter_tools.AVSYDO/flutter_appYDSRMK
  Stdout:
    Downloading Dart SDK from Flutter engine 7375a0f414bde4bc941e623482221db2fc8c4ab5...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   267  100   267    0     0   7216      0 --:--:-- --:--:-- --:--:--  7216
  
    It appears that the downloaded file is corrupt; please try the operation again later.
    If this problem persists, please report the problem at
    https://github.com/flutter/flutter/issues/new?template=ACTIVATION.md
  
  
  Stderr:
    [/b/s/w/ir/x/t/flutter_tools.AVSYDO/flutter_sdk_testMTJMSD/bin/cache/dart-sdk-linux-x64.zip]
      End-of-central-directory signature not found.  Either this file is not
      a zipfile, or it constitutes one disk of a multi-part archive.  In the
      latter case the central directory and zipfile comment will be found on
      the last disk(s) of this archive.
    unzip:  cannot find zipfile directory in one of /b/s/w/ir/x/t/flutter_tools.AVSYDO/flutter_sdk_testMTJMSD/bin/cache/dart-sdk-linux-x64.zip or
            /b/s/w/ir/x/t/flutter_tools.AVSYDO/flutter_sdk_testMTJMSD/bin/cache/dart-sdk-linux-x64.zip.zip, and cannot find /b/s/w/ir/x/t/flutter_tools.AVSYDO/flutter_sdk_testMTJMSD/bin/cache/dart-sdk-linux-x64.zip.ZIP, period.
  
  
  Exception: Command failed with exit code 1
  package:test_api                                      fail
  test/integration.shard/migrate_utils_test.dart 218:9  main.<fn>.<fn>
```

**Comment by christopherfujino** [comment]
Marking this a draft so it does not show up in PR review

**Comment by godofredoc** [comment]
Validations are now complete, closing!

**Pull request closed without merging**
