### PR TITLE
Update Gallery usage of Scaffold.of

### PR DESCRIPTION
**Pull request by jason-simmons**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
@HansMuller are you expecting this to return null?

Ideally we'd have a test for this too...

**Comment by HansMuller** [comment]
The existing  `Scaffold.of(context)?.appBarAnimation` should not have included the '?.'.  

The Scaffold.of() call is within a Builder widget that only exists so that the Scaffold.of() call will succeed.

**Comment by Hixie** [comment]
So it should not be returning null? It apparently is...

**Comment by HansMuller** [comment]
The problem appears to be the Scaffold's key: 
https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/gallery/home.dart#L102

I don't think there's any need for `_homeKey` and removing it fixes the problem.

**Comment by jason-simmons** [comment]
I'm still seeing Scaffold.of() returning null after removing the _homeKey

**Comment by HansMuller** [comment]
Yes, sorry about the misdirection. Although the problem seemed to have gone away after removing _homeKey (which I still don't think is needed), trying the remedy again fails for me too.

**Comment by jason-simmons** [comment]
Scaffold.of() seems to be returning null due to some sort of race involving the hero animation subsystem.

If the Builder within Gallery's AppBar is invoked while the animation is still in progress, then the AppBar widgets will be descendants of the HeroQuestState transition widgets and will not have a Scaffold ancestor.

@Hixie

**Comment by abarth** [comment]
Oh, that makes sense.  During the page transition, the AppBar is a hero that persists during the transition.  When it is transitioning, it isn't a child of the scaffold.

**Comment by jason-simmons** [comment]
Changed this to use a GlobalKey to locate the scaffold

PTAL

**Comment by HansMuller** [comment]
LGTM!

**Comment by Hixie** [comment]
Ideally this would have a test -- in fact I'm surprised the smoketest didn't catch this.

**Pull request merged**
