### PR TITLE
try fedors dashing fork

### LINKED ISSUE #60646: dashing (docset generation) is disabled due to taking too long
I noticed this started happening 6/29/20. Here's [an example](https://cirrus-ci.com/task/6625596312649728) (on that PR it timed out twice in a row).

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change. If you're changing visual properties, consider including before/after screenshots (and runnable code snippets to reproduce them).*

## Related Issues

Fixes https://github.com/flutter/flutter/issues/60646

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behavior with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by fkorotkov** [comment]
It should. I built it yesterday in my fork but the task failed with some weird issues and I got distracted by some other things. Could you please also try to set USE_IN_MEMORY_DISK to true?

**Comment by christopherfujino** [comment]
> It should. I built it yesterday in my fork but the task failed with some weird issues and I got distracted by some other things. Could you please also try to set USE_IN_MEMORY_DISK to true?

ahh, ok, maybe it's pulling in the cache from your test yesterday. switching to in memory disk.

**Comment by fkorotkov** [comment]
🤞

**Comment by christopherfujino** [comment]
Also, it looks like we (maybe me) updated docs.sh after disabling dashing on pre-submit, so if all goes well this will fail at the end trying to deploy. Still, we should be able to benchmark docset generation time, and if we land this we can just update the script to handle PRs.

**Comment by christopherfujino** [comment]
@fkorotkov switching to memory disk resulted in OOM killed

**Comment by fkorotkov** [comment]
You can try to bump to 12G. 🤔 Don't think it will need more then 4G.

**Comment by christopherfujino** [comment]
The task failed, but because of an unrelated bug: https://cirrus-ci.com/task/6251878486900736.

However, it concerns me that it took so long, 54:39. This doesn't seem faster than upstream Dashing. Any thoughts @fkorotkov ?

**Pull request closed without merging**
