### PR TITLE
Add more docs to `OrientationBuilder`

### PR DESCRIPTION
**Pull request by tvolkert**

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by HansMuller — APPROVED** [review]
LGTM too.  The name will probably still confuse people; I suppose it's really the parent's aspect ratio that we're telling the builder about.

**Comment by tvolkert** [comment]
Merging on red because it looks like the source of the redness is GitHub being down, but it's back up.

**Review by postmasters — COMMENTED** [review]
s/a factor/a ratio of/

**Pull request merged**
