### PR TITLE
Revert "[text_input] introduce TextInputControl"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#76072

An apparent bugfix in the Dart SDK is newly revealing that this change broke super_editor in customer_testing.

https://github.com/superlistapp/super_editor/pull/837

Unfortunately, super_editor is broken on Flutter master channel, so we are unable to simply apply the compensating change there and roll a new version into flutter/tests. Since the breakage is only revealed by a new Dart SDK, we are blocked from rolling the Engine into the framework until this is resolved. Since the roll blockage is a P0, we are preferring to solve it by landing a revert.

### CODE REVIEW

**Review by justinmc — APPROVED** [review]
LGTM 👍

**Comment by zanderso** [comment]
This can be relanded after https://github.com/flutter/tests/pull/165 lands.

**Comment by justinmc** [comment]
Looks like https://github.com/flutter/tests/pull/165 was landed, @jpnurmi are you able to resubmit your PR https://github.com/flutter/flutter/pull/76072?

**Comment by jpnurmi** [comment]
Thanks, resubmitted: https://github.com/flutter/flutter/pull/113758

**Pull request merged**
