### PR TITLE
Signal an error in the dependency checker if an import URI is invalid

### LINKED ISSUE #11539: Flutter run crashes if there is an invalid imports in the application sources.
Trying to `flutter run` an application with an invalid import in the source code makes __flutter tools__ crash.

```dart
import 'package:flutter/widgets.dart';
import '[object Object].dart';

void main() => runApp(const Center(child: const Text('Hello, world!')));
```

The crash is at https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/dart/dependencies.dart#L68

Log
```
## command

flutter run

## exception

FormatException: FormatException: Invalid character (at character 1)
[object Object].dart
^

0      _Uri._fail (dart:core/uri.dart:1597)
1      _Uri._normalize (dart:core/uri.dart:2292)
2      _Uri._normalizeOrSubstring (dart:core/uri.dart:2248)
3      _Uri._makePath (dart:core/uri.dart:2096)
4      new _Uri.notSimple (dart:core/uri.dart:1460)
5      Uri.parse (dart:core/uri.dart:1012)
6      DartDependencySetBuilder.build (package:flutter_tools/src/dart/dependencies.dart:68)
7      HotRunner._refreshDartDependencies (package:flutter_tools/src/run_hot.dart:76)
8      HotRunner.run (package:flutter_tools/src/run_hot.dart:177)
<asynchronous suspension>
9      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:339)
<asynchronous suspension>
10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:217)
<asynchronous suspension>
11     RunCommand.verifyThenRunCommand (package:flutter_tools/src/commands/run.dart:227)
<asynchronous suspension>
12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:159)
<asynchronous suspension>
13     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:277)
<asynchronous suspension>
15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
16     new Future.sync (dart:async/future.dart:222)
17     CommandRunner.run (package:args/command_runner.dart:109)
18     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:161)
19     run.<anonymous closure> (package:flutter_tools/executable.dart:142)
<asynchronous suspension>
20     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
21     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
22     _rootRun (dart:async/zone.dart:1120)
23     _CustomZone.run (dart:async/zone.dart:1001)
24     runZoned (dart:async/zone.dart:1467)
25     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
26     run (package:flutter_tools/executable.dart:114)
<asynchronous suspension>
27     main (package:flutter_tools/executable.dart:67)
<asynchronous suspension>
28     main (file:///C:/Users/B3rn475/git/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
29     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/11539

### CODE REVIEW

**Comment by jason-simmons** [comment]
@B3rn475

**Review by goderbauer — COMMENTED** [review]
Can you add a test for this?

**Comment by B3rn475** [comment]
+1 for the test

**Comment by jason-simmons** [comment]
Added a test - PTAL

**Review by B3rn475 — APPROVED** [review]

**Pull request merged**
