### PR TITLE
Super tiny code optimization: No need to redundantly check whether value has changed

### PR DESCRIPTION
**Pull request by fzyzcjy**
This super tiny code optimization removes two `if` checks, because when doing `ValueNotifier.value = ...`, it already checks whether old value == new value. If so, it already early halts. Therefore, it seems that we do not need to check whether the value is unchanged outside again - which is a duplication.

I am eager to submit larger and nontrivial PRs (and have already submitted many), however... :(

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by justinmc — APPROVED** [review]
LGTM with a test exemption.

Thanks for fixing these!  No PR is too small haha.  You're definitely right here.

What's the problem with your larger PRs?

Also, can you get a test exemption here?  See the bot comment above.

**Comment by fzyzcjy** [comment]
@justinmc Thank you!

As for the larger PRs, the one that is most important to me (because it is a bug that frequently happen in my app) is: https://github.com/flutter/flutter/pull/127456

P.S. test exemption request submitted https://discord.com/channels/608014603317936148/608018585025118217/1126652492848046160

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

**Pull request merged**
