### PR TITLE
Fix the maths for floating pinned app bars.

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by nonameden** [comment]
@Hixie  as far as I remember `RenderSliverFloatingPersistentHeader` have same issue as `RenderSliverFloatingPinnedPersistentHeader`

Please let me know if you need more info or sample to reproduce that issue

**Comment by Hixie** [comment]
I couldn't find an equivalent error in RenderSliverFloatingPersistentHeader. If you have an example that would be very useful.

**Comment by nonameden** [comment]
I have checked with latest version of Flutter, looks like there was some changes since my PR. changing maxExtent to minExtent in render class does not affect NestedScrollView anymore.

Please use Gist from @HansMuller for testing: https://gist.github.com/HansMuller/facae02ce97892eaa2f159ea50c45e61

Issue easy to replicate with `floating: true, pinned: true` and `floating: false, pinned: true` for sliver app bar inside `NestedScrollView`

**Comment by Hixie** [comment]
@nonameden I don't really understand that issue. Can you file a bug for it? Then we can handle it separately.

**Comment by nonameden** [comment]
Already did: #11222 
Just to clear on issue: inside the page we have a container with text `1 Header` - during a scroll it should not scroll under the pinned action bar.

**Comment by Hixie** [comment]
> #11222

Great, thanks. That looks like a separate issue.

**Comment by nonameden** [comment]
Yep, but before it was fixable with `minExtent` in renderer, because scroller in `NestedScrollView` was using it to calculate scroll range for outer scroll

**Comment by HansMuller** [comment]
LGTM

**Pull request merged**
