### PR TITLE
more verbose error message

### PR DESCRIPTION
**Pull request by sethladd**
Because "root of a project" was a little unclear to me.

cc @eseidel

### CODE REVIEW

**Comment by jimbeveridge** [comment]
How about, "This command should be run from the root of your Flutter project." (changed "a" to "your".)

Also, I believe it's eventually supposed to be work to update the Flutter directories (especially the samples) by running flutter upgrade at the root of the flutter tree. This was not working when I tried earlier this week. The workaround is to run `dev/update_packages.dart`.

**Comment by Hixie** [comment]
see issue #339

**Comment by sethladd** [comment]
Thanks @Hixie . ptal

**Comment by Hixie** [comment]
I would probably output the last sentence only if we detected that that's what had happened somehow, and otherwise would say "The current directory does not have a pubspec.yaml file." instead.

But either way, LGTM.

**Comment by sethladd** [comment]
Agreed, we could do more detection here.

**Pull request merged**
