### PR TITLE
Tight Paragraph Width

### LINKED ISSUE #26585: Text widget doesn't change it's size when line break happened
Same problem from android, there I override onMeasure to change Text widget size when line break happened. 

Here is code 
``` dart build(context) {
    return Column(
        crossAxisAlignment: me ? CrossAxisAlignment.end : CrossAxisAlignment.start,
        children: <Widget>[
          Container(
            margin: const EdgeInsets.only(bottom: 8.0, left: 8.0, right: 8.0),
            padding: const EdgeInsets.all(8.0),
            decoration: BoxDecoration(
              color: Colors.teal,
              borderRadius: BorderRadius.only(
                topRight: Radius.circular(15.0),
                topLeft: Radius.circular(15.0),
                bottomLeft: me ? Radius.circular(15.0) : Radius.circular(0.0),
                bottomRight: me ? Radius.circular(0.0) : Radius.circular(15.0),
              )
            ),
            child: Text(message),
          ),
        ],
      );
  }
```

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale ru-RU)
    • Flutter version 1.0.0 at /Users/daniel/crossplatform/flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/daniel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • iPhone XR • 0ED8A7F1-CE8A-4026-820D-1763AF319C68 • ios • iOS 12.1 (simulator)

! Doctor found issues in 2 categories.
```

### PR DESCRIPTION
**Pull request by justinmc**
Closes https://github.com/flutter/flutter/issues/26585, #15300
Depends on https://github.com/flutter/engine/pull/8530

Paragraph currently sets its width to be the maximum space allowed for it when it wraps beyond one line.  This creates extra empty space when you want to draw something with a tight container:

51184156-82592080-18e4-11e9-8906-2bbce4f6327f

This PR will enable the drawing of a paragraph with a width only as wide as it needs to be to contain wrapping text tightly.

### CODE REVIEW

**Comment by justinmc** [comment]
This will have to wait for the corresponding engine PR to go in before its tests can pass (https://github.com/flutter/engine/pull/8530).

**Comment by HansMuller** [comment]
It might be best to change the naming for the sake of consistency. Stacks have a fit parameter whose value is StackFit (enum). Since this feature is for Text: maybe Text.fit and TextFit, where TextFit is either expand or tight.

**Comment by GaryQian** [comment]
I do think that the word `Width` should probably be in there somewhere as this specifically deals with the width of the paragraph.

**Comment by HansMuller** [comment]
@GaryQian How about TextFitWidth and Text.fitWidth?

**Comment by GaryQian** [comment]
Maybe TextWidthFit sounds a bit more natural?

**Comment by sroddy** [comment]
is this related/the same issue? https://github.com/flutter/flutter/issues/15300

**Comment by GaryQian** [comment]
Yes, #15300 seems to be the same issue. Adding to the desc.

**Comment by HansMuller** [comment]
OK, I propose that we call the enum `TextWidthBasis` (because it's what the text widget's width is based on), with values `parent` and `longestLine`, and we call the parameter `textWidthBasis`.

**Comment by justinmc** [comment]
This is ready for a final review.

```dart
// The current behavior, unchanged.
// A short single line is wrapped tightly.
// Multiple lines cause the text to take the full width of its parent.
Text(
  string,
  textWidthBasis: TextWidthBasis.parent, //default
)
```

```dart
// For a single line, the behavior is the same! Tightly wrapped.
// For multiple lines, the width is only the width of the longest line.
Text(
  string,
  textWidthBasis: TextWidthBasis.longestLine,
)
```

Green is `parent` and pink is `longestLine`:

**Comment by justinmc** [comment]
The tests are failing because they think `longestLine` doesn't exist in the engine, but the engine was rolled into flutter/flutter with my change here: https://github.com/flutter/flutter/commit/3cd15b52d4f85443c9eaa8f687a4e3a0e0175da9

Do I need to wait for something else?

**Comment by GaryQian** [comment]
Sometimes the luci engine buildbots haven't caught up yet, i'd check https://ci.chromium.org/p/flutter/builders/luci.flutter.prod/Linux%20Host%20Engine

Although it does look like everything is caught up.

**Comment by justinmc** [comment]
@dnfield After merging in your addition of `flutter doctor`, the same tests are still failing.  If I look at the output of the failure, I don't think I see `flutter doctor` being run, but maybe I'm looking for the wrong thing.  Shouldn't I find something with ctrl-f "doctor" in the failing test output?

**Comment by dnfield** [comment]
It looks like it ran from the output.  Are we sure 6280d4266983ff8eff24f26164d10172e3824385 is the right engine hash?

**Comment by justinmc** [comment]
Yeah that hash should be fine.  The engine commit I need is https://github.com/flutter/engine/commit/3493dcfbaec516effcde49e3fae68a33427045da, which looks to be about 5 days older than 6280d4266983ff8eff24f26164d10172e3824385.

**Comment by justinmc** [comment]
I'm going to go ahead and merge this and see what happens.  If anything fails then I'll immediately revert.

**Comment by dnfield** [comment]
SGTM.

**Pull request merged**
