### PR TITLE
prefer const constructors

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
Are we able to turn on the lint?

**Comment by a14n** [comment]
I will. It remains issues with `*Key`. Some PRs will follow.

**Comment by Hixie** [comment]
This patch noticeably increased our technical debt (by adding lots of //ignores). We could work around that by using variables rather than literals for the keys where you ignored the lint. This would  actually more accurately represent the case we're trying to test, too.

**Pull request merged**
