### PR TITLE
Switch branch correctly when there's a directory with the same anme

### LINKED ISSUE #14865: Alpha -> Dev upgrade path
## Steps to Reproduce

I had noticed this when I tried to upgrade the following notice:
`Transitioning from 'alpha' to 'dev'...`
However, when I do a `git status` it still says "alpha".   

So apparently it is NOT switching from `Alpha` to `Dev`.   

So I did some quick issue searching and found out `Alpha` branch is now depreciated and `dev` is the new place I should be.      For those who might see this issue: https://flutter.io/upgrading/ has the info about dev being more stable than master.

To fix, I had to manually use git to checkout the "dev" branch and put me on it...

##LOGS

`flutter upgrade -v`

```
[  +37 ms] [C:\Android\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +187 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/alpha
[   +1 ms] [C:\Android\flutter\] git rev-parse --abbrev-ref HEAD
[ +123 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] alpha
[   +2 ms] [C:\Android\flutter\] git ls-remote --get-url origin
[ +128 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[   +3 ms] [C:\Android\flutter\] git log -n 1 --pretty=format:%H
[ +132 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 2e449f06f0a3be076e336ad6b30b0e9ec99dbdfe
[   +1 ms] [C:\Android\flutter\] git log -n 1 --pretty=format:%ar
[ +139 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 weeks ago
[   +4 ms] [C:\Android\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +155 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v0.0.21-0-g2e449f0
[ +455 ms] [C:\Android\flutter\] git rev-parse @{u}
[ +186 ms] 2e449f06f0a3be076e336ad6b30b0e9ec99dbdfe
[   +3 ms] Upgrading Flutter from C:\Android\flutter...
[   +3 ms] Transitioning from 'alpha' to 'dev'...
[   +7 ms] [C:\Android\flutter\] git checkout dev
[ +285 ms] [C:\Android\flutter\] git pull --ff-only
[+4499 ms] Already up-to-date.
[   +9 ms] Upgrading engine...
[   +1 ms] [C:\Android\flutter\] C:\Android\flutter\bin\flutter --no-color precache
[+2657 ms] Already up-to-date.
[ +462 ms] Flutter 0.0.21 • channel alpha • https://github.com/flutter/flutter.git
           Framework • revision 2e449f06f0 (4 weeks ago) • 2018-01-29 14:26:51 -0800
           Engine • revision 6921873c71
           Tools • Dart 2.0.0-dev.16.0
[   +5 ms] Running flutter doctor...
[ +490 ms] [√] Flutter (on Microsoft Windows [Version 6.1.7601], locale en-US, channel alpha)
[   +2 ms]     • Flutter version 0.0.21 at C:\Android\flutter
[   +1 ms]     • Framework revision 2e449f06f0 (4 weeks ago), 2018-01-29 14:26:51 -0800
[   +1 ms]     • Engine revision 6921873c71
[   +1 ms]     • Tools Dart version 2.0.0-dev.16.0
[   +1 ms]     • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a
[ +200 ms] java -version
[ +180 ms] [√] Android toolchain - develop for Android devices (Android SDK 26.0.2)
[   +2 ms]     • Android SDK at C:\Android\sdk
[   +1 ms]     • Android NDK at C:\Android\sdk\ndk-bundle
[   +1 ms]     • Platform android-26, build-tools 26.0.2
[   +1 ms]     • ANDROID_HOME = C:\Android\sdk
[   +1 ms]     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
[   +1 ms]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
[   +5 ms] [√] Android Studio (version 3.0)
[   +1 ms]     • Android Studio at C:\Program Files\Android\Android Studio
[   +1 ms]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
[ +182 ms] [√] IntelliJ IDEA Ultimate Edition (version 2017.3)
[   +1 ms]     • Flutter plugin version 20.0.3
[   +1 ms]     • Dart plugin version 173.4127.31
[  +18 ms] C:\Android\sdk\platform-tools\adb devices -l
[  +60 ms] Exit code 0 from: C:\Android\sdk\platform-tools\adb devices -l
[   +1 ms] List of devices attached
[  +18 ms] C:\Android\sdk\platform-tools\adb devices -l
[  +52 ms] List of devices attached
[   +1 ms] [-] Connected devices
[   +1 ms]     • None
[  +37 ms] "flutter upgrade" took 9,493ms.
[ +260 ms] ensureAnalyticsSent: 254ms
[   +4 ms] exiting with code 0
```

```
C:\Android\flutter>git status
On branch alpha
Your branch is up-to-date with 'origin/alpha'.
nothing to commit, working directory clean
```

### PR DESCRIPTION
**Pull request by Timmmm**
Fixes #14865 probably. I haven't tested this other than by running the git command manually.

### CODE REVIEW

**Comment by mit-mit** [comment]
I think @Hixie may have fixed this in https://github.com/flutter/flutter/pull/14507 ?

**Comment by Phrohdoh** [comment]
Being nit-picky: This doesn't check for the existence of a directory with the given name.

**Comment by Timmmm** [comment]
@Phrodoh, sorry I don't understand what you mean? It isn't meant to check out a directory...

**Comment by tvolkert** [comment]
I didn't see this outstanding PR and submitted the same thing in https://github.com/flutter/flutter/pull/15026.  Closing

**Pull request closed without merging**
