### PR TITLE
Clamp scrollOffset to prevent textfield bouncing

### LINKED ISSUE #38417: Typing in different language other than English in multilines textfield makes letters shake.
## Steps to Reproduce

1. Run Flutter Gallery in examples project in Flutter SDK.
2. Navigate to Material -> Text Fields
3. Try typing in Life Story (Multilines TextField) in different languages such as Thai or Japanese causing the letters to shake. The shaking stop when type to the second line. Select the text at first line when its have multiple lines also cause the bug. This bugs seems to only appear when build on both IOS Simulator and real device.

## Example

```
No issues found! (ran in 5.5s)
```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-TH)
    • Flutter version 1.7.8+hotfix.4 at /Users/chatchapol/sdk/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/chatchapol/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)

```

### PR DESCRIPTION
**Pull request by GaryQian**
Fixes https://github.com/flutter/flutter/issues/38417 and https://github.com/flutter/flutter/issues/37377

This PR clamps the scrollOffset between 0 and the max scroll extent to prevent overscrolling while typing.

To accomplish this, `maxScrollExtent` is exposed in RenderEditable where the scroll extents are computed.

### CODE REVIEW

**Comment by GaryQian** [comment]
It is unclear to me how I can repro the exact conditions in a test, since it is font/language/device/platform/timing dependent.

**Review by justinmc — COMMENTED** [review]
This doesn't seem to fix https://github.com/flutter/flutter/issues/37377 for me.  I still see it bounce like this:

bounce

You might be able to write a test for this by doing what's shown in that gif and checking that the text field hasn't scrolled.  I think it should be consistently reproducible in a test if you set TextStyle's height to something pretty high.

**Comment by GaryQian** [comment]
Looks like the height of the paragraph isn't quite what I need to clamp by to prevent this on the bottom edge. The top edge is fixed by clamping to zero though.

**Comment by GaryQian** [comment]
Need to clamp to height of the text minus height of the field.

**Comment by GaryQian** [comment]
This new version should clamp properly for both the top and bottom. Adding tests.

**Comment by justinmc** [comment]
That fixed it for me, thanks!  I'll give this a final review when you finish the tests.

**Comment by GaryQian** [comment]
@justinmc Should be ready for review!

**Review by justinmc — APPROVED** [review]
LGTM 👍

**Pull request merged**
