### PR TITLE
Add test for search_anchor.0.dart

### PR DESCRIPTION
**Pull request by ValentinVignal**
Contributes to https://github.com/flutter/flutter/issues/130459

It adds a test for
- `examples/api/lib/material/search_anchor/search_anchor.0.dart`

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Review by piedcipher — APPROVED** [review]
LGTM! Thanks for contributing..

**Comment by bleroux** [comment]
@piedcipher
Thanks for reviewing this.
Gentle reminder that reviewers should be careful about details: in this PR there are 3 occurrences of the following format error: `widget.color ==const Color(0xff6750a4)` (missing space).

Also consider letting the author adding the autosubmit label:
- It will give time for a last check
- For many contributors it is a pleasure to add the autosubmit label because it is the last step of their work.

**Comment by ValentinVignal** [comment]
@bleroux Sorry for (once again) a formatting issue 😥 

I can make a PR to fix that

**Comment by piedcipher** [comment]
> @piedcipher Thanks for reviewing this. Gentle reminder that reviewers should be careful about details: in this PR there are 3 occurrences of the following format error: `widget.color ==const Color(0xff6750a4)` (missing space).
> 
> Also consider letting the author adding the autosubmit label:
> 
> * It will give time for a last check
> * For many contributors it is a pleasure to add the autosubmit label because it is the last step of their work.

I noticed this but I was unsure if we should've space. I'll be mindful about this. Thank you

**Comment by bleroux** [comment]
@ValentinVignal @piedcipher 
No worries, we all make mistakes and those ones were very very minor. My main point was about not applying the autosubmit label as it might help the author or someone else to give a last look.
Thanks for all your contributions :pray:

**Pull request merged**
