### PR TITLE
Allow Hybrid Composition fallback for Android platform views

### LINKED ISSUE #107313: `initSurfaceAndroidView` uses Virtual Display as fallback mode
(This is a summary of my current understanding; it's possible there are mistakes here.)

Prior to Flutter 3.0, we had two modes for Android PlatformViews:
- Virtual Display: min SDK version 20, lots of limitations around non-trivial views (no a11y support, some secondary controls in webviews didn't work, etc.)
    - This was selected using `initAndroidView`, which mapped to `TextureAndroidViewController`.
- Hybrid Composition: min SDK version 19: has threading implications, and performance on Android <10 is poor, but highly compatible.
    - This was selected using `initSurfaceAndroidView`, which mapped to `SurfaceAndroidViewController`.

In 3.0 we added a new mode (it doesn't have a formal name, but [the initial PR for it](https://github.com/flutter/engine/pull/31198) refers to "hybrid composition rendered as a texture layer", so I'm going to call it Texture Layer Hybrid Composition for now). The theory was that this would be strictly better than both modes and would thus replace both, and it was landed that way. But since then, various regressions were discovered and changes were made to the flow, most notably the recent https://github.com/flutter/engine/pull/33599

In the new flow, AFAICT, the modes are:
- Texture Layer Hybrid Composition: min SDK version 23, and doesn't work with SurfaceView. Also apparently [doesn't handle transparency on SDK <29](https://github.com/flutter/flutter/issues/104686#issuecomment-1156763554)
    - This is selected using either `initSurfaceAndroidView` or `initAndroidView` if the SDK and view type requirements are met.
- Virtual Display: now selected as a fallback for `initSurfaceAndroidView` or `initAndroidView` for SDK <23 or for `SurfaceView` native views.
- Hybrid Composition: now selected with `initExpensiveAndroidView`.

If this is correct, there are some pretty bad effects from the current state, for plugins that previously used Hybrid Composition. They now either use the new TLHC mode (which was the initial goal, when it was thought that this was a transparent update), or with the most recent change fall back **to Virtual Display**. So for instance `webview_flutter` (which we had previous switched to default to HC), which we don't want to be using VD due to the significant limitations, now does in some cases, in which case we unexpectedly:
  - dropped support for SDK 19, and
  - will have functionality regressions in SDK 20-22

And the only way to fix that would be to fully switch it to HC again (`initExpensiveAndroidView`), which means we wouldn't get the new behavior mode even when it would be supported.

I don't think this is a good state to leave the transition in. I see two better options:
1. Revert the behavioral change for `initSurfaceAndroidView` (so it goes back to using HC) and add a new explicit opt-in to the new mode.
1. Keep track of whether `initSurfaceAndroidView` or `initAndroidView` was originally called, and restructure things so that the fallback in unsupported cases is either to VD or HC depending on what was originally called, so that existing HC plugins don't have behavioral changes on SDK 20-22.

/cc @bparrishMines @cyanglaz @GaryQian @dnfield @Hixie for thoughts.

### PR DESCRIPTION
**Pull request by stuartmorgan-g**
Allows for the new Android platform view mode introduced in Flutter 3.0 (tentatively called Texture Layer Hybrid Composition) to fall back to Hybrid Composition rather than Virtual Display when TLHC mode is not supported if it was created with `initSurfaceAndroidView`, which was HC in Flutter 2.x. This allows us to avoid the issue introduced in Flutter 3.0 where a plugin that previously used HC will now use VD in some cases, which would not be the plugin author's intent since they had explicitly chosen the initialization mode that was for HC in Flutter 2.x.

In order to minimize breaking changes (in the hopes of cherry picking this to `beta`), this keeps all of the existing class return types, and extracts all of their logic to display-specific helpers that can be delegated to, allowing for the same class to switch from TLHC (which uses texture display) to HC (which composes actual views).

Fixes https://github.com/flutter/flutter/issues/107313
Engine portion: https://github.com/flutter/engine/pull/35233

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@bparrishMines @dnfield Same here; still needs tests, but I would appreciate feedback.

I have concerns about the fundamentals of the create/resize logic code here for TLHC (i.e., I suspect there are more subtle race conditions that are still latent here that this change neither fixes nor worsens), but wanted to limit the scope here since I am still hoping to get this onto `beta`.

**Comment by stuartmorgan** [comment]
> This also fixes a 3.0 regression found during manual testing, where `create` is sometimes called multiple times: once by the plugin author, but then again by internal code that was only intended to be used for TLHC and VD, but due to the async nature of the initialization, was being called for HC as well. Because some plugin authors have noticed the double-call bug and worked around it by removing their `create`, we can't actually directly fix the double-create without more extensive changes (unless we re-break plugins that worked around the 3.0 bug), so for now this drops duplicate calls, and leaves TODOs for fixing it more cleanly.

With more investigation, it looks like this is actually a 3.1+ regression, so I'm going to split it out into its own fix. It's a new regression that only affects beta, and it severely breaks HC mode, so should be fixed and cherry-picked separately. (I was hoping to avoid layer fixes and cherry picks, but this seems critical enough to take that risk.)

**Comment by stuartmorgan** [comment]
This still needs widgets tests for the new switching widget, but I think it would be worth reviewing now to see if that approach is in fact what we want before I implement the tests for it.

**Review by bparrishMines — APPROVED** [review]
LGTM Someone on the framework team should should probably have a look as well though. I'm not sure who currently own this code

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by orestesgaolin** [comment]
I have a small question. After this gets merged what would be the breakdown of modes?

- `initSurfaceAndroidView` -> TLHC, but can fallback to HC when SDK <23
- `initAndroidView` -> TLHC, but fallback to VD when SDK <23
- `initExpensiveAndroidView` -> always TLHC (?)

**Comment by stuartmorgan** [comment]
> * `initExpensiveAndroidView` -> always TLHC (?)

This PR doesn't change the behavior of `initExpensiveAndroidView`. It continues to always use HC.

> What would be used by default by `AndroidView`?

This PR doesn't change the behavior of `AndroidView`, which calls `initAndroidView`.

**Comment by goderbauer** [comment]
(triage): @stuartmorgan do you still have plans for this PR?

**Comment by stuartmorgan** [comment]
I'll be updating it shortly to be landing-ready; the engine side just landed.

**Pull request merged**
