### PR TITLE
[flutter_tools] reduce global count with this one weird trick

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Avoid restating Pub injection unnecessarily to reduce global count

### CODE REVIEW

**Review by jmagman — COMMENTED** [review]
This is cute but it's such a one-off and kind of random.  Can we exclude the tests (and maybe `context_runner`) from the globals count?

**Comment by jonahwilliams** [comment]
Yeah, that seems like a reasonable approach too. We need to get rid of testing globals, but its not as important as what is in lib.

WDUT @zanderso @christopherfujino  ?

**Comment by zanderso** [comment]
Excluding `context_runner.dart` sounds fine to me, but I'd prefer counting tests, since one of the goals of the refactor is making testing easier.

**Comment by jonahwilliams** [comment]
We could measure them separately, like we do for dependencies.

one for globals under `lib/`, and one for globals under `test/`

**Comment by christopherfujino** [comment]
> Excluding `context_runner.dart` sounds fine to me, but I'd prefer counting tests, since one of the goals of the refactor is making testing easier.

I agree.

> We could measure them separately, like we do for dependencies.
> 
> one for globals under `lib/`, and one for globals under `test/`

I like this idea.

**Comment by jmagman** [comment]
If we care about the globals count in tests then we should feel the shame of all those globals and not try to DRY them out for the sake of the counts.

**Comment by jonahwilliams** [comment]
SGTM, I'm going to close this one for now

**Pull request closed without merging**
