### PR TITLE
Remove some obsolete // ignore:

### PR DESCRIPTION
**Pull request by goderbauer**
## Description

These were no longer ignoring any warnings. They have been identified as obsolete by @srawlins in https://github.com/flutter/flutter/pull/45855.

## Related Issues

None

## Tests

I added the following tests:

None, comment only change.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by Piinks — APPROVED** [review]
LGTM

**Comment by Piinks** [comment]
Although cirrus seems to be unhappy right now. Looks to be timeouts.

**Comment by goderbauer** [comment]
Restarted all the cirrus checks that timed out.

**Comment by dnfield** [comment]
This would be a good one to land on red to kick CI.  We've disabled some fuchsia tests that are flaky right now.  That should be rolled through in a few minutes.

**Comment by goderbauer** [comment]
@dnfield Feel free to submit this whenever the roll is done.

**Comment by goderbauer** [comment]
Submitting on red per @dnfield's comment.

**Pull request merged**
