### PR TITLE
fix the return type on flutterPlatformOverride()

### PR DESCRIPTION
**Pull request by devoncarew**
- fix the return type on `flutterPlatformOverride()` (noticed while browsing around the code)

### CODE REVIEW

**Comment by Hixie** [comment]
Woah, woah, hold on. How did the analyzer not catch this?

The last line is returning a string literal.
The function is an async function of type `Future<Null>`.
How is that valid!

**Comment by Hixie** [comment]
LGTM but i'm baffled by how this was not caught by the analyzer.

**Comment by devoncarew** [comment]
Yeah, it looked odd when I ran across it. The method was defined to return null, but callers we're using it as if it returned `String`.  @leafpetersen, is this correct wrt the type system, or should we file a repro case against the analyzer?

**Comment by leafpetersen** [comment]
This is WAI, mostly.   Statically, this is an implicit downcast.  An async function with return type `Future<Null>` must return something assignable to either `Null` or `Future<Null>`, and `String` is assignable to `Null` (it's a downcast: the value could be null).

There is an implied Strong Mode runtime check on the downcast which would fail, but since you are running on the VM, you don't yet get those (in Dart 1.0, I believe that `async` functions always dynamically return `Future<dynamic>`, so you won't get a checked mode error either).

We do try to give errors on "stupid" casts which are guaranteed to fail in strong mode: e.g. a downcast of a literal.  We should be doing that for this case: we may not have implemented it for `String` literals yet.

**Comment by Hixie** [comment]
Is the plan eventually to get rid of the "implicit downcast" thing? I thought we were working towards that (e.g. with the "covariant" keyword on parameters).

**Comment by leafpetersen** [comment]
I had actually been under the impression that you guys (Flutter) were fairly strongly in the camp of wanting implicit downcasts.  There is a `no-implicit-casts` option that you can set in your .analysis_options file if you want to try out life without them.  I'd be interested in hearing any feedback that you have about it if you do try it.  There is some interest in exploring that direction, perhaps combined with an easy (and terse) syntax for inserting the "obvious" cast.  

cc @floitschG

**Comment by Hixie** [comment]
there's definitely cases that I'd love to catch because they're so "obviously" wrong, like:

```dart
   List<Foo> foos = bar.map<Foo>(...);
```

...which today fails at runtime instead of analysis time. There's also definitely been times when the casts aren't implicitly allowed, and we have to do:

```dart
   Foo foo = bar.baz(); // returns a supertype of Foo
   foo.lala();
```

...instead of being able to do:

```dart
   bar.baz().lala();
```

...where it would be nice if we could instead do:

```dart
  (bar.baz() as Foo).lala();
```

...which today we avoid because it introduces an extra check in release mode. But I believe in the future once the VM is strong-mode enabled the code with the assignment to a variable and the code with the inline `as` will be equivalent, and so we will be able to move to using `as` everywhere? Maybe once we can use `as` without paying an extra cost, implicit downcasts won't be needed. So long as we can still do the covariant overrides and covariant parameter stuff.

**Pull request merged**
