### PR TITLE
Roll engine.

### PR DESCRIPTION
**Pull request by aam**
Changes since last roll:
```
94cdd8103 Roll dart. (#4902)
af63732de Support `Path.addCircle` (#4783)
564c6a5a9 Add hint to use ninja with goma (#4894)
9af82c5a1 Rolled Dart SDK to e3051175192c83fafa3636c0f16d804734bb285a (#4877)
ea7bb0d5f (origin/master, origin/HEAD) libtxt: move to the next run if the current run ends before the start of the line block (#4891)
```

### CODE REVIEW

**Comment by aam** [comment]
Created https://github.com/dart-lang/pub/issues/1853 for `pub` failure.

**Comment by nex3** [comment]
dart-lang/pub#1854 will fix the pub issue.

**Comment by aam** [comment]
After merging updated list of changes "since the last roll":
```
ec1e96864 Revert pub roll from recent dart roll. (#4904)
ac552fba4 Port flutter content handler to FIDL2. (#4903)
94cdd8103 Roll dart. (#4902)
af63732de Support `Path.addCircle` (#4783)
564c6a5a9 Add hint to use ninja with goma (#4894)
```

**Review by cbracken — APPROVED** [review]
LGTM

**Pull request merged**
