### PR TITLE
Skip the drawShadow call in a MergeableMaterial with zero elevation

### LINKED ISSUE #89490: ExpansionPanel with no elevation and Colors.transparent has grey overlay
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:
<details>
  <summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool isExpanded1 = false;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(title: const Text('Test')),
        backgroundColor: Colors.green,
        body: ListView(
          children: [
            ExpansionPanelList(
              animationDuration: const Duration(milliseconds: 400),
              elevation: 0,
              expansionCallback: (int panelIndex, bool isExpanded) => setState(() => isExpanded1 = !isExpanded1),
              expandedHeaderPadding: EdgeInsets.zero,
              children: <ExpansionPanel>[
                ExpansionPanel(
                  backgroundColor: Colors.transparent,
                  canTapOnHeader: true,
                  headerBuilder: (BuildContext context, bool isExpanded) => Column(
                    children: const <Widget>[
                      ListTile(
                        title: Text('Title 3'),
                        subtitle: Text('Subtitle'),
                        contentPadding: EdgeInsets.symmetric(horizontal: 12.0),
                      ),
                    ],
                  ),
                  isExpanded: isExpanded1,
                  body: const SizedBox(),
                ),
              ],
            )
          ],
        ),
      ),
    );
  }
}
```
</details>

3. Launch on Xcode iOS simulator
4. Launch on a physical iOS device
5. Observe that there's a different "output" (real iOS device has a grey "overlay") 

**Expected results:** 
I expected the ExpansionPanel to be transparent if I provide Colors.transparent.

**Actual results:** 
On a real iOS device (tested on multiple iOS versions), I get a grey color on the ExpansionPanel:

However, with the iOS simulator, it works as expected:

**Additional notes:**
I remember this being an issue ~~(maybe even pre-Flutter 2.0?)~~.
I tried the same thing again on another project today and the same issue occurred again.
However, there was a Flutter version where the grey overlay wasn't there on a real iOS device.
It seems like this bug has existed for quite some time though and I can't remember the last version where the bug wasn't present. It still seems to be a regression.
Web (dartped.dev) also doesn't show a grey overlay. I haven't tested it on Android but I'd assume that it also doesn't show a grey overlay.

<details>
  <summary>Logs</summary>

```console
Analyzing testj...                                                      
No issues found! (ran in 2.0s)
```

```console
[✓] Flutter (Channel beta, 2.5.0-5.3.pre, on macOS 12.0 21A5506j darwin-x64, locale de-DE)
    • Flutter version 2.5.0-5.3.pre at /Users/username/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a7fb06d6fa (3 days ago), 2021-09-02 09:07:14 -0700
    • Engine revision fcde2c8b2f
    • Dart version 2.14.0 (build 2.14.0-377.8.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 13.0, Build version 13A5212g
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • iPhone 12 Pro (mobile) • xxxxxxxx            • ios            • iOS 15.0 19A5340a
    • iPhone 12 Pro Max (mobile)        • xxxxxxxx • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)                   • macos                                • darwin-x64     • macOS 12.0 21A5506j darwin-x64
    • Chrome (web)                      • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/89490

### CODE REVIEW

**Review by Hixie — APPROVED** [review]
Do we need to do this in other places that use elevations? (I worry that this seems like a specific instance of a more general problem.)

LGTM

**Comment by jason-simmons** [comment]
Not sure, but potentially this could affect other calls to canvas.drawShadow with zero elevation.

AFAICT the only other calls to drawShadow in the framework are in https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/slider_theme.dart.

**Comment by Hixie** [comment]
SGTM.

**Comment by TheJulianJES** [comment]
It's unlikely that this will get cherry-picked, right? (Was working fine in 2.3.x stable and regressed in 2.5.0 stable)

**Pull request merged**
