### PR TITLE
Added a null check for ranges in the sourceReport map.

### PR DESCRIPTION
**Pull request by fatherOfLegends**
## Description

I am adding a null checking throughout the functions that build the test coverage map. 

## Related Issues

This is related to https://github.com/flutter/flutter/issues/35907.

## Tests

I have added test cases for all of the null checks and the happy path.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [-] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by lmckenzie** [comment]
I have added tests for my new functionality and back filled coverage for other cases when composing the coverage report.

**Comment by lmckenzie** [comment]
@jonahwilliams I do not believe the failing tests are a result of my PR. What is the best way to proceed?

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
This was reverted since it broke coverage collection from tools: https://cirrus-ci.com/task/4821311406211072

To reproduce locally, try running the tool-coverage shard tests from `dev/bots/test.dart`

**Comment by lmckenzie** [comment]
I am looking into this and it seems reasonable to me to null check before writing the output lcov file. That said I do not understand how to reproduce this locally.

**Comment by jonahwilliams** [comment]
running `dart tool/tool_coverage.dart` from packages/flutter_tools should reproduce the issue

**Comment by lmckenzie** [comment]
@jonahwilliams this is not an issue for my team any longer. We are using https://github.com/2d-inc/Flare-Flutter for animations in our app. When we ran widget tests that included these animations some subsequent test would fail due to missing values in the isolate source report. After using their `FlareTesting.setup();` to avoid isolates in tests this is not an issue for us. I still think this should be improved but I am not sure when I will get to it.

**Pull request merged**
