### PR TITLE
Remove unused `enableObservatory` flag.

### PR DESCRIPTION
**Pull request by matanlurey**
I checked google3 as well and couldn't find any reference.

### CODE REVIEW

**Comment by bkonyi** [comment]
Removing this flag SGTM once this PR is cleaned up.

**Comment by matanlurey** [comment]
> Removing this flag SGTM once this PR is cleaned up.

Yeah woah I wonder what I did here.

**Comment by matanlurey** [comment]
There we go.

**Review by bkonyi — APPROVED** [review]
Much better! LGTM :)

**Pull request merged**
