### PR TITLE
Fix ShaderMask Example issue

### LINKED ISSUE #124323: Documentation with wrong code - Flutter ShaderMask Class
Screenshot_1

This code is not working, the text does not display the gradient, code is wrong.

### PR DESCRIPTION
**Pull request by adityathakurxd**
Fixed the code example for the ShaderMask class to make the text look like it is on fire.
Example that makes the text look like it is on fire

Fixes: #124323

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by piedcipher** [comment]
@adityathakurxd you could tick the last checkbox.

> All existing and new tests are passing.

**Comment by adityathakurxd** [comment]
> @adityathakurxd you could tick the last checkbox.
> 
> > All existing and new tests are passing.

Thank you @piedcipher 🚀

**Review by werainkhatri — APPROVED** [review]
thank you for your contribution!

this will need a second approval, will request for one.

LGTM

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
