### PR TITLE
Use the correct host toolchain when building from a local engine checkout on Mac.

### PR DESCRIPTION
**Pull request by chinmaygarde**
cc @jason-simmons

### CODE REVIEW

**Comment by eseidelGoogle** [comment]
Could you leave a comment about why Mac is special here?

**Comment by jason-simmons** [comment]
lgtm

**Comment by chinmaygarde** [comment]
> Could you leave a comment about why Mac is special here?

The toolchain are just named differently on Mac vs Linux. There is no such inconsistency with the buckets. This is just because we are grabbing stuff directly out of the build directory. Before we have had a chance to homogenize the names and locations.

We could also change the names of the toolchains themselves. But that would involve changing some GN files from Chromium.

**Comment by eseidelGoogle** [comment]
Ok.  If we end up with a bunch of these we'll want to centralize this kind of configuration.  But OK.  This one tiny option is way nicer than the giant pile of paths we hardcoded before :D

**Pull request merged**
