### PR TITLE
fix lint usage of `task` inside `resolve_dependecies.gradle` file

### PR DESCRIPTION
**Pull request by AbdeMohlbi**
according to [Gradle](https://docs.gradle.org/current/userguide/task_configuration_avoidance.htmll) :`As of Gradle 5.1, we recommend that the configuration avoidance APIs be used whenever tasks are created.`
writing-tasks-4
what android studio lint is failing ?
Capture d’écran 2024-11-01 214856

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by stuartmorgan** [comment]
test-exempt: code refactor with no semantic change

**Review by gmackall — APPROVED** [review]

**Comment by reidbaker** [comment]
will review after tests pass.

**Comment by AbdeMohlbi** [comment]
the errors are `OS Error: The process cannot access the file because it is being used by another process.`

**Comment by AbdeMohlbi** [comment]
done

> will review after tests pass.

it's done now

**Review by reidbaker — APPROVED** [review]

**Pull request merged**
