### PR TITLE
Measure CPU/GPU with the simple animation test

### PR DESCRIPTION
**Pull request by liyuqian**
Additionally, I also enabled CPU/GPU measurements for the complex layout
scroll test because the macrobenchmark app is having some troubles in my
local environment although it works fine in the device lab. In case that
the device lab tasks become flaky after this PR, having data on two
tasks would help us rule out where the problem is.

### CODE REVIEW

**Comment by liyuqian** [comment]
@iskakaushik @flar @gaaclarke : I've cleaned up the PR and it's ready for review.

**Review by iskakaushik — APPROVED** [review]
LGTM

**Review by flar — APPROVED** [review]
LGTM

**Comment by flar** [comment]
Just a comment on prior work - would the flag read better as `measureCpuGpu`?

"needs measure" feels odd to me, though I suppose there is a feature called "measureCpuGpu" and this benchmark needs that feature, but since it starts with a verb, "needs [verb]" reads awkwardly...

**Comment by liyuqian** [comment]
> Just a comment on prior work - would the flag read better as `measureCpuGpu`?
> 
> "needs measure" feels odd to me, though I suppose there is a feature called "measureCpuGpu" and this benchmark needs that feature, but since it starts with a verb, "needs [verb]" reads awkwardly...

Sounds good. I'll rename it and track the progress in https://github.com/flutter/flutter/issues/63227.

**Pull request merged**
