### PR TITLE
Semantics fixes

### LINKED ISSUE #31949: Rect is null when TextSpan with GestureDetector inside LayoutBuilder
## Steps to Reproduce

```
class Ex extends StatefulWidget {
  @override
  _ExState createState() => _ExState();
}

class _ExState extends State<Ex> {

  var xxt = TapGestureRecognizer()..onTap = () {
    print("tap tap tap!");
  };
  @override
  Widget build(BuildContext context) {
    List<TextSpan> lts = [TextSpan(style: TextStyle(color: Color(0xff000000), fontSize: 14.0), text: "When Thor's evil brother, Loki (Tom Hiddleston), gains access to the unlimited power of the energy cube called the Tesseract, Nick Fury (Samuel L. Jackson), director of S.H.I.E.L.D., initiates a superhero recruitment effort to defeat the unprecedented threat to Earth. Joining Fury's \"dream team\" are Iron Man (Robert Downey Jr.), Captain America (Chris Evans), the Hulk (Mark Ruffalo), Thor (Chris Hemsworth), the Black Widow (Scarlett Johansson) and Hawkeye (Jeremy Renner)."),
    TextSpan(style: TextStyle(color: Color(0xff2196f3)), recognizer: xxt, text: "https://www.youtube.com/watch?v=hA6hldpSTF8"),];

    return Scaffold(body: RichText(
      text: TextSpan(children: lts),
      maxLines: 3,
    ),);
  }
}
```

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown during a scheduler callback:
flutter: The getter 'left' was called on null.
flutter: Receiver: null
flutter: Tried calling: left
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
flutter: #1      RenderParagraph.assembleSemanticsNode.buildSemanticsConfig (package:flutter/src/rendering/paragraph.dart:495:14)
flutter: #2      RenderParagraph.assembleSemanticsNode (package:flutter/src/rendering/paragraph.dart:518:72)
flutter: #3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3354:13)
flutter: #4      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151:12)
flutter: #5      List.addAll (dart:core/runtime/libgrowable_array.dart:192:13)
flutter: #6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3351:16)
flutter: #7      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151:12)
flutter: #8      List.addAll (dart:core/runtime/libgrowable_array.dart:192:13)
flutter: #9      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3351:16)
flutter: #10     _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151:12)
flutter: #11     List.addAll (dart:core/runtime/libgrowable_array.dart:192:13)
flutter: #12     _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3245:16)
flutter: #13     _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151:12)
flutter: #14     Iterable.single (dart:core/iterable.dart:552:13)
flutter: #15     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2398:7)
flutter: #16     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:951:16)
flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:285:19)
flutter: #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
flutter: #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
flutter: #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #23     _invoke (dart:ui/hooks.dart:154:13)
flutter: #24     _drawFrame (dart:ui/hooks.dart:143:3)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: NoSuchMethodError: The getter 'left' was called on null.
```
## Flutter Doctor

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G4015, locale en-ID)
    • Flutter version 1.2.1 at /Users/richardogvt/Desktop/SDK/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/richardogvt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone 6s • 57564569-552E-4702-B8B1-86B6AE710385 • ios • iOS 10.2 (simulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by dnfield**
## Description

This patch should not be landed before https://github.com/flutter/flutter/pull/34368, and currently has those commits merged in (I'll merge again against master once that one lands).

The rects for a text span may be empty if the text span has been pushed out of view - for example, in a sized box with the height of one line and multiple text spans that span a few lines, where one of the ones out of view also has a gesture recognizer on it.  That triggers NPEs.

I also noticed issues here where we sometimes are passing in infinite values to the node, which we shouldn't be allowing (we never want to draw an infinite rect around something, or allow the a11y node report that it's physically larger by some user defined arbitrarily large/infinite amount).

## Related Issues

Fixes https://github.com/flutter/flutter/issues/31949
Addresses part of https://github.com/flutter/flutter/issues/34433 (I think)

## Tests

I added the following tests:

Test that overflows a secondary text span outside the constraints of a sized box.  Without this patch, that test crashes.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM,

you might need to skip the new test on web

**Comment by dnfield** [comment]
@GaryQian I updated some rects here.  At first I thought it was better but I'm not sure now - it looks off to me.  Maybe we can take a look together tomorrow.

**Comment by GaryQian** [comment]
Regarding the ordering issue, it looks like the bug is in the describeSemanticsConfiguration (line 736) where visitChildren is hitting all the children in a row before adding the text itself.

**Review by GaryQian — APPROVED** [review]
Other than the ordering issue which can be fixed separately, LGTM!

**Pull request merged**
