### PR TITLE
Cleanup flutter config output

### PR DESCRIPTION
**Pull request by mit-mit**
I'd like to propose that we cleanup the `flutter config` help output, by only printing channel notes for options that are limited to a subset of the possible branches.

### Current output

```
Usage: flutter config [arguments]
-h, --help                                      Print this usage information.
    --[no-]analytics                            Enable or disable reporting anonymously tool usage statistics and crash
                                                reports.
    --clear-ios-signing-cert                    Clear the saved development certificate choice used to sign apps for iOS
                                                device deployment.
    --android-sdk                               The Android SDK directory.
    --android-studio-dir                        The Android Studio install directory.
    --build-dir=<out/>                          The relative path to override a projects build directory.
    --[no-]enable-web                           Enable or disable Flutter for web. This setting will take effect on the
                                                master, beta, and stable channels.
    --[no-]enable-linux-desktop                 Enable or disable support for desktop on Linux. This setting will take effect
                                                on the master, beta, and stable channels.
    --[no-]enable-macos-desktop                 Enable or disable support for desktop on macOS. This setting will take effect
                                                on the master, beta, and stable channels.
    --[no-]enable-windows-desktop               Enable or disable support for desktop on Windows. This setting will take
                                                effect on the master, beta, and stable channels.
    --[no-]single-widget-reload-optimization    Enable or disable Hot reload optimization for changes to class body of a
                                                single widget. This setting will take effect on the master and beta channels.
    --[no-]enable-android                       Enable or disable Flutter for Android. This setting will take effect on the
                                                master, beta, and stable channels.
    --[no-]enable-ios                           Enable or disable Flutter for iOS. This setting will take effect on the
                                                master, beta, and stable channels.
    --[no-]enable-fuchsia                       Enable or disable Flutter for Fuchsia. This setting will take effect on the
                                                master channel.
    --[no-]enable-custom-devices                Enable or disable Early support for custom device types. This setting will
                                                take effect on the master, beta, and stable channels.
    --clear-features                            Remove all configured features and restore them to the default values.

Run "flutter help" to see global options.
```
### Update after PR

```
Usage: flutter config [arguments]
-h, --help                                      Print this usage information.
    --[no-]analytics                            Enable or disable reporting anonymously tool usage statistics and crash
                                                reports.
    --clear-ios-signing-cert                    Clear the saved development certificate choice used to sign apps for iOS
                                                device deployment.
    --android-sdk                               The Android SDK directory.
    --android-studio-dir                        The Android Studio install directory.
    --build-dir=<out/>                          The relative path to override a projects build directory.
    --[no-]enable-web                           Enable or disable Flutter for web.
    --[no-]enable-linux-desktop                 Enable or disable support for desktop on Linux.
    --[no-]enable-macos-desktop                 Enable or disable support for desktop on macOS.
    --[no-]enable-windows-desktop               Enable or disable support for desktop on Windows.
    --[no-]single-widget-reload-optimization    Enable or disable Hot reload optimization for changes to class body of a
                                                single widget.
                                                This setting applies to only the master and beta channels.
    --[no-]enable-android                       Enable or disable Flutter for Android.
    --[no-]enable-ios                           Enable or disable Flutter for iOS.
    --[no-]enable-fuchsia                       Enable or disable Flutter for Fuchsia.
                                                This setting applies to only the master channel.
    --[no-]enable-custom-devices                Enable or disable Early support for custom device types.
    --clear-features                            Remove all configured features and restore them to the default values.

Run "flutter help" to see global options.
```

This is a draft PR as I havn't updated tests yet (i'll do that if there is agreement that this change is good).

*List which issues are fixed by this PR. You must list at least one issue.*
No issue.

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*
TBD

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by mit-mit** [comment]
@christopherfujino @Jasguerrero wdyt?

**Comment by christopherfujino** [comment]
SGTM

**Comment by mit-mit** [comment]
@christopherfujino I fixed the test, can you PTAL?

**Comment by eliasyishak** [comment]
@mit-mit you may want to update the branch with the latest changes, there was a test (`SliverReorderableList item has correct semantics`) that has been fixed yesterday

**Comment by mit-mit** [comment]
@eliasyishak done!

**Comment by mit-mit** [comment]
> auto label is removed
oh, I thought this label was "auto merge once approved"

**Review by eliasyishak — APPROVED** [review]
LGTM, you should be able to add back your auto submit label now

**Pull request merged**
