### PR TITLE
[flutter_tools] add more info to coverage script

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Also output covered | total lines, and a summary percentage at the end

### CODE REVIEW

**Comment by christopherfujino** [comment]
Are we even running this?

**Comment by jonahwilliams** [comment]
I run this all the time

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Going to use this to kick the tree since it does not include any changes to running code

**Pull request merged**
