### PR TITLE
Added hoverColor property to CheckboxListTile widget

### LINKED ISSUE #94397: Add "hoverColor" property to CheckBoxListTile and ExpansionTile Widgets
## Use case

"hoverColor" property is implemented for a number of Widgets, but for some reason it has not yet been done for CheckBoxListTile and ExpansionTile which affects Web / Desktop UX.

Interesting, that "hoverColor" already exists in CheckBox Widget.

## Proposal

It's quite easy to add this property by modifying respected Widgets.

For CheckBoxListTile:
add to packages/flutter/lib/src/material/checkbox_list_tile.dart
```dart
  const CheckboxListTile({
    Key? key,
    required this.value,
    required this.onChanged,
    this.activeColor,
    this.checkColor,
    this.tileColor,
    this.title,
    this.subtitle,
    this.isThreeLine = false,
    this.dense,
    this.secondary,
    this.selected = false,
    this.controlAffinity = ListTileControlAffinity.platform,
    this.autofocus = false,
    this.contentPadding,
    this.tristate = false,
    this.shape,
    **this.hoverColor,**
    this.selectedTileColor,
  }) 
```

add property

  /// The color for the tile's [Material] when a pointer is hovering over it.
  **final Color? hoverColor;**       

and add into return method

    return MergeSemantics(
      child: ListTileTheme.merge(
        selectedColor: activeColor ?? Theme.of(context).toggleableActiveColor,
        child: ListTile(
          leading: leading,
          title: title,
          subtitle: subtitle,
          trailing: trailing,
          isThreeLine: isThreeLine,
          dense: dense,
          enabled: onChanged != null,
          onTap: onChanged != null ? _handleValueChange : null,
          selected: selected,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          selectedTileColor: selectedTileColor,
          tileColor: tileColor,
          **hoverColor: hoverColor,**
        ),
      ),
    ); 

ExpansionTile can be extended in the same way

I have created a pull request #91289 for these modification, but, unfortunately have not created test cases (have no experience) and the pull request was closed. Is it necessary to create new tests for such a minor update?.. If no, probably, the PR could be re-opened and merged.

Thanks!

### LINKED ISSUE #99608: [feature] add onFocusChange in ListTile
## Use case
On desktop (or in AndroidTV) when we have `ListTile` in `ListView` and the user navigates the items using `Arrow Down` or `Arrow Up` buttons it would be nice to have `onFocusChange` callback so we can change the state based on focus. 

Currently the same can be achieved by adding a listener to `focusNode` but then we had to manage it and dispose it which is not really nice for 100 list items. 

Also, it's so common for (almost 9 out of 10) flutter apps having `ListTile` in `ListView`. So this will be so convenient.

## Proposal

Current Implementation
```dart
class MyWidget extends StatefulWidget {
  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  final List<FocusNode> _nodes = [];
  final StreamController<int> _activeIndex = StreamController();

  
  @override
  void dispose() {
    for (var n in _nodes) {
      n.dispose();
    }
    super.dispose();
  }
   
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        ListView.builder(
          itemCount: 100,
          itemBuilder: (context, index) {
            var _focusNode = FocusNode();
            _focusNode.addListener(() {
              if (_focusNode.hasFocus) {
                _activeIndex.sink.add(index);
              }
            });
            _nodes.add(_focusNode);
            return ListTile(
               focusNode: _focusNode,
               title: Text("Item $index"),
            );
          },
        ),
        // Do stuff with focused item
      ],
    );
  }
}

```

Proposal 
```dart
class MyWidget extends StatefulWidget {
  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  final StreamController<int> _activeIndex = StreamController();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        ListView.builder(
          itemCount: 100,
          itemBuilder: (context, index) {
            return ListTile(
               onFocusChange: (hasFocus) => hasFocus ? _activeIndex.sink.add(index) : null,
               title: Text("Item $index"),
            );
          },
        ),
        // Do stuff with focused item
      ],
    );
  }
}
```

### PR DESCRIPTION
**Pull request by M97Chahboun**
Fixes #94397

Adds a `hoverColor` property to `CheckboxListTile` widget,

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

I have wrong on second commit message [Added tileColor property on CheckboxListTile widget](https://github.com/flutter/flutter/pull/116026/commits/51a4ef606436d45e91aa00d07bbb1cb385d21cec) I want write hoverColor not tileColor

### CODE REVIEW

**Comment by HansMuller** [comment]
See https://github.com/flutter/flutter/issues/94397#issuecomment-1335966249

**Comment by Hixie** [comment]
@M97Chahboun it looks like some tests are failing and there are some conflicts so I can't just rerun the tests to see if they are old flakes or actual bugs. Would you mind rebasing the patch and repushing?

@HansMuller do the more recent changes look correct?

**Comment by M97Chahboun** [comment]
@Hixie The changes I working on, I think already implemented.

**Comment by Hixie** [comment]
@M97Chahboun looks like one of the checkbox tests is failing (see the `framework_tests-libraries-linux` results). Can you take a look?

**Comment by M97Chahboun** [comment]
Ok I will check it, thanks

**Comment by Hixie** [comment]
@M97Chahboun Thanks for your contributions so far. Is this something you are still interested in working on?

**Comment by M97Chahboun** [comment]
Yes tomorrow I will try to solve tests issue

**Comment by Hixie** [comment]
Great!

**Pull request closed without merging**
