### PR TITLE
[fuchsia] Add explicit sources to a few targets.

### PR DESCRIPTION
**Pull request by pylaligand**

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
We are likely to end up letting these get out of sync because we don't have pre-commit tests for Fuchsia. Is there some way it would make sense for us to test this?

**Comment by pylaligand** [comment]
It turns out we could leave the `sources` parameter empty, and not worry about keeping it in sync. I'll follow up with another CL.

**Comment by pylaligand** [comment]
https://github.com/flutter/flutter/pull/15337

**Pull request merged**
