### PR TITLE
Only register WidgetInspectorService extension in debug builds.

### PR DESCRIPTION
**Pull request by jacob314**
I expect this to cause a couple benchmarks to regress.

### CODE REVIEW

**Review by mraleph — APPROVED** [review]

**Comment by jacob314** [comment]
@mraleph can you take a look at the anomalous behavior now that we've verified the issue still reproduces? It would be nice to rule out that the AOT compiler is actually generating materially different code outside of the WidgetInspector when the code is removed. Likely removing the widget inspector code is just changing when a GC occurs but I don't know a reasonable way to test that hypothesis.

The other possible next step is I can binary search to see how many of the methods in widget inspector can be wrapped in an assert before performance regresses.

**Comment by Hixie** [comment]
Around the time of this PR, `flutter_gallery_ios32__transition_perf` got much more flaky.

**Comment by Hixie** [comment]
Can we revert this patch while @mraleph looks into it? Having a regression like this live makes it much harder to determine what is going on when we have another regression.

**Comment by mraleph** [comment]
Arguably the benchmark is measuring something wrong - the patch removes the code from profile build, so it should not be regressing anything. We already have seen that this benchmark is very finicky, any plans to rewrite it?

**Comment by Hixie** [comment]
@mraleph if there's something wrong with the benchmark, please file a bug describing what's wrong (or submit a PR changing it to measure something more useful). I am not aware of the benchmark having any issues.

@jacob314 thanks!

**Comment by goderbauer** [comment]
I'd also be very intersted in an explanation why the removal of code has such averse effects on a seemingly unrelated benchmark. To reduce flutter's footprint I was gonna look at the dart snapshots next to see if we are shipping anything in release builds that we don't need.

**Comment by jacob314** [comment]
The most likely explanation is the problem benchmark is quite sensitive to when a GC occurs and with the code commented out a GC occurs later and so impacts benchmark timing.
@mraleph can you take a look at the AOT compiler output with and without the commented out line to make sure the generated code does not change in a material way other than not executing the specified method.

**Comment by Hixie** [comment]
What are the absolute numbers for the regression? Is it single-digit milliseconds, or more?

**Comment by Hixie** [comment]
`complex_layout_semantics_perf initialSemanticsTreeCreation` was the benchmark that drove this revert. It was averaging around 80ms with the patch, then went down to about 50ms once it was reverted, with noise in the range of around 20ms min-to-max.

Clearly all these benchmarks are less than ideal. However, they reflect real-world performance. The worst frame on a moto G4 on the complex_layout_scroll_perf benchmark does in fact vary by more than 30ms, and I agree that's bad (the fact that it's in fact _never_ less than 16ms is even more concerning to me). It's affecting users. It would be great if we could make the performance much more stable. If you would like to look at this benchmark, I'm happy to help.

**Comment by mraleph** [comment]
I have managed to reproduce slow runs (though only on 1ad9f0125 - was not able to reproduce the same thing by applying it on top of `master`). I can confirm that this a GC issue: slow runs have old-space garbage collection during semantics construction, fast runs don't:

Slow:

nrtuudu9z4d

Fast:

qm0ijzntiqy

I think given this discovery the change in question should be simply relanded - benchmark is sensitive to GC and of course allocating something during initialization changes GC timings. 

Maybe it makes sense to dig into why _exactly_ this change changes GC timing, but in the grand scheme of things it is an orthogonal investigation. /cc @rmacnak-google

**Comment by goderbauer** [comment]
Thanks for looking at it.

Are there ways to make the benchmark more resilient to GC? Back when I was benchmarking things on the web we would usually force a GC before a benchmark run to decrease the chances of it hitting during the benchmark run. While somewhat artificial that gave us a cleaner signal to detect regressions. Can we do something like that from Flutter as well?

**Comment by jacob314** [comment]
@Hixie 
To clarify, my CL is putting code in an assert that was not previously in an assert that should have always been in an assert as it is not useful outside of debug mode. So it is not surprising that removing the code reduces memory usage a little and so changed GC timing slightly. So I don't think removing the code instead of putting it an assert needs to be tested.

**Comment by Hixie** [comment]
@jacob314 adding the code in the first place didn't change GC timing either, though, right?
As in, we went from no code -> code -> code-in-assert, and the regression only appeared at the last step.

**Comment by jacob314** [comment]
The majority of the code that I put in the assert was added in 2017. I would expect GC timing for running a flutter app has changed significantly since then.

**Pull request merged**
