### PR TITLE
Simplification of build_runner integration

### PR DESCRIPTION
**Pull request by jonahwilliams**
## Description

Currently build_runner is integrated by wrapping the kernel and resident compilers, proxying the underlying calls and applying some existing configuration to support a multiroot scheme. This is fairly complex, and the only benefit is supporting build_to: cache, which isn't widely used since the generated code is hard to discover.

By removing this functionality, we can simplify the integration to a hook that verifies that all builds are up to date before running.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
cc @yjbanov and @jakemac53 for thoughts. Supporting the multiroot-scheme necessary for build to cache adds a decent amount of complexity, and anticipating the changes to .packages/package_config.json I'm looking for solutions to simplify it.

Besides inject.dart (which we can updated), I haven't found usage of build to cache besides angular dart.

**Comment by jakemac53** [comment]
I think most of the code generation use cases for flutter are probably compatible with `build_to: source`. It mostly comes down to dart source code generation in the current package (and not other packages).

I agree that things that require transitive codegen (ie: inject) are less common. I don't know how much it matters or not to support things like that. It is possible that inject could also migrate to a build to source approach (but it would mean shipping generated files on pub).

Another option here could be running flutter inside of the build output directory (and building with -o <some-output-dir>).

**Comment by jonahwilliams** [comment]
I'm not sure that the choice to build to cache for inject is intentional in this case. I think the issue with the output dir is whether or not we can get away with symlinks, IIRC they still don't work great on windows.

**Comment by jakemac53** [comment]
Fwiw the symlinks on windows have been improved so that we can actually use them, but they require users to put their OS in "developer mode" which may not be possible based on different corporate security policies.

**Comment by jonahwilliams** [comment]
@yjbanov friendly ping

**Comment by yjbanov** [comment]
Going with the simpler solution (single-root scheme) SGTM. We can revisit if there's strong demand for multi-root scheme. `package:inject` should not be affected by this because it does not change API from release to release by virtue of _not having an API_ in the first place :)

**Comment by goderbauer** [comment]
Is this PR still relevant or should we close it?

**Comment by jonahwilliams** [comment]
Closing to remove from review queue

**Pull request closed without merging**
