### PR TITLE
[ios] reduce xcode version requirement to 7.0

### PR DESCRIPTION
**Pull request by yjbanov**
Build bots only have 7.0.

### CODE REVIEW

**Comment by devoncarew** [comment]
I think simctl doesn't support the --json flag on < 7.2. That's how we get the list of simulator devices. We used to regex parse the regular user output before - a little more fragile, but functional.

**Comment by devoncarew** [comment]
We could still drop down to 7.0, we'd just have to be aware that some things won't work as well.

**Comment by eseidelGoogle** [comment]
Seems like we could just ask infra to update the bots. :D @riannucci

**Comment by chinmaygarde** [comment]
lgtm if you're convinced Xcode 7 supports what we need :)

**Comment by yjbanov** [comment]
I'll roll back if it doesn't work.

**Pull request merged**
