### PR TITLE
[proposal] Make timeline benchmarks self-driving.

### PR DESCRIPTION
**Pull request by sortie**
## Description

***Note: This is just a proposal to allow discussion. It is not intended for final code review. This change is a rough prototype.***

This change makes the timeline benchmarks self-driving. Instead of having flutter drive connect to the benchmarks' observatory to drive the benchmarks, the benchmarks now drive themselves by connecting to their own observatory and writing the benchmark results to the log.

The rationale is to decouple the timeline benchmarks from the flutter infrastructure, which enables benchmarking Flutter at scale. It means the host machine starting the benchmark and collecting results does not need to have Flutter installed nor any of Flutter's dependencies. Instead the benchmarks can be built in the cloud and the host machine simply need to install e.g. an apk for Android and launch it, and then listen on the phone's log for the benchmark results. Otherwise the overhead can be considerable to set up Flutter, building the benchmark, waiting for gradle to start, etc. This design means the host machine and phone needs to do nothing but run benchmarks, a design that currently means I can run Flutter microbenchmarks with 51% phone utilization with the remainder spent on downloading APKs, installing them, and cleaning up afterwards. I'm hoping this will let me do that as well for the timeline benchmarks.

The microbenchmarks already uses the self-driving scheme and this change extends it to the timeline benchmarks as well.

The self-driving benchmarks are accomplished using the new FlutterSelfDriver class that has been designed to minimize differences in the source code when porting benchmarks. The differences are generally minor such as using the real Finder class. There's a lot in common between the FlutterDriver class and FlutterSelfDriver, it might be possible and reasonable to unify them with a common base class. This prototype simply duplicates the code until a better design is found. Not every feature in FlutterDriver is currently implemented in FlutterSelfDriver.

The self-driving benchmarks are currently checked in as foo_test.dart rather than foo.dart in order to allow comparison and discussion, as that was where most of the logic was. It is the intention to simply name them foo.dart in the end.

The self-driving benchmarks do not currently exit upon completion. They could gain the ability to do so, or the host machine could stop them after receiving the results via the device log.

The results logging mechanism is not fully implemented yet. The frame_build_times and frame_rasterizer_times keys are currently removed from the logged results because they cause the android log lines to become too long and are not used by the benchmarks.

The self-driving benchmarks currently does not integrate with 'flutter drive'. That would be a good next step towards avoiding duplicating the benchmarks.

## Related Issues

None that I know of.

## Tests

These changes are all tests.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by liyuqian** [comment]
Thank you @sortie very much! This is seems to be a very promising solution to https://github.com/flutter/flutter/issues/38329 . It's not only helpful to our test infrastructure, but also useful for unblocking our stage-3 solution of eliminating shader compilation jank (https://github.com/flutter/flutter/issues/32170#issuecomment-524397047).

I wonder if the following can be achieved (if not, why?):

1. Make `flutter_self_driver.dart` and `flutter_driver.dart` share the exact same API. So to use the self-driven tests, simply swap `import 'package:flutter_driver/flutter_driver.dart';` with `import 'package:flutter_driver/flutter_self_driver.dart';`. It also allows us to easily replace the old host driver with the new self driver by simply `mv flutter_self_driver.dart flutter_driver.dart` without any additional code change.

2. Write the result in a json file locally on the device instead of writing the result to `adb logcat`. It would (1) maximize the compatibility with the old driver tests which always generates a json file on the host; (2) enable full timeline logging and easy parsing; (3) Allow iOS to use the same approach; (4) For flutter command line tools, all it needs to add is to pull the json file from the client to the host, and all other steps remain identical; (5) For cloud-based CI tests, we can write some simple client code to send that json file to some server.

**Comment by collinjackson** [comment]
If we're planning to modify the driver tests to use `FlutterSelfDriver`, I'm wondering if we should update them to use the `WidgetTester` API instead. Any missing functionality of `FlutterSelfDriver` that is needed for benchmarks that isn't already present (e.g. `forceGC`) could be added to `WidgetTester`. This would reduce our dependency on `FlutterDriver` and unify self-driving testing between testing and benchmarks.

Here is an example a self-driving test that uses the `WidgetTester` API in the flutter_test package:

https://github.com/flutter/plugins/blob/master/packages/e2e/example/test_driver/example_e2e.dart

The main thing that made this hard in the past was that it was hard to exit on completion using compatible with `LiveTestWidgetsFlutterBinding()`. This limitation is no longer an issue in `E2EWidgetsFlutterBinding()`.

**Comment by collinjackson** [comment]
We spoke offline about this. I'm trying to imagine what self-driving benchmarks would look like if we weren't wedded to the current `FlutterDriver` API.

`FlutterSelfDriver` is providing two classes of functionality that are useful for benchmarks:

### Flutter widget synchronization APIs

Rather than performing actions immediately, the tester waits for a finder to match and also ensures that no pending frames are scheduled. There are several options for offering this functionality to developers:
- **Synchronous with manual wait.** If we added a `waitFor` API to `WidgetTester`, developers could manually distinguish immediate tap `tester.tap(find.byType(MaterialButton))` from synchronized tap `tester.tap(await tester.waitFor(find.byType(MaterialButton)))` 
    - Helpers like `waitAndTap` could make code more readable but might clutter up the API.
    - Adds some cognitive load when writing tests because _sometimes_ you don't need the `waitFor`, and could lead to flakes if the test performs an action while the app under test is undergoing a transition.
- **Synchronized with escape hatch.** A subclass of `WidgetTester` for live testing could default to synchronized actions but have an escape hatch allowing immediate actions (as you're doing here with `runUnsynchronized`). Now developers can write more terse tests: `tester.tap(find.byType(MaterialButton))` and they don't have to worry about pumping frames.
- **Boolean toggle.** There could be an `enableSynchronization` and `disableSynchronization` API on `WidgetTester` (or some subclass thereof) that switches between the two modes above. I think this is how [Detox](https://medium.com/async-la/e2e-testing-react-native-with-detox-screenshots-595146073863) works, with the default being synchronized.

### Dart performance benchmarking APIs

The following methods connect to the observatory service APIs provided in `dart:developer`:
- `startTracing`
- `traceAction`
- `clearTimeline`
- `stopTracingAndDownloadTimeline`
- `forceGC`

These are a subset of the functionality offered in the FlutterDriver API but they aren't really specific to Flutter (it seems like non-Flutter benchmarks would find them useful). It feels to me that they could be moved into a separate pure Dart package.

/cc @adazh who has also been looking at synchronization

**Comment by goderbauer** [comment]
I am closing this PR since it is just a proposal.

**Pull request closed without merging**
