### PR TITLE
Roll engine 2d42c74a348d..d7ad50c96f05 (54 commits)

### PR DESCRIPTION
**Pull request by gaaclarke**
Revival of roll: #53178

flutter/engine@2d42c74...d7ad50c

git log 2d42c74a348d..d7ad50c96f05 --first-parent --oneline
d7ad50c96 Roll src/third_party/skia c97c90072499..6cb8168c2b9b (1 commits) (#17287)
704a869e0 Roll src/third_party/dart cbd67124d10e..8246621d4da3 (39 commits) (#17286)
33895cf6b Roll src/third_party/skia d1988219065a..c97c90072499 (2 commits) (#17285)
48d116562 Roll fuchsia/sdk/core/linux-amd64 from h8m0G... to y2Piw... (#17283)
0015b1954 Roll fuchsia/sdk/core/mac-amd64 from WaNBa... to gkIC0... (#17282)
518c9e09c Remove checks for the always true using_fuchsia_sdk flag in all GN files. (#17261)
1eea062c9 Roll src/third_party/skia 3c358420df4a..d1988219065a (3 commits) (#17279)
ad8ccf47b [Fuchsia] Move physical shape layer compositing to Flutter (#17005)
c490cb9be Roll src/third_party/skia 165b68ebb6ad..3c358420df4a (5 commits) (#17277)
4c41b1406 [web] Introduce js interop to enable experimental flags on web (#17099)
21f5d7f3c Roll src/third_party/skia 4098719375d8..165b68ebb6ad (7 commits) (#17274)
6fef0d0a0 Removed a text input trait that causes VoiceOver to be incorrect when tapping a text input. (#17203)
9343c5ed2 added missing mock to MockEngine for iOS unit tests (#17273)
af056a8de Roll src/third_party/skia 6f60a859c628..4098719375d8 (6 commits) (#17271)
33a21d1ff Add DartProject for Windows embedding API (#17210)
8a8b29840 Added a log message when sharing a FlutterEngine across multiple FlutterViewControllers. (#17186)
11f552187 Roll src/third_party/skia f04f21a5c913..6f60a859c628 (2 commits) (#17268)
da9e7788a Roll fuchsia/sdk/core/linux-amd64 from k4zbT... to h8m0G... (#17264)
c86a4ccd0 Roll fuchsia/sdk/core/mac-amd64 from bgp6U... to WaNBa... (#17263)
35e830363 Roll src/third_party/skia 538e358b0d82..f04f21a5c913 (2 commits) (#17260)
e56b335ad Allow external texture sources when using the Metal backend. (#17154)
c0deb2361 Don’t depend on an implicit transaction when no external view embedder is present. (#17258)
80846b0d6 Roll src/third_party/dart b7455646f90d..cbd67124d10e (3 commits) (#17257)
9c6402975 Documentation cleanups to RuntimeController. (#17256)
209e78650 Roll fuchsia/sdk/core/linux-amd64 from kGu6P... to k4zbT... (#17255)
aa2610635 Roll fuchsia/sdk/core/mac-amd64 from nmCXC... to bgp6U... (#17254)
eec744726 Roll src/third_party/dart bdf14543576a..b7455646f90d (1 commits) (#17253)
ba26ce3a0 Roll src/third_party/dart 861708483217..bdf14543576a (5 commits) (#17252)
c9a24af2e Roll src/third_party/skia cf3594b60362..538e358b0d82 (4 commits) (#17251)
59406cc7e Roll src/third_party/skia e41fa2d5e44d..cf3594b60362 (1 commits) (#17249)
7d21f9700 Roll src/third_party/dart f247613737ec..861708483217 (1 commits) (#17248)
db02fa195 Roll fuchsia/sdk/core/linux-amd64 from pTJOm... to kGu6P... (#17247)
f5314eaee Roll fuchsia/sdk/core/mac-amd64 from uyg4y... to nmCXC... (#17246)
31c47278b Document flutter::RuntimeController. (#17250)
7b9a67832 Roll src/third_party/dart 82f8a5451fae..f247613737ec (3 commits) (#17245)
3dd688c5f Roll src/third_party/dart ba8baa46b452..82f8a5451fae (40 commits) (#17244)
cafa097f9 Revert "Roll src/third_party/dart ba8baa46b452..fbd0c8a46813 (35 commits) (#17241)" (#17243)
2f769be66 Soften shadows (#17231)
48902d146 Felt add integration (#17190)
047c03bf5 Roll src/third_party/dart ba8baa46b452..fbd0c8a46813 (35 commits) (#17241)
f5d25da83 Reland: Implement unobstructed Platform Views on iOS (#17237)
d79170f08 Roll src/third_party/skia 933926683991..e41fa2d5e44d (2 commits) (#17240)
46cc35fac Roll fuchsia/sdk/core/mac-amd64 from MKYwg... to uyg4y... (#17234)
060cbc448 Revert "Roll src/third_party/dart ba8baa46b452..0296286c03f6 (11 commits) (#17226)" (#17239)
1152709f7 Roll fuchsia/sdk/core/linux-amd64 from ZmlfS... to pTJOm... (#17235)
47ae84beb Run web framework tests on third-party rolls (#17238)
e2ec94b84 Roll src/third_party/skia 7b7b78cb9f1b..933926683991 (6 commits) (#17232)
f58967fbd Re-land "Enable unified OpenGL/Metal builds." (#17230)
70f6d18bf Revert "Implement unobstructed Platform Views on iOS (#17049)" (#17233)
bba1a3cca Roll buildroot to a0fb98af (#17229)
2627634be Implement unobstructed Platform Views on iOS (#17049)
49f8dba82 Sync Cirrus web test config from flutter/flutter (#17228)
fdf4f7883 Roll src/third_party/skia 85755f46a881..7b7b78cb9f1b (6 commits) (#17227)
6c757f3bb Roll src/third_party/dart ba8baa46b452..0296286c03f6 (11 commits) (#17226)

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 1.
Please triage them at https://flutter-gold.skia.org/search?issue=53200.

**Comment by skia-gold** [comment]
Gold has detected one or more untriaged digests on patchset 1.
Please triage them at https://flutter-gold.skia.org/search?issue=53200.

**Comment by gaaclarke** [comment]
@yjbanov can you verify the shadow change, looks like it's a result of https://github.com/flutter/engine/commit/2f769be66344df0891120b5cd25b91ba30a37f3e.  I'm going to say it's good and have it reviewed after the fact since the roll is overdue.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by yjbanov** [comment]
> @yjbanov can you verify the shadow change, looks like it's a result of [flutter/engine@2f769be](https://github.com/flutter/engine/commit/2f769be66344df0891120b5cd25b91ba30a37f3e). I'm going to say it's good and have it reviewed after the fact since the roll is overdue.

LGTM

**Comment by gaaclarke** [comment]
@yjbanov here is the diff that was of interest: https://flutter-gold.skia.org/detail?test=widgets.shadow.PhysicalModel.enabled&digest=55e59bfecf57a0abb4cb1129f823fa85

**Comment by yjbanov** [comment]
LGTM

**Pull request merged**
