### PR TITLE
[Widget] RangeSlider active section support on tap

### PR DESCRIPTION
**Pull request by DetectiveAI4869**
## Description

**Issue**

Currently RangeSlider just responds to tap on inactive range.
* before start thumb
* after end thumb

**Fix**

Make RangeSlider responds to tap on active range.
* between start thumb and end thumb
* find closest thumb

Also code analysis issues
* camelCase variable name
* if statements block in {}

**Reference**

https://material.io/develop/android/components/sliders
com.google.android.material.slider.RangeSlider **support**
https://api.flutter.dev/flutter/material/RangeSlider-class.html not **support**

## Related Issues

*Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR. There should be at least one issue listed here.*

## Tests

I added the following tests:

Reuse Widget Tests

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by includecmath** [comment]
Hi @AnthonyMansour I see you are familiar with RangeSlider widget can you help me review.

**Comment by clocksmith** [comment]
Thanks for this contribution!

Since there are 2 separate issues here (1. code style, 2. range slider selection behavior), please create a separate PR for the style change issue.

For the 2nd issue, the current behavior of no selection when tapping on a space between the thumbs is the intentional material behavior. However, it can be changed via the `thumbSelector` param in the `SliderTheme`. Rather than changing this default behavior, I think it would be better to provide an example in the documentation on how to create the desired selection behavior (being able to tap anywhere and always getting a selection). That behavior is described here: https://medium.com/flutter/material-range-slider-in-flutter-a285c6e3447d in the "Custom Touch Input Selection" section. So the second change would be an example in the documentation using that code.

**Comment by includecmath** [comment]
> Thanks for this contribution!
> 
> Since there are 2 separate issues here (1. code style, 2. range slider selection behavior), please create a separate PR for the style change issue.
> 
> For the 2nd issue, the current behavior of no selection when tapping on a space between the thumbs is the intentional material behavior. However, it can be changed via the `thumbSelector` param in the `SliderTheme`. Rather than changing this default behavior, I think it would be better to provide an example in the documentation on how to create the desired selection behavior (being able to tap anywhere and always getting a selection). That behavior is described here: https://medium.com/flutter/material-range-slider-in-flutter-a285c6e3447d in the "Custom Touch Input Selection" section. So the second change would be an example in the documentation using that code.

Are you sure it's intentional material behavior?
Android Material(com.google.android.material.slider.RangeSlider) support default.
It’s weird that the active range cannot be clicked in any UI components library.

**Comment by Piinks** [comment]
I am going to close this per the comment above (https://github.com/flutter/flutter/pull/68288#issuecomment-715535666) to split this into a single change per issue. Thanks for the contribution!

**Pull request closed without merging**
