### PR TITLE
Add flutter assets

### PR DESCRIPTION
**Pull request by excitedhaha**
## Description
Fix the problem that no flutter assets merged to the apk.

## Related Issues

[38286](https://github.com/flutter/flutter/issues/38286)

## Tests

Tested in my project

### CODE REVIEW

**Comment by excitedhaha** [comment]
@googlebot I signed it!

**Review by dnfield — CHANGES_REQUESTED** [review]
@blasten will probably have much better feedback here, but this breaks some existing tests and doesn't add any new ones to cover this case. We won't be able to merge this PR without addressing those issues.

**Comment by blasten** [comment]
For reference, this is being discussed on https://github.com/flutter/flutter/issues/38286

**Comment by zanderso** [comment]
As discussed here and on the issue, this PR needs work on tests. @excitedhaha are you interested in continuing with this PR?

**Comment by excitedhaha** [comment]
@zanderso ok, I will try to give the exact steps that reproduce the issue

**Comment by blasten** [comment]
This issue was fixed via https://github.com/flutter/flutter/pull/41333. If you still see this issue, feel free to comment on the PR or the issue.

**Pull request closed without merging**
