### PR TITLE
[PageTransitionsBuilder] Reland Fix 'ZoomPageTransition' built more than once

### PR DESCRIPTION
**Pull request by shihaohong**
## Description

This has been unblocked internally via cl/318079801. b/159779895 was added to track fixing the tests that were originally preventing https://github.com/flutter/flutter/pull/58686 from landing.

cc/ @AlexVincent525 

## Issues

Fixes https://github.com/flutter/flutter/pull/58686
Reverts flutter/flutter#59992

### CODE REVIEW

**Review by renyou — APPROVED** [review]
LGTM

**Comment by flutter-github-sync** [comment]
Started Google testing for this PR

**Comment by shihaohong** [comment]
@renyou Unrelated to the PR itself, but does/should the `waiting for tree to go green` label account for Google testing for the PR? I was thinking of the case where this PR merges before we get a result from Google testing.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by renyou** [comment]
Don't think so. Still working on it.

**Comment by flutter-github-sync** [comment]
Google testing passed!

**Pull request merged**
