### PR TITLE
Changed ThemeData DiagnosticProperties to DiagnosticLevel.debug

### LINKED ISSUE #27478: ThemeData.toString() is way too verbose
We need to mark most of ThemeData's diagnostics as hidden by default, and we should add a test that verifies that no lines in the output of the default app are longer than a hundred or two hundred characters.

cc @gspencergoog @jacob314 @justinmc

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This is a similar change to replace the languishing PR https://github.com/flutter/flutter/pull/39617 by @amrfarid140 so that we can commit a fix. Thanks for helping us, Amr!

## Related Issues

- Fixes https://github.com/flutter/flutter/issues/27478

## Tests

- Adds a test to make sure that `toString` output of a `ThemeData` is less than 200 characters.

## Breaking Change

- [X] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by gspencergoog** [comment]
@jacob314 We went with `hidden` instead of `debug`, because although `debug` more closely represents when we'd like to show it, calling `toString` on it still produces strings that are too long, since it includes debug-level output.

**Comment by amrfarid140** [comment]
Thanks @gspencergoog for picking it up. Sorry, I didn't have much time to complete the original PR.

**Comment by gspencergoog** [comment]
@amrfarid140 No worries, it was helpful to be able to start with your PR.

**Comment by jacob314** [comment]
There was a bug. debug properties were not supposed to be included in toString but they were for one of the diagnostics classes. Sending out a fix now.
https://github.com/flutter/flutter/issues/50644

**Comment by gspencergoog** [comment]
Ahh, OK, I'll wait for your fix to land.

**Review by jacob314 — COMMENTED** [review]
Please change this to 
`DiagnosticLevel.debug`
I have sent out a PR to fix the bug that meant you had to use `DiagnosticsLevel.hidden`
https://github.com/flutter/flutter/pull/50645

**Comment by gspencergoog** [comment]
OK, done.  The test will fail until your PR lands, of course.

**Review by jacob314 — COMMENTED** [review]
lgtm

**Comment by jacob314** [comment]
lgtm

**Comment by gspencergoog** [comment]
@jacob314 LGTM is good enough for our process, but not good enough for GitHub, it wants a GitHub approval.

**Review by jacob314 — APPROVED** [review]

**Pull request merged**
