### PR TITLE
Create `takeExceptionDetails` which is similar to `takeException` but allows the user to know details (e.g. stack trace)

### LINKED ISSUE #103487: (PR made) Create `takeExceptionDetails` which is similar to `takeException` but allows the user to know details (e.g. stack trace)
## Use case

Currently, users can `takeException` to get the most recent exception. However, they can only see the `Exception`, but lose all details like stack trace, which is very useful when debugging as we all know. Therefore, this simple PR adds that information.

## Proposal

see above

### PR DESCRIPTION
**Pull request by fzyzcjy**
Please see https://github.com/flutter/flutter/issues/103487

Close #103487

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by fzyzcjy** [comment]
all tests passed.

image

**Comment by goderbauer** [comment]
What's the use case for needing that? What can you test now that you weren't able to test before?

**Comment by fzyzcjy** [comment]
> What's the use case for needing that? What can you test now that you weren't able to test before?

Not to test indeed, but to inform. Firstly, in https://github.com/fzyzcjy/flutter_convenient_test readme, there is a 1-minute video demonstrating how this open source lib looks like. Then you see this lib shows errors etc in the command panel in an intuitive way for the programmers. When talking about "errors", surely we want to show stack traces as well, but currently for errors like golden mismatch I have to use takeException and stacktrace is lost.

Where this lib needs it: https://github.com/fzyzcjy/flutter_convenient_test/blob/f9d38c9fd870a5dab5a61755f66214b29caadf2f/packages/convenient_test_dev/lib/src/functions/command.dart#L99

**Comment by fzyzcjy** [comment]
👀

**Comment by goderbauer** [comment]
It is a little odd to expose that here and may lead to confusion in the API. Have you considered just overwriting `FlutterError.onError` in your framework yourself to catch the error directly?

**Comment by fzyzcjy** [comment]
Well I hope to reuse the logic about errors in testing...

**Comment by fzyzcjy** [comment]
@Piinks Hi that does not suit. Btw `FlutterError.onError` cannot be rewritten outside a `widgetTest` since widgetTest overrides it again.

**Comment by fzyzcjy** [comment]
> even use setUp to override it for a group of tests.

That seems not possible, surprisingly. Because FlutterError.onError is overrided in `TestWidgetsFlutterBinding._runTest`, which seems to be run after all setup?

**Comment by fzyzcjy** [comment]
Yes, so it is not very convenient as we cannot do it in setup

**Comment by goderbauer** [comment]
We need to come up with another solution for this that doesn't require adding confusing API. This will need some more thinking. I suggest you describe what you want to achieve in an issue without proposing a concrete solution just yet.

**Pull request closed without merging**
