### PR TITLE
Use Mountain View/Cupertino terms in drawer on iOS

### PR DESCRIPTION
**Pull request by cbracken**
Use our platform identifiers rather than OS names for the platform
switcher radio buttons in the drawer as noted in section 2.3.10 of the
App Store review guidelines.

See: https://developer.apple.com/app-store/review/guidelines/

### CODE REVIEW

**Comment by cbracken** [comment]
Fixes #12637

**Comment by Hixie** [comment]
We should only do this when the actual platform is actually iOS.
On Android we should just say "iPhone" and "Android" and use the real icons.

**Comment by Hixie** [comment]
(check how we do this for the icons)

**Comment by cbracken** [comment]
SGTM - will update the patch.

**Comment by cbracken** [comment]
Updated.

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
