### PR TITLE
Reland "migrate part of painting to nullsafety (#62696)"

### PR DESCRIPTION
**Pull request by goderbauer**
Broke with https://github.com/flutter/flutter/pull/62696.

### CODE REVIEW

**Comment by a14n** [comment]
Won't the fix work only with #62696?

**Comment by a14n** [comment]
I mean: as #62696 has been reverted the line will still be 225 in master

**Comment by goderbauer** [comment]
The revert hasn't been submitted yet, still waiting for CI to finish. If the revert submits before this, we will need to merge #62696 back into this commit.

**Review by a14n — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
#62696 is merged.

**Comment by goderbauer** [comment]
@a14n PTAL, updated to revert the revert as well.

**Review by a14n — APPROVED** [review]
LGTM

**Pull request merged**
