### PR TITLE
[tool][web] Pass invoker flag to dart2js.

### PR DESCRIPTION
**Pull request by sigmundch**
Dart2js currently produces a warning message if it is invoked from its snapshot and not from the `dart compile js` command.

We plan to make it an error to invoke the snapshot directly, potentially in the Dart 3 timeframe.

There are two mechanisms available to avoid this error:
* use `dart compile js` to invoke dart2js instead of the dart2js snapshot
* use the `--invoker` flag to indicate to dart2js that the invocation is from a supported context. 

This CL takes the latter approach, which is the same approach used for the dart-cli and our internal build systems using bazel. Long term Flutter may prefer to start using `dart compile js`, but that would require a more careful validation.

For context see: https://github.com/dart-lang/sdk/issues/51695 and https://github.com/dart-lang/sdk/issues/46100

### CODE REVIEW

**Comment by sigmundch** [comment]
@christopherfujino - I have a limited setup for this repo, so I don't have a full validation that this is working as expected. Will the tests cover this codepath directly? If not, would you be available to help me validate that this works as expected?

The only observable difference today should be that you no longer see a warning message. In particular, today you see this when doing a flutter web build like `flutter build -d chrome`:
```
Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
```

**Comment by christopherfujino** [comment]
> @christopherfujino - I have a limited setup for this repo, so I don't have a full validation that this is working as expected. Will the tests cover this codepath directly? If not, would you be available to help me validate that this works as expected?
> 
> The only observable difference today should be that you no longer see a warning message. In particular, today you see this when doing a flutter web build like `flutter build -d chrome`:
> 
> ```
> Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
> ```

Looks like your failing presubmits are unit tests. I will manually verify the change tomorrow morning.

**Comment by sigmundch** [comment]
> Looks like your failing presubmits are unit tests. I will manually verify the change tomorrow morning.

It makes me happy when a test catches changes, even if minor :smile: I just uploaded test expectation changes. The updates don't validate what's the stdout of the underlying dart2js command, only that the command and test expectations are the same.

**Comment by christopherfujino** [comment]
> > Looks like your failing presubmits are unit tests. I will manually verify the change tomorrow morning.
> 
> It makes me happy when a test catches changes, even if minor smile I just uploaded test expectation changes. The updates don't validate what's the stdout of the underlying dart2js command, only that the command and test expectations are the same.

yep, they're not perfect, but better than nothing. so I'm actually trying to reproduce the warning message at HEAD (i.e. not on this branch) but I can't. Investigating futher...

**Comment by christopherfujino** [comment]
So on the Flutter master channel, I executed:

`flutter clean && flutter build web -v`

And I see this in the verbose logs:

```
[        ] dart2js: Starting due to {}
[   +3 ms] compiling dart code to kernel with command "/home/fujino/git/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev /home/fujino/git/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot
--platform-binaries=/home/fujino/git/flutter/bin/cache/flutter_web_sdk/kernel --native-null-assertions
-Ddart.vm.product=true -DFLUTTER_WEB_AUTO_DETECT=true --no-source-maps -o
/home/fujino/git/tmp/delete_me_flutter_box/.dart_tool/flutter_build/7c3cfbbc5a70aaa52eae27367273afb0/app.dill
--packages=.dart_tool/package_config.json --cfe-only
/home/fujino/git/tmp/delete_me_flutter_box/.dart_tool/flutter_build/7c3cfbbc5a70aaa52eae27367273afb0/main.dart"
[+3132 ms] dart2js: Complete
```

@sigmundch Shouldn't I have seen the warning about dart2js being deprecated? I know I've seen this warning before...

**Comment by sigmundch** [comment]
I see it often in bug reports. I wonder if it is only shown on stderr and is potentially hidden unless the tool crashes or returns an error? Do you see it by chance if you try to compile a program with a syntax error?

See for example: https://github.com/dart-lang/sdk/issues/51658

**Comment by sigmundch** [comment]
never mind - the error is printed to stdout when I run dart2js locally. Do you see the error if you simply copy/paste the command that is shown and run it directly outside the flutter tool?

**Comment by christopherfujino** [comment]
> never mind - the error is printed to stdout when I run dart2js locally. Do you see the error if you simply copy/paste the command that is shown and run it directly outside the flutter tool?

Hmm, yeah, when I run this compile command directly in my terminal I see the warning, let me dig more into where it goes...

**Comment by christopherfujino** [comment]
> > never mind - the error is printed to stdout when I run dart2js locally. Do you see the error if you simply copy/paste the command that is shown and run it directly outside the flutter tool?
> 
> Hmm, yeah, when I run this compile command directly in my terminal I see the warning, let me dig more into where it goes...

Ahh, ok, we only show that output if there is a compiler error. I can verify this change works, let me add an integration test that fails compilation and verifies we don't see the warning.

**Comment by sigmundch** [comment]
Awesome, thank you!

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
Pushed an update to an existing integration test and added the `autosubmit` label, provided presubmits all pass, a bot should merge this. Thanks @sigmundch

**Comment by sigmundch** [comment]
Fantastic, thank you so much @christopherfujino!

**Pull request merged**
