### PR TITLE
Roll engine 7e3b41dc7ba6..74e68ff8b108 and update tests

### PR DESCRIPTION
**Pull request by GaryQian**
git log 7e3b41dc7ba6..74e68ff8b108 --no-merges --oneline
74e68ff8b Roll src/third_party/skia 7b7805581733..66a973493468 (4 commits) (#6436)
58fbd1fd1 Roll src/third_party/skia 4442e3138927..7b7805581733 (1 commits) (#6435)
83151d9fc Roll src/third_party/skia 4dd17156c6e4..4442e3138927 (1 commits) (#6434)
5fe7e377d Roll src/third_party/skia 8841085abeb9..4dd17156c6e4 (1 commits) (#6432)
5340f4224 Revert "Use single_root_scheme when compiling platform (#6402)" (#6431)
37fd43d43 Add deadline_now_delta argument to Engine::NotifyIdle's trace (#6419)
4af077b29 Roll src/third_party/skia 4504a652c071..8841085abeb9 (1 commits) (#6429)
165f3dd1c Update //third_party/benchmark dependency to 21f1eb (ToT). (#6427)
34bd0ef87 Don’t build benchmarking binaries on Windows. (#6428)
ae4db4469 Ensure setViewIdResourceName has the correct version guard (#6404)
2c5d0c407 [rapidjson] Fix import statements (#6418)
c2128fc80 Create a benchmarking target for the shell. (#6420)
30f78af91 Raise errors on non-zero exits while creating artifacts on the bots. (#6424)
191168cec Disable line_height tests on Windows (#6423)
061cc6643 Fix ideographic baseline to match spec. (#6422)
74eac1f56 Roll src/third_party/skia bfa76f20bfcf..4504a652c071 (14 commits) (#6421)
10b45405b Implement ParagraphStyle.line_height and add tests for line_height and baselines. (#6417)

### CODE REVIEW

**Comment by dnfield** [comment]
Gary - something seems off with this (Cirrus can't seem to download the archive), but also I manually helped the engine roller along so you'll now have a conflict.

**Comment by GaryQian** [comment]
The engine commit is new, so the builders are still building the engine. I can patch it to be compatible with the autoroller.

**Comment by yjbanov** [comment]
For future reference, we have a "work in progress" label you can assign to a PR that tells the reviewers that the PR is not yet ready for review, for example, because the engine artifacts are not in place yet.

**Review by yjbanov — APPROVED** [review]

**Comment by yjbanov** [comment]
lgtm

**Pull request merged**
