### PR TITLE
Add RTL support to Stepper

### LINKED ISSUE #11379: Stepper RTL
The layout of a stepper is flipped in RTL. Ideally this would happen automatically but we'll need to check it.

### PR DESCRIPTION
**Pull request by abarth**
Fixes #11379

### CODE REVIEW

**Comment by abarth** [comment]
I'll need to think about how to test this effectively.  The existing stepper tests don't cover the LTR version.

**Comment by Hixie** [comment]
Maybe implement https://github.com/flutter/flutter/issues/11361 and then test that, and just flip the tests for this? :-)

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
(we discussed this in person and decided we'd add tests when fixing #11361 rather than now.)

**Pull request merged**
