### PR TITLE
Fix TextField/CupertinoTextField hint style overflow not work.

### PR DESCRIPTION
**Pull request by ksballetba**
*For HintText or PlaceholderText, I notice that `overflow` always is TextOverflow.ellipsis when build Hint Text Widget, and TextWidget Use TextWidget's property `overflow` first, not `overflow` property in`TextStyle`. so InputDecoration hintStyle TextOverflow.fade not work*

Build hint text widget code in input_decorator.dart
0CE03819-B8F4-4A1E-A57C-72D6BB12C280

Overflow annotation in text.dart
43FF1CBD-D6DF-4F57-9347-4886DB8659B7

**Set overflow: TextOverflow.clip to hintStyle**

Example Code
```
void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) =>
       const MaterialApp(
        home: Scaffold(
            body: Center(
              child: SizedBox(
                  width: 100,
                  child: TextField(
                    decoration: InputDecoration(
                      hintText: 'Long text to demonstrate',
                      hintStyle: TextStyle(
                          overflow: TextOverflow.clip
                      ),
                    ),
                  )
              ),
            )
        ),
      );
}
```

Before
IMG_20221031_141413

After
IMG_20221031_141353

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/113883

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by justinmc** [comment]
@ksballetba I just fixed this in InputDecorator the other day (https://github.com/flutter/flutter/pull/114378), but I missed the CupertinoTextField line.  Would you be able to merge master into this PR to pick up my change, then add a test for CupertinoTextField similar to the test in my PR?

Sorry for stepping on your toes here with my PR!

**Comment by ksballetba** [comment]
> @ksballetba I just fixed this in InputDecorator the other day (#114378), but I missed the CupertinoTextField line. Would you be able to merge master into this PR to pick up my change, then add a test for CupertinoTextField similar to the test in my PR?
> 
> Sorry for stepping on your toes here with my PR!

Of course, I will merge master into this PR to pick up your change, then add a test for CupertinoTextField. Could you help to review the code change？

**Review by justinmc — APPROVED** [review]
LGTM :+1: 

Thanks for updating this!

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

**Review by LongCatIsLooong — APPROVED** [review]

**Pull request merged**
