### PR TITLE
Fix OutlineButton and TextButton styleFrom throw exception when only given one cursor

### PR DESCRIPTION
**Pull request by timnew**
Fix issue https://github.com/flutter/flutter/issues/118071

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by bernaferrari** [comment]
Tests are failing

```
| ../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/material/outlined_button.dart:191:43: Error: The argument type 'MouseCursor?' can't be assigned to the parameter type 'MouseCursor' because 'MouseCursor?' is nullable and 'MouseCursor' isn't.
|  - 'MouseCursor' is from 'package:flutter/src/services/mouse_cursor.dart' ('../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/services/mouse_cursor.dart').
|       : _OutlinedButtonDefaultMouseCursor(enabledMouseCursor, disabledMouseCursor);
|                                           ^
| ../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/material/outlined_button.dart:191:63: Error: The argument type 'MouseCursor?' can't be assigned to the parameter type 'MouseCursor' because 'MouseCursor?' is nullable and 'MouseCursor' isn't.
|  - 'MouseCursor' is from 'package:flutter/src/services/mouse_cursor.dart' ('../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/services/mouse_cursor.dart').
|       : _OutlinedButtonDefaultMouseCursor(enabledMouseCursor, disabledMouseCursor);
|                                                               ^
| ../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/material/text_button.dart:205:39: Error: The argument type 'MouseCursor?' can't be assigned to the parameter type 'MouseCursor' because 'MouseCursor?' is nullable and 'MouseCursor' isn't.
|  - 'MouseCursor' is from 'package:flutter/src/services/mouse_cursor.dart' ('../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/services/mouse_cursor.dart').
|       : _TextButtonDefaultMouseCursor(enabledMouseCursor, disabledMouseCursor);
|                                       ^
| ../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/material/text_button.dart:205:59: Error: The argument type 'MouseCursor?' can't be assigned to the parameter type 'MouseCursor' because 'MouseCursor?' is nullable and 'MouseCursor' isn't.
|  - 'MouseCursor' is from 'package:flutter/src/services/mouse_cursor.dart' ('../../../../w/%C3%81%20flutter%20sdk/packages/flutter/lib/src/services/mouse_cursor.dart').
|       : _TextButtonDefaultMouseCursor(enabledMouseCursor, disabledMouseCursor);
```

**Review by QuncCccccc — COMMENTED** [review]
Thanks @timnew for your contribution! Seems we need to add some tests for the change and the current failing tests also need to be fixed.

**Comment by timnew** [comment]
@QuncCccccc will have further look at the tests, was a bit confused by the test reports.
I think I have better understanding now.

**Comment by bernaferrari** [comment]
Analyzer is the easiest one to fix

**Comment by timnew** [comment]
Got trapped in something, will come back and fix this

**Comment by TahaTesser** [comment]
Hi @timnew 
Thanks for your contribution. However due to the lack of tests and lack of activity for 2 months.
I feel to close this.

**Pull request closed without merging**
