### PR TITLE
[do not merge] google testing verify updating checkrun logic

### PR DESCRIPTION
**Pull request by XilaiZhang**
similar to https://github.com/flutter/flutter/pull/127895
this PR is used as an integration test to verify the logics we landed in cl/545799149

### CODE REVIEW

**Review by Jasguerrero — APPROVED** [review]
LGTM

**Comment by XilaiZhang** [comment]
Traced through the error this morning and it seems like we are [hardcoding to find a cr+lf+cr+lf in the http response to mark the ending of a header](https://source.corp.google.com/piper///depot/google3/dart/tools/github/lib/fetchproxy.dart;l=86-93;bpv=1;bpt=1?q=%22Input%20bytes%20are%20not%20a%20valid%20HTTP%20response.%22&sq=package:piper%20file:%2F%2Fdepot%2Fgoogle3%20-file:google3%2Fexperimental)

E.g. for a PR with empty content like the current one, the response [has no headers](https://patch-diff.githubusercontent.com/raw/flutter/flutter/pull/130046.patch)
and for a PR with content, the response [has a header](https://patch-diff.githubusercontent.com/raw/flutter/flutter/pull/130047.patch)

To unblock myself I will add some content to this PR.

**Comment by XilaiZhang** [comment]
The current error is due to a mismatch between github status states (failure, pending, success), and github checkrun statuses (queued, in progress, completed), working on a fix CL.

**Comment by XilaiZhang** [comment]
cl/547270332 has been merged and rolled out. rebased to see if the checkruns gets updated correctly this time.

**Comment by XilaiZhang** [comment]
Looks like the `Title` field is required, created cl/547615354 as a fix.

**Comment by XilaiZhang** [comment]
I have reset the live label to the frob server at head, since we confirmed in standup the culprit of [b/291100012](https://b.corp.google.com/issues/291100012) isn't checkrun related.

**Comment by XilaiZhang** [comment]
Traced through the logics (about 3 hours) on why the notification wasn't sent and the checkrun was doubly created. Eventually figured out that the checkrun field wasn't propagated when listing commits and rolls. Created cl/548243980

**Comment by XilaiZhang** [comment]
cl/549360644 was landed so we don't drop checkrun field when listing rolls. will retest this PR.

(we rolled mpm version back due to b/292007216, rerolling mpm back to head)

**Comment by XilaiZhang** [comment]
Umm the rolls are repeatedly created and deleted on a new pr, log: http://shortn/_irhfD2od2N. 
Looks like it is related to the logic in cl/548243905 , cc @CaseyHillers 
The isOpen field is always evaluated to false

**Comment by XilaiZhang** [comment]
Ok I think I found the ultimate solution to all the P0 and P1 bugs where new rolls are deleted. 

Sent cl/549797526

**Comment by XilaiZhang** [comment]
Screenshot 2023-07-21 at 10 16 25 AM
This looks expected. The next steps are to pretty print the log, add time stamps, and list in bullet points.

**Comment by XilaiZhang** [comment]
Testing timestamps added in cl/551665601

**Pull request closed without merging**
