### PR TITLE
Strip the CPU from the flutter basename when determining host basename

### PR DESCRIPTION
**Pull request by liamappelbe**
This makes it a little easier to run flutter with a local engine.

### CODE REVIEW

**Comment by zanderso** [comment]
@liamappelbe do you want to continue with this PR? Could you expand on the description a bit, if so? How does it improve the workflow?

**Comment by liamappelbe** [comment]
Currently if you build a local engine with a specific --android-cpu, eg android_debug_unopt_x86, the hostBasename will be deduced as host_debug_unopt_x86. But the host engine doesn't specify the CPU, so the tool will error saying the host directory doesn't exist.

The usual fix is for the developer to manually symlink host_debug_unopt_x86 -> host_debug_unopt, which seems like an unnecessary hassle to me. This change just means you don't have to make the symlink.

**Comment by kangwang1988** [comment]
Also see: https://github.com/flutter/flutter/pull/27765

**Comment by liamappelbe** [comment]
https://github.com/flutter/flutter/pull/27765 is submitted, so this PR is unnecessary.

**Pull request closed without merging**
