### PR TITLE
Return the padding of button theme is second

### PR DESCRIPTION
**Pull request by ghost**
When use [RaisedButton.icon], [FlatButton.icon] or [OutlineButton.icon] the padding in theme button is not returned.

That make issue when the padding [RaisedButton.icon], [FlatButton.icon] [OutlineButton.icon] is not same with the buttons using the padding in theme button.

Sorry my english not good.

### CODE REVIEW

**Comment by nguu** [comment]
@googlebot I signed it!

**Comment by HansMuller** [comment]
This looks like a reasonable change although it would need tests. The change might break existing tests (aside from the unit tests that have already been checked). If so, you'd have to navigate the breaking change policy: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes.

All that said, it's probably best to leave ButtonTheme alone because it's being replaced: https://flutter.dev/go/material-button-system-updates.

The default values, include padding, for the new button widgets are defined by the widget classes, not by their themes. So to discover the default padding for an ElevatedButton you'd write:
```dart
EdgeInsetsGeometry insets = ElevatedButton(
  onPressed: null,
  child: SizedBox(width: 100, height: 100),
).padding;
```

Or for label/icon version:

```dart
EdgeInsetsGeometry insets = ElevatedButton.icon(
  onPressed: null,
  label: SizedBox(width: 50, height: 100),
  icon: SizedBox(width: 50, height: 100),
).padding;
```

The sizes of the button children don't really matter.

As you can see in the latest sources, e.g. [the source for TextButton](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_button.dart#L180), the default padding depends on the current [textScaleFactor](https://api.flutter.dev/flutter/widgets/MediaQueryData/textScaleFactor.html). It's different than the values reported by ButtonTheme because all of the button components have been aligned with the current Material Design spec.

So: all that to say that we appreciate your contribution, but will probably not try and get this PR landed.

**Comment by nguu** [comment]
Thank you for your reply, i really hope to new button system.

**Comment by HansMuller** [comment]
I'm going to close this per https://github.com/flutter/flutter/pull/60973#issuecomment-670792756, thanks again for the contribution.

**Pull request closed without merging**
