### PR TITLE
Reland2: Revert "Revert "Add a warning/additional handlers for parsing`synthetic-package`.""

### PR DESCRIPTION
**Pull request by polina-c**
Reverts flutter/flutter#158078

### CODE REVIEW

**Review by matanlurey — APPROVED** [review]

**Comment by polina-c** [comment]
Bypassing G3 failures because fix is merged: https://github.com/flutter/flutter/pull/158126

**Comment by polina-c** [comment]
Should i bypass tree status?

**Comment by johnmccutchan** [comment]
if all tests are passing, go for it

**Comment by polina-c** [comment]
Its interesting that label did not trigger merge this time.

**Pull request merged**
