### PR TITLE
Roll engine 2707b7433874..e79d77f6e6cd (7 commits)

### PR DESCRIPTION
**Pull request by engine-flutter-autoroll**
https://github.com/flutter/engine/compare/2707b7433874...e79d77f6e6cd

git log 2707b7433874..e79d77f6e6cd --no-merges --oneline
e79d77f6e Add offset to engine OpacityLayer (flutter/engine#6594)
a9974a3f4 Roll src/third_party/skia 1bccae517ace..eb772c0869d5 (6 commits) (flutter/engine#6612)
2fab7d729 Roll src/third_party/skia e2865b28005f..1bccae517ace (1 commits) (flutter/engine#6611)
8b069adf1 Revert &#34;Roll buildroot to 4ee38927dc45c46f2a1c74b1e3700b3cf953e747 (#6586)&#34; (flutter/engine#6610)
958086d5a Roll src/third_party/skia 607d2610e5e3..e2865b28005f (2 commits) (flutter/engine#6608)
d0fae0428 Roll src/third_party/skia 9a986cfd5f58..607d2610e5e3 (4 commits) (flutter/engine#6606)
c0b1b37d6 Roll src/third_party/skia 798a713685a9..9a986cfd5f58 (2 commits) (flutter/engine#6604)

The AutoRoll server is located here: https://autoroll.skia.org/r/flutter-engine-flutter-autoroll

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/&#43;/master/autoroll/README.md

If the roll is causing failures, please contact the current sheriff, who should
be CC&#39;d on the roll, and stop the roller if necessary.

### CODE REVIEW

**Comment by engine-flutter-autoroll** [comment]
@liyuqian : New roll has been created by https://autoroll.skia.org/r/flutter-engine-flutter-autoroll

**Comment by engine-flutter-autoroll** [comment]
Trybots failed. These were the failed builds: https://cirrus-ci.com/task/5000933958221824 , https://cirrus-ci.com/task/6126833865064448

**Comment by engine-flutter-autoroll** [comment]
AutoRoller is stopped; closing the active roll.

**Comment by liyuqian** [comment]
Retry Cirrus for manual merge

**Pull request merged**
