### PR TITLE
generate docs for sprites

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
cc @abarth 

I'm surprised I didn't see "pub get" in this script, as we'll need to run that before I can run dartdocs. But maybe it's run somewhere else? So, let's see what travis says.

**Comment by sethladd** [comment]
also, cc @vlidholt because flutter_sprites

**Comment by abarth** [comment]
> I'm surprised I didn't see "pub get" in this script

It's in setup.sh

> So, let's see what travis says.

Travis doesn't run the dartdoc step for pull requests because it doesn't have the keeps to push the updates.

**Comment by sethladd** [comment]
Thanks. I looked at setup.sh and dev/update_packages.dart and it looks like `pub get` will be run for flutter_sprites.

Based on that, I expect this to merge and run cleanly.

**Comment by abarth** [comment]
LGTM

**Comment by sethladd** [comment]
Thanks!

**Pull request merged**
