### PR TITLE
Apply changes caused by https://github.com/flutter/flutter/pull/76662

### PR DESCRIPTION
**Pull request by Hixie**
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
This probably needs a test; I'm thinking maybe we should add something to the end of each shard that makes sure there's no local changes in the workspace? Not quite sure how to do that.
cc @jonahwilliams

**Comment by jmagman** [comment]
Not sure if there are more, but if you run `SHARD=build_tests  dart dev/bots/test.dart` locally it will build (and therefore update `generated_plugin_registrant`) all the example and integration tests.

https://github.com/flutter/flutter/issues/76726

**Comment by Hixie** [comment]
I thought I had, but that was on another PR's branch so maybe when I stashed the changes I didn't apply things sufficiently.

**Comment by jmagman** [comment]
> I thought I had, but that was on another PR's branch so maybe when I stashed the changes I didn't apply things sufficiently.

Ah okay that might be it then.

**Comment by jonahwilliams** [comment]
I'm not sure what the current state of the art for LUCI testing is. Since we generate the plugin registrants during a pub get, I think checking after running `flutter pub get` in each repo would be sufficient. Maybe we should update flutter update-packages so that it also does this?

**Comment by Hixie** [comment]
This isn't the only source of local changes we've ever had. I was imagining that we'd literally just end every shard with a quick check to see if `git diff` had any output, because if it does then that's a problem in general.

I guess I can literally just do `git diff --exit-code` at the end of every shard...

**Comment by Hixie** [comment]
Experimenting with https://github.com/flutter/flutter/pull/77100

**Review by blasten — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
I'll land this on green, I have tests for it in https://github.com/flutter/flutter/pull/77100

**Pull request merged**
