### PR TITLE
Make --flutter-repo analyze whole repo

### LINKED ISSUE #127989: `flutter analyze --flutter-repo` should analyze `analysis_options.yaml`
`flutter analyze --flutter-repo` currently does not analyze the `analysis_options.yaml` at the root of the repository. This caused us to miss some warnings about deprecated lints in that file. The command should be updated to analyze that file as well since it is part of the repository and it may have issues reported by the analyzer.

Steps to repro the failure to report deprecated lints in that file:

1. Add the deprecated lint `iterable_contains_unrelated_type` to the [analysis_options.yaml](https://github.com/flutter/flutter/blob/master/analysis_options.yaml) at the root of the repository.
2. Verify that the analyzer reports a deprecated lint when analyzing this specific file alone: `flutter analyze analysis_options.yaml`.
3. Run `flutter analyze --flutter-repo` and observe that no deprecated lint is reported.

Expected Output:

```
   info • 'iterable_contains_unrelated_type' is deprecated and should be replaced by 'collection_methods_unrelated_type' • analysis_options.yaml:113:7 •
          deprecated_lint_hint_with_replacement
```

Actual Output: nothing reported.

### PR DESCRIPTION
**Pull request by goderbauer**
Fixes https://github.com/flutter/flutter/issues/127989.

### CODE REVIEW

**Comment by goderbauer** [comment]
The failing analyzer checks are the reason for this change, we previously missed those issues. The failures are fixed in https://github.com/flutter/flutter/pull/127976.

**Comment by christopherfujino** [comment]
This code looks good to me. To test, I would add a hermetic analyze command test similar to: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands.shard/hermetic/analyze_test.dart#L85, but that provides the `--flutter-repo` argument and verifies in the `FakeCommand()` to the analysis server what the working directory is.

**Comment by goderbauer** [comment]
> provides the --flutter-repo argument and verifies in the FakeCommand() to the analysis server what the working directory is.

The directories to analyze are actually provided via stdin:

https://github.com/flutter/flutter/blob/513ff44bce174e7e5efe1afbfc9757aca969ce63/packages/flutter_tools/lib/src/dart/analysis.dart#L95

I saw the FakeCommand provides an option to pass in an stdin IOSink, but I haven't been able to wire this up properly so I could actually listen in the test what was send to the process via stdin...

**Comment by christopherfujino** [comment]
> > provides the --flutter-repo argument and verifies in the FakeCommand() to the analysis server what the working directory is.
> 
> The directories to analyze are actually provided via stdin:
> 
> https://github.com/flutter/flutter/blob/513ff44bce174e7e5efe1afbfc9757aca969ce63/packages/flutter_tools/lib/src/dart/analysis.dart#L95
> 
> I saw the FakeCommand provides an option to pass in an stdin IOSink, but I haven't been able to wire this up properly so I could actually listen in the test what was send to the process via stdin...

Ahh, interesting that it uses STDIN. Here's an example of a test that verifies what was passed via stdin to a sub-command: https://github.com/flutter/flutter/blob/master/dev/conductor/core/test/packages_autoroller_test.dart#L332

**Comment by goderbauer** [comment]
Thanks, I got it working.

**Review by christopherfujino — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
