### PR TITLE
Make packages_test run `flutter packages` from newly created project dir

### PR DESCRIPTION
**Pull request by tvolkert**
These changes to the test would have caught the issue that was
fixed by #12258

### CODE REVIEW

**Comment by Hixie** [comment]
I don't understand how this code change results in the test working as you expect but LGTM. :-)

RSLGTM

**Comment by Hixie** [comment]
@tvolkert are you still working on this?

**Comment by tvolkert** [comment]
I wasn't, but I should probably pick it back up.  I'll try to do so in the next few days.

**Comment by Hixie** [comment]
Closing for now, please reopen if you pick this back up! Thanks!

**Pull request closed without merging**
