### PR TITLE
Catch dismissable while it's animating.

### LINKED ISSUE #173: You can't catch a dismissable that's bouncing back
<a href="https://github.com/Hixie"></img></a> **Issue by [Hixie](https://github.com/Hixie)**
_Friday Sep 25, 2015 at 19:47 GMT_
_Originally opened as https://github.com/flutter/engine/issues/1348_

----

If you half-dismiss a card in the card collection demo, then wait for it to start bouncing back, then catch it as it's bouncing back and dismiss it again, nothing happens. I'm guessing it's because _handleDragStart() does nothing if the fade performance is underway, but surely it should interrupt the current performance and slave it to the finger if the finger goes down again.

### PR DESCRIPTION
**Pull request by Hixie**
Fixes #173.

### CODE REVIEW

**Comment by Hixie** [comment]
This doesn't work as well as it should, because the vertical drag gesture and the horizontal drag gesture fight over who should own the pointer so if you put your finger down, it keeps animating. I'm not really sure how to handle that... either the horizontal gesture should always win when you tap an animating dismissable (and you can't drag vertically at that time -- that should be easy to do, by just having a flag that makes it greedy), or we should stop it on down, and then resume it when the horizontal drag doesn't win (using the onDragDown/onDragCancel pattern from tap).

I propose doing that in a separate pass though. This patch is still an improvement over the status quo.

**Comment by abarth** [comment]
LGTM

The DrawerController has the same issue as you describe for the followup patch.  I think the DragDown/DragCancel pattern will scale better than a greedy flag (and we've already gone down that path for tap).

**Comment by abarth** [comment]
Another interesting case to look at is the Switch.  Dragging the switch has a delay because the drag gesture is fighting with the tap gesture.  However, the UX is arranged such that starting a drag and completing with a tap makes sense because they both want to drive the performance in the same direction.

**Comment by abarth** [comment]
Another interesting case to look at is the Switch.  Dragging the switch has a delay because the drag gesture is fighting with the tap gesture.  However, the UX is arranged such that starting a drag and completing with a tap makes sense because they both want to drive the performance in the same direction.  It's an odd case though and might be better handled with a custom gesture.

**Comment by abarth** [comment]
Another interesting case to look at is the Switch.  Dragging the switch has a delay because the drag gesture is fighting with the tap gesture.  However, the UX is arranged such that starting a drag and completing with a tap makes sense because they both want to drive the performance in the same direction.  It's an odd case though and might be better handled with a custom gesture.

**Comment by Hixie** [comment]
My main concern with having onDragDown, onDragDownMove, and onDragCancel is that it adds at least nine events to GestureDetector. I agree that it's probably the right solution though.

**Comment by Hixie** [comment]
Filed https://github.com/flutter/flutter/issues/1028

**Comment by Hixie** [comment]
Also filed https://github.com/flutter/flutter/issues/1029 for the opacity regression.

**Comment by abarth** [comment]
> My main concern with having onDragDown, onDragDownMove, and onDragCancel is that it adds at least nine events to GestureDetector. I agree that it's probably the right solution though.

We could switch how GestureDetector works so that it takes a TapGestureClient and a DragGestureClient as argument instead of individual callbacks.  Then you'd mix them into your State object.  That would also make it obvious which callbacks were grouped together into one gesture.

**Pull request merged**
