### PR TITLE
[flutter_tools] show only supported sub commands

### LINKED ISSUE #12512: Consider not showing options/flags of the flutter command which are irrelevant on the platform it's running on
Currently the `flutter help build` command will show this on my **linux**:

```
% flutter help build
Flutter build commands.

Usage: flutter build <subcommand> [arguments]
-h, --help    Print this usage information.

Available subcommands:
  aot     Build an ahead-of-time compiled snapshot of your app's Dart code.
  apk     Build an Android APK file from your app.
  clean   Delete the build/ directory.
  flx     Build a Flutter FLX file from your app.
  ios     Build an iOS application bundle (Mac OS X host only).

Run "flutter help" to see global options.
```

Since we cannot do iOS development on linux, maybe the help command should not even show **`ios`** here (see help text for last sub-command).

### PR DESCRIPTION
**Pull request by asashour**
Fixes #12512

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM - err wait

**Comment by jonahwilliams** [comment]
you need to update the failing unit/integration tests

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
This caused post-submit CI failures, and was reverted in https://github.com/flutter/flutter/pull/86131

**Pull request merged**
