### PR TITLE
move the calculator files around

### LINKED ISSUE #4110: Bots having trouble with Calculator part of mega_gallery
Maybe some sync work is needed per #4092.

See https://travis-ci.org/flutter/flutter/builds/132357929

Swan song is:
```
+dart dev/tools/mega_gallery.dart
Making 10 copies of flutter_gallery.
Stats:
  packages/flutter            : 382 files, 59,345 lines
  examples/flutter_gallery    :  58 files,  6,686 lines
  dev/benchmarks/mega_gallery : 481 files, 59,003 lines
+cd dev/benchmarks/mega_gallery
+flutter analyze --watch --benchmark
Running 'pub get' in mega_gallery...                 5.6s
Analyzing mega_gallery...
  error • Target of URI does not exist: '../calculator/interface.dart' • lib/gallery_1/gallery/app.dart:8:8
warning • Undefined name 'Calculator' • lib/gallery_1/gallery/app.dart:16:3
warning • Undefined class 'Calculator' • lib/gallery_1/gallery/app.dart:16:55
  error • Target of URI does not exist: '../calculator/interface.dart' • lib/gallery_1/gallery/home.dart:8:8
warning • Undefined name 'Calculator' • lib/gallery_1/gallery/home.dart:80:63
  error • Target of URI does not exist: '../calculator/interface.dart' • lib/gallery_2/gallery/app.dart:8:8
warning • Undefined name 'Calculator' • lib/gallery_2/gallery/app.dart:16:3
warning • Undefined class 'Calculator' • lib/gallery_2/gallery/app.dart:16:55
...
```

### PR DESCRIPTION
**Pull request by devoncarew**
Move the calculator files around in the flutter_gallery example (fix https://github.com/flutter/flutter/issues/4110). This makes the calculator files look more like the other demo\* files.

@HansMuller

### CODE REVIEW

**Comment by HansMuller** [comment]
LGTM

**Comment by Hixie** [comment]
Sorry about breaking the mega gallery. Shouldn't that have broken on travis?

I'd intentionally not done that originally because I was worried about the logic file being in the same directory as the demos. Also it seems kind of weird to have this be a demo since it actually is fully fledged and useful unlike the others. :-)

Having said that, this is fine by me. Hans owns this. :-)

**Comment by devoncarew** [comment]
> Shouldn't that have broken on travis?

Yup - looks like we aren't returning the right exit code for `--watch --benchmark`.

> I was worried about the logic file being in the same directory as the demos

This makes things slightly easier for the large benchmark app, but we can adjust to whatever the files system organization is. It might be nice to mirror the UI organization on the file system: Demos, Components, and Style.

**Comment by devoncarew** [comment]
https://github.com/flutter/flutter/pull/4117

**Comment by Hixie** [comment]
FWIW we might just remove this demo anyway, so don't worry about it.

**Pull request merged**
