### PR TITLE
docImports for flutter_test

### PR DESCRIPTION
**Pull request by goderbauer**
Part of https://github.com/flutter/flutter/issues/150800

Issues encountered:

- [ ] cannot reference something from flutter_driver (which is not a dependency of flutter_test), example: https://github.com/flutter/flutter/blob/af913a75b5d28b03f0bfe0ee44f9343ae26ae146/packages/flutter_test/lib/src/controller.dart#L2228
- [ ] (known) cannot reference anything in doc comments for enum values
- [ ] (known) cannot reference library names

### CODE REVIEW

**Comment by goderbauer** [comment]
Another observation that @srawlins might find interesting: While the comment_reference lint is happy with this reference after adding the docImport, the IDE still says "Cannot find declaration to go to" when trying to click through:

https://github.com/flutter/flutter/blob/ab55dd6620c0a9371972c88838d0932dc4d6263d/packages/flutter_test/lib/src/widget_tester.dart#L825

**Comment by srawlins** [comment]
Is it just in that one case? Is `TestFailure` from `package:test_api`?

**Comment by srawlins** [comment]
> cannot reference something from flutter_driver (which is not a dependency of flutter_test), example:

Can `flutter_driver` be a dev_dependency of `flutter_test`? Just for this purpose?

**Comment by goderbauer** [comment]
> Is it just in that one case?

First one I noticed.

> Is TestFailure from package:test_api?

Yes.

**Comment by goderbauer** [comment]
> Can flutter_driver be a dev_dependency of flutter_test? Just for this purpose?

Oh, interesting idea. Let me see if that breaks anything...

**Review by srawlins — APPROVED** [review]

**Pull request merged**
