### PR TITLE
Mark 'Mac plugin_dependencies_test' unflaky

### PR DESCRIPTION
**Pull request by jmagman**
Not flaky
https://data.corp.google.com/sites/flutter_infra_metrics_datasite/flutter_check_prod_test_flakiness_status_dashboard/?p=BUILDER_NAME:%22Mac%20plugin_dependencies_test%22

### CODE REVIEW

**Review by keyonghan — APPROVED** [review]
Planned to wait for the auto process to pick this up. Thanks for the change!
LGTM.

**Comment by jmagman** [comment]
> Planned to wait for the auto process to pick this up. Thanks for the change!
> LGTM.

Would you like me to wait for it to test it? I was surprised it didn't happen at the same time as https://github.com/flutter/flutter/pull/87048 and https://github.com/flutter/flutter/pull/87046

**Comment by keyonghan** [comment]
> > Planned to wait for the auto process to pick this up.
> 
> Would you like me to wait for it to test it? I was surprised it didn't happen at the same time as #87048 and #87046

It is good to land. The auto process is using the same logic: no flake in top 50 runs.

That's interesting. I don't see any reason why this one shouldn't be picked up. /cc @chunhtai do you have any clue here?

**Comment by chunhtai** [comment]
It looks like it has not been ran before july? I saw a big gap between 7/22 /2021 to 10/14/2020

Eitherway, when it ran this monday, the past 50runs contains this one which is flaky, so it didn't pass the check

2020-10-14 12:26:35 | 767fb98a7b3b75bb6545cd707b9ad5103ae12df7 | Mac plugin_dependencies_test | true
-- | -- | -- | --

**Comment by jmagman** [comment]
It automatically picked up in https://github.com/flutter/flutter/pull/87477.  Closing.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/87477 is a mess, there was an analyzer warning and now a merge conflict. I'm going to do this one manually.

**Comment by gaaclarke** [comment]
@jmagman  This was flagged for a regression of type "non-size-or-debt".  I'm not sure what that means, just checking in if it makes sense to you:

https://flutter-flutter-perf.skia.org/t/?begin=1628043304&end=1628043306&subset=all

I guess it could mean anything but size or debt...  so anything.   It seems to be related to the compilation size of a few tests.  I'm inclined to ignore this considering what is in this PR.

**Comment by jmagman** [comment]
Weird, definitely not related to this PR.  That metric is collected from `hello_world_android__compile`, `hello_world_ios__compile`, `technical_debt__cost`.  Sometimes it looks like a commit regresses a benchmark but it's really from a few commits before because the test scheduler coalesces a few into one test run (the gray boxes on the Flutter dashboard).  However in this case the only test that didn't run individually on this PR was `analyzer_benchmark`, which isn't used for that metric...

**Pull request merged**
