### PR TITLE
Update Dart SDK to 1.25.0-dev.16.4

### PR DESCRIPTION
**Pull request by cbracken**

### CODE REVIEW

**Comment by devoncarew** [comment]
lgtm; I assume this guy is more analyzer happy than `2.0.0-dev.8.0`?

**Comment by cbracken** [comment]
If this passes pre/post-submit I'll give a go bumping to the 2.0.0 series. Figured on doing this in two baby steps.

**Comment by devoncarew** [comment]
Leaf has a PR to go all the way to 2.0; it does require addressing a few dozen changes to do with removing "fuzzy arrows" strong mode feature in 2.0.

**Comment by cbracken** [comment]
Looks like this doesn't pass analysis shard on Travis without changes. Didn't go through the full list but the ones I did appear to be at least a subset of the issues covered in #13223.

**Pull request closed without merging**
