### PR TITLE
Fix some tests now that the isMultiline flag is added to values

### LINKED ISSUE #34265: [web][upstream] In semantics upstream isMultiline
Upstream isMultiline in semantics.dart

https://github.com/flutter/flutter_web/blob/master/packages/flutter_web/lib/src/semantics/semantics.dart

### PR DESCRIPTION
**Pull request by mdebbar**
Depends on https://github.com/flutter/engine/pull/9894

Fixes https://github.com/flutter/flutter/issues/34265

### CODE REVIEW

**Review by yjbanov — APPROVED** [review]
lgtm

**Comment by dnfield** [comment]
The tests have to be updated to support this - there are a bunch of semantics tests tha tlook like they're failing because they expect to see or not see the flag now.

**Comment by yjbanov** [comment]
I will try to land this in https://github.com/flutter/flutter/pull/37328.

@dnfield 

> The tests have to be updated to support this

This PR only changes tests. No other tests should be affected.

**Comment by dnfield** [comment]
When I commented there were a bunch of failing test, maybe for some unrelated reason then.

**Pull request closed without merging**
