### PR TITLE
Report semantics geometry in physical units.

### PR DESCRIPTION
**Pull request by Hixie**
Previously we used logical pixels. This made the accessibility metrics
tiny on modern devices, since the OS works in physical units.

Also add a bit more debugging info and some docs.

### CODE REVIEW

**Comment by Hixie** [comment]
See also https://github.com/flutter/engine/pull/3694 which fixes related bugs on Android.

**Comment by Hixie** [comment]
cc @abarth

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
PTAL, I had to make a bunch of additional changes now that the devicePixelRatio is non-1.0 in tests.

**Comment by abarth** [comment]
Still LGTM

**Pull request merged**
