### PR TITLE
Handle breaking changes in leak_tracker.

### PR DESCRIPTION
**Pull request by polina-c**

### CODE REVIEW

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
@polina-c it looks like you manually merged this with a failing google testing check. Per https://github.com/flutter/flutter/wiki/Tree-hygiene#landing-a-patch, contributors must use the `autosubmit` label and let the bot merge their PRs (this will be enforced soon).

In addition, the "Google testing" check is important for the release team: https://github.com/flutter/flutter/wiki/Understanding-Google-Testing. Please contact the #hackers-infra chat on discord if you need help with a false negative Google testing check. Thanks!

**Comment by polina-c** [comment]
> @polina-c it looks like you manually merged this with a failing google testing check. Per https://github.com/flutter/flutter/wiki/Tree-hygiene#landing-a-patch, contributors must use the `autosubmit` label and let the bot merge their PRs (this will be enforced soon).
> 
> In addition, the "Google testing" check is important for the release team: https://github.com/flutter/flutter/wiki/Understanding-Google-Testing. Please contact the #hackers-infra chat on discord if you need help with a false negative Google testing check. Thanks! 

@christopherfujino 

Yes, "Google testing" must be respected!

I've read the instructions for Google testing and they said, that if failure is because of merge conflict and it is low risk, it is ok to bypass google testing: https://github.com/flutter/flutter/runs/16984390339

As changes are just in tests and dev_dependencies, I decided it is low risk.

What did i miss?

**Comment by christopherfujino** [comment]
> I've read the instructions for Google testing and they said, that if failure is because of merge conflict and it is low risk, it is ok to bypass google testing: https://github.com/flutter/flutter/runs/16984390339
> 
> As changes are just in tests and dev_dependencies, I decided it is low risk.
> 
> What did i miss?

Ahh, I see what happened. The way to bypass "Google testing" is to set the GitHub status in the FRoB dashboard, see: https://github.com/flutter/flutter/wiki/Understanding-Google-Testing#i-am-a-googler-i-dont-want-google-testing-to-run-and-how-do-i-manually-set-google-testing-to-pass. Then add the `autosubmit` label, to allow the bot to merge your PR.

**Comment by polina-c** [comment]
> > I've read the instructions for Google testing and they said, that if failure is because of merge conflict and it is low risk, it is ok to bypass google testing: https://github.com/flutter/flutter/runs/16984390339
> > As changes are just in tests and dev_dependencies, I decided it is low risk.
> > What did i miss?
> 
> Ahh, I see what happened. The way to bypass "Google testing" is to set the GitHub status in the FRoB dashboard, see: https://github.com/flutter/flutter/wiki/Understanding-Google-Testing#i-am-a-googler-i-dont-want-google-testing-to-run-and-how-do-i-manually-set-google-testing-to-pass. Then add the `autosubmit` label, to allow the bot to merge your PR.

Oh, thanks. Will follow next time.

**Comment by christopherfujino** [comment]
> Oh, thanks. Will follow next time.

Thanks Polina!

**Pull request merged**
