### PR TITLE
Allow any iOS app to be added to an existing host app

### PR DESCRIPTION
**Pull request by jmagman**
## Description

Remove the module restriction from `flutter build ios-framework` to allow normal apps to be exported as embeddable frameworks.

The only difference in output is that the module has a `FlutterPluginRegistrant` framework that only contains the `GeneratedPluginRegistrant` class.  For non-modules, copy `GeneratedPluginRegistrant.{h,m}` to the output directory and tell the user to manually copy it to their host project.

Run from a `flutter create app` (not module) project:
Screen Shot 2020-11-16 at 1 19 02 PM
```
$ ls -la flutter-frameworks 
total 16
drwxr-xr-x   7 magder  primarygroup  224 Nov 16 13:18 .
drwxr-xr-x  26 magder  primarygroup  832 Nov 16 13:16 ..
drwxr-xr-x   4 magder  primarygroup  128 Nov 16 13:17 Debug
-rw-r--r--   1 magder  primarygroup  357 Nov 16 13:17 GeneratedPluginRegistrant.h
-rw-r--r--   1 magder  primarygroup  438 Nov 16 13:17 GeneratedPluginRegistrant.m
drwxr-xr-x   4 magder  primarygroup  128 Nov 16 13:18 Profile
drwxr-xr-x   4 magder  primarygroup  128 Nov 16 13:18 Release
```
## Tests

Updated build_ios_framework_module_test to test an app as well as a module.

### CODE REVIEW

**Comment by xster** [comment]
Removing arbitrary restrictions definitely sound reasonable. Do you foresee new potential collision issues since currently it's impossible for users to add entitlements, plists, change the build settings etc on the module. 

Also tangent: if we do this on Android, we'll have to re-think about how to do analytics for add-to-app since the detection (also very imperfect) is based on the module template being merged into the app.

**Comment by jmagman** [comment]
> Removing arbitrary restrictions definitely sound reasonable. Do you foresee new potential collision issues since currently it's impossible for users to add entitlements, plists, change the build settings etc on the module.

You mean the user may be surprised that they need to add an entitlement to their host app when they already added it to their Flutter iOS app?  I guess I'm assuming a higher level of Apple development understanding here.  This doesn't do anything for the more magic embedding CocoaPods case that requires a module.  Flutter isn't really special, it's just a framework, and some frameworks require that entitlements be added when you embed and use them. We can see if we get any confused user bugs.

**Review by xster — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Failing because it's causing the test to want to sign things: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8863328391455486464/+/steps/run_test.dart_for_build_tests_shard_and_subshard_0/0/stdout#L23291_0

**Pull request merged**
