### PR TITLE
Fixed broken links to apple human interface guidelines

### PR DESCRIPTION
**Pull request by levrik**

### CODE REVIEW

**Comment by levrik** [comment]
I signed it!

**Review by a14n — APPROVED** [review]
LGTM

There are also 2 other links to update in [packages/flutter/lib/src/cupertino/dialog.dart](https://github.com/flutter/flutter/blob/e792c6bb5b9c7b75761b77d51685b4193f1d3546/packages/flutter/lib/src/cupertino/dialog.dart) ([line 63](https://github.com/flutter/flutter/blob/e792c6bb5b9c7b75761b77d51685b4193f1d3546/packages/flutter/lib/src/cupertino/dialog.dart#L63) and [line 111](https://github.com/flutter/flutter/blob/e792c6bb5b9c7b75761b77d51685b4193f1d3546/packages/flutter/lib/src/cupertino/dialog.dart#L111))

**Comment by levrik** [comment]
@a14n Weird. These were the first two that I fixed...

**Review by a14n — APPROVED** [review]
LGTM

**Pull request merged**
