### PR TITLE
Turn on compute credits for all contributor builds

### PR DESCRIPTION
**Pull request by gspencergoog**

### CODE REVIEW

**Comment by fkorotkov** [comment]
@gspencergoog there was a mistake in the docs. The expressions should be `$CIRRUS_PR == ''`.

Fixed the docs here: https://github.com/cirruslabs/cirrus-ci-docs/commit/5c43b918895dbc7b0a88e0ab377b506182e43d11

Sorry for the inconvenience. 😅

**Comment by gspencergoog** [comment]
Is that the same as "user who has write access to the repo?"

**Comment by fkorotkov** [comment]
@gspencergoog not the same. It's all the people here https://github.com/flutter/flutter/graphs/contributors

There is no environment variable reflecting user's permissions but if you want `CIRRUS_USER_PERMISSION` can be added ;-)

**Comment by gspencergoog** [comment]
Yes, I think `CIRRUS_USER_PERMISSION` would be a nice feature.  `CIRRUS_USER_COLLABORATOR` will work for now, however.

**Comment by fkorotkov** [comment]
👍 created https://github.com/cirruslabs/cirrus-ci-docs/issues/68

**Comment by DanTup** [comment]
@gspencergoog based on the comments there, it seems like `CIRRUS_USER_COLLABORATOR` will be true for PRs from anyone that has had a change merged, but the title suggests it should only be non-PRs?

(if builds using credits may still end up queued, I wonder if being able to set a priority would be good - eg. we probably always want `master` builds to run before PRs, even if we were using credits for PR builds?)

**Comment by DanTup** [comment]
In that case, LGTM - I can see there credit badges on the completed builds in Cirrus (@fkorotkov it may be useful to show some indicator on the in-progress builds too, minus the cost ofc).

**Review by DanTup — APPROVED** [review]

**Pull request merged**
