### PR TITLE
Migrate Gradle

### LINKED ISSUE #87649: [flutter_tools] Support for Android Gradle Plugin 7.0.0
As Android Gradle Plugin 7.0.0 [released](https://developer.android.com/studio/releases/gradle-plugin#7-0-0)

### Steps to reproduce 

1.  Execute `flutter create myapp`
2.  Locate `myapp/android` and delete `gradle` distribution folder 
3. Update Android Gradle Plugin `myapp/android/build.gradle` to `7.0.0`
4.  Execute `flutter run -v` from the root directory of myapp.

### Actual Results:
Flutter doesn't support this version and throws the following exception: (using 7.0.2 default version) 
```console
[  +33 ms] Building APK
[  +40 ms] Running Gradle task 'assembleDebug'...
[  +15 ms] LocalFile: 'C:\Users\Taha\StudioProjects\triage-companion\android\build.gradle' provides AGP version: 7.0.0
[+9740 ms] Exception: Unsupported Android Plugin version: 7.0.0.
[   +2 ms] "flutter run" took 17,921ms.
```

The Source of this exception is [here](https://github.com/flutter/flutter/blob/c4a2a3e92d9b076cbcb7b76e7017410ddbc3bb5f/packages/flutter_tools/lib/src/android/gradle_utils.dart#L182-L186)

### Expected  Results:
The app runs with updated AGP and Gradle distribution is downloaded

### PR DESCRIPTION
**Pull request by TahaTesser**
- Migrated tools to Gradle 7.0.2 and AGP 7.0.1 (updated tests too).
- Migrated templates to Gradle 7.0.2 and AGP 7.0.1.
- Migrated flutter/dev samples to Gradle 7.0.2 and AGP 7.0.1.
- Migrated flutter/examples to Gradle 7.0.2 and AGP 7.0.1.
- Migrated packages/integration_test & packages/integration_test/example  to Gradle 7.0.2 and AGP 7.0.1.
- Update ci.yaml

Fixes https://github.com/flutter/flutter/issues/87649

A fresh take on https://github.com/flutter/flutter/pull/87761

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by TahaTesser** [comment]
@blasten 
This is a cleaner and updated PR for https://github.com/flutter/flutter/pull/87761
For some reason ci.yaml validation is failing again

**Comment by blasten** [comment]
Thanks. Are the changes in stock_strings.dart intended?

@CaseyHillers is the ci.yaml issue real?

**Comment by CaseyHillers** [comment]
> @CaseyHillers is the ci.yaml issue real?

This is an open issue i'm about to send a fix for (anyone sending PRs right when cocoon deploys is seeing this). Pushing an empty commit should fix it.

**Comment by guidezpl** [comment]
I saw activity on a related issue https://github.com/flutter/flutter/issues/81095 this morning, is it going to be a problem?

**Comment by TahaTesser** [comment]
@blasten 
`stock_strings.dart` change was intended, reversed those changes. 

Now the only `Linux android views` test failing, again I am lost D

**Comment by TahaTesser** [comment]
@blasten 
All green

**Comment by blasten** [comment]
sorry for the wait.  Feel free to merge after fixing the conflict

**Review by blasten — APPROVED** [review]
LGTM

**Comment by TahaTesser** [comment]
@blasten 
Completed AGP `7.0.1` updates :)

**Review by blasten — APPROVED** [review]

**Pull request merged**
