### PR TITLE
Revert "Delete flaky flutter_gallery XCUITest"

### PR DESCRIPTION
**Pull request by christopherfujino**
Reverts flutter/flutter#103666

Missed a file https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8814261726166927201/+/u/run_native_ui_tests_ios/test_stderr

### CODE REVIEW

**Comment by christopherfujino** [comment]
Landing this TBR @jmagman or @justinmc as this is at the tip of the tree and to green the tree

**Comment by christopherfujino** [comment]
Oh, I guess I can't land it TBR

**Comment by jmagman** [comment]
Would prefer to fix forward https://github.com/flutter/flutter/pull/103727

**Review by jmagman — APPROVED** [review]
LGTM

**Pull request merged**
