### PR TITLE
First step to optimise refresh_indicator for Dart2 

### PR DESCRIPTION
**Pull request by lasseschmitt**
After I got errors regarding type casting in with the current master and dart2. I have changed all `Future<Null>` to `Future<void>`

And also the generic type of `Completer<Null>` to `Completer<void>`

### CODE REVIEW

**Comment by DrivEddy** [comment]
I signed it!

**Comment by Hixie** [comment]
It's actually not clear that this is the right thing to do. `void` is a bit of a weird type, in that it means `dynamic` but can't be read. So the problem with `<void>` is that you can return values to it, and they just get dropped with no warning from the analyzer.

cc @leafpetersen @munificent 

@lasseschmitt Anyway, if we do want to do this, the first step will be to resolve the analyzer warnings that this found. Let me know if you're interested in doing this.

**Comment by leafpetersen** [comment]
I'm not sure of all of the context here, so it's possible that this is a good use case for `Future<Null>`.  In general though, `Future<Null>` was a workaround for not having `Future<void>`.

It's true that `Future<void>` that you can accidentally return values into `void` Futures, so if that is the primary concern then `Future<Null>` is your friend, since it will insist that you only return `null` to it.  Usually though, the problem is the opposite: the code correctly doesn't return anything meaningful (either `null` or something arbitrary), but since `Future<Null>` is a subtype of any `Future` you can accidentally use the resulting `Future` anywhere you want with no static warnings.

```
Future<Null> ignoreMe() {
  return null;
}

void main() {
  Future<int> x = ignoreMe();
  await x.then((a) => a.isEven);
}
```

**Comment by Hixie** [comment]
Filed https://github.com/dart-lang/sdk/issues/32827

**Comment by Hixie** [comment]
@lasseschmitt Sorry for the delay. We now have a lint that makes me more confident about applying your patch, so I think we should go ahead with your change.

There appear to be some test failures. Any chance you could update your PR to address those?

**Comment by Hixie** [comment]
@lasseschmitt Will you be able to continue working on this? It's totally fine if not; we can take it over (though it might take longer). I'm just asking because I'm trying to clean out our review queue.

**Comment by Hixie** [comment]
@lasseschmitt I'm going to close this PR since you're not working on it right now, but if you have time to come back to it please don't hesitate to reopen or open a new one or whatever, and if you need anything please don't hesitate to cc me. Thanks!

**Comment by jslavitz** [comment]
@leafpetersen Looks like this fix has already been made so I'm closing this PR!

**Pull request closed without merging**
