### PR TITLE
Update engine and Mojo usage

### PR DESCRIPTION
**Pull request by abarth**
@pylaligand

### CODE REVIEW

**Comment by abarth** [comment]
@tvolkert

**Comment by abarth** [comment]
This breaks the way we used to mock services.  Going to need some more thought.

**Comment by tvolkert** [comment]
is the travis failure real?

**Comment by abarth** [comment]
> is the travis failure real?

Yes.  The mojo update breaks how we mock out Mojo services.  If it's getting in your way, feel free to revert the mojo roll in engine.git.  Otherwise, I'll work out a way to mock services with the new APIs.

**Pull request merged**
