### PR TITLE
Re-enable hostonly tests on non-master branches

### PR DESCRIPTION
**Pull request by tvolkert**
## Description

This is a follow-on to https://github.com/flutter/flutter/pull/45455 - the test failures indicated a real problem, so re-enabling the tests on non-master.

## Related Issues

https://github.com/flutter/flutter/issues/45453

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by tvolkert** [comment]
@Hixie @fkorotkov

**Comment by fkorotkov** [comment]
LGTM

BTW I remember seen branches like `revert-some-change`. Seems checks will be ignored for such reverts with that logic. But if you create a PR from such branches then it should be fine.

**Comment by tvolkert** [comment]
Yup, we create PRs from such branches.

**Comment by tvolkert** [comment]
Per the discussion in #45453, the failing tests indicated a real problem on non-master, so I'm gonna  close this and revert #45455

**Comment by tvolkert** [comment]
Argh, the revert contained some code that should still be around, so manually reverting the right stuff here instead.

**Review by xster — APPROVED** [review]

**Pull request merged**
