### PR TITLE
Use incremental installation

### LINKED ISSUE #46198: Enable incremental installation by default
Per discussion in https://github.com/FirebaseExtended/flutterfire/issues/349, we can improve build times for `flutter create` devs by enabling incremental installation in the Podfile.

Potential downsides:
- Requires CocoaPods 1.7.0
- Possibly slightly longer initial builds

### PR DESCRIPTION
**Pull request by collinjackson**
## Description

This PR updates Flutter's Podfile templates to enable incremental installation by default. This may increase the speed of subsequent iOS builds when complex plugins like Firestore are being used, because Flutter won't need to recompile all the plugins when a new one is added.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/46198

## Tests

There should be no functional change here, just increased performance. I think that this should be covered by build time performance benchmarks.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jmagman — CHANGES_REQUESTED** [review]
I'm worried about this caveat:
> Warning: Switching your project to use multiple .xcodeproj may result in some compiler errors if your pods have relied on importing headers using the quote syntax for its dependencies. For example #import "PDDebugger.h" will no longer work in a pod that depends on PonyDebugger. Instead, we highly suggest you update your headers to correctly import the framework and its associated header: #import <PonyDebugger/PDDebugger.h>. This is intentional since this feature is currently opt-in.

http://blog.cocoapods.org/CocoaPods-1.7.0-beta/

I suspect many pods use the project `#import "PDDebugger.h` instead of the correct system `#import <PonyDebugger/PDDebugger.h>` and in fact our own registration template did this up until https://github.com/flutter/flutter/pull/10259/files#diff-fb912d7008f6a340a5c4584a6ee1ae85L130

Can we default this to being commented out with a comment about suggesting to turn it on to speed up compilation time?  Similar to how we used to have `use_framework!`

**Comment by goderbauer** [comment]
Is this PR still relevant? Or should we close it?

**Comment by jmagman** [comment]
@collinjackson I think this is a good change if it's commented out with a comment above it about when to uncomment it, like:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/cocoapods/Podfile-ios-objc#L1

**Comment by xster** [comment]
ping @collinjackson to follow up on Jenn's comments

**Comment by collinjackson** [comment]
Closing this for now to get it out of the review queue, I want to do a more thorough investigation before landing.

**Pull request closed without merging**
