### PR TITLE
Use fs.identical to compare paths when finding the engine source path

### PR DESCRIPTION
**Pull request by jason-simmons**
This will handle paths with symlinks that resolve to the same location.

### CODE REVIEW

**Comment by DanTup** [comment]
Drive-by question... I'd never seen this method before, but it sounded useful so I looked it up, but the docs say "Comparing a link to its target returns false, as does comparing two links that point to the same target"... I'm not sure if this is different to what you said (and, if so, what this method actually does do?)

**Comment by jason-simmons** [comment]
The improvement here comes from the "Directory links appearing inside a path are followed, though, to find the file system object." feature (https://pub.dartlang.org/documentation/file/latest/file/FileSystem/identicalSync.html)

On my setup I was running Flutter from a directory like `/symlink/flutter`.  The flutter_tools code that locates `sky_engine` mapped the package to `/target_of_symlink/flutter`.  Unlike a string comparison, `FileSystem.identical` will consider those paths to point to the same object.

**Comment by DanTup** [comment]
@jason-simmons Aha, got it, makes senes! Thanks for the info :-)

**Review by gspencergoog — COMMENTED** [review]
Is there any way to test this?  Couldn't you set up a symlink and see if it gets the right engine path?

**Comment by jason-simmons** [comment]
Added a test

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Pull request merged**
