### PR TITLE
Fix docs for TabBar indicator

### LINKED ISSUE #57970: TabBar docs missing how indicator behaves with Theme
The `TabBar` docs mention:

```dart
  /// If [indicator] is not null, then [indicatorWeight], [indicatorPadding], and
  /// [indicatorColor] are ignored.
```

But it fails to remind the user that an `indicator` can be provided into the App's theme using `TabBarTheme`, in that case the internal reference `_indicator` won't be null and `indicatorColor` and the others will be ignored. This brings confusion as the `TabBar` `indicator` property was indeed `null`, but the `TabBar` got an `indicator` from the App's `Theme`.

I suggest that the docs get updated to include this case or the behavior of the `TabBar` be updated to match its docs.

### PR DESCRIPTION
**Pull request by JuYeong0413**
## Description

Updated `TabBar` docs
Remind the user that an `indicator` can be provided from the App's theme by using `TabBarTheme`.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/57970

## Tests

None - only docs were touched.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Thank you for the contribution! This is a helpful doc tweak. Can you also add this clarification to the properties' documentation below, where it also mentions the indicator's effect on the individual properties?

It looks like that would be indicatorColor, indicatorWeight, indicatorPadding, & indicator.

**Comment by JuYeong0413** [comment]
Thank you @Piinks! It seems like there are already existing mentions of the indicator's effect on the individual properties.
These are the lines:
- [indicatorColor](https://github.com/flutter/flutter/blob/cfc0082db7e4cb1ec9da9cbf29fb7ecc5788ca13/packages/flutter/lib/src/material/tabs.dart#L650)
- [indicatorWeight](https://github.com/flutter/flutter/blob/cfc0082db7e4cb1ec9da9cbf29fb7ecc5788ca13/packages/flutter/lib/src/material/tabs.dart#L658)
- [indicatorPadding](https://github.com/flutter/flutter/blob/cfc0082db7e4cb1ec9da9cbf29fb7ecc5788ca13/packages/flutter/lib/src/material/tabs.dart#L672)
- [indicator](https://github.com/flutter/flutter/blob/cfc0082db7e4cb1ec9da9cbf29fb7ecc5788ca13/packages/flutter/lib/src/material/tabs.dart#L677#L678)

Please let me know if any updates are required. :)

**Review by Piinks — COMMENTED** [review]
Thanks for the update! I meant adding to those about the Theme implications, just like you are adding here in the higher level docs.. the ' or provided from [TabBarTheme],'?

**Comment by JuYeong0413** [comment]
Oh, sorry for the misunderstanding.
I updated all of those properties. Thank you.

**Review by Piinks — APPROVED** [review]
Awesome! LGTM! Thank you for the contribution. It looks like your branch needs to be updated with the latest changes from master in order to fix the failing checks.

**Comment by JuYeong0413** [comment]
Thank you :)
I force-pushed after rebasing my branch.

**Pull request merged**
