### PR TITLE
Add Spell Check to Editable Text (iOS)

### PR DESCRIPTION
**Pull request by camsim99**
Adds spell check integration for iOS and modifies documentation to include support for iOS.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
(Triage): @camsim99 do you still have plans for this PR in the near future?

**Comment by camsim99** [comment]
> (Triage): @camsim99 do you still have plans for this PR in the near future?

Yes, it's been blocked my some other issues, but I should return to it within the week.

**Review by justinmc — APPROVED** [review]
LGTM 👍  But to make sure I know what I'm looking at, you're just adding this because the engine side is good to go for iOS?  So it should work the same as Android now (no UI)?

Also, how does the integration test work?

**Comment by camsim99** [comment]
> LGTM 👍 But to make sure I know what I'm looking at, you're just adding this because the engine side is good to go for iOS? So it should work the same as Android now (no UI)?
> 
> Also, how does the integration test work?

Yes, the test should work the same on both! There is some UI but I'm not using an inferred `SpellCheckConfiguration`, so it will look the same.  I forgot I needed to add an additional task for iOS, so I just did that. I'll make sure it passes on this PR before submitting it.

**Comment by camsim99** [comment]
@cyanglaz Would you mind taking a look at this to double check I set up the task correctly?

**Review by cyanglaz — APPROVED** [review]
LGTM

**Pull request merged**
