### PR TITLE
Delete obsolete TODO and skip

### PR DESCRIPTION
**Pull request by dnfield**
This has been fixed.

### CODE REVIEW

**Review by Piinks — APPROVED** [review]
LGTM!

**Comment by Piinks** [comment]
See #55409 for reference.

**Comment by dnfield** [comment]
I think that was for a different one of these - #66289 is the todo this is fixing

**Comment by Piinks** [comment]
> I think that was for a different one of these - #66289 is the todo this is fixing

Oh whoops! You've been closing out so many TODOs I mixed them up! 😋  👍  🎉

**Pull request merged**
