### PR TITLE
Roll engine with dart roll 20171201

### PR DESCRIPTION
**Pull request by aam**

### CODE REVIEW

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm

**Comment by xster** [comment]
Do you mind rolling one commit further? :) So I don't have to roll again right after :)

**Comment by aam** [comment]
@xster , sure, if your engine mac build finishes before my travis CI build. :-) Those engine mac build seem to take forever(upward to hour and a half) :(

**Comment by aam** [comment]
@xster, sorry travis build is done, but mac engine build is still going.

**Comment by Hixie** [comment]
This regressed basic_material_app_android__compile release_full_compile_millis__preview_dart_2 pretty badly.

**Comment by aam** [comment]
there were 88 dart commits since yesterday's roll: `git log edf890f30cb465f508933d065a60147f1cd3e038..48a927acb2dc4178691b4ddfa817e87043e30b01`
@sivachandra @alexmarkov any thoughts on changes that could have affected kernel release build?

**Comment by sivachandra** [comment]
AFAIU, my change to gen_snapshot (now fixed on dart ToT), should lead to an an uncaught exception but should not have any negative effect. That said, I could be wrong as I only tested the flutter gallery example.

Are there any logs to take a look at to see the symptoms of the regression?

**Comment by aam** [comment]
> Are there any logs to take a look at to see the symptoms of the regression?

I don't think there are any logs available that could be useful to understand the cause of performance regression of preview-dart-2 release compile. I would imagine if there are ideas regarding what cls could have caused the regression we could try them locally by rerunning benchmark with cl reverted locally. If there are no ideas, there is always a bisect.

**Comment by sivachandra** [comment]
Ah, so this is only a performance regression then?

**Comment by aam** [comment]
> Ah, so this is only a performance regression then?

Yes, 15-20% regression in compilation time(which is basically frontend dart to kernel compilation + gen_snapshot from kernel file).

**Comment by sivachandra** [comment]
OK, thanks. I do not have any knowledge about changes affecting compilation time.

**Comment by aam** [comment]
Culprit of the performance regression is actually 124d592f595038da8c424e7bfd790bfa9d7a7583, @sivachandra . The fix for it is already - 4a19ab4e22373f5e4987546d7b95bd34da390eca, so hopefully today's roll will fix the regression.

**Comment by aam** [comment]
@cbracken , do you think we should fail build aot on missing deps file instead of printTrace'ing here https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/build_aot.dart#L449 ?

**Comment by cbracken** [comment]
@aam I think it's a great idea to check for specific conditions that we know we should never it and abort if they're detected.

**Pull request merged**
