### PR TITLE
migrate animated_placeholder_perf to e2e

### PR DESCRIPTION
**Pull request by CareF**
## Description

This is break down of #62171, and should be merged when devicelab is of low load.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by liyuqian** [comment]
@CareF : as we're migrating more macrobenchmarks to e2e, I wonder if we should also update https://github.com/flutter/flutter/wiki/How-to-write-a-render-speed-test-for-Flutter. Can you please have a first round of edit? I'll follow up and make revisions as well.

**Comment by CareF** [comment]
> @CareF : as we're migrating more macrobenchmarks to e2e, I wonder if we should also update https://github.com/flutter/flutter/wiki/How-to-write-a-render-speed-test-for-Flutter. Can you please have a first round of edit? I'll follow up and make revisions as well.

@liyuqian I no longer have the permission to edit the Wiki page. I would recommend mark section 4 deprecated and use the following: 

To keep Flutter performant, running a test locally once in a while and check the metrics manually is insufficient. The following steps let the [devicelab][] run the test automatically for every Flutter commit so performance regressions or speedups for the `super_important_case` can be detected quickly.

1. Add `super_important_case_perf__e2e_summary` to [dev/devicelab/manifest.yaml][] under `tasks`. Follow other tasks to properly set descriptions and choose agent such as `linux/android` (Moto G4) or `mac/ios` (iPhone 6s).

2. Add `super_important_case_perf__e2e_summary.dart` to [dev/devicelab/bin/tasks][] with a content like

   ```Dart
   import 'dart:async';

   import 'package:flutter_devicelab/tasks/perf_tests.dart';
   import 'package:flutter_devicelab/framework/adb.dart';
   import 'package:flutter_devicelab/framework/framework.dart';

   Future<void> main() async {
     deviceOperatingSystem = DeviceOperatingSystem.android;  // or ios
     await task(createSuperImportantCasePerfE2ETest());
   }
   ```

3. Add the following `createSuperImportantCasePerfTest` function to [dev/devicelab/lib/tasks/perf_tests.dart][]

   ```Dart
   TaskFunction createSuperImportantCasePerfE2ETest() {
     return PerfTest.e2e(
       '${flutterDirectory.path}/dev/benchmarks/macrobenchmarks',
       'test/super_important_case_e2e.dart',
     ).run;
   }
   ```

4. Locally test the devicelab task by running `../../bin/cache/dart-sdk/bin/dart bin/run.dart -t super_important_case_perf__e2e_summary` inside the [dev/devicelab][devicelab] directory with an Android or iOS device connected. You should see a success and a summary of metrics being printed out.

5. Submit a pull request of everything above.

6. Finally, remove `flaky: true` once the test is proven to be reliable for a few days. Since this may take a while, creating a reminder calendar event could be a good idea.

**Comment by CareF** [comment]
And the code block in section 2 should be changed to: 

```Dart
// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/gestures.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:macrobenchmarks/common.dart';

import 'util.dart';

void main() {
  macroPerfTestE2E(
    'super_important_case',
    kSuperImportantCaseRouteName,
    pageDelay: const Duration(seconds: 1),
    /* optional */ body: (WidgetController controller) async {
        ...
    }, 
    /* optional */ setup: (WidgetController controller) async {
        ...
    }, 
  );
}
```

**Comment by liyuqian** [comment]
Losing the edit permission must be an accident. Ray just added you back (sent an invitation), can you please check if that fixes the problem?

In addition to the 2 changes you mentioned above, I wonder if macrobenchmarks could also have hybrid benchmarks as we had in gallery. The hybrid one might be useful if we want to get CPU/GPU/memory usages from the Timeline which is currently unavailable from `FrameTiming`.

**Comment by CareF** [comment]
> Losing the edit permission must be an accident. Ray just added you back (sent an invitation), can you please check if that fixes the problem?
> 
> In addition to the 2 changes you mentioned above, I wonder if macrobenchmarks could also have hybrid benchmarks as we had in gallery. The hybrid one might be useful if we want to get CPU/GPU/memory usages from the Timeline which is currently unavailable from `FrameTiming`.

It fixes and I updated my modification to the wiki. 

The hybrid gallery test `flutter_gallery__transition_perf_hybrid` is definitely do-able, but it's quite away from the current e2e solution, since `flutter_gallery__transition_perf_hybrid` is not using e2e but just `LiveWidgetController` for input injection. It's a work-around, and is either still heavily replies on flutter driver binding, or cannot report test success/fail.

**Review by liyuqian — COMMENTED** [review]
I think the hybrid might be useful for CPU/GPU/memory metrics which is currently unavailable in e2e without reading the Timeline. It may be nice to use the same input injection for a normal e2e test, and a hybrid test for getting CPU/GPU/memory before we made them available outside of Timeline.

But that's not blocking anything here. The wiki update looks good and I made a few edits to add some missing links.

LGTM for this PR.

**Review by liyuqian — APPROVED** [review]

**Pull request merged**
