### PR TITLE
Correct scrollable tabs fling velocity

### LINKED ISSUE #7133: gallery colors demo scrolling tabs
Hello,

In the Colors demo of the gallery app, when you scroll only the tabs, we jump from the first color tab ("red") to the last color tab ("blue grey)" directly,

I think it is the same problem than #6618 and the problem of scrolling you can observe in the licences panel of gallery app.

I test on Android 6.0.1 on nexus 5.

I know that @Hixie is refactoring scrolling. I'm looking forward for this feature!! Do you have an idea when it will be available?
Thank you

### PR DESCRIPTION
**Pull request by HansMuller**
Fixes #7133

### CODE REVIEW

**Comment by Hixie** [comment]
Assuming the incoming `velocity` is in pixels per second, LGTM.

**Comment by lequem** [comment]
@Hixie according to your comment, do you think this kind of fix could resolve the scroll issue we can observe in the licenses panel of the gallery app?
@HansMuller are your aware of this issue?

When we go into the licenses panel of the gallery application (after clicking "view licenses"), the scroll "jump".
I observe this behavior with a nexus 5 on Android 6.0.1

Vincent

**Comment by Hixie** [comment]
I haven't looked into the lazy block scrolling issue, though I am aware of it. I'm rewriting that code so it may become moot.

**Comment by lequem** [comment]
ok thank you.
I'm looking forward your work. I hope it will be available soon!

**Pull request merged**
