### PR TITLE
Add Swift and Kotlin templates

### PR DESCRIPTION
**Pull request by mravn-google**
Go modern with 
```
flutter create --ios-language=swift --android-language=kotlin hello
flutter create --plugin --ios-language=swift --android-language=kotlin hello
```
Default languages are `objc` and `java`.

### CODE REVIEW

**Comment by mravn-google** [comment]
Fixes https://github.com/flutter/flutter/issues/7312

**Review by jakobr-google — APPROVED** [review]
Generally LGTM, but could we maybe keep all the files that are identical (icons, etc.) in a common directory?

So you'd have:

  `ios.tmpl/` -- files shared between Obj-C and Swift templates
  `ios-objc.tmpl/` -- Obj-C-specific files
  `ios-swift.tmpl/` -- Swift-specific files

And similar for Android. I think that should work with the current code, and we'd avoid having several copies of especially the binary files.

**Comment by mit-mit** [comment]
I wonder if we could abbreviate to just: `--swift` and `--kotlin`. I guess that wouldn't work if someday there way a single language that both iOS and Android supported, but I don't think that is super likely to happen...

**Comment by mravn-google** [comment]
@jakobr-google Yes, good point.

@mit-mit There are some minor wrinkles with the simpler `--swift` and `--kotlin` approach:

1. As you mention, `--some-great-language` may at some point become a supported language on more than one platform. Perhaps not very likely now, but we may have additional platforms too.
1. We should probably allow `--objc` and `--java` flags as well to allow people to be explicit (e.g. when posting help) and to allow scripts and test code to handle all languages uniformly.
1. Even if not, a third language option on one platform would require us to detect and fail on inconsistencies such as `flutter create --kotlin --scala hello`. This cross-option consistency condition is a bit awkward to document, and likely leads to duplicated information that must be updated consistently when the language landscape changes.

All minor objections of course (on the other hand, people need to write `--android-language` only once per project).

**Comment by mravn-google** [comment]
We might also consider abbreviated forms of the long-hand options, e.g. `-al kotlin -il swift`.

**Comment by mit-mit** [comment]
> We might also consider abbreviated forms of the long-hand options, e.g. -al kotlin -il swift.

Yes, that sounds like a great compromise!

**Comment by mravn-google** [comment]
Oh, no. We are not allowed to have two-letter abbreviations.

**Comment by mravn-google** [comment]
```
flutter create          -i swift -a kotlin hello
flutter create --plugin -i swift -a kotlin hello
```

**Review by mit-mit — APPROVED** [review]
Love it, thanks so much!

**Pull request merged**
