### PR TITLE
Add a sliver-based ScrollView

### PR DESCRIPTION
**Pull request by abarth**
This patch introduces ScrollView, which is a convenience widget for using a
SliverBlock. This patch also switches a number of clients from Block to
ScrollView. Once we support more features of block (e.g., padding and
shrinkwrapping), we'll be able to move over more clients.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

**Comment by abarth** [comment]
There's something wrong with hit testing.

**Comment by abarth** [comment]
I think I've fixed the hit testing.

**Comment by abarth** [comment]
Before landing, I'll split the bug fixes out from the mass conversion of Block clients.  Most likely we'll need to fix the clipping issue before converting so many clients.

**Comment by abarth** [comment]
This patch is ready for review now.

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
