### PR TITLE
[CP] Stable AGP 8.0 minification support when using integration_test package

### PR DESCRIPTION
**Pull request by reidbaker**
- Support minification for apps that depend on AGP 8 and integration_test (#127628)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by CaseyHillers** [comment]
@reidbaker this CP PR isn't mergeable in its current state. Can you rebase to only include the commit you are cherrypicking?

**Comment by CaseyHillers** [comment]
@camsim99 @gmackall  is this something you want to take over while Reid is OOO?

**Comment by camsim99** [comment]
> It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need [an exemption](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests) to this rule, contact Hixie on the #hackers channel in [Chat](https://github.com/flutter/flutter/wiki/Chat) (don't just cc him here, he won't see it! _He's on Discord!_).
> 
> If you are not sure if you need tests, consider this rule of thumb: the purpose of a test is to make sure someone doesn't accidentally revert the fix. Ask yourself, **is there anything in your PR that you feel it is important we not accidentally revert back to how it was before your fix?**
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.

This change has a test exemption on the original PR: https://github.com/flutter/flutter/pull/127628#issuecomment-1563648944

**Review by stuartmorgan-g — APPROVED** [review]
LGTM

**Review by gmackall — APPROVED** [review]

**Pull request merged**
