### PR TITLE
Only download the sky_engine package when needed.

### PR DESCRIPTION
**Pull request by pylaligand**

### CODE REVIEW

**Comment by pylaligand** [comment]
Not sure if this is the best solution, but on Fuchsia the pub executable is not available where the flutter tool expects it - and we don't need pub anyways.

I'm starting to think that instead of using the regular flutter tool we should build a slimmer version that only exposes the functionality currently in "flutter build mojo".

**Comment by pylaligand** [comment]
It looks like this is interfering with tests. Updating...

**Comment by eseidelGoogle** [comment]
@danrubel is a useful resource for you for flutter_tools changes and reviews. :)

**Comment by pylaligand** [comment]
Alternative implemented at:
https://github.com/flutter/flutter/pull/6159
https://github.com/flutter/engine/pull/3084

**Comment by abarth** [comment]
https://github.com/flutter/flutter/pull/6159 looks like a much cleaner approach.  Let's go with that one.

**Comment by pylaligand** [comment]
Agreed.

**Pull request closed without merging**
