### PR TITLE
Updated some links

### PR DESCRIPTION
**Pull request by LorenzNickel**
## Description

I crawled the repository for outdated links and I found those which are replace or removed by this pull request. I did everything possible for me to find the new locations of the files, but if I couldn't find it, I removed the link. If I did a mistake here feel free to let me know and I'll add/change it.

I also wanted to point out that [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scroll_physics.dart#L371) is a repository linked which I can't see. Maybe it's just private or it's deleted. Anyway, I didn't know how to proceed with it (because I can't just delete the link or step one, the whole part wouldn't make sense without out. Second thing that in the last line of [this file](https://github.com/flutter/flutter/blob/master/examples/stocks/README.md) you link to a website which is 'under maintenance', but I don't know if it will ever come back online. I just wanted to let you know that the link is currently not working, also probably you shouldn't care about it too much.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by tvolkert** [comment]
Generally LGTM, but it concerns me that the Dart articles have disappeared.  I've reached out to the `dart.dev` owners to find out why that's the case.  Let's hold off on merging until we find out the intended fate of those articles.

**Comment by tvolkert** [comment]
FYI @kwalrath

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by tvolkert** [comment]
FYI, sounds like the articles are going to be added back to dart.dev, so I recommend updating the PR to keep the [temporarily broken] articles, and we can send a separate PR to update them to point to their new locations once they're live.

**Comment by LorenzNickel** [comment]
Done.

**Review by tvolkert — APPROVED** [review]
LGTM

**Pull request merged**
