### PR TITLE
Roll engine to c903c217a1a8206cdebdab1703b52ec6180edf37.

### PR DESCRIPTION
**Pull request by aam**
This is to pick up updated dart roll.

### CODE REVIEW

**Review by bkonyi — APPROVED** [review]
LGTM

**Review by tvolkert — APPROVED** [review]

**Comment by Hixie** [comment]
This regressed analyzer performance.

**Comment by a-siva** [comment]
I have filed https://github.com/dart-lang/sdk/issues/32769 against the analyzer team to track this regression.

**Comment by Hixie** [comment]
This also looks to have regressed dartdoc performance. cc @jcollins-g

**Comment by Hixie** [comment]
This also regressed microbenchmarks stock_build_iteration and made it a lot more noisy.

**Comment by a-siva** [comment]
It could be because of
7d90df42f1 [Kernel, VM runtime] Hook up bool checks in strong mode (fixes #32336). Update kernel status file.
Additional runtime type checks were added to address a strong mode language issue https://github.com/dart-lang/sdk/issues/32336

We probably need to see if global type propagation will help eliminate this check.

**Pull request merged**
