### PR TITLE
Improve Windows build failure message

### PR DESCRIPTION
**Pull request by GroovinChip**
## Description

This PR improves the build failure message for Windows build targets. It suggests that the user run `flutter run -d windows -v` to see a stack trace, and if that does not help the user solve the build failure it prompts the user to open an issue.

## Related Issues

Contributes to, but does not fully address, #33583

## Tests

This PR does not change any behavior.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by GroovinChip** [comment]
@jonahwilliams Review please? Can't do it officially as I'm not a contributor.

**Review by jonahwilliams — CHANGES_REQUESTED** [review]
Please remove:  `please file an issue at https://github.com/flutter/flutter/issues/new/choose`. Since this error could be anything from a flutter build error to a reconfigured app to a compilation error in platfrom code it doesn't really provide any more signal.

**Comment by GroovinChip** [comment]
Done

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Thank you for the contribution @GroovinChip !

**Comment by GroovinChip** [comment]
You're very welcome @jonahwilliams  :D

**Comment by GroovinChip** [comment]
To further goal of making Windows build logs available in the console, would it make sense to take the `stderr` from the following code and print it?

build_windows.dart:
```dart
  try {
    process.stderr
      .transform(utf8.decoder)
      .transform(const LineSplitter())
      .listen(printError);
    process.stdout
      .transform(utf8.decoder)
      .transform(const LineSplitter())
      .listen(printTrace);
    result = await process.exitCode;
  } finally {
    status.cancel();
  }
```

`stderr` is defined in process.dart as:
```dart
  /**
   * Returns the standard error stream of the process as a [:Stream:].
   */
  Stream<List<int>> get stderr;
```

**Comment by jonahwilliams** [comment]
printError should already show up in the console above this message (if there was anything). It's possible we're dropping something on the floor before that. We would have to manually buffer to stderr output.

**Comment by GroovinChip** [comment]
So, somewhere in here, then?
```dart
  final Process process = await processManager.start(<String>[
    buildScript,
    vcvarsScript,
    fs.path.basename(solutionPath),
    configuration,
  ], workingDirectory: fs.path.dirname(solutionPath));
```
I know that the `buildScript` is `vs_build.bat` but that simply calls `vcvars64.bat` as far as I can tell.

**Comment by jonahwilliams** [comment]
That process call should already be logging all of the stderr. But it might be the case that we're not running the msbuild with the right verbosity. Let's land this change now, since it is simpler, and go further down the rabbit hole separately.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Pull request merged**
