### PR TITLE
Plumb --local-engine flag through to LOCAL_ENGINE in Local.xcconfig

### LINKED ISSUE #4186: flutter build ios --local-engine workflow broken
```
~flutter $ git clean -fdx
...
~flutter $ cd examples/hello_world/
~flutter/examples/hello_world $ flutter upgrade
...
~flutter/examples/hello_world $ pub get
...
~flutter/examples/hello_world $ flutter build aot --target-platform=ios --release
Missing files: [~flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot, ~flutter/bin/cache/artifacts/engine/ios-release/dart_vm_entry_points.txt, ~flutter/bin/cache/artifacts/engine/ios-release/snapshot.dart]
```

### PR DESCRIPTION
**Pull request by tvolkert**
Fixes #4186

### CODE REVIEW

**Comment by tvolkert** [comment]
@abarth @chinmaygarde

**Comment by abarth** [comment]
LGTM

I take it the environment variable approach didn't work.  Should we revert my patch that added it?

**Comment by tvolkert** [comment]
It didn't work when the app is launched via XCode.  It may still be needed for when it's launched strictly via the tools - I haven't tried that path yet.

**Comment by abarth** [comment]
The two mechanisms seem redundant.  If there's a requirement to be able to use local engine builds from the Xcode UI, then we should revert my patch and just go with your patch.

**Comment by tvolkert** [comment]
sgtm - I'll revert it

**Pull request merged**
