### PR TITLE
Make TabController communicating creation in constructor.

### PR DESCRIPTION
**Pull request by polina-c**
Contributes to https://github.com/flutter/flutter/issues/144910

### CODE REVIEW

**Comment by polina-c** [comment]
Test coverage is not needed because this PR is to improve troubleshooting.

**Comment by Hixie** [comment]
I don't quite understand why we wouldn't want to test this? It seems like we should test that all ChangeNotifiers are properly calling this. After all, if someone removes this code, that is a regression we would want to catch, no?

**Comment by polina-c** [comment]
> I don't quite understand why we wouldn't want to test this? It seems like we should test that all ChangeNotifiers are properly calling this. After all, if someone removes this code, that is a regression we would want to catch, no?

Removal of this code will result in more complicated troubleshooting. 

ChangeNotifiers that leaks make this call anyway in 'addListener'. Making it in constructor instead will make troubleshooting easier, because will give creation call stack for a leaking object. 

See description: https://github.com/dart-lang/leak_tracker/blob/main/doc/leak_tracking/TROUBLESHOOT.md#1-it-is-not-clear-who-owns-changenotifier

It is hard to test cover, because the class is internal and complexity of making it testable does not worth it. 

Does it help?

**Comment by Hixie** [comment]
We should definitely consider more complicated troubleshooting to be a regression.

That said, I agree with you that this code is virtually impossible to test without a change to Dart to allow privates to be tested. Hopefully one day we'll have that, but that day is not today.

test-exempt: testing this requires a change to Dart or a change to the API; changing the API is not desired for this code.

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
