### PR TITLE
Xcode 8-compatible provisioning profiles in devicelab tests

### PR DESCRIPTION
**Pull request by yjbanov**
This PR will require that I take the iOS part of the devicelab down to upgrade to Xcode 8 and reconfooble the provisiony things.

### CODE REVIEW

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm

**Comment by Hixie** [comment]
This did very odd things to the performance benchmarks.

**Comment by cbracken** [comment]
@yjbanov can confirm, but I believe this corrected some previously-odd benchmarks.

**Comment by yjbanov** [comment]
Yes, in the old Xcode7/iOS9 world our timeline data used to be partial. In the new Xcode8/iOS10 we are getting a complete timeline. The new numbers should be more accurate.

**Comment by yjbanov** [comment]
Here's the [relevant issue](https://github.com/flutter/flutter/issues/6477), which I'm tempted to close now.

**Comment by Hixie** [comment]
Excellent.

**Pull request merged**
