### PR TITLE
Add material localizations for keyboard keys used for shortcut descriptions in menus.

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

This change adds some localizations for keyboard keys that will be used in creating shortcut descriptions in menus.

## Related Issues
 - https://github.com/flutter/flutter/issues/23600

## Tests
 - Added tests for new strings.

### CODE REVIEW

**Comment by jmagman** [comment]
Unfortunately you hit https://github.com/flutter/flutter/issues/99036, please rebase onto https://github.com/flutter/flutter/pull/99037.

**Comment by gspencergoog** [comment]
@jmagman , thanks, will do!

**Review by HansMuller — APPROVED** [review]
LGTM.

Currently the analyzer is complaining about trailing white space.

**Comment by gspencergoog** [comment]
Merging even though "Google Testing" is red, since this PR contains files that are too large for FROB to handle, so it's not even running the tests.

**Pull request merged**
