### PR TITLE
Fixed reloading placeholder in case of loading image error

### LINKED ISSUE #26843: Image placeholders load incorrectly when returning from other screen
Inside Scroll Layout, if a list of elements with images is visible, and the screen is changed, and returned back, images that previously held a placeholder now have a an image of other element from the list. This issue happens f. e. when image fails to load and a placeholder is displayed.

## Steps to Reproduce

1. Create view with placeholder image inside
2. Embedd created view inside scrolling layout
3. Push another view on top of the one with scroll
4. Return back to previous view

## Logs

There is no log output related to issue
```
   info • Unused import: 'package:flutter_platform_widgets/flutter_platform_widgets.dart' •
          lib/ui/home/Home.dart:3:8 • unused_import

1 issue found. (ran in 12.7s)
```
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale pl-PL)
    • Flutter version 1.0.0 at /usr/local/Cellar/flutter/1.0.0
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/igor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/igor/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available
```

### PR DESCRIPTION
**Pull request by wodzu96**
Fixes [#26843](https://github.com/flutter/flutter/issues/26843) . This issue was the result of not changing state in case of error in downloading picture. Authors of this library founded that image can only replace placeholder but there is case wherein image can be replaced by placeholder. 
In my fix i'm handling error with downloading picture and in this case i'm putting placeholder.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Please add more context to your PR, including a description of how you are changing the behavior to fix the error in question.

**Comment by jonahwilliams** [comment]
Please also add a test case to fade_in_image_test.dart which verifies an image that fails to load does not remove the placeholder

**Comment by goderbauer** [comment]
@wodzu96 do you have some time in the near future to follow up on the comments posted above?

**Comment by wodzu96** [comment]
@goderbauer please give me one week and i will commit tests ;D

**Comment by goderbauer** [comment]
@wodzu96 Friendly ping. Are you still interested in this?

**Comment by goderbauer** [comment]
@wodzu96 Looks like there hasn't been any activity on this one in a while. I am going to close this one for now. If you ever find the time to address the comment above feel free to reopen and we will review it.

**Pull request closed without merging**
