### PR TITLE
Rearrange the Pesto internals

### PR DESCRIPTION
**Pull request by HansMuller**
Despite appearances, this is only a modest change to the pesto demo.
- Scrollables specify a global key to ensure that when the route they're on is recreated, their scroll position is restored. Define separate classes for the pesto home and favorites pages, each with its own scrollable key.
- Changed the way pesto text styles are defined.
- Moved the demo into subdirectory, split the recipe types data into a separate file.
- Many gratuitous name changes. Nearly all of the logic just as it was.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @mpcomplete

**Comment by mpcomplete** [comment]
Is it possible to break this up into:
1. Changes to current file.
2. Move to new files?

It's impossible to see what changed otherwise.

**Comment by HansMuller** [comment]
I'll try and push a version that doesn't MIRV

**Comment by mpcomplete** [comment]
Thanks, LGTM.

IMO it's better as one file. As soon as multiple files are involved, it transforms from lightweight demo to complicated app.

**Comment by HansMuller** [comment]
OK, then one file it will be.

**Pull request merged**
