### PR TITLE
✨ Android Q transition by default

### LINKED ISSUE #43277: Make Android 10 Activity Animation the default animation
After https://github.com/flutter/flutter/pull/41935 lands, we should default material page transitions to the newer animation.

### PR DESCRIPTION
**Pull request by AlexV525**
Continue from #98559, fix #43277.

Breaking change note: flutter/website#6646.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by AlexV525** [comment]
This adds an extra fix to the overall experience test to resolve the revert. FYI @zanderso

**Review by dnfield — APPROVED** [review]

**Comment by AlexV525** [comment]
I'm currently available and will keep an eye on further changes if any of them are requested.

**Review by zanderso — CHANGES_REQUESTED** [review]
Is there any update on the performance issues mentioned in https://github.com/flutter/flutter/issues/43277 and/or https://github.com/flutter/flutter/issues/88492?

**Comment by AlexV525** [comment]
> Is there any update on the performance issues mentioned in #43277 and/or #88492?

This should be addressed by flutter/engine#29775 as @flar said in https://github.com/flutter/flutter/issues/43277#issuecomment-1009247402.

**Review by zanderso — APPROVED** [review]
Got it thanks.

**Comment by AlexV525** [comment]
> Is there any update on the performance issues mentioned in #43277 and/or #88492?

We still need to monitor if any metrics have a sharp increase after this. Thanks for keeping track.

**Comment by zanderso** [comment]
> > Is there any update on the performance issues mentioned in #43277 and/or #88492?
> 
> We still need to monitor if any metrics have a sharp increase after this. Thanks for keeping track.

@GaryQian is the current sheriff. Gary, please watch out for the perf impact of this change in SkiaPerf.

**Comment by zanderso** [comment]
This has change has caused a larger memory footprint: https://flutter-flutter-perf.skia.org/e/?begin=1647895223&end=1648529864&keys=X845c9ddf84d6ac62deff51c6cee6ad22&requestType=0&xbaroffset=28090

Is that intentional?

**Comment by AlexV525** [comment]
> Is that intentional?

@zanderso I would say it's intentional since it involves more transforms than before. But I can't tell whether the difference should be acceptable.

**Pull request merged**
