### PR TITLE
Revert "Reland "Clipping if only one character text overflows (#99146…

### PR DESCRIPTION
**Pull request by XilaiZhang**
…)" (#102130)"

This reverts commit 3f43d9f3d4105d4190c839e087c42d79ebe092e8.

reverting on candidate branch. luci-tree on master branch is currently broken.

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Review by justinmc — APPROVED** [review]
LGTM, but what happened to the other revert PR? https://github.com/flutter/flutter/pull/106964

**Comment by goderbauer** [comment]
> LGTM, but what happened to the other revert PR? https://github.com/flutter/flutter/pull/106964

That one was to master, this one is to the candidate release branch.

**Comment by justinmc** [comment]
Ah got it, thanks!

**Pull request merged**
