### PR TITLE
Added assert to prevent complete ListTile trailing/leading horizontal expansion

### LINKED ISSUE #17666: Empty trailing Container in ListTile widget causes layout issues
@HansMuller There were some changes made to `ListTile` that caused some issues in the Hamilton app. In our modal bottom sheets that present a user state/country options, the trailing widget is either a checkmark icon or an empty container depending on the user's selection. It seems that now if the trailing widget is an empty `Container` the title lays out incorrectly. Replacing `Container` with `IgnorePointer` fixes the issue, but I'm filing the issue in case that was an unintended side effect.

**Before:**
img_2412

**Now:**
img_2411

`flutter doctor -v`
```
[✓] Flutter (Channel master, v0.4.5-pre.10, on Mac OS X 10.13.4 17E202, locale en-US)
    • Flutter version 0.4.5-pre.10 at /Users/albertlardizabal/dev/flutter
    • Framework revision 5159ab3513 (27 hours ago), 2018-05-15 10:09:25 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/albertlardizabal/Library/Android/sdk
    • Android NDK at /Users/albertlardizabal/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 24.2.2
    • Dart plugin version 181.4892.1
```

### PR DESCRIPTION
**Pull request by shihaohong**
## Description

Added an assert statement for when `leading` or `trailing` widgets are trying to take up the entire `ListTile` width. I also tweaked the documentation a little since it was formatting incorrectly on the master API documentation.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/17666

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by ibarrick** [comment]
@HansMuller Please see my comments on the assertions. I would love to get this issue resolved and would be happy to submit the PR myself. The assertions break multiple widgets in our project.

**Comment by shoxter** [comment]
How is adding assertions classified as "not a breaking change?" I have multiple widgets refusing to render now because of these asserts.

**Comment by shihaohong** [comment]
Hi @ibarrick @shoxter,
I apologize if this PR caused your widgets to break. I had not anticipated that these asserts would cause any issues. Could you create a new issue and share a minimal reproducible sample? Link it to this PR so we can better track what happened.

**Pull request merged**
