### PR TITLE
Fix ActivateIntent overriding the spacebar for text entry

### LINKED ISSUE #90907: Windows x64 TextField inside ListTile can't type space
## Steps to Reproduce

1. flutter create bug
2. create TextField inside ListTile. Or Copy my main.dart
3. Run on windows-x64
4. Try to type "Test Typing wow"

**Expected results:** 
"Test Typing wow"

**Actual results:** 
"TestTypingwow"

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

```
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(
        child: ListTile(
              title: TextField(
                
              ),
            ),
      ),
    );
  }
}
```

```
[  +69 ms] executing: [D:\Setup\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +83 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] ffb2ecea5223acdd139a5039be2f9c796962833d
[        ] executing: [D:\Setup\flutter/] git tag --points-at ffb2ecea5223acdd139a5039be2f9c796962833d
[  +63 ms] Exit code 0 from: git tag --points-at ffb2ecea5223acdd139a5039be2f9c796962833d
[        ] 2.5.1
[   +9 ms] executing: [D:\Setup\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [D:\Setup\flutter/] git ls-remote --get-url origin
[  +54 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +130 ms] executing: [D:\Setup\flutter/] git rev-parse --abbrev-ref HEAD
[  +58 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +74 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +67 ms] executing: D:\Setup\Android\Sdk\platform-tools\adb.exe devices -l
[  +59 ms] List of devices attached
[   +9 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +84 ms] Multiple devices found:
[  +35 ms] Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.194]
[   +2 ms] Chrome (web)      • chrome  • web-javascript • Google Chrome 94.0.4606.61
[   +1 ms] Edge (web)        • edge    • web-javascript • Microsoft Edge 94.0.992.31
[   +2 ms] [1]: Windows (windows)
[        ] [2]: Chrome (chrome)
[        ] [3]: Edge (edge)
[   +2 ms] Please choose one (To quit, press "q/Q")
[   +1 ms] : 
```

```
Analyzing bug...                                                        
No issues found! (ran in 2.3s)
```

```
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.22000.194], locale tr-TR)
    • Flutter version 2.5.1 at D:\Setup\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (11 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
```

### PR DESCRIPTION
**Pull request by justinmc**
Currently, if an EditableText is wrapped in something that uses ActivateIntent, such as ListTile, then the ActivateIntent will get all of the spaces and you won't be able to type them into the field.  This PR proposes to fix it by using DoNothingAndStopPropagationTextIntent in DefaultTextEditingShortcuts, however, there are architectural implications for Flutter to consider.

### Why this solution works

  * DefaultTextEditingShortcuts is just below the Shortcuts widget in WidgetsApp, so it gets to handle the space just before ActivateIntent would otherwise get invoked.
  * These are both way at the root of the tree, so this isn't interfering with users' ability to override the spacebar themselves.
  * Because I'm using DoNothingAndStopPropagationTextIntent and not DoNothingAndStopPropagationIntent, it is only used when an EditableText is currently focused, otherwise it passes the space through.  So, the ActivateIntent will work as normal for widgets that are not wrapping an EditableText.

### Architectural implications

In general, a widget that defines Shortcuts and has no children doesn't need to worry about any other widgets "stealing" the shortcuts from it.  As a leaf, they can't be stolen from it (even with @LongCatIsLooong's OverridableAction, because it is opt-in).

A widget that defines Shortcuts and DOES have children implicitly allows those children to steal keys from it.  That is ok.  Think of a scrollable list that can be scrolled with the arrow keys, but if one of the list items is a text field and it is focused, the text field should be able to consume those arrow keys itself.

This PR doesn't affect those assumptions, because even though EditableText is a leaf, it doesn't use Shortcuts itself.  That is done in DefaultTextEditingShortcuts near the root of the tree.  It's this separation of the visual widget and its Shortcuts definitions that is tricky here.

#### Getting to the point...

In our case, our architectural concern is the competition between the [default WidgetsApp Shortcuts](https://github.com/flutter/flutter/blob/23cea26715257103a7a4d225992fc58b48bd2605/packages/flutter/lib/src/widgets/app.dart#L1671) and the [DefaultTextEditingShortcuts](https://github.com/flutter/flutter/blob/23cea26715257103a7a4d225992fc58b48bd2605/packages/flutter/lib/src/widgets/app.dart#L1676), both near the root of the tree.  If we go with this PR's approach as-is, we are basically saying that we just need to be aware of the competition between these two and not introduce any more bugs like this, say, the next time that the WidgetsApp Shortcuts adds a new shortcut for a normal text input key.

Is there anything better we could do?  Do we need to defensively put a DoNothingAndStopPropagationTextIntent into DefaultTextEditingShortcuts for every possible text input key?  Could we create a SingleActivator that catches all possible text input keys?  Is there a better way overall?

### Related issues

Fixes https://github.com/flutter/flutter/issues/90907

### TODO

 * [ ] Decide if this is the right way to go architecturally
 * [x] Tests
 * [x] Enter key as well

### CODE REVIEW

**Comment by gspencergoog** [comment]
> Do we need to defensively put a DoNothingAndStopPropagationTextIntent into DefaultTextEditingShortcuts for every possible text input key?

We'd just need to add it for any of the text input keys that are also default shortcuts, right?
I'm not sure that's horrible. I mean, it's annoying, but it's all pretty hidden from the users.

**Comment by dkwingsmt** [comment]
If I understand correctly, the reason we have the bizarre behavior as this bug is because the `Shortcut` for text fields is placed at the root (out of the list tile), instead of at the leaf (inside the list tile, which is coherent to the behavior model users expect.) The current way looks like another bandage over the root cause. So why was it designed this way in the first place?

**Comment by dkwingsmt** [comment]
@justinmc Can you add a unit test (since this PR'll need it anyway) and try it against https://github.com/flutter/flutter/pull/90684?

**Comment by gspencergoog** [comment]
> Although, if you really want to check, why not just compare the activators, so that for example "Space" and "Ctrl+Space" can be told apart?

I was worried that they wouldn't compare as equal. Will activators created via different classes compare as equal?  For instance, if you create a `SingleActivator` and a `LogicalKeySet` with the same keys in them, will they compare the same?

**Comment by dkwingsmt** [comment]
@gspencergoog No, and they shouldn't, since they behave differently.

**Comment by gspencergoog** [comment]
> No, and they shouldn't, since they behave differently.

Sure, I agree, but if someone used `LogicalKeySet(LogicalKeyboardKey.space)` in one map, and `SingleActivator(LogicalKeyboardKey.space)` in another, they wouldn't compare as equal, even though they both handle `space` in the same way. Conversely, comparing the `triggers` of `LogicalKeySet(LogicalKeyboardKey.space)` in one map, and `SingleActivator(LogicalKeyboardKey.space, control: true)` would compare as equal, when one is not a text input key and the other is.

Ideally, they're all `SingleActivator`s anyhow, so maybe we can just enforce that, and then compare them directly. There might be some exceptions to that eventually, but we can cross that bridge when we come to it.

**Review by dkwingsmt — APPROVED** [review]
LGTM

**Comment by gspencergoog** [comment]
@justinmc is this something that should be re-landed, or was this fixed in another way?

**Comment by ghunkins** [comment]
This is still not fixed on web as well. The issue is sporadic and difficult to reproduce.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6 20G165 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by laveesingh** [comment]
Tried to use it (ListTile > TextField) for the mac desktop, doesn't seem fixed.
Happens for both space, and enter keys. I'm using the following version:

```
Flutter 2.9.0-0.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 8f1f9c10f0 (3 months ago) • 2021-12-14 13:41:48 -0800
Engine • revision 234aca678a
Tools • Dart 2.16.0 (build 2.16.0-80.1.beta) • DevTools 2.9.1
```

**Comment by dkwingsmt** [comment]
@laveesingh Can you switch to master channel and try again? The dev channel has been terminated. See the last paragraph of https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#which-channel-should-i-use

**Comment by LeonardoAppItalia** [comment]
Tried to use it (SingleChildScrollView > TextField) for the web, doesn't seem fixed.
I am doing a great job and this bug is very annoying, it would redact my work useless and unprofessional.
has anyone come to a solution?

> 
> [✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-arm, locale it-IT)
> [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
> [✓] Xcode - develop for iOS and macOS (Xcode 14.0)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2021.1)
> [✓] VS Code (version 1.71.2)
> [✓] Connected device (3 available)
> [✓] HTTP Host Availability

**Comment by dsyrstad** [comment]
> Tried to use it (SingleChildScrollView > TextField) for the web, doesn't seem fixed. I am doing a great job and this bug is very annoying, it would redact my work useless and unprofessional. has anyone come to a solution?
> 
> > [✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-arm, locale it-IT)
> > [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
> > [✓] Xcode - develop for iOS and macOS (Xcode 14.0)
> > [✓] Chrome - develop for the web
> > [✓] Android Studio (version 2021.1)
> > [✓] VS Code (version 1.71.2)
> > [✓] Connected device (3 available)
> > [✓] HTTP Host Availability

Flutter stable is 3.3.2 now, perhaps you should try this version.

**Pull request merged**
