### PR TITLE
Remove checks for the packagePath in gen_snapshot (it does not need to be passed)

### PR DESCRIPTION
**Pull request by mkustermann**
See also https://github.com/flutter/flutter/pull/28101

### CODE REVIEW

**Comment by mkustermann** [comment]
This should fix broken build

**Review by a-siva — APPROVED** [review]

**Comment by gspencergoog** [comment]
It needs more work than just removing it from the tests: if you can't set `--packages` anymore, then there's no point in `PackageMap` taking a package path in the first place, and that class also keeps a `globalPackagesPath` that should only ever be ".packages" now.

**Comment by jonahwilliams** [comment]
It looks like this was already removed in #28334, can we close this PR?

**Comment by mkustermann** [comment]
Sure.

**Pull request closed without merging**
