### PR TITLE
[CupertinoListSection] adds new property separatorColor

### LINKED ISSUE #124744: `CupertinoListSection` should take a parameter to change the color of the divider color
## Use case
Am using `CupertinoListSection.insetGrouped` to create a list of clicable item in ios style. Everything is rendering good but we cannot set the color of the divider to a preferred one. Setting the theme to light make the divider filled with black which is not so good to look for me. I would like to have capability to set my custom color to the divider.

image

## Proposal
Add `dividerColor` parameter to `CupertinoListSection`.

### PR DESCRIPTION
**Pull request by piedcipher**
Adds new property `separatorColor` to `CupertinoListSection` widget.

Fixes: #124744

### `separatorColor` property is not-null

| Color.fromARGB(255, 136, 13, 207) | Color.fromARGB(255, 13, 62, 207) | Color.fromARGB(255, 29, 207, 13) |
| --- | --- | --- |
| a | b | c |

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by MitchellGoodwin — APPROVED** [review]
LGTM

**Review by Piinks — APPROVED** [review]
Flutter_LGTM

**Comment by piedcipher** [comment]
Thanks a lot! Happy to contribute. ❤️ When I saw 2 LGTMs, couldn't control my happiness 🥹

**Comment by Piinks** [comment]
Thanks for contributing @piedcipher!

**Pull request merged**
