### PR TITLE
Update test instructions for flutter_tools

### PR DESCRIPTION
**Pull request by cbracken**
flutter_tools testing requires the FLUTTER_TOOLS environment variable to
be set.

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by abarth** [comment]
Thanks.  I ran into this today.  Also, apparently you need to unplug any devices that are attached.

**Comment by cbracken** [comment]
Ah good point. I ran into the devices thing the other day too. I'll add a note. Eventually it'd be nice to support mocked out [lack of] devices for unit tests and use real devices for the device-lab tests.

**Comment by cbracken** [comment]
Done.

**Comment by goderbauer** [comment]
LGTM

**Comment by eseidelGoogle** [comment]
FYI @tvolkert who's been mocking all the things.

**Pull request merged**
