### PR TITLE
Add a clipBehavior parameter to BottomAppBar.

### PR DESCRIPTION
**Pull request by amirh**
Setting the default clip behavior made bottom app bar to no longer clip
its children.
With this parameter users could opt-in to clipping.

While this doesn't fix the regression mentioned in #21413, it at least allows users to fix it in their code.

### CODE REVIEW

**Review by liyuqian — COMMENTED** [review]
Thanks Amir for fixing  this! Maybe also add a small unit test to verify the fix and ensure that we don't regress again? I'm not sure whether we can test PhysicalShape like the tests in https://github.com/flutter/flutter/pull/21231 or whether we have to create a golden test.

**Comment by amirh** [comment]
done

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by amirh** [comment]
Will land on green

**Review by liyuqian — APPROVED** [review]
LGTM

**Pull request merged**
