### PR TITLE
Add support for khmer language.

### PR DESCRIPTION
**Pull request by sophatvathana**
Hi, I would like to add support for Khmer language which is the language of the Khmer people and the official language of Cambodia.

### CODE REVIEW

**Comment by sophatvathana** [comment]
I signed it!

**Comment by sophatvathana** [comment]
@abarth Dear sir, I would like to kindly ask you to review and accept this pull request.Thanks

**Review by sophatvathana — COMMENTED** [review]
Merge add support for Khmer language.

**Review by sophatvathana — COMMENTED** [review]
Add support for khmer language.

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
Thanks for your contribution! Sorry it's taken so long for us to acknowledge it.

Just to simplify the merge, I will create a separate PR with material_km.arb your addition to the tests, etc.

In a couple of weeks your translations will have been completed and vetted by Google's translation team.

**Pull request closed without merging**
