### PR TITLE
Remove unused code from tests

### PR DESCRIPTION
**Pull request by goderbauer**
The dead code was found by running `dart run dart_code_metrics:metrics check-unused-code test` from https://pub.dev/packages/dart_code_metrics in `packages/flutter`. 

Other notes about the tool:
* The tool didn't find anything interesting in non-test code of the framework.
* There were a few false positives in the framework and in test code.

### CODE REVIEW

**Comment by goderbauer** [comment]
Regarding the dead code this tool found in tests: Ideally, we'd want to avoid accumulating this and there are a couple of lint proposals that would help: https://github.com/dart-lang/linter/issues/1258, https://github.com/dart-lang/linter/issues/685, https://github.com/dart-lang/linter/issues/2395. I believe, any of these would have avoided the dead code from making (or remaining) in the repository. (cc @pq)

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Excellent!

**Comment by pq** [comment]
This is pretty amazing.  Nice.   Thanks for sharing.  And cheers to the `dart_code_metrics` folks! 🍻

**Comment by incendial** [comment]
@goderbauer hi, co-author of Dart Code Metrics here 🙂. So happy to see that the tool helped find and remove unused code! Could you please share more details about the false-positives part? If you don't think this PR is a great place to discuss it, feel free to open an issue here https://github.com/dart-code-checker/dart-code-metrics/issues/new/choose

> This is pretty amazing. Nice. Thanks for sharing. And cheers to the dart_code_metrics folks! 🍻

Thank you! ❤️

**Pull request merged**
