### PR TITLE
Allow SingleChildScrollView to have overflowArea which will render de…

### LINKED ISSUE #60203: Specify overflow area for single child scroll view
## Use case
ezgif-3-3b886e0571e6
Scroll view doesn't render the overflowed content, however my application's design have some overflowed area where the content needs to show.

## Proposal
Allow SingleChildScrollView to take in a property allowing user to specify overflowing area that needs to be rendered.

### PR DESCRIPTION
**Pull request by chingyawhao**
## Description

This will allow user specified overflow area to render in single child scroll view.

## Related Issues

Close #60203 

## Tests

I added the following tests:
`packages/flutter/test/widgets/single_child_scroll_view_test.dart`

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by chingyawhao** [comment]
@googlebot I signed it!

**Comment by chingyawhao** [comment]
@googlebot I signed it!

**Comment by goderbauer** [comment]
I don't super-understand what this feature would be used for. What does this enable that you currently cannot do?

Also, we require tests for all PRs that get merged into Flutter to avoid that anything is broken by accident in the future. Can you please add some tests to this PR?

**Comment by chingyawhao** [comment]
This is to allow graphics rendering outside the viewport.
ezgif-3-f9602f7e7f77

I want my content to show under the button even when it is outside the scrollview.

**Comment by HansMuller** [comment]
@chingyawhao - to build something that looks like your demo, you need to [stack](https://api.flutter.dev/flutter/widgets/Stack-class.html) the panel that contains the "continue" button on top of the scrolling container.  I don't think any changes to Flutter are needed.

**Comment by chingyawhao** [comment]
@HansMuller thats not a proper solution, I would also need to calculate the height of the button everytime so that I can have a padding bottom of the same height allowing people to be able to scroll all the way down

And also, imagine the page is much longer and I want to auto scroll the input
ezgif-4-ebc6cbc698cc

For your solution, even after the auto focus, most of the input is blocked under the button.

**Comment by HansMuller** [comment]
@chingyawhao - I see what you're getting at. The problem here is that Scrollable.ensureVisible() can't know that part of its viewport is obscured by the button panel stacked on top. In this case that affects the automatic scroll that occurs when the a Scrollable descendant is focused: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/focus_traversal.dart#L40

To enable this use case I suppose we'd have to provide a way for developers to specify an additional Scrollable `visibleInsets` parameter.

CC @Piinks

**Comment by goderbauer** [comment]
On a textfield you can configure where it is positioned inside a scrollable with the scrollpadding setting: https://master-api.flutter.dev/flutter/material/TextField/scrollPadding.html

If you set this to something like `const EdgeInsets.only(bottom: <height of your obstruction>)` it would probably give you what you want?

**Comment by chingyawhao** [comment]
@HansMuller - ya, and this pull request's `overflowArea` can solve it too
Can you elaborate on your proposed `visibleInsets`? Is this what u meant?
sample

That would work, but I think maybe `hiddenInsets` might make more sense

**Comment by chingyawhao** [comment]
I modified this merge request by implementing scrollPadding as suggested by @goderbauer

**Comment by goderbauer** [comment]
> I modified this merge request by implementing scrollPadding as suggested by goderbauer

My suggestion was to just specify the `scrollPadding` on your text field, not to add it to the scroll view. Changing your text field to specify a scroll padding didn't work?

**Comment by Piinks** [comment]
Have we tried this with a lazy loading scroll view? I understand that there is only one child here, but doesn't a ListView or SliverList cache a certain amount of space before and after the visible area? I haven't tried it yet, but I imagine in that case it might still be visible in your use case.

**Comment by chingyawhao** [comment]
It doesn't work @goderbauer 
The SingleChildScrollView clip off the overflow child by default

**Comment by chingyawhao** [comment]
I get it now @goderbauer 
Don't know why I was thinking about scrollview and button in the same layer, it's quite obvious u meant something else

So edgeinsets of obstruction as the padding of scrollview and scrollpadding of all the textfields solve my problem unless I need more contents beside textfields to be scrolled into visible area

**Comment by chingyawhao** [comment]
I definitely learn a lot here
But it's still disappointing knowing I spent 2 hours working on this pull request for nothing

**Pull request closed without merging**
