### PR TITLE
Add fixes for AppBar deprecations

### LINKED ISSUE #74908: Write dart fixes for old deprecations/breaking changes
There are old deprecations/breaking changes that do not have fixes associated with them.

Moving forward we will be writing dart fixes in conjunction with new breaking changes and deprecations, but there is a bit of a backlog of old breaks that would be nice to support with the tool if we can.

### PR DESCRIPTION
**Pull request by Piinks**
This adds fixes for the deprecations added in https://github.com/flutter/flutter/pull/86198

Fixes #74908

It also adds a few missing deprecation notices to the affected api.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by HansMuller — APPROVED** [review]
LGTM

SystemUiOverlayStyle requires `import 'package:flutter/services.dart';` see https://github.com/flutter/gallery/pull/531 which applied the gallery changes.

**Review by darrenaustin — APPROVED** [review]
LGTM. Looks like there are some test failures that Hans had some insight into.

**Comment by Piinks** [comment]
Thanks! Yeah, I can add the import with the fix! :)

**Comment by Piinks** [comment]
So, I added the import, just like we have in another fix, but it is for some reason resulting in ~1000 import statements after running the fix. 🙃 

@bwilkerson is there something wrong here? 

Output:
[output.txt](https://github.com/flutter/flutter/files/6812227/output.txt)

**Comment by Piinks** [comment]
Not sure why flutter_svg would be broken by this. Checked it out locally with/without this change and the test failure persists, cc @dnfield

**Comment by dnfield** [comment]
Looks like it may be related to an engine change - does it help if you merge up to head?

**Comment by Piinks** [comment]
This is up to date as of 30 minutes ago, the failure has persisted for a few days now of merging master a couple of times.

**Comment by Piinks** [comment]
Synced again..

**Comment by Piinks** [comment]
Caught up with @dnfield offline, this failure does not appear to make sense with this change, I am going to open a fresh PR to see if it resolves itself.

**Comment by Piinks** [comment]
New PR is https://github.com/flutter/flutter/pull/88365

**Pull request closed without merging**
