### PR TITLE
Remove unused bigquery code and deps

### PR DESCRIPTION
**Pull request by dnfield**
This code is unused. It was part of an idea to track the time and flakiness of individual tests, but had some issues and has not been turned back on. We should just delete it and re-land it when we're ready to actually use it.

### CODE REVIEW

**Comment by dnfield** [comment]
This also required rolling packages.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by keyonghan — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Ignored the google testing check because none of this code runs in google.

**Pull request merged**
