### PR TITLE
Do Not Merge - Testing CI Goldens Issue

### PR DESCRIPTION
**Pull request by Piinks**
Changes from #36565, (originating from #36087), on a fresh branch to try to identify why the goldens repository can't be synced in CI.

### CODE REVIEW

**Comment by Piinks** [comment]
cc/ @LongCatIsLooong

**Comment by Piinks** [comment]
@fkorotkov This presubmit check is showing files that exist from another PR. (Originally #33688, which was reverted, and then #36103, which had not landed yet)
I'm not sure how they ended up here showing up on CI on a separate PR? And also why only this PR seems to be affected and not others?

**Comment by Piinks** [comment]
I think I understand what is happening here now. These files are actually being cached as specified in our .cirrus.yml file. I will see about cleaning up these files.

**Comment by brandondiamond** [comment]
Thanks for looking into this! Sorry for causing friction.

**Comment by Piinks** [comment]
Hi @brandondiamond, no friction at all! You helped us discover a bug that needs fixin. :) 
I've opened #36690 to resolve this issue, after which your PR (#36087) will be unblocked. Thanks for the contribution!

**Pull request closed without merging**
