### PR TITLE
Fix `ExpansionTile` double tap to collapse/expanded and expanded/collapsed states semantics announcements

### LINKED ISSUE #120650: When interacting with a ExpansionTile using a screen reader, the status of the tile is not announced
Internal bug: b/269139224

(Copied from the internal bug above)

The bug also happens on iOS devices.

## Steps to Reproduce

1. With an Android device or emulator with Talkback enabled.
2. Focus on the collapsed/expanded ExpansionTile and verify what the screen reader announces.
3. Double click to activate/collapse the ExpansionTile and verify the screen reader announcement.

**Expected results:** 

The tile should read "double tap to expand", "double tap to collapse" when focused on it.
The tile should announce "expanded" or "collapsed" when clicking on it.

**Actual results:** 

Screen reader is just reading "double tap to activate" when focused on the tile.
The tile doesn't announce anything when it's expanded or collapsed.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        // We also apply a custom font, ProductSans.
        title: Text(widget.title, style: TextStyle(fontFamily: 'ProductSans')),
      ),
      body: Center(
        child: ExpansionTile(
          title: Text('Tile'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

### PR DESCRIPTION
**Pull request by TahaTesser**
fixes https://github.com/flutter/flutter/issues/120650

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              ExpansionTile(
                title: Text('Flutter Forward'),
                children: <Widget>[
                  FlutterLogo(size: 100),
                ],
              ),
              SizedBox(height: 20),
              ExpansionTile(
                initiallyExpanded: true,
                title: Text('Flutter Forward'),
                children: <Widget>[
                  FlutterLogo(size: 100),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

``` 
	
</details>

### Demo

https://user-images.githubusercontent.com/48603081/221514339-306d8e9e-04f2-4ca9-b09a-0463c913f0f0.mp4

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by chunhtai — COMMENTED** [review]
Double checked with google internal a11y guideline and looks like this is also required for Android

1.4
Consider providing accessibility hints, especially in cases where additional detail may be helpful in explaining a click or long-click action. This is accomplished by overriding a standard accessibility action with a custom label, which will be appended to TalkBack’s feedback after the View’s content is spoken.

For example, if clicking on a card expands its contents to show more detail, but this isn’t conveyed in TalkBack’s output because the card contains other text, applying an accessibility hint as follows would result in TalkBack appending “Double tap to expand for more details.”, which provides a more polished user experience.


For iOS, we should add a SemanticsProperties.hint. The onTapHint does not work on iOS.
https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/iPhoneAccessibility/Making_Application_Accessible/Making_Application_Accessible.html#//apple_ref/doc/uid/TP40008785-CH102-SW6

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by TahaTesser** [comment]
@chunhtai 
Updated the PR for the onTapHint label, however for iOS, there is no hint for the list tile or related widgets such as the expansion tile so I want to fix the list tile and other widgets together in a separate PR.

**Review by chunhtai — APPROVED** [review]
LGTM

**Pull request merged**
