### PR TITLE
Wide gamut framework gradient test

### PR DESCRIPTION
**Pull request by gaaclarke**
issue: https://github.com/flutter/flutter/issues/127855
depends on https://github.com/flutter/engine/pull/54748 being rolled into the framework

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by gaaclarke** [comment]
I'm putting this into review, it shouldn't land until https://github.com/flutter/engine/pull/54748 rolls into the framework though.

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
reason for revert: failing on postsubmit

**Comment by jonahwilliams** [comment]
See: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20wide_gamut_ios/9920/overview

**Comment by gaaclarke** [comment]
things got broke in the engine after this PR didn't land because of a flake that blocked the autosubmit =(

**Comment by gaaclarke** [comment]
I ran these locally against 57c4bd0d85f3e41eb21522a0feb2dfaa514f8e22 and they still didn't pass.  Something happened between testing them locally and getting them landed in the separate repo.

**Comment by jonahwilliams** [comment]
Lets make sure we don't need to cherry pick anything to get wide gamut working...

**Comment by gaaclarke** [comment]
> Lets make sure we don't need to cherry pick anything to get wide gamut working...

Looking into it.  FWIW the standard wide gamut tests are passing, this is just for gradients.

**Comment by gaaclarke** [comment]
I verified that the colors are wide gamut all the way to sending them to the buffer.  On the output side the closest color to p3 red is (0.9965759667968751 -0.0014706249999999477 -0.0014706249999999477).  I was wondering if the blending of colors was making looking for p3 red fail by being slightly off but it seems like there may be some clamping done in the fragment shader.

**Comment by gaaclarke** [comment]
Found the clamping, it's in the dithering: https://github.com/flutter/engine/blob/7c5c5fe5c84dca784bf51d47840447411f547b03/impeller/compiler/shader_lib/impeller/dithering.glsl#L49

**Comment by gaaclarke** [comment]
We could fix the dithering math, but dithering actually isn't desirable either when we have wide gamut colors since we have 10bits per color component.

**Comment by jonahwilliams** [comment]
Wide gamut doesn't fix gradient banding. But we don't actually need to clamp there, so we can just delete it. For non wide gamut the driver will clamp

**Comment by gaaclarke** [comment]
> Wide gamut doesn't fix gradient banding.

It does in our case, banding with 10bits per color component is beyond the perceptible limit.

> But we don't actually need to clamp there, so we can just delete it.

Yea, playing with it.

**Comment by gaaclarke** [comment]
Removing the dithering works for the linear and the sweep gradient.  For the conical and the radial gradient it looks like you aren't guaranteed to get your requested color back so tweaking the threshold for those tests will be necessary.

**Comment by jonahwilliams** [comment]
I think if you want the test to be stable you need to either use an epsilon or make it a single color gradient

**Pull request merged**
