### PR TITLE
Reland "Update PopupMenuButton to match Material Design spec"

### PR DESCRIPTION
**Pull request by xu-baolin**
Relands #74620

Do not merge before @Piinks figure out what was breaking of the internal test.

### CODE REVIEW

**Comment by Piinks** [comment]
Thanks @xu-baolin! I'll find out what is going on. :)

**Comment by Piinks** [comment]
Update: The Google testing check here is not reflective of executing all of the tests, just a sampling. I have run all the tests and found some failures that look suspect. Working on finding out why now. :)

**Comment by Piinks** [comment]
Hey @xu-baolin I've revisited this and it is still massively breaking, can this be re-worked to make it possible to opt-in to the new behavior? I do not think we can land this in this state, over 1200 tests are broken on last check.

**Comment by xu-baolin** [comment]
@Piinks Hi, Thank you so much for your feedback.
I will separate this PR into two, one to fix the problem introduced by #64678, and the other to retry to let it meet the Material design specifications.

**Pull request closed without merging**
