### PR TITLE
[macOS] RawKeyboardDataMacos properly handles multi-char characters

### PR DESCRIPTION
**Pull request by dkwingsmt**
This PR changes the `logicalKey` value of a `RawKeyboardEvent` that has a multi-char `character`.

Previously its logical key is a unicode key, whose 32-bit value part is the concatenation of the two characters. This is inproper because:

- The resulting value is not a proper UniCode value. In fact, it will trigger an exception when being converted to `keyLabel`.
- It incorrectly assumes that there won't be more than 2 characters, and every character can fit in the 16-bit BMP area.

With this PR, its logical key is its key code mapped to the macOS plane.

This fixes the macOS-channel part of https://github.com/flutter/flutter/issues/82673.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gspencergoog** [comment]
I agree that the two character limit isn't right, but doesn't this disable all multi-char input, like emojis?

**Comment by dkwingsmt** [comment]
This change only affects the logical key's value (and consequently, the `keyLabel` of the logical key). It doesn't affect the event's `character`.

And if that's the concern, yes, a multi-char emoji event (if that's a thing) will have a minted logical key. What else can we give for this event?

**Comment by gspencergoog** [comment]
Got it.  Makes sense.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Pull request merged**
