### PR TITLE
Stop failing on double disposal.

### PR DESCRIPTION
**Pull request by polina-c**
After [cleanup of not disposed leaks](https://github.com/dart-lang/leak_tracker/issues/134), some user code that disposes instances of ChangeNotifier, started failing, because the disposal is now second disposal which is considered as usage after disposal. 
As all flutter tests passed and number of the failures in user code is small (cl/564068590), the failing disposals are violations of ownership.

This PR suggests to stop considering disposal as usage and allow second disposal for ChangeNotifier, the same way as it is allowed for many other disposables, like FocusManager: https://github.com/flutter/flutter/blob/9dbbd5b4bfefb34514b569f962f267ebe22c9399/packages/flutter/lib/src/widgets/focus_manager.dart#L1752

### CODE REVIEW

**Comment by Hixie** [comment]
I don't understand. If the failing cases are violating ownership, isn't asserting the right thing to do?

**Comment by jacob314** [comment]
Agree this shouldn't land. There was only a single g3 project failing due to new double disposal errors. We may want to instead update the assert with instructions on the correct steps to take if hitting this issue (the change to the g3 project was simple... remove a few unneeded dispose() calls).

**Comment by polina-c** [comment]
There are complicated cases. For example when user class creates ScrollController if it does not exist in context yet. 
So, ideally the user class should sometimes dispose the controller, sometimes not.

After getting failure some users will not have capacity to resolve it in right way and will just remove disposal completely.

So, in this cases the choice is between two issues (1) no disposal and (2) double disposal.

By failing on double disposal we are forcing user to go without disposal at all.

**Comment by goderbauer** [comment]
A double disposal usually means that someone incorrectly has assumed ownership of the object where it shouldn't have. That is almost certainly a bug and we shouldn't paper over it.

**Comment by polina-c** [comment]
Closing. Hopefully leak_tracker will prevent no-disposals

**Pull request closed without merging**
