### PR TITLE
Document MaterialApp's _errorTextStyle

### PR DESCRIPTION
**Pull request by abarth**

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM. Might be worth adding a debugLabel to that style too, e.g. "fallback style; consider putting your text in a Material" or something.

**Comment by abarth** [comment]
Done.

**Comment by Hixie** [comment]
LGTM

This is a private, BTW, so these docs will only appear to people reading the source.

**Comment by abarth** [comment]
> these docs will only appear to people reading the source.

Yeah...  It will take a bunch of debugging to get back to this point.  Maybe there's a way to log a message when this style is used?

**Comment by Hixie** [comment]
We could certainly make this actually use a new class that implements all the methods and/or getters or whatever to call reportFlutterError the first time they're accessed. It would be non-trivial effort but given how often people just don't set a font, and end up relying on the default without having thought about what it is, maybe it's worth it.

Feel free to land this in the meantime.

**Pull request merged**
