### PR TITLE
Short-circuit _debugCanPerformMutations if debugDoingLayout is false

### PR DESCRIPTION
**Pull request by Hixie**
It's more or less always ok to perform mutations if we're not doing layout and not painting.

Improves https://github.com/flutter/flutter/issues/76261

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: performance improvement with no semantic change

**Comment by Hixie** [comment]
@goderbauer points out i should remove the paint part, since this never returns false during paint currently anyway and is thus probably not even called during paint.

**Comment by goderbauer** [comment]
Conceptually, `_debugCanPerformMutations` probably should return false during paint as you shouldn't be calling adoptChild/dropChild/markNeedsLayout/setupParentData (the methods guarded by `_debugCanPerformMutations`) during paint, but it appears that the current implementation of `_debugCanPerformMutations` doesn't cover the paint case.

**Review by goderbauer — APPROVED** [review]
LGTM

(checks should go green with a rebase)

**Pull request merged**
