### PR TITLE
Use inheritStdio in pub.interactively

### PR DESCRIPTION
**Pull request by jonasfj**
Use `ProcessStartMode.inheritStdio` when calling `pub`. This allows `pub` to detect terminal, without this `pub` will default to no colors.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
I'm sorry this took me so long to get to.

Everything seems reasonable but I can't get this to work right. For example, on windows when I pub run test in `flutter_tools` (as a reference point) I can easily terminate the process and everything works normally afterwards
```
PS C:\Users\Jonah\flutter\packages\flutter_tools> pub run test .\test\general.shard\analytics_test.dart
00:00 +0: loading .\test\general.shard\analytics_test.dart - did not complete [E]
00:00 +0: Some tests failed.
^CTerminate batch job (Y/N)? y
```

If I use `flutter pub`, then cancelling the process leaves the terminal in a bad state where I cannot completely type or autocomplete any previous commands

```
PS C:\Users\Jonah\flutter\packages\flutter_tools> flutter pub run test .\test\general.shard\analytics_test.dart
00:03 +0: analytics doesn't send when disabled                                                                         Terminate batch job (Y/N)?
^C
PS C:\Users\Jonah\flutter\packages\flutter_tools> yCTer
```

fyi @zanderso in case he has some ideas

**Comment by zanderso** [comment]
I could imagine this happening if `pub` normally resets terminal state when being killed by a signal, and somehow this doesn't work when the tool is its parent, and the tool gets killed by a signal.

Separately, the tool should probably restore terminal state when killed by a signal.

**Comment by zanderso** [comment]
@jonasfj Since it seems like we're planning on exposing Dart SDK tools in a different way, should we close this PR?

**Comment by jonahwilliams** [comment]
Looked at this again last week , there is some issue with signal handling wherein killing the tool process does not kill the sub process.  @jonasfj you mentioned this might be related to the dartdev tooling right? Is there anything we could do on the flutter side or do we need to update Dart?

**Comment by jonasfj** [comment]
@jonahwilliams,
Hmm, is the problem only to do with force termination through sending a signal like sigint (ctrl+c) ?

**Comment by jonahwilliams** [comment]
Yeah, Ctrl+C on windows

**Comment by jonahwilliams** [comment]
Related issues:

https://github.com/dart-lang/sdk/issues/41978
https://github.com/dart-lang/sdk/issues/42092

**Comment by zanderso** [comment]
This looks blocked, so I'm marking it WIP.

**Comment by zanderso** [comment]
Maybe unblocked? https://github.com/dart-lang/sdk/commit/c40ebbc65eff63667ea989a2aceec5603ae1c29c

**Comment by zanderso** [comment]
@jonahwilliams ping

**Comment by jonahwilliams** [comment]
I updated this PR to ToT, however it still doesn't quite work. I've observed either no output or pub returning exit code 64.

```
jonahwilliams-macbookpro2:flutter_tools jonahwilliams$ flutter pub run test
INTERACTIVELy <- print added more process.start

```

then it hangs. When run with `-v`:

```
INTERACTIVELy
[   +8 ms] executing: /Users/jonahwilliams/Documents/flutter/bin/cache/dart-sdk/bin/pub run test -v
[ +511 ms] "flutter run" took 539ms.
[   +4 ms] pub finished with exit code 64
[   +1 ms] 
```

**Comment by jonahwilliams** [comment]
To be honest, I don't really know what needs to be done to make this work.

**Comment by jonahwilliams** [comment]
@jonasfj I don't think this is going to start working without some investigation into dart/dart:io's behavior. I'm going to close this PR for now

**Comment by jonasfj** [comment]
Okay, maybe we should reconsider how we do this, and if we should instead embed the `pub` command as an `Command` object from `package:args` -- we have some plans to do that for `dart pub` anyways.

**Pull request closed without merging**
