### PR TITLE
Fixed: DropdownMenu throws exception when it is in any scrollable list view and scrolls quickly #139871

### PR DESCRIPTION
**Pull request by faisalansari0367**
Fixed: DropdownMenu throws exception when it is in any scrollable list view and scrolls quickly #139871

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Hi @faisalansari0367 thanks for contributing! This will need a test to verify it works as expected, and to prevent us from regressing in the future. :)

**Comment by Piinks** [comment]
Can you also sign the CLA and fix the analysis failure?

**Comment by faisalansari0367** [comment]
Screenshot 2023-12-16 at 3 58 17 PM
Getting this although I have already signed the CLA.

**Comment by faisalansari0367** [comment]
Hi @Piinks,
Thanks for your response I am trying to write a test for the same. 
Can you please help why the Linux analyze test is failing with `no space after flow control statement` this message?

**Comment by bleroux** [comment]
> Can you please help why the Linux analyze test is failing with `no space after flow control statement` this message?

This is because of this line: `if(!mounted) {`.
A space is required after the `if` keyword.
I also noticed you added an extra empty line, on line 7, thank you to remove it.

**Comment by faisalansari0367** [comment]
> > Can you please help why the Linux analyze test is failing with `no space after flow control statement` this message?
> 
> This is because of this line: `if(!mounted) {`. A space is required after the `if` keyword. I also noticed you added an extra empty line, on line 7, thank you to remove it.

Thank you so much @bleroux for your inputs. Can you also help me with the CLA?

**Comment by bleroux** [comment]
> Can you also help me with the CLA?

The only CLA experience I have is that I signed it some years ago.

The 'Details' link associated with the `cla/google` gives the two following hints:

**Help! I've signed the CLA, but it's still showing me as unsigned.**

- It's possible we don't have your GitHub username. Verify that [your existing CLA data](https://cla.developers.google.com/clas) is accurate.
- You may not be using the email associated with your CLA in your Git commits. Check that the [email set on your git commits](https://help.github.com/articles/setting-your-email-in-git/) matches the [email associated with your CLA](https://cla.developers.google.com/clas).

**Comment by faisalansari0367** [comment]
> > Can you also help me with the CLA?
> 
> The only CLA experience I have is that I signed it some years ago.
> 
> The 'Details' link associated with the `cla/google` gives the two following hints:
> 
> **Help! I've signed the CLA, but it's still showing me as unsigned.**
> 
> * It's possible we don't have your GitHub username. Verify that [your existing CLA data](https://cla.developers.google.com/clas) is accurate.
> * You may not be using the email associated with your CLA in your Git commits. Check that the [email set on your git commits](https://help.github.com/articles/setting-your-email-in-git/) matches the [email associated with your CLA](https://cla.developers.google.com/clas).

Thanks again @bleroux I will surely try these, You're awesome 😇.

**Pull request closed without merging**
