### PR TITLE
Delete native_ui_tests_ios

### PR DESCRIPTION
**Pull request by jmagman**
Should have been included in https://github.com/flutter/flutter/pull/103666.

First part of https://github.com/flutter/flutter/issues/95193

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by christopherfujino** [comment]
Won't this still be red until the ci_yaml roller finishes?

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/103666 was reverted with https://github.com/flutter/flutter/pull/103726, this should merge first.

**Comment by christopherfujino** [comment]
To follow-up from discord discussion, I landed my revert instead and this deprecation will be re-landed in two PRs; the first removing the builders, the second deleting the test code

**Comment by keyonghan** [comment]
@christopherfujino I believe this is safe to land. Any concern here to close this PR?

**Comment by christopherfujino** [comment]
Oops, sorry, yeah, we should land this

**Comment by jmagman** [comment]
> I landed my revert instead and this deprecation will be re-landed in two PRs; the first removing the builders

This would be the first PR then.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by keyonghan — APPROVED** [review]
LGTM

**Pull request merged**
