### PR TITLE
Flutter Framework Beta 1.21.0-9.2.pre cherry picks

### PR DESCRIPTION
**Pull request by christopherfujino**
I accidentally closed https://github.com/flutter/flutter/pull/64680 and cannot re-open, so I'm recreating the PR with this one.

## Scheduled cherrypicks
* Engine cherry picks https://github.com/flutter/engine/pull/20797
* Cannot return with NULL from Isolate: Exception
  * Issue https://github.com/flutter/flutter/issues/63590
  * PR https://github.com/flutter/flutter/pull/63515
  * [Commit afc95099](https://github.com/flutter/flutter/commit/afc9509996b334b71f51f625125c232dce649606)
  * Author @a14n 
* Wrong hour/minute order in TimePicker
  * Issue https://github.com/flutter/flutter/issues/63427
  * PR https://github.com/flutter/flutter/pull/64097
  * Author @rami-a 

## Test/Infra Only Cherrypicks
- https://github.com/flutter/flutter/pull/63806
- https://github.com/flutter/flutter/pull/63796

### CODE REVIEW

**Comment by christopherfujino** [comment]
@a14n would you mind letting the CLA bot know it's ok to cherry pick your commit?

**Comment by a14n** [comment]
@googlebot I consent

**Comment by christopherfujino** [comment]
@a14n thanks!

**Review by pcsosinski — APPROVED** [review]
approved.  engine hash shows a web test failing FYI

**Pull request merged**
