### PR TITLE
fix memory leak of android view

### PR DESCRIPTION
**Pull request by Stonekity**
## Description

fix memory leak of android view

## Related Issues

#50104

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

 - [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
 - [x] I signed the [CLA].
 - [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
 - [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
 - [x] I updated/added relevant documentation (doc comments with `///`).
 - [x] All existing and new tests are passing.
 - [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
 - [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by goderbauer** [comment]
@Stonekity Thanks for your contribution! As per our policy we require that all changes have a test to ensure that we never regress this behavior and re-introduce the bug. Can you please add a test?

**Comment by Stonekity** [comment]
> @Stonekity Thanks for your contribution! As per our policy we require that all changes have a test to ensure that we never regress this behavior and re-introduce the bug. Can you please add a test?

@goderbauer, Thanks for your reply, Do you have any relevant documents to explain how to test this problem? At present, I use demo to verify this problem. There is a GIF picture on it, which shows the test results of devtools. The results show that the problem has been solved

**Comment by liyuqian** [comment]
@Stonekity : https://github.com/flutter/flutter/pull/46184 is an example memory test that you may follow. Please let me know if you have any questions. I'm very happy to help.

**Comment by Stonekity** [comment]
> @Stonekity : #46184 is an example memory test that you may follow. Please let me know if you have any questions. I'm very happy to help.

Thanks buddy, I'll take a look at it.

**Comment by xster** [comment]
@jason-simmons I remember you may have fixed a similar issue recently

**Comment by gaaclarke** [comment]
@Stonekity Since this people are waiting for this fix in issue https://github.com/flutter/flutter/issues/56442 I've added a test for you =)

**Review by gaaclarke — APPROVED** [review]

**Pull request merged**
