### PR TITLE
Use a fake stopwatch to remove flakiness.

### LINKED ISSUE #133215: Test fails based on time taken rather than testing the actual condition
In this PR: https://github.com/flutter/flutter/pull/132239

A test was added that looks for output that it expects to have "0ms" as the run time. That is not a reliable condition on test hosts and presumably doesn't actually test that the behavior was actually disabled, just that it doesn't take "much" time.

A failure on this test can derail an engine roll as seen here: https://cirrus-ci.com/task/5417897460236288?logs=main#L1130

### PR DESCRIPTION
**Pull request by Hixie**
Fixes https://github.com/flutter/flutter/issues/133215

### CODE REVIEW

**Comment by Hixie** [comment]
cc @flar

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
> I'm not sure what the fake stopwatch is, so I can't really evaluate this. Since the success metric on the original test case seemed to be its timing output, it sounds like the fake stopwatch might fake the success metric itself?

Really what we care about here is that there are no spinner animation characters

**Comment by Hixie** [comment]
I swear I've run into more flakes (mostly around the Google testing shard) trying to fix this flake than this flake itself has ever caused! :sweat_smile:

**Comment by Hixie** [comment]
manually merging on red because the red is false red.

**Pull request merged**
