### PR TITLE
Add material icons golden test

### PR DESCRIPTION
**Pull request by guidezpl**
Reland https://github.com/flutter/flutter/pull/73361 (reverted in https://github.com/flutter/flutter/pull/73521) by using a more robust method for obtaining the flutter root directory.

Adds a golden test for a few enlarged material icons (first, last, and variants). This will help validate upcoming icon font updates

Screenshot 2021-01-05 at 22 51 23

### CODE REVIEW

**Review by Piinks — APPROVED** [review]
LGTM! Thanks for updating this! :)

**Comment by Hixie** [comment]
I'm getting this in the logs when I run tests:
```
No expectations provided by Skia Gold for test: material.test.icons.sample.png. This may be a new test. If this is an unexpected result, check https://flutter-gold.skia.org.
Validate image output found at file:///home/ianh/dev/flutter/bin/cache/pkg/skia_goldens/packages/flutter/test/material/
```

Did we maybe never actually validate the goldens? It doesn't seem to fail the test, which seems weird.

**Comment by guidezpl** [comment]
Looks like I validated Windows and macOS, missing the golden for Linux (I just validated that one). I checked the LUCI logs and the test did indeed pass. I'm not sure why...

**Comment by Hixie** [comment]
Cool, thanks for looking into it. Would you mind filing a bug to remind us to make this a fatal error in the future?

**Comment by guidezpl** [comment]
Sure, filed https://github.com/flutter/flutter/issues/74712

**Pull request merged**
