### PR TITLE
Upgrade vm_service.

### PR DESCRIPTION
**Pull request by polina-c**
Command:

```
../../bin/flutter update-packages --cherry-pick-package vm_service --cherry-pick-version 14.1.0
```

### CODE REVIEW

**Comment by polina-c** [comment]
Error:

```
01:57 +17 ~1 -1: test/integration.shard/test_test.dart: flutter test should run a test when its name matches a regexp when --experimental-faster-testing is set [E]                                    
  Expected: a process with exit code 0 and stdout: "RegExp: pattern=\+\d+: All tests passed! flags="
    Actual: <Instance of 'ProcessResult'>
     Which: Actual exitCode was 1
            Actual stdout:
            [ERROR:flutter/shell/testing/tester_main.cc(671)] Unhandled exception
            Exception: 'file:///b/s/w/ir/x/w/flutter/dev/automated_tests/build/isolate_spawning_tester/root_test_isolate_spawner.dart': error: build/isolate_spawning_tester/root_test_isolate_spawner.dart:70:16: Error: The method 'toNativeUtf8' isn't defined for the class 'String'.
            Try correcting the name to the name of an existing method, or defining a method named 'toNativeUtf8'.
                          .toNativeUtf8()) as void Function(SendPort),
                           ^^^^^^^^^^^^
            Stack trace: #0      _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
            #1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
            #2      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
            
            
            Actual stderr:
            Error: Couldn't resolve the package 'ffi' in 'package:ffi/ffi.dart'.
            build/isolate_spawning_tester/child_test_isolate_spawner.dart:5:8: Error: Not found: 'package:ffi/ffi.dart'
            import 'package:ffi/ffi.dart';
                   ^
```

**Comment by polina-c** [comment]
@bkonyi @derekxu16 @a-siva 

Upgrade of vm_service for flutter results in ffi issue. Any ideas what can it be?

**Comment by derekxu16** [comment]
The problem is that `flutter update-packages` removed the `ffi` dependency from `package:flutter_tools`. The context for why the dependency was added is explained here (https://github.com/flutter/flutter/pull/141726#discussion_r1470086546) and here (https://github.com/flutter/flutter/pull/141726#discussion_r1490146548). I must have added the depedency incorrectly. @christopherfujino, can you please let me know how I can add the `ffi` dependency in a way such that it doesn't get removed by `flutter update-packages`? Thanks!

**Comment by polina-c** [comment]
> The problem is that `flutter update-packages` removed the `ffi` dependency ...

Added ffi as direct dependency. Let's see if tests pass.

**Comment by christopherfujino** [comment]
Was the issue here that vm_service removed the dependency to package:ffi, and flutter_tools was relying on it being present transitively via vm_service? If so, then I agree, explicitly adding package:ffi as a direct dep is the right way forward.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
