### PR TITLE
Internalize our dependency on the Dart SDK

### LINKED ISSUE #54: Download the Dart SDK automatically
Developers using Flutter or contributing to the Flutter framework shouldn't need to download their own copy of the Dart SDK.  Instead, we should manage that dependency automatically from the flutter.git repository.

### PR DESCRIPTION
**Pull request by abarth**
This patch teaches the flutter command to download the Dart SDK into
cache, removing another step from the Getting Started workflow. The
version of the Dart SDK is controlled by the "dart-sdk.version" file in
the bin/cache directory.

Fixes #54

### CODE REVIEW

**Comment by abarth** [comment]
@devoncarew @Hixie @chinmaygarde

**Comment by abarth** [comment]
@tvolkert

**Comment by abarth** [comment]
@sethladd

**Comment by chinmaygarde** [comment]
lgtm

**Comment by eseidelGoogle** [comment]
lgtm.  We can also now remove infra/download_dart_sdk.py (after updating
the bots of course).

**Comment by Hixie** [comment]
landing this to test it

**Pull request merged**
