### PR TITLE
use 'dart pub' instead of calling the pub executable directly

### PR DESCRIPTION
**Pull request by devoncarew**
- use 'dart pub' instead of calling the pub executable directly (bare use of the `pub` executable is being deprecated)

*List which issues are fixed by this PR. You must list at least one issue.*

- this is part of the work towards https://github.com/dart-lang/sdk/issues/46100

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

n/a

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by devoncarew** [comment]
I can't tell whether this PR is [test-exempt](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests) or not; it will be exercised by the CI as part of the doc generation process.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by gspencergoog** [comment]
I don't think it's test exempt.  There already is a test for this script at https://github.com/flutter/flutter/blob/master/dev/tools/test/dartdoc_test.dart

You could add a test in there with the fake process manager that makes sure it calls "dart pub" as part of an operation.

**Comment by gspencergoog** [comment]
It might help to refactor some of those calls into separate functions, and test those functions in isolation.

It's a pretty huge `main()` as it is.

**Review by jonasfj — APPROVED** [review]

**Comment by devoncarew** [comment]
Gotcha, thanks! I introduced a small abstraction - a `runPubProcess` method that the script calls, and added a test for it in `dev/tools/test/dartdoc_test.dart` (testing that we're not calling the pub binary directly).

**Pull request merged**
