### PR TITLE
fix-remove-useless-right-margin

### PR DESCRIPTION
**Pull request by EArminjon**
ExpansionPanel put a hardcoded margin at the right of the expand icon. This margin seems to not respond to any purpose. Because of this unexpected margin, some alignment issue can happen inside apps.

the margin is visible at the right of the chevron icon  :

Capture d’écran 2024-01-03 à 11 40 00

After this PR : 

Capture d’écran 2024-01-03 à 11 39 52

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by HansMuller — COMMENTED** [review]
Useless or not, we can't accept an unconditional change to this part of the AppBar layout because it would break an enormous number of existing layouts and tests.

**Comment by EArminjon** [comment]
> Useless or not, we can't accept an unconditional change to this part of the AppBar layout because it would break an enormous number of existing layouts and tests.

This PR didn't impact the AppBar widget it's just around the ExpansionPanel header icon.

Also I wonder about the Material Design. Does this widget today respect the material specs ?

**Comment by HansMuller** [comment]
Sorry, you're right, I meant ExpansionPanel not AppBar.

> Also I wonder about the Material Design. Does this widget today respect the material specs ?

Material Design dropped the expansion panel component, it's no longer part of the spec.

**Comment by EArminjon** [comment]
@HansMuller does this PR still valid if i fix ExpansionPanel unit tests ?

**Comment by HansMuller** [comment]
@EArminjon - I'm going to close this PR. If you'd like to keep working on it, feel free to reoopen it.

To eliminate the right margin without breaking existing layouts and tests, you'd need to expose the icon's padding as a default-null parameter that's used like this:

```dart
      Widget expandIconContainer = Container(
        margin: widget.expandIconMargin ?? const EdgeInsetsDirectional.only(end: 8.0),
        ...
```

You'd also need to include a test that checked the new parameter.

**Pull request closed without merging**
