### PR TITLE
[Material] Fix radio ink ripple to be centered

### PR DESCRIPTION
**Pull request by rami-a**
## Description

This change updates the position of the ink ripple for the radio button component to be centered. See screenshots for before/after.

Also added a golden test. See golden at: https://github.com/flutter/goldens/commit/07881de0d5ddb4a84cb83b7d8965ff220ceac753

| Before | After |
| - | - |
|radio-before|radio-after|

## Related Issues

None

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes tests for *all* changed/updated/fixed behaviors (See [Test Coverage]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by johnsonmh — APPROVED** [review]
LGTM, nice!

**Comment by goderbauer** [comment]
Any chance you can add a test for this (see checklist) to ensure this never breaks again?

**Review by clocksmith — APPROVED** [review]

**Review by willlarche — APPROVED** [review]
This is fantastic.

**Review by clocksmith — APPROVED** [review]

**Comment by rami-a** [comment]
Thanks for the review everyone, please also take a look at the golden test I added.

**Review by HansMuller — APPROVED** [review]
NICE

LGTM

**Comment by Hixie** [comment]
FYI, you can make the golden image smaller by putting the repaint boundary inside the Center instead of outside it.

**Pull request merged**
