### PR TITLE
Flutter sprites test

### PR DESCRIPTION
**Pull request by devoncarew**
Add a test for the `flutter_sprites` package (redux of https://github.com/flutter/flutter/pull/909); this lets the `flutter analyze --flutter-repo` command analyze the flutter_sprites package.

### CODE REVIEW

**Comment by devoncarew** [comment]
I do see exceptions from the analyzer package locally when trying to run the full flutter `analyze --flutter-repo` command - don't know how the travis bot will be effected.

**Comment by devoncarew** [comment]
Here are the current analysis issues for that package (also tracked here: https://github.com/flutter/flutter/issues/1013). We may want to wait to land this PR until after those issues are fixed, to keep the bot green.

```
[error] Type check failed: _effectPlayer.play(effect, false, (volume + evt.volumeVariance * randomSignedDouble()).clamp(0.0, 2.0), (pitch + evt.pitchVariance * randomSignedDouble()).clamp(0.5, 2.0), (pan + evt.panVariance * randomSignedDouble()).clamp(-1.0, 1.0), (SoundEffectStream s) {playingList.remove(newPlaying);}) (Future<SoundEffectStream>) is not of type SoundEffectStream (/home/travis/build/flutter/flutter/packages/flutter_sprites/lib/src/sound_manager.dart, line 120, col 25)
[warning] The method 'sharedInstance' is not defined for the class 'SoundEffectPlayer' (/home/travis/build/flutter/flutter/packages/flutter_sprites/lib/src/sound_manager.dart, line 67, col 55)
[warning] The method 'stop' is not defined for the class 'SoundEffectPlayer' (/home/travis/build/flutter/flutter/packages/flutter_sprites/lib/src/sound_manager.dart, line 88, col 23)
[warning] A value of type 'Future<SoundEffectStream>' cannot be assigned to a variable of type 'SoundEffectStream' (/home/travis/build/flutter/flutter/packages/flutter_sprites/lib/src/sound_manager.dart, line 120, col 25)
[warning] 1 positional arguments expected, but 6 found (/home/travis/build/flutter/flutter/packages/flutter_sprites/lib/src/sound_manager.dart, line 120, col 43)
[warning] The setter 'volume' is not defined for the class 'SoundEffectStream' (/home/travis/build/flutter/flutter/packages/flutter_sprites/lib/src/sound_manager.dart, line 138, col 71)
[warning] The getter 'volume' is not defined for the class 'SoundEffectStream' (/home/travis/build/flutter/flutter/packages/flutter_sprites/lib/src/sound_manager.dart, line 138, col 98)
[warning] The method 'stop' is not defined for the class 'SoundEffectPlayer' (/home/travis/build/flutter/flutter/packages/flutter_sprites/lib/src/sound_manager.dart, line 139, col 79)
[warning] The method 'stop' is not defined for the class 'SoundEffectPlayer' (/home/travis/build/flutter/flutter/packages/flutter_sprites/lib/src/sound_manager.dart, line 145, col 25)
[warning] 1 positional arguments expected, but 3 found (/home/travis/build/flutter/flutter/packages/flutter_sprites/lib/src/sound_manager.dart, line 204, col 24)
```

**Comment by Hixie** [comment]
LGTM modulo #1013. Thanks for doing this!

This will fix #759.

**Comment by sethladd** [comment]
cc @vlidholt can you help land this?

**Comment by devoncarew** [comment]
We'll likely want to get the analysis issues fixed before this lands.

**Comment by devoncarew** [comment]
Looks like adding this package to analysis uncovers a bug in the command-line analyzer (https://travis-ci.org/flutter/flutter/builds/102399407#L287). I believe this is one that exists on the stable sdk and is fixed in the dev sdk. Landing this PR while we're still testing against `1.13.0` would turn the bot red :(

**Comment by Hixie** [comment]
I don't really understand the travis failure.

**Comment by devoncarew** [comment]
The command line analyzer is throwing an exception when analyzing these files. It only shows up w/ this file set and the cli options we're passing in. The bug is fixed in the dev sdk - I think we have to wait until 1.14.0 is stable before we can land this -

**Comment by Hixie** [comment]
Do you know what the bug actually is?

**Comment by devoncarew** [comment]
No, not specifically. This was one exception: https://github.com/dart-lang/sdk/issues/25305. Note that `flutter analyze --flutter-repo` does not have the exception when run w/ `Dart VM version: 1.14.0-dev.7.0`.

**Comment by Hixie** [comment]
Hmm, I wonder if there a type annotation comment in there somewhere... Will
keep looking.

**Comment by Hixie** [comment]
Wow, if I just inline the files instead of using "part", that fixes it.

**Comment by Hixie** [comment]
I have it narrowed down to:
```dart
import 'package:box2d/box2d.dart' as box2d;

import 'src/action.dart';
import 'src/action_spline.dart';
import 'src/color_sequence.dart';
import 'src/constraint.dart';
```

...where the four `src/*.dart` files are 0 bytes long.

**Comment by Hixie** [comment]
Removing the box2d package import, with no other changes, also fixes the analyzer crash (at the cost of breaking all the code, obviously).

**Comment by Hixie** [comment]
I'm checking this in since the weather demo means that we're analyzing flutter_sprites now anyway.

**Pull request merged**
