### PR TITLE
re-write flutter analyze to use the analysis server

### PR DESCRIPTION
**Pull request by devoncarew**
This is a redux of https://github.com/flutter/flutter/pull/16281

- it's been updated to work with the latest source from master
- we've worked to make the `flutter analyze --flutter-repo` use case faster in the upstream analysis server from the dart sdk, and have some more optimizations we're working on to do with the architecture of lints

### CODE REVIEW

**Comment by devoncarew** [comment]
Here's the latest - a comparison between flutter at head and this PR, run locally on my machine:

## current:

flutter analyze --flutter-repo
- 43.3s
- 41.9s
- 40.7s

flutter analyze (DartConf / conference_app)
- 6.0s
- 5.2s
- 5.3s

flutter analyze --flutter-repo switching branches (31156aed4 4f31a3f51 9e0a6107f)
- 42.3s
- 45.0s
- 41.4s

## refactor PR:

flutter analyze --flutter-repo
- 73.3s
- 70.2s
- 70.3s

flutter analyze (DartConf)
- 7.4s
- 6.9s
- 6.9s

flutter analyze --flutter-repo modifying core files, w/o clearing the analysis cache
- 44.4s
- 7.9s
- 43.9s

flutter analyze --flutter-repo, few files changed, w/o clearing the analysis cache
- 10.1s
- 10.2s
- 10.1s

flutter analyze (DartConf / conference_app), few files changed, w/o clearing the analysis cache
- 1.9s
- 2.6s
- 2.4s

## Overall:

- flutter analyze --flutter-repo, first analysis is 40.7s ==> 70.2s or __72% slower__
- flutter analyze --flutter-repo, 2nd analysis is 40.7s ==> 10.1s or __4x faster__
- flutter analyze on a user app, first analysis is 5.2s ==> 6.9s or __33% slower__
- flutter analyze on a user app, 2nd analysis is 5.2s ==> 1.9s or __2.7x faster__
- flutter analyze --flutter-repo, simulated branch switching, 41.4s ==> [7.9s to 43.9s], so from between the __same speed as before to up to 5x faster__

I think the net-net is that we'll regress the times for cold analysis for the flutter repo and for project (and what a CI would see), but substantially increase 2nd and later analysis times for the flutter repo and for user projects, and not regress analysis times for switching between branches when working on the flutter repo itself.

**Comment by devoncarew** [comment]
I'd like to re-land this, based on the original review from @tvolkert and @danrubel, and after a discussion w/ @Hixie about the performance regression for the `flutter analyze --flutter-repo` use case.

**Comment by tvolkert** [comment]
LGTM

**Comment by Hixie** [comment]
the dartdocs benchmark went crazy right on this commit.

**Comment by devoncarew** [comment]
OK, thanks for the heads up. I'm OOO this week, but will take a look when I'm back.

**Comment by 0503256405** [comment]
> This is a redux of #16281
> 
> * it's been updated to work with the latest source from master
> * we've worked to make the `flutter analyze --flutter-repo` use case faster in the upstream analysis server from the dart sdk, and have some more optimizations we're working on to do with the architecture of lints

0503 2564 05

**Comment by 0503256405** [comment]
Umairkhan0503256405@gmail.com 2000umairkhan 5673568467 0503 2564 05

**Pull request merged**
