### PR TITLE
re-add semantic service events for tap and longPress

### LINKED ISSUE #17775: [a11y]: Activating a switch or checkbox with TalkBack no longer gives feedback about state
Turn TalkBack on and double tap on a checkbox or switch. It is supposed to announce how the state changed. However, no announcement is made anymore.

/cc @jonahwilliams

### PR DESCRIPTION
**Pull request by jonahwilliams**
Unreverts https://github.com/flutter/flutter/pull/17269.

Fixes https://github.com/flutter/flutter/issues/17775

### CODE REVIEW

**Comment by goderbauer** [comment]
Why was this reverted in the first place? Is whatever caused the revert fixed?

**Comment by jonahwilliams** [comment]
cc @cbracken - was this a targeted revert or just part of the attempts to get the Gallery working again?

**Comment by jonahwilliams** [comment]
From https://github.com/flutter/flutter/issues/17775#issuecomment-392207744 - this PR was linked to test failures in the gallery device lab tests. I've run these locally on one configuration and I think the underlying issue was fixed.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Will track the build status tonight and revert immediately if there are any new flakes or failures.  Hopefully there won't be, but if there are that could give us a better clue as to what our test coverage is missing.

**Pull request merged**
