### PR TITLE
Testing tryjob triage

### PR DESCRIPTION
**Pull request by Piinks**
## Description

This PR is to check for a potential bug where triaged tryjob results on Gold do not carry over to master.

## Tests

Small golden file test to check triage flow.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Piinks** [comment]
I would like to land this to verify the triaged result shows up correctly on master. I can revert it after confirming.

**Comment by Piinks** [comment]
cc/ @kjlubick

**Review by LongCatIsLooong — APPROVED** [review]

**Comment by Piinks** [comment]
Tryjob has been triaged. Re-running tasks.

I noticed when I triaged that I could click the checkmark, and it turned green as if it had been triaged, but a small snackbar indicated I was not signed in. I refreshed, and the result changed back to being untriaged. Logged in and triaged again. 

Maybe the checkmark turning green sans log in is causing a misconception about triage status? Although, I don't know how it would make pre-submit checks pass if it has not been triaged.

**Comment by Piinks** [comment]
The tryjob appears to have transitioned to master on Gold without any issue. 
No digest appeared for triage under By Blame. 
I have confirmed the tryjob test result now shows under By Test as a positive result at head. 
I updated the branch of another change (#47551) to run a tryjob against this test without additional triage, and it passed. 

At this point, I am not sure what caused the triage breakdown from #47837 as it worked in this case and did not reproduce the issue. I am going to revert this test change now, and will continue to monitor in case the issue presents itself again.

**Pull request merged**
