### PR TITLE
Update xcode project template to 9.1

### PR DESCRIPTION
**Pull request by xster**

### CODE REVIEW

**Comment by mit-mit** [comment]
Verified that this causes xCode 9.1 to open cleanly without any warnings, yay!

**Comment by mit-mit** [comment]
Two remaining issues I see:

1. An icon warning: "/Users/mit/tmp/xp1/ios/Runner/Assets.xcassets: A 1024x1024 app store icon is required for iOS apps"
1. After running: "2017-11-24 09:22:08.376694+0100 Runner[7523:10781563] You've implemented -[<UIApplicationDelegate> application:didReceiveRemoteNotification:fetchCompletionHandler:], but you still need to add "remote-notification" to the list of your supported UIBackgroundModes in your Info.plist."

Should we handle those as separate issues?

**Comment by cbracken** [comment]
I'm fine with us following up with those two issues as followups. Thanks for doing this cleanup.

@xster can you file an issue for (1)? Looks like there's already related issue #9984 for (2).

**Comment by cbracken** [comment]
lgtm

**Review by cbracken — APPROVED** [review]

**Comment by xster** [comment]
https://github.com/flutter/flutter/issues/13237

**Pull request merged**
