### PR TITLE
validate infra configs in flutter/flutter

### PR DESCRIPTION
**Pull request by XilaiZhang**
following steps in https://g3doc.corp.google.com/company/teams/flutter/release/workflows.md?cl=head to validate infra config. added a new line

### CODE REVIEW

**Comment by CaseyHillers** [comment]
We can ack Mac gradle_plugin_light_apk_test not running as it was removed from tip of tree

**Comment by CaseyHillers** [comment]
> Thanks for the instructions! Does it sound right if I cherrypick the newest commit from blasten?(https://github.com/flutter/flutter/commit/b7a64b76fa7362e6985fe0e8e9f53766dc9d5153)

No, as we still want to run it in post-submit

**Comment by XilaiZhang** [comment]
> No, as we still want to run it in post-submit
Thanks for the reply! I might be wrong since I still need to learn what are qualified as post submits, but I deleted the gradle_plugin_light_apk_test manually in a newest commit

**Comment by CaseyHillers** [comment]
Please revert https://github.com/flutter/flutter/pull/100108/commits/9596a315a2f7c90aac73d552838dbc2b6371ca96 as it's not necessary:
1. You're diverging the branch
2. We'll need to regenerate the flutter/infra configs

**Comment by CaseyHillers** [comment]
Once your flutter/engine PR lands, you'll need to update the pinned version with the merged commit. Other than that, this lgtm

**Comment by CaseyHillers** [comment]
See https://cs.opensource.google/flutter/flutter/+/master:bin/internal/engine.version

**Comment by CaseyHillers** [comment]
Any issues with this? You need to roll https://github.com/flutter/engine/pull/32025 in to be able to release it

**Pull request closed without merging**
