### PR TITLE
Add SliverFill

### PR DESCRIPTION
**Pull request by abarth**
SliverFill fills the remaining space in the viewport with each box
child. We'll use this sliver as a building block for pageable lists.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie

**Comment by Hixie** [comment]
why use a multichild model?

**Comment by abarth** [comment]
It can't be a Sliver-to-Sliver widget because you can't force your child sliver to be a particular size.  That means it needs to be a Sliver-to-Box widget.  You could have a version that was a single Box child, but this version is more general than that.  Plus, it's exactly what we need to build pageable.  (If we tried to build pageable out of the single Box version, it wouldn't be lazy.)

**Comment by Hixie** [comment]
oh i misunderstood what this was for. I thought it was for the vertical to horizontal adapter, going in the vertical list below an app bar and containing a horizontal Pageable, as opposed to being the Pageable's own sliver list.

As written this widget has weird effects. e.g. consider if it isn't the only thing in the list. scrolling by page will be weird.

**Comment by abarth** [comment]
The "scrolling by page" concept doesn't exist yet.  I think we have different ideas about how that is going to work.

**Comment by Hixie** [comment]
LGTM

**Pull request merged**
