### PR TITLE
fix framework to match new mojo sdk

### PR DESCRIPTION
**Pull request by Hixie**
The dart bindings changed semantics in a non-compatible way.

### CODE REVIEW

**Comment by Hixie** [comment]
This is expected to fail on Travis.

**Comment by Hixie** [comment]
I'll check this in immediately prior to revving the engine on the framework side.

**Comment by tonygentilcore** [comment]
The changes in the patch all lgtm -- but no idea if any places were missed.

**Comment by tonygentilcore** [comment]
btw, this needs to come w/ a pubspec.yaml change, right?

**Comment by Hixie** [comment]
The pubspec.yaml change will come as part of the engine rev. I can do it as part of this patch if you like. I guess that would minimise the window of breakage.

**Comment by Hixie** [comment]
I've rolled the pubspec.yaml change into this.

**Pull request merged**
