### PR TITLE
Make sure `flutter update-packages --verify-only` has a non-zero exit code

### PR DESCRIPTION
**Pull request by jonahwilliams**
Also fixes typo in message.  Required to make analysis fail for flutter build

### CODE REVIEW

**Review by tvolkert — APPROVED** [review]
LGTM

**Comment by cbracken** [comment]
This appears to have broken Travis and Appveyor at head.

**Comment by tvolkert** [comment]
Reverted

**Comment by jonahwilliams** [comment]
I continue to be reminded that travis is not tap 🥇

**Comment by cbracken** [comment]
Not having TAP is the best (possibly *only*) way to really appreciate the miracle of TAP.

**Pull request merged**
