### PR TITLE
Made LayoutBuilder's builder param required as well as added null check

### LINKED ISSUE #51363: LayoutBuilder's builder param should be required
RE:https://github.com/flutter/flutter/blob/0b8abb4724/packages/flutter/lib/src/widgets/layout_builder.dart#L203
Seeing as a `LayoutBuilder` with no child widget is useless, i proposed that the param should be required.

### PR DESCRIPTION
**Pull request by maschad**
## Description
A LayoutBuilder without a child as parameter would have no use so it's been added.

## Related Issues
Fixes [#51363](https://github.com/flutter/flutter/issues/51363)

## Tests
Given that super constructor for this class would throw an error if the builder parameter is null, I am unsure of how to write a meaningful test for this fix. As mentioned [here](https://github.com/flutter/flutter/issues/51363#issuecomment-590736260) . I am seeking some guidance on how the analyzer behavior could be tested to catch this particular fix @Hixie .

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [x] Yes, this is a breaking change. *If not, delete the remainder of this section.*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by maschad** [comment]
@googlebot I signed it!

**Comment by goderbauer** [comment]
You could test that when you pass in `null` for the builder argument an assertionError is thrown.

**Comment by maschad** [comment]
@goderbauer I was thinking that as well, but as @dnfield mentioned [here](https://github.com/flutter/flutter/issues/51363#issuecomment-590736260)  that would be a false positive since the super constructor would throw an assertion as well.

**Comment by dnfield** [comment]
The "real" test for this would be to run the analyzer on code that fails to do this and make sure that analysis picks up the issue here.  That's what this is really fixing.

I'm inclined to say we shouldn't bother with that, and instead focus on NNBD efforts, which will be changing this code around anyway and add better support from the langauge that would make this code an error that needs to be fixed.

I'm fine with this change as is.  @hixie - can we get an exception from the need to test this?

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
I'm voting we land this on the idea that a test for it will soon be useless since when we go to the null-saftey version of this the langauge keyword `required` will be mandatory, and whatever test we devise for this now would have to be retired (since it will no longer be an optional analysis lint but an actual compiler error).

If my understanding is wrong we can revisit adding a test for this, and other similar places in the codebase where we're missing `@required` on a subclass or composing class.

**Comment by goderbauer** [comment]
Sounds good.

**Comment by slightfoot** [comment]
@maschad Thanks for landing this change. Been bugging me for sometime.

**Pull request merged**
