### PR TITLE
Roll engine manual 31cd2dfca22a...b358dc58fbce (39 commits)

### PR DESCRIPTION
**Pull request by GaryQian**
Manual roll to update tests for https://github.com/flutter/engine/pull/13795

git@github.com:flutter/engine.git/compare/31cd2dfca22a...429e56e97427

git log 31cd2dfca22a..b358dc58fbce --no-merges --oneline
b358dc58fb Remove extra shadows from Web Engine EngineParagraphStyle (#13805)
6936b489b3 Roll src/third_party/dart d5d889668b..ffbd2eb7ee (15 commits)
a5680f9388 [dart_runner] Initialize logging and tracing (#13829)
198c2a7ddc Update version of dart/language_model distributed with flutter engine to latest (#13799)
2877aa470b Roll src/third_party/dart 5cce1e4acd..d5d889668b (17 commits) (#13806)
e5b4eabc4a Roll fuchsia/sdk/core/mac-amd64 from p9FbP... to _QV9E... (#13823)
2da2136153 Revert "Roll src/third_party/skia d860a78fd60c..581108137b46 (13 commits) (#13800)" (#13828)
7b0c11e707 Roll fuchsia/sdk/core/mac-amd64 from tZdOC... to p9FbP... (#13801)
7041238576 Create a WeakPtrFactory for use on the UI thread in VsyncWaiter (#13781)
1a8bc658a0 Roll src/third_party/skia d860a78fd60c..581108137b46 (13 commits) (#13800)
429e56e974 Roll src/third_party/dart 7ebc820ffc..5cce1e4acd (1 commits) (#13798)
a59c96910d Document the coordinate space of points in FlutterPointerEvent. (#13782)
dee42b4ead implement radial gradient in canvaskit backend (#13796)
db23a6cabf Adds missing comma in EngineParagraphStyle.toString() (#13795)
270fa824e4 Roll src/third_party/skia ad21d47cfa8d..d860a78fd60c (2 commits) (#13794)
885852bd68 Roll src/third_party/dart 7408ed4730..7ebc820ffc (20 commits)
5643988a9d Roll fuchsia/sdk/core/mac-amd64 from TnTbF... to tZdOC... (#13791)
679a4369b2 [web] Implement TextStyle.shadows (#13769)
e19ee72f31 Expose asset lookup from plugin binding. (#42019) (#13743)
c9afadccbf Roll src/third_party/skia 3de645cbca78..ad21d47cfa8d (15 commits) (#13790)
1a7bf8578d Move Path and PathMetrics from canvas.dart into their own files. No delta (#13772)
e150bf3305 Take devicePixelRatio into account when drawing shadows (#13786)
63e8c6275e Add ImageFilter and BackdropFilter to CanvasKit backend (#13768)
6d66993b1d Revert "Reland "Guarding EAGLContext used by Flutter #13314" (#13759)" (#13788)
726e8f54db Add Helvetica and sans-serif as fallback font families (#13784)
164df8e9e0 Roll src/third_party/skia 0fd4f01b9b83..3de645cbca78 (1 commits) (#13776)
f68de3f451 Add line boundary information to LineMetrics. (#13727)
ce0e9e79e6 Fix RendererContextSwitch result check in Rasterizer::MakeRasterSnapshot (#13785)
10d5ed19f8 [web] Fix path to svg for drrect (#13779)
b6e25aa7c9 Roll src/third_party/dart d45c3d15cb..7408ed4730 (20 commits) (#13778)
0172e08078 Roll fuchsia/sdk/core/mac-amd64 from RrTFI... to TnTbF... (#13775)
14cc5195c2 Roll fuchsia/sdk/core/mac-amd64 from 4JJNo... to RrTFI... (#13774)
3fb5d855f2 Roll fuchsia/sdk/core/mac-amd64 from xC_an... to 4JJNo... (#13773)
eec36a8d4f Roll fuchsia/sdk/core/mac-amd64 from eq_Rz... to xC_an... (#13771)
745909b412 Roll src/third_party/skia 4135cf0b57c2..0fd4f01b9b83 (1 commits) (#13770)
2dcfaaeb5d Reland "Guarding EAGLContext used by Flutter #13314" (#13759)
55c64a92d8 Point old plugin registry accessors to new embedding plugin accessors.  (#44225) (#13739)
20e3c5bb83 Revert "[fuchsia] Temporarily disable intl provider (#13696)" (#13721)
8a99d10748 Turn on RasterCache based on view hierarchy (#13762)

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/flutter-engine-flutter-autoroll
Please CC jimgraham@google.com on the revert to ensure that a human
is aware of the problem.

To report a problem with the AutoRoller itself, please file a bug:
https://bugs.chromium.org/p/skia/issues/entry?template=Autoroller+Bug

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+/master/autoroll/README.md

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by flar** [comment]
What is the point of this manual engine roll until either the tests are updated or the extra data in the ParagraphStyle.toString() is removed?

Note, that the comma in https://github.com/flutter/engine/pull/13795 is not the issue - the shadow string itself is the problem whether or not it has a comma.

**Comment by GaryQian** [comment]
Yeah, realized this, I have a PR to fix the web Paragraph style

**Comment by GaryQian** [comment]
Waiting on https://github.com/flutter/engine/pull/13805 to go green, land, and build

**Comment by GaryQian** [comment]
Commit causing failing cirrus was reverted. Landing.

**Pull request merged**
