### PR TITLE
Expose ExpansionTileState

### LINKED ISSUE #60387: Programmatically open and close ExpansionTile Widget.
I was building a Card which would be placed at the bottom of the screen, ExpansionTile is the child of this widget. When I click this card, the showModalBottomSheet() is called in OnExpansionChanged, however, I don't know how to close it. An open and close feature would be nice.

code reference: https://gist.github.com/ritvij-saxena/4726b3a834b8aa4afb7305eda2c970da
Live demo: https://dartpad.dev/4726b3a834b8aa4afb7305eda2c970da

### PR DESCRIPTION
**Pull request by xvrh**
Allows to programmatically expand or collapse an ExpansionTile
Fixes #60387

Example usage:
```dart
class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final GlobalKey<ExpansionTileState> _expansionTileKey = GlobalKey<ExpansionTileState>();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        ExpansionTile(
          key: _expansionTileKey,
          title: const Text('Collapsible menu'),
          children: const <Widget>[
            Text('Menu'),
          ],
        ),
        ElevatedButton(
          onPressed: () {
            ExpansionTileState expansionTile = _expansionTileKey.currentState!;
            if (expansionTile.isExpanded) {
              expansionTile.collapse();
            } else {
              expansionTile.expand();
            }
          },
          child: const Text('TOGGLE MENU'),
        )
      ],
    );
  }
}

```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by xvrh** [comment]
@Hixie I rebased the branch.
I'm available to make any other requested changes.

**Comment by flosketch** [comment]
+1 this PR

**Comment by HansMuller** [comment]
I've been reluctant to review this PR because it's generally not a good idea to turn a State object into public API, since State has many methods that aren't relevant in a case like this. Usually, we've dealt with this case by creating a class like ExpansionTileController that the developer can pass to a ExpansionTile and that exposes only as much API as is needed.

**Comment by xvrh** [comment]
@HansMuller understood!
I went with the public `State` approach as it the obvious one used by `Navigator`, `Scaffold` etc...

I will try with the `ExpansionTileController` way, taking inspiration from `ScrollController`, `TabController` etc...

**Comment by xvrh** [comment]
I'll close this PR and reopen a new one when I have time to work on the `ExpansionTileController` idea.

**Comment by HansMuller** [comment]
@xvrh - there are have been some additional requests for this feature so I'm going to try and land an ExpansionTileController version shortly. What I'm planning is very similar to what you've done, except that the controller's API will be limited to isExpanded, expand() and collapse():
```dart
class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final ExpansionTileController controller = ExpansionTileController();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        ExpansionTile(
          controller: controller,
          title: const Text('Collapsible menu'),
          children: const <Widget>[
            Text('Menu'),
          ],
        ),
        ElevatedButton(
          onPressed: () {
            if (controller.isExpanded) {
              controller.collapse();
            } else {
              controller.expand();
            }
          },
          child: const Text('TOGGLE MENU'),
        )
      ],
    );
  }
}
```
This really is the same thing under the hood, so an ExpansionTileController can only control one ExpansionTile.

**Pull request closed without merging**
