### PR TITLE
InteractiveViewer double tap

### LINKED ISSUE #64156: InteractiveViewer double tap to zoom
It should be easy to support double tap to zoom in InteractiveViewer, one way or another.

It's probably possible to do this currently, but it's pretty difficult:

  1. Pass a TransformationController to your InteractiveViewer.
  1. Listen to double taps by wrapping InteractiveViewer in a GestureDetector.
  1. On double tap, get the value of the TransformationController. Create a new Matrix4 by transforming the value matrix to whatever increase in zoom you want. Set value to the new matrix (or animate it).

Calculating the final matrix is probably the hardest part.  The simplest solution may be just to expose InteractiveViewer's internal transformation methods, like matrixScale in this case, that would make calculating the final matrix easy.

This came up in https://github.com/flutter/flutter/issues/63281#issuecomment-675578296.

### PR DESCRIPTION
**Pull request by justinmc**
## Description

This PR adds double-tap-to-zoom to InteractiveViewer.  I noticed that even Google Maps on desktop web support double tap to zoom, so we should too.  It also was fairly nontrivial to implement, so it's probably not something that users should be expected to implement themselves.

## Related Issues

Closes https://github.com/flutter/flutter/issues/64156

## Tests

I added the following tests:

  * Double tap and expect the scale to increase.

### CODE REVIEW

**Comment by justinmc** [comment]
I think this PR is blocked on the resolution of https://github.com/flutter/flutter/issues/58636.  It causes that bug to happen all the time because it listens to double tap, which interferes with the scale gesture listener.

**Comment by kamleshwebtech** [comment]
InteractiveViewer does not work properly with CarouselSlider. If we want to see left or right portion of an image then slider shows previous image or next image respectively. Do you have any suggestion? how can we fix it. Thanks a lot.

**Comment by Yusuf007R** [comment]
any updates on this?

**Comment by justinmc** [comment]
@Yusuf007R Let's move the conversation to the open issue: https://github.com/flutter/flutter/issues/64156#issuecomment-1028213139

**Pull request closed without merging**
