### PR TITLE
Roll engine to 33b88173f3820690169348859bbdc29133179e0b

### PR DESCRIPTION
**Pull request by jason-simmons**
libtxt is now the default text renderer

### CODE REVIEW

**Comment by jason-simmons** [comment]
@chinmaygarde @tvolkert

**Review by cbracken — APPROVED** [review]

**Review by chinmaygarde — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm

**Review by tvolkert — APPROVED** [review]

**Review by tvolkert — CHANGES_REQUESTED** [review]
Actually, let's roll to `33b88173f3820690169348859bbdc29133179e0b`

**Comment by jason-simmons** [comment]
Done - changed to the commit that introduced libtxt

**Comment by chinmaygarde** [comment]
https://github.com/flutter/flutter/pull/14830 is queued behind this PR.

**Review by tvolkert — APPROVED** [review]
LGTM

**Comment by tvolkert** [comment]
Looks like floating point issues on the Mac flutter_tester tests...

**Comment by xster** [comment]
@jason-simmons can you take a look at the memory usage regressions from this? It looks like hello_world__memory, flutter_gallery__memory_nav, flutter_gallery__back_button_memory regressed.

**Comment by tvolkert** [comment]
Should we revert?

**Comment by xster** [comment]
I think it's sensible considering flutter_gallery__back_button_memory is 300% higher :)

**Comment by jason-simmons** [comment]
This isn't a leak that will increase every time you suspend/resume the app.  It's a singleton process-wide font cache in libtxt that eagerly fetches some fallback fonts for emoji/CJK/etc. character sets.

I can look into finding a way to lazily populate the cache, or to clear the cache after the app is suspended.

**Comment by tvolkert** [comment]
> I can look into finding a way to lazily populate the cache

I think this is worth investigating, and reverting the libtxt change in the meantime.  We can just revert the engine revision, then revert the libtxt flip in the engine so we can keep rolling the engine into flutter/fluter in the meantime.

**Pull request merged**
