### PR TITLE
Revert "Fix SnackBar clipping when it is floating due to FloatingActionButton positioning"

### PR DESCRIPTION
**Pull request by shihaohong**
Unfortunately, it seems like flutter/flutter#47616 broke some internal tests. We will have to revert until we can figure out what caused the change.

### CODE REVIEW

**Comment by shihaohong** [comment]
cc/ @filaps I'll try to figure out what's broken since you cannot view the internal tests and share my findings here when I can

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
For a little more details: on an internal test we found that the snackbar was coming in a bit lower than expected after this change.

Hopefully we can add a similar test to the Flutter repo covering the same case.

**Comment by shihaohong** [comment]
In an example where SnackBarBehavior.floating is used, the SnackBar shows up lower than expected with the new change. With the old change, it appears a little higher.
Test case:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class CustomSnackBar {
  void show(BuildContext context) {
    final snackBar = message(context);
    Scaffold.of(context).hideCurrentSnackBar();
    Scaffold.of(context).showSnackBar(snackBar);
  }

  SnackBar message(BuildContext context) {
    return SnackBar(
      behavior: SnackBarBehavior.floating,
      content: FlutterLogo(),
    );
  }
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Builder(
          builder: (BuildContext context) => Center(
            child: OutlineButton(
              onPressed: () {
                final accountSnackBar = CustomSnackBar();
                accountSnackBar.show(context);
              },
              child: Text('Tap me'),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by shihaohong** [comment]
I just realized that the change is intentional. @filaps, how do you reproduce the case in your second screenshot where the SnackBar seems clipped by the bottom nav bar / space saved for the FAB rect?

**Comment by Zazo032** [comment]
> I just realized that the change is intentional. @filaps, how do you reproduce the case in your second screenshot where the SnackBar seems clipped by the bottom nav bar / space saved for the FAB rect?
> 
> Also, it may seem like we might have to make a breaking change announcement of some sort because while it is a fix, other developers might rely on the implementation or work around it. Still trying to figure out what to do in that case.
> 
> cc/ @Hixie

To reproduce the clipped SnackBar, you have to drag it a bit to the bottom (like if you were going to dismiss it). https://github.com/flutter/flutter/issues/43716

**Comment by shihaohong** [comment]
Right now, I think we should initiate the [breaking change process](https://github.com/flutter/flutter/wiki/Tree-hygiene#2-evaluate-the-breaking-change-proposal). @filaps, I could write the design doc and help land the changes required to make this change. If you'd prefer to take ownership of some parts of the process, please let me know!

**Comment by dnfield** [comment]
IMO this does not require a design doc - just a migration guide and a flag so that we can soft migrate downstream users.

**Comment by dnfield** [comment]
I say this because I suspect this is a change most users want without knowing they want it, and the migration guide is to update your golden image testing :)

**Pull request merged**
