### PR TITLE
Revert "[web] Move JS content to its own `.js` files"

### PR DESCRIPTION
**Pull request by itsjustkevin**
Reverts flutter/flutter#117691

### CODE REVIEW

**Comment by mdebbar** [comment]
Please don't revert the PR. Submitting the PR and working on a g3fix in postsubmit was the only way to land it.

I'm afraid even if you revert it, we'll have to reland it so that we can work on a g3fix for it.

**Comment by mdebbar** [comment]
We are actively working on it.

**Comment by itsjustkevin** [comment]
@mdebbar I am all caught up on the context now.

**Review by CaseyHillers — APPROVED** [review]
Preliminarily LGTMing. If this is still blocking the roll tonight, we will need to revert to prevent any more regressions landing on the tree

**Comment by itsjustkevin** [comment]
Tests failing on rerun.  @XilaiZhang and @CaseyHillers are we aware of these failures?

**Comment by CaseyHillers** [comment]
@itsjustkevin can you rebase this PR with tip of tree?

**Pull request merged**
