### PR TITLE
Fix recursive link resulted `flutter doctor` stucking. 

### PR DESCRIPTION
**Pull request by kangwang1988**
Fix issues like : #25885 and #25870

### CODE REVIEW

**Comment by devoncarew** [comment]
Thanks! This fix looks reasonable; @gspencergoog may be a better reviewer here.

**Comment by xster** [comment]
LG but please add a test. See android_studio_test.dart for examples of a mock file system being created in memory. You can use fs.link to make a recursive symlink to test.

**Comment by kangwang1988** [comment]
@xster 
I don't think it's proper to use the LocalFileSystem for testing.
However, the MemoryFileSystem way also don't work.

@tvolkert Please have a look at this issue and https://github.com/google/file.dart/issues/118

**Review by tvolkert — APPROVED** [review]
LGTM.  I'll look to fix the MemoryFileSystem issue separately.

**Comment by tvolkert** [comment]
Sorry @gspencergoog - I saw your comment after I approved and merged.

Temporary directories on the local FS were the source of quite a few flakes back in the day, so let's just add the real test after the MemoryFileSystem is fixed.  @kangwang1988 I'll ping you when it's ready.

**Comment by gspencergoog** [comment]
No worries.  That works too.

**Comment by kangwang1988** [comment]
@tvolkert 
Got it, thanks~

**Pull request merged**
