### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by knowbody**
add a gif with a tiny demo

### CODE REVIEW

**Comment by knowbody** [comment]
I signed it!

**Comment by abarth** [comment]
Neat idea!

I think there are a couple ways this can be improved:

1) The cursor is visible, which is confusing given that it's supposed to be a mobile video.
2) The app is in slow mode, which is why the animations aren't smooth.

Maybe the thing to do is to capture the video on on a real device (e.g., no cursor) and with a release build (i.e., not in slow mode).

**Comment by eseidelGoogle** [comment]
We don't yet have a `flutter screenrecord` command, but https://github.com/flutter/flutter/issues/3496 has instructions on how to record on Android if that's helpful to you.

**Comment by eseidelGoogle** [comment]
Once we have videos, there is a `gifify` command (which at least I use) to turn them into gifs for things like presentations or README.mds.  Hope that helps!

**Comment by knowbody** [comment]
In the meantime you can just have this one and then replace it once you have something better 😎

**Comment by Hixie** [comment]
We've decided not to include these because we don't want people to think that that is representative of our animation performance. But we are totally on board with the idea of having videos or 60Hz animated GIFs showing the gallery on an actual device in release mode.

**Pull request closed without merging**
