### PR TITLE
update the IntelliJ metadata templates

### PR DESCRIPTION
**Pull request by devoncarew**
- fix an issue with the templates escaping path slash chars (and emitting `file://&#x2F;Users&#x2F;devoncarew&#x2F;projects&#x2F;flutter&#x2F;flutter&#x2F;bin&#x2F;cache&#x2F;dart-sdk/lib/collection` instead of `file:///Users/devoncarew/projects/flutter/flutter/bin/cache/dart-sdk/lib/collection`); add a test for this
- remove references to dart: libs no longer shipped in flutter's dart sdk
- update for some changes to the .iml files (add `<JAVADOC />`)
- delete the `android.iml` file from the top level of generated projects; I don't believe this is used (@stevemessick, is this your understanding as well?)
- use `JAVA_MODULE` for our module types, instead of `WEB_MODULE`

### CODE REVIEW

**Comment by devoncarew** [comment]
There'll be a corresponding Flutter IntelliJ plugin PR for this.

**Comment by devoncarew** [comment]
@stevemessick, one additional change we could make (perhaps in a follow up PR) is to move the `project_name_android.iml` file from the top level into the `android/` folder. It would keep that module metadata closer to the source its for, and reduce confusion about when there are two .iml files at the top level. I think all we'd need to do as part of the move is update the .idea/modules.xml file to point to the new location.

**Comment by stevemessick** [comment]
Moving the android module definition file into the android module sounds good to me.

I'm not sure what the android.iml file is for. I wonder if @mravn-google has any opinion about deleting it?

**Comment by mravn-google** [comment]
@stevemessick AFAIK, the .iml files are present in the template only for the benefit of IntelliJ-based editors. If the all three templates (project/plugin/package) work in both CE IntelliJ and Android Studio without the `android.iml` file, then yes, please remove it.

**Review by stevemessick — APPROVED** [review]
LGTM

**Pull request merged**
