### PR TITLE
Text inline widgets, TextSpan rework

### PR DESCRIPTION
**Pull request by GaryQian**
*************************************************************************************
COPY OF https://github.com/flutter/flutter/pull/30069
New branch to fix versioning issues. See old PR for comments and history
*************************************************************************************

This PR implements the capability of embedding widgets inline into paragraphs.

New TextSpan inheritance structure is the following:
```
InlineSpan --> TextSpan
         |
         ----> PlaceholderSpan ---> WidgetSpan
```
Wrap widgets to embed in `WidgetSpan(widget: <yourwidgethere>)`

The TextSpan changes make this a breaking change, although existing code passing `<TextSpan>[]` into `RichText` or `TextPainter` should still work as expected. Only code directly modifying a InlineSpan tree will be affected.

Fix/Addition for https://github.com/flutter/flutter/issues/2022

Dependent on the engine/LibTxt side PR: https://github.com/flutter/engine/pull/8207

### CODE REVIEW

**Comment by GaryQian** [comment]
The original PR (https://github.com/flutter/flutter/pull/30069) has LGTM

**Comment by goderbauer** [comment]
Can you close the old PR if you don't need it anymore and tag this PR with all the tags that were present on the old one?

**Comment by GaryQian** [comment]
@fkorotkov Do you know anything about otherwise similar macos runs taking over twice as long and causing timeouts vs similar runs finishing cleanly? For example, see https://cirrus-ci.com/task/4851206602620928 vs https://cirrus-ci.com/task/5571162709426176

**Comment by fkorotkov** [comment]
@GaryQian don't recall seeing such behaviour. 🤔Do you know if dart can output test reports with test duration? Might be helpful to add such reports as artifacts of tasks for troubleshooting similar issues.

**Comment by jonahwilliams** [comment]
cc @GaryQian , the mac luci bot started failing with this PR. I think we should roll it back to verify if this is what pushed it over the edge.

**Comment by GaryQian** [comment]
Yeah, ill roll this back for now. It looks like flutter_gallery accessibility_test.dart reordable_list_demo frequently times out with this patch.

**Pull request merged**
