### PR TITLE
Roll engine to a83b37d35acd8afd82be3f567a4b7231d5bdb928

### PR DESCRIPTION
**Pull request by aam**
Changes since last roll:

```
a83b37d35 Roll dart to a5e41681e55d1e74684bfff530218db556d77ee8 (#5467)
e45971083 Roll src/third_party/skia 9856c3d..4295859 (1 commits) (#5466)
d913985ec Roll src/third_party/skia 4588ff3..9856c3d (1 commits) (#5465)
2a4d926ab Update FlutterPluginRegistrxxx docs for iOS (#5415)
8ecdc3098 Roll src/third_party/skia ddd92dc..4588ff3 (1 commits) (#5464)
0b60f450c Roll src/third_party/skia 5034384..ddd92dc (3 commits) (#5463)
014a53f58 Roll src/third_party/skia 69d0e51..5034384 (2 commits) (#5462)
366d0e3ef Fix Dart project configuration for headless Dart runners. (#5461)
3d87b2717 libtxt: fix bug in calculating line end positions excluding whitespace (#5459)
44863aa4f Remove uses of ReleaseOwnership from vulkan backend (#5458)
f2992a1f5 Roll src/third_party/skia 7c93472..69d0e51 (3 commits) (#5460)
8c84737ea Update GrVkBackendContext to no longer own the VkInstance and VkDevice (#5457)
975d4ead6 libtxt: support per-locale fallback font collections (#5434)
ac7d442a6 Roll src/third_party/skia 728b7f3..7c93472 (6 commits) (#5455)
aa5c11d3f Roll Dart SDK to 1fe279d859 (#5454)
5ca93f31f Roll src/third_party/skia fd6a52c..728b7f3 (1 commits) (#5453)
5babb905e Roll src/third_party/skia a09981c..fd6a52c (1 commits) (#5452)
d3d40617f Roll src/third_party/skia a694870..a09981c (2 commits) (#5451)
eb11142e5 Roll src/third_party/skia 257c1fb..a694870 (2 commits) (#5450)
16f4da984 Parse --verbose-logging flag from intent and pass to the engine as args. (#5447)
78f46bd42 Log an error and cancel DartVM init if the VM/isolate snapshots are invalid (#5449)
50f623ab6 Roll src/third_party/skia 2ab87fc..257c1fb (6 commits) (#5448)
b599b597e Update CONTRIBUTING.md (#5444)
f81ed8990 Roll src/third_party/skia 7abeb28..2ab87fc (12 commits) (#5445)
c0ec8d9f0 Restore archive support removed in #5305. Codepush bundles use zip. (#5441)
0470f1c8c Remove --limit-ints-to-64-bits Dart VM option (#5442)
d7e3f2d6e Fix lint errors to prepare for building Android files in Google (#5440)
bc7949980 Roll src/third_party/skia 22f673d..7abeb28 (9 commits) (#5439)
9be67586b Roll src/third_party/skia c4952be..22f673d (4 commits) (#5438)
7b6acfd14 Roll src/third_party/skia db33ee1..c4952be (1 commits) (#5437)
1b30d4604 Roll src/third_party/skia e70c5fb..db33ee1 (1 commits) (#5436)
```

### CODE REVIEW

**Review by alexmarkov — APPROVED** [review]
LGTM

**Comment by aam** [comment]
Since appveyor timed out, but cirrus completed, I will take that as a sufficient confirmation for that merge.

**Comment by aam** [comment]
This was submitted via 'Rebase and merge'. So what failed was one(first) commit out of three, which had linux engine build failure. Cirrus, Travis, AppVeyor check only the last commit.

**Comment by mkustermann** [comment]
In the engine -> flutter roll I prepared (https://github.com/flutter/flutter/pull/18166) I was going to use two revisions before the the Dart roll (because the revision immediately before the Dart roll had a broken build, the [buildbot was purple](https://build.chromium.org/p/client.flutter/builders/Linux%20Engine/builds/2939))

**Comment by aam** [comment]
Another way to roll to the previously failed engine build is to force that build again.

**Pull request merged**
