### PR TITLE
MasonryGridView and SliverMasonryGrid Widget

### LINKED ISSUE #40856: Staggered GridView in Flutter
## Use case
Why isn't there in-built support for a staggered grid view in Flutter?
This is a basic use case that is covered by almost any mobile framework.
For example, Android has a `StaggeredGridLayoutManager` for `RecyclerView`.
I don't want to rely on a 3rd party library for this type of UI constructs.

### PR DESCRIPTION
**Pull request by zmtzawqlp**
## Description

This PR introduces new widgets called MasonryGridView/SliverMasonryGrid.  They look like GridView and SliverGrid whose children have the fixed cross-axis size, the difference is that the main-axis size are variable. A contiguous sequence of children are laid out after the shortest one of the previous row/column. It has high performance when scroll quickly.

## Related Issues

Closes https://github.com/flutter/flutter/issues/40856

## MasonryGridView Example

MasonryGridView

```dart
        MasonryGridView.builder(
          padding: const EdgeInsets.all(5.0),
          gridDelegate: const SliverMasonryGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 4,
            crossAxisSpacing: 10,
            mainAxisSpacing: 10,
          ),
          itemBuilder: (BuildContext c, int index) {
            final Color color = getRandomColor(index);

            return Container(
              decoration: BoxDecoration(
                  border: Border.all(color: Colors.black),
                  color: getRandomColor(index)),
              alignment: Alignment.center,
              child: Text(
                '$index ',
                style: TextStyle(
                    color: color.computeLuminance() < 0.5
                        ? Colors.white
                        : Colors.black),
              ),
              height: ((index % 3) + 1) * 100.0,
            );
          },
        ),
```
## SliverMasonryGrid Example

SliverMasonryGrid

```dart
      CustomScrollView(
        slivers: <Widget>[
          SliverToBoxAdapter(
            child: Container(
              height: 200,
              color: Colors.red,
              alignment: Alignment.center,
              child: const Text(
                'Header',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 20,
                ),
              ),
            ),
          ),
          SliverMasonryGrid(
            gridDelegate: const SliverMasonryGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 4,
              crossAxisSpacing: 5,
              mainAxisSpacing: 5,
            ),
            delegate: SliverChildBuilderDelegate(
              (BuildContext c, int index) {
                final Color color = getRandomColor(index);
                return Container(
                  decoration: BoxDecoration(
                      border: Border.all(color: Colors.black),
                      color: getRandomColor(index)),
                  alignment: Alignment.center,
                  child: Text(
                    '$index',
                    style: TextStyle(
                        color: color.computeLuminance() < 0.5
                            ? Colors.white
                            : Colors.black),
                  ),
                  height: ((index % 3) + 1) * 100.0,
                );
              },
              childCount: 50,
            ),
          ),
          SliverToBoxAdapter(
            child: Container(
              height: 200,
              color: Colors.red,
              alignment: Alignment.center,
              child: const Text(
                'Footer',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 20,
                ),
              ),
            ),
          ),
        ],
      ),
```
## API Details

The api of MasonryGridView looks like GridView, and SliverMasonryGrid looks like SliverGrid.

* [MasonryGridView] Creates a scrollable, 2D array of widgets in masonry layout with a custom [SliverMasonryGridDelegate].

* [MasonryGridView.builder]  Create a masonry layout with a large (or infinite) number of children that are created on demand.

* [MasonryGridView.count] Creates a scrollable, 2D array of widgets in masonry layout with a fixed number of tiles in the cross axis.

* [MasonryGridView.extent]  Creates a scrollable, 2D array of widgets in masonry layout with tiles
 that each have a maximum cross-axis extent.

* [MasonryGridView.custom] Creates a scrollable, 2D array of widgets in masonry layout
with both a custom [SliverMasonryGridDelegate] and a custom [SliverChildDelegate].

* [SliverMasonryGrid] Creates a sliver that places multiple box children in masonry layouts.

* [SliverMasonryGrid.count] Creates a sliver that places multiple box children in masonry layout
with a fixed number of tiles in the cross axis.

* [SliverMasonryGrid.extent] Creates a sliver that places multiple box children in masonry layout
with tiles that each have a maximum cross-axis extent.

* [SliverMasonryGridDelegateWithFixedCrossAxisCount] Creates a delegate that makes masonry layouts with a fixed number of tiles in the cross axis.

* [SliverMasonryGridDelegateWithMaxCrossAxisExtent] Creates masonry layouts with tiles that each have a maximum cross-axis extent.

## Tests

I added the following tests:

✓ MasonryGridView the size of each child
✓ MasonryGridView the position of each child at TextDirection.ltr
✓ MasonryGridView the position of each child at TextDirection.rtl
✓ MasonryGridView crossAxisCount change test
✓ MasonryGridView crossAxisSpacing change test
✓ MasonryGridView mainAxisSpacing change test
✓ MasonryGridView maxCrossAxisExtent change test
✓ MasonryGridView Vertical are primary by default
✓ MasonryGridView with controllers are non-primary by default
✓ MasonryGridView sets PrimaryScrollController when primary
✓ MasonryGridView dismiss keyboard onDrag test
✓ MasonryGridView count dismiss keyboard onDrag test
✓ MasonryGridView extent dismiss keyboard onDrag test
✓ MasonryGridView dismiss keyboard manual test
✓ MasonryGridView count dismiss keyboard manual test
✓ MasonryGridView extend dismiss keyboard manual test
✓ MasonryGridView itemCount change test
✓ MasonryGridView items removeRange test
✓ MasonryGridView the child who out of viewport change big test
✓ MasonryGridView the child who out of viewport change small sroll into 0 test
✓ MasonryGridView the child who out of viewport change small sroll into 100 test
✓ MasonryGridView insert child out of viewport test
✓ MasonryGridView remove child out of viewport test

✓ SliverMasonryGrid the size of each child
✓ SliverMasonryGrid the position of each child at TextDirection.ltr
✓ SliverMasonryGrid the position of each child at TextDirection.rtl
✓ SliverMasonryGrid crossAxisCount change test
✓ SliverMasonryGrid crossAxisSpacing change test
✓ SliverMasonryGrid mainAxisSpacing test
✓ SliverMasonryGrid maxCrossAxisExtent change test
✓ SliverMasonryGrid itemCount change test
✓ SliverMasonryGrid items removeRange test
✓ SliverMasonryGrid the child who out of viewport change big test
✓ SliverMasonryGrid the child who out of viewport change small sroll into 0 test
✓ SliverMasonryGrid the child who out of viewport change small sroll into 100 test
✓ SliverMasonryGrid insert child out of viewport test
✓ SliverMasonryGrid remove child out of viewport test
✓ SliverMasonryGrid test with other slivers
✓ SliverMasonryGrid insert other slivers test

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

### CODE REVIEW

**Comment by Piinks** [comment]
This looks interesting! Thanks for the contribution! I am curious, if the main axis sizes are variable, can the cross axis sizes also be variable? 

This still may be better provided and supported through a separate package as suggested in the issue.

**Comment by Piinks** [comment]
@goderbauer what do you think?

**Comment by Hixie** [comment]
This looks amazing, but I agree with @Piinks that this would be more appropriate in a new package. We try to make the things in the core framework be the building blocks for packages like these. We're even considering moving things like the material and cupertino packages out of the core.

That said, we should totally have the tests for this run as part of the flutter/tests repo so that they are tested every time we commit anything, which would ensure we don't break it and provides the main advantage of being in the main repo.

**Comment by goderbauer** [comment]
This looks nice. I second (or third) what other have said, though. I hope you make this available as a third-party package!

Out of curiosity, how does the implementation handle the following situation: You're scrolled to the end and one of the boxes above the current scroll position changes its size. How/when do you re-layout to adjust the grid?

**Comment by zmtzawqlp** [comment]
> This looks interesting! Thanks for the contribution! I am curious, if the main axis sizes are variable, can the cross axis sizes also be variable?
> 
> This still may be better provided and supported through a separate package as suggested in the issue.

VariableSizedGridView, right?  This is a complex layout, [flutter_staggered_grid_view](https://pub.dev/packages/flutter_staggered_grid_view) supports that. But it loses [performance](https://github.com/letsar/flutter_staggered_grid_view/issues?q=performance). It's not good for big list. in fact,  we always use such layout for small data, [Flow] widget is enough.

But masonry layout is always used for show image in big list. People often said that it's sad scroll with low performance. Someone always ask why flutter doesn't  support masonry layout as other platform.  Thanks for powerful Flutter Slivers system, we can easily create stable masonry layout of widget with high performance. why lose the opportunity to show a better flutter.
I worked for GrapeCity(ComponentOne), I believe the customer is prefer the single function with high performance.

**Comment by zmtzawqlp** [comment]
> This looks amazing, but I agree with @Piinks that this would be more appropriate in a new package. We try to make the things in the core framework be the building blocks for packages like these. We're even considering moving things like the material and cupertino packages out of the core.
> 
> That said, we should totally have the tests for this run as part of the flutter/tests repo so that they are tested every time we commit anything, which would ensure we don't break it and provides the main advantage of being in the main repo.

I know the  test cases are not enough  for now.  I've been thinking about that and I need more professional advice to cover all cases. In fact, I've learned from the principles of ListView and GridView, and i try to make sure all code are good. It's good to provide masonry layout as other platform did.

**Comment by zmtzawqlp** [comment]
> This looks nice. I second (or third) what other have said, though. I hope you make this available as a third-party package!
> 
> Out of curiosity, how does the implementation handle the following situation: You're scrolled to the end and one of the boxes above the current scroll position changes its size. How/when do you re-layout to adjust the grid?

MasonryGridView and SliverMasonryGrid are the same as ListView and SliverList at main axis.

1. if the child is not in viewport, it's not in widget tree, so we don't need do any thing.
2. if the child is in viewport, the same as ListView and SliverList(layout from firstChild  one by one), the postion of children will recalculate base on leading children.

In my opinion, Masonry layout is  more common layout.  More than once did it mentioned that why we don't have such layout.

 I can explain any code about it to make sure the codes are stable.

More clarification:

This algorithm in principle is:  for example grid is vertical and  crossAxisCount is 4, 

 fill the leading children at the begining, we have 4 children as leading in first row.

then laid out next one under the shortest one, update leading children(may be shortest one has changed),

 repeat until trailing children are all reach at the end.  remove the children whose are out of viewport from widget tree.

keep the data of leading children and trailing children for the next layout. 

Flutter is power, i just want to contribute my share to the better flutter. Many thanks for your time.

**Comment by chunhtai** [comment]
> 1. if the child is not in viewport, it's not in widget tree, so we don't need do any thing.

We don't do anything if it is not in the viewport for sliver list because the layout is one dimensional. We are sure adding thing before the first child will just affect the position of the first child on that one dimensional axis, so we can pretend everything is fine until we scroll to very top and figure out the scroll offset is wrong. At that point we correct the scroll offset of all children and things will be fine.

However, adding a child in this grid view may complete change the whole layout. You can pretend things are fine and keep the wrong layout, but then you will have to correct it at some point (usually when you scroll to the top and figure out things does not match up). The correction might cause a big shift for every item in the grid.

That being said, I think we probably have the similar problem in slivergrid...

**Comment by zmtzawqlp** [comment]
> > 1. if the child is not in viewport, it's not in widget tree, so we don't need do any thing.
> 
> We don't do anything if it is not in the viewport for sliver list because the layout is one dimensional. We are sure adding thing before the first child will just affect the position of the first child on that one dimensional axis, so we can pretend everything is fine until we scroll to very top and figure out the scroll offset is wrong. At that point we correct the scroll offset of all children and things will be fine.
> 

I know what you mean. if the child is not in viewport ,and it's coming into viewport after scroll, it may be change the layout of children after its' index. But i think it's reasonable and necessary.  The following gif show this case.

AD6E384F2835AFDA283656DE04864553

In fact, in the actual scene, it has two situations.
1. know the image size before it is decoded and is rendered.
The customer should set aspectRatio base on image width/height.
This is the perfect solution for masonry layout.
```dart
    image = AspectRatio(
      aspectRatio: item.imageSize.width / item.imageSize.height,
      child: image,
    );
```
2.No image Size.

The customer should store image size after the Image is completed. I use [ExtendedImage](https://pub.dev/packages/extended_image), it has call back include the info of image when the Image is completed. when we scroll back, we know the size, do as scene 1.
```dart
          } else if (value.extendedImageLoadState == LoadState.completed) {
            item.imageRawSize = Size(
                value.extendedImageInfo.image.width.toDouble(),
                value.extendedImageInfo.image.height.toDouble());
          }
```
```dart
  if (konwSized) {
    image = AspectRatio(
      aspectRatio: item.imageSize.width / item.imageSize.height,
      child: image,
    );
  } else if (item.imageRawSize != null) {
    image = AspectRatio(
      aspectRatio: item.imageRawSize.width / item.imageRawSize.height,
      child: image,
    );
  }
```

What I'm trying to say, re-layout due to size changed is reasonable and necessary. It's not against 
the principles.

In fact, we have stored the parent data of leading children.
* if leading children is after scroll offset, we insert children before leading children base on the parent data of them. 
* if leading children is before scroll offset, we update them, remove who is out of viewport.
* The size changed child only change layout when it's coming into viewport again. I think they are reasonable as the other platform did.


> However, adding a child in this grid view may complete change the whole layout. You can pretend things are fine and keep the wrong layout, but then you will have to correct it at some point (usually when you scroll to the top and figure out things does not match up). The correction might cause a big shift for every item in the grid.
> 
> That being said, I think we probably have the similar problem in slivergrid...

I don't think we should change whole layout immediately when insert a new child if it's not in viewport. When scroll into the viewport, then update the layout at that time, there's nothing wrong with that.

**Comment by zmtzawqlp** [comment]
Hi guys, I would like to clarify the reason for this pr.
1. Masonry is common and popular layout in contemporary applications. ListView and GridView  doesn't have good experience on big screen as Flutter is support web,mac,windows.  So provide an official solution is valuable. 
2. 3rd party package is good, but it has not a sense of safety for customer. Maybe it won't be maintained or it has many issues not closed. That why in [#40856](https://github.com/flutter/flutter/issues/40856), people want to an official  solution.
3. Un like VariableSizedGridView ,the principle of MasonryGridView is consensus, it doesn't make  customer confused. So we can make a definite widget.
4. Flutter is amazing project for world. I'm glad to join it, and make some packages as the additional of Flutter SDK. Open source is interesting but it also should be responsible. I always keep my packages under maintenance and reduce issue as possible. I made this pr and i know my responsibility.

As Flutter said, Flutter makes it easy and fast to build beautiful apps for mobile and beyond. We can provide better experience for list. Would you please reconsider it? Thanks for your time.

**Comment by chunhtai** [comment]
> I don't think we should change whole layout immediately when insert a new child if it's not in viewport. When scroll into the viewport, then update the layout at that time, there's nothing wrong with that.

This may be true for some apps, but some other apps may prefer to change the whole layout immediately. We also need to think about not just size change, user can do any crazy things like reversing the entire list, or replacing it with a completely new list.
 
>Masonry is common and popular layout in contemporary applications. ListView and GridView doesn't have good experience on big screen as Flutter is support web,mac,windows. So provide an official solution is valuable.
>3rd party package is good, but it has not a sense of safety for customer. Maybe it won't be maintained or it has many issues not closed. That why in #40856, people want to an official solution.

We do have [flutter favorite program](https://pub.dev/flutter/favorites) which we have reviewed multiple packages and recommended them to the users. This is our attempt to address the concern you mentioned.


I still think we should put this into a third party package, given that this is a bit more specific to certain use cases and there is also a concern on how we should deal with the relaying out issue.

That being said, this is nice work, the grid looks beautiful.

**Comment by Hixie** [comment]
> * 3rd party package is good, but it has not a sense of safety for customer. Maybe it won't be maintained or it has many issues not closed. That why in [#40856](https://github.com/flutter/flutter/issues/40856), people want to an official  solution.

Unfortunately, checking something into the main repo doesn't guarantee it will be maintained either... which is especially true as we add more and more features. This is why we're focusing on adding fewer features. :-) Even if we were in agreement that this would be something that would be a good fit for the main repo, we'd still have to ask you to commit to maintaining it if you wanted to check it in... and as you're willing to make that commitment, people will be satisfied either way; indeed, having it in its own repo gives you much more autonomy for maintaining the code and lets you more directly address people's needs and concerns.

That said, as @chunhtai said, the "flutter favorite" programme is exactly the solution here: https://flutter.dev/docs/development/packages-and-plugins/favorites

We specifically developed this programme as a mechanism for marking third-party plugins and packages that _are_ being maintained and have high quality. Our goal is to encourage a healthy ecosystem with many packages and plugins that are actively maintained.

We also have the flutter/tests programme if you want to make sure that breaking changes to Flutter don't break your package.

**Comment by zmtzawqlp** [comment]
I feel sorry, but i will keep making more useful packages. Thanks for Flutter, we can make what we want.

**Comment by jagomf** [comment]
@zmtzawqlp have you published this as a separate package?

**Comment by zmtzawqlp** [comment]
> @zmtzawqlp have you published this as a separate package?

more functions  with  https://pub.dev/packages/waterfall_flow

**Pull request closed without merging**
