### PR TITLE
Switch to URIs for breakpoints and unskip tests on Windows

### PR DESCRIPTION
**Pull request by DanTup**
addBreakpointWithScriptUri expects Uris. By coincidence, FS paths work on Mac/Linux but they fail on Windows. One of the issues in the skip comment is fixed, the other one seems not relevant here.

### CODE REVIEW

**Comment by DanTup** [comment]
I think this needs #22507 in order to pass (I had a cached build of tools when I ran this). I'll rebase and try again once that's done.

**Review by goderbauer — APPROVED** [review]
LGTM, please make sure bots are happy before merging.

**Comment by DanTup** [comment]
The failure looks like a repeat of https://github.com/flutter/flutter/pull/21741 caused by symlinks in the temp paths coming from macOS (we don't handle breakpoints sent for symlinked paths, since the VM is using the real underlying path).

I've applied that fix (which only applied to one test file previously) to all integration tests to avoid this; hopefully it'll make everything green. (@goderbauer please check the new changeset and confirm if you're still happy with this).

**Comment by DanTup** [comment]
@goderbauer I pushed extra changes to handle symlinks since you approved this, let me know if you're still happy for me to land this.

(I'll rebase too since it's been a while)

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by DanTup** [comment]
Ug, I didn't spot flutter-build was missing from this, so I landed it while the build was red 😕

**Pull request merged**
