### PR TITLE
Reland "integrate testWidgets with leak tracking" (#140521)

### PR DESCRIPTION
**Pull request by polina-c**
Reverted PR: https://github.com/flutter/flutter/pull/140521
Fix: actually use the created flag in `_configureTearDownForTestFile()`.

Tested by setting `presubmit: true` for Linux_android flutter_test_performance.

### CODE REVIEW

**Comment by polina-c** [comment]
Linux_android flutter_test_performance and cla/google passed.

Disabling the test.

**Comment by zanderso** [comment]
Re-routing to the original reviewers.

**Review by kenzieschmoll — APPROVED** [review]

**Comment by goderbauer** [comment]
Is there a specific commit that contains what's different to the previous PR?

**Comment by polina-c** [comment]
> Is there a specific commit that contains what's different to the previous PR?

@goderbauer, the key change is in the added `!_shouldConfigureTearDownForTestFile()` in this block: 

```
void _maybeConfigureTearDownForTestFile() {
  if (_isTearDownForTestFileConfigured || !_shouldConfigureTearDownForTestFile()) {
    return;
  }
```

All other changes are renamings aimed to improve readability with this added condition.

Does it help?

**Comment by goderbauer** [comment]
For next time: If you isolate the changes over the original PR in a specific set of commits relands are a lot faster and easier to review.

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
