### PR TITLE
Expose the leader field of the LayerLink class.

### PR DESCRIPTION
**Pull request by cchamm**
Some packages, like [local_hero](https://pub.dev/packages/local_hero), need to access `LayerLink.leader` in order to work. `LeaderLayer? get leader => _leader` is added to the LayerLink class again.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
I took another look at this and I believe we can simplify the LeaderLayer even further, which will also allow us to bring back the `LayerLink.leader` property: https://github.com/flutter/flutter/pull/92598.

**Comment by dnfield** [comment]
local_hero may want to consider adding itself to `flutter/tests` so this doesn't get broken again

**Comment by goderbauer** [comment]
Closing this in favor of https://github.com/flutter/flutter/pull/92598, which has been merged.

**Comment by cchamm** [comment]
> local_hero may want to consider adding itself to `flutter/tests` so this doesn't get broken again

Adding test to `packages/flutter/test/rendering/layers_test.dart`, right?

**Comment by goderbauer** [comment]
No, that will not help :). Packages can contribute their tests to https://github.com/flutter/tests as explained in the readme over there: https://github.com/flutter/tests/blob/master/README.md. That gives us a signal whether our changes break anything in the real world and if it does we will either reconsider the change or provide a breaking change announcement with migration guide.

**Comment by creativecreatorormaybenot** [comment]
> Closing this in favor of #92598, which has been merged.

@goderbauer I do not understand - #92598 was merged last year and this PR was opened 17 days ago - how can this have been closed **in favor of #92598** when this PR is only a follow-up?

Is there anything wrong with this change ~

**Comment by goderbauer** [comment]
I accidentally linked to the wrong PR in that comment. Meant to link to https://github.com/flutter/flutter/pull/96486, which re-exposes the leader field in a cleaner way.

**Comment by creativecreatorormaybenot** [comment]
@goderbauer thanks! ❤️

**Pull request closed without merging**
