### PR TITLE
Revert "Animated placeholder perf"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#50851

This is broken in the devicelab.

### CODE REVIEW

**Comment by dnfield** [comment]
LGTM.

Landing on red to unred the tree.  Not sure why this is timing out on devicelab :\

**Comment by liyuqian** [comment]
@dnfield : maybe try to split your PR into 2 PRs, one for macos, and one for the rest, to see which one breaks the device lab?

**Comment by dnfield** [comment]
@liyuqian it wasn't the macos part - that has no impact on the devicelab.  The test itself is failing to connect to the vm service.

**Comment by liyuqian** [comment]
Great. That means we can at least merge a 1000-line change that adds `macos`?

**Comment by dnfield** [comment]
I'll open a new PR to land macos separately.  I've started a reland PR here: https://github.com/flutter/flutter/pull/50987 which has passed all tests and just makes the new test flaky for now.

**Pull request merged**
