### PR TITLE
Avoid using FlutterError.fromParts when possible

### PR DESCRIPTION
**Pull request by albertusdev**
## Description
This PR is a follow up of https://github.com/flutter/flutter/pull/42640/files
Some changes of that PR includes redundant changes using FlutterError.fromParts constructor even though it's not necessary
Some minor changes are:
- Remove one unnecessary todo
- Fix indent consistencies

## Related Issues
none

## Tests
- minor changes that was covered by tests included in the previous change

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jacob314 — APPROVED** [review]
lgtm
Thanks for cleaning this up.

**Comment by gspencergoog** [comment]
@adalberht, are you still planning on landing this PR?  It has been approved, but needs to have the file conflicts resolved.

**Comment by adalberht** [comment]
@gspencergoog Yes, I tried resolving the conflicts but the error message that I saw from the failing pipeline does not make sense to me now. Can you please help?

**Comment by adalberht** [comment]
Hey @gspencergoog, this PR should be ready to be landed once the CI is green now.
Earlier the CI kept failing because I used merge instead of rebase and that caused the version SDK to be stuck at 1.10 instead of the latest version.
Also, I added another commit to fix linter error (unnecessary string interpolation).

**Comment by gspencergoog** [comment]
Great, I'll land it!

**Pull request merged**
