### PR TITLE
revert #48985

### LINKED ISSUE #49567: The source tree is in a bad state
https://github.com/flutter/flutter/pull/48985 made a bunch of unintended changes

We should fix this before doing anything else

### PR DESCRIPTION
**Pull request by dnfield**
#48985 landed a bunch of unintended changes.  Let's just revert and then try to re-apply the intended changes.

Fixes #49567

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
RSLGTM

**Review by jmagman — APPROVED** [review]
RSLGTM

**Comment by jonahwilliams** [comment]
fyi @HansMuller for the deprecations

**Review by clocksmith — APPROVED** [review]

**Comment by HansMuller** [comment]
It might be possible to catch this kind of mixup. For example, we could refuse to land PRs if:
- The PR lacked a special label indicating that it was changing more than a dozen files
- If the number of files changed after the PR had been approved

**Comment by dnfield** [comment]
Landing this since tree is currently red on infra setup issue and this needs to get in to let the roll continue.

**Pull request merged**
