### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by zanderso**
`flutter update-packages --force-upgrade` for removal of direct dependence of the tool on package:platform. (It looks like there's still a transitive dependence, though?)

### CODE REVIEW

**Comment by zanderso** [comment]
@jonahwilliams Do you recognize the vmservice integration test failures? Could they be caused by updating the packages here?

**Comment by jonahwilliams** [comment]
Looks like a type signature got tightened up somewhere? I don't see anything in the changelog though and we don't seem to be using `<dynamic, dynamic>` ourselves.

@bkonyi

**Comment by bkonyi** [comment]
> Looks like a type signature got tightened up somewhere? I don't see anything in the changelog though and we don't seem to be using `<dynamic, dynamic>` ourselves.
> 
> @bkonyi

Sorry for the delay on this. I think we've found the issue and there's a CL up with a fix: https://dart-review.googlesource.com/c/sdk/+/147806. I'll let you know when `package:vm_service` v4.0.4 is published.

**Comment by bkonyi** [comment]
`package:vm_service` v4.0.4 is released. Try updating to that version to hopefully fix the failures you're seeing.

**Pull request closed without merging**
