### PR TITLE
Avoid ever creating the WidgetInspectorService or registering

### PR DESCRIPTION
**Pull request by jacob314**
inspector service extensions outside of debug mode.

### CODE REVIEW

**Comment by jacob314** [comment]
This fixes https://github.com/flutter/flutter/issues/21633

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
First step is probably to see if we can confirm it locally. It's pretty stark on the benchmarks.

**Comment by jacob314** [comment]
I'm on it.

**Comment by Hixie** [comment]
even more weirdly, `complex_layout_semantics_perf initialSemanticsTreeCreation` also regressed, unless i'm reading this wrong.

**Comment by jacob314** [comment]
We got one frame back in range and then a few more bad frames. I'm sending out a CL to tweak the warmup period  to see if that makes the benchmark less noisy.

**Comment by jacob314** [comment]
https://github.com/flutter/flutter/pull/21733
tries increasing the initial delay to 1 second to see if that reduces flakiness.

**Pull request merged**
