### PR TITLE
Revert "Minor change type nullability"

### PR DESCRIPTION
**Pull request by jmagman**
Reverts flutter/flutter#112778

This caused gallery to stop building: https://github.com/flutter/flutter/issues/113245

### CODE REVIEW

**Comment by jmagman** [comment]
cc @fzyzcjy

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by fzyzcjy** [comment]
So, shall I update that sample and PR again, or shall I just leave it there (the imperfect nullability)? 👀

**Comment by jmagman** [comment]
> Btw is there any methods I can know it will break the tree before merging - I do not intend to do so :(

You can check if https://github.com/flutter/gallery `flutter run`s on your change.  I filed https://github.com/flutter/flutter/issues/113248 so we can build that project in presubmit to catch breakages.

**Comment by fzyzcjy** [comment]
@jmagman Thanks!

**Comment by fzyzcjy** [comment]
FYI, upstream PR created: https://github.com/letsar/flutter_staggered_grid_view/pull/274

**Comment by fzyzcjy** [comment]
> but I believe that this test failure makes this a breaking change

You are right, I forgot that and will do that soon.

**Pull request merged**
