### PR TITLE
add libzip cache artifact

### LINKED ISSUE #42877: flutter install: Library not loaded libzip-flutter/lib/libzip.5.dylib
When I run `flutter install`, here's what I see:

```
❯ flutter install -d REDACTED
Installing com.tonal.mobile to Max's iPhone...
Process exited abnormally:
dyld: Library not loaded: /b/s/w/ir/k/homebrew/opt/libzip-flutter/lib/libzip.5.dylib
  Referenced from: /Users/maxlapides/flutter/bin/cache/artifacts/ideviceinstaller/ideviceinstaller
  Reason: image not found
Install failed
```

I also ran `flutter install` with the `-v` flag if this is useful:

<details><summary>Verbose log</summary>
<p>

```
❯ flutter install -d REDACTED -v
[  +25 ms] executing: [/Users/maxlapides/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +28 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] e70236e36ce1d32067dc68eb55519ec3e14b6b01
[        ] executing: [/Users/maxlapides/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +8 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.7-0-ge70236e36
[   +7 ms] executing: [/Users/maxlapides/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/maxlapides/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +49 ms] executing: [/Users/maxlapides/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +6 ms] executing: sw_vers -productName
[  +19 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +20 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15
[        ] executing: sw_vers -buildVersion
[  +20 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19A583
[  +31 ms] executing: /usr/bin/xcode-select --print-path
[  +12 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +4 ms] executing: /usr/bin/xcodebuild -version
[ +246 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +3 ms] Xcode 11.1
           Build version 11A1027
[  +61 ms] executing: /Users/maxlapides/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/maxlapides/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +22 ms] executing: /Users/maxlapides/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +307 ms] /usr/bin/xcrun simctl list --json devices
[ +164 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +39 ms] executing: /usr/bin/plutil -convert json -o - /Users/maxlapides/Repositories/mobile/ios/Runner/Info.plist
[   +9 ms] Exit code 0 from: /usr/bin/plutil -convert json -o -
/Users/maxlapides/Repositories/mobile/ios/Runner/Info.plist
[   +3 ms]
{"CFBundleName":"Tonal","UILaunchStoryboardName":"LaunchScreen","ITSAppUsesNonExemptEncryption":false,"LSApplicationQu
eriesSchemes":["fbapi","fb-messenger-share-api","fbauth2","fbshareextension"],"CFBundleDevelopmentRegion":"en","CFBund
leVersion":"91","NSCameraUsageDescription":"Upload profile avatar
photos","UIBackgroundModes":["remote-notification"],"NSHealthUpdateUsageDescription":"Synchronize your Tonal activity
and profile with
HealthKit","CFBundlePackageType":"APPL","CFBundleShortVersionString":"0.0.1","UIMainStoryboardFile":"Main","NSHealthSh
areUsageDescription":"Your Tonal profile will automatically be updated with the latest information from
HealthKit","NSAppTransportSecurity":{"NSAllowsArbitraryLoads":true},"CFBundleInfoDictionaryVersion":"6.0","CFBundleExe
cutable":"$(EXECUTABLE_NAME)","FacebookAppID":"2383478315000318","FacebookDisplayName":"Tonal","CFBundleURLTypes":[{"C
FBundleTypeRole":"Editor","CFBundleURLName":"tonalmobileapp","CFBundleURLSchemes":["https"]},{"CFBundleURLSchemes":["f
b2383478315000318"]}],"CFBundleIdentifier":"$(PRODUCT_BUNDLE_IDENTIFIER)","NSPhotoLibraryAddUsageDescription":"Your
photos library is used to save and upload Tonal-related
content","CFBundleSignature":"????","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait","UIInter
faceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"LSRe
quiresIPhoneOS":true,"CFBundleDisplayName":"Tonal","NSLocationAlwaysUsageDescription":"Your location is used to
improve the quality of push
notifications","UISupportedInterfaceOrientations":["UIInterfaceOrientationPortrait"],"NSPhotoLibraryUsageDescription":
"Your photos library is used to save and upload Tonal-related
content","UIViewControllerBasedStatusBarAppearance":true,"NSLocationWhenInUseUsageDescription":"Your location is used
to improve the quality of push notifications"}
[  +15 ms] Installing com.tonal.mobile to Max's iPhone...
[   +3 ms] executing: /Users/maxlapides/flutter/bin/cache/artifacts/ideviceinstaller/ideviceinstaller --list-apps
[  +18 ms] dyld: Library not loaded: /b/s/w/ir/k/homebrew/opt/libzip-flutter/lib/libzip.5.dylib
             Referenced from: /Users/maxlapides/flutter/bin/cache/artifacts/ideviceinstaller/ideviceinstaller
             Reason: image not found
[   +5 ms] executing: /Users/maxlapides/flutter/bin/cache/artifacts/ideviceinstaller/ideviceinstaller -i
build/ios/iphoneos/Runner.app
[  +17 ms] dyld: Library not loaded: /b/s/w/ir/k/homebrew/opt/libzip-flutter/lib/libzip.5.dylib
             Referenced from: /Users/maxlapides/flutter/bin/cache/artifacts/ideviceinstaller/ideviceinstaller
             Reason: image not found
[   +1 ms] Process exited abnormally:
           dyld: Library not loaded: /b/s/w/ir/k/homebrew/opt/libzip-flutter/lib/libzip.5.dylib
             Referenced from: /Users/maxlapides/flutter/bin/cache/artifacts/ideviceinstaller/ideviceinstaller
             Reason: image not found
[  +16 ms] "flutter install" took 1,069ms.
Install failed

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      InstallCommand.runCommand (package:flutter_tools/src/commands/install.dart:45:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:553:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

</p>
</details>

I believe this problem has been referenced in some other issues, but I'm not sure if these are the same issue that I'm experiencing:

- https://github.com/flutter/flutter/issues/42543#issuecomment-542635604
- https://github.com/flutter/flutter/issues/29932

This issue has been reproduced on other computers attempting to install on other mobile devices.

```
❯ flutter doctor -v
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.15 19A583, locale en-US)
    • Flutter version 1.10.7 at /Users/maxlapides/flutter
    • Framework revision e70236e36c (2 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/maxlapides/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/maxlapides/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • Max's iPhone  • REDACTED            • ios • iOS 13.1.2
    • iPhone 11 Pro • 8D361F98-6571-4CB0-A6B9-BB3C8A36FBB9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1
      (simulator)

• No issues found!
```

### PR DESCRIPTION
**Pull request by christopherfujino**
## Description

When building `ideviceinstaller`, we dynamically link to libzip. However, it was never distributed with the flutter tool. However, `flutter install` requires `libzip`, so this PR adds the `libzip` cache artifact.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/42877

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Review by jmagman — COMMENTED** [review]
Does DYLD_LIBARY_PATH need to be set to the libzip location when ideviceinstaller is run?  Or is there some magic that already does this?

**Comment by christopherfujino** [comment]
> Does DYLD_LIBARY_PATH need to be set to the libzip location when ideviceinstaller is run? Or is there some magic that already does this?

So much magic. Each `ArtifactSet` has a `Map<String, String> environment` that describes any environment variables that must be set to use said artifact. Then calling the `cache.dyLdLibEntry` getter will concatenate the `DYLD_LIBRARY_PATH`'s for all the artifacts in the cache. https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/cache.dart#L267

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by flar** [comment]
This PR appears to cause a regression in worst frame time on the `flutter_gallery_ios32__transition_perf` benchmark. Is there any reason that including libzip rather than dynamically linking it might cause our frame times to be affected?

**Comment by christopherfujino** [comment]
@flar This has me really stumped...

**Comment by flar** [comment]
What do we use libzip for? Is it really the same libzip?

**Comment by christopherfujino** [comment]
ideviceinstaller uses it for managing app packages https://github.com/libimobiledevice/ideviceinstaller/blob/master/src/ideviceinstaller.c

**Comment by flar** [comment]
If I understand our process, that is only used on the host side for app packaging and it only plays a role in getting the app to the phone. Once the app is on the phone, then zip has no role and so shouldn't affect frame times.

And thus the mystery?

**Comment by christopherfujino** [comment]
@flar that is also my understanding.

**Comment by liyuqian** [comment]
Has the mystery been solved? If not, I wonder if we can revert this for the ~3x regression on the iOS worst frame time.

**Comment by christopherfujino** [comment]
@flar @liyuqian does reverting this on ToT result in a 3x improvement? Reverting this will break `flutter install` on ios devices.

**Comment by flar** [comment]
I was in training for most of today. I'll rerun the benchmarks and try a ToT revert run as well, but if that breaks flutter install, then will I be able to run the benchmarks once I revert it?

**Comment by flar** [comment]
Here are the benchmark runs I get on a number of git commit hashes. I checked each out, ran update-packages, then ran the benchmark once and threw out the first result and then ran it 3 more times. Results are:

```
                      average    90th%     99th%     worst
commit #13c4ba2        6.67     16.625    17.289    20.558
                       8.806    16.672    17.351    21.079
                       6.931    16.651    17.259    19.111
commit #261594e        9.58     16.662    22.008    90.401
                       9.51     16.66     24.394    86.192
                      10.59     16.678    22.574    80.656
ToT #525855           10.985    16.714    23.967    62.398
                      10.958    16.737    22.633    66.381
                      10.386    16.714    32.281    69.608
ToT revert #261594e    6.741    16.608    17.495    18.626
                       6.254    16.63     17.623    22.935
                       6.984    16.644    17.393    18.099
```
iOS Gallery transition frame rasterization times

Reverting does seem to restore performance and I didn't have any trouble running the benchmarks on the "ToT" commit from today that I chose as my baseline.

**Comment by liyuqian** [comment]
Running the benchmark doesn't involve `flutter install` so it won't be affected by the revert.

It seems that we need to figure out what triggers the regression, and come up with a `flutter install` fix that doesn't regress. Before that, we have two options: (1) revert this PR to break `flutter install` but restore the performance; (2) keep this PR to fix `flutter install` but regress the performance. CC @Hixie @tvolkert @cbracken to see the preference over those two options.

**Comment by flar** [comment]
Here are some runs from ToT with the frame times plotted against each other. I see a very clear correlation with respect to when the long frames happen:

ToT 3 runs overlaid frame by frame
ToT Run 1 frame by frame plot
ToT Run 2 frame by frame plot (1)
ToT Run 3 frame by frame plot (1)

**Comment by tvolkert** [comment]
Trying to make sense of this long thread - do we understand _why_ this change regresses runtime performance?  Changing something that should have no bearing on the runtime artifacts should not be able to affect runtime performance...

Is it just debug performance as it relates to hot reload, or release performance?

**Comment by liyuqian** [comment]
It's not the debug performance. The iOS rasterization time is the profile mode performance, and it's highly correlated with release-mode janky animations according to our previous experiences.

I agree that it's very strange as libzip shouldn't affect rendering performance. @flar @christopherfujino : any update on the root cause?

**Comment by christopherfujino** [comment]
I have no update.

**Comment by flar** [comment]
We have no idea why this is happening. I've asked a bunch of people how we might be dependent on zip at run time and they have no clue.

Note also, that this is a change to the linking of a client side tool. I don't think it affects the binary we download in any way. Am I right there?

The best theory I have is that the version of zip we are using in these tools has changed and it is deciding on a different compression level or algorithm that changes the amount of processing that the client needs to deal with any compressed data in its bundle. But I say that without any idea of what compressed data would need to be dealt with during a run. This is, at best, a W.A.G...

**Comment by tvolkert** [comment]
I think at this point, we need to dig in and profile it to find out what specifically is slowing down.  Is someone willing to do that investigation?  @flar is that you?

**Comment by tvolkert** [comment]
@liyuqian are you able to dig into the cause of the performance issues that this triggered?

**Comment by liyuqian** [comment]
Sure, I can dig into it. But I don't have the device with me. @flar : can you please post two traces before and after this PR with `--trace-skia`? I'll try to analyze them to see if I can discover something useful.

**Comment by flar** [comment]
If you are looking for --trace-skia then I guess you are looking for Observatory runs, but the benchmark takes a few minutes to run which is much longer than the Observatory history shows. Also, the problem was mostly in just a few frames here and there and I'm not sure exactly when those are to be able to time a capture, especially with skia tracing which reduces the time window of Observatory traces a bit.

What specifically should I be trying to capture? Or is there a way to get a full Observatory capture from a benchmark run?

**Comment by liyuqian** [comment]
@flar : you can
1. Use `--trace-startup` to let the app use an endless buffer for tracing. It will capture all trace events until crash (out-of-memory).
2. Find what animation is triggering slow frames using your plot in https://github.com/flutter/flutter/pull/43677#issuecomment-576997032. Manually trigger those animations and only capture the short traces around those animations.

**Comment by liyuqian** [comment]
@flar : I recorded a video of the driver test https://photos.app.goo.gl/mS1gneTCT9Zge6hcA, and printed out the timestamp of each frame using https://github.com/flutter/flutter/pull/50272

Together with your analysis, I think the following transitions might need some tracing
```
3-92 frames: 0-2s first frame to studies transition

162-164 frames: 2-4s studies to shrine transition

240-256 frames: 4-5s studies to contact profile transition

366-381 frames: 7-9s material to bottom navigation transition

499-868 frames: 10-22s, button, card, chips, date and time pickers transition

90 frame => 1.7s

160 frame => 3.1s

240 frame => 4.8s

360 frame => 7.5s

500 frame => 10.1s

868 frame => 22s
```

I tried tracing myself using my Android phone but somehow Observatory isn't working properly and won't record or load any traces (my Flutter version is 49be146953b7a115af5e765ea9f792f110fcb007). @flar : can you try to trace the transitions above, and see any difference?

**Pull request merged**
