### PR TITLE
[flutter_tools] fix version tag `v` stripping

### LINKED ISSUE #55421: `flutter version` fails to parse the v in new tags correctly
Page URL: https://flutter.dev/docs/development/tools/sdk/releases.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/sdk/releases.md

Description of issue:

On the **Dev channel**, either Windows, Mac, or Linux, versions should start with a **v**. 

There is an issue when switching to a certain version and using the exact version name. For example:
`flutter version 1.18.0-dev.5.0`  will try to switch the version to **1.18.0-de.5.0**
Using `flutter version v1.18.0-dev.5.0` will switch to the correct version **1.18.0-dev.5.0**

I think the cause is that the **flutter version** command strips the first **v** that is found in the version tag.

This happens for the **Dev channel** starting with version tag **1.17.0-dev.0.0** 

This same issue appears on the latest published **Beta channel** version tag, **1.17.0-dev.3.1**.

### PR DESCRIPTION
**Pull request by peterlauri**
## Description

This fixes an incorrect string replacement that is intended to strip the first v, for example:

v1.0.0 => 1.0.0
1.0.0.dev.0 => 1.0.0.dev.0 (actual 1.0.0.de.0)

## Related Issues

Fixes https://github.com/flutter/flutter/issues/55421 and https://github.com/flutter/flutter/issues/55383

## Tests

Added test "dev version switch prompt is accepted" that checks that dev versions can be requested in the **flutter version** command.

Also fixed the test it self, as it had the same defect as the implementation it self.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jonahwilliams** [comment]
@peterlauri this approach seems good, so if you're interested in working on please let us know

**Comment by peterlauri** [comment]
Hi, yes. I just need to figure out my the development environment :) Want
to add a test that proves the problem as well...

**Comment by christopherfujino** [comment]
> Hi, yes. I just need to figure out my the development environment :) Want to add a test that proves the problem as well...

Sounds great. You will want to add a test to this file: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands.shard/hermetic/version_test.dart. Let me know if you need any additional help. I was going to try to patch this today, but if you can land this PR today it's all your's :)

**Comment by peterlauri** [comment]
@christopherfujino my biggest problem is to setup VScode to follow the styling guides. Any hint on a settings file or something? :)

**Comment by peterlauri** [comment]
To be honest, I don't know if I followed the style guides... I'll use Nano and fix the test styling for now, as VScode formatts plenty of things :)

**Comment by peterlauri** [comment]
To confirm the fix, revert the fix, and run

```
../../bin/cache/dart-sdk/bin/pub run test test/commands.shard/hermetic/version_test.dart
```

**Comment by christopherfujino** [comment]
> @christopherfujino my biggest problem is to setup VScode to follow the styling guides. Any hint on a settings file or something? :)

Sorry I just saw this now. Unfortunately, you cannot use autoformatting to follow our style guide.

**Comment by christopherfujino** [comment]
I'm looking at the test now...

**Comment by peterlauri** [comment]
@christopherfujino personally I would have refactored and parameterised the tests... But I gotta learn more about dart tests, coming from python/pytest background where I know exactly how to do it.

**Comment by christopherfujino** [comment]
@peterlauri this looks great! Thanks so much for this contribution!

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by christopherfujino** [comment]
Shucks, unfortunately this failed testing on post-submit and was reverted. If I have free cycles today I'll investigate...

**Comment by peterlauri** [comment]
@christopherfujino anything I can do to help?

**Comment by christopherfujino** [comment]
Sure, you could investigate why this test passed on pre-submit but failed on post: https://cirrus-ci.com/task/6113630626250752?command=main#L336

**Comment by peterlauri** [comment]
@christopherfujino sure, I'm on it. Can confirm after merging master prior to the merge that the test fails...

**Comment by peterlauri** [comment]
@christopherfujino Are tags like **1.18.0-dev.5.0** expected to be used with 'flutter version'? Or only tags like **1.18.0-6.0.pre**?

**Comment by christopherfujino** [comment]
> @christopherfujino Are tags like **1.18.0-dev.5.0** expected to be allowed with 'flutter version'? Or only tags like **1.18.0-6.0.pre**?

The short answer is no, the tags of the form `1.18.0-dev.5.0` are no longer allowed (although that is a recent change with the latest release).

**Comment by christopherfujino** [comment]
Ahh, I see, this must have passed on pre-submit because it was branched before the change was made.

**Comment by peterlauri** [comment]
@christopherfujino I know that is changed, but as the old tags exist should flutter version allow them? It is a fairly easy fix to allow both, and I'm happy to do that fix. Your call...

**Comment by christopherfujino** [comment]
Another instance that would have been caught by https://github.com/flutter/flutter/issues/53366

**Comment by christopherfujino** [comment]
Sorry, you're right that `flutter version 1.18.0-dev.5.0` should be allowed. But I think the test passed pre-submit because it wasn't rebased off of upstream.

**Comment by peterlauri** [comment]
Yes, I'll add test for both dev and pre and fix the implementation. Easy
one :)

**Pull request merged**
