### PR TITLE
Disable Dart analysis in Fuchsia.

### PR DESCRIPTION
**Pull request by pylaligand**
Fuchsia will soon use a newer version of the Dart analysis server which Flutter code has not been adjusted for yet.

### CODE REVIEW

**Comment by Hixie** [comment]
What are the errors? We can just fix them instead...

**Comment by pylaligand** [comment]
I don't have the list handy but I can generate it tomorrow.

The fundamental issue is that Flutter code is analyzed against an older version of the Dart analyzer whereas in Fuchsia we're soon going to be using a very recent one. Even if we do fix these errors, there's no guarantee that a new one won't show up and not be caught by your CI.

**Comment by pylaligand** [comment]
Here are the errors:
```
  info • A function of type '(_DropdownRouteResult<T>) → Null' can't be assigned to a variable of type '(dynamic) → FutureOr<Null>' at lib/src/material/dropdown.dart:545:56 • (uses_dynamic_as_bottom)
  info • A function of type '(Map<String, dynamic>) → Future<dynamic>' can't be assigned to a variable of type '(dynamic) → Future<dynamic>' at lib/src/widgets/binding.dart:181:45 • (uses_dynamic_as_bottom)
  info • A function of type '(_TableElementRow) → LocalKey' can't be assigned to a variable of type '(dynamic) → LocalKey' at lib/src/widgets/table.dart:305:14 • (uses_dynamic_as_bottom)
  info • A function of type '(_TableElementRow) → List<Element>' can't be assigned to a variable of type '(dynamic) → List<Element>' at lib/src/widgets/table.dart:306:14 • (uses_dynamic_as_bottom)
```

This only happens with strong mode enabled.

**Comment by Hixie** [comment]
The problem is that it's not just the analyzer that's different here; if we diverge too much you'll actually be running the wrong language (e.g. these changes are real changes, which should either not be flagged yet because the VM doesn't yet do this strong mode stuff, or which should be flagged _and will cause build errors_ because the code won't compile).

**Comment by Hixie** [comment]
@leafpetersen what's the story or these?

**Comment by Hixie** [comment]
@pylaligand Well in any case LGTM, because it makes sense that downstream consumers of Flutter wouldn't need to worry about our issues, it's our job (Flutter team) to make sure Flutter doesn't have bugs, and if something slips through (or if you look for different analysis issues) that's not your problem.

**Comment by leafpetersen** [comment]
Some more context on these new hints (soon to be errors) here:  https://github.com/dart-lang/sdk/issues/29630 .

Basically, before we had a way to use `Null` as the `bottom` type, strong mode would accept some certain statically unsafe usage patterns at the cost of having to use a more expensive calling convention for all functions with `dynamic` as an argument type.

As we unify strong mode into Dart 2.0, we're eliminating this special treatment.

**Comment by Hixie** [comment]
@leafpetersen I don't understand how to apply that to these cases, but we should follow up in a separate bug or PR.

**Comment by leafpetersen** [comment]
@Hixie sure ping me or file a bug and we can work through it.

**Pull request merged**
