### PR TITLE
Added the ability to bring up the date picker dialogs in calendar or text input only mode.

### LINKED ISSUE #72513: DatePickerHeader should has option to disable/hide `entryModeIcon`
## Use case

In application there should be an option to disable edit mode icon via some property [true/false]. In our app we don't want to use `DatePickerEntryMode.input` at all and maybe more developers want to disable that option.

## Proposal

Add property to DatePickerHeader to disable `entryModeIcon`

### PR DESCRIPTION
**Pull request by darrenaustin**
We have had a request to remove the entry mode switching buttons from the date picker dialogs. This PR adds two new values to the `DatePickerEntryMode` enum: `calendarOnly` and `inputOnly`.  These function exactly like the non-'only' counterparts, but remove the button in the dialog header that allows the user to switch calendar and input entry modes. This doesn't change the defaults, it just provides an option for apps that need to restrict the dialogs to only one mode of entry. This applies to the dialogs displayed by `showDatePicker` as well as `showDateRangePicker`.

| calendar  | calendarOnly |
| ------------- | ------------- |
| calendar  | calendarOnly  |

| input  | inputOnly |
| ------------- | ------------- |
| input  | inputOnly |

This looks like more changes than would be necessary, but that is only due to the fact that I refactored how the toggle button was implemented in the header to make it easier for us to add more action buttons there in the future.

Fixes #72513

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by rami-a — APPROVED** [review]
LGTM

**Review by HansMuller — APPROVED** [review]
LGTM

**Comment by malavikaa** [comment]
@darrenaustin In which flutter version is this change available?

**Comment by darrenaustin** [comment]
Looking at the tags on the [commit](https://github.com/flutter/flutter/commit/539510b4a1328b3bcde8ec60cc90d13bb7e88b6f) above it looks like it is tagged 2.3.0-16.0.pre which would put it on the Dev channel as well as Master. See the [releases page](https://flutter.dev/docs/development/tools/sdk/releases) for the details.

**Comment by Okiring** [comment]
am having flutter version 2.0.5 and cant see this setting anywhere. I only see initialEntryMode option that doesn't disable or remove the edit icon on the calendar.

**Comment by darrenaustin** [comment]
As I mentioned in my previous comment this feature is tagged with 2.3.0-16.pre so 2.0.5 will not have this feature. Currently it is only available on the Dev and Master channels.

**Pull request merged**
