### PR TITLE
Update EdgeInsets to EdgeInsetsGeometry in PopupMenuItem #106866

### PR DESCRIPTION
**Pull request by MuhmdHsn313**
In `PopupMenuItem`  I upgrade `EdgeInsets` to `EdgeInsetsGeometry` for multiple languages support (right to left and vice versa), where if there is more than one language in the application it requires the use of EdgeInsetsDirectional instead of EdgeInsets.

#106866

### CODE REVIEW

**Comment by goderbauer** [comment]
@MuhmdHsn313 Thanks for the contribution! Can you sign the CLA (see previous post for details)? Also, we require tests for all changes to make sure that we never break or undo this in the future. Can you please add one?

**Comment by MuhmdHsn313** [comment]
Ok, I signed the CLA, also I will add the tests.

**Comment by goderbauer** [comment]
@MuhmdHsn313 Do you still have plans to get back to this?

**Comment by goderbauer** [comment]
I am going to close this one since there has been no follow-up.

**Pull request closed without merging**
