### PR TITLE
Fix examples/api docs for extract_sample

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
The `README.md` in `examples/api` is the only place where I found any information about how to extract snippets. But it simply did not work for me. So (since I did not find any documentation nor source code for this tool anywhere) I dug and eventually found out that the correct command is actually just `snippets:extract` (don't ask me how I found out).

*Update*: after https://github.com/flutter/assets-for-api-docs/pull/168, this is now `snippets:extract_sample` → I adjusted the PR to match that.

Maybe I am wrong (would be cool 😜) → would be awesome to get some pointers about where docs for this live and if I am doing something wrong.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
Fixes #89068

**Comment by Hixie** [comment]
cc @gspencergoog for review

**Comment by gspencergoog** [comment]
Actually, I think we probably just want to remove the information about extract_sample.  All the samples have been extracted, and will stay that way, so nobody should need to do it anymore: they'll just author their sample by creating an entry that points to the correct file.

**Comment by creativecreatorormaybenot** [comment]
@gspencergoog Did the format of the samples change? Because I had no clue how I would go about doing it without the command 🤔

**Comment by gspencergoog** [comment]
Yes, the samples were moved out of the API comments and into separate files under `examples/api`, and the format in the API doc comments is as described in the current [README.md](https://github.com/flutter/flutter/tree/master/examples/api#readme).

I've actually already removed all of the instructions from the README about the extract_samples tool.

**Comment by Hixie** [comment]
> I've actually already removed all of the instructions from the README about the extract_samples tool.

Is this PR moot then?

**Comment by creativecreatorormaybenot** [comment]
@Hixie I will close this for now - let me know if this is not the case

**Pull request closed without merging**
