### PR TITLE
Fixed preferredSize getter in TabBar

### PR DESCRIPTION
**Pull request by setsrc**
Fixes an issue in the material TabBar where the preferredSize was not being set correctly if the "child" constructor parameter was used instead of the "text" constructor parameter. The issue caused the AppBar to appear shorter than it needed to be, potentially cutting off or suffocating the Title.

## Description
For example:
The following tab added to a TabBar causes the AppBar to expand vertically to accommodate the Icon and Text pair.
`Tab(text: 'Title', icon: const Icon(Icons.notifications))`

However, the identical widget structure below, does not cause the AppBar to expand vertically, treating the Tab as if there was only an Icon. This causes the AppBar Title to be cut off or suffocated.
`Tab(child: Text('Title'), icon: const Icon(Icons.notifications))`

In the TabBar constructor, the height is set properly if a child constructor parameter, but not passed on to the AppBar through the use of the 'preferredSize' getter.

This pull fixes the issues listed above.

## Related Issues

None

## Tests

I added the following tests:

- TabBar expands vertically to accommodate the Icon and child Text() pair the same amount it would expand for Icon and text pair.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by AnthonyMansour** [comment]
@googlebot I signed it!

**Comment by slightfoot** [comment]
I had this same issue. Thanks for the fix. 

To merge it'll need tests.. can you add two tests to one with and without child calling the preferredSize getter to verify the behaviour.

https://github.com/flutter/flutter/blob/master/packages/flutter/test/material/tabs_test.dart

**Comment by HansMuller** [comment]
@ AnthonyMansour this PR is still labeled "Work in Progress, do not review". If you're interested in having it reviewed, you'll want to remove the label.

**Comment by AnthonyMansour** [comment]
> @ AnthonyMansour this PR is still labeled "Work in Progress, do not review". If you're interested in having it reviewed, you'll want to remove the label.

@HansMuller 
I don't think I can. Don't have permission.

**Comment by HansMuller** [comment]
@AnthonyMansour  - I didn't realize that the WIP label couldn't be changed. Will take a look at this next week.

**Review by HansMuller — APPROVED** [review]
Nice change; LGTM. 

Will land this PR after checking the 3rd party test suite (assuming that the tests pass).

**Comment by HansMuller** [comment]
This PR doesn't cause any failures in the 3rd party test suite; will land it when the build goes green. Thank-you for the contribution!

**Pull request merged**
