### PR TITLE
[flutter_tools] use package:vm_service types for coverage collection requests

### PR DESCRIPTION
**Pull request by jonahwilliams**
~~Attempt to reduce coverage network chatter by caching script objects by URI~~ This was a failure.

Update the coverage collection to use the actual typed VM Service objects instead of Map<String, Object>

### CODE REVIEW

**Comment by jonahwilliams** [comment]
this isn't safe since the token pos table can change

**Comment by jonahwilliams** [comment]
actually wait no, it should be OK

**Comment by jonahwilliams** [comment]
I attempted to cache the token position tables across test runs. I found that they were not stable. instead, I opted to update the coverage collection code to use the package:vm_service types. This does not have any impact on performance but will make the code easier to update in the future.

**Comment by jonahwilliams** [comment]
FYI @bkonyi , just an idea of what we're doing today to collect coverage.

**Review by zanderso — APPROVED** [review]

**Pull request merged**
