### PR TITLE
Prefer .of to .from

### PR DESCRIPTION
**Pull request by dnfield**
.from uses a typecast.

.of does not.

We should have a lint for this - see https://github.com/dart-lang/sdk/issues/58359

There's not really a good way to test this right now. What we really want is a lint.

For historical context: my understanding is that `from` is more of a Dart 1 thing that was the original go-to and `of` was added later to make better use of types.

### CODE REVIEW

**Comment by Hixie** [comment]
Why not just `.toList()`?

**Comment by Hixie** [comment]
test-exempt: preparing codebase for future lint (https://github.com/dart-lang/linter/issues/2555)

**Comment by dnfield** [comment]
These aren't always lists.

**Comment by Hixie** [comment]
the List.of() cases are always Iterables though right? And can always take toList?

**Comment by dnfield** [comment]
Presumably yes. But I got here from looking at maps

**Comment by goderbauer** [comment]
The implementation of toList is to forward to List.of: https://master-api.flutter.dev/flutter/dart-core/Iterable/toList.html

**Comment by Hixie** [comment]
fair enough.

FWIW in general i feel toList is more idiomatic (and shorter) but I don't have a strong opinion here.

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
