### PR TITLE
Use correct branch for version checks on beta/dev

### PR DESCRIPTION
**Pull request by DanTup**
I've seen a number of complaints about Flutter telling people they're out of date when they're on latest beta (because the commit date is old) so I was going to look at putting a "real" update check in and discovered that there was already code to check the dates on the remote commits! Unfortunately it always used `master` branch unless you were on `alpha` so when you were more than x days out of date, it would always then warn you.

This PR adds `dev` and `beta` to the list of safe branches for checking (I'm not sure entirely why we need a safe list though, maybe it's to support checking against master when you're working on flutter on a branch?).

With this, when your beta is "too old" it should check the remote commit date and only warn if that's newer (eg., if there's actually a version you could update to on this branch).

This doesn't totally implement #14920 because it won't alert you until after 4 weeks(?), however simply reducing that duration to a lower number (or removing it entirely) may completely implement it.

Kinda Related:
- #15862
- #17748
- #14920

### CODE REVIEW

**Review by devoncarew — APPROVED** [review]

**Comment by DanTup** [comment]
I've changed this to use `officialChannels`. Does anyone know if there are any reasons not to just use the branch name as-is? (cc @tvolkert @yjbanov @jason-simmons). The current behaviour would fall back to checking `master` if you're on your own branch could be convenient, but I don't know how likely people would be on a branch that's not in `officialChannels` or what they'd expect.

**Comment by tvolkert** [comment]
It's done to handle the case of the user being on their own branch.

@Hixie are we ok dropping the special-case handling of `alpha`?  It's been almost 6 months...

**Comment by DanTup** [comment]
> It's done to handle the case of the user being on their own branch.

So we want it to check against master in that case? If so, we should stick with `officialChannels` rather than removing the whitelist.

> @Hixie are we ok dropping the special-case handling of `alpha`?

Ah, good spot - I didn't notice that `alpha` isn't in `officialChannels`. If we want to preserve it, we can put the special case back in but then fall back to the `officialChannels` check instead of always going to `master`.

**Comment by tvolkert** [comment]
Sounds like we do want to preserve the `alpha` channel handling, at least for a little longer.

**Comment by Hixie** [comment]
We can drop the handling of alpha. We just can't delete the branch itself yet.
(Nobody using this code will be on alpha.)

**Pull request merged**
