### PR TITLE
Add IPv6 loopback address to Doctor's proxy check

### LINKED ISSUE #26587: Add IPv6 loopback address to Doctor's proxy check if localhost resolves to it
If `HTTP_PROXY` is set we currently check that `127.0.0.1` and `localhost` are in `NO_PROXY` but we don't check for the IPv6 loopback (`::1`). Since `localhost` may resolve to it, we should check it too, but in order to avoid showing warnings to lots of people that may not be using IPv6 we should first check if `localhost` resolves to it.

(see https://github.com/flutter/flutter/issues/14991#issuecomment-454428345).

### PR DESCRIPTION
**Pull request by amogiska**
Add IPv6 loopback address to Doctor's proxy check. Only do this if ::1 is a valid loopback address.

## Related Issues

Fixes: https://github.com/flutter/flutter/issues/26587

## Tests

I amended the tests in `doctor_test.dart` as follows
- The group `proxy validator` now accounts for ipv6 loopback addresses.
- I've added the group `proxy validator ipv4` specifically for configurations that do not support ipv6.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by jonahwilliams** [comment]
FYI @Hixie @fkorotkov we're getting a "User is too new.." error when running this. What can we do to allow new users to submit PRs?

**Comment by fkorotkov** [comment]
It's a mechanism agains some enthusiasts that create bunch of new users and try to mine crypto coins so users that were created in less than 3 days are considered suspisious at the moment. I've whitelisted @amogiska. Sorry for the inconveniences!

**Comment by jonahwilliams** [comment]
That makes sense, but what I found surprising is that even If I try to trigger re-runs on their PR I can't

**Comment by fkorotkov** [comment]
@jonahwilliams you need to retry this task first https://cirrus-ci.com/task/4739114782162944 or re-trigger all tasks here https://cirrus-ci.com/build/5199878303252480 (I think you should see the button)

**Comment by zanderso** [comment]
@fkorotkov I clicked the button to re-trigger all tasks. It re-triggered the first one in the list, but not subsequent ones. I manually retried the first couple that it missed, and it looks like it is now retrying them. I'll leave it in its current state in case you'd like to investigate. Thanks!

**Comment by fkorotkov** [comment]
@zanderso thank you! Seems it's because some of the tasks are having dependencies between each other which is usually not the case. Created https://github.com/cirruslabs/cirrus-ci-docs/issues/650

**Comment by zanderso** [comment]
@amogiska Sorry this has taken so long. The change looks good, but it looks like one of the new tests is failing.

**Comment by zanderso** [comment]
@jonahwilliams

**Comment by jonahwilliams** [comment]
We'll consider addressing this in a separate PR. In the meantime I'm going to close as we won't have the time to get to it

**Pull request closed without merging**
