### PR TITLE
Roll engine to b6c9ca555204872c1446acc801079ec1b02281f2 (with Dart roll)

### PR DESCRIPTION
**Pull request by alexmarkov**

### CODE REVIEW

**Comment by aam** [comment]
You will probably have to roll to b6c9ca555204 to include revert of breaking test.

**Comment by aam** [comment]
lgtm

**Review by aam — APPROVED** [review]

**Comment by Hixie** [comment]
It's hard to tell because the benchmark is very flaky but stock_build_iteration may have regressed a little around when this landed. I'm going to assume this is because the OS was upgraded, cc @yjbanov for confirmation.

**Comment by yjbanov** [comment]
If I'm reading the charts correctly the regression coincided with the commit just before this one, https://github.com/flutter/flutter/commit/f17c661e7dfeb27340ef7904781092322f3b48ef, which happened Wednesday morning. The OS upgrades took place Tuesday around https://github.com/flutter/flutter/commit/ece737d1450b3aa5cee0235742116d468bba8856, which had effect on `complex_layout_scroll_perf__timeline_summary`. So I doubt that this regression is due to OS upgrade, but also it seems that it not this PR, but the preceding one.

**Comment by Hixie** [comment]
Oh, interesting. Ok. @cbracken said he thought you maybe had upgraded iOS after the Android updates that led to the complex_layout_scroll_perf__timeline_summary regression.

**Comment by Hixie** [comment]
That said, this _is_ https://github.com/flutter/flutter/commit/f17c661e7dfeb27340ef7904781092322f3b48ef. :-)

**Comment by Hixie** [comment]
@aam Did you land this in a weird way? Github seems very confused about what commit this PR corresponds to in the commit history.

**Comment by alexmarkov** [comment]
There are 2 commits in this PR, in order to distinguish engine roll with Dart SDK from other engine rolls.

**Comment by yjbanov** [comment]
The diff in this PR matches that of https://github.com/flutter/flutter/commit/a3dc810f4b0a5bcd37659d41979e8a6eca2c714f. I'm not sure what's going on.

As for iOS, I have not yet upgraded it. I'm still testing the upgrade locally. It's not sending any data to the dashboard.

**Comment by yjbanov** [comment]
Oh, perhaps you used "Rebase and merge" instead of "Squash and merge"?

**Comment by alexmarkov** [comment]
> Oh, perhaps you used "Rebase and merge" instead of "Squash and merge"?

That's right.

**Comment by yjbanov** [comment]
Maybe we should stick to "Squash and merge"? This way Github would link the commits back to PRs.

**Comment by alexmarkov** [comment]
> Maybe we should stick to "Squash and merge"? This way Github would link the commits back to PRs.

Can you suggest another way of making a commit in Flutter which contains _only_ Dart SDK roll? To be measured separately from other changes in the engine or Flutter?

**Comment by yjbanov** [comment]
Hmm, no :)

**Comment by Hixie** [comment]
Rebase and merge is fine, just unusual. :-)

**Comment by Hixie** [comment]
(You can get to the PR number from the commit page on GitHub, it seems.)

**Comment by Hixie** [comment]
In any case, I think this means stock_build_iteration did in fact slightly regress on iOS with the Dart SDK roll.

**Comment by alexmarkov** [comment]
It looks like stock_build_iteration is rather flaky on iOS and now it is back to pre-roll values. @Hixie, are you able to reproduce the regression?

**Comment by Hixie** [comment]
I haven't tried. I agree that the numbers are back to where they were before. This benchmark is extremely flaky and I am not too worried about it.

**Pull request merged**
