### PR TITLE
Disable pause-on-exceptions for (outgoing) isolates during hot restart

### LINKED ISSUE #3448: restart will alway pending when there are many break points
**Describe the bug**

First, check the `All Exceptions` and `Uncaught Exceptions` at debug panel.

Then debug the following example code. When debugger stoped at exception in function `a`,  press continue button, the debugger will stoped at catch block in function `b`. Finally, click restart button, debugger will run into endless waiting.

```
import 'package:flutter/material.dart';

void a() {
  throw Exception('a');
}

void b() {
  try {
    a();
  } catch (e) {
    throw Exception('b');
  }
}

void c() {
  try {
    b();
  } catch (e) {
    throw Exception('c');
  }
}

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    c();
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Study Flutter',
      theme: ThemeData(
        primarySwatch: Colors.green,
      ),
      home: Container(),
    );
  }
}
```

image

**Expected behavior**

After I click the restart button, debugger should stopped at exception in function `a`

**Versions (please complete the following information):**
 - VS Code version: 1.58.0-insider
 - Dart extension version: 2.2.0
 - Dart/Flutter SDK version: 3.23.1

### LINKED ISSUE #3631: Apply hot-restart fix to Flutter DAP
The fix in #3448 needs reproducing in the Flutter DAP too.

### PR DESCRIPTION
**Pull request by DanTup**
This is a (proper) fix for https://github.com/Dart-Code/Dart-Code/issues/3448. The issue is that during a hot restart, all existing isolates must exit. There was existing code to resume them, and remove all breakpoints (so they don't get stuck), however they were still able to pause on exceptions if the user had enabled this.

This change removes the pause-on-exception behaviour in addition to the breakpoints. A previous fix for this was implemented in Dart-Code's DAP, but that was VS Code-specific, and VS Code will soon move to the Flutter SDK DAP so it needed either reproducing in the DAP or here (here makes more sense because it's the same issue as breakpoints, and the DAP base classes don't currently expose a way to set this only for specific isolates).

This is safe to do because editors need to set this flag per-isolate anyway, so when these isolates disappear and new ones are created, the editors will already re-send this setting.

Fixes https://github.com/Dart-Code/Dart-Code/issues/3448.
Fixes https://github.com/Dart-Code/Dart-Code/issues/3631.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by DanTup** [comment]
The remaining test failures seem to be races, where if we terminate the app while startup code is running (which happens here because we hot restart, then immediately terminate and things are coming back), some errors occur because in-flight requests are aborted as the VM Service shuts down.

I'll take a look tomorrow - I suspect the fix will be to ignore these types of error ("Service has disappeared") that if we know we're already shutting down.

**Comment by DanTup** [comment]
Tests all green now 👍

**Comment by DanTup** [comment]
@christopherfujino not urgent, but in case you missed this :-)

**Comment by christopherfujino** [comment]
> @christopherfujino not urgent, but in case you missed this :-)

Thanks, I did (miss this).

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by DanTup** [comment]
Thanks!

**Pull request merged**
