### PR TITLE
Re-generate lockfiles for gradle_deprecated_settings integration test

### LINKED ISSUE #122039: Updating to androidx.annotation:annotation:1.5.0 is causing CI failures.
Take a look at https://github.com/flutter/flutter/pull/121847#discussion_r1124797112? I think by bumping a dependency on androidx.annotation:annotation:1.5.0, now some of the test apps in the flutter framework cannot do dependency resolution. 

https://github.com/flutter/packages/pull/3271/files#diff-a7a667ae2f4a6b9d0a2fc91cc1eb18310cf7bc98cecbcd9b27fe444028d87887R37

### PR DESCRIPTION
**Pull request by gmackall**
This fixes https://github.com/flutter/flutter/issues/122039. 

To generate these changes I ran 
`echo ./android/ | dart ~/development/flutter/flutter/dev/tools/bin/generate_gradle_lockfiles.dart` 
from 
`flutter/dev/integration_tests/gradle_deprecated_settings`
I also had to change a version in gradle-wrapper.properties and added an android-exported flag, to allow the script to run.

I confirmed that the test passes by running 
`dart run test test/integration.shard/deprecated_gradle_settings_test.dart`

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by gmackall** [comment]
Hmm, looks like it is failing to download dependencies because it can't find version 2.0.9 of [flutter_plugin_android_lifecycle](https://pub.dev/packages/flutter_plugin_android_lifecycle).

**Comment by gmackall** [comment]
Seems like a similar PR here failed: https://github.com/flutter/flutter/pull/119290. 

Need to look into if there is similarity in why.

**Comment by reidbaker** [comment]
Note for you gradles documentation says to write locks use `./gradlew --write-locks`. It appears that flutter wrote their own task to update locks which is available to run with `./gradlew :generateLockfiles`

**Comment by gmackall** [comment]
Closing in favor of https://github.com/flutter/flutter/pull/128898#pullrequestreview-1480275555

**Pull request closed without merging**
