### PR TITLE
[tool] Update `.gitignore` templates to include `.flutter-plugins` files

### LINKED ISSUE #152793: [tool] Generated `.gitignore` for template `package` should include `.flutter-plugins` files
Adding a flutter plugin as a dependency to a package generates these files. The non-package template `.gitignore` contains these.

### PR DESCRIPTION
**Pull request by Rexios80**
Fixes https://github.com/flutter/flutter/issues/152793

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by jmagman — COMMENTED** [review]
See https://github.com/flutter/flutter/pull/152766 for an example of how existing gitignores can be migrated.

**Comment by andrewkolos** [comment]
@jmagman Do you have any opinions on whether adding a migrator for existing .gitignores should be a blocker for this PR?

**Comment by Rexios80** [comment]
I don't have the bandwidth to write a migration for this right now. Also a migration is questionably useful since anyone who already accidentally checked in these files won't benefit without manually removing them from VCS.

**Comment by jmagman** [comment]
> @jmagman Do you have any opinions on whether adding a migrator for existing .gitignores should be a blocker for this PR?

I don't think it's a blocker.

**Comment by Rexios80** [comment]
@jmagman If that's the case can you please approve this PR? Or does it need other changes.

**Review by jmagman — APPROVED** [review]
> @jmagman If that's the case can you please approve this PR? Or does it need other changes.

Based on @stuartmorgan's comment in https://github.com/flutter/flutter/issues/152793#issuecomment-2271911708 this LGTM.

**Pull request merged**
