### PR TITLE
Fix formatting in rendering/box

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
This only fixes a tiny formatting issue. I noticed it while reading through the dry layout rendering code again.

There is no issue to link, of course.

I am not sure if a PR (commit on `master`) is even worth it for such a small change. On the flip side, I am not sure if this would ever be fixed otherwise. Are there existing considerations on this subject?

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by xu-baolin — APPROVED** [review]
LGTM, thanks for fixing this.

**Comment by creativecreatorormaybenot** [comment]
@xu-baolin Thanks! Can you deflake or is this an issue on master?

**Comment by xu-baolin** [comment]
Can you update your branch to the master? The tree seems to green now.

**Comment by creativecreatorormaybenot** [comment]
@xu-baolin Done 👍

**Pull request merged**
