### PR TITLE
ProGuard rules for Flutter

### PR DESCRIPTION
**Pull request by swavkulinski**
Quite blanket approach to Flutter part but it prevents 
https://github.com/flutter/flutter/issues/15100

### CODE REVIEW

**Comment by najeira** [comment]
By default, minifyEnabled should be off. Because we do not know whether third party plugins works or not with proguard.

**Comment by swavkulinski** [comment]
ok i will disable flags just leave the proguard config.

**Comment by Hixie** [comment]
I really would prefer that we removed files from our template instead of adding more, but...

cc @tvolkert @mravn-google

**Comment by swavkulinski** [comment]
Write docs instead?

**Comment by mravn-google** [comment]
@swavkulinski I think that would be a good alternative, yes. PRs to the [website repo](https://github.com/flutter/website) are more than welcome. The page to change would likely be [android-release-build.md](https://github.com/flutter/website/blob/master/android-release-build.md).

**Comment by Rockvole** [comment]
https://stackoverflow.com/questions/51342391/how-to-check-obfuscation-results-of-flutter-app

**Pull request closed without merging**
