### PR TITLE
Fix timer keeps active when resampling disabled in some cases

### PR DESCRIPTION
**Pull request by wangying3426**
Fix timer still keeps active when resampling disabled.

The problem will  occur like this:
- A developer set [`resamplingEnabled`](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/gestures/binding.dart#L506) to true.
- When events received, a [periodic timer](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/gestures/binding.dart#L168)  for resampling will be started until all resamplers are finished. But if one event's timestamp is larger than current simple time,  its resampler will keep resampling.
- Then, the developer set `resamplingEnabled` to false, at this moment the periodic time still keeps active .

For example, https://github.com/flutter/engine/pull/30422 shows a case that the timestamp of a fake event is much more than current sample time, so its resampler and the timer will keeps active for a very long time.

For the tests, an assert exception will occur and tests will failed  if  `_timer?.cancel` not be called.
```dart
Pending timers:
Timer (duration: 0:00:00.016667, periodic: true), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:284:41)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:248:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:183:19)
#5      _Resampler.sample.<anonymous closure> (package:flutter/src/gestures/binding.dart:168:24)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1090:9)
#8      AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame (package:flutter_test/src/binding.dart:1074:5)
#9      runApp (package:flutter/src/widgets/binding.dart:1037:7)
#10     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:813:7)
<asynchronous suspension>
(elided 2 frames from dart:async)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1236 pos 12: '!timersPending'

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1236:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:821:7)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)

The test description was:
  Timer should be canceled when resampling stopped
════════════════════════════════════════════════════════════════════════════════════════════════════
00:03 +1 -1: Timer should be canceled when resampling stopped [E]                                                                                                                                        
  Test failed. See exception logs above.
  The test description was: Timer should be canceled when resampling stopped
  
00:03 +1 -1: Some tests failed.    
```

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 6 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/97197

**Comment by skia-gold** [comment]
Gold has detected about 41 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/97197

**Comment by skia-gold** [comment]
Gold has detected about 30 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/97197

**Comment by skia-gold** [comment]
Gold has detected about 49 new digest(s) on patchset 4.
View them at https://flutter-gold.skia.org/cl/github/97197

**Comment by skia-gold** [comment]
Gold has detected about 50 new digest(s) on patchset 5.
View them at https://flutter-gold.skia.org/cl/github/97197

**Comment by skia-gold** [comment]
Gold has detected about 37 new digest(s) on patchset 6.
View them at https://flutter-gold.skia.org/cl/github/97197

**Comment by skia-gold** [comment]
Gold has detected about 12 new digest(s) on patchset 7.
View them at https://flutter-gold.skia.org/cl/github/97197

**Comment by skia-gold** [comment]
Gold has detected about 49 new digest(s) on patchset 8.
View them at https://flutter-gold.skia.org/cl/github/97197

**Comment by goderbauer** [comment]
@wangying3426 Looks like this PR is addressing two different issues? Can you please split it in two so we can evaluate (and land) them seperatly?

**Comment by skia-gold** [comment]
Gold has detected about 24 new digest(s) on patchset 9.
View them at https://flutter-gold.skia.org/cl/github/97197

**Comment by wangying3426** [comment]
> 
@goderbauer  I have modify this PR to focus only one issue.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
@wangying3426 Can you rebase this to the latest master to make the checks pass, please?

**Comment by skia-gold** [comment]
Gold has detected about 38 new digest(s) on patchset 11.
View them at https://flutter-gold.skia.org/cl/github/97197

**Comment by wangying3426** [comment]
> @wangying3426 Can you rebase this to the latest master to make the checks pass, please?

@goderbauer I have merged master branch, but it still seems to have some tests failed.

**Comment by goderbauer** [comment]
Restarted the tests, let's see if it was just flakes...

**Review by eggfly — APPROVED** [review]

**Comment by wangying3426** [comment]
@goderbauer Could you please also review this related PR https://github.com/flutter/engine/pull/30422 ？ thanks.

**Comment by goderbauer** [comment]
@wangying3426 It would be best to have that one reviewed by an engine expert.

**Pull request merged**
