### PR TITLE
Thin iOS app frameworks to the target architecture

### PR DESCRIPTION
**Pull request by cbracken**

### CODE REVIEW

**Review by chinmaygarde — APPROVED** [review]
lgtm. There is no sense in doing this is in non-release modes. It will just add to the time it takes to launch the application for development/debugging. Also, I would write it in Dart instead of shell.

**Comment by cbracken** [comment]
Rewritten from scratch with some additional error checking and lipo -info output in the case where an architecture isn't present. 

> There is no sense in doing this is in non-release modes.

Is there a foolproof way of detecting release vs non-release builds? `CONFIGURATION` won't be safe since developers can rename them at will. It'd be relatively simple to rule it out for simulator builds with a check against `CURRENT_PLATFORM` == `iphonesimulator` but that doesn't cover device debug builds. There are probably a few other heuristics we could use (like whether debug symbols are enabled), but given that it takes ~0.4s to run this (with just the Flutter framework), I wonder if the additional complexity is worth it.

**Comment by cbracken** [comment]
Fixes #7908.

**Comment by chinmaygarde** [comment]
lgtm. I guess if it is fast enough, it doesn't matter.

**Comment by cbracken** [comment]
sgtm. I've got a followup that rewrites all the `thin` command in Dart. Will get the `build` code and tests done and send as a followup patch.

That work still needs a bit of performance tuning; the runtime is ~1.2s vs 0.4s for the shell version. Will take a look at whether snapshotting helps significantly and if so, we can do what we do with the `flutter` tool.

**Comment by xster** [comment]
I may be reading incorrectly but wouldn't this cause issues with armv7 users if we declare support for standard architectures but stripped out armv7 from libraries?

**Comment by cbracken** [comment]
Part of this patch was to change the `ARCHS` setting from 'Standard architectures' to `arm64`. We don't update `VALID_ARCHS`, but given that Xcode only builds the intersection of `VALID_ARCHS` and `ARCHS`, we should be okay. (Personally I'd like to get armv7 builds working and revert 388280f.

**Comment by xster** [comment]
Ah, understood

**Pull request merged**
