### PR TITLE
update packages

### PR DESCRIPTION
**Pull request by christopherfujino**
to fix the tree.

I manually updated the pubspec template file to work around https://github.com/flutter/flutter/issues/61687

### CODE REVIEW

**Review by CareF — APPROVED** [review]
LGTM. Thanks!

**Comment by christopherfujino** [comment]
I'll land on red after at least analysis and the tools pass

**Review by jason-simmons — APPROVED** [review]

**Comment by christopherfujino** [comment]
shoot, commands failed

**Comment by christopherfujino** [comment]
```
SLVR:     conflict: every version of flutter_driver from sdk depends on test_api 0.2.18
SLVR:   derived: test_api 0.2.18
SLVR:   conflict: test >=1.15.0 <1.15.3-∞ depends on test_api 0.2.17
```

**Comment by christopherfujino** [comment]
updated a pubspec template that the commands create test uses

**Comment by christopherfujino** [comment]
landing on red to fix the tree

**Pull request merged**
