### PR TITLE
Exposing hook about tickers with zero overhead

### PR DESCRIPTION
**Pull request by fzyzcjy**
1. I will finish code details, refine code, add tests, make tests pass, etc, after a code review that thinks the *rough idea* is acceptable. It is because, from my past experience, reviews may request changing a lot. If the general idea is to be changed, all detailed implementation efforts are wasted :)
2. The PR has an already-working counterpart, and it produces ~60FPS smooth experimental results. The benchmark results and detailed analysis is in chapter https://cjycode.com/flutter_smooth/benchmark/. All the source code is in  https://github.com/fzyzcjy/engine/tree/flutter-smooth and https://github.com/fzyzcjy/flutter/tree/flutter-smooth.
3. Possibly useful as a context to this PR, there is a whole chapter discussing the internals - how flutter_smooth is implemented. (Link: https://cjycode.com/flutter_smooth/design/)

---

This PR is a part for implementing the 60fps smooth rendering (#101227).

Some discussions can be seen in Discord, such as around https://discordapp.com/channels/608014603317936148/608021234516754444/1024141682377236500.

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/101227

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

P.S. Not sure what naming do you like, so just put a very long (temporary) variable name here :)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by dnfield — CHANGES_REQUESTED** [review]
This patch needs a lot more context.

What's the main goal you're trying to achieve with this particular change?

Why is it doing it this way?

Why can't we used existing mechanisms to achieve the same thing?

Why do we need this mechanism to achieve the larger goal of having incremental/progressive layout?

**Comment by fzyzcjy** [comment]
Thanks, I did discussed with Hixie on discord and wrongly thought that public discussion was enough. I will fill all those contents in a few hours.

**Comment by fzyzcjy** [comment]
@dnfield 

**What is the big picture that it fixes?**

The ultimate goal is, let the app run smoothly at 60FPS, even if it has heavy subtree that is very slow to build/layout. In other words, the design doc: https://docs.google.com/document/d/1FuNcBvAPghUyjeqQCOYxSt6lGDAQ1YxsNlOvrUx0Gko

It already has a working demo. See the (new) "experiments" chapter, with a video, screenshots, full code, brief code, benchmark, analysis.

**What's the main goal you're trying to achieve with this particular change?**

In order to solve that big goal, we must let animation callbacks run at 60FPS even if the whole tree is very slow to build/layout. Otherwise, even if we refresh a subtree by 60FPS, anything like CircularProgressIndicator, FooTransition, or manual AnimationController will all never be smooth, because they do not see new timestamp at 60FPS.

Then, to fire (extra) animation callbacks, a natural solution is to work with the `Ticker`s. Originally, `Ticker`s are fired once per frame. But now, we also extra fire it (with proper timestamp) in each 60FPS smooth extra frame.

Lastly, to fire extra events to `Ticker`s , we must know the existence of Tickers in the auxiliary widget subtree (no need for Tickers in the main subtree since they should not be fired at 60FPS). That is why I added a callback when Tickers are created - then I can record it such that to fire extra ticks.

**Why is it doing it this way?**

Why it is a compile time flag `FLUTTER_ENABLE_TICKER_PROVIDER_STATE_MIXIN_CREATOR`: Because Hixie is worried about performance loss (in Discord hackers-framework). Making it a compile time flag, then nobody will have any even tiny bit of performance loss, if they do not need this feature.

Why there is `debugOverrideEnableTickerProviderStateMixinTickerCreator` in addition to compile time flag: Because Hixie said compile time flags are hard to test. By using this `debugOverride...` flag we can test it easily (indeed I have written tests there).

Why a context must be passed to the callback: Because as mentioned above, I need to determine whether it is in the second subtree or main subtree.

Btw the name is temporary, just suggest any name you like :)

**Why can't we used existing mechanisms to achieve the same thing?**

Well, Hixie and I have tried, but cannot come up with a solution :/ Feel free to suggest solutions! Microscopic speaking, seems that cannot know a Ticker in a TickerProviderMixin is created so cannot gather them. Macroscopic speaking, did not find other ways to let it be smooth.

**Why do we need this mechanism to achieve the larger goal of having incremental/progressive layout?**

Hope this question is clear with above ;)

**Comment by goderbauer** [comment]
In isolation, the API this exposes doesn't make a lot of sense to me and it feels hacky.

If you chose to continue working on this PR, please also take another look at the flutter style guide, especially the sections around API documentation: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#documentation-dartdocs-javadocs-etc.

**Comment by dnfield** [comment]
I'm still not quite clear on why this is a solution that should live in the framework.

Tickers have no means of interrupting work more often. Tickers have no special knowledge of when vsync happens. This seems to introduce a number of problems that will be difficult for developers to reason about. I think this could be solved in a package instead. I'm going to close this for now but let's discuss more on discord if you like.

**Comment by fzyzcjy** [comment]
Thank you, I will reconsider the API and discuss on discord.

**Comment by fzyzcjy** [comment]
> I'm still not quite clear on why this is a solution that should live in the framework.
Tickers have no means of interrupting work more often. Tickers have no special knowledge of when vsync happens. This seems to introduce a number of problems that will be difficult for developers to reason about. I think this could be solved in a package instead. 

Totally agree. However, I cannot find out a method to let it live in a package while making flutter_smooth implementable. flutter_smooth need to support AnimationController and everything built on it (CircularProgressIndicator, SlideTransition, ...), so it seems impossible to create a 3rd party package. Otherwise, at least users cannot use *any* builtin widget such as CircularProgressIndicator and higher-level widgets, as long as a widget directly or indirectly depends on AnimationController/TickerProviderMixin. Users also cannot use most of the other 3rd party packages, because they use AnimationController/TickerProviderMixin as well.

> I'm going to close this for now but let's discuss more on discord if you like.

(Firstly reply here before discussing on Discord since I guess you are on weekends)

**Pull request closed without merging**
