### PR TITLE
Support targeting physical iOS devices on Apple Silicon 

### PR DESCRIPTION
**Pull request by jmagman**
## Description
Stable hotfix PR.
`flutter run` works against physical iOS and Android devices.  Also works from Xcode.

Does not work on:
- iOS simulators (missing engine architecture)
- iOS apps with plugins (https://github.com/CocoaPods/CocoaPods/issues/9907)
- Android emulators ([b/162290052](https://b.corp.google.com/issues/162290052) can't launch)

## Related Issues
https://github.com/flutter/flutter/issues/60118

Pull requests applied (with some merge conflicts resolved):
https://github.com/flutter/flutter/pull/65978
https://github.com/flutter/flutter/pull/67970
https://github.com/flutter/flutter/pull/68050
https://github.com/flutter/flutter/pull/68855

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by pcsosinski** [comment]
@jmagman should we move the target branch to flutter-1.22-candidate.12 for this?

**Comment by pcsosinski** [comment]
removing cp label in favor of https://github.com/flutter/flutter/issues/65133

**Comment by pcsosinski** [comment]
mis-close, sorry :|

**Review by christopherfujino — APPROVED** [review]
Thanks for opening this!

**Comment by christopherfujino** [comment]
Closing this as I squash-merged this branch into https://github.com/flutter/flutter/pull/70327. Thanks again for opening it!

**Pull request closed without merging**
