### PR TITLE
[H] Factor out BorderSide creation for dividers

### PR DESCRIPTION
**Pull request by Hixie**
This allows other code to get the same style without having to know exactly it is computed.

### CODE REVIEW

**Comment by Hixie** [comment]
cc @abarth

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
Thanks!

**Comment by Hixie** [comment]
Going to land on red because it looks like the failure is a flake, and I don't have my corp credentials with me to restart the bot. I'll revert if this fails in the same way.

**Pull request merged**
