### PR TITLE
Revert "Ensure the engineLayer is disposed when an OpacityLayer is disabled"

### PR DESCRIPTION
**Pull request by renyou**
Reverts flutter/flutter#94280

This causes some internal test failure: b/209109682

### CODE REVIEW

**Comment by renyou** [comment]
Sorry, created by mistake.

**Comment by renyou** [comment]
Actually this is the right one.

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
@renyou Please cc original authors (and potentially reviewers) on reverts.

/cc @ctrysbita @dnfield

**Comment by ctrysbita** [comment]
@goderbauer @dnfield Hmmm, how can we inspect the failure?

**Comment by goderbauer** [comment]
Unfortunately, it is internal code. I tried to create an open-source reproducible test case yesterday, but haven't been successful. I'll post it when I have one.

**Review by dnfield — COMMENTED** [review]
We should reland this. The "broken" scubas are actually wrong internally.

**Pull request merged**
