### PR TITLE
CircleAvatar with border issue#13566.

### PR DESCRIPTION
**Pull request by Faiizii**
## Description

*User can specify the stroke/border around the Circle Avatar. Also, the user can customize the border/stroke color while creating the Circle Avatar widget*

## Related Issues

*Add border to CircleAvatar (#13566) #18039*

## Tests

I added the following tests:

**

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by Hixie** [comment]
The comments in #13566 and #18039 seem like they still apply.

**Comment by Faiizii** [comment]
@Hixie  I have address the comments as you mentioned. As, the border and its color was already optional. Also, I removed the default border = 0.0 as it indicate the hairline. For the default color for border(if user will not specify the border color), I picked the **ThemeData.primaryColorLight** in case of light foreground colors and **ThemeData.primaryColorDark** in case of dark foreground color. These are the vice versa to default backgroundColor(So it may be clear to the end user in case of absence of backgroundColor and borderColor attributes).
As per chitgoks comment at last, I also think that why we need to add more widgets just to show the border. So customizing the widget is the clean solution. 
let me know if I need to fulfill anything else to approve the request.

**Comment by Hixie** [comment]
What I meant was that the CircleAvatar widget is implementing the Material spec's circle avatar concept, https://material.io/design/communication/imagery.html#informational-imagery which doesn't have borders or anything like that.

**Comment by Faiizii** [comment]
@Hixie Good morning. Material Component Team has added [ShapeableImageView](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/imageview/ShapeableImageView.java) in the response of [Feature Request](https://github.com/material-components/material-components-android/issues/780). The ShapeableImageView is defining the stroke and its color, although they did not update the related doc/guideline.

**Comment by Hixie** [comment]
@Faiizii My recommendation would be to file a bug first so that we can shake out what the Material team thinks we should support exactly (e.g. is it just shape-based clipping, is it border styes around that shape, is it coloured shadows or something else, etc).

**Comment by Piinks** [comment]
This PR has not been updated in a while, so I am going to close it for now. If you would like to continue working on this, feel free to re-open. Thank you!

**Pull request closed without merging**
