### PR TITLE
Ensure VmService instance is disposed after failed direct connection attempt

### PR DESCRIPTION
**Pull request by bkonyi**
_attemptServiceConnection in FallbackDiscovery would fail if the root
library URI was not a package URI even if the VM service connection
attempt was successful. This resulted in a VM service connection being
left alive, causing DDS to fail its connection to the VM service.

Updated _attemptServiceConnection to ensure the VM service instance is
disposed after a non-connection related failure and to allow for root
library URIs with a file scheme.

Fixes the failure described in https://github.com/flutter/flutter/pull/65873#issuecomment-694657423 (cc/ @liyuqian).

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

Fixes existing test

**Comment by jonahwilliams** [comment]
LGTM to land on red to fix build

**Comment by liyuqian** [comment]
@bkonyi : thanks for the quick fix! However, `flutter_gallery_sksl_warmup__transition_perf_e2e_ios32` is still failing after this PR with a different error as below. Do you have an iPhone 4s to test it locally?

```
2020-09-18T15:18:18.148876: run stdout: [+1826 ms] Service protocol connection closed.
2020-09-18T15:18:18.149260: run stdout: [        ] Lost connection to device.
2020-09-18T15:18:18.154159: run stdout: [   +3 ms] "flutter run" took 160,023ms.
2020-09-18T15:18:18.157205: run stdout: [   +4 ms] ensureAnalyticsSent: 0ms
2020-09-18T15:18:18.157932: run stdout: [        ] Running shutdown hooks
2020-09-18T15:18:18.158114: run stdout: [        ] Shutdown hook priority 4
2020-09-18T15:18:18.159052: run stdout: [        ] Shutdown hooks complete
2020-09-18T15:18:18.159783: stderr: [+33504 ms] Unhandled exception:
stderr: [        ] DriverError: Failed to fulfill RequestData due to remote error
2020-09-18T15:18:18.159959: stderr: [        ] Original error: JSON-RPC error -32000: Bad state: The client closed with pending request "ext.flutter.driver".
stderr: [        ] Original stack trace:
2020-09-18T15:18:18.160174: stderr: [        ] package:json_rpc_2/src/client.dart 123:62                       Client.sendRequest
stderr: [        ] package:json_rpc_2/src/peer.dart 98:15                          Peer.sendRequest
2020-09-18T15:18:18.160411: stderr: [        ] package:vm_service_client/src/scope.dart 64:23                  Scope.sendRequestRaw
stderr: [        ] package:vm_service_client/src/isolate.dart 361:19               VMIsolateRef.invokeExtension
2020-09-18T15:18:18.160573: stderr: [        ] package:flutter_driver/src/driver/vmservice_driver.dart 348:63  VMServiceFlutterDriver.sendCommand
stderr: [        ] package:flutter_driver/src/driver/driver.dart 503:45            FlutterDriver.requestData
2020-09-18T15:18:18.160726: stderr: [        ] package:e2e/e2e_driver.dart 73:42                               e2eDriver
2020-09-18T15:18:18.160868: stderr: [        ] ===== asynchronous gap ===========================
2020-09-18T15:18:18.162178: stderr: [        ] test_driver/transitions_perf_e2e_test.dart 7:24                 main
stderr: [        ] dart:isolate-patch/isolate_patch.dart 301:19                    _startIsolate.<fn>
stderr: [        ] dart:isolate-patch/isolate_patch.dart 168:12                    _RawReceivePortImpl._handleMessage
stderr: [        ] #0      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:359:7)
stderr: [        ] <asynchronous suspension>
stderr: [        ] #1      FlutterDriver.requestData (package:flutter_driver/src/driver/driver.dart:503:45)
stderr: [        ] #2      e2eDriver (package:e2e/e2e_driver.dart:73:42)
stderr: [        ] <asynchronous suspension>
stderr: [        ] #3      main (file:///Users/flutter/.cocoon/flutter/dev/integration_tests/flutter_gallery/test_driver/transitions_perf_e2e_test.dart:7:24)
stderr: [        ] #4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
2020-09-18T15:18:18.162387: run stdout: [   +2 ms] exiting with code 0
stderr: [        ] #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
2020-09-18T15:18:18.177430: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-09-18T15:18:18.197895: stdout: [  +35 ms] Leaving the application running.
2020-09-18T15:18:18.207181: stdout: [   +9 ms] "flutter drive" took 38,350ms.
2020-09-18T15:18:18.210885: stderr: [   +3 ms] Driver tests failed: 255
2020-09-18T15:18:18.211303: stderr: [        ] 
stderr:            #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
stderr:            #1      _runTests (package:flutter_tools/src/commands/drive.dart:530:5)
stderr:            <asynchronous suspension>
stderr:            #2      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:324:23)
stderr:            #3      _rootRunUnary (dart:async/zone.dart:1198:47)
stderr:            #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
stderr:            #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
stderr:            #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
stderr:            #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
stderr:            #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
stderr:            #9      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
stderr:            #10     _rootRun (dart:async/zone.dart:1190:13)
stderr:            #11     _CustomZone.run (dart:async/zone.dart:1093:19)
stderr:            #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
stderr:            #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
stderr:            #14     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
stderr:            #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
stderr:            #16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
stderr:            #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
stderr: 
stderr: 
2020-09-18T15:18:18.212539: stdout: [   +1 ms] ensureAnalyticsSent: 0ms
2020-09-18T15:18:18.213784: stdout: [   +1 ms] Running shutdown hooks
2020-09-18T15:18:18.213939: stdout: [        ] Shutdown hooks complete
2020-09-18T15:18:18.214358: stdout: [        ] exiting with code 255
2020-09-18T15:18:18.224387: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 255
2020-09-18T15:18:18.230813: Task failed: Executable "/Users/flutter/.cocoon/flutter/bin/flutter" failed with exit code 255.2020-09-18T15:18:18.231085: 
```

[flutter_gallery_sksl_warmup__transition_perf_e2e_ios32_e00b153_1.log](https://github.com/flutter/flutter/files/5248704/flutter_gallery_sksl_warmup__transition_perf_e2e_ios32_e00b153_1.log)

**Comment by bkonyi** [comment]
@liyuqian no, I don't have an iPhone 4S. I'm guessing this needs to run on a 32-bit device?

**Comment by jmagman** [comment]
Filed https://github.com/flutter/flutter/issues/66162, let's revert this.

**Comment by jmagman** [comment]
Although I guess another test will fail?

**Comment by zanderso** [comment]
The test that this was intended to fix is still failing, and has caused another test to fail, so I think this should be reverted.

**Comment by zanderso** [comment]
The revert didn't help. I have filed an infra ticket here: https://github.com/flutter/flutter/issues/66166

**Pull request merged**
