### PR TITLE
Revert "Mark new_gallery__crane_perf flaky"

### PR DESCRIPTION
**Pull request by dnfield**
Reverts flutter/flutter#79470

The file(s) now get written to the correct location(s).  See #79310 and related PRs

### CODE REVIEW

**Comment by jmagman** [comment]
LGTM once `linux_new_gallery__crane_perf` goes green on https://github.com/flutter/flutter/commit/d377c1baeda6b802be16efdf9ab770bbc8cabe9c

**Comment by dnfield** [comment]
I think it was actually related to the change int he gallery to use the writeTimelineToFile method instead of writeSummaryToFile. It's already yellow on a previous commit. But I will wait to merge.

**Comment by jmagman** [comment]
> It's already yellow on a previous commit.

Yellow just means "running", but I think that one actually failed, it just hasn't updated in the dashboard yet https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8851216457778440192/+/steps/run_new_gallery__crane_perf/0/stdout

**Comment by dnfield** [comment]
Ahh I was confused, it somehow looked like it said all steps completed and I thought yellow meant rerun. I see it now.

**Comment by jmagman** [comment]
It's running now: https://ci.chromium.org/p/flutter/builders/prod/Linux%20new_gallery__crane_perf/977

**Comment by dnfield** [comment]
It passed.

**Pull request merged**
