### PR TITLE
Move mouse_tracking.dart to rendering

### PR DESCRIPTION
**Pull request by dkwingsmt**
## Description

This PR moves `mouse_tracking.dart` from the `gestures` package to the `rendering` package. This is because `MouseTracker` does not really fit the definition for gestures, and its existence in `gestures` blocks some API design. More details can be found at [flutter.dev/go/move-mouse-tracker-to-rendering](https://docs.google.com/document/d/1dYNOTZ4kdq6ndNHopjUlrGlGBw3W-3jMbnoNJouIYtE/edit?usp=sharing).

## Related Issues

- One of the blocks to https://github.com/flutter/flutter/issues/33675
- Blocks https://github.com/flutter/flutter/issues/49568

## Tests

I added the following tests:

- No tests are added or changed.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [x] I wrote a design doc: [https://flutter.dev/go/move-mouse-tracker-to-rendering](https://docs.google.com/document/d/1dYNOTZ4kdq6ndNHopjUlrGlGBw3W-3jMbnoNJouIYtE/edit?usp=sharing).
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
Is this potentially breaking?

**Comment by chunhtai** [comment]
this is a breaking change

**Comment by dkwingsmt** [comment]
It does not break any code in g3 or flutter/tests, but I’ll take it as breaking.

**Review by gspencergoog — COMMENTED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
