### PR TITLE
Add Gradle Kotlin DSL support (#93238)

### PR DESCRIPTION
**Pull request by alexugthub**
These changes are in relation with a request from those who want to migrate from Groovy to Kotlin DSL. This can open the possibility to either allow developers to choose the DSL for Android projects or to have that as an implicit build setup.

This request is presented here https://github.com/flutter/flutter/issues/93238 and I tried to do my best to fulfil it,

It's just a few changes in **flutter_tools** and now I can build with both _.gradle_ and _.gradle.kts_ for Android.

Open to any suggestions or improvements

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/100442

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/100442

**Comment by christopherfujino** [comment]
@alexmro thanks for contributing! There are two things I would need before reviewing this PR:

1) fix existing tests that were broken by your change
2) add new tests, verifying the new feature (namely support for kotlin DSL)

Thanks!

**Comment by christopherfujino** [comment]
Thank you for contributing! As you have not responded within 3 weeks, I will be closing this PR as stale. If you are still interested in landing this, feel free to rebase this PR upstream, address code review feedback, and re-open this PR.

**Comment by MaiTheLord** [comment]
It seems that this isn't solved yet, could I take over and make my own PR?

**Pull request closed without merging**
