### PR TITLE
Remove explicit width in ListTile trailing element

### PR DESCRIPTION
**Pull request by tvolkert**
It was incorrectly added in #11858

### CODE REVIEW

**Comment by tvolkert** [comment]
FYI @zzzev

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
lgtm

**Comment by Hixie** [comment]
test!

**Comment by zzzev** [comment]
Sorry about the regression. My code was based on the existing code for leading elements, which still has the explicit width. I've removed that explicit width for consistency in this pending PR: https://github.com/flutter/flutter/pull/12253

**Pull request merged**
