### PR TITLE
Revert "Add and plumb `useImplicitPubspecResolution` across `flutter_tools`."

### PR DESCRIPTION
**Pull request by polina-c**
Reverts flutter/flutter#157879 to unblock flutter roll.

Prerequisite reverts:
https://github.com/flutter/flutter/pull/157934

Reason: b/377107864

### CODE REVIEW

**Review by nate-thegrate — APPROVED** [review]
Approving for [same reason as before](https://github.com/flutter/flutter/pull/158078#pullrequestreview-2411896134) :)

**Comment by matanlurey** [comment]
> Approving for [same reason as before](https://github.com/flutter/flutter/pull/158078#pullrequestreview-2411896134) :)

I don't agree with this. It's a weekend, the pull request landed 4 days ago, and the reason for the internal regression is our internal test infrastructure was not working.

The work being reverted is a priority project that requires lots of coordination and should not have been reverted on a weekend without another Googler reviewing it. Let's talk about this Monday.

@johnmccutchan @jtmcdole for visibility, these reverts will probably cost me 1-2 days worth of work relanding that would have been completely trivial to fix in google3.

**Comment by nate-thegrate** [comment]
Oh shoot, I apologize, thank you for letting me know.

**Comment by nate-thegrate** [comment]
> Regressions should be reverted first and questions asked later.

From now on, I'll work with the understanding that this only pertains to while the "revert" label can be applied.

This should have been obvious, given that the bot will automatically approve the revert PR during this period but requires a review otherwise.

**Pull request merged**
