### PR TITLE
include exception details in tool exit displayed when adb call fails

### LINKED ISSUE #125971: Include more information about adb failure in `flutter daemon` exit messages
There have been some reports of the `flutter daemon` command (which IDEs use to maintain a list of available devices) crashing after some period of time (this was the cause of both https://github.com/Dart-Code/Dart-Code/issues/4510, https://github.com/Dart-Code/Dart-Code/issues/4475).

In a log provided by @guidezpl, there is this:

```
[9:46:07 PM] [FlutterDaemon] [Info] <== [{"event":"daemon.logMessage","params":{"level":"error","message":"Unable to run \"adb\", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: /Users/plg/Library/Android/sdk/platform-tools/adb"}}]
[9:46:07 PM] [FlutterDaemon] [Info] Process /Users/plg/Developer/flutter-dev/bin/flutter terminated! 1, null
```

The daemon sent this error message and then terminated with an exit code of 1. The origin of this message is here:

https://github.com/flutter/flutter/blob/bea17cc9690185ea00d3765203ba52ba74d6e415/packages/flutter_tools/lib/src/android/android_device_discovery.dart#L74-L79

It's not clear why this error is occurring, but it would be useful to expand the error message to include additional information that might help. For example, the exception `message`, `exitCode` and the stackTrace might help a) understand what this failure actually was, and b) what the code was actually running `adb` for.

@christopherfujino

### PR DESCRIPTION
**Pull request by andrewkolos**
Fixes #125971 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

### CODE REVIEW

**Comment by andrewkolos** [comment]
In #125971, @DanTup proposes (as an example) including the stack trace, but I feel like this would be pretty noisy to include in a tool exit message. Perhaps we could include the stack trace in a `printTrace` call, but I am not sure that would appear in the flutter daemon log output surfaced by VS Code. @DanTup, do you know if `printTrace` output would appear in these logs (i.e. does Dart-Code invoke `flutter daemon` with the `-v` flag)?

**Comment by DanTup** [comment]
> i.e. does Dart-Code invoke `flutter daemon` with the `-v` flag?

It doesn't currently. We could change it, but it does mean there would generally be a lot more output (in normal operation when there are no errors) being sent over to the IDEs to be read/ignored.

Is there a way we could include the stack trace info in the call to `throwToolExit` that could be handled by the daemon mode and always printed? (`flutter daemon` is only intended for IDEs, so having error messages be verbose even without `-v` could be helpful).

**Comment by andrewkolos** [comment]
> > i.e. does Dart-Code invoke `flutter daemon` with the `-v` flag?
> 
> It doesn't currently. We could change it, but it does mean there would generally be a lot more output (in normal operation when there are no errors) being sent over to the IDEs to be read/ignored.

Makes sense.

> Is there a way we could include the stack trace info in the call to `throwToolExit` that could be handled by the daemon mode and always printed? (`flutter daemon` is only intended for IDEs, so having error messages be verbose even without `-v` could be helpful).

I think we could augment this conditional (excerpted from the code that handles `ToolExit`s) https://github.com/flutter/flutter/blob/be0eb721d5a0668a32878a16da7a699a8998b7c4/packages/flutter_tools/lib/runner.dart#L176-L178

We could change `if (verbose)` to `if (verbose || args.first == 'daemon')` (in an actual implementation, I would try avoid the hard-coded dependency on the name of the command, but I'm keeping this simple). I'm pretty neutral on this since it's not clear how often this will be useful, but I'm down to implement this while I'm here. Any disagreement here, @christopherfujino?

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by andrewkolos** [comment]
> I'm pretty neutral on this since it's not clear how often this will be useful, but I'm down to implement this while I'm here. Any disagreement here, @christopherfujino?

@christopherfujino 😛

**Comment by andrewkolos** [comment]
> > I'm pretty neutral on this since it's not clear how often this will be useful, but I'm down to implement this while I'm here. Any disagreement here, @christopherfujino?
> 
> @christopherfujino 😛

I'm also fine to just merge this as is since this isn't high priority. If you agree, feel free to reapprove

**Review by christopherfujino — APPROVED** [review]

**Pull request merged**
