### PR TITLE
Updates the package dependencies by running flutter update-packages --force-upgrade

### PR DESCRIPTION
**Pull request by gspencergoog**
This simply updates the package dependencies by running `flutter update-packages --force-upgrade`.

I'm doing this with no other changes, because the last time I tried that, redness occurred.  I want to isolate the problem to a "clean" update of the packages.

### CODE REVIEW

**Comment by gspencergoog** [comment]
OK, it looks like the plugins device_info, connectivity, and url_launcher haven't yet had their gradle configurations updated, so they fail when trying to build with the new gradle.  I reverted the upgrade for those three packages only (in flutter_gallery) until we are ready to fix them (fixing them for master will break them for alpha users, so we need to do an alpha roll to do that).

**Comment by Hixie** [comment]
RSLGTM

**Comment by Hixie** [comment]
For future reference, when pinning a dependency, you should update update_packages.dart's pin map, rather than doing it by hand.

**Comment by zoechi** [comment]
Curious why you don't just commit `pubspec.lock` instead of maintaining transitive dependency versions in `pubspec.yaml` manually

**Comment by Hixie** [comment]
@zoechi Well we can't do that for the flutter package, since packages don't have .lock files, only applications do. But see https://github.com/flutter/flutter/issues/13428 about doing it for the applications that we ship.

**Pull request merged**
