### PR TITLE
Load assets in flutter_test without turning event loop.

### PR DESCRIPTION
**Pull request by dnfield**
This makes it possible to load an asset without actually turning the event loop. This is importnat because our FakeAsync zones may cause people to sprinkle in extra pumpAndSettles in when running tests that load assets, which is undesirable.

While I was here I noticed some unnecessary dynamic usage in SynchronousFuture.

### CODE REVIEW

**Comment by dnfield** [comment]
I came across this because I'm working on rolling a new version of flutter_svg into Google's monorepo. Tests in there that previously worked because of google-specific magic now are missing assets because the rewrite assumes you can do this kind of thing synchronously in a test. 

I'd like to get rid of all flutter_svg specific magic from test harnesses if possible.

**Review by jonahwilliams — APPROVED** [review]
LGTM (but not to CI)

**Comment by jonahwilliams** [comment]
I think if we can stick this change, i can delete the fake asset manager entirely and use the real one. Will need to experiment on my own

**Review by pdblasi-google — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
hah, I was wondering if that `!` was safe and now know it wasn't. Cool. I'll fix it.

**Pull request merged**
