### PR TITLE
Added textInputAction parameter to TextFormField.

### PR DESCRIPTION
**Pull request by matthew-carroll**
Added textInputAction parameter to TextFormField that forwards to TextField, added onEditingComplete parameter to TextField that forwards to EditableText, added onEditingComplete parameter to TextFormField that forwards to TextField.

#19397

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by MasseElch** [comment]
Can anyone say when this will be merged? This week? Month? I need this :+1:

**Comment by matthew-carroll** [comment]
@MasseElch it will be merged as soon as the Flutter build is fixed.  Maybe a day.  Maybe a few days.

**Pull request merged**
