### PR TITLE
Fix refresh cancelation

### LINKED ISSUE #138848: `RefreshIndicator` can end up canceled if the touch point moves upward by even one pixel on touch-up
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

When using `RefreshIndicator`, when you release the touch point, sometimes the point jumps upwards a tiny bit (either through inadvertent movement from the user, or because as the finger comes up off the screen, the centroid of the touch point moves upwards slightly).

If the touch point moves even one pixel upwards (back away from the point of maximum drag, when the refresh indicator is "armed"), `RefreshIndicator` cancels the drag.

This can make it maddeningly difficult to actually initiate a refresh, because half the time when you lift your finger, the touch point is canceled, even if it was previously armed.

This is the culprit code, in `refresh_indicator.dart`:

image

These numbers are 0.0, but should be greater than zero.

Setting both numbers to 20.0 mostly solves the "bounce-back and cancel" problem, but then the behavior feels a bit weird, because the spinner doesn't move at all for 20 pixels of vertical movement upwards, and yet the scrollview still refreshes on release.

I would actually prefer that the overscroll distance, beyond the "armed" point, be the distance that you can scroll back upwards by, before the drag is canceled. In other words, if `displacement` is 100, and you drag down 130 pixels, then you can drag back up by 30 pixels before the drag is canceled.

There's another issue here too: sometimes when releasing a drag, even using the emulator, with the mouse held perfectly still, you get not only bounce-back and cancel (with zero movement!), but also the scroll indicator bouncing back *causes the scrollview to scroll back as well*. It's almost like the drag controller of `RefreshIndicator` starts sending scroll events to the scrollview's scroll controller.

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel beta, 3.17.0-0.0.pre, on Fedora Linux 38 (Workstation Edition) 6.5.10-200.fc38.x86_64, locale en_US.utf8)
    • Flutter version 3.17.0-0.0.pre on channel beta at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0b591f2c82 (3 weeks ago), 2023-11-02 22:01:10 -0400
    • Engine revision dff66925dc
    • Dart version 3.3.0 (build 3.3.0-91.0.dev)
    • DevTools version 2.29.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/luke/Android/Sdk
    • Platform android-UpsideDownCake, build-tools 33.0.1
    • Java binary at: /opt/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 16.0.6 (Fedora 16.0.6-3.fc38)
    • cmake version 3.27.7
    • ninja version 1.11.1
    • pkg-config version 1.8.0

[✓] Android Studio (version 2022.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 73.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.77.20231101

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Linux (desktop)            • linux         • linux-x64      • Fedora Linux 38 (Workstation Edition) 6.5.10-200.fc38.x86_64
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by lukehutch**
Changes drag release logic so that an armed refresh is only canceled if the user has scrolled back up beyond the point where the refresh indicator was armed. (Fixes #138848.)

This is the minimal change I found could be made to restore something like the behavior that I would expect.

This may still need a bit of work, because it only masks the second issue I mentioned, that releasing a drag can cause the scroll position to be animated back up from the release point. There is actually a bug about that: #6052. I would like to see that bug fixed too. This PR doesn't address that, but makes it harder to hit that issue.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by lukehutch** [comment]
I honestly have no idea how to write a test for this... @Hixie 
(It's a very straightforward fix though, and can be manually tested...)

**Review by Piinks — COMMENTED** [review]
Hi @lukehutch welcome, thank you for contributing! 
It looks like there are a bunch of failing tests here, can you take a look?
This will also need a new test to verify it works as expected, as well as prevent us from undoing it in the future. Thanks!

**Comment by lukehutch** [comment]
@Piinks sorry, I didn't notice the failing tests...

Flutter's git main branch doesn't even build out of the box -- I get these errors:

```console
Resolving dependencies...
Note: web is pinned to version 0.3.0 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of flutter_test from sdk depends on web 0.3.0 and manual_tests depends on web 0.4.0, flutter_test from sdk is forbidden.
So, because manual_tests depends on flutter_test from sdk, version solving failed.
exit code 1
```

I think this is triggering a lot of the test failures. I'll try tinkering with this and see if I can get it working.

As far as writing a test for this, I have absolutely no idea how to do that for a Flutter widget, but I'll try to find examples in the existing tests.

**Comment by lukehutch** [comment]
Closing in favor of #139535 -- sorry, I have been battling with a git issue, and it's just easier to submit a new PR.

**Pull request closed without merging**
