### PR TITLE
[native_assets][tool] `template=package_ffi` Cpp integration

### LINKED ISSUE #151646: [native_assets] `package_ffi` template language options
`flutter create --template package_ffi my_package` creates a template detailing how to compile C code.

We should consider adding a `--language` option with `c`, `cpp`, `objective-c`, `swift`, `rust`, and `go`.

* [ ] `cpp` should be almost identical to `c`, but have a cpp file and use `extern "c"` and set the language in the hook.
* [ ] Objective-C ditto.
* [ ] Swift might need some extra steps. @liamappelbe 
* [ ] Rust can use [cbindgen](https://github.com/dart-lang/native/blob/rust-example/pkgs/native_assets_cli/example/use_rust/rust/build.rs) and [native_toolchain_rust](https://github.com/irondash/native_toolchain_rust)
* [ ] Go can use [native_toolchain_go](https://github.com/csnewman/flutter-go-bridge/tree/master/native_toolchain_go)

This would slightly ease exploring native interop with the various languages.

(Side note, we should also figure out how to share templates between `flutter create` and `dart create`. As these templates are not flutter specific.)

### PR DESCRIPTION
**Pull request by Buchimi**
This PR adds support for new languages when creating an FFI package in flutter using flutter create --template package_ffi my_package

Specifically, I have added support for C++

This is the first CL intended to fix https://github.com/flutter/flutter/issues/151646. It is smaller in scope as it is missing rust and Go implementations

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

### CODE REVIEW

**Comment by andrewkolos** [comment]
Per the ci.yaml check validation, you'll need to update this branch for checks to run. If this is not yet ready for review, please mark it as a draft. Otherwise, once checks run, I'll consider this ready for review.

**Comment by andrewkolos** [comment]
Is this change under test? In my opinion, the behavior here needs integration tests to make sure the build process works here.

**Comment by dcharkes** [comment]
> ci.yaml validation 

Is red so the rest of the tests is not running.

**Comment by Buchimi** [comment]
> Is this change under test? In my opinion, the behavior here needs integration tests to make sure the build process works here.

I wrote tests in ```packages/flutter_tools/test/commands.shard/hermetic/create_usage_test.dart```

**Comment by Buchimi** [comment]
I may need to edit the custom dimension class in `packages/flutter_tools/lib/src/reporting/custom_dimensions.dart` to report what language is being used during package creation. Do you think this is a good idea @dcharkes ?
This will also be useful for adding more tests.

**Comment by dcharkes** [comment]
> I may need to edit the custom dimension class in `packages/flutter_tools/lib/src/reporting/custom_dimensions.dart` to report what language is being used during package creation. Do you think this is a good idea @dcharkes ? This will also be useful for adding more tests.

I do not know about this "backend". Maybe @andrewkolos or @christopherfujino does. I don't think it's necessarily, from the comment I'm inferring it's reporting analytics, and I'm fine with not knowing which language you're using in this template.

**Comment by christopherfujino** [comment]
> I do not know about this "backend". Maybe @andrewkolos or @christopherfujino does. I don't think it's necessarily, from the comment I'm inferring it's reporting analytics, and I'm fine with not knowing which language you're using in this template.

Yes, the `CustomDimensions` class is for reporting analytics, and I don't think we need to change that.

**Comment by Buchimi** [comment]
Hey, so I have no idea on how to fix the build issues

**Comment by dcharkes** [comment]
It looks like the build failures are analysis failure and

```
            Because test >=1.16.6 <1.25.5 depends on web_socket_channel ^2.0.0 and every version of link_hook from path depends on web_socket_channel 3.0.1, test >=1.16.6 <1.25.5 is incompatible with link_hook from path.
            So, because package_with_native_assets depends on both link_hook from path and test 1.24.9, version solving failed.
```

These latter failures might be because we rolled some dependencies forward in the meantime?

**Comment by goderbauer** [comment]
(triage) Hey @Buchimi, do you still have plans for this PR to get it into a reviewable state?

**Comment by Buchimi** [comment]
@goderbauer No, I have other commitments (school), so I can't pay attention to this PR for a while.

**Pull request closed without merging**
