### PR TITLE
Reland "Reland - Introduce tone-based surfaces and accent color add-ons - Part 2"

### PR DESCRIPTION
**Pull request by QuncCccccc**
Reverts flutter/flutter#144262

The Golden diffs have been approved before, it should be safe to land this change now:)

### CODE REVIEW

**Comment by Piinks** [comment]
Can you push another commit without a force push so I can double check the goldens?

**Comment by QuncCccccc** [comment]
> Can you push another commit without a force push so I can double check the goldens?

Yes! Just pushed some empty commits. Since there was a conflict, so after I solved it, pushed another one.

**Comment by Piinks** [comment]
Ah thanks! Looks like Gold is good here, is the Google testing failure expected?

**Comment by QuncCccccc** [comment]
> Ah thanks! Looks like Gold is good here, is the Google testing failure expected?

Yes! Google testing failures are expected:)

**Review by Piinks — CHANGES_REQUESTED** [review]
LGTM!

**Comment by Piinks** [comment]
Oh weird, the github UI glitched when I submitted.

**Review by Piinks — APPROVED** [review]

**Comment by QuncCccccc** [comment]
> LGTM!

Thanks!

**Comment by Hixie** [comment]
This caused an application I'm working on to change color, from:

bright purple

...to:

desaturated purple

...and I can't figure out what value to pass to `ColorScheme.fromSeed` to get the old colors.

Was that intentional?

**Comment by DavidChZh** [comment]
I have some questions about the ColorScheme upgrade. 
In the latest version, I saw that background and onBackground were removed. In my project, I use it to define the background color of the page or card, without using surface and onSurface. Because onSurface is used in the system's built-in long-press popup option.
There are some other similar situations, but not many. For such situations, I generally avoid using this attribute.
In the latest version, background and onBackground have been removed. For me, I can only use surface and onSurface, but onSurface is occupied by the system. Do you have any good suggestions for this problem?

**Comment by QuncCccccc** [comment]
> I have some questions about the ColorScheme upgrade. In the latest version, I saw that background and onBackground were removed. In my project, I use it to define the background color of the page or card, without using surface and onSurface. Because onSurface is used in the system's built-in long-press popup option. There are some other similar situations, but not many. For such situations, I generally avoid using this attribute. In the latest version, background and onBackground have been removed. For me, I can only use surface and onSurface, but onSurface is occupied by the system. Do you have any good suggestions for this problem?

Hi! We can add color roles by using `ThemeExtension`! Here's an example showing how we can add more colors in theme:)

**Comment by DavidChZh** [comment]
> > I have some questions about the ColorScheme upgrade. In the latest version, I saw that background and onBackground were removed. In my project, I use it to define the background color of the page or card, without using surface and onSurface. Because onSurface is used in the system's built-in long-press popup option. There are some other similar situations, but not many. For such situations, I generally avoid using this attribute. In the latest version, background and onBackground have been removed. For me, I can only use surface and onSurface, but onSurface is occupied by the system. Do you have any good suggestions for this problem?
> 
> Hi! We can add color roles by using `ThemeExtension`! Here's an example showing how we can add more colors in theme:)

Great, thank you very much!

**Pull request merged**
