### PR TITLE
(insert|move|remove)ChildRenderObject Deprecation: Step 1

### PR DESCRIPTION
**Pull request by tvolkert**
## Description

This deprecates the following methods:

* RenderObjectElement.insertChildRenderObject
* RenderObjectElement.moveChildRenderObject
* RenderObjectElement.removeChildRenderObject

... and replaces them with the following methods:

* RenderObjectElement.insertRenderObjectChild
* RenderObjectElement.moveRenderObjectChild
* RenderObjectElement.removeRenderObjectChild

The reason for the deprecation is to provide the `oldSlot` argument to
the `moveRenderObjectChild` method (such an argument was missing from
the now-deprecated `moveChildRenderObject` method) and the `slot`
argument to the `removeRenderObjectChild` method (such an argument was
missing from the now-deprecated `removeChildRenderObject` method). While
no argument was added to `insertRenderObjectChild`, the name change (and
corresponding deprecation) was made to maintain naming parity with the
other two methods.

This initial step does not update or remove any of the `slotToChild`
patterns that exist in the framework. This work is being separated
into two commits in case something needs to be reverted to minimize
the scope of each commit.

## Related Issues

See https://github.com/flutter/flutter/issues/63269 for more info

## Tests

I added the following tests:

* Verify the correct slots are passed to the methods
* Verify that the new methods delegate to the old methods in the base class
* Verify that an assertion error is thrown that informs the developer of the deprecation if old methods are ever invoked

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

### CODE REVIEW

**Review by Hixie — APPROVED** [review]
LGTM

**Review by goderbauer — APPROVED** [review]
LGTM once all checks pass.

**Comment by mehmetf** [comment]
This is a breaking change. Internal chart library compilation is failing with:

```
  This method overrides a method annotated as '@mustCallSuper' in 'RenderObjectElement', but doesn't invoke the overridden method. #must_call_super
```

We need to soft land this internally and come up with a breaking change document.

**Comment by tvolkert** [comment]
Soft land step is cl/327627478, and re-application of this PR is https://github.com/flutter/flutter/pull/64254

**Comment by goderbauer** [comment]
Technically, because of the google3 breakage this is a breaking change now per https://github.com/flutter/flutter/wiki/Tree-hygiene#1-determine-if-your-change-is-a-breaking-change.

Maybe we should publish a quick migration guide for it on https://flutter.dev/docs/release/breaking-changes.

**Pull request merged**
