### PR TITLE
Tests for `flutter test [some_directory]`

### PR DESCRIPTION
**Pull request by DaveShuckerow**
Adding test coverage to be sure we can test a directory's contents instead of just its children.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by jonahwilliams** [comment]
Please ignore the codecov bot. It is correct, but still a little strict.

**Comment by tvolkert** [comment]
FYI: https://github.com/flutter/flutter/wiki/Tree-hygiene#squashing-commits

The commit message for this commit contains:

"""
* Add a test for a directory instead of a single test.

* Add test data to a child directory to test the command.

* Add test data to a child directory to test the command.

* Add test data to a child directory to test the command.

* Correct test.
"""

**Comment by DaveShuckerow** [comment]
Thanks Todd, I will keep this in mind going forward.

**Pull request merged**
