### PR TITLE
gradlew/gradlew.bat should not be gitignored according to official doc

### LINKED ISSUE #109749: gradlew/gradlew.bat should not be gitignored according to official doc
## Steps to Reproduce

According to https://docs.gradle.org/current/userguide/gradle_wrapper.html

> To make the Wrapper files available to other developers and execution environments you’ll need to check them into version control. All Wrapper files including the JAR file are very small in size. Adding the JAR file to version control is expected. 

So the gitignore seems to need some modification.

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 
n/a

**Actual results:** 
n/a

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
latest version, no error
```

</details>

### PR DESCRIPTION
**Pull request by fzyzcjy**
Close https://github.com/flutter/flutter/issues/109749

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jonahwilliams** [comment]
This is the repo's gitignore, not a template file gitignore.

**Comment by fzyzcjy** [comment]
I know. The problem is, maybe flutter repo itself also need to follow gradle's official suggestion?

**Comment by jonahwilliams** [comment]
We've done this historically because the tool can handle re-generating this and to avoid churn in the repo when the contents of this file changes.

**Comment by jonahwilliams** [comment]
I'm going to close this PR, as we don't intend to accept this change. If something changes we can always reconsider

**Comment by fzyzcjy** [comment]
I see. Thanks all the same

**Pull request closed without merging**
