### PR TITLE
Revert "Hide text selection toolbar when dragging handles on mobile"

### PR DESCRIPTION
**Pull request by zanderso**
Reverts flutter/flutter#104274

Analysis failures on CI: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20analyze/7624/overview

### CODE REVIEW

**Review by gaaclarke — APPROVED** [review]
lgtm

**Comment by zanderso** [comment]
@markusaksli-nc

**Comment by zanderso** [comment]
@justinmc

**Comment by justinmc** [comment]
@markusaksli-nc Looks like it was just that the curly brace lint rule was added at the same time as your PR.  Can you re-revert with that change?

**Pull request merged**
