### PR TITLE
Support materializing Flutter module host app on iOS

### PR DESCRIPTION
**Pull request by mravn-google**
WIP, not ready for review.

### CODE REVIEW

**Comment by mravn** [comment]
I'll carry this PR forward asap.

**Comment by mravn** [comment]
CLA signed.

**Comment by mravn** [comment]
FYI @matthew-carroll 

Added support for materializing Flutter module projects on iOS. Currently, the materialized host app is in Objective-C only and uses CocoaPods, even if there are no plugins. Plan:

- [ ] expand the module_test_ios device lab test to prove that we can add to an existing iOS host app
- [ ] support materializing Swift and Kotlin host apps
- [ ] decide whether we want to avoid the use of CocoaPods in the materialized iOS host app, and if so, how to help the user add Flutter plugins to that app later on

**Comment by mravn** [comment]
@dnfield @matthew-carroll This PR avoids the use of CocoaPods in the _ephemeral_ host app. Not sure if that is what you meant by "initial project structure"?

Avoiding CocoaPods also when _materializing_ an iOS host app comes with a usability cost: If you happen to materialize your iOS host app before adding Flutter plugins (and CocoaPods to support them), then we are not in a good position to automatically fix it later, if/when you realize that your app does need plugins.

The materialized host app is controlled by the app author and could be (almost) arbitrarily modified beyond the control and aid of Flutter tooling. So adding the plugin+CocoaPods setup later would in general be a manual step.

Options, as I see them:
* Accept that a materialized host app always involves CocoaPods, then work to push the threshold at which materialization is needed for simple, all-Flutter apps (e.g. by supporting more iOS-specific configuration in the pubspec.yaml file).
* Don't accept that a materialized host app without plugins involves CocoaPods, then work towards making the manual steps needed to add plugins and CocoaPods later as simple as possible (e.g. by making the project setups identical, as far as possible, but for the need to invoke `pod install`).

**Comment by matthew-carroll** [comment]
@mravn You're right, I totally spoke too soon.  I was thinking of the ephemeral project.

@dnfield when we make a host app editable (AKA materialize), we actually want to automatically add CocoaPods because we won't get another opportunity to do so.

**Comment by dnfield** [comment]
@mravn it looks like this code is checking for whether it should be using `.ios` or `ios`, which is good.

Am I missing something here where the `.ios` folder would actually get created, or is that still to be done?

**Comment by dnfield** [comment]
That sounds good, I have a couple other areas around this I'm working through as well.  If it's not looking good to you for this week please let me know so I can reprioritize - and thanks!

**Comment by matthew-carroll** [comment]
@mravn we're going to rename "materialize" to "make-host-app-editable" - should we wait until after this PR lands to do that?  Would that save us some conflicts?  Or should I take care of that ASAP?

**Comment by mravn** [comment]
I don't think it matters that much to my PR. I'll just rebase and sort it out. But don't rush the change for my sake.

**Comment by dnfield** [comment]
@mravn is this ready for review?

We'd like to get the functionality for this landed ASAP to unblock another effort on the ios/android materialization workflow.

**Comment by mravn** [comment]
@dnfield Sorry, I've been busy. The PR is close to ready. I'm having trouble getting code signing/provisioning to work on the ios_host_app used by the module_test_ios devicelab test I've added. I may need some help with that. Otherwise we can remove that part of module_test_ios for now.

I cannot edit the title of this PR to remove the WIP prefix, nor can I remove the cla:no label.

**Comment by dnfield** [comment]
Overriding CLA status because it's due to confusion over a closed/unlinked account.

@mravn can you go ahead and just disable the offending test for now, we can land this, and someone can pick up the test where you left off with it?  That should unblock @matthew-carroll

**Comment by mravn** [comment]
Done. The cla:no label came back though.

**Comment by dnfield** [comment]
This LGTM, but can you confirm this is ready (modulo the desire for eventually fixing that test)?

**Comment by mravn** [comment]
I'll test the functionality to be covered by the missing test tonight, manually. I'll keep you posted.

**Comment by mravn** [comment]
With Flutter module project, ephemeral/non-editable host app:

- [x] `flutter run` works for Simulator
- [x] `flutter run` works for device
- [x] `flutter run` works for Simulator, with plugin
- [x] `flutter run` works for device, with plugin

With Flutter module project, editable host app:

- [x] `flutter run` works for Simulator
- [x] `flutter run` works for device
- [x] `flutter run` works for Simulator, with plugin
- [x] `flutter run` works for device, with plugin

**Comment by mravn** [comment]
Whoa! Wasn't done checking the add2app case, and found a problem. See https://github.com/flutter/flutter/pull/22277.

**Pull request merged**
