### PR TITLE
Add the refresh rate fields to perf_test

### LINKED ISSUE #99516: How to make the fields in `TimelineSummary` being collected by skia
I added some new fields in `TimelineSummary` in this PR: https://github.com/flutter/flutter/pull/95699
Including: '30hz_frame_percentage',  '60hz_frame_percentage', '90hz_frame_percentage',  '120hz_frame_percentage', 'illegal_refresh_rate_frame_count'. 

These fields are not shown in the skia perf tool: https://flutter-flutter-perf.skia.org/e/

I have run the local tests and confirmed that the timeline summary file was generated and it contains the new key-values.

Is there anything that I'm missing for these new fields to be collected by Skia?

CC @keyonghan 

@dnfield @flar I heard you two might know how to do it :) 

This is blocking https://github.com/flutter/flutter/issues/95700

### PR DESCRIPTION
**Pull request by cyanglaz**
This PR adds the refresh rate benchmark fields to perf_test. This PR also adds 80Hz as a new valid fresh rate, this is because [iOS promotion display supports 80Hz] (https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro?language=objc)

Fixes https://github.com/flutter/flutter/issues/99516

If after landing this we can verity that these values are tracked in the benchmark, we can create a new PR to track all the lower refresh rates that supported by promotion display before closing https://github.com/flutter/flutter/issues/95700

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by cyanglaz** [comment]
@dnfield Tested locally that the output contains the new fields. Prob also need your help with how to grab those values from LUCI after landing this.

**Comment by cyanglaz** [comment]
cc @iskakaushik

**Review by dnfield — APPROVED** [review]

**Comment by cyanglaz** [comment]
@dnfield Looks like it was reverted due to some failure see: https://github.com/flutter/flutter/pull/99801

What am I missing?

**Comment by dnfield** [comment]
You can only include fields if they are actually reported. This patch as landed included fields that are nto always reported.

Your option is to either remove the key if it is not reported, or make sure to always report it with some default value (i.e. 0).

**Comment by cyanglaz** [comment]
> make sure to always report it with some default value

Ah, thanks. Do you mean I need to do something like this? https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/perf_tests.dart#L930

**Comment by dnfield** [comment]
Yes, exactly

**Pull request merged**
