### PR TITLE
Revert tool change

### PR DESCRIPTION
**Pull request by jmagman**
Reverts https://github.com/flutter/flutter/pull/74444
Reverts the hot reload help part of https://github.com/flutter/flutter/pull/74513

### CODE REVIEW

**Review by jonahwilliams — CHANGES_REQUESTED** [review]
//

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Review by christopherfujino — CHANGES_REQUESTED** [review]
should be merged into the candidate branch

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
