### PR TITLE
Add tiles_scroll_perf test

### PR DESCRIPTION
**Pull request by liyuqian**

### CODE REVIEW

**Comment by liyuqian** [comment]
@yjbanov : is this enough to have our dashboard to also track `tiles_scroll_perf.timeline_summary.json` inside `dev/benchmarks/complex_layou/build`?

**Comment by yjbanov** [comment]
Looks like it. LGTM.

**Review by yjbanov — APPROVED** [review]

**Comment by yjbanov** [comment]
lgtm

**Comment by yjbanov** [comment]
Ah yeah, it needs to be added to `manifest.yaml` for the devicelab to actually run it :smile: However, this PR is enough for the metrics to make it into the benchmarks dashboard once it's running.

**Pull request merged**
