### PR TITLE
Expose InputDecoration to customize TextField in SearchDelegate

### PR DESCRIPTION
**Pull request by mirkancal**
## Description

This PR adds ability to override InputDecoration for the SearchDelegate's TextField. This way it provides customization.

## Related Issues

https://github.com/flutter/flutter/issues/45498
https://github.com/flutter/flutter/issues/34127 (Only the hintText part)

## Tests

I added the following tests:

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by shihaohong** [comment]
This change seems to be failing multiple presubmit tests. Could you please fix the ones related to your PR first? 

At a high level, it seems like the analyzer is failing (Run `flutter analyze` to see where these issues are). Also, it seems that the fallback given that `InputDecoration` is not provided to `SearchDelegate` is not properly defined, which is causing some other tests to fail.

**Comment by shihaohong** [comment]
You will also need tests to go with your PR

**Comment by mirkancal** [comment]
Thanks! I'll add the tests.

**Comment by shihaohong** [comment]
Hi @mirkancal, any luck with the tests? Let me know if you're running into issues and I'll try to help out!

**Comment by shihaohong** [comment]
Hey @mirkancal I'm going to close this PR until there is progress. Feel free to re-open it once you've had some time to work on it, thank you! :)

**Comment by tapizquent** [comment]
Has there been any progress with this? It is really annoying indeed that there is no way to modify the looks of the textfield inside SearchDelegate. Properties like the background color, textColor and shape of the textfield should be allowed.

**Pull request closed without merging**
