### PR TITLE
No test core

### PR DESCRIPTION
**Pull request by dnfield**
Reverts:

- 57e134058fd25ec4d7f1a46265c495a0cb89e67c (https://github.com/flutter/flutter/pull/72699) 
- 87746c767408e3936093f338f9427e9b3ae4bfa7 (https://github.com/flutter/flutter/pull/70513)

These were related to introducing a dependency on test_core that we can't have in user-facing packages in this repo. We will have to come up with another way to deal with the reporter related issues - whether moving this functionality into flutter_tools, or potentially updating the platform specific plugin code to help handle test running and reporting for FTL.

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Failures are because the create template revert wasn't included, AFAICT. Merging up to head and trying again.

**Review by jonahwilliams — APPROVED** [review]
Still LGTM

**Review by jiahaog — APPROVED** [review]
I've been looking at modifying the tool to support integration tests, and it does appear that if we add support into `FlutterTestPlatform` for integration tests, `directRunTests` might not be needed. (At least, for the `drive` mechanism of running tests. Running the tests with XCTest or FTL will still need something like this)

**Comment by dnfield** [comment]
This should be safe to roll in once cl/352098861 lands.

**Pull request merged**
