### PR TITLE
URL encode asset paths to support reserved characters in paths

### LINKED ISSUE #14864: Flutter quits immediately at startup when adding assets with square brackets in the filename
As soon as I added this last `asset` line Flutter seems to just silently quit at startup (see debug console).

screen shot 2018-02-24 at 21 52 26

I repro'd with a file named `a[a.ch8` but it worked fine with spaces, commas, etc.

I tried putting quotes around it, but still did the same.

Running on Mac OS X, iOS Simulator.

```text
Dannys-MacBook:~ danny$ flutter --version
Flutter 0.1.6-pre.3 • channel master • https://github.com/flutter/flutter.git
Framework • revision 7f03b9e41b (25 hours ago) • 2018-02-23 12:49:57 -0800
Engine • revision ead227f118
Tools • Dart 2.0.0-dev.28.0.flutter-0b4f01f759
```

### PR DESCRIPTION
**Pull request by jason-simmons**
Fixes https://github.com/flutter/flutter/issues/14864

### CODE REVIEW

**Comment by jason-simmons** [comment]
@goderbauer

**Review by goderbauer — APPROVED** [review]
LGTM

Can you add a test where an asset uses a reserved character?

**Comment by jason-simmons** [comment]
Added a test

**Review by goderbauer — APPROVED** [review]
LGTM

**Pull request merged**
