### PR TITLE
Add `keyLog` and `connectionFactory` to HttpClient implementations

### PR DESCRIPTION
**Pull request by brianquinlan**
Add two setters that will be added in Dart 2.7:
  https://github.com/dart-lang/sdk/issues/48093
  https://github.com/dart-lang/sdk/issues/47887

One this PR is merged, my plan is to fill another issue (assigned to myself) to remove the `// ignore: override_on_non_overriding_member` comments when the engine has been updated to Dart 2.17.

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Comment by brianquinlan** [comment]
Hey @zanderso , can I submit this now or should I get test approval from @Hixie ?

**Comment by zanderso** [comment]
Yes get approval.

**Comment by Hixie** [comment]
test-exempt: fixes tests that would otherwise break in the future

**Comment by brianquinlan** [comment]
@zanderso I don't have write access to this repository - could you press the merge button?

**Review by aam — APPROVED** [review]

**Pull request merged**
