### PR TITLE
Revert "move compile/target sdk versions to 29"

### PR DESCRIPTION
**Pull request by jonahwilliams**
Reverts flutter/flutter#62799

Multiple devicelab machines are failing to download android-29 sources:

```
2020-08-04T10:52:24.777007: stdout: [+1388 ms] Checking the license for package Android SDK Platform 29 in /usr/local/share/android-sdk/licenses
2020-08-04T10:52:24.777794: stdout: [   +1 ms] License for package Android SDK Platform 29 accepted.
stdout: [        ] Preparing "Install Android SDK Platform 29 (revision: 4)".
2020-08-04T10:52:24.778500: stdout: [        ] Warning: Failed to read or create install properties file.
2020-08-04T10:52:24.780064: stderr: [   +1 ms] FAILURE: Build failed with an exception.
2020-08-04T10:52:24.780452: stderr: [        ] * What went wrong:
2020-08-04T10:52:24.780821: stderr: [        ] Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
2020-08-04T10:52:24.781139: stderr: [        ] > Failed to install the following SDK components:
2020-08-04T10:52:24.781452: stderr: [        ]       platforms;android-29 Android SDK Platform 29
2020-08-04T10:52:24.781884: stderr: [        ]   Install the missing components using the SDK manager in Android Studio.
2020-08-04T10:52:24.782407: stderr: [        ] * Try:
2020-08-04T10:52:24.783440: stderr: [        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
stderr: [        ] * Get more help at https://help.gradle.org
2020-08-04T10:52:24.784339: stderr: [        ] BUILD FAILED in 1s
2020-08-04T10:52:25.227565: stdout: [ +443 ms] Running Gradle task 'assembleDebug'... (completed in 1.9s)
2020-08-04T10:52:25.235111: stdout: [   +7 ms] "flutter drive" took 4,801ms.
2020-08-04T10:52:25.241076: stderr: [   +6 ms] Gradle task assembleDebug failed with exit code 1
```

### CODE REVIEW

**Comment by jonahwilliams** [comment]
@xster

**Comment by xster** [comment]
LGTM

**Review by jmagman — APPROVED** [review]

**Comment by jonahwilliams** [comment]
Landing on red to fix build

**Comment by blasten** [comment]
The SDK needs to be installed in the host via `sdkmanager "platform-tools" "platforms;android-29"`.   cc @godofredoc for the infra dependency.

We should probably update `flutter doctor`, so it accounts for this new requirement prior to running `flutter create`/`flutter build`.

**Comment by godofredoc** [comment]
Android in devicelab machines is manually provisioned.

**Pull request merged**
