### PR TITLE
Add VSCode to ide-config command

### PR DESCRIPTION
**Pull request by gspencergoog**
## Description

The `flutter ide-config` command has long been just for IntelliJ.  This PR makes it also support creating a default `launch.json` for VSCode.

This is just for Flutter developers working on the Flutter tree, and for people who want to run examples from the flutter tree.

It also adds it to the downloadable Flutter package so that the `.vscode` directory is setup by default when Flutter is unpacked.

## Tests

- Added a test to make sure the .vscode/launch.json gets created.

## Breaking Change

- [X] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Based on https://docs.google.com/document/d/1pfKtCacd3pJjpl9koNwuuhbMTHLcRPHzf9xPIIj4FTk/edit we should not be adding more developer only tooling to the flutter command.

I did not add ide-config to the list, but that should probably be on there

**Comment by gspencergoog** [comment]
So, what's the plan, then, moving the non-end-user functionality to a separate tool?

At the least, these configurations should be generated by the `prepare_package.dart` script, even if it's not part of the flutter command.

**Comment by gspencergoog** [comment]
OK, I added ide-config to the list.  I'll close this, and we can come back to it if we decide the code is useful.

**Comment by jonahwilliams** [comment]
I think it is useful, I just would like to have more of a distinction between developer tooling code and end user tooling code.  The latter needs to have stricter and stricter standards for testing and coverage so we can keep our quality bar up, but that gets harder if its mixed in with functionality that only needs to work for a few hundred people at mist

**Comment by gspencergoog** [comment]
Yeah, I totally understand the motivation, no worries. I just meant "useful for whatever resolution we come to".  As in, if we decide to move the functionality to the package preparation script, we might want to include the logic in this PR so we get VSCode support too.

**Pull request closed without merging**
