### PR TITLE
[unrevert] TextField border gap padding improvement

### LINKED ISSUE #82321: TextField with rounded corners - floating label shows extra whitespace
This is a similar issue as #33948.

I need my `TextField` (or `TextFormField`) to have rounded corners in order to match my company's design:

(picture taken from Vue.js application)
Screenshot 2021-05-12 at 08 29 33

I successfully achieved it by setting all the borders of the `TextField`'s `InputDecoration` to:
```dart
OutlineInputBorder(
  borderRadius: BorderRadius.circular(32.0),
)
```

However, the problem I face is that the floating label (which is especially needed for the desired design) is looking strange in my Flutter app:

Screenshot 2021-05-12 at 08 25 17

It has too much whitespace around it. When decreasing the border radius e.g. to `8.0`, the floating label displays fine. But I need it to be `32.0` in order to be completely round.

<details>
  <summary>Code to reproduce it</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final border = OutlineInputBorder(
    borderRadius: BorderRadius.circular(32.0),
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text("TextField test")),
        body: Container(
          alignment: Alignment.center,
          padding: const EdgeInsets.all(16.0),
          child: TextField(
            obscureText: true,
            decoration: InputDecoration(
              labelText: "Password",
              focusedBorder: border,
              enabledBorder: border,
              errorBorder: border,
              border: border,
              disabledBorder: border,
              focusedErrorBorder: border,
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>flutter doctor</summary>

```
   Doctor summary (to see all details, run flutter doctor -v):
  [✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en-GB)
  [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
  [✓] Xcode - develop for iOS and macOS
  [✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome)
      ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
  [✓] Android Studio (version 4.2)
  [✓] VS Code (version 1.56.0)
  [✓] Connected device (1 available)
  
  ! Doctor found issues in 1 category.
```
</details>

### PR DESCRIPTION
**Pull request by justinmc**
Reverts flutter/flutter#93925, which was itself a revert of https://github.com/flutter/flutter/pull/92940.

The PR fixes the gap in the TextField border around the label, but see the original PR for more details.

The revert was because of a failed golden test.  I suspect a problem with gold itself caused it but I'm not sure.  I'll try to make sure all the golden tests pass here and then double check with @Piinks.

Closes https://github.com/flutter/flutter/issues/82321

### CODE REVIEW

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 1.
View them at https://flutter-gold.skia.org/cl/github/93933

**Review by LongCatIsLooong — APPROVED** [review]

**Comment by justinmc** [comment]
@werainkhatri This seems to work fine with your floatingLabelAlignment.

Screen Shot 2021-11-23 at 2 45 50 PM

There can sometimes be a gap when the label is ellided, but I don't think that's a problem with either of our PRs.

Screen Shot 2021-11-23 at 2 46 00 PM

I'll merge this when it's green and the goldens pass.

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/93933

**Comment by skia-gold** [comment]
Gold has detected about 1 new digest(s) on patchset 3.
View them at https://flutter-gold.skia.org/cl/github/93933

**Comment by justinmc** [comment]
The failing Google tests are the expected tiny pixel differences caused by the math here.  I'll set them to passing and plan to merge this.  After merge any Google tests that fail on unnoticeable changes to the border can be accepted.

**Pull request merged**
