### PR TITLE
implement Iterator and Comparable instead of extending them

### LINKED ISSUE #123281: Flutter should `implement` and not `extend` the `Iterable` and `Comparable` classes
Related to https://dart-review.googlesource.com/c/sdk/+/289826

These are only meant to be implemented and not extended.

### PR DESCRIPTION
**Pull request by jakemac53**
Update some places to `implement` versus `extend` the `Iterator` and `Comparable` classes.

Fixes https://github.com/flutter/flutter/issues/123281.

This is in preparation for https://dart-review.googlesource.com/c/sdk/+/289826.

cc @Hixie can I get a test exemption? No new functionality, this would only result in static analysis failures if there was an issue.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: fixing future compile error

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by jakemac53** [comment]
I did just update one more place, just fyi :)

**Review by goderbauer — APPROVED** [review]
Still LGTM

**Comment by jakemac53** [comment]
@goderbauer I am seeing unrelated failures from Tap in the google roll ("Could not find an option named "sound-null-safety".). How should I proceed?

**Comment by goderbauer** [comment]
I saw those failures on my PR this morning was well. I am hoping that a rebase will fix them, if not, maybe @CaseyHillers or @itsjustkevin can advice if we can just ignore those and set the status to green on this pretty low risk PR.

**Comment by jakemac53** [comment]
If we could just land that would be great, this is about as low risk as possible and is blocking other high priority changes.

**Comment by CaseyHillers** [comment]
You can ignore the Google Testing failures. Those are unrelated to your PR

**Pull request merged**
