### PR TITLE
[flutter_tools] better message when origin points to a fork

### PR DESCRIPTION
**Pull request by asashour**
Part of #14120

This PR triggers `git remote -v`, and to check the `origin` URL.

If URL is pointing to a fork, print `origin repository does not point to https://github.com/flutter/flutter`
If no `origin`: print the original message `no origin repository configured.`

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by christopherfujino — CHANGES_REQUESTED** [review]
Thanks for submitting this PR. However, please note that a similar PR was recently landed in https://github.com/flutter/flutter/pull/79372 but reverted because of https://github.com/flutter/flutter/issues/83373. Any attempt to land this kind of fix will have to do so in a way that does not block the plugins repo.

**Comment by asashour** [comment]
I see, how about if we look for only `github.com/flutter/flutter`, I believe this would also work with `plugins.`

**Comment by christopherfujino** [comment]
> I see, how about if we look for only `github.com/flutter/flutter`, I believe this would also work with `plugins.`

No, that would not work, please see this comment on the issue: https://github.com/flutter/flutter/issues/83373#issuecomment-848393213

**Comment by asashour** [comment]
I read the comment, but both `https://chromium.googlesource.com/a/external/github.com/flutter/flutter` and `https://chromium.googlesource.com/external/github.com/flutter/flutter` contain `github.com/flutter/flutter`

We can search for even only `flutter/flutter`.

Or is it something I miss?

**Comment by christopherfujino** [comment]
> I read the comment, but both `https://chromium.googlesource.com/a/external/github.com/flutter/flutter` and `https://chromium.googlesource.com/external/github.com/flutter/flutter` contain `github.com/flutter/flutter`
> 
> We can search for even only `flutter/flutter`.
> 
> Or is it something I miss?

Ahh I see, that's a good point. I'm not sure if we should rely on this, however, as its coincidental and an implementation detail. @stuartmorgan WDYT?

**Comment by stuartmorgan** [comment]
> I'm not sure if we should rely on this, however, as its coincidental and an implementation detail. @stuartmorgan WDYT?

It's not just an implementation detail, but an implementation detail of an image whose creation process we do not control (as the Flutter installation comes from the Cirrus base image). So not only could it change at any time, but we wouldn't even be able to undo the change to fix the issue. So we should definitely not rely on it.

I think if adding this check is important the right way to move forward with it is probably to have an environment variable that disables the check; we can set that in our CI scripts to avoid triggering the check.

**Comment by christopherfujino** [comment]
> > I'm not sure if we should rely on this, however, as its coincidental and an implementation detail. @stuartmorgan WDYT?
> 
> It's not just an implementation detail, but an implementation detail of an image whose creation process we do not control (as the Flutter installation comes from the Cirrus base image). So not only could it change at any time, but we wouldn't even be able to undo the change to fix the issue. So we should definitely not rely on it.

This issue is unrelated to Cirrus, the problem is that the LUCI builds clone the framework from googlesource.com

> I think if adding this check is important the right way to move forward with it is probably to have an environment variable that disables the check; we can set that in our CI scripts to avoid triggering the check.

I agree

**Comment by christopherfujino** [comment]
Although, as discussed in the issue, I also agree that plugins repo should not be depending on flutter upgrade but use git directly, as flutter upgrade was never intended for use on CI.

**Comment by stuartmorgan** [comment]
I'm fine with us changing how flutter/plugins and flutter/packages set the channel; it should be straightforward.

> This issue is unrelated to Cirrus, the problem is that the LUCI builds clone the framework from googlesource.com

Sorry, I forgot the breakage was for the Windows bot.

**Comment by christopherfujino** [comment]
Thanks for this contribution. However, we cannot land this change until https://github.com/flutter/flutter/issues/83373 is resolved. I am thus closing this PR for now.

**Comment by stuartmorgan** [comment]
It should be safe to land this or reland https://github.com/flutter/flutter/pull/79372 now; flutter/plugins is no longer using `upgrade` on either LUCI or Cirrus.

**Comment by asashour** [comment]
Thanks for your follow up. I can create a new PR with same changes, but someone should decide which one (this or #79372).

**Comment by christopherfujino** [comment]
I would prefer #79372, as it went through code review. This change is NOT ready to land as is. @RoyARG02 are you interested in re-introducing your change?

**Comment by RoyARG02** [comment]
> I would prefer #79372, as it went through code review. This change is NOT ready to land as is. @RoyARG02 are you interested in re-introducing your change?

Sure. I would need some time to update the change against the current master, though.

**Comment by RoyARG02** [comment]
> > I would prefer #79372, as it went through code review. This change is NOT ready to land as is. @RoyARG02 are you interested in re-introducing your change?
> 
> Sure. I would need some time to update the change against the current master, though.

Reland: #87731

**Pull request closed without merging**
