### PR TITLE
Adjust test to tolerate additional trace fields

### PR DESCRIPTION
**Pull request by zanderso**
For https://github.com/flutter/flutter/issues/116910

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM!

**Review by CoderDake — APPROVED** [review]
Nice!

**Review by christopherfujino — APPROVED** [review]
LGTM

**Review by bkonyi — APPROVED** [review]

**Comment by zanderso** [comment]
Landing manually. g3 tests have passed, but info isn't propagating quickly.

**Pull request merged**
