### PR TITLE
Put shaders under a 'shaders' section in the manifest

### PR DESCRIPTION
**Pull request by zanderso**
This is a step towards no longer identifying shaders that need compilation by way of the `.frag` extension.

### CODE REVIEW

**Comment by zanderso** [comment]
@jonahwilliams @christopherfujino Thoughts on introducing `AssetKind` to signal that a transform is needed? Maybe ideally `AssetKind` would be a class instead of an enum, and the class could encode how the asset needs to be transformed, but that might be overkill at the moment.

**Comment by jonahwilliams** [comment]
I like it

> Thoughts on introducing AssetKind to signal that a transform is needed? Maybe ideally AssetKind would be a class instead of an enum

YAGNI. If it gets too unwieldy for whatever reason we can refactor.

**Review by jonahwilliams — APPROVED** [review]
LGTM!

**Comment by zanderso** [comment]
FRoB isn't running on pre-merge PRs at the moment, so I expect that this will need some follow-up after it runs post-merge.

**Comment by CaseyHillers** [comment]
> FRoB isn't running on pre-merge PRs at the moment, so I expect that this will need some follow-up after it runs post-merge.

Is there a bug for this? I wasn't aware presubmit testing was broken \cc @XilaiZhang @muditatandon it might be related to b/236975711

**Pull request merged**
