### PR TITLE
Roll Engine from 9ce1e5c5c7e7 to ec8c9b0e01b7 (44 revisions)

### PR DESCRIPTION
**Pull request by engine-flutter-autoroll**
Roll Engine from 9ce1e5c5c7e7 to ec8c9b0e01b7 (44 revisions)

https://github.com/flutter/engine/compare/9ce1e5c5c7e7...ec8c9b0e01b7

2020-05-21 skia-flutter-autoroll@skia.org Roll Dart SDK from ecce58c1e354 to 396b5fb7a97d (2 revisions) (flutter/engine#18560)
2020-05-21 skia-flutter-autoroll@skia.org Roll Fuchsia Mac SDK from RNByJ... to _zNmv... (flutter/engine#18558)
2020-05-21 st.krwlng@gmail.com [profiling] Memory Profiling support for iOS (flutter/engine#18516)
2020-05-21 skia-flutter-autoroll@skia.org Roll Skia from 22636205ce92 to b37105ea6cca (2 revisions) (flutter/engine#18557)
2020-05-21 skia-flutter-autoroll@skia.org Roll Dart SDK from d551980ac9fc to ecce58c1e354 (2 revisions) (flutter/engine#18556)
2020-05-21 skia-flutter-autoroll@skia.org Roll Dart SDK from bf7e9d13d730 to d551980ac9fc (6 revisions) (flutter/engine#18551)
2020-05-21 skia-flutter-autoroll@skia.org Roll Skia from 4c0578632217 to 22636205ce92 (4 revisions) (flutter/engine#18550)
2020-05-21 skia-flutter-autoroll@skia.org Roll Fuchsia Linux SDK from ThMeW... to ciqRH... (flutter/engine#18549)
2020-05-21 skia-flutter-autoroll@skia.org Roll Skia from 67ff541ac116 to 4c0578632217 (1 revision) (flutter/engine#18547)
2020-05-21 xster@google.com Let run_tests.py just stream output (flutter/engine#18534)
2020-05-21 robert.ancell@canonical.com Add FlKeyEventPlugin (flutter/engine#18313)
2020-05-21 mehmetf@users.noreply.github.com Add tests for StandardMethodCodec (flutter/engine#18521)
2020-05-21 skia-flutter-autoroll@skia.org Roll Skia from f83baf230c69 to 67ff541ac116 (1 revision) (flutter/engine#18545)
2020-05-21 skia-flutter-autoroll@skia.org Roll Fuchsia Mac SDK from 3o9aQ... to RNByJ... (flutter/engine#18543)
2020-05-21 dworsham@google.com fuchsia: Fix runtime_tests and shell_tests (flutter/engine#18492)
2020-05-21 skia-flutter-autoroll@skia.org Roll Skia from d2dc8ddcdf5e to f83baf230c69 (2 revisions) (flutter/engine#18539)
2020-05-21 skia-flutter-autoroll@skia.org Roll Dart SDK from 7aa8656d1dd8 to bf7e9d13d730 (21 revisions) (flutter/engine#18538)
2020-05-21 robert.ancell@canonical.com Add FlMethodChannel, FlMethodCodec, FlStandardMethodCodec and FlJsonMethodCodec (flutter/engine#18220)
2020-05-20 ferhat@gmail.com [web] Fix arc rendering when it starts a new sub path. (flutter/engine#18535)
2020-05-20 garyq@google.com Send platformResolvedLocale from iOS embedder (flutter/engine#18519)
2020-05-20 dkwingsmt@users.noreply.github.com System mouse cursor: macOS (flutter/engine#18131)
2020-05-20 skia-flutter-autoroll@skia.org Roll Skia from 656ee7bc0fd2 to d2dc8ddcdf5e (2 revisions) (flutter/engine#18537)
2020-05-20 robert.ancell@canonical.com Make FlBasicMessageChannelResponseHandle a GObject to detect unresponded and double responded messages. (flutter/engine#18514)
2020-05-20 dkwingsmt@users.noreply.github.com System mouse cursor: Web (flutter/engine#17718)
2020-05-20 ferhat@gmail.com [web] Reuse ImageElement(s) across frames (flutter/engine#18437)
2020-05-20 skia-flutter-autoroll@skia.org Roll Skia from 3e84312c0f4d to 656ee7bc0fd2 (8 revisions) (flutter/engine#18536)
2020-05-20 skia-flutter-autoroll@skia.org Roll Dart SDK from d2ee73b2513c to 7aa8656d1dd8 (12 revisions) (flutter/engine#18533)
2020-05-20 zhongwuzw@qq.com Fixes Semantic Object memory leak cause of wrong release call (flutter/engine#18107)
2020-05-20 gw280@google.com Set caches directory on Fuchsia (flutter/engine#18321)
2020-05-20 iska.kaushik@gmail.com [fuchsia] Remove SceneDisplayLag event on Fuchsia (flutter/engine#18515)
2020-05-20 skia-flutter-autoroll@skia.org Roll Skia from 682fca92996b to 3e84312c0f4d (3 revisions) (flutter/engine#18530)
2020-05-20 xster@google.com Move robolectric tests to sdk 28 (flutter/engine#18525)
2020-05-20 skia-flutter-autoroll@skia.org Roll Skia from 9d52ac1573f1 to 682fca92996b (1 revision) (flutter/engine#18529)
2020-05-20 skia-flutter-autoroll@skia.org Roll Fuchsia Mac SDK from fCHnB... to 3o9aQ... (flutter/engine#18528)
2020-05-20 skia-flutter-autoroll@skia.org Roll Dart SDK from 9807b83d5945 to d2ee73b2513c (5 revisions) (flutter/engine#18526)
2020-05-20 skia-flutter-autoroll@skia.org Roll Fuchsia Linux SDK from 73IKT... to ThMeW... (flutter/engine#18527)
2020-05-20 skia-flutter-autoroll@skia.org Roll Skia from 34eee0d9fc85 to 9d52ac1573f1 (3 revisions) (flutter/engine#18524)
2020-05-20 skia-flutter-autoroll@skia.org Roll Dart SDK from 3a764b7ae4d9 to 9807b83d5945 (3 revisions) (flutter/engine#18523)
2020-05-20 skia-flutter-autoroll@skia.org Roll Skia from 3bcb7bb01b82 to 34eee0d9fc85 (1 revision) (flutter/engine#18522)
2020-05-20 zhongwuzw@qq.com Fix iOS platform view not deallocated (flutter/engine#18164)
2020-05-20 skia-flutter-autoroll@skia.org Roll Skia from 5e6d789ce47c to 3bcb7bb01b82 (1 revision) (flutter/engine#18518)
2020-05-20 garyq@google.com Remove currentLocale prepend on iOS (flutter/engine#18379)
2020-05-20 skia-flutter-autoroll@skia.org Roll Dart SDK from 7706afbcf5c6 to 3a764b7ae4d9 (33 revisions) (flutter/engine#18517)
2020-05-20 skia-flutter-autoroll@skia.org Roll Skia from ac007669ee71 to 5e6d789ce47c (4 revisions) (flutter/engine#18513)

Also rolling transitive DEPS:
...

### CODE REVIEW

**Comment by engine-flutter-autoroll** [comment]
Commit queue failed; closing this roll.

**Comment by liyuqian** [comment]
@DanTup , the failure seems to be caused by your golden tests. Should the golden images be updated, or is there some problem that we need to fix in the engine?

**Comment by DanTup** [comment]
@liyuqian I'm not sure. There was an issue a few weeks ago that @jason-simmons resolved because there were changes that affected the golden images, but I'm not sure whether this failure is related. I think the tests will need running against the new engine (locally) to review the differences - I'll see if I can do that locally by just changing these hashes.

**Comment by DanTup** [comment]
I've no idea what's happend here, but this is the diff GitHub Desktop shows when I regenerate goldens with those hashes (and I've confirmed what's shown on the right is what the file looks like on disk):

Untitled

However, that doesn't seem to match what Flutter wrote into the "failures" folder, for example:

tileset_windows_isolatedDiff

That looks a lot less concerning. I'm not sure what's going on here!

**Comment by DanTup** [comment]
Oh wait, I think those red renderings are the red error screen! I do get some errors written out when running this, I'll see what's going on!

**Comment by DanTup** [comment]
Ok, the big red error images were because of bad paths (I ran `flutter test` instead of `flutter test test` and that affects the `cwd`).

The actual changes are much more subtle (like tiny little variations in pixel color - perhaps due to compression). [Here's a zip of the failure files](https://github.com/flutter/flutter/files/4684668/changes.zip)

I've commited the new versions to the repo here:

https://github.com/DanTup/tiler/commit/44b41536e7428d1070e8e2bd91376132c5a484fc

However the hash will need to be updated in [flutter/tests](https://github.com/flutter/tests/blob/master/registry/DanTup_tiler.test), and I don't think there's a way to do that atomically with an engine roll (so you may need to [temporarily disable them](https://github.com/flutter/tests/pull/36) and then restore with the new hash after landing the engine change).

**Pull request closed without merging**
