### PR TITLE
Replace FLUTTER_MODULE_TYPE with WEB_MODULE in dev/manual_tests/* and examples/* iml files

### PR DESCRIPTION
**Pull request by jwren**
This change is being staged to be in coordination with https://github.com/flutter/flutter-intellij/pull/1213

### CODE REVIEW

**Comment by jwren** [comment]
@devoncarew @pq

**Comment by devoncarew** [comment]
lgtm; let's wait to land this until M16 of the Flutter plugin has been out for a little bit.

**Comment by cbracken** [comment]
lgtm

**Review by cbracken — APPROVED** [review]

**Comment by cbracken** [comment]
This appears to have broken in the same way both on Travis and the Mac Chromebot. I'm not entirely sure *why* this change should have affected these but in both cases, `test/commands/create_test.dart: create project` failed. 

Wondering if it could be a flake due to a pub timeout?

**Comment by devoncarew** [comment]
I did just sync to master and ran the tests - these do pass locally.

**Comment by cbracken** [comment]
Bots are looking happier on re-run.

**Comment by postmasters** [comment]
Looks like the templates need fixed too?

```
git grep FLUTTER_MODULE_TYPE
packages/flutter_tools/templates/create/projectName.iml.tmpl:<module type="FLUTTER_MODULE_TYPE" version="4">
packages/flutter_tools/templates/plugin/projectName.iml.tmpl:<module type="FLUTTER_MODULE_TYPE" version="4">
```

**Pull request merged**
