### PR TITLE
v1.12.13+hotfix.3 cherry-picks

### PR DESCRIPTION
**Pull request by tvolkert**
* flutter/engine@ac93919 v1.12.13+hotfix.3 cherry-picks
  * flutter/engine@73da385 Disable a11y on detach
* d88345e only run codecov on master
* 6d848eb Name the docker_builer shard
* e98acc7 [flutter_tool] Print version info on a no-op upgrade
* 8eb6a92 Always compile with isysroot on iOS to point to SDK root
* fb69a39 Add bitcode and architectures to App.framework build ios framework command

### CODE REVIEW

**Comment by tvolkert** [comment]
@jmagman there were merge conflicts when merging fb69a39, so please have a look and make sure it looks good.

**Review by jmagman — APPROVED** [review]
https://github.com/flutter/flutter/commit/fb69a393b886aa91d30b81f79a590653fb677a4b part LGTM
Thanks, @tvolkert!

**Review by zanderso — APPROVED** [review]
lgtm

**Review by dnfield — APPROVED** [review]
LGTM.  @jmagman is the test failure related to changes you made?

**Comment by jmagman** [comment]
> @jmagman is the test failure related to changes you made?
```
stderr: ld: building for iOS, but linking in object file (/private/var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/flutter_module_test.QcOdS3/hello/build/ios/framework/Profile/iphoneos/arm64/snapshot_assembly.o) built for macOS
```

Yes, but actually another really bad bug already fixed in v1.13.0, exposed I believe by setting `isysroot` in this change but not where `snapshot_assembly.o` is `cc`'d.

https://github.com/flutter/flutter/pull/45436 (specifically line https://github.com/flutter/flutter/commit/6b11f18bc0c5a53753d1dc92928ec8ba1bdc5f95#diff-77d60a41797d03aa9a7de0c742b17ef1R254)

@tvolkert should we grab that change, too?  Or do you want me to clean this up to the minimum possible fix?

**Comment by jmagman** [comment]
> https://github.com/flutter/flutter/pull/45436

I assume that was the merge conflict, too.

**Comment by tvolkert** [comment]
Yeah that was the merged conflict.  I applied it here (technically https://github.com/flutter/flutter/pull/45560)

PTAL

**Review by jmagman — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
