### PR TITLE
Remove a sketchy override of a field

### PR DESCRIPTION
**Pull request by Hixie**
The way this was implemented is sketchy, especially in strong mode.

### CODE REVIEW

**Comment by Hixie** [comment]
Though maybe the right way to do this is just to have a virtual method?

**Comment by Hixie** [comment]
@devoncarew

**Comment by devoncarew** [comment]
I believe this was only a field so the validator could be toggled off for testing:

- https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/runner/flutter_command.dart#L206
-https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/src/mocks.dart#L74

almost certainly cleaner ways to do it :) lgtm

**Comment by Hixie** [comment]
Ah, that makes sense.

**Pull request merged**
