### PR TITLE
Expose textAlign on TextFormField

### LINKED ISSUE #11404: TextFormField should expose textAlign property
I have a need for a TextFormField that displays center-aligned text.

It seems like the class itself (text_form_field.dart) does not expose the textAlign property of the underlying TextField.

Would this be possible to add?

### PR DESCRIPTION
**Pull request by fredriks**
Fixes #11404

### CODE REVIEW

**Comment by Hixie** [comment]
This seems reasonable but we should probably have a test to make sure it works as expected (and more importantly, to make sure we don't accidentally remove it one day while "cleaning up"!)

cc @HansMuller who is working on text fields.
cc @cbracken who has worked on TextFormField recently.

**Comment by fredriks** [comment]
Right, sound good! I took inspiration from [text_form_field_demo_test.dart](https://github.com/flutter/flutter/blob/60effb993cc23597a44707ac84432ae9f9f781dd/examples/flutter_gallery/test/demo/material/text_form_field_demo_test.dart) and [text_field_test.dart](https://github.com/flutter/flutter/blob/60effb993cc23597a44707ac84432ae9f9f781dd/packages/flutter/test/material/text_field_test.dart) to setup a test case.

Since this is my first patch to Flutter I'm not sure about the testing practices so let me know if something is off 😄

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
Thanks!

**Pull request merged**
