### PR TITLE
Use Flutter app project's NDK version from FFI plugin

### PR DESCRIPTION
**Pull request by temeddix**
image

In most cases, a FFI plugin doesn't need its own specific Android NDK version. Just following the Flutter app project's NDK version is enough.

If a Flutter app project depends on multiple FFI plugins that use different Android NDK versions, it can be quite wasteful and use excessive disk space due to multiple NDK installations.

Using Flutter app project's NDK version is also less error-prone because upgrading the Flutter SDK would be enough when upgrading FFI plugins(If project's `ndkVersion` is `flutter.ndkVersion`), without messing with Android NDK installations.

This problem was discussed in some actual FFI plugin repositories, and they are striving to find their own solutions:
- https://github.com/superlistapp/super_native_extensions/issues/143#issuecomment-1646207706
- https://github.com/cunarist/rust-in-flutter/discussions/60#discussioncomment-6484218
- https://github.com/rive-app/rive-flutter/issues/320
- https://github.com/juicycleff/flutter-unity-view-widget/issues/832

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: configuration change

**Comment by temeddix** [comment]
It's strange that `Linux web_canvaskit_tests_1` is not passing. I didn't modify any files related to Linux and web.

**Comment by christopherfujino** [comment]
@dcharkes is this a safe change to make?

**Comment by dcharkes** [comment]
Here is all the discussion on it when landing support for FFI plugins: [NDK versioning doc](https://docs.google.com/document/d/1sljfqHpI5m4uxsL7B89yhYluO97Mz1YKyA0VgzzXyZ4/edit?usp=sharing&resourcekey=0-Ts9Rk8jbJor7WBMMiehKWg).

Reading the doc and comments, we went for specifying the value in the plugin so that the plugins specify a lower bound and added logic to check that the app NDK version as at least as new as the plugins. If plugin authors still need a lower bound they can follow the comment that is added to the template.

> In most cases, a FFI plugin doesn't need its own specific Android NDK version.

In the mentioned doc we note the same.

I believe this change to be safe. (Plugin authors who do need an NDK lower bound to read that comment and manually put in an NDK version, or their example app will immediately fail if it lists a too low NDK version.)

**Review by dcharkes — APPROVED** [review]

**Comment by christopherfujino** [comment]
> Here is all the discussion on it when landing support for FFI plugins: [NDK versioning doc](https://docs.google.com/document/d/1sljfqHpI5m4uxsL7B89yhYluO97Mz1YKyA0VgzzXyZ4/edit?usp=sharing&resourcekey=0-Ts9Rk8jbJor7WBMMiehKWg).
> 
> Reading the doc and comments, we went for specifying the value in the plugin so that the plugins specify a lower bound and added logic to check that the app NDK version as at least as new as the plugins. If plugin authors still need a lower bound they can follow the comment that is added to the template.
> 
> > In most cases, a FFI plugin doesn't need its own specific Android NDK version.
> 
> In the mentioned doc we note the same.
> 
> I believe this change to be safe. (Plugin authors who do need an NDK lower bound, need to read that comment and manually put in an NDK version, or their example app will immediately fail if it lists a too low NDK version.)

Thanks

**Review by christopherfujino — APPROVED** [review]
LGTM

**Comment by temeddix** [comment]
@christopherfujino It looks like auto label was remove due to this error https://github.com/flutter/flutter/pull/131141#issuecomment-1656187180. Would you mind handling this again?

**Pull request merged**
