### PR TITLE
Manual roll camera dependency

### PR DESCRIPTION
**Pull request by goderbauer**
Supersedes https://github.com/flutter/flutter/pull/148245

### CODE REVIEW

**Comment by goderbauer** [comment]
Looks like just removing that extra dependency is not enough. Now there are other gradle errors.

**Comment by stuartmorgan** [comment]
Buried in the output is:

```
┌─ Flutter Fix ───────────────────────────────────────────────────────────────────────────────┐
│ You need to update the lockfile, or disable Gradle dependency locking.                      │
│ To regenerate the lockfiles run: `./gradlew :generateLockfiles` in                          │
│ /b/s/w/ir/x/w/flutter/dev/integration_tests/gradle_deprecated_settings/android/build.gradle │
│ To remove dependency locking, remove the `dependencyLocking` from                           │
│ /b/s/w/ir/x/w/flutter/dev/integration_tests/gradle_deprecated_settings/android/build.gradle │
└─────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by goderbauer** [comment]
Thanks, totally missed that in the output. The command fails, though:

```
% ./gradlew :generateLockfiles                                               manualCameraBump

Welcome to Gradle 8.3!

Here are the highlights of this release:
 - Faster Java compilation
 - Reduced memory usage
 - Support for running on Java 20

For more details see https://docs.gradle.org/8.3/release-notes.html

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :app
You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

w: file:///Users/goderbauer/dev/flutter/packages/flutter_tools/gradle/src/main/kotlin/dependency_version_checker.gradle.kts:107:40: Variable 'agpVersion' initializer is redundant
w: file:///Users/goderbauer/dev/flutter/packages/flutter_tools/gradle/src/main/kotlin/dependency_version_checker.gradle.kts:108:40: Variable 'kgpVersion' initializer is redundant
w: file:///Users/goderbauer/dev/flutter/packages/flutter_tools/gradle/src/main/kotlin/dependency_version_checker.gradle.kts:143:28: Parameter 'project' is never used
w: file:///Users/goderbauer/dev/flutter/packages/flutter_tools/gradle/src/main/kotlin/dependency_version_checker.gradle.kts:152:40: Variable 'agpVersion' initializer is redundant
w: file:///Users/goderbauer/dev/flutter/packages/flutter_tools/gradle/src/main/kotlin/dependency_version_checker.gradle.kts:167:55: 'Version' is deprecated. Deprecated in Java
w: file:///Users/goderbauer/dev/flutter/packages/flutter_tools/gradle/src/main/kotlin/dependency_version_checker.gradle.kts:195:56: Unnecessary non-null assertion (!!) on a non-null receiver of type Any
w: file:///Users/goderbauer/dev/flutter/packages/flutter_tools/gradle/src/main/kotlin/dependency_version_checker.gradle.kts:344:28: The corresponding parameter in the supertype 'Comparable' is named 'other'. This may cause problems when calling this function with named arguments.
Starting a Gradle Daemon, 1 busy and 1 incompatible Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not open proj generic class cache for build file '/Users/goderbauer/dev/flutter/dev/integration_tests/gradle_deprecated_settings/android/build.gradle' (/Users/goderbauer/.gradle/caches/8.3/scripts/c192y7qa3j8v1de05e2zs4p7).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 4s

FAILURE: Build failed with an exception.

* Where:
Script '/Users/goderbauer/dev/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 222

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not create task ':generateLockfiles'.
   > Process 'command '/Users/goderbauer/dev/flutter/dev/integration_tests/gradle_deprecated_settings/android/gradlew'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 18s
```

**Comment by stuartmorgan** [comment]
> Unsupported class file major version 66

IIRC that means your Java version isn't in the support range of your Gradle version. This isn't my area of expertise, but it looks from a skim of search results like this mean you are using Java 22, and the Gradle output sounds like it's only supporting 20 at that version.

@reidbaker may have suggestions on how to handle this (other than by installing an old version of Java)?

**Comment by goderbauer** [comment]
For future archeologists: 

@gmackall helped me out and instructed me to set my JAVA_HOME to the java version that shipped with the engine:

```
export JAVA_HOME=/Users/goderbauer/dev/engine/src/third_party/java/openjdk/Contents/Home
```

With that, the `./gradlew :generateLockfiles` run succeeded in regenerating the lock files. Now 🤞 that everything will pass on CI as well.

Thanks a ton for everyone's help with this one!

**Review by stuartmorgan-g — APPROVED** [review]
LGTM

**Comment by goderbauer** [comment]
Note to self: Remember to close https://github.com/flutter/flutter/pull/148245 when this is submitted to restart auto-roller.

**Pull request merged**
