### PR TITLE
Point to master API docs

### PR DESCRIPTION
**Pull request by sethladd**
I _think_ this is the right place, since people contributing and working on master might care about where the API docs are for master branch.

### CODE REVIEW

**Comment by sethladd** [comment]
cc @Hixie

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
Maybe also link to the "real" docs, in case this comes up in Google for someone looking for regular docs.

**Comment by sethladd** [comment]
Yeah, good point!!

**Pull request merged**
