### PR TITLE
widen quiver constraint

### LINKED ISSUE #6926: Support newer quiver version
```
 (master) $ flutter packages upgrade
Running 'flutter packages upgrade' in myapp...           
Incompatible version constraints on quiver:
- bwu_ng_mdl 0.1.0 depends on version ^0.22.0
- fhir_client 0.1.0 depends on version ^0.22.0
- flutter_test 0.0.0 depends on version ^0.21.4
pub upgrade failed (1)
```

### PR DESCRIPTION
**Pull request by zoechi**
fixes #6926

### CODE REVIEW

**Comment by abarth** [comment]
Looks like there are multiple places that have constraints on quiver.  Travis is red because it checks that everywhere we use a given package we end up with the same version of that package.

Looks like you need to update `packages/flutter_driver/pubspec.yaml` as well.

Also, rather than having such a wide range, we should just bump it to `^0.23.0`.  That way the testing matrix is smaller.

**Comment by Hixie** [comment]
Or just pin it...

**Comment by zoechi** [comment]
@abarth narrow ranges make all packages that don't allow the newest version yet incompatible with Flutter.

**Comment by Hixie** [comment]
We are eventually going to just pin all our dependencies (#6767), so that's going to become a general problem.

**Comment by zoechi** [comment]
You could use the `.pubspec.lock` file with `flutter packages get` to ensure you get specific versions of packages and use wider ranges in `pubspec.yaml` to not limit Flutter users

**Comment by abarth** [comment]
`.pubspec.lock` doesn't help us because it doesn't reduce the matrix of packages that we need to test against.

**Comment by zoechi** [comment]
Right, if you want to test against all combinations of package that are possible this is not helpful.

**Comment by sethladd** [comment]
@zoechi should we use `^0.23.0` or similar? Not sure what the latest version of Quiver is...

**Comment by zoechi** [comment]
@sethladd `^0.23.0` would narrow it down unnecessarily which could cause conflicts with other dependencies that don't yet support the newest quiver version. Only if there were breaking changes affecting Flutter it would be a good idea.
I think now it should be `quiver: '>=0.21.4 <0.25.0' (current version `0.24.0`)
Don't remember why I used `0.23.0`, I guess because that was the minimum version required to solve my conflict.

**Comment by sethladd** [comment]
We've been burned before when a dep changes and breaks our tools, so we're hesitant to use wide constraints. What version do you need to fix your conflict? ^0.24 would work?

**Comment by zoechi** [comment]
@sethladd I just use `dependency_overrides`, so it doesn't really matter to me. I just thought to spare others the time I used to debug the problem I create a PR.
It's your call, but as mentioned it's likely to cause other issues because quiver dependencies are not often updated in packages that use it, and all packages that use older quiver versions will be rendered unusable with Flutter until they are updated.

**Comment by sethladd** [comment]
Understood. I think we should try to be on latest narrow version of our dependencies, when possible. We should bump to ^0.24.0, IMO.

@abarth wdyt?

**Comment by Hixie** [comment]
Our plan, which used to be a long-term plan but now is probably at most medium term and may even become short term, is to pin all our dependencies (i.e. not have a range at all, but require one version). This is moving us away from that so I'd rather not do it.

**Comment by abarth** [comment]
Let's just upgrade our quiver.  I can give that a try.

**Comment by abarth** [comment]
Quiver update in https://github.com/flutter/flutter/pull/7349

**Comment by sethladd** [comment]
Thanks.

**Pull request closed without merging**
