### PR TITLE
Add missing const to BorderRadius.circular

### PR DESCRIPTION
**Pull request by MrAlek**
## Description

Adds `const` keyword to `BorderRadius.circular` constructor which in turn uses the already `const` `BorderRadius.all` constructor.

My own use case:

```dart
Widget build(BuildContext context) {
  const shape = RoundedRectangleBorder(borderRadius: BorderRadius.circular(12));
  return Card(
    shape: shape,
    child: InkWell(
      customBorder: shape
    )
  );
}
```

## Workarounds

Using `BorderRadius.all(Radius.circular(x))` which are both already declared `const`.

## Related Issues

None reported (could open one).

## Tests

None (could add with some guidance)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Comment by MrAlek** [comment]
I did see https://github.com/flutter/flutter/pull/52309 but the main problem noted there was `Radius.circular` not being `const`, which it is https://github.com/flutter/engine/blob/master/lib/ui/geometry.dart#L900

**Comment by MrAlek** [comment]
I see now that the Flutter analyzer complains about `Radius.circular` but as far as I can see, it has been declared `const` ever since its inception (https://github.com/flutter/engine/pull/2820/files#diff-551f8e8bf77581b0737426421e6a2c5aR686)

**Comment by chunhtai** [comment]
Radius.circular is const constructor, but `radius` might not be.

**Comment by MrAlek** [comment]
@chunhtai You're right, just very confused why it doesn't work in a constructor setting.

**Pull request closed without merging**
