### PR TITLE
[flutter tools] Change the desktop device names and IDs

### PR DESCRIPTION
**Pull request by jamesderlin**
In google3, the Linux device is always available, and it has confused
people who run the Flutter doctor and see
"• Linux • Linux • linux-x64 • Linux" listed.

Rename the Linux device name to "Linux desktop" and the device ID to
be "linux".  Make similar changes to the Windows and macOS
devices for consistency.

The device ID change shouldn't be break `-d` usage since that does a
case-insensitive prefix match.

## Related Issues

Internal b/153516059.

## Tests

None.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

I did need to modify existing tests, but my understanding is that flutter_tools does not strictly follow the breaking change policy.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

### CODE REVIEW

**Review by jonahwilliams — APPROVED** [review]
LGTM if LG to @stuartmorgan

**Comment by stuartmorgan** [comment]
> Rename the Linux device name to "Linux desktop"

This SGTM.

> and the device ID to "linux-embedding"

This seems awkward. What is the word "embedding" adding here that naming the device "desktop" doesn't already do? I suspect the vast majority of people using Flutter don't know this terminology.

**Comment by jamesderlin** [comment]
> > and the device ID to "linux-embedding"
> 
> This seems awkward. What is the word "embedding" adding here that naming the device "desktop" doesn't already do? I suspect the vast majority of people using Flutter don't know this terminology.

Fair enough.  I'll try to think of a better IDs.  I'd like to at least change them to "linux"/"windows"/"macos" to distinguish them from the OS name (and that seems more consistent with IDs for web devices).

**Comment by zanderso** [comment]
@jamesderlin Are you still working on this?

**Comment by jamesderlin** [comment]
@stuartmorgan I wasn't able to devise better device IDs, so I just went with lowercased "linux", "windows", and "macos".  Could you please take another look?

**Review by stuartmorgan-g — APPROVED** [review]

**Comment by devoncarew** [comment]
Hi - this PR has some negative UI implications for IDEs. We're now showing:

Screen Shot 2020-06-26 at 12 41 38 PM

in IntelliJ (note the 'desktop desktop' text in the device label).

I'd suggest instead doing something like using the device type in the in the `flutter devices` output to help differentiate between types of devices (and perhaps use `linux-device` as the ID, for a bit more differentiation from the device name).

**Comment by jamesderlin** [comment]
I like those suggestions.  I'll try them and mostly revert this.

**Pull request merged**
