### PR TITLE
Use api 34 for integration_test

### PR DESCRIPTION
**Pull request by gmackall**
Uses Math.max(34, flutter.compileSdkVersion) so that we don't fall behind if we don't update.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by goderbauer** [comment]
Why do we only do this for the integration_test example app and not all of them?

cc @reidbaker Is this the right thing to do from an Android perspective?

**Comment by reidbaker** [comment]
Replacing myself with @johnmccutchan for the next 3 weeks #tigerteam

**Comment by gmackall** [comment]
> Why do we only do this for the integration_test example app and not all of them?

My understanding is that we plan to make this change for other example apps as well. But those other example apps mostly live in the packages repo, so they would be an independent change.

> cc @reidbaker Is this the right thing to do from an Android perspective?

FWIW as I remember this was Reid's idea

**Comment by gmackall** [comment]
I'm going to close this for now, as we will soon update `flutter.compileSdkVersion`, and if we are going to do this we should probably do it in more than just one place

**Pull request closed without merging**
