### PR TITLE
Remove Mimic

### PR DESCRIPTION
**Pull request by abarth**
This widget isn't tested and isn't used by Fuchsia or internally by Google. The
Hero widget is a better way of generating hero animations.

### CODE REVIEW

**Comment by abarth** [comment]
@Hixie @apwilson

**Comment by Hixie** [comment]
I do point people to this widget occasionally. I'm surprised there are no current consumers that we have visibility on.

**Comment by abarth** [comment]
I don't see any usage.  I also don't think it's a particularly good widget.  :(

**Comment by Hixie** [comment]
*shrug* I don't have a strong opinion either way.

**Comment by apwilson** [comment]
LGTM

**Pull request merged**
