### PR TITLE
Set PUB_ENVIRONMENT during `pub upgrade` in flutter_tools

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by Hixie** [comment]
This is going to add 200ms (the cost of running a Dart program) to initial Flutter run. Probably not noticeable in the grand scheme of things since we're struggling with other issues involving downloading gigabytes of cocoapods, of course...

**Comment by abarth** [comment]
IMHO, we should just write this code in shell.

**Comment by kevmoo** [comment]
> IMHO, we should just write this code in shell.

Sure. I'm worried about getting the logic correct in bash (and terrified of breaking something in the batch file).

If someone wants to run with the "spirit" of this PR – using pure shell, I won't argue. 🤷‍♂️

**Comment by kevmoo** [comment]
Ping here @abarth @Hixie 

I'd LOVE to get this in. At the moment, I'm doing some crazy dependency parsing to try to detect this install path.

This is the "spirit" of what I want. Even making sure there is a 'flutter_install' item in `PUB_ENVIRONMENT` (while including anything that already exists) would be great.

**Comment by eseidelGoogle** [comment]
@abarth indicated he was interested in helping last week.  @abarth, the keys Kevin is seeking is "flutter_bot" and "flutter_install" being added to the PUB_ENVIRONMENT environment variable:
https://github.com/flutter/flutter/pull/9670/files#diff-a9281319daef652a1fe92d41ef515098R30

**Comment by kevmoo** [comment]
Pri 0: concat w/ existing environment (if any)
Pri 0: flutter_install
Pri 1: flutter_bot

**Comment by goderbauer** [comment]
@kevmoo Do you only want these values in the env for this one specific call to pub at the very beginning? Or all calls to pub that flutter issues (e.g. `flutter update-packages`)?

**Comment by kevmoo** [comment]
@goderbauer already handle those – https://github.com/flutter/flutter/commit/358e1cd2e171e81067c9728df7508f0e72a76c3f

**Comment by goderbauer** [comment]
I see. I can work on a PR to add those env vars from the shell scripts for that specific command.

**Comment by kevmoo** [comment]
> I see. I can work on a PR to add those env vars from the shell scripts for that specific command.

Awesome. Thanks!

**Comment by goderbauer** [comment]
See https://github.com/flutter/flutter/pull/9725.

**Comment by kevmoo** [comment]
Going with https://github.com/flutter/flutter/pull/9725

**Pull request closed without merging**
